### ISSUE TITLE
Optional chaining optimization

### ISSUE THREAD

**Issue by romulof** [babel/babel#10004]
## Feature Request

**Is your feature request related to a problem?**

Current implementation of `@babel/plugin-proposal-optional-chaining` works like this:
- Input:
```js
const street = user?.address?.street;
```
- Output:
```js
var _user, _user$address;
const street = (_user = user) === null || _user === void 0
    ? void 0
    : (_user$address = _user.address) === null || _user$address === void 0
        ? void 0
        : _user$address.street;
```

Chaining ternary operators works fine, but theres a certain use case where it can be optimised:
- Input:
```js
if (user?.address?.street) {
    console.log('Street:', user.address.street);
}
```
- Output:
```js
var _user, _user$address;
if ((_user = user) === null || _user === void 0 ? void 0 : (_user$address = _user.address) === null || _user$address === void 0 ? void 0 : _user$address.street) {
  console.log('Street:', user.address.street);
}
```

**Describe the solution you'd like**

Inside an `if` clause it only needs to check if the result is falsy or not. Transforming could be more space-efficient like this:
```js
if (user && user.address && user.address.street) {
    console.log('Street:', user.address.street);
}
```

**Describe alternatives you've considered**

I would only apply this optimisation for specific scenarios (`if` and `while`), and in case there's no additional operator/call:
```js
// Bail out. ternary chain works better here
if (user?.address?.street === 'some street') { ... }
```

**Teachability, Documentation, Adoption, Migration Strategy**

Make this optimisation optional at start, then make it a default, keeping a way to opt-out:
```json
{
    "plugins": [
        ["@babel/plugin-proposal-nullish-coalescing-operator", {
            "fasly-expression-optimisation: true/false
        }],
    ]
}
```

**Comment by nicolo-ribaudo** [comment]
We could do it only in loose mode, because this wouldn't work:
```js
let obj = { str: "" }

if (obj.str?.length !== 1) {
}
```

**Comment by tanhauhau** [comment]
@romulof something like this? https://github.com/babel/babel/pull/10012

**Comment by JLHwung** [comment]
Closing this issue as won't fix, see https://github.com/babel/babel/pull/10012#discussion_r321535012.
