### ISSUE TITLE
Can't declare variable with the same name as TypeScript type import

### ISSUE THREAD

**Issue by leethree** [babel/babel#10015]
## Bug Report

**Current Behavior**
Babel shows error "Identifier 'xxx' has already been declared" when variable and type uses the same name. 

**Input Code**
- REPL link:
https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCEAdjEgB7wC-cAZlBCHAORSoZMDcAUF2sQM7xCJcjABcBYqQoAeHJQB8cALyI2MAHRpWKUsOkwAFPICU3LuUixckkRTiVuQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.4.5

```js
import React, { Context } from 'react';

const Context: Context<{}> = React.createContext({});

export { Context };
```

**Error message**
```
/repl: Identifier 'Context' has already been declared (3:6)
```

**Expected behavior/code**
Types should be ignored by Babel and name conflict should not happen. This code is acceptable by TypeScript compiler even with `isolatedModules` option.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: ['module:metro-react-native-babel-preset']
}
```

**Environment**
- Babel version(s): v7.4.5
- Node/npm version: v10.15.0
- OS: macOS 10.14.5
- Monorepo: no
- How you are using Babel: React Native metro bundler

**Possible Solution**
It can be inferred from the file that the imported identifier is a type. So it should not count as an identifier.

**Additional context**
Related issue: https://github.com/babel/babel/issues/7943

It's very common in TypeScript to use the same identifier for variable and type without introducing a name conflict. This behaviour should be supported by Babel as well.

**Comment by dangreen** [comment]
Same thing:

```ts
type WeatherState = ReturnType<Record.Factory<IWeatherStateProps>>;

const WeatherState = Record<IWeatherStateProps>({
	city:            null,
	currentWeather:  null,
	weatherForecast: List()
});

export {
	WeatherState
};
...
import { WeatherState } from '...';
...
WeatherState();
```

throws:

```
TypeError: (0 , _Weather.WeatherState) is not a function
```

**Comment by dangreen** [comment]
In my case, `@babel/plugin-transform-typescript@7.4.0` solves problem (need to check lock file, to be sure we have't other versions)

**Comment by Jessidhia** [comment]
The REPL is a bit annoying to check but yes, this is affecting code on actual builds.

**Comment by leethree** [comment]
`@babel/plugin-transform-typescript@7.4.0` doesn't solve the problem for me. Also we need higher version to resolve other issues.

**Comment by pbadenski** [comment]
Still an issue with `@babel/plugin-transform-typescript@7.16.8` - any updates on this?

**Comment by nicolo-ribaudo** [comment]
The solution is to use `import React, { type Context } from 'react';` instead of `import React, { Context } from 'react';`.

**Comment by pbadenski** [comment]
It doesn't seem to work for me - is there any additional configuration required?

**Comment by IanVS** [comment]
Here's a reproduction of this error in astexplorer https://astexplorer.net/#/gist/37f431b33541330bd2ba87a720f85150/b19d62a18cd600add6d2787c4e650d950e982cbc, in case that's helpful.
