### ISSUE TITLE
Runtime error on array destructuring without declaration on same line

### ISSUE THREAD

**Issue by rasco** [babel/babel#10026]
## Bug Report

**Current Behavior**
In some cases, when I try to **destructuring an array without declaring the variables on the same line** as the deconstruction itself, the compiler seems to behave erroneously.
Specifically, if there is a function being called on the preceding line.

It results in a runtime error: `TypeError: Cannot set property 'undefined' of undefined`.

**Edit:** this can actually be reproduced in the REPL on [babeljs.io/repl](https://babeljs.io/repl) with the default settings

**Input Code**

This code:
```js
function start() {
	return (preHandler) => {
		let err, response

		preHandler()

		[err, response] = [1,2]

		console.log(err, response)
	}
}

function pre() {}

start()(pre)
```

Compiles to:
```js
"use strict";

function start() {
  return function (preHandler) {
    var err, response;
    preHandler()[(err, response)] = [1, 2];
    console.log(err, response);
  };
}

function pre() {}

start()(pre);
```

**Expected behavior/code**
Why are `err` and `response` dragged to the preceding line and treated like some kind of  index tuple to the result of `preHandler`?

Am I missing something here?

**If I put a semicolon** behind `preHandler()`, it works and compiles as expected to:
```js
var err, response;
preHandler();
err = 1;
response = 2;
```

It also works as expected if the declaration of `err` and `response` is done on the same line as the deconstruction: `let [err, response] = [1,2]`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets":[
        "@babel/preset-env"
    ],
	"plugins": [
		["module-resolver", {
			"root": ["./src"]
		}],
    	[
    		"@babel/plugin-transform-runtime"
	    ]
	]
}
```

**Environment**
- Babel version(s): 
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.4",
    "@babel/node": "^7.2.2",
    "@babel/plugin-transform-destructuring": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-plugin-module-resolver": "^3.2.0",
- Node/npm version: [v11.14.0/npm 6.9.0]
- OS: [Darwin Kernel Version 18.6.0]
- How you are using Babel: [as npm run-script with `babel test.js`]

**Edit**: I was able to simplify the code that triggers the error like follows:
```js
function pre() {}
let err, response
pre()
[err, response] = [1,2]
console.log(err, response)
```

**Comment by nicolo-ribaudo** [comment]
You are missing a semicolon. I suggest reading http://2ality.com/2011/05/semicolon-insertion.html 😉

**Comment by rasco** [comment]
> It's exactly that: you are missing a semicolon before the destructing. I suggest reading http://2ality.com/2011/05/semicolon-insertion.html 😉

Thanks nicolo! I missed that! Closing
