### ISSUE TITLE
[@babel/preset-typescript] baseUrl not being used to transform imports

### ISSUE THREAD

**Issue by miqmago** [babel/babel#10022]
## Bug Report

**Current Behavior**
When using typescript preset and `"baseUrl": "."` in `tsconfig.json` the import paths are not being rewritten, so compiled file imports source file.

**Input Code**

*src/helpers/util.ts*
```ts
export function helper(bla) {
}
...
```

*src/component/sample.ts*
```ts
import { helper } from 'src/helpers/util';
```

**Expected behavior/code**
When build, this import should be transformed to build path but it's none:

*build/component/sample.ts*
```ts
var _util = require("src/helpers/util");
```

**Babel Configuration (.babelrc, package.json, cli command)**

*.babelrc*:
```js
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ],
        "@babel/preset-typescript"
    ],
    "plugins": [
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-syntax-import-meta",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-json-strings",
        "@babel/proposal-object-rest-spread"
    ]
}
```

*tsconfig.json*:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "core-js/es7/reflect": [
        "node_modules/core-js/proposals/reflect-metadata"
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: node v10.15.4, npm 6.9.0
- OS: OSX 10.14.5
- Monorepo: no
- How you are using Babel: `cli`, `register`

**Possible Solution**
Right now the only solution I've found is not to use `"baseUrl"`.

**Comment by nicolo-ribaudo** [comment]
Babel doesn't read `tsconfig.json` (as documented at https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats). You can use https://github.com/tleunen/babel-plugin-module-resolver instead.
