### ISSUE TITLE
Unwanted comments movement (e.g. @ts-ignore) causing bugs in TS projects

### ISSUE THREAD

**Issue by stavalfi** [babel/babel#10024]
## Bug Report

**Current Behavior**
babel core moves comments inside arrow functions of one line.

The outcome of this is that @ts-ignore won't do any effect and if there are ts-errors, the typescript compiler will fail.

input:
```js
const lmbda1 = () =>
  // @ts-ignore
  console.log()
```
output:
```js
const lmbada1 = () => // @ts-ignore
console.log();
```

### How to reproduce: (I reproduced it without using any plugin/presets)

```js
const core = require('@babel/core')
const parser = require('@babel/parser')

const source1 = `const lmbada1 = () =>
  // @ts-ignore
  console.log()`

  const ast = parser.parse(source1, {
    babelrc: false,
    sourceType: 'module',
    plugins: ['jsx', 'typescript'],
  })

  core.transformFromAst(
    ast,
    source1,
    {
      babelrc: false,
      plugins: [],
    },
    (error, { code, map }) => {
      console.log(options)
      console.log(code)
      return error ? callback(error) : callback(null, code, map)
    },
  )
```

**Environment**
```
    "@babel/core": "^7.4.4",
    "@babel/parser": "^7.4.4",
```
- Node/npm version: [e.g. Node 8.11.3/npm 6.9.0]
- OS: OSX Mojave 10.14.3 (18D109)
- Monorepo: no
- How you are using Babel: parser and then core

---
* Q: why it effects me? 
* A: I must run a specific babel plugin before ts-loader to transform all absolute paths to a relative before the typescript compiler produces d.ts files.
https://github.com/stavalfi/babel-plugin-module-resolver-loader will run internally:
https://github.com/tleunen/babel-plugin-module-resolver
---

**Comment by nicolo-ribaudo** [comment]
Maintaining the original formatting isn't a goal of Babel, since when used directly its output is meant to be used by a JavaScript engine (which shouldn't care about formatting).

If you don't want Babel to format your code, you can use it together with [recast](https://github.com/benjamn/recast). [Example](https://github.com/nicolo-ribaudo/legacy-decorators-migration-utility/blob/1c9f306b5287bb2d5d07a512d1ad84036fd4956a/packages/wrap-legacy-decorators/src/index.js#L105)

**Comment by stavalfi** [comment]
Thanks that's working great!

Last question: to get the source maps, is it enough to use `recast.print(output.ast).map`? (I want to return them from my webpack loader)

**Comment by nicolo-ribaudo** [comment]
Yup, it should work. If you also need to handle an input source map, you can use the `sourceMapName` option: https://github.com/benjamn/recast#source-maps.

**Comment by stavalfi** [comment]
Thanks for all the help! 

Sadly, I lost you on how to use existing source maps. It seems sourceMapName is the name of a file. shouldn't it accept a source map object instead?

**Comment by nicolo-ribaudo** [comment]
Mh you are right; I got confused by the example. You can find all the available options at https://github.com/benjamn/recast/blob/master/lib/options.ts

**Comment by stavalfi** [comment]
@nicolo-ribaudo 

`babel-core.transformAsync` will also transpile typescript code to js code (with without providing him any plugins). is there a way to prevent it? I mean, to run only the provided plugins without running any default plugins?

This is why I used `transformFromAst` to prevent transpiling typescript code in the first place. but for some reason, `transformFromAst` changes the comment locations.

It is a ___huge___ problem for my loader because if not, any ts-loader that will run after me will get a pure-js code and will throw errors that everything has no type...

**Comment by stavalfi** [comment]
I found a workaround: set `retainLines` to true in `transformFromAst` options.

**Comment by nicolo-ribaudo** [comment]
The default plugins are the one specified in your config. You can prevent it using the `configFile: false` option.

**Comment by stavalfi** [comment]
yeah, I already tried that but it doesn't affect anything (but I didn't actually remove my babel config file to test if that will help).

core seems to ignore that or as a set of default plugins to at least transpile typescript to valid js.
