### ISSUE TITLE
In playground, property initializers should not have `this` replaced with undefined

### ISSUE THREAD

**Issue by gabrielecirulli** [babel/babel#1003]
The following code:

```js
class MyClass {
  initialized = { element: this.something.somethingElse }
}
```

when [parsed in playground mode,](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=false&loose=false&spec=false&code=class%20MyClass%20%7B%0A%20%20initialized%20%3D%20%7B%20element%3A%20this.something.somethingElse%20%7D%0A%7D) translates to

```js
"use strict";

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

var MyClass = function MyClass() {
  this.initialized = { element: undefined.something.somethingElse };

  _classCallCheck(this, MyClass);
};
```

This syntax is reminiscent of what was proposed on the [react blog](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers), and it is indeed very useful.

There's a big problem with it though, at the moment: `this` gets changed to `undefined`. Such behavior is correct for its own reasons, but in this instance it should not happen.

-------

Another thing of importance, which might impair this syntax from being used with the new React way of specifying classes, is that in most cases when using this new pattern you will be calling `super()` in the constructor before `this.props` is available. If you're planning to use it in your `state = { ... }`, then it would have to be placed after your call to `super()` in your constructor.

I'm just wondering if these two issues make sense or if I might be misunderstanding something, and I would love to try to come up with a solution together if they make sense.

**Comment by sebmck** [comment]
Gab, I told you over private chat that this wasn't an issue. Search next time :wink: See #619.

**Comment by sebmck** [comment]
Related #847
