### ISSUE TITLE
feat: presets & plugins as required modules

### ISSUE THREAD

**Issue by AndersDJohnson** [babel/babel#10035]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue when I try to include a Babel compilation as part of a CLI tool that I want users to be able to execute with `npx`.

**Describe the solution you'd like**
I'd like Babel to support supplying plugins and presets as `require()`d modules, so that they could be bundled with a tool via something like `webpack` or `rollup`, rather than requiring them to exist in local `node_modules` at runtime. So an example config could look something like:

```js
const presets = [ require('@babel/preset-env') ];
const plugins = [ require('@babel/plugin-proposal-class-properties') ];

module.exports = { presets, plugins };
```

**Describe alternatives you've considered**

Possibly requiring them in and referring to them as strings could work with `webpack` and `npx`, but I don't recall:

```js
require('@babel/preset-env')
require('@babel/plugin-proposal-class-properties')

const presets = [ '@babel/preset-env' ];
const plugins = [ '@babel/plugin-proposal-class-properties' ];

module.exports = { presets, plugins };
```

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

Users can simply choose whether to require them in, or still refer to them by string name.

**Comment by loganfsmyth** [comment]
This already works like you've described :D
