### ISSUE TITLE
Should not remove class fields when using flow

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10039]
If the flow plugin runs before the class properties one (or if the class properties plugin isn't used), we remove uninitialize class fields:

```js
class Foo { x: string }
```

currently becomes
```js
class Foo {}
```

while it should be
```js
class Foo { x }
```

If someone still wants the old behavior, they can either use flow comments (as [offically recommended](https://github.com/facebook/flow/issues/6811#issuecomment-496808192)), or use the `ignoreUninitialized` option which will soon be added to the class properties plugin (https://github.com/babel/babel/pull/9141).

---

Is there anyone who wants to contribute for the first time to Babel? :slightly_smiling_face: 

> **NOTE** :warning::warning::warning: Since this is a breaking change, we won't merge the PR for a long time (before Babel 8), and it might seem that we are ignoring it.

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to know other possible contributors that you are working on this bug.
1. Fork the repo
2. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
3. Run `yarn && make bootstrap`
4. Wait :hourglass_flowing_sand: 
5. Run `make watch` (or `make build` whenever you change a file)
6. Change the wrong `output.js` files in the `tests/fixture` folder of `@babel/plugin-transform-flow-strip-types` (if there are any)
7. Update the code!
8. `yarn jest [name-of-the-package-to-test]` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
9. If it is working, run `make test` tu run all the tests
10. Run `git push` and open a PR!

**Comment by ajay2507** [comment]
@nicolo-ribaudo  Thanks. I can try this out.

**Comment by existentialism** [comment]
@ajay2507 it's yours! feel free to hit us up if you have any questions!

**Comment by ajay2507** [comment]
@nicolo-ribaudo  Cool. Thanks

**Comment by lidoravitan** [comment]
@existentialism @pajaydev is there some news with this issue? does still need help? thanks

**Comment by pajaydev** [comment]
@lidoravitan  I have done it, Some test are failing. I need to create a PR and get reviewed.

**Comment by lidoravitan** [comment]
@pajaydev cool thanks for the response

**Comment by pajaydev** [comment]
@existentialism  @nicolo-ribaudo  I created this PR https://github.com/babel/babel/pull/10120 . this test `babel-plugin-transform-flow-strip-types/test/fixtures/regression/class-prop-types` is failing, Shall I remove the `transform-classes` from `babel-plugin-transform-flow-strip-types/test/fixtures/regression/class-prop-types/options.json`  ?.

**Comment by pajaydev** [comment]
build status https://circleci.com/gh/babel/babel/10996?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pajaydev** [comment]
@nicolo-ribaudo  I fixed the test. Thanks for your help. I appreciate it.
