### ISSUE TITLE
I got an error on module not found core/is-array

### ISSUE THREAD

**Issue by ShintaroNippon** [babel/babel#10030]
Hi there iI have installed @babel/runtime-corejs2 but I'm getting this error:

```
[ error ] /snapshot/frontend/node_modules/next-server/dist/lib/loadable.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/is-array' in '/snapshot/frontend/node_modules/next-server/dist/lib'

```
package.json
"@babel/cli": "^7.2.3",
"@babel/core": "^7.3.4",
"@babel/helpers": "^7.3.1",
"@babel/polyfill": "^7.2.5",
"@babel/preset-env": "^7.3.4",
"@babel/runtime": "^7.3.4",
"@babel/runtime-corejs2": "^7.4.5",

Can someone help me?

THanks in advance !

**Comment by ShintaroNippon** [comment]
Thanks by the reply.

I will try the slack
Best regards
Carlos Vieira

**Comment by nicolo-ribaudo** [comment]
Does that file exist in your filesystem?
It exists in `@babel/runtme-corejs2`: https://unpkg.com/@babel/runtime-corejs2@7.4.5/core-js/array/is-array

**Comment by ShintaroNippon** [comment]
HI, thanks for the reply...
I have  made a search in all project for https://unpkg.com/@babel/runtime-corejs2@7.4.5/core-js/array/is-array

and it couldn't be founded,
thanks

**Comment by nicolo-ribaudo** [comment]
What does the `node_modules/@babel/runtime-corejs2/core-js/array` folder contain?

**Comment by ShintaroNippon** [comment]
I'm using this boiler plate
https://github.com/MustansirZia/next-express-bootstrap-boilerplate
he creates a folder .next on root with babelrc cwd

let me check the folder

**Comment by ShintaroNippon** [comment]
cd node_modules/@babel/runtime-corejs2/
shintaro@shintaro-PC:~/Desktop/projects/github/frontend/node_modules/@babel/runtime-corejs2$ ls
core-js  helpers  LICENSE  node_modules  package.json  README.md  regenerator


what I'm trying to do its binary using pkg

https://www.npmjs.com/package/pkg

thanks

**Comment by ShintaroNippon** [comment]
shintaro@shintaro-PC:~/Desktop/projects/github/frontend/node_modules/@babel/runtime-corejs2$ cd core-js/
shintaro@shintaro-PC:~/Desktop/projects/github/frontend/node_modules/@babel/runtime-corejs2/core-js$ ls
array               get-iterator.js  map.js  object          promise.js        set.js  symbol.js
clear-immediate.js  is-iterable.js   math    parse-float.js  reflect           string  weak-map.js
date                json             number  parse-int.js    set-immediate.js  symbol  weak-set.js
shintaro@shintaro-PC:~/Desktop/projects/github/frontend/node_modules/@babel/runtime-corejs2/core-js$ cd array/
shintaro@shintaro-PC:~/Desktop/projects/github/frontend/node_modules/@babel/runtime-corejs2/core-js/array$ ls
from.js  is-array.js  of.js
shintaro@shintaro-PC:~/Desktop/projects/github/frontend/node_modules/@babel/runtime-corejs2/core-js/array$

**Comment by nicolo-ribaudo** [comment]
Ok so the file is there (`is-array.js`). It might be a bug with `pkg` which for some reason doesn't load that package :thinking:

**Comment by ShintaroNippon** [comment]
ok ok, thanks, I will open an issue on pkg
many thanks

**Comment by ShintaroNippon** [comment]
https://github.com/zeit/pkg/issues/694
