### ISSUE TITLE
Register + RC (+ Ignore?)

### ISSUE THREAD

**Issue by jupl** [babel/babel#1004]
```
npm install mocha koa babel
```

```js
// .babelrc
{"ignore": false}

// test.js
import 'koa';

// setup-a.js
require('babel/register');

// setup-b.js
require('babel/register')({
  ignore: false
});
```

If I run `mocha --compilers js:babel/register` or `mocha --require setup-a`, I get an `Unexpected token *` error since a module (koa) was not transpiled. If I run `mocha --require setup-b` it works as expected. So far it appears that `.babelrc` is not being picked up with register for at least `ignore`.

**Comment by sebmck** [comment]
`.babelrc` is not documented so it's not currently supported until the next major. It only allows babel compilation options to be set and as such `ignore` is not available because it's a `babel/register` specific option.

**Comment by sebmck** [comment]
Just to clarify, you will be able to set `ignore` via `.babelrc` in the next major and it will be supported by all the plugins and integrations.
