### ISSUE TITLE
Identifier has already been declared error in TSModuleBlock

### ISSUE THREAD

**Issue by jj-choi** [babel/babel#10043]
## Bug Report

**Current Behavior**
SyntaxError: Identifier 'foo' has already been declared

**Input Code**
```js
declare class foo {
}
declare module 'bar' {
  export var foo: any; // Identifier 'foo' has already been declared
}
```

**Expected behavior/code**
no error

**Babel Configuration (.babelrc, package.json, cli command)**
typescript plugin

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: Node 11.13 / npm 6.7

**Possible Solution**
In tsParseModuleBlock(), should change its scope to SCOPE_VAR or something new.

**Comment by nicolo-ribaudo** [comment]
Is it thrown by `@babel/parser` or by `@babel/traverse`?

**Comment by jj-choi** [comment]
I only used a @babel/parser.
