### ISSUE TITLE
Getting warning - `useBuiltIns` option without declaring a core-js version even though there is (core-js@3.1.3)

### ISSUE THREAD

**Issue by slavkobojanic** [babel/babel#10049]
## Bug Report

**Current Behavior**
It seems as if `@babel/preset-env@7.4.5` is giving me a bit of a hard time after upgrading from `core-js@2.x.x` to `core-js@3.1.3`, the error it's spitting out says that .babelrc needs to have a core-js version specified if i'd like to use `useBuiltIns`. I've definitely tried to install core-js@3 as both a normal dependency and as a devDependency with no success, as well as that i'd tried to install core-js@3.1.3 as a global node_module which still had changed nothing.
This issue only occurs the first time I do a npm install then run my webpack build, and then doesn't occur again on subsequent webpack builds which I found odd.

**Input Code**
- REPL or Repo link if applicable:

```js
Not applicable, no input
```

**Expected behavior/code**
There shouldn't be any errors thrown by webpack about a missing core-js dependency when it is clearly installed.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "ie >= 11"
          ],
          "corejs": "3.1.3",
          "useBuiltIns": "usage"
        }
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ],
  "env": {
    "test-pipeline": {
      "plugins": [
        "@babel/plugin-transform-runtime",
        "istanbul"
      ]
    },
    "test": {
      "plugins": [
        "@babel/plugin-transform-runtime",
        "istanbul"
      ]
    },
    "development": {
      "plugins": [
        "@babel/plugin-transform-runtime",
        "react-hot-loader/babel"
      ]
    }
  }
}

```

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: 11.15.0
- OS: Ubuntu 18.04 LTS
- Monorepo: No
- How you are using Babel: babel-loader

**Possible Solution**
No suggestions here

**Additional context/Screenshots**
Doesn't require screenshots, but can be added for context :)

**Comment by hegelstad** [comment]
Don't put corejs and useBuiltIns properties inside of target.

**Comment by nicolo-ribaudo** [comment]
Exactly, it should be like this:
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "ie >= 11"
          ],
        },
        "corejs": "3.1.3",
        "useBuiltIns": "usage"
      }
    ],
    "@babel/preset-react"
  ],
```
