### ISSUE TITLE
`@babel/plugin-transform-named-capturing-groups-regex` fails to wrap all groups

### ISSUE THREAD

**Issue by 0xdevalias** [babel/babel#10045]
## Bug Report

**Current Behavior**

When composing regular expressions that contain named capture groups, they aren't properly wrapped in all cases. It seems only the `/foo/` regex literals get wrapped?

**Input Code**

- [Babel REPL](https://babeljs.io/repl#?babili=false&browsers=last%202%20Chrome%20versions%2C%0Alast%202%20Firefox%20versions%2C%0Alast%202%20Edge%20versions%2C%0ASafari%20%3E%3D%209%2C%0AIE%2011%2C&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wKIFkBCGAiA-gMIDy-GhAShgOIYAacAvHABRsCULAfHAN4AoOIhTo4AQwA28VgHo2AfgA80mDwB0AKkWdFc4aLTwpAS2QBrFnAUqzlzTr0GRSY3BimYU4NdsAuACIlZU9vYEddQOdBQzdxAFsJKAsAEwgAd2QASSSAc195EKSYBAALHgBCAB0AbQBBABkAFWqAXWq2RuyAOQBpatQtZuzmxoxqzk45DVQIAFcoBGBDEQ0oYDApCWW2AHIm5r2AGkkZWYWl4E5VuHXN7d297v6TuHsLC8Xlm5E1ja2O2A-xGYwwbzCPi-Vxuhg2MEWyDgyGAGTgVGAeQw4DYSRS6SyuQkBVOezyexuAF9OFwgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-transform-runtime%407.4.4%2C%40babel%2Fplugin-transform-regenerator%407.4.4%2C%40babel%2Fplugin-syntax-dynamic-import%407.2.0)

```js
export const EMBED_CODE_REGEX = (() => {
  const alt = /(?<alt>.*?)?/
  const link = /(?<link>.*?)?/
  const title = /(?:"(?<title>.*?)")?/

  const markdownImage = /(?<match>!\[ALT\]\(LINK\s*TITLE\))/.source
    .replace('ALT', alt.source)
    .replace('LINK', link.source)
    .replace('TITLE', title.source)

  return new RegExp(markdownImage, 'g')
})()
```

This turns into (with some boilerplate removed):
```js
var EMBED_CODE_REGEX = function () {
  var alt = _wrapRegExp(/(.*?)?/, {
    alt: 1
  });

  var link = _wrapRegExp(/(.*?)?/, {
    link: 1
  });

  var title = _wrapRegExp(/(?:"(.*?)")?/, {
    title: 1
  });

  var markdownImage = _wrapRegExp(/(!\[ALT\]\(LINK\s*TITLE\))/, {
    match: 1
  }).source.replace('ALT', alt.source).replace('LINK', link.source).replace('TITLE', title.source);

  return new RegExp(markdownImage, 'g');
}();
```

The intermediate regex literals are correctly wrapped, but on the second last line, the explicit `new RegExp` isn't wrapped.

Somewhere in this composure, the groups are lost, such that downstream code ends up breaking due to them not being present.

Running the above code in chrome console produces:
```js
export const EMBED_CODE_REGEX = /(?<match>!\[(?<alt>.*?)?\]\((?<link>.*?)?\s*(?:"(?<title>.*?)")?\))/g
```

Which when transpiled comes out as you would expect:
```js
var EMBED_CODE_REGEX = _wrapRegExp(/(!\[(.*?)?\]\((.*?)?\s*(?:"(.*?)")?\))/g, {
  match: 1,
  alt: 2,
  link: 3,
  title: 4
});
```

**Expected behavior/code**

I would expect that all code output from this would get transformed, including the explicit `new RegExp`/etc.

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: no
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by 0xdevalias** [comment]
This is how it looks when I manually compose it (eg. looks like it should work fine)

```js
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "EMBED_CODE_REGEX", function() { return EMBED_CODE_REGEX; });

// ..snip..

var EMBED_CODE_REGEX = _wrapRegExp(/(!\[(.*?)?\]\((.*?)?\s*(?:"(.*?)")?\))/g, {
  match: 1,
  alt: 2,
  link: 2,
  title: 2
}); // export const EMBED_CODE_REGEX = (() => {
//   const alt = /(?<alt>.*?)?/
//   const link = /(?<link>.*?)?/
//   const title = /(?:"(?<title>.*?)")?/
//
//   const markdownImage = /(?<match>!\[ALT\]\(LINK\s*TITLE\))/.source
//     .replace('ALT', alt.source)
//     .replace('LINK', link.source)
//     .replace('TITLE', title.source)
//
//   return new RegExp(markdownImage, 'g')
// })()
```

But then in my calling code:
```js
return function (markdown) {
    return Array.from(markdown.matchAll(markdown_field_constants__WEBPACK_IMPORTED_MODULE_0__["EMBED_CODE_REGEX"])).map(function (match) {
      return match.groups;
    }).filter(filter).reduce(reducer, markdown);
  };
```

It seems it fails to see any of the wrapping/groups stuff:
```js
markdown_field_constants__WEBPACK_IMPORTED_MODULE_0__["EMBED_CODE_REGEX"]
```
```
/(!\[(.*?)?\]\((.*?)?\s*(?:"(.*?)")?\))/g
```

![image](https://user-images.githubusercontent.com/753891/58608513-41880400-82e7-11e9-846a-14ff3b02defb.png)

**Comment by nicolo-ribaudo** [comment]
It's not possible for Babel to transpile the behavior of runtime functions (like `new RegExp`): you need a polyfill for that. You could try using https://github.com/slevithan/xregexp (I don't know any other polyfill which has named capturing groups support).
