### ISSUE TITLE
Flow: losing info about explicitly inexact objects

### ISSUE THREAD

**Issue by mrtnzlml** [babel/babel#10040]
## Bug Report

**Current Behavior**
Babel is currently losing info about explicitly inexact objects when using Flow parser plugin. It should return the code as is. Thanks for checking it! :)

**Input Code**
This is not possible to reproduce in REPL. Input code:

```js
// @flow strict
  
export type ExplicitlyInexact = { foo: number, ... };
```

Package.json:

```json
{
  "dependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5"
  }
}
```

Command:

```text
yarn babel input.js
```

Output:

```js
// @flow strict
export type ExplicitlyInexact = {
  foo: number
};
```

As you can see, information about the inexact object (` ... `)  is lost.

**Expected behavior/code**
It should return the code as is:

```js
// @flow strict
export type ExplicitlyInexact = {
  foo: number,
  ...
};
```

**Babel Configuration (.babelrc)**

```json
{
  "parserOpts": {
    "plugins": ["flow"]
  }
}
```

**Additional context/Screenshots**
https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf

**Comment by existentialism** [comment]
Looks like generator needs support for printing the trailing ellipsis:

https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/flow.js#L388

Want to take a stab @mrtnzlml?

**Comment by mrtnzlml** [comment]
I am afraid I do not have enough Babel knowledge for this. I could check it later but it would be helpful if someone else did. :) BTW, real-world (similar) example: https://github.com/kiwicom/babel-preset-kiwicom/commit/f592fb74d7535d394b79b4864bbe0eaa1878b7d9

**Comment by nicolo-ribaudo** [comment]
If anyone wants to open a PR, this is the file which handles the printing of flow-related nodes: https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/flow.js.

As you can see in the `@babel/types` package, an `ObjectTypeAnnotation` node can have an `inexact` boolean flag:
https://github.com/babel/babel/blob/8d492b159b342cfd1f399e4292e3cb12a895e1d3/packages/babel-types/src/definitions/flow.js#L259-L285

In the printer for that node, we are only checking for the `exact` flag (which marks `{| |}` types) but not `inexact`:
https://github.com/babel/babel/blob/8d492b159b342cfd1f399e4292e3cb12a895e1d3/packages/babel-generator/src/generators/flow.js#L388-L427

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to know other possible contributors that you are working on this bug.
1. Fork the repo
2. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
3. Run `yarn && make bootstrap`
4. Wait :hourglass_flowing_sand: 
5. Run `make watch` (or `make build` whenever you change a file)
6. Add a test (only `input.js`; `output.js` will be automatically generated)
7. Update the code!
8. `yarn jest [name-of-the-package-to-test]` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
9. If it is working, run `make test` tu run all the tests
10. Run `git push` and open a PR!

**Comment by mrtnzlml** [comment]
I was actually looking into it now and it looks doable. Especially with your guidance, thanks! I will take it and fix it.

**Comment by mrtnzlml** [comment]
Alright, here is my attempt: https://github.com/babel/babel/pull/10041

Please, have a look and let me know what to improve.
