### ISSUE TITLE
Error thrown if `api.env` is used together with `api.cache` in babel.config.js

### ISSUE THREAD

**Issue by mdekalka** [babel/babel#10052]
## Bug Report

**Current Behavior**
Created a simple boilerplate project using new `babel.config.js` file:
```
module.exports = api => {
  // If you comment this you will see the message from from here
  https://github.com/babel/babel/blob/master/packages/babel-core/src/config/files/configuration.js#L198
  api.cache(true)

  const presets = [
    "@babel/preset-env",
    "@babel/preset-react"
  ]

  const plugins = [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-throw-expressions"
  ]

  return {
    presets,
    plugins
  }
}
```
and then I want to add `api.env()` call for example:
```
...
const currentEnv = api.env()
console.log(currentEnv , 'hey env')
...
```
after doing this I get the error message(that cache was already configured):
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Caching has already been configured with .never or .forever()
```

**Expected behavior/code**
I think we should be able to use `api.cache` with `api.env` together in `babel.config.js`.
Didn't find any information that this two API's can't be used together
https://babeljs.io/docs/en/config-files#apienv

**Reproduce repo**
https://github.com/mdekalka/babel-check
Please run `yarn install` then `yarn start`

**Environment**
- Babel version(s): `babel-core`: `7.4.5`
- Node/npm version: Node `v8.11.3/v10.8.0` | npm `v5.8.0/v6.4.1`
- OS: `OSX 10.13.1` /  `Windows 10`
- Monorepo: `no`
- How you are using Babel: `cli`

**Comment by nicolo-ribaudo** [comment]
Yeah, the documentation should explain this better.
`api.env()` internally does something like `api.cache(currentEnv === oldEnv)`, so they can't be used together.

**Comment by mdekalka** [comment]
Got it. Thank you for response.
If `api.env()` doing some `caching` logic already under the hood, what if I want to disable cache at all and use `api.env()`:
```
api.cache(false)

const env = api.env()
...
```
should we switch in this case to `process.env.NODE_ENV` instead of `api.env()`?

**Comment by nicolo-ribaudo** [comment]
Yes. `api.env()` invalidates the cache only when `process.env.NODE_ENV` (or the `envName` programmatic option) changes.

**Comment by loganfsmyth** [comment]
FYI, at the moment I'm unaware of a situation where `.cache(false)` would actually be useful in any real way. As far as I know though, setting `false` after would just override the env caching to essentially disable it.

**Comment by tanhauhau** [comment]
by reading the code, I realise the order matters, ie:

```js
const env = api.env()
api.cache(false)
```

will not throw, maybe when calling `api.cache.forever()` or `api.cache.never()`, [we should also check whether the cache has been configured before?](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/caching.js#L131)

**Comment by loganfsmyth** [comment]
@tanhauhau Why are you using `api.cache(false)` in this case? I think the real answer is just to never use it. I kind of regret including it.

**Comment by tanhauhau** [comment]
I'm not, just want to prove a point that is possible.

**Comment by loganfsmyth** [comment]
Gotcha, sounds good!
