### ISSUE TITLE
regeneratorRuntime is not defiined

### ISSUE THREAD

**Issue by smileycreations15** [babel/babel#10056]
## Bug Report

**Current Behavior**
regeneratorRuntime is not defined when running in a browser.
```js
"use strict";

function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }

function _asyncToGenerator(fn) { return function () { var self = this, args = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(self, args); function _next(value) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); } function _throw(err) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); } _next(undefined); }); }; }

_asyncToGenerator(
/*#__PURE__*/
regeneratorRuntime.mark(function _callee() {
  return regeneratorRuntime.wrap(function _callee$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return Promise.resolve();

        case 2:
        case "end":
          return _context.stop();
      }
    }
  }, _callee);
}))();
```

**Input Code**
- REPL or Repo link if applicable:

```js
(async function(){await Promise.resolve()})()
```

**Expected behavior/code**
The code should run without errors.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [[
    "@babel/preset-env", {
      "useBuiltIns": "entry",
      "corejs":3
    }]]
}
```

**Environment**
- Babel version(s): v7
- Node/npm version: Node 10.14.5/NPM 6.9.0
- OS: OSX 10.14.5
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
`useBuiltIns: entry` needs an "hint" to know where to inject polyfills.

You need to add this code to the beginning of what you consider your entry point:
```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```

**Comment by smileycreations15** [comment]
> ```js
> import "core-js/stable";
> import "regenerator-runtime/runtime";
> ```

What about the tons of requires that can't be run in a web browser?

**Comment by nicolo-ribaudo** [comment]
Oh ok, then you don't want to use `useBuiltIns: entry` (and `corejs: 3`), because that's exactly what those options are for: add imports/requires to polyfills.

If you don't want them, you can remove them from your config and add
```html
<script src="https://unpkg.com/regenerator-runtime/runtime.js"></script>
```
To your html file, before loading your own code.

**Comment by smileycreations15** [comment]
> Oh ok, then you don't want to use `useBuiltIns: entry` (and `corejs: 3`), because that's exactly what those options are for: add imports/requires to polyfills.
> 
> If you don't want them, you can remove them from your config and add
> 
> ```
> <script src="https://unpkg.com/regenerator-runtime/runtime.js"></script>
> ```
> 
> To your html file, before loading your own code.
> 
> If you also need core-js, it's `https://unpkg.com/core-js-bundle@3.1.3/minified.js`

Thanks!
