### ISSUE TITLE
[TypeScript] SyntaxError on array destructuring

### ISSUE THREAD

**Issue by jj-choi** [babel/babel#10066]
## Bug Report

**Current Behavior**
SyntaxError: Unexpected type cast in parameter position

**Input Code**
```js
[x as Foo] = arr
```

**Expected behavior/code**
no error

**Babel Configuration (.babelrc, package.json, cli command)**
@babel/parser with typescript plugin

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: Node 11.13 / npm 6.7

**Comment by tanhauhau** [comment]
I don't think it's a valid typescript syntax: [TypeScript playground](https://www.typescriptlang.org/play/#src=function%20foo%20(arr%3A%20%5Bnumber%5D)%20%7B%0D%0A%20%20%20%20let%20%5Bx%20as%20number%5D%20%3D%20arr%3B%0D%0A%7D%0D%0A)

**Comment by jj-choi** [comment]
Its a valid assignment statement.
```js
function foo (arr: [number]) {
    let x;
    [x as number] = arr;
}
```

**Comment by SakibulMowla** [comment]
I'm taking a look into this issue.
