### ISSUE TITLE
plugin-proposal-class-properties and defineProperty

### ISSUE THREAD

**Issue by jeremad** [babel/babel#10064]
## Bug Report

**Current Behavior**
I have a file defining a class with a property. I add a type annotation (with flow) for this property, I define this property in the constructor, as non configurable. When using `plugin-proposal-class-properties`, this property is defined twice, and is now configurable which is not what I want.

**Input Code**

class:
```js
// @flow

export class Foo { 
  _bar: string; 
 
  constructor() { 
    Object.defineProperty(this, '_bar', { value: 'bar', writable: true }); 
  } 
 
  clean() { 
    delete this._bar; 
  } 
} 
```

package.json:
```json
{ 
  "devDependencies": { 
    "@babel/cli": "^7.4.4", 
    "@babel/core": "^7.4.5", 
    "@babel/plugin-proposal-class-properties": "^7.4.4", 
    "@babel/preset-env": "^7.4.5", 
    "@babel/preset-flow": "^7.0.0", 
    "@babel/register": "^7.4.4", 
    "flow-bin": "0.98.1", 
    "mocha": "^6.1.4" 
  }, 
  "babel": { 
    "presets": [ 
      "@babel/preset-flow", 
      [ 
        "@babel/preset-env", 
        { 
          "targets": { 
            "node": 8 
          } 
        } 
      ] 
    ], 
    "plugins": [["@babel/plugin-proposal-class-properties"]] 
  } 
}
```

test:
```js
import { Foo } from './foo'; 
 
describe('foo', () => { 
  it('clean', () => { 
    const foo = new Foo(); 
    foo.clean(); 
  }); 
}); 

```

**Expected behavior/code**
```
$ yarn
$ yarn mocha foo.spec.js --require @babel/register
```
The test passes, while it should fail

**Environment**
- Babel version(s):7.4.4
- Node/npm version: Node 11.15.0 yarn 1.15.2
- OS: Ubuntu 19.04
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: `register`

**Possible Solution**
Do not `Object.defineProperty` if the user already does that!

**Comment by nicolo-ribaudo** [comment]
Class properties internally use `defineProperty`: that's the what the specification say.

You can wrap your class property in a flow comment, so that it isn't actually included in the js code.

**Comment by jeremad** [comment]
Ok thank you very much
