### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by vonwao** [babel/babel#10062]
## Bug Report

**Current Behavior**
Get error:
(function (exports, require, module, __filename, __dirname) { import { addLike } from "./streamHelpers";
^SyntaxError: Unexpected token {

**Babel Configuration (.babelrc, package.json, cli command)**

  "presets": ["@babel/env"]

**Environment**
Babel version(s):
"@babel/cli": "^7.4.4",
"@babel/core": "^7.4.5",
"@babel/node": "^7.4.5",
"@babel/preset-env": "^7.4.5",
Node/npm version: [e.g. Node 8/npm 5]
v10.15.1
OS: [e.g. OSX 10.13.4, Windows 10]
Win10 and Mac OSX

**Comment by nicolo-ribaudo** [comment]
How are you running Babel, what is your directory structure and which file is throwing?

PS. Using `babel.config.js` instead of `.babelrc` might fix it.

**Comment by vonwao** [comment]
I was running with yarn
 "build": "babel -d ./build ./src -s",
  "start": "node ./build/main/server.js",

The file that was throwing was not the entry point, but another random file.

**Comment by existentialism** [comment]
Can you create a small repo that reproduces the error?

**Comment by canyavall** [comment]
Hi there!
I'm having exactly the same issue. I'm working with Windows 10 and using babel.config.js

babel.config.js
```
// Check if the argument REACT_APP_PLATFORM has been passed and get the value
const platform = !!process.env.REACT_APP_PLATFORM

// Different babel configurations depending on the build
if (platform) {
  module.exports = {
    presets: [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    plugins: ["@babel/plugin-proposal-class-properties", "@babel/plugin-proposal-export-default-from", "@babel/plugin-transform-runtime", "@babel/plugin-transform-modules-commonjs"]
  };
} else {
  module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
  };
}

```

My coleagues are using Mac and with Mac it works like a charm... The strange thing is that before leaving on holidays everything was working fine and now it is not working...

The project is a react native + react project and this is the file structure
![image](https://user-images.githubusercontent.com/11173569/60865131-aa876380-a225-11e9-878b-e2b32a803f33.png)

Any help is more than welcome!!

**Comment by canyavall** [comment]
So, doing what is mentiones in this post:
https://medium.com/@abhisheknalwaya/how-to-clear-react-native-cache-c435c258834e

and deleting the yarn.lock file did the trick....
