### ISSUE TITLE
 ObjectMethod: Too many arguments passed. Received 10 but can receive no more than 5

### ISSUE THREAD

**Issue by rubyless** [babel/babel#10077]
## Bug Report

**Current Behavior**

UnhandledPromiseRejectionWarning: Error: ObjectMethod: Too many arguments passed. Received 10 but can receive no more than 5

**Input Code**
- REPL or Repo link if applicable:

```js
t.objectMethod(
                  node.kind,
                  node.key,
                  node.params,
                  node.body,
                  node.computed,
                  node.async,
                  node.decorators,
                  node.generator,
                  node.returnType,
                  node.typeParameters
                )
```

**Comment by nicolo-ribaudo** [comment]
It only accepts these parameters: https://github.com/babel/babel/blob/f92c2ae830dbb32013a36fa74facd2ef95b9947d/packages/babel-types/src/definitions/core.js#L600

**Comment by rubyless** [comment]
But babel documentation shows that it accepts these parameters;
And i want to create an async objectMethod

```
kind: "method" | "get" | "set" (default: 'method')
key: if computed then Expression else Identifier | Literal (required)
params: Array<LVal> (required)
body: BlockStatement (required)
computed: boolean (default: false)
async: boolean (default: false)
decorators: Array<Decorator> (default: null)
generator: boolean (default: false)
returnType: TypeAnnotation | TSTypeAnnotation | Noop (default: null)
typeParameters: TypeParameterDeclaration | TSTypeParameterDeclaration | Noop (default: null)
```
https://babeljs.io/docs/en/next/babel-types#objectmethod

**Comment by nicolo-ribaudo** [comment]
The function you linked has 5 parameters in that page. The text you copied are the _properties_ an object method node can have.
You can manually set it to be async:
```js
var node = t.objectMethod(...);
node.async = true;
```

**Comment by rubyless** [comment]
Thanks  @nicolo-ribaudo. It works ok.
