### ISSUE TITLE
eval breaks "let" variable declaration scope

### ISSUE THREAD

**Issue by tchaffee** [babel/babel#10079]
## Bug Report

**Current Behavior**
Using `eval` can reveal the underlying Babel transformation and use of `var` to declare variables that are supposed to have block scope but no longer do.

**Input Code**
```js
{
  let j = 'privateToBlock';
}

eval('console.log(j)');
```

**Expected behavior/code**
In ES6 the above code produces `"ReferenceError: j is not defined"`.

The code transformed using Babel is:

```js
"use strict";

{
  var j = 'privateToBlock';
}
eval('console.log(j)');
```

Which of course outputs `privateToBlock` and is unexpected.

**Babel Configuration (.babelrc, package.json, cli command)**
None

**Environment**
Using the Babel website.

**Comment by nicolo-ribaudo** [comment]
Unfortunately we can't make any guarantees about `eval`, since it allows arbitrary execution of any code which Babel can't often statically analyze.
