### ISSUE TITLE
trimStart, trimEnd and their aliases trimLeft and trimRight are not supported in IE11 but are in generated babel output

### ISSUE THREAD

**Issue by jasondockery** [babel/babel#10074]
**Current Behavior**
trimStart, trimEnd and their aliases trimLeft and trimRight are showing in the output from Babel, but IE 11 doesn't support those functions. 

**Input Code**
```js
const greeting = " hello! ";

console.log(greeting.trimStart());
console.log(greeting.trimLeft());
console.log(greeting.trimEnd());
console.log(greeting.trimRight());
```

**Expected behavior/code**
Based on MDN site, trimStart, trimEnd and their aliases trimLeft and trimRight are not supported in IE 11.  This was also confirmed by trying to run the code in IE 11 via the console.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd

trimStart, trimEnd and their aliases trimLeft and trimRight should be replaced with code that is safe to run in IE 11.

**Babel Configuration (.babelrc, package.json, cli command)**
IE 11

**Environment**
I was seeing the issue in my own environment, so I tested it on the babeljs.io "try it now" and seen the same beahvior.

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![ie_error_output](https://user-images.githubusercontent.com/147926/59164334-22942980-8ac0-11e9-82da-e120c98f2200.jpg)

**Comment by nicolo-ribaudo** [comment]
What is your configuration?

**Comment by jasondockery** [comment]
@nicolo-ribaudo in our environment we use next.js.   To keep it simple for the bug report and take all other variables out of the equation, I used the "Try it Out" link on https://babeljs.io/repl.  I set Browsers to "ie 11" and no presets selected.  Would that produce different output than running babel against a specific file?

**Comment by existentialism** [comment]
> trimStart, trimEnd and their aliases trimLeft and trimRight should be replaced with code that is safe to run in IE 11.

Those features need to be _polyfilled_ and are not _transpiled_.

For example, if you enable `useBuiltIns: usage` in preset-env you can see the polyfills being added:

https://babeljs.io/repl#?babili=false&browsers=ie%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=MYewdgzgLgBA5gJwKZKgSzHGBeGAiGACyQBsSQBCfAbgChbRIQSkA6cuACkRXU1agI0AWwDKUAIYIonAJSy6jCMzYduyVBjgChwgDJIAZjPmLwyluxBcem_oJEBRMABM5ChuZVWbGvtodhACU0OEITBSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.4.5&externalPlugins=

(You can toggle the built-ins option to see the effect)

**Comment by jasondockery** [comment]
Thanks @existentialism, that helped.  I believe the issue is on my end and will close the ticket.
