### ISSUE TITLE
 Cannot find module 'caniuse-lite'

### ISSUE THREAD

**Issue by mkucaj1986** [babel/babel#10080]
● Test suite failed to run

    Cannot find module 'caniuse-lite/dist/unpacker/agents'

      at Object.<anonymous> (node_modules/@babel/preset-env/node_modules/browserslist/index.js:2:14)

On Gitlab Test Unit Runner 

.babelrc
`{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        "module:@trans-ui/components",
        "syntax-dynamic-import",
        "transform-class-properties"
    ],
    "env": {
        "production": {
            "plugins": [
                [
                    "transform-react-remove-prop-types",
                    {
                        "mode": "wrap",
                        "ignoreFilenames": [
                            "node_modules"
                        ]
                    }
                ]
            ]
        },
        "test": {
            "presets": [
                [
                    "@babel/preset-env",
                    {
                        "targets": {
                            "node": "current"
                        }
                    }
                ],
                "@babel/preset-react"
            ],
            "plugins": [
                "module:@trans-ui/components",
                "babel-plugin-dynamic-import-node"
            ]
        }
    }
}
`
.package.json
 "@babel/cli": "^7.4.4",
        "@babel/core": "^7.4.5",
        "@babel/node": "^7.4.5",
        "@babel/plugin-proposal-class-properties": "^7.4.4",
        "@babel/plugin-proposal-object-rest-spread": "^7.4.4",
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/plugin-transform-runtime": "^7.4.4",
        "@babel/polyfill": "7.0.0",
        "@babel/preset-env": "7.0.0",
        "@babel/preset-react": "7.0.0",
        "assets": "^2.1.0",
        "auto-styles-loader": "^1.0.2",
        "autoprefixer": "6.0.0",
        "babel-core": "^7.0.0-bridge.0",
        "babel-eslint": "^8.2.3",
        "babel-istanbul": "^0.12.1",
        "babel-jest": "^24.8.0",
        "babel-loader": "^8.0.0",
        "babel-plugin-dynamic-import-node": "^1.2.0",
        "babel-plugin-module-resolver": "^3.2.0",
        "babel-plugin-transform-react-remove-prop-types": "^0.4.14",
        "clean-webpack-plugin": "^0.1.19",
        "css-loader": "^0.28.11",
        "directory-named-webpack-plugin": "^4.0.0",
        "eslint": "^4.13.1",
        "eslint-config-airbnb": "^14.0.0",
        "eslint-config-google": "^0.9.1",
        "eslint-plugin-import": "^2.13.0",
        "eslint-plugin-jest": "^21.3.2",
        "eslint-plugin-jsx-a11y": "^6.0.0",
        "eslint-plugin-react": "^6.8.0",

**Comment by nicolo-ribaudo** [comment]
What does this code log?
```
cd node_modules/@babel/preset-env/node_modules/browserslist && node -p "require.resolve('caniuse-lite')"
```
