### ISSUE TITLE
RHS Function application with type arguments parse error

### ISSUE THREAD

**Issue by lunaleaps** [babel/babel#10082]
## Bug Report

**Current Behavior**
Unexpected token error parsing

**Input Code**

[Babel try it out](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoAekrgAFMAbCAd3LZgE8wk4AFHMAGc4AXjgBvcnDgA7FCCQAuOIJhRgMgObkAvhSoAqA1INwA4khlIoKBnDS5IVmfAAmSQWnVgYwCDIA6E0pyBxlVOABZDgBhR39LeDEACjABQWV-CCEAGjgiTGUACQAVSIAZABFgADcAUQYkBRcASlEAPgkpfKQYAFcoGTgAHldanswRcQKddoALJAYmCTkFHWHKMZr23X0wiJRRRGIYAMxoZhQoV2RMZOi48ATW0jhqOGZoAGtBUP8IgBGR2Q6FO5ygl2ut2GWSE7XusXizhgLVe70-UB-5BBGDOFyuNyQmBh6TypQq1XqjWaMHhDyRiVRbxoGKx-zcwJOeIhBOhsMEZLKVVqDSaiTpiKeyKZ7xKCzgoL6tjgfUEPDQKDVcBgcxQ8ABRBQWPISAAHpBYHB3JgUH0GPB6VLEqQgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cflow&prettier=false&targets=&version=7.4.5&externalPlugins=)

This is breaking line
```js
const d = React.forwardRef<Props, HTMLDivElement>(MyComponent);
```

**Expected behavior/code**
Expecting no parse error

**Babel Configuration (.babelrc, package.json, cli command)**
Believe I'm using Babel v7.4.5? That's what the bottom right version says on the Babel Try it out page. I suggest making it more explicit what version of Babel that site is using.

**Comment by nicolo-ribaudo** [comment]
The `// @flow` comment must be in the first line

**Comment by lunaleaps** [comment]
Oh sorry, that was indeed the issue, thank you!
