### ISSUE TITLE
Error: fork: argument fn is undefined or null

### ISSUE THREAD

**Issue by sahlouls** [babel/babel#10086]
## Bug Report

**Current Behavior**
When running test with `Jest`, despite all tests are successful, I still have a console error 

```
 console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:104
      Error: fork: argument fn is undefined or null
          at check (/home/dsdsd/repos/ggg-gui/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:26:11)
          at validateFnDescriptor (/home/dsdsd/repos/ggg-gui/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:446:3)
          at fork (/home/dsdsd/repos/ggg-gui/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:546:5)
```

my root saga
```
export default function* rootSaga(): SagaIterator {
  yield all([
    fork(mySaga1),
    fork(mySaga2),
    fork(mySaga3),
  ]);
}
```

The issue appear only when I added the `mySaga3`.

All is working perfectly, just this console error. 

Any idea where this error is coming from ? how to fix it ?

**Comment by nicolo-ribaudo** [comment]
How is this related to Babel?
I suggest adding some `console.log`s to understand what is undefined and why.

**Comment by sahlouls** [comment]
It was related to redux saga. Solved

**Comment by avilde** [comment]
Hi, @sahlouls .
I have the exact same problem. How did you solved it?

**Comment by sahlouls** [comment]
Hi @avilde 

Two workarounds worked for me, I choose the 1st
- Import the store where the sagaRoot is running in the test file
- do not run the sagaRoot when running tests
```
if (process.env.NODE_ENV !== 'test') {
  sagaMiddleware.run(rootSaga);
}
```

**Comment by avilde** [comment]
@sahlouls , I debugged the code and in the end I could not find the reason why one of my sagas is undefined for no reason.

In the end I rewrote my root saga generator:
```
function* rootSaga() {
  const sagas = [sagaOne, sagaTwo, sagaThree].filter(
    saga => saga !== undefined
  );

  yield all(sagas.map(saga => fork(saga)));
}
```
