### ISSUE TITLE
Unhelpful error message when forgetting to wrap JSX tags in parent node

### ISSUE THREAD

**Issue by gaearon** [babel/babel#1008]
Consider this:

```js
import React from 'react';

class OnOff extends React.Component {
  render() {
    return (
      <input type="checkbox" id="onoff" />
      <label for="onoff">Enable</label>
    );
  }
}
```

JSX compiler says `Adjacent JSX elements must be wrapped in an enclosing tag` but Babel prints `Unexpected token (7:13)`. Also the token it refers to is `for` argument which is confusing because the actual issue is due to tags not having an ancestor.

**Comment by sebmck** [comment]
Please report this upstream at [acorn-jsx](http://github.com/rreverser/acorn-jsx).
