### ISSUE TITLE
Module build failed: Error: Cannot find module 'babel-preset-env' - Did you mean "@babel/env"?

### ISSUE THREAD

**Issue by mh-abbassi** [babel/babel#10085]
When I run "npm run build" I get the error:

> "ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'babel-preset-env' from 'C:\djangoProjects\martin - Copy - Copy\martin' - Did you mean "@babel/env"?"

**This is my package.json file:**

    {
     "name": "martin",
      "description": "A Vue.js project",
     "version": "1.0.0",
      "author": "",
      "license": "MIT",
      "private": true,
      "scripts": {
        "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
        "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
      },
      "dependencies": {
        "aos": "^2.3.4",
        "axios": "^0.18.0",
        "babel-plugin-root-import": "^6.2.0",
        "node-sass": "^4.12.0",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.11",
        "vue-analytics": "^5.16.4",
        "vue-axios": "^2.1.4",
        "vue-chartist": "^2.2.0",
        "vue-i18n": "^8.11.2",
        "vue-meta": "^1.6.0",
        "vue-router": "^3.0.6",
        "vuetify": "^1.5.14",
        "vuex": "^3.1.1",
        "vuex-router-sync": "^5.0.0"
      },
      "browserslist": [
        "> 1%",
        "last 2 versions",
        "not ie <= 8"
      ],
      "devDependencies": {
        "@babel/cli": "^7.4.4",
        "@babel/core": "^7.4.5",
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/preset-env": "^7.4.5",
        "babel-loader": "^8.0.6",
        "babel-preset-stage-3": "^6.24.1",
        "cross-env": "^5.0.5",
        "css-loader": "^0.28.7",
        "file-loader": "^1.1.4",
        "vue-loader": "^13.0.5",
        "vue-template-compiler": "^2.4.4",
        "webpack": "^3.6.0",
        "webpack-bundle-tracker": "^0.4.2-beta",
        "webpack-dev-server": "^2.9.1",
        "write-file-webpack-plugin": "^4.5.0"
      }
    }

**and this is my .babelrc:**

     {
      "presets": [
        ["env", { "modules": false }],
        "stage-3"
      ],
      "plugins": [
        ["@babel/plugin-syntax-dynamic-import"],
        ["babel-plugin-root-import", {
          "rootPathSuffix": "src",
         "rootPathPrefix": "@"
        }]
     ]
    }
    

What's the best way to fix it?

**Comment by nicolo-ribaudo** [comment]
It should be `@babel/env`, not `env`. Also, the `stage-3` preset has been removed: https://github.com/babel/babel/blob/master/packages/babel-preset-stage-3/README.md

**Comment by nicolo-ribaudo** [comment]
```json
 {
  "presets": [
    ["@babel/env", { "modules": false }]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    ["babel-plugin-root-import", {
      "rootPathSuffix": "src",
     "rootPathPrefix": "@"
    }]
 ]
}
```
