### ISSUE TITLE
@babel/register does not load custom plugins when cached

### ISSUE THREAD

**Issue by ykadosh** [babel/babel#10081]
## Bug Report

**Current Behavior**
I'm running babel via `@babel/register`. In the configuration, I load a custom plugin that I wrote. 
When I run babel for the first time (there's no cache) - the plugin is loaded properly. However the next time I run babel (which is now operating with some cache) it doesn't load the plugin.
Deleting `node_modules/.cache` fixes it, but then the next time I run it it fails again.

**Input Code**

```js
require('@babel/register')({
  babelrcRoots: true,
  only: [...],
  plugins: [
    resolve(__dirname, './path/to/my/plugin'),
  ],
});
```
My Plugin

```js
console.log('required\n');
module.exports = () => ({
  name: 'my-plugin',
  pre: () => {
    console.log('loaded\n');
  },
  visitor: {
    ImportDeclaration: {
      enter(path) {
        console.log('parsed\n');
      },
    },
  },
});
```
**Expected behavior/code**
All log statements should be executed every time babel is run.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react'],
  plugins: [
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-function-bind',
    '@babel/plugin-transform-runtime',
    ['@babel/plugin-proposal-decorators', {'legacy': true}],
    ['@babel/plugin-proposal-class-properties', {'loose': true}],
    [
      'module-resolver',
      {
        'cwd': 'babelrc',
        'root': ['./'],
        'alias': {...},
      },
    ],
  ]
};
```

**Environment**
- Babel version(s): 7.4.0
- Node 10.15.1/npm 6.4.1
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `register`

**Comment by JLHwung** [comment]
It is expected. The cache will compare the modified time of the source file with the cache modified time and skip the transformation if the file is not modified. Therefore the plugin would not run when cache is valid.

Although we do not recommend it, but you can always disable the cache by
```js
require("@babel/register")({
  cache: false
});
```

**Comment by ykadosh** [comment]
@JLHwung Thanks for the explanation.
I'm trying to write a plugin that ignores certain imports. I need babel to ignore imports that it does not understand (i.e. `import './style.scss';`). 
Is that even possible? Or am I completely off?

**Comment by JLHwung** [comment]
You can remove the imports if it ends with `.scss`

https://astexplorer.net/#/gist/bb3cc383f1b7dadf5bf464f3c4f7c133/f83722b5eb7ccc1ce612e1d683a1741d9a76a31b

**Comment by ykadosh** [comment]
@JLHwung This is great, thank you so much!

**Comment by ykadosh** [comment]
One more question (if that's OK) - what if I have a named import and I want to assign an empty object to it?
For example:
```
import styles from './styles.scss';
```
If I remove this import completely, `styles` becomes `undefined`, and I need it to be an `Object`...

**Comment by JLHwung** [comment]
> I need it to be an Object

Babel is processing sources per file-level, which means it has no idea of what the `./styles.scss` will be. If you meant to interpret `./styles.scss` as a style Object which can be used later in any CSS-in-JS frameworks, then you can turn to the bundler (such as Webpack) plugins (such as css-loader).

Should you have further questions, please open a new question issues as it is out of the scope of the original one.

**Comment by ykadosh** [comment]
OK thanks!
