### ISSUE TITLE
Import with .mjs extension isn't renamed to .js in require() call

### ISSUE THREAD

**Issue by colinrotherham** [babel/babel#10089]
## Bug Report

**Current Behavior**
Based on the [documentation for Node.js v12.4](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions), we're now specifying `.mjs` extensions in all our imports so they're no longer extensionless:

>**Mandatory file extensions**
>A file extension must be provided when using the import keyword. Directory indexes (e.g. './startup/index.js') must also be fully specified.
>
>This behavior matches how import behaves in browser environments, assuming a typically configured server.

**Input Code**
```js
export { default as example } from './example.mjs';
```

This is so we can support `--experimental-modules` in Node.js v12 until it's unflagged, but we'd like to use Babel to maintain compatibility with Node.js v10 for now.

**Expected behavior/code**
I'd expect this to be transformed to:

```js
var _example = _interopRequireDefault(require("./example.js"));
```

But it's actually transformed to:
```js
var _example = _interopRequireDefault(require("./example.mjs"));
```

The require path retains `.mjs` even though the file has been renamed to `.js` by Babel.

```
Error: Cannot find module './example.mjs'
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    ['@babel/env', {
      shippedProposals: true,
      useBuiltIns: 'usage',
      corejs: 3,
      targets: {
        node: '10.16',
        browsers: [],
      },
    }],
  ],
};
```

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: v12.4.0
- OS: macOS 10.14.5
- Monorepo: no
- How you are using Babel: @babel/cli

```
npx babel src --out-dir dist
```

**Comment by loganfsmyth** [comment]
You can pass `--keep-file-extension` to the CLI to avoid the renaming.

**Comment by colinrotherham** [comment]
Sadly I need the renaming.

If the extension is kept as `.mjs` then Node.js expects an **ES module** not **CommonJS** when it's imported into another application.

E.g. If I try to import the new transpiled file:

```
Object.defineProperty(exports, "__esModule", {

ReferenceError: exports is not defined
```

Is there another option to instead change `require("./example.mjs")` to `require("./example")`?

Thanks

**Comment by nicolo-ribaudo** [comment]
Maybe `babel-plugin-module-resolver`'s [`stripExtensions`](https://github.com/tleunen/babel-plugin-module-resolver/blob/master/DOCS.md#stripextensions) (or `resolvePath`) would work.

**Comment by loganfsmyth** [comment]
Ah right, I misread, sorry. Babel doesn't do anything like that automatically, so it would be up to you to load a plugin to handle it.

**Comment by colinrotherham** [comment]
@nicolo-ribaudo Think that's more for resolution of non-native extensions `.ios.js`, `.android.js` that you can then strip out afterwards.

This one works though:
https://www.npmjs.com/package/babel-plugin-module-extension

```js
plugins: [
  ['module-extension', {
    mjs: 'js',
  }],
],
```

Thanks @loganfsmyth. Keep up the good work. Hopefully others can find this issue 😊
