### ISSUE TITLE
Unicode regexp doesn't match some unicode characters

### ISSUE THREAD

**Issue by jerrysu** [babel/babel#1009]
I had been using the following code to replace unicode-based characters with emoji rendered with React:

```
renderWithEmoji() {
  var output = [];
  text.replace(/./ug, function(character) {
    if (character in emoji) {
      output.push(<Emoji character={character} />);
    } else {
      output.push(character);
    }
  });
  return output;
}
```

I must have updated babel in my `package.json` because suddenly this code stopped working for most emoji characters. I decided to take some time to investigate this issue today.

With this file, `test.js`:

```
/./u.test('💩');
```

When you run `babel test.js`, the output is:

```
"use strict";

/(?:[\0-\t\x0B\f\x0E-\u2027\u202A-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/.test("💩");
```

*Note: If you execute this code, it returns `false`*

When you run `regexpu -f test.js`, the output is:

```
/(?:[\0-\t\x0B\f\x0E-\u2027\u202A-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/.test('💩');
```

*Note: If you execute this code, it returns `true`*

If you look closely at the regular expressions, it looks like a chunk in the middle is missing when transpiled by babel.

I've looked at regexpu@1.1.2 and confirmed that `rewritePattern` works as expected, which makes me believe that something downstream in babel may be affecting the pattern.

It may also be worth noting that the test for unicode regexes were fixed recently https://github.com/babel/babel/commit/999baf2888a9cedbc641c058049bb9c197961beb with the regression.

**Comment by sebmck** [comment]
Running:

```javascript
console.log(require("regexpu").rewritePattern("."));
```

returns:

```
(?:[\0-\t\x0B\f\x0E-\u2027\u202A-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])
```

Which is what Babel rewrote the regex to. I'm clueless when it comes to unicode so you're either doing something wrong or it's a bug in `regexpu`.

/cc @mathiasbynens

**Comment by sebmck** [comment]
Running

```javascript
console.log(require("regexpu").transpileCode("/./u"));
```

returns your expected output however:

```javascript
/(?:[\0-\t\x0B\f\x0E-\u2027\u202A-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/
```

**Comment by sebmck** [comment]
Actually no my bad, I spoke out of turn, my apologies. The `u` flag was being pulled before `regexpu.rewritePattern` was being called. I've pushed out 4.7.11 that fixes this issue, thanks!

**Comment by jerrysu** [comment]
Thanks for fixing this so quickly! :+1:
