### ISSUE TITLE
Unexpected behavior with react props. (Reopened)

### ISSUE THREAD

**Issue by sushant23** [babel/babel#10090]
I did already post this issue before [here](https://github.com/babel/babel/issues/7481) but could not create a minimal example so I am reopening this issue. 
[Here](https://github.com/sushant23/final_form_build_test) is a minimal project to recreate this issue.
To reproduce this issue clone the project and run
```
npm i
npm run build
```

Apparently `transform-es2015-modules-commonjs` is causing the build to fail.

**Comment by nicolo-ribaudo** [comment]
I clones that repo, I could reproduce the bug but it seem to be fixed by upgrading Babel.

You can download the git patch to upgrade it from https://gist.github.com/nicolo-ribaudo/45b1eb0a1b195e8d807440e23bad9301, then run
```
git apply path-to-downloaded-file.patch
```
```
rm -rf node_modules
```
```
npm ci
```
```
npm run build
```
and it should work. You can also try
```
BABEL_ENV=production npm run build
```
