### ISSUE TITLE
Script of decorated class unused anywhere else gets eliminated in biuld

### ISSUE THREAD

**Issue by Haaxor1689** [babel/babel#10096]
## Bug Report

**Current Behavior**
Decorated class that is not instantiated anywhere directly seems to be not compiled into to the final bundle. From the example below the `Foo` file will get eliminated from the build process, which in turn means that neither it's decorator is called nor the `console.log` in it's file. The `Goo` class seems to be ok after I call it's constructor somewhere in the code.

**Input Code**
[Typescript playground](https://typescript-play.js.org/?experimentalDecorators=true#code/PTAEBMFMGMHsCcCGAXBA6ZBnAUCUBaQo4k0s8i3MASwFsAHBZUAb1ADVF5rEA7ZADSgAKgE96kTtz7MAvqABm8WLVAAiNMABuXHvzUBubLgBUkAB6N4yE2B3xQ0VPEwAuVqADaYiaGq8RcUldGQBddxZeSAB3UAAKNESuAHM3UD5RT1CASncAUXNkJCcAHik9QQ9kIPcfSFBZAD55eQBeVnlETHTeUSNgM0smW0UAV14nalgAqDgkZxK60AtkSF5wbrrymUa46olaoOzWbFAz0HhIZFH4AIVxyenF5cK1jdYo2ISk+FT3DKyuQ4IX4TTicF4mCKoycCFqxxYp3OyIhmFgABtIGh0bBknEAAYAEhY+0g8lmCBQCHx2SMyJRzm67TYiTQsJcQk8pPCjmmUPgMOcDTp9LOl2ut15kOh7JFZ1k2AVVFAADFYLAMDg8BQdbq9URlXQrMw2BT5ggGoplKoNMAzVT4IZjAABe3OOJqNWwNTZUwWY0jaDorrdL1VGrqL1qUDtT3q6MK1EYrE4vFqBTx2nGPAAcXVmuV+qLxYNeCNTA8bot8iUKnUmirjqM2FdMEp7rUee9voG-uGYCDIdAXfDB3UXejsYnDWwScx2NxHuSmebeHsFQL2pL291hoYFbYYZr1vrwCj-Ro++sHhHx7rtonq8GAbApOB0n4MdV6tAAB9h+q-TPv2oBvlsILMO02z8J4aikmooSrmAtCIP4m5gDumHkHuxoeOy3R3jaDZtuaTY4QeAGwJatZEcAj7GKizDLlR7SfJRcRZnOKaLsxnF8swGYsaAbH4bBUahBxRhcQueKCbSQA)

**Expected behavior/code**
The `Foo` file from the example shouldn't be excluded because it has a decorator.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
    presets: [
        "@babel/preset-react",
        "@babel/preset-typescript",
        ["@babel/preset-env", { modules: false }]
    ],
    plugins: [
        ["@babel/plugin-proposal-decorators", { legacy: true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-transform-runtime",
        "babel-plugin-styled-components"
    ],
    env: {
        test: {
            plugins: ["@babel/plugin-transform-modules-commonjs"]
        }
    }
};
```

**Environment**
- Babel version(s): v7.3.4
- Node/npm version: Node v10.15.3/npm v6.9.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: webpack build

**Possible Solution**
If I am on the right track of what's causing the issue (the use decorator not marking the script as used) it would be nice to enable this option. Many decorators can have side effects. Other possible solution would be to able to mark scripts that should not be excluded from build even if they are evaluated by babel as not used.

**Additional context/Screenshots**
Since the provided example is all in one file, all works as expected. I wasn't able to find a proper playground client that allows typescript, decorator, multiple files and babel transpilation at once.

**Comment by loganfsmyth** [comment]
It's not clear what part of Babel you think is stripping things out. Would you be able to make a repository that clearly demonstrates the issue?
