### ISSUE TITLE
helper plugin utils does not support babel 7

### ISSUE THREAD

**Issue by RookieDevAum** [babel/babel#10106]
## Bug Report

**Current Behavior**
on application startup on dev env, the application gives an error 
Requires Babel "^7.0.0-beta.41", but was loaded with "7.4.5". You'll need to update your @babel/core version.

**Input Code**
index.js/lib.js
if (version.slice(0, 2) === "7.") {
    err = new Error(`Requires Babel "^7.0.0-beta.41", but was loaded with "${version}". ` + `You'll need to update your @babel/core version.`);
  } 

```js
var your => (code) => here;
```

**Expected behavior/code**
I expect the plugins to be supported. If not, then it will not work with any Babel 7 version, be it beta or release.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: 8
- OS: MacOS
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: loader

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by RookieDevAum** [comment]
If and else in index.js. No matter what comes in with Babel 7, it will throw an error all the time.
if (version.slice(0, 2) === "7.") {
    err = new Error("Requires Babel \"^7.0.0-beta.41\", but was loaded with \"" + version + "\". " + "You'll need to update your @babel/core version.");
  } else {
    err = new Error("Requires Babel \"" + range + "\", but was loaded with \"" + version + "\". " + "If you are sure you have a compatible version of @babel/core, " + "it is likely that something in your build process is loading the " + "wrong version. Inspect the stack trace of this error to look for " + "the first entry that doesn't mention \"@babel/core\" or \"babel-core\" " + "to see what is calling Babel.");
  }

**Comment by nicolo-ribaudo** [comment]
That's really strange, that code only runs when you are using an older Babel version. Can you share an example which reproduces the issue?

**Comment by loganfsmyth** [comment]
Please post the whole error message. The stack trace can also provide very useful information.

**Comment by j-arens** [comment]
I'm running into this same issue. My use case is a little convoluted so I'll try to boil it down as much as I can. Essentially I've got a project where I'm writing components with JSX, but the components in folder A need to be transformed using `wp.element.createElement` as the pragma, and the components in folder B need to be transformed with the standard `React.createElement` pragma.

I've setup a a custom babel-loader using `babel-loader.custom` to dynamically switch the configuration during webpack compilation.

```js
const loader = require('babel-loader');

// we need to run wordpress' special jsx pragma for gutenberg stuff,
// all other files can use the normal react preset

module.exports = loader.custom(babel => ({
  config({ options }) {
    const { filename } = options;
    if (/\/src\/js\/gutenberg/.test(filename)) {
      const jsx = require('@babel/plugin-transform-react-jsx');
      return {
        ...options,
        plugins: [...options.plugins, jsx.default(babel, { pragma: 'wp.element.createElement' })],
        presets: options.presets.filter(preset => preset.file.request !== '@babel/preset-react'),
      };
    }
    return options;
  },
}));
```

Looking at the source for the transform-react-jsx plugin I can see that `api.assertVersion(7);` is the first thing that happens. Which in turn is calling the `throwVersionError` function on line 47.

Given this chunk of code in the `declare` function though I would expect that the `throwVersionError` function would never be called.

```js
if (!api.assertVersion) {
      // Inject a custom version of 'assertVersion' for Babel 6 and early
      // versions of Babel 7's beta that didn't have it.
      api = Object.assign(copyApiObject(api), {
        assertVersion(range) {
          throwVersionError(range, api.version);
        },
      });
    }
```

If I `console.log(babel.assertVersion)` in my custom babel loader it turns out that `assertVersion` is indeed undefined. I'm not sure why, I'm using @babel/core 7.4.5.

**Comment by nicolo-ribaudo** [comment]
`assertVersion` is defined in the `api` object passed to the plugins, not in the exports of `@babel/core` (which is the object you are passing to the JSX plugin).

You should never instantiate plugins yourself, they should be "opaque" to the world outside of `@babel/core`. You should do something like this:
```js
module.exports = loader.custom(babel => ({
  config({ options }) {
    const { filename } = options;
    if (/\/src\/js\/gutenberg/.test(filename)) {
      const jsx = require('@babel/plugin-transform-react-jsx');
      return {
        ...options,
        plugins: [
          ...options.plugins,
          [jsx, { pragma: 'wp.element.createElement' }]
        ],
        presets: options.presets.filter(preset => preset.file.request !== '@babel/preset-react'),
      };
    }
    return options;
  },
}));
```
Babel will then take care of instantiating them and passing the correct parameters.

**Comment by j-arens** [comment]
Ah gotcha, that seems to have done the trick. Thanks for the help!

**Comment by nicolo-ribaudo** [comment]
@RookieDevAum Can you post the full error message and an example of how you are using the plugin and Babel?
