### ISSUE TITLE
Computed properties + Symbols

### ISSUE THREAD

**Issue by timoxley** [babel/babel#1010]
Symbols work fine as regular keys:

```js
> let key = Symbol('key')
undefined
> let a = {}
undefined
> a[key] = 'value'
'value'
> a
{}
> Object.getO
> Object.getOwnPropertySymbols(a)
[ {} ]
> JSON.stringify(a)
'{}'
```

So far so good but how about computed properties:

```js

> b = {[Symbol('anotherkey')]: 'value'}
{ 'Symbol(anotherkey)_r.7hg3clbbmf17nwmi': 'value' }
> Object.getOwnPropertySymbols(b)
[ {} ]
> JSON.stringify(b)
'{"Symbol(anotherkey)_r.7hg3clbbmf17nwmi":"value"}'
```
Symbols don't seem to work correctly as computed properties.
Seems to come down to computed properties being enumerable, regardless whether their contents are Symbols or not:

```js
> Object.getOwnPropertyDescriptors(a)
{ 'Symbol(key)_q.dfiwdc4nm9t9ms4i':
   { value: 'value',
     writable: true,
     enumerable: false,
     configurable: true } }
> Object.getOwnPropertyDescriptors(b)
{ 'Symbol(anotherkey)_r.7hg3clbbmf17nwmi':
   { value: 'value',
     writable: true,
     enumerable: true,
     configurable: true } }

```

Seems like a faulty artifact of babel transformation to me, but I checked the spec quickly and can't find any explicit references to the behaviour of Symbols in computed properties, so I'm not exactly sure what the correct behaviour should be here.

**Comment by sebmck** [comment]
What babel/node/io version? Are you using the runtime?

**Comment by timoxley** [comment]
`babel@4.7.9`
This is using `babel-node`.

**Comment by timoxley** [comment]
```
> echo "console.log(JSON.stringify({[Symbol('anotherkey')]: 'value'}))" > t.js && babel-node t.js && rm t.js
{"Symbol(anotherkey)_q.pba23r6ghu8tzkt9":"value"}
```

**Comment by zloirock** [comment]
Symbol polyfill uses setters in `Object.prototype` for prevent enumerability. Computed properties uses `defineProperty` and ignores setters.

**Comment by sebmck** [comment]
Thanks for the suggestion @zloirock :smile: Fixed.

**Comment by zloirock** [comment]
@sebmck I wrapped necessary methods, for correct behavior in this https://github.com/zloirock/core-js/issues/45 and the similar cases need revert this change and add to `runtime` `Object.{create, defineProperty, defineProperties}`.

**Comment by sebmck** [comment]
@zloirock Open an issue so I don’t forget please.
