### ISSUE TITLE
Add a clarification to `@babel/plugin-proposal-object-rest-spread` page.

### ISSUE THREAD

**Issue by catamphetamine** [babel/babel#10105]
The rest spread proposal is at Stage 4:
https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal

Still, the plugin page says nothing:
https://babeljs.io/docs/en/next/babel-plugin-proposal-object-rest-spread.html

Is it still needed?
Is it not needed anymore?
Is it considered deprecated?

**Comment by catamphetamine** [comment]
Update: seems that it is indeed deprecated.
I guess the docs page should reflect that.

https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/available-plugins.js#L40
```js
  "proposal-object-rest-spread": require("@babel/plugin-proposal-object-rest-spread"),
```

**Comment by nicolo-ribaudo** [comment]
It's not deprecated; but it is included in preset-env.

**Comment by catamphetamine** [comment]
@nicolo-ribaudo 

> It's not deprecated; but it is included in preset-env.

I'd say that's pretty much the definition of "deprecated".

**Comment by catamphetamine** [comment]
@nicolo-ribaudo I see. I'd say it's deprecated to be used in a Babel config then.

**Comment by nicolo-ribaudo** [comment]
It's not deprecated, as any other plugin for stable features. Many people use presets with custom plugin instead of using preset-env.
