### ISSUE TITLE
Add optional parsing support for V8 intrinsics

### ISSUE THREAD

**Issue by mathiasbynens** [babel/babel#10104]
## Feature Request

V8 exposes [a number of intrinsics](https://cs.chromium.org/chromium/src/v8/src/runtime/runtime.h?rcl=c843aa75886abbd9aa4ea65818ece3d661ab2ed3) when the `--allow-natives-syntax` flag is set. Examples include:

```js
%DebugPrint(object);
%PrepareFunctionForOptimization(fn);
```

Because we generally don't want to encourage the use of these intrinsics in production code, they rely on non-standard syntax; standard JS parsers (including Babel's) consider this to be a modulo operator without a left-hand side. [Here's how V8 implements parsing support based on the flag.](https://cs.chromium.org/chromium/src/v8/src/parsing/parser-base.h?l=1785-1789&rcl=5e14bd7ec82b9021667402cc5c92310230bea48c)

However, some research projects intentionally make use of these V8-specific intrinsics, and of course the V8 code base itself makes use of them extensively in JS tests.

It would be great if Babel could optionally support this syntax extension, similar to how it supports JSX and Flow syntax.

**Describe alternatives you've considered**

If this seems more feasible as a Babel parser plugin, that'd be a good solution too! I just wanted to discuss this proposal with the core team first.

**Teachability, Documentation, Adoption, Migration Strategy**

I'd be happy to write some docs if the team decides this makes sense in babel/parser core.

**Comment by nicolo-ribaudo** [comment]
I 100% agree with this proposal, I have thought about it more than once already.

> If this seems more feasible as a Babel parser plugin, that'd be a good solution too!

This should be an internal plugin.

**Comment by jridgewell** [comment]
@nicolo-ribaudo Didn't we recently do this? Maybe it was only for babel-templates?

**Comment by nicolo-ribaudo** [comment]
We only added some syntax for templates: `%%name%%`. While both this and V8's use `%`, they are different.

**Comment by JLHwung** [comment]
I would like to work on this if it have not been assigned yet.

The V8 Intrinsic syntax is defined as
```
// CallRuntime ::
//   '%' Identifier Arguments
```

Here is a proposed AST Node Solution which I borrow from the `AwaitExpression`

```js
interface V8IntrinsicExpression {
  type: "V8IntrinsicExpression",
  argument: CallExpression
}
```

For example, the AST of
```js
%DebugPrint()
```
should be (`loc` is trivial so neglected in the following example)
```json
{
  "type": "ExpressionStatement",
  "expression": {
      "type": "V8IntrinsicExpression",
      "argument": {
         "type": "CallExpression",
         "callee": {
              "type": "Identifier",
              "name": "DebugPrint"
         },
         "arguments": []
     }
  }
}
```
On implementation of such syntax extension, I suggest reuse the `modulo` token, start new node in `parseExprSubscripts`, check if `parseCallExpressionArguments` is subsequently invoked and then finish the node. It should bail if a call expression does not immediately follow the `modulo` token.

Note: a mixture of `modulo` and `V8Intrinsic` syntax would resemble [Placeholder syntax](https://github.com/babel/babel/issues/9112#issuecomment-453275595) but luckily there is no ambiguity here since `Placeholder` is an expression and `modulo` is an infix operator. For example
```js
a %% StringParseInt("42", 10) %% StringParseInt("42", 10)
```
can not be a valid `Placeholder` syntax and vice versa.
```
a = %% name %%
```

**Comment by loganfsmyth** [comment]
I'd probably be more in favor of this being a CallExpression with a new type of `callee` being `V8IntrinsicIdentifier` or something.

**Comment by nicolo-ribaudo** [comment]
> Note: a mixture of modulo and V8Intrinsic syntax would resemble Placeholder syntax but luckily there is no ambiguity here since Placeholder is an expression and modulo is an infix operator.

Lets just ban the `placeholders` plugin from being enabled at the same time as the `v8-intrinsics` plugin, to avoid an easy source of confusion.

**Comment by JLHwung** [comment]
> I'd probably be more in favor of this being a CallExpression with a new type of callee being V8IntrinsicIdentifier or something.

I agree on this neat solution. It results to simpler AST nodes.

> Lets just ban the placeholders plugin from being enabled at the same time as the v8-intrinsics plugin, to avoid an easy source of confusion.

True. While we ban the `placeholders` plugin, `v8instrinsic` should work with other plugins. As of the plugin order, I think it would be good to fit in any position as long as it comes after `estree`.
