### ISSUE TITLE
Error: Requires Babel “^7.0.0-0”, but was loaded with “6.26.3” when rendering react component using express-react-views package

### ISSUE THREAD

**Issue by renji** [babel/babel#10108]
I am using express-react-views package to render react components in serverside(NodeJs). I tried to render the react component as in the example https://github.com/reactjs/express-react-views/tree/master/examples/dynamic. I downloaded the files from there and run it by the commands:

npm install
npm start

But it raises an error on npm start. The error is:

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset:

I tried upgrading babel as per the link https://github.com/babel/babel-upgrade. Still there is the same error.

How can I fix this?

My package.json file

{
  "name": "dynamic-views",
  "version": "0.1.0",
  "description": "Example of creating a dynamic app using express-react-views",
  "author": "Chris Johnson <tenorviol@yahoo.com>",
  "private": true,
  "scripts": {
    "start":
      "browserify -t babelify views/main.js --standalone main -o public/main.js  && node app.js"
  },
  "dependencies": {
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babelify": "^7.3.0",
    "browserify": "^14.3.0",
    "express": "^4.15.3",
    "express-react-views": "file:../../",
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
  }
}

**Comment by nicolo-ribaudo** [comment]
Run `npx nls why babel-core` to find out which package is using Babel 6, and then update it.

**Comment by renji** [comment]
I run npx nls why babel-core and got the result as the babelify package is using babel-core.
babelify > babel-core@6.26.3.

How do I update  babel-core@6.26.3 to babel-core@7.0.0?

**Comment by nicolo-ribaudo** [comment]
Try updating babelify to v10 and install `@babel/core`

**Comment by renji** [comment]
Do you mean try running 
npm install --save-dev babelify @babel/core 
will resolve my issue?

**Comment by nicolo-ribaudo** [comment]
Yes, but first delete babelify from your dependencies.

**Comment by renji** [comment]
Yes. Thank You...Working very very well now
