### ISSUE TITLE
babel CLI - babel-node repl - can it be improved to handle multi-line?

### ISSUE THREAD

**Issue by jeffbski** [babel/babel#1011]
I really like the babel project and babel-node is a great idea.

One thing I noticed about the babel-node repl is that it doesn't support multi-line statements like the normal node repl.

Often syntax needs to be multi-line or I like to copy and paste from elsewhere too.

Could babel-node repl be improved to handle multi-line or is that a limitation of transpiling?

Thanks for an awesome project!

**Comment by sebmck** [comment]
Most likely. Not sure how to enable it with the [REPL](https://nodejs.org/api/repl.html) API. PRs accepted :smile: See [babel-node](https://github.com/babel/babel/blob/master/bin/_babel-node#L114-139) for the relevant file.

**Comment by sebmck** [comment]
Closing this, PRs accepted.
