### ISSUE TITLE
babel 7 docs says run "npx babel" but that shows error message

### ISSUE THREAD

**Issue by mo** [babel/babel#10114]
The documentation for babel 7.4.0 mentions several examples commands starting with "npx babel ..." here:
https://babeljs.io/docs/en/babel-cli

However, if run "npx babel" it prints "You have mistakenly installed the `babel` package, which is a no-op in Babel 6."

What is the babel7 equivalent of "npx babel"? It would be nice to have the babel7 docs be updated to something that works for babel7. Thanks.

**Comment by loganfsmyth** [comment]
@mo Have you already installed `@babel/cli` into your project?

**Comment by mo** [comment]
This happens regardless of where I run the command, for example even if I do "mkdir ~/test123 ; cd ~/test123 ; npx @babel/cli" I still get the same error, i.e. it executes the "cli" binary from $PATH

Just to see what would happen I also did "sudo mv /usr/bin/cli /usr/bin/cli2" and then tried to run it again:

$ npx @babel/cli
npx: installed 153 in 6.213s
Cannot find module '@babel/core'

...so the behavior of "npx" seems to be "look in $PATH if there is something called "cli" and if so then run it.

btw, my versions are:
$ npx --version
6.9.0

$ node --version
v10.15.0

**Comment by mo** [comment]
I also did "npm install -g npx" now so I got:
$ npx --version
10.2.0

...but that version has the same bug too.

**Comment by loganfsmyth** [comment]
You'll need to install `@babel/core` as well.

**Comment by mo** [comment]
I just read the npx man page and realized that I had misunderstood how npx works. I always thought you typed "npx foo" to execute the main cli script from package named "foo" but in reality it seems that "npx foo" means run "foo" if it exists on the $PATH, otherwise try to guess what package "foo" comes from, install that and run the "foo" binary from that.

**Comment by mo** [comment]
For posterity; the correct way to invoke babel7 via npx was:

```
npx -p @babel/cli -p @babel/core babel SOME PARAMS HERE
```
