### ISSUE TITLE
Typescript export gets lost when interface and JS object share same name

### ISSUE THREAD

**Issue by jwalton** [babel/babel#10112]
## Bug Report

**Current Behavior**

This is a regression that's broken somewhat recently - I just updated everything in my lockfile and it stopped working.  It's also kind of an obscure issue, but it just bit me.  :)

Basically, if you have an `interface Foo` and a `const Foo`, and you try to `export {Foo as Thing}`, you ought to get an `exports.Foo = ...` in the output, and (as of some recentish change) you do not.

**Input Code**

```ts
export interface Foo {
    value: number;
}

const Foo: Foo = {
    value: 7,
};

export { Foo as TheThing };
```

**Expected behavior/code**

[The Typescript compiler](https://www.typescriptlang.org/play/#src=export%20interface%20Foo%20%7B%0D%0A%20%20%20%20value%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20Foo%3A%20Foo%20%3D%20%7B%0D%0A%20%20%20%20value%3A%207%2C%0D%0A%7D%3B%0D%0A%0D%0Aexport%20%7B%20Foo%20as%20TheThing%20%7D%3B) generates the export, but babel does not:

```
"use strict";

const Foo = {
  value: 7
};
```

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc is:

```
    const babelConfig = {
        presets: [
            '@babel/react',
            ['@babel/env', { targets: { node: '10' } }],
            '@babel/preset-typescript',
        ],
        sourceMap: true,
        sourceRoot: path.resolve(root, 'src'),
        plugins: [
            '@babel/proposal-class-properties',
            '@babel/plugin-syntax-dynamic-import',
            'babel-plugin-dynamic-import-node',
            'babel-plugin-styled-components',
        ],
        // Need this or babel will accidentally pick up `npm link`ed folders.
        only: ONLY,
    };
```

Relevant versions from package.json:

```
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.1.0",
    "@babel/register": "^7.4.4",
```

But, as I said, just pushed these all to latest in the lockfile.

**Environment**
- Babel version: 7
- Node/npm version: Node 10.14.1/npm 6.9.0
- OS: OSX 10.14.4
- Monorepo: No
- How you are using Babel: CLI

**Comment by nicolo-ribaudo** [comment]
This has been fixed: https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQgjgG8AoOSuAN0wBsBXYALjiQYFsAjNAbjIC-ZMtghIAzvEIRW0uAF5SFKrUYs4AdgA0g_mVCRYpAkTiZxcACoALYDeQBzOAN5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-transform-typescript%407.6.0
