### ISSUE TITLE
@babel/preset-typescript does not export overloaded function (differs from `tsc`)

### ISSUE THREAD

**Issue by ford04** [babel/babel#10116]
## Bug Report

**Current Behavior**
Given an overloaded exported function
```
function overload(str: string);

function overload(str?: string) {
  return str || "Hello world";
}

export { overload };
```

, the transpiled version of the code does not export `overload` anymore.
```
function overload(str) {
  return str || "Hello world";
}
```

**Input Code**
 https://github.com/ford04/babel-typescript-function-overload-sample
`npm i && npm run build:babel && npm run build:tsc`

**Expected behavior/code**
The `overload` function will be exported in the same manner like when compiled with `tsc` directly (see repo). The typescript overloaded types should be just stripped off.

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc
```json
{
  "plugins": [],
  "presets": ["@babel/typescript"]
}
```

cli

```
babel operators.ts --out-file operators-babel.js
```

**Environment**
- Babel version(s): {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/preset-typescript": "^7.3.3"
}
- Node/npm version: v12.4.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `cli`

**Workaround**
As workaround, I exported each of the overloads like this
```
export function overload(str: string);
export function overload(str?: string) {
  return str || "Hello world";
}
```
, which worked. But I think, we should really have a uniform build, regardless if `tsc` or the preset is used. It gave me an hour of headaches, where a bigger build broke because of this nuance.

**Comment by Macil** [comment]
This looks related to https://github.com/babel/babel/issues/10112. In both cases, there's two things by the same name, one of the things is supposed to get removed by the typescript plugin, the name is being exported, and the typescript plugin is removing the export too.

**Comment by nicolo-ribaudo** [comment]
Can you try updating your babel-related dependencies? It seems to work:
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAMwK4DsDGMCWEVwgN2CgBsIBDAEwAoBnGKALjjqkxQHMBKAbgChRIsRKgzZcBIqUq16AfiYs2XOAG9ecOFGAwkUXCzgAfQ3ABEACWDFScAO7RiFU3wC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.5.5

**Comment by ford04** [comment]
Yes, it works now by upgrading manually to `"@babel/plugin-transform-typescript": "^7.5.5"`, thank you!
