### ISSUE TITLE
JS comments are stripped from JSX if no other tokens in the block

### ISSUE THREAD

**Issue by skyboyer** [babel/babel#10118]
## Bug Report

**Current Behavior**
It's an edge case of already closed bug #7153
If block contains only JS comments and no other tokens available then comments will be stripped from transpiled code.

**Input Code**
It's reproducible in Babel online sandbox as well

```js
function render() {
  return (
    <div>
      {/* A JSX comment */}
    </div>
  )
}

function render2() {
  return (
    <div>
      {null/* A JSX comment */}
    </div>
  )
}
```

**Expected behavior/code**
I'd expect both code blocks having JS comment included.

**Actual behavior/Code output**
```js
function render() {
  return React.createElement("div", null);
}

function render2() {
  return React.createElement("div", null, null
  /* A JSX comment */
  );
}
```

**Environment**
- Babel version(s): 7.4.5

**Comment by tanhauhau** [comment]
I wonder how you would want the comment to be, because it's not a children

**Comment by skyboyer** [comment]
@tanhauhau thanks, good point. 

how about 
```javascript
function render() {
  return React.createElement("div", null, undefined /* a JSX comment */);
}
```
?
Telling the truth I cannot say what'd be a benefit. I run into topic at SO https://stackoverflow.com/questions/56666638/how-can-i-keep-comments-when-minifying-my-react-code and then met #7153 while looking around. Unfortunately OP did not come here to provide motivation for such a goal. 

So I just believe this would be consistent with changes in scope of #7153, that's it.

**Comment by tanhauhau** [comment]
```js
function render() {
  return React.createElement("div", null, undefined /* a JSX comment */);
}
```

is actually 
```js
function render() {
   return (
       <div>
           {undefined /* a JSX comment */}
       </div>
   );
}
```
and will have error with React, because React do not render `undefined`

**Comment by skyboyer** [comment]
I see. Shame on me not checked that in first place.
