### ISSUE TITLE
will @babel/plugin-syntax-dynamic-import  support "assets host"?

### ISSUE THREAD

**Issue by jinggk** [babel/babel#10122]
## Feature Request
when i use webpack with babel, i have this config:
```
output: {
        path: ASSETS_PATH,
        filename: '[name]-[hash].js',
        chunkFilename: '[name]-[chunkhash].js',
        publicPath:'/web_static',
    },
```
as you can see, the publicPath here is '/web_static', i publish the assets online, and then i use async import like this:
```
const Utils = await import('./utils');
```
but then, something is wrong, console show that js url is 404,because we use cdn where to push our static assets, when we use html we will replace the url with cdn assets host,but with import it don't work expect, i think because the new script is only use publicPath, so,can this plugin support diffrent mode, for example:
```
["@babel/plugin-syntax-dynamic-import", {
    host: true,
    production: 'https://cdn.xx.com' // it's just an example
}]
at same time, i don't think it need to support development config~
``` 
i hope this will be supported~~~ thanks for your hard work~

**Comment by jinggk** [comment]
at sane time, i know there are some ways to void this problem, such as config diffrent publicPath,but i also think this is useful~

**Comment by nicolo-ribaudo** [comment]
This is a good idea for a third-party plugin.
It doesn't fit the scope of `@babel/plugin-syntax-dynamic-import`, since official plugins are only for features defined in the ECMAScript specification.

**Comment by jinggk** [comment]
> This is a good idea for a third-party plugin.
> It doesn't fit the scope of `@babel/plugin-syntax-dynamic-import`, since official plugins are only for features defined in the ECMAScript specification.

you are right, i will think of it & try it~

**Comment by nicolo-ribaudo** [comment]
If you need any help, you can ask in our slack channel.
