### ISSUE TITLE
IE8 polyfilled when targets option specify ie9

### ISSUE THREAD

**Issue by chillyond** [babel/babel#10129]
## Bug Report

**Current Behavior**
![image](https://user-images.githubusercontent.com/11400674/60121654-27dabf00-97b6-11e9-830e-f580440522a3.png)

**Input Code**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "chrome": "55",
          "ie": "9"
        },
        "useBuiltIns": "usage",
        "corejs": 2,
        "debug": true
      }
    ]
  ]
}

```

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: v10.13.0
- OS: OSX 10.13.4
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: webpack

**Comment by nicolo-ribaudo** [comment]
What does the `debug` option log? It might need that that fille is imported by another polyfill which is needed for your targets.

**Comment by chillyond** [comment]
> What does the `debug` option log? It might need that that fille is imported by another polyfill which is needed for your targets.

The entry module and the `debug` option logs:
![image](https://user-images.githubusercontent.com/11400674/60146488-5da29680-97fc-11e9-97cb-243fbc708eb4.png)

**Comment by zloirock** [comment]
https://github.com/babel/babel/pull/7646#discussion_r179333093

**Comment by nicolo-ribaudo** [comment]
Closing, since that polyfill is an internal `core-js` dependency and not something that we inject (https://github.com/babel/babel/pull/7646#discussion_r179474561).
