### ISSUE TITLE
parse the files in the node_modules folder

### ISSUE THREAD

**Issue by sxt1992** [babel/babel#10137]
on file `babel/packages/babel-core/src/config/files/package.js` line 21

Sometimes we need to parse the files in the node_modules folder. So, I want you to provide a configurable place, not a fixed one.

**Comment by nicolo-ribaudo** [comment]
What exactly do you want to configure?

**Comment by sxt1992** [comment]
> What exactly do you want to configure? What is your current config?

I failed with `. babelrc` , succeeded with `babel.config.js`
