### ISSUE TITLE
Is there a way to set destructuring to double equals?

### ISSUE THREAD

**Issue by mqliutie** [babel/babel#10131]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Source code:
```
const { a = [] } = infoItem;
```
after babel:
```
"use strict";

var _infoItem = infoItem,
    _infoItem$a = _infoItem.a,
    a = _infoItem$a === void 0 ? [] : _infoItem$a;
```

There is `_infoItem$a === void 0` , that is triple equals. Can I change to double equals?

**Describe the solution you'd like**
I don't know how to do 

**Describe alternatives you've considered**
Now , I  can only do this:
```
const a  = infoItem.a  || [];
```

**Comment by nicolo-ribaudo** [comment]
That's not how JavaScript works. I suggest writing your own plugins tranforms
```js
const { a = [] } = infoItem;
```
to
```js
const { a: _a } = infoItem;
const a = _a == void 0 ? [] : _a;
```

and then let babel transpile it.

**Comment by tanhauhau** [comment]
What is the reason to transpile to double equals in the first place?

**Comment by mAAdhaTTah** [comment]
@tanhauhau Default assignment only applied to `undefined`, not `null`.

```js
const { a = 1 } = { a: null };
a === null // true
```

**Comment by tanhauhau** [comment]
Yes, that's how default assignment supposed to work.
If you want a custom behaviour of the default assignment syntax, you would have to implement a custom babel transform plugin yourself.

**Comment by existentialism** [comment]
Going to close this for now, @mqliutie let us know if you have any more questions!

**Comment by mqliutie** [comment]
@nicolo-ribaudo  Thanks for your suggestion

I have not written plugin of babel... So, I don't know if I wrote the right thing.
The code is as follows, It did what I expected.
```
module.exports = function () {
    return {
        name: 'transform-destructing-for-null',
        visitor: {
            ConditionalExpression(path) {
                path.traverse({
                    BinaryExpression(path) {
                        const node = path.node;
                        if (node.right.type === 'UnaryExpression' && node.right.operator === 'void') {
                            node.operator = '==';
                        }
                    },
                });
            }
        }
    };
};
```
The source code as follow :
```
const result = { a: null };
const result1 = { b: undefined };
const result2 = { c: 1 };

const { a = 'a' } = result;
const { b = 'b' } = result1;
const { c = 'c' } = result2;

if (a === 'a') {
    console.log(`a === 'a'`);
}

if (b === 'b') {
    console.log(`b === 'b'`);
}

const testCondition = a === void 0 ? 'default' : a;
console.log(testCondition);
```
After the plugin
```

const result = {
  a: null
};
const result1 = {
  b: undefined
};
const result2 = {
  c: 1
};
const _result$a = result.a,
      a = _result$a == void 0 ? 'a' : _result$a;
const _result1$b = result1.b,
      b = _result1$b == void 0 ? 'b' : _result1$b;
const _result2$c = result2.c,
      c = _result2$c == void 0 ? 'c' : _result2$c;

if (a === 'a') {
  console.log(`a === 'a'`);
}

if (b === 'b') {
  console.log(`b === 'b'`);
}

const testCondition = a == void 0 ? 'default' : a;
console.log(testCondition);
```
Looking at it now, as I expected it.But I don't know if it will lead to bug.. 
I hope you can give me some suggestions. Thank you
