### ISSUE TITLE
How to transform output of presets?

### ISSUE THREAD

**Issue by mohsinulhaq** [babel/babel#10142]
I want to transform the `core-js` imports added by `@babel/preset-env`, but plugins always run before presets, as such I don't have access to those imports. Is there any other way to achieve this?

**Comment by nicolo-ribaudo** [comment]
This is a bug with the core-js 3 support.

This works:
```js
const input = `
new Map();
`;

const out = babel.transformSync(input, {
  configFile: false,
  presets: [
    [
      load("preset-env"),
      { corejs: 2, useBuiltIns: "usage", modules: false },
    ],
  ],
  plugins: [
    () => ({
      visitor: {
        ImportDeclaration(path) {
          path.node.source.value = "MODIFIED";
        },
      },
    }),
  ],
});

/* OUTPUT:
import "MODIFIED";
import "MODIFIED";
import "MODIFIED";
import "MODIFIED";
import "MODIFIED";
new Map();
*/
```

While this doesn't:
```js
This works:
```js
const input = `
new Map();
`;

const out = babel.transformSync(input, {
  configFile: false,
  presets: [
    [
      load("preset-env"),
      { corejs: 3, useBuiltIns: "usage", modules: false },
    ],
  ],
  plugins: [
    () => ({
      visitor: {
        ImportDeclaration(path) {
          path.node.source.value = "MODIFIED";
        },
      },
    }),
  ],
});

/* OUTPUT:
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.map";
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.string.iterator";
import "core-js/modules/web.dom-collections.iterator";
new Map();
*/
```

As a workaround, you can place your plugin inside a preset and visit `Program:exit`

**Comment by mohsinulhaq** [comment]
Alright, thanks a lot. Will try it out and update here.

**Comment by mohsinulhaq** [comment]
@nicolo-ribaudo I tried putting my plugin inside a preset and use `Program:exit`, but I still get the imports from `corejs:2` but not from `corejs:3`

**Comment by nicolo-ribaudo** [comment]
Did you also put your plugin inside a preset?
I know that this bug is unfortunate and hard to workaround, I will take a look at it.

**Comment by mohsinulhaq** [comment]
Let me know if I am doing this right, I am quite new to it:
```es6
// babel.config.js
module.exports = {
  presets: [
    '@babel/typescript',
    '@babel/react',
    ['@babel/env', {loose: true, useBuiltIns: 'usage', corejs: 3}],
    './config/custom-babel-preset'
  ],
  plugins: [
    'macros',
    'react-hot-loader/babel',
    '@babel/syntax-dynamic-import',
    '@babel/transform-runtime'
  ]
};
```

```es6
// custom-babel-preset.js
const plugin = require('./custom-babel-plugin');

module.exports = function() {
  return {plugins: [plugin]};
};
```

```es6
// custom-babel-plugin.js
module.exports = function() {
  return {
    visitor: {
      Program: {
        exit(path) {
          path.traverse({
            ImportDeclaration(path) {
              console.log(path.node.source.value);
            }
          });
        }
      }
    }
  };
};
```

**Comment by nicolo-ribaudo** [comment]
I have tested the workaround a bit, and the only working solution seems this:
```js
// custom-babel-plugin.js
module.exports = function() {
  return {
      post({ path }) {
        path.traverse({
          ImportDeclaration(path) {
            console.log(path.node.source.value);
          }
        });
      }
    }
  };
};
```
And the custom preset should come _before_ `preset-env`

**Comment by mohsinulhaq** [comment]
I tried the above snippet, keeping the file reference, before or after is not working for me. Earlier keeping my preset before `preset-env` was not console logging and keeping it after did, but now I am not getting console logs in either case.

**Comment by nicolo-ribaudo** [comment]
It will hopefully be fixed soon (https://github.com/babel/babel/pull/10146)

**Comment by mohsinulhaq** [comment]
alright, thanks a lot 🙂

**Comment by mohsinulhaq** [comment]
Hi @nicolo-ribaudo , I have one more query. Similar to having access to `core-js` imports, I want to have access to imports added by `@babel/runtime`. Here are two such exports:
```es6
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
var _inheritsLoose2 = _interopRequireDefault(require("@babel/runtime/helpers/inheritsLoose"));
```
When I use a babel plugin to access the `ImportDeclarations`, I get only the `inheritsLoose` and other imports but never the `_interopRequireDefault` import.
Am I doing this wrong or is this expected?

**Comment by nicolo-ribaudo** [comment]
Yes, because the transformation happens like this:
```js
class A {}
```
-> Class transform
```js
import inheritsLoose from "@babel/runtime/helpers/inheritsLoose";

function A() { ... }
```
-> Modules transform (part 1)
```js
var _inheritsLoose = _interopRequireDefault(require("@babel/runtime/helpers/inheritsLoose"));

function A() { ... }
```
-> Modules transform (part 2)
```js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
var _inheritsLoose = _interopRequireDefault(require("@babel/runtime/helpers/inheritsLoose"));

function A() { ... }
```

`_interopRequireDefault` is never an `ImportDeclaration`, it is directly injected as a requrie call.

**Comment by mohsinulhaq** [comment]
Ok understood. How do you suggest should I get hold of the `_interopRequireDefault` transform?

**Comment by nicolo-ribaudo** [comment]
You can try visiting `CallExpression` and checking if the callee is `require`

**Comment by mohsinulhaq** [comment]
Is there any issue in merging this? @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
The only blocker is that PRs need to have at least two :heavy_check_mark: reviews. If you could find some time and check if the code I wrote makes sense, a :white_check_mark: would help!
