### ISSUE TITLE
__defineGetter__ does not exist in IE9

### ISSUE THREAD

**Issue by hipertracker** [babel/babel#1014]
I cannot use Babel in IE9:

```
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; InfoPath.2)
Timestamp: Fri, 13 Mar 2015 16:01:39 UTC

Message: Object doesn't support property or method '__defineGetter__'
Line: 1
Char: 357
Code: 0
URI: http://localhost:3000/static_files/v2/vendor/requirejs_babel/babel-4.7.8.min.js
```

I added the latest es5-shim but it haven't helped. I added also es5-sham but I still get the same exception. Any hints?

**Comment by sebmck** [comment]
Are you talking about the actual compiler or the generated files?

**Comment by sebmck** [comment]
Looks like `__defineGetter__` is used by [convert-source-map](https://github.com/thlorenz/convert-source-map/search?utf8=%E2%9C%93&q=__defineGetter__). You can try suggesting they use [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty).

**Comment by hipertracker** [comment]
Where is that convert-soruce-map used? To whom should I talk exactly? My code sample https://github.com/hipertracker/react-iframe

**Comment by sebmck** [comment]
Babel uses the module `convert-source-map` which uses the `__defineGetter__` method (see the code search results that I linked in my previous comment).

**Comment by hipertracker** [comment]
OK. Done. https://github.com/thlorenz/convert-source-map/issues/23

**Comment by NervosaX** [comment]
If anyone else is dealing with this issue, I found a relevant polyfill here:

http://blogs.msdn.com/b/ie/archive/2010/09/07/transitioning-existing-code-to-the-es5-getter-setter-apis.aspx

Specifically

```javascript
if (!Object.prototype.__defineGetter__ &&
      Object.defineProperty({},"x",{get: function(){return true}}).x) {
    Object.defineProperty(Object.prototype, "__defineGetter__",
       {enumerable: false, configurable: true,
        value: function(name,func)
           {Object.defineProperty(this,name,
               {get:func,enumerable: true,configurable: true});
    }});
    Object.defineProperty(Object.prototype, "__defineSetter__",
       {enumerable: false, configurable: true,
        value: function(name,func)
           {Object.defineProperty(this,name,
               {set:func,enumerable: true,configurable: true});
    }});
 }
```

**Comment by bbnnt** [comment]
@NervosaX I'm not that experienced, understanding it has to be put somewhere to override the babel function
how would you use it within a project ? Should the part of code has to be rewrittten from within the package ?

**Comment by NervosaX** [comment]
@bbnnt: It polyfills the browsers native code, not babel. It should just be added right at the start of your application. In this instance, it adds __defineGetter__ and setter to the Object prototype. 

It is, however, non standard - so the above is really just a hack rather than a polyfill. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__ for deprecation notice
