### ISSUE TITLE
class properties is undefined through prototype

### ISSUE THREAD

**Issue by cybermerlin** [babel/babel#10150]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- REPL or Repo link if applicable:

```js
class Some {
  pp = 99;
}
console.log(Some.prototype.pp) // > undefined;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{}
```

**Environment**
- Babel version(s): [e.g. v7.4.4]
- Node/npm version: [e.g. Node 10/npm 5]
- OS: [e.g. Windows 10]
- Monorepo: [e.g. yes]
- How you are using Babel: [e.g. `cli`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
This is the expected behavior, per the spec.
Class fields are initialized on the `this` object, using `Object.defineProperty`.

It is needed to prevent possible problems like this:

```js
class OrderedArray {
  items = [];
  
  push(v) {
    this.items.push(v);
    this.items.sort();
  }

  get(index) {
    return this.items[index];
  }
}

var arr1 = new OrderedArray;
arr1.push(1);

var arr2 = new OrderedArray;
arr2.push(2);
console.log(arr2.get(0));
```

If the property was on the prototype (and thus shared), it would log `1` instead of `2`, and the array would contain both the numbers.

**Comment by cybermerlin** [comment]
@nicolo-ribaudo mmm, nop, I said not about an object, I said about class definitions. As I see it after casting in to a lower version javascript: 
```js
var Some = function(cfg){...}; Some.prototype.pp = 99; 
```
but now it's wrong

**Comment by mAAdhaTTah** [comment]
@cybermerlin It doesn't matter, that's not how class properties work according to the spec. They're assigned to the instance when the object is constructed. That's true of all properties, not just object properties. Nicolo shared the reasoning for it, but it applies to all properties.

**Comment by cybermerlin** [comment]
@mAAdhaTTah James, Guys, I want to say, what if I declare properties in a class and because in javascript all works through Prototype, then all declared properties should looked like `ClassName.prototype.fieldName` n I want to access to that properties exactly through  the prototype. I understand you both, but now I'm talking about defining properties, not about applying (assigning the value in\after constructor) to the resulting object.

I'm hope u understand differences between result and definition from my bony description.

Look this example (both works, but in 2nd in prototype has bug):
```
function Some (){}
Some.prototype.pp = 99;
console.log((new Some).pp); // > 99
console.log(Some.prototype.pp); // > 99
```

```
class Some {
  pp = 99;
}
console.log((new Some).pp); // > 99
console.log(Some.prototype.pp); // > undefined
```

**Comment by cybermerlin** [comment]
And of course example with Array|Object we need define through Object.defineProperty, which should define that property in prototype like function-initializer, but we have not now this pended result.

**Comment by mAAdhaTTah** [comment]
I understand what you're trying to say, and the differences between those two. I'm saying, if you want to do that, the class properties syntax does not do that. The second example is not a bug; it's how the language is specified to work.

If you want to transpile it such that it attaches properties to the prototype, you'll need to write your own Babel plugin to do that.

**Comment by cybermerlin** [comment]
@mAAdhaTTah , ok, thx, it seemed to me that the specification did not state that the properties should not be accessible through the prototype... ok-ok, I'll just do it now
