### ISSUE TITLE
Optional runtime cannot be used in a web worker on Safari

### ISSUE THREAD

**Issue by bcamper** [babel/babel#1015]
(This is a regenerator-related issue, but submitting it here since it looked like the babel-regenerator fork doesn't have issues enabled.)

The optional runtime throws an error when loaded in a web worker in some versions of Safari (I initially encountered this in Safari 8 on Yosemite & iOS8, but have since noticed the error in Safari 7 too).

The error relates to `hasOwnProperty` failing when called on the worker `self` object, and is described here:
https://github.com/facebook/regenerator/pull/183

And fixed in regenerator master here:
https://github.com/facebook/regenerator/pull/184

Not sure of the current process for merging upstream changes here, but it would be great to get these fixes into Babel's regenerator so that it can used in worker's on Safari.

**Comment by sebmck** [comment]
Extremely sorry for the delay. I've updated to the latest version of `regenerator` with the goal of eventually using vanilla regenerator (see #1123). Released as of 5.1.0, thanks!

**Comment by bcamper** [comment]
Thanks! Will check it out.
