### ISSUE TITLE
code frame formatting messed up when using colors

### ISSUE THREAD

**Issue by devsnek** [babel/babel#10159]
## Bug Report

**Current Behavior**
Using color in code frames causes odd formatting

**Input Code**
```js
console.log(codeFrameColumns(`
function a(b, c) {
  return b + c;
}
`, {
  start: {
    line: 2,
    column: 1,
  },
  end: {
    line: 4,
    column: 1,
  },
}, {
  highlightCode: true,
  message: 'Message about things',
}));

```

**Expected behavior/code**
Arrow formatting remains consistent

**Environment**
- `@babel/code-frame`: `7.0.0`

**Possible Solution**

**Additional context/Screenshots**

Input code from above with and without `highlightCode`:

![](https://gc.gy/29908279.png)

--

P.S. it also seems that with the non-color output, the first line is 1 character short.

**Comment by devsnek** [comment]
Quickly reading through the code-frame source, it appears that the issue is that highlighting is immediately applied to the source before arrow length calculation is done, resulting in the arrow length including ANSI escape sequences.

**Comment by nicolo-ribaudo** [comment]
We peobably are counting "hidden" ANSI codes, while we shouldn't.
