### ISSUE TITLE
@babel/plugin-transform-modules-amd version 7.5.0 isn't published

### ISSUE THREAD

**Issue by Jrfidellis** [babel/babel#10164]
I don't know if it's a error with `@babel/plugin-transform-modules-amd` itself or with `babel-plugin-dynamic-import-node`, i hope you guys could help me.

But evidence i took from npm suggests it's related with `@babel/plugin-transform-modules-amd`.

The error shown in our GitLab CI job:
```
npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-plugin-dynamic-import-node@^2.3.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.2.0, 2.1.0, 2.0.0, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 1.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/plugin-transform-modules-amd'
npm ERR! notarget 
```

Evidence: 

Time of your latest release:
![image](https://user-images.githubusercontent.com/26925730/60686975-1cf0f000-9e82-11e9-88d5-6df425b55a72.png)

Time our erros begun:

![Screenshot_1](https://user-images.githubusercontent.com/26925730/60687081-b3bdac80-9e82-11e9-8c79-ad14e91a9f84.jpg)

**Comment by nicolo-ribaudo** [comment]
`@babel/plugin-transform-modules-amd` has been published: https://www.npmjs.com/package/@babel/plugin-transform-modules-amd
Also `babel-plugin-dynamic-import-node@^2.3.0`: https://www.npmjs.com/package/babel-plugin-dynamic-import-node

Plase try to run the workarounds described at https://github.com/babel/babel/issues/10165
