### ISSUE TITLE
TypeError: class constructors must be invoked with |new|

### ISSUE THREAD

**Issue by kottackalsulvin** [babel/babel#10168]
Hi,
I have the below shown error while integrating a libp2p application in Ethereum Blockchain application. The error message is:

> TypeError: class constructors must be invoked with |new|

My code is like below:

```
const node = new Node({peerInfo})

node.start((err) => {
console.log("node start");
if (err) callback(err)
callback(null, node)
})
.....
class Node extends libp2p {
constructor (peerInfo,opts) {
const wstar = new WebRTCStar()
const DEFAULT_OPTS = {
modules:{
transport: [new WS(), wstar], 
connEncryption: [secio],
streamMuxer: [mplex],
peerDiscovery: [ wstar.discovery ]
}
}
super(defaultsDeep(opts,peerInfo, DEFAULT_OPTS))
}
}
...
```
My webpack.config.js code is as below:

```
module: {
rules: [
{ test: /\.json$/, use: 'json-loader' },
{ test: /\.css$/, use: [ 'style-loader', 'css-loader' ]},
{
test: /\.jsx?$/,
loader: 'babel-loader',
exclude: {
test: /(node_modules|bower_components)/,
not: [
/libp2p/
]
},
query: {
presets:['es2015'],
plugins:['transform-object-rest-spread']
}
}
]
},
```

**Environment** 
Npm / Node version: 6.9.0 / 10.16.0
webpack: 3.11.0
babel-loader:7.1.0
Os:Ubuntu 18.04

I don’t understand why showing the error messages. I tested the same libp2p application in meanstack and it works fine. Any ideas?

**Comment by nicolo-ribaudo** [comment]
The problem is that native classes (i.e. `libp2p`) can't be extended by transpiled classes (`Node`).
You have two options:

Does your environment support classes?
yes -> don't transpile them in your code
no -> you also have to transpile them inside the `libp2p` library, otherwise it won't work.

**Comment by kottackalsulvin** [comment]
Thank you for your reply. The environment don't support classes. Can you
explain how should I transpile the class inside the libp2p library. I am
confusing.

**Comment by nicolo-ribaudo** [comment]
Linking at your config they should already be transpiles, but there must be a problem somewhere.
Can you check in your webpack output if there really are untranspiled classes?
