### ISSUE TITLE
ReferenceError: _objectSpread is not defined after update

### ISSUE THREAD

**Issue by jenniferlynparsons** [babel/babel#10179]
## Bug Report

**Current Behavior**
I've updated to 7.5 and have been following the developments with issues that should have been resolved with https://github.com/babel/babel/releases/tag/v7.5.1 however after stripping and reinstalling everything babel-related, I'm still getting this error. 

**Babel packages**
@babel/cli: "^7.5.0"
@babel/core: "^7.5.0"
@babel/helpers: "^7.5.1"
@babel/plugin-proposal-object-rest-spread: "^7.5.1"
@babel/plugin-transform-runtime: "^7.5.0"
@babel/polyfill: "^7.4.4"
@babel/preset-env: "^7.5.0"
@babel/preset-react: "^7.0.0"
babel-eslint: "^10.0.2"
babel-jest: "^24.8.0"
babel-loader: "^8.0.6"
babel-plugin-dynamic-import-node: "^2.3.0"
babel-plugin-jsx-remove-data-test-id: "^2.0.0"
babel-plugin-transform-class-properties: "^6.24.1"
babel-plugin-transform-decorators-legacy: "^1.3.5"
babel-plugin-transform-export-extensions: "^6.22.0"
babel-plugin-transform-object-rest-spread: "^6.26.0"

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "env": {
    "test": {
      "plugins": [
        "transform-class-properties",
        "dynamic-import-node",
        "@babel/plugin-transform-runtime"
      ]
    },
    "production": {
      "plugins": ["babel-plugin-jsx-remove-data-test-id"]
    }
  },
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": ["transform-class-properties"]
}

```

**Environment**
- Babel version(s): 7.5.0
- Node/npm version: 6.5.0
- OS: Linux Mint Cinnamon
- Monorepo: yes

**Comment by nicolo-ribaudo** [comment]
Can you post your webpack config?

**Comment by jenniferlynparsons** [comment]
I installed the plugins from scratch without indicating version number, so I'll have to see if there are updated versions available somewhere. Here's my webpack config:
```
/*
    ./webpack.config.js
*/
const path = require("path");

const HtmlWebpackPlugin = require("html-webpack-plugin");
const HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: "./client/src/index.html",
  filename: "index.html",
  inject: "body"
});

module.exports = {
  entry: "./client/src/index.js",
  output: {
    path: path.resolve("dist"),
    filename: "index_bundle.js",
    publicPath: "/"
  },
  module: {
    rules: [
      {
        test: /\.(sass|scss)$/,
        use: ["style-loader", "css-loader", "sass-loader"]
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: "babel-loader"
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: "babel-loader"
      },
      {
        test: /\.svg$/,
        use: [
          {
            loader: "babel-loader"
          },
          {
            loader: "react-svg-loader",
            options: {
              jsx: true // true outputs JSX tags
            }
          }
        ]
      }
    ]
  },
  resolve: {
    extensions: [".js", ".jsx"]
  },
  devServer: {
    historyApiFallback: true
  },
  plugins: [HtmlWebpackPluginConfig]
};
```

**Comment by jenniferlynparsons** [comment]
A bit more investigation leads to Jest being part of the problem. That's where I'm getting that error, specifically. It requires things like `babel-plugin-transform-class-properties: "^6.24.1"`. I'm going to see if there's any way to update that.

**Comment by jenniferlynparsons** [comment]
Further update: Earlier today I had rolled back to my previous branch and everything worked correctly. The only difference between the two branches is that I installed Yup (https://github.com/jquense/yup) for some error validation.

**Comment by nicolo-ribaudo** [comment]
Installing a new package might have changed other things in your lockfile.

Recent versions of Jest use Babel 7, which version are you using?

**Comment by jenniferlynparsons** [comment]
I'm on the most current version of Jest. The project I'm working on is fairly new (started in October/November) and I had just updated everything last week, so it's all current versions, or as close as possible.

**Comment by mstruensee** [comment]
I am getting this same issue ... downgrading fixed the issue.

**Comment by nicolo-ribaudo** [comment]
Can someone of you share a small repository which reproduces the issue?

**Comment by mstruensee** [comment]
I would have to make one, currently it is happening on internal private repositories.

**Comment by nicolo-ribaudo** [comment]
Hopefully you would only need the same config and a one-line sample file to transpile.

**Comment by jenniferlynparsons** [comment]
@nicolo-ribaudo here's my current branch where it's failing https://github.com/jenniferlynparsons/cuppa-webpack/tree/feature/login-form-validation

I've got it narrowed down at the moment to the AuthReducer.js file where I've added the "LOGIN_ERRORS" case. The case before that is the one that's failing in the AuthReducers.test.js file.

**Comment by nicolo-ribaudo** [comment]
I tried downloading that branch, updating Babel plugins to v7 and `npm test` worked.

**Comment by jenniferlynparsons** [comment]
Well, that's encouraging! @nicolo-ribaudo can you clarify which plugins should be updated? And is it enough to run `npm update pluginX` for each of them?

**Comment by nicolo-ribaudo** [comment]
Oh yeah, sorry for not being clear. We renamed the packages in Babel 7:

package.json
```json
  "devDependencies": {
    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.3",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-proposal-dynamic-import": "^7.5.0",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-react": "^7.0.0",
    "@testing-library/react": "^8.0.1",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.7.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-jsx-remove-data-test-id": "^2.0.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.4",
    "html-webpack-plugin": "^3.2.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.8.0",
    "jest-dom": "^3.5.0",
    "jsdoc": "^3.6.2",
    "lodash": "^4.17.11",
    "moxios": "^0.4.0",
    "nodemon": "^1.18.11",
    "prettier": "^1.16.4",
    "react-svg-loader": "^2.1.0",
    "react-test-renderer": "^16.8.6",
    "redux-devtools-extension": "^2.13.8",
    "redux-mock-store": "^1.5.3",
    "sass": "^1.18.0",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.3.1"
  },
```

.babelrc
```json
{
  "env": {
    "test": {
      "plugins": [
        "@babel/proposal-dynamic-import",
        "@babel/transform-runtime"
      ]
    },
    "production": {
      "plugins": ["babel-plugin-jsx-remove-data-test-id"]
    }
  },
  "presets": ["@babel/env", "@babel/react"],
  "plugins": ["@babel/proposal-class-properties"]
}
```

**Comment by mstruensee** [comment]
@jenniferlynparsons where is @babel/plugin-proposal-object-rest-spread in your .babelrc?

**Comment by mstruensee** [comment]
@jenniferlynparsons where is @babel/plugin-proposal-object-rest-spread in your .babelrc?

**Comment by jenniferlynparsons** [comment]
Thanks for the clarification @nicolo-ribaudo ! Looks like I'm still having issues, but I can move forward with more confidence that it's not a babel issue. Time to try restarting the machine. :D

**Comment by jenniferlynparsons** [comment]
@mstruensee I didn't have it in mine. Just tried adding it and wow that made everything so much worse. lol. 

Now I'm not just getting the error on the one test, but on most of them.

**Comment by jenniferlynparsons** [comment]
Okay, I think (fingers crossed) I have it fixed. For me, it took uninstalling `jest` and `jest-cli` globally and reinstalling them. That seems to have finally resolved the issue.

**Comment by nicolo-ribaudo** [comment]
I suggest never I stalling packages globally, always use the local copy.

**Comment by HsuTing** [comment]
I had the same problem. I use this with `next.js`.
The source code like this:

In:
```js
export const handlePages = (pages, removeIcon = false) =>
  (pages || []).map(
    ({ pages: subPages, newWindow, params, icon, ...page }) => ({
      ...page,
      newWindow: !!newWindow,
      params: params || {},
      pages: handlePages(subPages),
      icon:
        removeIcon && !icon?.use
          ? null
          : {
              direction: icon?.direction || 'right',
              font: icon?.font || null,
              image: icon?.image || null,
            },
    }),
  );

export default ({ design, pages, ...menu }) => ({
  ...menu,
  pages: handlePages(pages),
  design: {
    ...design,
    showLogo: design?.showLogo || false,
    ...
});
```

Out:
```js
var handlePages = function handlePages(pages) {
  var removeIcon = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;
  return (pages || []).map(function (_ref) {
    var subPages = _ref.pages,
        newWindow = _ref.newWindow,
        params = _ref.params,
        icon = _ref.icon,
        page = _babel_runtime_helpers_objectWithoutProperties__WEBPACK_IMPORTED_MODULE_1___default()(_ref, ["pages", "newWindow", "params", "icon"]);

    return _babel_runtime_helpers_objectSpread__WEBPACK_IMPORTED_MODULE_0___default()({}, page, {
      newWindow: !!newWindow,
      params: params || {},
      pages: handlePages(subPages),
      icon: removeIcon && !(icon === null || icon === void 0 ? void 0 : icon.use) ? null : {
        direction: (icon === null || icon === void 0 ? void 0 : icon.direction) || 'right',
        font: (icon === null || icon === void 0 ? void 0 : icon.font) || null,
        image: (icon === null || icon === void 0 ? void 0 : icon.image) || null
      }
    });
  });
};
/* harmony default export */ __webpack_exports__["a"] = (function (_ref2) {
  var design = _ref2.design,
      pages = _ref2.pages,
      menu = _babel_runtime_helpers_objectWithoutProperties__WEBPACK_IMPORTED_MODULE_1___default()(_ref2, ["design", "pages"]);

  return _objectSpread({}, menu, {
    pages: handlePages(pages),
    design: _objectSpread({}, design, {
     ...
```

Some `_objectSpread` had changed to `_babel_runtime_helpers_objectSpread__WEBPACK_IMPORTED_MODULE_0___default`, but others did not change.

`babel.config.js`
```js
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        useBuiltIns: 'usage',
        corejs: '2.6.9',
      },
    ],
    '@babel/react',
    '@babel/preset-typescript',
  ],
  plugins: [
    '@babel/transform-runtime',
    '@babel/proposal-optional-chaining',
    '@babel/proposal-export-default-from',
    [
      '@babel/proposal-decorators',
      {
        legacy: true, // TODO: remove, typescript not support
      },
    ],
    '@babel/proposal-class-properties',
    [
      'transform-imports',
      {
        /* eslint-disable no-template-curly-in-string */
        antd: {
          transform: 'antd/lib/${member}',
          kebabCase: true,
        },
        lodash: {
          transform: 'lodash/${member}',
        },
        fbjs: {
          transform: 'fbjs/lib/${member}',
        },
        validator: {
          transform: 'validator/lib/${member}',
        },
        'react-icons/fa': {
          transform: 'react-icons/lib/fa/${member}',
          kebabCase: true,
        },
        'react-icons/md': {
          transform: 'react-icons/lib/md/${member}',
          kebabCase: true,
        },
        /* eslint-enable no-template-curly-in-string */
      },
    ],
    'idx',
    [
      'module-resolver',
      {
        root: ['./src'],
        cwd: 'packagejson',
      },
    ],
    'css-modules-transform',
  ],
};
```

@nicolo-ribaudo do you have any idea?

**Comment by nicolo-ribaudo** [comment]
This seems like a problem with webpack, which only transpiles _some_ usages of the imported helper and not all of them.

**Comment by HsuTing** [comment]
After I tested, this work correctly when I downgrade to `@babel/plugin-proposal-object-rest-spread@7.4.4` and `@babel/helpers@7.5.1`.

**Comment by v-angolenko** [comment]
i have similar problem, but my config has only 2 plugins
```
['@babel/plugin-transform-modules-commonjs'],
['@babel/plugin-proposal-object-rest-spread'],
```

babel generate function _objectSpread2 but tries to use _objectSpread2 and _objectSpread, and it causes error "_objectSpread is not defined"

**Comment by nicolo-ribaudo** [comment]
@v-angolenko @HsuTing Can you provide a repository which shows the issue?

**Comment by v-angolenko** [comment]
> @v-angolenko @HsuTing Can you provide a repository which shows the issue?

I added minimal part of the project to simplify search the issue  
src/index.js -> lib/index.js

[spread-issue-repo.zip](https://github.com/babel/babel/files/3373576/spread-issue-repo.zip)

**Comment by kddeisz** [comment]
Hi friends - here's a repo with the issue: https://github.com/CultureHQ/react-state-mutations/pull/123. It's a pretty minimal repo so hopefully should get you going. The `.babelrc` contains:

```
{
  "presets": ["@babel/preset-env"]
}
```

Here are the dependencies in `package.json`:

```
  "devDependencies": {
    "@babel/cli": "^7.5.0",
    "@babel/core": "^7.5.0",
    "@babel/preset-env": "^7.5.3",
    "@culturehq/scripts": "^2.1.0",
    "@testing-library/react-hooks": "^1.0.4",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-test-renderer": "^16.8.6"
  }
```

**Comment by kddeisz** [comment]
Some further investigation: this PR https://github.com/babel/babel/pull/10170 is the last one to touch the spread plugin, and there is a mention in the discussion of various babel/core versions causing a problem. Looks like I have `jest-config` and `@jest/transform` in my yarn.lock file both requesting `"@babel/core" "^7.1.0"`. Would that cause a problem? I'm on the latest for everything so likely something needs to change here but not sure what.

**Comment by nicolo-ribaudo** [comment]
@kddeisz In your repository, it is enough to delete `@babel/core` 7.4.5 and `@babel/helpers` 7.4.4 from the lockfile. I'm trying to understand why it is broken, but I can't reproduce it only with `yarn prepublishOnly` (I belive this is somehow caused by the Jest integration)

**Comment by kddeisz** [comment]
Yeah I just got there as well. It looks like if you use the built distribution it will work. It's got to be something with `@jest/transform`

**Comment by nicolo-ribaudo** [comment]
If you delete those entries from yarn.lock and re-run `yarn --frozen-lockfile`, tests pass :thinking: 	

@v-angolenko I get this error:
```
➜ npm test

> @deepvision/svg-sprite-generator@0.1.3 test /home/nicolo/Documenti/dev/babel-bugs/spread-issue
> jest

sh: 1: jest: not found
npm ERR! Test failed.  See above for more details.
```

**Comment by kddeisz** [comment]
So this gist: https://gist.github.com/kddeisz/c37c9a32f1694aeaa7b7c1e00a234de3 is what the jest transform compiles out to. So it looks like it injects a `_objectSpread2` helper, and calls it in a couple places, but then calls `_objectSpread` in others.

**Comment by nicolo-ribaudo** [comment]
Thanks, it appears to be the same problem as in @v-angolenko's package. I'm trying to understand what it is caused by.

**Comment by nicolo-ribaudo** [comment]
Repl demo: https://babeljs.io/repl/version/7.2.0#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBCCuUAOiDC4BmBLA5jAvDAN4wB05CyiMAvgNwBQoksz2ehJ5pOApmLwBOAQwA26MO1p0gA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.1.6&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.5.3

It appears to be a problem when using an old version of `@babel/core` with a new version of `@babel/plugin-proposal-object-rest-spread`. As a workaround, you can update `@babel/core` to `^7.5.0`.

**Comment by nicolo-ribaudo** [comment]
I have created https://github.com/babel/babel/issues/10187 which shows the root cause of this issue.

**Comment by kddeisz** [comment]
Nice work @nicolo-ribaudo! Thanks for the quick research!

**Comment by nicolo-ribaudo** [comment]
Btw, the fix for that bug will go in the next `@babel/core` version, so you'll have to update it anyway.

**Comment by mstruensee** [comment]
@nicolo-ribaudo @babel/core was mentioned in this thread, so I happened to look at my package.json and I am shocked to see that it was not in there ... I added the latest and then upgraded 		"@babel/plugin-proposal-object-rest-spread": "7.5.4" and my error is gone. 👍

**Comment by kddeisz** [comment]
When using `jest`, it's going to request babel `7.1.0`, which still causes problems with the spread operator because of #10187. But you can get around it by adding a resolution to your package.json, as in:

```
"resolutions": {
    "@babel/core": "^7.5.4"
  }
```

which will force jest into using the newer babel. This seems to fix the problem with jest at least.

**Comment by MizuBishi** [comment]
I have the same error and I am using it with gatsby.

**Comment by nicolo-ribaudo** [comment]
Yeah, please update `@babel/core` until this is fixed.

**Comment by MizuBishi** [comment]
Yes I updated `"@babel/core": "^7.5.4"` but I still get `ReferenceError: _objectSpread is not defined`.

**Comment by pleunv** [comment]
@MizuBishi You might want to remove your `node_modules` and reinstall, I had a similar issue.

**Comment by bscs-dev-team** [comment]
> I have the same error and I am using it with gatsby.

We are also having this issue in Gatsby. Our site suddenly won't build on Netlify.

**Comment by edahlseng** [comment]
I'm also encountering the same issue. `npm ls @babel/core` confirms that I'm using version 7.5.4, and I can similarly confirm that I'm using version 7.5.0 of @babel/node and version 7.5.4 of @babel/plugin-proposal-object-rest-spread.

**Comment by bscs-dev-team** [comment]
We have this resolved for Gatsby on Netlify by adding `plugin-proposal-object-rest-spread` to Gatsby.

package.json:
`
"devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.4",
    "babel-preset-gatsby": "^0.2.1"
},
"resolutions": {
    "@babel/core": "^7.5.4"
}
`

.babelrc in root:

`
{
  "presets": ["babel-preset-gatsby"],
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}
`

**Comment by hubgit** [comment]
I was having this issue when running tests in Jest, after upgrading to `@babel/core@7.5.4`.

I found that running `yarn-deduplicate && yarn` was enough to fix it.

* yarn-deduplicate: https://www.npmjs.com/package/yarn-deduplicate
* Relevant yarn issue https://github.com/yarnpkg/yarn/issues/3967

**Comment by joefiorini** [comment]
I've tried everything in this list in our yarn workspaces monorepo. I've added the `resolutions` field for `@babel/core` and am now on `7.5.4` for both:

```
web-infrastructure on  gatsby-update [⇡$!] 
➜ yarn list --pattern @babel/core
yarn list v1.15.2
└─ @babel/core@7.5.4
✨  Done in 1.49s.

web-infrastructure on  gatsby-update [⇡$!] 
➜ yarn list --pattern @babel/plugin-proposal-object-rest-spread
yarn list v1.15.2
└─ @babel/plugin-proposal-object-rest-spread@7.5.4
✨  Done in 1.69s.
```

I've run `yarn-deduplicate` (at least on `@babel/runtime` and `@babel/preset-env`. I still have [a few other `@babel` dependencies that are considered duplicates](https://gist.github.com/joefiorini/40acab5fe3abdb89b0d170b334b4f302), could any of those be related to this issue?

With every attempt to fix this issue I've run `rm -rf node_modules **/node_modules` to remove from all folders in my workspace. Every time running `yarn test` still results in the same error:

> ReferenceError: _objectSpread is not defined

Anyone manage to work around this without one of the already-mentioned solutions?

**Comment by FeXd** [comment]
Just wanted to confirm for others struggling with this issue that @jenniferlynparsons recommendation fixed my issue.
> Time to try restarting the machine.

Was fighting with our CI machine and followed many of the above suggestions, but a reboot finally fixed the issue.

**Comment by thinkkevin** [comment]
I had similar issue when I tried to upgrade babel to v7 and my unit test with jest failed with such error.

Eventually, I found I need to have to set `BABEL_ENV=test` in env vars.

And I don't have to add `@babel/plugin-transform-runtime` plugin.
