### ISSUE TITLE
flow annotation didn't stripped correctly

### ISSUE THREAD

**Issue by chunghe** [babel/babel#10177]
## Bug Report

**Current Behavior**
Flow type annotation didn't strip correctly

**Input Code**
- REPL or Repo link if applicable: [demo](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FASwtgDg9gTgLgAgEoFMCGBjRAzGUwIBEM6WhA3MMBlAHYDOiaAynDCLQOYBcCj7XBAF4EAcgAWKADZSoCAO6wpAE1HA4ATwgoEAFUlgUurTpGEpITuLiEEAHyLK0MANaFgKAB7R4CGg0R9FENhZFI4ADoMEjQ4FABhOjjPOAAeIMNjbQA-AApzS2tCAEpyIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3%2Cflow&prettier=false&targets=&version=7.5.0&externalPlugins=)

```js

import React from "react";

const aString: string = 'hello world'
type ThemeType = "light" | "dark"
export const Theme = React.createContext<ThemeType>("light");
```

**Expected behavior/code**
`string`/`ThemeType` flow annotation should be stripped correctly. But only `string` is stripped

If add `// @flow` then it works properly, [demo](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgBEWJ5tA3IoqbAHYDOexAyjizJOAcwBcoXsLGgAvKADkAC0LQ4oeNmgATRYhwBPdIVAAVVakJnjphbWjJRynLVAAfOjuJYA1rURCAA9MXFAOHjwLQit5AkYcADpSBmIcQgBhLnSgnAAeaKsbEwA-AAoHJxdaAEpmIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3%2Cflow&prettier=false&targets=&version=7.5.0&externalPlugins=)

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      '@babel/plugin-proposal-export-namespace-from',
      '@babel/plugin-syntax-dynamic-import',
      '@babel/plugin-transform-runtime',
    ],
    env: {
      test: {
        plugins: ['dynamic-import-node'],
      },
    },
  };
};
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Comment by nicolo-ribaudo** [comment]
You need `@babel/preset-flow`.

**Comment by chunghe** [comment]
could you please take a look at these two demos:
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FASwtgDg9gTgLgAgEoFMCGBjRAzGUwIBEM6WhA3MMBlAHYDOiaAynDCLQOYBcCj7XBAF4EAcgAWKADZSoCAO6wpAE1HA4ATwgoEAFUlgUurTpGEpITuLiEEAHyLK0MANaFgKAB7R4CGg0R9FENhZFI4ADoMEjQ4FABhOjjPOAAeIMNjbQA-AApzS2tCAEpyIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3%2Cflow&prettier=false&targets=&version=7.5.0&externalPlugins=

https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgBEWJ5tA3IoqbAHYDOexAyjizJOAcwBcoXsLGgAvKADkAC0LQ4oeNmgATRYhwBPdIVAAVVakJnjphbWjJRynLVAAfOjuJYA1rURCAA9MXFAOHjwLQit5AkYcADpSBmIcQgBhLnSgnAAeaKsbEwA-AAoHJxdaAEpmIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3%2Cflow&prettier=false&targets=&version=7.5.0&externalPlugins=

both with flow preset checked, why first demo only strip part of the flow annotation(stripped `string` but not `ThemeType`). Appreciate  your feedback!

**Comment by existentialism** [comment]
@chunghe the flow pragma comment (// @flow) is required because `f<T>(e)` is valid JavaScript (a nested BinaryExpression) `((f < T) > e)`.

Ref: https://github.com/babel/babel/pull/7934
