### ISSUE TITLE
The runtime transformer without core-js

### ISSUE THREAD

**Issue by monolithed** [babel/babel#1017]
The babelify transform section:
```
transform: [
	[
		'babelify', {
			optional: [
				'runtime',
			],

			loose: [
				'es6.forOf',
			]
		}
	]
]
```

```
➜ grunt browserify

Running "browserify:owa" (browserify) task
>> Error: Cannot find module 'babel-runtime/core-js' from 'utils'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

##### 1st
There's no `babel-runtime` module, however:

```
➜ ls -1 node_modules/babelify/node_modules/babel-core/node_modules/{regenerator-babel,core-js}
node_modules/babelify/node_modules/babel-core/node_modules/core-js:
Gruntfile.js
README.md
bower.json
build
client
index.js
library.js
package.json
shim.js
src

node_modules/babelify/node_modules/babel-core/node_modules/regenerator-babel:
CONTRIBUTING.md
LICENSE
PATENTS
README.md
bin
lib
main.js
node_modules
package.json
runtime-module.js
runtime.js
```

I don't understand why this package must be installed separately?
And there are no words in the documentation!

```
➜ npm install babel-runtime
babel-runtime@4.7.12 node_modules/babel-runtime
└── core-js@0.6.1
```

```
➜ grunt browserify
Ok....
```

##### 2nd

I've a very simple code without any additional objects like`Map`, `Set`, `Promise`, `Symbol` etc.

For example:

```js
export default function *(object, callback, context) {
	for (let key of Object.keys(object)) {
		yield [key, object[key]];
	}
}
```

As you see I don't need the `core-js` as well! 
How to exclude the one?

**Comment by AluisioASG** [comment]
> And there are no words in the documentation!

There's [a whole box](https://babeljs.io/docs/usage/runtime/) about it, actually.

> I've a very simple code without any additional objects like `Map`, `Set`, `Promise`, `Symbol` etc.

Except that [`for-of` does use `Symbol`](https://babeljs.io/docs/usage/caveats/#polyfills) under the hood.

If you're concerned about pulling in all of `core-js` in your code, you could install a [custom build](https://github.com/zloirock/core-js#custom-build) at your top-level `node_modules` and remove the one from under `babel-runtime`'s.

**Comment by monolithed** [comment]
> There's a whole box about it, actually.
Hm, It's true

> Except that for-of does use Symbol under the hood.
Also drew attention to the [source code](https://github.com/facebook/regenerator/blob/master/runtime.js#L17) (

> If you're concerned about pulling in all of core-js in your code, you could install a custom build at your top-level node_modules and remove the one from under babel-runtime's.

> If you're concerned about pulling in all of core-js in your code, you could install a custom build at your top-level node_modules and remove the one from under babel-runtime's.
Good advice, thanks!
