### ISSUE TITLE
babel/packages/babel-parser/typings/babel-parser.d.ts lacks some plugins

### ISSUE THREAD

**Issue by hybloid** [babel/babel#10186]
## Bug Report

**Current Behavior**
Currently, TS definition for ParserPlugin type (definded inbabel/packages/babel-parser/typings/babel-parser.d.ts) misses the plugins _placeholders, partialApplication, logicalAssignment_ which could be enabled and used with the parser.

Current workaround is to specify <any> alongside with the first plugin name to make tsc compiler work;

**Input Code**

```js
const options: ParserOptions = {
    sourceType: 'unambiguous',
    strictMode: false,
    plugins: [
        <any>'placeholders',
        'logicalAssignment',
        'partialApplication',
   ],
};
```

**Expected behavior/code**
I expect definition to be modified allowing specify ParserOptions without <any>

```js
const options: ParserOptions = {
    sourceType: 'unambiguous',
    strictMode: false,
    plugins: [
        'placeholders',
        'logicalAssignment',
        'partialApplication',
   ],
};
```

**Environment**
- Babel version(s): 7.5.0
- Node/npm version: 10.16.0
- OS: Ubuntu
- How you are using Babel: npm package

**Comment by JLHwung** [comment]
`babel-parser.d.ts` has not been updated since Feb. So PR's welcome.

It should be a `good first issue`.

**Comment by Letladi** [comment]
I am willing to attempt this
