### ISSUE TITLE
Invalid Option: '>=10' is not a valid value for 'targets.node'

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel#10182]
## Bug Report

**Current Behavior**
I'm getting the error above.

**Expected behavior/code**
`>=10` appears to be [supported by browserlist](https://github.com/browserslist/browserslist#full-list), so it should just simply work.

**Babel Configuration (.babelrc, package.json, cli command)**

```shell
babel lib-esm/ --out-dir=lib/ --source-maps
```
```js
"use strict";
const {engines: {node}} = require('./package.json');

module.exports = {
  presets: [
    ['@babel/preset-env', {
      targets: {node}
    }]
  ]
};
```

**Environment**
- Babel version(s): v7.5.0
- Node/npm version: Node 12.6.0/npm 6.9.0
- OS: macOS 10.14.5
- Monorepo: no
- How you are using Babel: `cli`

**Comment by nicolo-ribaudo** [comment]
Only the `browsers` target option is passed to browserlist. If you directly specify an engine, you must use an exact version (which is the minimum supported).

**Comment by stevenvachon** [comment]
I guess I'll need to hack it with `parseFloat()`, then.

**Comment by nicolo-ribaudo** [comment]
I would expect that to work, I'll check.

In the meanwhile, you can try
```js
module.exports = {
  presets: [
    ['@babel/preset-env', {
      targets: {
        browsers: [`node ${node}`]
      }
    }]
  ]
};
```

**Comment by stevenvachon** [comment]
Awesome, `browsers` worked, despite being a bit confusing.

**Comment by nicolo-ribaudo** [comment]
Yeah "browsers" is what gets passed to browserslist.
