### ISSUE TITLE
throw new Error("only one instance of babel/polyfill is allowed");

### ISSUE THREAD

**Issue by fundon** [babel/babel#1019]
`babel/polyfill` problem

dirs tree:

```
├── server.js
├── node_modules
│   └── trek
```

Both `server.js` and `node_modules/trek` use ES6+ syntax.

### server.js

```js
import Trek from 'trek';

var app = new Trek(__dirname);

app.get('/', function* (next) {
  this.body = 'Hello Trek.js!';
});

app.on('error', function (err, context) {
  app.logger.error(err);
});

app.run();
```

###  index.js of trek module

```js
import Trek from './lib/trek';

export default Trek;
```

### run the server.js

```bash
$ babel-node server.js
```

output:

```
/Users/fundon/dev/trekjs/trek-cli/trekapp/node_modules/babel/lib/babel/polyfill.js:4
  throw new Error("only one instance of babel/polyfill is allowed");
        ^
Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/fundon/dev/trekjs/trek-cli/trekapp/node_modules/babel/lib/babel/polyfill.js:4:9)
....
```

How to solve it?

**Comment by sebmck** [comment]
The error message is pretty clear, only one instance of the polyfill should be used at all times. You have two modules with different versions of `babel` polluting globals with polyfills which leads to weird bugs. Either have the modules that are using `babel/polyfill` set to the same version so it resolves to the same module or compile the code with the [runtime transformer](https://babeljs.io/docs/usage/runtime).

**Comment by fundon** [comment]
I'm sure the tow modules have same versions of `babel`.

**Comment by fundon** [comment]
When running `babel-node` cmd will `ignore` the packages in the `node_modules` directory.
https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L34

So I hacked it in the `server.js` file, based on https://github.com/postcss/postcss/blob/master/index.js.

```js
var escape = function (str) {
    return str.replace(/[\[\]\/{}()*+?.\\^$|-]/g, "\\$&");
};

var regexp = ['lib', 'test', 'node_modules/god'].map(function (i) {
    return '^' + escape(path.join(__dirname, i) + path.sep);
}).join('|');

require('babel/register')({
    only:   new RegExp('(' + regexp + ')'),
    ignore: [ 'node_modules' ],
    loose: 'all'
});
```

And the `shouldIgnore` function
https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L75-L77

Maybe this will be better:

```js
var shouldIgnore = function shouldIgnore(filename) {
  if (onlyRegex && onlyRegex.test(filename)) {
    return false;
  }
  return ignoreRegex && ignoreRegex.test(filename);
};

```

@sebmck  Do you need I submit a PR for this?

**Comment by fundon** [comment]
I think `Babel` should not ignore all `node_modules` path.
Maybe check a identifier in `package.json` and transform the module automagically that will be great.

**Comment by hax** [comment]
This issue should be reopen. It's impossible to control all the deps (and the deps of a dep) to use same version (and even same versions still throw error) or use runtime transformer.

**Comment by loganfsmyth** [comment]
@hax Dependencies should not be loading the polyfill at all. If they rely on global ES6 features, then they need to document that and the root application should ensure that a polyfill is loaded, or the deps should use the `runtime` transform to load a non-global version of the polyfill.

**Comment by hax** [comment]
@loganfsmyth I assume all you said is correct , then:
0. The document of babel should include the caveat for the library writers
0. Runtime transformer should be in the default list not optional, and
0. Ask the major libraries which use babel to recompile and republish their packages.

**Comment by ruslansavenok** [comment]
If you use react.js on server and client, you might already have `babel/polyfill` loaded in node, but not in browser, this hack in my root file solved the problem:

```
// In node.js env, polyfill might be already loaded (from any npm package),
// that's why we do this check.
if (!global._babelPolyfill) {
  require('babel-core/polyfill')
}
```

**Comment by ruslansavenok** [comment]
If you use react.js on client and server, you might have babel/polyfill already loaded in node.js but not browser. 

This is how i solved it:
```
// In node.js env, polyfill might be already loaded (from any npm package),
// that's why we do this check.
if (!global._babelPolyfill) {
  require('babel-core/polyfill')
}
```

**Comment by sklyukin** [comment]
@ruslansavenok thx, works for me.

**Comment by hax** [comment]
@fundon I agree with you that babel should support compiling module by checking the fields in package.json (maybe `"babel": true, "main-babel": "src/index.js"`)

**Comment by fundon** [comment]
@hax thx.
haha, You can submit a PR for this.

**Comment by jameslk** [comment]
So what are we supposed to do with Babel 6? It looks like the runtime is no longer used. I'm trying to write a library using ES6 and I do not want to pollute the global namespace with polyfills.

**Comment by loganfsmyth** [comment]
@jameslk Please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by jameslk** [comment]
@loganfsmyth Thanks. I figured it out anyway. It looks like babel-runtime has been moved to babel-plugin-transform-runtime and this needs to be added to the list of plugins to use it. Would of helped if that was documented somewhere.
