### ISSUE TITLE
Failing tests on a windows machine due to path format

### ISSUE THREAD

**Issue by sag1v** [babel/babel#10209]
When running `yarn jest transform-runtime`
The `packages/babel-plugin-transform-runtime/test/index.js` tests fails with (not the backslashes `\` -> `//`):
```
- var _classCallCheck = require("<CWD>/packages/babel-plugin-transform-runtime/node_modules/@babel/runtime/helpers/classCallCheck");
+ var _classCallCheck = require("<CWD>\\packages\\babel-plugin-transform-runtime\\node_modules\\@babel\\runtime/helpers/classCallCheck");
```
When running `make test`, all of these fail
- packages/babel-core/test/config-chain.js
- packages/babel-preset-env-standalone/test/babel-preset-env.js
- packages/babel-generator/test/index.js
- packages/babel-plugin-transform-react-jsx-source/test/index.js
- packages/babel-preset-react/test/preset-options.js
- packages/babel-plugin-transform-runtime/test/index.js
- packages/babel-preset-env/test/debug-fixtures.js
- packages/babel-generator/test/index.js

Windows 7 (x64)

**Comment by JLHwung** [comment]
@sag1v Could you attach the jest result report? It can help us narrow down the list of affected modules. You can do it like
```
yarn jest > test-report.log 2>&1
```
