### ISSUE TITLE
@babel/preset-env Can't install?

### ISSUE THREAD

**Issue by yizhengfeng-jj** [babel/babel#10213]
## Bug Report

@babel/preset-env Can't install

**Input Code**
用npm 安装
```js
npm install @babel/preset-env
```

**Environment**
npm 6.1.0

**Possible Solution**
My npm version was originally 6.10.0, thought it was a version issue, upgrade to 6.10.1

**Additional context/Screenshots**
this is error log.
![image](https://user-images.githubusercontent.com/20452750/61171134-f0398880-a5a5-11e9-9194-e4e4a2214a65.png)

**Comment by nicolo-ribaudo** [comment]
Your download has been corrupted. Try clearing your cache and reinstalling it.
