### ISSUE TITLE
Add MIT license file to project

### ISSUE THREAD

**Issue by MerlinMason** [babel/babel#10229]
## Feature Request

**Is your feature request related to a problem? Please describe.**
For compliance reasons we're currently compiling a list of licenses for OSS projects we use. To do this we're using an automated tool (https://www.npmjs.com/package/license-reporter) this expects a `LICENSE` file to be present in the root of the repo.

**Describe the solution you'd like**
MIT `LICENSE` file to be added to the root of the repo. Happy to raise a PR :)

**Describe alternatives you've considered**
N/A

**Teachability, Documentation, Adoption, Migration Strategy**
N/A

**Comment by nicolo-ribaudo** [comment]
Do you need in the repo or in the published packages?

**Comment by MerlinMason** [comment]
In the published packages would be ideal.

**Comment by existentialism** [comment]
@MerlinMason do you know which published package doesn't have the `LICENSE` file?

We copy the file at publish time via https://github.com/babel/babel/blob/master/scripts/clone-license.sh
(Ref: https://github.com/babel/babel/pull/8409)

**Comment by MerlinMason** [comment]
It's the babel-polyfill package, in my `package.json` I have `"babel-polyfill": "^6.26.0",` and this gives me the following in my `node_modules` directory:

![image](https://user-images.githubusercontent.com/3215478/61367429-7b0ad380-a883-11e9-9a85-c859e5c73dfd.png)

**Comment by nicolo-ribaudo** [comment]
We aren't updating v6 packages anymore; `@babel/polyfill` v7 has the license file.

**Comment by MerlinMason** [comment]
Ahh ok, thanks for letting me know, best I upgrade then :)
