### ISSUE TITLE
How can I skip files that caused error?

### ISSUE THREAD

**Issue by fengh16** [babel/babel#10222]
I'm trying to use babel to transfer all files in a folder, and some of the files can't be parsed successfully. So the process of babel stopped when such error occurs. How can I just skip the file that caused error? (I think there may be a parameter to do so)

(Now there are js files in a folder named `js_code`, and I used the command `babel js_code -d js_converted` to convert all the files and store them in the folder `js_converted`, when a file caused error such as `Unexpected token`, the babel process will stop. I want the process just ignore these files and convert the other)

**Comment by Letladi** [comment]
@fengh16 [this](https://babeljs.io/docs/en/babel-cli#ignore-files) might help.

**Comment by fengh16** [comment]
> @fengh16 this might help.
> You're looking at something like this:
> npx babel src --out-dir lib --ignore "src/file1.js","src/file2.js"

I know this parameter, but I'm facing a more difficult situation:  there are too many files, and they are not obeying the same rule. It's not possible to list all files that caused error.

In fact, I'm trying to train a code search module of JS, so I'm using **hundreds of thousands** of files (now there are 480000 js files). It's not useful for me to just ignore files.

(Now I wrote a python script to list the names of files and deal with each of them. It works, but each file need about 1.5 second. Considering the number of files, it's a lot of time.)

**Comment by nicolo-ribaudo** [comment]
I suggest writing a node script which calls `babel.transformSync` with a try/catch block, instead of using `@babel/cli`.

**Comment by Letladi** [comment]
You may also consider [changing](https://github.com/babel/babel/blob/d8da63c929f2d28c401571e2a43166678c555bc4/packages/babel-cli/src/babel/dir.js#L13) babel-cli itself to suit your own needs, or perhaps suggest the addition of a `--skip-failing` option to babel-cli if other people have a similar need

**Comment by fengh16** [comment]
> You may also consider changing babel-cli itself to suit your own needs, or perhaps suggest the addition of a --skip-failing option to babel-cli if other people have a similar need

Thank you! I'm trying to add such an option now.

**Comment by nicolo-ribaudo** [comment]
I don't think that that option should be added to `@babel/cli` (you can add it in a fork), since apart from your very specific use case, if a file isn't compiled the app doesn't run.
