### ISSUE TITLE
Unable to use babel-runtime out-of-the-box with System.js

### ISSUE THREAD

**Issue by cmaher** [babel/babel#1022]
(previously opened against systemjs/systemjs https://github.com/systemjs/systemjs/issues/374)

When using the Babel option 'runtime' with SystemJs, Babel loads helper functions as separate files instead of inlining them in every file. This option can be enabled with:

```js
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  }
```

This configuration causes babel to load helper functions from files that look like:
```js
// babe-runtime/helpers/create-class.js
exports["default"] = (function () {
  return function () {
    // ...
  };
})();

exports.__esModule = true;
```
(I've downloaded and built the current master of Babel and babel-runtime to confirm that this is still the case)

When this file is loaded, it's interpreted as the object
```js
var _createClass = { 
  default: function () { /* the create-class function */ }, 
  __esModule: true}`
}
```
But Babel calls it as a method: `_createClass(/*...*/)`, which fails, because _createClass is an object, and not a function.

I'm working around this with the following configuration:
```js
var systemInstantiate = System.instantiate;
System.instantiate = function (load) {
  if (~load.name.indexOf('babel-runtime')) {
    load.source = load.source + '\n;module.exports = module.exports["default"];';
  }
  return systemInstantiate.call(this, load);
};
```
using `System.instantiate` instead of a plugin, since I can't change Babel's loading of `babel-runtime`.

In the issue I originally opened against SystemJs @guybedford writes:
> if the helper is meant to be interpreted as a single export style module, then it shouldn't have the `__esModule` flag set.

which implies that this is probably a Babel issue.

This is very similar to https://github.com/babel/babel/issues/774, but the fix for that (https://github.com/babel/babel/commit/8a5da5716278a74a53691c77475a88773cd4ae4c) only seems to have addressed Babel's internal usage of `core-js` while not addressing the case where external modules load the helper functions.

**Comment by sebmck** [comment]
Note `_classCallCheck = _babelRuntimeHelpersClassCallCheck["default"];`.

```javascript
System.register(["babel-runtime/helpers/class-call-check"], function (_export) {
  var _classCallCheck, Foo;

  return {
    setters: [function (_babelRuntimeHelpersClassCallCheck) {
      _classCallCheck = _babelRuntimeHelpersClassCallCheck["default"];
    }],
    execute: function () {
      "use strict";

      Foo = function Foo() {
        _classCallCheck(this, Foo);
      };
    }
  };
});
```

**Comment by sebmck** [comment]
The current `.default` access was specifically requested by @guybedford in #774 so I'm not sure what the issue is.

**Comment by cmaher** [comment]
When the code is loaded/transpiled, I have:

```js
(function() { var __moduleName = "lib/test-class"; var __moduleAddress = "http://localhost:9876/base/lib/test-class.js";System.register(["babel-runtime/helpers/class-call-check", "babel-runtime/helpers/create-class"], function (_export) {
  var _classCallCheck, _createClass, TestClass;

  return {
    setters: [function (_babelRuntimeHelpersClassCallCheck) {
      _classCallCheck = _babelRuntimeHelpersClassCallCheck["default"];
    }, function (_babelRuntimeHelpersCreateClass) {
      _createClass = _babelRuntimeHelpersCreateClass["default"];
    }],
    execute: function () {
      "use strict";

      TestClass = (function () {
        function TestClass() {
          _classCallCheck(this, TestClass);
        }

        _createClass(TestClass, {
          test: {
            value: function test() {}
          }
        });

        return TestClass;
      })();

      _export("default", TestClass);
    }
  };
});
```

which is generated from 

```js
'use strict';

export default class TestClass {
  constructor() {}
  test(){}
}
```

When this gets run, both `_classCallCheck` and `_createClass` are `{ default: <correct_function>, __esModule: true }`.

I think the difference from #774 is that in this case, the helpers are being loaded individually.

**Comment by sebmck** [comment]
If `_createClass ` isn't a function then it'd be a SystemJS bug then since `_createClass = _babelRuntimeHelpersCreateClass["default"];` is set which should be getting the function.

**Comment by cmaher** [comment]
Thanks for the help. I posted this sample code for debugging purposes: https://github.com/cmaher/systemjs-babel-runtime

**Comment by cmaher** [comment]
So I'm now convinced that jspm is downloading incompatible versions of SystemJS and Babel. Sorry for the run-around (again).

**Comment by sebmck** [comment]
All good! Better to be safe than sorry. Check out the [gitter room](gitter.im/babel/babel) if you run into anymore issues :smile:
