### ISSUE TITLE
A way to disable cloneDeep in a @babel/core transformFromAstSync

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#10231]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue with `@babel/core` when I’m using [transformFromAstSync](https://babeljs.io/docs/en/next/babel-core.html#transformfromastsync) [cloneDeep is used](https://github.com/babel/babel/blob/a9a7f4e690b15d569deb8a53719f37d6dc09393b/packages/babel-core/src/transformation/normalize-file.js#L79).
I’m passing `AST` generated by `babel` with help of [recast](https://github.com/benjamn/recast), which stores information about code structure in `prototype` of objects, and this information is lost after transform.

**Describe the solution you'd like**
Would be great to have ability to pass an option  `deepCopy` or something like this, to prevent AST from copying.

**Describe alternatives you've considered**
Alternative solution would be copy `AST` in a compatible with `recast` manner.

**Teachability, Documentation, Adoption, Migration Strategy**

```js
const sourceCode = "if (true) return;";
const parsedAst = babel.parse(sourceCode, { allowReturnOutsideFunction: true });
const { code, map, ast } = babel.transformFromAstSync(parsedAst, sourceCode, {
  ast: true,
  deepCopy: false,
});
```

I’m working on pluggable code transformer [putout](https://github.com/coderaiser/putout), which have it’s own [plugins api](https://github.com/coderaiser/putout#plugins-api), but I have an idea to add support of babel plugins as well, and don’t want to fork `@babel/core` or relay on implementation details for this purpose. The main feature of `putout` is ability to change as small code as possible and keep code style as it is, but after `transformFromAstSync` there is a full file change with a lot modifications here in there.

Idea to support babel plugins came to me after I saw [babel roadmap](https://babeljs.io/docs/en/roadmap#codemods-for-tc39-proposals) which says that babel going to support codemods, and this is amazing :).

**Comment by nicolo-ribaudo** [comment]
Until this is supported, you can work around this problem like I did at https://github.com/nicolo-ribaudo/legacy-decorators-migration-utility/blob/1c9f306b5287bb2d5d07a512d1ad84036fd4956a/packages/wrap-legacy-decorators/src/index.js#L119-L140

**Comment by coderaiser** [comment]
@nicolo-ribaudo that's nice, my workaround [became much bigger](https://github.com/coderaiser/putout/blob/f28a1dea128eb0dfa82ac26098393b84102df68f/packages/putout/lib/run-babel-plugins/index.js) 🙂.
