### ISSUE TITLE
Decorators plugin is unclear about what `legacy: true` is for exactly

### ISSUE THREAD

**Issue by catamphetamine** [babel/babel#10234]
The plugin page says:

https://babeljs.io/docs/en/babel-plugin-proposal-decorators

> `legacy`
`boolean`, defaults to `false`.
Use the legacy (stage 1) decorators syntax and behavior.

And that's it.
It's unclear what are the breaking changes when moving from `legacy: false` to `legacy: true`.

**Comment by nicolo-ribaudo** [comment]
You can find some info at https://babeljs.io/blog/2018/09/17/decorators

**Comment by catamphetamine** [comment]
@nicolo-ribaudo Thx.
So could we say that:

> `legacy: true` flag means that the decorators spec hasn't been finalized yet and `legacy: false` is therefore reserved for the future when the spec is finalized. The only valid option for `legacy` currently is `true`, so you're supposed to always pass it. There may be some breaking changes in the finalized spec or there may be none. For now, there're no breaking changes.

**Comment by nicolo-ribaudo** [comment]
- `legacy: true` is the proposal as it was about 3 years ago
- `legacy: false` is the proposal as it was at the end of 2018
- The current proposal is not supported yet; I'm working on it.

**Comment by catamphetamine** [comment]
Yeah, that's cool, I mean the visitors of the documentation page would be confused about what does `legacy: true` flag add or remove.
I suggest that you leave a note there explaining how a user would decide whether to use `legacy: true` or not.
Or maybe you could just include there the link you posted here.
I'm closing this issue because I think you got the message.
