### ISSUE TITLE
Decorators of ClassProperty is not same in babel and typescript

### ISSUE THREAD

**Issue by legu2009** [babel/babel#10236]
## Decorators of ClassProperty is not same in babel and typescript

**Input Code**

```js
function o() { }
class A {
    @o
    b = 1
}
```

**Current Behavior**
using typescript, in constructor of class A,  'this.b = 1;'
but using babel, is not same.

use babel
```js
var A = _decorate(null, function (_initialize) {
  var A = function A() {
    _classCallCheck(this, A);

    _initialize(this);
  };

  return {
    F: A,
    d: [{
      kind: "field",
      decorators: [o],
      key: "b",
      value: function value() {
        return 1;
      }
    }]
  };
});
```

use typescript
```js
var A = /** @class */ (function () {
    function A() {
        this.b = 1; //is not same
    }
    __decorate([
        o
    ], A.prototype, "b", void 0);
    return A;
}());
```

**Expected behavior/code**
make them same

**Possible Solution**

**Comment by nicolo-ribaudo** [comment]
You need to pass the `legacy: true` option to the decorators plugin and `loose: true` to the class properties plugin.
