### ISSUE TITLE
transpiled version of `{...window.location}` doesn't work in IE 11

### ISSUE THREAD

**Issue by Hypnosphi** [babel/babel#10233]
## Bug Report

**Current Behavior**
Using `window.location` in an object spread causes an error in IE 11.
E.g., if you open https://hypnosphi.github.io/repro-babel-location-ie/ in IE:
<img width="770" alt="Screen Shot 2019-07-17 at 19 06 12" src="https://user-images.githubusercontent.com/6651625/61395896-c85c6480-a8c6-11e9-8f76-04aea283ff65.png">

**Input Code**
https://github.com/Hypnosphi/repro-babel-location-ie

```js
const locationCopy = {...window.location};
console.log(locationCopy);
```

**Expected behavior/code**
No error, a copy of location object logged to console

**Babel Configuration (.babelrc, package.json, cli command)**

https://github.com/Hypnosphi/repro-babel-location-ie/blob/master/.babelrc

**Environment**
- Babel version(s): 7.5.4
- Node/npm version: Node 10 / npm 6
- OS: macOS 10.14.5
- Monorepo: no
- How you are using Babel: webpack loader

**Possible Solution**
Don't rely on native `getOwnPropertyDescriptor` as it's buggy in IE

**Additional context/Screenshots**
Problem doesn't reproduce if I enforce `@babel/helpers` versions to be `7.5.1`: https://github.com/Hypnosphi/repro-babel-location-ie/commit/3cecfd7455a78b6ab79e3b2f3a849ee7a29eb181
It's probably introduced by #10171 (ironically)

**Comment by nicolo-ribaudo** [comment]
This seems like a missing polyfill feature in `core-js` (which is where the code you screenshotted comes from). Could you re-open it at https://github.com/zloirock/core-js?

**Comment by zloirock** [comment]
See https://github.com/zloirock/core-js/issues/601#issuecomment-514768457

**Comment by Hypnosphi** [comment]
Seems fixed with https://github.com/babel/babel/pull/10189
