### ISSUE TITLE
Error with object spread property when not used in assignment or call

### ISSUE THREAD

**Issue by jwarkentin** [babel/babel#1023]
Using the proposed es7 spread properties I was playing around and I found that when I do this:
```js
let obj = { a: 3, b: 4 };
{x: 1, y: 2, ...obj};
```

It throws an error and dies. However, if I simply include it in an assignment:
```js
let obj = { a: 3, b: 4 };
obj = {x: 1, y: 2, ...obj};
```

or a function call:
```js
let obj = { a: 3, b: 4 };
console.log({x: 1, y: 2, ...obj});
```

then it works just fine.

Granted, something like that should probably just be removed as dead code, but it shouldn't throw an error. I was actually trying to do it without an assignment just to see what the compiled output looked like.

**Comment by sebmck** [comment]
This is expected behaviour. It's completely unrelated to the object spread and is standard JavaScript behaviour. Parsing just:

```javascript
{x: 1, y: 2};
```

Will cause it to be parsed a block statement.

**Comment by jwarkentin** [comment]
Hah, duh. Good point. I wish the parser could look see the colons and commas and realize it's an object though.

**Comment by sebmck** [comment]
Adds too much complexity to the grammar for a scenario that's not really useful.
