### ISSUE TITLE
About how to useBuiltIns options for polyfill

### ISSUE THREAD

**Issue by galenjiang** [babel/babel#10239]
Question description
I have a lib without polyfill, and another app depends on it,  and compiled with webpack and babel, webpack babel-loader exclude /node_modules/.
I have no idea how to config babel with polyfill, the project has browserslist configure, I have two choice, but none can be satisfied:
1. define useBuiltIns: 'entry', but all polyfill included
2. useBuiltIns: 'usage', only get main project polyfill, but the lib can not polyfilled cause the babel config exclude the lib directory

expected:
It can import both lib and main app all polyfills by using browserlist.

**Comment by JLHwung** [comment]
I would suggest stick with `useBuiltIns: 'usage'` and note that you can always exclude `node_modules` but include one by
```js
{
  use: "babel-loader",
  exclude: /node_modules(?!\/my-awesome-module)/
}
```

**Comment by existentialism** [comment]
> I have no idea how to config babel with polyfill

Would welcome suggestions for how to improve:
https://babeljs.io/docs/en/babel-preset-env#usebuiltins

There's some proposed changes here too:
https://github.com/babel/website/pull/2067

**Comment by galenjiang** [comment]
I misunderstanding the configure of ```useBuiltIns: 'entry'```, I tried it again by using core-js@3/stable, it worked and only import the necessary based on environment.
