### ISSUE TITLE
Cannot find module '@babel/types'.  TS2307

### ISSUE THREAD

**Issue by nicewaytodoit** [babel/babel#10237]
I am getting this error on yarn start.

$ yarn -v 1.13.0
$ npm -v 6.10.1
$ node v10.15.0

```
C:/proj/node_modules/@types/babel__core/index.d.ts
TypeScript error in C:/proj/node_modules/@types/babel__core/ind
ex.d.ts(13,20):
Cannot find module '@babel/types'.  TS2307

    11 | import traverse, { Visitor, NodePath } from "@babel/traverse";
    12 | import template from "@babel/template";
  > 13 | import * as t from "@babel/types";
       |                    ^
    14 | import { ParserOptions } from "@babel/parser";
    15 |
    16 | export {
```

```
"dependencies": {
    "@babel/core": "^7.5.5",
    "@babel/types": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "@svgr/webpack": "4.3.2",
    "@types/react": "^16.8.23",
    "@types/react-dom": "^16.8.4",
    "@typescript-eslint/eslint-plugin": "1.12.0",
    "@typescript-eslint/parser": "1.12.0",
    "babel-eslint": "10.0.2",
    "babel-jest": "^24.8.0",
    "babel-loader": "8.0.6",
    "babel-plugin-named-asset-import": "^0.3.2",
    "babel-preset-react-app": "^9.0.0",
    ...
```
Any clue, I have done already rm -rf node_modules, and clean install.
Am I missing something globally ?

**Comment by JLHwung** [comment]
The error comes from `@types/babel__core` and it should depend on `@types/babel__types`. You may have a corrupted node_modules. You can check why there is `@types/babel__core`:
```
npm list @types/babel__core
```
It may also help if you can attach your `tsconfig.json`.

**Comment by nicewaytodoit** [comment]
tsconfig.json
```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "strictNullChecks": true,
        "module": "es6",
        "jsx": "react",
        "target": "es5",
        "allowJs": true
    },
    "include": [
        "./src/"
    ]
}


and npm list @types/babel__core
```
`-- babel-jest@24.8.0
  `-- @types/babel__core@7.1.2
```

**Comment by JLHwung** [comment]
Please add this to your `tsconfig.json`.
```json
{
  "compilerOptions": {
     "moduleResolution": "node"
  }
}
```

Since you have specified `modules: "es6"` on your tsconfig.json. TypeScript Compiler will use `Classic` module resolution, which unfortunately, does not resolve non-relative imports in `node_modules`. ([docs])

[docs]: https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies

**Comment by nicewaytodoit** [comment]
Thank you! That worked. I am closing this ticket.
