### ISSUE TITLE
@babel/node doesn't use presets

### ISSUE THREAD

**Issue by Banou26** [babel/babel#10246]
## Bug Report

**Current Behavior**
@babel/node doesn't use presets like @babel/preset-typescript

**Input Code**
`npx @babel/node script.ts --presets @babel/preset-typescript --extensions ".ts"`

```ts
// script.ts
interface Foo {}
```

**Expected behavior/code**
@babel/node should use presets like @babel/preset-typescript and run node  with the babel transpiled code

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/node": "^7.5.5",
    "@babel/preset-typescript": "^7.3.3"
  }
}
```

**Comment by JLHwung** [comment]
Workaround:
```
npm i --save-dev @babel/node
node ./node_modules/.bin/babel-node script.ts --presets @babel/preset-typescript --extensions .ts
```

**Comment by Banou26** [comment]
Yup, `babel-node` does work, thanks.
I'm leaving this open if you wanna rename it to an issue to update the docs.

**Comment by JLHwung** [comment]
@Banou26 Thank you. I have submitted document updates here: https://github.com/babel/website/pull/2070

Close this issue as it is not related to babel functionalities.
