### ISSUE TITLE
t. classProperty should allow to create static class property

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/babel#10247]
t. classProperty should allow to create static class property e.g.

```js
t.classProperty(key, value, typeAnnotation, decorators, computed, static);
```
or
```js
t.classStaticProperty(key, value, typeAnnotation, decorators, computed)
```
that will help to create plugins that efficiently work with babel decorators plugin that simpy ignores good old ```ClassName.prop = 1``` notation.

**Comment by JLHwung** [comment]
The builders in babel-type is generated from [type definitions](https://github.com/babel/babel/tree/master/packages/babel-types/src/definitions). For `classStaticProperty` to be a valid builder method, we should define a new `ClassStaticProperty` type, which I think is overkill and we don't do it on `ClassMethod`, `ClassPrivateMethod` as well.

I prefer to extend our current signature of `t.classProperty` from
```
t.classProperty(key, value, typeAnnotation, decorators, computed);
```

to
```
t.classProperty(key, value, typeAnnotation, decorators, computed, static);
```

As `t.classMethod` and `t.classPrivateMethod` both have `static` in its builder, I think it's not bad to have `t.classProperty` aligned with them.

I will mark this issue as good first, PR's welcome. 

Hint: Check `ClassProperty` type definitions and look through the `builder` field.
