### ISSUE TITLE
Support Browserslist in plugin-transform-runtime?

### ISSUE THREAD

**Issue by slavafomin** [babel/babel#10250]
Hello!

And once again, thank you for your hard work.

The `@babel/plugin-transform-runtime` has an option called `corejs`, which once specified, replaces language constructs with imports to `@babel/runtime-corejs*`. I like the idea of using a sandboxed polyfills, versus global ones. This should play nicely with libraries.

However, the `@babel/plugin-transform-runtime` doesn't respect the Browserslist and when `corejs` option is enabled it replaces everything it could, even the features that have good browser support. Eventually, this makes final bundles huge in size, which makes this option practically unusable for us.

Do you think this feature could be improved somehow to add imports only for the polyfills required according to the Browserslist?

Thanks!

**Comment by nicolo-ribaudo** [comment]
Related: https://github.com/babel/babel/issues/10008

**Comment by nicolo-ribaudo** [comment]
This is now implemented in https://github.com/babel/babel-polyfills
