### ISSUE TITLE
Runtime dependency spits out advertisement on install

### ISSUE THREAD

**Issue by mclark-newvistas** [babel/babel#10253]
## Bug Report

**Current Behavior**

When I updated `pdfmake`, which depends on `pdfkit`, which depends on `fontkit`, which depends on `babel-runtime`, `core-js`, which `babel-runtime` depends on, printed an advertisement.

```
~/n/project$ npm update

> core-js@2.6.9 postinstall /home/user/n/project/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ pdfmake@0.1.57
...
added 15 packages from 75 contributors, removed 20 packages, updated 61 packages, moved 5 packages and audited 1119 packages in 12.369s
found 0 vulnerabilities
```

**Expected behavior/code**

When I run `npm update` I am not shown advertisements.

**Environment**
- Babel version(s): v6.26.0
- Node/npm version: 8.4.0/6.10.0
- OS: Arch Linux
- Monorepo: ?
- How you are using Babel: as an indirect dependency of `pdfmake`

**Possible Solution**

Remove `core-js` dependency, to remove the advertisement, and to demonstrate to other node module maintainers that unsolicited advertising is not encouraged in the node developer community.

The sender of the first spam (unsolicited advertising) email doesn't regret it; I doubt the maintainer of `core-js` will either. A response must come from the community level - not (just) from irritated individuals. We have the example of email to learn from if we do not discourage unsolicited advertising now that it's encroached upon our terminals.

**Comment by mclark-newvistas** [comment]
Looking further into this issue - looks like PouchDB had a solution to remove the advertisement https://github.com/pouchdb/pouchdb/issues/7392

**Comment by nukeop** [comment]
Spamming ads in install logs is against npm terms of use, but maintainers of large packages that were shoehorned as dependencies into many projects get a get-out-of-jail-free card and a license to spam. Npm needs an option to disable all printing in pre-/postinstall that's enabled by default.

**Comment by nicolo-ribaudo** [comment]
`babel-runtime` is just a wrapper around `core-js`. It's not a "simple" dependency that we use internally, but it fully exposes it to the `babel-runtime` user.
The core-js developer has provided different options to disable the message:

```
ADBLOCK=true npm install
CI=true npm install
DISABLE_OPENCOLLECTIVE=true npm install
npm install --loglevel warn
```
