### ISSUE TITLE
@babel/core parseAsync doesn't allow the parse options

### ISSUE THREAD

**Issue by caub** [babel/babel#10256]
## Bug Report

I copied the example from the docs: https://babeljs.io/docs/en/babel-core#transformfromastasync

<sub>note: there's a typo `transformFromAstSync`/`transformFromAstAsync`</sub>

and I get this error:

> ReferenceError: Unknown option: .allowReturnOutsideFunction. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.

here's the code:
```js
const babel = require('@babel/core');

(async () => {
  const sourceCode = "if (true) return;";
  const parsedAst = await babel.parseAsync(sourceCode, { allowReturnOutsideFunction: true });

  const { code, map, ast } = await babel.transformFromAstAsync(parsedAst, sourceCode, options);

  console.log(code, ast);
})()
```

https://repl.it/@caub/babel-parse

babel version: ^7.5.5 (tested locally, the babel version is probably lower in repl.it)

**Comment by caub** [comment]
Ok, this is solved by using babel/parser:

```js
const babel = require('@babel/core');
const babelParser = require('@babel/parser');

(async () => {
  const sourceCode = "if (true) return;";
  const parsedAst = babelParser.parse(sourceCode, { allowReturnOutsideFunction: true });

  const { code, map, ast } = await babel.transformFromAstAsync(parsedAst, sourceCode, options);

  console.log(code, ast);
})()
```

**Comment by nicolo-ribaudo** [comment]
The problem in the docs is that `babel.parse(Async)` expects as options "Babel options", not "parser options"

**Comment by caub** [comment]
like this so: https://github.com/babel/website/pull/2072/files#diff-f25cc7613a9dc426e5a6fb653c139200
