### ISSUE TITLE
NullishCoalescing forbids mixing with LogicalExpressions without parenthesis

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#10260]
## Bug Report

**Current Behavior**
The nullish coalescing operator (`??`) currently allows mixing with the other logical operators (`||` and `&&`) without parenthesis. This is invalid per the latest specs, parenthesis are required to mix them:

```js
// Currently valid but should be a syntax error
a ?? b || c

// Currently valid but should be a syntax error
a || b ?? c

// Currently valid but should be a syntax error
a ?? b && c

// Currently valid but should be a syntax error
a && b ?? c
```

https://babeljs.io/repl/#?babili=false&browsers=Safari%2011&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEGEFcCdoUwHYBcA2BPUA3AhiglgCagBGkSoAzgBYD2kKRxco2lay2AHqHLDdAChWAfmElQAHwmgAxgIEgIMeMnRZchEmUq16jZqwrskXHn0Gsp40bPmKosRKgw58jbdToMSBth2680PxCoDbEoABkEbYKYA4qzupuWuSeej4sfiYB5iFR1mJyQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=true&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-proposal-nullish-coalescing-operator%407.4.4

**Expected behavior/code**
These should each throw a syntax error when parsing. It requires parens to disambiguate the intended grouping.

```js
// Valid according to spec
a ?? (b || c)

// Valid according to spec
(a ?? b) || c

// Valid according to spec
(a || b) ?? c

// Valid according to spec
a || (b ?? c)

// Valid according to spec
a ?? (b && c)

// Valid according to spec
(a ?? b) && c

// Valid according to spec
(a && b) ?? c

// Valid according to spec
a && (b ?? c)
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["proposal-nullish-coalescing-operator"]
}
```

**Environment**
- Babel version(s): 7

**Possible Solution**
These should throw during parsing. Somewhere around https://github.com/babel/babel/blob/fced5cea430cc00e916876b663a8d2a84a5dad1f/packages/babel-parser/src/parser/expression.js#L383-L390.

 Additionally, when printing the AST, the nullish coalescing operator should print parenthesis around the left/right hand side if they are the other logical operators. Somewhere around https://github.com/babel/babel/blob/fced5cea430cc00e916876b663a8d2a84a5dad1f/packages/babel-generator/src/generators/expressions.js#L232.

**Comment by vivek12345** [comment]
Can someone who has not contributed previously to Babel take this up?

**Comment by jridgewell** [comment]
Yes!

**Comment by dhruvdutt** [comment]
Can I pick this up? ✋

**Comment by vivek12345** [comment]
@dhruvdutt I have started looking into it.

**Comment by jridgewell** [comment]
I think this goes to @vivek12345 first, but you're welcome to collaborate with them on a PR?

**Comment by vivek12345** [comment]
@jridgewell Should I be checking in the parser if A) if op === tt.nullishCoalescing and B)  check if we have other logical operators around it and if yes then `throw raise an error`.
Am I thinking in the right direction here?

**Comment by jridgewell** [comment]
You're on the right track, but we only raise an error if the other operators are unparenthesized. `(a ||b) ?? c` is legal. Also note that we need to raise an error for both `a ?? b || c` _and_ `a || b ?? c`.

**Comment by vivek12345** [comment]
Understood. Also `a ?? b ?? c` this would be valid right? This won't need a parenthesis around.

**Comment by vivek12345** [comment]
@jridgewell while printing the AST with parenthesis, I see AssignmentExpression being exported as  LogicalExpression and inside AssignmentExpression I see a check for parenthesis needed and then accordingly it is adding a new token `(` before left node and then a `)` after right.

In our case this would slightly change and we will have to check if we need this parenthesis or not and then also check where it should be places, right or left.

Am I right in understanding this?

**Comment by vivek12345** [comment]
Also I am trying to understand why would I need this change in the printing AST part. If I am not allowing an expression like a ?? b && c without the parenthesis and only allowing it with the parenthesis like this a ?? ( b && c ) so will babel-generate not automatically use the token `(` specified in the expression while constructing the tree.

Why do we have to explicitly add it?

**Comment by jridgewell** [comment]
> Also `a ?? b ?? c` this would be valid right? This won't need a parenthesis around.

Correct.

> I see AssignmentExpression being exported as LogicalExpression and inside AssignmentExpression I see a check for parenthesis needed and then accordingly it is adding a new token `(` before left node and then a `)` after right.

It's probably time we made an explicit function for `LogicalExpression`, since it's not more complicated.

> In our case this would slightly change and we will have to check if we need this parenthesis or not and then also check where it should be placed: - right or left.

Correct.

> Why do we have to explicitly add it?

Because it's possible to construct the AST by hand, and our printer should be smart enough to know that parenthesis are required:

See https://astexplorer.net/#/gist/a896ac99208d75fac59b9924facbdf7e/20c49836c532c2db184df733f79d76d69d0cb476

**Comment by vivek12345** [comment]
@jridgewell I am a bit stuck at it now. My initial approach that I thought was to check 
```
if (op === tt.nullishCoalescing) {
    if (
        left.type === "LogicalExpression" &&
        left.operator !== "??" &&
        !(left.extra && left.extra.parenthesized)
    ) {
        throw this.raise(
            `Wrap left hand side of the expression in parentheses`,
        );
    }
```
and then do the same check for node.right but it seems the evaluation is left to right so even if right has a logical expression like let's say
a ?? c || d

Here a ?? c is considered as left and d is considered as right.

I was thinking a will be considering left and c || d would be a logical expression and with no paren and then I could just say wrap the right hand side in parenthesis.

Can you help me a bit here?

**Comment by vivek12345** [comment]
For something like this 
```
a ?? b && c || d
```
What should be the right parenthesis ordering?

**Comment by vivek12345** [comment]
Okay I have made some improvement.
@jridgewell Do you think this is in the right direction
```
if (op === tt.logicalOR) {
          if (
            left.type === "LogicalExpression" &&
            left.operator === "??" &&
            !(left.extra && left.extra.parenthesized)
          ) {
            throw this.raise(
              left.argument.start,
              `Wrap left hand side of the expression in parentheses`,
            );
          }
        }
        if (op === tt.nullishCoalescing) {
          if (
            left.type === "LogicalExpression" &&
            left.operator !== "??" &&
            !(left.extra && left.extra.parenthesized)
          ) {
            throw this.raise(
              left.argument.start,
              `Wrap left hand side of the expression in parentheses`,
            );
          } else if (
            node.right.type === "LogicalExpression" &&
            node.right.operator !== "??" &&
            !(node.right.extra && node.right.extra.parenthesized)
          ) {
            throw this.raise(
              this.state.start,
              `Wrap right hand side of the expression in parentheses.`,
            );
          }
        }
```

**Comment by jridgewell** [comment]
Can you open a PR (even if it’s not working 100%)? It’ll be easier for me to review and comment that way.

**Comment by vivek12345** [comment]
@jridgewell the repl is ready. Circle CI passed but CI failed due to `JOB=babel-parser-flow-tests`. Not really sure on why that failed.

**Comment by tanhauhau** [comment]
@vivek12345 the flow parser test case failed.

we borrowed the test case for flow parser from [here](https://github.com/facebook/flow/tree/master/src/parser/test/flow).

for example for your [`nullish_coalescing/precedence_and`](https://github.com/facebook/flow/blob/master/src/parser/test/flow/nullish_coalescing/precedence_and.js), flow parsed into [this ast](https://github.com/facebook/flow/blob/master/src/parser/test/flow/nullish_coalescing/precedence_and.tree.json), a passed case for them, but apparently this MR change will break this test case.

if according to the spec, they should fix their test case, we should raised an issue to them.

temporarily, we can whitelist the [test case here](https://github.com/babel/babel/blob/1d4d760ffc37e228814c06a482b6dcd87b44006b/scripts/tests/flow/flow_tests_whitelist.txt) for test cases that has discrepancy with flow's parser

**Comment by jridgewell** [comment]
I pushed a commit to whitelist the tests for now.

**Comment by vivek12345** [comment]
@tanhauhau and @jridgewell I have raised a bug on flow parser for the same issue.
https://github.com/facebook/flow/issues/7972
