### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@babel%2ftransform-react-jsx-source - Not found

### ISSUE THREAD

**Issue by talaikis** [babel/babel#10267]

**Comment by hzoo** [comment]
Hi @talaikis, thanks for the issue!

I can infer you aren't able to find a kind of package in the registry (or installing it). The package name has `plugin` in it, which is the convention for these packages. https://registry.npmjs.org/@babel/plugin-transform-react-jsx-source, https://www.npmjs.com/package/@babel/plugin-transform-react-jsx-source

> I would recommend next time you add a description to your issues that you create!

**Comment by talaikis** [comment]
> > I would recommend next time you add a description to your issues that you create!

Yeah, my wrong, copy pasted automatically updated module name from console and forgot to check if it's right, thanks.
