### ISSUE TITLE
Specify which types of comments should be removed

### ISSUE THREAD

**Issue by Markshall** [babel/babel#10272]
**Describe the bug**

I'm setting
```js
{
  "comments": false
}
```
...in my `babel.config.js` which obviously, as expected, removes all comments.

What I want to do is keep 'loud' comments, i.e. comments that start with `/*!` rather than just `/*` or `//`.
I know Sass/Scss allows this functionality but I've done some digging around and it looks as though Babel doesn't support it.

**To Reproduce**

Minimal code to reproduce the bug

```js
/*!
here is my loud comment
here is some more stuff to comment
*/

//here is a single-line comment

/*
here is a multi-line comment
*/
```

**Actual Output**

```js
```

**Expected Output**

```js
/*!
here is my loud comment
here is some more stuff to comment
*/
```

**Configuration**

```json5
module.exports = {
  "presets": [
    [
      "minify",
      {
        "keepFnName": false
      }
    ]
  ],
  "plugins": [
    ["@babel/plugin-transform-arrow-functions"],
    ["@babel/plugin-transform-destructuring"],
    ["@babel/plugin-transform-template-literals"]
  ],
  "comments": false
};
```

**Possible solution**

I'd suggest being able to specify which types of comments shouldn't be stripped out.  If no value is passed, then all comments should be removed.

For example, all comments would be removed here:
```js
{
  "comments": []
}
```

All comments except for loud comments will be removed:
```js
{
  "comments": ['loud']
}
```

Only single-line comments will be removed:
```js
{
  "comments": ['loud', 'multi-line']
}
```

**Comment by JLHwung** [comment]
I would suggest you define your own [`shouldPrintComment`](https://babeljs.io/docs/en/options#shouldprintcomment) handler. E.g.
```js
{
  shouldPrintComment(val) {
    return val.startsWith("!") // keep loud comments
  }
}
```
Note that in this case your babel config should be written as JavaScript instead of JSON.

**Comment by Markshall** [comment]
> I would suggest you define your own [`shouldPrintComment`](https://babeljs.io/docs/en/options#shouldprintcomment) handler. E.g.
> 
> ```js
> {
>   shouldPrintComment(val) {
>     return val.startsWith("!") // keep loud comments
>   }
> }
> ```
> 
> Note that in this case your babel config should be written as JavaScript instead of JSON.

Will take a look into that now, thanks!
