### ISSUE TITLE
Add way to automatically use generated sourcemaps in node.js

### ISSUE THREAD

**Issue by cowboy** [babel/babel#1027]
I'm writing some node.js code in ES6/7 and compiling it (along with sourcemaps) with babel. Then I'm running the compiled code with nodejs. Unfortunately, there doesn't seem to be built-in support in node.js for sourcemaps, so all the line numbers are of the generated files, not my source files.

I've figure out that I can work around this by installing the [source-map-support](https://github.com/evanw/node-source-map-support) npm module and adding `require('source-map-support').install();` to the top of my source files, but this seems a bit unwieldy to me.

Is there any way to get babel to automatically add the `require('source-map-support').install();` line to the top of the generated files? This doesn't seem like the kind of code I should be adding to my source files manually.

Alternatively, is there a better way to actually use the sourcemaps babel generates to help me debug my node.js code?

Thanks!

**Comment by sebmck** [comment]
> Is there any way to get babel to automatically add the require('source-map-support').install(); line to the top of the generated files?

In the next major there's going to be a plugin API so I guess a plugin could do this although you just have to include it **once** at the top of your entry file. You don't need to include it in every one of your files.

> Alternatively, is there a better way to actually use the sourcemaps babel generates to help me debug my node.js code?

Not really, you've pretty much found it.
