### ISSUE TITLE
babel --watch does initial compile but ignores changes when --extensions is missing

### ISSUE THREAD

**Issue by russelldavis** [babel/babel#10270]
## Bug Report

1. Create a typscript file `foo.ts`
2. Run `babel foo.ts --out-file foo.js --watch --verbose`
3. Make a change to `foo.ts`

**Current Behavior**
Babel runs an initial compile, but does not react to any changes in the file.

**Expected behavior/code**
Babel should recompile the file when it changes.

If you add `--extensions ".ts"` to the command line, babel will properly recompile when the file changes. However, since an exact filename has been given on the command line, the `--extensions` option shouldn't be needed.

**.babelrc**

```json
{
    "presets": [
        "@babel/env",
        "@babel/typescript"
    ]
}
```

**Environment**
- Babel version(s): v7.5.5
- Node/npm version: Node 10.16.0 / npm 6.9.0
- OS: macOS Mojave 10.14.6
- Monorepo: no
- How you are using Babel: cli

**Comment by RyanEwen** [comment]
This doesn't seem to work for me either, even if I add `--extensions '.js'` :(

```
{
    "name": "business-system",
    "version": "1.0.0",
    "scripts": {
        "build": "babel . --out-dir babeljs --ignore 'node_modules','babeljs','3rdparty' --watch"
    },
    "devDependencies": {
        "@babel/cli": "^7.5.5",
        "@babel/core": "^7.5.5",
        "@babel/preset-env": "^7.5.5",
        "@babel/runtime": "^7.5.5"
    },
    "dependencies": {
        "@babel/polyfill": "^7.4.4"
    },
    "babel": {
        "sourceType": "script",
        "sourceMaps": true,
        "minified": true,
        "presets": [
            ["@babel/env", {"targets": "last 2 years, not dead"}]
        ]
    }
}
```

**Comment by RyanEwen** [comment]
Scratch that, it actually does work for me, but nothing appears in the log as files are updated.
