### ISSUE TITLE
Issue with babel dynamic import 

### ISSUE THREAD

**Issue by ramanangru** [babel/babel#10289]
I am using PdfVuer with vue/cli-service - ^3.0.0-beta.1, I am facing the below issue. But the same works fine with @vue/cli-service - ^3.8.0

Failed to compile with 1 errors                                                                                               15:14:21

 error  in ./node_modules/pdfvuer/src/Pdfvuer.vue?vue&type=script&lang=js&

Syntax Error: SyntaxError: /home/ramnank/Documents/Code Repo/marker-aug-code/admin-panel/node_modules/pdfvuer/src/Pdfvuer.vue: Support for the
 experimental syntax 'dynamicImport' isn't currently enabled (43:11):

  41 |          this.fetch = function(query) {
  42 | 
> 43 |                  return import('raw-loader!pdfjs-dist/cmaps/'+query.name+'.bcmap' /* webpackChunkName: "noprefetch-[request]" */)
     |                         ^
  44 |                  .then(function(bcmap) {
  45 | 
  46 |                          return {

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.

 @ ./node_modules/pdfvuer/src/Pdfvuer.vue?vue&type=script&lang=js& 1:0-259 1:275-278 1:280-536 1:280-536
 @ ./node_modules/pdfvuer/src/Pdfvuer.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/common/PdfViewer.vue?vue&type=script&lang=js&
 @ ./src/components/common/PdfViewer.vue?vue&type=script&lang=js&
 @ ./src/components/common/PdfViewer.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/pages/ProjectPortal/Dashboard.vue?vue&type=script&lang=js&
 @ ./src/components/pages/ProjectPortal/Dashboard.vue?vue&type=script&lang=js&
 @ ./src/components/pages/ProjectPortal/Dashboard.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?https://192.168.0.255:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by xtuc** [comment]
We discussed on Slack. Is your issue now resolved?

**Comment by ramanangru** [comment]
Fixed the issue by adding the 'babel-eslint' library in dev dependency
