### ISSUE TITLE
How to redefine class mechanism?

### ISSUE THREAD

**Issue by finom** [babel/babel#1028]
Hi there!
I use my own class implementation which adds some hacks to IE8 (allows to use Object.defineProperty). The syntax is:
```js
A = Class({
	'extends': B
});
```
My lib uses prototype-based heritage for IE9+ but IE8 uses other way. So I can't write the code using ES6 syntax. Can I totally redefine class mechanism so code above will be translated from:
```js
class A extends B {

}
```
(no need _prototypeProperties, _inherits and _classCallCheck)

Sorry for my English.

Thanks, 
Andrey

**Comment by sebmck** [comment]
Hey @finom! In a future version of Babel (out soon, ~next week or so) you'll be able to write your own transformers so you'll be able to do exactly this (see #987 for more info).

**Comment by finom** [comment]
Great news. I hope this feature going to be easy-to-use. Thanks.
