### ISSUE TITLE
Option to generate import for custom JSX pragma

### ISSUE THREAD

**Issue by kodekameleon** [babel/babel#10286]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When using a custom JSX pragma the pragma is not imported, resulting in missing references in the generated code.

**Describe the solution you'd like**
An option to generate something like import pragma from "pragma-file".

**Describe alternatives you've considered**
I am currently using rollup-plugin-inject to inject the import during packaging; and @wordpress/babel-plugin-import-jsx-pragma to inject the import during testing with mocha.

**Comment by xtuc** [comment]
With the default React JSX pragam you still need to import it yourself. I think that's expected.

**Comment by kodekameleon** [comment]
I understand that it is expected, but just adding

import {mypragma} from "mypragmafile"

resulted in rollup resolving conflicting globals and renaming the calls to the pragma so that they did not match up.

**Comment by nicolo-ribaudo** [comment]
That is unexpected. Can you provide an example?

**Comment by kodekameleon** [comment]
Yes, I will try to get a minimal example of the behaviour shortly.
