### ISSUE TITLE
There are redundant dependencies in  babel-preset-env

### ISSUE THREAD

**Issue by JackyTianer** [babel/babel#10285]
## Bug Report

**Current Behavior**
when i run grunt babel, it has error in my console. like this
![image](https://user-images.githubusercontent.com/3354804/62188979-732d5200-b3a0-11e9-8fe5-f847623f4a43.png)
so i run 
>  npm ls @babel/plugin-syntax-dynamic-import
![image](https://user-images.githubusercontent.com/3354804/62189019-90622080-b3a0-11e9-9ed6-af72fc631056.png)

**Expected behavior/code**
no waring and error

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
...
"devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "babel-preset-es2015": "^6.24.1",
    "grunt-babel": "^8.0.0",
    "grunt-concurrent": "^0.4.3",
    "grunt-contrib-cssmin": "2.2.1",
    "grunt-contrib-requirejs": "~0.4.1",
    "grunt-contrib-uglify": "~0.5.1",
    "grunt-cssjoin": "~0.2.0",
    "load-grunt-tasks": "~0.2.1",
    "standard": "^10.0.3"
  },
}
```

**Environment**
- Babel version(s): 7.5.5
- Node/npm version: Node 10/npm 6.9.0
- OS: 10.14.5 
- Monorepo: yes
- How you are using Babel: grunt-babel

**Possible Solution**
when i read babel-preset-env/package.json  file history, `@babel/plugin-syntax-dynamic-import` only in devDependencies, but in 7.5.5,  plugin `@babel/plugin-syntax-dynamic-import` is in `dependencies` and also in `devDependencies`

remove `/babel-preset-env/package.json` line:26,

**Comment by JLHwung** [comment]
```
"@babel/core": "^7.4.4",
"@babel/preset-env": "^7.4.4",
"babel-preset-es2015": "^6.24.1"
```
Please remove `babel-preset-es2015` as
1) it is supposed to work with Babel 6
2) @babel/preset-env will include necessary preset-es2015 transforms.

It seems that your `node_modules` is corrupted, could you remove it and reinstall?

**Comment by JackyTianer** [comment]
Thank you,It worked
