### ISSUE TITLE
With polyfill deprecated, how do we use core-js + regenerator-runtime with script-tags?

### ISSUE THREAD

**Issue by RyanEwen** [babel/babel#10281]
I am working with an older site that does not have any sort of build system in place and consists of many js files that will most certainly step on each other's feet if concatenated into a single bundle.

Eventually I figured out how to setup babeljs to find all my js files and transpile them. Then I found I needed the polyfills loaded into the browser. However I see that this is deprecated in favor of using core-js and regenerator-runtime directly. (https://babeljs.io/docs/en/babel-polyfill)

My question is, what is the proper way to do that, if they're going to be loaded in the browser as <script> tags?

**Comment by nicolo-ribaudo** [comment]
```html
<script src="https://unpkg.com/core-js-bundle@3.1.4/index.js"></script>
<script src="https://unpkg.com/regenerator-runtime@0.13.3/runtime.js"></script>
```
should work.

**Comment by RyanEwen** [comment]
Just for others who might come across this... my `package.json` ended up like so:

```
{
    "name": "business-system",
    "version": "1.0.0",
    "scripts": {
        "build": "npm rum delete-prev-build && npm run update-polyfill && npm run compile-javascript",
        "delete-prev-build": "rm -rf babeljs && mkdir babeljs",
        "update-polyfill": "cp node_modules/@babel/polyfill/dist/polyfill.min.js babeljs/polyfill.min.js",
        "compile-javascript": "babel . --out-dir babeljs --ignore 'node_modules','babeljs' --source-maps --watch"
    },
    "devDependencies": {
        "@babel/cli": "^7.5.5",
        "@babel/core": "^7.5.5",
        "@babel/preset-env": "^7.5.5",
        "@babel/runtime": "^7.5.5",
        "@babel/polyfill": "^7.4.4"
    },
    "babel": {
        "sourceType": "script",
        "minified": true,
        "presets": [
            [
                "@babel/env",
                {
                    "targets": "last 2 years, not dead"
                }
            ]
        ]
    }
}
```

To build and start watching for changes I run `npm run-script build` which in turn runs a few other scripts:
* `delete-prev-build` recreates the `babeljs` directory (where I serve the complied JS from).
* `update-polyfill` copies the polyfill JS file into my `babeljs` dir .
* `compile-javascript` calls babel to do just that, and keep watching for changes.

I include the polyfill into pages like so:
```
<script type="text/javascript" src="babeljs/polyfill.min.js"></script>
```

But since polyfill is being deprecated I'll eventually need to do something like the following instead: 
```
<script src="https://unpkg.com/core-js-bundle@3.1.4/index.js"></script>
<script src="https://unpkg.com/regenerator-runtime@0.13.3/runtime.js"></script>
```
