### ISSUE TITLE
babel + typescript + subclass generates incorrect code when interacting with properties during construction

### ISSUE THREAD

**Issue by RangerRick** [babel/babel#10282]
## Bug Report

**Current Behavior**
I have a class which has a private property, and then a subclass which has its own (unrelated) property. While constructing an object, subclass-overrideable code is called which sets a property value in the sub-class, but then the babel-generated `_defineProperty` is called _after_ and overwrites the initialized value with void.

**Input Code**
A gist with sample code and relevant `tsconfig.json` and `.babelrc` is available [here](https://gist.github.com/RangerRick/0d5de383f186d34abbff2ed8003d82cd).

**Expected behavior/code**
When I run `tsc` on this code and then execute it, it properly generates a randomized string:

```bash
$ tsc constructor-subclass-initialization.ts
$ node constructor-subclass-initialization.js
Basic 0.2414404310454120202
$ 
```

When I run it through `babel` instead, the subclass's internal property is undefined after construction:

```bash
$ babel constructor-subclass-initialization.ts > constructor-subclass-initialization.js
Dynamic import can only be supported when transforming ES modules to AMD, CommonJS or SystemJS. Only the parser plugin will be enabled.
$ node constructor-subclass-initialization.js
undefined
$ 
```

**Environment**
- Babel version(s): 7.5.5 (preset-typescript=7.3.3)
- Node/npm version: 10.16.0
- OS: OSX 10.14.6
- Monorepo: ?
- How you are using Babel: webpack, but reproduced in cli

**Comment by RangerRick** [comment]
Also FYI, I thought maybe this was a side-effect of `@babel/plugin-proposal-class-properties` but I tried defining `{ "loose": true }` on it to avoid `defineProperty` and this issue still occurs.

**Comment by jridgewell** [comment]
This is correct per the spec. `computedString` (with its default value of `undefined`) gets set _just before_ the `super()` call returns control to the subclass constructor. You've set the initial `computedString` (via the subclass' `onNewHash`) during the parent class' constructor.

**Comment by RangerRick** [comment]
Aha, thanks.  What's the expected way to perform this kind of workflow?  Suck it up and access the superclass's variable directly?

**Comment by RangerRick** [comment]
Also, does this mean I should open a bug to typescript that they potentially leak initialized properties in subclasses?

**Comment by jridgewell** [comment]
> Aha, thanks. What's the expected way to perform this kind of workflow? Suck it up and access the superclass's variable directly?

Remove the property from your subclass definition, or set it to its own value (`computedString = this.computedString`), or use [type declaration](https://github.com/microsoft/TypeScript/issues/12437#issuecomment-444010614) instead.

Having an undeclared property should be seen as taboo. See https://github.com/tc39/proposal-class-fields/issues/242

> Also, does this mean I should open a bug to typescript that they potentially leak initialized properties in subclasses?

Typescript is aware.

**Comment by RangerRick** [comment]
Great, thanks for your help.
