### ISSUE TITLE
React - Module parse failed: You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by Andu033** [babel/babel#10287]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
I get this error when i try to run webpack --progress --colors --mode=deploy --target=web

`ERROR in ./~/entities/maps/decode.json
Module parse failed: /home/andrei/owas/otherowa/node_modules/entities/maps/decode.json Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:4)
    at Parser.pp$4.raise (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/home/andrei/owas/otherowa/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/andrei/owas/otherowa/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/home/andrei/owas/otherowa/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/home/andrei/owas/otherowa/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/andrei/owas/otherowa/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/andrei/owas/otherowa/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/andrei/owas/otherowa/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/andrei/owas/otherowa/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./~/entities/lib/decode_codepoint.js 1:16-46`

**Input Code**
Here is my webpack.config.js
`'use strict';
const webpack = require('webpack');
const path = require('path');
const fs = require('fs');
const env = require('yargs').argv.mode;
const target = require('yargs').argv.target;
const targetPort = require('yargs').argv.targetPort;

const UglifyPlugin = webpack.optimize.UglifyJsPlugin;
const CommonsChunkPlugin =  webpack.optimize.CommonsChunkPlugin;
const DedupePlugin = webpack.optimize.DedupePlugin;

const HtmlWebpackPlugin = require('html-webpack-plugin');
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const WebpackOnBuildPlugin = require('on-build-webpack');

const nodeModulesDir = path.resolve(__dirname, '../node_modules');

const THIS_APP_ID = 'otherowa';

var plugins = [];
const nodeModules = {};

let outputFile = `.bundle`;
let vendorOutputFile;
let outputPath;

var configJson;
let appEntryPoint;
let localOwaFolder;

let devtool;

var getConfig = function () {
	  var config;

	  try {
	    // look for config file
	    config = require('./config.json');
	  } catch (err) {
	    // create file with defaults if not found
	    config = {
	      'LOCAL_OWA_FOLDER': '/home/andrei/openmrs/test/owa/',
	      'APP_ENTRY_POINT': 'http://localhost:8080/openmrs/owa/otherowa/index.html'
	    };

	    fs.writeFile('config.json', JSON.stringify(config));

	  } finally {
	    return config;
	  };
	}
var config = getConfig();

var resolveBrowserSyncTarget = function () {
  if (targetPort != null && targetPort != 'null') {
    return config.APP_ENTRY_POINT.substr(0, 'http://localhost:'.length)
      + targetPort
      + config.APP_ENTRY_POINT.substr('http://localhost:'.length + targetPort.toString().length, config.APP_ENTRY_POINT.length);
  }
  else {
    return config.APP_ENTRY_POINT
  }
};
var browserSyncTarget = resolveBrowserSyncTarget();

/** Minify for production */
if (env === 'production') {

	  plugins.push(new UglifyPlugin({
	    output: {
	      comments: false,
	    },
	    minimize: true,
	    sourceMap: false,
	    compress: {
	        warnings: false
	    }
	  }));
	  plugins.push(new DedupePlugin());
	  outputFile = `${outputFile}.min.[chunkhash].js`;
	  vendorOutputFile = "vendor.bundle.[chunkhash].js";
	  outputPath = `${__dirname}/dist/`;
	  plugins.push(new WebpackOnBuildPlugin(function(stats){
      //create zip file
      var archiver = require('archiver');
			var output = fs.createWriteStream(THIS_APP_ID+'.zip');
			var archive = archiver('zip');

			output.on('close', function () {
			    console.log('distributable has been zipped! size: '+archive.pointer());
			});

			archive.on('error', function(err){
			    throw err;
			});

			archive.pipe(output);

      archive.directory(`${outputPath}`, '');

			archive.finalize();
		 }))

} else if (env === 'deploy') {
	  outputFile = `${outputFile}.js`;
	  vendorOutputFile = "vendor.bundle.js";
	  outputPath = `${config.LOCAL_OWA_FOLDER}${config.LOCAL_OWA_FOLDER.slice(-1) != '/' ? '/' : ''}${THIS_APP_ID}`;
	  devtool = 'source-map';

} else if (env === 'dev') {
	  outputFile = `${outputFile}.js`;
	  vendorOutputFile = "vendor.bundle.js";
	  outputPath = `${__dirname}/dist/`;
	  devtool = 'source-map';
}

plugins.push(new BrowserSyncPlugin({
    proxy: {
    	target : browserSyncTarget
    }
}));

plugins.push(new CommonsChunkPlugin({
    name: 'vendor',
    filename: vendorOutputFile
}));

plugins.push(new HtmlWebpackPlugin({
    template: './app/index.html',
    inject: 'body'
}));

plugins.push(new CopyWebpackPlugin([{
    from: './app/manifest.webapp'
}]));

plugins.push(new CopyWebpackPlugin([{
    from: './app/img/omrs-button.png',
    to: 'img/omrs-button.png'
}]));

var webpackConfig = {
  quiet: false,
  entry: {
	  app : `${__dirname}/app/js/otherowa`,
	  css: `${__dirname}/app/css/otherowa.css`,
	  vendor : [
	        	
	        	
                
                    'react', 'react-router'
                    
                        , 'redux', 'redux-promise-middleware', 'redux-thunk', 'react-redux'
                    
                
	            ]
  },
  devtool: devtool,
  target,
  output: {
    path: outputPath,
    filename: '[name]'+outputFile,
  },
  module: {
    loaders: [{
	    test: /\.jsx?$/,
	    loader: 'babel-loader',
	    exclude: /node_modules/,
	    query: {
	        presets: [ 'es2015', 'react' ],
	        cacheDirectory : true
	    }
    },{
	    test: /\.css$/,
	    loader: 'style-loader!css-loader'
	}, {
	    test: /\.(png|jpg|jpeg|gif|svg)$/,
	    loader: 'url'
	}, {
	    test: /\.html$/,
	    loader: 'html'
	}],
  },
  resolve: {
    // root: path.resolve('./src'),
    extensions: ['', '.js', '.jsx'],
  },
  plugins,
  externals: nodeModules,
};

module.exports = webpackConfig;
`
**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**
My package.json:
`{
  "name": "otherowa",
  "version": "0.1.0",
  "description": "a",
  "repository": {
    "type": "git",
    "url": "https://github.com/andu033/openmrs-owa-otherowa"
  },
  "dependencies": {
    "@openmrs/react-components": "^1.0.0",
    "babel-polyfill": "^6.26.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "redux": "^3.6.0",
    "react-redux": "^5.0.1",
    "redux-promise-middleware": "^4.2.0",
    "redux-thunk": "^2.1.0",
    "react-router": "^3.0.0"
  },
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.16.0",
    "browser-sync": "^2.11.1",
    "browser-sync-webpack-plugin": "^1.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.23.1",
    "eslint": "^4.0.0",
    "enzyme": "^3.4.0",
    "enzyme-adapter-react-16": "^1.2.0",
    "enzyme-to-json": "^3.3.4",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.24.1",
    "jasmine-core": "^2.6.4",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-firefox-launcher": "^1.0.1",
    "karma-jasmine": "^1.1.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.4",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.13",
    "yargs": "^4.3.1",
    "archiver": "^1.0.0",
    "on-build-webpack": "^0.1.0"
  },
  "scripts": {
    "clean": "rimraf dist && rimraf coverage*",
    "build": "npm run clean && webpack --progress --colors --mode=production --target=web",
    "build:dev": "npm run clean && webpack --progress --colors --mode=dev --target=web",
    "build:prod": "npm run test && npm run build",
    "build:deploy": "webpack --progress --colors --mode=deploy --target=web",
    "watch": "webpack --progress --colors --watch --mode=deploy --target=web",
    "test": "karma start --singleRun=true",
    "test:debug": "karma start"
  },
  "keywords": [
    "OpenMRS",
    "Open",
    "Web",
    "App"
  ],
  "author": "andu033",
  "license": "MPL-2.0"
}`

**Environment**
- Babel version(s): 6.2.1
- npm version: 6.10.2
- OS: ubuntu 18
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
```
ERROR in ./~/entities/maps/decode.json
Module parse failed: /home/andrei/owas/otherowa/node_modules/entities/maps/decode.json
Unexpected token (1:4) You may need an appropriate loader to handle this file type.
```
The error comes from Webpack trying to parse a JSON file with acorn, which is irrelevant to Babel. As is said, you may need [json-loader](https://webpack.js.org/loaders/json-loader/) to handle JSON files.
