### ISSUE TITLE
@babel/plugin-proposal-dynamic-import depends on a modules transform plugin

### ISSUE THREAD

**Issue by samselikoff** [babel/babel#10280]
I'm trying to upgrade @babel/preset-env from 7.4.5 to 7.5.0, and encountering this error:

> @babel/plugin-proposal-dynamic-import depends on a modules transform plugin

This happens when running jest on a single test. My repo has babel-jest installed, and my project's babel.config.js is this:

```js
module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        targets: {
          node: "current"
        }
      }
    ]
  ]
};
```

I'm new to configuring jest and babel on my own, but I'm confused about why changing preset-env from 7.4.5 to 7.5.0 would necessitate any changes on my part. Am I missing something obvious?

Here's a screenshot of the full error:

![image](https://user-images.githubusercontent.com/2922250/62129168-0fbdfa00-b2a4-11e9-8e63-8cc85c7c8dd3.png)

**Comment by samselikoff** [comment]
This seems to have been fixed between when I posted this and now! I'm guessing an upstream dependency was patched.

**Comment by tranvansang** [comment]
I am facing the same issue. It looks like the bug now appears again

**Comment by RichardPK** [comment]
Experiencing this issue as well -> https://github.com/babel/babel/issues/10374#issuecomment-540538042

**Comment by ferdelamad** [comment]
Clearing `node_modules` worked for me:
```
rm -rf node_modules
```
