### ISSUE TITLE
Flagging: Improved backticks support coming to TypeScript

### ISSUE THREAD

**Issue by arcanis** [babel/babel#10298]
TypeScript 3.7 will likely improve its support for template strings that have no substitutions, and make them usable in much more places than it currently does (basically every time it would accept a regular literal string, in particular in enum declarations), so the Babel parser will need to be updated accordingly.

This will be very useful for TS codebases since they'll finally be able to enable the `backtick` version of the ESLint [`quote` rule](https://eslint.org/docs/rules/quotes).

Ref https://github.com/microsoft/TypeScript/pull/32064#issuecomment-517402758

**Comment by arcanis** [comment]
ping @nicolo-ribaudo (no action needed, I just want to make sure this issue isn't lost as it just got more relevant now that 3.7 is on its way 😃; kinda related to #10527)

**Comment by nicolo-ribaudo** [comment]
Thanks, I totally missed this!

**Comment by nicolo-ribaudo** [comment]
@arcanis I'm not sure about what should be implemented in Babel. From that PR, it looks like that it allows template literals in the _type checker_ where a generic expression is already allowed.
It doesn't expand TS's syntax, by enabling for example template literals in types.

**Comment by arcanis** [comment]
It's not only a typecheck thing - the change allows to use backtick literals without substitutions everywhere a regular string would be accepted in the type definitions. For example, the following is valid with TS 3.7 only:

https://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/KYOwrgtgBAYg9nKBvAsAKClAFsANrxAXigAMAzBEgGnQF8BuIA

vs TS 3.6:

https://www.typescriptlang.org/play/index.html#code/KYOwrgtgBAYg9nKBvAsAKClAFsANrxAXigAMAzBEgGnQF8BuIA

**Comment by thorn0** [comment]
I wouldn't call it "everywhere"... See https://www.typescriptlang.org/play/index.html?ts=3.7-Beta&ssl=3&ssc=1&pln=4&pc=1#code/C4TwDgpgBAHlC8UDeUCGAuKA7ArgWwCMIAnKAXwG4BYAKFEihAVgG0ADVNgXWpqA

**Comment by nicolo-ribaudo** [comment]
@arcanis I tested the following cases, and it seems that every template literal which is parsed by TS also works with Babel:
```
// ok

enum A { hello = `foo` };
type B = `foo`;
type C = { [`foo`]: number };

// error for both TS and Babel
import `foo`;

// error for TS but not for Babel
type D = C[`foo`];
fn<`foo`>();
```

I will update the enum transform.
