### ISSUE TITLE
Object destructuring getting transpiled for modern Chrome

### ISSUE THREAD

**Issue by sgomes** [babel/babel#10293]
## Bug Report

**Current Behavior**
Object destructuring is being transpiled for target browsers that natively support it, namely recent Chrome versions. Older Chrome versions work correctly.

**Input Code**
```js
const {foo, bar} = {foo: 3, bar: 4};
```

[REPL link for Chrome 74](https://babeljs.io/en/repl#?babili=false&browsers=chrome%20%3E%3D%2074&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBA3gMxCANDARgQwE4F8YC88SIAXDAMxpbbkAsuA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.5.5&externalPlugins=)

[REPL link for Chrome 60](https://babeljs.io/en/repl#?babili=false&browsers=chrome%20%3E%3D%2060&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBA3gMxCANDARgQwE4F8YC88SIAXDAMxpbbkAsuA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.5.5&externalPlugins=)

**Expected behavior/code**
In both cases, the code should remain untransformed or as close to it as possible, as the target browsers natively support object destructuring.

**Babel Configuration (.babelrc, package.json, cli command)**

Env plugin with browsers set to "chrome >= 74" or "chrome >= 60", as per the examples above.

**Environment**
The issue is observed in the REPL, running version 7.5.5.

For the sake of completeness, I'm also including my system's details below.
- Babel version(s): 7.5.5
- Node/npm version: v10.15.2 / 6.10.2
- OS: Mac OS 10.14.6
- Monorepo: lerna
- How you are using Babel: loader

**Additional context/Screenshots**
We noticed an increase in size in our `evergreen` build target, after updating to Babel 7.5.5 from Babel 7.4.0 (core) / 7.4.2 (env plugin). A diff analysis of the output before and after the change revealed that after the update, object destructuring was now being transpiled. This is unexpected, since our `evergreen` build target only targets recent versions. Here is the list of browsers for the `evergreen` target in our browserslist, for reference:

```
"last 2 Chrome versions",
"last 1 ChromeAndroid versions",
"last 2 Firefox versions",
"last 2 Safari versions",
"last 2 iOS versions",
"last 2 Edge versions",
"last 2 Opera versions",
"unreleased Chrome versions",
"unreleased ChromeAndroid versions",
"unreleased Firefox versions",
"unreleased FirefoxAndroid versions",
"unreleased Edge versions",
"unreleased Opera versions"
```

I reiterate that the issue is plainly visible in the REPL, though, with the much simpler test cases I listed above.

**Comment by JLHwung** [comment]
An out-of-dated `browserslist` may return empty array for query like `Chrome >= 74` as long as Chrome 74 is not included in `browserslist`. <small>(For those curious about why, `ignoreUnknownVersions` [throws](https://github.com/browserslist/browserslist#js-api) on direct query only)</small> If Chrome 74 exists but `browserslist` does not include it, apparently `browserslist` is out-of-dated.

Rule of thumb to check if you should `browserslist`:

Change `chrome >= 74` to `chrome 74` and `browserslist` will throw if it is not included.

**Comment by sgomes** [comment]
@JLHwung The versioned Chrome is simply a reduced test case to demonstrate the bug in the REPL. Our string is of the relative form ("last 2 Chrome versions"), which does not fall prey to the issue you suggested. I would demonstrate using the relative form in the REPL, but unfortunately it fails with the error `[BABEL] /repl: Could not find plugin "syntax-json-strings". Ensure there is an entry in ./available-plugins.js for it. (While processing: "base$0")`

Furthermore, your suggested explanation does not account for the fact that this worked correctly before the update to Babel 7.5.5, nor the fact that this is the only transformation that seems to be affected by the issue.

I'll prepare a different test case that doesn't rely on the REPL.

**Comment by sgomes** [comment]
I can't create a minimal test case for this based on a new project, which leads me to conclude that this is indeed related to `browserslist`, and there appears to be some coincidence in how our build and the REPL behave (perhaps the REPL is running an old browserslist too?)

Comprehensively updating `browserslist` across the multiple levels of our lerna monorepo appears to fix the issue, so I'll assume there's indeed no bug and you were right all along, @JLHwung. I still don't understand how a relative string ("last 2 Chrome versions") could generate this behaviour, but I'll classify it as "general weirdness that happens when you have multiple browserslist versions in your project".

Thank you for looking into this, @JLHwung, and I apologise if I took too much of your time 😞

**Comment by JLHwung** [comment]
I could not reproduce this issue from the browserslist configuration you mentioned above. When you update Babel from 7.4.0 to 7.5.5, the changes to node_modules does not only include the Babel source code, but also the dependencies structure -- some may be hoisted to top level but some might not. Therefore it is important to make sure you are using the same latest browserslist, across all the devtools depending on it.

> perhaps the REPL is running an old browserslist too

It is, and you paste `async () => await g` and `chrome >= 76`.
