### ISSUE TITLE
Unexpected "catch" behavior in an async function

### ISSUE THREAD

**Issue by vitalybe** [babel/babel#1029]
I am running the following code [here](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=function%20timeout(ms)%20%7B%0D%0A%20%20return%20new%20Promise((resolve)%20%3D%3E%20%7B%0D%0A%20%20%20%20setTimeout(resolve%2C%20ms)%3B%0D%0A%20%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20asyncValue(value)%20%7B%0D%0A%20%20await%20timeout(1000)%3B%0D%0A%20%20return%20value%3B%0D%0A%7D%0D%0A%0D%0A(async%20function()%20%7B%0D%0Atry%20%7B%0D%0A%20%20var%20value%20%3D%20await%20asyncValue(45)%3B%0D%0A%20%20if(42%20!%3D%3D%20value)%20%7B%0D%0A%20%20%20%20throw%20new%20Error(%22I%20expected%20a%20different%20stuff!%22)%3B%0D%0A%20%20%7D%20%0D%0A%20%20console.log(%22Done!%22)%3B%20%0D%0A%7D%20catch(err)%20%7B%0D%0A%20%20console.error(%22hmm%22)%3B%0D%0A%7D%0D%0A%7D)()%3B%20):

	function timeout(ms) {
	  return new Promise((resolve) => {
	    setTimeout(resolve, ms);
	  });
	}

	async function asyncValue(value) {
	  await timeout(1000);
	  return value;
	}

	(async function() {
	try {
	  var value = await asyncValue(45);
	  if(42 !== value) {
	    throw new Error("I expected a different stuff!");
	  } 
	  console.log("Done!"); 
	} catch(err) {
	  console.error("hmm");
	}
	})();

The resulting console output is wrong:

```Uncaught (in promise) TypeError: Illegal invocation {stack: (...), message: "Illegal invocation"}```

**Comment by neVERberleRfellerER** [comment]
Strange. Problem is caused by `console.error`. When replaced with `console.log`, it works fine. You can easily check by adding `console.log(e);` before `console.error("hmm")`.

Same problem arises with this code
```javascript
function timeout(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

timeout(5).then(function () {
  return Promise.reject(new Error("I expected different result!"));
}).catch(function (err) {
  console.error("hmm");
});
```
This happens only in REPL, tested with FF and Chrome. Console/separate page in Chrome and FF works correctly. It works correctly in babel-node.
This
```javascript
var _console = console;
timeout(5).then(function () {
  return Promise.reject(new Error("I expected different result!"));
}).catch(function (err) {
  _console.error("hmmm");
});
```
Does not work too, but it does not throw eny error in FF (it simply does not do anything).

**Comment by vitalybe** [comment]
You're right `console.log` works fine. 

>  Console/separate page in Chrome and FF works correctly. It works correctly in babel-node.

A minor issue then.

**Comment by neVERberleRfellerER** [comment]
Minor issue, indeed. But still a issue. Problem is definitely not in Babel. Maybe the polyfill is the issue, since this
```javascript
try {
  throw new Error("eaaa");
} catch (err) {
  console.error(err);
}
```
does not work in REPL, but it works in... well, everywhere else.

**Comment by thejameskyle** [comment]
There's a lot of [magic](https://github.com/babel/babel.github.io/blob/master/scripts/repl.js#L219-L272) that goes into getting the console to work for async operations in the REPL. `console.error` just needs to be added to [this list](https://github.com/babel/babel.github.io/blob/master/scripts/repl.js#L239-L241).
