### ISSUE TITLE
preset-env not transform all shorthand properties

### ISSUE THREAD

**Issue by q2177329q** [babel/babel#10305]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
in out file, there are still 2 es2015 shorthand properties.that makes js fail in ios8.
**Input Code**
- REPL or Repo link if applicable:

```js
var t = {};
    function n(i) {
        if (t[i])
            return t[i].exports;
        var r = t[i] = {
            i,
            l: !1,
            exports: {}
        };
        return e[i].call(r.exports, r, r.exports, n), r.l = !0, r.exports
    }
    n.m = e, n.c = t, n.d = function(e, t, i) {
        n.o(e, t) || Object.defineProperty(e, t, {
            enumerable: !0,
            get: i
        })
    }, n.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }), Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }
```

**Expected behavior/code**
var t = {};
    function n(i) {
        if (t[i])
            return t[i].exports;
        var r = t[i] = {
            i: i,
            l: !1,
            exports: {}
        };
        return e[i].call(r.exports, r, r.exports, n), r.l = !0, r.exports
    }
    n.m = e, n.c = t, n.d = function(e, t, i) {
        n.o(e, t) || Object.defineProperty(e, t, {
            enumerable: !0,
            get: i
        })
    }, n.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }), Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
            test: /\.js$/,
            use: {
                loader: 'babel-loader',
                options: {
                    "plugins": [
                        "@babel/plugin-transform-runtime",
                        ["babel-plugin-kmui", { "libraryName": "@kaola/kmui" }],
                    ],
                    presets: [['@babel/preset-env', {
                        "targets": [
                            "> 0.25% in CN",
                            "last 2 versions",
                            "ios >= 6",
                            "android >= 4",
                            "not dead",
                        ],
                        modules: 'commonjs',
                        debug: true
                    }]]
                }
            },

            include: [
                function(path){
                    return path.indexOf('@kaola') >= 0;
                },
                path.join(DIRS.BASE, 'src'),
            ],
            exclude: /(jweixin|nej\-h5|messenger|qr)/,
        },
```

**Environment**
- Babel version(s): @babel/core v7.0.0
- Node/npm version: node 10.16.0/npm 6.9.0
- OS: OSX 10.14.6 
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/9465058/62626128-3f7e9900-b959-11e9-9e84-e990432a794b.png)
![image](https://user-images.githubusercontent.com/9465058/62626151-4f967880-b959-11e9-9ccf-0f1291eb32b2.png)

**Comment by JLHwung** [comment]
The error in your minified code comes from webpack main template used for bootstraping the module systems. 
https://github.com/webpack/webpack/blob/725f9d283d25a9ff567c23bc9c515cbc52a8bc0e/lib/MainTemplate.js#L188-L191
Before the code was minified it should look like:
```js
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

But apparently there is no shorthand properties inside the code snippet. So I guess it comes from the JavaScript minimizer. Please check your UglifyJSPlugin or TerserPlugin configuration. If you are using TerserPlugin, set `ecma` options to 5 so that it would _not_ try to emit shorthand properties.

```js
module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          ecma: 5
        },
      }),
    ],
  },
};
```

**Comment by q2177329q** [comment]
> ```js
> optimization
> ```
i was set

```
terserOptions: {
    output: {
        ecma: 8
    }
},
```

change to ecma: 5 works.
```
terserOptions: {
    output: {
        ecma: 5
    }
},
```
