### ISSUE TITLE
t.tsTypeParameter should take 3 parameters but throws

### ISSUE THREAD

**Issue by deificx** [babel/babel#10317]
## Bug Report

**Current Behavior**
calling [t.tsTypeParameter](https://babeljs.io/docs/en/babel-types.html#tstypeparameter) with the name parameter yields `Error: TSTypeParameter: Too many arguments passed. Received 3 but can receive no more than 2`

**Input Code**
```js
const generate = require("@babel/generator").default;
const t = require("@babel/types");

const ast = t.tsTypeParameter(
  t.tsTypeReference(t.identifier("bar")),
  t.tsTypeReference(t.identifier("baz")),
  "foo"
);

const { code } = generate(ast);
console.log(code);
```

**Expected behavior/code**
should output `foo extends bar = baz`

**Babel Configuration (.babelrc, package.json, cli command)**
N/A

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: Node v10.12.0 / yarn 1.17.3
- OS: Ubuntu 18.04

**Possible Solution**
Add `name` to [visitor](https://github.com/babel/babel/blob/master/packages/babel-types/src/definitions/typescript.js#L497)

**Comment by JLHwung** [comment]
> Add name to visitor

Agree, could you open a PR?
