### ISSUE TITLE
Fault-tolerant @bable/parser parsing

### ISSUE THREAD

**Issue by m4nuC** [babel/babel#10316]
Fault-tolerant flag option for parsing

**Is your feature request related to a problem? Please describe.**
acorn-loose is a thing, and esprima can be passed a tolerant flag with a value of true. For my usecase, it would be beneficial to reproduce this with babel parser.

**Describe the solution you'd like**
A flag option to be passed to the parser API

**Comment by JLHwung** [comment]
#10363 is related to this request.
