### ISSUE TITLE
Flow comments plugin removes generic type arguments of the right hand side of the `extends` keyword

### ISSUE THREAD

**Issue by zaygraveyard** [babel/babel#10321]
## Bug Report

**Current Behavior**
`@babel/plugin-transform-flow-comments` removes generic type arguments of the right hand side of the `extends` keyword

```js
class A extends B {}
```

**Input Code**
[REPL link](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjAQgHgA0A-aAbwF8AoIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=babel-plugin-syntax-jsx%406.18.0%2C%40babel%2Fplugin-transform-flow-comments%407.5.5)

```js
class A extends B<X> {}
```

**Expected behavior/code**

```js
class A extends B /*:: <X>*/ {}
```

**Environment**
- Babel version(s): v7.5.5
- How you are using Babel: Online REPL

**Possible Solution**
```js

  return {
    //...
    visitor: {
      //...
      ClassDeclaration(path) {
        if (path.parentPath.isFlow()) {
          return;
        }

        const { node } = path;
        if (node.superTypeParameters) {
          const superTypeParameters = path.get("superTypeParameters");
          const superClass = path.get("superClass");
          superClass.addComment("trailing", generateComment(superTypeParameters, node));
          superTypeParameters.remove();
        }
      },
      //...
    },
  };
```

**Comment by JLHwung** [comment]
PR is welcome.

**Comment by zaygraveyard** [comment]
I'm working on a PR
