### ISSUE TITLE
addNamed of @babel/helper-module-imports always generate alias

### ISSUE THREAD

**Issue by nianiaJR** [babel/babel#10328]
## Bug Report

**Additional context/Screenshots**
As the doc says:  https://babeljs.io/docs/en/next/babel-helper-module-imports.html
![image](https://user-images.githubusercontent.com/8124783/62933643-41cb7200-bdf5-11e9-80b0-0598b7fe9839.png)

But when I use addNamed like this, the it always output like this:
```
import { named as _named } from "source"
```
I don't know why I can't remove the alias. could you help me? thanks

**Comment by nicolo-ribaudo** [comment]
It's probably because we must always use `scope.generateUid` when injecting a new variable (to avoid possible conflicts), and it sees the `named` identifier as already used.
Out of curiosity, why do you need exactly `{ named }` and not `{ named as _named }`? I'd consider this just a bug in that exmaple in the documentation.

**Comment by nianiaJR** [comment]
@nicolo-ribaudo Yes, I just also find the `name = this._scope.generateUidIdentifier(name);` in the source code. As for your question,  it's that I am writting a babel plugin to translate code which uses my own lib:
```
// brefore
import { Button } from 'dwn-ui'
// after
import { Button } from 'dwn-ui/lib/Button'
```
This plugin can help to cut down the project code package. So if the translated code is ` { named } ` only，I won't do the rest code `named` indentifier translation. The `_named` alias don't exist in my original code.
Sorry about  my poor English, can you get my idea ? Thanks for your fast reply😁.

**Comment by nicolo-ribaudo** [comment]
In your case, wouldn't be enough to replace the import source, without replacing the whole import declaration?

**Comment by nianiaJR** [comment]
@nicolo-ribaudo I get your idea. And "replacing the source" is  proper for  just one module import like this:
```javascript
// before
import { Button } from 'dwn-ui' 
// after
import { Button } from 'dwn-ui/lib/Button'
```
But it may not work like that:
```javascript
// before
import { Button, Modal } from 'dwn-ui'
// which needed
import { Button } from 'dwn-ui/lib/Button'
import { Modal } from 'dwen-ui/lib/Modal'
```
Is that right? thanks

**Comment by nicolo-ribaudo** [comment]
Then I suggest directly building your imports, which is also way more performant: 
https://astexplorer.net/#/gist/10743870fdf24f273010e6a7633ab78b/latest

**Comment by nianiaJR** [comment]
Wow, I couldn't find the `path.replaceWithMultiple` before. It's so helpful. Thanks for your patience!
