### ISSUE TITLE
Can @babel/plugin-transform-runtime support include/exclude option like @babel/preset-env?

### ISSUE THREAD

**Issue by grtan** [babel/babel#10320]
## Feature Request

I find that setTimeout and Date.now are converted when i use babel transform runtime, but i do not want to converted them.

I want to @babel/plugin-transform-runtime can support include/exclude option like @babel/preset-env in the future.

**Comment by nicolo-ribaudo** [comment]
This is now supported by the new polyfill packages, at https://github.com/babel/babel-polyfills.
