### ISSUE TITLE
Named exports aren't being live bound

### ISSUE THREAD

**Issue by Alxandr** [babel/babel#1032]
If you transpile the following code to cjs

```javascript
export var bar = 42;
bar = 10;
```

you get

```javascript
var bar = 42;
exports.bar = bar;
bar = exports.bar = 10;
```

and it works as one would expect.

However, if I change the code to

```javascript
var bar = 42;
export {bar};
bar = 10;
```

I instead get the following:

```javascript
var bar = 42;
exports.bar = bar;

bar = 10;
```

The problem here is that `bar` is exported as `42`, instead of `10`.

Oh, and another case which is more or less the same, but would probably make a great test case is the following:

```javascript
// Before
var bar = 42;
export {bar as default};
bar = 10;

// After
var bar = 42;
exports["default"] = bar;
bar = exports["default"] = 10;
```

**Comment by sebmck** [comment]
Fixed via 25312396a581e74595d4c2782c6ce29861e350a2.
