### ISSUE TITLE
Babel 7 transform issues (arrow functions)

### ISSUE THREAD

**Issue by Ninos** [babel/babel#10322]
# v7 Regression

**Describe the regression**
Functions like ` const ExampleFunction = (() => {` are not transformed to IE11-friendly code.

**Input Code**
```js
const ExampleFunction = (() => {
// CODE
}
```

**Babel Configuration (.babelrc, package.json, cli command)**
I'm using webpack-encore
```js
.configureBabel(function (babelConfig) {
    // add additional presets
    babelConfig.presets.push('@babel/preset-flow');

    // no plugins are added by default, but you can add some
    babelConfig.plugins.push('@babel/plugin-proposal-class-properties');
    babelConfig.plugins.push('@babel/plugin-proposal-function-bind');
    babelConfig.plugins.push('@babel/plugin-proposal-object-rest-spread');
    babelConfig.plugins.push('@babel/plugin-transform-arrow-functions');
    babelConfig.plugins.push('@babel/plugin-transform-block-scoping');
    babelConfig.plugins.push('@babel/plugin-transform-function-name');
    babelConfig.plugins.push('@babel/plugin-transform-modules-commonjs');
    babelConfig.plugins.push('@babel/plugin-transform-object-assign');
    babelConfig.plugins.push('@babel/plugin-transform-typeof-symbol');
})
```

**Expected behavior/code**
Should transform arrow functions for supporting e.g. IE11.

**Environment**
- Babel version(s): [e.g. v7]
- OS: all
- How you are using Babel: webpack-encore (symfony)

**Comment by JLHwung** [comment]
> Functions like const ExampleFunction = (() => { are not transformed to IE11-friendly code.

The term "IE11-friendly" is a bit vague here. Could you attach the runtime error log of the transformed code? As is seen on [Babel REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYewdgzgLgBAogDwIYFsAOAbApgMQK5jBQCW4MAvDABRUCUFAfDAN4BQA9OzAMIDyAInFYwYAMxAgKMAEQAjJACdpAblYBfWkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-arrow-functions%407.2.0), the arrow function gets transformed correctly.

**Comment by Ninos** [comment]
I mean the arrow function does get transformed anyway, it stays
```js
const ExampleFunction = (() => {
// CODE
}
```

**Comment by FThompson** [comment]
While I haven't verified the issue myself, the syntax in question is an arrow function IIFE:

```javascript
const ExampleModule = (() => {
    // ...
})();
```

@Ninos Originally reported this issue in my repository, where I fixed the issue for him by changing the IIFE to use `const ExampleModule = (function() { ... })()` syntax. See that issue [here](https://github.com/FThompson/FormPersistence.js/issues/8).

**Comment by nicolo-ribaudo** [comment]
By default `webpack-encore` doesn't transpile dependencies: https://github.com/symfony/webpack-encore/blob/5640271a87e63048b8ae261d210922b4972cab69/index.js#L858

**Comment by Ninos** [comment]
Ahh thx, after adding
```js
, {
        exclude: '/vendor/'
    }
```
it's working fine +1
