### ISSUE TITLE
Flow comments change order of comments at beginning of file

### ISSUE THREAD

**Issue by zaygraveyard** [babel/babel#10324]
## Bug Report

**Current Behavior**
`@babel/plugin-transform-flow-comments` change order of comments at beginning of file when the file starts with a comment followed by a flow statement

```js
/*:: import type {A} from 'a';*/

/**/
X;
```

**Input Code**
[REPL link](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=PQKhwKASwWwBwPYCcAuACFBPOBTNBvAQQF80AzJBGNAcgEMaBuCADSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-flow-comments%407.5.5)

```js
/**/
import type {A} from 'a';
X
```

**Expected behavior/code**

```js
/**/
/*:: import type {A} from 'a';*/
X;
```

**Environment**
- Babel version(s): v7.5.5
- How you are using Babel: Online REPL

**Possible Solution**
```js
  //...
  function attachComment(path, comment) {
    let attach = path.getPrevSibling();
    let where = "trailing";
    if (!attach.node) {
      attach = path.getNextSibling();
      where = "leading";
    }
    if (!attach.node) {
      attach = path.parentPath;
      where = "inner";
    }
    attach.addComment(where, comment);
    path.remove();
  }
  //...
```

**Comment by JLHwung** [comment]
Could you open up a PR? Besides import declaration, any other flow-only statement, i.e. `type A = number;` will also result to incorrect behaviour if it has no `prevSibling`.

**Comment by zaygraveyard** [comment]
@JLHwung I know, I just happened to have the `import` case
But I'm working on a PR for any flow-only statement
