### ISSUE TITLE
Flow comments plugin moves the generic type arguments of the left hand side of the `extends` keyword to its right side

### ISSUE THREAD

**Issue by zaygraveyard** [babel/babel#10323]
## Bug Report

**Current Behavior**
`@babel/plugin-transform-flow-comments` moves the generic type arguments of the left hand side of the `extends` keyword to its right side

```js
class A extends B /*:: <X>*/ {}
```

**Input Code**
[REPL link](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAECCA8ANAfNApgDwC5oHYBMYAhaAbwF8AoIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-flow-comments%407.5.5)

```js
class A<X> extends B {}
```

**Expected behavior/code**

```js
class A /*:: <X>*/ extends B {}
```

**Environment**
- Babel version(s): v7.5.5
- How you are using Babel: Online REPL

**Possible Solution**
```js

  return {
    //...
    visitor: {
      //...
      ClassDeclaration(path) {
        if (path.parentPath.isFlow()) {
          return;
        }

        const { node } = path;
        if (node.typeParameters) {
          const typeParameters = path.get("typeParameters");
          const id = path.get("id");
          id.addComment("trailing", generateComment(typeParameters, node));
          typeParameters.remove();
        }
      },
      //...
    },
  };
```

**Comment by JLHwung** [comment]
Could you open a PR? I think it suffices to add trailing comments to `id` here
https://github.com/babel/babel/blob/ee397ff1074184a78fc78bc599cc2e4af66e61c8/packages/babel-plugin-transform-flow-comments/src/index.js#L204-L205

Note that we also need check `superTypeAnnotation` and extract it to comments. The following snippet is not working currently:
```js
class Foo extends Bar<X> {}
```

**Comment by zaygraveyard** [comment]
I'm working on a PR
