### ISSUE TITLE
Convert exported TypeScript types to undefined

### ISSUE THREAD

**Issue by remcohaszing** [babel/babel#10337]
## Bug Report

**Current Behavior**

When the code below is compiled using webpack and `babel-loader`, this triggers the following warning:

```
WARNING in ./src/Bar/index.tsx 1:0-42
"export 'BarProps' was not found in './Bar'
 @ ./src/index.tsx
```

The original issue is here: babel/babel-loader#769

However, I believe it can be fixed upstream (in `@babel/plugin-transform-typescript`).

**Input Code**

`src/Bar/Bar.tsx`

```tsx
export interface BarProps {
  value: string;
}

export default function Bar(props?: BarProps) {}
```

`src/Bar/index.tsx`

```tsx
export { default, BarProps } from './Bar'
```

`src/index.tsx` (Webpack entry point)

```tsx
import Bar from './Bar';

console.log(Bar())
```

**Expected behavior/code**

There are no warnings

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  plugins: ['@babel/plugin-transform-typescript']
}
```

**Environment**
- Babel version(s): 7.5.5
- Node/npm version: Node 10/npm 6
- OS: Ubuntu 18.04
- Monorepo: no
- How you are using Babel: `loader`

**Possible Solution**

Convert exported types and interfaces to undefined constants. This way, Webpack will find the constants and stop complaining and their types are still undefined when using `typeof` checks. A minifier should strip the constant, as it is unused in the final bundle.

I believe this should be an opt in solution on the Babel part. I.e. an option `typeToConst: true` for both `@babel/plugin-transform-typescript` and `@babel/preset-typescript`

**Additional context/Screenshots**

This webpack config can be used to verify behaviour.

```js
module.exports = {
  devtool: 'source-map',
  resolve: {
    extensions: ['.tsx'],
  },
  module: {
    rules: [
      { 
        test: /\.tsx?$/, 
        use: 'babel-loader'
      }
    ]
  }
};
```

**Comment by JLHwung** [comment]
Thank you for the report. We are working on the TypeScript interface exports at #10220, and it should fix this issue.

**Comment by realduolaf** [comment]
#10220 How's it going?

**Comment by JLHwung** [comment]
@realduolaf #10220 fixes flow type export. It does not address this issue.

**Comment by realduolaf** [comment]
@realduolaf OK. Thank you.

**Comment by realduolaf** [comment]
@JLHwung OK~ Thank you.

**Comment by jackmellis** [comment]
Is there any more news on this issue? This actually breaks builds using rollup and I’m struggling to find a workaround that doesn’t involve abandoning the Babel plugin

**Comment by nicolo-ribaudo** [comment]
In the next minor release, you'll be able to explicitly mark type-only exports using
```js
export type { foo };
```
