### ISSUE TITLE
This experimental syntax requires enabling the parser plugin: 'objectRestSpread'

### ISSUE THREAD

**Issue by scrossan-crown** [babel/babel#10345]
## Bug Report

**Current Behavior**
I'm getting the below error and I've been trying for hours to solve it with different plugins and options but haven't gotten anywhere.
`/app/node_modules/comlink/dist/esm/comlink.mjs:64:12: This experimental syntax requires enabling the parser plugin: 'objectRestSpread' (64:12)`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function(api) {
    api.cache(true);

    const presets = [
        
        [
            "@babel/preset-env", 
            {
                "targets": {
                    "browsers": ["last 1 Chrome version"]
                },
                "shippedProposals": true
            }
        ],
        "@babel/preset-react"
    ];

    const plugins =  [
        [
            "@babel/plugin-transform-runtime",
            {
                "regenerator": true
            },
        ],
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-transform-spread",
        "@babel/plugin-syntax-object-rest-spread"
    ];

    const parserOpts = {
        "plugins": ["objectRestSpread"] 
    };

    return {
        presets,
        plugins,
        parserOpts
    };
};
```

**Environment**
- Babel version(s): 7.5.5
- Node/npm version: Node 10
- OS: Debian GNU/Linux 8 (jessie)
- Monorepo: No
- How you are using Babel: Via [Parceljs](https://parceljs.org)

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/30405149/63152721-69445980-c004-11e9-8817-7671bdf30a11.png)

**Comment by nicolo-ribaudo** [comment]
It is because Parcel doesn't support JavaScript configs: https://github.com/parcel-bundler/parcel/issues/2110

**Comment by scrossan-crown** [comment]
@nicolo-ribaudo Thanks. I've converted it to a `.babelrc` and still get the same error

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 1 Chrome version"
          ]
        },
        "shippedProposals": true
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      },
    ],
    "@babel/plugin-syntax-object-rest-spread"
  ]
}
```

**Comment by nicolo-ribaudo** [comment]
That's because Babel only uses `babel.config.js`, which is the recommended config, to transpile dependencies. `.babelrc` is local to your own package.

Since Parcel doesn't support `babel.config.js`, it does some magic to allow you to config Babel for your dependencies, but it only works sometimes: https://github.com/parcel-bundler/parcel/issues/2304

Anyway, plase ensure that Babel is updated: the `objectRestSpread` parser option (and `@babel/plugin-syntax-object-rest-spread`) aren't needed since v7.1.5, which is 8 months old: https://github.com/babel/babel/commit/24c4901ff56c57db1ac60e4d810424656d18e374

**Comment by scrossan-crown** [comment]
@nicolo-ribaudo I thought it was on longer needed. I've but a snippet  of my package.json below.

```json
 "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/plugin-syntax-object-rest-spread": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/plugin-transform-spread": "^7.2.2",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
```

**Comment by nicolo-ribaudo** [comment]
Try running `npx nls why @babel/parser`

**Comment by scrossan-crown** [comment]
@nicolo-ribaudo  I ran `npx nls why @babel/parser` and the output is in this gist https://gist.github.com/scrossan-crown/b262e8ce808114eb4b9f76e71cba594f

**Comment by nicolo-ribaudo** [comment]
Ok, as you can see some packages are using an older version.

Try running `npm update @babel/parser --depth=9999` or `yarn upgrade @babel/parser`
