### ISSUE TITLE
@babel/register doesn't work when script is not called from root of project

### ISSUE THREAD

**Issue by Hotell** [babel/babel#10349]
## Bug Report

**Current Behavior**

- We have a monorepo with yarn workspaces.
- It contains a `libs/` and `apps/` folders , where `libs/` constains various node helpers for build/scripting/etc..., and `apps/` contains various apps/libraries to be published.
- these modules are written in typescript, but the final API export is handled via `register` and `index.js`, like following
- because it's registered as workspace, it's hoisted and available within root `node_modules/@my-org/build-tools`

```js
// ./libs/build-tools/src/index.js
require('@babel/register')({
  presets: [
    [
      'env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
    '@babel/preset-typescript',
  ],
  extensions: ['.jsx', '.js', '.ts', '.tsx'],
  cache: false,
});

module.exports = require('./module');
```

```ts
// ./libs/build-tools/src/module.ts
export * from './tools';

// ./libs/build-tools/src/tools/hello.ts
export function hello() {
  return 'Hello world';
}
```

_package.json of build-tools lib_

```json
{
  "private": true,
  "name": "@my-org/build-tools",
  "version": "1.0.0",
  "main": "src/index.js"
}
```

Now let's say I have a node script within some package folder within `./apps/pkg-one`

```js
// ./apps/pkg-one/build.js
const { hello } = require('@my-org');

console.log(hello);
```

**🚨 So here comes the issue**

When I execute this script from root of the project, everything works

```sh
node ./apps/pkg-one/build.js

# ✅WORKS! -> OUTPUT:
# 'Hello world'
```

But if my `cwd` is within particular project ( which is very common when executing scripts via lerna or `cd ... && yarn run ....` ), it behaves like there is no `@babel/register` at work at all

```sh
cd ./apps/pkg-one

node build.js

# 🚨🚨🚨ERROR
./libs/build-tools/src/module.ts:1
export * from './tools'
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

it should work

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    [
      'env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
    '@babel/preset-typescript',
  ],
  extensions: ['.jsx', '.js', '.ts', '.tsx'],
  cache: false
}
```

**Environment**

- Babel version(s): [7.4.4]
- Node/npm version: [Node 10/yarn 1.17]
- OS: [e.g. OSX Mojave]
- Monorepo: [e.g. yes - workspaces]
- How you are using Babel: [`register`]

**Comment by Hotell** [comment]
so passing `{cwd: __dirname}` fixed the issue ( thanks typescript for that "hidden" config ). I can add it to `registry` docs if you want. WDYT?

thanks!

**Comment by nicolo-ribaudo** [comment]
It's already the first options in the docs: https://babeljs.io/docs/en/options :sweat_smile: Do you have any suggestion about how we could make it clearer?
