### ISSUE TITLE
Class methods are non enumerable when they should be enumerable.

### ISSUE THREAD

**Issue by steelsojka** [babel/babel#1034]
Upgraded from 6to5 to babel and class methods were now non enumerable. Researched and found this issue in esnext. Is this issue valid?

https://github.com/esnext/es6-class/issues/13

**Comment by sebmck** [comment]
Yep, as of February 2, 2015 Draft Rev 32 class methods are non-enumerable.

> Methods defined within class definitions are now non-enumerable

**Comment by steelsojka** [comment]
Cool! Was not aware of that. Thank you for the quick response!

**Comment by dcrockwell** [comment]
Is there any way to get a list of properties from class otherwise?

**Comment by jquense** [comment]
Object.getOwnPropertyNames(Class.prototype) will work like Object.keys but with non enumerate properties

**Comment by dcrockwell** [comment]
@jquense Fantastic! Thank you very much for the prompt response.
