### ISSUE TITLE
export `getParserClass` out of @babel/parser

### ISSUE THREAD

**Issue by hsiaosiyuan0** [babel/babel#10351]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'd like to add some custom syntax through `@babel/parser`, now for this requirement I have to make a fork of `@babel/parser` then add the custom syntax plugins in that fork, the option `parserOverride`  does not work in this case since I want my custom parser to support all the`@babel/parser` options.

**Describe the solution you'd like**

Maybe it's not good but if we export this method [getParserClass](https://github.com/babel/babel/blob/master/packages/babel-parser/src/index.js#L68) out of `@babel/parser` then I can use this method to get the inherited class which applies the plugin options and let my custom parser class to inherit it.

**Comment by JLHwung** [comment]
> the option parserOverride does not work in this case since I want my custom parser to support all the@babel/parser options.

Could you elaborate on the your use case? If your custom parser is forked from `@babel/parser`, it should support all the options that `@babel/parser` has supported out-of-the-box, shouldn't it?

**Comment by loganfsmyth** [comment]
Maintainability of the parser is really the core issue here. By exposing something like this, we'd be exposing a bunch of internal state and therefore need to treat that as part of our public API. For instance, we've seriously discussed removing the class hierarchy entirely.

**Comment by hsiaosiyuan0** [comment]
@JLHwung @loganfsmyth 
Sorry for my description. I agree with that we need to keep the core is stable and the maintainability is one of the factors of stableness. 

I'd like to use `@babel/parser` as an individual dependency, and I expect there is a convenient way(except fork) to supply a plugin like 'jsx' does to add custom syntax. 

Looking for your suggestions, thank you.

**Comment by loganfsmyth** [comment]
> I'd like to use @babel/parser as an individual dependency, and I expect there is a convenient way(except fork) to supply a plugin like 'jsx' does to add custom syntax.

That is not currently a feature we think we'd be able to support in a stable/maintainable way. Keeping your own fork of the parser is the only option at the moment.

**Comment by hsiaosiyuan0** [comment]
I think fork is the last resort, since I always have to keep my fork is up to date.

I'll close this issue, thank you for your help.
