### ISSUE TITLE
Sourcemaps not quite working with babel/register

### ISSUE THREAD

**Issue by cowboy** [babel/babel#1035]
I'm assuming that sourcemaps are supposed to be working with `require('babel/register')` because when I take this `test.js` file:

```js
var {a, b} = {a: 1, b: 2};
console.log(a, b);
x
```

And run `node -e "require('babel/register'); require('./test');"` with babel 4.7.12, I see line **3** (the source line of the ReferenceError) instead of **8** (the compiled line of the ReferenceError) in the first line of the stack trace:

```
1 2

/Users/cowboy/repos/cowboy/test/test.js:8
x;
^
ReferenceError: x is not defined
    at Object.<anonymous> (/Users/cowboy/repos/cowboy/test/test.js:3:1)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/cowboy/repos/cowboy/test/node_modules/babel/lib/babel/api/register/node.js:119:5)
    at Object.require.extensions.(anonymous function) [as .js]
    (/Users/cowboy/repos/cowboy/test/node_modules/babel/lib/babel/api/register/node.js:132:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:28
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

Unfortunately, line **3** isn't mentioned in the initial error line (at the top, before the `x;` bit). Is that an error?

Also, if sourcemaps are indeed supposed to be supported, the paths could be better formatted. For example, if I compile `test.js` with `node_modules/.bin/babel --source-maps-inline test.js > test-compiled.js` I get this file (with the ReferenceError on line 8):

```js
"use strict";

var _ref = { a: 1, b: 2 };
var a = _ref.a;
var b = _ref.b;

console.log(a, b);
x;

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7V0FBWSxFQUFDLENBQUMsRUFBQyxDQUFDLEVBQUMsQ0FBQyxFQUFDLENBQUMsRUFBQztJQUFoQixDQUFDLFFBQUQsQ0FBQztJQUFDLENBQUMsUUFBRCxDQUFDOztBQUNSLE9BQU8sQ0FBQyxHQUFHLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDO0FBQ2xCLENBQUMsQ0FBQSIsImZpbGUiOiJzdGRvdXQiLCJzb3VyY2VzQ29udGVudCI6WyJ2YXIge2EsYn0gPSB7YToxLGI6Mn07XG5jb25zb2xlLmxvZyhhLCBiKTtcbnhcbiJdfQ==
```

And then run it with `node -e "require('source-map-support').install(); require('./test-compiled');"` I see this output with short paths and a reference to line 3 in both places. Although I still do see the reference to line 8 as well.

```
1 2

/Users/cowboy/repos/cowboy/js-es6-es7-workflow-ideas/test-compiled.js:8
x;
^

test.js:3
x
^
ReferenceError: x is not defined
    at Object.<anonymous> (test.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:42
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
```

If sourcemaps are supposed to be working with `babel/register`, could they be a little more consistent and nicely formatted?

Thanks!

**Comment by cowboy** [comment]
FYI, the extraneous reference to line 8 in the second version only happens when I do `node -e "require('source-map-support').install(); require('./test-compiled');"`. If I add `require('source-map-support').install();` into the source, compile it, and then just do `node ./test-compiled`, the extra message doesn't appear.

**Comment by sebmck** [comment]
> Unfortunately, line 3 isn't mentioned in the initial error line (at the top, before the x; bit). Is that an error?

You're right that in the following the line is incorrect:

```
/Users/cowboy/repos/cowboy/test/test.js:8
x;
^
```

However the following number is correct:

```
ReferenceError: x is not defined
    at Object.<anonymous> (/Users/cowboy/repos/cowboy/test/test.js:3:1)
```

This is due to #899 as otherwise it requires overriding `uncaughtException ` which interferes with a lot of libraries.

Basically the top code frame that Node inserts is incorrect as `babel/register` sets the `handleUncaughtExceptions` `source-map-support` option to `false`.

**Comment by cowboy** [comment]
Is there any way to set the `handleUncaughtExceptions source-map-support` option to `true`?

I'm thinking of using `require('babel/register')` only when developing, and using a built version in production.

**Comment by sebmck** [comment]
Nope, see the discussion in #899.

> Can't really do an option since the require injection stuff is done on require so it can be used like `$ mocha --require babel/register` and you can't override any of the `source-map-support` settings after initialisation.
