### ISSUE TITLE
Can't we dynamiclly load assets according to the browser it run,not the browserlistrc cofiguration

### ISSUE THREAD

**Issue by macarole** [babel/babel#10354]
sorrry, i just have a suggestion suddenly,and i'think it will be more resonable if it come to true one day.
now  we often pack our program due to the .browerslistrc we set. i think maybe  we can do more further here.we pack our program at the pack period and load the same assets in whatever browser you use. does it have some posibilities to load asssets due to the browser you use?

i think it's very interesting ,but i have no ability to complete it  ,may somebody help it out,thank you!

**Comment by nicolo-ribaudo** [comment]
This isn't something that would be directly integrated with Babel: a nodejs server should get the request for the js file, parse the user agent and pass the correct browser to preset-env.

**Comment by macarole** [comment]
> This isn't something that would be directly integrated with Babel: a nodejs server should get the request for the js file, parse the user agent and pass the correct browser to preset-env.

actually,i intended to issue under the @babel/preset-env (aim at the useBuiltIns option),but i  can't get that repository correctly,so i come here ....thank you

**Comment by nicolo-ribaudo** [comment]
`@babel/preset-env` is in this repository, but it doesn't know about servers, http responses and user agents. It doesn't give the same compiled file to every browser: it doesn't even know what "giving a file to a browser" mean :stuck_out_tongue: 

It should be done by another tool, which should parse the useragent and pass it to `@babel/preset-env`. For example, using express, it would be something like this:
```js
var express = require('express');
var useragent = require('express-useragent');

var app = express();
app.use(useragent.express());

app.get('/main.js', function(req, res){
    if (cached(req.useragent)) return from cache;

    var code = babel.transformSync(readFile("main.js"), {
      presets: [
        ["@babel/preset-env", { browsers: [`${req.useragent.browser} ${req.useragent.version}`] }]
      ]
    });

    cache code;
    res.send(code);
});
app.listen(3000);
```

**Comment by macarole** [comment]
> `@babel/preset-env` is in this repository, but it doesn't know about servers, http responses and user agents. It doesn't give the same compiled file to every browser: it doesn't even know what "giving a file to a browser" mean 😛
> 
> It should be done by another tool, which should parse the useragent and pass it to `@babel/preset-env`. For example, using express, it would be something like this:
> 
> ```js
> var express = require('express');
> var useragent = require('express-useragent');
> 
> var app = express();
> app.use(useragent.express());
> 
> app.get('/main.js', function(req, res){
>     if (cached(req.useragent)) return from cache;
> 
>     var code = babel.transformSync(readFile("main.js"), {
>       presets: [
>         ["@babel/preset-env", { browsers: [`${req.useragent.browser} ${req.useragent.version}`] }]
>       ]
>     });
> 
>     cache code;
>     res.send(code);
> });
> app.listen(3000);
> ```
> 
> ⚠️ Keep in mind that any old browser can be configured to provide a "fake" useragent representing a new browser.

i don't know how to reply.....i've been thinking your words , seemingly it is not babel's responsibility, probably i may think it from another view ,thank you for your advice
