### ISSUE TITLE
AMD equivalent of commonStrict

### ISSUE THREAD

**Issue by matthewp** [babel/babel#1036]
Shouldn't there be one?  Since Babel compiles to the commonjs amd wrapper style it's inconsistent that es modules set module.exports rather than exports.default. Could there be an `amdStrict` perhaps?

**Comment by stefanpenner** [comment]
we have been disabling babel's modules, and using esperantojs for this functionality.

**Comment by sebmck** [comment]
There is?

```javascript
export default foo();
```

```sh
$ babel --modules amdStrict
```

```javascript
define(["exports"], function (exports) {
  "use strict";

  export["default"] = foo();
})
```

**Comment by matthewp** [comment]
Woops, did not know about this!  Thanks! Is it documented.
