### ISSUE TITLE
import "regenerator-runtime/runtime" not working

### ISSUE THREAD

**Issue by Ma63d** [babel/babel#10364]
## Bug Report

**Current Behavior**
I write `import "regenerator-runtime/runtime";` but regenerator was not bundled into dist file by webpack. And the browser report this error:

regeneratorRuntime is not defined when running in a browser.

```
regeneratorRuntime.mark(function _callee() {
^

ReferenceError: regeneratorRuntime is not defined
```

**Input Code**
```js
// regenerator-runtime will not be bundled by webpack, if I write this:
import "regenerator-runtime/runtime";

// but if I use it like this ,it works:
import regenerator from "regenerator-runtime/runtime";
console.log('regenerator>>>', regenerator);
```

**Expected behavior/code**
`regenerator` should be bundled and the browser not report any error.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// webpack config:
use: [
          {
            loader: "babel-loader",
            options: {
              babelrc: false,
              presets: [
                [
                  "@babel/preset-env",
                  // https://github.com/babel/babel/blob/master/packages/babel-preset-env/data/plugins.json#L32
                  {
                    targets: { browsers: ["chrome >= 70"] },
                    useBuiltIns: "entry",
                    corejs: "3"
                  }
                ],
                "@babel/preset-typescript",
                "@babel/preset-react"
              ],
              plugins: [
                ["@babel/plugin-proposal-decorators", { legacy: true }],
                ["@babel/plugin-proposal-class-properties", { loose: true }],
                "@babel/plugin-syntax-dynamic-import"
              ]
            }
          }
        ]
```

**Environment**
- Babel version(s): 
```
"@babel/preset-env": "^7.4.5",
"@babel/preset-react": "^7.0.0",
"@babel/preset-typescript": "^7.3.3",
"@babel/plugin-proposal-class-properties": "^7.4.4",
"@babel/plugin-proposal-decorators": "^7.4.4",
"@babel/plugin-syntax-dynamic-import": "^7.2.0",
"webpack": "^4.34.0",
```
- Node/npm version: Node 12.6 
- OS: OSX 10.14.5 
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**
No idea. Have been reading about more than 20 issues about `regenerator ` but still not find solutions.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
This seems like a webpack problem, since it assumes that `regenerator-runtime/regenerator` can be removed.

**Comment by Ma63d** [comment]
> This seems like a webpack problem, since it assumes that `regenerator-runtime/regenerator` can be removed.
> 
> Maybe https://stackoverflow.com/a/52854503/2359289 works for you.

It works. Thanks. (btw, it's still a bit tricky)
