### ISSUE TITLE
Casting in an object with 'as' fails with parsing error unexpected token

### ISSUE THREAD

**Issue by devlinb** [babel/babel#10365]
## Bug Report

**Current Behavior**
Casting in a plain object using "as" when assigning a field fails.  

**Input Code**
- REPL or Repo link if applicable:

```ts
const inputStyle = {
 textStyle: 'center' as const, 
}
```
[Babel repl](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAlmADgVygZSgTwDYFMYC8MA3gFAxS4Ae6WeAXDAOTC5iUBOTMAhhDKEhQANDFIBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.5.5&externalPlugins=)

[Typescript repl](http://www.typescriptlang.org/play/#code/MYewdgzgLgBARiOMC8MDeAoGUCmAPKAZSgE8AbHALhgHJgcxcAnGmAQwhlEigBoYMAXyA)

**Expected behavior/code**
Behavior of TS plugin does same thing as TSC

**Babel Configuration (.babelrc, package.json, cli command)**

# babel.config.js
```js
module.exports = function(api) {
  api.cache(true);
  return {
    presets: [["module:metro-react-native-babel-preset"], ['react-app'],  ["@babel/preset-typescript"]],
    ignore: [ "node_modules/art/core/color.js" ],
    plugins: [
      ["module-resolver", {
        "alias": {
          "^react-native$": "react-native-web"
        }
      }],
      "@babel/plugin-proposal-class-properties"
    ],
  };
};
```

# Relevant parts of package.json

```
"devDependencies": {
  "@babel/core": "7.1.0",
  "@babel/plugin-transform-typescript": "^7.5.5",
  "@babel/preset-typescript": "^7.3.3",
  "babel-eslint": "9.0.0",
  "babel-jest": "23.6.0",
  "babel-loader": "8.0.4",
  "babel-plugin-module-resolver": "^3.1.1",
  "babel-plugin-named-asset-import": "^0.2.3",
  "babel-preset-react-app": "^6.1.0",
}
```

**Environment**
- Babel version(s): 7.1.0
- Node/npm version: node v10.15.3 NPM 6.4.1
- OS: [Win10]
- Monorepo: No
- How you are using Babel: Loader

**Comment by nicolo-ribaudo** [comment]
The TS preset in the repl doesn't work. If you enable the plugin, you will see that it works:
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAlmADgVygZSgTwDYFMYC8MA3gFAxS4Ae6WeAXDAOTC5iUBOTMAhhDKEhQANDFIBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.5.5

Note that the TS presets only enables itself in typescript files. What it the extension of the file where you are getting this bug?
