### ISSUE TITLE
Helper for object spread erroneously injected when targeting node

### ISSUE THREAD

**Issue by DullReferenceException** [babel/babel#10375]
## Bug Report

**Current Behavior**
Object spread syntax is causing helper functions to be injected, despite targeting a node version that natively supports it.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MDeAoGMCGAuGARgBosYAjAgJgwF8MNRJZycAnFdMgOl4RFLZgBAMx0A3BiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=Node-8&version=7.5.5&externalPlugins=

```js
const foo = {
  a: 1,
  b: 2
}

const bar = {
  ...foo,
  c: 3
};
```

**Expected behavior/code**

The expected behavior is that the native object spread is preserved instead of being replaced with a helper function call.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "8" } }]
  ]
}
```

**Environment**
- Babel version(s): v7.5.5
- Node/npm version: Node 10.15.3/npm 6.11.2
- OS: macOS 10.14.6
- Monorepo: no
- How you are using Babel: `cli`

**Additional context/Screenshots**

The output is generating an `_objectSpread` helper function and other helper functions to support that, when it doesn't have to change anything whatsoever.

**Comment by JLHwung** [comment]
Object Spread is officially [supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) in Node.js since 8.3 (previous versions behind a `--harmony` flags).

When one specifies `node 8` as targets, env preset assumes that the target is equivalent to `node >= 8.0.0`. If you don't need node.js 8.0 - 8.2 support, please specifies
```
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "8.3" } }]
  ]
}
```

**Comment by DullReferenceException** [comment]
Brilliant! Sorry for my mistake. Confirmed it works great.
