### ISSUE TITLE
Bug with default values in nested destructuring declaration

### ISSUE THREAD

**Issue by timukasr** [babel/babel#1037]
When declaring new variables with nested destructuring using default values, the result contains undestructured expression. Similar case for assignment works fine:
```
let z = {};

let {x: {y} = {}} = z; // not ok, produces var { y: y } = ...

({x: {y} = {}}) = z; // OK
```
[Link to Babel REPL](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=let%20z%20%3D%20%7B%7D%3B%0A%0Alet%20%7Bx%3A%20%7By%7D%20%3D%20%7B%7D%7D%20%3D%20z%3B%20%2F%2F%20not%20ok%0A%0A(%7Bx%3A%20%7By%7D%20%3D%20%7B%7D%7D)%20%3D%20z%3B%20%2F%2F%20OK)

**Comment by sebmck** [comment]
Fixed as of 4.7.13, thanks!
