### ISSUE TITLE
Granular loading of core-js

### ISSUE THREAD

**Issue by guybedford** [babel/babel#1039]
I'm just integrating the use of the runtime transformer with jspm, which is working really nicely.

The unfortunate part though is that small code bundles end up getting coupled with the whole of core-js.

It would be nice if the transformer just loaded the individual pieces of core-js necessary. Perhaps the runtime package could have a folder that just re-exports each of these granular entry points to core-js instead of using a single file build.

I know core-js isn't that large so it may not be such a big issue, but could be nice.

**Comment by AluisioASG** [comment]
Maybe you could use a custom build of core-js?  I should check if that actually works, and if it does, maybe add it to the FAQ, @sebmck?

**Comment by sebmck** [comment]
@AluisioASG Nah, that's not very practical.

@guybedford This is basically the goal of the runtime transformer (see babel/ember-cli-babel#24 for more info). It's impossible to do without core-js being modular which is what @zloirock is currently working on :smile:

**Comment by zloirock** [comment]
Now I have a problem with free time, but I'll try to finish commonjs api in the near future. I play with different variants of entry points, but all of them have any problems. Need to choose the most convenient and painless.

**Comment by sebmck** [comment]
All good @zloirock, no rush. Thanks for your awesome work!

**Comment by guybedford** [comment]
Ok great, glad to hear that is the plan! Sure yes no pressure at all, very happy with the way things are working right now.
