### ISSUE TITLE
[types] Not compiling because of JSDoc TS8020

### ISSUE THREAD

**Issue by AnandChowdhary** [babel/babel#10408]
## Bug Report

**Current Behavior**
The most recent recent publish of `@babel/types` is not compiling with TypeScript. The error is `TS8020`, JSDoc types can only be used inside documentation comments.

**Input Code**
- https://github.com/o15y/staart/pulls

```
node_modules/@babel/types/lib/index.d.ts:2098:30 - error TS8020: JSDoc types can only be used inside documentation comments.
2098 export function isNode(node: ?object): boolean
                                  ~~~~~~~
node_modules/@babel/types/lib/index.d.ts:2100:52 - error TS8020: JSDoc types can only be used inside documentation comments.
2100 export function isPlaceholderType(placeholderType: ?string, targetType: string): boolean
                                                        ~~~~~~~
node_modules/@babel/types/lib/index.d.ts:2104:34 - error TS8020: JSDoc types can only be used inside documentation comments.
2104 export function isType(nodetype: ?string, targetType: string): boolean
                                      ~~~~~~~
Found 3 errors.
```

**Comment by nicolo-ribaudo** [comment]
This has been fixed in `@babel/types` 7.6.1

**Comment by AnandChowdhary** [comment]
Awesome! Can we also patch update and publish all dependents of `@babel/types`, like `@babel/core` and `@babel/preset-env`? 😄

**Comment by AnandChowdhary** [comment]
Though #10403 is fixed already, perhaps we can keep this issue open until all packages using `@babel/types` are updated as well?

**Comment by nicolo-ribaudo** [comment]
It isn't needed, since they don't peen their dependencies. `yarn upgrade @babel/types` (or the equivalent npm command) should be enough.

**Comment by JLHwung** [comment]
Close as it duplicates #10403
