### ISSUE TITLE
regenerator blacklisted?

### ISSUE THREAD

**Issue by ronag** [babel/babel#1040]
When I try to use generators I get errors and I've noticed that for some reason 'regenerator' is blacklisted even though I have not blacklisted it anywhere? What's going on?

**Comment by sebmck** [comment]
Are you using the whitelist?

**Comment by ronag** [comment]
```
  require('babel/register')({
    optional: ['regenerator', 'asyncToGenerator']
  });
```

**Comment by AluisioASG** [comment]
You don't need that config, actually.  And it's self-contradictory.

**Comment by sebmck** [comment]
Enablign the optional `asyncToGenerator` transformer will disable `regenerator` since you're specifically asking for output with generators.

**Comment by ronag** [comment]
How do I get async to work then?

**Comment by sebmck** [comment]
Remove the `optional` option.

```javascript
require('babel/register');
```

**Comment by ronag** [comment]
Then async doesn't work...

**Comment by sebmck** [comment]
What isn't working, are you getting an error? Going to need some more information to narrow down what the actual issue is.

**Comment by sebmck** [comment]
What code are you trying etc

**Comment by sebmck** [comment]
Enable [experimental mode](http://babeljs.io/docs/usage/experimental).

```javascript
require('babel/register')({
  experimental: true
});
```

**Comment by sebmck** [comment]
Also as per the [README](https://github.com/babel/babel#readme)

> For questions and support please visit the [gitter room](http://gitter.im/babel/babel) before creating an issue.

Thanks!
