### ISSUE TITLE
[parser] Fake directive with "tail" can still trigger strict mode

### ISSUE THREAD

**Issue by pvdz** [babel/babel#10412]
## Bug Report

Super edge case: A property access, call, or tagged template on a `"use strict"` string that would otherwise be a directive should not be considered as such. Babel seems to do this anyways.

**Current Behavior**

A "directive" is a string that appears at the first series of statements of a script or function that are exclusively strings (ignoring whitespace, comments, and semi colons / ASI).

So when the parser sees a property access, call, or tagged template, it should no longer be tempted to consider the string a directive. Such strings can not trigger strict mode. It seems Babel is not resilient against this.

**Input Code**

https://astexplorer.net/#/gist/15eb31fbb1024faa6f42a4940d8beb4a/aa32936fd03f63e1e8084610fe5ded643823694b

```js
function f(){
  "use strict".foo;
  eval = 1;
}

function f(){
  "use strict"[foo];
  eval = 1;
}

function f(){
  "use strict"`foo`; // Only works syntactically, but same bug
  eval = 1;
}

function f(){
  "use strict"(foo); // Only works syntactically, but same bug
  eval = 1;
}
```

Note: changing the string contents will allow the example to pass, proving it's caused by the string.
Note: this seems to work correctly in script top level. Just not in a function.

**Expected behavior/code**

This should pass.

**Environment**

Babel 7.8.4

**Possible Solution**

Add more checks when parsing directives :)

**Additional context/Screenshots**

Very much an edge case. Low priority.

**Comment by CrCliff** [comment]
I'm looking to start contributing to Babel, would this be a good issue to take up?

**Comment by JLHwung** [comment]
@CrCliff Sure. This issue is related to babel-parser and it could be daunting if you have never worked with a recursive descent parser implementation. But trust me, it worths all the efforts to figure out what's going wrong and try to fix it eventually. Please go through the [CONTRIBUTING](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) first and get a development babel build.

**Comment by pvdz** [comment]
Conceptually, something is not asserting that the string is actually followed by a semi-colon or ASI before determining it to be a directive. 

How you should actually solve this in the parser really depends on the parser architecture. I can't tell you much about that on Babel.

**Comment by pvdz** [comment]
It seems this is no longer the case.

**Comment by JLHwung** [comment]
@pvdz 🤔I don't think this issue has been fixed yet?

**Comment by pvdz** [comment]
In that case Tenko is broken. The test cases that I had made an exception for that were marked with this issue are now in sync with how Tenko does it. So either I regressed, or "you" improved :)

**Comment by pvdz** [comment]
Oh you're right. Thanks. I see Tenko did not regress, maybe I changed the test runner to only run in strict mode when comparing.

**Comment by pvdz** [comment]
Yeah I switched up my testing runs a bit, adding module+annexb, which messed the comparison up.

Anyways, the same problem applies to treating the directive as a tagged template. It's the same problem but might require a different fix, depending on the implementation. Want me to file a separate ticket for that or shall I update the desc?

```js
function f() {
  "\5";
  "use strict"
  ` \8 `
} 
```

(This should pass in non-strict script mode with annexb rules because the last bit is a tagged template so strict mode never comes into play. And tagged templates are allowed to have illegal octal escapes, but that's just a red herring. I'm getting "Babel threw an error (and Tenko did not): Octal literal in strict mode (2:4)")

**Comment by pvdz** [comment]
Yeah, same for any tail really. I'll update the desc.

**Comment by kaicataldo** [comment]
Working on this!
