### ISSUE TITLE
[parser] `let` in catch clause is not an error in sloppy

### ISSUE THREAD

**Issue by pvdz** [babel/babel#10413]
## Bug Report

The `let` identifier should be valid in a catch clause in sloppy (non-strict) mode but this appears to be invalid.

**Current Behavior**

The `let` identifier is special in strict mode but not a keyword in non-strict mode. In this case Babel still throws over it where I think it should not.

**Input Code**

https://astexplorer.net/#/gist/15eb31fbb1024faa6f42a4940d8beb4a/50b40e18038bb65c40bc3257e886093a206ad411

```js
try {} catch (let) {}
```

**Expected behavior/code**

Should pass.

**Environment**

Babel 7.5.5

**Possible Solution**

Update heuristics to detect this :)

**Additional context/Screenshots**

I hope I'm not missing some weird exception in the spec but as far as I can see there is none and this should pass.

**Comment by bre30kra69cs** [comment]
Think i can fix it!

**Comment by nicolo-ribaudo** [comment]
If you need any help, feel free to ask in our slack channel! (In `#development`)

**Comment by gonzarodriguezt** [comment]
Hey, i think this actually isn't a bug, as [this PR](https://github.com/babel/babel/pull/10099) disallow `let` as name in lexical bindings (let and const style binding) per the spec detailed there, and the `catch` block has indeed that style of binding, but i do think that the error should be more general, the error thrown now is:

```
'let' is not allowed to be used as a name in 'let' or 'const' declarations. (1:14)
```

Maybe it should say something related with the scope type within the name is trying to be used.

**Comment by nicolo-ribaudo** [comment]
It was an oversight in that PR: the specification only limits `let` in `let` and `const` declarations.
