### ISSUE TITLE
[parser] `arguments` and `eval` as object shorthand should be valid in strict mode

### ISSUE THREAD

**Issue by pvdz** [babel/babel#10411]
## Bug Report

The object key shorthand syntax is checking the ident for being a keyword and triggers an error. This is not correct for `eval` and `arguments`, which are only read (which is legal).

**Current Behavior**

It will throw a syntax error `Unexpected keyword 'eval' (1:2)`

**Input Code**

https://astexplorer.net/#/gist/15eb31fbb1024faa6f42a4940d8beb4a/06e20b27a9291d5356faa340e430c0ded986ccb8

It will properly apply sloppy/strict mode exceptions (script vs module goal). So `eval` won't throw with script goal.

```js
({arguments})
```
```js
({eval})
```

Not sure if same bug, but definitely related is the next one, where the `eval` identifier is a regular object key, not a assignment destructuring pattern (because it assigns to `.x` of the object literal). Let me know if this is the same cause, otherwise I'll file a separate issue for this.

```
({...{eval}.x} = {});
```

**Expected behavior/code**

It should not throw an error because it's a regular object key and a read from `eval` / `arguments`, which is allowed.

**Environment**

Babel 7.5.5

**Possible Solution**

Add exception path for `eval` and `arguments` when doing the keyword check.

**Comment by nicolo-ribaudo** [comment]
`({break})` is a syntax error because it's the same as `({break: break})`

**Comment by pvdz** [comment]
Oh wow, thanks for that. I completely missed that detail.

Looking explicitly at it now, https://tc39.es/ecma262/#prod-PropertyDefinition uses https://tc39.es/ecma262/#prod-IdentifierReference for a shorthand. This leads to https://tc39.es/ecma262/#prod-Identifier which forbids "keywords". So you're absolutely correct; this is a syntax error.

**Comment by pvdz** [comment]
I will update the issue accordingly. I believe the bug here is that this would not apply to contextual value keywords like `eval` and `arguments`, which can be read in strict mode, just not written to. And this is just a read.
