### ISSUE TITLE
let/const scoping is broken

### ISSUE THREAD

**Issue by markokr** [babel/babel#1042]
let/const does not coordinate vars in different blocks, only with upper blocks:
```js
function foo(x)
{
    //var a,b; // uncomment and then all vars get unique names
    if (x) {
        let a;
        const b=2;
    } else {
        let a;
        const b=1;
    }
}
```

babel v4.7.12

**Comment by fkling** [comment]
Since only one of the blocks can be executed, what's the problem? Babel only renames variables if it has to (afaik).

**Comment by markokr** [comment]
problem is that there are 2 var declarations for same variable.  i'd like the generated code be jshint-clean

**Comment by eventualbuddha** [comment]
@markokr why not use babel-eslint *before* the transpilation? Is there a benefit to running jshint after?

**Comment by markokr** [comment]
jshint (with esnext) does not support all syntax handled by babel (jsx).  i actual;ly i have not played with eslint, but seems it has same situation.

also i think making result jshint-clean would help finding any conversation bugs easier.  why are you against it?

**Comment by fkling** [comment]
Linting tools help developers catch errors or style issues in their code early. There isn't really a point in linting generated code. The correctness of the generated code is verified by tests.

> jshint (with esnext) does not support all syntax handled by babel (jsx). i actual;ly i have not played with eslint, but seems it has same situation.

That's what **babel**-eslint solves.

**Comment by eventualbuddha** [comment]
Closing this as I think @fkling has explained the issue well, and using babel-eslint is the correct solution.
