### ISSUE TITLE
Labels with `let` and `const` variable declarations seem to no longer work

### ISSUE THREAD

**Issue by leoasis** [babel/babel#10424]
# v7 Regression

**Describe the regression**
Looking at http://astexplorer.net it seems that specifying a label for a variable declaration statement is treated as invalid code in Babel 7, but it is valid in Babel 6. Looking at MDN it doesn't look like this should be treated as invalid code.

**Input Code**
```
foo: let bar = 123;
```
shows this error message: 
```
/repl: Unexpected reserved word 'let' (1:5)

> 1 | foo: let bar = 123;
    |      ^
```

And this:
```
foo: const bar = 123;
```
shows this error message:
```
/repl: Lexical declaration cannot appear in a single-statement context (1:5)

> 1 | foo: const bar = 123;
    |      ^
```
**Babel Configuration (.babelrc, package.json, cli command)**
Using the default settings in astexplorer.net, with the babylon 7 parser.
In the babel repl, only set the `es2015` preset.

**Expected behavior/code**
Babel should treat these as valid code, I think.

**Environment**
- The babel repl site
- Also choosing babylon 7 in http://astexplorer.net

**Comment by nicolo-ribaudo** [comment]
It is a syntax error: you can try running `foo: let bar = 123;` in your browser's console.

If you are interested in why, a `LabelledStatement` can only contain what the spec defines as `Statement`:
https://tc39.es/ecma262/#sec-labelled-statements

A `Statement` is one of the following: (https://tc39.es/ecma262/#prod-Statement)
```
BlockStatement
VariableStatement
EmptyStatement
ExpressionStatement
IfStatement
BreakableStatement
ContinueStatement
BreakStatement
ReturnStatement
WithStatement
LabelledStatement
ThrowStatement
TryStatement
DebuggerStatement
```

Here you see `VariableStatement`, which only allows `var` and not `let`/`const`: https://tc39.es/ecma262/#prod-VariableStatement

**Comment by leoasis** [comment]
Oh my bad, sorry for filing this invalid ticket, and thanks for the thorough answer.
