### ISSUE TITLE
[parser] Tagged template with \8 should set value to null

### ISSUE THREAD

**Issue by pvdz** [babel/babel#10437]
## Bug Report

**Current Behavior**

Minor AST issue; The `\8` and `\9` are illegal escapes. In tagged template these should be recognized as bad escapes and set the `.value` property in the AST to `null` to reflect this.

**Input Code**

```js
`\8`
```

```js
`\9`
```

**Expected behavior/code**

For templates, an escape `\8` and `\9` end up as `NotEscapeSequence`
https://tc39.es/ecma262/#prod-NotEscapeSequence

The string value of that escape is undefined:
https://tc39.es/ecma262/#sec-static-semantics-tv-and-trv
> The TV of TemplateCharacter :: `\` NotEscapeSequence is `undefined`.

As such, the `.value` property in the AST nodes should be `null` to reflect this, like with other bad escapes.

**Environment**
Babel 7.5.5

**Possible Solution**

I think there's an exception to 8 and 9. Do the same as happens with `\1` ~ `\7`. This is for _tagged_ templates only.

**Comment by nicolo-ribaudo** [comment]
Note that it should set to `null` `value.cooked`, not `value` itself.

**Comment by nicolo-ribaudo** [comment]
Is this a Chrome bug?
```js
console.log`\1`
> [undefined, raw: Array(1)]

console.log`\8`
> ["8", raw: Array(1)]

"use strict"; console.log`\1`
> [undefined, raw: Array(1)]

"use strict"; console.log`\8`
> ["8", raw: Array(1)]
```

**Comment by pvdz** [comment]
In sloppy web compat, `'\8'` would be the character '8' where `\7` would be character `\u0007`. In strict both should be an error.
In a template literal any octal escape should always be an error, `\8` and `\9` are included as forbidden in the grammar.
In a tagged template it's considered a bad escape but not a syntax error.

One thing to note is that template behaviour of both kinds (for octals) are not susceptible to the strict mode state.

I had to disable reports for octals while fuzzing because node/v8 is allowing legacy octals to have a dot property and exponent, which is not allowed by the grammar, so I'm not sure how far those bugs go.

**Comment by ye7ia** [comment]
I'm looking into this.

**Comment by pnowak** [comment]
Hi @ye7ia. Are you working on it?
If not, can I take over?
