### ISSUE TITLE
[parser] Multi line group location ending

### ISSUE THREAD

**Issue by pvdz** [babel/babel#10436]
## Bug Report

**Current Behavior**

I think the location end is incorrect for multiline groups. If the group starts with the first non-whitespace after the parenthesis, then the end should be after the last non-whitespace but before the parenthesis. Right now it seems to be after the character before the closing paren. 

**Input Code**

```js
a = (
  b,
  c
)
```
Delta:
```
>    Babel AST is different:
>
>    -          loc:{start:{line:2,column:2},end:{line:3,column:3}},
>    +          loc:{start:{line:2,column:2},end:{line:4,column:0}},
>
```

```
class C extends (
  a,
  c
) {
}
```
Delta:
```
>    Babel AST is different:
>
>    -        loc:{start:{line:2,column:2},end:{line:3,column:3}},
>    +        loc:{start:{line:2,column:2},end:{line:4,column:0}},
```

**Environment**

Babel 7.5.5

**Possible Solution**

Update location tracking to ignore the trailing whitespace when creating the location for the group. 

Alternatively update the start to span the actual parenthesised area (in that case probably before and after the parens, rather than inside).

**Comment by pvdz** [comment]
(Still an issue as of 7.8.4)

**Comment by nicolo-ribaudo** [comment]
This also affects single-line expressions:
```
a = (  b, c  )
```

`SequenceExpression`'s start is at right before `b`, while its end is right before `)` (instead of right after `c`).
