### ISSUE TITLE
native builtins do not spread: new Map(...args), new Set(...args), new Promise(...args), etc

### ISSUE THREAD

**Issue by timoxley** [babel/babel#1043]
Spread operator does not work when run with native promises in Chrome:

```js
let args = [(Yeah, Nah) => Yeah()]
let promise = new Promise(...args)
```

> Uncaught TypeError: [object Object] is not a promise

https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=let%20args%20%3D%20%5B(Yeah%2C%20Nah)%20%3D%3E%20Yeah()%5D%0Alet%20promise%20%3D%20new%20Promise(...args)

**Comment by stefanpenner** [comment]
thoughts 

1. `Promise` constructor takes only 1 arg, why do you need to spread
2. `this` must be preserved to the `Promise` constructor, and `new` must be used. So I am unsure if this is even possible to transpile.

**Comment by timoxley** [comment]
> why do you need to spread

@stefanpenner generic algorithm that wraps instantiation of a few different datatypes, forwards any passed-in args.

> this must be preserved to the Promise constructor, and new must be used to construct it. So I am unsure if this is even possible to transpile.

If `Promise` wants to be special maybe it needs special casing :/ Gross, but might be only way.

**Comment by stefanpenner** [comment]
> If Promise wants to be special maybe it needs special casing. :/ Gross, but might be only way.

basically any new native constructor has this issue.

**Comment by timoxley** [comment]
If any new native constructor wants to be special maybe they needs special casing.

**Comment by stefanpenner** [comment]
is this `special` ? not using `new` breaks the model if something expected to be `new`'d

**Comment by zloirock** [comment]
@timoxley I don't touch `Promise` in Chrome :) It's expected behavior, problem in helper [`_applyConstructor`](https://github.com/babel/babel/blob/339bd2b6d9999db78f2e7db7b6a5ad60f0b1d3b4/src/babel/transformation/templates/apply-constructor.js). See https://github.com/babel/babel/issues/373 , looks like need to add `Promise` to list of native constructors. http://goo.gl/8kGmbf

**Comment by sebmck** [comment]
> I think that strengthens the case for special-casing at least the known built-ins.

They already are, `Promise` just needs to be added to that list.

**Comment by stefanpenner** [comment]
this work-around is bonkers. Just don't spread constructors.

**Comment by sebmck** [comment]
@stefanpenner Yeah I agree that spreading constructors is crazy but not allowing it seems even more crazy.

**Comment by sebmck** [comment]
Fixed as of 4.7.14, thanks!

**Comment by zloirock** [comment]
@sebmck also collections.

**Comment by sebmck** [comment]
Shit.

**Comment by timoxley** [comment]
@sebmck also:
```js
[
  'Uint16Array',
  'ArrayBuffer',
  'DataView',
  'Int8Array',
  'Uint8Array',
  'Uint8ClampedArray',
  'Uint32Array',
  'Int32Array',
  'Float32Array',
  'Int16Array',
  'Float64Array'
]

**Comment by timoxley** [comment]
FWIW This all came about because I'm building out some API smoke testing tools, eventually you'll be able to generate a bunch of random data to throw at a JS API to see how it responds. First thing I needed was a [list of the built-in types and the ability to construct them](https://github.com/timoxley/builtin-types).
