### ISSUE TITLE
[parser] x2028 and x2029 should increment location lines

### ISSUE THREAD

**Issue by pvdz** [babel/babel#10435]
## Bug Report

**Current Behavior**

While line terminators are not allowed in strings (unless continuation), and `\u2028` and `\u2029` are considered line terminators explicitly, they are still allowed inside a string without needing to be escaped. Should this increase the line counter? If multi-line comments and templates do, then I think this should as well.

The same goes for 2028 and 2029 in templates.

**Input Code**

Unfortunately it's not "safe" to just copy paste these characters for a test so I'll try to make it very unambiguous;

```js
babel.parse("\u2028")
babel.parse("\u2029")
```

**Expected behavior/code**

The location should have its line incremented.

```
>    Babel AST is different:
>
>    -  loc:{start:{line:1,column:0},end:{line:2,column:2}},
>    +  loc:{start:{line:1,column:0},end:{line:2,column:4}},
>    -        loc:{start:{line:1,column:0},end:{line:2,column:1}},
>    +        loc:{start:{line:1,column:0},end:{line:2,column:3}},
>    -      loc:{start:{line:1,column:0},end:{line:2,column:2}}
>    +      loc:{start:{line:1,column:0},end:{line:2,column:4}}
```

**Babel Configuration (.babelrc, package.json, cli command)**

**Environment**

Babel 7.5.5

**Possible Solution**

Treat 2028 and 2029 the same as CR or LF when it comes to location tracking.

**Comment by nicolo-ribaudo** [comment]
cc @loganfsmyth I remember that you did already think about this problem, am I right?

**Comment by pvdz** [comment]
Seems this is fixed in, at least, 7.6.4

**Comment by pvdz** [comment]
Apologies; it hasn't been fixed. I was looking at wrong results.

**Comment by pvdz** [comment]
fwiw --> https://github.com/estree/estree/issues/199

**Comment by JLHwung** [comment]
@pvdz I could not reproduce this error on [babel-ast-explorer](https://lihautan.com/babel-ast-explorer/#?eyJiYWJlbFNldHRpbmdzIjp7InZlcnNpb24iOiI3LjYuMCIsIm9wdGlvbmFsQ2hhaW5pbmciOnsib3B0aW9ucyI6e30sImVuYWJsZWQiOnRydWV9LCJkeW5hbWljSW1wb3J0Ijp7Im9wdGlvbnMiOnt9LCJlbmFibGVkIjp0cnVlfX0sInRyZWVTZXR0aW5ncyI6eyJoaWRlRW1wdHkiOnRydWUsImhpZGVMb2NhdGlvbiI6ZmFsc2UsImhpZGVUeXBlIjp0cnVlLCJoaWRlQ29tbWVudHMiOnRydWV9LCJjb2RlIjoiYSA9IGDigKhg4oCoYiA9IGDigKlgIn0=). In addition, the following snippet
```js
var babel = require("@babel/core");
var result = babel.parse("\u2028", { configFile: false })
console.log(result.program.loc);
```
also outputs expected result
```
SourceLocation {
  start: Position { line: 1, column: 0 },
  end: Position { line: 2, column: 0 }
}
```
