### ISSUE TITLE
the unicode definition of t.isValidIdentifier is outdated

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#10434]
## Bug Report

**Current Behavior**
The following snippet returns false because `esutils` are still using Unicode 9.0.0. 

**Input Code**
- REPL or Repo link if applicable: https://runkit.com/embed/h5oakw0vn4bs

```js
const t = require("@babel/types");

t.isValidIdentifier("\u{1B170}");
```

**Expected behavior/code**
Return true, which also aligns to babel-parser.

**Environment**
- Babel version(s): v7.6.1
- Node/npm version: Node 12
- OS: macOS 10.14, Chrome 76
- Monorepo: no
- How you are using Babel: reading source code and try to get rid of `esutils`

**Possible Solution**
Consider move `isIdentifierStart` and `isIdentifierChar` from tokenizer to babel-types, and then get rid of `esutils`.

**Additional context/Screenshots**
\u{1B170} (𛅰) is a [Nüshu](https://en.wikipedia.org/wiki/N%C3%BCshu) character, encoded since Unicode 10.0.0 and has `ID_Start` and `ID_Continue` properties.

<img width="220" alt="Screen Shot 2019-09-12 at 18 51 56" src="https://user-images.githubusercontent.com/3607926/64826539-03110f00-d58f-11e9-86e7-53514dd9b77c.png">

**Comment by nicolo-ribaudo** [comment]
It could work 👍
