### ISSUE TITLE
Calling a method on an `await`ed value with rest parameters incorrectly uses `undefined` as `this` value

### ISSUE THREAD

**Issue by twiss** [babel/babel#10431]
## Bug Report

**Input Code**
- [REPL link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsLwgCgHQHABOA5iAJQwDeAUDDDsAO7CrIwBuwANggKbk8AWz7IAFugAm-QqQoBuGgF8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.6.0&externalPlugins=)

```js
async function fn(...args) {
  (await value).method(...args);
}
```

**Correct code**
With "env preset" _disabled_, the above produces the following (_correct_) code:

```js
"use strict";

async function fn() {
  var _ref;

  (_ref = await value).method.apply(_ref, arguments);
}
```

**Broken code**
However, with "env preset" _enabled_, the above produces the following (_broken_) code:

```js
"use strict";

function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }

function _asyncToGenerator(fn) { return function () { var self = this, args = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(self, args); function _next(value) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); } function _throw(err) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); } _next(undefined); }); }; }

function fn() {
  return _fn.apply(this, arguments);
}

function _fn() {
  _fn = _asyncToGenerator(
  /*#__PURE__*/
  regeneratorRuntime.mark(function _callee() {
    var _ref;

    var _args = arguments;
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.next = 2;
            return value;

          case 2:
            _context.t0 = _ref;
            _context.t1 = _args;

            (_ref = _context.sent).method.apply(_context.t0, _context.t1);

          case 5:
          case "end":
            return _context.stop();
        }
      }
    }, _callee);
  }));
  return _fn.apply(this, arguments);
}
```

Please note how it passes `_context.t0` as the first parameter to `apply`, which is `undefined`. Instead, it should pass `_ref`.

This happens both in Babel v6 (locally) and v7 (in the REPL). The following is my local v6 config.

**Babel Configuration**

```js
{
  plugins: [
    "transform-async-to-generator",
    "syntax-async-functions",
    "transform-regenerator",
    "transform-runtime"
  ],
  presets: [['babel-preset-env', {
    targets: {
      browsers: [
        'IE >= 11',
        'Safari >= 9',
        'Last 2 Chrome versions',
        'Last 2 Firefox versions',
        'Last 2 Edge versions'
      ]
    }
  }]]
}
```

**Environment**
- Babel version(s): v6.26.3
- Node/npm version: Node 8/npm 6
- OS: Windows Subsystem for Linux
- How you are using Babel: babelify

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report, I moved it where the root cause of this bug (regenerator) is maintained: https://github.com/facebook/regenerator/issues/379
