### ISSUE TITLE
istanbul ignore next is ignored after upgrade @babel/core from 7.5.5 to 7.6.0

### ISSUE THREAD

**Issue by mgrybyk** [babel/babel#10432]
## Bug Report

**Current Behavior**
After upgrade `@babel/core` from 7.5.5 to 7.6.0 `jest --coverage` ignores `/* istanbul ignore next */`

**Input Code**
1. clone https://github.com/webdriverio/webdriverio
2. remove `node_modules` and `package-lock.json`
3. set `@babel/core` version to `7.6.0`
4. `npm install`
5. run `node_modules/.bin/jest --clearCache ; node_modules/.bin/jest packages/wdio-sync`

Actual Result:
`executeHooksWithArgs` in `executeHooksWithArgs.js` is NOT ignored which means that `/* istanbul ignore next */` is ignored

NOTE: 
if you repeat steps from 1 to 5 but set `@babel/core` version to `7.5.5` `executeHooksWithArgs` in `executeHooksWithArgs.js` will be ignored, which means the issue is regression since `@babel/core` version `7.5.5`

**Expected behavior/code**
`/* istanbul ignore next */` should be taken into account

**Babel Configuration (.babelrc, package.json, cli command)**

https://github.com/webdriverio/webdriverio/blob/master/babel.config.js

**Environment**
- Babel version(s): `@babel/core` `7.6.0`
- Node/npm version: Node 10 / npm 6.9.0
- OS: OSX 10.3.6 / Ubuntu Xenial
- Monorepo: lerna

**Possible Solution**

**Additional context/Screenshots**
`@babel/core` `7.6.0`
![image](https://user-images.githubusercontent.com/25589559/64742877-07d9b280-d4fe-11e9-8131-2fd6edbe8e4c.png)

`@babel/core` `7.5.5`
![image](https://user-images.githubusercontent.com/25589559/64742820-d06b0600-d4fd-11e9-98c2-b53463fd660d.png)

**Comment by s100** [comment]
It seems as if this is a parsing problem which occurs when the previous line ends with a close-parenthesis. We saw this issue with code looking like:

```js
const socket = socketClient(address)
/* istanbul ignore next */
socket.on('connect', function () {
  debug('Connected to ' + address)
})
```

where the `/* istanbul ignore next */` was not taking effect. We were able to get it to take effect by adding a semicolon to the end of the previous line:

```js
const socket = socketClient(address);
/* istanbul ignore next */
socket.on('connect', function () {
  debug('Connected to ' + address)
})
```

Of course, now our linter, which is configured to disallow semicolons at the end of lines, gets upset, so we also need a little linter configuration:

```js
/* eslint semi: off */

// ...

const socket = socketClient(address);
/* istanbul ignore next */
socket.on('connect', function () {
  debug('Connected to ' + address)
})
```

This is only a workaround.

**Comment by nicolo-ribaudo** [comment]
I'm working on this. It has been introduced by https://github.com/babel/babel/pull/10380
