### ISSUE TITLE
Empty transformer whitelist runs all transformers

### ISSUE THREAD

**Issue by dgreensp** [babel/babel#1044]
I would expect that `transform(code, { whitelist: [] })` would perform no transformations, since no transformers are whitelisted.  Instead, it seems to perform all transformations.

**Comment by sebmck** [comment]
Yeah, this is expected behaviour. Why do you want no transformations to take place?

**Comment by eventualbuddha** [comment]
I wouldn't expect this behavior, fwiw.

**Comment by thejameskyle** [comment]
Agreed, if you're explicitly setting it to an empty array then it makes sense not to run any transformations.

**Comment by dgreensp** [comment]
@sebmck, because that's the definition of a whitelist. :)  This isn't academic, though, it is bound to bite anyone who programmatically generates a whitelist.

For example:

```
var myTransform = function (code, options) {
  var transformList = [];
  
  if (options.arrows) {
    transformList.push('es6.arrowFunctions');
  }
  if (options.lets) {
    transformList.push('es6.blockScoping');
  }

  return babel.transform(code, { whitelist: transformList }).code;
};

myTransform(myCode, { arrows: true, lets: true }) // arrows and lets
myTransform(myCode, { arrows: true, lets: false }) // just arrows
myTransform(myCode, { arrows: false, lets: false }) // ALL TRANSFORMS??
```
