### ISSUE TITLE
Dynamic import does not work on Edge

### ISSUE THREAD

**Issue by rajithaw** [babel/babel#10450]
## Bug Report

**Current Behavior**

I am using import() statements for dynamically loading modules in my code. I've added "@babel/plugin-syntax-dynamic-import" plugin to the .babelrc file. My code runs fine on Chrome and Firefox but fails on Edge with the following error.

![Microsoft_Edge_Error](https://user-images.githubusercontent.com/5545438/65009050-b3479480-d94e-11e9-8ca8-b93aeffeee55.png)

**Input Code**
I have created a demo app which can be used for reproducing the issue.
Extract the zip file contents and run `npm install` and `npm start`.
When you open http://localhost:3000 in Chrome it works but not in Edge.

[dynamic-import.zip](https://github.com/babel/babel/files/3619135/dynamic-import.zip)

**Expected behavior/code**
When the transpiled code runs on Edge, it should recognize the import() statement and should not throw an error.

**Babel Configuration (.babelrc)**

```js
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "browsers": [
                        "IE >= 11",
                        "Edge >= 15",
                        "Safari >= 9.1",
                        "Chrome >= 49",
                        "Firefox >= 31"
                    ]
                }
            }
        ],
        "@babel/preset-react"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-decorators",
            { "legacy": true }
        ],
        [
            "@babel/plugin-proposal-class-properties",
            { "loose": true }
        ],
        "@babel/plugin-syntax-dynamic-import"
    ]
}
```
**Webpack config**
I have also added the core-js modules to my entry point as instructed in https://babeljs.io/docs/en/next/babel-plugin-syntax-dynamic-import.html
```
entry: {
        index: ["core-js/modules/es.promise", "core-js/modules/es.array.iterator",'./src/index.js']
}
```
**Package config**
I also have the latest versions of babel and related plugins installed as dev dependencies.
```
"devDependencies": {
        "@babel/core": "^7.6.0",
        "@babel/plugin-proposal-class-properties": "^7.5.5",
        "@babel/plugin-proposal-decorators": "^7.6.0",
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/preset-env": "^7.6.0",
        "@babel/preset-react": "^7.0.0",
        "babel-loader": "^8.0.6",
        "clean-webpack-plugin": "^3.0.0",
        "core-js": "^3.2.1",
        "html-webpack-plugin": "^3.2.0",
        "webpack": "^4.40.2",
        "webpack-cli": "^3.3.8",
        "webpack-dev-server": "^3.8.1"
}
```

**Environment**
- Babel version(s): [v7.6.0]
- Node/npm version: [Node 10.16.3/npm 6.9.0]
- OS: [Windows 10]
- Monorepo: [no]
- How you are using Babel: [`loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mAAdhaTTah** [comment]
The dynamic import plugin just allows babel to parse the syntax. It doesn't transform `import()`. The reason it works on Edge & Chrome is both of those browsers support dynamic module loading. Handling dynamic import is the responsibility of a bundler. Babel can't do anything for you here because it only works on a single file at a time. It can't know what the proper result should be for transforming `import()`.

**Comment by nicolo-ribaudo** [comment]
Note that Babel can transpile `import()` to commonjs, AMS or systemjs. In you case it should be handled by webpack.

**Comment by rajithaw** [comment]
Thanks for pointing me in the right direction. I'll close this issue and create a new one in webpack.
