### ISSUE TITLE
Babel transform default parameter when not needed

### ISSUE THREAD

**Issue by Austaras** [babel/babel#10454]
## Bug Report

**Current Behavior**
Transform default parameter to es5 when target browsers all support this syntax

**Input Code**
https://babeljs.io/en/repl#?babili=false&browsers=last%202%20versions%20and%20%3E%201%25%2C%20not%20ie%20%3C%3D%2011%2C%0Anot%20op_mini%20all&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAJwIZgOYFMAUBnKVZKRAXkQAYAaRLMAEzMoEpEBvAKEW8QgQMRFkTANoBdLj2BxhOADZYSMJgSJQA3ImUAeWg00wA1Idace5wcmQA6AA4g8ACxwxmk7gF93KRSGRIhDg8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript%2Cenv&prettier=false&targets=&version=7.5.4&externalPlugins=

**Comment by nicolo-ribaudo** [comment]
They aren't fully supported by Edge 17: https://kangax.github.io/compat-table/es6/#test-destructuring,_parameters_defaults,_arrow_function (expand the "destructuring, parameters" section)
