### ISSUE TITLE
Static fields named "constructor" should be a parser error

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10459]
## Bug Report

**Expected Behavior**
Static class fields can't be named `constructor`. We already disable it for instance fields.

**Input Code**
- REPL or Repo link if applicable:

```js
class A {
  static constructor;
}
```

[repl](https://babeljs.io/repl#?babili=false&browsers=last%202%20versions%20and%20%3E%201%25%2C%20not%20ie%20%3C%3D%2011%2C%0Anot%20op_mini%20all&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1oQC5nQS2NYA9gHYYBOArsOgaQNxIC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.6.0&externalPlugins=)

Specification: https://tc39.es/proposal-static-class-features/#sec-static-semantics-early-errors

---

If anyone wants to work on this issue, please leave a comment below! If you need any help, plase ask me (or to any other Babel team member) on [Slack](https://slack.babeljs.io/) :slightly_smiling_face: 

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Fork the repo
2. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
3. Run `yarn && make bootstrap`
4. Wait :hourglass_flowing_sand: 
5. Run `make watch` (or `make build` whenever you change a file)
6. Add a test in `packages/babel-parser/test/fixtures/experimental/class-properties` (you can take the `no-ctor` test in the same folder as an example)
7. Update the code!
8. `yarn jest parser` to run the tests
9. If it is working, run `make test` to run all the tests
10. Note: this change will likely also impact the results of running the [Test262](https://github.com/tc39/test262) suite on Babel.
    - Before running those tests you need to run `make bootstrap-test262` to download them
    - Use `make test-test262` to run them
    - If some tests which were previously failing now pass, you can run `make test-test262-update-whitelist`
10. Run `git push` and open a PR!

Tip: if you don't know where to start from, try to Ctrl+F for the error generated by non-static fields named `constructor`! :smile:

**Comment by guywaldman** [comment]
On it 😊 I'd love to contribute to Babel.

**Comment by nicolo-ribaudo** [comment]
Go for it!

**Comment by Basaingeal** [comment]
I see that this is already claimed, but I was hoping to take a crack at it when I saw it posted on Twitter. Would it be bad form to open a PR of my own with my version of the fix?

**Comment by nicolo-ribaudo** [comment]
Please give @guywaldman the time to fix it, if he doesn't in a few weeks it's your. I encourage you to try fixing this bug locally even if Guy will open a PR, to start getting comfortable with Babel's internals anyway!
