### ISSUE TITLE
URLSearchParams polyfill not provided

### ISSUE THREAD

**Issue by lukepass** [babel/babel#10452]
## Bug Report

**Current Behavior**
Hello, I am very new to this tool so please forgive me :)

I looked into this issue "Babel is not providing polyfill for URLSearchParams #9667" and it says that it should have been fixed while ago.

I noticed that it still doesn't polyfill URLSearchParams:

**Input Code**

```js
  var params = new URLSearchParams(window.location.search);
  var kind = params.get('kind');
```

**Expected behavior/code**
I expected it to be polyfilled.

**Babel Configuration (.babelrc, package.json, cli command)**

babel.config.js

```js
const presets = [
  [
    '@babel/preset-env',
    {
      'useBuiltIns': 'entry',
      'corejs': 3,
    },
  ],
];

module.exports = {presets};
```

packages.json

```
{
  "dependencies": {
    "@babel/polyfill": "^7.6.0",
    "autoprefixer": "^9.6.1",
    "core-js": "^3.2.1",
    "postcss-cli": "^6.1.3",
    "uglify-js": "^3.6.0",
    "uglifycss": "0.0.29"
  },
  "devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "eslint": "^6.4.0",
    "eslint-config-google": "^0.14.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}
```

.browserslistrc

```
last 1 version
> 0.2%
maintained node versions
not dead
ie 10
```

**Environment**
- Babel version(s): 7.6.0 (@babel/core 7.6.0)
- Node/npm version: 6.9.0
- OS: Ubuntu 18.04
- How you are using Babel: cli

Thanks.

**Comment by JennieJi** [comment]
Hi @lukepass , as @babel/polyfill doced [here](https://babeljs.io/docs/en/babel-polyfill), it is deprecated since v7.4.0, now you should use [corejs](https://github.com/zloirock/core-js) directly instead.

**Comment by hzoo** [comment]
Babel doesn't do polyfills directly (whether you use core-js/babel-polyfill/something else) but an updated polyfill should have if it's a newer built-in
