### ISSUE TITLE
IE: iframe.contentDocument: Object doesn't support property or method 'Symbol(Symbol.iterator)_*

### ISSUE THREAD

**Issue by htho** [babel/babel#10453]
Hi,

the original bug #4075 is long gone. But I got the same error in my setup and I want to document the solution, because somebody might face a similar issue.

I used an old version of html2canvas (0.5.0-beta4). `for...of` loops failed for elements selected inside the onclone callback (html2canvas clones the part of the dom that should be screenshotted).

Inside this callback, `clonedRoot.childNodes` is not an instanceof `NodeList`. This is true for the old version of html2canvas and the current version, but the exception is gone.

I dont have the time to investigate this deeper, but I just wanted to share this information. Maybe someone has a similar issue with some other library.

**Comment by htho** [comment]
since this is just fyi i close it now.

**Comment by htho** [comment]
Well,

I need to reopen this issue, because an update in fact did not fix my problem. I don't know why it worked temporarily.

It has nothing to do with html2canvas, but with elements in an iframe. (html2canvas creates the clone in an iframe)

Here is my test code:

```JavaScript
function test(){
    console.log("-- TEST DOCUMENT --");
    
    document.body.insertAdjacentHTML("beforeend", "<div><span id='a' class='foo'></span><span id='b' class='foo'></span></div>");
    
    runTestFor(document.body); // WORKS
    
    
    console.log("-- TEST IFRAME --");
    
    const iframe = document.createElement("iframe");
    document.body.appendChild(iframe);
    iframe.contentDocument.body.insertAdjacentHTML("beforeend", "<div><span id='a' class='foo'></span><span id='b' class='foo'></span></div>");
    
    runTestFor(iframe.contentDocument.body); // -> ERROR!
}

function runTestFor(/** @type {HTMLElement} */ root) {
    const collection = root.getElementsByClassName("foo");
    console.log("collection:");
    console.log(collection);
    console.log("collection instanceof HTMLCollection:", collection instanceof HTMLCollection);
    
    // // With a timeout the same variables get renderd differently in IE
    // // but they still are not a HTMLCollection
    // await new Promise((resolve, reject) => {setTimeout(()=>{resolve()}, 500)});
    // console.log("collection:");
    // console.log(collection);
    // console.log("collection instanceof HTMLCollection:", collection instanceof HTMLCollection);

    console.log("test for...of");
    // for(const child of Array.from(collection)) { // WORKS
    for(const child of collection) { // -> ERROR!
        console.log(child.id);
    }
}
```

Somehow an HTMLCollection within an IFrame is not an HTMLCollection.
Of course adding `Array.from(collection)` would fix it, but that is not the point of babel - right?

**Comment by nicolo-ribaudo** [comment]
An iframe is like a new page, with new JavaScript bultin objects. If you want things inside the iframe to be polyfilled, you need to load the polyfill inside the iframe:

```js
iframe.contentDocument.head.appendChild(`
	<script
		type="test/javascript"
		src="https://unpkg.com/browse/core-js-bundle@3.2.1/minified.js"
	></script>
`)
```
