### ISSUE TITLE
yield* and return()

### ISSUE THREAD

**Issue by rauschma** [babel/babel#1046]
If I understand the spec correctly, `yield*` propagates `return()` (= closing an iterator) similarly to an exception (let me know if you disagree – I may be wrong). I’ll use the following two generator functions to demonstrate what I mean.

```js
function* foo() {
    try {
        yield 'b';
        yield 'c';
    } finally {
        console.log('finally foo');
    }
}
function* bar() {
    try {
        yield 'a';
        yield* foo();
        yield 'd';
    } finally {
        console.log('finally bar');
    }
}
```

The following two examples use `foo()` and `bar()`. I’ve included the expected output (which differs from what Babel produces).

`for-of` closes iterators if one terminates early:

```js
for (let x of bar()) {
    console.log(x);
    if (x === 'b') break;
}
// Output:
// a
// b
// finally foo
// finally bar
```
Destructuring also closes iterators if one doesn’t iterate until the end:

```js
let [x, y] = bar(); // ['a', 'b']
// Output:
// finally foo
// finally bar
```

**Comment by sebmck** [comment]
Looks like a bug. Can you please report this upstream at [regenerator](https://github.com/facebook/regenerator).

**Comment by rauschma** [comment]
OK. I’ll file a separate issue for destructuring not closing iterators.
