### ISSUE TITLE
Numeric separators should be disallowed in unicode escape sequences

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10460]
## Bug Report

**Current and Expected Behavior**

Currently `@babel/parser` allows numeric separators (i.e. the `_` in `123_456`) inside unicode escape sequences, both in the `\u{...}` and `\uXXXX` forms. They should be disallowed.

**Input Code**
- REPL or Repo link if applicable:

```js
"\u{1F_639}";
"\u12_34";
"\x1_2";
```

[repl](https://babeljs.io/repl#?babili=false&browsers=last%202%20versions%20and%20%3E%201%25%2C%20not%20ie%20%3C%3D%2011%2C%0Anot%20op_mini%20all&build=&builtIns=false&spec=false&loose=false&code_lz=EQHQrg3gjAYg-gNgMwE4C-wDcAoUYoBMcSALFkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=&version=7.6.0&externalPlugins=%40babel%2Fplugin-syntax-bigint%407.4.4%2C%40babel%2Fplugin-syntax-numeric-separator%407.2.0)

**Babel Configuration (.babelrc, package.json, cli command)**

You may need to enable the `numericSeparator` parser plugin in order to debug this issue.

**Environment**
- Babel version(s): v7.6

**Possible Solution**

This is a bug in the `Tokenizer`, the part of `@babel/parser` which transforms the input source code into a lazy list of *tokens* (e.g. strings, numbers, identifiers, punctuators, ...).

The problem is that [`readInt`](https://github.com/babel/babel/blob/45a484f0a2802a932a951fca2f9cf1ba63b0aed5/packages/babel-parser/src/tokenizer/index.js#L883), when the `numericSeparator` plugin is enabled, always allows numeric separators.
When `readInt` is called by `readHexChar`, if it finds `_` it should throw something like `Numeric separators are not allowed inside unicode escape sequences`.

---

If anyone wants to work on this issue, please leave a comment below! If you need any help, plase ask me (or to any other Babel team member) on [Slack](https://slack.babeljs.io/) :slightly_smiling_face: 

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add some tests (at least one for `\u{...}`, `\uXXXX` and one for `\xXX`) in `packages/babel-parser/test/fixtures/experimental/numeric-separator`. Please don't call it "invalid-*", but use a descriptive name :stuck_out_tongue:
    - If you want an example of a test for an error, you can check one of the `invalid-*` tests in that folder.
1. Update the code!
1. `yarn jest parser` to run the tests
1. If it is working, run `make test` to run all the tests
1. Note: this change will likely also impact the results of running the [Test262](https://github.com/tc39/test262) suite on Babel.
    - Before running those tests you need to run `make bootstrap-test262` to download them
    - Use `make test-test262` to run them
    - If some tests which were previously failing now pass, you can run `make test-test262-update-whitelist`
1. Run `git push` and open a PR!

**Comment by ivandevp** [comment]
I would like to take this issue :blush:

**Comment by nicolo-ribaudo** [comment]
It's your!
