### ISSUE TITLE
The BigInt suffix should be disallowed in NonOctal Decimal Integer Literal

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#10465]
## Bug Report

**Current Behavior**
The following code should throw a syntax error if the parser plugin bigInt is enabled.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=AwDgnAdkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.6.0&externalPlugins=%40babel%2Fplugin-syntax-bigint%407.4.4

```js
089n
```

**Expected behavior/code**
It should throw `Invalid BigIntLiteral` error.

**Background**

We use tokenizer to process the source code into a stream of tokens and `08n` will be processed in `readNumber`
https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/packages/babel-parser/src/tokenizer/index.js#L981

The NonOctal Decimal Integer Literal is defined as

```
NonOctalDecimalInteger:
0 DecimalDigits

DecimalDigits:
DecimalDigit DecimalDigits_opt

DecimalDigit:
0 1 2 3 4 5 6 7 8 9
```
The above grammar requires a NonOctal Decimal Integer Literal to be a sequence of decimal digits starting with zero and the length is at least 2.

**Possible Solution**
1. Detect NonOctal Decimal Integer Literal in `readNumber`. Throw an error here when it is detected.

https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/packages/babel-parser/src/tokenizer/index.js#L1027-L1028

2. Add a test on https://github.com/babel/babel/tree/master/packages/babel-parser/test/fixtures/experimental/bigint

3. Run `make test-test262-update-whitelist` to update the whitelist, the following lines are expected to be removed.
https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/scripts/tests/test262/test262_whitelist.txt#L113-L116

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by gonzarodriguezt** [comment]
I would like to take this! :)

**Comment by JLHwung** [comment]
@gonzarodriguezt Sure, go for it. If you have any questions on developing with babel, feel free to discuss it in our [slack room](https://slack.babeljs.io/).
