### ISSUE TITLE
misbehave: babel.config.js VS .babelrc

### ISSUE THREAD

**Issue by xiaobeilo** [babel/babel#10463]
## Bug Report

**Current Behavior**
When I upgraded to Babel > 7 and used the. Babelrc configuration file, it seemed that babel-loader did not handle the dependencies under node_modules, although I added the build in webpack
When I used Babel. Config. js, it worked correctly

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false
    }]
  ]
}
```

**Environment**
    "@babel/core": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "babel-loader": "^8.0.6",
    "webpack": "^4.40.2",
    "webpack-cli": "^3.3.9"
- Node/npm version: [e.g. Node 10.9.0/npm 6.2.0]
- OS: [OSX 10.13.3 ]
- How you are using Babel: [`loader`]

**Possible Solution**
I expect consistent behavior

**Additional context/Screenshots**

I opened a can emersion git repository: https://github.com/xiaobeilo/babel-issues-demo

You can reproduce it by following the steps above on readme.md

**Comment by nicolo-ribaudo** [comment]
It is the expected behavior: `.babelrc` is only applied to your own package, while `babel.config.js` to the whole project.

If the documentation wasn't clear, how do you suggest we could improve it? https://babeljs.io/docs/en/config-files#configuration-file-types

**Comment by xiaobeilo** [comment]
Ha ha, sorry, I did not read carefully, now I understand, thank you for your reply
