### ISSUE TITLE
generatorOpts/jsescOption/minimal not working for Chinese characters

### ISSUE THREAD

**Issue by kofifus** [babel/babel#10464]
(after `npm install -g @babel/core @babel/cli @babel/preset-env @babel/generator babel-preset-minify`)

I am struggling to babel source code containing Chinese characters. 
Looking [here](https://github.com/babel/babel/pull/8143) I tried using `generatorOpts` like this:

.babelrc:
```
{
  "comments": false,
  "generatorOpts": {
    "jsescOption": {
      "minimal": true,
    }
  },
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": ["ios 7"]
      }
    }],
    ["minify"]
  ],
}
```

but Chinese strings are still transformed to another (wrong) encoding.

Ie in source:

`$('#LabelFilter').text('筛选');` (as displayed in ie VScode)

after babe with above .babelrc:

$("#LabelFilter").text("�?�??")

What I need is for babel to completely leave those strings alone.

Any help is appreciated!

**Comment by nicolo-ribaudo** [comment]
I can't reproduce this bug, could you provide a repository which reproduces it?

Also: never install Babel globally. It will cause problems because it might use old presets from your dependencies.
Do you get the same wrong output if you install them with `npm install --save-dev @babel/core @babel/cli @babel/preset-env @babel/generator babel-preset-minify` and compile using `./node_modules/.bin/babel` instead of `babel`?

**Comment by JLHwung** [comment]
Could you make sure the original source file is encoded in utf-8? 

Babel would always output the file in the utf-8 encoding. If the source file is encoded in GBK but _interpreted_ as utf-8, the output file would be so-called [Mojibake](https://en.wikipedia.org/wiki/Mojibake) or 乱码 in Chinese. And it will be even worse when these Mojibake is _interpreted_ by code editor as GBK source again.

**Comment by kofifus** [comment]
@nicolo-ribaudo  using `--save-dev` and `./node_modules/.bin/babel` did not help

@JLHwung  the source encoding as shown by VSCode is UTF-8, is there anything else I can check ?

**Comment by JLHwung** [comment]
> $("#LabelFilter").text("�?�??")

@kofifus Could you attach the transpiled source file? You may remove unrelated source.

**Comment by kofifus** [comment]
Ok I found it, you were right it had nothing to do with babel. I was doing some regexp replace stuff of the js before calling babel using another tool (`rxrepl.exe`) and forgot to set it to utf8, so babel already received broken input.

Thanks for the help, closing this.
