### ISSUE TITLE
Default function parameters is a inline function 

### ISSUE THREAD

**Issue by Wcdaren** [babel/babel#10471]
```js
var x = 1
function foo(x, y = function () { x = 2 }) {
	var x = 3
	y()
	console.log(x);
}
foo() 
console.log(x);  // 3 1 
```
after bable 
```js
"use strict";

var x = 1;

function foo(x) {
  var y = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : function () {
    x = 2;
  };
  var x = 3;
  y();
  console.log(x);
}

foo();
console.log(x);
// 2 1 
```

**Comment by JLHwung** [comment]
Related issue: #9947

**Comment by openorclose** [comment]
This looks to have been fixed by https://github.com/babel/babel/pull/10053

**Comment by openorclose** [comment]
My bad, I'll try to work on a fix.

**Comment by openorclose** [comment]
```js
function foo(a = 1) {
  var a = 1;
}
```
A related error.
This is valid but doesn't compile:
https://babeljs.io/repl/#?browsers=%3E0.5%25%2C%20not%20ie%20%3C%3D11%2C%20not%20safari%205.1%2C%20not%20samsung%204&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUBDRBeRBGASkQG8AoRRANwwCdEtc8BuUgXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Cenv&prettier=false&targets=&version=7.8.4&externalPlugins=%40babel%2Fplugin-transform-react-jsx%407.8.3
