### ISSUE TITLE
Partial destructuring should trigger a `return()`

### ISSUE THREAD

**Issue by rauschma** [babel/babel#1047]
If a destructuring doesn’t iterate over all the elements of an iterator, it should call `return()` (similar to `for-of`). Example:

```js
function* foo() {
    try {
        yield 'a';
        yield 'b';
    } finally {
        console.log('finally foo');
    }
}
let [x] = foo(); // x = 'a'
// Expected output:
// finally foo
```

**Comment by sebmck** [comment]
Fixed in the `experimental` branch that will be released in the next major. Thanks!
