### ISSUE TITLE
[parser] Disallow private properties access on super

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10470]
## Bug Report

**Input Code**

```js
class A extends B {
  #x;

  method() {
    super.#x;
  }
}
```

[repl](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjAQtA3gFDTQDESA3IcdALYIoAWA9pgBQCUBNJEArgAcEAJwB05KiQC-hKUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=&prettier=false&targets=&version=7.6.0&externalPlugins=%40babel%2Fplugin-syntax-class-properties%407.2.0)

**Expected behavior/code**

It should throw a parser error.

**Specification**

In the class fields proposal, [`MemberExpression`](https://tc39.es/proposal-class-fields/#prod-MemberExpression) (which is the technical tern for "property access") is defined as follows:
```
MemberExpression:
  PrimaryExpression
  MemberExpression [ Expression ]           <-- foo[bar]
  MemberExpression . IdentifierName         <-- foo.bar
  MemberExpression TemplateLiteral          <-- foo`bar`
  SuperProperty
  MetaProperty
  new MemberExpression Arguments            <-- new foo.bar()
  MemberExpression . PrivateIdentifier      <-- foo.#x
```

As you can see, `.PrivateIdentifier` (where a `PrivateIdentifier` is like `#x`) is only allowed after another `MemberExpression`.

Let's see what [`SuperProperty`](https://tc39.es/ecma262/#prod-SuperProperty) is. It is not redefined by the proposal, so we must search it in the main specification.
```
SuperProperty:
  super [ Expression ]                      <-- super[foo]
  super . IdentifierName                    <-- super.#x
```

As you might see, there is nothing allowing `super.#x`

**Babel Configuration (.babelrc, package.json, cli command)**

In order to test this bug, you must enable the `classPrivateProperties` parser plugin

**Environment**
- Babel version(s): v7.6

**Possible Solution**

When we parse the `super` keyword, we check if it is followed by `(`, `[` or `.` and throw otherwise:

https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/packages/babel-parser/src/parser/expression.js#L912-L920

A naive solution would be to also check the next token, using `this.lookahead()`. However, in `@babel/parser` `lookahead()` is _really_ expensive because it needs to clone the whole parser state, produce the next token and then reset the state to what it was before: it should be avoided when possible.

What we could do is to disallow it when we are parsing the `MemberExpression` rather than the `super` keyword:

https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/packages/babel-parser/src/parser/expression.js#L653-L662

After parsing the `node.property` (which is the "thing" after the dot), we can check if
1. the base object is a `Super` node, and
1. the property is a `PrivateName` node.

If both those condition are met, we should raise an error explaining that it is disallowed.

---

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. :red_circle: Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test inside `packages/babel-parser/test/fixtures/experimental/class-private-properties`. You can look in the folders to check how tests about errors are structured.
1. Update the code!
1. `yarn jest parser` to run the tests
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

If you need any other help, you can join our [Slack](https://slack.babeljs.io/) and ask in the `#developement` channel. *

<details>
<summary>*</summary>

I'm going bed now, but I'm sure you'll find someone else online! :slightly_smiling_face: 

</details>

**Comment by VivekNayyar** [comment]
I will pick this up

**Comment by nicolo-ribaudo** [comment]
It's yours!
