### ISSUE TITLE
Function declarations should not be limited in block scope when there is a let declaration

### ISSUE THREAD

**Issue by hgl** [babel/babel#1048]
```js
{
  let a = 2
  function b() {
    a;
  }
}

console.log(typeof b);
```

=>

```js
{
  (function () {
    var b = function () {
      a;
    };

    var a = 2;
  })();
}

console.log(typeof b);
```

Compiled code outputs `"undefined"`, which should be `"function"` if I'm not wrong.

Probably should compile to:

```js
{
  var b;
  (function () {
    var _b = function () {
      a;
    };
    b = _b;

    var a = 2;
  })();
}

console.log(typeof b);
```

**Comment by sebmck** [comment]
Nope, this is correct. In ES6 function declarations are block scoped. In previous versions the behaviour of function declarations in blocks wasn't specced so many implementations just hoisted them and it became pseudo-standard.

You can isolate this behaviour to just:

```javascript
{
  function a() {}
}
a;
```

**Comment by hgl** [comment]
Ah, B.3.3 of the spec addressed exactly that. Somehow missed it.

Thank you for the explanation. Very helpful.
