### ISSUE TITLE
objectSpread not working with boolean arguments

### ISSUE THREAD

**Issue by MengMengYan** [babel/babel#10482]
Hi,
We have a scenario where objectSpread throws an exception when the arguments list contains a boolean.

This particular piece of code 

```
function _objectSpread(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i] != null  ? arguments[i] : {};
    var ownKeys = Object.keys(source);

    if (typeof Object.getOwnPropertySymbols === 'function') {
      ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function (sym) {
        return Object.getOwnPropertyDescriptor(source, sym).enumerable;
      }));
    }

    ownKeys.forEach(function (key) {
      defineProperty(target, key, source[key]);
    });
  }

  return target;
}
```

gives an exception : Object.keys argument is not an object.

Shouldn't the check be like:
`   var source = arguments[i] != null && typeof arguments[i] === 'object' ? arguments[i] : {};`

**Comment by nicolo-ribaudo** [comment]
`Object.keys` should support boolean arguments. You might need to load a polyfill.

**Comment by chrishinrichs** [comment]
@nicolo-ribaudo this fails in IE11, which has `Object.keys` natively - seems like this should be fixed as we're using a `babel-preset-env` setting that should include IE11 and this issue did not occur with babel@6

**Comment by peey** [comment]
@chrishinrichs the spec for [Object.keys](https://www.ecma-international.org/ecma-262/9.0/#sec-object.keys) dictates that it should work for booleans^*. IE11 might be deviating from the spec.

Can you check if `Object.keys(new Object(boolean))` works? Your browser's supposed to be doing something similar internally.

**Comment by chrishinrichs** [comment]
@peey from what I can gather, IE11 implements the ES5 version of `Object.keys` which specified that the argument had to be an Object (http://ecma-international.org/ecma-262/5.1/#sec-15.2.3.14). The ES6 spec changed to indicate it should be coerced to an object, which is what modern browsers do (http://ecma-international.org/ecma-262/6.0/index.html#sec-object.keys).

I confirmed that `Object.keys(Object(boolean))` works in IE11 and have updated my PR accordingly.
