### ISSUE TITLE
`@babel/types` should validate the number of elements inside template literals

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10486]
## Feature Request

`@babel/types`, when calling `t.templateLiteral` , should throw an error if the number of `quasis` (static template strings) is not exactly one more than the number of `expressions` (substitutions).

**Possible Solution**

`@babel/types` already already provides the ability to define custom validation functions, for example
https://github.com/babel/babel/blob/a00f3716106a0811ff9b915783bb90f2949ef48a/packages/babel-types/src/definitions/core.js#L408-L412

You should add a custom validator to `TemplateLiteral`, defined in the `packages/babel-types/src/definitions/es2015.js` file.

---

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test at `packages/babel-types/test/builders/es2015/templateElement.js`
1. Update the code!
1. `yarn jest babel-types` to run the tests
    - If you need to update some snapshots generated by Jest, you can run the tests again with the `-u` cli flag
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by Basaingeal** [comment]
I'll give this one a go.

**Comment by tsareg** [comment]
Hey folks, after upgrading to recent @babel/types (namely 7.6.3) I started to get:
"Number of TemplateLiteral quasis should be exactly one more than the number of expressions.
Expected 2 quasis but got 1"

The code I'm trying is dynamic import with `@loadable/component`:
```js
const AsyncIcon = loadable(props => import(`./icons/${props.name}.js`));
```

This was working fine with @babel/types 7.4.4.
Can you please explain what's wrong now with this code and what needs to be changed?
