### ISSUE TITLE
No matching version found for @babel/generator@^7.6.2

### ISSUE THREAD

**Issue by Carrie-Zhang** [babel/babel#10485]
## Bug Report

**Current Behavior**
-Run npm install --save-dev @babel/core
  Get following error messages:
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for @babel/generator@^7.6.2
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    npm ERR! notarget 
    npm ERR! notarget It was specified as a dependency of '@babel/core'
    npm ERR! notarget

-Run npm install --save-dev @babel/generator
  Get + @babel/generator@7.6.0

- Run `npm config rm proxy` `npm config rm https-proxy` and `npm cache clean --force` does not help

**Environment**
- Babel version(s):"@babel/core": "^7.5.5"
- Node/npm version: node 8.9.1
- OS: OSX 10.13.6
- How you are using Babel: `loader`

**Comment by nicolo-ribaudo** [comment]
Thanks! I will fix this in a few minutes

**Comment by nicolo-ribaudo** [comment]
Actually, it seems that it has been correctly published: https://www.npmjs.com/package/@babel/generator :thinking:

**Comment by Carrie-Zhang** [comment]
Nothing in the log

**Comment by Carrie-Zhang** [comment]
Right now the error becomes to:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/traverse@^7.6.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/core'
npm ERR! notarget

**Comment by nicolo-ribaudo** [comment]
If you look for "dist-tags" at http://registry.npmjs.org/@babel/traverse, what version do you see (it should be in the first few lines)

**Comment by Carrie-Zhang** [comment]
"dist-tags":{"latest":"7.6.2"}

**Comment by Carrie-Zhang** [comment]
However, when do `npm i --save-dev @babel/traverse`
Got + @babel/traverse@7.6.0

**Comment by nicolo-ribaudo** [comment]
Oh ok. This is a npm bug, since you are correctly seeing the version as published.
Usually this kind of npm bugs are solved automatically by waiting until every proxy/cache between you and them is updated. You could report it at https://npm.community/

Btw, `npm view @babel/traverse` prints nothing?
Also, make sure that your npm client is updated.

**Comment by Carrie-Zhang** [comment]
npm view @babel/traverse

@babel/traverse@7.6.0 | MIT | deps: 9 | versions: 49
The Babel Traverse module maintains the overall tree state, and is responsible for replacing, removing, and adding nodes
https://babeljs.io/

dist
.tarball: https://artifactory.corp.adobe.com:443/artifactory/api/npm/npm-asset-release/@babel/traverse/-/traverse-7.6.0.tgz
.shasum: 389391d510f79be7ce2ddd6717be66d3fed4b516

dependencies:
@babel/code-frame: ^7.5.5                      @babel/helper-split-export-declaration: ^7.4.4 debug: ^4.1.0                                  
@babel/generator: ^7.6.0                       @babel/parser: ^7.6.0                          globals: ^11.1.0                               
@babel/helper-function-name: ^7.1.0            @babel/types: ^7.6.0                           lodash: ^4.17.13                               

maintainers:
- danez <daniel@tschinder.de>
- existentialism <bng412@gmail.com>
- hzoo <hi@henryzoo.com>
- loganfsmyth <loganfsmyth@gmail.com>
- nicolo-ribaudo <nicolo.ribaudo@gmail.com>

dist-tags:
latest: 7.6.0

**Comment by Carrie-Zhang** [comment]
npm view @babel/generator

@babel/generator@7.6.0 | MIT | deps: 5 | versions: 50
Turns an AST into code.
https://babeljs.io/

dist
.tarball: https://artifactory.corp.adobe.com:443/artifactory/api/npm/npm-asset-release/@babel/generator/-/generator-7.6.0.tgz
.shasum: e2c21efbfd3293ad819a2359b448f002bfdfda56

dependencies:
@babel/types: ^7.6.0 jsesc: ^2.5.1        lodash: ^4.17.13     source-map: ^0.5.0   trim-right: ^1.0.1   

maintainers:
- danez <daniel@tschinder.de>
- existentialism <bng412@gmail.com>
- hzoo <hi@henryzoo.com>
- loganfsmyth <loganfsmyth@gmail.com>
- nicolo-ribaudo <nicolo.ribaudo@gmail.com>

dist-tags:
latest: 7.6.0

**Comment by nicolo-ribaudo** [comment]
What does `npm config get registry` log?

**Comment by Carrie-Zhang** [comment]
Thanks @nicolo-ribaudo , found out registry point to a wrong url. Problem solved.
