### ISSUE TITLE
RFC: Support babel.config.json for better cacheability

### ISSUE THREAD

**Issue by devongovett** [babel/babel#10495]
At the moment, Babel supports several configuration options: `.babelrc`, `.babelrc.js`, and `babel.config.js`. Many projects have migrated to `babel.config.js` since it was introduced, especially monorepos. However, many configs are still quite simple and could be JSON instead of JavaScript. This has several benefits, including better cacheability. Babel should support `babel.config.json` in addition to its existing options for those cases.

Using JavaScript for configs can be nice when you need to do complex condition-based configuration, but it has several downsides including preventing caching. In Parcel 2, we have to bail on caching all files compiled with Babel when a JavaScript config file is used instead of JSON. Unfortunately, that leaves no recourse to users if they want the benefits of caching, but want to use a root config. If Babel supported `babel.config.json`, these issues would be alleviated somewhat. For simple configs that are JSON serializable, Parcel and other tools could correctly cache files as is already possible with `.babelrc`.

I am aware of the Babel config [caching](https://babeljs.io/docs/en/config-files#apicache) API, but it's not really designed for use in a cache that is serialized to disk. It is designed to avoid re-calling the config function, not to avoid re-compiling files. In addition, the API relies on callback functions to determine if the cache should be invalidated, but that only works when the callback can be stored in memory - we cannot serialize it to disk.

**Comment by nicolo-ribaudo** [comment]
Previous discussion: https://github.com/babel/babel/pull/7358#issuecomment-364638966

Personally, I would like this feature. For most users, the only dynamism that they might need in their config is provided by the `env` key.
Other that caching, I think that it has some advantages:
- It would allow us to esily lint configuration files (https://github.com/babel/babel/issues/7880, [babel-doctor](https://babeljs.io/blog/2015/11/03/babel-doctor))
- It make it possible to have autocompletion in editors, using a simple JSON schema. For example, I never remember if it's `overwrite`, `overwrites`, `override` or `overrides`, as well as `parserOpts` vs `parserOptions`.
- `babel-upgrade` is dying, and it a pity: it's a powerful tool which can have its advantages also when upgrading accross minor versions (for example, to remove an unnecessary plugin) or in the Babel 7 -> Babel 8 update. Unfortunatly, it can only work with JSON files.

**Comment by devongovett** [comment]
That's a good list of other advantages of JSON over JS. I'm happy to make a PR for this if it is something Babel would consider.

cc. @loganfsmyth from the previous discussion

**Comment by devongovett** [comment]
Made a PR since it was pretty easy: https://github.com/babel/babel/pull/10501

**Comment by Jessidhia** [comment]
@nicolo-ribaudo it actually is possible to have autocompletion in typescript-aware editors with `babel.config.js` -- but it takes some boilerplate. You need `@types/babel__core` installed and

```js
// @ts-check
'use strict'

/**
 * @param {import('@babel/core').ConfigAPI} api
 * @returns {import('@babel/core').TransformOptions}
 */
module.exports = function(api) {
  return {/* ... */}
}
```
