### ISSUE TITLE
babel-plugin-proposal-private-methods using symbols

### ISSUE THREAD

**Issue by vankop** [babel/babel#10498]
## Feature Request

**Is your feature request related to a problem? Please describe.**

If it will be possible to use `Symbol` for private method, plugin will produce less code. Obviously, it must be used only for supported envs.

**Describe the solution you'd like**

Code:
```
class A {
   constructor() {
        this.publicProperty = this.#privateMethod();
  }

  #privateMethod () { return 1; }
}
```

will be transformed to:
```
const privateMethod = Symbol();

class A {
   constructor() {
        this.publicProperty = this[privateMethod]();
  }

  [privateMethod]() { return 1; }
}
```

Maybe I do not understand why Babel can not use this assumption, it will be great if you will clarify for me why it is not possible.

**Comment by nicolo-ribaudo** [comment]
It's because they are not private properties. They are normal public properties with an unknown name. It's like doing this:

```js
const privateMethod = "Secret!" + Math.random();

class A {
   constructor() {
        this.publicProperty = this[privateMethod]();
  }

  [privateMethod]() { return 1; }
}
```

**Comment by vankop** [comment]
Thanks for explanation. It possible to access using `Object.getOwnPropertySymbols` only as I see
