### ISSUE TITLE
Nested Typescript enums wrong transpilation.

### ISSUE THREAD

**Issue by piet-v** [babel/babel#10497]
## Bug Report

**Current Behavior**
When defining an enum (NewEnum) using values from another enum (OriginalEnum) NewEnum will end up also containing all key/value pairs from OriginalEnum.

**Input Code**
https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYOwrgtgBAwg8gGTgJQMpQN4CgpQOoASAkgCoCiUAvFAOQDEAZk8zQDQ5QBCCAgjANJVadAAxjxbLAF8sWUJCglgADwAuMAPYAbDQCcAzpg4AHXQEsIAQ10BPIfCRoAdIVJl2ufcADGGkABNrO2oHFFQnbj5-dikgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.6.2&externalPlugins=%40babel%2Fplugin-transform-typescript%407.6.0

**Expected behavior/code**
The `TextColors` enum should not contain a copy of `Color` enum

https://www.typescriptlang.org/play/?ts=3.3.3#code/KYOwrgtgBAwg8gGTgJQMpQN4CgpQOoASAkgCoCiUAvFAOQDEAZk8zQDQ5QBCCAgjANJVadAAxjxbLAF8sWUJCglgADwAuMAPYAbDQCcAzpg4AHXQEsIAQ10BPIfCRoAdIVJl2ufcADGGkABNrO2oHFFQnbj5+dikgA

**Babel Configuration (.babelrc, package.json, cli command)**

```js
"@babel/plugin-transform-typescript": "7.6.0"
```

**Environment**
- Babel version(s): v7.0.0
- How you are using Babel: REPL

**Possible Solution**
Use same behaviour as Typescript compiler?

**Comment by piet-v** [comment]
Did some experimentation. Seems this inconsistency happens with any dynamic value.

Also happens for: 
https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MDe9EC4YHIBOApgCa4A0MARgIb5a6UA2ArobjAL4DcAUD4WGYBbGADEAlgC9JAYRCMQ-COh4wYjcQHMAFlFQAiOFMn6YAahj7KzafrKqYxWgGtUCEADoa-exyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.6.2&externalPlugins=%40babel%2Fplugin-transform-typescript%407.6.0

**Comment by polkovnikov-ph** [comment]
@piet-v The provided code doesn't reproduce the issue for me anymore. Seems it was fixed.

**Comment by nicolo-ribaudo** [comment]
This has been fixed: https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYOwrgtgBAwg8gGTgJQMpQN4CgpQOoASAkgCoCiUAvFAOQDEAZk8zQDQ5QBCCAgjANJVadAAxjxbLAF8sWUJCglgADwAuMAPYAbDQCcAzpg4AHXQEsIAQ10BPIfCRoAdIVJl2ufcADGGkABNrO2oHFFQnbj5-dikgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.6.2&externalPlugins=%40babel%2Fplugin-transform-typescript%407.6.0
