### ISSUE TITLE
[preset-env] ios8 Computed property names wont transfer in strict mode

### ISSUE THREAD

**Issue by qiyunbao** [babel/babel#10503]
## Bug Report

**Current Behavior**
when set env target to ios8, @babel/preset-env won‘t transform `Computed property names` syntax, which in ios8 is not fully support in strict mode.

**Input Code**

```js
(function () {
   "use strict";
    var C = {
       y: '12',
       m: '13',
     };
   var result = {
      [C.y]: 'abc',
      [C.m]: 'cde',
    };
    console.log(result);
 });
```

**Expected behavior/code**
If the target is set to ios8,  babel-env should transfer the code to es5,  but now it will keep the syntax and ios8 will throw an Error like this `SyntaxError: Attempted to redefine proerty '12'`

In caniuse.com, it says ios 8 support `Computed property names` Syntax, but the true is, it has some bug in strict mode. the code above will throw error, If you useing only one `[C.y]`  or only `[C.m]` it is ok, but together it will throw the error，in none strict mode, is is ok too. I believe it is some werid bug in ios 8 webview

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// preset-env's config
{
  "targets": { "ios": 8 }
}
```

**Environment**
- Babel version(s): 7.4.3
- Node/npm version: Node 10/npm 6
- OS:  ios8.4
- How you are using Babel: `loader`

**Possible Solution**

this Syntax should be transfer to es5 in ios8 target

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
The browser feature data in preset-env is aligned to caniuse. In this data every browser will have a range of versions in which the feature is natively supported. We would _not_ mark any specific version as unsupported if the implementation is faulty under some edge cases. 

Note that you can use `include` option of preset-env to enable `@babel/plugin-transform-computed-properties`.
```json
// preset-env's config
{
  "targets": { "ios": 8 },
  "include": ["@babel/plugin-transform-computed-properties"]
}
```

**Comment by jridgewell** [comment]
> We would not mark any specific version as unsupported if the implementation is faulty under some edge cases.

We can actually mark iOS 8 as broken and iOS 9 as fixed, and preset-env will only transpile if iOS 8 is included in the list. We did that for tagged template literals.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since it's not directly actionable for us.
Someone should open a PR adding this bug to https://github.com/kangax/compat-table/, and then it will be automatically fixed in Babel once we update our compat-table version.
