### ISSUE TITLE
TypeError: Invalid attempt to spread non-iterable instance [occurs only iOS Safari]

### ISSUE THREAD

**Issue by rzubrycki** [babel/babel#10509]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
`"devDependencies": {

"@babel/core": "^7.5.5",
"@babel/preset-env": "^7.5.5",
"babel-preset-env": "^1.7.0",
"parcel-bundler": "^1.12.3",
"sass": "^1.22.9"
	},
	"dependencies": {
		"date-fns": "^2.2.1",
		"mustache": "^3.0.1"
	},
	"scripts": {
		"start": "parcel index.html --open",
		"build": "parcel build index.html --no-source-maps --public-url $npm_package_config_public_url"
	},
	"browserslist": "> 0.02%"
}`

.babelrc
`{
	"presets": ["@babel/preset-env"]
}
`

## 🤔 Expected Behavior

Spread should work as is supported by Safari.

## 😯 Current Behavior

On Safari only i got error in console => "TypeError: Invalid attempt to spread non-iterable instance" 

## 💁 Possible Solution

I tried google it and try some solutions, but all failed.

## 💻 Code Sample

just trying to grab two dom elements and use map on it:
`const dateElement = [...document.querySelectorAll('.date')];`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |v11.3.0
| npm/Yarn         | 6.10.3
| Operating System | ios

Any help much appreciate, cheers.

**Comment by jieyouxu** [comment]
If you evalute the expression `document.querySelectorAll('.date')` in the console, you will find that the evaluated expression is of type `NodeList`, representing a collection of `Node`s (see [MDN | NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)). Note that the spread operator `...target` requires that `target` be an `iterable`, i.e. to implement the `[Symbol.iterator]` method (see [MDN | Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Only_for_iterables)). `NodeList` does *not* implement `[Symbol.iterator]`, which causes your `TypeError` (see [MDN | NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList)). To resolve this issue, either (possible solutions but not limited to):

1. Use the `NodeList.forEach` method and supply a callback (becareful the `element` is of type `HTMLElement` or similar, refer to [MDN | HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) for specifics):
    ```js
    document.querySelectorAll('.date').forEach(element => console.log(element))
    ```
2. Call the `NodeList.values()` method which will return an `iterable` allowing you to use the spread operator on it:
    ```js
    const dateElements = [...document.querySelectorAll('.date').values()];
    ```

Hope this helps!

**Comment by felboomy** [comment]
If you need any help, or just have general Babel or JavaScript questions, we have a vibrant,,

**Comment by nicolo-ribaudo** [comment]
Thanks @felboomy and @jieyouxu!
Even if it's not written on MDN, I believe that modern browsers support `[Symbol.iterator]` on `NodeList`.
That said, Babel is only about core JavaScript and not about dom APIs. I suggest manually loading a polyfill for `NodeList.prototype[Symbol.iterator]`, or (better) use `Array.from(x)` instead of `[...x]`

**Comment by felboomy** [comment]
Or just have general Babel or JavaScript questions, we have ..?

**Comment by samshelley** [comment]
I'm also seeing this on Edge 15, Chrome 49 (last chrome build for Windows XP), Facebook 239.0.0. These browsers are not super prevalent, but the error was easy enough to fix once we figured it out (it was just fairly surprising)

It looks like the helper function that is used to polyfill `...` on old browsers (https://github.com/babel/babel/blob/43065a9e24b42cf34a6da48b62576ab5909dcae2/packages/babel-helpers/src/helpers.js#L928) does this `Symbol.iterator in Object(iter)` to check validity. On newer browsers `NodeList` appears to implement `Symbol.iterator` as mentioned so it's fine. On the listed browsers it does not and errors.

It's fairly easy to fix by just using `Array.from` or `Array.prototype.slice.call`. That said this behavior is fairly surprising as some light googling finds stackoverflow answers that strongly suggest doing it the way the the original poster did (https://stackoverflow.com/questions/7459704/in-javascript-what-is-the-best-way-to-convert-a-nodelist-to-an-array)

Not sure where the right place to fix this is @nicolo-ribaudo or if this is worth fixing but figured I'd share my example as well. It definitely was a bit confusing that babel effectively loaded a polyfill that did not actually work on older browsers.

**Comment by mikeRChambers610** [comment]
For anyone it might help, this issue happened for me because I was trying to use a graphql query in the wrong way. I was doing the initial query which returned an object and then I was trying to refetch the same query but I was trying to return it in an items array. Once I removed the items[] the issue was solved.

GraphQL that had the issues:
graphql(myQuery, {

options: props => ({
  
    variables: {
      userID: " ",
      groupID: " "
    },
    fetchPolicy: 'cache-and-network'
}),
props: props => {
    return {

    dataReturned: props.data.getData,

    onGetMoreData: vars => {
      return props.data.fetchMore({
        query: myQuery,
        variables: vars,
        updateQuery: (previousResult, { fetchMoreResult }) => ({
          getData: {
            __typename: 'Data',
// items below was the issue
items: [
...fetchMoreResult.getData
]
}
})
})
},
data: props.data,
}
}
}),

After removing items (this fixed my issue)
graphql(myQuery, {

options: props => ({
  
    variables: {
      userID: " ",
      groupID: " "
    },
    fetchPolicy: 'cache-and-network'
}),
props: props => {
    return {

    dataReturned: props.data.getData,

    onGetMoreData: vars => {
      return props.data.fetchMore({
        query: myQuery,
        variables: vars,
        updateQuery: (previousResult, { fetchMoreResult }) => ({
          getData: {
            __typename: 'Data',
// items below was the issue
items: [
...fetchMoreResult.getData
]
}
})
})
},
data: props.data,
}
}
}),
