### ISSUE TITLE
`yield` as a parameter

### ISSUE THREAD

**Issue by rauschma** [babel/babel#1050]
The following code produces a syntax error. Any idea why? Firefox is fine with it.

```js
function* foo() {
    console.log(yield);
}
```

**Comment by sebmck** [comment]
Likely a Firefox bug. Possibly related discussion on yield grammar https://twitter.com/abargull/status/575800817376169986 and marijnh/acorn#219 Doesn't appear to be allowed by Traceur either.

**Comment by rauschma** [comment]
IINM, that’s a different issue. I’m asking further questions there. Thanks for the pointers!

**Comment by sebmck** [comment]
Fixed in the `experimental` branch.
