### ISSUE TITLE
last babel problem with array iterator

### ISSUE THREAD

**Issue by simonjoom** [babel/babel#10508]
babel transpile this:

```
[...Array(4).keys()].map(i =>{
        console.log("count",i) // expected output: 0 1 2
});
```
to

```
[].concat(Array(4).keys()).map(function (i) {
    console.log("count",i); // give output: undefined
})
```
the "count" give undefined after babel.

easy to see the output directly on
https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=true&loose=true&code_lz=NoOjEECdIQwTwBQBYCUIDWBTOBnBKBdIA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cenv&prettier=false&targets=Node-8.9&version=7.6.2&externalPlugins=

https://github.com/nathanreyes/v-calendar/issues/434#issue-499844702

**Comment by simonjoom** [comment]
> babel transpile this:
> 
> ```
> [...Array(4).keys()].map(i =>{
>         console.log("count",i) // expected output: 0 1 2
> });
> ```
> 
> to
> 
> ```
> [].concat(Array(4).keys()).map(function (i) {
>     console.log("count",i); // give output: undefined
> })
> ```
> 
> the "count" give undefined after babel.
> 
> easy to see the output directly on
> https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=true&loose=true&code_lz=NoOjEECdIQwTwBQBYCUIDWBTOBnBKBdIA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cenv&prettier=false&targets=Node-8.9&version=7.6.2&externalPlugins=

https://github.com/nathanreyes/v-calendar/issues/434#issue-499844702

**Comment by loganfsmyth** [comment]
When you use `loose: true`, you are opting out of the ability to use iterable types with spread syntax.

You'll either need to do
```
Array.from(Array(4).keys()).map(i =>{
```
or disable loose mode.

**Comment by simonjoom** [comment]
ah ok thks
