### ISSUE TITLE
[Typescript Plugin]: Enum is not initialized properly when value references another string enum case

### ISSUE THREAD

**Issue by jdeff** [babel/babel#10510]
## Bug Report

**Current Behavior**
When the value of an enum case references a string case on another enum an unexpected extra key is added to the compiled javascript object. This is especially apparent when the case names do not match.

**Input Code**
https://bit.ly/2nRTcds

```ts
enum Foo {
  foo = "foo"
}

enum Baz {
  baz = Foo.foo
}
```

**Expected behavior/code**
With the code above, I would expect a javascript object that contained one key, "baz", with the value "foo". Instead, "Baz" has two keys, "baz", "foo", with the values, "foo" and "baz" respectively. This does not match what the Typescript compiler produces: https://bit.ly/2nbliQX

**Babel Configuration (.babelrc, package.json, cli command)**

No special configuration. See the babel REPL link above for the full configuration.

**Environment**
- Babel version(s): v7.6.2
- Node/npm version: NA
- OS: NA
- Monorepo: no
- How you are using Babel: repl

**Comment by jdeff** [comment]
It looks like the issue could be fixed somewhere around `isStringLiteral` in [enum.js](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/src/enum.js#L80). Since `isStringLiteral` doesn't detect Foo.foo as a literal string, it uses the `buildNumericAssignment` template. We should probably translate `Foo.foo` to its literal value, "foo".

**Comment by JLHwung** [comment]
Hi Jayme, thank you for submitting this issue, unfortunately it duplicates #10497 and I would suggest we can discuss possible solution there.

**Comment by jdeff** [comment]
Ah! Perfect thanks for pointing me to that.
