### ISSUE TITLE
Source map is changed when re-running babel with no transforms.

### ISSUE THREAD

**Issue by coreyfarrell** [babel/babel#10518]
## Bug Report

**Current Behavior**
Running no transform on babel output changes the source-map.

**Input Code**

```js
'use strict';

const {transformSync} = require('@babel/core');

const source = `console.log('minimum test');`;
const baseConfig = {
  babelrc: false,
  configFile: false,
  filename: 'test.js',
  sourceMaps: true
};

const result1 = transformSync(source, baseConfig);
const result2 = transformSync(result1.code, Object.assign({inputSourceMap: result1.map}, baseConfig));

console.log(source === result1.code && source === result2.code ? 'Code is identical' : 'Code is changed');
console.log('\nresult1.map:', result1.map);
console.log('\nresult2.map:', result2.map);
```

**Expected behavior/code**
result1.map should deeply equal result2.map.

**Environment**
- Babel version(s): 7.6.2
- Node/npm version: node 12.11.0, npm 6.11.3
- OS: Fedora 30
- Monorepo: no
- How you are using Babel: API

**Additional context/Screenshots**

result1.map:
```js
{
  version: 3,
  sources: [ 'test.js' ],
  names: [ 'console', 'log' ],
  mappings: 'AAAAA,OAAO,CAACC,GAAR,CAAY,cAAZ',
  sourcesContent: [ "console.log('minimum test');" ]
}
```

result2.map:
```js
{
  version: 3,
  sources: [ 'test.js' ],
  names: [ 'console' ],
  mappings: 'AAAAA,OAAO,CAAPA,GAAAA,CAAAA,cAAAA',
  sourcesContent: [ "console.log('minimum test');" ]
}
```

This does seem to result in a loss of resolution in the source-map.  See visualization of [result1](https://sokra.github.io/source-map-visualization/#base64,Y29uc29sZS5sb2coJ21pbmltdW0gdGVzdCcpOwovKiBiYXNlNjQgc291cmNlIG1hcCByZW1vdmVkICov,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QuanMiXSwibmFtZXMiOlsiY29uc29sZSIsImxvZyJdLCJtYXBwaW5ncyI6IkFBQUFBLE9BQU8sQ0FBQ0MsR0FBUixDQUFZLGNBQVoiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zb2xlLmxvZygnbWluaW11bSB0ZXN0Jyk7Il0sImZpbGUiOiJleGFtcGxlLmpzIn0=,Y29uc29sZS5sb2coJ21pbmltdW0gdGVzdCcpOw==) compared to [result2](https://sokra.github.io/source-map-visualization/#base64,Y29uc29sZS5sb2coJ21pbmltdW0gdGVzdCcpOwovKiBiYXNlNjQgc291cmNlIG1hcCByZW1vdmVkICov,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QuanMiXSwibmFtZXMiOlsiY29uc29sZSJdLCJtYXBwaW5ncyI6IkFBQUFBLE9BQU8sQ0FBUEEsR0FBQUEsQ0FBQUEsY0FBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zb2xlLmxvZygnbWluaW11bSB0ZXN0Jyk7Il0sImZpbGUiOiJleGFtcGxlLmpzIn0=,Y29uc29sZS5sb2coJ21pbmltdW0gdGVzdCcpOw==) - hovering over parts of the generated/original source will highlight what is associated from the other source.

**Comment by liuxingbaoyu** [comment]
The problem of corrupted output source maps seems to be gone in the latest version.
It is expected that input and output source maps and code are not exactly equal, babel is based on AST and cannot preserve all formatting.
