### ISSUE TITLE
preset-typescript + decorator on abstract base class overwrites members with undefined

### ISSUE THREAD

**Issue by justinwilaby** [babel/babel#10514]
## Bug Report

**Current Behavior**
Decorating an abstract base class causes implementors to have `undefined` function refs even though the function is implemented.

Given this scenario: 
```js
abstract class A {

  @decorate()
  private decoratedMember: boolean

  protected abstract myMethod(): void
}

class B extends A {
  private config: any;

  constructor(config: any) {
    super();
    this.config = config;
  }

  public runMyMethod(): void {
    this.myMethod(); // <--- Error: undefined is not a function
  }

  protected myMethod(): void {
   // Do stuff
  }
}

const b = new B();
b.runMyMethod();
```

**Expected behavior/code**
Base class definitions should not initialize abstract methods to `void 0` when decorators are used. This will allow implementors of abstract classes that use decorators to properly define concrete functions. 

**Babel Configuration **
.babelrc

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "electron": "6"
        }
      }
    ],
    "@babel/preset-typescript"
  ],
  "ignore": ["**/*.d.ts"],
  "plugins": [
    "@babel/plugin-transform-react-jsx",
    [
      "@babel/plugin-proposal-decorators",
      {
        "decoratorsBeforeExport": true
      }
    ],
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime"
  ]
}
```

**Environment**
- Babel version(s): 7.5.5
- Node/npm version: 12.7
- OS:  OSX 10.14.6
- Monorepo: lerna
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
Note that TypeScript 3.7 will align with Babel's behaviour of initializing class fields to undefined.

**Comment by justinwilaby** [comment]
@nicolo-ribaudo - This defect is not related to class fields but rather class functions. 

If I defined a base class (` class A`) with an empty abstract method and then decorate any class field, all classes that extends the base (`class B`) will have `undefined` for the abstract method even when that method is implemented by the subclass. If I remove the decorator, everything works as expected. 

It seems the `_decorate` helper is overwriting the baseclass prototype.

**Comment by nicolo-ribaudo** [comment]
Oh I initially misunderstood the bug :+1:

**Comment by emilio-martinez** [comment]
I just ran into this issue as well. As described above, abstract methods get lost upon extending. Is there a workaround somebody's found for this? At least while this bug is triaged, which seems to have been pending for a while.

**Comment by oliverdunk** [comment]
Happy to take this one ✋

**Comment by tpluscode** [comment]
Bugger, I just wasted several hours looking for the problem in all the wrong places.

This has not been released yet, has it?

Is there any workaround?

**Comment by tpluscode** [comment]
No, wait, I assumed that it would be enough to install the latest typescript present. 

I updated `@babel/helper-create-class-features-plugin` to the latest (7.9.5) but it's still setting undefined to my abstract methods 😞

**Comment by nicolo-ribaudo** [comment]
What does `npx nls why @babel/helper-create-class-features-plugin` log?

**Comment by tpluscode** [comment]
```
  Who required @babel/helper-create-class-features-plugin:

  alcaeus > @babel/helper-create-class-features-plugin@7.9.5
  alcaeus > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.9.5
  alcaeus > @babel/plugin-proposal-decorators > @babel/helper-create-class-features-plugin@7.9.5
  alcaeus > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.9.5
```
