### ISSUE TITLE
TypeScript assertion signatures

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#10527]
TypeScript 3.7 will support an `asserts Identifier is Type` syntax in function annotation positions (much like with type predicates).

```ts
declare function assertIsFoo(x): asserts x is Foo;

function assertIsDefined<T>(x: T): asserts x is NonNullable<T> {
    if (x == null) throw "oh no";
}
```

See more at the original pull request: https://github.com/microsoft/TypeScript/pull/32695

**Comment by nicolo-ribaudo** [comment]
Will it be released in 3.7?

**Comment by tanhauhau** [comment]
anyone working on this? can I work on this issue?

**Comment by nicolo-ribaudo** [comment]
Yes :+1:

**Comment by DanielRosenwasser** [comment]
> Will it be released in 3.7?

Yes!

**Comment by DanielRosenwasser** [comment]
For the record, the grammar is something like

`asserts` <sub>\[No *LineTerminator* here]</sub> *Identifier* `is` *Type*

**Comment by thorn0** [comment]
@DanielRosenwasser A question about the grammar. The place of `Identifier` can be also be taken by `this`, right?
