### ISSUE TITLE
runtime helpers could not be resolved

### ISSUE THREAD

**Issue by blackstormx** [babel/babel#10528]
## Bug Report

**Current Behavior**
During build, I am getting errors:
```
'@babel/runtime/helpers/classCallCheck' is imported by **, but could not be resolved – treating it as an external dependency
'@babel/runtime/helpers/toConsumableArray' ... couldn't be resolved
'@babel/runtime/regenerator' ... couldn't be resolved
...
```
etc...
My package .json:
```
  "dependencies": {
    "@babel/core": "^7.6.2",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/polyfill": "^7.6.0",
    "@babel/runtime": "^7.6.2",
    "core-js": "^3.2.1",
    "rollup": "^1.23.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.6.2",
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@babel/plugin-external-helpers": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "@babel/preset-es2015": "^7.0.0-beta.53",
    "rollup-plugin-babel": "^4.3.3"
  }
```

And a part of a build script:
```
  .then(bundle => {
    bundle
      .generate({
        format: "iife",
        name: "mainModule"
      })
      .then(function(result) {
        require("fs").writeFileSync(
          "./_jsBuild/bundle.js",
          result.output[0].code
        );
      });
```
if I disable @babel/transform-runtime plug-in, and manually write this: 
`import { _classCallCheck } from "../node_modules/@babel/runtime/helpers/classCallCheck.js";
`
Into my source code, it still doesn't work. Same error.  

Also I am using rollup as you probably noticed for bundling my source files together, but I doubt that it's rollup's problem.

Should I take out files from /runtime and put them into my src folder and import them as modules in my main js file?

OS: windows 10

My file structure: 
----node_modules
----jsBuild
-------bundle.js
----jsSrc
-------main.js(main src file)
-------modules
----------module1
----------module2
----------....
----tools
-------build.js (I use it to bundle and transpile files using babel and rollup)

**Comment by nicolo-ribaudo** [comment]
> if I disable @babel/transform-runtime plug-in, and manually write this:
> `import { _classCallCheck } from "../node_modules/@babel/runtime/helpers/classCallCheck.js"; `
> Into my source code, it still doesn't work. Same error.

This makes me think that this problem is not actually related to Babel :thinking: 
Does that file exist in your node_modules?

**Comment by blackstormx** [comment]
Yes they all do. Here is the picture:
https://imgur.com/a/RFBPZAi

**Comment by blackstormx** [comment]
I found out its actually a rollup-babel plugin issue. 
If anybody is down for helping I posted here: https://github.com/rollup/rollup-plugin-babel/issues/330
