### ISSUE TITLE
Feature Request: a flag to print the current config

### ISSUE THREAD

**Issue by ianstormtaylor** [babel/babel#10538]
There doesn't appear to be an easy way to know which config settings Babel is using when processing your file. This is kind of insane given that Babel is known for being such a huge headache to configure, and I'd bet that the majority of the issues opened in this repository are likely frustrating misconfiguration issues.

It seems like…

- https://github.com/babel/babel/issues/2960 was opened in 2015, but then closed at some point and no one noticed?
- https://github.com/babel/babel/pull/4806 was submitted in 2016, and got reviewed but fell through the cracks again?
- https://github.com/babel/babel/issues/6856 was opened in 2017, but seems to have gone dormant too?
- https://github.com/babel/babel/pull/7201 was submitted in 2018, with a few comments but never got to the goal?

Please add this! I know it will make my life using Babel easier, instead of incredibly frustrating. And I feel like it will probably drastically reduce the number of issues you get, making your lives easier too. 😉 

TypeScript has solved this nicely with their `--showConfig` flag:

```bash
$ tsc --emitDeclarationOnly --declarationMap --outDir ./lib --showConfig
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "declaration": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "sourceMap": true,
        "strict": true,
        "suppressImplicitAnyIndexErrors": true,
        "target": "esnext",
        "emitDeclarationOnly": true,
        "declarationMap": true,
        "outDir": "./lib"
    },
    "files": [
        "./src/index.ts"
    ],
    "include": [
        "./src/**/*.ts"
    ]
}
```

And it's the first thing I use when I can't figure out why something is not compiling as expected.

**Comment by hzoo** [comment]
Thanks for bringing this up again! Yeah we definitely should work on this. The earlier PRs are only showing various internal options and specifically things like plugins/presets which I don't know is that helpful.

It's a little more complicated than that given you can have multiple configs, and different configs for different files/folders. Might be best to start with listing out where configs are located.
