### ISSUE TITLE
Top level comments are always kept at the top of the module.

### ISSUE THREAD

**Issue by fpipita** [babel/babel#1053]
Hi,

I've got into this use case:

```javascript
/* @ngAnnotate */
function foo(someDependency) {
  
}

export default foo;
```

the transpiled code looks like:

```javascript
/* @ngAnnotate */
"use strict";

function foo(someDependency) {}

module.exports = foo;
```

with the comment kept at the top of the module, `ng-annotate` cannot correctly annotate `foo`.
Is this the expected behavior?

I would expect it to be transpiled to:

```javascript
"use strict";

/* @ngAnnotate */
function foo(someDependency) {}

module.exports = foo;
```

which is something I can achieve by putting the `'use strict';` directive at the top of the module:

```javascript
'use strict';

/* @ngAnnotate */
function foo(someDependency) {
  
}

export default foo;
```
Thank you!

**Comment by thejameskyle** [comment]
heh, can't please everyone #1030

**Comment by sebmck** [comment]
Feel free to express your concerns in #1030.
