### ISSUE TITLE
Add OR (|) to packages for clear console

### ISSUE THREAD

**Issue by popuguytheparrot** [babel/babel#10537]
## Feature Request
Hey. Always, when i start install modules, i see in terminal this warning. I checked packages and saw peerDeps only use bridge version.
``` json
"peerDependencies": {
    "@babel/core": "^7.0.0-0"
  },
```
![image](https://user-images.githubusercontent.com/19804652/66666580-9b1b1a80-ec59-11e9-80d9-dfdf9bce18e2.png)

Can use | for peerDeps? Like "@babel/core": "^7.0.0-0 | ^7.0.0 " to remove warning ?

**Comment by nicolo-ribaudo** [comment]
It should already work: you can try putting `@babel/core` and `^7.0.0-0` 
in https://semver.npmjs.com/

**Comment by popuguytheparrot** [comment]
@nicolo-ribaudo 
nothing
![image](https://user-images.githubusercontent.com/19804652/66698587-df54fc00-ece7-11e9-8fa3-9a85184eb835.png)
