### ISSUE TITLE
some option allow keep trailing commas in generator or transformFromAst

### ISSUE THREAD

**Issue by baocang** [babel/babel#10540]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue when i create an ast with code like below:
```javascript
const a ={
  b:1,
  c:2,
};
```
After generate code from the AST via @babel/generator or @babel/core/transformFromAst, I get the flow code:
```javascript
const a = {
  b: 1,
  c: 2
};
```
In the real world, I created an AST by my visual code generate tool, and the code also can be modified by the tool and programer also can modify the code.
The problem is when I generate new property for object a, without trailing commas I will get two lines of change.
**Describe the solution you'd like**
Can babel add some option allow keep trailing commas in generator or transformFromAst

**Comment by nicolo-ribaudo** [comment]
`@babel/generator`'s output isn't meant to be developer-friendly.
Sure, we try to keep it as readable as possible, but we give precedence to speed and predictability.

If your generated code is meant to be consumed by humans (and not by machines), I suggest using `prettier` to convert the AST to a nice-looking source code.

**Comment by baocang** [comment]
👌，I will format code with prettier, add this step and it won't be too much trouble.
