### ISSUE TITLE
Generated code by preset-env causes error on Node.js v12 and ES Modules

### ISSUE THREAD

**Issue by shimataro** [babel/babel#10548]
## Bug Report

**Current Behavior**
```bash
$ node --experimental-modules dist/example.mjs
(node:5693) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:79
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /path/to/example/node_modules/core-js/modules/es.array.iterator imported from /path/to/example/dist/example.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:79:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:152:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Input Code**

`src/example.mjs` (source code)

```javascript
for (const x of [1, 2, 3]) {
  console.log(x);
}
```

`dist/example.mjs` (generated code)

```javascript
import "core-js/modules/es.array.iterator";

for (const x of [1, 2, 3]) {
  console.log(x);
}
```

**Expected behavior/code**
```bash
node --experimental-modules dist/example.mjs
(node:5717) ExperimentalWarning: The ESM module loader is experimental.
1
2
3
```

**Babel Configuration (.babelrc, package.json, cli command)**

```json
[
  "@babel/preset-env",
  {
    "targets": {
      "node": "8.5.0"
    },
    "useBuiltIns": "usage",
    "corejs": 3,
    "modules": false
  }
]
```

**Environment**
- Babel version(s): 7.6.4
- Node/npm version: Node v12.11.1/npm 6.11.3
- OS: Ubuntu 18.04
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
Could you add `.js` extension when importing polyfill?

```javascript
import "core-js/modules/es.array.iterator.js"; // needs ".js"

for (const x of [1, 2, 3]) {
  console.log(x);
}
```

Now, it will work properly!

```bash
$ node --experimental-modules dist/example.mjs
(node:5705) ExperimentalWarning: The ESM module loader is experimental.
1
2
3
```

**Additional context/Screenshots**
As of Node.js v12, [extension requires on `import` syntax](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff).

**Comment by JLHwung** [comment]
Although ESM requires explicit file extensions, you can always specify `--es-module-specifier-resolution=node` to restore CommonJS extension resolution:
```js
node --experimental-modules --es-module-specifier-resolution=node dist/example.mjs
```

**Comment by shimataro** [comment]
@JLHwung 
Thank you for your comment.

Yes, I'm using this option for now. But I think it's a makeshift, not a smart solution.

Since v12 and ESM will be standard in the near future, I think it's better to work by default, not to specify `--es-module-specifier-resolution=node`.
