### ISSUE TITLE
@babel/plugin-transform-runtime do not work well

### ISSUE THREAD

**Issue by codetker** [babel/babel#10562]
## Bug Report

**Current Behavior**
While using @babel/plugin-syntax-dynamic-import in babel.config.js, I got an error in my project 
![image](https://user-images.githubusercontent.com/9033585/66900398-50214e80-f02f-11e9-9ba6-5925386fd2eb.png)
But I did have installed @babel/plugin-syntax-dynamic-import@7.2.0. It made me confused.
Then I tried to use the old version babel-plugin-dynamic-import-webpack@1.1.0 and it worked.I guess there may be something wrong with @babel/plugin-transform-runtime.

**Expected behavior/code**
No error

**Environment**
- Babel version(s): 7.6.4
- Node/npm version: Node 12.10.0/npm 6.11.3
- OS: OSX 10.14.6
- Monorepo: no
- How you are using Babel: loader
all node_modules are latest

**Possible Solution**
Check the diffrence between @babel/plugin-transform-runtime and babel-plugin-dynamic-import-webpack

**Comment by JLHwung** [comment]
Could you attach the babel configuration?
