### ISSUE TITLE
Utility variables and "use strict" are placed outside of file-wrapping IIFE

### ISSUE THREAD

**Issue by Mosho1** [babel/babel#1056]
For example, the classes [example](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=(function()%20%7B%0A%20%20class%20SkinnedMesh%20extends%20THREE.Mesh%20%7B%0A%20%20constructor(geometry%2C%20materials)%20%7B%0A%20%20%20%20super(geometry%2C%20materials)%3B%0A%0A%20%20%20%20this.idMatrix%20%3D%20SkinnedMesh.defaultMatrix()%3B%0A%20%20%20%20this.bones%20%3D%20%5B%5D%3B%0A%20%20%20%20this.boneMatrices%20%3D%20%5B%5D%3B%0A%20%20%7D%0A%20%20update(camera)%20%7B%0A%20%20%20%20super.update()%3B%0A%20%20%7D%0A%20%20static%20defaultMatrix()%20%7B%0A%20%20%20%20return%20new%20THREE.Matrix4()%3B%0A%20%20%7D%0A%7D%0A%7D)) from "Learn ES6". I would expect the transpiler to respect the IIFE and not place those in the global scope.

**Comment by sebmck** [comment]
Similiar discussion in #1049. Babel assumes that you pass it a module, not a script.
