### ISSUE TITLE
babel transfrom runtime incompatible with url loader

### ISSUE THREAD

**Issue by samMeow** [babel/babel#10561]
## Bug Report

**Current Behavior**
Babel dynamic import `_interopRequireWildcard` function fail if imported obj/ modules is pure string (e.g. base64 encoded image), because cache (WeakMap) doesn't accept string as key (only accept object).

**Input Code**
Ref: https://github.com/babel/babel/pull/10161 

**Expected behavior/code**
`_interopRequireWildcard` should take care string module (url-loader/file-loader) also.

**Environment**
- @babel/core": "^7.6.4"
- node 10.15
- @babel/plugin-transform-runtime: 7.6.2
- url-loader : ^2.2.0

**Possible Solution**
 Consider a different cache mechanism (e.g. Map/ no cache for string)

![Screenshot 2019-10-16 at 2 15 17 PM](https://user-images.githubusercontent.com/9334075/66893370-84414300-f020-11e9-9edd-35ff485de98b.png)

**Comment by nicolo-ribaudo** [comment]
If you are using webpack you shouldn't transpile modules: it will just lead to a less optimized output.

**Comment by samMeow** [comment]
Thanks for quick response. If the direction is to only cache object, we can simply return at the top?
`if (typeof obj !== 'object') return obj` and skip those cache part?

**Comment by nicolo-ribaudo** [comment]
Good idea, it can be added to the condition of the first if statement.

**Comment by theKashey** [comment]
> Yeah, but it should return { default: obj } instead.

Why?
