### ISSUE TITLE
 Can't resolve '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by code-mattclaffey** [babel/babel#10584]
## Bug Report
I am working in a project that uses composer for its packages and I found a strange error where the module that I had in composer was searching for @babel/runtime in the root of the project and not within the scope of the composer module. When I try to import a js module in my entry file I get the following error:

```
Can't resolve '@babel/runtime/helpers/interopRequireDefault' in '/Users/mattclaffey/src/project/app/code/ThemeName/Theme/view/frontend/web/js/src'
 @ /Users/mattclaffey/src/project/app/code/ThemeName/Theme/view/frontend/web/js/src/index.entry.js 3:29-84
```

The project setup is like so:

```
frontend.config.js
composer
  - magento2-frontools
     - webpack.config.js 
     - babel.config.js // required into webpack
```

code to replicate:

```js
import module from './index2'; // just returns a function that says hello world
console.log('Hello World');

const test = 'Test';

module();
```

Is this a bug with the package or am I implementing it in the wrong manner.

## My NPM Packages
```
    "@babel/runtime": "^7.6.3",
    "babel-preset-env": "~1.2.1",
    "@babel/core": "^7.6.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.6.2",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.6.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.6.3",
```

**Environment**
- Node/npm version: 10.15
- OS: OSX
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**
I fixed it by npm init and installing the babel runtime in the project level but it should be scoped to the package that is using it and not the project.

**Comment by JLHwung** [comment]
Sorry for being brief, please see https://github.com/babel/babel-loader/issues/812#issuecomment-544635996

**Comment by code-mattclaffey** [comment]
I tried that and the cwd() is pointing to the right place

**Comment by JLHwung** [comment]
> /Users/mattclaffey/src/project/app/code/ThemeName/Theme/view/frontend/web/js/src

Where does `node_modules` reside? It should be in one of the parent folder chains of the path above.

**Comment by code-mattclaffey** [comment]
It lives in the composer/magento2-frontools folder.

**Comment by JLHwung** [comment]
`@babel/runtime` is a production dependency and it will ship with your production code. So it should be installed at one of `node_modules`
e.g.
```
/Users/mattclaffey/src/project/app/code/ThemeName/Theme/view/frontend/web/js/node_modules
```
or
```
/Users/mattclaffey/src/project/app/code/node_modules
```
so that your source code could resolve against. It won't be resolved by `webpack` if it is in `composer/magento2-frontools`.

**Comment by code-mattclaffey** [comment]
I think this is just issues with it being a composer package and not an npm one. I am not allowed to change it to being one at my work because its full of PHP devs vs one FE dev. Going to close this issue for now.
