### ISSUE TITLE
Array spread doesn't work correctly.

### ISSUE THREAD

**Issue by rev-hikari** [babel/babel#10586]
## Bug Report

**Input Code**

[REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhgJwQRhgXhgbQHS4IJJwCeAFAEwCUAugFCiSyIJnowELHkUDcd408JAGZWOXEzJVuQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.6.4&externalPlugins=)

```js
const arr1 = [...Array(2)]
const arr2 = Array(2);
const arr3 = [...arr2];
```

**Current Behavior**

```js
var arr1 = _toConsumableArray(Array(2)); // [undefined, undefined]
var arr2 = Array(2); // [empty × 2]
var arr3 = [].concat(arr2); // [empty × 2]
```

**Expected behavior/code**

```js
var arr1 = _toConsumableArray(Array(2)); // [undefined, undefined]
var arr2 = Array(2); // [empty × 2]
var arr3 = _toConsumableArray(arr2); // [undefined, undefined]
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env"]
}
```

**Environment**

- Babel version(s): v7.6.4

**Comment by JLHwung** [comment]
Closing it as duplicates of #7258.
