### ISSUE TITLE
Support Interop Rewire

### ISSUE THREAD

**Issue by KenPowers** [babel/babel#1058]
I haven't decided what the syntax should look like yet, but I think it would be cool to support [rewire](https://github.com/jhnns/rewire) using the `import` syntax.

Obviously this isn't an ES6 feature, so I was thinking something along the lines of letting users define their own `_interopRequire` functions.

**Comment by sebmck** [comment]
You can already supply a custom module resolver:

> `resolveModuleSource	`null`	Resolve a module source ie. `import "SOURCE";` to a custom value. Called as `resolveModuleSource(source, filename)`.

http://babeljs.io/docs/usage/options/

Is this no adequate and more suitable?

**Comment by KenPowers** [comment]
Hmm. That looks like something I could work with. I probably could have looked harder, just did a quick search for interop in the docs and rewire in the issues to see if anybody had tried it before.

Thank ya kindly.
