### ISSUE TITLE
Error evaluating async computed property: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wendt88** [babel/babel#10587]
## Bug Report

**Current Behavior**
wrong code in webpack build after `@babel/preset-env` update

**Input Code**
```js
class Test1 {
    constructor () {
    }

    setDefinition () {
    }
}

class Test2 extends Test1 {
    constructor (definition) {
        super();
        this.definition(definition);
    }

    async setDefinition (definition) {
        /* some async code */
        super.setDefinition(definition);
    }
}

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

babel.config.js
```js
module.exports = (api) => {
    api.cache(true);
    return {
        presets: [
            ['@babel/env', { targets: { esmodules: true } }]
        ]
    };
};
```

**Environment**
- Babel version(s): broken after `@babel/preset-env` `7.3.1`
- Node/npm version: Node 12
- OS: Windows 10
- How you are using Babel: `loader` via `webpack`

**Code output:**
```js
class Test2 extends _test1__WEBPACK_IMPORTED_MODULE_0__["default"] {
  constructor(definition) {
    super();
    this.setDefinition(definition);
  }
  setDefinition(definition) {
    var _this = this,
        _superprop_callSetDefinition = function _superprop_callSetDefinition() {
      return _superprop_callSetDefinition(...arguments);
    };
    /* the async code */
    _superprop_callSetDefinition(definition);
}
```

iside setDefinition gets defined a function `_superprop_callSetDefinition`  that calls itself

**Comment by nicolo-ribaudo** [comment]
Fixed by #9939 (it will be in the next release)
