### ISSUE TITLE
Syntax error on static/constructor properties

### ISSUE THREAD

**Issue by berwyn** [babel/babel#1059]
I have a case where I'm trying to use static properties in a class, and Babel raises a syntax error on the assignment. Test case:

```javascript
class Foo {
  static bar = {};
  static baz = [];
}
```

The error in question is raised on parse.js:60 (installed via npm) with an unexpected token on the assignment operator.

According to [the ECMA wiki](http://wiki.ecmascript.org/doku.php?id=harmony:classes), this should be valid. Thoughts?

**Comment by zloirock** [comment]
[It's not valid ES6 syntax](http://www.2ality.com/2015/02/es6-classes-final.html), but available in babel with [playground flag](http://goo.gl/jQI0Np). Maybe it will be added in ES7.

**Comment by fatuhoku** [comment]
The question is, how are static values supposed to be written?!

**Comment by sebmck** [comment]
@fatuhoku https://babeljs.io/blog/2015/03/31/5.0.0/#stage-0-class-properties
