### ISSUE TITLE
All `js` files minified when `mode` = `production`

### ISSUE THREAD

**Issue by Flcwl** [babel/babel#10602]
**I'm submitting a docbug report**

**Webpack Version:**
4.22.0

**Babel Core Version**:
6.26.3

**Babel Loader Version**:
7.1.5

**Please tell us about your environment:**
OSX 10.14.6 

**Current behavior:**
When the webpack `mode` is set to `production`, the `*.js` files passed through the babel-loader are compressed (Maybe `minified` set `true` when productionMode).

**Expected/desired behavior:**
According to the [documentation](https://babeljs.io/docs/en/options#minified), the attribute `minified` should always be `false`.

> **minified**
> Type: `boolean`
> Default: `false`
> 
> Includes `compact: true`, omits block-end semicolons, omits `()` from `new Foo()` when possible, and may output shorter versions of literals.

**Comment by nicolo-ribaudo** [comment]
`mode: production` enable the Terser plugin ([webpack docs](https://webpack.js.org/configuration/mode/)), which is a minified. You should disable it.

**Comment by Flcwl** [comment]
very thx. the webpack has so much default "behavior", not feel good.
