### ISSUE TITLE
@babel/preset-typescript doesn't appear to support generic functions

### ISSUE THREAD

**Issue by bsmith-cycorp** [babel/babel#10605]
## Bug Report

**Current Behavior**
Even the simplest example of a generic function, taken straight from the TypeScript docs, fails to parse. 

**Input Code**
https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKAQwCcBzALkXwEpb9EBvAKEU8XLShHKQVKAbjYBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.6.4&externalPlugins=

```js
function identity<T>(arg: T): T {
    return arg;
}
```
```
/repl: Unexpected token, expected "(" (1:17)

> 1 | function identity<T>(arg: T): T {
    |                  ^
  2 |     return arg;
  3 | }
```

**Expected behavior/code**
This was taken from the TypeScript docs here: https://www.typescriptlang.org/docs/handbook/generics.html

**Babel Configuration (.babelrc, package.json, cli command)**
(included in Babel REPL link)

**Environment**
(included in Babel REPL link)

**Additional context/Screenshots**
Unsurprisingly, the same problem seemed to happen with generic arrow functions.

**Comment by nicolo-ribaudo** [comment]
It's a big with the repl. You can use the bottom section in the sidebar to load `@babel/plugin-transform-typescript`.

**Comment by bsmith-cycorp** [comment]
That does appear to solve this exact case, although I got to this case via a problem with a more syntactically-complicated function I had in my own code. Let me see if I can reproduce that one.

**Comment by bsmith-cycorp** [comment]
Hmm. It seems to be an independent issue, and I can't reproduce it in the babel playground but I still see it in my own environment.

Here's the code:
```
const queryAndCheck = <T extends JSONValue>(predicate: (val: JSONValue|void) => boolean) => (value: JSONValue, path: Array<string>|string|void): T|void => {
  let val = query(value, path);
  if(predicate(val)) {
    return val as T;
  } else {
    return undefined;
  }
}
```

Here's the error (absolute paths scrubbed):
```
ERROR in .../jsonQuery.ts
Module build failed (from .../node_modules/babel-loader/lib/index.js):
SyntaxError: .../jsonQuery.ts: Unexpected reserved word 'let' (29:2)

  27 |  */
  28 | const queryAndCheck = <T extends JSONValue>(predicate: (val: JSONValue|void) => boolean) => (value: JSONValue, path: Array<string>|string|void): T|void => {
> 29 |   let val = query(value, path);
     |   ^
  30 |   if(predicate(val)) {
  31 |     return val as T;
  32 |   } else {
    at Object.raise (.../node_modules/@babel/parser/lib/index.js:6420:17)
    at Object.checkReservedWord (.../node_modules/@babel/parser/lib/index.js:9732:12)
    at Object.parseIdentifierName (.../node_modules/@babel/parser/lib/index.js:9697:12)
```

And here's the babel config:
```
    {
      "test": ["./src/**/*.ts"],
      "presets": [
        "@babel/preset-react",
        "@babel/preset-typescript",
        ["@babel/preset-env", {
          "targets": {
            "browsers": [ "last 2 Chrome versions, last 2 Firefox versions" ]
          },
          "modules": false
        }]
      ],
      "plugins": [
        ["@babel/plugin-proposal-decorators", {
          "legacy": true
        }],
        ["@babel/plugin-proposal-class-properties", {
          "loose": true
        }],
        "@babel/plugin-proposal-do-expressions",
        "@babel/plugin-proposal-export-default-from",
        "@babel/plugin-proposal-export-namespace-from",
        "@babel/plugin-proposal-function-bind",
        "@babel/plugin-proposal-function-sent",
        "@babel/plugin-proposal-json-strings",
        "@babel/plugin-proposal-logical-assignment-operators",
        "@babel/plugin-proposal-nullish-coalescing-operator",
        "@babel/plugin-proposal-numeric-separator",
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-optional-chaining",
        ["@babel/plugin-proposal-pipeline-operator", {
          "proposal": "minimal"
        }],
        "@babel/plugin-proposal-throw-expressions",
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-syntax-import-meta"
      ]
    }
```

**Comment by bsmith-cycorp** [comment]
Further details: It seems to have problems with both `as Foo` and `extends Bar`. If I remove both of those, it's happy. If either is there, it fails to parse. All other simplifications seem to have no effect on the problem.

**Comment by bsmith-cycorp** [comment]
Also, I know this should be valid TypeScript because it shows no issues in VSCode on TSC 3.6.3 or 3.7.1-rc

**Comment by basarat** [comment]
Experiencing this outside of the playground, with nextjs 9 (comes with babel / TypeScript configured out of the box). The input code provided (https://github.com/babel/babel/issues/10605#issue-512126194) gives an error `Module parse failed: Unexpected token` :rose:

**Comment by nicolo-ribaudo** [comment]
@bsmith-cycorp Can you also provide the first 26 lines of that file?

**Comment by bsmith-cycorp** [comment]
```javascript
import { JSONValue, JSONObject, JSONArray } from 'lib/js/types/Misc';

function query(value: JSONValue, path?: Array<string>|string|void): JSONValue|void {
  let currentValue = value;
  path = typeof path === 'string' ? path.split('.') : path;

  if(path) {
    for(let key of path) {
      if(currentValue != null && typeof currentValue === 'object') {
        currentValue = currentValue[key];
      } else {
        return undefined;
      }
    }
  }
  
  return currentValue;
}
```

**Comment by bsmith-cycorp** [comment]
(there are some comments that I left out)

**Comment by nicolo-ribaudo** [comment]
Thanks!
Also, what does `npx nls why @babel/parser` log?

**Comment by bsmith-cycorp** [comment]
That exact command just says:
```
npx: installed 28 in 2.195s
```

**Comment by bsmith-cycorp** [comment]
Strangely, because `@babel/parser` is in my node_modules but isn't in my package.json

**Comment by nicolo-ribaudo** [comment]
It doesn't log anything else? :thinking: 
It should tell you the exact versions of `@babel/parser` in your dependency tree and why they are there.

**Comment by basarat** [comment]
Ignore what I've said here : https://github.com/babel/babel/issues/10605#issuecomment-546104677 My issue root case was not babel :heart: Bad conincidence that it happened to stumble on this issue right now. My issue was that next doesn't transpile ts files imported outside of its root directory (e.g. a root `shared` folder above the folder containing next src), aka something I can fix in my code :rose:

**Comment by bsmith-cycorp** [comment]
Ah- it could be because I have package.lock disabled.

Here's this:
```
> grep "@babel/parser" node_modules/**/package.json
node_modules/babel-eslint/package.json:    "@babel/parser": "^7.0.0",
node_modules/istanbul-lib-instrument/package.json:    "@babel/parser": "^7.4.3",
node_modules/jsx-ast-utils/package.json:    "@babel/parser": "^7.4.4",
> cat node_modules/@babel/parser/package.json
  ...
  "version": "7.6.4"
}
```

**Comment by bsmith-cycorp** [comment]
Update: this is almost certainly not a problem with typescript. I had my typescript config (above) within an `override` clause which seems not to have been taking effect, because I get the same error when I remove it entirely. We're starting the process of migrating from Flow, which is the non-override configuration, so my guess is that Flow was trying to interpret this code which would explain why it choked on `extends` and `as`.

Thanks for trying to help, and apologies for taking up time with this

**Comment by nicolo-ribaudo** [comment]
Glad you are figuring it out!
