### ISSUE TITLE
TypeScript: "Fake this" in async function being treated as real argument

### ISSUE THREAD

**Issue by mkrause** [babel/babel#10611]
## Bug Report

**Current Behavior**
Given an `async` function, in the following code the ["fake this"](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters) argument seems to be treated as a real argument, causing the argument `param` to be undefined.

**Input Code**

[Link to REPL](https://deploy-preview-2019--babel.netlify.com/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsL3egFMgC1RBgC4YBvAXwBoYAHYAJ2AFsYBeSqgSkoCgYQmFEwh0AGwCmAOgnoA5rkYtWPANz8q_IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&filename=repl.ts&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.6.4&externalPlugins=babel-plugin-transform-class-properties%406.24.1)

```typescript
async function foo(this : {}, param = {}) {
    console.log(param);
}
```

Compiles to:

```js
"use strict";

function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }

function _asyncToGenerator(fn) { return function () { var self = this, args = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(self, args); function _next(value) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); } function _throw(err) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); } _next(undefined); }); }; }

function foo(_x) {
  return _foo.apply(this, arguments);
}

function _foo() {
  _foo = _asyncToGenerator(
  /*#__PURE__*/
  regeneratorRuntime.mark(function _callee() {
    var param,
        _args = arguments;
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            param = _args.length > 1 && _args[1] !== undefined ? _args[1] : {};
            console.log(param);

          case 2:
          case "end":
            return _context.stop();
        }
      }
    }, _callee);
  }));
  return _foo.apply(this, arguments);
}
```

(Notice `param` is being assigned `_args[1]`, rather than ` _args[0]`.)

**Expected behavior/code**
The `this` argument should be ignored.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    presets: [
        '@babel/typescript',
        ['@babel/env', {
            targets: {
                browsers: '>2%, ie 11, safari > 9',
            },
            
            modules: false,
        }],
    ],
    plugins: [
        '@babel/proposal-class-properties',
    ],
}
```

**Environment**
- Babel version(s): v7.6.4
- Node/npm version: Node 12.12/npm 6.11
- OS: macOS v10.14.6
- Monorepo: no
- How you are using Babel: `cli`

**Comment by nicolo-ribaudo** [comment]
Does it work if you give the `typescript` preset an higher precedence?
```json
{
    presets: [
        ['@babel/env', {
            targets: {
                browsers: '>2%, ie 11, safari > 9',
            },
            
            modules: false,
        }],
        '@babel/typescript',
    ],
    plugins: [
        '@babel/proposal-class-properties',
    ],
}
```

**Comment by mkrause** [comment]
@nicolo-ribaudo It does! That fixes the problem for me. Interesting, I thought it already had higher precedence because it was earlier in the list, but apparently it works the other way around.

**Comment by mkrause** [comment]
Should I close this or is this something that should be fixed regardless of the workaround/fix above?

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since curretly there isn't much we can do to make plugins automatically run in the correct order.
We have been trying different time to implement automatic ordering, but there are already different issues tracking it.
