### ISSUE TITLE
RFC: Print Babel Configuration

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#10617]
## Introduction

This document aims to address the requirement of printing babel configuration. The concept of configuration and environment information is clarified. Two new config items are introduced.

There have been multiple issues requesting this feature (#2960, #6856, #10538), of which we shall agree on the popularity and value.

There are two PRs (#4806, #7201) implementing this feature. Both of them were stale due to inactivity or lack of consensus. The scope of #4806 and #7201 are slightly different: the former prints the _resolved configuration_ while the latter prints the config items `plugins` and `presets`. Note that both of them prints babel plugin versions, which should be part of environment information.

Before we propose a solution, we should first clarify the concept of babel configuration and environment information.

## Concept

__Babel Configuration__ is a specific file content and/or user-supplied JavaScript object. Here is an example list: 1) contents of `.babelrc`, 2) contens of `babel` field in `package.json` and 3) the `opt` argument of `babel.transform(code, opt)`. `@babel/core` will process this  configuration lists and merge them into a __resolved configuration__.

__Environment Information__ is an umbrella term includes but is not limited to: versions of the OS, `node`, `npm`; versions of `babel` and its plugins/presets; versions of monorepo tools `lerna`, `yarn workspace`. A list of environment information is required in Babel's bug template to convey the context of this issue.

## Scope

Printing Environment Information is orthogonal to Babel and thus should not be implemented in `@babel/cli`. We have proposed a [`babel` preset](https://github.com/tabrindle/envinfo/pull/126) for `envinfo` and we expect it will soon be installed to issue templates.

In this document we will only address printing babel configs.

## Solution

Add a new config item: `showConfig: boolean`. Its default value is `false`.

This boolean option is an opt-in switch to output configs. The alternative environment variable is considered to use only when `@babel/core` is a transitive dependency or the configuration is not controlled by end user. 

Add a new config item: `showConfigForPath: string`. If it is not specified and `BABEL_SHOW_CONFIG_FOR_PATH` environment variable exists, set `showConfigForPath` to be its value. If this value is not nullish, it will imply that `showConfig` is `true`. When `showConfig` is specified, its default value is assigned from the `filename` transform option.

This option is used to eliminate the ambiguity of configuration chain when multiple babel configurations exist in different paths. Instead of printing all configurations which may be irrelevant, only applicable config with respect to `showConfigForPath` will be printed.

A new `@babel/cli` options `--show-config` is added. Note that `--show-config-for-path` is redundant as it can be inferred from the `path` argument.

When multiple paths are passed in `@babel/cli`, only the first one will be respected.

### Procedure
When loading configuration:

<pre>
if `showConfig` is `true`, compare `options.filename` with `showConfigForPath`:
  if it does not match, continue;
  else 
   a) serialize the applicable configuration descriptor
   b) print to stdout
   c) terminate the process with code 1
</pre>

The last step ensures that 
- the configuration would not be overwhelmed by other logs
- debug feedback is faster than running through the whole process.

### Using `@babel/cli`
```shell
babel src/foo.js --show-config --plugins=@babel/proposal-class-properties,@babel/transform-class
```
Example output:
```
// cli config
{
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/transform-class"
  ],
  "showConfig": true
}

// babel config ./src/.babelrc
{
  "plugins": [
    "lodash"
  ]
}

// babel config ./babel.config.cjs (serialized)
{
  "presets": [
    ["@babel/preset-env", { useBuiltIns: true }]
  ],
  "overrides": [
    { "test": "./src/foo.js", "compact": true }
  ]
}

// babel config ./package.json#babel
{
  "babelrcRoots": [
    ".",
    "./src/*"
  ]
}
```

### Using `webpack` and `babel-loader`

```shell=bash
BABEL_SHOW_CONFIG_FOR_PATH="./src/app.jsx" webpack --config webpack.config.js
```
Example output:
```
// user supplied config (serialized)
{
  "sourceMaps": "inline"
}

// babel config ./babel.config.cjs
{
  "presets": ["@babel/react"]
}
```

### Using `create-react-app`

```shell=bash
BABEL_SHOW_CONFIG_FOR_PATH="./src/app.jsx" react-scripts build
```
Example output:
```
// user supplied config (serialized)
{
  ... babel configuration injected by CRA
}

// babel config ./src/.babelrc.js (serialized)
{
  "plugins": [
    "lodash"
  ]
}
```

### static (.babelrc, babel.config.json, package.json#babel)

The static configuration is JSON format, therefore the config we get is a plain object, it is straightforward to stringify it back and output to console.

### dynamic (babel.config.js, babel.config.cjs, .babelrc.js, .babelrc.cjs)

The configuration object is produced from `require`ing CommonJS module before processing config items.

Serializing this object with customized JSON replacer `replace(key, value)`:

If `key` is `plugins` or `presets`, for every array item, check by `item`, `item.name`, `item[0].name` for plugin/preset name

Otherwise if `value` is of function type, omit this property

Mark the output as `serialized` as it may be different from the original dynamic config.

## Questions

Q: Should we support `--show-merged-config` flag to output a _merged_ JSON configuration?

A: Would be good to include it in next phase. It should help reasoning about the ignore/include config items.

Q: Should we print the resolved presets config? (`presets: ["@babel/env"]` vs `plugins: [...]`)

A: Not prioritized. It doesn't help on plugin ordering issues and it makes printed result more verbose.

Q: Should we print the _extended_ config item? i.e. `extends: "babel-preset-foo"`

A: Not prioritized. I don't think it is popular.

## Prior Art
This document is inspired from the following prior arts.

TypeScript Compiler `tsc` has a `--showConfig` option. It prints the merged configuration from the contents of `tsconfig.json` and default configs.
```
$ tsc --showConfig foo.ts

{
    "compilerOptions": {},
    "files": [
        "./foo.ts"
    ]
}
```

`npm` has a subcommand `npm config list`. It lists a chain of applicable configs with respect to current working directory.
```
$ npm config list

; cli configs
metrics-registry = "https://registry.npmjs.org/"

; userconfig /Users/foo/.npmrc
tag-version-prefix = ""

; globalconfig /usr/local/etc/npmrc
sign-git-tag = true
```

**Comment by nicolo-ribaudo** [comment]
1. I think one env var is enough. If I specify `BABEL_SHOW_CONFIG_FOR_PATH`, then it's obvious that I want to print the config and I shouldn't need `BABEL_SHOW_CONFIG`.
2. Maybe it could be a follow-up, but it would also be really useful to know _why_ Babel is loading or not a configuration. For example:
  ```
  - /my/project/folder
    - babel.config.js
    - .babelrc
    - packages
      - demo
        - package.json
        - .babelrc
        - src
          - input.js
  ```
  ```
  Looking for root configuration files starting from ./
    Found babel.config.js
  Looking for relative configuration files starting from ./packages/demo/src
  	Found ./packages/demo/.babelrc
      Ignored because not in babelrcRoots
  	Found package root at ./packages/demo/package.json: stopping
  ```

**Comment by JLHwung** [comment]
> I think one env var is enough. If I specify BABEL_SHOW_CONFIG_FOR_PATH, then it's obvious that I want to print the config and I shouldn't need BABEL_SHOW_CONFIG.

Good point! I have updated the document and also removed the `--show-config-for-path` cli option.

> why Babel is loading or not a configuration

We can append the _inactive configs_ to the output config chains. i.e.

```
// user supplied config (serialized)
{
  ... babel configuration injected by CRA
}

// inactive configs
- babel config ./src/.babelrc.js (not in babelrcRoots)
```
and _ignored_ when the effective config is empty. i.e.
```
// ignored from rules in ./src/.babelignore
```
What do you think?

**Comment by rajasekarm** [comment]
I worked on this implementation #7201 earlier, If this is proposal is finalized I can re-implement this.

@JLHwung @nicolo-ribaudo

**Comment by JLHwung** [comment]
@rajasekarm That's awesome. I will assign to you. Also feel free to comment on this proposal should you have any suggestions.

**Comment by aladdin-add** [comment]
any news?

**Comment by lencioni** [comment]
> Q: Should we print the resolved presets config? (presets: ["@babel/env"] vs plugins: [...])
> 
> A: Not prioritized. It doesn't help on plugin ordering issues and it makes printed result more verbose.

👋 I just wanted to chime in here with my current use-case where something like this would be pretty helpful, in case it might be helpful for yall. I'm currently working on taking a complicated Babel preset and inlining it directly into a complicated .babelrc file.

After a naive attempt, I'm getting confusing errors that I assume are due to the `env` and `overrides` options not working exactly how I expected or maybe due to a difference in ordering. Having a way to take my current Babel configuration and print out a resolved version where presets are converted to lists of plugins would be very helpful for this task. :)
