### ISSUE TITLE
babel.config.js read but not working via babel/core parseSync.

### ISSUE THREAD

**Issue by TheHighriser** [babel/babel#10610]
## Bug Report

**Current Behavior**
I have a custom script which is importing @babel/core and is using the parseSync method. I pass the option for rootMode (so it finds the babel.config.js) and the filename. I am using a plugin for allowing decorators:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
};
```

When I now try to parse the source code it always throws ILLEGAL token. Which is the line with the decorator. If I remove the plugin but pass parserOpts including the decorator plugin, the source code parses fine. 

**Input Code**

**NOT WORKING** (With the babel.config.js in combination above): It says ILLEGAL Token

```js
import * as babel from '@babel/core';

babel.parseSync(source, {
    rootMode : "upward",
    filename : "Something.js",
});
```
  
  
**WORKING**: Parses without any problems. If I also use the babel.config.js in combination with the parserOpts, it says that I can use the decorator plugin simultaneously with the other decorator plugin. 

```js
import * as babel from '@babel/core';

babel.parseSync(source, {
    parserOpts: {
    ...,
    plugins: [
        ['decorators', {decoratorsBeforeExport: true}]
    ]
}
});
```

**Expected behavior/code**
I would expect that the code parses fine with the plugin defined through the babel.config.js. Or is this some misunderstanding from my side? Is this not possible? 

**Environment**
- Babel core version(s): 7.6.4
- Node/npm version: Node 10.15.3 / NPM 6.4.1
- OS: Windows 10
- Monorepo: no
- How you are using Babel: Via Node script

**Comment by JLHwung** [comment]
`babel.parseSync` is not supposed to share the same configuration shape with `babel.transformSync`. For the former you may checkout `@babel/parser` [API Documentation].(https://babeljs.io/docs/en/babel-parser#api)

Could you help improve [babel.parserSync](https://babeljs.io/docs/en/babel-core#parsesync) docs and point it to `babel/parser` usage page?

**Comment by JLHwung** [comment]
I could not reproduce this issue on my local environment.

Note that the configuration
```js
babel.parseSync(source, {
    parserOpts: {
    ...,
    plugins: [
        ['decorators', {decoratorsBeforeExport: true}]
    ]
}
});
```
contradicts to the `babel.config.js` you have listed before
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
};
```
because  when `decoratorsBeforeExport` is true, `legacy` must be false. Could you offer a reproducing repository?

**Comment by TheHighriser** [comment]
Thanks for the real quick answer here. Probably this is a misunderstanding from my side. 

So the question is if the babel.config.js file is able to do the same work as the options above in the parseSync. So if you would remove the plugin from the parseSync block above, would it still be able to parse the decorator (because it is configured in the babel.config.js file) - Is this possible? Because that's what I am asking myself and that's what I am not able to do?

Or are those two configs, two different things and the parser only takes options from the parserOpts block?

My main goal is to implement a parsing which is using any babel.config.js file. I though this might be possible over the parseSync method as it reads the babel.config.js. So if any user is installing my module and uses the parser it will automatically take the babel.config.js and will be able (for example) to parse his decorators. Or do I always need to additionally pass the parserOpts block with the decorator option in it? Or are these two different things?

Thanks for the help!

P.S. Sadly I have no repo.

**Comment by nicolo-ribaudo** [comment]
Yes, `parseSync` can load the config file and use "normal" babel plugins.
Your original example seems correct, and I can't reproduce the bug locally.

If you can provide a small repository which reproduces the issue I'd be happy to help. As a quick workaround, you can pass `configFile: "path/to/babel.config.js"` to `parseSync`.
