### ISSUE TITLE
Add polyfill for Object.constructor.prototype.name

### ISSUE THREAD

**Issue by binarykitchen** [babel/babel#10624]
Any code which has `Object.constructor.prototype.name` is breaking on IE11 which hasn't reachend EOL yet.

Turns out Babel nor any of it's add-ons are polyfilling or transpiling it into IE11 compatible ES5 code. Would be good to add yeah?

**Comment by nicolo-ribaudo** [comment]
What is your config? It seems to be working:

**Comment by jridgewell** [comment]
He's likely talking about function names, which IE11 doesn't support:

```js
function Foo() {}
Foo.name; // => "Foo", but not defined in IE11

**Comment by binarykitchen** [comment]
Yeah that. And sorry about the false alarm, just found out core-js polyfills this well.
