### ISSUE TITLE
We noticed you're using the `useBuiltIns` option without declaring a core-js version

### ISSUE THREAD

**Issue by rifler** [babel/babel#10622]
## Bug Report

**Current Behavior**
I have the direct dependency `"core-js": "3.3.5",` in my `package.json`, but whatever see that warning.

**Expected behavior/code**
No warning

**Babel Configuration (.babelrc, package.json, cli command)**

```js
[
    '@babel/preset-env',
    {
        loose: true,
        modules: false,
        corejs: '3.3.5',
        useBuiltIns: 'usage',
        targets: {
            ie: '11',
        },
    },
],
```
I also tried `3` and `"3"`

**Environment**
- Babel version(s): 7.6.4
- Node/npm version: 10/6.12.1
- OS: OSX 10.14.6
- Monorepo: Lerna
- How you are using Babel: `babel-loader@8.0.6`

**Additional context/Screenshots**
```bash
> cat ./node_modules/core-js/package.json | grep version
  "version": "3.3.5",

```

**Comment by JLHwung** [comment]
@rifler Do you have other babel configurations? Such as the loader options of `babel-loader` in webpack configs?

**Comment by rifler** [comment]
it is my carelessness, sorry

thanks for babel!
