### ISSUE TITLE
Missing class static properties

### ISSUE THREAD

**Issue by ShinobiWPS** [babel/babel#10620]
## Bug Report

**Current Behavior**
When I use a Class with static property (like a simple variable) it breaks and suggest to add a plugin or class,if I remove static properties everything work perfectly as expected.

**Input Code**

```js
import Tabulator from 'tabulator-tables'
/* import '../vendor/cleanslate.css' */
import { config } from './config'

class SiapTable {
  static el;

  static defaultConfig = config

  static create (parentElement, data) {
    function doRender () {
      if (SiapTable.el) {
        throw new Error('SiapTable is already mounted, unmount first')
      }

      /* const el = document.createElement('div')
      el.setAttribute('class', 'cleanslate') */

      if (parentElement) {
        document.querySelector(parentElement).appendChild(el)
      } else {
        console.error('')
      }

      const table = new Tabulator(el, { ...data, ...SiapTable.defaultConfig })
      SiapTable.el = el
    }

    if (document.readyState === 'complete') {
      doRender()
    } else {
      window.addEventListener('load', () => {
        doRender()
      })
    }
  }
}
export default SiapTable
/* export { default as Siap } */
/* export {table} */

```

**Expected behavior/code**
Since every modern browser now supports es6 ,classes too, I expected to have  "@babel/plugin-proposal-class-properties" included in preset-env

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env"]
}
```

**Environment**
- Babel version(s): [7.6.4]
- Node/npm version: [npm 6]
- OS: [OSX 10.13.4]
- Monorepo: [no]
- How you are using Babel: [`loader`]

**Possible Solution**
Include "@babel/plugin-proposal-class-properties" in dependencies of babel for the ENV preset

**Additional context/Screenshots**
![Screenshot 2019-10-31 at 4 27 31 PM](https://user-images.githubusercontent.com/11430881/67960952-4d138a00-fbfb-11e9-9780-bdc4fe086ccd.png)

**Comment by ShinobiWPS** [comment]
> You can toggle on the [`shippedProposals`](https://babeljs.io/docs/en/babel-preset-env#shippedproposals) if your targeted browsers have native support.
> 
> By default `preset-env` supports latest finalized ECMAScript standard. Note that [Class field proposal](https://github.com/tc39/proposal-class-fields#class-field-declarations-for-javascript) is still stage 3, though it is supported on major browsers.

tryed and same exact output as in the screenshot above
`{
  "presets": [["@babel/preset-env", { "shippedProposals": true }]]
}`

**Comment by JLHwung** [comment]
@ShinobiWPS Sorry, my bad. `shippedProposals` tracks Stage 4 proposals only. For stage 3 proposal, you still have to add it to the `plugins` section.

**Comment by ShinobiWPS** [comment]
where i can track the progress of stage for that particular proposal?

**Comment by JLHwung** [comment]
You can check the status of active proposals on https://github.com/tc39/proposals.
