### ISSUE TITLE
Babel @babel/preset-es2015 Module not found

### ISSUE THREAD

**Issue by mzubairharoon** [babel/babel#10633]
I've installed babel 7 through the documentation command.

npm install -D babel-loader @babel/core @babel/preset-env @babel/preset-es2015 --save-dev

https://i.stack.imgur.com/z0KqM.png

But I'm getting error

`    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/preset-es2015'`

**babelrc**

`{ "presets": 
[ 
  [ 
  "@babel/preset-env", { 
  "modules": false, 
  "targets": { "browsers": ["> 1%", "last 2 versions", "not ie <= 8", "ie >= 11"] } } 
  ],
], 
"plugins": [ "@babel/plugin-syntax-dynamic-import", ] }`

**My webpack.config.js**

`// BABEL
            { 
                test: /\.js$/, 
                loader: 'babel-loader', 
                options: { presets: ["@babel/preset-env", '@babel/preset-es2015'] },
                exclude: /(node_modules)/ 
            },`

**Environment**
"@babel/core": "^7.6.4",
"@babel/preset-env": "^7.6.3",
"@babel/preset-es2015": "^7.0.0-beta.53",
"assets-webpack-plugin": "^3.9.10",
"babel-loader": "^8.0.6",

https://i.stack.imgur.com/HY2Y7.png

**Comment by nicolo-ribaudo** [comment]
You don't need it if you are already using preset-env

**Comment by mzubairharoon** [comment]
Hi @nicolo-ribaudo when I remove preset-es2015 the compiled source has functions in this format, which shows the syntax error in IE 11.

`module.exports = len => {`

Thanks

**Comment by nicolo-ribaudo** [comment]
Which is the path of the file containing that arrow function?

**Comment by mzubairharoon** [comment]
When I remove @babel/preset-es2015 it compiles without error.

`{ 
                test: /\.js$/, 
                loader: 'babel-loader', 
                options: { presets: ["@babel/preset-env"/*, '@babel/preset-es2015'*/] },
                exclude: /(node_modules)/ 
            },`

But it has function syntax which doesn't work in IE

`module.exports = len => {`

The file containing that arrow function is dist/chunk.bundle.vendors~main.js

https://i.imgur.com/jcRfsFj.png

**Comment by nicolo-ribaudo** [comment]
Sorry for not being clear: I meant the original source file, not the output one.

**Comment by mzubairharoon** [comment]
Sorry Crypto-browserify is a package which is used, can I show that source?

https://i.imgur.com/jcRfsFj.png

**Comment by mzubairharoon** [comment]
Here is the file which has this arrow function and it is not converted through babel.

https://imgur.com/QB7K3GX

**Comment by nicolo-ribaudo** [comment]
Ok so,
1) you are telling webpack not to pass that file to Babel, because you are excluding all your `/node_modules/`. You can use
```js
exclude: {
  test: /node_modules/,
  not: [/crypto-random-string/]
}
```
2) .babelrc is only applied to the current package, and not to other packages (like dependencies). You need to use `babel.config.js` instead.

**Comment by mzubairharoon** [comment]
Thanks, I tried number #1, but I see this error.

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0] has an unknown property 'not'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, resolve?, sideEffects?, query?, type?, resource?, resourceQuery?, compiler?, rules?, test?, use? }
   -> A rule
`

**Comment by nicolo-ribaudo** [comment]
You didn't copy it correctly

**Comment by mzubairharoon** [comment]
Perfect Thanks alot
