### ISSUE TITLE
Type annotation is stripped from Typescript template 

### ISSUE THREAD

**Issue by dentrado** [babel/babel#10636]
## Bug Report

**Current Behavior**
A `@babel/template` template with placeholders and a type annotation generates code without the annotation. A template without placeholders works as expected.

**Input Code**

```js
const template = require('@babel/template').default
const generate = require('@babel/generator').default
const t = require('@babel/types')
​
const withType = template({plugins:['typescript']}).ast`
    const greeting: string = 'Hello';
`
console.log(generate(withType).code)
// => "const greeting: string = 'Hello';"
​
const typeDisappears = template({plugins:['typescript']}).ast`
    const ${t.identifier('greeting')}: string = 'Hello';
`
console.log(generate(typeDisappears).code)
// => "const greeting = 'Hello';"
```

**Expected behavior/code**

I expect both templates above to keep the `: string` type in the generated code.

**Babel Configuration (.babelrc, package.json, cli command)**

No configuration, used from code, see above.

**Environment**
- Babel version(s): 7.6.4
- Node/npm version: Node 12.9.1 / yarn 1.17.3
- Monorepo: no

**Comment by nicolo-ribaudo** [comment]
The root cause of this bug is that the type annotation is a child node of the identifier. The identifier you are passing to `@babel/template` doesn't have the type annotation, and thus the one in the template is discarded.

https://github.com/babel/babel/issues/9545 would be a possible way of fixing this.
