### ISSUE TITLE
Export named function declaration issue with _interopRequire

### ISSUE THREAD

**Issue by cesarenaldi** [babel/babel#1063]
Hi,

I have a simple module that export a single named function declaration.
```javascript
'use strict';

export function name() { /* .. */ }
```
The transpiled output in CJS is:
```javascript
'use strict';

exports.__esModule = true;
exports.name = name;

function name() { /* .. */ }
```

This creates issue when I import this module as the helper function `_interopRequire` tries to export the missing `default` module property. See below.
```javascript
var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };
```

Am I doing something wrong or it's a genuine bug?

**Comment by sebmck** [comment]
No this is expected behaviour. You need to use `import * as foo from "bar";`
