### ISSUE TITLE
preset-env not properly respecting "browserslist"

### ISSUE THREAD

**Issue by jasonwilliams** [babel/babel#10635]
## Bug Report

**Current Behavior**
Setting "last 2 versions, not ie <= 10" still sets a target for IE 10.

**Input Code - inside package.json**
```
  "browserslist": [
    "last 2 versions",
    "not ie <= 10",
    "not op_mini all"
  ],
```
Generates
```
Using targets:
{
  "android": "76",
  "chrome": "76",
  "edge": "17",
  "firefox": "68",
  "ie": "10",
  "ios": "12.2",
  "opera": "12.1",
  "safari": "12.1",
  "samsung": "9.2"
}
```

**Expected behavior/code**
IE 10 should not be a target.

**Environment**
- @babel/preset-env@7.4.5
- Node/npm version: v12.11.1
- OS: Linux
- Monorepo: yes
- How you are using Babel: loader

**Possible Solution**
I've managed to fix the bug by explicity setting `ie: 11` copying:
https://github.com/babel/babel-preset-env/issues/345

**Comment by JLHwung** [comment]
It is expected because `ie_mob 10`, which is included in `last 2 versions`, is _not_ excluded. Under the hood Babel will map `ie_mob 10` to `ie 10`. Consider add `ie_mob 10` to the browserslist config:
```
"browserslist": [
    "last 2 versions",
    "not ie 10",
    "not ie_mob 10"
    "not op_mini all"
  ],
```
