### ISSUE TITLE
npm install --save-dev @babel/preset-env  **Not Working** 

### ISSUE THREAD

**Issue by Kizito25** [babel/babel#10641]
## Bug Report

**npm install --save-dev @babel/preset-env** is not **working in windows**
A clear and concise description of the behavior.

**Input Code**
- Code To Install @babel/preset-env:

```
npm install --save-dev @babel/preset-env

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```
**Returned Output **

```
npm ERR! Unexpected end of JSON input while parsing near '...hasum":"1820c3c9adb9a'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lizardSquad\AppData\Roaming\npm-cache\_logs\2019-11-04T22_28_37_791Z-debug.log

```

**Environment**
- Babel version(s): [7.6.4 (@babel/core 7.6.4)]
- Node/npm version: [Node 12.13.0/npm 6.12.0]
- OS: [ Windows 10]
- Monorepo: [yes]
- How you are using Babel: [.`cli`,]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
The file got corrupted while downloading. Try running it again.
