### ISSUE TITLE
throw error: api.caller is not a function in babel-preset-env/index.js

### ISSUE THREAD

**Issue by love2me** [babel/babel#10646]
## Bug Report

**Current Behavior**

` api.caller is not a function
    at _default
 (/Code/node_modules/@babel/preset-env/lib/index.js:234:35)
    at Object.default (/Code/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12)
    at getEnvPlugins (/Code/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/Code/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
`

**Environment**
- Babel version(s): [7.7.0]
- Node/npm version: [Node 8.11.3/npm 5.6.0]
- OS: [ OSX 10.13.4]
- Monorepo: [no]
- How you are using Babel: [cli]

**Possible Solution**
I think need to check api.caller is not a function in [packages/babel-preset-env/index.js line 240](https://github.com/babel/babel/blob/5f2240e7ab319c8e22cc6d2405364e439968e1e0/packages/babel-preset-env/src/index.js#L240).

**Comment by nicolo-ribaudo** [comment]
Could you open a quick PR? 🙏

**Comment by love2me** [comment]
> Could you open a quick PR? 🙏

I had to create a PR. Please review.
@nicolo-ribaudo
