### ISSUE TITLE
Some few possible spelling errors

### ISSUE THREAD

**Issue by jschleus** [babel/babel#10653]
On the FOSS server fossies.org I have used a new functionality and have done as a trial a "codespell" run for the new "Babel" release 7.7.0. Here the version independent URL of the resulting report:

https://fossies.org/linux/www/babel/codespell.html

That URL redirects always to the URL of the report for the last "Babel" release supported on Fossies (in case such a report was requested respectively is existing). Currently that is

https://fossies.org/linux/www/babel-7.7.0.tar.gz/codespell.html

Although I have already prefiltered some obviously wrong matches (false positives) please inform me if you find more of them so that I can force a new improved check.

For different reasons I myself am unable to create an according  PR.

I know it's not an important issue so naturally you can ignore it and close it.

**Comment by nicolo-ribaudo** [comment]
The first thing that I noticed is that many of them are in the changelog, but it's automatically generated using commit messages.

**Comment by jschleus** [comment]
I see the problem.

Spelling errors respectively typos in changelog files seem to be generally a little bit problematic. Some are very old (and nobody bothered about it) but in rare cases they may be give misleading information.

**Comment by JLHwung** [comment]
@nicolo-ribaudo we may check the typos in the commit message using [yaspeller](https://github.com/hcodes/yaspeller) and husky. But we will take some time to maintain a custom dictionary.
