### ISSUE TITLE
@babel/preset-env v7.7.1 update breaks async test

### ISSUE THREAD

**Issue by bernardodomingues-hotmart** [babel/babel#10659]
## Bug Report

**Current Behavior**
I have a test that starts an async function but asserts the app state synchronously. When `@babel/preset-env` was updated to `v7.7.1` from `v7.6.3`, the test broke because the async code is executed before the synchronous assertion is made.

**Input Code**

```js
/* app.js */
// This is an approximation - asyncFunc returns a promise which is resolved before the async code runs
async function asyncFunc() {
  // do something synchronously
  anotherAsyncFunc(); // The execution does not wait for this function to complete
  return;
}

/* test.js */
await asyncFunc()
//assertion
```

**Expected behavior/code**
The test should assess the app's state after the synchronous code has run, ignoring state change after any asynchronous code.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
/* .babelrc */
{
  "presets": [
    "@babel/preset-react",
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": "3"
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    [
      "@babel/transform-runtime",
      {
        "corejs": "3"
      }
    ]
  ],
  "env": {
    "test": {
      "plugins": [
        "dynamic-import-node"
      ]
    }
  }
}

/* package.json */
{
  "dependencies": {
    "@babel/runtime": "7.7.1",
   // ...
  },
  "devDependencies": {
    "@babel/core": "7.7.0",
    "@babel/plugin-proposal-class-properties": "7.7.0",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-runtime": "7.6.2",
    "@babel/preset-env": "7.7.1",
    "@babel/preset-react": "7.7.0",
    "@babel/runtime-corejs3": "7.7.1",
    // ...
  }
}
```

**Environment**
- Babel version(s): v7.7.0
- Node/npm version: Node 12.13.0/npm 6.12.0
- OS: Linux x64 / Docker `node:12`
- Monorepo: no
- How you are using Babel: webpack / jest plugin

**Possible Solution**
So far, rolling back `@babel/preset-env` to version `v7.6.3` fixed the issue.

**Additional context/Screenshots**
This might be a bug introduced by #10422, which was the only update in `@babel/preset-env` I could find in the changelog that was related to async code execution.

**Comment by JLHwung** [comment]
@bernardodomingues-hotmart I could not reproduce this issue on [REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAzhC8EEYDcAoAZgVwHYGMAuAlgPZYQBG4AFAJQQDeKE0cEAzKgL4oohQCeuCJlyESQokRr1GzeACZUTCmBqdulXgJwQpsAHzSmIAO4gCecZOqKIOElCIAbAKYA6R0QDmlKNZQdqGiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.7.1&externalPlugins=) and [runkit](https://runkit.com/embed/r89l2nwbkm13). Could you draft a reproducible example?

**Comment by bernardodomingues-hotmart** [comment]
HI @JLHwung! Thanks for the response. I've tried to set it up, but unfortunately, I wasn't able to reproduce this behavior on a simple and isolated code. My original faulty code involves `redux`, `redux-thunk` and asynchronous updates to the store, whose state is assessed by the tests.

I might refactor my tests to be less brittle regarding the async code execution order instead. Nevertheless, the update introduced some unexpected behavior and it might be worth to look over it again under this new light.

Best regards

**Comment by bernardodomingues-hotmart** [comment]
This [runkit](https://runkit.com/bernardofd/babel-10659) is a little closer to my use case but does not present the unexpected behavior

**Comment by dominykas** [comment]
> This might be a bug introduced by #10422, which was the only update in @babel/preset-env I could find in the changelog that was related to async code execution.

We're looking into a similar issue (things happening in a different order after moving from 7.6 to 7.7 - not sure about details just yet).

I think another suspect could be #9481.

**Comment by nicolo-ribaudo** [comment]
Closing since it was not possible to reproduce this issue.
