### ISSUE TITLE
No matching version found for @babel/helper-annotate-as-pure@^7.7.0

### ISSUE THREAD

**Issue by ymallikreddy521** [babel/babel#10655]
we will run npm install we get below error

No matching version found for @babel/helper-annotate-as-pure@^7.7.0

**Comment by JLHwung** [comment]
`@babel/helper-annotate-as-pure@7.7.0` is [published](https://www.npmjs.com/package/@babel/helper-annotate-as-pure) on `npm`. Are you using a customized npm registry?

**Comment by nicolo-ribaudo** [comment]
This is either a bug with npm, or a proxy/cache you are using which isn't updated. You could find a solution in https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed

**Comment by ymallikreddy521** [comment]
Nope. we are not doing any customization.

**Comment by JLHwung** [comment]
@ymallikreddy521 Could you attach the output of the following command?
```
curl --head -v `npm view @babel/helper-annotate-as-pure dist.tarball`
```

**Comment by ymallikreddy521** [comment]
There were some changes on Proxy by team. Now it works.
