### ISSUE TITLE
Template Literals Incorrect

### ISSUE THREAD

**Issue by jacobp100** [babel/babel#1065]
Say I have the object,

```js
let x = {
    toString() { return 'String' },
    valueOf() { return 4; }
};
`${x}`;
```

Expected result:
```js
'String'
```

Actual result:
```js
'4'
```

We should be calling `String(x)` for all the variables.

**Comment by sebmck** [comment]
Do you have a spec citation?

**Comment by sebmck** [comment]
Also your example has a ton of syntax errors.

**Comment by jacobp100** [comment]
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-gettemplateobject part 11.

**Comment by sebmck** [comment]
GetTemplateObject` isn't the relevant section, `ToString` is just being called on `index`.

[12.2.8.5 3](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literals-runtime-semantics-evaluation) appears to be where the expression is turned into a string. Looks like the current (apparently incorrect) behaviour is the same as the current V8 and Traceur so bugs should be reported on both of those.

Closing this as a wontfix as the performance impact of wrapping all template literal expressions with a call to `String` is going to be pretty significant and template literals will almost certainly occur in hot code.

**Comment by jacobp100** [comment]
Why is there a perf impact? `x: ${x}` should map to `'x: ' + String(x)`

**Comment by sebmck** [comment]
Yep, and that's the performance impact I alluded to.

[![screen shot 2015-03-23 at 9 31 59 pm](https://cloud.githubusercontent.com/assets/853712/6778108/10405422-d1a4-11e4-9b63-e26a54902275.png)](http://jsperf.com/string-constructor-wrapping)

May change this in the future but not at this time.

**Comment by jacobp100** [comment]
http://jsperf.com/tostring-vs-appending-empty-string

Alright. There is a perf impact. However, this is clearly not spec compliant. To what level should optimisations allow spec deviations?

**Comment by sebmck** [comment]
> To what level should optimisations allow spec deviations?

Almost never but seeing as all other implementations follow this behaviour I think it's ok for the timebeing.

**Comment by jacobp100** [comment]
Firefox is correct.

**Comment by sebmck** [comment]
I'll confirm if this is an issue in the latest v8 and report a bug otherwise and then work out how to proceed.

**Comment by sebmck** [comment]
Reopening for the time being, need to evaluate and investigate this more.

**Comment by AluisioASG** [comment]
Wouldn't this be the case for a `spec` transformer?

**Comment by sebmck** [comment]
@AluisioASG Nope. The `spec` transformer category is very loosley defined and is just a catch-all for things that don't really belong in another category but are related to spec compliancy.

**Comment by jacobp100** [comment]
https://code.google.com/p/v8/issues/detail?id=3980 for the V8 issue, although V8 is probably not a good metric to use for JS correctness.

**Comment by sebmck** [comment]
@jacobp100 Didn't say it was. Just wanted to verify if it was present in the latest and not in the version of iojs I'm using.

**Comment by sebmck** [comment]
Reference: google/traceur-compiler#1836
