### ISSUE TITLE
[Reopen]_typeof function in generated code calls itself before it is defined (T7149)

### ISSUE THREAD

**Issue by shrinktofit** [babel/babel#10662]
It's a reopen of ISSUE https://github.com/babel/babel/issues/4125.

I have found a reproducible example. My transform code:
```js
const babel = require('@babel/core');
const fs = require('fs');
(async () => {
	const result = await babel.transformFileAsync('predefine.ts', {
		presets: [
		    ["@babel/preset-env", { modules: 'umd' }],
		    [require("@babel/preset-typescript")],
		],
	});
	fs.writeFileSync("_typeof_out.js", result.code);
})();
```

Generated code:

[predefine.zip](https://github.com/babel/babel/files/3812495/predefine.zip)

babel version: 7.6.4
transform-modules-umd version:7.7.0, but 7.2.0 does not reference `_typeof` before declare it

@nicolo-ribaudo

**Comment by shrinktofit** [comment]
The error disappear if the original source doesn't contains `typeof` keyword.

**Comment by JLHwung** [comment]
I can reproduce this error by the following snippet ([REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQSgBAvAfGAuCeAHApgewGZgHYFcA2ekEEYA5KgEYBWyAxrKQNwBQQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.7.3&externalPlugins=%40babel%2Fplugin-transform-modules-umd%407.7.0%2C%40babel%2Fplugin-transform-typeof-symbol%407.2.0))
```js
() => typeof null === 'object';
```
