### ISSUE TITLE
No matching version found for @babel/parser@^7.7.0

### ISSUE THREAD

**Issue by smehdi21** [babel/babel#10666]
## Bug Report

**Current Behavior**
The npm package  @babel/parser@^7.7.0 not found

**Input Code**

pm ERR! notarget No matching version found for @babel/parser@^7.7.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/template'
npm ERR! notarget

```
**Environment**
- Babel version(s): [e.g. v7.0.0]

**Comment by JLHwung** [comment]
@babel/babel/parser@7.7.0 is [published](https://www.npmjs.com/package/@babel/parser) on npm. Could you attach the output?
```
curl --head -v `npm view @babel/parser dist.tarball`
```

You could also find a solution in https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed
