### ISSUE TITLE
Babel polyfill documentation

### ISSUE THREAD

**Issue by emilmuller** [babel/babel#10660]
How to polyfill is seriously confusing.

Under https://babeljs.io/docs/en, under Usage -> Polyfill, the first thing that greets you under the headline @babel/polyfill, is that the package is deprecated.

So the package is deprecated, how does one polyfill?

Apparently like so: As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions): [...]

So in essence, the documentation on this has been reduced to a single sentence, and what is found below is deprecated?

**Comment by JLHwung** [comment]
Although `@babel/polyfill` has been deprecated, the documentation is still helpful for those haven't transition to core-js and regenerator. That said, Microsoft still offers documentations of Windows XP even though it is end of life.

Could you help improve the polyfill page to make it more clear to our users? Thank you!

**Comment by emilmuller** [comment]
Of course I can help improve it, but I'm currently a little in the blue as to what is the correct approach :)

For instance, I would like to polyfill for ie11 based on usage. I also use npm packages (which reside in node_modules) which is a pretty common thing. Then you end up with questions such as https://stackoverflow.com/questions/52407499/how-do-i-use-babels-usebuiltins-usage-option-on-the-vendors-bundle/52415747. Now I still end up with errors when compiling for ie11, such as "TypeError: Cannot read property 'toStringTag' of undefined" after following that post, and I'm pretty sure it's my configuration, and I have no idea what's wrong. I also don't understand it completely. The documentation should provide a working example for the most common setup.

I would very much like to help and improve the polyfill page, but there are too many things that I cannot answer at this point because it is too confusing. For instance, why I would need to ignore core-js (which is undocumented) for the most common setup (my guess).
