### ISSUE TITLE
No matching version found for @babel/helper-module-imports@^7.7.0

### ISSUE THREAD

**Issue by ciroanni** [babel/babel#10664]
## Bug Report

we still have issue on @babel/helper-module-imports@^7.7.0.
could you update on npm the new version of this module please?

thanks

**Comment by JLHwung** [comment]
@babel/helper-module-imports@7.7.0 is published on npm. Could you attach the output?
```
curl --head -v `npm view @babel/helper-module-imports dist.tarball`
```

You could also find a solution in https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed

**Comment by ivanovivelin** [comment]
This issue is still present. Is there any solution for it ?

**Comment by existentialism** [comment]
@ivanovivelin it's definitely published: https://unpkg.com/browse/@babel/helper-module-imports@7.7.0/, https://www.npmjs.com/package/@babel/helper-module-imports

Can you check the results of the command that @JLHwung suggested?
