### ISSUE TITLE
Functions Object Literal Notation

### ISSUE THREAD

**Issue by jacobp100** [babel/babel#1066]
The object,
```js
let x = {
    toString() 'String'
};
```
Expected result
```js
var x = {
    toString: function toString() {
        return 'String'
    }
}
```
Actual result
```js
var x = {
    toString: function toString() "String"
};
```

EDIT:
As sebmck points out, the expected result is that this shouldn't parse. This also affects classes.

```js
class Test {
  constructor() {
    this.value = 3;
  }
  valueOf() this.value;
}
```

**Comment by sebmck** [comment]
That shouldn't even parse.

**Comment by jacobp100** [comment]
Caused by https://github.com/babel/babel/issues/1067

**Comment by sebmck** [comment]
The real bug here is that:

```javascript
let x = {
    toString() 'String'
};
```

is allowed to be parsed at all. See the `MethodDefinition` grammar [here](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functions-and-classes).
