### ISSUE TITLE
Function Return Literal

### ISSUE THREAD

**Issue by jacobp100** [babel/babel#1067]
Input:
```js
function x() 'test'
```
Expected result:
```js
function x() { return 'test'; }
```
Actual result:
**Fails**

**Comment by sebmck** [comment]
Why are you under the assumption that this is valid?

**Comment by sebmck** [comment]
This is almost certainly not valid. See the [function grammar](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-definitions).

**Comment by jacobp100** [comment]
It works in Firefox. Reopen until somebody is 100% sure.

**Comment by sebmck** [comment]
@jacobp100 I'm 100% sure. See the [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Expression_closures). This is a non-standard Firefox extension.

**Comment by jacobp100** [comment]
Weird, I thought that made it to the spec along with the arrow notation. I guess you're right then!
