### ISSUE TITLE
Parsing error for generic function named 'of'

### ISSUE THREAD

**Issue by alexwalterbos** [babel/babel#10675]
Thanks for the great tool guys! I found a parsing bug regarding generic function definitions and specific naming:

## Bug Report

**Current Behavior**
Babel-eslint parses a generic function just fine:
```JS
function someGenericFunction<R>(args: R): Array<R> {
  return [args];
}
```

It fails to parse that same function when it is named `of`, however:
```JS
function of<R>(args: R): Array<R> {
  return [args];
}
```
```
/path/to/index.js
  5:12  error  Parsing error: Unexpected token, expected "("

  3 | }
  4 | 
> 5 | function of<R>(args: R): Array<R> {
    |            ^
  6 | 	return [args];
  7 | }
  8 | 

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```
Flow accepts the function just fine and shows 'No errors!'. It confused me for longer than I'd like to admit, hopefully fixing this will save others some time.
It would seem that `of` is treated as a keyword - maybe because of the [`for...of` syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)?

**Input Code**
Reproduction repository: https://github.com/alexwalterbos/generic-function-of

**Expected behavior/code**
Parse the generic function named `of` just like any other generic function.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// package.json
{
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.6.0"
  }
}

// .eslintrc.js
module.exports = {
    "parser": "babel-eslint",
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
    }
};
```
Error is triggered simply with these commands in the reproduction repository linked above;
```
yarn install
yarn eslint .
```

**Environment**
- Babel version(s): v7.7.0 (`@babel/parser`)
- Node/npm version: Node v12.13.0, yarn v1.19.1
- OS: Fedora 29 x64
- Monorepo: no
- How you are using Babel: cli

**Workaround**
Don't name your generic functions `of`.

**Comment by rajasekarm** [comment]
I can pick this.

**Comment by rajasekarm** [comment]
The actual error is in babel-eslint.

In this https://github.com/babel/babel-eslint/blob/master/lib/parse.js#L36, plugin is always set to estree. But in this example, it a flow code.

So first thing, in the project, we've to configure flow as plugin.

```
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
        "babelOptions": {
            "plugins": ["flow"]
         },
    },
```

and we've to use this change in the parser inside babel-eslint.

https://github.com/babel/babel-eslint/blob/master/lib/parse.js#L36

**Comment by thorn0** [comment]
> The actual error is in babel-eslint.

It doesn't seem to be the case. This issue is [reproduced on the REPL](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABHYAeASgPgBQEMBOA5gM4Bci6AlOQIL764CeGmiA3gFCKL4CmUIfEgDaBEgF0A3BwC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Creact%2Cflow&prettier=false&targets=&version=7.7.4&externalPlugins=)  if the `flow` and `jsx` plugins are enabled.

**Comment by JLHwung** [comment]
@rajasekarm The issue is not related to babel-eslint and reproducible on REPL. Let me know if you are still working on this. :)

**Comment by rajasekarm** [comment]
No, I'm not working on it.

**Comment by JLHwung** [comment]
@rajasekarm Thanks. I will unassign you so if people are interested at a fix they can move on.
