### ISSUE TITLE
No matching version found for @babel/generator@^7.7.2

### ISSUE THREAD

**Issue by DavidKindler** [babel/babel#10676]
## Bug Report

**Current Behavior**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/generator@^7.7.2npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget

**Possible Solution**
Change @babel/generator to 7.7.0

**Comment by existentialism** [comment]
@DavidKindler it's definitely published: https://unpkg.com/browse/@babel/generator@7.7.2/, https://www.npmjs.com/package/@babel/generator

Are you behind a proxy/registry cache?

Can you attach the output of:

```
curl --head -v `npm view @babel/parser dist.tarball`
```

You could also find a solution in babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed

**Comment by DavidKindler** [comment]
Quite right.  Using a nexus proxy registry.  Problem seems to be there.  Thanks for your help.
