### ISSUE TITLE
Optional chaining on super.method() breaks

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#10673]
## Bug Report

**Current Behavior**
Optional call of a super method (`super.method?.()`) attempts to use `super` as an identifier, which is invalid. This might only happen in strict mode?

**Input Code**
[REPL](https://babeljs.io/repl/#?babili=false&browsers=last%201%20and_chr%20version%0A&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEBCkFNoG8BQ0PQLYIC4AsB7AEwAoBKFaAX1VtVEhgBEEAnASwDcFjoEAHrgQA7YjHgQkaTNjxEylGbMxs8AVzYjoEdQAd2AOhwESAfkMV0mWtSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-3&prettier=false&targets=&version=7.7.2&externalPlugins=)

```js
class Base {
    method() { }
}

class Sub extends Base {
    method() {
        return super.method?.()
    }
}
```

**Expected behavior/code**
Super method must always be invoked as `super.method()`, not `method.call(super)`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [ "@babel/plugin-proposal-optional-chaining" ]
}
```

**Environment**
- Babel version(s): 7.7.2
- Node/npm version: any
- OS: any
- Monorepo: any
- How you are using Babel: REPL

**Possible Solution**

Two different possible solutions:

1. ~Access `super.method` twice~ (Don't do this, see https://github.com/babel/babel/issues/10673#issuecomment-550959334)
2. Call the cached method with `this` instead of super

<details>

<summary>Solution 1 (ignore this)</summary>

```js
// Solution 1
// Input
super.method?.();

// Output
((_super$method = super.method) === null || _super$method === undefined)
  ? undefined
  : super.method();
```

</details>

```js
// Solution 2
// Input
super.method?.();

// Output
((_super$method = super.method) === null || _super$method === undefined)
  ? undefined
  : _super$method.call(this)
```

**Additional context/Screenshots**

This should be a beginner level fix.

**Comment by nicolo-ribaudo** [comment]
Solution 1 is not correct if `method` is a getter.

**Comment by jridgewell** [comment]
You're right. We can go the second solution.

Are there any meta properties that can be methods? Eg `new.target?.()`? We might need a new issue to track those.

**Comment by jridgewell** [comment]
To make this appropriate for a Good First Issue, the needed changes are in https://github.com/babel/babel/blob/c2bace4b73ae65771941efcf9c2eb33ad8c3463f/packages/babel-plugin-proposal-optional-chaining/src/index.js#L79-L93

We need to check if the context is `super`, and if so, use `this` instead.

**Comment by Shriram-Balaji** [comment]
@jridgewell I'd like to take a stab at this.

**Comment by jridgewell** [comment]
Excellent! It's yours.
