### ISSUE TITLE
Add cloneDeepWithoutLoc

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#10670]
I had a need for a `t.cloneDeepWithoutLoc` function today. We have a `t.cloneDeep` and a `t.cloneWithoutLoc` (both deprecated, but that's OK), but we do not have a `t.cloneDeepWithoutLoc`.

These functions all live in https://github.com/babel/babel/tree/bdb4318f47ec42ca4e325b5163e2e8ad57de4849/packages/babel-types/src/clone.

They are exported publicly at https://github.com/babel/babel/blob/bdb4318f47ec42ca4e325b5163e2e8ad57de4849/packages/babel-types/src/index.js#L19-L23.

We can add the functionality as a new optional-boolean parameter `t.cloneNode`. Let's call it `withoutLoc`. While we're add it, we can update `t.cloneWithoutLoc` to use this new parameter.

Let's also add [tests](https://github.com/babel/babel/blob/bdb4318f47ec42ca4e325b5163e2e8ad57de4849/packages/babel-types/test/cloning.js), and [flow](https://github.com/babel/babel/blob/bdb4318f47ec42ca4e325b5163e2e8ad57de4849/packages/babel-types/scripts/generators/flow.js#L133-L137) and [typescript](https://github.com/babel/babel/blob/bdb4318f47ec42ca4e325b5163e2e8ad57de4849/packages/babel-types/scripts/generators/typescript.js#L151-L155) types.

**Comment by Taym95** [comment]
I would like to work on it!

**Comment by nicolo-ribaudo** [comment]
It's yours!
