### ISSUE TITLE
@babel/generator output code different with input code

### ISSUE THREAD

**Issue by ShiChenCong** [babel/babel#10674]
## Bug Report
 
**Current Behavior**

**Input Code**
```js
import {
  BrowserRouter as Router, Route, Switch, Redirect,
} from 'react-router-dom';
```

**parse the code, then generate it into the file**
```js
const babelParser = require('@babel/parser');
const generate = require('@babel/generator').default;

const parsedCode = babelParser.parse(sourceCode, {
  sourceType: 'module',
  sourceFilename: 'route.js',
  plugins: [
    "jsx",
  ]
})
const code = generate(parsedCode, {
  retainLines: true,
  concise: true,
  // retainFunctionParens: true,
});
fs.writeFileSync('./route.js', code.code);
```

**output Code**

```js
import {
BrowserRouter as Router, Route, Switch, Redirect } from
'react-router-dom';
```

**Environment**
- "@babel/generator": "^7.6.4",
- "@babel/parser": "^7.6.4"

@nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
Babel doesn't make any guarantee about the output format.

I suggest using one of those packages:
- `recast`, which keeps the original formatting
- `prettier`, which prints your code nicely formatted

**Comment by ShiChenCong** [comment]
> Babel doesn't make any guarantee about the output format.
> 
> I suggest using one of those packages:
> 
> * `recast`, which keeps the original formatting
> * `prettier`, which prints your code nicely formatted

thx, it is helpful
