### ISSUE TITLE
Babel doesn't work from npm install

### ISSUE THREAD

**Issue by alexey-sh** [babel/babel#10681]
## Bug Report

**Current Behavior**
Here is a [simple app ](https://github.com/alexey-sh/test_webpack_with_npm) which I want to install via `npm i --save git+https://github.com/alexey-sh/test_webpack_with_npm.git`
After installation, it runs webpack and there is a babel rule as well. But the result of that process contains "class A extends B"(babel doesn't converted it) etc while running webpack from the `test_webpack_with_npm` repository makes transpiling into js without "class A extends B"(babel works). 

**Input Code**
Steps to reproduce:

1. `mkdir my_test_project`
2. `cd my_test_project`
3. `npm init`
4. `npm i --save git+https://github.com/alexey-sh/test_webpack_with_npm.git`
5. check `node_modules/testname/dist/index.js`
6. it contains `e.exports=class extends r`

**Expected behavior/code**
I'd like to see in `node_modules/testname/dist/index.js` something like this
`t.prototype=Object.create(e&&e.prototype,{constructor:{value:t,writable:!0,configurable:!0}})`

**Babel Configuration (.babelrc, package.json, cli command)**

package.json
```js
"dependencies": {
    "webpack": "4.41.0",
    "webpack-cli": "3.3.9",
    "@babel/core": "7.6.2",
    "@babel/plugin-proposal-object-rest-spread": "7.6.2",
    "@babel/plugin-transform-runtime": "7.6.2",
    "@babel/preset-env": "7.6.2",
    "babel-loader": "8.0.6"
  }
```

webpack.config.js
```
module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        "presets": [
                            [
                                "@babel/preset-env",
                                {
                                    "targets": {
                                        chrome: '40',
                                        firefox: '52',
                                        ie: '11',
                                        safari: '9'
                                    }
                                }
                            ]
                        ]
                    }
                }
            }
        ]
    }
```

**Environment**
- Babel version(s): n/a
- Node v11.15.0/npm 6.13.0
- OS: OSX 10.14.6 (18G95)
- Monorepo: ? perhaps no
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
If you add the `debug: true` option to the env preset, what does it print?

**Comment by alexey-sh** [comment]
turn out, the issue was about webpack settings.
here is more information about it
https://github.com/webpack/webpack/issues/9947

also the demo repo has been updated with proposed fix and it works perfectly.

thanks to babel team
