### ISSUE TITLE
babel-cli using outdated chokidar->fsevents dependency

### ISSUE THREAD

**Issue by pgnd** [babel/babel#10684]
current @babel/babel-cli uses old 'chokidar'

https://github.com/babel/babel/blob/master/packages/babel-cli/package.json#L32

results in

> [1/4] Resolving packages...
warning @babel/cli > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size

needs bump to chokidar v3+

latest,

https://github.com/paulmillr/chokidar/releases/tag/3.3.0

**Comment by nicolo-ribaudo** [comment]
It's not compatible with Node 6, so we can't upgrade yet.

**Comment by pgnd** [comment]
@nicolo-ribaudo 

Node *6*?  Isn't v6 long-ago EOL'd?

  https://nodejs.org/en/about/releases/

atm, _I_ have

node -v
  v13.1.0

Curious as to why there's a need for dragging along v6 compat?

**Comment by nicolo-ribaudo** [comment]
We will drop node 6 support in Babel 8, but until then we have to maintain it for backwards compatibility.

**Comment by JLHwung** [comment]
Closing it in favour of #9981, which also [mentioned](https://github.com/babel/babel/issues/9981#issuecomment-529808712) `chokdiar` issue.
