### ISSUE TITLE
transpiling node_modules that use generators

### ISSUE THREAD

**Issue by hojberg** [babel/babel#1069]
Hi,

Loving babel, but having an issue where i've installed js-csp (which uses generators) and when i run i through browserify and babel it won't transpile with regenerator. The transpilation of regenerator does work for my own code, but not for node_modules.

I've been using

```javascript
require("babel/register")({
  ignore: false
});
```

both with babel-node and regular node - always the same result.

Any advice?

**Comment by cesarandreu** [comment]
Transpiling node_modules is generally frowned upon.

Some options are to pull in the library manually, or use node with the harmony flag, or use iojs. 

I've been using babel-node with iojs, and I disable regenerator. One benefit of this is that you get better stack traces than with regenerator.

**Comment by hojberg** [comment]
Using iojs or node with the harmony wont solve this for me as I need to run it in the browser.
I guess the best option is to pull in those modules manually..

**Comment by sebmck** [comment]
Closing this as this is a question and appears to be resolved. As per the README:

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) before creating an issue.

Thanks!
