### ISSUE TITLE
TypeScript 3.7 featues in @babel/preset-typescript

### ISSUE THREAD

**Issue by kachkaev** [babel/babel#10690]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I upgraded to [TS 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) recently and tried playing with its new features like [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) and [nullish coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing). This syntax was perfectly swallowed by `tsc`, which I use to build my Node.js app. However, I noticed that my Jest tests began to fail – these use `babel` to load `ts` files.

I could remedy the problem by installing two babel plugins and tweaking `babel.config.js`:

```diff
 module.exports = {
   presets: [
     ["@babel/preset-env", { targets: { node: "current" } }],
     ["@babel/preset-typescript"],
   ],
+  plugins: [
+    "@babel/plugin-proposal-nullish-coalescing-operator",
+    "@babel/plugin-proposal-optional-chaining",
+  ],
 };
```

**Describe the solution you'd like**

It'd be great if just upgrading `@babel/preset-typescript` from `7.7.2`to something newer was enough. Could the preset include those plugins I had to add manually? Sorry if this issue is already being discussed – I could not find it after a bit of searching.

**Comment by JLHwung** [comment]
@kachkaev I don't think these two plugins will be added to the typescript preset in the future because
1) They are stage-3 ES proposals and would likely be included in the ECMAScript standard, by that time `preset-env` will include these plugins and you don't have to add these two plugins to your configs
2) `preset-typescript` aims to parse and strip the TypeScript-only language features such as type annotations, interface declarations, etc. Since these two plugins are not TypeScript-only, it would not be included

**Comment by fabb** [comment]
I would also have expected these plugins to be included in the @babel/preset-typescript. The problem is that the new syntax compiles fine when type checking with `tsc`, but fails at run time due to lacking browser support. I‘d suggest adding these plugins to @babel/preset-typescript to bridge the time until preset-env includes them.

**Comment by nicolo-ribaudo** [comment]
Why should we add those plugins to the TypeScript preset and not, for example, `@babel/plugin-transform-classes`?

**Comment by fabb** [comment]
`@babel/plugin-transform-classes` is covered by `preset-env`: https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json

**Comment by nicolo-ribaudo** [comment]
Given that in ~1 month these 2 features will probably become standard, we'll directly add them to preset-env in the next release.

**Comment by azizj1** [comment]
Has this been added yet?

**Comment by nicolo-ribaudo** [comment]
Not yet, but the next minor release (which will include them) will probably be in about 2 weeks.

**Comment by concision** [comment]
Tacking on for visibility - I can create a new issue for this topic if necessary, but it is fairly related in nature to this current issue.

**Problem**:
TypeScript has offered support for numeric seperators for quite some time now (version 2.7), as per their [documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#numeric-separators) (examples included).

However, the `@babel/preset-typescript` preset does not appear to handle numeric separators successfully.

The following snippet (as expected) will pass through babel successfully:
```js
const port: number = 3000;
```

However, a snippet with numeric separators will not:
```js
const port: number = 3_000;
```

The error:
```
Message:
    [REDACTED]\src\example.ts: Identifier directly after number (2:22)

  1 | 
> 2 | const port: number = 3_000;
    |                       ^
  3 | 
  4 | 
  5 | 
```

**Solution**:
Unless I have made a mistake here, the TypeScript preset _should_ come bundled with `@babel/plugin-proposal-numeric-separator` by default.

Adding it as a plugin _does_ resolves this issue, but the TypeScript preset should come with this support out of the box.

There is another issue [#8098](https://github.com/babel/babel/issues/8098) that also notes this discrepancy, but seems to lack attention (last activity: 2018).

Thanks

**Comment by nelsondude** [comment]
Has this been added to preset-env yet?

**Comment by nicolo-ribaudo** [comment]
I hope to publish it tomorrow or during the weekend

**Comment by JLHwung** [comment]
@nicolo-ribaudo I can see a busy Friday/Monday is coming.

**Comment by Maushundb** [comment]
Any update on this?

**Comment by joebowbeer** [comment]
@Maushundb it was published on 1/13 in 7.8.3

**Comment by nicolo-ribaudo** [comment]
Right! Now Babel is able to parse those features by default. So this config will work:
```json
{
  "presets": ["@babel/typescript"]
}
```

Note that if you want to transpile ECMAScript features you'll also need to add `"@babel/preset-env"`.

**Comment by azizj1** [comment]
Doing a `yarn upgrade` on both `@babel/preset-env` and `@babel/preset-typescript` worked for me
