### ISSUE TITLE
@babel/node command broke after installing and uninstalling babel-cli (old package)

### ISSUE THREAD

**Issue by cbdeveloper** [babel/babel#10708]
## Bug Report

**Current Behavior**
`npx babel-node main.js`  is triggering the error below:

```
npx: installed 1 in 1.888s
command not found: babel-node
```

It's weird cause it worked for a while and now is coming back as not found. I even closed and opened VSCode again and the error remained.

In between (from when it was working) I have installed the `babel-cli` (by mistake). Then I removed it and installed the correct one `@babel/cli` and then removed it again.

And this somehow broke the `npx babel-node` command.

**PS:** Now I removed everything and reinstalled and it's working again.

**Input Code**

**package.json**
```
{
  "name": "test-module-imports",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/node": "^7.7.0",
    "@babel/preset-env": "^7.7.1"
  }
}
```

**main.js**
```
async function main() {
  console.log('Inside main function...');
}

main();
```

**Expected behavior/code**

The install and uninstall of the `babel-cli` shouldn't break the `npx babel-node` command.

**Babel Configuration (.babelrc, package.json, cli command)**

**.babelrc**
```
{
  "presets": [
    [
      "@babel/preset-env", {
        "targets": {
          "node": "10"
        }
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): [see package.json]
- Node/npm version: [e.g. Node 10.16.2/npm 6.9.0]
- OS: [Windows 10]
- Monorepo: [?]
- How you are using Babel: [ @babel/node ]

**Possible Solution**

I removed everything and installed again and now it's working fine. Anyway, I don't know if there's something to be done in this situation. But I think it's good to have a record that it happened.

**Additional context/Screenshots**

**Comment by JLHwung** [comment]
You should install `@babel/node` and `@babel/core` before running `npx babel-node`, please refer to https://babeljs.io/docs/en/babel-node#install for more details.

**Comment by cbdeveloper** [comment]
I did. And the `npx babel-node` command was working fine. It only stopped working only after I've added the `babel-cli` (by mistake) package and removed it. Somehow it broke the `babel-node` command.
