### ISSUE TITLE
Babel 7 + Node 12 "Class constructor Transform cannot be invoked without 'new'"  

### ISSUE THREAD

**Issue by 1Jesper1** [babel/babel#10700]
I have a problem error with babel 7: "Class constructor Transform cannot be invoked without 'new'" when not using target node _current_

When using target node _current_ I get the error "ReferenceError: regeneratorRuntime is not defined".
I'm not importing @babel/polyfill, but instead importing:

```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```

```js
{
"@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": 3,
        "modules": false,
        "targets": {
          "node": "current"
        }
      }
}
```

How to fix these errors?

**Environment**
- Babel version(s): [7.7.0]
- Node/npm version: [Node 12]
- OS: [Windows 10]

**Comment by 1Jesper1** [comment]
Was a problem with Prosemirror-state. I have updated all Prosemirror modules.

**Comment by lastnigtic** [comment]
> Was a problem with Prosemirror-state. I have updated all Prosemirror modules.

hello! Have you solved this problem?

**Comment by 1Jesper1** [comment]
@lastnigtic Yes

**Comment by lastnigtic** [comment]
@1Jesper1 Could you share your solution?
Compile the prosemirror dependencies in node_modules?

**Comment by 1Jesper1** [comment]
@lastnigtic It had to do with this version: https://github.com/ProseMirror/prosemirror-commands/blob/master/CHANGELOG.md#bug-fixes-1 It was not compiled to ES5.

**Comment by lastnigtic** [comment]
@1Jesper1 Thanks for your help! Works well
