### ISSUE TITLE
Flow CJS interop notes

### ISSUE THREAD

**Issue by guybedford** [babel/babel#1070]
Just to note here - the latest 0.7 release of Flow supports an interop with CJS modules now that is completely in line with what is done in Babel and SystemJS.

There is one edge case that they have decided to handle differently though, and that is when a CommonJS module exports a `default` export.

In such a scenario, they take the value of `import cjs from 'cjs'` to be the `exports.default` value instead of the `module.exports` value which SystemJS and Babel use.

Thought it worth noting here, feel free to close this though.

I am also open to discussing allowing the `exports.default` value to be given preference if this sounds worthwhile, and for parity as well.

// cc @jeffmo in case I've gotten anything wrong here.

**Comment by sebmck** [comment]
That's similar to what the previous CommonJS interop did but it effected libraries like joi (see #493). I'm up for adopting this behaviour as I love myself a bit of interoperability but what about those cases of people using the `default` export when they don't mean it?

**Comment by jeffmo** [comment]
I'm quite jet lagged at the moment, but one thing that's worth noting is that Flow will initialize the exports object with a 'default' prop that cyclically points back to the exports object.

If a CJS module writes a value to that property via 'exports.default = foo' then doing an import-default will now receive the 'foo' value as the imported value on the ES6 side.

However, if the CJS module does something like module.exports = {default: foo};, I believe flow will return the {default:foo} object as the default export for an import-default

(I kinda want to go back and verify my memory on these details tomorrow when I'm less tired...but I'd say nothing is set in stone here yet -- in case we need to discuss adjusting something in Flow before announcing the CJS interop story more widely)

**Comment by guybedford** [comment]
@jeffmo thanks for clarifying, that helps a lot, and that is more or less what is replicated here in these projects.

The issue @sebmck points out was a real use case where this very behaviour was confusing to users. I forgot about that case, but was wondering if we should consider matching behaviour with what Flow was doing. Will put some more thought to it as well.

It's not that important that we completely align to every edge case anyway, but is really amazing we're on the same page with most of the interop cases.

**Comment by sebmck** [comment]
@guybedford The case was basically:

```javascript
function Foo() {}
Foo.prototype.default = function () {};
module.exports = new Foo;
```

There's most likely more occurrences of it out in the wild.

**Comment by guybedford** [comment]
Closing, as it's a decision already made in Babel. Thanks for the interop chat as always :)
