### ISSUE TITLE
default exports expressed as export {x as default} do not get output as module.exports

### ISSUE THREAD

**Issue by lukeapage** [babel/babel#1071]
The following only applies to non-strict module output options.
```
export default function test() {
};
```
as the only thing in a file, becomes
```
module.exports = function test() {};
```
However
```
function test() {};
export { test as default };
```
is not converted to module.exports but instead becomes
```
function test() {};
exports["default"] = test;
```
Now, I can still have the function and declaration seperate by doing the following...
```
function test() {};
export { test as default };
```
However, reading the spec, it seems export default can only be followed by a class declaration or a function declaration or an assignment of one of those 2.. so the code is invalid (babel doesn't complain though).

What do you think? Should the 2nd example be changed to give the same output as the first (in non-strict module output)?
Should the 3rd example actually give an error?

**Comment by SLonoed** [comment]
Can you provide link to place in spec about this?

**Comment by SLonoed** [comment]
This behavior unexpected. I have module with `export defaut...` and use it in another parts of app. If I add in this module `export var a = 1`, my code become invalid without any notification from babel.

**Comment by lukeapage** [comment]
> Can you provide link to place in spec about this?

Which part? In terms of export default * only being a function/class/generator, Looking at ecma-262-editiion_6_03-17-15-releasecandidate3.pdf section 15.2.3 we have

```
ExportDeclaration :
export * FromClause ; export ExportClause FromClause ; export ExportClause ; export VariableStatement export Declaration export default HoistableDeclaration[Default] export default ClassDeclaration[Default] export default [lookahead  { function, class }] AssignmentExpression[In] ;

where
HoistableDeclaration :
FunctionDeclaration GeneratorDeclaration
```

> This behavior unexpected. I have module with export defaut... and use it in another parts of app. If I add in this module export var a = 1, my code become invalid without any notification from babel.

Which behaviour? Taking this example..

```
export default function test() {};
export { test as b };
```
babel produces this...
```
exports["default"] = test;
...
exports.b = test;
```
which looks correct to me - there is an export as well as a default export, so babel cannot make it compatible using `module.exports` and must instead assign test to a named default export and a named "b" export.

The main problem for me is that this code
```
function test() {};
export { test as default };
```
on its own is not recognised as a single default export and therefore converted to `module.exports`.

**Comment by joliss** [comment]
Just a heads up: I remember having conversations[1] in the past trying to come up with a way to support exposing default exports on `module.exports` (rather than `module.exports['default']`), and the upshot was that there basically isn't a spec-compliant way to do this, without sacrificing support for circular imports or live binding (#1117).

[1] in person and on https://github.com/esnext/es6-module-transpiler/issues/85 (I don't expect anyone to read this monstrosity)

**Comment by lukeapage** [comment]
@joliss indeed I didn't read all of that bug, just the top bit, but it seems that the bug is about what babel has already solved - http://babeljs.io/docs/usage/modules/

this bug is just about two statements
```
export default F;
export {F as default};
```
which have the same meaning in es-6 but which are transpiled differently.

**Comment by lukeapage** [comment]
@sebmck is this high on your radar or not important to you? if the latter, would you accept a PR (assuming I work out why my tests are not working!) not 100% sure I'll get the time, but might be interesting.. My colleague feels strongly that exports should all happen at the bottom of the file...

**Comment by sebmck** [comment]
@lukeapage I'll look into it in the next hour or so. I've been caught up with preparation for 5.0.0 but rest assured it will be addressed.

**Comment by sebmck** [comment]
Fixed in the `experimental` branch. I can push out a new beta release if you'd like.

**Comment by lukeapage** [comment]
wow, thanks very much. I'll just try it from the github commit hash and change to a tag when its released, no hurry.

**Comment by lukeapage** [comment]
tested and it looks good, thanks.

Notice you didn't ban the following expressions that are spec invalid:
```
export default a;
```
I guess that's because you may as well silently let them work and let a tool like jshint complain about them?

**Comment by sebmck** [comment]
@lukeapage Except it is valid?

**Comment by lukeapage** [comment]
I may have read the spec wrong.. did you see my links to the spec above? It
did surprise me but the grammar seemed specific.

**Comment by sebmck** [comment]
@lukeapage 

```
export default [lookahead  { function, class }] AssignmentExpression[In] ;
```

**Comment by lukeapage** [comment]
Ah i thought the lookahead meant the assignment expression had to be that
type. Thanks.
