### ISSUE TITLE
"useBuiltIns" in preset-env cannot handle mixing cjs and esm modules with webpack

### ISSUE THREAD

**Issue by ZeeCoder** [babel/babel#10745]
## Bug Report

**Current Behavior**

Repo that reproduces the issue:
https://github.com/ZeeCoder/babel-preset-env-usebuiltins-error-repro

The way I noticed this was that I wanted to switch from including all polyfills from core-js (via the now deprecated @babel/polyfill) to have preset-env inject only the necessary bits based on usage.

When I enabled this however, I started to get a warning, similar to this one I reproduced in the above repo:
![error](https://user-images.githubusercontent.com/3679506/69328386-6f735300-0c4f-11ea-805e-d27b7823bf01.jpg)

This was an issue with some packages that we opted in to transpile within node_modules.
(For example [delay](https://github.com/sindresorhus/delay))

After tons of debugging, I found that babel was injecting import statements that were not working with webpack. (Seems to be related to the so-called "harmony" modules, but I found no references to it.)

I managed to reproduce the issue with the minimalistic example in the above repo, but essentially the problem is that when preset-env adds the import based on usage, it only works if the module formats match.
In my case: if the module that gets "polyfilled" is esm, then everything is fine, however when it's in cjs, I get the above warning.

It seems to me that the issue stems from preset-env adding import statements that are somehow not compatible with webpack anymore.
(Maybe adding "es6 imports" to a cjs module?)

I unfortunately couldn't figure out more than that by myself. 🙏

Oh, one more thing: with `module: "cjs"` it works.
(if I essentially force transpile everything to CJS)
But then I opt-out of tree-shaking via webpack. 🤷‍♂️

**Expected behavior/code**
I expected `useBuiltIn: "usage"` to work regardless of the module format it happens to polyfill.

**Environment**
```
- Babel version: 7.7.2
- webpack version: 4.41.2
- Node/yarn version: [e.g. Node 10.16.3/yarn 1.19.1]
- OS: Ubuntu Linux 18.04 LTS
- How you are using Babel: `loader`
```

**Possible Solution**
I suspect preset-env needs to add the import statements somehow differently based on the module it's processing for things to work properly.

**Comment by nicolo-ribaudo** [comment]
Using Babel's `override` config option, you can set the `sourceType: script` option for those dependencies: Babel will then directly inject `require` calls

**Comment by ZeeCoder** [comment]
Adding `"sourceType": "unambiguous" ` to the babel options worked!
Thanks @nicolo-ribaudo , and also @loganfsmyth who gave me answers on Slack, you guys rock! :raised_hands:
