### ISSUE TITLE
latest version on npmjs registry is still v7.7.2

### ISSUE THREAD

**Issue by chenrui333** [babel/babel#10750]
just FYI, the latest version on npmjs registry is still v7.7.2. Thanks!
`https://registry.npmjs.org/@babel/core`

**Comment by chenrui333** [comment]
Thanks @babel-bot, totally understand. Just to let the team know about this issue though. :)

**Comment by nicolo-ribaudo** [comment]
Thanks! It's because we only publish changed packages.
