### ISSUE TITLE
es6.blockScopingTDZ in non-strict mode with default args breaks

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#1075]
Accidentally discovered because we weren't running some of our code in strict mode when we thought we were. I'll just be fixing the "use strict" usage so not a huge priority for us. Just wanted to let you know.

Example input: Compiled without `strict` but with blockScopingTDZ
```
(function fn(arg, arg2='arg2'){
    console.log(arg, arg2);
})('arg')
```

results in

```
var _temporalAssertDefined = function (val, name, undef) { if (val === undef) { throw new ReferenceError(name + " is not defined - temporal dead zone"); } return true; };

var _temporalUndefined = {};
(function fn(arg) {
  var arg = _temporalUndefined;
  var arg2 = _temporalUndefined;
  arg = arguments[0] === undefined ? undefined : arguments[0];
  arg2 = arguments[1] === undefined ? "arg2" : arguments[1];
  console.log(_temporalAssertDefined(arg, "arg", _temporalUndefined) && arg, _temporalAssertDefined(arg2, "arg2", _temporalUndefined) && arg2);
})("arg");
```
In non-strict mode, that `var arg = _temporalUndefined` also changes `arguments[0]` because `arg` is a live binding to `arguments[0]`. So `arg = arguments[0] === undefined ? undefined : arguments[0];` ends up actually being `arg = _temporalUndefined === undefined ? undefined : _temporalUndefined;` and therefore is a no-op.

It doesn't seem like `arg` needed to be processed by TDZ anyway, so perhaps only processing TDZ on `arg2` is the real fix here?

**Comment by sebmck** [comment]
Dunno if I want to support or go out of my for the use-cases of blacklisting `strict` since you're deviating from what's spec compliant.

**Comment by sebmck** [comment]
Going to mark this as a `wontfix` since I don't want to encourage the non-use of strict mode.

**Comment by loganfsmyth** [comment]
@sebmck Totally fine with this not being fixed. Is there any way Babel could throw an error if you try to use this without strict mode though? It was tough to track down. Or at least a note on the transform that says it requires the file to be in strict mode.
