### ISSUE TITLE
Babel tries to import non existing package from core-js@3+

### ISSUE THREAD

**Issue by alekslario** [babel/babel#10751]
## Bug Report
**Current Behavior**
Babel tries to import non existing package from core-js@3+
```js
Cannot find module 'core-js/modules/es7.array.includes'
```
In core-js@3+ files are renamed and what used to be es7, es6 => now are es, esnext

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = function(api) {
  api.cache(true);

  const presets = [
     [
       "@babel/preset-env",
       {
         useBuiltIns: "usage",
         corejs: 3
       }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript",
    "linaria/babel"
  ];
  const plugins = [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-nullish-coalescing-operator"
  ];

  return {
    presets,
    plugins
  };
};
```
- Babel version(s): [7.5.5]
- Node/npm version: [e.g. Node 12.13.1/npm 6.7.0]
- OS: [ Windows 7]
- Monorepo: [no]
- How you are using Babel: [`loader`]

**Possible Solution**
Downgrading to 2.6.5 core-js  solves the issue.

**Comment by JLHwung** [comment]
Could you attach your babel-loader configuration?

**Comment by alekslario** [comment]
I narrowed it down to "linaria/babel". Closing.
