### ISSUE TITLE
Version Numbers Out of Sync

### ISSUE THREAD

**Issue by JustinHaight** [babel/babel#10760]
Version numbers aren't all in sync. With the latest `v7.7.4`, most of the packages were updated but the following weren't bumped:
* babel-core-frame
* babel-helper-fixtures
* babel-helper-plugin-utils
* babel-helper-regex
* babel-highlight
* babel-polyfill

**Comment by JustinHaight** [comment]
I'm willing to bump the versions in a PR if you'd like?

**Comment by nicolo-ribaudo** [comment]
We only publish packages whose source has changed, to avoid publishing 150+ packages each time
