### ISSUE TITLE
babel cdn

### ISSUE THREAD

**Issue by fellowT** [babel/babel#10765]
Can the introduction of CDN be introduced as needed  ,I just need to compile JSX

**Comment by JLHwung** [comment]
You can use the JSDelivr CDN: https://www.jsdelivr.com/package/npm/@babel/standalone and please refer to [@babel/standalone docs](https://babeljs.io/docs/en/babel-standalone) for its usage.

I assume that you are looking for a CDN used in PRC. I did a latency test and the result is [acceptable](http://www.17ce.com/site/http/201804_4f1b4607283bbef07550aae615a630a5.html).
