### ISSUE TITLE
Trailing comma in typescript spread

### ISSUE THREAD

**Issue by jandolezal71** [babel/babel#10769]
## Bug Report

Hi,

we have problem with trailing comma in typescript after upgrade to `@babel/core` to `7.7.4`.

We installed new prettier (https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1182), which was injected trailing comma after rest in type, but `babel-parser` don't like it.

`tsc` command will not produce any errors, so trailing commas are fine in TS.

Cannot be this relevant to "final fix" https://github.com/babel/babel/pull/10491 ?

Error:
```
SyntaxError: /my-project/src/file.ts: Unexpected trailing comma after rest element (12:12)

  10 | 	string,
  11 | 	string,
> 12 | 	...string[],
     | 	           ^
  13 | ];
  14 | 
  15 | export default function createChainableTypeChecker<T>(
    at Object.raise (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6975:17)
    at Object.raiseTrailingCommaAfterRest (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8881:10)
    at Object.checkCommaAfterRest (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8869:14)
    at Object.tsParseTupleElementType (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:4876:12)
    at Object.tsParseDelimitedListWorker (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:4519:23)
    at Object.tsParseDelimitedList (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:4508:25)
    at Object.tsParseBracketedList (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:4554:25)
    at Object.tsParseTupleType (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:4859:30)
    at Object.tsParseNonArrayType (/my-project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5001:21)
```

Ts file:
```ts
type ValidateArgs = [
	{
		[key: string]: any;
	},
	string,
	string,
	...string[],
];
```

package.json

```
    "@babel/core": "^7.7.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@babel/preset-typescript": "^7.7.4",
```

- Babel version(s): 7.7.4
- Node/npm version: 12.10
- OS: Ubuntu 19
- Prettier: 1.19.1

**Comment by JLHwung** [comment]
This issue can [reproduced](https://lihautan.com/babel-ast-explorer/#?eyJiYWJlbFNldHRpbmdzIjp7InZlcnNpb24iOiI3LjAuMCIsIm9wdGlvbmFsQ2hhaW5pbmciOnsib3B0aW9ucyI6e30sImVuYWJsZWQiOmZhbHNlfSwiZHluYW1pY0ltcG9ydCI6eyJvcHRpb25zIjp7fSwiZW5hYmxlZCI6ZmFsc2V9LCJjbGFzc1Byb3BlcnRpZXMiOnsib3B0aW9ucyI6e30sImVuYWJsZWQiOmZhbHNlfSwidHlwZXNjcmlwdCI6eyJvcHRpb25zIjp7fSwiZW5hYmxlZCI6dHJ1ZX19LCJ0cmVlU2V0dGluZ3MiOnsiaGlkZUVtcHR5Ijp0cnVlLCJoaWRlTG9jYXRpb24iOnRydWUsImhpZGVUeXBlIjp0cnVlLCJoaWRlQ29tbWVudHMiOnRydWV9LCJjb2RlIjoidHlwZSBmb28gPSBbXG4gLi4uc3RyaW5nW10sXG5dIn0=) in babel 7.0.0. So it's not a regression.

**Comment by nicolo-ribaudo** [comment]
Even if it is not a regression, this is highly problematic because it doesn't work with the output automatically generated by prettier.

**Comment by nicolo-ribaudo** [comment]
I believe that this is a bug in TypeScript itself, and I have opened an issue asking which is the correct behavior.

https://github.com/microsoft/TypeScript/issues/35375

**Comment by jandolezal71** [comment]
Thank you Nicolò for processing this request.

**Comment by nicolo-ribaudo** [comment]
If anyone wants to submit a PR, probably deleting the check for the rest comma from the `tsParseTupleElementType` parser function would be enough, but we'll also need tests.

https://github.com/babel/babel/blob/cfd26fdbf27a4c3eae2311ca145e36bc13dd2abc/packages/babel-parser/src/plugins/typescript/index.js#L615

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.json` will be automatically generated)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.json` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by yeonjuan** [comment]
@nicolo-ribaudo I will pick this up :)

**Comment by nicolo-ribaudo** [comment]
Sure!
