### ISSUE TITLE
Fat Arrow in ES6 class method definition

### ISSUE THREAD

**Issue by palamccc** [babel/babel#1076]
According to https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html (Autobinding section) , ES6 methods can be forced to bind to 'this' using syntax, 

    class Counter extends React.Component {
      tick = () => {
        ...
      }
      ...
    }

This syntax is not working in babel,  is it react documentation issue, is it valid ES6 ? or is it babel issue ?

**Comment by sebmck** [comment]
Please see #619

On Tuesday, 24 March 2015, palamccc <notifications@github.com> wrote:

> According to
> https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html
> (Autobinding section) , ES6 methods can be forced to bind to 'this' using
> syntax,
>
> class Counter extends React.Component {
>   tick = () => {
>     ...
>   }
>   ...
> }
>
> This syntax is not working in babel, is it react documentation issue, is
> it valid ES6 ? or is it babel issue ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1076>.
>


-- 
Sebastian McKenzie
