### ISSUE TITLE
Mocha and Babel 7 register not found

### ISSUE THREAD

**Issue by gear4s** [babel/babel#10777]
## Bug Report

**Current Behavior**
Mocha can't find module
`✖ ERROR: Cannot find module '@babel/register'`

**Input Code**
- REPL or Repo link if applicable:

**Expected behavior/code**
Mocha should require @babel/register

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`
```js
{
	plugins: [
		"@babel/transform-arrow-functions",
		"@babel/proposal-optional-chaining",
		"@babel/proposal-export-default-from",
		"@babel/proposal-class-properties",
		"require-context-hook"
	],

	presets: [
		[
			"@babel/env",
			{
				targets: {
					node: "10"
				},
				useBuiltIns: "usage",
				corejs: 3
			}
		]
	]
}
```

**Environment**
```
  System:
    OS: Linux 5.3 Arch Linux
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  npmPackages:
    @babel/cli: ^7.7.0 => 7.7.4 
    @babel/core: ^7.7.2 => 7.7.4 
    @babel/plugin-proposal-class-properties: ^7.7.0 => 7.7.4 
    @babel/plugin-proposal-export-default-from: ^7.5.2 => 7.7.4 
    @babel/plugin-proposal-optional-chaining: ^7.6.0 => 7.7.4 
    @babel/preset-env: ^7.7.1 => 7.7.4 
    @babel/register: ^7.7.4 => 7.7.4 
    babel-plugin-require-context-hook: ^1.0.0 => 1.0.0
```

**Additional context/Screenshots**
Run with:
`mocha -r @babel/register -r test/__fixtures/chai-plugins --recursive test/unitnpx envinfo --preset babel`

**Comment by futagoza** [comment]
You might need to pass `-r babel-plugin-require-context-hook/register` to mocha when using [babel-plugin-require-context-hook](https://www.npmjs.com/package/babel-plugin-require-context-hook)

**Comment by gear4s** [comment]
Thanks for replying @futagoza 

I now get the error that context hook register does not exist:
` ERROR: Cannot find module 'babel-plugin-require-context-hook/register'`

I'm also using the test/mocha.opts

**Comment by futagoza** [comment]
Try these (just to debug, they wont let you use `require.context`):
- exclude `babel-plugin-require-context-hook` entirely
- other register hooks (e.g. `ts-node/register`)

If neither of these work, it's either a problem with mocha (most likely) or your node installation

**Comment by gear4s** [comment]
I got it working, thanks for pointing out mocha and node installation

Issue was that mocha was in the global installed modules, and not part of dev dependencies. I've installed it into my project's dev deps and reinstalled node on nvm.

Thanks a lot!

**Comment by JLHwung** [comment]
@gear4s I am glad that your issue is resolved.
