### ISSUE TITLE
latest @babel/runtime + transform-runtime plugin yields "_typeof4.default is not a function" on compiled output

### ISSUE THREAD

**Issue by niftylettuce** [babel/babel#10773]
```sh
  /Users/user/Projects/frisbee/evalmachine.<anonymous>:161

    if (typeof Symbol === "function" && (0, _typeof4.default)(Symbol.iterator) === "symbol") {
                                                             ^

  TypeError: (0 , _typeof4.default) is not a function
```

`_typeof4` is an object that is `{ default: { } }`

It's not a function and it's trying to be invoked.

`.babelrc` contents:

```sh
{
  "presets": [
    [
      "@babel/env", {
        "debug": true,
        "targets": {
          "browsers": "extends @ladjs/browserslist-config"
        }
      }
    ]
  ],
  "plugins": [ "@babel/transform-runtime" ],
  "sourceMaps": "both"
}
```

Using latest versions of babel/everything.

**Comment by niftylettuce** [comment]
Seems related to https://github.com/babel/babel/issues/8731

**Comment by niftylettuce** [comment]
The fix described in #8731 worked for me.

**Comment by Tarpsvo** [comment]
Running into the same issue, but the described fixed didn't help me.

**Comment by nicolo-ribaudo** [comment]
@niftylettuce @Tarpsvo What are your input files?

**Comment by niftylettuce** [comment]
@nicolo-ribaudo https://github.com/niftylettuce/frisbee and you can see how I managed to workaround this via https://github.com/niftylettuce/frisbee/blob/master/.dist.babelrc.config.js

**Comment by nicolo-ribaudo** [comment]
@niftylettuce This isn't a bug but an unfortunate behavior which isn't really possible to fix, and your "workaround" is the correct way to do it.

A few days ago you changed your `browserify` command to compile every file 
(thus, also your `node_modules` folder) instead of only your own files (https://github.com/niftylettuce/frisbee/commit/dab117527b8c96abf682e48692a9926cb2ac6ce1).

This means that you were also transpiling `@babel/runtime`.

Consider this helper:
```js
module.exports = function _typeof(obj) {
  if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") {
    _typeof = function (obj) { return typeof obj; };
  } else {
    _typeof = function (obj) {
      return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype
        ? "symbol"
        : typeof obj;
    };
  }
  return _typeof(obj);
}
```
As you can see, it includes `typeof Symbol.iterator === "symbol"`, which should get transpiled:
```js
var _typeofHelper = require("typeof-helper");

// ...

_typeofHelper(Symbol.iterator) === "symbol"
```

This causes a circular dependency of the file on itself: the function that it exports needs itself to run. Due to CommonJS's semantics, it causes an "object is not a function" error; which ECMAScript modules you would probably get a "Maximum call stack size exceeded" error.

The only way to avoid this problem is to _not_ transpile the imported helpers, or at least to not transpile them using `@babel/plugin-transform-runtime`. The same happens to `core-js`.

**Comment by Tarpsvo** [comment]
I have a huge non-open-source project with the issue. The breaking commit for me was this:
![image](https://user-images.githubusercontent.com/2018660/69947799-14671900-14f7-11ea-8bbc-d83ad415d5d4.png)

Nothing else changed and nothing I've tried helps.

Babel excludes:
```
const babelExcludes = /node_modules[\/\\](?!(@optimistdigital[\/\\]create-frontend)[\/\\]).*/; // Exclude everything except create-frontend code

{
    test: /\.(js|mjs)$/,
    exclude: babelExcludes,
    use: [
        {
            loader: require.resolve('babel-loader'),
            options: babelOpts,
        },
    ],
},
```

Babel ignore:
```
module.exports = {
    presets: [
        ['@babel/preset-env', { corejs, modules: false, useBuiltIns: 'entry' }],
        '@babel/preset-react',
    ],
    plugins: [
        require.resolve('babel-plugin-dev-expression'),
        require.resolve('@babel/plugin-proposal-object-rest-spread'),
        [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }],
        [require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }],
        require.resolve('@babel/plugin-transform-react-display-name'),
        [require.resolve('@babel/plugin-transform-runtime'), { corejs: 3 }],
        require.resolve('babel-plugin-lodash'),
    ],
    ignore: [/[\/\\]core-js/, /@babel[\/\\]runtime/],
};
```

**Comment by nicolo-ribaudo** [comment]
Without a reproducible demo it's really hard for us to debug the issue :confused: 

1. Can you share the stack trace of the error?
2. `ignore` shouldn't be needed, since you are already telling webpack not to compile your `node_modules` except for `create-frontend`

**Comment by Tarpsvo** [comment]
Stack trace:
```
console.trace()
   at Anonymous function (eval code:20:7)
   at toString (eval code:178:5)
   at hoistNonReactStatics (eval code:86:7)
   at hoistNonReactStatics (eval code:70:9)
   at withRouter (eval code:730:3)
   at eval code (eval code:70:1)
   at ./node_modules/@optimistdigital/create-frontend/universal-react/Router.js (http://192.168.1.65:3000/app.js:4819:1)
   at __webpack_require__ (http://192.168.1.65:3000/app.js:727:12)
Incompatible receiver, Symbol required
SCRIPT5022: Exception thrown and not caught
eval code (431) (22,7)
```
 
`internal-state.js`
![aha](https://i.imgur.com/ty8r7Rw.png)

I'll also try to make a reproducible example, but it might be a while.

**Comment by nicolo-ribaudo** [comment]
After https://github.com/babel/babel/pull/11049, transpiling the `typeof` helper shouldn't cause problems.
