### ISSUE TITLE
Constructors should be able to contain declarations with the same identifier as the class

### ISSUE THREAD

**Issue by jamesallardice** [babel/babel#1077]
Given a class with an identifier `Example`, a declaration with that same identifier in the class constructor will throw a `TypeError`:

```js
class Example {
  constructor() {
    var Example;
  }
}

let t = new Example(); // Throws TypeError
```

The reason for this is the attempt to reference the constructor function by identifier from itself:

```js
"use strict";

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

var Example = function Example() {
  _classCallCheck(this, Example); // Example has been shadowed by the local var

  var Example;
};

var t = new Example();
```

**Comment by sebmck** [comment]
Spec citation please

On Wednesday, 25 March 2015, James Allardice <notifications@github.com>
wrote:

> Given a class with an identifier Example, a declaration with that same
> identifier in the class constructor will throw a TypeError:
>
> class Example {
>   constructor() {
>     var Example;
>   }
> }
> let t = new Example(); // Throws TypeError
>
> The reason for this is the attempt to reference the constructor function
> by identifier from itself:
>
> "use strict";
> var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };
> var Example = function Example() {
>   _classCallCheck(this, Example); // Example has been shadowed by the local var
>
>   var Example;
> };
> var t = new Example();
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1077>.
>


-- 
Sebastian McKenzie

**Comment by fkling** [comment]
@sebmck: This seems to be a Babel bug, what exactly do you want from the spec? Do you think it's disallowed to have a local variable in the constructor with the same name as the class?

**Comment by sebmck** [comment]
Oh right. I thought it was that it was allowed when it shouldn't be.

On Wednesday, 25 March 2015, Felix Kling <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck>: This seems to be a Babel bug, what
> exactly do you want from the spec? Do you think it's disallowed to have a
> local variable in the constructor with the same name as the class?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1077#issuecomment-85577333>.
>


-- 
Sebastian McKenzie

**Comment by jamesallardice** [comment]
@sebmck I've changed the title, hopefully that's a bit clearer now.

**Comment by sebmck** [comment]
Sorry for the delay. Fixed in the `experimental` branch which will be released very soon, thanks!
