### ISSUE TITLE
rewriteThis in helper-module-transforms misses computed class elements

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#10784]
## Bug Report

**Current Behavior**
The transformed code does not throw an expected error.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4GE4G84DaMAFgJZoB0AdigLbAC6AFAJR4C-c7QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.7.4

```js
export class C { [this.name]() {} }
```

**Expected behavior/code**
The transformed code should throw _can not read property `name` of undefined_. Because `this` is the top level context, which is `undefined` if the source type is `module`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": ["@babel/plugin-transform-modules-commonjs"]
}
```

**Environment**

```

  System:
    OS: macOS 10.15.1
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Monorepos:
    Lerna: 3.19.0
  npmPackages:
    @babel/cli: ^7.7.0 => 7.7.0 
    @babel/core: ^7.7.2 => 7.7.2 
    @babel/eslint-plugin-development: ^1.0.1 => 1.0.1 
    @babel/plugin-proposal-class-properties: ^7.7.0 => 7.7.0 
    @babel/plugin-proposal-export-namespace-from: ^7.5.2 => 7.5.2 
    @babel/plugin-proposal-nullish-coalescing-operator: ^7.4.4 => 7.4.4 
    @babel/plugin-proposal-numeric-separator: ^7.2.0 => 7.2.0 
    @babel/plugin-proposal-object-rest-spread: ^7.7.4 => 7.7.4 
    @babel/plugin-proposal-optional-chaining: ^7.6.0 => 7.6.0 
    @babel/plugin-transform-flow-strip-types: ^7.7.4 => 7.7.4 
    @babel/plugin-transform-for-of: ^7.7.4 => 7.7.4 
    @babel/plugin-transform-modules-commonjs: ^7.7.0 => 7.7.0 
    @babel/plugin-transform-runtime: ^7.6.2 => 7.6.2 
    @babel/preset-env: ^7.7.1 => 7.7.1 
    @babel/preset-flow: ^7.0.0 => 7.0.0 
    @babel/register: ^7.7.0 => 7.7.0 
    @babel/runtime: ^7.7.2 => 7.7.2 
    babel-eslint: ^11.0.0-beta.1 => 11.0.0-beta.1 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-plugin-transform-charcodes: ^0.2.0 => 0.2.0 
    eslint: ^6.0.1 => 6.0.1 
    eslint-config-babel: ^9.0.0 => 9.0.0 
    gulp-babel: ^8.0.0 => 8.0.0 
    jest: ^24.9.0 => 24.9.0 
    lerna: ^3.19.0 => 3.19.0 
    rollup-plugin-babel: ^4.0.0 => 4.3.3 
```

**Possible Solution**
https://github.com/babel/babel/blob/a6e8b3843b53c6e106d9fb2e37fea60c306dd97c/packages/babel-helper-module-transforms/src/rewrite-this.js#L17

1) Should traverse computed `ClassMethod`
2) requeue the `key` child of `ClassProperty` if it is computed. This step is to fix the following case
```js
export class C { [this.name] = 42 }
```

**Comment by sidntrivedi012** [comment]
I would like to work on this. 🙂

**Comment by sidntrivedi012** [comment]
@JLHwung I was working on this. Wanted to ask that how and where should I requeue the `key` child of `ClassProperty`?
