### ISSUE TITLE
the `var` declaration is missing with the default function parameters scope

### ISSUE THREAD

**Issue by guox191** [babel/babel#10798]
## Bug Report

**Current Behavior**

Playground:
https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABFApgZygClJRBeRTASnwD5EBvAKEUQDcBDAJ0Qf0QEYBuGxCBNHAA2KAHRC4Ac0wMiPAL4lqtRiwAOTFHXgg07AAwKuQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.7.4&externalPlugins=

**Input Code**
```js
function test(func = () => {
  var a = 1;
  console.log(a);
}) {
  var previous = 0;
};
```
Translate these with es2015 presets, the result is:
```js
"use strict";

function test() {
  var func = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : function () {
    var a = 1;
    console.log(a);
  };
  return function () {
    previous = 0;
  }();
}

;
```
We can see that the generated function returns a closure, and the various `previous` is not declared in the closure.

in strict mode, we will get the exception:
`Uncaught ReferenceError: previous is not defined`

**Expected behavior/code**
The `var` expression won't be removed.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Babel playground with es2015 preset config.

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/9742995/70054907-6ac97a00-1613-11ea-9800-6b48e7a2af94.png)

**Comment by guox191** [comment]
Any updates?

**Comment by smelukov** [comment]
I'm trying to research and solve it ☺️

**Comment by smelukov** [comment]
I think that I've found the reason:

- https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-parameters/src/params.js#L149 - at this point we use `callDelegate` helper
- https://github.com/babel/babel/blob/master/packages/babel-helper-call-delegate/src/index.js#L35 - at this point we use `hoistVariables`(there is a todo, maybe it is a reason?)
https://github.com/babel/babel/blob/master/packages/babel-helper-hoist-variables/src/index.js#L40 - and finally at this point, we replace `VariableDeclaration` with multiple `AssignmentExpression`

@nicolo-ribaudo I have a question here (cause, for now, I'm not so familiar with babel internals):
If `hoistVariables` replaces `VariableDeclaration` with multiple `AssignmentExpression` then it should add another `VariableDeclaration` with empty `init` props on `VariableDeclarator` to the top of the function? Where is it happen?

Thanks

**Comment by nicolo-ribaudo** [comment]
```
id => scope.push({ id })
```

This code, which is passes as a parameter to `VariableDeclaration` should already add the variables without initializer to the scope. Maybe that function isn't always called by `hoistVariables`?

**Comment by JLHwung** [comment]
This is a regression introduced by #10053.

**Comment by homobel** [comment]
I think issue I've met related to this one but in my case it related to **this**.
https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBC0G8C-AoFpIwILQKYA8AXXAOwBMZ4EUBIYAexIkICcBXYQ-lgChLAC2uADTRgAI2gBeaDwCU0gHxjGEeiFwA6EPQDmPQgAsAlhE38hchdRo0IbAA65ecgNxpbR0-cG5p0C1x3TxMzCX8JYNRUdFVCaDB_ElwAd2gsHgByADF6eky3FDBNCXl3IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.7.7&externalPlugins=

So it says _this is undefined.

**Comment by JLHwung** [comment]
@smelukov Looking into the code

https://github.com/babel/babel/blob/e9dc74e78768988c51e21741ba982c7240fd30b8/packages/babel-helper-call-delegate/src/index.js#L35

and

https://github.com/babel/babel/blob/e9dc74e78768988c51e21741ba982c7240fd30b8/packages/babel-helper-hoist-variables/src/index.js#L32

I think the timing of registering declaration is incorrect. While `state.emit` looks like a callback executed after the `path` is replaced by assignment expressions

https://github.com/babel/babel/blob/e9dc74e78768988c51e21741ba982c7240fd30b8/packages/babel-helper-hoist-variables/src/index.js#L40

it is actually executed _before_ the `path` is replaced. Therefore the inserted variable declarators from `scope.push` is also replaced.

We can delay the timing of `scope.push` after we collect an array of declared variables.

**Comment by JLHwung** [comment]
@homobel Thanks for the reproduction case! Yes it is the same issue.

**Comment by JLHwung** [comment]
@smelukov Are you still working on this issue? If you have any questions about developing a fix, feel free to ask in `#development` channel.

**Comment by openorclose** [comment]
Tried on this pr https://github.com/babel/babel/pull/11158,

and got this which should be right:

```js
function test() {
  var func = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : function () {
    var a = 1;
    console.log(a);
  };
  return function () {
    var previous = 0;
  }();
}

;
```

**Comment by homobel** [comment]
Hi guys my case with "this" seems not fixed.

**Comment by homobel** [comment]
@nicolo-ribaudo @JLHwung  Unfortunately #11158 fix not resolved issue with default parameter with "this"(7.9.6) I've mentioned above.

```
class B {}

class A extends B {
	constructor(name, cb = () => console.log(this.name)) {
		super();

		this.name = name;
		this.cb = cb;
	}
}

const a = new A('Foo');
a.cb();
```
Produces:

```
let B = function B() {
  _classCallCheck(this, B);
};

let A = /*#__PURE__*/function (_B) {
  _inherits(A, _B);

  var _super = _createSuper(A);

  function A(name) {
    var _this2 = this;

    let cb = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : () => console.log(_this.name);
    return function () {
      var _this;

      _classCallCheck(_this2, A);

      _this = _super.call(_this2);
      _this.name = name;
      _this.cb = cb;
      return _this;
    }();
  }

  return A;
}(B);

const a = new A('Foo');
a.cb();
```
With same "_this is not defined" error.

I'm not sure about approaches here used but I've checked example on playground with only @babel/plugin-transform-classes enabled and it produce also invalid code(same error):
```
let B = function B() {
  _classCallCheck(this, B);
};

let A = /*#__PURE__*/function (_B) {
  _inherits(A, _B);

  var _super = _createSuper(A);

  function A(name, cb = () => console.log(_this.name)) {
    var _this;

    _classCallCheck(this, A);

    _this = _super.call(this);
    _this.name = name;
    _this.cb = cb;
    return _this;
  }

  return A;
}(B);

const a = new A('Foo');
a.cb();
```
So probably here is the issue with shared responsibility(classes plugin shouldn't take default args but produces invalid code then and parameters plugin on the other hand should produce valid code on the top of invalid one).

Also here is version of ts compiler which is works as example:
```
var B = /** @class */ (function () {
    function B() {
    }
    return B;
}());
var A = /** @class */ (function (_super) {
    __extends(A, _super);
    function A(name, cb) {
        if (cb === void 0) { cb = function () { return console.log(_this.name); }; }
        var _this = _super.call(this) || this;
        _this.name = name;
        _this.cb = cb;
        return _this;
    }
    return A;
}(B));
var a = new A('Foo');
a.cb();
```
