### ISSUE TITLE
Class definitions should be able to contain a static `name` method

### ISSUE THREAD

**Issue by jamesallardice** [babel/babel#1079]
Per [14.5.16](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions-runtime-semantics-evaluation) class definitions should be able to contain a static `name` method which is not overwritten by the `name` data property of the class. The following will throw "cannot redefine property":

```js
class Example {
  static get name() { 
    return 'Something else';
  }
}
```

**Comment by zloirock** [comment]
In actual browsers functions `name` property non-configurable, cantfix.

**Comment by jamesallardice** [comment]
Ah, yeah that would be a bit of a problem!
