### ISSUE TITLE
@babel/plugin-proposal-optional-chaining works for tests but not for prod code

### ISSUE THREAD

**Issue by fasaas** [babel/babel#10799]
## Bug Report

**Current Behavior**
I am having a piece of code with the optional chaining to avoid deep level nest checking, and I wanted to give this plugin a try.
I am very successful in testing the code, and all my tests pass, but when I do `react-scripts start` I get the following error `Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.`

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`
```js
module.exports = api => {
  api.cache(false);
  return {
    presets: [
      [
        "@babel/preset-env",
        {
          targets: {
            node: "current"
          }
        }
      ],
      "@babel/preset-react"
    ],
    plugins: [
      "@babel/plugin-proposal-optional-chaining",
      [
        "@babel/plugin-proposal-class-properties",
        {
          loose: true
        }
      ]
    ]
  };
};

```

**Expected behavior/code**
I would expect when typing `yarn run start` or `yarn run build` to have the compiled code with the transformed optional chaining.

- Babel version(s): [@babel/core@7.6.0]
- Node/npm version: [e.g. Node 10.16.3/npm 6.11.3]
- OS: [Windows 10]
- How you are using Babel: [handtyping `babel.config.js`]

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/4102787/70054932-cc202780-15d8-11ea-8704-2c9752c71be4.png)

**Comment by JLHwung** [comment]
`create-react-apps` does not respect the top level `babel.config.js`, so the behaviour here is expected.

However, the good news is that create-react-apps will include optional chaining in the upcoming 3.3 release. See https://github.com/facebook/create-react-app/issues/7981 if you would like to try on 3.3 beta.

**Comment by fasaas** [comment]
@JLHwung Thanks for the quick answer.
I am not very clear on what you mean by the `top level babel.config.js`, could you enlighten me?
Furthermore, it's kinda curious that react-scripts takes `babel.config.js` into account but not for that particular plugin.

Thanks again.
