### ISSUE TITLE
dependency on core-js v2 which is deprecated.

### ISSUE THREAD

**Issue by theshashiverma** [babel/babel#10791]
# v7 Regression

> First check out: https://babeljs.io/docs/en/v7-migration
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Potential Commit/PR that introduced the regression**
If you have time to investigate, what PR/date introduced this issue.

**Describe the regression**
A clear and concise description of what the regression is.

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

I am using @babel/polyfill and it has its dependency on core-js version 2. The thing is i'm getting warning in my console that core-js v2 is depricated install v3. How to resolve this??

**Comment by nicolo-ribaudo** [comment]
https://babeljs.io/docs/en/babel-polyfill

> 🚨 As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions):
> 
> ```js
> import "core-js/stable";
> import "regenerator-runtime/runtime";
> ```

**Comment by ianchanning** [comment]
It took me a while to find this bug report as I was searching based off the yarn warning message I get. 

Anyone who finds this should look at the above answer: https://github.com/babel/babel/issues/10791#issuecomment-560344796

So I'm just putting this here for any future searches:

```
warning babel-polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning babel-polyfill > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```
