### ISSUE TITLE
 Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by Webboss** [babel/babel#10796]
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: [BABEL] /Users/apple/Downloads/project/router-app/node_modules/webpack/  buildin/global.js: Cannot find module './src/data'
  Require stack:
  - /Users/apple/Downloads/project/router-app/node_modules/core-js-compat/helper  s.js
  - /Users/apple/Downloads/project/router-app/node_modules/core-js-compat/get-mo  dules-list-for-target-version.js
  - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-ap  p/node_modules/@babel/preset-env/lib/polyfills/corejs3/entry-plugin.js
  - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-ap  p/node_modules/@babel/preset-env/lib/index.js
  - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-ap  p/dependencies.js
  - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/confi  g/files/plugins.js
  - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/confi  g/files/index.js
  - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/index  .js
  - /Users/apple/Downloads/project/router-app/node_modules/babel-loader/lib/inde  x.js
  - /Users/apple/Downloads/project/router-app/node_modules/loader-runner/lib/loa  dLoader.js
  - /Users/apple/Downloads/project/router-app/node_modules/loader-runner/lib/Loa  derRunner.js
  - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/NormalMod  ule.js
  - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/NormalMod  uleFactory.js
  - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/Compiler.  js
  - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/webpack.j  s
  - /Users/apple/Downloads/project/router-app/node_modules/react-scripts/scripts  /start.js (While processing: "/Users/apple/Downloads/project/router-app/node_m  odules/babel-preset-react-app/dependencies.js$0$9")
  
  - loader.js:797 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:797:15
  
  - loader.js:690 Function.Module._load
    internal/modules/cjs/loader.js:690:27
  
  - loader.js:852 Module.require
    internal/modules/cjs/loader.js:852:19
  
  - helpers.js:74 require
    internal/modules/cjs/helpers.js:74:18
  
  - helpers.js:3 Object.
    [router-app]/[core-js-compat]/helpers.js:3:14
  
  - loader.js:959 Module._compile
    internal/modules/cjs/loader.js:959:30
  
  - loader.js:995 Object.Module._extensions..js
    internal/modules/cjs/loader.js:995:10
  
  - loader.js:815 Module.load
    internal/modules/cjs/loader.js:815:32
  
  - loader.js:727 Function.Module._load
    internal/modules/cjs/loader.js:727:14
  
  - loader.js:852 Module.require
    internal/modules/cjs/loader.js:852:19
  
  - helpers.js:74 require
    internal/modules/cjs/helpers.js:74:18
  
  - get-modules-list-for-target-version.js:2 Object.
    [router-app]/[core-js-compat]/get-modules-list-for-target-version.js:2:51
  
  - loader.js:959 Module._compile
    internal/modules/cjs/loader.js:959:30
  
  - loader.js:995 Object.Module._extensions..js
    internal/modules/cjs/loader.js:995:10
  
  - loader.js:815 Module.load
    internal/modules/cjs/loader.js:815:32
  
  
  - Error: [BABEL] /Users/apple/Downloads/project/router-app/node_modules/webpac    k/buildin/global.js: Cannot find module './src/data'
  
  - Require stack:
  
  - - /Users/apple/Downloads/project/router-app/node_modules/core-js-compat/help    ers.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/core-js-compat/get-    modules-list-for-target-version.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-    app/node_modules/@babel/preset-env/lib/polyfills/corejs3/entry-plugin.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-    app/node_modules/@babel/preset-env/lib/index.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-    app/dependencies.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/con    fig/files/plugins.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/con    fig/files/index.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/ind    ex.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-loader/lib/in    dex.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/loader-runner/lib/l    oadLoader.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/loader-runner/lib/L    oaderRunner.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/NormalM    odule.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/NormalM    oduleFactory.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/Compile    r.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/webpack    .js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/react-scripts/scrip    ts/start.js (While processing: "/Users/apple/Downloads/project/router-app/no    de_modules/babel-preset-react-app/dependencies.js$0$9")
  
  - Module build failed (from ./node_modules/babel-loader/lib/index.js):
  
  - Error: [BABEL] /Users/apple/Downloads/project/router-app/node_modules/webpac    k/buildin/module.js: Cannot find module './src/data'
  
  - Require stack:
  
  - - /Users/apple/Downloads/project/router-app/node_modules/core-js-compat/help    ers.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/core-js-compat/get-    modules-list-for-target-version.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-    app/node_modules/@babel/preset-env/lib/polyfills/corejs3/entry-plugin.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-    app/node_modules/@babel/preset-env/lib/index.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-preset-react-    app/dependencies.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/con    fig/files/plugins.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/con    fig/files/index.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/@babel/core/lib/ind    ex.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/babel-loader/lib/in    dex.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/loader-runner/lib/l    oadLoader.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/loader-runner/lib/L    oaderRunner.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/NormalM    odule.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/NormalM    oduleFactory.js
  
  - - /Users/apple/Downloads/project/router-app/node_modules/webpack/lib/Compile    r.js

  I have an issue when run the react project

**Comment by zloirock** [comment]
See https://github.com/npm/cli/issues/545
