### ISSUE TITLE
Feature request: option to leave native generators instead of applying regenerator

### ISSUE THREAD

**Issue by amsul** [babel/babel#108]
This is primarily to allow using 6to5 on Node Harmony without the need to "regenerate" generators since it's natively supported.

Actually thinking about it now, maybe there should be an option to selectively disable any of the features if they've already been implemented in the target environment..

**Comment by togakangaroo** [comment]
Is this stil the case @sebmck I'm using babel via jspm and when I do `blacklist: ["generators"]` in `System.config` I get a **unknown transformer** error

**Comment by loganfsmyth** [comment]
@togakangaroo It's `blacklist: ['regenerator']` now.

**Comment by sebmck** [comment]
@togakangaroo This is an extremely old issue. The transformer is now called `regenerator`.

**Comment by togakangaroo** [comment]
Thanks! It popped up in google results so its probably still a good idea to have the note on this thread.
