### ISSUE TITLE
Enable optional chaining by default in @babel/preset-env

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10809]
## Feature Request

<div align="center">

### Optional chaining is Stage 4!
![](https://media.giphy.com/media/56pSvQ2JFeGT6/giphy.gif)
</div>

This means that it should be enabled by default in `@babel/preset-env` :tada:

It should be done similarly to this commit: https://github.com/babel/babel/commit/b92ad318f173e1a0573a188324aa0c222ea35782

1. Add it to `packages/babel-preset-env/src/available-plugins.js`
2. Add the `compat-table` mapping to `packages/babel-preset-env/data/plugin-features.js` (you can find the correct feature name at https://kangax.github.io/compat-table/esnext/)
3. Run `cd packages/preset-env` and `yarn build-data` to update the data about the supported browser versions
4. Add it to `@babel/preset-env-standalone` (`packages/babel-preset-env-standalone/src/available-plugins.js`)
5. Update the test as needed (you don't need to write new tests)
6. PR! :tada:

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test if needed (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-preset-env` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-preset-env` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by rajasekarm** [comment]
I can give a PR now.

**Comment by nicolo-ribaudo** [comment]
I was going to mark this as a `good first issue` for new contributors :sweat_smile:

**Comment by rajasekarm** [comment]
sure, we can do that as well.

**Comment by Druotic** [comment]
I'll take a stab at this 👍 - it sounds straight forward enough.

**Comment by PerpetualWar** [comment]
is this gonna happen soon ?

**Comment by nicolo-ribaudo** [comment]
It has been released in v7.8.0
