### ISSUE TITLE
Name collision with `export *` does not throw error

### ISSUE THREAD

**Issue by gustavoschmidt** [babel/babel#10803]
## Bug Report

**Current Behavior**
When two functions with the same name are re-exported from the same file with `export *` no error is thrown.

**Input Code**
File1.js
```js
export function asdf { return 'asdf'; }
```

File2.js
```js
export function asdf { return 'asdf'; }
```

File3.js
```js
export * from './File1.js';
export * from './File2.js';
```

File4.js
```js
import {asdf} from './File3.js';
asdf();
```

**Expected behavior/code**
I expect the same error I get when I import two functions to the same file: `Identifier 'asdf' has already been declared`

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`
```js
{
  presets: [
    '@babel/preset-flow',
    '@babel/preset-react',
    ['@babel/preset-env', {targets: {node: 'current'}}],
  ],
  plugins: [
    ['@babel/plugin-proposal-pipeline-operator', {proposal: 'fsharp'}],
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-class-properties',
  ],
}
```

**Environment**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.4.0 => 7.6.4 
    @babel/core: ^7.4.0 => 7.6.4 
    @babel/node: ^7.4.0 => 7.6.3 
    @babel/plugin-proposal-class-properties: ^7.5.5 => 7.5.5 
    @babel/plugin-proposal-optional-chaining: ^7.6.0 => 7.6.0 
    @babel/plugin-proposal-pipeline-operator: ^7.5.0 => 7.5.0 
    @babel/preset-env: ^7.4.0 => 7.6.3 
    @babel/preset-flow: ^7.0.0 => 7.0.0 
    @babel/preset-react: ^7.4.0 => 7.6.3 
    babel-eslint: ^10.0.1 => 10.0.1 
    babel-loader: ^8.0.0 => 8.0.5 
    eslint: 4.19.1 => 4.19.1 
    eslint-plugin-babel: 4.1.2 => 4.1.2 
    webpack: 4.39.1 => 4.39.1 
```

**Comment by JLHwung** [comment]
Babel processes input code per file level, which means it does not check if exports have been well defined in another file. Babel is a transpiler, it compiles every single JavaScript file to valid ES5. Therefore, in this case, it is the runtime/bundler that should take responsiblity to check module exports clash.

**Comment by nicolo-ribaudo** [comment]
When transpiling to commonjs, we could throw at runtime.

**Comment by gustavoschmidt** [comment]
@JLHwung Thank you for the quick response. Since the only exported function of `File1.js` is `asdf`, I would expect the three expressions below to be equivalent:
```js
import {asdf} from './File1.js';
export {asdf};
```
```js
export {asdf} from './File1.js';
```
```js
export * from './File1.js';
```
But only the first two throw an error, which shows the third one is not equivalent in every case. If this is correct and the third should not be equivalent to the first two, feel free to close the issue.

Also thanks for the proposed solution, I'll check for name clashes in runtime.
