### ISSUE TITLE
Optional delete must return true when base is nullish

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#10805]
## Bug Report

**Current Behavior**

When using optional delete to delete a property of a nullish base, the delete operation returns `undefined`. It should return `true`

**Input Code**
[repl](https://babeljs.io/repl/#?browsers=Chrome%2078&build=&builtIns=usage&spec=false&loose=false&code_lz=DYUwLgBAZg9jDcAoAxjAdgZ0gJ3BAvBACYihgjRwD8AdAEYCG2SK6GMoNDGGI2YAClyR8oiGGwBXEAEp4QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0)

```js
let foo;
const ret = delete foo?.bar;

console.assert(ret === true);
```

**Expected behavior/code**
The `ret` value should be `true`, not `undefined`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": ["@babel/plugin-proposal-optional-chaining"]
}
```

**Possible Solution**
When replacing optional deletes, we must use `t.booleanLiteral(true)` in the consequent (truthy branch of a ternary expression) instead of `scope.buildUndefinedNode()`.

Specifically, we must fix https://github.com/babel/babel/blob/d18afbd7c3e977208194acbea4c0de0313a6e1eb/packages/babel-plugin-proposal-optional-chaining/src/index.js#L116

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mpaarating** [comment]
I can look at this!

**Comment by nicolo-ribaudo** [comment]
Sure, it's yours!
