### ISSUE TITLE
Optional Chaining does not propagate receiver when parenthesized

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#10802]
## Bug Report

**Current Behavior**

Optional Calls allows you to parenthesize the expression to break the optional-ness of the chain. For instance, `(foo?.bar).baz` requires that an object be returned to access `.baz`. This also applies to call expressions: `(foo?.bar)()`.

The problem is, that `(foo?.bar)()` must propagate `foo` as the `this` receiver to the call expression. We currently do not do this.

**Input Code**

[repl](https://babeljs.io/repl/#?browsers=Chrome%2078&build=&builtIns=usage&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MDeMBGBDATgCgEp0ZcBTKAV1zBigAsBLCGAXzYG4AoL0SEADZkAdNggQyuKPgRJk8mDMQB-YTlyEihDkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0)

```js
const foo = { bar() { return this } };

console.assert(foo === (foo?.bar)());
```

**Expected behavior/code**
The `foo` object should be used as the receiver during the `foo.bar` method call.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": [ "@babel/plugin-proposal-optional-chaining" ]
}
```

**Possible Solution**
We need to detect parenthesized call expressions, and use `.call` to properly propagate the receiver.

**Additional context/Screenshots**

This is likely more difficult good-first-issue. I'm still prototyping a fix to see whether we should recommend it to a first time contributor.

**Comment by jridgewell** [comment]
Excellent, the fix is actually really easy! We can handle this the same way we handle `delete foo?.bar`.

When the parent is a regular call expression (and the callee is the optional chain), we can use the parent as the root of the transform. Specifically, we need to add another check like https://github.com/babel/babel/blob/d18afbd7c3e977208194acbea4c0de0313a6e1eb/packages/babel-plugin-proposal-optional-chaining/src/index.js#L39-L41

Then, we just need tests.

This is appropriate for a good first issue!

**Comment by iansu** [comment]
I’m interested in working on this issue if no one else is.

**Comment by nicolo-ribaudo** [comment]
Sure!

**Comment by jakewilson** [comment]
Hey @iansu, are you still working on this? If you're too busy, I'd love to take a crack at it.

**Comment by iansu** [comment]
@jakewilson I am still working on this. I just haven't had much time over the holidays. I'll pick it up again this week.

**Comment by sidntrivedi012** [comment]
Hey @iansu , are you still working on this ? Would like to work on it.

**Comment by iansu** [comment]
@sidntrivedi012 I am still working on this. I've written some failing tests to cover this case. I'm just working on actually fixing it. I don't have a ton of experience working with Babel's AST so it's taking me a little longer than I hoped but I am still trying to work through it.

**Comment by existentialism** [comment]
@iansu please let us know if you have any questions!

**Comment by taejs** [comment]
Hi, just wanted to check if someone is working on this issue. If not, it'll be my pleasure to work on it!
@iansu

**Comment by iansu** [comment]
I am working on this but I'm stuck on how to fix it. I've tried a few things without success. Any pointers on how I can detect this call expression would be appreciated.

**Comment by taejs** [comment]
If so it would be better to ask reporter or maintainer..!
I didn't investigate into details because I'm not a assignee.

@jridgewell @existentialism 
I think he needs some helps.

**Comment by JLHwung** [comment]
@iansu I come up with a possible solution inspired by @jridgewell 's tips. Let's see if we can sort it out.

** brief summary of optional-chaining plugin **
The optional-chaining transform plugin can be roughly divided into two parts:
i) The first part is to collect an array of to-be-processed AST nodes (`optionals`) and determine the AST node that we want to transform (`replacementPath`).
ii) The second part is to apply transforms to the `optionals` and replace `replacementPath` by the de-sugared member expressions or call expressions.

** Justin's approach **
@jridgewell 's approach is to reuse the logic that we choose `parentPath` to be the `replacementPath`, that said,
```js
foo?.bar;
// →
foo == null ? void 0 : foo.bar;
// replacementPath is `foo?.bar`, an optional member expression.

delete foo?.bar;
// →
foo == null ? true : delete foo.bar;
// replacementPath is `delete foo?.bar`, the **parentPath** of 
// the optional member expression`foo?.bar`
```

so we can imagine that
```js
(foo?.bar)();
// → foo == null ? void 0 : foo.bar();
// and the replacementPath is also the **parentPath** of
// the optional member expression`foo?.bar`
```
In this case `foo` is correctly propagated to be the `this` value of `foo.bar()` member expression. However the semantic of `(foo?.bar)()` is changed: if `foo` or `foo?.bar` is nullish, `(foo?.bar)()` must throw `undefined is not a function`. However here we have replaced the un-optional call expression `(foo?.bar)()` by optional chains which returns `undefined` when `foo` or `foo?.bar` is nullish.

** My approach **
Here I propose we use `.bind` to pass the this value and _preserve_ the non-optional call expression. In the example above
```js
(foo?.bar)();
// → (foo == null ? void 0 : foo.bar.bind(foo))();
```

So we still 1) preserve the call expression out of the optional member `foo?.bar` 2) pass this value `foo` to the replacement node `foo.bar` via `function#bind`.

As I said before the plugin can be divided into two parts. In this approach we only need focus on the how `replacement` is generated.

https://github.com/babel/babel/blob/3960f4de647e3c81b3c0d3020de8ef156c188944/packages/babel-plugin-proposal-optional-chaining/src/index.js#L121

we pass `replacement.node` (which is `foo.bar` in the above example) to be the non-nullish conditional alternate. We can check if the `replacementPath` is parenthesized and its parent path is a call expression

```js
let replacement = replacementPath.node;
if (
  replacementPath.isMemberExpression() &&
  replacementPath.node.extra?.parenthesized &&
  replacementPath.parentPath.isCallExpression()
) {
  // we have detected the pattern `(optional?.member)(any, arguments)`
}
```
And it is detected we can append `.bind(foo)` to `foo.bar`:
```js
replacement = t.callExpression(
  t.memberExpression(replacement, t.identifier("bind")),
  [t.cloneNode(replacementPath.get("object").node)],
);
```
where `.get("object")` extracts `foo` from `foo.bar` and `foo.bar.bind` is constructed from `t.memberExpression`.

@jridgewell Please let me know if I miss some semantic differences between `function#bind` and `function#call`, thank you!

**Comment by jridgewell** [comment]
> However the semantic of (foo?.bar)() is changed: if foo or foo?.bar is nullish, (foo?.bar)() must throw undefined is not a function. 

I think it's easiest if we transform to:

```js
foo == null ? (void 0)() : foo.bar()
```

Doing a `bind` is super expensive, and using `.call` is moderately expensive.

**Comment by iansu** [comment]
Thanks everyone! What about the `(void 0)()` part of the replacement? @JLHwung I don't think your replacement code produces that part, correct? I'm guessing that's something I can find elsewhere in the code. I'll work on this today and see how it goes.

**Comment by JLHwung** [comment]
@iansu 

```js
(foo?.bar)();
// →
(foo == null ? void 0 : foo.bar.bind(foo))();
```
is equivalent to
```js
foo == null ? (void 0)() : foo.bar()
```
if you apply the call expression on the conditional branches.

You can construct `(void 0)()` from `void 0` (`scope.buildUndefinedNode()`) via `t.callExpression`.

**Comment by jridgewell** [comment]
Hi @iansu, how's the progress on this?

**Comment by jridgewell** [comment]
Friendly ping @iansu

**Comment by iansu** [comment]
Hi. I will try to get a PR up for this today. Apologies for the delays.

**Comment by iansu** [comment]
I put up a PR for this but I don't think it's quite right. I think I might have got the `bind` solution working but I'm less sure I was able to covert it to @jridgewell's proposed solution.
