### ISSUE TITLE
`Object` variable declaration conflicts on commonjs

### ISSUE THREAD

**Issue by falsandtru** [babel/babel#10807]
## Bug Report

Avoiding reference to global variables such as `const { Object } = globalThis;` is an effective performance tuning technique: https://falsandtru.github.io/benchmark/suites/10/

But the current behavior prevents this tuning.

**Current Behavior**
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {};
const Object = {};
```
```
VM69:2 Uncaught ReferenceError: Cannot access 'Object' before initialization
    at eval (eval at <anonymous> (main-3.js:1239), <anonymous>:2:1)
    at main-3.js:1239
```

**Input Code**
https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28DeBfAKAGMIA7AZ3gHkAjAK2CPgF458BuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.7.4&externalPlugins=

```js
export default {}
const Object = {};
```

**Expected behavior/code**
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
{
exports.default = {};
const Object = {};
}
```

**Comment by nicolo-ribaudo** [comment]
Most of the transformations performed by Babel assume that the native environment isn't modified.
One of these assumptions is that all the built-in functions are not shadowed by any local variable.

**Comment by falsandtru** [comment]
Most other (especially native) module types don't have this limitation. Therefore this is incompatibility of module types with a very common namespace.

**Comment by liuxingbaoyu** [comment]
Because this isue is out of date, I will close it.
