### ISSUE TITLE
String.matchAll does not get polyfilled

### ISSUE THREAD

**Issue by pakaponk** [babel/babel#10816]
## Bug Report

**Current Behavior**
String.matchAll does not get polyfilled.

**Input Code**

```js
import 'core-js/stable'

const string = `world world world world world world`

console.log([...string.matchAll(/world/g)]);
```

**Expected behavior/code**
The transpiled code should contain this line `require("core-js/modules/es.string.match-all")`

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const presets = [
  [
    "@babel/env",
    {
      useBuiltIns: "entry",
      corejs: 3,
    },
  ]
]

module.exports = { presets };
```

- Browserslist: `last 1 safari version, last 1 chrome version, last 1 firefox version` 

**Environment**

```
System:
    OS: macOS 10.15
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v10.16.3/bin/npm
  npmPackages:
    @babel/cli: ^7.7.4 => 7.7.4 
    @babel/core: ^7.7.4 => 7.7.4 
    @babel/preset-env: ^7.7.4 => 7.7.4 
```
- Babel version(s): 7.7.4
- Node/npm version: 10.16.3
- OS: OS X 10.15
- Monorepo: no
- How you are using Babel: cli

**Additional context/Screenshots**
I have also tried to import `core-js/modules/es.string.match-all` or `core-js/es/string/match-all` after `core/stable`. None of them works.
The only way I can get `String.matchAll` polyfilled properly is to specifically import `core-js/modules/esnext.string.match-all`. 

```js
import 'core-js/stable'
import 'core-js/modules/esnext.string.match-all'

const string = `world world world world world world`

console.log([...string.matchAll(/world/g)]);
```

**Comment by zloirock** [comment]
You should use `corejs: '3.4`.

**Comment by pakaponk** [comment]
@zloirock Thanks! It works. At first, I thought when we use `corejs: 3`, it will always pick the latest version for us.

**Comment by zloirock** [comment]
> I thought when we use `corejs: 3`, it will always pick the latest version for us

It will break the case "modern compat data + old `core-js`".

**Comment by davideapvd** [comment]
Hello,
when using useBuiltIns: "usage", should the matchAll polyfill should be included? I have a test repo here https://github.com/davideapvd/testusagebabel and it doesn't get included.

**Comment by zloirock** [comment]
@davidaurelio since it's `usage`, it's another issue. `shippedProposals` does not make sense here. It's a Babel issue since built-ins definitions should be updated to the actual `core-js` version.

**Comment by davidaurelio** [comment]
@zloirock did you mean to mention me here?

**Comment by zloirock** [comment]
@davidaurelio sorry, seems it's an issue with GitHub autocomplete.
