### ISSUE TITLE
@babel/preset-typescript + @babel/plugin-syntax-jsx doesn't support explicit JSX element type parameters like tsc

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#10812]
I discovered today that `tsc` supports the following nice funky syntax:
```js
export const SomeQuery = () => (
  <Query<SomeData, SomeVariables> query={SOME_QUERY} ...>
    {({ data }) => {
      return <div> ... things happen... </div>;
    }}
  </Query>
);
```
According to my testing on AST explorer at least, babel 7 + `@babel/preset-typescript` + `@babel/plugin-syntax-jsx` flags this as a syntax error.

**Comment by thorn0** [comment]
It works: https://astexplorer.net/#/gist/62e0a6da42ea4e7b9004451ffbcd1191/cb51300cfffbf354b9a372c454c1d29c2836bae4

**Comment by JLHwung** [comment]
I could not reproduce this error on REPL: https://babeljs.io/repl#?browsers=last%201%20version%2C%20not%20ie%2011%2C%20not%20ie_mob%2011%2C%20not%20op_mini%20all&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wMoQLbAIoCuwUAnnALxwAUAlBQHzUBQccAPIcSW1rgCIBDGAIA0cXsABqAqAEsBAIwA2wVIwCORUuQDeGAPIBZAKIB9PAFVjAJQCaAX3otWcHVR1wAJkIFx7dckYdZxc4KGAYAihkdk9ZADdGADoUuBgAC1lkAHNUOHSBMDBgZBSk9gB6OMSAbhC_e2c2Cs5SJxoaoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.7.4&externalPlugins=

**Comment by jedwards1211** [comment]
Okay sorry, it must have been a bug in ASTExplorer then.  Maybe it failed to reparse after I tweaked the babel options
