### ISSUE TITLE
Enable nullish coalescing by default in @babel/parser

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#10813]
## Feature Request

<div align="center">

### Nullish coalescing is Stage 4!
![](https://media.giphy.com/media/xT5LMQ8rHYTDGFG07e/giphy.gif)
</div>

This means that it should be enabled by default in `@babel/parser` :tada:

It should be done similarly to this commit: https://github.com/babel/babel/commit/24c4901ff56c57db1ac60e4d810424656d18e374

1. Remove all the `this.hasPlugin` and `this.expectPlugin` checks related to this plugin in `packages/babel-parser/src`
2. Remove all the usages of `nullishCoalescingOperator` in `@babel/parser`'s tests
  1. Probably there is a test to ensure that the plugin is required; it can be removed.
3. Move the tests from the `experimental` folder to `es2020`
6. PR! :tada:

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test if needed (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by layershifter** [comment]
Can I take this one? 😇

**Comment by kaicataldo** [comment]
@layershifter Have at it!
