### ISSUE TITLE
'--ignore' conflicts with  '--copy-files'

### ISSUE THREAD

**Issue by sspantz** [babel/babel#10829]
## Bug Report

**Current Behavior**
cli option '--copy-files' copies all non-compiled files, including ignored files

**Input Code**
- Not behave as what i expect
```json
// package.json
{
  "scripts": {
     "build": "babel src --out-dir dist --copy-files --ignore src/**/*.test.js  --presets=@babel/env"
  }
}
```
run in terminal
```bash
$ npm run build
```

**Expected behavior/code**
'--copy-files' copies all non-compiled files, and skip ignored files

**Environment**

- Babel version(s): [v7.7.4]
- Node/npm version: [ Node v12.13]
- OS: [OSX 10.15.1,]
-  How you are using Babel: [`cli`]

**Comment by rajasekarm** [comment]
Hi @sspantz, ignored files should not be copied to the out-dir.

https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/dir.js#L88

Right now the condition is, 

1. if not written and copyFiles is enabled, move the file to out dir.
2. If the file is in ignore list, the written will be false, so ignored files is getting added.

But we've to add a condition , if not written and the file extension is supported and copyFiles is enabled.

**Comment by sspantz** [comment]
> Hi @sspantz, ignored files should not be copied to the out-dir.
> 
> https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/dir.js#L88
> 
> Right now the condition is,
> 
> 1. if not written and copyFiles is enabled, move the file to out dir.
> 2. If the file is in ignore list, the written will be false, so ignored files is getting added.
> 
> But we've to add a condition , if not written and the file extension is supported and copyFiles is enabled.

hi @rajasekarm , thanks for your response and quick fix. but what if i try to copy the ignored files after  this issue fixed.

**Comment by rajasekarm** [comment]
>but what if i try to copy the ignored files after this issue fixed?

Ignored folder/file will be always skipped when moving to the out dir.

**Comment by JLHwung** [comment]
Closing this as it duplicates #6226 

@sspantz It's a nice report.
