### ISSUE TITLE
Ability to skip modules transform

### ISSUE THREAD

**Issue by meandmycode** [babel/babel#1082]
Currently there doesn't appear to be a way to skip the modules transform, I'm working around this by supplying a custom transform like this, but it seems inefficient and the indexOf seems a bit hacky:

```js
var NoneFormatter = function NoneFormatter() {
};

NoneFormatter.prototype.importDeclaration = function (node, nodes) {
    nodes.push(node);
};

NoneFormatter.prototype.importSpecifier = function (specifier, node, nodes) {
    if (nodes.indexOf(node) === -1) nodes.push(node);
};

NoneFormatter.prototype.exportDeclaration = function (node, nodes) {
    nodes.push(node);
};

NoneFormatter.prototype.exportSpecifier = function (specifier, node, nodes) {
    if (nodes.indexOf(node) === -1) nodes.push(node);
};
```

The reason I'm trying to leave the module syntax alone is that I'm using another library to handle bundling, and the library is based on bundling the es6 module syntax.

I think in the future being able to keep the import / export syntax may be useful outside of this as module support becomes native to some platforms.

It would be useful to skip the modules transform, either with a flag or possibly a special case on the ```modules``` option.

Thanks,

**Comment by sebmck** [comment]
You can already blacklist any of the transformers.

```javascript
require("babel").transform("code", { blacklist: ["es6.modules"] });
```

```sh
$ babel --blacklist es6.modules script.js
```
