### ISSUE TITLE
Duplicate object property and getter/setter should throw an error

### ISSUE THREAD

**Issue by hgl** [babel/babel#1083]
This currently throws an error
```js
let a = {
  a: 1,
  a: 2
};
```
But this doesn't 
```js
let a = {
  a: 1,
  get a() {}
};
```

**Comment by sebmck** [comment]
Please report this upstream at [acorn](https://github.com/marijnh/acorn).

**Comment by hgl** [comment]
Done. https://github.com/marijnh/acorn/issues/226
