### ISSUE TITLE
IE11 Promise polyfill not loaded from @babel/present-env v7.7.0

### ISSUE THREAD

**Issue by AlmeroSteyn** [babel/babel#10830]
## Bug Report

I have an issue with `@babel/preset-env` not injecting the Promise polyfill after upgrading from `v7.6.3` to `v7.7.x`.

**Current Behavior**
In a Preact application, when upgrading `@babel/preset-env` from `v7.6.3` to `v7.7.x`, IE11 crashes with console error  `"Promise" is undefined`. In the same repo, by simply reverting back to `v7.6.3`, the issue goes away and the code works flawlessly again.

I have tried a large number of things, including confirming that the `browserslist` is resolved correctly but am unable to fix this issue.

**Input Code**
I am currently unable to reproduce this in a smaller repo that I can share without breaking non-disclosure of company code as I don't know what has changed and therefore where to even start looking for it yet.

I am hoping that this is a known issue or that my configuration is enough to suggest a fix.

**Expected behavior/code**
The polyfills should work in IE11.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Configuration is done in `webpack.config` as rules.

Initially the rule was loaded as:

```js
            plugins: [
              '@babel/plugin-syntax-dynamic-import',
              '@babel/plugin-proposal-object-rest-spread',
              [
                '@babel/plugin-transform-runtime',
                {
                  absoluteRuntime: false,
                  helpers: true,
                  corejs: 3,
                  regenerator: true,
                  useESModules: true,
                },
              ],
              [
                '@babel/plugin-transform-react-jsx',
                {
                  pragma: 'h',
                  pragmaFrag: 'Fragment',
                },
              ],
            ],
          },
        },
```

`BROWSERS` is defined as `const BROWSERS = 'last 1 version, > 1%, not dead'`

After consulting the documentation I change the deprecated `query` to `use`:

```js
        {
          test: /\.js$/,
          exclude: /(node_modules|bower_components)/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                [
                  '@babel/preset-env',
                  {
                    useBuiltIns: "entry",
                    corejs: '3'
                  }
                ],
              ],
              plugins: [
                '@babel/plugin-syntax-dynamic-import',
                '@babel/plugin-proposal-object-rest-spread',
                [
                  '@babel/plugin-transform-runtime',
                  {
                    absoluteRuntime: false,
                    helpers: true,
                    corejs: 3,
                    regenerator: true,
                    useESModules: true,
                  },
                ],
                [
                  '@babel/plugin-transform-react-jsx',
                  {
                    pragma: 'h',
                    pragmaFrag: 'Fragment',
                  },
                ],
              ],
            },
          },
        },
```

In `package.json` I have the following setting now:

```
  "browserslist": "last 1 version, > 1%, not dead"
```

**Environment**

```
- Babel version(s): 7.4.4
- Node/npm version: Node 10.16.0/npm 6.11.3/yarn used at 1.19.1
- OS: Windows 10
- Monorepo: no
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
> I am currently unable to reproduce this in a smaller repo that I can share without breaking non-disclosure of company code as I don't know what has changed and therefore where to even start looking for it yet.

Could you at least share the path of the source file which contains the promise which isn't being transpiled?

**Comment by AlmeroSteyn** [comment]
@nicolo-ribaudo Oh yeah of course!

Fails on `/node_modules/preact/dist/preact.module.js`  and `/node_modules/regenerator-runtime/runtime.js`. 

Both files that I cannot imagine should need transpilation?

**Comment by anthony-redFox** [comment]
I guess  - it is the same as https://github.com/babel/babel/issues/10678#issuecomment-551408687

**Comment by nicolo-ribaudo** [comment]
This should be fixe by https://github.com/facebook/regenerator/pull/383, because now we use the polyfilled promise with regenerator.
