### ISSUE TITLE
Documentation on https://babeljs.io/ is incorrect

### ISSUE THREAD

**Issue by kp2017** [babel/babel#10842]
The documentation states: "Babel is a JavaScript compiler." It should say, "Babel is a JavaScript transpiler." 

https://www.merriam-webster.com/dictionary/compiler defines a compiler as:
a computer program that translates an entire set of instructions written in a higher-level symbolic language (such as C) into machine language before the instructions can be executed

https://www.yourdictionary.com/transpiler defines a transpiler as:
Software that converts the source code of one language into the source code of another.

**Comment by nicolo-ribaudo** [comment]
From wikipedia:

> A compiler is a computer program that translates computer code written in one programming language (the source language) into another language (the target language).
> [...]
> However, there are many different types of compilers. [...] A program that translates between high-level languages is usually called a source-to-source compiler or transpiler. A language rewriter is usually a program that translates the form of expressions without a change of language.

https://en.wikipedia.org/wiki/Compiler

Thus, a transpiler is a compiler.

**Comment by kp2017** [comment]
Yes all transpilers are compilers but not all compilers are transpilers. Unless Babel is going to take on the role of all the other types of compilations, it would be better termed a transpiler. 

Your source also notes this: A program that translates between high-level languages is usually called a source-to-source compiler or transpiler.

**Comment by nicolo-ribaudo** [comment]
> Yes all transpilers are compilers but not all compilers are transpilers.

A man is a human, but not all the humans are men. If I had a website that says "I am a human" I wouldn't expect anyone to complain "You are not a human, you are a man!".
It's the same thing: even if not every compiler is a transpiler, every transpiler is a compiler and thus Babel _is_ a compiler.

That said, this discussion has already taken place a million times on every possible dev-related social network. You are free to call Babel a transpiler if you want.
