### ISSUE TITLE
typeAnnotation don't output to ts file correctly

### ISSUE THREAD

**Issue by onrun** [babel/babel#10844]
## Bug Report
![image](https://user-images.githubusercontent.com/18000037/70432120-786e7c00-1ab9-11ea-904d-4ab450b8ea13.png)

![image](https://user-images.githubusercontent.com/18000037/70432284-ddc26d00-1ab9-11ea-9610-6c0b4c90da44.png)

**Comment by nicolo-ribaudo** [comment]
Where did you get that AST from? It isn't well-formed.

1) Those nodes are for Flow, not for TS.
2) The node used to annotate the parameter should be a `TypeAnnotation` (if using flow), which contains your `ObjectTypeAnnotation`

If you are building that AST yourself, I suggest two good resources to do it correctly:
1) [ASTExplorer](https://lihautan.com/babel-ast-explorer/#?eyJiYWJlbFNldHRpbmdzIjp7InZlcnNpb24iOiI3LjYuMCIsInR5cGVzY3JpcHQiOnsib3B0aW9ucyI6e30sImVuYWJsZWQiOnRydWV9fSwidHJlZVNldHRpbmdzIjp7ImhpZGVFbXB0eSI6dHJ1ZSwiaGlkZUxvY2F0aW9uIjp0cnVlLCJoaWRlVHlwZSI6dHJ1ZSwiaGlkZUNvbW1lbnRzIjp0cnVlfSwiY29kZSI6IiJ9) allows you to visualize the AST of the code you have in mind
2) https://github.com/babel/babel/blob/master/packages/babel-parser/src/types.js contains the type definition of Babel's AST.

**Comment by onrun** [comment]
Sorry, it's my mistake !
