### ISSUE TITLE
develop a Chinese JS compiler

### ISSUE THREAD

**Issue by 403605209** [babel/babel#10840]
I am developing a Chinese js compiler.
hava any good idea?

for example:
``` 符 str = ‘abc’``` --->  ``` var str = ‘abc’```
``` 如(正){}```          --->  ```if(true){ }```
``` 函(参){}```          --->  ```function(parameter){ }```

**Comment by nicolo-ribaudo** [comment]
If you fork our parser and modify its tokenizer so that it looks for Chinese words rather than English words,you can the use it in an unmodified `@babel/core` which will already translate it to English.

**Comment by 403605209** [comment]
> If you fork our parser and modify its tokenizer so that it looks for Chinese words rather than English words,you can the use it in an unmodified `@babel/core` which will already translate it to English.

I downloaded the parser code and modified its tokenizer, how can I compile the code into a production version.

**Comment by nicolo-ribaudo** [comment]
You can run `make build` (after running `make bootstrap`), and then you can use either publish `packages/babel-parser` under a new name, or use it locally with `npm link`

**Comment by 403605209** [comment]
thx so much
