### ISSUE TITLE
Duplicate function declarations should throw an error

### ISSUE THREAD

**Issue by hgl** [babel/babel#1084]
This currently throws an error:
```js
let b = () => {
  let a = 1;
  let a = 2;
};
```

But this doesn't

```js
let b = (a) => {
  let a = 1;
};
```

**Comment by sebmck** [comment]
Fixed in the `experimental` branch due for the next major, thanks!

**Comment by sebmck** [comment]
Actually not sure if this is spec behaviour. Do you have a spec citation?

**Comment by hgl** [comment]
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-static-semantics-early-errors

This is for arrow functions, but others should be the same.
