### ISSUE TITLE
ESTree parser plugin incompatibility with ObjectProperty

### ISSUE THREAD

**Issue by edoardocavazza** [babel/babel#10852]
## Bug Report

**Current Behavior**

When transpiling JSX with the `estree` parser plugin we have an exception:
```
TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got "Literal"
```

**Input Code**

See https://gitlab.com/edoardo.cavazza/babel-estree-compatibility

**Expected behavior/code**

Babel is able to transpile JSX and to generate an ESTree compatibile AST.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
    "parserOptions": {
        "plugins": ["estree"]
    }
    "plugins": [
        "@babel/plugin-transform-react-jsx"
    ]
}
```

**Environment**

```
  System:
    OS: macOS 10.15.1
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.7.5 => 7.7.5 
    @babel/plugin-transform-react-jsx: ^7.7.4 => 7.7.4 
```

**Possible Solution**

Add `Literal` as real type in the `babel-types` package instead of considering it an alias?

**Comment by nicolo-ribaudo** [comment]
Babel expects an input AST that is in the Babel format, not in the ESTree one.

If you need to generate an ESTree AST, I suggest first running Babel and the converting it's output (either by re-parsing the output code, or by using something like https://github.com/lightscript/babel-to-estree)

**Comment by edoardocavazza** [comment]
Wasn't the `estree` plugin intended to convert the Babel AST to the ESTree one? I may have misinterpreted the doc 😅 https://babeljs.io/docs/en/babel-parser#output

**Comment by nicolo-ribaudo** [comment]
It is meant to generate an ESTree ast from the parser. The problem is that the transformers use the Babel AST format, so the `estree` parser plugin shouldn't be used if you want to then transform the AST using Babel's architecture.

**Comment by edoardocavazza** [comment]
Ok, it's all clear now, thanks @nicolo-ribaudo for the explanation!
