### ISSUE TITLE
@babel/preset-env doesn't work with default in browserslistrc

### ISSUE THREAD

**Issue by taralx** [babel/babel#10867]
## Bug Report

**Current Behavior**
If relying on external browserslist config, "defaults" in that file resolves to empty set, which enables all transforms.

**Expected behavior/code**
"defaults" should resolve normally. In the example below, many transforms should be disabled.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  presets: [
    ['@vue/cli-plugin-babel/preset', {debug: true}],
  ]
}
```
- Filename: `.browserslistrc`
```
defaults and last 4 years
```

**Environment**
```
  System:
    OS: Linux 5.3 Debian GNU/Linux bullseye/sid
  Binaries:
    Node: 10.17.0 - /usr/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
  npmPackages:
    babel-eslint: ^10.0.1 => 10.0.3
    eslint: ^6.7.0 => 6.7.0
```

**Additional context/Screenshots**
This is broken because of legacy support:

https://github.com/babel/babel/blob/bffa415b83e7cef21cb43b05cc05fc93cf0ac782/packages/babel-preset-env/src/targets-parser.js#L205-L214

This causes defaults to be empty (since `!hasTargets`) and thus the result is empty. 😢

**Comment by JLHwung** [comment]
Closing this as it duplicates #9962. We plan to fix it in babel v8.

@taralx It is a nice report, thank you!
