### ISSUE TITLE
support opt-in import-anywhere syntax

### ISSUE THREAD

**Issue by skeggse** [babel/babel#10864]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Generally, putting imports anywhere besides the top-level is covered by the dynamic imports case. In `jest`, the file-mocking mechanism enforces the loading of external modules within the confines of the module initializer provided to that mocking mechanism. That is, if I want `db.js` to export a fake database during tests (and needed to import some metadata), I'd write:

```js
jest.mock('.../db.js', () => {
  const indices = require('./indices');
  // Populates the equivalent of the commonjs exports object.
  return {
    listIndices: () => indices,
    query() {
      // ...
    },
  };
});
```

In some cases, it's desirable to use exclusively `import` statements in an application - e.g. for linting to ensure we don't unintentionally clobber exports or use features that won't transpile well into other environments. If jest supported async mock initialization functions, this wouldn't be an issue - just use a dynamic `import('./indices')`. Because `jest` doesn't support this functionality, it'd be nice to be able to just drop an `import indices from './indices';` inside the initialization function and have it transpile to `const indices = require('./indicies');`:

```js
jest.mock('.../db.js', () => {
  import indices from './indices';
  // Populates the equivalent of the commonjs exports object.
  return {
    listIndices: () => indices,
    query() {
      // ...
    },
  };
});
```

**Describe the solution you'd like**

I'd like to revisit support for static `import` statements in locations besides the top-level scope. This support would be opt-in, and somewhat separate from the existing `@babel/plugin-transform-modules-commonjs` as that plugin is highly specialized for declarative/hoisted imports at the top-level. In some ways, it'd probably be best to have this be a separate plugin while sharing some code via `babel-helper-module-transforms` - alternately, it could be an opt-in flag on `transform-modules-commonjs`.

**Describe alternatives you've considered**

I'll also file a feature request against `jest`, but they may reject the `async` module initialization approach.

**Teachability, Documentation, Adoption, Migration Strategy**

We can explain this mostly in commonjs terms, and possibly use some language from when an old version of `transform-modules-commonjs` supported similar functionality - before #4302 / #6954. Compared to the hoisting behavior of `transform-modules-commonjs`, a simple transformation from `import ... from` to `const ... require` is straightforward.

**Comment by nicolo-ribaudo** [comment]
We are not going to implement a feature unless it is at least an ECMAScript proposal. TypeScript/Flow/JSX are an exception because they are popular and widely used languages built on top of ECMAScript.

That said, you could enable the parser option `allowImportExportEverywhere` and write your own plugin to transform it.

**Comment by nicolo-ribaudo** [comment]
https://astexplorer.net/#/gist/e2f2e874eaae9fadf7a6a1f17449741f/8267013c429aa4c29f7d2ab7cff898e91c5f614f
