### ISSUE TITLE
Map and Set polyfills lack .keys(), .values(), and .entries()

### ISSUE THREAD

**Issue by AgentME** [babel/babel#1086]
If there is no native Map and Set present, then the polyfills from babel-runtime/core-js don't have the keys(), values(), or entries() methods.

This especially caught me off-guard because core-js (even 0.6.1) itself has them, which I'm pretty sure babel's runtime is based on:

```
> global.Set
undefined
> var foo = require('core-js')
undefined
> Set.prototype.keys
[Function]
```

```
> global.Set
undefined
> var _core = require("babel-runtime/core-js")["default"];
undefined
> _core.Set.prototype.keys
undefined
```

**Comment by sebmck** [comment]
`babel-runtime/core-js` is just `core-js/library`. Please report whatever issues you may be having on the [core-js](https://github.com/zloirock/core-js) repo.

**Comment by AgentME** [comment]
It seems that core-js 0.7.2 has this issue fixed:

```
[chris /tmp/aaa]$ npm i core-js@0.6.1
core-js@0.6.1 node_modules/core-js
[chris /tmp/aaa]$ node
> var _core = require('core-js/library');
undefined
> _core.Map.prototype.keys
undefined
[chris /tmp/aaa]$ rm -rf node_modules/
[chris /tmp/aaa]$ npm i core-js
core-js@0.7.2 node_modules/core-js
[chris /tmp/aaa]$ node
> var _core = require('core-js/library');
undefined
> _core.Map.prototype.keys
[Function]
```

**Comment by sebmck** [comment]
I'll push out a new version with an updated `core-js` in the morning. Feel free to harass me if I forget.

**Comment by zloirock** [comment]
Yep, old bug with multiple shims and feature detection, discussed ~month ago at gitter.

**Comment by sebmck** [comment]
@zloirock Ah, didn't realise this was the same issue.
