### ISSUE TITLE
@babel/plugin-transform-react-constant-elements is not create _ref for component in case of using object destructuring syntax

### ISSUE THREAD

**Issue by Mrdev1ce** [babel/babel#10879]
## Bug Report

**Current Behavior**
@babel/plugin-transform-react-constant-elements is not create _ref for component in case of using object destructuring syntax.
As you can see in example - _ref variable was used, but it was not defined. 

**Input Code**
- Babel REPL
https://babeljs.io/repl#?browsers=ie%20%3E%3D%2010%2C%20Chrome%20%3E%3D%2054%2C%20last%202%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4aUQk6x0k4BeOAb3LhwAsgE8Awrkg0kNGAC44ACjA4wdAJTcAfHBUQ1AOiYtyAXwrV68AEYBXYABsAJgBVW8HouNJNXHf0FLBj5RCXBaGRhTbjhvNg4KQSIYWygaJV8dRQFBOAAeUMkI2VjmJC5eb2iAei0c9QpTciA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.7.5&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.7.4%2C%40babel%2Fplugin-transform-destructuring%407.7.4

**Input:**
```js
import React from 'react';

const namespace = {
  MyComponent: (props) => props.name
};
const buildTest = (name) => {
  const {MyComponent} = namespace;
  return () => (
    <MyComponent name={name} />
  );
}
```
**Output:**
```js
"use strict";

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var namespace = {
  MyComponent: function MyComponent(props) {
    return props.name;
  }
};

var buildTest = function buildTest(name) {
  var MyComponent = namespace.MyComponent;
  return function () {
    return _ref;
  };
};
```
**Expected behavior/code**
_ref variable should be created.

**Expected output:**
```js
"use strict";

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var namespace = {
  MyComponent: function MyComponent(props) {
    return props.name;
  }
};

var buildTest = function buildTest(name) {
  var MyComponent = namespace.MyComponent,
      _ref =
  /*#__PURE__*/
  _react.default.createElement(MyComponent, {
    name: name
  });

  return function () {
    return _ref;
  };
};
```
But it's still possible to achieve expected behavior if don't use destructuring syntax.

Edits by @JLHwung : simplified the REPL setup.

**Comment by amadeus** [comment]
This is a very similar issue that I ran into as well - here's a small repro - for me it appears to be an issue when ALSO using the es2015 preset:

https://babeljs.io/repl#?browsers=ie%20%3E%3D%2010%2C%20Chrome%20%3E%3D%2054%2C%20last%202%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvAMolYwAWwzAczgBeOAAoAlCIB8cZgFcANovp0sAD0iw4AEywFkSwvOb5gLOPNRYAouuThFWMQG9kAGjgAjT7hFwDRWsAXwAuFGYAT08dcK8ICCdkZglw7DwYADp0_AA5CD04Fzo4OEoYeShmTCosqywAWSwQCDES0vEpYVk2jo6AHk4Qbj5Bdr7S5GE3YPGJr2mvWYmO3GncZZW4AHptuABVUxJh5nhFfixvLEUIAHc4GAhvSmQAa3FmCBhgXEuAfUoBAATHIsAA3LBQOACbjoPQEC46CRzPq7XTTHSbVHSOYSdxzADaHm8vhiAF12hJ6MEgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Ctypescript&prettier=false&targets=&version=7.7.5&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.7.4

**Comment by Pyrolistical** [comment]
I think I know why the `_ref` just disappears. I linked https://github.com/storybookjs/storybook/issues/11060 which revealed the `_ref` was being shoved into an import statement resulting in invalid code. I then subsequent transform from es modules to requires drops the invalid code.

**Comment by Pyrolistical** [comment]
should be fixed by https://github.com/storybookjs/storybook/pull/11086
