### ISSUE TITLE
Cannot parse json object with two keys. Unexpected token expected ";" 

### ISSUE THREAD

**Issue by chenyuncai** [babel/babel#10877]
## Bug Report

**Current Behavior**
We want to use babel/parser to extrac the strings in my code to auto localization. I write my own html parse to get the js code and send the js code to 'babel/parser'.

**Input Code**

```js
const parser = require("@babel/parser");
var code = "{a: 1, b : 2}"  // cannot parse this line
// var code = "{a: 1}" // When i cut the second property, it runs OK.
// var code = "{a: 1; b : 2}" // change the comma to semicolon， it runs OK.
let result = parser.parse(code, {
  allowAwaitOutsideFunction: true,
  allowImportExportEverywhere: true,
  allowReturnOutsideFunction: true,
  allowSuperOutsideMethod: true,
})
console.log(result)
```

**Expected behavior/code**
Expected return the same status about fail or success. But one of them goes wrong.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
We use none of any config file, just run in my code directlly.
```

**Environment**

```
Just NodeJS v8.12.0

```
- Babel version(s): [v7.4.3, v7.5.5] tried both
- Node/npm version: [Node 8.12.0 / npm 6.4.1]
- OS: [OSX 10.15.1]
- Monorepo: [no]
- How you are using Babel: [just require]

**Possible Solution**
Sorry, I have no any idea to solve this

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/8945203/70996631-2a3b2780-210e-11ea-87f0-ad148ce2aae4.png)

**Comment by JLHwung** [comment]
It is expected, because JSON file is not a valid JavaScript file.
```
$ node -e "{a: 1, b : 2}"
[eval]:1
{a: 1, b : 2}
         ^

SyntaxError: Unexpected token ':'
    at new Script (vm.js:87:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at evalScript (internal/process/execution.js:82:25)
    at internal/main/eval_string.js:23:3
```

> We want to use babel/parser to extract the strings in my code to auto localization. I write my own html parse to get the js code and send the js code to 'babel/parser'.

I am not sure that I follow. Can you give an example on how you use `@babel/parser`?

**Comment by nicolo-ribaudo** [comment]
For JSON, you can use `JSON.parse` instead of `@babel/parser`.

**Comment by chenyuncai** [comment]
Thx guys, it's my fault.

I'm writing a tool to extract strings from original vue files with babel/parser. 

The attr of some Node has the form like ' :param="{a: 1, b: 2}".

So I need to deal with this satuation on my own manually.

thanks again.
