### ISSUE TITLE
Make naming anonymous functions optional.

### ISSUE THREAD

**Issue by romeovs** [babel/babel#1087]
I'm having a problem with the automatic renaming of anonymous functions.

Since I'm uploading some of the functions to couchdb, and couchdb doesn't allow named functions,
this *is* a problem.

There should be a way to turn of automatic naming of anonymous functions.

**Comment by wycats** [comment]
I'm deeply worried about this kind of stuff. We can make ES6 not have ES5 semantics, but that's just going to perpetuate "ES6" code that is broken and won't work on real ES6 engines.

**Comment by eventualbuddha** [comment]
Can you give a specific example? Which anonymous functions are being renamed?

**Comment by sebmck** [comment]
@eventualbuddha He's talking about the function expression name inference.

```javascript
```

**Comment by sebmck** [comment]
@eventualbuddha He's talking about the function expression name inference.

```javascript
var foo = function () {};
```

becomes

```javascript
var foo = function foo() {};
```

@romeovs You can already disable any of the transformers. :smile: 

```javascript
require("babel").transform("code", { blacklist: ["spec.functionName"] });
```

```sh
$ babel --blacklist spec.functionName script.js
```

**Comment by pmowrer** [comment]
Thanks, this is great to know!

Our use case concerns Angular injection, where parameter names are very sensitive. We have a scenario where an identifier and a parameter name are identical. In this case, Babel renames the parameter in order to avoid collision with the generated function name.

```javascript
let foo = function(foo) {}
```
becomes (using Babel 5.8.23)
```javascript
var foo = function foo(_foo) {};
```

It would seem safer to me if the auto-generated function name was the one prefixed with `_`.

**Comment by Harut** [comment]
Hi! How do I disable this in babel 6? blacklist option has been removed

**Comment by jljouannic** [comment]
I managed to prevent naming of anonymous functions by not using `es2015` preset, but instead declaring all the plugins listed [here](https://babeljs.io/docs/plugins/preset-es2015/), but ommiting `transform-es2015-function-name` in my `.babelrc` file.

I hope there won't be any bad side effects.

**Comment by NedelescuVlad** [comment]
If you are using the `env` preset, check out the `exclude` option and what you can exclude here: https://github.com/babel/babel-preset-env/blob/master/data/plugin-features.js

**Comment by lwr** [comment]
This naming behavior cause problems.

testing code
```js
var s = function c() { console.log(s === c) }; s()
```
all browsers **except IE8** definitely outputs `true`, but **IE8** dosen't

so, after transform, some codes like this were broken
