### ISSUE TITLE
Allow key prop on React fragment in JSX

### ISSUE THREAD

**Issue by njlr** [babel/babel#10888]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**

You cannot add a `key` prop to a React fragment with the concise syntax:

```javascript
<key={myKey}>  // Not allowed
  <h1>Hello, world. </h1>
</>
```

Instead you must use the longer syntax:

```javascript
<React.Fragment key={myKey}> 
  <h1>Hello, world. </h1>
</React.Fragment>
```

This happens when generating elements dynamically, particularly dictionary lists (`<dl>`):

```javascript
<dl>
  {
    terms.map((term, i) => {

      return (
        <key={i}>
          <dt>{term.key}</dt>
          <dt>{term.value}</dt>
        </>
      );
    })
  }
</d>
```

**Describe the solution you'd like**

I would be nice if this were allowed:

```javascript
<key={myKey}> 
  <h1>Hello, world. </h1>
</>
```

**Describe alternatives you've considered**

The more verbose work-around is possible. 

**Teachability, Documentation, Adoption, Migration Strategy**

I am not familiar with Babel source-code, but this seems like a small change. It will not break existing code.

**Comment by rajasekarm** [comment]
Hi @njlr , By default, React is not supporting attributes for <></> including keys.

https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#keyed-fragments

**Comment by nicolo-ribaudo** [comment]
Yeah, this feature request should be made to the https://github.com/facebook/jsx repository.
