### ISSUE TITLE
Not importing Promise.allSettled with useBuiltIns: 'usage'

### ISSUE THREAD

**Issue by leomp12** [babel/babel#10883]
## Bug Report

**Current Behavior**
I'm using `Promise.allSettled` on source code but `core-js/modules/es.promise.all-settled` is not being imported on output.
Other polyfills like `core-js/modules/es.promise` and `core-js/modules/es.promise.finally` are normally imported, the problem seems to be only with [allSettled](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled).
> Is it because `Promise.allSettled()` is still a Draft?

**Input Code**
```js
Promise.allSettled(promises)
  .then(() => {
    // do stuff
  })
```

https://github.com/ecomclub/storefront-template/blob/930db9e9bae1d59d7b09e2292f878c0bbb5d1e2d/template/js/lib/load-widgets.js#L52

**Expected behavior/code**
```js
import 'core-js/modules/es.promise.all-settled'
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`
```js
{
  presets: [
    ['@babel/preset-env', { useBuiltIns: 'usage', corejs: 3 }]
  ],
  plugins: [
    '@babel/plugin-syntax-dynamic-import'
  ]
}
```

- Filename: `.eslintrc.js`
```js
module.exports = {
  parser: "babel-eslint",
};
```

- Filename: `.browserslistrc`
```
last 1 version
not dead
> 0.2%
```

**Environment**

```
  System:
    OS: Linux 5.4 Arch Linux
  Binaries:
    Node: 13.3.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  npmPackages:
    @babel/core: ^7.7.5 => 7.7.5 
    @babel/plugin-syntax-dynamic-import: ^7.7.4 => 7.7.4 
    @babel/preset-env: ^7.7.6 => 7.7.6 
    babel-loader: ^8.0.6 => 8.0.6 
    webpack: ^4.41.2 => 4.41.2
```

**Comment by zloirock** [comment]
https://github.com/babel/babel/issues/10816#issuecomment-564961336

**Comment by leomp12** [comment]
@zloirock you're suggesting to use `corejs: '3.4'`?
I've tried specifying `corejs: '3.4'` (`^3.4.8`), also tried specifying `corejs: '3.5'` (`^3.5.0`), unsuccessfully...
it only worked for me when I added `import 'core-js/modules/es.promise.all-settled'` it manually in the source code.

**Comment by zloirock** [comment]
You should use something like `corejs: '3.5'`, but now it will not work since built-ins definitions broken on the Babel's side. For `useBuiltIns: 'entry'`, `corejs: '3.5'` will fix it.

**Comment by leomp12** [comment]
_Update_: Hadn't tried before with `corejs: { version: 3, proposals: true }`, worked! :sweat_smile:
> But I had tried before with `shippedProposals: true` and it didn't work, `shippedProposals !== corejs.proposals`? :confused:

**Comment by zloirock** [comment]
Sure, but if you don't need the rest proposals and the size of the bundle makes sense for you - I don't recommend to do it, `import 'core-js/modules/es.promise.all-settled'` could be better -)

**Comment by zloirock** [comment]
`shippedProposals` makes no sense for `core-js@3`. `corejs.proposals` injects all built-ins proposals on usage.

**Comment by leomp12** [comment]
got it, thanks @zloirock
