### ISSUE TITLE
Chore/DX: move from make to JS-based taskrunner

### ISSUE THREAD

**Issue by kaicataldo** [babel/babel#10889]
Given the higher barrier for contribution for Windows users introduced by us using `make`, we should explore moving to a JS-based taskrunner. WSL should be the silver bullet for this, but I haven't been able to get `lerna bootstrap` run in WSL (and it [looks like I'm not the only one](https://medium.com/@sinansaka/working-with-lerna-and-yarn-workspaces-in-wsl-25bc28b55368)).

My initial exploration is [here](https://github.com/babel/babel/pull/10881), but some tests are failing and I think it's due to the fact that `shelljs` [doesn't preserve colors in the output of running shell commands](https://github.com/shelljs/shelljs/issues/86).

Some other alternatives:

- Modify the current `shelljs` PR and switch out `shelljs.exec()` for something like [node-cross-spawn](https://github.com/moxystudio/node-cross-spawn) or [execa](https://github.com/sindresorhus/execa).
- Go all in on Gulp
- Use something like [Just](https://microsoft.github.io/just/)

Would love to hear others' opinions on this! 😃

Follow-up question:

We use a lot of shell scripts in the dev build process that don't work natively in Windows. Should we also rewrite these in JS?

**Comment by TomasHubelbauer** [comment]
> We use a lot of shell scripts in the dev build process that don't work natively in Windows. Should we also rewrite these in JS?

Yes, please! I'm not partial about them being in JS, but they should IMO be cross-platform, so there are other options like PowerShell or something. But JS feels like the best choice given the project itself is written in it.

**Comment by JLHwung** [comment]
We do have travis building on Windows: https://travis-ci.com/babel/babel/jobs/268662807 so it is okay to build and test on Windows.

Some of maintenance scripts might not be cross platform, though. Since GNU Make is not bundled in Windows and GNU Make for Windows seems to be not actively maintained (Last updated 13 years ago), switching to JS-based task runner could help reduce the fiction here.

**Comment by thorn0** [comment]
@kaicataldo Did you try adding `"mutex": "file:../babel-mutex"` to `lerna.json`? This made `make bootstrap` work for me in WSL.

**Comment by kaicataldo** [comment]
@thorn0 I have not! Trying to find documentation around this option, but am coming up short. Mind sharing where you found that info? Thanks!

**Comment by thorn0** [comment]
@kaicataldo found it here https://github.com/lerna/lerna/pull/806

**Comment by layershifter** [comment]
Had the same friction during first time contribution, so totally support this 👍

I vote for Gulp as it is a time proven task runner. However any cross platform solution will be great 🙏

**Comment by kaicataldo** [comment]
@thorn0 Thanks for the suggestion, but it's unfortunately still not working for me.

**Comment by danez** [comment]
I once started with all in gulp, but never had the time to continue with it #9674

**Comment by Lodin** [comment]
I'm not sure I understand how `rm -rf` command work in Windows PowerShell in the travis.ci example. Could you please explain it? I'm stuck with setting the babel project up at Windows; even WSL 1.0 does not work with weird errors.

**Comment by kaicataldo** [comment]
I was able to test this in WSL2 today (currently only available in Windows 10 Insider in the Fast Ring), and was able to run everything when the repo was cloned into the Linux installation.

I couldn't even read the directory when trying to access the repo when it was cloned in my Windows home directory that's mounted into the Linux installation.

Definitely still seems like something we should fix.
