### ISSUE TITLE
Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by callum** [babel/babel#1089]
I've run into this a couple of times recently and haven't been able to figure out why it happens. I put together this small test case:

```js
var className = `${prefix}__header`;

var obj = {};
obj[className] = true;
obj[className + '--open'] = true;
obj[className + '--active'] = true;

// This works
var classes = cx(obj);

// This doesn't
var classes = cx({
  [className]: true,
  [className + '--open']: true,
  [className + '--active']: true
});
```

With the error

```
Parse Error: Duplicate data property in object literal not allowed in strict mode
```

**Comment by sebmck** [comment]
I can't replicate this in the [REPL](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=var%20className%20%3D%20%60%24%7Bprefix%7D__header%60%3B%0A%0Avar%20obj%20%3D%20%7B%7D%3B%0Aobj%5BclassName%5D%20%3D%20true%3B%0Aobj%5BclassName%20%2B%20'--open'%5D%20%3D%20true%3B%0Aobj%5BclassName%20%2B%20'--active'%5D%20%3D%20true%3B%0A%0A%2F%2F%20This%20works%0Avar%20classes%20%3D%20cx(obj)%3B%0A%0A%2F%2F%20This%20doesn't%0Avar%20classes%20%3D%20cx(%7B%0A%20%20%5BclassName%5D%3A%20true%2C%0A%20%20%5BclassName%20%2B%20'--open'%5D%3A%20true%2C%0A%20%20%5BclassName%20%2B%20'--active'%5D%3A%20true%0A%7D)%3B).

**Comment by sebmck** [comment]
Actually that error is being thrown by another plugin/parser and isn't Babel, check your other plugins (webpack etc).

**Comment by callum** [comment]
Ah, apologies @sebmck. It's jsxhint-loader.
