### ISSUE TITLE
Webpack with Babel compile fine but I get Uncaught ReferenceError: require is not define

### ISSUE THREAD

**Issue by BjMrq** [babel/babel#10893]
I am having some trouble implementing webpack with babel in a project I inherited.

I would like to use babel and webpack on an existing project, but i get Uncaught ReferenceError: require is not define.

Here is my webpack config:

```js
 const HtmlWebPackPlugin = require('html-webpack-plugin');
 const TerserPlugin = require('terser-webpack-plugin');
 const webpack = require('webpack');
 const nodeExternals = require('webpack-node-externals');
 const path = require('path');

module.exports = {
  entry: `${__dirname}/src/index.js`,
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/'
  },
 plugins: [
 new HtmlWebPackPlugin({
   template: "./public/index.html",
   filename: "./index.html",
   minify: {
     removeComments: true,
     collapseWhitespace: true,
     removeAttributeQuotes: true
    }
  }),
  new TerserPlugin({
    parallel: true,
    terserOptions: {
      ecma: 6,
    },
    })
   ],
 devServer: {
 inline: true,
 hot: true
 },
 devtool: 'sourcemap',
 module: {
   rules: [
    {
     test: /\.jsx?$/,
     exclude: /node_modules/,
     loader: 'babel-loader'
    },
   {
    test: /locales/,
    loader: '@alienfast/i18next-loader',
   },
   {
    test: /\.s?css$/,
    exclude: /node_modules/,
    loaders: ['style-loader', 'css-loader', 'sass-loader']
   },
   {
    test: /\.html$/,
    exclude: /node_modules/,
    loader: 'html-loader'
   },
   {
    test: /\.svg$/,
    exclude: /node_modules/,
    use: ['@svgr/webpack'],
   },
   {
    test: /\.(png|jpe?g|gif)$/i,
    exclude: /node_modules/,
    use: [
      {
        loader: 'file-loader',
       },
      ],
    },
   ]
   },
   resolve: {
   extensions: ['.js', '.jsx']
  },
  externals: [nodeExternals()],
  node: {
   fs: "empty"
  } 
 };
```
here is my babel config file:

```json
 {
 "presets": ["@babel/preset-react"],
 "plugins": [ "transform-class-properties", "@babel/plugin-proposal-object-rest-spread", 
 "@babel/plugin-syntax-dynamic-import", "@babel/plugin-transform-runtime"],
 "sourceType": "unambiguous",
 }
```
I trued quite some combination already but I am stuck, any help would be welcome :)

**Comment by nicolo-ribaudo** [comment]
Which is the source of the original file which, when bundled, throws the error?

**Comment by BjMrq** [comment]
the source file if an index.html document located in:
public/assets

**Comment by nicolo-ribaudo** [comment]
I mean, the file which contains `require`.

**Comment by BjMrq** [comment]
The bundled.js file

(I removed externals: [nodeExternals()], since I am buildng for web (react))

**Comment by nicolo-ribaudo** [comment]
Ok, I'm not being clear enough :sweat_smile: 

The _original_, _untranspiled_ and _unbundled_ files which contains the code that, after bundling, will throw the error.
Does that file contain both `require` and `import`/`export`?

**Comment by BjMrq** [comment]
I am now trying with webpack.config : 

`const HtmlWebPackPlugin = require('html-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const webpack = require('webpack');
const path = require('path');

module.exports = {
  entry: `${__dirname}/src/index.js`,
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/'
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: "./public/index.html",
      filename: "./index.html",
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
      }
    }),
    new TerserPlugin({
      parallel: true,
      terserOptions: {
        ecma: 6,
      },
    })
  ],
  devServer: {
    inline: true,
    hot: true
  },
  devtool: 'sourcemap',
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /locales/,
        loader: '@alienfast/i18next-loader',
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['style-loader', 'css-loader', 'sass-loader', 'resolve-url-loader?sourceMap', 'sass-loader?sourceMap'],
      },
      {
        test: /\.css$/,
        exclude: /node_modules/,
        loader: 'style-loader'
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'html-loader'
      },
      {
        test: /\.svg$/,
        exclude: /node_modules/,
        use: ['@svgr/webpack'],
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        exclude: /node_modules/,
        use: [
          {
            loader: 'file-loader',
          },
        ],
      },
    ]
  },
  resolve: {
    extensions: ['js', '.jsx']
  },
  target: 'web',
  node: {
    fs: "empty"
  }
};
`

Npm packages: 
`{
  "name": "rental-frontend-base",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/core": "^7.7.5",
    "@babel/runtime": "^7.7.6",
    "@trendmicro/react-sidenav": "^0.4.5",
    "@y0c/react-datepicker": "^1.0.1",
    "acorn": "^6.0.5",
    "acorn-dynamic-import": "4.0.0",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^3",
    "cross-env": "^6.0.3",
    "dayjs": "^1.8.15",
    "dotenv": "^8.1.0",
    "express": "^4.17.1",
    "google-maps-react": "^2.0.2",
    "history": "^4.7.2",
    "i18next": "^17.0.13",
    "jquery": "^3.3.1",
    "loadjs": "^3.6.0",
    "moment": "^2.24.0",
    "node-sass": "^4.11.0",
    "popper.js": "^1.16.0",
    "prop-types": "^15.7.2",
    "react": "^16.11.0",
    "react-albus": "^2.0.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-chartjs-2": "^2.7.6",
    "react-charts": "^2.0.0-alpha.12",
    "react-content-loader": "^4.2.1",
    "react-dates": "^20.2.5",
    "react-dom": "^16.8.6",
    "react-dropzone": "^10.2.0",
    "react-facebook-login": "^4.1.1",
    "react-global-configuration": "^1.3.0",
    "react-google-login": "^5.0.4",
    "react-i18next": "^10.12.2",
    "react-input-range": "^1.3.0",
    "react-loading": "^2.0.3",
    "react-progressive-image": "^0.6.0",
    "react-render-html": "^0.6.0",
    "react-responsive-carousel": "^3.1.49",
    "react-router-dom": "^4.3.1",
    "react-scripts": "3.3.0",
    "react-select": "^3.0.4",
    "react-slick": "^0.21.0",
    "react-star-rating-component": "^1.4.1",
    "react-stepzilla": "^6.0.0",
    "react-stripe-elements": "^3.0.0",
    "react-timeout": "^1.1.2",
    "react-toast-notifications": "^1.4.0",
    "react-with-direction": "^1.3.0",
    "reactstrap": "^8.0.1",
    "semantic-ui-react": "^0.87.2",
    "simplebar-react": "^2.0.5",
    "socket.io": "^2.2.0",
    "socket.io-client": "^2.2.0",
    "terser-webpack-plugin": "^2.3.1",
    "webpack": "^4.28.4"
  },
  "devDependencies": {
    "@alienfast/i18next-loader": "^1.1.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.7.4",
    "@babel/plugin-syntax-dynamic-import": "^7.7.4",
    "@babel/plugin-transform-react-jsx-source": "^7.7.4",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.7.6",
    "@babel/preset-react": "^7.7.4",
    "@svgr/webpack": "^4.3.3",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-styled-components": "^1.10.6",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "css-loader": "^3.2.0",
    "eslint": "^4.6.1",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.3.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "file-loader": "^4.2.0",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^3.2.0",
    "sass-loader": "^6.0.6",
    "style-loader": "^1.0.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "scripts": {
    "start": "webpack-dev-server --history-api-fallback --inline --progress",
    "start-script": "PORT=3005 react-scripts start",
    "build": "react-scripts build",
    "babel": "cross-env NODE_ENV=production babel ./src --ignore *.spec.js --out-dir ./build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
`
Babel:
`{
  "presets": ["@babel/preset-react"],
  "plugins": [ "transform-class-properties", "@babel/plugin-proposal-object-rest-spread", "@babel/plugin-syntax-dynamic-import", "@babel/plugin-transform-runtime"],
  "sourceType": "unambiguous",
}`

and the error i got is :+1: 
ERROR in ./src/index.js
Module not found: Error: Can't resolve './App' in '/home/bjmrq/code/BjMrq/Active/ChaletReatreat/chaletRetreat-frontend/src'
 @ ./src/index.js 5:0-24 31:23-26

ERROR in ./node_modules/react-i18next/dist/es/index.js
Module not found: Error: Can't resolve './I18nextProvider' in '/home/bjmrq/code/BjMrq/Active/ChaletReatreat/chaletRetreat-frontend/node_modules/react-i18next/dist/es'
 @ ./node_modules/react-i18next/dist/es/index.js 5:0-52 5:0-52
 @ ./src/index.js


for basicly all my imports

**Comment by nicolo-ribaudo** [comment]
That error is just from webpack and is not related to Babel.

**Comment by BjMrq** [comment]
Oh okay!
I' ll go looking for awnsers in this direction then, thank you!
