### ISSUE TITLE
Contributing on Windows

### ISSUE THREAD

**Issue by TomasHubelbauer** [babel/babel#10891]
Hi, I wanted to spend some time on trying to fix a bug I recently reported: #10869. I've read through the readme, but it mentions `make` as an entry-point to the build. I used Make for Windows, but the scripts seem to be written assuming macOS/Linux, so they didn't run successfully for me.

Is it possible/encouraged to contribute to Babel as a Windows user? Perhaps I need to use WSL?

**Comment by kaicataldo** [comment]
Your timing is impeccable! I just made this issue and am working on it as we speak: https://github.com/babel/babel/issues/10889.

Would you like to close this issue as a dupe and continue the conversation on that issue?

**Comment by TomasHubelbauer** [comment]
Awesome!
