### ISSUE TITLE
Leading comment is lost when using named import just before

### ISSUE THREAD

**Issue by elevatebart** [babel/babel#10892]
## Bug Report

- [X] I would like to work on a fix!

**Current Behavior**
Parsing the code in the section below using `@babel/parser` should return a leadingComments on the export declaration

**Input Code**

```js
import { test } from 'vue-test'

/**
 * lost comment
 */
export default {
   name: 'name-123',
}
```

**Expected behavior/code**
For the `leadingComment` to be attached to the exportDeclaration node

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
```ts
const babelParserOptions: ParserOptions = {
	sourceType: 'module',
	strictMode: false,
	tokens: true,
	plugins: [
		'decorators-legacy',
		'doExpressions',
		'objectRestSpread',
		'classProperties',
		'classPrivateProperties',
		'classPrivateMethods',
		'exportDefaultFrom',
		'exportNamespaceFrom',
		'asyncGenerators',
		'functionBind',
		'functionSent',
		'dynamicImport',
		'numericSeparator',
		'optionalChaining',
		'importMeta',
		'bigInt',
		'optionalCatchBinding',
		'throwExpressions',
		'nullishCoalescingOperator'
	]
}
```

**Environment**

```
 Node 10.17
```
- Babel version(s): v7.6.0
- Node/npm version: Node 10
- OS: windows 10/linux in CI/MacOS Mojave
- Monorepo: M?A
- How you are using Babel: API

**Possible Solution**
I am guessing a starting point would be in one of those 2 commits
https://github.com/babel/babel/pull/10380
https://github.com/babel/babel/pull/10292
https://github.com/babel/babel/pull/10369

**Additional context/Screenshots**
Here is a PR where the issue is visible.
https://github.com/vue-styleguidist/vue-styleguidist/pull/681

**Comment by elevatebart** [comment]
Additionally, this code actually finds the comment

```js
import test from 'vue-test'

/**
 * found comment
 */
export default {
}
```

and this one does not

```js
import test, { otherTest } from 'vue-test'

/**
 * lost comment
 */
export default {
}
```

**Comment by JLHwung** [comment]
@elevatebart Under the hood Babel uses comment attachment algorithm to consume the comments and assign to different AST nodes. It lives in `packages/babel-parser/src/parser/comments.js`, you can take a close look at
https://github.com/babel/babel/blob/80e95d0c833d639157579c765b6624cd4c2696d6/packages/babel-parser/src/parser/comments.js#L171-L181

There is a detailed comment on the third argument `takeAllComments` of `adjustCommentsAfterTrailingComments` thanks to @nicolo-ribaudo 

https://github.com/babel/babel/blob/80e95d0c833d639157579c765b6624cd4c2696d6/packages/babel-parser/src/parser/comments.js#L44-L52

When it's running on an `ImportDeclaration` (`import { test } from 'vue-test'`), the `commentPreviousNode` is an `ImportSpecifier` (`test`) and it will take all `leadingComments` to be the `trailingComment` of `ImportDeclaration`.

In your case, I don't think we can use `takeAllComments: true` here because apparently it can attach to the next node.

**Comment by elevatebart** [comment]
Hello @JLHwung 

I managed to write a fixture for my failing user story.
I am in the process of figuring out how the parser works. 

In the `comments.js` file, I am looking at `processComments()`.

I do not understand why a comment separated by two lines from the previous import (even a named import) should be taken as a trailing comment of the import (and removed from the export).

@nicolo-ribaudo @JLHwung do you guys take newlines into account when tokenizing?
If yes, do we take new lines into account when dealing with comments? 

Thank you both,

**Comment by elevatebart** [comment]
And, is there a way to scope the `make build` command. 

To understand the code, I would love to be able to see it step by step.
To step through it I try debugging and following [the contributor guide](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#debugging-code) I managed to step in the code using vscode debugger with `debugger;` statements. The issue is that for every change I make, it takes 30 seconds to rebuild babel entirely even if I only changed the parser.

Am I doing it wrong ?

**Comment by JLHwung** [comment]
Hi @elevatebart 

Generally the whitespace is ignored when consider what AST nodes should the trailing comments be attached to. Think about the following case

```js
/* my-linter-ignore-start */
foo();
bar();


/* my-linter-ignore-end */
qux()
```

If `/* my-linter-ignore-end */` is not attached as trailing comments of `bar();`, tools will find it difficult to determine the boundary of `my-linter-ignore`. But `/* my-linter-ignore-end */` should _also_ be the `leadingComments` of `qux()`.

> And, is there a way to scope the make build command.

You can run `make watch` for incremental builds. And also the fixture can be generated by
```
OVERWRITE=true yarn jest babel-parser
```

**Comment by elevatebart** [comment]
Understood, thank you,

The desired outcome of my use case is the following:
The "lost comment" should be attached both on the `import` node and on the `export` node

Does this seem correct?

**Comment by JLHwung** [comment]
@elevatebart Correct. It should stay in the state.leadingCommets stack and attach it to the export declaration.
