### ISSUE TITLE
useBuiltIns: "entry" of @babel/preset-env breaks webpack's minimizer

### ISSUE THREAD

**Issue by fancy-rabbit** [babel/babel#10908]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
useBuiltIn: "entry" of @babel/preset-env breaks webpack's minimize plugin(terser-webpack-plugin)
Output Code contains 

```js
/* 237 */
/***/ (function(module, exports) {

module.exports = __CoreJS.modules.es.string.ends-with;

/***/ }),
```
error message: Unexpected token: keyword (with) 

**Input Code**
- REPL or Repo link if applicable:

```js
import 'core-js';
```

while core-js is imported as a webpack external whose global name is __CoreJS

**Expected behavior/code**
will not break terser-webpack-plugin

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const presets = [
    "@babel/preset-react",
    ["@babel/preset-env", { "modules": "cjs", "useBuiltIns": "entry", "corejs": {"version": "3.6", "proposals": true}}]
];
const plugins = [
    "@babel/plugin-transform-async-to-generator",
    ["@babel/plugin-proposal-private-methods", { "loose": true }],

    // previous preset "stage-0"
    // Stage 0
    "@babel/plugin-proposal-function-bind",
    // Stage 1
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    ["@babel/plugin-proposal-optional-chaining", { "loose": false }],
    ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
    ["@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false }],
    "@babel/plugin-proposal-do-expressions",
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-proposal-json-strings",

    ["@babel/plugin-transform-runtime", { "corejs": false, "helpers": true, "regenerator": false, "version": "7.7.7"}],
];
module.exports = function(api) {
     return {presets, plugins};    
}
```

**Environment**

```
  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.19.0 - /usr/bin/yarn
    npm: 6.12.0 - /usr/bin/npm

```
- Babel version(s): 7.7.5 (@babel/core 7.7.7)
- Node/npm version: Node.js 12.13.0/npm 6.12.0
- OS: CentOS 7
- Monorepo: yes
- How you are using Babel: babel-loader

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by fancy-rabbit** [comment]
moreover,  this output code
```js
module.exports = __CoreJS.modules.es.string.ends-with;
```
will break babel itself too, if we run npx babel xxx.js it will throw "Unexpected token" with BABEL_PARSE_ERROR.

**Comment by ethan-pearce** [comment]
Same issue here too 🙋🏻‍♂️

**Comment by nicolo-ribaudo** [comment]
First of all, I suggest removing `"modules": "cjs"` from your Babel config since you are already using webpack.

Also, could you try replacing `import "core-js"` with `import "core-js/modules/es.string.ends-with"` and disable `useBuiltIns` in your config?
By doing so, we disable Babel's transformation of `core-js` imports and we can understand if the problem is caused by Webpack or by Babel.

**Comment by fancy-rabbit** [comment]
removing "modules":"cjs" could lead to some compatibility problems in our project because not all the modules are ES2015 compliant(i.e. use import and module.exports) and they work well with Babel 6 defaults, huh... modifying them could be a big project.

Replacing import 'core-js' with import "core-js/modules/es.string.ends-with" works without problem.

**Comment by nicolo-ribaudo** [comment]
Ok, could you also try replacing it with `require("core-js/modules/es.string.ends-with")`?
Also, do you have a repository which reproduces the issue I could look at?

**Comment by fancy-rabbit** [comment]
replacing it with require have the same problem:
in development mode, the generated code is like
'''js
eval("module.exports = __CoreJS.modules.es.string.ends-with;\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,*****\n//# sourceURL=webpack-internal:///core-js/modules/es.string.ends-with\n");
'''
and in production mode, the generated code is like
'''js
/***/ 100:
/***/ (function(module, exports) {

module.exports = __CoreJS.modules.es.string.ends-with;

/***/ }),
'''
which will be __webpack_require__() -ed.

I'm also wondering if it is a babel issue or a webpack one.

**Comment by nicolo-ribaudo** [comment]
If replacing it with `require` has the same problem, then it's not a Babel bug because Babel doesn't touch that `require()` call (it only transforms `import`s to `require`s).

It's probably a bug with whatever turns that require call into `__CoreJS.modules.es.string.ends-with` (which I don't know if is a webpack core feature or a webpack plugin).

**Comment by fancy-rabbit** [comment]
seems to be a webpack core feature since disabling all the plugins is uselss. I'll report an issue to them. Thanks very much~

**Comment by fancy-rabbit** [comment]
@ethan-pearce maybe we'd better move to https://github.com/webpack/webpack/issues/10172

**Comment by ethan-pearce** [comment]
@fancy-rabbit Yeah seems the most sensible
