### ISSUE TITLE
Add numeric separator to shippedProposals in preset-env

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#10921]
## Feature Request

<div align="center">

### Numeric Separator is Stage 3 and shipped in Chrome 75/Firefox 70/Safari 13!
<pre>
<code>
![](https://example.com/you-know-how-excited-i-am.gif)
</code>
</pre>
</div>

This means that it should be enabled via `shippedProposals: true` options in `@babel/preset-env` :tada:

It should be done similarly to this commit: https://github.com/babel/babel/pull/8438/commits/28bbd9fb0e010e077bf1e4c3ec4fa25098ea9430

1. Add it to `packages/babel-preset-env/src/available-plugins.js`
1. Add the `compat-table` mapping to `packages/babel-preset-env/data/plugin-features.js` (you can find the correct feature name at https://kangax.github.io/compat-table/esnext/)
1. Add it to `packages/babel-preset-env/data/shipped-proposals.js`
1. Run `cd packages/preset-env` and `yarn build-data` to update the data about the supported browser versions
1. Add it to `@babel/preset-env-standalone` (`packages/babel-preset-env-standalone/src/available-plugins.js`)
1. Update the test as needed (you don't need to write new tests)
1. PR! :tada:

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test if needed (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-preset-env` to run the tests
    - Since you don't need to write new tests, you can run `OVERWRITE=true yarn jest babel-preset-env` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by Wetinee** [comment]
I'd like to try this out, with such detailed instructions above.  ;)

**Comment by rajasekarm** [comment]
@Wetinee Any updates on this issue? Let us know if you need any help.

**Comment by Wetinee** [comment]
> @Wetinee Any updates on this issue? Let us know if you need any help.

Sure! It should be done by tomorrow. ;)

**Comment by AjayPoshak** [comment]
I would like to give it a try.

**Comment by existentialism** [comment]
@AjayPoshak let's give @Wetinee a chance to respond!

**Comment by JLHwung** [comment]
@Wetinee has talked to me offline a bit. She's working on it after the holiday seasons.
