### ISSUE TITLE
plugin-transform-modules-commonjs: export binding not updated by 'for...in' and 'for...of'

### ISSUE THREAD

**Issue by ajafff** [babel/babel#10941]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
If an exported binding is used as LHS in a ForOfStatement or ForInStatement, only the local variable is updated. The exported binding stays the same.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAG2PAZhCcC8cDkBLAOzxjwEMEcBuAKGrSjgAo0NC4BvMKCMALjgCMAXwCUHIbXpMWcCCjgBtHMCQBbYARg4AumPYS60JuxZDZ8hSfT8cAE2ABnGFACuAYxguowWziG7xWiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2016&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.7.5

```js
export let foo = 'initial';

for (foo in {prop: 1}) {}

for (foo of ['element']) {}

for ({foo} of [{foo: 'destructured'}]) {}
```

**Expected behavior/code**
`exports.foo` should be updated every time `foo` is assigned a new value.
I tested the code without transpilation in Node.js and it works as expected.

**Comment by vedantroy** [comment]
I'll work on a fix.

**Comment by vedantroy** [comment]
I'll take a shot at this.

**Comment by vedantroy** [comment]
@ajafff How did you test the given code sample in Node.js. I tried running it, but Node.js does not support `export let foo = ` syntax.

I think I'm confused, but it seems like in Node.js, the expected behavior is not for `exports.foo` to be updated.

For example:

```
exports.foo = 'initial'

for(foo of ['element']) {
    console.log(foo)
    console.log(exports.foo)
}
```
Outputs
```
element
initial
```
not
```
element
element
```

Or are you referring to the fact that if I run the following two files in the browser (without transpilation):

**lib.js**
```
export let foo = 1;

export function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms))
}

(async () => {
    for (foo of [2, 3, 4, 5, 6, 8, 9, 10]) {
        await sleep(1000)
    }
})()
```

**index.js**
```
import { foo, sleep } from './lib.js'

(async () => {
    for (let i = 0; i < 10; i++) {
        await sleep(1000)
        console.log(foo)
    }
})()
```
the output will be
```
1
2
3
...
```

Whereas, if Babel compiles these files + the files are bundled with a bundler, the output will just be:
```
1
1
1
...
```

If so, I tested with a bable + a bundler (parcel), and the output Javascript indicated that `exports.foo` was being assigned to/updated in the for loop. `exports.foo = _arr[_i]`

**Comment by ajafff** [comment]
You can run the untranspiled code in Node.js by using the `--experimental-modules` option and using `.mjs` as file extension.
The behavior is the same as running the untranspiled code in the browser.

Since the transpiled code should be semantically identical, it should update `exports.foo` whenever `foo` is updated.

---

I don't know exactly how these presets work. It seems like "es2015" is transpiling the `for...of` loop to a regular `for` loop before the commonjs transformer is executed. That already works, because there's an explicit assignment to `foo` which the commonjs transform is able to find. This bug is only about transpiling to ES6 or higher.

**Comment by vedantroy** [comment]
@ajafff It seems like the solution to this issue, is make Babel replace

```
for(foo of [1, 2, 3]) {
}
```
with
```
for(exports.foo of [1, 2, 3]) {
}
```

**Comment by ajafff** [comment]
@vedantroy while your suggested fix works, there's another case that it doesn't cover: You can export the same variable multiple times with different names:

```js
export let foo;
export {foo as bar};

for (foo of [1, 2]) {}
```

should give roughly this code:

```js
let foo;
for (foo of [1, 2]) {
  exports.foo = exports.bar = foo;
}
```

**Comment by vedantroy** [comment]
Status update.

I managed to partially fix the issue. Look at this commit: https://github.com/vedantroy/babel/commit/18c95592cf4c861763cf4d616ddad9cc57328ef1

Currently:
```
export let foo  = 42;
for (foo of [1, 2, 3]) {
}
```
is transpiled to
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = void 0;
let foo = 42;
exports.foo = foo;
for (let _foo of [1, 2, 3]) {
  exports.foo = foo = _foo
}
```
However, the transpilation is broken when the inner loop body re-declares the exported variable, like this:
```
export let foo = 42;
for (foo of [1, 2, 3]) {
   let foo = 3;
}
```
this transpiles to
```
// the usual export boilerplate
for (let _foo2 of [1, 2, 3]) {
  foo = _foo2
  // This loop body is transformed incorrectly
  // correct output should be
  // exports.foo = _foo2
  let foo = 3;
}
```
Do any Babel contributors have thoughts?
