### ISSUE TITLE
null in ArrayExpression elements type

### ISSUE THREAD

**Issue by ciez** [babel/babel#10948]
## Feature Request
ArrayExpression elements type is [currently defined](https://github.com/babel/babel/blob/26eb8918702552c98bbe2dd9f41dd1d6aaeb7a1f/packages/babel-types/src/definitions/core.js#L26) as 

```
interface ArrayExpression extends BaseNode {
  type: "ArrayExpression";
  elements: Array<null | Expression | SpreadElement>;
}
```
However Expression already includes NullLiteral.

Is _null_ in the current definition different from NullLiteral? 

If _null_ is not the same as NullLiteral, when  would the parser return _null_, and when - the NullLiteral object?

**Comment by JLHwung** [comment]
Hi @ciez, they are good questions. Let me try to answer them.

> Is null in the current definition different from NullLiteral?

Yes.

> If null is not the same as NullLiteral, when would the parser return null, and when - the NullLiteral object?

`[,]` will be parsed as `elements: [null]` while `[null]` will be parsed as `elements: [NullLiteral]`.

Happy hacking babel and happy new year!

**Comment by ciez** [comment]
Thank you kindly Huáng!

It is a very clear explanation.

Happy New Year!
