### ISSUE TITLE
Not getting errors when using Promises

### ISSUE THREAD

**Issue by chrisabrams** [babel/babel#1094]
Please see [my repo](https://github.com/chrisabrams/babel-error-missing) for an example. How do you see the errors that a promise swallows without console.something from the error handler of the promise?

**Comment by fkling** [comment]
I doubt this has anything to do with babel. The `Promise` polyfill comes from core-js, but Chrome and Firefox already implement it natively.

This is actually once of the controversial points of promises (afaik). If you don't add a "fail" handler, you may miss errors. But Chrome actually tells you about uncaught errors:

```
> Promise.resolve().then(function() { throw 42 });
Uncaught (in promise) 42
```

**Comment by chrisabrams** [comment]
I can't run Chrome on Node.js though :/. I'll take a look at core-js.

**Comment by fkling** [comment]
As I said, this is native behavior of promises. Your best bet may be to provide a wrapper around promises which always adds a failure callback.

**Comment by zloirock** [comment]
io.js and `core-js` `Promise` supports `unhandledRejection`:
```js
process.on('unhandledRejection', console.error.bind(console, 'unhandledRejection'));
Promise.reject(42);
// unhandledRejection 42 {}
```
But `core-js` not polyfilled it for Node 0.12 `Promise`.

**Comment by vjpr** [comment]
Thanks @zloirock, without this I had the most insanely difficult bugs to track down. It feels so dangerous not having this enabled by default.
