### ISSUE TITLE
a?.b.c() produces different result than a?.b!.c()

### ISSUE THREAD

**Issue by proteriax** [babel/babel#10959]
## Bug Report

- [ ] I would like to work on a fix!

**Input Code**
- REPL or Repo link if applicable:

```js
a?.b.c()
a?.b!.c()
```

**Actual behavior**
```js
"use strict";

var _a, _a2;

(_a = a) === null || _a === void 0 ? void 0 : _a.b.c();
((_a2 = a) === null || _a2 === void 0 ? void 0 : _a2.b).c();
```

**Expected behavior/code**
The `!` should have no effect on the produced code.

Problem: Suppose `a` is null, then the second line can be reduced to:
```js
   ((_a2 = a) === null || _a2 === void 0 ? void 0 : _a2.b).c()
=> ((a2 = null) === null || _a2 === void 0 ? void 0 : _a2.b).c()
=> (null === null || _a2 === void 0 ? void 0 : _a2.b).c()
=> (true ? void 0 : _a2.b).c()
=> undefined.c()
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-typescript", "@babel/preset-stage-3"]
}
```

**Environment**
- Babel version(s): 7.7.7
- How you are using Babel: https://babeljs.io/repl

**Possible Solution**
¯\\\_(ツ)_/

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by macabeus** [comment]
I'm working in a fix to this bug.

**Comment by macabeus** [comment]
PR opened: https://github.com/babel/babel/pull/10961

**Comment by nicolo-ribaudo** [comment]
This is correct. For reference, this is what the TypeScript compiler (verision 3.8) does: [[TS Playground](https://www.typescriptlang.org/play?ts=3.8.3#code/IYfgdARmDGBQqQIQ1vcVoAoCUakx1iA)]

```js
a?.b.c
a?.b!.c

a?.b.c()
a?.b!.c()
```

```js
a === null || a === void 0 ? void 0 : a.b.c;
(a === null || a === void 0 ? void 0 : a.b).c;
a === null || a === void 0 ? void 0 : a.b.c();
(a === null || a === void 0 ? void 0 : a.b).c();
```

And this is Babel's output: [[Babel repl](https://babeljs.io/repl/#?browsers=chrome%2070&build=&builtIns=false&spec=false&loose=false&code_lz=IYfgdARmDGBQqQIQ1vcVoAoCUakxyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Ctypescript%2Cenv&prettier=true&targets=&version=7.9.0&externalPlugins=%40babel%2Fplugin-syntax-class-properties%407.8.3)]
```js
(_a = a) === null || _a === void 0 ? void 0 : _a.b.c;
((_a2 = a) === null || _a2 === void 0 ? void 0 : _a2.b).c;
(_a3 = a) === null || _a3 === void 0 ? void 0 : _a3.b.c();
((_a4 = a) === null || _a4 === void 0 ? void 0 : _a4.b).c();
```

**Comment by proteriax** [comment]
@nicolo-ribaudo There’s a bug filed at the TypeScript repo.
