### ISSUE TITLE
sourcemap not mapping correct

### ISSUE THREAD

**Issue by xianwei-lu** [babel/babel#10952]
## Bug Report

sourcemap not mapping correct when using babel-loader

**Current Behavior**

**project old-babel behavior**

![image](https://user-images.githubusercontent.com/28993048/71669119-97a1b600-2da6-11ea-8426-992e2c95ba13.png)

**project test-project behavior**

![image](https://user-images.githubusercontent.com/28993048/71669016-4691c200-2da6-11ea-9db5-2f4e0a30ad13.png)

**Input Code**
there is my demo
[https://github.com/xianwei-lu/npm-test](url)

![image](https://user-images.githubusercontent.com/28993048/71669235-f404d580-2da6-11ea-93d1-3c3eeada02a3.png)

package is an npm package
test-project is create by create-react-app
old-babel is create by myself

**Expected behavior/code**

I want to konw，how to configure project old-babel，that make sourcemap same with test-project, rather than sourcemap after babel
there is my config in demo

![image](https://user-images.githubusercontent.com/28993048/71669518-e00da380-2da7-11ea-869b-0cc833239e4e.png)
![image](https://user-images.githubusercontent.com/28993048/71669561-003d6280-2da8-11ea-8e08-918fc861d786.png)

**Environment**

```

```
- Babel version(s): [v7.1.1]
- How you are using Babel: [`loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
I think it falls onto webpack configuration issues, and given that CRA works as expected, the issue is likely from an invalid configurations. Please submit this issue to the webpack communities.
