### ISSUE TITLE
Recursing combined with destructuring and more than 1 argument breaks.

### ISSUE THREAD

**Issue by PaulAvery** [babel/babel#1095]
The following:

	function resolve({a, b}, c) {
		return resolve();
	}

results in:

	"use strict";
	
	function f(_x, _x2) {
		var _again = true;
	
		_function: while (_again) {
			var a = _ref.a;
			var b = _ref.b;
			_again = false;
			var _ref = _x,
			    c = _x2;
			a = b = undefined;
			_again = true;
			continue _function;
		}
	}

This obviously breaks, as `_ref` is accessed before being declared.
It only seems to happen, if the function is named (and recurses by calling itself by that name) and takes more than one argument.
The above example is the smallest I could narrow it down to. I realise it would create an endless loop, but the problem still exists, if you make the recursing conditional.

I hope this issue is not a duplicate of anything and I did not accidentally miss another issue.
Tested with babel@4.7.16, straight from npm.

**Comment by sebmck** [comment]
Looks like it's due to the statement hoisting.

**Comment by sebmck** [comment]
Looks like this was fixed via ed6421876ae46bf9dbf9458cb0539817309494e2.
