### ISSUE TITLE
Feature Request: @babel/preset-typescript import names transform

### ISSUE THREAD

**Issue by Banou26** [babel/babel#10951]
## Feature Request
- [x] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**
When using babel on a folder with `.ts` files, the output files are renamed to `.js`, but ESM `import`s are kept with the `.ts` extension,

**Describe the solution you'd like**
When using `@babel/preset-typescript`, in addition of renaming files from `.ts` to `.js`, we should rename ESM `import`s from `.ts` to `.js`

**Teachability, Documentation, Adoption, Migration Strategy**
It shouldn't add backward compatibility issues since:
People using Typescript doesn't put file extensions in their import as it's invalid typescript.
But with some nifty Deno plugin you are actually able to remove all of the errors regarding file extensions and imports in VSC.
Having file extensions in imports just seems right to me, and with the coming of ESM and top level await, this would make us able to do dynamic multi-platform scripts with nice syntax, and i'd really like having those advantages working with Typescript

**Comment by nicolo-ribaudo** [comment]
Since changing extensions in import paths isn't specific to TypeScript, I think that it should be a separate plugin.
Would https://github.com/tleunen/babel-plugin-module-resolver wotk for you?

**Comment by Banou26** [comment]
Alrighty, i'll make an issue over there then.
Thanks :)
