### ISSUE TITLE
Not transforming to ES5

### ISSUE THREAD

**Issue by Hydroper** [babel/babel#10957]
I already used Babel once, but now I'm unable to transform a single `src` directory into ES5/ES3 syntax.

Reproduction:

```
$ npm install --save-dev @babel/core @babel/cli
$ npm install --save-dev @babel/preset-env
$ babel src -d src_es3
```

Somehow sources into `src_es3` still contain ES2015 `class`.

**Comment by nicolo-ribaudo** [comment]
You need to create a configuration file:

```json
// babel.config.json

{
  "presets": ["@babel/preset-env"]
}
```
