### ISSUE TITLE
[babel-generator]: jsescOption.numbers does not affect NumericLiterals

### ISSUE THREAD

**Issue by sanex3339** [babel/babel#10960]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
Currently, when I set:

```
{
    jsescOption: {
        numbers: 'hexadecimal'
    }
}
```
This option has not affects any numbers that `@babel/generator` is generated.

For example i need the following in the output generated code:
```
var foo = 0x1;
```

**Expected behavior/code**
```
{
    jsescOption: {
        numbers: 'hexadecimal'
    }
}
```
This option should affect any numbers that `@babel/generator` is generated

- @babel/generator version: 7.7.7 
- Node/npm version: Node 12

**Possible Solution**
Looks like here: https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/types.js#L121
number value should be generated using `jsesc` like in `StringLiteral`

**Comment by sidntrivedi012** [comment]
@nicolo-ribaudo I would like to work on this. Can you please guide how to proceed? Thanks :)

**Comment by sanex3339** [comment]
Set the options as descrived above.

With these options, all numbers should be generated in hexadecimal view:
`0` -> `0x0`

**Comment by sidntrivedi012** [comment]
Made a Draft PR at #11028 . PTAL.

**Comment by sanex3339** [comment]
Thank you!
