### ISSUE TITLE
Multiple spreads

### ISSUE THREAD

**Issue by ivan-kleshnin** [babel/babel#1096]
Not supported yet?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

> Just like with spread for argument lists ... can be used anywhere in the array literal and it can be used multiple times.

Snippet quote, which is expected to work:
```javascript
  var someArgs = ["a", "b", "c"];
  var moreArgs = [1, 2, 3];
  // Using the spread operator twice, with a non-spread argument
  console.log(...someArgs, "between", ...moreArgs);
```

Produces an error: **Spread must be the final element of an element list**

**Comment by sebmck** [comment]
No, that works. You're probably using a webpack plugin or something similar that doesn't support it.

**Comment by ivan-kleshnin** [comment]
Heck, yeah. That's esprima parser issue https://github.com/jquery/esprima/issues/1057

**Comment by elskwid** [comment]
@ivan-kleshnin just happened to see that the [issue above](https://github.com/jquery/esprima/issues/1057) has been closed. Thought you might like to know. :smile:

**Comment by ivan-kleshnin** [comment]
@elskwid thanks :+1:
