### ISSUE TITLE
Parentheses removed falsely when transforming nullish-coalescing-operator

### ISSUE THREAD

**Issue by dword-design** [babel/babel#10966]
## Bug Report

**Current Behavior**
When transforming an AST containing a nullish coalescing operator, parentheses are removed falsely, leading to different behavior.

**Input Code**
```js
const babel = require('@babel/core')
const { readFileSync, writeFileSync } = require('fs')

const code = readFileSync('src/index.js')
// src/index.js:
// const foo = 'test'
// console.log((foo ?? '') == '')

const babelConfig = {
  plugins: [
    '@babel/plugin-proposal-nullish-coalescing-operator',
  ],
}

// this works as expected
const ast = babel.parseSync(code, babelConfig)

// this removes the parentheses
const { code: transformedCode } = babel.transformFromAstSync(ast, code)

writeFileSync('dist/index.js', transformedCode)
// dist/index.js:
// const foo = 'test';
// console.log(foo ?? '' == '');

const babelRegister = require('@babel/register')
babelRegister(babelConfig)

require('./dist')
// outputs 'test' instead of false
```

See also:
https://github.com/dword-design/test-babel-missing-parentheses

**Expected behavior/code**
The resulting file should still contain the parentheses.

**Environment**

- Babel version(s): 7.7.7
- Node/npm version: Node 11.15.0/npm 6.7.0
- OS: macOS 10.14.6
- Monorepo: no
- How you are using Babel: core, register

**Comment by sidntrivedi012** [comment]
Hey, I would like to work on it. Thanks.

**Comment by githubxiaowen** [comment]
You may need to write like this。you just parse the code, not transform it
```
const { code: transformedCode } = babel.transformFromAstSync(
  ast,
  code,
  babelConfig
);
```

**Comment by sidntrivedi012** [comment]
Hey, was working on this issue. Needed some help in that how do we decide precedence in https://github.com/babel/babel/blob/master/packages/babel-generator/src/node/parentheses.js ?

Also, how to find which function in `parentheses.js` implements operations on `??` operator ?

**Comment by nicolo-ribaudo** [comment]
Its precedence should be the same as `??` or lower.

In the spec, they are represented at the same level: https://tc39.es/ecma262/#sec-binary-logical-operators
```
ShortCircuitExpression:
  LogicalORExpression
  CoalesceExpression
```

> Also, how to find which function in parentheses.js implements operations on ?? operator ?

`??`, `&&` and `||` are represented using a `LogicalExpression` node: you can see it on ASTExplorer. [demo](https://astexplorer.net/#/gist/2d7aa7f6ea9b8350d50c0e5e5bd81880/9e1002ec7ed9355bf11de8946dab8385e9523fe0)
You need to create a `LogicalExpression` function, which must return `true` when the node needs parentheses.

**Comment by sidntrivedi012** [comment]
Ok, working on it. Just to confirm, is this causing this issue? https://github.com/babel/babel/blob/master/packages/babel-generator/src/node/parentheses.js#L114-L126

**Comment by nicolo-ribaudo** [comment]
Oh good catch! It seems that the problem is there.
Probably `Binary` is an alias for `BinaryExpression` and `LogicalExpression`.

**Comment by nicolo-ribaudo** [comment]
But removing that `isLogicalEexpression` test would still leave some cases to fix.

**Comment by sidntrivedi012** [comment]
@nicolo-ribaudo so, should I remove the `isLogicalExpression` condition ?

**Comment by sidntrivedi012** [comment]
Also, here true is already returned for it - https://github.com/babel/babel/blob/master/packages/babel-generator/src/node/index.js#L111

**Comment by nicolo-ribaudo** [comment]
Oh right, we are already handling cases of mixed `??` and `||`/`&&`. Then assigning the correct precedence might be enough.
Btw, if you have other questions please open a draft PR so that it's easier to see what you are doing!
