### ISSUE TITLE
Empty coverage report when using "type": "module" with babel/register

### ISSUE THREAD

**Issue by IgorNovozhilov** [babel/babel#10970]
Empty coverage report when using `"type": "module"` in "package.json".

```
  "devDependencies": {
    "@babel/register": "latest",
    "@babel/plugin-proposal-class-properties": "latest",
    "@babel/plugin-transform-modules-commonjs": "latest",
    "babel-eslint": "latest",
    "babel-plugin-istanbul": "latest",
    "eslint": "latest",
    "eslint-config-standard": "latest",
    "eslint-plugin-import": "latest",
    "eslint-plugin-node": "latest",
    "eslint-plugin-promise": "latest",
    "eslint-plugin-standard": "latest",
    "nyc": "latest"
  }
```

How to configure everything to work "out of the box"?

Example repo: https://github.com/demo-source/node-app

Here is the output in the original:
![изображение](https://user-images.githubusercontent.com/3082812/71974558-d1e5da00-3222-11ea-8aab-62b921b15692.png)

Relying on the message: `ExperimentalWarning: The ESM module loader is experimental.`, I assume that the source code is not converted using the module `@babel/register`, and is still executed as an ESM

But if you manually change the type, but everything works. (`"type": "commonjs"`)
if you add a small plug(https://github.com/demo-source/node-app/blob/master/update-package.cjs), and in real-time to replace the type:
![изображение](https://user-images.githubusercontent.com/3082812/71974504-b11d8480-3222-11ea-8fd0-fa34eadeb301.png)

**Comment by nicolo-ribaudo** [comment]
`@babel/register` only works with commonjs scripts, because node doesn't have a stable API to hook into modules loading yet.

**Comment by IgorNovozhilov** [comment]
@nicolo-ribaudo, Maybe there is a plugin that solves this problem?

**Comment by mAAdhaTTah** [comment]
@IgorNovozhilov No. Node does not yet provide the capabilities needed to create a plugin.

**Comment by IgorNovozhilov** [comment]
Well, then I'll use my solution, maybe someone will be useful:
https://www.npmjs.com/package/babel-hook-esm-to-cjs-package-type-runtime
Or maybe someone will suggest something else...

**Comment by JLHwung** [comment]
Closing this as it is limited by Node.js capabilities.
