### ISSUE TITLE
Suggestion: Move babel-core into separate repo

### ISSUE THREAD

**Issue by joliss** [babel/babel#1097]
At the moment, it seems that the babel and babel-core npm packages both come out of the same repo. This makes `npm link`ing a bit tricky. It might be nicer to have separate repos.

May I suggest moving all code into a separate babel-core repo at some point? Then the babel repo can be a (fairly thin?) CLI frontend that depends on babel-core for its functionality.

**Comment by sebmck** [comment]
They're in the same repo because it's literally the same package with a different `package.json`. [This](https://github.com/babel/babel/blob/master/tools/generate-core-package-json) is the file that generates the `babel-core` `package.json`.

**Comment by joliss** [comment]
Fair enough.

For posterity if anyone else is looking for how to `npm link` it, I figured out to run `make` first to have it update `package.json` to say `name: "babel-core"`, and then `npm link`.

**Comment by sebmck** [comment]
I've since moved the babel cli into `packages/babel-cli`. It will still be published to npm as `babel` (confusing I know) and it'll depend on `babel-core` which is the main `package.json`.

**Comment by joliss** [comment]
:+1: - keeping the main CLI as "babel" is a pretty good choice I think; with Broccoli having to `install -g broccoli-cli` for the command line tool seems to be an occasional source of confusion.
