### ISSUE TITLE
Unexpected token when parsing a member expression after a property initializer in an object pattern

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#10989]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
A clear and concise description of the behavior.

The following snippet will throw SyntaxError: Unexpected token, expected ","
**Input Code**
- REPL or Repo link if applicable: [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwBAhmC8YCwCYA0YBGAuMIC-A6AJmNjFtgJRA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=&prettier=false&targets=&version=7.8.0&externalPlugins=)

```js
({ a = 42, b: {}.d } = {})
```

**Expected behavior/code**
It should parse successfully.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**: No plugin.

**Environment**
REPL

**Possible Solution**
We may reset `refExpressionErrors.shortAssign` when parsing Assignment Expression after eating `tt.colon` in `parseObjectProperty`.

https://github.com/babel/babel/blob/bfb82e778fea5b766e18066a68f79ae3fbbab9bc/packages/babel-parser/src/parser/expression.js#L1732

**Comment by vedantroy** [comment]
I would like to take this up.

**Comment by JLHwung** [comment]
@vedantroy Sure. If it's the first time you are contributing Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

Note that the possible solution is based on my recent refactor branch: https://github.com/JLHwung/babel/tree/fix-6705 I suggest you work from this branch as the code is a little bit different than the master branch.

⚠️The solution is still pretty rough, and and in some situations you may find that it doesn't work at all. Welcome to discuss the solution on the `#development` [Slack](https://babeljs.slack.com/) channel.

**Comment by vedantroy** [comment]
@JLHwung It seems like fix-6705 has been merged into master. I assume this means I can just work with the master branch, correct?

**Comment by JLHwung** [comment]
@vedantroy Correct!

**Comment by vedantroy** [comment]
@JLHwung While messing with the presented test case, I found that `{a = 3} = {}` works in the Chrome DevTools console, but fails in babel. Could this also be considered a bug? If so, I should probably try and fix that first, since it seems like a simpler case of the above bug.

![Valid_Code](https://user-images.githubusercontent.com/8407819/72645601-030c8b80-3942-11ea-8276-0eb2408de116.png)

**Comment by nicolo-ribaudo** [comment]
It's because chrome parses it as an expression. If you use `@babel/parser`'s `parseExpression` it will work, or you have to wrap it in parentheses: `({ a = 3 } = {})`.
