### ISSUE TITLE
`import type` in TypeScript

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#10981]
TypeScript 3.8 will support a new `import type` construct. While there's already some logic for similar stuff (Flow has its own `import type`), TypeScript's has a few extra restrictions.

* `import type` can only be used on imports with named imports or with a default import - but not both.

  ```ts
  import type FooDefault, { Bar, Baz } from "module"; // error!
  ```
* Even though `import type` creates no emit, an `import type` functionally shadows variables from the outer scope, and using these declarations in a value position that will be emitted causes an error.

  ```ts
  import type { RegExp } from "special-regexp-module";

  // Okay - RegExp won't be used at runtime here.
  declare class Foo extends RegExp { }

  // Okay - RegExp won't be used at runtime here.
  let r: typeof RegExp;

  // Error! RegExp is imported via import type and cannot be used as a value here.
  new RegExp()
  ```

See more at

* https://github.com/microsoft/TypeScript/pull/35200
* https://github.com/microsoft/TypeScript/pull/36092
* https://github.com/microsoft/TypeScript/issues/36138

**Comment by DanielRosenwasser** [comment]
CC @andrewbranch

**Comment by kaicataldo** [comment]
For my own understanding, how do we decide what the interface for AST nodes for TypeScript-specific syntax is like? Is there a spec?

**Comment by andrewbranch** [comment]
If it helps, here’s the changes to TypeScript’s parse tree node interfaces: https://github.com/microsoft/TypeScript/pull/35200/files#diff-4b8bd1eea29904f1be39cd864e1a45c0

The only change was adding a boolean `isTypeOnly` property to ImportClause and ExportDeclaration.

**Comment by armano2** [comment]
> For my own understanding, how do we decide what the interface for AST nodes for TypeScript-specific syntax is like? Is there a spec?

i have same issue, i was planning to add this to @typescript-estree but i'm unsure if we want to extend existing `ImportDeclaration` by adding new property to it or creating new node type `TSImportTypeDeclaration`

**Comment by nicolo-ribaudo** [comment]
Currently, we use a `.type` property for flow imports. It would be nice to keep them aligned.

**Comment by armano2** [comment]
`type` property seems good to me, for imports/exports that are not `type` do we want to set is as null or undefined?

**Comment by jridgewell** [comment]
> Currently, we use a .type property for flow imports. It would be nice to keep them aligned.

The [explorer suggests](https://astexplorer.net/#/gist/be2e4a6c169562f6d52e0d00853f467a/fbbe1fb43700251e596d109542b771ef820534c6) we use `importKind: 'type'` for type imports and `importType: 'value'` for value imports.

**Comment by nicolo-ribaudo** [comment]
Oh, you are right :man_facepalming:
And we are using `exportKind` for `export type { x } from "x"`/`export { x } from "x"`.

**Comment by MLoughry** [comment]
I don't suppose anyone's working on a code mod to migrate existing code to this syntax? 🤞

**Comment by andrewbranch** [comment]
@MLoughry if you set `importsNotUsedAsValues: "error"` in your tsconfig, I plan to have a quick fix for the resulting errors. It shouldn’t be too hard to write a small program to do the same across a whole project, but that’s not something tsc or the language service currently supports.

**Comment by nicolo-ribaudo** [comment]
Also, this will be hard to implement using Babel because we don't have type information.

**Comment by MLoughry** [comment]
@andrewbranch Is there a way to programmatically invoke quick fixes across a set of files? Our project is over 20k modules, and tsserver can't really hold the entire project in memory at once. 😅

**Comment by andrewbranch** [comment]
Sort of. There’s a language service command to _get_ code fixes for a given file, which will return text change range information that you should be able to pump into a String.prototype.splice on the string contents of a file and write it back to disk.

**Comment by jridgewell** [comment]
> Also, this will be hard to implement using Babel because we don't have type information.

Actually, I think it'll be really easy for imports. We don't have type information, but we do know whether an imported value is only used in type positions in the AST. The difficult one is for exports, since we have no idea if an `export { Foo } from "foo.js"` is exporting a value or a type.

**Comment by nicolo-ribaudo** [comment]
Oh you are right.
And if someone is already using Babel, `export { Foo } from "foo.js"` will already be broken for them when `Foo` is a type: we can then assume that it is a value.

**Comment by andrewbranch** [comment]
Note that the assumption may not hold up for any re-exported import, not just export declaration re-exports:

```ts
import { Foo } from "foo.js"

function f(p: Foo) {}

// `Foo` was only used as a type *here*, but we still don’t know whether
// it may have a value meaning accessed by another module.
export { Foo };
```

**Comment by jridgewell** [comment]
> Note that the assumption may not hold up for any re-exported import, not just export declaration re-exports:

Yup. We'll have trouble with any re-exported thing. But my intuition is that re-exporting is much less common than using imported values, or only exporting local values.

**Comment by ExE-Boss** [comment]
Will&nbsp;it&nbsp;be&nbsp;possible to&nbsp;import&nbsp;types from&nbsp;`@types/*`&nbsp;packages&nbsp;directly?

## Example:
```ts
import type Foo from "@types/foo";
```

---

This&nbsp;would be&nbsp;particularly&nbsp;useful for&nbsp;importing&nbsp;types from&nbsp;non‑**npm**&nbsp;`@types/*`&nbsp;packages.

**Comment by nicolo-ribaudo** [comment]
I don't see how it's different from importing from any other package, from a Babel point of view.

**Comment by ExE-Boss** [comment]
I thought this was the **TypeScript** repository.

**Comment by kaicataldo** [comment]
Unassigning myself since this will be a team effort! :)

**Comment by nicolo-ribaudo** [comment]
We will also need to introduce the `importsNotUsedAsValues` option (https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports)
