### ISSUE TITLE
If no runtime installed, how our babel transforms es6 feature class?

### ISSUE THREAD

**Issue by zxh19890103** [babel/babel#10984]
I am studying Babel these days. I found that Babel interpolates many helper functions where I use `class`. This is the case I didn't install `@babel/runtime`. When I set the plugin `@babel/plugin-transform-runtime` with `@babel/runtime` installed, Babel requires the helpers for defining `class` from `@babel/runtime`. How does Babel provide these helpers if no `runtime` installed? Thanks.

**Comment by nicolo-ribaudo** [comment]
`@babel/helpers`, a dependency of `@babel/core`, includes the source of all the helpers.
We use it to generate `@babel/runtime`, and `@babel/core` uses it to inject the inline helpers.

I suggest looking at the source code of the `addHelper` function in `@babel/core` 😉

**Comment by zxh19890103** [comment]
> `@babel/helpers`, a dependency of `@babel/core`, includes the source of all the helpers.
> We use it to generate `@babel/runtime`, and `@babel/core` uses it to inject the inline helpers.
> 
> I suggest looking at the source code of the `addHelper` function in `@babel/core`

Got. Thank you very much.
