### ISSUE TITLE
Code too slow because of "mutating the [[Prototype]] of an abject [..]" error

### ISSUE THREAD

**Issue by pindamonhangaba** [babel/babel#1099]
Using browser-polyfill.js my app gets so slow it momentarilly makes firefox not respond, with the warning.
     
    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by sebmck** [comment]
This is not an issue with Babel. Please report it on the [core-js](https://github.com/zloirock/core-js) repo. cc @zloirock
