### ISSUE TITLE
Latest version breaks on node<10

### ISSUE THREAD

**Issue by abhinavsingi** [babel/babel#10990]
## Bug Report

**Current Behavior**
semver is included as "^7.1.1" in following:
https://github.com/babel/babel/pull/10899/files#diff-ef7266ff2423fa596fa449062b0b725fR23
https://github.com/babel/babel/pull/10899/files#diff-284fef7c611cebc1a424f6a765782a30R28

Newly created packages `babel-compat-data` and `babel-helper-compilation-targets` seems to be using v7.1.1 of semver which breaks on node<10

Ref: https://github.com/npm/node-semver/commit/d61f828e64260a0a097f26210f5500#r36469180

**Expected behavior/code**
Just like the rest of the packages of babel - semver should be less than v7.1.1 possibly in 5 or 6 range

- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: Node 8.15.0
- OS: OSX 10.13.6
- Monorepo: Yes (Lerna workspace)
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**
Please don't depend on v7.1.1 of semver package

**Additional context/Screenshots**
```error semver@7.1.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.15.0" error Found incompatible module.```

Please let me know if I'm looking it in an incorrect way

**Comment by nicolo-ribaudo** [comment]
Fixed in 7.8.1
