### ISSUE TITLE
version 7.8.0 fail to install on node 6.1.0 

### ISSUE THREAD

**Issue by eilon-shai** [babel/babel#11000]
our build is failing since 12/1 on npm install, we are using jest@23.6.0 and it is using @babel/highlight@7.8.0
it fails both on jenkins (linux) and locally (macos).
we are using node 6.1.0 npm 3.8.6
error:
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:188:3)

expected behaviour
npm install should pass successfully as before

**Comment by nicolo-ribaudo** [comment]
Using node 6.1.0 and npm 3.8.6 I get a slightly different error:
```
➜ npm i -D jest@23.6.0
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Linux 5.3.0-26-generic
npm ERR! argv "/home/nicolo/n/bin/node" "/home/nicolo/n/bin/npm" "i" "-D" "jest@23.6.0"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/home/nicolo/n/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/home/nicolo/n/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/home/nicolo/n/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /home/nicolo/n/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /home/nicolo/n/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /home/nicolo/n/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/home/nicolo/n/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/home/nicolo/n/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/home/nicolo/n/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /home/nicolo/n/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nicolo/Documenti/dev/babel-bugs/issue-11000/npm-debug.log
```

(Nore the `This is an error with npm itself` message)

**Comment by nicolo-ribaudo** [comment]
Ok, this is the problem:
When `npm@3` downloads a `package.json` file from the registry, in some cases (I didn't understand exactly when) it adds a `type: ` property to mark it as having a different format.

We added `type: "commonjs"` to our package, thus `downloadedPackage.type` is always truthy and thus "normal" `package.json` files aren't handled correctly.

https://github.com/npm/npm/blob/db9cde008ce855bdac801bb6649cbfb5bb7911ac/lib/install/deps.js#L452-L458

**Comment by eilon-shai** [comment]
Thank you for the quick response

**Comment by nicolo-ribaudo** [comment]
I'll release it after that https://github.com/babel/babel/pull/11002 (a fix for a different regression) is merged.

**Comment by eilon-shai** [comment]
great, thanks
