### ISSUE TITLE
Internal proxy registry can't get latest version of code-frame.

### ISSUE THREAD

**Issue by Lighttree** [babel/babel#11008]
Hi guys, this is might be not related to `@babel/code-frame`. But this is only case I recently faced, so I think there is something different in how the package published.

We have private proxy repository which saves all installed packages from `NPM`.

With latest release of `@babel/code-frame` I started to get error during `npm update`:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/code-frame@7.8.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
I did quick check of our proxy and noticed that it actually has `7.8.0` as `latest`:
```json
{
    "users": {
        "fangbot": true
    },
    "readme": "# @babel/code-frame\n\n> Generate errors that contain a code frame that point to source locations.\n\nSee our website [@babel/code-frame](https://babeljs.io/docs/en/next/babel-code-frame.html) for more information.\n\n## Install\n\nUsing npm:\n\n```sh\nnpm install --save-dev @babel/code-frame\n```\n\nor using yarn:\n\n```sh\nyarn add @babel/code-frame --dev\n```\n",
    "homepage": "https://babeljs.io/",
    "dist-tags": {
        "latest": "7.8.0"
    },
   ...
}
```

The problem is that I also checked other `Babel` plugins and they "in sync" as expected and have `7.8.3` as latest.

So I'm not sure how to address this issue, maybe there is some specificity in how this package distributed or something wasn't done ?

**Comment by lukepolo** [comment]
Im having similar issues 

```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-plugin-utils@^7.8.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/plugin-proposal-nullish-coalescing-operator'
npm ERR! notarget 

```

**Comment by JLHwung** [comment]
Both `@babel/code-frame@7.8.3` and `@babel/plugin-proposal-nullish-coalescing-operator@7.8.3` have been published to `npm`
https://www.npmjs.com/package/@babel/code-frame
https://www.npmjs.com/package/@babel/plugin-proposal-nullish-coalescing-operator

Frankly speaking we could not control the cache policy of third party npm registry, but typically they will be resolved after couple of hours or days.

I have tagged this issue with `i: npm cache` and you can refer to the similar issues back when we published 7.7 or old versions.

I will close the issue now as only time can resolve this issue. Feel free to reopen it if you didn't see a new version after couple of days.

**Comment by nicolo-ribaudo** [comment]
Or better, please report the bug to npm. Every time we release a Babel version we are affected by this bug, and it's really annoying that they aren't fixing it because it only affects people for a few hours/days.

**Comment by Lighttree** [comment]
Thanks. Today `npm update / install` back to normal. Seems that it takes some time to get latest version information. I was thinking that `npm update / install` will force this, but seems that it is not.
