### ISSUE TITLE
syntax error running test with jest

### ISSUE THREAD

**Issue by josteinjhauge** [babel/babel#11010]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
A clear and concise description of the behavior.
test fails because of syntaxError 
 FAIL  __tests__/App.test.js
  ● Test suite failed to run

    SyntaxError: /Users/Jostein/Documents/jobb_Ovitas/projects/hunnor/node_modules/react-native/jest/mockComponent.js: Support for the experimental syntax 'classProperties' i
sn't currently enabled (20:24):

      18 | 
      19 |   const Component = class extends SuperClass {
    > 20 |     static displayName = 'Component';
         |                        ^
      21 | 
      22 |     render() {
      23 |       const name =

    Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

**Input Code**
- REPL or Repo link if applicable:
Jest configuration in package.json
```
 "jest": {
    "preset": "jest-expo",
    "verbose": true,
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|my-project|react-native-button)/)"
    ],
    "setupFiles": [
      "./setupTests.js"
    ],
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "html"
    ]
  },
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
expect jest to run test

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": ["module:metro-react-native-babel-preset", "babel-preset-expo"],
  "sourceMaps":true,
  "plugins": ["@babel/plugin-proposal-class-properties"]

}
```

**Environment**

```
System:
    OS: macOS 10.15.2
  Binaries:
    Node: 13.6.0 - ~/Documents/jobb_Ovitas/projects/hunnor/node_modules/.bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.8.3 => 7.8.3 
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3 
    @babel/polyfill: ^7.8.3 => 7.8.3 
    @babel/preset-env: ^7.8.3 => 7.8.3 
    babel-core: ^7.0.0-bridge.0 => 7.0.0-bridge.0 
    babel-eslint: ^10.0.2 => 10.0.3 
    babel-jest: ^23.6.0 => 23.6.0 
    eslint: ^6.0.1 => 6.8.0 
    jest: ^24.9.0 => 24.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
Please use `babel.config.json` instead of `.babelrc`. `.babelrc` is meant for file relative config, searching `.babelrc` will stop once a `package.json` is seen. So the `@babel/plugin-proposal-class-properties` is never applied to `node_modules/react-native/jest/mockComponent.js` because there is a `package.json` in `node_modules/react-native`.

This issue duplicates https://github.com/facebook/react-native/issues/21075.
