### ISSUE TITLE
Increased bundle size after upgrading past 7.6

### ISSUE THREAD

**Issue by Kadrian** [babel/babel#11013]
# v7 Regression

**Potential Commit/PR that introduced the regression**
https://github.com/babel/babel/pull/10161

**Description**
When we recently upgraded from `7.5` to `7.8` we experienced a bundle size increase from `~3,4 MB` to `3.5 MB` minified (`+90 KB` difference)

When we checked the bundle diff, we found that a function `_getRequireWildcardCache` is being re-defined for every module in our application and adds quite a bunch of code in total.

Searching for the function, we found that it's a new feature in babel `7.6`. Here's a blog post where @ifsnow , who built this feature explains it nicely: https://www.notion.so/Improving-Babel-Import-performance-makes-React-Native-faster-4ab20915a599481ab8fbb4993db38709 (thanks for the explanation by the way)

But what we find now is that besides the performance improvement we're hoping to get, we're seeing this regression in bundle size.

Is that to be expected? Is it possible to opt-out of this optimization?

**Comment by JLHwung** [comment]
> we found that a function _getRequireWildcardCache is being re-defined for every module in our application and adds quite a bunch of code in total.

Could you share how your app is bundled? If it is bundled by webpack, you should use [@babel/plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) to replace the injected helper codes
```js
var _interopRequireWildcard  = ...
```
by runtime imports
```js
var _interopRequireWildcard = require("@babel/runtime/helpers/interopRequireWildcard")
```

**Comment by nicolo-ribaudo** [comment]
If you are already using `@babel/plugin-transform-runtime`, this is probably what is happening: the helper has been updated, so Babel must inline it to ensure that you are using the new version (just in case your `@babel/runtime` is old). You can prevent this by passing a `"version": "^7.6.0"` (or what ever you are using) to tell "Hey Babel, I'm already using a version which includes the new feature. You don't need to inline it!".

**Comment by Kadrian** [comment]
Thank you for the hints! That already helped. So we're using the parcel bundler and we didn't use `@babel/plugin-transform-runtime` before. Now after adding the plugin, the bundle size decreased considerably, but checking the bundle: the `_getRequireWildcardCache` is still being redefined. We've also been using corejs-2. So after adding `@babel/runtime-corejs2` and including these parameters
```
{
        version: '^7.8.0',
        corejs: 2,
},
```
we're seeing a slight bundle size increase again, and the `_getRequireWildcardCache` still being redefined / or "inlined" as you call it

**Comment by nicolo-ribaudo** [comment]
If you are also using `preset-env`, I suggest using it's `useBuiltIns: usage` option rather than `plugin-transform-runtime`'s `corejs`. This is because `preset-env` only includes polyfills for your target environments, while `transform-runtime` polyfills everything.

**Comment by JLHwung** [comment]
> the _getRequireWildcardCache is still being redefined.

Could you see where these codes comes from? It is likely that they may come from the node_modules because some library use babel to transpile itself before publishing.

**Comment by Kadrian** [comment]
Hmm, that's a good idea, but the code seems to be injected between our own modules / files. It's around ~330 duplicate function definitions, which could about match our number of own files that make up our bundle. 

After monkey patching the `cache.get` method, we realized that the cache is never even called, probably because all of our modules are esmodules, and the cache is only accessed for non-es-modules.

**Comment by nicolo-ribaudo** [comment]
Could you share your full config, and the config of the tool you are using to run Babel (if any)?
