### ISSUE TITLE
[@babel/plugin-proposal-decorators] decorators for functions?

### ISSUE THREAD

**Issue by aprilmintacpineda** [babel/babel#11033]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**

Allow usage of decorators for functions not just classes.

**Describe the solution you'd like**

currently

```js
@myHOC
class MyClass {};
```

is allowed, but when you do

```js
@myHOC
function MyObject () {}
```

You get an error saying `Leading decorators must be attached to a class declaration`.

Useful links:

- https://github.com/wycats/javascript-decorators/issues/4
- https://github.com/finom/function-decorators-proposal 

**Describe alternatives you've considered**

N/A

**Teachability, Documentation, Adoption, Migration Strategy**

N/A

**Comment by nicolo-ribaudo** [comment]
It's not supported by the proposal: https://github.com/tc39/proposal-decorators/issues/40
