### ISSUE TITLE
`TypeError: (0 , _typeof3.default) is not a function` when executing test inside sub-package of monorepo

### ISSUE THREAD

**Issue by soryy708** [babel/babel#11036]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
Executing tests written in ES6+ inside sub-package of monorepo results in error: `TypeError: (0 , _typeof3.default) is not a function`

**Input Code**
Repro repo: https://github.com/soryy708/typeof3.default-repro

**Expected behavior/code**
Executed tests without errors

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
    presets: [
        ['@babel/preset-env', {
            modules: 'commonjs'
        }]
    ],
    plugins: [
        '@babel/transform-runtime'
    ],
    ignore: [
        'node_modules'
    ]
};
```

**Environment**

```
npx: installed 1 in 2.935s

  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
```
- Babel version(s): 7.8.3
- Node/npm version: Node11.13 npm6.12
- OS: Windows 10 x64 Home
- Monorepo: Yes
- How you are using Babel: register

**Possible Solution**
 ¯\\_(ツ)_/¯

**Additional context/Screenshots**
Perhaps related?

* https://swizec.com/blog/dont-worry-its-a-compiler-bug/swizec/6764
* https://github.com/babel/babel/issues/2954
* https://github.com/babel/babel/issues/3737
* https://github.com/babel/babel/issues/10996

**Comment by soryy708** [comment]
(opened an issue about it with mocha as well, since I'm unsure on whose end the bug is)

**Comment by nicolo-ribaudo** [comment]
I get this output with your repository:
```
➜ npm run test

> @ test /home/nicolo/Documenti/dev/babel-bugs/issue-11036
> mocha --require @babel/register "subrepo/{,!(node_modules)/**}/*.test.js" --exit



  foo
    ✓ bar


  1 passing (7ms)

```

**Comment by soryy708** [comment]
What OS are you using @nicolo-ribaudo ?

**Comment by soryy708** [comment]
I've just tried the same repro repo with the `/`s replaced with `\\`s as so:

    "test": "mocha --require @babel/register \"subrepo\\{,!(node_modules)\\**}\\*.test.js\" --exit"

There is no change to the output - I'm still reproducing.
