### ISSUE TITLE
Disable Babel in the @babel/runtime package.

### ISSUE THREAD

**Issue by aradzie** [babel/babel#11047]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**
The combination of Webpack with Babel may cause a problem such as #10996 if the `@babel/runtime` package is not explicitly excluded from Babel. This package contains helper functions which must not be transpiled by Babel. However, if care is not taken to exclude, Webpack will apply Babel to `@babel/runtime` resulting in a broken bundle. 

For example, the Babel runtime contains helper function `_typeof(obj)` which replaces the `typeof` operator to recognize `Symbol`s. This function contains few typeof operators internally, and when transpiled by Babel these operators are replaced with the same helper function. Whoops!

**Describe the solution you'd like**
If Babel contains any exclusion mechanism, it must be applied to package `@babel/runtime` to prevent the situations as the above.

**Comment by nicolo-ribaudo** [comment]
I think that there is still value in transpiling it sometimes, for example to include polyfills for the functions used by the helpers.
I think we could so something ad-hoc for the type of helper.

**Comment by aradzie** [comment]
Looking at the plugin [source code](https://github.com/babel/babel/blob/1815c349877acca1d3275ea72512ee7824db49e3/packages/babel-plugin-transform-typeof-symbol/src/index.js#L39-L51) it seems like it already tries to detect the situation when the typeof helper is applied to itself. Is this the case? If so, then that code probably is not working properly and needs to be fixed instead of this issue.

**Comment by wolf-benjamin** [comment]
To me it seems Webpack tries to take care of the case that another typeof function exists by reassigning it to

`var _typeof2 = __webpack_require__(/* @babel/runtimehelpers/typeof */ "./node_modules/@babel/runtime/helpers/typeof.js");` 

before using this new function to do the work. But somehow this doesn‘t get the job done: The error `_typeof2 is not a function` gets thrown.
Let me know if I‘m on the right track...

**Comment by aradzie** [comment]
@wolf-benjamin No, please take a look at the imported module id. It is the same as the module id in which the helper function is declared. The module imports from itself! And this is the result of application  of Babel to its own helper function.

PS I am preparing a small project to demonstrate the bug.

**Comment by wolf-benjamin** [comment]
Btw, adding ignore/exclude commands for `@babel/runtime` in `babel.config.js` seems not to work.

**Comment by aradzie** [comment]
And here is the repository I created to demonstrate this issue -- https://github.com/aradzie/babel-typeof-bug

**Comment by nicolo-ribaudo** [comment]
@aradzie Thanks! I didn't know that we already tried to prevent this.

**Comment by aradzie** [comment]
@nicolo-ribaudo Unfortunately this seems to be a recurring bug.
As @soryy708 mentioned in #10996, these issues may be related:
#2954
#3737
https://swizec.com/blog/dont-worry-its-a-compiler-bug/swizec/6764

**Comment by nicolo-ribaudo** [comment]
I'm preparing a PR
