### ISSUE TITLE
Update to Chokidar 3.x in babel cli

### ISSUE THREAD

**Issue by tracker1** [babel/babel#11056]
You're currently referencing an older version of Chokidar in babel cli, which in turn references an older version of fsevents, which seems to have had a point release that is causing issues in npm installs in windows...

Would you please consider updating to Chokidar 3.3.1 (current)?

This is somewhere between a bug and a feature, and pretty much removed the template as it doesn't quite fit this case specifically.

**Comment by nicolo-ribaudo** [comment]
It will be done in Babel 8: https://github.com/babel/babel/issues/9981#issuecomment-529808712
