### ISSUE TITLE
err.loc.column is zero-indexed while line is one-indexed

### ISSUE THREAD

**Issue by joliss** [babel/babel#1106]
Given an input file that consists only of the letter `%`, Babel throws

```
file.js: Unexpected token (1:0)

> 1 | %
    | ^
```

where `err.loc == { line: 1, column: 0 }`.

I'm surprised that `column` is 0, while `line` is 1. To me it looks like `column` is zero-indexed while `line` is one-indexed. Do you agree that both `line` and `column` should be 1? Or am I misunderstanding their meaning?

This seems like a very nitpicky issue, but we're in the process of tying down some of the error handling in Broccoli, so I'm genuinely interested in your opinion as a compiler author.

**Comment by eventualbuddha** [comment]
This seems to be the way acorn reports parse errors. My guess is that it inherits this behavior from esprima. I don't know why esprima chose to use 1-based lines and 0-based columns, but I personally find it quite annoying. I'd prefer them both to be 0-based and display as 1-based.

**Comment by sebmck** [comment]
Yeah this is ESTree behaviour.

> Each Position object consists of a linenumber (1-indexed) and a column number
(0-indexed):

https://github.com/estree/estree/blob/master/spec.md

On Saturday, 28 March 2015, Brian Donovan <notifications@github.com> wrote:

> This seems to be the way acorn reports parse errors. My guess is that it
> inherits this behavior from esprima. I don't know why esprima chose to use
> 1-based lines and 0-based columns, but I personally find it quite annoying.
> I'd prefer them both to be 0-based and display as 1-based.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1106#issuecomment-87115906>.
>


-- 
Sebastian McKenzie

**Comment by joliss** [comment]
Cool, thanks for elaborating!
