### ISSUE TITLE
Installing @babel/preset-env is failing

### ISSUE THREAD

**Issue by mattgrande** [babel/babel#11067]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
I'm attempting to install `@babel/preset-env`, and it is failing with the following message:

```
λ npm install @babel/preset-env
npm ERR! Unexpected end of JSON input while parsing near '...JcnRiBCRA9TVsSAnZWagA'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mgran\AppData\Roaming\npm-cache\_logs\2020-01-29T21_22_48_630Z-debug.log
```

You can see the log file here: https://gist.github.com/mattgrande/3ab7e88213ecb6089babf5ccafd47bb9

**Input Code**
`npm install @babel/preset-env`

**Expected behavior/code**
A successful installation

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
N/A

**Environment**

```
  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    babel-loader: ^8.0.6 => 8.0.6
    webpack: ^4.41.5 => 4.41.5
```

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
`npm` has downloaded corrupted data. Try cleaning the cache and re-installing it.

**Comment by mattgrande** [comment]
```
λ npm cache clear --force
npm WARN using --force I sure hope you know what you are doing.

λ npm install @babel/preset-env
npm WARN price-is-rite@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @babel/preset-env@7.8.3
added 91 packages from 16 contributors and audited 10651 packages in 9.316s
found 0 vulnerabilities
```

That did it! Thank you!

**Comment by existentialism** [comment]
@mattgrande closing for now, but let us know if you run into any other problems!
