### ISSUE TITLE
wrong js code when using ts constructor assignment

### ISSUE THREAD

**Issue by wan2land** [babel/babel#11061]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
If a module imported from TypeScript has the same name as a constructor parameter, a bug occurs.

**Input Code**
- REPL or Repo link if applicable: 
  - [babeljs repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbziApgZzQQwObAHbZwC-cAZlBCHAOSnBQoBGmaKAtJgCYj7UBQfFAA9IsOAGMANizRwAypRQwAFvkII-cCRDxoYUAK7iY0ABSa4ASDAHGk4OOTosuAgC4nGHGoB0AWWdvAgsASkQLIj5IoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript%2Cenv&prettier=false&targets=Node-8.9&version=7.8.3&externalPlugins=)
  - [typescript repl](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=3&pc=1#code/JYWwDg9gTgLgBAbziApgZzQQwObAHbZwC+cAZlBCHAOSnBQoBGmaKAtJgCYj7UBQfFAA9IsOAGMANizRwAypRQwAFvkII+cCRDxoYUAK7iY0ABSa4ASDAHGk4OOTosuAgC4nGHGoB0AWWdvAgsASkQLIj5IoA)

```ts
import { messaging } from 'firebase-admin'

export class Something {
  constructor(
  	public messaging: messaging.Messaging
  ) {
  }
}
```

**Expected behavior/code**

Expected,

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Something = void 0;

class Something {
  constructor(messaging) {
    this.messaging = messaging;
  }

}

exports.Something = Something;
```

But actual,

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Something = void 0;

var _firebaseAdmin = require("firebase-admin");

class Something {
  constructor(_firebaseAdmin.messaging) { // Whoops!
    this.messaging = messaging;
  }

}

exports.Something = Something;
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
  "presets": [
    ["@babel/env", {
      "targets": "maintained node versions",
      "useBuiltIns": "usage",
      "corejs": 3
    }],
    "@babel/typescript"
  ]
}
```

**Environment**

```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  npmPackages:
    @babel/cli: ^7.8.3 => 7.8.3
    @babel/core: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-decorators: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-object-rest-spread: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-optional-chaining: ^7.8.3 => 7.8.3
    @babel/preset-env: ^7.8.3 => 7.8.3
    @babel/preset-typescript: ^7.8.3 => 7.8.3
    eslint: ^6.2.2 => 6.2.2
    jest: ^24.9.0 => 24.9.0
```

- Babel version(s): 7.8.3
- Node/npm version: node 10.16.3 / npm 6.9.0
- OS: macOS 10.15.2
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
.

**Comment by sidntrivedi012** [comment]
I would like to help out to fix this. Please assign it to me. Thanks :)

**Comment by dangreaves** [comment]
I experienced a very similar issue to this when importing a type with the same name as the constructor argument. However, in my case, the output was slightly different to the above, resulting in a module import.

## Source

```typescript
import { S3EventRecord } from "aws-lambda";

export class SapFileCreated {
  constructor(protected S3EventRecord: S3EventRecord) {}
}
```

## Expected output

```js
class SapFileCreated {
  constructor(S3EventRecord) {
    this.S3EventRecord = S3EventRecord;
  }
}
```

## Actual output

```js
var _awsLambda = __webpack_require__(246);

class SapFileCreated {
  constructor(S3EventRecord) { // S3EventRecord is ignored here
    this.S3EventRecord = _awsLambda.S3EventRecord;
  }
}
```

## Versions

- @babel/core 7.9.0
- @babel/preset-env 7.9.0
- @babel/preset-typescript 7.9.0

**Comment by sidntrivedi012** [comment]
Sorry for delaying the work on this issue. Will start working on it from today onwards.

**Comment by codeflo** [comment]
I just ran into this. My case matches @dangreaves 's exactly: the imported value is assigned to the property instead of the constructor parameter. This leads to a "broken" object, which in my case caused problems only much further down the road. It took me way longer to trace this down to a transpilation error than I want to admit right now.

@nicolo-ribaudo Assuming @sidntrivedi012 isn't actively working on this at the moment, is there chance to re-triage/re-assign this?

**Comment by JLHwung** [comment]
I can not reproduce this error on v7.12.3 REPL:

https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbziApgZzQQwObAHbZwC-cAZlBCHAOSnBQoBGmaKAtJgCYj7UBQfFAA9IsOAGMANizRwAypRQwAFvkII-cCRDxoYUAK7iY0ABSa4ASDAHGk4OOTosuAgC4nGHGoB0AWWdvAgsASkQLIj5IoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=Node-8.9&version=7.12.3&externalPlugins=

However if `transform-class` is applied, the [transformed](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbziApgZzQQwObAHbZwC-cAZlBCHAOSnBQoBGmaKAtJgCYj7UBQfFAA9IsOAGMANizRwAypRQwAFvkII-cCRDxoYUAK7iY0ABSa4ASDAHGk4OOTosuAgC4nGHGoB0AWWdvAgsASkQLIj5IoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=) result still refers to `_firebaseAdmin.messaging`.
