### ISSUE TITLE
Sha issue with @babel/compat-data version 7.8.4

### ISSUE THREAD

**Issue by dforbes49** [babel/babel#11076]

**Comment by dforbes49** [comment]
Apologies hit enter accidentally before I got to type my message. Issue with @babel/compat-data version 7.8.4
error sha512-lHLhlsvFjJAqNU71b7k6Vv9ewjmTXKvqaMv7n0G1etdCabWLw3nEYE8mmgoVOxMIFE07xOvo7H7XBASirX6Rrg== integrity checksum failed when using sha512: wanted sha512-lHLhlsvFjJAqNU71b7k6Vv9ewjmTXKvqaMv7n0G1etdCabWLw3nEYE8mmgoVOxMIFE07xOvo7H7XBASirX6Rrg== but got sha512-cHaa41T/RoakGXgjOAzqhSCAWdSp+2aUTLf57+NHflbcRmWmY8D5AJLQzyz/5uAecvTG56GwaP2beeXMKAIDcA==. 

Not happending on 7.8.1

**Comment by nicolo-ribaudo** [comment]
Try clearing you npm cache and reinstalling it.

**Comment by HunterJS-bit** [comment]
Not working event after clearing npm cache

**Comment by nicolo-ribaudo** [comment]
This should be fixed in `@babel/compat-data@7.8.5`.
