### ISSUE TITLE
[plugin-proposal-optional-chaining] Loose mode produces unoptimized code for class methods

### ISSUE THREAD

**Issue by Lodin** [babel/babel#11084]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
The `loose` mode of `optional-chaining` plugin compiles class methods in non-optimized way repeating the call to the method instead of remembering its result.

It does not happen for function call though.

**Input Code**
- REPL or Repo link if applicable: [Runkit](https://runkit.com/lodin/optional-chaining-repeating-call-to-object-method).

```js
a.get(b)?.();
```
compiles to:
```js
a.get(b) == null ? void 0 : a.get(b)();
```

**Expected behavior/code**
The result of method call should be memoized as it happens in the strict mode.

```js
var a$get;

(a$get = a.get(b)) == null ? void 0 : a$get();
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
    plugins: [[require('@babel/plugin-proposal-optional-chaining'), {loose: true}]]
}
```

**Environment**

- Babel version(s): 7.8.4
- Node/npm version: v13.5.0/6.13.4
- OS: Windows 10
- Monorepo: Lerna
- How you are using Babel: cli/programmatically

**Comment by nicolo-ribaudo** [comment]
Note that this bug only affects optional calls. Optional member expressions are already memoized in loose mode.

**Comment by oliverdunk** [comment]
I'd love to work on this one :)

**Comment by jridgewell** [comment]
Are you still working on this @oliverdunk?

**Comment by oliverdunk** [comment]
> Are you still working on this @oliverdunk?

I am, sorry for the delay. I did a first draft and sent it to Nico, but he requested some changes. Will hopefully put up an MR this weekend.

**Comment by jridgewell** [comment]
All good. Happy to review an unfinished PR, please open one when you can.
