### ISSUE TITLE
Transform regex feature from normalize-url package

### ISSUE THREAD

**Issue by TrySound** [babel/babel#11086]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**
I use normalize-url package in browser code. Since v5.0 code contains regex syntax not supported by safari 13.0.3.
```
/(?<!https?:)\/{2,}/g
```
Here's the error I get
```
SyntaxError: Invalid regular expression: invalid group specifier name
```
For context
https://github.com/sindresorhus/normalize-url/commit/76172da85d377d5221413117e5398d3af37db60f#diff-168726dbe96b3ce427e7fedce31bb0bcR120

**Describe the solution you'd like**
A babel plugin as part of babel-preset-env if this is part of js spec. I'm not very familiar with this language feature.

**Comment by nicolo-ribaudo** [comment]
Lookbehind assertions cannot be transpiled :disappointed:

**Comment by TrySound** [comment]
This is sad. Thanks for the answer!

**Comment by oyeanuj** [comment]
@nicolo-ribaudo @TrySound I'm facing the same issue - curious, did you find a workaround?

**Comment by nicolo-ribaudo** [comment]
Unfortunately the only "workaround" is to avoid using them.
