### ISSUE TITLE
Cannot use @babel/preset-env with @babel/core after code has ran through webpack

### ISSUE THREAD

**Issue by 1nfility** [babel/babel#11085]
## Bug Report

I'm trying to transform code into es5 using nodejs, but i get an error if the code trying to transform a string of code, has been through webpack first. If i create a ``test.js`` file, and do the exact same I do not get an error.

This is the error I get: https://i.imgur.com/z6DeJGQ.png

**Webpack Rule**
```js
{
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'babel-loader',
              query: {
                presets: ['@babel/preset-env', '@babel/react']
              }
            }
          ]
        }
```

**Transform to es5 code**
```js
import fs from 'fs';
import * as babel from '@babel/core';

console.log(babel.transformSync(`code string...`, {presets: ['@babel/preset-env']}));
```

**Environment**
```
System:
    OS: macOS 10.15.3
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.8.4 => 7.8.4 
    @babel/preset-env: ^7.8.4 => 7.8.4 
    @babel/preset-react: ^7.8.3 => 7.8.3 
    babel-eslint: ^10.0.3 => 10.0.3 
    babel-loader: ^8.0.6 => 8.0.6 
    eslint: ^6.8.0 => 6.8.0 
    webpack: ^4.41.4 => 4.41.5
```

**Comment by nicolo-ribaudo** [comment]
Does this work?

```js
import fs from 'fs';
import * as babel from '@babel/core';

const env = eval("require('@babel/preset-env')");

console.log(babel.transformSync(`code string...`, {presets: [env]}));
```

If it doesn't, then it's now a Babel bug but, for some reason, the `@babel/preset-env` package is not available.

**Comment by 1nfility** [comment]
@nicolo-ribaudo That worked, thank you so much! I tried to fix this bug for so many hours.

**Comment by nicolo-ribaudo** [comment]
Ok, if it works you can also remove eval.
The problem was that webpack didn't know that it had to bundle preset-env.

**Comment by 1nfility** [comment]
Removing eval will cause it to not work.

**Comment by nicolo-ribaudo** [comment]
Oh that's super strange :thinking:
Did you kept the `require()` call after removing eval?

Anyway, this seems to be a problem with your bundler and not with Babel.

**Comment by 1nfility** [comment]
Yes, I kept the require call, seems like webpack messes the require call up, but putting it into a string and an eval call causes webpack to not *transform* the require.

**Comment by nicolo-ribaudo** [comment]
Oh then it won't work in a browser. Btw, why are you bundling Babel? Usually you only want to bundle the code generated by Babel, not Babel itself.

**Comment by 1nfility** [comment]
It's only for a script in development on the main process.
