### ISSUE TITLE
types.isReferenced incorrectly returns true for object/class method param identifiers

### ISSUE THREAD

**Issue by brokensandals** [babel/babel#11087]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**

For code like this:

```js
class Foo {
  bar(baz) {}
}
```

calling `isReferenced` for the `baz` node returns `true`.

**Input Code**

Here's a (failing) test case to demonstrate:

```js
test('demonstrate isReferenced issue', () => {
  const results = {};
  function plugin() {
    return {
      visitor: {
        Identifier(path) {
          results[path.node.name] = path.isReferenced();
        },
      },
    };
  }

  const code = 'class Foo { bar(baz) {} }';
  babel.transformSync(code, { plugins: [plugin], configFile: false });
  expect(results.baz).toBe(false);
});
```

**Expected behavior/code**

`isReferenced` for `baz` should be `false` because it is simply declaring a param for the method.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

The test case above uses `configFile: false` when calling into babel; I'm running the test case itself with this config:

- Filename: `babel.config.js`

```js
module.exports = {
  presets: ['@babel/preset-env'],
};
```

**Environment**

- Babel version(s): 7.8.3
- Node/npm version: node 12.13.1, npm 6.13.6
- OS: OSX 10.14.6
- Monorepo: Lerna
- How you are using Babel: writing a babel plugin

**Possible Solution**

See this commit, let me know if I should submit a PR: https://github.com/brokensandals/babel/commit/63767c5841ff48c1a13f9af43c4bcf4a61ccf5b3

**Additional context/Screenshots**

I'm writing a plugin that tries to transform all expressions in the source code. It needs to distinguish between identifiers that will be evaluated as expressions, and those which simply name functions/params/etc. My understanding is that `path.isReferenced` returning `true` should indicate that the Identifier node represents retrieval of a value by name, so I've been using that. It seems to work right in most cases, but not in the case described here.

**Comment by nicolo-ribaudo** [comment]
Good catch!
Regarding your commit, please don't use `.includes` because we still support Node 6.
