### ISSUE TITLE
Upgrade core.js

### ISSUE THREAD

**Issue by eknkc** [babel/babel#1109]
Could we have the bundled core-js upgraded to `7.x` versions if there are no dependencies on the older version?

**Comment by zloirock** [comment]
Not sure that this is actual. Versions `0.7.x` was planned as an intermediate in the transition to the commonjs modular structure, but also was fixed some bugs. I've had problems with free time to finish transition - state exams. In near days I'll publish `0.8.0`.

**Comment by sebmck** [comment]
@eknkc What do you mean by bundled core-js version? Is there any particular reason you need the latest minor?

**Comment by eknkc** [comment]
@sebmck Just created an issue on core-js referencing this. My initial thought was that babel had a significantly outdated version of core-js while creating this issue, but it seems that it's not the case.

**Comment by AgentME** [comment]
Related: #1086 :P
