### ISSUE TITLE
Transpile dependencies

### ISSUE THREAD

**Issue by epoberezkin** [babel/babel#1110]
When dependency is "npm install"ed, it is not transpiled.
When dependency is "npm link"ed, it is transpiled.

I agree that using babel in libraries is not a good idea, but when the package is the part of the project it may be a good idea to have babel available without the need to link that dependency.

Browserify, for example, has an option that can be included in package.json to instruct it to run transforms in that package:

```
"browserify": {
  "transform": [ "babelify", "brfs" ]
}
```

Is there maybe a similar option for require hook?
If not, would you accept a PR with such an option?

**Comment by sebmck** [comment]
> Is there maybe a similar option for require hook?

Yes. Please see the [docs](http://babeljs.io/docs/usage/require/#usage):

> **NOTE:** By default all requires to `node_modules` will be ignored. You can override this by passing an ignore regex via:
> 
> require("babel/register")({
>   // This will override `node_modules` ignoring - you can alternatively pass
>   // a regex
>  ignore: false
> });

Also as per the README:

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) before creating an issue.

Thanks!

**Comment by epoberezkin** [comment]
Thanks!
