### ISSUE TITLE
Unicode RegExp escape sequences handled backwards (lone braces and brackets)

### ISSUE THREAD

**Issue by pygy** [babel/babel#11138]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**

The way lone braces and brackets are handled when the `u` flag is set isn't spec conformant. Babel accepts invalid regexps, and emits useless escape sequences.

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAlmAbgQwDZwCYwLwwNoD0AvgQK4A0MBAumdUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.8.4&externalPlugins)

```js
const invalid = [/}/u, /]/u]

```

**Expected behavior/code**

Both of these RegExps are syntax errors when the Unicode flag is set, those brackets must be escaped according the the spec ([see them fail in browers live here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5iAJwCeAAmAAdNNOkwAbhigAKOSAD0rHQFdtASgWtp1DMWqFpGmMdkKlQuLVj4Y48bXH3TaKwKChIy8orKapraOgC6hiZmFlY2dg5OEa7uMJ7evv5mCpQgcDCw1MQQ9Ag8AIy1iAAMbBwgmDh4+NRwAjT0jMw8bLGsQA)).

Also, the resulting RegExp doesn't have the Unicode flag set, so escaping these characters is not needed in the result, but Babel escapes them anyway. `/\}/u` could be compiled to `/}/` without harm.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Default config using the online REPL. I don't have Babel installed yet.

**Environment**

```

```
- Babel version(s): v7.8.4
- Node/npm version: online REPL
- OS: any Mac Browser

**Possible Solution**

Fix the parser :-)

**Comment by nicolo-ribaudo** [comment]
Could you reopen this issue in https://github.com/mathiasbynens/regexpu-core? It's what we use to transform regexps.

**Comment by pygy** [comment]
Not sure it is the right place to report it...

Babel [correctly throws on `/\-/u`](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAlmAbgQwDZwCYwLwwPQA6AtHgK4DcAUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ces2015%2Cstage-2%2Cstage-3%2Cenv&prettier=true&targets=&version=7.8.4&externalPlugins=%40babel%2Fplugin-proposal-unicode-property-regex%407.8.3), but it accepts `/}/u`.

`regexpu-core` accepts all of these... 

```
> rewritePattern('}', 'u')
'\\}'
> rewritePattern('-', 'u')
'\\x2D'
```

Babel should catch the braces problem where it catches the escaped dash.

@mathiasbynens any thoughts on this?

**Comment by pygy** [comment]
This may cause a downstream RegExpocalypse...

**Comment by pygy** [comment]
@nicolo-ribaudo if this is merged as is upstream, it will break code that relises on Babel, and publishing a codemod to fix this automatically will be hard (since the fix will be picked up by `regexpu-core` and `@babel/helper-create-regexp-features-plugin` through semver, preventing the parsing of the problematic source files). 

I suppose we need to create and publish a codemod first, and wait for the ecosystem to be in good shape.

... unless you have a way to override `@babel/helper-create-regexp-features-plugin` on a per install basis, in which case we can create the codemod based on the previous version of `regjsparser`...
