### ISSUE TITLE
_objectWithoutProperties doesn't take default values into account for deeply nested object destructuring with specific preset-env

### ISSUE THREAD

**Issue by przemyslawzalewski** [babel/babel#11149]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
`_objectWithoutProperties` is being called directly on deeply nested destructured property chains without taking default values into account. This causes `TypeError: Cannot read property 'X' of undefined` errors being thrown in a code that uses fallback values to guards against missing nested properties.
The strange thing is that issue only happens for a specific environment set - `Chrome >= 61, Firefox >= 60, Opera >= 48, Safari >= 11, Edge >= 16, ChromeAndroid >= 77, iOS >= 11`.
I have thought that it may be some optimization/minimization/mangling issue, however, it seems that the root cause is somewhere within the babel-preset-env. Default parameter assignments seem to be dropped when object-destructuring, but not the object rest operator, is supported on the selected platform/env.

**Input Code**
- The full case for reproduction [is available on the REPL](https://babeljs.io/repl#?browsers=Chrome%20%3E%3D%2061%2C%20Firefox%20%3E%3D%2060%2C%20Opera%20%3E%3D%2048%2C%20Safari%20%3E%3D%2011%2C%20Edge%20%3E%3D%2016%2C%20ChromeAndroid%20%3E%3D%2077%2C%20iOS%20%3E%3D%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC5WgbwFDWgcwKYBdO5ywCcAKASmTXWmAHsA7CPVa6gMwEsimAZLANywgA8mwByWJh3oYAXJVasIWOvQAmfQSPGSc0uQsVLaAWywAFIrQAOxHAE8ANFSPoAdB6K6XigL7QAXmRfH3R_IKQQ1nDoHAALDggAbhQfLxwAVyJ6aC8mFLCUXxSUVSZoaSYwemAsQPR6LAB3OAQIchSy2hAsNxBaDBJKnGrat2wcQiIyErK8NnqSFmhObhxNIVEJKRl5ZfRlVQ0BTZ0dg33qCFMLK1siB2cjDzc8nB8YyKpPkN8KAIAfLldLMGNcen0BiQ2Es_jMgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.8.4&externalPlugins=). Please disable the ENV PRESET > Enabled checkbox to see the code running properly when the legacy transforms apply and thus default values are applied.

```js
class Class {
  get getter() {
    const {
      firstLevelOfNesting: {
        secondLevelOfNesting: {
          someProperty,
          ...rest
        } = {}
      } = {}
    } = this;

    return rest;
  }
};
```

This code generates the following output code when preset-env is not used:

```js
var _this$firstLevelOfNes = this.firstLevelOfNesting;
      _this$firstLevelOfNes = _this$firstLevelOfNes === void 0 ? {} : _this$firstLevelOfNes;
      var _this$firstLevelOfNes2 = _this$firstLevelOfNes.secondLevelOfNesting;
      _this$firstLevelOfNes2 = _this$firstLevelOfNes2 === void 0 ? {} : _this$firstLevelOfNes2;

      var someProperty = _this$firstLevelOfNes2.someProperty,
          rest = _objectWithoutProperties(_this$firstLevelOfNes2, ["someProperty"]);
```

The `=== void 0 ? {} :` expressions apply the fallback values before following code extracts nested properties. However, this is not the case when `preset-env` is applied with the mentioned browser list:

```js
const {
      firstLevelOfNesting: {
        secondLevelOfNesting: {
          someProperty
        } = {}
      } = {}
    } = this,
          rest = _objectWithoutProperties(this.firstLevelOfNesting.secondLevelOfNesting, ["someProperty"]);
```

As you can see the destructured property chain is evaluated in-place without taking default values into account `this.firstLevelOfNesting.secondLevelOfNesting` - this causes the cannot read property X of undefined errors being thrown.
The issue also affects argument destructuring of plain functions. A single level of nesting is not affected due to `_objectWithoutProperties` handling `undefined`/`null` case on its own.

**Expected behavior/code**
The code with the specific browser list applied should behave like the code without preset-env applied and match native implementation (the code below, after pasting into Chrome DevTools, should not throw):

```javascript
class Class {
  get getter() {
    const {
      firstLevelOfNesting: {
        secondLevelOfNesting: {
          someProperty,
          ...rest
        } = {}
      } = {}
    } = this;

    return rest;
  }
};

const instance =  new Class();
console.log(instance.getter);

const f = ({
  firstLevelOfNesting: {
    secondLevelOfNesting: {
      someProperty,
      ...rest
    } = {}
  } = {}
}) => rest;

console.log(f({}));
``` 

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- `preset-env` with the following browser list `Chrome >= 61, Firefox >= 60, Opera >= 48, Safari >= 11, Edge >= 16, ChromeAndroid >= 77, iOS >= 11`:

```javascript
[
  'Chrome >= 61',
  'Firefox >= 60',
  'Opera >= 48',
  'Safari >= 11',
  'Edge >= 16',
  'ChromeAndroid >= 77',
  'iOS >= 11'
]
```

**Environment**
- Babel version(s): [7.8.4]
- Node/npm version: [Node 12.14.0/npm 6.13.4]
- OS: [Windows 10]
- Monorepo: [no]
- How you are using Babel: [`loader`, `REPL`]

**Comment by JLHwung** [comment]
Closing this as it duplicates #10735, which is fixed in #10738 (unmerged yet 😅).

@przemyslawzalewski It is a very detailed report, thank you!
