### ISSUE TITLE
Cannot access private member through public method via Proxy

### ISSUE THREAD

**Issue by sionzeecz** [babel/babel#11144]
## Bug Report

**Current Behavior**
Throws an error **attempted to get private field on non-instance**

**Input Code**
- Link to [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoa0DEED2AtvAGICW8IAJtALzQAMA3JtCwObwrECSAogDIARABQBKNCywAnTgFcpAO2hIAFqQgA6XIRLkqLAL7oj6YHgXJopC0jALg8WtAXwA7nERIxzMzegAHKTwADwBPJxd3AAUgsOFrZDsHABoJLA4vWykM1P9UmQdSADd4KXEMLGk5RWgAJXgAMxB4YCQNDOEsnID8lvhi0vFmLCMDUWZ0QJDQjR4BQSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.8.4&externalPlugins=)
```js
class Test {
  #someField = 0;
  
  get FIELD() {
    return this.#someField
  }
}

const instance = new Test();
const proxy = new Proxy(instance, {
  get(target, p, receiver) {
    return Reflect.get(target, p, receiver) ;
  }
});

console.log(proxy.FIELD)
```

**Expected behavior/code**
I expect to normally access the public method through proxy.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    "@babel/env",
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties"
  ]
}
```

**Environment**

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.2 - /usr/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4
    @babel/core: ^7.8.4 => 7.8.4
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-transform-runtime: ^7.8.3 => 7.8.3
    @babel/preset-env: ^7.8.4 => 7.8.4
    @babel/preset-typescript: ^7.8.3 => 7.8.3
    @babel/runtime: ^7.8.4 => 7.8.4
    babel-loader: ^8.0.6 => 8.0.6
    webpack: ^4.41.6 => 4.41.6

```
- How you are using Babel: babel-loader through webpack

// Edit
When I access the method directly from proxy like:
```js
const instance = new Test();
const proxy = new Proxy(instance, {
  get(target, p, receiver) {
    if(p === "FIELD") return target.FIELD
    return undefined;
  }
});

console.log(proxy.FIELD)
```
Then it works. So workaround is to redefine all public methods in proxy and call them directly. (as temp solution OK but it is pretty ugly)

// Edit 2
The same issue has also typescript-compiler. Am I doing something wrong?

// Edit 3
Seems this issue is related to `Reflect.get`
I managed to get it work by modifying the code above to:
```js
class Test {
  #someField = 0;
  
  get FIELD() {
    return this.#someField
  }
}

const instance = new Test();
const proxy = new Proxy(instance, {
  get(target, p, receiver) {
    if(p in target) return target[p]
    return Reflect.get(target, p, receiver) ;
  }
});

console.log(proxy.FIELD)
```

**Comment by jridgewell** [comment]
This behavior is correct per the spec. You're "getting" a prop from the proxy, which is invoking the getter with `proxy` as the `this` context (via the 3rd argument to `Reflect.get`, `receiver === proxy`). You cannot access private fields through proxies, only on the target.
