### ISSUE TITLE
CallExpression expected node to be of a type [...]

### ISSUE THREAD

**Issue by jeffersonlicet** [babel/babel#11156]
Hello, I'm trying to migrate a babel 6 plugin to the new version, in the old version I was able to create a CallExpression using as a parameter an ObjectPattern.

What I'm trying to do is something like `funcFoo({date, time});` where `{ a: 1, b: 2 }` is the ObjectPattern
But Im getting this error:

> TypeError: @babel/template placeholder "input": Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "ObjectPattern"

The original code is:

```
type TypeDateTime = {
    date: string,
    time: string
};

const demo = ({date, time}: TypeDateTime) => {
    return {};
};

export default demo;
```

The lib I'm migrating: 
https://github.com/jeffersonlicet/babel-plugin-typecheck

Thanks.

**Comment by nicolo-ribaudo** [comment]
ObjectPattern is used for destructuring (`ObjectPattern = ...`). You want an ObjectExpression, which is an object literal.

**Comment by jeffersonlicet** [comment]
> ObjectPattern is used for destructuring (`ObjectPattern = ...`). You want an ObjectExpression, which is an object literal.

Perfect. I solved it using: `t.objectExpression(input.properties)`
