### ISSUE TITLE
Float32Array support for array spread

### ISSUE THREAD

**Issue by titivermeesch** [babel/babel#11162]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**
When we spread a Float32Array, we get the next error : 
`Invalid attempt to spread non-iterable instance`
This happens on Chrome Mobile but not on Chrome PC

**Input Code**

```js
const arr = new Float32Array(0)
const newArray = [...arr]
```

**Expected behavior/code**
This should just spread like a normal array.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    [
      "babel-plugin-root-import",
      {
        "rootPathPrefix": "~"
        // "rootPathSuffix": "src"
      }
    ]
  ],

  "env": {
    "test": {
      "plugins": ["@babel/plugin-transform-runtime", "@babel/plugin-proposal-class-properties"]
    }
  }
}
```

**Environment**
```
 System:
    OS: macOS 10.15.3
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
```

**Possible Solution**
in `_arrayWithoutHoles` we could check for Float32Array instead of just doing `Array.isArray()`.

**Comment by JLHwung** [comment]
@titivermeesch You can view the transformed output from [Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhgJwTAvDMBTA7jAYgGxDigGYAmAQSTgE8AKABgEoAoUSWTLKhW1GANoA6EYgQBdIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=true&targets=Node-13&version=7.8.4&externalPlugins=). 

If `_arrayWithoutHoles` is `false`, it will pass to `_iterableToArray`

```js
function _iterableToArray(iter) {
  if (
    Symbol.iterator in Object(iter) ||
    Object.prototype.toString.call(iter) === "[object Arguments]"
  )
    return Array.from(iter);
}
```
And `Symbol.iterator in Object(new Float32Array)` must be `true` so it will return `Array.from(arr)`.

> This happens on Chrome Mobile but not on Chrome PC

Can you offer the version and the platform (OS) of `Chrome Mobile`? It seems to me that on that browser `Symbol.iterator in Object(new Float32Array)` does not return true.

**Comment by titivermeesch** [comment]
@JLHwung I tried that code on Babel REPL before but I couldn't reproduce the issue, even when I specified the browser version.

I'm running on an Android emulator (along with Cordova) running on `Chrome Mobile 80.0`.
It's not something specific with Cordova though because running the app without it just gives me the same error.

I've indeed tested `Symbol.iterator in Object(new Float32Array)` and it gives me a different result.

**Comment by JLHwung** [comment]
@titivermeesch Can you check if `Symbol.iterator in Object(new Float32Array)` returns `true` on an Android device with `Chrome Mobile 80.0`? According to [compat-table](https://kangax.github.io/compat-table/es6/): (Search `%TypedArray%.prototype[Symbol.iterator]`), it is supported on Chrome 80.

If it turns out Chrome 80 on Android does not support iterator symbol, this means the compat-data babel uses is incorrect, please submit an issue on compat-table. Otherwise the behaviour difference may only come from the emulator and we couldn't do much about that.

**Comment by titivermeesch** [comment]
I've just tested it with BrowserStack and everything works fine there, so it seems like the emulator is behaving weirdly in this case and you can't indeed do anything about it.
Thanks for your help.
