### ISSUE TITLE
Deep optional chaining breaks in function argument destructuring

### ISSUE THREAD

**Issue by maxdavidson** [babel/babel#11166]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

Optional chaining breaks when destructuring deep chains inside the function arguments, due to incorrect hoisting of temporary variables.

[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FAMwrgdgxgLglgewgAgBYFMA2mEAoDewyyAhgDRHIBGyAvKQPwB0VzUFAvgJTKHEBO6GGH4oADAG5gHYMAzY8-UgC5eHAAXcpQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cenv&prettier=true&targets=Node-13&version=7.8.4&externalPlugins=)

**Input Code**

```js
function hello({
  a,
  b = a?.b?.c,
}) {
  return 0;
}
```

**Output Code**
```js
"use strict";

function hello({
  a,
  b = a === null || a === void 0 ? void 0 : (_a$b = a.b) === null || _a$b === void 0 ? void 0 : _a$b.c
}) {
  var _a$b;

  return 0;
}
```

**Expected behavior/code**

The code should assign a value to `b`, and not fail with `_a$b is not defined`.

**Babel Configuration**

```js
// .babelrc
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": { "node": "current" }
      }
    ]
  ]
}

```

**Environment**

- Babel version(s): 7.8.4
- Node/npm version: 13.8.0/6.13.7

**Possible Solution**

Either move the hoisted variable to the module scope, or use a temporary variable for the argument and perform the destructuring inside the function body.

**Comment by jridgewell** [comment]
We keep having bugs related to injecting temp variables in a param scope.

**Comment by nicolo-ribaudo** [comment]
Maybe in Babel 8 we could add a "transparent" scope (transparent similar to how we handle block scopes) to represent params scope.

**Comment by Zzzen** [comment]
😕  What is the expected output though?

**Comment by nicolo-ribaudo** [comment]
Probably something like this:
```js
function hello({
  a,
  b = (() => {
    var _a$b;
    return a === null || a === void 0 ? void 0 : (_a$b = a.b) === null || _a$b === void 0 ? void 0 : _a$b.c;
  })()
}) {
  return 0;
}
```

**Comment by LarsDenBakker** [comment]
Just ran into this too :( Is it possible to still fix this within babel v7?

**Comment by nicolo-ribaudo** [comment]
Yes, definetly. The implementation won't be "nice", but it can be fixed.
