### ISSUE TITLE
babel-node doesn't execute multiple files

### ISSUE THREAD

**Issue by MoOx** [babel/babel#1116]
I just upgraded a project that where still using 6to5.

`6to5-node test/*.js` was executing all files (since zsh convert to `6to5-node test/a.js test/b.js` in my case).
But now with `babel-node`, only the first is executed.
Is this a bug or on purpose ?

Is this related to the [2.0.0](https://github.com/babel/babel/blob/master/CHANGELOG-6to5.md#200) change ` 6to5-node now behaves the same as node.`?

**Comment by sebmck** [comment]
It's on purpose and yes the 2.0.0 change is the case. It only makes sense for `babel-node` to behave **exactly** how `node` does.

**Comment by MoOx** [comment]
Thanks for the confirmation.
I just found what I need in my case: https://github.com/wavded/babel-tape-runner
Have a nice day.

**Comment by ericclemmons** [comment]
@MoOx Thanks for posting this!  Just started using `node-tape` tonight and this was exactly what I was trying to replicate myself.
