### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by namesweretaken** [babel/babel#11161]
Hi,

In the babel-helper-plugin-utils package src/index.js there seems (at least to me) to be a syntax error on line 93 . Though this file hasn't been changed for over 2 years.

https://github.com/babel/babel/blob/4b045819b897dee49199d1439776a6013fed49a7/packages/babel-helper-plugin-utils/src/index.js#L93

**Comment by nicolo-ribaudo** [comment]
It's not a syntax error: that's a valid Flow type cast.
