### ISSUE TITLE
No matching version found for @babel/traverse@^7.8.6

### ISSUE THREAD

**Issue by zabawt** [babel/babel#11177]
While installing @babel/core@7.8.6 I'm receiving this error.
It is caused by @babel/helper-replace-supers.  Apparently it shouldn't be true as latest version is exactly this @babel/traverse -> 7.8.6 https://www.npmjs.com/package/@babel/traverse.

I tried installing @babel/core@7.7.7 and @babel/core@.7.7.0 both versions are failing due to the issue mentioned above.

I will upload npm logs in a second.

**Comment by zabawt** [comment]
Fixed on my side, closing the ticket

**Comment by hbrls** [comment]
@zabawt  How did you fix that?
