### ISSUE TITLE
Add ability to run babel with any .babelrc as cli parameter 

### ISSUE THREAD

**Issue by Kivylius** [babel/babel#11174]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have multiple babel configs that output different code in my package and want specifically to transpile my code with babel with a cli parameter that points to a ".babelrc" (or in my case .test-babelrc). I cannot do it programatically and need this support on the cli level.

**Describe the solution you'd like**
`babel ./src --out-dir dist --babelrc './configs/.test-babelrc'` or something along these lines.

**Describe alternatives you've considered**
None is available as I do not control the other builds and cannot do `babelrc: false` or something along those lines.

**Teachability, Documentation, Adoption, Migration Strategy**
The doc already have a parameter called `configFile`, if we could make this work on the cli we would kill two birds with one stone and just remove the line that states: 'Placement: Only allowed in Babel's programmatic options' and allow on cli (add example as above).

**Comment by nicolo-ribaudo** [comment]
Doesn't `--config-file` (pointing to a `babel.config.json` file) works for you? `.babelrc`s are only meant to be loaded based on the file path.
