### ISSUE TITLE
Forced calls of OptionalCalls do not print correctly

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#11187]
## Bug Report

It's possible to force the calling of an `OptionalCallExpression` by wrapping it in parentheses:

```js
foo?.();     // <- That's an optional call
foo?.()();   // <- That's an optional call of an optional call

(foo?.())(); // <- That's a forced call of an optional call
```

This roughly translates to the following:

```js
foo == null ? undefined : foo();     // <- That's an optional call
foo == null ? undefined : foo()();   // <- That's an optional call of an optional call

(foo == null ? undefined : foo())(); // <- That's a forced call of an optional call
```

Now, the bug: When we print these without transforming them (meaning we're going to output ES2020 syntax), the forced call loses its parentheses:

```js
// Input
(foo?.())();

// Output
foo?.()();
```

This is incorrect! If we were to try parsing that output, it'd be an optional call of an optional call, not a forced call of an optional call.

**Current Behavior**

Outputs `foo?.()()`, which is incorrect

**Input Code**
- [REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=PTAEDEHsCcGMFMAmpYEMA27SQGalQHbYAOALgJaQEYoboBQAFDpJAPwB0jAlNzwNz16ICDATIAtvAkAjeNGx5CJClRppMTFuy68OM1AC9-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=true&targets=&version=7.8.6&externalPlugins=)

```js
(foo?.())();
```

**Expected behavior/code**

Outputs `(foo?.())()`

**Possible Solution**

We need to check if parenthesis are necessary when outputting an `OptionalCallExpression`. We already do this for `OptionalMemberExpression`s (which have a very similar behavior).

https://github.com/babel/babel/blob/d13fd7c7bdb51995e8c9171b7047fc93402f8c3a/packages/babel-generator/src/node/parentheses.js#L254-L259

You can verify that if you input `(foo?.bar).baz` (a forced member of an optional member), it will have parenthesis in the output.

**Additional context/Screenshots**

We need to test the following to cases:

```js
// Forced call of an optional call
(foo?.())();

// Forced member of an optional call
(foo?.()).baz;
```

**Comment by sag1v** [comment]
Would love to take a shot if no takers :)

**Comment by sag1v** [comment]
@jridgewell / @nicolo-ribaudo 
So basically we should add this function to `parentheses.js`?
```
export function OptionalCallExpression(node: Object, parent: Object): boolean {
  return t.isCallExpression(parent) || t.isMemberExpression(parent);
}
```

Seems to fix these 2 use cases but breaks other use cases such as

```diff
- a.foo(bar?.());
+ a.foo((bar?.()));
``` 

Or

```diff
- a.foo(bar?.("test"));
+ a.foo((bar?.("test")));
```

Another thing i don't understand yet, is why we pass `parent` and not `node` to `isCallExpression` and `isMemberExpression`?

**Comment by sag1v** [comment]
I went with this approach:
```
export function OptionalCallExpression(node: Object, parent: Object): boolean {
  const nodeHasParens = node.extra && node.extra.parenthesized;
  return t.isOptionalCallExpression(node) && nodeHasParens;
}
```

Seems to be passing all tests as well as the 2 new cases.
Any feedback is welcome :)

**Comment by jridgewell** [comment]
> Seems to fix these 2 use cases mentioned in the issue, but breaks other use cases.

This is fine from a code perspective. The AST and runtime will behave correctly, it's just not as neat as we could make it.

If you want, you can add the following test cases:

```js
foo(bar?.baz);
foo(bar?.baz());
foo(bar?.("test"));


foo[bar?.baz];
foo[bar?.baz()];
foo[bar?.("test")];
```

None of these require parens, but they'll get them. We can modify the calls to `t.isCallExpression(parent)` to check if the `callee` node is the current `node`:

```js
t.isCallExpression(parent, { callee: node })
```

This'll fix the parens in the call cases. I'll let you figure out how to fix the member expression case.

> Another thing i don't understand yet, is why we pass parent and not node to isCallExpression and isMemberExpression?

The difference between a forced call of an optional call (and a forced member of an optional call) is that the parent node is a regular `CallExpression`/`MemberExpression`. In an optional call of an optional call (`foo?.()()`), the parent is an `OptionalCallExpression`. So the difference is only in the parent, not the current node.

**Comment by sag1v** [comment]
@jridgewell Thanks for the info, I wonder if you saw my edited comment regarding this approach
```
export function OptionalCallExpression(node: Object, parent: Object): boolean {
  const nodeHasParens = node.extra && node.extra.parenthesized;
  return (t.isCallExpression(parent) || t.isMemberExpression(parent)) && nodeHasParens;
}
```
It looks the same to me, but i may be missing something.

> We can modify the calls to t.isCallExpression(parent) to check if the callee node is the current node

Well, i was sure that `parent.callee` is always the `node` in our case 🤔

**Comment by sag1v** [comment]
@jridgewell After some playing with AST Explorer and some of your tests, i realised we probably need to modify the `OptionalMemberExpression` function as well.

```js
export function OptionalMemberExpression(
  node: Object,
  parent: Object,
): boolean {
  return (
    t.isCallExpression(parent, { callee: node }) ||
    t.isMemberExpression(parent, { object: node })
  );
}
``` 
and 
```js
export function OptionalCallExpression(node: Object, parent: Object): boolean {
  return (
    t.isCallExpression(parent, { callee: node }) ||
    t.isMemberExpression(parent, { object: node })
  );
}
```

What do you think?

**Comment by jridgewell** [comment]
> I wonder if you saw my edited comment regarding this approach

That will miss cases that are manually constructed in AST (it'd work fine if you parse from a source string). Setting `node.extra.parenthesized` shouldn't be required to get the generator to print correct code.

> I realized we probably need to modify the `OptionalMemberExpression` function as well

Yah, we should sync these changes in both places.

> This case `foo[bar?.baz];` transforms to this (before my change)

Those are both equivalent code, just has an unnecessary parentheses. The updated `t.MemberExpression` check should fix it.

**Comment by sag1v** [comment]
@jridgewell Thanks for the explanations and pointers, i have learned a lot. 👍🤓
