### ISSUE TITLE
@babel/standalone  transform cannot set presets stage-0

### ISSUE THREAD

**Issue by songyule** [babel/babel#11205]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
when i  use Babel.transform(version: @babel/standalone@7.8.6) set presets stage-0, i got an error
`Error: [BABEL] unknown: The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you want to use the legacy decorators semantics, you can set the 'legacy: true' option. (While processing: "base$1$0$0$0")`
But I use the old version(@babel/standalone@7.0.0-beta.44) and the same behavior works
**Input Code**
- REPL or Repo link if applicable:
https://codesandbox.io/s/amazing-moon-6glcz
```js
import * as Babel from "@babel/standalone";
  const testCode = `
    class App extends React.Component {
      state = { value: '' }
      onChange = e => {
        this.setState({value: e.target.value});
      }
      render() {
        return (
          <label>
            Enter a value111111:
            <br />
            <input type="text" value={this.state.value} onChange={this.onChange} />
          </label>
        )
      }
    }  
  `;
    const outputCode = Babel.transform(testCode, {
      presets: ["react", "stage-0"],
      plugins: [
        "proposal-class-properties",
        ["proposal-decorators", { legacy: true }]
      ]
    }).code;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

**Environment**

```
@babel/standalone version: v7.8.6
Node/npm version: v10.16.0/v6.9.0
OS: macOS v10.15.1
```

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/23656890/75852272-9c2a2f80-5e26-11ea-9e0d-1e3f6d4d74da.png)
![image](https://user-images.githubusercontent.com/23656890/75852332-b6fca400-5e26-11ea-8564-5318da98aa8d.png)

**Comment by JLHwung** [comment]
We should add default value `true` for `decoratorsBeforeExport` options accepted in the following places:

https://github.com/babel/babel/blob/21c91418722e3b0c0e9042427bb1524baebba452/packages/babel-standalone/src/preset-stage-0.js#L10

and `preset-stage-1.js`, `preset-stage-2.js`.

PR is welcome!

**Comment by nicolo-ribaudo** [comment]
We didn't add a default value on purpose: it wasn't clear which one we should have used. The current proposal has decorators _after_ export, but it's a completely different proposal from the one implemented in Babel.

This is a configuration error: in that sandbox, both "modern" and "legacy" decorators are enabled. "modern" decorators using the `stage-0` preset, and "legacy" using the plugin.

This should work:
```js
    const outputCode = Babel.transform(testCode, {
      presets: [
        "react",
        ["stage-0", { decoratorsLegacy: true }]
       ]
    }).code;
```

**Comment by songyule** [comment]
> We didn't add a default value on purpose: it wasn't clear which one we should have used. The current proposal has decorators _after_ export, but it's a completely different proposal from the one implemented in Babel.
> 
> This is a configuration error: in that sandbox, both "modern" and "legacy" decorators are enabled. "modern" decorators using the `stage-0` preset, and "legacy" using the plugin.
> 
> This should work:
> 
> ```js
>     const outputCode = Babel.transform(testCode, {
>       presets: [
>         "react",
>         ["stage-0", { decoratorsLegacy: true }]
>        ]
>     }).code;
> ```

thx, It's ready to work
