### ISSUE TITLE
[parser] Illegal arrow expression containing `in` as `for` lhs

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11202]
## Bug Report

Copied from https://github.com/acornjs/acorn/issues/922

REPL: [Safe link](https://babeljs.io/repl#?browsers=node%206&build=&builtIns=false&spec=false&loose=false&code_lz=GYewTgBAFAHhC8A-CMCWA7CBPA3DglDkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env&prettier=true&targets=Node-13&version=7.8.6&externalPlugins=)

(change `xin` to be `x in` and you will see REPL is stuck 😱)

**Comment by nicolo-ribaudo** [comment]
Oh wow, this is the first time I see `@babel/parser` stuck in an infinite loop.

**Comment by vedantroy** [comment]
I don't get an infinite loop. Running `./babel test.js` where "test.js" = `for (x => x in y;;);` outputs `for (x => (x in y);;);`, which is wrong, but there is no infinite loop.

**Comment by kaicataldo** [comment]
Huh, so interestingly, at least in Firefox:

```js
// Executing this in the console causing the page to lock up - some kind of infinite loop.
for (x=>(x in y);;);

// Executing this results in an immediate error: `SyntaxError: invalid for-in/of left-hand side.`
for (x=>x in y;;);
```

**Comment by nicolo-ribaudo** [comment]
```js
for (x=>(x in y);;);
```
This is an infinite loop because it's valid code, and you didn't provide a condition in the test :stuck_out_tongue: 

```js
for (x=>(x in y); false;);
// or
for (x=>(x in y);;) break;
```

**Comment by kaicataldo** [comment]
Ah, that makes sense :laughing:
