### ISSUE TITLE
[parser]: A class should not extend an async function

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11209]
## Bug Report

copied from https://github.com/acornjs/acorn/issues/917

The following snippet throw unexpected token `=>`.

```js
class A extends async () => {} {}
class B extends async function () {} {}
```

[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjSBPdw0AFAJTQC8AfNAN4C-tdAUKJDAEKKobbR4HQAZgFcCKAJYB7dMTL1GQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env&prettier=false&targets=Node-6&version=7.8.7&externalPlugins=).

**Comment by nicolo-ribaudo** [comment]
@leobalter Would tests like this one be accepted in test262?

**Comment by leobalter** [comment]
We probably have a similar test for the (sync) arrow function in the extends position. I don’t think it’s a problem to add a valid function form that is not allowed in that position. The only thing I would request is for the test to include the matching spec text in the info meta tag.

**Comment by JLHwung** [comment]
Closing this issue as the current behaviour aligns to spec. See https://github.com/acornjs/acorn/issues/917#issuecomment-662047238
