### ISSUE TITLE
Problem with extending Promise

### ISSUE THREAD

**Issue by rtm** [babel/babel#1120]
I am trying to extend Promise:

    class PersistedPromise extends Promise { }

Then call the static `resolve` on the derived class to directly create a resolved promise:

    PersistedPromise.resolve(1)

In Babel (run as `babel-node --experimental promise.js`) it results in:

        Promise.apply(this, arguments);
                ^
    TypeError: [object Object] is not a promise
        at new PersistedPromise (~rtm/gen/promise.js:1:23)
        at Function.resolve (native)
        ...

I was depending on this:

> All static methods of Promise support subclassing: they create new instances via their receiver (think: new this(...)) and also access other static methods via it (this.resolve(...) versus Promise.resolve(...)).

from http://www.2ality.com/2014/10/es6-promises-api.html.

It appears that node checks the `this` on calls such as `Promise.resolve.call(this, val)` for being a `Promise`, rather than (correctly?) `Promise` or a derived class thereof (v0.12.0).

Can Babel work around this somehow, or is this a bug in node's promises that we're stuck with, or is there some other workaround?

i tried defining my own `resolve` as

    PersistedPromise.resolve = function(v) { return new this(() => { }).then(() => v); };

but ran into the same kind of problem, presumably when `then` is trying to create a new promise to return.

**Comment by zloirock** [comment]
[Babel not support subclassing native constructors.](https://babeljs.io/docs/usage/caveats/#classes)

**Comment by sebmck** [comment]
Please see the [caveats](http://babeljs.io/docs/usage/caveats/#classes). :smile:

**Comment by rtm** [comment]
The caveat says:

> Built-in classes such as Date, Array, DOM etc cannot be properly subclassed due to limitations in ES5.

However, Promise is not even in ES5, thus any reason for it not being subclassable cannot be attributed to limitations in ES5.  Also, Promise has no "magic" behaviors like Array. The reason appears to be limitations in the implementation of Promise in certain environments (such as V8), in which case it would be nice to mention that. 

In addition, Babel ships with its own Promise polyfill in core-js, which could presumably be modified to be subclass-friendly. 

For instance, the line https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L161

    resolve: function(x){
        return isObject(x) && RECORD in x && $.getProto(x) === this.prototype

probably needs to be fixed to check that the Promise prototype is in the chain, rather than being strictly equal. Should I report this separately on core-js?

Of course, even if core-js is fixed, I need some way to tell Babel to use the polyfill instead of native promises--I wonder if there is some way to do that.

**Comment by sebmck** [comment]
> However, Promise is not even in ES5, thus any reason for it not being subclassable cannot be attributed to limitations in ES5.

It's attributed to limitations in the ES5 specification and implementations.

> In addition, Babel ships with its own Promise polyfill in core-js, which could presumably be modified to be subclass-friendly.

Correct, I spoke to soon.

> Should I report this separately on core-js?

Most likely. cc @zloirock

**Comment by zloirock** [comment]
@rtm on Node 0.12 core-js not replace native `Promise`. I can replace it, but don't think this a good idea - it conforms to the spec. `Promise` has "magic" behavior like `Array` (for example, #1043).

core-js `resolve` works correct - if it's accepts promise, **created `this` constructor**, it's returns this promise - that's why we need this check.

**Comment by rtm** [comment]
@zloirock Thanks for response. `Promise` does **not** have magic behavior. The issue you referenced is about something else, which is spread parameters in `new` calls.

**Comment by zloirock** [comment]
@rtm looks like you don't fully understood cause of that issue. The reasons are completely similar - in magic behavior of native constructors, but current can't be so simply fixed.

**Comment by rtm** [comment]
Maybe I understand the cause of that issue, maybe I don't. Basically, the following needs to work:

    Promise.prototype.resolve.call(instance_of_my_derived_promise_class);

This is what Babel generates, essentially, which is fine!!

The problem is that the **implementation** of `Promise#resolve`, when it checks the type of `this`, needs to check not that it is precisely a Promise, but rather that it is a Promise *or subclass thereof*, i other words, that Promise is in the prototype chain. If the check passes, the rest of the logic should work just fine. In other words, there is a **bug** in the V8 implementation of `Promise#resolve`, where the check for the type of `this` is incorrect.

There is no way for Babel to change the behavior of V8. The best you can do is to ensure that your bundled polyfill works correctly, and provide some means to invoke it.

**Comment by zloirock** [comment]
@rtm it's not a bug, V8 implementation works by spec. `YourPromise#resolve` -> `new  YourPromise(resolver)` (by spec) -> `Promise.apply(this, arguments)` (in babel) -> native constructor error - can't be called w/o `new`.

**Comment by stefanpenner** [comment]
```
Promise.resolve.call(instance_of_my_derived_promise_class);
```

I believe this should actually work,  as long as `instance_of_my_derived_promise_class instanceof Promise === true`. It does not, because you cannot yet subclass promises in v8.

**Comment by zloirock** [comment]
@stefanpenner [step 2](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.resolve), it does not consider the prototype chain.

**Comment by stefanpenner** [comment]
@zloirock sorry i assumed this was a subclassing related issue? Maybe i don't understand the @rtm's actual bug report

**Comment by stefanpenner** [comment]
ah, ok I understand his exact question. (Although my above subclassing comment does remain true, although for a different point I suppose.)

`resolve` should be thought of as `cast` where it will downcast or upcast (depending on your perspective). 

for example:

```js
class CancellablePromise extends Promise {
  // ...
}

var a = new CancellablePromise( (resolve, reject, cancel) => { });
var b = new Promise( (resolve, reject) => { } );

CancellablePromise.resolve(a).constructor === CancellablePromise;
Promise.resolve(a).constructor === Promise;

CancellablePromise.resolve(b).constructor === CancellablePromise;
Promise.resolve(b).constructor === Promise;
```

Why is this a thing? Promise's are basically not allowed to operate on promises of a different type, they must first cast the the thennable before operating.

Interestingly an early iteration of the spec had both `resolve` and `cast`, and `resolve` was dropped and `cast was renamed to `resolve`.

**Comment by zloirock** [comment]
@stefanpenner about `ES6Promise` feature detection - it's not correct subclassing by ES6 spec. I don't think it's a reason for replace native `Promise` anywhere. As I wrote above, possible add option for forced usage polyfill.

**Comment by stefanpenner** [comment]
> it's not correct subclassing by ES6 spec.

ya this pre-dates the `super` requirement, which makes it impossible to detect... crap

**Comment by stefanpenner** [comment]
https://github.com/jakearchibald/es6-promise/pull/91
