### ISSUE TITLE
transformFromAst: Add option to not clone the AST

### ISSUE THREAD

**Issue by mischnic** [babel/babel#11206]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**

https://github.com/babel/babel/issues/7987 / https://github.com/babel/babel/pull/8342 clones the AST by default, but cloning can take a considerable amount of time and the caller might decide it is not needed.

**Describe the solution you'd like**
Add an option to `transformFromAst` to not clone the input ast, because I am fine with mutation.

**Teachability, Documentation, Adoption, Migration Strategy**
```js
transformFromAst(ast, sourceCode, {cloneAst: false});
```

**Comment by nicolo-ribaudo** [comment]
As a workaround, I'm currently using [this plugin](https://github.com/nicolo-ribaudo/codemods/blob/40e90e3ad6e2db91fd7756bcce68bfefd373a3a3/src/utils.js#L59-L67).

Out of curiosity, would using `@babel/traverse` directly (rather than Babel core) work for your use case?

**Comment by mischnic** [comment]
> As a workaround, I'm currently using this plugin.

The current situation works, but could be faster. I think that plugins doesn't help me?

> Out of curiosity, would using @babel/traverse directly (rather than Babel core) work for your use case?

https://github.com/parcel-bundler/parcel/blob/a07a8b84923a74077b70a4d2fcbc5a9f17736f3b/packages/transformers/js/src/JSTransformer.js#L142

https://github.com/parcel-bundler/parcel/blob/a07a8b84923a74077b70a4d2fcbc5a9f17736f3b/packages/transformers/babel/src/babel7.js#L53

But `@babel/traverse` wouldn't accept the Babel options (`presets`/`plugins`/`createConfigItem`)?
