### ISSUE TITLE
plugin-syntax-dynamic-import didnot re

### ISSUE THREAD

**Issue by 3cp** [babel/babel#11204]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
Based on comments [here](https://github.com/babel/babel/blob/38f8bbac1ab3d70c43c276f48a0c85f3fd72b2bf/packages/babel-plugin-proposal-dynamic-import/src/index.js#L14-L17) in plugin-proposal-dynamic-import: 

```
If you are using Webpack or Rollup and thus don't want
Babel to transpile your imports and exports, you can use
the @babel/plugin-syntax-dynamic-import plugin and let your
bundler handle dynamic imports.
```

plugin-syntax-dynamic-import should preserve dynamic import statement. But it did not.

**Input Code**

Demo repo https://github.com/3cp/babel-dynamic-import-issue

With config
```json
{
  "presets": [["@babel/preset-env", {"loose": true}]],
  "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

And source code
```js
import('foo');
```

Babel compiled it into

```js
"use strict";

function _getRequireWildcardCache() { if (typeof WeakMap !== "function") return null; var cache = new WeakMap(); _getRequireWildcardCache = function _getRequireWildcardCache() { return cache; }; return cache; }

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } if (obj === null || typeof obj !== "object" && typeof obj !== "function") { return { "default": obj }; } var cache = _getRequireWildcardCache(); if (cache && cache.has(obj)) { return cache.get(obj); } var newObj = {}; var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null; if (desc && (desc.get || desc.set)) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } newObj["default"] = obj; if (cache) { cache.set(obj, newObj); } return newObj; }

Promise.resolve().then(function () {
  return _interopRequireWildcard(require('foo'));
});
```

The result **didn't retain dynamic import statement**.

**Expected behavior/code**
plugin-syntax-dynamic-import should help to retain dynamic import statement.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `. babelrc`

```json
{
  "presets": [["@babel/preset-env", {"loose": true}]],
  "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

**Environment**
```
  System:
    OS: macOS 10.15.3
  Binaries:
    Node: 12.16.0 - ~/.nodenv/versions/12.16.0/bin/node
    Yarn: 1.22.0 - ~/.nodenv/versions/12.16.0/bin/yarn
    npm: 6.14.1 - ~/.nodenv/versions/12.16.0/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    @babel/core: ^7.8.6 => 7.8.6 
    @babel/plugin-syntax-dynamic-import: ^7.8.3 => 7.8.3 
    @babel/preset-env: ^7.8.6 => 7.8.6 
```

**Possible Solution**
Nil

**Additional context/Screenshots**
I recall it worked before. I don't remember what time I checked this, might be a year ago.

**Comment by nicolo-ribaudo** [comment]
You have to exclude the plugin from preset-env. (Add `exclude: ["proposal-dynamic-import"]`)

It's only automatically excluded when you are using a bundler.

**Comment by 3cp** [comment]
Oh, thx you.

Might be a good idea to show preset-env config in doc of https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import
