### ISSUE TITLE
Babel-generated code incompatible with Safari's implementation of strict mode

### ISSUE THREAD

**Issue by tyteen4a03** [babel/babel#1121]
I'm on Safari 8.0.5 and running babel-processed code gives me the following error:

`[Error] SyntaxError: Cannot declare a parameter named 'error' as it shadows the name of a strict mode function.`

This is my original code:

        $.ajax({
            url: "/cart/add.js",
            method: "POST",
            dataType: "json",
            success: function (data, status, jqXHR) {
                location.href = "/cart";
            },
            error: function (jqXHR, status, error) {
                $(".error-row", $page).add("active");
                if (status == 422) {
                    $(".error-row .error", $page).text($.parseJSON(jqXHR.responseText)["description"]);
                } else {
                    $(".error-row .error", $page).text("Service unavailable; please try again later.");
                }
            }
        });

This is babel-processed code:

        $.ajax({
            url: "/cart/add.js",
            method: "POST",
            dataType: "json",
            success: function success(data, status, jqXHR) {
                location.href = "/cart";
            },
            error: function error(jqXHR, status, error) { // Line of Error
                $(".error-row", $page).add("active");
                if (status == 422) {
                    $(".error-row .error", $page).text($.parseJSON(jqXHR.responseText).description);
                } else {
                    $(".error-row .error", $page).text("Service unavailable; please try again later.");
                }
            }
        });

**Comment by sebmck** [comment]
Safari is terrible and I hate that they have a horribly out of spec implementation of strict mode, it causes so much pain. I'll probably add some param detection logic to the `spec.functionName` transformer. In the meantime just disable it:

```javascript
require("babel").transform("code", { blacklist: ["spec.functionName"] });
```

```sh
$ babel --blacklist spec.functionName
```

**Comment by sebmck** [comment]
Actually looks like I already took this behaviour into consideration as there's [this](https://github.com/babel/babel/blob/master/src/babel/transformation/helpers/name-method.js#L62-73) big whopping comment. Looks like it was disabled pending an actual fix for #871.

**Comment by tyteen4a03** [comment]
Do you know if this has been reported to them?

**Comment by monsanto** [comment]
@tyteen4a03 This issue has been known in the developer community since at least 2013. I actually cannot find an issue on the WebKit tracker for it, feel free to make one. Note that it is highly unprobable that the Safari team will release something promptly to fix this, because they never do.
