### ISSUE TITLE
Can I use babel to transform in AST, instead of code?

### ISSUE THREAD

**Issue by jiyinyiyong** [babel/babel#1122]
I want to build ES6 by learning https://github.com/estree/estree and https://github.com/jquery/esprima and then generate ES5 code. Can I do this with babel?

**Comment by sebmck** [comment]
Yes.

```javascript
require("babel").transform.fromAST(ast, originalCode, options);
```

Note: A number of ES6 AST definitions were changed as they were standardised by ESTree. This means that 4.x is outdated and does not reflect the changes represented in the ESTree docs. This will however change with the upcoming 5.x release which will be 100% ESTree compliant.

**Comment by sebmck** [comment]
Also, GitHub issues is not the correct place to ask these types of questions, as per the README:

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) before creating an issue.
