### ISSUE TITLE
@babel/plugin-proposal-private-methods "Unexpected token" when accessing private property with elvis operator (obj?.#prop)

### ISSUE THREAD

**Issue by leonardoraele** [babel/babel#11224]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
When I try to access a private property of an object using elvis operator, I get a "Unexpected token" error.

**Input Code**
```js
class Face
{
    #data;
    layout;

    constructor(other = null)
    {
        this.#data = new LayoutData(other?.#data); // <- here
        this.layout = other?.layout ?? null;
    }
}
```
By comparison, the following equivalent code seems to be working fine:
```js
class Face
{
    #data;
    layout;

    constructor(other = null)
    {
        const otherData = other ? other.#data : undefined; // Replaced ?.# by equivalent ternary condition
        this.#data = new LayoutData(otherData);
        this.layout = other?.layout ?? null;
    }
}
```

**Expected behavior/code**
No error should occur.

**Babel Configuration**
```js
// babel.config.js
module.exports =
{
	presets:
	[
		'@vue/cli-plugin-babel/preset',
	],
	plugins:
	[
		[
			require.resolve('babel-plugin-module-resolver'),
			{
				root: [ './src' ],
				alias: {
					tests: './tests',
					loaders: './loaders',
					assets: './assets',
				},
			},
		],
		[
			"@babel/plugin-proposal-private-methods",
		],
	]
};
```

**Environment**
- @babel/code-frame: 7.8.4
- @babel/compat-data: 7.8.5
- @babel/core: 7.8.4
- @babel/generator: 7.8.4
- @babel/plugin-proposal-private-methods: 7.8.3
- Node/npm version: 13.9.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: via webpack (4.41.6)
- babel-loader: 8.0.6

**Comment by JLHwung** [comment]
Thanks for the report.

Both `a?.#b` and `a.#b?.c` is _not_ a valid grammar production. According to the [spec](https://tc39.es/proposal-optional-chaining/#prod-OptionalChain)
```
OptionalChain:
  ?.[ Expression ]
  ?.IdentifierName
  ?.Arguments
  ?.TemplateLiteral
  OptionalChain[ Expression ]
  OptionalChain.IdentifierName
  OptionalChain Arguments
  OptionalChain TemplateLiteral
```
`OptionalChain` does not allow `?. PrivateIdentifier` and `OptionalChain . PrivateIdentifier`. Closing this as it is expected.

Side note: there is an open discussion thread on tc39 about interoperability between optional chaining and private fields: https://github.com/tc39/proposal-optional-chaining/issues/28
