### ISSUE TITLE
@babel/proposal-class-properties class field initialization override field value in some situation

### ISSUE THREAD

**Issue by fwang2002** [babel/babel#11223]
## Bug Report
- [ ] I would like to work on a fix!

**Current Behavior**
@babel/proposal-class-properties generate field initialization code, which overrides the field values assigned dynamically in base class.
Although dynamically assign field value is not good, but sometimes it may write such code. For example: in base class, read a JSON file, and dynamically assign values for class members.

**Input Code**
```ts
class Base {
    constructor(obj: any = null) {
        if (obj != null) {
            console.log('in base');
            for (let key in obj) {
                this[key] = obj[key];
                console.log(`  this.${key}: ${this[key]}`);
            }
        }
    }
}

class Extended extends Base {
    id: number;
    name: string;

    constructor(obj: any = null) {
        super(obj);
        console.log('in extended');
        console.log(`  this.id: ${this.id}`);
        console.log(`  this.name: ${this.name}`);
    }
}

new Extended({id: 1, name: "test"});
```

**Expected behavior/code**
the correct output should be:
```
in base
  this.id: 1
  this.name: test
in extended
  this.id: 1
  this.name: test
```

but now it is:
```
in base
  this.id: 1
  this.name: test
in extended
  this.id: undefined
  this.name: undefined
```

targeting ES6, the transformed code for class Extended is:
```js
class Extended extends Base {
  constructor(obj = null) {
    super(obj);
    this.id = void 0;
    this.name = void 0;
    console.log('in extended');
    console.log(`  this.id = ${this.id}`);
    console.log(`  this.name = ${this.name}`);
  }
}
```
the field initialization caused the problem.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
  "presets": [
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

**Possible Solution**
Do not generate field initialization code when there is only a class field declaration without value initialization, especially in loose mode.
```ts
class Extended extends Base {
    public id: number;    // do not generate initialization code
    public name: string = 'test'; // generate initialization code
}
```

**Comment by JLHwung** [comment]
Please use the `declare` syntax if you intend `public id: number` to be a type on declaration.

```js
class A {
  foo: string | void; // initialized to undefined
  declare bar: number; // type-only
}
```
Since it is introduced in recent TypeScript 3.7, it is behind a `allowDeclareFields` flag.
```js
{
  presets: [
    ["@babel/typescript", { "allowDeclareFields": true }]
  ]
}
```

In Babel 8 we will remove uninitialized type only declaration.
