### ISSUE TITLE
JS Prefixer

### ISSUE THREAD

**Issue by Legends** [babel/babel#11229]
Does babel support js prefixing like:

`pointerdown --> mspointerdown`

**example:**
`document.addEventListener("pointerdown", ()=>....);`

**Comment by xtuc** [comment]
You could write a Babel plugin that does that. I would recommend you looking at https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md

**Comment by Legends** [comment]
Actually a stupid question....
