### ISSUE TITLE
Use vanilla regenerator

### ISSUE THREAD

**Issue by sebmck** [babel/babel#1123]
I'm reducing the amount of forks I need to maintain. I've inlined `acorn`, mainly because Babel requires **extensive** modifications to it. `regenerator`, not so much. The following is required in order to use vanilla `regenerator`:

 - [ ] Have a way to require `regenerator` without pulling in `recast` and `esprima-fb`.

 - [x] Have a way to hoist all statements to the "outer rim". See [here](https://github.com/babel/regenerator-babel/blob/master/lib/visit.js#L71-80) for the relevant code that I've added. Basically with that modification, given the following:

  ```javascript
  function* foo(...foo) {

  }
  ```

  Will produce:

  ```javascript
  "use strict";

  var foo = regeneratorRuntime.mark(function foo() {
    for (var _len = arguments.length, foo = Array(_len), _key = 0; _key < _len; _key++) {
      foo[_key] = arguments[_key];
    }

    return regeneratorRuntime.wrap(function foo$(context$1$0) {
      while (1) switch (context$1$0.prev = context$1$0.next) {
        case 0:
        case "end":
          return context$1$0.stop();
      }
    }, foo, this);
  });
  ```

  Without it the following will be produced:

  ```javascript
  "use strict";

  var foo = regeneratorRuntime.mark(function foo() {
    var _len, foo, _key, _arguments = arguments;

    return regeneratorRuntime.wrap(function foo$(context$1$0) {
      while (1) switch (context$1$0.prev = context$1$0.next) {
        case 0:
          for (_len = _arguments.length, foo = Array(_len), _key = 0; _key < _len; _key++) {
            foo[_key] = _arguments[_key];
          }

        case 1:
        case "end":
          return context$1$0.stop();
      }
    }, foo, this);
  });
  ```

  This will cause `arguments` to deopt the entire function in V8 and other engines.

  I'm planning on moving away from this pattern by introducing some hoisting levels that node replacement will automatically work out but this is necessary for the foreseeable future.

 - [x] Have a way to have unique `runtimeProperty` nodes across transforms. (Babel mutates these and it caused me a lot of pain and was very difficult to debug)

/cc @benjamn Would you be willing to add these additional options to `regenerator`?

**Comment by benjamn** [comment]
That all seems reasonable. I've given some thought to transforming `...rest` more efficiently (https://github.com/facebook/regenerator/issues/132) but never settled on a good strategy.

By uniquing `runtimeProperty` nodes, you just mean I should be recreating them each time I need them, rather than [creating them once](https://github.com/facebook/regenerator/blob/9226f0c5604ad9ed9ee8b0b75e1d5b4cb20ad82e/lib/visit.js#L23-L26)?

**Comment by sebmck** [comment]
@benjamn 

> By uniquing `runtimeProperty` nodes, you just mean I should be recreating them each time I need them, rather than [creating them once](https://github.com/facebook/regenerator/blob/9226f0c5604ad9ed9ee8b0b75e1d5b4cb20ad82e/lib/visit.js#L23-L26)?

Yeah, right now I'm [recreating](https://github.com/babel/regenerator-babel/blob/master/lib/visit.js#L107) them.

**Comment by sebmck** [comment]
@benjamn What do you see as a good compromise for the `_blockHoist` requirement? Happy to prepare a PR that adds all of this to `regenerator`.

**Comment by fundon** [comment]
Hwo to keep `function* (){}`?

I installed the latest babel v5.0.2. But the `"blacklist":["regenerator"]` losed efficacy.

**Comment by sebmck** [comment]
@fundon That does in fact still work in 5.x.

**Comment by benjamn** [comment]
@sebmck I'm ok with the `_blockHoist` technique, as long as Regenerator doesn't depend on it. It seems similar in spirit to https://github.com/facebook/regenerator/issues/171, if you think of `awaitExpression.all` and `statement._blockHoist` as special extensions to the AST supported by only some parsers.

If you want to prepare a PR for that, I think it will actually be a little easier now that I'm [not hoisting `FunctionDeclaration` nodes anymore](https://github.com/facebook/regenerator/commit/53a2bf9c5280f9f104d7deafcc166bd7ae056c03).

With regard to https://github.com/benjamn/recast and https://www.npmjs.com/package/esprima-fb, I'm considering moving the transform into a NPM package named either `regenerator-transform` or `regenerator-core` and making the current package be a small wrapper around that provides compilation. Then you could depend on the core package and not the Facebook one.
