### ISSUE TITLE
babel/preset-env doesn't compile according to .browserlistrc and IE

### ISSUE THREAD

**Issue by Yegorich555** [babel/babel#11238]
## Bug Report
- [ ] I would like to work on a fix!

**Current Behavior**
1) use **.browserslistrc** with single line ```IE>=10```
2) babel doesn't compile this according to IE that doesn't support ES6!

**Input Code**
Reproducible repo [here](https://github.com/Yegorich555/WebpackMustHave/tree/feature/bug_babelBrowserListIE)
How to run:
```
npm install
npm run serve
```
open **localhost:8080** in **IE11** - you will find the error  ```Object doesn't support property or method 'find'``` because **find** doesn't exist on array in IE11 and ES5 in general

**Expected behavior/code**
Babel must compile code according to browser list

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  presets: [
    "@babel/preset-react", // optional: react: this resolves react-files (jsx, tsx)
    "@babel/preset-typescript", // allows  to use TypeScript
    "@babel/preset-env" // allows you to use the latest JavaScript
  ],
  plugins: [
    "@babel/plugin-proposal-class-properties", // transforms static class properties as well as properties declared with the property initializer syntax
    "jsx-classnames-advanced" // optional: react: this resolves className={object}
  ]
};
```

- Filename: `.browserslistrc`
```
IE>=10
```
**Environment**
```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 13.10.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    babel-eslint: ^10.0.3 => 10.0.3
    babel-loader: ^8.0.6 => 8.0.6
    babel-plugin-jsx-classnames-advanced: ^1.0.2 => 1.0.2
    eslint: ^6.6.0 => 6.7.1
    webpack: ^4.41.3 => 4.41.3
```

**Comment by nicolo-ribaudo** [comment]
Babel compiles _syntax_: `find` is a function, which needs to be polyfilled. You can either use `@babel/preset-env`'s `useBuiltIns` option ([docs](https://babeljs.io/docs/en/babel-preset-env#usebuiltins)) or `@babel/plugin-transform-runtime`'s `corejs` option ([docs](https://babeljs.io/docs/en/babel-plugin-transform-runtime#corejs)). Or you can also load your own polyfill with a `<script>` tag.

**Comment by Yegorich555** [comment]
Ohh. Thank you. Looks like ```useBuiltIns: 'usage'``` is the best for me.
**useBuiltIns** fixes this but, it's not obvious at all. It's weird that I need to point on polyfills when it's clear from **.browserslistrc**. I have got even any warning, that can draw my attention to it. 
It will be a nice feature
