### ISSUE TITLE
No matching version found for @babel/types@^7.7.0

### ISSUE THREAD

**Issue by Jiang1996** [babel/babel#11237]
**Current Behavior**
-Run npm i -g babel-eslint
Get following error messages:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.7.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'babel-eslint'
npm ERR! notarget

**Environment**
- Babel version(s): v7.6.4
- Node/npm version:  Node v10.16.3/npm 6.14.1
- OS:  OSX 10.15.3
- How you are using Babel: loader

**Comment by JLHwung** [comment]
@babel/types@7.7.0 is [published](https://www.npmjs.com/package/@babel/types) on npm. Could you attach the output?
```
curl --head -v `npm view @babel/types dist.tarball`
```
Please check if you are behind a proxy or using a third parth npm registry.

There are situations when these cache need some time to update to the latest version. You could also find a solution in https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed
