### ISSUE TITLE
Support setting Context displayName in `@babel/plugin-transform-react-display-name`

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel#11241]
## Feature Request

- [x] I would like to work on this feature!
- [ ] I have bandwidth to work on this feature in the near future. 🙁

**Is your feature request related to a problem? Please describe.**

Here's an example of React DevTools with a few context providers and consumers:

![image](https://user-images.githubusercontent.com/1500684/76429668-f8380b00-6374-11ea-8ec2-a3713d3e4689.png)

You'll notice that the context consumer and provider rendered under `ThemeProvider` have generic `Context.Consumer` and `Context.Provider` display names, but there's also a `Router.Provider` and `Router.Consumer` in there which are much more clear.

They accomplish this by setting the context's `displayName` value.

Here are some test cases:

```javascript
import React from 'react'

const MyContext = React.createContext()
MyContext.displayName = 'MyContext'
```

**Describe the solution you'd like**

I'd like [`@babel/plugin-transform-react-display-name`](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-display-name/src/index.js) to support automatically setting the `displayName` property for contexts.

**Describe alternatives you've considered**

I can set it manually. Not desirable. Or I could write my own babel plugin, but then others wouldn't benefit from it if they either don't know about the plugin or can't install it. Also, this seems to make a lot of sense to be included here to me.

**Teachability, Documentation, Adoption, Migration Strategy**

No need, it'll just magically start working and people will be pleasantly surprised.

**Comment by kevin940726** [comment]
I would love to help :) !

However, I think `@babel/plugin-transform-react-display-name` only supports assigning `displayName` to components created by `createClass`? I'm not sure if it should be the right target package we should build this into? Maybe I'm missing something 🤔

**Comment by kentcdodds** [comment]
Yes, I believe that's true. That said, there's nothing in the name to suggest that all it handles and considering it's already used by projects which would want this feature I think it's an acceptable place to put this.

**Comment by kevin940726** [comment]
@kentcdodds Fair enough 👍! I'm just curious then why [`babel-plugin-add-react-displayname`](https://github.com/opbeat/babel-plugin-add-react-displayname) isn't also part of this?

**Comment by kentcdodds** [comment]
I'm also curious about that. I definitely prefer the trade-off of a few extra bytes to have a better production debugging experience.

**Comment by nicolo-ribaudo** [comment]
Oh wow, I had no idea that our plugin was so outdated.

@roncohen Would you be open to adding this feature to [`babel-plugin-add-react-displayname`](https://github.com/opbeat/babel-plugin-add-react-displayname), and then merging `babel-plugin-add-react-displayname` to the official Babel plugin?

**Comment by existentialism** [comment]
Related: https://github.com/babel/babel/issues/8748

**Comment by ahutchings** [comment]
Related: #5679
