### ISSUE TITLE
Converts utf-8 characters

### ISSUE THREAD

**Issue by alexey-sh** [babel/babel#11258]
**Actual behaviour**:
ES2015 option converts 
"\u0002\u001e\u012e\b\u0001\b\u0001\u0004\u0002\t\u0002\u0004\u0003\t"
into
"\x02\x1E\u012E\b\x01\b\x01\x04\x02\t\x02\x04\x03\t"

[link to babel playground](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBCELwQRAHQK4AZ0CYXoIwFNscMCAjbXRMtC61AFnNSwBdGtaHaBmRZ-IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.8.7&externalPlugins=)

**Expecting**:
the same string.
![image](https://user-images.githubusercontent.com/1584156/76643107-7f4bd580-6565-11ea-9df9-7db671ecca1b.png)

**Comment by JLHwung** [comment]
These two strings are identical, you can check by
```js
"\u0002\u001e\u012e\b\u0001\b\u0001\u0004\u0002\t\u0002\u0004\u0003\t" === "\x02\x1E\u012E\b\x01\b\x01\x04\x02\t\x02\x04\x03\t"
// returns true
```
Babel uses [jsesc](https://github.com/mathiasbynens/jsesc#compact) to generate string literal, by default it will try to convert the string to a format which is 1) ASCII-safe (e.g. `\x02`) and 2) as short as possible (`\x02` vs `\u0002`). If you want to preserve the original `\u` format, please add the following items to your babel config
```json
{
  "generatorOpts": {
    "jsescOption": {
      "compact": false
    }
  }
}
```

**Comment by alexey-sh** [comment]
the values are the same but it is important whey you are trying to serve it with a static server on cp1251.
babel documentation doesn't contain the option you've mentioned. so the option is totally unuseful. 

so... @JLHwung thanks for your help. even if it makes no sense

**Comment by nicolo-ribaudo** [comment]
It will be documented soon: https://github.com/babel/website/pull/2172

> even if it makes no sense

Why? Babel doesn't give any guarantee about its output formatting. It only tries to preserve the _runtime_ behavior.

**Comment by alexey-sh** [comment]
>Babel doesn't give any guarantee 

exactly. so there is no reason to use this tool. also I'd like to note that formatting != encoding.

**Comment by JLHwung** [comment]
https://tc39.es/ecma262/#sec-ecmascript-language-types-string-type

> The String type is generally used to represent textual data in a running ECMAScript program, in which case each element in the String is treated as a UTF-16 code unit value.

I have no idea how `\u0042` => `\x42` can result to incorrect cp1251 encoding. Can you share a reproduction repo?

**Comment by alexey-sh** [comment]
>Can you share a reproduction repo?
sorry no. 
it's a tomcat server and jvm with -Dfile.encoding=Cp1251 option

**Comment by alexey-sh** [comment]
Actually it's webpack issue. Here is a demo repo
https://github.com/alexey-sh/webpack_and_babel_broken_encoding
