### ISSUE TITLE
Custom polyfill bundles?

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#1125]
I want to start using Babel in an existing clientside project. I can see it comes with a big browser polyfill that contains everything needed to support Babel output.

The thing is, I'm using [polyfill.io](https://polyfill.io/) already. This automatically polyfills [lots of features](https://cdn.polyfill.io/v1/docs/features/) in a per-browser way, e.g. browsers that already have `Array.from` don't even download that particular polyfill, which is nice. It includes most ES6 stuff, but it lacks a few things Babel needs, like the regenerator runtime, plus Map/Set.

So I don't want to use Babel's full `browser-polyfill.js` in every browser. Ideally I'd like to include just the polyfills I need.

Could I do something like this...

```js
require('MY_COREJS_BUILD');
require("regenerator-babel/runtime");
```

..where MY_COREJS_BUILD is the path to a custom corejs build that only contains stuff that isn't already provided by polyfill.io (like Map/Set)?

Would that work, or am I missing anything?

**Comment by zloirock** [comment]
> Could I do something like this

[Yep](https://github.com/zloirock/core-js#commonjs).

Not sure usage `polyfill.io` [`Array.from`](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array.from/polyfill.js) is a good idea - it's supports iterator protocol.

**Comment by sebmck** [comment]
>  I can see it comes with a big browser polyfill that contains everything needed to support Babel output.

You don't need to use it. You can continue using `polyfill.io` as-is or even use a custom core-js build as @zloirock suggests.

**Comment by callumlocke** [comment]
for the record, more details on exactly what needs polyfilling here:
http://babeljs.io/docs/usage/caveats/

**Comment by TimDaub** [comment]
Ok here's the problem from another angle:

We're using Babel in a big project and would like to get rid of certain polyfills that are not used in the application.
Is there a way to strip out all of those, or is there a way to run Babel so that it tells you which features you're using in your application?

**Comment by af7** [comment]
Hi, I have the exact same need as @TimDaub.

Is there a way to make the babel polyfill much smaller by including only the features we want?

P.S. I am aware of `custom builds` of `core-js`, I refer to `babel` (which uses it).

**Comment by aaani** [comment]
I have same issues as TimeDaub and afilp. I want to use just the Promise polyfill from it, but don't want to bundle all the polyfills into my build.

**Comment by aaani** [comment]
Update: Directly importing `core-js/es6/promise` from node_modules, or adding it to entry did the trick for me. 👍
