### ISSUE TITLE
TypeError:  Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null

### ISSUE THREAD

**Issue by YvetteLau** [babel/babel#11251]
The code as follow running normally at last version(V7.8.6), but at Version7.8.7，throw error.

```js
let obj = {one:{a:1}, other: {b:2}}
function fn(obj, key) {
  for(var key in obj) {
    fn(obj[key], key)
  }
}
fn(obj, 'base');
```
throw error: 

TypeError:  Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null.

my enviorment: `@babel/core:7.8.7, @babel/types:7.8.7,@babel/generator:7.8.7`.

Now, I fix it as:

```js
let obj = {base:{a:1}, other: {b:2}}
function fn(obj, key) {
  for(let key in obj) {
    fn(obj[key], key)
  }
}
fn(obj, 'base');
```

or like this:

```js
let obj = {base:{a:1}, other: {b:2}}
function fn(obj, key) {
  for(var key2 in obj) {
    fn(obj[key2], key2)
  }
}
fn(obj, 'base');
```

Is it a bug with V7.8.7 or just change rules?

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/issues/11231

**Comment by nicolo-ribaudo** [comment]
This will be fixed in the next patch release.
