### ISSUE TITLE
Fat arrow function and this scoping

### ISSUE THREAD

**Issue by hokkos** [babel/babel#1127]
Hi,
a reddit user [reported](http://www.reddit.com/r/webdev/comments/30wwgk/an_overview_of_javascript_in_2015_ecmascript_6/cpwpoor) this example that supposedly breaks fat arrow function and this scoping :

````javascript
var __slice = Array.prototype.slice;

var extendWithFunc = function (fn, obj) {
  return fn.apply(obj, __slice.call(arguments, 2));
};

var myExtend = () => {
  this.newData = __slice.call(arguments, 0);
  return this;
};

//this will add to the global object NOT the object you expect
//more importantly, it will run one way after Babel compilation
//and another way in FF with real ES6 scoping rules
var newObj = extendWithFunc(myExtend, {some: "object"}, "a", "b", "c");
````

See the [full explanation here](http://www.reddit.com/r/webdev/comments/30wwgk/an_overview_of_javascript_in_2015_ecmascript_6/cpwxoho).

**Comment by fkling** [comment]
That's how arrow functions work. It's a bug in Firefox. [From the spec about `.apply`](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function.prototype.apply):

> If func is an arrow function or a bound function then the thisArg will be ignored by the function [[Call]] in step 6.

**Comment by fkling** [comment]
I deleted my previous comment because I may have misunderstood the issue. What exactly is the issue? How does Babel behave incorrectly?

**Comment by fkling** [comment]
Ah I guess the problem is whoever created the example assumed that this code is executed as "script". Babel assumes that every file it gets fed is a *module*. Modules have their own scope and `this` is undefined.

**Comment by sebmck** [comment]
Please see the [FAQ](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-).
