### ISSUE TITLE
SourceType script and useBuiltIns

### ISSUE THREAD

**Issue by irbian** [babel/babel#11270]
**Current Behavior**
Hi! I´m new to Babel so maybe I´m approaching this issue in a wrong way but,

We have useBuiltIns that analyzes our code and load the polyfills needed
And we have sourceType script, where "Setting the correct sourceType can be important because having the wrong type can lead to cases where Babel would insert import statements into files that are meant to be CommonJS files"

So... I was expecting that if I use both, the needed polyfills would be added to the global spacer, or something on that lines

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const presets = [
    [
        "@babel/preset-env"
        ,
        {
            useBuiltIns: "usage",
            debug: true,
            modules: false
        }
    ]
];

const sourceType = "script";

module.exports = { presets, sourceType };
```

**Environment**

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 6.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 3.10.10 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gulp-babel: ^8.0.0 => 8.0.0
```
- Babel version(s): 7.8.4
- Node/npm version: Node v6.17.1 / npm 3.10.10
- OS: Windows 10
- Monorepo: no idea
- How you are using Babel: gulp-babel

**Comment by nicolo-ribaudo** [comment]
When using `sourceType: "module"` babel will inject imports; when using `sourceType: "script"` it will inject `require()` calls (which are supported in CommonJS scripts).

**Comment by irbian** [comment]
But require is not supported on the browser, I would need something like webpack or babelify, and the codebase is not prepared for that

**Comment by nicolo-ribaudo** [comment]
> So sourceType "script" doesn´t mean necesarily "browser"?

Exactly. Before the introduction of ECMAScript modules (`import`/`export`), everything was a script: both the JavaScript you run in the browser and the JavaScript you run in mode.

Unfortunately, there are only two (*) standard systems to import files _from another JS file_: `require` (which only works in some scripts) and `import` (which only works in some modules).

If you can't use native ECMAScript modules and you can't use CommonJS's `require`, I suggest directly loading a polyfill (for example, `core-js-bundle`, or `es6-shim`) using a `<script>` tag.
