### ISSUE TITLE
Invalid assignment order introduced in v7.8.0

### ISSUE THREAD

**Issue by shesek** [babel/babel#11278]
## Bug Report

**Current Behavior**
The code below results in incorrect assignment order.

**Input Code**

```js
function F({ a, ...O }, b = O){}
```

Which transplies to:

```js
function F(_ref) {
  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : O;

  var a = _ref.a,
      O = _objectWithoutProperties(_ref, ["a"]);
}
```

**Expected behavior/code**
`O` should be assigned before `b`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

None

**Environment**

```
- Babel version(s): v7.8.7
- Node/npm version: Node 10.18.0
- OS: Linux
- Monorepo: no
- How you are using Babel: cli
```

**Additional context**

It appears like this bug was introduced in v7.8.0, downgrading back to v7.7.7 solved it for me.

I'm not able to reproduce this in the web REPL for some reason, but I was able to using this:

```
$ mkdir /tmp/assign-bug-test && cd /tmp/assign-bug-test
$ npm init -y && npm install @babel/cli@7.8.4 @babel/core@7.8.7 @babel/preset-env@7.8.7
$ echo 'function F({ a, ...O }, b = O){}' | babel --presets @babel/preset-env --no-babelrc
```

And here's how it looks with v7.7.7:

```
$ npm install @babel/cli@7.7.7 @babel/core@7.7.7 @babel/preset-env@7.7.7
$ echo 'function F({ a, ...O }, b = O){}' | babel --presets @babel/preset-env --no-babelrc

function F(_ref) {
  var a = _ref.a,
      O = _objectWithoutProperties(_ref, ["a"]);

  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : O;
}
```

**Comment by JLHwung** [comment]
As a workaround you can instruct `transform-parameters` to run before `preset-env`
```json
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    "@babel/plugin-transform-parameters"
  ]
}
```
The regression introduced at 7.8.0 relates to plugin orders of `transform-parameters` and `proposal-object-rest-spread`.

However, restoring the plugin orders does not fix it for all. when preset-env is targeting to `Chrome 51`, only `proposal-object-rest-spread` will be enabled. The following snippet
```js
function F({ a, ...O }, b = O){}
```
will be transformed to
```js
function F(_ref, b = O) {
  var a = _ref.a,
      O = _objectWithoutProperties(_ref, ["a"]);
}
```
which is incorrect.

**Comment by shesek** [comment]
Thanks for the swift response and fix, cheers!
