### ISSUE TITLE
[@babel/plugin-proposal-decorators] should also return the class name

### ISSUE THREAD

**Issue by wvq** [babel/babel#11275]
When use a decorator, like: 
```
@SomeDecorator
class Todo {
	hello() {}
}
```
will receive a descriptor:
```
Object [Descriptor] {
  kind: 'class',
  elements: [
    Object [Descriptor] {
      kind: 'method',
      key: 'hello',
      placement: 'prototype',
      descriptor: [Object]
    }
  ]
}
```
The class name 'Todo' does not in the Descriptor, sometimes it's useful.
For example,  logger which class do somethings.

**Comment by nicolo-ribaudo** [comment]
The version of the proposal implemented in Babel didn't include the class name in the metadata passed to the decorator (actually, no version ever did).

You can use a `finisher`, which receives as a parameter the class, and then get `Class.name`:

```js
@dec
class A {}

function dec(desc) {
  return {
    ...desc,
    finisher(Class) {
      alert(Class.name);
    }
  }
}
```
