### ISSUE TITLE
Private Name in the left ForOfStatement is not transformed

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11272]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
The following snippet, when transformed via preset-env and stage-3 preset, will throw
```
Property left of ForOfStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got "CallExpression"
```

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oGIAOBuF0C2AFAJSK6oBmA9gE7QEAuAFgJYQB0m0l50A2gLpEcqAL5IRQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-3%2Cenv&prettier=false&targets=&version=7.8.7&externalPlugins=)

```js
class C {
  #p;
  m() {
    for (this.#p of []);
  }
}
```

**Expected behavior/code**
It should be transformed into something like
```js
// helpers is omissioned
var C = /*#__PURE__*/function () {
  function C() {
    _classCallCheck(this, C);

    _p.set(this, {
      writable: true,
      value: void 0
    });
  }

  _createClass(C, [{
    key: "m",
    value: function m() {
      for (var _i = 0, _arr = []; _i < _arr.length; _i++) {
        i = _arr[_i];
        _classPrivateFieldSet(this, _p, i);
      };
    }
  }]);

  return C;
}();
```

**Possible Solution**

As Justin noted, we can fix it by detecting such patterns in `@babel/helper-member-expression-to-functions`, so babel will apply `destructureSet` private name handler, which will return a member expression -- a valid LHS.

https://github.com/babel/babel/blob/1ba41f208430bdf382b75b56e9aad7436ca522ad/packages/babel-helper-member-expression-to-functions/src/index.js#L110

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch`
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-plugin-proposal-class-properties` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Additional context/Screenshots**
This issue is likely due to plugin ordering: the `private-class-properties` runs before `for-of-transforms` after `this.#p` is transformed to helper calls which is not a valid LHS, the for-of transforms throws on unsupported for-of left.

**Comment by jridgewell** [comment]
Looks like we just need to use the `destructureSet` transform when inside of the `init`.

**Comment by reznord** [comment]
I would be happy to pick this one up.

**Comment by jridgewell** [comment]
How's this going @reznord?

**Comment by reznord** [comment]
Hey, had a rough last week. I’ll ge getting on this issue today. Sorry for the delay

**Comment by jridgewell** [comment]
No problem! This isn't to make you feel guilty, I just want to avoid situation where you're stuck and haven't asked for help. Take the time you need, especially with all circumstances going on.

**Comment by AjayPoshak** [comment]
@JLHwung I would like to take it up.

**Comment by reznord** [comment]
Hey sorry @JLHwung, I can't pick this up right now. Dealing with some personal issues.

Apologies for not getting back on this issue.

**Comment by wlawt** [comment]
hi @jridgewell ! Is the `init` being referred to the one in the helper-member-expression-to-functions file? thanks!

**Comment by JLHwung** [comment]
@wlawt Yep we should check such patterns in https://github.com/babel/babel/blob/36f9798f429d596c0f1efaf09570cd5396f37bd3/packages/babel-helper-member-expression-to-functions/src/index.js#L339-L355

**Comment by wlawt** [comment]
ok, just to clarify we want to check for/add more patterns to resolve this `["VariableDeclaration","LVal"]` from being called the wrong type?

**Comment by JLHwung** [comment]
@wlawt I am not sure I can follow the context of `["VariableDeclaration","LVal"]`. Are you referring to definitions in the `@babel/types`?

The check I mentioned above detects patterns like `// { KEY: MEMBER } = OBJ`, etc, where the `path` refers to `MEMBER` and `parentPath` refers to the `{ KEY: MEMBER }`. We are now going to support `for ( MEMBER of ARR)`, you can check if the `parentPath` is a `ForXStatement`, which covers both `for-in` and `for-of`.

Tip: you can also get yourself familiar with Babel AST on https://astexplorer.net/.
