### ISSUE TITLE
`object-rest-spread` does not transpile correctly when binding is referenced in param initializer

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11281]
## Bug Report

- [ ] I would like to work on a fix!

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwBAhgNGB08HkwF8YCMwF4wJgYy0gEosA-MEZIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.8.7&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.8.3%2C%40babel%2Fplugin-external-helpers%407.8.3)

```js
({ a, ...O }, b = O, c = a) => {}
```
**Current Behavior**
The code above is transformed to
```js
(_ref, b = O, c = a) => {
  let {
    a
  } = _ref,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
};
```
where initializers `b = O` and `c = a` no longer refers to the destructured params. 

**Expected behavior/code**
It should transformed to
```js
(function (_ref) {
  let { a } = _ref,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : O;
  var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : a;
});
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": { "@babel/proposal-object-rest-spread" }
}
```

**Environment**: REPL

**Possible Solution**
I haven't come up with a simple solution. Suggestions are welcome.

Solution 1: Fall back to `transform-parameters` when such pattern is detected

i) A function param declarator contains a RestElement.
ii) The declarator is also referenced by another params' initializers.

This solution will downgrade unnecessary codes, i.e.
```js
({ a, ...O }, b = 2, c = O) => {}
```
will be transformed to
```js
(function (_ref) {
  var a = _ref.a,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 2;
  var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : O;
});
```
even when `b = 2` is supported on the target platform.

Solution 2: Extract `convertSingleParam` from `convertParams` defined in `transform-parameters`, apply `convertSingleParam` if one of params satisfies the pattern mentioned above. 

This solution should prevent downgrading the code as much as possible. i.e.
```js
({ a, ...O }, b = 2, c = O) => {}
```
should be transformed to
```js
(function (_ref, b = 2) {
 let { a } = _ref,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
   var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : O;
});
```

**Additional context/Screenshots**
This issue is discovered when I am investigating #11278.

**Comment by TrejGun** [comment]
is it valid to use number as rest param?

**Comment by JLHwung** [comment]
@TrejGun In `({ a, ...O }, b = 2, c = O) => {}`, the rest element is `...O` while `2` is the initializer of param `b`. It may looks like `{ a, ...O }, b = 2, c = O` is a big destructuring param but it is not. 😄

**Comment by TrejGun** [comment]
i mean part `{a, ...0}` ,`0` (zero) a not valid name for variable. 
in other words you can't do `const 0 = 0`
why it should be possible with destruction?

**Comment by vedantroy** [comment]
This issue seems interesting, I'll try fixing it.

@TrejGun I tried evaluating a simple case and got this:

```
let f = ({ a, ...0 }, b = 0, c = a) => {
    console.log(a)
    console.log(0)
    console.log(b)
    console.log(c)
}
f({a: 'hello', b: 'world', e: '!'})
```
outputs 
```
hello
0
{ b: 'world', e: '!' }
hello
```

**Comment by vedantroy** [comment]
@JLHwung Is there a function that acts as the opposite of `getBindingIdentifiers`. Context: I need to get the names of all the default initializes, to see if they reference a variable declaration in a RestElement.

Example
```
({...b}, a = b) => {...}
```
I need to know that the right-side of `a =` is `b`, so I can transform the parameter.

**Comment by vedantroy** [comment]
@JLHwung, what would happen with solution 2 under the following scenario:

```
({ a, ...S }, b = S, c = 2) => {}
```
In this case, you must keep `b` in the parameters of the function, so `c = 2` is in the right place.
```
(function (_ref, b = S, c = 2) {
   let { a } = _ref, S = babelHelpers.objectWithoutProperties(_ref, ["a"]);
   var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[2] : S;
});
```
However, this will throw a `S is not defined` error. Is this a solution?
```
(function (_ref, b = undefined, c = 2) {
   let { a, ...S} = _ref
   var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[2] : S;
});
```
