### ISSUE TITLE
@babel/core 7.8.8 not available on npm?

### ISSUE THREAD

**Issue by Friksel** [babel/babel#11286]
Trying to update @babel packages to my surprise npm doesn't have a 7.8.8 version. I would expect to have it though, as @babel here has the 7.8.8 released 7 days ago and as core seems to be a part of the full @babel repo I would expect it to have the same version. 

Should core have a 7.8.8 version? If so; is the 7.8.8 core package not pushed to npm or is there no changed code or something else I am missing here?

**Comment by nicolo-ribaudo** [comment]
> is the 7.8.8 core package not pushed to npm or is there no changed code 

It's that! Since this monorepo contains ~150 packages, we have found that publishing all of them together too often causes problems. For this reason, we only publish packages whose source has changed.

**Comment by Friksel** [comment]
Ah, that makes sense. Thanks @nicolo-ribaudo
