### ISSUE TITLE
7.9.0: TS regression with import type as an identifier

### ISSUE THREAD

**Issue by hzoo** [babel/babel#11291]
## Bug Report

Reported via Twitter DM, related to https://github.com/babel/babel/pull/11053

**Current Behavior**

Throws an error with an import with identifier type.

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=Last%201%20Chrome%20Version&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBDAnmApnAZlCI4HJ0QS4DcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ctypescript&prettier=false&targets=&version=7.9.0&externalPlugins=)

```js
import type from 'foo';
```

as opposed to

```js
import type T from './mod';
import type { A, B } from './mod';
import type * as Types from './mod'; 
```

Guess:

We are assuming the check for `type` is the type word vs. an identifier named type so we need to check that first (like if `from` occurs after or something like that)

https://github.com/babel/babel/blob/bb6a1580d208e57f5a75b9a4e5df398837936f15/packages/babel-parser/src/plugins/typescript/index.js#L1869-L1870

**Comment by kaicataldo** [comment]
I'm working on this :)

**Comment by DanielRosenwasser** [comment]
CC @andrewbranch
