### ISSUE TITLE
7.9.0 Regression with React preset and pragma defaults

### ISSUE THREAD

**Issue by hzoo** [babel/babel#11294]
## Bug Report

Via https://github.com/zeit/next.js/issues/11230 and on Slack
with the error (error coming from https://github.com/babel/babel/pull/11126)

**Input Code**

Error: `transform-react-jsx: pragma has been set but pragmaFrag has not been set`

```js
import React from 'react';
const D = <></>;
```

```json
{
  "presets": [["@babel/preset-react", {
    "pragma": "__jsx"
  }]]
}
```

We removed the defaults in the preset when refactoring in https://github.com/babel/babel/pull/11154 and https://github.com/babel/babel/pull/11126

**Comment by Ailrun** [comment]
As I mentioned in https://github.com/babel/babel/pull/11126#pullrequestreview-378810819, this issue blocks `@emotion/babel-preset-css-prop` and `gatsby-plugin-emotion` too. I hope #11295 merged as soon as possible (I understand it requires tests though...)

**Comment by existentialism** [comment]
@Ailrun it's going out very soon!

**Comment by Ailrun** [comment]
@existentialism Thank you for such a quick response! I'm so glad it will be soon.

**Comment by nicolo-ribaudo** [comment]
@Ailrun I'll release when Travis finishes on master.

**Comment by Ailrun** [comment]
Thank you all for hard work! I appreciate it a lot :)
