### ISSUE TITLE
`babel.buildExternalHelpers` with empty array, includes all helpers.

### ISSUE THREAD

**Issue by rwjblue** [babel/babel#1129]
I have been testing the 5.0.0-beta versions with Ember's build system, and it seems that calling `babel.buildExternalHelpers` with an empty array actually includes all helpers when I would expect it to include none.

Repro:

```javascript
var babel = require('babel');

var neededHelpers = [];

var helperText = babel.buildExternalHelpers(neededHelpers);
console.log(helperText);
```

**Comment by sebmck** [comment]
Grrr, looks like this was present in [4.x](https://github.com/babel/babel/blob/v4.7.16/src/babel/tools/build-external-helpers.js#L55) too. I'm planning on pushing the 5.0.0 release shortly so stay tuned.
