### ISSUE TITLE
Regression in plugin-transform-for-of 7.9.0

### ISSUE THREAD

**Issue by ptomato** [babel/babel#11301]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**
Starting with 7.9.0, Babel seems to output ES6 code (method definition shorthand) when transpiling for-of loops, where it didn't before. This breaks if you are using uglify to subsequently process that code, because uglify only handles ES5 code.

Reporting a new bug because this doesn't seem to be covered in any of the other threads on 7.9.0 regressions.

Error log from building the toy project below:
```
$ npm run build

> testbug@1.0.0 build /redacted
> rollup -c rollup.config.js


index.js → bundle.js...
  54 |         err;
  55 |     return {
> 56 |       s() {
     |       ^ Unexpected token: punc «(»
  57 |         it = o[Symbol.iterator]();
  58 |       },
  59 | 
[!] (plugin uglify) Error: Unexpected token: punc «(»
SyntaxError: Unexpected token: punc «(»
    at JS_Parse_Error.get (eval at <anonymous> (/redacted/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:69:23)
    at reportError (/redacted/node_modules/jest-worker/build/workers/processChild.js:107:11)
    at reportClientError (/redacted/node_modules/jest-worker/build/workers/processChild.js:87:10)
    at execFunction (/redacted/node_modules/jest-worker/build/workers/processChild.js:157:5)
    at execHelper (/redacted/node_modules/jest-worker/build/workers/processChild.js:139:5)
    at execMethod (/redacted/node_modules/jest-worker/build/workers/processChild.js:143:5)
    at process.<anonymous> (/redacted/node_modules/jest-worker/build/workers/processChild.js:64:7)
    at process.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Input Code**

**package.json**:
```json
{
  "name": "testbug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rollup -c rollup.config.js"
  },
  "author": "Philip Chimento <pchimento@igalia.com>",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "rollup": "^2.1.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-uglify": "^6.0.4"
  }
}
```

**index.js**:
```js
for (const prop of {})
  ;
```

**rollup.config.js**:
```js
import babel from 'rollup-plugin-babel';
import { uglify } from 'rollup-plugin-uglify';

export default {
  input: "index.js",
  output: {
    name: "test",
    file: "bundle.js",
    format: "umd"
  },
  plugins: [
    babel({
      presets: ["@babel/preset-env"]
    }),
    uglify()
  ]
};
```

**Expected behavior/code**
It's expected that this pipeline would continue to work as it did before upgrading babel to 7.9.0. Pinning `@babel/plugin-transform-for-of` to 7.8.6 (using e.g. npm-force-resolution) eliminates the error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
See above

**Environment**

```
  System:
    OS: Linux 5.4 Fedora 31.20200117.0 (Workstation Edition) 31.20200117.0 (Workstation Edition)
  Binaries:
    Node: 12.16.1 - ~/.local/bin/node
    npm: 6.14.2 - ~/.local/bin/npm
  npmPackages:
    @babel/core: ^7.9.0 => 7.9.0 
    @babel/preset-env: ^7.9.0 => 7.9.0 
    rollup-plugin-babel: ^4.4.0 => 4.4.0 
```

**Possible Solution**

It looks like the regression was introduced in https://github.com/babel/babel/commit/59976680df6b471a50972aaecd4daea95695b410.
As a workaround, pin `@babel/plugin-transform-for-of` to 7.8.6. The solution would be to use ES5 syntax in the new code introduced in the commit that I linked above. Will prepare a PR shortly.

**Additional context/Screenshots**
None

**Comment by nicolo-ribaudo** [comment]
Thanks for the report! I was careful not to use es6 syntax in the new helper, but apparently not careful enough 😢
