### ISSUE TITLE
// comments in anonymous functions break React code

### ISSUE THREAD

**Issue by jakub-gonet** [babel/babel#11304]
**I'm submitting a bug report**

**Webpack Version:**
4.42.0

**Babel Core Version**:
7.9.0

**Babel Loader Version**:
8.1.0

**Please tell us about your environment:**
OSX 10.14

**Current behavior:**
After running yarn build in create-react-app following code transpiles to wrong JS code:
```js
import React from "react";

function App() {
  return (
    <div className="App">
      <A
        render={() => (
          //test
          <B />
        )}
      />
    </div>
  );
}

const A = ({ render }) => {
  return <>{render()}</>;
};

const B = () => {
  return <p>bbbbbbb</p>;
};

export default App;
```

Transpiled and packed:
```
function App(){return/*#__PURE__*/react_default.a.createElement("div",{className:"App"},/*#__PURE__*/react_default.a.createElement(App_A,{render:function render(){return/*#__PURE__*/ //test <-----------------------
react_default.a.createElement(App_B,null);}}));}var App_A=function A(_ref){var render=_ref.render;return/*#__PURE__*/react_default.a.createElement(react_default.a.Fragment,null,render());};var App_B=function B(){return/*#__PURE__*/react_default.a.createElement("p",null,"bbbbbbb");};/* harmony default export */ var src_App = (App);
```
(arrow added)
`render()` has dangling `return` (line break after comment), so JS adds semicolon there - function returns undefined.

When setting `compact: false` in loader options this behavior isn't observed

**Expected/desired behavior:**

babel-loader should keep parens in arrow functions, following code is valid JS
```js
x = () => (
// TEST
5
);
```

* Minimal demo
Here's ejected react-create-app with reproduction
https://github.com/jakub-gonet/babel-loader-comment-bug

Run `yarn build && serve -s build` (assuming serve is installed)

When changing compact to false in `webpack.config.js#351` it works correctly

EDIT:

```js
function App() {
  return (
    <div className="App">
      {(() => (
        //test
        <span>test</span>
      ))()}
    </div>
  );
}
```
also reproduces this issue.

**Comment by nicolo-ribaudo** [comment]
Smaller reproduction:
```js
const code = `
() => (
  //test
  <B />
);
`;

const out = babel.transformSync(code, {
  configFile: false,
  plugins: [
    require("@babel/plugin-transform-react-jsx"),
    require("@babel/plugin-transform-arrow-functions"),
  ],
  compact: true,
});

console.log(out.code);
```

**Comment by codex-zaydek** [comment]
I noticed this in my own code…I thought I was going crazy. I have the following code:

```
React.useLayoutEffect(() => {
	const { Provider } = EditorContext
	ReactDOM.render(
		<Provider value={state}>
			{state.data.map(({ type: Type, ...each }) => (
				// NOTE: props.children (on any component) cannot
				// be an object; rename to data
				<Type key={each.id} {...{ ...each, children: undefined }} data={each.children} />
			))}
		</Provider>,
		ref.current,
	)
```

In development — no problem. In production, it’s basically a no-op and nothing renders. Simply removing the `NOTE` comment fixed my problem.
