### ISSUE TITLE
Pure identifier breaks JSX rendering when using istanbul and auxiliaryCommentBefore option

### ISSUE THREAD

**Issue by carpie** [babel/babel#11312]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
I ran into an issue when running Jest tests with coverage enabled with Babel 7.9.1 where I would get the failure `Nothing was returned from render`.  This only happened when `--coverage` was passed to Jest.

Digging deeper, I learned that, when `istanbul` plugin is active, and the `auxiliaryCommentBefore` config option is used, transpiling a JSX function component looks something like this:

```js
const Foo = () => {
  /* foobar */
  cov_yolaofdup().f[0]++;
  cov_yolaofdup().s[1]++;
  return /*#__PURE__*/
  /* foobar */
  React.createElement(
  /* foobar */
  "div",
  /* foobar */
  null,
  /* foobar */
  "Hi");
};
```
The `return` is returning nothing in this case due to missing parentheses.

If the `auxiliaryCommentBefore` option is not used, working code is generated.
```js
const Foo = () => {
  cov_yolaofdup().f[0]++;
  cov_yolaofdup().s[1]++;
  return /*#__PURE__*/React.createElement("div", null, "Hi");
};
```
Sadly, Jest forces this option on: https://github.com/facebook/jest/blob/master/packages/babel-jest/src/index.ts.

Babel 7.8.3 works in that it wraps the return arguments in parens.  I tracked the missing parens down to https://github.com/babel/babel/blob/master/packages/babel-generator/src/printer.js#L286.  I don't understand the `pure` use cases enough to propose a fix however.

**Input Code**
Here is a minimal sample illustrating the issue: https://gitlab.com/carpie/babel-render-bug
`npm ci && npm start` will just invoke babel on a simple component demonstrating the issue.

**Expected behavior/code**
Expected valid JSX conversion. See above for details.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  presets: [ '@babel/preset-react' ],
  plugins: [ 'istanbul' ],
  auxiliaryCommentBefore: ' foobar '
}
```

**Environment**

```
  System:
    OS: Linux 4.15 Linux Mint 19 (Tara)
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    @babel/preset-react: ^7.9.1 => 7.9.1 
    babel-plugin-istanbul: ^6.0.0 => 6.0.0 
```
**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by weareoutman** [comment]
I ran into the same issue. It seems to be introduced by #11126 .

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/11306, I will release in one hour.
