### ISSUE TITLE
[preset-typescript] Type annotations are not removed for private fields

### ISSUE THREAD

**Issue by Lodin** [babel/babel#11310]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**
When `@babel/preset-typescript` is used along with `@babel/plugin-syntax-class-properties` , it does not remove type annotations for private fields and methods.

**Input Code**
- REPL or Repo link if applicable:
[Private fields typings - Runkit](https://runkit.com/lodin/private-fields-typings)

```js
class Foo {
  #bar: string = 'baz';
}
```

**Expected behavior/code**
A pure JS code that can be executed in the modern environment. No Typescript annotations should left.

```js
class Foo {
  #bar = 'baz';
}
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: no (inline configuration)

```js
{
  presets: [require('@babel/preset-typescript')],
  plugins: [
    require('@babel/plugin-syntax-class-properties'),
  ]
}
```

**Environment**
- Babel version(s): 7.9.0
- Node/npm version: Node 13.5.0 / npm unknown (Runkit)
- OS: unknown (Runkit; probably, Linux)
- Monorepo: no
- How you are using Babel: `babel.transform()`

**Possible Solution**
I assume that it happens because of code that starts at [line 327](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/src/index.js#L327). There are checks only for class property and class method but not for class private property and class private method.

The strange thing is that for a private method everything works correct though it fails for a private property.

**Comment by nicolo-ribaudo** [comment]
> I assume that it happens because of code that starts at line 327 . There are checks only for class property and class method but not for class private property and class private method.

Correct!

> The strange thing is that for a private method everything works correct though it fails for a private property.

For private methods it's working because params/return types are handled by a generic `Function` visitor.
