### ISSUE TITLE
Conditional transcompiling based on statistics service

### ISSUE THREAD

**Issue by nikitastaf1996** [babel/babel#11311]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**
Let's assume we have a service that can provide statistics of js features support of our userbase.Something like this.
`stats:{
"spread-operator":89}`
Which means that 89 percent of our users support spread operator.
**Describe the solution you'd like**
Add to the Babel config something like this:
`stats{
service:"stats.js",
percentage:{
all:90}}`
Based on data from service and config we can stop transcompiling certain features whenever they reach threshold set in config.

**Comment by nicolo-ribaudo** [comment]
How is this different from using browserslist with custom stats?
