### ISSUE TITLE
Publish change log to releases

### ISSUE THREAD

**Issue by nhunzaker** [babel/babel#1132]
I realize it's one more thing to do when you release a new version, but it would make it so that those subscribed to releases could see the change set from their RSS reader. 

I would love this, though I seriously question how many people would find it useful. Still, I would love this.

**Comment by sebmck** [comment]
Releases are pushed automatically when I run `$ make publish` and this would require manual intervention. The [CHANGELOG](https://github.com/babel/babel/blob/master/CHANGELOG.md) is already extremely accessible.
