### ISSUE TITLE
Inserted identifier clashes with existing identifier from the inner scope

### ISSUE THREAD

**Issue by Andarist** [babel/babel#11320]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**

Inserted identifier clashes with the existing one **if** the scope gets crawled before generating the inserted UID.

**Input Code**
```js
require('@babel/core').transform(`

  export default () => {
    var _jsx;
    return <div />;
  };

`, {
  configFile: false,
  babelrc: false,
  plugins: [api => ({ visitor: { Program(p) { p.scope.crawl() } } })],
  presets: [['@babel/preset-react', { runtime: 'automatic' }]],
}).code
```

**Expected behavior/code**
actual vs expected
```diff
-import { jsx as _jsx } from "react/jsx-runtime";
+import { jsx as _jsx2 } from "react/jsx-runtime";
export default (() => {
  var _jsx;

-  return /*#__PURE__*/_jsx("div", {});
+  return /*#__PURE__*/_jsx2("div", {});
});
```

**Babel Configuration**

```js
{
  configFile: false,
  babelrc: false,
  plugins: [api => ({ visitor: { Program(p) { p.scope.crawl() } } })],
  presets: [['@babel/preset-react', { runtime: 'automatic' }]],
}
```

**Environment**

Babel 7.9, the rest is quite irrelevant as the issue is not env-specific and is easy to reproduce.

**Comment by nicolo-ribaudo** [comment]
This might be a bug in `@babel/helper-module-imports`, or in the logic used to collect all the already used identifiers. I don't think that it lives in the jsx helper.
