### ISSUE TITLE
_createSuper is not defined

### ISSUE THREAD

**Issue by milolu** [babel/babel#11336]
## Bug Report

**Current Behavior**
if you define two class in one js file, will error
Uncaught ReferenceError: _createSuper is not defined

**Input Code**
- REPL or Repo link if applicable:

```js
class A extends React.Component {
}
export default class B extends React.Component {
}
```

**Expected behavior/code**
update dependencies

**Environment**

- @babel/plugin-transform-classes@7.9.2

**Possible Solution**

**Additional context/Screenshots**
![image-20200326141901583](https://tva1.sinaimg.cn/large/00831rSTly1gd7b2t1nnvj317g05ogn5.jpg)

**Comment by nicolo-ribaudo** [comment]
Could you try updating `@babel/core` to at least 7.5.5? I think that error is caused by a but we fixed long time ago (https://github.com/babel/babel/pull/10208).

**Comment by nicolo-ribaudo** [comment]
@ulrichb This bug should only happen when using `@babel/core` <7.5.5, but CRA uses 7.9.0.

Could you run `npx nls why @babel/core` and post the output?

**Comment by ulrichb** [comment]
Okay, I had a second package which depended on @babel/core (`jest`) and therefore indeed `7.4.4` got resolved. After re-installing _both_ `jest` and `react-scripts`, now `7.9.0` got resolved.

Result: Now I get even earlier a false-positive [_Module parse failed: Cannot use keyword 'await' outside an async function_](https://github.com/facebook/create-react-app/issues/8707#issuecomment-603212499) error :(

**Comment by nicolo-ribaudo** [comment]
@ulrichb I'm sorry for these bugs :frowning_face: 
Can you post an example which reproduces the second error? (Maybe in a new issue)

**Comment by ulrichb** [comment]
@nicolo-ribaudo No prob.

I've boilded the problem down to the following sample:

```TS
async function someAsync(
    factory: () => Promise<string>,
    options: {
        someCallback?: (theSameNameAsTheLocalBelow: number) => void;
    } = {},
): Promise<string> {

    const theSameNameAsTheLocalBelow = await factory();

    return theSameNameAsTheLocalBelow;
}
```

So there seems to be a conflict between the name of the local and the callback typing argument. When renaming one, the error disappears.

BUT: I can only reproduce this in my production app. Not in a fresh CRA, neither in the Babel playground :/

On the positive side: The "_createSuper is not defined" error disappeared with `7.9.0`.

**Comment by telenko** [comment]
Hi,

I'm facing same issue. The first time it appeared when I had such versions in package.json:
`"@babel/core": "7.5.5",
"@babel/cli": "7.6.0",
"@babel/plugin-external-helpers": "7.2.0",
"@babel/preset-env": "7.6.0"`

To solve the issue I've tried to upgrade to the last versions all libraries above:
`"@babel/cli": "7.8.4",
    "@babel/core": "7.9.0",
    "@babel/plugin-external-helpers": "7.8.3",
    "@babel/preset-env": "7.9.0"
`
And also updated my external-helpers script.
But result was same. I've found weird thing (I'm not pretty familiar with helpers API and how they should be used, so sorry if I'm getting wrong) that all helpers like `createClass` are called in the transpiled code like this: `babelHelpers.createClass(...)`, but with `createSuper` it is called just as `_createSuper(...)`. I see that inside of external helpers script createSuper function exists, but transpiled code doesn't refers to babelHelpers variable to reach it.

When I've played some time with it I've got same error with another helper `_createForOfIteratorHelper` with exactly same issue.

Maybe I have incorrect version configuration? Can you please help?

**Comment by nicolo-ribaudo** [comment]
Can you check what `npx nls why @babel/helpers` prints?

Also, those helpers aren't called from `babelHelpers.createSuper` probably because Babel doesn't know which helpers it can safely use from the `babelHelpers` object (it must assume that it is ^7.0.0). You can pass the `"helperVersion": "^7.9.0"` option to the plugin if you want to tell Babel that you are using an up-to-date `babelHelpers` object.
