### ISSUE TITLE
_get helper only allows writable SuperProperties to be called

### ISSUE THREAD

**Issue by michaelficarra** [babel/babel#1133]
Because `_get` has `&& desc.writable`, non-writable methods on the superclass cannot be called through `super.methodName()`.

```js
class A {}
Object.defineProperty(A.prototype, "methodName", {value: function(){}, writable: false});
class B extends A {
  otherMethod() {
    super.methodName(); // fails, but should not
  }
}
```

**Comment by sebmck** [comment]
Not sure why it was like that in the first place. Might have been ported from the super set helper. Fixed as of 5.0.2.
