### ISSUE TITLE
Babel is not building for angular

### ISSUE THREAD

**Issue by faridg18** [babel/babel#11333]
## Bug Report

- [ ] I would like to work on a fix!

Currently when I try to build on linux I get the following error:
 Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it

Although I works fine on macOs 

I've tried doing: 
  "resolutions": { //adding to package.json
    "@babel/preset-env": "^7.8.7"
  },
npm install npm-force-resolutions --save-dev
npm install
npx npm-force-resolutions
npm install
npm run build -- --prod

 but still it fails on linux

**Comment by nicolo-ribaudo** [comment]
What does `npx nls why @babel/preset-env` print?

**Comment by faridg18** [comment]
@nicolo-ribaudo here is the result for npx nls why @babel/preset-env:

  Who required @babel/preset-env:

  eleven-app-frontend > @angular-devkit/build-angular > @babel/preset-env@7.8.3
  eleven-app-frontend > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > @babel/preset-env@7.9.0
  eleven-app-frontend > @nrwl/cypress > @cypress/webpack-preprocessor > @babel/preset-env@7.9.0

**Comment by faridg18** [comment]
UPDATE: Solved it by adding 

 "@babel/compat-data": "~7.8.0" to the dev depencies

**Comment by nicolo-ribaudo** [comment]
Glad that you managed to work around it!

Btw, I have noticed that `@angular-devkit/build-angular` released a new version which doesn't depend on the broken `@babel/preset-env@7.8.3` (https://unpkg.com/browse/@angular-devkit/build-angular@0.901.0/package.json)
