### ISSUE TITLE
Traspiling typescript code coming from node_modules

### ISSUE THREAD

**Issue by marcellomontemagno** [babel/babel#11340]
**Current Behavior**
I receive `SyntaxError` when trying to traspile a valid `.ts` file coming from `node_modules` other files withing the project would be transpiled as expected. I use babel through `babel-loader` providing an `include` rule so it can traverse the path I'm interested in within `node_modules`.

**Input Code**
here a minimal repo to reproduce the issue:
`https://github.com/marcellomontemagno/babel-test`
you should run 
`npm i`
and then
`npm run start`
to reproduce the issue

**Expected behavior/code**
I expect to be able to traspile `foo.ts` because the webpack loader is able to reach that file

**Further info**
- Node/npm version: Node v12.10.0 / npm 6.13.7
- OS: OSX 10.15.2 (19C57)

Thank you very much for the support.

**Comment by JLHwung** [comment]
Please rename `.babelrc.js` to `babel.config.js`, this change file relative config to project-wide config. `.babelrc.js` is only applied to your own module, that said, Babel does not apply `.babelrc.js` to `node_modules/aDependency`.

See [Configuration docs](https://babeljs.io/docs/en/config-files#configuration-file-types) for different configuration types.

**Comment by marcellomontemagno** [comment]
@JLHwung thank you for the prompt reply, renaming the file fixes my issue
