### ISSUE TITLE
Explicitely do not transpile some required modules

### ISSUE THREAD

**Issue by Globegitter** [babel/babel#1134]
Looking at my PR here https://github.com/balderdashy/enpeem/pull/4, or well this branch: https://github.com/Globegitter/enpeem/tree/skip-dry-run-prefix-features

I want to use babel (via `require('babel/register')`) only for my tests, so I can have nice es6/7 syntax for the tests, but the module itself should not get transpiled. This works quite well in theory, the module itself does not get transpiled when someone `npm install`s it, but the tests to transpile the application code. So for example tests work on node 0.10 even though I am using native Promises which only works on node 0.12/io.js 1.x.

If have tried to use the `only` option, see https://github.com/Globegitter/enpeem/blob/skip-dry-run-prefix-features/tests/runner.js#L12, but that is not changing anything in my case.

But to get to the point, I still want to be able to use ES6/7 in my tests, but I want this require: https://github.com/Globegitter/enpeem/blob/skip-dry-run-prefix-features/tests/acceptance/basic-test.js#L8 to be ignored by babel. Is that somehow possible?

**Comment by eventualbuddha** [comment]
As far as I can tell, [this works fine the way you have it in the PR](https://gist.github.com/eventualbuddha/c807401d3d206600392d) (using the `only` option). If you'd like to follow up, please consider using the [gitter room](https://gitter.im/babel/babel) as the issue tracker is reserved for bugs and tasks. Thanks!

**Comment by Globegitter** [comment]
@eventualbuddha I think I found the bug - it is really strange and might be specific to `new Promise` and node 0.10.x

See https://gist.github.com/Globegitter/ee46154b9a1b7506af19

**Comment by sebmck** [comment]
@Globegitter I don't understand that gist, can you elaborate?

**Comment by Globegitter** [comment]
@sebmck Just copied the format of @eventualbuddha's gist. But to replicate that on your machine, there are 3 files, one index.js at root, one index.js in a lot sub folder and one in a tests sub-folder. 
The root level one requires babel and the tests/index.js, which then requires the lib/index.html. 

And you can see that even though it is specified to only transpile files in the tests folder, the Promise throws no error on node 0.10.x. If you remove babel completely (as well as the class which would now throw an error) you can see that node 0.10.x indeed throws an error. 

The gist from @eventualbuddha is pretty similar and correctly throws an error on node 0.10.x as I would expect. 

Hope that clears it up a bit more.

**Comment by sebmck** [comment]
@Globegitter Whatever issue is potentially present would be with core-js not Babel.

**Comment by Globegitter** [comment]
@sebmck But how does it even get that far? Surely if you define `only` or `ignore` babel should not even touch any of these ignored files at all. 

I am going to file a bug at core-js as well, but again, how does core-js even get to touch the file that I specify not to be touched?

**Comment by sebmck** [comment]
@Globegitter Ignoring a file has no control over whether or not the globals that core-js pollutes will be accessed.

**Comment by Globegitter** [comment]
Ahhh ok that explains it a bit further - thanks.
