### ISSUE TITLE
import + anonymous generator function raises AssertionError

### ISSUE THREAD

**Issue by monsanto** [babel/babel#1135]
```
import foo from 'bar';
(function* () {});
```

Compiling this raises `AssertionError: test.js: undefined does not match type Pattern`

**Comment by sebmck** [comment]
Most likely has to do with the new ESTree module AST nodes.

**Comment by sebmck** [comment]
It is. @benjamn is there any way to override existing definitions? It throws an assertion error if I try and do it in [patch.js](https://github.com/babel/babel/blob/master/src/babel/patch.js).

**Comment by topaxi** [comment]
I get the same error for anonymous async functions

**Comment by sebmck** [comment]
@topaxi It wouldn't be from async functions since they don't introduce any new node types.

**Comment by topaxi** [comment]
Well, this one does not work.
http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=import something from 'something'%3B%0A%0Afoo%28async function%28%29 {}%29

**Comment by sebmck** [comment]
@topaxi It's the `import` not the `async` function.

**Comment by sebmck** [comment]
The use of the async function just triggers regenerator to be ran.

**Comment by topaxi** [comment]
I see :)

**Comment by monsanto** [comment]
> The use of the async function just triggers regenerator to be ran.

@sebmck I'm not sure what you mean, are you suggesting that just running regenerator in the presence of an import is enough to trigger the error? Because I don't think that is true, as adding a name to the generator function is enough to fix the error for me.

**Comment by olegafx** [comment]
Got same issue on [generator example](https://babeljs.io/docs/learn-es6/#generators)
> ./src/index.js
Module build failed: AssertionError: /Users/olegafx/code/sandbox/src/index.js: undefined does not match type Pattern
    at Type.Tp.assert (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/types.js:53:16)
    at addPattern (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:220:24)
    at recursiveScanScope (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:167:9)
    at recursiveScanChild (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at NodePath.<anonymous> (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:150:13)
    at NodePath.each (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/path.js:96:22)
    at recursiveScanScope (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:149:14)
    at recursiveScanChild (/Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:214:9)
    at /Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/scope.js:176:13
    at /Users/olegafx/code/sandbox/node_modules/babel-loader/node_modules/babel-core/node_modules/ast-types/lib/types.js:627:18
 @ multi main

**Comment by lightsofapollo** [comment]
yeah I also see this :/

**Comment by KenPowers** [comment]
Same here. I started watching this issue so I could get status updates on when it is fixed.

**Comment by benjamn** [comment]
@sebmck It's definitely possible to override or modify existing definitions. What specifically needs to change here?

**Comment by sebmck** [comment]
@benjamn Actually no, it's a thing with the `ast-types` scope tracking not having support for the latest ESTree module definitions. https://github.com/benjamn/ast-types/blob/master/lib/scope.js#L168

**Comment by benjamn** [comment]
Hmm, this looks like a place where ESTree/acorn and esprima(-fb) disagree. I can make the scope tracking code flexible against all possibilities, but I'd be interested to read any discussions you can point me to that explain why `.imported`/`.local` won out over `.id`/`.name`. That seems like a breaking change for Esprima to take, and I don't see any issues [here](https://github.com/facebook/esprima/issues) about fixing it…

**Comment by sebmck** [comment]
`esprima-fb` is basically dead AFAIK. Perhaps @jeffmo can say more. It hasn't been updated to the ESTree agreed definitions so there's possible quite a few things that are oudated. Related discussion (apologies for so many links, isn't really a single place where this was discussed/agreed on): estree/estree#38 estree/estree#35 estree/estree#11 estree/estree#35

**Comment by benjamn** [comment]
Is there a repo/branch of Esprima that is (closer to) up-to-date than esprima-fb?

**Comment by sebmck** [comment]
The official `master` branch of Esprima maybe. Not sure if it supports all the same ES6 features but the unit tests are [here](https://github.com/jquery/esprima/tree/master/test/fixtures/ES6). If you need an ESTree reference parser then there's also [Espree](https://github.com/eslint/espree) and [Acorn](https://github.com/marijnh/acorn).

**Comment by monsanto** [comment]
Fix works for me. Thanks @benjamn!

**Comment by sebmck** [comment]
Woot, thanks @benjamn!
