### ISSUE TITLE
Fails to parse object division in ternary alternate: `weird ? true : {}/2`

### ISSUE THREAD

**Issue by lydell** [babel/babel#11353]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
Fails to parse two useless but valid pieces of JavaScript.

**Input Code**

[Case 1](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=O4UwlgTgJgBA_DALhAriGAuGBvAvgegCYBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.9.0&externalPlugins=):

```js
weird ? true : {}/2;
```

```
Unterminated regular expression (1:18)
```

[Case 2](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=O4UwlgTgJgBA_DALhAriGAuGBvAvgegCZ8BzAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.9.0&externalPlugins=):

```js
weird ? true : {}/2/g;
```

```
Unexpected token, expected ";" (1:17)
```

Note: When adding parentheses parsing succeeds:

```js
weird ? true : ({}/2);
```

But Babel’s output is:

```js
weird ? true : {} / 2;
```

Which means that Babel cannot parse its output.

Moving `{}/2` to the consequent of the ternary parses:

```js
weird ? {}/2 : true;
```

**Expected behavior/code**
They should parse. For example Node.js, Firefox and TypeScript accept them.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Defaults.

**Environment**

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 13.11.0 - /home/linuxbrew/.linuxbrew/bin/node
    Yarn: 1.22.4 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 6.13.7 - /home/linuxbrew/.linuxbrew/bin/npm
  npmPackages:
    @babel/parser: 7.9.4 => 7.9.4 
    eslint: 6.8.0 => 6.8.0 
    jest: 25.2.3 => 25.2.3 

```

**Comment by lydell** [comment]
Maybe related:

[Case 3 (error)](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYQwRgpsBcAEDeBfA9AJgNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=7.9.0&externalPlugins=):

```js
label: {}/2;
```

```
Unterminated regular expression (1:10)
```

[Case 4 (correct output)](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYQwRgpsBcAEDeBfA9AJmQcwNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=7.9.0&externalPlugins=):

```js
label: {}/2/g;
```

```js
label: {}

/2/g;
```

**Comment by nicolo-ribaudo** [comment]
Isn't the error in Case 3 expected? It's a block statement.

**Comment by lydell** [comment]
> Isn't the error in Case 3 expected? It's a block statement.

You’re right! Updating the comment.

**Comment by oliverdunk** [comment]
Could I take this one? ✋

**Comment by oliverdunk** [comment]
I started to investigate here. It looks like at the `:` symbol, we call [updateContext()](https://github.com/babel/babel/blob/3ce7c2e394f9bbd249600bef3ce04aa3519890fb/packages/babel-parser/src/tokenizer/index.js#L1549). This sets `exprAllowed` to true, causing the binary expression to be interpreted as a regular expression.

I think my next steps are to get more familiar with https://github.com/sweet-js/sweet-core/wiki/design, and how it's implemented in Babel.

**Comment by oliverdunk** [comment]
Just wanted to say that I haven't forgotten about this one. https://github.com/babel/babel/pull/11404 has been taking my focus, but I hope to tackle this soon.
