### ISSUE TITLE
`proposal-logical-assignment` should not assign anonymous function name

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11362]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
The following snippet, after transform will print string `"f"` to the console

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAZg3AUACihA_CgvNArgOwMYAuAlgPY4ICUEA3gL4UB0OIAtgKZA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Cstage-1&prettier=false&targets=&version=7.9.0&externalPlugins=%40babel%2Fplugin-syntax-class-properties%407.8.3)

```js
var f;
console.log((f ??= function() {}).name)
```

**Expected behavior/code**
According to https://tc39.es/proposal-logical-assignment/#sec-assignment-operators-runtime-semantics-evaluation, the anonymous function is not applied with NamedEvaluation, so it should print an empty string to the console.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": ["@babel/proposal-logical-assignment-operators"]
}
```

**Environment**
REPL.

**Solution**
Transform `f ??= function() {}` to `f = f ?? function() {}` may fix this issue. Or we leave a caveat note that we are not supporting function name in this plugin.

**Comment by arku** [comment]
@JLHwung I would like to take a stab at this issue.
