### ISSUE TITLE
compile Javascript Code (string) and return via http

### ISSUE THREAD

**Issue by GlauberF** [babel/babel#11367]
maybe my question may seem strange, but what I need is to create a call in nodejs, where I send in the body a typescript or javascript code in string format and I get a return compiled in string as well.

Reason:
I have a cms / editor where I can write the code in javascript and save this javascript code in the string format in the database, then use it to render the information on screen.

however I want to create an http call, before saving to the database, go through the compiler and only then send it to the database.

would you have any example of how i can do this?

**Comment by nicolo-ribaudo** [comment]
You can do something like this, using `babel.transformAsync` (or `babel.transformSync`).

```js
const babel = require("@babel/core");
const http = require("http"); 

http.createServer(async function (req, res) {
  let inputCode = await getPostBodyFromRequest(req);
  let compiledCode = await babel.transformAsync(inputCode, {
    configFile: false,
    // your babel config here
  });
  await writeCompiledCodeToDB(req, compiledCode);

  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.write('Done!');
  res.end();
}).listen(8080);
```
