### ISSUE TITLE
babelrc doesn't seem to work

### ISSUE THREAD

**Issue by tleunen** [babel/babel#1137]
I've updated Babel to latest version (5.0.2) and I tested the new configuration file `.babelrc` but it doesn't seem to work.

Let's say I have `.babelrc` like this:
```json
{
  "blacklist": ["es6.classes"],
  "comments": false
}
```
With this js file:
```js
class A {
    constructor() {
        // This is a test
        this.p = 1;
    }
}
```
My output file still has the transformation and the comment. Not sure if I'm missing something.
I did the test on Windows.

**Comment by deepsweet** [comment]
same problem, I can't get it work with `"stage": 1` in `.babelrc`, only with cli `--stage 1`.

**Comment by mistadikay** [comment]
Same here. We have `.babelrc` looking like this:
```json
{
  "optional": "runtime",
  "stage": 1
}
```

And we have an error on object spread:
```js
SyntaxError: lib/ProcessRequire.js: Unexpected token (41:20)
  39 |             if (optName.charAt(0) === '_') {
  40 |                 opts.mods = {
> 41 |                     ...opts.mods,
     |                     ^
  42 |                     [optName]: optVal
  43 |                 };

```

CLI flag `--stage 1` seems to be working normally though

**Comment by sebmck** [comment]
It's because the CLI isn't passing an absolute location to `babel.transform`.

**Comment by sebmck** [comment]
Should be fixed as of 5.0.3, thanks!

**Comment by mistadikay** [comment]
Awesome, thanks!

**Comment by tleunen** [comment]
Great, Thanks! :)
