### ISSUE TITLE
How to target flexbox support?

### ISSUE THREAD

**Issue by emilmuller** [babel/babel#11381]
So I want to support flexbox as a minimum requirement. I find out (through caniuse) that Firefox on Android has a minimum requirement of 68, and that desktop Firefox has a minimum requirement of 52. How can I target that?

As "and_ff" doesn't seem to be supported, and after finding this pull request: https://github.com/babel/babel/pull/10814/commits/f22162aab0cfe0a3e0d2dba9d45b7ca73b37a84d, it would seem that "and_ff" is mapped to "firefox". Why was this done? It cannot be correct because these version numbers **are not in sync at all**.

For example, my FF on my Android (which I just updated) has the version number 68.7.0. My desktop FF has the version number 74.0.1.

I think this is an error.

Kind regards, Emil.

**Comment by nicolo-ribaudo** [comment]
Why are you saying that they are not in sync?

Firefox for Android 68 and Firefox 68 have been released on the same day ([Firefox for Android 68 release notes](https://www.mozilla.org/en-US/firefox/android/68.0/releasenotes/)], [Firefox 68 release notes](https://www.mozilla.org/en-US/firefox/68.0/releasenotes/)).
