### ISSUE TITLE
BABEL_PARSE_ERROR with decorator

### ISSUE THREAD

**Issue by wvq** [babel/babel#11389]
Decorator cann't execute method in chains, only the chains last node can do that.

```javascript
let Decorator = {
  a: {
    b() {
      return (descriptor) => {
        // do something...
      }
    }
  },

  d() {
    return {
      e(descriptor) {
        // do something
      }
    }
  }
}

// it's ok
@Decorator.a.b()
class Todo {}

// will cause error 'BABEL_PARSE_ERROR'
@Decorator.d().e
class Todo2{}

```

**Comment by nicolo-ribaudo** [comment]
Are you using "legacy" decorators or the other implemented version?

**Comment by wvq** [comment]
> Are you using "legacy" decorators or the other implemented version?

Not use legacy option or other implemented version.

package.json :
``` json
{
  "dependencies": {
    "@babel/core": "^7.9.0",
    "@babel/node": "^7.8.7",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/preset-env": "^7.9.0"
  }
}
```

and the .babelrc: 
```json
{
  "presets": ["@babel/preset-env"],
  "plugins": [["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }], ["@babel/plugin-proposal-class-properties"]]
}
```

**Comment by nicolo-ribaudo** [comment]
@wvq In "non-legacy" mode, decorators must be in the form of `foo.bar.baz` or `foo.bar.baz()`. No other expressions are allowed.

This is the version of the proposal implemented in Babel: https://github.com/tc39/proposal-decorators/tree/7fa580b40f2c19c561511ea2c978e307ae689a1b

If you are comfortable with reading the spec text, you can find the syntax [here](https://github.com/tc39/proposal-decorators/blob/7fa580b40f2c19c561511ea2c978e307ae689a1b/spec.html#L93-L108).
