### ISSUE TITLE
Is it possible to use lodash-es instead of lodash?

### ISSUE THREAD

**Issue by OZZlE** [babel/babel#11396]
## Feature Request

I'm going through our main bundle size and I see babel requires `lodash` and another module we have installed requires `lodash-es` which seems to be exactly the same thing except `lodash-es` is lodash converted to ES modules https://www.npmjs.com/package/lodash-es

Would it be possible for babel to only require lodash-es as it's much smaller in size?

It's dependent in the following:

    "@babel/helper-module-imports": {
      "version": "7.8.3",
      "resolved": "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.8.3.tgz",
      "integrity": "sha512-R0Bx3jippsbAEtzkpZ/6FIiuzOURPcMjHp+Z6xPe6DtApDJx+w7UYyOLanZqO8+wKR9G10s/FmHXvxaMd9s6Kg==",
      "requires": {
        "@babel/types": "^7.8.3"
      },
      "dependencies": {
        "@babel/types": {
          "version": "7.8.3",
          "resolved": "https://registry.npmjs.org/@babel/types/-/types-7.8.3.tgz",
          "integrity": "sha512-jBD+G8+LWpMBBWvVcdr4QysjUE4mU/syrhN17o1u3gx0/WzJB1kwiVZAXRtWbsIPOwW8pF/YJV5+nmetPzepXg==",
          "requires": {
            "esutils": "^2.0.2",
            "lodash": "^4.17.13", <--
            "to-fast-properties": "^2.0.0"
          }
        }
      }
    },

    "@babel/helper-module-transforms": {
      "version": "7.8.3",
      "resolved": "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.8.3.tgz",
      "integrity": "sha512-C7NG6B7vfBa/pwCOshpMbOYUmrYQDfCpVL/JCRu0ek8B5p8kue1+BCXpg2vOYs7w5ACB9GTOBYQ5U6NwrMg+3Q==",
      "requires": {
        "@babel/helper-module-imports": "^7.8.3",
        "@babel/helper-simple-access": "^7.8.3",
        "@babel/helper-split-export-declaration": "^7.8.3",
        "@babel/template": "^7.8.3",
        "@babel/types": "^7.8.3",
        "lodash": "^4.17.13" <--
      },

        "@babel/types": {
          "version": "7.8.3",
          "resolved": "https://registry.npmjs.org/@babel/types/-/types-7.8.3.tgz",
          "integrity": "sha512-jBD+G8+LWpMBBWvVcdr4QysjUE4mU/syrhN17o1u3gx0/WzJB1kwiVZAXRtWbsIPOwW8pF/YJV5+nmetPzepXg==",
          "requires": {
            "esutils": "^2.0.2",
            "lodash": "^4.17.13",
            "to-fast-properties": "^2.0.0"
          }
        }

    "@babel/helper-optimise-call-expression": {
      "version": "7.8.3",
      "resolved": "https://registry.npmjs.org/@babel/helper-optimise-call-expression/-/helper-optimise-call-expression-7.8.3.tgz",
      "integrity": "sha512-Kag20n86cbO2AvHca6EJsvqAd82gc6VMGule4HwebwMlwkpXuVqrNRj6CkCV2sKxgi9MyAUnZVnZ6lJ1/vKhHQ==",
      "requires": {
        "@babel/types": "^7.8.3"
      },
      "dependencies": {
        "@babel/types": {
          "version": "7.8.3",
          "resolved": "https://registry.npmjs.org/@babel/types/-/types-7.8.3.tgz",
          "integrity": "sha512-jBD+G8+LWpMBBWvVcdr4QysjUE4mU/syrhN17o1u3gx0/WzJB1kwiVZAXRtWbsIPOwW8pF/YJV5+nmetPzepXg==",
          "requires": {
            "esutils": "^2.0.2",
            "lodash": "^4.17.13", <--
            "to-fast-properties": "^2.0.0"
          }
        }
      }
    },

    "@babel/helper-regex": {
      "version": "7.8.3",
      "resolved": "https://registry.npmjs.org/@babel/helper-regex/-/helper-regex-7.8.3.tgz",
      "integrity": "sha512-BWt0QtYv/cg/NecOAZMdcn/waj/5P26DR4mVLXfFtDokSR6fyuG0Pj+e2FqtSME+MqED1khnSMulkmGl8qWiUQ==",
      "requires": {
        "lodash": "^4.17.13" <--
      }
    },

        "@babel/generator": {
          "version": "7.8.4",
          "resolved": "https://registry.npmjs.org/@babel/generator/-/generator-7.8.4.tgz",
          "integrity": "sha512-PwhclGdRpNAf3IxZb0YVuITPZmmrXz9zf6fH8lT4XbrmfQKr6ryBzhv593P5C6poJRciFCL/eHGW2NuGrgEyxA==",
          "requires": {
            "@babel/types": "^7.8.3",
            "jsesc": "^2.5.1",
            "lodash": "^4.17.13", <--
            "source-map": "^0.5.0"
          }
        },

        "@babel/traverse": {
          "version": "7.8.4",
          "resolved": "https://registry.npmjs.org/@babel/traverse/-/traverse-7.8.4.tgz",
          "integrity": "sha512-NGLJPZwnVEyBPLI+bl9y9aSnxMhsKz42so7ApAv9D+b4vAFPpY013FTS9LdKxcABoIYFU52HcYga1pPlx454mg==",
          "requires": {
            "@babel/code-frame": "^7.8.3",
            "@babel/generator": "^7.8.4",
            "@babel/helper-function-name": "^7.8.3",
            "@babel/helper-split-export-declaration": "^7.8.3",
            "@babel/parser": "^7.8.4",
            "@babel/types": "^7.8.3",
            "debug": "^4.1.0",
            "globals": "^11.1.0",
            "lodash": "^4.17.13" <--
          }
        },

**Comment by nicolo-ribaudo** [comment]
Why are you bundling Babel? It's meant to be used as a build tool, not as part of your app.

**Comment by OZZlE** [comment]
> Why are you bundling Babel? It's meant to be used as a build tool, not as part of your app.

I used `webpack-bundle-analyzer` and it reports lodash to be a big part of our bundle, and from package-lock.json it seems to come from babel.. I cannot see that we are bundling Babel though.. If I compare with for example https://www.valentinog.com/blog/babel/ then this is what we're doing also.

So it seems like either webpack-bundle-analyzer doesn't understand that this is not a part of the generated bundle or we have some module that has lodash in it's own sources files.. I cannot find that however.. so I guess it's the former..

**Comment by OZZlE** [comment]
my bad seems it comes from https://www.npmjs.com/package/react-image-gallery
