### ISSUE TITLE
Where is the acorn in babel-parser?

### ISSUE THREAD

**Issue by jx453331958** [babel/babel#11393]
In the [official document](https://babeljs.io/docs/en/babel-parser#credits) we can see "Heavily based on acorn and acorn-jsx, thanks to the awesome work of RReverser and marijnh.". But I never see the 'acorn' in the babel's source code. So I have some questions:

1. Did we rewrite all the 'acorn' in this project ? 
2. And why we didn't use the 'acorn' as a dependency ?
3. What difference between babel-parser and acorn ? 

I'm so curious about this. Looking forward to your reply.

Thanks for all!

**Comment by nicolo-ribaudo** [comment]
`@babel/parser` was born as a fork of Acorn, but it has been completely rewritten. However, we still use some of it algorithms (for example, to handle expressions precedence).

**Comment by jx453331958** [comment]
> `@babel/parser` was born as a fork of Acorn, but it has been completely rewritten. However, we still use some of its algorithms (for example, to handle expressions precedence).
> 
> Some differences are:
> 
> * `@babel/parser` doesn't support third-party plugins
> * `acorn` only supports Stage 4 proposals
> * They have different AST formats. You can make `@babel/parser` match Acorn's AST by enabling the `"estree"` "plugin".

Thanks! I understand.
