### ISSUE TITLE
npm ERR! notarget No matching version found for @babel/helper-validator-identifier@7.9.5

### ISSUE THREAD

**Issue by darpanrangari** [babel/babel#11391]
### No matching version found for @babel/helper-validator-identifier@7.9.5

**Current Behavior**
Run npm install --save-dev @babel/helper-validator-identifier@7.9.5
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-validator-identifier@7.9.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darpanrangari/.npm/_logs/2020-04-08T09_41_15_890Z-debug.log

**Environment**

- Babel version(s): v7.4.3
- Node/npm version: v10.16.0/ npm: v6.9.0
- OS: macOs High Sierra
- How you are using Babel: cli

**Comment by FlorinPorusniuc** [comment]
I have the same problem

**Comment by darpanrangari** [comment]
I dont need karma-coverage the issue is with @babel/helper-validator-identifier@7.9.5 even if we install with ^ its not downloading the latest 7.9.5

**Comment by FlorinPorusniuc** [comment]
> I dont need karma-coverage the issue is with @babel/helper-validator-identifier@7.9.5 even if we install with ^ its not downloading the latest 7.9.5

I have no issues trying to run npm install --save-dev @babel/helper-validator-identifier@7.9.5 on my local machine but when I do this from jenkins using a registry node config I also get:

 npm ERR! code ETARGET
 npm ERR! notarget No matching version found for @babel/helper-validator-identifier@^7.9.5
 npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
 npm ERR! notarget 
 npm ERR! notarget It was specified as a dependency of '@babel/types'
 npm ERR! notarget

**Comment by darpanrangari** [comment]
I am using a private registry that could be the issue, I tried the same with npm registry and it worked. it can be closed.

**Comment by darpanrangari** [comment]
@FlorinPorusniuc is this specific to the latest publish which was done 15hr ago?

**Comment by kmxcubeathota** [comment]
@darpanrangari we are also facing the same issue.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-validator-identifier@^7.9.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/types'
npm ERR! notarget

**Comment by nicolo-ribaudo** [comment]
7.9.5 has been correctly published to `npm`: https://www.npmjs.com/package/@babel/helper-validator-identifier.

If you are using a proxy for the npm registry (maybe it's used by your company, or you are using it because your country blocks the main npm registry), then it's likely that it has cached the old version of the package and it isn't loading the new one. If you can, try clearing the proxy's cache. Otherwise, you will have to wait until the cache is automatically updated (it might take a few hours, or even days).

If you are not using a proxy, or if it isn't a caching problem, please report the issue to npm (https://github.com/npm/cli/issues/new/choose).

**Comment by bendavidsonku** [comment]
This is definitely still an issue.

**Comment by nicolo-ribaudo** [comment]
This shouldn't have nothing to have with your PC but with some cache between you and npm. Anyway, it's not actionable for us since our packages are correctly published on npm's servers.

**Comment by prashantmaheshwari** [comment]
If you are proxying npmjs site from nexus to save dependencies in your environment, so suggest you to invalidate cache of your repository in nexus and rebuild index. It helped me in past.

**Comment by darpanrangari** [comment]
@prashantmaheshwari  since we are in same team, can you please invalidate the cache so that index can be rebuild?
