### ISSUE TITLE
"use strict" should be inside of module-wrapper-function

### ISSUE THREAD

**Issue by azproduction** [babel/babel#114]
Just to play safe it is better to place `"use strict"` inside function to avoid concat issues in future.

Original

``` js
import {a} from './a.js';
```

Expected

``` js
define(["exports", "./a.js"], function(exports, _a) {
  "use strict";
  var a = _a.a;
});
```

Actual

``` js
"use strict";

define(["exports", "./a.js"], function(exports, _a) {
  var a = _a.a;
});
```

The same is for UMD. 

It is possible to fix it by placing `_moduleFormatter` transformer after `useString`. But I am not sure that it is a good way.

**Comment by jayphelps** [comment]
@sebmck I'm now seeing `"use strict"` outside the `define`. Seemed to have regressed due to https://github.com/babel/babel/commit/7927aa2e189453b9fddd6f30d05722774626102f.

Is this known, intentional, and desired going forward? (causes concat issues in certain cases, as mentioned above)

**Comment by sebmck** [comment]
@jayphelps Yes this was intentional. There were hacks littered throughout the code to do allow for this behaviour that had other consequences such as #828. I'll look into it to see if there's another way though if it's that big of an issue for you.

**Comment by jayphelps** [comment]
@sebmck IMO it would be the expected and best practice, even if it meant at the expense of internal code quality because of the limitations it forces on consumers.

**Comment by sebmck** [comment]
Probably, I'll look into it when I get the chance

On Wednesday, 25 February 2015, Jay Phelps <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> IMO it would be the expected and best
> practice, even if it meant at the expense of internal code quality because
> of the limitations it forces on consumers.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/114#issuecomment-75867982>.
>


-- 
Sebastian McKenzie

**Comment by jayphelps** [comment]
For everyones reference, @sebmck fixed this regression here https://github.com/babel/babel/commit/7d87e52377b74f159a03fa392a6480296efd5432

**Comment by Beldur** [comment]
Thanks a lot!
