### ISSUE TITLE
Typescript: object method with type assertion and spread arguments

### ISSUE THREAD

**Issue by davewasmer** [babel/babel#11400]
## Bug Report

**Current Behavior**
When compiling Typescript, asserting an object's method as some type and immediately invoking it with spread arguments results in calling the method with `.apply(void 0, ...`, which results in an undefined value for `this` inside the method (despite being called on the object).

This does not occur if you drop the type assertion, or if you don't use the spread operator. Only if both are used.

**Input Code**
- [REPL link](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQEw9g5gdARghgJwNYAI4Gc0DsCeBKYKIxCdPIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ctypescript&prettier=false&targets=&version=7.9.0&externalPlugins=)

```js
// using es2015-loose for brevity, but also reproducible with es2015

(dog.bark as any)(...args)
// ^ compiles to `dog.bark.apply(void 0, args)` - wrong

(dog.bark as any)(args)
// ^ compiles to `dog.bark(args);` - correct

(dog.bark)(...args)
// ^ compiles to `(_dog = dog).bark.apply(_dog, args);` - correct
```

**Expected behavior/code**
The method should be invoked with the object as the `this` arg.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Reproducible in the REPL with only es2015 and typescript presets.

**Environment**
N/A - see REPL link

**Comment by oliverdunk** [comment]
I went ahead and opened a PR to fix this! We were trying to form the "this" of the apply call from the as expression, when it's really useless to us.
