### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions. 

### ISSUE THREAD

**Issue by RajAakash** [babel/babel#11418]
![image](https://user-images.githubusercontent.com/40253371/79200065-9e37d300-7e55-11ea-8b25-27e0d4830afa.png)
I got that issue when running a simple code of file: add.test.js
`const add = (a,b) => a + b;

//syntax for test: test('',code_for_test); 

test('should add two numbers',()=>{
    const result=add(3,4);

    if(result!==7){
        throw new Error(`You add 4 and 3. The result was ${result} ,Expect 7`);
    }
});

And my Package.json is given `below.
```
{
  "name": "boilerplate",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "serve": "live-server public/",
    "build": "webpack",
    "dev-server": "webpack-dev-server",
    "test": "jest"
  },
  "author": "Aakash",
  "license": "ISC",
  "dependencies": {
    "@babel/preset-react": "^7.9.4",
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "babel-loader": "^8.0.0-beta.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-env": "^1.5.2",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.4",
    "jest": "^25.3.0",
    "live-server": "^1.2.1",
    "moment": "^2.24.0",
    "node-sass": "^4.13.1",
    "normalize.css": "^8.0.1",
    "react": "^16.0.0",
    "react-addons-shallow-compare": "^15.6.2",
    "react-dates": "^21.8.0",
    "react-dom": "^16.0.0",
    "react-modal": "^2.2.2",
    "react-redux": "^5.0.5",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.5",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "uuid": "^7.0.3",
    "validator": "^8.0.0",
    "webpack": "^3.1.0",
    "webpack-dev-server": "^2.5.1"
  }
}
```

and .babelrc is given below:
```
{
    "presets":[
        "env",
        "react"
    ],
    "plugins":[
        "transform-class-properties",
        "transform-object-rest-spread"
    ]
}
```
and my program structure look like this:

![image](https://user-images.githubusercontent.com/40253371/79200557-5a919900-7e56-11ea-9f34-e721ebb3fae3.png)

**Comment by nicolo-ribaudo** [comment]
The problem is that you are using Babel 6 plugins/presets with Babel 7. Please use `@babel/preset-env`, `@babel/preset-react`,  and `@babel/plugin-transform-class-properties` instead. Also, I suggest not using the beta but a newer version (at least 7.9.0).
