### ISSUE TITLE
Babel throws confusing error when private property is used as computed key

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11414]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
The following snippet, after transformed, throws
```
Cannot read property 'get' of undefined
```

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqD2BzRICm0DeAoa0DEADgE7wHQC80ARACYCWEYARmjVQNw7QDaALgBYMAdIRIEAuhWgAzMCAiosAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=env%2Cstage-3%2Cenv&prettier=false&targets=Node-13&version=7.9.0&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.9.5)

```js
class Toggle {
  #prop = "disabled";
  [this.#prop] = false
}
```

**Expected behavior/code**
It should throw
```
attempted to get private field on non-instance
```
**Environment**
REPL

**Possible Solution**

We should also check if `privateMap` is `undefined` in https://github.com/babel/babel/blob/a6e8b3843b53c6e106d9fb2e37fea60c306dd97c/packages/babel-helpers/src/helpers.js#L1121

**Additional context/Screenshots**
Found this issue when reviewing PR 11405.

**Comment by jridgewell** [comment]
Once #11405 has landed, this will be a very simple fix. All that's needed is to rearrange https://github.com/babel/babel/blob/070ec201packages/babel-helper-create-class-features-plugin/src/index.js#L185-L186, so that the private name nodes are inserted before the key nodes.

I think this is a GFI.

**Comment by AjayPoshak** [comment]
I would like to take it up.
