### ISSUE TITLE
Having trouble with building angular project

### ISSUE THREAD

**Issue by faridg18** [babel/babel#11427]
**Current Behavior**
I am building my angular project on circleci and it just keeps failing with the following message:
**An unhandled exception occurred: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'**

Require stack:
- /home/circleci/eleven-app/frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/circleci/eleven-app/frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/preset-env/lib/index.js
- /home/circleci/eleven-app/frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/config/files/plugins.js
- /home/circleci/eleven-app/frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/config/files/index.js
- /home/circleci/eleven-app/frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/index.js
- /home/circleci/eleven-app/frontend/node_modules/@angular-devkit/build-angular/src/utils/process-bundle.js
- /home/circleci/eleven-app/frontend/node_modules/jest-worker/build/workers/processChild.js

 
I am using 
{
    "@babel/plugin-proposal-numeric-separator": "^7.8.3",
    "core-js": "3.2.1",
    "tslib": "^1.11.1",
    "@babel/compat-data": "~7.8.0",
    "@babel/runtime-corejs3": "^7.9.2",
    "ts-node": "7.0.0",
    "tslint": "5.11.0",
    "typescript": "3.5.3",
}
 resolutions:  {
    "@babel/preset-env": "^7.8.7"
  }

here is npx nls why @babel/preset-env output:

  eleven-app-frontend > @angular-devkit/build-angular > @babel/preset-env@7.8.7
  eleven-app-frontend > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > @babel/preset-env@7.9.5
  eleven-app-frontend > @nrwl/cypress > @cypress/webpack-preprocessor > @babel/preset-env@7.9.5

Thank you for reading.

**Comment by benschoch** [comment]
As we're facing a similar issue, here are 2 options we came up with so far:
- Adapt dependency of babel/preset-env to v7.9.0: `"@babel/preset-env": "=7.9.0"`
- In case you use a NodeJS Docker Image, fix the version to something below 13.13, i.e.: `node:13.12.0-alpine`

Both solutions are temporarily and should be removed as soon as there is an actual fix of the node images or the babel/preset-env library.

Hope this helps somehow.

**Comment by nicolo-ribaudo** [comment]
This was a breaking change in node 13.13 which breaks with Babel <7.9.0: https://github.com/nodejs/node/issues/32852#issuecomment-613652057

Either update Babel or don't update Node.js :stuck_out_tongue:
