### ISSUE TITLE
babel#7.9.5 not working well with some self-closing tags

### ISSUE THREAD

**Issue by AngeloAvv** [babel/babel#11429]
## Bug Report

**Current Behavior**
Using babel with version 7.9.5, some self-closing tags like: `<span><i class="fa fa-heart-o"/></span>` do not get rendered well and then all the DOM will be broken. This behavior appears only with this version, with previous versions like 7.9.0 or above it works.

If you change the self-closing tag into a normal tag, the babel-preset-env work pretty well.
`<span><i class="fa fa-heart-o"></i></span>`

**Input Code**
```
<div ng-if="ctrl.rooms && ctrl.rooms.length > 0" class="full-height dflex flex-direction-column">
            <div class="input-group col-lg-3 col-md-3 col-sm-5 col-xs-11 text-lg">
                <div class="input-group-addon" style="border:none; background-color:white; font-size: 18px;">
                    <span><i class="fa fa-heart-o"/></span>
                </div>
                <select class="form-control no-border-radius"
                        ng-options="item as item.label for item in ctrl.inChargeFilters track by item.id"
                        ng-model="ctrl.inChargeFilterSelected"
                        ng-change="ctrl.inChargeFilter()">
                </select>
            </div>
 ...
```

**Expected behavior/code**
As shown in the screenshot, we have only a single heart icon, we see multiple heart icons rendered in the DOM with the version 7.9.5

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `webpack.config.js (babel snippet)`

```js
{
                    test: /.*(\/|\\)(?!app).*(\/|\\)(ctrls|dirs|module|svcs)(\/|\\).+\.js$/,
                    exclude: [/node_modules/],
                    use: [{
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env']
                        }
                    }, {
                        loader: 'webpack-conditional-loader',
                    }]
                }
```

- Filename: `package.json (snippet)`

```json
"devDependencies": {
    "@babel/core": "^7.6.3",
    "@babel/preset-env": "^7.6.3",
    "babel-loader": "^8.0.6",
...
```

**Environment**

```

```
- Babel version(s): v7.9.5
- babel-preset-env version(s): v7.9.5
- babel-loader version(s): v8.0.6
- Node/npm version: Node 10.20.1 / npm 6.14.4
- OS: Ubuntu 18.04
- How you are using Babel: loader

**Possible Solution**
To temporarily avoid this problem without rewriting the code, we suggest to downgrade babel-preset-env to 7.9.0

**Additional context/Screenshots**

Right render:
![Right DOM](https://user-images.githubusercontent.com/7781143/79432222-d06b4100-7fcb-11ea-88f0-497bbc5f21d6.png)

Broken render:
![Broken DOM](https://user-images.githubusercontent.com/7781143/79432145-b9c4ea00-7fcb-11ea-9780-736904080084.png)

Right DOM:
![Right DOM](https://user-images.githubusercontent.com/7781143/79432538-3952b900-7fcc-11ea-8f09-cabb9871f806.png)

Broken DOM:
![Broken DOM](https://user-images.githubusercontent.com/7781143/79432406-03add000-7fcc-11ea-9eed-8189da0029a8.png)

**Comment by nicolo-ribaudo** [comment]
I don't understand how this could be caused by Babel. Babel only parses JavaScript code, not HTML files or angular templates. Did you only update `@babel/preset-env`, or also other packages? Do you have a running example that  reproduces the bug?

**Comment by AngeloAvv** [comment]
I don't have a running example since it is a closed source project and it's still in development. Consider that most of our dependencies in our package.json file are legacy so they aren't updated by far. As I mentioned before, I could fix the bug by following two ways: without using the self-closing tags with babel-preset-env 7.9.5 (but our project is very huge and it will take a lot of effort to convert all of the self-closing tags to standard ones) or by downgrading babel-preset-env to 7.9.0 or below. I've tried different version combinations to make sure that it's a babel-preset-env related issue. 

About your doubts regarding HTML files, we use some loaders in our project, so the HTML that I mentioned above goes into a javascript file which is then transpiled by babel (I guess), so that may be the cause.

I will provide to you our webpack.config.js, so you could better understand what I'm saying.

- Filename: `webpack.config.js`

```js
'use strict';

var path = require('path');
var webpack = require('webpack');

const HtmlWebpackPlugin = require('html-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const MergeJsonWebpackPlugin = require('merge-jsons-webpack-plugin');

module.exports = (env, argv) => {
    process.env.ENV = process.env.NODE_ENV = argv.mode;

    var isWatching = argv.watch;
    var modeuleExport = {
        devServer: {
            contentBase: path.join(__dirname, 'dist'),
            compress: true,
            port: 7000
        },
        entry: {
            app: ['./app.js',]
        },
        optimization: {
            minimize: false,
            minimizer: [
                new TerserPlugin({
                    cache: true,
                    sourceMap: true,
                    parallel: true,
                    exclude: [
                        /\/node_modules/,
                    ],
                    terserOptions: {
                        output: {
                            comments: false,
                        },
                    },
                })
            ],

            splitChunks: {
                maxInitialRequests: Infinity,
                minSize: 0,
                chunks: 'all',
                cacheGroups: {
                    vendors: {
                        test: /node_modules/,
                        priority: 0,
                        name (module) {
                            if (module.context.indexOf('angular') >= 0) {
                                return 'angular';
                            }

                            return 'vendors';
                        }
                    },

                    core: {
                        test: /www\/com\.noemalife\.(0|1|4|7).*/,
                        name: 'core',
                        priority: -10
                    },

                    p4c: {
                        test: /www\/com\.noemalife\.(2|6).*/,
                        name: 'p4c',
                        priority: -30
                    },

                    c4c: {
                        test: /www\/eu\.dedalus\.8.*/,
                        name: 'c4c',
                        priority: -10
                    },
                }
            }
        },
        output: {
            path: path.resolve(__dirname, 'dist'),
            publicPath: './',
            filename: 'js/[name].bundle.js',
            chunkFilename: 'js/[name].chunk.js'
        },
        module: {
            rules: [
                {
                    exclude: [/index\.html/, /^((www(\/|\\)index)\.(html)$).*\.*$/],
                    test: /\.html$/,
                    loader: 'ng-cache-loader?module=app&prefix=www:**'
                },
                /*
                {
                    test: /\.svg/,
                    loader: 'svg-url-loader'
                },
                */
                {
                    test: /\.(jpe?g|png|gif|ico|jpg|svg)$/i,
                    use: [
                        {
                            loader: 'url-loader',
                            options: {
                                name: 'img/[name].[ext]',
                                limit: 1,
                                url: false
                            }
                        },
                        {
                            loader: 'img-loader'
                        }
                    ]
                },
                {
                    test: /\.css$/,
                    loader: ['style-loader', 'css-loader']
                },
                {
                    test: /\.less$/,
                    use: [{
                        loader: 'style-loader', // creates style nodes from JS
                    }, {
                        loader: 'css-loader', // translates CSS into CommonJS
                    }, {
                        loader: 'less-loader', options: {
                            paths: [
                                path.resolve(__dirname, 'www/**/less')
                            ]
                        }
                    }]
                },

                {
                    test: /\.(ttf|woff|woff2|eot)$/,
                    loader: 'url-loader',
                    options: {
                        name: 'fonts/[name].[ext]',
                        limit: 1,
                        url: false
                    }
                },
                {
                    type: 'javascript/auto',
                    test: /.+(\/|\\)pages(\/|\\).+\.json$/,
                    exclude: /(node_modules)/,
                    use: [{
                        loader: 'file-loader',
                        options: {name: '[path][name].[ext]', outputPath: 'pages/', context: 'www/pages'}
                    }]
                },
                {
                    test: /www(\/|\\)templates(\/|\\).+\.html$/,
                    use: [{
                        loader: 'file-loader',
                        options: {name: '[name].[ext]', outputPath: 'templates/', context: 'www/templates'}
                    }]
                },
                {
                    test: /.*(\/|\\)(?!app).*(\/|\\)(ctrls|dirs|module|svcs)(\/|\\).+\.js$/,
                    exclude: [/node_modules/],
                    use: [{
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env']
                        }
                    }, {
                        loader: 'webpack-conditional-loader',
                    }]
                }
            ]
        },
        resolve: {
            extensions: ['.js', '.jsx', '.less'],
        },
        externals: [
            'child_process',
            'fs',
            'pages',
            'localStorage',
        ],
        watchOptions: {
            ignored: /.*(\/|\\)i18n.*/
        },
        plugins: [
            new webpack.ProvidePlugin({
                $: 'jquery',
                jQuery: 'jquery',
                'window.jQuery': 'jquery',
                io: 'socket.io-client',
            }),
            new webpack.SourceMapDevToolPlugin({
                'filename': '[file].map[query]',
                'moduleFilenameTemplate': '[resource-path]',
                'fallbackModuleFilenameTemplate': '[resource-path]?[hash]',
                'sourceRoot': 'webpack:///'
            }),
            new HtmlWebpackPlugin({
                template: 'www/index.html'
            })
        ]
    };
    if (!isWatching) {
        modeuleExport.plugins.push(
            new MergeJsonWebpackPlugin({
                'encoding': 'utf8',
                'debug': false,
                'output': {
                    'groupBy': [
                        {
                            'pattern': '**/*it-IT.json',
                            'fileName': './i18n/locale_it-IT.json'
                        },
                        {
                            'pattern': '**/*fr-FR.json',
                            'fileName': './i18n/locale_fr-FR.json'
                        },
                        {
                            'pattern': '**/*en-US.json',
                            'fileName': './i18n/locale_en-US.json'
                        }
                    ]
                },
                'globOptions': {
                    'nosort': true
                }
            }));
    }
    return modeuleExport;
};

```

**Comment by panthony** [comment]
Hello everyone 👋 

I have the same issue as @AngeloAvv.

I have a dependency to [spectrum](https://github.com/bgrins/spectrum) which generate HTML with self-closing tags (see [here](https://github.com/bgrins/spectrum/blob/master/spectrum.js#L143) using JavaScript.

Reverting back to a previous version of babel fixed the issue.

**Comment by developit** [comment]
Neither of these examples appear to use JSX?

If they somehow do, perhaps it's an issue with pragma calls now being marked as `@PURE`? ([example](https://babeljs.io/repl#?browsers=Edge%3E%3D16&build=&builtIns=false&spec=false&loose=true&code_lz=DwEwlgbgBAdg5gWjAMwLwCIDGAXATgGwDpcB7EgWwGcoAyGqHA4sqw_AU3mwAsoA-KAAZ0DfAENKlDMgCu-fAm7swcbtighkHAB5Qt7bQnC52OMCRgJMJfDPIx0fAFBQooSKIlT0YGAAcZbAQ4Uhk_BhsEfEQAZgiFchAEOOsFSnIEAFZ4hG1KBABGAqhsAyDoxxdXN3BoTHFJDF8AoJCSMIQxEBALEUpsAE8ODAAjElwQdlwALhgLdgBuKBGxTABrNpkYJNTx6YB3bjBSpeQLIMowAC92aagCgA4_bQXK6urgSj8xGD5gME8jXQyDEejEinYYlwQRI6AA9H84V8fs53sA4bVUR9KOwODhAd4zrgMtYYHgbLASAgxhMpghcF0wDJKOgqu94AgSH5sOYYN5juxyFAJFABeQ2GIRri9ONRaUhb4GHgiL4AMLcKFwdgAMTA-FKuGoeFWa2WAzlgsIYBArPerg55BIk3wGEYKpg6s1Or1BoAyrjTKUbWzqhzMBr4OxXcqrR6Nbgtbr9VMABQASjeHyRAZwWPRmKc-cgfCAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cenv&prettier=true&targets=&version=7.9.0&externalPlugins=), VS [7.8.0 example](https://babeljs.io/repl#?browsers=Edge%3E%3D16&build=&builtIns=false&spec=false&loose=true&code_lz=DwEwlgbgBAdg5gWjAMwLwCIDGAXATgGwDpcB7EgWwGcoAyGqHA4sqw_AU3mwAsoA-KAAZ0DfAENKlDMgCu-fAm7swcbtighkHAB5Qt7bQnC52OMCRgJMJfDPIx0fAFBQooSKIlT0YGAAcZbAQ4Uhk_BhsEfEQAZgiFchAEOOsFSnIEAFZ4hG1KBABGAqhsAyDoxxdXN3BoTHFJDF8AoJCSMIQxEBALEUpsAE8ODAAjElwQdlwALhgLdgBuKBGxTABrNpkYJNTx6YB3bjBSpeQLIMowAC92aagCgA4_bQXK6urgSj8xGD5gME8jXQyDEejEinYYlwQRI6AA9H84V8fs53sA4bVUR9KOwODhAd4zrgMtYYHgbLASAgxhMpghcF0wDJKOgqu94AgSH5sOYYN5juxyFAJFABeQ2GIRri9ONRaUhb4GHgiL4AMLcKFwdgAMTA-FKuGoeFWa2WAzlgsIYBArPerg55BIk3wGEYKpg6s1Or1BoAyrjTKUbWzqhzMBr4OxXcqrR6Nbgtbr9VMABQASjeHyRAZwWPRmKc-cgfCAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cenv&prettier=true&targets=&version=7.8.0&externalPlugins=))

**Comment by AngeloAvv** [comment]
After further investigations, I can say that the issue may not involve directly the preset-env, so I changed title and the description of the issue accordingly. Also, downgrading doesn't fix the problem because the nested dependencies of core and preset are still referencing the last ones. I found it by analyzing directly our yarn.lock file.

In other words, if we use our yarn.lock file which references previus versions like 7.8.7, it works pretty well, but if you perform a yarn update (or npm update), it breaks down.

**Comment by ueler** [comment]
We also have babel in our project and also suspected babel first.
However, in our case upgrading the dependency jquery to 3.5.0 (see their release notes) was responsible for messing up our whole AngularJS project. Back to 3.4.1 everything works fine again.

Maybe this is not directly related to this question, just in case someone also has upgraded babel together with jquery.

**Comment by existentialism** [comment]
It would be really helpful if someone could create a small repo that reproduces the problem!

**Comment by AngeloAvv** [comment]
@ueler is right. By forcing jQuery version to 3.4.1 the problem doesn't appear anymore.
I didn't think about jQuery because 95% of our dependencies are legacy projects which no longer get updated by far.
