### ISSUE TITLE
@babel/plugin-transform-for-of  state.availableHelper

### ISSUE THREAD

**Issue by cherishing** [babel/babel#11430]
`        if (!state.availableHelper(builder.helper)) {
          (0, _noHelperImplementation.default)(loose, path, state);
          return;
        }
`

Module build failed (from ./node_modules/_babel-loader@8.1.0@babel-loader/lib/index.js):
TypeError: state.availableHelper is not a function
but  `   if (state.availableHelper && !state.availableHelper(builder.helper))` can be running.  why?

**Comment by nicolo-ribaudo** [comment]
What is the full stack trace?
