### ISSUE TITLE
.babelrc in windows cli

### ISSUE THREAD

**Issue by calebboyd** [babel/babel#1143]
The command and accompanying rc file are working fine with babel 4.7.16 or 5.0+ on ubuntu 14.04

However it does not work with babel 5.0+ on windows. (worked with 4.7..)
In addition it _does_ get applied when using `--compilers js:babel/register` with mocha.

`babel index.src.js --out-file index.js`

.babelrc
```
{
    "optional": ["bluebirdCoroutines"]
}
```

**Comment by sebmck** [comment]
Not really a regression since in 4.x .babelrc wasn't documented or
encouraged for use at all.

On Friday, 3 April 2015, Caleb Boyd <notifications@github.com> wrote:

> The command and accompanying rc file are working fine with babel 4.7.16 or
> 5.0+ on ubuntu 14.04
>
> However it does not work with babel 5.0+ on windows. (worked with 4.7..)
> In addition it *does* get applied when using --compilers js:babel/register
> with mocha.
>
> babel index.src.js --out-file index.js
>
> .babelrc
>
> {
>     "optional": ["bluebirdCoroutines"]
> }
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1143>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
Actually probably related to the absolute relative issue that's fixed
earlier. Please test against the latest.

On Friday, 3 April 2015, Sebastian McKenzie <sebmck@gmail.com> wrote:

> Not really a regression since in 4.x .babelrc wasn't documented or
> encouraged for use at all.
>
> On Friday, 3 April 2015, Caleb Boyd <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> The command and accompanying rc file are working fine with babel 4.7.16
>> or 5.0+ on ubuntu 14.04
>>
>> However it does not work with babel 5.0+ on windows. (worked with 4.7..)
>> In addition it *does* get applied when using --compilers
>> js:babel/register with mocha.
>>
>> babel index.src.js --out-file index.js
>>
>> .babelrc
>>
>> {
>>     "optional": ["bluebirdCoroutines"]
>> }
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/babel/babel/issues/1143>.
>>
>
>
> --
> Sebastian McKenzie
>


-- 
Sebastian McKenzie

**Comment by calebboyd** [comment]
Haha. Awesome. My local copy was out of date. Sorry for the spam :/
