### ISSUE TITLE
Anonymous generator function expression with typescript generic fails to parse

### ISSUE THREAD

**Issue by devongovett** [babel/babel#11435]
## Bug Report

**Current Behavior**

Anonymous generator functions with typescript generics fail to parse:

```typescript
const fn = function* <T>(input: T): Generator<number> {
  yield 2;
}
```

`SyntaxError: Unexpected token, expected "(" (1:21)`

When adding a name to the function it works as expected:

```typescript
const fn = function* fn<T>(input: T): Generator<number> {
  yield 2;
}
```

TSC parses anonymous generator functions with generics [as expected](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=4&pc=1#code/MYewdgzgLgBAZmGBeeBXMwoEtwCoYA8AKgHwAUWYADqlAFwxECUDA4gKZjsBOAhlCG4EwqALYAjHiRgBvAFAwYATyzsANgBMYAJgDccgL5ygA).

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeeBXMwoEtwCoYA8AKgHwAUWYADqlAFwxECUDA4gKZjsBOAhlCG4EwqALYAjHiRgBvAFAwYATyzsANgBMYAJgDccgL5ygA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.9.0&externalPlugins=)

```typescript
const fn = function* <T>(input: T): Generator<number> {
  yield 2;
}
```

**Expected behavior/code**

Should parse as an anonymous generator function with generic.

**Additional info**

Appears that the current behavior is correct for function declarations, but not function expressions. TSC [throws a parse error](https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mAVAAgDwBUB8AKGYAOIUAXMugJSkDiApmDQE4CGUcDqYIAtgEaObIA3gChkyAJ4waAGwAmyAEwBuYQF9hQA) when the function is parsed as a declaration, but not when parsed as an expression (as above).

**Environment**

```
- Babel version(s): v7.9.4
- Node/npm version: 12
- OS: macOS
- Monorepo: N/A
- How you are using Babel: `@babel/parser`

**Comment by existentialism** [comment]
Note the error only occurs when `jsx` is enabled too ([REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeeBXMwoEtwCoYA8AKgHwAUWYADqlAFwxECUDA4gKZjsBOAhlCG4EwqALYAjHiRgBvAFAwYATyzsANgBMYAJgDccgL5ygA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.9.0&externalPlugins=)).

**Comment by hzoo** [comment]
Good catch - later, should we just enable jsx parsing by default in the tests or run them separately?

https://github.com/babel/babel/blob/1a08aa5adc564d5205dc7900d8364b28dc0914a5/scripts/parser-tests/typescript/index.js#L72

**Comment by devongovett** [comment]
Good catch on JSX, and thanks for fixing @existentialism! 😍
