### ISSUE TITLE
Binary operator after TypeScript `as` assertion causes wrong SyntaxError

### ISSUE THREAD

**Issue by woongsikchoi** [babel/babel#11446]
## Bug Report

**Current Behavior**

If a bianry operator like `>=` appears directly after TypeScript `as` assertion, a wrong SyntaxError occurs.

**Input Code**
```ts
function foo(x: any) {
	return x as number >= 0;
}
```

The above code causes the following SyntaxError:
```
{ SyntaxError: test.ts: Unexpected token (2:22)
  1 | function foo(x: any) {
> 2 |   return x as number >= 0;
    |                       ^
  3 | }
  4 | 
```

**Expected behavior/code**

No SyntaxError should occur.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**
```
  System:
    OS: Linux 4.4 Ubuntu 14.04.5 LTS, Trusty Tahr
  Binaries:
    Node: 10.15.1 - ~/local/lib/node-v10.15.1-linux-x64/bin/node
    Yarn: 1.22.4 - ~/local/lib/node-v10.15.1-linux-x64/bin/yarn
    npm: 6.9.0 - ~/local/lib/node-v10.15.1-linux-x64/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    @babel/core: ^7.9.0 => 7.9.0 
    @babel/preset-typescript: ^7.9.0 => 7.9.0 
```

**Comment by nicolo-ribaudo** [comment]
@DanielRosenwasser What is the precedence of the `as` operator? It seems like it has very different precedences on the left and on the right, but I'm not sure about it.

Specifically, on the left is it higher or lower than relational operators? I'm asking because from my experiments it has an higher precedence than `>` and lower precedence than `<`, but `>` and `<` should have the same precedence.

```js
a as b > c > +d; // This is parsed as two `>` operators, and an unary `+`
a as b < c > +d; // This is parsed as a sum between (a as b<c>) and d
```

**Comment by woongsikchoi** [comment]
The same problem occurs also for the nullish coalescing operator `??`.

**Comment by clar-cmp** [comment]
Also dealing with this bug.

**Comment by JLHwung** [comment]
> The same problem occurs also for the nullish coalescing operator `??`.

Can you open a new issue? They have different root causes. @woongsikchoi
