### ISSUE TITLE
Remove moduleRoot from the generated module name

### ISSUE THREAD

**Issue by shangwenhe** [babel/babel#11445]
https://github.com/babel/babel/blob/f6c7bf36cec81baaba8c37e572985bb59ca334b1/packages/babel-helper-module-transforms/src/get-module-name.js#L36

**Comment by nicolo-ribaudo** [comment]
Why?

**Comment by shangwenhe** [comment]
```javascript
    [
      "@babel/plugin-transform-modules-amd",
      {
        "allowTopLevelThis": true,
        "moduleIds": true,
        "sourceType": "module",
        "moduleRoot": "/Users/shang/Downloads/"
      }
    ]
```

Failed to achieve the expected effect, use 'moduleIds' and 'moduleRoot' config;

**Comment by JLHwung** [comment]
Per [docs](https://babeljs.io/docs/en/options#moduleroot), the `moduleRoot` will always be included in the generated source. If you would to strip the `moduleRoot` in the generated module name, you can pass your own `getModuleId` function:
```js
[
      "@babel/plugin-transform-modules-amd",
      {
        "allowTopLevelThis": true,
        "moduleIds": true,
        "sourceType": "module",
        "moduleRoot": "/Users/shang/Downloads/",
        getModuleId(name) {
            return name.replace("/Users/shang/Downloads/", ".");
        }
      }
    ]
```

**Comment by shangwenhe** [comment]
So ga
