### ISSUE TITLE
Q: Querying a field of a prototype or constructor function without invoking the getter or setter

### ISSUE THREAD

**Issue by silkentrance** [babel/babel#11441]
Over at https://github.com/testdeck/testdeck we skim through the available fields in a given suite class in order to find actual test methods. Some of the user defined suites might have getters or setters for whatever reason. (context: typescript.)

Now, accessing these via `prototype[key]` will invoke the getter or setter and thus may result in error.

It would be nice to have some means of reflection to know before hand whether this is a just a method or a getter or setter function, e.g. Reflect.isGetter(key, prototype/ctor) and so on.

Would this be possible to have in a future version of the language?

I hope that you all are doing well.

**Comment by silkentrance** [comment]
See also https://github.com/testdeck/testdeck/blob/master/packages/core/index.ts#L137

**Comment by silkentrance** [comment]
Perhaps you can get things up to speed in the respective committees. TIA!

**Comment by silkentrance** [comment]
https://github.com/testdeck/testdeck/issues/248

**Comment by nicolo-ribaudo** [comment]
You already can!
```js
const isGetter = "get" in Object.getOwnPropertyDescriptor(obj, key);
const isSetter = "set" in Object.getOwnPropertyDescriptor(obj, key);
const isProperty = "value" in Object.getOwnPropertyDescriptor(obj, key);
```

In general, this isn't the correct repository to propose new JS features: please read [how to do it](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals).
