### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/classCallCheck'

### ISSUE THREAD

**Issue by pramish22** [babel/babel#11444]
I've installed babel but still I'm getting this error. How to fix this?

**Comment by nicolo-ribaudo** [comment]
What is your package.json? Did you add `@babel/runtime` to your dependencies? What is the full error?

**Comment by pramish22** [comment]
That one is fixed now I'm getting different error
![image](https://user-images.githubusercontent.com/31245053/79684954-d2930100-8252-11ea-83bd-2e4b4cc550d2.png)

**Comment by nicolo-ribaudo** [comment]
That one is not related to Babel.

It's a permissions problem, probably caused by some files being created with admin rights. You can try to delete `node_modules` and re-install it.

If it doesn't work, I suggest asking on StackOverflow on in some other general JavaScript support platform!
