### ISSUE TITLE
Destructuring assignment not supported in namespaces

### ISSUE THREAD

**Issue by m93a** [babel/babel#11461]
## Bug Report

**Current Behavior**
Set up a TypeScript repository with Babel and [plugin-transform-typescript](https://babeljs.io/docs/en/babel-plugin-transform-typescript/). Add this code:

**Input Code**
```typescript
const obj = {a: "foo", b: 42}

namespace Foo
{
    export const {a, b} = obj
}
```

**Expected behavior/code**
It should compile just fine. In TypeScript this just works: [Playground Link](https://www.typescriptlang.org/play/#code/MYewdgzgLgBCBGArGBeGBvAhgLhgIgDMQQ8AaGeXAFgCYBfAWAChmxMBbAUwgAdNhOMAGLFm6ZjEkxOADx4gATrFCRYWcvDqo4SZoyZA)

**Actual behavior**
The compiler throws a **very misguiding** error:
```
TypeError: foo.ts: Property name expected type of string but got null
```

**Babel Configuration**
- The repository was created with:
```bash
yarn create react-app --template=typescript
yarn add @babel/plugin-transform-typescript react-app-rewired customize-cra
```
Then add this to `config-overrides.js`:
```javascript
const {
    override,
    addExternalBabelPlugin
  } = require("customize-cra");

module.exports = override(
    addBabelPlugin([
        "@babel/plugin-transform-typescript",
        { allowNamespaces: true }
    ])
);
```

**Environment**
- Babel version(s): v7.9.0
- Node/npm version: v13.13.0
- OS: elementary
- Monorepo: no
- How you are using Babel: via `react-scripts`, `webpack`

**Comment by sidntrivedi012** [comment]
I would like to work on it after completing #11061 .
