### ISSUE TITLE
`Array.isArray` issue while upgrading to 5.0

### ISSUE THREAD

**Issue by pascalduez** [babel/babel#1147]
```js
if (Array.isArray(...)) { ... }
```
```
if (_core.Array.isArray(...)) {
                    ^
TypeError: undefined is not a function
```

```json
{
  "stage": 1,
  "loose": ["all"],
  "optional": ["runtime"],
  "auxiliaryComment": "istanbul ignore next"
}
```
```json
"babel-runtime": "^4.7.16",
"babel": "^5.0.6"
```

**Comment by sebmck** [comment]
Upgrade your `babel-runtime` to 5.x

**Comment by sebmck** [comment]
Also as per the README:

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs). The Babel issue tracker is exclusively for bug reports and future requests.

Thanks!

**Comment by pascalduez** [comment]
Sorry, for some reason I kept getting version 4.7, all good now, thanks.
