### ISSUE TITLE
Babel is optimizing code and there are no way to disable that

### ISSUE THREAD

**Issue by jcubic** [babel/babel#11473]
## Bug Report

Babel is removing code that is always true and there are no way to disable that feature.

it seems that there are no way to disable this optimization, why babel do that?

- [ ] I would like to work on a fix!

**Current Behavior**

Babel is optimizing the code and there are no option to turn this off.

**Input Code**
I have code like this:

```javascript
        var date = '{{DATE}}';
        var _date = date === '{{' + 'DATE}}' ? new Date() : new Date(date);
```

and babel is happy because it removed my code and replaced it with:
```javascript
var _date = new Date();
```

`{{DATE}}` is updated later with my build date.

**Expected behavior/code**
I expect that no code is removed. I need to wrap the code with object to prevent this to happen, If Would like to have this optimized I would run minifier and will be fine if he removed that code. Minifier in my build script is run when `{{DATE}}` is already real date.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

I use rollup babel plugin that just pass through the options to babel.
```js
        babel({
            "babelrc": false,
            "runtimeHelpers": true,
            "plugins": [
                "@babel/plugin-transform-async-to-generator",
                "@babel/plugin-transform-regenerator",
                ["@babel/plugin-transform-runtime", {
                    "helpers": true,
                    "regenerator": true
                }]
            ],
            "presets": [
                "@babel/preset-env"
            ],
            "exclude": "node_modules/**"
        }),
```

**Environment**

```
  System:
    OS: Linux 5.5 Fedora 30 (Thirty) 30 (Thirty)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.4.5 => 7.7.4 
    @babel/plugin-external-helpers: ^7.2.0 => 7.7.4 
    @babel/plugin-transform-async-to-generator: ^7.4.4 => 7.7.4 
    @babel/plugin-transform-regenerator: ^7.4.5 => 7.7.4 
    @babel/plugin-transform-runtime: ^7.4.4 => 7.7.4 
    @babel/preset-env: ^7.4.5 => 7.7.4 
    @babel/runtime: ^7.4.5 => 7.7.4 
    @babel/runtime-corejs2: ^7.4.5 => 7.7.4 
    babel-preset-env: ^1.7.0 => 1.7.0 
    babel-preset-es2015: ^6.24.1 => 6.24.1 
    babel-preset-stage-0: ^6.24.1 => 6.24.1 
    eslint: ^6.8.0 => 6.8.0 
    jest: ^24.8.0 => 24.9.0 
    rollup-plugin-babel: ^4.3.2 => 4.3.3
```

**Possible Solution**
Options to turn of any optimizations.

**Comment by nicolo-ribaudo** [comment]
Babel doesn't do those optimizations; it's some other tool you are using.

**Comment by jcubic** [comment]
Sorry it was rollup Tree-shaking.
