### ISSUE TITLE
Use of lodash modules for leaner bundle

### ISSUE THREAD

**Issue by igorlino** [babel/babel#11483]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**

Analysing the size of the angular CLI bundle that requires angular/localize that dependes on babel/core, i noticed an additional complete lodash dependency. 

```
>npm ls lodash

+-- @angular/localize@9.1.3
| `-- @babel/core@7.8.3
|   `-- lodash@4.17.15  deduped

```

The lodash fully included has:
Stat size: 527.84 KB
Parsed size: 70.72 KB
Gzipped size: 23.81 KB

looking at the babel/core:

```
C:\projects\babel\packages\babel-core>npm ls lodash
@babel/core@7.9.0 C:\projects\babel\packages\babel-core
+-- @babel/generator@7.9.5
| `-- lodash@4.17.15  deduped
+-- @babel/helper-module-transforms@7.9.0
| `-- lodash@4.17.15  deduped
+-- @babel/helper-transform-fixture-test-runner@7.9.2
| +-- @babel/core@7.9.0
| | `-- lodash@4.17.15  deduped
| +-- @babel/helper-fixtures@7.8.6
| | `-- lodash@4.17.15  deduped
| +-- jest@24.9.0
| | `-- jest-cli@24.9.0
| |   `-- jest-config@24.9.0
| |     `-- jest-environment-jsdom@24.9.0
| |       `-- jsdom@11.12.0
| |         `-- request-promise-native@1.0.8
| |           `-- request-promise-core@1.1.3
| |             `-- lodash@4.17.15  deduped
| `-- lodash@4.17.15  deduped
+-- @babel/traverse@7.9.5
| `-- lodash@4.17.15  deduped
+-- @babel/types@7.9.5
| `-- lodash@4.17.15  deduped
`-- lodash@4.17.15
```

**Describe the solution you'd like**

If using lodash-es with individual imports of what is really required, its possible to significantly reduce the size of the dependency.

https://medium.com/@armno/til-importing-lodash-into-angular-the-better-way-aacbeaa40473

**Describe alternatives you've considered**

remove dependency of lodash altogether. the cost will be to high.

**Teachability, Documentation, Adoption, Migration Strategy**

The users would benefit out-of-the-box when consuming the package properly.

**Comment by nicolo-ribaudo** [comment]
We can't do this because Node.js <14 doesn't support ECMAScript modules.

**Comment by igorlino** [comment]
You are right, I had a feeling that could be the case. I will raise an issue in the Angular project, why this dependency appears on the 1st place.

Thank you for the answer, I will close this issue :)
