### ISSUE TITLE
Getting error while building the project

### ISSUE THREAD

**Issue by srv-smn** [babel/babel#11489]
## Bug Report

- [ ] I would like to work on a fix!
Hello , I am very much new to this node , react and javascript world , I developed a project a by seeing the tutorial but , now when I am trying to build the project I am getting . I read a lot of post regarding this issue but I was unable to fix the issue , From last 1 week I am trying to solve the issue , recently I was reading a Post treating this issue and there was link on how to solve this .
so following those links I came here , and I think is the best place where I can put up my issue , Sorry if I am wrong .
Sorry if I am unable to properly convey my issue 
I will be very happy if you solve my problem 

**Current Behavior**
My project is working fine as expected but when I am trying to build that project `npm run build` I am getting errors
` 'commons.js from UglifyJs\n' +
      'Unexpected token keyword «function», expected punc «,» [commons.js:32913,28]'`
### [Github Repo ](https://github.com/srv-smn/demo)

Full error :
`G:\videos\programming blockchain\Kickstart - Copy>npm run build

> kickstart@1.0.0 build G:\videos\programming blockchain\Kickstart - Copy
> next build

> Failed to build on C:\Users\SOURAV~1\AppData\Local\Temp\fc2be532-5532-4ebf-a085-224a51812668
Error: commons.js from UglifyJs
Unexpected token keyword «function», expected punc «,» [commons.js:32913,28]
    at G:\videos\programming blockchain\Kickstart - Copy\node_modules\next\dist\server\build\index.js:182:21
    at G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\Compiler.js:269:13
    at Compiler.emitRecords (G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\Compiler.js:375:38)
    at G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\Compiler.js:262:10
    at G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\Compiler.js:368:12
    at next (G:\videos\programming blockchain\Kickstart - Copy\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.<anonymous> (G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (G:\videos\programming blockchain\Kickstart - Copy\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\Compiler.js:365:9)    at G:\videos\programming blockchain\Kickstart - Copy\node_modules\webpack\lib\Compiler.js:354:15 {
  errors: [
    'commons.js from UglifyJs\n' +
      'Unexpected token keyword «function», expected punc «,» [commons.js:32913,28]'
  ],
  warnings: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kickstart@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kickstart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sourav Suman\AppData\Roaming\npm-cache\_logs\2020-04-27T07_41_05_234Z-debug.log`
**Input Code**
this is Link of my repository , please visit and try to solve
 [Github Repo ](https://github.com/srv-smn/demo)

**Comment by JLHwung** [comment]
Please update all dependencies to their latest versions, especially if you are working on a kickstart project. i.e. the latest version of `next` is `next@9` but your repo is using `next@4`, likewise for other dependencies in your repo.

The JavaScript ecosystem is evolving really fast. That said, it is likely that the post you read may be out-of-dated even if they are written in 2019. As a rule of thumb, always use latest versions and checkout the official `next.js` [docs](https://nextjs.org/docs/getting-started).
