### ISSUE TITLE
Please update chokidar optional dependency to 3.4.0 from 2.1.8 for @babel/cli package

### ISSUE THREAD

**Issue by abhranilnaha** [babel/babel#11488]
It is throwing below warning with Node 12 while loading chokidar dependency (version 2.1.8) which has a dependency on fsevents version 1.2.7. Minimum fsevents 1.2.9 version is required for Node 12. Please update to chokidar 3.4.0 which is dependent on fsevents 2.1.2 which will not throw any error with Node 12. I am using macOS Catalina.

Error:
warning Error running install script for optional dependency: "/Users/XXX/dev/YYY/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/XXX/dev/YYY/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XXX/dev/YYY/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XXX/Library/Caches/node-gyp/12.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/XXX/Library/Caches/node-gyp/12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/XXX/Library/Caches/node-gyp/12.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/XXX/dev/YYY/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/XXX/dev/YYY/node_modules/fsevents

**Comment by nicolo-ribaudo** [comment]
This will be done in Babel 8 (https://github.com/babel/babel/pull/10747) at some point in 2020. It is a breaking change, so it can't be done earlier.

However, please note that:
1. `@babel/cli` depends on `chokidar@^2.1.8`. `chokidar@2.1.8` depends on `fsevents@^1.2.7`. Due to [how version ranges work](https://stackoverflow.com/a/22345808/2359289), npm can resolve it to `fsevents@1.2.9` which, as you wrote, works with Node.js 12
2. `chokidar` is an [_optionalDependency_](https://docs.npmjs.com/files/package.json#optionaldependencies) of `@babel/cli`: if it fails to install, npm should ignore the error and continue installing your dependencies without problems. If it doesn't, then it's an npm bug.

I'm now closing this issue, since it has already been discussed [multiple times](https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+chokidar+fsevents+is%3Aclosed+).

**Comment by coreyward** [comment]
@nicolo-ribaudo Since chokidar@3 is almost entirely backwards compatible aside from Node@6 support, would it not be possible to simply relax the requirement to `>2.1.8`?

**Comment by nicolo-ribaudo** [comment]
No, that would install version 3 even on Node.js 6.

If you are using yarn you can use `"resolutions"`, or [`npm-force-resolutions`](https://www.npmjs.com/package/npm-force-resolutions) with npm.
