### ISSUE TITLE
@babel/register to hook .cjs files

### ISSUE THREAD

**Issue by perrin4869** [babel/babel#11497]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**
Right now `@babel/register` will by default hook the following extension files with node: `.es6`, `.es`, `.jsx`, `.mjs`, and `.js`. It seems to me that if `.mjs` is included, then `.cjs` should be included too. There are practical reasons for this as well.

**Describe the solution you'd like**
Make the default:
```javascript
require('@babel/register')({ extensions: ['.es6', '.es', '.jsx', '.mjs', '.cjs', '.js'] });
```

**Teachability, Documentation, Adoption, Migration Strategy**
Since `.mjs` was added without a breaking change, it doesn't seem like a breaking change would be needed here either

**Comment by nicolo-ribaudo** [comment]
Yeah, I think that we can add this in a minor.
FYI, I'm experimenting at https://github.com/babel/babel/pull/11409 with the possibility of setting `extensions` in config files, but that PR needs to wait for Babel 8.

**Comment by perrin4869** [comment]
hm... I noticed that these extensions are defined in `@babel/core`: https://github.com/babel/babel/blob/2d8edf7c6f1b077e0c92cbd18a9b3b3f59642e88/packages/babel-core/src/index.js#L44

This means that changing this value could have big unexpected implications... what do you think? Should I try to keep this change confined to `@babel/register` or go ahead and change the core value?

**Comment by nicolo-ribaudo** [comment]
That `DEFAULT_EXTENSIONS` is only used by `@babel/register`, `@babel/cli`, and `@babel/core`, so it should be ok to change it.
Maybe first wait for another :+1: from another team member.
