### ISSUE TITLE
Circular dependency import results in an empty object imported

### ISSUE THREAD

**Issue by AntJanus** [babel/babel#1150]
I'm running this on NodeJS (v0.10.33) with the `babel/register` hook. Here's my app structure:

start.js <- app entry point

````js
require('newrelic');
require('babel/register');

module.exports = require('./app.js')
````

app.js (next entry point):

`````js
import express from 'express';

var app = express();

export default app;

//app settings, middleware, etc.

import './server/app'; //import routes
````

server/app.js (used to register routes)
````js
import '../app'; //imports app, might be redundant but deleting this did not fix the issue

import './routes/upload';
````

server/routes/upload.js:

````js
import app from '../../app'; //the original app which start.js imports

app.post('/api/upload', someFunction);
````

I get an error stating that `post` method does not exist under the last file. I `console.log`ed out what the app looks like in that upload.js file, and it came back as an empty object.

I rolled back to the latest 4.x.x and it worked fine without an issue. Did something change in the way the imports/exports work?

**Comment by sebmck** [comment]
#1117 and #1057. Try upgrading to 5.0.7 to see if it fixes it if not, there's probably nothing that can be done.

**Comment by sebmck** [comment]
Actually, 5.0.7 changes wont help this case. #1057 however is the correct change that introduced this behaviour.

**Comment by AntJanus** [comment]
@sebmck oh okay, thanks for letting me know. Yeah, I tried this with `5.0.7` and it didn't help. I'll definitely upgrade when this fix goes into a release!

**Comment by AntJanus** [comment]
@sebmck I'm still having the same issue. Just an FYI. I updated to 5.0.12

**Comment by tobscure** [comment]
Also having this issue. Is it something that can be fixed?

**Comment by sebmck** [comment]
@tobscure Not really. Imports are hoisted and exported functions are hoisted. It's to the spec.

**Comment by tobscure** [comment]
@sebmck OK, thanks. Any recommendations on what I could do instead to achieve something like this?

```javascript
// a.js
import B from 'b';

export default class A {
  constructor() {
    var b = new B(this);
  }
};
```

```javascript
// b.js
import A from 'a';

export default class B {
  constructor(parent) {
    if (parent instanceof A) {
      // ...
    }
  }
};
```

**Comment by sebmck** [comment]
That should work actually.

**Comment by tobscure** [comment]
I hadn't tested that code exactly (it was a simplified version of the scenario I do have), but I did just then, and it's not working. Getting this error:
> Uncaught TypeError: Expecting a function in instanceof check, but got #<Object>
Because A is an empty object in b.js.

**Comment by AntJanus** [comment]
Knowing about the hoisting helps but damn is that inconvenient. I'll have to figure out how to restructure my app or stick to 4.X for the time being.

**Comment by tobscure** [comment]
@sebmck Still having this issue with the example I posted above. If you say it should work, then perhaps it's something else in my chain that's causing problems (e.g. the fact that I'm using https://github.com/ember-cli/loader.js?) I've put together a quick example project, would you mind taking a look?

https://dl.dropboxusercontent.com/u/15724107/babel-cyclic-test.zip

`npm install`, `gulp`, then open index.html in a browser.

**Comment by sebmck** [comment]
@tobscure It's because you're using the `amd` module formatter. I've rejiggered around some stuff which may fix it which will be available in the next patch.

**Comment by tobscure** [comment]
@sebmck Great, thank you :)

**Comment by tobscure** [comment]
@sebmck Still not working, unfortunately. Is there anything else that can be done?

**Comment by callumlocke** [comment]
@sebmck I have this same issue, and I'm not using the AMD formatter or any custom formatter. Can produce a minimal demo of the bug if that would help.

**Comment by sebmck** [comment]
Sure

**Comment by chicoxyzzy** [comment]
same issue

**Comment by loganfsmyth** [comment]
@chicoxyzzy Do you have a reproducible example we can look at?

**Comment by kenkouot** [comment]
I'm running `5.6.15` of Babel installed from JSPM, running in the browser with files loaded from System.js.

I have two files:
```js
// app.js
import angular from 'angular';
import foo from './components/foo';

var app = angular.module('app', [
  foo.name
]);

// will return a proper expected object
console.log(app);

export default app;
```
In the second file
```
import angular from 'angular';
import app from '../app';

// This will be undefined
console.log(app);
```
As with the others, I'm not using any sort of module transforms, but simply running ES6 code through Babel's browser runtime. Any help would be much appreciated.

**Comment by sebmck** [comment]
@kenkouot Expected behaviour. You're exporting `app` after it's being referenced.

**Comment by AntJanus** [comment]
Hey guys,
I wondered if my architecture would help someone with this:

`start.js` is my entry file and it has the `babel/register` hook, it requires `./server/app.js`.

My `app.js` looks like this:

```
import app from './bootstrap';

import './routes/login';
//and a bunch of other routes

export default app;
```

I'm able to thus require the entire app from a testing environment as well. Here's my `boostrap` file:

```
//bunch of dependencies

import express from 'express';

var app = express();

//plugin stuff

export default app;
```

Whenever I need to use a part of the actual app definition, like in a route, I can just import the `bootstrap` file:

```
import app from '../bootstrap';

app.get('/whateverurl', whateverHandler);

function whateverHandler(req, res) {

}
```

I never export anything from the routes and I don't get any undefineds. The reason why I import `app` per route is because I get to set locals in my `bootstrap` file.

I'm guessing that in some way, the dependencies get built where `app` is available for every part of my app. I hope that makes sense!

Also, another workaround inspired by Angular's JS styleguide:

```
import angular from 'angular';
import myComponent from './myComponents';

export default angular.module('app', [])
  .run(run)
 .config(config)
;

function run() {

}

function config() {

}
```

I use this structure on the front-end and it doesn't cause any issues or undefineds. In fact, it follows [john papa's angularjs styleguide](https://github.com/johnpapa/angular-styleguide) (mostly).

Or, this will work as well:

```
import angular from 'angular';
import myComponent from './myComponents';

export default startApp();

function startApp() {
  var app = angular.module('app', []);

  return app;
}
```

Or something like that because functions get hoisted. I'm guessing they get hoisted above import/exports which is awesome :)

**Comment by JiLiZART** [comment]
I have the same error in 5.8.23 version, i've created repo for reproducing https://github.com/JiLiZART/babel-import-bug

**Comment by loganfsmyth** [comment]
@JiLiZART You have a circular dependency, you'll need to do something to ensure that the modules have loaded first before building up the relationships. If you want to chat and get more support, please join the Babel [Slack community](https://babel-slack.herokuapp.com/). This issue queue is for bug reports, not support.
