### ISSUE TITLE
Decorator declaration syntax seemingly completely unsupported

### ISSUE THREAD

**Issue by DullReferenceException** [babel/babel#11507]
## Bug Report

In looking through [the TC39 explainer](https://github.com/tc39/proposal-decorators), I have attempted to define a decorator thusly:

```js
const cacheMap = Symbol('cacheMap');

export decorator @memo {
  @wrap(fn => function (...args) {
    let cache = this[cacheMap]
    if (!cache) {
      cache = this[cacheMap] = new Map();
    }
                 
    const key = JSON.stringify(args);
    if (cache.has(key)) {
      return cache.get(key);
    }

    cache.set(key, fn.apply(this, args));
  })
}
```

Sadly, I get a syntax error as soon as what should be the `decorator` keyword is encountered:

> Unexpected token, expected "{"

I've whittled down my `.babelrc` to just this, and the problem still occurs:

```
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      decoratorsBeforeExport: true
    }]
  ]
}
```

Oddly, I'm not seeing a lot of material on the web about the TC39 syntax shown in that document, even though it _is_ the stage 2 proposal.

What am I missing here?

Sorry, I'd post a playground link, but `@babel/plugin-proposal-decorators` completely fails to load unless configuration options are supplied, and the playground interface doesn't let you set options (or perhaps the plugin has _another_ reason it's not loading).

**Environment**

```
npx: installed 1 in 32.706s

  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  npmPackages:
    @babel/cli: ^7.0.0 => 7.1.2
    @babel/core: ^7.9.6 => 7.9.6
    @babel/plugin-proposal-decorators: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-object-rest-spread: ^7.0.0 => 7.0.0
    @babel/plugin-proposal-optional-chaining: ^7.0.0 => 7.0.0
    @babel/preset-env: ^7.0.0 => 7.1.0
    @babel/preset-flow: ^7.0.0 => 7.0.0
    @babel/register: ^7.0.0 => 7.0.0
    babel-eslint: ^10.1.0 => 10.1.0
    babel-plugin-add-module-exports: ^0.2.1 => 0.2.1
    eslint: ^6.8.0 => 6.8.0
    eslint-plugin-babel: ^5.3.0 => 5.3.0
```

I'm using babel's cli, though the error also shows up in eslint using the babel parser.

**Comment by DullReferenceException** [comment]
OK, I think I've finally found the info that the current stage-2 proposal is _not_ implemented by anyone, either Babel or TypeScript.

Maybe this ticket should be morphed into a plea to update the [documentation on the babel plugin](https://babeljs.io/docs/en/babel-plugin-proposal-decorators) so it clarifies that it does _not_ support the current proposal but only an earlier proposal.

**Comment by nicolo-ribaudo** [comment]
Closing because this syntax has been removed by the proposal. We still don't support the fourth proposal version, but there are other issues to track it.
