### ISSUE TITLE
Should we combine the transform-runtime and preset-env in an application?

### ISSUE THREAD

**Issue by NE-SmallTown** [babel/babel#11515]
## Question 1

I find that there are many unnecessary duplications in the (webpack) bundle (output)result, to be specific, they all are the helpers(like `classCheck`, `objectSpread`(due to the `object-spread` plugin).

So, I want to reduce the duplications. If it's a library, sure, I will use transform-runtime plugin(refer to `runtime-corejs3`) to do this. But now this is an **application**, so, what's the correct way to do this?

Therefor I'm getting confused because the `transfrom-runtime` plugin is recommended **for library**(and is for the whole reduction. i.e. `core-js`, `regenerator` and the helpers). But here I **just** want to reduce the **helper** duplications, not others duplications because that **has been done** by `preset/env`.

So here the question I want to ask/discuss is that **is** it necessary to reduce the `helpers` duplications in an **application**, if yes, and how?

## Question 2

The other question is, `core-js/modules/es.promise.js` and  `core-js-pure/modules/es.promise.js` are exactly the same code, the main difference just is that the former has global pollution? If so, why `core-js` doesn't use(directly import) `core-js-pure` to polyfill and then add it to global? IMO, this will greatly reduce the duplications because at now the libs use `transform-runtime`(finally `core-js-pure`) but apps use `preset-env`(finally `core-js`), there is no shared/shareable codes between apps and libs, right?

**Comment by nicolo-ribaudo** [comment]
The docs are confusing: `@babel/transform-runtime`'s `corejs` option is recommended for applications, but it's not discouraged for libraries. We only want to discourage using any polyfill injecting method that is not `@babel/transform-runtime`'s `corejs` option when creating libraries.

Also, we are currently reworking our methods to inject polyfill to unify them: https://github.com/babel/babel/issues/10008

> If so, why core-js doesn't use(directly import) core-js-pure to polyfill and then add it to global?

This should be asked in the `core-js` repository :shrug:

**Comment by JMarkoski** [comment]
Answer to the first question: To reduce the helper duplication you should use the `@babel/transform-runtime` plugin together with the `@babel/runtime` dependency. The `corejs` option of the `@babel/transform-runtime` plugin should be set to `false`. This way the plugin will alias the helpers to the `@babel/runtime` dependency, and every helper will be included only once in the application, thus reducing the size. For more thorough answer, see here: [https://github.com/babel/babel/issues/9853#issuecomment-619587386](https://github.com/babel/babel/issues/9853#issuecomment-619587386)

**Comment by NE-SmallTown** [comment]
Thanks, it's more clear now!

The second question has beeen refered to https://github.com/zloirock/core-js/issues/833
