### ISSUE TITLE
Assert fail

### ISSUE THREAD

**Issue by alanhg** [babel/babel#11510]
Errors are confusing me.

I found switch syntax cause the error
 
**Webpack Version:**
    "webpack": "4.17.1",

**Babel Core Version**:
    "@babel/core": "7.9.6",

**Babel Loader Version**:
    "babel-loader": "8.1.0",

**Please tell us about your environment:**
OSX 10.15.4 

**Current behavior:**
> ERROR in ./src/main/webapp/app/components/lead-info/leadSearchForm.tsx
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Assert fail

![image](https://user-images.githubusercontent.com/9245110/80856225-8bf1cd80-8c7a-11ea-932e-76fb4cd8d41c.png)

**Expected/desired behavior:**

build success

**Comment by nicolo-ribaudo** [comment]
Could you share the contents of `leadSearchForm.tsx`, or a minimal example which reproduces the bug?

**Comment by alanhg** [comment]
> Could you share the contents of `leadSearchForm.tsx`, or a minimal example which reproduces the bug?

I fixed by refactor the code. I found switch in render logic code can lead to the issue
