### ISSUE TITLE
IIFE problem

### ISSUE THREAD

**Issue by dehghani-mehdi** [babel/babel#11513]
Consider [this babeljs.io/en/repl](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAHhC8EAoBmBXAdgYwC4EsD2aCAlBAN4BQEEGBAzngDYCmAdA3gOYIDkL3RAbnIBfIsSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=) example, the output should be:

```js
var x = (function () {
  console.log('.');
})();
```

Instead of:

```js
var x = function () {
  console.log('.');
}();
```

**Comment by nicolo-ribaudo** [comment]
Those two outputs have the same behaviour.
