### ISSUE TITLE
Outdated dependency: Chokidar v2 incompatible with Nodejs v14

### ISSUE THREAD

**Issue by csvan** [babel/babel#11516]
## Bug Report

**Current Behavior**

Installing Babel on a Nodejs system yields the warning:

`warning @babel/cli > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`

**Expected behavior/code**
Babel should not have a dependency on Chokidar2, but rather 3.

**Environment**

```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.0.0 => 7.8.4 
    @babel/register: ^7.0.0 => 7.9.0 
    babel-eslint: ^10.0.0 => 10.1.0 

```

**Possible Solution**

Upgrade to Chokidar3, there should be no breaking changes. See https://github.com/webpack/watchpack/issues/130

**Comment by existentialism** [comment]
@csvan check out https://github.com/babel/babel/issues/11488#issuecomment-619614369 for more details (also https://github.com/babel/babel/pull/10741)

**Comment by csvan** [comment]
Thanks @existentialism! Closing this
