### ISSUE TITLE
`export interface` throws "Unexpected token" error

### ISSUE THREAD

**Issue by Arnavion** [babel/babel#1151]
```javascript
export interface Set<T> {
	/**
	 * @param {T} value
	 * @return {libjass.Set.<T>} This set
	 */
    add(value: T): Set<T>;
}
```

```
SyntaxError: ./foo.ts: Unexpected token (1:17)
> 1 | export interface Set<T> {
    |                  ^
  2 |   /**
  3 |    * @param {T} value
  4 |    * @return {libjass.Set.<T>} This set
    at Parser.pp.raise (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\location.js:68:13)
    at Parser.pp.unexpected (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\parseutil.js:87:8)
    at Parser.pp.expectContextual (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\parseutil.js:46:39)
    at Parser.pp.parseExportFrom (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:650:8)
    at Parser.pp.parseExport (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:596:10)
    at Parser.pp.parseStatement (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:102:71)
    at Parser.parseStatement (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\plugins\flow.js:631:22)
    at Parser.pp.parseTopLevel (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:22:21)
    at Object.parse (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\index.js:109:12)
    at module.exports (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\babel\helpers\parse.js:39:21)
```

It compiles fine without the `export`

**Comment by sebmck** [comment]
Is this valid Flow syntax?

On Saturday, 4 April 2015, Arnav Singh <notifications@github.com> wrote:

> export interface Set<T> {
>     /**     * @param {T} value     * @return {libjass.Set.<T>} This set     */
>     add(value: T): Set<T>;
> }
>
> SyntaxError: ./foo.ts: Unexpected token (1:17)
> > 1 | export interface Set<T> {
>     |                  ^
>   2 |   /**
>   3 |    * @param {T} value
>   4 |    * @return {libjass.Set.<T>} This set
>     at Parser.pp.raise (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\location.js:68:13)
>     at Parser.pp.unexpected (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\parseutil.js:87:8)
>     at Parser.pp.expectContextual (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\parseutil.js:46:39)
>     at Parser.pp.parseExportFrom (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:650:8)
>     at Parser.pp.parseExport (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:596:10)
>     at Parser.pp.parseStatement (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:102:71)
>     at Parser.parseStatement (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\plugins\flow.js:631:22)
>     at Parser.pp.parseTopLevel (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:22:21)
>     at Object.parse (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\index.js:109:12)
>     at module.exports (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\babel\helpers\parse.js:39:21)
>
> It compiles fine without the export
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1151>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
cc @jeffmo

On Saturday, 4 April 2015, Sebastian McKenzie <sebmck@gmail.com> wrote:

> Is this valid Flow syntax?
>
> On Saturday, 4 April 2015, Arnav Singh <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> export interface Set<T> {
>>     /**     * @param {T} value     * @return {libjass.Set.<T>} This set     */
>>     add(value: T): Set<T>;
>> }
>>
>> SyntaxError: ./foo.ts: Unexpected token (1:17)
>> > 1 | export interface Set<T> {
>>     |                  ^
>>   2 |   /**
>>   3 |    * @param {T} value
>>   4 |    * @return {libjass.Set.<T>} This set
>>     at Parser.pp.raise (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\location.js:68:13)
>>     at Parser.pp.unexpected (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\parseutil.js:87:8)
>>     at Parser.pp.expectContextual (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\parseutil.js:46:39)
>>     at Parser.pp.parseExportFrom (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:650:8)
>>     at Parser.pp.parseExport (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:596:10)
>>     at Parser.pp.parseStatement (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:102:71)
>>     at Parser.parseStatement (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\plugins\flow.js:631:22)
>>     at Parser.pp.parseTopLevel (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\statement.js:22:21)
>>     at Object.parse (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\acorn\src\index.js:109:12)
>>     at module.exports (G:\src\babel\packages\babel-cli\node_modules\babel-core\lib\babel\helpers\parse.js:39:21)
>>
>> It compiles fine without the export
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/babel/babel/issues/1151>.
>>
>
>
> --
> Sebastian McKenzie
>


-- 
Sebastian McKenzie

**Comment by Arnavion** [comment]
It's valid TypeScript. Flow gives me `/stuff/src/flow-experiments/foo/test.js:5:8,16: Use of future reserved word in strict mode`

**Comment by sebmck** [comment]
Why should Babel parse Typescript?

On Saturday, 4 April 2015, Arnav Singh <notifications@github.com> wrote:

> It's valid TypeScript. Flow gives me /stuff/src/flow-experiments/foo/test.js:5:8,16:
> Use of future reserved word in strict mode
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1151#issuecomment-89405915>.
>


-- 
Sebastian McKenzie

**Comment by Arnavion** [comment]
See updated comment.

**Comment by Arnavion** [comment]
Bah, nvm. The initial error was correct. I forgot `flow check` doesn't typecheck without a `@flow` comment.

So you don't intend to have babel parse TS then?

**Comment by jeffmo** [comment]
This isn't currently valid Flow syntax, but I believe it's valid TypeScript.

For the purposes of Babel, at least, I'd say it's up to Babel to decide if this is something they wish to support. There are other small syntactic differences between TypeScript and Flow code right now as well: TypeScript's legacy module syntax (`export =`) is TS but not Flow, [Expression Typecasts](http://flowtype.org/blog/2015/02/18/Typecasts.html) (`var a = (null: ?number);`) are Flow but not TypeScript, as is the shorthand [Bounded Polymorphism](http://flowtype.org/blog/2015/03/12/Bounded-Polymorphism.html) (`:` instead of `extends`). There might be others that I can't recall off the top of my head).

Flow might add `interface` at some point in the future, but it's not a near-term priority right now (Flow uses type aliases via `type = ...` for many cases where interfaces are used in TypeScript).

**Comment by Arnavion** [comment]
Yes, `type` can be used instead of `interface` with TS as well, except that [TS doesn't support generic type aliases yet.](https://github.com/Microsoft/TypeScript/issues/1616)

As I checked with Jeff in #flowtype , the Flow equivalent for types across module boundaries might look like `export type Set<T> = { ... }` and a corresponding `import type { Set } from "set";` as he mentioned in [this comment.](https://github.com/facebook/jstransform/pull/54#issuecomment-68902713)

**Comment by sebmck** [comment]
@Arnavion 

> So you don't intend to have babel parse TS then?

No reason for it too. As I said in #1152, there are certain things that are ambiguous with the use of both Flow and JSX so the entire TypeScript syntax can't really be supported. Even if it could, supporting TypeScript **and** Flow would be terrible confusing.
