### ISSUE TITLE
RangeError: maximum call stack size exceeded when using require to import a second file

### ISSUE THREAD

**Issue by daveneeley** [babel/babel#11521]
## Bug Report

**Current Behavior**
When I run `yarn test` or `yarn coverage`, the test suite Bot.tests.js fails with
```
tests/Bot.test.js
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      1 | /* global require */
      2 | /* instanbul ignore next */
    > 3 | if (typeof(require) !== undefined) {
        |                 ^
      4 |   var Chat = require('./Help.js')['default'];
      5 | }
      6 | var Bot = {

      at _typeof (src/Bot.js:3:17)
      at _typeof (src/Bot.js:3:88)
      (previous line repeated 97 times)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.824 s
Ran all test suites.
```

**Input Code**
Linked code reproduces the issue.
https://gist.github.com/daveneeley/89cc99d4741d880b988688664408eeae

**Expected behavior/code**
I expect `yarn test` or `yarn coverage` to pass all test suites.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
    "presets": ["env"]
}
```

**Environment**
```
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 10.16.3 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.4 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.4 - ~\scoop\apps\nodejs-lts\current\bin\npm.CMD
  npmPackages:
    @babel/core: ^7.9.6 => 7.9.6
    babel-jest: ^26.0.0 => 26.0.0
    babel-preset-env: ^1.7.0 => 1.7.0
    jest: ^26.0.0 => 26.0.0
```
- Monorepo: [e.g. yes/no/Lerna] I don't know what this means :)
- How you are using Babel: called by jest

**Comment by daveneeley** [comment]
Related: https://github.com/babel/babel/issues/9127

**Comment by existentialism** [comment]
First thing to check is that you’re mixing v7 (@babel/core) and v6 (babel-preset-env) dependencies. You’ll want to switch to @babel/preset-env.

**Comment by daveneeley** [comment]
babel-jest wants babel-preset-env, it doesn't compile if I upgrade. If I downgrade babel-core to 6.26.3, the error still reproduces. Updated gist.

**Comment by daveneeley** [comment]
However, if I delete node_modules and try revision 4 of the gist, it passes! Though it takes 21 seconds. So @babel/core and @babel/preset-env work after all, my babel config was wrong for that scenario.
