### ISSUE TITLE
Support TS / flow type assertions

### ISSUE THREAD

**Issue by Arnavion** [babel/babel#1152]
The `<T>` syntax before an expression asserts that the expression is of type T (somewhat like typecasts in other languages, but no runtime behavior).

```javascript
var x: string | string[];
if (Array.isArray(x)) {
    console.log((<string[]>x).length);
}
```

Should be stripped unless `flow` is blacklisted.

**Comment by sebmck** [comment]
I don't think flow has these. It's syntactically ambiguous to JSX. See
http://flowtype.org/blog/2015/02/18/Typecasts.html

On Saturday, 4 April 2015, Arnav Singh <notifications@github.com> wrote:

> The <T> syntax before an expression asserts that the expression is of
> type T (somewhat like typecasts in other languages, but no runtime
> behavior).
>
> var x: string | string[];if (Array.isArray(x)) {
>     console.log((<string[]>x).length);
> }
>
> Should be stripped unless flow is blacklisted.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1152>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
cc @jeffmo

On Saturday, 4 April 2015, Sebastian McKenzie <sebmck@gmail.com> wrote:

> I don't think flow has these. It's syntactically ambiguous to JSX. See
> http://flowtype.org/blog/2015/02/18/Typecasts.html
>
> On Saturday, 4 April 2015, Arnav Singh <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> The <T> syntax before an expression asserts that the expression is of
>> type T (somewhat like typecasts in other languages, but no runtime
>> behavior).
>>
>> var x: string | string[];if (Array.isArray(x)) {
>>     console.log((<string[]>x).length);
>> }
>>
>> Should be stripped unless flow is blacklisted.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/babel/babel/issues/1152>.
>>
>
>
> --
> Sebastian McKenzie
>


-- 
Sebastian McKenzie

**Comment by Arnavion** [comment]
Ah, okay, I didn't know flow's syntax was different. It seems it's a one-to-one correspondence so I should be able to convert flow's syntax to typescript's with post-processing.

**Comment by weswigham** [comment]
In Typescript's own upcoming JSX support [here](https://github.com/Microsoft/TypeScript/pull/3564) to resolve the ambiguity they've decided that typescript files with jsx in them (tsx) no longer have access to xml-style type assertions. Instead they must use the new 'as' keyword style assertions. Is this a change that makes supporting typescript alongside jsx more workable again?
