### ISSUE TITLE
Difference between JSX prop="\n" vs prop={"\n"}.

### ISSUE THREAD

**Issue by jillesme** [babel/babel#11526]
## Bug Report

- [X] I would like to work on a fix! (_May take a while due to time constraints so if anyone else would like to, feel free!_)

**Current Behavior**
See input/output code. Result is different for these 2 components:

![image](https://user-images.githubusercontent.com/2955483/81123566-37538a00-8ee8-11ea-8f62-d995c392554f.png)

- [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAsgTwMIgLYAdwFMywLwwAUA3ugE4joC-AlDHgHxEBQMMAPBOgIZgOkV0AOgA2OAOZQAFlXYB6LrwbMaAbmbN2AEwCWAN2UBIdohQZsuGOUp5iAIgA6YO1RhyjJ5Gkxgcsa-h4js5uyvK6BkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-3&prettier=false&targets=&version=7.9.6&externalPlugins=), [CodePen](https://codepen.io/practual/pen/PoPELWX?editors=1010)

**Input Code**

```jsx
<>
  <MyComponent prop={"\n"} />
  <MyComponent prop="\n" />
</>
```

**Expected behavior/code**
I expect the outputted JSX to be:

```js
React.createElement(React.Fragment, null, 
  React.createElement(MyComponent, { prop: "\n" }), 
  React.createElement(MyComponent, { prop: "\n" })
);
```

Actual output is:

```js
React.createElement(React.Fragment, null, 
  React.createElement(MyComponent, { prop: "\n" }), 
  React.createElement(MyComponent, { prop: "\\n" })
);
```

**Environment**
```
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  npmPackages:
    @babel/core: 7.1.2 => 7.1.2
    @babel/runtime: 7.1.2 => 7.1.2
    @babel/standalone: 7.1.0 => 7.1.0
    babel-eslint: 10.0.1 => 10.0.1
    babel-loader: 8.0.4 => 8.0.4
```

**Possible Solution**
No time to investigate yet, wondering if this is a bug or expected behavior.

**Comment by thorn0** [comment]
This is expected. `\` doesn't have any special meaning in JSX text and attribute values.
