### ISSUE TITLE
Should ParentClass.call(this); work if ParentClass and its parent is Babel compiled?

### ISSUE THREAD

**Issue by briandipalma** [babel/babel#11525]
## Bug Report

Here's a link to some code which is quite common in our code base. It works OK up to the point that we nuke our yarn.lock file and then it breaks horribly.

https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAKYCcCmA7ALvZ7oG8BQ00wA9ihGggK7BrEIAUAlLgYdGgBYCWEAdAA6JUGIegBqYEJSTQAvNABEARiUKA3KwC-ebXlCQYmYdCQAPNKgAmh0SKxoWhEmQrVaDZvjbQIlfkg8Nb04eAVsJKRl5ZQAGdS0dPDwAM0oUGi5SaABhbhBLJkc4W15gSRB6EIhGVlZnCGIQJF4QYgBzSu4-QXsI6RqnUgamlvbO0J7hI3FJfsS8XK58gQRiWjQAT385aAB5ACMAKyQaUuQwC3pptBW1ta2kABoWAEgXgHJ61xo6d4AuXAmFCUAC2ATA-yaAOSkggTxeADdZkgAYt8tBtC9NIwNHgUEgAO45PIFGp4IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Ces2017%2Creact%2Cstage-3%2Cenv&prettier=true&targets=Node-8.9&version=7.9.6&externalPlugins=

```javascript
class ParentParent {
  constructor() {
    this.parentParentValue = "11";
  }
}

class Parent extends ParentParent {
  constructor() {
    super();
    this.parentValue = "10";
  }
}

function Child() {
  Parent.call(this)
  
  console.log(this.parentValue)
  console.log(this.parentParentValue)
}

Child.prototype = Object.create(Parent.prototype, {
		'constructor': { enumerable: false,	value: Child }
	});

new Child()
```

I would expect 10 and 11 to be logged to the console but they aren't. The fun thing is that if you break the inheritance chain between Parent and ParentParent then 10 is correctly logged...

This is a very painful issue and I'm pretty sure it's a bug. It will make gradual upgrades to ES classes very difficult. Am I correct in my guess?

**Comment by nicolo-ribaudo** [comment]
To be 100% spec compliant, that code should throw because you can't `.call()` a class.

**Comment by briandipalma** [comment]
Hi Nicolò, thanks for replying.

OK, so the older version of Babel that we have in our current yarn.lock files allows us to mingle classical and ES6 classes without an issue but with the newest versions of Babel it's no longer possible as it was a bug to do so. I understand that but what I don't understand is introducing such a change in a patch/minor release?

Our code has gone from working to being broken without a major Babel version rev. We will have to convert classical classes to ES classes to take this new version of Babel. We have done something similar with Babel 6 to 7 and the module changes but that's a major version change.

Is there any quick/easy tweak we can make like using loose spec that would allow us to upgrade the yarn.lock file without having to do the class upgrade work?

**Comment by briandipalma** [comment]
Also it would be good to get some clarity on what is OK to convert. Can an ES class inherit from a classical prototype class? So maybe we can convert from the bottom upwards? If we convert a class that has children we would then have to convert all the children etc all the way down to ES classes correct?

**Comment by briandipalma** [comment]
You can extend a classical prototype class from an ES class but not vice-versa:

```javascript
function Parent() {
  this.parentValue = "10";
}

class Child extends Parent {
  constructor() {
    super();

    console.log(this.parentValue)
  }
}

new Child()

> Object { parentValue: "10" }
> 10
```

```javascript
class Parent {
  constructor() {
    this.parentValue = "10";
  }
}

function Child() {
  Parent.call(this);
  
  console.log(this.parentValue);
}

Child.prototype = Object.create(Parent.prototype, {
  'constructor': { enumerable: false, value: Child }
});

new Child();

> TypeError: class constructors must be invoked with 'new'
```

And `Reflect.construct` is no help:

```javascript
class Parent {
  constructor() {
    this.parentValue = "10";
  }
}

function Child() {
  Reflect.construct(Parent, arguments, this);
  
  console.log(this.parentValue);
}

new Child();

> TypeError: this is not a constructor
```

Back to classical classes for our higher up classes. I don't understand the logic behind that decision in the spec.

**Comment by nicolo-ribaudo** [comment]
With `Reflect.construct`, the 3rd argument should be `new.target` and the return value is the new "`this`".

**Comment by briandipalma** [comment]
> With Reflect.construct, the 3rd argument should be new.target and the return value is the new "this".

Yes but that requires almost as many changes/work as just upgrading the leaf classes to ES classes as you can't replace `this` you have to store the object as `this._self` etc. I'll close this anyway as it's not a bug it's spec behaviour but I'll update it with the version of the babel dependency you need to lock to to prevent this change from causing issues. We're going to upgrade our code and our clients code but lock versions in the meantime.

**Comment by briandipalma** [comment]
```
  "resolutions": {
    "@babel/plugin-transform-classes": "7.8.6"
  }
```

Locks you to a working version.
