### ISSUE TITLE
Expose types of VISITOR_KEYS, ALIAS_KEYS in the @babel/types TypeScript declaration file

### ISSUE THREAD

**Issue by wereHamster** [babel/babel#11528]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**

The linaria project currently uses TypeScript module augmentation to extend the babel types with declarations which are not in the official package. If those two consts are part of the public API, they should be documented in the official package.

```
declare module '@babel/core' {
  namespace types {
    type AllNodes = { [T in Node['type']]: Extract<Node, { type: T }> };

    type VisitorKeys = {
      [T in keyof AllNodes]: Extract<
        keyof AllNodes[T],
        {
          [Key in keyof AllNodes[T]]: AllNodes[T][Key] extends
            | Node
            | Node[]
            | null
            ? Key
            : never;
        }[keyof AllNodes[T]]
      >;
    };

    const VISITOR_KEYS: { [T in keyof VisitorKeys]: VisitorKeys[T][] };
    const ALIAS_KEYS: {
      [T in Node['type']]: {
        [K in keyof Aliases]: AllNodes[T] extends Aliases[K] ? K : never;
      }[keyof Aliases][];
    };

    const FLIPPED_ALIAS_KEYS: {
      [T in keyof Aliases]: Aliases[T]['type'][];
    };
  }
}
```

**Comment by JLHwung** [comment]
The `types` exports in `@babel/core` are forwarded from `@babel/types`, can you add the type definition to `packages/babel-types/scripts/generators/typescript.js`?

**Comment by nicolo-ribaudo** [comment]
Those types are now exposed by `@babel/types`: https://unpkg.com/browse/@babel/types@7.12.12/lib/index.d.ts (line 2302).
