### ISSUE TITLE
@babel/polyfill 7.8.7 still uses core-js 2 while @babel/node uses 3

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#11536]
Hopefully this isn't intentional...
```
$ npm ls core-js
@jcoreio/clarity-gateway@1.5.5 /Users/andy/clarity-gateway
├─┬ @babel/node@7.8.7
│ └── core-js@3.6.5 
├─┬ @babel/polyfill@7.8.7
│ └── core-js@2.6.11 
```

**Comment by nicolo-ribaudo** [comment]
`@babel/polyfill` is deprecated, and we encourage directly including the `core-js` version that you need.

**Comment by nicolo-ribaudo** [comment]
I realized that we have the deprecation notice in the docs and in the readme, but never used `npm deprecate`. I just fixed it.

**Comment by jedwards1211** [comment]
Gotcha, thanks!
