### ISSUE TITLE
@babel/standalone can't parse any quantifiers in unicode regexes

### ISSUE THREAD

**Issue by rhendric** [babel/babel#11534]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

It's right there in the title. Something about the @babel/standalone compilation process causes it to omit critical parts of regjsparser, such that any regex literal with a `u` flag and a quantifier will cause Babel to incorrectly raise a syntax error.

Can be reproduced [on babeljs.io](https://babeljs.io/repl#?code_lz=PQQwVMCuQ&presets=es2015).

**Input Code**

```js
/a*/u
```

**Expected behavior/code**

It should parse valid regexes correctly.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

```js
{ presets: ['es2015'] }
```

**Environment**

- Babel version(s): 7.9.6
- Node/npm version: N/A
- OS: N/A
- Monorepo: N/A
- How you are using Babel: standalone

**Comment by nicolo-ribaudo** [comment]
Rollup is removing this code:
https://github.com/jviereck/regjsparser/blob/03d4486ec43184c1e6a18a871308d7ba1825c992/parser.js#L488-L495
