### ISSUE TITLE
@types/babel__traverse is missing several isXXX methods

### ISSUE THREAD

**Issue by vedantroy** [babel/babel#11535]
## Bug Report

- [Maybe (depends on complexity) ] I would like to work on a fix!

**Current Behavior**
The type definition for `NodePath` is missing some isXXX methods.

**Input Code**

```typescript
function example(path: NodePath<Node>) {
    // VsCode says this method does not exist on path, but I know it does
    path.isTSType()
}
```

**Expected behavior/code**
`isTSType` (and several other isXXX) should exist on any `path` object. I know they do exist because when I inspect the code while it is running in the debugger, I see the method `path.isTSType()`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
I don't think it is relevant?

**Environment**
```
  System:
    OS: Linux 5.6 EndeavourOS
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v13.9.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.9.0/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    @babel/core: ^7.9.6 => 7.9.6 
    @babel/plugin-transform-modules-commonjs: ^7.9.0 => 7.9.0 
    @babel/plugin-transform-typescript: ^7.9.4 => 7.9.4 
    @babel/preset-env: ^7.9.5 => 7.9.5 
    @babel/register: ^7.9.0 => 7.9.0 
    babel-plugin-macros: ^2.8.0 => 2.8.0 
```
**Possible Solution**
I looked at `index.d.ts` inside of "babel__traverse" in my node_modules folder. There is a section that starts with
```javascript
    // ------------------------- isXXX -------------------------
```
looking at the methods in this section, we can see that several methods are missing.

I don't know if this issue should be filed here. It might just be an issue with the `@types/babel__traverse`. Maybe there should be an automated way to generate the `babel__traverse` types, so the type definitions stay in sync with Babel? I feel like having Babel use Typescript would allow the type definition files to stay in sync with the codebase, and I'd be willing to take a look into that once I get some time (I know that someone has already done some work in translating Babel to Typescript).

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report!

The TypeScript type definitions are not maintained by us, but at https://github.com/DefinitelyTyped/DefinitelyTyped: please report the bug there!

Btw, we are thinking about providing official type definitions, but that's a longer-term goal.
