### ISSUE TITLE
[Feature/Discussion] Babel for Deno

### ISSUE THREAD

**Issue by Soremwar** [babel/babel#11543]
# Babel for Deno

**Is your feature request related to a problem? Please describe.**
Deno reaches v1.0 on two days. There has been some discussion inside the repo on how to produce reliable polyfills and transpilation inside Deno. The runtime itself has the capabilities to make some level of transpilation through the TSC compiler, but the quality and usability of it isn't really aimed for all JavaScript environments (yet!).

**Describe the solution you'd like**
To setup an integration of Babel with Deno that can realistically transpile any sorts of JavaScript code served by Deno, making it usable in all environments.

**Teachability, Documentation, Adoption, Migration Strategy**
Technical pros of supporting Deno:
-  More accurate module resolution. Deno uses JavaScript resolution system, which you should be able to inspect through the V8 bindings Deno provides.
- Deno native compiler/bundler. Deno already has built-in functionality for this matter, however I'd argue that the best in the business may provide a better insight on how to approach this kind of very-desired functionality. Perhaps your efforts will be merged into Deno at some point!
- Easier mantainability across versions. 
- Better asynchronous support.

_On top of that, you could really benefit of this feature._
[Open Compiler's API](https://github.com/denoland/deno/issues/1739)

That said, I'm not sure it this is an easy or hard task. In one way, Babel only would have to support native JS since Deno doesnt use any syntaxis not implemented in the ECMA especifications (like require or commonJS). In the other, Babel is most likely tweaked to perform those exact operations, so a refactor might be inminent.

Congratulations on your great work and your support to the JavaScript community!

**Comment by xtuc** [comment]
I'm not very familiar with Deno but my understanding is that it uses TypeScript instead of JavaScript. While Babel supports TypeScript, i'm unsure to understand why we would use it instead of TypeScript itself? Maybe I misunderstand what you are suggesting

**Comment by Soremwar** [comment]
Hi @xtuc.

Even though Deno does treat TypeScript as a first class language, internally all the code is transpiled and run though the V8 engine, in that way, it's very similar to Node.

One trick that Deno manages to pull off is using the TSC compiler of TypeScript to both compile TypeScript to JavaScript and JavaScript to a lower-more supported version. However, as I mentioned earlier, this doesn't cover any internal API's used by Deno, and doesn't do polyfills for features such as Promises. That means that even though the code can be run under Deno, it's not possible to use it in the browser right away, which would be very convenient.

One example that really bothers me. React has worked in Deno for a while now. But the code produced by Deno's transpiler doesn't contain any of this stuff, meaning that it can't be distributedin any browser realistically.

**Comment by SaekiRaku** [comment]
Hi, @xtuc I have a use-case for now.

I'm writing a program that needs to deal with the React + JSX files, I want to use `@babel/core` to transform the code string to AST. But `Deno` can only import ES Modules and `@babel/core` provides a CommonJS module for now.

I'm not sure how complex that make babel support Deno, I'm no pro at it. In my case, I think if `@babel/core` only deal with code string and transform, provide an ES version maybe can make it be used in `Deno` directly? I'm not sure, just guessing, you can pass this paragraph.

**Comment by luke-john** [comment]
@SaekiRaku, just a note, I was able to use babel/core via jspm in deno, it works, but you don't have any typesafety.

```ts
import babelCore from "https://dev.jspm.io/@babel/core";
import babelSyntaxJsx from "https://dev.jspm.io/@babel/plugin-syntax-jsx";

const result = babelCore.transform(svgText, {
    plugins: [babelSyntaxJsx],
    configFile: false,
  })
```

**Comment by timreichen** [comment]
```ts
import babelCore from "https://dev.jspm.io/@babel/core"
import babelPresetEnv from "https://dev.jspm.io/@babel/preset-env"

```

How to specify ```targets``` ?

**Comment by luke-john** [comment]
Just tested and the standard api seems to work in deno for `targets`.

```ts
import babelCore from "https://dev.jspm.io/@babel/core";
import babelPresetEnv from "https://dev.jspm.io/@babel/preset-env";

const code = `const foo = "bar"`;
const config = {
  presets: [[babelPresetEnv, { targets: "> 0.25%, not dead" }]],
};

babelCore.transform(code, config);
```

**Comment by timreichen** [comment]
Thank you! Works perfectly now!

**Comment by brainkim** [comment]
This issue is related to #11701 and potentially solved by #11938. JSPM is great, but I’m squeamish about relying on an artifact which only exists in the æther, especially because I still have no idea how to find relevant d.ts files on JSPM. If babel ships an ESM version it would potentially be available via unpkg as well.

**Comment by shardyMBAI** [comment]
babel/core seems broken in deno@1.5.1 and up.

<img width="619" alt="Screen Shot 2020-11-10 at 11 53 55 AM" src="https://user-images.githubusercontent.com/27963753/98705180-6f320300-234b-11eb-8433-52499009248e.png">

**Comment by shardyMBAI** [comment]
I found a fix for the above, add `--no-check` to the deno options to skip type checks against babel

I call my script like so

```
deno run -r --allow-read --allow-run --no-check ./.github/workflows/scripts/npm_release_files/babel_ts_serialize.ts > dist/ts_serialize.js
```

and the script contents are

```ts
import babelCore from "https://dev.jspm.io/npm:@babel/standalone";
import babelPluginProposalClassProperties from "https://dev.jspm.io/npm:@babel/plugin-proposal-class-properties";
import babelPluginProposalOptionalChaining from "https://dev.jspm.io/npm:@babel/plugin-proposal-optional-chaining";
const p = Deno.run({
  cmd: ["deno", "bundle", "./mod.ts"],
  stdout: "piped",
  stderr: "piped",
});
const { code } = await p.status();

if (code === 0) {
  const source = await p.output();
  const { transform } = babelCore as any;
  const { code } = transform(
    new TextDecoder().decode(source),
    {
      filename: "dist/ts_serialize.js",
      presets: ["env"],
      plugins: [
        babelPluginProposalClassProperties,
        babelPluginProposalOptionalChaining,
      ],
    },
  );
  const encoded = new TextEncoder().encode(code);
  let written = 0;
  while (written < encoded.length) {
    written += await Deno.stdout.write(encoded.slice(written));
  }
} else {
  const rawError = await p.stderrOutput();
  const errorString = new TextDecoder().decode(rawError);
  console.log(errorString);
}
```

**Comment by nicolo-ribaudo** [comment]
Fwiw, we are starting to migrate the monorepo to TS and we'll start publishing ECMAScript modules in Babel 8.

We have no plan to support Deno, but maybe that will increase compatiblity.

**Comment by shardyMBAI** [comment]
@nicolas-marien thank you for the response! Babel is amazing

**Comment by nicolo-ribaudo** [comment]
Closing because of https://github.com/babel/babel/issues/11543#issuecomment-724959695: we have no plans to support Deno, but it _might work_ starting from Babel 8.
