### ISSUE TITLE
TypeScript & @babel/plugin-proposal-class-properties -- `_defineProperty` is called for abstract properties

### ISSUE THREAD

**Issue by KB1RD** [babel/babel#11542]
## Bug Report
- [ ] I would like to work on a fix! (Maybe... Depends on how involved it is)

**Input Code**
This issue appears specific to @babel/plugin-proposal-class-properties and TypeScript. Here is the input TypeScript:
```ts
abstract class A {
  abstract test: number
}
class B extends A {
  get test(): number {
    return 5
  }
}

console.log(new B().test) // Should be 5
                          // Actually is undefined
```
Also in [this](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=IYIwzgLgTsDGEAJYBthjAgggg3gKAQVEhngQgFNIAuBAOwFcBbECqPAXzxTQwCEEFAB6U6AEwzZ8hAOYVElSAAoAlLUYs2uAoQRR5DKHQQBWHVy7cA9nTBXkFAHTIrMpXQoB3BH1WPFECoIAPTBCADKABZWDMhiCKymOropqWlpoVjwDMDIyACeCACWGAziFABmRR5iQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.8.3) repl.

**Current Behavior**
The above code compiles into this:
```js
"use strict";

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

class A {
  constructor() {
    _defineProperty(this, "test", void 0);
  }

}

class B extends A {
  get test() {
    return 5;
  }

}

console.log(new B().test); // Should be 5
// Actually is undefined
```
This code logs `undefined` into console.

**Expected behavior/code**
This code should log `5` to the console. Instead, it logs `undefined.` For any additional information, see the repl.

In plain JS, if a property is declared in a superclass, a getter in the subclass cannot change its value even if it is set to `undefined`.  This leads to the behavior above where `undefined` is logged. The implication in TS when specifying an abstract property is that the property has *no* value, not that its value is undefined. When `_defineProperty` is placed in the resulting code, this sets the value of that property to undefined, which is not consistent with non-Babel TypeScript compilers and leads to the unexpected `undefined`.

**Comment by KB1RD** [comment]
So I've traced it down to [this](https://github.com/babel/babel/blob/master/packages/babel-helper-create-class-features-plugin/src/index.js#L177) line of code:
```js
if (prop.node.static) continue;
```
It seems like this should also check if the prop is abstract as well as static. However, it seems like the prop object has no member indicating that it is abstract.

**Comment by KB1RD** [comment]
Fixed on fork https://github.com/KB1RD/babel/commit/236d0a359828405e6d35c0ed5a5300089e5cedc7

**Comment by jridgewell** [comment]
This is the correct behavior when comparing against typescript, see https://www.typescriptlang.org/play/index.html?useDefineForClassFields=true#code/IYIwzgLgTsDGEAJYBthjAgggg3gKAQVEhngRGABMAuBAOwFcBbEAUygG48CFLWVgUVkXDQ4iAOYB7KTXrM2nPAF8gA.

This would need to be changed in typescript first.

**Comment by KB1RD** [comment]
My apologies... I had [tested with `useDefineForClassFields` disabled.](https://www.typescriptlang.org/play/#code/IYIwzgLgTsDGEAJYBthjAgggg3gKAQVEhngQgFNIAuBAOwFcBbECqPAXzzxTQwCEEFAB6U6AEwzZ8hAOYVElSAAoAlLgKEEUBQyh0EAVk1cOQA) This is the default option in TypeScript playground, so I had assumed it was a bug. I have since read https://www.typescriptlang.org/v2/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier and enabled [`allowDeclareFields`](https://babeljs.io/docs/en/babel-preset-typescript#allowdeclarefields).
