### ISSUE TITLE
Decorators in object literals trigger SyntaxError

### ISSUE THREAD

**Issue by rwjblue** [babel/babel#1154]
Object literal syntaxes for `es7.decorators` seem unsupported at the moment.

### Object Literal Method Declaration

Described at: [wycats/javascript-decorators#object-literal-method-declaration](https://github.com/wycats/javascript-decorators#object-literal-method-declaration)

Syntax:

```javascript
var object = {
  @fooDecorator('some', 'stuff')
  bar() { }
}
```

### Object Literal Accessor Declaration

Described at: [wycats/javascript-decorators#object-literal-accessor-declaration](https://github.com/wycats/javascript-decorators#object-literal-accessor-declaration)

Syntax:

```javascript
var object = {
  @fooDecorator('some', 'stuff')
  get bar() { }
  set bar(value) { }
}
```

---

Reproduction steps:

```javascript
var babel = require('babel');

var content = "var o = {\n" +
              "  @fooDecorator('some', 'blah')\n" +
              "  blah() { }\n" +
              "};";

var babelOutput = babel.transform(content, {
  optional: ["es7.decorators"]
});
```

```
/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: unknown: Unexpected token (2:2)
  1 | var o = {
> 2 |   @fooDecorator('some', 'blah')
    |   ^
  3 |   blah() { }
  4 | };
    at Parser.pp.raise (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseIdent (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:717:10)
    at Parser.pp.parsePropertyName (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:604:92)
    at Parser.pp.parseObj (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:555:12)
    at Parser.pp.parseExprAtom (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:347:19)
    at Parser.parseExprAtom (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:162)
    at Parser.pp.parseExprSubscripts (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:212:19)
    at Parser.pp.parseMaybeUnary (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:194:19)
    at Parser.pp.parseExprOps (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:150:19)
```

**Comment by sebmck** [comment]
> Object literal syntaxes for es7.decorators seem unsupported at the moment.

Correct.

On Saturday, 4 April 2015, Robert Jackson <notifications@github.com> wrote:

> Object literal syntaxes for es7.decorators seem unsupported at the moment.
> Object Literal Method Declaration
>
> Described at:
> wycats/javascript-decorators#object-literal-method-declaration
> <https://github.com/wycats/javascript-decorators#object-literal-method-declaration>
>
> Syntax:
>
> var object = {
>   @fooDecorator('some', 'stuff')
>   bar() { }
> }
>
> Object Literal Accessor Declaration
>
> Described at:
> wycats/javascript-decorators#object-literal-accessor-declaration
> <https://github.com/wycats/javascript-decorators#object-literal-accessor-declaration>
>
> Syntax:
>
> var object = {
>   @fooDecorator('some', 'stuff')
>   get bar() { }
>   set bar(value) { }
> }
>
> ------------------------------
>
> Reproduction steps:
>
> var babel = require('babel');
> var content = "var o = {\n" +
>               "  @fooDecorator('some', 'blah')\n" +
>               "  blah() { }\n" +
>               "};";
> var babelOutput = babel.transform(content, {
>   optional: ["es7.decorators"]
> });
>
> /Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
>     throw err;
>           ^
> SyntaxError: unknown: Unexpected token (2:2)
>   1 | var o = {
> > 2 |   @fooDecorator('some', 'blah')
>     |   ^
>   3 |   blah() { }
>   4 | };
>     at Parser.pp.raise (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:68:13)
>     at Parser.pp.unexpected (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
>     at Parser.pp.parseIdent (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:717:10)
>     at Parser.pp.parsePropertyName (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:604:92)
>     at Parser.pp.parseObj (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:555:12)
>     at Parser.pp.parseExprAtom (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:347:19)
>     at Parser.parseExprAtom (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:162)
>     at Parser.pp.parseExprSubscripts (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:212:19)
>     at Parser.pp.parseMaybeUnary (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:194:19)
>     at Parser.pp.parseExprOps (/Users/rjackson/Source/javascript/es6-testing/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:150:19)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1154>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
Yeah, didn't consider it worth the effort for the timebeing because the initial demand (over just class decorators) wasn't there. I'll address this in the next couple weeks though hopefully.

**Comment by rwjblue** [comment]
The use case for me is that I would like to begin work porting the Ember codebase (likely starting with apps) to use decorators (fully realizing that effort will have to be put in to keep them up to date as the spec matures).

I would very much like the following to work:

```javascript
import Component from 'ember-component';
import computed from 'ember-computed';

export default Component.extend({
  @computed('firstName', 'lastName')
  fullName() {
    return `${this.get('firstName')} ${this.get('lastName')}`;
  }
});
```

Due to other issues in our object model we can't yet use `class` syntax...

**Comment by eviltrout** [comment]
I too would love to have this for Ember.js support as the benefits of a `@computed` decorator would be immensely helpful.

(Although @rwjblue I'd suggest having the gets be decorated automatically, and just call the method like `fullName(firstName, lastName)` :) )

**Comment by Aaike** [comment]
:+1: i would love to be able to use decorators for object literals !

**Comment by sebmck** [comment]
I'll do it in this weekend.

**Comment by tfga** [comment]
@rwjblue @eviltrout Like this?

```js
@computed('firstName', 'lastName')
fullName(firstName, lastName) {
    
    return `${firstName} ${lastName}`;
}
```

If this is what you mean, I think your idea seriously rocks.

**Comment by eviltrout** [comment]
@tfga that's exactly what I was thinking! 

The best argument I've heard against it is that some gets are expensive and some computed properties don't need all gets to return the result (via a conditional).

Having said that, I think a `@computed` that performs the gets automatically is what want almost all the time, and much less error prone and prettier than calls to `this.get` everywhere. I wouldn't be against having two decorators, one that does this and one that doesn't.

**Comment by sebmck** [comment]
Released as of 5.1.0, thanks!

**Comment by rwjblue** [comment]
Thanks @sebmck!!

I just released [ember-computed-decorators](https://github.com/rwjblue/ember-computed-decorators) taking advantage of the recent update.

**Comment by mmun** [comment]
This is great!
