### ISSUE TITLE
Strip “proposal-” from plugin names, when the features are set in stone.

### ISSUE THREAD

**Issue by dilyanpalauzov** [babel/babel#11559]
Strip “proposal-” from plugin names, that are stage 4-TC 39-set in stone:

*   babel-plugin-proposal-async-generator-functions
*   babel-plugin-proposal-dynamic-import
*   babel-plugin-proposal-export-namespace-from
*   babel-plugin-proposal-json-strings
*   babel-plugin-proposal-nullish-coalescing-operator
*   babel-plugin-proposal-object-rest-spread
*   babel-plugin-proposal-optional-catch-binding
*   babel-plugin-proposal-optional-chaining
*   babel-plugin-proposal-unicode-property-regex

This is already mentioned at https://github.com/babel/babel/issues/10746#issuecomment-611866816.  I write it separately so that this can be included explicitly to the Babel 8 milestone.

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/babel/babel/pull/15614
