### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by RDIL** [babel/babel#11556]
## Bug Report

Hi Babel team,
I was trying to add `@babel/plugin-transform-inline-consecutive-adds` (as showcased by the docs), but yarn seems to think it doesn't exist:
```js
yarn add v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel%2fplugin-transform-inline-consecutive-adds: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/workspace/proj/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
- [ ] I would like to work on a fix!

**Current Behavior**

Package not found.

**Input Code**

n/a

**Expected behavior/code**
Package to properly resolve.

**Environment**

```
/workspace/proj $ npx envinfo --preset babel

  System:
    OS: Linux 4.14 Ubuntu 20.04 LTS (Focal Fossa)
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Monorepos:
    Lerna: 3.20.2
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    @babel/core: ^7.9.6 => 7.9.6 
    @babel/preset-env: ^7.9.6 => 7.9.6 
    babel-jest: ^26.0.1 => 26.0.1 
    eslint: ^7.0.0 => 7.0.0 
    jest: ^26.0.1 => 26.0.1 
    lerna: ^3.20.2 => 3.20.2 

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] latest v7
- Node/npm version: [e.g. Node 8/npm 5] v12 with latest yarn v1
- OS: [e.g. OSX 10.13.4, Windows 10] Ubuntu Focal
- Monorepo: [e.g. yes/no/Lerna] Lerna
- How you are using Babel: [e.g. `cli`, `register`, `loader`] cli

**Possible Solution**
No idea.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JMarkoski** [comment]
The installation command is 

> ``npm install babel-plugin-transform-inline-consecutive-adds --save-dev``

See here: [https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-inline-consecutive-adds](https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-inline-consecutive-adds)

**Comment by RDIL** [comment]
That fixed it.  Thanks!
