### ISSUE TITLE
Nested function result destructuring breaks block scope checks

### ISSUE THREAD

**Issue by sventschui** [babel/babel#11569]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

When nesting destructuring of function results something goes bad with block scope checks. The following code is ending up in a `"x" is read-only` error on the line `[x] = [2]`. When changing `const [y] = ...` to `const y = ...` everything works as expected.

(REPL: [bad](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=true&code_lz=EQVwzgpgBGAuBOBLAxrYBuAUMg9gOzigG0BPAXSgF4oAzEPVRfKAEwAoBKKAbykyii4CsYgA8K1Og1hM8UAIace_AVAA2EEaKpQAjFlW16jZsiXcVhouJ1EATGUtQAvpifxNIeHKJmOjgWdOFRUPWC8fXTsAZkcgjiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.9.6&externalPlugins=) vs. [good](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=true&code_lz=EQVwzgpgBGAuBOBLAxrYBuAUMg9gOzigE8oBeKAMxD1UXygBMAKASigG8pMopcDYoAbQAeAXTKVqtegENWHbjygAbCAOESAjFiWSasOnl7z2i3SPHlBAJlFmoAX0z34akPCODkrOzwetFRVdYd09NawBmO38WIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.9.6&externalPlugins=))

```js
"use strict";
const [y] = function d() { 
  const [x] = function a() {
    let x = 1;
    function c() {
      [x] = [2]
    }

    return [c()]
  }()
  
  return [123]
}()
```

**Expected behavior/code**
No read only error as `x` refers to the inner let, not the const.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": [
    "@babel/transform-block-scoping",
    "@babel/transform-destructuring"
  ]
}
```

**Environment**

```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    eslint: ^6.0.1 => 6.8.0 
    jest: ^24.9.0 => 24.9.0 
```

**Possible Solution**

**Additional context/Screenshots**
n/a

**Comment by nicolo-ribaudo** [comment]
@calebeby Could you check if your PR fixes this bug?

**Comment by liuxingbaoyu** [comment]
Seems to have been fixed.
