### ISSUE TITLE
Nodes with _blockHoist = 2 have higher priority than import declarations

### ISSUE THREAD

**Issue by vasiliicuhar** [babel/babel#11573]
## Bug Report

[x] I would like to work on a fix!

**Current Behavior**
If a plugin (in my case it's react-refresh/babel) inserts a variable declaration in the root scope, this declaration is printed before any import statement in this file. This breaks some parsers, that expect import declarations should be before any statements.

- [Codesandbox](https://codesandbox.io/s/floral-architecture-y6yhf?file=/src/index.js)

This happens, because by default, pushing variable declarations to scope, adds `_blockHoist = 2` property to the node:
https://github.com/babel/babel/blob/f6c7bf36cec81baaba8c37e572985bb59ca334b1/packages/babel-traverse/src/scope/index.js#L887

After that it looks like following code is executed:
https://github.com/babel/babel/blob/31b361b736ee519180f9ea341e2a3e4e710d2ef4/packages/babel-core/src/transformation/block-hoist-plugin.js#L54-L61

It says "Priority over normal nodes" in the comment, which I would think it's not the case, because imports should be at the top of the file.

**Input Code**

```js
import foo from 'foo'
```

**Expected behavior/code**

```js
import foo from 'foo';
var _test = bar();
```

**Actual behavior/code**

```js
var _test = bar();
import foo from 'foo';
```
**Environment**
```
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.2.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  npmPackages:
    @babel/core: ^7.9.6 => 7.9.6 
    @babel/plugin-syntax-import-meta: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-react-jsx: ^7.9.4 => 7.9.4 
```

**Possible Solution**
I ended up with a temporary user-space solution: a plugin that assigns _blockHoist = 3 for all import declarations:

```js
{
  name: "hoist-imports",
  visitor: {
    Program: {
       exit(path) {
           path
              .get("body")
              .filter((p) => p.isImportDeclaration())
              .forEach((p) => {
                 p.node._blockHoist = 3;
              });
        },
     },
   },
 },
```

**Comment by nicolo-ribaudo** [comment]
> This breaks some parsers, that expect import declarations should be before any statements.

This is a bug with those parsers. Also, the actual and expected code you posted have the same behavior because import statements are always executed before anything else regardless of their position in the file.

**Comment by vasiliicuhar** [comment]
I know from somewhere that imports are hoisted, and from the spec it looks like the only requirement for imports is to be on top level.
Do you know why the spec allows statements before imports?

**Comment by nicolo-ribaudo** [comment]
I think that the only reason is that the spec doesn't want to enforce any code style.

**Comment by vasiliicuhar** [comment]
Fair point.
