### ISSUE TITLE
babel-node should add '.ts', '.tsx' as a default extensions to hook into

### ISSUE THREAD

**Issue by stnor** [babel/babel#11577]
## Bug Report

**Current Behavior**

I'm running jasmine tests in babel-node in my front-end typescript project, and I got
```
SyntaxError: Cannot use import statement outside a module
```
It took me four hours to understand that *.ts files aren't included by default in babel-node. Google/SE was no help.

As Typescript is supported by babel since a while back, it seems resonable that babel-node should hook into '.ts'-files by default? Perhaps '.tsx' too.

See https://babeljs.io/docs/en/next/babel-node.html

**Input Code**
DOESN'T WORK
package.json:
```js
  "scripts": {
    "test": "npx babel-node spec/run.ts",
  },
```

DOES WORK
package.json:
```js
  "scripts": {
    "test": "npx babel-node -x '.ts' spec/run.ts",
  },
```

**Comment by dilyanpalauzov** [comment]
Do you mean what is described athttps://github.com/microsoft/TypeScript/issues/38546?

In particular that 'import ./b' in typescript means all of 'import ./b.ts', 'import b.js' or import the directory b/, whichever exists, while in ES6 syntax, one has to be explicit 'import ./b.js', 'import ./b.ts' or 'import ./b'.  Sadly, I had no luck to communicating the problem to the TypeScript team and the documentation, how alternative typescript parsers should behave, is vague.

**Comment by dilyanpalauzov** [comment]
I edited the comment above several times.

**Comment by nicolo-ribaudo** [comment]
Related - https://github.com/babel/babel/issues/8652

**Comment by stnor** [comment]
@dilyanpalauzov no. It's what @nicolo-ribaudo ref'ed..
