### ISSUE TITLE
Failed to compile with SCSS file

### ISSUE THREAD

**Issue by bluetch** [babel/babel#11589]
## Bug Report

When I install node-sass, and change my file from .css to .scss it display below error, could you help me to resolve this problem?

ERROR in ./style/template_editor/EditBar.scss
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (1:0)

=========

{
  "name": "practice",
  "version": "1.0.0",
  "description": "practice",
  "main": "index.js",
  "scripts": {
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "start:dev": "webpack-dev-server --host 10.22.224.61",
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test",
    "test:watch": "npm run test -- --watch",
    "build": "webpack -p --define process.env.NODE_ENV='\"production\"' --progress --colors",
    "production": "webpack -p --progress"
  },
  "author": "test",
  "devDependencies": {
    "@svgr/webpack": "^5.4.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "node-sass": "^4.14.1",
    "sass-loader": "^8.0.2",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "3.9.0"
  },
  "dependencies": {
    "@ant-design/icons": "^4.0.5",
    "@zalando/oauth2-client-js": "0.0.18",
    "antd": "^3.26.13",
    "axios": "^0.19.2",
    "babel-plugin-import": "^1.13.0",
    "babel-preset-stage-1": "^6.1.18",
    "browser-image-compression": "^1.0.9",
    "cors": "^2.8.5",
    "css-loader": "^3.4.2",
    "file-saver": "^2.0.2",
    "firebase": "^7.13.1",
    "image-js": "^0.21.9",
    "jszip": "^3.2.2",
    "lodash": "^3.10.1",
    "react": "16.3.2",
    "react-color": "^2.18.1",
    "react-cookie": "^4.0.3",
    "react-dom": "16.3.2",
    "react-redux": "5.0.7",
    "react-router-dom": "^5.1.2",
    "redux": "4.0.0",
    "style-loader": "^1.1.3"
  }
}

**Comment by nicolo-ribaudo** [comment]
What's your webpack config?
