### ISSUE TITLE
Do not strip imports in preset-typescript

### ISSUE THREAD

**Issue by dilyanpalauzov** [babel/babel#11601]
With this input a.ts:
```javascript
import './b.js';
import i from './i.js';

let t = '123';
```
`babel --presets '@babel/preset-typescript' a.ts` prints:
```javascript
import './b.js';
let t = '123';
```
so `import i from './i.js';` is gone, whereas `babel a.ts` keeps that `import` in the output.  This is inconsistent.

**Comment by dilyanpalauzov** [comment]
If I rename a.ts to a.js and call `babel --presets '@babel/preset-typescript' a.js`, then `import i from './i.js';` is in the output.

**Comment by nicolo-ribaudo** [comment]
This is the correct behavior: https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22#code/JYWwDg9gTgLgBAcgHQHoBGSBWBnBBuAKFEljmDgDMoIRFVgtdCCAbAU3ngF5EBGAJgDM+IA

If you want Babel to only remove imports marked as `type`, you can enable the [`onlyRemoveTypeImports`](https://babeljs.io/docs/en/babel-preset-typescript#onlyremovetypeimports) option.
