### ISSUE TITLE
No "exports" main resolved in @babel/helper-compilation-targets/package.json with Node 12.17.0

### ISSUE THREAD

**Issue by JamesSingleton** [babel/babel#11615]
## Bug Report

I know #11216 mentions a similar issue, but that is with Node 13, this is with the newly released 12.17.0.

**Current behavior**

Node just released 12.17.0 and now running `"build": "babel src -d ./",` with the following deps (also installed the latest versions as well and still had the issue)

```json
"@babel/cli": "^7.8.3",
"@babel/core": "^7.8.3",
```
results in:

```sh
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/singleton/OSS/holocron/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/singleton/OSS/holocron/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Input Code**

```json
"build": "babel src -d ./",
```

**Expected behavior**

It should build properly without error as it does on Node 12.16.3.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = function (api) {
  api.cache(true);
  return {
    babelrcRoots: ['.', './packages/*'],
  };
}
```

**Environment**

```
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Monorepos:
    Lerna: 3.20.2
  npmPackages:
    @babel/cli: ^7.8.3 => 7.8.3 
    @babel/core: ^7.8.3 => 7.8.3 
    babel-preset-amex: ^2.1.0 => 2.2.0 
    eslint: ^6.8.0 => 6.8.0 
    jest: ^25.1.0 => 25.1.0 
    lerna: ^3.20.2 => 3.20.2 
```

**Additional context**
It works fine on Node 12.16.3.

**Comment by MylesBorins** [comment]
@JamesSingleton I was unable to reproduce locally with the exact same babel config and the following dependencies

```
  "dependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6"
  }
```

Do you have an example of the code you are attempting to transpile?

**Comment by JamesSingleton** [comment]
@MylesBorins, two repos that I know of that are exhibiting this behavior right now are
* https://github.com/americanexpress/holocron
* https://github.com/americanexpress/redux-idle-callback

**Comment by MylesBorins** [comment]
Looks like the issue was an out of date version of helper-compilation-target in the package-lock. I've opened a PR that should fix this.

https://github.com/americanexpress/holocron/pull/35

Once that has confirmed to fix stuff I think this issue can be closed.

**Comment by existentialism** [comment]
@MylesBorins thanks for digging in!

**Comment by JamesSingleton** [comment]
@MylesBorins what is _weird_ is when I did `npm i -D @babel/core@latest` I still ran into issues. Did you delete the `package-lock.json` and then reinstall? I had to copy in your lockfile for it to finally work... weird

**Comment by JamesSingleton** [comment]
@MylesBorins going to close this issue, thanks for taking the time to help me out!

**Comment by MylesBorins** [comment]
FTR I had to blow away the entire lockfile and run `npm install` again to get the right dependency graph

**Comment by jseminck** [comment]
In my case, the `@babel/helper-compilation-targets` package is installed as a dependency of `@babel/preset-env`. Updating it to the latest version fixed the issue for me.

```
$ npm ls @babel/helper-compilation-targets
└─┬ @babel/preset-env@7.8.3
  └── @babel/helper-compilation-targets@7.8.3
```

**Comment by smilingkite** [comment]
For people trying to deal with this one: I had to not only delete the lock file, but also delete the whole node-modules directory (though deleting the specific package would probably have worked as well).

THEN do an 'npm install'.
