### ISSUE TITLE
Modify all our package.json's to use a different value for the repository field

### ISSUE THREAD

**Issue by hzoo** [babel/babel#11619]
So `package.json` files can have a `repository` field!

After looking at https://github.com/babel/babel-polyfills with @nicolo-ribaudo, we realized there's another format for it that we should change all the packages in this monorepo to. https://docs.npmjs.com/files/package.json#repository

![image](https://user-images.githubusercontent.com/588473/82948460-d1e73c00-9f6f-11ea-9e72-ba8b99eeaa19.png)

So for example: `babel-cli`

```json
"repository": "https://github.com/babel/babel/tree/master/packages/babel-cli",
```
we should change to:

```json
"repository": {
  "type" : "git",
  "url" : "https://github.com/babel/babel.git",
  "directory": "packages/babel-cli"
}
```

I would change all the files in eslint/codemods/packages folders!

**Comment by saulosantiago** [comment]
@hzoo Can I work on this issue?

**Comment by existentialism** [comment]
@saulosantiago it's yours!
