### ISSUE TITLE
React Component is not working with class decorators

### ISSUE THREAD

**Issue by Dignifiedquire** [babel/babel#1161]
I was very excited for the new decorator syntax and was trying to get a simple example of class decorators with react working. Unfortunately I'm running into the following issue:

Using this simple component
```js
@Enhance
export class Simple extends Component {

  render() {
    return (
      <span>I am a {this.props.enhanced ? 'enhanced' : 'simple'} component.</span>
    )
  }
}
```

and this `Enhance` decorator

```js
import React from 'react'
const { Component } = React

const Enhance = Target => class extends Component {

  render() {
    return <Target {...this.props} enhanced={true} />
  }
}
```
If I try to render this component it throws with

```
Uncaught TypeError: Cannot call a class as a function  bundle.js:58 
_classCallCheck                                        bundle.js:101
```

The generated `bundle.js` can be found [here](https://gist.github.com/Dignifiedquire/e5244904712f94f9c05c)

It seems that the check for the constructor of the `Simple` component is referencing the constructor where `Enhance` has already been applied to.

I might be just doing  something wrong, if so a pointer to what I need to fix would be great. 

Thanks for a great tool!

---

Libraries used:
```bash
➜  react  npm ls react
/Users/dignifiedquire/play/react
└── react@0.13.1

➜  react  npm ls babel-loader
/Users/dignifiedquire/play/react
└── babel-loader@5.0.0

➜  react  npm ls babel-core
/Users/dignifiedquire/play/react
├── babel-core@5.0.8
└─┬ babel-loader@5.0.0
  └── babel-core@5.0.8
```

**Comment by sebmck** [comment]
It's basically exactly as the error message says. The class is being called rather than created with `new`. This is spec behaviour.

**Comment by Dignifiedquire** [comment]
@sebmck Please consider reopening this, or at least trying to explain to me where the constructor is being called without `new`, as from my understanding it's called with `new` from react. 

According to the [spec](https://github.com/wycats/javascript-decorators#desugaring-es6), the following code 

```js
@Enhance
export class Simple extends Component {
    constructor(props) {
      super(props)
      console.log(props)
    }

  render() {
    return (
      <span>I am a {this.props.enhanced ? 'enhanced' : 'simple'} component.</span>
    )
  }
}
```
should desugar to

```js
var Simple = (function () {
  class Simple extends Component {
    constructor(props) {
      super(props)
      console.log(props)
    }

    render() {
      return (
          <span>I am a {this.props.enhanced ? 'enhanced' : 'simple'} component.</span>
      )
    }
  }
  Simple = Enhance(Simple) || Simple
  return Simple
})()
```
This manual desugared version runs without any issues, but using the babel transpiled version throws the error mentioned above. 

--- 

Looking at this [minimal example](http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&playground=true&code=var%20Foo%20%3D%20(function%20()%20%7B%0A%20%20class%20Foo%20%7B%0A%20%20%20%20test()%20%7B%7D%0A%20%20%7D%0A%0A%20%20Foo%20%3D%20F(%22color%22)(Foo%20%3D%20G(Foo)%20%7C%7C%20Foo)%20%7C%7C%20Foo%3B%0A%20%20return%20Foo%3B%0A%7D)()%3B%0A%0A%0A%40F(%22color%22)%0A%40G%0Aclass%20Bar%20%7B%0A%20%20test()%20%7B%7D%0A%7D) it's clear that there is a difference between the manual desugared version and the babel desugared version resulting in different `this` bindings.

**Comment by sebmck** [comment]
@Dignifiedquire Can you provide the entire stack trace

**Comment by Dignifiedquire** [comment]
Sure,
![screen shot 2015-04-05 at 04 54 35](https://cloud.githubusercontent.com/assets/790842/6995558/0069c88e-db50-11e4-8f83-b6ccf42f1de3.png)

Also the arguments passed to `_classCallCheck`:

```js
> instance.constructor
function Simple(props) {
	    _classCallCheck(this, Simple);

	    _get(Object.getPrototypeOf(Simple.prototype), 'constructor', this).call(this, props);
	    console.log(props);
	  }

> Constructor
function (props) {
	      _classCallCheck(this, _class);

	      _get(Object.getPrototypeOf(_class.prototype), 'constructor', this).call(this, props);
	    }
```

**Comment by sebmck** [comment]
I'll reopen until I have a chance to have a closer look. I'll likely be unavailable for a couple days but I'll try and look into it if I have a chance.

**Comment by Dignifiedquire** [comment]
Sure, I will try to find out more if I can in the meantime, so far I was able to reduce it down to this minimal example:


```js
function F(Target) {
  // Calling `new Target()` here works fine
  return () => {
    target: new Target() // This breaks things
  }
}

var Foo = (function () {
  class Foo {
    constructor() {}
  }

  Foo = F(Foo) || Foo;
  return Foo;
})();


@F
class Bar {
  constructor() {}
}

const foo = new Foo()
const bar = new Bar()  // Throws `Cannot call a class as a function`

```

The error only happens when `new Target()` is executed inside the returned value of the decorator.

**Comment by cdebotton** [comment]
I would like to add that, if the class being rendered exists in the same file as the decorator, there are no error thrown, eg:

```js
"use strict";

import React from "react";

export default function subscription(...stores) {
  let getStateFromStores = stores.pop();
  return function decorator(Target) {
    return class SubscriptionComponent extends React.Component {
      constructor(props) {
        super(props);

        this.state = getStateFromStores(props);
      }

      render() {
        return (
          <TestClass />
        );
      }
    }
  }
}

class TestClass extends React.Component {
  render() {
    return (
      <div>This is a mock class.</div>
    );
  }
}
```

However, ifI used the `Target` argument that is naturally passed in through the error stating that a class cannot be called as a function.

`
  TypeError: Cannot call a class as a function
      at _classCallCheck (/Users/cdebotton/www/cdb/app/components/App/index.js:5:106)
      at new App (/Users/cdebotton/www/cdb/app/components/App/index.js:14:22)
      at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactCompositeComponent.js:135:16)
      at [object Object].wrapper [as mountComponent] (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactPerf.js:70:21)
      at Object.ReactReconciler.mountComponent (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactReconciler.js:38:35)
      at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactCompositeComponent.js:237:34)
      at [object Object].wrapper [as mountComponent] (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactPerf.js:70:21)
      at Object.ReactReconciler.mountComponent (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactReconciler.js:38:35)
      at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactCompositeComponent.js:237:34)
      at [object Object].wrapper [as mountComponent] (/Users/cdebotton/www/cdb/node_modules/react/lib/ReactPerf.js:70:21)
`

Been trying to figure this out for a few days, any help would be greatly appreciated!

**Comment by andreypopp** [comment]
Yeah... the problem is that class call check perform a check in the constructor against decorated constructor function — it picks up by the name from the scope where it's being redefined:
```
var App = (function (_React$Component) {
  function App() {
    _classCallCheck(this, App);

    if (_React$Component != null) {
      _React$Component.apply(this, arguments);
    }
  }

  ...

  App = _Async.Async(App) || App; // !!!
  return App;
})(_React2['default'].Component);
```

**Comment by Dignifiedquire** [comment]
Yes, as @andreypopp said the constructor that is being referenced is wrong:

```js
// Generated Code
function F(Target) {
  return function () {
    target: new Target();
  };
}
var Bar = (function () {
  function Bar() {
    _classCallCheck(this, Bar); // Bar refrences actually F(Bar) instead of the original Bar when executed
  }

  Bar = F(Bar) || Bar;
  return Bar;
})();
```

@sebmck the simplest solution to fix I see is to instead generate this code:

```js
var Bar = (function () {
  var Bar = function Bar() {
    _classCallCheck(this, Bar);
  }

  Bar = F(Bar) || Bar;
  return Bar;
})();
```

which is what babel already generates when transforming the manual es6 desugared case:

```js
var Bar = (function () {
  class Bar {}

  Bar = F(Bar) || Bar;
  return Bar;
})();
```

**Comment by eventualbuddha** [comment]
@Dignifiedquire I don't believe the proposed generated code is correct, either. The `Bar` reference inside the `function Bar() {` expression will still refer to the pre-enhanced version due to the binding the named function expression creates inside itself. Really you'd need something like this:

```js
var Bar = (function () {
  var _Bar = function Bar() {
    _classCallCheck(this, _Bar);
  };

  _Bar = F(_Bar) || _Bar;
  return _Bar;
})();

**Comment by Dignifiedquire** [comment]
> expression will still refer to the pre-enhanced version

@eventualbuddha but the issue is that we are referencing the enhanced version, we want to reference the pre-enhanced version, as `this` referes to an instance of the pre-enhanced version inside the constructor.
