### ISSUE TITLE
babel stand alone version 7.10.0 doesnt work

### ISSUE THREAD

**Issue by yigalirani** [babel/babel#11628]
7.10 doent seems do do anything at all. null behavoir. I had to revert to 7.9

**Comment by hamlim** [comment]
We're also running into an error when using `7.10.0` with `@babel/standalone` while using the stage-0 preset:

```
Error: [BABEL] unknown: The 'moduleAttributes' plugin requires a 'version' option, representing the last proposal update. Currently, the only supported value is 'apr-2020'. (While processing: "base$1$0$0")
    at babel.min.js:1
    at babel.min.js:1
    at babel.min.js:1
    at l (babel.min.js:1)
    at Generator._invoke (babel.min.js:1)
    at Generator.forEach.e.<computed> [as next] (babel.min.js:1)
    at l (babel.min.js:1)
    at b (babel.min.js:1)
    at Generator._invoke (babel.min.js:1)
    at Generator.forEach.e.<computed> [as next] (babel.min.js:1)
```

It seems like the stage-1 preset defaults the `version` to `may-2020` and that option doesn't seem to be overridable from the `stage-0` preset: https://github.com/babel/babel/blob/master/packages/babel-standalone/src/preset-stage-1.js#L13

Should all options for stage-0 be spread down so users can also configure stage-1, stage-2, etc?

**Comment by hamlim** [comment]
I just noticed the linked pull request won't resolve the error we're running into above, would it be better to open up a new issue to track this?

**Comment by nicolo-ribaudo** [comment]
@hamlim Could you open a PR adding that option to the stage 0 preset? We can merge it for the next patch.

**Comment by hamlim** [comment]
Sure!

**Comment by hamlim** [comment]
@nicolo-ribaudo I tried using `make build-dist` to build locally and test but it doesn't seem to create the single file entry for the standalone package, do you know how I can test this locally?

**Comment by hamlim** [comment]
I think this issue should still be open as there is another issue with the 7.10 release of babel-standalone unrelated to the PR that was merged above cc @existentialism
