### ISSUE TITLE
Lerna's npmClientArgs is sitting in an incorrect place

### ISSUE THREAD

**Issue by wataruoguchi** [babel/babel#11620]
## Bug Report

Hi Babel team!

This is super minor.

I was just reading your lerna settings and saw `npmClientArgs` in https://github.com/babel/babel/blob/master/lerna.json#L39 .

According to [Lerna's document](https://github.com/lerna/lerna/blob/master/README.md#lernajson), `npmClientArgs` would only be placed in `command.bootstrap.npmClientArgs`, however, you don't have `command.bootstrap` so maybe your `npmClientArgs` would not work.

I really appreciate your hard work. Babel is an amazing project. Thank you so much!

**Comment by wataruoguchi** [comment]
Sorry, please disregard this

**Comment by nicolo-ribaudo** [comment]
Don't worry! I appreciate that someone is taking a look at out files looking for problems!
