### ISSUE TITLE
In-browser JSX translation broken with 7.9 -> 7.10 upgrade.

### ISSUE THREAD

**Issue by daniel-s** [babel/babel#11621]
## Bug Report

**Current behavior**

In browser JSX translation does not work for Babel 7.10.0.

A script tag in HTML like the following works fine.
<script src="normal_script.js"></script>

A tag like this does not work:
<script src="react_script.jsr" type="text/babel"></script>

By *does not work* I mean that no Javascript in that file will execute. Not even simple JS that does not require any translation. For example, if react_script.jsr contained only this line:

`console.log("hi` world");

it would fail to execute.

This issue is remedied back to normal if following change is made to the HTML.

<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

changed to

<script src="https://unpkg.com/@babel/standalone@7.9.0/babel.min.js"></script>

**Expected behavior**

The above not to break as described.

**Environment**

```
- Babel version(s): v7.10.0
- OS: Windows 10 and Linux 4.19
- Browser: Chrome and Firefox

**Possible Solution**
Temp workaround: use v7.9.0 of babel.

**Comment by epihel** [comment]
This might be related to this CI failure: https://github.com/babel/babel/runs/710737539. It looks like other babel modules for version **7.10.0** successfuly published, but if _any_ version of `@babel/plugin-proposal-class-properties` is included in `package.json`, then `npm install` fails.

**Comment by hzoo** [comment]
Must be related to https://github.com/babel/babel/pull/11466, if you look at the history of standalone. https://github.com/babel/babel/commits/master/packages/babel-standalone

**Comment by hzoo** [comment]
Ok looks like `type: script.getAttribute("data-type"),` should be `type: script.getAttribute("data-type") || "",` or the if check should be changed to include null in https://github.com/babel/babel/pull/11466/files#diff-7a71ff75920619cbc0e67883df263ca8L53.

I guess in this case, the workaround for 7.10 standalone would be to define a `data-type` in your script tag.

**Comment by arku** [comment]
@hzoo I would like to fix this issue.

**Comment by dfabulich** [comment]
The fix is ready! Sorry everybody!

**Comment by arku** [comment]
@dfabulich Ah, you beat me to it.

Let me close my PR. Thanks for the quick fix!

**Comment by thecodejack** [comment]
Hey guys...our builds are breaking. Any ETA on release?

**Comment by nicolo-ribaudo** [comment]
Later today

**Comment by nicolo-ribaudo** [comment]
Later today
