### ISSUE TITLE
Transformer plugins cannot be extracted as separate modules

### ISSUE THREAD

**Issue by shuhei** [babel/babel#1162]
Here I mean the new plugin feature that were introduced in 5.0.0.

https://github.com/babel/babel/blob/v5.0.8/src/babel/transformation/transformer.js#L73-L75 expects transformer plugins to use the same `babel-core` as the one that consumes them. However, the expectation is hardly met.

When I tried to use my custom transformer in a project with `babel-loader`, I got the following error:

```
ERROR in ./src/app.es6
Module build failed: TypeError: Transformer angular2-at-annotation is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-core/lib/babel/transformation/transformer.js:97:13)
    at File.addPlugin (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:287:48)
    at File.buildTransformers (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:215:12)
    at new File (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:89:10)
    at Object.transform (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/index.js:43:24)
```

The transformer's code is like the following:

```js
var babel = require('babel-core');
var t = babel.types;
var Transformer = babel.Transformer;

module.exports = new Transformer('angular2-at-annotation', {
  // ...
});
```

To make it work, I had to `require('babel-loader/node_modules/babel-core')`. But this workaround prevents me from extracting the transformer as a separate npm module.

If modules like `babel-loader` and `babelify` only use `babel-core` as `peerDependencies`, transformer modules can use `peerDependencies` too. But it seems like [`peerDependencies` is going to be deprecated](https://github.com/npm/npm/issues/5080).

I would be happy if the `instanceof File` check is omitted or if you allow us to write transformers without `Transformer` constructor:

```js
var babel = require('babel-core');
var t = babel.types;

module.exports = {
  key: 'angular2-at-annotation',
  transformer: {
    // ...
  }
});
```

**Comment by sebmck** [comment]
Add babel-core with a range of ^5.0.0 and reinstall your node_modules by
deleting the folder and running npm install again.

On Sunday, 5 April 2015, Shuhei Kagawa <notifications@github.com> wrote:

> Here I mean the new plugin feature that were introduced in 5.0.0.
>
>
> https://github.com/babel/babel/blob/v5.0.8/src/babel/transformation/transformer.js#L73-L75
> expects transformer plugins to use the same babel-core as the one that
> consumes them. However, the expectation is hardly met.
>
> When I tried to use my custom transformer in a project with babel-loader,
> I got the following error:
>
> ERROR in ./src/app.es6
> Module build failed: TypeError: Transformer angular2-at-annotation is resolving to a different Babel version to what is doing the actual transformation...
>     at Transformer.buildPass (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-core/lib/babel/transformation/transformer.js:97:13)
>     at File.addPlugin (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:287:48)
>     at File.buildTransformers (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:215:12)
>     at new File (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/file/index.js:89:10)
>     at Object.transform (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
>     at transpile (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/index.js:54:24)
>     at Object.module.exports (/Users/shuhei/work/js/babel-angular2-app/node_modules/babel-loader/index.js:43:24)
>
> The transformer's code is like the following:
>
> var babel = require('babel-core');var t = babel.types;var Transformer = babel.Transformer;
> module.exports = new Transformer('angular2-at-annotation', {
>   // ...
> });
>
> To make it work, I had to require('babel-loader/node_modules/babel-core').
> But this workaround prevents me from extracting the transformer as a
> separate npm module.
>
> If modules like babel-loader and babelify only use babel-core as
> peerDependencies, transformer modules can use peerDependencies too. But
> it seems like peerDependencies is going to be deprecated
> <https://github.com/npm/npm/issues/5080>.
>
> I would be happy if the instanceof File check is omitted or if you allow
> us to write transformers without Transformer constructor:
>
> var babel = require('babel-core');var t = babel.types;
> module.exports = {
>   key: 'angular2-at-annotation',
>   transformer: {
>     // ...
>   }
> });
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1162>.
>


-- 
Sebastian McKenzie

**Comment by shuhei** [comment]
Thanks, It worked!

**Comment by shuhei** [comment]
I'll try to extract the transformers as separate modules and see how if it works.

**Comment by shuhei** [comment]
I could successfully extract transformer plugins as npm modules. They use `peerDependencies` for now though. Let's wait for npm@3 to officially deprecate `peerDependencies`.

- https://github.com/shuhei/babel-plugin-angular2-at-annotation
- https://github.com/shuhei/babel-plugin-angular2-type-annotation

Thanks!
