### ISSUE TITLE
@babel/plugin-proposal-class-properties Can't Be Installed after 7.10.0 Upgrade

### ISSUE THREAD

**Issue by epihel** [babel/babel#11632]
Since yesterday (26 May 2020), when many babel modules were upgraded to **7.10.0**, trying to install _any_ version of @babel/plugin-proposal-class-properties via `npm install` (latest is **7.8.3**) fails with messages such as:

`No matching version found for @babel/helper-member-expression-to-functions@^7.10.0`

This configuration in `package.json` works, as long as I don't include `@babel/plugin-proposal-class-properties`:
```
"@babel/core": "7.9.6",
"@babel/plugin-proposal-object-rest-spread": "7.9.6",
"@babel/preset-env": "7.9.6",
"@babel/preset-react": "7.9.4",
"@babel/register": "7.9.0",
"babel-eslint": "10.1.0",
"babel-loader": "8.1.0",
"babel-plugin-module-resolver": "4.0.0"
```

**Comment by nicolo-ribaudo** [comment]
Please see https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67 (GitHub should have shown you this link when clicking on "new issue").

npm link of that package: https://www.npmjs.com/package/@babel/helper-member-expression-to-functions

**Comment by epihel** [comment]
@nicolo-ribaudo Yes; you're right. The problem was with my company's Nexus cache. Once we cleared the cache, everything installed.
