### ISSUE TITLE
Babel should transform class private properties mixed with logical assignment operators

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11646]
## Bug Report

This is a good first issue for first-time Babel contributors.

**Current behavior**
A clear and concise description of the behavior.

- [Codesandbox](https://codesandbox.io/s/admiring-shape-r8657)

throws
```
unknown: Property operator expected value to be one of ["+","-","/","%","*","**","&","|",">>",">>>","<<","^","==","===","!=","!==","in","instanceof",">","<",">=","<="] but got "??"
```

**Input Code**

```js
class C {
  #x;
  m() { this.#x ??= 42 }
};
```

**Expected behavior**
It should be transpiled successfully

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": "Edge 16",
      "shippedProposals": true
    }]
  ],
  "plugins": ["@babel/plugin-proposal-logical-assignment-operators"]
}
```

**Environment**
CodeSandbox

**Possible Solution**

When transforming private class properties, babel will call `packages/babel-helper-member-expression-to-functions/src/index.js` which transforms private property usage to helper calls. For example,
```js
this.#x += 42
```
is approximately transformed to
```
_privateSet(this, x, _privateGet(this, x) + 42)
```

As you can see `_privateGet(this, x) + 42` is a binary expression. But `??` is not a valid binary expression, so the error is thrown. To fix it, we should construct logical expression for logical assignment operators, namely `??=`, `||=` and `&&=`.

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated) to `packages/babel-plugin-proposal-class-properties/test/fixtures/private/logical-assignment` (tip: you can copy from contents of `fixtures/private/assignment`)
1. Update the code!
1. `yarn jest class-properties` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by jridgewell** [comment]
Specifically, this needs to be handled in https://github.com/babel/babel/blob/5b24d798758a9ad1f5aa383d1e83869ae7964ab1/packages/babel-helper-member-expression-to-functions/src/index.js#L287-L313

**Comment by ryzokuken** [comment]
Can I give this a shot? :smile:

**Comment by existentialism** [comment]
@ryzokuken it's yours!

**Comment by eiji03aero** [comment]
@ryzokuken 
Hi, I was wondering if you are still working on this?

**Comment by ryzokuken** [comment]
Hi @eiji03aero. It's a rather busy week, but I do infact intent to work on the PR.

**Comment by eiji03aero** [comment]
@ryzokuken 
aye aye noted

**Comment by sag1v** [comment]
Is this in WIP?

**Comment by ryzokuken** [comment]
@sag1v yep, check out the linked PR for the full conversation and current status. I'm planning to make the final requested changes this week :crossed_fingers:

**Comment by sag1v** [comment]
> @sag1v yep, check out the linked PR for the full conversation and current status. I'm planning to make the final requested changes this week :crossed_fingers: 

Thank you 💚
