### ISSUE TITLE
Function with destructuring assignment breaks react dev build

### ISSUE THREAD

**Issue by untitledlt** [babel/babel#11656]
## Bug Report
Tested on clean `create-react-app` install.
This function in any component file breaks React app:

```javascript
const myFn = ({ set = '' }) => {};
```

**Current behavior**
```
./src/App.js 7:6
Module parse failed: Unexpected token (7:6)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/eslint-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| 
| const myFn = ({
>   set = ''
| }) => {};
|
```

if I change `set` to anything else, everything works fine.

**Input Code**

```js
const myFn = ({ set = '' }) => {};
```

**Expected behavior**
Should transpile without errors.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Clean, not ejected `create-react-app`.

**Environment**
```
- Babel version(s): [7.9.0]
- Node/npm version: [12.14.0]
- OS: [macOS 10.15.4]
- Monorepo: [no]
- How you are using Babel: [`loader`]
```
**Possible Solution**
Do not use `set` as object property

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by JLHwung** [comment]
The error is not thrown from babel but from acorn, which is used by Webpack to parser `src/App.js`.

I can confirm on astexplorer.net that Acorn 7.1.1 fails on the following snippet

```js
({ set = '' }) => {};
({ get = '' }) => {};
```
Please file an issue to https://github.com/acornjs/acorn.
