### ISSUE TITLE
Add option to embed entire @babel/runtime

### ISSUE THREAD

**Issue by marco-a** [babel/babel#11663]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**
This is a feature requested based on [this](https://github.com/babel/babel/discussions/11611#discussioncomment-19405) issue. 
I would like babel to have an option to embed the entire `@babel/runtime` in the transpiled code so no external dependencies are needed to run the code.
It is possible to embed _some_ of the runtime by setting the flag `helpers` to `false`.
However, no option exist to embed the entire runtime.

**Describe the solution you'd like**
That `@babel/plugin-transform-runtime` accepts a new option called `embed`.
When set to `true`, babel will automatically embed all external dependencies in the transpiled code:

`{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "embed": true
      }
    ]
  ]
}`

**Describe alternatives you've considered**.
It is possible to embed the dependencies yourself by using a bundler like `webpack`.
However this adds unnecessary complexity for a simple project.

**Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and how it might be documented. Maybe a mock-up?

---

### `embed`
`boolean`, defaults to `false`.

Tells babel whether or not to embed all runtime dependencies.
If set to `true` babel will create output code that does not depend on any external dependencies.

**Comment by nicolo-ribaudo** [comment]
This is specifically for `regenerator-runtime`, everything else can be embedded just be removing the plugin. I think this should be moved to https://github.com/facebook/regenerator

**Comment by marco-a** [comment]
Why should this be moved to `regenerator-runtime`? 

I'm not familiar with the babel code base but it seems that this could be accomplished within the plugin pretty easily?

If I'm correct then this code is responsible for injecting the `runtime-generator` dependency:

```
if (name === "regeneratorRuntime" && useRuntimeRegenerator) {
	path.replaceWith(
		this.addDefaultImport(
			`${modulePath}/regenerator`,
			"regeneratorRuntime",
		),
	);
	return;
}
```
