### ISSUE TITLE
Cannot import module with babel ^7.10

### ISSUE THREAD

**Issue by Enase** [babel/babel#11661]
## Bug Report

Cannot import `aws-amplify` npm after update to babel 7.10.

All the details and how to reproduce you can find [here](https://github.com/Enase/babel-issue)

**Steps to reproduce:**

1. Run `git clone https://github.com/Enase/babel-issue.git`
2. Run `npm i` in project root
3. Run `npm run start` in project root
4. Open `http://localhost:3000` in browser

**Expected result:**

`Hello` message in a browser with no errors in console.

**Actual result result:**

Error in a browser:
```
Uncaught TypeError: Cannot read property 'register' of undefined
    at new APIClass (API.js?0f51:80)
    at eval (API.js?0f51:205)
    at Object../node_modules/@aws-amplify/api/lib/API.js (vendors~main.chunk.js:2003)
    at __webpack_require__ (main.js:849)
    at fn (main.js:151)
    at eval (index.js?636d:15)
    at Object../node_modules/@aws-amplify/api/lib/index.js (vendors~main.chunk.js:2015)
    at __webpack_require__ (main.js:849)
    at fn (main.js:151)
    at eval (index.js?b994:42)
```

```
- Babel version(s):7.10.2
- Node/npm version: `"node": ">= 12.13.0" "npm": ">= 6.13.4"`
- OS: any
- Monorepo: does not matter
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
This is an Amplify bug:
- [This file](https://github.com/aws-amplify/amplify-js/blob/1123cef546e906ba1beecedecdc60b3844f38297/packages/api/src/API.ts#L19) imports `{ Amplify }` from `@aws-amplify/core`
- That package [doesn't specify](https://github.com/aws-amplify/amplify-js/blob/1123cef546e906ba1beecedecdc60b3844f38297/packages/api/package.json#L40) the version of `@aws-amplify/core` it depends on, so it uses whatever is available
- In your case it's using version 2.3.0, which [doesn't export](https://unpkg.com/browse/@aws-amplify/core@2.3.0/src/index.ts) `Amplify` as a named export.

**Comment by Enase** [comment]
Thanks a lot!
