### ISSUE TITLE
Transform React Constant Elements incorrectly orders variable declaration in respect to reference

### ISSUE THREAD

**Issue by noahnu** [babel/babel#11686]
## Bug Report

**Current behavior**

- [REPL](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=GYVwdgxgLglg9mABHEUCmAnAFAQwwcwEpEBvAKEUQgQGcpEA3HAGxDQCFEBeRMEZ5gG4KVWvSas0AQW6kAvsJGhIsBIhhgwmLMXKV9osDTjM0AOmZx8WEQYMAeGQGs0ATylcSEtlLkA-Wzsg-04XV3ZPbw5_QKC4xHsAYUQwxM88fDlEAHoA-ODs9jz8-2ypPwAaWMRCETkyEQ0tbEJheqA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.10.2&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.10.1)

`valueA` is defined and set after it is passed into React.createElement, causing it to be undefined in the createElement function.

**Input Code**

```jsx
function outer(arg) {
  const valueB = null;
  const valueA = {};

  function inner() {
      console.log(
          <A keyA={valueA}>
              <B keyB={valueB}>
                  <C keyC={arg} />
              </B>
          </A>,
      )
  }

  inner();
}
```

**Output Code according to REPL**

```js
"use strict";

function outer(arg) {
  var valueB = null,
      _ref = /*#__PURE__*/React.createElement(A, {
    keyA: valueA
  }, /*#__PURE__*/React.createElement(B, {
    keyB: valueB
  }, /*#__PURE__*/React.createElement(C, {
    keyC: arg
  })));

  var valueA = {};

  function inner() {
    console.log(_ref);
  }

  inner();
}
```

**Expected behavior**

The `valueA` variable declaration should occur before it is passed into React.createElement. I.e. `var valueA = {}` should be moved above its use in `createElement(A`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Reproducible in the REPL and by copying and pasting the input code into the test fixtures in the plugin's directory within the monorepo. React + Spec + Bug Fixes + Shipped Proposals.

**Environment**

- Babel version(s): v7.10.2

**Additional context**

- If you remove the outer function param, the output is correctly ordered.
- Related to the 'dont-host-before-declaration' test?

**Comment by noahnu** [comment]
It looks like the bug is in babel-traverse, specifically this block of code: https://github.com/noahnu/babel/blob/3498195ae25475a376edf7149bff0e8b69eee002/packages%2Fbabel-traverse%2Fsrc%2Fpath%2Flib%2Fhoister.js#L129

I don't have enough understanding of the babel AST to understand where the bug is in the logic.

**Comment by mwiencek** [comment]
I ran into what appears to be this issue earlier today, and it was quite frustrating to debug!

Please see https://github.com/mwiencek/babel-issue-11686 for another minimal reproduction.
