### ISSUE TITLE
Add React.createContext to @babel/plugin-transform-react-pure-annotations

### ISSUE THREAD

**Issue by jessethomson** [babel/babel#11684]
## Feature Request

- [x] I would like to work on this feature!
(I don't actually care who works on this, but I'm happy to do it. Whatever is easier.)

**Is your feature request related to a problem?**

I have a React component library. When consuming applications use the library, a bunch of React.createContext calls are added to the bundle for components that aren't even being used. This shouldn't be the case as `createContext` simply takes in some parameters and returns an object.

**Describe the solution you'd like**

Super pumped about the new `@babel/plugin-transform-react-pure-annotations` package. I would like to add React.createContext to this PURE_CALLS map.

https://github.com/babel/babel/blob/71d3527ef580d63a2764a2a96b0072b23195df4f/packages/babel-plugin-transform-react-pure-annotations/src/index.js#L10-L23

**Describe alternatives you've considered**.

Nothing. I'm open to them, but this seems straightforward enough.

**Documentation, Adoption, Migration Strategy**

Adoption and Migration are simple a npm update. Not sure is this is something that is documented or not. I'm guessing not.

**Comment by jessethomson** [comment]
Created a PR for this: https://github.com/babel/babel/pull/11685

**Comment by mischnic** [comment]
Can be closed now

**Comment by jessethomson** [comment]
The `@babel/preset-react` still has the old version of this plugin. Will that eventually get updated to use the latest version that includes this change? Or should I create an issue or something for that?

**Comment by nicolo-ribaudo** [comment]
`@babel/preset-react` uses `^` to specify the version of the plugin, so it can already download the latest one.

**Comment by jessethomson** [comment]
Oh, I totally missed that. Awesome!
