### ISSUE TITLE
Transforming spread of Array(number) makes code not iterable

### ISSUE THREAD

**Issue by gndelia** [babel/babel#11683]
## Bug Report

**Current behavior**
The following code

```js
[...Array(2)].map((_, index) => index);
```

gets transpiled into 

```js
[].concat(Array(2)).map(function (_, index) {
  return index;
});
```

However, when running in a console, the first snippet returns an array with numeric values as expected `[0, 1]`

![image](https://user-images.githubusercontent.com/352474/83905659-70c22400-a738-11ea-80dd-c4224722ec5b.png)

but the second returns an array of `empty` which is not iterable, even though it has a length

![image](https://user-images.githubusercontent.com/352474/83905709-83d4f400-a738-11ea-9573-ad0d9534ec37.png)

for instance, if a `console.log` was inside the `map` function, in the original code it would get executed, but in the transpiled code, it won't

- [REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=true&code_lz=NoOjEECdIQwTwBQCYCUBdEBbGAHBCB9AGgAIBLAOwBMBTADxRIF4A-c6-lAbiA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env%2Creact%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=)

**Input Code**

```js
[...Array(2)].map((_, index) => index);
```

**Expected behavior**
The result of executing that code after transpilation should be `[0, 1]`.

- Filename: `babel.config.js`

I don't have the exact `babel` configuration as I am using this from a package that uses babel on it. But I tracked down by reviewing the generated code, and then playing in the Babel.repl by just adding `preset-env`, and checking the `loose` and `force all transformations` options

**Environment**
  System:
    OS: Windows 10 10.0.18362
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Monorepos:
    Yarn Workspaces: 1.21.1
    Lerna: 3.20.2
  npmPackages:
    babel-eslint: 10.x => 10.0.3
    eslint: 6.8.0 => 6.8.0
    lerna: ^3.20.2 => 3.20.2

**Possible Solution**
My current workaround is to change the code from

```ts
[...Array(2)].map((_, index) => index);
```

to

```ts
Array.from(Array(fixCols).keys()).map((_, index) => index);
```

That [gets transpiled](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=true&code_lz=IIJxEME8DoDMQPYFsAUoKRQJgJTQNYCmkAzijnkuAA4ooD6ANAAQCWAdgCaEAeOzAXgB8bLrxwBuIA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env%2Creact%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=) into

```ts
Array.from(Array(2).keys()).map(function (_, index) {
  return index;
});
```

which works well in the console

![image](https://user-images.githubusercontent.com/352474/83906153-6eac9500-a739-11ea-8b55-a2f4675e5dee.png)

**Additional context**
We were using this to dynamically iterate an array of elements and render some components. We tried this on storybook and it worked, but once transpiling this into a library, it did not work - we would always get `null` no matter what the number in `Array(number)` was.

I think storybook was not using babel, as the compilation to release was, so then I track that down into this piece of code that was causing the issue.

**Comment by oliverdunk** [comment]
Easily able to reproduce this by opening the REPL.

I'm not sure if it's fair to say that `Array(2)` produces an array of empty which isn't iterable? I think it would be more correct to say that it's iterable, but no values are produced when iterating over it?

[The docs](https://babeljs.io/docs/en/babel-plugin-transform-spread) for loose mode currently say this:

> In loose mode, all iterables are assumed to be arrays.

We are working on an array, so based on those docs, it feels like this should work. I can't think of an alternative to applying all of the helpers that we currently reserve for non-loose mode, though. Maybe a better option is to update the docs to something like:

> In loose mode, all iterables are assumed to be arrays. Empty values will be ignored.

By the way, I thought this would be a fun one to triage, but I'm not on the Babel team! It's totally possible that they'll come along and disagree with everything I've said 😆

**Comment by nicolo-ribaudo** [comment]
I'd just update the docs. Using array with holes is not that common, so I'd be ok with asking not to enable loose mode if you need holes to work.

**Comment by oliverdunk** [comment]
I've opened a PR to update the docs: https://github.com/babel/website/pull/2270
