### ISSUE TITLE
Comparison to multiple values syntactic sugar

### ISSUE THREAD

**Issue by jackHedaya** [babel/babel#11699]
## Feature Request

Comparison to multiple values syntactic sugar.

- [x] I would like to work on this feature! (Very limited experience working with babel though)

**Describe alternatives you've considered**.

this is already possible in js using `(variable === val1 || variable === val2 ...)`

**Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and how it might be documented. Maybe a mock-up?

Instead of  `(variable === val1 || variable === val2 ...)`, `variable === |val1, val2|`.

**Comment by JLHwung** [comment]
Hi @jackHedaya,

Thanks for the post. It seems to me that you are discussing a potential ECMAScript language feature. The Babel team currently considers ECMAScript proposals only, so it is out of our project scope. Can you post at https://es.discourse.group/? There are more language folks out there.

**Comment by jackHedaya** [comment]
@JLHwung Got it, thanks!
