### ISSUE TITLE
Incorrect switch break logic

### ISSUE THREAD

**Issue by pingyen** [babel/babel#11690]
## Bug Report

Switch break does not work.

Babel **ES2015 Preset** puts "break" in another "switch", so the original "switch" is not "break", and the logic is wrong.

The issue can reproduce on [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQMwrgdgxgLglgewsOMCmBbAzgGgARwCUeA3gFB55RJYx4A2aEeAvAetgHSMQDmMACwDcZCnhAIATnmBCCeADwMmcgNSqipMZWoRa7TKwPYA2nAC6I7XiwB3VFAEzUmEwAZzxcpR9UAhlhoeACMAFxavr66-oG6ACZGLhgmwZaikT5wIM4cKeasLGyQcWggcBBocV7WGZJoMGCSECIZlAC-6a2BMAAqcBhoCGAwoJCwiMjVrT5-jJIjsUhVLa1t-MGEVtMARnV-ANYrvh0ZUAFBAEzh3q2zaPPAF5s1PrtoB0c-J5ElIH5g9BgoRelDeH2s3w6bUIwBMeXwJgu5nM62eQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.10.2&externalPlugins=).

In the following code, case 1 does not break.

**Input Code**

```js
(function(items, i) {
  const len = items.length;

  for (; i < len; ++i) {
    const item = items[i];

    switch (item[0]) {
      case 1: {
        const second = item[1];

        if (item[1] === undefined) {
          return;
        }

        setTimeout(function() {
          alert(second);
        }, 1);

        break;
      }
      case 2: {
        alert(2);
        break;
      }
      default:
        break;
    }
  }
})([[1], [2]], 1);
```

**Output Code**

```js
"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

(function (items, i) {
  var len = items.length;

  for (; i < len; ++i) {
    var item = items[i];

    switch (item[0]) {
      case 1:
        {
          var _ret = function () {
            var second = item[1];

            if (item[1] === undefined) {
              return {
                v: void 0
              };
            }

            setTimeout(function () {
              alert(second);
            }, 1);
            return "break";
          }();

          switch (_ret) {
            case "break":
              break;

            default:
              if (_typeof(_ret) === "object") return _ret.v;
          }
        }

      case 2:
        {
          alert(2);
          break;
        }

      default:
        break;
    }
  }
})([[1], [2]], 1);
```

**Environment**

- Babel version(s): v7.10.2

**Comment by Georift** [comment]
I had a look at the reproduction provided in the repl and while the code provided above doesn't error for me I created a smaller snippet which does cause an error:

```javascript
(function() {
  for(let i = 0; i < 1; i++) {
    switch (1) {
      case 1: {
        const scopedVariable = "something we will use inside setTimeout";

        if (false) { return; }

        setTimeout(function() {
          console.log('scopedVariables:', scopedVariable);
        }, 1);
        
        break;
      }
        
      default:
      	throw new Error("Should not be reached") 
    }
  }
})();
```

When I try to evaluate the [REPL output](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQMwrgdgxgLglgewsAlAAgN4Cg1pAgJ2ABsBTGNONAXjQAYBuStAHjQEYm4Bqb9bXLgDOAdzgwoACzTB2_HINxQAhkNIcAXJgWKlSIRSFQEAB1IATAGrKCcZQCMyNNACIhCALblJcCAHM0EXUxYmI0MDVKCCE4c3U1GAAVOC8EMBgXBiwdXTgQGRBlYjV-NAJyMAIIJgBfbN1BBOTU9NBIWERkeQbFY2iEMgA6YgQ_YAByI1MLa1sHMiENcYAaNCmzKxs7R1IULJ60GtW5LJzFM8F7cuUAa33dOoOLuMKwYhgNC4BIGEkCBBEaAgpEBAFECP8iC4AMqSNLEcxAhAUezqa5SCwudA5R6HLA1FCoLJAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=true&targets=&version=7.10.2&externalPlugins=), the error in the default case is thrown. While the original input data runs without hitting the error.

This is my first attempt at contributing to babel so any tips would be great, I'm going dig into this some more tomorrow 🤞
