### ISSUE TITLE
config file standardisation

### ISSUE THREAD

**Issue by timreichen** [babel/babel#11705]
## Feature Request

- [x] I would like to work on this feature!

**Short context**
I was working with lots of different tools and plugins and observed that a lot of them have different config file specifications, staring with the naming conventions. I could not find anything about this topic and so I wrote a short article [here](https://gist.github.com/timreichen/87a894c94a4c2258b15962d1754e34a8) to describe the current problem and a possible solution.
I am writing to different authors of popular tools like babel and typescript to get their opinions, some insight and hopefully creating a discussion and maybe an overarching standard for the near future. What do you think about this?

**Describe the solution you'd like**

Having a naming standard for config files similar or as described in  [this article](https://gist.github.com/timreichen/87a894c94a4c2258b15962d1754e34a8).

**Comment by nicolo-ribaudo** [comment]
Hey, thanks for the suggestion.

We prefer to keep our current config system, since that proposed standard doesn't allow differentiating between our `.babelrc.json` and `babel.config.json` config types.
