### ISSUE TITLE
Transpiling (non-conflicting) namespace reexports emits invalid code

### ISSUE THREAD

**Issue by mischnic** [babel/babel#11710]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

```
TypeError: Cannot redefine property: c
```

Namespace reexports are transpiled like this:
```js
for(key ...){
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function () {
      return imported[key];
    }
  });
}
```

But the spec allows for reexporting a symbol twice in the same file if it is actually the same binding (see example code below).

This means that `Object.defineProperty(exports, "c", ...)` is called twice, causing the error.

One of the packages that do this is `@fluentui/react` (this came up in https://github.com/parcel-bundler/parcel/issues/4399)

**Input Code**

- https://github.com/mischnic/parcel-issue-4399 (`lib/` already contains the Babel output of `src-valid`)

```js
export * from "./a.js";
export * from "./b.js";

// ---- everything below is just for context ---

// a.js
export { c } from './c.js'; // <-- 
export const a = "a";
// b.js
export { c } from './c.js'; // <-- 
export const b = "b";

// c.js
export function c() {
	return false;
}
```

**Expected behavior**

The first file should export `a, b, c` (and not throw).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

```sh
babel --plugins @babel/plugin-transform-modules-commonjs --delete-dir-on-start src-valid -d lib
```

**Environment**

```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.10.1 => 7.10.1
    @babel/core: ^7.10.2 => 7.10.2
    @babel/plugin-transform-modules-commonjs: ^7.10.1 => 7.10.1
```

**Possible Solution**
Not use `Object.defineProperty`? `configurable: true` ? But all of these have other sideffects

**Additional context**

Technically, f there are conflicting reexports (see `src-invalid`), there should be a SyntaxError (!).

But even [Rollup doesn't handle this correctly](https://rollupjs.org/repl/?version=2.15.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJTVDJTIyLiUyRmEuanMlNUMlMjIlM0IlNUNuZXhwb3J0JTIwKiUyMGZyb20lMjAlNUMlMjIuJTJGYi5qcyU1QyUyMiUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwYyUyMCU3RCUyMGZyb20lMjAnLiUyRmMxLmpzJyUzQiU1Q25leHBvcnQlMjBjb25zdCUyMGElMjAlM0QlMjAlNUMlMjJhJTVDJTIyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwYyUyMCU3RCUyMGZyb20lMjAnLiUyRmMyLmpzJyUzQiU1Q25leHBvcnQlMjBjb25zdCUyMGIlMjAlM0QlMjAlNUMlMjJiJTVDJTIyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmMxLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwYygpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBmYWxzZSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYzIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBjKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHRydWUlM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) (and Babel cannot work across multiple files anyway). https://github.com/rollup/rollup/issues/3629

**Comment by mischnic** [comment]
Loose mode with `exports[key] = _a[key];` works as expected

**Comment by nicolo-ribaudo** [comment]
Before throwing, we could check if the old value is `===` to the new value. This would shallow errors when there is a real duplicated binding exporting a primitive, but will allow us to correctly handle this case.
