### ISSUE TITLE
404 errors in docs

### ISSUE THREAD

**Issue by kobezzza** [babel/babel#1171]
https://babeljs.io/docs/usage/transformers/ 

* [es6.spec.blockScoping](https://babeljs.io/docs/usage/transformers/es6/block-scoping)
* [es6.spec.templateLiterals](https://babeljs.io/docs/usage/transformers/es6/spec-templat=e-literals)

**Comment by sebmck** [comment]
Fixed, thanks @kobezzza.

Also as per the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

Thanks!
