### ISSUE TITLE
Redundant polyfills added for IE11 with useBuiltIns: usage

### ISSUE THREAD

**Issue by georgeshevtsov** [babel/babel#11713]
## Bug Report
**Current behavior**
Targetting default browsers includes polyfills for IE11 which are useless according to **Can I Use**. 
I see these polyfills added

es.array.for-each { "ie":"11" }
web.dom-collections.for-each { "ie":"11" }
es.array.filter { "ie":"11" }
es.array.map { "ie":"11" }
es.array.slice { "ie":"11" }

- [REPL](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=usage&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4EExiQSwRRnwgDs4BvAKDkXLRigFcEZoAKAd3zIEoqtOnBgALfGgB0PMgBMIXOAF44MoXTETJvfPBWapOmJIBGvWRwN91I8VJS4kATwBizMgmW2tDvK_cIpuaWdtZ0AL5CRhwCNMLeUgCOzMApXgDaAIwANHAATLkAzAC6NgaSyanAXuWVKZIAZvhIMMBQHBzASAJKAHxwXXD9mXySALYOnUjK_YMAVHAAnGFwkXS-zm4eMYLxTE678XAAbihQcGcA5pgqHFfMY8BkMFJIT5diykoqmXAA_HB0vdHs80OkAAzFYpwABc2CgUBQTkkGycHDIzCQSFywKeLz4K3ip3ODQCWCg1y8VykaAICGAHBGNjoxLgpI8ADkUI8qRSwZDmXB8A04Bx2QguTzvioAORGfAoAgAL2AMtigo0dm0ZF0KMcaIMuXF5OuhOEa3NiGICFEoraUHVRzZAUl1RU1IhpSdCAYEDekiQEEuHAABgBRBHQOAQBAIZgI4CyERQJy8S4iCBwFgUMTVcUkchwAAklHFrvCcJDuXtZotkUi1FZvi8ZGAihweEIxFIZG45gU1mFopk8i4KJMngAZJPVP2xygJxVHScznA6m7Z3IFOPAokhOvGtAwygbWKAgWKHc-bELrg9X4toFUXdcDjr6trJER9uF553XfUUfII5BfMA-CAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=true&targets=&version=7.10.2&externalPlugins=)

**Input Code**

```js
export class Application {
  constructor(win) {
    this.window = win
    this.init = this.init.bind(this)
    this.applyFunc = this.applyFunc.bind(this)
  }
  init() {
    this.queue = [1, 2, 3]
    this.queue = this.queue.filter((el) => el > 1).map(el => el * 9)
  }
  applyFunc() {
    try {
      var args = (arguments.length === 1 ? [arguments[0]] : Array.apply(null, arguments))
      var funcArgs = args.slice(1)
      var funcName = args[0]
      if (funcName === 'initialize') {
        this.init.apply(this, funcArgs)
      }
    } catch (err) {
      funcName = args[0]
      console.log(`Error occurred trying to run the function ${funcName}: `, err)
    }
  }
}
```

**Expected behavior**
based on this [can I use for Array filter link](https://caniuse.com/#search=Array%20filter)
and others relate to forEach and map and slice these polyfills are not supposed to be included 

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
```js
{
  {
  "presets":  [
    [
      "@babel/env",
      {
          "debug": true,
          "useBuiltIns": "usage",
          "corejs": "3.6.5",
          "modules": false,
          "bugfixes": true,
          "targets": "defaults"
      }
    ]
  ]
}

}
```

**Environment**

```
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.10.1 => 7.10.1 
    @babel/core: ^7.10.2 => 7.10.2 
    @babel/preset-env: ^7.10.2 => 7.10.2 
    babel-loader: ^8.1.0 => 8.1.0 
    webpack: ^4.43.0 => 4.43.0 
```
- How you are using Babel: [`loader`]

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by nicolo-ribaudo** [comment]
Fore core-js 3, we don't maintain the compat data but they are in the `core-js` repository.

I suggest trying to ask there, or better cloning the repository and running the tests on ie11 to understand why the polyfill is included. Usually caniuse marks a feature as supported even if there are some bugs, and the polyfill is needed to fix them.

**Comment by georgeshevtsov** [comment]
@nicolo-ribaudo Thank you for your response, I see what you mean about Can I Use, But compat table tells the same. Those are ES5 features and according to this https://kangax.github.io/compat-table/es5/. I wish I could now who assigns polyfills to the code, is it babel/env or core-js. And by the way running the same code but with core-js 2 will not include the same polyfills as core-js 3

**Comment by nicolo-ribaudo** [comment]
Sorry for the incomplete response; I was from my smartphone and couldn't find the correct links.

- This is the file that contains compat data for `core-js@3`: https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/src/data.js. When a new version of that package is released, `@babel/preset-env` should automatically pick it up.
- This is the polyfill implementation. I don't know about IE11, but it seems like it's needed at lease for Edge 14: https://github.com/zloirock/core-js/blob/76d9bf50b1b15439366af92885c5a7a1d0ad61c6/packages/core-js/modules/es.array.filter.js#L8
- These are the tests: https://github.com/zloirock/core-js/blob/master/tests/tests/es.array.filter.js. Maybe you could try, without cloning the whole repository, to just run those assertions manually one by one in IE11 and check what is failing.

**Comment by and-poulsen** [comment]
@georgeshevtsov Did you figure anything out? This is bugging me as well - so many unnecessary imports.

**Comment by jtwee** [comment]
It seems to have been introduced with this commit [zloirock/core-js@fb6bd7fb4145399cfb8b6add18eb83109686699a](https://github.com/zloirock/core-js/commit/fb6bd7fb4145399cfb8b6add18eb83109686699a).

**Comment by and-poulsen** [comment]
Is there any alternative compatibility tables that we can use, that is not so incredibly strict. Something that is similar to caniuse or mdn

**Comment by georgeshevtsov** [comment]
> Is there any alternative compatibility tables that we can use, that is not so incredibly strict. There's good data in https://github.com/mdn/browser-compat-data and https://github.com/kangax/compat-table - it would then need to be mapped to this naming syntax
> 
> Looks like it used to use Kangax's compat table - [babel/babel-preset-env#7](https://github.com/babel/babel-preset-env/issues/7)
> 
> It also does look like the core-js-compat allows for some configuration of aggressiveness - but it would require manually adding every single polyfill you would like to use natively instead of polyfill, which doesn't help much when you want it automatically with useBuiltins: 'usage'
> 
> **Edit: I've rolled back to [7.3.4 which uses Kangax compat table](https://github.com/babel/babel/blame/7df0d161319817edbaad66255bd9d63741616dc9/packages/babel-preset-env/package.json), instead of the aggressive core-js-compat**
> 
> **This works way better for me - not so many unnecessary polyfills. Array.map and Array.reduce is then not polyfilled 🎉**
> 
> ` "@babel/core": "7.3.4", "@babel/preset-env": "7.3.4",`
> 
> I'd suggest going back to this @nicolo-ribaudo

Hey @and-poulsen thanks sounds like a good suggestion, I personally went for just manually excluding all redundant polyfills.

**Comment by nicolo-ribaudo** [comment]
Kangax's compat table is still used for core-js 2, while it has never been used for core-js 3.

**Comment by robinloeffel** [comment]
I'm facing the same issue here. These are my targets:

```js
{
  "android": "85",
  "chrome": "85",
  "firefox": "81",
  "ie": "11",
  "ios": "13",
  "safari": "13"
}
```

And these are some of the unnecessary polyfills I get:

```sh
es.array.find { "ie":"11" }
es.regexp.exec { "ie":"11" }
es.string.match { "ie":"11" }
es.string.split { "ie":"11" }
es.array.filter { "ie":"11" }
es.array.for-each { "ie":"11" }
```

Looking at the compat data linked [here](https://github.com/babel/babel/issues/11713#issuecomment-643413668) (https://github.com/zloirock/core-js/blob/v3.8.0/packages/core-js-compat/src/data.js), I see, that, `es.string.split`, for example should only be polyfilled for the following targets:

```js
  'es.string.split': {
    chrome: '54',
    firefox: '49',
    safari: '10.0',
  }
```

I'm on `core-js@3.8.0`, `@babel/core@7.12.9` and `@babel/preset-env@7.12.7` with the following config:

```js
module.exports = {
  presets: [[ '@babel/preset-env', {
    useBuiltIns: 'usage',
    corejs: 3,
    bugfixes: true
  }]],
  plugins: [
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-proposal-class-properties'
  ]
};
```

**Comment by nicolo-ribaudo** [comment]
> I see, that, `es.string.split`, for example should only be polyfilled for the following targets:
>
> ```js
>   'es.string.split': {
>     chrome: '54',
>     firefox: '49',
>     safari: '10.0',
>   }
> ```

No, that means that it should _not_ be polyfilled if you have at least those targets. The polyfills are being included because IE is not marked as fully supporting `String#split` (I _think_ that it's because it doesn't support some `Symbol`-related stuff).

Anyway, I'm closing this issue since discussion about core-js 3 compat data should be done in the `core-js` repo, where they are maintained.

**Comment by robinloeffel** [comment]
Thanks for the explanation and the hint about `@babel/plugin-syntax-dynamic-import`! Have a good one!

**Comment by backflip** [comment]
Based on @jtwee's link above, this seems to be related to "fixing early implementations of `Array#{ every, forEach, reduce, reduceRight, some }` for usage of `ToLength`".

Since my code does not seem to rely on this, I have decided to extend the `@babel/preset-env` config with the following:
```
exclude: ['es.array.for-each']
```
