### ISSUE TITLE
[Idea] Simple subclassing of native constructors

### ISSUE THREAD

**Issue by zloirock** [babel/babel#1172]
I see too many issues about the impossibility of subclassing of native constructors.

After the last changes of inheritance in the specification, we have 2 limitations: `Derived constructor must call super()`, `'this' is not allowed before super()` - in this case possible emulate inheritance of native constructors.

We can simply replace `this` in constructor to native instance with replaced prototype. For example:
```js
class A extends B {
  constructor(){
    super();
    this.x = 42;
  }
}

// currently:

// ...
  function A() {
    _classCallCheck(this, A);
    _get(Object.getPrototypeOf(A.prototype), "constructor", this).call(this);
    this.x = 42;
  }
// ...

// possible:

// ...
  function A() {
    _classCallCheck(this, A);
    var _this = _super(A, this, []);
    _this.x = 42;
    return _this;
  }
// ...

// helpers:

var _bind = Function.prototype.bind;
function _isNativeConstructor(it){
  // switch with native constructors or regexp with native check
}
function _super(C, that, args){
  var Super = Object.getPrototypeOf(C.prototype).constructor, result;
  if(_isNativeConstructor(Super)){
    result = new (_bind.apply(Super, [null].concat(args)))(); // constructor spread
    result.__proto__ = Object.getPrototypeOf(that);
    return result;
  }
  result = Super.apply(that, args);
  // possible simplify, but not sure
  return typeof result == 'object' || typeof result == 'function'
    && Object.prototype.toString.call(result) != '[object Object]' ? result : that;
}
```

Inheritance of native constructors will work only with `__proto__`, but currently `__proto__` used in inheritance of statics.

Looks ugly, works (for native constructors) slow, has some limitations, but it's better than nothing :)

**Comment by sebmck** [comment]
Hm, good idea! Ideally it'd only work for staticly inlined constructors right? So:

```javascript
class Foo extends Array {}
```

but not

```javascript
var Bar = Array;
class Foo extends Bar {}
```

**Comment by zloirock** [comment]
@sebmck why not? Should works too :)

**Comment by sebmck** [comment]
Because then you'd need to output a ton of boilerplate for even a simple derived class.

**Comment by sebmck** [comment]
Could make it use that only for inlined constructors and then add an `es6.spec.classes` transformer that does it for all classes.

**Comment by zloirock** [comment]
@sebmck class code size would perhaps even less. Additional size will be only in helpers. I agree, optional transformer for this is a good idea.

**Comment by zloirock** [comment]
If you wanna it only for staticly inlined constructors, possible simple
```js
class A extends Array{
  constructor(){
    super();
    this.x = 42;
  }
}
// =>
// ...
  function A() {
    _classCallCheck(this, A);
    // constructor spread only if it's required and native constructor accept more than 1 argument
    var _this = new Array();
    _this.__proto__ = A.prototype;
    _this.x = 42;
    return _this;
  }
// ...
```
but it, unlike the first variant, will kill multilevel inheritance
```js
class A extends Array {}
// in other module
class B extends A {}
```
