### ISSUE TITLE
@babel/core - Get rid of (only 4 instances) lodash to fix security issue

### ISSUE THREAD

**Issue by jorenbroekema** [babel/babel#11726]
## Feature Request

I would like to remove lodash as a dependency in @babel/core. There has been a very long period where lodash had the chance to fix a prototype pollution vulnerability, and even after long period of security companies advicing privately, the security report was published publicly. And still, the maintainer is openly ignoring the security problem. https://github.com/lodash/lodash/issues/4738

This has lead many dependents to get off lodash, rightfully so. Security should not be ignored for this long, especially with this many weekly downloads.

@babel/core is a pretty huge dependent of lodash, but there are actually only 4 instances where lodash is used:
- escapeRegExp --> ./src/config/pattern-to-regex.js
- escapeRegExp --> ./test/config-chain.js
- sortBy --> ./src/transformation/block-hoist-plugin.js
- cloneDeep --> ./src/transformation/normalize-file.js

Safe to say, lodash is just helpers, and you never actually NEED them, you can just use regular JavaScript or create your own helper if you need it. Reducing dependencies is always a smart security/risk move.

If the babel maintainers agree, I would be happy to try and provide a pull request to replace the instances of lodash in @babel/core so we can get rid of it, and subsequently fix the security vulnerability that so many people face who are using @babel/core. 

Let me know!

- [x] I would like to work on this feature!

**Comment by JLHwung** [comment]
I think if the goal was to minify Babel itself and to accelerate install speed, we can consider bundling lodash into `@babel/core` via RollUp, thus any unused lodash functionalities does _not_ exist in `@babel/core`. Therefore the security exposure is controlled.

> Safe to say, lodash is just helpers, and you never actually NEED them, you can just use regular JavaScript or create your own helper if you need it

I don't think reinventing lodash always leads to fixing vulnerabilities. The popularity of `lodash` encourages security folks to scrutinize the code base, while an helper function used in `@babel/core` only may not be watched carefully.

Note that if you are using `yarn` and worried about the lodash vulnerabillities, you can use `resolution` to point `lodash` to your own fork. So it fixed for all your dev tools that may depends on `lodash`.

```json
"resolutions": {
    "**/lodash": "file://my/own/lodash",
  }
```

**Comment by jaeh** [comment]
i looked through the babel packages directory to get an overview how much would have to be replaced.

i will leave this here for anyone picking this up in the hopefully near future.

### Usage locations
output of `find . | grep -nHIrF -- 'from "lodash'` in the babel/packages directory: 

```
grep -nHIrF -- from "lodash (in directory: /babel/packages/)
./babel-cli/src/babel/file.js:4:import defaults from "lodash/defaults";
./babel-cli/src/babel/dir.js:3:import defaults from "lodash/defaults";
./babel-cli/src/babel/dir.js:4:import debounce from "lodash/debounce";
./babel-cli/src/babel/util.js:5:import includes from "lodash/includes";
./babel-cli/src/babel/options.js:7:import uniq from "lodash/uniq";
./babel-helper-module-transforms/src/index.js:4:import chunk from "lodash/chunk";
./babel-helper-fixtures/src/index.js:1:import cloneDeep from "lodash/cloneDeep";
./babel-helper-fixtures/src/index.js:2:import clone from "lodash/clone";
./babel-helper-fixtures/src/index.js:3:import extend from "lodash/extend";
./babel-plugin-transform-block-scoping/src/index.js:5:import values from "lodash/values";
./babel-plugin-transform-block-scoping/src/index.js:6:import extend from "lodash/extend";
./babel-generator/src/printer.js:1:import isInteger from "lodash/isInteger";
./babel-generator/src/printer.js:2:import repeat from "lodash/repeat";
./babel-plugin-transform-proto-to-assign/src/index.js:2:import pull from "lodash/pull";
./babel-types/src/utils/inherit.js:2:import uniq from "lodash/uniq";
./babel-types/src/converters/valueToNode.js:2:import isPlainObject from "lodash/isPlainObject";
./babel-types/src/converters/valueToNode.js:3:import isRegExp from "lodash/isRegExp";
./babel-types/src/builders/builder.js:2:import loClone from "lodash/clone";
./babel-register/src/node.js:1:import deepClone from "lodash/cloneDeep";
./babel-register/src/node.js:4:import escapeRegExp from "lodash/escapeRegExp";
./babel-traverse/src/visitors.js:3:import clone from "lodash/clone";
./babel-traverse/src/path/introspection.js:4:import includes from "lodash/includes";
./babel-traverse/src/index.js:3:import includes from "lodash/includes";
./babel-traverse/src/scope/index.js:1:import includes from "lodash/includes";
./babel-traverse/src/scope/index.js:2:import repeat from "lodash/repeat";
./babel-traverse/src/scope/index.js:6:import defaults from "lodash/defaults";
./babel-traverse/test/traverse.js:1:import cloneDeep from "lodash/cloneDeep";
./babel-helper-regex/src/index.js:1:import pull from "lodash/pull";
./babel-plugin-transform-function-name/test/fixtures/function-name/modules-2/input.mjs:1:import last from "lodash/last"
./babel-helper-transform-fixture-test-runner/src/index.js:7:import defaults from "lodash/defaults";
./babel-helper-transform-fixture-test-runner/src/index.js:8:import includes from "lodash/includes";
./babel-helper-transform-fixture-test-runner/src/index.js:9:import escapeRegExp from "lodash/escapeRegExp";
./babel-helper-transform-fixture-test-runner/src/index.js:11:import extend from "lodash/extend";
./babel-helper-transform-fixture-test-runner/src/index.js:12:import merge from "lodash/merge";
./babel-helper-define-map/src/index.js:2:import has from "lodash/has";
./babel-core/src/transformation/block-hoist-plugin.js:3:import sortBy from "lodash/sortBy";
./babel-core/src/transformation/normalize-file.js:6:import cloneDeep from "lodash/cloneDeep";
./babel-core/src/config/pattern-to-regex.js:3:import escapeRegExp from "lodash/escapeRegExp";
./babel-core/test/config-chain.js:4:import escapeRegExp from "lodash/escapeRegExp";
Search completed with 39 matches.
```

#### functions in use:

```
const fns = [
  "defaults",
  "debounce",
  "includes",
  "uniq",
  "chunk",
  "cloneDeep",
  "clone",
  "extend",
  "values",
  "isInteger",
  "repeat",
  "pull",
  "uniq",
  "isPlainObject",
  "isRegExp",
  "escapeRegExp",
  "last",
  "merge",
  "has",
  "sortBy",
]
```

**Comment by jorenbroekema** [comment]
Thanks for the comments and clarification guys. Sadly I'm more busy than expected, and the scope is a little bit bigger than I thought initially as well, so I won't be able to pick this up anytime soon. Probably somewhere in August

**Comment by jaeh** [comment]
i would love to pick this up too, it's very tempting to get rid of the 272 security warnings npm shows for my static page generator.

if babel were my library, i would replace functions with their builtin versions (uniq, includes, etc)
in other cases i would probably copy the functionality into a new @babel/dash package, including the tests, then simplify the functionality and api where applicable.

@sebmck is this something that you are interested in?
before i start i will need a confirm that this will get merged, 
as well as get a briefing regarding the approach,
does a person in the team have some time to coordinate with me?

**Comment by nicolo-ribaudo** [comment]
Could we use the individual packages (like `lodadh.uniq`) instead of the "big" `lodash`? By doing so we would only get reports for vulnerabilities in the functions we are using.

**Comment by merceyz** [comment]
@nicolo-ribaudo Those have been deprecated and tend to lead to larger installs as people are likely to already have lodash in their dependency tree https://lodash.com/per-method-packages

**Comment by coreyward** [comment]
Fun fact: every Babel package brings its own `node_modules` folder along with its own copy of Lodash. Here's the `node_modules` folder on a larger app. The darker purple section is just @babel, and the consistently-sized bits are each a copy of lodash (5.1MB). 😬

<img width="393" alt="Screen Shot 2020-10-09 at 11 54 34 AM" src="https://user-images.githubusercontent.com/81224/95610647-405ffe80-0a26-11eb-8fc2-3c7c875e9d6c.png">

**Comment by nicolo-ribaudo** [comment]
That looks like a yarn/npm bug that can't properly dedupe deps :thinking:

**Comment by existentialism** [comment]
@coreyfarrell fwiw, I'm not seeing that in any of my projects that use Babel (all the lodash's get deduped), can you create a repo that reproduces that?

**Comment by coreyfarrell** [comment]
@existentialism I've been very busy lately / not closely following open source, I'm not sure if you meant to address @nicolo-ribaudo?  I have not seen any issue with lodash deduplication.

**Comment by existentialism** [comment]
@coreyfarrell weird why it @'d you, sorry. it was a reply to a now deleted comment? sorry for the noise.

**Comment by dodedom** [comment]
Would like to request it to be bumped to 4.17.20 because of the prototype pollution vulnerability issues.
