### ISSUE TITLE
Generic types in functions in typescript throws "Unexpected token"

### ISSUE THREAD

**Issue by Undefitied** [babel/babel#11733]
## Bug Report

**Current behavior**
Generic types in functions don't work.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAtgTwOoCcCGAHDBTFAxAVzGCgEtwYBeGAHgEEUBzCAFQRxmwA8pswATCDDRgEAbQC6AGhgARNFDRscAPhgAKUmFJk0AG0LEy4AJRU1AbwBQASBTYoBFGBgByABalXVgL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=)

**Input Code**

```js
const myWrapperFunction = <ArgsType extends any[], DataType> (initialFunction) => {
	return 'hi'
}
```

**Expected behavior**
Should work, I guess

**Babel Configuration**
- Filename: `.babelrc.json`

```js
{
  "presets": ["@babel/env", "@babel/preset-react", "@babel/preset-typescript"],
  "plugins": ["react-hot-loader/babel", "babel-plugin-styled-components", "transform-class-properties"]
}
```

**Environment**

```
System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.9.6 => 7.9.6
    @babel/preset-env: ^7.9.6 => 7.9.6
    @babel/preset-react: ^7.9.4 => 7.9.4
    @babel/preset-typescript: ^7.9.0 => 7.9.0
    babel-loader: ^8.1.0 => 8.1.0
    babel-plugin-styled-components: ^1.10.7 => 1.10.7
    babel-plugin-transform-class-properties: ^6.24.1 => 6.24.1
    webpack: ^4.43.0 => 4.43.0
```
- Monorepo: no
- How you are using Babel: cli, with webpack

**Possible Solution**

I've found a similar issue in the past: https://github.com/babel/babel/issues/9006 . This one, however, is not related to async/await.

**Additional context**
-

**Comment by nicolo-ribaudo** [comment]
If I enable TS in the repl ([link](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAtgTwOoCcCGAHDBTFAxAVzGCgEtwYBeGAHgEEUBzCAFQRxmwA8pswATCDDRgEAbQC6AGhgARNFDRscAPhgAKUmFJk0AG0LEy4AJRU1AbwBQASBTYoBFGBgByABalXVgL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=)) I cannot reproduce the issue.

Is your input file name ending with `.js` or `.ts`?

**Comment by Undefitied** [comment]
I see...
it is `entry: ['react-hot-loader/patch', './src/index.tsx'],`

**Comment by Undefitied** [comment]
So I have now tested my code with enabled TS in repl and it works there. Hence the issue is around my config. Thanks for the help.
Though I'm confident in the purity of my config the fact confuses me a bit. 

Maybe there can be some cache-files?
Please, close the issue if no.

**Comment by existentialism** [comment]
@Undefitied can you show stack trace? Trying to create a small repo that can repro the problem will help too

**Comment by Undefitied** [comment]
I've decided to ignore the problem for the time being and move further. I appreciate everyone's attention. Thank you.
