### ISSUE TITLE
Inheritance issue when subclassing transpiled ES6 class in ES5

### ISSUE THREAD

**Issue by croes** [babel/babel#11749]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
When subclassing an ES6 class in ES5, parent properties are not inherited.

- [Codesandbox](https://codesandbox.io/s/babel-es5-inheritance-cedhk?file=/src/sub-subclass.js)

You'll notice that the properties inherited from the `SubClass` and `Base` parent classes (first name / middle name) are undefined.

**Input Code**

See [Codesandbox](https://codesandbox.io/s/babel-es5-inheritance-cedhk?file=/src/sub-subclass.js)

```js
class Base {
  constructor() {
    this._firstName = "Abraham";
  }
}

class SubClass extends Base {
  constructor() {
    super();
    this._middleName = "Jebediah";
}

function SubSubClass() {
  SubClass.call(this);
  this._lastName = "Simpson";
}

SubSubClass.prototype = Object.create(SubClass.prototype);
SubSubClass.prototype.constructor = SubSubClass;

const test = new SubSubClass();

console.log(test._firstName); // undefined
console.log(test._middleName); // undefined
console.log(test._lastName); // Simpson
```

**Expected behavior**
The inherited properties are not undefined. (`SubSubClass._firstName`, `SubSubClass._middleName`).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    "env"
  ]
}
```

**Environment**

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  npmPackages:
    @babel/core: 7.10.3 => 7.10.3 
    @babel/preset-env: 7.10.3 => 7.10.3 
```
- Babel version(s): [7.10.3]
- Node/npm version: [12.18.1]
- OS: [Ubuntu 18.04.4 LTS ]
- Monorepo: [no]
- How you are using Babel: [cli / with parcel]

**Possible Solution**

Ran into this while upgrading dependencies.
This did work with an older version of babel:
```js
"devDependencies": {
    "@babel/core": "7.7.0",
    "@babel/preset-env": "7.7.1",
    "@babel/plugin-transform-classes": "7.7.0",
    "parcel-bundler": "^1.6.1"
  },
```

**Additional context**
/

**Comment by nicolo-ribaudo** [comment]
This is expected: in ES6 classes, `this` is created by the `Base` class. This means that the `this` you pass as a parameter to `SubClass.call` is ignored. Your code doesn't work natively in a browser because classes cannot be `.call`ed: you should use `Reflect.construct` instead.

```js
class Base {
  constructor() {
    this._firstName = "Abraham";
  }
}

class SubClass extends Base {
  constructor() {
    super();
    this._middleName = "Jebediah";
  }
}

function SubSubClass() {
  Reflect.construct(SubClass, [], SubSubClass);
  this._lastName = "Simpson";
}

SubSubClass.prototype = Object.create(SubClass.prototype);
SubSubClass.prototype.constructor = SubSubClass;

const test = new SubSubClass();

console.log(test._firstName); // undefined
console.log(test._middleName); // undefined
console.log(test._lastName); // Simpson
```

As you can see, it logs `undefined` for `_firstName` and `_middleName`. The proper way of extending ES6 classes with ES5-style "classes" is to get the new `this` and use it:


```js
class Base {
  constructor() {
    this._firstName = "Abraham";
  }
}

class SubClass extends Base {
  constructor() {
    super();
    this._middleName = "Jebediah";
  }
}

function SubSubClass() {
  var _this = Reflect.construct(SubClass, [], SubSubClass);
  _this._lastName = "Simpson";
  return _this;
}

SubSubClass.prototype = Object.create(SubClass.prototype);
SubSubClass.prototype.constructor = SubSubClass;

const test = new SubSubClass();

console.log(test._firstName); // Abraham
console.log(test._middleName); // Jebediah
console.log(test._lastName); // Simpson
```

**Comment by croes** [comment]
Thanks for the clear explanation, @nicolo-ribaudo! I assume it only worked coincidentally in older versions of Babel.
We'll adapt our remaining ES5 code to use `Reflect.construct`, and tell our API users to do the same. Those that target IE will have to polyfill it, but I take it they're already doing plenty of polyfilling.
