### ISSUE TITLE
transpiled rest param changes semantics of code

### ISSUE THREAD

**Issue by yortus** [babel/babel#11744]
## Bug Report

The transpiled code for rest params may have different semantics to the original code. The transpiled code injects a reference to `Array`, assuming it is the builtin array constructor. However if another identifier called `Array` is in scope, it will be referenced instead.

**Input Code**

```js
let Array = [];
let f = (...args) => args;
console.log(f(1, 2, 3));
```

**Current behavior**

Running the transpiled code for [this example](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAggTjCGBPCBeCBtAugbgFCkgDNUIAKAOkvhgHMBnASlQD4Jr68BjAewDs7uocsG41ShUgEYANBABMsgMwMG2IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.10.3&externalPlugins=) throws `"TypeError: Array is not a constructor"`.

**Expected behavior**
Running the transpiled code outputs `[1, 2, 3]`.

**Environment**
- Babel version: v7.10.3
- How you are using Babel: babeljs.io/repl

**Comment by JLHwung** [comment]
Currently Babel output assumes the built-ins are not modified in a spec-incompliant way. In your case it is shadowed and `Array` is not a constructor anymore.

**Comment by yortus** [comment]
> Currently Babel output assumes the built-ins are not modified in a spec-incompliant way.

The builtin is not modified, and there is nothing spec-incompliant in the sample code.

This is simple shadowing by an ordinary variable in lexical scope. Babel is just making a faulty assumption here.

The section added to `caveats.md` in the linked PR (https://github.com/babel/website/pull/2283) doesn't cover babel's assumptions about simple shadowing. To cover this case and eg #10807, I suggest extending the wording in `caveats.md` to add babel's assumption that the program will not have any variables in scope with the same name as builtins.

Alternatively, since babel knows the variable names in the program being transpiled, it could issue an error here since the output would be invalid. Or even better, refer to builtins in a way that can't clash with local names.
