### ISSUE TITLE
make build broken

### ISSUE THREAD

**Issue by hipertracker** [babel/babel#1175]
I cannot build dist/* with `make build`. It stops at `node packages/babel-cli/bin/babel-external-helpers >dist/external-helpers.js` with error:

```
node packages/babel-cli/bin/babel-external-helpers >dist/external-helpers.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'commander'
```

I added it with `npm install commander` and reply the command. Now, I get another  error:

```
node packages/babel-cli/bin/babel-external-helpers >dist/external-helpers.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-core'
```
This time I cannot add it with `npm install babel-core` because 

```
npm WARN install Refusing to install babel-core as a dependency of itself
```
Any comments?

**Comment by sebmck** [comment]
Run `make bootstrap`.
