### ISSUE TITLE
Parser throws `undefined` when parsing HTML-Like comment

### ISSUE THREAD

**Issue by fisker** [babel/babel#11769]
## Bug Report

- [ ] I would like to work on a fix!

Properly not

**Current behavior**

When parsing HTML-Like comment with `sourceType: 'module'`, the `@babel/parser` throws `undefined`.

**Input Code**

```js
require('@babel/parser').parse('alert(<!--comment\n)', {plugins: ['jsx'], sourceType: 'module'})
```

**Expected behavior**

Should throw an error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

NaN

**Environment**

```
- Babel version(s): 7.10.4
- Node/npm version: [e.g. Node v14.4.0/npm v6.14.5]
- OS: Windows 10
- Monorepo: no
- How you are using Babel: api
```

**Possible Solution**

NaN

**Additional context**

PR on Prettier project https://github.com/prettier/prettier/pull/8688

CI Log https://github.com/prettier/prettier/runs/825234580?check_suite_focus=true#step:7:1200

> Expected error, Received: undefined

**Comment by fisker** [comment]
Maybe caused by #11722?

**Comment by fisker** [comment]
Local tested changing

https://github.com/babel/babel/pull/11722/files#diff-56fea09eea2de51b8291db400d2f69beR1175

to 

```diff
-          throw this.expectOnePlugin(["jsx", "flow", "typescript"]);
+          this.expectOnePlugin(["jsx", "flow", "typescript"]);
```

Fixes this issue, but I think it's not right, if it's HTML-Like comment, it should not expect those plugins, and those plugins wouldn't help.

Maybe we need check `sourceType` there.

I'm not familiar with codebase, I'm not going to send PR.

**Comment by JLHwung** [comment]
@fisker Thanks for the detailed report and background digging. It helps a lot.
