### ISSUE TITLE
for...of loop on HTMLcollection not working in old devices like iPhone 4s

### ISSUE THREAD

**Issue by butlimous** [babel/babel#11763]
## Bug Report

**Current behavior**

The new for....of loop does not work on HTML collections in old browsers like that of iPhone 4s. It does not understand the syntax at all, not even catching an error in try,catch.

**Input Code**

```js
let ids = [];
for (const element of document.getElementsByTagName('div')) {
  ids.push(element.id);
}
```

**Expected behavior**

The syntax should work on old devices that don't support it (like the iPhone 4s) as it works on new devices that support it (iPhone 8, Android Chrome, OSX safari, OSX chrome, ...etc)

**Environment**

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
    Babel: 7.9.0
    Babel preset-env: 7.9.5
 - How you are using Babel: [`loader`]
```

**Possible Solution**
Babel could compile the new syntax to the old one:
```js
for(let i=0; i < document.getElementsByTagName('div').length; i++)
```

**Comment by JLHwung** [comment]
Please upgrade to Babel 7.10 and specify `allowArrayLike: true` (https://babeljs.io/docs/en/babel-plugin-transform-for-of#allowarraylike)

```json
{
  "plugins": [
    ["@babel/plugin-transform-for-of", {
      "allowArrayLike": true
    }]
  ]
}
```
