### ISSUE TITLE
New version not found using npm cli

### ISSUE THREAD

**Issue by seanc-dev** [babel/babel#11766]
## Bug Report

**Current behavior**

npm install fails on dependency @babel/types@^7.10.4, listed as dependency of @babel/generator. Non-existent version of dependency. 

npm view @babel/types returns 7.10.3 as the most recent version, but https://www.npmjs.com/package/@babel/types shows 7.10.4.

**Environment**
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v10.14.2/bin/npm

-- gatsby starter uses the following babel dependencies:
"@babel/core": "7.9.0",
    "@babel/plugin-proposal-class-properties": "7.8.3",
    "@babel/plugin-proposal-optional-chaining": "7.9.0",
    "@babel/plugin-transform-flow-strip-types": "^7.9.0",
    "@babel/preset-env": "7.9.5",
    "@babel/preset-react": "7.9.4",

**Additional context**
fwiw, this is the starter I'm using: https://github.com/alxshelepenok/gatsby-starter-lumen

**Comment by igl** [comment]
I had this problem too.

I upgraded `@babel/cli` to `7.10.4` but `@babel/cli@7.10.4` was not found in the registry. 
https://registry.npmjs.org/@babel%2ftypes was not listing the `7.10.4` version.
When i tried to load `@babel/types@7.10.4` in codesandbox.io it worked!

I suspect the npm-registry had a outdated http-cache in my region.

I could only successfully upgrade all of babels packages after a few hours. (3 hours after the publish date to be exact)

**Comment by JLHwung** [comment]
@babel/types@7.10.4 is [published](https://www.npmjs.com/package/@babel/types) on npm. 

Please check if you are behind a proxy or using a third party npm registry. There are situations when these cache need some time to update to the latest version. You could also find a solution in https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed
