### ISSUE TITLE
Non-legacy decorators @babel/plugin-proposal-decorators issue when decorating both getter and setter of a property

### ISSUE THREAD

**Issue by tonix-tuft** [babel/babel#11765]
## Bug Report

Hello, I am facing this issue when I use non-legacy decorators on a getter and a setter:

```
Uncaught ReferenceError: Decorators can't be placed on different accessors with for the same property (prop).
```

**Input Code**

```js
// index.js
const decorator = (label) => (...args) => {
  console.log(label, ...args);
};

class SomeClass {
  constructor() {
    this.value = 123;
  }

  @decorator("getter")
  get prop() {
    return this.value;
  }

  @decorator("setter")
  set prop(value) {
    console.log(`Setting prop value to ${value}`);
    this.value = value;
  }
}
```

```js
// .babelrc
// ...
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        // ...
      ]
// ...
```

Works as expected (no errors with legacy decorators).

Whereas with this `.babelrc`:

```js
// ...
      "plugins": [
        [
          "@babel/plugin-proposal-decorators",
          { "decoratorsBeforeExport": false }
        ],
        // ...
      ]
// ...
```

I get the error:

```
Uncaught ReferenceError: Decorators can't be placed on different accessors with for the same property (prop).
```

**Expected behavior**
No error as in legacy mode.

Thank you!

**Comment by JLHwung** [comment]
The current decorators proposal is completely rewritten compared to the legacy one. So different behaviours are expected when switching from legacy to current proposal.

The current implementation matches the behaviour specified in clause 3.a.i.3 of https://tc39.es/proposal-decorators/#sec-coalesce-class-elements , if you consider such behaviour is questionable, please submit an issue to the decorators proposal instead.

**Comment by tonix-tuft** [comment]
Thank you for your reply! I have found the answer on the BabelJS Slack group, the code should be rewritten to this:

```js
  @decorator("getter")
  @decorator("setter")
  get prop() {
    return this.value;
  }
  set prop(value) {
    console.log(`Setting prop value to ${value}`);
    this.value = value;
  }
```

This way it works both with legacy as well as non-legacy decorators.
