### ISSUE TITLE
The lastest version of @babel/helper-builder-react-jsx-experimental in registry is 7.10.1 but when installing it gets 7.10.4

### ISSUE THREAD

**Issue by araujosnathan** [babel/babel#11772]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-builder-react-jsx-experimental@^7.10.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/plugin-transform-react-jsx'
npm ERR! notarget

**Comment by ZacharyRaineri** [comment]
I was able to install @7.10.4 with no issues and it looks like 7.10.4 is the [latest version](https://www.npmjs.com/package/@babel/helper-builder-react-jsx-experimental)

You can try clearing the npm or yarn cache (whichever you use):
`npm cache clean`
`yarn cache clean`

Then delete your lock file and try an install

Hope this helps! 👍

**Comment by araujosnathan** [comment]
Helllo @ZacharyRaineri! Thanks for your reply!
I have tested and really it is ok!
When i open a new root folder and install it, it works!
But when i am in specific folder where is my project that error happened! Do you know what can be doing that?

**Comment by ZacharyRaineri** [comment]
@araujosnathan no problem!

In the project folder, delete the node_modules folder and the lock file then try an install

**Comment by araujosnathan** [comment]
I found the problem! It relates to particular registry that was set!
Thanks @ZacharyRaineri  for your help! I am going to close this issue!

**Comment by ZacharyRaineri** [comment]
@araujosnathan Sounds good glad it's working!
