### ISSUE TITLE
Trying to install  @babel/helper-validator-identifier but instead of 7.10.4 it is installing 7.10.3 which is not latest

### ISSUE THREAD

**Issue by qaiser1516** [babel/babel#11771]
## Bug Report

- [ ] I would like to work on a fix!
![bable issue](https://user-images.githubusercontent.com/4457174/86233675-74fa2980-bb9e-11ea-858e-a0c20d8fca82.png)

**Current behavior**
A clear and concise description of the behavior.

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by ZacharyRaineri** [comment]
The outdated version may be cached.  Have you tried?
`npm cache clear`

Also you can install a specific version with:
`npm install --save-dev @babel/helper-validator-identifier@7.10.4`

or the latest stable with:
`npm install --save-dev @babel/helper-validator-identifier@latest`

In this instance those both should be the same, but the second doesn't require you to know the latest stable version.

For yarn users:
`yarn add @babel/helper-validator-identifier@7.10.4 --dev`
`yarn add @babel/helper-validator-identifier@latest --dev`

Hope this helps :+1:

**Comment by qaiser1516** [comment]
![bable issue2](https://user-images.githubusercontent.com/4457174/86235231-c60b1d00-bba0-11ea-8661-f16151532547.png)
I tried the above steps, here are the result,
when I executed this command : npm install --save-dev @babel/helper-validator-identifier@latest
Result : 7.10.3 got installed

And when I ran this command: npm install --save-dev @babel/helper-validator-identifier@7.10.4
Result: Got an exception, 

But when I am going to npm page for this it is showing latest version as 7.10.4, so this must be an error.

**Comment by qaiser1516** [comment]
And this is coming from today, I am working on an angular app and when I am trying to run **npm i** this is the error it is showing

 npm i                                                                          npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @angular/http@7.2.16: Package no longer supported. Use @angular/common instead, see https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated rollup-plugin-node-resolve@3.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.0.4: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated tooltip.js@1.3.3: Tooltip.js is not supported anymore, please migrate to tippy.js
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-validator-identifier@^7.10.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/types'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qimam\AppData\Roaming\npm-cache\_logs\2020-07-01T10_46_32_589Z-debug.log

**Comment by ZacharyRaineri** [comment]
Try clearing cache, deleting your node_modules folder, and deleting the lock file before doing the install

It's common to get some depreciation warnings depending on the dependencies you're using, if at all possible try to use the most updated versions. fsevents is just because your not on a mac, that won't go away unfortunately

**Comment by qaiser1516** [comment]
My Apologies,
the issue is related to registry, my organization registry is not updated and hence i was getting this error.
thanks it is resolved now.

**Comment by ZacharyRaineri** [comment]
@qaiser1516 Glad to hear it's working for you 👍
