### ISSUE TITLE
@babel/generator generates TSPropertySignature in TSTypeLiteral with semicolon instead of comma

### ISSUE THREAD

**Issue by floriangosse** [babel/babel#11773]
## Bug Report

I try to convert some code in our project with the use of `@babel/generator`. The problem is the output for `TSTypeLiteral` can cause a syntax error.

**Current behavior**

`TSPropertySignature` inside of `TSTypeLiteral` has trailing semicolon instead of a comma.

- [Repo for reproduction](https://github.com/floriangosse/issue-babel-generator-tstypeliteral-tspropertysignature)

**Environment**

```
- @babel/generator: 7.10.4
- @babel/types: 7.10.4
```

**Possible Solution**

Adjust generator to render the property signature based on parent's type. 

https://github.com/babel/babel/blob/3d498d05e737b6b497df55a177c113fd8167b744/packages/babel-generator/src/generators/typescript.js#L80-L95

**Comment by JLHwung** [comment]
TypeScript 3 accepts both `;` and `,` for property signature in type literal: [REPL](https://www.staging-typescript.org/play?useDefineForClassFields=true&ts=3.3.3#code/C4TwDgpgBAglC8UDeUBmB7dAuKBnYATgJYB2A5gDRQBGAhgTvseVQL4BQ7okUAQgsjSZGhUmQDcNeiOYSorIA).

> TSPropertySignature inside of TSTypeLiteral has trailing semicolon ... [which] can cause a syntax error

What is the version of your TypeScript compiler?

**Comment by floriangosse** [comment]
I'm using `typescript@3.9.5`. But it seems to work now. It might have been a problem with another part of my toolchain.

I'll close this issue.
