### ISSUE TITLE
Using the -d option and inconsistency issues

### ISSUE THREAD

**Issue by bucaran** [babel/babel#1178]
About using the `-d` option:
> -d, --out-dir [out]                Compile an input directory of modules into an output directory

```fish
babel src -d lib
src/index.js -> lib/index.js  # OK!

babel src/index.js -d lib 
src/index.js -> lib/src/index.js # Wut?
```

In the second example the new file is generated in `lib/src/index.js`, when I was expecting it to be in `lib/index.js`.

Am I missunderstanding something or what is the reasoning behind this?

**Comment by sebmck** [comment]
That behaviour was chosen because if you did:

```sh
$ babel foo/bar/index.js -d lib
```

You wouldn't expect it to go into `lib/index.js` or would you? Both behaviour is pretty weird so I just settled on what was the easiest.
