### ISSUE TITLE
Cant see console.log again in Remote Debug

### ISSUE THREAD

**Issue by marceliano13** [babel/babel#11788]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
I added thee remove console plugin, saw it working an tried to remove it. Now when i do remote debug i cant see logs anymore in iOS, Android works fine.

**Input Code**

**Expected behavior**
Show console.log

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Comment by JLHwung** [comment]
> I added thee remove console plugin

They are not reflected on your posted babel config. And I am not sure how this issue is related to Babel.
