### ISSUE TITLE
@babel/preset-env not including classProperties

### ISSUE THREAD

**Issue by reintroducing** [babel/babel#11796]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
According to https://github.com/babel/babel/blob/master/packages/babel-compat-data/scripts/data/plugin-features.js, it looks like `@babel/plugin-proposal-class-properties` is no longer needed and included in `preset-env`, please correct me if I'm wrong here because that would nullify this whole issue. That being said, without including it, I'm getting the following error:
```
{ SyntaxError: /Users/mattp/Work/SpotHero/fe-ui/src/AutoSuggestInput/AutoSuggestInput.jsx: Support for the experimental syntax 'classProperties' isn't currently enabled (13:22):

  11 |
  12 | export default class AutoSuggestInput extends Component {
> 13 |     static propTypes = {
     |                      ^
  14 |         ...TextInputPropTypes,
  15 |         /** Whether or not to highlight the first suggestion in the list when suggestions are presented. */
  16 |         autoActivateFirstSuggest: PropTypes.bool,

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.
    at Object._raise (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:757:17)
    at Object.raiseWithData (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:750:17)
    at Object.expectPlugin (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:8839:18)
    at Object.parseClassProperty (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:12232:12)
    at Object.pushClassProperty (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:12192:30)
    at Object.parseClassMemberWithIsStatic (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:12125:14)
    at Object.parseClassMember (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:12062:10)
    at withTopicForbiddingContext (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:12007:14)
    at Object.withTopicForbiddingContext (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:11078:14)
    at Object.parseClassBody (/Users/mattp/Work/SpotHero/fe-ui/node_modules/@babel/parser/lib/index.js:11984:10)
  loc: Position { line: 13, column: 21 },
  pos: 523,
  missingPlugin: [ 'classProperties' ],
  code: 'BABEL_PARSE_ERROR' }
```

**Input Code**

```js
...see below
```

**Expected behavior**
The cli will run through the code and not produce any errors.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: 
```
"babel": {
    "presets": [
      "@spothero/spothero"
    ]
  }
```

I have a preset I created that handles babel configuration.

```js
// preset-env included plugins: https://github.com/babel/babel/blob/master/packages/babel-compat-data/scripts/data/plugin-features.js
module.exports = () => ({
    presets: [
        [
            require('@babel/preset-env', {
                useBuiltIns: 'entry',
                corejs: 3,
            }),
        ],
        require('@babel/preset-react'),
    ],
    plugins: [
        [require('@babel/plugin-transform-runtime', {corejs: 3})],

        // Stage 1
        require('@babel/plugin-proposal-export-default-from'),

        // Stage 3
        require('@babel/plugin-proposal-logical-assignment-operators'),
        require('@babel/plugin-syntax-dynamic-import'),

        // Stage 4
        require('@babel/plugin-proposal-export-namespace-from'),
    ],
    env: {
        development: {
            plugins: [require('react-hot-loader/babel')],
        },
        production: {
            plugins: [
                [
                    require('babel-plugin-transform-react-remove-prop-types', {
                        removeImport: true,
                        ignoreFilenames: ['node_modules'],
                    }),
                ],
            ],
        },
    },
});
```

**Environment**

```

```
System:
    OS: macOS 10.15.3
  Binaries:
    Node: 10.3.0 - ~/.nvm/versions/node/v10.3.0/bin/node
    npm: 6.1.0 - ~/.nvm/versions/node/v10.3.0/bin/npm
  npmPackages:
    @babel/core: 7.10.4 => 7.10.4
    @babel/runtime-corejs3: 7.10.4 => 7.10.4
    babel-loader: 8.1.0 => 8.1.0
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
Adding `[require('@babel/plugin-proposal-class-properties', {loose: true})],` as the last plugin entry in the config fixes the issue.

**Additional context**
If I misunderstood what is included in preset-env and the plugins in the linked file above are not actually included, please let me know. This will beg the question, where can I find all the plugins included with `preset-env`, however?

**Comment by JLHwung** [comment]
Sorry for the short reply as I am on the phone. Please checkout https://babeljs.io/docs/en/babel-preset-env#shippedproposals

**Comment by reintroducing** [comment]
> Sorry for the short reply as I am on the phone. Please checkout https://babeljs.io/docs/en/babel-preset-env#shippedproposals

No worries, thank you. I went ahead and tried this, however, and removed the class properties proposal and i'm still seeing the issue. I removed class properties proposal plugin and changed my preset-env config to this:
```
[
    require('@babel/preset-env', {
        useBuiltIns: 'entry',
        corejs: 3,
        shippedProposals: true,
    }),
],
```

Did I misunderstand something?

**Comment by reintroducing** [comment]
@JLHwung In reading the babel docs again, I think I misunderstood and because I'm using `useBuiltIns: 'entry'` I need to directly import the proposal polyfill. If I were using 'usage' then I could use `shippedProposals: true`. Is that correct?

**Comment by existentialism** [comment]
@reintroducing `shippedProposals` is unrelated to `useBuiltIns`. `useBuiltIns` adjusts how _polyfills_ are handled, not what transforms are performed.

**Comment by reintroducing** [comment]
@existentialism Hmm, I guess I'm confused by this bit in the docs then:
```
By default, only polyfills for stable ECMAScript features are injected: if you want to polyfill them, you have three different options:

when using useBuiltIns: "entry", you can directly import a proposal polyfill: import "core-js/proposals/string-replace-all".
when using useBuiltIns: "usage" you have two different alternatives:
set the shippedProposals option to true. This will enable polyfills and transforms for proposal which have already been shipped in browsers for a while.
use corejs: { version: 3, proposals: true }. This will enable polyfilling of every proposal supported by core-js.
```

**Comment by existentialism** [comment]
Yeah it's made slightly more confusing because there are _proposal_ polyfills too... but those again only apply to those [made available via core-js](https://github.com/zloirock/core-js/tree/master/packages/core-js/proposals).

**Comment by JLHwung** [comment]
```js
[
    require('@babel/preset-env', {
        useBuiltIns: 'entry',
        corejs: 3,
        shippedProposals: true,
    }),
],
```
is incorrect because it is passing `{ shippedProposals: true }` to `require()`, which is definitely no-op. I don't think the `require`-call is necessary here, and we don't recommend using `require("@babel/preset-env")` on the docs, too.

```js
[
    ['@babel/preset-env', {
        useBuiltIns: 'entry',
        corejs: 3,
        shippedProposals: true,
    }],
]
```

**Comment by reintroducing** [comment]
@JLHwung This is inside of an external config that gets published to npm and my understanding was that this is how they should be written. Is that not correct?

**Comment by existentialism** [comment]
@JLHwung nice catch on passing options to require()!

@reintroducing "Correct" really depends on a number of things, but if in your case it is necessary you can always do something similar to what CRA does:

```
[
  require('@babel/preset-env').default,
  {
    useBuiltIns: 'entry',
    corejs: 3,
    shippedProposals: true,
  },
],
```

**Comment by reintroducing** [comment]
oh, i see my error now and what you guys are saying, i forgot to close the require and pass the options after it. my apologies, i again misread the docs on creating presets. let me try to fix that first before anything :\

**Comment by JLHwung** [comment]
Sidenote: if your app is working perfectly with this preset already, maybe you can consider remove all options (since they are passed to `require()`) and resort to defaults -- it's much easier to maintain.

**Comment by reintroducing** [comment]
OK, that did the trick, final looks like this (for historical context if anyone is an idiot like me):
```
[
    require('@babel/preset-env'),
    {
        useBuiltIns: 'entry',
        corejs: 3,
        shippedProposals: true,
    },
],
```

@JLHwung This is actually a new preset I created when extracting the babel config out of a project so we can re-use it across the board and the issues I'm seeing are coming from my first try at implementing it and running babel with this preset. 

Anyway, thank you guys for the help in looking at this, really appreciate it. Babel configuration can be very confusing sometimes (I still don't know if I have the optimal config in this, but its a start at least), even though this wasn't as much a Babel config as just me not watching details of where I'm putting options. Great eye @JLHwung!
