### ISSUE TITLE
Insert more auxiliaryComments

### ISSUE THREAD

**Issue by alawatthe** [babel/babel#1180]
Using babel 5.0.9, the following code

```js
var factorial = function (n) {
  if (n === 0) {
    return 1;
  }
  else {
    return factorial(n - 1) * n;
  }
};
```

gets transpiled to

```js
"use strict";

var factorial = (function (_factorial) {
  function factorial(_x) {
    return _factorial.apply(this, arguments);
  }

  factorial.toString = function () {
    return _factorial.toString();
  };

  return factorial;
})(function (n) {
  if (n === 0) {
    return 1;
  } else {
    return factorial(n - 1) * n;
  }
});
```

When testing such a function, normally you don't test the ```factorial.toString```function, since this is just a babel implementation detail. But not testing it, decreases the test coverage. So I'd like to have the ```auxiliaryComment``` before the ```factorial.toString```function.

Any thoughts?

**Comment by kobezzza** [comment]
+1

More examples: auxiliaryComment in modules, UMD / AMD

```js
export myLib;
```

->

```js
(function (global, factory) {
	if (typeof define === 'function' && define.amd) {
		define('myLib', ['exports', 'module'], factory);
	} else if (typeof exports !== 'undefined' && typeof module !== 'undefined') {
		factory(exports, module);
	} else {
		var mod = {
			exports: {}
		};
		factory(mod.exports, mod);
		global.myLib= mod.exports;
	}
})(this, function (exports, module) {
   /* My real code */
});
```

**Comment by alawatthe** [comment]
Good point @kobezzza. I renamed the issue accordingly.

Does anyone know more places, where an auxiliaryComment would be great?

**Comment by sebmck** [comment]
I regret adding this option in the first place because it's going to make the transformation code extremely convoluted. Probably going to give this one a pass unless there's a more compelling use-case. If you need code coverage then use [babel-istanbul](https://github.com/ambitioninc/babel-istanbul) or [isparta](https://github.com/douglasduteil/isparta).
