### ISSUE TITLE
`arguments` object don't have a Symbol.iterator property

### ISSUE THREAD

**Issue by monolithed** [babel/babel#1181]
```js
// Firefox
void (() => console.log(...arguments))(0, 1); 
// TypeError: arguments[Symbol.iterator] is not a function
```

```js
// Babel
void (() => console.log(...arguments))(0, 1); // 0, 1
```

Problem is that `arguments` object don't have a `Symbol.iterator` property.

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createunmappedargumentsobject
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createmappedargumentsobject

**Comment by zloirock** [comment]
Step 7 at first link, step 22 at second. FF has wrong behavior.

`core-js` doesn't add `@@iterator` to `arguments` object:
```js
Object.getPrototypeOf(arguments) === Object.prototype
```
but `babel` uses `Array.from` for spread.

**Comment by zloirock** [comment]
BTW, [about your example](http://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-).

**Comment by monolithed** [comment]
I don't understand what you mean.

The fallowing examples:

```js
void (() => console.log(...arguments))(0, 1); 
```

```js
void function () { 
  console.log(...arguments)
}(0, 1); 
```

Should not be compiled by Babel!

>> FF has wrong behavior.
Why do you think so?

**Comment by zloirock** [comment]
* By spec, `arguments` object has default iterator, look closely at the links given by you.
* Arrow functions does not create `arguments` object.

> Why do you think so?

See spec.

**Comment by sebmck** [comment]
@monolithed 

Relevant steps from the spec @zloirock linked:

[9.4.4.6 CreateUnmappedArgumentsObject(argumentsList)](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createunmappedargumentsobject)

> Step 7. Perform DefinePropertyOrThrow(obj, @@iterator, PropertyDescriptor {[[Value]]:%ArrayProto_values%, [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true}).

[9.4.4.7 CreateMappedArgumentsObject ( func, formals, argumentsList, env )](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createmappedargumentsobject)

> Step 22. Perform DefinePropertyOrThrow(obj, @@iterator, PropertyDescriptor {[[Value]]:%ArrayProto_values%, [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true}).
