### ISSUE TITLE
[typescript] Generic parameter is not removed when using the optional chaining operator

### ISSUE THREAD

**Issue by RafaelSalguero** [babel/babel#11813]
## Bug Report

- [ X ] I would like to work on a fix!

**Current behavior**
Generic parameters are not removed from function calls after using the optional chaining operator

- [Codesandbox](https://codesandbox.io/s/red-leaf-z8wbs), [Repo](https://github.com/RafaelSalguero/BabelTypescriptGenericsError)
**Input Code**

```ts
//ok:
let x: number[] = [1,2,3];
x.map<boolean>(x => x > 1);

//error (generic parameter not removed):
let y: number[] = [1,2,3];
y?.map<boolean>(x => x > 1);
```

**Expected behavior**
Generic parameters should be removed from function calls after the optional chaining operator

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.json`

```json
{
  "presets": [
    [
      "@babel/preset-typescript",
      {
        "isTSX": true,
        "allExtensions": true
      }
    ]
  ]
}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD   
  npmPackages:
    @babel/cli: ^7.10.4 => 7.10.4
    @babel/core: ^7.10.4 => 7.10.4
    @babel/preset-typescript: ^7.10.4 => 7.10.4    
```
- Monorepo: no
- How you are using Babel: cli

**Comment by JLHwung** [comment]
`x?.map<boolean>()` is an `OptionalCallExpression`, we shall remove its `typeParameters` like we did for `CallExpression`

https://github.com/babel/babel/blob/55ce749f429ffd03ede4cd16afb4db1f89085540/packages/babel-plugin-transform-typescript/src/index.js#L418-L420



@RafaelSalguero If you are willing to send a PR, please leave a message so I will assign this issue to you, thanks.

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated) to `packages/babel-plugin-transform-typescript/test/fixtures/type-arguments`
1. Update the code!
1. `yarn jest transform-typescript` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by RafaelSalguero** [comment]
@JLHwung please assign the issue to me, thanks!
