### ISSUE TITLE
Options being passed in when invoking the require hook should be able to override .babelrc

### ISSUE THREAD

**Issue by gsklee** [babel/babel#1182]
For example, if I have this in `.babelrc`:

```javascript
"blacklist": [
  "es6.modules"
]
```

and am running a file with this require hook:

```javascript
require('babel/register')({
  blacklist: []
});
```

I think I should be able to override the defaults in `.babelrc` which is currently not the case.

**Comment by sebmck** [comment]
Going to close this and just say this is expected behaviour. I can't satisfy everybody and there'll likely be scenarios where someone wants `.babelrc` to override the register options.

**Comment by gsklee** [comment]
@sebmck If so, is there anyway to instruct Babel to ignore or override the settings in `.babelrc` for a particular run?

**Comment by sebmck** [comment]
Not at this time.
