### ISSUE TITLE
Upgrade lodash version as they have fixed one vulnerability

### ISSUE THREAD

**Issue by sukrut-gs** [babel/babel#11828]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**
A concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**.

**Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and how it might be documented. Maybe a mock-up?
Upgrade lodash version as they have fixed one vulnerability.

**Comment by existentialism** [comment]
@sukrut-gs thanks for the issue, but this is fixed in https://github.com/babel/babel/pull/11818 (and since we use `^` range for the dep you shouldn't need to wait for a Babel release, you can either remove `node_modules` or remove it from your lockfile and reinstall)
