### ISSUE TITLE
JSX plugins

### ISSUE THREAD

**Issue by insin** [babel/babel#1183]
Is it possible to write plugins which leverage Babel's support for JSX to output something other than `React.createElement()` calls?

Having React output as a default makes it easy for me to jump over to Babel when I want to make use of more ES<Number> transpilations in my React code, but since [JSX itself is a syntax extension](http://facebook.github.io/jsx/) rather than being React-specific, it's useful anywhere you're doing DOM building or generating any other tree-like structures.

I've tweaked React's own transformer to output [Mithril-compatible virtual DOM objects and function calls](https://github.com/insin/msx/) and would be interested in porting this to Babel if possible, to take advantage of the other transpilations it supports, without having to do a similar fork+tweak approach.

**Comment by sebmck** [comment]
Plugins by default run before all the internal transformers so they'll have raw access to the uneffected JSX AST. You can find the docs for plugins (if you haven't already) [here](http://babeljs.io/docs/usage/plugins/).
