### ISSUE TITLE
npm ERR code ETARGET-- no matching version found for babel/types@^7.10.5

### ISSUE THREAD

**Issue by MohammedYacub1029** [babel/babel#11841]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.10.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/helper-define-map'
npm ERR! notarget

can anyone help me on this

**Comment by manojsubbarayalugmi** [comment]
Even in the latest version https://www.npmjs.com/package/@babel/types **(@babel/types@7.10.5)** I'm facing the same error.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.10.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/helper-define-map'
npm ERR! notarget

**Comment by manojsubbarayalugmi** [comment]
> Even in the latest version https://www.npmjs.com/package/@babel/types **(@babel/types@7.10.5)** I'm facing the same error. Can someone help me to resolve the same...
> 
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @babel/types@^7.10.5.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of '@babel/helper-define-map'
> npm ERR! notarget

**Comment by MohammedYacub1029** [comment]
hey manoj its not actually a bug its jus a cache ask yur repo maintanence team to clear the cache it wil work fine
