### ISSUE TITLE
inlineEnvironmentVariables and babel cache

### ISSUE THREAD

**Issue by zertosh** [babel/babel#1186]
The babel cache doesn't respect changes to the inlined environment variables.

**Comment by sebmck** [comment]
Kinda tempted to just choke this up to expected behaviour. It seems dirty to save the environment variables in the cache key as I'd imagine it'd get extremely long and some environment variables are privy to constantly changing (ie. `PWD`), it'd require keeping a list of these non-constant environment variables and it'd vary from OS and shell so it'd be difficult.

**Comment by zertosh** [comment]
I agree. Even keeping track in the cache file of what values where inlined - kinda like config - seems like it would be error-prone. It's probably worth leaving a note somewhere that this behavior is expected.

**Comment by dgcoffman** [comment]
Hard to fix but this absolutely is not expected behavior.

**Comment by sebmck** [comment]
I know. Open to suggestions.

**Comment by dgcoffman** [comment]
I don't know your cache invalidation strategy so forgive my nativity... I'd include in the per-file cache key only those env variables that have been inlined in that file.

**Comment by sebmck** [comment]
Transformers aren’t aware of any type of cache and introducing that concept is incredibly dangerous.

**Comment by baer** [comment]
An example of a plugin that is affected is:
https://github.com/FormidableLabs/babel-plugin-transform-define

**Comment by pungggi** [comment]
same here https://github.com/brysgo/babel-plugin-inline-dotenv

could this be the path to a solution? : https://github.com/yosuke-furukawa/active-cache-babel-register

**Comment by trisys3** [comment]
Any plans to document this anywhere? I think I noticed this as environment variables seem inconsistent but upon clearing the cache they always get refreshed.
