### ISSUE TITLE
Enable logical assignment in @babel/preset-env

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11861]
## Feature Request

<div align="center">

### Logical assignment is Stage 4!
![](https://media.giphy.com/media/3o6MbnqpZBwWdWg3gk/giphy.gif)
</div>

This means that it should be enabled by default in `@babel/preset-env` :tada:

It should be done similarly to this commit: https://github.com/babel/babel/commit/b92ad318f173e1a0573a188324aa0c222ea35782

1. Add it to `packages/babel-preset-env/src/available-plugins.js`
2. Add the `compat-table` mapping to `packages/babel-compat-data/scripts/data/plugin-features.js` (you can find the correct feature name at https://kangax.github.io/compat-table/esnext/)
3. Run `cd packages/babel-compat-data` and `yarn build-data` to update the data about the supported browser versions
4. Update the test as needed (you don't need to write new tests)
5. PR! :tada:

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test if needed (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-preset-env` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-preset-env` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by arku** [comment]
@JLHwung I would like to work on this.

**Comment by morrme** [comment]
If this is for new-to-project contributors only (just saw that on a different issue) then I'll jump in and volunteer :)

**Comment by arku** [comment]
@morrme It is! Feel free to get started 🙂

**Comment by morrme** [comment]
@arku Thank you so much! :heart:

**Comment by existentialism** [comment]
@morrme let us know if you have any questions!

**Comment by morrme** [comment]
@existentialism Will do! Thanks!

**Comment by morrme** [comment]
I am at the step where I add the feature to `packages/babel-compat-data/scripts/data/plugin-features.js ` 
 ... I found "Logical Assignment" on https://kangax.github.io/compat-table/esnext/ but I am not sure where to put it in the` plugin-features` file.

**Comment by existentialism** [comment]
@morrme you can create a new mapping like so:

```
const es2021 = {
  "proposal-logical-assignment-operators": "Logical Assignment",
};
```

And then add `es2021` to `module.exports` at the bottom!

**Comment by JLHwung** [comment]
@morrme I forgot to mention that we have a new feature branch `feat-7.11.0/stage-4`, if you just started working on this issue, I suggest you checkout that branch instead of `main`. You can see there is an `es2021` item out there.

The PR should also target to `feat-7.11.0/stage-4` instead of `main`.
