### ISSUE TITLE
[babel-node] babel-node won't use --config-file when using -e codeToEval

### ISSUE THREAD

**Issue by vvo** [babel/babel#11877]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

Given a configuration file of:

```js
// .test-babelrc.js
module.exports = {
  presets: ["@babel/preset-env"],
};
```

And a command line of:

```bash
yarn babel-node --config-file ./.test-babelrc.js -e "const a = 1"
```

It will error with: "SyntaxError: /[redacted path]/[eval]: Only `var` variables are supported in the REPL". Because it's actually not using the configuration file.

The configuration file is not used to eval the code. You can even give the command line a bad configuration file path or mess up the inside syntax of the configuration: it does not matter, it won't be used.

If you rename `.test-babelrc.js` to `.babelrc.js` and change command to:

```bash
yarn babel-node -e "const a = 1"
```

Then it works, because somehow now the default babel configuration file location is used.
Also, if you use:

```bash
./node_modules/.bin/babel-node --config-file ./.test-babelrc.js ./test.js
```

Then it works, given a test.js file of:

```js
// test.js
const a = 1;
console.log(a);
```

PS: I **need** to use a different default configuration file path (.test-babelrc.js) in the context of my project.

**Input Code**

I created a repository to reproduce the bug here: https://github.com/vvo/test-babel-node-configuration-file

**Expected behavior**
The custom configuration file path should be used when combined with the eval code.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  presets: ["@babel/preset-env"],
};
```

**Environment**

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  npmPackages:
    @babel/core: 7.10.5 => 7.10.5
    @babel/node: 7.10.5 => 7.10.5
    @babel/preset-env: 7.10.4 => 7.10.4
```
- Monorepo: n/a
- How you are using Babel: babel-node

**Possible Solution**
n/a

**Additional context**
n/a

**Comment by JLHwung** [comment]
I believe the bug comes from the fact that we are not passing the normalized babel options 

https://github.com/babel/babel/blob/b9407d766062118660faab66bf7ce0d9ef1bcf74/packages/babel-node/src/_babel-node.js#L69-L86

to the `replEval` babel transform

https://github.com/babel/babel/blob/b9407d766062118660faab66bf7ce0d9ef1bcf74/packages/babel-node/src/_babel-node.js#L127-L131

The normalized options are registered in `@babel/register` but it is never applied to the REPL transform because evaluating code does not invoke the require hook.

@vvo Thanks for the reproduction repo! Let me know if you can spend some time working on that.

**Comment by ameenshake** [comment]
Looking to pick up my first issue. This appears to be within my capabilities. If there are no concerns, I will work on this :)

**Comment by JLHwung** [comment]
@ameenshake I have assigned the issue to you. Feel free to reach out on Slack if you have any questions on building / testing Babel.

**Comment by jimmymorris** [comment]
Any updates here?

**Comment by Mupli** [comment]
any updates here 2 ?

**Comment by slatereax** [comment]
It seems that there is no work being done on this issue, so I decided to try to figure it out. I apologize if I'm wrong.

Transform code for babel-node eval does not use the options that were passed in the cli flags. Also, replPlugin, which is used for code transformation, only allows var variables, although modern versions of node repl support let and const.

Based on the history of this file, it appears that this code was written in 2017 when node did not support any variables other than var, but there is no need for this check now. If anyone needs to use babel-node with node < 6.0.0, they can pass their configuration file through --config-file.

If i understand thi correctly, [this pull-request](https://github.com/babel/babel/pull/16642) should fix this bug.
