### ISSUE TITLE
[@babel/plugin-transform-runtime] Option absoluteRuntime not working as expected

### ISSUE THREAD

**Issue by sz-coder** [babel/babel#11885]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

- Clone [this](https://github.com/sz-coder/babel-issue-11885) repository.
- Run `npm install && npm run build`

Not all required runtime functions are `require`d with an absolute path:

```js
var _interopRequireDefault = require("<ABSOLUTE_PATH>/@babel/runtime-corejs3/helpers/interopRequireDefault");
var _map = _interopRequireDefault(require("@babel/runtime-corejs3/core-js-stable/instance/map"));
// ...
```

**Input Code**

```js
[1,2,3].map(console.log)
```

**Expected behavior**
Required runtime functions should be `require`d with an absolute path:

```js
var _interopRequireDefault = require("<ABSOLUTE_PATH>/@babel/runtime-corejs3/helpers/interopRequireDefault");
var _map = _interopRequireDefault(require("<ABSOLUTE_PATH>/@babel/runtime-corejs3/core-js-stable/instance/map"));
// ...
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
	"presets": ["@babel/preset-env"],
	"plugins": [["@babel/plugin-transform-runtime", {
		"helpers": true,
		"absoluteRuntime": true,
		"corejs": 3
	}]]
}

```

**Environment**

```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  npmPackages:
    @babel/cli: ^7.10.5 => 7.10.5
    @babel/core: ^7.10.5 => 7.10.5
    @babel/plugin-transform-runtime: ^7.10.5 => 7.10.5
    @babel/preset-env: ^7.10.4 => 7.10.4
    @babel/runtime: ^7.10.5 => 7.10.5
    @babel/runtime-corejs3: ^7.10.5 => 7.10.5
```
- Babel version(s): 7.10.5 (@babel/core 7.10.5)
- Node/npm version: v12.18.2 / 6.14.5
- OS: macOS 10.15.6
- Monorepo: no
- How you are using Babel: cli, node api

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by sz-coder** [comment]
I found the root cause of this behaviour:

In `packages/babel-plugin-transform-runtime/src/index.js`:

https://github.com/babel/babel/blob/6373eb5d82d527f9b86a0145bdd2c4c9970a16eb/packages/babel-plugin-transform-runtime/src/index.js#L313

https://github.com/babel/babel/blob/6373eb5d82d527f9b86a0145bdd2c4c9970a16eb/packages/babel-plugin-transform-runtime/src/index.js#L382

https://github.com/babel/babel/blob/6373eb5d82d527f9b86a0145bdd2c4c9970a16eb/packages/babel-plugin-transform-runtime/src/index.js#L410

If one replaces `moduleName` with `modulePath`, it works as expected.

I wanted to create a pull request, but I'm having issues getting the project running on my computer.

**Comment by JLHwung** [comment]
@sz-coder Join our [Slack community](https://babeljs.slack.com/) if you have troubles building Babel on your local machine.

**Comment by sz-coder** [comment]
OK, I forgot to `cd` into the repository before executing `make bootstrap`. It was a long day...

Anyway, got babel up and running, will work on a pull request now.
