### ISSUE TITLE
broken subclassing of Map and Set

### ISSUE THREAD

**Issue by jaawerth** [babel/babel#1188]
Hello! The Map and Set polyfills used in babel appear to be incompatible with subclassing via either ES6 syntax or the more ES5 setPrototypeOf/Object.create approach.

**Note:** overriding Map and Set by importing es6-shim makes the following work, so I imagine this is related to core-js.

For example, the following code:

```javascript
// structs.js
export class Dict extends Map {
  constructor(iter) {
    super(iter);
  }
}
 
export class Bin extends Set {
  constructor(iter) {
    super(iter);
  }
}
```

In each of these cases, the subclassed items instantiate fine, but calling any of the native methods `let d = new Dict(); d.set('foo', 1);`, `let b = new Bin(); b.add('foo');` throws an error with the following stacktrace. The results are same with the ES5 approach to subclassing.

```
TypeError: Method Map.prototype.set called on incompatible receiver [object Object]
    at Dict.set (native)
    at Dict.proto.(anonymous function) (/home/jesse/.nvm/versions/node/v0.12.0/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.collection.js:16:27)
    at Object.<anonymous> (/home/jesse/Projects/alfgate/util/transduce/structures.js:86:3)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/jesse/.nvm/versions/node/v0.12.0/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:122:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jesse/.nvm/versions/node/v0.12.0/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:135:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/home/jesse/.nvm/versions/node/v0.12.0/lib/node_modules/babel/bin/_babel-node:111:12)
```

Thanks!

**Comment by zloirock** [comment]
See [caveats](https://babeljs.io/docs/usage/caveats/#classes) and [this proposal](https://github.com/babel/babel/issues/1172).

**Comment by zloirock** [comment]
Also, why `es6-shim` collections are broken (just discussed):
```js
// test
var array = [];
for(var i = 0; i < 100000; i++)array.push([{}, {}]);
array = array.concat(array);
console.time('Map test');
var map = new Map(array);
console.log('Map size: ' + map.size);
console.timeEnd('Map test');

// es6-shim result:
// Map size: 100000
// Map test: 895443.700ms

// core-js result:
// Map size: 100000
// Map test: 737.848ms
```

**Comment by jaawerth** [comment]
Thanks for the links. I checked for existing posts on it yesterday and then didn't recheck before posting it today. I did see that caveats about built-ins, but I wasn't clear on it since Map and Set aren't really built-ins in ES5 environments.

Unless core-js uses the native object when it exists?

**Comment by zloirock** [comment]
@jaawerth `core-js` uses native collections in most case, just fixes methods / constructor, if it's required and in old environment uses fast polyfill (O(1) lookup). `es6-shim` replaces native collections in all environments and uses slow case for objects (O(n) lookup).

**Comment by jaawerth** [comment]
@zloirock Got it;  I just caught up on the discussion over in the es6-shim [here](https://github.com/paulmillr/es6-shim/pull/323) as well, so this makes a lot more sense. Thanks again.

**Comment by 75lb** [comment]
the "caveats" page linked to above is no longer available.. 

i also get the "incompatible receiver" error when subclassing Map.. is it possible to subclass Map using babel? after reading this thread i'm still unclear how to fix this..

**Comment by zloirock** [comment]
@75lb fast answer - no, you can't subclass built-ins with `babel`. You can do it only with some hacks, second link from the first comment.

**Comment by 75lb** [comment]
ok, thanks for letting me know.. although i am subclassing Array successfully (i haven't noticed any issues so far)..

**Comment by zloirock** [comment]
@75lb you can't subclass `Array` without hacks too, just `Array` methods generics and you still had not issues about `Array Exotic Objects` behavior.
