### ISSUE TITLE
@babel/parser throws error when the given JSX doesn't properly formatted

### ISSUE THREAD

**Issue by balazsmatepetro** [babel/babel#11884]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
It tried to parse the attached code snippet with the `@babel/parser` package, but it throws an error. As it turned out, it's caused by the missing semicolon between the `const` declaration and the `if` statement in the `onChange` event handler.
When the code is properly formatted, the error doesn't occur.

- [Failing example](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DwSQdgDgrgLgBANwIYCcCWSwwLwG8CmKKA9inAPxwDkAJpgOaFVwBccUYN-AZmmPjQC-iJABso-PMnH4KlKlWHEwAYQAWDSbgAU-BPixsASviQBjGADoAYqQC2AUX1ZgACQAqAWQAy4aDAdRfDsDGAA-AEo4bDC4XDgzZQBneH4AdwA1MQlouD1QyzMoIlD3VEYraRy0bjhtdKyZSzskGDM1bQB6AD1tchYAHRoAagjyABJOiKjcZXVNevxM7NlsNepmSjAoUVFWOAhUJPxwGEXlmQAaOABGAAZpuEFnuE6wgCggA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.10.5&externalPlugins=)
- [Working example](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DwSQdgDgrgLgUAAgQNwIYCcCWqwwLwDeApuugPboID8CARACY4DmJtCAXAlGPUQGaYwRegF9EKVABsoRQmmlFqNWrTFIyYAMIALZrIIAKIsiK5OAJSKoAxjAB0AMQoBbAKIncwABIAVALIAMuDQMK6SRM6mMAB8AJQIeNEIBOJI1hoAzjAIQgDuAGpSMgkIxlF21lCkUT4YLPbyMgDcqQiYfAgGeYUKds6oMNbaBgD0AHoGVOwAOvQA1LFUACQjsfEpSJsIGjp6XUQFRYp4J3RsNGBQkpIcCBAYGUTgMPuHCgA0CACMAAxrLVs1AgRGIRtEWkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.10.5&externalPlugins=)

**Input Code**

```jsx
<Input variant={error ? 'danger' : undefined} value={value ?? ''} onChange={(event: React.FormEvent<HTMLInputElement>) => { const newValue = event.currentTarget.value if (newValue.match(/^(?:\d+)?$/)) {onChange(newValue === '' ? null : parseInt(newValue, 10)) }}} />
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `cli command`

```js
{
    plugins: ['jsx', 'typescript'],
    allowReturnOutsideFunction: true,
}
```

**Environment**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.10.0/bin/npm
  npmPackages:
    @babel/cli: ^7.2.3 => 7.8.4 
    @babel/core: ^7.2.2 => 7.9.0 
    @babel/parser: ^7.10.5 => 7.10.5 
    @babel/plugin-proposal-class-properties: ^7.2.3 => 7.8.3 
    @babel/plugin-transform-runtime: ^7.6.2 => 7.9.0 
    @babel/preset-env: ^7.2.3 => 7.9.0 
    @babel/preset-react: ^7.0.0 => 7.9.4 
    @babel/preset-typescript: ^7.9.0 => 7.9.0 
    babel-jest: ^24.8.0 => 24.9.0 
    babel-loader: ^8.0.5 => 8.1.0 
    babel-plugin-emotion: ^10.0.21 => 10.0.33 
    babel-plugin-require-context-hook: ^1.0.0 => 1.0.0 
    jest: ^24.8.0 => 24.9.0 
    rollup-plugin-babel: ^4.4.0 => 4.4.0
```

- Monorepo: no
- How you are using Babel: Node.js

**Possible Solution**
n/a

**Additional context**
n/a

**Comment by nicolo-ribaudo** [comment]
This is expected: the missing semicolon is not just a formatting thing, it's a _syntax error_.

You can try running this code (without JSX) in Babel, and then in your browser's console: it will throw in both places.
```js
const a = 1 if (true) {}
```

**Comment by balazsmatepetro** [comment]
Hi @nicolo-ribaudo 

Thank you your for feedback. You're completely right, I tried to run the attached code snippet in the browser's console and it threw an error. I had a feeling it's a syntax error and not an error in the parser package, but thank you for the confirmation. :)

Feel free to close this issue.
