### ISSUE TITLE
Unexpected behavior when parsing { "foo": "bar" } vs { foo: "bar" }

### ISSUE THREAD

**Issue by hogpilot** [babel/babel#11880]
## Bug Report

**Current behavior**
On the Babel [homepage ](https://babeljs.io/) (or on the [repl](https://babeljs.io/repl)... or any configuration I have tried which uses '@babel/parser'), I'm seeing inconsistent behavior.

If you have simple input of `{ foo: "bar" }`, it parses to the same output `{ foo: "bar" }`.

However, if you express the same object another way, it throws an exception:

- JSON:  `{ "foo": "bar" }` throws the following error `Unexpected token, expected ";" (1:7)`
- Computed property names: `{ ["foo"]: "bar" }` throws the following error `Unexpected token, expected ";" (1:9)`

**Input Code**

```js
const babelParser = require('@babel/parser');     // version 7.10.5
const options = {};
babelParser.parse('{ foo: "bar" }', options);     // { foo: "bar" }
babelParser.parse('{ "foo": "bar" }', options);   // Unexpected token, expected ";" (1:7)
babelParser.parse('{ ["foo"]: "bar" }', options); // Unexpected token, expected ";" (1:9)
```

**Expected behavior**
I understand that the above examples aren't javascript files themselves, nor programs, but I would expect that they behave the same way (either all fail, or none fail).  In contrast, most browsers I tried the same expression in resolved to an object `{ foo: "bar" }`, although IE throws the same error as babel.

**Environment**
- Babel version: v7.10.5
- Node/npm version: 12.15.0
- OS: Windows 10
- How you are using Babel: cli and node script via direct import of "@babel/parser" with all defaults

**Additional context**
Babel homepage:
![image](https://user-images.githubusercontent.com/2762204/88599589-5fefa980-d029-11ea-8fc0-61b157166934.png)
![image](https://user-images.githubusercontent.com/2762204/88599546-464e6200-d029-11ea-9493-98f75c2fcc54.png)

Chrome console:
![image](https://user-images.githubusercontent.com/2762204/88599969-5286ef00-d02a-11ea-9c58-0727049b7ca1.png)

IE console:
![image](https://user-images.githubusercontent.com/2762204/88600212-e062da00-d02a-11ea-941e-eafc55314c0a.png)

**Comment by JLHwung** [comment]
> the above examples aren't javascript files themselves, nor programs

`{ foo: "bar" }` is indeed a valid JavaScript program. If you paste them to https://astexplorer.net/, you can see it is an BlockStatement `{}`, whose body is a LabeledStatement with label `foo` and the statement itself is an expression statement with string literal `"bar"`.

The IE's console output is indeed technically correct here: that `{ foo: "bar" }` returns `"bar"`. Hence the Chrome DevTools prefers convenience over technical correctness. It interprets `{ foo: "bar" }` as an object literal, just like it were wrapped in parenthesis:

```js
// an object literal
({ foo: "bar" })
```

Unlike Chrome DevTools where developers can inspect object literals, Babel REPL prefers technical correctness here. I don't think we will change the behaviour.
