### ISSUE TITLE
When '@babel/preset-env' loose: true , the NodeList can't iterat in [...nodeList]

### ISSUE THREAD

**Issue by huyaocode** [babel/babel#11886]
This is my setting:
```
  addBabelPresets([
    '@babel/preset-env',
    {
      useBuiltIns: 'usage',
      corejs: 3,
      shippedProposals: true,
      loose: true,
    },
  ]),
```
 When `loose` is set to `true`, I find my [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) can't iterat in spread array.

My code: 
```js
const list = [...nodelist]
```

**Comment by JLHwung** [comment]
https://babeljs.io/docs/en/babel-plugin-transform-spread#allowarraylike

You can add overwrite the options of `@babel/plugin-transform-spread`
```
addBabelPlugins([
    '@babel/plugin-transform-spread',
    {
      allowArrayLike: true,
    },
  ]),
```

**Comment by imirkin** [comment]
Note that I ran into this after upgrading to Angular 10, which no longer ships ES5-transpiled source, so I had to set up my own babel configuration for the first time. It uses this pattern with document.querySelectorAll(), which resulted in the error

    Invalid attempt to spread non-iterable instance.
    In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

It took me a while to track this issue down, so leaving a note about it here. The following webpack loader config did the trick for me:

      {
        test: /\.js$/,
        include: [
          helpers.root('node_modules', '@angular'),
          helpers.root('node_modules', 'zone.js'),
        ],
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                [ '@babel/preset-env', { useBuiltIns: 'entry', corejs: 3 } ],
              ],
              plugins: [
                // Angular likes to use spread with NodeList's which
                // in IE11 aren't actually iterable.
                [ '@babel/plugin-transform-spread', { allowArrayLike: true } ],
              ],
            }
          }
        ],
      },
