### ISSUE TITLE
[@babel/preset-typescript] not support typescript v4 `??=`

### ISSUE THREAD

**Issue by bluelovers** [babel/babel#11904]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

not support typescript v4 `??=`

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```js
a.x ??= 1
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by nicolo-ribaudo** [comment]
This isn't TypeScript-specific: it's a normal ECMAScript feature and it should be enabled by default in `@babel/core` 7.11.0. Which version are you using?

**Comment by bluelovers** [comment]
typescript v4 + tsconfig `"target": "ES2019"` support transpile `??=`
