### ISSUE TITLE
Property 'expression' does not exist on type 'Statement'.

### ISSUE THREAD

**Issue by leandrotk** [babel/babel#11905]
## Bug Report

- [X] I would like to work on a fix!

**Current behavior**
After parsing code, the `Statement` type doesn't support the `expression` attribute (node).

- [Repo](https://github.com/leandrotk/laziness/compare/dts-gen?expand=1#diff-1739f16282f84aeae86081efc4690dcdR30)

**Input Code**

```typescript
import * as parser from '@babel/parser';

const code = `
SampleComponent.propTypes = {
  arrayProp: PropTypes.array,
  boolProp: PropTypes.bool.isRequired,
  numberProp: PropTypes.number,
  objectProp: PropTypes.object,
  stringProp: PropTypes.string,
  anyProp: PropTypes.any,
  elementProp: PropTypes.element,
  nodeProp: PropTypes.node,
  arrayOfString: PropTypes.arrayOf(PropTypes.string),
  onChange: PropTypes.func.isRequired,
  oneOfString: PropTypes.oneOf(['foo', 'bar']),
	oneOfStringOrNumber: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
	shapeProp: PropTypes.shape({
		foo: PropTypes.number,
		bar: PropTypes.string
  }).isRequired,
  /**
   * @param {object} value - The param value.
   */
};
`;

const ast = parser.parse(code);
ast.program.body[0].expression; // Property 'expression' does not exist on type 'Statement'. Property 'expression' does not exist on type 'BlockStatement'.
```

**Expected behavior**

The body type is `Program.body: Statement[]`. And the first element of the body node looks like this:

```js
Node {
  type: 'ExpressionStatement',
  start: 1,
  end: 660,
  loc: SourceLocation {
    start: Position { line: 2, column: 0 },
    end: Position { line: 22, column: 2 }
  },
  expression: Node {
    type: 'AssignmentExpression',
    start: 1,
    end: 659,
    loc: SourceLocation { start: [Position], end: [Position] },
    operator: '=',
    left: Node {
      type: 'MemberExpression',
      start: 1,
      end: 26,
      loc: [SourceLocation],
      object: [Node],
      property: [Node],
      computed: false
    },
    right: Node {
      type: 'ObjectExpression',
      start: 29,
      end: 659,
      loc: [SourceLocation],
      properties: [Array],
      extra: [Object]
    }
  }
}
```

So I think the `Statement` type should have the `expression` attribute.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

The package uses TSDX as the foundation, but I'm just using babel to parse code here.

**Environment**

- Babel version(s): ^7.11.0
- Node/npm version: Node v14.3.0 (npm v6.14.5)
- OS: OSX 10.15.5
- Monorepo: yes
- How you are using Babel: as a parser

**Possible Solution**

The `BlockStatement` type should have the property `expression`.

**Additional context**
I'm using TypeScript together with Babel parser.

**Comment by leandrotk** [comment]
If I use the `@babel/traverse`, it works fine with the types.

```typescript
traverse(ast, {
  enter(path) {
    if (path.node.type === 'ExpressionStatement') {
      console.log(path.node.expression);
    }
  },
});
```

**Comment by nicolo-ribaudo** [comment]
It's because only `ExpressionStatement` has the `expression` property, not all the `Statement`s.

**Comment by JLHwung** [comment]
This is expected, see https://github.com/babel/babel/blob/main/packages/babel-parser/ast/spec.md for the AST spec.

**Comment by leandrotk** [comment]
It makes sense! Doing a `forEach` but narrowing the type also works fine.

```ts
ast.program.body.forEach((statement) => { // Statement type
  if (statement.type === 'ExpressionStatement') {
    statement.expression; // ExpressionStatement type
  }
});
```

I'm closing this issue! Thanks guys!
