### ISSUE TITLE
@babel/eslint-parser does not have default parserOptions (but babel-eslint did)

### ISSUE THREAD

**Issue by jharris4** [babel/babel#11902]
## Bug Report

I just tried out replacing `babel-eslint` with the `@babel/eslint-parser`, and the first thing I encountered were a few instances of the error:

```
Parsing error: ImportDeclaration should appear when the mode is ES6 and in the module context
```

After doing a little digging, I realized that I needed to set the parserOptions in my eslint config like this:

```
parserOptions: {
  "ecmaVersion": 6,
  "sourceType": "module",
  "ecmaFeatures": {
    "modules": true
  }
}
```

I'm filing this as a bug report because `babel-eslint` provides default parserOptions [here](https://github.com/babel/babel-eslint/blob/6398dac79448a9ac2c8bd3109795433f86799529/lib/index.js#L27) but the new `@babel/eslint-parser` package does not.

I'd vote that either these defaults should be used for `@babel/eslint-parser` as well, or else there should be a very prominent message in the package's README explaining that defaults are no longer provided (I bet that'd save more issues like this one being opened in the future :-) )

**Comment by jharris4** [comment]
@kaicataldo The new `@babel/eslint-parser` package works great! It lets me pass in the full babel configuration, thanks again for working on it! I'd be curious to hear your thoughts about the default parserOptions though...

**Comment by kaicataldo** [comment]
Glad to hear it's working! This might be a bug if the default parser options aren't being merged in - they're supposed to be (see [here](https://github.com/babel/babel/blob/main/eslint/babel-eslint-parser/src/configuration.js#L3))!

**Comment by jharris4** [comment]
@kaicataldo I dug into this a little bit, and I'm not sure why but something in the `eslint` CLI itself is setting the `ecmaVersion` config key to `undefined`, which is of course then overwriting the default value when `Object.assign(defaultOptions, options)` is being run.

**Comment by kaicataldo** [comment]
Thanks for doing some detective work. Will take a look today or tomorrow so we can hopefully get this fixed ASAP.

**Comment by kaicataldo** [comment]
Apologies for the delay on my end. I've verified this and located the source of the bug. Working on a PR right now.
