### ISSUE TITLE
Cannot export `declare`d functions in flow

### ISSUE THREAD

**Issue by bradzacher** [babel/babel#11913]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

- [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEHcHsCcGsGdQDMCWA7ApgKACYYMYA2AhtBqBgB4AOMALsgK5r50qRqgBGpAFAJQAuUADdIKHAG4sWEBBgJk6bHiKlyI0t2IBbYfDrR0Ac2lVa0BgG9tO0AF9pssOfoVo0GPFwESZJixsHMiQkALCYhJmNG42SKEO0kA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=flow&prettier=false&targets=&version=7.11.1&externalPlugins=)

**Input Code**

```js
declare function foo(): void;
export { foo };
```

**Expected behavior**

This should parse without an error.

**Babel Configuration**

repros just using preset flow

**Environment**
- Babel version(s): v7.11.1

**Possible Solution**

This should work fine as it's no different to either of these working cases

```js
declare export function bar(): void;

declare var bam: string;
export { bam };
```

**Comment by existentialism** [comment]
@bradzacher thanks for the report, looks like it's just missing a scope registration. I'll take a look a bit later if no one else gets to it first.

**Comment by JLHwung** [comment]
This is a known issue because declare function declarations have complicated binding behaviour, as I have noted in https://github.com/babel/babel/pull/10220.

**Comment by nicolo-ribaudo** [comment]
I think that Babel is correct here.

```js
// input.js
declare function foo(): void;
export { foo };
```

means that someone else in another file is doing something like
```js
globalThis.foo = function foo() {};
```

However, it would be invalid for `input.js` to be compiled to this:
```js
export { foo };
```

because it's not a valid ES module (the `foo` binding must be declared in that file).

**Comment by bradzacher** [comment]
I get your reasoning - but:

- If you're banning `declare function foo(): void; export { foo };`, then you should also ban the variable decl case: `declare var bam: string; export { bam };`.
  - Otherwise there is a distinct asymmetry in babel's logic.
- Why is `declare export function foo(): void` allowed? By your reasoning it should be banned.
- Most importantly: flow declaration files ofc do these practices, which is where it's used, and why it shouldn't be banned.

I don't think babel should be in the business of validating semantics this deeply

**Comment by nicolo-ribaudo** [comment]
I'm trying to fix this, and Flow's scope handling of `declare function`s seems completely random:

```js
// error
function A(): void {}
declare function A(): void;
```
```js
// ok
declare function A(): void;
function A(): void {}
```
```js
// ok
declare function A(): void;
function A(): void {}
declare function A(): void;
```
