### ISSUE TITLE
camelcase support "allow" pattern option from eslint base #186

### ISSUE THREAD

**Issue by TSMMark** [babel/babel#11910]
https://eslint.org/docs/rules/camelcase#allow

Original test cases from eslint:

https://github.com/eslint/eslint/blob/41b1e4308c1cb01c8b00cc8adc36440e77854117/tests/lib/rules/camelcase.js#L200-L215

https://github.com/eslint/eslint/blob/41b1e4308c1cb01c8b00cc8adc36440e77854117/tests/lib/rules/camelcase.js#L687-L706

Copied from babel/eslint-plugin-babel/issues/186

I don't have time right now but someone could probably use the PR I opened a year ago here babel/eslint-plugin-babel/pull/187

**Comment by kaicataldo** [comment]
We have removed the camelcase rule from the plugin since everything it checked is now supported in ESLint core. We can always add it back, but can you verify that the core rule doesn't work for your case first?
