### ISSUE TITLE
`no-invalid-regexp` not catching invalid regex

### ISSUE THREAD

**Issue by twrdjpalmer** [babel/babel#11915]
## Bug Report

**Current behavior**

In Safari 13, the following code throws a SyntaxError:

```js
new RegExp(/(?<!\?.+)(?<=\/)[\w-]+(?=[/\r\n?]|$)/)
// SyntaxError: Invalid regular expression: invalid group specifier name
```

With the default parser, setting `parserOptions.ecmaVersion: 2017` and `no-invalid-regexp: 2` correctly catches the error. With `parser: 'babel-eslint'` set, it seems to ignore the `ecmaVersion` and incorrectly asserts that the regex is valid.

Babel doesn't appear to transpile the regex, [per this repl](https://babeljs.io/repl/#?browsers=Safari%2011%0A%0A&build=&builtIns=false&spec=false&loose=false&code_lz=HYUw7gBASiDmCiAPADgCgPSoPwB4CEAOlgHQDUAlNjgLwHrkDaBYAtALqnbUPoEBOBYFjYAfACTl6QA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=), so I don't believe there should be a difference between the two parsers in this instance.

**Input Code**

```js
new RegExp(/(?<!\?.+)(?<=\/)[\w-]+(?=[/\r\n?]|$)/)
// SyntaxError: Invalid regular expression: invalid group specifier name
```

**Expected behavior**

Eslint should throw an error or warning if `no-invalid-regexp` is set to `error` or `warning`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  parser: "babel-eslint",
  env: {
    browser: true,
    jest: true,
  },
  parserOptions: {
    ecmaVersion: 2017,
  },
  rules: {
    "no-invalid-regexp": 2,
  },
}
```

**Environment**
```
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  npmPackages:
    @babel/core: ^7.1.2 => 7.10.5 
    @babel/node: ^7.2.2 => 7.10.5 
    @babel/plugin-proposal-class-properties: ^7.1.0 => 7.10.4 
    @babel/plugin-proposal-object-rest-spread: ^7.0.0 => 7.10.4 
    @babel/plugin-proposal-optional-chaining: ^7.9.0 => 7.10.4 
    @babel/plugin-syntax-dynamic-import: ^7.0.0 => 7.8.3 
    @babel/polyfill: ^7.0.0 => 7.10.4 
    @babel/preset-env: ^7.1.0 => 7.10.4 
    @babel/preset-react: ^7.0.0 => 7.10.4 
    babel-core: ^7.0.0-bridge.0 => 7.0.0-bridge.0 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-jest: ^25.1.0 => 25.5.1 
    babel-loader: ^8.0.4 => 8.1.0 
    eslint: ^7.6.0 => 7.6.0 
    jest: ^25.1.0 => 25.5.4 
```
- Monorepo: no
- How you are using Babel: Mixture

**Comment by JLHwung** [comment]
```
/(?<!\?.+)(?<=\/)[\w-]+(?=[/\r\n?]|$)/
```
is a [valid](https://regex101.com/r/8vdY49/1) JavaScript regex. However Safari 13 does not support ES2018 negative lookbehind `?<!`, thus it is thrown.

The `no-invalid-regexp` rule is an ESLint builtin rule and hosted there. In other words the regex is not parsed by Babel. I notice that https://github.com/eslint/eslint/blob/07db7b8080c2f68ee28e7d447db356c33e6fddce/lib/rules/no-invalid-regexp.js#L12 hardcoded `ecmaVersion: 2018` in regexp validator. I believe the rule should respect `parserOptions.ecmaVersions`.

@kaicataldo Can you transfer this issue to eslint?

**Comment by kaicataldo** [comment]
New issue opened [here]https://github.com/eslint/eslint/issues/13595). Closing this now. Thanks for the bug report!
