### ISSUE TITLE
Records & Tuples: records as React props

### ISSUE THREAD

**Issue by slorber** [babel/babel#11926]
Hey, reposting this records & tuples bug, as @nicolo-ribaudo asked me to do here https://github.com/tc39/proposal-record-tuple/issues/195

---

This does not work:

https://rickbutton.github.io/record-tuple-playground/#eyJjb250ZW50IjoiaW1wb3J0IFJlYWN0IGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdFwiO1xuaW1wb3J0IFJlYWN0RE9NIGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdC1kb21cIjtcblxuXG5jb25zdCBIZWxsbyA9ICh7dXNlcn0pID0+IHtcbiAgcmV0dXJuIDxwPkhlbGxvIHt1c2VyLm5hbWV9PC9wPlxufTtcblxuUmVhY3RET00ucmVuZGVyKFxuICAgIDxIZWxsbyB1c2VyPXsje25hbWU6IFwiU2ViYXN0aWVuXCJ9fS8+LFxuICAgIGRvY3VtZW50LmJvZHksXG4pO1xuXG4iLCJzeW50YXgiOiJoYXNoIiwiZG9tTW9kZSI6dHJ1ZX0=

```jsx
const Hello = ({user}) => {
  return <p>Hello {user.name}</p>
};

ReactDOM.render(
    <Hello user={#{name: "Sebastien"}}/>,
    document.body,
);
```

![image](https://user-images.githubusercontent.com/749374/89665808-8b03b400-d8d9-11ea-9b80-801b3ddf1bb9.png)

---

But this does:

https://rickbutton.github.io/record-tuple-playground/#eyJjb250ZW50IjoiaW1wb3J0IFJlYWN0IGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdFwiO1xuaW1wb3J0IFJlYWN0RE9NIGZyb20gXCJodHRwczovL2Nkbi5za3lwYWNrLmRldi9yZWFjdC1kb21cIjtcblxuXG5jb25zdCBIZWxsbyA9ICh7dXNlcn0pID0+IHtcbiAgcmV0dXJuIDxwPkhlbGxvIHt1c2VyLm5hbWV9PC9wPlxufTtcblxuY29uc3QgdXNlciA9ICN7bmFtZTogXCJTZWJhc3RpZW5cIn1cblxuUmVhY3RET00ucmVuZGVyKFxuICAgIDxIZWxsbyB1c2VyPXt1c2VyfS8+LFxuICAgIGRvY3VtZW50LmJvZHksXG4pO1xuXG4iLCJzeW50YXgiOiJoYXNoIiwiZG9tTW9kZSI6dHJ1ZX0=

```jsx
const Hello = ({user}) => {
  return <p>Hello {user.name}</p>
};

const user = #{name: "Sebastien"}

ReactDOM.render(
    <Hello user={user}/>,
    document.body,
);
```

**Comment by JLHwung** [comment]
Fixed in `@babel/parser@7.11.4`.
