### ISSUE TITLE
JSX Loader for node esm experimental loaders

### ISSUE THREAD

**Issue by jony89** [babel/babel#11934]
## Feature Request

I've been trying to use node.js new esm loader by adding `"type": "module",` in `package.json` and running script using `node --es-module-specifier-resolution=node myScript.js`

The script includes some import to React component : 

```js
import MyReactComponent from '../components/MyReactComponent';
```

Yet I get the following exception : 

>  (node:11964) ExperimentalWarning: The ESM module loader is experimental.
>  file:///D:/.../components/MyReactComponent.js:58
>              <div className="col-lg-6 col-md-12
>              ^
>  SyntaxError: Unexpected token '<'
>      at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
> 

Untill now I was able to use : 

```js
require('@babel/register')({
    presets: [
        ['@babel/env', { targets: { node: true } }],
        '@babel/react',
    ],
});
```

But now, with the new node esm loader, require does not exist and its irrelevant. How can I load JSX loader while using nodejs ES Modules ?

Node.js does say they support loaders : https://nodejs.org/api/esm.html#esm_experimental_loaders with `--experimental-loader ./loader-name.mjs`

But I could not find one for React.

**Comment by nicolo-ribaudo** [comment]
You can try using the Babel loader from https://github.com/targos/multiloader

**Comment by jony89** [comment]
@nicolo-ribaudo Thanks, but it clearly says 

> but don't use it in production

So it does not help much. though I will take a look.

**Comment by nicolo-ribaudo** [comment]
We have been discouraging using also `@babel/runtime` in production; the preferred way is to precompile your files.

**Comment by joeldenning** [comment]
I have created an ESM NodeJS loader for babel at https://github.com/node-loader/node-loader-babel.

I think the best approach would be to add a similar implementation to `@babel/node`. @nicolo-ribaudo would you be open to a pull request adding this to `@babel/node`?

**Comment by nicolo-ribaudo** [comment]
@joeldenning Thanks for creating that package! However, the Node.js loader API [is still experimental and will change in the future](https://nodejs.org/api/esm.html#esm_experimental_loaders): we will probably wait for it to became stable before providing an official solution.

**Comment by joeldenning** [comment]
Fair enough - looking forward to when they are stable 😄.

**Comment by OzzyCzech** [comment]
> I have created an ESM NodeJS loader for babel at https://github.com/node-loader/node-loader-babel.
> 
> I think the best approach would be to add a similar implementation to `@babel/node`. @nicolo-ribaudo would you be open to a pull request adding this to `@babel/node`?

that's working! thanks a lot @joeldenning

**Comment by callumgare** [comment]
I think it’s worth noting that a ES modules in Node are now, as far as I’m aware, considered stable: https://nodejs.org/api/esm.html#esm_modules_ecmascript_modules

**Comment by JLHwung** [comment]
Thanks for the note. The loader is still experimental: https://nodejs.org/api/esm.html#esm_experimental_loaders

**Comment by callumgare** [comment]
@JLHwung Ah, bummer. Looks like I misunderstood what ESM loaders meant. Back to waiting I guess.

**Comment by twelve17** [comment]
> I have created an ESM NodeJS loader for babel at https://github.com/node-loader/node-loader-babel.
> 
> I think the best approach would be to add a similar implementation to `@babel/node`. @nicolo-ribaudo would you be open to a pull request adding this to `@babel/node`?

Thanks for writing this loader @joeldenning . Would you mind giving a little info as to how to use this loader for JSX files? I noticed in https://github.com/node-loader/node-loader-babel/issues/11 that maybe the loader doesn't support JSX extensions?

**Comment by Mupli** [comment]
any news about using jsx/babel in esm module.

**Comment by jetjo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jony89** [comment]
I was ending up using `tsx` for dev and build the code for production with `@babel/env` and `@babel/preset-typescript`

**Comment by Mupli** [comment]
Hi @jony89. Thanks for sharing your solution.  Though for me is out of the option. I would need to rewrite code to tsx/ts.

**Comment by rdsedmundo** [comment]
I suppose there is a lot of people subscribed to this issue like me, since it has been linked from others too as the master issue tracking this feature, thus it should be kept open because we are waiting for Babel's support on this and not another tool. @jony89 can you please reopen this? Or @nicolo-ribaudo

**Comment by Mupli** [comment]
I have some success with this one. Maybe it will be useful for someone else. 

package.json 
```json
{
type:"module",
"scripts": {
       "build": "babel app --out-dir _app",
        "start": "npm run build && node _app/app.js",
}}
```

**dir**
/app - contains code for REACT in my case /app/react/App.js etc. .  
**/_app**  babel  generated dode 
/_app/app.js - starting code express etc. (using SSR with renderToString)


**babel.config.js** - DO NOT ADD  @babel/env - because it will change all imports to require and **type=module** will not work with generated code "_app/.."
 
```js
export default (api) => {
    // api.cache(true);
    return {
        ignore: ["**/public/**"],
        presets: [ ["@babel/preset-react", { 
            "runtime": "automatic"
         }]],
       
    };
};
```
