### ISSUE TITLE
arrow function is not transpiled to es5 when used inside a parameter of a function decrator

### ISSUE THREAD

**Issue by Aaike** [babel/babel#1194]
the decorator get transpiled like this : `decorators: [foo((thisObj, args) => thisObj.foo)],`

https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&playground=true&code=class%20Test%20{%0A%20%20constructor%28%29%20{}%0A%20%20%0A%20%20%40foo%28%28thisObj%2C%20args%29%20%3D%3E%20thisObj.foo%29%0A%20%20bar%28%29{%0A%20%20%20%20%0A%20%20}%0A}

**Comment by sebmck** [comment]
Update Babel.

**Comment by Aaike** [comment]
i've updated now to `5.0.10` , but the problem still remains.

**Comment by sebmck** [comment]
Are you sure? Works for me:

**script.js**

```javascript
class Test {
  constructor() {}

  @foo((thisObj, args) => thisObj.foo)
  bar(){

  }
}
```

```
$ babel --stage 0 script.js
"use strict";

var Test = (function () {
  function Test() {
    _classCallCheck(this, Test);
  }

  _createDecoratedClass(Test, [{
    key: "bar",
    decorators: [foo(function (thisObj, args) {
      return thisObj.foo;
    })],
    value: function bar() {}
  }]);

  return Test;
})();
```

**Comment by Aaike** [comment]
omg , i've updates jspm babel , npm babel , but not gulp-babel, the one i needed ... sorry about that :)
