### ISSUE TITLE
wrong result of `this` replacement for `JSXIdentifier` in class function properties

### ISSUE THREAD

**Issue by xc2** [babel/babel#11949]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

- [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEASCmIQHtrwB4Bd4DsAmMAwsgLYAOyOum0A3gFDTQDuyATiHtALzQAUASh4A-aAB5MACwCWEAHQB1dp2hlutKbLkA3AL7QA9MPq6gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=&version=7.11.1&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.10.4%2C%40babel%2Fplugin-syntax-jsx%407.10.4%2C%40babel%2Fplugin-transform-classes%407.10.4)

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  plugins: [
    ["@babel/proposal-class-properties"],
    ["@babel/transform-classes"],
    ["@babel/plugin-syntax-jsx"]
  ]
}
```

**Input Code**

```js
class Hello extends Component {
  world = () => <this.World p={this.v} />
}
```

**Output Code**

```js
//...
var Hello = /*#__PURE__*/function (_Component) {
  "use strict";

  _inherits(Hello, _Component);

  var _super = _createSuper(Hello);

  function Hello() {
    var _this2 = this;

    var _this;

    _classCallCheck(this, Hello);

    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    _this = _super.call.apply(_super, [this].concat(args));

    _defineProperty(_assertThisInitialized(_this), "world", function () {
      return <_this2.World p={_this.v} />;
    });

    return _this;
  }

  return Hello;
}(Component);
//...
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

```js
//...
var Hello = /*#__PURE__*/function (_Component) {
  "use strict";

  _inherits(Hello, _Component);

  var _super = _createSuper(Hello);

  function Hello() {
    var _this;

    _classCallCheck(this, Hello);

    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    _this = _super.call.apply(_super, [this].concat(args));

    _defineProperty(_assertThisInitialized(_this), "world", function () {
      return <_this.World p={_this.v} />;
    });

    return _this;
  }

  return Hello;
}(Component);
//...
```

**Environment**

```
  System:
    OS: macOS 11.0
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  npmPackages:
    @babel/core: 7.11.1 => 7.11.1
    @babel/plugin-proposal-class-properties: 7.10.4 => 7.10.4
    @babel/plugin-syntax-jsx: 7.10.4 => 7.10.4
    @babel/plugin-transform-classes: 7.10.4 => 7.10.4
```

**Possible Solution**

This patch won't be correct, but work for the snippet above:

```patch
--- transformClass.js	2020-08-11 21:49:04.000000000 +0800
+++ transformClass.patch.js	2020-08-11 21:55:10.000000000 +0800
@@ -54,6 +54,7 @@
     staticPropBody: [],
     body: [],
     superThises: [],
+    jsxSuperThises: [],
     pushedConstructor: false,
     pushedInherits: false,
     protoAlias: null,
@@ -75,6 +76,9 @@
       ThisExpression(path) {
         classState.superThises.push(path);
       },
+      JSXIdentifier(path) {
+        if (path.node.name === 'this') classState.jsxSuperThises.push(path);
+      },
     },
   ]);
 
@@ -339,6 +343,15 @@
       );
     }
 
+    for (const thisPath of classState.jsxSuperThises) {
+      const { node, parentPath } = thisPath;
+      if (parentPath.isJSXMemberExpression({ object: node })) {
+        const ref = thisRef();
+        ref.type = "JSXIdentifier";
+        thisPath.replaceWith(thisRef());
+      }
+    }
+
     const bareSupers = new Set();
     path.traverse(
       traverse.visitors.merge([
```

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by existentialism** [comment]
@xc2 thanks for the issue, but I believe this has already been reported: https://github.com/babel/babel/issues/11806

**Comment by jridgewell** [comment]
Hi @xc2, I think your proposed solution is actually correct. Would you like to open a PR with it?

**Comment by xc2** [comment]
> @xc2 thanks for the issue, but I believe this has already been reported: #11806

Oh, it's the same problem. I'll close this one.

> Hi @xc2, I think your proposed solution is actually correct. Would you like to open a PR with it?

Glad to hear it helps. I'm sorry I won't open a PR due to not knowing much about babel. 

---

Looking forward it will be fixed soon.

**Comment by JLHwung** [comment]
Duplicate of #11806.
