### ISSUE TITLE
Arrow function not getting transpiled inside node_modules

### ISSUE THREAD

**Issue by brvenkat** [babel/babel#11954]
## Bug Report

**Current behavior**
I am using a 3rd party library called joi-date as follows
const joiDate = require('@hapi/joi-date');

The issue is The arrow function used in @hapi/joi-date is not getting transpiled in IE11 due to which my app does not work in IE11. i attached the screenshot below. I am using babel7 and webpack4

**Input Code**

```js
Here is my webpack config
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!.*hapi\/joi-date)/,
        loader: 'babel-loader',
      },
Tried using function version as well but did not help
        exclude: function(modulePath) {
          return /node_modules/.test(modulePath) &&
              !/node_modules\/@hapi\/joi-date/.test(modulePath);
        },


```

**Expected behavior**
Babel-loader should convert the arrow function into es2015 style function

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: .babelrc

```js
{
.babelrc entries
{
  "presets": [
    "@babel/env",
    "@babel/react",
    "@babel/preset-flow"
  ],
  "env": {
    "development": {
      "plugins": [
        "react-hot-loader/babel"
      ]
    }
  },
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 2,
        "helpers": false,
        "regenerator": true
      }
    ],
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-optional-chaining",
    [
      "@babel/plugin-proposal-pipeline-operator",
      {
        "proposal": "minimal"
      }
    ],
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-do-expressions",
    "@babel/plugin-proposal-function-bind"
  ]
}
}
```

**Environment**

```

```
- Babel version(s): 7.0.0
- Node/npm version: 12.16.3
- OS: OSX 10.13.4
- Monorepo:No
- How you are using Babel: loader

**Additional context**
<img width="1340" alt="Screen Shot 2020-08-11 at 1 08 22 pm" src="https://user-images.githubusercontent.com/11412050/89853093-d10b9100-dbd3-11ea-9f05-07cc79150f29.png">

**Comment by existentialism** [comment]
@brvenkat check out the section in our docs that describes diff config file types and their use cases:

https://babeljs.io/docs/en/configuration#whats-your-use-case

(You'll want to switch to a `babel.config.json` file)

**Comment by brvenkat** [comment]
thanks @existentialism , i created a babel.config.json and copied the contents of .babelrc into it, but does not help. i am getting the same issue with the arrow function not being converted in IE11. Tried removing `exclude node_modules` too and it too did not work

**Comment by existentialism** [comment]
@brvenkat can you create a small repo that reproduces the problem?

**Comment by brvenkat** [comment]
thanks @existentialism created a small repo https://github.com/brvenkat/sample-joi
This small app runs fine until i add the `@hapi/joi-date` dependency at which point it starts failing

**Comment by existentialism** [comment]
Your regex needs to also include `@hapi/joi`.

**Comment by brvenkat** [comment]
thanks @existentialism tried that too and did not work, tried to be as explicit as below . I have not checked in change as it does not work
`
      {
        test: /\.js$/,
        exclude: [
          /node_modules\/(?!.*hapi\/joi)/,
          /node_modules\/(?!.*hapi\/joi-date)/
        ],
        include: [
          path.resolve(__dirname, '..', 'src'),
          path.resolve(__dirname, '..', 'node_modules/@hapi/joi'),
          path.resolve(__dirname, '..', 'node_modules/@hapi/joi-date')
        ],
        loader: 'babel-loader',
      },
`

**Comment by AjayPoshak** [comment]
@brvenkat If you change your `node_modules` exclusion regex to `exclude: [/node_modules\/(?!(@hapi\/joi-date|@hapi\/joi)\/).*/],` then it would start transpiling your node_modules except `@hapi/joi` and `@hapi/joi-date`.

**Comment by JLHwung** [comment]
If you are running webpack on IE 11, see also https://github.com/babel/babel-loader/pull/883/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R101 for how to include `@hapi/joi-date` but exclude all the other node_modules.
