### ISSUE TITLE
Сoncat window.location.protocol + window.location.host

### ISSUE THREAD

**Issue by mihrich** [babel/babel#11957]
## Сoncat window.location.protocol + window.location.host

**Current behavior**
One extra ":" character when merging protocol name and hostname. I tested it in Chrome version 84.0.4147.125
**Input Code**

```js
let site = window.location.protocol + '//' + window.location.host;
```
OR

```js
let site = `${window.location.protocol}//${window.location.host}`;
```
babel transform as 

```js
var site = "".concat(window.location.protocol, "://").concat(window.location.host);
```
that out  **https:://site.com** when **:** is excess
```
- "@babel/cli": "^7.8.4"
- "@babel/core": "^7.9.0"
- "@babel/plugin-proposal-class-properties": "^7.8.3"
- "@babel/plugin-proposal-decorators": "^7.10.1"
- "@babel/preset-env": "^7.9.5"
- "babel-loader": "^8.1.0"

**Comment by JLHwung** [comment]
I can not reproduce this issue on [REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=DYUwLgBAzglmIQLwQAYBIDeB3GA7AJgPZYB0whAxgIZgyG4kAOAToWJYcAL4D0PmOAsTKUadBgAtCUMFxQBuIA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cstage-0%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=), please share a reproduction repo. However, I believe it is highly unlikely a babel bug as we don't do magic like adding `:` to `//` on string literals, I am gonna close it and feel free to reopen if you can come up with a reproducing repo.
