### ISSUE TITLE
@babel/preset-typescript "Binding invalid left-hand side in function parameter list"

### ISSUE THREAD

**Issue by funn1est** [babel/babel#11959]
## Bug Report

**Current behavior**
the arrow function return wrapped by bracket should work. Component `FC` and `FC1` works, but `FC2` got parse error. Without typescript preset works too.

- [reproduce REPL](https://babeljs.io/repl#?browsers=ie%209&build=&builtIns=usage&spec=false&loose=false&code_lz=MYewdgzgLgBARiEAbGBeGUBOBXApgbgChDRJYAxAYTRgAoBKNAPhgG9CYZNcptMwYAHkogAtgAcY4zCHERUrAJZRco5nUEATRQDcmARkOCA9Nr30AvjGNMiFoiXDQYVfTQbr2nbr350OnEIiEgGBUjJyCqFh8IhI0TEwAPwwyqrqWroGRqZZCTEAXKkqaqgstJl6AEw1JmZM9PkW0TYB9HYOpM5UVe6MZWwBPnwCtNHCYuL50rLyXomxyPlhKWml5ZXZ-nVZjQuBRWvqFfU1VTvmTS1MbR2EQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=)

**Input Code**

```jsx
const bool = true;

const FC = () => {
  return <Comp props={item => (<div>111</div>)} />;
};

const FC1 = () => {
  return (
    <Comp
      props={
        bool
          ? item => <div>111</div>
          : item => (<div>222</div>)
      }
    />
  );
};

const FC2 = () => {
  return (
    <Comp
      props={
        bool
          ? item => (<div>111</div>)
          : item => (<div>222</div>)
      }
    />
  );
};
```

**Expected behavior**
`FC2` works

**Comment by JLHwung** [comment]
Related: #11038

**Comment by brodybits** [comment]
I encountered a simpler reproduction in Prettier & prettierX: [this REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAlgxiMCcQEMC2EC8AoCEDuAFspBhhAEQwD2AdiOTrhAPwQAOmAfBABQCEfDqwAGBEEgDkAZwgBPKgFcEEACQBvNgF8I1OsIgAuCMIBWCqZDBiIIVGzCydtEBABmVZfIXCAlI1xGHBjcouIg0nKKyupaqmqExJrCANxYQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.14.4&externalPlugins=)

**Input code:**

```js
let icecream =
  what == "cone"
    ? p => (!!p ? `here's your ${p} cone` : `just the empty cone for you`)
    : p => `here's your ${p} ${what}`;
```

Discovered here: https://github.com/brodybits/prettierx/pull/549

/cc @adalinesimonian
