### ISSUE TITLE
SyntaxError: Support for the experimental syntax 'jsx' isn't currently enabled (12:17)

### ISSUE THREAD

**Issue by iamKushagra** [babel/babel#11966]
## Bug Report

- [ ] I would like to work on a fix!
`{
  "name": "mern-ecommerce",
  "version": "1.0.0",
  "description": "MERN Ecommerce",
  "main": "server/index.js",
  "scripts": {
    "build": "npm run build:clean && cross-env NODE_ENV=production webpack --progress --colors",
    "build:clean": "rimraf ./dist",
    "start": "cross-env NODE_ENV=development nodemon server",
    "start:production": "cross-env NODE_ENV=production node server",
    "production": "npm run build",
    "postinstall": "npm run build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "node",
    "express",
    "mongoose",
    "react",
    "redux",
    "redux-thunk",
    "webpack"
  ],
  "author": "Kushagra",
  "license": "MIT",

  "dependencies": {
    "axios": "^0.19.0",
    "babel": "^7.0.0",
    "bcryptjs": "^2.4.3",
    "bootstrap": "^4.3.1",
    "compression": "^1.7.4",
    "connect-history-api-fallback": "^1.6.0",
    "connected-react-router": "^6.4.0",
    "cors": "^2.8.5",
    "crypto": "^1.0.1",
    "dotenv": "^8.0.0",
    "express": "^4.17.1",
    "font-awesome": "^4.7.0",
    "history": "^4.9.0",
    "jsonwebtoken": "^8.5.1",
    "mailchimp-api-v3": "^1.14.0",
    "mailgun-js": "^0.22.0",
    "mongoose": "^5.5.11",
    "mongoose-slug-generator": "^1.0.4",
    "passport": "^0.4.0",
    "passport-facebook": "^3.0.0",
    "passport-google-oauth2": "^0.2.0",
    "passport-jwt": "^4.0.0",
    "react": "^16.8.6",
    "react-bootstrap-table-next": "^3.1.5",
    "react-bootstrap-table2-toolkit": "^2.0.1",
    "react-cookies": "^0.1.1",
    "react-dom": "^16.8.6",
    "react-notification-system-redux": "^2.0.0",
    "react-redux": "^7.0.3",
    "react-router-dom": "^5.0.1",
    "react-select": "^3.0.4",
    "reactstrap": "^8.0.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "simple-line-icons": "^2.4.1",
    "validatorjs": "^3.18.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.5",
    "@babel/core": "^7.11.1",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/polyfill": "^7.4.4",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "autoprefixer": "^9.6.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^7.1.5",
    "chalk": "^2.4.2",
    "copy-webpack-plugin": "^5.0.3",
    "cross-env": "^5.2.0",
    "css-loader": "^2.1.1",
    "cssnano": "^4.1.10",
    "dotenv-webpack": "^1.8.0",
    "file-loader": "^4.0.0",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.7.0",
    "node-sass": "^4.12.0",
    "nodemon": "^1.19.1",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss-loader": "^3.0.0",
    "rimraf": "^2.6.3",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "terser-webpack-plugin": "^1.3.0",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.2",
    "webpack-dev-middleware": "^3.7.0",
    "webpack-dev-server": "^3.5.1",
    "webpack-hot-middleware": "^2.25.0",
    "webpack-merge": "^4.2.1",
    "webpack-pwa-manifest": "^4.0.0"
  }
}
`

my webconfig file
`const common = require('./config/webpack/webpack.common');
const webpackMerge = require('webpack-merge');

let envConfig;
switch (process.env.NODE_ENV) {
  case 'prod':
  case 'production':
    envConfig = require('./config/webpack/webpack.prod');
    break;

  case 'dev':
  case 'development':
  default:
    envConfig = require('./config/webpack/webpack.dev');
}

module.exports = webpackMerge(common, envConfig);
`

my babelrc
`{
  "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
  ],
  "plugins": [
      [
        "@babel/plugin-proposal-class-properties"
      ]
  ]
}
`
![2020-08-15 (1)](https://user-images.githubusercontent.com/16055492/90315938-fe8e6c80-df3c-11ea-92aa-8cffccae9f96.png)

**Current behavior**
A clear and concise description of the behavior.

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by JLHwung** [comment]
Can you upgrade `@babel/core` to 7.11 and attach the output of
```
BABEL_SHOW_CONFIG_FOR=./client/app/index.js npm start
```

It should print the effective babel config of `./client/app/index.js`.

**Comment by iamKushagra** [comment]
OK I WILL
