### ISSUE TITLE
Typescript code does not update with --watch flag

### ISSUE THREAD

**Issue by techno021** [babel/babel#11965]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
The --watch flag has no effect, typescript code does not update

**Input Code**

```ts
enum Role { ADMIN, READ_ONLY, AUTHOR }

const person = {
  name: 'Rishab',
  age: 13,
  hobbies: ['Coding', 'Astronomy', 'Gaming'],
  role: Role[0]
};

console.log(person);
```

**Expected behavior**
The --watch flag should detect code changes and recompile my typescript file.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}
```
```bash
babel ./src/app.ts --extensions \".ts\" --out-file=build/app.js --watch
```

**Environment**
```bash
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.7.0/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  npmPackages:
    @babel/cli: ^7.10.5 => 7.10.5
    @babel/core: ^7.11.1 => 7.11.1
    @babel/preset-env: ^7.11.0 => 7.11.0
    @babel/preset-react: ^7.10.4 => 7.10.4
    @babel/preset-typescript: ^7.10.4 => 7.10.4
    babel-core: ^7.0.0-bridge.0 => 7.0.0-bridge.0
    eslint: ^7.6.0 => 7.6.0
```
Just to let you know I'm using WSL with the Ubuntu Distro
**Possible Solution**
I haven't checked babel's code so no idea, sorry
**Additional context**
[A github repo of my code](https://github.com/techno021/babel-typescript)

**Comment by existentialism** [comment]
@techno021 your repo works for me on macOS. I don't have a machine to test WSL on, maybe @hzoo can take a look?

**Comment by techno021** [comment]
@existentialism does the --watch flag do what is expected?

**Comment by existentialism** [comment]
Yes

**Comment by techno021** [comment]
@existentialism It got fixed after moving from C:/Users/(my_user)/Documents/Projects too /home/(my_wsl_user)/Projects
