### ISSUE TITLE
Babel + typescript does not transpile when combined with dynamic property keys

### ISSUE THREAD

**Issue by joshjee** [babel/babel#11967]
## Bug Report

**Current behavior**
When using dynamic property keys on an object, babel fails to transpile other ES6 features into ES5 friendly code. In my current example, babel failed to transpile an arrow function and object destructuring. This phenomenon only occurs when using typescript. I tried this with vanilla javascript, and it faced no issues.

**Input Code**

```js
  const key: 'key' = 'key';
  const { [key]: value } = [
    { key: 'value1' },
    { key: 'value2' }
  ].find(({ key }) => key === 'value1');
```

**Output Code**
```js
var n = [{ key: "value1" }, { key: "value2" }].find(({ key: e }) => "value1" === e).key;
```

**Expected Output Code**
```js
var n = [{ key: "value1" }, { key: "value2" }].find((function (e) { return "value1" === e.key })).key;
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}
```

**Environment**
```
 System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.11.1 => 7.11.1 
    @babel/preset-env: ^7.11.0 => 7.11.0 
    @babel/preset-typescript: ^7.10.4 => 7.10.4 
    babel-loader: ^8.1.0 => 8.1.0 
    webpack: ^4.44.1 => 4.44.1 
```

**Comment by techno021** [comment]
Hey @joshjee see #11965, hope it helps

**Comment by joshjee** [comment]
> Hey @joshjee see #11965, hope it helps

I am currently using webpack and `babel-loader` to transpile my code. Is it possible to insert in the `watch` flag in the `.babelrc` file? This doesn't seem to work. 

.babelrc file
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ],
  "watch": true
}
```

**Comment by techno021** [comment]
@joshjee its not possible, you have to use the --watch flag

**Comment by liuxingbaoyu** [comment]
I can't reopen this, it may have been fixed already, feel free to reopen if the problem persists.
