### ISSUE TITLE
@babel/eslint-parser @babel/eslint-plugin does not play nice with eslint-plugin-import

### ISSUE THREAD

**Issue by TrejGun** [babel/babel#11975]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
@babel/eslint-parser throws error on parsing 3rd party libraries

**Input Code**

```js
import moment from "moment";


export default moment();
```

throws error 

```
ESLint: Parse errors in imported module 'moment': No Babel config file detected for ~/node_modules/moment/src/moment.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files. (undefined:undefined)(import/namespace)
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```json
{
  "extends": ["standard", "eslint:recommended", "plugin:import/errors", "plugin:import/warnings"],
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "ecmaVersion": 9,
    "sourceType": "module"
  },
  "plugins": ["standard", "@babel/eslint-plugin", "import"],
  "rules": {
    "new-cap": "off",
    "@babel/new-cap": "error",

    "no-invalid-this": "off",
    "@babel/no-invalid-this": "error",

    "no-unused-expressions": "off",
    "@babel/no-unused-expressions": "error",

    "object-curly-spacing": "off",
    "@babel/object-curly-spacing": "error",

    "semi": "off",
    "@babel/semi": ["error", "always"]
  }
}
```

```json
{
  "presets": [
    [
      "@babel/env"
    ]
  ]
}
```

**Environment**
```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.8.0 - /opt/local/bin/node
    npm: 6.14.7 - /opt/local/bin/npm
```
```
    "@babel/cli": "7.10.5",
    "@babel/core": "7.11.1",
    "@babel/eslint-parser": "7.11.3",
    "@babel/eslint-plugin": "7.11.3",
    "@babel/preset-env": "7.11.0",
    "eslint": "7.7.0",
    "eslint-config-prettier": "6.11.0",
    "eslint-config-standard": "14.1.1",
    "eslint-plugin-import": "2.22.0",
    "eslint-plugin-jest": "23.20.0",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-prettier": "3.1.4",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-standard": "4.0.1",
```

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by kaicataldo** [comment]
It looks like this occurs because `eslint-plugin-import` uses the configured parser to parse imported modules (see https://github.com/benmosher/eslint-plugin-import/blob/master/utils/parse.js), and since the module in question in this issue is in `node_modules`, Babel doesn't have a config for it.

I'm not sure what the best path forward is here. In the interim, you might be able to use `parserOptions.babelOptions` in your ESLint config to explicitly configure Babel for `node_modules/**/*.js` files so that it has a configuration at the time of linting, but not compilation time.

**Comment by kaicataldo** [comment]
Digging into this a bit more, have you tried the [`import/parsers`]([https://github.com/benmosher/eslint-plugin-import#importparsers]) option yet? I believe setting it to the default ESLint parser (`espree`) should handle the majority of use cases.

**Comment by kaicataldo** [comment]
If that doesn't work, I think this might have to be fixed on the `eslint-plugin-import` side, and I'm certainly happy to figure out a solution and implement it.

**Comment by TrejGun** [comment]
Thanks for your answer. Indeed this config works
```
  "settings": {
    "import/parsers": {
      "espree": [
        ".js",
        ".jsx"
      ]
    }
  }
```
I dont know where is the problem, and who should fix it. It might happen `eslint-plugin-import` is integrated into `eslint` itself because node 14 is supporting modules out of the box
This issue was created for reference for anybody who has the same problem or/and want to fix it

**Comment by camiblanch** [comment]
I am having this same issue with errors being thrown in relation to the `moment` package. Adding
```	
"parserOptions": {
	"requireConfigFile": false,
},
```

does not seem to do anything as well as adding the `espree` settings as stated above. Any ideas on what I can try?

**Comment by minocoko** [comment]
from my side
babel.config.js not works
bug .babelrc works

**Comment by Ignalion** [comment]
You can add `"babel": {}` to your package.json file. It seems to work well

**Comment by Shemchuk** [comment]
In my case it was solved with adding sections "parserOptions" and "babelOptions" to .eslintrc:
`	"parser": "@babel/eslint-parser",
	"parserOptions": {
		"requireConfigFile" : "false"
	},
	"babelOptions": {
		"configFile": "./.babelrc",
	},`

**Comment by TrejGun** [comment]
I changed my mind, addign import/parser -> espree introduces new problems

**Comment by texonidas** [comment]
> In my case it was solved with adding sections "parserOptions" and "babelOptions" to .eslintrc:
> `"parser": "@babel/eslint-parser", "parserOptions": { "requireConfigFile" : "false" }, "babelOptions": { "configFile": "./.babelrc", },`

For anyone else who lands here and gets an unexpected top-level property error, babelOptions for in parserOptions, not at the root
