### ISSUE TITLE
Provide bridge version for `babel-eslint` to `@babel/eslint-parser`

### ISSUE THREAD

**Issue by ylemkimon** [babel/babel#11989]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**
`babel-eslint` is now `@babel/eslint-parser` and has moved into the Babel monorepo. This causes similar problem when Babel 7 moved to scoped package: packages declaring `babel-eslint` as a peer dependency cannot move to `@babel/eslint-parser` without breaking change.

**Describe the solution you'd like**
Similar to https://github.com/babel/babel-bridge, publish `babel-eslint@11.0.0-bridge.0` with `module.exports = require("@babel/eslint-parser");`.

**Describe alternatives you've considered**.
Use `peerDependenciesMeta` to declare both packages optional. However, this cannot enforce peer dependency.

**Documentation, Adoption, Migration Strategy**
Adapted from https://github.com/babel/babel-bridge#solution:

To address this, we're releasing this bridge package, to allow users to do

```js
peerDependencies: {
  "babel-eslint": "10.x || ^11.0.0-bridge.0"
}
```

then where users of this package would originally have done

```sh
npm i eslint babel-eslint
```

to install `babel-eslint`, they could now do

```sh
npm i eslint babel-eslint@^11.0.0-bridge.0 @babel/eslint-parser
```

to install the bridge package and install `@babel/eslint-parser`.

**Comment by kaicataldo** [comment]
The hard break was intentional here because we've changed how the parser works and there are significant breaking changes. I'm in favor of making things fail faster in this case so that people are aware of the changes if/when they upgrade.
