### ISSUE TITLE
Octal literal confused with control code?

### ISSUE THREAD

**Issue by bucaran** [babel/babel#1198]
```
/Users/b/dev/<PROJECT NAME>/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: src/index.js: Octal literal in strict mode (4:31)
  2 | 
  3 | function clear() {
> 4 |   return process.stdout.write("\033c");
    |                                ^
  5 | }
```

I was able to write the `clear` function like this, but would like what's wrong with the above too.

```js
function clear() {
  return process.stdout.write('\u001B[2J\u001B[0;0f');
}
```

**Comment by sebmck** [comment]
cc @RReverser

**Comment by RReverser** [comment]
Nope, things like `'\033'` are (were) treated as octal literal escapes, so it was equal to `String.fromCharCode(033)`. In ES6, this is disallowed and you should use hex-based escapes instead (either in `\u1234` or `\u{12345...}` format).

**Comment by sebmck** [comment]
Thanks @RReverser!

**Comment by knownasilya** [comment]
Would \033 be \x21 ?
