### ISSUE TITLE
referenced static property in class instance throws ReferenceError

### ISSUE THREAD

**Issue by dnalborczyk** [babel/babel#11990]
## Bug Report

**Current behavior**

the below code throws **ReferenceError: B is not defined**. 

It works natively in **node.js (latest/14.8.0)** as well as **TypeScript (latest/4.0)**

**Input Code**

```cli
npx babel-node a.js
```

```js
// b.js
exports.b = new (class B {
  static a = 0

  static b = B.a

  getB() {
    return B.b
  }
})()
```

```js
// a.js
const { b } = require('./b.js')

console.log(b.getB())

// ReferenceError: B is not defined
```

**Workaround**
```js
// b.js
class B {
  static a = 0

  static b = B.a

  getB() {
    return B.b
  }
}

exports.b = new B()
```

**Expected behavior**

should not throw an error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
'@babel/plugin-transform-typescript', {
    allowDeclareFields: true,
},
'@babel/plugin-proposal-class-properties',
```

- Babel version(s): 
    "@babel/cli": "7.10.5",
    "@babel/core": "7.11.4",
    "@babel/node": "7.10.5",
    "@babel/plugin-proposal-class-properties": "7.10.4",
    "@babel/plugin-transform-typescript": "7.11.0",

- Node/npm version: 14.8.0
- OS: macOS 10.15.6

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/13429
