### ISSUE TITLE
@babel/proposal-class-properties is not compatible with Windows OS

### ISSUE THREAD

**Issue by dharmsingh2120** [babel/babel#11999]
I am getting following error
ReferenceError: Unknown plugin "@babel/proposal-class-properties"

Can someone help on this.
Following is log and babel configuration.
[2020-08-24T11_00_51_726Z-debug.log](https://github.com/babel/babel/files/5117534/2020-08-24T11_00_51_726Z-debug.log)

## Bug Report

- [ ] I would like to work on a fix!

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": true
        }
      }
    ],
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    "transform-async-generator-functions",
    "@babel/transform-async-to-generator"
  ]
}
```

**Environment**

```

```
- Babel version(s): {
    "@babel/cli": "^7.10.5",
    "@babel/core": "^7.8.3",
    "@babel/node": "^7.10.5",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/plugin-proposal-numeric-separator": "^7.8.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.8.3",
    "@babel/plugin-transform-async-to-generator": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@babel/preset-react": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",
    "@babel/register": "^7.10.5",
}
- Node/npm version: [Node 12.16.1/npm 6.13.4]
- OS: [Windows 10]
- How you are using Babel: [`cli`, `register`, `loader`]

**Additional context**
![2020-08-24_17-15-09](https://user-images.githubusercontent.com/59353019/91041304-6aec2880-e62d-11ea-9cdc-db6ffa7d172c.png)

**Comment by AjayPoshak** [comment]
I believe you need to specify full name of plugin in .babelrc
```js
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": true
        }
      }
    ],
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-transform-async-to-generator"
  ]
}

```

**Comment by existentialism** [comment]
@dharmsingh2120 closing this for now, feel free to comment if you're still having issues
