### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by 007tom** [babel/babel#12018]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

> Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.

**Input Code**
import my own local npm package into a create-react-app project
```js
const MyComponent = () => {
  return (
    <div>
      <button type="button">Click me</button>
      <p>Hello</p>
    </div>
  )
}
```

**Expected behavior**
expect to work successfully!!

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `package.json`

```json
{
  ...,
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/plugin-transform-react-jsx": "^7.10.4",
    "@babel/plugin-transform-react-jsx-self": "^7.10.4",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "babel-loader": "^8.1.0",
    "css-loader": "^4.2.2",
    "reactstrap": "^8.5.1",
    "style-loader": "^1.2.1",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
  "babel": {
    "presets": [
      "@babel/preset-react",
      "@babel/preset-env"
    ],
    "plugins": [
      "@babel/plugin-transform-react-jsx"
    ]
  }
}
```

**Environment**

```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.11.4 => 7.11.4 
    @babel/plugin-transform-react-jsx: ^7.10.4 => 7.10.4 
    @babel/plugin-transform-react-jsx-self: ^7.10.4 => 7.10.4 
    @babel/preset-env: ^7.11.0 => 7.11.0 
    @babel/preset-react: ^7.10.4 => 7.10.4 
    babel-loader: ^8.1.0 => 8.1.0 
    webpack: ^4.44.1 => 4.44.1 

```
- Babel version(s): [6.18.0 (babel-core 6.18.2)]
- Node/npm version: [Node 14.5.0/npm 6.14.7]
- OS: [macOS Catalina 10.15.6]
- Monorepo: [no]
- How you are using Babel: [`package.json`, using `.babelrc` still not working]

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable
<img width="1240" alt="截屏2020-08-28 下午3 01 29" src="https://user-images.githubusercontent.com/31362988/91531457-67171980-e93f-11ea-9d72-fc98caa1e882.png">

**Comment by nicolo-ribaudo** [comment]
What is your webpack config?

**Comment by 007tom** [comment]
@nicolo-ribaudo 
the **same** problem occurs

`babel.config.json`

```json
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": ["@babel/plugin-transform-react-jsx"]
}
````

- package-directory > `yarn build`
- create-react-app-project-directory > `yarn add package-directory`
- create-react-app-project-directory > `yarn start` _the same error message..._

**Comment by 007tom** [comment]
my `webpack.config.js`:
```js
const path = require("path");

module.exports = {
	mode: "production",
	entry: "./index.js", // that's no problem
	output: {
		path: path.resolve("build"),
		filename: "index.js",
		libraryTarget: "commonjs2"
	},
	module: {
		rules: [
			{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" },
			{
				test: /\.css$/,
				loader: "style-loader!css-loader"
			}
		]
	},
	externals: {
		react: "react"
	}
};
```

**Comment by AjayPoshak** [comment]
@007tom You should not exclude `node_modules` in babel-loader, if you want to transpile node_modules.

**Comment by 007tom** [comment]
@AjayPoshak I have tried it, but no effect.
```shell
.
├── my-own-npm-package    // 1
└── package-used-project // 2
```
`1` contains `bable.config.json` and `webpack.config.js`, while `2` is a create-react-app, no addtional babel and webpack configurations

First, I build `my-own-npm-package` and then `yarn add` to `package-used-project`, the problem still exits

**Comment by JLHwung** [comment]
Can you post the package.json of your own component library? In the main field, it should be something like 
`main: build/index.js`. Otherwise Webpack will resolve to the untranspiled JSX source.

**Comment by 007tom** [comment]
`package.json`: 

```js
{
  "name": "draft-js-simple-table",
  "version": "1.0.0",
  "description": "",
  "main": "index.js", // it's in root directory
  "scripts": {
    "build": "webpack"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/plugin-transform-react-jsx": "^7.10.4",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "babel-loader": "^8.1.0",
    "css-loader": "^4.2.2",
    "style-loader": "^1.2.1",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
  "dependencies": {
    "bootstrap": "^4.5.2",
    "draft-js": "^0.11.7",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "reactstrap": "^8.5.1"
  }
}

```

**Comment by JLHwung** [comment]
```diff
--- "main": "index.js"
+++ "main": "./build/index.js"
```
Otherwise Webpack will resolve to the untranspiled JSX source.

**Comment by 007tom** [comment]
fixed, thank you @JLHwung

**Comment by dueka** [comment]
@007tom how were you able to fix this issue?

**Comment by 007tom** [comment]
It seems that someone reply new comment.
I found it in my mailbox

**Comment by JLHwung** [comment]
@007tom I don't see new replies here. I can lock this thread if you see spam comments.
