### ISSUE TITLE
Replace Object.assign with the provided polyfill

### ISSUE THREAD

**Issue by JedWatson** [babel/babel#1201]
I've got a simple React component that I want to have as few dependencies as possible, which needs to make use of Object.assign but should work in browsers without native support for that function.

The simple solution is to include a lightweight package like `xtend` or `object-assign` but I've noticed that Babel automatically adds in its own one-line polyfill as `_extends` at the top of any file that requires it (e.g. when you use `{...spread}` in JSX)

So I was wondering if it would be possible to re-use the polyfill from within my own code rather than including two of them. Since the polyfill uses `Object.assign` if it exists, it seems nondestructive to replace any `Object.assign` calls with `_extends` in the transpiled code.

**Comment by sebmck** [comment]
You could do it as a plugin:

**node_modules/babel-plugin-object-assign**

```javascript
var Transformer = require("babel-core").Transformer;
var t = require("babel-core").types;

module.exports = new Transformer("object-assign", {
  CallExpression: function (node, parent, scope, file) {
    if (this.get("callee").matchesPattern("Object.assign")) node.callee = file.addHelper("extends);
  }
});
```

```sh
$ babel --plugins object-assign script.js
```

```javascript
require("babel").transform("code", { plugins: ["object-assign"] });
```

**Comment by zloirock** [comment]
@JedWatson [you can require only needed feature](https://github.com/zloirock/core-js#commonjs). `babel/polyfill` simply requires fully version of `core-js/shim`and `regenerator/runtime`.

**Comment by JedWatson** [comment]
@zloirock correct but as Babel is already adding a helper to my transpiled code, I'm trying to _reduce_ the number of times this particular function is included.

Thanks for the implementation @sebmck, I've published that to npm :smile: 

https://github.com/JedWatson/babel-plugin-object-assign

**Comment by sebmck** [comment]
:tada: :balloon: :birthday: First ever released Babel plugin :birthday: :balloon: :tada:

**Comment by sebmck** [comment]
@thejameskyle We need a page on the site for this now :smile:

**Comment by thejameskyle** [comment]
Heh let's wait until we have a few more

**Comment by sebmck** [comment]
:dancer: :dancer:

**Comment by stefanpenner** [comment]
emberaddons.com + broccoliplugins.com are the result of the same code-base, maybe that will be handy for you guys?

**Comment by thejameskyle** [comment]
Yeah we should probably do something like that. We should also document the `babel-plugin-*` naming scheme and certain npm keywords to use.
