### ISSUE TITLE
`arguments` is incorrect in nested functions 

### ISSUE THREAD

**Issue by jhorwit2** [babel/babel#1202]
I'm on the newest version of babel and found a huge bug with how arguments is being generated in nested functions. 

Code that messes up: 

https://github.com/addthis/fluxthis/blob/master/src/ActionCreator.es6.js#L152

Explanation: 

You will notice that this fat arrow function we call

`payload = createPayload.apply(this, arguments);`

In past versions of babel, arguments always pointed to the fat arrow function; however, currently the arguments that are being passed to this function is that of the surrounding function.  You can see the generated code here:

http://pastebin.com/P0HeL3P9

You will notice that _arguments gets used in the createPayload method invocation when it should be arguments of the current function.

**Comment by zloirock** [comment]
See [FAQ](http://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-).

**Comment by jhorwit2** [comment]
Wow, never realized that. Was this recently a fixed bug @zloirock ?

**Comment by sebmck** [comment]
No it's always been like this.

**Comment by jhorwit2** [comment]
This works on 4.xx :). Our production code works fine.

**Comment by sebmck** [comment]
`arguments` inside of arrow functions have always been remapped.

**Comment by jhorwit2** [comment]
Ah, we recently made changes that broke this and some how our tests didn't pick this up. Lo siento

**Comment by jhorwit2** [comment]
Thanks for the quick response as always though!
