### ISSUE TITLE
BigInt exponentiation

### ISSUE THREAD

**Issue by Miladiir** [babel/babel#12036]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
Code is emitted as `Math.pow(10n, 3n)` which is invalid.

- [Repo](https://git.oliverconzen.de/miladiir/blog/src/branch/decimal-experimentation)
Take a gander at BadDecimal.ts where I toy with bigint.

**Input Code**

```js
10n ** 3n
```

**Expected behavior**
The code is emitted as ``10n ** 3n``, so left untouched. As far as I know this is the only valid syntax for the operation. Please correct me if I am wrong.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    "@babel/env",
    [
      "@babel/preset-typescript",
      {
        "allowDeclareFields": true,
        "onlyRemoveTypeImports": true
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-bigint",
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining",
    [
      "polyfill-corejs3", {
        "method": "usage-pure"
      }
    ],
    [
      "polyfill-regenerator", {
        "method": "usage-pure"
      }
    ]
  ]
}

```

**Environment**

```

  System:
    OS: Windows 10 10.0.20201
  Binaries:
    Node: 12.18.3 - ~\nvm\nodejs\bin\node.EXE
    npm: 6.14.6 - ~\nvm\nodejs\bin\npm.CMD
  npmPackages:
    @babel/core: ^7.11.4 => 7.11.6
    @babel/plugin-proposal-class-properties: ^7.10.4 => 7.10.4
    @babel/plugin-proposal-nullish-coalescing-operator: ^7.10.4 => 7.10.4
    @babel/plugin-proposal-object-rest-spread: ^7.11.0 => 7.11.0
    @babel/plugin-proposal-optional-chaining: ^7.11.0 => 7.11.0
    @babel/plugin-syntax-bigint: ^7.8.3 => 7.8.3
    @babel/plugin-syntax-dynamic-import: ^7.8.3 => 7.8.3
    @babel/preset-env: ^7.11.0 => 7.11.5
    @babel/preset-typescript: ^7.10.4 => 7.10.4
    babel-loader: ^8.1.0 => 8.1.0
    babel-loader-exclude-node-modules-except: ^1.0.3 => 1.0.3
    babel-plugin-polyfill-corejs3: 0.0.5 => 0.0.5
    babel-plugin-polyfill-regenerator: 0.0.4 => 0.0.4
    webpack: ^4.44.1 => 4.44.1

```
- Babel version(s): v7.11.4
- Node/npm version: Node v12.18.3 / npm 6.14.6
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `loader`

**Possible Solution**
No idea.

**Additional context**
As you can see, I use the two new `babel-plugin-polyfill-*` plugins, so that might be related. I don't see why babel transforms the code though, as the target I was aiming at definetly understands `**` for numbers as well.

Relevant is the `.browserslist.rc`: 
```
[development]
last 1 chrome version
last 1 firefox version

[production]
>0.5%
last 4 versions
Firefox ESR
not ie < 9
```

I used the development target.

**Comment by JLHwung** [comment]
Thanks for the repo. Here are some issues I found:

`@babel/plugin-syntax-bigint` is unnecessary: BigInt is part of ES2020 and always enabled in `@babel/parser` 7.11. The plugin is an no-op for modern `@babel/parser` versions

Your repo includes a `.npmrc` with custom `registry`: I don't recommend to include it in a public reproduction for security concerns.

> the target I was aiming at definitely understands ** for numbers as well.

I don't think so. Your production targets includes IE 9 which does not support `**` and thus `**` is transformed. You can add `debug: true` to see why Babel applies certain plugin.

```json
["@babel/env", { "debug": true }]
```

You can also use `BABEL_SHOW_CONFIG_FOR=./src/BadDecimal.ts` to see the effective babel config applied on your source.

On the issue of `10n ** 3n`: This is a good catch. Babel could skip when one of operands is a BigInt Literal. But Babel will still convert `a ** b` to `Math.pow(a, b)`: It's up to users discretion that `a` or `b` is not a BigInt.

**Comment by Miladiir** [comment]
>Your repo includes a .npmrc with custom registry: I don't recommend to include it in a public reproduction for security concerns.

Thank you for pointing this out. The repository requires authentication, therefore this would only be an inconvenience for those trying to reproduce. Not really a security concern though, unless I am wrong.

> Your production targets includes IE 9

Damn. I though I was careful about that, but I guess not. I really do not want to support browsers that low. That probably is the issue. Thank you for catching that. I will close this issue now.

I guess babel would have no way to see that `a ** b` are not numbers, but bigints. The same way that JSBI is needed as a library instead of a proper biging polyfill.
