### ISSUE TITLE
[preset-env] allow specifying corejs location

### ISSUE THREAD

**Issue by 43081j** [babel/babel#12035]
As mentioned in storybookjs/storybook#12312, we currently have a problem due to babel injecting a relative core-js import.

Inside storybook, we build from the consumer's directory rather than storybook's own directory (inside node_modules) which means when babel is executed, it will try import the top-level core-js.

This is a problem because the top-level core-js isn't necessarily the same version as the one storybook has as a dependency. It can therefore cause many problems, especially if core-js 2 is imported rather than 3.

Ideally, what would be nice is **the ability to specify an absolute path to core-js** for babel to use when injecting paths. We could then specify the one storybook installs, explicitly.

Here:

https://github.com/babel/babel/blob/20fd450ab7855622674f56772879953b49c95f23/packages/babel-preset-env/src/utils.js#L63-L65

You blindly import `core-js/modules/${mod}` which is where the problem lies by the looks of it. If we could specify an absolute path which is prepended to this instead, that would solve the issue here.

I am happy to work on this if you can point me in the right direction.

**Comment by arcanis** [comment]
@nicolo-ribaudo Would @43081j's suggestion be reasonable? When using Storybook with workspaces, `core-js` has to be listed as dependency in every workspace containing stories 🤔

**Comment by nicolo-ribaudo** [comment]
It is reasonable, but I would prefer to implement this in https://github.com/babel/babel-polyfills (which will be the replacement for `@babel/preset-env`'s `core-js` integration in Babel 8)

**Comment by 43081j** [comment]
Keep in mind this is causing all sorts of problems over at storybook for many, many people. There is no obvious workaround either other than installing core-js directly and hoping for the best.

If there's any short term solution to unblock storybook's problem, that would be useful.

**Comment by nicolo-ribaudo** [comment]
I'm trying to understand what is the problem, but I'm not sure I got it.

Inside a storybook file (let's suppose it's `@storybook/html/index.js`) there is an `import "core-js/modules/some-polyfill.js"` injected while transpiling Storybook with Babel.

Let's consider the files structure mentioned in the Storybook issue (plus `@storybook/html/index.js`):
```
/node_modules
- core-js (2.x)
- some-dependency
-- node_modules/core-js (DEDUPED, 2.x)
- @storybook
-- html
--- index.js
--- node_modules/core-js (3.x)
```

You are suggesting to inject `import "/node_modules/@storybook/html/node_modules/core-js/modules/some-polyfill.js"` when compiling `@storybook/html/index.js`, however I don't understand why just `import "core-js/modules/some-polyfill.js"` doesn't work: doesn't webpack use the normal Node.js resolution algorithm starting from `/node_modules/@storybook/html/index.js` when resolving `core-js`, thus getting the correct version?

**Comment by arcanis** [comment]
It's the classic hosting problem: the version of core-js that will be used won't necessarily be the one expected by Storybook. And under PnP installs such errors are very visible, thus requiring users to add core-js to their own deps.

**Comment by 43081j** [comment]
yes basically the webpack build is executed from the _user's_ working directory. again using this example:

```
/src
/node_modules
- core-js (2.x)
- some-dependency
-- node_modules/core-js (DEDUPED, 2.x)
- @storybook
-- html
--- index.js
--- node_modules/core-js (3.x)
```

storybook executes webpack with inputs `["src/*", "node_modules/@storybook/whatever.js"]` effectively, from `/` as the working directory.

what this means is when webpack passes it through babel, babel will inject relative imports just like you said. 

but then we end up with errors like this:

```
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator'
```

because babel injected a corejs 2 import, while storybook depends on corejs 3. if we tell babel to inject 3.x imports (if thats possible), then the consumer's code will break the same way as we'll be trying to import a 3.x path from corejs 2.

**Comment by lake2** [comment]
same issue +1

**Comment by merceyz** [comment]
This is solved by using https://github.com/babel/babel-polyfills/tree/main/packages/babel-plugin-polyfill-corejs3 and can probably be closed

**Comment by nicolo-ribaudo** [comment]
Thanks @merceyz, I'm closing this since the `babel-plugin-polyfill-corejs3` solution is exactly what is needed for this issue.
