### ISSUE TITLE
Issue with @babel/parser@7.11.5

### ISSUE THREAD

**Issue by mfs-abhinav** [babel/babel#12042]
## Bug Report
Not able to install @babel/parser@7.11.5 package whereas 7.11.4 is working
node -v ---> v12.18.0
npm -v ---> 6.14.4

npm i @babel/parser@7.11.5
OR
npm i @babel/parser

**Current behavior**
$ npm i @babel/parser@7.11.5
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path P:\TestApp\node_modules\@babel\parser
npm ERR! dest P:\TestApp\node_modules\@babel\.parser.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'P:\TestApp\node_modules\@babel\parser' -> 'P:\TestApp\node_modules\@babel\.parser.DELETE'    
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by JLHwung** [comment]
This is a bug of npm. See also https://github.com/facebook/jest/issues/10150#issuecomment-675864493 for a workaround.
