### ISSUE TITLE
parser/generate/traverse types mismatch

### ISSUE THREAD

**Issue by zenxds** [babel/babel#12047]
## Bug Report

**Current behavior**

**Input Code**

```js
import * as parser from '@babel/parser'
import generate from '@babel/generator'
import traverse from "@babel/traverse"

const code = "const a = 123"
const ast = parser.parse(code)
traverse(ast, {}) // Error line

const { code: outputCode } = generate(ast, {}, code) // Error line
```

then got TypeScript error

(node_modules/@babel/types/lib/index").File' is not assignable to type 'babel.types.File'

**Expected behavior**

No TypeScript Error

```
"@babel/generator": "^7.11.5",
"@babel/parser": "^7.11.5",
"@babel/traverse": "^7.11.5",
"@babel/types": "^7.11.5"
```

**Possible Solution**

add types for @babel/traverse and @babel/generator with `import('@babel/types').File`

**Comment by zenxds** [comment]
I resolved this by add paths config to tsconfig.json

```
"paths": {
    "@babel/types": ["./node_modules/@babel/types"]
}
```

**Comment by nicolo-ribaudo** [comment]
I'm pretty sure this is because npm/yarn don't always dedupe your dependencies, but TS expects them to be deduped.
