### ISSUE TITLE
No warning when polyfill is needed?

### ISSUE THREAD

**Issue by Tilogorn** [babel/babel#12045]
## Bug Report

**Current behavior**
I am transpiling my code with babel to work with `IE 11` (among others) with `preset-env`, no polyfill library and no bundler. Arrow functions, default parameters, ... everything was transpiled magically. But when I started using `Array.prototype.find` the generated output file contained the exact same call to `Array.prototype.find`, no polyfill. But according to [caniuse.com](https://caniuse.com/array-find)  `Array.prototype.find` is not supported on IE 11 (which I can confirm by testing).

See this [REPL](https://babeljs.io/repl#?browsers=IE%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAcwKZQNKoJ4CFsBqAhgDYioAUcARgFarQA0iAbqeQJSIDeAUIgMQAndCCFIA8nQZQAdAGscAZyrToHWcBhgAJhUXZEAXgB8iGvWgBtAwF1jRo63aoOAbl4BfXkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Ces2015%2Cenv&prettier=true&targets=&version=7.11.6&externalPlugins=)

I get that using just the preset replaces only certain cases of syntax, but a warning like **"hey, you use `Array.prototype.find`, you must include a polyfill library for your targets"** is very important in my opinion, isn't it? So am I missing a hint in the docs/cli output or is this really not implemented yet? Am I maybe misunderstanding that babel is capable of detecting such compatibility issues?

**Input Code**

```js
function getKeyByValue(object, value) {
    return Object.keys(object).find(key => object[key] === value);
}

```

**Expected behavior**
I would expect to see babel replace the `find` method e.g. with a loop:

```js
function getKeyByValue(object, value) {
    var keys = Object.keys(object);
    for (var i = 0; i < keys.length; i++) {
        if (object[keys[i]] === value) {
            return keys[i];
        }
    }
}
```

But instead I get this output:

```js
function getKeyByValue(object, value) {
  return Object.keys(object).find(function (key) {
    return object[key] === value;
  });
}
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "ie": "11",
                    "chrome": "49",
                    "firefox": "66",
                    "edge": "17"
                }
            }
        ]
    ]
}

```

- Filename: `.package.json`

```js
{
  ...
  "scripts": {
    "build": "babel mysource -d mydest",
  },
  ...
}
```

**Environment**

```
  System:
    OS: Linux 5.4 Linux Mint 19.3 (Tricia)
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  npmPackages:
    @babel/cli: 7.8.4 => 7.8.4 
    @babel/compat-data: 7.8.4 => 7.8.4 
    @babel/core: 7.8.4 => 7.8.4 
    @babel/preset-env: 7.8.4 => 7.8.4
```

**Comment by JLHwung** [comment]
Babel assumes your environment has full ES5 support. https://babeljs.io/docs/en/caveats#es5

> a warning like "hey, you use Array.prototype.find, you must include a polyfill library for your targets"

- There are false positive cases on detecting `Array#find`. For example, in `arr.find()`, `arr` could be an Array, or an instance of a class that supports `.find`. Printing warning messages on cases like that introduces demands on new option `suppressArrayFindWarnings: boolean` -- that will eventually makes config complicated.

- You can add a polyfill without babel: For example requiring [`array-polyfill`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill) before your app. Babel has no idea whether `Array#find` is polyfilled: eventually you will have to manually set `suppressArrayFindWarnings: true` after you have added a polyfill. This is not great.

The idea is that polyfill is independent with Babel - It is part of a runtime code but Babel can only do static analysis. That said, we could print such messages in a customized plugins, which scans your code and reports builtin method usage (though likely) that might need a polyfill. But we will not consider doing this in `@babel/preset-env`.

**Comment by Tilogorn** [comment]
Alright, thanks for the clarification :+1:
