### ISSUE TITLE
Cannot find module '@babel/preset-core'

### ISSUE THREAD

**Issue by tmsean** [babel/babel#12041]
I'm getting the error `Cannot find module '@babel/preset-core'` in my project.
Running `npm install @babel/preset-core` but this error appeared:
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@babel%2fpreset-core - Not found
npm ERR! 404
npm ERR! 404  '@babel/preset-core@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`
Have this package been published? If not then which package should i remove to resolve this error?

Thank you,
Son To Minh

**Comment by JLHwung** [comment]
`@babel/preset-core` is not a valid babel preset name. Please attach your babel config.

**Comment by tmsean** [comment]
> `@babel/preset-core` is not a valid babel preset name. Please attach your babel config.

My babel.config.js:
`module.exports = function(api) {
  api.cache(true);
  return {
    "presets": [
      "@babel/core",
      "@babel/preset-env", 
      "@babel/preset-react",
    ]
  };
};`

**Comment by JLHwung** [comment]
`@babel/core` is not a preset, please remove it from your `babel.config.js`.

**Comment by tmsean** [comment]
> `@babel/core` is not a preset, please remove it from your `babel.config.js`.

Thank you, the problem is solved.

**Comment by tmsean** [comment]
> `@babel/core` is not a preset, please remove it from your `babel.config.js`.

Thank you, i removed @babel/core from `babel.config.js` and the problem is solved
