### ISSUE TITLE
Destructuring Assignment completion value inconsistent / differs from spec 

### ISSUE THREAD

**Issue by jsoverson** [babel/babel#1204]
According to [12.14.5.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-destructuringassignmentevaluation) the completion value for destructuring assignments (seemingly) should be undefined. Right now babel transforms array assignment pattern into code that either completes to the rhs value or the last assignment, eg.

```javascript
let x,y; 
[x,y] = [1,2]
```

transforms to 

```javascript
// earlier code cut
var x = undefined,  y = undefined;
_temp = [1, 2];

var _temp2 = _slicedToArray(_temp, 2);

x = _temp2[0];
y = _temp2[1];
```

The completion value there will be the last assignment instead of undefined.

In another case, the following code 

```javascript
var x,y; 

function foo() {
  return [x,y] = [1,2]
}
```

will transform to 

```javascript
// earlier code cut
var x, y;

function foo() {
  var _temp, _temp2;

  return (_temp = [1, 2], _temp2 = _slicedToArray(_temp, 2), x = _temp2[0], y = _temp2[1], _temp);
}
```

The above function will return the rhs value instead of undefined.

FWIW, Firefox's implementation returns the right hand value in both cases so I'm not sure if i'm interpreting the spec incorrectly but babel is still inconsistent either way.

**Comment by jsoverson** [comment]
btw I came across this trying to adapt kevin smith's esdown repl to use babel for embedding into blogs/docs, you can see the results of the inconsistent behavior [here](http://jsoverson.github.io/es6repl/#____%5Bx%2Cy%5D%20%3D%20%5B1%2C2%5D%0A(function()%7Breturn%20%5Bx%2Cy%5D%20%3D%20%5B1%2C2%5D%7D()))

**Comment by sebmck** [comment]
> According to 12.14.5.2 the completion value for destructuring assignments (seemingly) should be undefined

What step are you getting that from?
