### ISSUE TITLE
No way to force Babel to transpile arrow functions?

### ISSUE THREAD

**Issue by colbymelvin** [babel/babel#12053]
## Bug Report

- [x] I would like to work on a fix!
(Unless there's already an existing solution)

**Current behavior**
My organization works with a code base that does not support Internet Explorer, therefore we don't supply an `ie` target in our browserlist. However, some of our 3d party dependencies rely on Babel transforms that are seemingly only performed when targeting `ie >= 11`, specifically the `transform-arrow-functions` transform. 

We're using `@babel/preset-env`, and I've tried various methods of _forcing_ Babel to perform the `transform-arrow-functions` transform, to no avail. 
- using `include: ['@babel/plugin-transform-arrow-functions']` on the preset doesn't seem to work
- using `forceAllTransforms: true` on the preset doesn't seem to work

Only when we add an `ie` target back into our browserlist does Babel transform arrow functions. Is there a way to achieve this _without_ specifying an `ie` target or otherwise altering our browserlist (which we use for other things)?

**Expected behavior**
I would expect that using `forceAllTransforms` or using `include` with the specific plugin would instruct Babel to perform the relevant transform, even though Babel thinks it's not needed given our browserlist.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`
```js
...
 presets: [
    [
        '@babel/preset-env',
        {
            useBuiltIns: 'entry',
            corejs: 3,
            forceAllTransforms: true, // doesn't work
            include: ['@babel/plugin-transform-arrow-functions'] // doesn't work
        }
    ]
],
...
```

- Browserlist:
```
"browserslist": [
    "chrome >= 66",
    "firefox >= 60",
    "edge >= 41",
    "ios >= 10"
]
```

**Environment**
```  
System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - bin/docker-stubs/npm
  npmPackages:
    @babel/core: ^7.11.1 => 7.11.1 
    @babel/plugin-proposal-class-properties: ^7.10.4 => 7.10.4 
    @babel/plugin-proposal-optional-chaining: ^7.11.0 => 7.11.0 
    @babel/plugin-transform-arrow-functions: ^7.10.4 => 7.10.4 
    @babel/plugin-transform-runtime: ^7.11.0 => 7.11.0 
    @babel/preset-env: ^7.11.0 => 7.11.0 
    @babel/preset-react: ^7.10.4 => 7.10.4 
    @babel/runtime: ^7.11.2 => 7.11.2 
    babel-cli: ^6.26.0 => 6.26.0 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-jest: ^26.2.2 => 26.2.2 
    babel-loader: ^8.1.0 => 8.1.0 
    babel-plugin-lodash: ^3.3.4 => 3.3.4 
    babel-plugin-require-context-hook: ^1.0.0 => 1.0.0 
    babel-plugin-syntax-trailing-function-commas: ^6.22.0 => 6.22.0 
    eslint: ^7.6.0 => 7.6.0 
    eslint-plugin-babel: ^5.3.1 => 5.3.1 
    jest: ^26.2.2 => 26.2.2 
    webpack: ^4.44.1 => 4.44.1
```

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by JLHwung** [comment]
You can add `debug: true` to preset-env options. It will print enabled plugins. Does it contain `arrow-functions` transform when you specify `include: ['@babel/plugin-transform-arrow-functions']`?

You can also prepend `BABEL_SHOW_CONFIG_FOR=./src/debugging-source-code.js` to your build command, Babel will print effective configs.

**Comment by colbymelvin** [comment]
@JLHwung 

Yes, when using `include: ['@babel/plugin-transform-arrow-functions']`, I do see that the `arrow-functions` transform is included:

```
Using targets:
{
  "chrome": "66",
  "edge": "79",
  "firefox": "60",
  "ios": "10"
}

Using modules transform: auto

Using plugins:
  proposal-numeric-separator { "chrome":"66", "firefox":"60", "ios":"10" }
  proposal-logical-assignment-operators { "chrome":"66", "edge":"79", "firefox":"60", "ios":"10" }
  proposal-nullish-coalescing-operator { "chrome":"66", "edge":"79", "firefox":"60", "ios":"10" }
  proposal-optional-chaining { "chrome":"66", "edge":"79", "firefox":"60", "ios":"10" }
  proposal-json-strings { "firefox":"60", "ios":"10" }
  proposal-optional-catch-binding { "ios":"10" }
  proposal-async-generator-functions { "ios":"10" }
  proposal-object-rest-spread { "ios":"10" }
  transform-dotall-regex { "firefox":"60", "ios":"10" }
  proposal-unicode-property-regex { "firefox":"60", "ios":"10" }
  transform-named-capturing-groups-regex { "firefox":"60", "ios":"10" }
  transform-async-to-generator { "ios":"10" }
  transform-exponentiation-operator { "ios":"10" }
  transform-template-literals { "ios":"10" }
  transform-arrow-functions {} <<- included here with no targets
  transform-unicode-regex { "ios":"10" }

```

However, there's no target specified and the code that is ultimately output still contains arrow functions as evidenced by `grep -r ")=>" path/to/build/dir`

**Comment by JLHwung** [comment]
> However, there's no target specified and the code

This is expected, because none of targets needs `transform-arrow-functions` and so it is manually specified by users. If it shows here, the plugin is already applied.

> output still contains arrow functions

What is the output of `BABEL_SHOW_CONFIG_FOR=./path/to/arrow-functions-source npm build`? If you see no babel config output, it is not processed by Babel and you should check on `babel-loader` `exclude` options.

**Comment by existentialism** [comment]
(Sidenote, we might want to include whether a plugin was forcibly added via `include` in the debug output to help reduce any confusion)

**Comment by colbymelvin** [comment]
(apologies for the delay in response)

> What is the output of `BABEL_SHOW_CONFIG_FOR=./path/to/arrow-functions-source npm build`? If you see no babel config output, it is not processed by Babel and you should check on `babel-loader` `exclude` options.

@JLHwung  Good catch; I had an aggressive `exclude` in my Webpack config that resulted in skipping over the file in question.

> (Sidenote, we might want to include whether a plugin was forcibly added via include in the debug output to help reduce any confusion)

@existentialism I agree - that would have been more apparent when reading the output above. Would that be something you all would accept a PR for? Happy to work on that!

**Comment by existentialism** [comment]
@colbymelvin sure!

**Comment by existentialism** [comment]
@colbymelvin going to close this for now, looking forward to your PR!
