### ISSUE TITLE
babel-plugin-transform-es2015-unicode-regex breaks regex

### ISSUE THREAD

**Issue by rwoll** [babel/babel#12075]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

`/[^\d\-a-z]/iu.exec("a")`  correctly evaluates to `null`; however, after applying the `babel-plugin-transform-es2015-unicode-regex` the transformed code incorrectly evaluates to `[ 'a', index: 0, input: 'a', groups: undefined ]`.

The transformed output is:

```
/(?:[\0-,\.\/:-`\{-\u017E\u0180-\u2129\u212B-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/i.exec("a");
``` 

You can see the input/output with the plugin applied here: https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=PQbQegOgJhC0CGsBeBdYBLArgOgKYA9cBjACgCJ4yBKIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=babel-plugin-transform-es2015-unicode-regex%406.24.1

**Expected behavior**

`babel-plugin-transform-es2015-unicode-regex` should produce code that evaluates to `null` to match the input. 

Relates: https://github.com/facebook/create-react-app/issues/9654

**Comment by rwoll** [comment]
It looks like this is a simpler regex the breaks it in the same way:

```js
# Input code
/[^a-z]/iu.exec("a")
# Evals to `null`

# Transformed code
/(?:[\0-`\{-\u017E\u0180-\u2129\u212B-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])/i.exec("a");
# Evaluates to `[ 'a', index: 0, input: 'a', groups: undefined ]`
```

**Comment by jridgewell** [comment]
Fun. It's because of the `i` flag. The transformed regex didn't exclude the insensitive-equivalent `[A-Z]`. This is actually a bug in our regex engine, [regexpu-core](https://github.com/mathiasbynens/regexpu-core). @mathiasbynens

**Comment by rwoll** [comment]
Thanks for taking a look! I've filed a bug report upstream: https://github.com/mathiasbynens/regexpu-core/issues/45

**Comment by jridgewell** [comment]
This is fixed upstream now, running `npm update regexpu-core --depth=2` should bring you up to date.

**Comment by mathiasbynens** [comment]
Thanks for taking care of this, @jridgewell!
