### ISSUE TITLE
Better error message for missing number exponent after "e"

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#12071]
## Feature Request

**Is your feature request related to a problem?**
Consider this (invalid) code:
```js
12.3e
```

It throws this error:
```
Invalid number (1:0)
```

**Describe the solution you'd like**

It should throw something like
```
Missing exponent after 'e' in floating-point number
```

---

If you are interested in fixing this bug, you should introduce a new error message and use it in the "tokenizer": the part of the parser which takes the input source code as a string and generates a set of corresponding tokens (`1.2`, `foo`, `+`, `"baz"`, `var`, ...).

[:warning: **SPOLIER** (it's here, but first try finding it yourself!)](https://github.com/babel/babel/blob/7028a14c7f8d0d6ae8954ff9020ec48c241293de/packages/babel-parser/src/tokenizer/index.js#L1152)

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. ~Add a test~ _We probably already have tests for this with the "bad" error message_
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.json` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

If you need any help, feel free to reply here or write me on slack!

**Comment by JLHwung** [comment]
An edge case: Currently Babel throws
```
Invalid or unexpected token
```
for `1.e`, which should have thrown `Missing exponent after 'e' in floating-point number`.

**Comment by iamfotx** [comment]
I'm going to work on this.

**Comment by nicolo-ribaudo** [comment]
It's yours! If you need any help feel free to ask.

**Comment by abhinavjonnada82** [comment]
Is this available? If so, would like to work on it?

**Comment by iamfotx** [comment]
> Is this available? If so, would like to work on it?
Nope. I've already submitted the PR.
