### ISSUE TITLE
URL polyfill for Safari 13+

### ISSUE THREAD

**Issue by dilyanpalauzov** [babel/babel#12089]
With these files bbb.json:
```json
{
  "presets": [
    [
      "@babel/preset-env",
	{
	    "bugfixes": true,
	    "corejs": 3,
	    "modules": false,
	    "targets": "safari > 13.1", 
	    "useBuiltIns": "usage"
      }
    ]
  ]
}
```
and xxx.js:
```javascript
new URL('https://x.y.z');
```
calling `babel --config-file ./bbb.json xxx.js` produces
```
import "core-js/modules/web.url";
new URL('https://x.y.z');
```
https://caniuse.com/url and https://caniuse.com/urlsearchparams have no concerns.

Why is the polyfill necessary for Safari?

**Comment by nicolo-ribaudo** [comment]
We use `core-js-compat` as the data source for `core-js` 3, please ask the question in the `core-js` repository.

Usually it's a browser bug that `core-js` fixes but isn't listed in caniuse.

**Comment by nicolo-ribaudo** [comment]
Ok, it's needed for https://github.com/zloirock/core-js/issues/656
