### ISSUE TITLE
Since 7.11.5 the standalone babel.js is uglified

### ISSUE THREAD

**Issue by njoAI** [babel/babel#12095]
## Bug Report

**Current behavior**
Since version 7.11.5 the **standalone** versions of babel.js and babel.min.js are identical and both uglified. This can be verified locally and by looking at the CDN-scripts:

See [unpkg@7.11.5/babel.js](https://unpkg.com/@babel/standalone@7.11.5/babel.js) and [unpkg@7.11.5/babel.min.js](https://unpkg.com/@babel/standalone@7.11.5/babel.min.js).
See [unpkg@7.11.6/babel.js](https://unpkg.com/@babel/standalone@7.11.6/babel.js) and [unpkg@7.11.6/babel.min.js](https://unpkg.com/@babel/standalone@7.11.6/babel.min.js).

**Expected behavior**
See [unpkg@7.11.4/babel.js](https://unpkg.com/@babel/standalone@7.11.4/babel.js) and  [unpkg@7.11.4/babel.min.js](https://unpkg.com/@babel/standalone@7.11.4/babel.min.js).

- Babel version(s): [>=v7.11.5]

**Comment by JLHwung** [comment]
This is a regression introduced in https://github.com/babel/babel/pull/12010/files#diff-878989239e07228f7903fde98f450ed9L105, @njoAI Do you wanna open a PR?

**Comment by njoAI** [comment]
Hello JLHwung,

thank you for your quick reaction. No I don't want to open a PR. I'm not to familiar with your code base. I'm good if this is rectified some time in the future.
