### ISSUE TITLE
preset-env targets is different even though resolved browserslist query is equal

### ISSUE THREAD

**Issue by eps1lon** [babel/babel#12123]
## Bug Report

Given a `browserlist` query with "unresolved" targets (e.g. "last 1 version, > 0.5%") and its resolved version ("android 81 [...]") the targets used by `preset-env` are different.

Repro: https://github.com/eps1lon/babel-preset-env-browserslist

**Current behavior**
```
> 0.5%, last 2 versions, Firefox ESR, not dead, not IE 11
```
lists `android: "android": "84"` in `targets`

while 
```
and_chr 85
and_ff 79
and_qq 10.4
and_uc 12.12
android 81
baidu 7.12
chrome 85
chrome 84
chrome 83
edge 85
edge 84
firefox 81
firefox 80
firefox 79
firefox 78
ie 11
ios_saf 14.0
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
kaios 2.5
op_mini all
op_mob 59
opera 71
opera 70
safari 14
safari 13.1
samsung 12.0
samsung 11.1-11.2
```

lists `android: "android": "81"` in `targets`

**Expected behavior**
Since both produce the same browsers with `browserslist` the `preset-env` targets should be equal

**Environment**

```
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
  Binaries:
    Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
  npmPackages:
    @babel/cli: ^7.11.6 => 7.11.6 
    @babel/core: ^7.11.6 => 7.11.6 
    @babel/preset-env: ^7.11.5 => 7.11.5
```

**Possible Solution**

No idea.

**Additional context**

This behavior isn't breaking in this particular instance since the plugins used are the same. But it might break in the future

**Comment by JLHwung** [comment]
These queries are not equivalent, well in the sense of `@babel/helper-compilation-targets`, because 

https://github.com/babel/babel/blob/9808d2566e6a2b2d9e4c7890d8efbc9af180c683/packages/babel-helper-compilation-targets/src/index.js#L211

See also [browserslists docs](https://github.com/browserslist/browserslist#js-api). It is specified so that `android: 68` would not be processed as `android: 85` because `caniuse` does not have stat data about `android: 68`.

**Comment by eps1lon** [comment]
> These queries are not equivalent, well in the sense of @babel/helper-compilation-targets, because

Should we maybe document the options with which you run the browserslist query? Because this is confusing. I don't think we should be expected to know about babel source code.

**Comment by eps1lon** [comment]
Opened https://github.com/babel/website/pull/2381
