### ISSUE TITLE
Babel typescript wrong overwrite subclass property

### ISSUE THREAD

**Issue by duannx** [babel/babel#12128]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
Let say, I have 2 classes `Parent` and `Child`. `Child` is extending `Parent`. `Child` has one property `height` that is set in the constructor by calling the method `setProperties`. I create an Object of `Child` and it's `height` is always `undefined` because it got overwritten by `_defineProperty` method which is called after the super constructor. The result is different from typescript standalone that the `height` property is set correctly. Please refer 2 examples below to view the result

- [Babel example](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=FAYwNghgzlAEAKEBOBTAdgF1gb2LWAkAO4CWAJhgBYBcsaArgLYBGKSe-sIA9mlBknogM3JAAoAlDg6dOVElAB0UFBnhJuABzYYSKKJJmwAvkZVqN2pLv2TpBeUtIVKAXgCMABk9HTp0JAwsADClCRgZLAoAB4Y6GRwiKiY0rKUKCQA5pQYtAwsbEY8fAJCIuJSuLKyUPRWhrKmNarqWjp6BpVG-LVWyi2W7bYS3XJhSulZObCusF4-jcD-xfxcYREzdChEIetkhivcYCiKYNyZYiB7EkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Ctypescript%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.10.4)
- [Typescript example](https://www.typescriptlang.org/play?target=1#code/FAYwNghgzlAEAKEBOBTAdgF1gb2LWAkAO4CWAJhgBYBcsaArgLYBGKSe+sIA9mlBknogM3JAAoAlDg6dOVElAB0UFBnhJuABzYYSKKJJmwAvkZVqN2pLv2TpBeUtIVKAXgCMABk9HTp0JAwsADClCRgZLAoAB4Y6GRwiKiY0rKUKCQA5pQYtAwsbEY8fAJCIuJSuLKyUPRWhrKmNarqWjp6BpVG+LVWyi2W7bYS3XJhSulZObCusF4+jcD+xfxcYREzdChEIetkhivcYCiKYNyZYiB7EkA)

**Input Code. Typescript**

```ts
class Parent {
  	width: number
    constructor() {
        this.setProperties()
    }
    setProperties() {
	this.width=100
    }
}

class Child extends Parent {
    height: number
    constructor() {
        super()
    }
    setProperties() {
      super.setProperties()
        this.height = 100
    }
}

const child = new Child()
console.log(child) // output {width:100, height:100} in typescript
```

**Output Code**
```js
function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

class Parent {
  constructor() {
    _defineProperty(this, "width", void 0);

    this.setProperties();
  }

  setProperties() {
    this.width = 100;
  }

}

class Child extends Parent {
  constructor() {
    super();

    _defineProperty(this, "height", void 0);
  }

  setProperties() {
    super.setProperties();
    this.height = 100;
  }

}

const child = new Child();
console.log(child); // output {width:100, height: undefined}
```

**Expected behavior**
The `height` property is set correctly. Maybe `_defineProperty(this, "height", void 0);` should be place before `super` constructor

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const presets = [
  [
    '@babel/env',
    {
      targets: {
        edge: '17',
        firefox: '60',
        chrome: '67',
        safari: '11.1',
      },
      corejs: '^3.6.5',
      useBuiltIns: 'usage',
    },
  ],
  '@babel/preset-typescript',
]
const plugins = ['@babel/plugin-proposal-class-properties']

module.exports = {
  presets,
  plugins,
}
```

**Environment**

```
System:
    OS: macOS 10.15.6
Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
npmPackages:
    @babel/cli: ^7.11.6 => 7.11.6 
    @babel/core: ^7.11.6 => 7.11.6 
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.10.4 
    @babel/preset-env: ^7.9.6 => 7.11.5 
    @babel/preset-typescript: ^7.10.4 => 7.10.4 
```

**Comment by nicolo-ribaudo** [comment]
That's the correct behavior according to the spec. If you don't want `width: number` to have any runtime effect, you can use `declare width: number;`.

**Comment by duannx** [comment]
Hi @nicolo-ribaudo, thanks for the quick reply. Could you please clarify that TypeScript will change its default behavior to be the same as the way babel is doing or vice versa?

**Comment by nicolo-ribaudo** [comment]
Babel is following the ECMAScript spec and TypeScript aims to do so, so I suppose that they will change the default behavior. You can watch https://github.com/microsoft/TypeScript/issues/12437 for more info.
