### ISSUE TITLE
Use native ESM for dev scripts 

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#12137]
Since we are now only building Babel on Node.js 14 (even if we still test it on Node.js 6), we can use native ECMAScript modules for the build scripts:

- [ ] **Top-level scripts**
  There are a bunch of scripts/tests in the [`scripts`](https://github.com/babel/babel/tree/main/scripts) folder: they can probably all be rewritten to ES modules.
  We can probably add `"type": "module"` to the top-level `package.json`, renaming config files (such as `.eslintrc.js`) to `.cjs`. Note that we cannot use ES modules for `babel.config.js` and `jest.config.js`, because those two files are used to run tests on Node.js 6.

- [ ] **[`babel-types/scripts`](https://github.com/babel/babel/tree/main/packages/babel-types/scripts)** can be rewritten to ES modules. These files should be renamed to `.mjs`, to keep the dist `@babel/types` files with the `.js` extension (they are CJS modules).

Please note that `babel-types/scripts` depends on the top-level scripts, so `babel-types/scripts` must be converted first (it cannot synchronously import an ESM file while still being CJS).

In order to test if your changes are still ok, running `yarn` (only when you clone the repo) and `make build && yarn jest` should be enough.

**Comment by JLHwung** [comment]
Note that we should also bump building requirements to `^12.16 || >= 14` in https://github.com/babel/babel/blob/main/CONTRIBUTING.md#developing

We can also update gulp to 4.2.0 which supports `.mjs` config.

**Comment by karansapolia** [comment]
I would like to work on this 🙂

**Comment by sag1v** [comment]
Can i have a go?

**Comment by nicolo-ribaudo** [comment]
Uh... I'm assigning this to @karansapolia since he claimed this issue first, but if you two want to split the work in two parts (maybe the two points I wrote in the issue description? The second one is probably easier) please discuss about it :smile:

**Comment by sag1v** [comment]
Thats okay 🙂 

@karansapolia Go for it! 💪

**Comment by karansapolia** [comment]
>We can probably add "type": "module" to the top-level package.json, renaming config files (such as .eslintrc.js) to .cjs

Renaming `Gulpfile.js` to `Gulpfile.cjs` [is not supported](https://github.com/gulpjs/gulp/issues/2417#issuecomment-586193414) and [neither does Gulp support esm](https://github.com/gulpjs/gulp/issues/2417#issuecomment-586186722).

Either we should not include `"type": "module"` in the top-level `package.json` and rename all esm files to `.mjs` from `.js`. Or we can do something else.

Currently, after following the recommendations in the issue description and putting `"type": "module"` in `package.json`, `make build` throws [this error](https://pastebin.com/eRTuxWa1). Let me know what should be done or if I am missing something.

@nicolo-ribaudo

**Comment by karansapolia** [comment]
> Note that we should also bump building requirements to `^12.16 || >= 14` in https://github.com/babel/babel/blob/main/CONTRIBUTING.md#developing
> 
> We can also update gulp to 4.2.0 which supports `.mjs` config.

Ah! Missed this. So we will have to update gulp. Will do.

**Comment by nicolo-ribaudo** [comment]
Oh that's unfortunate 🙁
We can use the `.mjs` extension instead of `"type": "module"` then.

**Comment by nicolo-ribaudo** [comment]
@karansapolia Now that I think about it again, it's easier to avoid `"type": "module"` in package.json and only migrate build scripts: `Gulpfile.js` needs to be kept as-is because we run it on Node.js 6

**Comment by nicolo-ribaudo** [comment]
@karansapolia I see you pushed some commits! :muscle: Do you need any help to move forward?

**Comment by karansapolia** [comment]
@nicolo-ribaudo Yes, I was stuck on an error. Could use some help definitely. Let me create a draft PR so all can have a look.
