### ISSUE TITLE
Babel is not able to output the optional chaining operator without transpiling it

### ISSUE THREAD

**Issue by craigjennings11** [babel/babel#12140]
## Bug Report

**Current behavior**
Babel is not able to output the optional chaining operator without first transpiling it.

With a browserslist of: `last 2 Chrome versions`
```
ERROR in ./index.js 3:14
Module parse failed: Unexpected token (3:14)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| (() => {
|   const x = 'abc';
>   const y = x?.length;
| })();
```

With a browserslist of: `last 2 Chrome versions, IE 11`, it succeeds. However the output (as expected) has the optional chaining operator transpiled to 

```js
  var x = 'abc';
  var y = x === null || x === void 0 ? void 0 : x.length;
```

**Input Code**

```js
const x = 'abc';
const y = x?.length;
```

**Expected behavior**
Babel would succeed even when the browserslist only lists browsers that currently support the optional chaining operator.

**Babel Configuration**
- `babel.config.js`

```js
module.exports = {
  presets: ['@babel/preset-env'],
};
```

- `.browserslistrc`

```
last 2 Chrome versions
```

- `webpack.config.js`

```js
module.exports = {
  entry: './index.js',

  module: {
    rules: [
      {
        test: /\.js$/,
        use: 'babel-loader',
      },
    ],
  },
};
```

- `index.js`

```js
(() => {
  const x = 'abc';
  const y = x?.length;
})();
```

**Environment**
- Babel version: v7.11.6
- Node/Yarn version: Node 12.18.4/Yarn 1.22.4
- OS: Windows 10
- Monorepo: No
- How you are using Babel: `loader`

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by craigjennings11** [comment]
I just made the connection that this is probably a webpack issue. Turns out that's the issue.

**Comment by JLHwung** [comment]
Duplicate of https://github.com/babel/babel-loader/issues/871
