### ISSUE TITLE
Typescript: fields defined with definite assignment assertion are removed with TS compiler flag `useDefineForClassFields` set

### ISSUE THREAD

**Issue by akphi** [babel/babel#12146]
## Bug Report

**Current behavior**
If I have a field defined using `!`, for example:
```typescript
class Person {
  job?: number;
  age!: number;

  constructor() {
    
  }
}
```

`babel` using `preset-typescript` will transform it to this (REPL [link](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=true&loose=false&code_lz=MYGwhgzhAEAKCmAnCB7AdtA3gKGtAVigEYD8AXNGgK4C2RSA3LtGAObwCEF1dj2zwdBAAuiKsGEpEACgCUWZnmYBfbMqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=)):

```javascript
class Person {
  constructor() {}
}
```

I think is the behavior currently being implemented, given [this](https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-typescript/test/fixtures/class/uninitialized-definite-with-declare-enabled) test case.

This is the same behavior I observe in Typescript version < 3.7, see this playground [link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=3.6.3#code/MYGwhgzhAEAKCmAnCB7AdtA3gWAFDWjTAFt4B+ALmggBdEBLNAcwG48DgALekAE0XhoAhFTQBXYgCMkbfNDBN4IwhOmJZ7aMHS1EY4DRSIAFAEosmgL55LQA)

But Typescript 3.7 comes with the new compiler flag `useDefineForClassFields` ([doc](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#the-usedefineforclassfields-flag-and-the-declare-property-modifier)). With this option enabled, see this playground [link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=3.7.5#code/MYGwhgzhAEAKCmAnCB7AdtA3gWAFDWjTAFt4AuaCAF0QEs0BzAbjwICsUAjAfgrQFdinJC3zQwDeAEI+g4YlGtowdNUT9gVFIgAUASixKCSgL54TQA), for the same input above, what Typescript generates is:
```javascript
"use strict";
class Person {
    job;
    age;
    constructor() {
    }
}
```

**Expected behavior**
I think I get the decision behind stripping out fields defined using definite assignment assertion, so conceptually, they are no different than fields defined using `declare`. However, for my use case, I would really like `babel` to be in sycn with Typescript here for the case where `useDefineForClassFields` is set to `true`, that is I want to fields to be present and initialized to `undefined`. I think I have seen exception made in the past for not stripping away `!` fields like in #8238. I wonder if we can add a new setting to `preset-typescript` or make another exception.

**Environment**
I thought the above REPLs and playgrounds should suffice, but in case you need a minimal repo, I prepared this [repo](https://github.com/akphi/config-tester). For this the important bits in my configs are:
```js
// tsconfig.json
{
  ...
  "useDefineForClassFields": true,
  ...
}

// babel settings (in webpack)

presets: [
      '@babel/preset-env',
      '@babel/preset-react',
      './dev/test-preset',
      ['@babel/preset-typescript', {
        onlyRemoveTypeImports: true,
        allowDeclareFields: true
      }],
    ]

// where `dev/test-preset` looks like the following 

plugins: [
      ['@babel/plugin-proposal-decorators', { legacy: true }],
      ['@babel/plugin-proposal-class-properties', { loose: true }],
    ],
```

**Additional context**
If this is appropriate, I want to mention my use case. I have some classes where the constructor is not a good place to initialize some of the fields, but I want to keep defining them using `!` because they should not be nullable (If only JS/TS support overloading constructors, this would be a non-problem). I'm also using `mobx`, which creates an observable wrapper around fields so the recommended place to set this is in the constructor, and `mobx` cannot really wrap fields that do not exist because `babel` strips away the field defined with `!` during build time. `mobx` used to work fine in the past because they use the decorator form, i.e. `@observable age!: number` which at the time worked because of #8238

Also, another totally coincidental thing is I used to have `@babel/plugin-proposal-class-properties` running before `preset-typescript` so it emits `!` fields and things work just fine, but recently, because I use `declare` field like `declare name: string`, I have to make sure `preset-typescript` runs before `@babel/plugin-proposal-class-properties`. So this problem surfaces, then on that topic, there's #10311

Anyhow, this has been a long report, please let me know what you think or what I can (maybe) help with since I'm still pretty inexperience. Thanks a lot!

**Comment by nicolo-ribaudo** [comment]
It seems like our logic in the plugin is wrong:

https://github.com/babel/babel/blob/3ec4537baa8b0802ad364dbb67b527edf4cb9314/packages/babel-plugin-transform-typescript/src/index.js#L72-L90

We unified the error handling for initializers in `declare` and definite fields, and accidentally also unified the logic to remove the class field. Are you interested in opening a PR to fix it? (I'll label this as "good first issue" otherwise").

**Comment by nicolo-ribaudo** [comment]
Please note that we should keep the field _only_ when `allowDeclareFields` (the equivalent of `useDefineForClassFields`) is true.

**Comment by akphi** [comment]
@nicolo-ribaudo Thanks for giving the opportunity. I will give it a shot!

**Comment by nicolo-ribaudo** [comment]
In case you need any help with getting started (feel free to ignore this message otherwise):

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. ~~**Write a comment there** to let other possible contributors know that you are working on this bug.~~ (done :heavy_check_mark:)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.ts`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest typescript` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest typescript` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by akphi** [comment]
@nicolo-ribaudo that was super super helpful :) I created an MR, please could you take a look? Also, if this is merged, could we do a release for @babel/transform-typescript anytime soon?
