### ISSUE TITLE
readonly modifier not being transpiled down with plugin-transform-parameters, plugin-transform-typescript

### ISSUE THREAD

**Issue by nealmanaktola** [babel/babel#12152]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

`readonly` modifier is not being transpiled down when babel plugins are used in the following order.
```
  1. @babel/plugin-transform-parameters
  2. @babel/plugin-transform-typescript
```
It seems like it happens when de structuring occurs. Here is an example:

[Simple example](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAECyCeBhcVoG8BQ1rAPYDsIAXAJwFdgjcSAKLbaAI0gFMBVEkALmmJIEt8AcwA09bLgAORfgQg8w-eNAC86AL5iG0SQIBuYIi2gkWYACYEQy0wEcyLYjz6DR9AJQaM6oA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=%40babel%2Fplugin-transform-parameters%407.10.5%2C%40babel%2Fplugin-transform-typescript%407.11.0)
**Input Code**

```ts
class MyClass {
  constructor(
    baseUrl: string,
    options: any = {},
    private readonly request: string,
  ) {}
}
```

**Expected behavior**
The actual output is 
```
"use strict";

var MyClass = function MyClass(baseUrl) {
  var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  var private readonly request = arguments.length > 2 ? arguments[2] : undefined;
  this.request = request;
};
```
The expected output should not have the use of the modifier `readonly`

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```
 yarn babel --plugins @babel/plugin-transform-parameters,@babel/plugin-transform-typescript  MyClass.ts
```

*NOTE* With the plugins reversed, i.e `@babel/plugin-transform-typescript, @babel/plugin-transform-parameters` this issue does *NOT* come up. 

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.5 - ~/github/home2/node_modules/.bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.5
  npmPackages:
    eslint: 6.8.0 => 6.8.0
    jest: 24.9.0 => 24.9.0
```
**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Plugin ordering matters; we should document that the typescript plugin should run first. (i.e. if you are using the plugin put it first, if you are using the preset put it last)

https://babeljs.io/docs/en/plugins/#plugin-ordering

**Comment by nealmanaktola** [comment]
Thanks for the very prompt response.

The context behind this issue is that metro-react-native-preset specifies the default plugins first and the typescript plugin second.
https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js#L187
I'll create an issue on their end!
