### ISSUE TITLE
preset-typescript option "onlyRemoveTypeImports" is not working 

### ISSUE THREAD

**Issue by whimzyLive** [babel/babel#12150]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

**Input Code**
I am trying transpile ts with babel using @babel/preset-typescript, but one of the challange I am facing is that, when injecting classes as parameter, import assigned type is removed by preset-typescript. I then came accross  `"onlyRemoveTypeImports": true` which promises to do exactly what I am trying to achieve. However, this does not seem to work :( 

Here is my ts file 

some-service.ts
```ts
// THIS SHALL NOT BE REMOVED
import AWS from 'aws-sdk';

@Injectable()
export class SomeService {

 constructor(
    @Inject(AWS_TOKEN.DOCUMENT_CLIENT) private dc: AWS.DynamoDB.DocumentClient,
  ) {}

// ... do some stuff with this.dc 
}
```

But in final output AWS import is removed as it wan't used within a service. and running transpiled file gives me `"ReferenceError: AWS is not defined"` error

**Expected behavior**
when onlyRemoveTypeImports option is given, typescript preset should only ever remove type imports as stated in documentation.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
  "presets": [
    [
      "@babel/preset-env"
    ],
    [
      "@babel/preset-typescript",
      {
        "onlyRemoveTypeImports": true
      }
    ]
  ],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    ["@babel/plugin-proposal-class-properties"]
  ]
}
```

**Environment**

```
  System:
    OS: Linux 4.15 elementary OS 5.1.3 Hera
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.5.0/bin/npm
  npmPackages:
    @babel/plugin-proposal-class-properties: ^7.10.4 => 7.10.4 
    @babel/plugin-proposal-decorators: ^7.10.5 => 7.10.5 
    @babel/preset-env: ^7.11.5 => 7.11.5 
    @babel/preset-typescript: ^7.9.0 => 7.10.4 
    babel-plugin-transform-typescript-metadata: ^0.3.0 => 0.3.0 

```
- Babel version(s): [ v6.26.0]
- How you are using Babel: [`cli`]

**Comment by nicolo-ribaudo** [comment]
Can you check in your lockfile which version of `@babel/plugin-transform-typescript` is installed?

**Comment by whimzyLive** [comment]
@nicolo-ribaudo it is.

``` "@babel/plugin-transform-typescript": {
      "version": "7.11.0",
      "resolved": "https://registry.npmjs.org/@babel/plugin-transform-typescript/-/plugin-transform-typescript-7.11.0.tgz",
      "integrity": "sha512-edJsNzTtvb3MaXQwj8403B7mZoGu9ElDJQZOKjGUnvilquxBA3IQoEIOvkX/1O8xfAsnHS/oQhe2w/IXrr+w0w==",
      "dev": true,
      "requires": {
        "@babel/helper-create-class-features-plugin": "^7.10.5",
        "@babel/helper-plugin-utils": "^7.10.4",
        "@babel/plugin-syntax-typescript": "^7.10.4"
      }
    },
```

**Comment by existentialism** [comment]
@whimzyLive can you create a repo that reproduces the problem? the import isn't removed when I test this locally.

**Comment by whimzyLive** [comment]
Yep, I can do that

**Comment by whimzyLive** [comment]
@existentialism  added a repo at https://github.com/whimzyLive/babel-ts-imports-removed-repro

**Comment by existentialism** [comment]
@whimzyLive it seems like the source of the issue is `babel-plugin-transform-typescript-metadata` and `'@babel/plugin-transform-modules-commonjs'`. I haven't had a chance to really dig into why though.

**Comment by whimzyLive** [comment]
This indeed was a issue with [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata).

You can read more about it [here](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/issues/37)
