### ISSUE TITLE
transform-react-jsx with `runtime: automatic` should always using `jsx-runtime`

### ISSUE THREAD

**Issue by morlay** [babel/babel#12177]
## Bug Report

"@babel/plugin-transform-react-jsx" ^7.10.4

```js
[ "@babel/plugin-transform-react-jsx", { "runtime": "automatic"  }]
```

**Current behavior**
fallbacked classic runtime when jsx use spread with key exists 

```js
_createElement("span", {...obj, key: "key"})
```

**Input Code**

```js
<span {...obj} key={"key"} />
```

**Expected behavior**
```js
_jsx("span", obj, "key")
```

**Environment**
- Babel version(s): 7.12.0
- Node/npm version: 14.12.0
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: yes
- How you are using Babel:  `cli`, `register`, `loader`

**Possible Solution**

may transform codes like

`<span key={key} {...obj} />` => `jsx("span", obj, key)`
`<span {...obj} key={key} />` => `jsx("span", {...obj, key}, key)`

to support https://github.com/babel/babel/blob/master/packages/babel-helper-builder-react-jsx-experimental/src/index.js#L270

it will be friendly for custom `jsx-runtime` and some react-like lib

**Additional context**

**Comment by AjayPoshak** [comment]
`key` is also a prop, so it need to be merged with `obj` prop before passing it down to JSX function call. I believe this is the correct behavior.

**Comment by morlay** [comment]
I got it by the comments. https://github.com/babel/babel/blob/master/packages/babel-helper-builder-react-jsx-experimental/src/index.js#L270

But it will be confused for adding custom `jsx-runtime` like https://github.com/emotion-js/emotion/pull/1970

**Comment by morlay** [comment]
key prop not be used in react component for now
i think transfroming to `_jsx("span", obj, "key")` is safe.

When we want to use key from prop. 
we should migrate to `jsx-runtime` first. then just put key into `obj` for spread, like

```
const obj = {
    key: "key"
}

<div {...obj} key={key} />
```

The rule `<div key={key} {...obj} />` using `jsx` but `<div {...obj} key={key} />` using `createElement`
i think we need a new eslint-rule to lint it 😆

**Comment by morlay** [comment]
or like this:

`<div key={key} {...obj} />` => `jsx("div", obj, key)`
`<div {...obj} key={key} />` => `jsx("div", {...obj, key}, key)`

Should got same behavior as the comments expect

**Comment by morlay** [comment]
clear enough https://github.com/facebook/react/issues/20031#issuecomment-710346866
