### ISSUE TITLE
Failed to install chokidar@2.1.8

### ISSUE THREAD

**Issue by eddierl** [babel/babel#12181]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

We have a bug installing `babel@7.12.0`.
The error we see is this one
```
error An unexpected error occurred: "https://registry.npmjs.org/chokidar/-/chokidar-2.1.8.tgz: ETIMEDOUT".
```
We are using a private repository, so we shouldn't access `registry.npmjs.org`.

**Expected behavior**

Install packages succesfully 

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.4

```
**Possible Solution**

Looks like it's related to this area of code
https://github.com/babel/babel/pull/12174/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR13

**Additional context**

**Comment by nicolo-ribaudo** [comment]
I'm surprised that it fails the install since it's marked as an optional dependency, but we can fix it I think.
