### ISSUE TITLE
babel, typescript => Syntax error when using object destructing and return type annotation together on arrow function

### ISSUE THREAD

**Issue by 07akioni** [babel/babel#12199]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

see
- [case a](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=BQbwBAHgNGB08CcCmBnALmAvgSgFxgEMA7ATzAF4A-MZdIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.12.1&externalPlugins=%40babel%2Fplugin-transform-typescript%407.12.1)
- [case b](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=BQbwBAhmC8YNoF0A0YBGN4LAXwJQC5IA7ATxgD4wRsg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.12.1&externalPlugins=%40babel%2Fplugin-transform-typescript%407.12.1)

Syntax Error

**Input Code**

Case a
```ts
({ x, ...rest }): any => rest
```
Case b
```ts
({ a, b = [] }): any => {}
```

**Expected behavior**

No syntax error

See 
- [case a ts playground](https://www.typescriptlang.org/play?ssl=1&ssc=26&pln=1&pc=30#code/BQbwBAHgNGB08CcCmBnALmAvgSgFxgEMA7ATzAF4A+MZdIA)
- [case b ts playground](https://www.typescriptlang.org/play?#code/BQbwBAhmC8YNoF0A0YBGN4LAXwJQC5IA7ATxgD4wRsg)

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

see
- [case a](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=BQbwBAHgNGB08CcCmBnALmAvgSgFxgEMA7ATzAF4A-MZdIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.12.1&externalPlugins=%40babel%2Fplugin-transform-typescript%407.12.1)
- [case b](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=BQbwBAhmC8YNoF0A0YBGN4LAXwJQC5IA7ATxgD4wRsg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.12.1&externalPlugins=%40babel%2Fplugin-transform-typescript%407.12.1)

**Environment**

see
- [case a](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=BQbwBAHgNGB08CcCmBnALmAvgSgFxgEMA7ATzAF4A-MZdIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.12.1&externalPlugins=%40babel%2Fplugin-transform-typescript%407.12.1)
- [case b](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=BQbwBAhmC8YNoF0A0YBGN4LAXwJQC5IA7ATxgD4wRsg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.12.1&externalPlugins=%40babel%2Fplugin-transform-typescript%407.12.1)

---

- Babel version(s): 7.12.1
- Node/npm version: N/A
- OS: Mac OS
- Monorepo:  no
- How you are using Babel: N/A

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
I reverted the commit that introduced the regression and released it as 7.12.2
