### ISSUE TITLE
No matching version found for @babel/plugin-transform-exponentiation-operator@^7.12.1

### ISSUE THREAD

**Issue by zaccb** [babel/babel#12191]
```
17:18:23 npm ERR! code ETARGET
17:18:23 npm ERR! notarget No matching version found for @babel/plugin-transform-exponentiation-operator@^7.12.1
17:18:23 npm ERR! notarget In most cases you or one of your dependencies are requesting
17:18:23 npm ERR! notarget a package version that doesn't exist.
17:18:23 npm ERR! notarget 
17:18:23 npm ERR! notarget It was specified as a dependency of '@babel/preset-env'
17:18:23 npm ERR! notarget 
```

This repo is asking for `7.12.1` but the [latest version](https://www.npmjs.com/package/@babel/plugin-transform-exponentiation-operator) of `plugin-transform-exponentiation-operator` is `7.10.1`.

![image](https://user-images.githubusercontent.com/3512878/96196400-80365280-0f0c-11eb-90b9-ea8d90fcba63.png)

**Comment by JLHwung** [comment]
I believe it is an npm cache issues. If you search the package name, https://www.npmjs.com/search?q=%40babel%2Fplugin-transform-exponentiation-operator, `7.12.1` is just published an hour ago.

![image](https://user-images.githubusercontent.com/3607926/96196741-3191b400-0f1e-11eb-9f9e-b45db514d86f.png)
