### ISSUE TITLE
loadPartialConfig() throws Cannot destructure property `showIgnoredFiles` of 'undefined' or 'null' on v7.12.0

### ISSUE THREAD

**Issue by MwumLi** [babel/babel#12194]
## vue 项目构建报错

项目之前是好的, 但是最近构建报错, 如下:
```
TypeError: Cannot destructure property `showIgnoredFiles` of 'undefined' or 'null'.
TypeError: Cannot destructure property `showIgnoredFiles` of 'undefined' or 'null'
     at Function.<anonymous>  (/Users/luo/WorkSpace/company/alarm/node_modules/@babel/core/lib/config/partial.js:132:7)
```
经过排查, 发现是 `@babel/core` 最新的版本 ^7.x.x 版本中发布了[不兼容的变更](https://github.com/babel/babel/pull/11907)  
根据语义话版本号的描述, ^7.x.x 版本的发布应该是兼容性功能增强, 但是因为 API 的变更导致以前直接使用 `babel.loadPartialConfig()` 的库会报错, 比如项目使用了 `@vue/cli-plugin-babel@4.1.1`, 他的实现如下
![image](https://user-images.githubusercontent.com/6889433/96206750-2e3d0d80-0f9c-11eb-94b5-fd765e1ae479.png)

这一切的问题是因为 babel 并没有安装 samver 语义话版本造成, 期待对 `loadPartialConfig` 做一下兼容修复, 重新发布版本

**Comment by MwumLi** [comment]
为什么 github v7.12.1 上面的源码已经修复了这个问题, https://github.com/babel/babel/blob/v7.12.1/packages/babel-core/src/config/partial.js#L73-L81, 但是在 npm 上的 v7.12.1 的包上代码没有更改  😪

![image](https://user-images.githubusercontent.com/6889433/96208650-9aba0b80-0fa0-11eb-8ca7-8bb6bea42dd7.png)

**Comment by nicolo-ribaudo** [comment]
I reverted the commit that introduced the regression and released it as 7.12.2

**Comment by MwumLi** [comment]
@nicolo-ribaudo `@babel/parser@7.12.2` When to publish to npm
![image](https://user-images.githubusercontent.com/6889433/96226292-044c1100-0fc5-11eb-9141-e5775ae26d20.png)

**Comment by nicolo-ribaudo** [comment]
I see this :thinking:
Maybe it's a caching issue?

![Schermata da 2020-10-16 09-38-52](https://user-images.githubusercontent.com/7000710/96227403-5b85bd80-0f94-11eb-8017-795d5a7a9f7c.png)

**Comment by MwumLi** [comment]
I can't change it, because that `vue/cli-plugin-babel` call `loadPartialConfig ()`, you can see the issue description above.
And,  https://github.com/babel/babel/blob/v7.12.1/packages/babel-core/src/config/partial.js#L73-L81  has modifed, only not publish to npm
