### ISSUE TITLE
Class inheritance with closure compiler

### ISSUE THREAD

**Issue by ffxsolutions** [babel/babel#1220]
I can not use closure compiler in this compiled code:
```js
// Child.js
var Child = (function (_Parent) {
	/* some other compiled code here */
	/*...*/
	_createClass(Child, [{
		key: 'foo',
		value: function foo(param) {
			_get(Object.getPrototypeOf(Child.prototype), 'bar', this).call(this, param);
		}
	}]);
	return Child;
})(Parent);
// other file
var child = new Child();
child.foo('hello'); //foo will be obfuscated by closure
// I can use this to make it works by use key value:
child.['foo']('hello'); // but I don't want this.
```
Is there any config like push _propertyLiterals in blacklist to get what i want?

**Comment by eventualbuddha** [comment]
I don't believe it'd be wise to run closure compiler with advanced optimizations on the output of babel. There's just no way it'll be able to understand the code enough to make those optimizations safe.

Really it'd be better to run it before babel, if it properly understood ES6. Another option is to use loose mode and don't use any features that closure compiler doesn't understand, like getters and setters (I think).

**Comment by ffxsolutions** [comment]
Yes, I have my old product with simply prototype inherits, it works fine with every things.
When I saw the React's support of es6 class, and the type checker in Flowtype.org. I was impressed with all of that, so I decided to do some converting to new version..

But I think we can change a little in the compiler

**Comment by sebmck** [comment]
Yeah this usage isn't supported. In 4.x the output of Babel could have been passed through the Closure compiler with advanced minification turned on but as of 5.x you can't as the classes helpers were reduced.

**Comment by soul-wos-vn** [comment]
Hi, I go through this by enable loose mode config {loose: 'all'} in the babel transformer. It will use simple prototype inheritance and 'Making your code faster (but less spec-compliant)' http://babeljs.io/docs/usage/loose/
