### ISSUE TITLE
What happened to the `format` option?

### ISSUE THREAD

**Issue by Naddiseo** [babel/babel#1221]
From the change log I can see that the `format` option was removed, but I can't find what, if anything, replaced it.

**Comment by sebmck** [comment]
Only remaining options are `comments` and `compact` which has been moved to the root options, everything else is irrelevant because it's inherited. See the [options docs](http://babeljs.io/docs/usage/options/#options) for more info.

Also as per the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and future requests.

Thanks!
