### ISSUE TITLE
Await is not a reserved keyword in loose mode

### ISSUE THREAD

**Issue by sguillia** [babel/babel#12228]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

main.js

```js
let await = 42
console.log(await)
```

```
$ node main.js
42

$ babel main.js
SyntaxError: babel-await-repro/main.js: Can not use keyword 'await' outside an async function (1:4)
```

`await` is not a reserved keyword

- https://github.com/sguillia/babel-await-repro

**Input Code**

See above

**Expected behavior**

Does not crash, and prints the following

```js
let await = 42
console.log(await)
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

n/a

**Environment**

```
  System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.4.0/bin/npm
```
- How you are using Babel: cli and loader (also reproduces with loaders)

**Possible Solution**

Update list of reserved keywords

**Additional context**

https://stackoverflow.com/questions/55934490/why-are-await-and-async-valid-variable-names

**Comment by JLHwung** [comment]
By default, Babel assumes [`sourceType`](https://babel.dev/docs/en/options#sourcetype) is "module", thus it throws because module code is always strict and `await` can not be an identifier name outside of async function in strict mode. You can specify `sourceType: "script"` in babel config.

**Comment by sguillia** [comment]
Thank you
