### ISSUE TITLE
Iterating over a range the ES6 way?

### ISSUE THREAD

**Issue by jsg2021** [babel/babel#1223]
My colleague asked me why didn't this work:
```
for (let i of 7){
  console.log(i);
}
```
or ```console.log([...7])```

The first doesn't work only because 7[Symbol.iterator] isn't defined. no big deal. But that left me wondering what is the proper way? has it solidified?

**Comment by sebmck** [comment]
There isn't. Also as per the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and future requests.

Thanks!

**Comment by jsg2021** [comment]
thanks! sorry :}

**Comment by zloirock** [comment]
@jsg2021 you can use full version `core-js` with [`Number` iterator](https://github.com/zloirock/core-js#number) instead of `core-js/shim` from `babel/polyfill`, but it not in the spec and is not planned.
