### ISSUE TITLE
Combination of `preset-env` and `preset-flow` presets causes the `BABEL_TRANSFORM_ERROR` error.

### ISSUE THREAD

**Issue by miherlosev** [babel/babel#12261]
![image](https://user-images.githubusercontent.com/4133518/97264381-e76dd400-1835-11eb-99a2-889a91f105df.png)

Node.js/npm versions: 12.19.0/6.14.8
Babel version: ^7.12.3

OS: Window 10 Enterprice

[Example.zip](https://github.com/babel/babel/files/5443330/example.zip) to reproduce. 

Steps to reproduce: 
* download and unpack archive. 
* install modules (`npm i`).
* run the `node compile.js` command in the terminal

**Comment by existentialism** [comment]
Since your config uses `passPerPreset`, you'll want to run `preset-flow` _before_ `preset-env`.

Are you sure you need `passPerPreset`?

**Comment by miherlosev** [comment]
Yes, you are right. I removed the `passPerPreset` option, and it works fine.
So, the issue is resolved.
