### ISSUE TITLE
Get Incorrect position information from the AST node(await) with @babel/parser 7.11.5

### ISSUE THREAD

**Issue by liuliangsir** [babel/babel#12284]
## Bug Report

**Current behavior**

- [AST explorer](https://astexplorer.net/#/gist/ef9d907e68594bb4763d85915881d3e2/36373f74d799f8e3e0d570b296ce9c5b9c0e4f3a)

**Input Code**

```js
async function foobar() {
  await ac.sysDialogOn({
    content: `wwwwww`,
    id: 2330,
    hasRoleName: true,
    hasBg: false,
    hasRoleAvatar: true,
    roleName: `角色名`,
    roleAvatarResId: '$262638',
  });
}
```

**Expected behavior**
Give correct position information. In this example, the end column should be 7, which is as follows:
```js
  loc: {
    start: {
      line: 2,
      column: 2,
    },
    end: {
      line: 10,
      column: 7,
    },
  }
```

**Comment by nicolo-ribaudo** [comment]
On line 10 column 7 there is nothing in your input code. The last token of AwaitExpression is the `)`, which is on column 4.

**Comment by liuliangsir** [comment]
Oh, it's my fault. I'll close the issue above.
