### ISSUE TITLE
Add `caller` option for enabling top level await parsing

### ISSUE THREAD

**Issue by SimenB** [babel/babel#12292]
## Feature Request

- [ ] I would like to work on this feature!

I'm working on native ESM support in Jest, and we currently tell people to [disable Babel](https://jestjs.io/docs/en/ecmascript-modules) in order to use it (as it's somewhat clunky to configure babel for ESM unless you're familiar with it). I'd really like for `babel-jest` to work as seemingly as possible so people don't know it's there.

**Is your feature request related to a problem?**

Jest already sends in `supportsDynamicImport` and `supportsStaticESM` in the `caller` object, so we're very close to have `@babel/preset-env` automatically do the correct thing when used with default config. TLA seems like a thing a "runtime" can tell Babel it supports similar to `import()` and `import from`. In Jest's case TLA will work if Node supports it (i.e. `node@>=14.3.0`) and the ESM `vm` APIs are available (`--experimental-vm-modules`) is passed. Both of these things are trivial for us to check and pass in via the `caller` option.

**Describe the solution you'd like**

Ergh, see above 😅 

**Describe alternatives you've considered**.

Telling people to enable the syntax plugin if they want to use TLA. Which is probably fine as well, but automagic support would be even nicer 🙂 

**Documentation, Adoption, Migration Strategy**

This is something Jest would pass in, so the user wouldn't have to do anything. I suppose webpack (if they support it) etc could do that via `babel-loader` as well.

**Comment by SimenB** [comment]
Well, then...

https://github.com/babel/babel/blob/95fcb3e16c8d08bc4ff2980c4b53fa2506948774/packages/babel-preset-env/src/index.js#L221-L223

😅

**Comment by SimenB** [comment]
I'm unable to get it to work, tho...

![image](https://user-images.githubusercontent.com/1404810/97764959-a533e380-1b10-11eb-83a8-e3d450c4f239.png)

Logging what is passed to `@babel/core`'s `transformSync` at the bottom - from what I can understand that should be enough? Or maybe it only works for `preset-env` and not `core` in general? If yes - can that be changed? Or is that dependent on it becoming stage 4?

**Comment by SimenB** [comment]
An alternative is of course that `@babel/jest` adds the syntax plugin ourselves if the option is passed.

**Comment by JLHwung** [comment]
Yes we only enable stage 4 syntax features in the parser. Before that please add the syntax plugin if you requires TLA.￼

**Comment by SimenB** [comment]
Yeah, makes sense. I think we can add it to https://github.com/nicolo-ribaudo/babel-preset-current-node-syntax/, but Babel core makes sense to stick to stage 4. Thanks!
