### ISSUE TITLE
[Bug] when `ThisExpression` marked as `Purish`, deadcode plugin will remove arrowy function plugin build result

### ISSUE THREAD

**Issue by SoloJiang** [babel/babel#12306]
## Bug Report

@babel/types @7.12.5:
This [pr](https://github.com/babel/babel/pull/12251/files) marked `ThisExpression` as `Purish`, it will cause `babel-plugin-minify-dead-code-elimination` removes `@babel/plugin-transform-arrow-functions` compiled result.
For example:
```js
<div onClick={() => {
  this.a = 1;
} }></div>
```
It will be transformed by `@babel/plugin-transform-arrow-functions`:
```js
var _this = this
<div onClick={function() {
  _this.a = 1;
} }></div>
```
After this pr, it will be transformed as:
```js
<div onClick={function() {
  this.a = 1;
} }></div>
```
So, the `this` will be `undefined`.

**Comment by huangjian008** [comment]
so, @babel/types version I go back to 7.12.1 to temp solve this problem

**Comment by xqin** [comment]
Please revoke this version!!!!

**Comment by salvoravida** [comment]
please fix it!!

you are breaking CI builds!!!!!

**Comment by xqin** [comment]
can we publish new version `v7.12.6` as soon as possible?

**Comment by nicolo-ribaudo** [comment]
I'll release once CI on `main` finishes

**Comment by nicolo-ribaudo** [comment]
Publishes as `@babel/types@7.12.6`!
