### ISSUE TITLE
React constant elements conflict with ...rest handling

### ISSUE THREAD

**Issue by caroqliu** [babel/babel#12303]
## Bug Report

`Illegal variable reference before declaration` error surfaces when using `...rest` props destructure and React constant elements.

**Current behavior**

- [REPL](https://babeljs.io/repl/#?browsers=safari%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAMTnAFAbziKBnAUygEEAnUuAdzwBpEA6R0gvKAXwEpFMAoRRZlBCkkIQgFkCAWwx9-idFwC8APkQAeACYwAbohz4iZCtSXZchEuSp42AehU05_ANoHLxmwF05HANw8bDw8oJCwCIgAQgCGpOgADhTxeFy8_AA2RNzO-hZG1tRO8gxMLFBybIhKiIlwyQH8gsKiEtKyxYpValq6uYZWJnhm7vmD9o45bnkD3r4BbEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.12.1%2C%40babel%2Fplugin-syntax-jsx%407.12.1)

**Input Code**

```js
function Foo({outsetArrows, ...rest}) {
  return useMemo(
    () => <div outsetArrows={outsetArrows}/>,
    [outsetArrows]
  );
}
```

**Output Code**
```js
function Foo(_ref) {
  var _ref2 = <div outsetArrows={outsetArrows} />; // Illegal variable reference before declaration 

  let {
    outsetArrows
  } = _ref,
      rest = _objectWithoutProperties(_ref, ["outsetArrows"]);

  return useMemo(() => _ref2, [outsetArrows]);
}
```

**Expected behavior**

Should behave the same as if the `props` were destructured inside the function body:
```js
function Bar(props) {
  let {
    outsetArrows,
    ...rest
  } = props;
  return useMemo(
    () => <div outsetArrows={outsetArrows}/>,
    [outsetArrows]
  );
}
```

**Additional context**

The above examples have the same output without use of `...rest`: [REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAMTnAFAbziKBnAUygEEAnUuAdzwF8BKRTAKEUVKJFKREIFkCAthhatE6BgF4AfIgA8AExgA3RDnxEyFahOy5CJclVoB6KQBoRrANpr9mowF0RdANxMaTJqEiwEiAEIAhqToAA4UoXgMzKwANkSMlqp6GobUIjSIEojhcJFurOxQnNx8gsKiYpIyCsrJ6gZaeDq2qU00phaVNimNjs5uNEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.12.1)

**Comment by arifiq** [comment]
@caroqliu Please provide more detail, when i checked it is working fine.

**Comment by JLHwung** [comment]
@arifiq This Bug can be reproduced in the REPL link provided by OP.

**Comment by caroqliu** [comment]
Yes, specifically this portion from the [above REPL](https://babeljs.io/repl/#?browsers=safari%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAMTnAFAbziKBnAUygEEAnUuAdzwBpEA6R0gvKAXwEpFMAoRRZlBCkkIQgFkCAWwx9-idFwC8APkQAeACYwAbohz4iZCtSXZchEuSp42AehU05_ANoHLxmwF05HANw8bDw8oJCwCIgAQgCGpOgADhTxeFy8_AA2RNzO-hZG1tRO8gxMLFBybIhKiIlwyQH8gsKiEtKyxYpValq6uYZWJnhm7vmD9o45bnkD3r4BbEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.12.1%2C%40babel%2Fplugin-syntax-jsx%407.12.1):

```
function Foo(_ref) {
  var _ref2 = <div outsetArrows={outsetArrows} />;

  let {
    outsetArrows
  } = _ref,
      rest = _objectWithoutProperties(_ref, ["outsetArrows"]);

  return useMemo(() => _ref2, [outsetArrows]);
}
```

Note that `outsetArrows` is referenced prior to declaration.

**Comment by arifiq** [comment]
i want to take a look on this

**Comment by nicolo-ribaudo** [comment]
Thanks, it's your!
