### ISSUE TITLE
t.arrowFunctionExpression not accepting arguments listed in documentation

### ISSUE THREAD

**Issue by deificx** [babel/babel#12319]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

I want to generate an arrow function with a `returnType`, but before getting that far (in listing arguments) it seems to fail after adding 3.

**Input Code**

```js
const t = require("@babel/types");
const body = t.blockStatement([t.returnStatement(t.booleanLiteral(true))]);
const fn = t.arrowFunctionExpression([], body, false, false);
```

**Result**

```
Error: ArrowFunctionExpression: Too many arguments passed. Received 4 but can receive no more than 3
    at builder (node_modules/@babel/types/lib/builders/builder.js:21:11)
    at Object.arrowFunctionExpression (node_modules/@babel/types/lib/builders/generated/index.js:470:31)
    at Object.<anonymous> (index.js:3:14)
```

**Expected behavior**

I would expect to be able to pass the arguments listed [in the documentation](https://babeljs.io/docs/en/babel-types#arrowfunctionexpression).

**Environment**

- Babel version(s): `"@babel/types": "^7.12.6"`
- Node/npm version: `v14.9.0`

Not sure more details are needed here

**Possible Solution**

I started digging a bit in the code

- The function is being [generated using a builder](https://github.com/babel/babel/blob/main/packages/babel-types/src/builders/generated/index.js#L221)
- This looks like where it [throws the error](https://github.com/babel/babel/blob/0641a15030565e7f47ef0c5ff25f36264c182b11/packages/babel-types/src/builders/builder.js#L10-L12)
- I guess it has some info in `BUILDER_KEYS[type]`, but I can't tell how that is [being populated](https://github.com/babel/babel/blob/0641a15030565e7f47ef0c5ff25f36264c182b11/packages/babel-types/src/definitions/utils.js#L310)

So I'm a bit stuck.

**Comment by JLHwung** [comment]
The documentation you refers to is the shape of the returned AST node, while the signature have only three arguments

> t.arrowFunctionExpression(params, body, async)

Will be appreciated you can improve the babel types docs a bit.

**Comment by nicolo-ribaudo** [comment]
Closing since the docs already specify only three parameters.
