### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by getify** [babel/babel#1231]
IIRC, this may already be tracked in another bug, but I couldn't find it. So apologies if dupe.

--------

This kind of thing is strange and misleading:

![screen shot 2015-04-11 at 5 56 05 pm](https://cloud.githubusercontent.com/assets/150330/7103416/5a865e58-e074-11e4-881d-fd6e47800938.png)

`null` and `undefined` are definitely not the same value. ;-)

**Comment by sebmck** [comment]
Kyle, please see the README.

> For documentation and website issues please visit the [babel.github.io](https://github.com/babel/babel.github.io) repo.

You already reported this **exact** issue in #968 and it's being tracked at babel/babel.github.io#172.
