### ISSUE TITLE
Invalid sourcemaps even without any AST changes

### ISSUE THREAD

**Issue by mischnic** [babel/babel#12312]
## Bug Report

- [x] I would like to work on a fix or @DeMoorJasper might want to

**Current behavior**
This script parses a file and then stringifies the AST again without changing it:
```js
const fs = require("fs");
const parse = require("@babel/parser").parse;
const generate = require("@babel/generator").default;

let inputCode = fs.readFileSync("index.js", "utf8");

let ast = parse(inputCode, { sourceFilename: "index.js" });

let { code: outputCode, map: outputMap } = generate(
	ast,
	{ sourceMaps: true },
	{ "index.js": inputCode }
);

fs.writeFileSync(
	"babel/index.js",
	outputCode + "\n//# sourceMappingURL=index.js.map"
);
fs.writeFileSync("babel/index.js.map", JSON.stringify(outputMap));
```

The bracket after the call arguments is mapped to the start of the line (just like `console`):
<img width="732" alt="Bildschirmfoto 2020-11-05 um 11 59 23" src="https://user-images.githubusercontent.com/4586894/98233120-d40de780-1f5e-11eb-9969-c06a046f65d6.png">

**Input Code**

```js


console.log("Other!");
```

**Expected behavior**

For example Rollup's output:

<img width="700" alt="Bildschirmfoto 2020-11-05 um 12 01 35" src="https://user-images.githubusercontent.com/4586894/98232981-a7f26680-1f5e-11eb-9f81-92d016b0094c.png">

**Environment**

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.12.3 => 7.12.3
    @babel/generator: ^7.12.5 => 7.12.5
    @babel/parser: ^7.12.5 => 7.12.5
```

**Possible solution**

It looks like characters that don't have their own AST node (e.g. brackets) just use the location of their parent node (CallExpression), without accounting for any child nodes that might be between the start of the parent and the character (the callee or the arguments).

**Additional context**
This might cause invalid sourcemaps with Parcel (after passing Babel's output to other tools).

Repo containing script & artifacts for Babel and Rollup: https://github.com/mischnic/parcel-invalid-sourcemaps

**Comment by mischnic** [comment]
Looks like this is related to this function resetting the position after the argument is printed:
https://github.com/babel/babel/blob/32279147e6a69411035dd6c43dc819d668c74466/packages/babel-generator/src/buffer.js#L270-L305

**Comment by liuxingbaoyu** [comment]
fixed in https://github.com/babel/babel/pull/14967
