### ISSUE TITLE
Cannot find module '@babel/eslint-plugin-plugin-proposal-optional-chaining'

### ISSUE THREAD

**Issue by rajeevsi** [babel/babel#12324]
## Bug Report

Error: Failed to load plugin '@babel/plugin-proposal-optional-chaining' declared in 'package.json': Cannot find module '@babel/eslint-plugin-plugin-proposal-optional-chaining'

**Comment by nicolo-ribaudo** [comment]
You are using a Babel plugin as if it was an ESLint plugin.

Please move it from `.eslintrc.js` to `babel.config.js`

**Comment by nicolo-ribaudo** [comment]
You are using a Babel plugin as if it was an ESLint plugin. Please move it to your Babel config.
