### ISSUE TITLE
Why does Babel think Safari 12 and 12.1 don't support template literals?

### ISSUE THREAD

**Issue by joshgoebel** [babel/babel#12325]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

When using `"safari": "12"` with Babel all my template literals are transformed into `concat`.  It seems because the ruleset has the cut-off listed as "13".

https://github.com/babel/babel/blob/0641a15030565e7f47ef0c5ff25f36264c182b11/packages/babel-compat-data/data/plugins.json#L167-L172

I was told (https://github.com/babel/babel/commit/83fc3f26236a91bf21c6dcea93e56d9a351597ad#r43941797)

> When bugfixes: true is provided, preset-env will use the plugin-bugfixes.json to determine whether any plugin should be applied. It will be the new default for Babel 8.

But don't completely understand this... Why is the value in `bugfixes` 9 vs 13 in `plugins`?  Still from where I'm sitting it seems if template literals are fully supported on 12 or 12.1 that the value of 13 in `plugins.json` would indeed be incorrect.  Am I missing sometning?

**Expected behavior**

I expect the template literals to not be transformed - but instead be left as native code when `safari` is set to `12` or `12.1`.   From what I can see Safari has supported template literals since version 9.  I'm told there are bugs with v9 (and I see 12 has a tiny caveat - with tagged template literals, not template literals in general)... but it seems then that the proper value here would be either "12" or "12.1".  Again, I'm speaking about template literals only, not tagged templates which I realize are different and have a few caveats.

**Babel Configuration**

- Filename: `babel.config.js`

```js
{
"presets": [
  [
  "@babel/env",
    {
      "targets": {
        "edge": "79",
        "firefox": "60",
        "chrome": "67",
        "safari": "12",
        "node": "12.0"
        }
      }
    ]
  ]
}
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 14.8.0 - ~/.brew/bin/node
    Yarn: 1.22.4 - ~/.brew/bin/yarn
    npm: 6.14.8 - ~/.brew/bin/npm
  npmPackages:
    @babel/core: ^7.12.3 => 7.12.3
    @babel/preset-env: ^7.12.1 => 7.12.1
    eslint: ^7.12.1 => 7.12.1
```

- Monorepo: [?]
- How you are using Babel: via rollup-babel

**Possible Solution**

Update the mapping tables to show that Safari 12 (or 12.1) supports template literals.

**Comment by existentialism** [comment]
> But don't completely understand this... Why is the value in bugfixes 9 vs 13 in plugins? Still from where I'm sitting it seems if template literals are fully supported on 12 or 12.1 that the value of 13 in plugins.json would indeed be incorrect. Am I missing sometning?

As @nicolo-ribaudo mentioned in his reply, this is correct. The value is `13` in `plugins` because, as you can see on `compat-table`, Saf12/12.1 do _not_ have full support for template literals. However, with the `bugfixes` option, we apply a fix that allows support down to version `9`.

**Comment by JLHwung** [comment]
See also https://github.com/babel/babel/commit/83fc3f26236a91bf21c6dcea93e56d9a351597ad#r43943668 for why Safari 12/12.1 does not fully support template literals.

**Comment by joshgoebel** [comment]
OMG, thanks so much for such detail and amazing answers.  OK, I get it now.  One last question if I may:

Let's say I don't care about this equality/GC behavior at all (and that does seem to be the only issue) - our project only uses template literals as syntactic sugar for string concatenation. Is there an easy (or not so easy) way I can explicitly manually override the "transform-template-literals" and tell it that for my project it should act as if the setting was "12" (or lower) not "13"?

**Comment by JLHwung** [comment]
You can exclude a plugin if you think it is unnecessary: https://babeljs.io/docs/en/babel-preset-env#exclude
```json
["@babel/preset-env", { "exclude": ["@babel/plugin-transform-template-literals"] }]
```

**Comment by nicolo-ribaudo** [comment]
Btw, I suggest enabling the `bugfixes: true` option to compile less things (it will leave normal template literals uncompiled).

**Comment by joshgoebel** [comment]
@JLHwung That's awesome. :-)

I'm confused what the intention of `bugfixes` is though... Why does saying "bugfixs true/enabled" actually compile LESS actual bugfixes?  Semantically it doesn't make sense to me...

**Comment by nicolo-ribaudo** [comment]
`bugfixes: true` means "fix bugs in a feature rather than just not using that feature" (i.e. template literals).

**Comment by existentialism** [comment]
@joshgoebel as @nicolo-ribaudo mentioned, think of it as an option to "apply bugfixes". it compiles less, because after the bugfixes are applied the minimum version drops (in this case from 13 to 9). Would love for suggestions on how to improve the docs to make it more clear!

**Comment by joshgoebel** [comment]
Ok, I'm getting a crash course to the amazing Babel tools. :-)    Your web GUI is awesome.   It's all crystal clear now. :-)  We wouldn't need either the rewrite or the bugfix in our usage of course, but yes the bugfix version is much nicer and I understand the flag now. :-)

Thanks!

**Comment by joshgoebel** [comment]
>  Would love for suggestions on how to improve the docs to make it more clear!

Where can I find `bugfixes` in the docs and I'll take a look.

**Comment by existentialism** [comment]
@joshgoebel https://babeljs.io/docs/en/babel-preset-env#bugfixes

**Comment by joshgoebel** [comment]
I think that's reasonably clear. :)
