### ISSUE TITLE
runtime option without core-js

### ISSUE THREAD

**Issue by BerkeleyTrue** [babel/babel#1233]
Is it possible to use the runtime while not aliases core features? 

Essentially I want to only use babel helper functions from the babel-runtime package but using the runtime option alias Map to the Core.js Map version.

**Comment by sebmck** [comment]
Not at this time. Another option is the [external helpers](http://babeljs.io/docs/usage/external-helpers/). Also note that in the next release that the runtime transformer will only import what it needs so it should be relatively compact, see #1206.

Also as per the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!
