### ISSUE TITLE
TypeScript type guards are broken since 7.10.0

### ISSUE THREAD

**Issue by gilbsgilbs** [babel/babel#12336]
## Bug Report

- [x] I would like to work on a fix!

I'd like to work on a fix, however I haven't been able to figure out what exactly caused this regression yet. I'd appreciate som help.

**Current behavior**

- TypeScript type guards seems broken since 7.10.0.

**Input Code**

```typescript
function babelStuff(nodePath: NodePath) {
  if (nodePath.isMemberExpression()) {
    // nodePath is "NodePath<Node> & NodePath<MemberExpression>"
    const obj = nodePath.get('object');
    // Here, obj should be "NodePath<Expression>" but is now "NodePath<Node> | NodePath<Node>[]"
    // As a consequence, doing this errors: "Property 'isIdentifier' does not exist on type 'NodePath<Node> | NodePath<Node>[]'"
    if (!obj.isIdentifier()) {
      console.log("obj is identifier");
    }
  }
}
```

**Expected behavior**

Above code should not produce typescript errors.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    ["@babel/preset-env", {"targets": {"node": "current"}}],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ]
}
```

**Environment**

```
npx: installed 1 in 1.295s

  System:
    OS: Linux 5.9 Arch Linux
  Binaries:
    Node: 15.1.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  npmPackages:
    @babel/cli: ^7.12.1 => 7.12.1 
    @babel/core: ^7.12.3 => 7.12.3 
    @babel/types: ^7.12.6 => 7.12.6 
```
- Babel version(s): v7.10.0-v7.12.1
- Node/npm version: 15.1.0
- OS: Arch
- Monorepo: no
- How you are using Babel: plugin

**Possible Solution**

Not sure :thinking: .

**Additional context**

I rely on this type guard pattern quite a lot for [babel-plugin-i18next-extract](https://github.com/gilbsgilbs/babel-plugin-i18next-extract/pull/174/files). This issue prevents me from upgrading dependencies which is quite annoying. I have no idea what caused it and what is a proper solution.

**Comment by nicolo-ribaudo** [comment]
We only maintain TS type definitions for `@babel/types`, everything else is at https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by gilbsgilbs** [comment]
Thanks @nicolo-ribaudo .

**Comment by nicolo-ribaudo** [comment]
Btw, we are starting to migrate the repo to TS so one day we'll provide official type definitions!
