### ISSUE TITLE
`assertions` property is always array when `importAssertions` parser plugin is enabled

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#12343]
## Bug Report

- [x] I would like to work on a fix!

If this behaviour is intentional, I want to know the reason.

**Current behavior**

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAMwhRUIjgIgHQHokTYBWAzhAHaYDcAUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cstage-3&prettier=false&targets=&version=7.12.3&externalPlugins=)

`assertions` property of `ImportDeclaration` (and other nodes for import/export) is empty array when `assert` does not exist if  `importAssertions` parser plugin is enabled.

<details><summary>AST</summary><div>

```json
{
  "type": "ImportDeclaration",
  "start": 0,
  "end": 28,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 1,
      "column": 28
    }
  },
  "specifiers": [
    {
      "type": "ImportDefaultSpecifier",
      "start": 7,
      "end": 10,
      "loc": {
        "start": {
          "line": 1,
          "column": 7
        },
        "end": {
          "line": 1,
          "column": 10
        }
      },
      "local": {
        "type": "Identifier",
        "start": 7,
        "end": 10,
        "loc": {
          "start": {
            "line": 1,
            "column": 7
          },
          "end": {
            "line": 1,
            "column": 10
          },
          "identifierName": "foo"
        },
        "name": "foo"
      }
    }
  ],
  "source": {
    "type": "StringLiteral",
    "start": 16,
    "end": 28,
    "loc": {
      "start": {
        "line": 1,
        "column": 16
      },
      "end": {
        "line": 1,
        "column": 28
      }
    },
    "extra": {
      "rawValue": "./foo.json",
      "raw": "\"./foo.json\""
    },
    "value": "./foo.json"
  },
  "assertions": []
}
```

</div></details>

**Input Code**

```js
import foo from "./foo.json";
```

**Expected behavior**

The `assertions` property should be undefined if the assert does not exist, even if the `importAssertions` plugin is enabled.

We want to distinguish between `import foo from ". /foo.json"` and `import foo from "foo.json" assert {}`.

<details><summary>AST</summary><div>

```diff
{
  "type": "ImportDeclaration",
  "start": 0,
  "end": 28,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 1,
      "column": 28
    }
  },
  "specifiers": [
    {
      "type": "ImportDefaultSpecifier",
      "start": 7,
      "end": 10,
      "loc": {
        "start": {
          "line": 1,
          "column": 7
        },
        "end": {
          "line": 1,
          "column": 10
        }
      },
      "local": {
        "type": "Identifier",
        "start": 7,
        "end": 10,
        "loc": {
          "start": {
            "line": 1,
            "column": 7
          },
          "end": {
            "line": 1,
            "column": 10
          },
          "identifierName": "foo"
        },
        "name": "foo"
      }
    }
  ],
  "source": {
    "type": "StringLiteral",
    "start": 16,
    "end": 28,
    "loc": {
      "start": {
        "line": 1,
        "column": 16
      },
      "end": {
        "line": 1,
        "column": 28
      }
    },
    "extra": {
      "rawValue": "./foo.json",
      "raw": "\"./foo.json\""
    },
    "value": "./foo.json"
  },
-  "assertions": []
}
```

</div></details>

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const { parse } = require("@babel/parser");

parse(`import foo from "./foo.json"`, {
  sourceType: "module",
  plugins: ["importAssertions"],
});
```

**Environment**

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
I think that this is similar to how `new Foo` and `new Foo()` have the same AST, even if one has the call parens and the other doesn't.

**Comment by nicolo-ribaudo** [comment]
Also
```js
import {} from "foo";
import "foo";
```
both have an empty `specifiers` array.

**Comment by JLHwung** [comment]
This is expected. It aligns to the ESTree spec: https://github.com/estree/estree/blob/master/experimental/import-assertions.md

**Comment by sosukesuzuki** [comment]
I see. It would be nice to be able to distinguish them for Prettier, but I got it.  We'll try it with tokens.

**Comment by nicolo-ribaudo** [comment]
Out of curiosity, how does prettier distinguish the `import {} from "foo"` vs `import "foo"` cases?

**Comment by sosukesuzuki** [comment]
Regex for original text https://github.com/prettier/prettier/blob/b5aab4006d689be1fc1514bd6b056d54524b9e11/src/language-js/printer-estree.js#L878-L880

**Comment by JLHwung** [comment]
@sosukesuzuki We could develop a `prettier` parser plugin that tries to differentiate these cases but eventually prettier should work on a CST to preserve/format styles.

**Comment by sosukesuzuki** [comment]
It's a bit off topic, I found a bug like this because the regex can't detect comments:smile: https://github.com/prettier/prettier/issues/9645
