### ISSUE TITLE
Async functions doesn't throws exceptions.

### ISSUE THREAD

**Issue by asdf404** [babel/babel#1234]
Hi. Async function doesn't throws exceptions.

```js
async function run() {
  throw new Error();
  return 1;
}

run();
```

Outups nothing.

I ran this code with `babel-node --stage 0 ./async-test.js`. Version of `babel` is 5.0.12.

**Comment by sebmck** [comment]
Yes, that's the entire point of async functions. They return an `Promise` that you then attach a handler to:

```javascript
run().then(function (val) {

}, function (err) {

});
```

or:

```javascript
run().catch(function (err) {

});
```

**Comment by asdf404** [comment]
Ok. Thanks
