### ISSUE TITLE
Remove `Noop` node from `@babel/types`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#12355]
We should have [removed it in Babel 7](https://github.com/babel/babel/pull/5970), but it's still there:
https://github.com/babel/babel/blob/3e0fa927c09183b0ef9a280b4258f8db673085fc/packages/babel-types/src/definitions/misc.js#L9-L11

It's not used anywhere in our code.

**Comment by sidntrivedi012** [comment]
Hey @nicolo-ribaudo , please assign this to me. Would love to work on it. 🙂

**Comment by nicolo-ribaudo** [comment]
Sure! Remember to target the `next-8-dev` branch.

(I noticed CI is failing there, I'll take a look later today)
