### ISSUE TITLE
babel-parser allows trailing comma inside import(...) arguments with importAssertions

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#12358]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

[REPL link](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgFAIgGYQggNAAgN6ZgTzAFMAuTBAKwGcIA7BAX3QEoBuAKCA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=env%2Cstage-3&prettier=false&targets=&version=7.12.3&externalPlugins=)

No syntax error is thrown.

**Input Code**

```js
import("foo", { type: "json" },);
```

**Expected behavior**

Syntax error `Trailing comma is disallowed inside import(...) arguments ` should be thrown.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const { parse } = require("@babel/parser");

parse(`import("foo", { type: "json" },);`, { plugins: ["importAssertions"] });
```

**Environment**

**Possible Solution**

**Additional context**

**Comment by JLHwung** [comment]
As a feature, the Import Assertions allows trailing comma in arguments: https://tc39.es/proposal-import-assertions/#prod-ImportCall.

**Comment by sosukesuzuki** [comment]
I didn't know! It seems intentional. Thank you.

Out of curiosity, why trailing comma is needed there?

**Comment by JLHwung** [comment]
It's for consistency with call expression. When trailing comma was allowed, the `import()` proposal did not catch up, so we added back, as a feature, in the import assertions proposal.
