### ISSUE TITLE
Class function cannot be named 'declare' and be generic 

### ISSUE THREAD

**Issue by damacisaac** [babel/babel#12353]
**I'm submitting a bug report**

**Webpack Version:**
4.41.5

**Babel Core Version**:
7.7.2

**Babel Loader Version**:
8.0.6

**Please tell us about your environment:**
OSX 10.15.5

**Current behavior:**
```
SyntaxError:
Unexpected token (38:9)

  36 |   }
  37 | 
> 38 |   declare<T extends any>(arg: T): T {
     |          ^
  39 |     return arg;
  40 |   }
  41 | 
```

**Expected/desired behavior:**
Class functions can have the name `declare` and be generic without causing a syntax error. Note that it needs to be inside a class to be reproduced.

**Comment by nicolo-ribaudo** [comment]
Demo: https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1oBMCmowCcMB4AVAPgAoBKRAXySqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=env%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.12.3&externalPlugins=

**Comment by sosukesuzuki** [comment]
Note: This happens for `abstract` and `readonly`.  [abstract demo](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1pgEYQC4CczCwB4AVAPgAoBKRAXyRqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=env%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.12.3&externalPlugins=), [readonly demo](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1oCcCmYAmB7AdiAJ4A8AKgHwAUAlIgL5L1A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=false&presets=env%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.12.3&externalPlugins=)
