### ISSUE TITLE
Cannot export an immediately instantiated class

### ISSUE THREAD

**Issue by nesk** [babel/babel#1236]
This code doesn't work:

```js
export new class {
    // ...
}
```

However, I can't manage to find in the specification if this should be authorized or not… Maybe Babel's behaviour is justified?

**Comment by sebmck** [comment]
The grammar doesn't allow it.

**Comment by loganfsmyth** [comment]
@nesk To clarify @sebmck 's comment, `export` is used for named exports, and your example has not provided a name. Perhaps you are looking for one of these.


1. Export it as the default export, which doesn't need a name:
    ```
    export default new class {
    }
    ```

2. Export it with a name
    ```
    export const Name = new class {
    }
    ```

Feel free to ask questions in the [Gitter chat room](https://gitter.im/babel/babel) if you'd like clarification.

**Comment by nesk** [comment]
Ah! Thank you for the clarifications! Indeed, I was looking for the default export, since Babel doesn't require it to be specified I didn't add it to my code.
