### ISSUE TITLE
core-js 3 missing .js extension when 'type': 'module'

### ISSUE THREAD

**Issue by bytestream** [babel/babel#12378]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

`'type': 'module'` is used in `package.json` and when `corejs: 3` is specified in `babel.config.js` webpack complains about missing `.js` extension despite it existing in `src/page.js`. If I comment out `corejs: 3` then the error goes away.

```
ERROR in ./src/page.js 1:0-37
Module not found: Error: Can't resolve 'core-js/modules/es.weak-set' in '/home/kieran/PhpstormProjects/babel-test/src'
Did you mean 'es.weak-set.js'?
BREAKING CHANGE: The request 'core-js/modules/es.weak-set' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

I would be incredibly grateful if someone could put me out my misery.

**Input Code**

https://github.com/bytestream/babel-test

**Expected behavior**

I expect the code to transpile when using corejs 3.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
    presets: [
        [
            '@babel/preset-env',
            {
                'useBuiltIns': 'entry',
                'corejs': 3, // <--- problematic line
            }
        ]
    ],
    plugins: [
        // Don't allow polyfills to pollute global namespace.
        '@babel/plugin-transform-runtime',
        // Support for the experimental syntax 'classPrivateProperties'
        '@babel/plugin-proposal-class-properties',
        // Support for the experimental syntax 'classPrivateMethods'
        '@babel/plugin-proposal-private-methods',
    ]
};
```

**Environment**

```
$ npx envinfo --preset babel

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  npmPackages:
    @babel/core: ^7.12.3 => 7.12.3 
    @babel/plugin-proposal-class-properties: ^7.12.1 => 7.12.1 
    @babel/plugin-proposal-private-methods: ^7.12.1 => 7.12.1 
    @babel/plugin-transform-runtime: ^7.12.1 => 7.12.1 
    @babel/preset-env: ^7.12.1 => 7.12.1 
    @babel/runtime-corejs3: ^7.12.5 => 7.12.5 
    babel-loader: ^8.2.1 => 8.2.1 
    webpack: ^5.6.0 => 5.6.0 
```

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/10862

**Comment by bytestream** [comment]
Thank you for the fast reply @nicolo-ribaudo 

Is there a workaround until that's merged?

**Comment by nicolo-ribaudo** [comment]
You could try using https://github.com/tleunen/babel-plugin-module-resolver to add the `.js` extension to `core-js` imports.

**Comment by pongstylin** [comment]
I've tried to use the recommended workaround without success.  Has anybody else had success with it?  Here's my .babelrc file.  It is effective at changing other resolve paths when I change what I match against, so the plugin does seem to be doing stuff.  It just doesn't seem to catch the problematic imports.
`{
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "^core-js/modules/(.+)$": "core-js/modules/\\1.js"
        }
      }
    ]
  ]
}
`

**Comment by bytestream** [comment]
No it didn't work for me either. I removed the code that required corejs polyfill 😅

**Comment by RamboHunterJb** [comment]
,please save my build .. bcoz i just use android 8 😂Dihantar daripada Galaxy saya
-------- Mesej asal --------Daripada: Kieran <notifications@github.com> Tarikh: 28/11/20  4:54 PM  (GMT+08:00) Kepada: babel/babel <babel@noreply.github.com> Sk: Subscribed <subscribed@noreply.github.com> Subjek: Re: [babel/babel] core-js 3 missing .js extension when 'type': 'module' (#12378) 

No it didn't work for me either. I removed the code that required corejs polyfill 😅

**Comment by eugeneoshepkov** [comment]
Having the same issue in my configuration. `babel-plugin-module-resolver` didn't help since most of `node_modules` packages are not transpiled, making that alias config above useless

**Comment by RamboHunterJb** [comment]
Dihantar daripada Galaxy saya

**Comment by RamboHunterJb** [comment]
Gmail - [GitHub status]_ Webhook problem detectedValid until: 16 Nov 2020https://linksharing.samsungcloud.com/kVk59vnIwcQIsudo !!Dihantar daripada Galaxy saya

**Comment by RamboHunterJb** [comment]
Saya menggunakan Gboard untuk menaip dalam Melayu (Latin) (Malaysia) (QWERTY) dan Inggeris (UK) (QWERTY). Anda boleh mencuba ciri ini di: https://gboard.app.goo.gl/p3P5yDihantar daripada Galaxy saya
