### ISSUE TITLE
Documentation still refers to --experimental

### ISSUE THREAD

**Issue by warrenseine** [babel/babel#1237]
Hi,

The documentation for babel-node on the site is outdated and still refers to `--experimental`, which has been removed in 5.0+. The replacement should be `--stage=0` (but detail wouldn't hurt).

Regards,
Warren.

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by warrenseine** [comment]
My bad.
