### ISSUE TITLE
SyntaxError: unknown: 'with' in strict mode

### ISSUE THREAD

**Issue by gogo9th** [babel/babel#12385]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

SyntaxError: unknown: 'with' in strict mode (1:27)

**Input Code**

```
const babel = require('@babel/core');

var code = 'function f(foo, values) {  with (foo) {   }  }'

var res = babel.transform(code, {
   retainLines: true,
   compact: false,
   presets: ['@babel/preset-env'],
   plugins: [
    ["@babel/plugin-transform-modules-commonjs", { "strictMode": false }]
  ]
}).code;
```

**Expected behavior**

The instrumentation should succeed.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
None
```

**Environment**

```
None
```

- Babel version(s): 7.0.0
- Node/npm version: 15.2.0
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: No
- How you are using Babel: I used the above code

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
`"strictMode": false` doesn't tell Babel that your input code is in not strict mode, but that you don't want the output code to be in strict mode.

You can pass `sourceType: "script"` to parser your input file as a `script`, which are in non-strict mode.

**Comment by gogo9th** [comment]
Thanks for the solution. This works well.

I have one more question.. I also need to instrument the contents of <script type='module> tags. This tag's contents should be treated as module, not script, right? Then is it that there will be cases that we get a transformation error when we give the sourceType: 'script' option for this?

**Comment by nicolo-ribaudo** [comment]
Yes, for `<script type='module'>` you should use `sourceType: "module"`. However, `with` is a syntax error inside `<script type='module'>` so it shouldn't be a problem (Babel will throw for `with` inside `modules`, but the browser would throw anyway).

**Comment by gogo9th** [comment]
Got it, thanks man. I'm sorry, but I have a final question. I tried to transpile NodeJS files with the `sourceType: "script"` option, and the transpiled program seems to run okay. So I think changing the `sourceType: "module"` option to `sourceType: "script"` won't cause a transpiled program to crash which didn't before. Is my assumption correct? I need to ensure this because I'm gonna run experiments on a very big test corpus..

**Comment by nicolo-ribaudo** [comment]
Well, if you are using `import` or `export` it's going to crash, because they are only allowed in modules.

You could use `sourceType: "unambiguous"`, which means "if there are `import`/`export` it's `sourceType: "unambiguous"`, otherwise it's `sourceType: "module"`.

I think that this will work in 99.9% of the cases (there are some differences between modules and scripts, but usually the problem is only when going from `script` to `module`).

**Comment by gogo9th** [comment]
I think you meant:

You could use` sourceType: "unambiguous"`, which means "if there are `import/export` it's `sourceType: "module"`, otherwise it's `sourceType: "script"`. This does solve the problem perfectly. Thanks a lot!
