### ISSUE TITLE
Bumping @babel/preset-env from 7.12.1 to 7.12.7 breaks tests (jest)

### ISSUE THREAD

**Issue by wachunei** [babel/babel#12393]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Bumping @babel/preset-env from 7.12.1 to 7.12.7 breaks tests

- Dependabot PR: https://github.com/wachunei/directUC/pull/162 
- Tests run: https://github.com/wachunei/directUC/pull/162/checks?check_run_id=1448125840

Nullish coalescing and optional chaining operator are not parsed anymore.

**Input Code**

Example:
```js
const getElement = container => container?.firstChild;
```

**Expected behavior**

To transform correctly

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `package.json#babel`

```json
  "babel": {
    "presets": [
      "@babel/preset-env",
      [
        "@babel/preset-react",
        {
          "runtime": "automatic"
        }
      ]
    ]
  }
```

**Environment**

```
  System:
    OS: macOS 11.0.1
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  npmPackages:
    @babel/core: ^7.12.8 => 7.12.8
    @babel/preset-env: ^7.12.7 => 7.12.7
    @babel/preset-react: ^7.12.7 => 7.12.7
    babel-jest: ^26.6.3 => 26.6.3
    eslint: ^7.14.0 => 7.14.0
    jest: ^26.6.3 => 26.6.3
```

**Possible Solution**

- Maybe enabling these features is required in the babel config but I would not expect that since it works before bumping patch version.
- Maybe babel-jest is ignoring babel config

**Additional context**

**Comment by nicolo-ribaudo** [comment]
This should be fixed by https://github.com/babel/babel/pull/12391!
I'm trying to write a proper test case, hopefully we'll release it by today.

**Comment by wachunei** [comment]
> This should be fixed by #12391!
> I'm trying to write a proper test case, hopefully we'll release it by today.

Hello @nicolo-ribaudo, sounds good, can we leave this open until release, bump and test pass? I can take care of closing it once that happens (hopefully 🤞)

**Comment by nicolo-ribaudo** [comment]
Sure!

**Comment by JLHwung** [comment]
I don't think it is related to #12391.

The test in https://github.com/wachunei/directUC/pull/162 fails because Babel does not transpile `??` and `?.` given that the the target browsers

https://github.com/wachunei/directUC/blob/d3fe4c06cc940acef0c691d24cc34d5c0afabf95/package.json#L115-L120

have native `??` and `?.` support, but the Jest tests is run on Node.js 12 https://github.com/wachunei/directUC/blob/develop/.github/workflows/checks.yml#L11 which doesn't.

You can either specify a different preset-env targets for Jest tests, or run tests on Node.js 14 which has native support.

**Comment by wachunei** [comment]
That totally makes sense, but how is it explained that it worked before then?

**Comment by JLHwung** [comment]
> but how is it explained that it worked before then?

Because what `last N versions` resolves to is determined by `caniuse-lite`, which is indirectly bumped in #12241.

> How can I add { targets: { node: true } } to preset-env options when process.env.NODE_ENV is test, but using package.json#babel config?

You can create a `.browserslistrc` on your project root

```
[production]
last 5 Chrome versions
# and other targets

[test]
current node
```

**Comment by wachunei** [comment]
I did not use environment keys in my `package.json@browserslist` config because it was not being picked up correctly by parcel@v1. I resolved to upgrade to use node 14 for development. Thank you for the help.
