### ISSUE TITLE
numeric: keep hex numeric

### ISSUE THREAD

**Issue by fundon** [babel/babel#1239]
I have codes and do not want to transform it to decimal numeric.

```js
const a = 0x2A;
```

will be transformed to:

```js
const a = 42;
```

**Comment by sebmck** [comment]
There's no way to disable it since they're represented identically in the AST. I don't know why you'd want to disable it anyway since they're identical.

**Comment by fundon** [comment]
@sebmck http://jsperf.com/hex-vs-decimal

**Comment by sebmck** [comment]
![screen shot 2015-04-12 at 8 57 03 am](https://cloud.githubusercontent.com/assets/853712/7106340/e790c040-e0f1-11e4-8fc8-762ed6162880.png)


That difference is extremely minute and once you take into account the million things your computer could have been doing while it was doing that to fudge them then it's insignificant.

**Comment by fundon** [comment]
Okay, agreed. :)
