### ISSUE TITLE
Array destructuring assignment works unexpectedly

### ISSUE THREAD

**Issue by ipy** [babel/babel#1241]
[arr[i-1],arr[i]]=[arr[i],arr[i-1]];

is transformed to:

    "use strict";

    var _temp;

    var _slicedToArray = function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } };

    _temp = [arr[i], arr[i - 1]];

    var _temp2 = _slicedToArray(_temp, 2);

    arr[i - 1] = _temp2[0];
    arr[i] = _temp2[1];

Let `arr = [1, 2, 3]` and `i = 1`, then result is `arr = [2, 1, 3]`. I think it should be the right result.
However, if I add the assignment to the source file:

    var arr = [1,2,3], i = 1;
    [arr[i-1],arr[i]]=[arr[i],arr[i-1]];
    console.log(arr); // should be [2, 1, 3]

It is transformed to

    "use strict";
  
    var arr = [1, 2, 3],
        i = 1;
    arr[i - 1] = arr[i];
    arr[i] = arr[i - 1];
  
    console.log(arr); // result is [2, 2, 3]

`arr[1]` is overwrited.

**Comment by sebmck** [comment]
Fixed as of 5.1.0, thanks!
