### ISSUE TITLE
The node type SpreadProperty has been renamed to SpreadElement at Object.isSpreadProperty

### ISSUE THREAD

**Issue by romanown** [babel/babel#12421]
when i using babel-plugin-transform-object-rest-spread after compile saved many errors "The node type SpreadProperty has been renamed to SpreadElement at Object.isSpreadProperty."
babelrc
`"plugins": [
    "babel-plugin-transform-object-rest-spread",
`

package.json have the 
`"babel-plugin-transform-object-rest-spread": "^6.26.0",`

i am updated react from 15.6.0 to 16.13.1

**Comment by nicolo-ribaudo** [comment]
You are likely using Babel 7, so:
- If you re using `@babel/preset-env`, you can just remove that plugin.
- Otherwise, you need to replace it with `@babel/plugin-transform-object-rest-spread`
