### ISSUE TITLE
babel is ignore a file which filename include 'rtmp'

### ISSUE THREAD

**Issue by LiamShao** [babel/babel#12427]
I have a Sequelize migration file like '20201127072449-add_rtmp.js', but when I using command :

>babel --ignore node_modules,public,tmp --loose es6.modules -d ${BABEL_TMP_PATH} . ./bin/${MAIN_JS}.js

I can't see any output info about this file, as well as the file not exist in BABEL_TMP_PATH, but the other files are good, that drives me crazy,  I try to change the file name, when the name not includes 'rtmp' it works! so, 'rtmp' is a keyword or anything?

babel version: 6.26.0 (babel-core 6.26.3)
node version: v8.16.0
npm version: 6.4.1

**Comment by JLHwung** [comment]
Babel 6 is not supported, can you check if this issue can be reproduced on Babel 7?

**Comment by LiamShao** [comment]
> Babel 6 is not supported, can you check if this issue can be reproduced on Babel 7?

Babel 7 didn't reproduced, upgrade is useful, thanks a lot.
