### ISSUE TITLE
Reconsider bailing out with `BABEL_SHOW_CONFIG_FOR`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#12425]
## Bug Report

**Current behavior**

When using `BABEL_SHOW_CONFIG_FOR`, the file for which Babel is logging the config is considered as ignored and it's not compiled/handled: https://github.com/babel/babel/blob/cb30c1dd54fd09f05045b5094ff9d038604768b3/packages/babel-core/src/config/config-chain.js#L266

However, all the other files are still compiled. This means that if my build script is `babel src -d out`, if I have two files (`src/main.js` and `src/dep.js`) and I run
```
BABEL_SHOW_CONFIG_FOR=./src/main.js npm run build
```

I will get an `out` folder containing only the `dep.js` file.

If you want to see this behavior, you can clone https://github.com/nicolo-ribaudo/babel-bug-show-config-behavior and run `BABEL_SHOW_CONFIG_FOR=./src/main.js npm run build`.

**Expected behavior**

Either Babel should compile everything, or nothing.

I think the best thing to do would be to still compile the file, so that `BABEL_SHOW_CONFIG_FOR` only has effect on logging and on nothing else. However, I would be open to ignoring everything.

**Additional context**

Thanks @laurieontech for the feedback!

**Comment by laurieontech** [comment]
Thanks for taking the time to write it up! This would be more intuitive behavior in my mind.
