### ISSUE TITLE
Throw better error message when `await` is not used in async functions in errorRecovery mode

### ISSUE THREAD

**Issue by fisker** [babel/babel#12436]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

```js
require('@babel/parser').parse('function foo () {await bar();}', {sourceType: 'module', errorRecovery: true})
Uncaught [SyntaxError: Unexpected token, expected ";" (1:23)
] {
  loc: Position { line: 1, column: 23 },
  pos: 23
}
```

Should throw an error with better message.

**Input Code**

```js
function foo () {await bar();}
```

**Expected behavior**

Mabe like this, when `errorRecovery: false`

```js
require('@babel/parser').parse('function foo () {await bar();}', {sourceType: 'module'})
Uncaught [SyntaxError: 'await' is only allowed within async functions (1:17)
] {
  loc: Position { line: 1, column: 17 },
  pos: 17
}
```

The error message is much better.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Through API, without config

**Environment**

```
- Babel version(s): v7.12.7
- Node/npm version: Node 14/npm 6
- OS: Windows 10
- Monorepo: no
- How you are using Babel: api

```

**Possible Solution**

I have no idea

**Additional context**

Issue on Prettier https://github.com/prettier/prettier/issues/9799 and https://github.com/prettier/prettier/issues/9084

**Comment by nicolo-ribaudo** [comment]
When improving this error, we should be careful since
```js
function foo () {
  await
  bar();
}
```
is valid code.

**Comment by sosukesuzuki** [comment]
This happens for `yield` too.

```js
require('@babel/parser').parse('function foo () { yield bar();}', {sourceType: 'module', errorRecovery: true })
```

```
SyntaxError: Unexpected token, expected ";" (1:24)
```
