### ISSUE TITLE
Plugins@5.1: Transformer foo is resolving to a different Babel version ...

### ISSUE THREAD

**Issue by deepsweet** [babel/babel#1244]
```
test/node_modules/babel-core/lib/babel/transformation/transformer.js:97
      throw new TypeError("Transformer " + this.key + " is resolving to a diff
            ^
TypeError: Transformer foo is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (test/node_modules/babel-core/lib/babel/transformation/transformer.js:97:13)
    at File.addPlugin (test/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:287:48)
    at File.buildTransformers (test/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:215:12)
    at new File (test/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:88:10)
    at Object.transform (test/node_modules/babel/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at Object.exports.transform (test/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (test/node_modules/babel/bin/babel/util.js:41:18)
    at test/node_modules/babel/bin/babel/file.js:112:25
    at arrayEach (test/node_modules/babel/node_modules/lodash/index.js:1342:13)
    at Function.<anonymous> (test/node_modules/babel/node_modules/lodash/index.js:3299:13)
```

there is no npm links and any kind of locally installed babel. simple downgrading to babel*@5.0 with the same code works fine. am I missing some breaking changes about this?

**Comment by deepsweet** [comment]
looks like instance of Transformer is not satisfies [this](https://github.com/babel/babel/blob/master/src/babel/transformation/transformer.js#L73) anymore. from [Plugins docs](https://babeljs.io/docs/usage/plugins/#visitor-overview):

```js
import { Transformer, types as t } from "babel-core";

export default new Transformer("foo", {
    FunctionDeclaration(node, parent) {}
});
```

**Comment by sebmck** [comment]
This isn't a Babel issue. You need to ensure that the same instance of `babel-core` resolves to the plugin. Whether this is updating your local babel instance or clearing your npm cache and reinstalling it.

**Comment by deepsweet** [comment]
it can't be the same instance of babel-core because:
1. babel itself depends on babel-core
2. plugin itself depends on babel-core
3. npm will not automatically flatten deps tree w/o peerDeps until v3

so:
```
$ mkdir tmp/ && cd tmp/

$ npm i babel babel-plugin-example

$ npm ls babel-core
tmp
├─┬ babel@5.1.8
│ └── babel-core@5.1.8
└─┬ babel-plugin-example@1.0.0
  └── babel-core@5.1.8
```

and then:
```
$ echo "let a = function() {}" > script.js

$ babel script.js
"use strict";

var a = function a() {};

$ babel --plugins example script.js
tmp/node_modules/babel-plugin-example/node_modules/babel-core/lib/babel/transformation/transformer.js:97
      throw new TypeError("Transformer " + this.key + " is resolving to a diff
            ^
TypeError: Transformer plugin-example is resolving to a different Babel version to what is doing the actual transformation...
    at Transformer.buildPass (tmp/node_modules/babel-plugin-example/node_modules/babel-core/lib/babel/transformation/transformer.js:97:13)
    at File.addPlugin (tmp/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:287:48)
    at File.buildTransformers (tmp/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:215:12)
    at new File (tmp/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:88:10)
    at Object.transform (tmp/node_modules/babel/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at Object.exports.transform (tmp/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (tmp/node_modules/babel/bin/babel/util.js:41:18)
    at tmp/node_modules/babel/bin/babel/file.js:112:25
    at arrayEach (tmp/node_modules/babel/node_modules/lodash/index.js:1342:13)
    at Function.<anonymous> (tmp/node_modules/babel/node_modules/lodash/index.js:3299:13)
```

and again, it somehow works with babel*@5.0...

**Comment by terinjokes** [comment]
Can you force npm to flatten the tree with `npm dedupe`?

**Comment by deepsweet** [comment]
nope:

```
$ npm ls babel-core
tmp
├─┬ babel@5.1.8
│ └── babel-core@5.1.8
└─┬ babel-plugin-example@1.0.0
  └── babel-core@5.1.8

$ npm dedupe

$ npm ls babel-core
tmp
├─┬ babel@5.1.8
│ └── babel-core@5.1.8
└─┬ babel-plugin-example@1.0.0
  └── babel-core@5.1.8
```

```
npm --version
2.8.1
```

maybe dedupe is looking for (missed) package.json or something. anyway, even if it worked, we should stuck with peerDeps (until npm@3?) to let npm flatten the tree. or... is it really necessary to have the same instance of babel-core? I mean that I slightly misunderstood this `is resolving to a different Babel version` error.

**Comment by terinjokes** [comment]
@deepsweet i setup a basic package.json (below) and ran `npm install` followed by `npm dedupe` and only had one `babel-core`.

```
babel-temp/› cat package.json
{
  "dependencies": {
    "babel": "^5.0.0",
    "babel-plugin-example": "^1.0.0"
  }
}

babel-temp/› npm install
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data

> fsevents@0.3.5 install /Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
babel-plugin-example@1.0.0 node_modules/babel-plugin-example
└── babel-core@5.1.8 (slash@1.0.0, trim-right@1.0.0, path-is-absolute@1.0.0, shebang-regex@1.0.0, to-fast-properties@1.0.1, fs-readdir-recursive@0.1.1, leven@1.0.1, strip-json-comments@1.0.2, user-home@1.1.1, private@0.1.6, globals@6.4.1, estraverse@3.1.0, esutils@2.0.2, convert-source-map@1.0.0, js-tokens@1.0.0, line-numbers@0.2.0, is-integer@1.0.4, debug@2.1.3, ast-types@0.7.6, detect-indent@3.0.1, chalk@1.0.0, output-file-sync@1.1.0, repeating@1.1.2, minimatch@2.0.4, source-map-support@0.2.10, source-map@0.4.2, regexpu@1.1.2, regenerator@0.8.21, lodash@3.6.0, core-js@0.8.3)

babel@5.1.8 node_modules/babel
├── path-is-absolute@1.0.0
├── fs-readdir-recursive@0.1.1
├── convert-source-map@0.5.1
├── commander@2.7.1 (graceful-readlink@1.0.1)
├── source-map@0.4.2 (amdefine@0.1.0)
├── output-file-sync@1.1.0 (xtend@4.0.0, mkdirp@0.5.0)
├── lodash@3.6.0
├── chokidar@1.0.1 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.0, readdirp@1.3.0, anymatch@1.2.1, fsevents@0.3.5)
└── babel-core@5.1.8 (slash@1.0.0, shebang-regex@1.0.0, to-fast-properties@1.0.1, trim-right@1.0.0, leven@1.0.1, strip-json-comments@1.0.2, user-home@1.1.1, private@0.1.6, globals@6.4.1, estraverse@3.1.0, esutils@2.0.2, convert-source-map@1.0.0, line-numbers@0.2.0, is-integer@1.0.4, js-tokens@1.0.0, debug@2.1.3, chalk@1.0.0, detect-indent@3.0.1, ast-types@0.7.6, repeating@1.1.2, minimatch@2.0.4, source-map-support@0.2.10, regexpu@1.1.2, regenerator@0.8.21, core-js@0.8.3)

babel-temp/› npm ls babel-core
@ /Users/terin/Development/babel-temp
├─┬ babel@5.1.8
│ └── babel-core@5.1.8
└─┬ babel-plugin-example@1.0.0
  └── babel-core@5.1.8


babel-temp/› npm dedupe
npm WARN unavoidable conflict chalk { '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/regex-cache/node_modules/benchmarked/node_modules/chalk': '1.0.0',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/regex-cache/node_modules/chalk': '0.5.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict micromatch { '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch': '2.1.5',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/regex-cache/node_modules/micromatch': '1.6.2' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict extend-shallow { '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/regex-cache/node_modules/benchmarked/node_modules/extend-shallow': '1.1.2',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/regex-cache/node_modules/benchmarked/node_modules/file-reader/node_modules/extend-shallow': '0.2.0' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict isobject { '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/braces/node_modules/expand-range/node_modules/fill-range/node_modules/isobject': '1.0.0',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/object.omit/node_modules/isobject': '0.2.0' }
npm WARN unavoidable conflict Not de-duplicating
for-own@0.1.3 node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/for-own
└── for-in@0.1.4
babel-core@5.1.8 node_modules/babel-core
├── slash@1.0.0
├── to-fast-properties@1.0.1
├── trim-right@1.0.0
├── path-is-absolute@1.0.0
├── shebang-regex@1.0.0
├── fs-readdir-recursive@0.1.1
├── leven@1.0.1
├── strip-json-comments@1.0.2
├── user-home@1.1.1
├── private@0.1.6
├── globals@6.4.1
├── estraverse@3.1.0
├── esutils@2.0.2
├── convert-source-map@1.0.0
├── js-tokens@1.0.0
├── is-integer@1.0.4 (is-finite@1.0.0, is-nan@1.0.1)
├── line-numbers@0.2.0 (left-pad@0.0.3)
├── ast-types@0.7.6
├── debug@2.1.3 (ms@0.7.0)
├── detect-indent@3.0.1 (get-stdin@4.0.1, minimist@1.1.1)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── output-file-sync@1.1.0 (xtend@4.0.0, mkdirp@0.5.0)
├── minimatch@2.0.4 (brace-expansion@1.1.0)
├── repeating@1.1.2 (is-finite@1.0.0, meow@3.1.0)
├── source-map@0.4.2 (amdefine@0.1.0)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── regexpu@1.1.2 (regjsgen@0.2.0, regenerate@1.2.1, regjsparser@0.1.4, recast@0.10.11)
├── regenerator@0.8.21 (through@2.3.7, esprima-fb@13001.1.0-dev-harmony-fb, recast@0.10.11, commoner@0.10.1, defs@1.1.0)
├── lodash@3.6.0
└── core-js@0.8.3
npm WARN unavoidable conflict commander { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/commander': '2.5.1',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/commander': '2.7.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict convert-source-map { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/convert-source-map': '1.0.0',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/convert-source-map': '0.5.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict source-map { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/source-map': '0.4.2',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/source-map-support/node_modules/source-map': '0.1.32',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/source-map': '0.4.2' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict minimatch { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/minimatch': '2.0.4',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/readdirp/node_modules/minimatch': '0.2.14' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict esprima-fb { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/esprima-fb': '8001.1001.0-dev-harmony-fb',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regenerator/node_modules/esprima-fb': '13001.1.0-dev-harmony-fb' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict graceful-fs { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs': '3.0.6',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs': '2.0.3' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict recast { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regenerator/node_modules/recast': '0.10.11',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/recast': '0.9.18',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/regexpu/node_modules/recast': '0.10.11' }
npm WARN unavoidable conflict Not de-duplicating
is-finite@1.0.0 node_modules/babel-core/node_modules/is-finite
get-stdin@4.0.1 node_modules/babel-core/node_modules/get-stdin
minimist@1.1.1 node_modules/babel-core/node_modules/minimist
path-is-absolute@1.0.0 node_modules/path-is-absolute
fs-readdir-recursive@0.1.1 node_modules/fs-readdir-recursive
output-file-sync@1.1.0 node_modules/output-file-sync
├── xtend@4.0.0
└── mkdirp@0.5.0 (minimist@0.0.8)
lodash@3.6.0 node_modules/lodash
mkdirp@0.5.0 node_modules/mkdirp
└── minimist@0.0.8
npm WARN unavoidable conflict minimist { '/Users/terin/Development/babel-temp/node_modules/babel-core/node_modules/minimist': '1.1.1',
npm WARN unavoidable conflict   '/Users/terin/Development/babel-temp/node_modules/mkdirp/node_modules/minimist': '0.0.8' }
npm WARN unavoidable conflict Not de-duplicating

babel-temp/› npm ls babel-core
@ /Users/terin/Development/babel-temp
└── babel-core@5.1.8


babel-temp/› npm --version
2.8.1
```

**Comment by deepsweet** [comment]
ok, so:

1. babel itself should have babel-core as peerDeps
2. every plugin should have babel-core as peerDeps

to make it work w/o manual deduping. right?

**Comment by terinjokes** [comment]
In npm@3, peer dependencies will no longer be installed automatically, so manual action would then be required. If in a fresh install (there is no "node_modules" directory), an install from npm@3 will automatically dedupe these as modules as they are configured right now.

A simple `npm dedupe` should resolve it here, and a colleague confirms the same output as I.

I can't speak for the necessity of the same module instance being used. I imagine it's important, as sebmck took the time to add in the error.

**Comment by deepsweet** [comment]
imo manual `npm dedupe` can't be a proper solution for this issue.

> so manual action would then be required

no, because npm will automatically flatten (by `dedupe`) your normal deps.
seems like we need to use babel-core both as normal deps and peerDeps right now. or only peerDeps until npm@3 will arrive.

**Comment by jayphelps** [comment]
I'm bitten by this as well. Hopefully a solution exists other than asking consumers to run `npm dedupe` and hope it works. (in my testing, it didn't always, depending on the dep tree)

**Comment by sebmck** [comment]
I'll probably have to change/offer an alternate plugin API although it'll likely have to be pretty gross:

```javascript
export default function (babel) {
  return new babel.Transformer("key", {});
}
```

But then all plugins will initialize themselves completely every single time they're used instead of once :/

**Comment by deepsweet** [comment]
let's start with babel-core as peerDeps? it must work with current npm@2 behaviour.

**Comment by sebmck** [comment]
Actually, I can probably do some magic to get this to _just work_™.

**Comment by deepsweet** [comment]
![](http://funkyimg.com/i/VVJp.jpg)

**Comment by sebmck** [comment]
See attached commit. _Should_ work.

**Comment by deepsweet** [comment]
nope, same error :( index.js is handled, but magic doesn't work.

try it with https://github.com/babel/babel/issues/1244#issuecomment-92589041

**Comment by jayphelps** [comment]
Hey @sebmck can we get this ticket reopened? This is still an issue for me and I assume the others who have chimed in.

**Comment by sebmck** [comment]
@jayphelps The behaviour is intentional. I need to figure out a good strategy to handle this and it's likely just going to be "wait for npm 3 to be released".

**Comment by jayphelps** [comment]
@sebmck Right, I understand it's intentionally needed to work this way, but we can't seem to consume it this way at the moment. I'd just like somewhere that's tracking this issue. Maybe my environment is more screwed up than most, but I can't even get a simple hello world plugin to work without npm depude, which isn't acceptable for consumers.

**Comment by deepsweet** [comment]
but why we can't move babel-core to peerDeps for now? it should work as expected unti npm@3 will arrive.

"wait for npm 3 to be released" is "you can't write your own babel plugin for a months"

**Comment by sebmck** [comment]
cc @terinjokes

On Wednesday, 15 April 2015, Kir Belevich <notifications@github.com> wrote:

> but why we can't move babel-core to peerDeps for now? it should work as
> expected unti npm@3 will arrive.
>
> "wait for npm 3 to be released" is "you can't write your own babel plugin
> for a months"
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1244#issuecomment-93607896>.
>


-- 
Sebastian McKenzie

**Comment by JedWatson** [comment]
My suggestion would be for babel plugins to include `babel-core` as a `peerDependency` and _explain it in their documentation_.

Listing `babel-core` as a `peerDependency` in `babel` itself is unnecessary.

For the workaround to be effective, plugins need to specify the peerDep liberally, so I would suggest something like `>=5.0.0`. This guards against new versions of babel being released without new plugin versions being released (which is always an awkward time). The downside would be if the new version of Babel truly isn't compatible, things will break, but the other option is that the new version _is_ compatible and nobody can `npm install` without it throwing hard errors (IMO the worse of two evils)

So; when installing Babel you don't need to worry about `babel-core` as a project dependency, but for plugins you do. Then the npm dedupe resolution will work as expected on `npm install` and if plugin maintainers are vigilant with new versions it's all good.

Not awesome but it's the most elegant I can come up with until npm@3, and works today.

**Comment by deepsweet** [comment]
most elegant is to move babel-core to peerDeps everywhere (even in babel itself, because it's kind of wrapper), no? :) and npm@2 will solve our problem automatically.

the same approach as with grunt/gulp plugins, karma stuff, webpack loaders and so on.

**Comment by deepsweet** [comment]
@sebmck please re-open this issue to let other people get involved.

**Comment by natew** [comment]
I'm running into this but can't get it to dedupe even with peerdeps because I want to develop a plugin locally. So when you npm link it in, it either gives you the "different versions" error or if you delete the `node_modules/babel-core` in the plugin, it said dependency not met and doesn't run.

Seems like the only way to develop locally is so actually edit your module inside node_modules and then copy/paste it back out, which is really horrible.

Would be good to allow npm link'ed modules to work as well.

cc @deepsweet

**Comment by deepsweet** [comment]
@natew yeah, I developed a plugin exactly that horrible way, inside node_modules :fearful:

**Comment by JedWatson** [comment]
@natew @deepsweet same here. @jossmac @dcousens and I have had _heaps_ of issues with this while developing touchstonejs apps.

Basically `npm link touchstonejs` is unusable as it will _always_ load its own version of React, because of the way node resolves `require` statements and symbolic links. Same here with Babel plugins.

I would argue for a change in node/iojs itself (this isn't even a problem npm could solve in isolation) but I doubt it would go anywhere because of the other cases it would break.

@sebmck perhaps you could expose an optional plugin API we could use for babel plugin development..?

So in plugins:

```
export default function (babel) {
  if (!babel) babel = require('babel-core');
  return new babel.Transformer('key', {});
}
```

while developing a plugin:

```
babel({ plugins: [require('babel-plugin-key')(babel)] });
```

for standard use:

```
babel({ plugins: ['key'] });
```

I implemented a similar technique in KeystoneJS to get around the same problem using mongoose; by default Keystone will set `keystone.mongoose = require('mongoose')` and it's _usually_ the mongoose installed into the project.

But if you're using `npm link keystone` for development, you can use `keystone.connect(mongoose)` to override it with your project's instance (you need to do this just after requiring keystone the first time). Then all use of mongoose in Keystone refers to `this.mongoose` instead of `require('mongoose')`.

It ain't pretty, but it works, and the hack is limited to keystone development or edge cases rather than general use.

**Comment by deepsweet** [comment]
@sebmck sorry, but I must be annoying because I want to use custom babel plugins :smirk_cat:

**Comment by sebmck** [comment]
@deepsweet Stop harassing me please. I said I was still thinking of a good way to handle this since once it's implemented there's no going back. In fact I already have with 9cb16711dda17d1e53c975cd117d70b2c381e422, I just need to write tests. If this **really** bothered you then there's no reason you couldn't have done a PR. Sorry for the alarmist tone, it's just extremely irritating.

**Comment by sebmck** [comment]
Just released 5.2.0 that lets you export plugins as a function that's called with the `babel` instance. I've also updated the [docs](http://babeljs.io/docs/usage/plugins) to reflect this and removed the use of ES6 syntax in the plugin examples as it was pretty confusing.

**Comment by timbur** [comment]
The Gods are smiling upon me lately.  The past few times I've needed some solution/fix for some library, I google it and it's been fixed less than 10 hours prior.  xD  Pretty cutting edge stuff, I guess.  I like it.

@sebmck You da man.

With that said, I seem to be running into another issue: #1402

**Comment by jayphelps** [comment]
@sebmck HUGE THANK YOU! (I have yet to test, but solution looks like it solves issue IMO)
