### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by inovramadani** [babel/babel#12463]
## Bug Report

**Current behavior**
I faced intricate issue I think it's related to babel, posted on SOF: https://stackoverflow.com/questions/65164157/set-up-testing-library-react-with-mocha-got-syntaxerror-unexpected-token

Please clone this repo: https://github.com/inovramadani/babel-bug
And then run `npm test`
Should get this error:
```
import Button from './button';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Expected behavior**
Should be able to run the test smoothly and not getting any error.

**Environment**
Tried on 3 different OS-es and 3 different npm and node versions, got same error. So I think has nothing to do with the environment.

**Comment by inovramadani** [comment]
hi @babel-bot, the sign up link is expired:  
![image](https://user-images.githubusercontent.com/27492820/101605019-41b4a400-3a34-11eb-9782-f2e3540a620a.png)

**Comment by nicolo-ribaudo** [comment]
You need to add `"sourceType": "module"` to your Babel config.
