### ISSUE TITLE
regeneratorRuntime is not defined with async/await in Gulp Babel

### ISSUE THREAD

**Issue by sts-ryan-holton** [babel/babel#12464]
I'm using Gulp 4.0.2 and have set up my environment to use `async/await` functions. I've tried suggestions such as https://github.com/babel/babel/issues/8829#issuecomment-456524916 to get async/await to work but continue to get the following error:

> regeneratorRuntime is not defined

I've got installed...

```
"@babel/core": "7.12.3"
"@babel/preset-env": "7.12.1"
"@babel/runtime": "^7.12.5"
"@babel/plugin-transform-runtime": "^7.12.1"
```

See attached code...

```javascript
/ build the Icicle Client Plugin
gulp.task('build-honeycomb-icicle-client-js', () =>
  gulp.src([
    'src/js/plugins/honeycomb-icicle-client.js'
  ])
  .pipe(concat('honeycomb-icicle-client.js'))
  .pipe(babel({
    presets: [['@babel/env', { modules: false }]],
    plugins: [['@babel/transform-runtime', { regenerator: true }]]
  }))
  .pipe(minify())
  .pipe(gulp.dest('src/assets/js/'))
);
```

What's wrong here?

**Comment by nicolo-ribaudo** [comment]
What's the full stack trace? What is the output generated by Babel?

**Comment by sts-ryan-holton** [comment]
@nicolo-ribaudo Where abouts what I find that? Nothing is logged to my gulp watcher, it's just the error in the browser...

```
honeycomb-plugins.js?v=1607519457578279000:514 Uncaught ReferenceError: regeneratorRuntime is not defined
    at _saveHashBetweenDomains (honeycomb-plugins.js?v=1607519457578279000:514)
    at saveHashBetweenDomains (honeycomb-plugins.js?v=1607519457578279000:510)
    at new HoneycombIcicle (honeycomb-plugins.js?v=1607519457578279000:542)
    at honeycomb-core.js?v=1607519457578279000:966
```

**Comment by JLHwung** [comment]
@sts-ryan-holton `@babel/transform-runtime` will inject imports of `regeneratorRuntime` to `src/js/plugins/honeycomb-icicle-client.js` like this
```
const regeneratorRuntime = require("regenerator-runtime") 
```
It seems that you are not using a bundler to pack the `regenerator-runtime` library to your artifacts. You can try concatenating the source of `regenerator-runtime`.

**Comment by sts-ryan-holton** [comment]
@JLHwung I'm pretty sure I am utilising the runtime, see attached:

```javascript
gulp.task('build-honeycomb-icicle-client-js', () =>
  gulp.src([
    'src/js/plugins/honeycomb-icicle-client.js'
  ])
  .pipe(concat('honeycomb-icicle-client.js'))
  .pipe(babel({
    presets: [['@babel/env', { modules: false }]],
    plugins: [['@babel/transform-runtime', { regenerator: true }]]
  }))
  .pipe(minify())
  .pipe(gulp.dest('src/assets/js/'))
);
```

But this still does not work.

**Comment by nicolo-ribaudo** [comment]
The "regeneratorRuntime is not defined" error comes from the `honeycomb-plugins.js` file, but in that `gulp` config you are only compiling `honeycomb-icicle-client.js`.

**Comment by JLHwung** [comment]
Closing this issue as we didn't hear from OP, assuming the issue resolved. Feel free to reopen if it is not.
