### ISSUE TITLE
helper-compliation-targets merges desktop and mobile browsers

### ISSUE THREAD

**Issue by brendo** [babel/babel#12472]
## Bug Report

- [x] I would like to work on a fix!

`@babel/helper-compliation-targets` is used by `@babel/preset-env` to transform the browsers/targets property into a list that can be actioned. In this process, it appears that `and_chr` and `and_ff` will be resolved to just `chrome` or `firefox` which results in the wrong targets being resolved.

**Current Behaviour**

```
last 1 firefoxandroid versions
last 3 firefox versions
```

results in the following output when using the debug flag:

```
Using targets:
{
  "firefox": "81"
}

Using modules transform: false

Using plugins:
  syntax-numeric-separator { "firefox":"81" }
  syntax-nullish-coalescing-operator { "firefox":"81" }
  syntax-optional-chaining { "firefox":"81" }
  syntax-json-strings { "firefox":"81" }
  syntax-optional-catch-binding { "firefox":"81" }
  syntax-async-generators { "firefox":"81" }
  syntax-object-rest-spread { "firefox":"81" }
  syntax-dynamic-import { "firefox":"81" }
  syntax-export-namespace-from { "firefox":"81" }
  syntax-top-level-await { "firefox":"81" }
```

**Expected Behaviour**

```
last 1 firefoxandroid versions
last 3 firefox versions
```

resolves to a target of:

```
{
  "firefox": "81",
  "firefox android": "83"
}
```

**Possible Solution**

Update the [`browserNameMap`](https://github.com/babel/babel/blob/main/packages/babel-helper-compilation-targets/src/targets.js#L5-L20) to give distinction to mobile versions. For example if I change it to be:

```
and_ff: "firefox android",
```

Then my resulting output from running `@babel/preset-env` with the debug flag is correct:

```
Using targets:
{
  "firefox": "81",
  "firefox android": "83"
}

Using modules transform: false

Using plugins:
  proposal-numeric-separator { "firefox android":"83" }
  proposal-logical-assignment-operators { "firefox android":"83" }
  proposal-nullish-coalescing-operator { "firefox android":"83" }
  proposal-optional-chaining { "firefox android":"83" }
  proposal-json-strings { "firefox android":"83" }
  proposal-optional-catch-binding { "firefox android":"83" }
  transform-parameters { "firefox android":"83" }
  proposal-async-generator-functions { "firefox android":"83" }
  proposal-object-rest-spread { "firefox android":"83" }
  transform-dotall-regex { "firefox android":"83" }
  proposal-unicode-property-regex { "firefox android":"83" }
  transform-named-capturing-groups-regex { "firefox android":"83" }
  transform-async-to-generator { "firefox android":"83" }
  transform-exponentiation-operator { "firefox android":"83" }
  transform-template-literals { "firefox android":"83" }
  transform-literals { "firefox android":"83" }
  transform-function-name { "firefox android":"83" }
  transform-arrow-functions { "firefox android":"83" }
  transform-block-scoped-functions { "firefox android":"83" }
  transform-classes { "firefox android":"83" }
  transform-object-super { "firefox android":"83" }
  transform-shorthand-properties { "firefox android":"83" }
  transform-duplicate-keys { "firefox android":"83" }
  transform-computed-properties { "firefox android":"83" }
  transform-for-of { "firefox android":"83" }
  transform-sticky-regex { "firefox android":"83" }
  transform-unicode-escapes { "firefox android":"83" }
  transform-unicode-regex { "firefox android":"83" }
  transform-spread { "firefox android":"83" }
  transform-destructuring { "firefox android":"83" }
  transform-block-scoping { "firefox android":"83" }
  transform-typeof-symbol { "firefox android":"83" }
  transform-new-target { "firefox android":"83" }
  transform-regenerator { "firefox android":"83" }
  transform-member-expression-literals { "firefox android":"83" }
  transform-property-literals { "firefox android":"83" }
  transform-reserved-words { "firefox android":"83" }
  proposal-export-namespace-from { "firefox android":"83" }
  syntax-dynamic-import { "firefox":"81", "firefox android":"83" }
  syntax-top-level-await { "firefox":"81", "firefox android":"83" }
```

**Additional context**

Given a browserslist of:

```
last 1 firefoxandroid versions
last 3 firefox versions
```

This resolves to (when using the `debug` flag of `@babel/preset-env`) to:

```
Using targets:
{
  "firefox": "81"
}

Using modules transform: false

Using plugins:
  syntax-numeric-separator { "firefox":"81" }
  syntax-nullish-coalescing-operator { "firefox":"81" }
  syntax-optional-chaining { "firefox":"81" }
  syntax-json-strings { "firefox":"81" }
  syntax-optional-catch-binding { "firefox":"81" }
  syntax-async-generators { "firefox":"81" }
  syntax-object-rest-spread { "firefox":"81" }
  syntax-dynamic-import { "firefox":"81" }
  syntax-export-namespace-from { "firefox":"81" }
  syntax-top-level-await { "firefox":"81" }
```

This isn't correct though as it should resolve to Firefox 81, and Firefox Android 83 (at the time of writing).

The issue occurs in the `getLowestVersions` function:

https://github.com/babel/babel/blob/4f3fcf11101d52e9bb27042708080bf5c619e201/packages/babel-helper-compilation-targets/src/index.js#L209-L216

This function attempts to normalize the incoming browser name, and in do so, loses the distinction between the mobile and desktop version. While this function gets the correct browsers:

```
[ 'and_ff 83', 'firefox 83', 'firefox 82', 'firefox 81' ]
```

It loses it once it's normalized:

https://github.com/babel/babel/blob/4f3fcf11101d52e9bb27042708080bf5c619e201/packages/babel-helper-compilation-targets/src/index.js#L74

This is because the targets map will cast `and_ff` to be just `firefox`:

https://github.com/babel/babel/blob/4f3fcf11101d52e9bb27042708080bf5c619e201/packages/babel-helper-compilation-targets/src/targets.js#L7

This also affects `and_chr`, `ie_mob` and `op_mob`.

**Comment by nicolo-ribaudo** [comment]
We don't have data for mobile browsers, so we map them to the corresponding desktop version (which has the same supported features).

**Comment by JLHwung** [comment]
For most engine support information we use `compat-table`, as you can see `compat-table` [does not](https://github.com/kangax/compat-table/blob/gh-pages/environments.json) support `firefox android`. However, MDN maintains engine informations (the most important piece is how we should map the firefox android version to Gecko version) about `firefox android`: https://github.com/mdn/browser-compat-data/blob/master/browsers/firefox_android.json, I will be very appreciate if you can prepare a PR to https://github.com/kangax/compat-table which ports the MDN data to [compat-table](https://github.com/kangax/compat-table/blob/gh-pages/environments.json). After `compat-table` supports Firefox Android, Babel will update `@babel/compat-table` for `android firefox` support.

**Comment by brendo** [comment]
Thanks for the swift responses @nicolo-ribaudo and @JLHwung!

I get what you're saying:

- [Chrome Android](https://github.com/mdn/browser-compat-data/blob/master/browsers/chrome_android.json) mirrors the Chrome version. 
- [Firefox Android](https://github.com/mdn/browser-compat-data/blob/master/browsers/firefox_android.json) mirrors the Firefox version.

I guess the only one that is different potentially is [Opera Android](https://github.com/mdn/browser-compat-data/blob/master/browsers/opera_android.json)? This doesn't seem to match up with the capabilities of [Opera](https://github.com/mdn/browser-compat-data/blob/master/browsers/opera.json). Is Opera Android actually `op_mob`, instead of say `and_mob`?

With that said, I'm a bit confused by the plugins output if I tweak the browser map to be `and_ff: "firefox android",`. Why does it appear to select more plugins for "firefox android 83" than it does for "firefox 81"?

**Comment by JLHwung** [comment]
> I guess the only one that is different potentially is Opera Android?

Yes! The Opera mapping is quite nasty. Babel currently maps `Opera Android -> Opera`, which is not accurate. I will be appreciated if you can port that data to `compat-table`.

> With that said, I'm a bit confused by the plugins output if I tweak the browser map to be and_ff: "firefox android",. Why does it appear to select more plugins for "firefox android 83" than it does for "firefox 81"?

Because babel regards `firefox android` as an unknown browser, so it conservatively applies all transforms.

**Comment by brendo** [comment]
> Because babel regards `firefox android` as an unknown browser, so it conservatively applies all transforms.

Ah! This makes perfect sense. Thank you!

> Yes! The Opera mapping is quite nasty. Babel currently maps `Opera Android -> Opera`, which is not accurate. I will be appreciated if you can port that data to `compat-table`.

I'll give this a go today 👍

**Comment by brendo** [comment]
@JLHwung I gave this a go in https://github.com/kangax/compat-table/pull/1691 🙏

**Comment by JLHwung** [comment]
Closing this issue as the upstream one is resolved.
