### ISSUE TITLE
@babel/plugin-transform-runtime 7.12.10 breaks pnpm monorepo

### ISSUE THREAD

**Issue by johannes-z** [babel/babel#12476]
## Bug Report

**Current behavior**
I updated the `@babel/plugin-transform-runtime` dependency in one of my projects from, which is a pnpm monorepo. Version `7.12.1` was working fine, but `7.12.10` throws an error. I'm guessing this change is breaking: 208acb1d6c216b265fd49b9d393237a45725ff6a

```
[!] Error: Could not load /<ROOT>/node_modules/.pnpm/@babel/runtime@7.12.5/node_modules/@babel/runtime/helpers/esm/objectSpread2 (imported by ../other-package/dist/other-package.esm.js): ENOENT: no such file or directory, open '/<ROOT>/node_modules/.pnpm/@babel/runtime@7.12.5/node_modules/@babel/runtime/helpers/esm/objectSpread2'
```

**Expected behavior**
resolving babel-runtime packages should still work.

**Environment**

```
  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.0/bin/npm
  npmPackages:
    @babel/plugin-transform-runtime: ^7.12.1 => 7.12.10 
    @babel/preset-env: ^7.12.10 => 7.12.10 
    @babel/runtime: ^7.12.5 => 7.12.5 
```
- Babel version(s): (see above)
- Node/npm version: v14
- OS: Ubuntu
- Monorepo: pnpm
- How you are using Babel: rollup

**Additional context**
Reverting to `7.12.1` fixed this issue for me

**Comment by nicolo-ribaudo** [comment]
What is your Babel config? That commit should only affect you if you are using the `absoluteRuntime: true` option of `plugin-transform-runtime`.

**Comment by johannes-z** [comment]
I'm using babel through babel. This is what the plugin config looks like:

```js

const babelDefaults = {
  comments: false,
  babelrc: false,
  configFile: false,
  // vue-runtime-helpers needs to be transpiled
  exclude: /node_modules(?!.*vue-runtime-helpers)/,
  extensions: ['.js', '.jsx', '.ts', '.tsx', '.vue', '.mjs'],
}

...

babel({
  ...babelDefaults,
  babelHelpers: 'bundled',
  presets: [
    '@vue/babel-preset-jsx',
    ['@babel/preset-env', {
      corejs: 3,
      useBuiltIns: 'usage',
      exclude: [
        'es.weak-map.*',
        'es.weak-set.*',
        'esnext.map.*',
        'esnext.set.*',
        'es.set.*',
        'es.map.*',
      ],
    }],
  ],
})
```

pnpm uses symlinks for node_modules, so that's why I assumed that `require.resolve` broke it.

**Comment by nicolo-ribaudo** [comment]
Can you show the full stack trace?

**Comment by johannes-z** [comment]
I set up a small repro, turns out it's not `@babel/plugin-transform-runtime` but `@rollup/plugin-node-resolve` that breaks imports from `@babel/runtime` (ref: https://github.com/rollup/plugins/issues/684). Sorry for the inconvenience!
