### ISSUE TITLE
Runtime does not transform Promise static methods

### ISSUE THREAD

**Issue by mpk** [babel/babel#1248]
Hi,

I'm using the runtime option to automatically include Promise polyfill from core-js, but it seems to work for the Promise constructor only. Static methods (such as Promise.all) are left unchanged, which causes an error in browsers without native Promise support.

For example,
```javascript
var A = new Promise();
Promise.all();
```
is transformed to:
```javascript
var _Promise = require("babel-runtime/core-js/promise")["default"];

var A = new _Promise();
Promise.all(); // Error
```

**Comment by zloirock** [comment]
Also `Reflect`, `Math.hypot`, all `Number` and `String` methods, maybe something else. After #1206

**Comment by sebmck** [comment]
@zloirock There's no `hypot` exposed by the `core-js` library?

**Comment by zloirock** [comment]
@sebmck https://github.com/zloirock/core-js/blob/master/fn/math/hypot.js :)

**Comment by sebmck** [comment]
@zloirock Whoops, I was looking in `number`.

**Comment by sebmck** [comment]
Fixed as of 5.1.3, thanks!

**Comment by zloirock** [comment]
@sebmck also `Reflect` and `Number.EPSILON` (in uppercase).

**Comment by barbalex** [comment]
Hm. What could I be doing wrong? I am using babel v. 5.8.29. And in both projects I use it in `Promise.all` is not transformed and causes a `Promise is undefined` Error in IE11. 

Do I need to tweak any special settings?

**Comment by zloirock** [comment]
@barbalex use [polyfill](https://babeljs.io/docs/usage/polyfill/) / [commonjs `core-js` api](https://github.com/zloirock/core-js#commonjs) if you need only part of polyfills / [`runtime` plugin](http://babeljs.io/docs/plugins/transform-runtime/) if you write a library. For questions use [slack](https://babeljs.slack.com).

**Comment by barbalex** [comment]
@zloirock Thanks A LOT! Somehow I completely missed this. And by the way: That was number one quick answer!
