### ISSUE TITLE
Any way to compile async functions to 'wrapped' generators?

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#1249]
I can blacklist regenerator if I want to leave untransformed generators in my output (e.g. if I'm targeting io.js).

But when I enable the optional transformation `es7.asyncFunctions` in combination with blacklisting regenerator, it doesn't seem to have any effect. The output contains untransformed `async` and `await` keywords, which won't run in io.js. (I'm guessing this is because `es7.asyncFunctions` actually just alters the regenerator config?)

It would be cool if I could use Babel to transform async functions down to a plain generator, wrapped in some kind of 'spawn' function so they work exactly like async functions, like [this suggestion by Jake Archibald](http://jakearchibald.com/2014/es7-async-functions/#until-es7-arrives).

```js
// source
async function () { await foo; }

// could compile to to
spawn(function *() { yield foo; })
```

...where `spawn` is a helper like [this](https://gist.github.com/jakearchibald/31b89cba627924972ad6) or maybe [co](https://github.com/tj/co)?

Then in theory the output of that could be subsequently handled by regenerator on standard settings, for people who didn't blacklist regenerator. (or is there more to it than that?)

**Comment by zloirock** [comment]
See [`asyncToGenerator`](http://babeljs.io/docs/usage/transformers/other/async-to-generator/) or [`bluebirdCoroutines`](http://babeljs.io/docs/usage/transformers/other/bluebird-coroutines/).
