### ISSUE TITLE
File level options support

### ISSUE THREAD

**Issue by wmira** [babel/babel#1250]
Currently we can only pass global options via babelrc or directly via a specific loader. It would be nice to have a way to provide file level options ala how jshint does it. e.g.
```javascript
/* babel blacklist: useStrict */
```
So we can do per specific file. At the moment we need to turn off this feature on all of the generated sources as the old library we are trying to wrap (and getting rid off ) does a caller ref.

**Comment by sebmck** [comment]
I don't want to encourage Babel-specific directives in peoples code.
