### ISSUE TITLE
NPM Install Fails Due To Wrong Version

### ISSUE THREAD

**Issue by vsaravind007** [babel/babel#12515]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

For some reason, running npm install is currently failing with the following error:

**Command Output**

```js
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-validator-identifier@^7.12.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/types'
npm ERR! notarget 
```

**Expected behavior**

NPM install should run correctly.

**Environment**

```
  System:
    OS: Linux 5.3 Ubuntu 18.04.1 LTS (Bionic Beaver)
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
```

**Possible Solution**

**Additional context**

This started failing last day. NPM cache was cleared, issue still persists.

**Comment by midudev** [comment]
I'm getting the same error on Travis CI builds for different projects.

**Installing locally** seems to be working fine with node 12 and node 14 versions.

```
npm install @babel/types
└─┬ @babel/types@7.12.11
  ├── @babel/helper-validator-identifier@7.12.11
  ├── lodash@4.17.20
  └── to-fast-properties@2.0.0
```

PS: Seems my Travis Builds are working again. Maybe something from npm end wasn't working as expected?

**Comment by nicolo-ribaudo** [comment]
The package is correctly published on npm: https://www.npmjs.com/package/@babel/helper-validator-identifier/v/7.12.11

This could a proxy's cache problem, or a problem with the registry itself.
