### ISSUE TITLE
When using corejs: 3、useBuiltIns: 'usage', the packages have extra stuff

### ISSUE THREAD

**Issue by 23cicada** [babel/babel#12518]
webpack:
```
test: /\.js$/,
exclude: /node_modules/,
use: {
loader: 'babel-loader',
options: {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'usage',
        corejs: 3
        }
      ]
    ]
  }
}
```
result:
![image](https://user-images.githubusercontent.com/52289446/102372825-90e17280-3ffa-11eb-9889-9ef4e859e9e6.png)
I don't know if it's normal or if I've configured something wrong
I think Internals is redundant

**Comment by JLHwung** [comment]
This is expected, the `internals` is the internal functions of `core-js`. By default Babel will apply all transforms so as you can see there are polyfills for Promise, consider specify `targets` of your app: https://babeljs.io/docs/en/babel-preset-env#targets

**Comment by nicolo-ribaudo** [comment]
Specifically, you can see that `es.promise.js` depends on many internal helpers: https://unpkg.com/browse/core-js@3.7.0/modules/es.promise.js
