### ISSUE TITLE
usage doc needs update for latest CLI changes

### ISSUE THREAD

**Issue by jeffbski** [babel/babel#1253]
Apparently the CLI options have changed so

https://babeljs.io/docs/usage/cli/

needs to be updated. I don't know of all the recent changes, but I know that `-t` is no longer the way to get inline source maps which is now `-s inline`. There may be other changes too?

**Comment by sebmck** [comment]
Please see the README:

>  For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
