### ISSUE TITLE
[Parser][FlowJs] Expose @babel/parser FlowJs definitions

### ISSUE THREAD

**Issue by moroine** [babel/babel#12543]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem?**
I need to use `@babel/parser` in a project using FlowJs. I found it very frustrating to see `@babel/parser` is written using FlowJs but I can't use definitions within my project.

**Describe the solution you'd like**
Either include `src` in npm file or `src/types.js` with related dependencies

**Comment by liuxingbaoyu** [comment]
Because this isue is out of date, I will close it.
