### ISSUE TITLE
Questionable "Parenthesized left hand expressions are illegal" error

### ISSUE THREAD

**Issue by michaelficarra** [babel/babel#1254]
I get the error "Parenthesized left hand expressions are illegal" when trying to compile this program:

```js
(a) = b;
```

I would expect no error. See ES6 sections [12.14.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors), [12.2.0.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-semantics-static-semantics-isvalidsimpleassignmenttarget), and [12.1.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-identifiers-static-semantics-isvalidsimpleassignmenttarget) which relate to early errors in assignment expressions.

**Comment by sebmck** [comment]
This should only be happening for object patterns.

**Comment by sebmck** [comment]
Actually, not sure. See jshint/jshint#2269 which is what lead to this change.

**Comment by sebmck** [comment]
Fixed as of 5.1.8.
