### ISSUE TITLE
Babel does not compile node_modules when using .babelrc in webpack

### ISSUE THREAD

**Issue by jokyme** [babel/babel#12551]
webpack rules
  {
    test: /\.(t|j)sx?$/,
    include: [new RegExp(
      \`node_modules/(?=(${[
        'acorn-jsx',
        'estree-walker',
        'regexpu-core',
        'unicode-match-property-ecmascript',
        'unicode-match-property-value-ecmascript',
        'react-dev-utils',
        'ansi-styles',
        'ansi-regex',
        'chalk',
        'strip-ansi',
        'js-base64',
        '@ctrl'
      ].join('|')})/).*\`
    )],
    use: [
      {
        loader: 'babel-loader',
        options: {
          babelrc: true,
          cacheDirectory: true,
          cacheCompression: false,
          compact: !isDev,
        },
      },
    ],
  }

i set a lot of plugins and prsets in .babelrc，but the package in node_modules would not compiler with the plugin.
then i debugger with vscode, and found that the babelrcLoadEnabled function will always return false when the filename includes "node_modules". that's because the findPackageData while break when the dirname equals to "node_modules",
so it can't reach the root directory of the project.

https://github.com/babel/babel/blob/e498bee10f0123bb208baa228ce6417542a2c3c4/packages/babel-core/src/config/files/package.js#L22

**Comment by JLHwung** [comment]
Rename `.babelrc` to `babel.config.json` if you want to compile node_modules: https://babel.dev/docs/en/configuration#whats-your-use-case
