### ISSUE TITLE
--watch doesnt save file

### ISSUE THREAD

**Issue by thegamerx1** [babel/babel#12559]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

--watch does not work but first compile does

**Input Code**

cli command
```cmd
babel --verbose --config-file C:/Users/TheGamerX05/Documents/Autohotkey/Lib/EzGui/.babelrc --watch --relative --out-dir . R:\TempCode\js.jsx
```

**Expected behavior**

save file on change

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
	"presets": [
		"@babel/preset-react",
		["@babel/preset-env", {
			"targets": {
				"ie": "11",
				"firefox": "69"
			}
		}]
	]
}
```

**Environment**

```
  System:
  OS: Windows 10 10.0.19042
Binaries:
  Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD                                                                                                
```
- Babel version(s): 7.12.10 (@babel/core 7.12.10)
- Node/npm version: Node 12.13.1/npm 6.12.1
- OS: Windows 10
- Monorepo: i have no idea what this means
- How you are using Babel: cli

**Possible issue**

My node_modules of babel is at `C:\Users\TheGamerX05\Documents\Autohotkey\Lib\EzGui` but im trying to compile a file at `R:\TempCode`

**Additional context**

https://user-images.githubusercontent.com/34986564/103106430-be9b6c80-4635-11eb-92d4-2d2a36ace905.mp4

**Comment by JLHwung** [comment]
If you click on the "..." button of Explorer tab, there will a "refresh explorer" option, try manually refresh it so it will reappear in VSCode.

**Comment by thegamerx1** [comment]
the issue its not with vscode but that babel `--watch` is broken the file is basically not created or modified if it exists

**Comment by JLHwung** [comment]
I can not reproduce this issue on macOS. Please provide a reproduction repo.

**Comment by thegamerx1** [comment]
how am i supposed to make a reproduction repo if its from cli?

**Comment by JLHwung** [comment]
> make a reproduction repo

See https://stackoverflow.com/help/minimal-reproducible-example

For CLI you can add some notes about how to reproduce this issue: like open a terminal tab with `babel --watch` and open another terminal to run
```
rm generated.js
echo "extra change" > source.js
# check if generated.js exists
stat generated.js
``
