### ISSUE TITLE
@babel/types toIdentifier: naming collision with non-ASCII characters

### ISSUE THREAD

**Issue by mischnic** [babel/babel#12574]
## Bug Report

- [x] I would like to work on a fix! (As in: I'd be willing to fix this if no one else steps up or you want to make this a "good first issue")

**Current behavior**

```
$ node
Welcome to Node.js v14.15.3.
> require("@babel/types").toIdentifier('ɵ2')
'_'
> require("@babel/types").toIdentifier('ɵ3')
'_'
> JSON.parse(fs.readFileSync(require.resolve("@babel/types/package.json"), "utf8")).version
'7.12.12'
```

It seems like `ɵ` is just removed and only the prepended `_` remains?

**Possible Solution**
Somehow handle non-ascii chars better? These two examples are actually valid identifiers already.

**Additional context**
Triggered by bindings of these names in https://unpkg.com/browse/@angular/core@11.0.5/fesm2015/core.js via https://github.com/parcel-bundler/parcel/issues/5547

**Comment by mischnic** [comment]
https://github.com/babel/babel/blob/1290d215f1cb8cc711057b4628f69c6d541d5622/packages/babel-types/src/converters/toIdentifier.ts#L6-L10

The "non-valid" part is probably overly strict? Not sure if this has changed between Javascript spec versions?

**Comment by JLHwung** [comment]
We can do
```js
name.replace(/\P{ID_Continue}/gu, "-"); 
```
or use https://github.com/babel/babel/blob/2d35f5a8f7f575d87a350b6a0f14efd96091c35f/packages/babel-helper-validator-identifier/src/identifier.ts#L68

Slightly prefer the second approach since `/\P{ID_Continue}/gu` depends on platform unicode version.
