### ISSUE TITLE
Reexports default could not co-exists with reexports star(SystemJS output)

### ISSUE THREAD

**Issue by shrinktofit** [babel/babel#12573]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAbzgE2AMwIYFcA28C-caUEAtnAORoQQUDcAUKJLHAFREnlU31A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-transform-modules-systemjs%407.12.1%2C%40babel%2Fplugin-proposal-class-properties%407.12.1%2C%40babel%2Fplugin-syntax-top-level-await%407.12.1)

**Input Code**

```js
export { default } from 'foo';
export * from 'foo';
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

```js
{
  "plugins": ["@babel/transform-modules-systemjs"]
}
```

**Environment**

- Babel version(s): [e.g. v7.12.12]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report! And thanks for ticking "I would like to work on a fix!" :smile: 

If you need any pointer, feel free to ask!
