### ISSUE TITLE
Babel can't parse decorators containing function expression

### ISSUE THREAD

**Issue by fisker** [babel/babel#12576]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl#?browsers=chrome%208&build=&builtIns=false&spec=false&loose=false&code_lz=AIMwrgdgxgLglgewgCgJQG8C-AoKAbAQwGciACAQSyA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Creact%2Cstage-2%2Cflow&prettier=false&targets=&version=7.12.12&externalPlugins=)

**Input Code**

```js
@function(){}
class A{}
```

**Expected behavior**

Should be able to parse it, `flow`, `typescript`, `meriyah` can parse it.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

N/A, directly use `parse` api.

**Environment**

```
- Babel version(s): [e.g. v7.12.0] v7.12.11
- Node/npm version: [e.g. Node 12/npm 7] Node 14/npm 7
- OS: [e.g. macOS 10.15.4, Windows 10] Windows 10
- Monorepo: [e.g. yes/no/Lerna] no
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`] api
```

**Possible Solution**

N/A

**Additional context**

If add parens to function expression, babel can parse it correctly

```js
@(function(){})
class A{}
```

Context: https://github.com/prettier/prettier/issues/4136

**Comment by nicolo-ribaudo** [comment]
That syntax is only valid when using legacy decorators (the `decorators-legacy` parser plugin), which is what flow, typescript and meriyah use.

**Comment by fisker** [comment]
Thank you! I'll close.
