### ISSUE TITLE
Typescript type references are not fully erased in build

### ISSUE THREAD

**Issue by avindra** [babel/babel#12578]
An issue was seen in [Recharts (#2360)](https://github.com/recharts/recharts/issues/2360) where Typescript types are not fully erased.

A repo with the detail and minimum set to reproduce the problem can be found here:

https://github.com/avindra/babel-ts-export-type-bug

**Comment by existentialism** [comment]
@avindra similar to https://github.com/babel/babel/issues/11464, you'll want to mark the type re-export with `export type`, otherwise Babel has no way of knowing it's a type.

**Comment by avindra** [comment]
Thanks @existentialism , I was hoping to avoid the `export type` since we cannot use this to mix type imports with standard imports.

But I can confirm Babel is able to erase it fully once it is explicitly marked with `export type`.
