### ISSUE TITLE
babel.transformSync does not parse type declarations

### ISSUE THREAD

**Issue by JohnPool** [babel/babel#12580]
Hello,

I am a babel-newby and I have a question about using `babel.transformSync()`.
I am using `@babel/core@7.12.10`.

What I noticed is that TypeScript type declarations do not seem to be parsed.
E.g. running:

`const output = babel.transformSync('let n: number = 1', {});`

results in:

`** transformation error: unknown: Unexpected token, expected ";" (1:5)`

All other TypeScript syntax seems to be handled correctly. 
Do I have to specify some setting or option?

Kind regards,

John Pool

**Comment by nicolo-ribaudo** [comment]
Do you have a Babel config file containing the TypeScript plugin or preset?

If not, you need to pass the TypeScript plugin to `babel.transformSync`.

**Comment by JohnPool** [comment]
Thanks Nicolò, that did the trick!

 

Regards, John

 

Van: Nicolò Ribaudo <notifications@github.com> 
Verzonden: Friday, January 01, 2021 13:58
Aan: babel/babel <babel@noreply.github.com>
CC: John C Pool <j.pool@ision.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [babel/babel] babel.transformSync does not parse type declarations (#12580)

 

Do you have a Babel config file containing the TypeScript plugin or preset?

If not, you need to pass the TypeScript plugin to babel.transformSync.
