### ISSUE TITLE
`export default` replacement breaks cyclic imports

### ISSUE THREAD

**Issue by ivan-kleshnin** [babel/babel#1258]
When I put `export default xxx` it's get translated to

```javascript
exports["default"] = x;

... 

// End of file
module.exports = exports["default"];
```

So the statement order is totally messed up and possibility to solve cyclic dependency is ruined. 
I used to use cyclic dependency with Express partially because I hate Node `index.js` required name for folder endpoints.

More concrete example:

```javascript
// IMPORTS 
let Express = require("express");

// EXPORTS 
let router = Express.Router(); // routes depend on `router` variable existance

module.exports = router; // WORKS "broadcast" variable
//export default router; // FAILS

// CYCLIC IMPORTS (blame node taken index.js as folder root) 
require("backend/robot/routes/create-post"); // pull routes one by one
require("backend/robot/routes/create-put");
... other routes
```

**Comment by ivan-kleshnin** [comment]
I'm pretty sure that `module.exports = router` and `export default router` should be absolutely interchangeable.

**Comment by hege91** [comment]
I think you should not mix CommonJS like imports with es6 exports in a single file. Es6 imported modues will try to load before the importing module itself anyways, even if the import statement is at the end of the file, so imports and require are not interchangeable either.

However, I think you can workaround all this by introducing a new file that will manage the imports/requires, for example:

```
// server.js
// IMPORTS 
let Express = require("express");
// EXPORTS 
let router = Express.Router(); // routes depend on `router` variable existance
export default router;

// main.js
require("./server.js");
require("backend/robot/routes/create-post"); // pull routes one by one
require("backend/robot/routes/create-put");
... other routes
```

**Comment by sebmck** [comment]
> So the statement order is totally messed up and possibility to solve cyclic dependency is ruined. 

I don't understand this statement. You shouldn't be mixing CommonJS and ES6 module syntax since they're fundamentally different. The reason Babel assigns to `exports.default` to start off with is so that when another ES6 module file imports it it'll get the flat `exports` that contains a `default` property that can be mutated so circular dependencies work. And then the `module.exports` at the end flattens it for normal CommonJS consumers.

**Comment by ivan-kleshnin** [comment]
@hege91, @sebmck yes I was wrong. Thanks for clarification!
