### ISSUE TITLE
@babel/generator support changing indent style

### ISSUE THREAD

**Issue by LeuisKen** [babel/babel#12586]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem?**

I want to change the indent to tab of my generated code, and according to https://github.com/babel/babel/blob/main/packages/babel-generator/src/index.js#L51 I can't change the indent style.

**Describe the solution you'd like**

Add an option to change the indent style.

**Describe alternatives you've considered**.

**Documentation, Adoption, Migration Strategy**

**Comment by JLHwung** [comment]
`@babel/generator` focuses on emitting correct JavaScript code with basic readability. That said, it does not provide much whitespace-related formatting options. You can pass the `@babel/generator` code to [`prettier`](https://prettier.io/) which provide more formatting options.

**Comment by LeuisKen** [comment]
I got it.
