### ISSUE TITLE
Property decorator function's parameter problem (stage 2)

### ISSUE THREAD

**Issue by nugaon** [babel/babel#12584]
## Bug Report

**Current behavior**

I console logged the got parameters in the example `Option` property decorator's function and it gave the following output: 

```text
target Object [Descriptor] {
  kind: 'field',
  key: 'option1',
  placement: 'own',
  descriptor: { configurable: true, writable: true, enumerable: true },
  initializer: undefined
}
propertyKey undefined
```

**Input Code**

```ts
import "reflect-metadata";

class TestCommand {
  @Option({ key: 'option-test-1', describe: 'Test option for TestCommand' })
  public option1!: string;

  public run(): void {
    console.log(`test ${this.option1}`)
  }
}

export function Option(options: IOption): PropertyDecorator {
  return function(target, propertyKey) {
    console.log('target', target)
    console.log('propertyKey', propertyKey)
    Reflect.defineMetadata(optionMetadataKey, options, target, propertyKey);
  }
}
```

**Expected behavior**

Get the same parameters in property decorator callback functions as Typescript PropertyDecorator type defines and also Babel does with `legacy: true` option.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- [config](https://github.com/nugaon/furious-commander/blob/master/.babelrc.js) - this config works with the project, but if I don't use legacy version, it does not work.

Output:
```text
target TestCommand {}
propertyKey option1
```

**Environment**

```
  System:
    OS: Linux 5.0 Linux Mint 19.3 (Tricia)
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  npmPackages:
    @babel/core: ^7.12.10 => 7.12.10 
    @babel/plugin-proposal-class-properties: ^7.12.1 => 7.12.1 
    @babel/plugin-proposal-decorators: ^7.12.12 => 7.12.12 
    @babel/plugin-transform-runtime: ^7.12.10 => 7.12.10 
    @babel/preset-env: ^7.12.11 => 7.12.11 
    @babel/preset-typescript: ^7.12.7 => 7.12.7 
    babel-jest: ^26.6.3 => 26.6.3 
    babel-loader: ^8.2.2 => 8.2.2 
    eslint: ^7.17.0 => 7.17.0 
    jest: ^26.6.3 => 26.6.3 
    webpack: ^5.11.0 => 5.11.1
```

"Wrong" proposal decorator setting: `['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }],`

"Good" proposal decorator setting: `['@babel/plugin-proposal-decorators', { legacy: true }],`

**Additional context**

For me it's a little bit vague whether it is inteded to be like this (because decorators are still in draft state), but if so, then it's a setback compare to the older version of it, because it provides lesser data about the decoratored target.

**Comment by nicolo-ribaudo** [comment]
If you want the legacy proposal then... use the legacy proposal :sweat_smile: 

Unfortunately the decorators proposal was completely rewritten multiple times, so this is a bit confusing.

The proposal that you are using is more modern than "legacy" but not the last one. The current proposal hasn't been implemented yet, but we'll do it in the next months.
If you are interested in decorators, I suggest reading https://github.com/tc39/proposal-decorators and giving feedback to the proposal authors!

**Comment by nicolo-ribaudo** [comment]
This is the proposal implemented in Babel: https://github.com/tc39/proposal-decorators/tree/7fa580b40f2c19c561511ea2c978e307ae689a1b
