### ISSUE TITLE
Decorator helpers use find, which breaks ie11

### ISSUE THREAD

**Issue by bschlenk** [babel/babel#12591]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

When using decorators through `@babel/plugin-proposal-decorators` and `@babel/plugin-transform-runtime`, [code is included that uses find](https://github.com/babel/babel/blob/a967910b8b9b41e0abac3ce622b0808ecd36ca0f/packages/babel-helpers/src/helpers.js#L2020), which is [unsupported in ie11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#browser_compatibility). 

**Input Code**

```js
@decorator
class MyClass {}

function decorator() {}
```

**Expected behavior**

I was under the impression that babel would output code that works with what I have in my `.browserslistrc` file, which includes ie11. I have `@babel/preset-env` set up with `useBuiltIns: "usage"` and core-js@3, but I am building through webpack and ignore node_modules. Should I allow babel to transform itself?

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  plugins: [
    ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }],
    '@babel/plugin-proposal-class-properties',
    [
      '@babel/plugin-transform-runtime',
      {
        useESModules: true,
        version: require('@babel/runtime/package.json').version,
      },
    ],
  ],
  presets: [
    ['@babel/preset-env', { useBuiltIns: 'usage', corejs: 3 }],
    '@babel/preset-typescript',
  ],
};
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.0/bin/npm
  npmPackages:
    @babel/core: ^7.12.10 => 7.12.10 
    @babel/plugin-proposal-class-properties: ^7.12.1 => 7.12.1 
    @babel/plugin-syntax-dynamic-import: ^7.2.0 => 7.8.3 
    @babel/preset-env: ^7.12.11 => 7.12.11 
    @babel/preset-typescript: ^7.12.7 => 7.12.7 
    babel-jest: ^26.6.3 => 26.6.3 
    babel-loader: ^8.2.2 => 8.2.2 
    jest: ^26.6.3 => 26.6.3 
    webpack: ^4.43.0 => 4.43.0 
```

**Possible Solution**

Use a helper function that loops instead of calling `.find`.

**Additional context**

**Comment by nicolo-ribaudo** [comment]
You can ignore `node_modules` _except for `@babel/runtime` (we made sure that it's safe to compile it), so that `preset-env` can inject the necessary polyfills:

```js
// in webpack.config.json
  {
    exclude: {
      test: /node_modules/, // Exclude libraries in node_modules ...
      not: [
        // Except @babel/runtime
        /@babel[\\/]runtime/,
      ]
    },
    use: 'babel-loader',
  }
```

**Comment by bschlenk** [comment]
Thanks @nicolo-ribaudo for the workaround! If this is intended, then is there a specific lowest browser that babel helpers is documented to support without having to run itself through babel?

**Comment by nicolo-ribaudo** [comment]
No, but it's definitely something we should document and enforce internally.

**Comment by nicolo-ribaudo** [comment]
Hi! The decorators proposal has been completely rewritten and we are discontinuing maintenance of the 2018-09 version (which will then be completely removed in Babel 8). You can migrate to the Stage 3 version of the [proposal](https://github.com/tc39/proposal-decorators/) by using `version: "2021-12"`.
