### ISSUE TITLE
_isNativeFunction(HTMLElement) throws an error in Firefox 31.

### ISSUE THREAD

**Issue by matthias-ccri** [babel/babel#12609]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

In Firefox 31.6.0 ESR, `_wrapNativeSuper` fails when called with `HTMLElement` (the error is thrown from `_isNativeFunction`). 

![image](https://user-images.githubusercontent.com/18034092/104240420-07bb3100-542a-11eb-9e20-3d589eddd788.png)
"TypeError: Function.prototype.toString called on incompatible object"

A simpler way to reproduce this is to run this in FF DevTools: `Function.toString.call(HTMLElement)`.
![image](https://user-images.githubusercontent.com/18034092/104240529-36390c00-542a-11eb-8951-83b9de711cfa.png)

Repro:
Since FF 31 fails to load both the babel repl and codesandbox, the repro is two steps:
1. I generated the babel output with the babel REPL: [link](https://babel.dev/repl#?browsers=ff%2031&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAuDnXgDyfAdgExgAlYBZAGQFER4BbXJaAbwChppgB7HHeYbPAMJgQIAEZhgAa2gAKAJRMkACwCWEAHQru8AE7Fy0ALzQA5IXgiOJgNwBfZrevMA7lrwdn64AFdkHGlS09Bp48ABmWvAyJtjIALSxSCYANHCIKOly1kA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=)
2. I pasted the output into JSBin (which still works with FF 31.6): [link](https://jsbin.com/hutewirebe/1/edit?js,output)

The code just subclasses `HTMLElement` to create a simple web component. Babel wraps `HTMLElement` with `_wrapNativeSuper` which in turn calls `_isNativeFunction`, which fails in FF 31.6.

**Input Code**

```js
class TestTest extends HTMLElement {
  connectedCallback () {this.innerHTML = 'Hello';}
};
window.customElements.define('test-test', TestTest);
```

**Expected behavior**
Expected no error in FF 31.6.

**Babel Configuration (codesandbox)**
Preset-env: `ff 31`

**Environment**

```

```
- Babel version(s): v7.12.12
- Node/npm version: n/a - codesandbox
- OS: n/a - codesandbox
- Monorepo: n/a - codesandbox
- How you are using Babel: n/a - codesandbox

**Possible Solution**
Wrap in a try/catch? Maybe call `fn.toString` directly?
```js
function _isNativeFunction(fn) {
  var s;
  try {s = Function.toString.call(fn)} catch(e){}
  try {s = fn.toString()} catch(e){}
  return s && s.indexOf("[native code]") !== -1;
}
```

**Additional context**
Given that Firefox 31 is six years old now, (2015), is this bug something that babel is willing to accept a fix for? If so, is the try/catch solution acceptable? (Class declarations typically aren't in hot code paths). Otherwise, what fix do you suggest?

Note: my method of running FF 31.6 involves running a docker image in ubuntu and mounting my X11 socket into the docker container. Let me know if you need help reproducing.

Thanks!

**Comment by nicolo-ribaudo** [comment]
Hey, sorry for not replying earlier.

Yeah, class declarations are not usually in hot paths, and class declarations compiled by Babel are already slow anyway so a `try/catch` doesn't hurt.

I think the helper should be something like this:
```js
function _isNativeFunction(fn) {
  if (typeof fn !== "function") return false;
  try {
    return Function.toString.call(fn).indexOf("[native code]") !== -1;
  } catch (e) {
    return true;
  }
}
```
We can return `true` in `catch` because non-native functions don't throw when stringified.
