### ISSUE TITLE
Possible Bug in babel-runtime/regenerator/index.js

### ISSUE THREAD

**Issue by gearsdigital** [babel/babel#1261]
I'm not quite sure if this is the right place to file this issue but somewhere i've to start.

I tried tu use `sassdoc-grunt`, which depends on `sassdoc` which depends on `babel-runtime`. The Grunt task dies with:

>  ReferenceError: Symbol is not defined

This happens until i changed the following lines in `babel-runtime/regenerator/index.js`.

*Please note the missing "_"!*

**Line 22**
```js
var iteratorSymbol = typeof _Symbol === "function" && Symbol.iterator || "@@iterator";
```
should be 
```js
var iteratorSymbol = typeof _Symbol === "function" && _Symbol.iterator || "@@iterator";
```
**Line 123**
```js
Promise.resolve(info.value).then(callNext, callThrow);
```
should be 
```js
_Promise.resolve(info.value).then(callNext, callThrow);
```

**Comment by sebmck** [comment]
Please upgrade to the latest.

**Comment by gearsdigital** [comment]
I'll file this issue over at sassdoc. There is version 5.0.* referenced. Thank you for your fast response!
