### ISSUE TITLE
browserslistrc - New Config Check Tool and a tutorial

### ISSUE THREAD

**Issue by aavmurphy** [babel/babel#12617]
## Feature Request

A tutorial about configuration, browserlistrc, and the debug:true option would be great.

https://babeljs.io/docs/en/configuration

The config documentation is a little unclear.  

A tutorial, with a standard sample config for people to adapt would be great

Especially highlight the 'debug:true' option which is very useful for users to work out which polyfills are used and why.

.babeljs
```
{
  "presets": [   [ "@babel/preset-env", { loose: true, bugfixes: true, modules: false, debug:true } ] ]
}

```
.browserslistrc (nb shared with other npm modules)
```
>= 0.5% in GB
last 2 major versions
not dead
# needed since Legacy Edge still has usage; 79 was the first Chromium Edge version
not Edge < 79
not Explorer <= 11
not OperaMini all
```

Sample output

```
Using targets:
{
  "android": "86",
  "chrome": "86",
  "edge": "86",
  ...
}

Using modules transform: false

Using plugins:
  proposal-numeric-separator { "ios":"10.3" }
  proposal-logical-assignment-operators { "edge":"86", "ios":"10.3", "opera":"71", "safari":"13", "samsung":"12" }
  proposal-nullish-coalescing-operator { "ios":"10.3", "safari":"13", "samsung":"12" }
 ...
```

[Edited to remove the request for a debug tool as it already exists the debug:true option above]

**Comment by nicolo-ribaudo** [comment]
You can pass `debug: true` to `@babel/preset-env`

**Comment by aavmurphy** [comment]
awesome, thanks @nicolo-ribaudo for the very quick reply, exactly what i needed
i'll edit the issue to be just documentation
