### ISSUE TITLE
Labeled for/of loop as brace-less sub-statement crashes

### ISSUE THREAD

**Issue by marijnh** [babel/babel#12610]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Code with a labeled `for/of` loop as direct substatement of an `if` crashes Babel.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYMwBAFALgTgrgUwJQCgxgIYGMrAPYB2AzgFxgh4yQA2CUYAHmHuAJ5JgDea6YWhuAokw58xHgF8UQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=),

**Input Code**

```javascript
if (true)
  actions: for (let x of y) {
    continue actions
  }
```

**Expected behavior**

Compilation works.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

See the repl link. Only happens when `es2015` is checked.

**Comment by lweathermon** [comment]
[](https://mail.google.com#inbox/FMfcgxwHNqFmBmqfSHFvjHlQwZZtnLSC)

**Comment by nicolo-ribaudo** [comment]
Thanks for taking the time to report this!
