### ISSUE TITLE
Error when trying to require `babel/external-helpers` with Browserify

### ISSUE THREAD

**Issue by spencercarnage** [babel/babel#1262]
I'm trying to include the external helpers file in a browserify build, but I always get the error `Error: Cannot find module 'babel/external-helpers' from '/my/repo'`. I recreated the error in a repo at https://github.com/spencercarnage/external-helpers-bug. 

Looking at the `babel` repo, the only reference I can find for `external-helpers` is in the Makefile. Am I supposed to run this Makefile on my project? That seems a little counterintuitive. Also, the [docs for external helpers](http://babeljs.io/docs/usage/external-helpers/) reference using a script tag for the browser, which has the `src` of `your-path-to/babel/external-helpers.js`. When `babel` is installed in `node_modules` as a `dependency`, there is definitely no `external-helpers.js` file in `node_modules/babel`. 

Some clarification on using `babel` both with `browserify` and including a script tag in the `HEAD` would be great. Thanks!

**Comment by sebmck** [comment]
Use the package babel-core, the docs need to be updated.

On Tuesday, 14 April 2015, Spencer Carney <notifications@github.com> wrote:

> I'm trying to include the external helpers file in a browserify build, but
> I always get the error Error: Cannot find module 'babel/external-helpers'
> from '/my/repo'. I recreated the error in a repo at
> https://github.com/spencercarnage/external-helpers-bug.
>
> Looking at the babel repo, the only reference I can find for
> external-helpers is in the Makefile. Am I supposed to run this Makefile
> on my project? That seems a little counterintuitive. Also, the docs for
> external helpers <http://babeljs.io/docs/usage/external-helpers/>
> reference using a script tag for the browser, which has the src of
> your-path-to/babel/external-helpers.js. When babel is installed in
> node_modules as a dependency, there is definitely no external-helpers.js
> file in node_modules/babel.
>
> Some clarification on using babel both with browserify and including a
> script tag in the HEAD would be great. Thanks!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1262>.
>


-- 
Sebastian McKenzie

**Comment by spencercarnage** [comment]
That worked. Thanks!
