### ISSUE TITLE
Babel-node doesn't respect `--max_old_space_size` option when working with cluster

### ISSUE THREAD

**Issue by ryancat** [babel/babel#12635]
## Bug Report

**Current behavior**

This are some codes on REPL that shows the error. Basically, babel-node doesn't respect the `--max_old_space_size` option when running with cluster. The out of memory exception will throw regardless of the extra memory allocated. Running without cluster everything works.
- [REPL] https://repl.it/@ryancat/AustereFriendlyHarddrive

**Expected behavior**

Babel-node should work with cluster as well when `--max_old_space_size` is provided.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Just install `@babel/node` and `@babel/core`.

**Environment**

```
$ npx envinfo --preset babel
npx: installed 1 in 1.377s

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  npmPackages:
    @babel/core: ~7.8 => 7.8.7 
    @babel/node: ~7.8 => 7.8.7 
    @babel/runtime: ~7.8 => 7.8.7 
```

**Possible Solution**

The only solution right now is to add `NODE_OPTIONS=--max-old-space-size=4096` before `node`.

**Comment by JLHwung** [comment]
I can not reproduce this error on my local build. As `@babel/node` should pass through all V8 options including `--max-old-space-size`:

https://github.com/babel/babel/blob/fec4a132adbddea725b2efdb5ac8ea948af3acf5/packages/babel-node/src/babel-node.js#L55-L60
 
You can add the following snippets
```
console.log(process.argv[0], args);
throw new Error("exit");
```
before https://github.com/babel/babel/blob/fec4a132adbddea725b2efdb5ac8ea948af3acf5/packages/babel-node/src/babel-node.js#L71

Can you attach your log output after you edit `node_modules/@babel/node/lib/babel-node`?

**Comment by ryancat** [comment]
@JLHwung Thanks for looking into this. I used htop to check my code and found the `--max_old_space_size` option is passed down in cluster correctly. However, it's not respected by the child process and they would run out of memory regardless of that option.

The example code on repl.it that I linked in the issue do not have `@babel/node` and `@babel/core` dependencies. However this could be easily reproduced if you copy them to local folder, run `yarn add @babel/node` and `yarn add @babel/core`, then run 
```
node node_modules/@babel/node/bin/babel-node.js --max_old_space_size=4096 runCluster.js
```
You will notice the code failed with OOM exceptions. If you run the same script use node by itself, it works.
```
node --max_old_space_size=4096 runCluster.js
```

**Comment by JLHwung** [comment]
```
node node_modules/@babel/node/bin/babel-node.js --max_old_space_size=4096 runCluster.js
```

I can not reproduce this error on my local build:

```
Success!
Allocated since start 3.05 GB
Success!
Allocated since start 2.95 GB
Allocated since start 3.05 GB
Success!
Allocated since start 2.95 GB
Allocated since start 3.05 GB
Success!
Allocated since start 3.05 GB
Success!
```

And `--max_old_space_size=4096` is indeed passed to the spawned process, which then executes `runCluster.js`

Did you try update `@babel/node` to latest version?

**Comment by JLHwung** [comment]
Posted an upstream issue https://github.com/nodejs/node/issues/36948 as I can't figure out how to fix it on Babel side. As a workaround mentioned by OP, please use `NODE_OPTIONS=(...supported v8 options)` when running `@babel/node`.
