### ISSUE TITLE
flow type alias of an object causes parse error

### ISSUE THREAD

**Issue by terinjokes** [babel/babel#1263]
Aliasing a flow type to an object causes a parse error.

[Flow Reusable Object Types](http://flowtype.org/docs/objects.html#reusable-object-types)
[REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=type%20T%20%3D%20%7Bdata%3A%20Object%2C%20loadStatus%3A%20string%7D%3B%0Avar%20x%3A%20T%20%3D%20%7Bdata%3A%20%7B%7D%2C%20loadStatus%3A%20'OK'%7D%3B)

**Comment by sebmck** [comment]
The separator is a semicolon and not a comma.

**Comment by terinjokes** [comment]
Gracias.

**Comment by sebmck** [comment]
![lol](http://thumb101.shutterstock.com/display_pic_with_logo/726364/726364,1301336245,3/stock-vector-mexican-74122186.jpg)

**Comment by hallettj** [comment]
Flow now accepts semicolons *or* commas as field separators. It would be nice if Babel accepted both as well. I don't know if the field separator syntax has stabilized; but from my perspective, I would prefer that Babel be quite permissive regarding type annotation syntax, since it is IMO Flow's job to check that.

**Comment by monsanto** [comment]
@hallettj I don't see this in their docs, and it's rejected by `jsx --strip-types` (which on their [website](http://flowtype.org/docs/running.html#_) they recommend as the best way to run flow code in production).

**Comment by hallettj** [comment]
> it's rejected by jsx --strip-types

Well, that is kind of unfortunate.  I suppose that the Flow and JSX implementations are out of sync on that point.  But my feeling is that outside of Facebook's documentation Babel is the recommended way to run Flow code :)

My only references are the Flow source code and my own testing (with Flow v0.10.0).  Support for commas-as-delimiters was added to Flow in this commit:

https://github.com/facebook/flow/commit/04e4f7e8

It's a big commit; but in there is a change in the `_object` parser function that replaces a check for a `T_SEMICOLON` token with a check for `T_COMMA | T_SEMICOLON`.

So commas-as-delimiters are undocumented, and are not consistently supported.  I will understand if you do not want to modify Babel to accommodate them.

**Comment by monsanto** [comment]
It's not in the 0.10 changelog either. Just to be on the safe side, let's get confirmation that this isn't an accident. @jeffmo (sorry, just picked the first person I saw w/ an owner tag) can you tell us whether commas are officially allowed in object types, and the docs/jsx are just out of date?

**Comment by jeffmo** [comment]
Oh sorry, yes both commas and semis are allowed for type alias property separators now in Flow (we syncd with TypeScript some time back and agreed it would make sense for both systems).

I lost track and forgot to ping Babel and apparently also our docs about this...my bad!

**Comment by sebmck** [comment]
Fixed via f5b3d727300764c21228d48624a6873884c7f4f3.
