### ISSUE TITLE
@babel/preset-env with the browserlist affects to scope resolving in eval

### ISSUE THREAD

**Issue by davakh** [babel/babel#12637]
## Bug Report

**Current behavior**

There is incorrect scope resolving while transpiling the code, whereas by the logic the function expression should be shadowed by the function argument, but the argument identifier becomes renamed, and the eval execution becomes incorrect.

- [Babel playground](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011%2C%20chrome%20%3E%2049&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAsg9gJgVwDYFMIF4IDMEDsDGALgJYy4AUsiqAlBAN4BQEL08yamVHEAPrwwC-Abmat8ZAM6EIAIwwQUoJOQBE5HARJlydehEJgAngwhgUhBGFxtqafkIiCI-EIXwALcij1mLVm3pnYJpdVRoxFgB6KIgAOgSExki_S2tbDlFBIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=)

It seems to be a bug with `@babel/preset-env` when you set the list of supported browsers. For example, in the playground, if you use `chrome > 49` - the bug exists, but if you increase the version of Chrome, the bug disappears. It can be affected by other browsers, but Chrome is there f.e.

Input code is a short version of the compiled `emscripten` module.

**Input Code**

```js
var Module = function(Module) {
    Module = Module || {};
    const b = eval("(function() { try { return Module || {} } catch(e) { return {} } })()")
    // .....

    return Module;
}
```

**Expected behavior**

`Module` should be referred to the function argument, not outer `var`
```js
"use strict";

var Module = function (Module) {
  Module = Module || {};
  const b = eval("(function() { try { return Module || {} } catch(e) { return {} } })()"); // .....

  return Module;
};
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

- Config in the [Babel playground](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011%2C%20chrome%20%3E%2049&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAsg9gJgVwDYFMIF4IDMEDsDGALgJYy4AUsiqAlBAN4BQEL08yamVHEAPrwwC-Abmat8ZAM6EIAIwwQUoJOQBE5HARJlydehEJgAngwhgUhBGFxtqafkIiCI-EIXwALcij1mLVm3pnYJpdVRoxFgB6KIgAOgSExki_S2tbDlFBIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=)

**Environment**

- Config in the [Babel playground](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011%2C%20chrome%20%3E%2049&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAsg9gJgVwDYFMIF4IDMEDsDGALgJYy4AUsiqAlBAN4BQEL08yamVHEAPrwwC-Abmat8ZAM6EIAIwwQUoJOQBE5HARJlydehEJgAngwhgUhBGFxtqafkIiCI-EIXwALcij1mLVm3pnYJpdVRoxFgB6KIgAOgSExki_S2tbDlFBIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=)

**Comment by davakh** [comment]
Seems related https://github.com/babel/babel/discussions/12067

**Comment by JLHwung** [comment]
Babel does not support `eval`. You can add this file to `ignore`: https://babel.dev/docs/en/options#ignore
