### ISSUE TITLE
Wrong emit for computed and shorthand `__proto__` property

### ISSUE THREAD

**Issue by ExE-Boss** [babel/babel#12647]
## Bug Report

- [x] I would like to work on a fix!

### Input Code

```js
const computed = {
	// Expected: _defineProperty({}, '__proto__', 123)
	['__proto__']: 123,
};

const shorthand = {
	// Expected: _defineProperty({}, '__proto__', __proto__)
	__proto__,
};

const method = {
	// Expected: _defineProperty({}, '__proto__', function __proto__() {})
	__proto__() {},
};
```

- [REPL](https://babeljs.io/repl#?code_lz=MYewdgzgLgBKC2AHArlApgExgXhgbwCgBIAehJgFEAPRNYdDALhgH0M0AzASzDQAUATiFoCoATwAUeAL4AaGAHIWLREKghlC-QEYATAGYAlMQDaSlWo0sFAXWZ79sgtIDcBAqEiwIACxCifAEMwLFxCUnJqWnpMZjZOHn4hEXEpOUVlVRB1TXlMy2VjInzsqydXd09oGHg0KD9Q_GIySho6Bjj2bl5BYTRRSRl5cyyc63kOZDB6LnBWC1LlCUN8aSKSseXV8rcgA&sourceType=script&lineWrap=true&prettier=true&spec=true&loose=false&presets=es2015&browsers=)

### Current behaviour
```js
var _computed;
var computed = (
	(_computed = {
		// Expected: _defineProperty({}, '__proto__', 123)
	}),
	(_computed["__proto__"] = 123),
	_computed
);

var shorthand = {
	// Expected: _defineProperty({}, '__proto__', __proto__)
	__proto__: __proto__
};

var method = {
	// Expected: _defineProperty({}, '__proto__', function __proto__() {})
	__proto__: function __proto__() {}
};
```

### Expected behaviour
```js
var computed = _defineProperty(
	{
		// Expected: _defineProperty({}, '__proto__', 123)
	},
	'__proto__',
	123
);

var shorthand = _defineProperty(
	{
		// Expected: _defineProperty({}, '__proto__', __proto__)
	},
	'__proto__',
	__proto__
);

var method = _defineProperty(
	{
		// Expected: _defineProperty({}, '__proto__', function __proto__() {})
	},
	'__proto__',
	function __proto__() {}
);
```

### Environment

- Babel version(s): v7.12.12 (according to REPL)
- Node version: v15
- OS: REPL
- Monorepo: no
- How you are using Babel: REPL

### Possible Solution

Always use the `_defineProperty` helper for the computed and shorthand `__proto__` property initialisers.

### Additional context

- <https://github.com/microsoft/TypeScript/issues/38385>
- <https://github.com/microsoft/TypeScript/pull/42359>

**Comment by JLHwung** [comment]
See also #4188 and #11882.
