### ISSUE TITLE
import doesn't work in babel-node interactively

### ISSUE THREAD

**Issue by AgentME** [babel/babel#1264]
This used to work for me in 4.x, but since updating it doesn't seem like import works interactively any more.

```
[chris /tmp/aaa]$ npm i kefir
kefir@1.3.1 node_modules/kefir
[chris /tmp/aaa]$ babel-node --version
5.1.9
[chris /tmp/aaa]$ babel-node
> import Kefir from 'kefir';
'use strict'
> Kefir
ReferenceError: Kefir is not defined
    at [object Object]:3:1
    at _eval (/usr/local/lib/node_modules/babel/bin/_babel-node:54:13)
    at REPLServer.replEval [as eval] (/usr/local/lib/node_modules/babel/bin/_babel-node:136:14)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
> [chris /tmp/aaa]$ 
[chris /tmp/aaa]$ echo "import Kefir from 'kefir'; console.log(Kefir);"|babel-node
> import Kefir from 'kefir'; console.log(Kefir);
{ DEPRECATION_WARNINGS: true,
  Observable: [Function: Observable],
  Stream: [Function: Stream],
  Property: [Function: Property],
  withInterval: [Function],
  fromPoll: [Function],
  interval: [Function],
  sequentially: [Function],
  repeatedly: [Function],
  later: [Function],
  merge: [Function],
  concat: [Function],
  Pool: [Function: Pool],
  pool: [Function],
  Bus: [Function: Bus],
  bus: [Function],
  zip: [Function],
  combine: [Function],
  sampledBy: [Function],
  fromBinder: [Function],
  emitter: [Function],
  Emitter: [Function: Emitter],
  never: [Function],
  constant: [Function],
  constantError: [Function],
  repeat: [Function],
  and: [Function],
  or: [Function],
  fromCallback: [Function],
  fromNodeCallback: [Function],
  fromPromise: [Function],
  fromSubUnsub: [Function],
  fromEvent: [Function],
  Kefir: [Circular] }
undefined
> [chris /tmp/aaa]$ 
```

**Comment by sebmck** [comment]
I don't think there's a way I could even make it work. It requires access to the entire file and it's similar to how you can reassign constants in the node REPL.

**Comment by sebmck** [comment]
Yeah, doesn't look like anything can be done about this unfortunately since the entire file is needed to remap.

**Comment by briancavalier** [comment]
FWIW, `let` + `require` + destructuring has been a reasonable workaround for me.

```
babel-node
> let { foo, bar } = require('baz');
```

**Comment by AgentME** [comment]
It's not been much of an issue for me now that I know about the limitation.

When I first ran into the issue of import not working after it worked in previous versions, I immediately assumed babel-node was completely broken because the line with `import` was the first command I tried running, and I spent a while wrestling with NPM and looking at my global node modules trying to figure out why my babel-node install was broken before I realized it was specifically imports that didn't work.

It looks like the limitation has surprised other people too. Maybe the REPL should disallow imports entirely with an informative error message ("import not supported in interactive mode", etc).

**Comment by briancavalier** [comment]
> It's not been much of an issue for me now that I know about the limitation.
> It looks like the limitation has surprised other people too.

Cool.  Yeah, it surprised me as well.

> Maybe the REPL should disallow imports entirely with an informative error message ("import not supported in interactive mode", etc).

Sounds like a great idea, and maybe also add the `let` + `require` workaround hint to the error message.

**Comment by halhenke** [comment]
Some kind of error message would definitely be a good idea - can say from personal experience that it would save some people a fair bit of time wondering what was going on.

**Comment by super-cache-money** [comment]
Agreed. It's pretty off-putting.

**Comment by git-toni** [comment]
+1 @ some feedback :)

**Comment by AgentME** [comment]
>Yeah, doesn't look like anything can be done about this unfortunately since the entire file is needed to remap.

All definitions in the REPL are top-level declarations and therefore global, right? If imports were rewritten like this, then they could work properly in the REPL without requiring future lines to be remapped:

```javascript
import foo, {bar} from 'foobar';
``` 

```javascript
(function(){
  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
  var _foobar = require('foobar');
  var _foobar2 = _interopRequireDefault(_foobar);
  Object.defineProperties(global, {
    foo: {
      enumerable: true,
      get: function(){return _foobar2.default;},
      set: function(){throw new Error("Not writable");}
    },
    bar: {
      enumerable: true,
      get: function(){return _foobar.bar;},
      set: function(){throw new Error("Not writable");}
    }
  });
})();
```

**Comment by sebmck** [comment]
In the `development` branch due out for 6.0 there's [this](https://github.com/babel/babel/blob/development/packages/babel-cli/src/_babel-node.js#L38-L50) plugin that warns on use of specific code. I'm not going to maintain a separate module transformer just for the REPL.

**Comment by git-toni** [comment]
@sebmck didn't see that, great to know, thanks!
