### ISSUE TITLE
if/for don't play well together

### ISSUE THREAD

**Issue by assaf** [babel/babel#1265]
```
(function test() {
  if (true)
    for (let x of [1,2,3])
      return;
  console.log('fail');
})();
```

If the `if` statement uses brackets to enclose the `for` loop, everything works correctly. Without brackets, as in the above example, it produces:

'use strict';
```
(function named() {
  if (true) (function () {
      var _arr = [1, 2, 3];

      for (var _i = 0; _i < _arr.length; _i++) {
        var x = _arr[_i];
        return;
      }
    })()console.log('fail');
})();
```

1. The additional internal IIFE prevents the `return` statement from actually exiting the function.
2. No semicolon/newline following the IIFE

**Comment by sebmck** [comment]
Fixed as of 5.1.10.
