### ISSUE TITLE
plugin-proposal-decorators implementation does not accurately reflect stage-2 description.

### ISSUE THREAD

**Issue by Enteleform** [babel/babel#12654]
# Bug Report

&nbsp;  
## Description

According to the current [**Stage-2 Description**](https://github.com/tc39/proposal-decorators#2-calling-decorators), two parameters should be passed to decorators when they are called:

```ts
element: (class | function | {get, set})

context: {kind, name, isStatic}
```

&nbsp;  
## Input Code

```ts
function decorated(element, context){
  console.log({element, context})
}

class Foo{
  @decorated
  bar(){}
}
```

&nbsp;  
## Current Output

```js
{
  element: {
    key:       "bar",
    kind:      "method",
    placement: "prototype",
    descriptor: {
      configurable: true,
      enumerable:   false,
      value:        ƒ bar(),
      writable:     true,
    },
  },
  context: undefined,
}
```

&nbsp;  
## Expected Output

```js
{
  element: ƒ bar(),
  context: {
    kind:     "method",
    name:     "bar",
    isStatic: false,
  },
}
```

&nbsp;  
## Babel Configuration / Environment

This is reproducible in the REPL, so I did not include my personal configuration.

- [**REPL**](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAEwKYTgJwIZVcgClQBtUBbVMKAGkQytQA8oBKAbwChE6EBnOUgDpicAOYE2JcpRo8GzAL4sOCjhwjFsvXogBicOJ24ABNBhx5kXRACNsmAu1UKgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=)

&nbsp;  
## Additional context

I believe that the function signature of decorators should accurately reflect the current state of the proposal, to minimize erroneous code & the need for refactoring when the specification is finalized & implemented.

Also, the [**Return Value**](https://github.com/tc39/proposal-decorators#the-return-value) implementation should match the current description as well.

**Update:**  
It also seems like the `kind` values are inconsistent. For example, the decorator of a `get` member receives `{kind: "method"}` instead of the described [**Context**](https://github.com/tc39/proposal-decorators#the-context-object-the-second-parameter) of `{kind: "getter"}`.

**Comment by MatheusBueno782** [comment]
I have the same feeling about it @Enteleform, by not reflecting the proposal's function signature of the decorator, we potentially increase the amount of refactoring when the spec get approved. There is a specific reason for deviating from the proposal on this specific matter?

**Comment by JLHwung** [comment]
Implementation of the 2021-12 decorator proposal is tracked in #14004.

**Comment by nicolo-ribaudo** [comment]
We are working on it on https://github.com/babel/babel/pull/14004: our implementation will match the current Stage 2 proposal in the next minor.

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/pull/14004 has been merged, we'll release it in the next version.
