### ISSUE TITLE
Using spread operator on Sets fails to import required Array.from polyfill for IE11

### ISSUE THREAD

**Issue by pablobarria** [babel/babel#12668]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Using `@babel/preset-env` with the `babel-loader` for `webpack`, with a browserslist value of "> 0.25%, not dead", our build crashes on IE11 with the error message  `Object doesn't support property or method 'from'` if we try to use the spread ("...") operator on a Set.

**Input Code**

```js

//const sampleArray = Array.from({ length: 10 }, (_, i) => i);  // if I uncomment this line, IE11 works as expected
const sampleSet = new Set([5, 4, 4, 4, 3, 2, 2, 2, 2, 1, 1, 1]);
console.log(...sampleSet); // this will throw on IE11 unless the first line is uncommented


```

**Expected behavior**

For useBuiltIns to understand that `[...(new Set())]` requires Array.from to be polyfilled forn relevant targets

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `webpack.config.js`

```js
...
            {
                test: /\.jsx?$/,
                loader: "babel-loader",
                options: {
                    presets: [
                        [
                            "@babel/preset-env",
                            {
                                useBuiltIns: "usage",
                                corejs // variable storing core-js version read directly from package.json
                            }
                        ],
                        "@babel/preset-react"
                    ]
                },
...
```

**Environment**

```

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 15.0.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 7.0.3 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.12.10 => 7.12.10
    @babel/preset-env: ^7.12.11 => 7.12.11
    @babel/preset-react: ^7.12.10 => 7.12.10
    babel-loader: ^8.2.2 => 8.2.2
    eslint: ^7.18.0 => 7.18.0
    webpack: ^5.16.0 => 5.16.0

```

**Possible Solution**

**Additional context**

**Comment by JLHwung** [comment]
[REPL](https://babel.dev/repl#?browsers=IE%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=MYewdgzgLgBBCGBbADgGwKYGV2wLwzHQHcZsoAKAbQFYAaGAFnqcfoGZ6AmLnmbmAIz0hggLoBKANwAoUJBAYAdKhABzcos0IUGMlKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=)

Both `Array.isArray` and `Array.from` used in `@babel/helpers` should be polyfilled when targeting IE 8.

**Comment by JLHwung** [comment]
I can not reproduce this error on Babel 7.15: [REPL](https://babel.dev/repl#?browsers=IE%208&build=&builtIns=usage&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBBCGBbADgGwKYGV2wLwzHQHcZsoAKAbQFYAaGAFnqcfoGZ6AmLnmbmAIz0hggLoBKANwAoUJBAYAdKhABzcos0IUGMlKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.15.7&externalPlugins=&assumptions=%7B%7D)

@pablobarria Can you confirm the issue has been fixed?
