### ISSUE TITLE
Do not strip flow import type declarations

### ISSUE THREAD

**Issue by djvern** [babel/babel#12669]
The latest version of Babel 7 strips out flow `import type` declarations by default. They used to be included with earlier versions of Babel 7 and 6. Whilst it makes sense to remove them, is there an easy way to keep them and treat them as regular imports, as the app I'm working on uses flow-runtime and relies on the types to work. 

Is there an existing plugin that can do this, or do I need to write my own? At the moment I'm replacing `import type` with `import` as a build step before running babel, but if feels like there should be a way to do it all within Babel.

**Comment by JLHwung** [comment]
You can skip the flow transform by replacing `@babel/preset-flow` to `@babel/plugin-syntax-flow`, so Babel will leave the flow syntax as-is. Then you can pass the generated code to `flow-runtime`.

**Comment by djvern** [comment]
Ah, I tried that but import type declarations are still being stripped out. Is this just a default setting in Babel now? If so, how can I override it?

**Comment by nicolo-ribaudo** [comment]
Babel by default doesn't transform your code, you are unknowingly enabling the flow transform somewhere.

You can post the output of [`BABEL_SHOW_CONFIG_FOR`](https://babeljs.io/docs/en/configuration#print-effective-configs) (use your build command instead of `npm start`) if you need help figuring out where it's enabled.

**Comment by nicolo-ribaudo** [comment]
Closing since this was a configuration problem. If you still need help feel free to ping.

**Comment by djvern** [comment]
@nicolo-ribaudo thanks for the info - after a bit more investigating I realised the issue was with flow-runtime and the plugin babel-plugin-flow-runtime. There's a fix in the latest version which has resolved the issue if it helps anyone else: https://github.com/gajus/flow-runtime/issues/254
