### ISSUE TITLE
Content Security Policy error when using Babel 5.x in Atom editor

### ISSUE THREAD

**Issue by gandm** [babel/babel#1267]
I have developed/testing a Babel package for Atom and now I get a Content Security Policy error in Atom when using babel-core. This happens at line 46 in babel/src/acorn/src/identifier.js which is a 'new Function' call. 
Message is:
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". + stack trace

**Comment by sebmck** [comment]
Oversight on my behalf, my bad. I'll probably just remove the eval predicate stuff since modern engines are smart enough to optimise for it anyway (at least from my interpretation of IRHydra).

**Comment by sebmck** [comment]
Any ideas on how to incorporate CSP into the test framework? I don't want regressions sneaking in like this in the future.

**Comment by gandm** [comment]
No I'm not sure how this can be tested. I thought that it would be implicit - i.e. CSP would be on in node (V8) for server side JS.

**Comment by sebmck** [comment]
Fixed as of 5.1.10.

**Comment by AgentME** [comment]
@sebmck I just redefine eval and Function in tests to simulate CSP's no-eval rule:

```javascript
    var _eval = eval, _Function = Function;
    before(function() {
      global.eval = global.Function = function() {throw new Error("eval not allowed");};
    });
    after(function() {
      global.eval = _eval;
      global.Function = _Function;
    });
  })();
```

**Comment by bucaran** [comment]
@AgentME That's clever!
