### ISSUE TITLE
Cannot transpile yield/await spread for Firefox 47

### ISSUE THREAD

**Issue by boris-petrov** [babel/babel#12690]
## Bug Report

**Current behavior**
- [REPL](https://babeljs.io/repl#?browsers=firefox%2047&build=&builtIns=false&spec=false&loose=true&code_lz=JYWwDg9gTgLgBAYQuCA7Apq-AzKy4DkAAgOYA2oI6UA9AMbKQZYEDcAUKJLHMFtQGd0dGMDRxc-AmQgATAIYCAFjT4xBw0Wjbt26AB7d4s9NnkBXMvDplFAuADEIEJCmbwD61LPuummeABvdjg4RQBPVDoJZwAKAEo4YNDQtQ0RMVRYgDpc2PkAd3lgeAAFPBBgIWz5MjJYgG0AXXjWjlCAX3YOoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-1&prettier=true&targets=Node-14.14&version=7.12.12&externalPlugins=)

```js
import Component from '@glimmer/component';
import intersection from 'lodash/intersection';

export default class FooComponent extends Component {
  async foo() {
    intersection(...(await Promise.all([])));
  }
}
```

**Expected behavior**
Code to be transpiled correctly.

Currently Babel blows up with:

```
Expected type "Expression" with option undefined, but instead got "SpreadElement".
```

Using `firefox 35` for targets works. As does `firefox 53` and above.

**Comment by nicolo-ribaudo** [comment]
Minimal reproduction:
```js
function *foo() {
  intersection(...yield);
}
```

**Comment by nicolo-ribaudo** [comment]
Closing as tracked at https://github.com/facebook/regenerator/issues/397
