### ISSUE TITLE
Cannot transpile class expression for Firefox 47

### ISSUE THREAD

**Issue by boris-petrov** [babel/babel#12692]
## Bug Report

**Current behavior**
- [REPL](https://babeljs.io/repl#?browsers=firefox%2047&build=&builtIns=false&spec=false&loose=true&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29UGcCeAdgMZzLokwCWEhcAFAJRwDeAUHHFMDOlHcUx5ccUDGCEEIgEJ5grDpzIQITBUqXde_OAEYA3Is4BfRccOmgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-1&prettier=true&targets=Node-14.14&version=7.12.12&externalPlugins=)

```js
export default async function () {
  return class extends Base {
    foo() {
      return 1;
    }
  };
}
```

**Expected behavior**
Code to be transpiled correctly.

Currently Babel blows up with:

```
unknown Expression of type "ClassExpression"
```

Using `firefox 35` for targets works. As does `firefox 53` and above. Similarly to https://github.com/babel/babel/issues/12690.

**Comment by nicolo-ribaudo** [comment]
Moved to https://github.com/facebook/regenerator/issues/407, since this is caused by regenerator.
