### ISSUE TITLE
@babel/code-frame incorrectly marks lines containing tab characters

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#12696]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

The `@babel/code-frame` function `codeFrameColumns` incorrectly marks a location in a line that follows tab characters; the markers are not indented using the right mix of spaces and tab characters to indent enough to visually line up with the characters being marked.

Example:

```js
"use strict";

const { codeFrameColumns } = require("@babel/code-frame");

console.log(
  codeFrameColumns(
    'x\t\tabc',
    {
      start: { line: 1, column: 3 },
      end: { line: 1, column: 6 },
    },
    { forceColor: true }
  )
);
```

<img width="649" alt="Screen Shot 2021-01-27 at 3 11 49 pm" src="https://user-images.githubusercontent.com/1754873/105941934-94185580-60b2-11eb-8079-66b03e72c4a6.png">

**Expected behavior**

Code frame markers horizontally line up visually with the characters being marked.

**Environment**

- `@babel/code-frame`: v7.12.11

**Comment by nicolo-ribaudo** [comment]
There are two different questions:
1. **Is `@babel/code-frame` doing the correct thing?**
   Imo yes. A tab isn't 1-column-large, but it spawns multiple columns. If highlight "abc" in my editor, it says that it starts at column 9.
2. **Is `@babel/parser` (or whoever is generating that `line/column` info) doing the correct thing?**
   If it reports `\t` as one column probably not, but it would require a `tabWidth` option or similar.

**Comment by jaydenseric** [comment]
- Regarding (1), a column in a text editor is whatever the character is. 1 tab character = 1 column.
- Regarding (2), column is correct (as explained above).

It seems tabs and visual alignment of the markers have been accounted for in the past, but only for far-left indentation in lines:

https://github.com/babel/babel/pull/3464

I don't see the harm in making sure the markers line up correctly by indenting them with a combination of tabs and spaces, as required.

**Comment by nicolo-ribaudo** [comment]
> a column in a text editor is whatever the character is. 1 tab character = 1 column

At least in vscode and gedit they are counted as multiple columns, while vim gives you both the number counting them as 1 and as multiple.

Anyway, this is probably easier to fix in `@babel/generator` as you suggest, so we can do it.

**Comment by jaydenseric** [comment]
Here is step-by-step example.

I'm using `@babel/code-frame` for JSDoc related error messages in [`jsdoc-md`](https://www.npmjs.com/package/jsdoc-md). One such error, is if the user references a JSDoc member that doesn’t exist in a namepath:

<img width="310" alt="Screen Shot 2021-01-28 at 9 46 39 am" src="https://user-images.githubusercontent.com/1754873/106064965-af38a300-614e-11eb-95df-e0e1361812af.png">

Notice in this example, the user has indent-aligned the JSDoc tag values using spaces.

The link to the start of the problem code location can be CMD+Clicked in VS Code, and you can see that it places the carrot at the right spot:

<img width="305" alt="Screen Shot 2021-01-28 at 9 46 53 am" src="https://user-images.githubusercontent.com/1754873/106065193-0a6a9580-614f-11eb-82ec-63de82dddb17.png">
<img width="366" alt="Screen Shot 2021-01-28 at 9 47 05 am" src="https://user-images.githubusercontent.com/1754873/106065201-0d658600-614f-11eb-9857-c06d5d0ede37.png">

Now, lets try the same thing but with the JSDoc tag values indent-aligned using tabs instead of spaces:

<img width="312" alt="Screen Shot 2021-01-28 at 9 50 06 am" src="https://user-images.githubusercontent.com/1754873/106065299-384fda00-614f-11eb-9821-81b8f8f95c69.png">
<img width="302" alt="Screen Shot 2021-01-28 at 9 50 19 am" src="https://user-images.githubusercontent.com/1754873/106065315-4140ab80-614f-11eb-870a-691970577ed1.png">
<img width="365" alt="Screen Shot 2021-01-28 at 9 50 28 am" src="https://user-images.githubusercontent.com/1754873/106065334-47cf2300-614f-11eb-83c4-70c8e91946d1.png">

As you can see, the start column is correct how it is. What is incorrect is the way `@babel/code-frame` visually indents the column location markers. Hence this issue.

**Comment by liuxingbaoyu** [comment]
I re-investigated the issue and found that the problem came from the `column` parameter of `@babel/code-frame` being 1-based.
If I increase them by 1, it works fine.

![image](https://github.com/babel/babel/assets/30521560/4c9e9a59-8b82-4f87-93e5-2958743d6813)

```js
const { codeFrameColumns } = require("@babel/code-frame");

const code = "x\t\tabc";

console.log(
  codeFrameColumns(
    code,
    {
      start: { line: 1, column: 4 },
      end: { line: 1, column: 7 },
    },
    { forceColor: true }
  )
);

console.log(
  codeFrameColumns(
    code.replace(/\t/g, " "),
    {
      start: { line: 1, column: 4 },
      end: { line: 1, column: 7 },
    },
    { forceColor: true }
  )
);

```
