### ISSUE TITLE
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax,

### ISSUE THREAD

**Issue by takhello** [babel/babel#12709]
## Bug Report
babel.config.js ，Configuration is as follows：
```ja
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        corejs: 3,
        useBuiltIns: 'usage',
        targets: '> 0.000000001%,last 2 versions,not dead,ie 10'
      }
    ],
    '@vue/babel-preset-jsx'
  ],
  plugins: [
    ['@babel/plugin-transform-arrow-functions'],
    ['@babel/plugin-transform-runtime', {
    }]
  ]
}
```

- [ ] I would like to work on a fix!

**Current behavior**
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax,

**Expected behavior**

There is no abnormal

**Environment**

```
npm -v
6.4.1
node -v
v10.15.3

"@babel/core": "^7.12.10",
"core-js": "^3.8.3",
"@babel/preset-env": "^7.12.11",
...
...

```

**Possible Solution**

Modify the configuration:

```ja
module.exports = {
  presets: [
    [
      '@babel/preset-env'
    ],
    '@vue/babel-preset-jsx'
  ],
  plugins: [
    ['@babel/plugin-transform-arrow-functions'],
    ['@babel/plugin-transform-runtime', {
    }]
  ]
}
```

**Additional context**

null

**Comment by nicolo-ribaudo** [comment]
> Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax

This error is not thrown by Babel.
However, if you think that it's caused by Babel and that config change fixes it, it's probably because you are also compiling `node_modules/core-js` (which doesn't support being compiled).
