### ISSUE TITLE
Missing extension of @babel/runtime helper imports in ESM context

### ISSUE THREAD

**Issue by cdoublev** [babel/babel#12704]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

`babel index.js -o output.js` creates `output.js` with imports of Babel helpers which are injected without their file extension.

**Input Code**

**index.js:**

```js
class Foo {}
class Bar extends Foo {}
```
**package.json:**

```json
 {
   "type": "module",
   "scripts": {
     "build": "babel index.js -o output.js"
   },
   "dependencies": {
     "@babel/runtime": "^7.12.5",
     "core-js": "^3.8.3"
   },
   "devDependencies": {
     "@babel/cli": "^7.12.10",
     "@babel/core": "^7.12.10",
     "@babel/plugin-transform-runtime": "^7.12.10",
     "@babel/preset-env": "^7.12.11"
   }
 }
```

**Expected behavior**

```js
import _inherits from "@babel/runtime/helpers/esm/inherits.js";
// ...
```

Instead of:

```js
import _inherits from "@babel/runtime/helpers/esm/inherits";
// ...
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.cjs`

```js
module.exports = {
  presets: [['@babel/preset-env', { modules: false }]],
  plugins: [['@babel/plugin-transform-runtime', { useESModules: true }]],
}
```

**Environment**

- Babel version(s): 7.12.10
- Node/npm version: Node 15 / npm 7
- OS: Debian Buster
- Monorepo: no
- How you are using Babel: @babel/cli

**Possible Solution**

Append the `.js` file extension [here](https://github.com/babel/babel/blob/9ac36b136adcfa1940cdcc60399cb4079fb67361/packages/babel-plugin-transform-runtime/src/index.js#L211) if `helpersDir === 'helpers/esm'`, but this feels unappropriate.

**Additional context**

The issue has already been [reported](https://github.com/babel/babel/issues/12158) [a few](https://github.com/babel/babel/issues/12058) [times](https://github.com/babel/babel/issues/12169) before #10853, which was supposed to fix those issues and has been merged in `@babel/runtime@7.12.0`, as noted in their comments, but I can't figure out how to get the expected result.

**Comment by nicolo-ribaudo** [comment]
What is the extension needed for? We define `"exports"` in `@babel/runtime`'s `package.json`, so the extension is going to break compatibility with Node.js and Webpack 5.

**Comment by cdoublev** [comment]
Oh I'm sorry. I did see this export map but didn't realized then that having `core-js` and `@babel/runtime/helpers` imports both with/without file extension is not an issue.
