### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token using forceAllTransforms preset

### ISSUE THREAD

**Issue by Mogget24** [babel/babel#12703]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

- Manually transpiling using babel.transform() with **_forceAllTransforms_** preset
- After viewing the result, I got the "Uncaught SyntaxError: Invalid or unexpected token" error in console

**Input Code**

```js
babel.transform(code, {
                comments: false,
                compact: true,
                minified: true,
                presets: [
                    [
                        "@babel/preset-env",
                        {
                            targets: {
                                chrome: 59,
                                edge: 13,
                                firefox: 50,
                            },
                            // for uglifyjs...
                            forceAllTransforms: true,
                        },
                    ],
                ],
            }, (err, result) => {
                ...
            });
```

**Environment**
- Babel version(s): 7.12.3
- Node/npm version: Node 14.15.3 / npm 6.14.4
- OS: Windows 10
- Monorepo: yes
- How you are using Babel: webpack

**Possible Solution**

Removing the "\n" characters from generated line below, solves the issue
```js
throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")
```

**Comment by nicolo-ribaudo** [comment]
Can you share a repo which reproduces the issue?

**Comment by Mogget24** [comment]
> Can you share a repo which reproduces the issue?

I'm trying to create a clean repo in order to make it easy to find the issue as the problem has been found on a big (an private) repo I cannot share

**Comment by Mogget24** [comment]
I cannot replicate the issue on a clear repo so I think it might depend on an old Babel version on my original repo

The bug was a error-in-error situation generated by a call like
`js 
throw new TypeError`

The js compiler (in the console) was not able to parse the "\n" character inside the TypeError message

On the clean repo I correctly get
![working](https://user-images.githubusercontent.com/6150073/106613443-7d6a7680-656a-11eb-9f3a-998b0f72d920.PNG)
split in 2 lines

Feel free to close this issue if needed

**Comment by nicolo-ribaudo** [comment]
It's really unexpected that `\n` breaks it 🤔
As a workaround, if making sure that all your `@babel/` dependencies and subdeoendencies aren't up to date, you could try using `@babel/plugin-transform-runtime` to avoid injecting the helpers directly in the compiled code.

**Comment by liuxingbaoyu** [comment]
Since this issue has been inactive for a long time, I will close it for now, feel free to reopen it if the issue persists.
