### ISSUE TITLE
Template parser can't handle let declaration with syntactic placeholder variable

### ISSUE THREAD

**Issue by Zalathar** [babel/babel#12717]
## Bug Report

- [X] I would like to work on a fix!

**Current behavior**

When `template` is called with a `let` statement containing a syntactic placeholder for the variable (e.g. `let %%foo%% = 1`), the parser rejects it and mysteriously complains about `Unexpected reserved word 'let'`.

```js
Welcome to Node.js v15.6.0.
Type ".help" for more information.
> require("@babel/template/package.json").version
'7.12.7'
> template = require("@babel/template").default
> template("let %%foo%% = 1")()
Uncaught [SyntaxError: Unexpected reserved word 'let' (2:0)
  1 | /* @babel/template */;
> 2 | let %%foo%% = 1
    =============
] {
  loc: Position { line: 2, column: 0 },
  pos: 23,
  code: 'BABEL_TEMPLATE_PARSE_ERROR'
}
```

**Input Code**

```js
template("let %%foo%% = 1")({ foo: "x" });
```

These also give the same syntax error:

```js
template.statement("let %%foo%% = 1")({ foo: "x" });
template.statements("let %%foo%% = 1")({ foo: "x" });
template.program("let %%foo%% = 1")({ foo: "x" });
```

**Expected behavior**

The template invocation should return an AST for `let x = 1`.

These invocations return an AST as expected:

```js
// No placeholder
template("let x = 1")();

// Identifier placeholder
template("let FOO = 1;")({ FOO: "x" });

// const or var instead of let
template("const %%foo%% = 1")({ foo: "x" });
template("var %%foo%% = 1")({ foo: "x" });

// Ordinary identifier appears first
template("let a = 0, %%foo%% = 1")({ foo: "x" });

// Array destructuring
template("let [%%foo%%] = []")({ foo: "x" });
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

- Importing `@babel/template` directly from the Node repl; no Babel config.

**Environment**

```
$ npx envinfo --preset babel

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.0 - /usr/local/bin/npm
  npmPackages:
    @babel/template: ^7.12.7 => 7.12.7 
```

I can also reproduce this in AST Explorer and in RunKit, so it's unlikely to be environment-specific.

**Possible Solution**

**Additional context**

**Comment by Zalathar** [comment]
I'm not familiar with the parser internals, but this seems to be the relevant code:

https://github.com/babel/babel/blob/a0c1a9a9e41cfcc900afbe7901c3031ba3407284/packages/babel-parser/src/parser/statement.js#L118-L142

Normally, `let` is treated as a keyword if the next token is an identifier. However, the parser determines that the placeholder `%%foo%%` isn't an identifier (which would normally be the correct judgement in standard syntax), and concludes that `let` should not be treated as a keyword in this context.

The placeholder plugin doesn't have appear to have any hook to override this normally-correct behaviour, so the parse encounters a syntax error.

**Comment by nicolo-ribaudo** [comment]
We could overwrite `isLet` in `packages/babel-parser/src/plugins/placeholders.js`, and:
1. if `super.isLet()` returns `true`, return `true`
2. if `!this.isContextual("let")`, return `false`
3. If the next character and the following one are `%%`, return `true`

**Comment by Zalathar** [comment]
I already have a slightly different solution, but either way the change is small, so we can worry about the details after I write some more tests and post a PR.

**Comment by Zalathar** [comment]
While writing tests I noticed that `let %%lhs%%;` and `var %%lhs%%;` (without an initializer) also don't work, for reasons that are similar to this issue but not quite the same.

I'll leave those alone for now since they're easier to work around (just initialize to undefined) and I don't want to deal with scope-creep.
