### ISSUE TITLE
Unexpected token when yielding

### ISSUE THREAD

**Issue by jamwaffles** [babel/babel#1271]
This code fails to parse with an `Unexpected token` error on the `yield` line:

```javascript
function doStuff() {
	return new Promise((resolve, reject) => {
		resolve(1)
	})
}

// Unexpected token
let foo = yield doStuff()
```

Babel version 5.1.9
Node version 0.12.2

**Comment by sebmck** [comment]
Is the `yield` inside a generator?

**Comment by fkling** [comment]
Also yield doesn't really do anything with the promise (afaik). Do you mean to use `await` perhaps? That would also only work inside an `async` function.

**Comment by jamwaffles** [comment]
That snippet was tested both in file scope and inside a class method but not inside a generator. I've used the above syntax in another project and it worked absolutely fine so maybe it's something to do with my environment. I have the `es7.classProperties` flag turned on. Could this be a possible cause?

**Comment by sebmck** [comment]
`yield` needs to be used inside a generator.

**Comment by maggiesavovska** [comment]
It is possible to get this error if you ARE inside a generator but you're not yielding an actual promise.

**Comment by loganfsmyth** [comment]
This should only happen if outside a generator, but keep in mind that outside a generator could also be an issue if you are inside a callback, for instance

```
function * fn() {
  var callback = () => {
    yield 4;
  };
  callback();
}
```

would still cause that error since the parent function of the `yield` is the arrow function, not the generator.
