### ISSUE TITLE
React.Fragment closing tag syntax as text

### ISSUE THREAD

**Issue by Fox4148** [babel/babel#12720]
## Bug Report

**Current behavior**

showing text following the slash / in =>  </>, text appear as yellow

**Code**
using;
`ReactDOM.render(
        <>
		<App />
		<App2/>
	</>,'//<=Following this slash the code goes yellow (string text color => "same as this")
  	document.getElementById('root')
);`

**Expected behavior**

The closing tag should appear as the correct tag bracket color and the slash white

**Babel Configuration)**

- Filename: package.json`
{
  "dependencies": {
    "get-stdin": "4.0.1",
    "resolve": "1.1.6"
  },
  "private": true
}

**Environment**

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/preset-react: ^7.0.0 => 7.12.10ible Solution**

**Comment by fedeci** [comment]
If I understood your issue, the code goes yellow because you are defining a single-line comment (and there is a single quote token starting a `string` declaration).

Try this:
```js
This is the right way to define a comment
ReactDOM.render(<> <App /> <App2/> </>, /*<=Following this slash the code goes yellow (string text color => "same as this") */ document.getElementById('root'));


```

**Comment by kaicataldo** [comment]
As @fedeci mentions, you have a single `'` character before the comment. This is a syntax error (check it out [here](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=EoUwhgxgLgIg8gWQHQCcQDsAmIUAoAEAPAHxECCADhfgPSmGUUBMdRdANAOQ02EC8AMQD2AGxFCA7gEt0Ac3xQAFlIDO-FSLArFCxSHwQh2fLKEg1ATxBjJ-XCqgoZ8qCAAeUA6KEp8fUgBEKmAAtvpauqoBAJT4mEIQAK5h6FBIsiBQAKIiIClQAEIWAJKYuJwoQkJQnLHRANxAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-syntax-jsx%407.10.4)).

**Comment by Fox4148** [comment]
To better describe what my issue is, I will post an image
![image](https://user-images.githubusercontent.com/24654228/106363128-9f5ac380-62f4-11eb-8109-651a8af5509f.png)

**Comment by nicolo-ribaudo** [comment]
If that's SublimeText, you should report the bug to https://github.com/babel/babel-sublime

**Comment by Fox4148** [comment]
> 
> 
> If that's SublimeText, you should report the bug to https://github.com/babel/babel-sublime

Thank you for pointing the correct li0brary to post to solve this issue.
