### ISSUE TITLE
A bug of anonymous function tail recursion optimization

### ISSUE THREAD

**Issue by xiaorong61** [babel/babel#1272]
Please add tail recursion optimization support to **anonymous** function
like:
```ls
fibonacci = (x,y=0,z=1)->
  if x is 1 then z else fibonacci x-1,z,y+z
```

**Comment by sebmck** [comment]
This isn't a bug :) Function expressions are only optimised for self tail recursion if they're never reassigned. So:

```javascript
var foo = function () {
  foo();
};
```

will work but not:

```javascript
var foo;
foo = function () {
  foo();
};
```

Since it's an assignment and we deopt on those for various reasons.
