### ISSUE TITLE
parserOverride is not working

### ISSUE THREAD

**Issue by dxramax** [babel/babel#12736]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

parserOverride is not working

**Expected behavior**
the custom parser should be invoked instead of the default one.

- Filename: `babel.config.js`

```js
module.exports = (api) => {
  api.cache(false)
  return {
    plugins: [{
      parserOverride(code, opts) {
        return customParse(code, opts);
      },
    }]
  }
}
```

**Environment**
no specific environment

- Babel version(s): 7.12.12
- Node/npm version: v11.15.0
- OS: Linux
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: build from source

**Possible Solution**
More documentation on how to call parseOverride

**Additional context**

**Comment by JLHwung** [comment]
I can not reproduce this issue on #12740, the `parserOverride` is invoked as expected. Can you provide a reproduction repo?
