### ISSUE TITLE
Map option in babel-core API doesn't appear to work correctly

### ISSUE THREAD

**Issue by gandm** [babel/babel#1273]
I maybe misunderstanding this but when using babel-core, setting options and calling transformFile I get mixed results:-

If I set sourceMap to either 'inline' or 'both' I get a verbose base64 map line appended to my compiled result.code as well as a result.map. 

If I set sourceMao to truthy then I get nothing added to my code but result.map is returned. I was expecting a URL to be added to my code. I've tried adding various sourceMapName and sourceFileName but these don't seem to do anything.

**Comment by sebmck** [comment]
Currently there's no way to include the `//# sourceMappingURL=foo.js.map` comment which is what I assume you want?

**Comment by gandm** [comment]
Ok thanks. Yes I was expecting that but it's easy to add myself.

**Comment by sebmck** [comment]
Alright, great. Feel free to submit a PR adding a `"url"` option if it'd be easier. Relevant lines would are [here](https://github.com/babel/babel/blob/master/src/babel/transformation/file/index.js#L603). Thanks!
