### ISSUE TITLE
class-property transform leaks new.target in initializer to upper level

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#12737]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl#?browsers=IE%206&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1rAPYDsIBcBOArsDungBQCUiKq0OAFgJYQB0AYuutALxrhTVatXGByNg0AA49omAKYB3FjjB4A5nJw1UAXxp69YEHLw4yZeQrgV2nFpIpA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3&prettier=false&targets=&version=7.12.12&externalPlugins=)

`(new C).Foo.p` evaluates to `C`.

**Input Code**

```js
class C {
  constructor() {
    this.Foo = class {
      static p = new.target
    }
  }
}
```

**Expected behavior**
`(new C).Foo.p` should evaluate to `undefined`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
See REPL configs

**Environment**
REPL

**Possible Solution**
When we are converting class properties into `defineProperty` calls that are appended to the `class`, we should replace `new.target` in class field initializers to `undefined` if it is [associated](https://github.com/babel/babel/blob/bab5c62f907b6f90d094531ab22aa0a86d7c35a5/packages/babel-plugin-transform-new-target/src/index.js#L20-L30) to the class scope, otherwise `new.target` is leaked to the upper `new.target` values.

The replacing step can be inserted after `super()` is replaced in initializers:

https://github.com/babel/babel/blob/bab5c62f907b6f90d094531ab22aa0a86d7c35a5/packages/babel-helper-create-class-features-plugin/src/fields.js#L684

More test examples:

```js
class C {
  constructor() {
    this.Foo = class {
      static p1 = class { constructor() { new.target } } // should not replace
      static p2 = new function () { new.target } // should not replace
      static p3 = () => { new.target } // should replace
    }
  }
}
```

**Comment by nicolo-ribaudo** [comment]
If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js` and `exec.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest class-properties` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by iamfotx** [comment]
@nicolo-ribaudo I would love to work around this one...

**Comment by nicolo-ribaudo** [comment]
It's yours!

If you need any help feel free to ask.

**Comment by colinaaa** [comment]
Any progress on this? I can help on this!
