### ISSUE TITLE
plugin-proposal-class-properties "loose" mode not working

### ISSUE THREAD

**Issue by sorvell** [babel/babel#12734]
## Bug Report

Using the "loose" setting for `plugin-proposal-class-properties` is supposed to use assignment semantics instead of defineProperty as explained in the [documentation](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties#loose). However ,setting "loose" mode has no affect on the output.

**Current behavior**

[Example in REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAECC0G8BQ1oAcBOB7N0C80AZmCBAKYDcSAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.12.1)

**Input Code**

```js
class A {
  prop = false;
}
```

**Expected behavior**

```js
class A {
  constructor() {
    this.prop = false;
  }
}
```

**Actual behavior**

```js
class A {
  constructor() {
    _defineProperty(this, "prop", false);
  }

}
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

```js
{
  "plugins":[
    ["@babel/plugin-proposal-class-properties", {"loose": true}]
    ]
}
```

**Environment**

- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 14/npm 7]
- OS: [e.g. macOS 10.15.4]
- Monorepo: no
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
In the REPL example you enabled loose mode for `preset-env`, but not for the `class-properties` plugin (which isn't possible in the REPL).

Can you also reproduce this locally? If you can, are you sure you don't have any other config file?

**Comment by sorvell** [comment]
OK, no it doesn't repro locally. The issue I'm seeing seems to be related to https://github.com/babel/babel/issues/12040. I'll close this and post info there.
