### ISSUE TITLE
[TS] "Abstract methods can only appear within an abstract class" on "export default abstract class"

### ISSUE THREAD

**Issue by gentoid** [babel/babel#12745]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

I'm getting the `Abstract methods can only appear within an abstract class.` error on `export default abstract class AbstractClass` after bumping `"@babel/core"` from `"7.12.10"` to `"7.12.13"` 

- [I have a repo reproducing the behaviour](https://github.com/gentoid/babel-abstract-method-error-repro)

**Input Code**

_Copied from the repro repo_

```ts
abstract class WorkingAbstractClass {
    abstract test(): void;
}

class SomeClass extends WorkingAbstractClass {
    test(): void {
        console.log('ok!');
    }
}

export abstract class AbstractClassIsWorkingToo {
    abstract test(): void;
}

// this is the case where Babel raises the error
export default abstract class NotWorkingAbstractClass {
    abstract test(): void;
}
```

**Expected behavior**

I guess it should be according to the TS behaviour, i.e., this case should be allowable.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

_Copied from the repro repo_

```js
{
    "presets": [
        "@babel/typescript"
    ]
}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.16.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.5 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.11 - ~\scoop\apps\yarn\current\global\node_modules\.bin\npm.CMD
  npmPackages:
    @babel/cli: ^7.12.13 => 7.12.13
    @babel/core: ^7.12.13 => 7.12.13
    @babel/preset-typescript: ^7.12.13 => 7.12.13
```

**Possible Solution**

Do not treat such cases as a syntax error

**Additional context**

**Comment by Mrjeff578575** [comment]
the same issue

**Comment by nicolo-ribaudo** [comment]
Fixed in [v7.12.14](https://github.com/babel/babel/releases/tag/v7.12.14).

**Comment by forivall** [comment]
Was caused by #12686

**Comment by gentoid** [comment]
seems it wasn't published to the NPM registry

**Comment by nicolo-ribaudo** [comment]
https://www.npmjs.com/package/@babel/parser/v/7.12.14

**Comment by gentoid** [comment]
Ah, thanks. I wrongly checked `@babel/core`
