### ISSUE TITLE
@babel/parser(ts): TSUnionType is not including leading pipe into range

### ISSUE THREAD

**Issue by armano2** [babel/babel#12754]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

`TSUnionType` with leading pipe `|` has is not including leading pipe character into its range.

this issue is also present for `TSIntersectionType`

- [REPL babel](https://astexplorer.net/#/gist/7ea7e76e3a444af545b8ed14aca37181/6d8d93d31e30eafe2081e34c33d484f18b34ab2c)
- [REPL typescript](https://astexplorer.net/#/gist/7ea7e76e3a444af545b8ed14aca37181/c4cb2430bc58fa52b1c25738dc2af746764c1b10)
- [REPL typescript-eslint](https://astexplorer.net/#/gist/7ea7e76e3a444af545b8ed14aca37181/049f5f728616d2afd4ccec455e21fdddfe3f5b94)

**Input Code**

```ts
type x = 
  | string
  | number
```

**Expected behavior**
Babel should include leading `|` character into range of TSUnionType, 
note: leading `|` is optional and can be omitted

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
enabled plugins

```js
[
    'classProperties',
    'decorators-legacy',
    'estree',
    'typescript',
]
```

**Environment**

- Babel version(s): 7.12.14
- Node/npm version: 10-15
- OS: win/linux/mac
- Monorepo: no
- How you are using Babel: parse(....)

**Possible Solution**

**Additional context**

**Comment by fedeci** [comment]
Same for `&` operator.

**Comment by existentialism** [comment]
@fedeci thanks for the quick PR :+1: 💯, mind mentioning next time you're working on a fix so we can mark it as assigned?

**Comment by fedeci** [comment]
Sure, sorry if I didn't😬

**Comment by existentialism** [comment]
@fedeci no worries at all!
