### ISSUE TITLE
@babel/parser(ts): TSTypePredicate should include asserts into its range

### ISSUE THREAD

**Issue by armano2** [babel/babel#12761]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

I did some testing for this change #12678 and fix does not seem to be fully correct, right now `asserts` keyword is not included into range, 

this issue seem to be present only when `this` keyword is used, in other cases range is correct

related ticket #12676

**Input Code**

```js
class AssertsFoo {
  isBar(): asserts this is string {
    return;
  }
}
```

**Expected behavior**
`asserts` keyword should be included into range of TSTypePredicate 

**Environment**

- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Comment by fedeci** [comment]
Working on this, the solution should be similar to #12757
