### ISSUE TITLE
@babel/generator comment deduplication removes too many comments

### ISSUE THREAD

**Issue by mischnic** [babel/babel#12769]
## Bug Report

- [ ] I would like to work on a fix!

**Input Code**

```js
import { parse } from "@babel/parser";
import generator from "@babel/generator";
import t from "@babel/types";

const code1 = `
// hello!
a();
`;

const code2 = `
// hello
b();
`;

let ast1 = parse(code1).program;
let ast2 = parse(code2).program;

let ast = t.program([...ast1.body, ...ast2.body]);

console.log(generator.default(ast).code);
```

**Expected behavior**

```js
// hello!
a();
// hello
b();
```

**Current behavior**

```js
// hello!
a();
b();
```

**Environment**

```json
    "@babel/generator": "7.12.15",
    "@babel/parser": "7.12.15",
```

**Possible Solution**

**Additional context**

I was surprised that there are cases where comment exists twice (as leading and trailing), e.g. 
```js
if (1) {
  a();
}
// /* */
else {
  b();
}
```
. Looks like babel-generators "workaround" for this isn't quite right.

Distantly related to https://github.com/parcel-bundler/parcel/issues/5787

**Comment by kaicataldo** [comment]
This does seem like unexpected/destructive behavior to me, though I think the example given in https://github.com/babel/babel/pull/13169#issue-617434389 is a more realistic repro case. Curious what the rest of the team thinks.

**Comment by kaicataldo** [comment]
I don't think this is fixed yet since we split https://github.com/babel/babel/pull/13169 into two separate PRs. Reopening for now.
