### ISSUE TITLE
@babel/parser(ts): incorrect multiline parsing of module declaration

### ISSUE THREAD

**Issue by armano2** [babel/babel#12773]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
New line after `module` should not generate `TSModuleDeclaration` 

https://github.com/microsoft/TypeScript/blob/master/tests/baselines/reference/asiPreventsParsingAsAmbientExternalModule01.js

**Input Code**

```js
declare                // this is the identifier 'declare'
module                 // this is the identifier 'module'
"my external module"   // this is just a string
{ }                    // this is a block body
```

**Expected behavior**
I do expect that babel is going to generate 2 identifiers and string and block body, instead of that it generates:
```diff
 ExpressionStatement: Identifier: declare
- TSModuleDeclaration: TSModuleBlock
+ ExpressionStatement: Identifier: module
+ ExpressionStatement
+ ExpressionStatement
```

**Environment**

- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Comment by fedeci** [comment]
I am working on this!
