### ISSUE TITLE
babel-parse(ts): Unfriendly syntax error for accesibility after readonly

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#12772]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Syntax error `Unexpected token` is thrown.

- [REPL](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oCcCmYAm8AdiAJ7QAOmAlgG5gAu20AZogNyoC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.12.14&externalPlugins=)

**Input Code**

```ts
class Foo {
  readonly private foo;
}
```

**Expected behavior**

Recoverable syntax error `'private' modifier must precede 'readonly' modifier.` is thrown. Like [TS](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oCcCmYAm8AdiAJ7QAOmAlgG5gAu20AZogNyoC+qQA).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

**Environment**

**Possible Solution**

**Additional context**

I found this while working on #12767

**Comment by taejs** [comment]
Hi.  @sosukesuzuki 
If you're not available, Can I give a look on it?

**Comment by sosukesuzuki** [comment]
@taejs Sure! Please go ahead!

**Comment by taejs** [comment]
I found it's fixed by #13096!

@nicolo-ribaudo 
This issue can be closed.
