### ISSUE TITLE
Global const is undefined in async function

### ISSUE THREAD

**Issue by marcolilli** [babel/babel#12784]
## Bug Report

- [ ] I would like to work on a fix!
 
I ran into a strange behaviour with babel together with a certain [browserlist](https://github.com/browserslist/browserslist) configuration in a [create-react-app](https://github.com/facebook/create-react-app).

---

**Input Code**
- I created a [repository](https://gitlab.com/marcolilli/async-scoping-issue) with a minimal working example to reproduce the issue. 
```js
const foo = 'foo'

const asyncFunc = async () => {
    if (false) {
        const foo = 'bar'
        console.log('foo in if', foo) // this line is only to use the local variable foo once
    } else {
        console.log('foo in else', foo) // foo is undefined
    }
}

asyncFunc()
```

**Current behavior**
The variable `foo` is `undefined` inside of the else-block of the condition. 

**Expected behavior**
Since `foo` is defined globally I expect it to be "foo" in the else-block. It actually is "foo" when compiling the code with a different browserlist setting.

---

**Environment**

- Dependencies in `package.json`
```js
 "dependencies": {
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.6.3",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.2",
    "web-vitals": "^1.1.0"
}
```
- Browserlist configuration in `package.json`
```js
{
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all",
      "not ie <= 11"
    ]
  }
}
```

---

**Additional context**
* This is is only reproducible with create-react-App. The code works when just using babel.
* Looking at the compiled code (screenshot below) it seems that an empty **var** `foo` gets defined in line 25. My guess is that in line 30 that empty **var** `foo` is being logged instead of the previously created **const** `foo`.

![Screenshot 2021-02-09 at 18 07 38](https://user-images.githubusercontent.com/25379471/107400041-b58d2e80-6b01-11eb-8236-625ead1e9796.png)

---

**`npx envinfo --preset babel` Output:**
**System:**
- OS: macOS 11.2

**Binaries:**
- Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
- npm: 6.14.11 - ~/.nvm/versions/node/v14.15.1/bin/npm

**Comment by marcolilli** [comment]
Btw: I've already [posted](https://babeljs.slack.com/archives/C0DFJT81H/p1612515441081700) this issue in slack, but didn't get any useful information.

**Comment by nicolo-ribaudo** [comment]
This is likely a bug with https://github.com/facebook/regenerator.

Recently we have received different reports about regenerator not working with some ES features, I'll take a look at all of them next week probably.

**Comment by marcolilli** [comment]
@nicolo-ribaudo  Any news?

**Comment by liuxingbaoyu** [comment]
It has been fixed.
[repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MDkCRoFDdJWAQwgE8xgAxAV3JRmLOBgAoBKFAPhgG9sZ-YASzgs4hADYQApu14D5MfNHiI6aAEaEATjgUClIcVIB04kAHNmGVYLBC4aADQqQ7APRuYUABaCIMcVspIX9wcRIvJCppL29gs2AJGAA3bUFCdSMXGHBgKT4BAF8YKUlguT1FcAhDEzNLayRbErKnF3dPTBCYGgATKTgg3oL-Quwx7AZyanI2IA&debug=false&forceAllTransforms=true&modules=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.22.8&externalPlugins=&assumptions=%7B%7D)
