### ISSUE TITLE
Wrong code generation

### ISSUE THREAD

**Issue by socketpair** [babel/babel#1279]
Suppose code:

```
async function proxify() {
    try {
        while (true) {
            break;
        }
    }
//    catch(c) {
//        console.log('should never happen');
//    }
    finally {
        console.log(1);
    }
    console.log(2);
}

proxify();
```

This code, as I expect should do ``log(1)`` and ``log(2)`` and then exit. If you try that, it wil really do ``log(1)`` in endless loop. BUG.

BUT(!)(!) If I add exception handler (uncomment lines) bug is not reproduced (!) and everything is work as expected.

**Comment by sebmck** [comment]
This is a bug with [regenerator](https://github.com/facebook/regenerator), please report it there.

**Comment by socketpair** [comment]
https://github.com/facebook/regenerator/issues/192

done

**Comment by socketpair** [comment]
Fixed in regenerator!

**Comment by sebmck** [comment]
Great. It's fixed in Babel then too :) You just have to reinstall it to get
the latest version of regenerator.

On Thursday, 16 April 2015, Коренберг Марк <notifications@github.com> wrote:

> Fixed in regenerator!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1279#issuecomment-93846099>.
>


-- 
Sebastian McKenzie

**Comment by stefanpenner** [comment]
wooho :)
