### ISSUE TITLE
[@babel/eslint-plugin] better no-undef; static no-undef

### ISSUE THREAD

**Issue by MasterOfBob777** [babel/babel#12798]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**
When using static properties on classes their existence doesn't get checked; `no-undef` doesn't work with static anything.

**Describe the solution you'd like**
I feel like a simple check to check if it's been defined would be sufficient.

**Describe alternatives you've considered**.
I don't think this is very applicable in this scenario, but maybe not including it in the first place. 

**Documentation, Adoption, Migration Strategy**
Just a `@babel/no-undef`.

**Comment by JLHwung** [comment]
This issue was fixed in #12370, it will be shipped in Babel 7.13. `no-undef` will support class properties then.
