### ISSUE TITLE
Named alias import documentation

### ISSUE THREAD

**Issue by kedashoe** [babel/babel#1280]
This is low/no priority, but figured I'd mention it since it lead me on a wild goose chase. This page

https://babeljs.io/docs/usage/modules/

says

Named alias import:

    import {foo as bar} from "foo";
becomes

    var bar = require("foo").foo;

However that does not appear to be what babel actually does, rather this happens

    import { foo as bar } from "foo";
becomes

    var _bar = require("foo");

and it's not until you actually use `bar` that it becomes apparent what babel is doing

    import { foo as bar } from "foo";
    let x = bar(100);
becomes

    var _bar = require("foo");
    var x = _bar.foo(100);

Some of the other examples do show what actually happens rather than simply the spirit of what happens, eg

    import * as foo from "foo";
becomes

    var foo = _interopRequireWildcard(require("foo"));

so maybe a small update to the docs that reflects what actually happens for named alias imports is warranted? Either way, thanks for the great project!

**Comment by sebmck** [comment]
Please see the README :smile: 

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by kedashoe** [comment]
haha README was so short I didn't bother reading it! Thanks, PR submitted
