### ISSUE TITLE
babel-parser(ts): Throw syntax error for not defined export in TS module declarations

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#12801]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

Syntax error ` Export 'foo' is not defined (3:11)` is thrown.

- [REPL](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=CYUwxgNghgTiAEBbA9sArhBAiARrL8A3gFDzwCWiADsjAC5HwBmyy8AvszMovFi8iwBuUvBAAPGvUYCOI9sSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.12.15&externalPlugins=)

**Input Code**

```ts
declare module "bar" {
  import { foo } from "foo";
  export { foo };
}
```

**Expected behavior**

No error is thrown.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**

**Possible Solution**

**Additional context**

**Comment by liuxingbaoyu** [comment]
It has been fixed in the latest version.
