### ISSUE TITLE
Unnecessary requires

### ISSUE THREAD

**Issue by wood-chris** [babel/babel#12802]
## Bug Report

**Current behavior**

Targeting IE11 creates `require`s which are unnecessary. For example, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace shows that IE has supported this function since version 4, but targeting just IE11 results in:

    require("core-js/modules/es.string.replace.js");

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Relevant portion of Gruntfile:

```
babel: {
    options: {
        presets: [
            ["@babel/preset-env", {
                "targets": {
                    "ie": "11"
                 },
                "useBuiltIns": "usage",
                "corejs": 3.8
            }]
        ]
    },
    dist: {
        files: {
            "assets_src/main_babel.js": "assets_src/main.js"
        }
    }
}
```

**Environment**

```
$ npx envinfo --preset babel

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    npm: 7.3.0 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.12.13 => 7.12.13 
    @babel/core: ^7.12.10 => 7.12.10 
    @babel/preset-env: ^7.12.11 => 7.12.11 
    grunt-babel: ^8.0.0 => 8.0.0 
```

**Comment by nicolo-ribaudo** [comment]
The compat data for `core-js` 3 is not maintained by us, but it's at https://github.com/zloirock/core-js/tree/master/packages/core-js-compat.

Usually it's a browser bug not reported by MDN but fixed by a `core-js` polyfill.

**Comment by nicolo-ribaudo** [comment]
In this specific case, if you pass an object with a `Symbol.replace` key to `"".replace`, IE11 doesn't correctly handle it.
