### ISSUE TITLE
parser(ts): TSTypeParameter name should be an Identifier

### ISSUE THREAD

**Issue by armano2** [babel/babel#12825]
## Feature Request

- [ ] I would like to work on this feature!

#### This change can/should be considered as a breaking change.

**Is your feature request related to a problem?**

Make TSTypeParameter name property an Identifier.
There is no easy way to traverse over this field and this is also not aligned with other uses of generic/template parameters/arguments 

TSTypeReference and TSTypeParameter has simmilar use -> both can be used in generic/template parameters

```ts
f<F>()

TSTypeReference
  - typeName: Identifier
```

```ts
function f<T>() {}

TSTypeParameter
  - name: string
```

```ts
function f< /* x */ T = 2>() {}
function f<T>() {}
function f<T = 2>() {}
```

**Describe the solution you'd like**

`TSTypeReference` node should have property name of type `Identifier` instead of `string`

**Describe alternatives you've considered**.

additionally we could align also name of property `typeName` and `name` (I'm not sure about this)

**Documentation, Adoption, Migration Strategy**

### Additional info

prettier integration issue https://github.com/JamesHenry/typescript-estree/issues/109 (yes old one i forgot to repost it here)

**Comment by fedeci** [comment]
Should we add this under `BABEL_8_BREAKING` or keep both `name: string` and `typeName: Identified` deprecating the first one?

**Comment by armano2** [comment]
I'm insur about change to name, we could do this, but it's better to hear opinion of other ppl as this change will be a breaking change for babel and typescrip-eslint

**Comment by fedeci** [comment]
Considering that Typescript behaviour is:
`TypeReference => typeName`
`TypeParameter => name`
I think we should not touch `TSTypeReference`, but parse the entire `Identifier` for `TSTypeParameter` instead of just his name.
