### ISSUE TITLE
Webpack 5 error for missing extention for regenerator runtime when `absoluteRuntime` is used and a .mjs file is transformed

### ISSUE THREAD

**Issue by mbehzad** [babel/babel#12824]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

babel-loader is used with webpack with the `"@babel/plugin-transform-runtime` plugin and `regenerator` AND `absoluteRuntime` path . Weback 5 (since webpack v5.0.0-beta.30,) when parses an es module (.mjs or type: module), tries to enforce the node spec regarding the deep imports, where the file extention should be present and when it's missing, it throws an error:
```
ERROR in ./src/index.mjs 1:0-114
Module not found: Error: Can't resolve '.../node_modules/@babel/runtime/regenerator' in '...\src'
Did you mean 'index.js'?
BREAKING CHANGE: The request '.../node_modules/@babel/runtime/regenerator' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

- [REPL]
minimal reproducible repo: https://github.com/mbehzad/webpack-babel-absoluteruntime-issue

**Input Code**
cmd: `webpack build`    

**Expected behavior**

When the runtime imports are injected, and the user has specifies a path to babel-runtime and therefor not the module name (and package exports maps) are used, the file extensions should be in the imports so webpack is happy.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `weback.config.js`

```js
const path = require("path");

module.exports = {
  mode: "development",
  entry: "./src/index.mjs",
  module: {
    rules: [
      {
        test: /\.m?js$/,
        use: {
          loader: "babel-loader",
          options: {
            presets: [
              [
                require.resolve("@babel/preset-env"),
                {
                  targets: {
                    ie: 11
                  }
                }
              ]
            ],
            plugins: [
              [
                require.resolve("@babel/plugin-transform-runtime"),
                {
                  corejs: false,
                  regenerator: true,
                  useESModules: false,
                  helpers: false,
                  absoluteRuntime: path.dirname(
                    require.resolve("@babel/runtime/package.json")
                  )
                }
              ]
            ]
          }
        }
      }
    ]
  }
};

```

**Environment**

```
- Babel version(s): [v7.12.0]
- Node/npm version: [Node 15.3.0/npm 7.0.14]
- OS: [Windows 10]
- Monorepo: [no]
- How you are using Babel: [ `webpack`]
- {
    "@babel/core": "7.2.0",
    "@babel/plugin-transform-runtime": "7.12.15",
    "@babel/preset-env": "7.12.16",
    "babel-loader": "8.2.2",
    "webpack": "5.22.0",
    "webpack-cli": "4.5.0"
  }
  ```

**Possible Solution**

I guess in `babel-plugin-transform-runtime/index.js` the extentions / index.js should be added to the end of the runtime module names for the imports.
**Additional context**

N/A

**Comment by HitkoDev** [comment]
Thank you, I spent waaaay too long figuring what's causing the problem and how to solve it. Hope the fix gets merged soon.
