### ISSUE TITLE
Constant Propagation for primitive values

### ISSUE THREAD

**Issue by phpnode** [babel/babel#1283]
It'd be nice to have an optional transformer that can do constant propagation for primitive values, especially when combined with the `utility.inlineExpressions` transformer. 

```js
const SOME_VALUE = 123;
const SOME_OTHER_VALUE = 2;
const SOME_STRING = "wat";

function foo () {
    return [
      SOME_VALUE * SOME_OTHER_VALUE,
      SOME_STRING
    ];
}
```

could compile to

```js
const SOME_VALUE = 123;
const SOME_OTHER_VALUE = 2;
const SOME_STRING = "wat";

function foo () {
    return [
      246,
      "wat"
    ];
}
```

or with `utility.deadCodeElimination` enabled:
```js
function foo () {
    return [
      246,
      "wat"
    ];
}
```

**Comment by bucaran** [comment]
:+1:

**Comment by sebmck** [comment]
Closing this as I'd like for these types of transformers to be done in userland [plugins](http://babeljs.io/docs/usage/plugins). Feel free to use the [utility.inlineExpressions](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/utility/inline-expressions.js) transformer as reference (just remove the `Identifier` function).
