### ISSUE TITLE
babel-cli chmod doesn't always work

### ISSUE THREAD

**Issue by siddharthvp** [babel/babel#12835]
## Bug Report

Babel cli is trying to run chmod on built files: https://github.com/babel/babel/blob/3af936fc2b39e92d92d4b02129bb3666b19268eb/packages/babel-cli/src/babel/util.js#L8 called at https://github.com/babel/babel/blob/3af936fc2b39e92d92d4b02129bb3666b19268eb/packages/babel-cli/src/babel/dir.js#L69

This is problematic in some situations - such as when the files are being built on a remote server (via a continuous integration workflow) and the SSH user isn't the owner of the files. In such cases, chmod fails and thus the transpilation. 

It would be helpful if there could be an opt-out for this behaviour.

**Environment**

- Babel version(s): babel-cli 7.12.16
- Node/npm version:  Node: 14.12.0, npm: 6.14.8 
- OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
- How you are using Babel: babel-cli

**Comment by nicolo-ribaudo** [comment]
We could wrap it in a try/catch and just print a warning if it fails.

**Comment by siddharthvp** [comment]
Yes that would be ideal, I think.

**Comment by nicolo-ribaudo** [comment]
I'm marking this as a good first issue.

I'm not sure about how we could write a test for it, so updating the source code is enough (but if anyone can write a test please do so!)
