### ISSUE TITLE
@babel/preset-env/lib/utils has been removed

### ISSUE THREAD

**Issue by markhoney** [babel/babel#12856]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Nuxt JS relies on @babel/preset-env/lib/utils, which appears to have been removed in version 7.13

**Input Code**

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

**Environment**

- Babel version(s): v7.13.0
- Node/npm version: Node 14
- OS: macOS 11.2.1
- Monorepo: Lerna
- How you are using Babel: webpack

**Possible Solution**

Re-add the file utils.js to @babel/preset-env

**Additional context**

**Comment by nicolo-ribaudo** [comment]
We can check if we can add a stub back to restore the original functionality, but that file has never been part of the public API.

**Comment by markhoney** [comment]
Adding it back in, for now, would be great, as I'm sure there will be a few Nuxt users who are going to have issues with this. In the long term, hopefully Nuxt will work around this.

**Comment by nicolo-ribaudo** [comment]
Ok it looks like it's easier to make a PR to remove that usage in Nuxt.js, I think I'll do that instead.

**Comment by JLHwung** [comment]
Closing this issue as https://github.com/nuxt/nuxt.js/pull/8883 is merged. Importing internal Babel files will throw on Babel 8, as we mentioned in [Babel 8 release plan](https://github.com/babel/babel/issues/10746)

> If anyone else is relying on internal Babel files, please let us know!
