### ISSUE TITLE
Internal error in the corejs2 provider: unknown polyfill "es6.array.slice"

### ISSUE THREAD

**Issue by it1011** [babel/babel#12859]
## Bug Report
after upgrade babel to 7.13.* I got this error if I use Array.silce in my code:
**Internal error in the corejs2 provider: unknown polyfill "es6.array.slice"**

**Current behavior**
![image](https://user-images.githubusercontent.com/30334815/108798722-7a8efe80-75c9-11eb-89e3-5e5c0c8b46a2.png)

**Input Code**

```js
data.slice(0, 20)
```

**Expected behavior**
it seems that es6.array.slice shouldn't be a polyfill

```
- Babel version(s): [e.g. v7.13.0]
- How you are using Babel: `webpack`

**Comment by paradite** [comment]
same issue here. downgrading `@babel/core` to `7.12.17` as it still uses `@babel/traverse@7.13.0`

**Comment by sky-leaf** [comment]
Temporary solution：downgrading @babel/preset-env to 7.12.17 can solve the problem. Because @babel/preset-env ci failed to build

**Comment by eligao** [comment]
It seems we have `es6.array.slice` missing here?
https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/corejs2-built-ins.json

**Comment by xhlwill** [comment]
downgrade

**Comment by nicolo-ribaudo** [comment]
Working on this

**Comment by nicolo-ribaudo** [comment]
I published a quick patch of `babel-plugin-polyfill-corejs2@0.1.4` (an internal dependency) to simply ignore `es6.array.slice`; @eligao is working on adding back support for it.

**Comment by it1011** [comment]
> babel-plugin-polyfill-corejs2

Build sucess with **@babel/preset-env 7.13.5** and **babel-plugin-polyfill-corejs2@0.1.4**,

Thanks @nicolo-ribaudo
