### ISSUE TITLE
Any Gatsby project errors with "cannot read property 'resolved' of undefined"

### ISSUE THREAD

**Issue by KyleAMathews** [babel/babel#12851]
With the latest 7.13 release. If I downgrade to 7.12.17 it works again.

**Comment by nicolo-ribaudo** [comment]
Can you share the complete stack trace?

**Comment by gillkyle** [comment]
I am seeing the same, with a minimal gatsby site (created by `npm init gatsby -y`).

The logs I'm getting from `gatsby develop` are:

```
 ERROR #98123  WEBPACK

Generating development SSR bundle failed

Cannot read property 'resolved' of undefined

File: .cache/ssr-develop-static-entry.js

not finished Building development bundle - 0.301s
```

I was able to unblock myself by adding `resolutions` to my package.json as well:

```
  "resolutions": {
    "@babel/core": "7.12.0"
  }
```

**Comment by gillkyle** [comment]
Here's a minimal site with the latest packages installed where I'm seeing the error: https://codesandbox.io/s/github/gillkyle/babel-repro

cc @nicolo-ribaudo (or whoever, thanks for looking into this 🙂)

**Comment by KyleAMathews** [comment]
The error is happening in our config merging logic https://github.com/gatsbyjs/gatsby/blob/255b56575f69787884655a3642afbb3ea90f8869/packages/gatsby/src/utils/babel-loader-helpers.js#L117-L142

This bit of code https://github.com/gatsbyjs/gatsby/blob/255b56575f69787884655a3642afbb3ea90f8869/packages/gatsby/src/utils/babel-loader-helpers.js#L100-L105 used to generate an object but now it returns a generator (console.log outputs) `Object [Generator] {}`

**Comment by nicolo-ribaudo** [comment]
Thanks, working on a fix.

**Comment by KyleAMathews** [comment]
Another one https://github.com/babel/babel/issues/12854
