### ISSUE TITLE
7.13 _Object$getOwnPropertySymbols is not defined

### ISSUE THREAD

**Issue by zllkjc** [babel/babel#12860]
## Bug Report

Hello

**Current behavior**
My project use @babel/plugin-transform-runtime in rollup

After build my package，the following code is inserted

```javascript
function ownKeys(object, enumerableOnly) { 
   var keys = _Object$keys2(object); 
   if (_Object$getOwnPropertySymbols) { 
      var symbols = _Object$getOwnPropertySymbols(object);
  }
 // other code...
}
```
but `_Object$getOwnPropertySymbols` is not defined in v7.13.2

**Expected behavior**
rollback @babel/plugin-transform-runtime v7.12.17 , everything is right

the following code is inserted

```javascript
var _Object$getOwnPropertySymbols = require("@babel/runtime-corejs3/core-js-stable/object/get-own-property-symbols");
`` 

**question**

is there some new API in v7.13 ？

or is it a bug ?

```
- Babel version(s): v7.13.2
- Node/npm version: Node 12
- OS: macOS
- Monorepo: yes
- How you are using Babel: rollup

**Comment by nicolo-ribaudo** [comment]
This is the same as https://github.com/babel/babel/issues/12863. It _should_ be fixed, I'm waiting for someone to confirm it.
