### ISSUE TITLE
Uncaught ReferenceError: _forEachInstanceProperty is not defined

### ISSUE THREAD

**Issue by Edge00** [babel/babel#12863]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
Error occurred after upgrade to latest version

```
- Babel version(s): v7.13.1
- Node/npm version: v12.13.1
- OS: macOS 11.2.1
- Monorepo: No
- How you are using Babel: webpack
```

![image](https://user-images.githubusercontent.com/23715779/108811947-2431b800-75e9-11eb-9334-1b879cea1dd8.png)

**Comment by simaQ** [comment]
I got another error when i upgrade to latest version.

`Uncaught TypeError: _interopRequireDefault is not a function`

**Comment by duan602728596** [comment]
I got another bug `_Reflect$construct is not defined`. I tested that I found that Babel compile is correct, but there is an error after packaging webpack.

**Comment by nicolo-ribaudo** [comment]
Oh thanks for start investigating!
If you could share a small repository that shows it that would make it easier to fix the bug 🙏

**Comment by duan602728596** [comment]
> Oh thanks for investigating!
> If you could share a small repository that shows it that would make it easier to fix the bug 🙏

Maybe these are the same type of errors? This can be used as a reference.
https://github.com/duan602728596/webpack-class-bug
https://github.com/webpack/webpack/issues/12758

**Comment by nicolo-ribaudo** [comment]
Working on a fix

**Comment by nicolo-ribaudo** [comment]
@dollysingh3192 (I'm replying here)

The PR that caused this is https://github.com/babel/babel/pull/12845.

If anyone could create a github repository that shows the bug it would be easier for me to fix it :pray:

**Comment by nicolo-ribaudo** [comment]
This should be fixed in `@babel/helper-define-polyfill-provider` 0.1.1; I'll publish a `@babel/preset-env` release to make it easier to force the upgrade.

**Comment by nicolo-ribaudo** [comment]
I'm keeping this open until someone confirms that https://github.com/babel/babel/issues/12863#issuecomment-784131383 works and I release a `transform-runtime` version.

**Comment by dollysingh3192** [comment]
@nicolo-ribaudo ,

I checked and found that ```"./node_modules/@babel/runtime-corejs3/core-js-stable/reflect/construct.js"``` is injecting correctly with babel "7.13.0" successfully with @babel/helper-define-polyfill-provider 0.1.1 change.

But after this change jasmine test case's are failing. I raised a bug [here](https://github.com/jasmine/jasmine/issues/1878#issuecomment-772675097) previously  where ```window.setTimeout``` and ```setTimeout``` was different. Here one is jasmine definition(which is correct) and other one is shim by babel

But now they both have same definition. Screenshot

<img width="833" alt="Screen Shot 2021-02-23 at 5 47 14 PM" src="https://user-images.githubusercontent.com/8565108/108842541-6fef5c00-75ff-11eb-88be-0d8f00f00283.png">

**Comment by nicolo-ribaudo** [comment]
Thanks for confirming!

I would expect `window.setTimeout` and `setTimeout` to always be the same, since global functions (such as `setTimeout`) are what is defined on the `window` object.

However, if you want con continue the discussion about it and look for a workaround for what you need, please open an issue at https://github.com/babel/babel-polyfills :pray:

**Comment by nicolo-ribaudo** [comment]
This should be fixed now

**Comment by YanYuanFE** [comment]
"@babel/runtime-corejs3": "^7.13.6", not work

**Comment by YanYuanFE** [comment]
"@babel/plugin-transform-runtime": "^7.13.9", fixed.
