### ISSUE TITLE
@babel/runtime 7.13.3 unexpected cjs modules in esm modules

### ISSUE THREAD

**Issue by afc163** [babel/babel#12861]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

https://unpkg.com/@babel/runtime@7.13.2/helpers/createSuper/_index.mjs

```js
import getPrototypeOf from "@babel/runtime/helpers/getPrototypeOf";
import isNativeReflectConstruct from "@babel/runtime/helpers/isNativeReflectConstruct";
import possibleConstructorReturn from "@babel/runtime/helpers/possibleConstructorReturn";
export default function _createSuper(Derived) {
  var hasNativeReflectConstruct = isNativeReflectConstruct();
  return function _createSuperInternal() {
    var Super = getPrototypeOf(Derived),
        result;

    if (hasNativeReflectConstruct) {
      var NewTarget = getPrototypeOf(this).constructor;
      result = Reflect.construct(Super, arguments, NewTarget);
    } else {
      result = Super.apply(this, arguments);
    }

    return possibleConstructorReturn(this, result);
  };
}
```

**Expected behavior**

Should it be?

```diff
```js
- import getPrototypeOf from "@babel/runtime/helpers/getPrototypeOf";
- import isNativeReflectConstruct from "@babel/runtime/helpers/isNativeReflectConstruct";
- import possibleConstructorReturn from "@babel/runtime/helpers/possibleConstructorReturn";
+ import getPrototypeOf from "@babel/runtime/helpers/esm/getPrototypeOf";
+ import isNativeReflectConstruct from "@babel/runtime/helpers/esm/isNativeReflectConstruct";
+ import possibleConstructorReturn from "@babel/runtime/helpers/esm/possibleConstructorReturn";
export default function _createSuper(Derived) {
  var hasNativeReflectConstruct = isNativeReflectConstruct();
  return function _createSuperInternal() {
    var Super = getPrototypeOf(Derived),
        result;

    if (hasNativeReflectConstruct) {
      var NewTarget = getPrototypeOf(this).constructor;
      result = Reflect.construct(Super, arguments, NewTarget);
    } else {
      result = Super.apply(this, arguments);
    }

    return possibleConstructorReturn(this, result);
  };
}
```

like: https://unpkg.com/browse/@babel/runtime@7.12.0/helpers/esm/createSuper.js

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.3.0/bin/yarn
    npm: 7.0.14 - ~/.nvm/versions/node/v15.3.0/bin/npm
  npmPackages:
    @babel/runtime: ^7.12.5 => 7.13.2 
    babel-plugin-add-react-displayname: ^0.0.5 => 0.0.5 
    eslint: ^7.9.0 => 7.20.0 
    eslint-plugin-babel: ^5.3.0 => 5.3.1 
    jest: ^26.0.0 => 26.6.3 
```
- Babel version(s): 7.13.3
- Node/npm version: 15.3.0
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Is this causing a problem? `@babel/runtime/helpers/getPrototypeOf` should resolve to `_index.mjs` in every tool that supports Node.js's resolution algorithm, and in the worst case the CJS version should still work.

**Comment by 372623460jh** [comment]
The esm module unable to import the cjs module.
Error: 'default' is not exported by node_modules/_@babel_runtime@7.13.2@@babel/runtime/helpers/defineProperty/index.js, imported by node_modules/_@babel_runtime@7.13.2@@babel/runtime/helpers/objectSpread2/_index.mjs.

**Comment by afc163** [comment]
[Package exports](https://webpack.js.org/guides/package-exports/) is not supported in webpack 4

https://github.com/babel/babel/blob/f47737c31c224635f1186d1f2cdc53109db15ec0/packages/babel-runtime/package.json#L190-L194

**Comment by KACAH** [comment]
It is causing a problem. I am using Babel with Webpack and resuting source is like

![image](https://user-images.githubusercontent.com/1206330/108826602-2a19a000-75cd-11eb-9773-a8253bf51258.png)

As you see, I got module instead of function in _toConsumableArray variable. The usage of it (generated by transform-runtime) obviously fails.

![image](https://user-images.githubusercontent.com/1206330/108826844-8aa8dd00-75cd-11eb-8e6d-b35d042a650f.png)

`_toConsumableArray is not a function`

Maybe there is a setting somewhere to fix this, but it's definetly a breaking change for me, not just a minor update. Babel 7.12 works perfectly fine.

**Comment by dollysingh3192** [comment]
I have babel "7.12.17" with below configuration and everything was working fine till yesterday.

```
{
    "presets": [
        [
            "@babel/env"
        ],
        [
            "@babel/typescript",
            {
                "allowDeclareFields": true
            }
        ]
    ],
    "plugins": [
        "lodash",
        [
            "@babel/plugin-proposal-decorators",
            {
                "legacy": true
            }
        ],
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread",
        [
            "@babel/plugin-transform-runtime", //target environment are not supported
            {
                "corejs": 3,
                "helpers": true,
                "regenerator": true,
                "useESModules": true
            }
        ]
    ]
}
```

After "7.13.0" release I am continuously getting error, where I am trying to extend a Class but not able to do so.
```
Uncaught ReferenceError: _Reflect$construct is not defined at _isNativeReflectConstruct
```

Any suggestions? Please

**Comment by KACAH** [comment]
> I have babel "7.12.17" with below configuration and everything was working fine till yesterday.
> After "7.13.0" release I am continuously getting error, where I am trying to extend a Class but not able to do so.
> Any suggestions? Please

As temporary fix you can rollback to 7.12.x. Replace "^7.12.17" with "~7.12.17" for all @babel packages in your package.json and reinstall dependencies.

**Comment by dollysingh3192** [comment]
Yes @KACAH  Just did that. But Why is this happening, I mean what causing polyfill not injecting?

**Comment by nicolo-ribaudo** [comment]
@dollysingh3192 We unified our polyfill implementations for corejs2 and corejs3, and it caused problems.

**Comment by nicolo-ribaudo** [comment]
# For people with the corejs problem

Please go to https://github.com/babel/babel/issues/12863, this is a different issue!

**Comment by dollysingh3192** [comment]
@nicolo-ribaudo  Thanks for your response and the link in above comment. 

Is there any helpful link where we can read more on detail on this unification implementation? 

Thanks again!

**Comment by nicolo-ribaudo** [comment]
@KACAH Your problem is the opposite: your bundle is requiring an ESM file in CJS. Could you create a small repo that shows the error?

@372623460jh Could you create a small repository that shows your error?

**Comment by KACAH** [comment]
> @KACAH Your problem is the opposite: your bundle is requiring an ESM file in CJS. Could you create a small repo that shows the error?
> 

My problem seems to be fixed after [this commit](https://github.com/babel/babel/commit/a2114d452cda907085852488cd2573906828ef05). So the build works fine again after `@babel/runtime >= 7.13.4`. Thank you for a fast reaction!

Here is a [small repo](https://github.com/KACAH/babel-bug-1) with pre-fix problem demo, just for a history I guess. BTW problem does not appear without `sourceType: 'unambiguous'` in a babel config.

**Comment by nicolo-ribaudo** [comment]
I'm glad that it was solved, I'm sorry it took us a few attempts to finally get the `"exports"` definitions correct :sweat_smile:

**Comment by KACAH** [comment]
Just found out [documentation](https://nodejs.org/api/packages.html#packages_package_entry_points) on `exports` setup in "package.json". There is a note about `node` export condition.

> "node" - matches for any Node.js environment. Can be a CommonJS or ES module file. This condition should always come after "import" or "require"

Not sure if this is or will be important, but your `node` conditions come BEFORE `import`. Just letting you know.

**Comment by nicolo-ribaudo** [comment]
Yes that was a deliberate decision: when running in Node, we always want to load the CommonJS file. Otherwise you could end up running two different "copies" of the same helper: the ESM one when using `import` and the CJS one when using `require`.

Unfortunately in webpack there could still be duplication between ESM and CJS, but it's not something that we can fix until Babel 8.
