### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by CristalFJJ** [babel/babel#12866]
## Bug Report

![image](https://user-images.githubusercontent.com/28974824/108827432-9366d680-7600-11eb-85c2-025cf26a3f97.png)

v7.13.2
chrome  v88.0
I guess it's because of the.@bable/runtime v7.13.2  *.mjs file

**Comment by hzoo** [comment]
Can you check with v7.13.6?

**Comment by rubyless** [comment]
I also have the same problem

![image](https://user-images.githubusercontent.com/4181778/108932512-72e06000-7684-11eb-92d0-bbfcf3908bff.png)

**Comment by CristalFJJ** [comment]
> Can you check with v7.13.6?

v7.13.6 the same problem exists， I use history@4.10.1 check with it.

**Comment by CristalFJJ** [comment]
> Can you check with v7.13.6?

![image](https://user-images.githubusercontent.com/28974824/108951014-2f94ea00-76a2-11eb-8778-5f45882cc226.png)

chang it like this  and it will work

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/issues/12866#issuecomment-784772786. This is really strange 🤔

Can someone create a repository that reproduces the bug? I have trouble understanding why it's happening and cannot reproduce it locally.

**Comment by CristalFJJ** [comment]
> [#12866 (comment)](https://github.com/babel/babel/issues/12866#issuecomment-784772786). This is really strange 🤔
> 
> Can someone create a repository that reproduces the bug? I have trouble understanding why it's happening and cannot reproduce it locally.

is the same problem  with this issues and it is resolved [https://github.com/babel/babel/issues/12881#issuecomment-785053270](12881)
thanks ！！！

**Comment by JLHwung** [comment]
I am glad it works!
