### ISSUE TITLE
npm ERR! notarget No matching version found for @babel/helper-replace-supers@^7.13.0

### ISSUE THREAD

**Issue by dep-dt** [babel/babel#12875]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Our CI is failing this morning with the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-replace-supers@^7.13.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/helper-module-transforms'
npm ERR! notarget 
```

Is this a transitive dependency failure of some kind?

**Expected behavior**

CI build passes

**Comment by nicolo-ribaudo** [comment]
This is correctly published on npm: https://www.npmjs.com/package/@babel/helper-replace-supers

It's likely a problem with a cache between your CI build and the npm registry, which didn't load the updated package.
