### ISSUE TITLE
Boolean for targets.node option throws an error

### ISSUE THREAD

**Issue by cdoublev** [babel/babel#12878]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Transforming an input code with a `babel` configuration that includes the `targets` option (new in `@babel/core@^7.13.0`) assigned to `{ node: true }` throws the following error: `Error: .targets["node"] must be a string or an integer number`.

**Input Code**

```js
1 + 1
```

**Expected behavior**

It should accept a `Boolean`, as per the documentation:

> **targets.node**
>
>Type: string | "current" | true.
>
> If you want to compile against the current node version, you can specify "node": true or "node": "current", which would be the same as "node": process.versions.node.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  targets: {
    node: true,
  }
}
```

**Environment**

- Babel version(s): v7.13.1
- Node/npm version: Node 15.8 / npm 7.5.4
- OS: Debian Buster
- Monorepo: no
- How you are using Babel: @babel/cli

**Possible Solution**

**EDIT:** obviously, the following suggestion will not work with `'current'`, so I guess a dedicated `assertNodeTarget` should be created.

[Here](https://github.com/babel/babel/blob/4acb73449fa5476dee2b73e49fbc0f5d570b949c/packages/babel-core/src/config/validation/option-assertions.js#L397):

```diff
 const browsersLoc = access(loc, "browsers");
 const esmodulesLoc = access(loc, "esmodules");
+ const nodeLoc = access(loc, "node");

 assertBrowsersList(browsersLoc, value.browsers);
 assertBoolean(esmodulesLoc, value.esmodules);
+ assertBoolean(nodeLoc, value.node);
```

And [here](https://github.com/babel/babel/blob/4acb73449fa5476dee2b73e49fbc0f5d570b949c/packages/babel-core/src/config/validation/option-assertions.js#L407):

```diff
- if (key === "esmodules") assertBoolean(subLoc, val);
+ if (key === "esmodules" || key === "node") assertBoolean(subLoc, val);
```

**Additional context**

The above change fixes the issue and the code is transpiled. But cloning the `babel` git repository always fails in Windows (guest) because of long paths, and installing the package dependencies fails in Debian Buster (guest vm) because of the following error:

```shell
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

I guess I will not be able to make a PR.

**Comment by nicolo-ribaudo** [comment]
Since `node: true` is the same as the supported `node: "current"` (and `node: "current"` better expresses what it does), we could just decide to remove `node: true` from the docs.

This is not a regression, since it only affects the new top-level `targets` option and not the option in `@babel/core`.

@existentialism @JLHwung @hzoo Thoughts?

> The above change fixes the issue and the code is transpiled. But cloning the babel git repository always fails in Windows (guest) because of long paths, and installing the package dependencies fails in Debian Buster (guest vm) because of the following error:

(it's because Babel uses `yarn`, not `npm`)

**Comment by JLHwung** [comment]
@nicolo-ribaudo Agreed it works as intended, we should revise docs.

@cdoublev Please check out https://github.com/babel/babel/blob/main/CONTRIBUTING.md#developing if you want to contribute. Thanks!

**Comment by cdoublev** [comment]
I was willing to point out the potential confusion by allowing `node: true` only in `@babel/preset-env` but not in the "global" options. And now I can see that `node: true` has been removed on the documentation of `@babel/preset-env` instead of / but not on the documentation of the "global" options.

IMO, an ideal situation would be to use `targets: <query>` and get `browserslist`, which already handles `"current node"` as input query, renamed to `targetlist` or something similar.

While keeping the above opinion in mind, `options.targets` is documented with `string | Array<string> | { [string]: string }` but `options.targets.esmodules: true` can still be used. Mayve you could extend the `browserlists` query strings with `"esmodules"`.

I will probably open a new issue for the following, but by setting `options.targets.esmodules: true` and removing `targets.esmodules: true` from `@babel/preset-env`, the `debug: true` and the output file sizes hints me that the `esmodules: true` to defined `targets` "globally" is not properly forwarded to `@babel/preset-env`

I was going to point out the potential confusion brought by allowing `node: true` only in `@babel/preset-env` but not in the "global" options. And now I can see that `node: true` has been removed in the documentation for `@babel/preset-env` instead of / but not in the documentation of the "global" options.

IMO, an ideal situation would be to use `targets: <query>` and have `browserlist`, which already handles `"current node"` as an input request, be renamed to `targetlist` or something similar.

While keeping the above opinion in mind, I would still like to point out that `options.targets` is documented with `string | Array <string> | {[string]: string}` but this signature does not take into account `options.targets.esmodules: true`. Maybe the `browserlists` queries could be extended with `"esmodules"`.

In the meantime but I'll probably create a new issue for the following, but the `debug: true` of `@babel/preset-env` and the size of the output files hint me that `options.targets.esmodules: true` is not correctly passed to `@babel/preset-env`.
