### ISSUE TITLE
unknown: .targets is not allowed in preset options

### ISSUE THREAD

**Issue by pascalduez** [babel/babel#12879]
## Bug Report

**Current behavior**

Upgrading our preset to babel 7.13.x, and trying to hoist the `targets` options at the preset root, following [the blog post](https://babeljs.io/blog/2021/02/22/7.13.0#top-level-targets-option-12189httpsgithubcombabelbabelpull12189-rfchttpsgithubcombabelrfcspull2) and [the docs](https://babeljs.io/docs/en/options#output-targets), I get the following error:

```
[BABEL] unknown: .targets is not allowed in preset options

  at node_modules/@babel/core/lib/config/validation/options.js:100:13
      at Array.forEach (<anonymous>)
  at validateNested (node_modules/@babel/core/lib/config/validation/options.js:92:21)
  at validate (node_modules/@babel/core/lib/config/validation/options.js:83:10)
  at node_modules/@babel/core/lib/config/full.js:328:36
  at cachedFunction (node_modules/@babel/core/lib/config/caching.js:62:27)
      at cachedFunction.next (<anonymous>)
  at evaluateSync (node_modules/gensync/index.js:251:28)
  at sync (node_modules/gensync/index.js:89:14)
  at loadPresetDescriptor (node_modules/@babel/core/lib/config/full.js:317:18)
```

**GitHub Repo**

https://github.com/Gandi/babel-preset-gandi/pull/29  

**Input Code**

```js
module.exports = (context, options = {}) => {
  let targets = {
    browsers: ['last 2 versions', '> 1%', 'Firefox ESR', 'not dead'],
    ...options.targets,
  };

  let envOpts = {
    modules: options.modules,
    bugfixes: targets.esmodules === true,
  };

  let runtimeOpts = {
    corejs: 2,
    helpers: true,
    regenerator: true,
    version: '7.13.0', // 1
  };

  let presets = [
    ['@babel/preset-env', envOpts],
    '@babel/preset-react',
    '@babel/preset-flow',
  ];

  let plugins = [
    '@babel/plugin-transform-flow-strip-types', 
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-transform-runtime', runtimeOpts],
  ];

  return {
    targets,
    presets,
    plugins,
  };
};
```

**Expected behavior**
No error...

**Environment**
```
System:
  OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
Binaries:
  Node: 12.16.2 - /tmp/fnm-shell-1022461/bin/node
  Yarn: 1.22.5 - /usr/bin/yarn
  npm: 6.14.9 - /tmp/fnm-shell-1022461/bin/npm
npmPackages:
  @babel/core: ^7.13.1 => 7.13.1 
  @babel/plugin-proposal-class-properties: ^7.13.0 => 7.13.0 
  @babel/plugin-transform-runtime: ^7.13.5 => 7.13.5 
  @babel/preset-env: ^7.13.5 => 7.13.5 
  @babel/preset-flow: ^7.12.13 => 7.12.13 
  @babel/preset-react: ^7.12.13 => 7.12.13 
  @babel/runtime-corejs2: ^7.13.4 => 7.13.4 
  jest: ^26.6.3 => 26.6.3 
```

**Comment by nicolo-ribaudo** [comment]
For now we could only allow `targets` in configuration files.

This is because presets (such as `@babel/preset-env`) need to be _consumers_ of `targets` and thus they cannot define new targets (because we need to know the targets and pass them to the presets _before_ calling the presets).

The docs mention that this is only `Allowed in Babel's programmatic options, or in config files` (not in presets), maybe we could make that message more prominent.

We might relax this restriction in the future, but for now there isn't a clear way to do so :frowning_face:.

(also, usually only the authors of the app knows what browsers they want to target, and not the authors of the presets that the final developers are using).

**Comment by pascalduez** [comment]
Thanks for the quick reply @nicolo-ribaudo!

> The docs mention that this is only Allowed in Babel's programmatic options, or in config files (not in presets), maybe we could make that message more prominent.

Ah yes sorry, totally missed this one... 

> (also, usually only the authors of the app knows what browsers they want to target, and not the authors of the presets that the final developers are using).

Yeah that's something I would like to change, although it works fine for use, always made me a but nervous.

**Comment by pascalduez** [comment]
I've got some weird changes.

If I remove the `useESModules` config (I get a warning about this), it doesn"t looks like it's working.
```diff
- import _classCallCheck from "@babel/runtime-corejs2/helpers/esm/classCallCheck";
+ import _classCallCheck from "@babel/runtime-corejs2/helpers/classCallCheck";
```

Which is wrong because leading to commonjs exports.

Also

```diff
- var _interopRequireDefault = require("@babel/runtime-corejs2/helpers/interopRequireDefault");
+ var _interopRequireDefault = require("@babel/runtime-corejs2/helpers/interopRequireDefault").default;
```

https://github.com/Gandi/babel-preset-gandi/pull/29

**Comment by nicolo-ribaudo** [comment]
> Which is wrong because leading to commonjs exports.

In webpack or in Node.js? Does it actually cause problems? We tried to carefully reorganize `@babel/runtime-corejs2` so that Node.js / the bundler can automatically choose between the CJS and ESM helpers.

**Comment by pascalduez** [comment]
> In webpack or in Node.js? 

Node.js here, just running the tests we have in our preset. 

If I check the content of `@babel/runtime-corejs2/helpers/classCallCheck/index.js` it's a commonjs module, imported in an ES module. This used to error.    
There's an `_index.mjs` alongside, and still a `../esm` folder, do you mean node or bundlers will be able to find those? 
We are still on node 12 and webpack 4 though...

**Comment by nicolo-ribaudo** [comment]
> This used to error.

In which Node.js version? (I'm not trying to attack you, just trying to understand better :sweat_smile:)

- Node.js will always load the CJS version. This should work as far as I know.
- Webpack 5 and Rollup will load the ESM version when using `import`
- Webpack 4 and Webpack 5 will load the CJS version

This was to make sure that every tool has a working version, while still making it possible for tools that need to target browsers without bundling modules to directly use the ESM version automatically.

When I tested those different bundlers/versions everything seemed to work, but I might have missed something.

**Comment by nicolo-ribaudo** [comment]
Ok I tested this in Node.js 12.17 (the first version with unflagged ESM support):

```js
// main.mjs
import foo from "./foo.js";
console.log(foo);
```

```js
// foo.js
console.log("foo!");
module.exports = 2;
```

And it seems to work:
```js
➜ node main.mjs
(node:172488) ExperimentalWarning: The ESM module loader is experimental.
foo!
2
```

**Comment by pascalduez** [comment]
> In which Node.js version? 

I only I could remember :sweat_smile:, I guess Still 12.  

> (I'm not trying to attack you, just trying to understand better)

No worry! That's really kind of you to take the time to troubleshoot! 

I've run some quick tests (libs compilation, storybook) and seems fine. 
I guess I'm a little worried about tree-shaking etc. But trusting you more than anything! 

What I don't get is how bundlers can resolve/find either `./_index.mjs` or `../esm/classCallCheck/index.js` from that common.js file. My gosh, how many years have we spent fighting with this cjs/esm thing.

Thanks again!

**Comment by pascalduez** [comment]
> What I don't get is how bundlers can resolve/find either ./_index.mjs or ../esm/classCallCheck/index.js from that common.js file

Wow okay, the `exports` config in `@babel/runtime-corejs2` package.json !

**Comment by nicolo-ribaudo** [comment]
Yeah but I don't know if webpack 4 supports `exports` 😬
In the worst case it loads the cjs version.

Helpers are usually non-treeshakable anyway because they are "atomic files", but if you run in any issue please ping us!
