### ISSUE TITLE
ES7 function bind

### ISSUE THREAD

**Issue by kobezzza** [babel/babel#1287]
It would be great if Babel support this feature
https://github.com/zenparsing/es-function-bind

**Comment by phpnode** [comment]
i think this was known as "abstract references" before and got removed until the spec was ironed out

**Comment by zloirock** [comment]
BTW, [I like TC39 conclusion at this proposal](https://github.com/rwaldron/tc39-notes/blob/master/es6/2015-03/mar-25.md#6vi-function-bind-and-private-fields-redux-kevin-smith):
> Get more feedback from users of Babel

:)

**Comment by bucaran** [comment]
:+1: :+1: :+1: :+1:

**Comment by sebmck** [comment]
@bucaran As I've said [before](https://github.com/babel/babel/issues/1289#issuecomment-94359556):

> Also just a nit but +1s are incredibly unproductive, extremely annoying and don't get bugs fixed faster.

**Comment by bucaran** [comment]
@sebmck Wait, I was working on my reply, but got distracted with Super Mario Chuck Norris at the office. Dude, you are really working 24/7 on this.

**Comment by bucaran** [comment]
@sebmck Wait, I was working on my reply, but got distracted with Super Mario Chuck Norris at the office. Dude, you are really working 24/7 on this.

**Comment by sebmck** [comment]
@bucaran I do it largely in my spare time.

**Comment by bucaran** [comment]
There is possibly also a significant time difference as I am based in Japan.

**Comment by zenparsing** [comment]
FWIW, I didn't push for any ES "stage" level on the function bind proposal.  I personally think it would be a transformative feature, but it's really in the hands of JS users for now (hence the conclusion to get user testing and feedback).

I'll take a look into adding a patch for Babel, but with my current workload I probably won't be able to spend much time on it.

**Comment by UltCombo** [comment]
This feature would be very helpful IMHO.
I'm wondering whether it would be possible to optimize away and replace `.bind()` with `.call()` when it is part of a `callExpression`.

**Comment by zenparsing** [comment]
@UltCombo From the es-function-bind repo:

> If the bound function is immediately called, and the target function is strict mode, then the bound 
> function itself is not observable and the bind operator can be optimized to an efficient direct 
> function call.
>
> NOTE: If the target function is not strict, then it may use function.callee or arguments.callee, 
> which would result in an observable difference of behavior.

So, yes, for strict functions and non-strict functions which do not access `arguments.callee` it can be optimized away.

**Comment by UltCombo** [comment]
@zenparsing oh nice! I'll read the spec carefully when I get home.
By the way, I've skimmed through the proposal but I couldn't find the precedence of the `::` operator. Would it be the same as property access?

**Comment by zenparsing** [comment]
The grammar is the trickiest part, because in JS MemberExpression is just plain tricky.

But yes, the precedence is just lower than "." and "[".  For something like:

```js
a.b::c.d();
```

It ends up parsing like:

```js
CallExpression  `a.b::c.d()`
    BindExpression  `a.b::c.d`
        MemberExpression `a.b`
        MemberExpression `c.d`
```

https://github.com/zenparsing/esparse/blob/master/src/Parser.js#L820

**Comment by donaldpipowitch** [comment]
This is not really related to ES7 function bind (which I really look forward to!), but I hope that someday the discussion for a cascade operator in JavaScript will (re-)gain momentum. I know about two possible specs/syntaxes: [this one](https://blog.mozilla.org/dherman/2011/12/01/now-thats-a-nice-stache/) and `..` taken from [Dart](https://www.dartlang.org/docs/dart-up-and-running/ch02.html#operators). With the last one we would probably see code like `a..b::c.d()`.

:dancers:

I wouldn't mind^^

**Comment by sebmck** [comment]
I doubt you'd ever see consensus on a `..` subscript operator since it's so close to just `.` and would be extremely confusing.

**Comment by bucaran** [comment]
@donaldpipowitch I don't know about you, but I prefer just returning `this` from my methods and just cascading like we've done since forever. Not as handy as a cascade operator though.

**Comment by donaldpipowitch** [comment]
@sebmck I don't know, maybe we should ask some Dart developers about this which use exactly this style: `.` and `..` next to each other. I find it somewhat convenient... a little bit like `$ cd ../foo` and `$ cd ./foo` :)

@bucaran No problem in your own code, sure. But wouldn't this be nice?: `someArray.push('foo').push('bar').push('baz')` But this throws an error, because `someArray.push('foo')` returns `1`. Something like `someArray.push('foo')..push('bar')..push('baz')` would be nice to have (imo).

**Comment by bucaran** [comment]
@donaldpipowitch Sold!

You can always do something like:
```js
let dart = (function (array) {
  return function (_array) {
    if (_array) array = [].concat(_array, array)
    array.push = function () {
      [].push.apply(array, arguments)
      return array
    }  
    return array    
  }
}([]))
```
LOL

**Comment by RReverser** [comment]
See #1518 for implementation.

**Comment by mattdesl** [comment]
I think it's great that Babel is encouraging experimentation with JavaScript as a language. But why not grow these efforts into Babel plugins or user-land modules, rather than bundling them into core? 

I'm trying to imagine the landscape of Babel in a few years, after some of these proposals have been long-forgotten and discarded, or replaced by subtly different (yet conflicting) implementations. It seems like a lot of baggage to bring into core, and a lot of extra burden on maintainers.

Just my 2c. :beers: Also, great job on the implementation @RReverser.

**Comment by sebmck** [comment]
@mattdesl Because plugins don't allow hooking into the parser etc. It's actually architecturally pretty difficult to allow additional node types too.

**Comment by mattdesl** [comment]
Ok. Is there any long-term plan for this? From what I can tell it seems like function bind syntax is super experimental, and subject to being thrown out entirely from ES7, at which point will Babel continue to support it? Just curious about how it will all go down, if all new ES7 proposals start making their way into Babel core.

**Comment by sebmck** [comment]
I don't know. That's pretty far out. See #1351 for previous discussion. It's not super high priority right now.
