### ISSUE TITLE
do not define a valid './helpers/interopRequireWildcard' target  error

### ISSUE THREAD

**Issue by huseyinbuyukdere** [babel/babel#12871]
Hi everyone,

Today we took this error without changing nothing, 

Package exports for 'node_modules\regenerator-transform\node_modules\@babel\runtime' do not define a valid './helpers/interopRequireWildcard' target (While processing: node_modules\@babel\preset-env\lib\index.js) 

Our versions are like below

@babel/preset-env : 7.13.0
regenerator-transform : 0.14.5
regenerator-transform -> @babel/runtime : 7.13.4

**Comment by nicolo-ribaudo** [comment]
As you can see at line 158 of https://unpkg.com/browse/@babel/runtime@7.13.4/package.json, we define the `"default"` fallback for `interopRequireWildcard` which should _always_ be valid according to how export conditions work.

What build tool is throwing that error? Is it thrown directly by node?

**Comment by huseyinbuyukdere** [comment]
We are building our project by gulp. We can't run gulp tasks now.

**Comment by nicolo-ribaudo** [comment]
cc @Andarist This seems to be a Node.js error, maybe you know what's happening :thinking:

**Comment by nicolo-ribaudo** [comment]
@huseyinbuyukdere As a workaround, downgrade `@babel/runtime` to `~7.12.0`

**Comment by nicolo-ribaudo** [comment]
What is your exact Node.js version?

**Comment by wangcherry** [comment]
I need help too!!!
When webpack4 is ok，but webpack5 is error。
![image](https://user-images.githubusercontent.com/11580793/108840220-fe200e00-7610-11eb-987c-ccba5f44412c.png)

**Comment by huseyinbuyukdere** [comment]
> What is your exact Node.js version?

Node : 13.1.0

**Comment by wangcherry** [comment]
> @huseyinbuyukdere As a workaround, downgrade `@babel/runtime` to `~7.12.0`

I can't, @babel/runtime not my dependencies, is dependencies to dependencies

**Comment by nicolo-ribaudo** [comment]
@wangcherry That is another issue: https://github.com/babel/babel/issues/12854

**Comment by nicolo-ribaudo** [comment]
@huseyinbuyukdere As a workaround you could also trying to use Node.js 14 LTS (13 is not maintained anymore)

**Comment by huseyinbuyukdere** [comment]
> > @huseyinbuyukdere As a workaround, downgrade `@babel/runtime` to `~7.12.0`

We tried now 7.12.0 , it is worked but most of our machines took the latest version. We cant update instantly, so we will wait new version.

**Comment by wangcherry** [comment]
> @wangcherry That is another issue: #12854

I have @babel/runtime 7.13.2 with webpack5 and still have a problem:
_interopRequireDefault is not a function

this problem is not solved.....

**Comment by Andarist** [comment]
Could you add a log that would dump `_interopRequireDefault` there and paste in the result?

**Comment by nicolo-ribaudo** [comment]
What's surprising to me is that the error in this issue:
> Package exports for 'node_modules\regenerator-transform\node_modules@babel\runtime' do not define a valid './helpers/interopRequireWildcard' target

is a Node.js error related to the `package.json#exports` field, but according to the Node.js docs that file isn't used in Node.js 13.1.0 (it was unflagged in 13.7.0).

**Comment by nicolo-ribaudo** [comment]
I know what's going on and I have a fix.

**Comment by nicolo-ribaudo** [comment]
This should be fixed in v7.13.6
