### ISSUE TITLE
Generating modules with absolute name / id

### ISSUE THREAD

**Issue by hege91** [babel/babel#1288]
Greetings!

Transforming es6 modules to CommonJS or AMD modules with `{ moduleIds: true }` will produce module names like `'a/b/c'`. I would like them to be generated as `'/a/b/c'`. Using `moduleRoot` will automatically insert an extra `'/'`, so transforming with `{ moduleIds: true, moduleRoot: '/' }` produces module names like `'//a/b/c'`, with double leading slashes. Is there a simple way to generate module names with single leading slashes `'/a/b/c'`?

Backstory:
I an building an app with multiple source root directories, and using es6 module syntax. The module loader I use on the transpiled AMD modules needs exact string match to find a module by id, so all my imports are in the form `'a/b/c'` to match the generated module ids. But this way the IDE handles them as relative paths, and refactoring files to be in other source roots keeps replacing my imports with relative paths like `'../srcRootB/a/b/c'`. Using absolute paths would solve my problem.
I know I could modify my module loader to trim off leading slashes at import, and in fact it might be the IDE that mishandles my sources, but I think it should be definitely possible to generate module names like that.

**Comment by stagas** [comment]
Not sure if it helps, but the option `resolveModuleSource` gives you a chance to modify the module name. From the docs:
```
resolveModuleSource 	null 	

Resolve a module source ie. import "SOURCE"; to a custom value. Called as resolveModuleSource(source, filename).
```

**Comment by sebmck** [comment]
@stagas That's only for module sources, not IDs.

@hege91 You can alternatively pass your own module ID via the option `moduleId`.

**Comment by vatula** [comment]
How does moduleId help OP's question? I basically have the same issue. If you have relative names in imports and your moduleRoot option is set to some string, why does transformer leaves relative path in imports? Is there a point in not replacing relative part with moduleRoot?
