### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module on @babel/runtime 7.13.*

### ISSUE THREAD

**Issue by lukezavrel** [babel/babel#12889]
## Bug Report
Hello, on @babel/runtime version 7.12.18 everything works correctly, however after updating to any newer version (7.13.0 to 7.13.7), build fails and following error is thrown

**Current behavior**
ERROR in ./js/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/.../webapp/node_modules/@babel/runtime/helpers/interopRequireWildcard/_index.mjs
    at Module.load (internal/modules/cjs/loader.js:991:11)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/.../webapp/node_modules/regenerator-transform/lib/visit.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/.../webapp/node_modules/regenerator-transform/lib/index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
 @ multi babel-polyfill ./js/main app[1]

It might be possible i am doing something wrong, but i have no idea what, because it is working correctly on 7.12.18. Maybe it has something to do with https://github.com/babel/babel/pull/12842 ?

**Expected behavior**
No error is thrown and build completes successfully

**Environment**
- Babel version(s): 7.13.7
- Node/npm version: Node 13.6.0/Npm 6.13.4
- OS: macOS 10.15.7
- How you are using Babel: webpack

**Comment by nicolo-ribaudo** [comment]
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/.../webapp/node_modules/@babel/runtime/helpers/interopRequireWildcard/index.mjs

We removed that `index.mjs` file in 7.13.1, what error do you get with newer versions? What is your webpack config?

**Comment by lukezavrel** [comment]
My bad, sorry, the error i posted was with version 7.13.0, i updated the issue description (same error but different file)  
My webpack config is quite long, so i'll try to post relevant parts
```
module.exports = (env = {}) => {
	if (!env.ROOT_PATH) {
        throw Error('Variable env.ROOT_PATH is not defined. Set this parameter in your app!');
	}
	if (!env.MAIN_FILE_PATH) {
		console.warn('Variable env.MAIN_FILE_PATH for specific path to index file is not defined. Default path "js/main" will be used.');
	}
	const isAnalyzer = env.BUNDLE_ANALYZER ? true : false;
	const config = getConfig(env);
	const webpackCommon = {
		entry: {
			app: ['babel-polyfill', env.MAIN_FILE_PATH || './js/main']
		},
		output: {
			path: env.ROOT_PATH,
			publicPath: config.PUBLIC_PATH,
			filename: config.ASSET_PATH + '/js/[name].js?v=[hash]',
			chunkFilename: config.ASSET_PATH + '/js/[name].chunk.js?v=[hash]'
		},
		module: {
			rules: [
				{
					test: /\.(js|jsx)$/,
					exclude: /node_modules/,
					use: {
						loader: 'babel-loader?cacheDirectory=true',
						options: {
							presets: [
								['@babel/preset-env', {
									'targets': {
										browsers: ['last 3 versions', 'not ie <= 10']
									},
									debug: isDev
								}],
								['@babel/preset-react', {}]
							],
							plugins: ['@babel/plugin-proposal-object-rest-spread', 'lodash', "@babel/plugin-syntax-dynamic-import", "@babel/plugin-proposal-class-properties"]
						}
					}
				},
				{
					test: /\.(css|sass|scss)$/,
					use: [
						{
							loader: isDev ? 'style-loader' : MiniCssExtractPlugin.loader,
							options: isDev ? {} : {
								publicPath: '../../'
							}
						},
						{
							loader: 'css-loader',
							options: {
								importLoaders: 1,
								sourceMap: true
							}
						},
						{ loader: 'sass-loader' },
					]
				},
				{
					test: /\.(eot|svg|ttf|woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
					use: {
						loader: 'url-loader',
						options: {
							limit: 50000,
							name: config.ASSET_PATH + '/fonts/[hash].[ext]',
						}
					},
				},
				{
					test: /.(png|jpe?g|gif|svg)$/,
					use: {
						loader: 'url-loader',
						options: {
							name: config.ASSET_PATH + '/images/[hash].[ext]',
							limit: 8192
						}
					},
				},
				{
					test: /.(icon.png|icon.ico)$/,
					use: {
						loader: 'file-loader',
						options: {
							name: config.ASSET_PATH + '/images/[name].[ext]',
						}
					},
				},
			]
		},
		resolve: {
			extensions: ['.js', '.jsx', '.json'],
		},
		performance: {
			hints: false
		},
		plugins: [
			new MiniCssExtractPlugin({
				filename: config.ASSET_PATH + '/css/style.css?v=[hash]',
				chunkFilename: '[id].css'
			}),
			new webpack.SourceMapDevToolPlugin({
				filename: config.ASSET_PATH + '/js/[name].js.map[query]',
			}),
			new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /en|cs|fr|de|it/) // use only en, cs, fr, de, it locales for moment library
		]
	};

	return webpackMerge(webpackCommon, {
			resolve: {
				alias: nodeModulesInfo.loadNames().reduce((aliases, moduleName) => {
					aliases[moduleName] = path.resolve('./node_modules/' + moduleName);
					return aliases;
				}, {})
			},
			devtool: '#eval-source-map',
			devServer: {
				port: config.DEV_SERVER_PORT,
				host: config.DEV_SERVER_HOST,
				historyApiFallback: {
					index: config.PUBLIC_PATH + 'index.html'
				},
				compress: true,
			},
			plugins: [
				new webpack.DefinePlugin({
					'process.env': {
						NODE_ENV: JSON.stringify('development')
					},
					globalParams: config.GLOBAL_PARAMS,
					feVersions: JSON.stringify(feVersions)
				}),
				new HtmlWebpackPlugin({
					template: config.WEBPACK_PATH + '/index.dev.html',
					filename: 'index.html',
					title: config.PAGE_TITLE
				})
			]
		});
	}
```

**Comment by nicolo-ribaudo** [comment]
I'll check this later, as a workaround you could try using any newer Node.js version (I think even 13.7 is enough).

**Comment by lukezavrel** [comment]
After updating node.js it works, thanks

**Comment by fengxinming** [comment]
because of `_index.mjs`

**Comment by nicolo-ribaudo** [comment]
Nah this has nothing to do with mjs, using an es module with .js would have had the same behaviour.
