### ISSUE TITLE
Targets for esmodules not forwarded to @babel/preset-env

### ISSUE THREAD

**Issue by cdoublev** [babel/babel#12903]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

When using the global `targets` option set to `{ esmodules: true }`, the targets passed to `@babel/preset-env` (and other presets/plugins) and the code output are not the same as when defining the same value in the preset options.

- https://github.com/cdoublev/babel-issue

**Input Code**

```js
10 ** 2
```

**Expected behavior**

The targets corresponding to `esmodules: true` should be forwarded to `@babel/preset-env`, instead of (I presume) the default targets from `browserslist"

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
    presets: ['@babel/preset-env'],
    targets: { esmodules: true },
}
```

**Environment**

- Babel version(s): 7.13.0
- Node/npm version: Node 15.8 / npm 7.5.4
- OS: Debian Buster
- Monorepo: no
- How you are using Babel: `@babel/cli`

**Possible Solution**

Maybe [here](https://github.com/babel/babel/blob/039eb2710d54d03f02240106808cd9f0ef1732d8/packages/babel-helper-compilation-targets/src/index.js#L208):

```diff
- if (esmodules && (esmodules !== "intersect" || !browsers)) {
+ if (esmodules && (esmodules !== "intersect" || !browsers?.length)) {
```

**Additional context**

The `@babel/babel-helper-compilation-targets` test case named `[it] can be intersected with a .browserslistrc file` is failing with/without the above change.

**EDIT:** I didn't realized that tests should be run after `make build`. Tests are passing with the suggested change. I'm working on a PR.

**Comment by cdoublev** [comment]
Sorry for closing/re-opening, I was trying to cancel my comment, which was about telling that I leave making a PR up to you.

I was about running the tests with my changes. I'm not sure that `targets` comes in `getTargets` (in `@babel/helper-compilation-targets`) with `esmodules` set to `true` anymore, and I removed the warning in `babel/preset-env` about mixing `targets.esmodules` and `targets.browsers`. 

Anyway, thank you for woking on this issue.

**Comment by nicolo-ribaudo** [comment]
I'm sorry, I didn't se you ticked "I would like to work on a fix" 😅

**Comment by cdoublev** [comment]
I think I edited my initial comment and checked this box while you were creating your PR. Please don't wait for my work and feel free to finish your PR! Honestly I just want this new global `targets` option to work so that I can publish an update to my libraries.

As noted in my above comments, tests pass when replacing `!browsers` by `!browsers?.length`, and `@babel/preset-env` can call `getTargets` directly [here](https://github.com/babel/babel/blob/bb558aaf28ee84a85eba25c4b6765a5bac50d15d/packages/babel-preset-env/src/index.js#L320), which allows removing `getLocalTargets` and the warning related to the following note from the doc:

> Please note: when specifying the esmodules target, browsers targets will be ignored.

**Comment by JounQin** [comment]
@nicolo-ribaudo 

Hi, I think the strategy of combining `esmodules: true` and `browserslist` config is not clear in the documentation. What would happen when using `esmodules: true` with custom `.browserslistrc` file? Is the browser target to be intersection or union, or `browserslist` config will just be ignored?

**Comment by JounQin** [comment]
@nicolo-ribaudo Thank you for the clarification. I think it's worth to add it into document personally, what do you think?

**Comment by JounQin** [comment]
@nicolo-ribaudo I raised https://github.com/babel/website/pull/2525. I'm not a native English speaker, please help to review the representation.
