### ISSUE TITLE
build babel packages locally

### ISSUE THREAD

**Issue by varunmankal** [babel/babel#12913]
My company has a requirement to build dependencies locally and publish them to our internal server. One of our project dependency is babel, I see some discrepencies while building babel packages locally:

The way I build the package, for example: `babel-cli` , is 

- clone babel repo
- cd into the desired package, in this case, `cd packages/babel-cli`
- run `npm install`
- then run `npm pack`

Once these steps are executed, the `babel-cli` package is generated and I have compared the contents of it with the one downloaded from npm and they match for this package. 

However, when I try to build the package: `build-standalone` by following the above mentioned steps, the contents of the locally built package is not matching with the one from npm.

**The contents in the package downloaded directly from npm:**

> npm notice 0      package
npm notice 1.1kB  LICENSE
npm notice 492B   README.md
npm notice 4.5MB  babel.js
npm notice 2.5MB  babel.min.js
npm notice 5.3kB  package.json
npm notice 0      src
npm notice 0      test
npm notice 221B   src/babel-package-shim.js
npm notice 12.1kB src/index.js
npm notice 3.5kB  src/preset-es2015.js
npm notice 473B   src/preset-stage-0.js
npm notice 1.1kB  src/preset-stage-1.js
npm notice 846B   src/preset-stage-2.js
npm notice 593B   src/preset-stage-3.js
npm notice 5.3kB  src/transformScriptTags.js
npm notice 4.3kB  test/babel.js

**contents of the locally built package:**

> npm notice 221B   src/babel-package-shim.js
npm notice 12.1kB src/index.js
npm notice 3.5kB  src/preset-es2015.js
npm notice 473B   src/preset-stage-0.js
npm notice 1.1kB  src/preset-stage-1.js
npm notice 846B   src/preset-stage-2.js
npm notice 593B   src/preset-stage-3.js
npm notice 5.3kB  src/transformScriptTags.js
npm notice 5.3kB  package.json
npm notice 492B   README.md

The files `babel.js` and `babel.min.js` are missing in the locally built one. can I know how to build these packages without any missing files ? 

**Environment**
- Node/npm version: [e.g. Node 10.24.0/npm 6.14.11]
- macOS 10.14.6

**Comment by nicolo-ribaudo** [comment]
The only think you need to build Babel is `make bootstrap` in the monorepo root.

https://github.com/babel/babel/blob/main/CONTRIBUTING.md#developing
