### ISSUE TITLE
codejs@2 has some problem when builded

### ISSUE THREAD

**Issue by xuweihao** [babel/babel#12916]
![image](https://user-images.githubusercontent.com/24407002/109273695-7f63e480-784d-11eb-9c0b-b1571859a200.png)

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/12901, it will be in the next release later today.

In the meantime, you can downgrade `@babel/preset-env` and its dependency `@babel/compat-data` to version 7.12.

**Comment by nicolo-ribaudo** [comment]
The fix has been released.
