### ISSUE TITLE
Destructuring a function argument requires the argument be present even if it's empty

### ISSUE THREAD

**Issue by sazzer** [babel/babel#1293]
ES6 allows for us to destructure an object directly as function arguments. For example:

    let httpPost = function(
        url, {
        cache = true,
        contentType = "application/json",
        timeout = 2500,
        headers = {},
        // ...
    }) {
        // ...
    };

In this case, *httpPost* is a function with two arguments, the first of which is a String and the second of which is an Object. We automatically destructure some fields out of the Object, and - more importantly - we automatically provide default values for all of these fields if they aren't specified. This means that the following are perfectly valid ways of calling the method:

    httpPost('http://www.google.com', {contentType: 'text/html'});
    httpPost('http://www.google.com', {timeout: 10000, cache: true});
    httpPost('http://www.google.com', {});

Unfortunately, the following does not work:

    httpPost('http://www.google.com');

Even though every single field in the second parameter is defaulted, the second parameter itself is still required even if it is only an empty object.

**Comment by monsanto** [comment]
This follows the spec, you need to write `{cache=true, ...}={}`

**Comment by sazzer** [comment]
Fair enough - I've just found a writeup that explains that. It feels like a bit of a gap in the spec, but if that's how it works then that's how it works. :)

**Comment by stagas** [comment]
Can you share the writeup? @sazzer

**Comment by sazzer** [comment]
Sure thing. It's at http://www.2ality.com/2015/01/es6-destructuring.html

The bit that made this work for me was under **Simulating Named Parameters in JavaScript** in that article. Specifically the fact that you can do my previous example as:
    let httpPost = function(
        url, {
        cache = true,
        contentType = "application/json",
        timeout = 2500,
        headers = {},
        // ...
    }** = {}**) {
        // ...
    };

And then you can just totally omit the second parameter, which then gets defaulted to {}, which then gets passed into the destructuring and fills out the other values with their defaults.
