### ISSUE TITLE
[...new Array(N)] transpiled wrong; loose: true

### ISSUE THREAD

**Issue by dimaqq** [babel/babel#12935]
## Bug Report

- [ ] I would like to work on a fix! (probably beyond my level)

**Current behavior**

- [REPL](https://babel.dev/repl) - so far unable to reproduce in repl
- [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js) - so far unable to reproduce in sandbox
(I'm quite confused, perhaps it's some kind of incompatibility / mess in my project?)

**Input Code**

```js
const PRINTABLE = [...new Array(127)].map((_, i) => String.fromCharCode(i)).slice(0x20, 0x7f);
```

Gets transpiled to:
```
var PRINTABLE = [].concat(new Array(127)).map(function (_, i) {
  return String.fromCharCode(i);
}).slice(0x20, 0x7f);
```

Which appears to be wrong, because:
```
[...new Array(1)]           is [undefined] // array with 1 slot with value `undefined`
but
[].contact(new Array(1))    is [1x empty]  // array with 1 hole
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
// in package.json
  "babel": {
    "plugins": [
      "babel-plugin-macros"
    ],
    "presets": [
      [
        "@babel/preset-env",
        {
          "loose": true,
          "useBuiltIns": false,
          "shippedProposals": true,
          "debug": false
        }
      ]
    ]
  },
  "babelMacros": {
    "styledComponents": {
      "pure": true
    }
  },
```

**Environment**

```
  System:
    OS: macOS 11.2.2
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.5.3 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.7.4 => 7.13.8
    @babel/preset-env: ^7.5.4 => 7.13.8
    babel-plugin-macros: 3 => 3.0.1
    eslint: >=7.6.0 => 7.21.0
    jest: ^26.6.3 => 26.6.3
```

- Babel version(s): `@babel/core@7.13.8` (but also `7.1.0 ... 7.12.13` as transient deps, not actually installed, I think)
- Node/npm version: `node 15.10.0; npm 7.5.3`
- OS: macOS 11.22.2
- Monorepo: no
- How you are using Babel: `webpack` 4.44.2

**Possible Solution**

**Additional context**

**Comment by dimaqq** [comment]
The critical configuration bit is the `loose` setting:
```
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "loose": true
        }
      ]
    ]
  },
  ```

Changing that to `false` or removing that solved the problem.

I wonder why this happened now, I've had the loose setting on since 2020-05-27 due to #11622

**Comment by dimaqq** [comment]
And `"react-scripts#babel-preset-react-app#@babel#preset-env#@babel#plugin-proposal-private-methods"` still requires the loose mode: 

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
```

😢 

perhaps there could be finer-granularity of loose-ness?

**Comment by JLHwung** [comment]
> perhaps there could be finer-granularity of loose-ness?

See https://babel.dev/assumptions#iterableIsArray and https://babeljs.io/docs/en/options#assumptions.

**Comment by dimaqq** [comment]
Yay, for others who may waste a lot of time chasing this:
Spec: https://github.com/babel/rfcs/blob/master/rfcs/0003-top-level-assumptions.md
Status as of 2021-02-01: not yet implemented

For the time being I have two solutions:
1. `"loose": false` and ignore all those warnings
2. roll back `@babel/core` to `7.12.x`

**Comment by nicolo-ribaudo** [comment]
Oh we should update the RFC status, it has been implemented.

**Comment by nicolo-ribaudo** [comment]
I suggest opening an issue/PR to CRA asking for an option to disable loose mode for the class properties transform (https://github.com/facebook/create-react-app/blob/f92c37a6e6636ed1650ffd976c6881f59b1be803/packages/babel-preset-react-app/create.js#L152), then you can use `assumptions` selectively enable non-spec compliant transpilation where it's ok for your app.

**Comment by dimaqq** [comment]
@nicolo-ribaudo

regarding implemented... weirdly I was not able to use `assumptions` in the babel block of my package.json 🤷🏿 

regarding class properties in react (not CRA), I don't have a ref handy, but apparently they did this for performance...
I think it's unlikely they'd backtrack on that :( it may get better if one day react drops support for legacy browsers?

**Comment by nicolo-ribaudo** [comment]
Well they can leave it enabled by default but provide an option to disable it, or use the `setPublicFields` assumption which is what's needed for performance reasons.

> regarding implemented... weirdly I was not able to use assumptions in the babel block of my package.json 🤷🏿

Which `@babel/core` version are you using?

**Comment by dimaqq** [comment]
@babel/core@7.13.8

**Comment by nicolo-ribaudo** [comment]
Uh it should work :thinking: 

Note that any `loose` option overrides `assumption` for the specific plugins that uses `loose`, so it's not possible to override `loose` in create-react-app unless they provide a way to do it.

**Comment by dimaqq** [comment]
CRA references this issue: https://github.com/babel/babel/pull/9486
Source: first two matches at https://github.com/facebook/create-react-app/search?q=loose&type=code
(I think I'm out of my depth here, I'll post a new issue in CRA so that maybe babel and react folk can talk to each other directly?)
