### ISSUE TITLE
(plugin-transform-react-jsx): Compile error, when element's JSXAttribute key isn't given a value

### ISSUE THREAD

**Issue by hajnalbendeguz** [babel/babel#12931]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

When compiling a React component that returns an array of elements and we missuse the key prop, we only get the following error:
```
TypeError: <filename>: Property arguments[2] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got undefined
```

**Input Code**

```js
function Component() {
  return (
    [
      <div key></div>
    ]
  )
}

```

**Expected behavior**

I want the console error to be more helpful on why the build process failed or the build to be successful.

**Babel Configuration**
- CRA v4.0.2
https://github.com/facebook/create-react-app/tree/v4.0.2/packages/babel-preset-react-app

**Environment**

```
 System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  npmPackages:
    babel-eslint: ^10.0.3 => 10.1.0 

```
- Babel version(s): v7.12.3
- @babel/plugin-transform-react-jsx" v7.12.17
- Monorepo: no

**Possible Solution**

A warning should be printed after the transformed value is empty(null) for the attribute named "key". Or maybe the true boolean literal should be applied, as stated in the documentation for JSX props.

https://github.com/babel/babel/blob/265424d43f964cafd976a2143ddeee4066e14fd6/packages/babel-plugin-transform-react-jsx/src/create-plugin.js#L406-L423

**Additional context**

I don't think this is a big issue since key values are supposed to be unique in every list. It would save some debugging for others, especially since it doesn't occur in development mode. I'm ready and happy to help improve the code.

**Comment by nicolo-ribaudo** [comment]
@hajnalbendeguz Would you like opening a PR throwing a more descriptive error?

---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in `packages/babel-plugin-transform-react-jsx/test/fixtures/react-automatic`. You can use the `should-disallow-spread-children` test in that folder as an example of test that throws
1. Update the code!
1. `yarn jest transform-react-jsx` to run the tests
    - You can run `OVERWRITE=true yarn jest transform-react-jsx` to automatically update the tests.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!
