### ISSUE TITLE
TypeScript: 'assert and assign' vs createParenthesizedExpressions

### ISSUE THREAD

**Issue by thorn0** [babel/babel#12932]
## Bug Report

**Current behavior**

`SyntaxError: Invalid parenthesized assignment pattern (1:0)`

**Input Code**

```js
(a as any) = null;
```

**Expected behavior**

no error

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

```js
require("@babel/parser").parse("(a as any) = null", {
  createParenthesizedExpressions: true,
  plugins: ["typescript"],
});
```

- Babel version(s): 7.13.4
- Node/npm version: Node 14.15.0
- OS: Windows 10
- How you are using Babel: API

**Additional context**
Works fine without `createParenthesizedExpressions`.
Related PR: https://github.com/babel/babel/pull/7098

**Comment by fedeci** [comment]
Working on this.
