### ISSUE TITLE
subclassing Error

### ISSUE THREAD

**Issue by PinkaminaDianePie** [babel/babel#1294]
there is no stack trace in Error subclasses.

```javascript
var MyError = class extends Error{
	get name(){return 'MyError' }
	constructor(message){
		super(message);
	}
}
throw new MyError("")
```
output of this code: 
```bash
~/projects/planck/build/lib/active-record/lib$ node ./active-record-base.js
Uncaught exception: [MyError]
```
expected output: 
```bash
~/projects/planck/build/lib/active-record/lib$ node ./active-record-base.js
throw new MyError("")
      ^
MyError
    at Object.<anonymous> (/source/lib/active-record/lib/active-record-base.js:107:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by zloirock** [comment]
![sub-error](http://habrastorage.org/files/398/f4d/b90/398f4db903724412a02c858068dc0c17.png)
Update to actual version. Subclassing `Error` was added in 5.1.9.

**Comment by PinkaminaDianePie** [comment]
upgraded to 5.1.10, still have an issue with Errors.

stack trace appeared, but it show place where my subclass declared, instead of place where error was thrown. Even if i export MyError class and use it in another module - stack trace show module where MyError was declared.

```javascript
/source/lib/active-record/lib/active-record-base.js:101
class MyError extends Error{
             ^
MyError: test error message
    at new MyError (/source/lib/active-record/lib/active-record-base.js:101:14)
    at Object.<anonymous> (/source/test/active-record/active-record.js:5:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```
i thought it was problem with source maps, but all other features not affected, stack trace in all other code works fine. builtin Error also show normal stack trace.

**Comment by sebmck** [comment]
@PinkaminaDianePie That's basically the native constructor subclassing just does a `new Error` inside the constructor and then changes the prototype to `this`. There's no other way to shim it in and the call stack is always going to be changed.

**Comment by PinkaminaDianePie** [comment]
@sebmck but why @zloirock have normal stack trace in Error subclass?

**Comment by zloirock** [comment]
@PinkaminaDianePie 
```js
throw new MyError("");
      ^
MyError
    at new MyError (C:\x.js:11:21)       // => var _this = new _Error(message);
    at Object.<anonymous> (C:\x.js:29:7) // => throw new MyError("");
```

**Comment by PinkaminaDianePie** [comment]
@zloirock my stack trace shows same code lines as yours, but on throw it highligts 
```javascript
class MyError extends Error{
```
instead of 
```javascript
throw new MyError("");
```

**Comment by zloirock** [comment]
@PinkaminaDianePie I run a precompiled code without source maps.

**Comment by PinkaminaDianePie** [comment]
without sorce maps it highlight this at top of stack trace:
```javascript
        var _this2 = new _Error(message);
                     ^
MyError: test error message
```

**Comment by zloirock** [comment]
I have no idea where the difference - v8 versions or differences in base code. In any case, current stack trace is enough to understand where the problem and change it is problematically or not possible.

**Comment by PinkaminaDianePie** [comment]
@zloirock i have similar behavior on node v0.10.36 and io v1.7.1, so no changes to my code for large range of v8 versions.
