### ISSUE TITLE
babel-node cannot load configuration file in ESM project

### ISSUE THREAD

**Issue by zhilidali** [babel/babel#12942]
## Bug Report

**Current behavior**

`package.json` In the project is set to `{"type": "module"}`,
run `npx babel-node --config-file ./babel.config.cjs index.js`,
`@babel/node` does not load the `babel.config.cjs` configuration file

**Input Code**

`package.json`
```json
{
  "type": "module"
}
```

**Expected behavior**

run `npx babel-node index.js`, Babel can load configuration files to run code.

**Babel Configuration**
- Filename: `babel.config.cjs`

```js
module.exports = {
  plugins: [['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }]],
};
```

**Environment**

- Babel version(s): `7.13.0`
- Node/npm version: ` v14.16.0`

**Additional context**

In the same case, when I compile the code with `@babel/cli`, run `npx babel index.js -o build.js`, Babel successfully loads the configuration file.

Alternatively, the configuration file can be loaded successfully by removing `{"type": "module"}` from `package.json`.

**Comment by nicolo-ribaudo** [comment]
Native modules are not supported, please see https://github.com/babel/babel/issues/11934.

**Comment by zhilidali** [comment]
@nicolo-ribaudo thanks, [node-loader-babel](https://github.com/node-loader/node-loader-babel) can solves my problem, and I expect Node.js Loader API became stable.
