### ISSUE TITLE
preset-env not removing all consts when using browserslist - works fine when directly supplied with target (v7.12.7 works fine)

### ISSUE THREAD

**Issue by neil-morrison44** [babel/babel#12953]
## Bug Report

**Current behavior**

I have a `browserslist` property in my package.json, if this is set to `ie 11` then my output file will contain ~43 `consts`, if I do `not ie 11` then there's ~293 `const`s.

I'm using webpack & babel-loader and my presets look like:

```js
                presets: [
                  [
                    "@babel/env",
                    {
                      modules: false,
                      useBuiltIns: "usage",
                      corejs: { version: 3, proposals: true },
                    },
                  ],
                  "@babel/preset-react",
                ],
```

(I've tried swapping the order and it didn't change much)

As far as I can tell there's nothing special about the `const`s that're being forgotten about, aside from them coming from a node_module (which is correctly being parsed since it's being run through `@babel/preset-react` just fine)

@babel/preset-env v7.12.7 gets every `const` with exactly the same config, both the current version (v7.13.9) and v7.13.0 seem to leave some `const`s.

The strange thing is if I tell `@babel/env` to target IE 11 explicitly by doing

```js
                    {
                      modules: false,
                      useBuiltIns: "usage",
                      corejs: { version: 3, proposals: true },
                     target: {
                       ie: 11
                     },
                    },
```

then v7.13.7 works as well as v7.12.7 does when reading from the browserslist

**Expected behavior**

It builds an output without any `const`s when targetting IE 11 via browserslist

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```
  System:
    OS: Linux 5.4 Debian GNU/Linux 8 (jessie) 8 (jessie)
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    @babel/preset-env: 7.13.7 => 7.13.7
```
- Babel version(s): latest as of issue
- Monorepo: no
- How you are using Babel: webpack

Repo isn't publicly accessible & I'm not sure how easy it'd be to get a contained reproducible example of it happening (might be something to do with volume, I've really got no idea)

**Comment by JLHwung** [comment]
Can you add `debug: true` to the `preset-env` config and attach the log output? It will print the resolved targets and enabled plugins.

**Comment by nicolo-ribaudo** [comment]
> Repo isn't publicly accessible & I'm not sure how easy it'd be to get a contained reproducible example of it happening (might be something to do with volume, I've really got no idea)

Can you at least try understanding if the remaining `const`s are from a dependency, and which dependency?

**Comment by neil-morrison44** [comment]
@nicolo-ribaudo remaining `const`s are from an internal dependency, which is something in node_modules but the `const`s are right beside jsx which is getting transformed by `@babel/preset-react` correctly & errors when `@babel/preset-react` is removed or the `exclude` regex is changed to exclude the dependency.

They'll be very similar to another internal dependency (two react component libraries) which appears to be getting fully transpiled

@JLHwung I've tried adding
```
                  [
                    "@babel/env",
                    {
                      modules: false,
                      useBuiltIns: "usage",
                      corejs: { version: 3, proposals: true },
                      debug:true
                    },
                  ],
```
but I'm not seeing any different output to running without it - if that's the right config I'll have another look tomorrow & check we're not doing something which is hiding the output

**Comment by nicolo-ribaudo** [comment]
Can you try with `BABEL_SHOW_CONFIG_FOR=./path/to/dependency/with/const.js npm run build` (with your build command instead of `npm run build`)?

**Comment by neil-morrison44** [comment]
Could have found what's going on, the dependency does have a `browserslist` property which excludes ie 11 in its `package.json` - would that be effecting things in v7.13.x but not v7.12.x?

**Comment by neil-morrison44** [comment]
Running our build with `BABEL_SHOW_CONFIG_FOR ` gives the following output, but it also breaks the build (on both v7.13.9 & v 7.12.7)

```
Babel configs on "/XYZ/node_modules/[the_dependency]/lib/components/locationInfo/index.js" (ascending priority):
programmatic options from babel-loader
{
  "plugins": [
    "lodash",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime"
  ],
  "presets": [
    [
      "@babel/env",
      {
        "modules": false,
        "useBuiltIns": "usage",
        "corejs": {
          "version": 3,
          "proposals": true
        }
      }
    ],
    "@babel/preset-react"
  ],
  "filename": "/XYZ/node_modules/[the_dependency]/lib/components/locationInfo/index.js",
  "sourceMaps": true,
  "sourceFileName": "/XYZ/node_modules/[the_dependency]/lib/components/locationInfo/index.js",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  }
}
Error parsing bundle asset "/XYZ/dist/main~01e7b97c.8bb96daf9d688b78e8c0.js": no such file
```

**Comment by nicolo-ribaudo** [comment]
I know what's going on.

We recently added `targets` support to `@babel/core` (other than `@babel/preset-env`) and we discovered that [browserslist config files are meant to be resolved relative to the file that is being compiled](https://github.com/babel/rfcs/pull/2#issuecomment-619573888).

1. This affected the `targets` option of `@babel/preset-env`, which is a regression
2. Given this dependencies scenario, it probably doesn't make sense even for `@babel/core`?

As a workaround (but I didn't test it), you can try passing `configPath: __dirname + "/package.json"` to `@babel/preset-env`'s options, to force it to load the top-level browserslist config.

**Comment by neil-morrison44** [comment]
Can confirm `configPath: __dirname + "/package.json"` fixes the issue - will do that rather than pin to v7.12.x

**Comment by DamienCassou** [comment]
I had a similar problem and adding `configPath` fixed it.
