### ISSUE TITLE
[Bug]The transformation of async function will cause it losing `Symbol.toStringTag` property

### ISSUE THREAD

**Issue by NE-SmallTown** [babel/babel#12959]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoASBIF8SSpMR0AbAUwDpH0BzXAclRGzoYoSFABcMHgBpBAbQDKYALYAjJq2Tp5yAE6oInACrBOAXRgBeK5ICC4aADEkUNJh74gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.13.9&externalPlugins=)

**Input Code**

```js
async function foo() {
	
}

console.log('is foo async: ', foo[Symbol.toStringTag] === 'AsyncFunction')
```

**Expected behavior**

The console ouputs `true`. Just as the behavior when not be transformed

**Environment**

```
No need, see REPL
```
- Babel version(s): 7.13.9
- Node/npm version: No need, see REPL
- OS: No need, see REPL
- How you are using Babel: No need, see REPL

**Possible Solution**

**Additional context**

**Comment by JLHwung** [comment]
The `Symbol.toStringTag` is a reflection feature, a code which checks the code itself. Babel does not guarantee reflection works due to the nature of transpiler -- which compiles JavaScript to JavaScript. 

Although we could emit code to overwrite `foo[Symbol.toStringTag]`, I don't think it should be overwritten at all, because one may use reflection to check if the async function has been transpiled by Babel.

Similarly, Babel does not guarantee `Function.prototype.toString.call(async function() {}) === "async function() {}"`, too.

**Comment by NE-SmallTown** [comment]
Thanks!

> I don't think it should be overwritten at all, because one may use reflection to check if the async function has been transpiled by Babel.

It's fair, but the question is if you guarantee that we can "check if the async function has been transpiled by Babel.", then you should also garantee that we can check whether a function is a async function, right? (If I'm wrong, please let me know)

But seems that there is no **any way** to identify whether a function is a async function if it has been transformed by Babel?

**Comment by nicolo-ribaudo** [comment]
Well, after being transpiled by Babel it's not an async function anymore (according to some definition of "async function").

Regardless of Babel, these two functions are exactly the same:
```js
 async function f() {
  return Promise.resolve(2);
}
function g() {
  return Promise.resolve(2);
}
```

but only one of them has the `Symbol.toStringTag`.

**Comment by NE-SmallTown** [comment]
> Regardless of Babel, these two functions are exactly the same:

No exactly right , That's depend on how you use it. Thinks about this scenario, I want/need to run a function **as soon as possible**. This function may be an async function **or not**, like :

```javascript
const getFooFunc = () => {
  if (Math.random() > 0.5) {
    return async () => await Promise.reolsve()
  } else {
    return () => {}
  }
}

async function main1() {
  await getFooFunc()()

  console.log('side effect.')
}

function main2() {
   getFooFunc()()

   console.log('side effect.')
}
```

```
main1() // this will output 'end, 'side effect'.   **always**
console.log('end')
```

```
main2() // this will output 'side effect', 'end'. **always**
console.log('end')
```

But the "correct" behavior should be, if `getFooFunc` return an aync function, it should ouput 'side effect', 'end', and if `getFooFunc` return a normal function, it should output 'end', 'side effect'. So I should change this code to :

```javascript
function main() {
   const foo = getFooFunc()

  if (foo[Symbol.toStringTag] === 'AsyncFunction') {
    foo().then(() => console.log('side effect.'))
  } else {
    foo()

    console.log('side effect.')
  }
}
```

```
main() // this will output 'side effect', 'end' when `foo` is an async function, and ouput 'end', 'side effect' when not.
console.log('end')
```

By this way, I can achieve my goal “run a function **as soon as possible**”. But if the async function be transformed by Babel, there is no way to achieve this(we must execute `foo` and check the return value is thenable/promise, but sometimes you cant run it first)

**Comment by nicolo-ribaudo** [comment]
I don't understand your use case. How would you handle the two functions defined in https://github.com/babel/babel/issues/12959#issuecomment-790486118?

> But if the async function be transformed by Babel, there is no way to achieve this(we must execute foo and check the return value is thenable/promise, but sometimes you cant run it first

That's generally the correct approach: what makes a function async is an implementation detail of the function. What matters is of "what the function does" happens synchronously or asynchronously.

**Comment by NE-SmallTown** [comment]
> How would you handle the two functions defined in #12959 (comment)?

That's constrained by our library rule: if you want your `foo`(in real library it's a option) be async, you need declare your `foo` as an async function instead returning a promise, if you want your `foo` be a normal function, you need declare your `foo` as a normal function

> That's generally the correct approach: what makes a function async is an implementation detail of the function. What matters is if "what the function does" happens synchronously or asynchronously.

Yea, generally that's ture. But there are some scenarios(like I described above) depends on "how to use it(the option(i.e. `foo`))" rather than "what is a async function in definition/academe"

The ECMAScript itself allows us to do that, but after being transformed we can't do that anymore. So maybe we need find some ways to do it

**Comment by nicolo-ribaudo** [comment]
Closing in favor of https://github.com/babel/babel/issues/8642
