### ISSUE TITLE
Typo in 7.13.0 release notes

### ISSUE THREAD

**Issue by GhassenRjab** [babel/babel#12961]
There is a typo in this article https://babeljs.io/blog/2021/02/22/7.13.0

![image](https://user-images.githubusercontent.com/6123547/109874732-c861d180-7c6f-11eb-9081-f5b0a5ef15d3.png)

It is saying Babel 7.12.0 instead of 7.13.0

**Comment by nicolo-ribaudo** [comment]
Thanks, fixed!
