### ISSUE TITLE
ReferenceError: _objectSpread is not defined

### ISSUE THREAD

**Issue by NCorreia100** [babel/babel#12966]
Hi, this issue seems to be caused by @babel/plugin-proposal-object-rest-spread. 
It's inconsistent as in some instances (like react-router) it has no problems transpiling, whereas it doesn't work in some in-house made modules. Everything was working before without making config changes (maybe a browser update?).
This issue also seems to only happen in development mode, I'm using eval devtool but I've tried others.

Unlike the other reported issue throwing the same error, in my case I'm not using Jest. I couldn't find this issue reported elsewhere. I've tried to get different plugin versions & rebuilding node_modules and package-lock.json.

Here's a code snippet example where the code is breaking:

      this.setNotification(confirmationType, success = false,showConfirmation=false, payload = this.state.confirmationPayload) {
         if (!confirmationType) throw ('confirmationType is missing:', confirmationType)
    
        this.setState({
             confirmationType,
             notificationSuccess: success,
             showNotification: !success||!showConfirmation,
             confirmationPayload: {...payload}  //here's the implementation of rest spread
        })
     }

Here's the stack trace in the console:
![rest_spread_issue](https://user-images.githubusercontent.com/29066146/110012040-b589e400-7ce5-11eb-972e-9ef4ad8967a4.JPG)

Here's my webpack config:
           
          use: {
                loader: 'babel-loader',
                query: {
                  presets: ['@babel/preset-env','@babel/preset-react'] ,
                  plugins: [   
                    // "babel-plugin-es6-promise", //for older browsers that don't support Promises 
                    "@babel/plugin-proposal-object-rest-spread", //convert to ES2015 rest spread
                    "@babel/transform-runtime", //for async await                                                                  
                    "@babel/plugin-syntax-dynamic-import",//for dynamic imports 
                    "@loadable/babel-plugin", //break code into chunks 
                    "@babel/plugin-transform-destructuring", //bug https://github.com/facebook/regenerator/issues/391
                    "@babel/plugin-transform-regenerator", //async imports of modules                        
                    "@babel/plugin-proposal-class-properties",   //transforms static class properties                 
                    "@babel/plugin-transform-react-constant-elements", //optimizes garbage collection
                    "@babel/plugin-transform-react-inline-elements",  //remove vars from global scope
                    "babel-plugin-transform-react-remove-prop-types", //removed unused react propTypes
                    "babel-plugin-transform-dead-code-elimination", //? eliminates unused code
                 ]                
                }                             
              }      

Here's my package.json:

 
        "dependencies": {
    "@babel/polyfill": "^7.8.3",
    "bootstrap": "^4.4.1",
    "classnames": "^2.2.6",
    "compression": "^1.7.4",
    "copy-webpack-plugin": "^6.0.3",
    "dotenv": "^8.2.0",
    "dotenv-expand": "^5.1.0",
    "express": "^4.16.4",
    "html-webpack-plugin": "4.0.0-beta.4",
    "md5": "^2.2.1",
    "memory-cache-stream": "^1.2.0",
    "promise-polyfill": "^8.1.3",
    "prop-types": "^15.6.2",
    "react": "^16.7.0",
    "react-datepicker": "^2.1.0",
    "react-dev-utils": "^11.0.3",
    "react-dom": "^16.7.0",
    "react-loadable": "^5.5.0",
    "react-phone-input-auto-format": "^0.1.0",
    "react-recaptcha-v3": "^1.0.2",
    "react-render-html": "^0.6.0",
    "react-router-dom": "^4.3.1",
    "react-select": "^2.2.0",
    "webfontloader": "^1.6.28",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.10",
    "whatwg-fetch": "^3.0.0"
       },
        "devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/helpers": "7.5.1",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.4",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-destructuring": "^7.10.4",
    "@babel/plugin-transform-react-constant-elements": "^7.8.3",
    "@babel/plugin-transform-react-inline-elements": "^7.8.3",
    "@babel/plugin-transform-regenerator": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.4",
    "@babel/preset-react": "^7.5.4",
    "@loadable/babel-plugin": "^5.10.3",
    "babel-loader": "^8.0.5",
    "babel-plugin-es6-promise": "^1.1.1",
    "babel-plugin-named-asset-import": "^0.3.6",
    "babel-plugin-transform-dead-code-elimination": "^2.2.3",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "cache-loader": "^4.1.0",
    "core-js": "^3.6.4",
    "css-loader": "^3.4.2",
    "file-loader": "^5.1.0",
    "nodemon": "^2.0.2",
    "postcss-flexbugs-fixes": "^4.2.0",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.7.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "svg-url-loader": "^4.0.0",
    "url-loader": "^3.0.0"
        }
 
Thanks in advance.

**Comment by NCorreia100** [comment]
Update:
Removing babel-plugin-transform-dead-code-elimination from the plugin list fixed the issue.

**Comment by JLHwung** [comment]
If you are using `@babel/transform-runtime`, you should also install `@babel/runtime`.
