### ISSUE TITLE
Allow multiple class static block, and follow the document order

### ISSUE THREAD

**Issue by Kingwl** [babel/babel#12979]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oQC5nQS2KgZtALzQCMKamOeC0wA9gHYT0gCmAdCPQOYAU6ABbYIHfABpoQkWPwBKaAF8KGLLmj5CJAEwqq62g2atO3ftNGbJF2fKV61eTVugBmJIqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.13.9&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.13.0%2C%40babel%2Fplugin-proposal-class-static-block%407.12.13)

According to https://github.com/tc39/proposal-class-static-block

> A class may have any number of static {} initialization blocks in its class body.
> static {} initialization blocks are evaluated in document order interleaved with static field initializers.

**Input Code**

```js
class C {
  static  f = 1
  static { console.log(this.f, this.ff) }
  static ff = 2
  static { console.log(this.ff, this.fff) }
  static fff = 3
}
```

**Expected behavior**

Multiple block works fine. And the evaluate order follow the document order.

But currently:

> Duplicate static block in the same class (5:2)

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Already tracked at https://github.com/babel/babel/pull/12738!

**Comment by Kingwl** [comment]
Thanks!
