### ISSUE TITLE
Switch statements should create a new lexical scope

### ISSUE THREAD

**Issue by joeybaker** [babel/babel#1297]
The spec says that `switch` statements should create a new scope, [but they don't appear to in babel](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=let%20a%20%3D%20true%0Alet%20b%20%3D%20false%0A%0Aswitch%20(a)%20%7B%0A%20%20case%20true%3A%0A%20%20%20%20let%20b%20%3D%202%0A%20%20%20%20break%0A%20%20case%20false%3A%0A%20%20%20%20let%20c%20%3D%203%0A%20%20%20%20break%0A%7D). 

First discovered here: https://github.com/eslint/eslint/pull/2330/files#r28651621

**Comment by sebmck** [comment]
Oh right, this is because ESTree doesn't represent switch bodies as block statements, grr.

**Comment by joeybaker** [comment]
Thanks!

**Comment by sebmck** [comment]
Fixed as of 5.1.11, thanks!
