### ISSUE TITLE
No matching version found for @babel/preset-env@^1.7.0.

### ISSUE THREAD

**Issue by MollyXuemn** [babel/babel#12973]
## Bug Report
(base) Meinis-MacBook-Pro:threejs-parcel-boilerplate meinixue$ npm i parcel-plugin-glsl
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://registry.npmjs.org/w3c-xmlserializer failed, reason: Socket timeout
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/preset-env@^1.7.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/meinixue/.npm/_logs/2021-03-06T12_23_39_279Z-debug.log
(base) Meinis-MacBook-Pro:threejs-parcel-boilerplate meinixue$ npm install --save-dev @babel/preset-env
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/preset-env@^1.7.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/meinixue/.npm/_logs/2021-03-06T12_30_19_982Z-debug.log
(base) Meinis-MacBook-Pro:threejs-parcel-boilerplate meinixue$ npm uninstall parcel
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/preset-env@^1.7.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/meinixue/.npm/_logs/2021-03-06T12_37_22_408Z-debug.log
<img width="731" alt="Screenshot 2021-03-06 at 20 40 56" src="https://user-images.githubusercontent.com/46561070/110207061-a344ad00-7e81-11eb-8680-4a84d505981b.png">
<img width="723" alt="Screenshot 2021-03-06 at 20 41 04" src="https://user-images.githubusercontent.com/46561070/110207067-a770ca80-7e81-11eb-8a08-6ea72393c5e5.png">

- [x] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
The first version of `@babel/preset-env` is 7.0.0. This is a bug with whatever package is trying to use 1.7.0 as a dependency.
