### ISSUE TITLE
Incorrect transformation for Set with spread operator

### ISSUE THREAD

**Issue by kumar-ranjan-singh** [babel/babel#12984]
## Bug Report

**Current behavior**
Current behaviour can be seen in babel try it [link](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=true&code_lz=NoOjAoDsFMHcAIDK0Au5gEYA0AmLBmAXQEpjCg&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.13.9&externalPlugins=). After transformation the transformed code is not equivalent and gives wrong computation.

**Input Code**

```js
[...(new Set([1,2,3]))]
```
**Transpiled Code**

```js
[].concat(new Set([1, 2, 3]));
```

**Expected behavior**
The transformation done is wrong, can be corrected in many ways.

```
- Babel version(s):  v7.10.0
- Node/npm version: Node 12
- OS: macOS 11.1
- Monorepo: Lerna
- How you are using Babel: webpack


I had to fix by using ```js
Array.from(new Set([1,2,3]))
```

**Comment by nicolo-ribaudo** [comment]
If you need spec-compliant behaviour you can disable the `loose` option.

**Comment by kumar-ranjan-singh** [comment]
> If you need spec-compliant behaviour you can disable the `loose` option.

Thanks @nicolas-marien, do babel recommends for which plugins to use `loose` options, for me its increases the bundle size a lot, is there any recommendation document from babel. 

Thanks.

**Comment by nicolo-ribaudo** [comment]
It really depends on your code. Rather than `loose` I strongly recommend using the new `assumptions` option (https://babeljs.io/docs/en/options#assumptions), which gives you control exactly on what optimization Babel can make depending on how you code.

**Comment by kumar-ranjan-singh** [comment]
Thanks @nicolo-ribaudo , I will close this issue and consider implementing recommended (https://babeljs.io/docs/en/options#assumptions) options.
