### ISSUE TITLE
yarn add  <<<< @babel/preset-env

### ISSUE THREAD

**Issue by ron-zhao** [babel/babel#12987]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

![捕获](https://user-images.githubusercontent.com/34527495/110475401-cbe7d380-811b-11eb-96bd-b6a96a228f79.PNG)

**Comment by JLHwung** [comment]
The error is thrown from PowerShell, which means `@` in `@babel/preset-env` can not be parsed as a string in PowerShell. Consider either upgrade PowerShell to 3.0 or escape `@` by <code>`</code>

```ps
yarn add `@babel/core --dev
```

**Comment by ron-zhao** [comment]
thank you
