### ISSUE TITLE
"'return' outside of function" errors in babel 5.x

### ISSUE THREAD

**Issue by maximilianschmitt** [babel/babel#1298]
Create a script `test.js`:

```js
'use strict';

if (true) {
  console.log('true');
  return;
}
```

Run it with:

```
$ babel-node test
```

At version **4.x** it works just fine and outputs `true`.
At version **5.1.10** you get this error:

```
/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: /Users/maximilianschmitt/Desktop/test.js: 'return' outside of function (5:2)
  3 | if (true) {
  4 |   console.log('true');
> 5 |   return;
    |   ^
  6 | }
  7 |
    at Parser.pp.raise (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.parseReturnStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:247:74)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:77:19)
    at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseBlock (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:93:19)
    at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseIfStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:241:26)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:75:19)
    at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
```

**Comment by sebmck** [comment]
Expected behaviour. Top level returns are not ES6 module compliant.

On Sunday, 19 April 2015, maximilianschmitt <notifications@github.com>
wrote:

> Create a script test.js:
>
> 'use strict';
> if (true) {
>   console.log('true');
>   return;
> }
>
> Run it with:
>
> $ babel-node test
>
> At version *4.x* it works just fine and outputs true.
> At version *5.1.10* you get this error:
>
> /usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
>     throw err;
>           ^
> SyntaxError: /Users/maximilianschmitt/Desktop/test.js: 'return' outside of function (5:2)
>   3 | if (true) {
>   4 |   console.log('true');
> > 5 |   return;
>     |   ^
>   6 | }
>   7 |
>     at Parser.pp.raise (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:68:13)
>     at Parser.pp.parseReturnStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:247:74)
>     at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:77:19)
>     at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
>     at Parser.pp.parseBlock (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
>     at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:93:19)
>     at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
>     at Parser.pp.parseIfStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:241:26)
>     at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:75:19)
>     at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1298>.
>


-- 
Sebastian McKenzie

**Comment by maximilianschmitt** [comment]
Ah OK, I didn't know that. I just read something about how `return`s outside of functions are legal in node.js so I was expecting babel-node to behave the same way in that regard.

I'm not sure if `return`s outside of functions will ever become illegal in node. If not, maybe it would be good to optionally allow them with babel-node.

**Comment by sebmck** [comment]
> I'm not sure if `return`s outside of functions will ever become illegal in node.

There was some discussion of this in esdiscuss. I tried to find the thread (Have a link handy @michaelficarra?) but the consensus was (unfortunately) that ES6 modules would not be changed to allow top-level return, which is a detriment to ES6 module implementations that will want CommonJS interoperability.

> If not, maybe it would be good to optionally allow them with babel-node.

Interoperability issues are introduced though which is harmful.

**Comment by stagas** [comment]
I think, however, there should be an option to skip these top level checks, because this isn't ES6, it's a transpiler, in which the user might want to use the output elsewhere like in a `new Function(code)` where it's valid.

**Comment by sebmck** [comment]
No, this is an ES6 transpiler so it should be following ES6 semantics. ES6-like doesn't make much sense.

**Comment by feross** [comment]
So, using babel on code that I then want to run through `browserify` isn't supported? Why can't there be a `node` option?

**Comment by stagas** [comment]
+1 locally I remove the check because for what I'm doing I need this but if it was an option it would be super great.

**Comment by sebmck** [comment]
Top level `return` is not supported by default because the spec doesn't support it. Node/io.js are going to have an extremely hard time supporting ES6 modules because of the weird module function wrapper.

Anyway, you can disable this via the [`loose` option](http://babeljs.io/docs/advanced/loose/#es6-modules/), I don't really like to recommend it because of the spec compliancy issues mentioned before but you can I guess:

**.babelrc**

```javascript
{
  "loose": ["es6.modules"]
}
```
**CLI**

```sh
$ babel --loose es6.modules
```

**Node API**

```javascript
require("babel-core").transform("code", { loose: ["es6.modules"] });
```

**Comment by stagas** [comment]
This is great. Perhaps this behavior should documented [here](http://babeljs.io/docs/advanced/loose/#es6-modules) as well?

**Comment by sebmck** [comment]
Yeah it should. Using it doesn't make any sense though as you're merging two fundamentally distinct semantics together that is likely never going to work in the future.

**Comment by stagas** [comment]
In a controlled environment where you are the only consumer you don't really care about that.

**Comment by michaelficarra** [comment]
*cringe*

**Comment by stagas** [comment]
Haha

**Comment by Wandalen** [comment]
What if I want transpile source code which I don't control? What if that source code have "return" outside of function. That works perfectly fine in nodejs. Point of view that it's must be not working just only because it's stated in a paper doesn't make sense for me.

**Comment by Wandalen** [comment]
Anybody know how can I make babel ignore "return" outside of function? Seems loose: ["es6.modules"]  does not work anymore.

**Comment by hzoo** [comment]
This issue was created for Babel 5 which isn't supported anymore. If you need it babylon has a option for it https://github.com/babel/babylon#options but doesn't mean we **support** the transform just the parsing.

**Comment by Wandalen** [comment]
Ah, that's useful. Thank you @hzoo

**Comment by madhavi-hai** [comment]
what is the solution to do global returns in node.js

**Comment by hzoo** [comment]
`allowReturnOutsideFunction` is the babylon option but again this is for babel 5.
