### ISSUE TITLE
potential security Vulnerability with lodash version 4.17.19 dependency 

### ISSUE THREAD

**Issue by bhadana-rajesh** [babel/babel#12992]
Hi, 

lodash version 4.17.19 has potential security vulnerability, you might consider updating lodash version 

High7.2CVE-2021-23337Feb-15-2021 | lodash-4.17.19.js | All versions of package lodash; all versions of package org.fujion.webjars:lodash are vulnerable to Command Injection via template.
-- | -- | --

https://github.com/lodash/lodash/commit/3469357cff396a26c363f8c1b5a91dde28ba4b1c

Thanks,
Rajesh

**Comment by bhadana-rajesh** [comment]
@jridgewell , Thank you for quick response .

Now I understand babel is not using _.template.  but our devops pipeline tool is showing vulnerability due to lodash 4.17.19.

can you please consider request to upgrade lodash to 4.17.21 or latest released version

**Comment by nicolo-ribaudo** [comment]
Babel depends on lodash using ^, which means you can automatically get the update without needing anything from us. Just delete lodash from your lockfile and run `npm install` or `yarn install` again.
