### ISSUE TITLE
Flow interface declarations do not work at all

### ISSUE THREAD

**Issue by thealjey** [babel/babel#1299]
Consider the following code:

    declare class ChildProcess {
      on(type: string, fn: (code: number) => void): void;
      kill(): void;
    }
    
    /**
     * here the nullable "maybe" type (the question mark) validates just fine
     */
    var flow: ?ChildProcess;
    
    function typecheck() {
      /**
       * everything works great up to this point
       * flow is nullable, but we check for it's existence and the kill method is declared
       */
      if (flow) flow.kill();
      /**
       * and here all hell breaks loose
       * - if I omit the type declaration then the next line reports that
       *   the "on" method is undefined
       * - if I leave it as is babel says that ChildProcess is undefined
       * - ridiculously enough, if I put "any" there instead of "ChildProcess",
       *   babel says that "any" is undefined (LOL, what?)
       * - also, this line does not support maybe types,
       *   if I put a question mark before the type babel dies with "unexpected identifier"
       */
      flow: ChildProcess = spawn('flow', [], {stdio: 'inherit'});
      flow.on('close', function (code) {
        
      });
    }

This is driving me crazy, can you please point me in the right direction if maybe I am doing something wrong here?
The reason why I think that it's a bug is that babel and flow seem to disagree about whether ChildProcess is defined or not.

**Comment by sebmck** [comment]
Babel doesn't check flow types.

On Sunday, 19 April 2015, Al Jey <notifications@github.com> wrote:

> Consider the following code:
>
> declare class ChildProcess {
>   on(type: string, fn: (code: number) => void): void;
>   kill(): void;
> }
>
> /**
>  * here the nullable "maybe" type (the question mark) validates just fine
>  */
> var flow: ?ChildProcess;
>
> function typecheck() {
>   /**
>    * everything works great up to this point
>    * flow is nullable, but we check for it's existence and the kill method is declared
>    */
>   if (flow) flow.kill();
>   /**
>    * and here all hell breaks loose
>    * - if I omit the type declaration then the next line reports that
>    *   the "on" method is undefined
>    * - if I leave it as is babel says that ChildProcess is undefined
>    * - also, this line does not support maybe types,
>    *   if I put a question mark before the type babel dies with "unexpected identifier"
>    */
>   flow: ChildProcess = spawn('flow', [], {stdio: 'inherit'});
>   flow.on('close', function (code) {
>
>   });
> }
>
> This is driving me crazy, can you please point me in the right direction
> if maybe I am doing something wrong here?
> The reason why I think that it's a bug is that babel and flow seem to
> disagree about whether ChildProcess is defined or not.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1299>.
>


-- 
Sebastian McKenzie

**Comment by thealjey** [comment]
@sebmck then can you please explain to me why this error is happening:

flow: any = _spawn.spawn('flow', [], { stdio: 'inherit' });
            ^
ReferenceError: any is not defined
    at typecheck (/Users/al/Documents/www/adcube/backend/app.js:25:12)
    at Object.<anonymous> (/Users/al/Documents/www/adcube/backend/app.js:33:1)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/al/Documents/www/adcube/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:122:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/al/Documents/www/adcube/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:135:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/Users/al/Documents/www/adcube/node_modules/babel/bin/_babel-node:111:12)
    at Module._compile (module.js:460:26)

**Comment by sebmck** [comment]
So, that's not actually valid flow syntax. This isn't a problem with Babel or Flow, it's actually the code itself. You aren't writing an labelled statement with an assignment. ie. What you're actually writing is just `any = spawn('flow', [], {stdio: 'inherit'});` with the label `flow`.
