### ISSUE TITLE
Add `absoluteImports` configuration option to `preset-env`

### ISSUE THREAD

**Issue by charlessuh** [babel/babel#13002]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem?**

`preset-env` (which now uses `babel-polyfills` under the hood) should expose an option available in `babel-polyfills` called [`absoluteImports`](https://github.com/babel/babel-polyfills/blob/main/docs/usage.md#absoluteimports).

This option is needed in more complicated setups -- for example, if you have an application split up as a monorepo, have enabled yarn 2's strict mode, and want to compile files across the monorepo, you might want polyfills like `core-js` to be resolved from a single resolve path where it can be resolved, instead of needing to specify `core-js` as a dependency in every one of your individual packages in the monorepo (which can be repetitious and error-prone.)

Note there is precedence for exposing an option like this, in `@babel/plugin-transform-runtime` today with [`absoluteRuntime`](https://babeljs.io/docs/en/babel-plugin-transform-runtime#absoluteruntime), which does the same thing.

**Describe the solution you'd like**

`preset-env` should support configuring an `absoluteImports` option (and just pass it along to `babel-polyfills`.)

**Describe alternatives you've considered**.

Not sure, but I'm open to alternative solutions.

**Documentation, Adoption, Migration Strategy**

This option is already documented in `babel-polyfills`. It could be copied over to the `preset-env` documentation.

**Comment by nicolo-ribaudo** [comment]
`@babel/preset-env`'s polyfill support is only to provide the same interface present in older versions. If you need to use any of the new options, you can use the `babel-polyfills` packages directly.

**Comment by charlessuh** [comment]
Ah, okay -- the intention is one should use `babel-polyfills` directly instead of `@babel/preset-env` for more advanced usage.

I'd suggest documenting this on the Babel website that preset-env uses `babel-polyfills` under the hood and to explore this package for more configuration options -- but thanks for the clarification!
