### ISSUE TITLE
loadFullConfig wastes time on findConfigUpwards again when I've already done loadOptions with `rootMode: 'upward-optional'`

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#13006]
How do I actually load the config once and for all and prevent babel from doing any fs operations on subsequent `parseSync` calls?

In a tool of mine that parses stuff with `@babel/core`, the main bottleneck in the profiler is loading the babel config on every file.

I tried to fix this with by doing `babel.loadOptionsAsync({ filename, cwd, rootMode: 'upward-optional' })` but it still doesn't fix the problem:

![image](https://user-images.githubusercontent.com/1448194/111259321-aad82480-85ec-11eb-9bdb-5bf75e41c33a.png)

To my chagrin, I discovered that `parseSync` still does `findConfigUpwards` even if I pass it the fully-loaded config from `loadOptions`, because `loadOptions` returns an object with `rootMode: 'upward-optional'`, and you can see what happens here in the debugger:

![image](https://user-images.githubusercontent.com/1448194/111259448-e4109480-85ec-11eb-9250-286e5ce9225a.png)

This is a bug right?  My understanding was that there would be zero filesystem calls to load config if I pass options from `loadOptions` to `parse` etc.

**Comment by jedwards1211** [comment]
Even when I force `rootMode: 'root'` to prevent the `findConfigUpwards` it's doing `findPackageData` on every single `parseSync` call.  I could have so much better performance in my codemod if not for babel (and `jscodeshift` using the sync APIs...)

**Comment by nicolo-ribaudo** [comment]
I _think_ passing `configFile: false, babelrc: false` would disable most (if not any) FS operation. If you are using Babel ^7.13 you might also need to pass `browserslistConfigFile: false`.

**Comment by jedwards1211** [comment]
Yeah seeing that it sets those options, i was surprised that fs operations are still happening.

I wish there were an API to extract `@babel/parser` options from the config, because all I need to do in a bunch of codemod tools is parse the user's code successfully.

**Comment by nicolo-ribaudo** [comment]
It might not be 100% reliable, but this should work in most of the cases:

```js
const { plugins } = babel.loadOptionsSync({ filename, cwd });
const opts = { parserOpts: { plugins: [] }, generatorOpts: {} };
for (const { manipulateOptions } of plugins) {
  manipulateOptions?.(opts, opts.parserOpts);
}
```

**Comment by jedwards1211** [comment]
That basically worked, thanks!  I had to pass `sourceType` from the loaded options to the parser options as well.

If there were a 100% reliable way to get the parser options, it would be a great thing for the ecosystem, because `jscodeshift` currently uses reasonable default babel parser options, meaning it won't work on everyone's code.

**Comment by jedwards1211** [comment]
What I'm doing now in my own codemods is

```js
const parserCache: Map<
  string,
  { parse: (code: string) => ASTNode } | undefined
> = new Map()

async function chooseJSCodeshiftParser(
  file: string
): Promise<string | { parse: (code: string) => ASTNode } | undefined> {
  const tsMatch = /\.(tsx?)$/.exec(file)
  if (tsMatch) return tsMatch[1]

  const parentDir = Path.dirname(file)

  let result = parserCache.get(parentDir)
  if (result) return result
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const babel = require(await resolve('@babel/core', { basedir: parentDir }))
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const parser = require(await resolve('@babel/parser', {
      basedir: parentDir,
    }))

    const options = await babel.loadOptionsAsync({
      filename: file,
      cwd: process.cwd(),
    })
    const { plugins, sourceType } = options
    const opts = {
      parserOpts: { plugins: [], tokens: true, sourceType },
      generatorOpts: {},
    }
    for (const { manipulateOptions } of plugins) {
      manipulateOptions?.(opts, opts.parserOpts)
    }
    result = {
      parse: (code: string): ASTNode => {
        return parser.parse(code, opts.parserOpts)
      },
    }
  } catch (error) {
    result = undefined
  }

  parserCache.set(parentDir, result)
  return result
}
```

**Comment by jedwards1211** [comment]
@nicolo-ribaudo thanks!

As I mentioned earlier, it was still doing fs ops when I manually set `rootMode` to `root` on the loaded config - it still calls `findPackageData`, unless that's been fixed

**Comment by nicolo-ribaudo** [comment]
Yeah my PR was just a partial fix, I'll keep working on this to also avoid that function call :+1:
