### ISSUE TITLE
Bugfix transform needed for optional chain expressions with spread arguments

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#13001]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Re: https://stackoverflow.com/questions/66609657/optional-chaining-function-prototype-apply-was-called-on-undefined-which-is-a

There's a [bug](https://bugs.chromium.org/p/v8/issues/detail?id=11558) in Chrome when invoking a bare optional call (not a method on an object) when there is a spread arguments **and** a following argument:

**Input Code**
[REPL](https://babeljs.io/repl#?browsers=Chrome%20%3E%2080&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeGYCuAbDBuAUKSWRFdLPA6GEZGAbwF89cB6ZmAMQEswBTXBAPwA6ABRDxAbQC6ASjwhhUEAGUoAJ24BzMZKkAaGAEY5uBUKWqNYTcJ1DpB43jDCAtjygALEABNb4-30jExY2ABVPNRAAdwgYEVc0SgAjHhgAQzAATwy1TTR3MFgvdNg4ECwYuPSYAIgABzUedJ8ZfhdRAIdg7Bh2_10DLtl5IXcvXwHAxxNWGAjOOPA0xZhXEEoINDVGxa0AQlwO8e8fO26nXCA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.13.10&externalPlugins=) (Chome throws, Firefox/Safari are fine)

```js
const fn = null;
const n = null;
const o = {};

// Fine
fn?.(...[]);
o?.toString(...[], 1);
o?.toString?.(...[], 1);
n?.method?.(...[], 1);

// Throws (must be any argument that follows a ...spread)
fn?.(...[], 1); 
fn?.(...[], ...[]);
o.method?.(...[], 1);
// This one is most surprising!
n?.method(...[], 1);
```

**Expected behavior**

None of these should throw in Chrome

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "Chrome > 80",
        "bugfixes": true
      }
    ]
  ]
}
```

**Possible Solution**

We need to add a new bugfix transform that detects these `...foo` spread arguments inside an optional chain, and forces the transform.

**Additional context**

Edits by @JLHwung 
- Added link to v8 issue for reference.

**Comment by nicolo-ribaudo** [comment]
I saw the tweet about this earlier on twitter and completely forgot to open an issue. :grimacing: Thanks!

**Comment by nicolo-ribaudo** [comment]
The first step to fix this is to add it to `compat-table`.
