### ISSUE TITLE
@babel/standalone is broken after #12795

### ISSUE THREAD

**Issue by egoist** [babel/babel#13016]
## Bug Report

- [ ] I would like to work on a fix!

#12795 breaks the `@babel/standalone` rollup bundle because how `@rollup/plugin-commonjs` commonjs interop works: https://github.com/rollup/plugins/issues/635

**Current behavior**

https://github.com/babel/babel/blob/a9e43662b6c424456b73a951d7781fa837bd49f8/packages/babel-plugin-transform-runtime/src/index.js#L12

it's `undefined` here in the `@babel/standalone` rollup bundled 

**Environment**

- Babel version(s): 7.13.11
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

Affects https://github.com/vitejs/vite/issues/2442

**Comment by nicolo-ribaudo** [comment]
This can be easily reproduce with the REPL: https://babeljs.io/repl#?browsers=defaults&build=&builtIns=usage&spec=false&loose=false&code_lz=IxA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.13.11&externalPlugins=
