### ISSUE TITLE
@babel/generator not outputting the same code as went into the AST

### ISSUE THREAD

**Issue by Sawtaytoes** [babel/babel#13010]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```js
// okay!
[1, 2, 3].map(function() {
  return
})
['fun'
 + 'yo'
]
.filter(Boolean)

const blah = ({
  // middle comment
  first,
  second,
}) => {
  console.log('okay?');
}
```

**Output Code**

```js
// okay!
[1, 2, 3].map(function () {
  return;
})[
'fun' +
'yo'].

filter(Boolean);

const blah = ({
  // middle comment
  first,
  second }) =>
{
  console.log('okay?');
};
```

**Code to do the work**
```js
const {
  default: generate,
} = require('@babel/generator')
const {
  parse,
} = require('@babel/parser')
const fs = require('fs')

const codeInput = (
  fs
  .readFileSync(
    './testInput.js',
    'utf-8',
  )
)

const ast = (
  parse(
    codeInput,
    {
      createParenthesizedExpressions: true,
      ranges: true,
      tokens: true,
    }
  )
)

const {
  code: codeOutput,
} = (
  generate(
    ast,
    {
      retainFunctionParens: true,
      retainLines: true,
    },
    codeInput,
  )
)

fs
.writeFileSync(
  './testOutput.js',
  codeOutput,
)
```

**Expected behavior**

The file I input into the `@babel/parser` AST should come out exactly the same when run through `@babel/generator`.

Or am I misunderstanding how this is supposed to work?

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.13.10 => 7.13.10
    @babel/generator: ^7.13.9 => 7.13.9
    @babel/parser: ^7.13.11 => 7.13.11
    @babel/traverse: ^7.13.0 => 7.13.0
```

**Possible Solution**

Absolutely no clue.

**Additional context**

**Comment by jridgewell** [comment]
> The file I input into the @babel/parser AST should come out exactly the same when run through @babel/generator.

The file has to be syntatically equivalent (they compute to the same result), we make no guarantees on formatting. In this case, the input and output are syntatically equivalent.

**Comment by Sawtaytoes** [comment]
Thanks. Explains what I needed!
