### ISSUE TITLE
'undefined is not a function' with new JSX transform on development mode

### ISSUE THREAD

**Issue by romanlex** [babel/babel#13019]
## Bug Report

I'm use [jsx-control-statement@4.1.0](https://github.com/AlexGilleran/jsx-control-statements) plugin.
Production build is work properly but when I start development mode I have error `undefined is not a function`

![image](https://user-images.githubusercontent.com/3369304/111654069-79906c00-8819-11eb-855e-6aa094b053b6.png)

In the source code of my development build I see this

![image](https://user-images.githubusercontent.com/3369304/111654253-a3e22980-8819-11eb-88e6-d80818d4ecad.png)

**Expected behavior**
Development build work properly

```
- Babel version(s): v7.13.10
- Node/npm version: Node 13
- Monorepo: no
- How you are using Babel: webpack
```

**Additional context**

I found similar issue with [babel-plugin-inline-react-svg](https://github.com/airbnb/babel-plugin-inline-react-svg/issues/91)

**Comment by nicolo-ribaudo** [comment]
What is your React version? Do you have duplicated copies of React in your dependencies?

**Comment by romanlex** [comment]
React 17.0.1
Doesn't have duplicates

**Comment by JLHwung** [comment]
Can you share a reproducing repo?
