### ISSUE TITLE
Aliasing of imports - Minification

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#1303]
Given a file like this:
```
import {Component, PropTypes} from 'react';

export default class ResultsSubjects extends Component {
  render() {
    return <div>YOLO</div>;
  }
}

ResultsSubjects.propTypes = {
  first: PropTypes.string.isRequired,
  second: PropTypes.bool.isRequired,
  third: PropTypes.shape({
    lol: PropTypes.bool,
    wut: PropTypes.string,
  }),
}
```

Babel compiles the PropTypes into something like:
```
var _Component$PropTypes = require('react');
// ... other stuff ...
ResultsSubjects.propTypes = {
  first: _Component$PropTypes.PropTypes.string.isRequired,
  second: _Component$PropTypes.PropTypes.bool.isRequired,
  third: _Component$PropTypes.PropTypes.shape({
    lol: _Component$PropTypes.PropTypes.bool,
    wut: _Component$PropTypes.PropTypes.string }) };
```

Once minified, `_Component$PropTypes.PropTypes.string` becomes something like `r.PropTypes.string.isRequired`, resulting in the string "r.PropTypes" being repeated quite frequently in the resulting JS. It seems like this would minify better if PropTypes was pulled into a variable, something like:
```
var _Component$PropTypes = require('react');
var _PropTypes = _Component$PropTypes.PropTypes;
...
ResultsSubjects.propTypes = {
  first: _PropTypes.string.isRequired,
...
```

Which would minify to something like "a.string.isRequired" and remove the repeated "PropTypes".

On the other hand, repeated strings gzip very well, so maybe it wouldn't actually have much effect.

Thoughts?

**Comment by sebmck** [comment]
This was basically the behaviour for 4.x. In 5.x the behaviour was changed to support live bindings through the use of remapping the variables to always reference the `exports` object of the imported module. Diverting from that would break ES6 modules expectations.
