### ISSUE TITLE
Using babel-node + @babel/preset-flow fails when using ES Modules 

### ISSUE THREAD

**Issue by callumgare** [babel/babel#13036]
If babel-node is run on a project with flow type anatations and @babel/preset-flow to strip those anationats then it will fails IF package.json contains `"type": "module"`. If  `"type": "module"` is removed then it will work fine. This occurs with the latest versions of @babel/core (7.13.10), @babel/node (7.13.10) and @babel/preset-flow (7.12.13). I've thrown together an example repo for reproduction: https://github.com/callumgare/example-flow-babel-node-es-modules-fail

When running `babel-node index.js` in the above repo with node 14 under ubuntu I get:
```
file:///home/callumgare/repos/babel-node-test/index.js:2
function main(val: string) {
                 ^

SyntaxError: Unexpected token ':'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:141:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by nicolo-ribaudo** [comment]
You can use the package linked at https://github.com/babel/babel/issues/11934#issuecomment-706799520; I'm closing this since we are already tracking an official implementation in that issue!

**Comment by callumgare** [comment]
> You can use the package linked at [#11934 (comment)]

Great! Thanks for pointing me in the direction of that :)
