### ISSUE TITLE
@babel/runtime 7.13.10 breaking on JSPM

### ISSUE THREAD

**Issue by guybedford** [babel/babel#13059]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), https://jspm.org/sandbox#H4sIAAAAAAAAA7WabVPbOBDH3/dTqLk3vTtsE1r6QEMnNOU6cEA5Hsr03in2JlaxLSPJPN3cd7+V5aSJsURU5mZaIPZ/f7uSVytZyuB5wmN1VwJJVZ59eDaY/QKafHhGyCAHRUmcUiFBbfcqNQne9uobiqkMPpwAjRU5VVQoEIPIXJzbFTSH7d41g5uSC9UjMS8UFMi5YYlKtxO4ZjEE9Yc1wgqmGM0CGdMMtvvoZRCZMAZjntzV1OdBQHZPySFPqgzIacpyuUX2ck0nOS0lKXl2N2FZRiZckLyWSTIW/EaCkOSGqZRXirAFC1mV9YcXFK3gNoZSkVEqeA7k7bvffyVBUHuWsWB4h8q7IiZSxNu9VKlSbkXRlIbfZZmHjEdFmW+BDIzfQOrwhuthH/9FCZMqat0Lc1agbe/DIDJ47alpJv4iZP/0+JB8hgIEVdiepqGHtKzv7iZMkfOTgy0yD2UmnUf0y/nG1+m3zx8vP+2WR2ejzZPRaHP/YFTuH1zs8TPZP7ofXe+fHX1T98lfakdevvr85fLv1yjfOczg9fGl2NlBX8t9oNNlu2f6ELuwTod/6oiai7K31VzASxJyWigWBxULhM4WvGnruwfa4Ua4Hr40nRfzPOfFdxmxIoFb3W+1i3/XjGsZ8xKWPHc4WbiNguGYjiGLRIU+c8Bky0rMkohKTBZ1ljK5Z1KS3UPiiHoZM3wT9l/iM3fjdPhrj0YSYycoGGWI+Hn/C5DVvMItDtLkCR4bwGreWJGCYEoecC7h530uYVb1jDWLlydwVTEBn2BCq8yVnY9G0IH7mUguWJbEVDwh5bp5q8XCx98hVhemUh4jBZOXwVMfj4u6Wly66vDJE5JS5g2j7W+SVTgpVSyqS06AdabkBV4J4Fr/zLD46Lrqcr0iAieDzX74plXPcBoM5zVtpcAEODvCZecZQslL7D1UxFw4H/+SEMv2u9mcFzd4I2jzH1T8yPSYVDS+dPlzGg7xyYcbUcbG1pbFmbx18PXtYR8ps1bg5xYBbqG4diDq+8jYwEi6IriEuzHHYRngHw7MoqyOaD3C5Uc0u/wn3LW4GU+oTDFimpcOrpENX4X9N+FG38gtJMwf97zdZhmDbloC40q4BlMLZvQWFptMQEARu1KzzZvbWJi6cLJp6tHeuUk3EbMzXR2m1RYOroxLOIHp7q3Hg120snCvQbgysA3U8m4SrryVs1C2UEZvYxWuGfABqWjPbwucPT38/GB7HSN2ThTSIztquYXExa5XcjQG3bQpeESF4m5KSl0rvxYFxd0UVpzQYuoxLBsDGy3OqgQ8AptZ2HiYdhIXJIwXPswfVjYujg2Ph2D0Vha/9OpArbew5I4Q1GOMNwY22kfOM6A+XTczsRF381J5xVcbWGlXFc28aNrARvujKnwzZW5jYx4xr/hQbiVV+din5s4sbLwv9Urdh2csbLzjjLLCH7pgZiOfKsGKqQ/UWNh451jysfQ73/UfIOdG3VRcpn30yOtabiV51D+t7uboHZuVMSi2Ur5SfM3wCGluYiFCztm9R8FrDCw05jFcm224h5SCc4/O0upuTkmF3vjxXFYuWlm4zPmS1Oah2s7xSVOj72YJv3lf2Gd9AUnls7I3eguLVz7LyVreTZI+qyxpW2VJr1SX1jyXPPfhoNrGEconA4zewtKnASPq3C5q42YmDqLUu0eeyNrGwqxyD1iVd1MU9VmjabWFw3KfWlrLLSQcURLfEzxaNzexEZkXjFk4VeG1iKrlVtKVF+iqm3PtOYVdO+av5mxpdVhj0KKZjdKASsmmrs5a0mlm2O/cZSoFLwO97+lq5g/RsL8ZYnTWbbPHTnDMqQ02cP0xSJBwV1bNNavBJlSajU7q3KZ8KB6+DDfC9c6uM2Lm6riZZLUgzRboozgjG25gYJv1Hma8eOi1QJVxCvo00YWca4YYnyvEuVCXg9i9sO6ENmZtbEqzjN/AI29ki7Jml7MryBsqCndojQJHRH1wiHE1V8LZgeH8yLD7iHDlHfTls0SvZHldn00sP4pVY3s4Vv+nQJ7Nfur/7RPqpaNgc6ZdnwOT2dn6b4RKMtukP2fmewITwfOuE+H3hkpIFJELwRSQHN/+mvN7EvMESAoC1ggXGksRjGOXom7CUKArKV7sSRH3CFU4A40rvMcLolKYUUzEYe0m5oXkGYQZn75oxfjr+6XWDiLz3YNBZL4Y8R9etTaaMCEAAA==

**Input Code**

Loading `@babel/runtime@7.13.10/helpers/interopRequireWildcard.js` includes a `require` to `@babel/runtime/helpers/typeof` which is mapped to resolve to `@babel/runtime@7.13.10/helpers/esm/typeof.js` in all environments that aren't Node.js environments by the exports definitions.

This file then also uses the import pattern:

```js
var _typeof = require("@babel/runtime/helpers/typeof")["default"];
```

Where accessing the `default` off of the `helpers/esm/typeof.js` file makes `_typeof` undefined.

**Expected behavior**

`"require"` should not remap to an ESM module, or if it does the interop should take into account the varying signature of the exports.

**Possible Solution**

I'm not sure what would be best actually. Ideally using relative paths in the first place would avoid this. Alternatively using the `"require"` condition instead of the `"node"` condition. If it is really desired to replace the CJS require statements with ES modules then the Webpack / build-tool-specific `"module"` condition could be used.

**Comment by nicolo-ribaudo** [comment]
Context (in chronological order): #12632, #12865, #12877, #12893

In #12893 I removed the `require` condition because I wrongly assumed that it would have been unnecessary since we specify `node` and `default`.

> includes a `require` to `@babel/runtime/helpers/typeof` which is mapped to resolve to `@babel/runtime@7.13.10/helpers/esm/typeof.js` in all environments that aren't Node.js environments by the exports definitions.

I don't understand how this remapping happens. This is the `exports` map:
```json
    "./helpers/typeof": [
      {
        "node": "./helpers/typeof.js",
        "import": "./helpers/esm/typeof.js",
        "default": "./helpers/typeof.js"
      },
      "./helpers/typeof.js"
    ],
```

I might be reading it wrong, but I would expect a non-Node.js environment using `require` to interpret it as such:
- `node` is ignored, because the environment is not Node.js
- `import` is ignored, because the helper is being `require()`ed
- `default` matches

However, `default` points to [a CJS file](https://github.com/babel/babel/blob/main/packages/babel-runtime/helpers/typeof.js), so I would expect it to work :thinking:

**Comment by guybedford** [comment]
Thanks for the quick response here @nicolo-ribaudo, you're right this looks like a bug if it is incorrectly matching the `"import"` condition. Let me see if I can fix that up and reopen if I'm still seeing any issues.
