### ISSUE TITLE
`typeof Symbol() === 'symbol'` fails in non-native-symbol browsers

### ISSUE THREAD

**Issue by ljharb** [babel/babel#1305]
See http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=console.log(typeof%20Symbol()%3D%3D%3D'symbol')

In Firefox/Chrome, which do have native Symbols, this returns `true`, naturally. In Safari, which does not have native Symbols, it returns `false`.

If babel is going to attempt to polyfill Symbols, then I think, in any browser without native Symbols, it needs to transpile *every* `typeof` operator usage that could possibly be applied to a symbol value (ie, everything, but not necessary when it's typeof of a literal value, or a value that babel knows for certain is a non-symbol type)

**Comment by sebmck** [comment]
[es6.spec.symbols](http://babeljs.io/docs/usage/transformers/es6/spec-symbols/) :)

**Comment by ljharb** [comment]
@sebmck Great! Then why does the repl on the website not do exactly that?

**Comment by ljharb** [comment]
In other words, imo this can *not* be an optional transform. If you're going to use Symbols, this **will** cause a bug in your code unless you use this. Thus, using `Symbol` imo should automatically opt you in to that transform.

**Comment by sebmck** [comment]
What about files that don't explicitly use Symbol but still receive them?

On Monday, 20 April 2015, Jordan Harband <notifications@github.com> wrote:

> In other words, imo this can *not* be an optional transform. If you're
> going to use Symbols, this *will* cause a bug in your code unless you use
> this. Thus, using Symbol imo should automatically opt you in to that
> transform.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1305#issuecomment-94346200>.
>


-- 
Sebastian McKenzie

**Comment by ljharb** [comment]
@sebmck Yes, that's why babel must, by default, transpile *every single typeof reference* unless it can be certain that it's not receiving a symbol. Otherwise, there will be bugs.

The only other alternative I see is not to attempt to shim Symbols at all, which I assume isn't an option.

**Comment by sebmck** [comment]
@ljharb It's fine, really. This may be a priority for you but it's not for 99.whatever% of other users. This is also the stance taken by Traceur (optional and off by default). `typeof` appears regularly in hot code and the performance penalty associated with doing this for **every** `typeof` is significant. As you likely already know, you **cannot** accurately shim symbols. The type coercion semantics are impossible to implement for various reasons (you need to wrap every single `BinaryExpression` and more which is insane).

On a partially related note, `es6-shim`s stance on symbols is literally one of the only reasons I switched to `core-js` (there are additional features such as the library mode which are also especially handy).

**Comment by ljharb** [comment]
That's sad to hear - this is a caveat that will definitely cause babel users bugs when they write frontend code, and `typeof` is a pretty big thing to not have work correctly for a long list of browsers (all the ones that don't natively support Symbols, that most users will in fact have to continue to support for years).

If there's a way to use Babel while completely disabling Symbol support, then I'd love to be able to continue to recommend Babel as a viable option.

**Comment by sebmck** [comment]
I'm unsure what you mean by disabling symbol support?

**Comment by ljharb** [comment]
I'd want an option which which removes any Symbol shams/prollyfills, and ideally warns on any usage of `Symbol`.

**Comment by ljharb** [comment]
(I'd love to discuss this on IRC, if you're on freenode, I think this issue is coming off more adversarial than necessary)

**Comment by sebmck** [comment]
You can use whatever polyfill with Babel and you can accomplish the erroring on `Symbol` usage with a [plugin](http://babeljs.io/docs/usage/plugins/):

```javascript
var Transformer = require("babel-core").Transformer;

module.exports = new Transformer("no-symbos", {
  Identifier: function () {
    if (this.isReferenced({ name: "Symbol })) throw this.errorWithNode("your message here");
  }
});
```

**Comment by sebmck** [comment]
> (I'd love to discuss this on IRC, if you're on freenode, I think this issue is coming off more adversarial than necessary)

Sure, I'm on freenode as sebmck :)
