### ISSUE TITLE
Support Flow's indexed access type

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#13052]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

Current babel-parser cannot parse Flow's indexed access types with Syntax Error `Unexpected token, expected "]" (1:15)
`

- [REPL](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=C4TwDgpgBAYg9nKBeKAhAhgJwNoHIBmCuAugNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=flow&prettier=false&targets=&version=7.13.12&externalPlugins=).

**Input Code**

```js
type Foo = Bar['foo'];
```

**Expected behavior**

Returns the AST like below:

```ts
interface IndexedAccessType {
  objectType: Type;
  indexType: LiteralType;
}
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Use parser directly.

**Environment**

- Babel version(s): current `main`

**Possible Solution**

**Additional context**

I could not find the feature from [changelog on Flow repo](https://github.com/facebook/flow/blob/master/Changelog.md) but it seems to be supported by current Flow. See prettier/prettier#10594.

**Comment by mischnic** [comment]
I think this issue can be closed?
