### ISSUE TITLE
@babel/plugin-transform-react-constant-elements@7.13.10 broken

### ISSUE THREAD

**Issue by cgood92** [babel/babel#13051]
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**
@babel/babel-plugin-transform-react-constant-elements@7.13.10 does not handle `let` variables that change correctly.

- [REPL](https://babeljs.io/repl#?browsers=ie%2011%0A&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFEIEBnKRMOAE31sQF5EBtAXUsQDgcAE6JCBBjE6IADAG5E0gDyIAjAqUBqLcUQUqVJq1oA6bCFoALQsuYwAbogDW-AJ4dSMAL7UrMXGYRfDBPHwA-ZQB6ewdw4gFvAQFgqBARJGM2eXJvIA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0%2C%40babel%2Fplugin-transform-react-constant-elements%407.13.10), [Codesandbox](https://codesandbox.io/s/wizardly-bush-ouhhz?file=/src/App.js)

**Input Code**

```js
function Example(){
  const nodes = []
  
  for (let i = 0; i < 10; i++) {
    nodes.push(<div key={i} children={i}></div>)
  }
  
  return nodes;
}
```

**Expected behavior**
In this case, this JSX should not be seen as constant

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
      "presets": ["react"],
      "plugins": [
        ["@babel/plugin-transform-react-constant-elements"],
      ])
}
```

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  npmPackages:
    @babel/core: 7.13.10 => 7.13.10 
    @babel/plugin-transform-react-constant-elements: 7.13.10 => 7.13.10
    @babel/plugin-transform-react-inline-elements: 7.12.13 => 7.12.13 
    @babel/plugin-transform-runtime: 7.13.10 => 7.13.10 
    @babel/preset-env: 7.13.12 => 7.13.12 
    @babel/preset-react: 7.12.13 => 7.12.13 
    @babel/runtime: ^7.13.10 => 7.13.10 
    babel-eslint: 10.1.0 => 10.1.0 
    babel-loader: 8.2.2 => 8.2.2 
    babel-plugin-emotion: 9.2.11 => 9.2.11 
    babel-plugin-transform-imports: 2.0.0 => 2.0.0 
    babel-plugin-transform-react-remove-prop-types: 0.4.24 => 0.4.24 
    eslint: 7.22.0 => 7.22.0 
    jest: 26.6.3 => 26.6.3 
    webpack: 5.27.2 => 5.27.2 
```

- How you are using Babel: webpack

**Additional context**
This is the commit that broke things: https://github.com/babel/babel/commit/8dacf85859fca38c962a7d36585d3ad6bae2b45a.  V7.12.13 works fine.

**Comment by jridgewell** [comment]
This is an interaction with `block-scoping` and `react-constant-elements`: [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFEIEBnKRMOAE31sQF5EBtAXUsQDgcAE6JCBBjE6IADAG5E0gDyIAjAqUBqLcUQUqVJq1oA6bCFoALQsuYwAbogDW-AJ4dSMAL7UrMXGYRfDBPHwA-ZQB6ewdw4gFvAQFgqBARJGM2eXJvIA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.13.10%2C%40babel%2Fplugin-transform-block-scoping%407.12.13)

**Comment by jridgewell** [comment]
Wow, we overlooked a really simple case:

```js
function Example(){
  const nodes = []
  
  for (var i = 0; i < 10; i++) {
    nodes.push(<div key={i} children={i}></div>)
  }
  
  return nodes;
}


function Example2(){
  const nodes = []
  let i = 0;
  for (; i < 10; i++) {
    nodes.push(<div key={i} children={i}></div>)
  }
  
  return nodes;
}
```

Neither of these should be constant.

@cgood92: You've marked that you'd like to fix this. It's actually really simple: When we find an `Identifier` in the JSX node, we should only consider it a constant element if the identifier is constant. Currently, we just ignore any `Identifier`: https://github.com/babel/babel/blob/2ae19d01b132f5222e1d5bee2c83921e2f107d70/packages/babel-plugin-transform-react-constant-elements/src/index.js#L67

```js
if (path.isIdentifier()) {
  const binding = path.scope.getBinding(path.node.name);
  if (binding.constant) return;
}
```

**Comment by cgood92** [comment]
Thank you very much for your suggestion @jridgewell.  I have attempted my first PR here: https://github.com/babel/babel/pull/13054.  Can you please give feedback if this is not what you intended?

Thanks again.
