### ISSUE TITLE
@babel/traverse   Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by dealdot** [babel/babel#13061]
## @babel/traverse

browser:  chrome
os:  windows10

"devDependencies": {
    "@babel/parser": "^7.13.13",
    "@babel/traverse": "^7.13.13",
    "html-webpack-plugin": "^5.3.1",
    "webpack": "^5.28.0",
    "webpack-cli": "^4.5.0"
  },
  "dependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^8.2.2",
    "babel-preset-env": "^1.7.0"
  }

```
import * as parser from "@babel/parser";
import traverse from "@babel/traverse";

const code = `let sum = 10 + 66;`;
const ast = parser.parse(code);
console.log(ast);

traverse(ast, {
    enter(path) {
        console.log(path.node.type)
    }
});

```

```
Uncaught ReferenceError: process is not defined
    at eval (core.js:28)
    at Object../node_modules/@babel/types/lib/definitions/core.js (main.js:2)
    at __webpack_require__ (main.js:2)
    at eval (index.js:68)
    at Object../node_modules/@babel/types/lib/definitions/index.js (main.js:2)
    at __webpack_require__ (main.js:2)
    at eval (builder.js:8)
    at Object../node_modules/@babel/types/lib/builders/builder.js (main.js:2)
    at __webpack_require__ (main.js:2)
    at eval (index.js:254)
```

**Comment by nicolo-ribaudo** [comment]
If you are bundling Babel, you must make sure to provide a node-like environment.

With Webpack 5 you might be able to "shim" `process.env` using `DefinePlugin`.

**Comment by IamFonky** [comment]
Maybe this is what you need

``` javascript
const webpack = require('webpack')

module.exports = {
...
plugins: [
  new webpack.ProvidePlugin({
    Buffer: ['buffer', 'Buffer'],
  }),
  new webpack.ProvidePlugin({
    process: 'process/browser',
  }),
    ],
```

I found that [here](https://stackoverflow.com/questions/41359504/webpack-bundle-js-uncaught-referenceerror-process-is-not-defined)
