### ISSUE TITLE
[docs] Regex needed for 'only' option, not array of globs

### ISSUE THREAD

**Issue by IanVS** [babel/babel#1306]
The [options docs](https://babeljs.io/docs/usage/options/) currently state that the `only` option takes an array of globs:

> An array of glob paths to **only** compile. When attempting to compile a non-matching file it's returned verbatim.

But it seems to instead accept a regex, as indicated in https://babeljs.io/docs/usage/require/:

>  // Optional only regex - if any filenames **don't** match this regex then they
  // aren't compiled
  only: /my_es6_folder/,

It sure would be nice if the option accepted globs, but so far all I can get to work are regular expressions.

**Comment by sebmck** [comment]
It can take an array of globs, a single regex, a single string glob or an array of regexs.

**Comment by sebmck** [comment]
Also please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by IanVS** [comment]
Ah, missed that link, thanks.
