### ISSUE TITLE
transforming "typeof" to "_typeof" causes an error in Javascript in many webpages

### ISSUE THREAD

**Issue by gogo9th** [babel/babel#13062]
## Feature Request

**Is your feature request related to a problem?**
Babel transforms "typeof" to "_typeof". However, some Javascript such as the one in nationalgeographic.com defines the _typeof function, which causes an error due to the conflicting name.  

**Describe the solution you'd like**
The transformed keyword should be more complex than this to avoid conflicts, for example," __babel__typeof." I wonder which files I should modify in order to apply this change.

**Comment by nicolo-ribaudo** [comment]
The only `_typeof` function I can find on https://www.nationalgeographic.com/ is the one defined by Babel, so even renaming it wouldn't avoid the conflict.

However, I don't understand why it causes a problem: are you re-transforming the web pages you visit with Babel?

**Comment by fengxinming** [comment]
I had a same problem about `_typeof`
