### ISSUE TITLE
TypeScript: unparenthesized `as` in assignment LHS

### ISSUE THREAD

**Issue by thorn0** [babel/babel#13070]
## Bug Report

**Current behavior**

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBARhC8EHIEBoIA84QN4QIYC4IBmCAXwG4AoSgCiwOjwGc8A7AT0wCYAGP0zGgCUVGLha4Og8kA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.13.13&externalPlugins=), [TypeScript Playground](https://www.typescriptlang.org/play?#code/DYUwLgBARhC8EHIEG4BQpIA84QN4QEMAuCAZggF81UAKXY6QgZ0IDsBPHAJgAY+KcmAJTIgA)

**Input Code**

```js
({a: b as any = 2000} = x);
b as any = x;
```

**Expected behavior**
Syntax error

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

```js
{ plugins: ["typescript"] }
```

**Environment**

- Babel version(s): v7.13.10, v7.13.13

**Additional context**

If the `as`-expressions had parentheses around them, it'd be valid TypeScript syntax.

**Comment by fedeci** [comment]
If @thorn0 doesn't intend to work on this I can do it.
