### ISSUE TITLE
node v13 is not supported?

### ISSUE THREAD

**Issue by aprilmintacpineda** [babel/babel#13083]
## Bug Report

- [x] I would like to work on a fix!

I'm running on a CI/CD tool, while doing `yarn`, I got this error:

```
error @babel/eslint-parser@7.13.10: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || >=14.0.0". Got "13.12.0"
```

Looking at https://github.com/babel/babel/blob/main/eslint/babel-eslint-parser/package.json#L20, it does show that node v13 is not supported, any particular reason for this?

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Node.js 13 isn't maintained anymore (https://github.com/nodejs/Release#release-schedule), and it's common practice in the JS tools ecosystem to only support maintained Node.js versions.

When we released `@babel/eslint-parser` for the first time Node.js 13 was already unmaintained, so we didn't add support for it.

**Comment by aprilmintacpineda** [comment]
> Node.js 13 isn't maintained anymore (https://github.com/nodejs/Release#release-schedule), and it's common practice in the JS tools ecosystem to only support maintained Node.js versions.
> 
> When we released `@babel/eslint-parser` for the first time Node.js 13 was already unmaintained, so we didn't add support for it.
> 
> It might work, but you need to pass yarn the `--ignore-engines` option.

Makes sense... I guess this VM that I'm running on is also unmaintained now... Thanks for the kind reply
