### ISSUE TITLE
babel-core api treats an empty whitelist array as don't apply any transforms

### ISSUE THREAD

**Issue by gandm** [babel/babel#1308]
Using the babel-core API if I use ```whitelist: []``` as options babel does not apply any transforms. Seems to treat an empty array as whitelist nothing - blacklist everything. Not what I was expecting. Can this be changed?

code that handles this seems to be in transformer-pass.js at line 40
```
    // whitelist
    var whitelist = opts.whitelist;
    if (whitelist) return includes(whitelist, key);
```

**Comment by sebmck** [comment]
[Can't satisfy everyone :disappointed:](https://github.com/babel/babel/issues/1044).
