### ISSUE TITLE
@babel/helper-module-transforms rewrites type annotations containing named imports incorrectly

### ISSUE THREAD

**Issue by jaked** [babel/babel#13094]
## Bug Report

**Current behavior**

Type annotations containing named imports are incorrectly transformed to `MemberExpressions` and cause a validation error: `Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"`. See [Babel repl](https://babel.dev/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgMQhOBfOAzKERwDkAdAPTZqEBQV2ArgHYDGMwEDcARgIZQAUFCAC4UaAJSJMVIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.13.14&externalPlugins=%40babel%2Fplugin-syntax-typescript%407.12.13%2C%40babel%2Fplugin-transform-modules-commonjs%407.13.8).

This seems to be due to [this line in `helper-module-transforms`](https://github.com/babel/babel/blob/main/packages/babel-helper-module-transforms/src/rewrite-live-references.ts#L239), which rewrites any `ReferencedIdentifier` to a `MemberExpression`; but type annotations may contain `Identifiers` and be matched by `ReferencedIdentifier`.

**Input Code**

```js
import { Foo } from './foo'

function bar(foo: Foo) { }
```

**Expected behavior**

Type annotations are transformed correctly, or (if this module is not intended to be used with type annotations) flagged with a clear error.

**Comment by Codex-** [comment]
Weird that it generates: `var _foo = require("./foo");` when importing a type/alias from TS when going to commonjs
