### ISSUE TITLE
an async traversal visitor, which your current version of Babel does not support

### ISSUE THREAD

**Issue by jackluson** [babel/babel#13095]
![image](https://user-images.githubusercontent.com/36684351/113474358-27e71300-94a2-11eb-8dbe-25fdb28aa471.png)
my babel version is 7.13.14 (@babel/core 7.13.14)

> The following is part of the code:

```javascript
const visitor: Visitor = {
    async TaggedTemplateExpression(path: NodePath<TaggedTemplateExpression>) {
      if (isStyledTagged(path.node)) {
        await transform(path.node.quasi);
      }
    },
    async CallExpression(path: NodePath<CallExpression>) {
      if (
        isMemberExpression(path.node.callee) &&
        isIdentifier(path.node.callee.object) &&
        isStyled(path.node.callee.object)
      ) {
        if (path.node.arguments.length >= 1 && isArrowFunctionExpression(path.node.arguments[0])) {
          const arrowFn = path.node.arguments[0] as ArrowFunctionExpression;
          if (isTemplateLiteral(arrowFn.body)) {
            await transform(arrowFn.body);
          }
        }
      }
    },
  };
```

**Comment by nicolo-ribaudo** [comment]
Babel does not support async visitors. We added that error message just in case we'll figure out how to implement them, but so far it seems impossible to do so without either damaging the performance a lot or causing a ton of race conditions.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since we added that error for clarity but supporting async visitors is currently out of scope.
