### ISSUE TITLE
TypeScript: trailing commas after rest parameters in ambient contexts

### ISSUE THREAD

**Issue by thorn0** [babel/babel#13100]
## Bug Report

**Current behavior**

Currently, Babel throws an unrecoverable syntax error whenever it finds a trailing comma after a rest parameter, however TypeScript allows such commas in ambient contexts (in declarations marked with `declare` or in `.d.ts` files).

- [Babel REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoA6M2AcwGcAueKVATwG0BdAGgEo6HGBuAFADQkWAlFUq8AEKx4AbwHxlBYmRKVa9Jmy48mAgL5CR0OPCyoMIGIihgEsgF4KlKxIVLkY1fSw7c2oxGJuBmCBiMAA4IAIrwALzwXho-Wry6nIkAfEFAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.13.14&externalPlugins=), [TS Playground](https://www.typescriptlang.org/play?ts=4.2.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoA6M2AcwGcAueKVATwG0BdAGgEo6HGBuALAAoYaEiwE4qlXgAhWPADew+KoLEyJSrXpM2XHk2EBfYaPDQ48LKgwgYiKGATyAXkpVrEhUuRjVDFg5uXUYTMyExSwQMRgAHBABFeABeeF8tfx1efU5UgD5QoA)

**Input Code**

```ts
// in a .ts file
declare function foo(...args: any[],): any;

declare class Bar {
    foo(...args: any[],): any
}

declare interface Baz {
    foo(...args: any[],): any
}

declare type Q = (...args: any[],) => any

// in a .d.ts file
function foo(...args: any[],): any;

class Bar {
    foo(...args: any[],): any
}

interface Baz {
    foo(...args: any[],): any
}

type Q = (...args: any[],) => any
```

**Expected behavior**

No error

**Environment**

- Babel version(s): v7.13.14

**Comment by nicolo-ribaudo** [comment]
The error definitely shouldn't be unrecoverable, but I'll ask to the TS team if allowing those trailing commas is intentional.

**Comment by thorn0** [comment]
It's intentional, see https://github.com/microsoft/TypeScript/issues/23070
