### ISSUE TITLE
it shouldn't turn ** in to Math.pow for BigInt

### ISSUE THREAD

**Issue by himanshuchawla009** [babel/babel#13109]
### Describe the bug
-  (**) operator is converted to Math.pow  and Math.pow doesn;t supports bigint which causes error while serving build files.

### Steps to reproduce

- Do a exponent operations BigInt(2) ** BigInt(10), it will work fine with npm start
- After npm build, build file converts ** to Math.pow (https://babeljs.io/docs/en/babel-plugin-transform-exponentiation-operator) which doesn't supports BigInt.

### Expected behavior
- Exponent operator ** should not be converted to math.pow for bigint.

**Comment by nicolo-ribaudo** [comment]
BigInts are only supported in browsers that also support `**` and they are not compiled by Babel, so if your app/library uses native BigInts you can disable the `transform-exponentiation-operator` plugin.

**Comment by himanshuchawla009** [comment]
Thanks @nicolas-marien , can you tell me a way to remove  `transform-exponentiation-operator` this plugin from create react app without ejecting.

**Comment by fedeci** [comment]
@himanshuchawla009 There is no official way to edit Babel config in `cra`, but you may be able to do it using some third party tools like `react-app-rewired` and `customize-cra`.

**Comment by yume-chan** [comment]
`create-react-app` uses `@babel/preset-env` so I believe modifying the `browserslist` setting in `package.json` to versions that native support BigInt and `**` should be enough.

https://github.com/babel/babel/blob/fb908fd87e1bf8a5ebe2c881c0baab1488c917e7/packages/babel-compat-data/data/plugins.json#L153-L163

**Comment by nicolo-ribaudo** [comment]
Closing as the solution is https://github.com/babel/babel/issues/13109#issuecomment-826287089
