### ISSUE TITLE
A method doesn't have a getter.

### ISSUE THREAD

**Issue by filimo** [babel/babel#1310]
I've taken below code from decorations sample.

```javascript
function autobind(target, key, descriptor) {
  var fn = descriptor.value;
  delete descriptor.value;
  delete descriptor.writable;
  descriptor.get = function () {
    return this[key] = fn.bind(this);
  };
}

class Person {
  firstName = "Sebastian";
  lastName = "McKenzie";

  @autobind
  getFullName() {
    return `${this.first} ${this.last}`;
  }
}

console.log(new Person().getFullName.call(null), "Sebastian McKenzie")
```

output:
Cannot set property getFullName of [object Object] which has only a getter

**Comment by fkling** [comment]
FYI, you can format your post so that the code is easier to read (https://guides.github.com/features/mastering-markdown/).

**Comment by loganfsmyth** [comment]
@filimo That `autobind` function isn't correct. It converts your `getFullName` method into a getter property that returns a function, which is fine, but you cannot `this[key] = ...` because your didn't specify a `descriptor.set = function(val){}` anywhere. Hence the error. You'd be better off storing the value on `this` with a different key. Most implementations I've seen use a Symbol  to ensure that the function is stored uniquely.

**Comment by filimo** [comment]
I try to rewrite `autobind` function like 

```javascript
function attr1(target, key, descriptor) {
  var fn = descriptor.value

  descriptor.value = function(...args) {
    console.log(this, 1)
    return fn.apply(this, args)
  }
}

class Test {
  constructor(prop1) {
      this.prop1 = prop1
    console.log(this, prop1)
  }


  @attr1
  test(p1, p2) {
    console.log(this)
    return `${this.prop1} ${p1} ${p2}`;
  }
}

var fn = new Test('value2').test
fn(33, 44)
````

and catch an error: Cannot read property 'prop1' of undefined

**Comment by filimo** [comment]
**@loganfsmyth** Thanks, I got it but I want to write a decorator to bind my methods to an instance.

**Comment by loganfsmyth** [comment]
@filimo 
From the Babel README:

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) or StackOverflow. The Babel issue tracker is exclusively for bug reports and feature requests.

I'll respond, but if you have any more to ask, please ask on the Gitter channel.

Your code now doesn't bind at all. I'd do something along the lines of:

```
function autobind(target, key, descriptor) {
  var fnKey = Symbol('@autobind ' + key.toString());
  var fn = descriptor.value;
  delete descriptor.value;
  delete descriptor.writable;
  descriptor.get = function () {
    if (!this[fnKey]) this[fnKey] = fn.bind(this);
    return this[fnKey];
  };
}
```

**Comment by sebmck** [comment]
As @loganfsmyth, please see the gitter room or StackOverflow for questions and support.

A working code example would be:

```javascript
function autobind(target, key, descriptor) {
  var fn = descriptor.value;
  delete descriptor.value;
  delete descriptor.writable;
  descriptor.get = function () {
    var val = fn.bind(this);
    Object.defineProperty(this, key, { value: val });
    return val;
  };
}

class Person {
  firstName = "Sebastian";
  lastName = "McKenzie";

  @autobind
  getFullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

console.log(new Person().getFullName.call(null), "Sebastian McKenzie")
```

However, I'd highly discourage the use of this pattern as it's terrible for performance and the semantics seem awkward.

**Comment by filimo** [comment]
I am confuse with  `this` is `undefined`

````javascript
function autobind(target, key, descriptor) {
  var fn = descriptor.value;
  delete descriptor.value;
  descriptor.value = function (...args) {
      console.log(this, args)
      return fn.bind(this)
  };
}

class Person {
  firstName = "Sebastian";
  lastName = "McKenzie";

  @autobind
  test() {
    return `${this.firstName} ${this.lastName}`;
  }
}

var fn = new Person().test
console.log(fn(1, 2))
````

Otherwise if I use getter `this` is `Person`
````javascript
function autobind(target, key, descriptor) {
  var fn = descriptor.value;
  delete descriptor.value;
  delete descriptor.writable;
  descriptor.get = function (...args) {
      console.log(this)
      return fn.bind(this)
  };
}

class Person {
  firstName = "Sebastian";
  lastName = "McKenzie";

  @autobind
  test() {
    return `${this.firstName} ${this.lastName}`;
  }
}

var fn = new Person().test
console.log(fn(1, 2))
````

**Comment by sebmck** [comment]
That's the way JavaScript works. Calling a function without a member expression evaluates it without a context.

**Comment by filimo** [comment]
I see but the first sample I call method with a context. Obviously an user will expect to have the same result.

**Comment by fkling** [comment]
A "value" property is simply not the same as a "getter" property. In the first case, with `value`, `new Person().test` literally returns the function

```js
function (...args) {
      console.log(this, args)
      return fn.bind(this)
  };
}
```

you are calling that function "normally", i.e. `this` will be `undefined`.

With the getter, the result of `new Person().test` is `fn.bind(this)`, i.e. the function you assigned to `get` is **executed**, with the right `this` value, and its return value, (`fn.bind(this)`) is assigned to `fn`.

Simpler example:

```
function foo() {
    return 'bar';
}

var obj = {};
Object.defineProperties(obj, {
  foo: {value: foo},
  foo2: {get: foo}
});
```

`obj.foo` returns the function `foo`, `obj.foo2` **calls** `foo` and returns `bar`.

**Comment by filimo** [comment]
ok, I've got it, I want to make `@autobind` instead of `.bind(this)`
but I can't redefine the method like this to get full control(getter and setter)

````javascript
function autobind(target, key, descriptor) {
  var fn = descriptor.value;
  delete descriptor.value;
  descriptor.get = function (...args) {
      console.log(this)
      return fn.bind(this)
  };
  descriptor.set = function (...args) {
      console.log(this)
      return fn.bind(this)
  };
}

class Person {
  firstName = "Sebastian";
  lastName = "McKenzie";

  @autobind
  test() {
    return `${this.firstName} ${this.lastName}`;
  }
}

var fn = new Person().test
console.log(fn(1, 2))
````
