### ISSUE TITLE
require('babel/polyfill') twice throws

### ISSUE THREAD

**Issue by mtscout6** [babel/babel#1312]
I'm sure there is a reasoning for this although I'm struggling to understand a proper workaround. I have a module that I'm building where babel transforms my src folder to the lib folder when I publish to npm. Since I'm publishing transpiled code I felt the need to include `import 'babel/polyfill';` as the first line of the entry script for my module. This works fine within the unit tests in that module since the babel/polyfill file is the same file and not loaded more than once.

Now, I have a second module that will depend on the first and is also using babel to transform my scripts prior to publishing. The problem is that the moment at which the upstream module is imported the upstream tries to apply the polyfill and bam I'm hit with an error: https://github.com/babel/babel/blob/master/src/babel/polyfill.js#L1-L3

I'm pretty confident that this issue will go away once npm v3 is released and the node_modules folder is flattened, although I'm left with what feels like a hack. I'm pretty sure that the problem is because there are two identical files that register the polyfill.

```
/DownstreamModule
├─┬ node_modules
│ ├─┬ UpstreamModule
│ │ ├─┬ lib
│ │ │ └── index.js  ( first line:   import 'babel/polyfill'; )
│ │ ├─┬ node_modules
│ │ │ └─┬ babel (v5.1.11)
│ │ │   └── polyfill
│ ├─┬ babel (v5.1.11)
│ │ └── polyfill
├─┬ src
│ └── index.js (source es6 js files)
├─┬ test
│ ├── mocha.opts (if you are using mocha)
│ └── (unit tests written in es6)
└── ...
```

Would it be reasonable to store the babel version number in that global variable instead of a boolean. Then potentially do some kind of SemVer check to see if that polyfill that is loaded is ok, then if not to `console.log('Some Warning');`.

Or is there a better work around for this that I'm not seeing?

**Comment by loganfsmyth** [comment]
The reasoning is that I'd never expect loading a module to mutate global objects, which is what the polyfill does.

The recommended solution to writing modules in ES6 is to use [the runtime transform](http://babeljs.io/docs/usage/runtime/) to re-write all global object access to use a scoped version of the polyfill. Then the code that is being distributed just references the `babel-runtime` module instead of referencing globals added by the polyfill.

If you have questions, feel free to ask on [Gitter](https://gitter.im/babel/babel).

**Comment by sebmck** [comment]
Unsure where the confusion is? The error is thrown when two different versions of `babel/polyfill` are loaded. As long as all the requires resolve to the same location then the polyfill will only be loaded once. If you're building a library that includes the polyfill then I'd highly discourage it.

**Comment by mtscout6** [comment]
What is the recommended approach then? The ES6 code i've written is using generators, which is not accounted for with functions with the same script. It requires the regenerator runtime, which is not inlined. See: https://github.com/css-band-aid/css-band-aid/blob/master/src/chunk.js. My work around for this has to be in a separate script: https://github.com/css-band-aid/css-band-aid/blob/master/src/index.js#L1-L8 since the regenerator code is prepended before any other script imports.

**Comment by sebmck** [comment]
Use the [runtime](http://babeljs.io/docs/usage/runtime).

**Comment by mtscout6** [comment]
Ok, sorry about that I completely misunderstood that page when I skimmed it yesterday. Thanks!
