### ISSUE TITLE
Babel parser typescript should throw when declare is applied to accessors

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#13126]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Parsed successfully.

- [REPL](https://babel.dev/repl#?browsers=chrome%2088&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEDCCc9oG8BQ1oBMCmowCdtoBzbAF2gCMwAvACgEoAuORdLXcQ6Ccq2ugDcGqAL5A&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.13.15&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.12.13)

**Input Code**

```ts
class C99 {
  declare get baz(): C99
  declare set baz(v)
}
```

**Expected behavior**

Babel parser should throw class accessors should not have "declare" modifier, like we did for class methods.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
REPL

**Possible Solution**

**Additional context**

Found this issue when reviewing #13089.

**Comment by fedeci** [comment]
I can handle this!
