### ISSUE TITLE
new version 7.13.15 can't be found from NPM

### ISSUE THREAD

**Issue by YiHan0525** [babel/babel#13124]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by JLHwung** [comment]
@babel/parser@7.13.15 is [published](https://www.npmjs.com/package/@babel/parser) on npm. The npmjs.com is the single source of truth.

Please check if you are behind a proxy or using a third party npm registry. There are situations when these cache needs some time to update to the latest version. In the past we have come across these issues after a new version is released https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed It will be solved eventually through time.

**Comment by crh225** [comment]
no proxy, no downloads on npm statistics either

**Comment by crh225** [comment]
our issue was we had our own versions of npm packages installed on azure devops, and it hasnt gotten the new version yet.

**Comment by crh225** [comment]
@JLHwung that is what I am doing now, running it with `npm ci` vs install. Thanks!!

**Comment by GranticusOfSparta** [comment]
Quick question, so the idea is that we just don't get the latest version now? Also what does this have to do with azure devops? There are zero downloads for the npm package @babel/parser at version 7.13.15 on https://www.npmjs.com/package/@babel/parser/v/7.13.15. Wouldn't you expect at least one download by now?

**Comment by saswat3115** [comment]
If you have package-lock.json file before this version then it ll work.
