### ISSUE TITLE
 glob-parent 3.1.0 dependency vulnerability on @bable/cli@7.13.14

### ISSUE THREAD

**Issue by madhurjya** [babel/babel#13135]
It looks like that package use’s babel/cli which requires nicolo-ribaudo/chokidar-2 which has in turn used glob-parent 3.1.0 which is the package with the vulnerability. nicolo-ribaudo/chokidar-2 hasn’t been updated since Nov 2020. Any update to removing this vulnerability?

![image](https://user-images.githubusercontent.com/6246568/114307837-4ddf6980-9ad9-11eb-99bc-9ecb4f672775.png)

**Comment by nicolo-ribaudo** [comment]
That dependency is only used when you are on Node.js 6. If you use Node.js 8+ the vulnerable code is never executed on your machine.

On Node.js 6 (which hasn't been maintained for years anyway) there is no alternative for that package (which is a fork of `chokidar` 2), so we cannot remove it.

**Comment by CodingAnarchy** [comment]
@nicolo-ribaudo I might be misunderstanding, but given that Node.js < 10 is not supported at all anymore, what is the reasoning behind keeping around dependencies that support Node.js 6?

**Comment by nicolo-ribaudo** [comment]
Babel 7 supports Node.js 6+. We will drop support for Node.js 6, 8, 10, 11 and 13 in the next major.

**Comment by mattlysf** [comment]
can this come sooner? I am literally going to have to find an alternative to babel-cli to maintain internal compliance for my project unless we can remove older versions of glob-parent from my project's dependency set

**Comment by mattlysf** [comment]
I am literally having to fork babel-cli and remove this from it over this issue.

**Comment by nicolo-ribaudo** [comment]
The issue here is with the vulns reporting tool that doesn't allow marking some vulnerability as "not actually affecting my codebase" :shrug: 

Anyway, we already merged a fix to update `glob-parent`. I was going to release but our release tool had a problem, it will probably go out in a few hours.
