### ISSUE TITLE
Trim down install size by 5 mb by dropping lodash

### ISSUE THREAD

**Issue by marvinhagemeister** [babel/babel#13134]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**

Currently every babel installation installs `lodash` as a dependency, because it is required by `@babel/types`. This consumes 5MB of disk space for every babel installation. 

```bash
$ du -h node_modules | sort -h
# ...snip
4.9M	node_modules/lodash
5.9M	node_modules/@babel
7.4M	node_modules/esbuild/bin
7.5M	node_modules/esbuild
8.0M	node_modules/prettier/esm
 17M	node_modules/rxjs
 18M	node_modules/prettier
 54M	node_modules/typescript/lib
 57M	node_modules/typescript
133M	node_modules
```

```bash
$ npm ls lodash
my-project@0.0.1 /Users/marvinhagemeister/dev/github/my-project
└─┬ @babel/core@7.13.14
  └─┬ @babel/types@7.13.14
    └── lodash@4.17.21
```

Doing a quick grep over babel's repo the `lodash` package is used for the following tasks:

- Get the last element in an array
	- https://github.com/babel/babel/blob/9808d2566e6a2b2d9e4c7890d8efbc9af180c683/packages/babel-plugin-transform-function-name/test/fixtures/function-name/modules-2/input.mjs#L9
- Check if a value is an object that was created via the `Object` constructor
	- https://github.com/babel/babel/blob/6b39bafab696a82132e2dd0cc9f7b14661297ae9/packages/babel-types/src/converters/valueToNode.ts#L98
- Deeply clone a value
	- https://github.com/babel/babel/blob/7bc72bb451e71d7d8964efdf4438d5a907aae655/eslint/babel-eslint-plugin/test/rules/no-invalid-this.js#L55
	- https://github.com/babel/babel/blob/6b39bafab696a82132e2dd0cc9f7b14661297ae9/packages/babel-register/src/node.js#L45
- Debounce a function
	- https://github.com/babel/babel/blob/98aa72ca74631dc80e0a9e56a3a105c139b152a4/packages/babel-cli/src/babel/dir.js#L138 

A small footprint is desireable as it makes docker images smaller which in turn lead to faster deployments.

**Describe the solution you'd like**

Smaller install size. I did start a [small ~4kb lodash clone](https://github.com/marvinhagemeister/smoldash) a while back, but it's missing `isPlainObject`. The rest should work out of the box. Functions like getting the last element of an array should probably be just inlined though.

**Describe alternatives you've considered**.

**Documentation, Adoption, Migration Strategy**

**Comment by nicolo-ribaudo** [comment]
Yeah at least `last`, `isPlainObject` and `debounce` can be easily inlined.

**Comment by hzoo** [comment]
Agreed, we're happy to take a PR to inline these especially since a lot of them are only used once/in one place. Did a few of these kinds of PRs earlier https://github.com/babel/babel/pull/13057

For the particular thing about `@babel/core`, we can inline isPlainObject and remove it since it's the main reason
