### ISSUE TITLE
Module not found: Error: Can't resolve '@babel/runtime/helpers/asyncToGenerator'

### ISSUE THREAD

**Issue by wangzl1163** [babel/babel#13144]
error msg: 
Module not found: Error: Can't resolve '@babel/runtime/helpers/asyncToGenerator'
Module not found: Error: Can't resolve '@babel/runtime/helpers/defineProperty'
Module not found: Error: Can't resolve '@babel/runtime/regenerator'

babel.config.json content : 
{
	"presets": [
		"@babel/preset-env",
		"@babel/preset-typescript"
	],
	"plugins": [
		"@babel/plugin-transform-runtime"
	]
 }

babel version: v7.13.15
babel/runtime version: v7.13.10
babel/plugin-transform-runtime version: v7.13.15
Node/npm version: v14.16.0/6.14.11

**Comment by JLHwung** [comment]
Can you provide a reproducing repo?

**Comment by wangzl1163** [comment]
> 
> 
> Can you provide a reproducing repo?

babel`s  "try it out" no error, but reported an error locally.

**Comment by JLHwung** [comment]
> babel`s "try it out" no error, but reported the error locally.

Can you isolate the error and extract to a git repo? I can not reproduce this error.
