### ISSUE TITLE
[@babel/preset-env] Optional chaining operator not working in Chrome

### ISSUE THREAD

**Issue by scinos** [babel/babel#13145]
## Bug Report

Repo with reproduction: https://github.com/scinos/test-babel-not-optional-chaining

**Input Code**

- Filename `.babelrc.js`
    ```js
    module.exports = {presets: ['@babel/preset-env']};
    ```

- Filename `.browserslistrc`
    ```text
    Chrome 88
    ```

- Filename `src/index.js`
    ```js
    console?.log("test")
    ```

**Current behavior**

When running `babel src -d dist` it generates a file with `?.` transpiled down:

```js
"use strict";

var _console;

(_console = console) === null || _console === void 0 ? void 0 : _console.log("test");
```

**Expected behavior**

It should generate a file with the optional chaining operator:

```js
"use strict";

console?.log("test");
```

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  npmPackages:
    @babel/cli: 7.13.14 => 7.13.14 
    @babel/compat-data: 7.13.15 => 7.13.15 
    @babel/core: 7.13.15 => 7.13.15 
    @babel/preset-env: 7.13.15 => 7.13.15 
```

**Possible Solution**

Looks like the error is related to Chrome (using `Firefox 88` as the target works), and introduced since `@babel/preset-env@7.13.10` and/or `@babel/compat-data@7.13.11`.

Potentially related to #13009 ?

**Comment by nicolo-ribaudo** [comment]
Yes, Chrome doesn't fully support optional chaining.
If you want to compile only the unsupported bits of that feature, you can enable the `bugfixes: true` option of `@babel/preset-env`.

**Comment by JLHwung** [comment]
For more context, see https://github.com/babel/babel/issues/13001

Closing this issue as the behaviour is intended.
