### ISSUE TITLE
Auto-wrap multiple siblings elements into a React JSX Fragment

### ISSUE THREAD

**Issue by MrNossiom** [babel/babel#13146]
### Hello there 👋🏻,
I had an idea during the day and I wanted to submit it to confront others' though...

### Describe the solution you'd like 📖 

The idea is to automatically warp all siblings tags in a JSX Fragment if there is more than one tag.
This would give something like:
```jsx
const Homepage = () => (
	<Head lorem={'ipsum'} foo={'bar'} />
	<main>
		<section>
			<h1>Headline</h1>
			<Headline />
		</section>
		<section>
			<h1>About</h1>
			<About />
		</section>
	</main>
);
```
that transpile, with the wrapping JSX Fragment, to:
```jsx
const Homepage = () =>  React.createElement(
    React.Fragment,
    null,
    React.createElement(Head, { lorem: 'ipsum', foo: 'bar' }, null),
    React.createElement("main", null, /* Children tags */)
  )
```

### Describe alternatives you've considered. 🚶🏻

I've considered placing the JSX Fragments by myself `😢` ...

### Documentation, Adoption, Migration Strategy ⚠️
I can document myself and make an issue, but I would like to know devs' feedback.

It could also be optional and toggled in the config. 🤷🏻‍♂️

Thanks for your attention and any answers.
MrNossiom

**Comment by MrNossiom** [comment]
I think this affect this package: [@babel/plugin-transform-react-jsx](https://www.npmjs.com/package/@babel/plugin-transform-react-jsx)

**Comment by hzoo** [comment]
It's a nice idea! We don't tend to modify the syntax/behavior of things whether it's JSX or not in Babel itself. I think that would be a suggestion for https://github.com/facebook/jsx (can check if someone has asked about it before). As you noted, the error `Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?` does tell the user to maybe wrap it.

I think best we can do is do a codemod to automatically add the <> in your source for you but it could also be an editor thing.

**Comment by nicolo-ribaudo** [comment]
I agree with Henry, this is something that needs first to be proposed and accepted in the JSX specification!

**Comment by MrNossiom** [comment]
I'll do this...

Thanks
