### ISSUE TITLE
this should be disallowed in static

### ISSUE THREAD

**Issue by ben-ng** [babel/babel#1314]
Babel seems to be happy with this:

```js
class Farm {
  static a () {
    this.cow = 'b'
  }
}
```

Since Babel is is smart enough to know when `super` is used improperly, I was expecting it to whine about this. Is this expected behavior? unimplemented feature? bug?

**Comment by sebmck** [comment]
How isn't this expected behaviour?

**Comment by ben-ng** [comment]
I expect using `this` in a static method to fail, since there is no instance to refer to.

**Comment by sebmck** [comment]
`this` doesn't refer to an instance, it refers to a context. In this case the context is the `Farm` singleton.

**Comment by ben-ng** [comment]
I see, thanks
