### ISSUE TITLE
resolve vue PropType 

### ISSUE THREAD

**Issue by lingchenzheng** [babel/babel#13165]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```ts
import {defineComponent, PropType} from 'vue'
export default defineComponent({
    props: {
          type: {
               type: String  as PropType<'a' | 'b'>
         }
   }
})
```

**Expected behavior**

Unexpected token  , expected ","

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by fedeci** [comment]
Hi @lingchenzheng, that is the wrong syntax, you should wrap the `as` between parenthesis,
```ts
import {defineComponent, PropType} from 'vue'
export default defineComponent({
    props: {
          type: {
               type: (String as PropType<'a' | 'b'>)
         }
   }
})

```

**Comment by fedeci** [comment]
I can't reproduce this in [REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbwCYFMBmwB2KDCFwTaYwA0cAClBGACoCeYKAvnGlSHAOQBuAripwBQKAB6RYcVGgCGvADbwpWXPkhEYACgSC4uuGCpgAzgC5EOvZd0wGKM9quPLNxmYDKMKFgDmu6UYpDekYAHk5pTjgAHy4AI04APgsnJmTUpgBKIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.13.15&externalPlugins=). What version of `vue` are you using?

**Comment by nicolo-ribaudo** [comment]
You need to enable the Typescript Babel plugin
