### ISSUE TITLE
Release build crashes on iOS and Android. Fatal Exeption

### ISSUE THREAD

**Issue by leandrojpinh** [babel/babel#13161]
Hello Guys, 

On this afternoon, I was trying to generate release version of app that I'm working with my time, and we got error that says in logcat:
`com.facebook.react.common.JavascriptException: ReferenceError: Can't find variable: typeAnnotation, stack:...`

And we asked to yourself... what's this? and after so long time, we find in a article that could be something with @babel/types, and there we go, we found in our code, this import:
`import { isTerminatorless } from '@babel/types';`

but, the intersting things is: We aren't use that function: isTerminatorless, why ocurred error if we wasn't using the function?

**Comment by nicolo-ribaudo** [comment]
> `com.facebook.react.common.JavascriptException: ReferenceError: Can't find variable: typeAnnotation, stack`

You cropped the most important part of the error: the stack trace :stuck_out_tongue:

**Comment by nicolo-ribaudo** [comment]
Closing as not reproducible.
