### ISSUE TITLE
destructuring assignment (...other) to fails in JSX  (React V13.0.2)

### ISSUE THREAD

**Issue by codeuniquely** [babel/babel#1316]
according to React Docs
https://facebook.github.io/react/docs/transferring-props.html

Sometimes it's fragile and tedious to pass every property along. In that case you can use destructuring assignment with rest properties to extract a set of unknown properties.

List out all the properties that you would like to consume, followed by ...other.

but when you write 

    var { checked, ...other } = this.props;

You get an error of Unexpected token (16:17)

```
 }
 render() {
         var { checked, ...other } = this.props;
                        ^

**Comment by sebmck** [comment]
Not a bug, please see the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Object spread/rest is an ES7 proposal and it's currently at stage 1, see the [experimental docs](http://babeljs.io/docs/usage/experimental/) for more info.

**Comment by codeuniquely** [comment]
Why is it not a bug - its been in React since 0.12.x and you say you support React at V 0.13.x.and JSX but you don't appear to generate the right output.

What README???? - Add the actual link would have been nice.

Why add two links to a general forums and a link to a next to useless page  ?

**Comment by sebmck** [comment]
> Why is it not a bug - its been in React since 0.12.x and you say you support React at V 0.13.x.and JSX but you don't appear to generate the right output.

Because Babel does in fact support it. I linked you to [this](http://babeljs.io/docs/usage/experimental/) page which explains how to enable it.

> What README???? - Add the actual link would have been nice.

The actual GitHub README which is only 3 lines: https://github.com/babel/babel#readme

**Comment by codeuniquely** [comment]
I don't understand  - what enables it, I'm actually using babel-loader via the NPM package the docs there (under options) https://github.com/babel/babel-loader reference you information on runtime at http://babeljs.io/docs/usage/runtime/ 

So do I just pass a ?stage=1 at the end of the JSX loader definition?

**Comment by sebmck** [comment]
> So do I just pass a ?stage=1 at the end of the JSX loader definition?

Yes.

**Comment by codeuniquely** [comment]
That seems to work - well no errors anyway ...

cheers
