### ISSUE TITLE
commonjs transform does not convert to MemberExpression for second decorator

### ISSUE THREAD

**Issue by proteriax** [babel/babel#13177]
## Bug Report

Apologies for not using the template because your `bug_report.yml` is currently invalid so there’s no way to report a bug from the web page right now.

In short, 

```js
import { namespace } from 'test'

@namespace.test
@namespace.test
class Test {}
```

becomes

```js
"use strict";

var _source = require("source");

@_source.namespace.test
@_namespace.test
class Test {}
```

Reproduction: https://github.com/proteriax/babel-bug
Please clone the repository and run `yarn build`. Observe the `.babelrc.js` because it contains a custom plugin.

**Comment by nicolo-ribaudo** [comment]
I think that the problem might be that you are using duplicated nodes in the AST, and this causes problems.

Does it work if you do `t.cloneNode(namespace)` when building the second decorator, so that you don't re-use the `namespace` node?

**Comment by proteriax** [comment]
You are correct, cloning the node indeed works. Should this be considered a bug or working as intended?

**Comment by JLHwung** [comment]
It works as intended. As a plugin author you can use https://github.com/Andarist/babel-check-duplicated-nodes to check if the plugin produce duplicate AST nodes.
