### ISSUE TITLE
[Bug]: `sourceFileName` vs. `sourceFilename` scattered differently over project, sometimes typed wrong

### ISSUE THREAD

**Issue by wooorm** [babel/babel#13170]
### 

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

n/a

### Configuration

n/a

### Current and expected behavior

```js
  function myFancyBabelPlugin() {
    return {
      parserOverride(contents, options) {
        if (
          options.sourceFileName &&
```

^-- type error “Did you mean 'sourceFilename'”, but `sourceFilename` is undefined and `sourceFileName` is set.
A bit of searching shows differently cased values: https://github.com/babel/babel/search?q=sourceFilename+path%3Apackages.

### Environment

```sh
$ npx envinfo --preset
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

No "true" preset found.
```

### Possible solution

picking either

### Additional context

Actual code is here: https://github.com/wooorm/xdm/blob/main/test/babel.js#L37-L41.

**Comment by fedeci** [comment]
That's because different packages are now using different option name. We may align the syntax in Babel 8 because it is a breaking change.

**Comment by wooorm** [comment]
I can understand differently cases due to history, and would welcome a single case. But it remains that the types are incorrect!

**Comment by nicolo-ribaudo** [comment]
We can start by allowing both the current "mixed" versions and the consistent versions in the next minor; then in Babel 8 we can remove the "mixed" versions (and yes, we should fix the type definitions).

**Comment by fedeci** [comment]
I did some research while changing all occurrences of `sourceFileName` with `sourceFilename` and discovered that the error of the issue is caused by the following lines
https://github.com/babel/babel/blob/90d5eb7f2f2c699019aab2d5388ec1e8f3f469d2/packages/babel-core/src/transformation/normalize-opts.ts#L29-L33
We are setting the unused `sourceFileName` parser option and, in fact, commenting line 33 results in no tests failing, because there is "nothing to break".

**Comment by aleclarson** [comment]
This inconsistency seems to be breaking `@babel/plugin-transform-react-jsx-source` in some cases. Could the `getOptions` function support both namings in a new patch version?

https://github.com/babel/babel/blob/224a35c5c69750f7deea19744d4bc14cb069789e/packages/babel-parser/src/options.js#L73-L79

```js
export function getOptions(opts: ?Options): Options {
  const options: any = {};
  for (const key of Object.keys(defaultOptions)) {
    options[key] = opts && opts[key] != null ? opts[key] : defaultOptions[key];
  }
  if (opts.sourceFileName) {
    options.sourceFilename = opts.sourceFileName
  }
  return options;
}
```
