### ISSUE TITLE
[Bug]: unknown Expression of type "ClassExpression

### ISSUE THREAD

**Issue by mike-lischke** [babel/babel#13171]
### 

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I prepared a simple project which reproduces the problem: https://github.com/mike-lischke/babel-test

Run `npm install` in the root, then npm `run build` and after a while the build will stop with:

    ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/wordDistance.js
    Error: /babel-test/node_modules/monaco-editor/esm/vs/editor/contrib/suggest/wordDistance.js: unknown Expression of type "ClassExpression"
    at Array.forEach ()

Now change 2 entries in package.json:

"monaco-editor": "^0.20.0",
"monaco-editor-webpack-plugin": "^1.9.1",

and run the same two steps again. The build will now succeed.

### Configuration file name

package.json

### Current and expected behavior

This is part of a setup created by create-react-app, so babel is just one of a number of tools used in the chain.

The problem was found when upgrading monaco-editor to version to 0.23.0. Now you might think this is probably an issue with that 3rd party lib, but analysis has shown that Babel might well have a stake here. Someone filed an[ issue against monaco-editor](https://github.com/microsoft/monaco-editor/issues/2191) where it was analyzed to be an issue of the transformation of async to generator code.

It's not totally clear to me who's the culprit in this scenario, but since this issue is a timebomb for my project, I'm trying to get a solution urgently.

The linked issue has a pretty detailed analysis of the problem, which I don't want to copy here (but I can if you prefer).

### Environment

  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    npm: 7.6.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.13.15 => 7.13.15 
    @babel/preset-env: ^7.13.15 => 7.13.15 
    @babel/preset-typescript: ^7.13.0 => 7.13.0 
    eslint: ^7.24.0 => 7.24.0 
    jest: 26.6.3 => 26.6.3

**Comment by nicolo-ribaudo** [comment]
Babel uses `regenerator` to compile generator functions, which has a bug when compiling generators that contain class expressions: https://github.com/facebook/regenerator/issues/407 (I'm now closing this issue since it's already tracked there).

I also prepared a PR to fix this problem, but it needs to be reviewed and merged: https://github.com/facebook/regenerator/pull/408.
