### ISSUE TITLE
[Bug]: latest version of @babel/core has No matching version found for @babel/helper-compilation-targets@^7.13.16.

### ISSUE THREAD

**Issue by gaje** [babel/babel#13181]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Simple `npm i @babel/core` fails with:

```
npm ERR! notarget No matching version found for @babel/helper-compilation-targets@^7.13.16.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/core'
npm ERR! notarget 
```

### Current and expected behavior

Should install babel/core

### Environment

Any

**Comment by grdlo** [comment]
seem's to be the same issue than https://github.com/babel/babel/issues/13180

**Comment by JLHwung** [comment]
@babel/helper-compilation-targets@7.13.16 is [published](https://www.npmjs.com/package/@babel/helper-compilation-targets) on npm. The npmjs.com is the single source of truth.

Please check if you are behind a proxy or using a third party npm registry. There are situations when these cache needs some time to update to the latest version. In the past we have come across these issues after a new version is released https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed It will be solved eventually through time.
