### ISSUE TITLE
[Bug]:  Unable to install @babel/traverse

### ISSUE THREAD

**Issue by NishithHM** [babel/babel#13187]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

npm i @babel/traverse

### Current and expected behavior

Current
pm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/generator@^7.13.16.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget 

Expected:
installation should be successful

### Environment

node version 15.12
npm version 6.14.0

**Comment by nicolo-ribaudo** [comment]
`@babel/generator` 7.13.16 is on npm: https://www.npmjs.com/package/@babel/generator/v/7.13.16

Please see https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67
