### ISSUE TITLE
[Bug]:  Can't find package @babel/types@^7.13.16

### ISSUE THREAD

**Issue by SteinNs** [babel/babel#13180]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

none

### Current and expected behavior

Hi, I got the following error

`
   @babel/generator@7.13.16 › @babel/types@^7.13.16] Can't find package @babel/types@^7.13.16
`

@babel/types@^7.13.16 is not released

### Environment

- Node@15

**Comment by fedeci** [comment]
This is likely a problem with npm registry cache or the proxies between you and the registry.
See #13127 and #13124.

**Comment by nwhite89** [comment]
Forcing cache clean seems to have sorted this out for me
