### ISSUE TITLE
Babel options bleed thru when transforming plugins

### ISSUE THREAD

**Issue by lukescott** [babel/babel#1319]
Example:

```javascript
var gobble = require("gobble");

module.exports = gobble("app")
.transform("babel", {
	blacklist: ["strict", "es6.modules"],
	plugins: ["./foo"],
})
.transform("esperanto-bundle", {
	entry: "main.js",
	type: "umd",
	name: "director"
});
```

And if my plugin is written in ES6, just like the babel docs show, it fails to run the plugin because "es6.modules" is blacklisted.

**Comment by sebmck** [comment]
Not sure I completely understand the problem?

**Comment by fkling** [comment]
>  it fails to run the plugin because "es6.modules" is blacklisted.

How is your plugin related to "es6.modules"? Are you saying that when "es6.modules" is blacklisted, no plugin will be executed?

**Comment by lukescott** [comment]
I'm using esperanto bundler to concat the files. So I add `es6.modules` to the blacklist as babel transforms first. When I run "gobble build" I get:

```
(function (exports, require, module, __filename, __dirname) { import {Transfor
                                                              ^^^^^^
Unexpected reserved word
```

For some reason my app's babel settings are being used to transform the plugin. I only need to blacklist `es6.modules` when used in conjunction with esperanto.

**Comment by lukescott** [comment]
Just confirmed this happens to plugins included from node_modules. I've tried adding a `.babelrc` to the plugin with `{}` and `{blacklist:[]}` and it still happens.

**Comment by cesarandreu** [comment]
Try setting `breakConfig: true`, it'll stop babel from trying to read your babelrc file.

@sebmck is breakConfig considered a public API?

**Comment by lukescott** [comment]
@cesarandreu This happens without a `.babelrc` file. It's picking up options from the code in the first post. I have tried using a `.babelrc` file to clear the options while transforming the plugin, but that doesn't work either.

The only thing I've gotten working is simply not writing my plugins in ES6. Which for me isn't a big deal because my plugin is 8 lines long, but options in a project like `blacklist: ["es6.modules"]` would break other plugins.

To be clear, `blacklist: ["strict", "es6.modules"]` is in my project in my gobblefile.js. The plugin itself can either be a local file or installed thru npm. Either way I get the `Unexpected reserved word` error.

**Comment by sebmck** [comment]
It's unclear what the specific issue is. Can you please provide steps to reproduce

**Comment by lukescott** [comment]
I created a new project and was able to reproduce, but since the current issue misrepresents the actual issue, I'll close this one.
