### ISSUE TITLE
[Bug]: after building, system got an error when triggering click event

### ISSUE THREAD

**Issue by jiangyh1024** [babel/babel#13206]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
onTreeSelect = (selectedKeys, { node }) => {
    const { dispatch, data } = this.props;
    if (node) {
      const accountType = data.accountTree.filter(item => {
        return Number(node.key) === Number(item.key);
      });
      dispatch({
        type: 'chargeItemType/updateAccountState',
        payload: {
          accountTypeId: accountType[0].key,
          subjectNumber: accountType[0].subjectNumber,
          accountTypeName: accountType[0].name,
          isIncome: accountType[0].isIncome,
        },
      });
    }
    dispatch({
      type: 'chargeItemType/fetchList',
      payload: { page: 1, pageSize: data.pageSize },
    });
  };
```

### Current and expected behavior

![image](https://user-images.githubusercontent.com/34930870/116037056-245a3c80-a69a-11eb-96c2-c34a81a4079b.png)

as described in above image

### Environment

@babel/core 7.4.5

**Comment by fedeci** [comment]
Hi @jiangyh1024, can you provide more info about your config file and how you are using babel?

**Comment by jiangyh1024** [comment]
I'm using umijs. All I need to do is run 'npm run build' command, and it'll generate the final bundled files

here is the version of 'babel'
![image](https://user-images.githubusercontent.com/34930870/116041241-92553280-a69f-11eb-946e-e96f0ee425d8.png)


I've also tried to upgrade it to the latest version, but it still doesn't work.

**Comment by jiangyh1024** [comment]
it  seems that this isn't related to babel, but 'react-activation' package. After I remove it, it works.
