### ISSUE TITLE
async/await doese not work with systemjs

### ISSUE THREAD

**Issue by PinkaminaDianePie** [babel/babel#1320]
seems to SystemJS polute global scope, used by babel polyfills or smth. for example this code works well:
```javascript
A.get({}).get('123').get('123', '456'); //returns Promise
```
but this code
```javascript
try{
	let a = await A.get({}).get('123').get('123', '456'); //es7 async function, works with promises
	done();
}catch(e){
	done(e);
}
```
fails with error:
```bash
node_modules/es6-module-loader/dist/es6-module-loader.src.js:1185
				next.become(new Rejected(e));
        ^
TypeError: Cannot read property 'become' of undefined
```
Both snippets works well without SystemJS, but when i include it (just include, without any System.import calls), second snippet crashes with error.
i dont know is it a babel issue or systemjs, so i post this in systemjs thread: https://github.com/systemjs/systemjs/issues/415

UPD:
after some research i found what error appeared only if i return subclass of promise. 
```javascript
class MyPromise extends Promise{
	constructor(executor){
		super(executor);
	}
}
```
if i return plain Promise async/await works fine. after that i test Promises without async/await and have similar issue. so problem is with Promise subclassing. May be SystemJS polute promise polyfill and subclassing fails.

**Comment by sebmck** [comment]
cc @guybedford

**Comment by guybedford** [comment]
@PinkaminaDianePie it would really help if you can be explicit about the operations you are performing. It is great to see code examples, but it is very difficult to tell what you mean by "when I include it, without any System.import calls". Am I right in thinking you are using a Node `require` to load direct ES6 here? Or did you transpile it through Babel first?

**Comment by zloirock** [comment]
BTW, about `Promise` subclassing - `Promise` methods are not generic by result in some envieronments:
```js
class MyPromise extends Promise { }
function f(){}

console.log(new MyPromise(f) instanceof MyPromise) // true
console.log(new MyPromise(f).then(f) instanceof MyPromise) // true in V8, false in FF
```

**Comment by PinkaminaDianePie** [comment]
@guybedford at first i created Promise subclass and returned in in 'get()' function.  class "Chainable" in https://github.com/PinkaminaDianePie/planck/blob/master/lib/active-record/lib/active-record-base.js) then i run tests in https://github.com/PinkaminaDianePie/planck/blob/master/test/active-record/active-record.js, exact test is there
```javascript
			it('should return promise', async (done) => {
				try{
					await A.get({}).get('123').get('123', '456');
					done();
				}catch(e){
					done(e);
				}
			});
```
tests and code precompiled with babel and everything is ok. if i include SystemJS in file with tests (just add the line with require(), every my module loads with import/require, nothing loaded via System.import) then test with my promise subclass fails. at first i thought its problem with async/await, but then i changed my code to 
```javascript
			it('should return promise', (done) => {
				A.get({}).get('123').get('123', '456').then(() => {
					done()
				});
			});
```
nothing has changed. i always have same error:

```bash
node_modules/es6-module-loader/dist/es6-module-loader.src.js:1185
                next.become(new Rejected(e));
        ^
TypeError: Cannot read property 'become' of undefined
```
if i remove from my code this text
```javascript
var System = require("systemjs");
```
everything works again. if i include systemjs all other tests works fine, tests without promises subclassing also works, problems only with subclassing. so i think problem with compatibility between babel's promises and SystemJS.

**Comment by guybedford** [comment]
Ok thanks for clarifying. SystemJS loads the when.js Promise shim, which actually seems to always overwrite the `Promise` global.

The next major release of SystemJS will no longer rely on this shim by default.

In the mean time, it's advisable to always reference `Promise` and not use it via the global to avoid issues like this. A workaround might be to reassign Promise immediately after requiring SystemJS. Not nice at all, but it will work.

**Comment by sebmck** [comment]
This doesn't seem to be a bug with Babel and instead with the promise library/native Promsie subclassing. Let me know if there's anything I can do to help further.
