### ISSUE TITLE
Where is the ||= operator?

### ISSUE THREAD

**Issue by ooflorent** [babel/babel#1321]
`||=` seems to be gone since 5.0.0.
Why? Am I missing something?

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by sebmck** [comment]
Also the [CHANGELOG](https://github.com/babel/babel/blob/master/CHANGELOG.md#500) and [release blog post](http://babeljs.io/blog/2015/03/31/5.0.0/#removed-features).

**Comment by ooflorent** [comment]
Well, sorry. Thanks for your answer.
