### ISSUE TITLE
Path replacement with string source containing custom syntax

### ISSUE THREAD

**Issue by undefinedbuddy** [babel/babel#13210]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Currently, `path.replaceWith` exists for overriding a node with another and `path.replaceWithSourceString` for overriding with a string source. Does there exist a process to achieve the latter without Babel parsing the source string provided to the method?

### Describe the solution you'd like

Something like:

```js
ArrayExpression(path) {
  path.no_parse_replaceWithSourceString("%[]%");
}
```

Such that passing `[10, 20, 30]` would result in `%[10, 20, 30]%`. If not, does there exist a workaround to achieve that? Perhaps by making use of line and column positions to override sources by successive truncating and/or string slicing?

### Describe alternatives you've considered

I have not yet explored any workarounds, just to be certain that the API does not actually exist before I could work on achieving said feature.

### Documentation, Adoption, Migration Strategy

Mostly identical to `path.replaceWithSourceString`, except a custom syntax can be used without overriding `@babel/parser`.

**Comment by hzoo** [comment]
If you are going to modify the source directly, I would suggest using another tool. Babel works by modifying the AST in a certain way and then printing it. There wouldn't be an AST node for `%[10, 20, 30]%` so I'm not sure how that would work.

Related modules would be https://babeljs.io/docs/en/babel-template. You probably want https://github.com/Rich-Harris/magic-string if you are going to be changing it to arbitrary text, it lets you this

```
var MagicString = require( 'magic-string' );
var s = new MagicString( 'problems = 99' );

s.overwrite( 0, 8, 'answer' );
s.toString(); // 'answer = 99'
```
