### ISSUE TITLE
Support targets in @babel/plugin-transform-runtime as same as @babel/preset-env

### ISSUE THREAD

**Issue by QuarkGluonPlasma** [babel/babel#13226]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

I found that "Array.prototype.fill" is supported above Chrome 45 in @babel/compat-data.

![](https://user-images.githubusercontent.com/80755847/116250403-46d67d80-a7a0-11eb-9d30-5b4cae8ea81a.png)

I have tried it use @babel/preset-env which targets set to "Chrome 45" or "Chrome 44" and use corejs3. It works fine.

![](https://user-images.githubusercontent.com/80755847/116250833-afbdf580-a7a0-11eb-8269-b8b12cdf0c1b.png)
![](https://user-images.githubusercontent.com/80755847/116250852-b5b3d680-a7a0-11eb-8cd5-1bbbbc72aa9e.png)

But when I try to extract it use @babel/plugin-transform-runtime, it also transofromed "Array.prototype.fill" api  in "chrome 45".

![](https://user-images.githubusercontent.com/80755847/116251354-2b1fa700-a7a1-11eb-9a89-06b38132a788.png)

The two behaviour is not consistence. 

![](https://user-images.githubusercontent.com/80755847/116251830-9bc6c380-a7a1-11eb-8f00-ea0a85b4dc51.png)

![](https://user-images.githubusercontent.com/80755847/116251857-a1240e00-a7a1-11eb-9b7d-eb3a4daf1f03.png)

Should we make it consistent ?  Can I help?

### Describe the solution you'd like

Support targets opiton. Filter the runtime-corejs-definations with targets option and compat-data before transform the code.

It likes  use targets option and comat-data to  fiter plugin in @babel/preset-env before transform, we can use it to filter the features data also.

### Describe alternatives you've considered

I  think it's feasible and clear and probably won't fail.

**Comment by nicolo-ribaudo** [comment]
You can use the new polyfill packages, that support targets in every mode: https://github.com/babel/babel-polyfills

**Comment by QuarkGluonPlasma** [comment]
Awesome design! 

Extract "targets" to top level option so that @babel/preset-env and @babel/polyfills can use it both, and possiblely other plugins, but it maybe need change the @babel/core logic to inject targets option to every plugin's context.I guess we only need to use @babel/preset env in babel 8, and we don't need to configure @babel/polyfills separately.

Looking forward to babel 8!

( Thank you for solving my doubts. I'm writing a pamphlet about babel's principle, maybe open source it and translate to english  next year.)

**Comment by QuarkGluonPlasma** [comment]
Surprise! I saw the doc update.

https://babeljs.io/docs/en/babel-helper-compilation-targets

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since you can specify `targets` as shown in https://github.com/babel/babel/issues/13226#issuecomment-827776196.
