### ISSUE TITLE
Destructured Assignment to Property Reference

### ISSUE THREAD

**Issue by bathos** [babel/babel#1323]
The following works in Babel:

    var foo = {};
    var bar = [ 4, 5 ];
    [ foo.four, foo.five ] = bar;

... which is cool (foo is now `{ four: 4, five: 5 }` as one might expect), but I've been trying to figure out if this is intended behavior. The ES6 final draft doesn't seem to support this (though maybe it does and I'm missing something -- the syntax for binding patterns isn't exactly straightforward). I couldn't find an ES7 strawman proposal addressing it either. Is this formal ES6, a pending spec, or a Babel-specific extension?

**Comment by fkling** [comment]
It is valid. Quoting the [spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment):

```
ArrayAssignmentPattern[Yield] :
    [ Elisionopt AssignmentRestElement[?Yield]opt ]
    [ AssignmentElementList[?Yield] ]
    [ AssignmentElementList[?Yield] , Elisionopt AssignmentRestElement[?Yield]opt ]


AssignmentElementList[Yield] :
    AssignmentElisionElement[?Yield]
    AssignmentElementList[?Yield] , AssignmentElisionElement[?Yield]

AssignmentElement[Yield] :
    DestructuringAssignmentTarget[?Yield] Initializer[In,?Yield]opt

DestructuringAssignmentTarget[Yield] :
    LeftHandSideExpression[?Yield]
```

So any [`LeftHandSideExpression`](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-left-hand-side-expressions) is valid, which includes `MemberExpression`s

**Comment by bathos** [comment]
Awesome! I wasn't aware of the supplemental syntax section(s), so I was just looking at the rules stemming from ArrayBindingPattern and ObjectBindingPattern. The phrasing there ("In certain circumstances...") leaves me wondering which circumstances require the more restricted version ... parameters maybe? In any case it's nice to know about this, thanks.
