### ISSUE TITLE
[Bug]: Typo on `babel/plugin-proposal-private-private-property-in-object` package name

### ISSUE THREAD

**Issue by aancer-rca** [babel/babel#13236]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Bug occurs on a `npm install` with `@babel/preset-env` preset set.

### Current and expected behavior

Npm provides the correct babel plugin name to install `babel/plugin-proposal-private-property-in-object` and not `babel/plugin-proposal-private-private-property-in-object`

### Environment

 System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - ~/node_modules/.bin/yarn
    npm: 7.11.2 - ~/Repositories/shared-ui-components/node_modules/.bin/npm
  npmPackages:
    @babel/core: ^7.9.0 => 7.14.0 
    @babel/plugin-proposal-private-property-in-object: ^7.14.0 => 7.14.0 
    @babel/preset-env: ^7.10.2 => 7.14.0 
    babel-jest: ^26.0.1 => 26.6.3 
    babel-loader: ^8.1.0 => 8.2.2 
    eslint: ^7.25.0 => 7.25.0 
    jest: ^26.0.1 => 26.6.3 

### Possible solution

Replace line:
https://github.com/babel/babel/blob/672a58660f0b15691c44582f1f3fdcdac0fa0d2f/packages/babel-helper-create-class-features-plugin/src/features.js#L16

with 

`"@babel/plugin-proposal-private-property-in-object",`

**Comment by nicolo-ribaudo** [comment]
I not sure about how we missed it, but if you'd like to open a PR please do it!

**Comment by aancer-rca** [comment]
> I not sure about how we missed it, but if you'd like to open a PR please do it!

Looks like I don't have the required permissions to establish a branch for the bugfix in order to create a PR.

**Comment by JLHwung** [comment]
@aancer-rca You can fork the Babel repo and create a PR from your fork.
