### ISSUE TITLE
[Bug]: `Unexpected token` syntax error is thrown with `classStaticBlock` and `typescript`.

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#13234]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```ts
class Foo {
  static {}
}
```

### Configuration

Use `classStaticBlock` and `typescript` plugin.

```js
const { parse } = require("@babel/parser");

const code =`class Foo {
  static {}
}`;

const result = parse(code, {
  sourceType: "module",
  errorRecovery: true,
  plugins: ["classStaticBlock", "typescript"],
});
```

### Current and expected behavior

**current:**

SyntaxError: Unexpected token

**expected:**

no error

### Environment

- `@babel/parser` 7.14.0

### Additional context

https://github.com/prettier/prettier/pull/10802#discussion_r623549163

**Comment by JounQin** [comment]
+1 for this, I'm also facing this issue when upgrading babel in https://github.com/rx-ts/babel-preset-proposal-typescript.

**Comment by ddolcimascolo** [comment]
Hey guys, we have tests that start to fail with an automated upgrade of babel to v 7.14.0.
Context is a CRA with nothing fancy but qi can't confirm we're hit by this exact problem, I'll provide all the details later today and create a separate issue if it's not the same thing.

Cheers,
David

**Comment by nicolo-ribaudo** [comment]
Was this working in previous versions? If yes, I guess the bug has been introduced by https://github.com/babel/babel/pull/13209

**Comment by JounQin** [comment]
@nicolo-ribaudo Yes, it was working previously.

**Comment by ddolcimascolo** [comment]
> Hey guys, we have tests that start to fail with an automated upgrade of babel to v 7.14.0.
> Context is a CRA with nothing fancy but I can't confirm we're hit by this exact problem, I'll provide all the details later today and create a separate issue if it's not the same thing.
> 
> Cheers,
> David

Guys, sorry for the noise our failure was totally unrelated :eyes: 

Cheers,
David
