### ISSUE TITLE
[Bug]: plugin-transform-block-scoping constant checks produce different behaviour

### ISSUE THREAD

**Issue by overlookmotel** [babel/babel#13245]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
let isCalled = false;
const fn = () => isCalled = true;

const i = 0;
try {
  i = fn();
} catch (e) {
  console.log(isCalled);
}
```

[Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=DYUwLgBAlgzgwgQ2KAJhAvBAZkmIDcAUAMYD2AdjJFuRhABQCUGAfNPEqnWAE4CuBQiQpVodAIxFeATwgBvQhDGYaTIgF8IxBGGIALBiGYKlZSqVAA6YKQDm9WImQgUjDYSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-10&version=7.14.0&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.13.16)

### Current and expected behavior

Original code logs "true".

But [plugin-transform-block-scoping](https://babeljs.io/docs/en/babel-plugin-transform-block-scoping)'s constant checks produces code with a slightly different behaviour:

```js
function _readOnlyError(name) { throw new TypeError("\"" + name + "\" is read-only"); }
var isCalled = false;
var fn = () => isCalled = true;

var i = 0;
try {
  i = (_readOnlyError("i"), fn());
} catch (e) {
  console.log(isCalled);
}
```

This logs "false" because `_readOnlyError()` throws before `fn()` is evaluated.

### Environment

Babel REPL

### Possible solution

Order of `fn()` and `_readOnlyError("i")` should be reversed:

```js
i = (fn(), _readOnlyError("i"))
```

This order would produce wrong result if `_readOnlyError()` returned a value, but since we know for sure it'll throw, that's not relevant.

### Additional context

There are two other more obscure cases where the above solution is not sufficient to solve the problem:

(I may have time to make a PR for the simple case above, but unlikely I will for these two)

#### Destructuring

```js
const c = 0;
let x = 1, y = 2;
try {
  [x, c, y] = [11, 0, 22];
} catch (e) {
  console.log( {x, y} );
}
```

[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=MYewdgzgLgBMMF4YAYDcAoANgU1gD0RgEYAaGAT0ICYMoAnSgb3RhgG08zgzyBdQtkVIoyVKrwwBfOAEMowABYwAFNgCUMZq1CQQOAHSYQAc2WNOFSWqnogA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-10&version=7.14.0&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.13.16)

`[x, c, y] = []` is transformed to `[x, c, y] = (_readOnlyError("c"), [11, 0, 22])`.

Original logs `{x: 11, y: 2}` whereas transpiled code logs `{x: 1, y: 2}`. It should throw only after `x` has been assigned, but before `y` is.

This is tricky to get right. Best solution I can see is:

```js
// NB Assignment to `y` has been omitted
[x] = [11, 0, 22], _readOnlyError("c");
```

#### Assignment operators

```js
const calls = [];
const fn = () => calls.push('fn');

const i = {
  valueOf() {
    calls.push('valueOf');
    return 1;
   }
};

try {
  i += fn();
} catch (e) {
  console.log(calls);
}
```

[Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=MYewdgzgLgBMCGAbREYF4YG0C6BuAUKJLAGZjowAUAlOgHxxIoB0ADgK4QAWlA5Gb2oFC4aDACWFAN74YMAG5J2AUwDyJGjBly5CZBDacevRYhXrBBHTABOyqOxvkAjFbkBffO-FQbATy1ZCRgAagwyGgJ3RihgLiplWm04URBEZWZEEABzSj0UIS8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-10&version=7.14.0&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.13.16)

Original logs `[ 'fn', 'valueOf' ]`.

Babel transforms `i += fn()` to `i += (_readOnlyError("i"), fn())`. So transpiled code logs `[]`.

After reversing `fn()` and `_readOnlyError("i")`, it logs `[ 'fn' ]` (still incorrect).

The correct transpiled output would be:

```js
i + fn(), _readOnlyError("i")
```

NB `&&=`, `||=` and `??=` aren't affected by this additional complication, but I think all other assignment operators are.

`i++` / `++i` should be treated as same as `i += 1`:

```js
i + 1, _readOnlyError("i")
```

**Comment by nicolo-ribaudo** [comment]
Thanks for the detailed writeup! I'm assigning this to you since you ticked "Would you like to work on a fix?".

If you need any help feel free to ask!
