### ISSUE TITLE
arguments in _regeneratorRuntime wrapper

### ISSUE THREAD

**Issue by hgenru** [babel/babel#1324]
i try run this function as decorator http://pastebin.com/qtfs7Pyu
and babel give me this transformed function http://pastebin.com/z0jWNigw

In console i see:
    wtf <%mythis%>, [Context, callee: (...), caller: (...)], <%normal arguments%>

The problem is that trying to get access to the my arguments I get arguments `callee$2$0$(context$3$0)` function.

**Comment by stagas** [comment]
I think it's a [regenerator](https://github.com/facebook/regenerator) issue related to https://github.com/facebook/regenerator/issues/131.

**Comment by sebmck** [comment]
@stagas Don't think it is, I'll investigate.

**Comment by sebmck** [comment]
I can't replicate this on the current version of Babel and the code is generated as expected. Please upgrade to the latest (5.1.11).

**Comment by hgenru** [comment]
Sorry, i'm update babel, but forgot update babelify
