### ISSUE TITLE
Plugins pipeline

### ISSUE THREAD

**Issue by stagas** [babel/babel#1325]
From what I understand, there are no significant semantic differences from plugins and transforms. The issue is the way the pipeline runs now is too abstract and leaky and it introduces unnecessary complexity dealing with all those cases for everybody, i.e blacklists, whitelists, optional, playground, plugins working with strings/objects etc. and lots of issues I'm seeing derive from this.

What if we had the pipeline decoupled and exposed and then have Babel be an opinionated set of plugins on top of this, but still allow for lower level flexibility for the other cases and playground stuff. This way you could add, remove, group plugins, isolate groups that depend on each other, be explicit on the order of the execution. Babel dev would have better focus on just working on the plugins for spec compliancy instead of dealing with pipeline issues, and the pipeline dev would get better focus as well. So the suggestion in short is decoupling Babel plugins/transforms and the AST manipulation pipeline.

What do you think?

**Comment by sebmck** [comment]
> From what I understand, there are no significant semantic differences from plugins and transforms. The issue is the way the pipeline runs now is too abstract and leaky and it introduces unnecessary complexity dealing with all those cases for everybody

Plugins will eventually have the ability to plug into the parser so it's a very important distinction. The processes involved are naturally complex and sugarcoating it is only going to add yet another layer of abstraction.

> playground

FYI there's no Playground anymore, it was removed in 5.0.0

> What if we had the pipeline decoupled and exposed and then have Babel be an opinionated set of plugins on top of this, but still allow for lower level flexibility for the other cases and playground stuff.

Batteries included is an extremely good approach and one that is undervalued by a majority of people.

> Babel dev would have better focus on just working on the plugins for spec compliancy instead of dealing with pipeline issues, and the pipeline dev would get better focus as well.

Unsure what you mean by this, can you elaborate please?

**Comment by stagas** [comment]
> Plugins will eventually have the ability to plug into the parser so it's a very important distinction. The processes involved are naturally complex and sugarcoating it is only going to add yet another layer of abstraction.

I'm actually talking about desugaring and removing a layer of abstraction because it is leaky the way it is implemented right now.

> Batteries included is an extremely good approach and one that is undervalued by a majority of people.

Agree totally, I'm not talking changing end user API, just architecting the internals in bottom up way that allows flexibility.

Let me try to elaborate a bit. Looking at the source code more closely, I see two projects; one is an AST transformation pipeline, and one is a set of transforms that produce ES6->ES5 transformations. Because currently the pipeline is too coupled, it is leaky, meaning you have cases where you need to introduce declarative options for the end user to manipulate its internals (white/blacklist, optional, etc) and there will always be cases where people need a workflow not predicted, meaning introducing more configuration options for more internals manipulation. So, clearly, as an abstraction it fails to achieve its goal which is to hide these away.

Instead, the pipeline could live as a separate project, have a clearly defined API by itself, where a user imperatively could use the workflow they need to produce the output they need, without having to bug the Babel project, which should primarily be focusing on producing the set of transforms for spec ES6->ES5 transformations plus offering a sugary API that *uses* the pipeline in an opinionated way, batteries included and stuff.

**Comment by sebmck** [comment]
> I'm actually talking about desugaring and removing a layer of abstraction because it is leaky the way it is implemented right now.

Do you have a specific proposal in mind? It's unclear without examples about the structure and the specific abstraction you have in mind.

> Let me try to elaborate a bit. Looking at the source code more closely, I see two projects; one is an AST transformation pipeline, and one is a set of transforms that produce ES6->ES5 transformations.

> Because currently the pipeline is too coupled, it is leaky, meaning you have cases where you need to introduce declarative options for the end user to manipulate its internals (white/blacklist, optional, etc)

The pipeline is certainly not coupled. Unsure what you mean specifically by this, there is no ES6 transformer logic inside the traversal or node replacement mechanisms.

Whitelist/blacklist/optional are just ways to turn off and on transformers. Unsure how that is leaky since the entire intention is to expose them since they're fundamentally an intentional piece of public API.

> there will always be cases where people need a workflow not predicted, meaning introducing more configuration options for more internals manipulation.

You can disable any of the transformers as well as add your own, unsure what use-cases these don't cover. This is the same approach taken by ESLint, to much praise.

> So, clearly, as an abstraction it fails to achieve its goal which is to hide these away.

What if the intention isn't to hide these away? Unsure what you're proposing. The only thing that is exposed to the enduser is the existence of transformers and the fact that they can toggle them on and off. This is pretty powerful and I'm unsure why you think it's a good idea to remove them or what to replace them with?

> Instead, the pipeline could live as a separate project, have a clearly defined API by itself, where a user imperatively could use the workflow they need to produce the output they need, without having to bug the Babel project, which should primarily be focusing on producing the set of transforms for spec ES6->ES5 transformations plus offering a sugary API that uses the pipeline in an opinionated way, batteries included and stuff.

I don't think you understand what Babel is then. Babel isn't just an ES6 transpiler, it's an entire transformation platform. I know it just sounds like buzzwords but it's difficult to explain to people that Babel is more like the Closure Compiler (or will be) than it is like Traceur.

**Comment by stagas** [comment]
> Babel isn't just an ES6 transpiler, it's an entire transformation platform.

Exactly. I'm suggesting we expose the transformation pipeline in a formal and clean way, instead of a set of configuration options. It's leaky because we attempt to hide the internals but then expose configuration options to manipulate their behavior, instead it could look like this:

```js

import TransformPipeline from 'babel-transform-pipeline';
import ts from 'babel-transformers';

let internal = new TransformPipeline;

internal.add(ts.internal.strict);
internal.add(ts.internal.validation);
// ...

export var es6 = new TransformPipeline;

es6.add(ts.es6.arrowFunctions);
es6.add(ts.es6.blockScoping);
es6.add(ts.es6.classes);
// ...

export var es7 = new TransformPipeline;

es7.add(ts.es7.classProperties);
es7.add(ts.es7.trailingFunctionCommas);
es7.add(ts.es7.asyncFunctions);
// ...

export var babel = new TransformPipeline;

babel.add(internal);
babel.add(es6);
babel.add(es7);
// ...

// implementing whitelists/blacklists/stage/deprecated etc
// a .use() method could run before every transform passing
// the transform instance to it and expecting to return
// a transform instance
babel.use(filter(whitelist));
babel.use(filter(stage));

function filter(fn) {
  return function(t) {
    if (fn(t)) return t;
    else return noop;
  };
}

function whitelist(t) {
  return ~options.whitelist.indexOf(t.name);
}

function stage(t) {
  return t.metadata.stage >= options.stage;
}

// want to implement a transform that depends on some other
// transforms running before or after it:
var p = new TransformPipeline;

p.add(ts.es6.arrowFunctions);
p.add(myTransform);
p.add(ts.es7.asyncFunctions);

export var transform = p;
```

A `Transform` and a `TransformPipeline` both implement `.transform()` exactly the same way. This way you can mix and match any pipeline and transforms in a new pipeline and achieve any workflow combination. Basically what is happening in `transformation/*` but exposed instead of hidden+configuration.

So instead of a user doing:

```js
babel.transform(code, {
  whitelist: ['es6.arrowFunctions', 'es6.blockScoping'],
  optional: ['runtime']
});
```

could be like:

```js
babel() // returns a TransformPipeline
.add(es6.arrowFunctions) // .add returns this
.add(es6.blockScoping)
.add(runtime)
.transform(code);
```

**Comment by sebmck** [comment]
I do not see what benefit pulling everything out brings other than a more complicated release and development cycle as well as making it harder for users to use and compose.

**Comment by stagas** [comment]
There's already a pipeline, it's `TransformerPass`. I'm suggesting we clean it up, enhance it and expose it in a composable way, instead of a `canTransform()`, have a `use()` add middleware, then reimplement these things as middleware in the pipeline. Pre/post/enter/exit hooks, stage etc can be implemented there. From the user perspective, nothing needs to change, but anyone wanting to do more advanced stuff can now do so. And I think it will actually make development cycles faster as now all these bits and pieces manipulating the pipeline are everywhere instead of being in one place.

**Comment by sebmck** [comment]
> There's already a pipeline, it's `TransformerPass`. I'm suggesting we clean it up, enhance it and expose it in a composable way

What you're proposing isn't in any way synonymous with a `TransformerPass`. `TransformerPass` instances are wrappers around a `Transformer` that are bound to a `File`. What you're proposing is a `TransformerPipeline` that controls a set of `Transformers` and compiles `File`s.

> instead of a `canTransform()`, have a `use()` add middleware, then reimplement these things as middleware in the pipeline.

`canTransform` is a private API so I'm not sure how this is relevant to what's exposed to userland?

> Pre/post/enter/exit hooks, stage etc can be implemented there. From the user perspective, nothing needs to change, but anyone wanting to do more advanced stuff can now do so

Possibly. I need to change the API anyway to allow asynchronous and multi-file transformations but also want to expose a synchronous single-file API so I need to think of a way to compose it.

> And I think it will actually make development cycles faster as now all these bits and pieces manipulating the pipeline are everywhere instead of being in one place.

I don't understand how having bits and pieces everywhere instead of one place is somehow a benefit? Sounds counter intuitive, having to crawl through the codebase to find a specific piece of logic seems irritating.

**Comment by stagas** [comment]
> What you're proposing isn't in any way synonymous with a TransformerPass. TransformerPass instances are wrappers around a Transformer that are bound to a File.


transformer-pass.js:
```js
/**
 * This class is responsible for traversing over the provided `File`s
 * AST and running it's parent transformers handlers over it.
 */
```
This sounds like a pipeline entry running transformers on a file's AST. But because there isn't a separate pipeline class, the handler stack is invoked in `File`. You call it a wrapper, fine, it's the entry point of a pipeline's job though.

> I don't understand how having bits and pieces everywhere instead of one place is somehow a benefit? 

I'm actually saying the opposite. The pipeline concerns are now split in these files `transformation/index.js`, `transformation/transformer.js`, `transformation/transformer-pass.js` and `transformation/file/index.js` (maybe more) that each one do a piece of the pipeline. I'm saying we have a pipeline class, move the stuff that are pipeline behavior out of these files into that one, and have it somewhere exposed so people can build, mix, match pipeline behavior without having to resort to whitelists and blacklists, optional and whatnot. `canTransform` is perfectly great, but if you look closely it's doing multiple `.filter(fn)`'s on the transforms stack. Having the pipeline a separate class will allow building behavior like this and more complex stuff(like async pipeline) in a much cleaner, composable and easier way. Am I making sense?

**Comment by sebmck** [comment]
Ok so I've implemented something similar/the same to what you suggested but with a slightly different API since the connect-like one isn't very descriptive and feels pretty wonky IMO. The way `transform` is exported is slightly wonky due to requiring backwards compatibility. See [transformation/index.js](https://github.com/babel/babel/blob/master/src/babel/transformation/index.js) for the actual code.

Unsure how this is going to factor into the bundler API that I need to work out so I'm not going to document it as a public API but it feels a lot cleaner. Thanks for the suggestion :)

**Comment by sebmck** [comment]
Closing as the issue originally raised has been addressed.
