### ISSUE TITLE
[Bug]: unhandled promise rejection type error undefined is not an object evaluating this$msg.stts.code

### ISSUE THREAD

**Issue by PrathyushaKadiri** [babel/babel#13255]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
var setPrototypeOf = require("./setPrototypeOf");

var isNativeReflectConstruct = require("./isNativeReflectConstruct");

function _construct(Parent, args, Class) {
  if (isNativeReflectConstruct()) {
    module.exports = _construct = Reflect.construct;
  } else {
    module.exports = _construct = function _construct(Parent, args, Class) {
      var a = [null];
      a.push.apply(a, args);
      var Constructor = Function.bind.apply(Parent, a);
      var instance = new Constructor();
      if (Class) setPrototypeOf(instance, Class.prototype);
      return instance;
    };
  }

  return _construct.apply(null, arguments);
//Giving error here
}

module.exports = _construct;
```

### Current and expected behavior

should not give any error

### Environment

babel version : ^7.9.6
Node Vesrion: v15.12.0

**Comment by PrathyushaKadiri** [comment]
node_modules/react-native/node_modules/@babel/runtime/helpers/construct.js 


This is the file locations which we are getting the this issue.

**Comment by nicolo-ribaudo** [comment]
The code you posted (which is a Babel runtime helper) doesn't contain any reference to `this$msg.stts.code`. That helper is used to compile classes: can you share the input and compiled code of the class in your sources that is giving problems?
