### ISSUE TITLE
[Bug]: Documentation for `allowArrayLike` is confusing/misleading

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [babel/babel#13257]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
let [a, ...b] = document.querySelectorAll("img.big");
for (let i of document.querySelectorAll("img.big"));
[...document.querySelectorAll("img.big")];
```

### Configuration file name

babel.config.js

### Configuration

Targeting IE11 and modern browsers.

### Current and expected behavior

The documentation for plugins `@babel/transform-destructuring`, `@babel/transform-for-of` and `@babel/transform-spread` says that the primary use case for `allowArrayLike` is to allow the transforms to work on iterables like DOM collections.

However, the transforms work just fine on iterables with `allowArrayLike: false`, even on older browsers like IE11 as long as `Symbol.iterator` support has been polyfilled, as they hit the check in helper function `_iterableToArray()`.

The exception is that loose transforms must be disabled for `@babel/transform-destructuring` and `@babel/transform-spread` - but for this use case there's no difference between `loose: true, allowArrayLike: true` and `loose: false, allowArrayLike: false`.

So `allowArrayLike` is only really useful for array-likes that aren't iterables, which the documentation says it is not spec compliant for spread/destructuring/for-of to work on in the first place.

### Environment

```
@babel/cli: 7.13.16
@babel/core: 7.14.0
@babel/preset-env: 7.14.1
```

### Possible solution

The documentation for `allowArrayLike` should not mention DOM collections as a use case, as the option has no effect on whether the transforms work on them.

The documentation for `loose` in `@babel/transform-destructuring` and `@babel/transform-spread` could be extended to clarify that enabling loose transforms will break spread/destructuring on DOM collections (though personally I'd prefer if setting `loose: true` on `@babel/preset-env` didn't enable these loose transforms in the first place, as they break a common use case - the other loose transforms seem far less problematic to me).

### Additional context

I hope this report is formatted reasonably, as I wasn't sure how to go about reporting a documentation issue.
Documentation links:
https://babeljs.io/docs/en/babel-plugin-transform-destructuring
https://babeljs.io/docs/en/babel-plugin-transform-for-of
https://babeljs.io/docs/en/babel-plugin-transform-spread

**Comment by JLHwung** [comment]
Thanks for the report. We just updated the docs on loose mode. It will take minutes to build but you can preview it here: https://deploy-preview-2502--babel.netlify.app/docs/en/babel-plugin-transform-spread

If you are using Babel 7.13, you can migrate to the top level assumption `arrayLikeIsIterable`. I think the new assumption name conveys the intention of `allowArrayLike`.

**Comment by ehoogeveen-medweb** [comment]
Thanks for the quick reply, that does look like what I want! However it looks like putting `loose: true` in the options for `@babel/preset-env` overrides the global assumption (it doesn't act like setting `allowArrayLike: true` in the individual plugins), so I'll have to set the global assumptions individually instead.

**Comment by ehoogeveen-medweb** [comment]
I went through the list of assumptions and I think everything is set the way I want now, thanks!

@JLHwung One thing I noticed: the text for `mutableTemplateObject` is identical to the text for `ignoreToPrimitiveHint`, is that intended?

**Comment by JLHwung** [comment]
@ehoogeveen-medweb Good catch! That is a docs bug.
