### ISSUE TITLE
Improving es5 generated code to not reassigning props

### ISSUE THREAD

**Issue by mahmood-sajjadi** [babel/babel#13251]
### 💻

- [x] Would you like to work on this feature?

### What problem are you trying to solve?

Bavel grater code is using _createClass function which for every new instance looping on an array of props and reassigning it to OBJ.prototypes
for big objects and projects which has lots of object instances, it is slow and problematic but could be avoided by defining the props only once
for example this code:
```
class Test {
  constructor() {
    this.m = 10;
  }
  abc() {
    return this.m;
  }
}
```

will be transpired to 
```
"use strict";

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Test = function () {
  function Test() {
    _classCallCheck(this, Test);

    this.m = 10;
  }

  _createClass(Test, [{
    key: "abc",
    value: function abc() {
      return this.m;
    }
  }]);

  return Test;
}();
```

which is equivalent to 
``` 
"use strict";

var _createClass = function() {
    function defineProperties(target, props) {
        for (var i = 0; i < props.length; i++) {
            var descriptor = props[i];
            descriptor.enumerable = descriptor.enumerable || false;
            descriptor.configurable = true;
            if ("value" in descriptor) descriptor.writable = true;
            Object.defineProperty(target, descriptor.key, descriptor);
        }
    }
    return function(Constructor, protoProps, staticProps) {
        if (protoProps) defineProperties(Constructor.prototype, protoProps);
        if (staticProps) defineProperties(Constructor, staticProps);
        return Constructor;
    };
}();

function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}

var Test = function() {
    function Test() {
        _classCallCheck(this, Test);
        this.m = 10;
    }

    return Test;
}();

_createClass(Test, [{
    key: "abc",
    value: function abc() {
      return this.m;
    }
}]);
```

As you can see I just need to move the `_createClass` call from inside of the `Test` function to outside and then this function will get called once per object type not once per instance.

As a second improvement, originally it was required for the descriptor to be `configurable` and `writable` as we were rewriting the property for every instance.
but in this new structure, it can be `configurable: false, writable: false`. it will give an opportunity to have some sort of control over transpiled code (if required). for example, make sure that in the generated library (npm package for example) no one will be able to override the specific property or delete it.

### Describe the solution you'd like

It would be nice to call `_createClass` once per type and not once per instance.

and also as a second improvement have control over descriptor for configurable and writable.

### Describe alternatives you've considered

I can't think of any other alternatives other than not using classes and define the object and factory functional from scratch, in this case, the code will not be generated by babel and we have more control over it.

### Documentation, Adoption, Migration Strategy

I think this solution is fully backward compatible.

**Comment by nicolo-ribaudo** [comment]
`_createClass` is already invoked only once: it's inside an immediately invoked function, not inside the constructor. Your alternative output is functionally identical, but it has the drawback that it prevent three-shaking of unused classes.
