### ISSUE TITLE
Node Require hook loading is slow (13 seconds)

### ISSUE THREAD

**Issue by friday** [babel/babel#1326]
This line of code takes 13429ms for me to execute:
```javascript
require("babel/register")({ extensions: [".es6"] });
```
I recently updated to 5.1.11. In 4.7.16 it took 8 seconds. I've been using both with Node 0.10.33

Any suggestions on what I could do? Help to debug? This actually isn't when it's transpiling my es6 files (which is really fast).

**Comment by sebmck** [comment]
Add the environment variable `NODE_DEBUG=babel`. So if you run `$ node app.js` then run `$ NODE_DEBUG=babel node app.js`. This will dump some timing information so you can see where the bottlenecks are and what files are actually being transpiled.

**Comment by sebmck** [comment]
Also please see the README:

>  For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
