### ISSUE TITLE
Support a flag to optimize out export hoisting

### ISSUE THREAD

**Issue by realduolaf** [babel/babel#13278]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I want to reduce the output code size. When I write this in a source file:
```js
// source
export const a = 1;
```
I will get this:
```js
// target
"use strict";

exports.__esModule = true;
exports.a = void 0;
const a = 1;
exports.a = a;
```
Could I reduce the `exports.a = void 0;` in every file?

By the way
-  for some reasons, I didn't use bundle tools like webpack.
- I found this [link](https://stackoverflow.com/questions/54428255/how-do-i-prevent-babel-from-emitting-export-declarations-twice).

### Describe the solution you'd like

Add flag such as `--optimize-out-export-hoisting` to optimise out export hoisting when not needed.

### Describe alternatives you've considered

Could someone provide a feasible solution?

**Comment by fedeci** [comment]
I can work on this.

**Comment by nicolo-ribaudo** [comment]
We need to come up with a name:
- This assumption would be more general than just "I don't have circular dependencies"
- This is about observing own properties of uncomplete module namespace objects
- I don't have a good name idea :sweat_smile:

**Comment by JLHwung** [comment]
Naming is hard, maybe `accessCjsExportsAfterInitialized` ?

> can be enabled by default in files without `import` statements?

Agreed, but should we also check `import()`, even `require()`? We could come up with better defaults later.

**Comment by nicolo-ribaudo** [comment]
> `accessCjsExportsAfterInitialized`

`ns.foo` would still have the correct behavior even if you access it _before_ that it's initialized (it returns `undefined`). The only difference with this assumption is that `Object.prototype.hasOwnProperty.call(ns, "foo")` would return `false`.

**Comment by JLHwung** [comment]
Good point. In that case maybe noBrandCheckCjsExportsBeforeInitialized?

**Comment by realduolaf** [comment]
Cool guys. I will continue to pay attention and learn from it. 👍
