### ISSUE TITLE
Injecting class properties with plugin API

### ISSUE THREAD

**Issue by lukescott** [babel/babel#1327]
I'm writing a plugin that attaches a static "_className" property to each class. The goal is to be able to resolve the name no matter what (after uglify, or in IE). The plugin is here: https://github.com/webconnex/babel-plugin-class-name/blob/master/index.js

So far it "works" on build (using gobble-transform) but fails as soon as I run it thru mocha. This is the error I get:

```
Line 0: Key conflict with sibling node
```

(I added `loc: {start:{line: 0}},` to get the error to display)

And the class looks like this:
```javascript
class Node {
    constructor() {
        console.log(this.constructor._className);
    }
}
```

The error only occurs with the console.log. I'm assuming this is because of source maps.

This probably is something I shouldn't be doing, so this is possibly a feature request. The reason for me doing it is I don't want to rely on runtime methods.

**Comment by sebmck** [comment]
Seems to work fine for me? Do you have steps to reproduce?

**Comment by lukescott** [comment]
Ok, looks like this was caused by another issue of babel loading my plugin twice, which I bypassed incorrectly. Will open a separate issue for that.

@sebmck does plugin code look correct? Is there a nicer way to do it?
