### ISSUE TITLE
Helpers can collide with local bindings

### ISSUE THREAD

**Issue by wolframkriesing** [babel/babel#1328]
I looked at the resulting code and was curious if the `_extends` that gets created also gets renamed if I create an identifier with the same name, it works when it's all on the root level, but inside a function it seems to fail.
```
it('', () => {
  const _extends = {};
  const obj = {...obj};
});
```
transpiles to this
```
var _extends = 'lots of code ....';

it('', function () {
  var _extends = {};
  var obj = _extends({}, obj);
});
```
which would use my `_extends`, which I think is not intended, right?

see [example repl](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=it(''%2C%20()%20%3D%3E%20%7B%0A%20%20const%20_extends%20%3D%20%7B%7D%3B%0A%20%20const%20obj%20%3D%20%7B...obj%7D%3B%0A%7D)%3B)

**Comment by sebmck** [comment]
Local bindings aren't checked for collisions with injected helpers. I'm ambivalent to this, I'll have to think of a clean way to do this.

**Comment by wolframkriesing** [comment]
what about moving the helper into the local scope too
would only require the same logic to have applied, right?
It would cause (possibly lots) of duplication of the helpers
though ...

--
Kind regards / Saludos / Mit freundlichen Grüßen
Things we think are important http://www.uxebu.com/universe/
Meet uxebus at http://www.uxebu.com/about-us/events/

Wolfram Kriesing, CTO
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by sebmck** [comment]
Then there's no point in having the helpers at all.

**Comment by timoxley** [comment]
> I'll have to think of a clean way to do this.

Symbols?

**Comment by sebmck** [comment]
How are symbols relevant at all?

**Comment by RReverser** [comment]
@sebmck Maybe just prefix all the helpers with `_babel_`? Not a 100% solution, but should help for all the cases except when people try to intentionally collide with helper names.

**Comment by sebmck** [comment]
Easier to either:

 - Be cheeky and rewrite all user bindings beginning with `_`.
 - Collect all nested local bindings on the top level scope so collisions can be checked.
