### ISSUE TITLE
[Bug]: Class Private Fields/Accessors/Methods must not be re-initialized on instance

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#13299]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

(See "Prevent private class members from being added more than once" section in https://github.com/evanw/esbuild/releases/tag/v0.11.20#:~:text=Prevent%20private%20class%20members%20from%20being%20added%20more%20than%20once)

```js
class Base {
  constructor(obj) {
    return obj;
  }
}

let counter = 0;
class Derived extends Base {
  #foo = ++counter;
  static get(obj) {
    return obj.#foo;
  }
}

const foo = {};
new Derived(foo);
assert.equals(Derived.get(foo), 1);

// This should throw an error, private fields must not be re-initialized
// on an object that already contains the field.
assert.throws(() => {
  new Derived(foo);
});
// ^ That should have thrown, but it doesn't.

// Must not re-initialize the field
assert.equals(Derived.get(foo), 1);
// But the counter is incremented (the initializer runs, but the field
// should not re-add)
assert.equals(counter, 2);
```

[REPL](https://babeljs.io/repl/#?browsers=Chrome%2075&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBCkFNoG8BQ1rAPYDsIBcAnAV2Hy0IAosAjAKwEoV0NpCF9jCdpa6BuFgF9UI1CA6YsxHPgSFoAXmgAGQaEgwAIvICWANwQATaAgAecnEZjwISNBgDEAMyxYl0ANSfsMuYUEMAjB8XWBoAHMOanomB1Z2Tm5eegA6FzdA6BExbDx8aFd3ZWQhQRwEAHdoHUIDY0oihkFNeXxUhABHYjAQCEpa-qNUqPxGtwYAGmgARmbUVAB6RegAFQALXRgIdekQE3x1wixqsB55Y8JpgAc6_RCkZ10EfZgAW2ICaBwsApokdgAWl0OF0oV6ugAXsYlitcNAzik6AgyNBDiEESB2GAjABPKSyMAgmCHR7PfapVCtQjtQ7HSr9ShMRQAPmYGAq1UGhiM4yw8yE82W0AAemt1hidnsTBLDGijiccNMaMQCmDoEYsAgIDgAOTtBbCgCynwKPwKQJBYN0EOh8rJLyMVKgbQ63V6_W5xhG0Sa0zmgmFsFV9qkfnk0C2kZwwHYbwQsmM0EopOj1ttEZIeGVIdTT0dsOgUuI-2-vzYCEBOKMDGddhpbp6fUovkTV2gACZmkA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.14.1&externalPlugins=)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "shippedProposals": true,
        "targets": {
          "chrome": "75"
        }
      }
    ]
  ]
}
```

### Current and expected behavior

Currently, this will re-initialize the field `#foo`, but this is incorrect. It should throw an error when trying to initialize the field a second time.

### Environment

- Babel version: v7.14.1

### Possible solution

We should create new `initializePrivateFieldSpec`, `initializePrivateAccessorSpec`, and `initializePrivateMethodSpec` ~~(and `static` versions)~~ [helpers](https://github.com/babel/babel/blob/main/packages/babel-helpers/src/helpers.js) to initialize the field to a descriptor. Inside the helpers, we should check if the `WeakMap`/`WeakSet` that represents the transformed field already contains the `instance` key. If so, throw. Else, initialize.

Or, we could just have a simple `checkPrivateFieldInitSpec` which does the check, but doesn't initialize. We'd then call the `check` before initializing a field.

After creating the helpers, we should call them in the appropriate place in https://github.com/babel/babel/blob/main/packages/babel-helper-create-class-features-plugin/src/fields.js (look for any function that ends in "InitSpec").

### Additional context

This is a medium difficulty issue, so could be tackled by someone with a little experience making changes to Babel.

**Comment by nicolo-ribaudo** [comment]
I prefer the `checkPrivateFieldInitSpec` idea because:
1. We need a single function both for private fields and private methods, since it would use the `.has` method defined both on `WeakMap` and `WeakSet`
2. It's self-contained, so it would be easier to potentially introduce an `noPrivateReinitialization` assumption to omit it (since 99.99% of the apps won't probably need this check).

**Comment by jridgewell** [comment]
One specific item with `checkPrivateFieldInitSpec`. We still have to run the initializer, but it has to fail when trying to reset the field:

```js
// From OP, the very last line
assert.equals(counter, 2);
```

If we go with `checkPrivateFieldInitSpec`, we'll have code that looks a bit like:

```diff
class Derived extends Base {
  constructor() {
    const _this = super();
-    _foo.set(_this, { value: ++counter }); 
+    _foo.set(_this, (desc = { value: ++counter }, checkPrivateFieldInitSpec(_this, _foo), desc)); 
  }
}

const _foo = new WeakMap();

**Comment by nicolo-ribaudo** [comment]
It could also be something like this:
```js
_foo.set(_this, _checkPrivateFieldInitSpec(_this, _foo, { value: ++counter });
```
where `_checkPrivateFieldInitSpec` is
```js
function _checkPrivateFieldInitSpec(obj, collection, value) {
  if (collection.has(obj)) throw new TypeError();
  return value;
}
```

And for methods:
```js
_checkPrivateFieldInitSpec(_this, _foo), _foo.add(_this);
```

**Comment by mdaj06** [comment]
could i help here?

**Comment by nicolo-ribaudo** [comment]
Yes!



If it is the first time that you contribute to Babel, you can follow these steps: (you need to have `make` and `yarn` available on your machine)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build`/`yarn gulp build` whenever you change a file). When updating `@babel/helpers`, I'm not 100% sure that `make watch` works.
1. Add a test (only `exec.js` and/or `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest [name-of-the-package-to-test]` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by nicolo-ribaudo** [comment]
Could you implement the `initializePrivateFieldSpec`/`initializePrivateMethodSpec` version?

**Comment by mdaj06** [comment]
sure i can try it out

**Comment by jridgewell** [comment]
@mdaj06: Hope the implementation is going well, please ping if you have any questions!

**Comment by nicolo-ribaudo** [comment]
Hi @mdaj06! Are you still working on this?

**Comment by mdaj06** [comment]
Yes @nicolo-ribaudo! Got a bit side-tracked in the past few weeks.

**Comment by komyg** [comment]
Hi,

I would like to help out if stuck somewhere.

Thanks,
Komyg

**Comment by mdaj06** [comment]
sure @komyg  you can take it up , i havent gotten a chance to really work on it in the past few weeks.

**Comment by komyg** [comment]
Thanks, I will start working right away

**Comment by komyg** [comment]
Hi @nicolo-ribaudo, I saw that the link in the readme file is broken. I tried to search for it in the documentation, but I haven't found it:

```md
[@babel/helper-create-class-features-plugin](https://babeljs.io/docs/en/babel-helper-create-class-features-plugin)
```

If you pass me the right link, I can update it as a part of this PR.

**Comment by nicolo-ribaudo** [comment]
Uh, that link is auto-generated and unfortunately I think we don't have docs for that internal package :sweat_smile:

**Comment by komyg** [comment]
Hi @nicolo-ribaudo, 

I think that the generated code should look somewhat like this:

```js
'use strict';

function _classPrivateFieldGet(receiver, privateMap) {
  var descriptor = _classExtractFieldDescriptor(receiver, privateMap, 'get');
  return _classApplyDescriptorGet(receiver, descriptor);
}

function _classExtractFieldDescriptor(receiver, privateMap, action) {
  if (!privateMap.has(receiver)) {
    throw new TypeError(
      'attempted to ' + action + ' private field on non-instance'
    );
  }
  return privateMap.get(receiver);
}

function _classApplyDescriptorGet(receiver, descriptor) {
  if (descriptor.get) {
    return descriptor.get.call(receiver);
  }
  return descriptor.value;
}

/** CHANGES HERE */
function _checkPrivateFieldInitSpec(obj, privateMap) {
  if (privateMap.has(obj)) {
    throw new TypeError();
  }
}

class Base {
  constructor(obj) {
    return obj;
  }
}

let counter = 0;

var _foo = /*#__PURE__*/ new WeakMap();

class Derived extends Base {
  constructor(...args) {
    super(...args);

    /** CHANGES HERE */
    _checkPrivateFieldInitSpec(this, _foo);
    _foo.set(this, {
      writable: true,
      value: ++counter,
    });
  }

  static get(obj) {
    return _classPrivateFieldGet(obj, _foo);
  }
}

const foo = {};
new Derived(foo);
console.log(Derived.get(foo));

new Derived(foo);
console.log(Derived.get(foo));
```

I've created this function: `_checkPrivateFieldInitSpec` and called it inside the constructor: `_checkPrivateFieldInitSpec(this, _foo);`.

The rationale being that if the private map already has a reference to the object, then we know that we've passed through the constructor, and we can consider the field initialized.

I've tested it in node, and it does throw the expected exception.

What do you think? Can I go forward with this?

**Comment by komyg** [comment]
Hi guys, just created a [draft PR](https://github.com/babel/babel/pull/13601) for this issue, so you can follow my progress if you want. 

I'll let you know once it is ready for review.

**Comment by nicolo-ribaudo** [comment]
Your example has a problem: the error is thrown _before_ evaluating `++counter`, so it's only incremented once and not twice.

We could introduce a new helper, `_privateFieldInitSpec`, called like this:
```js
    _privateFieldInitSpec(this, _foo, {
      writable: true,
      value: ++counter,
    });
```

Internally this helper would throw the error if the field is already initialized, but at least `++counter` would be evaluated before throwing.

**Comment by komyg** [comment]
I see. So based on your suggestion, I think I will create a new function:

```js
function _privateFieldInitSpec(obj, privateMap, value) {
  if (privateMap.has(obj)) {
    throw new TypeError();
  }
  privateMap.set(obj, value);
}

// [...]
constructor(...args) {
  super(...args);

  _privateFieldInitSpec(this, _foo, {
    writable: true,
    value: ++counter,
  });
}
```

Here is the full code:

```js
'use strict';

function _classPrivateFieldGet(receiver, privateMap) {
  var descriptor = _classExtractFieldDescriptor(receiver, privateMap, 'get');
  return _classApplyDescriptorGet(receiver, descriptor);
}

function _classExtractFieldDescriptor(receiver, privateMap, action) {
  if (!privateMap.has(receiver)) {
    throw new TypeError(
      'attempted to ' + action + ' private field on non-instance'
    );
  }
  return privateMap.get(receiver);
}

function _classApplyDescriptorGet(receiver, descriptor) {
  if (descriptor.get) {
    return descriptor.get.call(receiver);
  }
  return descriptor.value;
}

function _privateFieldInitSpec(obj, privateMap, value) {
  if (privateMap.has(obj)) {
    throw new TypeError();
  }
  privateMap.set(obj, value);
}

class Base {
  constructor(obj) {
    return obj;
  }
}

let counter = 0;

var _foo = /*#__PURE__*/ new WeakMap();

class Derived extends Base {
  constructor(...args) {
    super(...args);

    _privateFieldInitSpec(this, _foo, {
      writable: true,
      value: ++counter,
    });
  }

  static get(obj) {
    return _classPrivateFieldGet(obj, _foo);
  }
}

const foo = {};
new Derived(foo);
console.log(Derived.get(foo));  // 1
console.log('count', counter); // 1

try {
  new Derived(foo);
  console.log(Derived.get(foo));
} catch (err) {
  console.error(err);
}

console.log(Derived.get(foo));  // 1
console.log('count', counter); // 2
```

What do you think?

**Comment by nicolo-ribaudo** [comment]
It looks good! The new function can be created in `packages/babel-helpers/src/helpers.js`, and it can be used using the `addHelper` internal method (you can Ctrl+F for it to see how it works).

**Comment by komyg** [comment]
Hey @nicolo-ribaudo,

I've been trying to reproduce this error on Node with private static fields, but I wasn't able to. I think it is because the static fields are a part of the class itself, therefore there is no way to re-declare them.

This is an example that I came up to see if I could reproduce the error:

```js
class Base {
  constructor(obj) {
    return obj;
  }
}

let counter = 0;
class Derived extends Base {
  static #foo = ++counter;

  static getFoo() {
    return this.#foo;
  }

  static #bar() {
    return 'hello world';
  }

  static getBar() {
    return this.#bar();
  }
}

const foo = {};
new Derived(foo);
console.log(Derived.getBar());

new Derived(foo);
console.log(Derived.getBar());
```

I've ran it on Node and it works fine.

Could you help me find an example where we should throw an error for the static field re-declaration, and we are not doing so?

**Comment by nicolo-ribaudo** [comment]
I believe it's impossible to initialize static fields twice, so we only need to fix instance fields.

**Comment by komyg** [comment]
Ok, in this case, I think I am done. I've marked the PR as ready for review.

My PR covers instance properties, methods and accessor methods. Is there anything else that we should cover?

**Comment by nicolo-ribaudo** [comment]
No, it's ok :+1:

**Comment by komyg** [comment]
Great, thanks! 🙂 

I await your review then.

**Comment by jridgewell** [comment]
> I believe it's impossible to initialize static fields twice, so we only need to fix instance fields.

Correct. I was wrong in my issue description, this only applies to instance fields.
