### ISSUE TITLE
[Bug]: @babel/parser failed to release 7.14.2

### ISSUE THREAD

**Issue by dan-trewin** [babel/babel#13302]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

package.json:

```
...
"devDependencies": {
    "@babel/core": "7.14.2"
    ...
}

...

```

### Current and expected behavior

It seems that babel 7.14.2 released about 2 hours ago (<https://github.com/babel/babel/releases/tag/v7.14.2>) and it requires `@babel/parser@^7.14.2` (but that hasn't released). This is causing all `npm install` calls to fail:

<img width="567" alt="Screen Shot 2021-05-12 at 1 46 46 PM" src="https://user-images.githubusercontent.com/35882574/118028311-8c5e8300-b328-11eb-9e08-aec66531d84f.png">

### Environment

Babel version: 7.14.2

**Comment by dan-trewin** [comment]
It seems to have published right after I opened this issue -> <https://www.npmjs.com/package/@babel/parser>

Closing.

**Comment by fedeci** [comment]
Always the same npm registry cache problems🙄

**Comment by nicolo-ribaudo** [comment]
It was probably a npm bug: I tried opening https://www.npmjs.com/package/@babel/parser and it gave an ESOCKET error; at the second attempt it showed 7.14.2
