### ISSUE TITLE
[Bug]: Missing `babel/preset-flow` v7.14.x on npm

### ISSUE THREAD

**Issue by ssidorchik** [babel/babel#13300]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

n/a

### Current and expected behavior

Apologize for using the current bug template, but I didn't find a better way to report this issue.

I noticed that few babel packages: `babel/core`, `babel/parse`, `babel/preset-env` were already published with the v7.14.x version on npm. But the latest version for `babel/preset-flow` is still v7.13.13. Do you have any estimate for when it can be updated. I'm looking to use [Flow type's indexed_access feature](https://github.com/facebook/flow/commit/4b1c518b6324850d6a0bc2e75cf9cdeb935f3d41#diff-bf470ba6376d9c0dfdd5f8c6b1e28d4b446135ca5523ea3ecf45914c47d819a4R3), but it's [supported only in the latest preset version](https://github.com/babel/babel/pull/13053).

### Environment

n/a

**Comment by nicolo-ribaudo** [comment]
Sorry for the confusion: we only publish packages with changes, and all the changes needed for the new flow features are in `@babel/parser@7.14.0`. `@babel/preset-flow` is only needed to remove every flow feature, but usually it doesn't need to be updated every time.

`@babel/parser` is a dependency of `@babel/core`, so using `@babel/core^7.14.0` should be enough.

**Comment by ssidorchik** [comment]
Ohh, I see. Thank you for prompt response
