### ISSUE TITLE
[Bug]: `assumptions` specified in presets are not respected

### ISSUE THREAD

**Issue by billyjanitsch** [babel/babel#13316]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

[Here](https://github.com/billyjanitsch/babel-bug-preset-assumptions) is a minimal repro. Specifically, see [this diff](https://github.com/billyjanitsch/babel-bug-preset-assumptions/compare/208355b12945035bb6ef6b76ea3496bf5db17575...ddaa83d34086776a38df360521917028ed690fca).

Input code:

```js
export const foo = 1;
```

### Configuration file name

babel.config.js

### Configuration

This configuration works as expected:

```js
// babel.config.js
module.exports = {
  presets: ["@babel/preset-env"],
  assumptions: { enumerableModuleMeta: true },
};
```

This configuration does not:

```js
// preset.js
module.exports = () => ({
  presets: ["@babel/preset-env"],
  assumptions: { enumerableModuleMeta: true },
});

// babel.config.js
module.exports = {
  presets: ["module:./preset.js"],
};
```

### Current and expected behavior

The first configuration correctly applies the `enumerableModuleMeta` assumption, resulting in the following transpiled output:

```js
"use strict";

exports.__esModule = true;
exports.foo = void 0;
var foo = 1;
exports.foo = foo;
```

In the second configuration, the only difference is that the config has been pulled into a preset. The `assumptions` [docs](https://babeljs.io/docs/en/options#assumptions) and [RFC](https://github.com/babel/rfcs/blob/master/rfcs/0003-top-level-assumptions.md) suggest that this is allowed. However, the assumption is not applied, resulting in the following output:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = void 0;
var foo = 1;
exports.foo = foo;
```

It appears that, in general, `assumptions` specified in presets are not respected.

### Environment

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.17.0 - ~/.local/share/nvm/v14.17.0/bin/node
    npm: 7.12.0 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.13.16 => 7.13.16 
    @babel/preset-env: ^7.14.2 => 7.14.2 
```

### Possible solution

Without any knowledge of the implementation, I wonder if the issue is that the `assumptions` object receives default values before configurations get merged. So, from Babel's perspective, a value of `{ enumerableModuleMeta: false }` was implicitly "specified" in babel.config.js, taking precedence over the one in the preset. This would prevent assumptions specified anywhere other than the top-level config from being respected. Just a guess.

There does seem to be a [test case for this](https://github.com/babel/babel/blob/main/packages/babel-core/test/assumptions.js#L35-L47), though. 🤷

**Comment by nicolo-ribaudo** [comment]
This is an example showing how integration tests (or higher level unit tests) are better than low-level unit tests :grimacing:

**Comment by billyjanitsch** [comment]
Thanks for confirming! I looked at https://github.com/babel/babel/pull/12219 and couldn't easily spot the issue. I'm guessing it's one of the places where `assumptions` gets defaulted to `{}`? If it's more obvious to you and you can offer a pointer, I'm happy to work on a fix if that would be helpful, but nw if it would be easier just to fix by that point. 🙂

**Comment by billyjanitsch** [comment]
In case it helps, I was curious if this would work (setting an unrelated assumption in the top-level config, to avoid it getting a default assignment):

```js
// preset.js
module.exports = () => ({
  presets: ["@babel/preset-env"],
  assumptions: { enumerableModuleMeta: true },
});

// babel.config.js
module.exports = {
  presets: ["module:./preset.js"],
  assumptions: { noDocumentAll: true },
};
```

But it doesn't. We still get the `Object.defineProperty` call.

**Comment by nicolo-ribaudo** [comment]
I have been debugging this for one hour now and I still don't know where the problem is :grimacing: 
I _thought_ I found it 10 mins ago (we were initializing the context passed to plugins _before_ applying the presets), but even moving that initialization I still see the bug.

I think I'll find open a PR myself when I manage to fix it mostly because I cannot spot the problem so I don't know how to give you any pointer :sweat_smile:. But this is a fun bug lol

**Comment by nicolo-ribaudo** [comment]
Ok I fixed it
