### ISSUE TITLE
[Bug]: Lets collectively invoice Babel a portion of our web hosting bill 

### ISSUE THREAD

**Issue by yishengjiang99** [babel/babel#13319]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

there are 12966 files on my webserver containing the word 'babel' and 458 folders. 

I did not consent to the installation of any of them. 

This is coming from someone who actively types 'rm -rf node_module' several times a week. My hands' muscle memory subconsciously equates the cmd to to 'make things slightly better'. whenver my wife complains about toilet being clogged, I want to say 'have you tried rm -rf node_module'

but no matter what I do, the babel folders just grow like weed. even on projects where I only npm install my own packages, babel folders just appear out of thing air. (I think you have to delete babelrc too but who knows). a lot of these packages even traverses up the folder tree to include things from there. 

your decision to break down every morsel of code into its own packages and update in non-lock-step fashion just make things worse. Instead of npm trying to use same folder for multiple references. because there are different versions of each package, depending on when they are added to the project, npm has to install many different versions.

### Describe the solution you'd like

the invoice  is a small, symbolic reimbursement for my long-lost pride to call myself as a javascript developer. javascript used to be the programming language of the blue-collar programmer. we import jquery in a src tag of the index.html, and then we write rest of our code in another src tag. now we 'npm install mocha' and 200 babel packages magically appear on our computer.

now we have become a community that collectively downloads `is-binary-path` 22 million times a week? some guy had the bridge idea of listing a list of file extensions as binary path. instead of doing #define binary_path ... he had to publish an npm package. now 22 million copies of it magically appear. each one makes us every more of a laughing stock

### Describe alternatives you've considered

as Eric Cartman, screw u guys, i'm going <cross>home<cross> rewrite my latest javascript project in [c](https://github.com/yishengjiang99/render). 100% babel/sindrehus free zone in that project.

**Comment by nicolo-ribaudo** [comment]
Feel free to delete every piece of code written by us from your PC. Two things can happen:
- your app still works. Congrats, you saved a lot of memory!
- your app stops building. This means that you need all of our crap, so it's us who should send to you the invoice and not the opposite 😘

**Comment by nicolo-ribaudo** [comment]
Also, you might love this command to reduce the size of your `node_modules`: https://docs.npmjs.com/cli/v7/commands/npm-dedupe

If it helps, feel free to thank me by [sponsoring me on GitHub!](https://github.com/sponsors/nicolo-ribaudo).

**Comment by fedeci** [comment]
I would also add that the Babel LICENSE explicitly says that:
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND
