### ISSUE TITLE
Infer React displayName from class

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#1331]
[The documentation](https://babeljs.io/docs/usage/jsx/) says:

> When doing export default React.createClass({}); the displayName is inferred from the current filename.

Can we get something similar for ES6 class syntax too, based off the class name?

```
import {Component, PropTypes} from 'react';

export default class Foobar extends Component {
}
```

At the moment I need to do `Foobar.displayName = 'Foobar';` myself.

**Comment by sebmck** [comment]
Is `displayName` even necessary? Can React not get it from `Component.name`?

**Comment by Daniel15** [comment]
When my code is minified, the React dev tools are showing the minified name. I needed to add the `displayName` to get the correct name showing.

**Comment by sebmck** [comment]
Makes sense.

**Comment by jquense** [comment]
This might lead to inconsistent transformations, as React components don't need to inherit from `React.component` such as:

```js
class Box {
  render(){ return <span/> }
}
```

Which seems like you'd be forced to either add `displayName` to every class (component or not) or accept missing some. Admittedly its not a big deal to get a false negative, but I assume adding displayName to every class is probably not a good idea.

**Comment by sebmck** [comment]
@jquense Actually yeah, that's a good point. Even though `React.createClass` is special cased, there could be `class Foo extends Bar` and it's not explicitly inheriting from `React.component` and it will inherit the `displayName` of `Bar` which will obviously be wrong. @Daniel15 Thoughts?

**Comment by jridgewell** [comment]
> Even though React.createClass is special cased, there could be class Foo extends Bar and it's not explicitly inheriting from React.component and it will inherit the displayName of Bar which will obviously be wrong.

Wouldn't `class Foo extends Bar` set `Foo.displayName = 'Foo'`?

**Comment by sebmck** [comment]
@jridgewell Nope, it would only be done for `class Foo extends React.Component`. Not willing to have `displayName` set on every single class when there's `name` and not all Babel users are React/JSX ones :)

**Comment by monsanto** [comment]
If debugging minified code is important to you I recommend using a setting that does not change function names. For UglifyJS2 you can use `--keep-fnames`.

**Comment by Daniel15** [comment]
@sebmck  I think just doing it for `class Foo extends Component` would be fine, and still useful.

**Comment by bloodyowl** [comment]
as uglyfying is usually for production and that warnings & invariant call are disabled in this very mode, I think relying on `reactClass.name` is enough.

**Comment by sebmck** [comment]
I'm not really a fan of having inconsistent behaviour, ie. only adding `displayName` on classes that extend `React.Component` and the bug about child classes inheriting their parents `displayName`.

If you want this then you can use the following plugin:

```javascript
var babel = require("babel-core");
var t = babel.types;

module.exports = new babel.Transformer("react-class-display-name", {
  ClassDeclaration: function () {
    if (this.get("superClass").matchesPattern("React.Component")) {
      this.insertAfter([
        t.expressionStatement(t.assignmentExpression(
          "=",
          t.memberExpression(node.id, t.identifier("displayName")),
          t.literal(node.id.name)
        ))
      ]);
    }
  }
});
```

**Comment by EcutDavid** [comment]
THANKS
