### ISSUE TITLE
[Bug]: Unexpected reserved word when variable contains ascii

### ISSUE THREAD

**Issue by alan-agius4** [babel/babel#13323]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
let \u0275ResourceLoaderImpl_BaseFactory
```

https://babeljs.io/repl#?browsers=ie%209&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAOgrgDAJgOwFYBKIDOB7GAnAYxABlsBDAExDwEkBbAB2AH0AhMzEAMTILGzwBPIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=&version=7.14.2&externalPlugins=

### Configuration

Can be reproduced with any config included in the repl.

### Current and expected behavior

Unexpected reserved word 'let'. (1:0)

> 1 | let \u0275ResourceLoaderImpl_BaseFactory
    | ^

### Environment

  **System:**
    OS: macOS 11.2.3
  **Binaries:**
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.2/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v12.20.2/bin/npm
**Babel**
    @babel/core 7.14.0,
    @babel/preset-env: 7.14.1

**Comment by submarines-and** [comment]
If it helps anyone:

**WORKING:**
const \u0275ResourceLoaderImpl_BaseFactory = 4
let x\u0275ResourceLoaderImpl_BaseFactory
var \u0275ResourceLoaderImpl_BaseFactory
let ɵResourceLoaderImpl_BaseFactory

So seems to only be an issue with "let" + first char being escaped unicode

**Comment by nicolo-ribaudo** [comment]
This actually used to work in the past: it has been broken in 7.4.0
