### ISSUE TITLE
[Bug]: Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose'

### ISSUE THREAD

**Issue by aatifbandey** [babel/babel#13320]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

With react and @loadable/components

### Input code

I am facing an issue when i try to build via webpack, I am using webpack 5

Issue
`Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose`

Current version 
`@babel/runtime: 7.13.17"

### Configuration file name

babel.config.js

### Configuration

```
module.exports = {
  
  presets: [
      ['@babel/preset-env',{
        
          "loose": true,
          "shippedProposals": true
        }
      ], '@babel/preset-react'],
  plugins: [
    '@loadable/babel-plugin',
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-object-rest-spread', { useBuiltIns: true }],
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-transform-destructuring', { useBuiltIns: true }],
    ['@babel/plugin-transform-runtime', { helpers: false, regenerator: true }],
  ],
};
```

### Current and expected behavior

-

### Environment

- Babel verions: 7.13.1
- Node: 16.0.0

**Comment by nicolo-ribaudo** [comment]
(Sorry, I had a bit of fun writing this answer in a game-like way :grimacing:)

1. Does `@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js` exist in your `node_modules`?
   - **YES**: Go to 2
   - **NO**: Go to 3
1. Does `@babel/runtime/package.json` have a mapping in `"exports"` to map `./helpers/esm/objectWithoutPropertiesLoose` to `./helpers/esm/objectWithoutPropertiesLoose.js`?
   - **YES**: This is a Webpack resolution bug, or a bug in your webpack configurations that makes its resolution stop working.
   - **NO**: Which is the `@babel/runtime` version? Please make sure that you are using the latest one.
3. Check in the error message which package is requiring `@babel/runtime/helpers/esm/objectWithoutPropertiesLoose`: does it have `@babel/runtime` in the `"dependencies"` field of its `package.json`?
   - **YES**: It's a bug in that package, it should correctly specify its dependencies. Please report the issue to them!
   - **NO**: I have no idea about what is going on, try deleting `node_modules` and reinstalling it again. If it still doesn't work, we'll need a repository which reproduces the issue.
