### ISSUE TITLE
[Bug]: TSLiteralType should accept UnaryExpression

### ISSUE THREAD

**Issue by alexandre-cai** [babel/babel#13327]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

See REPL: https://runkit.com/alexandre-cai/60a2ae9feaab4400130133c8

```js
transform(`
  type Test = 1 | -1;
`, {
  parserOpts: {
    plugins: ["typescript"],
  },
  plugins: [
    ({ types: t }) => ({
      visitor: {
        TSLiteralType(path) {
          path.node = t.tsLiteralType(path.node.literal)
        }
      }
    }),
  ],
})
```

### Current and expected behavior

Babel currently accepts UnaryExpression while parsing TSLiteralType, but can’t generate one. Output: 
```
TypeError: unknown: Property literal of TSLiteralType expected node to be of a type 
["NumericLiteral","StringLiteral","BooleanLiteral","BigIntLiteral"] but instead got "UnaryExpression"
```

### Environment

- @babel/core: 7.14.2

### Possible solution

https://github.com/babel/babel/blob/main/packages/babel-types/src/definitions/typescript.ts#L342
Add `UnaryExpression`.

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report!
The accepted type should be:
- one of `"NumericLiteral","StringLiteral","BooleanLiteral","BigIntLiteral"`
- or a `UnaryExpression` whose argument is one of `"NumericLiteral","StringLiteral","BooleanLiteral","BigIntLiteral"`.

It can be implemented by replacing https://github.com/babel/babel/blob/main/packages/babel-types/src/definitions/typescript.ts#L342 with a custom validator, similarly to https://github.com/babel/babel/blob/9d620c2d423cec4cf5d555d4b8884288068bd17d/packages/babel-types/src/definitions/core.ts#L659.

**Comment by alexandre-cai** [comment]
I think `UnaryExpression` should only accept `NumericLiteral` and `BigIntLiteral` with an operand of `-`.

**Comment by Patil2099** [comment]
@nicolo-ribaudo I would love to help in fixing this issue. I am new to this project. Can you guide me a little more on closing this issue? Thanks!

**Comment by nicolo-ribaudo** [comment]
@Patil2099 You follow these steps: (you need to have `make` and `yarn` available on your machine)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add one or more tests in https://github.com/babel/babel/tree/main/packages/babel-types/test/builders/typescript
1. Update the code!
1. `yarn jest babel-types` to run the tests
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by tony-go** [comment]
Hi 👋 

Is this issue always available ?

**Comment by nicolo-ribaudo** [comment]
@tony-go Let's give @Patil2099 a few more days to work on this. If @Patil2099 doesn't reply within Wednesday, you can work on this.

As an alternative, if you prefer I opened https://github.com/babel/babel/issues/13399.

**Comment by tony-go** [comment]
Hey @nicolo-ribaudo 

Yeah for sure ! ✌🏼

**Comment by nicolo-ribaudo** [comment]
@Patil2099 Hi! Are you still working on this?

**Comment by lala7573** [comment]
Is this issue available? I'd like to try this one.
