### ISSUE TITLE
babel-runtime version is not checked at runtime

### ISSUE THREAD

**Issue by AgentME** [babel/babel#1332]
This is in the changelog for 4.7.0:

* Throw an error on different babel and babel-runtime versions.

but it seems like this check isn't done at runtime, which misses what I'd assume would be the common failure case: a babel-transpiled library (using the runtime transform) could be published to NPM, reference babel-runtime as a dependency, but accidentally specify a version range for it (using ^, etc) instead of pinning the specific version that corresponded to the version of babel used to compile the library before it was published onto NPM.

**Comment by sebmck** [comment]
See #1266.

**Comment by AgentME** [comment]
Oh, good to hear! I didn't realize that changed. I was going to follow up with another issue that the documentation doesn't mention this exact-version-match requirement anywhere, but the requirement not actually still existing now simplifies things.
