### ISSUE TITLE
[Bug]: Babel does not add parens around number followed by `.` when `minified: true`

### ISSUE THREAD

**Issue by zcarde** [babel/babel#13330]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const babel = require('@babel/core');
let tranformed = babel.transformSync("1000000000000000128.0.toFixed(0)!==\"1000000000000000128\"", {
    comments: false,
    minified: true
});
```

### Current and expected behavior

Minified float number is modified when float is larger than max integer
Babel should not modify the float value

Minified code: 1000000000000000100 .toFixed(0)!=="1000000000000000128";
Expected minified code: 1000000000000000128.0.toFixed(0)!=="1000000000000000128";

### Environment

```
System:
    OS: macOS 10.15.7
Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v12.1.0/bin/npm
npmPackages:
    @babel/core: 7.12.x => 7.12.17 
    @babel/preset-env: 7.12.x => 7.12.17
```

**Comment by nicolo-ribaudo** [comment]
`1000000000000000128.0` and `1000000000000000100` have the same runtime behavior, so Babel can safely replace one with the other. You can verify it in your browser's console:
```js
1000000000000000128.0 === 1000000000000000100; // true
1000000000000000128.0.toFixed(0) === "1000000000000000128"; // true
(1000000000000000100).toFixed(0) === "1000000000000000128"; // true
```

If you need to use large integers with more precision I suggest using BigInts instead of floats.

**Comment by zcarde** [comment]
@nicolo-ribaudo Ok i didn't know and still don't understand why the equality is true but after further investigation the problem was babel not adding parenthesis around 10000xxxx100 and we are working on old browser who cannot understand 10000 .toFixed() with space
I will try beautify option

Thanks for your answer, now its on my side !

**Comment by nicolo-ribaudo** [comment]
> babel not adding parenthesis around 10000xxxx100

It's a bug then!

**Comment by zcarde** [comment]
I don't know the exact version/model of the browser but its a really old one, he doesn't even handle es5 features
For now we found that we didn't needed this piece of code (its a polyfill from core-js for Number.toFixed, and we took all Number polyfill but didn't needed toFixed) so we removed it but thank's for the plugin, we will add it in case someday we need the polyfill

**Comment by nicolo-ribaudo** [comment]
Ok I'm closing this again then, if anyone else reports the same problem we can investigate moving that plugin to an official package :+1:
