### ISSUE TITLE
[Bug]: @babel/register does not transpile modules when `node`'s CWD is a subdirectory

### ISSUE THREAD

**Issue by vvanpo** [babel/babel#13353]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

https://github.com/vvanpo/minimal-repros/tree/1f6fb5b539c98da55cd718d59a9ff682597fecb3/@babel/register

### Configuration file name

babel.config.js

### Current and expected behavior

In the above folder, install dependencies via `yarn install`, and then run `./test`.

The `./test` file first loads a module that imports `@babel/register`, which works as expected. Next, it changes the current working directory to a subdirectory, and then loads the module again. This time, we get a syntax error indicating that `@babel/register` is not transpiling intercepted modules.

### Environment

  System:
    OS: Linux 5.11 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
  Binaries:
    Node: 14.16.1 - /usr/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 6.14.12 - /usr/bin/npm
  npmPackages:
    @babel/core: ^7.14.3 => 7.14.3 
    @babel/preset-env: ^7.14.2 => 7.14.2 
    @babel/register: ^7.13.16 => 7.13.16

**Comment by nicolo-ribaudo** [comment]
We should document this explicitly, but the reason for this behavior is that:
- `@babel/register`'s default behavior is to only load modules in the CWD
- By default Babel loads the `babel.config.js` file in the CWD

You can fix this by:
- passing a custom [`ignore`](https://babeljs.io/docs/en/babel-register#specifying-options) option to `@babel/register`
- and set [`rootMode: "upward"`](https://babeljs.io/docs/en/options#rootmode) in `@babel/register`'s options

**Comment by vvanpo** [comment]
Thanks for clarification. I think this is a reading comprehension problem on my part, I remembered that `babel.config.js(on)` is "project-wide", but I had just assumed that "project-wide" meant "wherever the nearest `package.json` is", even though [the docs are clear](https://babeljs.io/docs/en/config-files#project-wide-configuration) about the CWD being the default.

For context on why this was an issue for me:
A project I work on uses `@babel/register` to allow our Webpack config to be written in ES6+, and our ESLint configuration is dependent on our Webpack config via `eslint-plugin-import`. This is fine when running ESLint via a `package.json` script a la `yarn lint` or `npm run lint`, as these tools automatically set the CWD to the root of the project. But some IDEs, like JetBrains IDEs, will run ESLint themselves using an absolute path, and do so setting the CWD to the directory of the file they are linting. So `@babel/register` would fail to find our `babel.config.js`. Thanks for the tip about `rootMode`. It sounds like in our case we could also just pass `root: __dirname`.
