### ISSUE TITLE
Extending builtins should work

### ISSUE THREAD

**Issue by ljharb** [babel/babel#1336]
http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=true&code=class%20Foo%20extends%20String%20%7B%7D%0AString.prototype.toString.call(new%20Foo('abc'))

```js
class Foo extends String { }
String.prototype.toString.call(new Foo('abc'));
```

This should **not** throw, since a `Foo` should have a [[[StringData]] internal slot](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-properties-of-the-string-prototype-object). This is of course impossible in a pre-ES6 engine, so that means that `String.prototype.toString.call` calls probably need to be transpiled too - or at least, a warning should perhaps be issued when extending builtins?

**Comment by zloirock** [comment]
Emm... [It works](http://goo.gl/QuaJim).

**Comment by ljharb** [comment]
Wow, you're right. I could have sworn it threw a "function is not generic" error when I filed this.

Am I crazy, or did the website just get updated now? :-)

**Comment by zloirock** [comment]
Support subclassing `String` and most native constructors was added in 5.1.0. For some native constructor support subclassing was added in 5.1.9, in REPL now 5.1.3.

**Comment by tomjakubowski** [comment]
The linked example says "String.prototype.toString is not generic" on Chrome 43 and "toString method called on incompatible Object" on Firefox 38 (both latest versions). I'm fairly sure that Chrome 43's v8 version (4.3.61.23) supports native subclassing.

What am I missing here?

**Comment by zloirock** [comment]
@tomjakubowski looks like subclassing native constructors was removed ~5.4 =\

**Comment by ljharb** [comment]
In that case, should `babel` throw on extending builtins? Or, should all the primordial prototype methods that throw on missing internal slots be wrapped?

Going with "neither" seems like a huge hazard.

**Comment by tomjakubowski** [comment]
This is kind of a bummer, because v8 and Chrome [natively support this feature](https://github.com/v8/v8-git-mirror/blob/master/test/mjsunit/harmony/classes-maps.js#L53-L55) now if you pass all the right experimental command line flags and whatnot. But tools like Webpack generally barf on ES6 syntax, so it's necessary to run ES6 source through something like Babel if you want to also want to take advantage of Webpack.

**Comment by tomjakubowski** [comment]
Is there a rationale in a GitHub issue or commit message or something that explains why this feature was removed?

**Comment by sebmck** [comment]
Yes, there was an extremely important reason why this was removed. I'll
find the relevant issue when I'm not mobile, feel free to ping this thread
if I forget.

On Thursday, 28 May 2015, Tom Jakubowski <notifications@github.com> wrote:

> Is there a rationale in a GitHub issue or commit message or something that
> explains why this feature was removed?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1336#issuecomment-106647176>.
>


-- 
Sebastian McKenzie

**Comment by loganfsmyth** [comment]
@tomjakubowski When I played with it last week, extending builtins worked in Chrome when using native class syntax, but not when using ES5-style inheritance, so I'm not sure that'd work either way.

@sebmck Do you know what the spec says as far as builtin extensibility using ES5-style inheritance? Given that test last week, it was unclear to me if Chrome had just only partially-implemented builtin extension, or if it is supposed to eventually work with ES5-style extension too.

**Comment by loganfsmyth** [comment]
My test in Chrome (without Babel):
```
// Prints a nice stack trace
new (function(){
  "use strict";
  return class E extends Error { }
}());
```
```
// Doesn't
new (function(){
  "use strict";
  function E(message){
    Error.call(this, message);
  };
  E.prototype = Object.create(Error);
  E.prototype.constructor = E;
  return E;
}());
```

**Comment by tomjakubowski** [comment]
Found this issue. #1424

**Comment by tomjakubowski** [comment]
@loganfsmyth this sort of thing works for me in Chrome:

```javascript
function E(message) {
  this.__proto__ = new Error('E!!!' + message);
}

throw new E('foo')
```

but of course, that's not portable and v8 is even deprecating `__proto__`. I think also you meant `E.prototype = Object.create(Error.prototype)` but that still doesn't work. I'm not sure if v8's added support for ES6 subclassing of natives/builtins "extends" to ES5-style subclassing.

**Comment by loganfsmyth** [comment]
Woops, just a typo. Yeah that was my question basically.

**Comment by ljharb** [comment]
`__proto__` is deprecated but `Object.setPrototypeOf` and `Object.getPrototypeOf` are not, so that should all work (you can shim `setPrototypeOf` in most any engine where `__proto__` is available).

**Comment by sebmck** [comment]
@tomjakubowski Yep, that's the one.

@ljharb What do you mean be deprecated? Deprecated be whom? `__proto__` is in the ES6 spec.

**Comment by ljharb** [comment]
It's in Annex B, which is the place where deprecated-but-defacto-web-standards go. Nobody should be using `__proto__` going forward, especially when `Object.getPrototypeOf` and `Object.setPrototypeOf` exist.
