### ISSUE TITLE
Babel > 5 's es6 module syntax output breaks rewire-webpack

### ISSUE THREAD

**Issue by sairion** [babel/babel#1337]
Please see my comment over their issuetracker -> https://github.com/jhnns/rewire-webpack/issues/12#issuecomment-95797024

(Actually I'm not sure its Babel > 5 's own problem since I was not using Babel for a bit of time)

**Comment by sebmck** [comment]
I don't think this is a problem with Babel. I'm not going to change the way modules are generated because it's necessary to support live bindings. Let me know if I can be of any further assistance though.

**Comment by sairion** [comment]
Seems reasonable. Then is there any way (general Babel API, plugin-level API...) to get the bound name?

**Comment by sebmck** [comment]
There's no public API but I guess you could do:

```javascript
import foo from "foo";
```

```javascript
var Transformer = require("babel-core").Transformer;

module.exports = new Transformer("my-plugin", {
  Program: function (node, parent, scope, file) {
    file.moduleFormatter.remaps.foo; // AST of _foo.default
  }
});
```

**Comment by sairion** [comment]
I'll try that. Thanks!

**Comment by damassi** [comment]
For cross reference, please see:  https://github.com/jhnns/rewire/issues/55#issuecomment-96846033

**Comment by jhnns** [comment]
The current design breaks usages of `eval()`. While I totally agree, that `eval()` should not be used in day-to-day code, it is still part of the language and will not be deprecated. There are legitimate use-cases for it.

**Comment by sebmck** [comment]
Babel assumes all input code is module code which means it has an implicit strict mode. This means the arguments for `eval`, `new Function` and `with` are moot since you can't even use them.

**Comment by jhnns** [comment]
That assumption is valid for most of the code out there. But `eval()` is *not* deprecated and strict mode does not prohibit the use of `eval()`, it just restricts the scope.

**Comment by sebmck** [comment]
@jhnns 

> But `eval()` is *not* deprecated and strict mode does not prohibit the use of `eval()`, it just restricts the scope.

Wasn't aware of this but upon checking the spec you're right. Looks like it's a spec inconsistency with [Acorn](https://github.com/marijnh/acorn) then since `eval()` is literally a syntax error.

Regardless of your strong feelings against this, there's really nothing I can do. I'm not willing to ditch spec compliant live module bindings just to support the rare case that someone wants to `eval`.

**Comment by jhnns** [comment]
I totally understand this, it is really an edge-case. But `eval()` is the only way for a module like [rewire](https://github.com/jhnns/rewire) to retrieve internal variables in a test-case.

There is nothing I can do... :disappointed:

**Comment by loganfsmyth** [comment]
It seems like it might be easier to have a replacement for rewire that's written to process an AST, then you could easily have a babel plugin to inject a function to read/write all top-level module variables, and if one of those modules happened to be exported, Babel's module export logic would just work.

**Comment by RReverser** [comment]
> Wasn't aware of this but upon checking the spec you're right. Looks like it's a spec inconsistency with Acorn then since eval() is literally a syntax error.

Maybe problem with your fork since original Acorn parses it without error.

**Comment by sebmck** [comment]
Wait, nope, [my bad](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/other/strict.js#L24). Can't for the life of me remember the reasoning.

**Comment by jhnns** [comment]
> It seems like it might be easier to have a replacement for rewire that's written to process an AST

That is nasty ... but probably just as nasty as using `eval()` :grin:

However, that is a lot of work just to support babel :(

**Comment by damassi** [comment]
If this issue will most likely never get resolved then I need to begin migrating all of my tests away from Rewire -- off the top of anyone's head, does anyone know of a library similar to Rewire that works with ES6+ syntax?  Such a shame!  Rewire seemed to work fine with Babel 4.

**Comment by loganfsmyth** [comment]
At the end of the day, rewire works on CommonJS modules. I'd say that while Babel can create CommonJS modules, it seems like assuming that the CommonJS structure would map directly to ES6 modules is a mistake.

That said, there is nothing stopping you from writing your Babel modules as CommonJS and just not using ES6 modules.

**Comment by damassi** [comment]
Right, that's how I've gotten around the issue for the time being, but this isn't supportable in the long run.

**Comment by doctyper** [comment]
+1 @damassi. If the solve is "don't use ES6 imports", I and my co-workers are in the same boat and will unfortunately need to migrate away from Rewire.

**Comment by jhnns** [comment]
I don't know too much about ES6 module details, but afaict it's not correct that rewire is not compatible with the ES6 module syntax itself. It is not compatible with babel, because babel renames variables based on the assumption that all variables can be statically analyzed – which is only true for ~99.99% of JavaScript.

**Comment by sebmck** [comment]
@jhnns Except rewire works under a similar assumption where the local variable is named exactly the same as the source.

**Comment by jhnns** [comment]
Yes, I'm writing code under the assumption that my variables are named exactly the same as in the source :)

**Comment by jhnns** [comment]
So ... just loud thinking:

If rewire would use an AST, then it'd turn this module:

```javascript
let a = 1;
let b = 2;
```

into

```javascript
let a = 1;
let b = 2;

export let __set__ = function (variable, value) {
    let setters = {
        a(value) {
            a = value;
        },
        b(value) {
            b = value;
        }
    };
    
    setters[variable](value);
};

export let __get__ = function (variable) {
    let getter = {
        a() {
            return a;
        },
        b() {
            return b;
        }
    };
    
    return getter[variable]();
};
```

and babel would be fine?

**Comment by loganfsmyth** [comment]
Yeah, that's what I was getting at. I'd expect that to work.

**Comment by loganfsmyth** [comment]
And walking the top-level VariableDeclaration nodes in the file would be pretty straightforward.

**Comment by jhnns** [comment]
I haven't worked with an AST parser yet, but yes... it probably is. This change would break the "feature" that allowed to use dot notation when calling `__set__("console.log", fn)` but I haven't considered this to be feature anyway ^^. It was just an unwanted side-effect of `eval()`.

Nonetheless it would be a breaking change... and I still assume it to be a lot of work. It needs to be added to rewire-webpack as well.

**Comment by sebmck** [comment]
Here's a plugin I whipped up in a few minutes, it does the exact transformation specified in [this comment](https://github.com/babel/babel/issues/1337#issuecomment-97261856):

```javascript
var Transformer = require("babel-core").Transformer;
var t           = require("babel-core").types;

module.exports = new Transformer("rewire", {
  Program: function (node, parent, scope, file) {
    this.stop(); // optimisation: stops the traversal from traversing the rest of the AST

    var bindings = Object.keys(scope.bindings);

    var buildBindingObject = function (buildBody) {
      var obj = t.objectExpression([]);

      for (var i = 0; i < bindings.length; i++) {
        var name = bindings[i];
        var id = t.identifier(name);
        obj.properties.push(t.property(
          "init",
          id,
          t.functionExpression(t.identifier("_" + name), [], t.blockStatement([buildBody(id, name)]))
        ));
      }

      return obj;
    };

    var buildExportDeclaration = function (name, params, buildBody) {
      params.unshift(t.identifier("name"));

      var block = t.blockStatement([
        t.returnStatement(
          t.callExpression(
            t.memberExpression(buildBindingObject(buildBody), params[0], true),
            []
          )
        )
      ]);

      var func = t.functionDeclaration(
        t.identifier(name),
        params,
        block
      );

      return t.exportNamedDeclaration(func);
    };

    var nodes = this.get("body");

    nodes[nodes.length - 1].insertAfter([
      buildExportDeclaration("__set__", [t.identifier("value")], function (id) {
        return t.expressionStatement(t.assignmentExpression("=", id, t.identifier("value")));
      }),

      buildExportDeclaration("__get", [], function (id) {
        return t.returnStatement(id);
      })
    ]);
  }
});
```

Spaghetti code, especially the `nodes[nodes.length - 1].insertAfter` bullshit, need to add an API for it.

**Comment by damassi** [comment]
Thanks @sebmck!

**Comment by kossnocorp** [comment]
@sebmck there is a problem in the code:

1. I'm getting:

  ```
  Module build failed: TypeError: code/node_modules/baggage-loader/index.js?style.styl!code/new/ui/app/projects/index.jsx: Cannot read property 'start' of undefined
      at File.errorWithNode (code/node_modules/babel-core/lib/babel/transformation/file/index.js:460:23)
      at TraversalPath.enter (code/node_modules/babel-core/lib/babel/transformation/transformers/es6/constants.js:41:26)
      at TraversalPath.call (code/node_modules/babel-core/lib/babel/traversal/path/index.js:456:26)
      at TraversalPath.visit (code/node_modules/babel-core/lib/babel/traversal/path/index.js:468:10)
      at TraversalContext.visitSingle (code/node_modules/babel-core/lib/babel/traversal/context.js:63:41)
      at TraversalContext.visit (code/node_modules/babel-core/lib/babel/traversal/context.js:73:19)
      at Function.traverse.node (code/node_modules/babel-core/lib/babel/traversal/index.js:44:17)
      at TraversalPath.visit (code/node_modules/babel-core/lib/babel/traversal/path/index.js:485:18)
      at TraversalContext.visitMultiple (code/node_modules/babel-core/lib/babel/traversal/context.js:50:16)
      at TraversalContext.visit (code/node_modules/babel-core/lib/babel/traversal/context.js:71:19)
  ```

2. Original error that failed to render is `"Projects" is read-only` (it was defined as `const`).

Not sure how to solve this problem, but rewire plugin must ignore `const`.

**Comment by loganfsmyth** [comment]
@kossnocorp For your second point, could you elaborate? It doesn't seem unreasonable to me for the plugin to be unable to alter the value of a `const` value. Especially if you consider that in time we'll have const support in-browser, and then it won't really be rewire's call whether it can set things.

**Comment by kossnocorp** [comment]
@loganfsmyth main idea of rewire is to give ability to override any variable in global scope regardless from type. It's not supposed to be used in production, but in tests it plays significant role.

For example I have `const location = document.location` on the top of my module and I want to override it:

```
Module.__set__('location', {
  pathname: '/invitation/qwerty123',
  search: '?action=sign-in'
});
```

Then I will be able to check how my module behaves when `location.pathname == '/invitation/qwerty123'` without messing with browser.

Of course I can use `var` in this case but I dislike the idea to do any code changes for tests optimization.

In this case `const` error might be safely ignored.

**Comment by speedskater** [comment]
@kossnocorp have you found a solution to your first point in https://github.com/babel/babel/issues/1337#issuecomment-97327678 as i am having the same issue.

**Comment by kossnocorp** [comment]
@speedskater nope, but you can try to remove all the `const`'s if it's suitable ¯\\_(ツ)_/¯

**Comment by virajsanghvi** [comment]
@kossnocorp Does that mean that all ```const```s need to be removed for any dependencies required in a test, or do you only get that error while trying to set the value of a const?

I can't find any great alternatives to rewire, and downgrading babel isn't a long term solution, so any guidance here, even if rewire is just "mostly" usable, would be great (outside of using require instead of import).

**Comment by kossnocorp** [comment]
I didn't checked described solution, but yeah, I beleave if you want to use it globally you have to remove all the `const`'s.

Personally I still use rewire and old-fashion `rewire('blah-blah-blah')`.

**Comment by jhnns** [comment]
Rewiring `const`s is out of scope for rewire. That can't be circumvented for obvious reasons. A hacky solution would be to rewrite `const` into `var` or `let`, but that's too invasive imho.

Concerning babel compatibility: I'm thinking about implementing the AST solution as pointed out here, but that requires a major rewrite which I currently don't have the time for :disappointed:

**Comment by speedskater** [comment]
Based on the prototype from @sebmck I wrote a small babel plugin which transforms the import statements into commonjs require statements. Furthermore its adds the methods __Rewire__, __GetDependency__ and __ResetDependency__ to the default export declaration.

```javascript
var Transformer = require("babel-core").Transformer;
var t           = require("babel-core").types;
var GettersArray = t.identifier("__$Getters__");
var SettersArray = t.identifier("__$Setters__");
var ReSettersArray = t.identifier("__$Resetters__");


module.exports = new Transformer("rewire", {
  Program: function(node) {
      var gettersArrayDeclaration = t.variableDeclaration('let', [ t.variableDeclarator(GettersArray, t.arrayExpression([])) ]);
      var settersArrayDeclaration = t.variableDeclaration('let', [ t.variableDeclarator(SettersArray, t.arrayExpression([])) ]);
      var resettersArrayDeclaration = t.variableDeclaration('let', [ t.variableDeclarator(ReSettersArray, t.arrayExpression([])) ]);

      var nameVariable = t.identifier("name");
      var valueVariable = t.identifier("value");

      var universalGetter = t.exportNamedDeclaration(t.functionDeclaration(
          t.identifier('__GetDependency__'),
          [nameVariable ],
          t.blockStatement([
              t.returnStatement(t.callExpression(t.memberExpression(GettersArray, nameVariable, true), []))
          ])
      ));

      var universalSetter = t.exportNamedDeclaration(t.functionDeclaration(
          t.identifier('__Rewire__'),
          [nameVariable, valueVariable ],
          t.blockStatement([
              t.expressionStatement(t.callExpression(t.memberExpression(SettersArray, nameVariable, true), [valueVariable]))
          ])
      ));

      var universalResetter = t.exportNamedDeclaration(t.functionDeclaration(
          t.identifier('__ResetDependency__'),
          [ nameVariable ],
          t.blockStatement([
              t.expressionStatement(t.callExpression(t.memberExpression(ReSettersArray, nameVariable, true), []))
          ])
      ));

      node.body.unshift(gettersArrayDeclaration, settersArrayDeclaration, resettersArrayDeclaration, universalGetter,
          universalSetter, universalResetter);
      return node;
  },
  ImportDeclaration: function(node, parent, scope, file) {
      var requireVariableDeclarators = [];
      var originalVariableDeclarations = [];
      var getters = [];
      var setters = [];
      var resetters = [];
      var accessors = [];

      var mappedSpecifiers = node.specifiers.forEach(function(specifier) {
          var localVariable = specifier.local;
          var localVariableName = localVariable.name;
          var getter = t.identifier('__get' + localVariableName + '__');
          var setter = t.identifier('__set' + localVariableName + '__');
          var resetter = t.identifier('__reset' + localVariableName + '__');
          var originalVariableIdentifier = t.identifier('__' + localVariableName + 'Orig__');
          var requireExpression = t.callExpression(t.identifier('require'), [node.source]) ;

          if(specifier.type !== "ImportDefaultSpecifier" && specifier.type !== "ImportNamespaceSpecifier") {
              requireExpression = t.memberExpression(requireExpression, specifier.imported || specifier.local, false);
          }
          requireVariableDeclarators.push(t.variableDeclarator(
              specifier.local,
              requireExpression
          ));


          originalVariableDeclarations.push(t.variableDeclaration('const', [ t.variableDeclarator(originalVariableIdentifier, localVariable)]));

          function addAccessor(array, operation) {
              accessors.push(t.expressionStatement(t.assignmentExpression("=", t.memberExpression(array, t.literal(localVariableName), true), operation)));
          }

          getters.push(t.functionDeclaration(
              getter,
              [],
              t.blockStatement([
                  t.returnStatement(localVariable)
              ])
          ));
          addAccessor(GettersArray, getter);

          setters.push(t.functionDeclaration(
              setter,
              [t.identifier("value")],
              t.blockStatement([
                  t.expressionStatement(t.assignmentExpression("=", localVariable, t.identifier("value")))
              ])
          ));
          addAccessor(SettersArray, setter);


          resetters.push(t.functionDeclaration(
              resetter,
              [],
              t.blockStatement([
                  t.expressionStatement(t.assignmentExpression("=", localVariable, originalVariableIdentifier))
              ])
          ));
          addAccessor(ReSettersArray, resetter);
      });

      return [t.variableDeclaration('let', requireVariableDeclarators)].concat(originalVariableDeclarations).concat(setters).concat(getters).concat(resetters).concat(accessors);/*.
          concat(originalVariableDeclarations).concat(setters).concat(resetters);*/
  },

  ExportDefaultDeclaration: function(node) {
      return t.exportDefaultDeclaration(t.callExpression(t.memberExpression(t.identifier('Object'),  t.identifier('assign')), [ node.declaration, t.objectExpression([
      t.property('init', t.literal('__Rewire__'), t.identifier('__Rewire__')),
          t.property('init',t.literal('__ResetDependency__'), t.identifier('__ResetDependency__')),
          t.property('init',t.literal('__GetDependency__'), t.identifier('__GetDependency__'))
      ])]));
  }
});
```

To use it:
```javascript

import MyModule from 'pathToModule.js';

MyModule.__Rewire__('DependentModule', {
   theMocked: 'property'
});
```

Afterwards:

```javascript

MyModule.__ResetDependency__('DependentModule');
```

@sebmck: Do you see any drawbacks using this techniques for testing purposes? If not I will publish this plugin as an npm package in the following days.

**Comment by damassi** [comment]
@speedskater - when you are ready to publish could you please notify this thread?

**Comment by sebmck** [comment]
@speedskater Unsure about the correctness, you're likely to run into compatibility issues with existing ES6 since you're changing the semantics quite dramatically but I don't know for sure.

**Comment by speedskater** [comment]
@sebmck You are right. Converting the import into require statements can cause troubles when using other module loaders.

Therfore I changed the implementiation regarding the ImportDeclaration. The original import is replaced by another es6 import to a new artficial variable and a temporary variable with the original import name. This change should make the plugin independent of the actual module loading system used.

The updated handling of the import declaration.
```javascript
 ImportDeclaration: function(node, parent, scope, file) {
      var variableDeclarations = [];
      var getters = [];
      var setters = [];
      var resetters = [];
      var accessors = [];

      node.specifiers.forEach(function(specifier) {
          var localVariable = specifier.local;
          var localVariableName = localVariable.name;
          var getter = t.identifier('__get' + localVariableName + '__');
          var setter = t.identifier('__set' + localVariableName + '__');
          var resetter = t.identifier('__reset' + localVariableName + '__');
          var requireExpression = t.callExpression(t.identifier('require'), [node.source]) ;
          var actualImport = scope.generateUidIdentifier(localVariableName + "Temp");
          specifier.local = actualImport;

          variableDeclarations.push(t.variableDeclaration('let', [ t.variableDeclarator(localVariable, actualImport)]));

          function addAccessor(array, operation) {
              accessors.push(t.expressionStatement(t.assignmentExpression("=", t.memberExpression(array, t.literal(localVariableName), true), operation)));
          }

          getters.push(t.functionDeclaration(
              getter,
              [],
              t.blockStatement([
                  t.returnStatement(localVariable)
              ])
          ));
          addAccessor(GettersArray, getter);

          setters.push(t.functionDeclaration(
              setter,
              [t.identifier("value")],
              t.blockStatement([
                  t.expressionStatement(t.assignmentExpression("=", localVariable, t.identifier("value")))
              ])
          ));
          addAccessor(SettersArray, setter);


          resetters.push(t.functionDeclaration(
              resetter,
              [],
              t.blockStatement([
                  t.expressionStatement(t.assignmentExpression("=", localVariable, actualImport))
              ])
          ));
          addAccessor(ReSettersArray, resetter);

      });

      return [node].concat(variableDeclarations).concat(setters).concat(getters).concat(resetters).concat(accessors);
  }
```

**Comment by speedskater** [comment]
Finally published the [babel-rewire-plugin](https://github.com/speedskater/babel-rewire-plugin).

**Comment by sebmck** [comment]
If you name it `babel-plugin-rewrite` then people can just use it like `$ babel --plugins rewire`.

**Comment by speedskater** [comment]
@sebmck Thanks renamed the project and republished it https://github.com/speedskater/babel-plugin-rewire

**Comment by damassi** [comment]
I really appreciate this @speedskater; will spread the word.

**Comment by sairion** [comment]
@speedskater Nice!

**Comment by jhnns** [comment]
Thx @speedskater for investigating this. Could you explain in bulletpoints what your code does?

As far as I understand, it looks for `__Rewire__`, `__GetDependency__`, `__ResetDependency__` methods and injects setters and getters for the variables in the target module. But how is the target module identified? How do you get into the scope of the target module?

And why did you opt for another API than rewire? It looks like your plugin is not actually compatible with rewire.

**Comment by speedskater** [comment]
@jhnns The code generates the methods __Rewire__, __GetDependency__ and __ResetDependency__ and internally dispatches them to the corresponding getters and setters, which allow to modify the respective imported models.

e.g.:

```js
import MyModule from 'path/to/MyModule.js';

export default "";
```
will be transformed to:
```js
"use strict";

export { __GetDependency__ };
export { __Rewire__ };
export { __ResetDependency__ };
import _MyModuleTemp from "path/to/MyModule.js";

var __$Getters__ = [];
var __$Setters__ = [];
var __$Resetters__ = [];

function __GetDependency__(name) {
  return __$Getters__[name]();
}

function __Rewire__(name, value) {
  __$Setters__[name](value);
}

function __ResetDependency__(name) {
  __$Resetters__[name]();
}

var MyModule = _MyModuleTemp;

function __setMyModule__(value) {
  MyModule = value;
}

function __getMyModule__() {
  return MyModule;
}

function __resetMyModule__() {
  MyModule = _MyModuleTemp;
}

__$Getters__["MyModule"] = __getMyModule__;
__$Setters__["MyModule"] = __setMyModule__;
__$Resetters__["MyModule"] = __resetMyModule__;
export default Object.assign("", {
  "__Rewire__": __Rewire__,
  "__set__": __Rewire__,
  "__ResetDependency__": __ResetDependency__,
  "__GetDependency__": __GetDependency__,
  "__get__": __GetDependency__
});
```

Regarding the compatibility to rewire.js you are right. It was a mistake from my side. I just added the respective methods \_\_set\_\_ and \_\_get\_\_ for compatibility reasons.  

Regarding the \_\_with\_\_ method, it would imho make more sense to move the respective code into a small library which can work with rewire.js as well as babel-plugin-rewire. In case of BDD style tests I would propose the following API for it (automatically adds afterEach) and could publish it into a new project (e.g. named use-require) the day after tomorrow. @jhns what do you think?

```js
import useRewire from 'use-rewire';
import ComponentToTest from 'my-fancy-wrapper-component-module';

ComponentToTest.__Rewire__('ChildComponent', React.createClass({
    render: function() { return <div {...this.props}></div>; }
}));

describe('Tests my fancy wrapper module', function() {
	var rewire = useRewire();

	it('renderTest', function() {
		rewire(ComponentToTest, 'ChildComponent', React.createClass({
    			render: function() { return <div {...this.props}></div>; }
		}));

                 ..... test component ....
	});
});

```

**Comment by jhnns** [comment]
Ok, so your plugin just adds `__set__` and `__get__` to *every* module. That's not exactly how rewire works...

I'm curious about your solution, because I'm thinking about a similar solution for rewire. But I'd appreciate if you would stick to the rewire API as close as possible because otherwise people will need to rewrite their modules. Then it does not make sense to carry the `rewire` name in your module name :)

**Comment by speedskater** [comment]
I get your point. And my indent wasn't to deviate too much from rewire.js, although I might have overseen some details ;). 
Theoretically it should be possible to create a fully es6 compatible version but imho providing a plain call to rewire('dependency') can only be satisfied in a commons environment.

Therefore I would propose the following enhancement:
Adding a __rewire__ method on the default export which allows to rewire the module with the same semantics as rewire.js as well as to provide a small wrapper rewire function for commonjs environments.

As my knowledge of rewire.js is limited and there always will be a functionality I likely will oversee when porting the API into the babel plugin I would suggest to join forces to create a solution which tries to be as compatible as possible to rewire.js while providing module system independent es6 support.

**Comment by damassi** [comment]
@speedskater - So i've finally got around to replacing Rewire with your library and its working great.

**Comment by 0x80** [comment]
I'm trying to use the babel-plugin-rewire as a replacement but without even trying to mock anything I get an error saying `Attempting to define property on object that is not extensible`. Am I missing something? 

See speedskater/babel-plugin-rewire/issues/28

**Comment by speedskater** [comment]
I think it might be a regression. Please try version 0.1.12 of babel-plugin-rewire until speedskater/babel-plugin-rewire#28 is fixed.

**Comment by speedskater** [comment]
@0x80 the new version 0.1.14 should fix your issues.
