### ISSUE TITLE
babel.config.json as jsonc (json with comments)

### ISSUE THREAD

**Issue by thernstig** [babel/babel#13371]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I cannot see any description anywhere if the `babel.config.json` file supports JSON with comments (`jsonc`). But when trying to use comments, it seems Babel can parse the file just fine anyway

As such, should this be explicit somewhere (e.g. in the docs)? (I can then create an issue in the babel website repo).

And my second question, if it is true, is it fine if I submit a feature request or PR on the VS Code repo to automatically interpret `babel.config.json` as `jsonc` instead of just `json`? This has a few benefits, such as comments not getting red squiggly lines as if something was wrong.

### Describe the solution you'd like

A babel website update and a VS Code editor update.

### Describe alternatives you've considered

Maintaining a local VS Code project-wide config mapping the file to `jsonc`.

**Comment by nicolo-ribaudo** [comment]
In the "config file extensions" section (https://babeljs.io/docs/en/config-files#supported-file-extensions) we mention that they are parsed as JSON5. Maybe we can explicitly specify that this means that they support comments?

> And my second question, if it is true, is it fine if I submit a feature request or PR on the VS Code repo to automatically interpret babel.config.json as jsonc instead of just json? This has a few benefits, such as comments not getting red squiggly lines as if something was wrong.

Yes please! They already do that for `.babelrc` (without extension).

**Comment by thernstig** [comment]
Hmm, if you do mention it is JSON5 then maybe that is sufficient. As comments is just "one part" of that spec. If you feel that is ok, then we can close this.

I also submitted an issue on VS Code: https://github.com/microsoft/vscode/issues/124683
