### ISSUE TITLE
[Bug]: Unexpected object spread operator behavior in Babel 7

### ISSUE THREAD

**Issue by adwydman** [babel/babel#13378]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
const testArray = [
  'someValue',
  ...{},
  'otherValue'
];
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  'assumptions': {
    enumerableModuleMeta: false
  },
  'presets': [
    '@babel/preset-react',
    [
      '@babel/preset-env', {
        loose: true,
        useBuiltIns: 'usage',
        corejs: { version: '3.12.1', proposals: true },
        targets: '>0.25%, not dead'
      }
    ]
  ],
  'plugins': [
    ['@babel/plugin-proposal-decorators', { 'legacy': true }],
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-import-meta',
    'lodash'
  ],
  'env': {
    'test': {
      'presets': [
        '@babel/preset-react',
        [
          '@babel/preset-env', {
            loose: true,
            useBuiltIns: 'usage',
            corejs: '3'
          }
        ]
      ],
      'plugins': [
        ['@babel/plugin-proposal-decorators', { 'legacy': true }],
        '@babel/plugin-syntax-dynamic-import',
        '@babel/plugin-syntax-import-meta',
        'lodash'
      ]
    }
  }
};

```

### Current and expected behavior

I am upgrading Babel from 6 to 7 and I noticed that the object spread operator behaves differently.

In Babel 6 using the spread operator on en empty object literal would return nothing at all, for example:

```js
const testArray = [
  'someValue',
  ...{},
  'otherValue'
];

// result:
[
  'someValue',
  'otherValue'
]
```

However in Babel 7 the result for the above code is:

```
[
  'someValue',
  {}
  'otherValue'
]
```

### Environment

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    npm: 7.14.0 - ~/Documents/vice-frontend/node_modules/.bin/npm
  npmPackages:
    @babel/core: 7.14.3 => 7.14.3 
    @babel/plugin-proposal-decorators: 7.14.2 => 7.14.2 
    @babel/plugin-proposal-json-strings: 7.14.2 => 7.14.2 
    @babel/plugin-proposal-object-rest-spread: 7.14.2 => 7.14.2 
    @babel/plugin-syntax-dynamic-import: 7.8.3 => 7.8.3 
    @babel/plugin-syntax-import-meta: 7.10.4 => 7.10.4 
    @babel/preset-env: 7.14.2 => 7.14.2 
    @babel/preset-react: 7.13.13 => 7.13.13 
    babel-eslint: ^9.0.0 => 9.0.0 
    babel-jest: ^26.0.0 => 26.6.3 
    babel-loader: 8.2.2 => 8.2.2 
    babel-plugin-istanbul: 4.1.5 => 4.1.5 
    babel-plugin-lodash: 3.3.4 => 3.3.4 
    eslint: 4.13.1 => 4.13.1 
    jest: ^26.0.0 => 26.6.3 
    webpack: 4.41.5 => 4.41.5

**Comment by nicolo-ribaudo** [comment]
The `loose: true` option of `@babel/preset-env` enables all the [assumptions](https://babeljs.io/docs/en/assumptions).

I suggest removing `loose: true` and manually enabling only what you want: in this case, the problem is that [`iterableIsArray`](https://babeljs.io/docs/en/assumptions#iterableisarray) shouldn't be enabled.

**Comment by adwydman** [comment]
@nicolo-ribaudo Thanks for a quick reply.

Making that changes causes an error:

```
Invalid attempt to spread non-iterable instance.
``` 

Which is fine, I can make a code change to get rid of it. What I'm more curious about is why did the behavior of the spread operator change? 

In Babel 6 I also used `loose: true` flag for the `env` preset and using the spread operator on an empty object literal didn't return an object literal like it does in Babel 7. Do you know what might have caused it?

**Comment by nicolo-ribaudo** [comment]
> `Invalid attempt to spread non-iterable instance.`

That's actually correct, you would also get an error in a browser's console because you can only spread objects in arrays if they have a `[Symbol.iterator]()` method.

> In Babel 6 I also used loose: true flag for the env preset and using the spread operator on an empty object literal didn't return an object literal like it does in Babel 7. Do you know what might have caused it?

Since `loose` has never been well defined, we made some changes to better balance between "correctness" and "code size/speed". The reason we introduced `assumptions` is to avoid these ambiguities.
