### ISSUE TITLE
spec.protoToAssign doesn't work for buildExternalHelpers?

### ISSUE THREAD

**Issue by lukescott** [babel/babel#1338]
When using inline helpers the `inherits` helper replaces `__proto__` with `defaults`, as expected. I can't seem to find a way to pass any options into `buildExternalHelpers(whitelist)` that would give me the same result. Because of this `spec.protoToAssign` isn't working for external helpers.

**Comment by sebmck** [comment]
I'm confused?

```
$ node
> require("babel-core").buildExternalHelpers(["inherits"])
'(function (global) {\n  var babelHelpers = global.babelHelpers = {};\n\n  babelHelpers.inherits = function (subClass, superClass) {\n    if (typeof superClass !== "function" && superClass !== null) {\n      throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);\n    }\n\n    subClass.prototype = Object.create(superClass && superClass.prototype, {\n      constructor: {\n        value: subClass,\n        enumerable: false,\n        writable: true,\n        configurable: true\n      }\n    });\n    if (superClass) subClass.__proto__ = superClass;\n  };\n})(typeof global === "undefined" ? self : global);'
```

**Comment by lukescott** [comment]
```
$ node
> require("babel-core").buildExternalHelpers(["defaults", "inherits"])
```

Produces (pretty-printed):
```javascript
(function (global) {
  var babelHelpers = global.babelHelpers = {};
  babelHelpers.inherits = function (subClass, superClass) {
    if (typeof superClass !== "function" && superClass !== null) {
      throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
    }
    subClass.prototype = Object.create(superClass && superClass.prototype, {
      constructor: {
        value: subClass,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
    if (superClass) subClass.__proto__ = superClass;
  };
  babelHelpers.defaults = function (obj, defaults) {
    var keys = Object.getOwnPropertyNames(defaults);
    for (var i = 0; i < keys.length; i++) {
      var key = keys[i];
      var value = Object.getOwnPropertyDescriptor(defaults, key);
      if (value && value.configurable && obj[key] === undefined) {
        Object.defineProperty(obj, key, value);
      }
    }
    return obj;
  };
})(typeof global === "undefined" ? self : global);
```

Notice the `if (superClass) subClass.__proto__ = superClass;`.

When I do helpers inline the `__proto__` is transformed within the helper. But with external helpers it does not. This is likely because I have no way to pass my options into buildExternal helpers, assuming the first arg is an array and the second is a string.

**Comment by sebmck** [comment]
The external helpers build script isn't ran through the transformation layer so there's no options to pass along. You can just pass the output through `babel.transform` if you want I guess.

**Comment by lukescott** [comment]
Ah, good idea, thanks! Is that what is done with the internal helpers?

**Comment by sebmck** [comment]
What do you mean?

**Comment by lukescott** [comment]
Ok, so I've wrapped buildExternalHelpers in a transform. Now how do I get the defaults helper in there? As in, how do I know which helpers require other helpers? As per my pervious question, how does babel handle this with inline helpers?

**Comment by sebmck** [comment]
No helpers require other helpers.

**Comment by lukescott** [comment]
The `inherits` helper needs the `defaults` helper when `spec.protoToAssign` is enabled. Babel resolves this with internal helpers. I'm just trying to figure out the best way to get the `defaults` helper in there when `inherits` is needed and `spec.protoToAssign` is on, without checking for those two specifically. 

The only thing I can think of is running the transform twice. On the first pass get a list of more helpers needed. Then run it a second time to get all the helpers needed. Is there a cleaner way to do this?

**Comment by sebmck** [comment]
Transformers have the option of pushing themselves multiple times to the transformer stack. There's the hidden internal `_declarations` transformer that adds the helpers. Basically this is the order the transformers are ran in for the code `class Foo extends Bar {}`:

 - `es6.classes` Adds the `inherits` helper.
 - `spec.protoToAssign` - Does nothing since there's no `__proto__` anywhere.
 - `_declarations` - Adds `inherits` helper to the AST.
 - `spec.protoToAssign` - Catches `__proto__` in the `inherits` helper.
 - `_declarations` - Adds `defaults` helper is added to the AST as `spec.protoToAssign` required it.

**Comment by lukescott** [comment]
So it would seem that running transform on the helpers is not equivalent. The downside of using transform on helpers is es6.tailCall is applied to the get helper, whereas this doesn't happen when doing inline.

It's kind of a hack, but I'm running transform on the helpers twice. First pass to get helpers needed, and second pass to get all the helpers. I'm injecting `strict` and `es6.tailCall` into the blacklist. That seems to work for now, although it would be nice if buidExternalHelpers had an options arg that mimicked what you described above.

**Comment by lukescott** [comment]
@sebmck Is inherits the only helper influenced by a transformer / another helper? If that's the case, why not create two different inherits helpers based on `spec.protoToAssign` being used or not? That way external helpers can be used without needing to do a transform on the helpers.

The `runtime` transformer helps out quite a bit, but it currently suffers from the same problem. And unfortunately `spec.protoToAssign` is critical when supporting IE 10 and below.

**Comment by sebmck** [comment]
@lukescott It's a slippery slope if transformers can influence what helpers are used.

**Comment by sebmck** [comment]
>  Is `inherits` the only helper influenced by a transformer / another helper? 

Kinda. `es3.propertyLiterals` and `es3.memberExpressionLiterals` are used on the helpers which turns `default` to `"default"` etc.

**Comment by lukescott** [comment]
Don't transformers decide which helpers are used? In the case of `inherits` the class transformer just needs to know that `spec.protoToAssign` is being used and use a different helper.

Not sure about the cases you mentioned, but if we used a different `inherits` helper would helpers need to be transformed? They already don't get transformed in 2/3 cases (buidExternalHelpers and runtime transformer vs inline).

**Comment by sebmck** [comment]
> The class transformer just needs to know that `spec.protoToAssign` is being used and use a different helper.

As I said, a transformer shouldn't be aware of the existence of another transformer. There are a few internal transformers that are but it's an antipattern that I'm moving away from.

**Comment by lukescott** [comment]
What would you suggest? Needing to transform helpers are just as problematic because 2 ways of getting the helpers are not transformed. I think the solution would either be don't transform helpers at all and find a different solution for `spec.protoToAssign`, or find a different way to do helpers that allows them to be expressed once for a collection of files and have them transformed.

The use case for me specifically: I'm not using `__proto__` directly in my project. I'm assuming that isn't the primary use case for `spec.protoToAssign`? I'm using static properties on my classes, but I don't use static properties in a way that suffers from the issue mentioned on the [spec.protoToAssign page](http://babeljs.io/docs/usage/transformers/spec/proto-to-assign/). I just need static properties to work (and get inherited) in IE 10 and below. Given that requirement, it should behave the same way in Chrome, so it can't be a runtime check.

If `spec.protoToAssign` and converting `__proto__` in the inherits helper are two different use cases, perhaps an option on class transformer would be better?

**Comment by sebmck** [comment]
@lukescott There's no transformer-specific options besides stuff like loose mode since it adds additional complexity to the transformers and leads to having a transformer that is dependent on a bunch of external state which isn't very nice.

**Comment by sebmck** [comment]
Closing this as there doesn't appear to be any particularly resolvable issues. More than happy to continue discussing possible solutions to make this process easier though.
