### ISSUE TITLE
Subclassing built-in not working properly

### ISSUE THREAD

**Issue by daliwali** [babel/babel#1339]
Suppose I have:

```js
class CustomError extends Error {}
class NotFoundError extends CustomError {}
const error = new NotFoundError('This is the error message')
console.log(error.stack) // undefined
console.log(error.message) // empty string
```

This seems to be broken in io.js 1.8.1 and Node.js 0.12.2, but works in the Babel REPL (tried with Firefox/Chrome).

**Comment by sebmck** [comment]
Correct behaviour. Builtin extension only works if you use built-in literals. ie. `class Foo extends Error {}` not `var Bar = Error' class Foo extends Bar {}`. See #1172 for related discussion.

**Comment by daliwali** [comment]
Ok, I will avoid this pattern. However, it magically works in a browser, why?

**Comment by sebmck** [comment]
The browser you're using probably supports native `Error` subclassing.
