### ISSUE TITLE
Change the parser to allow the RegExp d flag.

### ISSUE THREAD

**Issue by ota-meshi** [babel/babel#13393]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

RegExp literals can now use the `d` flag, but the `d` flag causes a parsing error.

https://github.com/tc39/proposals/blob/master/finished-proposals.md
tc39/proposals@f0adbe1
https://github.com/tc39/proposal-regexp-match-indices
tc39/ecma262#1713

### Describe the solution you'd like

Change the parser so that the d flag of the RegExp literal does not cause a parsing error.

I'm not familiar with it, but I might just add the flag to the next line.
https://github.com/babel/babel/blob/main/packages/babel-parser/src/tokenizer/index.js#L24

### Describe alternatives you've considered

I don't think there is an alternative.

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report! This needs to be fixed adding the flag to https://github.com/babel/babel/blob/813f2a3cce04a5366de7c1cc370652db64507305/packages/babel-parser/src/tokenizer/index.js#L24

Then, we should add a test in https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/es2022.

**Comment by nicolo-ribaudo** [comment]
I'm assigning this issue to you since you ticked "Would you like to work on this feature?" :smile:
