### ISSUE TITLE
[Bug]: Reference to class expression in private methods is not correctly compiled

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#13399]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
fn(class WorkerClient {
  static #worker_threads() {
    return WorkerClient;
  }
});
```

[REPL](https://babeljs.io/repl#?browsers=chrome%2060&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=GYOwFAxgNghgznABAdQPYCcDWBTdBhKAS2xABdEBvAKEUTlJlMIkQGIB3DHdAfVIAt02GABM4YAJSUatRENIBXdCBRdcBYmQDcMgL5VdErUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.4)

### Configuration

```json
{
  "plugins": [
    "@babel/plugin-proposal-private-methods",
    "@babel/plugin-proposal-class-properties"
  ]
}
```

### Current and expected behavior

It is compiled to this:
```js
var _class;

fn(_class = class WorkerClient {});

function _worker_threads() {
  return WorkerClient;
}
```

As you can see, `WorkerClient` is not reachable. It should be compiled to something like this:
```js
var _class;

fn(_class = class WorkerClient {});

function _worker_threads() {
  return _class;
}
```

### Environment

- Babel 7.14.4

### Possible solution

In the `replaceThisContext` function that we use to replace `this` usage in class fields and private methods:
https://github.com/babel/babel/blob/813f2a3cce04a5366de7c1cc370652db64507305/packages/babel-helper-create-class-features-plugin/src/fields.ts#L672

we should add a new `path.traverse` call to replace references to the inner binding, with a visitor similar to this one:
```js
const innerReferencesVisitor = {
  ReferencedIdentifier(path, state) {
    const { name } = path.node;
    if (path.scope.bindingIdentifierEquals(name, state.innerBinding)) {
      state.needsClassRef = true;
      path.replaceWith(t.cloneNode(state.classRef));
    }
  },
};
```

where `state` is the one used by `thisContextVisitor` with the addition of `state.innerBinding`, which is the node representing the id of the class expression.

Note that we don't need to merge this visitor with `environmentVisitor`: `environmentVisitor` is only needed to avoid replacing nested `this`es that don't refer to the class, while for normal bindings we use `path.scope.bindingIdentifierEquals`.

We can get `innerBinding` from right before extracting the class reference at https://github.com/babel/babel/blob/813f2a3cce04a5366de7c1cc370652db64507305/packages/babel-helper-create-class-features-plugin/src/index.ts#L173-L178

We only need to get it if we have a `ClassExpression` and `path.node.id` is set, otherwise we can leave `innerBinding` as `undefined` and use it as a "signal" to skip the new `path.traverse` call.

After working on the fix itself, we'll need a bunch of tests:
- A simple `input.js`/`output.js` test, for example my original example
- An `exec.js` test, to check that the binding is the correct one. For example:
  ```js
  let x = class Test {
    static #getTest() { return Test }
    static getTest() { return this.getTest() }
  };
 
  expect(x.getTest()).toBe(x);
  ```
- An `input`/`output` test to verify that it works when the binding is used in nested scopes, for example:
  ```js
  let x = class Test {
    static #method() {
      return function inner() {
        return Test;
      };
    }
  }
  ```
- An `input`/`output` test to verify that it doesn't rewrite shadowed bindings:
  ```js
  let x = class Test {
    static #method() {
      new Test();

      return function inner() {
        let Test = 2;
        return Test;
      };
    }
  }
  ```

### Additional context

The same bug happens with static class fields (both public and private) and instance private methods:
```js
fn(class WorkerClient {
  static #x = WorkerClient;
  static y = WorkerClient;
});
```

we should duplicate the tests for those cases.

**Comment by lala7573** [comment]
Can I give it a try? I'm new to this project but the spec looks quite clear. ... :)

**Comment by fedeci** [comment]
@lala7573 sure!

**Comment by nicolo-ribaudo** [comment]
@lala7573 In case you need some help setting up this repository locally:



1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. In a separate terminal, run `make watch` (or `make build` whenever you change a file)
1. Add a test (`exec.js` and `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest class-properties private-methods` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest class-properties private-methods` and they will be automatically updated.
1. If it is working, run `yarn jest` (or `make test`) to run all the tests
1. Run `git push` and open a PR!

**Comment by lala7573** [comment]
This is draft https://github.com/babel/babel/pull/13429
