### ISSUE TITLE
[Bug]: Non fixable max-len error after @babel/eslint-parser 7.14 update

### ISSUE THREAD

**Issue by morgoth** [babel/babel#13401]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```js
function Something() {
  function handlePostalCodes() {
    fetch(
      `/staff/api/postal_codes?country_code=${selectedCountry}&central_postal_code=${centralPostalCode}&radius=${radius}`,
}

```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.',
    )
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          targets: {
            node: 'current',
          },
        },
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol'],
        },
      ],
      [
        '@babel/preset-react',
        {
          runtime: 'automatic',
          targets: {
            node: 'current',
          },
        },
      ],
    ].filter(Boolean),
    plugins: [
      'babel-plugin-macros',
      '@babel/plugin-syntax-dynamic-import',
      isTestEnv && 'babel-plugin-dynamic-import-node',
      '@babel/plugin-transform-destructuring',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true,
        },
      ],
      [
        '@babel/plugin-proposal-object-rest-spread',
        {
          useBuiltIns: true,
        },
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false,
          regenerator: true,
          corejs: false,
        },
      ],
      [
        '@babel/plugin-transform-regenerator',
        {
          async: false,
        },
      ],
    ].filter(Boolean),
  }
}

```

### Current and expected behavior

When I run `yarn eslint app/javascript` I got an error:
`14:1  error  This line has a length of 122. Maximum allowed is 120  max-len`, but running
`yarn eslint --fix app/javascript` does not modify the file, thus not fixing the problem.

In the `@babel/eslint-parser@7.13.14` the error was not reported.

Is it possible that the given error is a falsy one as it's not really fixable?

### Environment

```
# npx envinfo --preset babel
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
  Binaries:
    Node: 14.16.0 - ~/.asdf/installs/nodejs/14.16.0/bin/node
    Yarn: 1.22.10 - ~/.asdf/installs/nodejs/14.16.0/.npm/bin/yarn
    npm: 6.14.11 - ~/.asdf/installs/nodejs/14.16.0/bin/npm
  npmPackages:
    @babel/eslint-parser: 7.14.4 => 7.14.4 
    @babel/preset-react: ^7.0.0 => 7.13.13 
    eslint: ^7.11.0 => 7.26.0 
    jest: ^26.5.3 => 26.6.3 
```

**Comment by JLHwung** [comment]
> In the @babel/eslint-parser@7.13.14 the error was not reported.

The line containing string template has 122 characters, so eslint should throw on `max-len: 120`. The `eslint-parser` 7.14 works as expected.

> yarn eslint --fix app/javascript does not modify the file, thus not fixing the problem.

Babel/eslint-parser only parses the source into the ESLint-compatible AST, it does not fix linting errors. As I can see on the [ESLint Demo](https://eslint.org/demo#eyJ0ZXh0IjoiZnVuY3Rpb24gU29tZXRoaW5nKCkge1xuICBmdW5jdGlvbiBoYW5kbGVQb3N0YWxDb2RlcygpIHtcbiAgICBmZXRjaChcbiAgICAgIGAvc3RhZmYvYXBpL3Bvc3RhbF9jb2Rlcz9jb3VudHJ5X2NvZGU9JHtzZWxlY3RlZENvdW50cnl9JmNlbnRyYWxfcG9zdGFsX2NvZGU9JHtjZW50cmFsUG9zdGFsQ29kZX0mcmFkaXVzPSR7cmFkaXVzfWAsXG4gICAgKVxuICB9XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJtYXgtbGVuIjoyfSwiZW52Ijp7fX19), eslint v7.27.0 cannot fix this rule. I would suggest opening an issue at the ESLint repo.

**Comment by nicolo-ribaudo** [comment]
@morgoth I'm closing this since as @JLHwung mentioned this also happens without `@babel/eslint-parser` so it's an ESLint issue.

Also please note that many ESLint errors are not fixable, so I wouldn't necessarily expect this one to be.

**Comment by morgoth** [comment]
@nicolo-ribaudo After more inspection on https://github.com/eslint/eslint/issues/14651 I'm coming back here.
Looks like the update I mentioned does not take `ignoreTemplateLiterals` into consideration.

**Comment by JLHwung** [comment]
I can not reproduce this issue on https://github.com/JLHwung/babel/commit/829ec50fdabbc0952539e44bf6ad48965f83f2ba.

Can you try removing `node_modules` and re-install?
Can you provide a reproducing repo?

**Comment by morgoth** [comment]
I cannot reproduce it anymore when taking another look after some time.
Maybe it was indeed some caching issue...
Sorry for falsy report and thank you for your patience.

**Comment by nicolo-ribaudo** [comment]
Well, we are glad that it's working now even if we couldn't figure out the reason!
