### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ralves87** [babel/babel#13403]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

 verbose stack @babel/types: No matching version found for @babel/types@^7.14.4.

### Configuration file name

package.json

### Current and expected behavior

I'm facing this error in the azure pipeline

### Environment

babel/types: ^7.14.4.

**Comment by nicolo-ribaudo** [comment]
Please see https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67.
