### ISSUE TITLE
Allowing alternative browser compatibility data source for preset-env

### ISSUE THREAD

**Issue by maxloh** [babel/babel#13411]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I encounter the same problem proposed by #11713. 

### Describe the solution you'd like

The compatibility data provided by core-js is rarely updated [(~2-4 commits per month)](https://github.com/zloirock/core-js/commits/master/packages/core-js-compat/src/data.js), so it would be great if we can choose alternative data source, and fall back to core-js if anything is missing.

### Describe alternatives you've considered

- [caniuse-lite](https://www.npmjs.com/package/caniuse-lite) ([~55 updates](https://github.com/Fyrd/caniuse/commits/main) per moth)
- [@mdn/browser-compat-data](https://www.npmjs.com/package/@mdn/browser-compat-data) ([300+ updates](https://github.com/mdn/browser-compat-data/commits/main) per moth)

Both of them are more frequently updated than the core-js equivalent, and more well known as a data source for browser compatibility.

### Documentation, Adoption, Migration Strategy

Add a new config to preset-env for choosing the data source for detecting browser compatibility.

**Comment by JLHwung** [comment]
The compatibility data provided by core-js essentially offers a mapping from browser targets to required core-js polyfills while `caniuse-lite` and `browser-compat-data` offers mapping from browser targets to _features_. If we switch to `caniuse-lite`, we still have to maintain the mapping from _features_ to specific polyfills, which has been actively maintained in `core-js-compat`.

The `caniuse` and `browser-compat-data` also maintain compat data of language features, and the browser versions. This could partially explain why they have more commits than `core-js-compat`. If you find missing features in `core-js-compat`, please open an issue there.

**Comment by maxloh** [comment]
Thx.
