### ISSUE TITLE
comments[Bug]: 

### ISSUE THREAD

**Issue by narbek-abd** [babel/babel#13437]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

my code:
```
/** desc */ 
function main() {
  let a = 1;
}
main();


/** desc */ 
function clone() {  
  let b = 1;
}
```

Result:
```
"use strict";

/** desc */
function main() {
  var a = 1;
}

main();
/** desc */

function clone() {
  var b = 1;
}
```

I expected:
```
"use strict";

/** desc */
function main() {
  var a = 1;
}

main();

/** desc */
function clone() {
  var b = 1;
}
```

### Current and expected behavior

I expected the line feed to be exactly like on my code

### Environment

last versions

**Comment by nicolo-ribaudo** [comment]
@narbek-abd Babel doesn't give any guarantee about the output formatting. If you need to run Babel and to keep the original formatting, you can use Recast similarly to how I did at https://github.com/nicolo-ribaudo/codemods/blob/40e90e3ad6e2db91fd7756bcce68bfefd373a3a3/src/utils.js#L32.
