### ISSUE TITLE
[Bug]: async(x?) should throw

### ISSUE THREAD

**Issue by tony-go** [babel/babel#13446]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
async(x?) // it should throw
```

[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=PTAEAEDMBsHsHcBQiCGBnAngOwMagBQAeA_AJRA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.14.4&externalPlugins=%40babel%2Fplugin-transform-typescript%407.14.4)

### Current and expected behavior

Current: the input is parsed correctly

Expected: it should throw a `Unexpected end of input` (with the token position of course)

### Environment

- Babel version: `7.14.4`
- Electron: `1.8`
- Node: `10.3`

**Comment by nicolo-ribaudo** [comment]
We should also check that just `(x?);` throws.

**Comment by tony-go** [comment]
Once #13419 is merged I switch to this one ^^

**Comment by tony-go** [comment]
Hi @JLHwung and @nicolo-ribaudo 👋 

It's a bit funny but is seems that on the [version 7.14.5](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=IYZwngdgxgFAHgfgJRA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.14.5&externalPlugins=) it works 😆

I also check that it doesn't throw with typescript and flow. But I let you double check.

**Comment by tony-go** [comment]
@JLHwung Maybe we fix it in our previous fix...

**Comment by nicolo-ribaudo** [comment]
Well, it _should_ throw when Flow or TS are enabled :stuck_out_tongue:

**Comment by JLHwung** [comment]
Can confirm it is fixed in #13419 . Because the checking logic was moved to `checkExpressionErrors` and we have already invoked `checkExpressionErrors` when parsing async call:

https://github.com/babel/babel/blob/47ad54a057ed660bdc524ee26a00d5e985696d34/packages/babel-parser/src/parser/expression.js#L796

**Comment by nicolo-ribaudo** [comment]
Oh we should still add a test then.

**Comment by tony-go** [comment]
I'll add it so :)
