### ISSUE TITLE
[Bug]: non-null assertion operator in comparison

### ISSUE THREAD

**Issue by veloek** [babel/babel#13445]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
some.value! < another.value!
```

### Current and expected behavior

I'm getting "SyntaxError: Missing semicolon." in version 7.14.5, but it was working fine in 7.14.4.

### Environment

@babel/parser version 7.14.5

### Additional context

The typescript compiler is not complaining.

**Comment by JLHwung** [comment]
[REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=B4OgXghABAPFoE8JA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react%2Ctypescript&prettier=false&targets=&version=7.14.5&externalPlugins=).
Requires `jsx` and `typescript` parser plugin to reproduce.
Possibly introduced in #13431.

**Comment by veloek** [comment]
Thanks for the quick fix, @JLHwung!

**Comment by prueker** [comment]
When will this fix be released, it's been 4 days, but the broken version 7.14.5 is still the latest version in the repo and npm @JLHwung

**Comment by JLHwung** [comment]
Fixed in `@babel/parser` 7.14.6.
