### ISSUE TITLE
[Bug]: @babel/types 7.14.5 is not getting synchronised with AWS Code Artifact

### ISSUE THREAD

**Issue by pranavams** [babel/babel#13451]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

$ npm install @babel/types@7.14.5 --savedev
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@7.14.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pranavam/.npm/_logs/2021-06-10T17_24_35_029Z-debug.log

---------------------------------------------------------------------------

where as for the version 7.14.4; there is no issue

$ npm install @babel/types@7.14.4 --savedev
npm WARN pms-ui-utils@1.1.17 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @babel/types@7.14.4
added 3 packages from 3 contributors in 1.525s

19 packages are looking for funding
  run `npm fund` for details

### Current and expected behavior

We are using aws code-artifact to store the npm private packages which is inturn connected to npmjs public repository; post the update of 7.14.5 version of babel, the syncrhonization in aws artifact is not happening (mostly due the json file not sending the version update), it still picks up the 7.14.4. 

current behavior
npm install @babel/types@7.14.5 
the above command is expected fetch the module from repo (aws code artifact inturn npmsjs) but it does not.

### Environment

npx: installed 1 in 1.424s

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 12.22.1 - /usr/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/bin/npm

### Additional context

I have removed the cache & the repository in aws code artifact to make sure that I get the new ones.

**Comment by JLHwung** [comment]
Please see https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67.
