### ISSUE TITLE
wierd stuff on website

### ISSUE THREAD

**Issue by thecotne** [babel/babel#1345]
on this page https://babeljs.io/docs/using-babel/
text "For full documentation on the Babel CLI see the usage docs."
is not clickable and selectable

because of this css

![capture](https://cloud.githubusercontent.com/assets/1606993/7327486/a21345b4-eade-11e4-8cbf-03d7927e9fd3.PNG)

**Comment by sebmck** [comment]
See the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
