### ISSUE TITLE
[Bug]: Tokens in record and tuple not transformed for `@babel/eslint-parser` parser

### ISSUE THREAD

**Issue by fisker** [babel/babel#13465]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```js
require('@babel/eslint-parser').parse('#[]', {requireConfigFile: false, babelOptions: { parserOpts: {plugins:[['recordAndTuple',{syntaxType: 'hash'}]], tokens: true}}}).tokens[0]
```

### Current and expected behavior

```text
Token {
  type: TokenType {
    label: '#[',
    keyword: undefined,
    beforeExpr: true,
    startsExpr: true,
    isLoop: false,
    isAssign: false,
    prefix: false,
    postfix: false,
    binop: null,
    updateContext: null
  },
  value: undefined,
  start: 0,
  end: 2,
  loc: SourceLocation {
    start: Position { line: 1, column: 0 },
    end: Position { line: 1, column: 2 },
    filename: undefined,
    identifierName: undefined
  },
  range: [ 0, 2 ]
}
```

### Environment

Latest version of `@babel/eslint-parser`

### Additional context

The `type` property should be a string, and `value` property should not be `undefined`.

`#{`, `{|`, `|}`, `|]` tokens also need fix.

**Comment by nicolo-ribaudo** [comment]
We need to add those four tokens to the list of `Punctuator` tokens to convert, at https://github.com/babel/babel/blob/f808a3eb148c53437e5560fe886c9702b45a6076/eslint/babel-eslint-parser/src/convert/convertTokens.cjs#L99-L139

We can then add a test similar to
https://github.com/babel/babel/blob/f808a3eb148c53437e5560fe886c9702b45a6076/eslint/babel-eslint-parser/test/index.js#L325-L333
making sure to test both the `["recordAndTuple", { syntaxType: "hash" }]` and `["recordAndTuple", { syntaxType: "bar" }]` syntax variants.

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add the tests
1. Update the code!
1. `yarn jest eslint-parser` to run the tests
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by lala7573** [comment]
I'd like to fix it. Can I try?

**Comment by existentialism** [comment]
@lala7573 let's wait a bit (2 hours?) to see if any first-time contributors pop in... otherwise, it's yours!

**Comment by lala7573** [comment]
@existentialism 
Oh, ok. It would be better if first time contributor get this issue.
Is there any alternative that I can try? I'd like to contribute and watch some issues but it's hard to find.

**Comment by existentialism** [comment]
@lala7573 welp, no takers, still up for tackling this?

**Comment by plourenco** [comment]
Not sure if I'm still on time, but without anticipation, if there's still a chance I would like to contribute! :)

**Comment by nicolo-ribaudo** [comment]
@plourenco It's yours!

**Comment by plourenco** [comment]
Thanks @nicolo-ribaudo. May I also ask, aside from the above (`#{, {|, |}, |]`), don’t `#[` and `[|` need to be added as Punctuators as well?

**Comment by nicolo-ribaudo** [comment]
Right, yes!
