### ISSUE TITLE
[Bug]: wrong key assignment with antd 

### ISSUE THREAD

**Issue by vadeneev** [babel/babel#13461]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

https://codesandbox.io/s/bold-pond-g5nzv

### Current and expected behavior

If you will try to check example - you will notice that submenu items have collision with key names, however, if you will check what are expected assignment to this keys - they are no issue supposed to be. Moreover this code is working right now, but with different packages, mostly with 7.12.13, after I tried to re-generate my lock.yarn file - application gets broken.

Expected behavior:
Submenus in that particular case shouldn't have key's collision/duplication and as single-players.

Current behavior:
If you will expand any submenu - you will see warnings about duplicated keys also, if you will hover any sub-menu's item - they all will be highlighted, because of the same key value.

### Environment

Node 12

### Possible solution

Possibly it might be caused somewhere in between 7.12.13 and latest one

### Additional context

Tried this on on manual config and with react-scripts, after new installations (yarn re-generation as well) - code works with issue. If i compile my code with old yarn.lock file for manual config (based on 7.12.13) - everything works as expected.

**Comment by JLHwung** [comment]
It seems that when React is rendering sub menu items, the `restProps` contains an `eventKey` attribute, inherited from the parent `NavMenuItem` component, with higher priority than the specified `key`. So a workaround is add `eventKey={subLevelItem.path}` after `{...restProps}` so the `NavMenuItem` can get the correct sub menu key.

```jsx
function NavMenuItem(props) {
  const {
    children,
    title,
    id,
    path,
    displayIcon,
    menuLevel,
    suburlPrefixes,
    ...restProps
  } = props;
  const isSubmenu = Array.isArray(children) && children.length && !menuLevel;

  return isSubmenu ? (
    <Menu.SubMenu {...restProps} title={title}>
      {children.map((subLevelItem) => (
        <NavMenuItem
          key={subLevelItem.path}
          {...restProps}
          // override eventKey in restProps
          eventKey={subLevelItem.path}
          {...subLevelItem}
          menuLevel={menuLevel + 1}
        />
      ))}
    </Menu.SubMenu>
  ) : (
    <Menu.Item {...restProps}>
      <span>{title}</span>
    </Menu.Item>
  );
}
```
[Sandbox link](https://codesandbox.io/s/vibrant-fire-69beg?file=/src/menu/item.js:57-725).

**Comment by vadeneev** [comment]
Thanks a lot! It looks so crazy that it works this way, I was confused that it worked before (it contains same version of antd and rc was used)
