### ISSUE TITLE
Call for contributors!

### ISSUE THREAD

**Issue by sebmck** [babel/babel#1347]
So Babel has become a pretty big beast. I'm looking for contributors. Right now contributions have been pretty [inconsistent](https://github.com/babel/babel/graphs/contributors). Don't get me wrong, I love and appreciate all contributions but at the end of the day I'm still maintaining Babel and attend to the majority of the bug fixes and new features. This can become incredibly stressful and in the interests of my personal free time and sanity I'd like for that to change.

### Documentation/Website

Seriously, this is mega-important. The documentation so far has been great and has been a killer feature of Babel. There are sections that could certainly use some work and even the addition of a paragraph here or there is extremely appreciated.

If you have any free time and you see areas of the documentation that you think can be improved please submit a pull request. See the [babel.github.io](https://github.com/babel/babel.github.io) repo for the website source.

---

### Work on Babel core

Feel free to ping me on [slack](https://babel-slack.herokuapp.com/) if you have any specific internal questions. I'll be looking into doing some screencasts on the internals and/or blog posts to ease the transition into the code base for newcomers.

If you're looking to dive in and fix something, consider picking from the list of issues labeled [`good first bug`](https://github.com/babel/babel/labels/good%20first%20bug).

**Note about pull requests**

Please note that before any significant contributions (feature additions etc) I'd love if an issue was open prior discussing what it is you want to do. There's nothing worse than having to turn down a PR if it could have been avoided prior to all the effort being put in.

#### Optimisations

This is an area that hasn't really been given much love since @gaearon did some V8 optimisations.

The [code generator](https://github.com/babel/babel/tree/master/src/babel/generation) is an area that needs a lot of work, it takes exponentially longer the larger the source file is, this is crap. Files that are megabytes or hundreds of kilobytes should not take a million years to generate. This will be especially important moving forward as Babel becomes a more general JavaScript transformer.

---

### Respond to issues

Responding to issues is another extremely effective way to help out. I've been trying to keep support and questions out of [GitHub issues](https://github.com/babel/babel/issues?utf8=%E2%9C%93&q=see+the+readme), even though the README is literally 3 lines, some people don't seem to read it. Pointing these people in the right direction (eg. to slack, website repo, StackOverflow etc) is extremely appreciated.

---

### Answer questions on [slack](https://babel-slack.herokuapp.com/)

Babel has an incredibly active [slack channel](https://babel-slack.herokuapp.com/). Slack has an [IRC bridge](https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP) as well as a range of [apps](https://api.slack.com/community) which makes idling and answering questions super easy.

---

### Anything else!

Seriously, **any** contributions are appreciated.

---

Thank you in advance to anyone who helps out!

:nail_care: :sparkles:

**Comment by sebmck** [comment]
Also [here](https://speakerdeck.com/sebmck/babel-facebook-talk) are the slides from a recent talk I did where I scratched the surface of the Babel architecture. Some of it may be a bit confusing without the accompanying audio but hopefully it gives a good basic overview :)

**Comment by sebmck** [comment]
Oh and a shoutout to all the awesome people who've helped out so far! @gaearon @RReverser @#2neVERberleRfellerER @eventualbuddha @webpro @AluisioASG @monsanto @sindresorhus Thank you so much!

Separate shout out to @thejameskyle who made the awesome [babejs.io website](http://babeljs.io) and who's been invaluable to Babel community outreach and management. Seriously, thank you :heart:

**Comment by bloodyowl** [comment]
I just started to watch the repo to be able to answer to new issues.
I might also work a bit on the core if needed.

![you_have_my_sword](https://cloud.githubusercontent.com/assets/1688645/7330389/11ccbff2-eaee-11e4-8c9d-b53c7e2a36af.jpg)

**Comment by monsanto** [comment]
@sebmck Thanks for the shoutout, and I'll help out in any way I can. Honestly I wanted to help out more in the beginning, but the project was moving so quickly that I was afraid the internals were going to completely change by the time I was done with a fix/feature/whatever. Totally a compliment btw :stuck_out_tongue:

I've been responding to issues for a while so if you want to give me the power to tag/close stuff I can try to take that off your plate.

**Comment by TheAlphaNerd** [comment]
I started watching the repo... I'll see what I can do to help out!

**Comment by sebmck** [comment]
@monsanto 

> Honestly I wanted to help out more in the beginning, but the project was moving so quickly that I was afraid the internals were going to completely change by the time I was done with a fix/feature/whatever

Main reason is that I had no idea what I was doing as this has all been a learning exercise for me. I didn't know how to architect something like but it's now in a stable place and the internal architecture is extremely unlikely to change and any major changes will be discussed in an issue beforehand.

> I've been responding to issues for a while, I could help with tagging/closing stuff if you want?

Sounds good to me :smile: 

@TheAlphaNerd Rad, thanks!

**Comment by torifat** [comment]
I'm in :smile: since I'm using `babel` for my `React` codes.

**Comment by zcei** [comment]
Started watching and looking forward for some contribution!

Will start of with issues / docs to get used to the source, then I'd love to contribute some code where needed.

Awesome lib so far, let's keep up the good work together :+1:

**Comment by loganfsmyth** [comment]
Mostly trying to help in Gitter, but also watching and trying to help with opened issues when I can. Will try to do more as time allows. :D

**Comment by jquense** [comment]
Watching! will try to help where I can, hope you can get some rest and space to do other things

**Comment by ameyms** [comment]
I tried going through the slides, but I found it difficult to understand without audio.
@sebmck - Maybe you could have a "**good-first-bug**" label? That ways, people new to the codebase can start squashing bugs that might be trivial to you and in that process gain more insight into the codebase.

**Comment by lukescott** [comment]
@sebmck, first off I want to say you've done an amazing job. It's rare to see a project with such a low open to close issue ratio. Currently 20 open issues out of 1,150. That is 1% of the total issues. That is amazing! Many well maintained projects with several contributors are around 20%. And you do this in your free time!? Dude, you are a rock star! I can't express enough the appreciation I have for this project!

Most of what I've contributed thus far has impacted me directly with a work project. I don't have much in the free time department yet, but I want to contribute in any way that I can.

**Comment by boopathi** [comment]
I'm using it for all my projects. I'm in.

**Comment by mithun-daa** [comment]
The starter videos would help immensely.

**Comment by vnovick** [comment]
started to watch repo. Count me in :)  I'm using babel for my projects, so will gladly contribute

**Comment by benjamingr** [comment]
I'm going to mention this issue in a talk I'm giving, so I apologize in advance if people show up :) Hopefully. I think an internals guide would go a huge way to help - as well as a tutorial on writing a transformer.

**Comment by jmm** [comment]
I'm finding the babel code base rather difficult to get up to speed with. I've looked at the slides and they're not much help. More documentation about the architecture would be helpful, as would more comments in the source code. Do you have any plans to add a lot of comments to the source anytime soon, and would you be open to PRs for that?

**Comment by sebmck** [comment]
There are already a bunch of method JSDoc comment placeholders that I’m planning on filling in. Most of the code is fairly self-documenting and the codebase is always going to be difficult to get into if you don’t already understand the core concepts (ASTs etc).

**Comment by sebmck** [comment]
Also thanks everyone for your kind words and interest in contributing! In the coming weeks i'll hopefully be able to put together better contribution guides and architecture documents. I've recently created a [Babel Slack](https://babel-slack.herokuapp.com/) to foster of a "Babel Community", so if you're still interested in helping out then I'd recommend getting on the slack and joining `#development`, I'm more than happy to organise collaboration/contribution and to answer architectural questions.

**Comment by jmm** [comment]
> There are already a bunch of method JSDoc comment placeholders that I’m planning on filling in.

:thumbsup:

> Most of the code is fairly self-documenting

That hasn't been my experience so far. Possibly you're overestimating this effect.

> and the codebase is always going to be difficult to get into if you don’t already understand the core concepts (ASTs etc).

Understood, but that's not the only issue.

**Comment by sebmck** [comment]
> That hasn't been my experience so far. Possibly you're overestimating this effect.

Well yeah, I'm obviously a bit biased :stuck_out_tongue: 

> Understood, but that's not the only issue.

Can you elaborate then?

**Comment by jmm** [comment]
> Can you elaborate then?

A lot more source code comments is really obvious, low-hanging fruit. Currently, even just looking at a single file and trying to understand what the methods do and how they interact is a pain. It gets worse when you start trying to connect the dots between files. That's a lower-level problem than understanding concepts like ASTs.

Take [this file](https://github.com/babel/babel/blob/0918da856938f1c30b199a8b1d34ce689134d39f/src/babel/transformation/file/index.js) for example. I don't think there's so much as one method that has a description or notation about return value. That creates a lot of friction for gaining an understanding of the code base.

**Comment by sebmck** [comment]
Ah yeah, that's true. I've never maintained a large open source project before and have always worked independently so this is all a learning experience for me :smile:  so thanks for the constructive criticism! I'll work on improving that.

**Comment by jmm** [comment]
@sebmck 
> Ah yeah, that's true. I've never maintained a large open source project before and have always worked independently so this is all a learning experience for me :smile: I appreciate the constructive criticism and will work on improving internal docs and code structure.

Awesome, thank you! If you want I can try PR'ing source comments if / when I figure those kinds of things out.

**Comment by vtambourine** [comment]
> Feel free to ping me on gitter..

Please, change link to gitter chat with slack chat in the desription.

**Comment by eventualbuddha** [comment]
@vtambourine I updated the initial comment to refer to Slack instead of Gitter. Thanks for pointing that out.

**Comment by jmm** [comment]
@eventualbuddha Would probably also be good to mention the [`good first bug`](https://github.com/babel/babel/labels/good%20first%20bug) label in the initial comment, if you feel like making the edit.

**Comment by eventualbuddha** [comment]
@jmm done.

**Comment by jmm** [comment]
@eventualbuddha Thanks.
