### ISSUE TITLE
[Bug]: babel-node: AsyncLocalStorage.run() cause an error

### ISSUE THREAD

**Issue by wvq** [babel/babel#13484]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

this example code from nodejs api:
https://nodejs.org/dist/latest-v14.x/docs/api/async_hooks.html#async_hooks_class_asynclocalstorage

```js
const http = require('http');
const { AsyncLocalStorage } = require('async_hooks');

const asyncLocalStorage = new AsyncLocalStorage();

function logWithId(msg) {
  const id = asyncLocalStorage.getStore();
  console.log(`${id !== undefined ? id : '-'}:`, msg);
}

let idSeq = 0;
http.createServer((req, res) => {
  asyncLocalStorage.run(idSeq++, () => {
    logWithId('start');
    // Imagine any chain of async operations here
    setImmediate(() => {
      logWithId('finish');
      res.end();
    });
  });
}).listen(8080);

http.get('http://localhost:8080');
http.get('http://localhost:8080');
```

### Configuration file name

babel.config.json

### Configuration

{
  "presets": ["@babel/preset-env"]
}

### Current and expected behavior

babel-node cause an error
```bash
node example/context/index          
0: start
0: finish
1: start
1: finish
```

```bash
npx babel-node example/context/index
[1]    84950 segmentation fault  npx babel-node example/context/index
```

### Environment

  System:
    OS: macOS 11.3
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.16.0 - ~/.nvm/versions/node/v16.3.0/bin/npm
  npmPackages:
    @babel/cli: ^7.14.5 => 7.14.5 
    @babel/core: ^7.14.6 => 7.14.6 
    @babel/node: ^7.14.5 => 7.14.5 
    @babel/plugin-proposal-decorators: ^7.14.5 => 7.14.5 
    @babel/plugin-transform-runtime: ^7.14.5 => 7.14.5 
    @babel/preset-env: ^7.14.5 => 7.14.5

**Comment by nicolo-ribaudo** [comment]
This is a Node.js bug (segfaults are always Node.js bugs), but it looks like it has been fixed in Node.js 16.4.
