### ISSUE TITLE
More correct work with symbols

### ISSUE THREAD

**Issue by zloirock** [babel/babel#1348]
[`core-js` 0.9](https://github.com/zloirock/core-js#090---20150424) adds support correct symbol descriptors. For correct work in [this](https://github.com/zloirock/core-js/issues/45) and similar cases, need:

* Revert [this](https://github.com/babel/babel/issues/1010#ref-commit-8d3a7ac) change
* Add to `runtime` `Object.{create, defineProperty, defineProperties}` entry points

**Comment by sebmck** [comment]
Fixed as of 5.1.12, thanks!

**Comment by zloirock** [comment]
@sebmck also need remove `Symbol` check from `_defineProperty` helper.

**Comment by sebmck** [comment]
Done.

**Comment by zloirock** [comment]
:thumbsup:
