### ISSUE TITLE
[Bug]: transpiled `for await` has different behavior than untranspiled `for await`

### ISSUE THREAD

**Issue by danieltroger** [babel/babel#13490]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
let resolve;
let promise = new Promise((r) => (resolve = r));
let iterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        return promise;
      },
    };
  },
};

(async () => {
  for await (let value of iterable) {
    console.log(value);
  }

  // let iterator = iterable[Symbol.asyncIterator]();
  // while (true) {
  //   let result = await http://iterator.next();
  //   if (result.done) {
  //     break;
  //   }
  //   console.log(result.value);
  // }
})();

(async function () {
  for (let v of [0, 1]) {
    await null;
    let oldresolve = resolve;
    promise = new Promise((r) => (resolve = r));
    oldresolve({ value: v, done: false });
  }
  resolve({ value: undefined, done: true });
})();
```

### Configuration

I think it's this? But you just need any configuration that correctly loads regenerator runtime and transpiles async functions. I tried to load `babel-plugin-transform-runtime` or something to make it load in the REPL but the REPL just showed error messages, sorry.

Please set target to `ie 11`.

```
{
  "presets": ["@babel/preset-typescript", "@parcel/babel-preset-env"],
  "plugins": [
    ["@parcel/babel-plugin-transform-runtime"],
    ["@babel/plugin-proposal-private-methods", { "loose": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
  ],
};
```

### Current and expected behavior

Running the untranspiled code yields this output:

```
0
1
```

Running the transpiled code yields this output:
```
0
```

### Environment

- Babel 7.14.5 (@babel/core 7.14.6)
- Node v16.3.0
- npm 7.15.1
- macOS 10.15.7 (19H1217)

### Possible solution

Make the transpiled code behave/output the same as the untranspiled code.

### Additional context

If you replace the `for await` loop with the commented out while loop the transpiled code behaves as expected.

Kudos to @mischnic  for simplified repro code.

**Comment by danieltroger** [comment]
@kdy1 SWC has the same issue FYI. But I'll wait for babel telling me whether this is a bug or actually impossible to transpile before opening an issue with SWC.

**Comment by mischnic** [comment]
> But you just need any configuration

For example this without any config file: `babel --presets @babel/preset-env --plugins @babel/plugin-transform-runtime index.js -o dist/babel.js`
and then comparing `node index.js` and `node dist/babel.js`

**Comment by nicolo-ribaudo** [comment]
A slightly simplified example:
```js
let resolve;
let promise = new Promise((r) => (resolve = r));
let iterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        return promise;
      },
    };
  },
};

(async () => {
  for await (let value of iterable) {
    console.log(value);
  }
})();

(async function () {
  resolve({ value: 0, done: false });
  promise = new Promise((r) => (resolve = r));

  await null;
  resolve({ value: 1, done: false });
  promise = new Promise((r) => (resolve = r));

  resolve({ value: undefined, done: true });
})();
```

This happens even without compiling async functions (compiling `for await` is enough to see the bug).

[repl](https://babeljs.io/repl#?browsers=chrome%2055&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBATiDOD2wBuIDcAoUkAOV4FsBLWECAXggDsQB3CABTyJIAoWoBKcgPgnbkQpy0DhwxYIhMCCgBDAEahhAb3QQIAbQDKAT3zzEAOlmwdlAMYBJaXLDwoAXRZdV69TDABXKJQiu36tQAHmDOfmoBbh7evrgExGgRAQC-ADRJEMkY6mnoWejoLCZm5nxcZLz-AGb2ELI0slJ8EkiywJ6k8FWSNgqgLhnm8JQIoIbA8ADmLK3tIGIRyXkczhiFxRYQVZ4WYITDZeHuAsggLMoQsx0AXBAADKkQACbDILdVbSSZC-pxzKQUah0RjxVjscq8fijIQUTgLCL1RqQSieYDAbLQE4oc6XNo3CAARkeL2o70-pGSPwgfwSwiBDCYCTYnB4fBg0IBInhxw5OKubwgOyeICqhGoT2Jr1uYCgHW-GEpq3QQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.6&externalPlugins=) (copy/parse the input and output in the console to see the actual and expected results)

If I replace `await null` with `await null; await null` it works, so there is an extra tick somewhere in the `for await` compiled code.

**Comment by nicolo-ribaudo** [comment]
While working on a fix, I found another bug:
```js
let resolve;
let promise = new Promise((r) => (resolve = r));
let iterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        return Promise.resolve({
          get value() { throw new Error("ERR") },
          done: true
        });
      },
    };
  },
};


(async () => {
  for await (let value of iterable) {
    console.log(value);
  }
})();
```

When compiled, this code throws.

**Comment by danieltroger** [comment]
Hey @nicolo-ribaudo, do you know when @hzoo is back from vacation?

Also, sorry for being impatient lol. I can't wait to do freaky things with `for await`.
