### ISSUE TITLE
[Bug]: Uncaught SyntaxError: The requested module '/node_modules/@babel/runtime/regenerator/index.js?v=8bc5bdce' does not provide an export named 'default'

### ISSUE THREAD

**Issue by JesusTheHun** [babel/babel#13498]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Using `esbuild` and `@testing-library/dom` I run into this error : 

`Uncaught SyntaxError: The requested module '/node_modules/@babel/runtime/regenerator/index.js?v=8bc5bdce' does not provide an export named 'default'`

Because `@testing-library/dom` uses `import _regeneratorRuntime from '/node_modules/@babel/runtime/regenerator/index.js';

Sadly this file https://github.com/babel/babel/blob/main/packages/babel-runtime/regenerator/index.js lacks of the `default` export.

### Current and expected behavior

`https://github.com/babel/babel/blob/main/packages/babel-runtime/regenerator/index.js` should have the `default` export.

### Environment

`@babel/runtime@7.14.6`

` System:
    OS: macOS 11.4
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 2.4.1 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  npmPackages:
    @babel/core: ^7.14.6 => 7.14.6 
    @babel/eslint-parser: ^7.14.5 => 7.14.5 
    babel-loader: ^8.2.2 => 8.2.2 
    eslint: ^7.5.0 => 7.28.0 
    jest: ^27.0.4 => 27.0.4 
`

### Possible solution

Add the default export

**Comment by nicolo-ribaudo** [comment]
`regenerator-runtime` only provides a CJS entry point. You need to configure your bundler to support CJS files, or you cannot transform generators to ES5.

**Comment by nrgnrg** [comment]
I'm also using `esbuild` and `@testing-library/react` and am getting this error

**Comment by nicolo-ribaudo** [comment]
You need to configure `esbuild` to be able to import commonjs files.

**Comment by FuShanChuan** [comment]
Would like to ask how the final solution?

**Comment by nicolo-ribaudo** [comment]
This is an esbuild configuration problem; it's unlikely that someone in this repository can help 😅
