### ISSUE TITLE
[Bug]: Problems after using transform-arrow-functions

### ISSUE THREAD

**Issue by Jeggery** [babel/babel#13493]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

const onClose = async () => {
  await query.init();
};
Asynchronous arrow function error
![微信截图_20210621173921](https://user-images.githubusercontent.com/39072827/122741855-f79c5d00-d2b7-11eb-8f70-2931e3efea25.png)

### Current and expected behavior

To solve the problem：  Cannot instantiate an arrow function error

### Environment

"@babel/cli": "7.12.10",
    "@babel/core": "7.12.10",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/plugin-transform-arrow-functions": "^7.14.5",
    "@babel/plugin-transform-async-to-generator": "^7.14.5",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.5",
    "@babel/preset-typescript": "^7.12.1",
    "@babel/runtime": "^7.12.1",
    "@mapbox/vector-tile": "^1.3.1",
    "@pmmmwh/react-refresh-webpack-plugin": "0.4.2",
    "@svgr/webpack": "5.4.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/react-hooks": "^4.2.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "@typescript-eslint/eslint-plugin": "^4.5.0",
    "@typescript-eslint/parser": "^4.5.0",
    "antd": "4.9.4",
    "axios": "^0.21.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.0",
    "babel-loader": "8.1.0",
    "babel-plugin-dva-hmr": "^0.4.2",
    "babel-plugin-import": "^1.13.1",
    "babel-plugin-named-asset-import": "^0.3.7",
    "babel-preset-react-app": "^10.0.0",

**Comment by nicolo-ribaudo** [comment]
I tried compiling this code with your configuration:
```js
const query = {
  async init() {}
}

const onClose = async () => {
  await query.init();
};

onClose().then(() => console.log("It works!"))
```

and it correctly logs `It works!` without throwing any error. Can you provide a complete example that shows the bug?
