### ISSUE TITLE
Default export of anonymous template string throws

### ISSUE THREAD

**Issue by wbinnssmith** [babel/babel#1349]
Hi! Thanks for babel, it's truly incredible. All of your effort amazes me and it's really appreciated.

Under the latest babel 5, acorn throws a parse error when trying to compile a default export of an anonymous template literal. Under babel 4, the same example compiles just fine:

```
export default `foo`;
```

I assume this is valid es6. If it's not, was babel/acorn adjusted to adhere closer to spec, and that's why it compiles in babel 4.x?

Thanks again.
Will

**Comment by monsanto** [comment]
Confirmed; as a workaround, you can put parens around the expression, as follows:

```export default (`foo`)```

**Comment by monsanto** [comment]
Upstream acorn handles this fine, looks like the problem is on our end
