### ISSUE TITLE
[Bug]: `abc${ true ? 'true' : 'false' }` err

### ISSUE THREAD

**Issue by cocobino** [babel/babel#13519]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

When Babel compiles strings, there is a bug as follows.

```
'abc'${ true ? 'true' : 'false' }`;
```

correct answer : `abctrue` 

but babel compile wrong answer as follow
with an invalid `concat` string function.

### Configuration file name

.babelrc

### Configuration

{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "ie >= 11"
          ]
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-transform-arrow-functions",
    "@babel/proposal-optional-chaining",
    "@babel/proposal-object-rest-spread",
    "@babel/plugin-proposal-class-properties"
  ]
}

### Current and expected behavior

In the past, there are cases where legacy code creates and puts a DOM with a string.
```
'abc'.concat(function() {
if(true) return 'true'; else return 'false';
});
```

wrong answer :` "abcfunction() {\nif(true) return 'true'; else return 'false';\n}"`

### Environment

{
"@babel/cli": "^7.7.0",
    "@babel/core": "^7.12.13",
    "@babel/preset-env": "^7.12.13",
    "babel-loader": "^8.2.2"
}

### Possible solution

just get the result of executing the function.
```
'abc'.concat(function() {
if(true) return 'true'; else return 'false';
}());
```

right answer : "abctrue"

**Comment by fedeci** [comment]
Could you update `@babel/preset-env` to the last version?
I can't reproduce the error in Babel REPL.

**Comment by nicolo-ribaudo** [comment]
Are you sure that there is no other tool transforming your code (maybe a webpack plugin, or a minifier)? Babel doesn't wrap the `? :` operator in functions.
