### ISSUE TITLE
[Bug]: babel fails on flow definition file, if modules in it have imports with the same name

### ISSUE THREAD

**Issue by zxbodya** [babel/babel#13510]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
//@flow

declare module 'test' {
  import type { JSONSchema7 } from 'json-schema';
}

declare module 'test/submodule' {
  import type { JSONSchema7 } from 'json-schema';
}
```

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011%2C%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=PTACDMBsHsHcCh4BMCmBjSBDATigBALbRICuk-A5AC4oDOVFeA3vHngJYEAO02VeVAJ5d8TPACkAygHkAcpLQALFAUwB2PAF884bNAJ4KAK1rQAdgFpaSlZgoBueJsSoMOfEVLlDNesFokAEaeZCiMLGycPHwCwqISMvI2qhrauvqGJuZWyXaOzvBAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cflow&prettier=false&targets=&version=7.14.7&externalPlugins=)

### Current and expected behavior

 There is an error about duplicate declaration:
 
```js
Duplicate declaration "JSONSchema7"
   6 |
   7 | declare module 'test/submodule' {
>  8 |   import type { JSONSchema7 } from 'json-schema';
     |                 ^^^^^^^^^^^
   9 | }
  10 |
  11 |
 ```
 
But, it should be allowed to have same imports in different modules

### Environment

not specific to the environment

### Additional context

Found this when trying traverse an ATS from parsing flow definitions file ([code where it happens](https://github.com/zxbodya/flowts/blob/master/packages/cli/src/detectOptions.ts)).

**Comment by colinaaa** [comment]
I would like to work on this!

Seems that not only flow has this problem, the input code is also valid for typescript but complained by babel

```ts
// test.ts
declare module 'test' {
  import type { JSONSchema7 } from 'json-schema';
}

declare module 'test/submodule' {
  import type { JSONSchema7 } from 'json-schema';
}
```
