### ISSUE TITLE
[Bug]: Module block should be allowed in member expression

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#13533]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
module {}.foo
```

[AST Explorer](https://astexplorer.net/#/gist/db4b1a51b7645517f2a3c2f9690fbd6b/447c886c9745c468c1774b4e3dbe126d188e3520)

### Current and expected behavior

Current: Parsing fails
Expected: Parsing succeeds

According to the [spec](https://github.com/tc39/proposal-js-module-blocks#syntax-details), InlineModuleExpression (`module {}`) is a primary expression, so it should be allowed before the `.` in a member expression.

### Environment

- Babel versions: 7.14.5

### Possible solution

The module block is parsed in `Parser#parseMaybeUnary`

https://github.com/babel/babel/blob/bc1b9537b00499f462aa3ac0d49e30314a66f413/packages/babel-parser/src/parser/expression.js#L511-L517

which aligns to the [UnaryExpression](https://tc39.es/ecma262/#prod-UnaryExpression) in the spec. It should be moved to `Parser#parseExprAtom`, which handles PrimaryExpression.

https://github.com/babel/babel/blob/bc1b9537b00499f462aa3ac0d49e30314a66f413/packages/babel-parser/src/parser/expression.js#L971

Specifically we can extend the current logic for `tt.name` token and handle the `module {}` checks here: https://github.com/babel/babel/blob/bc1b9537b00499f462aa3ac0d49e30314a66f413/packages/babel-parser/src/parser/expression.js#L995

**Comment by nicolo-ribaudo** [comment]
If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test at https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/experimental/module-blocks (only `input.js`; `output.json` will be automatically generated)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by nme077** [comment]
I’m getting started on this bug. It’ll be my first.

**Comment by JLHwung** [comment]
@nme077 Thanks! I have assigned the issue to you. Feel free to reach out if you have questions when developing a fix.

**Comment by nme077** [comment]
This is my first time contributing. How do I add a test? The instructions above make it sound like it is auto generated, but I am unsure how to generate it. Thanks for your help!

**Comment by JLHwung** [comment]
You can create an `input.js` in https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/experimental/module-blocks with following content

```js
module {}.foo
```

Now that you can run `yarn jest babel-parser`, `output.json` will be automatically generated. In your case, you will instead see an `options.json`
```json
{
  "throws": "Unexpected token"
}
```
because parser thinks the code is invalid and throwing an error. Now we can run `make watch` to host development server, make suggested code changes, and see if the AST `output.json` will be generated.

**Comment by nme077** [comment]
@JLHwung thanks for the help! I added that file and ran the command to generate the options.json and it doesn't seem to work. I get this error. 
<img width="1695" alt="Screen Shot 2021-07-11 at 1 23 37 PM" src="https://user-images.githubusercontent.com/55118955/125207775-6a5f7f00-e24b-11eb-862f-b603a58b699e.png">

**Comment by JLHwung** [comment]
You can safely ignore this error. Though I am wondering why this test fails. Not sure if it helps but you can try rerunning "make bootstrap".

**Comment by nme077** [comment]
Thank you for your help. I made the changes, but am still running into issues running the tests. After some time, I found what I think might be the cause. The `devDependencies` that use "workspace:*" for the version are causing "Cannot find module" errors. I have run all of the commands suggested previously with no luck. 

My understanding is that those versions should be replaced automatically with the most current version. Any thoughts on how to fix this?

Here is an example of the errors I get when running `yarn jest babel-parser`


    Test suite failed to run

    Cannot find module '@babel/helper-fixtures' from 'packages/babel-parser/test/helpers/runFixtureTests.js'

    Require stack:
      packages/babel-parser/test/helpers/runFixtureTests.js
      packages/babel-parser/test/estree-throws.js

    > 1 | import { multiple as getFixtures } from "@babel/helper-fixtures";
        | ^
      2 | import { codeFrameColumns } from "@babel/code-frame";
      3 | import fs from "fs";
      4 | import path from "path";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:311:11)
      at Object.<anonymous> (packages/babel-parser/test/helpers/runFixtureTests.js:1:1)`

**Comment by JLHwung** [comment]
Did you run `make build`? It seems to me that `packages/babel-helper-fixtures/lib` is empty.

See also https://github.com/babel/babel/blob/main/CONTRIBUTING.md#setup for how to setup your dev environment.

**Comment by nme077** [comment]
@JLHwung I finally found the issue with setting up my dev environment. I was using a version of node.js that is not supported. Now I will get to solving the actual issue at hand. Thanks for your help!

**Comment by dhrubesh** [comment]
Hi, @nme077 are you still working on this? I would like to jump in if you've not gotten the chance to pick it up yet?

**Comment by nme077** [comment]
I have. I am just putting it through final testing and will make a PR later today.
