### ISSUE TITLE
[Bug]: _inherits dose not support that superClass is undefined

### ISSUE THREAD

**Issue by lancewuz** [babel/babel#13556]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
var superClass = undefined;
class subClass extends superClass {}
```

### Configuration file name

babel.config.json

### Configuration

```json
{}
```

### Current and expected behavior

_inherits supports undefined, since it supports null.

### Environment

babel version v7.12.0

### Possible solution

https://github.com/babel/babel/blob/main/packages/babel-helpers/src/helpers.js#L344-L346
&& (superClass !== null || superClass !== undefined)

### Additional context

no

**Comment by nicolo-ribaudo** [comment]
Classes cannot extend `undefined`. If you try running that code directly in your browser (without transpiling), you'll get an error.
