### ISSUE TITLE
[issue with 7.4.4 version]build babel-types@7.4.4 locally

### ISSUE THREAD

**Issue by varunmankal** [babel/babel#13557]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

- git clone https://github.com/babel/babel.git
- git checkout tags/v7.4.4 -b branch-7.4.4
- make bootstrap

### Current and expected behavior

current behavior:
When I run the command: make bootstrap, I get the error 
Couldn't find match for "49861d37095db2ba9dfb4e0e23457c9913a1b87f" 

### Environment

- node v8.17.0
- npm v6.13.4
- macOS 10.15.7

### Additional context

I am trying to build babel-types@7.4.4 package locally on my machine.

**Comment by JLHwung** [comment]
The build error comes from https://github.com/babel/babel/blob/2c88694388831b1e5b88e4bbed6781eb2be1edba/package.json#L73

It is a forked lerna that we used to determine which package should be used. You can safely remove the resolution field and build your own babel-types fork.
