### ISSUE TITLE
Type inference is fragile and somewhat unpredictable

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1355]
Another thing I noticed while playing around:

```
var x = [1,2];
x = {};
[3, ...x];
```

compiles to 

```
var x = [1, 2];
x = {};
[3].concat(x);
```

whereas

```
var x = {};
[3, ...x]
```

compiles to

```
var x = {};
[3].concat(_toConsumableArray(x));
```

**Comment by sebmck** [comment]
Looks like a bug. I purposely made it not do anything on reassigned bindings since the type inference, as you can tell, is extremely dumb.

**Comment by deebloo** [comment]
If I wanted to look into it where do you think the problem resides?

**Comment by sebmck** [comment]
It'd be a bit intricate. [Here](https://github.com/babel/babel/blob/master/src/babel/traversal/path/index.js#L829) would be a good starting point.

**Comment by deebloo** [comment]
ok cool. I will see how much trouble I can get myself into :)
