### ISSUE TITLE
[Bug]: variance is missing from NODE_FIELDS.ClassProperty 

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#13558]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
console.log(require('@babel/types').NODE_FIELDS.ClassProperty.variance)
```

### Configuration file name

.babelrc

### Configuration

```json
{
  "presets": [["@babel/preset-env", { "targets": { "node": "current" } }], "@babel/preset-flow"]
}
```

### Current and expected behavior

Expected `NODE_FIELDS.ClassProperty.variance` to be defined, but it isn't.

Parsing the following code produces a `ClassProperty` with a `variance` field:

```js
class Foo {
  +blah: number 
}
```
https://astexplorer.net/#/gist/40f552d7977ffe512792d48ccb584ced/a9dcd37f91fc623481253f94835888b04c744136

### Environment

- `@babel/types` version: 7.14.5

### Possible solution

copy over the `variance` field definition from `ObjectTypeProperty` to `ClassProperty`

**Comment by nicolo-ribaudo** [comment]
Good catch! This needs to be fixed in this list: https://github.com/babel/babel/blob/bfcf783834cbe293ca540e84c1ad285ed2e728e2/packages/babel-types/src/definitions/core.ts#L2067

I'm assigning this bug to you since you ticked "I would like to work on a fix"; feel free to ask if you need any help!

**Comment by JLHwung** [comment]
We should also add `variance` to `ClassPrivateProperty`.

**Comment by jedwards1211** [comment]
Sounds good

**Comment by jedwards1211** [comment]
@nicolo-ribaudo I'm wanting to make a test that scans all the `@babel/parser` output fixtures, and checks to see if any AST nodes in those have fields that are missing from the `@babel/types` defs, so that we can catch missing fields like this going forward.

But I doubt it's appropriate to have tests from `@babel/types` depend on content in `@babel/parser`.  Is there any other way to make such a test that you can think of?

**Comment by nicolo-ribaudo** [comment]
Oh well, I think it's ok to put it in `babel-types`'s tests

**Comment by jedwards1211** [comment]
Are `declare`, `readonly`, and `definite` all valid `ClassPrivateProperty` fields as well?  (#13563) If so than I can fix both these issues by spreading fields into `ClassProperty` and `ClassPrivateProperty`.

Though I'm still confused why it was necessary to make a separate `ClassPrivateProperty` node type instead of just allowing `ClassProperty.key` to be a `PrivateName`...

**Comment by jedwards1211** [comment]
Here's a list of missing properties I identified with a script.  Some of them are probably spurious, like `ImportDeclaration.attributes`.  Which ones are valid?

I manually eliminated many things from this list that the script found.  Some of the `@babel/parser` fixtures seem outdated; I see `id: null` and `predicate: null` properties on `ClassMethod`s in some fixtures, `method: false` on some `ObjectProperty`s, among many other examples.  If I'm going to make a test that scans the fixtures, I'll have to update the outdated ones.

```js
{
  ClassProperty: {
    variance: {
      example: 'babel-parser/test/fixtures/es2022/class-properties/new-target-with-flow/output.json',
      count: 25,
      fileCount: 14
    }
  },
  ImportDeclaration: {
    attributes: {
      example: 'babel-parser/test/fixtures/experimental/module-attributes/invalid-syntax-with-attributes-multiple-lines/output.json',
      count: 4,
      fileCount: 4
    }
  },
  ClassPrivateProperty: {
    variance: {
      example: 'babel-parser/test/fixtures/flow/class-private-property/1/output.json',
      count: 5,
      fileCount: 3
    },
    declare: {
      example: 'babel-parser/test/fixtures/flow/class-private-property/declare-field/output.json',
      count: 1,
      fileCount: 1
    },
    readonly: {
      example: 'babel-parser/test/fixtures/typescript/class/private-fields-modifier-readonly/output.json',
      count: 2,
      fileCount: 1
    },
    optional: {
      example: 'babel-parser/test/fixtures/typescript/class/private-fields/output.json',
      count: 2,
      fileCount: 1
    },
    definite: {
      example: 'babel-parser/test/fixtures/typescript/class/private-fields/output.json',
      count: 2,
      fileCount: 1
    }
  },
  DeclareOpaqueType: {
    impltype: {
      example: 'babel-parser/test/fixtures/flow/opaque-type-alias/opaque_declare_export_neither/output.json',
      count: 6,
      fileCount: 6
    }
  },
  RestElement: {
    optional: {
      example: 'babel-parser/test/fixtures/flow/optional-type/4/output.json',
      count: 3,
      fileCount: 3
    }
  },
  ExportDefaultDeclaration: {
    exportKind: {
      example: 'babel-parser/test/fixtures/typescript/class/abstract-false-positive/output.json',
      count: 6,
      fileCount: 4
    }
  },
  TSParameterProperty: {
    override: {
      example: 'babel-parser/test/fixtures/typescript/class/constructor-with-override-modifer-names/output.json',
      count: 1,
      fileCount: 1
    },
    decorators: {
      example: 'babel-parser/test/fixtures/typescript/class/parameter-properties-with-decorators/output.json',
      count: 1,
      fileCount: 1
    }
  },
  ArrayPattern: {
    optional: {
      example: 'babel-parser/test/fixtures/typescript/declare/pattern-parameters/output.json',
      count: 11,
      fileCount: 5
    }
  },
  TSImportEqualsDeclaration: {
    importKind: {
      example: 'babel-parser/test/fixtures/typescript/import/equals-require/output.json',
      count: 13,
      fileCount: 10
    }
  },
  TSPropertySignature: {
    kind: {
      example: 'babel-parser/test/fixtures/typescript/interface/get-set-properties/output.json',
      count: 2,
      fileCount: 1
    }
  },
  StaticBlock: {
    static: {
      example: 'babel-parser/test/fixtures/typescript/static-blocks/static-blocks-and-proptery-named-static/output.json',
      count: 4,
      fileCount: 4
    }
  }
}
```

**Comment by nicolo-ribaudo** [comment]
- `StaticBlock.static` looks like a parser bug.
- `ImportDeclaration.attributes` has been replaced by `ImportDeclaration.assertions`, and it will be removed in Babel 8

All the other ones look like valid AST props when parsing Flow/TS.

**Comment by jedwards1211** [comment]
I see, so adding to the set of types a single-value field can be would be considered breaking, but adding to the set of types an array field like `ClassBody.body` can take isn't considered breaking?  Is there a consistent philosophy or is it decided on a case-by-case basis?
