### ISSUE TITLE
[Bug]: Derived constructors should not be allowed to return primitive values

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#13566]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
new class extends class {} {
  constructor() {
    super();
    return 3;
  }
}
```

[repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=HYUw7gBAxgNghgZwREAPALiYATZtHIDeAvhIQFATQD2wC6ATgK5TrUMAUAlGZVRAiYAHEJy4BuPlQYh0TBsAgBmSVWLl1QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.7&externalPlugins=)

### Configuration

Just `@babel/preset-env`

### Current and expected behavior

It currently returns an empty object, but it should throw a TypeError. This doesn't apply to base constructors.

Spec: step 12.c of https://tc39.es/ecma262/#sec-ecmascript-function-objects-construct-argumentslist-newtarget

### Environment

Babel 7.14.7

**Comment by JLHwung** [comment]
https://github.com/babel/babel/blob/47d79ac9755cde808fa4483014f3b0b450408687/packages/babel-helpers/src/helpers.js#L618-L620

We should throw a type error when `call` is not `undefined` and `typeof call` is neither `"object"` nor `"function"`. This can be a good first issue.

**Comment by nicolo-ribaudo** [comment]
If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-classes/test/fixtures/spec (only `exec.js` and `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest classes` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest classes` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests (and `OVERWRITE=true make test` if needed)
1. Run `git push` and open a PR!

**Comment by dhrubesh** [comment]
Hi @nicolo-ribaudo do you mind if I pick this? It'll be my first issue.

**Comment by fedeci** [comment]
It's yours!

**Comment by Yokubjon-J** [comment]
Hello! If this issue is still open, could you please assign me?

**Comment by nicolo-ribaudo** [comment]
Oh actually, this was fixed by https://github.com/babel/babel/commit/23d4f8c5633ef4b347be38ae91dcd6ba78fd1d58. Sorry 😅
