### ISSUE TITLE
[Bug]: transform-es2015-modules-amd

### ISSUE THREAD

**Issue by jonathan-s** [babel/babel#13565]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

Version of lit-html@2.0.0-rc.3

```
babel lit-html -d lit-html6 --plugins transform-es2015-modules-amd
```

### Configuration file name

.babelrc

### Current and expected behavior

Current behaviour. 
```
SyntaxError: lit-html/development/directives/async-append.js: Unexpected token, expected ( (37:12)
  35 |         let i = 0;
  36 |         const { _value: value } = this;
> 37 |         for await (let v of value) {
     |             ^
```

Expected behaviour
Not getting a syntax error since it's valid javascript. 

### Environment

- Babel: 6.26.0 (babel-core 6.26.3)
- Node: v14.15.1
- Npm: 6.14.8
- OSX: 10.14.6

**Comment by nicolo-ribaudo** [comment]
Could you try using Babel 7 instead? (`@babel/cli`, `@babel/core`, `@babel/plugin-transform-modules-amd`)

**Comment by nicolo-ribaudo** [comment]
Closing since this is a Babel 6 bug, and Babel 6 is not maintained anymore.
