### ISSUE TITLE
[Bug]: "The Function constructor is eval" warning from Mozilla Addons Linter

### ISSUE THREAD

**Issue by tdriley** [babel/babel#13574]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

From the `regenerator-runtime` repo: https://github.com/facebook/regenerator/blob/master/packages/runtime/runtime.js#L748

```
try {
  regeneratorRuntime = runtime;
} catch (accidentalStrictMode) {
  // This module should not be running in strict mode, so the above
  // assignment should always work unless something is misconfigured. Just
  // in case runtime.js accidentally runs in strict mode, we can escape
  // strict mode using a global Function call. This could conceivably fail
  // if a Content Security Policy forbids using Function, but in that case
  // the proper solution is to fix the accidental strict mode problem. If
  // you've misconfigured your bundler to force strict mode and applied a
  // CSP to forbid Function, and you're not willing to fix either of those
  // problems, please detail your unique predicament in a GitHub issue.
  Function("r", "regeneratorRuntime = r")(runtime);
}
```

### Configuration

```js
    loader: "babel-loader",
    options: {
        presets: [
            '@babel/preset-env',
            '@babel/preset-react'
        ]
     }
```

### Current and expected behavior

Our Browser Extension seems to be stuck in review with Mozilla, and their submission service is feeding back (what appear to be ESLint warnings), saying "DANGEROUS_EVAL The Function constructor is eval."

I can recreate the warnings by running the Mozilla addons-linter on our extension's dist files and have traced them back to the babel dependency "regenerator-runtime".

Looking around, regenerator-runtime seems to be causing problems in many other projects because of its use of the Function constructor - code which was introduced after regenerator-runtime v0.13.1.

We'd like to avoid switching away from babel for transpiling, but are having trouble finding any fix or workaround for this issue which has been around for a few years now.

### Environment

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    npm: 7.5.2 - ~/.nvm/versions/node/v12.2.0/bin/npm
  npmPackages:
    @babel/core: ^7.5.5 => 7.5.5 
    @babel/preset-env: ^7.5.5 => 7.5.5 
    @babel/preset-react: ^7.0.0 => 7.0.0 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-loader: ^8.0.6 => 8.0.6 
    babel-plugin-emotion: ^10.0.19 => 10.0.19 
    jest: ^24.9.0 => 24.9.0 
    webpack: ^4.39.2 => 4.39.2

**Comment by JLHwung** [comment]
For more info, see https://github.com/facebook/regenerator/issues/450#issuecomment-881960051

**Comment by JLHwung** [comment]
```
loader: "babel-loader",
    options: {
        presets: [
            ['@babel/preset-env', { targets: "defaults, not ie 11" }],
            '@babel/preset-react'
        ]
     }
```

Please provide targets to `preset-env`, see https://babeljs.io/docs/en/babel-preset-env#targets

`regenerator-runtime` are for legacy browsers which does not support generator. If you are compiling to modern browsers, tell `preset-env` so it will not transpile generator and the `regenerator-runtime` won't be included at all.

**Comment by tdriley** [comment]
> `regenerator-runtime` is for legacy browsers which do not support generator. If you are compiling to modern browsers, tell `preset-env` so it will not transpile generator and the `regenerator-runtime` won't be included at all.

Thanks for the suggestion @JLHwung, I was definitely targeting browsers further back than I needed to. However, it appears that no matter how recent I make the browser support, `regenerator-runtime`'s signature `Function("return this")` is still written into the dist files and picked up by the linter.

I even specifically excluded regenerator as per the babel docs: https://babeljs.io/docs/en/babel-preset-env#exclude

```
loader: "babel-loader",
options: {
	presets: [
		["@babel/preset-env", {
			targets: {
				browsers: ["last 1 Chrome version"]
			},
			exclude: [
				"@babel/plugin-transform-regenerator",
				'transform-regenerator'
			]
		}],
		"@babel/preset-react"
	]
}
```
...and tried using every possible combination of the `useBuiltIns` and `corejs` param values detailed in the docs. Somehow it still gets into the build!

**Comment by JLHwung** [comment]
@tdriley Can you share a reproducing repo? Is `regenerator-runtime` depended by a library in `node_modules`? In that case this issue can only be fixed at `regenerator-runtime`.

**Comment by nicolo-ribaudo** [comment]
@tdriley `Function("return this")` is not from `regenerator-runtime`. Regenerator only uses `Function("r", "regeneratorRuntime = r")`.

**Comment by tdriley** [comment]
> @tdriley `Function("return this")` is not from `regenerator-runtime`. Regenerator only uses `Function("r", "regeneratorRuntime = r")`.

@nicolo-ribaudo I believe both are used in different versions. `Function("return this")` is in older versions such as v0.11.1 and `Function("r", "regeneratorRuntime = r")` is in newer ones such as v0.13.8. Both cause the linter warning I am trying to get around.

**Comment by nicolo-ribaudo** [comment]
@tdriley I opened a PR to Regenerator so that `Function("r", "regeneratorRuntime = r")` is not _executed_ in modern browsers.

However, if Firefox disallows it at lint time and not at runtime it will still warn. You can use the `unsafe-eval` CSP flag to allow `Function(...)` in your extension: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by tdriley** [comment]
> However, if Firefox disallows it at lint time and not at runtime it will still warn. You can use the `unsafe-eval` CSP flag to allow `Function(...)` in your extension: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

@nicolo-ribaudo Thank you, but adding this to the manifest does not prevent the linter warning and also adds a new `MANIFEST_CSP_UNSAFE_EVAL` one. This is the same linter Mozilla use to evaluate extensions when they are submitted for release, and we believe it is blocking the approval process. I'd like to completely remove the problem code if possible, as modern browsers don't need it.

**Comment by nicolo-ribaudo** [comment]
Do you know for sure that it is not being approved because of `Function()`? According to https://github.com/mozilla/addons-linter/blob/6886efcc8ef8a25b01dc699e63e1e0e96e2711fd/docs/rules.md#web-extensions--manifestjson (`DANGEROUS_EVAL`), it's just a warning an not an error.

Anyway, https://github.com/babel/babel/issues/13574#issuecomment-882903660 shows how to stop Babel from injecting `regenerator-runtime`. If you still see `Function("return this")`, it's because one of your dependencies depends on it and there is nothing we can do about it. Also, `Function("return this")` and `Function("r", "regeneratorRuntime = r")` is perfectly safe code so you should ask to Mozilla to allow it in their linter.

As an alternative, you can replace `Function("return this")` with `globalThis` in your final bundle using a regexp.

**Comment by tdriley** [comment]
>Do you know for sure that it is not being approved because of Function()?

We cannot be sure. The extension approval process is taking much longer than usual and they have not been able to communicate why.

@nicolo-ribaudo @JLHwung Thanks for your help. I've been able to remove all of the "Function constructor is eval" warnings by:

- Removing package `lodash.clonedeep`
- Removing package `react-html-parser`
- Updating package `webext-redux` to 2.1.7
- Updating package `react-redux` to 7.2.4

The warnings were not caused by the babel configuration at all, but by other dependencies of our application.
