### ISSUE TITLE
[Bug]:  Running `npm install` with @babel/core7.14.8 fails

### ISSUE THREAD

**Issue by techdiary** [babel/babel#13582]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Seeing following error: 
```
No matching version found for @babel/generator@^7.14.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/core
```

### Current and expected behavior

npm install should work as expected

### Environment

 - Babel version 7.14.8
 - Node version 14

**Comment by alielkhateeb** [comment]
I am facing this exact error trying to `npm i` with `@babel/core@7.14.2`

**Comment by nicolo-ribaudo** [comment]
`@babel/generator` 7.14.8 is on npm: https://www.npmjs.com/package/@babel/generator/v/7.14.8. Please see https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67

**Comment by techdiary** [comment]
@nicolo-ribaudo  thank you for taking time and looking into it.
when I run `npm view @babel/generator` latest tag displayed is 7.14.5
```
npm view @babel/generator

@babel/generator@7.14.5 | MIT | deps: 3 | versions: 94
Turns an AST into code.
https://babel.dev/docs/en/next/babel-generator

dist
.tarball: https://nexus.corp.bluejeans.com/nexus/repository/npm-all/@babel/generator/-/generator-7.14.5.tgz
.shasum: 848d7b9f031caca9d0cd0af01b063f226f52d785
.integrity: sha512-y3rlP+/G25OIX3mYKKIOlQRcqj7YgrvHxOLbVmyLJ9bPmi5ttvUmpydVjcFjZphOktWuA7ovbx91ECloWTfjIA==
.unpackedSize: 115.1 kB

dependencies:
@babel/types: ^7.14.5 jsesc: ^2.5.1         source-map: ^0.5.0

maintainers:
- hzoo <hi@henryzoo.com>
- loganfsmyth <loganfsmyth@gmail.com>
- danez <npm@tschinder.de>
- existentialism <bng412@gmail.com>
- nicolo-ribaudo <nicolo.ribaudo@gmail.com>
- jlhwung <i@jhuang.me>

dist-tags:
latest: 7.14.5

published a month ago by nicolo-ribaudo <nicolo.ribaudo@gmail.com>
```

**Comment by nicolo-ribaudo** [comment]
I get `7.14.8` when using both `npm view` and `npm show`. I also see it with `npm view @babel/generator versions`. Probably npm is using different proxy servers for us, I suggest asking directly to them.

**Comment by alielkhateeb** [comment]
@nicolo-ribaudo You're right, it's the proxy, I cleaned the cache and it works now. Sorry I didn't see this gist before commenting here 😄
