### ISSUE TITLE
[Bug]: `@babel/runtime/helpers/extends` could trigger too much recursive call

### ISSUE THREAD

**Issue by mycoin** [babel/babel#13597]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
require('@babel/runtime/helpers/extends')({},{})
```

webpack.config.js
```
const UglifyWebpackPlugin = require('uglifyjs-webpack-plugin')

module.exports = {
    mode: 'production',
    entry: './index.js',
    optimization: {
        minimizer: [
            new UglifyWebpackPlugin(),
        ],
    }
}
```

### Configuration file name

package.json

### Configuration

```json
{
  "dependencies": {
    "@babel/core": "^7.14.8",
    "@babel/preset-env": "^7.14.8",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^5.46.0",
    "webpack-cli": "^4.7.2"
  },
  "scripts": {
    "build": "webpack"
  }
}
````

### Current and expected behavior

source code for '@babel/runtime/helpers/extends': 
```javascript
function _extends() {
  module.exports = _extends = Object.assign || function (target) {
    for (var i = 1; i < arguments.length; i++) {
      var source = arguments[i];

      for (var key in source) {
        if (Object.prototype.hasOwnProperty.call(source, key)) {
          target[key] = source[key];
        }
      }
    }

    return target;
  };

  module.exports["default"] = module.exports, module.exports.__esModule = true;
  return _extends.apply(this, arguments); // ??
}

module.exports = _extends;
module.exports["default"] = module.exports, module.exports.__esModule = true;

```

some times cause `RangeError: Maximum call stack size exceeded`

### Environment

  System:
    OS: macOS 11.4
  Binaries:
    Node: 12.22.3 - ~/.nvm/versions/node/v12.22.3/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v12.22.3/bin/npm
  npmPackages:
    @babel/core: ^7.13.14 => 7.14.8 
    @babel/preset-env: ^7.13.12 => 7.14.8 
    babel-core: ^6.26.3 => 6.26.3 
    babel-loader: ^8.2.2 => 8.2.2 
    babel-preset-es2015: ^6.24.1 => 6.24.1 
    webpack: ^4.46.0 => 4.46.0 

### Possible solution

update to:
```javascript
module.exports = Object.assign || function (target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];

    for (var key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) {
        target[key] = source[key];
      }
    }
  }

  return target;
};

module.exports["default"] = module.exports;
module.exports.__esModule = true;

```

### Additional context

https://github.com/mishoo/UglifyJS/issues/5098

_No response_

**Comment by nicolo-ribaudo** [comment]
In that file there are two extends function: the outer one is called exactly once and the it's replaced with the inner one, which doesn't recurse.

This is just a bug with your minifier.

**Comment by mycoin** [comment]
> In that file there are two extends function: the outer one is called exactly once and the it's replaced with the inner one, which doesn't recurse.
> 
> This is just a bug with your minifier.

nice reply,  related issues have been fixed.  https://github.com/mishoo/UglifyJS/pull/5099

closed! wish you a nice day .  😇
