### ISSUE TITLE
[Bug]: babel/traverse cannot handle typescript function overloading in a default export

### ISSUE THREAD

**Issue by thisissami** [babel/babel#13594]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

The following code is valid TypeScript but crashes babel.

```typescript
export default function(choiceField: PDFDict, selectedIndex: number): void;
export default function(choiceField: PDFDict, selectedValue: string): void;
export default function(choiceField: PDFDict, selection: number | string) {
  // ...
}
```

### Configuration file name

babel.config.js

### Configuration

```
{
  presets: ['@babel/preset-typescript']
}
```

### Current and expected behavior

The expected behaviour is that it would transform properly. Instead, it crashes babel with the error stack that follows. 

> { TypeError: /home/thisissami/code/s2sBackend/s2sWebApi/src/libraries_v2/PDF/fillPDF/interactiveFields/choiceFields/fillChoiceField.ts: Cannot read property 'name' of null
>     at PluginPass.enter (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/plugin-transform-typescript/lib/index.js:263:59)
>     at newFn (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:171:21)
>     at NodePath._call (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
>     at NodePath.call (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
>     at NodePath.visit (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
>     at TraversalContext.visitQueue (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:99:16)
>     at TraversalContext.visitSingle (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:73:19)
>     at TraversalContext.visit (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:127:19)
>     at Function.traverse.node (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:76:17)
>     at traverse (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:56:12) code: 'BABEL_TRANSFORM_ERROR' }

### Environment

- Babel Version: 7.14.8
- Node: 10.24.0
- OS: both windows 10 and Ubuntu 18.04

### Possible solution

This is not a fix, but it is a workaround. Avoiding overloading the `default` directly, but instead overloading the function elsewhere and then exporting that overloaded function as default works, as follows:

```ts
function fillChoiceField(choiceField: PDFDict, selectedIndex: number): void;
function fillChoiceField(choiceField: PDFDict, selectedValue: string): void;
function fillChoiceField(choiceField: PDFDict, selection: number | string) {
  // ...
}

export default fillChoiceField;
```

**Comment by tony-go** [comment]
Could take a look 👋🏼 ! Let me know.

**Comment by nicolo-ribaudo** [comment]
It's yours!

**Comment by thisissami** [comment]
@tony-go for what it's worth, this was not an issue on older versions of `TypeScript` and `Babel`. Previously, we were using `@babel/core v7.4.4`, `@babel/preset-typescript v7.3.3`, and `typescript v3.9.6`. We upgraded all 3 libraries to the `@latest` versions last week, and babel would no longer let things compile. After quite a bit of digging, I was able to isolate this bug that I've shared here. I hope this additional context is helpful!

**Comment by fedeci** [comment]
It may be helpful to bisect then.

**Comment by JLHwung** [comment]
The error is thrown from 

https://github.com/babel/babel/blob/e0dc925bbe148022df6b43dd6965ebca661915fc/packages/babel-plugin-transform-typescript/src/index.ts#L291-L300

We should check if `TSDeclareFunction` has an `id` before registering global types.
