### ISSUE TITLE
[Bug]:  destructuring loses this point

### ISSUE THREAD

**Issue by ProfBramble** [babel/babel#13592]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

    traverse(AST, {
      CallExpression: (path: NodePath<CallExpression>) => {
        const { get } = path; // lost this / reference
        if (get('callee').toString() === 'require') {
            // do something
        }
     }}

 
    

### Current and expected behavior

destructuring assignment will lose the context, this should be strongly bound

### Environment

  System:
    OS: macOS 11.4
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.2 - /usr/local/bin/npm

### Possible solution

add an explicit this binding to the method

**Comment by nicolo-ribaudo** [comment]
This is a design decision: all the methods in our code base are _not_ bound, so that we can share them across all the `NodePath` instances and save a lot of memory.

Btw, in general most methods in JS are not bound. For example, this will not work:
```js
let { forEach } = [1, 2, 3];
forEach(console.log);
```

**Comment by ProfBramble** [comment]
Thanks for sharing
