### ISSUE TITLE
[Bug]: Legacy decorator does not support computed property

### ISSUE THREAD

**Issue by alex-kinokon** [babel/babel#13591]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const { parseSync } = require("@babel/core");

parseSync(`
class A {
  @dec
  [Symbol.iterator]() {}
}
`, {
  parserOpts: {
    plugins: ["decorators-legacy", "typescript"],
  },
})
```

### Configuration

See above.

### Current and expected behavior

**Expected**: TypeScript parses this and compiles it into:

```js
var _a;
class A {
    [_a = Symbol.iterator]() { }
}
__decorate([
    dec,
    __metadata("design:type", Function),
    __metadata("design:paramtypes", []),
    __metadata("design:returntype", void 0)
], A.prototype, _a, null);
```

**Actual**:

```
SyntaxError: unknown: Unexpected token (4:22)

  2 | class A {
  3 |   @dec
> 4 |   [Symbol.iterator]() {}
    |                       ^
  5 | }
  6 |
```

### Environment

- Babel version: 7.14.8

**Comment by nicolo-ribaudo** [comment]
The "legacy" decorators proposal considered `[...]` to be part of the decorator itself. In other words,
```ts
class A {
  @deco [x]
  y
}
```
is a decorator (`deco[x]`) that decorates the `y` field, and not a decorator (`deco`) that decorates the `[x]` field followed by an unrelated `y` field.

TypeScript didn't correctly implement the proposal, but they built their own decorators version.

We are currently in contact with the authors of the new decorators proposal and we'll probably start implementing them in the summer. Hopefully this proposal will be the last one and it will align the Babel and TS implementations.

**Comment by liuxingbaoyu** [comment]
As TS and Babel now support the latest decorative proposals, I will close this issue.
