### ISSUE TITLE
Tail call in class method not optimzied

### ISSUE THREAD

**Issue by roblabla** [babel/babel#1360]
As can be seen [here](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20X%20{%0A%20%20test%28x%29%20{%0A%20%20%20%20if%20%28x%20%3C%3D%200%29%0A%20%20%20%20%20%20return%201%3B%0A%20%20%20%20else%0A%20%20%20%20%20%20return%20this.test%28x%20-%201%29%3B%0A%20%20}%0A}%0A%0Afunction%20test%28x%29%20{%0A%20%20if%20%28x%20%3C%3D%200%29%0A%20%20%20%20return%201%3B%0A%20%20else%0A%20%20%20%20return%20test%28x%20-%201%29%3B%0A}), it looks like BabelJS doesn't optimize terminally recursive class methods. Is this a bug in the current impl, or just not currently supported ? Or am I doing it wrong ?

**Comment by sebmck** [comment]
Not supported. There's no way to be sure that `this.test` is going to refer to the same function.
