### ISSUE TITLE
[Bug]: Babel typescript do not bind private field to object

### ISSUE THREAD

**Issue by polRk** [babel/babel#13602]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
class A {
  private cache = {};

  private getFromCache(key: string){
    return this.cache[key];
  }
}


const {getFromCache}  = new A(); // doesn't work, can not get property cache of undefined.

const a = new A();
a.getFromCache(''); // works well

```

### Configuration

  ```js
module.exports = createTransformer({
    plugins: [
        'const-enum',
        '@babel/plugin-proposal-class-properties',
        '@babel/transform-typescript',
    ],
    presets: [
        '@babel/preset-env',
        '@babel/preset-react',
        '@babel/preset-typescript',
    ],
});

```

### Current and expected behavior

should bind private methods to configured object.

### Environment

- jest: 26.6.3
- @babel/core: 7.12.9
- node: v10.14.0 

### Additional context

Need in jest tests

**Comment by nicolo-ribaudo** [comment]
This is the expected behavior and it [matches what TypeScript does](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1oAcBOBLAbmALgKbTBjAAWxAvIgL4DcSK62eR0A5ofgGIYD2AWwDCZSgAoA1oQCeALmgR82AHYcAlMlSoM3AK4YV0fOSwQAdKQqEA2tJkBdRqlpJaQA): that code is equivalent to the JS code
```js
class A {
    cache = {};
    getFromCache(key) {
        return this.cache[key];
    }
}
```

and class methods aren't bound. You have to manually bind it:
```js
class A {
    private cache = {};

    constructor() {
      this.getFromCache = this.getFromCache.bind(this);
    }

    private getFromCache(key: string) {
        return this.cache[key];
    }
}
```
