### ISSUE TITLE
[Bug]: After babel/parser generates ast, immediately use babel/generator to output, the results are inconsistent

### ISSUE THREAD

**Issue by Linkontoask** [babel/babel#13617]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
const { parse } = require('@babel/parser')
const generator = require('@babel/generator')

const source = `const babel = {
  version() {},
  author: ''
};`

const ast = parse(source)

console.log(generator.default(ast).code === source) // false

console.log(generator.default(ast).code)
/*
const babel = {
  version() {},

  author: ''
};
*/
```

### Current and expected behavior

The input source code is consistent with the production source code

### Environment

- @babel/generator: 7.14.5
- @babel/parser: 7.14.7

**Comment by fedeci** [comment]
The input and output code is the same, probably it is indented differently so the equality check is falsy.

**Comment by Linkontoask** [comment]
@fedeci There will be one more blank line in the output of the above code.

I didn't do any conversion. Why is there a blank line when generating the code?
If I change the code to this
```
const source = `const babel = {
   version: () => {},
   author:''
};`
```
Then you will get the correct output

**Comment by fedeci** [comment]
I'll investigate.

**Comment by nicolo-ribaudo** [comment]
The reason is that `@babel/generator` doesn't make any guarantee about formatting. It prints the same code, but it might be formatted differently.

If you need to keep the original format, I suggest using https://github.com/benjamn/recast.

**Comment by fedeci** [comment]
However is there any particular reason for which we print a new line after a `BlockStatement`?

**Comment by JLHwung** [comment]
Babel parser is not an CST parser, the whitespaces are not preserved in the AST, so when Babel generator prints code from the AST, it is almost for sure the output is not exactly the input.

See also https://github.com/babel/babel/issues/10674#issuecomment-550960410.

I think we can mention it in the docs.

**Comment by Linkontoask** [comment]
Thank you for your reply.
If the output format is not guaranteed, I feel that I can write a little tip here https://babeljs.io/docs/en/babel-generator to tell users

**Comment by nicolo-ribaudo** [comment]
That would be appreciated :pray:

Docs are in the https://github.com/babel/website repository.
