### ISSUE TITLE
[Bug]:  Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method."

### ISSUE THREAD

**Issue by nosillytrying** [babel/babel#13620]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

...{name: 123}] is not allow
 [...new Set([1,1,2,2]) is allow

### Current and expected behavior

presets： [
      "@babel/env",
      {
        "targets": {
          "edge": "17",
          "firefox": "60",
          "chrome": "67",
          "safari": "11.1"
        },
        "useBuiltIns": "usage",
        "corejs": "3.6.5"
      }
    ],
   "plugins": [
        [
            "@babel/plugin-transform-runtime",{
                "corejs": 3
            }
        ]
    ]

### Environment

@babel/core@^7.11.0
@babel/preset-env@7.14.8

**Comment by nicolo-ribaudo** [comment]
This is the expected behaviour: you cannot spread normal objects in arrays.

Probably there is another way to get what you want: what do you expect `[...{name: 123}]` to be?
