### ISSUE TITLE
Add React Native e2e tests

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#13639]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

We recently had a React-related regression that made React Native unusable. We can add it as an e2e test, since we don't have any e2e test for jsx.

### Describe the solution you'd like

https://twitter.com/motiz88/status/1423189085632487427

### Describe alternatives you've considered

/

**Comment by kelset** [comment]
Feel free to count me in to help setting this up 👍

**Comment by kelset** [comment]
Ok, quick round up of what this CI will need:
* `npx react-native init RNBABEL` to initialize a fresh project (on the latest "stable" RN version). This should run even on a plain linux machine, but could be that it needs either cocoapods or android stuff installed. Need to be tested TBH
* `cd RNBABEL`
* `npx react-native bundle --entry-file index.js --bundle-output ios.bundle`. We actually don't really care about the bundle name itself (ios/android), this will just trigger [Metro](https://github.com/facebook/metro) to run correctly. If this commands succeeds, everything should be fine.
