### ISSUE TITLE
Hand plugin the correct instance of babel

### ISSUE THREAD

**Issue by Alxandr** [babel/babel#1363]
I've tried my luck at creating a plugin in babel here the other day, and run it by my `mimosa-babel` mimosa plugin. However, the issue that quickly presented itself was that the mimosa plugin and the babel plugin each loaded their own `babel`, which ends in failure (even though they are the exact same version).

So I suggest changing the plugin api from allowing this:

```javascript
import { Transformer, types as t } from 'babel-core';

export default new Transformer('aurelia-babel-plugin', {
  Function(node, parent) {
  	console.log(node);
  }
});
```

To instead enable this:

```javascript
export default function(babel) {
  const {Transformer, types: t} = babel;
  
  return new Transformer('aurelia-babel-plugin', {
    Function(node, parent) {
      console.log(node);
    }
  });
};
```

This way, babel can hand itself to the plugin to make sure there aren't version discrepancies. Also, since babel has a `babel.version` string, if the plugin requires a certain version, it can check that and throw if it's not within valid range.

**Comment by sebmck** [comment]
This is going to be terrible for performance since a new `Transformer` will be created on every file transform. I'm probably going to do something like:

```javascript
export var key = "aurelia-babel-plugin";

export function build(babel) {
  const {Transformer, types: t} = babel;

  return {
    Function(node, parent) {
      console.log(node);
    }
  };
};
```

So the result can be cached with `key`.

**Comment by Alxandr** [comment]
You can cache it with the function instead.

```
// inside babel somewhere
if(!transformerCache.has(buildFn))
  transformerCache.add(buildFn, buildFn(babel));
```

**Comment by sebmck** [comment]
Hadn't thought of that :stuck_out_tongue:

**Comment by phpnode** [comment]
@sebmck did https://github.com/babel/babel/commit/9cb16711dda17d1e53c975cd117d70b2c381e422 fix this?

**Comment by sebmck** [comment]
@phpnode Yep, I'll need to write up some tests for it all though before I release.

**Comment by sebmck** [comment]
This will be available in the next release.
