### ISSUE TITLE
[Bug]: Error when parsing ternary inside parens with arrow functions when using Flow

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#13644]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
(a ? v => (sum += 1) : v => 0);
```

[REPL](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=BQQwBA_GBuYLwD4zAM4FcC2YDUcwEYBKMALhniQAZCBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-1%2Cflow&prettier=false&targets=&version=7.15.1&externalPlugins=&assumptions=%7B%7D)

### Current and expected behavior

It should be parsed successfully, but it throws.

### Environment

`@babel/parser` 7.15.0

### Additional context

Originally reported at https://github.com/babel/babel/issues/11038#issuecomment-893729786

**Comment by nicolo-ribaudo** [comment]
Another test case: `(a ? (sum += 1) : v => 0);`

**Comment by nicolo-ribaudo** [comment]
Another test case:
```js
(a ? (sum += 1) : v => 0 : any)
```

It's a ternary type-casted to `any`.

**Comment by lightmare** [comment]
Is there any possibility Flow/TypeScript fix their broken grammar? This mess is unsustainable.

**Comment by nicolo-ribaudo** [comment]
TypeScript's grammar is worse since is also has `(x: T)` type casts, but I don't think they'll ever change it :shrug: 

I also found another bug while fixing this: `<T>(b => c)` should throw but it doesn't.

**Comment by julianklumpers** [comment]
What is exactly fixed? I'm still getting this issue with a fresh project and `d3-geo` installed.

![09a56525-3029-454e-982a-7779e7866380](https://user-images.githubusercontent.com/26057014/130293077-3a9e9797-33f3-4f0a-9ec1-7ec1ff4b8226.jpg)

**Comment by nicolo-ribaudo** [comment]
Can you share your lockfile?

**Comment by nicolo-ribaudo** [comment]
Could you try running `npx nls why @babel/parser`?
