### ISSUE TITLE
Include name of class that cannot be called as a function in error message

### ISSUE THREAD

**Issue by timoxley** [babel/babel#1365]
It would make for a clearer error message, especially in cases where sourcemaps are switched off, if the message also contained the name of the class that you're trying to call as a function.

The existing error messages look like this:
```
TypeError: Cannot call a class as a function
```

Perhaps they could look more like the following, if "Person" is the name of the class:

```
TypeError: Person: Cannot call a class as a function.
TypeError: Cannot call a class as a function: Person.
TypeError: Cannot call class Person as a function.
```

**Comment by sebmck** [comment]
Isn't it included in the stack trace?

**Comment by sebmck** [comment]
Yup, it is:

```
TypeError: Cannot call a class as a function
    at _classCallCheck (repl:3:106)
    at Foo (repl:6:3)
```

I don't think it's worth adding to the message. Thanks for the suggestion!
