### ISSUE TITLE
[Bug]: `scope.hasBinding` and `scope.getBinding` inconsistent for newly created vars

### ISSUE THREAD

**Issue by overlookmotel** [babel/babel#13665]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const babel = require('@babel/core');

const myPlugin = () => ({
  visitor: {
    Program: {
      exit(programPath) {
        // Sub-traversal to ensure runs after ESM->CJS transform
        programPath.traverse({
          ReferencedIdentifier(path) {
            if (!path.findParent(p => p.isFunction())) return;
            const varName = path.node.name;
            path.addComment(
              'leading',
              ` ${varName} ${
                path.scope.hasBinding(varName) ? 'hasBinding' : 'no hasBinding'
              }, ${
                path.scope.getBinding(varName) ? 'getBinding' : 'no getBinding'
              } `
            );
          }
        });
      }
    }
  }
});

const input = `
  import {x} from './foo.js';
  var y = true;
  function f() {
    return [x, y, console];
  }
`;

const output = babel.transformSync(input, {
  plugins: [
    '@babel/plugin-transform-modules-commonjs',
    myPlugin
  ]
}).code;

console.log(output);
```

### Configuration file name

n/a

### Configuration

n/a

### Current and expected behavior

In above example, [@babel/plugin-transform-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) transforms `import {x} from './foo.js';` to `var _foo = require("./foo.js");` and `x` to `_foo.x`.

My plugin runs after this transform and checks whether the vars used inside function `f` are bound to a variable definition in the file, and if so, to where.

All works as expected, except for the newly-created `_foo` variable. In that case, `path.scope.hasBinding()` returns `true` (correctly), but `path.scope.getBinding()` returns `undefined` (incorrectly).

The output from above example is:

```js
"use strict";
var _foo = require("./foo.js");
var y = true;
function f() {
  return [
    /* _foo hasBinding, no getBinding */ _foo.x,
    /* y hasBinding, getBinding */ y,
    /* console no hasBinding, no getBinding */ console
  ];
}
```

I would expect the comment before `_foo.x` to read: `_foo hasBinding, getBinding`.

### Environment

```
System:
  OS: macOS Mojave 10.14.6
Binaries:
  Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
  npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
npmPackages:
  @babel/core: ^7.15.0 => 7.15.0 
  @babel/generator: ^7.15.0 => 7.15.0 
  @babel/helper-plugin-utils: ^7.14.5 => 7.14.5 
  @babel/parser: ^7.15.0 => 7.15.0 
  @babel/plugin-transform-arrow-functions: ^7.14.5 => 7.14.5 
  @babel/plugin-transform-modules-commonjs: ^7.15.0 => 7.15.0 
  @babel/plugin-transform-react-jsx: ^7.14.9 => 7.14.9 
  @babel/plugin-transform-strict-mode: ^7.14.5 => 7.14.5 
  @babel/register: ^7.14.5 => 7.14.5 
  @babel/traverse: ^7.15.0 => 7.15.0 
  @babel/types: ^7.15.0 => 7.15.0 
  babel-jest: ^27.0.6 => 27.0.6 
  babel-plugin-dynamic-import-node: ^2.3.3 => 2.3.3 
  eslint: ^7.32.0 => 7.32.0 
  jest: ^27.0.6 => 27.0.6
```

### Possible solution

I am actually not entirely sure if this is intended behavior or not, but it certainly seems counter-intuitive.

**Comment by JLHwung** [comment]
For the newly created variables, there binding are not registered within the scope. 

https://github.com/babel/babel/blob/1d4bd31950ec6399c9620c08b61b44fe4d5c085c/packages/babel-plugin-transform-modules-commonjs/src/index.js#L236

It is a known issue of `Path#unshiftContainer`, in

https://github.com/babel/babel/blob/1d4bd31950ec6399c9620c08b61b44fe4d5c085c/packages/babel-core/src/transformation/file/file.ts#L218-L223

we have workarounds for that, guess we can apply similar patch for commonjs transforms.

`Scope#hasBinding` returns `true` merely because `_foo` is a generated uid.

https://github.com/babel/babel/blob/1d4bd31950ec6399c9620c08b61b44fe4d5c085c/packages/babel-traverse/src/scope/index.ts#L1158

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue?

**Comment by overlookmotel** [comment]
@The-x-Theorist I haven't had time to start on this, so yes, please feel free. That would be great.

**Comment by The-x-Theorist** [comment]
Can this issue be assigned to me?

**Comment by overlookmotel** [comment]
@The-x-Theorist I don't see anyone else clamouring to work on it, and it may take the maintainers some time to get to your request to assign you (I imagine they're pretty busy). So, if I were you, I'd just get to work on it. Probably you'll have already completed your PR before they get around to assigning you!

**Comment by The-x-Theorist** [comment]
@overlookmotel Okay, I will do the same I will open the PR.
