### ISSUE TITLE
False positive in React validation

### ISSUE THREAD

**Issue by mjohnston** [babel/babel#1366]
The React validator throws an error when you try to `require("React")`: https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/validation/react.js#L12

However, there is a legitimate use case for the uppercase version when interacting with React Native code. They use a custom module format that is file-system independent so `require("React")` is a valid relative path. https://github.com/facebook/react-native/tree/master/packager/react-packager/src/DependencyResolver/haste/DependencyGraph

Is there a way to tell Babel to skip this validation?

**Comment by fkling** [comment]
See https://github.com/babel/babel/commit/5fb793b75f047e08ec61383e9950b4996b88e287. Apparently you can blacklist `validation.react`.

**Comment by mjohnston** [comment]
Ah, missed that! Thanks @fkling
