### ISSUE TITLE
[Bug]: preset-env target.esmodules adds Promise polyfill

### ISSUE THREAD

**Issue by rifler** [babel/babel#13672]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
var a = new Promise(() => {})

(async () => {
  await a
})

var b = new URL('https://example.com')
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
    "presets": [
        [
            "@babel/preset-env",
            {
                "loose": true,
                "corejs": "3.16.0",
                "shippedProposals": true,
                "useBuiltIns": "usage",
                "targets": {
                    "esmodules": true
                }
            }
        ],
        "@babel/preset-typescript",
        "@babel/preset-react"
    ],
    "plugins": [
        "babel-plugin-const-enum",
        "@babel/plugin-transform-runtime",
        [
            "import",
            {
                "libraryName": "lodash-es",
                "libraryDirectory": "",
                "camel2DashComponentName": false
            }
        ]
    ]
}

```

### Current and expected behavior

current:
polyfills for Promise and URL are added, async/await transpiled to yield

expected:
polyfills for Promise and URL are not added, async/await not transpiled

because every browser supported esmodules also supported Promise, URL and async/await
https://caniuse.com/es6-module
https://caniuse.com/url
https://caniuse.com/async-functions

### Environment

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    npm: 7.20.6 - ~/.nvm/versions/node/v14.17.1/bin/npm
  npmPackages:
    @babel/cli: 7.14.8 => 7.14.8 
    @babel/core: 7.14.8 => 7.14.8 
    @babel/plugin-proposal-class-properties: 7.14.5 => 7.14.5 
    @babel/plugin-proposal-decorators: 7.14.5 => 7.14.5 
    @babel/plugin-proposal-do-expressions: 7.14.5 => 7.14.5 
    @babel/plugin-proposal-export-default-from: 7.14.5 => 7.14.5 
    @babel/plugin-proposal-function-bind: 7.14.5 => 7.14.5 
    @babel/plugin-proposal-function-sent: 7.14.5 => 7.14.5 
    @babel/plugin-proposal-pipeline-operator: 7.15.0 => 7.15.0 
    @babel/plugin-proposal-throw-expressions: 7.14.5 => 7.14.5 
    @babel/plugin-syntax-import-meta: 7.10.4 => 7.10.4 
    @babel/plugin-transform-runtime: 7.15.0 => 7.15.0 
    @babel/preset-env: 7.15.0 => 7.15.0 
    @babel/preset-react: 7.14.5 => 7.14.5 
    @babel/preset-typescript: 7.15.0 => 7.15.0 
    @babel/runtime: 7.15.3 => 7.15.3 
    babel-loader: 8.2.2 => 8.2.2 
    babel-plugin-const-enum: 1.1.0 => 1.1.0 
    babel-plugin-import: 1.13.3 => 1.13.3 
    webpack: 5.48.0 => 5.48.0

**Comment by nicolo-ribaudo** [comment]
caniuse is not always reliable for this type of data.
- For _transforms_, we use https://kangax.github.io/compat-table/es2016plus/ to generate https://github.com/babel/babel/blob/936fe405e05e09a976103ec67a1dcd6e3a25bcb2/packages/babel-compat-data/data/plugins.json#L155-L165. You can try enabling the [`bugfixes` option](https://babeljs.io/docs/en/babel-preset-env#bugfixes), which makes Babel compile a bit less stuff.
- For _core-js polyfills_, we use the data that core-js exposes at https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/src/data.mjs.

**Comment by rifler** [comment]
> For transforms, we use https://kangax.github.io/compat-table/es2016plus/ to generate

`bugfixes: true` returns `async/await` back, thanks
