### ISSUE TITLE
[Bug]: babel/babel-eslint (Archived) has incorrect "Website" in repository details

### ISSUE THREAD

**Issue by LukasPolak** [babel/babel#13688]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

N/A

### Configuration

N/A

### Current and expected behavior

In the repository details of [babel/babel-eslint (Archived)](https://github.com/babel/babel-eslint) repository, there is a wrong website pointing to a "master" branch instead of a "main", e.g.:
`https://github.com/babel/babel/tree/master/eslint/babel-eslint-parser`
instead of 
`https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser`

![image](https://user-images.githubusercontent.com/17145302/129867073-20188983-1f24-4754-b248-1dee999ab538.png)

`README.md` file has the correct link ([note](https://github.com/babel/babel-eslint#note-babel-eslint-is-now-babeleslint-parser-and-has-moved-into-the-babel-monorepo))

This issue can cause confusion because the `master` branch has [This project is still experimental and will be released with Babel v8. You can track our progress here! Please use babel-eslint in the meantime.](https://github.com/babel/babel/tree/master/eslint/babel-eslint-parser#this-project-is-still-experimental-and-will-be-released-with-babel-v8-you-can-track-our-progress-here-please-use-babel-eslint-in-the-meantime) note

### Environment

N/A

### Possible solution

replace
`https://github.com/babel/babel/tree/master/eslint/babel-eslint-parser`
with
`https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser`

**Comment by hzoo** [comment]
Thanks a lot for the for the report, done!
