### ISSUE TITLE
Tail call optimization doesn't work for function expressions

### ISSUE THREAD

**Issue by MadaraUchiha** [babel/babel#1368]
Compare 
```
function range(from, to, result = []){
  return (to - from < 0) ? result : range(from+1, to, result.concat(from));
}
```
with
```
let range = function(from, to, result = []) {
  return (to - from < 0) ? result : range(from+1, to, result.concat(from));
}
```

When you input both into the REPL on https://babeljs.io/repl/, the former gets TCO while the latter does not.

Fat arrow expressions are the same as functional expressions in this regard it seems.

**Comment by sebmck** [comment]
See #1367.

**Comment by benjamingr** [comment]
lol, 20 minutes apart, what are the odds. @MadaraUchiha you should do a PR

**Comment by MadaraUchiha** [comment]
@benjamingr The other issue mentions it's intentional.

**Comment by benjamingr** [comment]
Read on 😀
