### ISSUE TITLE
[Bug]: Parser accepts illegal syntax `obj.[prop]`

### ISSUE THREAD

**Issue by overlookmotel** [babel/babel#13694]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
val = obj.[prop];
```

[REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=G4QwNgBAvBD2BGArAdAbQA4CdboLoG4AoIA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=true&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

n/a

### Configuration

n/a

### Current and expected behavior

`obj.[prop]` is not legal Javascript (note the `.` before `[`). Would expect parser to throw an error.

Instead, it parses it as if it was `obj[prop]` (i.e. without the `.`).

### Environment

```
System:
  OS: macOS Mojave 10.14.6
Binaries:
  Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
  npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
npmPackages:
  @babel/core: ^7.15.0 => 7.15.0 
  @babel/generator: ^7.15.0 => 7.15.0 
  @babel/helper-module-transforms: ^7.15.0 => 7.15.0 
  @babel/helper-plugin-utils: ^7.14.5 => 7.14.5 
  @babel/parser: ^7.15.3 => 7.15.3 
  @babel/plugin-transform-arrow-functions: ^7.14.5 => 7.14.5 
  @babel/plugin-transform-modules-commonjs: ^7.15.0 => 7.15.0 
  @babel/plugin-transform-react-jsx: ^7.14.9 => 7.14.9 
  @babel/plugin-transform-strict-mode: ^7.14.5 => 7.14.5 
  @babel/register: ^7.15.3 => 7.15.3 
  @babel/traverse: ^7.15.0 => 7.15.0 
  @babel/types: ^7.15.0 => 7.15.0 
  babel-jest: ^27.0.6 => 27.0.6 
  babel-plugin-dynamic-import-node: ^2.3.3 => 2.3.3 
  eslint: ^7.32.0 => 7.32.0 
  jest: ^27.0.6 => 27.0.6
```

**Comment by JLHwung** [comment]
This issue is a regression introduced in https://github.com/babel/babel/pull/11871.

**Comment by overlookmotel** [comment]
Amazing! Thanks very much for very swift fix.
