### ISSUE TITLE
[Bug]: rest operator produces global variables

### ISSUE THREAD

**Issue by jakeye-nuvolo** [babel/babel#13703]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

`export const Event = (function init() {
function getsomething(){
    let o = {
     'siteIds':122,
     'sitename':'test',
     'sitecity': 'san fran'
     };
    return o;
}
    const { siteIds, ...rest } =
      getsomething();
  
  return {getsomething};
})();

`
reproducible here https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wKIDdjPgXjgAoAzAV2QRgEsU5rlqYiBKOAbwChzKa6BzYDFQQAtkIAWDfqy5x5cADZC4EOITkK4AclRNgASQAmqbQC4AjACYrAGk5ademLgCG489pfpt9x7v0EJgBPcydXZDgSKAjtBy0AXwBuePkoITIoSIgUhNTEFHQOOGdDE1s4ADpq9KKE9Xz5QWExSWlWFPl49JhMyPZmkXEYKWR-ZM4Elg6gA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D

In v7.15.3 -> the compiled output creates a global variable called _excluded.
in v7.13.17 -> the compiled output does not create a global variable, instead it places the array inline.

Is this expected?  is there a way to turn this off and revert to use v7.13.17 behavior?

Multiple scripts will collide with same global variable.

### Current and expected behavior

In v7.15.3 -> the compiled output creates a global variable called _excluded.
in v7.13.17 -> the compiled output does not create a global variable, instead it places the array inline.

Is this expected?  is there a way to turn this off and revert to use v7.13.17 behavior?

Multiple scripts will collide with same global variable.

### Environment

see https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wKIDdjPgXjgAoAzAV2QRgEsU5rlqYiBKOAbwChzKa6BzYDFQQAtkIAWDfqy5x5cADZC4EOITkK4AclRNgASQAmqbQC4AjACYrAGk5ademLgCG489pfpt9x7v0EJgBPcydXZDgSKAjtBy0AXwBuePkoITIoSIgUhNTEFHQOOGdDE1s4ADpq9KKE9Xz5QWExSWlWFPl49JhMyPZmkXEYKWR-ZM4Elg6gA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D

**Comment by asilberschneider** [comment]
I am having exactly the same issue in a very similar setup (multiple files transpiled and used on same page with RequireJS, but also multiple transpiled files which are concatenated afterwards).

**Comment by nicolo-ribaudo** [comment]
@asilberschneider Are you using Babel to compile modules to AMD, for RequrieJS?

**Comment by asilberschneider** [comment]
> @asilberschneider Are you using Babel to compile modules to AMD, for RequrieJS?

Our babel input files are in AMD format already, we use transpilation for new ECMAScript features or proposals and React elements.
"var excluded ..." values overwrite each other when files are loaded with Dojo toolkit AMD loader.
