### ISSUE TITLE
[Bug]: TypeError: template is not a function

### ISSUE THREAD

**Issue by backtolife2021** [babel/babel#13719]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```zsh
mkdir demo;
cd demo;
echo 'import template from "@babel/template";
import generate from "@babel/generator";
import * as t from "@babel/types";

const buildRequire = template(`
  var %%importName%% = require(%%source%%);
`);

const ast = buildRequire({
  importName: t.identifier("myModule"),
  source: t.stringLiteral("my-module"),
});

console.log(generate(ast).code);' > index.js;
echo '{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js","type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "author",
  "license": "ISC",
  "devDependencies": {
    "@babel/generator": "^7.15.0",
    "@babel/template": "^7.14.5",
    "@babel/types": "^7.15.0"
  }
}
' > package.json;
yarn;
node index.js;
```

### Current and expected behavior

TypeError: template is not a function

### Environment

  System:
    OS: Linux 5.13 Arch Linux
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  npmPackages:
    @babel/generator: ^7.15.0 => 7.15.0 
    @babel/template: ^7.14.5 => 7.14.5 
    @babel/types: ^7.15.0 => 7.15.0 

### Additional context

template.default is a function

**Comment by nicolo-ribaudo** [comment]
This is because of how Node.js's strategy to import CJS from ESM works.

When using native ESM, you'll need something like this:
```js
import _template from "@babel/template";
const template = _template.default;
```

This will work better when we'll switch to ESM (https://github.com/babel/babel/issues/11701, https://github.com/babel/babel/pull/13414), but it takes time.
