### ISSUE TITLE
[Bug]: duplicate plugin-syntax-dynamic-import in package.json of preset-env

### ISSUE THREAD

**Issue by fyzhu** [babel/babel#13718]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
no code
```

### Current and expected behavior

If I install newest preset-env with npm, I have to install plugin-syntax-dynamic-import  manually due to plugin-syntax-dynamic-import in both dependencies and devDependencies.

update 2021-09-07
Seem like duplicate dependency didn't cause my problem, but we still need to delete plugin-syntax-dynamic-import in devDependencies.

### Environment

System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  npmPackages:
    @babel/preset-env: ^7.15.0 => 7.15.0 
    @babel/runtime: 7.1.2 => 7.1.2 
    babel-eslint: 8.2.6 => 8.2.6 
    babel-helper-vue-jsx-merge-props: 2.0.3 => 2.0.3 
    babel-loader: ^8.0.5 => 8.2.2 

### Possible solution

delete plugin-syntax-dynamic-import in devDependencies

**Comment by merceyz** [comment]
> If I install newest preset-env with npm, I have to install plugin-syntax-dynamic-import manually due to plugin-syntax-dynamic-import in both dependencies and devDependencies.

Why do you have to do that? Package managers ignore `devDependencies` when they aren't from your own `package.json`

**Comment by fyzhu** [comment]
When I use the newest preset-env, I enconder a problem, I have to install plugin-syntax-dynamic-import manually, then I found package.json of preset-env had plugin-syntax-dynamic-import in both devDependencies and dependencies, I thought it's assosiated with my problem. Maybe it's not.
So I have two questions:
1. why preset-env has plugin-syntax-dynamic-import in both devDependencies and dependencies
2. why should I install plugin-syntax-dynamic-import manauly, but other packages in preset-env I don't have to.
PS
Both preset-env and `plugin-proposal-dynamic-import` depend on plugin-syntax-dynamic-import@^7.8.3, but I don't get a plugin-syntax-dynamic-import in first-level of node_modules, so I have to install plugin-syntax-dynamic-import by hand.

**Comment by fyzhu** [comment]
The second problem solved, I've already knew why it happened.
