### ISSUE TITLE
[Bug]: Legacy decorator not parsed anymore on class (regression from 7.14)

### ISSUE THREAD

**Issue by JSteunou** [babel/babel#13722]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Similar code & conf than this [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=FAAQ7glgLgFgkgRgBwDsAUBKYBTAHgBwHsAnKAAgGMAbAQwGc6yBhQlFbCqCVgCWyvzZiAIUK4yeKNhQATRgCVsNTgDoWAWyLsU5AN7AyZYtJlDMZfYcPGoAV2IoyKW1SoGyAX2AegA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.15.3&externalPlugins=babel-plugin-transform-dynamic-import%402.1.0&assumptions=%7B%22setPublicClassFields%22%3Atrue%7D)

except you have to set decorator to legacy (REPL does not save this parameter)

### Configuration file name

none, babel-loader options

### Configuration

See REPL above

## Current behavior

```
SyntaxError: /Foo.jsx: Unexpected token, expected "{" (43:7)

  41 | }) => isButton ? <button {...restProps} /> : <a {...restProps} />;
  42 |
> 43 | export @withRoute
     |        ^
  44 | class Foo extends React.Component {
  45 |   static propTypes = {

```

notice the export being before the decorator (in real code it is after)

## Expected behavior

no error 

### Environment

- Babel v7.15.3
- Node v14
- Webpack 5
- babel-loader 8

### Additional context

I really do not understand why it fails with my base code and not in REPL, it is very disturbing :(

**Comment by nicolo-ribaudo** [comment]
Are you 100% sure that the code that you are passing to Babel has the decorator _before_ `export`? In error messages Babel always prints the original code, so I don't understand how the error can be different from the code that you pass to Babel.

Can you try creating a repository with your existing setup, to show the bug?

**Comment by JSteunou** [comment]
100% sure, I'm cleaning my conf & code to try to recreate this issue. I have other loader & plugin to check to be sure

**Comment by JSteunou** [comment]
ok the issue is from linaria

We are using linaria v2 and the weird thing is that using `linaria/babel` in presets force us to have a `babel.config.js`, (we are in a webpack babel-loader context) and even with the same babel configuration, the linaria-loader (called after the babel-loader) trigger this error... I do not know what's going exactly but that really weird

**Comment by JSteunou** [comment]
thank you @nicolo-ribaudo I'll do this then

**Comment by JSteunou** [comment]
but yeah clearly both project are linked on this issue, rolling back either linaria or babel make it worked again.

With both version colliding, it crashes on decorator if I add a babel.config.js but on  TypeScript syntax if I remove the wide babel.config.js

As if linaria loader does not process babel loader input but run babel on its own

**Comment by JSteunou** [comment]
@nicolo-ribaudo I made a repo with minimal code so you can help analyze this issue https://github.com/JSteunou/babel-linaria-decorator-issue 

Babel configuration might seems over-engined but that is because you have a really large code base and I based this repo on it, keeping the same structure to be sure to keep everything that could help.

**Comment by nicolo-ribaudo** [comment]
When using linaria, Babel is called twice:
- First it's called by the linaria webpack loader, to do some linaria-specific transforms.
- Then, it's called by `babel-loader`

The problem is that [linaria parses your code with your Babel config, but then doesn't use it when transforming/printing the transformed code](https://github.com/callstack/linaria/blob/4662afb8703c9803ecc1bda713c4314684e6de4b/src/transform.ts#L179-L196). For this reason, decorators are printed with the default Babel config which prints them _after_ the `export`.

Then, you are (correctly) using the legacy decorators plugin, which expects decorators to be before `export`.

**Comment by JSteunou** [comment]
Ok so pure linaria issue, can I close this issue and share your analyse?

**Comment by nicolo-ribaudo** [comment]
Yes!

**Comment by JSteunou** [comment]
Thank you :pray:
