### ISSUE TITLE
Update chalk dependency

### ISSUE THREAD

**Issue by guybedford** [babel/babel#13728]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I've just been running Babel core in Deno using JSPM import maps (https://generator.jspm.io/#W8nDwMDE7JSYlJqjkJ+n4JKal6/I4JAE4usn5xelOpjrGZrqGcCECopSi1NLdEsqC1KLk4syC0qg8gD3eyFFRwA) and there's an issue with Chalk 2.x because it mutates `__proto__` which was banned by Deno in https://github.com/denoland/deno/issues/4324.

Updating to Chalk 4 fixes the issue.

### Describe the solution you'd like

Update to Chalk 4.

### Describe alternatives you've considered

None

**Comment by hzoo** [comment]
Sounds good, can at least make a similar change to js-tokens for babel-highlight https://github.com/babel/babel/blob/5fcf876c5761f12af47facdfc994b73e842cf1df/packages/babel-highlight/package.json#L19-L20

**Comment by JLHwung** [comment]
Yeah we can't bump because Babel 7 still supports Node.js 6. We can, however, fork `chalk` and then proxy Node.js 6 users to our `chalk@2` fork like we did for `chokidar`: https://github.com/nicolo-ribaudo/chokidar-2
