### ISSUE TITLE
in a constructor, can skip super() and can call super() after using this

### ISSUE THREAD

**Issue by mohayonao** [babel/babel#1372]
on 5.1.12

I found strange behaviors in a constructor.

```js
class A {}

class B extends A {
  constructor() {
    // skip `super()`
    if (0) super();
  }
}

class C extends B {
  constructor() {
    // call `super()` after using `this`
    0 && super();  // skip `super()`
    this.a = 100;
    super();
  }
}

class D extends C {
  constructor() {
    // call `super()` again
    super();
    super();
    super();
  }
}
```

I expect to raise a ReferenceError or a compile error.
But the below code is compiled and run without errors.

**Comment by sebmck** [comment]
Unsure if there's anything explicitly forbidding calling `super();` multiple times. As for the other ones, they're impossible to check for unless the entire script is statically evaluated which is expensive and complicated.

**Comment by mohayonao** [comment]
Are these not to dynamically check?

**Comment by sebmck** [comment]
It would require delegating it to runtime which would lead to complicated code.

**Comment by sebmck** [comment]
From what I can tell, duplicate `super()` is allowed. See #1131 for related discussion on runtime errors being relegated to compile time ones. Thanks!
