### ISSUE TITLE
[Bug]: Error when I specify "declare class" and "function" with the same name

### ISSUE THREAD

**Issue by Lodin** [babel/babel#13735]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=CYUwxgNghgTiAEkoGdnwILwN4F8BQeAZgK4B2YALgJYD2pG8AFAJTY5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.15.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.13.0&assumptions=%7B%7D)
```ts
declare class A {}

function A () {}
```

### Configuration file name

.babelrc

### Configuration

```json
{
  "presets": ["@babel/preset-typescript"]
}
```

### Current and expected behavior

I expect this construction to be compiled correctly because `tsc` [can](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwILwN4F8BQeAZgK4B2YALgJYD2pG8AFAJTY5A) do it. However, currently Babel throws an error:
```
Duplicate declaration "A"
  1 | declare class A {}
  2 |
> 3 | function A () {}
    | 
```

### Environment

- Babel version(s): 7.15.5
- Node: 16
- npm: 7
- OS: Windows 10
- Monorepo: no

**Comment by fedeci** [comment]
I can look into this

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue, If @fedeci is not currently working on this?

**Comment by fedeci** [comment]
It's yours!

**Comment by The-x-Theorist** [comment]
Thank you @fedeci, But where can I write tests for this issue?

**Comment by fedeci** [comment]
It is likely an issue with babel-traverse so that should be the right folder.

**Comment by The-x-Theorist** [comment]
`fixtures/regression` will this directory be good for writing test?

**Comment by JLHwung** [comment]
@The-x-Theorist I don't think it is a regression unless it worked before (not because when we are not tracking them at all). You can put the test around

https://github.com/babel/babel/blob/d30308fe8eb5dd11c16a2d4c3a058e63ffe7949e/packages/babel-traverse/test/scope.js#L656

**Comment by The-x-Theorist** [comment]
@JLHwung The test isn't throwing up the error.
<img width="768" alt="Screenshot 2021-11-26 at 12 19 10 PM" src="https://user-images.githubusercontent.com/75059911/143539114-6f3e9ff8-f465-4832-bb57-ff214c9b5db8.png">

When error is expected it throws `Recived function did not throw`.

<img width="566" alt="Screenshot 2021-11-26 at 12 18 06 PM" src="https://user-images.githubusercontent.com/75059911/143539191-c777679e-0232-4b8a-905b-da3005883e37.png">

Can you suggest a workaround with this?

**Comment by JLHwung** [comment]
@The-x-Theorist `t.declareClass` is for Flow, you can construct TypeScript AST from `t.classDeclaration`. See also https://astexplorer.net/#/gist/92c45fee6dec0904bbb9e045315de661/b701b341936beb303287908c723f42d02ca273cc for the AST shape.

**Comment by The-x-Theorist** [comment]
If `declare: boolean (default: null, excluded from builder function)` this is excluded than how can we add declare in AST?

**Comment by JLHwung** [comment]
Good question. You can build the AST and manually assign `declare` to it

```js
const decl = t.classDeclaration(...);
decl.declare = true;
```
