### ISSUE TITLE
Don't throw an error if babel polyfill is already included

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#1374]
I'm using AMD modules, some of which require the polyfill.
It's tedious to check each module I use to include the polifyll only once.
Can't babel just don't rewrite it without throwing an error?

**Comment by jquense** [comment]
The error is mostly there (I believe) to prevent exactly this bad pattern. Modules and libraries should __not__ use the polyfill. The polyfill is for applications and should be required once at the entry file of the app. Modules should use the [`runtime`](https://babeljs.io/docs/usage/runtime/) transformer OR they should publish that they expect certain polyfills to be present. Library code should never polute the global scope.

**Comment by monsanto** [comment]
I am unfamiliar with AMD, but does it not cache loaded modules? In this case your application is trying to load multiple versions of the polyfill (or your module system is bad at deduplicating modules). This is exactly the kind of thing the error is trying to protect you from.

**Comment by callumacrae** [comment]
If AMD is anything like CommonJS, the code is executed only once and the return value is cached.

@nicolo-ribaudo Are you using RequireJS or another module loader?

**Comment by jquense** [comment]
I am not sure about requirejs but webpack/browserify definitely cache them. I can't imagine that requirejs doesn't to that as well

**Comment by nicolo-ribaudo** [comment]
> The polyfill is for applications and should be required once at the entry file of the app. Modules should use the runtime transformer OR they should publish that they expect certain polyfills to be present.

Thanks for the explanation. Unfortunately, the app can't include the polyfill in this case: I solved the issue by including a polyfill which exports the objects I need without polluting the global scope.
