### ISSUE TITLE
[Bug]: [Babel standalone can't import css]

### ISSUE THREAD

**Issue by letanloc1998** [babel/babel#13748]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

components-button-index.js
```js
import "./style.css";
```

I can't import css when using Babel standalone and React by embedded into HTML

```html
    <script src='src/lib/react/17.0.2/react.production.min.js'></script>
    <script src='src/lib/react-dom/17.0.2/react-dom.production.min.js'></script>
    <script src='src/lib/react-router-dom/5.2.0/react-router-dom.min.js'></script>
    <script src='src/lib/babel/standalone/7.15.3/babel.min.js'></script>
    ...
    <script type="text/babel" data-presets="config-preset"
            src="src/components/Button/components-button-index.js"></script>
```

### Configuration

```html
    <script>
        Babel.registerPreset("config-preset", {
            presets: [
                [Babel.availablePresets["es2017"], { modules: true }],
                [Babel.availablePresets["react"]]
            ],
            plugins: [
                [Babel.availablePlugins["transform-modules-umd"]],
            ]
        });
    </script>
    ...
    <script type="text/babel" data-presets="config-preset"
        src="src/components/Button/components-button-index.js"></script>
```

### Current and expected behavior

I want to import css

### Environment

react version 17.0.2
react-dom version 17.0.2
react-router-dom version 5.2.0
babel standalone version 7.15.3

**Comment by nicolo-ribaudo** [comment]
Babel is only about JS. If you want to import CSS files, you need something like webpack or parcel.

**Comment by letanloc1998** [comment]
> Babel is only about JS. If you want to import CSS files, you need something like webpack or parcel.

Thank you
