### ISSUE TITLE
[Bug]: No error thrown for an ExportAllDeclaration with a non-identifier exported name

### ISSUE THREAD

**Issue by bradzacher** [babel/babel#13746]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
export * as 'oops' from 'module';
```

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgQwM5wOQQmVG4BmUEAtpiRACYCuANsBgNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=&prettier=true&targets=&version=7.15.6&externalPlugins=&assumptions=%7B%7D

### Configuration

(see repl above)

## Current:

No error

## Expected:

Error is thrown

### Environment

(see repl above)

### Possible solution

Babel should throw an error

**Comment by nicolo-ribaudo** [comment]
I believe this is valid? It's the same as
```js
import * as x from 'module';
export { x as 'oops' };
```

**Comment by nicolo-ribaudo** [comment]
Oh it looks it has reached consensus at tc39, but it hasn't been merged yet (because of editorial problems, not normative/semantics): https://github.com/tc39/ecma262/pull/2154

**Comment by bradzacher** [comment]
It looks like support was added for this in https://github.com/babel/babel/pull/12091
