### ISSUE TITLE
Can't compile `/\p{Letter}/u` in REPL

### ISSUE THREAD

**Issue by Ayc0** [babel/babel#13765]
When I try to compile this code:

```js
const a = /\p{Letter}/u
```

the REPL crashes with the error `/repl.js: Unknown property: Letter`:

![image](https://user-images.githubusercontent.com/22725671/133397833-dab896da-668a-4c96-8907-b695d6b588be.png)

I have no settings enabled, except `present-env` + `ie11` (to force the compiling of unicode regexes), and I'm on the latest version (but I tried with all the other available in the UI and they all break)

https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDA9AHQA4G8AyBTKKPAJwF8UBXIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.15.6&externalPlugins=&assumptions=%7B%7D

**Comment by nicolo-ribaudo** [comment]
Thanks! I'm moving this to the `babel/babel` repo because it's a `@babel/standalone` bug.
