### ISSUE TITLE
[Bug]: true `ignoreBrowserslistConfig` but reading `.browserslistrc`

### ISSUE THREAD

**Issue by loynoir** [babel/babel#13780]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```sh
$ strace -f -e file -o file.log babel --config-file ./babel.config.json example.mjs
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "debug": true,
        "ignoreBrowserslistConfig": true,
        "targets": {
          "chrome": "92"
        }
      }
    ]
  ]
}
```

### Actual
```sh
$ grep -F .browserslist file.log && echo FAIL || echo OK
... access("/path/to/cwd/browserslist", F_OK) = -1 ENOENT (No such file or directory)
... access("/path/to/cwd/.browserslistrc", F_OK) = -1 ENOENT (No such file or directory)
... access("/path/to/cwd/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
... access("/path/to/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
... access("/path/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
... access("/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
FAIL
```

### Expected
```sh
$ grep -F .browserslist file.log && echo FAIL || echo OK
OK
```

### Environment

```txt
@babel/preset-env: ^7.15.6 => 7.15.6
```

### Not a real world use case

Just try to analyze filesystem footprint, to solve another config problem by **another** build tool .

Found babel have this footprint, even set `ignoreBrowserslistConfig` to false.

**Comment by JLHwung** [comment]
I can not reproduce this issue. And I notice that the command you have given actually test whether Babel accesses `.babelrc`. Can you try
```
grep -F .browserslistrc file.log && echo FAIL || echo OK
```

**Comment by loynoir** [comment]
```sh
$ grep -qF .browserslistrc file.log && echo FAIL || echo OK
FAIL
```

```txt
access("/path/to/cwd/browserslist",
access("/path/to/cwd/.browserslistrc",
access("/path/to/cwd/browserslist-stats.json",
access("/path/to/browserslist-stats.json",
access("/path/browserslist-stats.json",
access("/path/browserslist-stats.json",
```

**Comment by JLHwung** [comment]
```
$ grep -F .babelrc file.log && echo FAIL || echo OK
... access(".../.babelrc", ...
FAIL
```

It seems that you have `.babelrc` somewhere. Did you try adding `babelrc: false` to your babel config?

**Comment by loynoir** [comment]
No, I don't have any babel config at default location.

```txt
access("/path/to/cwd/.babelrc", F_OK) = -1 ENOENT (No such file or directory)
```
```txt
access("/path/to/cwd/browserslist", F_OK) = -1 ENOENT (No such file or directory)
access("/path/to/cwd/.browserslistrc", F_OK) = -1 ENOENT (No such file or directory)
access("/path/to/cwd/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
access("/path/to/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
access("/path/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
access("/browserslist-stats.json", F_OK) = -1 ENOENT (No such file or directory)
```

Also, not a real world use case. 😂 
Just happend to find that.
And everything seems fine.

**Comment by loynoir** [comment]
```txt
Babel configs on "./example.mjs" (ascending priority):
config ./bbbb.babel.config.json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "debug": true,
        "ignoreBrowserslistConfig": true,
        "targets": {
          "chrome": "92"
        }
      }
    ]
  ]
}

programmatic options from @babel/cli
{
  "configFile": "./bbbb.babel.config.json",
  "sourceFileName": "example.mjs",
  "caller": {
    "name": "@babel/cli"
  },
  "filename": "example.mjs"
}
-----End Babel configs-----
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "92"
}

Using modules transform: auto

Using plugins:
  syntax-private-property-in-object
  syntax-class-properties
  syntax-numeric-separator
  syntax-nullish-coalescing-operator
  proposal-optional-chaining { chrome }
  syntax-json-strings
  syntax-optional-catch-binding
  syntax-async-generators
  syntax-object-rest-spread
  transform-modules-commonjs
  proposal-dynamic-import
  proposal-export-namespace-from { }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
"use strict";

```

**Comment by JLHwung** [comment]
That's certainly strange: It should not load `browserslistrc` when browser targets are given to preset-env:

https://github.com/babel/babel/blob/3d1481f36382d0f335eda33e4a45efa930dd3681/packages/babel-helper-compilation-targets/src/index.ts#L190-L198

The read of `browserslist-stats.json` seems to be issued by the `browerslists`. AFAIK preset-env is not aware of the browserslist stats.

> not a real world use case

That's ok, can you prepare a reproduction repo? It can help us determine whether it is a bug of `browserslist` or `preset-env`.

**Comment by loynoir** [comment]
https://github.com/loynoir/reproduce-babel-13780.js

**Comment by JLHwung** [comment]
The current behaviour is expected:
- `preset-env` does not load `.browserslistrc` as instructed by `ignoreBrowserslistConfig: true`. Actually since you have specified `targets`, you can safely remove `ignoreBrowserslistConfig`.
- `@babel/core` loads `.browserslistrc` because the [top level `targets`](https://babeljs.io/docs/en/options#targets) option is not provided. Note that `@babel/core` is unaware of `preset-env`, so it tries to load the browserslist config, in order to determine a global `targets` information that can be respected by all plugins/presets.

In your case, if you migrate `targets` in `preset-env` to top level, Babel will not load browserslistrc.

```json
{
  "targets": {
    "chrome": "92"
  },
  "presets": [
    [
      "@babel/preset-env",
      {
        "debug": true,
      }
    ]
  ]
}
```
