### ISSUE TITLE
[Bug]: runtime/helpers/esm/*.js import the CJS version of "typeof" 

### ISSUE THREAD

**Issue by pmcelhaney** [babel/babel#13786]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

This lines from `node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js`

```js
import _typeof from "@babel/runtime/helpers/typeof";
import assertThisInitialized from "./assertThisInitialized.js";

```

should be

```js
import _typeof from "./typeof.js";
import assertThisInitialized from "./assertThisInitialized.js";
```

In other words, the second line should match the first. It should import the ESM version of `typeof.js` rather than the CJS version which lives in the parent directory. Every file in that directory that imports `typeof.js` has the same problem, and for some reason it's specific to `typeof.js`. Other siblings are imported the same as they are in line 2 above.  

### Configuration

n/a

### Current and expected behavior

Current: 

```
Uncaught SyntaxError: The requested module '../typeof.js' does not provide an export named 'default'
```

Expected: 

No error, because it's loading the ESM version of `typeof.js` instead of the CJS version. 

### Environment

Babel version 7.15.4

### Possible solution

This looks like a trivial fix. I just can't figure out where the source code that generates these files lives. 

### Additional context

I encountered this error when importing i18next in a browser. I was able to fix it by changing that import directly in node_modules. I then installed @babel/runtime directly in a clean npm repo to confirm my node_modules wasn't altered by some other process.

**Comment by nicolo-ribaudo** [comment]
The code which should "fix" the imports in the helpers is at in https://github.com/babel/babel/blob/178d43ff179e8f245b9e37887c14d689b5db1b07/packages/babel-plugin-transform-runtime/scripts/build-dist.js#L260.



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Whenever you want to re-generate the helpers run `build-dist`. For a full build, run `make build`
1. Update the code!
1. If it is working, run `make test` to run all the tests
1. It might make sense to commit `@babel/runtime/helpers/esm/possibleConstructorReturn.js`, so that we notice if we break it again.
1. Run `git push` and open a PR!

**Comment by pmcelhaney** [comment]
I spent a few hours looking into and I'm lost. :( 

With most of the  runtime helpers, `path.get("arguments")[0].node` is just the name of the helper, e.g. `"assertThisInitialized"`. But for typeof, it's the full path to the file without the esm directory (`"@babel/runtime/helpers/typeof"`). 

https://github.com/babel/babel/blob/178d43ff179e8f245b9e37887c14d689b5db1b07/packages/babel-plugin-transform-runtime/scripts/build-dist.js#L298

I can't figure out where the code to stick the import for the typeof helper at the top of the file is. 

I noticed there's a [babel-runtime/helpers/typeof.js](https://github.com/babel/babel/blob/672a58660f0b15691c44582f1f3fdcdac0fa0d2f/packages/babel-runtime/helpers/typeof.js) but is counterpart is missing from [babel-runtime/helpers/esm/](https://github.com/babel/babel/blob/672a58660f0b15691c44582f1f3fdcdac0fa0d2f/packages/babel-runtime/helpers/esm). Also typeof seems to be a special case here:

https://github.com/babel/babel/blob/178d43ff179e8f245b9e37887c14d689b5db1b07/packages/babel-plugin-transform-runtime/scripts/build-dist.js#L238-L258

Not sure if either of those has anything to do with it.

**Comment by nicolo-ribaudo** [comment]
@pmcelhaney It looks like this is a problem when injecting an import _because the helpers is being transpiled and depends on another helper_, not for normal helper dependencies. In the `possibleConstructorReturn`, the helper itself does not depend on `typeof`: https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-helpers/src/helpers.ts#L618-L630

A working workaround would be to remove the `"@babel/runtime/helpers/"` prefix in `adjustImportPath`.

**Comment by nicolo-ribaudo** [comment]
Hi @pmcelhaney! Are you still working on this?

**Comment by FuryACE007** [comment]
Hi,
I am a newbie and I want to make my first open-source contribution. Could you please assign this bug to me?

**Comment by nicolo-ribaudo** [comment]
Sure, thanks! If you need any help, feel free to ask here or on slack.

**Comment by exb** [comment]
Hi @FuryACE007! 👋 Still working on this? If not, I’d like to pick this up.

**Comment by nicolo-ribaudo** [comment]
@exb If @FuryACE007 doesn't respond within Monday, this bug is yours!

**Comment by azeez1776** [comment]
Hey @nicolo-ribaudo can I try working on the problem?

**Comment by nicolo-ribaudo** [comment]
@exb Are you still working on this?

**Comment by exb** [comment]
Hi @nicolo-ribaudo, I started working on this yesterday :)

**Comment by azeez1776** [comment]
Hey @exb , pls let me know when your done
