### ISSUE TITLE
JSX transforms variable into string - breaking react.createElement

### ISSUE THREAD

**Issue by abritinthebay** [babel/babel#1379]
Simple example:

    var myElement = React.createClass({});
    var x = <myElement prop={foo} />

Simple enough, right? Well this is transpiled into:

    var myElement = React.createClass({
        displayName: "myElement"
    });
    var x = React.createElement("myElement", { prop: foo });

As you can see in `createElement` the `myElement` variable is now a string. This seems somewhat counter to how it's intended to work. 

Thoughts as to a way to workaround this, or a way to fix this?

**Comment by fkling** [comment]
That is exactly working as expected. From the [React documentation](https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components)

> **HTML Tags vs. React Components**
> 
> React can either render HTML tags (strings) or React components
> (classes).
> 
> To render a HTML tag, just use lower-case tag names in JSX:
> 
    var myDivElement = <div className="foo" />;
    React.render(myDivElement, document.body);
> 
> To render a React Component, just create a local variable that starts
> with an upper-case letter:
> 
>     var MyComponent = React.createClass({/*...*/});
>     var myElement = <MyComponent someProperty={true} />;
>     React.render(myElement, document.body);
> 
> React's JSX uses the upper vs. lower case convention to distinguish
> between local component classes and HTML tags.

**Comment by abritinthebay** [comment]
well... there we are then. Clearly I missed that (and I did look). Thanks for the correction!
