### ISSUE TITLE
Iterop require on import doesn't check if default is present, breaks object import.

### ISSUE THREAD

**Issue by abritinthebay** [babel/babel#1380]
if I have an export in MyModule like so:

    export {foo, bar, baz};

You'd expect that this would work:

    import myVar from myModule;

and in fact it does with a default require, populating `myVar` as an object with the named properties _but_ the interop wrapper breaks this. 

It checks to see if the module is an ES6 module and if so returns `obj["default"]` but that doesn't exist! This means that this breaks the logic and the only way to create a module in this form is to declare (and wrap) these like so:

    var obj = {foo, bar, baz};
    export default obj;

while this is a workaround it seems somewhat like a bug. Is this intended behavior from some spec or just a bug?

**Comment by fkling** [comment]
> Is this intended behavior from some spec or just a bug?

It is intended behavior. In your first example, you don't have a default export, hence you cannot use a default import. However, you could use a namespace import:

    import * as myVar from myModule;

[See the tables of the different syntax in](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-source-text-module-records).

**Comment by abritinthebay** [comment]
Ah, I figured it was a case of spec behavior vs require behavior clashing somewhere. Annoying... but understandable.

Namespace import it is!
