### ISSUE TITLE
`babel-node --ignore` actually accepts glob pattern instead of regexp

### ISSUE THREAD

**Issue by deepsweet** [babel/babel#1381]
https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L148
+
https://github.com/babel/babel/blob/master/src/babel/util.js#L73
+
https://github.com/isaacs/minimatch/blob/master/minimatch.js#L584-L586

so it's very difficult to make a custom ignore – you need to write a glob pattern that will be transformed to regexp you actually want.

**Comment by sebmck** [comment]
See #1376.
