### ISSUE TITLE
[Bug]: jsx tagName this is not treated as string currently

### ISSUE THREAD

**Issue by LongTengDao** [babel/babel#13830]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[repl](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DwQwBA9AfA3AUMALgCwJYGdKwQQSzIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=7.15.8&externalPlugins=&assumptions=%7B%7D)

```jsx
<a />;
<this />;
<A />;
```

### Current and expected behavior

current:

```js
/*#__PURE__*/
React.createElement("a", null);

/*#__PURE__*/
React.createElement(this, null);

/*#__PURE__*/
React.createElement(A, null);
```

expected:

```js
/*#__PURE__*/
React.createElement("a", null);

/*#__PURE__*/
React.createElement("this", null);

/*#__PURE__*/
React.createElement(A, null);
```

### Environment

repl

### Additional context

[User-Defined Components Must Be Capitalized](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)

[TypeScript will follow suit](https://github.com/microsoft/TypeScript/issues/46275#issuecomment-940377922)

**Comment by JLHwung** [comment]
Related: https://github.com/babel/babel/pull/12279#issuecomment-770285954

**Comment by JLHwung** [comment]
The behaviour was introduced no later than 6.0.0:

https://github.com/babel/babel/blob/3974dd762d1c58eb21da78eeab736508be67b9db/packages/babel-plugin-builder-react-jsx/src/index.js#L31-L32

And it seems to me more like a feature than a bug. Given that it has been there for a long time and people may depend on that, I don't think we are gonna change that unless we have strong opinions from the jsx team.
