### ISSUE TITLE
System.import to require(...) when amd

### ISSUE THREAD

**Issue by Frrede** [babel/babel#1383]
When I write
```
System.import("lib/math").then(function(m) {
  alert("2π = " + m.sum(m.pi, m.pi));
});
```
shouldn't that gets transformed to something like that when I use '--modules amd'
```
require(["lib/math"], function(m) {
    alert("2π = " + m.sum(m.pi, m.pi));
});
```
System.import is ES6 I think?
Without transpiling System.import one has to use a polyfill for it I guess but that's quite an overhead in the frontend.
Thanks!

**Comment by sebmck** [comment]
Nope, you need to use ES6 module syntax so:

```javascript
import * as m from "lib/math";
```

**Comment by Frrede** [comment]
But I want to import a script conditionally when I need it and not at the top of the file and according to http://www.2ality.com/2014/09/es6-modules-final.html my example is the right ES6 syntax or isn't it?

**Comment by RReverser** [comment]
Your example doesn't use ES6 syntax at all, it just uses System Loader API which you need to polyfill if you want to use it.

**Comment by Frrede** [comment]
Ah ok sorry, I think I misread the article then. I thought because of the headline "The ECMAScript 6 module loader API" in the article it's a part of ES6 but it's more like a separat API I guess?
Thanks for your help!

**Comment by RReverser** [comment]
It is part of ES6, but it's just an API at the same time (i.e. like Promises).

**Comment by sebmck** [comment]
@RReverser Not really. It's a [separate WHATWG spec](https://github.com/whatwg/loader).

**Comment by thgreasi** [comment]
Nevertheless, it would be great to have a transformer that would change it the other module types. In my case, the equivalent umd pattern.

**Comment by sebmck** [comment]
@thgreasi Babel has a [plugin api](http://babeljs.io/docs/usage/plugins) if you want to take a stab at it.

**Comment by thgreasi** [comment]
@sebmck Yea, I have noticed and I have been wrestling with it for some days :)

**Comment by thgreasi** [comment]
Just pushed [babel-plugin-system-import-transformer](https://github.com/thgreasi/babel-plugin-system-import-transformer) that replaces `System.import` to AMD, CommonnJS & Global module imports.
There is no AMD specific configuration yet (aka you get all the UMD like statements). Hope this helps.
