### ISSUE TITLE
[Bug]: Upgrading some babel packages leading to npm install erroring out

### ISSUE THREAD

**Issue by leximarie** [babel/babel#13839]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

This is breaking, not sure what other packages are broken
```bash
npm install @babel/plugin-proposal-throw-expressions@7.14.5
```

### Configuration file name

babel.config.js

### Current and expected behavior

npm install shouldn't break :)

Error when npm installing: 
`Unexpected end of JSON input while parsing near '...nicolo-ribaudo"`

### Environment

  System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    @babel/core: 7.15.8 => 7.15.8 
    @babel/eslint-parser: 7.15.8 => 7.15.8 
    @babel/plugin-proposal-throw-expressions: 7.14.5 => 7.12.1 
    @babel/plugin-syntax-dynamic-import: 7.8.3 => 7.8.3 
    @babel/plugin-transform-runtime: 7.12.1 => 7.12.1 
    @babel/preset-env: 7.12.1 => 7.12.1 
    @babel/preset-react: 7.12.5 => 7.12.5 
    @babel/register: 7.12.1 => 7.12.1 
    babel-jest: 24.9.0 => 24.9.0 
    babel-loader: 8.2.2 => 8.2.2 
    babel-plugin-transform-react-remove-prop-types: 0.4.24 => 0.4.24 
    eslint: 7.13.0 => 7.13.0 
    webpack: ^5.56.0 => 5.56.0

**Comment by leximarie** [comment]
Tried updating `@babel/plugin-transform-runtime` and I'm getting this error
```
Unexpected end of JSON input while parsing near '...085338"
     }
 }'
```

**Comment by leximarie** [comment]
@nicolo-ribaudo  does that mean it's something on my end or on yours?

**Comment by nicolo-ribaudo** [comment]
Can you share the full stack trace?
