### ISSUE TITLE
[Bug]: @babel/transform-react-jsx "Unknown term type: reference"

### ISSUE THREAD

**Issue by adminy** [babel/babel#13847]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```javascript
const tokens = [
   ['REGEXP', /\/(?<source>(\\.|[^\1])*?[^\1\\]?)\/(?<options>[gim]+)?/, result => {
     const str = result.groups.source
       .replace(/\\u([0-9a-f]{4})/i, value => String.fromCharCode(parseInt(value.slice(2), 16)))
       .replace(/\\x([0-9a-f]{2})/i, value => {
         const char = parseInt(value.slice(2), 16)
         return char < 127 ? `\\x${char.toString(16)}` : String.fromCharCode(char)
       })

     return [str, result.groups.options]
   }]
]
```

### Configuration file name

package.json

### Configuration

```javascript
{
  ...
  "babel": {
    "plugins": [
      [
        "@babel/transform-react-jsx",
        {
          "pragma": "((fn, args) => fn(args))"
        }
      ]
    ]
  }
  }
  ```

### Current and expected behavior

Compiles and runs as if I ran the js directly.

### Environment

Latest Available:
    "@babel/cli": "^7.15.7",
    "@babel/core": "^7.15.8",
    "@babel/node": "^7.15.8",
    "@babel/plugin-transform-react-jsx": "^7.14.9",
    "@babel/preset-env": "^7.15.8",

### Additional context

I'm trying to use nicer looking <Tag {...params} /> way of calling a function.

**Comment by adminy** [comment]
Thank you for looking into this.

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/jviereck/regjsparser/pull/115
