### ISSUE TITLE
Update the deprecation warning for `babel-eslint` to mention `@babel/eslint-parser` instead of `@babel/eslint`

### ISSUE THREAD

**Issue by lgarron** [babel/babel#13870]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I was trying to figure out why `eslint` was failing on the `export` keyword in a `"type": "module"` project.

- A bunch of internet searches say to use `babel-eslint`.
- `babel-eslint` says it's deprecated and to use `@babel/eslint`.
- `@babel/eslint` says it's deprecated and to use `@babel/eslint-parser`.

I know that the JS tooling ecosystem is constantly being refactored, but this is really demotivating.

### Describe the solution you'd like

Would you consider releasing one more version of `babel-eslint` so that 
https://www.npmjs.com/package/babel-eslint points directly to `@babel/eslint-parser`?

I know that's only a small detail, but it would be really helpful to be pointed directly to the right thing instead of being sent on a wild goose chase as my first experience trying to install this parser. 🙏

### Describe alternatives you've considered

N/A

**Comment by liuxingbaoyu** [comment]
It appears to have done so.
