### ISSUE TITLE
examples: /auth-flow/app.js: Line 7: 'this' is not allowed before super()

### ISSUE THREAD

**Issue by Howard-Nzxt** [babel/babel#1387]
I try add 
```
super();
```
at line 7 and line 72. will fix this problem. 
thanks :)

**Comment by monsanto** [comment]
I'm confused. Did you mean to file this bug report at https://github.com/rackt/react-router/ ?

**Comment by RReverser** [comment]
@monsanto I think so too. Doesn't seem to be related to Babel.

**Comment by Howard-Nzxt** [comment]
@monsanto  yes, I report the wrong issue.  so embarrassed...
