### ISSUE TITLE
[Bug]: Bodyless methods AST is different from `@typescript-eslint/parser`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#13878]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
class A {
  x();
  x() {}
}
```

### Configuration

```jsonc
{
  plugins: ["estree", "typescript"]
}
```

### Current and expected behavior

For the first `x();` we generate a `FunctionExpression` node without the `.body` property, while `@typescript-eslint/parser` generates a `TSEmptyBodyFunctionExpression` node. It's probably better to align with them, so that `FunctionExpression`s always have a body.

Also, when it comes to function declarations we already do something similar (`TSDeclareFunction` instead of `FunctionDeclaration`).

### Environment

- `@babel/parser` 7

### Additional context

This is a breaking change, it needs to wait for Babel 8.

**Comment by liuxingbaoyu** [comment]
Thanks for the mention! I'll take a look.

**Comment by liuxingbaoyu** [comment]
> For the first x(); we generate a FunctionExpression node without the .body property, while @typescript-eslint/parser generates a TSEmptyBodyFunctionExpression node.

We appear to have generated `TSDeclareMethod` now.
This was a bit hard to unify with `typescript-eslint` , since that's now unified with our `ClassMethod` for JS methods.

**Comment by nicolo-ribaudo** [comment]
Unification is good but not a requirement, so if you think aligning is not worth the cost we can close this issue.

**Comment by liuxingbaoyu** [comment]
`TSDeclareMethod` = `MethodDefinition` + `TSEmptyBodyFunctionExpression`.
Since we can't unify `MethodDefinition` no matter what, it looks good to keep it as it is.
