### ISSUE TITLE
[Bug]: plugin-transform-modules-systemjs transformation is unsafe

### ISSUE THREAD

**Issue by Rich-Harris** [babel/babel#13888]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgDzgXzgMyhEcDkAdAPTKEBWAzvgNwBQdwmcAFDFAK4CmAlInQEgAxhAB2leKgC8cAIz1hYyhAA2XQiogBzFsh700DUVwDurISoCGlSnC7IYXUQBNbqBGh4t9dIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.15.8&externalPlugins=%40babel%2Fplugin-transform-modules-systemjs%407.15.4&assumptions=%7B%7D).

```js
import { x } from './x.js';

if (true) {
	const x = 1;
	console.log(x);
}

new (class extends x {})();
```

### Configuration

Using `@babel/plugin-transform-modules-systemjs`, nothing else

### Current and expected behavior

I would expect the `x = 1` to declare a local constant, as it does in the original code. Instead, it assigns to a new module-level variable (which in this case has the same name as an import, causing an error). 

### Environment

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  npmPackages:
    @babel/core: ^7.15.8 => 7.15.8 
    @babel/plugin-proposal-dynamic-import: ^7.14.5 => 7.14.5 
    @babel/plugin-transform-modules-systemjs: ^7.15.4 => 7.15.4 
```

### Additional context

cc @guybedford :)

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue?

**Comment by The-x-Theorist** [comment]
If we rename the variables in hoisting operation, `babel-plugin-proposal-do-expressions/test/fixtures/do-expressions/variable-declaration-start-to-iife/exec.js: bar is not defined` this test throws error.

**Comment by lightmare** [comment]
> If we rename the variables in hoisting operation, `babel-plugin-proposal-do-expressions/test/fixtures/do-expressions/variable-declaration-start-to-iife/exec.js: bar is not defined` this test throws error.

Can you keep the name for `var` declarations, and only rename `const/let` ?

**Comment by The-x-Theorist** [comment]
> Can you keep the name for `var` declarations, and only rename `const/let` ?

Yeah, I can do that.
