### ISSUE TITLE
Error when requiring babel in Webpack in a file that is processed via babel-loader

### ISSUE THREAD

**Issue by kenwheeler** [babel/babel#1389]
I have a file where I require babel, in order to use the .transform method. Any time the following line is in a file that is also processed by babel-loader, I get a slew of errors.

```
var babel = require('babel');
```

The errors in question can be seen here:

https://gist.github.com/kenwheeler/7b856ddf18c3f1af94ce

@gaearon had suggested that there is a conflict between Webpack and require.resolve, in util.js:

https://github.com/babel/babel/blob/master/src/babel/util.js#L35

**Comment by sebmck** [comment]
It browserifies perfectly so it's probably not a Babel issue. The errors are all on JSON and seems to be webpack config-specific.

**Comment by monsanto** [comment]
Presumably you mean to include `babel-core` if you are using webpack?

**Comment by kenwheeler** [comment]
The error persisted even after properly configuring `json-loader`. Also, this error is on JSON?:

```
Error: Cannot resolve module 'fs'
```

**Comment by sebmck** [comment]
It's not, it's because webpack doesn't attempt to shim the `fs` module.

**Comment by kenwheeler** [comment]
I don't mean to suggest there is any inadequacy in the library, I just would really prefer to use babel for https://github.com/FormidableLabs/component-playground , than JSX Transform.

**Comment by sebmck** [comment]
Have you tried the browser version? `require("babel-core/browser")`

**Comment by kenwheeler** [comment]
I just tried and got:

```
WARNING in ./~/babel-core/browser.js
Critical dependencies:
1:475-482 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/babel-core/browser.js 1:475-482
```

and in my app:

```
ReferenceError: Unknown option: stage
```

Does the browser version not support the stage option?

**Comment by sebmck** [comment]
It should support all the same options. Only way that can be thrown is if you're on a 4.x version of `babel-core`.

**Comment by kenwheeler** [comment]
You're right I was on 4. Switched to 5 and added a noParse option to my webpack config for the browser version and everything is working swimmingly. Thanks so much, love the library and I admire your dedication to supporting it.

**Comment by sebmck** [comment]
Awesome, glad to hear!
