### ISSUE TITLE
[Bug]: JSX pragma can happen anywhere in a comment

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#13896]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
// Make sure not to use a jsx pragma here (like "@jsx Something"), we need this to be React.createElement!
<blah/>
```

### Configuration

N/A

### Current and expected behavior

Currently, the above will actually generate this code:

```js
Something"),("blah", null);
``` 

But, even if ignore the syntax error, it seems to me that JSX pragmas should be a bit stricter as to what they match.For example, if we just add the `^` and `$` operators to the current RegExp:
```regex
/\*?\s*@jsx\s+([^\s]+)/
```
becomes:
```regex
/\^*?\s*@jsx\s+([^\s]+)$/
```
Then this would lead to jsx pragmas only being allowed if they are the only content in the comment. This seems to me to be more in the spirit of the intent.

In many ways, the current RegExp is a bit nonsensical just in its construction: `*?\s*` with no ^ is a completely useless pattern, since the entire sequence is optional and there's nothing preceding it. That's why something like "francisco@jsx hi'' is matched.

BTW, I actually ran into this myself, which is why I am filing this. It's annoying that one's first inclination to "escape" the jsx pragma (by doing something like \\@jsx blah) doesn't work either, for the same reason "francisco@jsx hi" is matched.

### Environment

N/A

### Possible solution

Changing

```regex
/\*?\s*@jsx\s+([^\s]+)/
```
to

```regex
/\^*?\s*@jsx\s+([^\s]+)$/
```

And making the equivalent change for JSX fragments.

**Comment by nicolo-ribaudo** [comment]
Yeah, that regexp was definitely meant to be with `^` and `$`.

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue, But where I can start of with?

**Comment by JLHwung** [comment]
@The-x-Theorist You can check https://github.com/babel/babel/blob/d30308fe8eb5dd11c16a2d4c3a058e63ffe7949e/packages/babel-plugin-transform-react-jsx/src/create-plugin.ts#L37-L38

**Comment by The-x-Theorist** [comment]
@JLHwung Could you please assign this issue to me so that I can work on it?

**Comment by The-x-Theorist** [comment]
After changing the regex pattern some other tests are failing.

**Comment by The-x-Theorist** [comment]
`Test cannot throw and also return output code:` how this error can be fixed?

**Comment by JLHwung** [comment]
> Test cannot throw and also return output code:

The error means some tests (expect to fail) are now passing.

> `/\^*?\s*@jsx\s+([^\s]+)$/`

Note that the proposed regex forbids `/* @jsx Something */` (when there are whitespaces after `Something`)

I think you can add `\s*` to the proposed regex

```
/^\*?\s*@jsx\s+([^\s]+)\s*$/
```
so that `/* @jsx Something */` can be passed.

You can also copy the regex to https://regex101.com/r/Wt1cQ5/1/ and see if it matches JSX pragma.

**Comment by JLHwung** [comment]
Should we allow

```
/**
 * @jsx jsx
 */
```
? Such comment pattern can be seen in JSX docs or copyright headers.

**Comment by The-x-Theorist** [comment]
Yes we should allow this pattern for JSX docs or copyright headers, I will change the regex pattern accordingly.
