### ISSUE TITLE
[Bug]: `super()` in class methods is not reported by `@babel/eslint-parser`

### ISSUE THREAD

**Issue by ljharb** [babel/babel#13903]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```jsx
        class Foo extends React.Component {
          contructor(props) {
            super(props);
            this.initialValues = {
              test: '',
            };
          }

          render = () => {
            return (
              <Component
                initialValues={this.props.initialValues || this.initialValues}
              >
                {formikProps => (
                  <Input {...formikProps} />
                )}
              </Component>
            );
          }
        }
```

### Configuration

n/a

### Current and expected behavior

I would expect a parse error, because `super()` is not valid except in `constructor() {}` and this is `contructor() {}`.

### Environment

v7.16.0 of `@babel/eslint-parser`, eslint v8.1.10, node v17.0.1

### Possible solution

Don't allow `super()` outside of a class `constructor() {}`

### Additional context

Confusion over this led me to file https://github.com/eslint/eslint/issues/15234, but eslint 8 is actually handling this correctly because of the typo.

related: https://github.com/typescript-eslint/typescript-eslint/issues/4072

**Comment by JLHwung** [comment]
Babel with estree plugin already throws: https://astexplorer.net/#/gist/03f767f5dbe210bd68f53a0e841b7d35/ddcf3abd498633acefc578aba4c50478eedb30eb

and we don't have "contructor" in the codebase anyway, I guess there is nothing can be done on Babel's side?

**Comment by ljharb** [comment]
hmm, then why does the test case pass for me in eslint-plugin-react? it fails properly in eslint 8.

**Comment by ljharb** [comment]
In AST Explorer, when i select the babel *eslint* parser, as opposed to the babel parser, it does not throw.

**Comment by nicolo-ribaudo** [comment]
I don't know why, but it looks like this is intentional:
https://github.com/babel/babel/blob/5b29557af9491cec39d555849054f70785be95fa/eslint/babel-eslint-parser/src/worker/configuration.cjs#L31

**Comment by nicolo-ribaudo** [comment]
We should probably just align with the current ESLint 7 and 8 behavior, since that PR was to align with the old ESLint/espree version.

**Comment by nicolo-ribaudo** [comment]
Other context for a similar behavior: https://github.com/babel/babel-eslint/issues/327

**Comment by ljharb** [comment]
oof, ok - so how can i opt out of this behavior?

**Comment by nicolo-ribaudo** [comment]
In your eslint config:
```js
parserOpts: {
  babelOptions: {
    allowReturnOutsideFunction: false,
    allowSuperOutsideMethod: false,
  }
}
```

**Comment by nicolo-ribaudo** [comment]
Actually, babel/babel-eslint#327 is opt-in and not by default, so it's different.

**Comment by nicolo-ribaudo** [comment]
Currently ESLint accepts this code (our `allowReturnOutsideFunction`):
```js
return 2;
```

**Comment by ljharb** [comment]
`allowReturnOutsideFunction` is correct for CJS and transpiled ESM, but wildly incorrect for native ESM, so it seems like it should depend on the sourceType.

`allowSuperOutsideMethod` hasn't ever been correct, so i'm baffled why that'd ever be enabled.
