### ISSUE TITLE
Initializers with Inheritance

### ISSUE THREAD

**Issue by alidavut** [babel/babel#1391]
```javascript
class A {
  constructor() {
    console.log('the val :' + this.key);
  }
}

class B extends A {
  key = 'test';
}

new B();
```

When I run this code I get this output:
```
the val :undefined
```

What do you think? Should this be ```the val: 'test'```

**Comment by monsanto** [comment]
That would imply that `this.key = 'test'` executes before `super()`, which is illegal. Initializers aren't on the prototype, if that is the source of confusion

**Comment by monsanto** [comment]
(Specifically [this section](https://gist.github.com/jeffmo/054df782c05639da2adb#property-initialization-during-construct-and-supercall), I fudged the earlier link)
