### ISSUE TITLE
[Bug]: `@babel/estlint-parser` fails in projects relying on `parserOverride`

### ISSUE THREAD

**Issue by birdofpreyru** [babel/babel#13915]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

`@babel/eslint-parser` fails if Babel config in the host project relies on any preset / plugin using `parserOverride`. This happens because [`@babel/eslint-parser` itself uses it to capture Babel options](https://github.com/babel/babel/blob/05af38cff2d5fc2288ce79b11b755b361a7e946d/eslint/babel-eslint-parser/src/worker/extract-parser-options-plugin.cjs#L3-L5). Although there seems to be [some code in place](https://github.com/babel/babel/blob/05af38cff2d5fc2288ce79b11b755b361a7e946d/eslint/babel-eslint-parser/src/worker/maybeParse.cjs#L20-L29) to safeguard against "_More than one plugin attempted to override parsing_" error when some other parsers/plugin rely on `parserOverride`, it does not seem to help in practice.

### Current and expected behavior

`@babel/eslint-parser` fails to work in the described scenario, it should work though.

### Environment

Babel 7.16.0

**Comment by nicolo-ribaudo** [comment]
This is probably a regression from when I refactored `@babel/eslint-parser`. Do you know if an older version worked?

**Comment by birdofpreyru** [comment]
@nicolo-ribaudo I don't know: before v7.16.0 (and #13782) it was not working for me (in my first-to-go project for testing risky upgrades) because of #13060.

**Comment by nicolo-ribaudo** [comment]
This was a silly error: after catching the error for the duplicate `parserOverride`, I was re-running Babel with the same options so it always threw again :grimacing:

PR: #13918
