### ISSUE TITLE
[Bug]: Unexpected Token '<'  error in jsx

### ISSUE THREAD

**Issue by FabriSoftware** [babel/babel#13926]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```jsx
import React from 'react';

 function App(){

  return (
{/*in this line give error >*/}<div><h1>Hello World</h1></div>
  );
}

export defualt App;

```

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ]
}
```

### Current and expected behavior

this code works in babel-loader 7.1.5 but i had to update all my babel dependencies and it gave me this error

### Environment

System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v16.6.1/bin/npm
  npmPackages:
    @babel/cli: ^7.16.0 => 7.16.0 
    @babel/core: ^7.16.0 => 7.16.0 
    @babel/node: ^7.16.0 => 7.16.0 
    @babel/preset-env: ^7.16.0 => 7.16.0 
    @babel/preset-react: ^7.16.0 => 7.16.0 
    babel-loader: ^8.2.3 => 8.2.3 
    webpack: ^5.61.0 => 5.61.0 

### Additional context

/home/User/Desktop/proyects/testinCode/DashBoard/src/app/components/App.jsx:8
    \<div\>
    ^

SyntaxError: Unexpected token '<'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module._compile (/home/User/Desktop/proyects/testinCode/DashBoard/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .jsx] (/home/User/Desktop/proyects/testinCode/DashBoard/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)

**Comment by nicolo-ribaudo** [comment]
That is not valid JSX. Does it work if you remove the `{ }` around the comment?
```js
import React from 'react';

 function App(){

  return (
    <div><h1>Hello World</h1></div>
  );
}

export defualt App;
```

If it still doesn't work:
- Can you share your webpack config?
- What is the path of the `.babelrc` file?
- What is the path of the webpack config?
- Which command are you using to run webpack?

**Comment by FabriSoftware** [comment]
The {} I put when I wrote the issues 

`/` = root of the proyect
webpack dir:
/webpack.config.js:
```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
  entry: "./src/app/index.jsx",
  output: {
    path: __dirname + "/src/public/js/",
    filename: "bundle.js",
  },
  module: {
    rules: [{
        use: 'babel-loader',
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        query:
      {
        presets:['react']
      }
    }],
  },
  resolve: {
    extensions: ['.js', '.jsx']
  }
};
```
 > dir of .babelrc

 /.babelrc
 
 and the commands I run is `webpack --mode development --watch`
or I also use the express-react-view engine that also uses webpack

**Comment by nicolo-ribaudo** [comment]
The only problem I see in your config is that you are mixing Babel 6 (`babel-preset-react`, in your webpack config) and Babel 7 (in your `.babelrc`). However, the error you see isn't caused by this problem. Could you create a repository that reproduces the error? It will help a lot with understanding what causes the problem.

Also, looking at your stack trace again it seems like you are trying to run `/home/User/Desktop/proyects/testinCode/DashBoard/src/app/components/App.jsx` on Node.js (the `internal/modules/cjs/loader` piece in the stack trace means that), rather than just bundling it with weback.

You are probably using Babel to transforms the file that you are bundling with webpack, but not to transform the files you are running on Node.js.

**Comment by firstChairCoder** [comment]
Could simply changing the last line to export default App solve your issue. I see "defualt" in the input code.
The other suggestions had it working on my end after adding this line.

**Comment by SimonChaumet** [comment]
Not sure if I have the same bug, I followed the tutorial https://babeljs.io/docs/en/babel-node :

.babelrc.json
```json
{
  "presets": [
    ["@babel/preset-react", {
      "runtime": "automatic"
    }],
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ]
  ]
}
```

package.json
```json
"scripts": {
    "build": "babel scripts/server.js app -d dist",
    "watch": "yarn run build && nodemon --experimental-specifier-resolution=node dist/server.js",
    "start": "yarn run build && node --experimental-specifier-resolution=node dist/server.js"
},
"devDependencies": {
    "@babel/cli": "^7.16.8",
    "@babel/core": "^7.16.12",
    "@babel/eslint-parser": "^7.14.7",
    "@babel/node": "^7.16.8",
    "@babel/plugin-syntax-top-level-await": "^7.14.5",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7"
}
```

Result :
![Screenshot from 2022-01-31 19-59-42](https://user-images.githubusercontent.com/7894362/151855731-42d2e9a5-cfbb-420e-95fd-a63b2dbb5218.png)

But the produced code in dist seems correct :
![Screenshot from 2022-01-31 20-00-55](https://user-images.githubusercontent.com/7894362/151855851-7f6e7d6d-ad4c-4ce4-b173-c68c95a373d5.png)

**Comment by JLHwung** [comment]
@SimonChaumet Please rename `server.js` to `server.jsx` if it contains JSX syntax, otherwise `preset-react` will not be applied to that file.

**Comment by nicolo-ribaudo** [comment]
Unfortunately `@babel/node` and `@babel/register` don't support native ESM files yet, because there isn't a stable hook to compile them on-the-fly.

**Comment by SimonChaumet** [comment]
@JLHwung node doesn't accept jsx extensions apparently
![Screenshot from 2022-01-31 20-27-03](https://user-images.githubusercontent.com/7894362/151859412-c33d2308-e30c-40a0-a163-d39ca90e4003.png)

**Comment by JLHwung** [comment]
Oh I was meant for `src/server.jsx`, they will be compiled into `dist/server.js`.

**Comment by SimonChaumet** [comment]
@JLHwung server.js does not contain react code, the only file is the one shown above included in the app directory which is compiled into .js but I have errors shown on the base code instead of the compiled code which is weird

**Comment by JLHwung** [comment]
It seems to me it is a nodemon-specific issue. Does nodemon have any cache? Did you try restarting nodemon? If that can't help, please prepare a reproduction repo, and open a new issue.

**Comment by SimonChaumet** [comment]
@JLHwung even with only node (by running start) the result is still the same

**Comment by nicolo-ribaudo** [comment]
Are you running your code with `@babel/node`, or are you compiling them with `@babel/cli` and then run them as normal Node.js scripts?

In the first case, `@babel/node` doesn't support yet native ESM files because Node.js doesn't have a stable ESM loader API yet.

**Comment by SimonChaumet** [comment]
@nicolo-ribaudo as you can see in package.json above I run build and then run on it

**Comment by nicolo-ribaudo** [comment]
I'm confused because the error shown in your screenshot is _not_ in the `dist` folder, while your `package.json` runs files in `dist`.

**Comment by SimonChaumet** [comment]
My paths are modified to get the code from my source directory instead of getting the code from the dist folder, I think it's related to #8193

**Comment by a89529294** [comment]
I ran into the same issue. I solved it by removing type:'module' from package.json.

**Comment by Urssito** [comment]
i had the same problem, and I saw what webpack doesn't read the `.jsx` files, so i added jsx option to test key on babel loader

`
module.exports = {
//some code
module:{
    rules: [ {test: /\.js$|jsx/ ...
//rest of code
}
`

**Comment by KhalfaniW** [comment]
Removing `type: module` from my package.json allowed me to see more errors. 

I also had conflicting versions (v6 and v7) for some babel packages

**Comment by SanNic20** [comment]
Somebody find a solution ?

**Comment by liuxingbaoyu** [comment]
This issue looks out of date, if anyone encounters it again please open a new issue.

**Comment by jaryroxas** [comment]
I only encounter it if you use babel 6 and have a different config format ( e.g. format for babel 7 config )
