### ISSUE TITLE
[Bug]: Babel does not throw duplicated __proto__ when followed by a property whose value is an assignment expression

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#13930]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
({
  __proto__: a,
  __proto__: a,
  a: a = 1
})
```

[REPL](https://babel.dev/repl#?browsers=firefox%2091&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=BQbwUABBD60A4CcD2AXJsBcECGAaSM8yamO-U2W2EAvBAIxgC-AlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-1&prettier=false&targets=&version=7.16.2&externalPlugins=&assumptions=%7B%7D)

### Configuration

N. A.

### Current and expected behavior

Currently Babel parses it without errors.

It should throw 

```
Redefinition of __proto__ property.
```

just like Babel correctly throws in the following example:

```js
({
  __proto__: a,
  __proto__: a,
})
```

### Environment

REPL

### Possible solution

This issue is very similar to https://github.com/babel/babel/issues/10262. 

Like how we handle `shorthandAssign`

https://github.com/babel/babel/blob/7250d2562be881f9cdc24c6646468e0f3afcaf9d/packages/babel-parser/src/parser/expression.js#L317-L319

we should reset `doubleProto` only when it is used correctly.

https://github.com/babel/babel/blob/7250d2562be881f9cdc24c6646468e0f3afcaf9d/packages/babel-parser/src/parser/expression.js#L312

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue.

**Comment by nicolo-ribaudo** [comment]
Thanks! If you need any help feel free to ask.

**Comment by The-x-Theorist** [comment]
How does a doubleProto assignment expression look like?

**Comment by JLHwung** [comment]
A doubleProto assignment is an object literal with duplicate `__proto__` key:
```js
// invalid
({
  __proto__: a,
  __proto__: a,
})
```
However, the duplicate `__proto__` key is allowed in destructuring:
```js
// valid
({
  __proto__: a,
  __proto__: b
}) => {}
```
so we should track such errors in `refExpressionErrors`, and then throw later when we are sure it is a pattern. In this issue, the `a = 1` tricks the parser to think `__proto__: a, __proto__: a,` has been in a pattern, so we should check how assignment expression is parsed.

**Comment by The-x-Theorist** [comment]
@JLHwung Thank you for helping, I'm soon opening a PR.
