### ISSUE TITLE
[Bug]: @babel/parser throws error when parsing specific regular expressions

### ISSUE THREAD

**Issue by Aarebecca** [babel/babel#13935]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from "@babel/parser";

const ast = parse(`const regex = /\//i`);
```

### Current and expected behavior

**Current**:  As shown below, it throws an exception
![image](https://user-images.githubusercontent.com/25787943/140607629-1712c797-9793-4ad3-90e2-30765039a270.png)
**Expected**: 
I want to be able to parse the JS snippet correctly and get the AST, which should look like this:
![image](https://user-images.githubusercontent.com/25787943/140607575-1f66e718-679a-4737-8774-7fbc78849248.png)

### Environment

  * System:
    * OS: Windows 10 10.0.19043
  * Binaries:
    * Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    * Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    * npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  * npmPackages:
    * @babel/generator: ^7.16.0 => 7.16.0
    * @babel/parser: ^7.16.0 => 7.16.0
    * @babel/traverse: ^7.16.0 => 7.16.0
    * @babel/types: ^7.16.0 => 7.16.0
    * jest: ^27.3.1 => 27.3.1

### Additional context

Regular expressions like `\/` cause exceptions, and [here](https://codesandbox.io/s/pensive-night-y9nkp?file=/src/index.js) is an example in codesandbox.

**Comment by JLHwung** [comment]
```js
const ast = parse(`const regex = /\//i`);
```

is invalid because the `\/` is interpreted as escaped `/` in the string template, instead of `\` and `/` respectively. Since the regex contains unescaped `/`, it throws a syntax error.

You can escape `\` by `\\`:

```js
const ast = parse(`const regex = /\\//i`);
```

**Comment by Aarebecca** [comment]
> ```js
> const ast = parse(`const regex = /\//i`);
> ```
> 
> is invalid because the `\/` is interpreted as escaped `/` in the string template, instead of `\` and `/` respectively. Since the regex contains unescaped `/`, it throws a syntax error.
> 
> You can escape `\` by `\\`:
> 
> ```js
> const ast = parse(`const regex = /\\//i`);
> ```

Thanks! I guess I was careless.
