### ISSUE TITLE
[Bug]: replaced node still be traversed

### ISSUE THREAD

**Issue by LongJinCen** [babel/babel#13934]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
const parser = require("@babel/parser")
const generate = require("@babel/generator").default
const traverse = require("@babel/traverse").default

const {
  callExpression,
  identifier,
  stringLiteral,
} = require("@babel/types");

const code = `
  const value = 1
  const str = 'test1' + value + 'test2' + value + 'test3'
`

const ast = parser.parse(code)

traverse(ast, {
  StringLiteral(path) {

    console.log('this is a string value: ', path.node.value);

    // find the whole  'test1' + value + 'test2' + value + 'test3'  BinaryExpression
    const topBinaryExpressionPath = path.findParent(path => !path.parentPath.isBinaryExpression())

    const finalKey = 'testkey'
    const replaceNode = callExpression(
      identifier("$i18n"),
      [stringLiteral('testkey')]
    )

    topBinaryExpressionPath.replaceWith(replaceNode)
    // skip the new node traverse
    topBinaryExpressionPath.skip()
  }
})

const result = generate(ast)
console.log(result.code);
```

to reproduce, please clone this repo https://github.com/LongJinCen/babelTraverse

### Current and expected behavior

When traversing to a string, if the string satisfies some conditions and is in the context of BinaryExpression, the entire BinaryExpression will be replaced with a new node.

In my example, when traversing to `'test1'` for the first time, the entire node of `"'test1' + value +'test2' + value +'test3'"` will be replaced with `$i18n('somekey')`. So the subsequent `'test2'` and `'test3'` should not be traversed to。

I hope that after the node is replaced, the old node should no longer be traversed. How should I prevent the old node from continuing to be traversed

current output:
```javascript
this is a string value:  test1
this is a string value:  test2
this is a string value:  test3

'const value = 1; \n const str = $i18n("testkey");'
```

expected output:
```javascript
this is a string value:  test1

'const value = 1; \n const str = $i18n("testkey");'
```

### Environment

System:
- OS: macOS 11.5.2

Binaries:
- Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
- Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.2/bin/yarn
- npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm

npmPackages:
- @babel/generator: ^7.16.0 => 7.16.0
- @babel/parser: ^7.16.2 => 7.16.2
- @babel/traverse: ^7.16.0 => 7.16.0
- @babel/types: ^7.16.0 => 7.16.0

**Comment by JLHwung** [comment]
The behaviour is expected: Replacing a parent path or ancestral path does not skip current visiting node's siblings. It can't be handled by `@babel/traverse` because if we mark every to-be-replaced node and their children as should-be-skipped, the performance will be very slow.

For this reason we don't recommend using `replaceWith` on parentPath, ideally `replaceWith` should only be called on current visiting path or its children.

For your case, you can rewrite the visitor to hook on `BinaryExpression`, and then initiate a subtraverse to find StringLiteral, to determine if it should be replaced. When replacing happens on the `BinaryExpression` visitor, at this time its children are not yet queued for visit and thus the to-be-replaced children are automatically be skipped.

**Comment by LongJinCen** [comment]
> The behaviour is expected: Replacing a parent path or ancestral path does not skip current visiting node's siblings. It can't be handled by `@babel/traverse` because if we mark every to-be-replaced node and their children as should-be-skipped, the performance will be very slow.
> 
> For this reason we don't recommend using `replaceWith` on parentPath, ideally `replaceWith` should only be called on current visiting path or its children.
> 
> For your case, you can rewrite the visitor to hook on `BinaryExpression`, and then initiate a subtraverse to find StringLiteral, to determine if it should be replaced. When replacing happens on the `BinaryExpression` visitor, at this time its children are not yet queued for visit and thus the to-be-replaced children are automatically skipped.

Ok, I see. Thank you very much for your answer
