### ISSUE TITLE
[Bug]: babel transforms chained awaits (`await await`, etc) incorrectly

### ISSUE THREAD

**Issue by danieltroger** [babel/babel#13947]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
main();
f2();
let i = 0;
async function main() {
  await await null;
  console.log(i);
}

async function f2() {
  await null;
  i++;
}
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  "presets": ["@babel/preset-typescript", "@parcel/babel-preset-env"],
  "plugins": [
    ["@parcel/babel-plugin-transform-runtime"]
  ],
};
```

### Current and expected behavior

When executed untranspiled, the code logs `1` to the console. When executed after transpilation, the code logs `0` to the console.

[REPL Link](https://babeljs.io/repl/#?browsers=IE%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=PQKhCgAIUhhB7ADgTwE4EsDmALALpACgGMBKSAJgAYBGAFgFpFUBTAZ2YDtcAaSAMQCGRZgCN48ANa8AkhyIA6KBGiQAKtnStIreAFdUwyEXgATZpE2QANumEd2JyLo5nUkXNnMBZaauu3OdkgAMz0XCw53TyVIABlpWABRADkAZUSQ9CtzdEiPc1RxfBN0FiJceFRkSHhgqMsdfUNcFmZFaGBwcAA3ATdUZ1x0AFtzAF5CYOdy9HhIgmYAD0RK3FYyAG8oSAAiXSDWFttcHYBuLshIXrcAeURICZuRACtmcvkmeArcZERmc8u10g2AErBuAHdIo9EPIQWDIQAFQp_VA_AFXPpOFzMYK5ZgmU6QYDASBeSrmYzDJhsVjoETZKICSLdeDoRyUdoYtwAElSyGGYisD3cv2YtUgfIF8CFY1luymciGcx2kAA_BL-YLIAAuSAbAC-6KB6FwzFQAgqqElWomvM10vkJrNFsqkAAPm7dgABL1O82Ws7bIGg5ByaSm_2Va3S4V2qVWeQhsMRl1uD3er1Jojh50Bo2YiqpI4cTCqASYaMyyBxwXyQvF0vl92enY--sYEtlzCB7YKmZzSBmXEcZgEeAvXgSZjIXi9Ky6ZibbaXJ6vd5DvFIpBmn5jieQKczvXLy4Y-fMXVzhfcE-XTi6Ubm-kX9wDZg30-n4wcXGYfQCZ9dRaa9b0gcEMFwADsiAt8T31Eh0UuFhcH0SJx2eABtQ8AF10X1bYWmqLZP2JSBpAyAAOYFQUgARIBEQop0iVc3lweQNxHLcUR-Rl8DmKxqnBSoJC0AcABEbi8GoXlY1hOUuDjRwNXgdh2BDtn1IwLSIbBCDNVAl0_RThT7JUOD3Z5J2nWcBHPQzP0gZDUOkzCcOFK9_jgvCLhCaYzLA81EAIXIR1QPgOF4PQI3C3h2CsYJeEI2J4CIVhYk0XB7MuUjpDqKKzXCyBPm6Nl8Vo8J8rCjgPkKb5RQsLQ6IAcU4XNKkSzw0N0aLqs-Oq_giQ4mWEcUWtC1N5K5IravgMa2rcCZKsKgAyZaam6grepmn4BtyIa5DFOo5sjNx1SWyJdWO1NEKmzBWpO4UWPeIgWAtUc-tm-6Jo-nbFxuoFv1NRZ8AmEdwTgOYgdwAgkpStKMubSAMOw9ST1I9RzHkAB9XIWSnSBRg8UwsXQXE2CiHIqWyUYuAtWZ7BqOp8kgeQR2Bj9T1IutsEKcFeCZRx5Cc1BIkJ7BTDkk87vGy1sdxyRxgJgQp1kPHmC8ZgiZMYKOFCmLtGYeLeEBpZMvOE9hciaX5u8u9llWOTwIEe4JidxBzeyklVCqYAiG03TPCsFF3HgAnchGdAAC9zDMJAhmGKO6bmOTIAAJU11DGqMeAqc1-ntlIspKkcGx8ZN4G6yqRIuAwNgMPQbD5EpRBsjM-Q1A0LRcgjYIhApPQrBMAuSRBbpzBEZhOEIAWwJo6kSr0VgBLIMxaUwEdHAqdxlfMOiiCseBWH0cwt4n4eIjVxxwRNcXuto1A_xptZeBEO_cloqwhWZv32C0cEKT6LvMQd9_7n1sq9Ew1RR670iEsDKuRMAE01uLK-5hwRMnwFvP2n9Yqh3yCwAA5FoDgocRz4nPlg16ppaKQDBr5RU9MXKsXbgAdQAbAseVtNa0XQYJG-tFWBHwTiWChngkFa23lOLQSwhC4AEjUEc99H6cB4NoXIzQQT4BBIgP4DNT4n1gp7CIkBmBjyqFpdguCwIxzmAQrRAgx4hxDroHSFMlEPhUaJGS7wO7MHPvxaoAgTAlDMrZD-B8_b-RYAAR10KUMqlhv45xbnnAcRdUAmF4OCDQOlz5whoUNZ82htEwMcDoYE24pif2qKwW-g96IUk8M7JxtkIlvU5KZRhhFYD-wIMECKLl-YPyyq-IioFLZ6hFH8XUOwSGoGGLZHYQzMC6n6U3VpFlllkENHBLSuBXELFQAZY8DlHIZxFpM36MyPC8yWUo3U-lIA7M_PhS4-EgyYjGkWN6qR9i6LMCYb5qJhQ7CPqwf5-IgUnHzG4L5kFTS_PBZwAFABNdAhtHATFBX85F-I0UYsDICT5nBvmmkSIsN43UEEgqWJSoYJZCVTThW9BAudTSYt2M3Vu-IexGPTihEW1KPCWHQqxEIhRhhuJCptaiWhmasAEKMExwRghitBOfBizBlbUqiozNxJRwX-20NffZukhqmifpyIECAuC5AXKkFReIqwGg9kSEkYkHzDGqN-Q4Axyiuk6cnXi1inBBBoszJuydgL-rcALc-kb7DRtlj9eqnxuLoq0KENwga9GaLOQKyIV1LT-O8WsdufAA26E_toP4RBs5U3QMNd8kBkB6CVnw2pTjvy_mPi2vQqBz7CNJuitwJDMGhwWSWBkzMOCKvJuKfIQRcBCXof2ewHS_KMKLZUAgmxXmrv8tusKm65i7r1PunNkAj18BPRwLc_VRx7p8ujTuDUaErAEriatWbIAAFIcwnXvV8UUv6Qiuk4CVQoHAn5ys0efEwtj8CzqGGPeRR8dGrAsGxD5bgAOpiA79YULrtiKQIHhy0BHRS8D9KmSsvBL1nuIqeCZwrWB4VRkStwd1cBAceqW-Q3HKN_BuMEGFkBkh0zHuRyoQnFaCZmpAVakB5NfHgAQFTFQCAeVYAQZGJB9PolJoQCTKHmDSdQLJxTy1QImfQFJlMFHtr1QAIRyjuFZ0CcIITVWwVYAgtn7PzVk9RhzUZ7RWH0yczmXtX0QdKHMJ-sqaHIbs-Yf9oWLNOb-L-wk-wcj4D2qaIJaMSQLrER-5AX6EwnnM5ZiYAWzMZdk95HDV6XZXq-paG9DC5iyZqqpwjYwTxHv6w-vja42IvS1aaMjTWst_W2Ne29o3gMDQmEtnrd75volI01RAKkfVJsqHcjba7ZPqQUjiPEBBTtmWC5yqNfqAy8Fu_TC7HWZaVG62u9imgW4CGQBJpVExSPDc61929wWTztgQV2OjJ4diveVNsDjbrIAAAlDbBx_RxIVYjWam14NzXm_NwhC3OaLZBEs9X5HPuZiIPc-7GIjMMUSdQ6K0inZjHGHA1biJQRuzbg4rsjnMxrLWOmU1_BGRhWZps7k7BufAcECvLY7EblmxIQhsB9NvQQMWpgRmXeHO9ebvADeZIPfTAgfRMBG-YxT-ockedq311Ty3tv3svK908977y7YrFRHJTQSOoRW9PdLbrIyAaWmFL9cUkfnAPDlDsHNKolOJ5849lxloboTJjaBdUMbk_rfB8eoXHpQJGIrW4GdknzCh-zomp77U3ET0OCGv2HAq9o4Q2-rBngiASCw1oVmc7prblRMgSan5iCywNf9wH4_0wxrH6MMgsosWh52KBVZtl2B4VdUsQPZaFmoGHxMHN6nOBR6i5cIzBAnpsXYDx-bIn7dP_kC_2TInr8cG6y9mXt9ndvNj7ppIbEEExp-JntjFjB9FjFjMKKHs1qBKRpnolPAEWB2I2BWOFipNvmAVLDfs4CtoNpAJ_lNm9DdogD7hMpnofs-iSCwjfO_MzGIJAnqkyIEqwKGHWjmrwAAAYCDoImiQCLACH97mj2BZqjCbzwDnwCHIDor1IsDWwnSpyDAjBtDCGBQECLAkACFWIeAWhuIDC2pKpd7uBsC4AKFeaQjrKfxaa2TXi7AIHCECAmhqQSFbxmAs54gWBMxiJKEYplQeQNSDpapcBOITw8IeHsqcjH4OyJhuwmR66e5375rOQbCQBuEiG4C6i25PIMG9i3qQAACCPByY80f-80vAW4Cc7A0gVMIyl68sU4buWsyyvALAOgVgY83RzAE29uQI6SHK3SvSahqYGEFu2EvAkxloWyN09-dQBAoxdY9Um-uwSuKu9uSEgxrEqxbwxciYwySxTyJiVgkBPeIxbAVaIMZyxgGSJxmAZxnGZ4C4woPRdx8gHkrxARhAYRq0Pen48edQYRmxOwoq5Q6e1mpypydhPmGyHkKkuRcRakuxDuBakA9RmgZmVM5OvRY8Th54sB7hJoJA3MnAuum2xJC4GJn4bRo4cuwMdyyJZyhJzaLAQxfxby9Geu-k9Jp4jJBAiuPMyudy-kAxHJAx3JwJvufx_ucJEyOJjR-JPR0oRJHkFJ-Q5kV-zgbsfwJggppELCnUNCwRg8ZUKpOQWg6pfR-IIWmauQYSYRE8lIbAcppEEaYRZW5g1pAAPBsMiQhiOPqAAHzsl3Fga17RBwnRZGD6AsBRE0ZtxylfFWBsTglYgGn4g8nskamjjplmw976h8k0n6SVDGkki5Q0JcmsRWkSq4mzxaAWkAodS8ymH7Frr0RCASCekkjdx4JiJZjKZl7h6RDlKiGWExEgguDZCbyeAsAz4OQTLCmim3K8AVmoBSkFkymsQ-7e5nH7pvI-RvHzyzD7DWmuqXCXqcCxLMALgdEoJbIZE3mlG-aqwKzMEeDi4oJlEuBlEPyMY94TJ0LWlNEtzUlrqHHSlnJDGvkOTCkW5dH5n2l7nlAHmnjwRHmnmYnOTnmLzWkPA945R1B3kLgfH5ITxTy-ZlQTxZrNo6khroJRFbx5FYhDBWAkUkitLTSmIXlaDWlaDQINJTx2ljyOD0XkhaSfzUqMkcynKkTlLGH4BFmNQsAfy8JaBmA2BmIJJ5BiKPFlB8QZJmjty5TcUmIcD3mUU0RjqiWRC0WSU4jkgdRTyiGWAjAn4YIhyWW-YXwKwWDDCyGNqmgCRZI3y6p5E6qRB7ytIiC9lOK4gsAKUORKVDkmHMwjnzGVpC75LMxIAn7OAmjVA-HyFxmkRcG0JvA0h9A1IZz3Dvx0TUglDlBQRoIA7tzqCWAtXHAARZAlWWWWDZKlViJEWHYt5uCVE6RQaLzyKMldxrCWW0pEDdSui-YJVD6k5XzYDcG8HjlaDTVikkL7ACTLUUqrXULGBmANIMVuLJUd5klsQSjqJoKUwpKJa0i5yWUjk5pdx5Bmis6cHTWjmfaoCsAhZvpsC1qNrVJDVUirA-VbzcZO6ORYB4CbmcJRB6A4BYZnKxLxJaB-xLk94EWXmNlBDqhk2sDWmUnmRykfm85fk3y_mmD_kmCAWYCpWKUkhlEshsgT6IDlh0wlghAeHzg9FOJCWZEix0XVBWBvQDpxlGLyyRL0xs5SoZbLmfiM1qzfnYCs0c0AUPw95kC6i63M0_nu7s2c27o3SKlGJiQi4nxiLFVkyOCBzBwW7BqWB5ZyFBUfUqIsxsw8AlYszbHbUswTIEDsAxzO1i7u7rCTSsZyxM34wTDkUPmeQnkkbx0ZaG06YVG8HmakGijvakZF1VEnSl1_D8zTXmZ0bjmEAjIsadzsboiJFB7yCV3ZgZbCg93mauqkTJBfAu0mFfUpICL7V_X3zvXUwqJlQDgVD3C1DnwD191QlrCEj5DVDPD7CqWO50REU_rMw-nBCiLmDDhhJFkT4mAuJy2a3zQJH2xd0jmX567SpVSRQbRf0GxGyjLJSpTpSHB1EU14ktwjIP7gVUwl5XCsjshkDQMtzChXm4XGgRjCh0Lr3VGgRuw6x6wDLnSxSGwJQANwzAOZTc3YlgMQVcWfio57FYmd1loh5AF67nQkCF5YZmho41nnRvp0Q5Xbky0GWX1VpCgpmVDLm6h-gE7Ay7p01QVmQwV3GCkTJFnsRzDmDqgaNhEyMRhyPQyYVvJ-6uqXoLIqxp3qzu74ObTEP_3lyZQZFAjmqKzMoIo4rYiAqQSojXkiNN1IXu4vlQFCkrGuOwPuPMDkp0oIIYnbHVXgyJBHI7qI5jmWDgJaocFmEcAIJqQ4WgQP7hObGROsopLsoYkP7e0QnbFqQIUglingy24Km4UkQkgABCl9lQmAdmCCvAwc5AAArPIAAMwjNjPDM05iJIpEDaiWV4C4CICsDajEh_BIDZDyDDDwCRxZAK3yBdPAAAB-zw5ILglQKqwAbAAAbPQCYOaMEGxHgMMFYAAMTsBED0BCNfGjAgWO4hnMDpxHwZl22gQO1fiQymwbPu7CgW5nGOPPHChNMtNgQaAMgwxvgYlAg6XMCYBvTChwtYs4umh_EP4EtvSCmYuGzYtvQAtRkTALLIATyflThO3ZCEujikumjGzgvAzGOhOEAcv_O3EZmCnLH8uUtss0sZmwM2r0r2qOojgRZN6yvZ3K2MPOQCuSu4B5nHkOSgsMkrFwtVMp4h21MhM80Siaz0qIJwtYzsBRE_qstCA1K6AYbArihtMASGxEL9njlf5B1eXz20ypmqtwt2v3E2tht4vctsSIslkXFBAP6GtQvVMNOmtymFPwrjByiROIoQreN9BONmtwlFMfakrMClPcoEhymXDxNwuIuqt6sOT4t_b-zkrCCIDKN1unFItvLxs5AGvRuQsSIQlq6Cl1sMQuvQw7Bq5ctcAQue7NM94luRPROXUIJ-Ofg3GPFjFVA9Kmq2O_1xSkOOO8sP5rGDbGuVALJWBpuqukXlQmKLDtv-SJINORDBASoRAENZLmDZAOLmBFOyg-srsXVUqi0zwHxIA9lD7RnlRfCLkBVq1zDa2nglv4taPVtqiluZsVuazkKquXCXQkqZu5u4omD4qDwbuIUrFrGFGbEyt2rMAOq2oKsitKuMfas9t4UXJFunIeS6i0cPxUOnJ_Pm2Dt_Nyk7JxsQH9uEDnsbEp41OCnLvEcsrJKVt5mkRiQtumpuJLDPuMIiDy3iCIDUqbXD59BhD-2053skjNuGqmptvMAdvW5dt24yVCgATwBjwoeXBJvDtbGpt5luefFHFPH1twk6snkvItZGI9LVoCuOgZYYT-coLYTECDvpEzyzkmDTqxlo5Fmbk3w8NGciPUp0TZFsl_PnE30fs5wUzwbiu4uSPCOuilebMlDBBKGi2pfEwzxuccxKWWvUr4tNfUJbwcDiOR2Wx47mAMeTdMfyuGyC7dn0uMtWMstUszYCuztQzR6YhVPC6OumhJfzQpeDszE3SVPJtyjOCKRGkIWkRlHh0NM1BuDk5YnZJTzMwCvcMPT5IkIve8ygSkTe22RaVWHzLOmmiwbmCtkwCQcwigSjfHeKyTefxUeJsXc3dYpKd1No4j2mi6iy5q7YQEz70NKhplQ_qJCpATNC3g0jfJJ0wiADU_AocktjdtAtck8U7q5VlkSBFx2o9_ephJZ0QTLIXKapZ40CA-s6RNpdp_uRAuu-dKsQuHfTt8_BeZcPzCh3fO1VuqtrdmYbdc8EA7fq88tUf6uEC9eYqKeptsf3sm9MvMCbdssZdzs8tGCzl3SOD2_io5yYekRa8Foqhbzrnim8CtzBref6SlRuKqCihJOFBuATwHzghq9qsXLzdysseGycdxmNt-fY8BdR8q5_EhegzMDgzJ9_Cp87pyk7AYyi-x4Ibkz2XFSJ90R2INMEL86mB5MgtIsTJ5-LcF9WD21oOYijFx67u9JS-Jcte7fzvdsnhnthcmDrFraO-3L26B-49BfI-6-IITCCcvEn_e9sS_egziNnFj-QyMfMf0qF9wQz9uC5ChChfbvPF-MP7OYIgoQA_mXxQQgoamsLU_pg1r5qAU-yTVACKRa6RkpWlgeykyCYTQlMKKPLbmj3v7jJHc4_F_k6mn4b8ViX_eAJoxHD24nugiLAKI2QF8QhemQHJrUjKi_ct4zMC1IHjqog8SQ1wRtEUmmbDoH6iXIskDnMAx1J4R3HARRyNLLlHGGEUQUK1wDiCyeEwcgT8WcKeReBacW4kqhWpUoBwmVMRKvHiQlwUoSceYLHWkFstZBFJK_lDEMbChEuIdQBlR3vaB90EWgCviqFfiYITBXPaiHOTKg2c0qJIfTs5zMgx9uEBVH-qDXmgT5hAZUOZNewEjmVz65rTwTRGZInB6MXTbhCF05yGBRCVFSeN3nNY7AfUHiEwL4NGrC8cBbfKRoLyt5sRvaXgnQWH1Qh3JWkyuNxJUCwDOkhQH3ZyP5SwRP8FuzOfLq03WgYMhGy5LHtfyHZgDXMWKUdvj0P67ATWVfKARMAN4m4jeurXCuAUuLmAi2pEdOPQFbKdlAWB9AtA_R-6BCLcy5Vcj-HgAkDphrfX7kgMsDDhNAngS3OUizQo1RC_XcYR8RNTYAw6sQ2YWXkmjYC2WmDPAZ-Ef4sd8-r_KfhpEYKQAnaJuD7E_SlxtANgIdbgBHUtiaRWCgNDWqENIhu10UgsF3IFU9o8MnhudE3AnQlzUFUcu2fbCHCwKw5ywjdVJmDWH5r08RD0WpAPEcDg8ActpR3CaCPYCJH6D0Tesi2-75dSIPoJAa0SJqtJF6kQE0O3FSA5xx4vMdgODQH4BtmAT8SwVSPVEDk-6BI33h4X1FyBKgxlearnESysZjYAgfYLNzFGpgS0E2JxPZRiKWxqen7VjB5y6qxZ7Ax8WDCYQ76sAOAdiaiDok4CchSIDqcwPM0WbLNgA3TDwLoBECRphgwAXuMIDECSBgAqhMvMAE0BHw2AwAcgAAHZaAsHTZhpV8Li1JYxua7HthCzzRG6V-Fuo7lYzt0fI3IlSDDgZRlloKo4rEjsAwgqij02ERlNhR8iXpEA-wbAN7GQDVxCIBACJOsGcaYgVE5iCYNkVhgzNrAcMDCJQDJ5SdbeBAagMYmPH25zx0-SJDpEAbChjxGEagLhHf6kDCA5AN8XDA_E1xp8V9apL-ImD_jyAQE05J-MTD3MzQcE28alAwjDMkJWFXCinUIgHja4ckbcbUgWBQS_cm40oj0U1h7iiJyAciYRH279At-woFCVylSSRB0wxGZEVvx36KxZkV7RZDdCxbUIL-N0diep04k_9i4sXJujK1NhotkAgDeGIcBGQvoCgRQKyoRAwH4AFgKqViKlnkR0QdJrjRLBCN1RxVTUYdV0HRBgnyJ6QKUCQGQG6ZjwtA-wd9ArWaChxDg0lbTFEF5jvsJUYdNpGZD_iLkXaZoG0rQlDicB94h8IVOYjMkqJk6ncSuPuJrgZphQGEK8VUEAYzJCgXwFUPqFwk1s8p5DDKPIE1za4CApE3cVXCgkdRNAPuFOjROhjAQFsOdAPEkUPBaB36NJTesxIPDTg-pSMUqbBycJuBDwxiQaQhV6kfAdxBAQ8IQU_DzSWAZidgMCzDqpwLQCHYwpEBm7gc0IpaMCPwjogh1B-luf-MNOc5QiNAJYQ6paPKiOBW65gC6a0TWAkNJoEyS9CHWAqnJskWQCQfNOyAlgPAGLTENNImDzSVgQUU9isWmnvxZpvHU8CHU0HnhhQh4PMmjOq6X598KrOMqBVNjNNTkjbdGKHAcTwMjAVCcrrFWCQmh6YYSTej-0gB70O8fvNxOjIXA6CZ4lA8wGmh3BZTagTA96aURVHyivpHcTQDzMuKxS4xktFSm4iHRkw3A18atGgJIQcB-QUcSKb61Ag4ytG8_BcA_0dwh17axRN8kLm0zBQUwz4SBmQNtnZBhimIFrobWFA0Znw9cDLJWHGmisbZ80Q2hiVXL513cDhPzB7Kdn5NTkD-UEqL2fBOCISaeIOXKMdkEy8JBTFYs5k0ASZkg_sp8Os1BmYBwZEMz_sKHoDUBeAF0_qd2T-mClAZqLAANQNz0AkAf0nHILmcAi52ANjg_gRJhy857VajJFhRmnI0ZWZCOcwHri-zlaBsxRHjJOF5leJWJM2Zhyi6HC5SY8rQfr2xD7DsZELXGa-GNlccc-kQFecXxt7-M0ZVc6qsDBwovJcK5ww-vqL7oQiYp7xNgN9MdzZEQ6uoP5pqyKKYjupXdfyRMG0xmNSif85Qf9O46RBKuWg3UHsLxCW5ROh88wM8ieQ-QFJFcR0ZeJPATUc8lQXUFgtDoWw2AmsVZHrlYASB0AiAVQFaMQAAtNY9uFOvPGFCUAziKda-ewp0GMLcAVrFodjEjYOsqWRAZ1q60YGQAPWGfb1uaxzR-tkynolRJYOXIp1I2EwFOrayDq7Cd5SCjhWlIPm9wF5oEFOrf1oR4DjFaUzXlsIsWaB4W2i-7lRwIkNSjgH86qTpBgq0TnFVQBhnywIDOYqFNCuhVSF4UYkf0k02hOPlYKdwBehPbQL2i853wCqLna9m91cCTMyFTeEJOrVmaqsH8s6UYE3BBCoAyi0MSgBvkU4wlMOlwPub5hhidxK5c6MgECQI6ngs5rAHOQQAbn5K2gS8AIC-P0xsdWMGEbpWoKxAOLJOJZEfi8hvAnhfJiAChTSWYX6LDZ6it8FRxGJFB6JceNKYRMyl1wHxZxDZV8HTjbtPimyqCaWLKb0wziZ7IoCcuOIXsj--_fHvE0Km4B7l4XB-FHJXJji0pqAOcPbRmVGQdOOkJzi5zmALLoKEQ8FRwHtwxzllVAl5a92hVmRvlm7TEI422WaAzil6HLtkCPEpQfRugHAIWx-a_8yCPgv4hfzYlPtIh1ynvHC2vkRIL5ibX0SSoF41kfuIK_4Y-wM4DgvBWkYlXgHoiBI9kriRyVtR9ZMVY-is78bpAlXD48VuslFYwhSGtJp8DNUAcTCxTWKQ2OwsZYb0XaEzHczmQAX7CFVasR-oEMJcaCxVyRdlLiuSIXI8CQB6AkAagISBblhkJg7C11fQHQAlztJF4p3OlKIkZop5fxLdsXDYkXKOJqKrjg_hQnXjYG07IoLe2VqkQwV_kbYl1DWCJ9xQVVHSQquDTGAq0HtAWNkB9YmgrEL-NxHGsYRn09OtqDSpegqBSrXuzMFVchzTKO4lVIpZFMP2L4JqViSa8qXWn9LqK0p88clpiDhB7tXEEwGpRsk_EHZ_YgDQdcrSBBwg-Agw-RIutBDeZ-5K6-ULuuUkpQRRuSlYnOqNRKZt1p6nuSsRYXrTW5Qar8WupShscT5QQ3LqOHYnvqiAiUdFovPOIyd_idS2xawrbkoT7JZ60gPj1OQTI-10G09YA15b3zJOfbMDdetNQPrCAT60xC-r_WmpUN8Gn5ViSQ2xr_1gGuksBpL5YVMNvc0EDutnTVJcN4Gkic-qg0XKYNJGkeWRucgUbCIVUlDR-to3HyQNJw0jTW1e50JG-CAxXElMzbmTIqd8OVW92YHqqN1Q67TYcOmW4UAIAwDtpCuUa_Rgm1q10OEpbmTrbFDq4ifIGdW6Q3VHqiwJAG9WQBfV9Af1YGs_F2rQ1ey1gBGp7yJqLlyaidSGtYXNKCOS6xwsetTwiaiAtTSLaq3w3dBCN3G-LTOuzSnqtlGdKCXmU1TKwSZ686OSsRg1bKktcJGGApyxQFaJAKoSvAR0eUPZURzARLbCWVplaQtY61uRMEKIVbTkhRMLZ1qE08aP1-PHKOvGkrMwYNr6_4oDEKASNiEXwVmQ-FM6i0t4cvCqiSFCmMIootIG6pwJ9hqaFVKHYbcGvR4YjSZSLKNRkhMjZaoJWHM7V-Kkn-RdQPEn5eSo2JTI05exX_nRyUSY9St92piUitsVWL5cfxThabDu0saBI9E4TbDtg1UqCBYIifuiLRUwKQ1cawslvzAJAqwWbKF8FflGL8w0JqAXjRnLk58SmtPguJq93ElWqStVOz7bvxq2vQ6tzYHtSzqzZYpAYjHdNacih3AwZJnyy_qTIY00dqd1W3YGsJRmtS5wvm_7QzrjIp1NeauSHWlOvk7AB1R5CXczoeXS7BJ8yRZFZlohk6KdKuzXdDt63m6UoGOr9YQKW6XasK-Om8uHFqTGbrco2uDUWxtUuzfNtmjNPZs7kuqnNnq1zT6sJCeaA1-PIED5us32qvF4ahuMSxHXpbEdcEuUN7sFIp1sdjEqoJctbj0xNyFygQLbtIB5k2pdEqCfnuQBob_GjuyfkVvvl6aEccqnYJ7tPTXj7cfu0uQnr82Org9YMxze6vD1uaPNXm2PWeIe397A9dcFPUFrT1Cbk1mxbvaRpu0cpJJbKelZev11PEadePPjW8RzUi7t-EXVVlXq8UMTPx9eteUvOcg5rm96c81q3zhZqbvawwCngEkp5OVTpLquiDtrmA8yH4HiVinmiMrQ05gJgOVBTIPAkJIQYq-VREgkAqKZNMAuTYgM_hUshQami0FwJOB47cKArWQZ3vMgTypSdxcQZXNNgW6HIJiwIbgrjItdLwWgnTBPJIDCcGB4ggTsoKoM95XBKUXUAIaIAgtAdeGyxTj02Hy4MSWnQ2HSFzCGxqgQImIWIgVod5I2YRZSnmmukhk7EP1IgEQFKi0xqkRUUEItQUROIHhqPFDinX-2IKN49uhvajqIEKtp-byIeiSHTg4sMk2QQRHqi-74JUarAF6DQoKzSJQO_CmiHRFZSbMOAAAKVSAExTAVaPxEYldBjoBiWJZmGYXjjmAVRWhkwtdMsJmB94gCNxPwParnxaxYNDQuYRyD0DKo2gYwLXWRa2BdIPQ8ELBksAdcUj0RVI2jlyATYyoWqWkA5OqACFWeHAGsdizHLR65A84MwPQByNaEmjGADtvIGeCsABCnICZMwzYxdB9QBAOnIEQaAhGO2UNCI-VyzgxG5gCRpI3fWyC8A8s9xlI_ID2NgJYeZyIRrUdyMRLRghqYQO3BuD4Jr4QQSgtQnOkwD6FPwIMcwkgCJBiuqsgHG5QYE6oTpasoUDET9pOJw4QwWyDrIvpfGy8PxlYxUaKTGCT4UHMrD8KBmchY5PRhkBCU3oqh1QDJtoHsZ1DnpwABmLoDpKYzVH5oJJ4HI5E0KjBzgmkNTTbgMNGHIIVgPkeUDJBmB7IL6bo8kYZASiy1MU_AGGOcA5NRa78X1McHuPNotDQCePh8bXjQYg6Gp-pNKOQB_xhIWIXw4dWNHCp9TWgBot2iwDHxt-kAOI_vXPjvwf4BQUU20E2O0RpTZgYw_IjML_VtARwcoMaeoyixTAZoWBCWDxCsBz4RR9AcfhsCGG5EgSAwzSGUwHwEqVgbqinFkA1BLSbgTuZmc7y5ngjzsfo0pQTP4AOu5gP0eB1LPjgwkwBRhL5hjGWBS19Sb8MIDsxQQlD4tQM-zghhzsoiDqVahBGqAIhpQtgJQ5UFZ7QHQ01KAc3MBfhvwDKJhYM4SYFlTVpQhg_UTAcyCLA3EQgQw1GdlPxmMAiZzsxPmfDDB0h58VtLoAISOJPTcwHtCwEcC_n0-d3bILXlDhZpDAhpt86meem0QdENgMqJtrRywBUgCIJKluYFr7mBkM8X8wQg0r2UMTQqaC-gDvPMBETkzQ-K2ZJCfBPzENIqH-yCDdisgfafQCTHvJ8VWqc6ZMrFSvQmh0cxYhqI2M5AxzRQCeMs7ZErMprmTIyTANJYrN_KZjNR0M58VDN4RMNITPCyKVQCq5VLgp9S-fzUirFQzlE95OAAWS5BgWwQcgMC1j5Wb3N5wX6qUWsvmR7IT1WIqIQu3ogfU0oNoAfEwDBR1I7yVy0LjsvQKvLvl7YOgCbnimgAA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.16.3&externalPlugins=&assumptions=%7B%7D)

The issue is this section in the output code:
```
while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.next = 2;
            return null;

          case 2:
            console.log(i);

          case 3:
          case "end":
            return _context.stop();
        }
      }
```

### Environment

- Babel 7.16.0
- Node 17.0.1
- Yarn 3.1.0
- MacOS 10.15.7 (19H1419)

### Possible solution

It should be transformed like SWC does [repl](https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA8tNzMzT0LTmSjMCkTmpJQqZCrYKBtZcicWVeckKaaV5ySWZ%2BXkKuWB1CtVcCgqJ5YmZJVAyrzQnxxoolpyfV5yfk6qXk5%2BukQk0qJYL3QCQBUjaYRoztbWBqgEuhfGDhgAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSw7DIAwF7%2BI122bBHXoIizoRFT%2FZjhSEuHshQerOfm88bvAVB7ZBQRbiOUlNihdYIBdRHPuiYAY2IuWTugFFPkgnIa9RhZyFntJA9MnvdXpcjoVJBOyOQWaF6Qi01j48MX%2FOGTTQWuj2bdD%2FjnXn5b3A%2B%2F8Pdg70ULMAAAA%3D)

```
while(1)switch(_ctx.prev = _ctx.next){
                case 0:
                    _ctx.next = 2;
                    return null;
                case 2:
                    _ctx.next = 4;
                    return _ctx.sent;
                case 4:
                    console.log(i);
                case 5:
                case "end":
                    return _ctx.stop();
            }
```

**Comment by nicolo-ribaudo** [comment]
This bug also happens without regenerator: we transform `await await null` to `yield null`.
