### ISSUE TITLE
Recent versions are not published in NPM registry

### ISSUE THREAD

**Issue by vhenzl** [babel/babel#13950]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

N/A

### Current and expected behavior

The last published version of all Babel packages on NPM is 7.16.0. There are three consequent tags in this repository (v7.16.1, v7.16.2 and v7.16.3) that are not available in the registry.

### Environment

N/A

**Comment by vhenzl** [comment]
I'm stupid. I didn't realise that only changed packages are published with a new version therefore there isn't any `@babel/core` or `@babel/preset-env` in version `7.16.3`. Sorry for the noise.

**Comment by nicolo-ribaudo** [comment]
Yeah sorry this can be confusing! We have 100+ packages, and we found that publishing all of them every time often causes problems.
