### ISSUE TITLE
[Bug]: DirectiveLiterals seem to "over-escape" when generated from a parse

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#13953]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
const { parse } require("@babel/parser");

[
    parse(`"\\t hi"`).program.directive[0].value,
    parse(`;"\\t hi"`).program.body[1].expression.value]
]
```

Outputs: 
```javascript
["\\t hi", "\t hi"]
```

### Current and expected behavior

Current behavior: this above code outputs `["\\t hi", "\t hi"]`
Expected behavior: I would expect it to output `["\t hi", "\t hi"]`

Perhaps the spec defines directives to parse differently, but this seems off to me. Especially considering that when doing `DirectiveLiteral("\t hi")`, then value is "\t hi" (matching the behavior from StringLiterals). As such, this seems to be happening during the parse, and not the AST node creation.

### Environment

RunKit Notebook: https://runkit.com/tolmasky/directive-literals-too-many-slashes

- Node 14.7.6
- @babel/parser v7.16.3

### Possible solution

I haven't looked at the code yet, but I imagine doing whatever strings do when they parse. Again, if this is spec defined then happy to retract this bug.

### Additional context

We convert the last directive in the directive prologue into a string literal (by appending a statement manually), since REPLs have the expectation that *something* should be "returned" after every line. So, if you type:

```javascript
"use strict";
"pizza";
```

Technically this code has not expressions, since all the strings count as directives. However, the user would expect to see "pizza" returned. This matches eval behavior:

```javascript
eval(`"use strict";
"pizza";`)
```

The above returns "pizza".

Anyways, we do something like the following to accomplish this:

```javascript
if (program.directives.length > 0)
     program.body = program
        .directives
        .slice(-1)
        .map(({ value }) =>
            t.ExpressionStatement(
                t.StringLiteral(value.value)))
        .concat(body);
```

Unfortunately, this generated the wrong result if there are any escape sequences. I've looked at trying to use the contents of `extra.raw` and `extra.rawValue`, but those aren't super helpful either, unless you just *re-parse* `extra.raw`, which seems like overkill. `JSON.parse(extra.rawValue)` almost works, but fails on cases like this:

```javascript
"abc \
hi"
```

**Comment by tolmasky** [comment]
So the line in questions seems to be the following, in `stmtToDirective`:

https://github.com/babel/babel/blob/d5ba35586754da12ae406f6012b24d7f02ac17a6/packages/babel-parser/src/parser/statement.js#L162

Here, Babel is performing the inverse operation that I will eventually perform, turning a StringLiteral into a DirectiveLiteral. Except, instead of keeping the existing `value` from StringLiteral, it is explicitly choosing to set the value to the `raw` value minus the surrounding quotes, leaving the double-escaping. Is there a specific reason for this? I think just removing this "custom" value extrapolation would make this behave the way I originally expected it to.

Interestingly, the `estree` version of this code does precisely that, and thus has the "correct" (in my interpretation) behavior:

https://github.com/babel/babel/blob/2e2d202694df8ec485ac2bae79e5258b9e552fd9/packages/babel-parser/src/plugins/estree.js#L80

**Comment by JLHwung** [comment]
> It is explicitly choosing to set the value to the raw value minus the surrounding quotes, leaving the double-escaping. Is there a specific reason for this?

Yes, because
```
"us\u0065 strict";
```
should not be interpreted as a `"use strict"` directive. The spec requires a directive to be an [exact codepoint sequence](https://tc39.es/ecma262/#sec-directive-prologues-and-the-use-strict-directive), so we preserve the escape in its `value`, while the `value` of a StringLiteral corresponds to [SV](https://tc39.es/ecma262/#sec-static-semantics-sv) (the unescaped text) in the spec.

**Comment by tolmasky** [comment]
Ah, I see, I was interpreting that to mean to that you should be comparing the raw value (as in, doing .rawValue === ...). Makes sense. In that case is there a simple way to go from raw to "normal" value? JSON.parse is insufficient since JSON.parse does not allow for newlines in strings.

**Comment by tolmasky** [comment]
This is kine or tricky because the `StringLiteral` to `DirectiveLiteral` transformation drops the `value` information, the original generation of which seems non-trivial, requiring taking the `rawValue` and rerunning it through `Tokenizer.readString` (and thus `Tokenizer.readEscapedChar`) to replicate. It's a shame because this work *has* already been done, only to then be undone later. If there was a something like `unrawValue` or `stringValue` attached to the `extra` object of DirectiveLiteral then this would be very simple.

**Comment by tolmasky** [comment]
One additional point, the spec seems to only refer to escape sequences with respect to the `UseStrictDirective`, and not all directives. As far as I can tell, this restriction is only for "use strict", and left open to individual implementers for custom directives. I think this is a pretty good reason to have something like `stringValue` in the `DirectiveLiteral`'s `extra` object. Would there be opposition to adding this?

**Comment by JLHwung** [comment]
> left open to individual implementers for custom directives

Yes. Though the spec also mentions that

> If an appropriate notification mechanism exists, an implementation should issue a warning if it encounters in a Directive Prologue an ExpressionStatement that is not a Use Strict Directive and which does not have a meaning defined by the implementation.

so custom directives are in a limbo.

> extra.stringValue

That looks good to me, essentially moving https://github.com/babel/babel/blob/54c539ecc12a70706e642ef9354b2ece6360444a/packages/babel-parser/src/plugins/estree.js#L140 to the base parser. Do you want to open a PR?

**Comment by tolmasky** [comment]
Yup, will do, thanks!
