### ISSUE TITLE
[Bug]: Error after add @babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by dubyouth** [babel/babel#13963]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

./node_modules/@jclem/logfmt2/dist/logger.js
SyntaxError: /Users/bristan/gmlverse/node_modules/@jclem/logfmt2/dist/logger.js: Support for the experimental syntax 'classProperties' isn't currently enabled (9:12):

   7 |  */
   8 | class Logger {
>  9 |     context;
     |            ^
  10 |     timers = {};
  11 |     stream;
  12 |     constructor({ stream, context } = {}) {

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.

### Configuration file name

.babelrc, package.json

### Configuration package.json

{
  "name": "gmlverse",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "3box": "^1.19.1",
    "3box-profile-edit-react": "^0.0.9",
    "@ant-design/icons": "^4.5.0",
    "@babel/plugin-proposal-class-properties": "^7.16.0",
    "@babel/preset-env": "^7.16.0",
    "@fractalsoftware/random-avatar-generator": "^1.0.5",
    "@portis/web3": "^3.0.3",
    "@self.id/3box-legacy": "^0.1.0",
    "@self.id/core": "^0.1.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@walletconnect/web3-provider": "^1.3.4",
    "antd": "^4.11.2",
    "authereum": "^0.1.0",
    "axios": "^0.21.1",
    "fortmatic": "^2.2.1",
    "ipfs-http-client": "^49.0.4",
    "moment": "^2.29.1",
    "react": "^17.0.2",
    "react-alice-carousel": "^2.4.0",
    "react-dom": "^17.0.2",
    "react-dropzone": "^11.3.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-slick": "^0.28.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "slick-carousel": "^1.8.1",
    "web-vitals": "^1.0.1",
    "web3": "^1.3.3",
    "web3modal": "^1.9.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/cli": "^7.16.0",
    "@babel/core": "^7.16.0"
  }
}

### Current and expected behavior

Error after add @babel/plugin-proposal-class-properties

### Environment

System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.16.0 => 7.16.0 
    @babel/core: ^7.16.0 => 7.16.0 
    @babel/plugin-proposal-class-properties: ^7.16.0 => 7.16.0 
    @babel/preset-env: ^7.16.0 => 7.16.0

**Comment by JLHwung** [comment]
What is the version of `@babel/parser` used by `react-scripts`? I suspect it is out-of-date. You can try remove the lock file and install again.

**Comment by dubyouth** [comment]
> What is the version of `@babel/parser` used by `react-scripts`? I suspect it is out-of-date. You can try remove the lock file and install again. I've tried it but still not able to run 

babel/parser@7.16.3

**Comment by JLHwung** [comment]
Since `@babel/parser` 7.14.0, `classProperties` are no more experimental so the error you posted almost surely comes from an old version of `@babel/parser`.

Can you post the result of
```
npm ls @babel/parser
```
or
```
yarn list @babel/parser
```
(depends on your package manager)

If all points to 7.16.3, can you provide a reproduction repo? If some points to an older version, you can see why an older version was used.
