### ISSUE TITLE
[Bug]: Failed to parse json

### ISSUE THREAD

**Issue by fengzilong** [babel/babel#13974]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

https://babeljs.io/repl#?browsers=Chrome%20since%2010&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=N4IgZg9hIFwAQgEYEMBOIC-Q&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=true&sourceType=module&lineWrap=false&presets=react%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D

#### Current

Missing semicolon. (1:6)

```
> 1 | {"foo": "bar"}
    |       ^
```

#### Expectation

No error is thrown

### Environment

```
Babel:
  @babel/core@7.16.0
System:
  OS: macOS Mojave 10.14.5
Binaries:
  Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
  Yarn: 1.22.0 - /opt/yarn-v1.22.0/bin/yarn
  npm: 7.24.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
Monorepo:
  No
```

### Possible solution

Haven't dig into it yet

### Additional context

I'm not sure if this is by design or not, IMO JSON is also valid js code

**Comment by nicolo-ribaudo** [comment]
JSON code is only valid JavaScript code when it's in am expression position: you can make it work by wrapping it in parentheses.

**Comment by fengzilong** [comment]
I think you are right, thanks for the workaround tip and quick reply 🚀
