### ISSUE TITLE
[Bug]: 'Attempted import error' when importing a re-exported TS type (possible regression?)

### ISSUE THREAD

**Issue by rally25rs** [babel/babel#13972]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

I reacted a minimal example using Create React App's `--template typescript` here:
https://github.com/rally25rs/cra-ts-test

If you clone the above repo and run `yarn install` and `yarn start` you will receive the error
```
Failed to compile

./src/App.tsx
Attempted import error: 'ButtonProps' is not exported from './button'.
```

### Configuration

The config comes from create-react-app

### Current and expected behavior

Attempting to import  a re-exported TS type fails.
Expect the import to work (or more accurately, to have been removed when transpiling TS to JS).

This seems very similar to #10156 possibly a regression?

### Environment

Fresh `create-react-app` environment.

* @babel/core@7.12.17

  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm

**Comment by nicolo-ribaudo** [comment]
Since Babel matches the TypeScript `--isolatedModules` behaviour (because it doesn't perform cross-file analysis) you must mark the import as type-only: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Comment by rally25rs** [comment]
> mark the import as type-only

Ah ok, I was going to come back and ask why the difference between `tsc`, but it looks like `tsc` has the same issue

```
$ yarn run tsc
yarn run v1.22.5
$ /Users/jvalore/Projects/cra-ts-test/node_modules/.bin/tsc
src/App.tsx:3:10 - error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

3 export { ButtonProps };
           ~~~~~~~~~~~
```

It's unfortunate that both VSCode and eslint don't report that error in the IDE and led me to thinking that the code was fine. In my actual project I even have a fully working unit test that runs with `ts-jest` (which uses tsc) without an error, but it must be using slightly differenet config or not actually covering the file with the invalid export, or something.

My fault. I appreciate the help!
