### ISSUE TITLE
Why babel can parse `(x=1)=y;` ?

### ISSUE THREAD

**Issue by msmhrt** [babel/babel#1397]
Hi all,

Please see the following log.

```
$ babel --version
5.1.13
$ echo "let x = (y) => { let z; return (z=1)=y; };" | babel
"use strict";

var x = function x(y) {
  var _temp, _temp2;

  var z = undefined;return (_temp = y, _temp2 = _temp, z = _temp2 === undefined ? 1 : _temp2, _temp);
};

$
```

It seems that `=1` is treated like as *Initializer* in ES2015.
But I think it that `(z=1)=y;` is an invalid syntax in ES2015.
This is an experimental feature of babel?

**Comment by sebmck** [comment]
Yeah, it's invalid. `x=1` is being treated as an `AssignmentPattern`. Can you please report this to the [Acorn repo](https://github.com/marijnh/acorn) also, thanks!

**Comment by msmhrt** [comment]
@sebmck Thank you for your very quick reply! I'll report this bug to Acorn later.

**Comment by sebmck** [comment]
Closing in favor of marijnh/acorn#258 and marijnh/acorn#255. Thanks!
