### ISSUE TITLE
[Bug]: DI for typescript?

### ISSUE THREAD

**Issue by wang12124468** [babel/babel#13991]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```ts
class A {
     // Module parse failed: Unexpected character '@'
     constructor(@IB b: IB) {  }
}
```

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [
        ["@babel/preset-env", { "modules": false, "useBuiltIns": "entry", "corejs": { "version": 3, "proposals": true } }],
        "@babel/preset-react"
    ],
    "plugins": [
        ["@babel/plugin-transform-typescript", { "isTSX": true, "allExtensions": true, "allowNamespaces": true, "allowDeclareFields": true }],
        "@babel/plugin-proposal-function-bind",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }],
        "@babel/plugin-proposal-optional-chaining"
    ]
}
```

### Current and expected behavior

![image](https://user-images.githubusercontent.com/17714343/142984440-d0462848-ef2d-4499-9054-aad38a7ff53f.png)

### Environment

- babel: 7.10.4

**Comment by JLHwung** [comment]
Babel TypeScript preset does not support TypeScript parameter decorator yet. As a workaround, please install https://github.com/WarnerHooh/babel-plugin-parameter-decorator

**Comment by wang12124468** [comment]
> Babel TypeScript preset does not support TypeScript parameter decorator yet. As a workaround, please install https://github.com/WarnerHooh/babel-plugin-parameter-decorator

it's nice! thank you!!
