### ISSUE TITLE
`node` is undefined in `plugin-manager.js`

### ISSUE THREAD

**Issue by timbur** [babel/babel#1402]
https://github.com/babel/babel/blob/c12e8122f83636be31a1d6f888fea30bbe682f6a/src/babel/transformation/file/plugin-manager.js#L13

I encountered this just when using a custom plugin.  Apologies if I'm just overlooking something or if it's already a known issue.

**Comment by timbur** [comment]
Also, not sure how relevant it might be, but I'm running the plugin within a web browser.

**Comment by timbur** [comment]
My guess is that `node` here is actually supposed to be the `babel-core` module, containing `{ Transformer, types }` at the very least.

**Comment by sebmck** [comment]
Released as of 5.2.3, thanks!

**Comment by timbur** [comment]
I should add that there seems to be some issue with `babel.Transformer` (i.e., `node.Transformer`) also being `undefined` because `export default class Transformer` within [`transformer.js`](https://github.com/babel/babel/blob/cfffaf6cdbaafdbdfe5f58e4d288b05af04b521c/src/babel/transformation/transformer.js#L16) isn't being exported/imported properly via webpack/`_interopRequire`/whatever it is, but it could very well be a result of my hacking onto `browser.js` for my own short term purposes.

**Comment by sebmck** [comment]
@timbur You'd be referencing it before `Transformer` was initialised.

**Comment by timbur** [comment]
How do I ensure it's initialized?  When I was hacking onto `browser.js` just to see if I could make it work, I was able to essentially change `_interopRequire(transformer.js)` to `_interopRequireDefault(transformer.js)` and then using `babel.Transformer.default` worked, which I would assume means it is initialized but the actual `export default` step had not yet completed?

**Comment by sebmck** [comment]
> the actual `export default` step had not yet completed?

Basically. Live bindings are the only reason it works later on. Unsure what exactly you're hacking.

**Comment by timbur** [comment]
A little more info: I have a `SystemJS` plugin that transforms `jsx` files using `Babel`.

SystemJS `jsx.js` plugin:
https://gist.github.com/timbur/d91d235b568bfe984f1c

And the WIP `babel-plugin-react-hotify.js`:
https://github.com/timbur/babel-plugin-react-hotify/blob/master/index.js

Also, is `plugins: ['babel-plugin-react-hotify']` or `plugins: ['react-hotify']` supposed to work?  Right now I have to explicitly pass the actual plugin.

What needs to be done differently to make this work?  Sorry to bombard you with this right now!

**Comment by sebmck** [comment]
@timbur 

> What needs to be done differently to make this work?

Should work without the `default`. I just checked and there's no reason for the `default` property to be required.

> Sorry to bombard you with this right now!

All good :smile: 

> Also, is `plugins: ['babel-plugin-react-hotify']` or `plugins: ['react-hotify']` supposed to work?

It should, yeah. It's resolved relative to the cwd if that makes a difference.

**Comment by timbur** [comment]
@sebmck Would you mind testing it yourself?  I made a simple in-browser test: https://jsfiddle.net/sg5kbote/

Am I doing something wrong?

**Comment by sebmck** [comment]
@timbur Looks like it was due to a race condition with browser API as it has a separate front facing API. I'll push out a patch release with a fix.

**Comment by sebmck** [comment]
Fixed as of 5.2.4.

**Comment by timbur** [comment]
Cool, thanks!  Good ol' race conditions amirite.

Also, when I use `plugins: ['babel-plugin-react-hotify']`, I don't see any indication in my network panel that `babel-plugin-react-hotify.js` is being requested.  It's not a big deal since we can `require` the plugin beforehand though.  Or is there something I can do to make `browser.js` recognize and use `SystemJS`?

**Comment by sebmck** [comment]
Oh right yeah, passing in plugins via string references in the browser wont work because there's no module loader available.

**Comment by timbur** [comment]
Good to know!  Just wanted to make sure things were working as intended.  :)

**Comment by timbur** [comment]
Just tested 5.2.4 and it works beautifully!  Thanks again!!!
