### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by diy4869** [babel/babel#14027]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```tsx
function Demo () {
  const a: number = 1

  console.log(a)
  
  return (
    <div>
      <Grid gap={10}>
        {
          Array.from({
            length: 24
          }).map((_, index) => {
            return (
              <GridItem key={index} className={`demo-container ${index % 2 === 0 ? 'red' : 'blue'}`}>{index + 1}</GridItem>
            )
          })
        }
      </Grid>
    </div>
  )
}

ReactDOM.render(<Demo/>, container)
```
```js 
const result = transformSync(code, {
            // sourceType: 'module',
            filename: 'test.js',
            parserOpts: {
              presets: [
                '@babel/preset-env',
                
                // '@babel/preset-react',
                '@babel/preset-typescript',           // '@babel/preset-react'
              ]
            }
   
          })
          console.log(result)
```

### Current and expected behavior

I want to compile a section of typescript react code through @ Babel / core, but the output results show that the part of typescript is not compiled successfully, but it is OK on the official website.

Hope for results
![image](https://user-images.githubusercontent.com/29079700/144749945-87f235f4-6a37-495a-a8f9-21d6adc247c1.png)

Actual compilation results
![image](https://user-images.githubusercontent.com/29079700/144749898-46e65dfe-1dba-4add-919e-a64799ea4dea.png)

github: ![OTAKU-UI](https://github.com/diy4869/otaku-ui)

cd packages/site

npm run demo-test

### Environment

```json
"@babel/core": "^7.13.8",
"@babel/plugin-transform-typescript": "^7.16.1",
"@babel/preset-env": "^7.13.9",
"@babel/preset-react": "^7.12.13",
"@babel/preset-typescript": "^7.16.0",
"ts-loader": "^8.0.17",
"typescript": "^4.2.3",
```

- node 16.13.0
- npm 8.1.0
- yarn 1.22.0
- Windows 10

**Comment by nicolo-ribaudo** [comment]
You should pass the presets directly, not in `parserOpts`:
```js
          const result = transformSync(code, {
            // sourceType: 'module',
            filename: 'test.js',
            presets: [
              '@babel/preset-env',
                
              // '@babel/preset-react',
              '@babel/preset-typescript',           // '@babel/preset-react'
            ]
          })
```

**Comment by diy4869** [comment]
I don't quite understand. Doesn't this count

**Comment by diy4869** [comment]
At first, the configuration was written in babel.config.js, but it could not be compiled, so it was tested through @ Babel / core transform, but it still could not be compiled

```js

module.exports = {
  presets: [
    '@babel/env',
    '@babel/preset-react',
    '@babel/preset-typescript'
  ],
  plugins: [
    'react-hot-loader/babel',
    '@babel/plugin-syntax-dynamic-import'
  ],
  parserOpts: {
    // presets: [
    //   '@'
    // ]
    plugins: [
      'jsx',
      'typescript'
    ]
  }
}
```

**Comment by diy4869** [comment]
repo address： https://github.com/diy4869/otaku-ui

##: test
-yarn install
- cd packages/site 
- npm run demo-test
- demoPath: packages/site/webpack/loader/md-loader.js

or 
- yarn install
- cd packages/site
- npm run dev
- address: http://localhost:8080/#/grid

**Comment by JLHwung** [comment]
The error is thrown in 

https://github.com/diy4869/otaku-ui/blob/08d6f951a9cef0f32a24f442b1f8716fc517e2c3/packages/site/webpack/loader/md-loader.js#L113-L128

The `preset-typescript` and `preset-jsx` is not activated because the passed `filename` ends with `.js`. In most Babel use cases,  the input source are read from a file system so it makes sense to skip unwanted transform for vanilla js files. In your case you are extracting the code snippets from a markdown file, it makes sense to set file extensions accordingly. For example, use `example.tsx` as the `filename` for snippet annotations such as <code>```tsx</code>.

**Comment by diy4869** [comment]
This code is just an example I use for testing
```js
module.exports = {
  presets: [
    '@babel/preset-env',
    [
      '@babel/preset-typescript',
      {
        isTsx: true
      }
    ],
    '@babel/preset-react'
  ]
}

```

This is the corresponding configuration file

**Comment by liuxingbaoyu** [comment]
Since this issue is outdated, I will close it.
