### ISSUE TITLE
[Bug]: Problem on both using Babel babel/plugin-transform-classes and regenerator for async class methods

### ISSUE THREAD

**Issue by a20185** [babel/babel#14030]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```ts

class Demo {
	
  public nonAsyncFn() {
  	console.log('nonAsyncFn')
  }
  
  public async asyncFn() {
  	console.log('asyncFn')
  }

}

```

### Configuration file name

babel.config.js

### Configuration

```json
{
  presets: ['@vue/app'],
}
```

### Current and expected behavior

Current behavior: the error stack inside current method lose context, when trying to getting where the function is running from, we currently get the meaningless `TestClass._callee$` instead of original `TestClass.asyncFn`

### Environment

repl: https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEAiCmBbA9tA3gKAJAetADgK4BGIAlsNAHbJUCCEAnlcAGJUAUAlOrtFsFoRkIeADoQyAOYcA5DXpMW7WVz4BfPnyKkK0SM0oHlnHpjwChI8ZJmzjbKqo0YM6oA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.16.4&externalPlugins=%40babel%2Fplugin-transform-regenerator%407.16.0&assumptions=%7B%7D

### Possible solution

Provide method names in the Regenerator.mark and Regenerator.wrap, to ensure we can get correct execution info.

### Additional context

When using both, it seemed that the async methods in _createClass output lose the origin names, compared to the other non-async functions:
![image](https://user-images.githubusercontent.com/14831358/144773201-0e728347-c309-4cc6-86ab-430593e3d421.png)
I found this was troublesome in some cases. Take runtime stack parsing as an example, now function was replaced by another function which name is not the same as original, hence we cannot figure out what function is really running at runtime(Because the error stack now shows at SomeClass.callee$ instead of at SomeClass.yourActualMethod )
![image](https://user-images.githubusercontent.com/14831358/144773222-b20b83a9-1098-46b4-b452-69eed3142bbb.png)
I'm not quite sure about this transforming procedure machanism is done by babel itself or regenerator transform. An 'option' to preserve the function name, or providing enough infomation at execution will be really really helpful, thanks!

**Comment by a20185** [comment]
It seemed that this problem was caused by [@babel/plugin-transform-async-to-generator](https://babeljs.io/docs/en/babel-plugin-transform-async-to-generator), while wrapped by an anonymous generator function performing remapping

**Comment by a20185** [comment]
@nicolo-ribaudo If it's difficult to adjust, is it possible to remap the output outside (within babel, by creating anther plugin, or something else), such as replacing the following output
```javascript
_createClass(Demo, [{
    key: "nonAsyncFn",
    value: function nonAsyncFn() {
      console.log('nonAsyncFn');
    }
  }, {
    key: "asyncFn",
    value: function () {
      var _asyncFn = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
        return regeneratorRuntime.wrap(function _callee$(_context) {
          while (1) {
            switch (_context.prev = _context.next) {
              case 0:
                console.log('asyncFn');

              case 1:
              case "end":
                return _context.stop();
            }
          }
        }, _callee);
      }));

      function asyncFn() {
        return _asyncFn.apply(this, arguments);
      }

      return asyncFn;
    }()
  }]);
```
into `remapped named` version:

```
_createClass(Demo, [{
    key: "nonAsyncFn",
    value: function nonAsyncFn() {
      console.log('nonAsyncFn');
    }
  }, {
    key: "asyncFn",
    value: function () {
      var _asyncFn = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _asyncFn$() {
        return regeneratorRuntime.wrap(function _asyncFn$$(_context) {
          while (1) {
            switch (_context.prev = _context.next) {
              case 0:
                console.log('asyncFn');

              case 1:
              case "end":
                return _context.stop();
            }
          }
        }, _asyncFn$);
      }));

      function asyncFn() {
        return _asyncFn.apply(this, arguments);
      }

      return asyncFn;
    }()
  }]);
```

**Comment by nicolo-ribaudo** [comment]
@a20185 Babel does not rename the function; thanks to this code that it injects:
```js
      function asyncFn() {
        return _asyncFn.apply(this, arguments);
      }
```

You can verify it by logging `console.log(Demo.prototype.asyncFn.name)`. However, it injects a bunch of calls _inside_ the `asyncFn` function: you are seeing them in the stack trace, but if you look at a silghtly longer stack trace you will see the function name that you expect. If you add a `throw new Error("Err");` inside `asyncFn` in the example, the stack trace looks like this:
```
Uncaught (in promise) Error: Err
    _callee$ debugger eval code:32
    l https://babel.dev/js/build/repl.js:2
    _invoke https://babel.dev/js/build/repl.js:2
    x https://babel.dev/js/build/repl.js:2
    asyncGeneratorStep debugger eval code:3
    _next debugger eval code:5
    _asyncToGenerator debugger eval code:5
    _asyncToGenerator debugger eval code:5
    asyncFn debugger eval code:43
    <anonymous> debugger eval code:2
    <anonymous> debugger eval code:3
```

you an see that a few lines before the `asyncGeneratorStep` (where your error stack is cropped), there is `asyncFn`.

If you are using Chrome or Node.js, you can get longer error stacks by setting `Error.stackTraceLimit = 50`.

**Comment by a20185** [comment]
Wow，thanks a lot!
`Error.stackTraceLimit = 50` indeed solved the stack parsing at development!
