### ISSUE TITLE
[Bug]: Babel is throwing an error at the `$schema` property in json config files

### ISSUE THREAD

**Issue by arthurfiorette** [babel/babel#14038]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```jsonc
// babel.config.json
{ 
  "$schema": "https://json.schemastore.org/babelrc",
   "...": "..."
}
```

### Configuration file name

babel.config.json

### Configuration

```json
{ 
  "$schema": "https://json.schemastore.org/babelrc",
   "...": "..."
}
```

### Current and expected behavior

Babel is throwing the following error, but the `$schema` property should be allowed to add editor intellisense.

```
$ babel src --out-dir dist --extensions '.ts'
Error: Unknown option: .$schema. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  ...
  code: 'BABEL_UNKNOWN_OPTION'
```

### Environment

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.2.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @babel/cli: ^7.16.0 => 7.16.0 
    @babel/core: ^7.16.0 => 7.16.0 
    @babel/plugin-proposal-class-properties: ^7.16.0 => 7.16.0 
    @babel/plugin-proposal-object-rest-spread: ^7.16.0 => 7.16.0 
    @babel/plugin-transform-runtime: ^7.16.4 => 7.16.4 
    @babel/preset-env: ^7.16.4 => 7.16.4 
    @babel/preset-typescript: ^7.16.0 => 7.16.0 
    babel-loader: ^8.2.3 => 8.2.3 
    babel-runtime: ^6.26.0 => 6.26.0 
    eslint: ^8.3.0 => 8.4.1 
    jest: ^27.4.0 => 27.4.3 
    webpack: ^5.65.0 => 5.65.0  
```

### Possible solution

Allow the `$schema` property at configuration files.

Probably in this function:

https://github.com/babel/babel/blob/94af0e5c629b63fa11512b2ea8a8ac81d11a9db5/packages/babel-core/src/config/validation/options.ts#L295

**Comment by nicolo-ribaudo** [comment]
I agree that we can ignore it. Note that it should only be ignored at the top-level of JSON files, and no where else. It might actually be easier to just delete the `$schema` property when reading the file.

**Comment by The-x-Theorist** [comment]
@nicolo-ribaudo how can we delete the `$schema` property?

**Comment by nicolo-ribaudo** [comment]
We can do it in the function which loads JSON files: https://github.com/babel/babel/blob/7178fbb0085bff96945e88f0a35ab492288532c2/packages/babel-core/src/config/files/configuration.ts#L258

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue, can this issue be assigned to me?

**Comment by nicolo-ribaudo** [comment]
I just noticed that @arthurfiorette checked "Would you like to work on a fix?" in the issue description; lets give him two days to confirm if he wants to :pray:

**Comment by arthurfiorette** [comment]
Hey!

Sorry, but this week is being tough. If no one start this, next week i'll work on it

**Comment by The-x-Theorist** [comment]
@arthurfiorette I will start working on this.

**Comment by The-x-Theorist** [comment]
@nicolo-ribaudo where can we write test for the this?

**Comment by nicolo-ribaudo** [comment]
Somewhere in https://github.com/babel/babel/blob/main/packages/babel-core/test/config-chain.js, with a fixture in https://github.com/babel/babel/tree/main/packages/babel-core/test/fixtures/config/config-files

**Comment by arthurfiorette** [comment]
> @arthurfiorette I will start working on this.

Have you made any progress? I think I can help you now.

**Comment by The-x-Theorist** [comment]
@arthurfiorette Thank you, But I have found a solution to fix the issue that might work, opening a PR soon.
