### ISSUE TITLE
[Bug]: Unexpected `StringLiteral` node in `@babel/eslint-parser`

### ISSUE THREAD

**Issue by fisker** [babel/babel#14037]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const {ast} = require('@babel/eslint-parser').parseForESLint('export { "a" } from "a";', {requireConfigFile: false})
```

```text
ast.body[0].specifiers[0]
Node {
  type: 'ExportSpecifier',
  start: 9,
  end: 12,
  loc: SourceLocation {
    start: Position { line: 1, column: 9 },
    end: Position { line: 1, column: 12 },
    filename: undefined,
    identifierName: undefined
  },
  range: [ 9, 12 ],
  local: Node {
    type: 'Literal',
    start: 9,
    end: 12,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: undefined
    },
    range: [ 9, 12 ],
    value: 'a',
    raw: '"a"'
  },
  exported: Node {
    type: 'StringLiteral',    // <------------ Here
    start: 9,
    end: 12,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: undefined
    },
    range: [ 9, 12 ],
    extra: undefined,
    value: 'a'
  }
}
```

### Current and expected behavior

`StringLiteral` should be `Literal` with string value.

### Environment

Latest version of @babel/eslint-parser

### Additional context

Similar to #13329, but only happens when specifier is shorthand.

**Comment by JLHwung** [comment]
This is a regression introduced in #13611. 

The `cloneStringLiteral` method always set `type` to `StringLiteral`:

https://github.com/babel/babel/blob/94af0e5c629b63fa11512b2ea8a8ac81d11a9db5/packages/babel-parser/src/parser/node.js#L82

we can override `cloneStringLiteral` in `estree` plugin.
