### ISSUE TITLE
[Bug]: the classProperty function in  babel/types can not create classProperty with tSNonNullExpression

### ISSUE THREAD

**Issue by YuFengDing** [babel/babel#14046]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

**
import * as t from "@babel/types"
import generate from "@babel/generator"

const classProperties = t.classProperty(
            t.tSNonNullExpression(
                t.identifier('test')
            ),
            null, 
            t.tsTypeAnnotation(
                t.tSStringKeyword()
            ))
const classBody = t.exportNamedDeclaration(t.classDeclaration(
        t.identifier('ClassName'), null,t.classBody(classProperties)
    ))
const output = generate(classBody,{});
console.log('code',output.code);
**

### Current and expected behavior

Current i got 
```
/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/definitions/utils.js:132
    throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val == null ? void 0 : val.type)}`);
          ^
TypeError: Property key of ClassProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "TSNonNullExpression"
    at validate (/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/definitions/utils.js:132:11)
    at /Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/definitions/core.js:1288:9
    at Object.validate (/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/definitions/utils.js:229:7)
    at validateField (/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/validators/validate.js:24:9)
    at validate (/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/validators/validate.js:17:3)
    at String.builder (/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/builders/builder.js:39:27)
    at Object.classProperty (/Users/dingyufeng/workspace/eval-framework/node_modules/_@babel_types@7.16.0@@babel/types/lib/builders/generated/index.js:584:27)
    at /Users/dingyufeng/workspace/eval-framework/packages/villajs-tpl-gen/gen/node.ts:41:18
    at Array.map (<anonymous>)
```

I had checked the parameter type of classProperty 
![image](https://user-images.githubusercontent.com/23763023/145765512-5f0a90c6-0134-43ea-9623-a54581b24c21.png)

it contians `Expression` so i think it is unexcepted when i gave the `TSNonNullExpression` type

### Environment

System:
    OS: macOS 10.15.7
  Binaries:
    Node: 10.24.0 - ~/workspace/eval-framework/node_modules/.bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/workspace/eval-framework/node_modules/.bin/npm
  npmPackages:
    @babel/parser: ^7.16.0 => 7.16.0 
    @babel/traverse: ^7.16.0 => 7.16.0 
    @babel/types: ^7.16.0 => 7.16.0

**Comment by lightmare** [comment]
Property key can only be expression for computed properties, so you need to pass `true` in the 5th argument.

Babel could, however, give a more useful error message in this case. It took me a while of digging into validators to figure out what's going on. Although it's kinda obvious in hindsight, the type declaration alone doesn't explain this interaction.

https://github.com/babel/babel/blob/dfcfbf3b274343f782edbf5f6de0a6d830d77edb/packages/babel-types/src/definitions/core.ts#L1750-L1753

For reference this is the validation function:

**Comment by JLHwung** [comment]
If you intend to create AST for

```ts
class C {
  test!: string
}
```

the `test!` here is _not_ an TSNonNullExpression. Instead it is a definite class property, which can be created by assigning `definite: boolean`:

```js
const classProperty = t.classProperty(
  t.identifier("test"),
  null,
  t.tsTypeAnnotation(t.tsStringKeyword())
);
classProperty.definite = true;

```

**Comment by nicolo-ribaudo** [comment]
Or, if you prefer,
```js
const classProperty = Object.assign(t.classProperty(
  t.identifier("test"),
  null,
  t.tsTypeAnnotation(t.tsStringKeyword())
), { definite: true });
```

Builders for JS nodes don't have explicit params for Flow and TS features, so you have to manually set them.
