### ISSUE TITLE
[Bug]: Strange error on latest

### ISSUE THREAD

**Issue by alexander-schranz** [babel/babel#14059]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

The setup is a little bit complexer where I can reproduce it.
Simpliest way is by doing:

```
git clone git@github.com:sulu/sulu.git
cd sulu

npm install
npm run build
```

### Configuration file name

babel.config.js

### Configuration

```json
{
    "presets": [
        ["@babel/preset-env", {"useBuiltIns": "usage", "corejs": "3.18"}],
        "@babel/preset-react"
    ],
    "plugins": [
        ["@babel/plugin-proposal-decorators", {"legacy": true}],
        "@babel/plugin-transform-flow-strip-types",
        "@babel/plugin-proposal-nullish-coalescing-operator"
    ],
    "assumptions": {
        "setPublicClassFields": true
    }
}
```

### Current and expected behavior

Currenlty the build errors with:

```
ERROR in ./node_modules/sulu-custom-url-bundle/containers/Form/fields/CustomUrl.js 10:15
Module parse failed: Unexpected token (10:15)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
| let CustomUrl = observer(_class = class CustomUrl extends React.Component {
>   handleChange = value => {
|     const {
|       onChange
```

The build should not error

### Environment

Babel: 7.16.6 (latest versions)
Node: v14.18.1
Npm: 6.14.15
OS: MacOS (multiple OSs)

### Possible solution

I have no possible solution yet.

### Additional context

The build is using flow and so flow babel plugin. Maybe there is some incompatibility now?

Difference between an old (left) working package-lock.json and a new (right) not longer working packages: https://www.diffchecker.com/CXEQcvCi So not 100% sure if its caused by babel, but most of the package update come from it.

**Comment by nicolo-ribaudo** [comment]
This is not actually caused by Babel, but the recent Safari 15.x releases which changed the meaning of "the last 2 browser versions".

Your browserslistrc file is this one:
```
last 2 versions and not dead
not ie < 12
not ie_mob < 12
```

which resolves to these targets and plugins:
```
@babel/preset-env: `DEBUG` option

Using targets:
{
  "android": "95",
  "chrome": "95",
  "edge": "95",
  "firefox": "94",
  "ios": "15",
  "opera": "81",
  "safari": "15.1",
  "samsung": "14"
}

Using modules transform: auto

Using plugins:
  proposal-class-static-block { ios, safari, samsung }
  proposal-private-property-in-object { samsung }
  syntax-class-properties
  syntax-numeric-separator
  syntax-nullish-coalescing-operator
  proposal-optional-chaining { samsung }
  syntax-json-strings
  syntax-optional-catch-binding
  transform-parameters { ios, safari }
  syntax-async-generators
  syntax-object-rest-spread
  proposal-export-namespace-from { ios, safari }
  syntax-dynamic-import
  syntax-top-level-await
```

As you can see, it doesn't include the class fields transform because it's supported by all the browsers you are targeting. You have a few options:
- change your browserslistrc file to include older browsers
- explicitly add `@babel/plugin-proposal-class-fields` to your Babel config
- update Webpack to a version that supports class fields

<details>
<summary>For reference, a few days ago it resolved to this</summary>

```
Using targets:
{
  "android": "94",
  "chrome": "94",
  "edge": "94",
  "firefox": "92",
  "ios": "14.5",
  "opera": "79",
  "safari": "14.1",
  "samsung": "14"
}

Using modules transform: auto

Using plugins:
  proposal-class-static-block { firefox < 93, ios, opera < 80, safari, samsung }
  proposal-private-property-in-object { ios < 15, safari < 15, samsung }
  proposal-class-properties { ios < 15, safari < 15 }
  proposal-private-methods { ios < 15, safari < 15 }
  syntax-numeric-separator
  syntax-nullish-coalescing-operator
  proposal-optional-chaining { samsung }
  syntax-json-strings
  syntax-optional-catch-binding
  transform-parameters { ios, safari }
  syntax-async-generators
  syntax-object-rest-spread
  proposal-export-namespace-from { ios, safari }
  transform-modules-commonjs
  proposal-dynamic-import
```
</details>

**Comment by alexander-schranz** [comment]
@nicolo-ribaudo Thank you very much. This did help us a lot. We also did target it down at the same time as you posted to the new `caniuse-lite` version. And as you mention we are still using `webpack 4` and `webpack 4`and the old webpack terser parser does not yet support this syntax. We will go with the `@babel/plugin-proposal-class-fields` at current state. Really thank you for the detail report and help here!

**Comment by alexander-schranz** [comment]
A question how did you get to the output of you did post with the used plugins?

**Comment by nicolo-ribaudo** [comment]
You can add `"debug": true` to the `preset-env` options 🙂

**Comment by alexander-schranz** [comment]
@nicolo-ribaudo Thank you! I think we can then close the issue as it has not directly todo with babel.
