### ISSUE TITLE
Default arguments in phantomjs 1.9 - es5 shim

### ISSUE THREAD

**Issue by piuccio** [babel/babel#1405]
Hi. I noticed this problem in phantomjs 1.9 when converting this code to es5.

```js
function (one='default', two='default') {}
```

In the generated code, `one` is always undefined.

I'm not good at explaining this in words, so I've created a repo. https://github.com/piuccio/phantom-es6

You can check the README, follow the steps.

Because phantom 1.9 is an old browser, I've included the es5-shim.

The file that is wrongly generated is `lib/params.js`.

If you try to simplify the code (have only one default argument or remove the underscore call) the code works fine.

**Comment by sebmck** [comment]
Can't reproduce this.

```sh
$ phantomjs index.js
correct
```

**Comment by piuccio** [comment]
Are you using phantom 1.9 or 2.0?

**Comment by sebmck** [comment]
Whoops, 2.0. PhantomJS 1.9 is extremely old and I'm unsure how to even begin debugging this. Is there a reason you need to support it?

**Comment by piuccio** [comment]
Unfortunately there's a reason...

Unit tests depend on node-phantomjs which however doesn't wrap phantomjs 2 yet because it doesn't compile on Mac/Linux.
See [this discussion](https://github.com/Medium/phantomjs/issues/288) for a better explanation.

I reckon the issue being in es5-shim, but I have no clue of how babel works and which polyfilled method is not working as expected.

**Comment by loganfsmyth** [comment]
Confirmed. I tracked down the issue this morning, PR should be an easy fix, I'll submit later tonight.
