### ISSUE TITLE
[Bug]: not able to install babel-helper-create-class-features-plugin^7.16.5

### ISSUE THREAD

**Issue by dhiraj05** [babel/babel#14053]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
npm install @babel/helper-create-class-features-plugin@^7.16.5
```

### Current and expected behavior

Not able to install "babel-helper-create-class-features-plugin" through npm, as it says version 7.16.5 not found, while the parent module "plugin-proposal-private-methods" needs this 7.16.5 version.

### Environment

Any

### Possible solution

Look at the CircleCI validation "https://github.com/babel/babel/runs/4512750050", it might be waiting for some approval.

It's been waiting for more than 5 hrs.

**Comment by JLHwung** [comment]
The package of version 7.16.5 is published. https://www.npmjs.com/package/@babel/helper-create-class-features-plugin

Please see https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67.

**Comment by dhiraj05** [comment]
ok, I am able to install.
