### ISSUE TITLE
[Bug]: @babel/cli `--copy-files` `--ignore **/**` can not work at the same time

### ISSUE THREAD

**Issue by joriewong** [babel/babel#14051]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
babel src -d es --ignore src/.umi/ --copy-files
```

### Current and expected behavior

current: `src/.umi` would be copied.
expected: ignored

### Environment

- @babel/cli@7.16.0
- node@v16.10.0
- npm@7.24.0
- macOS@12.0.1
- Monorepo: no

**Comment by heiseshandian** [comment]
Hi @joriewong , the meaning of `--ignore` means "List of glob paths to **not** compile.", `--no-copy-ignored` means "Exclude ignored files when copying non-compilable files.". 
So if you don’t want to copy the uncompiled code to the target directory you can use the following command:
```sh
babel src -d es --ignore src/.umi/ --copy-files --no-copy-ignored
```

Maybe the docs [@babel/cli](https://babeljs.io/docs/en/babel-cli#ignore-files) should be updated.

**Comment by joriewong** [comment]
@heiseshandian it's not working.

**Comment by heiseshandian** [comment]
Hi, @joriewong, did you delete the previously generated es directory?
![image](https://user-images.githubusercontent.com/7780463/148719349-6cbec77e-ad5e-4679-abf8-d694df9f67ca.png)

**Comment by joriewong** [comment]
@heiseshandian `--delete-dir-on-start` was using. you can try `--presets` to reproduce.

**Comment by simo385** [comment]
Dear All,

@heiseshandian  I've the same issue. Any updates?

Simone

**Comment by heiseshandian** [comment]
@simo385 No, it hasn't been fixed.

**Comment by JLHwung** [comment]
If you don't want to copy ignored files, please specify `--no-copy-ignored`:

```
babel src --out-dir lib --copy-files --no-copy-ignored
```

See also https://babel.dev/docs/babel-cli#copy-files

**Comment by simo385** [comment]
Dear @JLHwung,

I'm using Babel-cli 7.25.6, and the `--no-copy-ignored` param doesn't work (see @heiseshandian above).

Could you share any solution with us?

Thanks for your support.
Simone

**Comment by JLHwung** [comment]
The intent of `--copy-files` is to copy all non-compilable files, we don't offer more features than that due to complexity concern. If you want to further exclude some non-compilable files or only include some non-compilable files, please use other tools for the copy task: For example, you can use `rsync`:

```shell
# Suppose you only compile *.js files
babel src --out-dir lib

# Copy all .css files in src to lib
rsync -a --include='*.css' src/ lib/

# Or copy all files except '*.md' files in src to lib
# In this case you have to exclude *.js as well
# otherwise the Babel output will be overwritten
rsync -a --exclude='*.md' --exclude='*.js' src/ lib/
```
