### ISSUE TITLE
[Bug]: Destructuring of sparse arrays yields null token

### ISSUE THREAD

**Issue by gajus** [babel/babel#14064]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```js
const [a,,b] = obj;
```

### Configuration

N/A

### Current and expected behavior

This will yield elements AST:

```json
[
  {
    "type": "Identifier",
    "start": 7,
    "end": 8,
    "loc": {
      "start": {
        "line": 1,
        "column": 7
      },
      "end": {
        "line": 1,
        "column": 8
      }
    },
    "range": [
      7,
      8
    ],
    "name": "a"
  },
  null,
  {
    "type": "Identifier",
    "start": 10,
    "end": 11,
    "loc": {
      "start": {
        "line": 1,
        "column": 10
      },
      "end": {
        "line": 1,
        "column": 11
      }
    },
    "range": [
      10,
      11
    ],
    "name": "b"
  }
]
```

The problem is that `null` cannot be used with ESLint sourcecode utility, e.g.

https://github.com/gajus/eslint-plugin-canonical/commit/2a804fcb9c96dc60efc895e04b2ea8afb4d5ea78

I would expect that AST includes some information that could be at least used to locate the token.

### Environment

  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.3.0/bin/yarn
    npm: 7.24.2 - ~/Documents/dev/gajus/eslint-plugin-canonical/node_modules/.bin/npm
  npmPackages:
    @babel/cli: ^7.16.0 => 7.16.0
    @babel/core: ^7.16.5 => 7.16.5
    @babel/eslint-parser: ^7.16.5 => 7.16.5
    @babel/node: ^7.16.5 => 7.16.5
    @babel/plugin-transform-react-jsx: ^7.16.5 => 7.16.5
    @babel/preset-env: ^7.16.5 => 7.16.5
    babel-plugin-add-module-exports: ^1.0.4 => 1.0.4
    eslint: ^8.5.0 => 8.5.0

**Comment by nicolo-ribaudo** [comment]
Babel matches the ESLint AST shape: https://astexplorer.net/#/gist/b7f638ecd898b097bd96bd6586ffbe7c/latest

**Comment by gajus** [comment]
Correct, however, that does not help.

**Comment by nicolo-ribaudo** [comment]
We need to match exactly the ESLint AST, so that ESLint plugins keep working when using `@babel/eslint-parser`. The ESLint AST is based on the [ESTree specification](https://github.com/estree/estree), which cannot have breaking changes: this will be `null` forever (except if ESLint stops follwing ESTree, then we'll match whatever ESLint does).

I suggest opening an issue in the ESLint repository asking to provide a `SourceCode` utility to handle these `null` nodes.

**Comment by nicolo-ribaudo** [comment]
> I would expect that AST includes some information that could be at least used to locate the token.

Btw, you _can_ locate the tokens! In `const [a,,b] = obj;`, the first comma is the first token after `a` (after `[0].range[1]` in the AST you posted), and the second comma is the last token before `b` (before `[2].range[0]`).
