### ISSUE TITLE
[Bug]: JSX: <\u{48}ello /> parse error

### ISSUE THREAD

**Issue by strager** [babel/babel#14060]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```jsx
function MyComponent() {
  return <\u{48}ello />;
}
```
https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAWQJ4GE4FsAOCCmYUAFAJSIDeAUIogE75Qh1IA8AOiBQCwAcAvvgA2QuIgD0APgDcVfkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.16.6&externalPlugins=&assumptions=%7B%7D

### Current and expected behavior

According to my understanding of the [JSX specification](https://facebook.github.io/jsx/) and the [ECMAScript specification](https://262.ecma-international.org/6.0/), `<\u{48}ello />` is a legal expression. I assume it is semantically the same as `<Hello />`.

Babel rejects `<\u{48}ello />`:
```
/repl.jsx: Unexpected token (2:10)

  1 | function MyComponent() {
> 2 |   return <\u{48}ello />;
    |           ^
  3 | }
```

Relevant syntax rules:
```
PrimaryExpression :
    JSXElement

JSXElement :
    JSXSelfClosingElement

JSXSelfClosingElement :
    < JSXElementName JSXAttributes(opt) / >

JSXElementName :
    JSXIdentifier

JSXIdentifier :
    IdentifierStart
    JSXIdentifier IdentifierPart

IdentifierStart::
    UnicodeIDStart
    \ UnicodeEscapeSequence

UnicodeEscapeSequence::
    u Hex4Digits
    u{ CodePoint }
```

### Environment

Web REPL https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAWQJ4GE4FsAOCCmYUAFAJSIDeAUIogE75Qh1IA8AOiBQCwAcAvvgA2QuIgD0APgDcVfkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.16.6&externalPlugins=&assumptions=%7B%7D

### Additional context

The TypeScript compiler parse the code in question as I expect: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWQJ4GE4FsAOCCmYUAFAJSIDeAUIogE75Qh1IA8AOiBQCwAcAvvgA2QuIgD0APgDcVfkA

esbuild and ESLint+espree fail to parse the code. esbuild and ESLint+espree seem to have behavior similar to Babel.

**Comment by JLHwung** [comment]
[TypeScript supports it](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoTAVwDsNgIa4AdKgFiQAZOAKASjgBvOERhUoTADwALAIwA+SQHo58uAF9yk1h26KlOrp3lA), I think we should follow.

**Comment by JLHwung** [comment]
Closing this issue as the current behaviour is intended, TS will match Babel's behaviour: https://github.com/facebook/jsx/pull/139
