### ISSUE TITLE
[Bug]:  '@babel/generator@7.16.4' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

### ISSUE THREAD

**Issue by MohitSChauhan** [babel/babel#14089]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

 '@babel/generator@7.16.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

### Configuration file name

package.json

### Current and expected behavior

Build is getting Failed

### Environment

PRID

**Comment by JLHwung** [comment]
There is no `@babel/generator@7.16.4`: https://www.npmjs.com/package/@babel/generator

We only publish changed packages during each release. You can safely use `@babel/generator@7.16.0` if you are using `@babel/parser@7.16.4`.
