### ISSUE TITLE
[Bug]: present-env compiles optional-chaining when browserslist query set does not require it

### ISSUE THREAD

**Issue by cdaringe** [babel/babel#14088]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel cli

### Input code

```js
const x = a?.b?.x;
```

output code:

```js
const x = (_a = a) === null || _a === void 0 ? void 0 : (_a$b = _a.b) === null || _a$b === void 0 ? void 0 : _a$b.c;
// expected
// const x = a?.b?.x;
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": ["@babel/preset-env"]
}
```

### Current and expected behavior

# Current

transpiles optional chaining

# Expected

no transpilation

### Environment
  System:
    OS: macOS 11.6.1
  Binaries:
    Node: 16.6.2 - ~/.fnm/node-versions/v16.6.2/installation/bin/node
    Yarn: 1.22.11 - ~/.fnm/node-versions/v16.6.2/installation/bin/yarn
    npm: 8.1.1 - ~/.fnm/node-versions/v16.6.2/installation/bin/npm
  npmPackages:
    @babel/cli: ^7.16.7 => 7.16.7 
    @babel/core: ^7.16.7 => 7.16.7 
    @babel/preset-env: ^7.16.7 => 7.16.7 

### Possible solution

- correct handling of browser detection in browserslist json map
- update browserslist json map

### Additional context

Full, minimal reproduction here: https://github.com/cdaringe/babel-preset-env-browserslist-optional-chaining-bug

**Comment by cdaringe** [comment]
- I've discovered that when [I remove `samsung` from the list](https://github.com/cdaringe/babel-preset-env-browserslist-optional-chaining-bug/commit/cd51cb9d3cd0d602eba68f66b0e2eb5088b993a4), it emits non-transpiled code.
- If you add ["samsung": "13.0"](https://caniuse.com/?search=optional%20chaining) to `@babel/compat-data/data/plugins.json`, it works per expectation

Is this correct behavior? How is `ios_safari` being processed? `ios_safari` is also missing from the map, but the compilation still does not down level

**Comment by cdaringe** [comment]
cc/ @HenrikJoreteg, because i know you care about optional-chaining expansion inefficiency! ;)

**Comment by JLHwung** [comment]
The optional chaining kicks in because Samsung (V8) has a bug on transforming optional chaining: https://crbug.com/v8/11558

You can add `bugfixes: true` to the preset-env options to tell Babel: only transform optional chaining when the input code is actually affected by this bug. This will be enabled by default on Babel 8.

**Comment by cdaringe** [comment]
Thanks @JLHwung, I’ll try this out soon. Can you comment on the relevance of the JSON config files? What inputs go into the decision to transpile a browserslist aware or not?

**Comment by JLHwung** [comment]
> What inputs go into the decision to transpile a browserslist aware or not?

Good question. preset-env [normalizes](https://github.com/babel/babel/blob/ddd93b9c61a197711c2e3eae8a8b175783ea6976/packages/babel-helper-compilation-targets/src/targets.ts#L5-L19) the browser name and then queries against the compat-data `plugins.json`. So in your cases

```
samsung -> samsung -> is in plugins.json ? -N-> Transpile 
ios_saf -> ios -> is in plugins.json ? -Y-> Not transpile
```

When `bugfixes` is `true`, the only difference is that we query against [`plugins-bugfixes.json`](https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugin-bugfixes.json).

```
samsung -> samsung -> is in plugins-bugfixes.json ? -Y-> Not transpile
ios_saf -> ios -> is in plugins-bugfixes.json ? -Y-> Not transpile
```

See also https://babel.dev/docs/en/babel-preset-env#how-does-it-work

**Comment by nicolo-ribaudo** [comment]
Closing since the question has been answered. If this needs to be reopened just leave a comment!
