### ISSUE TITLE
[Bug]:  babel not transpiling when importing css (webpack 5)

### ISSUE THREAD

**Issue by jnaklaas** [babel/babel#14083]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

index.js

```js
import "./style.scss";

var nums = [1, 2, 3];
var doubleNums = nums.map((e) => e * 2);
```

webpack.config.js

```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: ["babel-loader"],
      },
      {
        test: /\.scss$/,
        use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: "asset/resource",
      },
      {
        test: /\.(html)$/,
        use: ["html-loader"],
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html",
    }),
    new CleanWebpackPlugin(),
    new MiniCssExtractPlugin(),
  ],
};
```

### Configuration file name

babel.config.json

### Configuration

{
  "presets": [
    [
      "@babel/preset-env",
    ]
  ]
}

### Current and expected behavior

When importing a (s)css file in `index.js`, the js doesn't transpile properly (still contains an arrow function). 
```js
(()=>{"use strict";[1,2,3].map((function(t){return 2*t}))})();
```

When removing the css import statement, the arrow function is gone (although I'd expect the `"use strict";` statement to still be there).
```js
[1,2,3].map((function(n){return 2*n}));
```

### Environment

-   System:
    OS: macOS 10.15.7
 - Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
 - npmPackages:
    @babel/core: ^7.16.5 => 7.16.5 
    @babel/preset-env: ^7.16.5 => 7.16.5 
    babel-loader: ^8.2.3 => 8.2.3 
    webpack: ^5.65.0 => 5.65.0

**Comment by JLHwung** [comment]
What's the output if we disable `babel-loader`?

**Comment by jnaklaas** [comment]
> What's the output if we disable `babel-loader`?

```(()=>{"use strict";[1,2,3].map((s=>2*s))})();```

**Comment by JLHwung** [comment]
It seems to me the arrow function is generated by webpack. If your target does not support arrow function, consider set `output.environments` accordingly:

https://webpack.js.org/configuration/output/#outputenvironment

**Comment by jnaklaas** [comment]
> It seems to me the arrow function is generated by webpack. If your target does not support arrow function, consider set `output.environments` accordingly:
> 
> https://webpack.js.org/configuration/output/#outputenvironment

Correct, thank you!
