### ISSUE TITLE
Allow to add "configurable: true" for re-exported members

### ISSUE THREAD

**Issue by heiseshandian** [babel/babel#14085]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

Currently, for re-exported members, babel didn't add `configurable: true` props, which will cause us to write more code when mocking. 

For example, there is a module named "moduleA".
```js
// moduleA
import foo from 'internal module'
export {foo}
```
After babel compilation, it will become:
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "foo", {
  enumerable: true,
  get: function get() {
    return _internalModule.default;
  }
});

var _internalModule = _interopRequireDefault(require("internal module"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

As we can see, "foo" is not configurable after babel compilation(if `configurable` is not specified, it will default to `false`).

Now, if we want to mock the return value of "foo", we have to mock the whole module, let's take `jest` for instance:
```js
jest.mock('moduleA',() => {
  const original = jest.requireActual('moduleA');
  return {
      ...original,
      foo: () => "mock value",
  };
})
```
If we can add an option to indicate babel to add `configurable: true` for re-exported members, then we can simplify our test code as bellow.
```js
import * as ModuleA from 'moduleA';
jest.spyOn(ModuleA,'foo').mockReturnValue("mock value");
```

### Describe the solution you'd like

Add an option such as `allowConfigurableForReExports` to indicate babel to add `configurable: true` for re-exported members.

### Describe alternatives you've considered

Directly mock the whole module when mocking re-exported members.

**Comment by heiseshandian** [comment]
Did some research in the repo, and I have discovered that `@babel/plugin-transform-modules-amd`, `@babel/plugin-transform-modules-commonjs`, `@babel/plugin-transform-modules-umd` depends on `@babel/helper-module-transforms` to transform modules, which contains some hard-code templates for transforming modules:
```ts
const ReexportTemplate = {
  constant: template.statement`EXPORTS.EXPORT_NAME = NAMESPACE_IMPORT;`,
  constantComputed: template.statement`EXPORTS["EXPORT_NAME"] = NAMESPACE_IMPORT;`,
  spec: template.statement`
    Object.defineProperty(EXPORTS, "EXPORT_NAME", {
      enumerable: true,
      get: function() {
        return NAMESPACE_IMPORT;
      },
    });
    `,
};
```

Maybe we can add an option to generate different templates(one with `configurable: true`, another without `configurable: true`)

**Comment by JLHwung** [comment]
The spec requires that a module namespace exotic object can't be extended, so `configurable` must be `false`: https://tc39.es/ecma262/#sec-module-namespace-exotic-objects-isextensible

If you prefer the loose `configurable: true` behaviour, you can enable the `constantReexports` assumption:

https://babeljs.io/docs/en/assumptions#constantreexports

**Comment by heiseshandian** [comment]
@JLHwung Thank you very much for your answer, I should read the documentation first. Sorry for wasting your time.
