### ISSUE TITLE
A way to process typescript without deleting types

### ISSUE THREAD

**Issue by Paolo-Oliverio** [babel/babel#14095]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I want to use babel to add macros to typescript but still retain types that I need for further transpilation in lua script.

### Describe the solution you'd like

an option to disable type deletion

### Describe alternatives you've considered

look for a pass trough preset for babel, but it doesn't seem to exist.

**Comment by nicolo-ribaudo** [comment]
You can use `@babel/plugin-syntax-typescript` rather than `@babel/preset-typescript`/`@babel/plugin-transform-typescript`.

All the `-syntax-` plugins enable parsing without transforming await their feature.
