### ISSUE TITLE
[Bug]: path.stop() method not working on ReferencedIdentifier/AssignmentExpression nodes

### ISSUE THREAD

**Issue by Amarettini** [babel/babel#14099]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

https://github.com/Amarettini/babel-issue-stop-traversal is the repo for this issue.

https://github.com/Amarettini/babel-issue-stop-traversal/blob/master/index-short-short.js is the file that isolates the problem. Run it with `node ./index-short-short.js`. The other files are less specific.

### Configuration file name

package.json

### Configuration

No configuration needed, only `@babel/traverse` and `@babel/parser` are used.

## Observed issue

`path.stop()` method does not stop the traversal when called in `ReferencedIdentifiers`/`AssignmentExpression` nodes.

## Expected behavior

`path.stop()` should stop the traversal as soon as the method was called.

## Example

You can see how babel continues to traverse the tree, visiting multiple times a `ReferencedIdentifier` node, ignoring the `path.stop()` call.
Current output of `index-short-short.js`:
```
PS C:\Users\Pat\dev\side\babel-stop-traversal> node index-short-short.js
Enter Program
Enter FunctionDeclaration
Enter Identifier
Enter Identifier
Enter Identifier
Enter BlockStatement
Enter ExpressionStatement
Enter AssignmentExpression
Enter Identifier
Enter StringLiteral
Enter VariableDeclaration
Enter VariableDeclarator
Enter Identifier
Enter BinaryExpression
Enter Identifier
-> ReferencedIdentifier      (path.stop() called!)
Enter ExpressionStatement
Enter CallExpression
Enter MemberExpression
Enter Identifier
-> ReferencedIdentifier      (path.stop() called!)
Enter Identifier
-> ReferencedIdentifier      (path.stop() called!)

```

Expected output of `index-short-short.js`
```
PS C:\Users\Pat\dev\side\babel-stop-traversal> node index-short-short.js
Enter Program
Enter FunctionDeclaration
Enter Identifier
Enter Identifier
Enter Identifier
Enter BlockStatement
Enter ExpressionStatement
Enter AssignmentExpression
Enter Identifier
Enter StringLiteral
Enter VariableDeclaration
Enter VariableDeclarator
Enter Identifier
Enter BinaryExpression
Enter Identifier
-> ReferencedIdentifier      (path.stop() called!)

```

### Environment

System:
OS: Windows 10 10.0.19043

Binaries:
Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
Yarn: 3.0.2 - C:\Program Files\nodejs\yarn.CMD
npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD

npmPackages:
@babel/parser: ^7.16.7 => 7.16.7
@babel/traverse: ^7.16.7 => 7.16.7

**Comment by JLHwung** [comment]
A minimal test case without virtual types:
```js
const code = `
f;
g;
`;

const ast = parser.parse(code);

traverse(ast, {
  noScope: true,
  enter(path) {
    console.log("Enter", path.type);

    // the log statement below should only log once, which is not the case
    if(path.isIdentifier()) {
      console.log("-> Identifier      (path.stop() called!)");
      path.stop();
    }
  }
});
```

When a node is stopped, it seems to me that the parent is not stopped accordingly, so the parent siblings keeps being visited.
