### ISSUE TITLE
[Bug]: Babel "loose" mode produce wrong code with spread syntax

### ISSUE THREAD

**Issue by SukkaW** [babel/babel#14090]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
const a = [...document.querySelectorAll()]
const b = [...new Set(['a'])]
```

### Current and expected behavior

With `loose` enabled, Babel produces:

```js
"use strict";

require("core-js/modules/es.array.concat.js");

require("core-js/modules/es.array.iterator.js");

require("core-js/modules/es.object.to-string.js");

require("core-js/modules/es.set.js");

require("core-js/modules/es.string.iterator.js");

require("core-js/modules/web.dom-collections.iterator.js");

var a = [].concat(document.querySelectorAll());
var b = [].concat(new Set(['a']));
```

Obviously, something unintended happened.

### Environment

[Babel REPL](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=usage&corejs=3.6&spec=false&loose=true&code_lz=MYewdgzgLgBAhjAvDA2gOgwExMArgWwFMwo0BHXQgJwE8BlQgG0OChCoEFHGAKASgC6AKFCRYAIySoMaMIQDuMBlB4oA5HDUDBQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.16.7&externalPlugins=%40babel%2Fplugin-proposal-export-default-from%407.5.2&assumptions=%7B%7D)

**Comment by nicolo-ribaudo** [comment]
loose mode assumes that you are spreading an array. You can either stop using loose mode (and use the better and more granular [`assumptions`](https://babeljs.io/docs/en/assumptions) option), or you can convert your iterables to arrays:
```js
const a = [...Array.from(document.querySelectorAll())]
const b = [...Array.from(new Set(['a']))]
```
