### ISSUE TITLE
Missing structuredClone

### ISSUE THREAD

**Issue by MatthD** [babel/babel#14100]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Hello,

I am trying to use https://developer.mozilla.org/en-US/docs/Web/API/structuredClone api but it does not seems to exist in the current babel latest versions 

### Describe the solution you'd like

Integrates the `StructuredClone` function

### Describe alternatives you've considered

I do not see any alternatives

**Comment by zloirock** [comment]
It's available in the latest `core-js`. For availability in `preset-env` with the `usage` mode, its `babel-plugin-polyfill-corejs3` dependency should be updated.

**Comment by nicolo-ribaudo** [comment]
Updated in https://github.com/babel/babel/pull/14108, it will be released in the next version.

If you want to use it now, I suggest using the `core-js` integration from github.com/babel/babel-polyfills/ directly.
