### ISSUE TITLE
[Bug]: Set is not transformed into array in loose mode

### ISSUE THREAD

**Issue by dherbolt** [babel/babel#14115]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
const s = new Set('a')
const a = [...s]
```

### Configuration file name

.babelrc

### Configuration

```js
{
              useBuiltIns: 'entry',
              loose: true,
              corejs: '3',
              // Do not transform modules to CJS
              modules: false,
              // Exclude transforms that make all code slower
              exclude: ['transform-typeof-symbol'],
}
```

### Current and expected behavior

current
```js
var s = new Set('a');
var a = [].concat(s);
```

expected: 
```js
a.concat(Array.from(s)) // or anything else supported by required browsers
```

### Environment

- Babel 7.16
- browserlist config: >0.2%, not dead, not op_mini all

### Additional context

`[...(new Set())]` is incorrectly transformed if **loose** mode is used. Result also depends on required browsers.

Example: https://babeljs.io/repl#?browsers=%3E0.2%25%2C%20not%20dead%2C%20not%20op_mini%20all&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=MYewdgzgLgBBMF4ZgKYHcYGUVQBQHIBDfASgChRJZDEYBtAOiYgF0g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env&prettier=false&targets=&version=7.16.7&externalPlugins=&assumptions=%7B%7D

Bable config: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/src/babel/preset.ts#L32
Result: https://playcode.io/850890/

**Comment by nicolo-ribaudo** [comment]
Please see https://github.com/babel/babel/issues/14090#issuecomment-1003414511.
