### ISSUE TITLE
@babel/template suport typescript token

### ISSUE THREAD

**Issue by gaollard** [babel/babel#14117]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

it is too much to build complex InterfaceDeclaration node use @babel/types interfaceDeclaration, it need to do recursive.

### Describe the solution you'd like

use template to create InterfaceDeclaration Node:

```js
const declaration = template.statement.ast`interface Model {}`
```

### Describe alternatives you've considered

noop

**Comment by JLHwung** [comment]
You can pass extra parser options to the `template.statement` API.

```js
const declaration = template.statement("interface Model {}", { plugins: ["typescript"] })()
```

**Comment by gaollard** [comment]
> You can pass extra parser options to the `template.statement` API.
> 
> ```js
> const declaration = template.statement("interface Model {}", { plugins: ["typescript"] })()
> ```

wow, appreciate it!
