### ISSUE TITLE
[Bug]: Rogue 'let' statements in Babel package breaks ES5 support

### ISSUE THREAD

**Issue by NeilFraser** [babel/babel#14112]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

<script src="https://unpkg.com/@babel/standalone@7.16.4/babel.min.js"></script>

### Current and expected behavior

Browsers which don't support ES6 (e.g. Gecko/20100101 Firefox/43.0) throw a syntax error due to instances of 'let' in the standalone package.

The expected behaviour is that 'let' would be 'var' in this package, allowing older browsers to use Babel.

### Environment

N/A

### Possible solution

There are 11 instances of 'let' in this package, here's one: `for(let e=1;e<t.length;e++)`  They are all grouped together right at the top of the file.  By contrast, there are 5,114 instances of 'var', so it's 99.8% ES5 compliant.

### Additional context

This is generating errors for Google's Blockly Games, where we attempt do a client-side transpile of user-created ES6 code to ES5.

Originally posted as #14008 as a discussion more than a month ago, but got no traction.

**Comment by JLHwung** [comment]
The `let` statements are injected rollup commonjs helpers. https://github.com/rollup/plugins/blob/c954336dad283b17ba4fd958e3f7bb57b46e08dc/packages/commonjs/src/helpers.js

**Comment by JLHwung** [comment]
This issue is currently only blocked by two upstream Rollup issues:

https://github.com/rollup/plugins/pull/1082
https://github.com/rollup/plugins/issues/1085
