### ISSUE TITLE
[Bug]: Mocha + Babel does not work with @babel/preset-flow

### ISSUE THREAD

**Issue by cburton-godaddy** [babel/babel#14114]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

https://github.com/cburton-godaddy/babel-mocha-test

Run `yarn` then `DEBUG=* yarn mocha index.test.js`

### Configuration file name

babel.config.json

### Configuration

```
{
    "presets": ["@babel/preset-env", "@babel/preset-flow"]
}
```

### Current and expected behavior

Expected: Should parse the flow code correctly and run the test.

Actual: Throws an error `Unexpected token ':'` This is the first character that is not valid in vanilla JS, but is valid in flow.

I followed this official guide to setup [on this page](https://babeljs.io/setup) babel + mocha. Adding `core-js` or `regenerator-runtime` does not help.

### Environment

```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.8.0/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
  npmPackages:
    @babel/core: ^7.16.7 => 7.16.7
    @babel/preset-env: ^7.16.7 => 7.16.7
    @babel/preset-flow: ^7.16.7 => 7.16.7
    @babel/register: ^7.16.7 => 7.16.7
```

**Comment by nicolo-ribaudo** [comment]
That page suggests using a `.mocharc.yaml` file but I don't see it in your repo :thinking:

**Comment by cburton-godaddy** [comment]
@nicolo-ribaudo  My bad, was a hidden file so didn't upload. It's there now.

**Comment by existentialism** [comment]
IIRC this has to do with ESM?

From:
https://babeljs.io/docs/en/babel-register

> Note: @babel/register does not support compiling native Node.js ES modules on the fly, since currently there is no stable API for intercepting ES modules loading.

**Comment by cburton-godaddy** [comment]
Makes sense, thank you. I will have a look monday how we were doing this before as we have been using Mocha with Flow in Mocha 6 and recently upgraded to Mocha 7 and experienced this issue.

**Comment by cburton-godaddy** [comment]
The issue seems to be with `@babel/preset-flow` not doing what I expect. The ES Modules were being transpiled correctly by Babel, but it would then fail at `@babel/preset-flow`.

I got around this by running `flow-remove-types` and ran my tests on the output, that was sufficient.

Thanks.
