### ISSUE TITLE
[Bug]: babel-plugin-transform-for-of doesn't work with jQuery arrays in IE 11

### ISSUE THREAD

**Issue by Maxim-Mazurok** [babel/babel#14111]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
const someArray = $("div").map((i, e) => e.outerHTML);
for (const element of someArray) {
    console.log(element);
}
```

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": "58",
                    "ie": "11"
                }
            }
        ]
    ],
    "sourceType": "script"
}
```

### Current and expected behavior

Currently, when using for..of with jQuery arrays in IE11, I'm getting "Invalid attempt to iterate non-iterable instance":
![image](https://user-images.githubusercontent.com/7756211/148485338-15272d45-2fc5-444c-abed-11d08cd726f1.png)

Expected: for..of with jQuery arrays in IE11 doesn't throw an error (it doesn't throw in latest Chrome, for example).

### Environment

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 17.1.0 - ~\AppData\Local\nvs\default\node.EXE
    npm: 8.1.3 - ~\AppData\Local\nvs\default\npm.CMD
  npmPackages:
    @babel/core: ^7.11.0 => 7.15.0 
    @babel/plugin-transform-modules-commonjs: ^7.10.4 => 7.15.0 
    @babel/plugin-transform-runtime: ^7.10.4 => 7.15.0 
    @babel/plugin-transform-strict-mode: ^7.10.4 => 7.14.5 
    @babel/preset-env: ^7.11.0 => 7.15.0 
    babelify: ^10.0.0 => 10.0.0 
    eslint: ^7.32.0 => 7.32.0 
    gulp-babel: ^8.0.0-beta.2 => 8.0.0

    @babel/plugin-transform-for-of: 7.16.7
```

### Possible solution

Will post the actual solution that I've found while filing this issue.

**Comment by Maxim-Mazurok** [comment]
Solution: add this to the babel config:

```json5
{
    //...
    "plugins": [
        [
            "@babel/plugin-transform-for-of",
            {
                "allowArrayLike": true
            }
        ]
    ],
    //...
}
```

**Comment by JLHwung** [comment]
Using `assumptions` is better. You don't have to install `transform-for-of`.

```js
{
  assumptions: {
    arrayLikeIsIterable: true
  }
}
```

See https://babeljs.io/docs/en/assumptions#arraylikeisiterable

**Comment by Maxim-Mazurok** [comment]
> Using `assumptions` is better

Thank you, it works and is better indeed!


> You don't have to install `transform-for-of`.

I didn't have to install it with my original solution either. It's not listed in `package.json`, only in `package-lock.json` as a dependency of `@babel/preset-env`
