### ISSUE TITLE
[Bug]: Some SyntaxErrors still ignore startLine option.

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#14123]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
require("@babel/parser").parse("import.meta", { sourceType:"script", startLine: 10 })
```

### Configuration

N/A

### Current and expected behavior

Following up from https://github.com/babel/babel/issues/9015, it appears only some of the SyntaxErrors were fixed to take into account he `startLine` option. As you can see in the example above, it is still possible to get SyntaxErrors with the unadjusted line number. Others however do respect it.

### Environment

- Babel version: 7.16.7
- https://runkit.com/tolmasky/some-syntax-errors-still-ignore-the-startline-option

**Comment by tolmasky** [comment]
It would appear that the problem is that `getLineInfo` (see below): always starts counting from 1. If you pass in `startLine`, then I think the line number issues are fixed:

https://github.com/babel/babel/blob/94af0e5c629b63fa11512b2ea8a8ac81d11a9db5/packages/babel-parser/src/util/location.js#L43

I changed it to the following locally, and I think I'm getting the right line numbers now:

```javascript
export function getLineInfo(startLine : number, input: string, offset: number): Position {
  let line = 1;
  let lineStart = startLine;
  // ...
}
```

Then, in `getLocationAtPosition`: https://github.com/babel/babel/blob/64d116bd6ae1cdb460e4a6b137e89896091707ae/packages/babel-parser/src/parser/error.js#L81

```javascript
getLineInfo(this.state.startLoc.line, this.input, pos);
```

This seems relatively straight-forward, and I can make a PR for this. I will mention that all this seems a bit inefficient however. We already know the correct line number at the time of raising this error, and then re-traverse the entire string to go from position to line number again. Perhaps this is being handled differently in Babel 8, but it just seems weird to start from scratch here, and I think is the "root cause" of this bug: the fact that different parts of the code are keeping track of the line numbers separately. Of course this would be a much larger change, and I'll only be making this two-line change here, but just wanted to point it out as a place for potential future improvement.

**Comment by nicolo-ribaudo** [comment]
Thanks for investigating! I agree: we should simplify location tracking, but for now the "quick fix" is enough.
