### ISSUE TITLE
[Bug]: babel.loadOptionAsync is not a function  , issue while deployment  "@babel/core": "7.5.5",     "@babel/node": "7.5.5"

### ISSUE THREAD

**Issue by akashepik** [babel/babel#14131]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

babel file 
{
    "presets": [
        ["@babel/preset-env"]
    ],
    "plugins": [
        ["@babel/plugin-proposal-export-default-from"]
    ],
    "env": {
        "debug": {
          "sourceMaps": "inline",
          "retainLines": true
        }
      }
  }

Start Script : { "start": "babel-node app.js"}

### Configuration file name

package.json

### Configuration

 {
 devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/node": "7.5.5",
    "@babel/plugin-proposal-export-default-from": "7.5.2",
    "@babel/preset-env": "7.5.5"
}
}

### Current and expected behavior

Hi, while trying to deploy any new node application . Facing 
babel.loadOptionAsync is not a function

### Environment

babel/core: "7.5.5",  
babel/node: "7.5.5",
node : 14.17.6

### Possible solution

Should remove the dependency of missing function

**Comment by nicolo-ribaudo** [comment]
As a workaround, update `@babel/core`.

**Comment by nicolo-ribaudo** [comment]
Can you share the full error stack trace?

**Comment by akashepik** [comment]
![image](https://user-images.githubusercontent.com/78129748/148922298-7736089b-fa00-4f8a-9f4d-4ef7ef40f5ad.png)
