### ISSUE TITLE
One Liners Compact Whitespace

### ISSUE THREAD

**Issue by CWSpear** [babel/babel#1413]
Couldn't come up with a better title, and this is pretty minor, but I noticed that one line statements:

```js
if (bar) return null;
```

are having braces added, and then they collapse all the whitespace underneath them and put the next line on the same line as the closing brace:

Authored:

```js
if (bar) return null;

return foo;
```

Compiled:

```js
if (bar) {
  return null;
}return foo;
```

[Example in the playground](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=true&code=function%20demo()%20%7B%0A%20%20if%20(bar)%20return%20null%3B%0A%0A%20%20%0A%20%20return%20foo%3B%0A%7D)

This may? be related to #1304, which is also a case of collapsing whitespace.

**Comment by sebmck** [comment]
It's related to the `es6.tailCall` transformer exploding nodes as it visits them.

**Comment by sebmck** [comment]
Looks like some code just had to be removed (none added!) to fix this. I've added internal node replacement logic that handles the explosion of statements in block position so it's not longer necessary.

**Comment by CWSpear** [comment]
Awesome! Thanks =)
