### ISSUE TITLE
chore: automate compat-data update

### ISSUE THREAD

**Issue by tony-go** [babel/babel#14138]
### 💻

- [x] Would you like to work on this feature?

### What problem are you trying to solve?

Each time upstream compat-data have been updated,  maintainers have to manually open a pull request.

### Describe the solution you'd like

Use the same approach as https://github.com/babel/babel/blob/main/.github/workflows/update-parser-tests.yml

Having a CRON in GitHub action that will check if there are any updates on the following sources:
- https://github.com/kangax
- "@mdn/browser-compat-data": "^4.0.10",
- "core-js-compat": "^3.20.2",
- "electron-to-chromium": "^1.3.893"

Then, run existing scripts in the repo like `make build-compat-data`

Open a pull request!

Thanks @JLHwung, for the idea 🙌 

### Describe alternatives you've considered

Didn't imagine any alternative here 💩.

**Comment by nicolo-ribaudo** [comment]
Oh this would be awesome!

**Comment by tony-go** [comment]
Sorry for the wait. 

I just struggle with a simple thing: get the last commit for the `gh-pages` [branch](https://github.com/kangax/compat-table/commits/gh-pages) the github API give me on older one :s 😭 

I'll continue my journey and keep you informed.

**Comment by JLHwung** [comment]
You can checkout the latest `compat-data` somewhere, retrieve the HEAD commit SHA1 and inject it to the `download-compat-data.sh`, similar to how we handle `test262`:

https://github.com/babel/babel/blob/b05dad7fed07672514fa6d0d21ce4c1e2c3a6f79/.github/workflows/update-parser-tests.yml#L33-L38

**Comment by tony-go** [comment]
Hey there ! 

Just to say that I accomplish a few things on my side, but nothing to share atm ^^

**Comment by liuxingbaoyu** [comment]
fixed in https://github.com/babel/babel/pull/14248
