### ISSUE TITLE
[Bug]: `Error: Reentrant plugin detected trying to load "<...>.mjs"`

### ISSUE THREAD

**Issue by samualtnorman** [babel/babel#14148]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

`src/foo.js`
```js
export function foo() {
	console.log("foo")
}

export default foo
```

`src/bar.js`
```js
export function bar() {
	console.log("bar")
}

export default bar
```

### Configuration

`babel.config.json`
```json
{
	"plugins": [ "./babel/test.mjs" ],
	"ignore": [ "./babel/test.mjs" ]
}
```

`babel/test.mjs`
```js
export default () => ({})
```

`.babelignore`
```
./babel/test.mjs
```

`package.json`
```json
{
	"name": "babel-test",
	"devDependencies": {
		"@babel/cli": "^7.16.8",
		"@babel/core": "^7.16.7"
	}
}
```

### Current and expected behavior

I would expect this to just work when I run `npx babel src` but I'm getting
```
Error: Reentrant plugin detected trying to load "/home/samual/babel-test/babel/test.mjs". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore.
    at requireModule (/home/samual/babel-test/node_modules/@babel/core/lib/config/files/plugins.js:194:11)
    at requireModule.next (<anonymous>)
    at loadPlugin (/home/samual/babel-test/node_modules/@babel/core/lib/config/files/plugins.js:69:24)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/samual/babel-test/node_modules/@babel/core/lib/config/config-descriptors.js:187:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/samual/babel-test/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/samual/babel-test/node_modules/gensync/index.js:291:5)
    at /home/samual/babel-test/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
```

#### System:
- OS: Linux 5.10 Manjaro Linux

#### Binaries:
- Node: 17.3.1 - ~/.nvm/versions/node/v17.3.1/bin/node
- npm: 8.3.0 - ~/.nvm/versions/node/v17.3.1/bin/npm

#### npmPackages:
- @babel/cli: ^7.16.8 => 7.16.8 
- @babel/core: ^7.16.7 => 7.16.7 

### Additional context

this only happens when the plugin is a `.mjs` file (or `"type": "module"` is set in `package.json`)

**Comment by nicolo-ribaudo** [comment]
This error is only needed to prevent `@babel/register` and `@babel/node` from compiling their own plugins while they are being set up. However:
- this isn't a problem that can happen when running Babel asynchronously (as you are doing), and as you noticed it's buggy in this case
- In Babel 8 we can completely remove the error, since thanks to https://github.com/babel/babel/pull/14025 `@babel/register` doesn't have this problem anymore.
