### ISSUE TITLE
IE issue with setImmediate

### ISSUE THREAD

**Issue by box-turtle** [babel/babel#1414]
Using babel with projects that rely on requestAnimationFrame or setImmediate I see "Invalid Calling Object" errors when viewing in IE 11 on Windows 7.

I believe that when you alias setImmediate in IE you have to first bind the function to a calling object.

Here is the specific issue I hit with the Flummox project: 

https://github.com/acdlite/flummox/issues/167

References:
https://github.com/caolan/async/issues/299
https://github.com/substack/node-browserify/issues/237
https://msdn.microsoft.com/library/gg622930(v=vs.85).aspx

**Comment by loganfsmyth** [comment]
Can you give an example of the code that you are running that triggers this?

**Comment by box-turtle** [comment]
It is a Flummox action class that utilizes async/await. Babel is being run with stage=0.

```
'use strict';

import {Actions} from 'flummox';
import request from '../util/HttpRequest';

export default class MessageActions extends Actions {

  async getAllMessages() {
    try {
      let response = await request.get('/api/messages').exec();
      return response.body;
    } catch (err) {
      console.log(err);
    }
  }

  async getMessage(id) {
    try {
      let response = await request.get(`/api/messages/${id}`).exec();
      return response.body;
    } catch (err) {
      console.log(err);
    }
  }
}
```
After transpilation by webpack, when I load the page in the dev server, the error occurs in the file es6.promise.js at the line:

```
if(isReject || chain.length)asap(function(){
```

**Comment by sebmck** [comment]
This is not an issue with Babel. Please report this on the [core-js repo](https://github.com/zloirock/core-js). cc @zloirock
