### ISSUE TITLE
[Bug]: Why i cannot install this 7.16.9 version ?

### ISSUE THREAD

**Issue by cheungseol** [babel/babel#14152]
### How are you using Babel?

@babel/register or @babel/node

### Current  behavior

I try to install babel@v7.16.9, but fails. Is this version still not published or released ?
https://github.com/babel/babel/releases/tag/v7.16.9

I got the following error:

<img width="772" alt="截屏2022-01-14 下午5 06 06" src="https://user-images.githubusercontent.com/12060295/149488911-27fe6da0-3af2-41c6-bff2-b1e4dfad4577.png">

### Environment

Node: v10.24.1
Babel: 7.16.9 
registry: http://www.npmjs.org

**Comment by nicolo-ribaudo** [comment]
It has been published: https://www.npmjs.com/package/@babel/register/v/7.16.9

It's either a bug with the npm registry (and you should report it to them), or with a non proxy you are using that sits between you and the main registry (for example, a company proxy).
