### ISSUE TITLE
Split es3.property-literals transform into two

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1415]
Google Closure Compiler (in advanced mode) distinguishes between string-literal keys and identifier keys in objects:

```
var x = { 'hello': 1, world: 2 };
f(x.world);
```

gets minified to something like:

```
var a={hello:1,b:2};
f(a.b);
```

The es3.property-literals transform gets rid of quotes for any keys that are valid identifiers. For React we'd like to turn off this behavior but keep the quoting of ES3 reserved words – any chance these can be split into two separate transforms?

**Comment by sebmck** [comment]
It is split into two transformers? `es3.memberExpressionLiterals` and `es3.propertyLiterals`.

**Comment by sebmck** [comment]
Oh wait, nevermind I understand.

**Comment by sebmck** [comment]
I'm unsure about splitting it up into two transformers. Probably best to just remove the behaviour of unquoting non-keyword literals.

**Comment by spicyj** [comment]
Also fine with that.
