### ISSUE TITLE
[Bug]: rest args and deconstruction, error.

### ISSUE THREAD

**Issue by zhangenming** [babel/babel#14156]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
function foo(...[x]) {
 var x = 1
}
```
/repl.js: Duplicate declaration "x"

### Configuration

https://babeljs.io/repl#?browsers=chrome%2033&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUA6LBtAHgXQEpEBvAKEQDcBDAJ0V0QF5EBGMgXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%7D

### Current and expected behavior

Current :error
expected : no error

### Environment

.

### Additional context

.

**Comment by zhangenming** [comment]
same as 
```js
function foo(...{x}) {
 var x = 1
}
```
and
https://babeljs.io/repl#?browsers=chrome%2048&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcCMAKAHgXjQSkQG8AoRANwEMAnRLRHRNEgXxNElgWVQCYMiWFoVIUadBk1btw0eEhRwAzBgB06rCLJVa9RsxZA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%7D

`foo3` No closure is returned
Does this meet the scope requirements of the specification?
thanks

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue?

**Comment by nicolo-ribaudo** [comment]
Sure, thanks!
