### ISSUE TITLE
[Bug]: Position includes index = undefined

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#14182]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

After moving everything over to the `WeakMap` system, I forgot to remove the declaration, so the latest release of Babel includes an `undefined` index property: https://github.com/babel/babel/blob/main/packages/babel-parser/src/util/location.js#L13

Apologies! Should I just do a commit removing it?

### Current and expected behavior

Expected: Shouldn't have an index property
Current: Has an index property.

### Environment

- Babel: 7.16.10

**Comment by nicolo-ribaudo** [comment]
This has now been fully exposed: https://github.com/babel/babel/pull/14174
