### ISSUE TITLE
@jsx pragma broken in latest versions of babel-loader & @babel/core

### ISSUE THREAD

**Issue by MartinSoderholm** [babel/babel#14189]
**I'm submitting a bug report**

**Webpack Version:**
5.66.0

**Babel Core Version**:
7.16.10

**Babel Loader Version**:
8.2.3

**Please tell us about your environment:**
macOS 12.1
node.js 16.9.0

**Current behavior:**
`/** @jsx jsxCreateModel */` pragma is ignored and transpiled code has `React.createElement(...`. Error `React is not defined` is thrown.

**Expected/desired behavior:**
`/** @jsx jsxCreateModel */` pragma should result in transpiled code with my custom method `jsxCreateModel(...`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

I tried downgrading various packages, and to get it working I had to revert to `@babel/core 7.15.5` and `babel-loader 8.2.2`. Only upgrading core to `7.16.0` breaks it. Only upgrading the loader to `8.2.3` breaks it. Upgrading both of them breaks it.

**Comment by JLHwung** [comment]
I can't reproduce this issue. Are you sure the pragma comment is `/** @jsx jsxCreateModel */`? In https://github.com/babel/babel/pull/14012 we limits the `@jsx` pragma comment, i.e. `/** some thing @jsx jsxCreateModel */` is not allowed. But `/** @jsx jsxCreateModel */` is still supported.

**Comment by MartinSoderholm** [comment]
I was about to say “Yes, I'm sure”, but then I checked and apparently it was `/** @jsx jsxCreateModel **/`, for some reason.

So I guess the ending `**/` is no longer supported 😊.

Thanks for your help 👍

**Comment by nicolo-ribaudo** [comment]
Uh well, we should probably add it back since it doesn't seem too uncommon (especially because multiline dockblock comments end with `**/`).
