### ISSUE TITLE
ES6 Date parsing

### ISSUE THREAD

**Issue by mj1856** [babel/babel#1418]
The behavior or parsing a date or date+time string to a `Date` object (using the `new Date(string)` constructor, or `Date.parse(string)` function) is changed in ES6.   This isn't currently accounted for in babel transpiled code.  Should it be?

[ES6 §20.3.1.16](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-date-time-string-format)
> If the time zone offset is absent, the date-time is interpreted as a local time.

[ES5.1 §15.9.1.15](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15):
> The value of an absent time zone offset is "Z".

To get ES6 behavior out of ES5, the string would need to be mutated to be interpreted in local time.  The transpiler would have to be careful only to do this for the specific use cases affected.

ES6 | ES5
------|------
`new Date("2014-12-31")`  |   `new Date("2014/12/31")`
`new Date("2014-12-31T01:23:45")`  |   `new Date("2014/12/31 01:23:45")`
`new Date("2014-12-31T01:23:45Z")`  |  *no change*
`new Date("2014-12-31T01:23:45-05:00")`  |  *no change*

Note, the hyphens are replaced with slashes, but still kept in year/month/day order to prevent internationalization ambiguities.  Also note the `T` removed.  Also note that ECMAScript *only* defines the ISO8601/RFC3339 format, leaving everything else implementation specific.  It just happens that all major implementations support the formats I showed.

**Comment by monsanto** [comment]
This would need to be solved in core-js before we could add support in the `runtime` transformer. cc @zloirock

**Comment by sebmck** [comment]
There's no way this can really be solved on the Babel side and as @monsanto said, it's something that would need to be added to `core-js`. Can you please repost this issue on the [core-js repo](https://github.com/zloirock/core-js)? Unsure about the difficulty required as AFAIK `core-js` doesn't actually parse the dates which would require a lot of work to get complete support (lots of legacy compat) and would bloat the default `core-js` build up significantly.
