### ISSUE TITLE
[Bug]: Random segfaults when running webpack and using @babel/core 7.16.10

### ISSUE THREAD

**Issue by Artur-** [babel/babel#14186]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

No idea how to reproduce it. It reproduces in random places in our CI builds, starting from yesterday after the release of 7.16.10

### Current and expected behavior

Apparently we are using Babel through workbox which is used through webpack which is run from Java
```
├─┬ workbox-build@6.4.1
│ ├─┬ @babel/core@7.16.10
```

The only expectation I have is that `webpack` should finish the build instead of segfault. Assuming here that exit value 139 means segmentation fault.

### Environment

- Babel: 7.16.10
- Node 16.0.0

### Possible solution

Downgrading to `@babel/core` `7.16.7` resolves the problem

### Additional context

https://github.com/vaadin/flow/runs/4882425225?check_suite_focus=true is an example of a failed build but it does not provide much more information

https://github.com/vaadin/flow/runs/4882529524 is the same build but with babel 7.16.7

**Comment by jlowcs** [comment]
I might be experiencing a similar issue in our circleci builds. I'm not seeing a segfault, but the build sometimes fails right away without any information from webpack.

![image](https://user-images.githubusercontent.com/3777724/150521019-70be148d-5fc1-43c5-8ef6-8c855afc9857.png)

This is a node build (webpack target is `node`) and it fails about 10% of the time. Our browser build seems to work fine though.

**Comment by jlowcs** [comment]
We also noticed that a segfault appeared in our eslint CI job since bumping babel. eslint uses `@babel/eslint-parser`.

![image](https://user-images.githubusercontent.com/3777724/150521695-c80ab014-0564-45d9-856c-67c582e891b1.png)

**Comment by Artur-** [comment]
I was unable to get a core dump out from our CI yet. Maybe posting or analyzing that will give more clues

**Comment by jlowcs** [comment]
For reference, here are our version changes from our babel bump that introduced the issues:

@babel/core: 7.16.7 => 7.16.10
@babel/helper-create-class-features-plugin: 7.16.7 => 7.16.10
@babel/parser: 7.16.8 => 7.16.10
@babel/plugin-proposal-private-methods: 7.16.7 => 7.16.11
@babel/plugin-transform-runtime: 7.16.8 => 7.16.10
@babel/preset-env: 7.16.8 => 7.16.11
@babel/traverse: 7.16.8 => 7.16.10

**Comment by nicolo-ribaudo** [comment]
Could any of you try using [`patch-package`](https://www.npmjs.com/package/patch-package) or [Yarn 2/3's `patch:` protocol](https://yarnpkg.com/features/protocols#patch), or a script that you run on CI after installing your dependencies but before running webpack, to comment out line 23 from https://unpkg.com/browse/@babel/core@7.16.10/lib/config/files/import-meta-resolve.js?

That line _might_ cause https://github.com/nodejs/node/issues/35889 if for some reason webpack is running inside a Node.js [`vm` context](https://nodejs.org/api/vm.html), and without more details (or better, if someone manages to reproduce the error outside of CI and can share the repository that I can use to debug the problem) it's the only clue I have.

**Comment by jlowcs** [comment]
I just created a branch with that patch. Now, since the segfault doesn't happen every time, I'm gonna have to run the CI multiple times to confirm the issue has actually disappeared.

**Comment by jlowcs** [comment]
so far, my eslint job has run without failing 5 times out of 5 with that patch.

**Comment by jlowcs** [comment]
10/10 on the eslint job, and 5/5 on the node build, so it looks like that patch does fix the issue.

**Comment by Artur-** [comment]
I will see if I can monkey patch this and test also. Seems like `patch-package` does not support `pnpm` so I cannot use that

**Comment by Artur-** [comment]
After a couple of failing patch attempts I think I now agree with @jlowcs that removing 
```
try {
 import_ = require("./import").default;
} catch (_unused) {}
```

resolves the issue

**Comment by nicolo-ribaudo** [comment]
@Artur- thanks! If you have time, could you also test if what I wrote in the description of https://github.com/babel/babel/pull/14192#pullrequestreview-859720848 works too (rather than deleting that try/catch)?

**Comment by Artur-** [comment]
With this change https://github.com/vaadin/flow/pull/12778/commits/94f26a075b1db2c6f3cacbbc2e34584338bd0ec8 all I see is `[webpack-cli] ReferenceError: polyfill is not defined`. Should `polyfill` be something else like `_importMetaResolve`?

**Comment by nicolo-ribaudo** [comment]
Oh yes right, it should be `_importMetaResolve.resolve` :sweat_smile:

**Comment by Artur-** [comment]
[That fix](https://github.com/vaadin/flow/pull/12778/commits/adc0b887f0831bfe59befe23d5258e1897f4c5c9) seems to also resolve the issue

**Comment by nicolo-ribaudo** [comment]
I'm releasing 7.16.12 with the workaround for this V8 bug.

**Comment by jlowcs** [comment]
thank you!
