### ISSUE TITLE
[v8 bug] Modern v8 doesn't support static class fields named `name`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#14181]
### 💻

- [x] Would you like to work on this feature?

### What problem are you trying to solve?

https://bugs.chromium.org/p/v8/issues/detail?id=12421

### Describe the solution you'd like

We probably need a bugfix plugin for that

### Describe alternatives you've considered

/

**Comment by nicolo-ribaudo** [comment]
Node.js is not affected and it looks like they are waiting for a v8 fix before upgrading: https://github.com/nodejs/node/pull/40907. However, Chrome/Edge 97 might be affected.

The first step is to add a `compat-table` test for this bug, if anyone wants to help.

**Comment by ljharb** [comment]
https://github.com/kangax/compat-table/pull/1784
