### ISSUE TITLE
Cannot export function

### ISSUE THREAD

**Issue by asdf404** [babel/babel#1419]
Hi. In some reason `export function myfunc() {...}` doesn't work in part of my app.
So I've tried to rewrite it to:

```js
function myfunc() {...}

export default {myfunc}
```

And it works when I'm import it in tests, but not in another file. It very strange.

You can look at my app [here](https://github.com/asdf404/rouchdb/tree/fd7195034b406abc19d77a1dd08492881197b07d) (link to broken commit).

Problem in file `src/routes.js`. It exports as `undefined` even if I set `export default {...}`.

I'm using mocha for tests and I get an error `TypeError: Cannot read property 'generate' of undefined`.

[Here](https://travis-ci.org/asdf404/rouchdb/jobs/60945858) you can see a test log. 

I'm using babel v5.2.6.

Thanks.

**Comment by sebmck** [comment]
`export default {myfunc}` is equivalent to `export default { myfunc: myfunc }`. What is it exactly that you're trying to do?

**Comment by asdf404** [comment]
I've tried to export function from module `A` for using in module `B` . But when I'm import module `A` from module `B` it `undefined`:

```js
// A.js
export function myfunc() {}

//B.js
import A from 'A.js'

A.myfunc() // error 
console.log(A) // undefined
```

But it worked [before](https://github.com/asdf404/rouchdb/blob/7ba3b9ccad66059c09da3b980ec4fa3f0370e8ad/src/routes.js).

P.S. Sorry, english it's not my native language.

**Comment by sebmck** [comment]
Use this then: 

```javascript
export default function myfunc() {}
```

When you do

```javascript
import A from 'A.js'
```

you're requesting the **default** export that you haven't defined.

**Comment by sebmck** [comment]
Also, please see the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks :)
