### ISSUE TITLE
Store imported items in own variable instead of obj['default'] etc.

### ISSUE THREAD

**Issue by pozadi** [babel/babel#1420]
Currently when an `import` statement is used the imported items are stored in a object, is it possible to store them in own variables?

For instance, this snippet:
```
import {b} from 'foo';
b();
```
is compiled to:
```
...
_b.b();
```

For import default it's even worse:
```
import b from 'foo';
b();
↓
...
_b2['default']();
```

This has bad performance consequences as a function call like this works slower than a normal call — `b()`: http://jsperf.com/obj-default-vs-fn

**Comment by sebmck** [comment]
See #1341 and  #1337. It's necessary to support ES6 live bindings.

**Comment by pozadi** [comment]
Ah, I see. Too bad, guess, I stuck with hacks like this https://github.com/pozadi/kefir/commit/aa1578c3583393ff8e168b6a778afae46a7572c8 , as it has a really bad influence in my case.

Thanks for so fast response, btw!

**Comment by monsanto** [comment]
Maybe we should disable live bindings in loose mode?

**Comment by pozadi** [comment]
That would be great, if it possible!

**Comment by sebmck** [comment]
@monsanto Too much of a dramatic change and the performance impact of a simple member expression is **extremely small**.

**Comment by pozadi** [comment]
In my case the performance impact is pretty noticeable:

Without hack:
```
stream.map(id)
----------------------------------------------------------------
Kefir x 8,668,823 ops/sec ±1.94% (67 runs sampled)
```

With hack:
```
stream.map(id)
----------------------------------------------------------------
Kefir x 10,468,228 ops/sec ±1.96% (65 runs sampled)
```

Basically, as [jsperf shows](http://jsperf.com/obj-default-vs-fn) a call with a member expression  ~2 times slower. The real impact depends on how hot this code is, but I think it might be pretty noticeable especially if one has a highly modular codebase with a lot of functions imported.

In my case only one instance of this issue slows down whole lib by about 20%, as every event dispatch causes `_Event['default'](...)` call.

**Comment by pozadi** [comment]
Perhaps the reason why it is slower not because the member expression itself, but because `foo.bar()` is a function call with `foo` as context.

**Comment by pozadi** [comment]
For those who go here after me: another workaround is to simply use CommonJS modules system instead of ES6 one.

For instance:
```js
const {foo, bar} = require('baz');

↓

'use strict';
var _require = require('baz');
var foo = _require.foo;
var bar = _require.bar;
```
