### ISSUE TITLE
[Bug]:  Babel transform from ESM to CommonJS not working in AWS

### ISSUE THREAD

**Issue by daxaymakwana** [babel/babel#14214]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const core = require("@babel/core");
const vm = require("vm");
const exceptions = require("./shared/exceptions");
const jsCodeBabelConfig = {
    plugins: ['@babel/plugin-transform-modules-commonjs'],
    presets: [['@babel/preset-env', { targets: { node: true } }]],
};
const handler = async function () {
    const jsCode = `import _ from 'lodash';const data = [1, 2, new Date()];export function run() {return _.map(data, String);}`
    try {
        const transpiledData = await core.transformAsync(jsCode, jsCodeBabelConfig);
        if (!transpiledData || !transpiledData.code) {
            throw new exceptions.BadRequestException('Invalid JS code');
        }
        try {
            const script = new vm.Script(transpiledData.code);
            const runFunc = script.runInContext(vm.createContext());
            const func = runFunc.run ? runFunc.run : runFunc;
            const result = await func();
            return { result };
        }
        catch (error) {
            console.error('Error in running js code', error);
            return { error: true, msg: 'Error in running js code' + error }
        }
    }
    catch (error) {
        if (error instanceof exceptions.BadRequestException) {
            return { error: true, msg: error.getResponse() }
        }
        return { error: true, msg: 'Internal Server Error' }
    }
};
exports.handler = handler;
```

### Current and expected behavior

# Context
Above code is written for the AWS Lambda, where it is currently running. Since security is not my concern I can execute code at run time based on request.
I am using babel to convert ESM code into CommonJs code since Node16 is not supported by AWS Lamda.
For easy understanding I have added **_jsCode_** as static but in realtime it is dynamic.

# Problem
I am getting below error whenever I am running function.
```
ERROR	Error in running js code Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@babel/plugin-transform-modules-commonjs' imported from /var/task/babel-virtual-resolve-base.js
    at new NodeError (/var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2552:5)
    at packageResolve (/var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3208:9)
    at moduleResolve (/var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3242:18)
    at defaultResolve (/var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3281:13)
    at /var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3304:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:63:103)
    at _next (/var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:194)
    at /var/task/dist/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:364
    at new Promise (<anonymous>) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
I have make sure that I installed ```@babel/plugin-transform-modules-commonjs``` but still getting that error everytime.
### Note:- I have tried this solution in AWS EC2 and it is working great. But we need this behaviour in AWS Lambda.

# Expected Behaviour
Babel should convert code into Commonjs.

### Environment

- @babel/core : "^7.16.12",
- @babel/plugin-transform-modules-commonjs : "^7.16.8",
- @babel/preset-env : "^7.16.11"
- NodeJs:- 14.18.3
- AWS Lambda:- arm64

**Comment by nicolo-ribaudo** [comment]
You can manually load the plugins, to completely bypass Babel's plugins resolution:
```js
const jsCodeBabelConfig = {
    plugins: [require('@babel/plugin-transform-modules-commonjs')],
    presets: [[require('@babel/preset-env'), { targets: { node: true } }]],
};
```

---

The reason you are getting this error is that Babel resolves the plugins/presets starting from the cwd. I think that you are running your script from `/var/task`, but the `node_modules` folder (which contains `@babel/plugin-transform-modules-commonjs`) is inside `/var/task/dist`.

You could move `node_modules` to `/var/task` to match the common structure of Node.js projects, however the proper "fix" to make Babel work with your directory structure is to explicitly specify where Babel should start looking for plugins from, using the [`cwd`](https://babeljs.io/docs/en/options#cwd) option:
```js
const jsCodeBabelConfig = {
    cwd: "/var/tast/dist", // or maybe __dirname
    plugins: ['@babel/plugin-transform-modules-commonjs'],
    presets: [['@babel/preset-env', { targets: { node: true } }]],
};
```

**Comment by daxaymakwana** [comment]
Hi @nicolo-ribaudo,
Thanks for the answer and great explanation.
You answer resolved my issue.
