### ISSUE TITLE
Support ES Modules in @babel/preset-typescript

### ISSUE THREAD

**Issue by LandonSchropp** [babel/babel#14219]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

*Apologies if this is captured elsewhere. I'm trying to sort out all of the moving parts with configuring Babel/TypeScript, so I may have missed something.*

I'm setting up a TypeScript Node.js project, and I'd like to be able to do the following:

* Use TypeScript.
* Use the `import`/`export` syntax in my files.
* Use top-level `await` (requires `"type": "module"` in `package.json`)
* Use Jest (requires Babel)

### Describe the solution you'd like

Ideally, I'd be able to have one TypeScript configuration and use that for everything, including running my project, type checking, and running my tests. Here's what I'd expect the configuration to look like:

``` json
// babel.config.json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}
```

``` json
// package.json
{
  "type": "module",
  ...
}
```

### Describe alternatives you've considered

Prior to adding Jest as a requirement, I was using `ts-node`. However, with Jest, I need to be able to use Babel. Ideally, I'd be able to use the same configuration and tools for everything, to ensure the code works consistently.

**Comment by nicolo-ribaudo** [comment]
Hi! Sorry this issue didn't get noticed :slightly_smiling_face: 

I think all the four requirements you have should work, but you might need to tell Babel not to compile ESM to CJS:
```json
{
  "presets": [
    ["@babel/preset-env", { "modules": false }],
    "@babel/preset-typescript"
  ]
}
```

However, you will need to compile your files ahead of time (using `@babel/cli`): Babel does not support running "at runtime" yet like `ts-node` when using native ESM, because Node.js doesn't have a stable ESM loader API yet.

**Comment by LandonSchropp** [comment]
Not a problem at all! Thanks for the reply. 🙂

Ah, I wasn't aware of the `modules` setting in `preset-env`. That's really helpful to know.

> Babel does not support running "at runtime" yet like ts-node when using native ESM, because Node.js doesn't have a stable ESM loader API yet.

That makes sense. Fingers crossed that lands sometime soon.

Thanks!
