### ISSUE TITLE
Reduce bundle size of `@babel/codeframe`

### ISSUE THREAD

**Issue by TimvdLippe** [babel/babel#14213]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

Reduce the bundle size of projects that depend on `@babel/codeframe`

### Describe the solution you'd like

We are working on reducing the bundle size of Prettier, tracked in https://github.com/prettier/prettier/issues/12144

In https://github.com/prettier/prettier/issues/12144#issuecomment-1024994274 @dakmor suggested to switch Chalk in `@babel/codeframe` to [colorette](https://github.com/jorgebucaran/colorette), which should reduce the size of the package by 19kB (as Chalk pulls in 20kB and colorette is 1kB)

Can we remove large dependencies from `@babel/codeframe` and reduce its disk footprint?

### Describe alternatives you've considered

Keep Chalk and keep a large bundle

**Comment by nicolo-ribaudo** [comment]
`colorette` only supports Node.js 10+, and unfortunately Babel 7 still supports Node.js 6.

We can consider it to Babel 8, comparing it to updating chalk from v2 to v5.

**Comment by nicolo-ribaudo** [comment]
Ok let me try something :eyes:

**Comment by nicolo-ribaudo** [comment]
Uh, apparently we export a whole `chalk` instance from `@babel/highlight` (a dependency of `@babel/code-frame`), making it part of the public API :confused: 

We cannot remove chalk until Babel 8, even if we find a library that supports Node.js 6.

**Comment by daKmoR** [comment]
right - now that you mention it... I remembered seeing that in code last time I investigated... was the reason I did not even open an issue to discuss it back then, as I figured it will never happen 🙈. 

too bad... 😭

**Comment by TrySound** [comment]
https://github.com/alexeyraspopov/picocolors has enough node support as already used by browserslist the dependency of babel. There is also a shim for browsers which may simplify bundling.

**Comment by daKmoR** [comment]
anything that is less than let's say 5kB would be an improvement 👍
