### ISSUE TITLE
[Bug]: no binding is found when traverse a FunctionDeclaration node

### ISSUE THREAD

**Issue by SmallStoneSK** [babel/babel#14216]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import traverse from '@babel/traverse';
import * as parser from '@babel/parser';

const code2ast = (code) => {
  const ast = parser.parse(code, {
    sourceType: 'module',
    plugins: ['jsx', 'classProperties', 'decorators-legacy', 'exportDefaultFrom'],
  });
  return ast;
};

const code = `
  function foo() {}
  const a = 1;
  console.log('this is foo');
`;

const ast = code2ast(code);

traverse(ast, {
  FunctionDeclaration(path) {
    console.log(path.scope.bindings);  // {}
  },
  VariableDeclaration(path) {
    console.log(path.scope.bindings);  // { foo: xxx, a: xxx }
  },
});
```

### Current and expected behavior

the output of `path.scope.bindings` when traverse a FunctionDeclaration node or a VariableDeclaration node should be the same

### Environment

- @babel/traverse 7.16.8
- @babel/parser 7.16.8
- Node: 15
- OS: MacOS 10.14.2
- Monorepo: no

**Comment by nicolo-ribaudo** [comment]
`path.scope` refers to the scope of the current path or, if it doesn't exist, to the outer scope.

In the `FunctionDeclaration` visitor, `path.scope` is thus the function scope, and there are no bindings defined inside the function. Variables don't have their own scope, so `path.scope` refers to the program scope where you defined the function and the variable.
