### ISSUE TITLE
[Bug]: @babel/plugin-transform-destructuring not transform function parameters

### ISSUE THREAD

**Issue by SmallStoneSK** [babel/babel#14221]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`)

### Input code

```js
import * as babel from '@babel/core';
import transformDestructuringPlugin from '@babel/plugin-transform-destructuring';

const code = `
  function foo({a, b}) {
    const {c, d} = a;
  }
`;

const options = {
  plugins: [[transformDestructuringPlugin]],
};

const main = async () => {
  const ret = await babel.transformAsync(code, options);
  console.log(ret.code);
};

main();
```

### Current and expected behavior

- current

```js
function foo({
  a,
  b
}) {
  const c = a.c,
        d = a.d;
}
```

- expected

```js
function foo(_ref) {
  var _ref = {a, b};
  var a = _ref.a,
       b = _ref.b;
  const c = a.c,
        d = a.d;
}
```

### Environment

- @babel/core 7.16.7
- @babel/plugin-transform-destructuring 7.16.7
- Node: 15
- OS: MacOS 10.14.2
- Monorepo: no

**Comment by nicolo-ribaudo** [comment]
I know it's confusing but you also need `@babel/plugin-transform-parameters`.

**Comment by SmallStoneSK** [comment]
@nicolo-ribaudo 
Thank you, I also found this plugin in @babel/preset-env and tried it successfully~
