### ISSUE TITLE
[Bug]: Today's release breaks for any build using node < 10.0.0

### ISSUE THREAD

**Issue by BradMcDev** [babel/babel#14228]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

- use any version of node < 10.0.0
- include @babel/core in your build
- it will fail due to jridgewell/resolve-uri now-requiring >= node 10.0.0

### Current and expected behavior

**Current:**

- As of today's release, ampproject/remapping requires jridgewell/resolve-uri, but the latest release of jridgewell/resolve-uri (3.0.3) requires node >= 10.0.0
  - error @jridgewell/resolve-uri@3.0.3: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.17.0"
- Any project using @babel/core and previous versions of node are now having breaking changes & are required to version lock.
- Was this release supposed to require node 10.0.0, and should we be expected to version-lock to fix this?

**Expected**

- Our build should not have randomly started breaking from this babel release, in a perfect world :)

### Environment

- Babel: v7.17.0
- Node: v8.17.0
- Yarn: v1.15.2

### Possible solution

- Update jridgewell/resolve-uri to be compatible with older versions of node

**Comment by jridgewell** [comment]
I can fix this with a new release of `@jridgewell/resolve-uri`. The >= 10 requirement is unnecessary in recent releases.

**Comment by BradMcDev** [comment]
> I can fix this with a new release of `@jridgewell/resolve-uri`. The >= 10 requirement is unnecessary in recent releases.

That'd be fantastic, thank-you so much @jridgewell!

**Comment by jridgewell** [comment]
Done. If you update to v3.0.4, I've tested down to node v6.

**Comment by BradMcDev** [comment]
Our build is working again- thank-you so much for the quick turn-around on this, @jridgewell. Closing this out!

**Comment by nicolo-ribaudo** [comment]
Thanks for the quick fix! I'm surprised we didn't catch it, because we test Babel on Node.js 6.
