### ISSUE TITLE
Sorting Object.freeze 'd array produces weird results

### ISSUE THREAD

**Issue by dazld** [babel/babel#1422]
Possibly missing something here, but this seems a bit weird.

Fully understand that const ref to a mutable object (in this case an array) perhaps doesn't make a lot of sense on its own.

env:
Node: 0.10.33 (with babel/register)
Babel: 5.2.6

```js

const strs = ['zz','ee','DD','dd','PP'];

function sortFirstLetter (a,b){
    // whatever, some sort function
    a = a.toLowerCase().charCodeAt(0);
    b = b.toLowerCase().charCodeAt(0);

    if (a === b) {return 0;}
    else if (a > b) {return 1;}
    else {return -1;}
    
}


var times = 10;
while (times){
    strs.sort(sortFirstLetter);
    console.log(...strs)
    times--;
}
console.log(' -- reset counter, freeze then try to sort again');
times = 10;
Object.freeze(strs);
while (times){
    strs.sort(sortFirstLetter);
    console.log(...strs)
    times--;
}

```

Produces following output: 

```

DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
DD dd ee PP zz
 -- reset counter, freeze then try to sort again
PP zz DD ee dd
ee dd PP DD zz
DD zz ee PP dd
PP dd DD ee zz
ee zz PP DD dd
DD dd ee PP zz
PP zz DD ee dd
ee dd PP DD zz
DD zz ee PP dd
PP dd DD ee zz

```

..am I missing something?

**Comment by sebmck** [comment]
Not sure what the bug is that you're reporting. Is it that you can modify constants?

**Comment by dazld** [comment]
No, that the sort produces deterministic output before it is frozen, and seems to go crazy after.

**Comment by sebmck** [comment]
How is this a Babel bug?

**Comment by dazld** [comment]
Was just playing with babel, and saw this behaviour. I'll try without.

**Comment by monsanto** [comment]
This has nothing to do with Babel, it's an issue with node 0.10. On io.js it throws an error (like it should)

**Comment by dazld** [comment]
Thanks for the quick replies. Got it!
