### ISSUE TITLE
[Bug]: TypeError: _core.types.isStaticBlock is not a function

### ISSUE THREAD

**Issue by AarRidho** [babel/babel#14230]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```jsx
import React from 'react';
import ReactDOM from 'react-dom';

export class Portal extends React.Component<{ selector: string }> {
    private element: HTMLElement;

    componentDidMount() {
        this.element = document.querySelector(this.props.selector);
        this.forceUpdate();
    }

    render() {
        if (this.element === undefined) {
            return null;
        }

        return ReactDOM.createPortal(this.props.children, this.element);
    }
}
```

### Current and expected behavior

Current: Today's release breaks Next.js ```next build``` pipeline

Expected: Today's release should not affect pipeline build just like yesterday

### Environment

- Babel: v7.7.7 (core)
- Webpack: v4.41.5
- Node: v12.18.0
- Next.js: v9.5.5

### Additional context

Pipeline message:
![image](https://user-images.githubusercontent.com/18082030/152299871-cf4a65fa-a43a-4a93-9505-120ffcb15186.png)

**Comment by nicolo-ribaudo** [comment]
As a workaround, update `@babel/types`.

**Comment by AarRidho** [comment]
Updating `@babel/types` fix the issue for me

**Comment by nicolo-ribaudo** [comment]
Fixed in `@@babel/helper-create-class-features-plugin@7.17.1`; I'm releasing it now.

**Comment by imyelo** [comment]
> Fixed in `@babel/helper-create-class-features-plugin@7.17.1`; I'm releasing it now.

still break in @babel/plugin-proposal-class-static-block

https://github.com/babel/babel/blob/0058b7f/packages/babel-plugin-proposal-class-static-block/src/index.ts#L56
