### ISSUE TITLE
[Bug]: When using legacy decorators, accessing a class in a static method of said class gives the non-decorated class

### ISSUE THREAD

**Issue by Agapurnis** [babel/babel#14245]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[Babel REPL Link](https://babeljs.io/repl#?browsers=%0A&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgziA2CmB0w4EMBOAKAlAbgFCkhgWhAHN0AiAIWQCNZoACABWmQE9TUQBXMAEwqZcuAC7sADrEYBhNhAgzwEUah7BRIVIwA8AFUYBeRsjDsAfEcZhYAd0bp4TtKQgAuE2YDaAXUxHLPREAMz4NAEtwRgARWFBUZE1UADFkDS12B38Ab1xGfMZUWFEeVDBGULAIqNj4xK0HAhU1dNQPU3YcvIKeptV1JK8KfjitRNhBHyt-2DxunvyikrLGJGQFRlgAD1FYAQhV5X7WxlyF88PIY6SHJ3gXd092Xy6Lt8YIHikMO4ecefePVEAAtwhAhiM6rtJtM1LMAYD8k0iPASOQKEori1RJFysBkBJlhMAIRCBEXAC-5PyFJMB3EUhAwUuzQGWgBVKpuAAArUxklUq12Fh8PIDnpYCo5OsDmcCgB6ABUisYAHVgcUNdoQWDVmLGMD1ox6HtGJD-RNGIr5QCJDxaNBwsAPqJEk6zaMEtCrMFkNAILAAUqVerNbBtaCDmsNuErqZgNJDQcTXijtjLcFuABbEweqGWvrYhrW232x3O81ey3GX3--Glh3ulRu51Z5AAa2kWFO5IAkMi4KiyJQAJIAOQAyiPogBRRgTvQAQT0I5kjAAsjO9AAJADy0QoABpGBKpWL4JoJ6pY-RMMI3n1GLHm1VpMYbPZT6JpQo8A_lCiaKjpO05zguy6rhuW57tEjCAMgEsgADKLhOE4xDOMi7gASsuM4HseX4_uCwyeuMkz3hcA7EMOFDjlOs7zkuK5rpuO77vBjB0UuY4yHOyRYbu67oZhOF6HhR5PnGr4QqR0IUH41KFMUpTlM-rqvhyuAUnM-BHCy1zVtYdgnpK35ilgeCPpmIBZuumogPwViEeebadhZIhUUO6K7gAqno9FzjIyGocJyGiSOu5jhJzkyheIBXqgN5YMInlARQvn-aBSEoWhs5BYu4WRRx-UhXl2G4fhJlnjKMn5uRumEIOaUZQF2WlRhYUQUVCHoJhk56FhPkyGJ0T-Fxi48XxAlCWVonicehYDBMtUWvVqU0S1WUlblHUFV1Y4ceg4HMVBbGjZx_UTbxjD8YJwnlSNEnWbZ9n8CtVb1UAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-2%2Ctypescript&prettier=false&targets=&version=7.17.1&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.16.7&assumptions=%7B%7D)

### Configuration

N/A – See [Babel REPL](https://babeljs.io/repl#?browsers=%0A&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgziA2CmB0w4EMBOAKAlAbgFCkhgWhAHN0AiAIWQCNZoACABWmQE9TUQBXMAEwqZcuAC7sADrEYBhNhAgzwEUah7BRIVIwA8AFUYBeRsjDsAfEcZhYAd0bp4TtKQgAuE2YDaAXUxHLPREAMz4NAEtwRgARWFBUZE1UADFkDS12B38Ab1xGfMZUWFEeVDBGULAIqNj4xK0HAhU1dNQPU3YcvIKeptV1JK8KfjitRNhBHyt-2DxunvyikrLGJGQFRlgAD1FYAQhV5X7WxlyF88PIY6SHJ3gXd092Xy6Lt8YIHikMO4ecefePVEAAtwhAhiM6rtJtM1LMAYD8k0iPASOQKEori1RJFysBkBJlhMAIRCBEXAC-5PyFJMB3EUhAwUuzQGWgBVKpuAAArUxklUq12Fh8PIDnpYCo5OsDmcCgB6ABUisYAHVgcUNdoQWDVmLGMD1ox6HtGJD-RNGIr5QCJDxaNBwsAPqJEk6zaMEtCrMFkNAILAAUqVerNbBtaCDmsNuErqZgNJDQcTXijtjLcFuABbEweqGWvrYhrW232x3O81ey3GX3--Glh3ulRu51Z5AAa2kWFO5IAkMi4KiyJQAJIAOQAyiPogBRRgTvQAQT0I5kjAAsjO9AAJADy0QoABpGBKpWL4JoJ6pY-RMMI3n1GLHm1VpMYbPZT6JpQo8A_lCiaKjpO05zguy6rhuW57tEjCAMgEsgADKLhOE4xDOMi7gASsuM4HseX4_uCwyeuMkz3hcA7EMOFDjlOs7zkuK5rpuO77vBjB0UuY4yHOyRYbu67oZhOF6HhR5PnGr4QqR0IUH41KFMUpTlM-rqvhyuAUnM-BHCy1zVtYdgnpK35ilgeCPpmIBZuumogPwViEeebadhZIhUUO6K7gAqno9FzjIyGocJyGiSOu5jhJzkyheIBXqgN5YMInlARQvn-aBSEoWhs5BYu4WRRx-UhXl2G4fhJlnjKMn5uRumEIOaUZQF2WlRhYUQUVCHoJhk56FhPkyGJ0T-Fxi48XxAlCWVonicehYDBMtUWvVqU0S1WUlblHUFV1Y4ceg4HMVBbGjZx_UTbxjD8YJwnlSNEnWbZ9n8CtVb1UAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-2%2Ctypescript&prettier=false&targets=&version=7.17.1&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.16.7&assumptions=%7B%7D) link. Note that decorators should use the legacy specification, which is not preserved in the link.

## Expected

1. Accessing a class in a static method of said class should return the decorated class.
2. The static method `make` of `TestClass` should return a `TestClass` instance whose property `decorated` is `true`.
3. Running `TestClass.toString()` in the context of the static method `make` of `TestClass` should result in the following, which (disregarding formatting differences) is the same as what was output by running `TestClass.toString()` outside of the static method.
```js
class extends constructor {
    constructor(...args) {
        super(...args);
        this["decorated"] = true;
        console.log("Construction captured!");
    }
}
```

This is the same behavior that is achieved by running the same code in the [TypeScript playground](https://www.typescriptlang.org/play?#code/MYewdgziA2CmB0w4EMBOAKAlAbgFCkhgWhAHN0AiAFQE8AHWAZWFQEs6AXAAgAVpkapVCACuYACYVMuXB3qwuAYX4QIi8BA6oRwDiFRcAPFS4BeLsjA0AfGa5hYAdy7p4btKQgAuC1YDaALqYZrZUMgBmYrqs4FwAIrCgqMh6qABiyLr6NC7BAN64XEVcqLAcIqhgXJFg0bEJSSn6LgSa2lmoPpY0+YXF-a1aOql+FOKJ+imwkgF2Q7B4ff1FpeWVXEjIqlywAB4csBIQGxpDHVwFy1cnkGepLm7wHt6+NIG9159cECIMGI-PHBLL79DgAC1YEFG40aBxmc20C2BIKKrSI8BI5Ao6lu7Q4MSqwGQnAq0wAhFJkdcAL5UorUizHOQMEDhG5tYb6YG02m4AACDUmqQyHRoWHwKmOVFgmmUW2Ol2KAHoAFQqrgAdTBZW1BnBkI2kq4YK2XAARrBDlwYULplwVUrgXQRGboKxgN8OCl3daJsk4XZwshoBBYMDVeqtTrYHqIcdNttWLdLMAFCbjharYM8XbwsIALYWX2wu3ZzkGB1Ol1uj02-128xBkNIquun2ab0e-PIADWCiwFypAEg0XAMWRKABJAByjEncQAolxGFQAIJUSeKLgAWQXVAAEgB5OIUAA0XGlssl8D0jC0SfImGkn0GXCTHdqCnMDmcl44ctUPAXw0dFMSnWd5yXFd103Hc9yPOIuEAZAIlAAGVXRhGHiBdFEPAAldcFxPc8-wAqExj9KYZmfa5R2ICcKBnOdF2XNcNy3XcD2PZCuCYtdp0UJc0jww9t2w3CCKoIizzfZNP2hSi4QoII6RKMoKiqd8vU-blcGpRZ8FOdk7gbewnAvGV-0lLA8FfPMQHzbcdRAcQ7FI69uz7GyZDo8csUPABVKhmKXRR0Mw8T0MkydD2nGT3PlG8QDvNgwEfaRfLAihAuCyC0IwrDFzC1dotinjioior8MI4iLKveUFJLajDMIMcspykL8sqnCopgsqUPQXDZyoPCAsUKS4mCPjVwEoSRLEqrJOk88y10aZGttZrMoYjq8oqwqepKvrpx49BoPYuCuMm3jhpmwSuGE0TxOqiaZPsxznPEDb62aoA) using TypeScript's decorator implementation.

## Actual

1. Accessing a class in that static method of said class returns the non-decorated class.
2. The static method `make` of `TestClass` returns a `TestClass` instance whose property `decorated` is `false`.
3. Running `TestClass.toString()` in the context of the static method `make` of `TestClass` results in a stringified function that is different from doing it outside of the context of the static method `make`.

I was notified that the second problem can be resolved by using `new this` instead of `new TestClass`, but this is not ideal as it is expected that either of these would produce the same behavior, and this could cause issues when decorator-based APIs are used and consumers are unaware of this requirement.

### Environment

N/A - Used REPL.

### Screenshots of the current behavior using Babel versus the desired behavior using TypeScript.

<details><summary>Click to expand comparison of property values</summary>
<p>
<img src="https://user-images.githubusercontent.com/4649286/152666310-55b0de1f-15fd-4cac-b810-7740af69253e.png" width="80%" height="80%">
</p>
</details>

<details><summary>Click to expand comparison of stringified classes</summary>
<p>
<img src="https://user-images.githubusercontent.com/4649286/152666305-c133663b-a31c-41fd-8ac7-caef2b8e60b5.png" width="60%" height="60%">
</p>
</details>

### Other Information

- This behavior is reproducible outside of the REPL.
- [TypeScript Playground Link](https://www.typescriptlang.org/play?#code/MYewdgziA2CmB0w4EMBOAKAlAbgFCkhgWhAHN0AiAFQE8AHWAZWFQEs6AXAAgAVpkapVCACuYACYVMuXB3qwuAYX4QIi8BA6oRwDiFRcAPFS4BeLsjA0AfGa5hYAdy7p4btKQgAuC1YDaALqYZrZUMgBmYrqs4FwAIrCgqMh6qABiyLr6NC7BAN64XEVcqLAcIqhgXJFg0bEJSSn6LgSa2lmoPpY0+YXF-a1aOql+FOKJ+imwkgF2Q7B4ff1FpeWVXEjIqlywAB4csBIQGxpDHVwFy1cnkGepLm7wHt6+NIG9159cECIMGI-PHBLL79DgAC1YEFG40aBxmc20C2BIKKrSI8BI5Ao6lu7Q4MSqwGQnAq0wAhFJkdcAL5UorUizHOQMEDhG5tYb6YG02m4AACDUmqQyHRoWHwKmOVFgmmUW2Ol2KAHoAFQqrgAdTBZW1BnBkI2kq4YK2XAARrBDlwYULplwVUrgXQRGboKxgN8OCl3daJsk4XZwshoBBYMDVeqtTrYHqIcdNttWLdLMAFCbjharYM8XbwsIALYWX2wu3ZzkGB1Ol1uj02-128xBkNIquun2ab0e-PIADWCiwFypAEg0XAMWRKABJAByjEncQAolxGFQAIJUSeKLgAWQXVAAEgB5OIUAA0XGlssl8D0jC0SfImGkn0GXCTHdqCnMDmcl44ctUPAXw0dFMSnWd5yXFd103Hc9yPOIuEAZAIlAAGVXRhGHiBdFEPAAldcFxPc8-wAqExj9KYZmfa5R2ICcKBnOdF2XNcNy3XcD2PZCuCYtdp0UJc0jww9t2w3CCKoIizzfZNP2hSi4QoII6RKMoKiqd8vU-blcGpRZ8FOdk7gbewnAvGV-0lLA8FfPMQHzbcdRAcQ7FI69uz7GyZDo8csUPABVKhmKXRR0Mw8T0MkydD2nGT3PlG8QDvNgwEfaRfLAihAuCyC0IwrDFzC1dotinjioior8MI4iLKveUFJLajDMIMcspykL8sqnCopgsqUPQXDZyoPCAsUKS4mCPjVwEoSRLEqrJOk88y10aZGttZrMoYjq8oqwqepKvrpx49BoPYuCuMm3jhpmwSuGE0TxOqiaZPsxznPEDb62aoA), which results in the expected behavior.

**Comment by Agapurnis** [comment]
I'm willing to attempt potentially solving this if someone could give me some pointers regarding where to look.
I don't have much time and might end up giving up, so don't take this as any form of commitment 😅 

If this issue has been present for some time (I'm not sure if it was the latest update to decorator package), I do have concerns over how/whether or not this *should* be fixed. Changing this could perhaps cause issues with already existing usage of decorators, but I find the idea of there being a discrepancy between the runtime behavior of TypeScript-transpiled code and Babel-transpiled code greatly concerning as well.

I would love a comment on whether or not I should take a look or not, as it seems like quite a conundrum; one that I'm not qualified to make a decision on.

**Comment by nicolo-ribaudo** [comment]
The old decorators proposal (https://github.com/wycats/javascript-decorators) did not specify if the class binding should point to the decorated or undecorated class. There was a discussion about it (https://github.com/wycats/javascript-decorators/issues/79), but it was not resolved.

Since Babel has been supporting legacy decorators for years, I'm hesitant to change this just to align with TS. Now that we support the new decorators proposal, I'd like to consider support for the older ones as frozen (except for obvious bugs/crashes).

I suggest using a workaround, like
```js
let A = @decorator class {};
```

**Comment by Agapurnis** [comment]
> Since Babel has been supporting legacy decorators for years, I'm hesitant to change this just to align with TS. Now that we support the new decorators proposal, I'd like to consider support for the older ones as frozen (except for obvious bugs/crashes).

I can definitely see why, as any change could be considered breaking and likely mess up packages that depend on this behavior.

>
> I suggest using a workaround, like
> 
> ```js
> let A = @decorator class {};
> ```

I'll give that a try, but it does seem unfortunate that this needs to be done. One of the reasons I'm using decorators in a library I'm creating is that integration should be as seamless as possible, not requiring extending any classes (as a base class may already need to be extended from in a setup being used).

The usage of a workaround like this brings up some of the previous concerns I had regarding workaounds:
> [...] but this is not ideal as it is expected that either of these would produce the same behavior, and *this could cause issues when decorator-based APIs are used and consumers are unaware of this requirement.*

I suppose there could be some sort of setting in the decorator plugin that enables this, but I'm not sure if something like that is worth it for a niche requirement such as this, or if its feasable/considerable.

(I am actually quite surprised that this seemingly hasn't caused any issues before)

> [...] I'm hesitant to change this just to align with TS. [...]
> [...] I'd like to consider support for the older ones as frozen [...]

Would you suggest that I close this issue then? I'm not too sure myself, as to me personally this does feel like unintended behavior.

**Comment by nicolo-ribaudo** [comment]
This is not the only difference between Babel and TS: `babel-plugin-transform-typescript-decorators` could be a new plugin that fully supports TS decorators to provide maximum compatibility.

However, [decorators might be promoted to Stage 3 in March](https://github.com/tc39/agendas/blob/main/2022/03.md), and Stage 3 is usually when TS starts implementing ECMAScript features. The best strategy for now is probably to wait until march and see if the new decorators proposal is accepted.

**Comment by Agapurnis** [comment]
TypeScript is [committed to the implementation of stage-3 decorators](https://github.com/microsoft/TypeScript/issues/48885). Can’t wait for things to hopefully all be standard. :)
