### ISSUE TITLE
[Bug]: unable to use addExternalDependency

### ISSUE THREAD

**Issue by goatandsheep** [babel/babel#14252]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Code is here: https://github.com/goatandsheep/react-native-dotenv/blob/64cfaec582900712eac53d3f3cdf1c079ecc7c61/index.js

it's based on the following sample code:

```javascript
function plugin(api) {
  const dotEnvFilename = `${process.cwd()}/.env`;

  const env = api.cache.using(() => fs.readFileSync(dotEnvFilename, "utf8"));
  api.addExternalDependency(dotEnvFilename);
  
  return {
    visitor: {}...
  }
}
```

### Configuration file name

.babelrc

### Current and expected behavior

Currently the following errors:

* the `cache` function gets "Cannot change caching after evaluation has completed"
* and the `addExternalDependency` function gets "Cannot add property 0, object is not extensible"

Expecting no errors

### Environment

- Babel Version : v7.17.2
- Node: v14.17.5
- Yarn: 1.22.15

### Additional context

I'm testing out the `addExternalDependency` function for the new version [v7.17.2](https://github.com/babel/babel/releases/tag/v7.17.2) and the function is present in my library but I'm getting some errors. Babel has worked previously and it works when I do not have the new function so my guess is my usage of the function is incorrect.

**Comment by nicolo-ribaudo** [comment]
Caching must be configured in the plugin factory (before line 23 on your code), since it tells Babel when it needs to reinstantiate your plugin.

I see you need to access the options in order to configure the cache: you can get them from the second factory parameter, after `api`.

**Comment by goatandsheep** [comment]
Thank you! This helped https://github.com/goatandsheep/react-native-dotenv/pull/288
