### ISSUE TITLE
[Bug]: `import type {} from 'some-module'` results in invalid typescript

### ISSUE THREAD

**Issue by nicojs** [babel/babel#14250]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import type { } from 'some-module';
```

### Configuration

No configuration file

### Current and expected behavior

Using this code:

```js
const { parseAsync } = require("@babel/core");
const generate = require("@babel/generator").default;

async function main() {
  const parsed = await parseAsync('import type {} from "some-module";', {
    filename: "main.ts",
    presets: [require.resolve("@babel/preset-typescript")],
    plugins: [],
  });
  console.log(
    generate(parsed, {sourceMaps: false}).code
  );
}

main().catch(console.error);
```

Results in: `import type "some-module";`

Which is invalid typescript.

### Environment

- Babel: `7.16.12`

### Possible solution

I've noticed that the AST for:

```ts
import type {} from "some-module";
```

And 

```ts
import type "some-module";
```

is the exact same. See https://astexplorer.net/#/gist/3a6d7dc99689e175f667747004a015f4/2c079662c137fb0f3af1be0f7c04920a9d6a199a

I see 3 solutions:

1. Output generate code for the AST as `import type {} from "some-module";`
2. Add AST properties so we know the difference between the 2
3. Add support for `import type "some-module";` to typescript (and flow script?)

### Additional context

This got reported in StrykerJS: https://github.com/stryker-mutator/stryker-js/issues/3386

We're using babel to parse and output files as is, after which `tsc` might need to run.

**Comment by nicolo-ribaudo** [comment]
We should always print `{}` in this case.

**Comment by JLHwung** [comment]
@The-x-Theorist You can add a test in `packages/babel-generator/test/fixtures/typescript`, the `input` is `import type { } from 'some-module';` and the output should be the same.

**Comment by The-x-Theorist** [comment]
Do we have to change the AST for type only importSpecifier to add the braces in the generator?

**Comment by JLHwung** [comment]
I don't think we need to change the AST. We can print `braces` when `node.importKind` is `"type"` even if `specifiers.length` is 0:

https://github.com/babel/babel/blob/e06c0998e5f207ae5ce1eafcaf188e7ddf1fc5e1/packages/babel-generator/src/generators/modules.ts#L204

May also check if we should handle this issue in `typeof` import and `export type {} from "some-module"`.

**Comment by The-x-Theorist** [comment]
@JLHwung Can you suggest an example for `typeof` import to check?

**Comment by nicolo-ribaudo** [comment]
`node.importKind === "typeof"`, when using `import typeof U from "x";` with flow.
