### ISSUE TITLE
[Bug]: Parser throws when var declaration and function declaration in class static block

### ISSUE THREAD

**Issue by overlookmotel** [babel/babel#14257]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
class X {
  static {
    var x;
    function x() {}
  }
}
```

[REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEAa0G8BQ1oQC5nQS2Ilq0AbmAE7QAeA3AagGYCuAdsDgPZOUAUAlIgL4FB_IA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=&version=7.17.2&externalPlugins=&assumptions=%7B%7D)

### Configuration

n/a

### Current and expected behavior

I believe that the above code is legal. It happily runs in NodeJS.

Babel's parser throws an error `Identifier 'x' has already been declared`.

This only applies within a class static block. The following parses correctly (when `sourceType: 'script'`):

```js
var x; function x() {}
class X {
  foo() { var x; function x() {} }
  static foo() { var x; function x() {} }
}
function f() { var x; function x() {} }
() => { var x; function x() {} };
function f2() { 'use strict'; var x; function x() {} }
() => { 'use strict'; var x; function x() {} };
```

[REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=G4QwTgBAHg3BBmBXAdgYwC4EsD2zoAoBKCAbwF8AoVAGxAGc6IANUiiBbbI0iUSWBCgw48UbuQiV2ddCCyoOXYiV7hocJGiy4CyspIqVNwnfHGr-GodtHj9lbgF4AfDz7rBWkbtL2YFYxsEACZzAHJEOgBTCBkwTAwwuHcBQO8xPQMnVxUI6Nj0eMTktVTrdLtJGCA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=&version=7.17.2&externalPlugins=&assumptions=%7B%7D)

### Environment

```
System:
  OS: macOS 10.15.7
Binaries:
  Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
  npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
npmPackages:
  @babel/core: ^7.17.2 => 7.17.2
  @babel/generator: ^7.17.0 => 7.17.0
  @babel/helper-module-transforms: ^7.16.7 => 7.16.7
  @babel/helper-plugin-utils: ^7.16.7 => 7.16.7
  @babel/parser: ^7.17.0 => 7.17.0
  @babel/plugin-transform-arrow-functions: ^7.16.7 => 7.16.7
  @babel/plugin-transform-modules-commonjs: ^7.16.8 => 7.16.8
  @babel/plugin-transform-react-jsx: ^7.16.7 => 7.16.7
  @babel/plugin-transform-strict-mode: ^7.16.7 => 7.16.7
  @babel/traverse: ^7.17.0 => 7.17.0
  @babel/types: ^7.17.0 => 7.17.0
  babel-plugin-dynamic-import-node: ^2.3.3 => 2.3.3
  eslint: ^7.32.0 => 7.32.0
  jest: ^27.5.1 => 27.5.1
```

### Additional context

Happy to work on a PR. But could someone please point in right direction? I'm not at all familiar with the parser.

**Comment by JLHwung** [comment]
The error is thrown from https://github.com/babel/babel/blob/76dd49197af69a312283145cae2403ff2bd8961b/packages/babel-parser/src/util/scope.js#L152

When Babel is parsing a static block, it will push a `SCOPE_STATIC_BLOCK`
https://github.com/babel/babel/blob/76dd49197af69a312283145cae2403ff2bd8961b/packages/babel-parser/src/parser/statement.js#L1746

I think we should handle that in
https://github.com/babel/babel/blob/76dd49197af69a312283145cae2403ff2bd8961b/packages/babel-parser/src/util/scope.js#L103

Alternatively, we can enable `SCOPE_FUNCTION` flag instead(I didn't try). Intuitively the static block is a function body so `SCOPE_FUNCTION` may be applied, too.

**Comment by nicolo-ribaudo** [comment]
@overlookmotel I'm assigning this to you since you selected "Would you like to work on a fix?". If you are not interested anymore just leave a comment!

**Comment by Yokubjon-J** [comment]
I would be happy to take on this issue @nicolo-ribaudo .

**Comment by overlookmotel** [comment]
@Yokubjon-J I'd be very happy if you did! I was going to, but I'm unfamiliar with the parser code base, so will probably take me a while.

**Comment by Yokubjon-J** [comment]
please assign me, @nicolo-ribaudo. i have started working on the issue.

**Comment by Yokubjon-J** [comment]
For some unknown reason, I am getting the error `false != [object Object] in .ast` after running test inside fixtures subdirectory (one in `\babel-parser\test\fixtures\es2015\class\static-block\input.js` another in `\babel-parser\test\fixtures\static\class-static-method\input.js`, shown in the picture below, their contents are not the same). 
I think the test file directories are organized correctly, I would like to know your suggestion.
![image](https://user-images.githubusercontent.com/67240021/156349268-90b9077c-68ab-4d15-b951-659ff90e455b.png)

**Comment by nicolo-ribaudo** [comment]
That might be a bug in our test runner; what does it say if you set the `OVERWRITE=true` environment variable when calling running out tests?

**Comment by Yokubjon-J** [comment]
Thanks, it worked! Now, I am back to the issue.

**Comment by Yokubjon-J** [comment]
when i write tests inside already created folders, they execute normally.
But after creating my own new folder inside fixtures, (`\babel-parser\test\fixtures\static\class-static-block`) i get the error `Error: ENOENT: no such file or directory, open 'C:\Users\User\Desktop\Projects\babel\packages\babel-parser\test\fixtures\static\class-static-block\input.js\output.json'`. Would you like to suggest something about it?
![image](https://user-images.githubusercontent.com/67240021/156933992-29b5b0b1-fa56-464f-8f90-b879cd0950da.png)

**Comment by JLHwung** [comment]
@Yokubjon-J Please run `yarn` to install dependencies. If you are developing on Windows, you can also run `make bootstrap` in the embedded Linux, mingw64 may not be well supported since we don't run CI on mingw64 environment.

**Comment by Yokubjon-J** [comment]
#https://github.com/babel/babel/pull/14336

**Comment by Yokubjon-J** [comment]
#14336

**Comment by Yokubjon-J** [comment]
[https://github.com/babel/babel/pull/14336](url)

**Comment by overlookmotel** [comment]
@Yokubjon-J Just want to say thanks loads for fixing this.

**Comment by Yokubjon-J** [comment]
@overlookmotel thank you also for letting me have this bug (to fix)!
