### ISSUE TITLE
i have following issue in yarn

### ISSUE THREAD

**Issue by reshma651999** [babel/babel#14258]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/cjs/puppeteer/node/install' is not defined by "exports" in /Users/kite/projects/video/remotion/sample/node_modules/puppeteer-core/package.json

### Configuration file name

package.json

### Current and expected behavior

create video

### Environment

node v 14

**Comment by nicolo-ribaudo** [comment]
I don't think that that error is thrown by Babel.
