### ISSUE TITLE
[Bug]: Babel/node got different results  with node.js when using caller.js

### ISSUE THREAD

**Issue by chlshown** [babel/babel#14254]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

// test.js
const caller = require('caller');
function fn() {
    console.log('-----', caller(1))
}
fn();

### Configuration file name

package.json

### Configuration

...
  "dependencies": {
    "caller": "^1.0.1"
  },
  "devDependencies": {
    "@babel/core": "7.14.3",
    "@babel/node": "7.14.2"
  }
...

### Current and expected behavior

// Using node to execute
node test.js 
// ----- /Users/lchen29/Projects/Demo/simple/test.js

// Using babel-node to execute
yarn bebel-node test.js 
//----- /Users/lchen29/Projects/Demo/simple/node_modules/caller/index.js 

### Environment

Node: 14.15.4
yarn : 1.22.17
 @babel/core: "7.14.3",
 @babel/node: "7.14.2"

### Possible solution

The issue happens after core-js upgrade to 3.20.0, it's fine on 3.19.3

**Comment by nicolo-ribaudo** [comment]
Unfortunately the `caller` package assumes that `Error` has not been polyfilled. I suggest opening an issue in that package's repository asking to support polyfilled error constructors.
