### ISSUE TITLE
[Bug]: Can not install @babel/helper-explode-assignable-expression

### ISSUE THREAD

**Issue by nam-hle** [babel/babel#14265]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

`npm i @babel/helper-explode-assignable-expression`

### Current and expected behavior

Current error:
```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@babel/helper-explode-assignable-expression/-/helper-explode-assignable-expression-7.16.7.tgz
npm ERR! 404 
npm ERR! 404  '@babel/helper-explode-assignable-expression@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Expect succeed installing

### Environment

- Babel version: N/A
- Node: v14.17.0
- npm: v6.14.13
- OS version: MacOS v10.15.6
- Monorepo: no

### Additional context

I come from `storybook` user while trying to run `sb init` through `npx sb init --builder webpack5 `

**Comment by nicolo-ribaudo** [comment]
Please report this to npm. The package was published (https://www.npmjs.com/package/@babel/helper-explode-assignable-expression), so this looks like a registry bug.
