### ISSUE TITLE
[Bug]:  Cannot find module 'babel-plugin-jsx'

### ISSUE THREAD

**Issue by social-uni** [babel/babel#14260]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
import { parse } from "@babel/core";

const sourceCode = `
    console.log(1);

    function func() {
        console.info(2);
    }

    export default class Clazz {
        say() {
            console.debug(3);
        }
        render() {
            return <div>{console.error(4)}</div>
        }
    }
`;

const ast = parse(sourceCode, {
  sourceType: 'unambiguous',
  plugins: ['jsx']
});
```

### Configuration file name

package.json

### Configuration

package.json
```
{
  "name": "babeldemo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/core": "^7.17.2"
  }
}

```

### Current and expected behavior

expected excute success

i excute this code by @babel/parse is worker, use @bebel/core  parse is not work

### Environment

 "@babel/core": "^7.17.2"

**Comment by JLHwung** [comment]
`babel.parser` accepts a Babel option while `babelParser.parse` accepts Parser options. See

https://babel.dev/docs/en/options

https://babel.dev/docs/en/babel-parser

In your case, you should install `@babel/plugin-syntax-jsx` and use it as the `babel.parser` plugin.
