### ISSUE TITLE
export * should not export default

### ISSUE THREAD

**Issue by guybedford** [babel/babel#1426]
I believe this involves changing the `_interopRequireWildcard` to exclude the default property.

In addition, in the System output, we should output the following setter code:

```javascript
for (var _key in _q) {
  if (_key !== 'default')
    _export(_key, _q[_key]);
}
```

instead of:

```javascript
for (var _key in _q) {
  _export(_key, _q[_key]);
}
```

Apologies for not catching this one sooner.

**Comment by guybedford** [comment]
Unfortunately this is going to break jspm.... so I'll have to lock Babel at the last patch for a few releases. Any chance we can hold this back for a little while to let me catch up?

**Comment by sebmck** [comment]
@guybedford Sure, I'll pull it over to a branch and I can merge when you give the :+1:.

**Comment by guybedford** [comment]
Thanks so much! Unfortunately there's no easy workaround, so this will have to wait for the grand re-architectural, which may be a while yet. Hate to push back on something like this, but as it is breaking, perhaps it can be queued for version 6?

**Comment by sebmck** [comment]
Sure, not planning Babel v6 for quite a while now anyway (nothing breaking that I want to introduce) so it should align nicely.

**Comment by guybedford** [comment]
:+1:
