### ISSUE TITLE
also emit type arguments with --emitDecoratorMetadata

### ISSUE THREAD

**Issue by hypno2000** [babel/babel#1427]
At the moment:
```ts
class Article {
   @Relation
   author: OneRelation<Author>;
}
```
emits:
```js
__metadata('design:type', OneRelation)
```

My suggestion is that that instead of just type it would also include the type args.

Maybe something like this:
```js
__metadata('design:type', {type: OneRelation, args: [{type: Article: args: []}])
```

With the latter i don't have to repeat myself in decorator that this is a one relation to article as i have already specified this in type. 

Thanks,
Reio

**Comment by sebmck** [comment]
Wrong repo?

**Comment by hypno2000** [comment]
yep :D sorry
