### ISSUE TITLE
Integration with sublime build system

### ISSUE THREAD

**Issue by surganov** [babel/babel#1428]
I want to get `console.log()` messages in Sublime's console. It works perfectly fine with `node` or `iojs`:

```js
{
  "cmd": ["/usr/local/bin/iojs", "$file"],
  "selector": "source.js",
  "quiet": true
}
```

![screen shot 2015-05-04 at 00 08 16](https://cloud.githubusercontent.com/assets/2229334/7446945/b1a1d29c-f1f1-11e4-8b02-0670eb6155db.png)

But I don't see any messages when I'm using babel-node:

```js
{
  "cmd": ["/usr/local/bin/babel-node", "$file"],
  "selector": "source.js",
  "quiet": true
}
```

I have the latest version of `babel` and `babel-node`.

**Comment by sebmck** [comment]
Can you create an example repo with exact steps to reproduce please

**Comment by surganov** [comment]
1. Open _Sublime Menu → Tools → Build System → New Build System..._
2. Run `$ which babel-node` (I got `/usr/local/bin/babel-node`)
3. Paste this code, with respect to the previous step
```js
{
  "cmd": ["/usr/local/bin/babel-node", "$file"],
  "selector": "source.js"
}
```
4. Save file as `babel.sublime-build`
5. Create js file, write something like `console.log(`Hello, ${ 'World' }`);`, hit save.
6. Choose `babel` build system within that file via _Sublime Menu → Tools → Build System → babel_
7. Hit ⌘B and open build results via _Sublime Menu → Tools → Build Result → Show Build Result_

**Comment by surganov** [comment]
Also, I got error mesage
```
[Finished in 0.1s with exit code 127]
[cmd: ['/usr/local/bin/babel-node', '/Users/surganov/Desktop/some.js']]
[dir: /Users/surganov/Desktop]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

**Comment by sebmck** [comment]
This is an environment setup problem and not a bug or issue with Babel.

> Value 127 is returned by `/bin/sh` when the given command is not found within your `PATH` system variable and it is not a built-in shell command. In other words, the system doesn't understand your command, because it doesn't know where to find the binary you're trying to call.

**Comment by alawatthe** [comment]
I just tried it, and everything works on my machine (babel-node --version 5.2.6, Sublime Text build 3083).

**Comment by surganov** [comment]
Sorry, I mistook this behaviour because `node` and `iojs` are working with these settings.

I found why this isn't working: because of first line in `babel-node` source file:
```
#!/usr/bin/env node
```
http://stackoverflow.com/a/20077620/1638307

So, I found the solution for my machine:
```
{
  "cmd": ["babel-node", "$file"],
  "selector": "source.js",
  "path": "/usr/local/bin:$PATH",
  "quiet": true
}
```

**Comment by surganov** [comment]
Finally I can test my ES6 code snippets inside sublime. Thanks for help!
