### ISSUE TITLE
Why does Babel shim Object.keys?

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#1429]
When I have `optional=runtime` set, this:

```
export default function buildQueryString(data) {
	return Object.keys(data)
		.map(key => `${key}=${encodeURIComponent(data[key])}`)
		.join('&');
}
```

Is compiling to:
```
var _Object$keys = __webpack_require__(/*! babel-runtime/core-js/object/keys */ 13)['default'];

exports.__esModule = true;
exports['default'] = buildQueryString;

function buildQueryString(data) {
  return _Object$keys(data).map(function (key) {
    return '' + key + '=' + encodeURIComponent(data[key]);
  }).join('&');
}

module.exports = exports['default'];
```

Is the `babel-runtime/core-js/object/keys` import necessary? I'm just using `optional=runtime` to reduce the repetition of all the Babel helpers, I don't expect it to change the behaviour of the code in other ways.

**Comment by sebmck** [comment]
See the [runtime docs](http://babeljs.io/docs/usage/runtime/). Modularising the helpers isn't the only thing it does. In this case `Object.keys` needs to be replaced in order to ensure spec compliancy with it excluding symbols.

**Comment by Daniel15** [comment]
@sebmck  The documentation doesn't mention that it will always pull in helper methods. I did read that page, but thought it'd only pull in the stuff required (ie. only if I'm using Map, Set, or Promise). Can I modularise the helpers without pulling in other unnecessary code?

**Comment by sebmck** [comment]
It realiases all the builtins that it needs to that are included in the [definitions.json](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/other/runtime/definitions.json). It's not unnecessary and is required since it's to ensure that symbols aren't included in the returned keys.

**Comment by Daniel15** [comment]
>  It's not unnecessary and is required since it's to ensure that symbols aren't included in the returned keys.

I'm not using symbols in any of my code though, so why would I need that?

**Comment by zloirock** [comment]
`Object.keys` replaced for support primitives as target, not for `Symbols` - they already are not enumerable.

**Comment by loganfsmyth** [comment]
@Daniel15 What's the core of the complaint here? It'd be a huge pain to have to manually specify which things to convert with `runtime`, and there is no way for Babel to know whether you are using the primitive `keys` support that @zloirock mentioned. At the end of the day, the code should behave identically.

**Comment by sebmck** [comment]
@zloirock Ah ok, my bad. Figured it was somehow related as I recall changes being done in relation to symbols with many `Object` methods.

**Comment by Daniel15** [comment]
@zloirock 

> What's the core of the complaint here? 

I'm trying to remove all unnecessary code from my bundled JavaScript and I noticed these modules Babel is pulling in. Disabling the runtime removes them but also introduces repetition since the helpers functions aren't modularised. I was just wondering if there's a way to have modularised helper functions without pulling in things like this Object.keys shim since I don't need them.

**Comment by zloirock** [comment]
@Daniel15 with runtime - no way, w/o - [custom build `core-js`](https://github.com/zloirock/core-js#custom-build) w/o module `es6.object.statics-accept-primitives` or you can [require only needed modules](https://github.com/zloirock/core-js#commonjs).
