### ISSUE TITLE
[Bug]: Property redefining leads to it being set to undefined

### ISSUE THREAD

**Issue by nowifi4u** [babel/babel#14291]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
interface BaseOptions {
  test1?: boolean;
}

abstract class BaseClass {
  public readonly options: BaseOptions;

  public constructor (options: BaseOptions) {
    this.options = options;

    console.log('BaseClass this', this);
  }
}

interface ChildOptions extends BaseOptions {
  test2?: number;
}

class ChildClass extends BaseClass {
  public readonly options!: ChildOptions;

  public constructor (options: ChildOptions) {
    super(options);

    console.log('ChildClass this', this);
  }
}

export const t = new ChildClass({
  test1: true,
  test2: 2,
});
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "parserOpts": {
    "strictMode": true
  },
  "sourceMaps": "inline",
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": { "node": "current" },
        "modules": "commonjs"
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }], "@babel/plugin-proposal-class-properties"]
}
```

### Current and expected behavior

Current behavior:
`_defineProperty` is present in the generated code in the constructor after super call
```js
class BooleanResolvableType extends _Base.BaseType {
  constructor(options) {
    super(options);

    _defineProperty(this, "options", void 0);

    console.log('BooleanResolvableType constructor options', options);
    console.log('BooleanResolvableType constructor this', this);
  }

  async run(val, context) {
    console.log('BooleanResolvableType run this.options', this.options);
    const lval = val.toLowerCase();
    return await this.options.resolver(lval, context);
  }
}
```

Expected behavior:
_defineProperty should not be present in the constructor for the fields defined in a parent class

### Environment

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.0
    npm: 8.3.1
  npmPackages:
    @babel/plugin-proposal-class-properties: 7.16.7
    @babel/plugin-proposal-decorators: 7.17.2
    @babel/preset-env: 7.16.11
    @babel/preset-typescript: 7.16.7
    eslint: 8.6.0
    jest: 27.4.7

**Comment by nicolo-ribaudo** [comment]
This is the expected behavior to match what JavaScript does. You can test it by running this code in your browser's console:
```js
class A {
  x = 1
}
class B extends A {
  x
}

console.log("x is: " + new B().x); // undefined
```

The current TypeScript behavior of ignoring `x` in `B` is wrong, but you can enable the `useDefineForClassFields` in your TS config to make it work correctly.

If you want to ignore `x` in the subclass, you can use the `declare` modifier:
```ts
class B extends A {
  declare x;
}
```

[TS playground](https://www.typescriptlang.org/play?useDefineForClassFields=true#code/MYGwhgzhAECC0G8BQ1oA9oF5oEYkF8lRIYAhaAUzQBcKA7AExnmVTQKSPCmlIH0GFAGYBLOhUo16TOIhSpog4gCcJaANwEgA)
