### ISSUE TITLE
[Feat]: Support `"type": "module"` in `package.json` for `@babel/node`

### ISSUE THREAD

**Issue by ITenthusiasm** [babel/babel#14312]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

It seems that as of `node@12`, ECMAScript modules have been stably supported in Node.js. I noticed that in #11108, the [concern](https://github.com/babel/babel/issues/11108#issuecomment-583610872) was that support was only experimental. However, that is no longer the case. Is there a chance we could have `"type": "module"` supported soon in `@babel/node`?

### Describe the solution you'd like

Just normal support for using ECMAScript modules with `@babel/node`. I imagine it could just rely on what node does when it comes to this.

### Describe alternatives you've considered

I'm not sure what Babel's constraints are, but I was assuming there wouldn't be the need for any alternatives if it could just rely on what the user's version of node does for imports. (Please excuse my ignorance if that's inaccurate.)

### Documentation, Adoption, Migration Strategy

Assuming my assumptions stand, the docs would only need to be updated to show that ECMAScript modules are supported out of the box for the node versions that support them.

> `@babel/node` will support either CommonJS modules or ECMAScript modules, depending on the value you supply to `type` in your `package.json`. Note that if you want to use both simultaneously, you may want to use [babel-plugin-transform-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) instead.

**Comment by nicolo-ribaudo** [comment]
> However, that is no longer the case.

It's still experimental: https://nodejs.org/api/esm.html#loaders

They are actively developing loaders at https://github.com/nodejs/modules/, and it looks like there are already different planned changes that diverge from the current experimental implementation.

**Comment by ITenthusiasm** [comment]
Ah, that's unfortunate. :pensive: I thought they were stable based on the docs I was reading about both module systems. My mistake! Thanks for the info!
