### ISSUE TITLE
[Bug]: RegExp named captures are not transpiled correctly when creating Regexp using `new Regexp(/%val/)` syntax 

### ISSUE THREAD

**Issue by Sc222** [babel/babel#14325]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Babel REPL:
[link](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=PTAEBUAsEsGdQE4FMDmSAeAHUdQDkB5cUAdwQENNMkATHAO1AAMB9MygJVQFEsAKAJRNQ5enRIB7BAGt45eNHoAXJGNoAoAMYT6sJYh5YAjKAC8oekhKguKXpj4AiPgH4APCr0A-AHQAqAUcBAG51dRAIGHhkNCwceHYqWgZmNgpMW3tBYVFxKVkRBWVVGg1tXX0Y-wAmM1BgVw8kb38BYFDwsChcGIxsXETqOkVUxMz-IRExUEh5UABXNQAzRWSmFAQJecxYJi0dPQM7LABmOstrcYcG908lXwDgELDyw7uAZSUEOsdYCQBbJBKGD0FCOUKvCQAGyQPihEhQfA-Xx8_3ISk0kD4VSwAh8Gy2O2ekJhcIRSOaSk-CFR6Mx2MMmGqeIJ21gxIO0Nh8MRyJpaIxWJxmBOLM2bJC9TAyCU8wQugWy1WNCAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=true&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D)

### Current and expected behavior

I've created RegExp using 3 variants noted in [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#literal_notation_and_constructor):
```JavaScript
const regExp1 = new RegExp("(?<test>.*)");
const regExp2 = /(?<test>.*)/;
const regExp3 = new RegExp(/(?<test>.*)/);
```

Babel did not wrap regExp1 in `_wrapRegExp` but applied that rule to regExp2 and regExp3.

As a result named groups work in runtime for `regExp1` and `regExp2` but return undefined for syntax used when creating `regExp3`.

Demo console outputs before and after transpilation:
https://stackblitz.com/edit/js-f1qtt8?file=index.js

I expect Babel to transpile  `new RegExp(/(?<test>.*)/)` such way, that named groups will not be undefined for match that uses this RegExp.

### Environment

 System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.14.6 => 7.16.7
    @babel/plugin-proposal-decorators: ^7.14.5 => 7.16.7
    @babel/plugin-transform-named-capturing-groups-regex: ^7.16.8 => 7.16.8
    @babel/plugin-transform-runtime: ^7.16.8 => 7.16.8
    @babel/preset-env: ^7.14.7 => 7.16.7
    @babel/preset-react: ^7.14.5 => 7.16.7
    @babel/preset-typescript: ^7.14.5 => 7.16.7
    babel-eslint: ^10.1.0 => 10.1.0
    babel-loader: ^8.2.2 => 8.2.3
    babel-plugin-parameter-decorator: ^1.0.16 => 1.0.16
    eslint: ^7.32.0 => 7.32.0
    webpack: ^5.44.0 => 5.65.0

### Possible solution

I think issue is in @babel/plugin-transform-named-capturing-groups-regex plugin and it should process RegExp, created using `new Regexp(/%val/)` syntax  the different way

**Comment by magic-akari** [comment]
I am trying to fix this.

it's hard to handle some cases like following

```javascript
const es = "es"
new RegExp(`(?<t${es}t>.*)`);
```

**Comment by nicolo-ribaudo** [comment]
This is not possible to fix with a static transform; it needs to implemented as a runtime polyfill. Static transforms are mostly for syntax, not for runtime functions.
