### ISSUE TITLE
[Bug]: Parse error when using React and TypeScript plugins/presets to transform TypeScript/React code programmatically

### ISSUE THREAD

**Issue by chialuka** [babel/babel#14323]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
const code = `
  function Books (props: BookProps): JSX.Element {
    return (
      <div>
        <h1>title </h1>
        <h1>author </h1>
      </div>
    )
  }
  
  function Library (): JSX.Element {
    function handleClick () {
      console.log("hello world");
    }
    return (
      <div>
        <Books title="Lord of the Flies" author={"William Golding"}/>
        <button onClick={handleClick}>click me!</button>
      </div>
    )
  }
`
  
const compileCode = transformSync(code, {
  plugins: ["@babel/plugin-transform-react-jsx", "@babel/plugin-syntax-jsx",
  ["@babel/plugin-transform-typescript", { isTsx: true, allExtensions: true }]]
});
```

### Current Behaviour
The Babel TypeScript plugin returns an error when it encounters JSX code.
```
Error evaluating code:  SyntaxError: /${path-to-file}/index.ts: Unterminated regular expression. (4:14)

  2 | 	return (
  3 | 	<div>
> 4 | 		<h1>title </h1>
    | 		            ^
  5 | 		<h1>author </h1>
  6 | 	</div>
  7 | 	)

  loc: Position { line: 4, column: 14, index: 80 },
  pos: 80,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnterminatedRegExp'
```

### Expected Behaviour
There should be no error parsing TypeScript/React code programmatically since both plugins or presets are used.

### Environment

- babel/core version: [v.7.17.5]
- babel/plugin-transform-react-jsx version: [v7.17.3]
- babel/plugin-transform-typescript: [v7.16.8]
- Yarn version: [v1.22.17]
- Node version: [v17.4.0]
- OS: [Mac 12.2.1]
- monorepo: no

**Comment by JLHwung** [comment]
> { isTsx: true, allExtensions: true }

It should be `{ isTSX: true, allExtensions: true }`, see https://babeljs.io/docs/en/babel-plugin-transform-typescript#istsx

**Comment by chialuka** [comment]
Thanks for chiming in @JLHwung. That's what I did and I still got the error

That's also shown in the code you quoted:
> ["@babel/plugin-transform-typescript", { isTsx: true, allExtensions: true }]]

Am I missing something else?

**Comment by JLHwung** [comment]
`isTsx` is not a supported because of the case, `isTSX` is expected.

In Babel 8 we will produce more helpful errors, i.e.

> @babel/preset-transform: 'isTsx' is not a valid top-level option.
> - Did you mean 'isTSX'?

**Comment by chialuka** [comment]
How did I miss this 🤦🏾‍♂️? Thanks a lot @JLHwung
