### ISSUE TITLE
System format name

### ISSUE THREAD

**Issue by guybedford** [babel/babel#1433]
The System format has quite a bit of naming confusion unfortunately.

Ideally it should be called the `register` format as the format should really be independent of SystemJS (and the `System` global is no longer defined in the spec as well). In due course it should probably output `Reflect.loader.register` to track the environment loader global.

Unfortunately when it was first written in Traceur, there was already a `register` format so we couldn't use that name.

Let me know if a transition into calling this `register` might be possible, perhaps with an intermediate deprecation. I've also created https://github.com/google/traceur-compiler/issues/1915.

No rush, but I just wanted to open the discussion and hear feedback on the idea. Thanks for your time as always.

**Comment by sebmck** [comment]
Sure, definently up for immediate deprecation. Unsure about the `register` name since it seems to be just as confusing.

**Comment by guybedford** [comment]
Thanks. Suggestions for a better name are very welcome too.

**Comment by guybedford** [comment]
An alternative may be to stick with `system` across the board, and then transition to `loader` or `polyfill` or something like that when the output changes to be `Reflect.loader.register`.

That may well make more sense for user upgrade paths as well.

If you agree, I'll close this for now until the time comes for the above change.

**Comment by sebmck** [comment]
Sure, that sounds reasonable.

**Comment by guybedford** [comment]
Ok, thanks for hearing me out!
