### ISSUE TITLE
[Bug]: clone repo and error while `make bootstrap`

### ISSUE THREAD

**Issue by dhlolo** [babel/babel#14331]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```sh
make bootstrap
```

### Current and expected behavior

![image](https://user-images.githubusercontent.com/50065494/156737684-4915c8b2-ce6d-45c7-82a3-942ef89909fa.png)

### Environment

- Babel version: 7.17.6
- Node: 14.15.3
- npm 6.14.9/yarn 3.1.1
- OS: Windows 10

### Possible solution

I found that you guys use 'patch:@rollup/plugin-commonjs@^18.1.0#./.yarn/patches/@rollup__plugin-commonjs.patch' to manually fix '@rollup/plugin-commonjs', but it seems not work for me.
I can only temporarily skip the error, but I am not sure if it will affect the functions.
![image](https://user-images.githubusercontent.com/50065494/156736907-c373b1f8-3733-4954-9683-7c3dca681fe5.png)

By the way, I am trying to figure out referencePaths and bindings in @babel/traverse through source code for tracing var in js/ts.

**Comment by dhlolo** [comment]
> We do have a Windows CI build and it is not affected by this issue.
> 
> https://github.com/babel/babel/blob/8855e4c27e8b0e90409b4295336d07e8971386b4/.yarn/patches/%40rollup__plugin-commonjs.patch#L12
> 
> The commonjs patch manually adds a dynamic require entrypoint: it needs to end with a hardcoded path `/dynamic-require-entrypoint.cjs`. I guess for some reason in your environment rollup gives `\dynamic-require-entrypoint.cjs` so the build fails. We can augment the patch to cover `\` as well.
> 
> If the proposed fix works for you, you are welcome to send a PR.
> 
> > I can only temporarily skip the error, but I am not sure if it will affect the functions.
> 
> If standalone build fails, only the `@babel/standalone` will be affected, you can skip `@babel/standalone` related tests and the rest of tests are pretty much self-contained.

I tried to make some change.
![image](https://user-images.githubusercontent.com/50065494/159621409-e7cda36c-553f-4635-98c9-6f19ffceb907.png)
But it still doesn't work.
![image](https://user-images.githubusercontent.com/50065494/159621534-c56e4eaf-351e-44e0-9ad9-b57d7c790511.png)

**Comment by nicolo-ribaudo** [comment]
After that https://github.com/rollup/plugins/pull/1038 is merged we will be able to remove that patch. Just waiting for it might fix the problem.
