### ISSUE TITLE
[Bug]: update Expression transform into wrong result in cjs

### ISSUE THREAD

**Issue by magic-akari** [babel/babel#14340]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAG2PAZhCcC8cCMA7AbgCgi0IBqcgoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D)
```javascript
export let foo = 1n;

foo++;
```

### Current and expected behavior

```javascript
exports.foo = void 0;

var _foo;

let foo = 1n;
exports.foo = foo;
_foo = +foo, exports.foo = foo = _foo + 1, _foo;
```

Note: cannot mix bigint with number.

### Environment

default config

### Possible solution

```javascript
++foo
=> exports.foo = ++foo

bar++
=> (ref = bar++, exports.bar = bar, ref)
```

**Comment by nicolo-ribaudo** [comment]
Good catch, like the private fields one!
