### ISSUE TITLE
Modules should be strict

### ISSUE THREAD

**Issue by mzgol** [babel/babel#1434]
According to the ES6 spec, modules have implicit strict mode. Babel should add `'use strict';` pragmas to transpiled modules; it doesn't do it either for the `common` output nor for the `amd` one.

**Comment by sebmck** [comment]
>  Babel should add `'use strict';` pragmas to transpiled modules; it doesn't do it either for the `common` output nor for the `amd` one.

[Yes it does?](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=foo()%3B)

**Comment by mzgol** [comment]
Am I doing sth wrong?

a.js:
```js
import b from './b';
```
b.js:
```js
export default 'b';
```
And yet:
```
$ babel --version
5.2.9
$ babel --whitelist es6.modules a.js --modules common                              
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _b = require('./b');

var _b2 = _interopRequireDefault(_b);
```

**Comment by sebmck** [comment]
You're using the whitelist so the `strict` transformer is being disabled.

**Comment by mzgol** [comment]
I see. It seems `es6.modules` should imply `strict`, though as it's part of the semantics.

Is using a whitelist discouraged?

**Comment by sebmck** [comment]
Depends on your usage, but generally using the whitelist is pointless since it wont speed up compilation which is what 90% of people use it for.

**Comment by mzgol** [comment]
I use it mainly so that I don't transpile features that work on current io.js.

**Comment by sebmck** [comment]
There are more features unavailable on io.js so it'd be easier to just use the blacklist.
