### ISSUE TITLE
[Bug][Regression]: @babel/parse 7.17.7 - TS generics notation parsing fail when using react plugin

### ISSUE THREAD

**Issue by jlowcs** [babel/babel#14361]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Arrow function with generics:

```ts
const fn = <T>() => {}
```

[Babel REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeGAeAKgPgBQEpmYwDeAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.17.7&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json, babel.config.js

### Configuration

```js
module.exports = (api) => ({
	sourceType: 'unambiguous',
	presets: [
		[
			'@babel/preset-env',
			{
				useBuiltIns: 'entry',
				corejs: 3,
				loose: false,
				targets: api.caller((caller) => caller && caller.target === 'node') ? { node: '12' } : {},
			},
		],
		'@babel/preset-typescript',
		['@babel/preset-react', { runtime: 'automatic', importSource: 'theme-ui', throwIfNamespace: false }],
	],
	plugins: [
		'@emotion/babel-plugin',
		'@babel/plugin-syntax-dynamic-import',
		'@babel/plugin-proposal-class-properties',
		...(api.env('test') ? [] : ['@loadable/babel-plugin']),
		'@babel/plugin-transform-runtime',
		...(api.env('test')
			? []
			: [['babel-plugin-styled-components', { ssr: true, displayName: false, namespace: 'corgi' }]]),
	],
});
```

### Current and expected behavior

Current behavior:

```
$ node
> require('@babel/parser').parse('const fn = <T>() => {}', { plugins: ['jsx', 'typescript'] })
Uncaught:
[SyntaxError: Single type parameter T should have a trailing comma. Example usage: <T,>. (1:14)
] {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'SingleTypeParameterWithoutTrailingComma',
  syntaxPlugin: 'typescript',
  loc: Position { line: 1, column: 14, index: 14 },
  pos: [Getter/Setter]
}
```

Expected behavior (working on @babel/parser 7.17.0)

```
$ node
> require('@babel/parser').parse('const fn = <T>() => {}', { plugins: ['jsx', 'typescript'] })
Node {
  type: 'File',
  start: 0,
  end: 22,
  loc: SourceLocation {
    start: Position { line: 1, column: 0, index: 0 },
    end: Position { line: 1, column: 22, index: 22 },
    filename: undefined,
    identifierName: undefined
  },
  errors: [],
  program: Node {
    type: 'Program',
    start: 0,
    end: 22,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: undefined
    },
    sourceType: 'script',
    interpreter: null,
    body: [ [Node] ],
    directives: []
  },
  comments: []
}
```

### Environment

- Babel version: 7.17.7
- Node version: 16.13.2
- npm version: 8.1.2
- OS: macOS 12.13

### Additional context

It seems like the presence of both `typescript` and `react` plugins is at fault here. Removing the `jsx` plugin fixes the issue (although it's not an option for us).

**Comment by JLHwung** [comment]
```tsx
const fn = <T>() => {}
```
tsc will throw when JSX is enabled, Babel is aligning to the tsc behaviour here. [Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZmGBeGAeAKgPgBQEpmYwDeAvkA).

As mentioned in the error message, please add a trailing comma after `T`:
```tsx
const fn = <T,>() => {}
```

**Comment by emerikool** [comment]
This error occurs also on ts file not only on tsx. Is there a way to disable this rule ?

**Comment by nicolo-ribaudo** [comment]
TSX is exactly TS+JSX. You can have a "pure TS" syntax by disabling the JSX plugin for that file.

**Comment by nicolo-ribaudo** [comment]
```js
module.exports = (api) => ({
	sourceType: 'unambiguous',
	presets: [
		[
			'@babel/preset-env',
			{
				useBuiltIns: 'entry',
				corejs: 3,
				loose: false,
				targets: api.caller((caller) => caller && caller.target === 'node') ? { node: '12' } : {},
			},
		],
	],
	plugins: [
		'@emotion/babel-plugin',
		'@babel/plugin-syntax-dynamic-import',
		'@babel/plugin-proposal-class-properties',
		...(api.env('test') ? [] : ['@loadable/babel-plugin']),
		'@babel/plugin-transform-runtime',
		...(api.env('test')
			? []
			: [['babel-plugin-styled-components', { ssr: true, displayName: false, namespace: 'corgi' }]]),
	],
    overrides: [{
      // Only enable the React preset for .jsx and .tsx files
      test: /\.(jsx|tsx)$/,
      presets: [
        ['@babel/preset-react', { runtime: 'automatic', importSource: 'theme-ui', throwIfNamespace: false }],
      ]
    }, {
      // Only enable the TypeScript preset for .ts and .tsx files
      test: /\.(ts|tsx)$/,
      presets: ['@babel/preset-typescript']
    }],
});
```

**Comment by paztis** [comment]
problem came from '@babel/plugin-transform-typescript' that require a isTSX boolean (it is not discovering by itself if the page is tsx or not)

**Comment by nicolo-ribaudo** [comment]
That might be a bug, `isTSX`'s default should be based on the file extension :thinking:

**Comment by paztis** [comment]
Not exactly: if we use babel/plugin-transform-typescript instead of the preset, we have to fill the IsTsx var.

I don't remember why but I was not able ti use the preset because of execution ordering (plugins before presets) while the typescript must be expected first. Because of this I use babel/plugin-transform-typescript directly

To resolve this problem, I use overrides to configure it with true boolean in case of TSX file and false in all other cases

**Comment by nicolo-ribaudo** [comment]
Oh right, it's only handled automatically by the TS preset.

**Comment by paztis** [comment]
But the ordering of presets vs plugins was problematic I think

Le mer. 16 mars 2022, 23:03, Nicolò Ribaudo ***@***.***> a
écrit :

**Comment by liby** [comment]
> To resolve this problem, I use overrides to configure it with true boolean in case of TSX file and false in all other cases

It works. But I have to write like this now.

<details>
<summary>babel.config.js</summary>

```
overrides: [
      {
        // Only enable the React preset for .jsx and .tsx files
        test: /\.(jsx|tsx)$/,
        presets: [
          [
            "@babel/preset-react",
            {
              runtime: "automatic",
            },
          ],
        ],
      },
      {
        // Only forcibly enables jsx parsing for .tsx files
        test: /\.tsx$/,
        presets: [
          [
            "@babel/preset-typescript",
            {
              isTSX: true,
              allExtensions: true,
              allowDeclareFields: true,
            },
          ],
        ],
      },
      {
        test: /\.ts$/,
        presets: [
          [
            "@babel/preset-typescript",
            {
              allowDeclareFields: true,
            },
          ],
        ],
      },
    ],
```
</details>

> That might be a bug, isTSX's default should be based on the file extension 🤔
I don't think this is in line with isTSX's expected behavior.

**Comment by nicolo-ribaudo** [comment]
I am tempted to revert the new restriction for now: even if it's technically correct, many are parsing `.ts` files as TSX (even if it might be because of a configuration "problem"), and thus the update breaks them.

We could postpone it to Babel 8. Wdyt @JLHwung / @existentialism / @hzoo?
