### ISSUE TITLE
[Bug]: types are not exported in @babel/core

### ISSUE THREAD

**Issue by xiaoxiangmoe** [babel/babel#14360]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

none

### Current and expected behavior

* Current：`@babel/core` not export `.d.ts` files
* Expected: export `.d.ts` with `.js`

### Environment

```
  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 17.5.0 - /var/folders/sb/lx5g8cjd3cs67qsglbb5lwym0000gn/T/fnm_multishells/53649_1647347330729/bin/node
    Yarn: 1.22.15 - /var/folders/sb/lx5g8cjd3cs67qsglbb5lwym0000gn/T/fnm_multishells/53649_1647347330729/bin/yarn
    npm: 8.4.1 - /var/folders/sb/lx5g8cjd3cs67qsglbb5lwym0000gn/T/fnm_multishells/53649_1647347330729/bin/npm
  npmPackages:
    @babel/core: ^7.17.7 => 7.17.7 
    @babel/parser: ^7.17.7 => 7.17.7 
    @babel/traverse: ^7.17.3 => 7.17.3 
    @babel/types: ^7.17.0 => 7.17.0 
```

**Comment by nicolo-ribaudo** [comment]
We are not ready yet to publish our internal type definitions. You can add `@types/babel__core` to your dependencies to get the Babel types from DefinitelyTypes.
