### ISSUE TITLE
Cannot replace Program with `TraversalPath#replaceWith()`

### ISSUE THREAD

**Issue by shuhei** [babel/babel#1436]
Hi, [these lines](https://github.com/babel/babel/blob/0717eaddce47c6fd8f05312c346a11c5cf61f60f/src/babel/traversal/path/index.js#L512-515) seem to prevent `Program` from being replaced with `TraversalPath#replaceWith()`. 

I'm writing a transformer plugin that appends a statement to Program. Simplified code is:

```js
module.exports = new Transformer('type-assertion', {
  Program: {
    enter: function (node, parent, scope, file) {
      var specifiers = [t.importSpecifier(t.identifier('assert'), t.identifier('assert'), '')];
      var declaration = t.importDeclaration(specifiers, t.literal('rtts_assert/es6/src/rtts_assert'));
      node.body.unshift(declaration);

      this.replaceWith(node); // This doesn't work now.

      // Update local imports cache.
      file.moduleFormatter.getLocalImports();
    }
  }
});
```

After https://github.com/babel/babel/commit/0717eaddce47c6fd8f05312c346a11c5cf61f60f, the `this.replaceWith(node)` stopped working because:

1. `this.replaceWith(node)` is normalized to `this.replaceWithMutiple(this.node.body)` if it's `Program`
2. `replaceWithMultiple()` calls `insertAfter()`
3. `insertAfter()` calls `this.parentPath.isExpressionStatement()`
4.  It raises an error because the `path` for `Program` has undefined `parentPath`

For the meanwhile, I could make it work replacing `this.replaceWith(node)` with `this.setScope(); this.checkSelf()` though.

**Comment by sebmck** [comment]
Please don't use internal APIs that aren't documented (ie. `moduleFormatter.getLocalImports`). Your plugins will break. As mentioned in the [plugin docs](http://babeljs.io/docs/usage/plugins/):

> Internal APIs are still in a high state of flux. If you find something that is not documented on this page then you're at risk of it changing without notice.

You can use `file.addImport("import-name");` which will the default export and return an identifier that you can use to reference it.

You shouldn't be replacing a node with itself and I'll probably add a warning since it's an antipattern and will cause a bunch of reflows internally.

**Comment by shuhei** [comment]
Thanks for pointing `file.addImport()`! I'll definitely use it instead of internal APIs.

**Comment by shuhei** [comment]
Hmm, the module that I want to import is a third party module and doesn't have default import. Is there any sane way to add named imports to `file`?

**Comment by sebmck** [comment]
Not currently via the `File#addImport` API.

**Comment by shuhei** [comment]
I see. Thanks!
