### ISSUE TITLE
[Bug]: Duplicate declaration in transformed for...of

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14379]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function toLowerCase(){}
low = {toLowerCase}
const v1 = fullStr => {
    const v2 = new Map();
    const v3 = [1,2,3];
    for (let v4 of v3) {
        let {
            v20: v0,
            v4 : v4
        } = {
            [6]: 5,
            get: -12
        };
    }
    return v2;
};
v1(low)
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABFOAZOB3ApgJwMICGAzlgBQCUA3gL4BQANpogLyKUrrb7FZ0QJEoiAG4BGFolD16AZSg4WAPja1EaxPzCCRAJglgsGRAFkCABwoBuVes3bhAZgkBtUQBodbhwF1r6yXAKpPRYQsIALIhwwCIO5Cr-_iFClDaJicI6AAwAXCJZbmnp6hGIeRFF_tQSqcWJzgBs3nkArIV1_gDmoXkAtKI6lerUfsNFOKEgOEiZ1iO0YsGY5EA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

The input code can be run by node, but when it is converted by babel, there is an error report
```bash
Duplicate declaration "v4"
```

### Environment

- babel 
- - ├── @babel/cli@7.17.0=6
- - ├── @babel/generator@7.17.3
- - ├── @babel/plugin-transform-runtime@7.17.0
- - ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
It looks like this is the same bug as https://github.com/babel/babel/issues/11920. Enabling only `@babel/plugin-transform-for-of` is enough to reproduce the bug.

The problem is that the plugin is internally transform that code to this one, where we have the duplicate `let x` declaration:
```js
function f(y) {
  var _iterator = _createForOfIteratorHelper(y),
      _step;

  try {
    for (_iterator.s(); !(_step = _iterator.n()).done;) {
      let x = _step.value;
      let x = y;
      return x;
    }
  } catch (err) {
    _iterator.e(err);
  } finally {
    _iterator.f();
  }
}
```
