### ISSUE TITLE
[Bug]: referencesImport is always false for JSXMemberExpression

### ISSUE THREAD

**Issue by swandir** [babel/babel#14375]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from "@babel/parser";
import traverse from "@babel/traverse";

const ast = parse(
  `\
import * as mod from "mod";
mod.name();
<mod.name />;
`,
  {
    sourceType: "module",
    plugins: ["jsx"],
  }
);

traverse.default(ast, {
  MemberExpression(path) {
    if (path.referencesImport("mod", "name")) {
      // referencesImport works with MemberExpression
      console.log("MemberExpression references `name` in `mod`");
    }
  },
  JSXMemberExpression(path) {
    if (path.referencesImport("mod", "name")) {
      // but not with JSXMemberExpression
      // not executed
      console.log("JSXMemberExpression references `name` in `mod`");
    }
  },
});
```

https://codesandbox.io/s/trusting-platform-g4znd2

### Current and expected behavior

For `MemberExpression`, `referencesImport` infers if a function is imported from given source.
For `JSXMemberExpression` it always returns `false`.

As the structure is similar, I'd expect `referencesImport` to be useful with both of these types.

### Environment

```
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    @babel/parser: 7.17.8 => 7.17.8
    @babel/traverse: 7.17.3 => 7.17.3
```

**Comment by nicolo-ribaudo** [comment]
This is tricky, because in `import { a } from "a"; <a/>` it's _not_ referencing the import. For JSXIdentifiers it's only a reference if it starts with an uppercase letter.

**Comment by swandir** [comment]
> This is tricky, because in `import { a } from "a"; <a/>` it's _not_ referencing the import. For JSXIdentifiers it's only a reference if it starts with an uppercase letter.

`NodePath<JSXIdentifier>.referencesImport` works as expected though — given that the name is capitalized of course.

It's `NodePath<JSXMemberExpression>.referencesImport` that does not. And `JSXMemberExpression` always references something because it implies there's a dot in JSX element name.

Anyway, you can change `name` to `Name` in the repro and it doesn't change the outcome.

**Comment by nicolo-ribaudo** [comment]
This is a good issue for a first-time contributor, if anyone wants to help!

`referencesImport` is implemented at https://github.com/babel/babel/blob/3ee9db7afe741f4d2f7933c519d8e7672fccb08d/packages/babel-traverse/src/path/introspection.ts#L177-L197

You can see that if we don't have a `ReferencedIdentifier` (i.e. an `Identifier` or `JSXIdentifier` in a reference position), we only check for `MemberExpression` and `OptionalMemberExpression`: we should expand that to also include `JSXMemberExpression`. You can then add a test at https://github.com/babel/babel/blob/3ee9db7afe741f4d2f7933c519d8e7672fccb08d/packages/babel-traverse/test/introspection.js#L106

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-traverse` to run the tests
    - If the output of some fixtures changes (and it's a correct change),  you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by swandir** [comment]
@nicolo-ribaudo Thanks for the pointers! I'm going to work on in 🖖

**Comment by nicolo-ribaudo** [comment]
Sure, thanks!
