### ISSUE TITLE
[Bug]: WeakMap.set(Record) does not trigger a TypeError as stated in [proposal](https://github.com/tc39/proposal-record-tuple#weakmap-and-weakset)

### ISSUE THREAD

**Issue by Vinsurs** [babel/babel#14374]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
const imutableRecord_1 = #{
    name: "vinsurs",
    age: 18
}
const imutableTuple_1 = #[1, 2, 4]

const weakMap = new WeakMap()
weakMap.set(imutableRecord_1, "imutableRecord")
weakMap.set(imutableTuple_1, "imutableTuple")
// TypeError does not throw and can get results normally.
console.log("weakMap", weakMap.get(imutableRecord_1), weakMap.get(imutableTuple_1))
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
    presets: ["@babel/preset-env"],
    plugins: [
        ["@babel/plugin-proposal-record-and-tuple", {
            importPolyfill: true,
            // "hash" | "bar"
            syntaxType: "hash"  
        }]
    ]
}
```

### Current and expected behavior

**current**: The console can log result normally.
**expected**: The console should throw a TypeError because WeakMap cannot accept a [primitive value](https://github.com/tc39/proposal-record-tuple#compound-primitive-types) as it's key, or as mentioned in [Record-and-Tuple Proposal](https://github.com/tc39/proposal-record-tuple#weakmap-and-weakset).

### Environment

System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.12.0
    Yarn: 1.22.17
    npm: 8.3.0 
  npmPackages:
    @babel/cli: ^7.17.6 => 7.17.6
    @babel/core: ^7.17.8 => 7.17.8
    @babel/plugin-proposal-record-and-tuple: ^7.16.7 => 7.16.7
    @babel/preset-env: ^7.16.11 => 7.16.11

**Comment by nicolo-ribaudo** [comment]
Please reopen this in the polyfill repository!
https://github.com/bloomberg/record-tuple-polyfill

**Comment by nicolo-ribaudo** [comment]
https://github.com/bloomberg/record-tuple-polyfill/issues/76
