### ISSUE TITLE
[Bug]: `plugin-transform-modules-commonjs` outputs unnecessary sequence expression (comma operator) for function calls from name imports

### ISSUE THREAD

**Issue by golopot** [babel/babel#14394]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
import {a} from './foo'
a()
```

### Configuration file name

.babelrc.json

### Configuration

```json
{
  "plugins": ["@babel/plugin-transform-modules-commonjs"]
}
```

### Current and expected behavior

**Current output:**
```js
"use strict";

var _foo = require("./foo");

(0, _foo.a)();
```
**Expected output:**
```js
"use strict";

var _foo = require("./foo");

_foo.a();
```

### Environment

  System:
    OS: Linux 5.12 Arch Linux
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.4.0/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.4.0/bin/npm
  npmPackages:
    @babel/cli: ^7.17.6 => 7.17.6 
    @babel/core: ^7.17.8 => 7.17.8 
    @babel/preset-env: ^7.16.11 => 7.16.11 

### Additional context

Repl link:

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbwIYF84DMoRHA5AOgHp0IJcAoJACgEpzyg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.17.8&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.17.7&assumptions=%7B%7D

**Comment by nicolo-ribaudo** [comment]
If you put this in `foo.js` (and transpile it), you'll see that the proposed output has a different behaviour from the current output:

```js
export function foo() {
  console.log(this);
}
```
