### ISSUE TITLE
bluebird coroutines issue

### ISSUE THREAD

**Issue by simonfox** [babel/babel#1439]
I've just tried Gitter but looks like no one is around so I'll pop this here....

I'm building an Aurelia app, and I've just updated some of my dependencies. those relevant to this discussion are probably the following:

"gulp-babel": "^5.1.0"
"bluebird": "npm:bluebird@^2.9.24"

*gulp-babel has pulled in babel-core 5.2.11*

transpiling the following (greatly simplified) code

```javascript
export class ContractHeader {
  constructor() {
  }

  async save() {
    try {
    } catch(error) {
    }
  }
}
```

gives
```javascript
System.register(["bluebird"], function (_export) {
    var _bluebird, _createClass, ContractHeader;

    function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

    return {
        setters: [function (_bluebird2) {
            _bluebird = _bluebird2;
        }],
        execute: function () {
            "use strict";

            _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

            ContractHeader = (function () {
                function ContractHeader() {
                    _classCallCheck(this, ContractHeader);
                }

                _createClass(ContractHeader, [{
                    key: "save",
                    value: _bluebird.coroutine(function* () {
                        try {} catch (error) {}
                    })
                }]);

                return ContractHeader;
            })();

            _export("ContractHeader", ContractHeader);
        }
    };
});
```

And I get the error *_bluebird.coroutine is not a function* generated by the line `value: _bluebird.coroutine(function* () {`

It seems it could be related to #1219 but that should be fixed in the version I am using. Maybe there has been a regression?

**Comment by sebmck** [comment]
Seems to be a SystemJS issue. The code is output correctly and `require("bluebird").coroutine` returns the correct result.

**Comment by sebmck** [comment]
cc @guybedford

**Comment by simonfox** [comment]
thanks @sebmck 

@guybedford I'm using jspm 0.15.5 (which has loaded systemjs 0.16.11)

**Comment by guybedford** [comment]
@simonfox thanks for posting this. This will be resolved in the next version of SystemJS, when we add the code to extend ES6 modules with the named exports of their default property.

The work-around would be to alter the setter function to look like:

```javascript
        setters: [function (_bluebird2) {
            _bluebird2.coroutine = _bluebird2.default.coroutine;
            _bluebird = _bluebird2;
        }],
```

@sebmck I'm hoping the above will be enough to fix, but losing the `this` binding may possibly lead back to a similar issue some day.

**Comment by simonfox** [comment]
@guybedford thanks! Is this the relevant issue https://github.com/systemjs/systemjs/issues/334 in SystemJS repo?

**Comment by simonfox** [comment]
@guybedford that workaround doesn't seem to work. 

I can replace the usage of
```
value: _bluebird.coroutine(function* () {
```
with
```
value: _bluebird.default.coroutine(function* () {
```
to make it work though.

**Comment by guybedford** [comment]
@simonfox I've be very surprised if that workaround doesn't work - do you remember the error it gave? (as the fix will be equivalent to the workaround). I did try loading the module here and it seemed to define the module and work fine to me, but I didn't try running the coroutine.

**Comment by simonfox** [comment]
@guybedford the error is 

```
TypeError: Error loading "viewmodels/contractheader" at http://localhost:9000/dist/viewmodels/contractheader.js _bluebird.coroutine is not a function
```

If I change to the following
```
console.log(_bluebird2.default.coroutine);
_bluebird2.coroutine = _bluebird2.default.coroutine;
_bluebird = _bluebird2;
console.log(_bluebird.coroutine);
```
the second `console.log` logs undefined (the first logs the function as expected).

**Comment by guybedford** [comment]
@simonfox ok thanks for letting me know, that seems fine. It's probably a result of the `Object.preventExtensions` call on the module object in the module loader. So I don't think the fix would hit that path.

**Comment by simonfox** [comment]
@guybedford 

here is the stack trace if you want (it's 0.16.6 of es6-module-loader)

```
app-router.js:144
O	@	es6-module-loader.src.js:1183
K	@	es6-module-loader.src.js:1142
7.y.when	@	es6-module-loader.src.js:930
7.v.run	@	es6-module-loader.src.js:821
3.a._drain	@	es6-module-loader.src.js:97
3.a.drain	@	es6-module-loader.src.js:62
b	@	es6-module-loader.src.js:268

**Comment by simonfox** [comment]
@guybedford sorry, so will this still be fixed in the next version then?

**Comment by guybedford** [comment]
Yes exactly.

**Comment by simonfox** [comment]
@guybedford awesome, thanks so much!!

**Comment by simonfox** [comment]
@guybedford so I'm a wee bit out of my depth here, so feel free to just tell me not to worry and it.....but if I change to (and I understand this is a bad idea)
```
_bluebird2.__proto__.coroutine = _bluebird2.default.coroutine;
_bluebird = _bluebird2;
```
it works. But reading effects of [preventExtensions here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions), seems to suggest it shouldn't?

**Comment by guybedford** [comment]
@simonfox yes not a great idea, that will add it to every module in your app! You can always try

```javascript
_bluebird = { default: _bluebird2.default, coroutine, _bluebird2.default.coroutine };
```

**Comment by simonfox** [comment]
@guybedford there's a `,` instead of a `:` in that, but yes that works nicely. Thanks again, all your hard work is much appreciated!
