### ISSUE TITLE
[Bug]: Enum string value gets reverse mapped

### ISSUE THREAD

**Issue by MPuida** [babel/babel#14402]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
enum Enum {
    A,
    B = "B",
    C = 4
}

enum Test1 {
    A1 = Enum.A,
    B1 = Enum.B,
    C1 = Enum.C
}

enum Test2 {
    A1,
    B1 = "B",
    C1 = 4
}


describe("Match Enums", () => {
    it("Matches", () => {
        expect(Test1).toEqual(Test2);
    });
});
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
    presets: [["@babel/preset-env", { targets: { node: "current" }}], "@babel/preset-react", "@babel/preset-typescript"]
};
```

### Current and expected behavior

Current behavior: Test1 and Test2 does not match due to an additional key ("B") in Test1 enum. If the key "B1" in Test1 is renamed and matches the value, enums match as expected.

Expected behavior: Enum values which are a type of string should not have reverse mapping.

### Environment

- Babel version: [^6.23.0]
- Node version: [v14.16.0]
- npm/Yarn version: [npm v6.14.15/Yarn 3.0.2]
- TypeScript version: [^4.4.3]
- OS: [Windows 10]

### Additional context

Screenshot of the test result:

![image](https://user-images.githubusercontent.com/81805664/160557101-9f6d80c5-8dce-4735-826d-3fd7c46eca73.png)

**Comment by liuxingbaoyu** [comment]
https://www.staging-typescript.org/play?declaration=false&isolatedModules=true&ts=5.0.0-dev.20230128#code/KYOwrgtgBAou0G8BQVVQIIBoVoEJQF4oAiXY7NKAYUKgBYkBfJJUSKAFWAGcAXARijJK6QUTiQAdFhypcY2PEm4KaKgokRJVJizbQufAExDZGDUpmV5tUuTPram7UyA

ts5.0 unifies this strange behavior, now we can align ts.
