### ISSUE TITLE
Require hook still not ignoring `node_modules` folder. 

### ISSUE THREAD

**Issue by smcelhinney** [babel/babel#1441]
I noted that a regression issue was introduced in 5.2.1 which caused `node_modules` not to be ignored. Having updated to the latest (5.2.13 at time of writing) it appears this issue is still present for me. 

I've removed my `node_modules` folder and run `npm cache clean` and on a fresh `npm install`, gulp is still failing as it seems to be including the node_modules folder. 

My require hook setup 

```
require('babel/register')({
  only: /gulp|jscs-plugins/
});
```

The failing code (first module required is `gulp-util`)

```
SyntaxError: /<obscured>/node_modules/gulp-util/node_modules/beeper/index.js: 'return' outside of function (9:1)
   7 | 	process.argv.indexOf('--beep=false') !== -1) {
   8 | 	module.exports = function () {};
>  9 | 	return;
     |  ^
  10 | }
  11 |
  12 | function beep() {
    at Parser.pp.raise (/<obscured>/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.parseReturnStatement (/<obscured>/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:247:74)
    at Parser.pp.parseStatement (/<obscured>/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:77:19)
```

Is this issue still occurring?

**Comment by sebmck** [comment]
It's due to the `only` option.

**Comment by sebmck** [comment]
Actually I think the previous behaviour was a bug. It's only logical that `only` shadow `ignore` since you can't have one or the other.

**Comment by sebmck** [comment]
Yep, expected behaviour. This behaviour is inline with all other usage of `only`/`ignore`. You've explicitly set the `only` option which shadows any set `ignore` pattern.
