### ISSUE TITLE
[Bug]: Incorrect value of `sourceFileName` from the output of `@babel/cli` command?

### ISSUE THREAD

**Issue by nyngwang** [babel/babel#14411]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code (Not important in this problem)

```js
const arr = ['Roya', 'Owen', 'Eric']

const index = arr.findIndex((item) => item === 'Owen')

export default () => {
  console.log(`Owen is at pos ${index}`)
}
```

### Configuration file name

babel.config.js

### Configuration

```js
export default {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
    '@babel/preset-typescript',
  ],
  plugins: [
    '@babel/plugin-proposal-class-properties',
  ],
}
```

### Current and expected behavior

The project structure:

```
  ~/Desktop/GitHub/Test/ E  
    .git/
    lib/ 
    node_modules/
    src/ E  
   │  test/ E  
     └  index.js E 
    .eslintrc.json
    .gitignore
    README.md
    babel.config.js
    package.json  
    tsconfig.json  
    webpack.config.js  
    yarn.lock
```

The CLI command:

```
BABEL_SHOW_CONFIG_FOR=./src/test/index.js npx babel ./src/test --out-dir ./lib/nested
```

outputs:

```
Babel configs on "/Users/ningwang/Desktop/GitHub/Test/src/test/index.js" (ascending priority):
config /Users/ningwang/Desktop/GitHub/Test/babel.config.js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}

programmatic options from @babel/cli
{
  "sourceFileName": "../../src/test/index.js",
  "caller": {
    "name": "@babel/cli"
  },
  "filename": "src/test/index.js"
}
-----End Babel configs-----
Successfully compiled 1 file with Babel (420ms).
```

But according to the documentation of [`sourceFileName`](https://babeljs.io/docs/en/options#sourcefilename):

> Type: string
> Default: `path.basename(opts.filenameRelative)` when available, or `"unknown"`

So how can the value of `"sourceFileName"` be `"../../src/test/index.js"`? Since the function `path.basename()` will only output the last portion of the path, which in this case is `index.js`?

### Environment

- Babel versions:
     ```
     "@babel/cli": "^7.17.6",
     "@babel/core": "^7.17.8",
     "@babel/preset-env": "^7.16.11",
     ```
- Node: v16.13.1
- Yarn: 1.22.18
- OS: macOS 11.6.2
- Monorepo: yes

### Additional context

The current result, `"../../src/test/index.js"` is the output of `path.relative("./lib/nested", "./src/test/index.js")`.

So I guess the documentation is imprecise, because the source map would need a relative **path** to refer to the source file. The basename of it is `index.js`, which is useless in providing context about where to find the source file. But I also found that the `path.basename` is indeed appeared in the Repo.:

https://github.com/babel/babel/blob/66cadea103e59f1b67f5ef9333f2d230243d1665/packages/babel-core/src/transformation/normalize-opts.ts#L18

So my guess is probably wrong.

**Comment by JLHwung** [comment]
> So how can the value of "sourceFileName" be "../../src/test/index.js"?

As you can see from the `BABEL_SHOW_CONFIG_FOR` results, the `sourceFileName` is a programmatic options passed from `@babel/cli`:

https://github.com/babel/babel/blob/66cadea103e59f1b67f5ef9333f2d230243d1665/packages/babel-cli/src/babel/dir.ts#L48

The option docs you mentioned above declares the default value of `sourceFileName`, but the option could be overwritten by any babel callers. And in this case, `@babel/cli` passed the `sourceFileName` to `@babel/core`. I don't think the docs is imprecise.

Babel creates source map using `sourceFileName`, which should be resolved relative to the source location. So if you host both the transpiled results and the source codes, the devtools can fetch the source using `./../src/test/index.js`.

**Comment by nyngwang** [comment]
@JLHwung Could you elaborate more on this line:

> Babel creates source map using `sourceFileName`, which should be resolved relative to the source location.

My current understanding is that a "source file" is a file under `Proj/src/`, while the transpiled results are under `Proj/lib`. Since the source map in my case is generated under `Proj/lib`, and it's next to the transpiled results, so "[...] should be resolved relative to the **source** location" sounds strange? Shouldn't it be _dist_ location or something. (I mean the location of the transpiled results)

Thanks in advance...
