### ISSUE TITLE
[Bug]: Attribute missing due to variable passing

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14414]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var v0 = function* v1() {
    yield* [];
}();
let v4 = Object.getOwnPropertyNames(v0), v5 = Object.keys(v0);
for (let v0 = 0; v0 < v5.length; v0 += 1) {
    v6 = v5.v0;
    const v5 = v0.undefined || v0.undefined;
}
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=true&loose=true&code_lz=G4QwTgBMAMELwQGYFcB2BjALgSwPaoCooBGACgEoIBvAKAnogE9sBTAGwBMiBtAXQG4aAXwqC2LTFAAs8CAHkARgCsWWAHQBzCXIDuqAAphcABxZhMjAHIgAtiwDOpGOQA0UAKyzFK9QGsWjI7Ogoi4kKTikjCy0PxQsAA8HmriqBqYABZx0QDUCMSUtAxQAGyywO5qMILF6Pj2UZ4IMGpoHCyI2KgsHBAAPn3xrajtnd0cgkJAA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

The compiled code run by node report an error:
```shell
    v6 = _v2.v0;
             ^

TypeError: Cannot read properties of undefined (reading 'v0')
```
This may be because Babel's variable passing overrides the attribute？

### Environment

- babel 
- - ├── @babel/cli@7.17.6
- - ├── @babel/generator@7.17.7
- - ├── @babel/plugin-transform-runtime@7.17.0
- - ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
Unfortunately it's not possible to possible to implement proper TDZ checks in compiled code, so invalid code such as that one (where you are accessing v5 before that it's initialized) may throw different errors from the expected ones.

**Comment by nicolo-ribaudo** [comment]
You can enable explicit tdz checks in the `transform-block-scoping` plugin:
```json
{
  "sourceType": "unambiguous",
  "presets": [
    ["@babel/preset-env", { "exclude": ["transform-block-scoping"] }]
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    ["@babel/plugin-transform-block-scoping", { "tdz": true }]
  ]
}
```
the compiled code will then throw the correct error:
```
ReferenceError: v5 is not defined - temporal dead zone
```
