### ISSUE TITLE
[Bug]: @babel/helper-create-class-features-plugin not found in create-react-app

### ISSUE THREAD

**Issue by parrajr** [babel/babel#14428]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

npx create-create-react-app .

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-create-class-features-plugin@^7.17.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/plugin-proposal-decorators'

### Current and expected behavior

create the react app

### Environment

Node js version 14.17.3
Npm version 6.14.13

### Additional context

In https://www.npmjs.com/package/@babel/helper-create-class-features-plugin we can see that last version has 0 downloads since was released 2 hours ago.

**Comment by nicolo-ribaudo** [comment]
The version is on npm, if it cannot be downloaded it's a non registry bug 🤷

**Comment by parrajr** [comment]
> The version is on npm, if it cannot be downloaded it's a non registry bug 🤷

So, what should I do to solve it?

**Comment by parrajr** [comment]
Just to add:
When I run npm view @babel/helper-create-class-features-plugin, it shows me the latest version is 7.17.6 and not 7.17.9.

Even after run npm update the latest version still the same.

**Comment by JLHwung** [comment]
> > The version is on npm, if it cannot be downloaded it's a non registry bug 🤷
> 
> So, what should I do to solve it?

https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67
