### ISSUE TITLE
Publishing `@babel/eslint-parser` conversion functionality as a separate package

### ISSUE THREAD

**Issue by brettz9** [babel/babel#14422]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Hi,

I'm working with ESLint (and `eslint-plugin-jsdoc`), and see some use cases for converting ESLint-friendly ESTree AST into Babel AST.

This may include

- ESLint rules which modify the AST and serialize them back for use by `@babel/generate`.
- Allowing us to work on manipulating features of our own code base after first parsing with familiar ESTree syntax

### Describe the solution you'd like

Being able to install an npm package dedicated to the contents of https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser/src/convert .

Ideally too, there'd be separate exports for converting the AST, the tokens, and comments.

### Describe alternatives you've considered

Having the contents of https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser/src/convert added to `exports` could work as well, though a little less ideal re: modularity. Would be nice not to need to download all the other parsing facilities. But that would still be better than nothing.

### Documentation, Adoption, Migration Strategy

```sh
npm install @babel/babel-to-estree
```

```js
import {convert} from '@babel/babel-to-estree';

const estreeAST = convert(ast, code, tokLabels, visitorKeys);
```

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser/src/convert only converts the ESTree AST that `@babel/parser` can produce to the ESTree format that ESLint expects. We don't have any tools to convert from ESTree to the Babel AST format.

**Comment by brettz9** [comment]
I somehow got tripped up, sorry. There's a package that claims to convert from ESTree to Babel AST at https://www.npmjs.com/package/estree-to-babel so I guess I can try that.

I guess if I ever need converting from the Babel AST format to the ESLint ESTree format I can ask at such a time. Sorry for the noise!
