### ISSUE TITLE
[Bug]: Numeric separators broken

### ISSUE THREAD

**Issue by austindonisan** [babel/babel#14425]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

1_1

### Current and expected behavior

Currently throws error:

```
/repl.jsx: A numeric separator is only allowed between two digits. (1:1)

> 1 | 1_1
    |  ^
```

Expected output:

```
"use strict";

11;
```

### Environment

Babel REPL version 7.17.8

### Additional context

Works in 7.17.6, broken in 7.17.7

I'm guessing #14338 broke it

**Comment by nicolo-ribaudo** [comment]
Wow, I'm surprised our tests didn't prevent us from breaking so badly.

**Comment by nicolo-ribaudo** [comment]
I can reproduce this on the REPL, but not locally :thinking: 

@austindonisan Do you have an example outside of the repl?
