### ISSUE TITLE
[Bug][@babel/plugin-transform-typescript] imported and reexported interfaces from external package are not cleanup

### ISSUE THREAD

**Issue by paztis** [babel/babel#14421]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

package-1 (index.ts)
```
export interface ITest1 {}
export interface ITest2 {}
```

package-2 (index.ts)
```
import {ITest1, ITest2} from 'package-1';

export {ITest1, ITest2} 
```

### Configuration file name

.babelrc

### Current and expected behavior

@babel/plugin-transform-typescript well remove the import / export of interfaces when they came from the same package.
When they came from external package, there's no verification and it produces totally incorrect js code
This code crases in webpack builds because it tries to resolve unexisting js imports.

Typescript tsc transpilation correctly remove them

current behavior

package-2 (index.js)
```
import {ITest1, ITest2} from 'package-1';

export {ITest1, ITest2} 
```

expected behavior

package-2 (index.js)
```
export {}
```

### Environment

- babel: 7.17.0. Same for all plugins

### Possible solution

3rd part packages imports need to be verified to know if it is typescript imports or not

**Comment by nicolo-ribaudo** [comment]
Babel marchese TypeScript's `"isolatedModules"` option behaviour, because it works on a per&file basis.

You need to do this:
```js
import type {ITest1, ITest2} from 'package-1';
```

**Comment by paztis** [comment]
True, I can do this

```
import type {ITest1, ITest2} from 'package-1';
export {ITest1, ITest2}
—

But the initial code was working well with the typescript compiler.
```

**Comment by nicolo-ribaudo** [comment]
Yes, but Babel explicitly matches the behaviour of TSC when using it with the `--isolatedModules` option (https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options).

If you enable that option in your tsconfig, TypeScript will also complain about that input code.

**Comment by paztis** [comment]
Ok understood.
Sorry for the false positive

Le mar. 5 avr. 2022, 08:13, Nicolò Ribaudo ***@***.***> a
écrit :
