### ISSUE TITLE
[Bug]: Scope bindings missing in AST for the variables which are introduced by `babel-plugin-transform-destructuring`

### ISSUE THREAD

**Issue by peey** [babel/babel#14438]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

https://github.com/peey/babel-missing-ast-scope-bindings-repro

## Current Behavior

No scope bindings in the AST for variables introduced by `@babel/plugin-transform-destructuring`.

E.g. in the example 
```js
function f() { return {x: 1, y: 2}; }; const {x,y} = f();
```
The transformed source is 

```
function f() {
  return {
    x: 1,
    y: 2
  };
}

;

const _f = f(),
      x = _f.x,
      y = _f.y;
```

Each variable has an associated scope binding in the AST, but the variable introduced by the transform (`_f`) does not.

## Expected Behavior

Scope bindings expected to be present

### Environment

  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @babel/core: ^7.17.9 => 7.17.9
    @babel/parser: ^7.17.9 => 7.17.9
    @babel/plugin-transform-destructuring: ^7.17.7 => 7.17.7
    @babel/traverse: ^7.17.9 => 7.17.9
    @babel/types: ^7.17.0 => 7.17.0

### Possible solution

Perhaps the related piece of source code is the following:?
https://github.com/babel/babel/blob/f8543735a2895b2b3dc23fe8482b21e5ea7de359/packages/babel-plugin-transform-destructuring/src/index.ts#L161

I was expecting to find templates which introduce the variable, but it seems like the resulting AST is constructed in another way for this transform so I'm not sure.

**Comment by liuxingbaoyu** [comment]
This problem may be difficult to fix.
But if you just want it to work.
Please use `originalAst = parse()` again

**Comment by peey** [comment]
Hi @liuxingbaoyu . I agree that's a good alternative perhaps. But I think if this can be fixed it could be useful to downstream plugins which need scope info (e.g. if some plugin runs after de-structuring, for correct operation it definitely needs correct scope info right?)

I've tried to fix it and made some progress. Please look at the linked PR (very small change -  2 lines in source, ~60 lines in test) in case you have any insights you can share which could help improve it.

**Comment by liuxingbaoyu** [comment]
Yes, I think that makes sense too.

However I prefer to provide options to isolate plugins, which is clearly an issue in many plugins.

**Comment by peey** [comment]
What do you mean by isolating plugins in context of this issue? 

If you mean they should have clear boundaries and interfaces then I agree. I think this would be a step towards it. Instead of having to worry about "I might have scope bindings if I ran before plugin X but not before plugin Y" this can be a first step towards providing the guarantee that "Each plugin will always receive a proper AST with full information as input, and must produce a proper AST as output". Currently `babel-plugin-transform-desturcturing` is violating that in that it does recieve valid ASTs but it produces ASTs which are incomplete (e.g. they have AST elements but their bindings have been uninitalized) 

Thankfully I was able to fix this issue in the linked PR for `babel-plugin-transform-destructuring`, but a reviewer had interesting comments about how this approach could perhaps be generalized to all plugins. If that's something you're interested in you can check that out, and maybe that'd be the next step after the PR is merged. In case you do check it out, please also leave a review! The final code is even smaller and simpler thanks to the first reviewer's contribution.
