### ISSUE TITLE
How to manipulate property initializer with decorators?

### ISSUE THREAD

**Issue by alidavut** [babel/babel#1443]
Can I change the default value with getter and setter? 

I need something like this:
```javascript
const decorator = (instance, name, desc) => {
  instance.constructor.defaults[name] = the default value here('Test');
  desc.get = function() { return this[name] || instance.constructor.defaults[name]  };
  desc.set = function(val) { this[name] = val }; 
  return desc;
}

class A {
  @decorator name = 'Test';
}
```

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by sebmck** [comment]
Also see https://github.com/wycats/javascript-decorators/blob/master/INITIALIZER_INTEROP.md

**Comment by alidavut** [comment]
thanks for reply
