### ISSUE TITLE
How to known the plugin task is finished ? 

### ISSUE THREAD

**Issue by chaunceym** [babel/babel#14437]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

I want get the moment which is plugin task is finished, like some lifecycle hooks: created, updated, or unmount

### Describe the solution you'd like

....

### Describe alternatives you've considered

...

**Comment by nicolo-ribaudo** [comment]
I don't understand what you are asking for exactly; maybe you could add a `Program` visitor with enter/exit?

What's your use case?
