### ISSUE TITLE
Support TypeScript 4.7 `in` and `out` variance annotations

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#14442]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

TypeScript 4.7 Beta ships with `in` and` out` modifiers for type parameters on type declarations.

```ts
type Getter<out T> = () => T;

type Setter<in T> = (value: T) => void;

interface State<in out T> {
    get: () => T;
    set: (value: T) => void;
}
```

TypeScript developers using Babel will need to support this syntax.

These `in` and `out` modifiers can only be placed on type parameter declarations for

* `type` aliases
* `interface` declarations
* `class` declarations
* [~*possibly*~ `class` expressions](https://github.com/microsoft/TypeScript/issues/48618)

It is possible to have `in`, `out`, and `in out`. Duplicates are not allowed, and `in` must always come before `out`.

### Describe the solution you'd like

For the next minor version of Babel, we may want to implement this feature.

### Describe alternatives you've considered

There are alternative compilers, but that would not be ideal for Babel users.

**Comment by nicolo-ribaudo** [comment]
Thanks for the heads up!
