### ISSUE TITLE
Unminified browser-polyfill should be contained in the npm package

### ISSUE THREAD

**Issue by mzgol** [babel/babel#1444]
A common practice is to use unminified vendor files during development so that potential bugs touching used tools are easier to debug and to only switch to minified ones when deploying to production.

It'd be useful if the `babel-core` package contained both unminified `browser-polyfill.js` & minified `browser-polyfill.min.js`.

**Comment by sebmck** [comment]
I'd rather not encourage the use of `browser-polyfill.js` and I consider it a mistake as it can easily fall out of sync with the latest versions of dependencies.

**Comment by sebmck** [comment]
Guess I’m obligated to support it still :/

**Comment by mzgol** [comment]
What's the recommended replacemend then? http://babeljs.io/docs/usage/polyfill/ mentions the `browser-polyfill.js` and without the polyfill compiled files won't work in most browsers.

**Comment by mzgol** [comment]
Should I include `core-js` & `regenerator` files by myself instead?

**Comment by sebmck** [comment]
You should be building it yourself or using a module bundler where you can just require `babel/polyfill`.

**Comment by mzgol** [comment]
This would mean my pipeline needs to understand CommonJS, wouldn't it?
