### ISSUE TITLE
[Bug]: Arrow function throws an error "Identifier xxx has already been declared"

### ISSUE THREAD

**Issue by alexleboucher** [babel/babel#14441]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
const auth = "dontReallyCare";
return (auth => new WhatEver(auth))(auth);
```

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [
        [
            "next/babel",
            {
                "preset-react": {
                    "runtime": "classic"
                }
            }
        ]
    ],
    "plugins": [
        [
            "module-resolver",
            {
                "root": ["./"],
                "alias": {
                    "src": "./src"
                }
            }
        ],
        // See https://styled-components.com/docs/advanced#nextjs
        [
            "styled-components",
            {
                "ssr": true
            }
        ],
    ]
}

```

### Current and expected behavior

Babel is doing :
```js
var auth;const auth=...
```
I think that when the variable name used in the arrow function has the same name than a declared variable in the same scope, Babel declares 2 variables with the same name and it throws an error `Identifier 'auth' has already been declared`.

The problem is this arrow function is not in my code so I cannot modify the variable name, the arrow function is in a package and this package is important for the project. The package is `firebase`...

### Environment

System:
    OS: macOS 11.6.5
  Binaries:
    Node: 17.6.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.17.8 => 7.17.9 
    babel-loader: ^8.2.4 => 8.2.4 
    babel-plugin-module-resolver: ^4.0.0 => 4.1.0 
    babel-plugin-styled-components: ^2.0.6 => 2.0.6 
    eslint: ^7.32.0 => 7.32.0 
    jest: ^27.5.1 => 27.5.1

### Additional context

I simplified the examples but if you want all the details, the code of firebase is : 
```js
const auth = _castAuth(
    container.getProvider(_ComponentName.AUTH).getImmediate()!
);
return (auth => new AuthInterop(auth))(auth);
```
You can find it [here](https://github.com/firebase/firebase-js-sdk/blob/7405e7d593b40c9945c32ffbe66ac6fb11e2991e/packages/auth/src/core/auth/register.ts) in the function `_registerComponent`.

And Webpack generates this code : 
```js
container=>{var auth;const auth=_castAuth(container.getProvider("auth").getImmediate());return auth=auth,new AuthInterop(auth)},"PRIVATE").setInstantiationMode("EXPLICIT")),(0,esm_index_esm2017.KN)(index_6de4cbb9_name,version,getVersionForPlatform(clientPlatform)),(0,esm_index_esm2017.KN)(index_6de4cbb9_name,version,"esm2017")}function getAuth(app=(0,esm_index_esm2017.Mq)()){const provider=(0,esm_index_esm2017.qX)(app,"auth");return provider.isInitialized()?provider.getImmediate()
```

It's maybe the same issue than [this one](https://github.com/babel/babel/issues/14023) but I was not sure, sorry if it's the case

Thank you for your time !

**Comment by JLHwung** [comment]
> And Webpack generates this code

Comparing the output
```js
return auth=auth,new AuthInterop(auth)
```
with the input
```js
return (auth => new AuthInterop(auth))(auth);
```
the IIFE in the input is optimized to an expression, which may come from an minimizer. Can you reproduce this issue without minification?

**Comment by alexleboucher** [comment]
Indeed, it wad due to SWC (I use Next), I disabled it and now it works, thank you !

**Comment by nicolo-ribaudo** [comment]
Please report this to SWC if you have time, so that they can fix it!
