### ISSUE TITLE
typeof on #private Fields

### ISSUE THREAD

**Issue by magic-akari** [babel/babel#14451]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

TypeScript 4.7 now allows us to perform typeof queries on private fields.

```typescript
class Container {
    #data = "hello!";

    get data(): typeof this.#data {
        return this.#data;
    }

    set data(value: typeof this.#data) {
        this.#data = value;
    }
}
```

- https://github.com/microsoft/TypeScript/pull/47696

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Documentation, Adoption, Migration Strategy

https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#typeof-on-private-fields

**Comment by jakebailey** [comment]
We're [reverting](https://github.com/microsoft/TypeScript/pull/48959) the linked change in TS, so you probably shouldn't merge this (we may not even allow this syntax).

**Comment by nicolo-ribaudo** [comment]
I'm closing this; we will reopen if it ends up being included in a future TS version.
