### ISSUE TITLE
Unexpected Symbol.iterator behavior with `babel-loader?optional=runtime`

### ISSUE THREAD

**Issue by angus-c** [babel/babel#1445]
In the babel REPL these work as expected

```js
console.log(typeof Symbol.iterator); // "symbol"
console.log([][Symbol.iterator]) // function
```

However when I execute them in runtime (via karma runner) I get

```js
console.log(typeof Symbol.iterator); // "string"
console.log([][Symbol.iterator]); // undefined
```

`[][Symbol.iterator]` is transpiled to `[][_Symbol$iterator]`

I'm using babel-loader in webpack:

```
    webpack: {
      module: {
        loaders: [
          { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?optional=runtime' },
        ],
      },
      watch: true,
    }
```

**Comment by sebmck** [comment]
Expected behaviour. Getting the iterator function doesn't make much sense and not sure how it'd be implemented. You need to actually call the iterator so `[][Symbol.iterator]` to construct an iterator instance.

**Comment by angus-c** [comment]
>> Getting the iterator function doesn't make much sense

Agree it makes no sense in application code, but I'm building an [ES6 test suite](https://github.com/angus-c/es6-tests) (mainly for my own education). 

Fair enough if it's hard to fix - but it works in the babel REPL - so was curious how I could replicate the REPL behavior at runtime. I assumed they both used the core shim.

**Comment by sebmck** [comment]
Yeah they do, I’ll look into supporting it. May be something extremely obvious that I’m missing, I’ll reopen until I have time to dig more into it.

**Comment by angus-c** [comment]
Thanks Sebastian.

**Comment by sebmck** [comment]
No dice, doesn't look like there's anything exposed.

**Comment by zloirock** [comment]
Currently getting iterator function impossible in `core-js/library` w/o access to internal `core-js` modules. I can add helper for this case, but it's really required?

**Comment by angus-c** [comment]
No, it's not a  big deal - just want to make my ES6 test suite as comprehensive as possible.
`typeof Symbol.iterator` returning "string" might be a bigger issue for devs (it correctly returns "symbol" in the REPL)

**Comment by sebmck** [comment]
It would be returning “symbol” because the version of chrome you’d be using would have native symbols. You can enable the `es6.spec.symbols` transformer to rewrite `typeof` to take into consideration symbols across all environments.

**Comment by angus-c** [comment]
Oh good point. Thanks.

**Comment by zloirock** [comment]
`es6.spec.symbols` will not work for `Symbol.iterator` with current `runtime` transformer. To minimize dependencies, w/o native symbols `core-js/library/symbol/iterator` and other well-known symbols are simple, not wrapped, strings. `require('core-js/library/symbol').iterator` - wrapped, but much more heavy.
