### ISSUE TITLE
babel-node should understand --harmony_rest_parameters

### ISSUE THREAD

**Issue by krnlde** [babel/babel#1446]
io.js supports rest parameters natively since [v2.0.0](https://github.com/iojs/io.js/blob/master/CHANGELOG.md) and provides a flag for that.

This flag should also be understood by [babel-node](https://github.com/babel/babel/blob/master/packages/babel-cli/bin/babel-node#L41).

**Comment by sebmck** [comment]
PR? :) Just need to add it to [packages/babel-cli/bin/babel-node](https://github.com/babel/babel/blob/master/packages/babel-cli/bin/babel-node#L55).

**Comment by topaxi** [comment]
Just note that native params are way slower than transpiled as native support isn't optimized: https://code.google.com/p/v8/issues/detail?id=2159#c17

**Comment by krnlde** [comment]
@sebmck I tried just that on my local system but it didn't work. It looked like just adding the option to the array isn't enough. I'm not in babel's code deep enough to understand what needs to be done in addition to pass the option to node / iojs.

@topaxi thanks for linking that issue! I didn't know that.

**Comment by sebmck** [comment]
Released as of 5.2.16, thanks!

**Comment by krnlde** [comment]
Can confirm it works :) Thanks a lot!
