### ISSUE TITLE
[Bug]: The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean

### ISSUE THREAD

**Issue by Stophface** [babel/babel#14469]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

I only added the `plugin-proposal-decorators` to the project

    yarn add --dev @babel/plugin-proposal-decorators

And adde this to the `babel.config.js` file

```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}
```

### Configuration file name

babel.config.js

### Configuration
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
};
```

### Current and expected behavior

I expect the App to run without error. Currently I get

> The decorators Plug In, when version is '2018-09' or not specified, requires a 'decoratorsBeforeExport' option, whose value must be a Boolean. (While processing node_modules/@babel/plug-in-proposal-decorators/lib/index.js$inherits

### Environment

"@babel/core": "^7.12.9",
"@babel/plugin-proposal-decorators": "^7.17.9",
"@babel/runtime": "^7.12.5",
"@react-native-community/eslint-config": "^2.0.0",
"babel-jest": "^26.6.3",    
"react": "17.0.2",
"react-native": "0.66.4",

Node: 17.0.1

### Possible solution

I tried 

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
    ["@babel/plugin-proposal-decorators", { "legacy": true, "decoratorsBeforeExport": false }] // as well as true
  ]
};
```
but get the same error. 

### Additional context

Existing react-native project.

**Comment by nicolo-ribaudo** [comment]
Can you check if using `"version": "legacy"` instead of `"legacy": true` fixes the error?

**Comment by Stophface** [comment]
@nicolo-ribaudo nope, no luck...

**Comment by liuxingbaoyu** [comment]
I'll close it due to long periods of inactivity, feel free to open it if the problem persists.
