### ISSUE TITLE
[Bug]: 'selfClosing' doesn't work in 't.jsxElement'

### ISSUE THREAD

**Issue by wjw99830** [babel/babel#14460]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import g from '@babel/generator';
import * as t from '@babel/types';

const jsxElement = t.jsxElement(t.jsxOpeningElement(t.jsxIdentifier('div'), []), null, [], true);
console.log(g(jsxElement).code); // <div>
const jsxElement2 = t.jsxElement(t.jsxOpeningElement(t.jsxIdentifier('div'), [], true), null, [], true);
console.log(g(jsxElement2).code); // <div />
```

### Configuration

no config

### Current and expected behavior

Current:
Can not generate self-closing jsx code if pass true to the fourth parameter of `t.jsxElement`;

Expected:
Generate self-closing jsx code if pass true to the fourth parameter of `t.jsxElement`;

### Environment

- Babel versions: 
  - @babel/types 7.17.0
  - @babel/generator 7.17.9
- Node: 14.19.1
- pnpm: 7.0.0-rc.3
- OS: macOS 11.6
- Monorepo: no

### Possible solution

At the type level, remove `t.jsxElement`'s  fourth parameter and remove the `selfClosing` prop in interface `JSXElement`.
Or fix the generator to make sense of `JSXElement`'s `selfClosing` parameter.

**Comment by JLHwung** [comment]
Good catch. The `jsxElement.selfClosing` is never used or created in `@babel/parser`. I think we should remove it from the `@babel/types` builder and the AST definitions in Babel 8.

https://github.com/babel/babel/blob/df5c1ebb45040eff6c7146b7bee3a5142edc6223/packages/babel-types/src/definitions/jsx.ts#L45

We use `process.env.BABEL_8_BREAKING` to toggle breaking changes. If it's the first time you contribute to Babel, please also checkout our [contributing guide](https://github.com/babel/babel/blob/main/CONTRIBUTING.md).
