### ISSUE TITLE
[Bug]: Incorrect translation completely changed meaning of if clause

### ISSUE THREAD

**Issue by adityatoshniwal** [babel/babel#14468]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

This is the original code:
```js
this._eventListeners = this._eventListeners.filter((e)=>{
  if(e.event === event) {
    return e.callback.toString()!=callback.toString();
  }
  return e.event!=event && e.callback.toString()!=callback.toString();
});
```
and this is the translated code for the filter function from the bundle file:
```js
return (n.event === e || n.event != e) && n.callback.toString() != t.toString()
```

### Configuration

I'm using webpack with config:

```
{
  test: /\.jsx?$/,
  exclude: [/node_modules/, /vendor/],
  use: {
    loader: 'babel-loader',
    options: {
      presets: [['@babel/preset-env', {'modules': 'commonjs', 'useBuiltIns': 'usage', 'corejs': 3}], '@babel/preset-react', '@babel/preset-typescript'],
      plugins: ['@babel/plugin-proposal-class-properties', '@babel/proposal-object-rest-spread'],
    },
  },
}
```

### Current and expected behavior

The code basically filters all the event listeners from the _eventListeners array of object {event: 'eventname', callback: func}.
Inside the filter it checks if the event name matches. If it matches, then return if callback matches.
However, the code is now translated to be based on callback match only. I think is incorrect. I have changed `e.event!=event && e.callback.toString()!=callback.toString();` to `true` to make it work for me.

### Environment

  System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.10.2 => 7.13.8 
    @babel/eslint-parser: ^7.17.0 => 7.17.0 
    @babel/eslint-plugin: ^7.17.7 => 7.17.7 
    @babel/plugin-proposal-class-properties: ^7.10.4 => 7.13.0 
    @babel/plugin-proposal-object-rest-spread: ^7.10.1 => 7.14.7 
    @babel/plugin-syntax-jsx: ^7.16.0 => 7.16.7 
    @babel/preset-env: ^7.10.2 => 7.13.9 
    @babel/preset-react: ^7.12.13 => 7.13.13 
    @babel/preset-typescript: ^7.8.3 => 7.16.0 
    babel-loader: ^8.1.0 => 8.2.3 
    babelify: ~10.0.0 => 10.0.0 
    eslint: ^7.19.0 => 7.32.0 
    karma-babel-preprocessor: ^8.0.0 => 8.0.1 
    webpack: ^5.21.2 => 5.61.0

**Comment by nicolo-ribaudo** [comment]
1. Can you show also where `event` is defined and how it's transformed? (or is it the `event` global?)
2. That code looks minified. Can you try disabling the minifier (terser?) in your webpack config, and see if the bug persists?

**Comment by nicolo-ribaudo** [comment]
Btw, if `e` in the output code still refers to the `event` variable of the original code, that transform looks correct to me.

```js
  if(e.event === event) {
    return e.callback.toString()!=callback.toString();
  }
  return e.event!=event && e.callback.toString()!=callback.toString();
```
->
```js
  if(e.event === event) {
    return e.callback.toString()!=callback.toString();
  }
  if (e.event != event) {
    return e.callback.toString()!=callback.toString();
  } else {
    return false;
  }
```
->
```js
  if(e.event === event || e.event != event) {
    return e.callback.toString()!=callback.toString();
  } else {
    return false;
  }
```
-> 
```js
  return (e.event === event || e.event != event) && e.callback.toString()!=callback.toString();
```

**Comment by adityatoshniwal** [comment]
> 1. Can you show also where `event` is defined and how it's transformed? (or is it the `event` global?)
Here is the complete code
```js
  deregisterListener(event, callback) {
    if(callback) {
      this._eventListeners = this._eventListeners.filter((e)=>{
        if(e.event === event) {
          return e.callback.toString()!=callback.toString();
        }
        return true;
      });
    } else {
      this._eventListeners = this._eventListeners.filter((e)=>e.event!=event);
    }
  }
```

**Comment by adityatoshniwal** [comment]
> ```js
>   if(e.event === event) {
>     return e.callback.toString()!=callback.toString();
>   }
>   if (e.event != event) {
>     return e.callback.toString()!=callback.toString();
>   } else {
>     return false;
>   }
> ```




> Btw, if `e` in the output code still refers to the `event` variable of the original code, that transform looks correct to me.
> 
> ```js
>   if(e.event === event) {
>     return e.callback.toString()!=callback.toString();
>   }
>   return e.event!=event && e.callback.toString()!=callback.toString();
> ```
> 
> ->
> 
> ```js
>   if(e.event === event) {
>     return e.callback.toString()!=callback.toString();
>   }
>   if (e.event != event) {
>     return e.callback.toString()!=callback.toString();
>   } else {
>     return false;
>   }
> ```
> 
> ->
> 
> ```js
>   if(e.event === event || e.event != event) {
>     return e.callback.toString()!=callback.toString();
>   } else {
>     return false;
>   }
> ```
> 
> ->
> 
> ```js
>   return (e.event === event || e.event != event) && e.callback.toString()!=callback.toString();
> ```

Yeah. Looking at the steps you mentioned, it looks like a correct transformation. But, it behaves different if used in dev and prod mode. Looks like somehow `e.callback.toString()!=callback.toString()` returns true in dev mode but false in prod mode for few of my functions which are not identical.
OK. I think this bug can be closed. Sorry for the noise. But still, what could have made `e.callback.toString()!=callback.toString()` the value to change ?

**Comment by nicolo-ribaudo** [comment]
If `e.callback` is a function, compiling it will change it's contents. It's possible that you have to similar functions in two different places, and when compiled they have different sources.

For example, consider this code:
```js
console.log(function ({ x }) { return x }.toString());
console.log(function ({ x }) { return x }.toString());
```
they have the same code, but when compiled with Babel they are different:
```js
console.log(function (_ref) {
  var x = _ref.x;
  return x;
}.toString());
console.log(function (_ref2) {
  var x = _ref2.x;
  return x;
}.toString());
```

I strongly recommend not relying on a function's `.toString()`.

**Comment by adityatoshniwal** [comment]
Thank you @nicolo-ribaudo for looking into this. I will check for any alternative to function toString.
