### ISSUE TITLE
Best Practices for Promisifying

### ISSUE THREAD

**Issue by francoislaberge** [babel/babel#1447]
Now that Promises are included in io and/or polyfilled by babel. What technique/module do people recommend for promisifying node/node-style async functions? Think bluebird's promisify. 

I've found solutions, but would rather move towards a standard solution if there is one.

Considerations much appreciated,
Francois

**Comment by loganfsmyth** [comment]
Sorry, please see Babel's README:

> For questions and support please visit the [gitter room](https://gitter.im/babel/babel) or StackOverflow. The Babel issue tracker is exclusively for bug reports and feature requests.

I'm sure someone would be happy to chat over on Gitter.

**Comment by francoislaberge** [comment]
Thanks will do.
