### ISSUE TITLE
[Bug]: typescript enum error: Enum member must have initializer

### ISSUE THREAD

**Issue by PPpro** [babel/babel#14473]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```ts
enum EnumA {
    A = 1,
    B
}

enum EnumB {
    A = EnumA.B,
    B,
}
``` 

#### Expected behavior:
The input code works on typescript compiler, here is the compile result on [Typescript Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/KYOwrgtgBAouEEEoG8BQUNSQXigRgBp1MAhVAX1VVElnhJWIxzkgQDoSjMouLUgA)

#### Current behavior:
while it throw error on  bable plugin transfrom-typescript, here is the compile result on [Babel Playground](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYOwrgtgBAouEEEoG8BQUNSQXigRgBp1MAhVAX1VVElnhJWIxzkgQDoSjMouLUgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.17.9&externalPlugins=%40babel%2Fplugin-transform-typescript%407.15.8&assumptions=%7B%7D):

### Environment
```
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.13.10 => 7.13.10
    @babel/preset-env: ^7.8.7 => 7.8.7
    @babel/plugin-transform-typescript: ^7.15.8 => 7.15.8
```

**Comment by liuxingbaoyu** [comment]
[repl](https://deploy-preview-2652--babel.netlify.app/repl#?browsers=&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=KYOwrgtgBAouEEEoG8BQUNSQXigRgBp1MAhVAX1VVElnhJWIxzsgQDoSjMouKg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.18.13&externalPlugins=%40babel%2Fplugin-syntax-typescript%407.18.6&assumptions=%7B%7D)

Seems to have been fixed, I'll close it for now, feel free to reopen it if the problem persists.
