### ISSUE TITLE
Update @babel/eslint-parser use of eslint-scope to the latest version

### ISSUE THREAD

**Issue by Standard8** [babel/babel#14496]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

eslint-scope v5.1.1 was released in Sept 2020, and there is now a eslint-scope v7.1.1 that ESLint v8 uses.

eslint-visitor-keys (v2.1.0) is also about a year out of date, and ESLint v8 uses 3.1.1.

For one of the projects I'm working on, we're using ESLint v8 and having the differences makes some things difficult to handle.

### Describe the solution you'd like

Would it be possible to upgrade these modules to the latest versions? Would this require a breaking change and only included in babel 8?

There is #13343 which looks to indicate that dependencies need to be updated, but that doesn't seem to be active?

### Describe alternatives you've considered

We can (and probably will) work around this on our side, but I thought I'd ask as there's newer functionality in eslint-scope & eslint-visitor-keys that may be useful for Babel/eslint-parser.

**Comment by nicolo-ribaudo** [comment]
Depending on what breaking changes there are in the new major versions of those packages we might have to wait for Babel 8, but yes we should update them.
