### ISSUE TITLE
Plugins are not included with whitelisting

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#1450]
If the `whitelist` option is passed, the plugins are not executed, even if the names of the plugins are listed in the `whitelist` array.

**Comment by sebmck** [comment]
Two possible solutions here:

1. Fix `whitelist` to accept plugin transformer keys.
2. Implicit whitelist when using plugins.

Leaning more towards 2. since it seems the most logical.

**Comment by DmitrySoshnikov** [comment]
Yeah, agreed, 2 seems the better way to go (since we already explicitly say via the `plugins` option, what else should be included to the run).

**Comment by DmitrySoshnikov** [comment]
Thanks for the quick fix!

**Comment by fkling** [comment]
Awesome, I also ran into this issue (but it wasn't a big deal for me...). :+1:

**Comment by amasad** [comment]
thanks, new version please?

**Comment by sebmck** [comment]
Released as of 5.2.16, thanks!
