### ISSUE TITLE
Extending class fails if super class's prototype.constructor is incorrect

### ISSUE THREAD

**Issue by hgl** [babel/babel#1451]
Many es5 code use this pattern:

```js
function B() {}
B.prototype = {...};
```

And for code like this
```js
class A extends B {
  constructor() {
    super();
  }
}
```
babel uses 
```js
_get(Object.getPrototypeOf(A.prototype), "constructor", this)
```
to get super class, which is `Object` actually.

I wonder why can't `B` be used directly in the compiled code?

**Comment by sebmck** [comment]
```javascript
class A extends B {
  constructor() {
    super();
  }
}
A.prototype = someOtherObject;
```

Suddenly your code is now broken. In fact, the default constructor that's used for derived classes should also have this check. Feel free to enable [loose mode for classes](http://babeljs.io/docs/usage/loose/) to get the behaviour you want.

**Comment by hgl** [comment]
If I'm not wrong, `super` refers to `A.__proto__`, so even if `A.prototype` is changed, `super()` should still call `A.__proto__` which is `B`, with `this` referring to an object whois `__proto__` is the new `A.prototype`.

What do you mean by "code is now broken"?

**Comment by hgl** [comment]
Step 4 in http://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-getsuperconstructor

Let `superConstructor` be `activeFunction.[[GetPrototypeOf]]()`.

This is not necessarily `activeFunction.prototype.__proto__.constructor`. And since the `_inherits` helper already sets `A.__proto__`, I think the generated code should use that.

P.S. traceur uses `A.__proto__` to get `B`.

**Comment by hgl** [comment]
@sebmck not saying you should change it or anything, but would like to hear your opinion on this. :)
