### ISSUE TITLE
[Bug]: original assignment statement inside of braces is not transpiled properly

### ISSUE THREAD

**Issue by Meir017** [babel/babel#14514]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var fn;
(fn) = function () {};
var name = fn.name
```

`name` should have the value `"fn"`

### Configuration

https://babeljs.io/repl/#?browsers=%20Chrome%20%3E%3D%2067%2C%20Firefox%20%3E%3D%2063%2C%20Edge%20%3E%3D%2017%2C%20Opera%20%3E%3D%2057%2C%20Safari%20%3E%3D%2011.1%0A&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAZgdg3AKABSwJQQLzQK4wMZgCWA9jEqgN4C-iepAzpDAIYC2Im0MAdC-3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.17.11&externalPlugins=%40babel%2Fplugin-transform-async-to-generator%407.16.5&assumptions=%7B%7D

### Current and expected behavior

the output should a syntax matching the input syntax

### Environment

running inside https://bablejs.io/repl

### Possible solution

This scenario works properly with typescript, see https://www.typescriptlang.org/play?#code/G4QwTgBAZgdg3BAFLAlBAvNArjAxgFwEsB7GRFAbwF84g

**Comment by JLHwung** [comment]
```
var fn;
(fn) = function () {};
var name = fn.name
```

The `name` here should be an empty string, see the [spec 13.15.2](https://tc39.es/ecma262/#sec-assignment-operators-runtime-semantics-evaluation):

> If [IsAnonymousFunctionDefinition](https://tc39.es/ecma262/#sec-isanonymousfunctiondefinition)([AssignmentExpression](https://tc39.es/ecma262/#prod-AssignmentExpression)) and [IsIdentifierRef](https://tc39.es/ecma262/#sec-static-semantics-isidentifierref) of [LeftHandSideExpression](https://tc39.es/ecma262/#prod-LeftHandSideExpression) are both true, then
i. Let rval be ? [NamedEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-namedevaluation) of [AssignmentExpression](https://tc39.es/ecma262/#prod-AssignmentExpression) with argument lref.[[ReferencedName]].

And IsIdentifierRef returns false for the parenthesized identifier reference `(fn)`.

Both the Babel output and TS output look good to me: `fn.name` is an empty string after transpilation. What do you mean by "works properly with typescript"?

**Comment by Meir017** [comment]
My bad. I meant to write that babel removes the parenthesis around the variable

The original code returns an empty string, after transpiling through babel the parenthesis are removed and the name is "fn"

**Comment by Meir017** [comment]
@JLHwung thanks for the quick fix!
