### ISSUE TITLE
[Bug]: @babel/runtime/helpers/setPrototypeOf.js throws error: Cannot add property __esModule, object is not extensible

### ISSUE THREAD

**Issue by Jack-Works** [babel/babel#14527]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

https://cdn.jsdelivr.net/npm/@babel/runtime@7.17.9/helpers/setPrototypeOf.js

```js
function _setPrototypeOf(o, p) {
  module.exports = _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  }, module.exports.__esModule = true, module.exports["default"] = module.exports;
  return _setPrototypeOf(o, p);
}

module.exports = _setPrototypeOf, module.exports.__esModule = true, module.exports["default"] = module.exports;
```

It writes `__esModule` and `default` property to native `Object.setPrototypeOf`. It throws an error when `Object.setPrototype` is frozen.

![image](https://user-images.githubusercontent.com/5390719/166897132-e15c4389-de17-4b69-ba13-b25fc12a39b4.png)

### Current and expected behavior

Not modifying built-in

### Environment

Unrelated

**Comment by nicolo-ribaudo** [comment]
Since every engine that supports `setPrototypeOf` also supports `bind`, we could replace `Object.setPrototypeOf` with `Object.setPrototypeOf.bind()`

**Comment by Jack-Works** [comment]
> Since every engine that supports `setPrototypeOf` also supports `bind`, we could replace `Object.setPrototypeOf` with `Object.setPrototypeOf.bind()`

Should I open a PR for this?

**Comment by magic-akari** [comment]
This is not an unique case.

```JavaScript
module.exports = _construct = Reflect.construct, module.exports.__esModule = true, module.exports["default"] = module.exports;
```

**Comment by nicolo-ribaudo** [comment]
I don't think we can transform it in a different way,  we can only go through our helpers and add `.bind` where needed.

> Should I open a PR for this?

Yes please!
