### ISSUE TITLE
[Bug]: Error Installing Optional Chaining Plugin

### ISSUE THREAD

**Issue by AT-Freelance** [babel/babel#14540]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

I get error after running this command
npm install --save-dev @babel/plugin-proposal-optional-chaining
Code:
https://replit.com/@AT-Freelance/MintcreamRundownDisassembly

### Configuration file name

package.json

### Configuration

{
  "name": "node",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "h": "node ./src/h.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "express": "^4.18.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.17.10",
    "@babel/core": "^7.17.10",
    "@babel/node": "^7.17.10",
    "@babel/preset-env": "^7.17.10",
    "nodemon": "^2.0.16"
  }
}

### Current and expected behavior

I am trying to install the abovementioned plugin on my VS Code Terminal (which I've opened via WSL Ubuntu on Windows 10) but get unexpected error:
```
Running this:
npm install --save-dev @babel/plugin-proposal-optional-chaining
Gives This Error:
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /home/a/node/node_modules/babel-plugin-dynamic-import-node
npm ERR! dest /home/a/node/node_modules/.babel-plugin-dynamic-import-node-bCevrLwi
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/home/a/node/node_modules/babel-plugin-dynamic-import-node' -> '/home/a/node/node_modules/.babel-plugin-dynamic-import-node-bCevrLwi'
npm ERR!  [Error: EACCES: permission denied, rename '/home/a/node/node_modules/babel-plugin-dynamic-import-node' -> '/home/a/node/node_modules/.babel-plugin-dynamic-import-node-bCevrLwi'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/home/a/node/node_modules/babel-plugin-dynamic-import-node',
npm ERR!   dest: '/home/a/node/node_modules/.babel-plugin-dynamic-import-node-bCevrLwi'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/a/.npm/_logs/2022-05-10T20_23_41_201Z-debug-0.log
```

### Environment

  System:
    OS: Linux 4.4 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm

**Comment by liuxingbaoyu** [comment]
This doesn't seem to be a problem with babel, you can try running it with `sudo`.

**Comment by JLHwung** [comment]
EACCESS is permission issue reported from your file system. See https://stackoverflow.com/questions/16151018/how-to-fix-npm-throwing-error-without-sudo for solutions.

There is nothing Babel can do on our side.
