### ISSUE TITLE
[Bug]: parser/whiteSpace.js 

### ISSUE THREAD

**Issue by wj453245456** [babel/babel#14547]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

import * as babel from '@babel/core';
import presetEnv from "@babel/preset-env";

var global = typeof self !== 'undefined' ? self : global;
global.babelTransform1 = function(code,option){
  return babel.transform(code,{
    babelrc: false,
    presets:[presetEnv],
    ...option
  })
} 

### Current and expected behavior

In @babel/parser/util/whiteSpace.js 

Yhe code : export const skipWhiteSpaceInLine =
  /(?:[^\S\n\r\u2028\u2029]|\/\/.*|\/\*.*?\*\/)*/y;

Compile and package Babel through webpack and Babel

After Compile:
var skipWhiteSpaceInLine = new RegExp(\"(?:[^\\\\S\\\\n\\\\r\\\\u2028\\\\u2029]|\\\\/\\\\/.*|\\\\/\\\\*.*?\\\\*\\\\/)*\", \"y\");

The package can't run in IE11.

The Regexp is Wrong
![image](https://user-images.githubusercontent.com/28704757/168054309-e4955d5f-8b5b-453d-b050-5d0efea01dc1.png)

### Environment

Babel:latest
webpack:4

**Comment by liuxingbaoyu** [comment]
![](https://user-images.githubusercontent.com/30521560/168083260-f34b1e08-705d-4bad-9bad-c4c0fca15caa.png)

**Comment by JLHwung** [comment]
> Yhe code : export const skipWhiteSpaceInLine =
/(?:[^\S\n\r\u2028\u2029]|//.|/*.?*/)*/y;

The regex in `@babel/parser` is different to the one you posted:

https://github.com/babel/babel/blob/6dc633e71ef65943554e4087c39a4b939b0eadd0/packages/babel-parser/src/util/whitespace.js#L26-L27

As @liuxingbaoyu mentioned, the one you posted is not a valid regex after all. Did you run any code preprocessing tool before Babel?

**Comment by wj453245456** [comment]
> ![](https://user-images.githubusercontent.com/30521560/168083260-f34b1e08-705d-4bad-9bad-c4c0fca15caa.png)

It's my mistake.I use babel to compile @babel/core and @babel/preset-env

**Comment by wj453245456** [comment]
> > Yhe code : export const skipWhiteSpaceInLine =
> > /(?:[^\S\n\r\u2028\u2029]|//.|/_.?_/)*/y;
> 
> The regex in `@babel/parser` is different to the one you posted:
> 
> https://github.com/babel/babel/blob/6dc633e71ef65943554e4087c39a4b939b0eadd0/packages/babel-parser/src/util/whitespace.js#L26-L27
> 
> As @liuxingbaoyu mentioned, the one you posted is not a valid regex after all. Did you run any code preprocessing tool before Babel?

It's my mistake.The right code is `const skipWhiteSpaceInLine = /(?:[^\S\n\r\u2028\u2029]|\/\/.*|\/\*.*?\*\/)*/y;
I` use babel to compile @babel/core and @babel/preset-env
wanted to transfrom online in IE11
before import @bable/core ,Babel Polyfill has been imported
when change code from babel-polyfill
![image](https://user-images.githubusercontent.com/28704757/168122004-9aae02b1-3c0a-4ed7-8b63-becfbbcc94a3.png)
It will be run with no error
IE11 cant use ‘y’ flag

**Comment by liuxingbaoyu** [comment]
```js
var out = babel.transformSync(String.raw`skipWhiteSpaceInLine = /(?:[^\S\n\r\u2028\u2029]|\/\/.*|\/\*.*?\*\/)*/y;`, {
    configFile: false,
    plugins: [["polyfill-corejs3", {"method": "usage-global",  "version": "3.21"}]],
    targets: {ie:11},
    presets: [ ["@babel/preset-env"]],
});
console.log(out.code);
```
Did you specify core-js = 3.21?
The default 3.0 does not include `es.regexp.sticky.js`.

**Comment by liuxingbaoyu** [comment]
Since this issue has been inactive for a long time, I will close it for now, feel free to reopen it if the issue persists.
