### ISSUE TITLE
[Bug]: Can't import the named export 'SetArray' from non EcmaScript module

### ISSUE THREAD

**Issue by rathorekuldeepsingh** [babel/babel#14550]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

yarn start

### Configuration

./node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs

### Current and expected behavior

getting compilation error as 

Failed to Compile
./node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'SetArray' from non EcmaScript module (only default export is available)

### Environment

System:
    OS: macOS 12.0.1
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  npmPackages:
    @babel/cli: ^7.7.5 => 7.17.10 
    @babel/core: 7.7.4 => 7.7.4 
    @babel/plugin-proposal-class-properties: ^7.13.0 => 7.16.7 
    @babel/plugin-proposal-json-strings: ^7.7.4 => 7.16.7 
    @babel/plugin-syntax-dynamic-import: ^7.7.4 => 7.8.3 
    @babel/plugin-syntax-import-meta: ^7.7.4 => 7.10.4 
    @babel/preset-env: ^7.7.6 => 7.17.10 
    @babel/preset-react: ^7.7.4 => 7.16.7 
    @babel/runtime-corejs2: ^7.7.6 => 7.17.11 
    babel-eslint: 10.0.3 => 10.0.3 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-loader: 8.0.6 => 8.0.6 
    babel-plugin-named-asset-import: ^0.3.5 => 0.3.8 
    babel-preset-react-app: ^9.1.0 => 9.1.2 
    eslint: ^6.6.0 => 6.8.0 
    jest: 24.9.0 => 24.9.0 
    webpack: 4.41.2 => 4.41.2 

React - ^16.12.0

**Comment by nicolo-ribaudo** [comment]
What is the full stack trace of that error?

**Comment by rathorekuldeepsingh** [comment]
@nicolo-ribaudo 

After successfully building project at the time of compilation i am getting this error without any other stack trace 

<img width="966" alt="image" src="https://user-images.githubusercontent.com/30040688/168405684-dde0dfd3-0094-47f4-a205-8bbd727421d0.png">

**Comment by nicolo-ribaudo** [comment]
This is either a bug with the bundler you are using, or a bundler configuration error.

Babel uses `require` to load `@jridgewell/gen-mapping` (https://github.com/jridgewell/gen-mapping), but your bundler is picking up the E version instead of the CJS one.
This would still be fine in theory, but then your bundler does the opposite thing: when importing `@jridgewell/set-array` from an ESM file, it's loading the CJS version. This is weird but it would still be fine, but apparently the bundle you are using does not support Node.js-like inrerop for importing CJS in ESM.

**Comment by nicolo-ribaudo** [comment]
You will probably be able to reproduce this bundler problem even without using Babel, you only need to require that `gen-mapping` package.

**Comment by divijande12** [comment]
Facing the same issue with @jridgewell/gen-mapping importing issue, do we have any solution for it because this type of problem was not there when I run the project earlier when I clone the project again and hit the npm install I ran onto this problem for the first time. I need solution for this is this th bug with babel or the configuration.

**Comment by rathorekuldeepsingh** [comment]
@divijande12 

Still figuring what is the issue For me  this project is working fine in linux but in windows and mac i am facing this issue

**Comment by divijande12** [comment]
@rathorekuldeepsingh Okay I'm also figuring out what will be the solution for this issue if found any solution to this will you please comment here .
Thanks

**Comment by nicolo-ribaudo** [comment]
Are you all trying to bundle Babel, or is the error thrown while _running_ Babel?

**Comment by DariaCohen** [comment]
Hey, 
is there a solution for this problem? I am having the same issue :(

**Comment by rathorekuldeepsingh** [comment]
@nicolo-ribaudo Please reopen this issue many of us are still facing this issue

**Comment by nicolo-ribaudo** [comment]
Either provide a repository that I can run to reproduce the bug, or report it to the bundled you are using. I'm almost certain that this is not a Babel bug, but I'm happy to take a look at a failing repository.

**Comment by JLHwung** [comment]
Here is a similar SO question: https://stackoverflow.com/questions/69343038/cant-import-the-named-export-xxxx-from-non-ecmascript-module-only-default-expo, please make sure your webpack config supports `.mjs`.

**Comment by alimsadeghi1** [comment]
I still have the same issue

**Comment by nicolo-ribaudo** [comment]
@alimsadeghi1 https://github.com/babel/babel/issues/14550#issuecomment-1131481853=

**Comment by cha0s** [comment]
Same issue.

I'll see about making a repro.

**Comment by uddipacharjee** [comment]
facing the same issue. Any update please?

**Comment by nicolo-ribaudo** [comment]
@uddipacharjee https://github.com/babel/babel/issues/14550#issuecomment-1131481853

**Comment by Tsaqif-Aushaf-Farodis** [comment]
![image](https://user-images.githubusercontent.com/62985235/190048852-76365f76-7f8b-4f6e-ab04-0d39589dbf02.png)
I also have the same issue, has anyone found a solution?

**Comment by liuxingbaoyu** [comment]
@Tsaqif-Aushaf-Farodis https://github.com/babel/babel/issues/14550#issuecomment-1131481853

**Comment by AlonsoK28** [comment]
in my case this issue was caused by import the following for error with `vscode` autocompletation tab

`import { template } from '@babel/core';`
