### ISSUE TITLE
[Bug]: Update from 7.17.10 to 7.17.12 breaks Charka Theme in monorepo

### ISSUE THREAD

**Issue by Poolshark** [babel/babel#14560]
### How are you using Babel?

babel-loader (webpack)

### Input code

Unfortunately I cannot reproduce my entire monorepo. I can however, provide package.json's in case that helps.

### Configuration file name

`webpack.config.ts`

### Configuration
```ts
{
    test: /\.(ts|tsx)?$/,
    use: {
      loader: require.resolve("babel-loader"),
      options: {
        generatorOpts: { compact: false },
        presets: ["@babel/preset-env", ["@babel/preset-react", { runtime: "automatic" }], "@babel/preset-typescript"],
        plugins: [
          ["lodash"],
          ["relay", { artifactDirectory: resolve(__dirname, "../../../frontend/__generated__"), eagerESModules: true }],
          ["@babel/plugin-transform-runtime"],
        ],
      },
    },
  },
```

### Current and expected behavior

**Current behaviour:**
Running the application with `webpack-dev-server` works but without theme support (@babel/core v7.17.12)

**Expected behaviour:**
Theme support like with `@babel/core v7.17.10`

### Environment

```
"@babel/core": "^7.17.10",
"@babel/plugin-transform-runtime": "^7.17.12",
"@babel/preset-env": "^7.17.12",
"@babel/preset-react": "^7.17.12",
"@babel/preset-typescript": "^7.17.12",
"@babel/runtime": "^7.17.9",
```

### Possible solution

At the moment I downgrade to `@babel/core v7.17.10`.

### Additional context

I guess, I cannot rely on a fix since my monorepo is complicated and it might be somehow related to the structure and/or package dependencies. However, it was working nicely before and only since the update from `@babel/core v7.17.10` to `@babel/core v7.17.12` the problem arose. I can reproduce the issue by down/upgrading between these versions.
 
 I can live with the downgrade but maybe someone else experienced the same problem and thus it might be worth to have a look at this problem.

**Comment by nicolo-ribaudo** [comment]
Do you at least have a stack trace? Does the error happen at build time or when running the compiled code?

**Comment by nicolo-ribaudo** [comment]
The only `@babel/core` changes between those versions have been to internal TS type annotations or to test files :thinking:

**Comment by Poolshark** [comment]
Hey @nicolo-ribaudo

thanks for the very quick response! Sorry, was out of office yesterday already.

I have tested a bit now and to be honest, it just got weirder... Regarding your request for a _stack trace_: since I get no actual error, I also can't provide a stack trace for the problem. Also, I did not yet deploy the bundled version of the application, so at the moment this only happens when running `webpack-dev-server`.

I might have to add some info about my current setup in the monorepo. I run and build all apps from a **centralised package** `config` within my monorepo. This package also builds my lambdas which are necessary for my backend applications. Furthermore, I have a package which provides **shared components** for my frontend applications. This package contains the **Theme Provider** which is responsible for implementing the Chakra Theme into our applications. 

However, I have figured that when running with `@babel/core v7.17.12` the provider values for the Chakra Provider (there is something called `useTheme()` from which I have access to all the themeing variables) is empty! If I run the application with `v7.17.10` the provider values get forwarded normally.

This behaviour is particularly strange when you say that the update contains only internal TS annotations...

As always with NPM I fear that this might not have something to do with `babel` but a combination of `webpack`, `babel` and the monorepo structure.

**Comment by nicolo-ribaudo** [comment]
Could you share your lockfile with the working setup and with the broken setup? It might be caused by a different Babel package used by babel/core.

**Comment by Poolshark** [comment]
Alright, seems I have found the solution 🙌

Not sure wether it has something to do with the internal type annotations but **adding `@babel/plugin-transform-runtime v7.17.12` and `@types/babel__plugin-transform-runtime v.7.9.2`** to the application's dev-dependencies, did the job.

Thanks for the help!

**Comment by nicolo-ribaudo** [comment]
I have no idea about how that could fix the big, but I'm happy that it worked 😬

**Comment by Poolshark** [comment]
Well, me neither 🙈
But in frontend web development sometimes you just starting to accept miracles 😂

I guess I will have a different problem on one of the next minor updates from some other package anyway 😜
