### ISSUE TITLE
[Bug]: notarget No matching version found for @babel/parser@^7.18.0

### ISSUE THREAD

**Issue by visheshtyagim** [babel/babel#14569]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

> npm install @babel/traverse

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/parser@^7.18.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget 

### Current and expected behavior

Not getting the latest @babel/parser@^7.18.0 version in npm install.

npm install --save-dev @babel/parser
npm notice save @babel/parser is being moved from dependencies to devDependencies

+ @babel/parser@7.17.12
updated 1 package in 6.886s

### Environment

Node v10.14.1
NPM v6.4.1
"babel-polyfill": "^6.5.0",
"babel-eslint": "~6.0.4",

**Comment by nicolo-ribaudo** [comment]
Version 7.18.0 is on npm: https://www.npmjs.com/package/@babel/parser

It's either a bug with the npm registry itself, or most likely with a cache/proxy between your machine and the npm servers.
