### ISSUE TITLE
Unspected execution order with decorators

### ISSUE THREAD

**Issue by PillowPillow** [babel/babel#1457]
Hi, i'm playing with the decorator feature and i don't understand the execution order when i add more than one decorator.

decorators:
```javascript
    function first() {
        console.log('first:1');
        return () => console.log('first:2');
    }
    function second() {
        console.log('second:1');
        return () => console.log('second:2');
    }
```

Decorator:class
```javascript
    @first()
    @second()
    class fubar {
        constructor() {}
        method() {}
    }
```
result:
>second:1
>second:2
>first:1
>first:2

Decorator:method
```javascript
    class fubar {
        constructor() {}
        @first()
        @second()
        method() {}
    }
``` 

result:
>first:1
>second:1
>first:2
>second:2

---
In order to have a point of comparison i tryed with the TypeScript implementation

result:
>first:1
>second:1
>second:2
>first:2

What's the right behaviour? Is the difference between the method and class normal?

**Comment by sebmck** [comment]
Yeah, the method decorator order is incorrect. I fixed it for the class wrappers but not for the methods it seems.

**Comment by sebmck** [comment]
Fixed as of 5.2.16, thanks!

**Comment by PillowPillow** [comment]
The class decorator behaviour and the method decorator behaviour are still different in 5.2.16.
Are you sure it's the right order? :)

````javascript
function classFirst() {
    console.log('class:first:1');
	return () => console.log('class:first:2');
}

function classSecond() {
    console.log('class:second:1');
	return () => console.log('class:second:2');
}
function methodFirst() {
    console.log('method:first:1');
	return () => console.log('method:first:2');
}

function methodSecond() {
    console.log('method:second:1');
	return () => console.log('method:second:2');
}

@classFirst()
@classSecond()
class FuBar {
	@methodFirst()
	@methodSecond()
	method() {}
}
````
````
//result:
method:second:1
method:first:1
method:second:2
method:first:2
class:second:1
class:second:2
class:first:1
class:first:2
````

**Comment by sebmck** [comment]
Yes, class decorators are installed/executed last. Method decorators are executed bottom-up. They can't be installed right after they've been declared due to output code complexity constraints and this is considered to be an ok compromise. You can see the spec [here](https://github.com/wycats/javascript-decorators).

**Comment by PillowPillow** [comment]
ok, thanks
