### ISSUE TITLE
[Bug]: @babel/runtime v7.18.0 cause a runtime "regeneratorRuntime is not defined" error

### ISSUE THREAD

**Issue by tinder1024** [babel/babel#14576]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

placehoder

### Current and expected behavior

I thought the problem might be 
![image](https://user-images.githubusercontent.com/8242746/169772027-14765f1e-f16c-4c1f-80ef-6572d5b21e52.png)

### Environment

@babel/runtime version 7.18.0

**Comment by nicolo-ribaudo** [comment]
What is the full stack trace?

**Comment by cuitianze** [comment]
same issue

**Comment by IanTorquato** [comment]
I'm having the same problem here. In my case `@babel/runtime` is a sub-dependency and the file (`regeneratorRuntime `) is not found in node_module (`\node_modules\@babel\runtime\helpers\esm`)

This issue appeared when updating `antd` from `@^4.19.5` to `@^4.20.0`

Using `resolutions` in package.json, I forced it to version `7.12.5` as described [here](https://github.com/webpack/webpack/issues/11467#issuecomment-727014123), removed node_modules and cleared yarn cache. Unfortunately that was not enough, still with the error

I also tried keeping on version `7.17.9`
```
"resolutions": {
    "@babel/runtime": "7.17.9"
  },
```

**Comment by cuitianze** [comment]
[CompileProject][INFO] Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/esm/regeneratorRuntime" from "node_modules/@ant-design/pro-card/node_modules/@ant-design/pro-utils/es/hooks/useDebounceFn/index.js".

**Comment by yerlink** [comment]
lock the old dependency version:
    "@babel/runtime": "7.17.2",
    "@babel/plugin-transform-runtime": "7.17.0",

**Comment by nicolo-ribaudo** [comment]
# Note

The `regeneratorRuntime is not defined` errors are different from the error about `@babel/runtime/helpers/esm/regeneratorRuntime`. The ant-design maintainers are already aware of the second one.

**Comment by nicolo-ribaudo** [comment]
@drbeat Can you share a gist containing your lockfile?

**Comment by drbeat** [comment]
So after setting @babel/preset-react in resolutions it works now.
`
"resolutions": {
    "@babel/preset-react": "7.17.12"
  },
`

**Comment by markwoon** [comment]
> This is a bug with some other packages that has a dependency on `regenerator-runtime` but doesn't specify it in their package.json. They were lucky because it was a dependency of `@babel/runtime` so it was still loaded, but in Babel 7.18.0 it doesn't happen anymore.

This implies that if I add `regenerator-runtime` myself, things should work again, but that's not the case.

I'm declaring this dependency and still get the error.

In my case, the stacktrace is:

```react-table.development.js?9781:272 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (react-table.development.js?9781:272:1)
    at useAsyncDebounce (react-table.development.js?9781:350:6)
    at TextFilter (Text.js?0cad:62:54)
    at renderWithHooks (react-dom.development.js?f8c1:16175:1)
    at mountIndeterminateComponent (react-dom.development.js?f8c1:20913:1)
    at beginWork (react-dom.development.js?f8c1:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?f8c1:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?f8c1:4210:1)
    at invokeGuardedCallback (react-dom.development.js?f8c1:4274:1)
    at beginWork$1 (react-dom.development.js?f8c1:27405:1)```

**Comment by nicolo-ribaudo** [comment]
You also have to import that library in your code, since it's side-effectful.

**Comment by nicolo-ribaudo** [comment]
I opened https://github.com/babel/babel/pull/14581 to make this error more rare. However, please continue reporting this bug to the affected libraries so that they can fix it.

**Comment by daejong123** [comment]
same issue in vue-cli with @vue/cli-plugin-babel.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/19252403/170162115-074e1de6-d325-46a6-8bd7-38c3dc8cda52.png">

**Comment by mansion-sun** [comment]
看报错是缺少@babel/runtime导致，我在devDependencies安装"@babel/runtime": "^7.18.3",同样解决问题；今天另一个项目升级遇到了error network request to https://cdn.npmmirror.com/packages/%40ant-design/pro-utils/1.42.0/pro-utils-1.42.0.tgz failed, reason: getaddrinfo ENOTFOUND cdn.npmmirror.com，我想是不是新版本缺少ant-design/pro-utils依赖？

**Comment by taylordlankford** [comment]
error Generating JavaScript bundles failed
10:14:10 AM: Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime' in '/opt/build/repo/node_modules/rc-util/es/React'
10:14:10 AM: If you're trying to use a package make sure that '@babel/runtime/helpers/esm/regeneratorRuntime' is installed. If you're trying to use a local file make sure that the path is correct.

**Comment by nicolo-ribaudo** [comment]
Update rc-util.
