### ISSUE TITLE
Destructuring mistakenly uses adjusted name for property on target object

### ISSUE THREAD

**Issue by jgwhite** [babel/babel#1458]
We expect the following:

```js
var Utils = {
  get: function() {}
};

var { get } = Utils;

var bar = {
  get: function(arg) {
    get(arg, "baz");
  }
};
```

To become:

```js
"use strict";

var Utils = {
  get: function get() {}
};

var _get = Utils.get;

var bar = {
  get: function get(arg) {
    _get(arg, "baz");
  }
};
```

But actually we get:

```js
"use strict";

var Utils = {
  get: function get() {}
};

var _get = Utils._get; // <--- Note the extra underscore

var bar = {
  get: function get(arg) {
    _get(arg, "baz");
  }
};
```

I’ve prepared a branch with failing test case:

https://github.com/babel/babel/compare/babel:a241300...jgwhite:2826614

Let me know if you want a PR.

**Comment by monsanto** [comment]
As a workaround, blacklist `spec.functionName`

**Comment by jgwhite** [comment]
@monsanto thanks, will try now

**Comment by jgwhite** [comment]
@monsanto that gets us green. Many thanks.

Is that test case useful at all?

**Comment by monsanto** [comment]
The test case in the PR isn't minimal, we'd probably want something more like this in the test suite:

```
var obj = { foo: function() { foo } };
var { foo } = obj;
```

Anyway, as I expected, this is because `key` and `value` share the same object when a shorthand property. Similar problem to https://github.com/babel/babel/pull/1385. The `Declaration` case of [scope.rename](https://github.com/babel/babel/blob/a241300ff1a817d2e495de949ad15b5f22c44e7c/src/babel/traversal/scope.js#L135) will return `foo` as a value to rename, but since that rename affects the key as well, it shows up on the RHS after `es6.destructuring` does its work.

**Comment by jgwhite** [comment]
Cool. Sounds like you have this well in hand. Shall I close the issue?

**Comment by jgwhite** [comment]
Updated the branch along the lines you suggest:
https://github.com/babel/babel/compare/babel:a241300...jgwhite:aff01ab

**Comment by monsanto** [comment]
@jgwhite nah let's leave it open until this gets fixed :smile:

@sebmck What is the point of the [line I referenced above](https://github.com/babel/babel/blob/a241300ff1a817d2e495de949ad15b5f22c44e7c/src/babel/traversal/scope.js#L135)? All tests pass without it & it seems to me like its logic would be covered by the `ReferencedIdentifier` case. If we comment out that line the [shorthand expanding code](https://github.com/babel/babel/blob/a241300ff1a817d2e495de949ad15b5f22c44e7c/src/babel/traversal/scope.js#L95) in the `ReferencedIdentifier` case solves this issue.

**Comment by sebmck** [comment]
@monsanto To cover things like `function foo() {}`, `class Foo {}` etc.

**Comment by sebmck** [comment]
@monsanto Just remembered it was also done for:

```javascript
var foo = "foo";

var foo = "bar"; // we just shadowed the first binding
```

**Comment by gaearon** [comment]
Just bumped into this with

```js
const { a } = x; // meh, will access x._a

class wow {
  a() {
      console.log(a);
  }
}
```

**Comment by jgwhite** [comment]
<3
