### ISSUE TITLE
[Bug]: No matching version found for @babel/helper-validator-identifier@^7.18.2

### ISSUE THREAD

**Issue by chelsumz007** [babel/babel#14593]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Typescript using babel as peer dependency

### Current and expected behavior

While npm install getting error: No matching version found for @babel/helper-validator-identifier@^7.18.2

### Environment

Angular v13
Node v14
npm v6

**Comment by nicolo-ribaudo** [comment]
Do you know which package depends on that? This might be a publishing bug indeed.

**Comment by chelsumz007** [comment]
@nicolo-ribaudo so recently I have upgraded my angular to v13. Did not face this issue before, but today when I cloned my angular upgrade branch and tried an npm install it gave me this error:

![image](https://user-images.githubusercontent.com/52992133/170308964-1dd8a923-7d42-47f8-93e0-3737c7065530.png)

**Comment by chelsumz007** [comment]
@nicolo-ribaudo not sure about the dependent package, but pretty sure did not face this issue before, it is only with this version that was published today/not yet published

**Comment by chelsumz007** [comment]
None of my package-lock json dependencies show any sign of 7.18.2 version. they are all referring to older versions, yet this issue is coming.

**Comment by JLHwung** [comment]
The error message shows that no matching version found for `@babel/helper-compilation-targets`, however, it has been published in npm: https://www.npmjs.com/package/@babel/helper-compilation-targets

There is nothing we can do, see also https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67
