### ISSUE TITLE
eslint/eslint-parser require node engine version 13.x

### ISSUE THREAD

**Issue by Ricky816845** [babel/babel#14596]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Hi,I have a situation on my project build server with Nodejs Version 13.14.0 and unable to upgrade. but the package 'eslint-parser'
requires node engine not include 13.x .
Is that a posibility to add it?

![nodeproblem](https://user-images.githubusercontent.com/20158450/170404315-a2c5a7b4-d052-4432-9e08-25354256d1a4.png)

### Describe the solution you'd like

Is that a posibility to add it?

### Describe alternatives you've considered

If there's any verion of Babel  about 7.x support  node version 13.14.0?

**Comment by JLHwung** [comment]
Node.js 13 is no longer supported as of May 2022. Please upgrade to Node.js 14 or higher supported versions.

**Comment by nicolo-ribaudo** [comment]
To expand on @JLHwung's comment: Node.js 13 is not maintained anymore by Node.js itself, it's not just that we don't support it. Youn won't receive any security fixes, even for important (and already known) vulnerabilities. You can see here which versions you can/should use: https://nodejs.org/en/about/releases/

Anyway, that package works on Node.js 12 so it might work on Nods.js 13, even if we do not guarantee it and we won't fix any Node.js 13-specific bug. Almost every package manager has an option to ignore the engines requirement, so you can enable it.
