### ISSUE TITLE
Weird arrow return behavior with js objects

### ISSUE THREAD

**Issue by neverov** [babel/babel#1459]
I was trying to return a simple json value from arrow shortcut and encountered that if you try to return a js object from oneliner, it actually returns `undefined`, which is kind of confusing:
```javascript
>> babel-node
> let foo = () => {foo: 1}
undefined
> foo()
undefined
> let foo = () => { return {foo: 1}}
undefined
> foo()
{ foo: 1 }
```
Version:

```
>> babel-node --version
4.0.1
```

I can't find anything on this specific behavior in the spec, is that the way it supposed to work?

**Comment by iamdustan** [comment]
That is correct behavior.
The `=> {}` curlys indicate a block versus an implicit return.

To get the implicit return you need to wrap your object in parens.

```
>> babel-node
> let foo = () => ({foo: 1})
{ foo: 1 }
```

**Comment by neverov** [comment]
Oh, okay then, btw I didn't find anything about this in the documentation, could you please show me where it is?

**Comment by iamdustan** [comment]
Here is the specification for the arrow function syntax: http://wiki.ecmascript.org/doku.php?id=harmony:arrow_function_syntax

I’m not much of a spec reader, but I believe that this note in concerning the grammar rules is referencing the ambiguity of what many—including you and I—have attempted:

> The ArrowFormalParameters production requires GLR parsing or equivalent to disambiguate against the other right-hand sides of AssignmentExpression. For an LR(1) grammar, we can use:

> ArrowFormalParameters :
    ( Expression_opt )

**Comment by hzoo** [comment]
http://www.nczonline.net/blog/2013/09/10/understanding-ecmascript-6-arrow-functions/

> Because curly braces are used to denote the function’s body, an arrow function that wants to return an object literal outside of a function body must wrap the literal in parentheses. For example:

```js
var getTempItem = id => ({ id: id, name: "Temp" });
// effectively equivalent to:
var getTempItem = function(id) {
    return {
        id: id,
        name: "Temp"
    };
};
```

**Comment by neverov** [comment]
thx guys!
