### ISSUE TITLE
[Bug]: parser(ts), ast, TSTypePredicate and TSEnumDeclaration returns additional index property in loc.start

### ISSUE THREAD

**Issue by armano2** [babel/babel#14590]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
export declare const enum Foo {
    foo = 1,
    bar
}
```
```ts
export declare enum Foo {
    foo = 1,
    bar
}
```
```ts
class AssertsFoo {
  isBar(): asserts this is string {
    return;
  }
  isBaz = (): asserts this is string => {
    return;
  }
}
```

### Configuration

```ts
  require('@babel/parser').parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins: [
      [ 'estree', { classFeatures: true }, ],
      'decorators-legacy',
      'classStaticBlock',
      'importAssertions',
      'typescript',
    ],
  });
```

### Current and expected behavior

"index" property is added to loc.start of `TSTypePredicate` and `TSEnumDeclaration`

this property is present only on those 2 nodes and it's with us since version 7.17.x

```diff
{
  "end": { "column": 1, "line": 4 },
- "start": { "column": 7, "index": 7, "line": 1 }
+ "start": { "column": 7, "line": 1 }
}
```

### Environment

- Babel: 7.18.2 

### Additional context

https://github.com/typescript-eslint/typescript-eslint/blob/1fb31a4b3e05734f801ade0450fea33494e4d5e6/packages/typescript-estree/tests/ast-alignment/utils.ts#L284-L297

**Comment by nicolo-ribaudo** [comment]
It should be present on every node since #14174

**Comment by armano2** [comment]
> It should be present on every node since #14174

hmm, as a customer we are receiving it only for those 2 nodes, 

https://astexplorer.net/#/gist/b06fc4b0b2d238282285f58e27064212/eb0d4df61075524af9dea0a6b0621f767a62de42

![image](https://user-images.githubusercontent.com/625469/170292085-fdad0f59-6161-439b-8100-39730bd6ec66.png)

**Comment by nicolo-ribaudo** [comment]
Note that astexplorer still uses Babel 7.16

**Comment by armano2** [comment]
yea I'm aware of that, this report comes from our alignment tests, we are doing deep comparison between AST produced by babel and ts-estree to keep in "aligned" and find potential issues in one of those packages

**Comment by liuxingbaoyu** [comment]
This does seem to be a bug and I will investigate.
