### ISSUE TITLE
[Bug]: notarget No matching version found for @babel/types@^7.18.2.

### ISSUE THREAD

**Issue by SravanaLakshmiS** [babel/babel#14594]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

  "babel": {
    "testOptions": {
      "retainLines": true
    }
  },

### Configuration file name

package.json

### Current and expected behavior

Getting Error:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.18.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

### Environment

  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v15.14.0/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm

**Comment by liuxingbaoyu** [comment]
The error message shows that no matching version found for @babel/types, however, it has been published in npm: https://www.npmjs.com/package/@babel/types

There is nothing we can do, see also https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67
