### ISSUE TITLE
babel --extensions loads files without extensions

### ISSUE THREAD

**Issue by dariocravero** [babel/babel#1460]
Hi all,

It seems that `babel --extensions` loads files without extensions too. Like, say `CHANGELOG`.

This doesn't happen when I don't use the --extensions flag.

I put together a [little repo showing this](https://github.com/dariocravero/babel-extensions-issue).

I'm ignoring the specific file for now but it seems like a bug to me?

Thanks,
Darío

**Comment by dariocravero** [comment]
:) thanks!

**Comment by sebmck** [comment]
Fixed as of 5.2.16, thanks!

**Comment by dariocravero** [comment]
Hi @sebmck, `opts.extensions` seems to be `undefined` at all times. `commander.extensions` has the param I sent to it though, so I guess that the code was right as it was before.

[canCompile](https://github.com/babel/babel/blob/master/src/babel/util.js#L30) is expecting an array and we're sending in a string, which is fine for `_.contains` as it kind of works like an `indexOf` returning a boolean. The problem is that `_.contains('.es6', '')` returns `true`, making the whole thing fail. See #1470 for a patch :).

**Comment by dariocravero** [comment]
Class, thanks! :)
