### ISSUE TITLE
[Bug]: Changelog no longer gets rendered on github.com

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [babel/babel#14618]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Checking the [changelog](https://github.com/babel/babel/blob/dc9bc6c31b43ca6ea533e77aea2857506ce5002a/CHANGELOG.md) for v7.18.4 this morning I noticed that it was no longer being rendered. Checking back a while later, I now just get "This blob took too long to generate.". I get the same message with older versions of the changelog (e.g. [v7.18.3](https://github.com/babel/babel/blob/bc02e8277635cd544be16b0873e3552e65ad1fcf/CHANGELOG.md)), so maybe github reduced a processing time limit somewhere.

### Current and expected behavior

Changelog should be rendered.

### Environment

n/a

**Comment by nicolo-ribaudo** [comment]
Oh thanks, I'll split it in two files.

**Comment by Philip1435** [comment]
sdfsdfsfsf
