### ISSUE TITLE
[Bug]: Ejected create-react-app : Cannot find module './ast-types/generated'

### ISSUE THREAD

**Issue by pauldmps** [babel/babel#14634]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Its a React.js application compiled by ejected create-react-app, with no modifications to the webpack config or other CRA config files. We ejected it because we would like to modify the config in the future.

### Configuration file name

package.json

### Configuration

```json
"babel": {
    "presets": [
      "react-app"
    ]
  },
```

### Current and expected behavior

**Current error:**
**Issue started appearing a couple of days ago. It was compiling fine before that. If I npm install again, the issue goes away temporarily. I can see that the folder _node_modules/@babel/types/lib/ast-types/generated_ is empty.**

```
Error: Cannot find module './ast-types/generated'
Require stack:
- ReactApp\node_modules\@babel\types\lib\index.js
- ReactApp\node_modules\@babel\core\lib\transformation\file\file.js
- ReactApp\node_modules\@babel\core\lib\index.js
- ReactApp\node_modules\@rollup\plugin-babel\dist\index.js
- ReactApp\node_modules\workbox-build\build\lib\bundle.js
- ReactApp\node_modules\workbox-webpack-plugin\build\generate-sw.js
- ReactApp\node_modules\workbox-webpack-plugin\build\index.js
- ReactApp\config\webpack.config.js
- ReactApp\scripts\start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (ReactApp\node_modules\@babel\types\lib\index.js:629:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'ReactApp\\node_modules\\@babel\\types\\lib\\index.js',
    'ReactApp\\ClientApp\\node_modules\\@babel\\core\\lib\\transformation\\file\\file.js',
    'ReactApp\\ClientApp\\node_modules\\@babel\\core\\lib\\index.js',
    'ReactApp\\ClientApp\\node_modules\\@rollup\\plugin-babel\\dist\\index.js',
    'ReactApp\\ClientApp\\node_modules\\workbox-build\\build\\lib\\bundle.js',
    'ReactApp\\ClientApp\\node_modules\\workbox-webpack-plugin\\build\\generate-sw.js',
    'ReactApp\\ClientApp\\node_modules\\workbox-webpack-plugin\\build\\index.js',
    'ReactApp\\ClientApp\\config\\webpack.config.js',
    'ReactApp\\ClientApp\\scripts\\start.js'
  ]
```

**Expected behavior:**
Should compile successfully

### Environment

    "@babel/core": "^7.18.2",
    "babel-jest": "^27.4.2",
    "babel-loader": "^8.2.3",
    "babel-plugin-named-asset-import": "^0.3.8",
    "babel-preset-react-app": "^10.0.1",
    "webpack": "^5.64.4",
    "webpack-dev-server": "^4.6.0",
    "webpack-manifest-plugin": "^4.0.2",
    "workbox-webpack-plugin": "^6.4.1"

**Comment by nicolo-ribaudo** [comment]
It's empty so it's unnecessary, but it shouldn't cause an error 🤔

The file is there. This looks like a bug with whatever tool is throwing that error.

**Comment by pauldmps** [comment]
The issue is back today again. The folder is empty. There are no files.

![image](https://user-images.githubusercontent.com/6829986/171807691-db6f1be9-7570-40a5-8eae-64e29f078b7f.png)

I also tried commenting out the w_ebpack-workbox-plugin_ part in webpack config but then another webpack plugin that triggers babel also caused the same error.

**Comment by nicolo-ribaudo** [comment]
That folder is not empty in the version published on npm: https://unpkg.com/browse/@babel/types@7.18.4/lib/ast-types/generated/

If you delete node_modules and reinstall them, is it immediately empty?
- Yes: it's a bug with your package manager. Which one are you using? Which version?
- No: there is something on your machine that deletes that file. Try making it non-writable (with chmod if you are on Linux, I believe there should be similar commands on other operating systems): whatever is deleting that file will hopefully crash so that you can find who it is.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since the file is present in the published package and thus it's a bug with something else that deletes it.

**Comment by toabm** [comment]
Hello guys, I am having same issue here. Did you find any solution?
