### ISSUE TITLE
mergeSourceMap in streaming mode

### ISSUE THREAD

**Issue by vasicvuk** [babel/babel#14635]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

PR limits the size of inputSourceMap to 1MB since otherways it is causing OOM issue.

As mentioned in PR adding this limit, mergeSourceMap should be working in streaming mode to overcome these limits.
https://github.com/babel/babel/pull/10890

### Describe the solution you'd like

Any solution that would allow bigger input source map would be great.

### Describe alternatives you've considered

We considered using JSONStream library https://www.npmjs.com/package/JSONStream

**Comment by jridgewell** [comment]
With the switch to `@ampproject/remapping` and `@jridgewell/trace-mapping`, we could likely increase the file size considerably. There's also a way to we could perform the remapping during the output code generation, so that we don't need to allocate an output map to feed into `remapping` at all.

**Comment by liuxingbaoyu** [comment]
The problem doesn't seem to be related to JSON parsing, but rather taking up a lot of memory when merging.

As @jridgewell  said, we've switched to `@ampproject/remapping`, which should reduce memory usage.
We just need to re-evaluate the size limit.

**Comment by vasicvuk** [comment]
I encountered the same error when passing 3mb parsed object sa input source map, that is why I assumed it is json parse, but I see now that i can do Json parse of even larger Json.

**Comment by vasicvuk** [comment]
I can verify with version 7.18.2 that 3MB input map loads without any issue by changing the threshold in normalize-file.js

**Comment by nicolo-ribaudo** [comment]
As a quick workaround we can immediately merge a PR that bumps the limit to 3mb. In the next minor we can make it configurabile (using an env variable?), and longer term we can investigate support for arbitrarily large source maps.

**Comment by vasicvuk** [comment]
Here is the PR.

https://github.com/babel/babel/pull/14641
