### ISSUE TITLE
destructuring bug

### ISSUE THREAD

**Issue by ashaffer** [babel/babel#1463]
This code:

```javascript
function create(tag, range, attrs) {
  return {
    tag: tag,
    range: range,
    attrs: attrs || {}
  };
}
```

Generates the following error: `TypeError: Invalid attempt to destructure non-iterable instance`

**Comment by sebmck** [comment]
That's not the cause of the error. There's no destructuring in it.

**Comment by ashaffer** [comment]
Impressive response time :).  Ya you're right, misread.  Apologies.
