### ISSUE TITLE
minification.deadCodeElimination being run too early?

### ISSUE THREAD

**Issue by afrojas** [babel/babel#1464]
Still having deadCodeElimination issues. I haven't been able to fully track this one down, but I can easily reproduce the error:

```javascript
// ./src/index.js
let Helper = {

  ify(...args) {
    console.log(args);
  }

};

module.exports = Helper;
```

Run with `babel --optional minification.deadCodeElimination -d ./dist ./src` results in:

```bash
Error: src/index.js: cannot turn RestElement to an expression
```

Without deadCodeElimination optional:

```javascript
"use strict";

var Helper = {

  ify: function ify() {
    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    console.log(args);
  }

};

module.exports = Helper;
```

It's appears to be the *usage* of `args` that causes issues because:

```javascript
let Helper = {

  ify(...args) {
  }

};

module.exports = Helper;
```

Compiles just fine:
```javascript
"use strict";

module.exports = {

  ify: function ify() {
    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }
  }

};
```

While messing around I placed `"minification.deadCodeElimination":      require("./minification/dead-code-elimination"),` after `"es6.spread": require("./es6/spread"),` which caused a different error: `TypeError: src/index.js: Cannot read property 'type' of undefined`.

At that point I realized I was out of my depth and filed this issue.

**Comment by sebmck** [comment]
I should really put a disclaimer on that transformer docs since I'm not ready to recommend it for production use, it's littered with bugs and there are zero tests for it.

**Comment by afrojas** [comment]
A disclaimer would be great. Do you have a recommended way of producing the desired result?

Cheers!

**Comment by sebmck** [comment]
I'll write some tests for this in the coming days to ensure it's stability. I'll also look into some way of flagging transformers as being "under development" or something like that.

**Comment by Naddiseo** [comment]
@sebmck, perhaps a flag along the same lines as the "Stage" flag?
