### ISSUE TITLE
React warning message in the browser when transpile es6 classes

### ISSUE THREAD

**Issue by juanmac** [babel/babel#1466]
I'm using babel with ReactJS combined with some es6 features like modules and classes and all looks fine. However, I'm getting a warning message from react in the browser console when I use classes. It says:

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
`

The code:
```jsx
React = require("react");

class Hello extends React.Component {
  render() {
    return <p>Hello, world!</p>;
  }
}

React.render(<Hello/>, document.getElementById('content'));
```

The message does not appear when I use `react-tools` as transpiler.
Thanks for your awesome work! ;)

**Comment by sebmck** [comment]
What version of react are you using? I can't find this check anywhere in the codebase.

**Comment by sebmck** [comment]
It's not coming from React, it's coming from Firefox internally because the classes helper uses `__proto__ = `. There's no other way to replicate static inheritance.

**Comment by juanmac** [comment]
thanks @sebmck Yes i'm using Firefox right now with React v0.13.2. I will try chrome later. Thanks!

**Comment by juanmac** [comment]
the message does not exist in the codebase in v0.13.2 i'm sorry. thanks again!
