### ISSUE TITLE
[Bug]: Unable to download 7.18.5 version

### ISSUE THREAD

**Issue by agusfuentes** [babel/babel#14664]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

No needed

### Current and expected behavior

The new 7.18.5 version has 0 downloads in the last 12 hours, and still failing... 

I mean, you think it's normal having 0 downloads when the previous version has 7 million? xD

![1](https://user-images.githubusercontent.com/107431684/173420266-e6d913cf-9fe7-4314-8035-c19b023ce1c4.png)

### Environment

@babel/parser 7.18.5

### Possible solution

I don't know

**Comment by existentialism** [comment]
I've verified on multiple machines that it has been published and is available: 

[https://www.npmjs.com/package/@babel/parser/v/7.18.5](https://www.npmjs.com/package/@babel/parser/v/7.18.5)
[https://unpkg.com/browse/@babel/parser@7.18.5/](https://unpkg.com/browse/@babel/parser@7.18.5/)

It's either a bug with the npm registry (and you should report it to them), or with a non proxy you are using that sits between you and the main registry (for example, a company proxy).

**Comment by agusfuentes** [comment]
So if you dowloaded why I still viewing 0 downloads on the list? Is my company proxy setting that 0? I think is still passing something weird with that build.

I close this and reporting to npm. Thanks.

**Comment by JLHwung** [comment]
The download count on npm is not realtime. Sometimes it can take days to update. See also #14597.

**Comment by agusfuentes** [comment]
I'm not using any proxy or vpn... So I will clean the npm cache in loop until it download the correct version, thank you
