### ISSUE TITLE
Regression: decoratored properties are incorrectly marked as readonly by default

### ISSUE THREAD

**Issue by jayphelps** [babel/babel#1467]
[Example repl](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20lolz(shit)%20%7B%0A%20%20return%20shit%3B%0A%7D%0A%0Aclass%20Foo%20%7B%0A%20%20%40lolz%0A%20%20bar%20%3D%20null%3B%0A%7D%0A%0Avar%20foo%20%3D%20new%20Foo()%3B%0Afoo.bar%20%3D%20'whatever'%3B&stage=0)
```js
function lolz(shit) {
  return shit;
}

class Foo {
  @lolz
  bar = null;
}

var foo = new Foo();
foo.bar = 'whatever';
// Cannot assign to read only property 'bar' of [object Object]
```

**Comment by jayphelps** [comment]
I need to lay off the crack pipe apparently. I believe this is an ID10T error.

**Comment by jayphelps** [comment]
protip: don't code when you've been drinking. you can quote me on that.

**Comment by sebmck** [comment]
It's ok @jayphelps, I've added a new label just for you.
