### ISSUE TITLE
[Bug]: `templateElement({ raw: 'string' })` leaves `cooked` unset / `@babel/plugin-transform-template-literals` requires `cooked` to be set

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [babel/babel#14682]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { transformFromAstSync } from '@babel/core';
import * as t from '@babel/types';

const { code } = transformFromAstSync(
  t.program([
    t.expressionStatement(
      t.templateLiteral(
        [t.templateElement({ raw: 'leading' }), t.templateElement({ raw: 'trailing' }, true)],
        [t.identifier('identifier')]
      )
    ),
  ]),
  '',
  { plugins: ['@babel/plugin-transform-template-literals'] }
);

console.log(code);
```

### Current and expected behavior

Current output:
```
"".concat(identifier);
```
Expected output:
```
"leading".concat(identifier, "trailing");
```

### Environment

- Babel `7.18.5`
- Node `16.15.1`

### Additional context

* The `cooked` property is marked as optional, so I would expect it not to matter (e.g. match `raw`) if omitted.
* With `@babel/plugin-transform-template-literals` disabled, I get the expected result `` `leading${identifier}trailing` ``.

**Comment by liuxingbaoyu** [comment]
This doesn't seem to be just a plugin issue.
In https://github.com/babel/babel/blob/master/packages/babel-parser/ast/spec.md#templateelement, we define the `cooked `property as string or null type, null and optional are not completely same.

However, I am not too familiar with this piece, the above is for reference only, waiting for others to comment.

**Comment by liuxingbaoyu** [comment]
This doesn't seem to be just a plugin issue.
In https://github.com/babel/babel/blob/master/packages/babel-parser/ast/spec.md#templateelement, we define the `cooked `property as string or null type, null and optional are not completely same.

However, I am not too familiar with this piece, the above is for reference only, waiting for others to comment.

**Comment by nicolo-ribaudo** [comment]
I'm surprised that template literals without the cooked property are invalid, because in (for example)
```js
tag`\u`
```
there is no valid cooked representation that we can generate.

**Comment by merceyz** [comment]
Related to this: https://github.com/babel/babel/issues/9242
