### ISSUE TITLE
ReferenceError: ** is not undefined error when using import

### ISSUE THREAD

**Issue by camsong** [babel/babel#1468]
I'm using babel + browserify + gulp. 

```
# app.js
import DatePicker from './DatePicker'
# use DatePicker here
```
It runs smoothly in the browser, however when I'm debugging, open **console** of DevTools and type  `DatePicker`, got an undefined error
```
ReferenceError: "DatePicker is not defined" 
```

my gulpfile.js is like:
```
  var bundle = browserify('./app.js', {
    debug: true,
    cache: {},
    packageCache: {},
    insertGlobals: true,
    extensions: ['.js', '.jsx']
  }).transform(babelify, {stage: 0, loose: "all"});
```

**Comment by sebmck** [comment]
Expected behaviour. Imports need to be rewritten in order to support live bindings. For example:

```javascript
import DatePicker from './DatePicker'
DatePicker;
```

is turned into

```javascript
'use strict';
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; 
var _DatePicker = require('./DatePicker');
var _DatePicker2 = _interopRequireDefault(_DatePicker);
_DatePicker2['default'];
```

So the `DatePicker` binding doesn't actually exist.

**Comment by camsong** [comment]
@sebmck thanks for the quick response.
How can I got `DatePicker` in the console. I'm deadly need this in case of debugging

**Comment by sebmck** [comment]
You can't really. Even if the binding did exist, browserify modules aren't ran in the global context, they're localised so you wouldn't be able to access it anyway.

**Comment by camsong** [comment]
I was able to access `DatePicker` before when using `require` syntax in browserify + gulp. Not sure if there is a way to make it works like before.

**Comment by sebmck** [comment]
Oh wait, `insertGlobals: true`. You can probably access `DatePicker` manually via `_DatePicker`.

**Comment by camsong** [comment]
It works, now I can access it by `_srcIndexJs.DatePicker`, though kinda weird but works. thanks so much!

**Comment by sebmck** [comment]
Oh weird. Glad it works though, no problem! :)

**Comment by aldendaniels** [comment]
@sebmck - Just ran into this as well. This can make debugging quite difficult.

Couldn't your example instead be transpiled to:

```javascript
'use strict';
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; 
var _DatePicker = require('./DatePicker');
var _DatePicker2 = _interopRequireDefault(_DatePicker);
var DatePicker = DatePicker2['default']; // Added this line.
DatePicker;
```

If possible, this would help debugging immensely.

**Comment by sebmck** [comment]
@aldendaniels Nope. That doesn't allow for live bindings.

**foo.js**

```javascript
import { num } from "./bar";

setInterval(function () {
  console.log(num);
}, 1000);
```

**bar.js**

```javascript
export var num = 1;
setInterval(function () {
  num++;
}, 1000);
```

Running:

```sh
$ babel-node foo.js
```

should output:

```
1
2
3
4
5
...
```

But with your suggestion will just output:

```
1
1
1
1
1
1
...
```

**Comment by aldendaniels** [comment]
@sebmck - Oh, I get it. Thanks for the example! The ability to export a primitive by reference rather than by value is very cool, although also somewhat counterintuitive. I hadn't realized that was possible. 

OTOH, live bindings seem like an edge case. One possibility would be to make this behavior opt-in: 

```javascript
import live { num } from "./bar"
```

So then:
```javascript
import (live) { num } from "./bar"
debugger; //  num is not defined

import  { num } from "./bar"
debugger; //  num is defined, value is not live.
```

This sacrifices spec compatibility for better debugging. It's definitely a tradeoff.

**Comment by goto-bus-stop** [comment]
@aldendaniels Live bindings are also quite nice for recursive dependencies:

```javascript
// Square.js
import { Rectangle } from './Rectangle'
export class Square {
  constructor(size) { this.size = size }
  toRectangle() { return new Rectangle(this.size, this.size) }
}
```
```javascript
// Rectangle.js
import { Square } from './Square'
export class Rectangle {
  constructor(width, height) { this.width = width, this.height = height }
  getCoveringSquare() { return new Square(Math.max(this.width, this.height)) }
}
```

This way, the Rectangle class will still get access to the Square class because the `Square` binding in that module "updates" when the class is finally actually defined.

**Comment by aldendaniels** [comment]
@goto-bus-stop - very cool!

My idea to opt-in to live bindings is probably a bad one - too much non-compliancy and a lot of conceptual overhead.

Another idea:

```javascript
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; 
var _DatePicker = require('./DatePicker');
var _DatePicker2 = _interopRequireDefault(_DatePicker);
function DatePicker() {
  return DatePicker2['default'];
}
DatePicker();
```

So `DatePicker` is still defined - it's just an accessor function instead of the actual library. 

This way in the debugger you can simply call `DatePicker().doSomething()` instead of `DatePicker.doSomething()`. Also, hovering over `DatePicker` will now show the accessor function instead of `undefined`, which is more informative.

Thoughts?

**Comment by aldendaniels** [comment]
On second thought, my above example doesn't work for writing live bindings... so scratch that. 

A final thought - to make this behavior more intuitive. Babel could expose a debug option to simply add the following:

```javascript
var DatePicker = 'In debugger, use "_DatePicker2[\'default\']". See http://babeljs.io/docs/faq/xyz';
```

That would go a long way, I think, towards eliminating confusion.

**Comment by mkscrg** [comment]
+1, just to say that this makes debugging Babel-ified code pretty difficult. I don't know much about sourcemaps, but I would have expected them to help here :/

**Comment by loganfsmyth** [comment]
Soucemaps are extremely limited in what they can do unfortunately.
