### ISSUE TITLE
[Bug]: Destructurisation transformation loses typescript types

### ISSUE THREAD

**Issue by cainrus** [babel/babel#14691]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
type Point = {
  x: number;
  y: number;
}

export function test({x, y}: Point) {
  return x * y;
}
```

### Configuration file name

.babelrc.json

### Configuration

```json
{
  "plugins": [
    "@babel/plugin-transform-parameters",
    ["@babel/plugin-transform-destructuring", {
      "loose": true
    }],
    "@babel/plugin-syntax-typescript"
  ]
}
```

### Current and expected behavior

Current output:
```ts
type Point = {
  x: number;
  y: number;
};
export function test(_ref) {
  let x = _ref.x,
      y = _ref.y;
  return x * y;
}
```
Expected output:
```ts
type Point = {
  x: number;
  y: number;
};
export function test(_ref: Point) {
  let x = _ref.x,
      y = _ref.y;
  return x * y;
}
```

### Environment

  System:
    OS: macOS 12.2
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    @babel/cli: ^7.17.10 => 7.17.10
    @babel/core: ^7.18.5 => 7.18.5
    @babel/plugin-syntax-typescript: ^7.17.12 => 7.17.12
    @babel/plugin-transform-destructuring: ^7.18.0 => 7.18.0

### Additional context

[Reproduction repo](https://github.com/cainrus/test-babel-ts-to-ts-transform)

**Comment by nicolo-ribaudo** [comment]
Out of curiosity, which tool/platform are you using that supports TS but not destructuring?

**Comment by cainrus** [comment]
> Out of curiosity, which tool/platform are you using that supports TS but not destructuring?

I want to use it with [assemblyscript](https://www.assemblyscript.org/), to downgrade some neat modern syntax features to compatible with assemblyscript syntax (partial es2015 support).

**Comment by magic-akari** [comment]
Is this the only case which type is losing?
I am willing to fix it, and I guess there are a lot of similar issues.

**Comment by cainrus** [comment]
> Is this the only case which type is losing? I am willing to fix it, and I guess there are a lot of similar issues.

Maybe [nativescript](https://nativescript.org/). It allows to generates android/ios apps from typescript sources.
