### ISSUE TITLE
Getter/Setter on ES6 class should call defineProperty with enumerablue:true

### ISSUE THREAD

**Issue by lukas-zech-software** [babel/babel#1469]
I tried to write a class with getters for some properties.
When I tried to serialise  those classes to JSON I saw that the getters are not invoked and simply left out.

The same happened when I cloned the instance with Object.assign which should invoke getters [according to MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Description)

After some investigation I found out, that getters ES6 classes get compiled code calling Object.defineProperty with **enumerable:false**

Writing the same code in ES5 and putting the get on object literals will compile to calling Object.defineProperty with **enumerable:true** which is the expected behaviour

I put together an [example in the playground](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=true&code=class%20Foo%20%7B%0A%20%20constructor%20()%20%7B%0A%20%20%7D%0A%20%20%20%0A%20%20get%20test%20()%20%7B%0A%20%20%20%20return%20'bar'%3B%0A%20%20%7D%0A%7D%0A%0A%0Alet%20foo%20%3D%20new%20Foo()%3B%0Avar%20a%20%3D%20Object.assign(%7B%7D%2C%20foo)%3B%0A%0Aconsole.log(foo)%3B%0Aconsole.log(foo.hasOwnProperty('test'))%3B%0Aconsole.log(a)%3B%0Aconsole.log(a.hasOwnProperty('test'))%3B%0A%0Avar%20Foo2%20%3D%20function()%7B%0A%20%20return%7B%0A%20%20%20%20get%20test2()%7B%0A%20%20%20%20%20%20return%20'bar2'%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Avar%20foo2%20%3D%20new%20Foo2()%3B%0Avar%20a2%20%3D%20Object.assign(%7B%7D%2C%20foo2)%3B%0A%0Aconsole.log(foo2)%3B%0Aconsole.log(foo2.hasOwnProperty('test2'))%3B%0Aconsole.log(a2)%3B%0Aconsole.log(a2.hasOwnProperty('test2'))%3B) where you can clearly see the difference.
With one approach the getters are never printed on console and also return false on hasOwnProperty

Did I miss something or is this behaviour intended?

**Comment by sebmck** [comment]
It's expected behaviour. ES6 class methods (getters and setters are just a type of method) are non-enumerable.

**Comment by topaxi** [comment]
You could implement a `toJSON()` method if you want to represent data from getters.

```js
class Foo {
    get baz() {
        return 'bar'
    }
    toJSON() {
        'value': this.value,
        'bar': this.baz
    }
}
```

`JSON.stringify()` will call your objects `toJSON()` method :)

**Comment by sebmck** [comment]
Relevant spec steps:

[14.5.14 Runtime Semantics: ClassDefinitionEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-classdefinitionevaluation)

> 21.x.i. Let status be the result of performing PropertyDefinitionEvaluation for m with arguments F and false.

[14.3.9 Runtime Semantics: PropertyDefinitionEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-method-definitions-runtime-semantics-propertydefinitionevaluation)

> MethodDefinition : get PropertyName ( ) { FunctionBody }
> With parameters object and enumerable.
> 9. Let desc be the PropertyDescriptor{[[Get]]: closure, [[Enumerable]]: enumerable, [[Configurable]]: true}

@topaxi Need a `return` in there:

```javascript
class Foo {
    get baz() {
        return 'bar'
    }
    toJSON() {
        return {
            'value': this.value,
            'bar': this.baz
        };
    }
}
```

**Comment by lukas-zech-software** [comment]
@sebmck Thanks for providing the Specs for that behaviour, I tried to find them and thought it might be an error after I couldn't find anything related

@topaxi Thanks for your hint, I was already implementing it that way.

What I still find very disturbing is there difference in the behaviour between getters on object literals and getters on classes - simply feels incosistent to me

**Comment by lukas-zech-software** [comment]
This issue is still confusing me.

According to the [MDN article for **Object.assign**](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Description) the function copies only enumerable properties and by doing so invokes getters and setters

>The Object.assign() method only copies **enumerable** and own properties from a source object to a target object. It uses [[Get]] on the source and [[Put]] on the target, so it will **invoke getters and setters**.

As the babel code sets getter to not enumerable, Object.assign does not invoke them so its behaviour contradicts the description in the MDN article.

Is the article is wrong from your point of view?

**Comment by bloodyowl** [comment]
`get` & `set` are by default enumerable in objects, but not in classes.
