### ISSUE TITLE
[Bug]: @babel/types cannot find @babel/traverse error since 7.18.6

### ISSUE THREAD

**Issue by aomarks** [babel/babel#14705]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```sh
mkdir babel-types-error-repro
cd babel-types-error-repro
npm init --force
npm i @babel/types@7.18.6 typescript@4.7.4
echo "import {BlockStatement} from '@babel/types'" > index.ts
echo '{"compilerOptions":{"moduleResolution":"node","strict":true}}' > tsconfig.json
npx tsc
```

### Current and expected behavior

**Currently errors with**:

```
node_modules/@babel/types/lib/index.d.ts:1:23 - error TS2307: Cannot find module '@babel/traverse' or its corresponding type declarations.

1 import { Scope } from '@babel/traverse';
                        ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@babel/types/lib/index.d.ts:1
```

**Expected**: No error.

### Environment

- Node: v16.15.0
- npm: 8.11.0
- @babel/types: v7.18.6
- OS: Ubuntu Linux 20.04
- Monorepo: no

### Additional context

This was a regression between `@babel/types@7.18.4` and `@babel/types@7.18.6`.

Running the following in the above repro directly removes the error:

```
npm i @babel/types@7.18.4
npx tsc
```

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/14706
