### ISSUE TITLE
[Bug]: incorrect source-map generate by @babel/core with vue-cli and can't debugger in browser

### ISSUE THREAD

**Issue by Wonder233** [babel/babel#14714]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Vue Project generated by  @vue/cli-service.
![image](https://user-images.githubusercontent.com/8199240/176838913-9d5a30fc-52c1-44a5-9274-d7e36b3ebf49.png)

### Configuration file name

package.json

### Configuration

```json
{
  "name": "test-babel-with-vue-cli",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.8.3",
    "vue": "^2.6.14"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.4.0",
    "@typescript-eslint/parser": "^5.4.0",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "@vue/eslint-config-typescript": "^9.1.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "typescript": "~4.5.5",
    "vue-template-compiler": "^2.6.14"
  }
}

```

### Current and expected behavior

It can't generate correct source-map when debugger in project as show in Input code.
![image](https://user-images.githubusercontent.com/8199240/176839078-69f9092a-2b20-4159-b63b-3d67deda6df7.png)
![image](https://user-images.githubusercontent.com/8199240/176839197-43e31453-7a98-4e0e-bfee-3ef137aab971.png)

### Environment

Babel: 7.18.6
Node: 16.14.0
Yarn: 1.22.17
OS: Windows 11

### Possible solution

When I downgrade @babel/core to v7.16.12，source-map generate correct and can debugger in chrome.
```json
{
  "name": "test-babel-with-vue-cli",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.8.3",
    "vue": "^2.6.14"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.4.0",
    "@typescript-eslint/parser": "^5.4.0",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "@vue/eslint-config-typescript": "^9.1.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "typescript": "~4.5.5",
    "vue-template-compiler": "^2.6.14"
  },
  "resolutions": {
    "@babel/core": "7.17.4"
  }
}

```

And I found that the babel/core version where the problem occurs is v7.17.5. When I downgrade @babel/core to v7.17.4，source-map generate correct; while I upgrade @babel/core to v7.17.5, not work.

**Comment by Wonder233** [comment]
You can test it in: 
@babel/core v7.17.5   https://github.com/Wonder233/test-babel-with-vue-cli/tree/test-error
@babel/core v7.17.4   https://github.com/Wonder233/test-babel-with-vue-cli/tree/test-success

**Comment by nicolo-ribaudo** [comment]
This _might_ be the same as https://github.com/babel/babel/issues/14676. @Wonder233 Could you check if forcing `@jridgewell/trace-mapping@0.3.12` in your dependencies fixes this problem?

**Comment by liuxingbaoyu** [comment]
I tested and `@jridgewell/trace-mapping@0.3.12` works fine.

**Comment by jridgewell** [comment]
Note, there's also https://crbug.com/1333411 that affects placing debug statements in a sourcemap.
