### ISSUE TITLE
Make babel-plugin-generator another option of babel-plugin-transform-regenerator

### ISSUE THREAD

**Issue by konicyQWQ** [babel/babel#14721]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

The `babel-plugin-transform-regenerator` uses `regenerator-transform` lib. It's helper function `regeneratorRuntime` is about **6.6KB**, While the TypeScript's helper function `__generator` just uses **1.1KB**. (Both in uglify.js)

If the polyfill way of TypeScript uses can be another option of `babel-plugin-transform-regenerator`, the bundle size will be reduced more!

`__generator` can be seen in [TypeScript exercise](https://www.tslang.cn/play/index.html#src=function*%20f()%20%7B%0D%0A%20%20%20%20%0D%0A%7D)

### Describe the solution you'd like

I have written a babel-plugin [babel-plugin-generator](https://github.com/konicyQWQ/babel-plugin-generator). It's a ported version of TypeScript generator transform. Maybe this plugin can be used in `babel-plugin-transform-regenerator`. I'd like to make babel-plugin-generator another option of babel-plugin-transform-regenerator.

### Describe alternatives you've considered

None yet.

**Comment by nicolo-ribaudo** [comment]
I don't think we should have a plugin option to completely change the plugin behavior: you can just remove the `regenerator` plugin from your config (or pass `exclude: ["transform-regenerator"]` if you are using preset-env), and you can load your own plugin.
