### ISSUE TITLE
[Bug]: clone-deep has a bug I think...

### ISSUE THREAD

**Issue by kenilam** [babel/babel#14732]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code
Proposed fixes to clone-deep:
https://github.com/jonschlinkert/clone-deep/commit/987a496f19f34c251a26011cf149d779f3389e2d

<img width="867" alt="Screen Shot 2022-07-06 at 20 22 24" src="https://user-images.githubusercontent.com/657845/177684919-4caae844-a270-4095-9bc8-cba3672f71ae.png">

### Current and expected behavior

It should compile successfully

### Environment

  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.17
  npmPackages:
    @babel/core: 7.18.6 => 7.18.6 
    @babel/node: 7.18.6 => 7.18.6 
    @babel/plugin-proposal-class-properties: 7.18.6 => 7.18.6 
    @babel/plugin-proposal-decorators: 7.18.6 => 7.18.6 
    @babel/plugin-proposal-export-default-from: 7.18.6 => 7.18.6 
    @babel/plugin-proposal-object-rest-spread: 7.18.6 => 7.18.6 
    @babel/plugin-proposal-private-methods: 7.18.6 => 7.18.6 
    @babel/plugin-syntax-dynamic-import: 7.8.3 => 7.8.3 
    @babel/plugin-transform-modules-commonjs: 7.18.6 => 7.18.6 
    @babel/plugin-transform-runtime: 7.18.6 => 7.18.6 
    @babel/preset-env: 7.18.6 => 7.18.6 
    @babel/preset-flow: 7.18.6 => 7.18.6 
    @babel/preset-react: 7.18.6 => 7.18.6 
    @babel/preset-typescript: 7.18.6 => 7.18.6 
    @babel/register: 7.18.6 => 7.18.6 
    babel-eslint: 10.1.0 => 10.1.0 
    babel-jest: 28.1.2 => 28.1.2 
    babel-plugin-add-module-exports: 1.0.4 => 1.0.4 
    babel-plugin-module-resolver: 4.1.0 => 4.1.0 
    babel-plugin-react-css-modules: 5.2.6 => 5.2.6 
    babel-plugin-rewire: 1.2.0 => 1.2.0 
    babel-plugin-root-import: 6.6.0 => 6.6.0 
    babel-plugin-system-import-transformer: 4.0.0 => 4.0.0 
    babel-plugin-transform-class-properties: 6.24.1 => 6.24.1 
    babel-plugin-transform-decorators-legacy: 1.3.5 => 1.3.5 
    babel-plugin-transform-export-extensions: 6.22.0 => 6.22.0 
    babel-plugin-transform-object-rest-spread: 6.26.0 => 6.26.0 
    babel-plugin-transform-react-constant-elements: 6.23.0 => 6.23.0 
    babel-plugin-transform-react-inline-elements: 6.22.0 => 6.22.0 
    babel-plugin-transform-react-jsx-self: 6.22.0 => 6.22.0 
    babel-plugin-transform-react-jsx-source: 6.22.0 => 6.22.0 
    babel-polyfill: 6.26.0 => 6.26.0 
    babel-preset-env: 1.7.0 => 1.7.0 
    babel-preset-react: 6.24.1 => 6.24.1 
    eslint: 7.32.0 => 7.32.0 
    jest: 28.1.2 => 28.1.2 

### Possible solution

Wait for clone-deep responses?

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/177688297-687c41d7-39a2-45cd-a3c9-ca5038d3d272.png)

It works fine for me locally.
Have you transformed node_modules as well.

**Comment by kenilam** [comment]
yes I am, here is my babel.config
```JS
module.exports = function (api) {
  const isTest = api.env('test');

  let ignore = ['node_modules'];

  if (isTest) {
    ignore = null;
  }

  return {
    exclude: [/\/core-js\//],
    ignore,
    presets: [
      ['env', { targets: { node: true } }],
      [
        '@babel/preset-env',
        {
          corejs: 3,
          debug: false,
          useBuiltIns: 'usage',
        },
      ],
      '@babel/preset-react',
      '@babel/preset-typescript',
    ],
    plugins: [
      [
        'transform-class-properties',
        {
          spec: true,
        },
      ],
      [
        '@babel/plugin-proposal-decorators',
        {
          legacy: true,
        },
      ],

      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-export-default-from',
      '@babel/plugin-proposal-private-methods',
      '@babel/plugin-proposal-object-rest-spread',
      '@babel/plugin-syntax-dynamic-import',
      'transform-export-extensions',
      '@babel/plugin-transform-modules-commonjs',
      'babel-plugin-add-module-exports',
    ],
  };
};

```

Also, the error is coming from within  the `clone-deep` dependency

`const isPlainObject = require('is-plain-object');`

is-plain-object export isPlainObject as a static export, so I think it should be written as 
`const { isPlainObject } = require('is-plain-object');` - and the script ran successfully

I already filed a change request to clone-deep
<img width="619" alt="Screen Shot 2022-07-06 at 21 18 05" src="https://user-images.githubusercontent.com/657845/177690313-6cfd794d-7c56-4e67-977b-6086e5cbb1e4.png">

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/177690712-e237fb5a-d07a-4529-bc44-f710a3d9b884.png)

I don't think it's a bug of `is-plain-object`.

**Comment by kenilam** [comment]
yeah, no when I think of it

**Comment by kenilam** [comment]
if that so, any ideas when could have cause the issue I can facing?

**Comment by kenilam** [comment]
would there be a setting that I may have done incorrectly?

**Comment by liuxingbaoyu** [comment]
I'm guessing it has something to do with babel configuration, but I'm not too familiar with this to give advice.
We can wait a bit for the other members, they are familiar with it.

**Comment by kenilam** [comment]
Thanks @liuxingbaoyu

**Comment by kenilam** [comment]
Adding more trace stacks:

```BASH
TypeError: isPlainObject is not a function
    at cloneObjectDeep ({appRoot}/node_modules/clone-deep/index.js:27:24)
    at cloneDeep ({appRoot}/node_modules/clone-deep/index.js:14:14)
    at exports.transformSync ({appRoot}/node_modules/@babel/register/lib/worker/transform.js:82:8)
    at Function.handleMessage ({appRoot}/node_modules/@babel/register/lib/worker/handle-message.js:23:16)
    at LocalClient.<anonymous> ({appRoot}/node_modules/@babel/register/lib/worker-client.js:134:86)
    at LocalClient.transform ({appRoot}/node_modules/@babel/register/lib/worker-client.js:64:47)
    at compile ({appRoot}/node_modules/@babel/register/lib/hook.js:58:25)
    at compileBabel7 ({appRoot}/node_modules/@babel/register/lib/hook.js:49:14)
    at Module._compile ({appRoot}/node_modules/pirates/lib/index.js:130:29)
```

**Comment by nicolo-ribaudo** [comment]
`clone-deep` uses `isPlainObject@2.0.4` (https://github.com/jonschlinkert/clone-deep/blob/fb63468c27c087349f67929b90441f09d64bed2f/package.json#L23), which uses `module.exports = function isPlainObject(...) { ... }` to export the function (https://unpkg.com/browse/is-plain-object@2.0.4/index.js).

@kenilam Could you check these?
- If you add a `console.log(isPlainObject)` in `{appRoot}/node_modules/clone-deep/index.js` after the require calls, what does it log?
- If `{appRoot}/node_modules/clone-deep/node_modules/is-plain-object` exists, what is the version in its `package.json`?
- If `{appRoot}/node_modules/is-plain-object` exists, what is the version in its `package.json`?

**Comment by kenilam** [comment]
Thanks @nicolo-ribaudo that is helpful, and I think I figured the issue

I use `yarn` and I believe `is-plain-object` got rollup to `5.0.0` by `vite-plugin-mkcert` which has a dependency `@octokit/endpoint` - see screenshot
<img width="496" alt="Screen Shot 2022-07-07 at 01 18 48" src="https://user-images.githubusercontent.com/657845/177726602-bd71fe81-b201-4c34-9592-5529b1627621.png">

<img width="832" alt="Screen Shot 2022-07-07 at 01 24 03" src="https://user-images.githubusercontent.com/657845/177727896-5b855ec7-4a4c-4dbb-9938-ebec4f029a4c.png">

And indeed `clone-deep` package show `"is-plain-object": "^2.0.4"`

So, the `is-plain-oject@2.0.4` indeed is a default export vs `is-plain-oject@5.0.0` is a static export

Therefore, @liuxingbaoyu s correct that it is not a bug from clone-deep, instead it is a version mismatcch with libraries that I use

**Comment by kenilam** [comment]
Thank you for responding @nicolo-ribaudo @liuxingbaoyu - I will do some investigation myself, and closing this issue
