### ISSUE TITLE
Unable to install/rebuild with io.js-v2.0.0

### ISSUE THREAD

**Issue by abrkn** [babel/babel#1475]
See https://github.com/strongloop/fsevents/issues/68

**Comment by sebmck** [comment]
This is a result of the `chokidar` dependency which is **optional** which means that if building it fails then  you can use Babel fine. Possibly open this issue on the [chokidar](https://github.com/paulmillr/chokidar/) repo, although it's using a range that includes the released version that you linked to.

**Comment by abrkn** [comment]
thanks for clarifying, @sebmck
