### ISSUE TITLE
a transitive dependency update changed codegen and broke coverage

### ISSUE THREAD

**Issue by michaelficarra** [babel/babel#1476]
In the Shift parser project, we lock down our version of babel so we can have reproducible builds. But recently a transitive dependency updated which not only changed the babel output, but also broke the `--auxiliary-comment` feature. See https://github.com/shapesecurity/shift-parser-js/pull/187 for the diff.

0. Please fix the `--auxiliary-comment` feature for `_inherits` and `_classCallCheck`
0. Is there any way we can guarantee reproducible builds without resorting to npm shrinkwrap?

**Comment by sebmck** [comment]
1. Please fix the `--auxiliary-comment` feature for `_inherits` and `_classCallCheck`

Done. Released as of 5.2.17.

2. Is there any way we can guarantee reproducible builds without resorting to npm shrinkwrap?

Not really. While this is a bug, I'm not going to guarantee that the output is going to be **exactly** the same throughout an entire major.

**Comment by michaelficarra** [comment]
Not major, patch. We lock down the release number in our package.json.
