### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xusyang** [babel/babel#14770]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

``` js
import generate from '@babel/generator'
import { parse } from '@babel/parser'

const code = `
  // this is a line comment
  const a = 1;
  // this is function comment
  const b = 2;
`

const ast = parse(code)
const result = generate(ast).code
// result != code

/* Result is : 

// this is a line comment
const a = 1; // this is function comment

const b = 2;"
*/
```

for up code, input code source is not equal to result. I can not sure that is generate's options reason.

### Current and expected behavior

if no extra options or operatings,  I hope that the input code is equal result.

### Environment

  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @babel/code-frame: ^7.18.6 => 7.18.6 
    @babel/core: ^7.18.6 => 7.18.6 
    @babel/generator: ^7.18.7 => 7.18.7 
    @babel/parser: ^7.18.6 => 7.18.6 
    @babel/template: ^7.18.6 => 7.18.6 
    @babel/traverse: ^7.18.6 => 7.18.6 
    @babel/types: ^7.18.7 => 7.18.7

**Comment by nicolo-ribaudo** [comment]
`@babel/generator` doesn't make any guarantee about the output format; if you need to preserve it you can either use [`recast`](https://github.com/benjamn/recast) or format Babel's output with something like prettier.
