### ISSUE TITLE
[Bug]: "Invalid host defined options" when using polypill-corejs3 with recent versions of @babel/core

### ISSUE THREAD

**Issue by literalpie** [babel/babel#14778]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

[Minimal reproduction repo](https://github.com/literalpie/webpack-babel-corejs)

### Configuration file name

.babelrc

### Configuration

```
{
  "presets": [],
  "plugins": [
    [
      "polyfill-corejs3",
      {
        "method": "usage-pure"
      }
    ]
  ]
}
```

### Current and expected behavior

Webpack build fails. It should not fail.

### Environment

```
System:
    OS: macOS 12.4
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    @babel/core: 7.16.10 => 7.16.10 
    babel-loader: 8.2.5 => 8.2.5 
    babel-plugin-polyfill-corejs3: 0.5.2 => 0.5.2 
    webpack: 5.73.0 => 5.73.0
```
I'm also on webpack-cli 4.8.0.

### Additional context

Downgrading to `@babel/core@7.16.7` or lower fixes the issue.
Upgrading to webpack-cli 4.10.0 also fixes the issue. Because of this, I'm not sure if this is a babel issue, an issue with the plugin, or an issue with Webpack CLI. 

I'm mostly making this issue so that if someone else runs into this, they will know they can update webpack-cli to fix the issue.

**Comment by nicolo-ribaudo** [comment]
This is a webpack-cli bug, that didn't allow using dynamic imports in any code that runs during the build project: https://github.com/webpack/webpack-cli/issues/1274
