### ISSUE TITLE
Incompatibility of `es7.asyncFunctions` and `bluebirdCoroutines` with blacklisted `es6.classes`

### ISSUE THREAD

**Issue by th0r** [babel/babel#1477]
Hey there!
Found one bug in `babel v5.2.17`.
This test snippet:
```js
class Cls1 {
    async method() {
        return Promise.resolve(1);
    }
}
```
transforms by
```
babel script.js --blacklist es6.classes --optional bluebirdCoroutines,es7.asyncFunctions
```
into this
```js
"use strict";

var _bluebird = require("bluebird");

class Cls1 {
    method()
}
```
Note that `method()` is empty.
If I remove either `--blacklist es6.classes` or `--optional bluebirdCoroutines` bug disappears.

P.S. Blacklisting `es6.classes` became actual with `iojs 2.0`

**Comment by sebmck** [comment]
This behaviour isn't really supported. It's basically the same as the `es7.decorators` transformer where it requires the desugaring of classes in order to work. It should probably throw an error but I haven't really added "transformer dependencies".

**Comment by th0r** [comment]
@sebmck So what do you recommend? Remove `--blacklist es6.classes`?

**Comment by sebmck** [comment]
Well, yeah.

**Comment by th0r** [comment]
@sebmck And the funny thing is if I remove `--optional bluebirdCoroutines` it will be transformed into
```js
"use strict";

class Cls1 {
    method() {
        return regeneratorRuntime.async(function callee$0$0$(context$1$0) {
            while (1) switch (context$1$0.prev = context$1$0.next) {
                case 0:
                    return context$1$0.abrupt("return", Promise.resolve(1));

                case 1:
                case "end":
                    return context$1$0.stop();
            }
        }, null, this);
    }
}
```

**Comment by sebmck** [comment]
That seems fine/expected. You can't replace a class method with a function call.

**Comment by th0r** [comment]
@sebmck Yes, got it =(

**Comment by th0r** [comment]
@sebmck Can't babel attach such methods to constructor's prototype after class definition or it's to complicated?

**Comment by sebmck** [comment]
It could but there are so few users using the bluebirdCoroutines transformer that it doesn’t justify the additional maintenance.

**Comment by th0r** [comment]
@sebmck But it could also help `es7.decorators` users as well.

**Comment by sebmck** [comment]
It wouldn’t. The code for decorated classes would be **extremely** verbose without the desugaring of the entire class and there would be literally no benefits since you need to work with the raw descriptors anyway.

**Comment by sebmck** [comment]
May look into supporting this in the `es7.decorators` transformer in the future though. I'm probably going to remove the `asyncToGenerator` and `bluebirdCoroutines` transformers in the next major since they're just unnecessary noise. Anyone is free to move them into a plugin since they're relatively simple.
