### ISSUE TITLE
[Bug]: AST changed in v7.18.9

### ISSUE THREAD

**Issue by fisker** [babel/babel#14777]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
new A < B >
C
```

### Current and expected behavior

Not sure when it changed, but after 7.18.5, I'm not familiar with this syntax, not sure what's correct. But Prettier format it different than `typescript` parser.

```js
// `typescript` parser and older babel
new A() < B > C;
```

```js
// new 
new A<B>();
C;
```

I think `B` is a type parameter now.

Same as `@typescript-eslint/eslint-plugin` parser?

### Environment

N/A

### Additional context

Prettier PR https://github.com/prettier/prettier/pull/13065

**Comment by JLHwung** [comment]
Likely a regression introduced in #14650. I think we should also add `tests/format/typescript` to our prettier-e2e tests.

**Comment by fisker** [comment]
Thank you!

**Comment by fisker** [comment]
> I think we can also add tests/format/typescript

`tests/format/flow` `tests/format/flow-repo` too?
