### ISSUE TITLE
[Bug]: `babel-plugin-polyfill-corejs3` transpiled code unspectly when using updateExpression

### ISSUE THREAD

**Issue by sanyuan0704** [babel/babel#14784]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var a = { repeat: 0 };
a.repeat++;
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": ["ie 11"]
        },
        "useBuiltIns": false,
        "corejs": 3,
        "modules": false
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 3
      }
    ]
  ]
}

```

### Current and expected behavior

Current result:

```js
import _repeatInstanceProperty from "@babel/runtime-corejs3/core-js-stable/instance/repeat";
var a = {
  repeat: 0
};
// Notice this line
_repeatInstanceProperty(a)++;
```

Expect result:
```js
var a = { repeat: 0 };
a.repeat++;
```

### Environment

System:
    OS: macOS 12.1
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  npmPackages:
    @babel/cli: 7 => 7.18.6 
    @babel/core: 7.18.2 => 7.18.2 
    @babel/plugin-transform-runtime: 7.18.9 => 7.18.9 
    @babel/preset-env: 7.18.2 => 7.18.2 
    @babel/runtime-corejs3: 7.7.4 => 7.7.4 

### Possible solution

When i open the function of @babel/plugin-transform-runtime，the bug will be reproduced.At the same time，`@babel/plugin-transform-runtime` use `babel-plugin-polyfill-corejs3` to analysis and inject polyfill code.But the latter didn't  consider the situation of using updateExpress such as `someObject.repeat ++`.

So i think it's better to fix like this：
```js
usagePure(meta, utils, path) {
      // When handling the object property
      if (meta.kind === "property") {
        if (!path.isMemberExpression()) return;
        if (!path.isReferenced()) return;
        //  Add the following line to skip the updateExpression
        if (!path.isUpdateExpression()) return;
      }
}
```

**Comment by sanyuan0704** [comment]
https://github.com/babel/babel-polyfills/pull/134

**Comment by liuxingbaoyu** [comment]
Fixed by https://github.com/babel/babel-polyfills/pull/134
