### ISSUE TITLE
[Bug]: Error when type and variable have the same name

### ISSUE THREAD

**Issue by Magin-CC** [babel/babel#14795]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
// this "A" is an Interface
import { A } from './interface';

class A {}
```

### Current and expected behavior

In babel, it throw TypeError: Duplicate declaration "A".
But it compile success in typescript.

### Environment

@babel/core: 7.18.2

**Comment by nicolo-ribaudo** [comment]
This matches TypeScript's behavior with `--isolatedModules`, which is Babel's goal. You have to explicitly annotate type imports:
```ts
import { type A } from './interface';

class A {}
```
or
```ts
import type { A } from './interface';

class A {}
```

**Comment by Magin-CC** [comment]
Thank you !
