### ISSUE TITLE
[Bug]: Pure annotations are incorrectly modified to wrong scope

### ISSUE THREAD

**Issue by hyrious** [babel/babel#14797]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
(/* @__PURE__ */ f()).g()
```

[REPL Link](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=BQegVABAAg-jAKBVASgUThMIIDNgEp8A6AcwKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.18.9&externalPlugins=&assumptions=%7B%7D)

### Configuration

None

### Current and expected behavior

Currently babel strips the parentheses of `(/* @__PURE__ */ f())`, causing the whole expression `f().g()` be marked as pure.

```js
/* @__PURE__ */
f().g();

// expect: same as input
```

### Environment

```
System:
  OS: macOS 12.5
Binaries:
  Node: 18.6.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 8.15.0 - /usr/local/bin/npm
npmPackages:
  @babel/core: ^7.7.4 => 7.18.9
  @babel/plugin-proposal-class-properties: ^7.7.4 => 7.18.6
  @babel/plugin-proposal-object-rest-spread: ^7.7.4 => 7.18.9
  @babel/plugin-transform-modules-commonjs: ^7.15.0 => 7.18.6
  @babel/preset-env: ^7.7.4 => 7.18.9
  @babel/preset-react: ^7.7.4 => 7.18.6
  @babel/preset-typescript: ^7.7.4 => 7.18.6
  babel-loader: ^8.0.6 => 8.2.5
  webpack: ^5.74.0 => 5.74.0
```

**Comment by JLHwung** [comment]
As a workaround, you can enable the `createParenthesizedExpressions` parser option:

```js
{
  // babel config
  plugins: [...],
  parserOpts: { createParenthesizedExpressions: true }
}
```

It will generate the `ParenthesizedExpressions` AST node where the pure annotation comment can be attached.
