### ISSUE TITLE
add "// Generated by babel vX.Y.Z" comment to generated files

### ISSUE THREAD

**Issue by michaelficarra** [babel/babel#1479]
The existence of this comment will let Github know to suppress the file when it is displayed (such as in a diff). It is also useful so people know which version of babel was used to generate the file.

**Comment by sebmck** [comment]
IMO it just adds unnecessary noise and 90% of users will want to turn it off and if it were to be added to core I wouldn't want it on my default which would effectively make it useless. If you want this behaviour then you can always use the following Babel plugin:

```sh
$ babel script.js --plugins ./plugin
```

**plugin.js**

```javascript
module.exports = function (babel) {
  return new Transformer("comment", {
    Program: function () {
      node.leadingComments = node.leadingComments || [];
      node.leadingComments.push({
        type: "Line",
        value: "Generated by Babel v" + babel.version
      });
    }
  });
};
```

Thanks!

**Comment by cmichaelgraham** [comment]
pretty slick :+1: suppose i wanted to echo back the leadingComments data structure as it looks in the source file?  got any cool code hanging around for that?

love babel, btw

babel plugins are too cool.

**Comment by loganfsmyth** [comment]
@cmichaelgraham Feel free to ask plugin questions in the #plugins Slack channel.
