### ISSUE TITLE
TCO performed on functions that close over values may break.

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#1480]
```
function callbackPerInt(count, cb){
  if (count < 0) return;
  
  cb(function(){ return count; });
  
  return callbackPerInt(count - 1, cb);
}
```

Currently, TCO makes this

```
function callbackPerInt(_x, _x2) {
  var _again = true;

  _function: while (_again) {
    _again = false;
    var count = _x,
        cb = _x2;

    if (count < 0) return;

    cb(function () {
      return count;
    });

    _x = count - 1;
    _x2 = cb;
    _again = true;
    continue _function;
  }
}
```

which means that the value returned by the final callback depends on when the function passed to the callback is called. If it's called synchronously inside `cb` then it will return the correct value, but otherwise it'll a later version of `count`.

I don't know the spec, but I'd guess we either need to skip optimizing, or the while loop body needs to be treated like all function-scoped variables are block-scoped inside the while loop like a normal while loop.

**Comment by sebmck** [comment]
> I don't know the spec, but I'd guess we either need to skip optimizing, or the while loop body needs to be treated like all function-scoped variables are block-scoped inside the while loop like a normal while loop.

Yeah, skipping optimisation is probably the most practical at this stage.

**Comment by loganfsmyth** [comment]
This is the important part of the spec, right?

> 14.6.3 Runtime Semantics: PrepareForTailCall ( )
The abstract operation PrepareForTailCall performs the following steps:
1. Let leafContext be the running execution context.
2. Suspend leafContext.
3. Pop leafContext from the execution context stack. The execution context now on the top of the stack
becomes the running execution context.
4. Assert: leafContext has no further use. It will never be activated as the running execution context.

> A tail position call must either release any transient internal resources associated with the currently executing function execution context before invoking the target function or reuse those resources in support of the target function.

Looking at this more, skipping optimization seems like it would break lots of valid code. As long as function using TCO-function scoped values is called synchronously, it seems like the spec description above would expect the function to be TCO properly. So it is only if state was closed over and a reference to the context is kept that TCO is not allowed.

The alternative being that the transform breaks code is bad though, not sure what the best choice is. Do we lose anything by going to IIFE route?

**Comment by RReverser** [comment]
> or the while loop body needs to be treated like all function-scoped variables are block-scoped inside the while loop like a normal while loop

Sounds like the best option to me and requires not much changes.

**Comment by sebmck** [comment]
I've removed TCO from Babel 6 as there are way too many issues with it since it relies on all ES6 desugaring. I've opened issue #2614 to track a reimplementation.

**Comment by RReverser** [comment]
@sebmck O_O minor issues arise in various features, that's a weird way of solving them :/

**Comment by sebmck** [comment]
@RReverser I want to ship ASAP and I do not have time to rewrite the transform. Babel 6 is going to ship with transforms that can be toggled on and off and everything will work fine and this isn't inline with that.
