### ISSUE TITLE
[Bug]: There is an error in the compiled code of version 7.18.9

### ISSUE THREAD

**Issue by AlexGoing** [babel/babel#14807]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

if (sometihing) {
     ```
    } else {
      const { a } = funA({
       ```
      });
    }

### Configuration file name

package.json

### Current and expected behavior

When I update Babel to version 7.18.9，some code cant compiler for es5，compiled code generation  error in  chrome browser:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/39686438/181509762-62e37c3b-3c25-440d-be7a-af4370cdc66e.png">

Babel compiled code:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/39686438/181509896-c0b55eed-45bb-483e-a066-29f8bca7bb97.png">

The above compiled code has syntax errors in the browser
![image](https://user-images.githubusercontent.com/39686438/181511603-fa06ee8c-7d6b-48fe-88e7-d3726d49cf6d.png)

origin code like this:
if (sometihing) {
     do something
    } else {
      const { a } = funA({
       do something
      });
    }

### Environment

System:
    OS: macOS 12.3.1
  Binaries:
    babel: 7.18.9
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    monorepo:yes

**Comment by JLHwung** [comment]
Can you post your Babel config?

**Comment by AlexGoing** [comment]
Babel config:
![image](https://user-images.githubusercontent.com/39686438/181757428-afa4c6f5-4a3d-4229-af60-a87af8ea472f.png)

**Comment by liuxingbaoyu** [comment]
[repl](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYMwBAFAzg9gtgUwC7ABbAHYHMCUYDeAUAIaEC-YCANlAgYQMYwZRIFjFgUC8YIArhgCCEIgCNyOANzkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.18.9&externalPlugins=&assumptions=%7B%7D)

I can't reproduce the problem in the repl.
Also I noticed the presence of `eval` in your error stack.

So this is probably highly relevant to your code, and you'd better provide a reproducible repo.

**Comment by nicolo-ribaudo** [comment]
@AlexGoing Are you using a minifier? That code looks more like something that would be generated by a minifier than by Babel.
