### ISSUE TITLE
Allow CodeGenerator.normalizeOptions to accept a maxCodeLength option

### ISSUE THREAD

**Issue by clintonjrobinson** [babel/babel#1481]
Surprisingly, I have a need for this my current project.  Currently hard coded to 100000 bytes, should be trivial to implement into the opts.

```javascript
   if (format.compact === "auto") {
      format.compact = code.length > 100000; // 100KB

      if (format.compact) {
        console.error(messages.get("codeGeneratorDeopt", opts.filename, "100KB"));
      }
    }
```

**Comment by sebmck** [comment]
Why can't you just manually set the `compact` option?

```javascript
babel.transform(code, {
  compact: code.length > yourMaxSize
});
```

**Comment by sebmck** [comment]
Closing this since you can just set the `compact` option manually and adding an additional option to control this would be overkill.

**Comment by clintonjrobinson** [comment]
@sebmck Ah good point.  Should have RTFM.  Thanks
