### ISSUE TITLE
Babel REPL shows only a single line on its console

### ISSUE THREAD

**Issue by yfain** [babel/babel#1482]
I'm testing a code fragment that has several console.log() statements, but Babel REPL shows only one line in its console at the bottom right. It would be nice if the REPL's console would support multi-line output (as in Traceur's REPL) so opening browser's console wouldn't be needed.

**Comment by sebmck** [comment]
See the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by yfain** [comment]
What a rude answer, sebmck. I've opened this issue after trying to find something in the doc.

**Comment by sebmck** [comment]
@yfain Excuse me? I'm pointing you in the right direction.

**Comment by loganfsmyth** [comment]
@yfain He means `babel/babel` is for features/bugs in the transpiler. The REPL code lives in https://github.com/babel/babel.github.io so you should file a bug in that issue queue for REPL-related requests.
