### ISSUE TITLE
[Bug]: Instance of `Object spread` not transpiled correctly for Safari 11

### ISSUE THREAD

**Issue by DEV-ONI** [babel/babel#14823]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
{
    test: /\.js$/,
    loader: "babel-loader",
    exclude: /node_modules\/(?!ufo)/,
    options: {
        presets: [
            ["@babel/preset-env", { corejs: 3, debug: true }],
        ],
        plugins: ["@babel/plugin-transform-runtime"],
    },
},
```

### Current and expected behavior

I'm using `babel-loader` in order to transpile my web project, which includes transpiling some node_modules as well ( since we require support for ios > 10 ), however while other modules as well as project code seem to be transpiling correctly, the `[ufo](https://www.npmjs.com/package/ufo)` seems to leave an instance of the spread operator untranspiled.

Any ideas what might be causing this? I've excluded narrowed down my babel configs to just that module

@babel/preset-env: `DEBUG` option

```
Using targets:
{
  "ios": "10.3"
}

Using modules transform: auto

Using plugins:
  proposal-class-static-block { ios }
  proposal-private-property-in-object { ios < 15 }   
  proposal-class-properties { ios < 15 }
  proposal-private-methods { ios < 15 }
  proposal-numeric-separator { ios < 13 }
  proposal-logical-assignment-operators { ios < 14 } 
  proposal-nullish-coalescing-operator { ios < 13.4 }
  proposal-optional-chaining { ios < 13.4 }
  proposal-json-strings { ios < 12 }
  proposal-optional-catch-binding { ios < 11.3 }     
  transform-parameters { ios }
  proposal-async-generator-functions { ios < 12 }
  proposal-object-rest-spread { ios < 11.3 }
  transform-dotall-regex { ios < 11.3 }
  proposal-unicode-property-regex { ios < 11.3 }
  transform-named-capturing-groups-regex { ios < 11.3 }
  transform-async-to-generator { ios < 11 }
  transform-template-literals { ios < 13 }
  transform-unicode-regex { ios < 12 }
  transform-block-scoping { ios < 11 }
  proposal-export-namespace-from { ios }
  syntax-dynamic-import
  syntax-top-level-await

```

### Environment

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  npmPackages:
    @babel/core: ^7.16.0 => 7.18.10
    @babel/plugin-transform-modules-commonjs: ^7.18.6 => 7.18.6
    @babel/plugin-transform-runtime: ^7.16.4 => 7.18.10
    @babel/preset-env: ^7.16.4 => 7.18.10
    babel-loader: ^8.2.3 => 8.2.5
    eslint: ^8.4.1 => 8.21.0
    jest: ^28.1.3 => 28.1.3
    webpack: ^5.65.0 => 5.74.0

### Additional context
The code block:

```js
function withQuery(input, query) {
  const parsed = parseURL(input);
  const mergedQuery = { ...parseQuery(parsed.search), ...query };
  parsed.search = stringifyQuery(mergedQuery);
  return stringifyParsedURL(parsed);
}
```

**Comment by liuxingbaoyu** [comment]
Can you try specifying a newer corejs version?

ref: https://github.com/babel/babel/discussions/12642#discussioncomment-288590

**Comment by JLHwung** [comment]
I can't reproduce this issue on [REPL](https://babel.dev/repl#?browsers=ios%2010.3&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAdxlAFgRRAUwE4CeAFDGAA4hQA0iAjroQJSIDeAUIohAgM5SJkAhnh44AJogC8A4aICqAJQAyJcpUYBuDl178AtvgDm47PgJTWiAHQ2hInKcJE7osVdHCI6RjRtX6ZogAvlqcLuLuOJ7oFnx4pIYwwASOxAZ4xmKpmtp4OFAgeEhxCUkEAAqy4ooq4WI5QWxAA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.18.10&externalPlugins=&assumptions=%7B%22setClassMethods%22%3Atrue%2C%22noDocumentAll%22%3Atrue%7D).

Do you have any other Babel config that may ignore `node_modules`? You can look for `.babelrc` / `babel.config.*`. Can you attach the output of

```
BABEL_SHOW_CONFIG_FOR="./node_modules/ufo/dist/index.cjs" npm build 
```

or any other build command you are using. It should print the Babel config applied to the `ufo` package.

**Comment by DEV-ONI** [comment]
Apologies.

I needed to include `*.cjs` in the tests
