### ISSUE TITLE
[Bug]: @babel/helper-wrap-function@7.18.10 build error

### ISSUE THREAD

**Issue by ostwindli** [babel/babel#14824]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

This change [https://github.com/babel/babel/commit/4f278dc05a85da3ce39687f59691e23c1c66877b#diff-13301793f9705926efa934907a80c6d92342813613d1ef42e638f21158d395d9R12](https://github.com/babel/babel/commit/4f278dc05a85da3ce39687f59691e23c1c66877b#diff-13301793f9705926efa934907a80c6d92342813613d1ef42e638f21158d395d9R12)  results in an error.

The corresponding version is [https://www.npmjs.com/package/@babel/helper-wrap-function/v/7.18.10](https://www.npmjs.com/package/@babel/helper-wrap-function/v/7.18.10)

### Current and expected behavior

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/17735161/182574700-7804caea-0cc9-4e4f-b840-1d3c94bdcc05.png">

### Environment

System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  npmPackages:
    @babel/core: 7.12.3 => 7.12.3 
    @babel/generator: 7.17.10 => 7.17.10 
    @babel/helper-module-imports: 7.12.1 => 7.12.1 
    @babel/helper-wrap-function: 7.18.9 => 7.18.9 
    @babel/helpers: 7.12.1 => 7.12.1 
    @babel/parser: 7.17.10 => 7.17.10 
    @babel/plugin-proposal-class-properties: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-decorators: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-do-expressions: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-export-default-from: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-export-namespace-from: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-function-bind: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-function-sent: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-optional-chaining: ^7.11.0 => 7.18.9 
    @babel/plugin-proposal-pipeline-operator: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-private-methods: 7.12.1 => 7.12.1 
    @babel/plugin-proposal-throw-expressions: 7.12.1 => 7.12.1 
    @babel/plugin-syntax-dynamic-import: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-modules-commonjs: ^7.15.4 => 7.18.6 
    @babel/plugin-transform-runtime: 7.12.1 => 7.12.1 
    @babel/plugin-transform-typescript: ^7.16.1 => 7.18.10 
    @babel/preset-env: 7.12.1 => 7.12.1 
    @babel/preset-typescript: ^7.10.4 => 7.18.6 
    @babel/runtime: 7.12.1 => 7.12.1 
    @babel/template: 7.16.7 => 7.16.7 
    @babel/traverse: 7.17.10 => 7.17.10 
    babel-code-frame: ^6.26.0 => 6.26.0 
    babel-loader: ^8.1.0 => 8.2.5 
    babel-plugin-istanbul: ^6.0.0 => 6.1.1 
    eslint: ^7.9.0 => 7.32.0 
    jest: ^26.6.1 => 26.6.3 
    webpack: ^5.73.0 => 5.73.0 

### Possible solution

use version 7.18.9

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/pull/14752#issuecomment-1203510392

Could you try this?

**Comment by JLHwung** [comment]
Fixed in `@babel/helper-wrap-function` 7.18.11.
