### ISSUE TITLE
[Bug]: 7.18.0 missing isTopicReference from @babel/types

### ISSUE THREAD

**Issue by SleeplessByte** [babel/babel#14820]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```javascript
// file.ts
null?.test
```

// I cannot make it fail on repl, I can see that the export doesn't exist in the source

### Configuration file name

.babelrc

### Configuration

```json
{
  "assumptions": {
    "noDocumentAll": true
  },
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": "3.24",
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "~src": "./src",
          "~test": "./test"
        }
      }
    ]
  ]
}
```

### Current and expected behavior

**Expected**: Running `yarn babel src --out-dir dist --extensions .ts` is supposed to work.

**Current**:
```shell
$ yarn babel src --out-dir dist --extensions .ts
$ path\to\node_modules\.bin\babel src --out-dir dist --extensions .ts
TypeError: path\to\file.ts: isTopicReference is not a function
$   at Scope.isStatic (path\to\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:441:52)
```

### Environment
```text
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.4.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\.yarn\bin\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/cli: ^7.18.10 => 7.18.10
    @babel/core: ^7.18.10 => 7.18.10
    @babel/node: ^7.18.10 => 7.18.10
    @babel/preset-env: ^7.18.10 => 7.18.10
    @babel/preset-typescript: ^7.18.6 => 7.18.6
    @babel/types: ^7.18.10 => 7.18.10
    babel-jest: ^27.5.1 => 27.5.1
    babel-plugin-module-resolver: ^4.1.0 => 4.1.0
    eslint: ^8.21.0 => 8.21.0
    jest: ^27.5.1 => 27.5.1
```

#### Workaround (downgrade)

```json
{
  "@babel/cli": "~7.17.10",
  "@babel/core": "~7.17.12",
  "@babel/node": "~7.17.10",
  "@babel/preset-env": "~7.17.12",
  "@babel/preset-typescript": "~7.17.12",
  "@babel/types": "~7.17.12"
}
```

#### Fix

Remove `isTopicReference` import and call from `babel-types` or add it to `@babel/types`.

### Additional context

- The source for `@babel/types` does _not_ export a function called `isTopicReference` as seen here: https://github.com/babel/babel/blob/main/packages/babel-types/src/index.ts (version tagged: https://github.com/babel/babel/blob/v7.18.10/packages/babel-types/src/index.ts)
- The source for `babel-traverse` _expects_ it as seen here: https://github.com/babel/babel/blob/703ee007378c9de464fbef58a7175f7c15e1f051/packages/babel-traverse/src/scope/index.ts#L50 (version tagged: https://github.com/babel/babel/blob/v7.18.10/packages/babel-traverse/src/scope/index.ts#L50)

**Comment by SleeplessByte** [comment]
> [v7.18.10/packages/babel-types/src/validators/generated/index.ts#L3068](https://github.com/babel/babel/blob/v7.18.10/packages/babel-types/src/validators/generated/index.ts#L3068)

I guess it's supposed to be exported via this line then
https://github.com/babel/babel/blob/v7.18.10/packages/babel-types/src/index.ts#L95, right? Going into the source after I nuked `node_modules` didn't solve it. 

> The error may be due to circular imports in @babel/types, can you provide a reproduction repo?

Ah yeah, right, that could be the case.

When testing I used resolutions to make sure all versions were the same to remove that option (mismatching version in a sub-sub dependency) as well.

```json
"resolutions": {
  "**/@babel/types": "^7.18.0"
}
```

Repo I encountered this on was https://github.com/exercism/javascript-analyzer. If you change the versions to .18 and `yarn install`, it is encountered directly in post install (as that tries to compile).

Was able to reproduce it by removing _all_ `.ts` files and only keeping a single one with `null?.test`.

**Comment by JLHwung** [comment]
I notice that there are two `@babel/types` copies in the current `main` lock file:

https://github.com/exercism/javascript-analyzer/blob/ef83d093155bd806e1d0f242a4b61b2f78783e60/yarn.lock#L1435-L1450

I updated Babel deps to 7.18 in [this branch](https://github.com/JLHwung/javascript-analyzer/tree/update-babel-7-18) and yarn removes the `7.17` one. However I can't reproduce the post install error either in `main` or the this branch.

Can you share a reproducible branch? It may have a different lock file which results to different node modules layout.

**Comment by SleeplessByte** [comment]
Sorry, yes. That's only because of the changes I made to workaround the problem. Let me try to reproduce for you with a fresh clone from the correct "commit".

**Comment by SleeplessByte** [comment]
Ugh. 

Okay. I think yarn borked this. This is what I did.

1. First I tried to reproduce the issue again by copying the previous lock (https://github.com/exercism/javascript-analyzer/blob/43342063fc3c7c34f3a9cdd08854d8e2734faf4c/yarn.lock) and previous package.json + updating to .18. No dice.
2. Then I tried a fresh clone: everything fine again.
3. I then opened the original folder where I still had the issue open. Here a `yarn install` gives me the postinstall error. In this copy of node_modules this package is somehow stuck on 7.15 (but there are also many copies of babel-types). Nuking the lock _and_ node_modules here and re-installing fixed it.

I don't know what caused this. The same steps don't yield the same results. Things I can think of:
- My hard drive is dying
- VS Code was locking the file for whatever reason so it did not update
- There is a bug in yarn
- babel was executing for whatever reason as I was installing.

Since this seems solved for me, I'll close it, but I'm a bit scared it will happen again. If so, I'll get you a reproducible commit.

**Comment by JLHwung** [comment]
> In this copy of node_modules this package is somehow stuck on 7.15 (but there are also many copies of babel-types). Nuking the lock and node_modules here and re-installing fixed it.

If you are using Yarn 1, you can try https://github.com/scinos/yarn-deduplicate, it keeps node_modules smaller and you are way less likely to come across such bugs.

**Comment by SleeplessByte** [comment]
Thank you @JLHwung. That looks like exactly what I had needed.
