### ISSUE TITLE
[Bug]: Incorrect error location info when using `jsx` plugin and `startColumn`

### ISSUE THREAD

**Issue by fisker** [babel/babel#14838]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
<a></a>
<b></b>
```

### Current and expected behavior

```text
require('@babel/parser').parse('<a></a>\n<b></b>',{plugins: [],startColumn: 99})
Uncaught:
[SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (1:99)
] {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'MissingOneOfPlugins',
  loc: Position { line: 1, column: 99, index: 0 },
  pos: [Getter/Setter],
  missingPlugin: [Getter/Setter]
}
```

```text
require('@babel/parser').parse('<a></a>\n<b></b>',{plugins: ['jsx'],startColumn: 99})
Uncaught:
[SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (2:0)
] {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnwrappedAdjacentJSXElements',
  syntaxPlugin: 'jsx',
  loc: Position { line: 2, column: 0, index: 8 },
//                                 ^ `column` should be 99
  pos: [Getter/Setter]
}
```

### Environment

Should not related.

### Additional context

There seems more in https://github.com/prettier/prettier/pull/13262, but I'm not sure how to reproduce them all, will have to fix one by one.

**Comment by thorn0** [comment]
This works as intended. `startLine` and `startColumn` only redefine the location of the beginning of the code. The intended use case is parsing JS code embedded in some other file.

**Comment by fisker** [comment]
It seems 

> That changes the column number only for the first line. 

 https://github.com/prettier/prettier/pull/13262#issuecomment-1209103198

Is it expected?

@JLHwung Mentioned since you implement it in #13887

**Comment by JLHwung** [comment]
Yes, it works as intended. `(startLine, startColumn)` defines the location of `(0, 0)` in the embed sources.

> should I request a columOffset option instead?

It could be confusing with `startColumn`. If you are dealing with small `columnOffset` like 2, 3, 4. You can pass Babel the modified sources, presumably those with desired whitespaces-padding. Or you can catch the parser error and append the offset to the column info.

**Comment by fisker** [comment]
Thanks for the answer. Close then.
