### ISSUE TITLE
[Bug]: babel-node ignoring config file

### ISSUE THREAD

**Issue by spacepluk** [babel/babel#14839]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

Here's a simple repro:

https://github.com/spacepluk/test-babel

Running this works as expected and you can see it prints the log in the config file:
` npx babel index.js --out-dir dist`

This on the other hand fails to import the text files because it's ignoring the config file (I think):
` npx babel-node --config-file babel.config.js index.js`

### Configuration file name

babel.config.js

### Configuration

Here's the output when running babel to generate a build, babel-node doesn't output any config and it just shows the import error.

```
BABEL_SHOW_CONFIG_FOR=./index.js npx babel index.js --out-dir dist

CONFIG
Babel configs on "/Users/spacepluk/Hacking/crypthulhu/test-babel/index.js" (ascending priority):
config /Users/spacepluk/Hacking/crypthulhu/test-babel/babel.config.js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ],
  "plugins": [
    [
      "babel-plugin-inline-import",
      {
        "extensions": [
          ".graphql",
          ".cdc"
        ]
      }
    ]
  ]
}

programmatic options from @babel/cli
{
  "sourceFileName": "../index.js",
  "caller": {
    "name": "@babel/cli"
  },
  "filename": "index.js"
}
-----End Babel configs-----
Successfully compiled 1 file with Babel (443ms).
```

### Current and expected behavior

I'm trying to use babel-plugin-inline-import in a simple project but it seems like babel-node is ignoring the configuration file. It works when running babel directly to generate a build.

### Environment

  System:
    OS: macOS 12.5
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.18.10 => 7.18.10
    @babel/core: ^7.18.10 => 7.18.10
    @babel/node: ^7.18.10 => 7.18.10
    @babel/preset-env: ^7.18.10 => 7.18.10
    babel-plugin-inline-import: ^3.0.0 => 3.0.0

### Additional context

![image](https://user-images.githubusercontent.com/824762/183622443-30b5e356-e8a6-4258-b6ea-781b24529c82.png)

**Comment by liuxingbaoyu** [comment]
Currently `babel-node` only supports packages with `"type": "commonjs"` in `package.json`.
It works fine after I set `"type": "commonjs",`.
![image](https://user-images.githubusercontent.com/30521560/187770300-84aa2242-b9de-45d0-8173-e4e77df8c28d.png)

ref: https://babeljs.io/docs/en/babel-register/#experimental-babel-8-implementation

> Note: @babel/register does not support compiling native Node.js ES modules on the fly, since currently there is no stable API for intercepting ES modules loading.
