### ISSUE TITLE
[Bug]: new.target Error but Report Redeclaration

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14848]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
const doubleAndReturnArgs = (array, ...values) => {
    return [
        ...array,
        ...values.map(val => new.target)
    ];
};
```
Here is [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.21&spec=true&loose=true&code_lz=GYVwdgxgLglg9mABMAFADwDSIJ5YF4CUiA3gFAC-poksCy6WuihJFVKYApgO4B0UAQwBOAc05QCAbiA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=Node-10.13&version=7.18.12&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Babel report error
```shell
/repl.js: Identifier 'f' has already been declared. (3:9)
```
But should the right mistake be
```shell
Meta-property 'new.target' is only allowed in the body of a function declaration, function expression, or constructor
```

### Environment

- babel 
- - ├── @babel/cli@7.18.12
- - ├── @babel/plugin-transform-runtime@7.18.12
- - ├── @babel/preset-env@7.18.12
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by liuxingbaoyu** [comment]
It looks like the input code in the issue is inconsistent with the repl.
````js
function f(x, y, z) {
}
function f(x, y, z) {
}
f(new.target);
````
There are two errors in this code, it's just that babel is thrown in a different order than chrome.

**Comment by nicolo-ribaudo** [comment]
When running that code as a module, chrome/Node.js throw `Uncaught SyntaxError: Identifier 'f' has already been declared`. If you want the `new.target` error, you must specify `sourceType: "script"`.

(Also, the ECMAScript spec only requires that that code throws a `SyntaxError`, but it doesn't define the message).
