### ISSUE TITLE
[Bug]:Error: Module is not Defined in Transpiled Code

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14849]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
module.exports = {
    valor: 1,
    inc() {
        (() => this.x).valor++;
    }
};
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=LYewJgrgNgpgdDAHgBxAJwC4GcAEBeHAbwCgcycA3AQynQC4cBGAGlPIEsA7AYwAoBKIm3LleA_AD4cGABbsscRPzjVaaANTqA3MJwBfYnq1A&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=Node-10.13&version=7.18.12&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Node runs the code report error transpiled by Babel
```shell
module is not defined
```

### Environment

- babel 
- - ├── @babel/cli@7.18.12
- - ├── @babel/plugin-transform-runtime@7.18.12
- - ├── @babel/preset-env@7.18.12
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/184473477-61f3c94b-6431-489d-ae7c-abd3f094b3dc.png)

The code in the repl works fine, can you check it?

**Comment by nicolo-ribaudo** [comment]
The `module` variable is not defined anywhere in your input code: it's relying on a `module` global (for example, provided by CommonJS). If the compiled code throws `module is not defined`, it's because that global is not present.
