### ISSUE TITLE
[Bug]: This function must be inherited from.

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14851]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var accValue;
class AbstractNumbers {
    constructor(...values) {
        if (new.target === AbstractNumbers) {
            throw new TypeError('This function must be inherited from.');
        }
        this.values = values;
    }
}
let AbstractNumbersProxy = new Proxy(AbstractNumbers, { ...accValue });
let instance = new AbstractNumbersProxy(1, 2, 3, 4);
console.log(instance.values);
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBCDG0GogDYFcCmBuAUNRIDOeEAggEZ4AuYM5AcsgLYmpiEDemEnE0A9gHYUwyaOR5gAFADppoFKjwBKCOy6qIASwBmEcX1QB3SeXABzVOQgBea8TKVqdRs0XKOa9-QAWYHvoh6_ABUATwAHVABRMB8JAHJAz3VCTWQ-EXV-CHpkCggmDT5PZnVyVAATCE0feklYhSx3TgBfNw9EvElZNEJLCC75Bq4WlsRzW0EHBiYWAAUfAA9gq38DCDmeRfFSCZFHabwAGmUIaUkYeCQ0CCb6zFGLdQFjNNRlgPH7Xanndc2ARiOACYjgBmI4AFluvAEPFGkkQPBM4keFBAL06l3k9SAA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=Node-10.13&version=7.18.12&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

The original code print
```shell
[ 1, 2, 3, 4 ]
```
But transpiled by babel, the code run by node will throw an exception set by Babel
```shell
TypeError: This function must be inherited from.
```

### Environment

- babel 
- - ├── @babel/cli@7.18.12
- - ├── @babel/plugin-transform-runtime@7.18.12
- - ├── @babel/preset-env@7.18.12
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
This is documented at https://babeljs.io/docs/en/babel-plugin-transform-new-target#caveats: `new.target` works the same as `this.constructor` when compiled by Babel.
