### ISSUE TITLE
[Bug]: `new.target` can only be used in functions or class properties.

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14852]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
(test) = async () => {
    await new.target && global.__MONGOD__.stop();
    console.log('test')
};
test()
```
Here is [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=BQFwpgziCUAEC8sCGECeA7AxrYd4D5YBvAKFnOQHckBLEWdMSgOhCQCcBzMegMl9icANgHsARkiHMA-tICyAeQByAcQUARWcygiADrgDcZCphHoIIoWGajOwAOTgo96CQC-RpyFxA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=Node-10.13&version=7.18.12&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

The code print normally but report 
```shell
/repl.js: `new.target` can only be used in functions or class properties. (2:10)
```
when transpiled by babel

### Environment

- babel 
- - ├── @babel/cli@7.18.12
- - ├── @babel/plugin-transform-runtime@7.18.12
- - ├── @babel/preset-env@7.18.12
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
When run uncompiled, that code throws `Uncaught SyntaxError: new.target only allowed within functions` in Firefox and `Uncaught SyntaxError: new.target expression is not allowed here` in Chrome, so it's correct for Babel to throw.
