### ISSUE TITLE
[Bug]: Res is not Defined

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14857]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
const Events = /\P{Number}/s;
console.log(Events)
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=true&loose=true&code_lz=MYewdgzgLgBAogNwKZihGBeGB6AOgBQG8A5AVwFsAjJAJwF9sIBuAKFEhABskA6TkAOYAKRCjQBKIA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=&version=7.18.12&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Babel report error
```shell
Res is not defined
```
But nodejs can run this code 

### Environment

- babel 
- - ├── @babel/cli@7.18.12
- - ├── @babel/plugin-transform-runtime@7.18.12
- - ├── @babel/preset-env@7.18.12
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
This is a bug in regjsparser 0.8, fixed in 0.9. I'm looking at what we need to do to upgrade it.
