### ISSUE TITLE
State per file, init per file

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#1485]
This issue is to discuss design of a state per file, and init hook per file in each transform.

The API of a trasnformer today is an object which properties are names of the nodes, and corresponding handlers of those nodes:

```javascript
var funcsPerFile = [];

new Transformer('Foo', {
  Function: function(node, parent) {
    funcsPerFile.push(node.name.id);
    ...
  }
});
```

The problems is, the transform instance is created _once_, and then is ran for _all_ files. This means that collections at module-level (like `funcsPerFile`) are going to be preserved between different files runs. In order to initialize some data  "per-file", today's "workaround" is to have the `Program` handler:

```javascript
var callsPerFile;

new Transformer('Foo', {
  Program: function(node) {
    callsPerFile = [];
  },

  Function: function(node, parent) {
    funcsPerFile.push(node.name.id);
    ...
  }
});
```

This works well today, however some people don't like having the module-level data. Also, if by some reason you need to do two pass of the program in one transform, the data will be overridden.

Alternative to storing this state at module level, we could have just a property `_callsPerFile` sitting on the transformer, but this looks a bit weird, because usually there sit node handlers (and `_callsPerFile` doesn't sound like a node name).

Not an urgent thing (since "`Program` + module-level vars" pattern works), but something to discuss.

CC @amasad

**Comment by sebmck** [comment]
The main thing that I've been struggling with is how to expose it to a transformer. There are currently 4 arguments passed to visitors (`node, parent, scope, state/file`) and adding another one may be overloading it, `this` is also taken by the nodes `TraversalPath`.

Currently `file` has a Map-like API that you can use to store arbitrary data:

```javascript
file.set("foo", 5);
file.get("foo");
```

**Comment by sebmck** [comment]
The plugin visitor method type signature has been changed to `(path, state)` so you an store metadata on the `state` object. There's also `pre` and `post` method hooks.
