### ISSUE TITLE
[feat request] stage 3 decorators proposal

### ISSUE THREAD

**Issue by trusktr** [babel/babel#14889]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I think since the 2021-12 release there have been a few minor changes and the spec went to stage 3. 

### Describe the solution you'd like

It would be sweet to have that version of proposal-decorators to start trying it out.

### Describe alternatives you've considered

waiting

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/14836, it will be in the next minor release.
