### ISSUE TITLE
[Bug]: Package "exports" field stripped on publishing

### ISSUE THREAD

**Issue by marvinhagemeister** [babel/babel#14887]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

None, this is an error with the babel's publishing process.

### Current and expected behavior

The development entry point of the `@babel/transform-plugin-react-jsx` cannot be imported in ESM environments because the `exports` field [is missing in the published package](https://www.runpkg.com/?@babel/plugin-transform-react-jsx@7.18.10/package.json). It's present [in the source](https://github.com/babel/babel/blob/cf0b1e74a2bd2c3f631459869ae856d146f70020/packages/babel-plugin-transform-react-jsx/package.json#L52-L56) though, so I'm assuming that this is a publishing error.

Due to the missing field it not possible to load the `development.js` entry point.

### Environment

- Babel version: 7.18.10
- Node: 18.7.0
- Yarn: 1.22.17
- OS: macOS 12.5.1

**Comment by nicolo-ribaudo** [comment]
We cannot publish "exports" yet for backward compatibility (when publishing in non-Babel-8 mode, it's [set to null](https://github.com/babel/babel/blob/cf0b1e74a2bd2c3f631459869ae856d146f70020/packages/babel-plugin-transform-react-jsx/package.json#L42)). You can use `@babel/plugin-transform-react-jsx-development` instead.

**Comment by marvinhagemeister** [comment]
TIL, I didn't know about that package. Switched to that, but I can't get it to work either. Node still sees the `./lib/development.js` require call in that package and errors.

**Comment by nicolo-ribaudo** [comment]
That is a cjs-to-cjs require, I don't see why Node.js would error 🤔

**Comment by marvinhagemeister** [comment]
Ok so I couldn't reproduce it with node in isolation, but something in a test project which uses astro + vite the error reliably occurs. 

Here is the stack trace:

```
 error   Package subpath './lib/development' is not defined by "exports" in /project/node_modules/.pnpm/@babel+plugin-transform-react-jsx-development@7.18.6_@babel+core@7.18.13/node_modules/@babel/plugin-transform-react-jsx/package.json
  File:
    /project/src/components/Foo.jsx
  Stacktrace:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/development' is not defined by "exports" in /project/node_modules/.pnpm/@babel+plugin-transform-react-jsx-development@7.18.6_@babel+core@7.18.13/node_modules/@babel/plugin-transform-react-jsx/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/project/node_modules/.pnpm/@babel+plugin-transform-react-jsx-development@7.18.6_@babel+core@7.18.13/node_modules/@babel/plugin-transform-react-jsx-development/lib/index.js:13:20)
```

**Comment by nicolo-ribaudo** [comment]
Can you check if `project/node_modules/.pnpm/@babel+plugin-transform-react-jsx-development@7.18.6_@babel+core@7.18.13/node_modules/@babel/plugin-transform-react-jsx/package.json` contains an `exports` field? 🤔

**Comment by liuxingbaoyu** [comment]
I'll close it due to long periods of inactivity, feel free to open it if the problem persists.

**Comment by marvinhagemeister** [comment]
The issue still exists, but I haven't had time to follow up. The `package.json` doesn't contain the `exports` field.

**Comment by nicolo-ribaudo** [comment]
> The package.json doesn't contain the exports field.

That's expected and it's known to not cause problems, most of the packages on npm don't contain the exports field.

**Comment by nicolo-ribaudo** [comment]
@marvinhagemeister Any update on this?
