### ISSUE TITLE
[Bug]: branches coverage isn't correct with 7.18.13

### ISSUE THREAD

**Issue by CSchulz** [babel/babel#14899]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Using following typescript code with jest-preset-angular@12 and angular@13:

```
@Pipe({
  name: 'config',
})
export class ConfigPipe implements PipeTransform {
  constructor(private service: ConfigService) {
    console.log('');
  }

  public transform<K extends keyof Config>(key: K): Config[K] {
    return this.service.get(key);
  }
}
```

### Current and expected behavior

Branches are covered with 7.18.10 for 100 % and 7.18.13 for 75 %.

I have tracked it down to the change between @babel/core@7.18.10 and @babel/core@7.18.13.
Here is the direct diff between the instrumented code fragments:
https://www.diffchecker.com/2omuXETX

### Environment

babel/core 7.18.13
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.14.2 - C:\nodejs\node.EXE
    npm: 8.5.0 - C:\nodejs\npm.CMD
  Monorepos:
    Lerna: 5.1.8
  npmPackages:
    eslint: ~8.2.0 => 8.2.0
    jest: ~28.1.0 => 28.1.3
    lerna: ~5.1.3 => 5.1.8

**Comment by liuxingbaoyu** [comment]
Can you provide a repo that reproduces it?

**Comment by CSchulz** [comment]
I am trying to set it up, but it is not easy because I can't produce it in a tiny project.

**Comment by liuxingbaoyu** [comment]
Ok, if the project is not private, a not-minimal reproduction might also help.

**Comment by nicole-ashley** [comment]
I know it's not that helpful, but this is affecting our project too via an upgrade from Angular 15.0.4 to 15.1.0 (which upgraded @babel/core). 

It's a large, private project so not helpful for repro. But the upgrade lowers not both the total number of branches and the coverage of those branches (coverage lowers more than total so the ratio ends up lower, which is how I noticed the issue).

**Comment by nicolo-ribaudo** [comment]
Closing as no repository to reproduce the issue has been provided.
