### ISSUE TITLE
class ClassTail only occurs as part of an ExportDeclaration

### ISSUE THREAD

**Issue by timoxley** [babel/babel#1490]
[section 14.5.15, Runtime Semantics: BindingClassDeclarationEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-bindingclassdeclarationevaluation), states:
 
> ClassDeclaration : class ClassTail
> Return the result of ClassDefinitionEvaluation of ClassTail with argument undefined.
> NOTE ClassDeclaration : class ClassTail only occurs as part of an ExportDeclaration and the setting of > a name property and establishing its binding are handled as part of the evaluation action for that  production. See 15.2.3.11.

[![image](https://cloud.githubusercontent.com/assets/43438/7552056/6af75a92-f6d3-11e4-90bb-54bbbbdccdf8.png)](
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-bindingclassdeclarationevaluation)

This makes me believe that the following should not be valid when parsed by babel, should require a proceeding `export`:

```js
const A = class {
  constructor() {
    
  }
}
```

[View the above source in babel repl](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20A%20%3D%20class%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A%0Aconsole.log(A.toString()))

**Comment by sebmck** [comment]
That's a ClassExpression, not a ClassDeclaration.

On Saturday, 9 May 2015, Tim Oxley <notifications@github.com> wrote:

> section 14.5.15, Runtime Semantics: BindingClassDeclarationEvaluation
> <https://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-runtime-semantics-bindingclassdeclarationevaluation>,
> states:
>
> ClassDeclaration : class ClassTail
> Return the result of ClassDefinitionEvaluation of ClassTail with argument
> undefined.
> NOTE ClassDeclaration : class ClassTail only occurs as part of an
> ExportDeclaration and the setting of > a name property and establishing its
> binding are handled as part of the evaluation action for that production.
> See 15.2.3.11.
>
> [image: image]
> <https://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-runtime-semantics-bindingclassdeclarationevaluation>
>
> This makes me believe that the following should not be valid when parsed
> by babel, should require a proceeding export:
>
> const A = class {
>   constructor() {
>
>   }
> }
>
> View the above source in babel repl
> <https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20A%20%3D%20class%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A%0Aconsole.log(A.toString())>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1490>.
>


-- 
Sebastian McKenzie

**Comment by timoxley** [comment]
@sebmck my bad.

**Comment by sebmck** [comment]
Just to clarify, that specific note is about the behaviour of:

```javascript
export default class {}
```

**Comment by timoxley** [comment]
indeed, and this correctly does not parse:

```js
class {

}
```
