### ISSUE TITLE
Update sourcemaps at function declaration sites

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#14907]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Chrome is releasing a new feature called [friendly call frames](https://developer.chrome.com/blog/devtools-modern-web-debugging/#friendly-call-frames), where they'll use the sourcemaps's unminified names when rendering the callstack in dev tools:

Before:
<img width="224" alt="Screen Shot 2022-09-02 at 12 54 28 PM" src="https://user-images.githubusercontent.com/112982/188205812-f2a7c1a7-8d17-4e8d-9aad-0bdf7c8ba0d7.png">

After:
<img width="226" alt="Screen Shot 2022-09-02 at 1 19 57 PM" src="https://user-images.githubusercontent.com/112982/188205831-34628b65-c235-4797-ab16-579388a14d2c.png">

To unminify a frame, you need to have a name attached to the `(` of the _declaration site_. So, we need to have a name:

```js
function foo() {
//          ^ Here
  bar(baz);
}

function bar(callback) {
//          ^ Here
  callback();
}

function baz() {
//          ^ Here
  throw new Error('test');
}

foo();
```

It doesn't matter that we've properly named the `bar`/`callback`/`Error`/`foo` identifiers at before the `(`, the segment that includes the `(` must also include it.

Insert breakpoints whatever point you want in: https://gray-nifty-brook.glitch.me/

### Describe the solution you'd like

We can take Terser's approach of generating a single segment for the full `bar(` (instead of one for `bar` and one for `(`).

Or, we can include the name as part of the individual segment for the `(`. This'll produce slightly larger sourcemaps (a single additional byte is necessary for each `(`).

### Describe alternatives you've considered

Do nothing. DX is important, and this isn't acceptable.

**Comment by liuxingbaoyu** [comment]
It's all good for me. However, the second one seems to have fewer modifications and is more beautiful, so as long as there are no compatibility issues, I prefer the second one.

**Comment by nicolo-ribaudo** [comment]
@liuxingbaoyu Did your recent sourcemap changes fix this?

**Comment by liuxingbaoyu** [comment]
Should not. I'm not sure what I'm trying to do, maybe it needs to be upstream?
Feel free to say if there is anything that needs to be done in babel.

**Comment by jridgewell** [comment]
We need to add the function's identifier name to the call that marks the opening `(` of the function. This needs to be done by babel.
