### ISSUE TITLE
[Bug]: Extra newlines added to JSX with retainLines option

### ISSUE THREAD

**Issue by dexbol** [babel/babel#14918]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
const Test = function () {
    var a = 1;
    return (
        <div>
            {a === 1 && (
                <div>
                    <p>1</p>
                    <p>11</p>
                </div>
            )}
            {a === 22 && (
                <div>
                    <p>2</p>
                    <p>22</p>
                </div>
            )}
        </div>
    );
};
```

### Current and expected behavior
```javascript
generate(ast, {
        retainLines: true,
        compact: true
});
```
Current output:
```javascript
const Test = function () {
    var a = 1;
    return (
        <div>
            {a === 1 && (
                <div>
                    <p>1</p>
                    <p>11</p>
                </div>
            )}

            {a === 22 && (
                <div>
                    <p>2</p>
                    <p>22</p>
                </div>
            )}
        </div>
    );
};
```
Expect output:
```javascript
const Test = function () {
    var a = 1;
    return (
        <div>
            {a === 1 && (
                <div>
                    <p>1</p>
                    <p>11</p>
                </div>
            )}
            {a === 22 && (
                <div>
                    <p>2</p>
                    <p>22</p>
                </div>
            )}
        </div>
    );
};
```

### Environment

@babel/core v7.19.0
@babel/generate v7.19.0
node v18.4
Mac OS 12.5.1

**Comment by nicolo-ribaudo** [comment]
Related: https://github.com/babel/babel/issues/14868

**Comment by liuxingbaoyu** [comment]
After a long period of debugging I found that I can't seem to reproduce it.😅
There are no extra newlines, just the parentheses are removed and the curly braces are merged onto the previous line.

input
```
const Test = function () {
  var a = 1;
  return (
      <div>
          {a === 1 && (
              <div>
                  <p>1</p>
                  <p>11</p>
              </div>
          )}
          {a === 22 && (
              <div>
                  <p>2</p>
                  <p>22</p>
              </div>
          )}
      </div>
  );
};
```
output
```
const Test = function () {
  var a = 1;
  return (
    <div>
          {a === 1 && 
      <div>
                  <p>1</p>
                  <p>11</p>
              </div>}
          
      {a === 22 && 
      <div>
                  <p>2</p>
                  <p>22</p>
              </div>}
      
    </div>);

};
```

**Comment by dexbol** [comment]
> After a long period of debugging I found that I can't seem to reproduce it.😅 There are no extra newlines, just the parentheses are removed and the curly braces are merged onto the previous line.
> 
> input
> 
> ```
> const Test = function () {
>   var a = 1;
>   return (
>       <div>
>           {a === 1 && (
>               <div>
>                   <p>1</p>
>                   <p>11</p>
>               </div>
>           )}
>           {a === 22 && (
>               <div>
>                   <p>2</p>
>                   <p>22</p>
>               </div>
>           )}
>       </div>
>   );
> };
> ```
> 
> output
> 
> ```
> const Test = function () {
>   var a = 1;
>   return (
>     <div>
>           {a === 1 && 
>       <div>
>                   <p>1</p>
>                   <p>11</p>
>               </div>}
>           
>       {a === 22 && 
>       <div>
>                   <p>2</p>
>                   <p>22</p>
>               </div>}
>       
>     </div>);
> 
> };
> ```
thanks for your feedback , I will try to creating a test repo for reproducing .

**Comment by dexbol** [comment]
> There are no extra newlines, just the parentheses are removed and the curly braces are merged onto the previous line.

Finally, I got it. "the newline" is the empty line that the right curly braces remained . Is there some way to remove the empty line if the content merged to previous line.

BTW, I created a test repo anyway. https://github.com/dexbol/babel-generator-test

Thank you very much.

**Comment by liuxingbaoyu** [comment]
You're welcome. The purpose of the `retainlines` option is to try to keep the line numbers consistent, if you want to not have this blank line, you can use `retainlines: false`.

**Comment by dexbol** [comment]
Got it. It is a feature not a bug 😄.  I will keep using `retainLines: true`, and using eslint `react/jsx-newline` to remove empty lines.
