### ISSUE TITLE
simplify return value of scope

### ISSUE THREAD

**Issue by Dashed** [babel/babel#1491]
Input:
```js
function fn() {
    {
        let tree;
        foo(function() {
          tree;
        });
        return;
    }
}
```

Output:
```js
"use strict";

function fn() {
    {
        var _ret = (function () {
            var tree = undefined;
            foo(function () {
                tree;
            });
            return {
                v: undefined
            };
        })();

        if (typeof _ret === "object") return _ret.v;
    }
}
```

I was wondering if the `if (typeof _ret === "object") return _ret.v;` boilerplate can be skipped.

----

REPL: https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=function%20fn()%20%7B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20let%20tree%3B%0A%20%20%20%20%20%20%20%20foo(function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20tree%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%7D%0A%7D%0A

**Comment by sebmck** [comment]
Not really. You need a way to tell the outer return that it's explicit.
