### ISSUE TITLE
this is undefined on static methods, with 'use strict'

### ISSUE THREAD

**Issue by kim3er** [babel/babel#1492]
With without `"use strict"`, the following code returns four `false` logs. With, the first three logs are `true`.

I accept that the third log, `new RunConvert(func);`, relates to boxing. I don't understand why I can't access `this` for the first two examples.

In the first log, the class has been initiated correctly, so should behave the same as the fourth log (I think).

The second log uses a static method. If this example is working correctly, I fail to see how else I'd access static variables without `this`.

It is the second log that is of most importance to me. Could someone explain why `this` is undefined, or confirm that it is bug?

``` js
class Person {
  
  iconvert() {
    console.log(this === undefined);
  }
  
  static convert() {
    console.log(this === undefined);
  }
  
}

function func() {
  console.log(this === undefined);
}

class RunConvert {
  
  constructor(convertor) {
    convertor();  
  }
  
}

new RunConvert(Person.convert);
new RunConvert(new Person().iconvert);
new RunConvert(func);

new Person().iconvert()
```

**Comment by zloirock** [comment]
[Looks like you don't understand logic of `this` keyword](https://goo.gl/KPexlb).

**Comment by kim3er** [comment]
Hey @zloirock, it appears not. Thank you, that example was really helpful. I was not aware of `bind`. Rich
