### ISSUE TITLE
"this" in module scope always compiles to "undefined"

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#1493]
```js
this.foo;
```

[compiles to](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=this.foo%3B)

```js
"use strict";

undefined.foo;
```

So for example [this doesn't work as expected](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=false&code=(function%20()%20%7B%0A%20%20console.log(this%20%3D%3D%3D%20undefined)%3B%0A%7D).call(this)%3B%0A).

**Comment by zloirock** [comment]
See [FAQ](https://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-).
