### ISSUE TITLE
[Bug]: JSX inside .js syntax error only with @babel/plugin-transform-typescript

### ISSUE THREAD

**Issue by gremo** [babel/babel#14942]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
import React from 'react';

const Component = () => {
  return (
    <h1>Hello world!</h1>
  );
};
```

### Configuration file name

.babelrc.json

### Configuration

```json
{
  "presets": [
    ["@babel/preset-env", {
      "corejs": 3,
      "useBuiltIns": "usage",
      "bugfixes": true
    }],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    ["@babel/plugin-transform-typescript", {
      "allowDeclareFields": true
    }],
    "@babel/plugin-proposal-class-properties"
  ]
}
```

### Current and expected behavior

1. All files (`.tsx?` `.jsx?`) are processed using babel
2. The following error occurs when you use JSX inside `.jsx?` file

Example file:

```js
import React from 'react';

const Component = () => {
  return (
    <h1>Hello world!</h1>
  );
};
```

```
Syntax Error: Unexpected token, expected "," (5:14)

  3 | const Component = () => {
  4 |   return (
> 5 |     <h1>Hello world!</h1>
    |               ^
  6 |   );
  7 | };
  8 |
```

Expect no error, the file should be transpiled correctly I suppose.

### Environment

- Windows 10 x64
- node 16.15.0
- npm 8.10.0
- babel 7
- @babel/preset-typescript: 7.18.6
- @babel/preset-react: 7.18.6
- react: 18.2.0
- react-dom: 18.2.0

### Possible solution

Remove `@babel/plugin-transform-typescript` and errors is gone (**not a solution**).

### Additional context

Working solution:

```json
{
  "presets": [
    ["@babel/preset-env", {
      "corejs": 3,
      "useBuiltIns": "usage",
      "bugfixes": true
    }],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "overrides": [
    {
      "test": ["**/*.ts", "**/*.tsx"],
      "plugins": [
        ["@babel/plugin-transform-typescript", {
          "allowDeclareFields": true
        }]
      ]
    }
  ]
}
```

or just (leave  the preset choose the extension (usually ts/tsx):

```json
{
  "presets": [
    ["@babel/preset-env", {
      "corejs": 3,
      "useBuiltIns": "usage",
      "bugfixes": true
    }],
    "@babel/preset-react",
    ["@babel/preset-typescript", {
      "allowDeclareFields": true
    }]
  ]
}
```

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/en/options#overrides
Did you try this?

**Comment by gremo** [comment]
@liuxingbaoyu thanks for the input, i'm going to check it right now. I'm try to pass `allowDeclareFields` to `@babel/preset-typescript` without using the plugin directly.

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/en/babel-preset-typescript#allowdeclarefields
Yes it is possible.

**Comment by gremo** [comment]
@liuxingbaoyu yes, but it's not working for me and others, see comments here: https://stackoverflow.com/a/70701279/220180

**Comment by liuxingbaoyu** [comment]
Looks like it's because the plugin runs before the preset.
https://github.com/babel/babel/blob/main/packages/babel-preset-typescript/src/index.ts
You can refer here, just use the ts plugin and put it in front of `@babel/plugin-proposal-class-properties`.

**Comment by gremo** [comment]
O I can confirm that:

1. The plugin `@babel/plugin-transform-typescript` seems not loaded when using the `preset-typescript` alone. I've tested inserting a debug code here: https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-typescript/src/index.ts#L83
2. When I use `@babel/plugin-transform-typescript` into `.babelrc.json` plugin is activated (debug code shown)... but i'ts applied also to JS files.

Maybe I'm wrong?

**Comment by gremo** [comment]
@liuxingbaoyu what do you mean with "put it in front of @babel/plugin-proposal-class-properties"? Is already at the top and will be invoked before!

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/en/plugins#plugin-ordering
as you are using.
```js
  "plugins": [
    ["@babel/plugin-transform-typescript", {
      "allowDeclareFields": true
    }],
    "@babel/plugin-proposal-class-properties"
  ]
```

**Comment by gremo** [comment]
@liuxingbaoyu yes, exactly my configuration... and it's not working because it's applied to javascript files too, throwing the syntax error.

**Comment by liuxingbaoyu** [comment]
```js
  presets: [
    [
      "@babel/preset-env",
      {
        corejs: 3,
        useBuiltIns: "usage",
        bugfixes: true,
      },
    ],
    "@babel/preset-react",
  ],
  overrides: [
    {
      test: /\.jsx$/,
      plugins: ["@babel/plugin-proposal-class-properties"],
      test: /\.tsx$/,
      plugins: [
        [
          "@babel/plugin-transform-typescript",
          {
            allowDeclareFields: true,
          },
        ],
        "@babel/plugin-proposal-class-properties",
      ],
    },
  ],
```

Does this work?

**Comment by gremo** [comment]
@liuxingbaoyu Syntax is wrong BTW, i'm try to test overrides. But it's not clear why this behaviour...

**Comment by liuxingbaoyu** [comment]
Can you provide a repository to reproduce?

**Comment by gremo** [comment]
@liuxingbaoyu thanks for the help. I think I have solved moving the option to the preset, and removing the plugin from the plugins array.

When plugin is added "manually" the issue still occurs. Maybe it's the intended way?

**Comment by liuxingbaoyu** [comment]
Maybe this could work.
```js
  overrides: [
    {
      test: /\.jsx$/,
      plugins: ["@babel/plugin-proposal-class-properties"],
    },
    {
      test: /\.tsx$/,
      plugins: [
        [
          "@babel/plugin-transform-typescript",
          {
            isTSX: true,
            allowDeclareFields: true,
          },
        ],
        "@babel/plugin-proposal-class-properties",
      ],
    },
  ],
```
