### ISSUE TITLE
Incorrectly formed source maps (Windows)

### ISSUE THREAD

**Issue by clintwood** [babel/babel#1496]
Given a directory ./srcmaps which contains:
```
// app.es6
import {Greeter} from './greeter';

var greeter = new Greeter();
greeter.sayHi('FooBar');
```
doing this
`babel -s true './*.es6' -d ../build`
you get a source map that looks like this (formatted):
```
{
  "version": 3,
  "sources": ["..\\srcmaps\\app.es6"],
  "names": [],
  "mappings": ";;AAEA,SAAQ,OAAO,QAAO,WAAW,CAAC;;AAElC,IAAI,OAAO,GAAG,IAAI,OAAO,EAAE,CAAC;AAC5B,OAAO,CAAC,KAAK,CAAC,QAAQ,CAAC,CAAC",
  "file": "./app.es6",
  "sourceRoot": "./babel/src",
  "sourcesContent": ["\n// app.es6\nimport {Greeter} from './greeter';\n\nvar greeter = new Greeter();\ngreeter.sayHi('FooBar');\n"]
}
```
It looks like `sources` and `sourceRoot` should be as follows:
```
{
  "sources": ["../srcmaps/app.es6"], <-- use forward/nix separators
  "sourceRoot": "./",                <-- relative to this sourcemap file
}
```
EDIT: babel 5.2.17
EDIT: in the above `"file": "./app.es6"` is also incorrect and should be `"file": "./app.js"` since that is the file output by `babel` and to which the source map refers.

**Comment by jquense** [comment]
@clintwood has this caused actual breakage on your end? Its a bit hard to see what the issue is. Are you saying that the output sourcemaps should format paths in a *nix format regardless of the platform? Or that they are being formatted that way but should be windows style paths on windows (that shouldn't matter windows handles both '/' and '\' just fine)

**Comment by clintwood** [comment]
FYI, I've added edit to original issue regarding incorrect "file" value.

@jquense, no direct breakage (except in `node-inspector`, although this may be an issue with `node-inspector` itself), however, there are a number of indirect issues/nuances this causes:
- node-inspector: sources panel tree view does not accurately reflect the original source layout (due to incorrect `sourceRoot`). Actually it becomes a mess.
- it becomes difficult to consume the source maps for further processing by tools like  [mozilla/source-map](https://github.com/mozilla/source-map)
- there is inconsistent use of *nix & Windows path separators (IMHO, just use *nix all round)

I guess my main issue is that having consistency between tools generating source maps makes life a lot nicer!
Some references are [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) and[`source-map`](https://github.com/mozilla/source-map/#new-sourcemapconsumerrawsourcemap).

**Comment by lydell** [comment]
The sources and sourceRoot fields are _urls_ so they should use forward slashes.

**Comment by sebmck** [comment]
Nope, nothing about source maps implies they're only for browsers. Do you
have a spec reference?

On Tuesday, 12 May 2015, Simon Lydell <notifications@github.com> wrote:

> The sources and sourceRoot fields are *urls* so they should use forward
> slashes.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1496#issuecomment-101332083>.
>


-- 
Sebastian McKenzie

**Comment by lydell** [comment]
Not exactly a spec reference, but anyway: mozilla/source-map#91

**Comment by lydell** [comment]
Related: https://github.com/babel/babel/blob/a402d0cdeb341bcd691752167d14260cfa612dc4/src/babel/transformation/file/index.js#L137

**Comment by clintwood** [comment]
+1 for forward slashes...  since Windows 'handles both' anyway!

See references [at the bottom here](https://github.com/babel/babel/issues/1496#issuecomment-101177339).

Also original issue was more about incorrectly based references in the source map file including `sourceRoot` and `file`.

**Comment by jquense** [comment]
to be clear. Windows can handle both types of path separators but tooling built for Windows may or may not handle it. It is best to use the appropriate platform path separators when possible.

**Comment by sebmck** [comment]
I've normalised the filenames when using the CLI to unix path separators. Happy to accept a PR(s) that makes the behaviour of `sourceRoot` better, I believe you can manually use the `--source-root` arg anyway anyway.

**Comment by clintwood** [comment]
Awesome, will have a look at doing PR...
