### ISSUE TITLE
[Bug]: A transpiled generator should not have enumerable properties

### ISSUE THREAD

**Issue by p51lee** [babel/babel#14978]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
for ( var x in function * ( ) { } ) while ( x ) ;
```

### Current and expected behavior

The program is expected to terminate immediately, but in reality the transpiled program does not terminate.

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=since%202105&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYewTgBAFBBuCGkAeECWA7CwCu6DGALqiJgFTQQCUEA3hAL5UQDuAFqgDYCmFK1A3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.19.2&externalPlugins=&assumptions=%7B%7D)

**Comment by JLHwung** [comment]
The `constructor` property of a generator should be non-enumerable, however `regenerator-runtime` configure it as enumerable.

https://github.com/facebook/regenerator/blob/f6255cadd4e5272c1957c57a32760e232fd3dc97/packages/runtime/runtime.js#L107

This is an upstream issue.
