### ISSUE TITLE
Arguments array shared when function returns arrow function.

### ISSUE THREAD

**Issue by ludvigsen** [babel/babel#1497]
See [this fiddle](http://www.es6fiddle.net/i9jo79zv/) for an example.

**Comment by sebmck** [comment]
Expected behaviour. See the [FAQ](http://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-) as well as #842, #814, #733 and #730. Also, ES6 Fiddle uses [Traceur](https://github.com/google/traceur-compiler) not Babel so this is consistent behaviour.
