### ISSUE TITLE
Object method decorator doesn't seem to be working properly

### ISSUE THREAD

**Issue by gsklee** [babel/babel#1500]
Class method decorator behavior:
```javascript
function f(target, key, descriptor) {
  descriptor.value = () => 100;
}

class person {
  @f age() {
    return 10;
  }
}

console.log(new person().age());
// 100, as expected
```

Object method decorator behavior:
```javascript
function f(target, key, descriptor) {
  descriptor.value = () => 100;
}

var person = {
  @f age() {
    return 10;
  }
}

console.log(person.age());
// 10
```

**Comment by sebmck** [comment]
See the [decorators proposal](https://github.com/wycats/javascript-decorators) and [initializer interop document](https://github.com/wycats/javascript-decorators/blob/master/INITIALIZER_INTEROP.md). Class methods use `value`, class properties and object properties use a function called `initializer`.
