### ISSUE TITLE
Write some of small plugins that replace slow language constructs with more productive ones

### ISSUE THREAD

**Issue by budarin** [babel/babel#15002]
### 💻

- [ ] Would you like to work on this feature?
I would be very happy to participate, but my knowledge of Babel is very poor

### What problem are you trying to solve?

In the current version of V8, there are many narrow, in terms of performance, language instructions:
 - the `for` loop is still the most productive in relation to `forEach`, `map`, `for-in`, `for-of`
 - simple concatenation of strings from an array using `+` is several times faster than the native `join` method
 - `split` is much slower than `indexOf` and `substring`
 - and many others

### Describe the solution you'd like

it would not be difficult for you to write a small number of such small plugins that replace slow designs with more productive ones - this would allow a lot of developers not to worry about the performance of their code - they would write code in the most convenient way and plugins, thanks to performance tests, could be connected to the project and fix performance problems

I suggest creating a preset `perfomance-env` 😊

### Describe alternatives you've considered

I haven't found any alternatives yet

**Comment by liuxingbaoyu** [comment]
Looks like a good idea, but I'm not sure if this is suitable as an official babel plugin.

**Comment by budarin** [comment]
you can officially contain performance tests for the latest versions of V8 and, depending on the purpose, enable or disable certain preset-performance-envv plugin

**Comment by nicolo-ribaudo** [comment]
I agree with @liuxingbaoyu: such plugins/presets don't need to be under this org.

There are many popular Babel plugins/presets on npm not maintained by us, this could just be one of them.

**Comment by budarin** [comment]
if you try to search for such plugins, you will find that there are practically none, and those that are made superficially and cover only classical syntactic constructions - fans cannot write such a set of plugins

**Comment by liuxingbaoyu** [comment]
This is difficult, and even what we are currently doing relies on compatibility data and polyfills provided by third parties.
And performance testing is more complicated, especially for modern ones with jit (similar to v8).
Any trivial operation can cause performance problems.
https://v8.dev/blog/react-cliff
In addition, the benchmark suite in the nodejs field is not perfect. The most used one has not been updated for 4 years.
https://github.com/bestiejs/benchmark.js

**Comment by budarin** [comment]
understand, this functionality is not just a wishlist or a taste - it should have been good for Babel out of the box from the very beginning - this is like syntax highlighting in the IDE (and like who needs to write a plugin or look for it - syntax highlighting is a matter of taste)

Absolutely any team that works with a heavy load comes to the need for such plugins that fix performance problems of many syntactic constructions - only now the issue is solved not by plugins but by directives like: we do not write forEach, map, fot-in, for-of - we write only for.

And everyone suffers in silence. If there were such a set of plugins, Babel would be used in every project for node.js

**Comment by budarin** [comment]
I'm ready to start writing performance tests for the plugin checklist!

**Comment by budarin** [comment]
> In addition, the benchmark suite in the nodejs field is not perfect. The most used one has not been updated for 4 years.
> https://github.com/bestiejs/benchmark.js

I think that nothing has been updated there for 4 years, because there is basically nothing to update there anymore - the logic of the tests is honed and works well, but nothing has changed dramatically since then so that something needs to be changed

**Comment by budarin** [comment]
For example, we have pain on the project now - we have to write directives on what to use and what not to use the CPU efficiently - we have to think not about solving problems in the usual way and style, but constantly writing effective designs - it's very tiring and it's bad practice - tools like Babel should take care of this

**Comment by budarin** [comment]
It's the 21st century!
this should be an industry standard, and we still write our crutches every time, just like in the days of mammoths! :)
