### ISSUE TITLE
[Bug]: Babel is inserting a space child in call to React.createElement

### ISSUE THREAD

**Issue by russellfoster** [babel/babel#15004]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

function hello() {
  return <div> <div>Hello world!</div></div>;
}

### Configuration file name

package.json

### Current and expected behavior

I originally reported this as a MUI issue, since the MUI stepper component would error out when a space child is added:

[MUI issue](https://github.com/mui/material-ui/issues/33930)

The MUI team is convinced that babel is outputting incorrect code in this case:

> > > Space is added not by Babel but by Prettier. It is not valid for the `React.ReactNode` type, so the behavior is correct
> > 
> > 
> > The output I get from babel is adding a separate space node to the create element call.
> 
> This is nothing to do with MUI. We expect React.ReactNode type as pointed out. Please check with babel about the empty space.

[Link](https://github.com/mui/material-ui/issues/33930#issuecomment-1236104965)

### Environment

[Babel compiler](https://babeljs.io/repl/#?presets=react&code_lz=GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAUIogE6pQhlIA8AJjAG4B8AEhlogO5xnr0AhLQD0jVgG4iAXyJA)

Input:
```
function hello() {
  return <div> <div>Hello world!</div></div>;
}
```
 Output:
```
function hello() {
  return /*#__PURE__*/React.createElement("div", null, " ", /*#__PURE__*/React.createElement("div", null, "Hello world!"));
}
```

**Comment by liuxingbaoyu** [comment]
https://www.typescriptlang.org/play?noImplicitAny=false&ts=4.8.0-beta#code/GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAsAFCKIBOqUIFSAPACYwBuAfIk62wBIZaIA7nArpGAQnoB6Zu2my2AblIBfIA

I tested in the typescript repl and got the same output.
So it's probably not a problem with babel.

**Comment by nicolo-ribaudo** [comment]
You should delete the space from the input:
```diff
  function hello() {
-   return <div> <div>Hello world!</div></div>;
+   return <div><div>Hello world!</div></div>;
  }
```

**Comment by russellfoster** [comment]
> You should delete the space from the input:
> 
> ```diff
>   function hello() {
> -   return <div> <div>Hello world!</div></div>;
> +   return <div><div>Hello world!</div></div>;
>   }
> ```

Hmm this never occurred to me before, brilliant!

Anyways, as I mentioned before I think that the component itself should handle whitespace elements, but was told babel was the culprit, so I posted here hoping to find some spec reason why it adds space elements (similar to how html does, etc).

Also, while this example is obvious, with jsx it is not always so obvious. Take for example:

```
<Stepper activeStep={activeStep}> {steps.map((label, index) => {
    const stepProps = {};
    const labelProps = {};
    if (isStepOptional(index)) {
      labelProps.optional = (
        <Typography variant="caption">Optional</Typography>
      );
    }
    if (isStepSkipped(index)) {
      stepProps.completed = false;
    }
    return (
      <Step key={label} {...stepProps}>
        <StepLabel {...labelProps}>{label}</StepLabel>
      </Step>
    );
  })}
</Stepper>
```
If I send the {} expression to the next line, no space element. I've seen some parsers add a single whitespace element for space " " or newline, and then collapse any subsequent whitespace, so if this is by design, that's great, it would be nice to let the component makers know what to expect.

**Comment by russellfoster** [comment]
So to sum up:

element + newline + element, no space in output
element + 1 or more spaces + element or expression beginning "{", one space in output.
element + 1 or more spaces + newline + 0 or more spaces + element, no space in output

**Comment by nicolo-ribaudo** [comment]
Exactly. It may not be the most intuitive way, but:
- every tool aligns and the behavior has been the same for year, changing now would be a big breaking change
- I believe the origin of that behavior is that it's a mix of how inline HTML elements and block HTML elements behave

**Comment by russellfoster** [comment]
> Exactly. It may not be the most intuitive way, but:
> 
> * every tool aligns and the behavior has been the same for year, changing now would be a big breaking change
> * I believe the origin of that behavior is that it's a mix of how inline HTML elements and block HTML elements behave

I don't think any change is warranted, but it may be good to add something in the documents that expressions should always begin on a newline because of this behavior.

Couple of other notes:

element + 1 or more spaces + element or expression beginning "{", one space in output.
is actually
element + 1 or more spaces + element or expression beginning "{", the string between the elements, so 1 or more spaces.

Noticed this case is also different from straight html:
```
export default function App() {
  return (
    <div>hello
        <span>world</span>
    </div>
    );
}
```
There is no space element.

With html you get the space from the newline in the following:
```
<div>hello
    <span>world</span>
</div>
```
Output:
<div>hello
    <span>world</span>
</div>
