### ISSUE TITLE
[Bug]: Why `Array.includes` is polyfilled at `Chrome 52` when MDN shows `Chrome 47`

### ISSUE THREAD

**Issue by hbrls** [babel/babel#15014]
### How are you using Babel?

@babel/cli

### Input code

```javascript
// input.js
const arr = [1, 2, 3];
const res = arr.includes(4);
console.log(res);

// output.js
require("core-js/modules/es.array.includes");
...
```

### Configuration file name

babel.config.js

### Configuration

```javascript
// .browserslistrc
chrome 52

// .babel.config.js
presets: [
    ['@babel/preset-env', {
      useBuiltIns: 'usage',
      corejs: '3',
```

### Current and expected behavior

I'm working on some edge cases of polyfill.

The [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#browser_compatibility) shows `Array.include` is supported since `Chrome 47`.

I expect the `.browserslistrc` to config `chrome 47` without polyfill and `chrome 46` with polyfill.

But it's actually `chrome 52` the last version to include a polyfill, and `chrome 53` the first version to not include a polyfill.

I'm not sure if it's my misunderstanding of the config, or a bug about using data from MDN.

### Environment

- @babel/core@7.11.6
- node@14

**Comment by nicolo-ribaudo** [comment]
For core-js@3 we use the compat-data provided by core-js itself: https://github.com/zloirock/core-js/tree/master/packages/core-js-compat

**Comment by hbrls** [comment]
The data by [core-js-compat](http://zloirock.github.io/core-js/compat/) is `53`.
Thanks. I'll have a look at the difference.
