### ISSUE TITLE
[Bug]: transform-template-literals produces wrong syntax

### ISSUE THREAD

**Issue by pkit** [babel/babel#15028]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

```js
execute(`
              WITH "last_invite" AS (SELECT *
                                     FROM "invites"
                                     WHERE "business_email" = :email
                                       AND "org_id" = :org_id
                                     ORDER BY "date_created" DESC LIMIT 1)
              SELECT short_from_uuid("id"), "business_email", "fname", "lname", "full_name", "phone", "role"
              FROM "last_invite"
              WHERE "status" IN (${statuses})`, { email, org_id })
```

### Configuration

it's a rollup config
```js
        getBabelOutputPlugin({
          presets: ['@babel/preset-env'],
        }),
```

### Current and expected behavior

current
```js
execute("\n              WITH \"last_invite\" AS (SELECT *\n                                     FROM \"invites\"\n                                     WHERE \"business_email\" = :email\n                                       AND \"org_id\" = :org_id\n                                     ORDER BY \"date_created\" DESC LIMIT 1)\n              SELECT short_from_uuid(\"id\"), \"business_email\", \"fname\", \"lname\", \"full_name\", \"phone\", \"role\"\n              FROM \"last_invite\"\n              WHERE \"status\" IN (".concat(statuses), ")"), {
    email: email,
    org_id: org_id
  });
```
expected
```js
execute("\n              WITH \"last_invite\" AS (SELECT *\n                                     FROM \"invites\"\n                                     WHERE \"business_email\" = :email\n                                       AND \"org_id\" = :org_id\n                                     ORDER BY \"date_created\" DESC LIMIT 1)\n              SELECT short_from_uuid(\"id\"), \"business_email\", \"fname\", \"lname\", \"full_name\", \"phone\", \"role\"\n              FROM \"last_invite\"\n              WHERE \"status\" IN (".concat(statuses) + ")", {
    email: email,
    org_id: org_id
  });
```  

### Environment

@babel/preset-env@7.19.3

### Possible solution

Dunno, works fine for simpler statements.

**Comment by liuxingbaoyu** [comment]
Can you provide a reproducible repo? I tested in repl and it works fine.

[repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=G4QwTgBAzgLiMFcoFMoF4BEt5NRgNMgLYgCWANpsWeQQPZgDmA-qQCaYMvsYDcAUIIDGdAHZQ65ZADpydRgAoABvwhr1GjQHUAkgBUAEhAzkQsVqOCkYyDBACCAZQgLHAUQAybgMJ6IAKlVNYJDQsIgAMQAlAHkAWWNSS2s8IPD0jLUtAzcot2MAIyQk1Chmago7NAgALgryNMymsPsAOQARYy5WNira7vZG5uG1GKj23IgAIQBNYzZ4ZGYhMGRF3ogJx28IDx04_QgARgBKIbD3L19oAAsGGGYAMzA6ImYEBHYFDB4T_ELiqJSuUSJV_hhHqIQERbODyFCYQRjI8EORyMwEbDjAAHO5ApEYF5SDDnULReLGUzmJJWGwkprZXL5LBwRBQOw6VouAAkAG9sGzUABfE5Kf68iD1f4DNgQEVAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.19.3&externalPlugins=&assumptions=%7B%7D)

![image](https://user-images.githubusercontent.com/30521560/194643062-2313e732-7fd4-4a31-a69d-3ad895e50c7d.png)
