### ISSUE TITLE
Optional Hack pipes

### ISSUE THREAD

**Issue by ronag** [babel/babel#15039]
The pipeline proposal also mentions a short-circuiting mechanism. I think it would be useful if babel implemented this so that we can start to experiment with usage.

https://github.com/tc39/proposal-pipeline-operator#optional-hack-pipes

**Comment by JLHwung** [comment]
See https://github.com/babel/babel/pull/14255#issuecomment-1034257810, it should come up with an independent ES proposal before Babel can implement it.
