### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by usrgnome** [babel/babel#15030]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
if(false){
  function function123(){}
}
console.log(function123); // expected "undefined"

```

### Configuration file name

babel.config.js

### Configuration

site: https://babeljs.io/repl/
presets: ENV
force all transforms (ON)

### Current and expected behavior

An incorrectly transforming function declared function variable name.

Results in:
```js
if (false) {
  var _function = function _function() {};
}

console.log(function123); // throws an error "function123" is undefined", but is expected to log "undefined"
```

### Environment

https://babeljs.io/repl/ default settings

### Possible solution

Numbers at the end of the variable get cut causing this issue as well as adding a _ to the start of the var name

_No response_

**Comment by liuxingbaoyu** [comment]
Similar to this https://github.com/babel/babel/issues/14960, both caused by `@babel/plugin-transform-block-scoped-functions`, I might look at it in a few days.
This plugin looks rudimentary, maybe disabling it by default is a good option.

**Comment by usrgnome** [comment]
> Similar to this #14960, both caused by `@babel/plugin-transform-block-scoped-functions`, I might look at it in a few days. This plugin looks rudimentary, maybe disabling it by default is a good option.

Disabling this plugin worked. Thank you.

**Comment by liuxingbaoyu** [comment]
The problem also seems to be related to `transform-block-scoping`, which is enabled under node6 or chrome49.

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAQwBQEoDeAoRjeIzCrDIA2AzgKZYGiSwKLAtpYC-2nECFcZVAHRk4AcxKt0AbkQB6WYioAPAA5VoVACaIAROE1VgMMFp1dsQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=Node-4&version=7.19.3&externalPlugins=&assumptions=%7B%7D

Oops, this doesn't seem to be a bug, strict mode is automatically enabled when the input is a module.

**Comment by usrgnome** [comment]
Caused by strict mode when handling as a module.

**Comment by usrgnome** [comment]
Caused by strict mode when transpiring as a module (not a bug).
