### ISSUE TITLE
[Bug]: `this` is not preserved for super property template tags

### ISSUE THREAD

**Issue by evanw** [babel/babel#15041]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
// This should print "true true true"
async function test() {
  class Foo { foo() { return this } }
  class Bar extends Foo {
    a = async () => super.foo``
    b = async () => super['foo']``
    c = async (foo) => super[foo]``
  }
  const bar = new Bar
  console.log(
    (await bar.a()) === bar,
    (await bar.b()) === bar,
    (await bar.c('foo')) === bar,
  )
}
test()
```

[REPL link](https://babel.dev/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEBUAsEsGdVpA9gVwDYBNQAcBO0A7AF1ACIjcUBTUC62yq0gKAENYBPAgY1ADMUPItCQFaVWEQAUASlABvZqFDc07eADEkSBf22zduKkRS4xRGPAC-oK0pVrY8AEKtcoKgA8iVAhk3aCvbKrKAAvKDsXLwGYQB8CCjYVLgAdHzaAAaZwaAARuGRnDygsQmwSSkA2gDkGUg1ALrZubwRUSVS9XLxicm4VfXNOcp2ytyikvluhQRUAO6grrj2EwSwSGhUqWhIAOZSuVKs86zQJHluqayyPWERl7gANEcnZxdXebfh99PPr6dzn9UtwpHVtDUZHcHm4XsoZMw7D5JLJmEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.19.5&externalPlugins=&assumptions=%7B%7D)

### Configuration

I configured the REPL with `chrome 50`, which lowers async arrow functions.

### Current and expected behavior

The sample code should print `true true true` but currently prints `false false false` when transformed by Babel.

### Environment

- Babel version: v7.19.5

### Possible solution

I'm reporting this because I discovered that esbuild has the same bug. I plan to inject `.bind(this)` to fix this bug in esbuild. This is similar to what Babel already does for private property template tags:

```js
class Foo {
  a = () => this.#b``
  #b() { return this }
}
const foo = new Foo
console.log(foo.a() === foo)
```

[REPL link](https://babel.dev/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1pmgXmgCgEocA-aAFwAsBLCAOgGIAjAA2fWicJWgCcBTMgFceAO3LUYAX1TTg8ERDLQAZohzQRfAO5xEqOQvgg-tEPADmeVfFpgu2BysQEgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.19.5&externalPlugins=&assumptions=%7B%7D)

**Comment by liuxingbaoyu** [comment]
Fixed, thanks!
