### ISSUE TITLE
export default const/let

### ISSUE THREAD

**Issue by kobezzza** [babel/babel#1504]
```js
export default const foo = {
  get() {}
};
```

```
Unexpected token (1:15)
```

But

```js
const foo = {
  get() {}
};

export default foo;
```

All fine.

**Comment by monsanto** [comment]
`export default` takes an expression, not a statement. You can't use `var`, `let`, or `const`

**Comment by rattrayalex** [comment]
Because it confused me, you *can* do: 

```js
export default 3
```
or 
```js
export default {
  get() {}
}
```
etc

**Comment by jaitaiwan** [comment]
Yeah, this is a bit annoying as in react for instance if you define a stateless component and you want it to show with a nice name you had to do

```jsx
const MyComponent = () => (<div>Foo</div>)
export default MyComponent
```

It'd be much nicer to be able to do

```jsx
export default const MyComponent = () => (<div>Foo</div>)
```

If you want to use the second one you of course can't specify `const` so you end up seeing `<StatelessComponent />` all throughout your react code.
