### ISSUE TITLE
[Bug]: regression for module block parse

### ISSUE THREAD

**Issue by fisker** [babel/babel#15051]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```console
> require('@babel/parser').parse('module {/* comment */}', {plugins: ['moduleBlocks']}).program.body[0].expression.body
Node {
  type: 'Program',
  start: 21,   // <---------------------
  end: 8,  // <---------------------
  loc: SourceLocation {
    start: Position { line: 1, column: 21, index: 21 },
    end: Position { line: 1, column: 8, index: 8 },
    filename: undefined,
    identifierName: undefined
  },
  sourceType: 'module',
  interpreter: null,
  body: [],
  directives: [],
  trailingComments: [
    {
      type: 'CommentBlock',
      value: ' comment ',
      start: 8,
      end: 21,
      loc: [SourceLocation]
    }
  ]
}
```

### Configuration

N/A

### Current and expected behavior

Range should be `8 ~ 21`

### Environment

N/A

### Additional context

Possible introduced in #14980 @JLHwung

**Comment by nicolo-ribaudo** [comment]
If anyone has trouble understanding the problem: start and end are swapped.

**Comment by liuxingbaoyu** [comment]
It's weird, escaping our testing and even end-to-end testing.

**Comment by JLHwung** [comment]
In Babel-parser 7.18.0, the program node starts at 21 and ends with 22: 

https://astexplorer.net/#/gist/1b193f48d92b558bcd78e1516bef9c71/5a9bf187ab80c21af33bbbff591361d5f33eb533

After #14980 it starts at 21 but ends at 8, which is worse. The previous situation is not ideal, the Program node should start at comment's start (8) and end at 21, like how we parse a comment-only plain program `/* comment */`.

**Comment by fisker** [comment]
> like how we parse a comment-only plain program /* comment */

But we start at `0` for `<SPACE>/* comment */`, should this module block start for index after `{`?

**Comment by JLHwung** [comment]
> But we start at `0` for `<SPACE>/* comment */`, should this module block `Program` start from index after `{`?

Yes, the module block `Program` should start immediately after `{` and end immediately before the matching `}`. I may have to rewind the tokenizer to the position immediately before `}`.

**Comment by JLHwung** [comment]
@fisker Good question! Per [spec](https://tc39.es/ecma262/#_ref_17061):

> The [InputElementHashbangOrRegExp](https://tc39.es/ecma262/#prod-InputElementHashbangOrRegExp) goal is used at the start of a [Script](https://tc39.es/ecma262/#prod-Script) or [Module](https://tc39.es/ecma262/#prod-Module).

Because module block can only contains optional `ModuleBody`, the hashbang comment is not allowed in the module block. Currently Babel already disallows it but I will check if we have such a test case.

**Comment by fisker** [comment]
Maybe too earily to consider about the estree plugin, but Eslint(Espree)'s `Program` starts from first tokens.
