### ISSUE TITLE
[Bug]: line feeds without comments are being suppressed

### ISSUE THREAD

**Issue by jlowcs** [babel/babel#15064]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

[REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDALAJgNwCgukrAIyVUxwHoyYATCK3caGYY9DIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.19.6&externalPlugins=&assumptions=%7B%7D)

```js
const a = 42;

const b = 42;

// dsd
const c = 42;
```

### Current and expected behavior

Current output:
```js
"use strict";

const a = 42;
const b = 42;

// dsd
const c = 42;
```

Expected output:
```js
"use strict";

const a = 42;

const b = 42;

// dsd
const c = 42;
```

### Environment

- Babel: 7.19.6

### Additional context

This wasn't happening with 7.19.4.

**Comment by jlowcs** [comment]
Kind of. We are using [@svgr/cli](https://www.npmjs.com/package/@svgr/cli) to generate SVG React components, and it uses babel under the hood. So this change is suppressing all double line feeds in the output (which is supposed to still be readable).

**Comment by jlowcs** [comment]
We can probably live without those, it's just not ideal 😅

**Comment by liuxingbaoyu** [comment]
Can you show a before and after file?
I tested some files and it seems to be ok, although some places will not look as good without blank lines, but some unnecessary blank lines have disappeared.

**Comment by jlowcs** [comment]
before:
```ts
/*
 * This file is generated by icons/template.js
 */
import PropTypes from 'prop-types';
import styled from 'styled-components';
import { COMMON, CommonProps } from '../constants';
import theme from '../theme';
import sizeStyle, { IconSizeProps } from '../lib/iconSize';

const SvgComponent = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" role="img" {...props}>
    <path
      d="M255.708 445.235c-10.138 0-19.79-4.48-26.368-12.211L18.19 183.91c-12.34-14.54-10.523-36.352 4.018-48.691 14.567-12.365 36.353-10.573 48.717 3.993l184.808 218.01 185.013-218.01c12.314-14.54 34.176-16.332 48.692-3.993 14.566 12.365 16.358 34.176 3.993 48.717l-211.38 249.088a34.529 34.529 0 0 1-26.343 12.21"
      fill="currentColor"
      fillRule="evenodd"
    />
  </svg>
);

type Props = CommonProps & IconSizeProps;
const SvgBracketDown = styled(SvgComponent)<Props>`
  ${sizeStyle}
  ${COMMON}
`;
SvgBracketDown.defaultProps = {
  theme,
  // override default role set to img on generated icons
  role: 'none',
};
SvgBracketDown.propTypes = {
  ...sizeStyle.propTypes,
  ...COMMON.propTypes,
  theme: PropTypes.object, // eslint-disable-line react/forbid-prop-types
};
SvgBracketDown.displayName = 'IconBracketDown';
export default SvgBracketDown;
```

after:
```ts
/*
 * This file is generated by icons/template.js
 */
import PropTypes from 'prop-types';
import styled from 'styled-components';
import { COMMON, CommonProps } from '../constants';
import theme from '../theme';
import sizeStyle, { IconSizeProps } from '../lib/iconSize';
const SvgComponent = (props: React.SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" role="img" {...props}>
    <path
      d="M255.708 445.235c-10.138 0-19.79-4.48-26.368-12.211L18.19 183.91c-12.34-14.54-10.523-36.352 4.018-48.691 14.567-12.365 36.353-10.573 48.717 3.993l184.808 218.01 185.013-218.01c12.314-14.54 34.176-16.332 48.692-3.993 14.566 12.365 16.358 34.176 3.993 48.717l-211.38 249.088a34.529 34.529 0 0 1-26.343 12.21"
      fill="currentColor"
      fillRule="evenodd"
    />
  </svg>
);
type Props = CommonProps & IconSizeProps;
const SvgBracketDown = styled(SvgComponent)<Props>`
  ${sizeStyle}
  ${COMMON}
`;
SvgBracketDown.defaultProps = {
  theme,
  // override default role set to img on generated icons
  role: 'none',
};
SvgBracketDown.propTypes = {
  ...sizeStyle.propTypes,
  ...COMMON.propTypes,
  theme: PropTypes.object, // eslint-disable-line react/forbid-prop-types
};
SvgBracketDown.displayName = 'IconBracketDown';
export default SvgBracketDown;
```

But tbh those files are a bit of a mess to begin with. Still, if we wanted to make them a bit better and easier to read, we'd still not be able to rely on line feeds.

**Comment by liuxingbaoyu** [comment]
To be honest, it's all good for me.
There are only two blank lines in there, which may not seem like a big difference.

**Comment by JLHwung** [comment]
Babel currently does not preserve whitespaces because the AST does not record such information. You can give `recast` a try.

**Comment by nicolo-ribaudo** [comment]
@dfernandez79 `@babel/generator` will properly respect new lines if you enable the `retainLines: true` option.

**Comment by liuxingbaoyu** [comment]
@dfernandez79 
Previously babel didn't preserve newlines, it just added them forever.
And after that PR, babel doesn't add new lines according to the algorithm.
