### ISSUE TITLE
[Bug]: "core-js-pure/stable/object/define-property" no more exist in core-js-pure  v3.26.0. runtime-corejs3 execution totally fails 

### ISSUE THREAD

**Issue by paztis** [babel/babel#15071]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

no code

### Current and expected behavior

Babel import totally crash

Error: Failed to load plugin 'jsx-a11y' declared in '.eslintrc » eslint-config-digitalexp/ts » ./configs/eslintrc-airbnb.json » eslint-config-airbnb » /jenkins_data/mb_ccprt/workspace/workspace/_ui-l9-Tomer01-Halali-Release0.8/node_modules/eslint-config-airbnb/rules/react-a11y.js': Cannot find module 'core-js-pure/stable/object/define-property'

### Environment

runtime-corejs3 7.19.6

**Comment by nicolo-ribaudo** [comment]
That file exists: https://unpkg.com/browse/core-js@3.26.0/stable/object/define-property.js

**Comment by nicolo-ribaudo** [comment]
That file exists: https://unpkg.com/browse/core-js-pure@3.26.0/stable/object/define-property.js
