### ISSUE TITLE
[Bug]: parse error when I use `transformSync` to transform code with @babel/preset-react

### ISSUE THREAD

**Issue by priority3** [babel/babel#15079]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
const html = `
          <React.Fragment>
				<p>[[toc]]</p>
				<p>a.length > b.length</p>
				<p>a.length < b.length</p>
				<h2>code</h2>
          </React.Fragment>
`

const {code} = transformSync(html, {
        ast: false,
        presets: ['@babel/preset-react'],
        plugins: [],
      })
```

### Configuration

none

### Current and expected behavior

there is the `error` when the `html` contains '<'

![image](https://user-images.githubusercontent.com/75966543/198078348-96ea6033-286d-4a3c-9f6c-963714980d51.png)

### Environment

	"@babel/core": "^7.19.3",
    "@babel/preset-react": "^7.18.6",

### Additional context

if
```js
const html = `
	<React.Fragment>
			<p>[[toc]]</p>
			<p>a.length > b.length</p>
			
			<h2>code</h2>
        </React.Fragment>
`
```
they will work well

**Comment by nicolo-ribaudo** [comment]
The `<` character is disallowed in JSX text, because it conflicts with JSX tag. You can use this instead:
```js
const html = `
          <React.Fragment>
				<p>[[toc]]</p>
				<p>a.length &gt; b.length</p>
				<p>a.length &lt; b.length</p>
				<h2>code</h2>
          </React.Fragment>
`
```

or this:
```js
const html = `
          <React.Fragment>
				<p>[[toc]]</p>
				<p>a.length {">"} b.length</p>
				<p>a.length {"<"} b.length</p>
				<h2>code</h2>
          </React.Fragment>
`
```

**Comment by nicolo-ribaudo** [comment]
Btw, that error is thrown by vite and not by Babel.

**Comment by priority3** [comment]
> Btw, that error is thrown by vite and not by Babel.

oh, thx so mush, I got it,😁
