### ISSUE TITLE
[Bug]: Optional chaining operator is not transpiled

### ISSUE THREAD

**Issue by janschoenherr** [babel/babel#15072]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

```js 
const test = null;
test?.foo();
```

https://babel.dev/repl#?browsers=safari%2012&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBFCm0YF4ZgK4BtMG4BQC0A_AHQBmIIAFAJQ5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.19.6&externalPlugins=&assumptions=%7B%7D

### Configuration

```js
{
    presets: [
        [
            '@babel/preset-env',
            {
                loose: true,
                targets: {
                    safari: '12',
                },
            },
        ],
    ],
    extensions: ['.js'],
    babelHelpers: 'bundled',
    retainLines: true,
}
```

### Current and expected behavior

When upgrading @babel/preset-env from version 7.19.3 to 7.19.4, the optional chaining operator is no longer transpiled.

It works in the above REPL, I don't know what version of @babel/preset-env is used there.

### Environment

  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.19.6 => 7.19.6 
    @babel/preset-env: ^7.19.4 => 7.19.4 
    eslint: ^8.26.0 => 8.26.0

**Comment by liuxingbaoyu** [comment]
Can you provide a repository to reproduce?

**Comment by liuxingbaoyu** [comment]
I tried removing `yarn.lock` and updating to yarn3 both fixed the issue, which is weird.😕

**Comment by janschoenherr** [comment]
I am sorry for wasting your time. It seems to work for me too now. I am not sure what changed for it to work now.

**Comment by liuxingbaoyu** [comment]
No, it's not a waste of time, I can reproduce this.
This may also be related to babel, but I guess it's not bad to solve it the way it is now.😃

**Comment by liuxingbaoyu** [comment]
I'm guessing it might have something to do with yarn1, everything worked fine after I removed `node_modules` and re-run `yarn`.

**Comment by janschoenherr** [comment]
Okay, I reproduced the steps from this morning.

I upgrade a bunch of dependencies using `yarn upgrade-interactive --latest`

Now the lock file seems to have a bunch of older dependencies.

`"@babel/generator@^7.18.10"`
`"@babel/helper-environment-visitor@^7.18.6"`
`"@babel/helper-function-name@^7.18.6"`
... many more

After running `yarn upgrade @babel/preset-env` those dependencies get updated in the yarn.lock file and everything seems to be working again. 

Thanks, this seems to be an issue with yarn1.

**Comment by vishnumanikantan** [comment]
> Okay, I reproduced the steps from this morning.
> 
> I upgrade a bunch of dependencies using `yarn upgrade-interactive --latest`
> 
> Now the lock file seems to have a bunch of older dependencies.
> 
> `"@babel/generator@^7.18.10"` `"@babel/helper-environment-visitor@^7.18.6"` `"@babel/helper-function-name@^7.18.6"` ... many more
> 
> After running `yarn upgrade @babel/preset-env` those dependencies get updated in the yarn.lock file and everything seems to be working again.
> 
> Thanks, this seems to be an issue with yarn1.

For me this command fixed the issue npm upgrade @babel/preset-env . Thank you @janschoenherr
