### ISSUE TITLE
[Bug]:  isTSSatisfiesExpression is not a function some babel lib issue

### ISSUE THREAD

**Issue by lzxue** [babel/babel#15089]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

node code

### Current and expected behavior

isTSSatisfiesExpression is not a function

### Environment

 System:
    OS: macOS 12.6
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.11
    Lerna: 3.22.1
  npmPackages:
    @babel/cli: ^7.6.4 => 7.19.3 
    @babel/core: ^7.18.10 => 7.19.6 
    @babel/eslint-parser: ^7.18.9 => 7.19.1 
    @babel/plugin-proposal-decorators: ^7.6.0 => 7.20.0 
    @babel/plugin-proposal-nullish-coalescing-operator: ^7.4.4 => 7.18.6 
    @babel/plugin-proposal-object-rest-spread: ^7.7.4 => 7.19.4 
    @babel/plugin-proposal-optional-chaining: ^7.6.0 => 7.18.9 
    @babel/plugin-syntax-async-generators: ^7.7.4 => 7.8.4 
    @babel/plugin-transform-parameters: ^7.8.4 => 7.18.8 
    @babel/plugin-transform-runtime: ^7.7.6 => 7.19.6 
    @babel/preset-env: ^7.5.5 => 7.19.4 
    @babel/preset-react: ^7.0.0 => 7.18.6 
    @babel/preset-typescript: ^7.3.3 => 7.18.6 
    @babel/standalone: ^7.13.15 => 7.20.0 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-loader: ^8.0.6 => 8.2.5 
    babel-plugin-const-enum: ^0.0.2 => 0.0.2 
    babel-plugin-css-modules-transform: ^1.6.2 => 1.6.2 
    babel-plugin-inline-import: ^3.0.0 => 3.0.0 
    babel-plugin-inline-webgl-constants: ^1.0.1 => 1.0.3 
    babel-plugin-lodash: ^3.3.4 => 3.3.4 
    babel-plugin-transform-import-css-l7: ^0.0.6 => 0.0.6 
    babel-plugin-transform-import-styles: ^0.0.11 => 0.0.11 
    babel-plugin-transform-inline-environment-variables: ^0.4.3 => 0.4.4 
    babel-plugin-transform-node-env-inline: ^0.4.3 => 0.4.3 
    babel-plugin-transform-postcss: ^0.3.0 => 0.3.0 
    babel-polyfill: ^6.26.0 => 6.26.0 
    babel-preset-gatsby: ^1.12.0 => 1.14.0 
    babel-template: ^6.26.0 => 6.26.0 
    babel-types: ^6.26.0 => 6.26.0 
    eslint: ^7.32.0 => 7.32.0 
    jest: ^24.9.0 => 24.9.0 
    lerna: ^3.16.4 => 3.22.1 
    rollup-plugin-babel: ^4.3.3 => 4.4.0 
    webpack: ^4.17.1 => 4.46.0

**Comment by Lokya** [comment]
@liuxingbaoyu @lzxue 
I encountered the same problem but I solved it through upgraded @babel/types version (old version 7.17.10 -> new version 7.20.0).
Thanks very much @liuxingbaoyu , you tips help me.
I hope it can help you @lzxue .

**Comment by liuxingbaoyu** [comment]
Glad this helped!
This is a bit strange, because I checked all uses of `isTSSatisfiesExpression`, declared a dependency on `@babel/types: ^7.20.0`.😕

**Comment by nicolo-ribaudo** [comment]
If it happens to someone else, please share a stack trace!

**Comment by Lokya** [comment]
this is my old dependencies
"@babel/types": "7.17.10",
"@babel/cli": "7.17.6",
"@babel/core": "7.17.5",
"@babel/helper-hoist-variables": "7.16.7",
"@babel/helper-optimise-call-expression": "7.16.7",
"@babel/preset-env": "7.17.10",
"@babel/preset-react": "7.16.7",

error message:
    'compile-with-rc-lib' errored after 35 s
    TypeError in plugin "gulp-babel"
    xxxx.jsx: isTSSatisfiesExpression is not a function

update @babel/types version (7.20.0), build success. 
---------------------------------------
Hope my info is useful .

**Comment by lzxue** [comment]
by lock some babel libs to low version fix this error

https://github.com/antvis/L7/pull/1451/files

**Comment by liuxingbaoyu** [comment]
@lzxue No need to lock all dependencies to older versions, just lock `@babel/types` to `^7.20.0`.

**Comment by liuxingbaoyu** [comment]
```
Error: [BABEL] /home/liuxingbaoyu/L7/packages/three/src/index.ts: You gave us a visitor for the node type TSSatisfiesExpression but it's not a valid type
    at verify (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:110950:13)
    at Function.explode (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:110872:3)
    at /home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:30928:42
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:32690:3)
    at Generator.next (<anonymous>)
    at step (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:9559:32)
    at evaluateAsync (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:9589:5)
    at Function.errback (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:9411:7)
    at errback (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/babel/index.js:32745:18)

webpack compiled with 1 error
    at /home/liuxingbaoyu/L7/node_modules/father/node_modules/@umijs/bundler-webpack/dist/build.js:81:18
    at finalCallback (/home/liuxingbaoyu/L7/node_modules/father/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61758:32)
    at /home/liuxingbaoyu/L7/node_modules/father/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61775:13
    at Hook.eval [as callAsync] (eval at create (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:33:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4913)
    at onCompiled (/home/liuxingbaoyu/L7/node_modules/father/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61773:21)
    at /home/liuxingbaoyu/L7/node_modules/father/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62513:17
    at Hook.eval [as callAsync] (eval at create (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/liuxingbaoyu/L7/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4913)
    at /home/liuxingbaoyu/L7/node_modules/father/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62509:33
```
I tried https://github.com/antvis/L7 and the reason is `umijs` bundled `@babel/types`.
https://github.com/umijs/umi/blob/master/packages/bundler-utils/bundles/babel/bundle.js

**Comment by liuxingbaoyu** [comment]
https://stackoverflow.com/questions/74230711/build-failed-because-of-webpack-errors/74236587#74236587

next does the same thing, I'll try to open an issue or pr in the next repository later.

**Comment by trevorallred** [comment]
I'm using Expo with babel and seeing this error: `Expo.fx.js: isTSSatisfiesExpression is not a function`. I downgraded from 7.20 to 7.19 and it's working now.
Before:
```
  "dependencies": {
    "@babel/preset-env": "^7.20.2",
    "expo": "^47.0.0",
    ....
  },
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@babel/types": "^7.20.2",
    ....
  },
```

**Comment by ashishtilara** [comment]
I just had to delete `node_modules` and reinstall all dependencies. Issue I believe was due to change in node versions. In case if this helps anyone.
