### ISSUE TITLE
Arrow function causing `this` to be `undefined`

### ISSUE THREAD

**Issue by gordonkristan** [babel/babel#1508]
We have the following code in our codebase:

```js
$(React.findDOMNode(this.refs.drawerContent)).on($.support.transition.end, () => {
        console.log('HERE');
});
```

But Babel transpiles it to this:

```js
$(React.findDOMNode(undefined.refs.drawerContent)).on($.support.transition.end, function () {
        console.log('HERE');
});
```

Notice that `this.refs.drawerContent` inside the `findDOMNode` method call was transpiled to `undefined.refs.drawerContent`. (It actually gets transpiled to a different this value in our code, but that's what the REPL will produce if you paste only that snippet.) It seems like maybe Babel is getting tripped up on the scope?

**Comment by loganfsmyth** [comment]
That is the expected behavior. `this` in top-level module scope is `undefined` in ES6.

So that explains what you saw in the REPL. If that isn't also the issue in your production code, please post more code.

**Comment by gordonkristan** [comment]
Ahh, I see what you mean. I didn't know that it would replace `this` with `undefined` at the top level. (A little odd, but I see the reasoning.) In other words, I got a false negative on a bug in our code. There's still an issue with the arrow function in that code, but it could be on our end. I'll close this until we can confirm there is an issue with Babel (if there is one).

Sorry about the confusion.
