### ISSUE TITLE
destructing bug with object literals

### ISSUE THREAD

**Issue by joeybaker** [babel/babel#1509]
problem: https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=const%20a%20%3D%20%7Bb%3A%20%7Bc%3A%20Function()%7D%7D%0Aconst%20%7Bc%7D%20%3D%20a.b%0Aconst%20d%20%3D%20%7B%0A%20%20c%20()%20%7B%0A%20%20%20%20console.log(typeof%20c)%20%2F%2F%20should%20be%20function%2C%20is%20undefined%0A%20%20%7D%0A%7D

Input code
```js
const a = {b: {c: Function()}}
const {c} = a.b
const d = {
  c () {
    console.log(typeof c) // should be function, is undefined
  }
}
```

yields:
```js
"use strict";

var a = { b: { c: Function() } };
var _c = a.b._c; // this should be `c`, not `_c`

var d = {
  c: function c() {
    console.log(typeof _c);
  }
};
// should be function, is undefined
```

**Comment by sebmck** [comment]
Duplicate of #1458.

**Comment by joeybaker** [comment]
Ah! Thanks! Sorry for the dupe.
