### ISSUE TITLE
[Bug]: Library has syntax error

### ISSUE THREAD

**Issue by Veragin** [babel/babel#15108]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
_generateUid(name, i) {
    let id = name;
    if (i > 1) id += i;
    return `_${id}`;
//  }
//
//  generateUidBasedOnNode(node, defaultName) {
    const parts = [];
    gatherNodeParts(node, parts);
    let id = parts.join("$");
    id = id.replace(/^_/, "") || defaultName || "ref";
    return this.generateUid(id.slice(0, 20));
  }
```

### Current and expected behavior

This problem occur in your version 7.19.6 and also in 7.20, you have here probably by mistake commented 3 lines of code, that cause syntax error. Removing these // will fix the lib

How to reproduce:
Install @babel/traverse via yarn 2
look at file node_modules/@babel/traverse/lib/scope/index.js at lines 426-428

### Environment

System:
  OS: macOS 12.6
 Binaries:
  Node: 18.11.0 - /usr/local/bin/node
  Yarn: 3.2.4 - /usr/local/bin/yarn
  npm: 8.19.2 - /usr/local/bin/npm
 npmPackages:
  @babel/core: ^7.12.9 => 7.19.6
  @babel/plugin-proposal-decorators: ^7.10.5 => 7.20.0
  @babel/runtime: ^7.12.5 => 7.20.0
  babel-jest: ^26.6.3 => 26.6.3
  babel-plugin-module-resolver: ^4.0.0 => 4.1.0
  eslint: 7.32.0 => 7.32.0
  jest: ^26.6.3 => 26.6.3
  metro-react-native-babel-preset: 0.72.3 => 0.72.3
  react-native: 0.70.3 => 0.70.3

**Comment by liuxingbaoyu** [comment]
https://unpkg.com/browse/@babel/traverse@7.20.0/lib/scope/index.js
![image](https://user-images.githubusercontent.com/30521560/199205166-4eba2fe3-9669-4473-a5e9-d8c5b8ddf89b.png)

**Comment by Veragin** [comment]
i am getting this problem repeatedly (delete node_models + .lock and reinstall), but you are right, when i created pure project and install only babel/traverse everything seems to be fine ... i will try to investigate it more deeply, but probably it is not issue of your library

**Comment by Veragin** [comment]
you are right!!! thank you very much ...
