### ISSUE TITLE
[Bug]: VistorKeys missing `Program.interpreter`

### ISSUE THREAD

**Issue by fisker** [babel/babel#15116]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```console
> require('@babel/types').VISITOR_KEYS.Program
[ 'directives', 'body' ]
```

### Current and expected behavior

"interpreter" is an optional node in `Program`

### Environment

`@babel/types@7.20.0`

### Additional context

https://github.com/prettier/prettier/blob/bf6cf1c96c9f5ae48b6b5eb94367af5ef32f35de/src/language-js/traverse/visitor-keys.evaluate.js#L24-L25

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/blob/53185ea275b0a278ac4aafe5841f2a332cabff31/packages/babel-types/src/definitions/core.ts#L726-L729
I found this and it seems intentional.

**Comment by fisker** [comment]
We can close then. Thank you!
