### ISSUE TITLE
[Bug]: Regression. Babel generates invalid code.

### ISSUE THREAD

**Issue by andy128k** [babel/babel#15111]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
import { apiLogout } from "../api";
import { reportError } from "../libs/report_error";

export function logout() {
  return reportError(async (/*dispatch*/) => {
    await apiLogout();
    window.location.reload();
  });
}
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function(api) {
  const isTest = api.env('test');

  const envOptions = isTest
    ? {
      "targets": {
        "node": "current"
      }
    }
    : {
      modules: false,
      useBuiltIns: 'usage',
      corejs: "3.25",
      // debug: true,
    };

  return {
    "presets": [
      ["@babel/preset-env", envOptions],
      "@babel/preset-react"
    ],
  };
};
```

### Current and expected behavior

After an upgrade from `7.19.3` to `7.19.6` I've got a following failure.

```
ERROR in ./assets/actions/user.js 12:5
Module parse failed: Unexpected token (12:5)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export function logout() {
|   return reportError(async /*dispatch*/
>   () => {
|     await apiLogout();
|     window.location.reload();
 @ ./assets/actions/index.js 2:0-37 12:13-24
 @ ./assets/app.js 6:0-37 12:15-23
```

Babel inserts a new line and breaks async closure (I guess, auto-insertion of semicolon is involved).

The same error is reproducible in an online playground with other versions: [7.17.12 generates correct code](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgQzMAMhA5hArvAXzgDMoIQ4AiAOmoHpVhKBuAKFElkTigFNOYAUShkocIqXJVadADbAARgGc6fAQH1eI6C1ateADwElcAOwDGMYBFNxZ2PDAAUASkSs4PXjFxRba6CFtKCdkJQBPCzgnOgAqABNgJTBkGHMAC1i6NwBeAD53T09kAHdkYHhGTBx8VzYiuBLgU3iIEup7c1TrU2o-e2R4uo9xFzYCViA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.17.12&externalPlugins=&assumptions=%7B%7D) while [7.20.1 generates invalid code](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgQzMAMhA5hArvAXzgDMoIQ4AiAOmoHpVhKBuAKFElkTigFNOYAUShkocIqXJVadADbAARgGc6fAQH1eI6C1ateADwElcAOwDGMYBFNxZ2PDAAUASkSs4PXjFxRba6CFtKCdkJQBPCzgnOgAqABNgJTBkGHMAC1i6NwBeAD53T09kAHdkYHhGTBx8VzYiuBLgU3iIEup7c1TrU2o-e2R4uo9xFzYCViA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

#### Environment w/o the issue

  System:
    OS: Linux 6.0 Debian GNU/Linux bookworm/sid
  Binaries:
    Node: 14.20.0 - ~/apps/nodejs/bin/node
    Yarn: 1.22.19 - ~/apps/nodejs/bin/yarn
    npm: 6.14.17 - ~/apps/nodejs/bin/npm
  npmPackages:
    @babel/core: ^7 => 7.19.3 
    @babel/eslint-parser: ^7 => 7.19.1 
    @babel/preset-env: ^7 => 7.19.3 
    @babel/preset-react: ^7 => 7.18.6 
    babel-jest: ^29 => 29.1.2 
    babel-loader: ^8.0.0 => 8.2.5 
    eslint: ^8.2 => 8.24.0 
    jest: ^29 => 29.1.2 
    webpack: ^5 => 5.74.0 

#### Environment with the issue (after `yarn upgrade`)

  System:
    OS: Linux 6.0 Debian GNU/Linux bookworm/sid
  Binaries:
    Node: 14.20.0 - ~/apps/nodejs/bin/node
    Yarn: 1.22.19 - ~/apps/nodejs/bin/yarn
    npm: 6.14.17 - ~/apps/nodejs/bin/npm
  npmPackages:
    @babel/core: ^7 => 7.19.6 
    @babel/eslint-parser: ^7 => 7.19.1 
    @babel/preset-env: ^7 => 7.19.4 
    @babel/preset-react: ^7 => 7.18.6 
    babel-jest: ^29 => 29.2.2 
    babel-loader: ^8.0.0 => 8.2.5 
    eslint: ^8.2 => 8.26.0 
    jest: ^29 => 29.2.2 
    webpack: ^5 => 5.74.0

**Comment by nicolo-ribaudo** [comment]
Introduced by https://github.com/babel/babel/pull/15080, I'll work on a fix.

**Comment by arredgroup** [comment]
Hi! I have the same issue :(

**Comment by liuxingbaoyu** [comment]
@arredgroup Hi, have you tried the latest version?
