### ISSUE TITLE
[Bug]: comments in async function are not handled correctly by generator 

### ISSUE THREAD

**Issue by zxbodya** [babel/babel#15126]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
const fn = async () /* test */ => {
};
```

### Current and expected behavior

using `@babel/generator` version 7.20.0 and newer results in error

last working version is `7.19.6`

### Environment

- `@babel/generator@7.20.0`

### Additional context

also fails in [babel repl](https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011%2C%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeGBDCBPMwYAoCUMA9AFQxQCm0MJRyAfDAN4BQAvgNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=true&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/babel/babel/pull/15118 and will be released soon.
Thanks for your report!
