### ISSUE TITLE
I don't understand why this class property is undefined

### ISSUE THREAD

**Issue by chrisabrams** [babel/babel#1512]
When I run my code, I get the following error:

    this.generateBinFile(appName, cwd);
           ^
    TypeError: Object [object Object] has no method 'generateBinFile'    

Here is the file that is calling it - why would my class not see the method?
https://github.com/chrisabrams/brazier/blob/125600d10e3ce97a759526c671f12c05348e2e7e/bin/controllers/init.js#L37

**Comment by sebmck** [comment]
See the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Your problem is probably the `new` on [this](https://github.com/chrisabrams/brazier/blob/2dca91b4453fac8bf1b7a52831e062ac1298851c/src/dispatcher.js#L22), remove it and it'll *probably* work.

**Comment by chrisabrams** [comment]
Thanks @sebmck you were correct; looks like I have more to learn. And thanks for pointing out the gitter room, I'll try that in the future.
