### ISSUE TITLE
[Bug]: Getter should be shadowed by shorthand property

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15140]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
// Here, both x's before and after the getter are required to trigger the bug.
var x = { x , get x ( ) { return 0; } , x } ;
x.x = 1;
console.log(x.x);
```

### Current and expected behavior

`x`'s property `x.x` should be writable in the input code but it is not in the transpiled code.

### Current behavior

`x.x` is not writable:
```console
$ node output.js
0
```
### Expected behavior

`x.x` is writable:
```console
$ node input.js
1 // x.x became 1
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=since%202015&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBAHhC8EG9oQDQQOYFMAuyAUEAlIhGDgK5gB2EADANwQC-qyL9AUFAHQzwCMnAMYB7KgGcRAG0zcpI9Hh5RC9IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

**Comment by SuperSodaSea** [comment]
Currently Babel transform `var x = { x, get x() { return 0; }, x }` into this:
```js
var x =
  ((_x = {
    x: x
  }),
  (_x2 = "x"),
  (_mutatorMap = {}),
  (_mutatorMap[_x2] = _mutatorMap[_x2] || {}),
  (_mutatorMap[_x2].get = function () {
    return 0;
  }),
  _defineProperty(_x, "x", x),
  _defineEnumerableProperties(_x, _mutatorMap),
  _x);
```
The getter is setted by `_defineEnumerableProperties` at the end, overwriting previous `_defineProperty(_x, "x", x)`, which should be set at last in a correct transform.

Maybe we should transform it into this?
```js
// Other helper functions...
function _defineGetter(obj, key, get) {
  Object.defineProperty(obj, key, {
    get: get,
    enumerable: true,
    configurable: true
  });
  return obj;
}
// Add a _defineSetter if setter is used
var x =
  ((_x = {
    x: x
  }),
  _defineGetter(_x, "x", function () {
    return 0;
  }),
  _defineProperty(_x, "x", x),
  _x);
x.x = 1;
console.log(x.x);
```

**Comment by nicolo-ribaudo** [comment]
This can be reproduced using this code:
```js
var a = {
  get ["x"]() {
    return 0;
  },
  ["x"]: 1
};
```
and with only `@babel/plugin-transform-computed-properties`.

Using `_defineGetter` instead of that `mutuatorMap` sounds good, or we could even have a single helper:
```js
function _defineAccessor(type, obj, key, fn) {
  return Object.defineProperty(
    obj,
    key,
    _defineProperty({ enumerable: true, configurable: true }, type, fn)
  );
}
```
