### ISSUE TITLE
[Bug]: Super call in arrow function causing infinite recursion

### ISSUE THREAD

**Issue by SuperSodaSea** [babel/babel#15148]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
class Bar extends Foo {
    constructor() {
        let f = (...args) => super(...args);
        f();
    }
}
```

[Example on Babel REPL](https://babeljs.io/repl/#?browsers=since%202017&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEBCYCdoFMAeAXZA7AJjAYgPaHQDeAUNFdMIVhOggK7DqEIAUAlGZdfyGTpoAM2gBeaBwB0sxAHMIPcQD5oEJgAdknWdIVKA3H35UR3Y_wC-5G0A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.20.2&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [["@babel/preset-env", { "bugfixes": true }]],
    "targets": ["since 2017"]
}
```

##### Current behavior (silently success and causing infinite recursion)
```js
"use strict";

class Bar extends Foo {
  constructor() {
    var _supercall = function _supercall() {
      return _supercall(...arguments);
    };
    let f = function f() {
      return _supercall(...arguments);
    };
    f();
  }
}
```

##### Expected behavior
- Give ~~warning or~~ error in this situation;
- ~~Or just keep the arrow function;~~
- ~~Or transpile the whole class into pre-ES6 style (just like the result of using [`since 2016`](https://babeljs.io/repl/#?browsers=since%202016&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEBCYCdoFMAeAXZA7AJjAYgPaHQDeAUNFdMIVhOggK7DqEIAUAlGZdfyGTpoAM2gBeaBwB0sxAHMIPcQD5oEJgAdknWdIVKA3H35UR3Y_wC-5G0A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.20.2&externalPlugins=&assumptions=%7B%7D)).~~

### Environment

- Babel version: v7.20.2
- Node: v16.17.0
- pnpm version: pnpm 7.14.2
- OS: Windows 10
- Monorepo: no

**Comment by SuperSodaSea** [comment]
Since it looks impossible to transpile this code into a ES6 class without arrow function, I wondered which one would be the best solution.

**Comment by SuperSodaSea** [comment]
Seems that `@babel/plugin-transform-spread` will throw error in a similar situation, so I'd like to add a check and throw in `@babel/plugin-transform-parameters`. I will make a PR later.

https://github.com/babel/babel/blob/156b608d48900b9489bd31aff03189a6c18f9040/packages/babel-plugin-transform-spread/src/index.ts#L140-L146

**Comment by nicolo-ribaudo** [comment]
Thanks for the investigation @SuperSodaSea; an error with a similar message looks fine to me!
