### ISSUE TITLE
Exported functions get an implicit module context

### ISSUE THREAD

**Issue by gaearon** [babel/babel#1514]
This just tripped me but I'm not sure if it's intended behavior. Feel free to close if it's not an issue.

Basically I re-export a few functions in my lib's `index.js`:

```js
export { default as DragDropContext } from './DragDropContext';
export { default as DragLayer } from './DragLayer';
export { default as DragSource } from './DragSource';
export { default as DropTarget } from './DropTarget';
```

In my app, I import them:

```js
import { DragLayer } from 'react-dnd';
```

I just realized that this assigns them implicit context of `index.js`'s `exports` object because when I use them later, they are invoked “on it”:

```js
export default DragLayer(...)
```

becomes

```js
exports['default']) = _reactDnd.DragLayer(...)
```

and thus `this` inside `DragLayer` points to `exports` in `index.js`.

How do I solve this?

**Comment by sebmck** [comment]
Expected behaviour. It's necessary for live bindings.

**Comment by gaearon** [comment]
I see. Worth adding to caveats or something?

**Comment by sebmck** [comment]
Also duplicate of #1420, #1341, #1337.

@gaearon Most likely, it's come up often enough.

**Comment by fkling** [comment]
@gaearon, out of curiosity, what would you expect `this` to refer to, or how is this an issue in actual code?  As far as I can see, `this` should be `undefined` (because normal function call + module code), and with that in mind, there is no reason to access `this` anyway? Am I missing something?

**Comment by sebmck** [comment]
Actually. Function calls to module imports could be optimised to be
sequence expressions so they aren't method calls so they won't have a
context which negates this issue and results in faster code.

On Wednesday, 13 May 2015, Felix Kling <notifications@github.com> wrote:

> @gaearon <https://github.com/gaearon>, out of curiosity, what would you
> expect this to refer to, or how is this an issue in actual code? As far
> as I can see, this should be undefined (because normal function call +
> module code), and with that in mind, there is no reason to access this
> anyway? Am I missing something?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1514#issuecomment-101478353>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
Just released 5.3.1 where instead of:

```javascript
import foo from "foo";
foo();
```

turning into:

```javascript
"use strict";
var _foo = require("foo");
var _foo2 = _interopRequireDefault(_foo);
_foo2["default"]();
```

it now turns into:

```javascript
"use strict";
var _foo = require("foo");
var _foo2 = _interopRequireDefault(_foo);
(0, _foo2["default"])();
```

**Comment by gaearon** [comment]
@fkling Yes, I'd expect it to be `undefined`. I was trying to guard against calling my functions with `new` which was a symptom of misuse. (Although I later realized I should've guarded inner functions, but anyway.)

@sebmck Man I didn't realize this was valid JavaScript at first! Great job :+1:

**Comment by fkling** [comment]
@gaearon: Ah, that makes sense. A possible workaround could have been to test whether `this` is an instance of `DragLayer` (i.e. just test the other direction).

**Comment by gaearon** [comment]
Right, I haven't thought of that.

**Comment by guillaume86** [comment]
This issue also breaks the "isomorphic-fetch" module when used in chrome because the native function is not binded.

Couldn't that be solved (and still preserve live bindings) by transforming direct calls to module members into something like

    (unbound = _module['default'])(args)

I have no idea about the performande implications but it would fix the function call context issue.

**Comment by eventualbuddha** [comment]
@guillaume86 can you give a specific, reproducible example showing what you expect and what is actually happening?

**Comment by guillaume86** [comment]
It is exactly the same issue as the one originaly reported here:

    import fetch from 'isomorphic-fetch';
    fetch('http://google.com');

get transpiled to:

    'use strict';
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
    var _isomorphicFetch = require('isomorphic-fetch');
    var _isomorphicFetch2 = _interopRequireDefault(_isomorphicFetch);
    (0, _isomorphicFetch2['default'])('http://google.com');

which breaks in chrome with an IllegalInvocationExcption because `this` is implicitly changed.

My suggestion to fix this is to transpile to:

    'use strict';
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
    var _isomorphicFetch = require('isomorphic-fetch');
    var _isomorphicFetch2 = _interopRequireDefault(_isomorphicFetch);
    var _unboundCall = null;
    (0, (unboundCall = _isomorphicFetch2['default']))('http://google.com');

**Comment by eventualbuddha** [comment]
@guillaume86 I tried to reproduce the `IllegalInvocationException` with the code below in Chrome, but it worked as expected and logged `undefined`:

```js
(function() { 'use strict'; var a = { b() { console.log(this); } }; (0, a.b)(); })()
```

What is actually causing the exception?

**Comment by guillaume86** [comment]
You can do this to reproduce the fetch issue:

    var x = { fetch: fetch };
    x.fetch('whatever');

but this is just another symptom of the real issue reported by @gaearon

**Comment by sebmck** [comment]
@guillaume86 

> `this` is implicitly set to the module object.

No it's not? The sequence expression of `(0, _isomorphicFetch2['default'])('http://google.com');` clears the receiver.

**Comment by guillaume86** [comment]
@sebmck Oups I beg my pardon, I used the online babel translator to get a short snippet and it must have different version/settings than my real project, I'll check my version...

**Comment by sebmck** [comment]
@guillaume86 The REPL is always on the latest Babel version. (They're guaranteed to be now that Travis pushes to the website on each new version)

**Comment by guillaume86** [comment]
Sorry again, I should have checked the code I was posting, thanks for the
fast responses.

2015-07-07 23:02 GMT+02:00 Sebastian McKenzie <notifications@github.com>:
