### ISSUE TITLE
[Bug] `let` to `var` allows forward reference (use in definition)

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15150]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
let x = x;
```

### Current and expected behavior

Changing let to var incurs hoisting so it changes an erroneous code into normal:
```console
$ node input.js
input.js:1
let x = x;
        ^

ReferenceError: Cannot access 'x' before initialization
    at Object.<anonymous> (input.js:1:9)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```
```console
$ node output.js # no error
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=since%202015&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DYUwLgBAHhC80G4g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.20.2&externalPlugins=&assumptions=%7B%7D)

**Comment by nicolo-ribaudo** [comment]
We don't enable TDZ checks by default, because they increase the code size by a lot and usually they are not needed.

However, if you enable the `tdz` optinon of the `transform-block-scoping` plugin you'll get the error:
```js
const code = `
let x = x;
`;

const out = babel.transformSync(code, {
  configFile: false,
  sourceType: "module",
  plugins: [
    [require("./packages/babel-plugin-transform-block-scoping"), { tdz: true }],
  ],
});

console.log(out.code);
```
output:
```js
function _tdz(name) { throw new ReferenceError(name + " is not defined - temporal dead zone"); }
var x = _tdz("x");
```

**Comment by p51lee** [comment]
Thank you for your response!
I've tried `tdz` option and it solved most issues.

However, I found two cases that `tdz` option doesn't work as expected

1. `for ( let x in x );`; it is still compiled to `for ( var x in x );` even if `tdz` option is enabled.
2. `y++; let y;` is compiled to `_tdz(y)++; var y;`, which results in `SyntaxError`. According to the ECMAScript specification, function call can't be used as left-hand side expression so it throws an unexpected`SyntaxError` as an early error instead of `ReferenceError`. (By the way, there is a bug in NodeJS regarding early error. It incorrectly handles the case where the function call is used as left-hand side, so it throws `ReferenceError` when running `_tdz(y)++; var y;`, instead of `SyntaxError`. You may want to use other JavaScript engine to reproduce the error.)

**Comment by nicolo-ribaudo** [comment]
Thank you for the investigation! The tdz option needs a bit of care; I have started working on it so expect improvements in the next weeks :)

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/pull/15164 fixes the `_tdz("y")++` bug.
