### ISSUE TITLE
[Bug]: Destructuring empty array with invalid Symbol.iterator

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15154]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
var [ ] = { [ Symbol . iterator ] : ( ) => [ ] } ;
```

### Current and expected behavior

In `input.js`, `Symbol.iterator` is lazily evaluated so `input.js` is terminated without error.
On the other hand, `Array.from(iter)` in `output.js` eagerly throws `TypeError`:
```console
$ node input.js # no error

$ node output.js
output.js:48
    return Array.from(iter);
                 ^

TypeError: undefined is not a function
    at Function.from (<anonymous>)
    at _iterableToArray (output.js:48:18)
    at _toArray (output.js:17:5)
    at Object.<anonymous> (output.js:56:23)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBA2hC6EF4IG9oQMoE8C2AjA9gDYQB0EAlgC4CmYIl-k8AXBABQQCUiAfGvAF8IAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.20.2&externalPlugins=&assumptions=%7B%7D)

**Comment by SuperSodaSea** [comment]
I believe #15183 also fixes this problem. Empty array destructuring should only check the result of `[Symbol.iterator]()` is an object, and not calling its `next()` (but will call its `return()` if exist).
