### ISSUE TITLE
[Bug]: Empty array destructuring with async generator function results in infinite loop

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15168]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
[ ] = { [ Symbol . iterator ] : async function * ( ) { } } ;
```

### Current and expected behavior

The input code terminates immediately but the output code never terminates.
```console
$ node input.js # terminates with no error
```
```console
$ node output.js # never terminates
^C
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=NoAguiC8IN4qBlAngWwEYHsA2IB0IBLAFwFMAnAQyIzPBAC4QKBnJAOwGMQAzAV06IEMbEACoQAChABKWCAC-CkAG4AUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.19.2&externalPlugins=&assumptions=%7B%7D)

**Comment by nicolo-ribaudo** [comment]
@SuperSodaSea Without introducing a new helper, it might be enough to emit `_slicedToArray(_arr, 0)` (like we do for non-empty array destructuring)

**Comment by SuperSodaSea** [comment]
@nicolo-ribaudo Seems that `_iterableToArrayLimit(arr, i)` doesn't handle `i === 0` well (`next()` should not be called). Trying to fix it...
