### ISSUE TITLE
[Bug]: Babel Displays no errors and can't parse huge files

### ISSUE THREAD

**Issue by Brandon-T** [babel/babel#15162]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

The following code changes all `FunctionDeclaration` from:
```js
function foo() {
}
```
to:
```js
function foo() {
}
$(foo);
```

The code:
```js
function createVisitor(babel) {
    const Types = babel.types;
    
    let visitor = {
        FunctionDeclaration: {
            enter: function(path) {
                path.insertAfter(
                    Types.callExpression(
                        Types.identifier("$"), 
                        [path.node.id]
                    )
                )

                // path.replaceWithMultiple(
                //     [path.node,
                //     Types.callExpression(
                //         Types.identifier("$"),
                //         [path.node.id]
                //     )]
                // )
            }
        }
    }
    return visitor;
}

module.exports = function(babel) {
    return {
        name: "JSPlugin",
        visitor: createVisitor(babel)
    };
};
```

### Configuration file name

`webpack.config.js`

### Configuration

```json
const glob = require("glob");
const path = require("path");
const TerserPlugin = require('terser-webpack-plugin');

const test = glob.sync("./solanaWeb3.js")[0];

module.exports = {
  mode: "production",
  entry: {
    "test": test,
  },
  optimization: { minimize: false }, // use for debugging
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "Build")
  },
  optimization: {
    minimize: false,
    minimizer: [
      new TerserPlugin({
        extractComments: false,
        terserOptions: {
          format: {
            comments: false,
          },
        },
      }),
    ],
  },
  module: {
  rules: [
        {
          test: path.resolve(test),
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
            options: {
              presets: [],
              plugins: [require("./BabelPlugin.js")]
            }
          }
        }
      ]
  },
  plugins: []
};
```

### Current and expected behavior

ERROR in ./solanaWeb3.js 1:620
Module parse failed: Unexpected token (1:620)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.

Error is given when parsing: https://github.com/solana-labs/solana-web3.js `<!-- Development (un-minified) -->` from the ReadMe file. IE: https://unpkg.com/@solana/web3.js@latest/lib/index.iife.js

### Environment

System:
    OS: macOS 12.5
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.19.6 => 7.19.6 
    @babel/preset-env: ^7.19.4 => 7.19.4 
    babel-loader: ^9.1.0 => 9.1.0 
    webpack: ^5.74.0 => 5.74.0

**Comment by Brandon-T** [comment]
Hi, I've uploaded the source here:
[Source.zip](https://github.com/babel/babel/files/9963362/Source.zip)

and here: https://github.com/Brandon-T/Babel-Plugin

**Comment by liuxingbaoyu** [comment]
```
        path.insertAfter(
          Types.expressionStatement(
            Types.callExpression(Types.identifier("$"), [path.node.id])
          )
        );
```
It's not a babel issue, I tested this to work.

**Comment by Brandon-T** [comment]
Well that works! Wow. Did not know I had to add that anywhere. Is there somewhere in the docs where it says I needed that?
Thanks btw!
I will close the issue :)

**Comment by liuxingbaoyu** [comment]
To be honest, I'm also not 100% sure about the source of the problem. `t.expressionStatement` will add a semicolon after the statement, I'm guessing maybe statements without a semicolon are being mishandled by webpack during minification. I tested the intermediate output generated by babel and it can be parsed fine.
