### ISSUE TITLE
[Bug]: Deleting super property

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15169]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
class x { static y = delete super [ 0 ] ; }
```

### Current and expected behavior

`input.js` throws `ReferenceError`:
```console
$ node input.js
input.js:1
class x { static 0 = delete super [ 0 ] ; }
                     ^

ReferenceError: Unsupported reference to 'super'
    at <static_initializer> (input.js:1:22)
    at Object.<anonymous> (input.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```
but `output.js` is terminated normally:
```console
$ node output.js # no error
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEAe0G9oQC5hQS2NAntAvNACYCmIJKJyArgA4kBO0A2tAAzQC60A3NAL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.19.2&externalPlugins=&assumptions=%7B%7D)

**Comment by Jack-Works** [comment]
According to the spec:

- `delete super.xyz` should be translated to `throw new ReferenceError()`
- `delete super[expression]` should be translated to `;({ __proto__: null })[expression]; throw new ReferenceError()`.

Note: Chrome implementation is wrong (see https://bugs.chromium.org/p/v8/issues/detail?id=13452), please use Firefox or Engine262 to verify.

**Comment by SuperSodaSea** [comment]
@Jack-Works Just for my curiosity, how is `({ __proto__: null })[expression]` different from just `expression`? And if this is necessary, maybe it is better to use `Object.create(null)[expression]` to create an object with no prototype?

(I'm willing to create a PR to implement this translation.)

**Comment by Jack-Works** [comment]
> how is `({ __proto__: null })[expression]` different from just expression?

`delete super[expression]` will call [ToPropertyKey](https://tc39.es/ecma262/#sec-topropertykey) on the evaluated value. The easiest way to perform `ToPropertyKey` on a value is to use `something[expression]`

> maybe it is better to use `Object.create(null)[expression]` to create an object with no prototype?

`Object.create` need to lookup `Object` on the lexical scope / global scope, and then perform a lookup on the returned value which means it will be slower and unsafe (if Object.create has been changed) than `({ __proto__: null })`

**Comment by nicolo-ribaudo** [comment]
We have a `toPropertyKey` helper, which also takes care of calling `Symbol.toPrimitive` in environments with polyfilled symbols:
https://github.com/babel/babel/blob/4c59d9fb2c99893f0730d1a06e358b86d8680675/packages/babel-helpers/src/helpers.ts#L925

**Comment by SuperSodaSea** [comment]
So this?
```js
export default function _deleteSuperIdentifier() {
  throw new ReferenceError("delete super.prop is invalid");
}

import toPropertyKey from "toPropertyKey";
export default function _deleteSuperExpression(expr) {
  toPropertyKey(expr);
  throw new ReferenceError("delete super[expr] is invalid");
}
```

**Comment by Jack-Works** [comment]
I think you don't need two more helpers. transpile them in-place is simple enough
