### ISSUE TITLE
[Bug]: Nested iterators results in infinite loop

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15177]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
var [ x ] = { [ Symbol . iterator ] : function * ( ) { yield * { [ Symbol . iterator ] : x => [ ] } ; } } ; 
```

### Current and expected behavior

Input code is terminated with `TypeError` but the transpilation results in an infinite loop:
```console
$ node input.js
input.js:1
var [ x ] = { [ Symbol . iterator ] : function * ( ) { yield * { [ Symbol . iterator ] : x => [ ] } ; } } ;
                                                                                         ^

TypeError: undefined is not a function
    at [Symbol.iterator] (input.js:1:90)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (input.js:1:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```
```console
$ node output.js # never terminates
^C
```

### Environment

[Reproduction in Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBA2hAeEF0IF4IG9oQMoE8C2ARgPYA2EAdBAJYAuApmCDUZEgFwQBmArgHYDGNKkV4QAVBAAUEAJToIOKnRIATcfJi5CpCtXqNmrCB3jIAfJiQBfCAG4INm_aA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2&prettier=true&targets=&version=7.20.4&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.20.2&assumptions=%7B%7D)

**Comment by nicolo-ribaudo** [comment]
This can be reproduced with only the regenerator transform, using this code:
```js
(function* () {
  yield* {
    [Symbol.iterator]: x => [],
  };
})().next();
```
