### ISSUE TITLE
[Bug]: `@babel/plugin-proposal-unicode-sets-regex` – unexpected results

### ISSUE THREAD

**Issue by rauschma** [babel/babel#15193]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

```js
const assert = require('node:assert/strict');

assert.equal(
  /^[\p{Script=Arabic}&&\p{Number}]$/v.test('٣'), true // OK
);
assert.equal(
  /^[\p{Script=Arabic}&&\p{Number}]$/v.test('ق'), true // not OK
);

assert.equal(
  /[\p{ASCII}&&\p{Decimal_Number}]/v.test('4'), true // OK
);
assert.equal(
  /[\p{ASCII}&&\p{Decimal_Number}]/v.test('X'), true // not OK
);
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "plugins": [
    ["@babel/plugin-proposal-unicode-sets-regex"]
  ]
}
```

### Current and expected behavior

See comments in code

### Environment

```
  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 18.10.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.20.2 => 7.20.2 
    @babel/node: ^7.20.2 => 7.20.2 
    @babel/plugin-proposal-unicode-sets-regex: ^7.18.6 => 7.18.6 
```

### Additional context

Repo to reproduce this issue: https://github.com/rauschma/babel-unicode-sets

**Comment by liuxingbaoyu** [comment]
```
{
  "plugins": [
    "@babel/plugin-proposal-unicode-sets-regex",
    "@babel/plugin-transform-unicode-regex"
  ]
}
```
Can you try a configuration like this?

**Comment by rauschma** [comment]
> Can you try a configuration like this?
>
> Seems to work fine like this.

It does indeed! Thanks a lot.

> We might need to enhance the docs to mention `@babel/plugin-transform-unicode-regex`.

Yes, either would help:

* Mentioning the other plugin here (where the TC39 proposal pointed me): https://babeljs.io/docs/en/babel-plugin-proposal-unicode-sets-regex
* Loading the other plugin automatically (if that is possible)

**Comment by JLHwung** [comment]
This is a bug. `plugin-proposal-unicode-sets-regex` should not depend on `transform-unicode-regex`, which transpiles `/\u{10000}/u` to their non-unicode mode equivalent `/\uD800\uDC00/`. It should work with and without the unicode regex transform.

**Comment by liuxingbaoyu** [comment]
https://github.com/tc39/proposal-regexp-unicode-property-escapes
Those seem to belong in this proposal.😕

**Comment by JLHwung** [comment]
Babel currently transforms `/[\p{ASCII}&&\p{Decimal_Number}]/v` as `/[\p{ASCII}&&\p{Decimal_Number}]/u`, which is definitely incorrect.

Here the set notation cannot be transformed without first unwrapping code points behind the unicode property escape. In other words, when set notation contains property escapes, we should also transpile them even if the target might support unicode property escape.

https://github.com/mathiasbynens/regexpu-core/blob/3515c6ba6fa36851dfa0210fb6fe9a95cf2c0494/rewrite-pattern.js#L406

I guess we should somehow make `handlePositive.regSet` work with `handlePositive.nested`.

**Comment by rauschma** [comment]
Some of the following results also seem to be wrong (even if I use the workaround):

```js
assert.equal(
  /^\P{Lowercase_Letter}$/v.test('A'), false // should be true
);
assert.equal(
  /^\P{Lowercase_Letter}$/v.test('a'), false // OK
);

// Both should be true (if I’m not mistaken!)
assert.equal(
  /^\P{Lowercase_Letter}$/iv.test('A'), false
);
assert.equal(
  /^\P{Lowercase_Letter}$/iv.test('a'), false
);
```
