### ISSUE TITLE
[Bug]: Missing compat data information for optional chaining on Samsung Internet

### ISSUE THREAD

**Issue by sgomes** [babel/babel#15199]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

No input code; this is an issue with `@babel/compat-data`.

### Current and expected behavior

`@babel/compat-data` is missing support information for optional chaining on Samsung Internet. As per [`plugins.json`](https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugins.json):

```  
"transform-optional-chaining": {
  "chrome": "91",
  "opera": "77",
  "edge": "91",
  "firefox": "74",
  "safari": "13.1",
  "node": "16.9",
  "deno": "1.9",
  "ios": "13.4",
  "electron": "13.0"
},
"proposal-optional-chaining": {
  "chrome": "91",
  "opera": "77",
  "edge": "91",
  "firefox": "74",
  "safari": "13.1",
  "node": "16.9",
  "deno": "1.9",
  "ios": "13.4",
  "electron": "13.0"
}
```

Both objects should include `"samsung": "13.0"`.

### Environment

No environment; this is an issue with `@babel/compat-data` on the `main` branch.

### Possible solution

It looks like this data is automatically generated based on `@mdn/browser-compat-data`. The version of `@mdn/browser-compat-data` in use is outdated; according to `yarn.lock`, it's `4.0.10`, which was published approximately one year ago (Nov 9, 2021).

Updating to the latest `@mdn/browser-compat-data` (which may involve breaking changes, given that it's on `5.2.16` now) and rerunning generation should fix the issue, as well as any possible similar issues lurking in the dataset.

Having a mechanism in place to update the compatibility data dependency more frequently would be ideal.

**Comment by JLHwung** [comment]
The `@mdn/browser-compat-data` is only used for module-related features like `import` or `export * from`. The compat-data of optional chaining is generated from https://github.com/kangax/compat-table.

While "sumsung: 13" generally supports optional chaining, it is affected by the V8 bug https://crbug.com/v8/11558. If you are a compat-data user, you can refer to https://github.com/babel/babel/blob/4dedd57f64777bae004c50f1f9d9e1db18992dfd/packages/babel-compat-data/data/plugin-bugfixes.json#L108 for the "bugfixed" compat-data.
