### ISSUE TITLE
[Bug]: Comments cannot be accessed through the corresponding node

### ISSUE THREAD

**Issue by GoFzy** [babel/babel#15206]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from '@babel/parser';
  
return parse(code, {
    allowImportExportEverywhere: true,
    sourceType: 'module',
    plugins: ['dynamicImport', 'jsx', 'typescript', 'decorators-legacy'],
    ...options,
  });

```
![image](https://user-images.githubusercontent.com/46565627/202607735-a3d028f8-eea0-407d-ac6c-7cab0c5f7e3f.png)

### Current and expected behavior

current: Comments can only be accessed at the top-level property, not through the corresponding node leadingComments
![image](https://user-images.githubusercontent.com/46565627/202607808-1147342a-5767-4a8e-8552-7ea4b627f19d.png)

### Environment

 System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 14.20.0 - /usr/local/nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - /usr/local/nvm/versions/node/v14.20.0/bin/npm
  npmPackages:
    @babel/generator: ^7.20.4 => 7.20.4 
    @babel/parser: ^7.20.3 => 7.20.3 
    @babel/template: ^7.18.10 => 7.18.10 
    @babel/traverse: ^7.20.1 => 7.20.1 
    @babel/types: ^7.20.2 => 7.20.2 
    eslint: ^8.27.0 => 8.27.0

**Comment by JLHwung** [comment]
I can not reproduce this issue on astexplorer: https://astexplorer.net/#/gist/398f73ce8bceb4c5634383d4f6cf0031/45ecc8e7a848d6bec29f3cc1ef65889677e3c7dd

The comments are attached to ExportNamedDeclaration as expected. Can you provide a reproduction repo?

**Comment by GoFzy** [comment]
> I can not reproduce this issue on astexplorer: https://astexplorer.net/#/gist/398f73ce8bceb4c5634383d4f6cf0031/45ecc8e7a848d6bec29f3cc1ef65889677e3c7dd
> 
> The comments are attached to ExportNamedDeclaration as expected. Can you provide a reproduction repo?

Try this
https://astexplorer.net/#/gist/e796e1701fbd1897bb4d8c90bc4a10db/7fcad748775419c2df1a87c13fdb49aa25edbb3b

**Comment by JLHwung** [comment]
> > I can not reproduce this issue on astexplorer: https://astexplorer.net/#/gist/398f73ce8bceb4c5634383d4f6cf0031/45ecc8e7a848d6bec29f3cc1ef65889677e3c7dd
> > The comments are attached to ExportNamedDeclaration as expected. Can you provide a reproduction repo?
> 
> Try this @JLHwung https://astexplorer.net/#/gist/e796e1701fbd1897bb4d8c90bc4a10db/7fcad748775419c2df1a87c13fdb49aa25edbb3b

The leading comment is attached as expected.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/3607926/202615630-6fe8c2b6-806c-4c50-9454-937f130016f4.png">

**Comment by GoFzy** [comment]
> > > I can not reproduce this issue on astexplorer: https://astexplorer.net/#/gist/398f73ce8bceb4c5634383d4f6cf0031/45ecc8e7a848d6bec29f3cc1ef65889677e3c7dd
> > > The comments are attached to ExportNamedDeclaration as expected. Can you provide a reproduction repo?
> > 
> > 
> > Try this @JLHwung https://astexplorer.net/#/gist/e796e1701fbd1897bb4d8c90bc4a10db/7fcad748775419c2df1a87c13fdb49aa25edbb3b
> 
> The leading comment is attached as expected. What do you think is the correct behaviour?
> 
> <img alt="image" width="726" src="https://user-images.githubusercontent.com/3607926/202615630-6fe8c2b6-806c-4c50-9454-937f130016f4.png">

@JLHwung It's a bit strange that I locally found the leading comment is attached as expected, Is there something wrong with my @babel/parser configuration or version(7.20.3)?
![image](https://user-images.githubusercontent.com/46565627/202618298-174e7b23-acbf-4c1a-8fb7-ff50995cdbef.png)

**Comment by liuxingbaoyu** [comment]
Can you provide a repo to reproduce it?

**Comment by liuxingbaoyu** [comment]
Since this issue has been inactive for a long time, I will close it for now, feel free to reopen it if the problem persists.
