### ISSUE TITLE
[Bug]: babel@plugin-proposal-logical-assignment-operators no longer automatically included/used by @babel/preset-env as of 11:30 PM AEDT 18/11/2022

### ISSUE THREAD

**Issue by zailleh** [babel/babel#15213]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
test ??= "some value"
```

### Configuration file name

.babelrc

### Configuration
```json
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/transform-runtime", {
        "regenerator": false
      }
    ],
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      },
    ],
  ],
  "presets": [
    [
      "@babel/preset-env", {
        "modules": false,
        "loose": false,
        "useBuiltIns": "entry",
        "include": [
          "@babel/plugin-proposal-optional-chaining",
          "@babel/plugin-proposal-nullish-coalescing-operator"
        ],
        "corejs": { "version": 3, "proposals": true }
      }
    ]
  ],
  "comments": false,
  "env": {
    "test": {
      "plugins": ["dynamic-import-node", "@babel/transform-runtime", "@babel/plugin-syntax-jsx"],
      "presets": [
        [
          "@babel/preset-env", {
            "modules": "commonjs",
            "loose": false,
            "useBuiltIns": "usage",
            "corejs": 3,
            "targets": {
              "node": "current"
            }
          }
        ]
      ]
    }
  }
}
```

### Current and expected behavior

Currently getting `Module parse failed: Unexpected token` error. Expect build to proceed.

### Environment

```
 System:
    OS: macOS 12.6
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.19
  npmPackages:
    @babel/core: ^7.18.2 => 7.19.3
    @babel/eslint-parser: ^7.18.2 => 7.19.1
    eslint: ^8.17.0 => 8.24.0
    jest: ^28.1.0 => 28.1.3
    webpack: ^4.46.0 => 4.46.0
```

### Additional context

Building/parsing worked at 11:15pm AEDT 18/11/2022 -- and just 15 minutes later at 11:30pm AEDT 18/11/2022 the build fails and can be reproduced simply by changing the system time.

We were able to workaround this by manually including `babel@plugin-proposal-logical-assignment-operators` in `.babelrc` in the root plugins configuration option - even though this was, and should, be included automatically as a part of `@babel/preset-env`

| Fri 18 Nov 2022 23:15:33 AEDT | Fri 18 Nov 2022 23:30:56 AEDT |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3261554/202930085-27e0a5b8-5d35-42ea-9cc6-2c6816e34aa3.png) | ![image](https://user-images.githubusercontent.com/3261554/202930047-c6105945-aa2a-435f-b8b2-a528daabf2e8.png) |

**Comment by nicolo-ribaudo** [comment]
Can you add the `debug: true` option to `preset-env` and see what it logs?

**Comment by zailleh** [comment]
We can close this one. We kept investigating and it turns out it was browserlist config.

changing:
```json
  "browserslist": [
    "defaults",
    "not IE 11",
    "last 2 years"
  ]
```

to:
```json
  "browserslist": [
    "defaults",
    "not IE 11",
    "last 3 years"
  ]
  ```
  
 Comparing the browser targets from these selectors with the [caniuse data for nullish coalescing operator](https://caniuse.com/?search=Nullish%20coalescing%20operator) the old query was returning chrome v79 (which doesn't support the operator) whilst the new query only returns from v88 where it is meant to be supported so it seems like this was affecting it. This makes the most sense with the random timestamp at which the difference was noted.
