### ISSUE TITLE
[Bug]: Property 'data' does not exist on type 'Scope'

### ISSUE THREAD

**Issue by budarin** [babel/babel#15242]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

![image](https://user-images.githubusercontent.com/8055157/205181961-49356fac-dcea-49f0-90d4-8055118e9f02.png)

### Input code

```js
VariableDeclarator: {
  enter(path): void {
     console.log(path.scope.data)
  }
}


### Current and expected behavior

current - error
expected - not to have error

### Environment

- Babel 7.20.5
- Node 19.2.0

**Comment by liuxingbaoyu** [comment]
Currently we don't publish types, types are provided by https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel__traverse/index.d.ts.

**Comment by liuxingbaoyu** [comment]
Personally I hope so, but it might be difficult and there are no firm plans yet.
