### ISSUE TITLE
[Bug]: addComment is a noop

### ISSUE THREAD

**Issue by dherault** [babel/babel#15248]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const comment = '// foo'

addComment(path.node, 'leading', comment, true)
```

### Configuration file name

babel.config.js

### Configuration

```js
{
  sourceType: 'module'
  plugins: ['jsx', 'typescript'],
}
```

### Current and expected behavior

Current: No comment inserted.
Expected: `// foo` gets inserted.

### Environment

"@babel/core": "^7.20.5",
"@babel/generator": "^7.20.5",
"@babel/parser": "^7.20.5",
"@babel/plugin-syntax-jsx": "^7.18.6",
"@babel/plugin-syntax-typescript": "^7.20.0",
"@babel/traverse": "^7.20.5",
"@babel/types": "^7.20.5",
node v18.6.0
OS: macOS Monterey 12.4

**Comment by liuxingbaoyu** [comment]
Can you provide a repository or example to reproduce?

**Comment by dherault** [comment]
I'm deeply sorry about this one. 
I forgot to regenerate...
Best,
