### ISSUE TITLE
[Bug]: Module parse failed: The keyword 'private' is reserved

### ISSUE THREAD

**Issue by dsaenko** [babel/babel#15267]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Using `private` for arguments inside constructor
```js
 protected constructor(
        private readonly a: number,
        private readonly b: number,
    ) {
        this.a = a;
        this.b = b;
    }
```

leads to such error
```Module parse failed: The keyword 'private' is reserved
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
```

I discovered that the reason is in the version 7.17.12 of @babel/preset-typescript. Before that version all were ok.

### Configuration

```json
{
"presets": [
    "@babel/preset-typescript",
    "@babel/preset-react",
    "@babel/preset-env"
  ],
  "plugins": ["@babel/plugin-transform-runtime"],
}
```

### Current and expected behavior

Current behavior: valid code of typescript gives error.
Expected behavior: babel handles `private` inside constructor.

### Environment

Babel version: ^7.20.5
Node: 16.18.1
npm: 8.19.2
OS: macOS 10.15.7
Monorepo: no

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYGwhgzhAECCDeAoaAHATgewC4FNi4BNpgMA7CLNAV3wzQAplpmXU0BLANzF2jRzAEyIAJ7QwALmikqAWwBGONABomrZui48cfAUNKjo8qTIVLVrAJTQk6llgAW7CADow0ALziA3GvWPnF3lPI19WAF9EcKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D

I can't reproduce it in the repl, can you provide an example?

**Comment by dsaenko** [comment]
Hi, @liuxingbaoyu 
I made the example https://github.com/dsaenko/babel-bug-report

**Comment by JLHwung** [comment]
@dsaenko Thanks for the reproduction example, it is very helpful.

Unlike plugins, the Babel presets are applied from right to left. As a workaround, please apply `preset-typescript` before `preset-env`:

```js
{
"presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript",
  ],
  "plugins": ["@babel/plugin-transform-runtime"],
}
```

Admittedly the class properties transform should throw preset ordering error when typescript `private` is seen.

**Comment by dsaenko** [comment]
@JLHwung It works, thank you!
