### ISSUE TITLE
[Bug]: Duplicate declaration for type and value in ts

### ISSUE THREAD

**Issue by PaulBlanche** [babel/babel#15262]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
import { type Foo } from './foo'

function Foo() {}
```
[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzjAnmApnAYhCcC-cAZlBCHAOQB0A9EbhQFCNECuAdgMYzATva4AFAEpE-RkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": ["last 2 versions", "ie 11"]
        },
        "modules": "auto"
      }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"],
}
```
#### Current behavior

Babel throws an error : 
```
Duplicate declaration "Foo"
  1 | import { type Foo } from './foo'
  2 |
> 3 | function Foo() {}
    |          ^^^
  4 |
```

However there is no error if the type `Foo` is declared in the same file as the function `Foo`.

#### Expected behavior

Babel should accept that an imported type and a value can share the same name.

### Environment

Babel version: v7.20.5
Node: 16.15.1
Yarn: 1.22.19
OS: Linux 6.0 Arch Linux
Monorepo: yes (yarn workspaces)

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/babel/babel/pull/15284
