### ISSUE TITLE
yield in the body of '=>' operator

### ISSUE THREAD

**Issue by zlbbq** [babel/babel#1528]
The code bellow will cause complile error with babel version '5.3.3'

var fs = require('co-fs');
var O = {};
O.f = function * () {
       var arr = ['/root'];
       arr.forEach(p => {
               console.log(yield fs.exists(p));
       });
};

So, I had to change the argument of forEach from '=>' to a generator like the following code
var fs = require('co-fs');
var O = {};
O.f = function * () {
       var arr = ['/root'];
       arr.forEach(function * (p) {
               console.log(yield fs.exists(p));
       });
};

OK, it works. There is no example that I found described how to, even could be use yield keyword in the '=>' statement, but I think, as it named statement or expression, should it inherit any feature from the parent object such as a function or a generator function?

**Comment by sebmck** [comment]
This is expected behaviour. There's no way to create generator arrow functions and `yield` is only valid **directly** in generator function bodies.

**Comment by loganfsmyth** [comment]
@zlbbq Since you need to avoid creating a new function body, so I'd use a `for...of`:

```
var fs = require('co-fs');
var O = {};
O.f = function * () {
       var arr = ['/root'];
       for (const p of arr) yield fs.exists(p);
};
```
