### ISSUE TITLE
[Bug]: Nuxt 2.X build failing due to 'Cannot read properties of null (reading 'scope')' error in @babel/traverse

### ISSUE THREAD

**Issue by apoorv1410** [babel/babel#15299]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Can't add the code here. Error occurs with `npm run build` command

### Current and expected behavior

Current error screenshots:
![Screenshot from 2022-12-22 18-11-50](https://user-images.githubusercontent.com/43142014/209136709-fce313ec-5e1a-4467-8518-909af435c835.png)
![Screenshot from 2022-12-22 18-11-39](https://user-images.githubusercontent.com/43142014/209136720-bfde1bfd-af9c-4284-acb7-155fadd14fcf.png)

### Environment

- Babel [v 7.20.7]
- Nuxt [v 2.15.8]

### Additional context

The build is filing with Cannot read properties of null (reading 'scope') in @babel/traverse package version 7.20.7

**Comment by apoorv1410** [comment]
Fixed with updating node version from 16.13.1 to 16.14.2. Closing the issue now

**Comment by liuxingbaoyu** [comment]
It's weird and weirdly solved by upgrading nodejs, but glad it's working now.
If anyone else encounters this problem please reopen a reproducible issue.

**Comment by retyui** [comment]
Faced with the same issue, updating  a babel preset helped

```diff
-"metro-react-native-babel-preset": "^0.67.0",
+"metro-react-native-babel-preset": "^0.70.3",
```

**Comment by apoorv1410** [comment]
Update: just updating the nodejs version was not enough. We also had to downgrade to 7.20.5 explicitly from `package.json` with this code:
```

    "overrides": {
        "@babel/core": {
           ".": "7.20.5",
            "@babel/traverse":"7.20.5"
        }
    }
```

**Comment by xdlrt** [comment]
same issue at @babel/traverse, is there any progress?

**Comment by liuxingbaoyu** [comment]
Can anyone provide a repo that reproduces it?

**Comment by retyui** [comment]
@liuxingbaoyu sure:
- https://github.com/retyui/babel-issues-15299#readme

**Comment by liuxingbaoyu** [comment]
v7.20.10 is released, hoping to fix this issue.

**Comment by necatisarhanli** [comment]
@liuxingbaoyu fix is legit , thanks everyone :)
