### ISSUE TITLE
[Bug]: Could not transpile code with enabled preset-env 

### ISSUE THREAD

**Issue by Mavrin** [babel/babel#15293]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
export class Number {
  static type = "number";
}
```

### Current and expected behavior

throw error 
```
We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```
transpile code this accordingly babel/preset-env

### Environment

https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4DkCuBbAI2CjgG8AoOONGFGASwThgE8xg4BeOAIgDt8RKDwDc5AL7kgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D

### Additional context

but this code works
```js
class Number {
  static type = "number";
}
export {Number}
```

**Comment by Mavrin** [comment]
I noticed that code doesn't work when class name is name one of javascript type `String`, `Number`, `Symbol`

**Comment by JLHwung** [comment]
Note that the issue is not limited to `String`, `Number` or `Symbol`. It will be triggered when the export class name collides with any builtin depended by the injected Babel helpers.

For example:

```js
export class TypeError {
  #type = "number";
}
```
