### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'constantViolations')

### ISSUE THREAD

**Issue by cervotoc** [babel/babel#15300]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

![image](https://user-images.githubusercontent.com/25517179/209144826-0f456240-fad8-49ad-99d6-04f7f6aafc3b.png)

### Current and expected behavior

After release @babel/plugin-transform-block-scoping v7.20.7 have problem with build project. When override devDependencies to  v7.20.5 build works fine.

### Environment

- @babel/plugin-transform-block-scoping v7.20.7

**Comment by ndelangen** [comment]
Storybook's CI just started running into this problem as well:
https://app.circleci.com/pipelines/github/storybookjs/storybook/36687/workflows/80832c04-4c2e-464a-adad-62460fc137ad/jobs/461159

**Comment by timhuijgen** [comment]
We also have multiple Angular projects running into the same issue.

**Comment by ndelangen** [comment]
Looking at https://github.com/babel/babel/releases it would appear as if this PR might be the only thing that changed:
https://github.com/babel/babel/pull/15278 ?

But of course it could be that somewhere else in the call stack things changed..

Here's the full stack trace of 1 error we get:

```
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! TypeError: /tmp/storybook/bench/cra-default-ts/.storybook/preview.js: Cannot read properties of undefined (reading 'constantViolations')
ERR!     at disallowConstantViolations (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/validation.js:23:35)
ERR!     at validateUsage (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/validation.js:17:7)
ERR!     at transformBlockScopedVariable (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:123:57)
ERR!     at PluginPass.VariableDeclaration (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:83:11)
ERR!     at newFn (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/visitors.js:156:21)
ERR!     at NodePath._call (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:49:20)
ERR!     at NodePath.call (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:36:17)
ERR!     at NodePath.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:86:31)
ERR!     at TraversalContext.visitQueue (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:95:16)
ERR!     at TraversalContext.visitSingle (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:71:19)
ERR!     at TraversalContext.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:120:19)
ERR!     at traverseNode (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/traverse-node.js:20:17)
ERR!     at NodePath.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:92:52)
ERR!     at TraversalContext.visitQueue (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:95:16)
ERR!     at TraversalContext.visitSingle (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:71:19)
ERR!     at TraversalContext.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:120:19)
ERR!     at traverseNode (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/traverse-node.js:20:17)
ERR!     at traverse (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/index.js:50:34)
ERR!     at transformFile (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transformation/index.js:81:29)
ERR!     at transformFile.next (<anonymous>)
ERR!     at run (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transformation/index.js:24:12)
ERR!     at run.next (<anonymous>)
ERR!     at transform (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transform.js:23:41)
ERR!     at transform.next (<anonymous>)
ERR!     at step (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:221:32)
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:229:13
ERR!     at async.call.result.err.err (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:190:11)
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:159:13
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/gensync-utils/async.js:96:7
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:97:35
ERR!     at step (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:238:14)
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:229:13
ERR!     at async.call.result.err.err (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:190:11)
```

**Comment by ndelangen** [comment]
This is another PR that touched the code in this release:
https://github.com/babel/babel/pull/15275

**Comment by ndelangen** [comment]
Ow, this one seems a candidate: https://github.com/babel/babel/pull/15200

**Comment by ndelangen** [comment]
@nicolo-ribaudo It seems this issue isn't quite..

It might be related to browserlist somehow, I've heard 1 storybook user report:
> I could replicate the issue by removing the browserslist from the package.json file. Adding it back resolved the issue.
> ~ https://github.com/storybookjs/storybook/issues/20382#issuecomment-1363275148

But right now this is the error storybook users are facing:

```
ERR! TypeError: /tmp/storybook/bench/cra-default-ts/.storybook/preview.js: Cannot set properties of undefined (setting 'kind')
ERR!     at transformBlockScopedVariable (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:127:41)
```

full:
```
ERR! TypeError: /tmp/storybook/bench/cra-default-ts/.storybook/preview.js: Cannot set properties of undefined (setting 'kind')
ERR!     at transformBlockScopedVariable (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:127:41)
ERR!     at PluginPass.VariableDeclaration (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:83:11)
ERR!     at newFn (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/visitors.js:156:21)
ERR!     at NodePath._call (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:49:20)
ERR!     at NodePath.call (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:36:17)
ERR!     at NodePath.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:86:31)
ERR!     at TraversalContext.visitQueue (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:95:16)
ERR!     at TraversalContext.visitSingle (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:71:19)
ERR!     at TraversalContext.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:120:19)
ERR!     at traverseNode (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/traverse-node.js:20:17)
ERR!     at NodePath.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:92:52)
ERR!     at TraversalContext.visitQueue (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:95:16)
ERR!     at TraversalContext.visitSingle (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:71:19)
ERR!     at TraversalContext.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:120:19)
ERR!     at traverseNode (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/traverse-node.js:20:17)
ERR!     at traverse (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/index.js:50:34)
ERR!     at transformFile (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transformation/index.js:81:29)
ERR!     at transformFile.next (<anonymous>)
ERR!     at run (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transformation/index.js:24:12)
ERR!     at run.next (<anonymous>)
ERR!     at transform (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transform.js:23:41)
ERR!     at transform.next (<anonymous>)
ERR!     at step (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:221:32)
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:229:13
ERR!     at async.call.result.err.err (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:190:11)
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:159:13
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/gensync-utils/async.js:96:7
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:97:35
ERR!     at step (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:238:14)
ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:229:13
ERR!     at async.call.result.err.err (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:190:11)
```

**Comment by cervotoc** [comment]
> @nicolo-ribaudo It seems this issue isn't quite resolved..
> 
> Would you mind re-opening the issue, or @cervotoc?
> 
> It might be related to browserlist somehow, I've heard 1 storybook user report:
> 
> > I could replicate the issue by removing the browserslist from the package.json file. Adding it back resolved the issue.
> > ~ [storybookjs/storybook#20382 (comment)](https://github.com/storybookjs/storybook/issues/20382#issuecomment-1363275148)
> 
> But right now this is the error storybook users are facing:
> 
> ```
> ERR! TypeError: /tmp/storybook/bench/cra-default-ts/.storybook/preview.js: Cannot set properties of undefined (setting 'kind')
> ERR!     at transformBlockScopedVariable (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:127:41)
> ```
> 
> full:
> 
> ```
> ERR! TypeError: /tmp/storybook/bench/cra-default-ts/.storybook/preview.js: Cannot set properties of undefined (setting 'kind')
> ERR!     at transformBlockScopedVariable (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:127:41)
> ERR!     at PluginPass.VariableDeclaration (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:83:11)
> ERR!     at newFn (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/visitors.js:156:21)
> ERR!     at NodePath._call (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:49:20)
> ERR!     at NodePath.call (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:36:17)
> ERR!     at NodePath.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:86:31)
> ERR!     at TraversalContext.visitQueue (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:95:16)
> ERR!     at TraversalContext.visitSingle (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:71:19)
> ERR!     at TraversalContext.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:120:19)
> ERR!     at traverseNode (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/traverse-node.js:20:17)
> ERR!     at NodePath.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/path/context.js:92:52)
> ERR!     at TraversalContext.visitQueue (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:95:16)
> ERR!     at TraversalContext.visitSingle (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:71:19)
> ERR!     at TraversalContext.visit (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/context.js:120:19)
> ERR!     at traverseNode (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/traverse-node.js:20:17)
> ERR!     at traverse (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/traverse/lib/index.js:50:34)
> ERR!     at transformFile (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transformation/index.js:81:29)
> ERR!     at transformFile.next (<anonymous>)
> ERR!     at run (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transformation/index.js:24:12)
> ERR!     at run.next (<anonymous>)
> ERR!     at transform (/tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/transform.js:23:41)
> ERR!     at transform.next (<anonymous>)
> ERR!     at step (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:221:32)
> ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:229:13
> ERR!     at async.call.result.err.err (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:190:11)
> ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:159:13
> ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/@babel/core/lib/gensync-utils/async.js:96:7
> ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:97:35
> ERR!     at step (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:238:14)
> ERR!     at /tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:229:13
> ERR!     at async.call.result.err.err (/tmp/storybook/bench/cra-default-ts/node_modules/gensync/index.js:190:11)
> ```

i dont know how re-open this issue :\ but i want - the solution not work
