### ISSUE TITLE
[Bug]: TypeError: Cannot set properties of undefined (setting 'kind')

### ISSUE THREAD

**Issue by reesscot** [babel/babel#15302]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

<img width="883" alt="image" src="https://user-images.githubusercontent.com/6165315/209195104-b68d1d53-0a3a-42ae-8204-b466d69b3b07.png">

Seeing the error:
```
Cannot set properties of undefined (setting 'kind')
```
Seems related to https://github.com/babel/babel/issues/15300 and 

### Current and expected behavior

After release @babel/plugin-transform-block-scoping v7.20.8 seeing the error above.

### Environment

  System:
    OS: macOS 12.6.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm

### Possible solution

Does https://github.com/babel/babel/pull/15200 need to be reverted until the issues are all fixed?

**Comment by pgaurav9** [comment]
We are also experiencing a similar issue for a react-app with the following versions:
- node: 8.12.0
- npm: 6.4.1

The earlier error was `TypeError: 'constantViolations' of undefined` however now it's `TypeError: Cannot set property 'kind' of undefined`. Since our project is working on an old package version so we wanted to be sure whether it's a deprecation of babel dependency that we are using or something else. Kindly provide an update on this.

**Comment by nicolo-ribaudo** [comment]
A fix would be checking that every call to `scope.getOwnBinding` in https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-block-scoping/src can return `null`. I can probably work on a PR in a few hours, tomorrow morning (EU) at latest, but if someone else wants to open the PR it would be much appreciated.

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/209203946-aad78306-ba87-4fea-99ce-acce8d340807.png)

I found two places, one of which I'm not sure how to do.

**Comment by nicolo-ribaudo** [comment]
Maybe in the second one we could run a crawl if the binding is not present.

**Comment by pcr-bmiller** [comment]
I went back a version for @babel/plugin-transform-block-scoping and my react application is now building successfully again.
`npm i @babel/plugin-transform-block-scoping@7.20.5`

**Comment by ndelangen** [comment]
I'm 100% willing to help out, however I do not have sufficient knowledge to understand:
> Maybe in the second one we could run a crawl if the binding is not present.

@liuxingbaoyu you seem to have 👍'd it, do you understand? Do you want help?

**Comment by ndelangen** [comment]
I'm also a bit hesitant to ask.. but would a roll-back to `7.20.5` be an option? Meaning releasing a new patch with the contents of `7.20.5`?

I could provide a environment, in which you can replace some `node_modules` content and a command to run to reproduce the problem in "isolation"...

**Comment by gabriels1234** [comment]
Thanks, this is a good work-around for now.
A note to self, when dealing with these types of issues, make sure versions are pinned:
`"@babel/core": "7.20.5",`
vs `"@babel/core": "^7.20.5",` (does not fix the issue)

**Comment by liuxingbaoyu** [comment]
@ndelangen v7.20.9 has been released, has the problem been solved?

**Comment by ndelangen** [comment]
Going to try now!

**Comment by ndelangen** [comment]
Looking positive!

**Comment by barbalex** [comment]
can't find v7.20.9: https://www.npmjs.com/package/@babel/core?activeTab=versions

**Comment by nicolo-ribaudo** [comment]
@barbalex The bug/fix is in `@babel/plugin-transform-block-scoping`

**Comment by barbalex** [comment]
@nicolo-ribaudo Thanks!
My project has not explicitely included `@babel/plugin-transform-block-scoping` so far. So I:
- `npm i --dev @babel/plugin-transform-block-scoping`
- added `"@babel/plugin-transform-block-scoping": "7.20.9"` as overrides to package.json

and the build works again!

Thanks so much for your effort and help!

**Comment by mccoinu** [comment]
Hi I had the same problem,
First with the message:
`TypeError: 'constantViolation' of undefined`
then:
` TypeError: Cannot set property 'kind' of undefined.`

By setting
"@babel/core": "7.20.5"

I solved.

Thank you

**Comment by nicolo-ribaudo** [comment]
@barbalex Now you can also remove it from your package.json! The process you did updated the your lockfile, and now that the lockfile is updated you won't get the old version anymore :)

**Comment by barbalex** [comment]
@nicolo-ribaudo Wow. The marvels of lockfiles. Glad to be helped by guys with more insight!

**Comment by reesscot** [comment]
I can confirm that I'm no longer seeing the error after installing `@babel/plugin-transform-block-scoping@7.20.9`

**Comment by ndelangen** [comment]
Thank you @nicolo-ribaudo and everyone else that helped. 

I wish I could have done more to help myself.

Really truly appreciative of the quick fixes, thank you.
