### ISSUE TITLE
[Bug]: Internal Babel error: path is not in loop. Please report this as a bug

### ISSUE THREAD

**Issue by AeolusZane** [babel/babel#15306]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
const arr = [];

for (let i = 0; i < 10; i--) {
    const item = true; // or let
    arr.find(i => i === item);
}
```

### Current and expected behavior

this code babel cannot resolve.
it reports 'Error: Internal Babel error: path is not in loop. Please report this as a bug.'

### Environment

System:
    OS: macOS 12.4
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  npmPackages:
    @babel/plugin-proposal-logical-assignment-operators: ^7.16.7 => 7.20.7 
    @babel/plugin-transform-modules-commonjs: ^7.16.0 => 7.20.7 
    babel-loader: 8.0.6 => 8.0.6 
    eslint: ^7.0.0 => 7.32.0 
    webpack: ^5.72.0 => 5.75.0

**Comment by AeolusZane** [comment]
sorry i just find problem is from  @babel/plugin-transform-block-scoping: 7.5.5.

**Comment by liuxingbaoyu** [comment]
This is a bit odd since this hint was introduced a few days ago.

**Comment by AeolusZane** [comment]
thanks so much for your soonest replying~

**Comment by AeolusZane** [comment]
thanks so much for your soonest replying~
