### ISSUE TITLE
[Bug]:  Cannot find module 'regjsparser'

### ISSUE THREAD

**Issue by turnerhayes** [babel/babel#15317]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

https://github.com/turnerhayes/quintro/tree/ts-refactor

It occurs when I run `npm run test`

### Configuration file name

.babelrc

### Configuration

I attempted to do the BABEL_SHOW_CONFIG_FOR thing, but it appears the error was thrown before that had a chance to print the config. Here's the whole config file:

```json
{
	"plugins": [
		"transform-undefined-to-void",
		// Stage 0
		"@babel/plugin-proposal-function-bind",
		// Stage 1
		"@babel/plugin-proposal-export-default-from",
		"@babel/plugin-proposal-logical-assignment-operators",
		[
			"@babel/plugin-proposal-optional-chaining",
			{
				"loose": false
			}
		],
		[
			"@babel/plugin-proposal-pipeline-operator",
			{
				"proposal": "minimal"
			}
		],
		[
			"@babel/plugin-proposal-nullish-coalescing-operator",
			{
				"loose": false
			}
		],
		"@babel/plugin-proposal-do-expressions",
		// Stage 2
		[
			"@babel/plugin-proposal-decorators",
			{
				"legacy": true
			}
		],
		"@babel/plugin-proposal-function-sent",
		"@babel/plugin-proposal-export-namespace-from",
		"@babel/plugin-proposal-numeric-separator",
		"@babel/plugin-proposal-throw-expressions",
		// Stage 3
		"@babel/plugin-syntax-dynamic-import",
		"@babel/plugin-syntax-import-meta",
		[
			"@babel/plugin-proposal-class-properties",
			{
				"loose": true
			}
		],
		"@babel/plugin-proposal-json-strings",
		[
			"@babel/plugin-proposal-private-property-in-object",
			{
				"loose": true
			}
		],
		[
			"@babel/plugin-proposal-private-methods",
			{
				"loose": true
			}
		]
	],
	"presets": [
		[
			"@babel/preset-env",
			{
				"modules": false
			}
		],
		"@babel/preset-react"
	],
	"env": {
		"production": {
			"only": [
				"app",
				"shared-lib"
			],
			"plugins": [
				"transform-react-remove-prop-types",
				"transform-react-constant-elements",
				"transform-react-inline-elements"
			]
		},
		"test": {
			"plugins": [
				"transform-es2015-modules-commonjs",
				"dynamic-import-node"
			]
		}
	}
}
```

### Current and expected behavior

Current: Throws an error that it cannot find the module "regjsparser". Here is the require stack it shows:

```
/projects/websites/quintro/shared-lib/selectors/quintro.test.js
  0:0  error  Parsing error: [BABEL]: Cannot find module 'regjsparser'
Require stack:
- /projects/websites/quintro/node_modules/@babel/helper-create-regexp-features-plugin/node_modules/regexpu-core/rewrite-pattern.js
- /projects/websites/quintro/node_modules/@babel/helper-create-regexp-features-plugin/lib/index.js
- /projects/websites/quintro/node_modules/@babel/plugin-proposal-unicode-property-regex/lib/index.js
- /projects/websites/quintro/node_modules/@babel/preset-env/lib/available-plugins.js
- /projects/websites/quintro/node_modules/@babel/preset-env/lib/filter-items.js
- /projects/websites/quintro/node_modules/@babel/preset-env/lib/index.js
- /projects/websites/quintro/node_modules/@babel/core/lib/config/files/module-types.js
- /projects/websites/quintro/node_modules/@babel/core/lib/config/files/configuration.js
- /projects/websites/quintro/node_modules/@babel/core/lib/config/files/index.js
- /projects/websites/quintro/node_modules/@babel/core/lib/index.js
- /projects/websites/quintro/node_modules/@babel/eslint-parser/lib/worker/babel-core.cjs
- /projects/websites/quintro/node_modules/@babel/eslint-parser/lib/worker/handle-message.cjs
- /projects/websites/quintro/node_modules/@babel/eslint-parser/lib/client.cjs
- /projects/websites/quintro/node_modules/@babel/eslint-parser/lib/index.cjs
- /projects/websites/quintro/node_modules/@eslint/eslintrc/dist/eslintrc.cjs (While processing: /projects/websites/quintro/node_modules/@babel/preset-env/lib/index.js)
```

Expected: Compiles without error

I'm not sure why the `regjsparser` module is not getting installed; it's declared as a dependency of `regexpu-core`. I've tried removing `node_modules` and running `npm i` several times--no difference.

### Environment

System:
    OS: Linux 4.19 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @babel/cli: ^7.0.0 => 7.20.7 
    @babel/core: ^7.0.0 => 7.20.7 
    @babel/eslint-parser: ^7.19.1 => 7.19.1 
    @babel/plugin-proposal-class-properties: ^7.0.0 => 7.18.6 
    @babel/plugin-proposal-decorators: ^7.0.0 => 7.20.7 
    @babel/plugin-proposal-do-expressions: ^7.0.0 => 7.18.6 
    @babel/plugin-proposal-export-default-from: ^7.0.0 => 7.18.10 
    @babel/plugin-proposal-export-namespace-from: ^7.0.0 => 7.18.9 
    @babel/plugin-proposal-function-bind: ^7.0.0 => 7.18.9 
    @babel/plugin-proposal-function-sent: ^7.0.0 => 7.18.6 
    @babel/plugin-proposal-json-strings: ^7.0.0 => 7.18.6 
    @babel/plugin-proposal-logical-assignment-operators: ^7.0.0 => 7.20.7 
    @babel/plugin-proposal-nullish-coalescing-operator: ^7.0.0 => 7.18.6 
    @babel/plugin-proposal-numeric-separator: ^7.0.0 => 7.18.6 
    @babel/plugin-proposal-optional-chaining: ^7.0.0 => 7.20.7 
    @babel/plugin-proposal-pipeline-operator: ^7.0.0 => 7.18.9 
    @babel/plugin-proposal-private-methods: ^7.18.6 => 7.18.6 
    @babel/plugin-proposal-private-property-in-object: ^7.20.5 => 7.20.5 
    @babel/plugin-proposal-throw-expressions: ^7.0.0 => 7.18.6 
    @babel/plugin-syntax-dynamic-import: ^7.0.0 => 7.8.3 
    @babel/plugin-syntax-import-meta: ^7.0.0 => 7.10.4 
    @babel/plugin-transform-modules-commonjs: ^7.0.0 => 7.20.11 
    @babel/plugin-transform-react-constant-elements: ^7.0.0 => 7.20.2 
    @babel/plugin-transform-react-inline-elements: ^7.0.0 => 7.18.6 
    @babel/polyfill: ^7.0.0 => 7.12.1 
    @babel/preset-env: ^7.20.2 => 7.20.2 
    @babel/preset-react: ^7.18.6 => 7.18.6 
    @babel/register: ^7.18.9 => 7.18.9 
    @babel/runtime: ^7.4.5 => 7.20.7 
    babel-jest: ^23.4.2 => 23.6.0 
    babel-loader: ^9.1.0 => 9.1.0 
    babel-plugin-dynamic-import-node: 1.0.2 => 1.0.2 
    babel-plugin-react-intl: 2.3.1 => 2.3.1 
    babel-plugin-react-transform: 2.0.2 => 2.0.2 
    babel-plugin-styled-components: 1.1.4 => 1.1.4 
    babel-plugin-transform-es2015-modules-commonjs: ^6.26.2 => 6.26.2 
    babel-plugin-transform-react-remove-prop-types: 0.4.5 => 0.4.5 
    babel-plugin-transform-undefined-to-void: ^6.9.4 => 6.9.4 
    eslint: ^8.30.0 => 8.30.0 
    jest: ^29.3.1 => 29.3.1 
    webpack: ^5.75.0 => 5.75.0

**Comment by JLHwung** [comment]
Thanks for the reproduction repo. It helps a lot.

For some reason, you have removed `regjsparser` from the `package-lock.json` in this commit: https://github.com/turnerhayes/quintro/commit/3052d70bd33b674f479861a3fa7462b3eec930fb#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L1861 (expand the lock file), so `regjsparser` is not installed.

You can reset to the parent of the this commit or delete the lock file and install again.
