### ISSUE TITLE
[Bug]: Stage 3 decorators: initializers are undefined in Custom Element constructors

### ISSUE THREAD

**Issue by trusktr** [babel/babel#15325]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
const el = document.createElement('foo-el')

document.body.append(el)

function element(name) {
  return (Class) => {
    customElements.define(name, Class) // Uncaught TypeError: undefined is not a function
  }
}

function attribute(_, ctx) {
  return (initial) => initial
}

@element('foo-el')
class Foo extends HTMLElement {
  @attribute foo = 123
}
```

### Configuration file name

babel.config.json

### Configuration

```js
module.exports = {
	plugins: [
		['@babel/plugin-transform-typescript', {allowDeclareFields: true}],
		['@babel/plugin-proposal-decorators', {version: '2022-03'}],
		['@babel/plugin-proposal-class-static-block'],
	],

	presets: [
		['@babel/preset-typescript', {isTSX: true, allExtensions: true, onlyRemoveTypeImports: true}],
		['babel-preset-solid'],
	]
}
```

### Current and expected behavior

Initializers in the output are `undefined` when `constructor` runs during the `customElements.define()` call (element upgrade) inside the `@element` decorator.

### Environment

```
  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 18.12.1 - ~/.n-node-versions/bin/node
    npm: 8.19.3 - ~/.npm-packages/bin/npm
  npmPackages:
    @babel/cli: 7.18.10 => 7.18.10 
    @babel/core: 7.19.1 => 7.19.1 
    @babel/plugin-proposal-class-static-block: 7.18.6 => 7.18.6 
    @babel/plugin-proposal-decorators: 7.19.1 => 7.19.1 
    @babel/preset-typescript: 7.18.6 => 7.18.6 
    @babel/runtime: 7.19.0 => 7.19.0 
    babel-loader: 8.2.5 => 8.2.5 
    babel-preset-solid: 1.5.4 => 1.5.4 
    webpack: 5.74.0 => 5.74.0 
```

**Comment by trusktr** [comment]
Unable to make a simple reproduction yet. Here's my attempt:

https://codesandbox.io/s/babel-7-decorators-boilerplate-forked-cy2i01?file=/.babelrc

but it gives the error

```
Class fields are not enabled
```

for which there are no results on the internet.

**Comment by trusktr** [comment]
I can't [reproduce in repl](https://babeljs.io/repl#?browsers=chrome%20100&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBApgGxgXhgExMArgWzmKAOmACc4BDKOAUQTjwIAoByAMxBAFpFmBKAKH4ZsDIgCMQaAJ6FyABzn40jRAP6ssYYFACW4eHVGMw5PLxgBvfjBhkoWEmBiMAwgnIQI55AD5L1mxhsaBAcWnp8KAhCNDhWHTA4Y1M4ABoYNw8vAIBffjz1TW09J0ooEh0xLCpGAH107QAPcysbOwcnRgSdXXIEbz9u3oR8wQABRAimNg5uBD4YAHpF201dPHgSEhASfmB3TxgAMQ54RqowNAgYAAkAFQBZABlw0X8bMbKKqqoYdhAUDAAIwAJgAzPkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.20.12&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.20.7&assumptions=%7B%7D), unable to set options for plugins.

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/repl#?browsers=chrome%20100&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBApgGxgXhgExMArgWzmKAOmACc4BDKOAUQTjwIAoByAMxBAFpFmBKAKH4ZsDIgCMQaAJ6FyABzn40jRAP6ssYYFACW4eHVGMw5PLxgBvfjBhkoWEmBiMAwgnIQI55AD5L1mxhsaBAcWnp8KAhCNDhWHTA4Y1M4ABoYNw8vAIBffjz1TW09J0ooEh0xLCpGAH107QAPcysbOwcnRgSdXXIEbz9u3oR8wQABRAimNg5uBD4YAHpF201dPHgSEhASfmB3TxgAMQ54RqowNAgYAAkAFQBZABlw0X8bMbKKqqoYdhAUDAAIwAJgAzPkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2&prettier=false&targets=&version=7.20.12&externalPlugins=&assumptions=%7B%7D

It seems so?

**Comment by JLHwung** [comment]
Here is a reproduction without `customElements`:

```js
function classDec(Class) {
  return new Class, Class;
}

function memberDec(value) {
  return value;
}

@classDec 
class Foo {
  @memberDec foo
}
```

Currently it is transpiled as:
```js
/* other helpers omitted */
function _applyDecs(targetClass, memberDecs, classDecs) {
  var ret = [];
  return applyMemberDecs(ret, targetClass, memberDecs), applyClassDecs(ret, targetClass, classDecs), ret;
}

function classDec(Class) {
  return new Class, Class;
}

function memberDec(value) {
  return value;
}

let _Foo;
class Foo {
  constructor() {
    _defineProperty(this, "foo", _init_foo(this));
  }
}
[_init_foo, _Foo, _initClass] = _applyDecs(Foo, [[memberDec, 0, "foo"]], [classDec]);
_initClass();
```

Evaluating this script will throw "_init_foo is undefined" because we are invoking the initializer in the `Foo` constructor, which is invoked by the class decorator. At this point, the actual `foo` initializer is already in the `ret` of `_applyDecs`, but it is not yet bound to the `_init_foo` because `ret` is not yet returned from `_applyDecs`.

To address this issue, we can make `_applyDecs` a 2-pass iterator, which yielded the prepared initializers, and then modified classes. etc. Alternatively we can adopt the TS approach, which emits a member decorator applying pass and a class pass.

**Comment by trusktr** [comment]
I wonder if there is a workaround I can use for now. I'm trying to convert a custom element library to stage 3 decorators, and have some unit tests to ensure that pre-upgrade JS properties are handled properly when upgrade happens.

Something like this:

```js
		const fooEl = document.createElement('foo-element') as FooElement
		expect(fooEl).toBeInstanceOf(HTMLElement)

		document.body.append(fooEl)
		fooEl.foo = 1
		fooEl.setAttribute('bar', 2)

		@element('foo-element')
		class FooElement extends Element {
			@attribute foo = 3
			@attribute bar = 4
		}

		expect(fooEl).toBeInstanceOf(FooElement)
		// ... some other checks to ensure things were handled well ...
```

One thing I can do is use `queueMicrotask` to delay the `customElements.define()` call, and mention a temporary caveat that elements won't be defined until next microtask. This is not ideal of course, and might cause unforseen code ordering issues.

Or maybe I should detect upgrade inside of `@element` and throw an error saying it isn't supported at the moment.

**Comment by JLHwung** [comment]
> One thing I can do is use queueMicrotask to delay the customElements.define() call, and mention a temporary caveat that elements won't be defined until next microtask, requiring existing apps to await a microtask for DOM APIs to be available.

That could work, though of course as you may agree that it is hacky. No worry, I can assure you that bugs in proposal transform will get fixed soon.

**Comment by trusktr** [comment]
> I can assure you that bugs in proposal transform will get fixed soon.

Thank you! 🙏 

Aiming to ship something today nonetheless.

I tried the following but for some reason the error is not caught, still makes it to console:

```js
function element(...) {
  // ...
  try {
    customElements.define(tagName, ElementDecoratorFinisher)
  } catch (e) {
    // this is not reached!
    queueMicrotask(() => customElements.define(tagName, ElementDecoratorFinisher))
  }
}
```

Looks like browsers are doing something funky. This code in Chrome console never logs the catch block:

```js
class MyEl extends HTMLElement {
	foo = __init__foo(123)
}
document.body.append(document.createElement('my-el'))
try {
	console.log('try!')
	customElements.define('my-el', MyEl)
} catch(e) {
	console.log('caught!') // not reached!

	queueMicrotask(() => {
		console.log('try again!')
		window.__init__foo = n => n
		customElements.define('my-el', MyEl)
	})
}
```

But! If we delete the `queueMicrotask`, then the log runs:

```js
class MyEl extends HTMLElement {
	foo = __init__foo(123)
}
document.body.append(document.createElement('my-el'))
try {
	console.log('try!')
	customElements.define('my-el', MyEl)
} catch(e) {
	console.log('caught!') // now it runs!
}
```
