### ISSUE TITLE
Please release @babel/preset-typescript version 7.20

### ISSUE THREAD

**Issue by alesmenzel** [babel/babel#15323]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Cannot use `satisfies` typescript operator because I need @babel/plugin-transform-typescript version 7.20 which is dependency of `@babel/preset-typescript` which was left behind on version 7.18 and not released as part of https://babeljs.io/blog/2022/10/27/7.20.0

### Describe the solution you'd like

Update @babel/preset-typescript to use latest @babel/plugin-transform-typescript and release it.

### Describe alternatives you've considered

.

### Documentation, Adoption, Migration Strategy

.

**Comment by JLHwung** [comment]
Did you try removing the package lock files and install node modules again?

**Comment by alesmenzel** [comment]
Hi @JLHwung , you can see here that latest version is 7.18 -> https://www.npmjs.com/package/@babel/preset-typescript?activeTab=versions

**Comment by JLHwung** [comment]
Duplicate of #15157

**Comment by JLHwung** [comment]
See also https://github.com/babel/babel/issues/15157#issuecomment-1330548945.
If you remove the lock file and install again, npm will pick up the latest `@babel/transform-typescript` which implements the `satisfies` support.

**Comment by alesmenzel** [comment]
aha, thank you, that confused me a bit
