### ISSUE TITLE
strict transformer interpolates "use strict" between ngAnnotate pragma and function body

### ISSUE THREAD

**Issue by AprilArcus** [babel/babel#1533]
I'm using ngannotate's `// @ngInject` pragma to annotate modules for minification:

```JavaScript
// @ngInject
module.exports = function ($scope, $element ...) { ... };
```

which produces

```JavaScript
// @ngInject
module.exports = function ($scope, $element ...) { ... };
module.exports.$inject = ['$scope', '$element' ... ];
```

However, when I pre-process these directives through Babel, the following is emitted:

```JavaScript
// @ngInject
"use strict";

module.exports = function ($scope, $element ...) { ... };
```

which ngAnnotate cannot parse.

I can work around this and I realize that ngAnnotate's pragmas are nonstandard, but it seems like in general it could not hurt for "use strict" to always the the first node in the emitted file, preceding comments.

**Comment by sebmck** [comment]
Can't please everyone :( See #1030 and #1053.
