### ISSUE TITLE
[Bug]: @babel/core@7.20.12 want: ^7.20.12 - does not exists

### ISSUE THREAD

**Issue by ronabet** [babel/babel#15335]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Hi, 
When I try to install babel, babel/core requires a non-existing version of @babel/traverse - 7.20.12.

`silly placeDep node_modules/@babel/core @babel/traverse@ OK for: @babel/core@7.20.12 want: ^7.20.12
`

### Current and expected behavior

Can't run npm install.

### Environment

Babel-version: 7.20.12
System:
    OS: macOS 12.6
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm

**Comment by nicolo-ribaudo** [comment]
That version exists: https://www.npmjs.com/package/@babel/traverse?activeTab=versions
