### ISSUE TITLE
Babel generating ES6 Symbol

### ISSUE THREAD

**Issue by BDiehr** [babel/babel#1534]
I ran into this -- the babel output works fine in Firefox and Chrome, but not in the newest version of IE or Safari. 

The issue in hand is the ES6 Symbol,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

Here is an examble code input and output
```
/** FIRST METHOD (DOES NOT WORK IN IE) */            
               
/** BEFORE BABEL */
let a = [{text:'a'}, {text:'b'}];
for(let el of a) {
        console.log(el);
}
               
/** After Babel */
var a = [{ text: 'a' }, { text: 'b' }];
var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;
 
try {
        for (var _iterator = a[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
                var el = _step.value;
 
                console.log(el);
        }
} catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
} finally {
        try {
                if (!_iteratorNormalCompletion && _iterator['return']) {
                        _iterator['return']();
                }
        } finally {
                if (_didIteratorError) {
                        throw _iteratorError;
                }
        }
}
               
/** SECOND METHOD (DOES WORK IN IE )*/
 
/** Before Babel */
 
for(let el of [{text:'a'}, {text:'b'}]) {
        console.log(el);
}
 
/** After Babel */
 
var _arr = [{ text: 'a' }, { text: 'b' }];
for (var _i = 0; _i < _arr.length; _i++) {
        var el = _arr[_i];
        console.log(el);
}
```

I feel like this is an issue but I could be mistaken. Thanks for reading!

**Comment by sebmck** [comment]
This is expected behaviour. It's impossible to replicate `for...of` without a `Symbol` and iterator polyfill. Babel ships with a version of [core-js](https://github.com/zloirock/core-js) that you can use, see the [docs](http://babeljs.io/docs/usage/polyfill) for more info.

**Comment by DmitrySoshnikov** [comment]
We found this issue as well at FB when switching to Babel. In our previous (jstransform) implementation, instead of:

```javascript
a[Symbol.iterator]()
```

we used to have the check for iterables other then arrays like:

```javascript
a[/*global Symbol*/typeof Symbo l== "function" ? Symbol.iterator : "@@iterator"]()
```

We first tried polyfilling `Symbol.iterator`, however several other libraries got broken, since they tried to create actual symbols (by checking `if (type Symbol !== 'undefined')`). So in our code we end up with the check from above, and custom iterators are implemented as `"@@iterator"` string property.

Not sure how to fix this yet in Babel.

**Comment by DmitrySoshnikov** [comment]
CC @amasad

**Comment by sebmck** [comment]
@DmitrySoshnikov Could you not write a plugin that does `Symbol` transformation for you? 

```javascript
new Transformer("symbol-to-string", {
  MemberExpression: function (node) {
    var obj = this.get("object");
    var prop = this.get("proprety");
    if (this.get("object").isIdentifier({ name: "Symbol" }) && prop.isIdentifier()) {
      return t.conditionalExpression(
        t.binaryExpression("===", t.unaryExpression("typeof", t.identifier("Symbol"), true), t.literal("function")),
        node,
        t.literal("@@" + prop.node.name)
      );
    }
  }
});
```

**Comment by DmitrySoshnikov** [comment]
@sebmck, yeah, potentially. We can try, though, another transform -- another perf hit :( we use whitelist to run only needed things for better performance. The reason we chose `"@@iterator"` because this is how it's called in the spec.

OK, let me try running this additional transform to see how it actually affects the perf.

**Comment by sebmck** [comment]
@DmitrySoshnikov Have you been using the `metadata.group` property? Performance hit _should_ be negligible.

**Comment by DmitrySoshnikov** [comment]
@sebmck, exactly in the process of switching now, updating to the latest Babel version :smile:

**Comment by avindra** [comment]
Is there a way to get Babel to not emit Symbol?

Currently I am requiring the [polyfill](http://babeljs.io/docs/usage/polyfill/), which increases our common bundle (minified, before gzip), by 52KB. This doesn't seem like a smart way to solve the problem.

According to [Symbol via MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol), support for Symbol is in Chrome 38+ and IE doesn't support it at all. We have lots of users with both of those browsers, so we need to be able to polyfill Symbol or get rid of it somehow in our final code.

Am I correct in assuming that babel-polyfill is the only way to get this done?

**Comment by zloirock** [comment]
@avindra 
> Currently I am requiring the polyfill, which increases our common bundle (minified, before gzip), by 52KB. This doesn't seem like a smart way to solve the problem.

You can require only [needed features](https://github.com/zloirock/core-js#commonjs).

**Comment by avindra** [comment]
@zloirock : Thanks, that looks like a step in the right direction. However, it seems like one would still need to discover when Babel emits ES6 code by testing all of their code in different browsers and then polyfilling missing features. Is there an easier way to do this?

**Comment by zloirock** [comment]
@avindra before `babel` 6 was caveats  section in the docs with required polyfills for some transformers, but now I can't find it. I think, something like that will be added in near future.
