### ISSUE TITLE
[Bug]: onlyRemoveTypeImports: true should not remove imports with only inline type specifier

### ISSUE THREAD

**Issue by latin-1** [babel/babel#15348]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
import { type T } from "./mod";
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    ["@babel/preset-typescript", { "onlyRemoveTypeImports": true }]
  ]
}
```

### Current and expected behavior

Current behavior:

```ts
// empty
```

Expected behavior / tsc with `"isolatedModules": true` and `"importsNotUsedAsValues": "error"`:

```ts
import "./mod";
```

### Environment

```
  System:
    OS: Linux 6.1 Arch Linux
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    Yarn: 4.0.0-rc.35 - ~/.local/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @babel/cli: ^7.20.7 => 7.20.7 
    @babel/core: ^7.20.12 => 7.20.12 
    @babel/preset-typescript: ^7.18.6 => 7.18.6 
```

### Additional context

https://github.com/microsoft/TypeScript/issues/47118#issuecomment-993047937

**Comment by latin-1** [comment]
Minimal tsc repro:

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "module": "ESNext",
    "isolatedModules": true,
    "importsNotUsedAsValues": "error"
  }
}
```

```ts
// index.ts
import { type T } from "./mod";
```

```ts
// mod.ts
export type T = number;
```

#### Output

```js
// index.js
import "./mod";
```

```js
// mod.js
export {};
```

**Comment by chbdetta** [comment]
I think this is wrong. `importsNotUsedAsValues`'s default value is `'remove'` according to [here](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) and it'll remove import statements that only contain inline types.

Reproduce repo: https://stackblitz.com/edit/node-waxgo5?file=src/index.ts

In the case where `importsNotUsedAsValues` is set to `'preserve'` or `'error'`, tsc will preserve the import statement but babel shouldn't use that as the default behavior for `onlyRemoveTypeImports: true`. It should instead provide an option to mirror the tsc `importsNotUsedAsValues` option.

**Comment by nicolo-ribaudo** [comment]
`importsNotUsedAsValues: "remove"` is equivalent to _not_ setting `onlyRemoveTypeImports: true` in Babel.
