### ISSUE TITLE
[Bug]: unexpected behaviour for regex with `@babel/plugin-transform-unicode-regex`

### ISSUE THREAD

**Issue by qaisjp** [babel/babel#15357]
### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[→ View on REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBA-gUzKAJgg6gCwJZQRABwENgEYBeAKBhgAoIBKCgPhggDoAnBAgGxIS0A9AG0AegB0AHgCYAjAFppAdgCiEiBKgSwEzgF0hAcwCuAGjrAm5VgAMAZAGIAJAG9g7VAgAKIbGCgAQShaAAYGAF8AblsGKMpKRGQQNCxcfGJSWgAiQF4NwAO9wHg_7IYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.12&externalPlugins=%40babel%2Fplugin-transform-unicode-regex%407.18.6&assumptions=%7B%7D)

```js
const _encodeWhitespace =
  (s) => s.replace(/[^\x21-\x7E\s\t\n\r]/gu, (c) => `&#${c.codePointAt(0)};`);

_encodeWhitespace("🛠️") == '&#128736;&#65039;'
```

And `'&#128736;&#65039;'` correctly renders as 🛠️ in HTML.

### Configuration

The REPL is using `@babel/plugin-transform-unicode-regex` v7.18.6

### Current and expected behavior

The current behaviour is that the below JS is generated:

```js
const _encodeWhitespace = s => s.replace(/(?:(?![\t-\r -~\xA0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF])[\s\S])/g, c => `&#${c.codePointAt(0)};`);

_encodeWhitespace("🛠️");
```

which returns something different `'&#55357;&#57056;&#65039;'`, rendered incorrectly as ��️ in HTML.

I would expect the string returned to be the same as the input code.

### Environment

- Babel REPL is using Babel v7.20.12

**Comment by JLHwung** [comment]
This is an upstream issue, see https://github.com/mathiasbynens/regexpu-core/issues/72.
