### ISSUE TITLE
[Bug]: runtime-corejs3/helpers/regeneratorRuntime.js causes "_regeneratorRuntime is not defined" in chrome 41 with webpack serve mode

### ISSUE THREAD

**Issue by liumulin614** [babel/babel#15350]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

...

### Current and expected behavior

**Current**
When using webpack serve in local development, webpack will use eval to wrap every module's code, but in chrome 41, runtime-corejs3/helpers/regeneratorRuntime.js will causes ReferrenceError: _regeneratorRuntime is not defined. although this error does not occur in webpack bundled code(not using eval to wrap code)

 **expected behavior**
do not cause ReferrenceError

### Environment

chrome41
webpack  4.46.0 (serve mode, using devtool='eval')
runtime-corejs3: 7.20.1

### Possible solution

**this is related to a chrom bug related to eval and strict mode**: [https://bugs.chromium.org/p/chromium/issues/detail?id=177289](https://bugs.chromium.org/p/chromium/issues/detail?id=177289)
 
below is  **runtime-corejs3/helpers/regeneratorRuntime.js** code：
`
function _regeneratorRuntime() {
  "use strict"; /*! regenerator-runtime -- Copyright (c) 2014-present, Facebook, Inc. -- license (MIT): https://github.com/facebook/regenerator/blob/main/LICENSE */
  
  module.exports = _regeneratorRuntime = function _regeneratorRuntime() {
    return exports;
  }, module.exports.__esModule = true, module.exports["default"] = module.exports;
....
`
**suggestions**: remove "use strict" inside **function _regeneratorRuntime**, or add "use strict" in top level of runtime-corejs3/helpers/regeneratorRuntime.js

**Comment by nicolo-ribaudo** [comment]
Could you post the we pack output relative to that regenerator file?
I'm surprised to see that error, because `_regeneratorRuntime` _is_ defined (using `function _regeneratorRuntime`).

**Comment by liumulin614** [comment]
the origin code is large in my project, so i made a simple demo code: [https://github.com/liumulin614/fe-demo/blob/master/eval-babelruntimecorejs4-webpack4-demo.js](https://github.com/liumulin614/fe-demo/blob/master/eval-babelruntimecorejs4-webpack4-demo.js)

src/index.js is:
`import c from '@babel/runtime-corejs3/helpers/regeneratorRuntime';
try {
  console.log(c());
} catch(err) {
  console.error(err);
}`

run the code in chrome41, we can see "_regeneratorRuntime is not defined"

chrome41 can be downloaded from: [https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2F305391%2Fchrome-mac.zip?generation=1416769485193000&alt=media](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2F305391%2Fchrome-mac.zip?generation=1416769485193000&alt=media)

-------
Addtionally,  if using webpack5, the error does not occur. As i mentioned before, this issue seems to be related to a chrome bug(in my chrome 106, the error does occur ):  https://bugs.chromium.org/p/chromium/issues/detail?id=177289

**Comment by JLHwung** [comment]
Thanks for the reproduction repo and the triage information, they are very helpful.

Yes, it is affected by the chrome bug you have mentioned, according to https://bugs.chromium.org/p/chromium/issues/detail?id=177289#c9, the bug had been fixed before Aug 8, 2017 (Chrome < 61). Given that 1) it only affects very obsolete chrome versions, 2) it will not be triggered in production mode (using "eval" kills most optimizations anyway), I would mark this issue as a won't-fix.

**Comment by zloirock** [comment]
`regenerator` used for transpiling generators, they available from Chrome 39 - it's a strange argument that Chrome < 61 is obsolete -)

**Comment by liuxingbaoyu** [comment]
If it could be fixed just by removing `"use strict"` maybe I think it can be done.

**Comment by JLHwung** [comment]
Fwiw the `"use strict"` comes from `regenerator-runtime`: https://unpkg.com/browse/regenerator-runtime@0.13.11/runtime.js

I am not convinced that we should remove the strict mode from upstream library to workaround a v8 bug fixed in 5 years ago.

**Comment by liuxingbaoyu** [comment]
Anyway we've processed and bundled this library, this should be simple and have no bad effects.
https://github.com/babel/babel/blob/f9fbc25b5284d7ad87961128ea883e1d01a0b768/packages/babel-helpers/scripts/generate-regenerator-runtime.js
