### ISSUE TITLE
[Bug]: MemberExpression only allows identifiers on as property

### ISSUE THREAD

**Issue by LiraNuna** [babel/babel#15359]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
memberExpression(stringLiteral('test'), numericLiteral(0))
```

### Current and expected behavior

A `TypeError` is thrown when attempting to create a member expression that is indexed by a numeric literal:

```
TypeError: Property property of MemberExpression expected node to be of a type ["Identifier","PrivateName"] but instead got "NumericLiteral"
```

### Environment

  System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v14.21.2/bin/npm
  npmPackages:
    @babel/generator: ^7.20.7 => 7.20.7 
    @babel/types: ^7.20.7 => 7.20.7 

### Possible solution

Allow `Expression` for `property` in `memberExpression`

### Additional context

When using [AST Explorer](https://astexplorer.net/#/gist/96f996ba9ef51860cd2f43cf5b2d8e78/cd59dbae50ce2e024e040c79693a73c845dbb272) and attempting to parse expressions such as `"test"[0]` and `"hello"["world"]` the results are `MemberExpression(StringLiteral, NumericLiteral)` and `MemberExpression(StringLiteral, StringLiteral)` respectively.

However, when I try to mimic this structure in code, the validators throw an exception, saying only `Identifier` and `PrivateName` are allowed. 

Either I'm missing something obvious or this is an oversight.

**Comment by JLHwung** [comment]
> "test"[0] and "hello"["world"]

They are called computed member expression. To create these types, you must specify the third argument of `t.memberExpression`

```js
memberExpression(stringLiteral('test'), numericLiteral(0), true)
```

See also https://babeljs.io/docs/en/babel-types#memberexpression.

**Comment by LiraNuna** [comment]
Thank you so much, I missed the boolean variable.
