### ISSUE TITLE
regeneratorRuntime is required for `for-of` with `es6.forOf` option

### ISSUE THREAD

**Issue by Constellation** [babel/babel#1535]
When executing `babel` with blacklisted `es6.forOf`, the `for-of` is accidentally transformed and the generated code requires `regeneratorRuntime`.
However, it seems that it is not noted in http://babeljs.io/docs/usage/caveats/.

Steps to reproduce:
1. Execute babel `5.3.3` with  `babel -b es6.forOf`
2. Pass the text to stdin `for (let value of values);`
3. `Ctrl-D`

The result is
```js
"use strict";

for (var value, t$0$0 = regeneratorRuntime.values(values), t$0$1; !(t$0$1 = t$0$0.next()).done;) {
  value = t$0$1.value;
}
```

**Comment by sebmck** [comment]
This would have been consequent of switching to vanilla regenerator. I don't think this behaviour can be disabled. cc @benjamn

**Comment by benjamn** [comment]
I've been considering dropping built-in support for `for`-`of` in Regenerator: https://github.com/facebook/regenerator/issues/186. This issue makes me more confident that's a good idea.

**Comment by sebmck** [comment]
Looks like THIS behaviour was changed via #1536.
