### ISSUE TITLE
[Bug]: @babel/plugin-transform-runtime `regenerator` option no longer works

### ISSUE THREAD

**Issue by buu700** [babel/babel#15367]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
[
    require('@babel/plugin-transform-runtime').default,
    {regenerator: false}
]
```

### Current and expected behavior

Expected behavior: Output references `regeneratorRuntime` global.

Current behavior: `ReferenceError: _regeneratorRuntime is not defined`

### Environment

`babel --version` output:

```
Babel version: 7.20.7 (@babel/core 7.20.12)
```

`envinfo --preset babel` output:

```
  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 18.12.1 - ~/nodejs/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/nodejs/bin/npm
```

### Additional context

I don't know exactly when this broke, but it was working in a previous version.

**Comment by buu700** [comment]
Note: I'm unable to reproduce this issue via the basic Node API:

`node -e "console.log(require('@babel/core').transformSync('const balls = async () => { console.log(await Promise.resolve(0)); };', {plugins: [['@babel/plugin-transform-runtime', {regenerator: false}]], presets: ['@babel/preset-env']}).code)"`

For whatever reason, it seems to be specific to webpack.

**Comment by limingcan562** [comment]
Do you have a screenshot of the result after `Babel` has been compiled? I'd like to see what `Babel` compiles and outputs

**Comment by buu700** [comment]
I don't have a simple example that I can screenshot, but I should have mentioned that the issue was reproducible in an Angular application with several variations of the following patch applied to `node_modules/@angular-devkit/build-angular/src/babel/presets/application.js`:

```diff
164,171c164,170
<         plugins.push([
<             require('@babel/plugin-transform-runtime').default,
<             {
<                 useESModules: true,
<                 version: require('@babel/runtime/package.json').version,
<                 absoluteRuntime: path.dirname(require.resolve('@babel/runtime/package.json')),
<             },
<         ]);
---
>         plugins.push(
>             [
>                 require('@babel/plugin-transform-runtime').default,
>                 { regenerator: false },
>             ],
>             require('@babel/plugin-external-helpers').default,
>         );
```

**Comment by nicolo-ribaudo** [comment]
The reason for this is that now `@babel/plugin-transform-regenerator` itself does not rely on a global `regeneratorRuntime` anymore, and instead it uses "Babel helpers" like any other plugin.
