### ISSUE TITLE
[Bug]: Inconsistent on different `createParenthesizedExpressions` option

### ISSUE THREAD

**Issue by fisker** [babel/babel#15376]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
new (foo?.bar)();
```

### Current and expected behavior

```console
> require('@babel/parser').parse('new (foo?.bar)();', {createParenthesizedExpressions: true})
Node {
  type: 'File',
  start: 0,
  end: 17,
  ...
```

```console
> require('@babel/parser').parse('new (foo?.bar)();')
Uncaught [SyntaxError: Constructors in/after an Optional Chain are not allowed. (1:14)
] {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'OptionalChainingNoNew',
  loc: Position { line: 1, column: 14, index: 14 },
  pos: [Getter/Setter]
}
```

Should behave the same.

### Environment

`@babel/parser: 7.20.13 => 7.20.13`

Don't think other things matters.

### Possible solution

Maybe forgot to strip `ParenthesizedExpression` somewhere.

**Comment by jridgewell** [comment]
Actually, the first is correct and the second is incorrect. Both should be runtime errors, not syntax errors, because `(foo?.bar)` isn't an optional chain anymore.

**Comment by fisker** [comment]
You're right, thanks!
