### ISSUE TITLE
[Bug]: TypeScript compilation throws error on correct program (type inference on array spread syntax?)

### ISSUE THREAD

**Issue by cebamps** [babel/babel#15380]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
const foo = () => {
  const bar = 0 ? mkList() : [];

  return [...bar];
};

function mkList(): any[] {
  return [];
}

export default {};
```

[This REPL session](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MAUBKFA-GBvAKBhlElgCMBDAJxRgAYYB-GAWwGsAZAS2kxgBcMANoBdANwEiMagFMoAV2pgRAOnVVqEggF9JBOArDAo3cGy68omIZTABPMfmlzFykdp1TZADwAOINSwACaycJQKADaweHoEQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.20.14&externalPlugins=&assumptions=%7B%7D) also showcases the issue.

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}
```

### Current and expected behavior

Current behavior: compilation fails with the following log:
```
$ /tmp/babel/node_modules/.bin/babel src --extensions .ts -d build
TypeError: /tmp/babel/src/index.ts: Property types[1] of TSUnionType expected node to be of a type ["TSType"] but instead got "GenericTypeAnnotation"
    at validate (/tmp/babel/node_modules/@babel/types/lib/definitions/utils.js:112:11)
    at validator (/tmp/babel/node_modules/@babel/types/lib/definitions/utils.js:88:7)
    at Object.validate (/tmp/babel/node_modules/@babel/types/lib/definitions/utils.js:188:7)
    at validateField (/tmp/babel/node_modules/@babel/types/lib/validators/validate.js:21:9)
    at validate (/tmp/babel/node_modules/@babel/types/lib/validators/validate.js:15:3)
    at validateNode (/tmp/babel/node_modules/@babel/types/lib/builders/validateNode.js:12:27)
    at tsUnionType (/tmp/babel/node_modules/@babel/types/lib/builders/generated/index.js:1757:36)
    at createTSUnionType (/tmp/babel/node_modules/@babel/types/lib/builders/typescript/createTSUnionType.js:18:39)
    at createUnionType (/tmp/babel/node_modules/@babel/traverse/lib/path/inference/util.js:24:16)
    at NodePath.ConditionalExpression (/tmp/babel/node_modules/@babel/traverse/lib/path/inference/inferers.js:118:36) {
  code: 'BABEL_TRANSFORM_ERROR'
}
error Command failed with exit code 1.
```

Moving the function definition for `mkList` to the top of the file fixes the issue. So does adding a type assertion on line 4: `return [...(bar as typeof bar)];`.

Setting targets to "defaults" in the config also fixes the issue.

### Environment

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    @babel/cli: 7.20.7 => 7.20.7
    @babel/core: 7.20.12 => 7.20.12
    @babel/preset-env: 7.20.2 => 7.20.2
    @babel/preset-typescript: 7.18.6 => 7.18.6
```

### Additional context

This appears to be a regression between 7.17 and 7.18. See [this REPL session](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MAUBKFA-GBvAKBhlElgCMBDAJxRgAYYB-GAWwGsAZAS2kxgBcMANoBdANwEiMagFMoAV2pgRAOnVVqEggF9JBOArDAo3cGy68omIZTABPMfmlzFykdp1TZADwAOINSwACaycJQKADaweHoEQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.17.12&externalPlugins=&assumptions=%7B%7D), where I just changed the version to 7.17.

In the CLI, I can make the compilation succeed with the following package.json file for Yarn:
```json
{
  "devDependencies": {
    "@babel/cli": "~7.17.0",
    "@babel/core": "~7.17.0",
    "@babel/preset-env": "~7.17.0",
    "@babel/preset-typescript": "~7.17.0",
    "typescript": "4.9.4"
  },
  "resolutions": {
    "@babel/types": "~7.17.0",
    "@babel/generator": "~7.17.0",
    "@babel/traverse": "~7.17.0"
  }
}
```

**Comment by liuxingbaoyu** [comment]
This is a legacy issue, `path.getTypeAnnotation()` returns `[TSArrayType,GenericTypeAnnotation]` for `0 ? mkList() : []`.
The first is of type ts and the second is of type flow.
We have two solutions
1. Make sure both types are ts or flow
2. A similar solution to this one allows us to get the type of the current file https://github.com/babel/babel/issues/15262

I personally tend to do both.

PS: I am surprised that we actually deduce the ts type during the conversion process

**Comment by Amatewasu** [comment]
(I am also having the issue with `@babel/core: 7.23.2`.)

**Comment by Amatewasu** [comment]
I found a work around: replace the spread operator (`[...a, ...b]`) with the concat method `a.concat(b)`.
