### ISSUE TITLE
[Bug]: Typescript error -  A binding pattern parameter cannot be optional in an implementation signature

### ISSUE THREAD

**Issue by sebakerckhof** [babel/babel#15396]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```ts
type TParams<T extends boolean> = {
  all?: T;
};

function foo({ all }: TParams<true>): string[];
function foo({ all }?: TParams<false>): string;
function foo({ all = false } = {}) {
  const results = ['a', 'b'];
  return all ? results : results[0];
}
```

### Configuration

I use the online repl: https://babeljs.io/repl# with typescript enabled.

### Current and expected behavior

This code is valid typescript according to TSC (4.9.4) and friends, but babel throws:
`A binding pattern parameter cannot be optional in an implementation signature. (6:13)`

### Environment

I'm running it in the babel online repl: https://babeljs.io/repl (currently version: 7.20.14)

### Additional context

This compiles correctly with `tsc`

**Comment by liuxingbaoyu** [comment]
ts also throws an exception.
![image](https://user-images.githubusercontent.com/30521560/216297806-cf140a90-2890-496e-b37e-49d769eca7c5.png)
https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&jsx=0&isolatedModules=true&ts=4.9.4#code/C4TwDgpgBAKgCgQwE4ILYGcA8MoQB7AQB2AJulAEYD2VANhAkQHxQC8UA3gLABQUUCWrQD8ALlgBuXgF8pPXgDMArkQDGwAJZUiUBTQAUHAUKjTx8ZGizAkSiEwCU49DY1EA5gG0AunOVrNbV0DI0FaUzFYRBQMTAVBdHsnKBckN3c-FXUtHT0qQ2Nw9njaRNM2TmkHTl5+VW0XKCQIdCVaYHJ2TwByBG6AGihuim7fWqaIYCUkHTCoYQnW9vJxZqWOzwAGMZ5pXl58MCokYEqgA

**Comment by sebakerckhof** [comment]
You're right. Somehow tsc doesn't complain in my local setup. But since it complains in their online repl, it'll be down to my local setup. Sorry to have bothered

**Comment by liuxingbaoyu** [comment]
This seems to depend on `strictNullChecks`, not ruled out to be a parser bug.
cc @nicolo-ribaudo @JLHwung
