### ISSUE TITLE
[Bug]: The proposal polyfill "Array.uniqueBy" does not work in ie11

### ISSUE THREAD

**Issue by limingcan562** [babel/babel#15392]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

````js
// index.js
const data = [
    { id: 1, uid: 10000 },
    { id: 2, uid: 10000 },
    { id: 3, uid: 10001 }
]
const final_data = data.uniqueBy(it => it.uid); 
console.log(final_data);
````

Take a look at this [repository](https://github.com/limingcan562/babel-use-proposals-problem) for reproducing the problem

### Configuration file name

babel.config.js

### Configuration

````js
// babel.config.js
const presets = [
    [
        '@babel/preset-env',
        {
            debug: true,
            targets: "ie 11",
            useBuiltIns: "usage",
            corejs: {
                version: '3.27.2',
                proposals: true
            }
        }
    ]
];
module.exports = {presets};


// webpack.config.js
const path = require('path');
module.exports = {
    mode: 'production',
    entry: {
        index: './index.js',
    },
    output: {
        filename: 'dist.js',
        path: path.resolve(__dirname, 'dist/'),
        environment: {
            arrowFunction: false,
        }
    },
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader'
                }
            }
        ]
    },
    optimization: {
        minimize: false,
    }
}


// package.json
"dependencies": {
    "core-js": "^3.27.2"
  },
 "devDependencies": {
    "@babel/cli": "^7.20.7",
    "@babel/core": "^7.20.12",
    "@babel/preset-env": "^7.20.2",
    "babel-loader": "^9.1.2",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1"
 }
````

### Current and expected behavior

I was hoping that Babel would compile the proposal polyfill for me, but after packaging it in Webpack and running it in ie 11, I get the following error.

![error](https://user-images.githubusercontent.com/45028746/216005991-93b6404e-a1e3-4615-bafc-e932a292fba2.png)

### Environment

  System:
    OS: Windows 10 10.0.18363

  Binaries:
    Node: 14.16.1 - D:\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - D:\nodejs\npm.CMD

  npmPackages:
    @babel/cli: ^7.20.7 => 7.20.7
    @babel/core: ^7.20.12 => 7.20.12
    @babel/preset-env: ^7.20.2 => 7.20.2
    babel-loader: ^9.1.2 => 9.1.2
    webpack: ^5.75.0 => 5.75.0

**Comment by liuxingbaoyu** [comment]
Looks like this is a https://github.com/zloirock/core-js issue and babel can't do anything about it.

**Comment by nicolo-ribaudo** [comment]
cc @zloirock

**Comment by zloirock** [comment]
It's a Babel issue, https://github.com/zloirock/core-js/issues/1171#issuecomment-1411896880

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel-polyfills/blob/c395e14f0a88519c82032edb1afd937a29ee5bd3/packages/babel-plugin-polyfill-corejs3/src/index.ts#L187-L199

I did a quick investigation and found that `'esnext.array.unique-by'` is being filtered out here, but I don't know how to fix it.

**Comment by zloirock** [comment]
This filter is harmful in too many cases. In the case of saving this filter, for make it work properly, it will be required to rewrite the definitions and their logic.

**Comment by limingcan562** [comment]
Will it be fixed in the next version?

**Comment by limingcan562** [comment]
I'm sorry, I installed the latest `babel` and this problem still exists.

---

This is my dependent version:
  Binaries:
    Node: 14.16.1 - D:\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - D:\nodejs\npm.CMD
  npmPackages:
    @babel/cli: ^7.21.0 => 7.21.0
    @babel/core: ^7.21.0 => 7.21.0
    @babel/preset-env: ^7.20.2 => 7.20.2
    babel-loader: ^9.1.2 => 9.1.2
    webpack: ^5.75.0 => 5.75.0

This is my `babel` configuration:

````javascript
// babel.config.js
const presets = [
    [
        '@babel/preset-env',
        {
            debug: true,
            useBuiltIns: "usage",
            corejs: {
                version: '3.28.0',
                proposals: true
            }
        }
    ]
];
module.exports = {presets};
````

**Comment by liuxingbaoyu** [comment]
This requires waiting for https://github.com/babel/babel-polyfills to be released.
cc @nicolo-ribaudo
