### ISSUE TITLE
[Bug]: arithmetic overflow occurred while processing enums

### ISSUE THREAD

**Issue by kaikaibenkai** [babel/babel#15410]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```ts
export enum Permission {
  'CREATE_INSTANT_INVITE' = 1 << 0,
  'KICK_MEMBERS' = 1 << 1,
  // ...
  'USE_PRIVATE_THREADS' = 1 << 36,
  'USE_EXTERNAL_STICKERS' = 1 << 37,
}
```

### Configuration

This problem exists in **any configuration**.

### Current and expected behavior

Current: it will overflow if the value <= `2^31`
```js
export let Permission;
(function (Permission) {
  Permission[Permission["CREATE_INSTANT_INVITE"] = 1] = "CREATE_INSTANT_INVITE";
  Permission[Permission["KICK_MEMBERS"] = 2] = "KICK_MEMBERS";
  Permission[Permission["USE_PRIVATE_THREADS"] = 16] = "USE_PRIVATE_THREADS";
  Permission[Permission["USE_EXTERNAL_STICKERS"] = 32] = "USE_EXTERNAL_STICKERS";
})(Permission || (Permission = {}));
```
Excepted:

### Environment

- Babel: 7.19.0
- Node: 16.16.0
- Npm: 8.19.2
- Yarn: 1.22.19

### Possible solution

Using `number` in JavaScript for operation?

### Additional context

I use it [online](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBMAdgVwLZwArCqglgZ31wkTgG8AoOOAcgGEAlAUQEEAVJgfQEkA5AZTYtebHrwBq3DjTgBeOAEY4AHmVwADABoqtANLc6uzgFkmxgEJMG_GfKWrF26gHpncAHSedNAKr8uGAzc4uxcbAASzCwAIjZycABMCgAsAOzJABwAzABsmU60flxMABocDLwsADKcgga6VnF2KmpZqdoAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.20.15&externalPlugins=&assumptions=%7B%7D)

**Comment by liuxingbaoyu** [comment]
https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&isolatedModules=true&ts=4.9.5#code/KYDwDg9gTgLgBMAdgVwLZwArCqglgZ31wkTgG8BYAKDjgHIBhAJQFEBBAFRYH0BJAOQDKHNvw59+ANV5c6cALxwAjHAA8quAAYANNVp0A0rwYHuAWRZmAQiyaC5ileuW6acAPTu4AOl976AKqCPBhMvJKcPBwAEqxsACL2CspqGgDMAGyu+kE8LAAaXEz8bAAy3MLGBrZJjqlwaQDsrgC+QA

This is consistent with the output of ts.

**Comment by nicolo-ribaudo** [comment]
This is also how JavaScript works in general!

**Comment by ehoogeveen-medweb** [comment]
Try using `2**` ("raise 2 to the power of") instead of `1 <<` ("shift 1 left by"). But beware: Javascript numbers have a 53-bit mantissa, so you can't safely use flags above `2**53` (unless you don't use the low bits for flags with the high bits set).

**Comment by kaikaibenkai** [comment]
Using `2 **` is a useful solution at this time, but it is not elegant and will not be regarded as a constant by Typescript, in the fact.

**Comment by ehoogeveen-medweb** [comment]
It shows the right numbers for me on hover in the playground:
https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&isolatedModules=true&ts=4.9.5#code/KYDwDg9gTgLgBMAdgVwLZwArCqglgZ31wkTgG8BYAKDjgHIBhAJQFEBBAFRYH0BJAOQDKHNvw59+ANV5c6cALxwATHABUquAAYANNVp0A0rwYHuAWRZmAQiyaC5ilergBGXTTgB6T3AB0-vXoAVUEeDCZeSU4eDgAJVjYAEXsFZTUNAGYANnd9EJ4WAA0uJn42ABluYWMDWxTHdLgMgHZ3AF8gA

If e.g. `1 << 30` is treated as a constant but `2 ** 30` is not, then I personally think that's a bug.

**Comment by kaikaibenkai** [comment]
I think so too: 
https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBMAdgVwLZwArCqglgZ31wkTgG8AoOOAcgGEAlAUQEEAVJgfQEkA5AZTYtebHrwBq3DjTgBeOACY4AKmVwADABoqtANLc6uzgFkmxgEJMG_GfKWq4ARm3UA9K7gA6bzpoBVfi4MBm5xdi42AAlmFgARGzlFFTUAZgA2F1oAriYADQ4GXhYAGU5BA10rBLtkuBSAdm0AXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.20.15&externalPlugins=&assumptions=%7B%7D

**Comment by liuxingbaoyu** [comment]
Yes, this seems to be an inconsistency with ts, but it should not affect the runtime behavior.

**Comment by ehoogeveen-medweb** [comment]
Ah, I see. Well, browsers should still be intelligent enough to only evaluate these constant expressions once, but it would be nice if babel produced the same code for both operators. I don't know why `1 << 1` is evaluated but `2 ** 1` is not.

**Comment by nicolo-ribaudo** [comment]
@ehoogeveen-medweb Do you want to open a PR adding support for it at https://github.com/babel/babel/blob/9112b8f2bc85eddceb5aa22fe06b760fab6c7c85/packages/babel-plugin-transform-typescript/src/enum.ts#L258, and updating [this test](https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-typescript/test/fixtures/enum/constant-folding)?

**Comment by ehoogeveen-medweb** [comment]
Sure! Might take me a few days to get set up.

**Comment by nicolo-ribaudo** [comment]
Ping me here if you need any help!
