### ISSUE TITLE
Polyfilled methods cannot be accessed from within webworker

### ISSUE THREAD

**Issue by cryptopapi997** [babel/babel#15425]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

https://github.com/cryptopapi997/babel-worker-issue (it's a tiny repo, don't worry ;) )

### Configuration file name

`.babelrc`

### Configuration

```json
{
    "presets": [
        [
          "@babel/preset-env",
          {
            "useBuiltIns": "entry",
            "corejs": "3.22"
          }
        ]
    ],
    "plugins": [
        "@babel/plugin-transform-async-to-generator"
    ]
}
```

### Current and expected behavior

My issue stems from using babel-loader together with the [ffjavascript](https://github.com/iden3/ffjavascript) library whereby I'm applying the asyncToGenerator polyfill. 
My problem comes from the fact that ffjavascript uses webworkers that have their own scope from where they cannot access this polyfill. How these workers are set up can be found [here](https://github.com/iden3/ffjavascript/blob/master/src/threadman_thread.js) and how they are called [here](https://github.com/iden3/ffjavascript/blob/master/src/threadman.js#L116). 

I've created a github repository with a minimum reproducible example linked above. (Note that I have directly imported ffjavascript's index.js file rather than including the npm package to make the webpack part simpler). 

### Environment

```
  System:
    OS: Linux 5.17 Ubuntu 22.04 LTS
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
  npmPackages:
    @babel/cli: ^7.20.7 => 7.20.7 
    @babel/core: ^7.20.12 => 7.20.12 
    @babel/generator: ^7.20.14 => 7.20.14 
    @babel/plugin-transform-async-to-generator: ^7.20.7 => 7.20.7 
    @babel/preset-env: ^7.20.2 => 7.20.2 
    @babel/template: ^7.20.7 => 7.20.7 
    @babel/traverse: ^7.20.13 => 7.20.13 
    babel-loader: ^9.1.2 => 9.1.2 
    webpack: ^5.75.0 => 5.75.0 
```

### Possible solution

The easiest solution would be placing the polyfill declaration inside of the scope of the web worker, but I'm not experienced enough with babel to know how to tell it to do this.

**Comment by cryptopapi997** [comment]
Also FYI - slack invite unfortunately does not work anymore :( 
![image](https://user-images.githubusercontent.com/38372048/218997337-81f0db24-3628-4801-8f22-81b435fa4bfe.png)

**Comment by liuxingbaoyu** [comment]
This doesn't look like a babel-specific issue, though you could try moving these helpers into the `thread` function.

![image](https://user-images.githubusercontent.com/30521560/219021760-3368bbc0-a391-43af-9d54-57c81b2110c4.png)

**Comment by cryptopapi997** [comment]
Thanks for getting back to me so fast - the problem though is that the ffjavascript file you edited is just a copy of ffjavascript's exported index file i.e. I prefer not to edit the file itself as this means editing compiled babel code that stems from node_modules. 

I believe the issue itself is babel-specific because those helpers are generated by babel but are not accessible from within `thread` which runs as a web worker. To me it appears as though babel doesn't seem to understand that web workers run in their own scope and therefore don't have access to polyfills defined at the top level, but I might just be using it wrong.

**Comment by liuxingbaoyu** [comment]
https://github.com/iden3/ffjavascript/blob/d8979c27b2da72aad309283c82b533eb8961a631/src/threadman.js#L50

Here `thread.toString()` is used, which is out of support and babel can't do anything about it.

**Comment by cryptopapi997** [comment]
I see - what would be the correct way to instantiate the worker instead of `thread.toString()` so that babel correctly polyfills the helpers?

**Comment by liuxingbaoyu** [comment]
You can try not to bundle `ffjavascript`, because `thread` is placed in a separate file, which avoids scope issues.

**Comment by cryptopapi997** [comment]
Thanks, let me try this and get back to you

**Comment by cryptopapi997** [comment]
Exactly, I'm gonna try running it from source without bundling and see if that works first

**Comment by cryptopapi997** [comment]
Ok just tried importing from source (also pushed it to my demo repo linked above if you want to have a look) - unfortunately still the same error :(

**Comment by cryptopapi997** [comment]
> https://github.com/iden3/ffjavascript/blob/d8979c27b2da72aad309283c82b533eb8961a631/src/threadman.js#L50
> Here thread.toString() is used, which is out of support and babel can't do anything about it.

Wouldn't be surprised if that's because of this and babel therefore not understanding it's dealing with a web worker - do you know how to correctly instantiate web workers so babel understands it?

**Comment by liuxingbaoyu** [comment]
Sorry for giving a wrong suggestion.
This seems a bit tricky, there doesn't seem to be a very good way to have babel do this automatically.
Unless you write a babel plugin, or manually copy-paste them.

**Comment by cryptopapi997** [comment]
Do you mean there is no good way to do this with babel when a worker is part of a bundle or when using a worker in general?

**Comment by liuxingbaoyu** [comment]
Yes, unless you're willing to write a custom plugin.
Helpers will always be hoisted to the top, and ts is the same.

[ts](https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&target=0&isolatedModules=true&ts=4.9.5#code/PQKgBA5gNg9gRgQymA6gUzgQQM7bQWzigE8wRgBYAKGrQA8AHGAJwBcwATNAMwQFco7bnwB2AY1YBLGCLCsAFszQIOACjxRuASjABvamENgxM7OwCymABrmAoubABeMAGYATAHYAbB4DcBoyg0dkkRMwRxNH8qIzAg9nwCFmJogMNJbjB1NE0dfRjYow1uADoZRNwECDQnMGFxKRlVNDy0wtj4zgRWBGj29oystBKOboRWgv7+0Z7a4ZnetqmAXzAcvD0lqaMFub7tw2XqLYHM1QWAbQAGAF0SsXwOJ2cAIgBJADk3gBUXiYOBiJJKxzmNrjctCUFGgRKp6hJpLD-gCpsUSkwzOY0JVqqCeiUlNgBKwtPsUYdSSdCqt1jVBniEOD7o9nmAXt9bAAlcyfTAcv6bSbktFiWB4VSUoUrNZQDb5clGExhdiE2rMUTfBDYADWDMlCsMaIxrCxOLQqkJ+oBRylRmWZLANraWuI4jqogRMjAoWBesFUyVZmMMC4tREaAA7mAAKqhVgADkwzGYCGIDPuIZaDtigfYEa1+HMIYENWcCHzwNQGBweEIJAz+AYkiCqhMXCt7US+GSYcjVawuAIRGIJSx3eYad0PqkSAAXAsStOADRgfAIOiSfB8fCzsCWGz2ZaSqmhcKRWrlhCV9AD2vDxfKiIz1jm-PYQvFoIr+UAmEAN13H8FReLtkheXdQInKlYhtFYO0dY4aCQ2J4UaWQkFgMRVCCEQIAUZF2lzMA+HcXso1jERWHcJMUzTSCRzgPhuG4NBmBXK4VwARng2II3kZsalUEi3HBMAADJXB0YTwQAahk3xDGAYAwE5YI+GYdCoHzYhsDAJBJAgcMniYONWOwKkiNVZxpNubMjBsm4wBk5wcLw+Q7PSM4HKcuIYTcsAAD5VySCcSkY5jWLC4gXwAGT8-D-QBIixHUpRKIABSqbFanosKmJY5goti+L5DAZSrjoTirmqq4PMKTolAARz4SQlA4TLql05xzG6eQSm4WAWFUIT3FEmTfNwhLysqmqri0GTOLq2J6Salq2o67EAv3OxzB0VbWrQdqsuwRxtvsJajFyiBmBgCMLTQZqDqOzqAFoUuTGFWA27AeLtKklFYdTZEJB0nSFVDET0qBMIAIXy1jVHCgqCMKIiGAvaGYCwpHIrgaK0Diyb5F+w1gjhiLmFUBgVxx5gSbAAGgbABhQcQlCPTQyAyfhymTMo1iV1chKgNR0x2D4eMyJjONE2TVNVFy2n6cZjSwHDciZZo+WJbyimVx1vGXwAeWYvB2HGvmXzYia3PgsH2YaSGzfJgqqZgUzraVxLCLF4jJecdXpco2XaIVkKGJ5+mdbN1RA4ohMtbTJWV0t1i7bZowIa9dURE1HVVB6HUUeWs5C+1JkHieRxXk+H4BRFqYVdkacC61cvbnp2D+mS1g6FqBv+j-BBmGwXcLhuJdoKMGA+FYMebipe0LN94SECl+PqLlujw91gr2K4+miJgKAOEwTGxFqVfwTq7gWCyTpJEcWrvQAHjLkohfc705OL-psAjYEYhSqtx1BcSQdxK6-0IlqGoLxMAxRikbAAwgAZVsL8WcU9CK9xKEPEeFwy5gLuHgxyZZz4uwRoQ8Bu96ZTDgEoBA2oLqGDEDAtk8DEFIPAlg1GOC8HYAIW3IhuDh6kKhphEB5dqE4Vof0ehygmE8NYRsF4aCME8NiM7HmrY+HDwEVQ4hoiVwGJocwwo8jGFmOUbApBHDwLe3JGjYeCB8BdTAOPMxKE77YWCGAAAVk-BSfi35COoQwZxriP4lSCT-BxBpgzKmZrUEx4SUyuIuH4m4nj+j0lYMQBgaAYCZAYCI5gYAACE1c2SiC4NwUIh164aIBKklx2B0R8GwPIHRdBSkCJKSQnyVMyim18QAH1GWAOasiDg0llHSUu+TCnFJEcgSp1SRC1PqRwRptp4mGBaZEhgHSun9KQNM7YXcFSXPJKeHokQSj0CYGwfRoS7jcBEB8FxaAbiqBKH8g5P1smGAsYo3Z1IlFsJeAAcXQdwsFAYcEz1YII0B1CkViOqKwChlMJA9P4SiqRhjmATzkK8qJIhITYCgJIMQ5pzmxBBWY2p-BBCYPhf0BQN0oyB1sMmIa7wRBD2pU8SufwzHXJgsvRJwk4DrzjJvUOiseb7zANxOqMrRLOGPqfc+dUm7GERbPVmSE2j6pznnUFNogA)

**Comment by cryptopapi997** [comment]
Ah shit - I assume you're not aware of any existing plugins that might do this? 😅

**Comment by liuxingbaoyu** [comment]
Yes.

**Comment by nicolo-ribaudo** [comment]
Web workers have nothing to do with this, the problem is that `ffjavascript` converts functions to strings and then evals them (technically, it doesn't use `eval` but it creates a `text/javascript` data URL, but it's equivalent).

Take this example:
```js
function createFunction() {
  return function () {
    console.log("Hi! I'm Nicolò");
  };
}

const myFunctionString = createFunction().toString();
const myFunction = eval("(" + myFunctionString + ")");

myFunction(); // logs "Hi! I'm Nicolò"
```

This (which is what `ffjavascript` is doing) _seems_ to work, but as soon as the function captures a variable it breaks:
```js
function createFunction() {
  let name = "Nicolò";
  return function () {
    console.log("Hi! I'm " + name);
  };
}

const myFunctionString = createFunction().toString();
const myFunction = eval("(" + myFunctionString + ")");

myFunction(); // ReferenceError: name is not defined
```

What Babel is doing is exactly what I did in the second example, which is perfectly valid according to JS semantics: functions can capture variables from the outer scope. The solution is that `ffjavascript` shouldn't stringify their code, but rather it should either already include it as a string in their bundle.

**Comment by cryptopapi997** [comment]
Thanks Nicolo! If I understand you correctly, the fix would be to copy-paste the whole code that's meant to run inside the worker into one long string and instantiate the worker with that. If that's the case, that's a problem for me though, because that means I'd be effectively telling babel to ignore that code and so if I use babel to compile my project to a build that should run on e.g. a version of javascript that doesn't support async-await, it won't actually run there because my stringified code still includes async-await because babel didn't polyfill it.

**Comment by cryptopapi997** [comment]
Any suggestions regarding this @nicolo-ribaudo @liuxingbaoyu

**Comment by liuxingbaoyu** [comment]
I suggest you write a custom plugin to achieve it.

**Comment by cryptopapi997** [comment]
For my specific use case I found a different workaround, but thanks so much for your help nonetheless :D - might be good to add this feature in the future though, to allow for poly filling web workers
