### ISSUE TITLE
[Bug]:  babel/parser parse typescript file error 「Unexpected token ':'」

### ISSUE THREAD

**Issue by GoFzy** [babel/babel#15420]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from '@babel/parser';

  const schemaAST = parse(*****, {
    sourceType: 'module',
    attachComment: false,
    allowImportExportEverywhere: true,
    plugins: ['typescript']
  });
```
![image](https://user-images.githubusercontent.com/46565627/218392384-2c1266b2-faef-44bf-b6aa-366f3f0e1411.png)

### Current and expected behavior

Current: Typescript files cannot be parsed by@babel/parser now

### Environment

- "@babel/parser": "^7.20.3",

**Comment by liuxingbaoyu** [comment]
Please post the input code that is causing the error.

**Comment by GoFzy** [comment]
> Please post the input code that is causing the error.

```ts
interface Test {
  a: number;
}

const schema: Test = {
  a: 1,
};

export default schema;
```

**Comment by nicolo-ribaudo** [comment]
Does that error have a stack trace?

**Comment by GoFzy** [comment]
> Does that error have a stack trace?

Sorry, I found out it was my usage error
