### ISSUE TITLE
[Bug]: bundle exec error which should output a dependency tree built by rollup,  ansiStyles.color.close

### ISSUE THREAD

**Issue by fionaInBits** [babel/babel#15421]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

source code
```js
import traverse, { NodePath } from '@babel/traverse';
import { transformFileSync } from '@babel/core';

...

  routeEntry?.forEach(routePath => {
    const fullPath = resolvePath({ filePath: routePath });
    const res = transformFileSync(fullPath, TRANSFORM_OPTIONS);
    log('路由AST:', res?.ast);

    // 变量字典, 用于根据组件名获取importPath
    const cmpPathDict = getCmpPathDict(res?.ast);

    // 遍历ast
    traverse(res?.ast, {
      // <Component />
      JSXElement($path) {
        attachNode($path, cmpPathDict, routePath);
      },

      // <></>
      JSXFragment($path) {
        attachNode($path, cmpPathDict, routePath);
      },
    });
  });
```

rollup.config.js
```js
import { babel } from '@rollup/plugin-babel'
import commonjs from '@rollup/plugin-commonjs'
import json from "@rollup/plugin-json"
import resolve, { nodeResolve } from '@rollup/plugin-node-resolve'
// import replace from '@rollup/plugin-replace'
// import uglify from 'rollup-plugin-uglify'
// import shebang from 'rollup-plugin-shebang-bin'

const extensions = ['.js', '.jsx', '.ts', '.tsx', '.vue']
export default {
  input: './src/index.ts', // 入口文件
  output: {
    file: './dist/node/index.cjs', // 出口文件
    name: 'index', // 出口文件
    format: 'cjs' // 输出的模块语法格式
  },
  plugins: [
    babel({ 
      babelHelpers: 'bundled',
      exclude: 'node_modules/**',
      extensions,
      presets: [
      '@babel/preset-env',
      '@babel/preset-typescript'
      ],
  }),
    commonjs(),
    resolve({
        mainFields: ['module', 'main', 'jsnext:main', 'browser'],
        extensions,
        customResolveOptions: {
          moduleDirectories: ['node_modules']
        }
    }),
    nodeResolve({
        exclude: 'node_modules/**',
    }),
    json(),
    // replace({
    //   "const shebang = '#!/usr/bin/env node'": JSON.stringify('#!/usr/bin/env node')
    // })
    // uglify.uglify()
    // shebang(),
]
}
```

### Current and expected behavior

in development mode, it runs well
```js
 "dev": "node -r ts-node/register src/index.ts",
```

but after bundle with rollup, the output runs with error

/Projects/dependency-analysis/dist/node/index.cjs:28410
                ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                                          ^
TypeError: Cannot read properties of undefined (reading 'close')
    at /Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:28410:77
    at requireChalk (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:28567:3)
    at requireLib$b (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:28588:15)
    at requireLib$a (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:28706:19)
    at requireParse$2 (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:43979:19)
    at requireString (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:44285:15)
    at requireBuilder (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:44391:16)
    at requireLib$8 (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:44467:17)
    at Object.<anonymous> (/Users/liangfangfang/Projects/dependency-analysis/dist/node/index.cjs:44497:19)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)

I figured out that the code is in ansi-styles v3.2.1 which is referred by chalk v2.0.0, and chalk v2.0.0. is referred by @babel/highlight -> @babel/code-frame -> @babel/core。

Notification:  in my package.json, type is set to "module". I wonder if the error occurred because chalk v2.0.0 does not support  esmodule mode.

Is there a workaround ?

### Environment

 "@babel/core": "^7.20.12",
"@babel/plugin-syntax-decorators": "^7.19.0",
"@babel/runtime": "^7.20.13",
"@babel/traverse": "^7.20.13"

node --version
v18.14.0

**Comment by liuxingbaoyu** [comment]
It looks like babel can't do anything about it, you can try https://github.com/rollup/rollup/issues.
