### ISSUE TITLE
Turn off warnings

### ISSUE THREAD

**Issue by amasad** [babel/babel#1543]
Anyway to turn off warnings like this: `[BABEL] Note: The code generator has deoptimised the styling of "`

**Comment by amasad** [comment]
I'm basically turning on compact mode to get around this warning basically. Also, I found that there it isn't buying me much in perf.

**Comment by sebmck** [comment]
That's basically the only way to disable it. `compact` defaults to `"auto"` which is what picks this limit. The code generator will take like 30s (IIRC) to generate a 2MB file without it and it was a stopgap solution until the performance on large files addressed. Although something magical may have happened that fixed the performance for really large files.

**Comment by amasad** [comment]
Ok, how do I simply not show the warnings for my users?

**Comment by sebmck** [comment]
Just set `compact` to `true` or `false`.

**Comment by amasad** [comment]
:+1:

**Comment by amasad** [comment]
btw, I was wrong. There is a bit of speed improvement when `compact` is `true`. Not that big though.
