### ISSUE TITLE
[Bug]: Different compat data for `?.` between Babel and caniuse

### ISSUE THREAD

**Issue by rejas** [babel/babel#15447]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

`foo?.()
`

### Configuration file name

babel.config.json

### Configuration

```
{
  "presets": [
    ["@babel/preset-env", { "useBuiltIns": "usage", "corejs": "3", "debug": true }]
  ]
}

```

### Current and expected behavior

According to https://caniuse.com/mdn-javascript_operators_optional_chaining the operator is supported from (for example) chrome v80 onward.

When running babel on code that uses this operator the debug output states:

  proposal-optional-chaining { chrome < 91, edge < 91, opera < 77, samsung < 16 }

So even we have "modern" browsers only in our browserslist.rc the code is transpiled :-( So where does the discrepancy between babel and caniuse come from?

Current behaviour:
the ?.operator gets transpiled

Expected:
the ?.operator wouldn't have to be transpiled

### Environment

  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.2.3 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Monorepos:
    Yarn Workspaces: 3.2.3
  npmPackages:
    @babel/core: ^7.20.12 => 7.20.12 
    @babel/preset-env: ^7.20.2 => 7.20.2 
    babel-loader: ^9.1.2 => 9.1.2 
    webpack: ^5.75.0 => 5.75.0 

### Additional context

Our browserslist.rc

```
last 2 major versions
last 2 years
> 1%
not dead
not bb > 0
not and_uc > 0
not and_qq > 0
not baidu > 0
not ie > 0
not ie_mob > 0
not kaios > 0
not op_mob > 0
not op_mini all
```

**Comment by nicolo-ribaudo** [comment]
Our compat data source is https://kangax.github.io/compat-table/es2016plus/.

Checking https://github.com/kangax/compat-table/blob/b4bdfa42cb7199e26a740ae678c33ce1dde78350/data-es2016plus.js#L4647, it looks like the problem is that [this test](https://github.com/kangax/compat-table/blob/b4bdfa42cb7199e26a740ae678c33ce1dde78350/data-es2016plus.js#LL4784C16-L4784C57) fails in Chrome 90.

**Comment by rejas** [comment]
Thanks for the feedback @nicolo-ribaudo 

So is this test something that needs fixing or what is the open question here?

**Comment by JLHwung** [comment]
Chrome < 91 is affected by a bug related to optional chaining, so the support data is bumped to Chrome 91. You can tell Babel to only apply optional chaining transform when your code is actually affected by this bug:

```js
{
  "presets": [
    ["@babel/preset-env", { "useBuiltIns": "usage", "corejs": "3", "debug": true, "bugfixes": true }]
  ]
}
```

**Comment by rejas** [comment]
Thanks for the information, was very useful. Will try the bugfixes option to see if it helps us.
