### ISSUE TITLE
[Bug]: @babel/core  dependencies  "module"  but not in the package.json

### ISSUE THREAD

**Issue by luzhiy123** [babel/babel#15446]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/core  (webpack)

### Input code

code include module
https://github.com/babel/babel/blob/main/packages/babel-core/src/index.ts

![image](https://user-images.githubusercontent.com/13360151/220272571-4dd9a70f-08bf-4969-89a1-daa1b67f6cb7.png)

dependencies

"dependencies": {
    "@ampproject/remapping": "^2.2.0",
    "@babel/code-frame": "workspace:^",
    "@babel/generator": "workspace:^",
    "@babel/helper-compilation-targets": "workspace:^",
    "@babel/helper-module-transforms": "workspace:^",
    "@babel/helpers": "workspace:^",
    "@babel/parser": "workspace:^",
    "@babel/template": "workspace:^",
    "@babel/traverse": "workspace:^",
    "@babel/types": "workspace:^",
    "convert-source-map": "^1.7.0",
    "debug": "^4.1.0",
    "gensync": "^1.0.0-beta.2",
    "json5": "^2.2.2",
    "semver": "condition:BABEL_8_BREAKING ? ^7.3.4 : ^6.3.0"
  },

### Current and expected behavior

pacakage.json  dependencies include module

### Environment

 7.21.0

**Comment by yinsang** [comment]
@nicolo-ribaudo  Horrible Bug.

**Comment by Hzy0913** [comment]
npm i module -D， fixed my problem

**Comment by nicolo-ribaudo** [comment]
It's a built-in Node.js library, like `require("fs")` and `require("http")`: you don't need to install it. What error are you getting?

**Comment by nicolo-ribaudo** [comment]
Additionally, in the published version of Babel the `"module"` built-in module is never loaded. That import statement is compiled to this code:
```js
function _module() {
  const data = require("module");
  _module = function () {
    return data;
  };
  return data;
}
```
and the generated `_module` function is never called.

**Comment by ehoogeveen-medweb** [comment]
@nicolo-ribaudo It looks like the `module` API was added in Node.js version 12 ([v12 docs for `module`](https://nodejs.org/docs/latest-v12.x/api/module.html); [v11 docs have a page for `modules`](https://nodejs.org/docs/latest-v11.x/api/modules.html) but not `module`), so maybe this is about older versions of Node.js? Though what you said about `_module` not being called should still hold.

**Comment by EgoziE** [comment]
@nicolo-ribaudo I'm also getting an error after updating babel core 😵‍💫 
`Module not found: Error: Can't resolve 'module' in '/node_modules/@babel/core/lib'`
How can I trace what the real problem is?

Using node 16.19.1

**Comment by nicolo-ribaudo** [comment]
What version of `@babel/core` are you using? Do you get that error when running Babel, or when bundling it?

**Comment by EgoziE** [comment]
My `@babel/core` version is `^7.21.0` (updated from `7.20.12`)
It is used internally in Storybook, which is failing with this error when running or building.

I found a bad workaround that works.
When I inject this to my Storybook webpack configuration:
```
config.plugins.unshift(
    new webpack.IgnorePlugin({ resourceRegExp: /module$/ }),
);
```

I would rather not use it of course 🤷🏼‍♂️

**Comment by udit1994** [comment]
I am also facing the same issue, 
node version: 16.18.
@babel/core: ^7.20.12

I have tried upgrading the version, still no luck.

**Comment by nicolo-ribaudo** [comment]
Can you share your lockfile?
