### ISSUE TITLE
[Bug]: Array.prototype.at not included in `useBuiltIns: 'usage'` 

### ISSUE THREAD

**Issue by victor-wm** [babel/babel#15455]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code
```
window.console.log([].at(0));
window.console.log([].map(() => {}));
```

### Configuration

```json
{
   "plugins":[
      "@babel/plugin-transform-runtime"
   ],
   "presets":[
      [
         "@babel/preset-env",
         {
            "useBuiltIns":"usage",
            "corejs":3
         }
      ]
   ],
   "cacheCompression":false,
   "sourceType":"unambiguous"
}
```

### Current and expected behavior

```Using polyfills with `usage-global` method:

[/Users/vnascimento/work/WBD/wbd-beam-typescript/apps/beam-ctv-webos/lib/bootstrap.js]
The corejs3 polyfill added the following polyfills:
  es.array.map { "chrome":"38" }
```

While we would expect it to detect `es.array.at { "chrome":"38" }` as well


### Environment

"@babel/core": "^7.21.0",
"@babel/plugin-transform-runtime": "^7.19.6",
"@babel/preset-env": "^7.20.2",
"@babel/preset-react": "^7.18.6",
"@babel/runtime": "^7.20.7"
"babel-loader": "~8.2.5",
"babel-preset-solid": "^1.6.9",
"core-js": "~3.28.0",

### Possible solution

_No response_

### Additional context

_No response_

**Comment by zloirock** [comment]
Use `"corejs": "3.28"`.

**Comment by victor-wm** [comment]
Thanks @zloirock - do you know whether it's possible to make the build fail if a polyfill is not found?

**Comment by zloirock** [comment]
I'm not sure what you mean and how that it's possible -)

**Comment by victor-wm** [comment]
For example, the fact that `.at` was not detected makes it fail in runtime, but it would be nicer if, while transforming the code, babel understood that `.at` is not supported in our target and there's no polyfill available (because of a misconfiguration) and errored out instead of just producing the output.

**Comment by zloirock** [comment]
It's not possible since it can be defined in userland, static detection is not perfect and the language standard is not a constant.

**Comment by zloirock** [comment]
It can partially be solved on the TypeScript layer - however, it's not related to polyfills.
