### ISSUE TITLE
Not seeing 7.21.1 - in yarn add - but it shows as release ?

### ISSUE THREAD

**Issue by billnbell** [babel/babel#15453]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

NOPE

### Current and expected behavior

NOPE

### Environment

ALL

**Comment by nicolo-ribaudo** [comment]
We only release packages that have actual changes, so for 7.21.1 you'll only find these: https://github.com/babel/babel/commit/fa773138848bee9ae0e6b2e1dc65e2a544052bf8

All the other packages have not been released because they had no changes since 7.21.0.
