### ISSUE TITLE
[Bug]: Object can be Array deconstruction

### ISSUE THREAD

**Issue by wangfpp** [babel/babel#15452]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
   /**
   * @param { Object } row 
   **/
   function  showMasterPicture(row) {
        const pictureList = [...row]; // I know this sentence code is wrong babel should not make the decision for me to convert but throw an error directly
        const status = pictureList.filter((item) => {
          return item.masterFlag == 1;
        })[0];
        if (status) {
          return row.masterPictureUrl;
        }
        return row.masterPictureUrl;
      }
// babel convert code 
showMasterPicture: function (e) {
    [].concat(S(e)).filter(function (e) {
      return 1 == e.masterFlag;
    })[0];
    return e.masterPictureUrl;
  }
  function S(e) {
      if (Array.isArray(e)) {
        for (var n = 0, t = Array(e.length); n < e.length; n++) t[n] = e[n];
        return t;
      }
      return Array.from(e);
    }
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
};

```

### Current and expected behavior

throw error

### Environment

- Babel version(s): [7.20.5]
- Node: [Node 14]
- npm/Yarn version: [npm 7]
- OS: [Windows 10]

**Comment by JLHwung** [comment]
It seems to me you have somehow enabled the loose mode of the array destructuring transform, specifically the assumption [`iterableIsArray`](https://babel.dev/docs/assumptions#iterableisarray).

AFAIK `@vue/cli-plugin-babel/preset` does not enable the loose mode. Do you have other Babel configs not mentioned before?
