### ISSUE TITLE
[Bug]:  BABEL_PARSER_SYNTAX_ERROR on Windows if parse code include "utils" 

### ISSUE THREAD

**Issue by mqliutie** [babel/babel#15457]
### How are you using Babel?

- @babel/parser

### Input code

```js
import path from 'path';
import { parse } from '@babel/parser';

const correctPath = path.join('utils');
const errorPath = path.join('prefix', 'utils');

const code = `console.log('${errorPath}');`;
const ast = parse(code);
```

### Configuration

do not need configutation, You can copy my code and execute it by ts-node

### Current and expected behavior

Throw error

Because I want to print my file name which includes "utils" like "myApp/browser/utils/getName.ts" 

I think it should not throw this error

### Environment

- babel/parser 7.16.12

**Comment by mqliutie** [comment]
This error only throwed on Windows platform

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/220818260-536de07e-cdf3-433f-a5f7-ce3d56850eb7.png)
https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=entry&corejs=3.21&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUByAOgVwC4Etp0BKAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-4&version=7.21.1&externalPlugins=&assumptions=%7B%7D

This is expected.

**Comment by JLHwung** [comment]
```diff
--- const code = `console.log('${errorPath}');`;
+++ const code = `console.log('${JSON.stringify(errorPath)}');`;
```

should work as expected, since you should double escape `\` for it to be a valid escaped JS string.
