### ISSUE TITLE
[Bug]: Spreading a set incorrectly transpiles to [].concat(set, [value])

### ISSUE THREAD

**Issue by mnpenner** [babel/babel#15463]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```ts
function setAppend<T>(set: Set<T>, value: T) {
   return new Set([...set, value])
}
```

### Configuration file name

N/A. Can repro in repl

### Configuration

![image](https://user-images.githubusercontent.com/1112998/221451012-d0be07bc-0646-420f-aef5-440c18286844.png)

(Aside: If there was a button in the repl to show the config as JSON from that, I'd happily share it)

### Current and expected behavior

Current:

```js
function setAppend(set, value) {
  return new Set([].concat(set, [value]));
}
```

Expected:

```js
function setAppend(set, value) {
  return new Set([].concat(Array.from(set), [value]));
}
```

I guess? Basically don't assume `set` is an array. 

### Environment

https://babeljs.io/repl#?browsers=%3E%200.2%25&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABAZwKZQIIAcurAEwB4AVAPgAo0oAuRAZXRNIBpEA3AQwBsRVbiAlIgDeAKEQSATuhCSkYVAHd66cgG0AdFqqtOPVAF0BogL6jREBMjhdUGrnADmldNlwFyC5QyjqAjMwATMwAzEbMACyBAgJAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.21.2&externalPlugins=&assumptions=%7B%7D

### Possible solution

Wrap all spread objects in `Array.from()` or similar.

### Additional context

These give very different outputs:

```
> s = new Set([1,2,3])
Set(3) { 1, 2, 3 }
> new Set([...s,4])
Set(4) { 1, 2, 3, 4 }
> [].concat(s,[4])
[ Set(3) { 1, 2, 3 }, 4 ]
```

Noticed my app was doing something weird and couldn't figure it out until I turned off source maps.

**Comment by mnpenner** [comment]
Update: it does give correct output without `loose` at the expense of much bigger output. I think that's a little too loose still.

And it is documented: https://babeljs.io/docs/babel-plugin-transform-spread#options so that's good.

**Comment by lxfljw** [comment]
It has a way to resolve this problem, transform to Array, like this `new Map([...Array.form(new Map({},{}))])`
