### ISSUE TITLE
[Bug]: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`

### ISSUE THREAD

**Issue by kiran-chauhan-rapidops** [babel/babel#15466]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Stack trace

```
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
  at isModuleDeclaration (/home/project/node_modules/@babel/types/lib/validators/generated/index.js:3940:35)
  at NodePath.<computed> [as isModuleDeclaration] (/home/project/node_modules/@babel/traverse/lib/path/index.js:241:12)
  at PluginPass.addHelper (/home/project/node_modules/@babel/core/lib/transformation/plugin-pass.js:36:22)
  ...
  ...
  ...
  at buildCreateElementOpeningElementAttributes (/home/project/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:507:144)
  at buildCreateElementCall (/home/project/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:446:64)
  at PluginPass.exit (/home/project/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:189:26)
```

### Current and expected behavior

This warning should not come.

### Environment

- Node: 16.16.0
- npm: 8.11.0
- eslint: 8.14.0

### Additional context

This error is coming in one of the existing React project created using `create-react-app`. Following is the chain of the packages depends on -

`eslint-config-react-app > babel-preset-react-app > @babel/preset-react > @babel/plugin-transform-react-jsx > @babel/types`

**Comment by nicolo-ribaudo** [comment]
Could you share your lockfile, to know the versions of the various Babel packages?

**Comment by nicolo-ribaudo** [comment]
Also, make sure that you have at least version 7.20.7 of `@babel/traverse` and `@babel/helpers`, when we removed usage of the deprecated function. If they are older, delete these two packages from your `package-lock.json`/`yarn.lock`/`pnpm-lock.yaml` file and re-install your deps.

**Comment by Codex-** [comment]
Bumping your lock version to `>=7.20.7` doesn't seem to resolve this as it still seems to be present in the current version:
```json
    "node_modules/@babel/traverse": {
      "version": "7.21.2",
      "resolved": "https://registry.npmjs.org/@babel/traverse/-/traverse-7.21.2.tgz",
      "integrity": "sha512-ts5FFU/dSUPS13tv8XiEObDu9K+iagEKME9kAbaP7r0Y9KtZJZ+NGndDvWoRAYNpeWafbpFeki3q9QoMD6gxyw==",
      "dependencies": {
        "@babel/code-frame": "^7.18.6",
        "@babel/generator": "^7.21.1",
        "@babel/helper-environment-visitor": "^7.18.9",
        "@babel/helper-function-name": "^7.21.0",
        "@babel/helper-hoist-variables": "^7.18.6",
        "@babel/helper-split-export-declaration": "^7.18.6",
        "@babel/parser": "^7.21.2",
        "@babel/types": "^7.21.2",
        "debug": "^4.1.0",
        "globals": "^11.1.0"
      },
      "engines": {
        "node": ">=6.9.0"
      }
    },
```

**Comment by zeroimpl** [comment]
I just had same issue after installing `@babel/preset-typescript` to an existing project, but then doing `npm update` resolved it.

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/pull/15484 should fixed this.

**Comment by benomatis** [comment]
I still see the warning on core v7.21.8...

    "@babel/core": "^7.21.8",
    "@babel/eslint-parser": "^7.21.8",
    "@babel/preset-react": "^7.18.6",

**Comment by nicolo-ribaudo** [comment]
The warning still appears in case third party code (i.e. not code controlled by us, either now or in the past) uses the deprecated API.
