### ISSUE TITLE
[Feature] Run babel on specific file

### ISSUE THREAD

**Issue by mohit217** [babel/babel#15471]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

I am trying to run Babel on a specific file using babel.config.js but couldn't find out a way to do it. I saw a way to do it https://babeljs.io/docs/options#test using this option but it doesn't use the option and runs on everything.

I found a work around for this here, https://github.com/babel/babel/issues/5420#issuecomment-285379119 but I want to use just babel instead of webpack.

### Describe the solution you'd like

Use test at top level for plugin options.

### Describe alternatives you've considered

https://github.com/babel/babel/issues/5420#issuecomment-285379119

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/options#only

Are you looking for it?

**Comment by mohit217** [comment]
@liuxingbaoyu I want to run a specific plugin only for a specific file.

**Comment by JLHwung** [comment]
> I want to run a specific plugin only for a specific file.

Let specific file denoted by `foo.js`, if you really want to isolate `foo.js`'s config from other sources, you can create a new Babel config file (`foo.babel.config.json`) just for that `foo.js`. And then add a new pass to your build commands:

```sh
npx babel --config-file foo.babel.config.json --out-dir ./foo-output.js ./foo.js
```

In your main Babel config, you should ignore `./foo.js`:

```json
{
  "ignore": "./foo.js"
}
```
