### ISSUE TITLE
[Bug]:  [@babel/traverse ] DEPRECATED_ALIASES is undefined 

### ISSUE THREAD

**Issue by alex8088** [babel/babel#15488]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import * as babel from '@babel/core'

const re = babel.transform(code, {
  plugins: ['@babel/plugin-transform-arrow-functions']
})
```

### Current and expected behavior

```sh
TypeError: [BABEL] unknown file: Cannot use 'in' operator to search for 'CallExpression' in undefined
at explode (node_modules/@babel/traverse/src/visitors.ts:108:24)
at merge (node_modules/@babel/traverse/src/visitors.ts:220:5)
at Object.<anonymous> (node_modules/@babel/traverse/src/path/conversion.ts:223:43)
at Module._compile (node:internal/modules/cjs/loader:1155:14)
```

### Environment

- @babel/traverse 7.21.2
- node 16.18.1
- npm
- OS: linux

**Comment by nicolo-ribaudo** [comment]
Can you also check:
1. What is your `@babel/types` version
2. What does `console.log(require("@babel/types").DEPRECATED_ALIASES)` log

**Comment by alex8088** [comment]
Sorry, this is a mistake. It should be a problem with the package manager

**Comment by sonofmagic** [comment]
@alex8088 How did you solve it ? I meet this same problem and have no idea.

**Comment by alex8088** [comment]
@sonofmagic  remove the package manager lock file and reinstall.

**Comment by ErikGMatos** [comment]
> @sonofmagic remove the package manager lock file and reinstall.

Works for me, I was the same problem when I updated babel packages today.
