### ISSUE TITLE
ES6 Class - Can't extend HTMLElement in Safari

### ISSUE THREAD

**Issue by bradbenvenuti** [babel/babel#1548]
I am trying to create a custom element using an ES6 Class and inheriting from HTMLElement.

Example:
```
class TrafficShaping extends HTMLElement{

    createdCallback(){
    }

    attachedCallback(){
    }

    detachedCallback(){
    }
}
document.registerElement('traffic-shaping', TrafficShaping);
```

Babel's _inherits function (https://github.com/babel/babel/blob/088846a3479375a51d71084cb4fd70ef8fa21d29/src/babel/transformation/templates/helper-inherits.js) requires the super class to be a function or null, but in Safari typeof HTMLElement is an object. So this error is thrown:
```
if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
  }
```
In IE, Firefox and Chrome typeof HTMLElement is "function" so it works fine. See related bug here: https://bugs.webkit.org/show_bug.cgi?id=114457

Are there any recommended work arounds/polyfills for this issue?

**Comment by sebmck** [comment]
I guess you can shim it. I'm not willing to add in an edgecase.

```javascript
var _ HTMLElement = HTMLElement;

function HTMLElement() {}
HTMLElement.prototype = _HTMLElement.prototype.
```

**Comment by bradbenvenuti** [comment]
Thanks for the help. I had done that originally, but wasn't sure if there was a better way/something I was missing. I'll stick with that solution.

**Comment by SerkanSipahi** [comment]
This doesn't work for me:

```js
var _HTMLElement = HTMLElement;
function HTMLElement() {}
HTMLElement.prototype = _HTMLElement.prototype;
```

I get an error in Chrome 45.0.2416.0 canary:
Cannot assign to read only property 'prototype' of function HTMLElement() { [native code] }

it works only in Safari?

**Comment by bradbenvenuti** [comment]
This is my implementation... Only runs if typeof HTMLElement !== 'function'

if (typeof HTMLElement !== 'function'){
    var _HTMLElement = function(){};
    _HTMLElement.prototype = HTMLElement.prototype;
    HTMLElement = _HTMLElement;
}

**Comment by SerkanSipahi** [comment]
@bradbenvenuti do you use babel or traceur?

**Comment by bradbenvenuti** [comment]
I'm using Babel.

**Comment by SerkanSipahi** [comment]
Thank you @bradbenvenuti : it works :)

@sebmck : Switching( thousands lines of ES6 code ) from Traceur to Babel was easy ! Its works very well and faster than Traceur, thank you, too :)

**Comment by SerkanSipahi** [comment]
i believe i need `systemjs/dist/system-polyfills.src.js`! will check this out
