### ISSUE TITLE
repl: Bad character escape sequence (1:15) when parsing katex string

### ISSUE THREAD

**Issue by taras** [babel/babel#1550]
I have a string of latex that seems to break Babel's parser. Here is the string

```
f(x) = \int_{-\infty}^\infty
        \hat f(\xi)\,e^{2 \pi i \xi x}
        \,d\xi
```

If I use it with backticks, like this
```
let formula = `f(x) = \int_{-\infty}^\infty
        \hat f(\xi)\,e^{2 \pi i \xi x}
        \,d\xi`;
```

I get `real: Bad character escape sequence (1:15)`. 

![babel_ _the_compiler_for_writing_next_generation_javascript](https://cloud.githubusercontent.com/assets/74687/7662122/27935ab2-fb9c-11e4-8cf9-efebf41c5918.png)

**Comment by sebmck** [comment]
This is expected behaviour, the error message is correct, you have a bad character escape sequence. You need to replace your `\` with `\\` as `\` dictates an escaped character such as `\u` or `\x`.
