### ISSUE TITLE
[Bug]: Babel standalone doesn't work with JSX embedded in JSX.

### ISSUE THREAD

**Issue by garretwilson** [babel/babel#15504]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```jsx
import Bar from './Bar.jsx'

const Foo = () =>
  <p><Bar /></p>

export default Foo;
```

### Current and expected behavior

I'm using [Babel Standalone](https://babeljs.io/docs/babel-standalone) in an HTML file with React like this:

```html
<script src="assets/js/react.production.min.js"></script>
<script src="assets/js/react-dom.production.min.js></script>
<script src="assets/js/babel.min.js""></script>
```

Then I bring in a `Bar` React component like this:

```html
<script src="Bar.jsx" type="text/babel" data-plugins="transform-modules-umd"></script>
```

And I use it within the same HTML file:

```html
<script type="text/babel" data-plugins="transform-modules-umd">
  import Bar from './Quiz.jsx'

  … //get React root
  root.render(
    <p><Bar /></p>
  );
```

It works!

Now I want to use a `Foo` component which contains the same `Bar` component. I update the scripts like this (leaving the React and Babel import scripts the same):

```html
<script src="Foo.jsx" type="text/babel" data-plugins="transform-modules-umd"></script>
<script src="Bar.jsx" type="text/babel" data-plugins="transform-modules-umd"></script>
<script type="text/babel" data-plugins="transform-modules-umd">
  import Foo from './Quiz.jsx'

  … //get React root
  root.render(
    <p><Foo /></p>
  );
```

And `Foo.jsx` as mentioned looks like this:

```jsx
import Bar from './Bar.jsx'

const Foo = () =>
  <p><Bar /></p>

export default Foo;
```

Unfortunately this doesn't work. (Note that `Bar.jsx` is the same in both cases. (I don't include it. I think it's not relevant. It could just a single element. The point here is that it works when included from the HTML file but not from another JSX component in a `.jsx` file.)

How can I get one component `Foo` in `Foo.jsx` to include another component `Bar` in `Bar.jsx` using Babel Standalone?

P.S. Yes, I know Babel Standalone is just a toy, we shouldn't use it in production, etc. Still I wonder how to make this work.

### Environment

* React 18.2.0
* Babel 7.21.3
* Node 18.15.0
* Windows 10 22H2

**Comment by nicolo-ribaudo** [comment]
`@babel/standalone` only transforms the single script/file, and not all its dependencies. There is no way to do this directly with `@babel/standalone`; the best you could do is to have a ServiceWorker that intercepts requests to `.jsx` files from your web page and transpiles them on-the-fly using `@babel/standalone`, so that it doesn't matter how those files are imported (if with a `<script>` tag, or using `import`).
