### ISSUE TITLE
Can't debug mocha unit tests with node-inspector and babel/register

### ISSUE THREAD

**Issue by cr0cK** [babel/babel#1551]
Hello,

I don't know if I'm in the right place and if it's an issue of Babel, but maybe someone will be able to help me.

I try to debug a test of a React component written in ES6. The test works but I'd like to debug it with node-inspector to inspect elements and make stuff easier to write.

So, I start mocha with:
```
./node_modules/.bin/mocha --debug-brk test/*
```

I've a file ./test/babel-hook.js with the babel register function:

```
require('babel/register')({
  stage: 1,
  sourceMap: 'inline',
});
```

Mocha reads it and everything is working fine. Then I start a node-inspector, it breaks at startup like expected in the mocha source code, then I try to set a breakpoint in my test and I continue execution. But nothing is happening, the test goes forward and ends.

Have you got some ideas to make this to work?

**Comment by sebmck** [comment]
Try it without the `sourceMap` option.

**Comment by cr0cK** [comment]
Well, I tested dozens of times, it never worked and just after your response, it works!
You are a shaman :)

At the beginning, I was trying with:
```
mocha --compilers js:babel/register
```

And sure this syntax doesn't work.

Thank you.

**Comment by KeKs0r** [comment]
@cr0cK : Could you please specify slightly more detailed how the working setup now looks like?

I have tried with `mocha --compilers js:babel/register` as well and the sourcemaps don't seem to work.

Now I have copied your file, but how am I telling mocha to `read it` before the tests?

**Comment by cr0cK** [comment]
I just have `"test": "./node_modules/.bin/mocha --recursive"` in my alias in package.json and a file at the root of my tests with:

```
require('babel/register')({
  stage: 1
});
```

I run test with `npm test`. Mocha will read the file automatically.

**Comment by KeKs0r** [comment]
So the provided file is the only one at the root level? That is the reasons why its executed first?

**Comment by cr0cK** [comment]
yeah.

Here an example on a little project:

```
00:38 $ tree test/
test/
|-- babel-hook.js
|-- components
|   |-- DomainDetailsContactSpec.js
|   |-- DomainsDetailsSpec.js
|   |-- DomainsSpec.js
|   `-- MainSpinnerSpec.js
|-- fixtures
|   |-- domainInfo.json
|   `-- domains.json
`-- helpers
    |-- initDom.js
    `-- stubRouterContext.js

3 directories, 9 files
```
