### ISSUE TITLE
Regenerator causes generated code differ every transform

### ISSUE THREAD

**Issue by th0r** [babel/babel#1552]
I found it during building `webpack` build so maybe I should fill this issue in [babel-loader](https://github.com/babel/babel-loader) but I'm not sure.

The problem is that code transformed by regenerator is changing between build. This leads to mismatching hashes of the bundles with the same code.

I've made a diff between these bundles and found out that the changing part is the `N` counter in the generated `context$1$0.tN` props. Seems like this counter is not being reset between transformations of different modules (should it?) and `webpack` transforms these modules in the changing order between builds.

**Comment by sebmck** [comment]
cc @benjamn

**Comment by amasad** [comment]
It's important to have reproducible builds for build systems and caching. Can you open this issue on the regenerator repo? I think [this variable](https://github.com/facebook/regenerator/blob/356e84d00d1b3187477ab67e08f07009da271510/lib/emit.js#L230) must be an instance variable.

**Comment by benjamn** [comment]
Yep, that's the problem. Should be an easy fix. Thanks for reminding me about it!

**Comment by benjamn** [comment]
Should be fixed with version 0.8.26: https://www.npmjs.com/package/regenerator

**Comment by sebmck** [comment]
Thanks @benjamn!

**Comment by th0r** [comment]
Great! Thanks guys!
