### ISSUE TITLE
[Bug]:  template.ast goes endless loop

### ISSUE THREAD

**Issue by await-ovo** [babel/babel#15525]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const template = require("@babel/template").default;

const name = 'a'
const ast = template.ast`
export  { ${name} }   
`
console.log(ast);
```

### Configuration

No

### Current and expected behavior

Should get ast as expected

### Environment

  System:
    OS: macOS 11.7.4
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @babel/core: ^7.21.3 => 7.21.3 
    @babel/generator: ^7.21.3 => 7.21.3 
    @babel/parser: ^7.21.3 => 7.21.3 
    @babel/template: ^7.20.7 => 7.20.7 

### Possible solution

No

### Additional context

It seems that no matter how many times it is executed, there will be a case where `placeholder.isDuplicated`  be true, so it  just keep looping [here](https://github.com/babel/babel/blob/main/packages/babel-template/src/literal.ts#L79):

![image](https://user-images.githubusercontent.com/41503212/228515962-e86c061d-ef24-43d4-b960-9a43b23f0766.png)

I am not sure if there is something wrong with my usage, if so, please tell me, thanks a lot!

**Comment by await-ovo** [comment]
After some research, I still haven't figured out how to terminate the loop, and it seems that the loop makes sense in this case:

```
const template = require("@babel/template").default;

const name = 'a'
const ast = template.ast`
export  default ${name};
$0;
$$0
`
console.log(ast);
// => output:
[
  {
    type: 'ExportDefaultDeclaration',
    declaration: { type: 'Identifier', name: 'a' },
    loc: undefined
  },
  {
    type: 'ExpressionStatement',
    expression: { type: 'Identifier', name: '$0', loc: undefined },
    loc: undefined
  },
  {
    type: 'ExpressionStatement',
    expression: { type: 'Identifier', name: '$$0', loc: undefined },
    loc: undefined
  }
]
```

**Comment by await-ovo** [comment]
Hi @liuxingbaoyu , I'm not sure that the loop is just to keep the `$0` or `$1` in the template string, like the case above, but if so, I tried change `babel/template/src/literal.ts` locally like the following: 

![image](https://user-images.githubusercontent.com/41503212/228700095-02e7e127-94f5-41cd-884d-a3617928c327.png)
 
and the endless loop is gone, and the test case passed in the babel repository.

If this is the solution to the problem, I would be happy to send a PR, and add some new test cases,  thanks a lot ~

**Comment by liuxingbaoyu** [comment]
Thank you so much for your report and research.
This seems to fix the issue, but it's probably not the best way.
Probably a bigger refactor would be better for performance as well as readability, but I'm not sure about that as I'm not very familiar with the package.

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/228720318-743b784f-cd08-4b77-ba22-fdf7eaa02276.png)
Well this doesn't look like a complicated modification and this should work. At the same time this avoids possible multiple parsing.

**Comment by await-ovo** [comment]
> 
> ```ts
> function buildLiteralData<T>(
>   formatter: Formatter<T>,
>   tpl: Array<string>,
>   opts: TemplateOpts,
> ) {
>   let names;
>   let nameSet: Set<string>;
>   let metadata;
>   let prefix = "BABEL_TPL$";
> 
>   const raw = tpl.join("");
> 
>   do {
>     // If there are cases where the template already contains $0 or any other
>     // matching pattern, we keep adding "$$" characters until a unique prefix
>     // is found.
>     prefix = "$$" + prefix;
>   } while (raw.includes(prefix));
> 
>   const result = buildTemplateCode(tpl, prefix);
> 
>   names = result.names;
>   nameSet = new Set(names);
>   metadata = parseAndBuildMetadata(formatter, formatter.code(result.code), {
>     parser: opts.parser,
> 
>     // Explicitly include our generated names in the whitelist so users never
>     // have to think about whether their placeholder pattern will match.
>     placeholderWhitelist: new Set(
>       result.names.concat(
>         opts.placeholderWhitelist ? Array.from(opts.placeholderWhitelist) : [],
>       ),
>     ),
>     placeholderPattern: opts.placeholderPattern,
>     preserveComments: opts.preserveComments,
>     syntacticPlaceholders: opts.syntacticPlaceholders,
>   });
> 
>   return { metadata, names };
> }
> ```

The early do while check works grate for me, the test cases all seem to pass ~.
