### ISSUE TITLE
[Bug]: Unable to join the Slack community

### ISSUE THREAD

**Issue by aureq** [babel/babel#15538]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
console.log("Expired link 😂");
```

### Current and expected behavior

I'm trying to join the Babel slack community via https://slack.babeljs.io/ but the link is expired.

![image](https://user-images.githubusercontent.com/1161681/229396783-dae3bdbb-4705-4725-8449-29a6b9e04b28.png)

This is related to this workflow.

https://github.com/babel/babel/blob/main/.github/workflows/issue-triage.yml#L39-L41

### Environment

- n/a

**Comment by JLHwung** [comment]
We have just renewed the invite link, can you try if [this link](https://join.slack.com/t/babeljs/shared_invite/zt-1sv9zn30w-rVQwgmu4HuVBeLy0YgNSgQ) works?

**Comment by aureq** [comment]
@JLHwung Yes, it's working. Though, the link babel-bot sends when an issue is opened is still not working.

**Comment by JLHwung** [comment]
@aureq Thanks.

> Though, the link babel-bot sends when an issue is opened is still not working.
Yeah we are working on that, thus this issue is not closed.

**Comment by JLHwung** [comment]
https://slack.babeljs.io should work now.
