### ISSUE TITLE
license file for packages/babel-runtime

### ISSUE THREAD

**Issue by lotusorrose** [babel/babel#15541]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

license file is missing for the https://github.com/babel/babel/tree/main/packages/babel-runtime/ folder

### Describe the solution you'd like

add a license file with copyright info

### Describe alternatives you've considered

copy the generic MIT license without the copyrights

**Comment by JLHwung** [comment]
The licence file is attached in the published package: https://unpkg.com/browse/@babel/runtime@7.21.0/LICENSE

As for the repo, the license is in the root directory: https://github.com/babel/babel/blob/main/LICENSE
