### ISSUE TITLE
Cannot read property 'declareTemporary' of null

### ISSUE THREAD

**Issue by monolithed** [babel/babel#1554]
```js
export default function *(object) {
	for (let key of Object.keys(object)) {
		yield [key, object[key]];
	}
};
```

```
➜ grunt build
Running "babel:build" (babel) task
Warning: tools/entries.js: Cannot read property 'declareTemporary' of null Use --force to continue.

Aborted due to warnings.
```

The problem with generator specialization  __*__ 
It looks like it came with the last update

**Comment by sebmck** [comment]
I can't replicate this. What version are you on?

**Comment by sebmck** [comment]
Do you have a reproducible example in the [REPL](http://babeljs.io/repl/)? Because the code listed [compiles fine](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=export%20default%20function%20*(object)%20%7B%0A%20%20%20%20for%20(let%20key%20of%20Object.keys(object))%20%7B%0A%20%20%20%20%20%20%20%20yield%20%5Bkey%2C%20object%5Bkey%5D%5D%3B%0A%20%20%20%20%7D%0A%7D%3B&playground=false).

**Comment by monolithed** [comment]
```
➜ node -v
v0.12.1

➜ npm list | grep babel
├─┬ grunt-babel@5.0.0
│ └─┬ babel-core@5.4.3
```

**Comment by monolithed** [comment]
Could you clone my repository?

```
npm clone git@github.com:Polyfiller/polyfiller-catalog.git && cd polyfiller-catalog && npm install
```

**Comment by sebmck** [comment]
Ok so it's not a bug in `regenerator` or `babel`. You have [this](https://github.com/Polyfiller/polyfiller-catalog/blob/master/package.json#L116) line in your `package.json` which is screwing with the dependency graph as Babel needs `regenerator` in it's `node_modules` to properly patch `ast-types`.

**Comment by monolithed** [comment]
Sorry, but I don't understand. 
How do I fix it? :)

**Comment by sebmck** [comment]
Remove `regenerator` from your `package.json` and reinstall `node_modules`.

**Comment by monolithed** [comment]
Hm, It did not help me

**Comment by sebmck** [comment]
It works for me after removing `regenerator` from your `package.json` and running `rm -rf node_modules && npm install`.

**Comment by monolithed** [comment]
The problem is solved:
 
```
optional: [
	'runtime',
]
```
