### ISSUE TITLE
babel-node sourcemap support

### ISSUE THREAD

**Issue by michaelBenin** [babel/babel#1556]
Does babel-node have an option for sourcemap inline as stated here with babel:
https://babeljs.io/docs/usage/cli/

I'm using babel-node with nodemon found here in the docs:
https://babeljs.io/docs/using-babel/#nodemon - I have it running with gulp nodemon but when there is an error the stack trace shows the compiled source. 

I'm also using source-map-support in my script as debugging comes first when experimenting with a new build. 

It would be nice if babel-node had an option to inline the sourcemaps and add source-map-support in entries for you.

**Comment by sebmck** [comment]
[It already does](https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L68). If it's not working then there's nothing that can really be done on the Babel-side since it serves inline source maps already.

**Comment by sebmck** [comment]
[source-map-support is already setup too](https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L11-24).

**Comment by michaelBenin** [comment]
My simple script to test what happens on error:

````
import { server, application } from './services/server';


// this doesn't exist
server.nonexist();

server.listen(8000, function () {
  console.log('server is running on port 8000');
});

````

My execution with gulp and nodemon:

````
gulp.task('dev-server', function () {
  nodemon({
    script: 'server/index.js',
    exec: 'babel-node --stage 0',
    ext: 'js',
    env: {
      'NODE_ENV': 'development'
    }
  })
});
````

The error output:
````
/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/server/index.js:6
_servicesServer.server.nonexist();
                       ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/server/index.js:5:8)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/michaelbenin/.nvm/versions/v0.12.0/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:147:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/michaelbenin/.nvm/versions/v0.12.0/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/Users/michaelbenin/.nvm/versions/v0.12.0/lib/node_modules/babel/bin/_babel-node:111:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
````

The stack trace is not coming from the source.

**Comment by sebmck** [comment]
Sourcemaps only effect line information and actual source code. Error messages and stack trace name locations wont be effected.

**Comment by michaelBenin** [comment]
In past use of source maps, it aided in debugging, specifically showing line numbers of the original source on error as stated here: http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

In the browser, with browserify, when an error would occur, it would be clear where it occurred in the original source when using sourcemaps. 

When using babel-node its showing the transpiled locations of where the error occurred. If this is the expected output I'm confused to see how this is useful.

**Comment by sebmck** [comment]
This is a problem with your browser then. I don't see what you expect Babel to do. It already puts out valid source inline maps when using `babel-node` and `babel/register` and if a tool doesn't respect those then it's not Babel's problem.

**Comment by michaelBenin** [comment]
I'm not using a browser, this is transpiling server side nodejs using babel node.

**Comment by michaelBenin** [comment]
babel-node --version
5.4.2

**Comment by michaelBenin** [comment]
I'll try to record a screen cast to demonstrate this issue. I'm sorry for bothering you on a Sunday.

**Comment by sebmck** [comment]
I need a reproducible example then since it seems to work as expected :smile: 

**test.js**

```javascript
class Foo {
  bar() {
    throw new Error("foobar");
  }
}

new Foo().bar();
```

```sh
$ babel-node test.js
Error: foobar
    at Foo.bar (redacted/test.js:3:11)
...
```

**Comment by michaelBenin** [comment]
This week I'll create a repo to demonstrate this.

**Comment by sebmck** [comment]
Sounds good :)

**Comment by michaelBenin** [comment]
@sebmck https://github.com/michaelBenin/babel-node-sourcemaps-repro

**Comment by sebmck** [comment]
@michaelBenin That points to the current line for me?

```
TypeError: _servicesServer.server.nonexist is not a function
    at Object.<anonymous> (/Users/sebmck/Projects/babel-node-sourcemaps-repro/server/babel-node-repro.js:4:8)
    at Module._compile (module.js:431:26)
    at normalLoader (/Users/sebmck/Projects/babel/core/lib/babel/api/register/node.js:153:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sebmck/Projects/babel/core/lib/babel/api/register/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at Object.<anonymous> (/Users/sebmck/Projects/babel/core/packages/babel-cli/bin/_babel-node:111:12)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
```

**Comment by michaelBenin** [comment]
Did you compare to the one with using babel over babel-node? 

```
../server/sourcemaps_working.js:5
server.nonexist();
       ^
TypeError: undefined is not a function
    at Object.<anonymous> (../server/sourcemaps_working.js:5:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sebmck** [comment]
Everything looks fine and working to me.

You're probably looking at the

```
/Users/michael.benin/Desktop/babel-node-sourcemaps-repro/server/babel-node-repro.js:6
_servicesServer.server.nonexist();
                       ^
```

header. Rewriting of that has been disabled in `babel-node` by [this line](https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L12) because otherwise `source-map-support` overrides the `uncaughtException ` handler which means that app code can't listen to it. See #899 for more info.

**Comment by michaelBenin** [comment]
Is there an issue in source-map-support about this?

**Comment by sebmck** [comment]
Nope, it's expected behaviour. Adding an `uncaughtException` listener means that node wont exit the process so `source-map-support` has to exit it for us.

**Comment by michaelBenin** [comment]
https://github.com/michaelBenin/babel-node-sourcemaps-repro/tree/uncaught-working

So I'm getting uncaught exception in both cases?

**Comment by sebmck** [comment]
Well yeah, it's throwing an error.

**Comment by michaelBenin** [comment]
In the babel-node example ~

This is correct: 

'''
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/michael.benin/Desktop/babel-node-sourcemaps-repro/server/babel-node-repro.js:4:8)
'''

But the part of:
```
/Users/michael.benin/Desktop/babel-node-sourcemaps-repro/server/babel-node-repro.js:6
_servicesServer.server.nonexist();
                       ^
```

Is not and misleading. 

This works for me. I'll just need to explain that when we look at errors only look at the stack trace.

**Comment by michaelBenin** [comment]
Regarding to the overwriting of uncaughtException, source-map-support wasn't doing that in my branch.

**Comment by sebmck** [comment]
Yeah I know it's misleading, unfortunately there's not much that can be done.

**Comment by sebmck** [comment]
Yes it was. When you do `require("source-map-support").install();` it's explicitly overriding `uncaughtException` to rewrite those error headers.

**Comment by michaelBenin** [comment]
Would you accept a pr to update the docs?

**Comment by sebmck** [comment]
Absolutely.

**Comment by michaelBenin** [comment]
Regarding the uncaughtException, it was still exiting the process. That's not a problem as we are using domains and gracefully reloading our node processes on error.
