### ISSUE TITLE
[Bug]: @babel/plugin-transform-runtime not transform Object.hasOwn correctly

### ISSUE THREAD

**Issue by AXiLiYa** [babel/babel#15572]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

`@babel/cli`

### Input code

```js
const _ = function () {
    const obj = { a: 1}
    console.log(Object.hasOwn(obj, "b"));
    [].includes(1)
      
    const a = new Promise()
    return a
}
export default  _

console.log(_())
```

### Configuration file name

`babel.config.json`

### Configuration

```json
{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 3
      }
    ]
  ]
}
```

### Current and expected behavior

I used @babel/cli directly with the command `./node_modules/.bin/babel index.js --out-dir lib`. This is the output:
```js
import _includesInstanceProperty from "@babel/runtime-corejs3/core-js-stable/instance/includes";
import _Promise from "@babel/runtime-corejs3/core-js-stable/promise";
const _ = function () {
  var _context;
  const obj = {
    a: 1
  };
  console.log(Object.hasOwn(obj, "b"));
  _includesInstanceProperty(_context = []).call(_context, 1);
  const a = new _Promise();
  return a;
};
export default _;
console.log(_());
```
The `Promise` and `Array.includes` are replace with `@babel/runtime-corejs3` correctly. But `Object.hasOwn` not. And I find the `@babel/runtime-corejs3/core-js-stable` didn't exist the polyfill of `Object.hasOwn` which is realized in corejs. I have read the doc about `@babel/plugin-transform-runtime`, but I haven't found anything about this. So this behavior is designed so? Or I have missed some informations?

### Environment

```
  System:
    OS: macOS 13.2
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  npmPackages:
    @babel/cli: ^7.21.0 => 7.21.0
    @babel/core: ^7.21.4 => 7.21.4
    @babel/plugin-transform-runtime: ^7.21.4 => 7.21.4
    @babel/preset-env: ^7.21.4 => 7.21.4
    @babel/runtime: ^7.21.0 => 7.21.0
    @babel/runtime-corejs3: ^7.21.0 => 7.21.0
```

**Comment by nicolo-ribaudo** [comment]
`"corejs": 3` means `"3.0.0"`, and `Object.hasOwn` is only supported in more recent versions.

Unfortunately there is no good way yet to specify an higher version. You could update your config to this:
```json
{
  "plugins": [
    "@babel/plugin-transform-runtime",
    ["babel-plugin-polyfill-corejs3", { "method": "usage-pure", "version": "3.30" }]
  ]
}
```
and add `"core-js"` to your `package.json`, so that it injects polyfills supoprted by core-js 3.30.

However, with that config Babel would inject imports to `core-js` and to `@babel/runtime`, and not `@babel/runtime-corejs3`, so the runtime helpers are not polyfilled and might not work in old browsers.

Once we have https://github.com/babel/babel/pull/15531 or something similar, the above config should properly injects imports to `core-js` and `@babel/runtime-corejs3`.

**Comment by AXiLiYa** [comment]
Thanks a lot for your answer. But I still have a question. I find you said
> However, with that config Babel would inject imports to core-js and to @babel/runtime, and not @babel/runtime-corejs3, so the runtime helpers are not polyfilled and might not work in old browsers.

Is this means the entry I input will polyfilled correctly, but code in `@balbel/runtime` will not be polyfilled, and some of theme may not work in old browsers?

**Comment by nicolo-ribaudo** [comment]
Yes exactly
