### ISSUE TITLE
[Bug]: syntax-import-meta not included in preset-env

### ISSUE THREAD

**Issue by steverep** [babel/babel#15578]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

The documentation says that [`syntax-import-meta`](https://babeljs.io/docs/babel-plugin-syntax-import-meta) is included in `preset-env`, but that does not seem to be the case.  It would make sense since all other ES 2020 plugins are included.

### Configuration

n/a

### Current and expected behavior

n/a

### Environment

n/a

### Possible solution

Include it in `preset-env`'s `package.json` 😄

**Comment by JLHwung** [comment]
If you are using `@babel/core` 7.10.0 and above, you can safely ignore this issue as `@babel/parser` will always support import meta as if you have installed the syntax plugin. But this is indeed a compatibility bug: when using the latest `@babel/preset-env` with `@babel/core` < 7.9, Babel will throw syntax error on `import.meta`.

**Comment by steverep** [comment]
Using 7.21.4, I experienced babel-loader just hanging when it was encountered, but that was with a config not actually using preset-env and listing the plugin directly (thinking it was installed but not actually).

Thanks for the clarification though. 👍🏻

**Comment by steverep** [comment]
It's 5.72.1.  I think it was just hanging because a plugin that didn't exist was specified, although I'd expect it to throw.  That's unrelated to this issue anyway I think.

**Comment by JLHwung** [comment]
@steverep Yes, that seems like another issue. Can you open a new tracking issue? If you can come up with a reproduction, I would like take a look.
