### ISSUE TITLE
Adding `sourceType: "unambiguous"` to `babel.config.js`  Can't fix the error `Modules may not assign module.exports or exports.*, Use ESM export syntax`.

### ISSUE THREAD

**Issue by telephant** [babel/babel#15592]
@Mikilll94 Adding `sourceType: "unambiguous"` to `babel.config.js` seems to fix the error.

set the `"sourceType": "unambiguous",` is doesn't work for me. My config is below in .babelrc.json .
```
{
  "sourceType": "unambiguous",
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "edge": "17",
          "firefox": "60",
          "chrome": "67",
          "safari": "11.1"
        },
        "corejs": "3.8",
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime"
    ]
  ]
}

```

It is still reporting the error ` Modules may not assign module.exports or exports.*, Use ESM export syntax`

I try to track the error file, it is a `node_modules` pacakge - `debug`.

_Originally posted by @nicolo-ribaudo in https://github.com/babel/babel/issues/12731#issuecomment-780153966_

**Comment by JLHwung** [comment]
> I try to track the error file, it is a node_modules pacakge - debug.

Are you using babel with webpack / rollup? Please provide more information about how to reproduce this issue.
