### ISSUE TITLE
[Bug]: @babel/plugin-transform-regenerator doesn't bind const in inner loop

### ISSUE THREAD

**Issue by IlyaSemenov** [babel/babel#15594]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
async function main() {
  const obj = {}
  for (const key of ['foo', 'bar']) {
    obj[key] = () => key
  }
  console.log(obj.foo())
}

main()
```

[REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsIwLbFRACgEoYBvAKAEgpMRkZ0AjAKxgF4yBfKudAJxgEaEOjADWAUzAM4MANoByXugUAaGAsbA-CgLokKlSk2ZzJYXe0Ek2APnFSq3arXQAbCQDo36AOYETT2ViInJuclx8YnIgA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.21.4&externalPlugins=%40babel%2Fplugin-transform-regenerator%407.20.5&assumptions=%7B%7D)

### Configuration

```
babel --plugins @babel/plugin-transform-regenerator 1.js
```

### Current and expected behavior

Current behaviour: the compiled script writes `bar`.

Expected behaviour (that is what you get if you run it unprocessed): the script writes `foo`.

### Output code

```js
function main() {
  var obj, key;
  return _regeneratorRuntime().async(function main$(_context) {
    while (1) switch (_context.prev = _context.next) {
      case 0:
        obj = {};
        for (key of ['foo', 'bar']) {
          obj[key] = () => key;
        }
        console.log(obj.foo());
      case 3:
      case "end":
        return _context.stop();
    }
  }, null, null, null, Promise);
}
main();
```

### Environment

  System:
    OS: macOS 13.1
  Binaries:
    Node: 16.19.0 - ~/.nodenv/versions/16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nodenv/versions/16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nodenv/versions/16.19.0/bin/npm
  npmPackages:
    @babel/cli: ~7.21.0 => 7.21.0 

### Possible solution

`const` in regenerated loops should not be converted to `vars` blindly. Rather, the loops should be converted to ad-hoc functions (see how Facebooks regenerator does that).

### Additional context

[Facebook regenerator](https://github.com/facebook/regenerator) handles this case properly:

```js
function main() {
  var obj, _loop, _i, _arr, key;
  return regeneratorRuntime.async(function main$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          obj = {};
          _loop = function (key) {
            obj[key] = function () {
              return key;
            };
          };
          for (_i = 0, _arr = ['foo', 'bar']; _i < _arr.length; _i++) {
            key = _arr[_i];
            _loop(key);
          }
          console.log(obj.foo());
        case 4:
        case "end":
          return _context.stop();
      }
    }
  }, null, null, null, Promise);
}
main();
```

**Comment by nicolo-ribaudo** [comment]
`@babel/plugin-transform-regenerator` _is_ just Facebook's regenerator. It works if you enable the block scoping and arrow functions plugins, which is what regenerator does:
https://github.com/facebook/regenerator/blob/c24b7b7259ee8a6cea192c220860cc81bafb4571/packages/preset/index.js#L13-L14

**Comment by IlyaSemenov** [comment]
Thank you for the quick response! Enabling these two plugins indeed helps. But shouldn't they be automatically enabled somehow? I mean, that is not right that Babel silently emits **misbehaving** code?

I also discovered #12806 but I'm not sure if my issue is a full duplicate or not.

**Comment by IlyaSemenov** [comment]
Closing as duplicate of #12806
