### ISSUE TITLE
[Bug]: Cannot find module './data/corejs3-shipped-proposals.json （unresolved）

### ISSUE THREAD

**Issue by lhbxs** [babel/babel#15599]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

Cannot find module './data/corejs3-shipped-proposals.json'

### Current and expected behavior

Cannot find module './data/corejs3-shipped-proposals.json'

### Environment

7.21.5

**Comment by JLHwung** [comment]
Duplicate of #15597
