### ISSUE TITLE
[Bug]: Not found corejs3-shipped-proposals.json

### ISSUE THREAD

**Issue by jafg1993** [babel/babel#15597]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

corejs3-shipped-proposals.js dont found corejs3-shipped-proposals.json 

### Current and expected behavior

*

### Environment

- @babel/compat-data 
- Node 12.2.1

### Additional context

The corejs3-shipped-proposals.js dont found corejs3-shipped-proposals.json  disapear in the version 7.21.5

**Comment by tristanhoy** [comment]
Rolling back fixed it for me.
```
npm i --save-dev --save-exact @babel/compat-data@7.21.4
```

**Comment by lhbxs** [comment]
Cannot find module './data/corejs3-shipped-proposals.json'

**Comment by JLHwung** [comment]
This issue has been fixed in `@babel/compat-data@7.21.6`.

**Comment by JLHwung** [comment]
@babel/compat-data@7.21.6 is not published, we will revisit the publish process.

**Comment by lhbxs** [comment]
When is it expected to be released

**Comment by maGsTro48** [comment]
tmp fix: set "@babel/compat-data": "7.21.4" in package.json

**Comment by JLHwung** [comment]
Fixed in `@babel/compat-data@7.21.7`.

https://unpkg.com/browse/@babel/compat-data@7.21.7/data/corejs3-shipped-proposals.json
