### ISSUE TITLE
[Bug]: The "useBuiltIns: usage" mode and "usage-global" mode have different output codes

### ISSUE THREAD

**Issue by limingcan562** [babel/babel#15596]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
async function wait() {}

wait().then(() => console.log('hello'));
```

### Configuration

1. Use the `useBuiltIns: usage` mode:
```js
const presets = [
    [
        '@babel/preset-env',
        {
            targets: 'ie 11',
            useBuiltIns: 'usage',
            corejs: {
                version: '3.30.1',
                proposals: true
            }
        }
    ]
];

const plugins = [
    '@babel/plugin-transform-runtime'
];
module.exports = {plugins, presets};
```

2. Using the `usage-global` mode:
```js
const presets = [
    [
        '@babel/preset-env',
        {
            targets: 'ie 11',
        }
    ]
]

const plugins = [
    '@babel/plugin-transform-runtime',
    [
        'babel-plugin-polyfill-corejs3',
        {
            method: "usage-global", 
            version: "3.30.1",
            proposals: true,
        }
    ]
];
module.exports = {plugins, presets};
```

### Current and expected behavior

1. Code output using the `useBuiltIns: usage` mode:
```js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
var _regenerator = _interopRequireDefault(require("@babel/runtime/regenerator"));
var _asyncToGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));
function wait() {
  return _wait.apply(this, arguments);
}
....
```
**Cannot run on IE11.**

2. Code output using `usage-global` mode: 
```js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
var _regenerator = _interopRequireDefault(require("@babel/runtime/regenerator"));
var _asyncToGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));
require("core-js/modules/es.object.to-string.js");
require("core-js/modules/es.promise.js");
function wait() {
  return _wait.apply(this, arguments);
}
...
```
It added two more polyfills:
 - `core-js/modules/es.object.to-string.js`
 - `core-js/modules/es.promise.js`

**And it can run on IE11.**

---
Based on this https://github.com/babel/babel/issues/9853#issuecomment-619587386, I know that:

- `useBuiltIns: usage` mode, doesn't work on IE11 because the helper function (`@babel/runtime/helpers/asyncToGenerator`) contains `promise` and my code did not use it, so `promise` was not polyfilled.

- `usage-global` mode, due to the addition of `promise`'s ployfill, can run on IE11.

So, it seems that the `usage-global` mode is better because `babel-plugin-polyfill-corejs3` has already implemented the injection of polyfills into the helper functions used by `transform-runtime`?

If so, can I use this package directly instead of `useBuiltIns: usage` mode?

### Environment

System:
    OS: macOS 12.2.1
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    npm: 6.14.15 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.21.0 => 7.21.0 
    @babel/core: ^7.21.4 => 7.21.4 
    @babel/plugin-transform-runtime: ^7.21.4 => 7.21.4 
    @babel/preset-env: ^7.21.4 => 7.21.4 
    babel-loader: ^9.1.2 => 9.1.2 
    webpack: ^5.81.0 => 5.81.0

**Comment by nicolo-ribaudo** [comment]
`@babel/preset-env` internally uses `usage-global`, so I _think_ this might just be because of the different orders in which plugins are applied.

Given that `babel-plugin-polyfill-corejs3` has been proven stable by it's usage in `@babel/preset-env`, I recommend just using it directly.

**Comment by limingcan562** [comment]
I'm sorry for replying to you now. Thank you for your reply!
