### ISSUE TITLE
class with constructor only throws ReferenceError

### ISSUE THREAD

**Issue by chrispday** [babel/babel#1560]
Using version 5.2.6
Following code

	export class PostCreated {
		constructor (postId, dateCreated) {
			this.postId = postId;
			this.dateCreated = dateCreated;
		}
	}

transpiles to

	"use strict";		

	exports.__esModule = true;

	var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

	var PostCreated = function PostCreated(postId, dateCreated) {
		_classCallCheck(this, PostCreated); // THROWS HERE!

		this.postId = postId;
		this.dateCreated = dateCreated;
	};

	exports.PostCreated = PostCreated;
	//# sourceMappingURL=../../domain/posts/PostCreated.js.map

When using it in a test

	var assert = require("assert");

	import { PostCreated } 	from "../../../src/domain/posts/PostCreated.js";

	describe("some description", function () {
		it("some it", function() {
			var created = new PostCreated(1, Date.now());
		});
	});

which transpiles to

	"use strict";

	var _PostCreated = require("../../../src/domain/posts/PostCreated.js");

	var assert = require("assert");

	describe("some description", function () {
		it("some it", function () {
			var created = new _PostCreated.PostCreated(1, Date.now());
		});
	});

this throws  `ReferenceError: PostCreated is not defined` on the line `_classCallCheck(this, PostCreated);`

As soon as you add a function to the PostCreated class, it then works due to using an immediate execute function.

	export class PostCreated {
		constructor (postId, dateCreated) {
			this.postId = postId;
			this.dateCreated = dateCreated;
		}
	
		fixesIt() {}
	}

transpiles to 

	"use strict";

	exports.__esModule = true;

	var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

	var PostCreated = (function () {
		function PostCreated(postId, dateCreated) {
			_classCallCheck(this, PostCreated);

			this.postId = postId;
			this.dateCreated = dateCreated;
		}

		PostCreated.prototype.fixesIt = function fixesIt() {};

		return PostCreated;
	})();

	exports.PostCreated = PostCreated;
	//# sourceMappingURL=../../domain/posts/PostCreated.js.map

**Comment by sebmck** [comment]
What browser are you using?

**Comment by chrispday** [comment]
This was running through gulp/mocha on node v0.12

**Comment by sebmck** [comment]
I don't understand why a `ReferenceError` is even being thrown since it's explicitly defined in scope.

**Comment by chrispday** [comment]
Yep, it's a bit of a mystery.  Did you want me to create a repro project?

**Comment by sebmck** [comment]
Yes please!

**Comment by chrispday** [comment]
I'm struggling to reproduce this in a cut-down way and now the original project is having a hard time reproducing, grrrr.  I think this may be a subtle bug where an error in a resolving promise is causing this red-herring error to be thrown. I'll close it for now and if I can get a reliable repro I'll re-open.

**Comment by manaten** [comment]
I reproduce same problem with this code on babel-node.

```js
// foo.js
// Ｍｕｌｔｉ Ｂｙｔｅ
class Foo {
  constructor() {}
}
console.log(new Foo);
```

```sh
>> babel-node foo.js
/home/vagrant/babel-test/foo.js:7
  _classCallCheck(this, Foo);
                        ^
ReferenceError: Foo is not defined
    at new Foo (/home/vagrant/babel-test/foo.js:2:7)
    at Object.<anonymous> (/home/vagrant/babel-test/foo.js:5:13)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/lib/_babel-node.js:144:25)
    at Module._compile (module.js:460:26)
```

And run again, the error is not happened (Maybe cache problem?).

```sh
>> babel-node foo.js
{}
```


Same problem happened with `babel/register` .

```js
// bar.js
require('babel/register');
require('./foo.js');
```


```sh
node bar.js
/home/vagrant/babel-test/foo.js:7
  _classCallCheck(this, Foo);
                        ^
ReferenceError: Foo is not defined
    at new Foo (/home/vagrant/babel-test/foo.js:2:7)
    at Object.<anonymous> (/home/vagrant/babel-test/foo.js:6:13)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/vagrant/babel-test/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/babel-test/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/babel-test/bar.js:2:1)
```

So I think this problem is due to `babel/register` with multi byte char and only occurs without cache.

I reproduce this problem with babel 5.8.23 (babel-core 5.8.25) and node v0.12.2 or v4.1.1.

**Comment by loganfsmyth** [comment]
@manaten This has been narrowed down to a V8 issue in https://github.com/babel/babel/issues/2455

**Comment by manaten** [comment]
@loganfsmyth Oh, thanks.

**Comment by MrOrz** [comment]
+1 just encountered this in one of my project.
https://travis-ci.org/MrOrz/hacktabl-parser/builds/86234150

On my machine it happens once in every two executions, whose behavior is identical to @manaten 's description.

**Comment by loganfsmyth** [comment]
As the issue above says, this will need to be fixed in V8. There isn't much
else you can do but avoid non-ascii files for now.
On Oct 19, 2015 18:05, "Johnson Liang" <notifications@github.com> wrote:
>
> +1 just encountered this in one of my project.
> https://travis-ci.org/MrOrz/hacktabl-parser/builds/86234150
>
> On my machine it happens once in every two executions, whose behavior is
identical to @manaten 's description.
