### ISSUE TITLE
Exception in IE11

### ISSUE THREAD

**Issue by Manuel-S** [babel/babel#1561]
I set up a hello world example using aurelia and babel, but while it worked in chrome, I had no luck in IE. 
The exception I get is "Die Eigenschaft "Symbol(id)_i.22alybn8ccc" kann nicht definiert werden: Das Objekt ist nicht erweiterbar" (The Property "..." cannot be defined: The object is not extendable) But it's hard to trace the source of it.
Asked in the gitter if somebody knows what's going on, and @zloirock said "it's issue with core-js Map or Set and frozen objects, but it's tested for this case and should works correct. Possible conflict with other library. I can't find problem in stack trace."

So without further ado, here's the minimal example:

run `npm init` with defaults, `jspm init` with defaults (babel), `jspm install aurelia-bootstrapper`

file index.html

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Test-App</title>
    </head>
    <body aurelia-app>
        <script src="jspm_packages/system.js"></script>
        <script src="config.js"></script>
        <script>
            System.import('aurelia-bootstrapper');
        </script>
    </body>
</html>
```

file app.html

```html
<template>
  <section>
    <h2>${heading}</h2>

    <form role="form" submit.delegate="welcome()">
      <div class="form-group">
        <label for="fn">First Name</label>
        <input type="text" value.bind="firstName" class="form-control" id="fn" placeholder="first name">
      </div>
      <div class="form-group">
        <label for="ln">Last Name</label>
        <input type="text" value.bind="lastName" class="form-control" id="ln" placeholder="last name">
      </div>
      <div class="form-group">
        <label>Full Name</label>
        <p class="help-block">${fullName}</p>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </section>
</template>
```

file app.js

```javascript
export class Welcome{
  constructor(){
  this.heading = 'Hello World!';
  this.firstName = 'John';
  this.lastName = 'Doe';
  }

  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }

  welcome(){
    alert(`Welcome, ${this.fullName}!`);
  }
}
```

Hope someone can find what's going on here.

**Comment by Manuel-S** [comment]
Issue in Aurelia-Framework: https://github.com/aurelia/framework/issues/113

**Comment by sebmck** [comment]
There's nothing obvious going wrong and this appears to be an environment issue since the generated code is completely correct.

**Comment by sebmck** [comment]
Also, that code doesn't include any references to `Symbol` so it's likely an Aurelia issue that I unfortunately can't help with.

**Comment by zloirock** [comment]
As I wrote, looks like `traceur` runtime breaks [this simple function](https://github.com/zloirock/core-js/blob/v0.9.10/modules/%24.collection-strong.js#L21-L33) in `core-js` collections:

![scr](http://habrastorage.org/files/bde/2c4/7b1/bde2c47b1c594c54ba410a29f6747f37.png)

**Comment by luisrudge** [comment]
I'm not using aurelia and I'm having the same error.

![image](https://cloud.githubusercontent.com/assets/941075/8071004/97f8edfa-0edc-11e5-86d3-769c7daed3f4.png)

**Comment by sebmck** [comment]
@luisrudge You need a Symbol polyfill.

**Comment by luisrudge** [comment]
But this works fine on chrome. :(

**Comment by luisrudge** [comment]
Ahh, chrome already have that.

**Comment by sebmck** [comment]
Because the Chrome version you’d be using would have support for Symbols.

**Comment by luisrudge** [comment]
Shouldn't babel include that by default?

**Comment by sebmck** [comment]
How do you expect it to include it by default?

**Comment by luisrudge** [comment]
The same way I'm going to include it myself. Using https://github.com/medikoo/es6-symbol or something else.

**Comment by sebmck** [comment]
Babel has no opinions about your environment so there’s no way to inject anything.

**Comment by luisrudge** [comment]
I thought maybe this could be part of the babel runtime or something, since it's required to run on IE11 (IE Edge already has Symbol support).

**Comment by sebmck** [comment]
There’s already a variety of built-in ways to do this. See the docs: http://babeljs.io/docs/usage/polyfill/ http://babeljs.io/docs/usage/runtime/

**Comment by luisrudge** [comment]
There's no usage with webpack :(

**Comment by sebmck** [comment]
`require(“babel/polyfill”);`

**Comment by luisrudge** [comment]
Thanks! For everyone having the same problem on IE:

```
> npm install --save babel-core

on your entry point:
import 'babel-core/polyfill'; //or require('babel-core/polyfill');
```
