### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jiaxing-1994** [babel/babel#15624]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import * as babel from "@babel/core";
import fs from "fs";

const babelOptions = {
    presets: ["@babel/env"],
    compact: false,
    babelrc: false,
};
const config = await (babel.loadPartialConfigAsync || babel.loadPartialConfig)(
    babelOptions
);
const transformOptions = config.options;
const file = "./testFile.js";
const inputCode = fs.readFileSync(file).toString();
const { code, map } = await babel.transformAsync(inputCode, transformOptions);
fs.writeFileSync("./testFile2.js", code);
```

### Current and expected behavior

I want to use `@babel/env` for code compilation. Convert the Class syntax in the code into  Function syntax. Because the `@babel/plugin-transform-classes` library has been integrated into `@babel/env`, so I used the `@babel/env` preset directly, but the Class syntax still exists in the code after compilation, unless I manually install `@babel/plugin -transform-classes`, and then add it to the plugins parameter, that it will take effect.

### Environment

babel: v7.21.8
node: v14.18.0
npm: v6.14.15
os: macOS Monterey v12.6.2
Monorepo: pnpm

**Comment by JLHwung** [comment]
Can you add `{ debug: true }` and attach the log output?
```js
{
  presets: [
    ["@babel/env", { debug: true }]
  ],
}
```
It will tell you why `transform-classes` is not included, likely because your targets already support class features.

**Comment by jiaxing-1994** [comment]
> 您可以添加`{ debug: true }`并附加日志输出吗？
> 
> ```js
> {
>   presets: [
>     ["@babel/env", { debug: true }]
>   ],
> }
> ```
> 
> 它会告诉您为什么`transform-classes`不包括在内，可能是因为您的目标已经支持类功能。

感谢！ 添加了debug后发现的确该预设加载的插件很少，不全。 跟踪源码发现是因为没有指明targets，设置好正确的targets.browsers后，就可以按预期打包了。 还是对babel配置了解不深呀， 谢谢！！

**Comment by JLHwung** [comment]
@jiaxing-1994 I am glad that it helps. Reminder: please stick with English as others may not understand Chinese.
