### ISSUE TITLE
Changing modules system

### ISSUE THREAD

**Issue by omerts** [babel/babel#1563]
Hello,

I am trying to change the modules system to SystemJS, when running the following command:
```
babel --modules system
```
It looks like nothing is happening, and the cursor is just blinking.

Omer

**Comment by sebmck** [comment]
You need to specify a file to compile.

```sh
$ babel --modules system your-script-here.js
```

By default it reads from stdin.

**Comment by omerts** [comment]
Ok thanks, I thought it was a command to set up some config
