### ISSUE TITLE
[Bug]:  Source-map name mappings

### ISSUE THREAD

**Issue by lNikolayl** [babel/babel#15647]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Possible way to reproduce:

```js
import * as babel from '@babel/core';

babel.transform('function someFunctionName(arg1, arg2) {}', { sourceMap: true });
```

### Current and expected behavior

Current source map: 
```json
{
    "version": 3,
    "names": [
        "someFunctionName",
        "arg1",
        "arg2"
    ],
    "sources": [
        "unknown"
    ],
    "sourcesContent": [
        "function someFunctionName(arg1, arg2) {}"
    ],
    "mappings": "AAAA,SAASA,gBAAgBA,CAACC,IAAI,EAAEC,IAAI,EAAE,CAAC"
}
```

After mappings decoding: 
```json
[
  [0, 0, 0, 0],
  [9, 0, 0, 9, 0],
  [25, 0, 0, 25, 0],
  [26, 0, 0, 26, 1],
  [30, 0, 0, 30],
  [32, 0, 0, 32, 2],
  [36, 0, 0, 36],
  [38, 0, 0, 38],
  [39, 0, 0, 39],
]
```
On the previous version of babel (@babel/core: 7.20.12; @babel/generator: 7.20.14) mappings decoding is:
```json
[
  [0, 0, 0, 0],
  [9, 0, 0, 9, 0],
  [25, 0, 0, 25],
  [26, 0, 0, 26, 1],
  [30, 0, 0, 30],
  [32, 0, 0, 32, 2],
  [36, 0, 0, 36],
  [38, 0, 0, 38],
  [39, 0, 0, 39],
]
```

### Environment

npmPackages:
@babel/core: 7.21.5
@babel/generator: 7.21.5

### Possible solution

On [#15022](https://github.com/babel/babel/pull/15022) I've observed this change in `methods.ts` file:
```ts
const nameInfo = _getFuncIdName.call(this, idNode, parentNode);
if (nameInfo) {
  this.sourceIdentifierName(nameInfo.name, nameInfo.pos);
}
```

I suppose it should be moved to `parameters` function under arguments length check.

However I'm not in the context of this change in [#15022](https://github.com/babel/babel/pull/15022) PR.

### Additional context

We are using babel as part of ember-cli build. So, in the updated version we have an issue with source map validation. I was able to localize the issue to source map generation, specially to extra name field in the decoded mappings property of source map. If you will check the current and old behaviour you will find an extra element in the decoded mappings. This element represents the name index in the `names` array.

Note: Not really sure that it's an issue. However anyway it's breaking change of source map validation.

**Comment by liuxingbaoyu** [comment]
> I suppose it should be moved to parameters function under arguments length check.
> 
> However I'm not in the context of this change in https://github.com/babel/babel/pull/15022 PR.

Sorry I didn't understand what you mean, can you explain?

We append the identifier name to `(` on purpose.
Because in many of the methods below, it is more desirable to append the identifier name to `(` than to `"fn"]:function(`.
```js
var a = {
   fn() {},
   fn:function() {},
   [fn]:function() {},
   ["fn"]:function() {},
   [function() {}]: function() {},
   [()=> {}]: function() {},
   [fn]() { },
   ["fn"]() { },
   [function() {}]() { },
   [()=> {}]() { }
}
```

More context here https://github.com/babel/babel/issues/14907

**Comment by lNikolayl** [comment]
Oh, thank you, I got it. Inside Ember pipeline there is sourcemap validation stage and with the new version of babel all sourcemaps marked as invalid due to this change. In this case it's breaking change. Seems it should be addressed to the validator side. The issue is described [here](https://github.com/ben-ng/sourcemap-validator/issues/17).
