### ISSUE TITLE
`this` gets lost in arrow functions with TCO

### ISSUE THREAD

**Issue by jbt** [babel/babel#1564]
It looks like if `this` is used inside a tail-call-optimized arrow function, it gets reset to `undefined` before looping back, which breaks stuff.

Here's the simplest case I could think up:

```js
(function(){
  const foo = () => {
    if(this) return foo();
  }
  foo();
}).call({});
```

That [compiles to](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=(function()%7B%0A%20%20const%20foo%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20if(this)%20return%20foo()%3B%0A%20%20%7D%0A%20%20foo()%3B%0A%7D).call(%7B%7D)%3B):

```js
"use strict";

(function () {
  var _this2 = this;

  var foo = function foo() {
    var _this = _this2;
    var _again = true;

    _function: while (_again) {
      _again = false;

      if (_this) {
        _this = undefined;
        _again = true;
        continue _function;
      }
    }
  };
  foo();
}).call({});
```

Unless I'm being thick, it _should_ get stuck in an infinite loop, but instead the `_this = undefined` line causes the `if` to be falsy the second time round and it doesn't. It looks like it only gets reset if `this` appears before the recursion (e.g. if I changed it to `if(true) return foo();` it _does_ infinite loop.

Obviously this isn't the most sensible real-world scenario, but this was the simplest case I could find. (My real use-case was something like [this state-machine thingy](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=class%20Foo%20%7B%0A%20%20constructor(a)%7B%20this.something%20%3D%20a%3B%20%7D%0A%20%20bar(x)%7B%0A%20%20%20%20const%20baz%20%3D%20(y)%20%3D%3E%20%7B%0A%20%20%20%20%20%20switch(y)%7B%0A%20%20%20%20%20%20%20%20case%201%3A%0A%20%20%20%20%20%20%20%20%20%20if(this.something)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20not%20sure%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20do%20some%20stuff%0A%20%20%20%20%20%20%20%20%20%20return%20baz(2)%3B%0A%20%20%20%20%20%20%20%20case%202%3A%0A%20%20%20%20%20%20%20%20%20%20if(this.something)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20not%20sure%20again%20%20%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20more%20stuff%0A%20%20%20%20%20%20%20%20%20%20return%20baz(3)%3B%0A%20%20%20%20%20%20%20%20default%3A%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20something%20else%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20baz(x)%0A%20%20%7D%0A%7D%0A%0A%0A(new%20Foo(true)).bar(1)%3B) which throws `Cannot read property 'something' of undefined` on the second iteration because `_this` has been set to `undefined`)

**Comment by fkling** [comment]
`this` is replaced with `undefined` because `this` of an **arrow function** is lexically scoped, and you are referencing the module's `this`, which is`undefined`.

This is the output if you use a normal function:

```js
"use strict";

(function () {
  var foo = function foo() {
    var _this = this;

    var _again = true;

    _function: while (_again) {
      _again = false;

      if (_this) {
        _this = undefined;
        _again = true;
        continue _function;
      }
    }
  };
  foo();
}).call({});
```

**Comment by fkling** [comment]
There seems to be some issue with the replacement of the module's `this` value and TCO + arrow functions. It works fine if you use a normal function or no TCO.

**Comment by sebmck** [comment]
Should be as easy as just not touching `this` in arrow functions.

**Comment by jbt** [comment]
Wahey, thanks! :+1:

**Comment by sebmck** [comment]
Sorry for the delay, released as of 5.4.4. Thanks!
