### ISSUE TITLE
[Bug]: @babel/parser 7.22.0 failing to install

### ISSUE THREAD

**Issue by ogardnerffdc** [babel/babel#15654]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

N/A.

### Configuration file name

N/A.

### Configuration

N/A.

### Current and expected behavior

**Current Behaviour**
`@babel/parser` version 7.22.0 is failing to download on our develop pipeline:

```
npm ERR! notarget No matching version found for @babel/parser@^7.22.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/jenkins/.npm/_logs/2023-05-26T14_33_20_485Z-debug-0.log

Error: Unable to install package: Error: "npm install" encountered an error
```

**Expected Behaviour**
`@babel/parser` version 7.22.0 installs without error.

### Environment

- Babel: 7.22.0
- Node: 18.15.0
- npm: 9.5.0
- monorepo: yes

**Comment by JLHwung** [comment]
@babel/parser@7.22.0 is [published](https://www.npmjs.com/package/@babel/parser) on npm. The npmjs.com is the single source of truth.

Please check if you are behind a proxy or using a third party npm registry. There are situations when these cache needs some time to update to the latest version. In the past we have come across these issues after a new version is released https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed It will be solved eventually through time.

**Comment by ogardnerffdc** [comment]
Thanks for the quick reply @JLHwung.

As you suspected, the issue has sorted itself out with time.

Closing the issue. Thanks!
