### ISSUE TITLE
[Bug]: 7.22.0 introduces failure to find modules

### ISSUE THREAD

**Issue by raearnold** [babel/babel#15659]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

This isn't possible due to corporate restrictions, but occurs when running any of our apps using react-bootstrap 0.33* (Bootstrap 3 support), stemming from their Glyphicon component

### Configuration file name

babel.config.js

### Current and expected behavior

We're getting this error in our react-bootstrap3-based app, since 7.22.0 came out

```
    Cannot find module 'core-js/library/fn/symbol.js' from 'node_modules/@babel/runtime-corejs2/helpers/typeof.js'

    Require stack:

      node_modules/@babel/runtime-corejs2/helpers/typeof.js

      node_modules/@babel/runtime-corejs2/helpers/interopRequireWildcard.js

      node_modules/react-bootstrap/lib/index.js
```

I can't post much more troubleshooting info than that as it dives into corporate code

Pinning to 7.21.5 in our app fixes it, but is not an ideal solution.

### Environment

  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
  Monorepos:
    Lerna: 3.22.1
  npmPackages:
    @babel/core: ^7.12.10 => 7.22.0 
    jest: ^26.6.3 => 26.6.3 
    lerna: ^3.22.1 => 3.22.1
    
    Note that this also happens on our CI/CD pipeline boxes, not just local development

### Possible solution

Seems likely related to https://github.com/babel/babel/pull/15633/files#diff-58c78e884cf0f13228f17d48d5a5295a0f1d291d090dedd5e61a368b90af6676

**Comment by nicolo-ribaudo** [comment]
I probably introduced this regression in https://github.com/babel/babel/pull/15633

**Comment by nicolo-ribaudo** [comment]
Working on a fix in https://github.com/babel/babel-polyfills/
