### ISSUE TITLE
[Bug]: Babel 7.22 contains "type": "script" in package.json, which is invalid

### ISSUE THREAD

**Issue by devongovett** [babel/babel#15664]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

N/A

### Current and expected behavior

For example: https://unpkg.com/browse/@babel/types@7.22.0/lib/package.json

This currently breaks Parcel's new resolver, which I am going to fix by ignoring invalid values. https://github.com/parcel-bundler/parcel/issues/9040

Still might be worth fixing though. Valid values for "type" are "module" and "commonjs" according to https://nodejs.org/api/packages.html#type.

### Environment

N/A

**Comment by nicolo-ribaudo** [comment]
Thanks!  I had to manually publish and somehow those files from my local environment "leaked" to the published package. Will fix.

**Comment by liuxingbaoyu** [comment]
Yes, this seems to be a long-standing issue, I've encountered them locally many times. 😕

**Comment by sosukesuzuki** [comment]
FYI I've created a reproduction repository https://github.com/sosukesuzuki-sandbox/babel-7.22-esbuild-warnig-reproducing

**Comment by nicolo-ribaudo** [comment]
Yeah this is easy to fix, I just have to re-release. I'll do it later:)

**Comment by nicolo-ribaudo** [comment]
Re-releasing all the packages published in 7.22.0 that haven't been republished yet. They should be available on npm in ~5 minutes as 7.22.3.
