### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gburke-ppb** [babel/babel#15678]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

We are using `jest`, which is pulling in `babel`.
Having run an `npm upgrade -S`, a later version of `babel` was pulled in (7.22.4) and we are now getting the below error on build.

```
$ npm run build

> cdk@0.1.0 build
> tsc

node_modules/@types/babel__traverse/index.d.ts:321:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

321     [k: `${string}|${string}`]: VisitNode<S, Node>;
         ~
```

### Configuration

```
  "devDependencies": {
    "@types/jest": "^26.0.24",
    "@types/node": "10.17.27",
    "jest": "^26.6.3",
    "ts-jest": "^26.5.6",
    "ts-node": "^8.10.2",
    "typescript": "~4.1.0",
    ...
  },
```

### Current and expected behavior

compilation is failing.  It wasn't before the library version update.

### Environment

```
$ npm --version
9.5.1
```

```
$ node --version
v20.2.0
```

**Comment by ehoogeveen-medweb** [comment]
IIRC these types come from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/babel__traverse, so you probably need to file a bug there instead.

If I'm not mistaken (my TypeScript knowledge is a bit flaky), the type would work as `[k in `${string}|${string}`]` (` in ` instead of `: `).

**Comment by nicolo-ribaudo** [comment]
Yes, type definitions released in the `@types/` packages are not maintained by us.
