### ISSUE TITLE
SourceMap issue: `sources` including full system paths

### ISSUE THREAD

**Issue by getify** [babel/babel#1567]
Running this:

```js
babel.transformFileSync(
   path.join(__dirname,"foo","baz","bam.js"),
   {
      	sourceMaps: true,
        sourceMapName: "bam.es5.js"
   }
);
```

Produces a sourcemap like this:

```js
{ version: 3,
  sources: [ '/full/system/path/foo/baz/bam.js' ],
  file: 'bar.js.map',
  // ..
}
```

As you can see, by default the entire filesystem path is included in the `sources` list when `transformFile[Sync](..)` with an absolute file path. This would almost certainly **never** be the desired behavior for a web served sourcemap, but I can see it may be preferred for using sourcemaps in a node environment.

I know there's the `sourceFileName` option, which you can override this listing(s) in `sources`. I assume the intended behavior is that you're supposed to calculate your own appropriate filepaths and set them with this setting, as the spec calls for them to be relative to the location of where the source map itself is served from. There's also `sourceRoot` which when set and added to the map, means the consumer of the sourcemap is supposed to assume that this value is prepended to every relative URL, including those in the `sources` list.

So, here's my concern: I think it's unsafe for the default behavior to include the entire filesystem path in `sources` if `sourceFileName` is not passed. This default behavior is quite easy to accidentally leak perhaps sensitive/private information in a publicly web accessible file (the source map).

I think the default behavior should change to assume to include only the filename in `sources` with whatever path stripped. For usage in node, where I can imagine having the full path is useful, the `sourceFileName` can be obviously be used to provide a full path as necessary.

I just think the default behavior here should be more conservative and web-safe.

**Comment by sebmck** [comment]
Completely agree. I'll tag this for 6.0.0 since this would be a breaking change.

**Comment by getify** [comment]
:+1:

**Comment by 3y3** [comment]
:+1:

**Comment by jmm** [comment]
@sebmck Would it be at all worthwhile / practical for me to take a crack at this at this point in time? Is there going to be a 6.0 branch at some point?

**Comment by getify** [comment]
We should incorporate this to fix the problems with sourcemaps not being chained together properly: https://github.com/azu/multi-stage-sourcemap
