### ISSUE TITLE
[Bug]: Breaking change in a minor version bump

### ISSUE THREAD

**Issue by schneems** [babel/babel#15679]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
// Anything, the version release caused it to break old `babel.config.js` files
```

### Configuration file name

babel.config.js

### Configuration

```
module.exports = function(api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.'
    )
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          targets: {
            node: 'current'
          }
        }
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ]
    ].filter(Boolean),
    plugins: [
      'babel-plugin-macros',
      '@babel/plugin-syntax-dynamic-import',
      isTestEnv && 'babel-plugin-dynamic-import-node',
      '@babel/plugin-transform-destructuring',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-proposal-object-rest-spread',
        {
          useBuiltIns: true
        }
      ],
      [
        '@babel/plugin-proposal-private-methods',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-proposal-private-property-in-object',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false
        }
      ],
      [
        '@babel/plugin-transform-regenerator',
        {
          async: false
        }
      ]
    ].filter(Boolean)
  }
}

```

### Current and expected behavior

Before the 7.22 release projects that are locked to 7.x with the above config would execute fine. After 7.22.0 the get this error:

```
Compiling...
Compilation failed:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find package '@babel/plugin-proposal-private-methods' imported from /private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/babel-virtual-resolve-base.js
    at new NodeError (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
    at packageResolve (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
    at moduleResolve (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:902:20)
    at defaultResolve (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:985:15)
    at resolve (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:999:12)
    at resolve (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:13:10)
    at tryImportMetaResolve (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/files/plugins.js:123:45)
    at resolveStandardizedNameForImport (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/files/plugins.js:145:19)
    at resolveStandardizedName (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/files/plugins.js:154:12)
    at loadPlugin (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/files/plugins.js:47:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:139:16)
    at createDescriptor.next (<anonymous>)
    at step (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/gensync/index.js:291:5)
    at /private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/gensync/index.js:43:15)
    at Function.all (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:101:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:98:17)
    at createPluginDescriptors.next (<anonymous>)
    at /private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/gensync-utils/functional.js:21:23
    at Generator.next (<anonymous>)
    at mergeChainOpts (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-chain.js:192:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/config-chain.js:78:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/private/tmp/79de2b03fd57b181232892d89e7e9920/myapp/node_modules/@babel/core/lib/config/partial.js:79:62)
    at loadPrivatePartialConfig.next (<anonymous>) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I originally reported this in https://github.com/rails/rails/issues/48372, however, Rails 6 is no longer being maintained. The reason that this broke is because it is locked to babel 7.x as long as there are no breaking changes with 7.x it will continue to work, however 7.22 .0 changed the name of a module used in `babel.config.js` so the old module name expected in `babel.config.js` is no longer installed and this causes an error.

### Environment

```
$ npx envinfo --preset babel
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 13.4
  Binaries:
    Node: 19.6.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
  npmPackages:
    webpack: ^4.46.0 => 4.46.0
```

### Possible solution

Treat this as a bug/regression. Rollback the naming change in a new release of 7.22.x this will un-break old applications. Then release the breaking change in a new major version (presumably 8.x). 

There's nothing wrong with breaking changes (as long as they're intentional) provided that the major version is rev-d.

In the future, I recommend adopting the policy that all module renaming is a breaking change. For some minor prior art from another language, it's commonly considered a breaking change in Rust libraries to rename a module https://stackoverflow.com/a/41195476/147390. 

### Additional context

You're awesome, and babel is great! Thanks for all your work 💜

**Comment by schneems** [comment]
> Two good solutions are

Unfortunately, we cannot fix this in webpacker or Rails 6 as both of them are no longer under development and locked to a specific major version of babel. As long as there are no breaking changes to babel, that code will continue to work.

I understand the underlying dependency chain that is causing the issue. My main argument is that a change in babel should not break code that was previously working when people depending on it were locked to a specific major.

If your stance is that the developers who wrote this code (not me) "did it wrong," I would push back by asking how could we re-design the feature so that is either:

- Emits a warning
- Is harder than "doing it right"
- Not possible

That wouldn't fix this case, or any future cases as more plugins get renamed, but it might alleviate some future pain and guide people how to use the feature as you're expecting.

It would raise the question, what exactly did the developer do wrong? It sounds like you're saying they're importing a module without requiring it explicitly. I would agree that's generally not a good idea unless one of the reasons that library exists is to expose other modules. I'm not intimately familiar with this ecosystem (and not affiliated with webpacker gem at all), this npm library.

> @babel/preset-env is a smart preset that allows you to use the latest JavaScript without needing to micromanage which syntax transforms (and optionally, browser polyfills) are needed by your target environment (s).

Looking at the docs:

> [Babel plugins](https://github.com/babel/babel/blob/main/packages/babel-compat-data/scripts/data/plugin-features.js) - both full and shorthand names are supported, for example the following are functionally equivalent:

It looks like a feature of this library is to export plugins. If that's the case than a change in the name of available exported plugins would be a breaking change (again, this is a very weak assertion I'm not really that familiar with the ecosystem and want to lay my cards on the table).

**Comment by liuxingbaoyu** [comment]
> It looks like a feature of this library is to export plugins. If that's the case than a change in the name of available exported plugins would be a breaking change (again, this is a very weak assertion I'm not really that familiar with the ecosystem and want to lay my cards on the table).

No, it only contains `@babel/plugin-transform-xxx`, `@babel/plugin-proposal-xxx` needs to be installed manually by the developer.
This is a problem of nodejs dependency layout. When package A depends on package B and package B depends on package C, package A can sometimes directly use package C.
We're really just not using a dependency anymore (renaming is equivalent to removing dependency A and adding dependency B), and obviously changes to a package's internal dependencies should not be considered breaking changes.

But I agree that the current ramifications are somewhat annoying, and maybe consider keeping the old dependencies for now.

**Comment by nicolo-ribaudo** [comment]
> If your stance is that the developers who wrote this code (not me) "did it wrong," I would push back by asking how could we re-design the feature so that is either:
> - Emits a warning
> - Is harder than "doing it right"
> - Not possible

There are three package managers in the JavaScript ecosystem: npm, pnpm and yarn. By default, both pnpm and yarn prevent this problem:
- pnpm generates the first `node_modules` layout I mentioned in https://github.com/babel/babel/issues/15679#issuecomment-1573896798, so this case would have always been an error and it wouldn't have been possible to accidentally rely on it
- yarn (since version 2) doesn't use `node_modules` by default, and makes sure that every package can only depend on the packages it explicitly lists in its dependencies. Yarn 1 didn't support a way to catch this problem.
- npm has an [accepted RFC](https://github.com/npm/rfcs/blob/eb927e8a22d30ccf2aed173d5a83ee4fbfb2b3e3/accepted/0042-isolated-mode.md) for an opt-in way to catch these problems, but:
  - it's opt-in, so it doesn't catch the problem by default
  - as far as I know, it has not been actually developed yet

> I would agree that's generally not a good idea unless one of the reasons that library exists is to expose other modules. I'm not intimately familiar with this ecosystem (and not affiliated with webpacker gem at all), this npm library.
> 
> > @babel/preset-env is a smart preset that allows you to use the latest JavaScript without needing to micromanage which syntax transforms (and optionally, browser polyfills) are needed by your target environment (s).
>
> Looking at the docs:
>
> > [Babel plugins](https://github.com/babel/babel/blob/main/packages/babel-compat-data/scripts/data/plugin-features.js) - both full and shorthand names are supported, for example the following are functionally equivalent:
>
> It looks like a feature of this library is to export plugins. If that's the case than a change in the name of available exported plugins would be a breaking change (again, this is a very weak assertion I'm not really that familiar with the ecosystem and want to lay my cards on the table). 

The point of the preset is not to re-export all the plugins, but to abstract the plugins away from the Babel users. Instead of enabling the various plugins in the Babel config, that thus needs to be installed individually, the preset allows transforming all the necessary syntax without having to enable the individual plugins in the config. If a plugin is manually listed, it's "opting out" from being just enabled by default and thus its usage should not be considered as being enabled inside the preset, because it's not.

> Unfortunately, we cannot fix this in webpacker or Rails 6 as both of them are no longer under development and locked to a specific major version of babel

I'm not familiar at all with how Rails works, doesn't it give access to a `package.json` files that users can edit?

That said, I'm thinking about how to fix this in a way that lets us handle `@babel/preset-env`'s dependencies as an implementation detail without breaking major unmaintained packages using Babel. Even just a good error message explaining a workaround is better than the status quo.

**Comment by nicolo-ribaudo** [comment]
@schneems I'm implementing a workaround for this specifically, but in order to do it I need to know how to detect if I'm running in a rails 6 app. I have never used anything in the Ruby ecosystem, and I'm struggling to get even a basic app do install 😅 

Could you create one, and just commit everything and push it to GitHub, linking specifically to where the Babel config is?

**Comment by craftonixinc** [comment]
Is there any quick workaround for a newbie who doesn't want to get into the details?
I'm trying to follow the same path as @schneems and the Heroku workaround https://devcenter.heroku.com/articles/getting-started-with-rails6#fix-a-babel-regression still gives an error:
```
Compilation failed:
Hash: 50c91179df559b106792
Version: webpack 4.47.0
Time: 208ms
Built at: 2024-03-06 11:41:34 a.m.
 2 assets
Entrypoint application = js/application-a0a05a9c25d4f054cd70.js js/application-a0a05a9c25d4f054cd70.js.map
[0] ./app/javascript/packs/application.js 1.61 KiB {0} [built] [failed] [1 error]

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL]: --- PLACEHOLDER PACKAGE ---
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
dependencies (or devDependencies) in the package.json file.
Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies
to work around this error. This will make this message go away.
```

I added "@babel/plugin-proposal-private-property-in-object" to my devDependencies as follows:
```
diff --git a/babel.config.js b/babel.config.js
index 19a07f3..f42d298 100644
--- a/babel.config.js
+++ b/babel.config.js
@@ -54,7 +54,7 @@ module.exports = function(api) {
         }
       ],
       [
-        '@babel/plugin-proposal-private-methods',
+        '@babel/plugin-transform-private-methods',
         {
           loose: true
         }
diff --git a/package.json b/package.json
index b3f2a56..8d6560b 100644
--- a/package.json
+++ b/package.json
@@ -12,6 +12,7 @@
   },
   "version": "0.1.0",
   "devDependencies": {
-    "webpack-dev-server": "^3"
+    "webpack-dev-server": "^3",
+    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
   }
 }
```

but I'm still getting the same error.

**Comment by nicolo-ribaudo** [comment]
Can you check in your project where `@babel/plugin-proposal-private-property-in-object` is used, and use `@babel/plugin-transform-private-property-in-object` instead? (adding it to your deps)?

**Comment by marcioecom** [comment]
@craftonixinc I installed `@babel/plugin-proposal-private-methods` and `@babel/plugin-proposal-private-property-in-object`, it worked for me

```bash
yarn add @babel/plugin-proposal-private-methods @babel/plugin-proposal-private-property-in-object
```
