### ISSUE TITLE
[Bug] Cannot find module '@babel/plugin-proposal-object-rest-spread'

### ISSUE THREAD

**Issue by ijlee2** [babel/babel#15670]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I use these Babel plugins along with Rollup to bundle a package called `ember-container-query`:

```json5
/* package.json */
{
  "dependencies": { /* ... */ },
  "devDependencies": {
    "@babel/core": "^7.21.8",  // Tried to update to 7.22.1
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-decorators": "^7.21.0",
    "@babel/preset-typescript": "^7.21.5",
    "@babel/runtime": "^7.21.5",
    "rollup": "^3.23.0",
    "rollup-plugin-ts": "^3.2.0",
    "typescript": "^5.0.4"
  }
}
```

I'm not sure what might have recently changed. It seemed like, as soon as I update (1) a dependency that transitively updates `@babel/core` or (2) `@babel/core` directly, I can't build the `dist` folder.

- Pull request: https://github.com/ijlee2/ember-container-query/pull/194
- Deploy logs: https://app.netlify.com/sites/ember-container-query/deploys/6476dafcba91680008108332

```sh
7:29:09 AM: . prepare: > rollup --config
7:29:10 AM: . prepare:
7:29:10 AM: . prepare:  → dist...
7:29:11 AM: . prepare: [!] Error: Cannot find module '@babel/plugin-proposal-object-rest-spread'
7:29:11 AM: . prepare: Require stack:
7:29:11 AM: . prepare: - /opt/build/repo/node_modules/.pnpm/rollup-plugin-ts@3.2.0_6xndw7bhbbvnayyhgbtm25ismm/node_modules/rollup-plugin-ts/dist/esm/index.js
7:29:11 AM: . prepare:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
7:29:11 AM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
7:29:11 AM: . prepare:     at resolve (node:internal/modules/cjs/helpers:114:19)
7:29:11 AM: . prepare:     at getDefaultBabelOptions (file:///opt/build/repo/node_modules/.pnpm/rollup-plugin-ts@3.2.0_6xndw7bhbbvnayyhgbtm25ismm/node_modules/rollup-plugin-ts/src/transpiler/babel.ts:112:7)
7:29:11 AM: . prepare:     at Object.options (file:///opt/build/repo/node_modules/.pnpm/rollup-plugin-ts@3.2.0_6xndw7bhbbvnayyhgbtm25ismm/node_modules/rollup-plugin-ts/src/plugin/typescript-plugin.ts:291:22)
7:29:11 AM: . prepare:     at /opt/build/repo/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:26325:18
7:29:11 AM: . prepare:     at getInputOptions (/opt/build/repo/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:26318:67)
7:29:11 AM: . prepare:     at rollupInternal (/opt/build/repo/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:26259:72)
7:29:11 AM: . prepare:     at build (/opt/build/repo/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/bin/rollup:1540:20)
7:29:11 AM: . prepare:     at runRollup (/opt/build/repo/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/bin/rollup:1663:21)
7:29:11 AM: . prepare: undefined
7:29:11 AM: . prepare: /opt/build/repo/ember-container-query:
7:29:11 AM: . prepare:  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ember-container-query@4.0.2 build: `rollup --config`
7:29:11 AM: . prepare: Exit status 1
```

The error message shows that the error might have originated from `rollup-plugin-ts`, but [that package hasn't been updated since January](https://github.com/wessberg/rollup-plugin-ts/releases). The package refers to `@babel/plugin-proposal-object-rest-spread` in 1 place:

- https://github.com/wessberg/rollup-plugin-ts/blob/v3.2.0/src/transpiler/babel.ts#L112

### Configuration

```json5
/* babel.config.json */
{
  "presets": [["@babel/preset-typescript"]],
  "plugins": [
    "@embroider/addon-dev/template-colocation-plugin",
    ["@babel/plugin-transform-typescript", { "allowDeclareFields": true }],
    ["@babel/plugin-proposal-decorators", { "version": "legacy" }],
    "@babel/plugin-proposal-class-properties"
  ]
}
````

### Current and expected behavior

I can update dependencies to their next minor or patch version without encountering a breaking change (in this case, encountering the error message `Cannot find module '@babel/plugin-proposal-object-rest-spread'`).

### Environment

- Babel: 7.21.8, 7.22.0, 7.22.1
- Node: 16 (latest version in CI)
- Package manager: pnpm (latest version in CI)  
- Monorepo: yes

### Additional context

The same error occurred in another repo called [`@embroider/addon-blueprint`](https://github.com/embroider-build/addon-blueprint/actions/runs/5123413480/jobs/9213887669), which generalizes how I created the package `ember-container-query`.

**Comment by ijlee2** [comment]
The issue disappeared in https://github.com/ijlee2/ember-container-query/pull/196 and https://github.com/ijlee2/ember-container-query/pull/197 (not sure what changed, which is somewhat concerning). I'll close this issue for now, as I was able to update my package's dependencies.

**Comment by nicolo-ribaudo** [comment]
The problem is that rollup-plugin-ts requires `@babel/plugin-proposal-object-rest-spread` (https://github.com/wessberg/rollup-plugin-ts/blob/c10b718f382b9e7752f55e87cbf4881e80e066b9/src/transpiler/babel.ts#L112) without declaring it as a dependency (https://github.com/wessberg/rollup-plugin-ts/blob/c10b718f382b9e7752f55e87cbf4881e80e066b9/package.json#L63). You are probably lucky and that plugin is already in your node_modules for unrelated reasons, but it could break at any time.

**Comment by ijlee2** [comment]
@nicolo-ribaudo Thank you for investigating the issue further.

I will mention the issue to `@embroider/addon-blueprint`, which provides a share configuration, to understand better whether the blueprint could list `@babel/plugin-proposal-object-rest-spread` as a development dependency (somewhat a patch for `rollup-plugin-ts`), or `rollup-plugin-ts` should list its dependencies correctly.
