### ISSUE TITLE
Trailing commas in object literals create incorrect whitespace

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#1569]
```js
let obj = {
  foo: 'foo',
  bar: 'bar'
};
// outputs:
let obj = {
  foo: 'foo',
  bar: 'bar'
};
```
but:
```js
let obj = {
  foo: 'foo',
  bar: 'bar',
};
// outputs:
let obj = {
  foo: 'foo',
  bar: 'bar' };
```

This is a super critical high-priority bug, I'm super angry at you @sebmck. Why are you destroying my life? I hate you with every cell in my body and hope that you get hit by a bus. :trollface:

**Comment by sebmck** [comment]
Duplicate of #1304.
