### ISSUE TITLE
[Bug]: Error: Cannot find package '@babel/plugin-proposal-class-properties' imported from /MyProject/babel-virtual-resolve-base.js

### ISSUE THREAD

**Issue by varunnath** [babel/babel#15695]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

My pakage.json have the dependencies as below

"devDependencies": {
    "@babel/cli": "^7.22.5",
    "@babel/core": "^7.22.5",
    "@babel/preset-env": "^7.22.5"
  }

### Configuration file name

.babelrc

### Configuration

{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "current"
      }
    }]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}

### Current and expected behavior

I need to run node project, but currently babel build is throwing the error
Cannot find package '@babel/plugin-proposal-class-properties' imported from /MyProject/babel-virtual-resolve-base.js

### Environment

Node: 16.7.0
Ubunutu 18.04.5 LTS

**Comment by varunnath** [comment]
Can anyone help me to solve this issue

**Comment by nicolo-ribaudo** [comment]
All the plugins you use in your Babel config need to be defined as dependencies in your package.json, the same way as you would do it for any other package.

**Comment by qburst-varunnath** [comment]
> All the plugins you use in your Babel config need to be defined as dependencies in your package.json, the same way as you would do it for any other package.

Thanks for the quick reply

Or is it not necessary to add these in babelrc, seems available in preset-env?

**Comment by nicolo-ribaudo** [comment]
Yes, they are included :)

This config should be enough:
```json
{
  "targets": { "node": "current" },
  "presets": ["@babel/env"]
}
```
