### ISSUE TITLE
v7.22.5 inproduced Breaking Changes for Preset Env

### ISSUE THREAD

**Issue by daniluk4000** [babel/babel#15694]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

When I use @babel/plugin-proposal-private-property-in-object after update to v7.22.5 I'll HAVE to add it to devDependencies even if it's required by dependencies of some plugin. 

This is a breaking changes for presets like @nuxt/babel-preset-app (FYI @danielroe @pi0 this broke Nuxt 2 clear install).

Full error:

`Error: [BABEL] /WebstormProjects/unsubscribe/frontend/.nuxt/client.js: --- PLACEHOLDER PACKAGE ---
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
dependencies (or devDependencies) in the package.json file.
Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies
to work around this error. This will make this message go away.`

### Describe the solution you'd like

This had to be at least mentioned in release logs. Also it could be a deprecation _warning_

### Describe alternatives you've considered

Don't break existing setups in minor versions, the same thing as #15679 suggested.

**Comment by danielroe** [comment]
Fix is in progress at https://github.com/nuxt/nuxt/pull/21488

**Comment by daniluk4000** [comment]
> Fix is in progress at [nuxt/nuxt#21488](https://github.com/nuxt/nuxt/pull/21488)

Great! Didn't notice that, sorry for ping.

Btw, we've tried same solution in our internal library - didn't work. I had to add this to devDependencies, otherwise it refused to work.

**Comment by nicolo-ribaudo** [comment]
> That's exactly why this is a breaking change

That's why we released `@babel/plugin-proposal-private-property-in-object` as a pre-release version: because it had a breaking change, and releasing it as a "normal" version would have been a semver violation.

Even if we had released it as 8.0.0, this problem would have not being solved because nuxt didn't specify anywhere that it wanted a version compatible with ^7.0.0 (so it would have automatically received v8.0.0).

**Comment by daniluk4000** [comment]
> > That's exactly why this is a breaking change
> 
> That's why we released `@babel/plugin-proposal-private-property-in-object` as a pre-release version: because it had a breaking change, and releasing it as a "normal" version would have been a semver violation.
> 
> Even if we had released it as 8.0.0, this problem would have not being solved because nuxt didn't specify anywhere that it wanted a version compatible with ^7.0.0 (so it would have automatically received v8.0.0).

But if preset-env requires it, it automatically becomes the default when running with clear lockfile.

If it is simply added to any library, in lockfile you will see two versions

![image](https://github.com/babel/babel/assets/10450717/d3517fd2-8939-415a-b096-adec0afc1a44)

When I call require it imports 7.21.0-placeholder-for-preset-env.2 but not 7.21.11 :(

**Comment by daniluk4000** [comment]
I'm closing this as Nuxt fixed the issue, but I still think this had to be mentioned in changelog with upgrade steps/advices.
