### ISSUE TITLE
[Bug]: Git shows Babel/preset-modules and Babel/plugin-transform-typeof-symbol as affected by malware

### ISSUE THREAD

**Issue by orosl** [babel/babel#15697]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

-

### Configuration file name

package.json

### Current and expected behavior

Hello Babel and Babel community,

**This might or might not be an issue from your side and it might be related to the way Git sees your dependencies.**

A summary of the issue:

In our code we have Angular 11.2.5 which uses a series of Babel modules(i.e. babel/preset-env": "7.12.11" which later on use babel/preset-modules and babel/plugin-transform-typeof-symbol as third party dependencies). 
Git's Vulnerability Bot is showing the following dependencies used by Babel as affected by malware:

![image](https://github.com/babel/babel/assets/61190406/96ef33a6-062e-4a22-8d37-b83d14186d45)

The more in depth description is looking like this:

![image](https://github.com/babel/babel/assets/61190406/db5a2db4-6493-4039-952b-d6e82363c62b)

I checked Babel's official page; the version _babel/preset-modules@0.1.5_(as suggested by Git) and no vulnerability of this type is mentioned. 
Nonetheless, the following fake preset-modules package is:
https://www.npmjs.com/package/preset-modules

! We have no preset-module package installed except for the one associated with babel.

I assume this is a type of typosquatting attack and Babel should not be involved in this. GitHub must be informed about this and the vulnerability associated to Babel should be removed. Although, this is only an assumption. 

Is anyone else encountering this issue?

### Environment

"@babel/preset-env": "7.12.11"

**Comment by nicolo-ribaudo** [comment]
Mmmmm... Is it `@babel/preset-modules` (with the @) or `babel/preset-modules`?

**Comment by nicolo-ribaudo** [comment]
Also, those two GHSAs do not show up in the GHSA database 🤔 
- https://github.com/advisories?query=GHSA-23gm-4mrr-r6pg
- https://github.com/advisories?query=GHSA-3rhh-96r-68h4

**Comment by orosl** [comment]
Hi @nicolo-ribaudo,

We use @babel/preset-modules, as you can find in the screenshot below:

![image](https://github.com/babel/babel/assets/61190406/f68bfc9c-f80b-4893-9248-95cc2cff5041)


It doesn't make sense why Git bot is still showing that up for every PR we create..

**Comment by nicolo-ribaudo** [comment]
Can you share the link of the second screenshot?

**Comment by orosl** [comment]
I assume you mean this one:
**preset-modules**: https://github.com/advisories/GHSA-23gm-4mrr-r6pg

This is the other one **plugin-transform-typeof-symbol**: https://github.com/advisories/GHSA-3rhh-9j6r-68h4

**Comment by nicolo-ribaudo** [comment]
These vulnerability are not about the packages prefixes with `@babel/`. I think it's a bug in the bot you are using for vulnerability reports, which doesn't distinguish scoped packages. Please report it to them!
