### ISSUE TITLE
[Docs]: Slack invite link is broken (again)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [babel/babel#15713]
<details>
<summary>Template parts not applicable for this docs issue</summary>
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

n/a

### Configuration

n/a

### Current and expected behavior

n/a

### Environment

n/a

### Possible solution

n/a
</details>

### Additional context

Similar to #15538: I get _This link is no longer active_ trying to join the Slack.

#15545 _looked_ like it would fix things, but the links there are also invalid.

Could I join the Slack please? :smile:

**Comment by nicolo-ribaudo** [comment]
Thanks, I updated the slack.babeljs.io invite code. The default expiration is 30 days, and we probably forgot to set the old one to unlimited 😅

**Comment by JoshuaKGoldberg** [comment]
Awesome thanks! 🙌
