### ISSUE TITLE
`this` transpiles to `undefined`

### ISSUE THREAD

**Issue by hzr** [babel/babel#1573]
`this` in the global scope transpiles to `undefined`: http://babeljs.io/repl/#?code=this

Bisecting suggests this was introduced in https://github.com/babel/babel/commit/cfffaf6cdbaafdbdfe5f58e4d288b05af04b521c

**Comment by AluisioASG** [comment]
Expected behavior, see [the FAQ](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-).

**Comment by hzr** [comment]
Thanks.

**Comment by sebmck** [comment]
That's definently the wrong commit. See also #562, #814, #730, #733 etc.

**Comment by hzr** [comment]
@sebmck Thanks, I missed the part about Babel treating input as a module by default. And I can see how that commit is wrong considering the bump in dev dependencies.

Thanks for all your hard work!
