### ISSUE TITLE
[Bug]: Array.prototype.includes() on Firefox <=101

### ISSUE THREAD

**Issue by simo-an** [babel/babel#15735]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

```js
function isIncluded(array, data) {
  return array.includes(data)
}
```

REPL

https://babel.dev/repl#?browsers=firefox%20101&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgSUgGxAEwKY4AUAhgE6nECeANIjsVMQJSIDeAUIoqXlCKUjIVKAOhhZceFIXqMm7AL5A&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.22.5&externalPlugins=&assumptions=%7B%7D

I want to know why `include` function is not-supported on firefox 101 and transfer to the following code:
```
import "core-js/modules/es.array.includes.js";
function isIncluded(array, data) {
  return array.includes(data);
}
```

If I change targets to `firefox 102` , the `include` function is support.

Anyone know whether it is a bug of feature ?  Thanks very much!

### Configuration file name

babel.config.json, package.json

### Current and expected behavior

```js
function isIncluded(array, data) {
  return array.includes(data)
}
```

was transfered to 
```
import "core-js/modules/es.array.includes.js";
function isIncluded(array, data) {
  return array.includes(data);
}
```

on targets: firefox 101

Babel [REPL](https://babel.dev/repl#?browsers=firefox%20101&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgSUgGxAEwKY4AUAhgE6nECeANIjsVMQJSIDeAUIoqXlCKUjIVKAOhhZceFIXqMm7AL5A&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.22.5&externalPlugins=&assumptions=%7B%7D) is provided

### Environment

Babel [REPL](https://babel.dev/repl#?browsers=firefox%20101&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgSUgGxAEwKY4AUAhgE6nECeANIjsVMQJSIDeAUIoqXlCKUjIVKAOhhZceFIXqMm7AL5A&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.22.5&externalPlugins=&assumptions=%7B%7D) is provided

**Comment by simo-an** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#browser_compatibility

`includes` is supported after firefox 43

**Comment by liuxingbaoyu** [comment]
https://github.com/zloirock/core-js/blob/1893217ded979cff4f7110a8de4cb08ebcd78feb/packages/core-js-compat/src/data.mjs#L252
The upstream package `core-js-compat` says FF99-101 broken on sparse arrays.

**Comment by simo-an** [comment]
> https://github.com/zloirock/core-js/blob/1893217ded979cff4f7110a8de4cb08ebcd78feb/packages/core-js-compat/src/data.mjs#L252 The upstream package `core-js-compat` says FF99-101 broken on sparse arrays.

Oh, thank you very much.
