### ISSUE TITLE
[Bug]: Transform API always loads browserlist config

### ISSUE THREAD

**Issue by molisani** [babel/babel#15730]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

The following is only reproducible when `browserslist` decides to print a message to the console when the config is loaded (such as when your installation of caniuse-lite is outdated).

```ts
import babel from "@babel/core";

babel.transform("var x = 1;", {});
// Browserslist: caniuse-lite is outdated. Please run:
//   npx browserslist@latest --update-db
//   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

babel.transform("var x = 1;", {
    // this flag is (rightfully) undocumented and results in a TypeScript error
    browserslistConfigFile: false,
});
// no output
```

### Current and expected behavior

When using the `babel.transform` API, no browser targets are specified but `browserslist.loadConfig` is called. This config is not used, and the set of targets is not updated to include browsers. However, this is still disruptive as the `browserslist` package prints an occasional update reminder to the console, which can be confusing to end users when we do not target browsers.

Babel should not pull in this config if it is not needed (not targeting browsers).

### Environment

- Babel version: 7.16.0
- Node version: 18.16.0
- npm version: 8.19.4
- OS: Windows 10
- Monorepo: no

### Possible solution

The `@babel/helper-compilation-targets` package uses an option `ignoreBrowserslistConfig` to determine whether or not to load the browserslist config.

https://github.com/babel/babel/blob/cc110c63e93f93f876e45511bd40b0aa81c6dfbd/packages/babel-helper-compilation-targets/src/index.ts#L212-L216

The `ignoreBrowserslistConfig` option is calculated inside of `resolveTargets` by observing the value of `browserslistConfigFile`. It is only ignored if `browserslistConfigFile` is exactly `false`. Note that if `browserslistConfigFile` is `undefined`, then `ignoreBrowserslistConfig` will be `false`.

https://github.com/babel/babel/blob/cc110c63e93f93f876e45511bd40b0aa81c6dfbd/packages/babel-core/src/config/resolve-targets.ts#L41-L48

The default value for `browserslistConfigFile` is `false`, but it is set on the `options` object here and not on the `merged` precursor which is what is passed into `resolveTargets`.

https://github.com/babel/babel/blob/cc110c63e93f93f876e45511bd40b0aa81c6dfbd/packages/babel-core/src/config/partial.ts#L120-L130

The end result is that for use cases with no targets: `browserslistConfigFile` is always `undefined`, which means `ignoreBrowserslistConfig` is false, which means that the `browserslist` config is always loaded. A potential solution would be to refactor some of the logic of `loadPrivatePartialConfig` to construct the `options` value first and then pass that into `resolveTargets` before saving the result back to `options.targets`.

**Comment by Solo-steven** [comment]
Hi @liuxingbaoyu, I would like to take it issue if no one else is working on it, thanks ~

**Comment by nicolo-ribaudo** [comment]
Yes please! If you need any help feel free to ask here :)



---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest [name-of-the-package-to-test]` to run the tests
    - If some fixture test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

`[name-of-the-package-to-test]` might be `babel-core` or `babel-helper-compilation-targets` in this case (you can also specify both and it will run tests for both packages)

**Comment by Solo-steven** [comment]
Hi @molisani, Could you provide me the `.browserslistrc` that can console out something, I am not familiar with it so I am not sure if babel is loading config or not. thanks ~

**Comment by nicolo-ribaudo** [comment]
You can create a `.browserslistrc` file with invalid syntax, so that it throws when loaded:
```
abc
def
```

**Comment by nicolo-ribaudo** [comment]
Mh I realized that the `browserslistConfigFile` option is indeed the expected way to avoid loading the browserslist config, and it's documented at https://babeljs.io/docs/options#browserslistconfigfile.

You should verify is this still happens:
> When using the babel.transform API, no browser targets are specified but browserslist.loadConfig is called. This config is not used, and the set of targets is not updated to include browsers.

Ignoring those browsers is wrong, but if we are actually using them then everything is working as expected. You can verify this by writing some targets in the browserslistrc file and using preset-env's debug option
```js
babel.transformSync("some; code;", {
   presets: [["@babel/preset-env", { "debug": true }]]
});
```

**Comment by Solo-steven** [comment]
@nicolo-ribaudo Thanks, I found the same result by using the `transform` API from `@babel/core`, the`browserslistConfigFile` seems to work as expected. 

And seems the `transformSync` API works as expected too, if I set `browserslistConfigFile: false` no error is thrown out. (if 
 the `browserslistrc` is valid)

**Comment by Solo-steven** [comment]
Hi @nicolo-ribaudo ,  my test result shows that : 
|                   | `browserListrc` is valid |`broserslistrc` is not valid    |
| :---           |    :----:   |          ---: |
| `browserslistConfigFile` is false      |  no error thrown       | no error thrown   |
|  `browserslistConfigFile` is true   |  no error thrown       |  error thrown     |

it seems like every thing works as expected. since the `browserslistConfigFile` default is true, it is expected to load `browserslistrc` when the developer does not manually config it

**Comment by nicolo-ribaudo** [comment]
Yes, thank you for investigating!

I will close this issue, but if in the next few days I'll find something you could work on I'll ping you :)

**Comment by molisani** [comment]
My apologies, I think that when I was first testing this I was using a pre-`7.13.0` version so the [`browserslistConfigFile` option](https://babeljs.io/docs/options#browserslistconfigfile) wasn't exposed. This meant that it wasn't reflected in the TypeScript types and if I remember correctly, may have caused a config validation error. That being said, with this config now exposed this is a non-issue as it can be manually disabled. Thanks @Solo-steven for doing the testing even if it meant there was nothing to do! 😄
