### ISSUE TITLE
The order of operations gets garbled when template strings used in a boolean expression.

### ISSUE THREAD

**Issue by rollokb** [babel/babel#1575]
I noticed that a template string adjacent to a boolean operator like `&&` or `||` transpiles to es5 in such a way that it may garble the proper order of operations.

For instance this template string

    const url = `/api/resource/${id}` || otherURL;

Will compile to

    var url = '/api/resource/' + id || otherURL;

This is semantically quite different.

**Comment by topaxi** [comment]
Well since `+` has a higher precedence than the `||` operator, your examples are actually equivalent.

Checkout the following link to compare the precedence of all operators:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by sebmck** [comment]
Yep, @topaxi is completely right.

```javascript
var url = '/api/resource/' + id || otherURL;
```

and

```javascript
var url = ('/api/resource/' + id) || otherURL;
```

are equivalent due to operator precedence.
