### ISSUE TITLE
Plugin babel-plugin-module-resolver is no longer updated.

### ISSUE THREAD

**Issue by trevisanweb** [babel/babel#15764]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

The plugin is mentioned to solve aliasing in typescript, however the author archived the repository on Jun 8, 2023

### Describe the solution you'd like

This configuration can come directly from babel, which would use the tsconfig.json file using the existing configurations to apply both the alias and other configurations

### Describe alternatives you've considered

I looked for other plugins to use as a solution, but none at a level of excellence to use in production.

**Comment by pencilcheck** [comment]
babel-plugin-module-resolver doesn't work when babel.config.cjs is using .cjs, so I might not use it anymore.

**Comment by liuxingbaoyu** [comment]
Since the repository has been unarchived, I will close this issue.
