### ISSUE TITLE
babel CLI "--no-foo" help worded confusingly

### ISSUE THREAD

**Issue by tomxtobin** [babel/babel#1577]
For three of the help lines printed out for `babel --help`, the wording is a bit confusing:
```
--no-non-standard                  enable support for JSX and Flow
--no-highlight-code                ANSI syntax highlight code frames
--no-comments                      output comments in generated output
```
Given the `--no-` prefix, shouldn't that be something like:
```
--no-non-standard                  disable support for JSX and Flow
--no-highlight-code                disable ANSI syntax highlighting of code frames
--no-comments                      strip comments from generated output
```
The current wording makes it sound like the opposite effect is being achieved. o_O

**Comment by thejameskyle** [comment]
It might be better to update them to be this:

```
--[no-]non-standard                  enable/disable support for JSX and Flow (on by default)
--[no-]highlight-code                enable/disable ANSI syntax highlighting of code frames (on by default)
--[no-]comments                      output/strip comments from generated output (on by default)
```

These could be added to any of the `boolean` options. @sebmck thoughts?

If not, here's the [options file](https://github.com/babel/babel/blob/024e4454a1e3778b0f9b6d081d5f4e792f6035db/src/babel/transformation/file/options.json), PRs welcome to update the descriptions.

**Comment by sebmck** [comment]
Sure. Relevant file is [here](https://github.com/babel/babel/blob/master/src/babel/transformation/file/options.json).

**Comment by tomxtobin** [comment]
The new help for `--no-comments` is worded awkwardly IMHO:
```
--no-comments                      strip/output comments in generated output (on by default)
```
It's unclear whether "on by default" means to strip or output the comments. Also, the "strip/output" ordering here is reversed from the "enable/disable" of the other two.

Two possible solutions:
```
--no-comments                      output/strip comments in generated output (output by default)
--no-comments                      enable/disable comments in generated output (on by default)
```
It might be best to go with the latter, if it means consistency with the others.

**Comment by sebmck** [comment]
Happy to take PRs with alternate wording.
