### ISSUE TITLE
`for-of` boilerplate to helper function?

### ISSUE THREAD

**Issue by impinball** [babel/babel#1578]
The boilerplate for `for-of` includes a try-catch-finally block and a try-finally block. These are very hardly optimized by engines, both by SpiderMonkey and V8. Here's an example:

```js
// Input
for (let i of bar) {
  foo(i)
}
```

```js
// Output:
var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
  for (var _iterator = bar[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var i = _step.value;

    foo(i);
  }
} catch (err) {
  _didIteratorError = true;
  _iteratorError = err;
} finally {
  try {
    if (!_iteratorNormalCompletion && _iterator["return"]) {
      _iterator["return"]();
    }
  } finally {
    if (_didIteratorError) {
      throw _iteratorError;
    }
  }
}
```

Couldn't that boilerplate be all thrown into its own helper function? It would speed up code significantly that use these loops.

```js
function _forOf(iterable, loop) {
  var normalCompletion = true;
  var didError = false;
  var iter, iterError, step;

  try {
    for (iter = iterable[Symbol.iterator]();
        !(normalCompletion = (step = iter.next()).done);
        normalCompletion = true) {
      loop(step, value);
    }
  } catch (err) {
    didError = true;
    iterError = err;
  } finally {
    try {
      if (!normalCompletion && iter["return"]) {
        iter["return"]();
      }
    } finally {
      if (didError) {
        throw iterError;
      }
    }
  }
}

_forOf(bar, function (i) {
  foo(i);
});

// for (var i of bar) foo(i);
var i;
_forOf(bar, function (_i) {
  i = _i;
  foo(i);
});
```

Another bonus: it's a minification plus in the common case for-of is used multiple times in a single file.

**Comment by tyscorp** [comment]
Would hoisting for loop out of the ```try``` block into its own function have a noticeable effect by avoiding deoptimization? (at least in V8)

**Comment by impinball** [comment]
Actually, it somehow worsens performance, very noticeably...I'm closing it.

**Comment by sebmck** [comment]
See the [FAQ](http://babeljs.io/docs/faq/#why-is-the-output-of-for-of-so-verbose-and-ugly-). If you're interested in performance then enabling [loose mode](http://babeljs.io/docs/usage/loose/#es6-for-of) for `es6.forOf` is probably your best bet.

**Comment by impinball** [comment]
Ok.
