### ISSUE TITLE
Space between class keyword and the name of the class is removed in compact mode

### ISSUE THREAD

**Issue by Heliodromel** [babel/babel#1579]
Hi,

If i disable the transpilation "es6.blockScoping" (black list) and write a class in ecmascript 6, such as :
"use strict";
class Test {
constructor() {
this.a = 5
}
}

then if i compile this with the compact option to true, i result with something like : classToto{... which is not valid javascript obviously.

Did you already noticed that problem ? Could you have a look ?

Regards,

**Comment by Heliodromel** [comment]
Thanks !

**Comment by sebmck** [comment]
Fixed as of 5.4.4, thanks!
