### ISSUE TITLE
Vulnerable dependencies (indirect security issues) 

### ISSUE THREAD

**Issue by davidz1337** [babel/babel#15800]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

Dear Maintainers,

I hope this message finds you well. I wish to bring to your attention a potential security issue that I've discovered in our recently installed package. Upon conducting a vulnerability scan with Vulert on the lock file, it has come to my attention that there are more than 14 vulnerable dependencies.

Understanding the significant security risk these vulnerabilities could pose to our entire project, I am unsure about the proper procedure for reporting under responsible disclosure. Although some of these dependencies are development-only, they exist within the lock file and might surface in the vendor folder. Hence, it's crucial to consider their management.

For a comprehensive understanding, you can access the report of the scanned package-lock file at the following link: https://vulert.com/vuln-scan/list/5df733a4-c357-41f6-9ec5-f690a9b74486

I urge us to take swift action to rectify these vulnerabilities to safeguard the security of our project. If further information or elaboration is needed, do not hesitate to contact me.

Additionally, the lock file I scanned can be found here: https://github.com/babel/babel/blob/main/yarn.lock

I eagerly await your prompt response.

Best regards.

### Current and expected behavior

I urge us to take swift action to rectify these vulnerabilities to safeguard the security of our project. If further information or elaboration is needed, do not hesitate to contact me.

### Environment

babel/runtime

**Comment by nicolo-ribaudo** [comment]
That lockfile includes dev dependencies -- which of those vulnerabilities are still reported when installing Babel in a project?
