### ISSUE TITLE
[Bug]: decorators 2023-05: initializers are undefined in Custom Element constructors

### ISSUE THREAD

**Issue by trusktr** [babel/babel#15828]
### 💻

- [ ] Would you like to work on a fix?

### Related

- https://github.com/babel/babel/issues/15325

### How are you using Babel?

CLI

### Input code

```js
function element(tagName) {
  return ctor => customElements.define(tagName, ctor)
}

document.body.append(document.createElement('my-el'))

@element('my-el')
class MyEl extends HTMLElement {
  static foo = () => console.log('static foo')

  connectedCallback() {
    this.constructor.foo() // error
  }
}
```

[REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUwDbILbLFAFFAQwHMA5ArASkQG8AoRRAJ2ShEaWjkcQF4A-RBBABnKHAwBRdFhzCAdABNkwGGGT5iZLABpBYxhVoBfWrQVwhMqHIBGcBQE85BAA4vsC3OcvZrEZgRQyFKYvrgA5BgOALRo4RSGtAACaKE4EVGxqPG0EKgEwsKIALIOUigAHkFgCkUAEgAqxQAyIVY09IiigTAQiMBwcLyIuFT8ggjCcOhyqHBEEd2wfQNwOZ0QCGrQyAoAwgSoqDYEEADWox0MDFAAFjDym2CijCCcjHKrlwD03yiMjC4nRMJiAA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.9&externalPlugins=&assumptions=%7B%7D)

### Configuration

```js
export default {
	plugins: [['@babel/plugin-proposal-decorators', {version: '2023-05'}]],
}
```

### Current and expected behavior

I was thinking that the decorated class should be defined (static initializers executed) before the class decorator runs. But this is not what happens.

### Environment

Babel 7.22

**Comment by nicolo-ribaudo** [comment]
@pzuraq What is the expected behavior?

**Comment by trusktr** [comment]
Ah, here's the explanation as to why it was designed this way:

https://github.com/tc39/proposal-decorators/issues/329#issuecomment-695365599
