### ISSUE TITLE
'this' is not allowed before super() for AngularJS $injector.invoke() calls

### ISSUE THREAD

**Issue by martin-brennan-csnet** [babel/babel#1582]
I'm not sure if this is relevant here, but when using classes in AngularJS and using the [`$injector.invoke()`](https://docs.angularjs.org/api/auto/service/$injector#invoke) method, babel refuses to compile the file because `this` is used before the `super()` method is called. `$injector.invoke()`, for those who don't know, can be used to call the constructor of the parent class, simultaneously passing it parameters from the base class and injecting any other required dependencies. For example this code in the subclass:

```
class Activities extends Collection {
  constructor(parentResource, apiRoute) {
    $injector.invoke(super.constructor, this, {
      apiRoute: apiRoute || Activities.Model.apiRoute,
      Model: Activities.Model,
      parentResource
    });
  }
}
```

Calls the following constructor in the parent class, injecting Resourcer along the way, so it doesn't need to be injected into every subclass:

```
constructor(Resourcer, apiRoute, Model, parentResource) {
  this.Model = Model;
  this.apiRoute = apiRoute || Model.apiRoute;
  this.resource = new Resourcer(this.apiRoute, Model.key, Model.friendlyKey, parentResource);
  this.data = [];
}
```

The problem is that babel classifies this as an error because `super()` is not called before `this` is used, even though `super` is called by `$injector.invoke()`. Are there any known workarounds for this or will I need to continue using Traceur, which I assume doesn't have a problem with this because Google wrote it to be more accommodating to Angular?

**Comment by sebmck** [comment]
If this is working in Traceur then you're using an older version of Traceur.

![screen shot 2015-05-20 at 1 10 07 pm](https://cloud.githubusercontent.com/assets/853712/7725339/9642fda2-fef1-11e4-8dec-f62858a6a723.png)

This is spec compliant behaviour and isn't going to change, sorry.

**Comment by martin-brennan-csnet** [comment]
Wow yeah just checked and we are using Traceur `0.0.79`, it's now up to `0.0.89`, our release is 6 months old. Looks like it's actually been fixed as a result of an issue you raised @sebmck on Traceur's repo https://github.com/google/traceur-compiler/issues/1797 , which was fixed on 11 March https://github.com/google/traceur-compiler/commit/d38a9cf30a39aaacc35fb1691389d4132caff321. Looks like we will need another way to do our subclassing. Thanks!
