### ISSUE TITLE
[Bug]: Babel(?) transforms logical conditions incorrectly

### ISSUE THREAD

**Issue by maksim-brylev** [babel/babel#15821]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

```js
       g = J[a | 0];
       if ((g | 0) < (n | 0) | (g | 0) > (m | 0)) {
        break a;
       }
       g = J[a + 1 | 0];
       if ((g | 0) < (o | 0) | (g | 0) > (l | 0)) {
        break a;
       }
```

### Configuration

```js
module.exports = function (api) {
  api.cache(true)

  return {
    compact: false,
    minified: false,

    plugins: [
      [
        "@babel/plugin-transform-typescript",
        {
          allowDeclareFields: true,
          allowNamespaces: true,
          optimizeConstEnums: true,
        },
      ],
    ],

    presets: [
      [
        "@babel/preset-env",
        {
          corejs: { proposals: true, version: "3.31" },
          debug: true,
          modules: "auto",

          shippedProposals: true,
          useBuiltIns: "entry",
        },
      ],
      ["@babel/preset-typescript"],
    ],

    sourceType: "unambiguous",
  }
}

```

### Current and expected behavior

When targeting older browsers like IE11, Babel transforms the following snippet from Emscripten generated "asm.js" code into this:
```js
                          g = J[a | 0];
                          if ((g | 0)(m | 0)) {
                            break a;
                          }
                          g = J[a + 1 | 0];
                          if ((g | 0)(l | 0)) {
                            break a;
                          }
```

I'd expect Babel to not make those conditions to turn into a syntax error.

### Environment

  System:
    OS: Linux 6.4 undefined
  Binaries:
    Node: 20.4.0 - /usr/bin/node
    npm: 9.8.0 - /usr/bin/npm
  npmPackages:
    @babel/core: ^7.22.9 => 7.22.9 
    @babel/plugin-transform-runtime: ^7.22.9 => 7.22.9 
    @babel/preset-env: ^7.22.9 => 7.22.9 
    @babel/preset-typescript: ^7.22.5 => 7.22.5 
    @babel/runtime-corejs3: ^7.22.6 => 7.22.6 
    babel-loader: ^9.1.3 => 9.1.3 
    babel-plugin-minify-dead-code-elimination: ^0.5.2 => 0.5.2 
    babel-preset-minify: ^0.5.2 => 0.5.2 
    webpack: ^5.88.2 => 5.88.2 

### Possible solution

I don't know.

### Additional context

This happens with both Webpack and Rollup. Admittedly, I have no idea whose fault this is, core-js' or Babel's. Please excuse me if I'm barking up at the wrong tree.

**Comment by JLHwung** [comment]
While `(g | 0) < (n | 0) | (g | 0) > (m | 0)` may look like a binary expression, it is actually parsed as a TS type parameter instantiation when you have enabled the typescript plugin:

```ts
(g|0)<(n | 0) | (g | 0)>(m|0/* argument */)
```

so the `<(n | 0) | (g | 0)>` is stripped and you get `(g|0)(m|0)` in the result. This is consistent with TypeScript's behaviour:

[TS Playground](https://www.typescriptlang.org/play?#code/JYMwBAFBDmYD5gAwEowB5IDt5NQmOKYAfJALaHKoDeAUAL5A)

As you have mentioned that you are transforming Emscripten generated "asm.js" code and you have enabled the typescript plugin unconditionally, I suggest you remove the `@babel/plugin-transform-typescript` plugin and let `preset-typescript` handle the extensions (`.ts` vs `.js`):

```js
{
  presets: [
    [ /* preset env stuffs */],
    [
      "@babel/preset-typescript",
      {
        allowDeclareFields: true,
        allowNamespaces: true,
        optimizeConstEnums: true,
      },
    ],
  ];
}

```

**Comment by maksim-brylev** [comment]
Oh wow. That works! Thanks a ton.
