### ISSUE TITLE
[Bug]:`createConfigItem` returns nothing in `@babel/core` v8

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#15839]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

`CreateConfigItem` returns nothging and I get an error:

<img width="393" alt="image" src="https://github.com/babel/babel/assets/1573141/e6540d12-06e8-4b19-aea7-74b2c944bb52">

```js
const {createConfigItem} = require('@babel/core');
```

Here is [example](https://github.com/coderaiser/putout/blob/v30.7.0/packages/babel-plugin-putout/test/index.js#L29)

### Current and expected behavior

Current behavior `createConfigItem` returns nothing in `v8` (but works good in `v7`), anyways `createConfigItemSync` also works good. I think have sense to document this change.

### Environment

Babel v8

**Comment by JLHwung** [comment]
We should throw an error like "Starting from Babel 8.0.0, the 'createConfigItem' function expects a callback. If you need to call it synchronously, please use 'createConfigItemSync'", I will extend https://github.com/babel/babel/pull/12695 to cover `createConfigItem` as well.
