### ISSUE TITLE
[Bug]: typescript decorators not  work properly

### ISSUE THREAD

**Issue by Cola-Zhang** [babel/babel#15855]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js

function actionTest(target: any, propertyKey?: any) {
  console.log('actionTest start');
  Reflect.defineProperty(
    target,
    propertyKey,
    {
      configurable: true,
      enumerable: true,
      set(val: any) {
        console.info('actionTest set');
      }
    }
  );
}

class StoreTest {
  @actionTest
  list = [];

  update(): void {
    this.list = [];
  }
}

console.log('start');

let storeTest = new StoreTest();
storeTest.update();

console.log('finish');




```

### Configuration

```js

const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports =  {

  mode: 'development',
  devtool: 'source-map',
  resolve: {
    extensions: ['.ts', '.js'],
  },

  entry: {
    'bundle': './Main.ts',
  },
  module: {
    rules: [
      {
        test: /\.m?ts$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env', '@babel/preset-typescript'],
              plugins: [
                ["@babel/plugin-proposal-decorators", { "legacy": true }]
              ]
            },
          },
        ],
      }
    ],
  },

  watch: true,
  watchOptions: {
    aggregateTimeout: 500,
    followSymlinks: true,
    poll: 1000,
  },

  plugins: [
    new HtmlWebpackPlugin({
    
    }),
  ]
};

```

### Current and expected behavior

when use @babel/preset-typescript，@babel/plugin-proposal-decorators：decorator and Reflect.defineProperty use at the same time， Reflect.defineProperty setter function not work； 

when use ts-loader： works well；

[Additional context include demo]

expected browser log：
```js
actionTest start
start
actionTest set
actionTest set
finish
```

bug real log ：
```js
actionTest start
start
finish
```

### Environment

System:
    OS: macOS 13.4.1
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  npmPackages:
    @babel/cli: ^7.22.9 => 7.22.9 
    @babel/core: ^7.22.9 => 7.22.9 
    @babel/plugin-proposal-decorators: ^7.22.7 => 7.22.7 
    @babel/plugin-transform-runtime: ^7.21.4 => 7.21.4 
    @babel/preset-env: ^7.21.5 => 7.21.5 
    @babel/preset-typescript: ^7.22.5 => 7.22.5 
    @babel/runtime: ^7.21.5 => 7.21.5 
    babel-loader: ^9.1.2 => 9.1.2 
    webpack: ^5.82.1 => 5.82.1 

### Additional context

this is a demo project, download demo and execute command 'yarn'

when run 'yarn dev:babel' [browser console log]
```js
actionTest start
start
finish
```

when run 'yarn dev:tsloader' [browser console log]
```js
actionTest start
start
actionTest set
actionTest set
finish
```

[babel-bug-test-demo.zip](https://github.com/babel/babel/files/12308435/babel-bug-test-demo.zip)

**Comment by JLHwung** [comment]
Please migrate to the stage 3 decorators proposal as both TS 5.0 and Babel now support it
```
["@babel/plugin-proposal-decorators", { "version": "2023-05" }]
```

This is a historical issue: TS uses `[[Set]]` semantic for class fields so the decorator are invoked. However, the spec now uses `[[Define]]` semantic. If you are using `ts-loader`, please make sure you have enabled the [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) tsc option.
