### ISSUE TITLE
[Bug]: @babel/preset-modules dependency is invalid

### ISSUE THREAD

**Issue by ytreister** [babel/babel#15857]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

There seems to be an issue with the following dependency:
```
"@babel/preset-modules": "0.1.6-no-external-plugins",
```

https://github.com/babel/babel/blob/main/packages/babel-preset-env/package.json#L92
When I try to `npm install` I get the following error message:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/preset-modules@0.1.6-no-external-plugins.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Configuration file name

package.json

### Configuration

```json
{
  "name": "testbabel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "react-scripts": "5.0.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

### Current and expected behavior

I expect it to not error out.

### Environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD   

### Possible solution

Use a valid version of `@babel/preset-modules`

**Comment by JLHwung** [comment]
The `@babel/preset-modules@0.1.6-no-external-plugins` is published on npm: https://www.npmjs.com/package/@babel/preset-modules/v/0.1.6-no-external-plugins. Please check if you are under a corporate npm proxy.

**Comment by ytreister** [comment]
I am behind a corp proxy, and clearining the cache fixed the issue.

Thanks
