### ISSUE TITLE
permissions not preserved (CLI tool)

### ISSUE THREAD

**Issue by devTristan** [babel/babel#1586]
When I do:

```console
babel -w -d dist src
```

I expect dist/bin.js to have the same permissions as src/bin.js (specifically, executable bit)

In actuality, the permissions are not preserved.

**Comment by sebmck** [comment]
Not sure if it should. What if someone doesn't want this behaviour? There has to be some opinionated preset.

**Comment by devTristan** [comment]
That's a really good point. Gulp preserves permissions, I haven't used grunt recently but I'm pretty sure it does. Traceur doesn't.

**Comment by sebmck** [comment]
Closing this as I'd rather not get into super sophisticated stuff with the Babel CLI. You can already use an existing build system, such as Gulp, which as you said, preserves permission. Thanks!

**Comment by olalonde** [comment]
@sebmck would you accept a PR that does this? I think it'd be doable without too much code.

**Comment by sebmck** [comment]
@olalonde I do not think the additional complexity and maintenance is worth it. Use a proper build system.

**Comment by olalonde** [comment]
Which build system would read permission for every file in `./src` and then chmod every corresponding `./lib` file?
