### ISSUE TITLE
Support decorators and importAttributes in TypeScript

### ISSUE THREAD

**Issue by sxzz** [babel/babel#15866]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

TypeScript now has default support for both `decorators` and `importAssertions`. However, some third-party libraries may only include the `typescript` plugin, which results in neither syntax being supported.

### Describe the solution you'd like

Add `decorators` and `importAssertions` plugins when `typescript` plugin is enabled in `@babel/parser`.

### Describe alternatives you've considered

N/A

**Comment by nicolo-ribaudo** [comment]
We did this (inconsistently) in the past, by enabling parsing for class properties and object spread in the TS plugin, but then we never did it for all the other JS features implemented by TypeScript.

TypeScript is JS+types(+a few runtime features), and the TS plugin should only enable the types(+a few runtime features) part. Everything else is just plain JavaScript or JavaScript proposals, which should be enabled by the corresponding plugin.

> However, some third-party libraries may only include the typescript plugin, which results in neither syntax being supported.

This is true for any stage 3 proposal, not just these two and not just when using TS.
