### ISSUE TITLE
[Bug]: Optional chaining expressions resolving as `true` instead of undefined

### ISSUE THREAD

**Issue by EJLearner** [babel/babel#15887]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code
https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEDMEsCcGcBdQBtIDsCmoAWBDWoADACgH1p1xQBeUVAVySQEpqqb7GDQ9QAHHaIgD2leFkzoAHr3KxYkIalAB3LJADGWUOgBuOJHXjp88IYXjQ66LumjRF6IXVhIAnt1QATULIbx8aKBimKpCSBLSsvKKoABG6GgA5uaW1gBQHEgA_AB0RghpaSBBavgoGKCw6OgAtiZmsmE6mOpCdujq8G5pdF4UaOieufnwQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.11&externalPlugins=&assumptions=%7B%7D

### Configuration file name

reproduced in babel try it out - see for configuration

### Configuration

reproduced in babel try it out - see for configuration

### Current and expected behavior

In my application expressions like `null?.a` are evaluating as true. This behavior started today with version 7.22.11

### Environment

Babel version 7.22.11

### Possible solution

Changes like these in a recent change might be the issue? It looks like if a value is undefined, babel gives an expression that evalutes to true.

![image](https://github.com/babel/babel/assets/22520333/d859d3ff-adfe-4dad-b777-fabb3861db33)

https://github.com/babel/babel/pull/15871/commits/170c83478fbb3115aca98bef532bd8e8cc3bf7ae

**Comment by nicolo-ribaudo** [comment]
This is an optimization we introduced, that maybe is triggered too often 🤔 

Could you provide a code example that, when evaluated, has different behavior? Btw, this optimization does not apply in the last line of a script. You need to add another line in the repl after the one using optional chaining.

**Comment by EJLearner** [comment]
> This is an optimization we introduced, that maybe is triggered too often 🤔
> 
> Could you provide a code example that, when evaluated, has different behavior? Btw, this optimization does not apply in the last line of a script. You need to add another line in the repl after the one using optional chaining.

thanks, I updated the repl to have multiple lines and it now shows better how the top will evaluate to `true`

**Comment by JLHwung** [comment]
> > This is an optimization we introduced, that maybe is triggered too often 🤔
> > Could you provide a code example that, when evaluated, has different behavior? Btw, this optimization does not apply in the last line of a script. You need to add another line in the repl after the one using optional chaining.
> 
> thanks, I updated the repl to have multiple lines and it now shows better how the top will evaluate to `true`

In the REPL example provided above
```js
null?.test
undefined?.test
```
The evaluation result of `null?.test` is not used anyway, so Babel outputs code that is shorter. If you assign the value to a variable, Babel will fallback to the compliant transform so that it will evaluate to `undefined`.

```js
var a = null?.test
// transformed to
var a = (_ref = null) === null || _ref === void 0 ? void 0 : _ref.test;
```

Do you have an example that such optimization actually breaks your application?

**Comment by EJLearner** [comment]
> > > This is an optimization we introduced, that maybe is triggered too often 🤔
> > > Could you provide a code example that, when evaluated, has different behavior? Btw, this optimization does not apply in the last line of a script. You need to add another line in the repl after the one using optional chaining.
> > 
> > 
> > thanks, I updated the repl to have multiple lines and it now shows better how the top will evaluate to `true`
> 
> In the REPL example provided above
> 
> ```js
> null?.test
> undefined?.test
> ```
> 
> The evaluation result of `null?.test` is not used anyway, so Babel outputs code that is shorter. If you assign the value to a variable, Babel will fallback to the compliant transform so that it will evaluate to `undefined`.
> 
> ```js
> var a = null?.test
> // transformed to
> var a = (_ref = null) === null || _ref === void 0 ? void 0 : _ref.test;
> ```
> 
> Do you have an example that such optimization actually breaks your application?

Yes, sorry. I'm just realizing that the code that my attempted reproduction is exactly how this is supposed to work. I'm still looking into it and starting to suspect that this may be an issue with our testing setup. This can probably be dropped for now. If I need to, I can open a new one with hopefully more details.

**Comment by EJLearner** [comment]
To give a little more information. It seems to be only an issue when running jest tests with coverage. Right now we suspect that jest or another tool is somehow changing the code in a way that babel detects that the expression is not being assigned to anything and then the recent optimization kicks in when we don't want it to.

We're still trying to figure out if it's a babel issue, a jest issue, or an issue with our configuration.

**Comment by nicolo-ribaudo** [comment]
Jest probably transforms your files with https://github.com/istanbuljs/babel-plugin-istanbul for coverage, so a reproduction would probably need to use that plugin.

**Comment by nicolo-ribaudo** [comment]
This is a babel bug :)

https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEDMEsCcGcBdQBtIDsCmoAWBDWoADACgH1p1xQBeUVAVySQEpqqb7GDQ9QAHHaIgD2leFkzoAHr3KxYkIalAB3LJADGWUOgBuOJHXjp88IYXjQ66LumjRF6IXVhIAnt1QATULIbx8aKBimKpCSBLSsvKKoABG6GgA5uaW1gBQetDc1KBEAAwANLQMSAD8AHRGCEwA3GlpIEFq-CgYoLDo6AC2JmayYTqY6kJ26Orwbml0XhRo6J4VVfBAA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.11&externalPlugins=&assumptions=%7B%7D
