### ISSUE TITLE
TypeScript 5.2 features

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#15894]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

We need to make sure we support all the TS 5.2 features: https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/

The missing ones are:
- [ ] Decorators metadata (https://github.com/babel/babel/issues/15889) - I'm working on this
- [ ] Named and Anonymous Tuple Elements: `[first: T, T]` is now a valid type - `good first issue` :) (https://github.com/babel/babel/pull/15896)

Everything else seems to be supported

### Describe the solution you'd like

/

### Describe alternatives you've considered

/

**Comment by nicolo-ribaudo** [comment]
### Named and Anonymous Tuple Elements: `[first: T, T]` is now a valid type

For this change, we just need to delete the error about mixing tuple elements with and without labels from our parser. Tuples parsing is implemented at https://github.com/babel/babel/blob/e43d8e77cf88245e930055e70a42f46e2996bce6/packages/babel-parser/src/plugins/typescript/index.ts#L1041.

Then, there will probably be some tests that can be deleted because they were testing that error.

---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.ts`; `output.json` will be automatically generated)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by yukukotani** [comment]
I'm going to work on Named and Anonymous Tuple Elements

**Comment by sahilbaishya** [comment]
Heyy, can I work on this issue??

**Comment by ShiviTripathi13** [comment]
Is this issue still open, if yes, please assign it to me.

**Comment by liuxingbaoyu** [comment]
@ShiviTripathi13 Thank you! Now they have been completed. :)

**Comment by ShiviTripathi13** [comment]
Okay, if any issue opens in future please let me know,
