### ISSUE TITLE
[Bug]: Var declarations are not recognized correctly in sloppy mode when using equal sign (=) consecutively 

### ISSUE THREAD

**Issue by echo094** [babel/babel#15900]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from '@babel/parser'
import _traverse from '@babel/traverse'
const traverse = _traverse.default

let ast = parse('var a = b = 1;console.log(b);', { strictMode: false })
traverse(ast, {
  Identifier(path) {
    let name = path.node.name
    if (name !== 'b') {
      return
    }
    let binding = path.scope.getBinding(name)
    console.log(binding)
  }
})

```

### Configuration file name

package.json

### Current and expected behavior

In sloppy mode, the code below will define var `b`, and its a useful trick when assigning same value: [Assign Multiple Variables to the Same Value in JavaScript](https://livingwithcode.com/assign-multiple-variables-to-the-same-value-in-javascript/#google_vignette)

```js
var a = b = 1;
```

However, babel (the latest version) cannot parse the code correctly and does not generate a binding for var `b` in the scope. 

### Environment

```text  
  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 16.20.2 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/opt/node@16/bin/npm
  npmPackages:
    @babel/generator: ^7.22.10 => 7.22.10 
    @babel/parser: ^7.22.11 => 7.22.11 
    @babel/traverse: ^7.22.11 => 7.22.11 
    @babel/types: ^7.22.11 => 7.22.11 
    eslint: ^8.23.0 => 8.23.1 
```

### Possible solution

1. Check if the left of the assignmentExpression is an unknown Identifier.
2. Change the type of the node to variableDeclarator and make it the init of the left variableDeclarator.

**Comment by nicolo-ribaudo** [comment]
That code does not define `b` in the current scope, but as a global variable. `var a = b = 1` is exactly the same as `b = 1; var = 1;`, or as `var a = globalThis.b = 1`.
