### ISSUE TITLE
[Bug]: @babel/preset-env@7.22.14 has deprecated npm module "@babel/plugin-proposal-private-property-in-object"

### ISSUE THREAD

**Issue by stein2nd** [babel/babel#15919]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

nothing.
Delete "package-lock.json" and directory "node_modules" in the project folder. Then, execute "ncu", "ncu -u", and "npm install" in Terminal.app.

### Current and expected behavior

I ran "ncu, ncu -u, npm install" and got the following deprecated warning.

@babel/plugin-proposal-private-property-in-object@7.21.0-placeholder-for-preset-env.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.

## System:
 - OS: macOS 13.5.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 1.77 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.1 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
 - npm: 10.0.0 - ~/.nodebrew/current/bin/npm
 - pnpm: 8.6.12 - ~/.nodebrew/current/bin/pnpm

**Comment by nicolo-ribaudo** [comment]
We accidentally deprecated the wrong version of that package we'll fix it shortly.
