### ISSUE TITLE
[Bug]: @babel/core version 7.22.11 breaks the build

### ISSUE THREAD

**Issue by arthirm** [babel/babel#15916]
### How are you using Babel?

@rollup/plugin-babel

### Input code

I have a simple repro in this repo https://github.com/arthirm/babel-core-issue1. Downloading and doing `yarn install` and `yarn build` should break the build with the following error

```
[!] (plugin babel) SyntaxError: /Users/aravisha/babel-core-issue1/packages/test-plugin/index.ts: Unexpected token, expected "{" (11:7)

   9 |   }
  10 |
> 11 |   run(): void {
     |        ^
  12 |     console.log("Running test plugin");
  13 |   }
  14 | }
packages/test-plugin/index.ts (11:7)
    at constructor (/Users/aravisha/babel-core-issue1/node_modules/@babel/parser/lib/index.js:345:19)
    at Parser.raise (/Users/aravisha/babel-core-issue1/node_modules/@babel/parser/lib/index.js:3199:19)
```

### Current and expected behavior

The build should work fine without breaking.

### Additional context

Note:  Without any other changes if we downgrade the @babel/core changes to 1 patch below (7.22.10) the build works fine.

I also get the below error sometimes especially the first time and the next time I get `Unexpected token, expected "{"` 

```
[!] (plugin babel) SyntaxError: /Users/aravisha/babel-core-issue1/packages/core/index.ts: Support for the experimental syntax 'flow' isn't currently enabled (1:8):
> 1 | export type { BaseConfig } from './config.js';
    |        ^
Add @babel/preset-flow (https://github.com/babel/babel/tree/main/packages/babel-preset-flow) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-flow) to the 'plugins' section to enable parsing.
packages/core/index.ts (1:7)`
```

Also there is also some caching issues. Sometimes I need to delete the node_modules and should do `yarn cache clean` to revert to my original state. Just changing the code is not reflecting the change.

**Comment by nicolo-ribaudo** [comment]
Babel itself doesn't do any caching, so that's probably caused by roll-up. It looks like, for some reason, your Babel config is not being applied 🤔

**Comment by jraoult** [comment]
Oh, so I'm not the only one. I've been trying to investigate this issue for a few days. I have the same issue but with webpack as a bundler. Happy to provide a reproduction repo if necessary.

**Comment by jakebixby** [comment]
This might have something to do with it as well.
![Screen Shot 2023-09-03 at 1 00 15 PM](https://github.com/babel/babel/assets/102083128/7935d82d-e39d-42d2-9d63-064cc95faf36)

**Comment by nicolo-ribaudo** [comment]
7.22.7 had a publishing error -- most versions of `@babel/parser` do not include all those files.

**Comment by jakebixby** [comment]
> Moreover, those files are not part of the public API and as such their removal is not subject to semver (which only applies to public APIs).
I figured as much. I only discovered this because a package I was attempting to use depends on 7.22.7
https://github.com/patricklx/ember-template-tag/blob/main/lib/template-parser.ts
