### ISSUE TITLE
[Bug]: ClassDeclaration["id"] should be nullable

### ISSUE THREAD

**Issue by jordanbtucker** [babel/babel#15918]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
import parser from "@babel/parser";
const file = await parser.parse("export default class {}", {sourceType: "module"});
const exportDecl = file.program.body[0] as ExportDefaultDeclaration;
const classDecl = exportDecl.declaration as ClassDeclaration;
console.log(classDecl.id.name); // TypeError: Cannot read properties of null (reading 'name')
// TypeScript does not catch this error since the type of `id` is `Identifier` not `Identifier | null`.
```

### Current and expected behavior

When a class is a default export, it is not required to have an identifier, so `parse` correctly outputs a `ClassDeclaration` with its `id` property set to `null` when the identifier is omitted. However, the `ClassDeclaration` type from `@babel/types` does not have an optional `id` property. This results in situations where TypeScript users will be confident that the `id` of a `ClassDeclaration` is non-null when it might not be.

The `ClassDeclaration` interface's `id` property's type should optional and its type annotation should be `Identifier | null`.

See https://tc39.es/ecma262/2023/multipage/ecmascript-language-functions-and-classes.html#prod-ClassDeclaration

### Environment

- @babel/parser@7.22.14
- @babel/types@7.22.11

### Possible solution

The `ClassDeclaration` interface's `id` property's type should optional and its type annotation should be `Identifier | null`.

**Comment by JLHwung** [comment]
We should update the node definitions here: `./packages/babel-types/src/definitions/core.ts`. PR is welcome.
