### ISSUE TITLE
FAQ/docs: recommended way to blacklist/whitelist transformers for babel-node

### ISSUE THREAD

**Issue by naartjie** [babel/babel#1592]
I'm using babel-node to run my code on iojs (1.8.2 and 2.0.2). I am looking for a recommended way to blacklist the transformers which are fully supported in iojs.

#631 (and #462 #272 #686) try to tackle a much harder problem (in my opinion), to do this automagically, which would be cool, but in the case of node/iojs I think it is fine to do this manually, since the deploy runtime is known.

Maybe I missed this in the docs somewhere, but it would be cool if newcomers could find out about running `babel-node` with only the minimum subset of transformers needed for their node version.

I actually think that `babel-node` should get a mention on https://babeljs.io/docs/using-babel/, but it would require a bit of a refactor of the page, as it already has a Node section. I know `babe-node` is also on https://babeljs.io/docs/usage/cli/, but not as a first class citizen.

Happy for a PR for this? 1) which section should it be under? and 2) is the recommended way to create `.babelrc` in the root of the project?

PS. thanks for a frikken awesome project, which makes programming more fun.

**Comment by naartjie** [comment]
For some, a whitelist might be a more minimal subset. Just toying with the idea I came up with this `.babelrc` for my one project:

```json
{
  "whitelist": [
    "strict",
    "es6.arrowFunctions",
    "es6.modules",
    "es6.parameters.rest",
    "es6.parameters.default",
    "es6.destructuring",
    "es6.spread"
  ]
}
```

**Comment by loganfsmyth** [comment]
@naartjie PRs and requests related to documentation should be submitted to the issue queue at https://github.com/babel/babel.github.io/issues This queue is used exclusively for bug reports and feature requests for Babel itself. Feel free to open up an issue over there.

The whitelist approach seems reasonable to me.

**Comment by naartjie** [comment]
Ah, right, sorry and thanks for the info @loganfsmyth

**Comment by naartjie** [comment]
Moved to https://github.com/babel/babel.github.io/issues/299
