### ISSUE TITLE
[Bug]: Double export with TypeScript ExportAssignment and type only imports

### ISSUE THREAD

**Issue by modderme123** [babel/babel#15933]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import type {a} from "b";
const bla = {
  a: 1
};
export = bla;
```
(https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBDAnmApnA3gQwL5wGZQQhwBEARiQNwBQAxhAHYDO8ZANpnALwbVxyYAXHACM1bDRQAPSLG5x2mGkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.22.15&externalPlugins=babel-plugin-replace-ts-export-assignment%400.0.2&assumptions=%7B%7D)

### Current and expected behavior

Babel currently transforms this file into:
```js
const bla = {
  a: 1
};
module.exports = bla;
export {};
```
which has two exports. Instead, I would expect a commonjs output like this (when compiled with sourceType unambiguous):
```js
const bla = {
  a: 1
};
module.exports = bla;
```

(see typescript compiler output for comparison: https://www.typescriptlang.org/play?module=0#code/JYWwDg9gTgLgBDAnmApnA3gQwL5wGZQQhwBEARiQNwBQAxhAHYDO8ZANpnALwbVxyYAXHACM1bDRQAPSLG5x2mGkA)

### Environment

```
 System:
    OS: macOS 12.6.8
  Binaries:
    Node: 20.5.1 - /usr/local/bin/node
    npm: 10.0.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core
    @babel/preset-env
    @babel/plugin-transform-typescript
    babel-plugin-replace-ts-export-assignment
```

### Possible solution

It seems like `sourceType: unambiguous` is detecting `import type` as a module along with `export = `. Maybe this detection of `export =` could be removed?

**Comment by liuxingbaoyu** [comment]
https://github.com/G-Rath/babel-plugin-replace-ts-export-assignment
This plugin is third party.

Below are the ones we support.
```
/repl.ts: `export = <value>;` is only supported when compiling modules to CommonJS.
Please consider using `export default <value>;`, or add @babel/plugin-transform-modules-commonjs to your Babel config.
  3 |   a: 1
  4 | };
> 5 | export = bla;
    | ^^^^^^^^^^^^^
  6 |
```
https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBDAnmApnA3gQwL5wGZQQhwBEARiQNwBQAxhAHYDO8ZANpnALwbVxyYAXHACM1bDRQAPSLG5x2mGkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.22.15&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.21.2&assumptions=%7B%7D

**Comment by modderme123** [comment]
Hmm, the behavior that was unexpected is that even though it seems [typescript expects](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) `export =` to be transformed into `module.exports =` (and that is all the plugin [does](https://github.com/G-Rath/babel-plugin-replace-ts-export-assignment/blob/master/src/index.ts)), Babel's sourceType still detects the file type as a module (which is different than if the file had just had module.exports to begin with). My expectation would be that unambiguous wouldn't detect `export =` as a module. 

If that expectation is wrong though I'm happy to close this issue

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/pull/15497#issue-1625143448

This is intentional.
For babel, compiling .cts into .cjs is not just a simple replacement of keywords.
So we treat it as a module and run full esm to cjs processing.

**Comment by modderme123** [comment]
Thank you for the explanation!
