### ISSUE TITLE
suggestion: support JSON5 syntax for .babelrc

### ISSUE THREAD

**Issue by naartjie** [babel/babel#1593]
What do you think of supporting the less restrictive JSON5 syntax for `.babelrc`?

I think it would be quite handy, to allow comments, trailing commas and all that jazz. JSON isn't very human friendly. It isn't a standard, but JSON would still work fine, so I don't see a problem there.

**Comment by sebmck** [comment]
Seems inconsistent with all the other `.rc` files out there.

**Comment by deepsweet** [comment]
so maybe YAML? `.eslintrc` supports YAML with the same filename.

**Comment by naartjie** [comment]
> so maybe YAML?

@deepsweet actually YAML would be even better :+1: thanks for that

> Seems inconsistent with all the other `.rc` files out there.

@sebmck I've seen a couple of projects using it, but granted not for `.rc` rather `.json` files. [pm2](https://github.com/Unitech/PM2) is one example.

The thing is standard JSON would still be supported, so I see this as a win win. (+YAML would be a win win win) ;-)

**Comment by loganfsmyth** [comment]
@sebmck I'm not sure how wide-spread this is, but I'll just throw out that I know .jshintrc and [.jscsrc](https://github.com/jscs-dev/node-jscs/blob/2740ac6c8743483270e4ceb346fef47f0356cd24/lib/cli-config.js#L70) supports comments in JSON.

Perhaps if not JSON5, then we could adopt something simple like that? Looks like JSCS also supports `.jscs.json` and `.jscs.js`, loaded via `require` call if you wanted to strictly parse JSON or load a module to programmatically export a config. Maybe we could do that and say that if you have a `.babel.js` file then you can put comments in there and assign your JSON to `module.exports`?

**Comment by sebmck** [comment]
@loganfsmyth Comments are allowed in `.babelrc` following #1191.

**Comment by naartjie** [comment]
Actually on 2nd thought, I'm not sure if YAML is even better, but it's definitely a great option. I just think that it's us humans reading and writing these files by hand, so would be great to have slightly more lax syntax rules for them, while not losing support for the strict JSON syntax.

**Comment by naartjie** [comment]
@sebmck ah, comments are cool, and actually that already helps a whole bunch. Thanks!!! :+1: 

I'm closing this, don't want to make noise about such trivial things. I'm sure you guys have better things to do ;-)
