### ISSUE TITLE
[Bug]: @babel/parser: __esModule property is not defined in lib/index.js since version 7.22.11

### ISSUE THREAD

**Issue by tkallage** [babel/babel#15934]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

working in 7.22.10:
`npm i @babel/parser@7.22.10 local-pkg@0.4.3`
run in `node` REPL:
```js
require('local-pkg').importModule('@babel/parser').then(({parse}) => console.log(parse))
```
Result: `[Function: parse]`

not working in 7.22.11:
`npm i @babel/parser@7.22.11 local-pkg@0.4.3`
run in `node` REPL:
```js
require('local-pkg').importModule('@babel/parser').then(({parse}) => console.log(parse))
```
Result: `undefined`

And
```js
require('local-pkg').importModule('@babel/parser').then(({default: {parse}}) => console.log(parse))
```
Result: `[Function: parse]`

### Current and expected behavior

unplugin-vue-components uses [`importModule()` from the package local-pkg](https://github.com/antfu/local-pkg/blob/e707712fa952eef4fbf5be9c252ce4db88c4ffc1/index.cjs#L15C6-L15C6) to import @babel/parser.
It recognizes the property __esModule to import the default export of @babel/parser.

With @babel/parser 7.22.10 this works fine, but since 7.22.11 the esModule-marker is missing in the resulting lib/index.js file, resulting in the imported object `{ default: { parser(), ... } }` instead of `{ parser(), ... }`.

### Environment

  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - <project_path>\node_modules\.bin\npm.CMD
    pnpm: 8.5.0 - C:\Program Files\nodejs\pnpm.CMD
  npmPackages:
    @babel/parser: ^7.22.11 => 7.22.11
    @babel/runtime: ^7.22.11 => 7.22.11
    eslint: ^8.48.0 => 8.48.0

### Possible solution

Add 
```
Object.defineProperty(exports, '__esModule', {
  value: true
});
```
at the top of the resulting file `/lib/index.js` in @babel/parser

### Additional context

![grafik](https://github.com/babel/babel/assets/8417407/297eabf4-a683-4338-8c14-6c5717fd963e)
![grafik](https://github.com/babel/babel/assets/8417407/0805b29a-372d-42e8-ac57-2c8cb130de4c)

**Comment by nicolo-ribaudo** [comment]
I'm incredibly confused by how this could have happened

**Comment by liuxingbaoyu** [comment]
@nicolo-ribaudo https://github.com/babel/babel/pull/15038 I guess it is.

**Comment by nicolo-ribaudo** [comment]
As a quick fix, we could just concatenate `Object.defineProperty(exports, "__esModule", { value: true })` to the file generated by rollup.

**Comment by liuxingbaoyu** [comment]
I found a workaround and will open a PR later. :)

**Comment by tkallage** [comment]
Thanks for the fast fix! ♥️
