### ISSUE TITLE
[Bug]: @b

### ISSUE THREAD

**Issue by char0n** [babel/babel#15944]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var sym = Symbol();

var promise = Promise.resolve();

var check = arr.includes("yeah!");

console.log(arr[Symbol.iterator]());
```

### Configuration file name

babel.config.js

### Configuration

```js
{ 
  plugins: [
    [
      '@babel/plugin-transform-runtime',
        {
          corejs: { version: 3, proposals: false },
          version: '^7.22.15',
        },
    ]
 ]
}
```

### Current and expected behavior

**Input code:**

```js
var sym = Symbol();

var promise = Promise.resolve();

var check = arr.includes("yeah!");

console.log(arr[Symbol.iterator]());
```

**Expected output code**
```js
import _getIterator from "@babel/runtime-corejs3/core-js/get-iterator";
import _includesInstanceProperty from "@babel/runtime-corejs3/core-js-stable/instance/includes";
import _Promise from "@babel/runtime-corejs3/core-js-stable/promise";
import _Symbol from "@babel/runtime-corejs3/core-js-stable/symbol";

var sym = _Symbol();

var promise = _Promise.resolve();

var check = _includesInstanceProperty(arr).call(arr, "yeah!");

console.log(_getIterator(arr));
```

**Actual output code:**

```js
var sym = Symbol();

var promise = Promise.resolve();

var check = arr.includes('yeah!');

console.log(arr[Symbol.iterator]());
```

This is actually taken from https://github.com/babel/website/blob/main/docs/plugin-transform-runtime.md#core-js-aliasing.It is not possible to get to this result 

### Environment

"@babel/cli": "=7.22.15",
"@babel/core": "=7.22.15",
"@babel/plugin-transform-runtime": "=7.22.15",
"@babel/runtime-corejs3": "=7.22.15",

**Comment by char0n** [comment]
Overall it just seems that plugin doesn't handle any polyfilling, it just handles `helpers` processing as described in https://github.com/babel/website/blob/main/docs/plugin-transform-runtime.md#helpers and properly create imports from corejs3.

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/options#targets

Can you try specifying a `targets`?

**Comment by char0n** [comment]
Yep, that seems to do the trick. Thanks a lot!
