### ISSUE TITLE
[Bug]: `@babel/preset-typescript@7.22.15` fails when exporting namespace

### ISSUE THREAD

**Issue by snitin315** [babel/babel#15940]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

Building the following code with `@babel/preset-typescript` fails:

```js
import type { Brand, NativeOrWebBrand } from './types';

namespace Platform {
  export type Name = 'web';
}

export { Platform };
```

with the following error:

<img width="868" alt="Screenshot 2023-09-07 at 8 36 52 AM" src="https://github.com/babel/babel/assets/46647141/1894730e-4f23-4059-bd52-49e9a0efd825">

However if I move the export to declaration itself, it builds successful:

```ts
import type { Brand, NativeOrWebBrand } from './types';

export namespace Platform {
  export type Name = 'web';
}
``` 

### Configuration file name

.babelrc.js

### Configuration

```js
{
      presets: [
        ['@babel/preset-env', { modules: false }],
        '@babel/preset-typescript',
        ['@babel/preset-react', { runtime: 'automatic' }],
      ],
      plugins: [
        [
          '@babel/plugin-transform-runtime',
          {
            helpers: true,
            regenerator: true,
          },
        ],
        [
          'babel-plugin-styled-components',
          {
            displayName: true,
            pure: true,
            ssr: true,
          },
        ],
      ],
    },
```

### Current and expected behavior

Currently it throws error with v7.22

It should not throw error like in v7.16

### Environment

```
System:
    OS: macOS 13.4.1
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  npmPackages:
    @babel/core: 7.22.15 => 7.22.15 
    @babel/plugin-transform-react-jsx: 7.22.15 => 7.22.15 
    @babel/plugin-transform-runtime: 7.22.15 => 7.22.15 
    @babel/preset-env: 7.22.15 => 7.22.15 
    @babel/preset-react: 7.22.15 => 7.22.15 
    @babel/preset-typescript: 7.22.15 => 7.22.15 
    @babel/runtime: 7.22.15 => 7.22.15 
    babel-jest: 29.6.1 => 29.6.1 
    babel-loader: 8.2.3 => 8.2.3 
    babel-plugin-module-resolver: 4.1.0 => 4.1.0 
    babel-plugin-styled-components: 1.12.0 => 1.12.0 
    jest: 29.6.1 => 29.6.1 
    metro-react-native-babel-preset: 0.76.7 => 0.76.7 
    react-native: 0.72.3 => 0.72.3
   ```

**Comment by nicolo-ribaudo** [comment]
This has been probably caused by https://github.com/babel/babel/pull/15799, but the old output was wrong too.

We might have to add a "is namespace && will be stripped because it only contains types" check in https://github.com/babel/babel/blob/85a35adf1292a2035c23478da82f827968e64c28/packages/babel-plugin-transform-typescript/src/index.ts#L389, or call `registerGlobalType` in https://github.com/babel/babel/blob/85a35adf1292a2035c23478da82f827968e64c28/packages/babel-plugin-transform-typescript/src/namespace.ts#L27.

I see that you marked "Would you like to work on a fix?", let me know if you need further help :)

**Comment by snitin315** [comment]
>We might have to add a "is namespace && will be stripped because it only contains types" check in

@nicolo-ribaudo How do I check it's a namespace, currently `stmt` doesn't have access to the [`kind` property](https://astexplorer.net/#/gist/b8f4a001006f0e98b099c752600c9d22/c008c1cd3397d6aa0e786bc59fb27e5d2caeac22)

**Comment by nicolo-ribaudo** [comment]
You can use `stmt.isTSModuleDeclaration()` for that

**Comment by snitin315** [comment]
@nicolo-ribaudo not as of now. Feel free to  pick this up.

**Comment by nicolo-ribaudo** [comment]
If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-typescript/test/fixtures/namespace (only `input.ts`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest transform-typescript` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest transform-typescript` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by niftytyro** [comment]
hey there can I pick this up?

**Comment by nicolo-ribaudo** [comment]
Sure! Feel free to write here if you need more help :)

**Comment by CheadleCheadle** [comment]
I could try taking a stab at it if niftytyro isn't working on it anymore!

**Comment by niftytyro** [comment]
Yes sure please! I'm not working on it right now. Feel free to take it

**Comment by sabasyedcodes** [comment]
Hello there ! I am new to open source 😅. Can I work on this issue ?
