### ISSUE TITLE
Returning promise from async returns it's result

### ISSUE THREAD

**Issue by klimashkin** [babel/babel#1595]
Hello!
I'm trying to return promise object from ```async``` function, but instead of it, promise result returns.
Is it by spec?

```
var finalResult =  await getPromise(() => Bluebird.resolve(55)).tap(() => { some code })
async function getPromise (promiseCreator) {
    var promise = promiseCreator();
    await promise;
    return promise;
}
```
```tap``` in not a function, because ```await getPromise(() => Bluebird.resolve(55))``` returns 55, not promise object

**Comment by sebmck** [comment]
Expected behaviour. See the [spec](https://github.com/tc39/ecmascript-asyncawait) and [this](https://github.com/tc39/ecmascript-asyncawait/issues/41) issue.
