### ISSUE TITLE
[Bug]: Pulling of 7.22.18 is causing issues where other packages have already pinned it

### ISSUE THREAD

**Issue by GrahamCampbell** [babel/babel#15967]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

N/A

### Current and expected behavior

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.22.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Environment

node 18, npm 7

**Comment by dargmuesli** [comment]
See https://github.com/babel/babel/issues/15966

**Comment by Hao-yiwen** [comment]
I also have this qustion.

-------------
Run npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.22.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-09-1[4](https://github.com/Hao-yiwen/yiwen-blog-website/actions/runs/6187996183/job/16799508455#step:5:5)T1[6](https://github.com/Hao-yiwen/yiwen-blog-website/actions/runs/6187996183/job/16799508455#step:5:7)_13_32_2[8](https://github.com/Hao-yiwen/yiwen-blog-website/actions/runs/6187996183/job/16799508455#step:5:9)2Z-debug-0.log
Error: Process completed with exit code 1.

**Comment by dargmuesli** [comment]
Please give a :+1: to the original post or to the issue I linked instead of adding "me too" comments, thanks!

**Comment by Hao-yiwen** [comment]
ok

**Comment by nicolo-ribaudo** [comment]
Working on this, it will be fixed in ~10 minutes.

**Comment by Neeham** [comment]
Thank you! It's back working!

**Comment by Neeham** [comment]
Thank you for the quick update! 😄

**Comment by Anderson-SG** [comment]
Same here, @nicolo-ribaudo Thank you for the quick update!

**Comment by pedrohaccorsi** [comment]
same, thanks!

**Comment by ADumaine** [comment]
Working now.  Thanks!

**Comment by nicobytes** [comment]
Thanks!

**Comment by Neeham** [comment]
It's back working! Thank you once again! 💯

**Comment by Oteiza-a** [comment]
Now it's working, thanks!

**Comment by nicolo-ribaudo** [comment]
Awesome :) Sorry for the publishing problem in 7.22.18!

(and while many people are here: if your company is using Babel, remember that we are entirely funded by [donations on OpenCollective](https://opencollective.com/babel) -- feel free to reach out to me if your company is interested in sponsoring but you don't know how to do it 🙏)

**Comment by niklasfrick** [comment]
Works now. Packages are installing. Thanks :)
