### ISSUE TITLE
Export type BaseNode from @babel/types

### ISSUE THREAD

**Issue by LeoDog896** [babel/babel#15963]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I have a generic function that takes in any type of node, but I can't get the actual `BaseNode` class from any of the exported members

### Describe the solution you'd like

Export `BaseNode` for external use

### Describe alternatives you've considered

- Recreating the interface
- Patching the library

**Comment by nicolo-ribaudo** [comment]
Can you use `Node`?
