### ISSUE TITLE
Publish process broken

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#15966]
See https://github.com/babel/babel/actions/runs/6184255599/job/16787559069

Opening an issue because I do not have time to fix it now, I'll release locally.

**Comment by JLHwung** [comment]
We can ignore linting the `skip-bundled` tests on publish because those tests are skipped when bundled anyway.

**Comment by JLHwung** [comment]
And we may need force publishing these three packages if there aren't any source changes. 
- @babel/core
- @babel/types
- @babel/traverse

**Comment by dep** [comment]
Thanks for reporting. I'm having the same issue.  Let me know if there are any required steps (updating any dependencies) once this is resolved. Thanks!

**Comment by nicolo-ribaudo** [comment]
I temporarily disabled linting to quickly re-publish from CI as 7.22.19.

I first tried to publish locally, but:
- I got one OTP prompt per package from npm, and they were not ordered so I had to try multiple times to give the correct tokens
- At some point I got this error:
  ```
  Error while publishing [object Object]:
  RequestError: 001E4AF801000000:error:0A0003FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 20
  ```

and something has not been published properly.

**Comment by Anderson-SG** [comment]
Fixed here, THANKS!

**Comment by segovia-no** [comment]
Facing the same issues when using the @babel/core dependency

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.22.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! notarget It was specified as a dependency of '@babel/core'
```

**Comment by bilalfaisal-ct** [comment]
Facing same issue

```npm ERR! notarget No matching version found for @babel/types@^7.22.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.```

**Comment by EthanTuning** [comment]
Is this issue somehow related to an error I am getting when trying to `npm install @babel/types` ? 
I was startin up a new Ionic project this morning and got this error: `No matching version found for @babel/types@^7.22.19`
However, just tried again few mins later and all was good!
So, thanks for the speedy fix!

**Comment by nicolo-ribaudo** [comment]
`@babel/types@7.22.19` has been published, and `@babel/types@^7.22.18` will resolve to that version. It has been published on npm ~15 minutes ago (https://www.npmjs.com/package/@babel/types/v/7.22.19) -- if there is a proxy between you and npm it might need a little more time to sync the new version.

I'm hiding now all the comments related to the missing `@babel/types@7.22.18` since that has been fixed (and is tracked at https://github.com/babel/babel/issues/15967). This issue is to track the _root cause_ of that problem :)

Thanks @theredpea for cross-linking on StackOverflow!

**Comment by Oteiza-a** [comment]
@nicolo-ribaudo  Hey, maybe this is unrelated, but after the problem of the missing `@babel/types@7.22.18` was solved, i am getting another error on my app runtime: 
`Uncaught ReferenceError: require is not defined`

That i was not getting before, can there be any relation with this?

**Comment by nicolo-ribaudo** [comment]
Please open a new issue :)

**Comment by iammerrick** [comment]
Thank you so much for the quick resolution and communication! ❤️
