### ISSUE TITLE
[Bug]: Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by varunlad** [babel/babel#15964]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

if (typeof process === "object" && process.version === "v20.6.0") {
   if (exports["___internal__alreadyRunning" + ""]) return;
                                                        ^
    Object.defineProperty(exports, "___internal__alreadyRunning", {
     value: true,
    enumerable: false,

(node_modules\@babel\types\lib\index.js: 'return' outside of function.)

### Current and expected behavior

I have compile my Project with npm start it is giving me ERROR in ./node_modules/@babel/types/lib/index.js 

### Environment

Bable Version -^7.21.11,
Node Version - 16.15.1,
Windows PC

**Comment by holynewbie** [comment]
same problem.

![image](https://github.com/babel/babel/assets/8347286/60f7bfb3-8eb1-4bcd-a9f5-72120dc263d3)
