### ISSUE TITLE
want a config-option to  allow  ConstructorTypeParameters

### ISSUE THREAD

**Issue by navegador5** [babel/babel#15983]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

```
   var code = `
      class C { 
          constructor<T0,T1>(p0:T0,p1:T1) {

          }
     }
   `
```
currently the code will throw a ERROR : ConstructorHasTypeParameters
need a option to make the code valid:

### Describe the solution you'd like

I think just  change a little to parseMethod is OK,such as:

```
if (typeParameters && isConstructor) {
     if(allowConstructorHasTypeParameters) {

     } else {
        this.raise(typeParameters.start, TSErrors.ConstructorHasTypeParameters);
     }
}
```

### Describe alternatives you've considered

this will be useful for customer-defined ts-type-checker

**Comment by nicolo-ribaudo** [comment]
You can use `errorRecovery: true`:

```js
import * as parser from "@babel/parser";

function parse(code, opts) {
  const ast = parser.parse(code, { ...opts, errorRecovery: true });
  for (const err of ast.errors) {
    if (err.reasonCode !== "ConstructorHasTypeParameters") throw err;
  }
  ast.errors = null;
  return ast;
}
```
