### ISSUE TITLE
function.name-method transform shadows global with same name

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1598]
```
var test = {
  setInterval: function(fn, ms) {
    setInterval(fn, ms);
  }
};
```

transforms to

```
var test = {
  setInterval: function setInterval(fn, ms) {
    setInterval(fn, ms);
  }
};
```

which is wrong (the inner setInterval now shadows the global).

**Comment by spicyj** [comment]
Thanks!

**Comment by sebmck** [comment]
Fixed as of 5.4.6, thanks!

**Comment by kevinb7** [comment]
@sebmck I'm glad you fixed it.  I was thinking of adding an option to remove ids from all function expressions in the output, but there's probably code that uses the ids in certain situations.

**Comment by spicyj** [comment]
@kevinb7 You can disable the `function.name-method` transformer if you don't want this behavior, which we (currently) do on React core.

**Comment by kevinb7** [comment]
@spicyj I can't seem to find this transform.  I looked on http://babeljs.io/docs/usage/transformers/.  And then I looked in the code.  I found ```transformation/helpers/name-method.js```, is that what you're talking about?

**Comment by sebmck** [comment]
It's not documented for some reason, tracking issue babel/babel.github.io#287.
