### ISSUE TITLE
[Bug]: `interopRequireWildcard` can trigger override mistake

### ISSUE THREAD

**Issue by mhofman** [babel/babel#15995]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
import '@endo/init'
import chalk, { Chalk as ChalkClass } from "chalk@2.4.2";
```

[REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAcgAIFMB2ATCB6YbgwIBQRokscAxgBYCGANgNYA0cA3nAMJ1Ny0DOXHo070BggL5wAZlAgg4AIhoNGSAEwA6ACyb1igNwkgA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2&prettier=false&targets=&version=7.22.20&externalPlugins=&assumptions=%7B%7D)

### Current and expected behavior

When copying props of `module.exports` to `newObj`, `interopRequireWildcard` may use a simple assignment `=`, which may trigger the override mistake for exported properties also present in `Object.prototype` if `Object.prototype` had previously been frozen.

In this case the `chalk` package used by `@babel/code-frame` and `@babel/highlights` in the latest 7.22.20 version of babel triggers this issue [with its `constructor` export](https://github.com/chalk/chalk/blob/v2.4.2/index.js#L42C38-L42C38).

### Environment

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.6.11 - /usr/local/share/npm-global/bin/pnpm
  Monorepos:
    Yarn Workspaces: 1.22.5
  npmPackages:
    eslint: ^8.36.0 => 8.50.0 

### Possible solution

In this case there may be different alternatives to avoid triggering the override mistake:
- make `newObj` with a `null` proto
- Use `Object.defineProperty` in all cases (not just for accessors)

### Additional context

@nicolo-ribaudo will know the context :)

**Comment by nicolo-ribaudo** [comment]
For context, the "override mistake" in this case is that if you freeze `Object.prototype` than you cannot do `newObject["hasOwnProperty"] = 7` because, even if it would install the property on `newObject` and not on `Object.prototype`, that property has a `writable: false` descriptor.

Let's make `newObject` an object with `__proto__: null`, since that's how namespace imports should work in the first place.

**Comment by mhofman** [comment]
@nicolo-ribaudo thanks for implementing a fix for this issue. However as mentioned, the code triggering the override mistake was also published in `@babel/code-frame` and `@babel/highlights` v7.22.13, and while the v7.23.2 included the fix in `@babel/helpers`, the compiled code of the helpers in the above packages is still present in their latest version because no new versions of these packages were published for that release. Is there any way babel could have a minor version bump of the `@babel/code-frame` and `@babel/highlights` packages in the next v7 release?
