### ISSUE TITLE
Babel transpiles incorrectly when flow is blacklisted

### ISSUE THREAD

**Issue by astoilkov** [babel/babel#1599]
I have two files:

doSomething.js
```javascript
/* @flow */
import Property from './Property';

function doSomething(property:Property) { }
```

Property.js
```javascript
/* @flow */
export default class Property {
}
```

This setup transpiles incorrectly and flow encounters an error:
```javascript
/* @flow */
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _Property = require('./Property');

var _Property2 = _interopRequireDefault(_Property);

function doSomething(first: number, second: number, third: _Property2['default']) {
  return first + second;
}
```

The error is thrown on the line below:
```javascript
function doSomething(first: number, second: number, third: _Property2['default']) {
```

Flow throws unhandled parse error. If you need I could send you a link to a zip with the entire project.

**Comment by venelinpetrov** [comment]
+1

**Comment by sebmck** [comment]
There's no way that this can be fixed. Flow already supports ES6 modules and performs the exact same interop as Babel so there's no need to have it enabled.

**Comment by astoilkov** [comment]
However, Flow does not support some other ES6 features right? I have tried running Flow first but it errors with some other syntax exceptions. What do you recommend so I could have ES6 code and use Flow inside of it and then be able to compile it to ES5 and also check the Flow syntax.

**Comment by sebmck** [comment]
@astoilkov Flow does not support **some** ES6 features, yeah. As I said before though, it does support ES6 modules and uses the **exact** same interopability that Babel has.
