### ISSUE TITLE
expand support for async functions

### ISSUE THREAD

**Issue by tracker1** [babel/babel#1600]
There are a couple points of `stage 0` support for async methods that would be nice to expand upon

1. ~~Lambda syntax for async functions: `^()=>...` as sugar for `async function(){...}`~~
  * short syntax still in flux `async ()=>` should work
2. ~~await* : `let [r1,r2,r3] = await* [p1,p2,p3]` as sugar for `await Promise.all([r1,r2,r3])`~~
  * working in latest version (5.4.7 as of update)
3. exports: 
  * `export async function foo(){ ... }` (currently broken)
  * `export default async function(){ ... }` (currently broken)
  * ~~`export let foo = ^()=>...`~~ (see 1 above)

The issues with the export support I would consider a bug (currently working around with `export {funcName as default}`), the rest would be feature enhancements.

**Comment by tracker1** [comment]
As an addendum, I want to thank everyone who has worked on babel/6to5 over the years, It has allowed me to improve my code and workflows immeasurably over past year, with lambdas, async and await being a huge part of that ...

**Comment by sebmck** [comment]
> 1. Lambda syntax for async functions: `^()=>...` as sugar for `async function(){...}`

You can already do async arrow functions:

```javascript
(async () => {})
```

Not particularly keen on supporting alternate syntax for it, especially when there's no consensus on it. Doubtful that it'll be implemented too as generator arrow functions aren't a thing either.

> 2. await* : `let [r1,r2,r3] = await* [p1,p2,p3]` as sugar for `await Promise.all([r1,r2,r3])`

[This is already implemented.](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=async%20function%20foo()%20%7B%0A%20%20await*%20bar%3B%0A%7D&playground=false)

> 3. exports: 
>  * `export async function foo(){ ... }` (currently broken)
>  * `export default async function(){ ... }` (currently broken)
>  * `export let foo = ^()=>...`

Your first two examples [work](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=export%20async%20function%20foo()%20%7B%20%7D%0A%0Aexport%20default%20async%20function()%7B%20%7D&playground=false) so unsure how they're broken?

> As an addendum, I want to thank everyone who has worked on babel/6to5 over the years

Thank you for using it! Babel isn't even a year old though. :stuck_out_tongue: [First commit was October last year](https://github.com/babel/babel/graphs/contributors).

**Comment by tracker1** [comment]
@sebmck thanks

1. - Understandable

2. It seems to be working from me in babel-node 5.4.7, I was trying it earlier and it wasn't... *shrug*

It seemed that 6to5 has been around longer than that... I was using Traceur before switching, and since January have been using 6to5/Babel.

So I guess 3. fixing exports is really the only issue with standing.

**Comment by sebmck** [comment]
Nope, late October is when Babel development started :smile: As I said about exports, the two examples that you listed as broken do in fact work so I'm unsure what the exact issue is that you're describing?

**Comment by sebmck** [comment]
Closing for reasons stated above.
