### ISSUE TITLE
[Feature Request] provide import/exports in metadata

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#1601]
given:

```js
// lib/bar.js
import foo, { baz } from 'bar';
import apple from '../orange';

export var a = 1;
export default function User()  { }
```

maybe something like ?

```js
metadata.deps === {
  imports: [
    {
      id: 'bar',
      imports: ['default', 'baz']
    },

    {
      id: 'lib/apple',  // these ID's should take into account the optional resolution
      imports: ['default']
    }
  ],

  exports: [
    'default',
    'a'
  ]
}
```

**Comment by zertosh** [comment]
I'd use this :+1:

**Comment by novacrazy** [comment]
I could definitely use this. Right now I have a custom regex 'parser' that looks for AMD defines and gathers dependencies like that. Having them straight in the metadata of the compiled ES6/7 source would save a lot of time and effort.

**Comment by sebmck** [comment]
How would `export * from "bar";` be represented?

**Comment by novacrazy** [comment]
@sebmck It would add a lot of values, since it's exporting everything, but perhaps something like this:

```javascript
metadata.deps === {
  imports: [
    {
      id: 'bar',
      imports: [],
      exports: [/*Copy over whatever names bar exports*/]
    },

    {
      id: 'lib/apple',  // these ID's should take into account the optional resolution
      imports: ['default'],
      exports: [] //empty if nothing from lib/apple is exported using the extended export
    }
  ],

  exports: [
    'default',
    'a',
    /*Also copy over whatever names were mass exported*/
  ]
}
```

**Comment by sebmck** [comment]
@novacrazy There's no way for Babel to know the exports of the external module when doing `export * from "foo";`.

**Comment by novacrazy** [comment]
Yeah, good point. That would require some extra static analysis of other files. I'm too used to TypeScript. 

Well, perhaps:

```javascript
metadata.deps === {
  imports: [
    {
      id: 'bar',
      imports: ['default', 'baz'],
      exports: '*' // or ['each', 'name', 'exported']
    },

    {
      id: 'lib/apple',  // these ID's should take into account the optional resolution
      imports: ['default'],
      exports: null // Nothing exported directly
    }
  ],

  exports: [
    'default',
    'a'
  ]
}
```

Then leave `metadata.deps.exports` only for normally exported names.

**Comment by stefanpenner** [comment]
@sebmck I think it Should maybe represent it as a link. So tooling can resolve it later if it has the whole graph

**Comment by stefanpenner** [comment]
@sebmck any luck?

**Comment by sebmck** [comment]
@stefanpenner Will unlikely have time to get around to it this week, likely this weekend, as the data structure is seemingly more complicated than I would've first anticipated and don't want make any haste implementations.

**Comment by stefanpenner** [comment]
@chadhietala can you review this proposed module format?

**Comment by stefanpenner** [comment]
> as the data structure is seemingly more complicated than I would've first anticipated and don't want make any haste implementations.

Ya good call, don't want to rush this.

**Comment by chadhietala** [comment]
@stefanpenner @sebmck Are the exports needed on a per import basis?

**Comment by stefanpenner** [comment]
I believe the goal of `mod.deps` isn't to provide comphrensive static analyis,
rather to indicate loosely what edges the given module introduces to the larger
graph.

What I mean is, `mod.deps` should only report data that can be observed by
analyzing, a single module, and then only derived based on the static import /
export statements. It should not attempt to derive any relationships between import
and export statements.

Obviously some expressions, such as `export { * } from 'bar'` inherently share
this information. But others, which expose the binding may require runtime
analyis and as such should be left to more other tools.

Some refined examples:

```js`
// lib/bar.js
import foo, { baz } from 'bar';
import apple from '../orange';

export var a = 1;
export default function User()  { }
```

could produce:

```js
mod.deps = {
  imports: [
    {
      id: 'bar',
      imports: ['default', 'baz']
    },
    {
      id: '../orange',
      imports: ['default']
    }
  ],

  exports: ['a', 'default']
}
```

-----

```js
export default from 'other'
```

or

```js
export { default } from 'other'
```

could produce:

```js
mod.deps = {
  imports: [
    {
      id: 'other',
      imports: ['default']
    }
  ],

  exports: ['default']
}
```

--------

```js
export { * } from 'other'
```

could produce:

```js
mod.deps = {
  imports: [
    {
      id: 'other',
      imports: ['*']
    }
  ],

  exports: ['*']
}
```

----------


```js
export * as NS from 'other'
export default NS;
```

could produce:

```js
mod.deps = {
  imports: [
    {
      id: 'other',
      imports: ['*']
    }
  ],

  exports: ['default']
}
```

**Comment by sebmck** [comment]
This has been released as of 5.5.5, thanks! I'll hopefully get around to writing docs soon but the tests in the referenced commit should be enough for the impatient :smile:.

**Comment by chadhietala** [comment]
Thanks @sebmck!

**Comment by stefanpenner** [comment]
Thank you kindly sir. Thank you for iterating on the format
