### ISSUE TITLE
[Feature request] babel --module-id resolve relative imports (optionally)

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#1602]
given:

```js
// lib/bar.js
import foo from './baz';
```

```sh
babel lib/bar.js --module amd --module-id lib/bar
```

produces:
```js
define('lib/bar', ['./baz'], function(baz) {

});
```

It would be quite handy, if it could also (maybe optionally) resolve the relative require to `'lib/baz'`

which would produce:

produces:
```js
define('lib/bar', ['lib/baz'], function(baz) {

});
```

**Comment by sebmck** [comment]
Unsure if this belongs in core you could already do this yourself with the `resolveModuleSource` option:

```javascript
require("babel-core").transform('import foo from "foo";', {
  filename: "/bar/foo.js",
  resolveModuleSource: function (moduleSource, filename) { relative logic here; }
});
```

**Comment by stefanpenner** [comment]
Would be handy in core, but yes you are correct I believe that callback is sufficient

**Comment by stefanpenner** [comment]
I am curious why when providing --module-id this wouldn't be the default behavior ? This would be quite handy when just using babel quickly as a general purpose command line tool

**Comment by sebmck** [comment]
@stefanpenner Dunno, just seems weird to have Babel aware of directory structure.

**Comment by stefanpenner** [comment]
> @stefanpenner Dunno, just seems weird to have Babel aware of directory structure.

potentially, but convention here would go a long way.

**Comment by sebmck** [comment]
Then there'd need to be a way to opt out of it and that adds yet another option.

**Comment by stefanpenner** [comment]
> Then there'd need to be a way to opt out of it and that adds yet another option.

Ya, that kinda sucks. Maybe someday the world can agree on a convention here.

It seems like there is opposition to adding this extra functionality, until such time as the choice isn't ambiguous. Ultimately this is more of a "nice thing" but I believe It can be solved with the existing API, just requiring a small JS program over simpler CLI.

This is fine, as It isn't of huge importance. :)
