### ISSUE TITLE
[Bug]: Versioning error of transform-classes in @babel/preset-env

### ISSUE THREAD

**Issue by nanianlisao** [babel/babel#16030]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
const { transformSync } = require('@babel/core');

const { code } = transformSync(`class A {}`, {
  strict: false,
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          chrome: 46,
        },
      },
    ],
  ],
});

console.log(code); // class A {}
```

### Current and expected behavior

plugin-transform-classes should be loaded and class should be translated.
Because on [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class#browser_compatibility), the browser_compatibility of the class is `chrome 49`, whereas the babel specifies `chrome 46`.

### Environment

- babel version  7.22.20

### Possible solution

Changing the [babel source code](https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugins.json#L489) to `chrome 49`

**Comment by nicolo-ribaudo** [comment]
compat-data also only makrs them as supported just from Chrome 49: https://github.com/compat-table/compat-table/blob/6b68e5109b47771581d47faba6d4c5077f72061e/data-es6.js#L2842

**Comment by nanianlisao** [comment]
I'm sorry, I didn't understand what you meant,
But from the running results, I think this is a defect that needs to be fixed.

**Comment by JLHwung** [comment]
Yes we already marked it as a bug.

To obtain Chrome 46, you can visit https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html, go to the related platforms, and download the first version greater than 344925.

You can obtain the snapshot version from https://omahaproxy.appspot.com/:
<img width="628" alt="image" src="https://github.com/babel/babel/assets/3607926/2509f9ee-12ca-4b77-bbe9-533cc50d434a">

**Comment by nanianlisao** [comment]
> Yes we already marked it as a bug.

@JLHwung @nicolo-ribaudo How should this problem be solved? It seems like a modification with serious implications

https://github.com/babel/babel/blob/7e198e5959b18373db3936fa3223c0811cebfac1/packages/babel-compat-data/scripts/utils-build-data.js#L68-L78

**Comment by nanianlisao** [comment]
Got it, thanks for the explanation
