### ISSUE TITLE
[Bug]: Fails to parse expression satatement `(await) satisfies unknown;`

### ISSUE THREAD

**Issue by seiyab** [babel/babel#16047]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
(await) satisfies unknown;
```

### Current and expected behavior
Currently, it fails to parse with following error.
```
/repl.tsx: Unexpected token (1:6)

> 1 | (await) satisfies unknown;
    |       ^
```

Should successfully parse it.
TypeScript Playrgound doesn't yield error.
https://www.typescriptlang.org/play?#code/DYUwLgBAhg7lCWkC8EAMBuAUAClgsAlBAM5RjzEBm8IxEArgHYDWjA9jI+kA

### Environment
```
System:
  OS: macOS 13.4.1
Binaries:
  Node: 17.7.2 - ~/.asdf/installs/nodejs/17.7.2/bin/node
  Yarn: 3.6.3 - ~/.asdf/installs/nodejs/17.7.2/.npm/bin/yarn
  npm: 8.5.2 - ~/.asdf/plugins/nodejs/shims/npm
npmPackages:
  @babel/code-frame: 7.22.13 => 7.22.13
  @babel/generator: 7.22.15 => 7.22.15
  @babel/parser: 7.23.0 => 7.23.0
  @babel/types: 7.23.0 => 7.23.0
  eslint: 8.50.0 => 8.50.0
  jest: 29.7.0 => 29.7.0
```

Instantly reproducible here: https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=BQQw7iCWAuCUAEBnE1KIGaQKaPgVwDsBrAgezAIG4g&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.23.2&externalPlugins=&assumptions=%7B%7D

### Additional context

I have found this error investigating a Prettier issue.
https://github.com/prettier/prettier/issues/15491

**Comment by seiyab** [comment]
I also found `type satisfies never` accidentally be parsed successfully though TypeScript reports syntax error.
This might relate to https://github.com/babel/babel/issues/16048, that I considered independent one once.

**Comment by nicolo-ribaudo** [comment]
`(await)` is not a valid expression in modules.

It parses successfully if you set your source type to "script": https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=BQQw7iCWAuCUAEBnE1KIGaQKaPgVwDsBrAgezAIG4g&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.23.2&externalPlugins=&assumptions=%7B%7D

**Comment by seiyab** [comment]
Thank you, I probably
 understand!
