### ISSUE TITLE
Class transform depends on blockScoping

### ISSUE THREAD

**Issue by amasad** [babel/babel#1606]
If you disable `es6.blockScoping` transform then class compiles to `let className = function`.
Anyway we can remove that dependency? Or at least let it resolve internally.

**Comment by sebmck** [comment]
Intentional behaviour. Classes are block scoped and have a TDZ. This is required to give the `es6.spec.blockScoping` transformer that provides TDZ contextual information that it's a block binding. This is the same for the `es6.parameters.default` transformer.

**Comment by amasad** [comment]
I understand, I did that too when I wrote default params, but made the transform smart enough to run the dependent transform (before/after) it ran. This way, I can share the functionality without leaking the implementation details and still have the features togglable. Are you interested in something like this? I can look into seeing if we can do this cleanly.

For the use case, Flow doesn't currently support block scoping and it'd be great if the compiler didn't enable it as well.

**Comment by sebmck** [comment]
There's not really a way to do partial transforms. Would likely require another traversal since a transformer may be visiting multiple nodes so you can't just call the visitor function. What's your use-case for disabling `es6.blockScoping` if nothing in your pipeline supports it?

**Comment by amasad** [comment]
>What's your use-case for disabling es6.blockScoping if nothing in your pipeline supports it?

Not all files in our codebase are flow-enabled yet. Flow can interop with non-flow files, so that means that  part of our pipeline is all Babel. An engineer could be working on a feature, and testing, say in Firefox, and see that let/const "works" and commits the code.

Another way we can protect against this is via linting, however, our lint infra is still stuck on jshint and esprima which I don't think even parses let/const.

Maybe I can work around this by having a Babel plugin, that simply throws when it sees a block scoped node. Thoughts?

**Comment by sebmck** [comment]
@amasad 

> Maybe I can work around this by having a Babel plugin, that simply throws when it sees a block scoped node.

This is probably the easiest. Unsure how partial transforms would factor into the traversal algo as sometimes visiting parent nodes is necessary and you wouldn't know what nodes to restrict a partial transform to.

This *should* be enough to error on all block scoped nodes:

```javascript
module.exports = function (babel) {
  return new Transformer("transformer-name", {
    BlockScoped: function () {
      throw this.errorWithNode("error message here");
    }
  });
};
```

It'll cover `class Foo {}`, `const foo = "bar";` and `let foo;`. Specify the plugin as `after` if you only want to check the actual compiled source for the presence of these nodes.

**Comment by kevinb7** [comment]
@amasad Thank you for posting this issue.  I'm using a whitelist and ran into an issue with ```let``` showing up in the generated code.  Adding ```es6.blockScoping``` fixed the issue.

**Comment by sebmck** [comment]
Closing due to reasons listed before. Desugaring ES6 to other ES6 is necessary in order to delegate to other transformers.
