### ISSUE TITLE
Async arrow functions should use lexical scope

### ISSUE THREAD

**Issue by jgebhardt** [babel/babel#1607]
Specifically, in the following example, I would expect `this.foo` to get tranformed to `_this.foo`.

Input:
```javascript
var asyncTest = async () => {
  return this.foo;
};
```

Output:
```javascript
var asyncTest = function asyncTest() {
  return regeneratorRuntime.async(function asyncTest$(context$3$0) {
    while (1) switch (context$3$0.prev = context$3$0.next) {
      case 0:
        return context$3$0.abrupt('return', this.foo);

      case 1:
      case 'end':
        return context$3$0.stop();
    }
  }, null, _this);
};
```

Live example with more test cases:
http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=class%20Experimental%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20this.foo%20%3D%20'bar'%3B%0A%20%20%7D%0A%0A%20%20test()%20%7B%0A%20%20%20%20%2F*%20incorrect%20context%3A%20expected%20%60_this%60%2C%20got%20%60this%60%20*%2F%0A%20%20%20%20var%20asyncTest%20%3D%20async%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20this.foo%3B%0A%20%20%20%20%7D%3B%20%0A%20%20%20%20%0A%20%20%20%20%2F*%20correct%20context%3A%20%60this%60%20*%2F%0A%20%20%20%20var%20asyncTestNoArrow%20%3D%20async%20function()%20%7B%0A%20%20%20%20%20%20return%20this.foo%3B%0A%20%20%20%20%7D%3B%0A%0A%20%20%20%20%2F*%20correct%20context%3A%20%60_this%60%20*%2F%0A%20%20%20%20var%20syncTest%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20this.foo%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20%2F*%20correct%20context%3A%20%60this%60%20*%2F%0A%20%20%20%20var%20syncTestNoArrow%20%3D%20function()%20%7B%0A%20%20%20%20%20%20return%20this.foo%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

**Comment by loganfsmyth** [comment]
It is passing `_this` to the `regeneratorRuntime.async` function to set the context. Running your code, it seems to work as I'd expect.

**Comment by sebmck** [comment]
Yep, @loganfsmyth is correct. There's no bug here, the scope is correctly being resolved.
