### ISSUE TITLE
ES7 Decorators get/set error

### ISSUE THREAD

**Issue by mako-taco** [babel/babel#1608]
When trying to define `get` or `set` methods via a decorator, an error is thrown.

**Error:**
`Uncaught TypeError: Invalid property.  A property cannot both have accessors and be writable or have a value, [object Object]`

**Example code:**
```js
var literal = {
	@testGetSet
	what() {
		
	}
}

function testGetSet(target, fnName, descriptor) {
	delete descriptor.initializer;
	delete descriptor.value;

	descriptor.writable = false;
	
	descriptor.set = function (val) {
		value = val;
	};
	
	descriptor.get = function () {
		return value;
	};
	
	setTimeout(() => console.log(descriptor));
	
	return descriptor;
};
```

**Console log**:
![image](https://cloud.githubusercontent.com/assets/2238381/7777109/2cbb5be2-008e-11e5-9285-623a436e8055.png)

**Comment by mako-taco** [comment]
Sorry, apparently you cannot include `writeable` at all! False or true, both error out. It must be deleted.  Sorry..

**Comment by monsanto** [comment]
@mako-taco you may find it easier to just return `{get: ..., set: ...}` instead of deleting every other property from `descriptor`

**Comment by mako-taco** [comment]
yes, yes I do.  I thought I needed to return the original descriptor, mutated, for some reason.  Thanks!
