### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'addHelper')

### ISSUE THREAD

**Issue by SidneyLann** [babel/babel#16094]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

https://github.com/SidneyLann/taro-test-repo.git

### Configuration

const { mergeConfig } = require('metro-config')
const { getMetroConfig } = require('@tarojs/rn-supporter')

module.exports = (async function (){
return mergeConfig({
// custom your metro config here
// https://facebook.github.io/metro/docs/configuration
resolver: {}
}, await getMetroConfig())
})()

### Current and expected behavior

compile successfully. no "Cannot read properties of undefined (reading 'addHelper') "

### Environment

System:
OS: Windows 10 10.0.22621
Binaries:
Node: 20.3.1 - D:\DEV\nodejs\node.EXE
Yarn: 1.22.19 - D:\DEV\nodejs\yarn.CMD
npm: 9.6.7 - D:\DEV\nodejs\npm.CMD
npmPackages:
@babel/core: ^7.23.2 => 7.23.2
@babel/runtime: ^7.23.2 => 7.23.2
babel-preset-taro: 3.6.16 => 3.6.16
eslint: ^8.12.0 => 8.46.0
react-native: ^0.70.1 => 0.70.13
webpack: ^5.88.2 => 5.88.2

### Additional context

"resolutions": {
"@babel/traverse": "7.23.2",
"@babel/core": "7.23.2"
}

this not work for me

**Comment by liuxingbaoyu** [comment]
I can reproduce it. And it's different from https://github.com/babel/babel/issues/15752, even if I specify `@babel/traverse` as the latest version or `7.18.0`, the error still exists.

**Comment by liuxingbaoyu** [comment]
The `babel-plugin-minify-dead-code-elimination` plugin is causing this issue, it was last updated two years ago and is no longer maintained, please report this issue to the owner of `babel-preset-taro` for removal this plugin.
![image](https://github.com/babel/babel/assets/30521560/5ea36f7f-9d4b-4135-b7ca-a13e51c2a6ed)

**Comment by liuxingbaoyu** [comment]
cc @nicolo-ribaudo I noticed that we are the publisher of this plugin, maybe let us deprecate it?

**Comment by SidneyLann** [comment]
Thank you very much!
