### ISSUE TITLE
[Bug]: not found 7.23.3

### ISSUE THREAD

**Issue by kangdiandian** [babel/babel#16093]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.23.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Current and expected behavior

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.23.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Environment

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.23.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Additional context

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.23.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by codercqw** [comment]
how to fix the problem ？

**Comment by LbhFront-end** [comment]
the same problem when i install the old project,where umi@3.1.4 dependence  @babel/helper-module-transforms@^7.23.3

```shell
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @babel/helper-module-transforms@^7.23.3

This error happened while installing the dependencies of umi@3.1.4
 at @umijs/core@3.1.4
 at @umijs/babel-preset-umi@3.1.4
 at @babel/preset-env@7.9.5
 at @babel/plugin-transform-modules-amd@7.23.3

The latest release of @babel/helper-module-transforms is "7.23.0".

Other releases are:
  * next: 8.0.0-alpha.4
  * esm: 7.21.4-esm.4

If you need the full list of all 103 published versions run "$ pnpm view @babel/helper-module-transforms versions".
 WARN  deprecated date-format@0.0.0: 0.x is no longer supported. Please upgrade to 4.x or higher.
Progress: resolved 1973, reused 1963, downloaded 2, added 0
```
