### ISSUE TITLE
[Bug]: @babel/preset-env@7.23.3 does not understand optional chaining 

### ISSUE THREAD

**Issue by AlexMelw** [babel/babel#16103]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I remeber `@babel/preset-env@7.23.0` was including `@babel/plugin-transform-optional-chaining`

Why `@babel/preset-env@7.23.3` does not understand optional chaining anymore?

Is adding the `@babel/plugin-transform-optional-chaining` plugin explicitly now the only option to make optional chaining work?

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [
        [ "@babel/preset-env", { "useBuiltIns": "entry", "corejs": "3.33" } ],
        "@babel/preset-react"
    ],
    "plugins": [
        [ "babel-plugin-styled-components", { "pure": true } ],
        "@babel/plugin-transform-class-properties"
    ]
}
```

### Current Behavior

When I run my Webpack build, I receive a parsing error indicating that the optional chaining syntax is not recognized:

```
Module parse failed: Unexpected token (30:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           data
|         } = config;
>         if (data?.SessionExpiryWarning?.SessionExpiryWarningTimeInSeconds) {
|           const {
|             SessionExpiryWarningTimeInSeconds
```

This error suggests that the optional chaining operator is not being processed by Babel as expected.

### Expected Behavior
The expected behavior is for Babel to recognize the optional chaining syntax and transpile it to function correctly in environments that may not support this newer JavaScript feature. This would typically be handled by @babel/preset-env which should include the necessary plugin to transpile optional chaining.

### Environment

- Babel version: v7.23.3
- Node: v14.21.3
- npm version: 6.14.18
- OS: Microsoft Windows 10 Enterprise 10.0.19045 Build 19045
- Webpack version: 4.47.0

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/options#targets
Please set `targets`.

**Comment by AlexMelw** [comment]
> https://babeljs.io/docs/options#targets Please set `targets`.

Hi @liuxingbaoyu, thanks for the suggestion
I'm currently using `.browserslist` config file for setting `defaults` targets

![image](https://github.com/babel/babel/assets/15247302/af7e20e1-e7d7-4571-8596-3a79be11f94c)

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=CYQwLiD8B0DKCmBnRBLA9gOwKIA8AOKATgJ4DqIhGKGA5jAsutvkWRVbQCooC28AkhgQBjTMERA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.3&externalPlugins=&assumptions=%7B%7D

I suspect `defaults` means that the target already supports optional chaining.

**Comment by AlexMelw** [comment]
> https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=CYQwLiD8B0DKCmBnRBLA9gOwKIA8AOKATgJ4DqIhGKGA5jAsutvkWRVbQCooC28AkhgQBjTMERA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.3&externalPlugins=&assumptions=%7B%7D
> 
> I suspect `defaults` means that the target already supports optional chaining.
> 
> https://babeljs.io/repl#?browsers=node%206&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=CYQwLiD8B0DKCmBnRBLA9gOwKIA8AOKATgJ4DqIhGKGA5jAsutvkWRVbQCooC28AkhgQBjTMERA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.3&externalPlugins=&assumptions=%7B%7D
> 
> If I set the target to `node 6`, it will convert the optional chain.

You're right, changing the targets (even using `.browserslist`) removes the build issue. 
![image](https://github.com/babel/babel/assets/15247302/1dd03a31-04d7-43b4-9c13-4b1b5310c4ad)
Yet, specifying `defaults, node 10` as targets for the purpose of fixing pipeline builds is not a solution.
The final consumers are **browsers**, not the Node environment.
Should we consider it a bug 🐛 in this case?

**Comment by liuxingbaoyu** [comment]
> You can pick a sound set of versions with the [defaults](https://browsersl.ist/#q=defaults) query which is a shortcut for > 0.5%, last 2 versions, Firefox ESR, not dead. It matches recent versions of popular and supported browsers worldwide and includes Firefox Extended Support Release which is updated roughly annually.
> 
> The [defaults](https://browsersl.ist/#q=defaults) query was thoroughly designed by the Browserslist community. It helps promote best practices and avoid common pitfalls.

`default` means you only support popular browsers, if your consumers are using older browsers you should set this manually.
