### ISSUE TITLE
[Bug]: decorators don't support static properties

### ISSUE THREAD

**Issue by alexpods** [babel/babel#16105]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
function decorate(...args) {
    return (target, context) => {
    	if (context.kind === 'method') {
            return function (...innerArgs) {
            	console.log(args)
              	return target.call(this, ...innerArgs)
            }
        }
    }
}

class A {

  static STATIC_PROP = "static_prop"

  @decorate(A.STATIC_PROP) // <= ERROR Cannot access 'A' before initialization
  hello() {
  	console.log("HELLO")
  }        
}  
```

### Current and expected behavior

Now it's impossible to use static class properties as parameters for decorator initializers. We've got the error: `Cannot access 'A' before initialization` because it transpiles the code into something like:

```js
_dec = decorate(A.STATIC_PROP); // <= HERE THE PROBLEM !!!
class A {
  constructor(...args) {
    _initProto(this);
  }
  hello() {
    console.log("HELLO");
  }
}
_class = A;
[_initProto] = _applyDecs(_class, [[_dec, 2, "hello"]], []).e;
_defineProperty(A, "STATIC_PROP", "static_prop1");
```

But static properties should be accessible as we're trying to get them inside of the class context.

### Environment

- Babel: 7.22.9
- Node: 16
- OS: Mac

### Additional context

A link to babeljs REPL to check the problem: https://babeljs.io/repl/#?browsers=&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAEwKYTgJwIZVQCgDpjtMBzAZwEpEBvAKAEhNUoRMl8pSzWAaRBjB4AHlBoBeAHx16ieYkYxgifENFRCAaxhhkiCYcQByALasAFnGTGaDBQ8Us2HRKEiwEq4oV1hUmACC5NSyjuGKQhRwADaohDFwZPg81HIR4cys7Ejc5KyEENgxMVwWMBQCPn4BwZRU6RnyAL6Njq0Ora30EDHYFBSIgbLpFNywEIgAygAqgTMAkgDCAPoACgBKAPJrBogARGO4MBArAA6YcGcAjPv06QACaBg4ePiBhLPzy-vbaw3yCyoEpwfB2dKMKKxeKJZL7AASAFEADLIrb7AGIZoZejYxD0IA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cstage-3&prettier=false&targets=Node-10.1&version=7.23.3&externalPlugins=&assumptions=%7B%7D

**Comment by nicolo-ribaudo** [comment]
@pzuraq Is this expected to work according to the proposal?

**Comment by alexpods** [comment]
@nicolo-ribaudo yes, it looks like you're right - https://github.com/tc39/proposal-decorators#1-evaluating-decorators

``
Decorators are evaluated as expressions, being ordered along with computed property names. This goes left to right, top to bottom. The result of decorators is stored in the equivalent of local variables to be later called after the class definition initially finishes executing.
```

I'm closing the issue.
