### ISSUE TITLE
babel-node: Unexpected token import

### ISSUE THREAD

**Issue by interactionist** [babel/babel#1611]
Hi there.

I try to run a file with ```babel-node src/bin/server.js```, but I get the following error:

```bash
import http from "http";
^^^^^^
SyntaxError: Unexpected token import
```

---

server.js

```js
"use strict";

import http from "http";
import cluster from "cluster";
import os from "os";

```

**Comment by interactionist** [comment]
Okay, the problem is that once a worker dies, it restarts with ```node src/bin/server.js``` instead of ```babel-node  src/bin/server.js```. Any ideas how to fix that?

**Comment by Mark-Simulacrum** [comment]
The code below is a potential workaround. The problem seems to lie in that `babel-node` spawns a child process/replaces itself with `node` running the compiled code. The code I provided will instead spawn child processes with `babel-node` compiling them in turn. I don't know if this will work for the `http` use-case, but it might, so I thought I would provide it. It does a very simple representation of what `node`'s `cluster` module does to spawn child processes.

Another (simpler?) way of doing this is `babel FILE > /tmp/temp.js && node /tmp/temp.js` (where `FILE` is the location of the file you wish to execute). This compiles the file through babel and then runs `node` on the compiled file, avoiding the issues you are seeing. This would prevent babel's polyfill from loading, though. (You would need to require it manually for the polyfill to load).

```js
import childProcess from "child_process";

const childAmount = 4;
const isMaster = !("NODE_CLUSTER_PROCESS" in process.env);

function childPrint(childNum, data) {
    process.stdout.write(`Child Process #${childNum} Stdout: ${data}\n`);
}

if (isMaster) {
    process.stdout.write(`master process running with args: ${JSON.stringify(process.argv)}\n`);

    for (let num = 1; num <= childAmount; num++) {
        let child = childProcess.spawn("babel-node", process.argv.slice(1), {
            env: Object.assign(process.env, {
                // This allows the child process to detect that it isn't the master
                "NODE_CLUSTER_PROCESS": "true"
            })
        });
        child.stdout.on("data", childPrint.bind(null, num));
    }
} else {
    process.stdout.write(`cluster process running with args: ${JSON.stringify(process.argv)}`);
}
```

**Comment by monsanto** [comment]
If you are using io.js, you should be able to use `babel/register` as a preload hook (the `-r` switch) instead of using `babel-node`. This switch will be propagated by worker restarts.

**Comment by interactionist** [comment]
@Mark-Simulacrum Thanks for that. Will try it out!
@monsanto I've been using ```babel-register``` for now, tho it requires a separate file to run from :/ I thought ```babel-node``` would be a more elegant way.

**Comment by Mark-Simulacrum** [comment]
@interactionist
@monsanto is saying that `iojs -r "./node_modules/babel/register" FILE` will run the file with `babel/register` required, and everything spawned from it through `node`'s APIs. This means that you won't need the separate file to use `babel/register`.

**Comment by interactionist** [comment]
@Mark-Simulacrum I missed that io.js part. Thanks.

**Comment by sebmck** [comment]
If `babel-node` also set `process.execPath` then this would probably be fixed.

**Comment by interactionist** [comment]
@sebmck You reckon this to get it working without the workarounds above?

**Comment by sebmck** [comment]
Attached patch fixes this and makes it **just work** without any user trickery.

**Comment by interactionist** [comment]
+1

**Comment by sjmueller** [comment]
Can the command `iojs -r "./node_modules/babel/register" FILE` be run with `node-inspector` with `iojs`?  

The `-r` switch seems to get ignored with `node-debug -r "./node_modules/babel/register" server.js`, which results in the same error as OP.

cc @3y3

**Comment by 3y3** [comment]
Maybe:
`node-debug --nodejs="-r ./node_modules/babel/register" server.js`

**Comment by sjmueller** [comment]
@3y3 I tried that, but unfortunately no go.  Also tried `node-debug --nodejs="-r './node_modules/babel/register'" server.js` and `node-debug --nodejs "-r './node_modules/babel/register'" server.js` to no avail.

**Comment by hardchor** [comment]
@sjmueller Try `node -r "./node_modules/babel-core/register" FILE`
