### ISSUE TITLE
[BABEL8] Release updates to npm

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#16142]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Could you please publish new versions of Babel 8 according to [v7.23.5](https://github.com/babel/babel/releases/tag/v7.23.5).

### Describe the solution you'd like

publish babel 8 to npm

### Describe alternatives you've considered

-

**Comment by nicolo-ribaudo** [comment]
There are a bunch of Babel 8 PRs close to landing, I was waiting for them to be merged. It will take a couple of days.

**Comment by coderaiser** [comment]
> "The last will be first, and the first last"
> (c) (Matthew 20:16)

I see there is a [new version came up](https://github.com/babel/babel/releases/tag/v7.23.6), could you please publish a new version of Babel 8, or point how many issues is needed to be merged?

**Comment by nicolo-ribaudo** [comment]
Yes I'm doing it now, it's taking a while due to some problems in the publishing process.

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/releases/tag/v8.0.0-alpha.5
