### ISSUE TITLE
[Bug]: Destructuring assignment transformed for chrome 49

### ISSUE THREAD

**Issue by luckymore** [babel/babel#16156]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code
```js
[a, b] = [];

c = [[...[1,2,3]]];
```

### Configuration file name

.babelrc

### Configuration

```
chrome 49
```

### Current and expected behavior

`destructing assignment` supported with `chrome 49`, should not be transformed

![image](https://github.com/babel/babel/assets/5390013/f118b5d4-a080-4d64-b8e4-6705e4b6868a)

[demo](https://babeljs.io/repl#?browsers=chrome%2049&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=NoQwNABARguhC8FgwNwCg0GMFOAOgOAEYwAmMAZhmvTSA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=8.0.0-alpha.2&externalPlugins=&assumptions=%7B%7D)

### Environment

- Babel: Latest

**Comment by nicolo-ribaudo** [comment]
You can find our compatibility data in https://github.com/babel/babel/tree/main/packages/babel-compat-data/data, which is generated from https://github.com/compat-table/compat-table (and has more precise data than caniuse). Specifically, it looks like this destructuring test only passes in Chrome 51: https://github.com/compat-table/compat-table/blob/1a1ccdc02b8b2158ab39a6146d8a7308f43c830b/data-es6.js#L15361

**Comment by luckymore** [comment]
I think it closer to `with arrays`
```
[a, b] = [1, 2];
```

**Comment by luckymore** [comment]
uha, I get it. All `subtests` need to pass in order for a feature to be considered supported.
Is that right? @nicolo-ribaudo

**Comment by liuxingbaoyu** [comment]
Yes, Babel will target the worst case scenario for conversions.
Unless there are some particularly common real-world use cases.
Specific to this example, people often do not deconstruct an array literal, but deconstruct an identifier.
Although Babel can do some inference in some sophisticated ways, that requires a lot of work and has performance implications, so there will be some sub-optimal output.

**Comment by luckymore** [comment]
Thank you for your patience! ❤️

**Comment by JLHwung** [comment]
> Babel now use @mdn/browser-compat-data instead of caniuse-lite?

Babel draws modules related compat-data from the `@mdn/browser-compat-data`. Babel does not depend on `caniuse-lite` directly. Instead it is a dependency of `browserslist`, which is used by Babel to get the compilation targets from `browserslist` config.

> Isn't there a risk, if browserslist on caniuse-lite and babel on @mdn/browser-compat-data coexist my project?

AFAIK, no. They are different projects. That said, please open a new issue if you find any bugs.
