### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by lyanerzhang** [babel/babel#16153]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
// countComLoader.ts
const parser = require("@babel/parser")
const loaderUtils = require("loader-utils")
module.exports = function (source) {
   const ast = parser.parse(source, {
      sourceType: "module",
      plugins: ["jsx"]
    })
}
```
```
// vue.config.js
config.module
    .rule("vue")
    .use("countComLoader")
    .loader("./countComLoader.ts")
    .tap(options => {
      options = merge(options, {
        packageName: "chuxin-ui-mobile"
      })
      return options
    })
    .end()
```

### Current and expected behavior

自定义webpack loader中使用 `@babel/parser` 解析成AST时报错
希望可以解析成功，不报错，请教如何配置

### Environment

"@babel/parser": "^7.23.3",
"webpack": "^4.46.0"
"babel-eslint": "^10.1.0",
"babel-plugin-import": "^1.13.3",
"vue": "^3.2.13",

**Comment by lyanerzhang** [comment]
报错信息如下：
![image](https://github.com/babel/babel/assets/38914404/2b18dfaf-1347-40c9-956c-e4d50b48a234)

**Comment by liuxingbaoyu** [comment]
It looks like you are trying to parse a `.ts` file and you need to enable the `typescript` plugin.

```
// countComLoader.ts
const parser = require("@babel/parser")
const loaderUtils = require("loader-utils")
module.exports = function (source) {
   const ast = parser.parse(source, {
      sourceType: "module",
      plugins: ["jsx","typescript"]
    })
}
```

**Comment by lyanerzhang** [comment]
好的 我试一下

**Comment by lyanerzhang** [comment]
貌似还是一样的 @liuxingbaoyu 
![image](https://github.com/babel/babel/assets/38914404/9b0bbc58-f457-4187-a502-9b8c207b6e75)

**Comment by liuxingbaoyu** [comment]
Can you provide the code that is being parsed?

**Comment by lyanerzhang** [comment]
恐怕不可以提供，有点太多了

**Comment by liuxingbaoyu** [comment]
I will close this issue due to lack of required information for a long time.
