### ISSUE TITLE
[Bug]: Setting babelrc to false will skip the process of ignoreFile, is this a feature or bug?

### ISSUE THREAD

**Issue by HydratedPig** [babel/babel#16152]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[Demo with @babel/core@^7.23.5](https://github.com/HydratedPig/Demos/tree/babel-ignore)

Is this a `feature` or a `bug`?

### Current and expected behavior

The result I prefer is 
```
babelRunner1
ignore:
console.log('ignore');
main:
console.log('main');

babelRunner2
ignore:
console.log('ignore');
main:
console.log('main');
```
but the truth is 
```
babelRunner1
ignore:
ignore.js config is null
main:
console.log('main');

babelRunner2
ignore:
console.log('ignore');
main:
console.log('main');
```

### Environment

```sh
 System:
    OS: macOS 12.4
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    pnpm: 8.5.1 - ~/Library/pnpm/pnpm
  npmPackages:
    @babel/core: ^7.23.5 => 7.23.5 
```

### Possible solution

If it is a bug,  the reason maybe locale in [here](https://github.com/babel/babel/blob/380d186b77d32734c595652a40cbda5e4e109c5c/packages/babel-core/src/config/config-chain.ts#L212C2-L212C2). `ignoreFile` will not be processed when babelrc is not equal to false.

If it is a feature, just close the issue.

**Comment by JLHwung** [comment]
It is a feature. The `.babelignore` and `.babelrc` are both Babel 6 era legacy config files. When `babelrc` is `false`, the `.babelignore` will not be loaded, either. You can specify the `ignore` option in `babel.config.*`. We can clarify that in the docs.

**Comment by HydratedPig** [comment]
Got it. Thank you!
