### ISSUE TITLE
[Bug]: @babel/eslint-parser/experimental-worker hang when .babelrc located in directory

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#16163]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

Just trapped on interesting behavior, while linting markdown file with 🐊**Putout** one of my old repositories [coderaiser/itchy](https://github.com/coderaiser/itchy/tree/e4e6cc03f96893f271f9d73cc1dcdfc1d123c516), everything is hang, and the reason is ESLint with @babel/eslint-parser-experimental-worker and [`.babelrc`](https://github.com/coderaiser/itchy/blob/e4e6cc03f96893f271f9d73cc1dcdfc1d123c516/.babelrc).

Here is used config:
https://github.com/coderaiser/putout/blob/v33.13.4/packages/eslint-plugin-putout/lib/markdown.js#L43-L46

To reproduce clone repository [at the commit hash](https://github.com/coderaiser/itchy/tree/e4e6cc03f96893f271f9d73cc1dcdfc1d123c516) and run `node_modules/.bin/putout README.md`, at debugger you can find that ESLint [running](https://github.com/coderaiser/putout/blob/v33.13.4/packages/putout/lib/cli/process-file.js#L39) with provided config.

When I remove `.babelrc` (or disable experimental worker) the hang was fixed. Looks like some kind of conflict between babel configs 🤷‍♂️. It took some time to understand the reason of a process hang, so I share it, maybe it helps to fix it.

### Current and expected behavior

Expected not to hang

### Environment

Latest Babel

**Comment by liuxingbaoyu** [comment]
This is a very interesting problem.
I suspect the problem comes from nodejs' `worker_threads`.
When we throw an `await` error for the second time, `uncaughtException` will still be triggered even if `try` catches it.

**Comment by liuxingbaoyu** [comment]
This is caused by `@babel/core` and unfortunately I'm having trouble fixing it.
@nicolo-ribaudo @JLHwung 
Below is the simplest reproduction, if you have time you can take a look, thank you!
[babel-async-error.zip](https://github.com/babel/babel/files/13623253/babel-async-error.zip)

**Comment by nicolo-ribaudo** [comment]
Taking a look!
