### ISSUE TITLE
iisnode "homeOrTmp" Error

### ISSUE THREAD

**Issue by lancetw** [babel/babel#1616]
iisnode on Windows 2008 R2, 
already use v5.4.7, need helps.

``` cmd
Error: EPERM, operation not permitted 'C:\Windows\system32\config\systemprofile\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at save ([iisnode_webdir]\node_modules\babel-core\lib\babel\api\register\cache.js:30:19)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sebmck** [comment]
The error is coming from that module. Please report it to the [home-or-tmp repo](https://github.com/sindresorhus/home-or-tmp) instead. cc @sindresorhus.

**Comment by sindresorhus** [comment]
The module just uses the following environment variables: https://github.com/sindresorhus/user-home/blob/d9718785a6006b07abff6e97d2becb20cc59f34f/index.js#L7 or https://github.com/sindresorhus/os-tmpdir/blob/5c5d355f81378980db629d60128ad03e02b1c1e5/index.js#L10-L12 if not set. They should be writeable, if not, it's a problem with your system.

**Comment by lancetw** [comment]
Thanks @sindresorhus and @sebmck, finally I found a solution.
`process.env.USERPROFILE` returns `C:\Windows\system32\config\systemprofile` on my system.

According to below link, I must set IIS `loadUserProfile` to true.
It works now. :+1: 

ref: http://stackoverflow.com/questions/9490107/iis-7-5-application-pool-uses-wrong-appdata-for-custom-user-as-identity

**Comment by tp** [comment]
I had a similar problem with using Babel.js' `babel/register` on Windows Azure.

```
EventName="MessageEvent" Message="2015-06-26T09:47:08.451Z: EPERM, operation not permitted 'D:\Windows\system32\config\systemprofile\.babel.json'
Error: EPERM, operation not permitted 'D:\Windows\system32\config\systemprofile\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at save (C:\Resources\directory\d885c0fbef7c44f28b249bb7fff.nodeapp\1\node_modules\babel-core\lib\babel\api\register\cache.js:26:19)
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
errno = -4048
code = 'EPERM'
path = 'D:\\Windows\\system32\\config\\systemprofile\\.babel.json'
syscall = 'open'
version = 6.1.2 on Node.js v0.12.2
```
The fix for me was to disable the cache, using `process.env.BABEL_DISABLE_CACHE = 'true';` at the beginning of the `server.js` file.

Maybe there is a way for [the cache](https://github.com/babel/babel/blob/48d0df17d00b02a949ce423ad153f115ef40bbe6/src/babel/api/register/cache.js#L13) to check whether the file is readable or not?
