### ISSUE TITLE
regenerator with native let/const

### ISSUE THREAD

**Issue by PinkaminaDianePie** [babel/babel#1617]
regenerator with native let/const hoist them same as var (and they transpilled to var) on top of function, so when i tried to use native const/let in my async function they worked same as var. when i used babel's let/const they dont hoisted.

**Comment by sebmck** [comment]
I don't understand the issue. Please provide code examples and examples in the [REPL](http://babeljs.io/repl).

**Comment by PinkaminaDianePie** [comment]
original code:
```javascript
async function a(){
  for(let i=0; i<10; i++){
    console.log(i);
  }
  console.log(i);
}

a();
```
with babel's let everything is ok, after cycle i will be undefined
```bash
babel babel-test.js --stage=0
```
```javascript
"use strict";

function a() {
  var _i;

  return regeneratorRuntime.async(function a$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        for (_i = 0; _i < 10; _i++) {
          console.log(_i);
        }
        console.log(i);

      case 2:
      case "end":
        return context$1$0.stop();
    }
  }, null, this);
}

a();
```
with native let after cycle i will be 10
```bash
babel babel-test.js --stage=0 --blacklist=es6.blockScoping
```
```javascript
"use strict";

function a() {
  var i;
  return regeneratorRuntime.async(function a$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        for (i = 0; i < 10; i++) {
          console.log(i);
        }
        console.log(i);

      case 2:
      case "end":
        return context$1$0.stop();
    }
  }, null, this);
}

a();
```

same issue with native constants

**Comment by sebmck** [comment]
This is just a limitation of [regenerator](https://github.com/facebook/regenerator). Regenerator doesn't support any ES6 explosion of syntax. If you're in an environment that supports block scoped variables then you're in one that supports generators too and for those scenarios there are the optional [bluebirdCoroutines](http://babeljs.io/docs/usage/transformers/other/bluebird-coroutines/) and [asyncToGenerator](http://babeljs.io/docs/usage/transformers/other/async-to-generator/) transformers.
