### ISSUE TITLE
asyncToGenerator transformer always returns function with 0 length.

### ISSUE THREAD

**Issue by PinkaminaDianePie** [babel/babel#1618]
some frameworks (such as mocha) checks function length (parameters count), but if i used asyncToGenerator it transforms my code to
```javascript
before(_asyncToGenerator(function* (done) {
}));
```
where result of _asyncToGenerator will be babel's helper function:
```javascript
function () { var gen = fn.apply(this, arguments); 
```
it's length always 0.
need to transpile code to something like this:
```javascript
before(function(done) {
    _asyncToGenerator(function* (done) {
    }).apply(this, arguments);
});
```
then will be work fine.

**Comment by sebmck** [comment]
There's nothing that can be done about this. You can't mock or change a functions parameter length without explicitly specifying it and since the `asyncToGenerator` function is dynamic it's impossible.

**Comment by PinkaminaDianePie** [comment]
But you can wrap _asyncToGenerator with additional function with same params! At now you transpile 
```javascript
async function(params){}
```
to:
```javascript
_asyncToGenerator(function* (params) {});
```
but you can transpile it to:
```javascript
function(params) {
    _asyncToGenerator(function* (params) {}).apply(this, arguments);
}
```

**Comment by sebmck** [comment]
Want to send a PR?

**Comment by PinkaminaDianePie** [comment]
Sorry, i dont understand how babel works so i cant fix this issue =(

**Comment by PinkaminaDianePie** [comment]
so what about this issue? still closed with "cantfix" label? why my algorithm is wrong?

**Comment by sebmck** [comment]
As I said, happy to accept a PR. As for the timebeing, this is expected
behaviour.

On Friday, 29 May 2015, PinkaminaDianePie <notifications@github.com> wrote:

> so what about this issue? still closed with "cantfix" label? why my
> algorithm is wrong?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1618#issuecomment-106737029>.
>


-- 
Sebastian McKenzie

**Comment by PinkaminaDianePie** [comment]
if you want pr - change label to "help wanted" and reopen issue. with this "expected" behavior i cant use some libs such https://github.com/mochajs/mocha. very soon nodejs will be merged with iojs so there will be native generators + let + const, but i cant use them with this issue. i cant send you pr cause i dont know how babel works but maybe someone another can fixed it.

**Comment by PinkaminaDianePie** [comment]
still waiting for fixing this >_<

**Comment by sebmck** [comment]
Still waiting for a PR ;)

**Comment by PinkaminaDianePie** [comment]
but i will not do it. i dont want to waste week of time to understand how babel works just for fix, what can be done for 5 minutes by you. i tried to understand what the crap are going on in remap-async-to-generator.js, but understands nothing. just reopen this issue with "help wanted" label if you dont want do something with bugs, maybe someone another will fix it =\
