### ISSUE TITLE
[Bug]: decorators are broken and when applied, they override the preceding value.

### ISSUE THREAD

**Issue by amirmohsen** [babel/babel#16198]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

I've created a test repo with a basic example [here](https://github.com/amirmohsen/decorators-broken). You can also see it below:
```js
function decorateA(target) {
  return class extends target {
    a() {
      console.log("a");
    }
  };
}

function decorateB(target) {
  return class extends target {
    b() {
      console.log("b");
    }
  };
}

@decorateB
@decorateA
class Target {}

const target = new Target();

target.b();

target.a(); // This throws an error: TypeError: target.a is not a function
```
I only checked class decorators. This bug may exist for function decorators as well but I haven't checked.

### Configuration

```js
module.exports = (api) => {
  api.cache(true);
  return {
    presets: [
      [
        "@babel/preset-env",
        {
          modules: false,
          targets: {
            node: 20,
          },
        },
      ],
    ],
    plugins: [["@babel/plugin-proposal-decorators", { version: "2023-05" }]],
  };
};
```

### Current and expected behavior

Instead of passing the result of one decorator to the next, the original value of the `Target` class gets passed to each decorator and as a result, the last applied decorator result overrides the preceding ones.

### Environment

Babel package versions:
```json
"@babel/cli": "^7.23.4",
"@babel/core": "^7.23.7",
"@babel/plugin-proposal-decorators": "^7.23.7",
"@babel/preset-env": "^7.23.7",
```
Node: `20.9.0`
NPM: `10.1.0`
Yarn: `1.22.19`
Environment: `Ubuntu 20.04.4 LTS (WSL2 on Windows)`

### Additional context

This is a recent bug because I have a project that is using Babel version `7.23.2` and it's working fine. However, the bug doesn't seem to originate in Babel itself because simply reverting to an older version of the packages, doesn't fix anything. I think the problem might originate in a sub-dependency. I haven't had time to investigate further though.

**Comment by liuxingbaoyu** [comment]
Thank you for your report!
This is a regression for us, fixed in https://github.com/babel/babel/pull/16199.
