### ISSUE TITLE
$.g is undefined 

### ISSUE THREAD

**Issue by askaza** [babel/babel#1621]
Hi!
I have issue in FF and Chrome (both last versions):

`TypeError: $.g is undefined      
store = $.g[SHARED] || $.hide($.g, SHARED, {})[SHARED]; `

As I understood it's a part of core-js 
Windows 7
babel-runtime  5.4.7
babelify 6.0.2
react  0.13.3

Help me please, how could it be fixed?

**Comment by sebmck** [comment]
As you said yourself, this is not a problem with Babel and is in [core-js](https://github.com/zloirock/core-js) please report it there. cc @zloirock

**Comment by zloirock** [comment]
Show me reproducible example.
