### ISSUE TITLE
@babel/eslint-plugin: Support ESLint 9

### ISSUE THREAD

**Issue by brettz9** [babel/babel#16220]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

@babel/eslint-plugin reports an issue with ESLint 9 (alpha).

### Describe the solution you'd like

Review for ESLint 9 support and update @babel/eslint-plugin 's `peerDependencies` to indicate support.

### Describe alternatives you've considered

Ignore the warning

**Comment by fisker** [comment]
Need update `peerDependencies` for `@babel/eslint-parser` https://github.com/babel/babel/blob/f7a7715c896968a9e650d267cd7008b6daf8bfe5/eslint/babel-eslint-parser/package.json#L31

Blocking eslint-plugin-unicorn https://github.com/sindresorhus/eslint-plugin-unicorn/actions/runs/8579682135/job/23514924056?pr=2250#step:4:14

**Comment by nicolo-ribaudo** [comment]
ESLint 9 is now stable

**Comment by Pietervanhalem** [comment]
I cannot install the pre-release. Can someone help?

```bash
root@142809de69b9:/quasar-activitylog-admin# npm i @babel/eslint-parser@7.24.5-pre.1
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "condition:": condition:BABEL_8_BREAKING ? : 5.1.1-v1

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-08T12_37_03_930Z-debug-0.log
```


with package.json:

```json
{
  "name": "activitylog-admin",
  "version": "0.0.1",
  "description": "Activitylog Admin Interface",
  "productName": "Activitylog Admin",
  "author": "sawitree kalakul bloemendal",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"No test specified\" && exit 0",
    "dev": "quasar dev",
    "build": "quasar build",
    "upgrade": "ncu --upgrade; npm i; npm update"
  },
  "dependencies": {
    "@quasar/extras": "^1.16.11",
    "ajv": "^8.12.0",
    "axios": "^1.6.8",
    "core-js": "^3.36.1",
    "date-fns": "^3.6.0",
    "dotenv": "^16.4.5",
    "inflection": "^3.0.0",
    "json-editor": "^0.7.28",
    "json-editor-vue": "^0.13.0",
    "jsondiffpatch": "^0.6.0",
    "pinia": "^2.1.7",
    "pug": "^3.0.2",
    "pug-plain-loader": "^1.1.0",
    "quasar": "^2.15.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.24.1",
    "@quasar/app-webpack": "^3.12.4",
    "eslint": "^8.57.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-vue": "^9.24.0",
    "eslint-webpack-plugin": "^4.1.0"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 12.22.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}
```

System:
OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
Binaries:
Node: 18.19.1 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 10.2.4 - /usr/local/bin/npm
npmPackages:
@babel/eslint-parser: ^7.24.1 => 7.24.1
eslint: ^9.0.0 => 9.0.0

**Comment by nicolo-ribaudo** [comment]
Whoops, my mistake 😅 I'll re-publish.

**Comment by nicolo-ribaudo** [comment]
Can you try again with `@babel/eslint-parser@7.24.5-pre.2`? and `@babel/eslint-plugin@7.24.5-pre.1`.

**Comment by nicolo-ribaudo** [comment]
I can release later today

**Comment by newboy2006hosur** [comment]
We know it supports. But how to use it in `esling.config.mjs` file? There are no default exports here.
