### ISSUE TITLE
Please release Babel 8 with features from v7.23.9

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#16236]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Please release Babel 8 with features from [v7.23.9](https://github.com/babel/babel/releases/tag/v7.23.9).

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by nicolo-ribaudo** [comment]
Doing it now
