### ISSUE TITLE
[Bug]: @babel/eslint-parser@7.23.9 breaks linting with legacy decorators

### ISSUE THREAD

**Issue by andreyfel** [babel/babel#16239]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```js
import { tracked } from '@glimmer/tracking';

class State {
  @tracked depth = 0;
}
```

### Configuration

```js
module.exports = {
  root: true,
  parser: '@babel/eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    requireConfigFile: false,
    babelOptions: {
      plugins: [
        ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }],
      ],
    },
  },
}
```

### Current and expected behavior

Expected eslint to run without issues.
Actual: `error  'tracked' is defined but never used  no-unused-vars`

Reverting `@babel/eslint-parser` to 7.23.3 fixes the issue.

Here is a reference repository (pretty small ember addon) https://github.com/retailnext/ember-bem-helpers/pull/195 https://github.com/retailnext/ember-bem-helpers/actions/runs/7668263539/job/20899739663

### Environment

babel@7.23.9, Node@18

**Comment by nicolo-ribaudo** [comment]
I'm releasing the fix.
