### ISSUE TITLE
Provide the way to add plugin without creating a separate NPM package

### ISSUE THREAD

**Issue by inikulin** [babel/babel#1623]
It would be cool to have possibility to add plugin to Babel without creating a new NPM package.
E.g.:

```js
var myAwesomePlugin = function (babel) {
  return new babel.Transformer("foo-bar", {
    // visitors
  });
};

require("babel").transform("code", {
  plugins: [myAwesomePlugin]
});
```
I can issue a PR if you are OK with this approach.

**Comment by sebmck** [comment]
You already can.

**Comment by inikulin** [comment]
Oh, I did not find this in the [docs](https://babeljs.io/docs/usage/plugins/).

**Comment by sebmck** [comment]
Yeah, need to work on the docs a lot. There's a lot missing but I'm still trying to figure out best patterns before I open up the internals more.
