### ISSUE TITLE
[Slack]: Link broken again

### ISSUE THREAD

**Issue by robertalv** [babel/babel#16230]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

na

### Configuration

na

### Current and expected behavior

na

### Environment

na

### Possible solution

na

### Additional context

This link is no longer active trying to join the Slack.

Could I please get an invite to slack please?

**Comment by nicolo-ribaudo** [comment]
Finally fixed, thanks!

**Comment by nicolo-ribaudo** [comment]
Mh it still seems to be broken

**Comment by nicolo-ribaudo** [comment]
@JLHwung babel-slack-invite-link.netlify.app works, and slack.babeljs.io is setup to redirect to it:
![image](https://github.com/babel/babel/assets/7000710/1333354f-2d26-416d-a602-38c7724fb019)

However, slack.babeljs.io still brings me to the old one :thinking:

**Comment by nicolo-ribaudo** [comment]
I now tried disabling cloudflare's proxy and I'll check later if it works

**Comment by nicolo-ribaudo** [comment]
It works

**Comment by robertalv** [comment]
Works thank you.
