### ISSUE TITLE
Request for Compilation Option to Avoid Reflect.construct in Babel Transpilation

### ISSUE THREAD

**Issue by Cola-Zhang** [babel/babel#16246]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I am facing performance issues in a JavaScript game I am developing due to the use of Reflect.construct for object creation when transpiling ES6 to ES5 with Babel. The method's performance overhead is causing low frame rates when a large number of objects are created, which is critical in a gaming context.

### Describe the solution you'd like

I would like Babel to provide a compilation option that allows for ES6 to ES5 class transformation without using Reflect.construct. This option should enable a more performant alternative for object instantiation that aligns with the need for high-efficiency execution in applications like games, where rapid object creation is a common scenario.

### Describe alternatives you've considered

As an alternative, I have manually modified the construct and isNativeReflectConstruct methods in @babel/helpers/lib/helpers-generated.js to bypass the use of Reflect.construct. While this approach works, it is not maintainable or scalable. Additionally, the loose mode is not a viable alternative due to compatibility issues it introduces with the complex class libraries used in my project. Therefore, a supported compilation option within Babel's official configuration would be the ideal solution.

**Comment by liuxingbaoyu** [comment]
I'm surprised that `Reflect.construct` makes a noticeable performance difference.
In this case I recommend you use `patch-package` to patch `isNativeReflectConstruct`, it should rarely change.

**Comment by Cola-Zhang** [comment]
> I'm surprised that `Reflect.construct` makes a noticeable performance difference. In this case I recommend you use `patch-package` to patch `isNativeReflectConstruct`, it should rarely change.

Indeed, that's exactly what I did.

**Comment by Cola-Zhang** [comment]
> I'm surprised that `Reflect.construct` makes a noticeable performance difference. In this case I recommend you use `patch-package` to patch `isNativeReflectConstruct`, it should rarely change.

Indeed, that's exactly what I did. Thanks
