### ISSUE TITLE
Missing newlines at end of file

### ISSUE THREAD

**Issue by timkurvers** [babel/babel#1624]
When migrating a codebase from CoffeeScript to ES6/ES2015 I noticed Babel does not enforce end of file newlines. It also seems to discard any that may be present in the source files.

![screen shot 2015-05-25 at 21 30 15](https://cloud.githubusercontent.com/assets/378235/7801488/82a1dab0-0325-11e5-9d76-5cce4352954e.png)

Is this an oversight or a conscious decision? Hope this is the right place to report.

**Comment by sebmck** [comment]
> Is this an oversight or a conscious decision?

Why does it have to be either?

If there was a trailing whitespace then someone may not want it and I'd get this exact same issue requesting that it not be added :stuck_out_tongue_winking_eye: It's pretty simple to add the additional trailing newline yourself so unsure what you're asking exactly?

**Comment by timkurvers** [comment]
I see. How would I go about adding these as part of the compile process though? At present Babel seems to discard any explicit EOF newlines present in the source files.

**Comment by jgorset** [comment]
I think most developers prefer a trailing newline (which is why git highlights it as a bad thing).

**Comment by sebmck** [comment]
@timkurvers Depends on your build system, unsure to your setup so I can't recommend anything.

@jgorset Regardless of the preference, this couldn't be done until a major verison anyway since it will break tests since a newline will have randomly appeared on the end of their comparison string. Git is a pretty bad example since checking your compiled code into git is arguably far worse than missing trailing newlines.

**Comment by jgorset** [comment]
Sure; I'm not advocating checking the compiled code into version control, but rather that it's a good indicator of preference. Either way I don't feel strongly about it, but I guess you can consider us at least two :+1: for trailing newlines in the next major version. ;-)

**Comment by jgorset** [comment]
In the mean time, thanks for Babel! It's pretty rad.

**Comment by timkurvers** [comment]
@sebmck: Thanks, I'll ignore the warnings for now, not a biggie. The main reason I (sometimes) do check in compiled code, is to allow direct usage from - say - GitHub.

I understand the dilemma in having to support those who do want EOF newlines and those who do not. Having Babel respect the source file in the future would be a lovely addition.

**Comment by sebmck** [comment]
No problem! :smile: Thanks for the discussion guys. I'll close this and mark it as revisit for the next major. Thanks again!
