### ISSUE TITLE
[Bug]: compat-data for transform-parameters ios version looks like not correct

### ISSUE THREAD

**Issue by JiangWeixian** [babel/babel#16254]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

https://github.com/babel/babel/blob/08a057c169f0b92ad3797aea9214a4428ced1a9f/packages/babel-compat-data/data/plugins.json#L298

It requires `safari_ios` > `16.3`, but in `caniuse`, this version is support function rest parameters

![image](https://github.com/babel/babel/assets/6839576/be05a3d5-06f1-4f89-a561-09a8da7c818c)

### Current and expected behavior

I use swc-loader transform code, but it use compat-data.json from babel.

### Environment

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.10.5

**Comment by liuxingbaoyu** [comment]
This is introduced at https://github.com/babel/babel/pull/13842, and the related compatibility data is https://github.com/compat-table/compat-table/blob/1a1ccdc02b8b2158ab39a6146d8a7308f43c830b/data-es6.js #L16866-L16910.
I don't quite understand the context here, maybe other members might have an idea.

**Comment by JLHwung** [comment]
The compat-data we use is from https://github.com/kangax/compat-table, it is more granular than caniuse.

The Safari < 16.3 is affected by a bug https://bugs.webkit.org/show_bug.cgi?id=220517, where Safari will throw on such code:

```js
let b = function a({ test: a }) { console.log(a); };
```

Please enable the https://swc.rs/docs/configuration/compilation#envbugfixes option. If this option is _not_ enabled, Babel will transform parameters even if your source code may not be affected by this bug. I believe swc will behave the same.

**Comment by JiangWeixian** [comment]
@JLHwung thanks
