### ISSUE TITLE
[Bug]: should parse `type A = import("mod", { with: { type: "json" }});`

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#16276]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
type A = import("foo", {with: {type: "json"}})
```

### Configuration

N/A

### Current and expected behavior

**Current:**

```
SyntaxError: Unexpected token, expected ")"
```

**Expected:**

Success

### Environment

```js
const { parse } = require("@babel/parser"); // 7.23.9

const code = `type A = import("foo", { with: { type: "json"} }});`;
const result = parse(code, { plugins: ["typescript", "importAttributes" ]});
```

### Possible solution

Fix the parser

### Additional context

context: https://github.com/prettier/prettier/issues/16072

TypeScript compiler can parse it([Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UCWBbMB7ATsAFAIgDN108AaKAbwHclgALALktEibwCsBndAOzwF9+ASgBQQA))

**Comment by fisker** [comment]
After I merge https://github.com/prettier/prettier/pull/16130, I realized that there should be a update for `visitorKeys` expected, is it missing?
