### ISSUE TITLE
[Bug]: @babel/preset-env not including plugins for shippedProposals

### ISSUE THREAD

**Issue by arasmussen** [babel/babel#16282]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I created a very simple repo here: https://github.com/arasmussen/babel-repro

### Configuration

```js
const path = require("path");

const webpack = require("webpack");
const TerserJSPlugin = require("terser-webpack-plugin");

const WebpackConfig = {
  entry: {
    app: "./index.js",
  },

  mode: "production",

  module: {
    rules: [
      {
        test: /\.(ts|tsx|js)$/,
        include: [__dirname],
        use: [
          {
            loader: "babel-loader",
            options: {
              presets: [
                [
                  "@babel/preset-env",
                  {
                    bugfixes: true,
                    corejs: "3.36",
                    debug: true,
                    loose: true,
                    shippedProposals: true,
                    useBuiltIns: "usage",
                  },
                ],
              ],
            },
          },
        ],
      },
    ],
  },

  output: {
    filename: "[name].js",
    path: path.resolve(`${__dirname}/build`),
    publicPath: "https://example.com",
  },
};

module.exports = WebpackConfig;
```

### Current and expected behavior

Source file:
```js
class Foo {
  property = true;
}
```

Current behavior:
```
ERROR in ./index.js 2:11
Module parse failed: Unexpected token (2:11)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| class Foo {
>   property = true;
| }
```

Expected behavior:
- code compiles with no issue
  - using @babel/preset-env and shippedProposals: true so class properties should be loaded with no issue

### Environment

- Babel version: 7.23.9
- Node version: 18.17.0
- npm version: 9.8.1
- OS: 13.0
- webpack version: 4.47.0

### Possible solution

I found https://github.com/babel/babel/issues/11796 which seems very similar. Except that was an issue with how @babel/preset-env was being included/configured. I seem to be configuring it properly.

The docs for `@babel/plugin-transform-class-properties` say that `This plugin is included in @babel/preset-env, in ES2022`.

This is my list of targets that .browserslistrc compiles to:

```json
{
  "android": "120",
  "chrome": "109",
  "edge": "120",
  "firefox": "115",
  "ios": "15.6",
  "opera": "105",
  "opera_mobile": "73",
  "safari": "16.6",
  "samsung": "22"
}
```

All of these browsers appear to support ES2022. Any help would be greatly appreciated, thank you.

**Comment by arasmussen** [comment]
Even if I tighten the `.browserslistrc` all the way to just `chrome > 120` the issue still happens.

**Comment by nicolo-ribaudo** [comment]
All your targets support class fields, so Babel is _not_ compiling them. Then, you are using an old version of webpack that throws when it sees class fields. I suggest either updating webpack, or changing your targets to that Babel compiles class fields.

I'd like to support using webpack as a target to compute which features to compile in the future, but we don't support it yet: https://github.com/babel/babel/issues/14963

**Comment by arasmussen** [comment]
So helpful, thank you @nicolo-ribaudo! Going to close this out.
