### ISSUE TITLE
Support proposal-explicit-resource-management DisposableStack

### ISSUE THREAD

**Issue by yf-yang** [babel/babel#16290]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

@babel/plugin-proposal-explicit-resource-management does not support DisposableStack yet

https://github.com/tc39/proposal-explicit-resource-management#the-disposablestack-and-asyncdisposablestack-container-objects

### Describe the solution you'd like

Implement the class.

### Describe alternatives you've considered

Nope

**Comment by liuxingbaoyu** [comment]
Have you tried `core-js` or `es-shims`, this class should be implemented by polyfills.
It looks like they are already working with babel. (Not tested, just guessing)

**Comment by yf-yang** [comment]
Yep, core-js works fine, thanks.

`core-js` should be installed.
``` json
[
    "@babel/preset-env",
    {
      ...,
      "useBuiltIns": "usage",
      "corejs": {"version": "3.36", "proposals": true}
    }
  ]
```
