### ISSUE TITLE
[Bug]: decorator on symbol-keyed member throws error at evaluation time

### ISSUE THREAD

**Issue by tbroyer** [babel/babel#16292]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function decorator(target, context) {
  console.log(context.name);
};

const FOO = Symbol();

class Test {
    @decorator accessor #foo = 42;
  
    @decorator accessor ["computed"] = 42;

    @decorator accessor [FOO] = 42;
}
```

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAEwKYTgJwIZSwCim0wHNUoAaRDMKVADygEpEBvAKEWoQGc4AbVADp-cEvhp1GQsNgC2qJgG52AXxXsaPKIgBiAeX2IAvIgDKATzkAjAfmXtN_bDx6IAKqm1tOXRAAE0DBw8TERsCAgvPjCAYmA4OBNEABYAJhUuXy5A9CxcLHDI6MKAbQAiDDkABxA6ZHKAXWT0jT8AoPzQoqjXMoN9ZtNWtSA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.10&externalPlugins=&assumptions=%7B%7D)

Try commenting out each property.

### Current and expected behavior

Generated code throws error `Cannot convert a Symbol value to a string` at line https://github.com/babel/babel/blob/bf3d314880f48d3cbe99dcb08eeb1e742b9b67dc/packages/babel-helpers/src/helpers/applyDecs2305.ts#L499

### Environment

  System:
    OS: Linux 6.7 Arch Linux
  Binaries:
    Node: 20.11.1 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.4.0 - /usr/bin/npm
    pnpm: 8.6.0 - /usr/bin/pnpm

### Possible solution

The concatenation is used as a key in a `Map`, and the property name is concatenated with a boolean, so it could be possible to use two maps instead of one (one map for the static members, one for the non-static members) directly keyed by the property name (either a string or a symbol)

### Additional context

I encountered this while migrating a [Lit](https://lit.dev) element from `static properties` to using decorators through Babel; with `static properties` I couldn't use a private property (as the property from the `static properties` object value has to match a property in the enclosing class) so I had used a symbol (I could also have used any mangled, non-conflicting, name); I could migrate to using a private property with decorators but unfortunately Lit decorators don't seem to work with those, so in the mean time I can use a non-conflicting name (e.g. `_`-prefixed), so at least I have a workaround.

**Comment by liuxingbaoyu** [comment]
Thank you for your report!
This has been fixed at https://github.com/babel/babel/pull/16270.
Expected to be released at v7.24.0.
