### ISSUE TITLE
[Bug]: BABEL_PARSE_ERROR regarding duplicate function definitions

### ISSUE THREAD

**Issue by Roise-yue** [babel/babel#16303]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

function* countDown(begin) {
    while (begin >= 0) {
        yield begin--;
    }
}
var begin;
function* func1() {
    yield 'aha';
    yield 'ihi';
    yield 'uhu';
}
for (const e of func1())
    for (const e of countDown(10)) {
        console.log(e);
    }
function* countDown(begin) {
    while (begin >= 0) {
        yield begin--;
    }
}
for (const e of countDown(10)) {
    console.log(e);

}

### Configuration file name

.babelrc

### Configuration

{
  "presets": ["@babel/preset-env"],
  "plugins": []
}

### Current and expected behavior

I am using babel to run the code,and here is the error reported:Syntax error,Identifier "CountDown" has already been declared.
 To my knowledge, in JavaScript, when a function is declared repeatedly, the function declaration defined later will overwrite the previous function declaration. Therefore, I believe that the code I provided is grammatically compliant, but Babel refuses to translate this code. Is this because Babel believes there is a syntax error in this code? Please explain this issue to me, thank you

### Environment

Babel:v7.23.9
node.js : v21.6.1
npm: v10.2.4
Ubuntu: v20.04

**Comment by liuxingbaoyu** [comment]
Please check if the source type is set to `module`.
[repl](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mAVAAgncUAicDuYAUARgKYDmMYAlMgN4BQOAFjADbHJFkXIB8AvMgAM1egE8YxFgBNkJcmAC0CgN x0AvuroA3AIYAnWVzCrQkWAhSmIARnwi64yTIDkOxjuerH05M5jNPBwkfZxBGEECNYDgDfDQwAGcoZHY4YGQrW0pKOmjY-KSU5DTUdDAsXAJrYXsCuDYAOhY4UnxiSlUo8Gh4JFKMbDxOeXsmVnZh7n4 he28ZOQolTs08jgLk1PS0Acr8auzaOjrG5tb21XUgA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets= typescript&prettier=false&targets=&version=7.23.10&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.23.9&assumptions=%7B%7D)

**Comment by Roise-yue** [comment]
> Please check if the source code type is set to `module`, duplicate declarations are not allowed in strict mode. [repl](https://babeljs.io/repl#?browsers=&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mAVAAgncUAicDuYAUARgKYDmMYAlMgN4BQOAFjADbHJFkXIB8AvMgAM1egE8YxFgBNkJcmAC0CgNx0AvuroA3AIYAnWVzCrQkWAhSmIARnwi64yTIDkOxjuerH05M5jNPBwkfZxBGEECNYDgDfDQwAGcoZHY4YGQrW0pKOmjY-KSU5DTUdDAsXAJrYXsCuDYAOhY4UnxiSlUo8Gh4JFKMbDxOeXsmVnZh7n4he28ZOQolTs08jgLk1PS0Acr8auzaOjrG5tb21XUgA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.23.10&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.23.9&assumptions=%7B%7D)

Thank you for your answer. After checking, I found that the code is not in strict mode, maybe there are other reasons.

**Comment by liuxingbaoyu** [comment]
Since there has been no response for a long time I will close this issue.
