### ISSUE TITLE
[Bug]: Invalid Slack link in README file

### ISSUE THREAD

**Issue by shilgapira** [babel/babel#16308]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Current and expected behavior

I expect to be able to join the Slack community if it's listed in the README

### Additional context

<img width="400" src="https://github.com/babel/babel/assets/694968/5f570e4b-79d2-4651-a05e-29f25a59f9ec">

**Comment by nicolo-ribaudo** [comment]
Thanks, I'm looking into it.

**Comment by nicolo-ribaudo** [comment]
I updated it with one set to not expire, it will probably take 10-15 minutes to properly redirect.

https://github.com/babel/slack-invite-link/commit/46b100a4d02f1b1b31d6d564f02953aa64d1bdd4
