### ISSUE TITLE
Translation error with rest parameters and arrow function

### ISSUE THREAD

**Issue by stbix** [babel/babel#1631]
```javascript
function demo1(...args) {
    return (i) => {
        return args[i+0];
    };
}
```
is incorrectly translated into
```javascript
function demo1() {
    return function (i) {
        return arguments[i + 0 + 0];
    };
}
```
The problem is that `arguments` refers to the arguments of the inner function instead of the outer function. Small modifications result in correct translations:
```javascript
function demo2(...args) {
    return (i) => {
        return args[i];
    };
}
```
and
```javascript
function demo3(...args) {
    return function (i) {
        return args[i+0];
    };
}
```
are both translated correctly. I tried this on babeljs.io/repl and on the command line with version 5.4.7 and a few others.

**Comment by sebmck** [comment]
Yeah, it's to do with the static member expression optimisation.

**Comment by stbix** [comment]
Thank you, Sebastian.
