### ISSUE TITLE
[Feature request] Provide multiple transformers from plugins

### ISSUE THREAD

**Issue by ooflorent** [babel/babel#1632]
Something I would like to see in Babel is the ability to provide multiple transformers from a plugin. Current implementation requires the plugin to export a transformer sharing its name (`babel-plugin-foo` must export `foo` transformer). It would be great if it could export multiple transformers sharing its name through a namespace (`babel-plugin-foo` could export `foo.bar` and `foo.baz`).

**Comment by sebmck** [comment]
We've discussed this before in gitter. It doesn't make sense to have multiple transformers available a plugin because a plugin is fundamentally a single transformer.
