### ISSUE TITLE
[Bug]: sourceCode.getScope is not a function (`@babel/eslint-plugin`)

### ISSUE THREAD

**Issue by 01taylop** [babel/babel#16340]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
// na
```

### Current and expected behavior

This issue is concerning `eslint` and `@babel/eslint-plugin`.

When upgrading ESLint to `8.37.0`, the following lint error can be observed. When using `8.36.0` linting works as expected.

```
sourceCode.getScope is not a function
Occurred while linting /Users/username/folder/index.js:1
Rule: "@babel/no-invalid-this"
```

[Release notes for `8.37.0`](https://github.com/eslint/eslint/releases/tag/v8.37.0)

I suspect the cause of the issue could be [`feat: Copy getScope() to SourceCode`](https://github.com/eslint/eslint/pull/17004).

### Environment

package.json
```
"@babel/core": "7.24.0",
"@babel/eslint-parser": "7.23.10",
"@babel/eslint-plugin": "7.23.5",
"@babel/preset-react": "7.23.3",
"eslint": "8.37.0",
```

.eslintrc
```
{
  "rules": {
    "new-cap": 0,
    "@babel/new-cap": 2,
      
    "no-invalid-this": 0,
    "@babel/no-invalid-this": 2,
      
    "no-unused-expressions": 0,
    "@babel/no-unused-expressions": 2,
      
    "object-curly-spacing": 0,
    "@babel/object-curly-spacing": [2, "always"],
      
    "semi": 0,
    "@babel/semi": [2, "never"],
  },
  "plugins": [
    "@babel"
  ]
}
```

**Comment by JLHwung** [comment]
When using with ESLint 8, `@babel/no-invalid-this` delegates the rule to ESLint's built-in `no-invalid-this` rule since ESLint 8 supports class properties well:

https://github.com/babel/babel/blob/5ca9b9a84f5f06d16704c53717c9baae2b347839/eslint/babel-eslint-plugin/src/rules/no-invalid-this.cjs#L7-L11

You can try to remove the `@babel/no-invalid-this` rule and use `no-invalid-this`. If there error persists, that would be more like an ESLint regression.

**Comment by nicolo-ribaudo** [comment]
Do you have a repo we can clone to reproduce the error?

**Comment by 01taylop** [comment]
I found the issue I was having; multiple versions of eslint in my dependencies. I am using `gulp` and `gulp-eslint-new` which pulls in an older version of eslint 8. Setting the `resolutions` resolved the issue. Will close the issue.

```package.json
"resolutions": {
  "eslint": "8.57.0"
},
"dependencies": {
  "eslint": "8.57.0",
```
