### ISSUE TITLE
Better error message for non-iterable arguments passed to Set and Map

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#1635]
Right now if I pass a non-iterable argument to `Set` I get following error:

```
→ new Set({})
→ Uncaught TypeError: Cannot read property 'call' of undefined
```

V8 throws this error:

```
Uncaught TypeError: Set is not a function
    at new Set (native)
    at <anonymous>:2:5
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

Firefox does better:

```
new Set({})
TypeError: ({}) is not iterable
```

I think Firefox' error message is more clear and Babel polyfill should throw the same kind of error 

**Edit**: this also applies to `Map`.

**Comment by zloirock** [comment]
Please, next time open similar issues in [`core-js` repo](https://github.com/zloirock/core-js).

**Comment by mohsen1** [comment]
Is this a valid issue? Do you want me to move it there? BTW you guys can start using [github-issue-mover](https://github.com/google/github-issue-mover)

**Comment by zloirock** [comment]
@mohsen1 I've seen this issue - it's enough, but, please, next time open similar issues in correct place.

**Comment by mohsen1** [comment]
The way you're handling issues is very discouraging. I'm not sure if I will open the next issue if I find one. You close the issue before fixing it (Although it's still an issue in Babel since it's not merged in Babel yet). You're also expecting end users to know about all the internals before opening an issue. This is very common that end users open issues in user facing/wrapper product and open issue in that project. That's the very reason github-issue-mover exists.

I maintain [Swagger Editor](https://github.com/swagger-api/swagger-editor) and it's wrapping many different modules that end-users are not aware of. If they open an issue in Swagger Editor because code-gen is not working, I will comment on the issue to let them know and keep the issue open until upstream is fixed.

**Comment by zloirock** [comment]
@mohsen1 I close issue before fixing as it's invalid repo. This is not a bug or major enhancement and not required mention even in changelog. Something else?
