### ISSUE TITLE
[Bug]: TypeScript parser does not set typeParameters for CallExpression

### ISSUE THREAD

**Issue by gdbd** [babel/babel#16389]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

``` 
const babel = require("@babel/core");

const result = babel.transformSync(
  `
    someFunction<TSomeType>();
`,
  {
    parserOpts: { plugins: ["typescript"] },
    plugins: ["@babel/plugin-transform-typescript"],
    ast: true,
  },
);

```

### Configuration

```
 {
    parserOpts: { plugins: ["typescript"] },
    plugins: ["@babel/plugin-transform-typescript"],
    ast: true,
  }
```

### Current and expected behavior

expected: ```result.ast.program.body[0].expression.typeParameters !== null```

actual:       ```result.ast.program.body[0].expression.typeParameters === null```

### Environment

- babel: 7.24.0
- node.js: 21
- yarn: 1.22.21
- OS: linux 6.7

### Additional context

reproduce repository: https://github.com/gdbd/babel-test

to start:
1) clone
2) `yarn install`
3) yarn run 'transform-test'
4) yarn run 'plugin-test'

look in the output:
at step 3: 
![image](https://github.com/babel/babel/assets/5655858/c1a94adf-4735-480c-9be5-d313e94966a1)

at step 4:
![image](https://github.com/babel/babel/assets/5655858/6e2e9726-9f08-4851-b47d-5dce60648aef)

So, `typeParameters` is not avalibale directly via `CallExpression` but availbale whwn it accesses through it parents.

Same time, AST explorer works as expected:
![2024-03-28_18-50](https://github.com/babel/babel/assets/5655858/a00f94a5-2411-4b97-9122-9d348807fd35)

**Comment by JLHwung** [comment]
```diff
{
    parserOpts: { plugins: ["typescript"] },
-    plugins: ["@babel/plugin-transform-typescript"],
    ast: true,
  }
```
Please remove the typescript transform if you are to inspect the AST, since the transform will remove any typescript type notations.

**Comment by gdbd** [comment]
@JLHwung  thank you, problem is solved!
