### ISSUE TITLE
Spread operator syntax error

### ISSUE THREAD

**Issue by super-cache-money** [babel/babel#1638]
The following snippet throws an Unexpected Token error, at `...`:

    var {
      tooltip,
      touch,
      ...other } = this.props;

I'm applying the transformer thusly: 

    require("babel/register")({});

Weirdly, when running the transformer from the command line, it works perfectly. 
For what it's worth, the snippet above is required from a **jsx** syntax file.

What's likely to be the case here?

**Comment by loganfsmyth** [comment]
Object spreads are an experimental ES7 feature. You need to enable them.

    require("babel/register")({
        optional: ['es7.objectRestSpread']
    });
