### ISSUE TITLE
`@babel/plugin-transform-typescript` turn `const enum`s into `const` variables

### ISSUE THREAD

**Issue by samualtnorman** [babel/babel#16380]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

`@babel/plugin-transform-typescript` currently turns `const enum`s into `var Foo = { Bar: 0, Baz: 1 }` but I'd like it if it instead produced `const` variables

### Describe the solution you'd like

either the `t.variableDeclaration("var", ...` line is changed to `t.variableDeclaration("const", ...` or a new option is added like `optimizeConstEnumsUseConstVariable` or something

### Describe alternatives you've considered

if the variable really needs to be mutable or something, I wouldn't mind `let`

**Comment by nicolo-ribaudo** [comment]
TS also compiles them to `var` (in `isolatedModules` mode): https://www.typescriptlang.org/play?isolatedModules=true#code/MYewdgzgLgBApmArgWxgMRCGBvAUDGADxgF4YAmXAX1yA

`var` generally tends to be faster than `const` (it requires less checks). Do you have any example of valid TS code where `var`vs`const` causes an observable difference?

**Comment by samualtnorman** [comment]
> TS also compiles them to `var` (in `isolatedModules` mode): https://www.typescriptlang.org/play?isolatedModules=true#code/MYewdgzgLgBApmArgWxgMRCGBvAUDGADxgF4YAmXAX1yA
I should have been clearer in my issue, I meant when you're using `optimizeConstEnums: true`:
```ts
const enum Foo { Bar }
```
->
```js
var Foo = { Bar: 0 }
```

trying to reassign the `const enum` gives you `Cannot assign to 'Foo' because it is an enum. (2628)`

**Comment by samualtnorman** [comment]
If no one has any objections, I can go ahead and create a pull request.

**Comment by nicolo-ribaudo** [comment]
I would prefer to just use `const` rather than `var` — an option for this seems overkill.

However, this would then be a breaking change: we can ship this in Babel 8 (which is currently in alpha). If you want to open a PR, look for `BABEL_8_BREAKING` both in our sources and test fixtures to see how to introduce a Babel-8-only change.
