### ISSUE TITLE
Arguments of arrow function

### ISSUE THREAD

**Issue by vtambourine** [babel/babel#1641]
Recently I've found quite confusing situation with arrow functions. Consider following example:
```js
var props = {
    name: () => {
        return PropTypes.string.apply(null, arguments);
    }
}
``` 
Here I want to simple call some core library function behind the facade of some other function. I expect arrow to be simple shorthand to `function`, since I don't care about `this`. So, I expect compiled code to be:
```js
var props = {
    name: function name() {
        return PropTypes.string.apply(null, arguments);
    }
}
``` 
However, I have compiler breaks my code by substitution of `arguments`:
```js
var _arguments = arguments;
var props = {
    name: function name() {
        return PropTypes.apply(null, _arguments); // _arguments is undefined here
    }
};
```
Is that expected behaviour? Can you, please, explain logic behind this?

Babel version is 5.4.7.

**Comment by sebmck** [comment]
See the [FAQ](http://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-).
