### ISSUE TITLE
better to keep tranformed code's line number same with original code

### ISSUE THREAD

**Issue by yiminghe** [babel/babel#1642]
It's useful to visualize test coverage, as browser runs transformed code, but we need to highlight uncovered lines on original source code.

jstransform does this well, but it does not support much es6 features....

for example source code:
```js
var {x,y}=require('z')
var a = 1;
```

jstransform:  
```js
var $__0=  require('z'),x=$__0.x,y=$__0.y;
var a = 1;
```

babel:
```js
'use strict';

var _require = require('z');

var x = _require.x;
var y = _require.y;
var a = 1;
```

**Comment by sebmck** [comment]
See the [options docs](http://babeljs.io/docs/usage/options/). There's a `retainLines` option that you can use that generates disgusting code but keeps the line numbers.

**Comment by yiminghe** [comment]
thanks, my mistake
