### ISSUE TITLE
[Bug]: Cannot find package '@babel/plugin-preset-env' imported

### ISSUE THREAD

**Issue by msidolphin** [babel/babel#16434]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
{
  test: /\.tsx?$/,
  exclude: /node_modules/,
  use: [
  {
    loader: "babel-loader",
    options: {
      plugins: [
        ["@babel/plugin-transform-runtime", {
          "corejs": 3
        }],
        [
          "@babel/preset-env"
        ]
      ]
    }
  },
```

### Configuration
```js
{
    plugins: [
      ["@babel/plugin-transform-runtime", {
        "corejs": 3
      }],
      [
        "@babel/preset-env"
      ]
    ]
  }
```
### Current and expected behavior

Why do I configure @babel/preset-env but keep getting a message that the '@babel/plugin-preset-env' package imported from xxx/build/babel-virtual-resolve-base.js cannot be found?

### Environment

System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 10.4.0 - ~/.npm-global/bin/npm
    pnpm: 8.8.0 - ~/.npm-global/bin/pnpm
  npmPackages:
    @babel/core: ^7.24.4 => 7.24.4 
    @babel/plugin-transform-runtime: ^7.24.3 => 7.24.3 
    @babel/preset-env: ^7.24.4 => 7.24.4 
    @babel/runtime-corejs3: ^7.24.4 => 7.24.4 
    babel-loader: ^9.1.3 => 9.1.3

**Comment by msidolphin** [comment]
<img width="1333" alt="image" src="https://github.com/babel/babel/assets/26672484/f9de3cb2-a26c-492f-8039-fc765dac05b1">
<img width="1305" alt="image" src="https://github.com/babel/babel/assets/26672484/58d25d92-a94a-40de-88d2-247fe9a210a5">

It looks like the babel-loader automatically adds the plugin keyword

**Comment by nicolo-ribaudo** [comment]
You should move it to the `presets` array :)
