### ISSUE TITLE
[Bug]:  Fragment child elements are not transformed correctly when using @babel/plugin-transform-react-constant-elements

### ISSUE THREAD

**Issue by mo36924** [babel/babel#16449]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const a = () => <><div>a</div></>
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "parserOpts": {
    "plugins": ["jsx"]
  },
  "presets": [],
  "plugins": ["@babel/plugin-transform-react-constant-elements"]
}
```

### Current and expected behavior

Expected:
```js
var _div;
const a = () => <>{_div || (_div = <div>a</div>)}</>;
```
or
```js
var _Fragment;;
const a = () => _Fragment || (_Fragment = <><div>a</div></>);
```

Received:
```js
var _div;
const a = () => <>_div || (_div = <div>a</div>)</>;
```

### Environment

-  System:
    OS: macOS 14.4.1
-  Binaries:
    Node: 20.11.1 - ~/.proto/shims/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 10.2.4 - ~/.proto/shims/npm
    bun: 1.0.29 - ~/.proto/shims/bun
-  npmPackages:
    @babel/plugin-transform-react-constant-elements: ^7.24.1 => 7.24.1 
    @babel/preset-typescript: ^7.24.1 => 7.24.1 

### Possible solution

https://github.com/babel/babel/blob/e779cad081d47bd6a91302e274dbb93f08bd1d51/packages/babel-plugin-transform-react-constant-elements/src/index.ts#L245-L250

Although the entire fragment cannot be made constant, the transformation of child elements works fine using the code below.
```js
if (
  path.parentPath.isJSXFragment() ||
  path.parentPath.isJSXElement() ||
  path.parentPath.isJSXAttribute()
) {
  replacement = t.jsxExpressionContainer(replacement);
}
```

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR with that proposed fix? It looks good to me :)
