### ISSUE TITLE
[babel 8] Cleanup parser plugins

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#16456]
- [x] Remove from https://github.com/babel/babel/blob/main/packages/babel-parser/src/typings.d.ts all those that are enabled by default
  - Note that many of then are not explicitly marked as "deprecated" or "this is enabled by default"
- [x] `importAssertions` should be removed (https://github.com/babel/babel/pull/16770)
- [x] `importReflection` is now `sourcePhaseImports` (https://github.com/babel/babel/pull/16808)
- [x] `decimal` doesn't have syntax anymore (https://github.com/babel/babel/pull/16741)
- [x] The `smart` and `minimal` pipeline proposals are gone for sure (https://github.com/babel/babel/pull/16801)
- [x] Flow `enums` option should be enabled by default (https://github.com/babel/babel/pull/16792)
- [x] record&tuple is not going to use `{| ... |}` (https://github.com/babel/babel/pull/16458)

**Comment by JLHwung** [comment]
If record and tuple will use `#`, then we should remove the support of hack pipeline with topic token `#` right? These two are conflicted with each other.

**Comment by nicolo-ribaudo** [comment]
The current status is that:
- the future of R&T is uncertain, but _if it happens_ and _if it has syntax_, the only plan is to use `#{`
- the future of pipeline is uncertain, but _if it happens_ all possible tokens are still on the table

**Comment by JLHwung** [comment]
Well in that case we still have to support both features. Thus the error message here
https://github.com/babel/babel/blob/71c247a1831fe70e8b847fdb57b5fc10538d9748/packages/babel-parser/src/plugin-utils.ts#L164
should be refined since `syntaxType` won't be an option in Babel 8.

**Comment by liuxingbaoyu** [comment]
> Flow enums option should be enabled by default

Should we remove this option?

**Comment by JLHwung** [comment]
> > Flow enums option should be enabled by default
> 
> Should we remove this option?

Yes, similarly we should remove typescript plugins's `allowDeclareFields` in Babel 8.
