### ISSUE TITLE
[Bug]: Error parsing TypeScript generics on left-hand side

### ISSUE THREAD

**Issue by mtdavis** [babel/babel#16465]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

[REPL link](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAQVXSxgGF9C4BvAKDmbjAFclcBLTONBGDzgBbAJ4AxNgDtMAfgBccADwBZOKBjApAEyKk0GbNQIoAfAAomLazAAWXFIv3kjNFABor15lyn8ZwIoqntYAlHAAvKZwAG4QXNoA3AwAvgwMoJCwcHgmcJQQMlDAmsa0Glq6JGSGVG70XnDawLnFIhJcwLjaiga-AObJaRng0DiFaHC-XPARcObhUQ3WmBM4uERzBUUlwGUoyY14KAB0YpIyStuYxaVu0XPmvv6YwIvRjN4sq34QuMAnXAQfpPPwwBABE4AM063VCyWsaTSQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.24.5&externalPlugins=&assumptions=%7B%7D)

[other compilers for comparison](https://sucrase.io/#transforms=typescript&compareWithTypeScript=true&compressedCode=H4sIAJbyM2YAA22QTQqDMBCF94J3mKVC8QD%2BlVLozkNonNpAmkgyFkvx7k2MtlU6mzB58958CY690gR1Y0jXjICJ2hg4Le157l5hALb6oRGcgaGa7HF%2FXgbJjinkFeBIKNudrYy8zRXduEm38uGrcmkzJcMUquU2hqKEh%2BJtFgZTGIQBekxPd1aSaST0dH%2BXr8wtWotGR8tRtKml11x2%2B1hlCSwGJyggmpcvfq8wYaywWZs5%2BzwhTOL%2FIt8MlC5qfdlv5BqrBCZCdZ%2BZ5OoI48xPTTPhG7UjEZGeAQAA)

### Configuration file name

.babelrc

### Configuration

```json
{
  "presets": [
    [
      "@babel/preset-typescript",
      {
        "allowDeclareFields": true
      }
    ],
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": true
        },
        "modules": "commonjs"
      }
    ]
  ]
}
```

### Current and expected behavior

Current behavior: Babel outputs the error "Invalid left-hand side in assignment expression."

Expected behavior: Babel does not output an error, and generates code similar to what `tsc` generates.

### Environment

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.11.1 - ~\.nvm\versions\node\v20.11.1\bin\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - ~\.nvm\versions\node\v20.11.1\bin\npm.CMD
  npmPackages:
    @babel/cli: ^7.23.9 => 7.23.9
    @babel/core: ^7.24.0 => 7.24.0
    @babel/node: ^7.23.9 => 7.23.9
    @babel/polyfill: ^7.11.5 => 7.12.1
    @babel/preset-env: ^7.24.0 => 7.24.0
    @babel/preset-typescript: ^7.23.3 => 7.23.3
    eslint: ^8.57.0 => 8.57.0
    jest: ^29.7.0 => 29.7.0
```

### Additional context

The minimal reproduction code is a little weird, but the real use case where we encountered this issue is when initializing Sequelize model classes that extend a base class.

**Comment by JLHwung** [comment]
For the record, TS 5.7 does not allow `cls.fn<C> = x`: [TS Playground](https://www.typescriptlang.org/play/?useDefineForClassFields=true&experimentalDecorators=true#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAQVXSxgGF9C4BvAKDmbjAFclcBLTONBGDzgBbAJ4AxNgDtMAfgBccADwBZOKBjApAEyKk0GbNQIoAfAAomLazAAWXFIv3kjNFABor15lyn8ZwIoqntYAlHAAvKZwAG4QXNoA3AwAvgwMoJCwcHgmcJQQMlDAmsa0Glq6JGSGVG70XnDawLnFIhJcwLjaiga+AObJaRng0DiFaHC+XPARcObhUQ3WmBM4uERzBUUlwGUoyY14KAB0YpIyStuYxaVu0XPmvv6YwIvRjN4sq34QuMAnXAQfpPPwwBABE4AM063VCyWsaTSQA)

I didn't check further: It may have been implemented in an earlier TS version.
