### ISSUE TITLE
Special handling for undefined as a default value

### ISSUE THREAD

**Issue by julien-f** [babel/babel#1646]
For documentation purposes, I like to annotate optional parameters with `undefined` when their are no obvious default values:

```javascript
function foo ({
  bar = undefined
} = {}) {
  // ...
}
```

Currently it compiles to:

```javascript
function foo(_ref) {
  var _ref$bar = _ref.bar;
  var bar = _ref$bar === undefined ? undefined : _ref$bar;

  // ...
}
```

Which is not necessary and could simply be written has:

```javascript
function foo(_ref) {
  var _ref$bar = _ref.bar;
  var bar = _ref$bar;

  // ...
}
```

**Comment by sebmck** [comment]
This is unnecessary and there's no real compelling reason to do this. Running your code over some DCE or similar transforms will yield a much better result.

**Comment by julien-f** [comment]
You are right :)

Unfortunately, using DCE does not change anything.
