### ISSUE TITLE
Async Generators ("Observables") now Stage 1

### ISSUE THREAD

**Issue by staltz** [babel/babel#1647]
Just for your information, check this https://docs.google.com/file/d/1uEVcOgJIMsHjN1vypKKyfmDRg_bz5cKXpo0v4Nc0q8NfqKolBeSDHIj8z9GS8A4EiMpZ8QQ3l87Q_wF3/edit

Would be great to have this in Babel, and one can take inspiration from RxJS or most.js or Kefir in order to implement the babel=>ES5 transformation.

**Comment by Cmdv** [comment]
+1

**Comment by zloirock** [comment]
I wanted to add `Observable` to `core-js`, but [proposal](https://github.com/zenparsing/es-observable/) seriously changing every day. Too unstable :)

**Comment by xgrommx** [comment]
+1

**Comment by cesarandreu** [comment]
+1, interested in playing around with this

**Comment by sebmck** [comment]
Please stop +1ing issues.

**Comment by Cmdv** [comment]
@sebmck what would be a better way to show support? just if you say nothing then it might look like no one is interested in the feature being proposed. I understand where you are coming from though =)

**Comment by stefanpenner** [comment]
@Cmdv I suspect the best way to show interest is to implement it. :trollface:

On a less snarky note, as a maintainer it really just feels like noise. If there was no interest I suspect the issue would be closed. 

On the flip side, as a consumer showing interest feels appropriate. I do wish github had a +1 counter or star (like Google code) that didn't introduce comment thread noise.

**Comment by jmm** [comment]
@stefanpenner 
> If there was no interest I suspect the issue would be closed.

How are the maintainers / contributors supposed to know what issues few people (or one) care about vs. many? And by that logic, other people who see the issue and are also interested would just do nothing because they see there's already an issue and think that means it'll be on the radar, but if the OP loses interest they could just close the issue.

> On the flip side, as a consumer showing interest feels appropriate. I do wish github had a +1 counter or star (like Google code) that didn't introduce comment thread noise.

I think GitHub needs something like that.

**Comment by stefanpenner** [comment]
> On the flip side, as a consumer showing interest feels appropriate. I do wish github had a +1 counter or star (like Google code) that didn't introduce comment thread noise.
> I think GitHub needs something like that.

:100:

**Comment by deepsweet** [comment]
https://www.zenhub.io/ adds +1 feature to github as well as kanban-like issues management (which is very useful by the way) and other stuff, but it needs to be installed by all interested folks including Sebastian :) like "please use zenhub and I'll see and respect all your +1s".

**Comment by sebmck** [comment]
Ok so after reviewing those slides there doesn't appear to be much of any special syntax. The only special thing is `async function*` and `for...on` which includes little information on semantics. Seems extremely premature at this stage and I'm not ready to implement this without something more substantial. cc @jhusain.

**Comment by sebmck** [comment]
Actually, just remembered there was [this](https://github.com/jhusain/asyncgenerator). Doesn't seem to be the latest and most up to date. Anyway, that has already been requested in facebook/regenerator#163 and #602.

**Comment by sebmck** [comment]
Reopening until @jhusain has a chance to chime in.

**Comment by boopathi** [comment]
The latest proposal is here - https://docs.google.com/file/d/1uEVcOgJIMsHjN1vypKKyfmDRg_bz5cKXpo0v4Nc0q8NfqKolBeSDHIj8z9GS8A4EiMpZ8QQ3l87Q_wF3/edit 

Source: https://twitter.com/jhusain/status/604111900012511232

Also, I hope this one helps too - https://twitter.com/jhusain/status/604686082639200256 

> Committee concerned about number of new loops/constructs proposed. Examining ways of accomplishing same thing with primitives.

**Comment by jhusain** [comment]
Yes I haven't had a chance to do so but I'm   withdrawing the async generator proposal in favor of the more basic Observable class. 

JH

**Comment by zloirock** [comment]
@boopathi your link to the presentation, I mentioned link to the proposal above.

**Comment by zloirock** [comment]
@jhusain @zenparsing any ideas when the proposal will be stable enough to be implemented in `core-js` / `babel` / `regenerator`?

**Comment by stefanpenner** [comment]
I suspect the earlier people start playing with the [proposed spec/polyfil](github.com/zenparsing/es-observable) the better. 

@zloirock babel is has various stages, does core-js have the same?

**Comment by sebmck** [comment]
There's not enough current information on the new syntax being proposed so unsure what needs to be done on the Babel side as at this stage it's looking prematurel

**Comment by stefanpenner** [comment]
@sebmck i think the first step is actually on the polyfil side.

**Comment by zloirock** [comment]
@stefanpenner currently - none, [besides single entry points available namespaces](https://github.com/zloirock/core-js#commonjs), for example `core-js/es7` or `core-js/es7/object`. I'll think about stages. But there is another problem - I adapted `Observable` polyfill for `core-js` few days ago, but each day I see breaking changes. The question is when the proposal is stabilized.

**Comment by stefanpenner** [comment]
As mentioned above the more users the more fixes. I don't believe a fixed date exists or is possible to predict. But I do feel confident that when it is stable you will be made quickly aware.

That was my interest in stage support for core-js, as it would accommodate unstable experimentation users are already familiar with in babel proper.

**Comment by zenparsing** [comment]
@zloirock Thanks for your interest in getting the observable polyfill going in core-js.  That's awesome!  The churn that you're seeing in the spec is a result of meetings and discussions between myself and @jhusain over the last few days, and you should expect to see some minor changes as we iron out details and gather input.

Also, note that we've separated the Observable API proposal from any async generator function syntax proposals.

**Comment by benjamingr** [comment]
@sebmck the thing is that libraries like Angular _encourage_ users to +1 which makes +1ing issues more popular in the ecosystem. 

> There's not enough current information on the new syntax being proposed so unsure what needs to be done on the Babel side as at this stage it's looking premature.

Nothing, there are currently no syntax changes proposed in any case. If this is a change it's a change in core-js and not babel. I think this issue can safely be closed in favor of a core-js issue.

**Comment by sebmck** [comment]
@benjamingr 

> Nothing, there are currently no syntax changes proposed in any case. If this is a change it's a change in core-js and not babel. I think this issue can safely be closed in favor of a core-js issue.

Figured as much, thanks for the clarification! Was a bit confused because there were mentions of `for...on` and `async function*` in some of the recent slides.

**Comment by stefanpenner** [comment]
> for...on and async function* in some of the recent slides.

slides that contained "yellow or orange" where suggested to be viewed as "future ideas". I suspect that part of the presentation didn't carry over.

@jhusain maybe a legend at the start of the slide deck would help non committee member consumers.

**Comment by jhusain** [comment]
Agreed. Will change and send out new links.

**Comment by tristancaron** [comment]
Everyone is talking about the coming observable feature, but Chrome has Object.observer with a polyfill which could help us to get something very nice quickly. Currently, when I need a kind of StreamController(from Dart)/Rx.Subject(from RxJS), I use something like 

```javascript
class Stream {
  _stream;
  _notifier;
  
  constructor() {
    this._stream = {};
    this._notifier = null;
  };
  
  listen(callback: (event: any) => void) {
    if (this._notifier === null) {
      Object.observe(this._stream, changes => {
        for (let change of changes) {
          callback(change.value);
        }
      }, ['stream']);
      this._notifier = Object.getNotifier(this._stream);
    }
  }
  
  add(event) {
    this._notifier.notify({
      type: 'stream',
      value: event,
    });
  }
}

let test = new Stream();
test.listen(v => console.log(`My value: ${v}`));
test.add(42);
test.add(43);
```

It's not great but maybe it could help, or not...

**Comment by DylanPiercey** [comment]
AsyncGenerators proposal has changed -> https://github.com/zenparsing/es-observable

**Comment by benjamingr** [comment]
@dylanpiercey that's not the same one. This is a separate proposal.
