### ISSUE TITLE
"yield* undefined" should throw, but doesn't

### ISSUE THREAD

**Issue by AmitAber** [babel/babel#1648]
according to the spec, and as implemented in other engines (traceur, v8...), `yield* undefined` should throw a TypeError exception. Instead, the line is ignored / exception is caught and hidden inside.

To reproduce:

```Javascript
function* gen() {
  yield* undefined;
}

let y = gen();
while(true) {
  let r = y.next();
  for(let key in r)
    console.log(`  ${key}: ${r[key]}`);
  if(r.done)
    break;
}
```

**Comment by sebmck** [comment]
Please report this on the [regenerator repo](https://github.com/facebook/regenerator).

**Comment by AmitAber** [comment]
I reported the bug as you suggested. Am I supposed to close the issue here? (It's still affecting babel...)

**Comment by eventualbuddha** [comment]
@AmitAber at least cross-link them by posting a link to the issue you filed here. Thanks!

**Comment by sebmck** [comment]
Closing in favor of facebook/regenerator#202.
