### ISSUE TITLE
Key conflict on two symbol key properties with decorators

### ISSUE THREAD

**Issue by otakustay** [babel/babel#1649]
Sorry for so many issues on this, I'm really new to the decorators proposal and is not quite capable to understand the grammar, I tried to search over issues but did not find anything related.

```js
class Custom {
  @foo;
  [Symbol()]() {
  }
  
  @foo;
  [Symbol()]() {
  }
}
```

This code results in a `repl: Line 7: Key conflict with sibling node` error, when I either:

1. Remove the `@foo;` decorator
2. Give symbols a different name such as `[Symbol('x')]() {}`

it goes well.

I'm just wondering how decorator expressions can effect the method expression so it works when I remove `@foo;`, and why two `Symbol()` could be conflict since Symbol should be different with each other.

Thanks

**Comment by loganfsmyth** [comment]
Seems like an issue with [toKeyAlias](https://github.com/babel/babel/blob/49953e3464e09845b1ede717aee2bfdec72c0c21/src/babel/types/converters.js#L110) because it tries to compare the serialized AST nodes to decide if there is a key conflict, but that's not a valid assumption, as this issue demonstrates.

**Comment by loganfsmyth** [comment]
Perhaps we can say if the key contains a CallExpression or any expression that can cause mutation, we generate a unique key name? Since this would also trigger this bug:

```
let i = 0;

class Custom {
  [i++]() {
  }

  [i++]() {
  }
}
```

**Comment by sebmck** [comment]
I guess the check could be more relaxed for normal methods. Can't really do anything about getters and setters though since they **need** to be coerced into the same descriptor object.

**Comment by loganfsmyth** [comment]
@sebmck Two responses this this, after a bit of searching.

1. Does the grouping need to happen at build time? I'd assumed that they would be grouped at run time.
2. Are you certain we need to group them at all? Looking at the behavior of `defineProperty` in the ES6 spec at least, I think the answer is no. `Object.defineProperty` lets you apply a setter and a getter for a property as two separate calls.

    ```
    var obj = {};
    
    Object.defineProperty(obj, 'prop', {
      get(){
        return 'some-value'
      },
      enumerable: true,
      configurable: true
    });
    
    Object.defineProperty(obj, 'prop', {
      set(val){
        console.log('setting prop', val);
      },
      //get: undefined,
      enumerable: true,
      configurable: true
    });
    
    obj.prop = 'ho';
    
    console.log(obj.prop);
    ```

    for example creates an object with a getter and setter, it's only if you explicitly pass `get: undefined` that the getter is deleted. So you should be able to just pass separate descriptors at run-time and not worry about it.

**Comment by sebmck** [comment]
@loganfsmyth 

1. Doing it at runtime would be much more reliable and stable but would lead to a lot of extra code that would be pretty nasty. 
2. This would mess with decorators.
