### ISSUE TITLE
[Bug]: Cannot use @babel/preset-env in the browser from version 7.24.1

### ISSUE THREAD

**Issue by mstijak** [babel/babel#16491]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
import jsx from "@babel/plugin-transform-react-jsx";
import fbind from "@babel/plugin-proposal-function-bind";

import { transform } from "@babel/core";
import * as env from "@babel/preset-env";
import * as cx from "babel-plugin-transform-cx-jsx";

export function transpile(code) {
   try {
      var doc = transform(code, {
         presets: [[env, { loose: true }]],
         plugins: [cx, jsx, fbind],
      });
      return doc.code;
   } catch (e) {
      return `/* Error: ${e.message} \n ${e.stack} */`;
   }
}
```

### Current and expected behavior

```js
import corejs3Polyfills from "core-js-compat/data.json" with { type: "json" };
```
is compiled into
```js
const corejs3Polyfills = JSON.parse(require("fs").readFileSync(require.resolve("core-js-compat/data.json")));
```
which makes it impossible to use it in the browser.

I think this commit introduced the problem:
https://github.com/babel/babel/commit/ec0171e85e8ab4a9becaa90d84afcb432885837e#diff-f7b57f023be8b020c8b0a14c39105ee2fb9f3400c0438b9b3e912e78efd266c8

### Environment

- Babel version 7.24.4		

### Possible solution

Reverting to version 7.24.0 helps.

### Additional context

babel is loaded in a dev-like online environment:
https://fiddle.cxjs.io/?f=g33HXn2r

**Comment by nicolo-ribaudo** [comment]
If that line used `fetch` as a fallback for `fs.readFileSync`, would it be better?

**Comment by mstijak** [comment]
I think that might work. As long as it's possible to run it in the browser.
