### ISSUE TITLE
[Bug]: When I pull the Babel source code and execute the make bootstrap command, a syntax error is reported

### ISSUE THREAD

**Issue by moonsky-all** [babel/babel#16492]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

When I pull the Babel source code and execute the make bootstrap command, a syntax error is reported.

![image](https://github.com/babel/babel/assets/82572484/76092400-ae41-4b5a-83c6-1a2c5feea5d4)

I have checked my local environmental information, as follows

![image](https://github.com/babel/babel/assets/82572484/538747be-242c-49fb-87a8-9f99e6112be8)

### Current and expected behavior

I hope it can be compiled locally

### Environment

- babel：8.0
- yarn: 4.2.2
- node: 20.9
- MacOS: 14.4.1

**Comment by liuxingbaoyu** [comment]
Can you try node v20.13.1?

**Comment by JLHwung** [comment]
Yes to build Babel one will need node.js 20.10.0 or above. We should update the node requirement here as well

https://github.com/babel/babel/blob/6e14020b927b60a0cb8c152957e340117dbc0164/CONTRIBUTING.md?plain=1#L40

**Comment by moonsky-all** [comment]
Yes when I switch to node.js 20.13, I successfully compiled the source code, thank you
