### ISSUE TITLE
@babel/plugin-proposal-duplicate-named-capturing-groups-regex: support dynamically created regular expressions

### ISSUE THREAD

**Issue by rauschma** [babel/babel#16502]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

The plugin works for RegExp literals but not for regular expressions created via `new RegExp()`.

### Describe the solution you'd like

FWIW: I created the following (quick and very dirty) workaround: I replace `new RegExp` with `new RegExpX` – which invokes the class shown below. The solution I’d like would be cleaner than that.

```js
class RegExpX {
  constructor(str, flags) {
    const RE = /(?<!\\)\((\?<(?<name>[^<>]+)>)?/g;
    let parenCounter = 0;
    const groupNameToGroupNumbers = new Map();
    str = str.replaceAll(
      RE,
      (all, ...args) => {
        const groups = args.pop();
        parenCounter++;
        if (groups.name) {
          let groupNumbers = groupNameToGroupNumbers.get(groups.name);
          if (groupNumbers === undefined) {
            groupNumbers = [];
            groupNameToGroupNumbers.set(groups.name, groupNumbers);
          }
          groupNumbers.push(parenCounter);
          // It’s in the Map, only its group number matters now
          return `(`; // avoid any name clashes
        }
        return all;
      }
    );
    // Override what the constructor would normally return:
    return _wrapRegExp(
      new RegExp(str, flags),
      Object.fromEntries(groupNameToGroupNumbers)
    );
  }
}
```

### Describe alternatives you've considered

None

**Comment by liuxingbaoyu** [comment]
https://github.com/zloirock/core-js/commit/913625f59490f27af27c1e58c2a3dd2a52e3429b
Have you enabled corejs? It seems they already support it.

**Comment by rauschma** [comment]
Thanks! I tried both of the following import statements:

```js
import 'core-js/actual/regexp/constructor.js';
import 'core-js/actual/index.js';
```

But both failed as follows:

```
SyntaxError: Invalid regular expression:
/^(?<year>[0-9]{4})-(?<month>[0-9]{2})|(?<month>[0-9]{2})\/(?<year>[0-9]{4})$/:
Duplicate capture group name
```

I can create an issue for core-js, but it may make sense to document that the Babel plugin only handles RegExp literals.

**Comment by M-MkM** [comment]
**_**hi**_**

**Comment by M-MkM** [comment]
hi**__**
