### ISSUE TITLE
[Bug]: transitive dependency of @ampproject/remapping flagged as malware

### ISSUE THREAD

**Issue by ataraxus** [babel/babel#16529]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

.

### Current and expected behavior

Currently flagging our build due to grype reporting critical issue GHSA-8rmg-jf7p-4p22 in transitive dep

Expected behavior: if this is not a false positive, removing this dependency.

### Environment

"node_modules/@babel/core": {
      "version": "7.22.10",
      "integrity": "sha512-fTmqbbUBAwCcre6zPzNngvsI0aNrPZe77AeqvDxWM9Nm+04RrJ3CAmGHA9f7lJQY6ZMhRztNemy4uslDxTX4Qw==",
      "dev": true,
      "dependencies": {
        "@ampproject/remapping": "^2.2.0",
        "@babel/code-frame": "^7.22.10",
        "@babel/generator": "^7.22.10",
        "@babel/helper-compilation-targets": "^7.22.10",
        "@babel/helper-module-transforms": "^7.22.9",
        "@babel/helpers": "^7.22.10",
        "@babel/parser": "^7.22.10",
        "@babel/template": "^7.22.5",
        "@babel/traverse": "^7.22.10",
        "@babel/types": "^7.22.10",
        "convert-source-map": "^1.7.0",
        "debug": "^4.1.0",
        "gensync": "^1.0.0-beta.2",
        "json5": "^2.2.2",
        "semver": "^6.3.1"
      },
      "engines": {
        "node": ">=6.9.0"
      }
    },

### Additional context

Hey there, 

@ampproject/remapping as a transitive dep on https://github.com/jridgewell/gen-mapping see: 
https://github.com/babel/babel/blob/1bbc2266555cede40b92c3e984b2c843c7ffbe99/packages/babel-core/package.json#L49

which in turn got marked as malware: 

https://github.com/advisories/GHSA-8rmg-jf7p-4p22

this is probably a false positive but in case its not, i wanted to give you notice. 

I reported this to the maintainer here: https://github.com/jridgewell/gen-mapping/issues/12

Just in case this is not a false positive, i think this would require immediate response :/

**Comment by liuxingbaoyu** [comment]
I think this is completely irrelevant. Maybe you should report it to grype.
https://www.npmjs.com/package/gen-mapping
vs
https://www.npmjs.com/package/@jridgewell/gen-mapping

**Comment by ataraxus** [comment]
@liuxingbaoyu thanks for this headsup. 
I could reproduce this with the current version of grype, which apparently gets confused and reported it there (https://github.com/anchore/grype/issues/1886). Sorry for the confusion.
