### ISSUE TITLE
Can't return an object from a one-line arrow function

### ISSUE THREAD

**Issue by alexlafroscia** [babel/babel#1654]
I noticed that Babel doesn't seem to support returning an object from an arrow function.  For example, I am trying to write a function that compiled to this:

```javascript
var objects = [1, 2, 3].map(function (item) {
  return { 'number': item };
});
```

So, I wrote a one-liner using an Arrow function and the implicit return like this:

```javascript
const objects = [1, 2, 3].map((item) => { 'number': item });
```

However, the above ES6 code above compiles to the following:

```javascript
var objects = [1, 2, 3].map(function (item) {
  number: item;
});
```

and thus, `objects` has three `null`s in it.  I understand that the curly braces are probably confusing to the compiler, but is it possible that this could be supported eventually?

**Comment by loganfsmyth** [comment]
That is expected behavior, because wrapping the body of an arrow function with `{}` is how you define an arrow function with statements instead of with expressions. To do what you are trying to do, you need parens, e.g.

    const objects = [1, 2, 3].map((item) => ({ 'number': item }));

**Comment by alexlafroscia** [comment]
Oh, perfect! I didn't know about wrapping the object in parentheses.  Thanks for the tip!

**Comment by fkling** [comment]
@alexlafroscia: That's actually the same reason why you cannot write

```js
{"foo" 42}
```
It's ambiguous and in that case the `{...}` are considered to be a **block**.

Putting the construct in parenthesis (the *grouping operator*) forces the engine to interpret it as *expression*, and there is only one expression that starts with `{`: an object literal.

```js
({"foo": 42}) // works
```

**Comment by alexlafroscia** [comment]
@fkling totally makes sense! I figured that object and block both using `{` was the cause of the issue, but hadn't thought of wrapping it in parentheses to make it an express. I appreciate the help :smile:
