### ISSUE TITLE
[Bug]: @babel/helper-plugin-utils@npm:7.24.7: No candidates found

### ISSUE THREAD

**Issue by vonny29** [babel/babel#16558]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

yarn add --dev @babel/helper-plugin-utils@7.24.7            
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0082: │ @babel/helper-plugin-utils@npm:7.24.7: No candidates found
➤ YN0000: └ Completed in 0s 421ms
➤ YN0000: · Failed with errors in 0s 438ms

### Configuration file name

babel.config.json

### Configuration

{
  "sourceType": "unambiguous",
  "presets": [
    [
      "@babel/preset-env",
      {
        "shippedProposals": true,
        "loose": true
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-transform-shorthand-properties",
    "@babel/plugin-transform-block-scoping",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    [
      "@babel/plugin-proposal-private-methods",
      {
        "loose": true
      }
    ],
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-syntax-dynamic-import",
    [
      "@babel/plugin-proposal-object-rest-spread",
      {
        "loose": true,
        "useBuiltIns": true
      }
    ],
    "@babel/plugin-transform-classes",
    "@babel/plugin-transform-arrow-functions",
    "@babel/plugin-transform-parameters",
    "@babel/plugin-transform-destructuring",
    "@babel/plugin-transform-spread",
    "@babel/plugin-transform-for-of",
    "babel-plugin-macros",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    [
      "babel-plugin-polyfill-corejs3",
      {
        "method": "usage-global",
        "absoluteImports": "core-js",
        "version": "3.17.3"
      }
    ]
  ]
}

### Current and expected behavior

The latest version of `@babel/helper-plugin-utils` is shown as `7.24.7` but when I try to add it to my application it shows the following error:

yarn add --dev @babel/helper-plugin-utils@7.24.7            
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0082: │ @babel/helper-plugin-utils@npm:7.24.7: No candidates found
➤ YN0000: └ Completed in 0s 421ms
➤ YN0000: · Failed with errors in 0s 438ms

### Environment

  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn
    npm: 10.2.5 - /opt/homebrew/bin/npm

**Comment by majies** [comment]
@vonny29  try upgrade to the latest yarn, that fixed mine

**Comment by vonny29** [comment]
It was an issue with my company's Nexus server, thank you so much for responding so quickly and helping to resolve this.
