### ISSUE TITLE
[Bug]: No matching version found for @babel/helper-string-parser@^7.24.7

### ISSUE THREAD

**Issue by yang369390743** [babel/babel#16559]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

![error](https://github.com/babel/babel/assets/29563739/18786830-250f-4f6f-90bc-ebf8b9941c08)
npm install not found @babel/helper-string-parser@^7.24.7

### Current and expected behavior

Find the current version

### Environment

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-string-parser@^7.24.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/types'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\env\nodejs\node_cache\_logs\2024-06-06T02_58_56_966Z-debug.log

**Comment by lzwStore** [comment]
![image](https://github.com/babel/babel/assets/77309273/664b0d2c-7e9b-4b79-817f-27d9057b393b)
No matching version found for @babel/helper-create-class-features-plugin@^7.24.7

**Comment by JLHwung** [comment]
Please check [the npm website](https://www.npmjs.com/package/@babel/helper-create-class-features-plugin?activeTab=code):

<img width="938" alt="image" src="https://github.com/babel/babel/assets/3607926/621f2caf-e7b6-454a-bab2-93f8c425da09">

As you can see, the version 7.24.7 was indeed published to npm. Please check if there is a stale proxy or cache between you and npm (this is the most likely cause and it is common in corporate networks).
