### ISSUE TITLE
Computed es7.classProperties

### ISSUE THREAD

**Issue by elierotenberg** [babel/babel#1655]
I'm not sure this is a babel limitations, or a spec limitation, but with `es7.classProperties`, one can not define class properties with computed property key. Typical use case is with symbols.
```js
sym = Symbol();
class {
 [sym] = null;
}
```

Also, sorry if this issue has already been reported, but I seeked and couldn't find an identical issue.

**Comment by hzoo** [comment]
You should be able to do

```js
let sym = Symbol();
class MyClass { // name
  [sym]() { // computed symbol
    return null;
  }
}
```

**Comment by elierotenberg** [comment]
I am, but the semantics are different.
Basically I would like
```js
const sym = Symbol();
class MyClass {
 [sym] = null;
}
```
to be desugared to

```js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var sym = Symbol();

var MyClass = function MyClass() {
  _classCallCheck(this, MyClass);

  this[sym] = null;
};
```

**Comment by zloirock** [comment]
@elierotenberg see [this comment](https://gist.github.com/jeffmo/054df782c05639da2adb#comment-1406269) and [reply](https://gist.github.com/jeffmo/054df782c05639da2adb#comment-1406722).
