### ISSUE TITLE
[Bug]: Runtime error after upgrade @babel/node to 7.24.6

### ISSUE THREAD

**Issue by akairyuu1993** [babel/babel#16552]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

I am using @babel/node to work with SailJS project.
To lift up project I ran this command
`../../node_modules/.bin/babel-node --expose-gc app.js`

### Configuration file name

babel.config.js

### Configuration

module.exports = {
  presets: [['@babel/preset-env', {targets: {node: 'current'}}]],
};

### Current and expected behavior

got this error
```
/node_modules/@babel/node/lib/_babel-node.js:26
program.name("babel-node");
^
TypeError: Cannot read properties of undefined (reading 'name')
at Object.<anonymous> (/opt/absolute/absolute-ems-api/node_modules/@babel/node/lib/_babel-node.js:26:9)
at Module._compile (node:internal/modules/cjs/loader:1358:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
at Module.load (node:internal/modules/cjs/loader:1208:32)
at Module._load (node:internal/modules/cjs/loader:1024:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
at node:internal/main/run_main_module:28:49
```

### Environment

"@babel/cli": "7.24.6"
"@babel/core": "7.24.6"
"@babel/node": "7.24.6"
"@babel/preset-env": "7.24.6"
Node: v20.13.0
```

### Possible solution

_No response_

### Additional context

_No response_

**Comment by JLHwung** [comment]
I can not reproduce this issue. Can you provide a reproduction repo? babel-node 7.24 bumps commander to 6.2.0, please also check if node_modules are corrupted.

**Comment by akairyuu1993** [comment]
Found that my repo has put commander as fixed version 
```
"resolutions": {
          ...
	  "commander" : "3.0.2",
          ....
  }
```
Bump it to 6.2.0 and issue gone. Thanks!
I will close this issue
