### ISSUE TITLE
Binding pattern parameters

### ISSUE THREAD

**Issue by bathos** [babel/babel#1656]
(This is very likely correct behavior -- I just want to be sure.)

I was surprised to find that this throws:

    function abc({ xyz=true }) {}
    abc();

It throws because the binding argument wasn't provided. I wasn't able to find a description of how this is supposed to behave in the ES6 draft but I'm probably just not searching for the right things. With Babel, it does work if a default value for the parameter to be destructured is itself is provided:

    function abc({ xyz=true }={}) {}
    abc();

The logic is sound there, really -- perhaps it only seems strange to me because up till now it's never been possible for a function to throw based on nothing but its arguments.

**Comment by sebmck** [comment]
This is correct and expected behaviour. In the future please see the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
