### ISSUE TITLE
configure babel.register to just transform one node module + all my code

### ISSUE THREAD

**Issue by gilesbradshaw** [babel/babel#1657]
I can't work out how to do this with the ignore and only options - wondering if someone could help
I have
````
require("babel/register")({
  ignore: false,
  only: [
    "node_modules/js-csp/**/*.*",
    "src/**/*.*"
  ]
});
````

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!
