### ISSUE TITLE
[Bug]: get a error quasis

### ISSUE THREAD

**Issue by tenadolanter** [babel/babel#16575]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const text = `${a1}a${a2}${a3}${a4}b`;
```

### Current and expected behavior

get 5 quasis，but  actual it has 6

### Environment

https://astexplorer.net/

JavaScript

@babel/parse

**Comment by nicolo-ribaudo** [comment]
> get 5 quasis，but actual it has 6

Why 6? There is a quasi `""`, followed by `a1`, followed by a quasi `"a"`, followed by `a2`, followed by a quasi `""`, followed by `a3`, followed by a quasi `""`, followed by `a4`, followed by a quasi `"b"`. 5 in total: `""`, `"a"`, `""`, `""`, `"b"`.

ASTExplored shows that Babel correctly finds 5:
<img width="241" alt="image" src="https://github.com/babel/babel/assets/7000710/9fa0154b-fe29-456d-91e6-f64a118e1ec3">

**Comment by tenadolanter** [comment]
@nicolo-ribaudo  `${a1}a${a2}${a3}${a4}b` => `quasis:  ["", "a",  "", "", "", "b"]`, why you get 5

**Comment by tenadolanter** [comment]
@nicolo-ribaudo 

```
${a1}     => 1
a            => 2
${a2}     => 3
${a3}     => 4
${a4}     => 5
b            => 6
```

so `${a1}a${a2}${a3}${a4}b` => `quasis ['', 'a', '', '', '', 'b']`, so it is 6,  Is there any error here ?

**Comment by nicolo-ribaudo** [comment]
Yes, quasis are the parts that are _not_ in `${...}` :)

Try running this code in a browser:
```js
console.log`${1}a${2}${3}${4}b` 
```

The first logged value (the array) is the list of quasis, and the other logged values are those inside `${...}` (that Babel saves in `.expressions` in the AST).

**Comment by tenadolanter** [comment]
@nicolo-ribaudo Thank you, I misunderstood before
