### ISSUE TITLE
`return` inside `do` inconsistently supported 

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1658]
```js
function f() {
  var x = do { return 5; };
}
```

compiles to

```js
function f() {
  var x = (function () {
    return 5;
  })();
}
```

but 

```js
var x = do { return 5; };
```

gives

```
'return' outside of function (1:13)
```

Unless I'm missing something obvious, it seems either both should work or both shouldn't.

**Comment by sebmck** [comment]
These aren't actually documented anywhere Babel. The only proposal that exists is the one [here](http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions). `continue` and `break` should also be illegal inside of it since it's not in an `IterationStatement`.

**Comment by spicyj** [comment]
Got it. I also found this discussion after filing the issue which seems to agree that return probably shouldn't be supported:

https://esdiscuss.org/topic/const-vs-features-detection#content-11
