### ISSUE TITLE
"globals" package version is outdated

### ISSUE THREAD

**Issue by sacru2red** [babel/babel#16592]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

I am follwing set up [guide other pacakge](https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#configuration-new-eslintconfigjs)

and facing a [error](https://github.com/eslint/eslint/discussions/17868)

so I recoginized
- "@babel/plugin-transform-classes" under "@babel/preset-env"
- "@babel/traverse" under "@babel/core"
has outed "globals" version "^11.1.0" (released 2017-12-09)
globals latest version is [15.6.0](https://www.npmjs.com/package/globals/v/15.6.0)

### Describe the solution you'd like

update globals version

### Describe alternatives you've considered

globals update to "[13.24.0](https://www.npmjs.com/package/globals/v/13.24.0)" maybe

**Comment by liuxingbaoyu** [comment]
v11 is the last major version to support Node 6, and we will upgrade it in Babel 8.
