### ISSUE TITLE
Idea: Eliminating unnecessary IIFEs

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1659]
Currently,

```js
a(b(), class { z() {} }, c());
```

compiles to

```js
a(b(), (function () {
  var _class = function () {
    _classCallCheck(this, _class);
  };

  _createClass(_class, [{
    key: "z",
    value: function z() {}
  }]);

  return _class;
})(), c());
```

but it seems like it could compile to something like

```js
var _b = b();
  var _class = function () {
    _classCallCheck(this, _class);
  };

  _createClass(_class, [{
    key: "z",
    value: function z() {}
  }]);

  var _ref = _class;
var _c = c();
a(_b, _ref, _c);
```

which would (presumably) be more efficient at runtime. This could be a general optimization whenever a node transforms into more than one statement. (And a transformer to get rid of user-defined IIFEs could be possible too, though I imagine that wouldn't go in Babel core.)

Is this feasible? If you point me in the right direction maybe I could look into adding this…

**Comment by sebmck** [comment]
Sure, this could only be done for anonymous class expressions though. You could short circuit it [here](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/es6/classes.js#L219) if it's a `ClassExpression` with no `id` then push an `ExpressionStatement` onto it with the class ref and then just return a list of statements (When replacing an expression with a list of statements Babel explodes it into an expression). You'd have to special case super classes though and assign it to a temporary variable as you couldn't rely on the [closures parameters](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/es6/classes.js#L148-149).

**Comment by sebmck** [comment]
That would make:

```javascript
a(b(), class { z() {} }, c());
```

Compile to:

```javascript
var _class;

a(b(), (_class = function () {
  _classCallCheck(this, _class);
}, _createClass(_class, [{
  key: "z",
  value: function z() {}
}]), _class), c());
```

**Comment by spicyj** [comment]
Right, you can do this by changing how individual transformers work, but do you think it would be generally useful to have the ability to "break apart" the parent expressions in order to be able to support arbitrary statements? Then (for example), you could have an expression that compiles into a switch without adding an IIFE.

**Comment by sebmck** [comment]
Sure, although most of that logic would go into core while the plugin would just do something like:

```javascript
new Transformer("inline-iife", {
  CallExpression() {
    var callee = this.get("callee");
    if (callee.isFunctionExpression() && !callee.has("id")) {
      // assign parameters to temp variables and replace body references with temp names
      // append EmptyStatement to completion records
      // turn all ReturnStatements into completion records... somehow
      // return list of statements that can be exploded internally
    }
  }
});
```

Right now, when you replace an expression with a list of statements that can't be turned into a sequence expression then it's turned into an IIFE [here](https://github.com/babel/babel/blob/master/src/babel/traversal/path/replacement.js#L145-166) which obviously isn't ideal but it's the easiest. Exploding the surrounding code would be great though and would be necessary for a decent do expression implementation.

So yeah, totally doable. Feel free to investigate, unsure how tricky handling it would be. Happy to answer any questions!

**Comment by sebmck** [comment]
I had a go at trying to implement this and there are actually some caveats. One of which is loops:

```javascript
var classes = [];
for (let i = 0; i < 5; i++) {
  classes.push(class {});
}
new classes[0];
```

Basically you need to make the temp class variable a `let`. But when we generate those bindings internally we generate them differently to normal user bindings. We add them to the scope tracking even though they don't actually exist in the AST yet (there's no real performant way to "pick" them up) and the `es6.blockScoping` transformer relies on these "user bindings" in order to do it's thing.

Going to close this and mark it as "revisit" to potentially revisit in the future as implementing this right now is actually surprisingly painful, this is something that could also be done in a userland plugin too (as you suggested, via more general IIFE optimisation). Although, I'd assume that engines would optimise IIFE enough that they aren't doing any unnecessary allocations so not sure how beneficial this would be.

**Comment by spicyj** [comment]
Thanks for looking into it.
