### ISSUE TITLE
Request of `@babel/parser`: allow return `void` of `set accessor` 

### ISSUE THREAD

**Issue by finscn** [babel/babel#16593]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

when I parse the code : 
```
set foo (value: number): void
```
babel tell me : 
`SyntaxError: A 'set' accessor cannot have a return type annotation.`

But I think the `void` should be allowed

### Describe the solution you'd like

allow return `void` of  `set accessor` 

### Describe alternatives you've considered

none

**Comment by JLHwung** [comment]
For the following case, TypeScript 5.5.3 throws "A 'set' accessor cannot have a return type annotation." as well ([playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIDOEYyMmyAFAG5wA2ArhAFzIgMC2ARtAJSvV0wACa4AvkA)).
```ts
interface Foo {
  set foo (value: number): void
}
```

If you strongly believe that a setter should allow return type as `void`, please open a feature request to the TypeScript repo.
