### ISSUE TITLE
[Bug]: `using` declarations shoud disallow destructuring

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#16604]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
using x = null, {} = null;
```
and
```js
using x = null, [] = null;
```

### Configuration

Using `@babel/plugin-proposal-explicit-resource-management`

### Current and expected behavior

It should throw a parse error, but it doesn't

### Environment

Babel 7.24

**Comment by H0onnn** [comment]
Hello, @nicolo-ribaudo ! Can I solve this problem?

**Comment by nicolo-ribaudo** [comment]
Yes!



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in `packages/babel-parser/test`, together with the other `using` fixtures (only `input.js`; `output.json` will be automatically generated if you pass the `OVERWRITE=true` env var)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by JLHwung** [comment]
Context: This is a regression introduced in https://github.com/babel/babel/pull/15225.
