### ISSUE TITLE
sourcemaps : Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babel#1660]
//cli call
`babel src/js/app/ApplicationBootstrap.js --out-file src/js/compiled/ApplicationBootstrap.js --source-maps`

// ApplicationBootstrap.js
```js
import ApplicationConfig from 'app/ApplicationConfig';
import Application from 'app/Application';

export {
	Application as default,
	Application
};
```
// generated ApplicationBootstrap.js
```js
'use strict';

Object.defineProperty(exports, '__esModule', {
	value: true
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _appApplicationConfig = require('app/ApplicationConfig');

var _appApplicationConfig2 = _interopRequireDefault(_appApplicationConfig);

var _appApplication = require('app/Application');

var _appApplication2 = _interopRequireDefault(_appApplication);

exports['default'] = _appApplication2['default'];
exports.Application = _appApplication2['default'];

//# sourceMappingURL=ApplicationBootstrap.js.map
```

// ApplicationBootstrap.js in chrome, firefox, safari, ie sources
// Something goes wrong. See below on //# sourceMappingURL=ApplicationBootstrap.js
// The end of `(functions(exports, module, ..... is in the sourceMappingURL
// Is that a bug?
```js
(function(exports, module, require, __filename, __dirname, global){'use strict';

Object.defineProperty(exports, '__esModule', {
	value: true
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _appApplicationConfig = require('app/ApplicationConfig');

var _appApplicationConfig2 = _interopRequireDefault(_appApplicationConfig);

var _appApplication = require('app/Application');

var _appApplication2 = _interopRequireDefault(_appApplication);

exports['default'] = _appApplication2['default'];
exports.Application = _appApplication2['default'];

//# sourceMappingURL=ApplicationBootstrap.js.map}).call(_g._this, _g["exports"], _g["module"], _g["require"], _g["__filename"], _g["__dirname"], _g["global"]);
//# sourceMappingURL=https://domain.com/js/compiled/ApplicationBootstrap.js.map
```

**Comment by sebmck** [comment]
No this is a bug with whatever module bundler you're using. Babel does not wrap your code in anything like that.

**Comment by SerkanSipahi** [comment]
Well, with `systemjs@0.16.11, es6-module-loader@0.16.6, systemjs/builder@0.10.6` our application doesnt work in `Safari,7,8 and IE,9,10,11` but if we use `systemjs@master#last-revision, es6-module-loader@master#last-revision, systemjs/builder@master#last-revision` and this workarounds https://github.com/babel/babel/issues/1548 , https://github.com/systemjs/systemjs/issues/463 the app works without erros in `Safari,7,8 and IE,9,10,11`. So, generating sourcemaps with system/builder@master#last-revision occurs the error described above. We have to use that all things(#master-releases, workarounds) because we develop for 6 months and have next  month release-date :(

//system.conf
```js
System.config({
	"baseURL":"./",
	"map":{
		"jquery":"extlib/jquery",
		"underscore":"extlib/underscore",
		"moment":"extlib/moment",
		"babel" : "extlib/browser",
		"runtime" : "extlib/runtime",
	},
	"paths":{
		"app/*":"js/app/*.js",
		"com/*":"com/*.js",
		"compiled/*":"js/compiled/*.js",
		"config/*":"config/*.js",
		"core/*":"js/core/*.js",
		"extlib/*":"js/extlib/*.js",
		"lib/*":"js/lib/*.js",
		"model/*":"js/model/*.js",
		"pages/*":"pages/*.js",
		"plugins/*":"js/plugins/*.js",
	},
	"transpiler" : 'babel',
	"babelOptions" : {
		"stage" : 0,
		"externalHelpers": true,
	},
});
```

//sytem/builder
```js
var Builder = require('systemjs-builder');

var buildConfig = {
	minify : true,
	sourceMaps : true,
};

builder = new Builder();
builder.loadConfig('src/config/systemjs-cfg.js').then(function() {
	builder.config({baseURL: 'src'});
	builder.build('app/ApplicationBootstrap - [app/**/*] - [com/**/*] - [core/**/*] - [model/**/*] - [lib/**/*] - [compiled/**/*] - [config/**/*]', 'src/js/compiled/shared.js', buildConfig);
	builder.build('app/ApplicationBootstrap - [extlib/**/*]', 'src/js/compiled/ApplicationBootstrap.js', buildConfig);
});
```

If i remove the `buildConfig.minify` flag it doesnt occurs an error in the browser. It generate the sourcemap but now I get other problem.  In chrome `dev-tool sources` i can select my app files but dont get the js file. Instead, always the index.html. See pic http://de.tinypic.com/view.php?pic=15zhwtc&s=8#.VWxHf2TtlBc

Last but not least i tryed `babel src/js/app/ApplicationBootstrap.js --out-file src/js/compiled/ApplicationBootstrap.js --source-maps` :(

**Comment by sebmck** [comment]
I don't see how this is a Babel issue? The script is being wrapped in a function call and it's not adding a newline. It's completely unrelated to anything with Babel.
