### ISSUE TITLE
[feature request][UMD] expose the detected module system

### ISSUE THREAD

**Issue by thgreasi** [babel/babel#1662]
In case the UMD formatter is used, it would be great if the detected module system was also exposed somehow. It would allow for even greater dirty hacks...

Right now I need to duplicate the detection code (sniffing the global object since export & module are function parameters for the factory) in order to conditionally load other modules.

**Comment by sebmck** [comment]
Babel doesn't detect any module system though?

**Comment by thgreasi** [comment]
I was talking about passing the detected module type (at runtime) to the factory function.

Something like:
```js
(function (global, factory) {
    if (typeof define === 'function' && define.amd) {
        define(['exports', 'module'], function(){
          var args = Array.prototype.slice.call(arguments, 0);
          args.unshift('amd');
          factory.apply(this, args);
        });
    } else if (typeof exports !== 'undefined' && typeof module !== 'undefined') {
        factory('commonjs', exports, module);
    } else {
        var mod = {
            exports: {}
        };
        factory('global', mod.exports, mod);
        global.localforageSerializer = mod.exports;
    }
})(this, function (moduleType, exports, module) {
```

Surely the code could be better, but I'm just describing what would be helpful for my use case.

**Comment by sebmck** [comment]
I don't see what internal Babel facilities are supposed to be exposed for this? There's no special magic done internally for any module systems besides the different module formatters which are manually set.

**Comment by thgreasi** [comment]
This request targets the UMD formatter only. Not any internal babel part.
That way someone could load any required modules based on the moduleType detected at runtime.
Something like what [mozilla/localForage does](https://github.com/mozilla/localForage/blob/90dd7f0825057f14e14377576149b47d84f6daa0/src/localforage.js#L331-L350). Such a change to the UMD formatter would reduce this code duplication while transitioning to a build system that includes babel.

**Comment by sebmck** [comment]
Oh right, don't think this is a good idea to expose since if you're writing ES6 modules then you shouldn't care or know about how they're being used. Closing this as I consider it out of scope as it's sufficiently divergent behaviour to be very dangerous. Thanks for the suggestion though!
