### ISSUE TITLE
[Bug]: errors importing `@babel/standalone` since yesterdays Babel release

### ISSUE THREAD

**Issue by declann** [babel/babel#16634]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

n/a

### Current and expected behavior

Hi,

This notebook illustrates the issue: I cannot import latest `@babel/standalone`, but I can when I pin to `7.24.7`.

Error given is `SyntaxError: The requested module '/npm/@babel/core@7.24.8/+esm' does not provide an export named 'default'` which is a bit confusing for me because the 7.24.7 version of `@babel/core` serves the same content.

https://observablehq.com/@declann/babel-standalone-issue

Regards,
Declan

### Environment

n/a

**Comment by nicolo-ribaudo** [comment]
How are you importing `@babel/standalone`? It's an UMD package, so whatever service you are using to convert it to ESM is applying some transform on top of our code.

**Comment by nicolo-ribaudo** [comment]
It seems like it's jsdelivr that is failing to bundle it: https://cdn.jsdelivr.net/npm/@babel/core@7.24.8/+esm

**Comment by nicolo-ribaudo** [comment]
The source of the bug is that we have a `require("@babel/helper-module-transforms")` call left in the bundle, I'll investigate it.

**Comment by biffgaut** [comment]
I'm seeing problems since yesterday's release as well. My project structure is too complex to be useful to post here, I'm currently working on isolating the issue so I can clearly demonstrate the issue in a repeatable way. But I'll mention it here in case it's related or can increase the priority.

Every build has failed since the release with the following error:

```
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:16 - error TS1005: ']' expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                    ~~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:19 - error TS1005: ';' expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                       ~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:28 - error TS1005: ';' expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                                ~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:29 - error TS1128: Declaration or statement expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                                 ~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:30 - error TS1128: Declaration or statement expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                                  ~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:39 - error TS1005: ')' expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                                           ~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:971:40 - error TS1005: ';' expected.
@aws-solutions-constructs/core: 971     [N in Node as N["type"]]?: (keyof N)[];
@aws-solutions-constructs/core:                                            ~
@aws-solutions-constructs/core: ../../../node_modules/@babel/types/lib/index.d.ts:972:1 - error TS1128: Declaration or statement expected.
@aws-solutions-constructs/core: 972 };
```

**Comment by nicolo-ribaudo** [comment]
Could you open a new issue, including the TS version you are using? It's completely unrelated from the one discussed in this issue, and having a separate one would make it easier for us to track it.
