### ISSUE TITLE
[Bug]: Cannot use Class to be Decorator params when set targets to { chrome: '85', safari: '13' }

### ISSUE THREAD

**Issue by actake** [babel/babel#16661]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```typescript
const Decorator = (extConfig?) => {
  return (Cls) => {
    console.log("Cls: ", Cls);
    return class extends Cls {};
  };
};

const Log = (target, key, descriptor) => {
  const originMethod = descriptor.value;

  descriptor.value = function (...params) {
    console.log("in log decorator...");
    originMethod.apply(this, params);
  };

  return descriptor;
};

@Decorator(Main)
class Main {
  @Log
  test() {}
}

// @ts-ignore
window.Test = new Main();
```

### Configuration

```javascript
// webpack.config.js
const HtmlWebPackPlugin = require("html-webpack-plugin");
const path = require("path");

module.exports = {
  entry: [path.resolve("./src/index.tsx")],
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx", ".json", ".d.ts"],
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            sourceType: "unambiguous",
            plugins: [
              ["@babel/plugin-proposal-decorators", { version: "legacy" }],
            ],
            presets: [
              [
                "@babel/preset-env",
                {
                  useBuiltIns: "usage",
                  corejs: { version: "3", proposals: true },
                  // if remove targets config, work well
                  // but if add this config, will show error runtime
                  targets: {
                    chrome: "85",
                    safari: "13",
                  },
                  include: ["@babel/plugin-transform-class-properties"],
                },
              ],
              "@babel/preset-react",
              "@babel/preset-typescript",
            ],
          },
        },
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
          },
        ],
      },
    ],
  },
  devServer: {
    historyApiFallback: true,
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: path.resolve(__dirname, "./public/index.html"),
    }),
  ],
};
```

### Current and expected behavior

# Current behavior

with above code and compile config, will show this error(runtime console): 

```txt
Uncaught ReferenceError: Cannot access 'Main' before initialization
    at eval (model.ts:20:30)
    at ./src/model.ts (main.js:51:1)
    at __webpack_require__ (main.js:372:33)
    at fn (main.js:583:21)
    at eval (index.tsx:6:64)
    at ./src/index.tsx (main.js:41:1)
    at __webpack_require__ (main.js:372:33)
    at main.js:1456:37
    at main.js:1458:12
```

but if remove `targets` config, those code will **working well**

> Those code is working well when I use SWC compiler

# Expected behavior

like removed `targets` config behavior, or SWC behavior

### Environment

 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.17.1 - D:\env\nodejs\node.EXE
    Yarn: 1.22.21 - D:\env\nodejs\yarn.CMD
    npm: 9.6.7 - D:\env\nodejs\npm.CMD
    pnpm: 8.15.0 - D:\env\nodejs\pnpm.CMD
  npmPackages:
    @babel/core: 7.20.7 => 7.20.7
    @babel/plugin-proposal-decorators: 7.20.7 => 7.20.7
    @babel/plugin-transform-class-properties: ^7.24.7 => 7.24.7
    @babel/preset-env: 7.20.2 => 7.20.2
    @babel/preset-react: 7.18.6 => 7.18.6
    @babel/preset-typescript: 7.18.6 => 7.18.6
    babel-loader: 8.2.5 => 8.2.5
    webpack: 5.75.0 => 5.75.0

### Additional context
[Quick reproduce repo](https://github.com/actake/decorator-compile-bug)

**Comment by JLHwung** [comment]
The behaviour on `{ chrome: '85', safari: '13' }` is correct, as the runtime error said, you can not access the class binding `Main` when you are _evaluating_ the decorator expression `Decorator(Main)`. The decorator expressions are evaluated interleavingly with the computed keys. For example, 

```js
class Main {
  // error: Cannot access 'Main' before initialization
  [Main.name] = 1;
}
```
you can not access the class binding `Main` in a computed key `[Main.name]`, because they should be evaluated _before_ the class binding is initialized. This is the so-called Temporal Dead Zone (TDZ) error.

When the `targets` option is removed, the class will be transformed into a function, however Babel is not quite good at reproducing the TDZ error behaviour on the transformed class. So the transformed code does not throw a runtime error.

```diff
const Decorator = (extConfig?) => {
  return (Cls) => {
    console.log("Cls: ", Cls);
    return class extends Cls {};
  };
};

--- @Decorator(Main)
+++ @Decorator()
class Main {
  @Log
  test() {}
}
```
Now as far as I can tell from the code snippet, did you mean `@Decorator()` ? Because you don't have to pass `Main` to the `Decorator` factory. The factory does accept an extra config parameter but you are not using it anyway. The factory `Decorator` does returns a decorator `(Cls) => class extends Cls {}`, which will be applied to the `Main` class so the `Main` class will be accessed from the `Cls`, not `extConfig`.

**Comment by actake** [comment]
> The behaviour on `{ chrome: '85', safari: '13' }` is correct, as the runtime error said, you can not access the class binding `Main` when you are _evaluating_ the decorator expression `Decorator(Main)`. The decorator expressions are evaluated interleavingly with the computed keys. For example,
> 
> ```js
> class Main {
>   // error: Cannot access 'Main' before initialization
>   [Main.name] = 1;
> }
> ```
> 
> you can not access the class binding `Main` in a computed key `[Main.name]`, because they should be evaluated _before_ the class binding is initialized. This is the so-called Temporal Dead Zone (TDZ) error.
> 
> When the `targets` option is removed, the class will be transformed into a function, however Babel is not quite good at reproducing the TDZ error behaviour on the transformed class. So the transformed code does not throw a runtime error.
> 
> ```diff
> const Decorator = (extConfig?) => {
>   return (Cls) => {
>     console.log("Cls: ", Cls);
>     return class extends Cls {};
>   };
> };
> 
> --- @Decorator(Main)
> +++ @Decorator()
> class Main {
>   @Log
>   test() {}
> }
> ```
> 
> Now as far as I can tell from the code snippet, did you mean `@Decorator()` ? Because you don't have to pass `Main` to the `Decorator` factory. The factory does accept an extra config parameter but you are not using it anyway. The factory `Decorator` does returns a decorator `(Cls) => class extends Cls {}`, which will be applied to the `Main` class so the `Main` class will be accessed from the `Cls`, not `extConfig`.

**Comment by actake** [comment]
> The behaviour on `{ chrome: '85', safari: '13' }` is correct, as the runtime error said, you can not access the class binding `Main` when you are _evaluating_ the decorator expression `Decorator(Main)`. The decorator expressions are evaluated interleavingly with the computed keys. For example,
> 
> ```js
> class Main {
>   // error: Cannot access 'Main' before initialization
>   [Main.name] = 1;
> }
> ```
> 
> you can not access the class binding `Main` in a computed key `[Main.name]`, because they should be evaluated _before_ the class binding is initialized. This is the so-called Temporal Dead Zone (TDZ) error.
> 
> When the `targets` option is removed, the class will be transformed into a function, however Babel is not quite good at reproducing the TDZ error behaviour on the transformed class. So the transformed code does not throw a runtime error.
> 
> ```diff
> const Decorator = (extConfig?) => {
>   return (Cls) => {
>     console.log("Cls: ", Cls);
>     return class extends Cls {};
>   };
> };
> 
> --- @Decorator(Main)
> +++ @Decorator()
> class Main {
>   @Log
>   test() {}
> }
> ```
> 
> Now as far as I can tell from the code snippet, did you mean `@Decorator()` ? Because you don't have to pass `Main` to the `Decorator` factory. The factory does accept an extra config parameter but you are not using it anyway. The factory `Decorator` does returns a decorator `(Cls) => class extends Cls {}`, which will be applied to the `Main` class so the `Main` class will be accessed from the `Cls`, not `extConfig`.

Sorry, I think my example code will make some confused; It's my real use scene:
**`Decorator` is import from the third party lib, it must received target decorate class to be first params**
So I think we should not care the implement of the Decorator, we know it need target class to do something, that's enough;
Here is the simplified code(The repo's code also updated), I've remove something useless code:
```typescript
const Decorator = (targetClass, config?) => {
  // maybe use targetClass to do something
  return (Cls) => {
    return class extends Cls {};
  };
};

// will show runtime error
@Decorator(Main)
class Main {}
```

And then I will show my new discovery:
1. use dev mode to compile this scene code(goto above repo can see the detail), will show runtime error;
2. remove `targets` config to compile(also dev mode), working well;
3. **use product mode to compile(do not remove `targets` config), working well**

In addition, I think the the following code should be equal:
```typescript
@Decorator(Main)
class Main {}
```
and
```typescript
class _Main{}
const Main = Decorator(_Main);
```

**Comment by nicolo-ribaudo** [comment]
As @JLHwung explained, the bug is that under some configurations Babel does _not_ throw an error. Accessing the class in one of the params to the decorators is a TDZ error.

As a workaround, you can change your decorator to accept a function that returns a class:
```js
@Decorator(() => Main)
class Main {}
```

and the decorators has to be careful to not call that `() => Main` function until when the class is done being initialized.

---

In addition, I think the the following code should be equal:

@Decorator(Main)
class Main {}

and

class _Main{}
const Main = Decorator(_Main);

---

> In addition, I think the the following code should be equal:
> 
> ```ts
> @Decorator(Main)
> class Main {}
> ```
> 
> and
> 
> ```ts
> class _Main{}
> const Main = Decorator(_Main);
> ```

The first code snippet is more similar to the following:
```js
class _Main {}
const Main = Decorator(Main);
```

**Comment by actake** [comment]
> As @JLHwung explained, the bug is that under some configurations Babel does _not_ throw an error. Accessing the class in one of the params to the decorators is a TDZ error.
> 
> As a workaround, you can change your decorator to accept a function that returns a class:
> 
> ```js
> @Decorator(() => Main)
> class Main {}
> ```
> 
> and the decorators has to be careful to not call that `() => Main` function until when the class is done being initialized.
> 
> What is the third-party library that you are using?
> 
> > In addition, I think the the following code should be equal:
> > ```ts
> > @Decorator(Main)
> > class Main {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```ts
> > class _Main{}
> > const Main = Decorator(_Main);
> > ```
> 
> The first code snippet is more similar to the following:
> 
> ```js
> class _Main {}
> const Main = Decorator(Main)(_Main);
> ```

[UniverJS](https://github.com/dream-num/univer)
[Real usecase](https://github.com/dream-num/univer/blob/b3ebd7970309afd012fbdea4afaaca847417fe56/packages/core/src/services/user-manager/user-manager.service.ts#L24-L25)
[Decorator implement](https://github.com/dream-num/univer/blob/b3ebd7970309afd012fbdea4afaaca847417fe56/packages/core/src/services/lifecycle/lifecycle.ts#L74-L80)

**Comment by nicolo-ribaudo** [comment]
That decorator should be rewritten as follows:
```js
export function OnLifecycle(lifecycleStage: LifecycleStages, identifier?: DependencyIdentifier<unknown>) {
    const decorator = function decorator(constructor: Ctor<unknown>) {
        runOnLifecycle(lifecycleStage, constructor || identifier);
    };

    return decorator;
}
```
and used as
```js
@OnLifecycle(LifecycleStages.Ready)
class MyService {

}
```

However, if you don't want to change the decorator implementation, this shuold work too:
```js
@(Constructor => OnLifecycle(LifecycleStages.Ready, Constructor)(Constructor))
class MyService {}
```

**Comment by actake** [comment]
This bug should not be closed, why is there a difference behavior between development mode and production mode with the same configuration? @nicolo-ribaudo

**Comment by JLHwung** [comment]
> why is there has difference behavior between development mode and production mode with the same configuration?

When webpack `mode` is `production`, webpack will turn on terser to minimize the output. Terser is really good at removing unused codes, and in your case, the `model.ts` is completely stripped from the built result `dist/main.js` because terser considers this module as side-effect free. You can turn off the optimization 
```js
// webpack.config.js
{
  optimization: {
    minimize: true
  },
}
```
and check whether it will throw the same runtime error or you can just add `console.log(Main)` so that it has side effect.
