### ISSUE TITLE
arrow functions parsing 'this' to undefined

### ISSUE THREAD

**Issue by AdamCmiel** [babel/babel#1667]
```js
const arrow = () => this
```

translates to:
```js
"use strict";

var arrow = function arrow() {
  return undefined;
};

**Comment by sebmck** [comment]
See the [FAQ](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-) as well as #1573,  #562, #814, #730 and #733.

**Comment by AdamCmiel** [comment]
thanks much

**Comment by HiZhaoxiaoyang** [comment]
lots of answers, none works.
