### ISSUE TITLE
[Bug]: Script evaluation using babel-node’s ‘--eval’ doesn’t apply default config file

### ISSUE THREAD

**Issue by Rinzwind** [babel/babel#16675]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

```js
console.log("foo");
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  plugins: [
    [ "search-and-replace", { rules: [ { search: "foo", replace: "bar" } ] } ],
  ],
};
```

### Current and expected behavior

Using a file ‘test.js’ with the input code given above, and a file ‘babel.config.js’ with the given configuration which uses a plugin to replace `"foo"` by `"bar"`, the following has the expected result:

```
$ npx babel-node test.js
bar
```

But when using `--eval` to pass the input code, the result is unexpected, the config file does not seem to be applied:

```
$ npx babel-node --eval 'console.log("foo");'
foo
```

### Environment

```
  System:
    OS: macOS 13.6.7
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  npmPackages:
    @babel/node: ^7.24.8 => 7.24.8 
    babel-plugin-search-and-replace: ^1.1.1 => 1.1.1 
```

### Additional context

Issue #11877, which is about `--config-file` not being applied, is similar but differs in that it says that a default config file did work.

**Comment by JLHwung** [comment]
It will be fixed in v7.25.0 by #16642.
