### ISSUE TITLE
[Bug]: _traverse.visitors.environmentVisitor is not a function in @babel/helper-remap-async-to-generator@7.25.0

### ISSUE THREAD

**Issue by rayhomie** [babel/babel#16686]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

<img width="905" alt="image" src="https://github.com/user-attachments/assets/4d661e52-08fc-424d-aebb-4f83e23ad743">

### Current and expected behavior

<img width="905" alt="image" src="https://github.com/user-attachments/assets/1a27a7e6-09b6-4b48-9af7-7c564d4f082f">

### Environment

Node.js v18.19.0
[tnpm] subprocess:/Users/houmi/.npm-global/lib/node_modules/tnpm/lib/npm_child_process.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1
tnpm@9.13.6 (/Users/houmi/.npm-global/bin/tnpm)
npm@8.19.4 (/Users/houmi/.npm-global/lib/node_modules/tnpm/node_modules/npm/index.js)
node@18.19.0 (/usr/local/bin/node)
npminstall@6.7.1 (/Users/houmi/.npm-global/lib/node_modules/tnpm/node_modules/npminstall/lib/index.js)
prefix=/Users/houmi/.npm-global (load prefix from: /Users/houmi/.npmrc)
darwin arm64 22.5.0
registry=https://registry.antgroup-inc.cn
package.engines={} (package.json: /Users/houmi/Desktop/work-project/ant-design-mini)

### Possible solution

[_traverse.visitors.environmentVisitor is not a function](https://github.com/babel/babel/pull/16649/files#diff-2d3851963c927f431ba856453d67dc9b4a85718db5b0c00feed228ea88014c7bL16)

### Additional context

<img width="886" alt="image" src="https://github.com/user-attachments/assets/35f5de69-cfcb-432a-a864-cb733d104843">

**Comment by liuxingbaoyu** [comment]
Have you pinned `@babel/traverse`? That might be causing the problem.

**Comment by nicolo-ribaudo** [comment]
Please share your lockfile. `_traverse.visitors.environmentVisitor` has been introduced in `@babel/traverse@7.25.0`, and `@babel/helper-remap-async-to-generator@7.25.0` depends on that version.

**Comment by rayhomie** [comment]
> Have you pinned `@babel/traverse`? That might be causing the problem.

I am unable to lock the version of @babel/helper-remap-async-to-generator because it is an internal dependency of Babel.

**Comment by nicolo-ribaudo** [comment]
What should I see when running `npm run dev`? I just see this and then nothing for multiple minutes :thinking: 

```
> antd-mini@2.35.6 dev
> tsx ./scripts/dev.ts
```

Also, can you check what version you have in `node_modules/@babel/traverse/package.json`? I have 7.25.1, which does provide the method that is missing according to your error.

**Comment by nicolo-ribaudo** [comment]
What package manager are you using? From the error stack trace in your screenshot, it does not look like it's npm: npm doesn't generate `node_modules/_<package-name>@<version>` folders.

**Comment by rayhomie** [comment]
> What package manager are you using? From the error stack trace in your screenshot, it does not look like it's npm: npm doesn't generate `node_modules/_<package-name>@<version>` folders. This looks like a bug in your package manager, that is not installing the correct version of dependencies.

Thanks, I'm trying to change the package manager。

**Comment by PartMan7** [comment]
Which package manager were you using? I have a similar issue on yarn 3.2.4

**Comment by VMBindraban** [comment]
I got the issue on node 18, switching to node 20 fixed the problem for me.
