### ISSUE TITLE
[Bug]: ReferenceError: unknown node of type "Literal" with constructor "Node", when generating AST output by the estree plugin with `@babel/generator`

### ISSUE THREAD

**Issue by kazupon** [babel/babel#16707]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from '@babel/parser'
import generate from '@babel/generator'

const code = `
let count = 0;
function increment() {
  count += 1;
}
`
const ast = parse(code, { sourceType: 'module', plugins: ['estree'] })
const { code: output } = generate(ast)
```

### Current and expected behavior

No errors occur and generate to original code

### Environment

  System:
    OS: macOS 13.6.7
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
  npmPackages:
    eslint: ^9.6.0 => 9.7.0 

### Possible solution

use the estree-compliant generator, such as [code-red](https://github.com/Rich-Harris/code-red) or [astring](https://github.com/davidbonnet/astring)

**Comment by nicolo-ribaudo** [comment]
`@babel/generator` does not support ESTree. If you want to use Babel packages you should not use the `estree` plugin in the parser, which is only there for making it possible to use `@babel/parser` in different toolchains.

**Comment by kazupon** [comment]
Thank you for your advise! :)

**Comment by JLHwung** [comment]
@kazupon I am curious about how do you know the `estree` parser plugin?

Our website [here](https://babel.dev/docs/babel-parser#output) is indeed a bit confusing:

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/7bad8e70-a4de-4d9a-9234-9929809f461b">

which portraits `estree` as if it were a must-have parser plugin, which is quite opposite.

**Comment by kazupon** [comment]
@JLHwung 
> I am curious about how do you know the estree parser plugin?

I’ve heard it from @ota-meshi

> Our website [here](https://babel.dev/docs/babel-parser#output) is indeed a bit confusing:

I think, It should be mentioned in `@babel/generator` docs that it cannot be undone with the `estree` plugin.

I have some understanding of the javascript ast spec and I know that there is no way to use it as in this use case, but if it is put as such in the docs, I am tempted to try it. 😅

**Comment by JLHwung** [comment]
Oh I see. The motivation of the `estree` parser plugin is to serve `@babel/eslint-parser`, so that Babel can generate an ESTree-compliant AST for ESLint and other ESTree tools. `@babel/generator` does not support ESTree, otherwise we wouldn't have made this plugin.
