### ISSUE TITLE
injecting babel.parse result in a plugin looses structure

### ISSUE THREAD

**Issue by zbraniecki** [babel/babel#1670]
I'm working on an es6-bundler that collects imports and bundles them into a single source file.

I started using babel-plugin and most of work is done. The only remaining problem is that when I load the imported file using `babel.parse` and then inject the resulted AST into my source, the serialized JS looses some whitespaces.

I guess it has something to do with whitespaces in AST, but I'm not sure how to workaround it.

Example:
./file1.js
```javascript
import { L10nError } from './head';

function load() {}

function foo2() {}
```
./file2.js
```javascript

function load() {}

function foo2() {}
```

In my plugin, I parse the Import, collect ./file2 reference and load it into the same file.

The result looks like this:

```javascript
(function () {
  modules.set('bindings/html/head', function () {
    function load() {}function foo2() {}
  });
  modules.set('bindings/html/io', function () {
    const { L10nError } = getModule('runtime/web/head');

    function load() {}

    function foo2() {}
  });
})();
```

so, while the main module (the one babel is working on) keeps the whitespace properly, the stuff loaded using babel.parse looses WS. I'd like to keep them for readability reasons.

What can I do about that?

**Comment by sebmck** [comment]
You're injecting an AST where all the nodes have `loc` properties that don't correspond to the input code so whitespace is being handled weirdly.

You need to clear them with `babel.traverse.removeProperties` so a complete example would be:

```javascript
var babel = require("babel-core");

babel.traverse.removeProperties(babel.parse("code;"));
```

**Comment by zbraniecki** [comment]
That solved it! Thanks!
