### ISSUE TITLE
[Bug]: After the babel upgraded to 7.25.0, build is failing.

### ISSUE THREAD

**Issue by lakshman0369** [babel/babel#16719]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

"dependencies": {
    "@babel/preset-env": "^7.23.3",
    "@babel/preset-react": "^7.23.3",
},
"devDependencies": {
    "@babel/core": "^7.13.1",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
}

### Current and expected behavior

Creating an optimized production build...
  Failed to compile.
  
  ./node_modules/@testing-library/react/dist/@testing-library/react.esm.js 458:51
  Module parse failed: Unexpected token (458:51)
  File was processed with these loaders:
   * ./node_modules/babel-loader/lib/index.js
  You may need an additional loader to handle the result of these loaders.
  | // if you don't like this then either import the `pure` module
  | // or set the RTL_SKIP_AUTO_CLEANUP env variable to 'true'.
  > if (typeof process === 'undefined' || !process.env?.RTL_SKIP_AUTO_CLEANUP) {
  |   // ignore teardown() in code coverage because Jest does not support it
  |   /* istanbul ignore else */
  
  
  error Command failed with exit code 1.

Build is failing with the above error.

### Environment

Babel version: 7.25.0,
Node: 14.17.0,
yarn: 1.22.19

**Comment by nicolo-ribaudo** [comment]
Can you share your Babel config?

**Comment by lakshman0369** [comment]
![image](https://github.com/user-attachments/assets/7cd5a08d-e8fc-474d-b48c-4623f5c01b11)
currently using webpack version 4

**Comment by nicolo-ribaudo** [comment]
Do you have a .browserslistrc file? Are you passing any additional option to babel-loader?

Can you figure out where that `process.env?.RTL_SKIP_AUTO_CLEANUP` comes from? (Also check in node_modules)

**Comment by lakshman0369** [comment]
I don't have any .browserslistrc file.

`process.env?.RTL_SKIP_AUTO_CLEANUP` - this is coming from @testing-library/react.

{

              test: /\.(js|mjs|jsx|ts|tsx)$/,

              include: paths.appSrc,

              loader: require.resolve('babel-loader'),

              options: {
                customize: require.resolve(
                  'babel-preset-react-app/webpack-overrides'
                ),

                presets: [
                  [
                    require.resolve('babel-preset-react-app'),
                    {
                      runtime: hasJsxRuntime ? 'automatic' : 'classic',
                    },
                  ],
                ],
                
                plugins: [
                  [
                    require.resolve('babel-plugin-named-asset-import'),
                    {
                      loaderMap: {
                        svg: {
                          ReactComponent:
                            '@svgr/webpack?-svgo,+titleProp,+ref![path]',
                        },
                      },
                    },
                  ],
                  isEnvDevelopment &&
                    shouldUseReactRefresh &&
                    require.resolve('react-refresh/babel'),
                ].filter(Boolean),
                // This is a feature of `babel-loader` for webpack (not Babel itself).
                // It enables caching results in ./node_modules/.cache/babel-loader/
                // directory for faster rebuilds.
                cacheDirectory: true,
                // See #6846 for context on why cacheCompression is disabled
                cacheCompression: false,
                compact: isEnvProduction,
              },
            },
            // Process any JS outside of the app with Babel.
            // Unlike the application JS, we only compile the standard ES features.
            {
              test: /\.(js|mjs)$/,
              exclude: /@babel(?:\/|\\{1,2})runtime/,
              loader: require.resolve('babel-loader'),
              options: {
                babelrc: false,
                configFile: false,
                compact: false,
                presets: [
                  [
                    require.resolve('babel-preset-react-app/dependencies'),
                    { helpers: true },
                  ],
                ],
                cacheDirectory: true,
                // See #6846 for context on why cacheCompression is disabled
                cacheCompression: false,
                
                // Babel sourcemaps are needed for debugging into node_modules
                // code.  Without the options below, debuggers like VSCode
                // show incorrect code and set breakpoints on the wrong lines.
                sourceMaps: shouldUseSourceMap,
                inputSourceMap: shouldUseSourceMap,
              },
            },

{

              test: /\.(js|mjs)$/,

              exclude: /@babel(?:\/|\\{1,2})runtime/,

              loader: require.resolve('babel-loader'),

              options: {
                babelrc: false,
                configFile: false,
                compact: false,
                presets: [
                  [
                    require.resolve('babel-preset-react-app/dependencies'),
                    { helpers: true },
                  ],
                ],
                cacheDirectory: true,
                // See #6846 for context on why cacheCompression is disabled
                cacheCompression: false,
                
                // Babel sourcemaps are needed for debugging into node_modules
                // code.  Without the options below, debuggers like VSCode
                // show incorrect code and set breakpoints on the wrong lines.
                sourceMaps: shouldUseSourceMap,
                inputSourceMap: shouldUseSourceMap,
              },
            }

**Comment by nicolo-ribaudo** [comment]
Ok so, when compiling node_modules your webpack config is set to ignore your Babel config and instead use `babel-preset-react-app/dependencies`. That preset has a different behavior based on the NODE_ENV env variable (you can check it's source code to see how).

What is your NODE_ENV set to?

**Comment by lakshman0369** [comment]
NODE_ENV is set to production.
Is there a way to downgrade the babel to 7.24.x to fix this for now?

**Comment by subh-lio** [comment]
@lakshman0369  face same issue unfortunately had to downgrade to 7.24.4

**Comment by lakshman0369** [comment]
![image](https://github.com/user-attachments/assets/9f7c95c9-4148-4ac8-9a2e-0a70dd84b16e)
Are these packages in the resolution enough or need to make any changes?

**Comment by nicolo-ribaudo** [comment]
You can revert your lockfile to what it was before you updated Babel.

Unfortunately I think we'll need a repository that reproduces the issue, as by just looking at configs I do not understand what can cause this.

Please one if you three provide one :)

**Comment by erica4appz** [comment]
i believe you should stop ^version in package.json 
we removed node_modules 
then removed package-lock.json
and updated all package names without ^ 
and worked well 
EG:   "jspdf": "^2.5.1" ->  "jspdf": "2.5.1",

**Comment by JLHwung** [comment]
> I don't have any .browserslistrc file.

Did you set `browserslist` in your `package.json`? If you have not set it, create-react-app will [fallback](https://github.com/facebook/create-react-app/blob/0a827f69ab0d2ee3871ba9b71350031d8a81b7ae/packages/react-dev-utils/browsersHelper.js#L16-L42) to their default browserslist:

```js
const defaultBrowsers = {
  production: ['>0.2%', 'not dead', 'not op_mini all'],
  development: [
    'last 1 chrome version',
    'last 1 firefox version',
    'last 1 safari version',
  ],
};
```
As you can see, when the `NODE_ENV` is `production`, CRA will specify `'>0.2%', 'not dead', 'not op_mini all'` as the default compilation targets. This query is dynamic, and it will be resolved to specific browser versions, e.g. `chrome 109, firefox 115, safari 15.8`, by `browserslist` with the data from `caniuse-lite`.

In 7.25.0, we [bumped](https://github.com/babel/babel/pull/16614) `browserslist` from `4.22.2` to `4.23.1`, which indirectly bumped `caniuse-lite`. My best guess here is that the `caniuse-lite` updates breaks the build as previously `?.` was compiled merely because `>0.2%` includes a version of some browser that does not support optional chaining `?.`. When that version's user base is shrinking, it is finally removed from `>0.2%` so the production build does not compile optional chaining.

You can add an older browser, e.g. `chrome 79` so that the build should work for webpack 4 for the foreseeable future. If you ever upgrade to webpack 5, please remove `chrome 79` from the browserslist.
```json
// package.json
{
  "browserslist": {
      "production": [">0.2%", "not dead", "not op_mini all", "chrome 79"]
  }
}
```
Again, whenever possible, please upgrade to webpack 5, it will enable smaller build because it understands most modern JS syntax.

**Comment by lakshman0369** [comment]
>   "browserslist": {
>       "production": [">0.2%", "not dead", "not op_mini all", "chrome 79"]
>   }
On adding the chrome 79 to the browserlist, build is working without having to downgrade the babel.
