### ISSUE TITLE
Requires Babel "^7.16.0", but was loaded with "7.12.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

### ISSUE THREAD

**Issue by Jitenda-singh** [babel/babel#16723]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Node - v14
Error: [BABEL] /codebuild/output/src3999571347/src/client/src/index.js: Requires Babel "^7.16.0", but was loaded with "7.12.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing: "/codebuild/output/src3999571347/src/client/node_modules/babel-preset-react-app/index.js$0$2")

### Current and expected behavior

Node - v14
Error: [BABEL] /codebuild/output/src3999571347/src/client/src/index.js: Requires Babel "^7.16.0", but was loaded with "7.12.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing: "/codebuild/output/src3999571347/src/client/node_modules/babel-preset-react-app/index.js$0$2")

### Environment

Node - v14
Error: [BABEL] /codebuild/output/src3999571347/src/client/src/index.js: Requires Babel "^7.16.0", but was loaded with "7.12.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing: "/codebuild/output/src3999571347/src/client/node_modules/babel-preset-react-app/index.js$0$2")

**Comment by nicolo-ribaudo** [comment]
Please also provide your `package.json` file, your lockfile `package-lock.json`/`yarn.lock`/`pnpm-lock.json`, and the full stack trace of the error.

**Comment by Jitenda-singh** [comment]
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@amcharts/amcharts4-geodata": "^4.1.27",
    "@amcharts/amcharts5": "^5.3.16",
    "@amcharts/amcharts5-geodata": "^5.1.1",
    "@apollo/client": "^3.5.5",
    "@ckeditor/ckeditor5-react": "^2.0.0",
    "@date-io/date-fns": "^1.3.11",
    "@emotion/css": "^11.10.0",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@loadable/component": "~5.15.0",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.4.3",
    "@material-ui/lab": "^4.0.0-alpha.58",
    "@material-ui/pickers": "^3.2.7",
    "@metamask/onboarding": "^1.0.1",
    "@mui/icons-material": "^5.2.5",
    "@mui/lab": "^5.0.0-alpha.76",
    "@mui/material": "^5.2.5",
    "@mui/x-date-pickers": "^6.14.0",
    "@reduxjs/toolkit": "^1.9.5",
    "@snapshot-labs/snapshot.js": "^0.4.32",
    "@walletconnect/web3-provider": "^1.8.0",
    "@washingtonpost/wpds-pagination-dots": "^1.7.1",
    "apexcharts": "^3.35.4",
    "aws-amplify": "^1.3.3",
    "aws-appsync": "^4.1.4",
    "aws4fetch": "^1.0.13",
    "axios": "^0.27.2",
    "ckeditor5-build-balloon-and-classic": "0.0.3",
    "date-fns": "^2.0.0-beta.5",
    "dayjs": "^1.11.10",
    "debounce": "^1.2.1",
    "detect.js": "^2.2.3",
    "dom-helpers": "^3.2.1",
    "echarts": "^5.1.0",
    "echarts-for-react": "^3.0.1",
    "email-validator": "^2.0.4",
    "emoji-picker-react": "^4.4.9",
    "exceljs": "^3.5.0",
    "file-saver": "^2.0.2",
    "file-type": "^14.1.1",
    "i18n-iso-countries": "^7.7.0",
    "image-extensions": "^1.1.0",
    "interactjs": "^1.9.13",
    "is-url": "^1.2.4",
    "jquery": "^3.7.0",
    "material-ui-chip-input": "^1.1.0",
    "moment": "^2.29.4",
    "moment-timezone": "0.5.28",
    "n-krypta": "^1.0.6",
    "password-validator": "^5.0.2",
    "react": "^17.0.2",
    "react-apexcharts": "^1.3.9",
    "react-app-polyfill": "^1.0.6",
    "react-auto-translate": "0.0.6",
    "react-avatar-editor": "11.0.7",
    "react-beautiful-dnd": "^10.0.4",
    "react-circular-progressbar": "^2.0.3",
    "react-color": "^2.18.0",
    "react-csv": "^2.0.3",
    "react-dom": "^17.0.1",
    "react-dropzone-uploader": "^2.11.0",
    "react-fast-compare": "^3.1.1",
    "react-ga": "^2.7.0",
    "react-grid-carousel": "^1.0.1",
    "react-helmet-async": "^1.3.0",
    "react-html-parser": "^2.0.2",
    "react-infinite-scroll-component": "^5.0.2",
    "react-intl": "^3.3.2",
    "react-lazy-load-image-component": "^1.6.0",
    "react-lottie": "^1.2.3",
    "react-redux": "^8.0.7",
    "react-router-dom": "^5.1.2",
    "react-scripts": "4.0.1",
    "react-select": "^5.8.0",
    "react-share": "^4.4.1",
    "react-sticky": "^6.0.3",
    "react-swipeable-views": "^0.13.9",
    "redux-persist": "^6.0.0",
    "redux-persist-expire": "^1.1.1",
    "sass": "^1.52.1",
    "shiitake": "^3.0.2",
    "slate": "^0.82.0",
    "slate-history": "^0.66.0",
    "slate-hyperscript": "^0.77.0",
    "slate-react": "^0.82.0",
    "uuid": "^3.3.3",
    "web3": "^1.7.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts --max_old_space_size=8192 build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "ie 11",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "ie 11",
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "overrides": {
    "react-error-overlay": "6.0.9"
  }
}

**Comment by Jitenda-singh** [comment]
[package.json](https://github.com/user-attachments/files/16549654/package.json)
[package-lock.json](https://github.com/user-attachments/files/16549655/package-lock.json)

**Comment by nicolo-ribaudo** [comment]
Try deleting all he `@babel/`-related entries from your lockfile, and re-running `npm install`. Your lockfile is pinning a very old version of Babel.

**Comment by sergio222-dev** [comment]
having the exact same error, adding resolution version on my package.json solve this problem
`
  "resolutions": {
    "react-scripts/@babel/core": "^7.16.0"
  }
`

**Comment by Jitenda-singh** [comment]
> having the exact same error, adding resolution version on my package.json solve this problem
> 
> ```json
>   "resolutions": {
>     "react-scripts/@babel/core": "^7.16.0"
>   }
> ```

**Comment by Jitenda-singh** [comment]
> > having the exact same error, adding resolution version on my package.json solve this problem
> > ```json
> >   "resolutions": {
> >     "react-scripts/@babel/core": "^7.16.0"
> >   }
> > ```
Getting this error
./node_modules/@smithy/util-retry/dist-es/AdaptiveRetryStrategy.js 10:17
Module parse failed: Unexpected token (10:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     const {
|       rateLimiter
>     } = options ?? {};
|     this.rateLimiter = rateLimiter ?? new DefaultRateLimiter();
|     this.standardRetryStrategy = new StandardRetryStrategy(maxAttemptsProvider);


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Jitenda-singh** [comment]
> Try deleting all he `@babel/`-related entries from your lockfile, and re-running `npm install`. Your lockfile is pinning a very old version of Babel.

I deleted the package-lock file and reinstalled npm, but I'm still encountering the same error.

**Comment by nicolo-ribaudo** [comment]
Can you run `npx nls why @babel/core` and show the output?

**Comment by nicolo-ribaudo** [comment]
Is that code with ?? coming from your own code or from a dependency? The problem is that you are easing a very old weback version that does not support that syntax. I recommend updating to the latest version.

**Comment by Jitenda-singh** [comment]
> Is that code with ?? coming from your own code or from a dependency? The problem is that you are easing a very old weback version that does not support that syntax. I recommend updating to the latest version.

Thank you, could you please send me step-by-step documentation?

**Comment by nicolo-ribaudo** [comment]
https://webpack.js.org/migrate/5/

**Comment by djaffer** [comment]
Facing a similar issue, not sure what changed. I have already spent hours figuring this out.

**Comment by Jitenda-singh** [comment]
> https://webpack.js.org/migrate/5/

We attempted to update Webpack, but more issues are arising. Is there a simple way to build the app?

**Comment by Jitenda-singh** [comment]
> It was resolved by downgrading caniuse-lite. This recent update was very poorly managed and caused breakages. They should use a static version rather than ^.
> 
> Resolved with downgrading caniuse-lite as babel had upgraded to latest versions.
> 
> "caniuse-lite": "1.0.30001632"
> 
> ```
> npm install caniuse-lite@1.0.30001632 --save
> ```
> 
> ```
> yarn add caniuse-lite@1.0.30001632
> ```
> 
> Place the following in package.json depending on what you use yarn or npm for installation.
> 
> For npm
> 
> ```
>   "overrides": {
>     "caniuse-lite": "1.0.30001632"
>   },
> ```
> 
> For yarn
> 
> ```
>   "resolutions": {
>     "caniuse-lite": "1.0.30001632"
>   },
> ```

Even after that, we are still encountering the same issue.

**Comment by djaffer** [comment]
Did you delete package-lock or yarn.lock and node_modules.

**Comment by nicolo-ribaudo** [comment]
@Jitenda-singh If you can provide a repository that shows the issue I can take a look.

**Comment by Jitenda-singh** [comment]
> Did you delete package-lock or yarn.lock and node_modules.

Yes

**Comment by Jitenda-singh** [comment]
> @Jitenda-singh If you can provide a repository that shows the issue I can take a look.

Failed to compile.

Module not found: Error: Can't resolve './graphql' in '/home/jitendra/Techpearl/OLD_Backup/SWAE/Dev_Deployment_New/swae-3-client/node_modules/graphql'
Did you mean 'graphql.mjs'?
BREAKING CHANGE: The request './graphql' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by Jitenda-singh** [comment]
> @Jitenda-singh If you can provide a repository that shows the issue I can take a look.

Can we set up a meeting on Google Meet?

**Comment by djaffer** [comment]
This is some other error not related to babel loader rather graphql. The babel issue seems is resolved maybe downgrade graphql.
