### ISSUE TITLE
[Bug]: input code `[...Array(4).keys()] ` doesn't working as expected

### ISSUE THREAD

**Issue by BangKk** [babel/babel#16721]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

[...Array(4).keys()] 

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = api => {
    const isDev = api.env('development');
    return {
        presets: [
            ['@babel/preset-env', {
                loose: true,
                targets: '> 1%, last 2 versions, ie 11',
                // modules: false, // ES
                modules: 'commonjs',
                corejs: '3',
                useBuiltIns: 'usage',
            }],
            ['@babel/preset-react', {
                runtime: 'automatic'
            }]
        ],
        plugins: [
            ['@babel/plugin-proposal-decorators', {'legacy': true}],
            ['@babel/plugin-proposal-class-properties', {'loose': false}],
            ['@babel/plugin-proposal-private-methods', {'loose': false}],
            ['@babel/plugin-proposal-private-property-in-object', {'loose': false}],
            ['@babel/plugin-syntax-dynamic-import'],
            '@babel/plugin-proposal-export-default-from',
            isDev ? ['react-refresh/babel'] : null,
        ].filter(Boolean),
    };
};
```
### Current and expected behavior

current behavior:

input code: `[...Array(4).keys()] `
output code : `[].concat(Array(4).keys());`

If you run input code in browser, get `[0, 1, 2, 3]`, but output code get `[Array Iterator {}]`.

### Environment

- Babel version(s): 7.24.7
- Node:  20.9.0
- npm version: 10.1.0
- OS: macOS 14.1.1 (23B81)

**Comment by nicolo-ribaudo** [comment]
Loose mode assumes that you are only spreading arrays. Disable the `loose: true` option from preset-env.

You can check babeljs.io/assumptions to have more grabural control of what "loose" rules you want to use.
