### ISSUE TITLE
[Bug]: @babel/eslint-parser declare @babel/core as a peer dependency even though it requires it

### ISSUE THREAD

**Issue by ericmorand** [babel/babel#16742]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

Not applicable

### Current and expected behavior

`@babel/eslint-parser` declare `@babel/core` as a peer dependency even though it requires it. This creates issue when `@babel/eslint-parser` is declared as `bundledDependencies` because npm doesn't include peer dependencies into the package - which makes sense since they are supposed to be required by the package itself.

It is clear from npm documentation that peer dependencies exist to express the compatibility of `@babel/eslint-parser` with a range of versions of `@babel/core`, not to express that `@babel/eslint-parser` makes uses of `@babel/core`; in this case, `@babel/core` is a dependency.

### Environment

- @babel/eslint-parser@7.25.1

### Additional context

The part of the code that makes use of `@babel/core` is this one: https://github.com/babel/babel/blob/5174ad182faa9cdbd7833096376abf7df3f88f25/eslint/babel-eslint-parser/src/parse.cts#L8

**Comment by nicolo-ribaudo** [comment]
Peer dependencies are also for dependencies that are being imported. It just means "I'm not providing this package my self, but I expect my consumer to provide it"
