### ISSUE TITLE
[Bug]: Wrong ASI in class fields when TS plugin is enabled

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#16759]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
class A {
  static
  foo = 2
}
```

### Current and expected behavior

When the `typescript` plugin is enabled we parse that class as having a field named `static` and one named `foo`. When it's not enabled, we parse it as a class having a static field named `foo`.

The second behavior is correct, and enabling the TS plugin should not change it.

### Environment

Babel 7.25.0

**Comment by JLHwung** [comment]
I believe it is to align with the tsc behaviour, as the tsc 5.5 treats the example as a static property as well: https://www.typescriptlang.org/play/?useDefineForClassFields=true#code/MYGwhgzhAECC0G8BQ1oQC5nQS2C6AZgPZHQC80ATEgL5A

**Comment by nicolo-ribaudo** [comment]
Right, but when the TS plugin is enabled we do _not_ parse it as a static property.
