### ISSUE TITLE
[Bug]: gatsby-source-filesystem throwing error after latest update

### ISSUE THREAD

**Issue by marianobianchi** [babel/babel#16762]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

There is really no specific code that I can add here. The only thing I can mention is that today's morning we started to have issues when building some sites using our gatsby deployment tool. After looking at the dependencies we found that @babel/runtime was uploaded a few hours before. We added a package resolution to use version 7.25.0 instead of 7.25.4. And the issue was solved.

Here is the error we were getting:

```bash
 ReadError: The server aborted pending request
  
  - index.js:809 IncomingMessage.<anonymous>
    [v_1]/[gatsby-source-filesystem]/[gatsby-core-utils]/[got]/dist/source/core/index.js:809:31
  
  - node:events:631 Object.onceWrapper
    node:events:631:28
  
  - node:events:529 IncomingMessage.emit
    node:events:529:35
  
  - node:domain:489 IncomingMessage.emit
    node:domain:489:12
  
  - index.js:43 IncomingMessage.origin.emit
    [v_1]/[gatsby-source-filesystem]/[gatsby-core-utils]/[@szmarczak]/http-timer/dist/source/index.js:43:20
  
  - node:_http_incoming:224 IncomingMessage._destroy
    node:_http_incoming:224:10
  
  - destroy:109 _destroy
    node:internal/streams/destroy:109:10
  
  - destroy:71 IncomingMessage.destroy
    node:internal/streams/destroy:71:5
  
  - node:_http_client:461 TLSSocket.socketCloseListener
    node:_http_client:461:11
  
  - node:events:529 TLSSocket.emit
    node:events:529:35
  
  - node:domain:489 TLSSocket.emit
    node:domain:489:12
  
  - node:net:350 
    node:net:350:12
  
  - node:_tls_wrap:657 TCP.done
    node:_tls_wrap:657:7
```

### Current and expected behavior

It is throwing an error when building a gatsby site. In case it helps, I believe it is while the API is being called to get information that is added in graphql later. That is the broken step in gatsby build process.

### Environment

  System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm

### Possible solution

Something changed between version 7.25.0 and 7.25.4 that made this error start happening.

**Comment by liuxingbaoyu** [comment]
Could you try updating to v7.25.5?

**Comment by nicolo-ribaudo** [comment]
@marianobianchi Are you sure that that's the only dependency change? Between those two versions `@babel/runtime` only had some formatting changes: https://npmdiff.dev/%40babel%2Fruntime/7.25.0/7.25.4/
