### ISSUE TITLE
[Bug]: optional chain logic lost when using with super property get

### ISSUE THREAD

**Issue by shawandshaw** [babel/babel#16767]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

https://babeljs.io/repl#?browsers=last%202%20versions&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEDKvQN4ChrQJDAPYDsIBcAnAV2Hy0IAocwBbAUwEoV1p8ALASwgDoaHoAXmgByKCIDU_egG5UaBcnQBfZKuShIMAILbo9AB756OACYx4SeZlwESZCtTpMUChRGIAHelWmM5bmgc3HzOQqJgYCLQUs5yKshKkQDihPT0-JQQzEroHt6EPADmaRkA_DxZMaLstSL-Sqrq2Hj40GDhOPQA7tC6lCIAVmDAANb1cshgPCmlmSKm9UA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.25.4&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.21.2&assumptions=%7B%7D

### Current and expected behavior

Current:
got tranformed code losing optional chain check logic, which causes an undefined.apply error

expected:
tranformed code should remain the optional chain check logic

### Environment

- Babel version(s): 7.25.2
- Node: 16
- pnpm version: 8.8.0
- OS: macos Sonoma
- Mac with apple chip

**Comment by nicolo-ribaudo** [comment]
Unless I'm missing something, in that repl example the optional chain logic check is not lost:
```js
_superPropGet(AA, "greet", this, 3)) === null || _superPropGet2 === void 0 || _superPropGet2([s + 'hhh']);
```

`_superPropGet2` is only called if it's not null or undefined.

**Comment by nicolo-ribaudo** [comment]
Oh yeah this is a bug
