### ISSUE TITLE
[Bug]: Failed to compile.

### ISSUE THREAD

**Issue by pfrancug** [babel/babel#16763]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

There is no specific code I can input here, it's hard to identify. We're using CRA and today after cleaning modules and lock file `@babel/generator` got updated from `7.25.0` to `7.25.4`. This caused the following error during building process:

```
Module parse failed: Unexpected token (419:26)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|           e[_key - 1] = arguments[_key];
|         }
>         do for (s of i = t, e) t = t.replace(s[0], s[1]); while (t !== i);
|         return t;
|       },
```

### Configuration file name

.babelrc

### Configuration

```
{
  "plugins": [
    ["babel-plugin-transform-typescript-metadata"],
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
  "presets": [
    ["@babel/preset-env"],
    ["@babel/preset-react"],
    ["@babel/preset-typescript"]
  ]
}
```

### Current and expected behavior

Current behavior: fails to compile.
Excepted behavior: compiles successfully as in version `7.25.0`

### Environment

- System:
  - OS: macOS 14.5
- Binaries:
  - Node: 20.17.0 - /usr/local/bin/node
  - Yarn: 1.22.22 - /usr/local/bin/yarn
  - npm: 10.8.2 - /usr/local/bin/npm
- npmPackages:
  - @babel/generator: 7.25.4 => 7.25.4 
  - @babel/plugin-proposal-class-properties: ^7.18.6 => 7.18.6 
  - @babel/plugin-proposal-decorators: ^7.24.7 => 7.24.7 
  - @babel/plugin-proposal-private-property-in-object: ^7.21.11 => 7.21.11 
  - @babel/preset-env: 7.25.4 => 7.25.4 
  - @babel/preset-react: 7.24.7 => 7.24.7 
  - @babel/preset-typescript: ^7.24.7 => 7.24.7 
  - babel-plugin-transform-typescript-metadata: ^0.3.2 => 0.3.2 

### Possible solution

`SequenceExpression` function in `packages/babel-generator/src/node/parentheses.ts` returns wrong value.

### Additional context

For now we specify exact version `7.25.0` of `@babel/generator` in our `package.json` as temporary solution.

**Comment by Marlinxx** [comment]
When this fix will be released?

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/releases/tag/v7.25.5
