### ISSUE TITLE
Implement proposal for JSX standardization

### ISSUE THREAD

**Issue by sdegutis** [babel/babel#16790]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

JSX is here to stay, but currently fragmented and framework-defined.

### Describe the solution you'd like

Add a JSX plugin according to https://vanillajsx.com/unity/

### Describe alternatives you've considered

n/a

### Documentation, Adoption, Migration Strategy

It would be a plugin, an alternative to transform-react-jsx, tentatively called transform-vanilla-jsx, and would be in the docs and repos as a sibling to that first plugin.

**Comment by sdegutis** [comment]
See also https://github.com/denoland/deno/issues/25312

**Comment by nicolo-ribaudo** [comment]
This can already be implemented in a community plugin. I'm not opposites to eventually implementing it in Babel itself, but the path should be:
- it gets imemented in a third-party plugin
- the plugin gets adopted by multiple major frameworks
- the plugin gets moved to the Babel org
