### ISSUE TITLE
[Bug]: babel/highlight has two color libs

### ISSUE THREAD

**Issue by lukeed** [babel/babel#16806]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
npm install @babel/highlight
```

### Current and expected behavior

highlight directly installs two color libraries, including chalk@2.4.1

https://npmgraph.js.org/?q=%40babel%2Fhighlight

You even export a `getChalk` API, which [isn't used by anything in the babel monorepo](https://github.com/search?q=repo%3Ababel%2Fbabel%20getChalk&type=code)

### Environment

any

### Possible solution

remove chalk, which is a 7-item tree.

### Additional context

All the **tarballs** of chalk 2.4.2 amount to **33kB** of downloaded traffic. 
`@babel/highlight` is downloaded **51M** times a week

This means that `@babel/highlight` is forcing/contributing **1,683 GB of transfer every week** for a dependency that (apparently) does nothing, and at best, is redundant.

**Comment by JLHwung** [comment]
See https://github.com/babel/babel/pull/16359 for the reason why we can not remove `chalk` in Babel 7: It is used by the `getChalk` API and although this monorepo does not use it, it may be used by some users and removing an API is definitely a breaking change.

You can upgrade to the babel/hightlight@next (currently 8.0.0-alpha.12), which is a pure ESM library and does not depend on chalk.

**Comment by lukeed** [comment]
I don’t understand why it was added in the first place. If the immediate Babel monorepo has no need for it why would that API be made available in the first place, locking you into exposing it for all of 7.x?

**Comment by JLHwung** [comment]
The `getChalk` API had been used by `@babel/code-frame` before https://github.com/babel/babel/pull/16359 was merged. The old `@babel/code-frame` will stop working if we remove it. This API was added in the day 1 of `@babel/highlight` when the library was extracted from `@babel/code-frame` (https://github.com/babel/babel/pull/7351)

**Comment by lukeed** [comment]
Sorry, that was a poor design/maintainability decision & I hope these kinds of decisions are avoided in the future. That initial PR should have just added chalk as its own dependency. Because of it, 1.6TB transfer a week is wasted (ignoring disk space) since ~2018 & is/will b stuck that way until 8 is released... ignoring how long it takes people to migrate over.

The branches of this monorepo make no sense to me, so if the duplicate libs (and now-pointless API export) have been removed in the RC work, feel free to close this.

Sorry to be a nuisance but I find the sheer size/scale of this to be borderline appalling.

**Comment by JLHwung** [comment]
As far as I know, we don't have other APIS like `getChalk` which passes through a dependency. It is the only exception and it has been removed in Babel 8:

https://github.com/babel/babel/blob/69d65f1aef74de135a8b262bb9770a41e97b7476/packages/babel-highlight/src/index.ts#L284-L299

We don't have a Babel v8 branch, the Babel 8's code stays alongside with Babel 7 within the main branch, controlled by the `BABEL_8_BREAKING` boolean macro that will be stripped in compile time.

**Comment by nicolo-ribaudo** [comment]
Ref https://github.com/babel/babel/pull/16896
