### ISSUE TITLE
[feature request] Throw with informative error message for two adjacent JSX tags

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1682]
For the code

```js
<div></div> <div></div>;
```

esprima-fb gives:

> Parse Error: Line 1: Adjacent JSX elements must be wrapped in an enclosing tag

(https://github.com/facebook/esprima/blob/e68cf9d83071b7b553c9b2e3b5576440bf2a71a1/esprima.js#L7215)

while babel gives:

> Unexpected token (1:18)

Any chance you can add a nicer error message here? We used to get a lot of confusion around this and I'm expecting we will again when we start pointing people to babel.

(Note: this error technically disallows the otherwise parseable code `<div /> < 3` but you can work around that with `(<div />) < 3` if you really want that.)

**Comment by sebmck** [comment]
cc @RReverser

**Comment by RReverser** [comment]
Totally. @sebmck are you using `acorn-jsx` now or internal fork in Babel?

**Comment by sebmck** [comment]
Been using the [plugin](https://github.com/babel/babel/blob/master/package.json#L31) since like 5.2.x.

**Comment by RReverser** [comment]
Cool. I saw the dependency, but better to double-check.
