### ISSUE TITLE
[Bug]: BABEL_TYPES_8_BREAKING breaks `ObjectPattern` used as `id` inside `VariableDeclarator` without `init` in `ForOfStatement`

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#16829]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

I want to construct such code:

```js
for(const{b,c} of a)log(b,c)
```

```js
const forOfTemplate = template(`
for (const %%item%% of %%items%%)
     %%body%%
`);
```

But it throws with:

```js
 TypeError: @babel/template placeholder "item": Property id of VariableDeclarator expected node to be of a type ["Identifier"] but instead got "ObjectPattern"
```

When `BABEL_TYPES_8_BREAKING` is set to true.

### Current and expected behavior

Not throw when put `ObjectPattern` inside `VariableDeclaration` without `init` inside `ForOfStatement`

### Environment

latest

### Possible solution

Get rid of without check

### Additional context

What purpose of `without` check? 

https://github.com/babel/babel/blob/main/packages/babel-types/src/definitions/core.ts#L1233-L1237

In `for-of` constant declared without `init`:

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/babel/babel/pull/16830
