### ISSUE TITLE
React element can break lowercase convention.

### ISSUE THREAD

**Issue by rickyvetter** [babel/babel#1683]
There is an issue with JSX handling where a lower case element gets transformed into the corresponding variable instead of a standard element. This is contradicting the new [JSX behavior](https://gist.github.com/sebmarkbage/f1f4ba40816e7d7848ad). A few things have to be true to make this happen:

- variable has to be instantiated inside of the for loop declaration
- variable has to be `let`, not `var`

Input:
```js
class Icons extends React.Component {
    render() {
        var array = [];
        for(let i = 0; i < 4; ++i) {
            array.push(
                <i></i>
            );
        }
        var a = <i></i>
    }
}
```
Output:
```js
...
var Icons = (function (_React$Component) {
    function Icons() {
        _classCallCheck(this, Icons);

        if (_React$Component != null) {
            _React$Component.apply(this, arguments);
        }
    }

    _inherits(Icons, _React$Component);

    _createClass(Icons, [{
        key: "render",
        value: function render() {
            var array = [];
            for (var _i = 0; _i < 4; ++_i) {
                array.push(React.createElement(_i, null));
            }
            var a = React.createElement("i", null);
        }
    }]);

    return Icons;
})(React.Component);
```

If this is the wrong place and this issue should be brought up elsewhere, I'd be happy to move it there!

**Comment by sebmck** [comment]
It is actually being handled correctly. It's because the `es6.blockScoping` transformer renames .

**Comment by sebmck** [comment]
It is actually being handled correctly (the JSX element handling). It's because the `es6.blockScoping` transformer renames variables and turns `<i />` into `<_i />`.
