### ISSUE TITLE
Object destructuring

### ISSUE THREAD

**Issue by jkarttunen** [babel/babel#1684]
this works:

    let {a,b} = {a:1, b:2};
    console.log(a);  // ---> 1
    console.log(b);  // ---> 1

but not if variables are declared earlier. (E.g in outer scope or line befoer)

    let a, b; 
    {a,b} = {a:1, b:2};
    // SyntaxError:

with arrays that is fine:

    let a, b; 
    [a,b] = [1, 2];
    console.log(a);  // ---> 1
    console.log(b);  // ---> 1

**Comment by loganfsmyth** [comment]
This is expected behavior, though it is an unfortunate gotcha in the spec. Your destructuring is being parsed as a block scope. If you want, you can do

    ({a,b} = {a:1, b:2});

**Comment by jkarttunen** [comment]
Confirmed, this is how it works in Firefox too. :(
