### ISSUE TITLE
[Bug]: @babel/plugin-transform-typescript deletes class field when value is undefined

### ISSUE THREAD

**Issue by trusktr** [babel/babel#16861]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
class MyClass {
  baz
  baz2 = 123
}
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
	plugins: [
		['@babel/plugin-transform-typescript', {allowDeclareFields: true}],
		['@babel/plugin-proposal-decorators', {version: '2023-11'}],
	].map(p => [require.resolve(p[0]), p[1]]),

	presets: [
		['@babel/preset-typescript', {isTSX: true, allExtensions: true, onlyRemoveTypeImports: true}],
		['babel-preset-solid'],
	].map(p => [require.resolve(p[0]), p[1]]),
}
```

### Current and expected behavior

I'm expecting the `baz` property to not be deleted.

```js
class MyClass {
  baz2 = 123;
}
```

The output is as seen here (incorrect): [babel repl](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAECyCeBhcVoG8BQ1oCMwC8tcCAmaAXmgEYSBmDAXyA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=Node-0.10&version=7.25.6&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.24.1%2C%40babel%2Fplugin-transform-typescript%407.25.2&assumptions=%7B%7D)

I'm expecting the output to be like this:

```js
class MyClass {
  baz;
  baz2 = 123;
}
```

The expected output can be seen here when not using the typescript plugin: [babel repl](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAECyCeBhcVoG8BQ1oCMwC8tcCAmaAXmgEYSBmDAXyA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=Node-0.10&version=7.25.6&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.24.1&assumptions=%7B%7D)

### Environment

```
  System:
    OS: macOS 14.6.1
  Binaries:
    Node: 20.6.1 - ~/.n-node-versions/bin/node
    Yarn: 4.0.0 - ~/.n-node-versions/bin/yarn
    npm: 10.5.2 - ~/.npm-packages/bin/npm
  npmPackages:
    @babel/cli: 7.25.6 => 7.25.6 
    @babel/core: 7.25.2 => 7.25.2 
    @babel/plugin-proposal-decorators: 7.24.7 => 7.24.7 
    @babel/preset-typescript: 7.24.7 => 7.24.7 
    @babel/runtime: 7.25.6 => 7.25.6 
    babel-preset-solid: 1.9.0 => 1.9.0 
```

### Possible solution

Not sure what the problem is yet.

**Comment by trusktr** [comment]
I found a workaround:

The config in the OP did not work. Additionally this did not work, causing build errors in the presence of type-only `declare` fields elsewhere in the project:

```js
module.exports = {
	plugins: [
		['@babel/plugin-transform-typescript', {}],
		['@babel/plugin-proposal-decorators', {version: '2023-11'}],
	].map(p => [require.resolve(p[0]), p[1]]),

	presets: [
		['@babel/preset-typescript', {isTSX: true, allExtensions: true, onlyRemoveTypeImports: true, allowDeclareFields: true}],
		['babel-preset-solid'],
	].map(p => [require.resolve(p[0]), p[1]]),
}
```

However, putting the `allowDeclareFields: true` in **both** places worked:

```js
module.exports = {
	plugins: [
		['@babel/plugin-transform-typescript', {allowDeclareFields: true}], // here
		['@babel/plugin-proposal-decorators', {version: '2023-11'}],
	].map(p => [require.resolve(p[0]), p[1]]),

	presets: [
		['@babel/preset-typescript', {isTSX: true, allExtensions: true, onlyRemoveTypeImports: true, allowDeclareFields: true}], // AND here!
		['babel-preset-solid'],
	].map(p => [require.resolve(p[0]), p[1]]),
}
```

The default behavior of the TypeScript plugin is not aligned with JavaScript spec. Class fields without an initializer should not be deleted by default.

Here's a TypeScript playground with `useDefineForClassFields` set to `true` that shows that TypeScript does not delete the field when there is not a `declare`: [TS playground](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=10#code/MYGwhgzhAECyCeBhcVoG8BQ1oCMwC8tcCAmaAXmgEYSBmDAXyA)

To match JavaScript spec, Babel should not delete the field by default in the [above repl](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAECyCeBhcVoG8BQ1oCMwC8tcCAmaAXmgEYSBmDAXyA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=Node-0.10&version=7.25.6&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.24.1%2C%40babel%2Fplugin-transform-typescript%407.25.2&assumptions=%7B%7D).

**Comment by nicolo-ribaudo** [comment]
As you figured out, what you are seeing is the default TypeScript behavior. By enabling TypeScript transforms, you are opting out of JavaScript behavior in favor of TypeScript behavior (this is not the only case of this happening -- `console.log < 1 > (0)` is also another example).

That said, `allowDeclareFields` will be enabled by default in Babel 8: you can already try it with the latest alpha version.

Out of curiosity, why are you using both the TS plugin and the TS preset?
