### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dddssw** [babel/babel#16868]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
const code = `
export function register(selector: string, multiple?: false, parent?: Element): Element | null
export function register(selector: string, multiple?: true, parent?: Element): NodeList | null
export function register(
  selector: string,
  multiple: boolean = false,
  parent?: Element
): Element | NodeList | null {
  const parentElement = parent ?? document
  const domReference = multiple
    ? parentElement.querySelectorAll(selector)
    : parentElement.querySelector(selector)
  return domReference
}
`
```
```
import { parse } from "@babel/parser";
import traverse from "@babel/traverse";

export function getExportInfo(code) {
const ast = parse(code, { sourceType: "module", plugins: ["typescript"] });
traverse.default(ast, {
  ExportNamedDeclaration({ node }) {
console.log(node)
  },
});
```

### Current and expected behavior

![image](https://github.com/user-attachments/assets/a48f1c39-36fa-44bc-b187-6ad947b143d1)
there isn't body in node.declaration,When I delete the function overload body appears
![image](https://github.com/user-attachments/assets/7a064067-3df0-4368-8a6f-36f033617c02)

### Environment

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - C:\Program Files\nodejs\pnpm.CMD
  npmPackages:
    @babel/core: ^7.25.2 => 7.25.2
    @babel/parser: ^7.25.6 => 7.25.6
    @babel/preset-env: ^7.25.4 => 7.25.4
    @babel/traverse: ^7.25.6 => 7.25.6
    babel-loader: ^9.2.1 => 9.2.1
    webpack: ^5.94.0 => 5.94.0

**Comment by liuxingbaoyu** [comment]
It will print 3 nodes, the last one will contain `body`.
You can exclude the `TSDeclareFunction` node.

**Comment by dddssw** [comment]
Sorry, I don't quite understand, because ExportNamedDeclaration can only get this one

**Comment by liuxingbaoyu** [comment]
![image](https://github.com/user-attachments/assets/8c80bea4-5919-4560-963c-0cfc6834d955)
Your example would output three nodes.

**Comment by dddssw** [comment]
Thanks, I see. Is there a simple way to exclude the first two nodes, since the third node is enough?

**Comment by nicolo-ribaudo** [comment]
You can check if there is a body. If there is, you are in the third node.

**Comment by dddssw** [comment]
All right. Thank for your help
