### ISSUE TITLE
[Bug]: Reactjs with node v14.5.0 giving error: TypeError: Promise.allSettled is not a function OR (0 , _bluebird.allSettled) is not a function

### ISSUE THREAD

**Issue by shrutisaluja05** [babel/babel#16869]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

package.json
"dependencies": {
    "@babel/polyfill": "^7.12.1",
    "@babel/runtime-corejs3": "^7.25.6",
    "@blueprintjs/core": "^3.22.3",
    "@blueprintjs/datetime": "3.8.0",
    "@blueprintjs/table": "^3.8.2",
    "babel-runtime": "^6.26.0",
    "bluebird": "3.5.5",
    "classnames": "^2.2.5",
    "codemirror": "^5.52.2",
    "core-js": "^3.38.1",
    "create-react-class": "^15.6.2",
    "cropperjs": "^1.5.6",
    "d3": "5.12.0",
    "d3-selection-multi": "1.0.1",
    "dom-helpers": "^2.4.0",
    "element-resize-detector": "^1.1.14",
    "fast-deep-equal": "^3.1.3",
    "fastdom": "^1.0.5",
    "fileupload-react16": "^3.0.2",
    "fuse.js": "^3.4.5",
    "highcharts": "6.1.1",
    "hoist-non-react-statics": "^1.2.0",
    "jquery": "^3.3.1",
    "js-cookie": "~2.1.3",
    "lodash": "^4.17.21",
    "mobx": "~5.15.2",
    "mobx-react": "~5.4.0",
    "mobx-utils": "~5.2.0",
    "moment": "2.24.0",
    "moment-timezone": "^0.5.4",
    "npm": "^6.13.4",
    "numeral": "^1.5.3",
    "proj4": "^2.3.15",
    "prop-types": "^15.6.0",
    "query-string": "^4.3.1",
    "raf": "^3.2.0",
    "react": "~16.3.2",
    "react-codemirror2": "^7.1.0",
    "react-dnd": "2.6.0",
    "react-dnd-html5-backend": "2.6.0",
    "react-dom": "~16.3.0",
    "react-draggable": "^2.2.1",
    "react-motion": "^0.4.3",
    "react-router": "^3.2.6",
    "react-slick": "^0.27.13",
    "react-widgets": "^4.6.1",
    "react-widgets-simple-number": "^4.1.26",
    "recompose": "^0.30.0",
    "slick-carousel": "^1.6.0",
    "tinycolor2": "^1.4.1",
    "tinymce": "^7.0.0",
    "tween.js": "^16.3.5",
    "validate.js": "^0.9.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.11.6",
    "@babel/core": "^7.7.5",
    "@babel/node": "^7.25.0",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-decorators": "^7.10.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.20.7",
    "@babel/plugin-proposal-optional-chaining": "^7.21.0",
    "@babel/plugin-syntax-dynamic-import": "^7.7.4",
    "@babel/plugin-transform-async-generator-functions": "^7.25.4",
    "@babel/plugin-transform-class-properties": "^7.25.4",
    "@babel/plugin-transform-modules-commonjs": "^7.10.4",
    "@babel/plugin-transform-regenerator": "^7.24.7",
    "@babel/plugin-transform-runtime": "^7.25.4",
    "@babel/preset-env": "^7.7.6",
    "@babel/preset-react": "^7.10.4",
    "@babel/register": "^7.11.5",
    "autoprefixer": "^6.7.6",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.5.2",
    "babel-loader": "^8.0.6",
    "babel-plugin-add-module-exports": "^1.0.4",
    "babel-plugin-istanbul": "^6.0.0",
    "babel-plugin-transform-promise-to-bluebird": "^2.0.0",
    "brfs": "^2.0.2",
    "browserify": "^17.0.0",
    "browserify-css": "^0.15.0",
    "case-sensitive-paths-webpack-plugin": "^2.2.0",
    "clean-webpack-plugin": "^0.1.15",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^3.2.4",
    "css-loader": "^0.26.2",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16.3": "^1.7.3",
    "enzyme-to-json": "^3.6.1",
    "eslint": "^4.8.0",
    "eslint-friendly-formatter": "^1.2.2",
    "eslint-plugin-react": "^7.4.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.1",
    "git-revision-webpack-plugin": "^3.0.3",
    "html-webpack-plugin": "^2.28.0",
    "husky": "^4.3.0",
    "imports-loader": "^0.7.1",
    "jest": "^26.3.0",
    "jest-enzyme": "^7.1.2",
    "jest-junit": "^5.2.0",
    "jsdoc": "^3.6.6",
    "mobx-react-devtools": "~6.0.0",
    "mocha": "^8.1.3",
    "node-sass": "^4.6.0",
    "postcss": "^5.2.16",
    "postcss-loader": "^1.3.3",
    "postcss-scss": "^0.4.1",
    "promise-polyfill": "^8.3.0",
    "react-dnd-test-backend": "2.2.4",
    "react-hot-loader": "3.0.0-beta.6",
    "resolve-url-loader": "^3.0.0",
    "sass-loader": "^6.0.2",
    "style-loader": "^0.13.0",
    "stylelint": "^13.7.2",
    "stylelint-config-sass-guidelines": "^7.1.0",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "unminified-webpack-plugin": "^1.2.0",
    "url-loader": "^0.5.7",
    "webpack": "^3.5.5",
    "webpack-config": "^7.0.0",
    "webpack-dev-server": "^2.4.1",
    "worker-loader": "^0.8.0"
  }

webpack.config.js
 rules: [
      {
        test: /\.js$/,
        use: {
            loader: 'babel-loader',
            options: {
                presets: ['@babel/preset-env', "@babel/preset-react"],
                exclude: path.join(__dirname, '/node_modules'),
                plugins : [
                  '@babel/plugin-proposal-class-properties'
                ]
            },
        },
      },

js code
 const promise1 = Promise.resolve(3);
    const promise2 = new Promise((resolve, reject) =>
      setTimeout(reject, 100, 'foo'),
    );
    const promises = [promise1, promise2];
    
    Promise.allSettled(promises).then((results) =>
      results.forEach((result) => console.log(result.status)),
    );

### Configuration file name

.babelrc

### Configuration

{
  "env": {
    "development" : {
      "plugins": [
        "react-hot-loader/babel"
      ]
    },
    "test": {
      "sourceMaps": "inline",
      "retainLines": true,
      "plugins": [
        ["istanbul", {
          "exclude": [ "**/*.spec.js", "**/*.spec.jsx", "**/_test_/**.*" ],
          "useInlineSourceMaps": false
        }]
      ]
    }
  },
  "presets": [
    "@babel/preset-react",
    ["@babel/preset-env", {
      "useBuiltIns": "entry",
      "modules":false,
      "bugfixes": true,
      "shippedProposals": true,
      "corejs": { "version": "3.8", "proposals": true },
      "targets": {
        "browsers": ["ie >= 10", "ff >= 25", "safari >= 6", "chrome >= 31", "opera >= 34"],
        "node": "14"
      }
    }]
  ],
  "plugins": [
    "add-module-exports",
    "transform-promise-to-bluebird",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-transform-regenerator",
  ["@babel/plugin-transform-runtime", { "regenerator": true, "corejs": 3 }],
    ["@babel/plugin-transform-modules-commonjs", {
      "allowTopLevelThis": true
    }],
    ["@babel/plugin-transform-async-generator-functions",{"externalHelpers": true}],
    ["@babel/plugin-transform-async-to-generator", {
      "externalHelpers": true
    }]
  ]
}

### Current and expected behavior

If I am using Promise.allSettled directly in my code it gives error: (0 , _bluebird.allSettled) is not a function
If its getting used in 3rd party npm - Tinymce(v7.0.0) https://www.tiny.cloud/docs/tinymce/latest/basic-example/
give error: Promise.allSettled is not a function

### Environment

OS: Windows 10 Pro
Node: v14.5.0
npm: 6.14.5
@babel/cli: "^7.11.6",
@babel/core: "^7.7.5",

### Possible solution

None

### Additional context

![image](https://github.com/user-attachments/assets/9a20c269-857e-4c1d-8e56-67f7b989c45b)

**Comment by nicolo-ribaudo** [comment]
You are using `transform-promise-to-bluebird`, which means "use Bluebird instead of the browser implementation of Promise", and Bluebird does not support .allSettled.

You can either not use Bluebird (and thus remove that plugin), or not use .allSettled.

**Comment by shrutisaluja05** [comment]
Hi Thanks for quick response! transform-promise-to-bluebird we are using for Promise.join. Can we use otherwise using babel?

**Comment by JLHwung** [comment]
You can try replace the bluebird `Promise.join` with `Promise.all`. If you don't observe significant performance regression, you can safely remove the plugin and switch to the native Promise supported by browsers, which will provide `Promise.allSettled`.
