### ISSUE TITLE
🏁 Race of Sloths: The Open Source Developer Challenge is about to start

### ISSUE THREAD

**Issue by akorchyn** [babel/babel#16864]
As a team of Rust developers from [Race of Sloths](https://race-of-sloths.com/),  we recognized this repo to be highly valuable in the open-source movement.

Race of Sloth makes the open-source contributions more fun and rewarding.

* This issue is an invitation to check how Race of Sloths works
* To accept the invitation, comment @race-of-sloths accept
* Once the invitation is accepted, your contributors are eligible participate in the Race
* Contributors just need to mention @race-of-sloths in their PR within your normal contribution flow
* We invite you for collaboration and making open source development more engaging together!

**Comment by nicolo-ribaudo** [comment]
In the past we've received very low quality contributions through other projects that were giving some prizes in exchange for contributions _even in cases where maintainers had to explicitly approve the contributions_.

We are not interested at this time.

**Comment by kungfooman** [comment]
I'm sure the next PR would be a non-working Rust rewrite powered by ChatGPT or Gemini... :sweat_smile:
