### ISSUE TITLE
[Bug]:  Cannot find package @babel/plugin-syntax-dynamic-import since @babel/core 7.25.8

### ISSUE THREAD

**Issue by msev** [babel/babel#16899]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

----

### Configuration file name

babel.config.js

### Configuration

```
module.exports = {
  presets: [
    ['@babel/preset-env', {
      modules: false
    }]
  ],
  plugins: [
    '@babel/plugin-transform-runtime',
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-transform-for-of', {
      assumeArray: true
    }],
    ['@babel/plugin-transform-template-literals', {
      loose: true
    }]
  ]
};
```

### Current and expected behavior

Since version 7.25.8, when I run the `yarn build` command, I get the following error: 

```
ERROR in ./dev/scripts/theme.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-syntax-dynamic-import' imported from ...
```

I have the following dependencies in the package.json file:
```
"@babel/core": "^7.25.8",
"@babel/plugin-transform-runtime": "^7.25.7",
"@babel/preset-env": "^7.25.8",
"babel-loader": "^9.2.1",
```

If I install the `@babel/plugin-syntax-dynamic-import` dependency, this solves the problem and the `yarn build` command runs without error.

On this page https://babeljs.io/docs/babel-plugin-syntax-dynamic-import, the following tip appears:

>You can safely remove this plugin from your Babel config if using @babel/core 7.8.0 or above.

It should therefore not be necessary to add the `@babel/plugin-syntax-dynamic-import` dependency.

### Environment

- babel 7.25.8
- node 20.12.2

**Comment by JLHwung** [comment]
> Error: Cannot find package '@babel/plugin-syntax-dynamic-import' imported from ...

Can you provide the complete error trace? Which package is importing '@babel/plugin-syntax-dynamic-import'?

**Comment by nicolo-ribaudo** [comment]
You are loading that plugin in your babel.config.js file, so you need to add it as a dependency. You were lucky before because it was a transitive dependency of another package you depend on, and so it was available due to npm hoisting.

> You can safely remove this plugin from your Babel config if using @babel/core 7.8.0 or above.

Right, so remove it from your Babel config :)

**Comment by arendondiosa** [comment]
I confirm the solution works! 🔥 
I'm working on a project for ~3 years ago and that error was raised yesterday for the first time.

Thanks @nicolo-ribaudo 👍🏻
