### ISSUE TITLE
[Bug]: Path Error Showing 

### ISSUE THREAD

**Issue by murshidameenpv** [babel/babel#16916]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

/* This file is automatically generated by scripts/generators/tsconfig.js */
{
  "extends": [
    "../../tsconfig.base.json",
    "../../tsconfig.paths.json"
  ],
  "include": [
    "../../eslint/babel-eslint-parser/src/**/*.cts",
    "../../lib/globals.d.ts",
    "../../scripts/repo-utils/*.d.ts"
  ],
  "references": [
    {
      "path": "../../packages/babel-core"
    }
  ]
}

### Configuration

Here is my eslint.config.js
import js from '@eslint/js';
import globals from 'globals';
import babelParser from '@babel/eslint-parser';
import prettierPlugin from 'eslint-plugin-prettier';

export default [
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: babelParser,
      parserOptions: {
        requireConfigFile: false,
        babelOptions: {
          babelrc: false,
          configFile: false,
          presets: ['@babel/preset-env'],
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        process: true,
        __dirname: true,
      },
    },
  },
  {
    files: ['**/*.js'],
    plugins: {
      prettier: prettierPlugin,
    },
    ...js.configs.recommended,
    rules: {
      'prettier/prettier': [
        'error',
        {
          singleQuote: true,
          semi: true,
          tabWidth: 2,
          trailingComma: 'all',
          printWidth: 100,
          bracketSpacing: true,
          arrowParens: 'always',
        },
      ],
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-use-before-define': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'prefer-arrow-callback': 'error',
      'prefer-template': 'error',
      'object-shorthand': 'error',
      'prefer-destructuring': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      'no-throw-literal': 'error',
      'require-await': 'error',
      'no-return-await': 'error',
      'max-len': [
        'error',
        {
          code: 100,
          ignoreComments: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
          ignoreRegExpLiterals: true,
        },
      ],
    },
  },
  {
    files: ['src/**/*.js'],
    rules: {
      'no-console': ['error', { allow: ['error', 'warn'] }],
      'handle-callback-err': 'error',
      'no-buffer-constructor': 'error',
      'no-mixed-requires': 'error',
      'no-path-concat': 'error',
      'consistent-return': 'error',
      'no-param-reassign': 'error',
    },
  },
  {
    files: ['tests/**/*.js', '**/*.test.js', '**/*.spec.js'],
    rules: {
      'no-unused-vars': 'off',
      'no-console': 'off',
      'max-len': 'off',
      'require-await': 'off',
      'max-lines-per-function': 'off',
    },
  },
  {
    files: ['config.js', '*.config.js'],
    rules: {
      'no-console': 'off',
    },
  },
];

### Current and expected behavior

File '/home/murshid/Documents/GitHub/quote_app/node_modules/packages/babel-core' not found.ts
Path to referenced tsconfig or to folder containing tsconfig.
I got this error node_modules/@bable/eslint-parser/tsconfig.json
![Screenshot from 2024-10-19 12-14-49](https://github.com/user-attachments/assets/acac55df-0635-4967-8829-59ab715ef1c9)
Why this error showing ? i reinstalled all the packages 

### Environment

{
  "name": "quote_app",
  "version": "1.0.0",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon server.js"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@babel/core": "^7.25.8",
    "@babel/eslint-parser": "^7.25.8",
    "@babel/preset-env": "^7.25.8",
    "@eslint/js": "^9.13.0",
    "eslint": "^9.13.0",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-prettier": "^5.2.1",
    "prettier": "^3.3.3"
  },
  "dependencies": {
    "globals": "^15.11.0"
  }
}

**Comment by liuxingbaoyu** [comment]
You can temporarily remove `node_modules/@bable/eslint-parser/tsconfig.json`, I will try to fix it.

**Comment by nicolo-ribaudo** [comment]
This started happening in 7.25.3

**Comment by liuxingbaoyu** [comment]
> Does it affect the code if I remove it?

No problem, they shouldn't be published.
