### ISSUE TITLE
[Bug]: Possible conflict between module:metro-react-native-babel-preset and stage 3 decorators

### ISSUE THREAD

**Issue by guyca** [babel/babel#16921]
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
import { inject, injectable } from "react-obsidian";
import { MainGraph } from "./graph";

@injectable(MainGraph)
export class Main {
  @inject() foo!: String;

  static displayName = 'Main';

  print() {
    console.log(`injected {foo: ${this.foo}} into ${Main.displayName}`);
  }
}

new Main().print();
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  retainLines: true,
  presets: [
    'module:metro-react-native-babel-preset',
  ],
  plugins: [
    '@babel/plugin-transform-flow-strip-types',
    'react-obsidian/dist/transformers/babel-plugin-obsidian',
    ['@babel/plugin-proposal-decorators', { version: '2023-11' }],
    '@babel/plugin-transform-class-static-block',
    ['@babel/plugin-transform-class-properties', { loose: true }],
    ['@babel/plugin-proposal-private-methods', { loose: true }]
  ],
};
```

### Current and expected behavior

Current behavior: `_initClass` isn't initialized and that `_applyDecs` isn't called at all. I get a runtime error when running the code example above:

```
/Users/guyc/workspace1/babel-decorators-static-fields-repro/dist/index.js:8
displayName='Main',(0,_assertThisInitialized2.default)(_this),_initClass();return _this;}(0,_inherits2.default)(_class,_identity2);return(0,_createClass2.default)(_class);}(_identity))();
                                                              ^

TypeError: _initClass is not a function
    at new _class (/Users/guyc/workspace1/babel-decorators-static-fields-repro/dist/index.js:8:63)
    at Object.<anonymous> (/Users/guyc/workspace1/babel-decorators-static-fields-repro/dist/index.js:2:4120)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
```

### Environment

  System:
    OS: macOS 14.6.1
  Binaries:
    Node: 20.16.0
    Yarn: 4.3.1
    npm: 10.8.1

### Possible solution

I don't think this is a bug in Babel, rather conflicting configurations / missing configurations issue on my end.

### Additional context

* I wasn't able to create a REPL, but did public a reproduction to GitHub - https://github.com/guyca/babel-decorators-static-fields-repro.
* Issue doesn't reproduce when I use the following presets:
  ```js
    presets: [
      ['@babel/preset-env', { targets: { node: 'current' } }],
      ['@babel/preset-typescript']
    ]
  ```
* I wasn't able to print the resolved config using `BABEL_SHOW_CONFIG_FOR` 😕

**Comment by JLHwung** [comment]
Please enable the `allowDeclareFields` option so that the the property `foo` is indeed defined as a class property, otherwise it will be removed, this is unfortunately the behaviour of legacy flow/ts versions.

```js
module.exports = {
  plugins: [
    ['@babel/plugin-transform-flow-strip-types', { allowDeclareFields: true }]
  ]
}
```

**Comment by guyca** [comment]
WOW thank you so much! I've been banging my head over this for a while! Thank you ❤️

**Comment by JLHwung** [comment]
Thank you for reporting this issue. The `allowDeclareFields` option will be enabled by default in Babel 8, hopefully future users don't have to even be aware of this option.
