### ISSUE TITLE
metadataUsedHelpers deprecation warning

### ISSUE THREAD

**Issue by guybedford** [babel/babel#1694]
This is breaking builds in jspm unfortunately - see https://github.com/jspm/jspm-cli/issues/809. Is there anyway it can just be a logged warning instead of a breaking error?

I can post a patch as well though no problem too.

**Comment by sebmck** [comment]
I could've sworn this is what it did in the first place, sorry for the hassle.

**Comment by sebmck** [comment]
Fixed as of 5.5.4, thanks!

**Comment by guybedford** [comment]
Great, thanks so much!
