### ISSUE TITLE
"Unknown option: attachAuxiliaryComment" when running with istanbul

### ISSUE THREAD

**Issue by clark800** [babel/babel#1695]
Looks like this commit breaks the ability to run with istanbul: https://github.com/babel/babel/commit/ff8d90061fb72468e6780e7730ac4695a5f2c292#diff-ed7b2f9b60919cc513f080c47ff3eaf5R101

**Comment by sebmck** [comment]
Fixed as of 5.5.4, thanks!

**Comment by clark800** [comment]
Awesome, thanks for the fast response!
