### ISSUE TITLE
Feature: emit flow comments derived from flow type hints

### ISSUE THREAD

**Issue by ide** [babel/babel#1698]
Babel currently strips out flow type hints, which means that the emitted code can't be fully type checked by flow. Since most flow code is preprocessed before publishing to npm, this means it's usually not possible to fully type check packages downloaded from npm. The flow team added support for type hints in JS comments to address this (blog post: http://flowtype.org/blog/2015/02/20/Flow-Comments.html). Preferably Babel would emit these comments instead of discarding the type hints. This isn't urgent and is hopefully somewhat easy to add (it mostly looks like wrapping token runs in comments) but I thought it'd be good to have since Facebook's projects are using Babel now.

cc @glevi @mroch

**Comment by sebmck** [comment]
I wrote a plugin for this but forgot to post it:

```javascript
module.exports = function (babel) {
  var t = babel.types;

  function commentify(path) {
    var comment = path.getSource();
    if (comment[0] !== ":") comment = ":: " + comment;
    path.addComment("trailing", comment);
    path.replaceWith(t.noop());
  }

  return new babel.Transformer("flow-comments", {
    FlowDeclaration: function () {
      this.addComment("leading", ":: " + this.getSource());
      this.dangerouslyRemove();
    },

    Flow: function () {
      commentify(this);
    }
  });
};
```

Let me know if you test it as I'll chuck it up in a repo soon. It currently doesn't handle optional parameters and a few other things probably.

**Comment by ide** [comment]
It seems to mostly work. I found a couple bugs that I'll jot down here so they're not forgotten:

---

Comments in the type declarations are not escaped. For example:
```js
type CustomType = {
/** This is some documentation. */
name: string;
};
```
is emitted as:
```js
/*:: type CustomType = {
/** This is some documentation. */
name: string;
};*/
```

---

Consecutive type declarations are emitted on the same line and are hard to read:
```js
type A = number;
type B = {
  name: string;
};
```
becomes:
```js
/*:: type A = number;*/ /*:: type B = {
                          name: string;
                        };*/
```

---

Comments inside of the type declarations are emitted again at the bottom of the file. So this:
```js
type CustomType = {
/** This is some documentation. */
name: string;
};
```
actually becomes this:

```js
/*:: type CustomType = {
/** This is some documentation. */
name: string;
};*/

...

/** This is some documentation. */
```

**Comment by hzoo** [comment]
using `exit` fixes the 2nd issue (Consecutive type declarations are emitted on the same line and are hard to read:)

```js
Flow: {
      exit: function() {
        commentify(this);
      }
    }
```

Also it seems that you don't need the `FlowDeclaration` and it still will add the comments?

**Comment by sebmck** [comment]
I've created the repo [babel-plugins/babel-plugin-flow-comments](https://github.com/babel-plugins/babel-plugin-flow-comments) and published the plugin to npm. I've opened issues for all known problems so I'll move the conversation over there. @hzoo @ide I can add the both of you to the repo if you're interested :smile:

**Comment by hzoo** [comment]
alright - I can add some tests for the issues

**Comment by ide** [comment]
Thanks for opening up those issues @sebmck, awesome
