### ISSUE TITLE
Add support of Promise.withResolvers in preset-env

### ISSUE THREAD

**Issue by WangLeto** [babel/babel#16986]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

.babelrc
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "safari >= 12",
        "useBuiltIns": "usage",
        "corejs": "3"
      }
    ]
  ]
}
```

source
```
Promise.withResolvers();
```

output
```
"use strict";

Promise.withResolvers();
```

### Describe the solution you'd like

Support the transpilation of Promise.withResolvers.

### Describe alternatives you've considered

.

**Comment by liuxingbaoyu** [comment]
Could you try ` "corejs": "3.39"`?
![image](https://github.com/user-attachments/assets/60de4f32-26bc-4915-9b32-96398f440143)

**Comment by WangLeto** [comment]
@liuxingbaoyu It works!

**Comment by Svish** [comment]
@liuxingbaoyu Sorry, but I'm curious what output that's from?

We're seeing errors about "Promise.withResolvers is not a function." from for example Mobile Safari 16.6, but according to our babel and browserslist config my understanding is that it should not have been an issue:

```json
// babel.config.json
{
  "presets": [
    [
      "@babel/preset-react",
      {
        "runtime": "automatic"
      }
    ],
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": { "version": "3.40", "proposals": true }
      }
    ],
    "@babel/preset-typescript"
  ]
}
```

```
# .browserslistrc
defaults
cover 95% in NO
not dead
```

Is there a way for me to "debug" our babel and browserslist config to see what's taken care of and not?

**Comment by nicolo-ribaudo** [comment]
You can pass `debug: true` to `preset-env`'s options

**Comment by Svish** [comment]
Cool, thanks, I will try that out 😊
