### ISSUE TITLE
Issues with global `this`

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#1700]
First I tried 
```js
'use strict';
console.log({[this.document.name]: 'me'});
```
Which in the computed property name context of `this` was not global.

Then I tried
```js
this.name = 'name'

console.log({[this.name]: 'me'})
```
and noticed the global `this` is undefined: 

> Cannot set property 'name' of undefined

**Comment by sebmck** [comment]
See the [FAQ](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-) as well as previous issues: #1667, #1573, #562, #814, #730 and #733.
