### ISSUE TITLE
[Bug]: @babel/core@"7.25.2" from @angular/localize@18.2.13 spill debug npm package into prod builds

### ISSUE THREAD

**Issue by The-Duuude-dot** [babel/babel#17003]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

include @angular/localize in your package.json as a dependencies.

npm -i
npm explain debug | grep @angular/localize 

### Current and expected behavior

Current behavior:

```
npm explain debug | grep @angular/localize
      peer @angular/compiler-cli@"18.2.13" from @angular/localize@18.2.13
      node_modules/@angular/localize
        dev @angular/localize@"^18.2.13" from the root project
        peerOptional @angular/localize@"^18.0.0" from @angular-devkit/build-angular@18.2.12
        peerOptional @angular/localize@"^18.0.0" from @angular/build@18.2.12
    @babel/core@"7.25.2" from @angular/localize@18.2.13
    node_modules/@angular/localize
      dev @angular/localize@"^18.2.13" from the root project
      peerOptional @angular/localize@"^18.0.0" from @angular-devkit/build-angular@18.2.12
      peerOptional @angular/localize@"^18.0.0" from @angular/build@18.2.12
        peer @angular/compiler-cli@"18.2.13" from @angular/localize@18.2.13
        node_modules/@angular/localize
          dev @angular/localize@"^18.2.13" from the root project
          peerOptional @angular/localize@"^18.0.0" from @angular-devkit/build-angular@18.2.12
          peerOptional @angular/localize@"^18.0.0" from @angular/build@18.2.12
      @babel/core@"7.25.2" from @angular/localize@18.2.13
      node_modules/@angular/localize
        dev @angular/localize@"^18.2.13" from the root project
        peerOptional @angular/localize@"^18.0.0" from @angular-devkit/build-angular@18.2.12
        peerOptional @angular/localize@"^18.0.0" from @angular/build@18.2.12`
```

Current behavior:
Babel Core does not use spill debug package in prod build

### Environment

- angulat 18
- node 20
- npm 10

### Additional context

The question could also be, is that ok that a production package like @angular/localizepulls babel/core, if babel/core has been designed to only be a dev depenency ( is that the case?)

**Comment by nicolo-ribaudo** [comment]
I'm not sure I understand this question. The `debug` package is needed to collect logs in case of bugs not when we are developing Babel, but when Babel's users are using it.

**Comment by The-Duuude-dot** [comment]
Ok, thank you for the explanation why we have the debug package in production builds.
Given the name, we had doubts whether it should be in production builds, but now you gave us the rationale and thank you for that.

The thing with this package seems to suffer from the following vuln: Category CWE-1333 | Inefficient Regular Expression Complexity

CVE Details
Published: Dec 10, 2020
In NPM debug, the enable function accepts a regular expression from user input without escaping it. Arbitrary regular expressions could be injected to cause a Denial of Service attack on the user's browser, otherwise known as a ReDoS (Regular Expression Denial of Service). This is a different issue than https://github.com/advisories/GHSA-gxpj-cx7g-858c.


Does this CVE applies to debug package ?

**Comment by The-Duuude-dot** [comment]
https://github.com/debug-js/debug/issues/982

**Comment by The-Duuude-dot** [comment]
Just FYI @alan-agius4 , I filed a bug at debug's github repo.
The guy has already been warned many times but keeps closing Issues.
For example mine was closed:  https://github.com/debug-js/debug/issues/982.
I elaborated on why it must be tackled, and a likely pretty easy solution: https://github.com/debug-js/debug/issues/957

Let's see if he closes it too.

The thing is that with SCA tools, all of your packages now has a lot of high vulns ...

**Comment by nicolo-ribaudo** [comment]
Babel doesn't call the `enable()` method of `debug` with user-provided inputs, and as such it is not affected by that "vulnerability".

**Comment by nicolo-ribaudo** [comment]
The solution is that that vulnerability should not exist at all. It's not a security bug in the `debug` package -- it's a security bug when you pass untrusted input to its enable function (which is meant to receive tokens defined by the app developer, and not random user input).

Unfortunately it seems like Checkmarx is not a serious product, warning about what's easy to warn about for them rather than about where the actual problem lies, due causing a ton of false positives.
