### ISSUE TITLE
[Bug]: Error: Cannot find module '@jridgewell/gen-mapping'

### ISSUE THREAD

**Issue by Pswzy** [babel/babel#17015]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

null

### Current and expected behavior

webpack build error ,because  @ampproject/remapping has a error npm package : "@jridgewell/gen-mapping": "0.3.6"

### Environment

@babel/core@7.25.8

**Comment by Pswzy** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'

**Comment by jridgewell** [comment]
I've already reset the latest version of gen-mapping back to 0.3.5. You just need to rerun your package manager to update to latest.

**Comment by funny99** [comment]
error: \.pnpm\@babel+generator@7.26.3\node_modules\@jridgewell\gen-mapping\dist\gen-mapping.umd.js

**Comment by funny99** [comment]
Can‘t find which pkg version Influence it，The following are my dependency packages：

**Comment by tracyxu5298** [comment]
@babel/core 更新到7.26后，依然报错  Module build failed: /home/jenkins/agent/workspace/@jridgewell/gen-mapping/dist/gen-mapping.umd.js:

**Comment by nicolo-ribaudo** [comment]
@jridgewell Should we temporarily pin the version of your packages?

**Comment by jridgewell** [comment]
No, there's no need. If you `npm i @babel/core @babel/cli` you'll download `@jridgewell/gen-mapping@0.3.5`. Same if you just `npm i @jridgewell/gen-mapping`.
