### ISSUE TITLE
Runtime's regenerator version

### ISSUE THREAD

**Issue by UltCombo** [babel/babel#1701]
# Current situation

Let `y` be a valid (exact) semver version number.
Babel itself depends on `regenerator@^y`, while babel-runtime implicitly "depends on" (uses a compiled version of) `regenerator@y`.

When a new backwards-compatible (patch/minor) version of Regenerator is published, babel-core will use the newer version while babel-runtime will still be using an older version of Regenerator. This results in issues such as #1685.

# Case 1 - already published packages

Let `x` be a valid (exact) semver version number.
Assume a published package `pkg`, whose source code has been generated with babel-core version `x`, having `babel-runtime@^x` set as dependency.

**Result:** the compiled code will always stay the same, the runtime may be updated in a backwards-compatible way (when Regenerator publishes a new version, and babel-runtime does so as well). There should be no problem in this scenario, as long as both Regenerator and babel-runtime respect the semver semantics.

# Case 2 - development/CI

Assume a development/test environment where a given package's entire dependency graph is up to date (respecting semver ranges). This package depends on `babel-core` and `babel-runtime`.

In the timeframe between a Regenerator release and a babel-runtime release, the babel-core will use a more recent Regenerator version than babel-runtime, which may result in broken builds (#1685).

# Possible solutions

1. Make babel-runtime pull the latest backwards-compatible Regenerator version, that is, set `regenerator@^y` as a dependency and run the `runtime` transform on it on post-install. **Problem:** `npm update` and such may not work correctly as it will not trigger babel-runtime's postinstall inscript.

1. Make babel-core and babel-runtime depend on an exact version of Regenerator. **Problem:** bumping the dependency version manually is annoying.

Is there a better solution?

**Comment by sebmck** [comment]
> Babel itself depends on `regenerator@^y`, while babel-runtime implicitly "depends on" (uses a compiled version of) `regenerator@y`.

[No it doesn't.](https://github.com/babel/babel/blob/master/package.json#L54)

**Comment by UltCombo** [comment]
Oh you've changed this in the last 24 hours? Guess I missed it. :smile:

**Comment by UltCombo** [comment]
Oh, actually it has been 34 hours ago. https://github.com/babel/babel/commit/c26fd7a819f564f8ce1072d0ec7e52615745d7f9
