### ISSUE TITLE
Named Arrow Functions (function expression) support

### ISSUE THREAD

**Issue by MadLittleMods** [babel/babel#1702]
Example from [*ES6: arrow functions and method definitions* on 2ality](http://www.2ality.com/2012/04/arrow-functions.html)

Right now the following snippet throws a unexpected token error [in the babel playground](https://goo.gl/uGXoJy).

```
let fac = me(n) => {
	if (n <= 0) {
		return 1;
	} else {
		return n * me(n-1);
	}
};
```

**Comment by sebmck** [comment]
That blog post is from 2012 and is extremely out of date. That is not valid syntax.

**Comment by MadLittleMods** [comment]
Sorry, thank you for the prompt reply :)
