### ISSUE TITLE
[Bug]: error Error: https://registry.yarnpkg.com/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.22.5.tgz: Request failed "304 Not Modified"

### ISSUE THREAD

**Issue by rathodrajnesh** [babel/babel#17029]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

Just today we start receiving error of babel helper-annotate-as-pure request failed error:  while performing yarn

error Error: https://registry.yarnpkg.com/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.22.5.tgz: Request failed "304 Not Modified"

![image](https://github.com/user-attachments/assets/0cd0206a-e8a9-45de-9e60-a806931da602)

I am using angular 16 and having following dependency

please suggest a quick fix.

### Configuration file name

package.json

### Configuration

"dependencies": {
        "@angular/animations": "16.2.12",
        "@angular/cdk": "16.2.12",
        "@angular/common": "16.2.12",
        "@angular/compiler": "16.2.12",
        "@angular/core": "16.2.12",
        "@angular/forms": "16.2.12",
        "@angular/platform-browser": "16.2.12",
        "@angular/platform-browser-dynamic": "16.2.12",
        "@angular/router": "16.2.12",
        "@fortawesome/fontawesome-free": "^6.2.0",
        "@nobilex/shared-lib": "19791.0.7",
        "@odymaui/angular-tree-component": "^16.0.4",
        "@popperjs/core": "^2.11.8",
        "@sentry/browser": "5.12.1",
        "@stomp/rx-stomp": "^1.1.4",
        "@stomp/stompjs": "^6.1.2",
        "@types/js-yaml": "3.12.2",
        "@types/memoizee": "^0.4.8",
        "@types/mixpanel-browser": "^2.49.0",
        "@types/uuid": "3.4.7",
        "@types/ws": "8.5.4",
        "angular2-hotkeys": "^16.0.1",
        "flatpickr": "4.6.3",
        "ibantools": "2.2.0",
        "is-docker": "2.0.0",
        "js-joda": "1.11.0",
        "keycloak-js": "14.0.0",
        "lodash": "4.17.15",
        "memoizee": "^0.4.15",
        "mixpanel-browser": "^2.49.0",
        "ng2-pdf-viewer": "^9.0.0",
        "ngx-infinite-scroll": "^17.0.0",
        "ngx-quill": "17.0.0",
        "product-fruits": "^1.0.15",
        "quill": "^1.3.7",
        "rxjs": "^7.8.1",
        "sockjs-client": "^1.6.1",
        "tachyons": "4.11.1",
        "tachyons-sass": "4.9.3",
        "tslib": "^2.1.0",
        "update": "0.7.4",
        "uuid": "7.0.3",
        "zone.js": "~0.13.3"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "16.2.10",
        "@angular-eslint/builder": "^16.3.1",
        "@angular-eslint/eslint-plugin": "^16.3.1",
        "@angular-eslint/eslint-plugin-template": "^16.3.1",
        "@angular-eslint/schematics": "16.3.1",
        "@angular-eslint/template-parser": "^16.3.1",
        "@angular/cli": "16.2.10",
        "@angular/compiler-cli": "16.2.12",
        "@angular/language-service": "16.2.12",
        "@types/jasmine": "~3.6.0",
        "@types/jasminewd2": "2.0.8",
        "@types/lodash": "4.14.149",
        "@types/mime": "^4.0.0",
        "@types/node": "13.7.1",
        "@types/office-js": "1.0.75",
        "@types/quill": "^1.3.10",
        "@types/sockjs-client": "^1.5.1",
        "@typescript-eslint/eslint-plugin": "^5.59.2",
        "@typescript-eslint/parser": "^5.59.2",
        "eslint": "^8.39.0",
        "eslint-plugin-deprecation": "^1.5.0",
        "husky": "^4.2.5",
        "jasmine-core": "~4.1.0",
        "karma": "~6.3.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~5.0.0",
        "karma-jasmine-html-reporter": "~1.7.0",
        "ng-packagr": "^16.2.3",
        "sass-migrator": "^1.7.3",
        "ts-node": "8.3.0",
        "typescript": "4.9.5"
    },

### Current and expected behavior

yarn is getting failed due to above error

it should complete without error

### Environment

Ubuntu

**Comment by nicolo-ribaudo** [comment]
This is an issue either with the yarnpkg registry or with your package manager, it's out of our control.
