### ISSUE TITLE
Unknown option: retainLines

### ISSUE THREAD

**Issue by tontonskie** [babel/babel#1703]
I'm using gulp-babel and it's showing me error 

Unknown option: retainLines

**Comment by sebmck** [comment]
Full stack trace and babel version number please.

**Comment by sebmck** [comment]
Closing due to lack of reproducible example.

**Comment by zyklus** [comment]
Suggest re-opening:

```shell
➜  ~  babel --version
5.8.21 (babel-core 5.8.22)

➜  ~  babel --retainLines

  error: unknown option `--retainLines'
```

**Comment by sebmck** [comment]
--retain-lines
