### ISSUE TITLE
Module exports should be pure string-keyed map

### ISSUE THREAD

**Issue by RReverser** [babel/babel#1714]
According to http://people.mozilla.org/~jorendorff/es6-draft.html#sec-module-namespace-exotic-objects-getprototypeof, module objects should have `null` prototype.

Current export for CommonJS is:
```javascript
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

Which does not change prototype of exports to `null` and thus module also exposes native `Object.prototype.*` methods as exports which might be unwanted and unexpected.

I propose to generate following code instead:
```javascript
exports = module.exports = Object.create(null, {
  __esModule: { value: true }
});
```

This won't make any negative impact on output size nor performance, while would allow to follow the spec more closely.

**Comment by sebmck** [comment]
To make the reasoning for this change more compelling, do you have any examples of production code where this would be an issue? Also AFAIK, this only effects `import * as foo from "foo";` so all that would be required would be for [templates/helper-interop-require-wildcard.js](https://github.com/babel/babel/blob/master/src/babel/transformation/templates/helper-interop-require-wildcard.js) to be modified to return a new object with `Object.create(null);`.

**Comment by RReverser** [comment]
Mostly just prevention from errors - I had helper named `toString` (I know, I know :P) which was being imported from wrong module but everything silently worked... to some point.
