### ISSUE TITLE
auxiliaryComment before and after

### ISSUE THREAD

**Issue by phated** [babel/babel#1721]
First off, I'd like to say that the `auxiliaryComment` options is very cool.

However, I'm trying to use it with the `Lab` testing framework, which needs a comment before *and* after the block of code to ignore in their coverage report.  Would it be possible to add an option to add a comment after each helper block?

Thanks!

**Comment by sebmck** [comment]
I'm hesitant on extending the functionality of `auxiliaryComment` since maintaining it is a nightmare as there's a lot of dynamically inserted nodes and it's quite painful to have to add so many checks.

**Comment by phated** [comment]
Thanks. I can understand how much of pain this type of thing is. Before reaching out, I tried to implement something similar to `istanbul skip next` in lab but didn't think it would be possible due to the architecture. I appreciate you adding this.
