### ISSUE TITLE
babel-node parameters (e.g. --help, --debug) do not forward properly

### ISSUE THREAD

**Issue by gajus** [babel/babel#1730]
When used together with [commander](https://www.npmjs.com/package/commander), commands such as `--help` or `--debug` are being caught by `babel` before their passed to the program, e.g.

```js
'use strict';

let commander = require('commander'),
    command;

command = commander
    .command('foo')
    .description('bar')
    .option('--debug', 'Parameter that should enable debug.')
    .action((env) => {
        
    });

commander.parse(process.argv);
```

Executing this program using `--debug` flag will enable `node` debug mode:

```sh
curiosity:2015 01 07 mirror gajus$ babel-node ./src/bin/parser.js foo --debug
Debugger listening on port 5858
env { commands: [],
  options:
   [ { flags: '--debug',
       required: 0,
       optional: 0,
       bool: true,
       long: '--debug',
       description: 'Parameter that should enable debug.' } ],
  _execs: [],
  _allowUnknownOption: false,
  _args: [],
  _name: 'foo',
  _noHelp: false,
  parent:
   { commands: [ [Circular] ],
     options: [],
     _execs: [],
     _allowUnknownOption: false,
     _args: [],
     _name: 'parser',
     Command: [Function: Command],
     Option: [Function: Option],
     _events: { foo: [Function] },
     _eventsCount: 1,
     rawArgs:
      [ 'node',
        '/Users/gajus/Documents/dev/redbee/2015 01 07 mirror/src/bin/parser.js',
        'foo' ],
     args: [ [Circular] ] },
  _description: 'bar',
  _events: { debug: [Function] },
  _eventsCount: 1 }
```

**Comment by gajus** [comment]
Appears to be a known issue, https://github.com/babel/babel/issues/836.

**Comment by gajus** [comment]
This makes it impossible to work with some script, specifically a script that requires "debug" flag. Is there a workaround?

**Comment by AluisioASG** [comment]
I ran across a similar issue yesterday.  Can you try ` babel-node -- ./src/bin/parser.js foo --debug`?

**Comment by gajus** [comment]
That only pops a value of one of the parameters.

**Comment by gajus** [comment]
As it says in a comment by @sebmck (https://github.com/babel/babel/issues/836#issuecomment-75135408), unless you replace commander with something else to interpret CLI parameters, this cannot be fixed.

**Comment by gajus** [comment]
I had a look at `commander` use in babel-cli, and [given that its used vaguely for anything](https://github.com/babel/babel/search?utf8=%E2%9C%93&q=commander), it would be a fairly straightforward change to make.

**Comment by gajus** [comment]
Actually, I am wrong. I [see](https://github.com/babel/babel/blob/8201ea0aa202db4825584c7f855cf4f444791312/packages/babel-cli/bin/babel-node#L14) why you have suggested that I try adding `--`. Important to note is that `--` must be included after `babel-node` arguments. In my case, I have tried adding it just after `babel-node`, in a context of `babel-node -- --stage 0 ./foo --debug`

**Comment by gajus** [comment]
Lets have a look at the issues with the current implementation.

https://github.com/babel/babel/blob/8201ea0aa202db4825584c7f855cf4f444791312/packages/babel-cli/bin/babel-node#L16

```js
userArgs  = babelArgs.slice(argSeparator); // including the  --
```

This should be:

```js
userArgs  = babelArgs.slice(argSeparator + 1);
```

There is no reason to include the `---` separator into user arguments.

**Comment by gajus** [comment]
[`userArgs` declaration](https://github.com/babel/babel/blob/8201ea0aa202db4825584c7f855cf4f444791312/packages/babel-cli/bin/babel-node#L11) should start with empty array (variable value type consistency).

```js
var userArgs = [];
```

**Comment by sebmck** [comment]
Reopening #859 in favor of this issue.
