### ISSUE TITLE
Duplication of files during build

### ISSUE THREAD

**Issue by dcherman** [babel/babel#1731]
When you're passing multiple files/globs to babel that will be built into a single file, is it possible to eliminate duplicate file paths in the resulting build rather than duplicating the contents?

I'm trying to influence the ordering of some files where the order is important, so I have a command that looks like this:

```js
babel -s -c false --out-file tmp/built.js --ignore *.spec.js src/module.js "src/**/*.js"
```

At the moment, `module.js` would be included as the first file, then duplicated again when the second glob matches it.  Ideally, the file would only be included the first time it was encountered.

**Comment by sebmck** [comment]
Files need to be ran through `uniq` or something [here](https://github.com/babel/babel/blob/master/packages/babel-cli/bin/babel/index.js#L81-85).

**Comment by jmm** [comment]
@sebmck If you want to increase contributorship here I want to suggest that maybe a `good first contribution` label (in addition to `help wanted`) could be helpful and that this seems like a good fit for it.

**Comment by sebmck** [comment]
@jmm Good idea :) Done!
