### ISSUE TITLE
Simplify template strings by removing unnecessary empty strings whenever possible.

### ISSUE THREAD

**Issue by Dashed** [babel/babel#1732]
```js
`${foo}bar`;
``` 
renders to 

```js
"" + foo + "bar";
```

But the empty string concatenation in the beginning is not necessary:

```js
foo + "bar";
```

REPL: https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=%60%24%7Bfoo%7Dbar%60%3B%0A%0A%60bar%24%7Bfoo%7D%60%3B

**Comment by sebmck** [comment]
Something similar to [this](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/es6/template-literals.js#L61) line needs to be added, being careful to only do it for nodes of `length > 1`.

**Comment by mathieumg** [comment]
https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=const%20foo%20%3D%205%3B%0Aconst%20bar%20%3D%2010%3B%0A%0Aconst%20example%20%3D%201%20%2B%20%60%24%7Bfoo%7D%24%7Bbar%7D%60%3B

Intuitively looking at the code, `example` would be `"1510"`, but with the "fix" mentioned above, `example` would become `16`, no?.

**Comment by sebmck** [comment]
@mathieumg No? What makes you think that?

**Comment by RReverser** [comment]
@mathieumg seems right - if you remove `""` at the beginning, no coercion to string happens and, for example, `` `${foo}` `` will be converted directly to `foo` and thus `5`. So `` 1 + `${foo}` `` will be `6` and not `"15"`.

**Comment by sebmck** [comment]
This is why I mentioned

>  being careful to only do it for nodes of `length > 1`.

**Comment by RReverser** [comment]
Ah, I thought you were referencing to original `length`. Ok.

**Comment by mathieumg** [comment]
> Ah, I thought you were referencing to original length

So did I, that's why I put both `foo` and `bar`. @hzoo put my example as a test in https://github.com/hzoo/babel/tree/2c57f925031afc3519176815472a6ca80a402f58/test/core/fixtures/transformation/es6.template-literals/expression-first, so if that passes the implementation must be right. :+1: Sorry for the confusion.

**Comment by RReverser** [comment]
Looking at https://github.com/hzoo/babel/blob/2c57f925031afc3519176815472a6ca80a402f58/test/core/fixtures/transformation/es6.template-literals/expression-first/expected.js - and thinking that moreover, we could generalize this to remove all the empty string literals in between but leave one at the beginning.

**Comment by Dashed** [comment]
@RReverser I actually like that idea.

**Comment by hzoo** [comment]
Ok @RReverser @Dashed tried to implement that instead

Doesn't seem like I need to add a check if the first node is a string right? (it didn't change any tests)
```js
// make sure the first node is ""
if (!(t.isLiteral(nodes[0]) && isString(nodes[0].value))) {
  nodes.unshift(t.literal(""));
}
```

**Comment by RReverser** [comment]
Yeah, first node should always be a string.
Also, instead of one-by-one splice you could just go with `.filter`.

**Comment by hzoo** [comment]
Ok went ahead and changed to filter.

**Comment by benjamingr** [comment]
I'd like to see a test that shows that `${foo}${bar}` where foo and bar are `1` and `2` respectively doesn't become `3` and correctly becomes `"12"`.
