### ISSUE TITLE
Duplicate Object Key in alias-keys

### ISSUE THREAD

**Issue by grncdr** [babel/babel#1734]
The key `JSXEmptyExpression` is duplicated in `alias-keys.json`. This file is converted to JavaScript in browserification, and evaluating _that_ source in strict mode causes an exception to be thrown. 

https://github.com/babel/babel/blob/8055ce29f7dbbc8564087f01fa11a34d9d258a33/src/babel/types/alias-keys.json#L79

https://github.com/babel/babel/blob/8055ce29f7dbbc8564087f01fa11a34d9d258a33/src/babel/types/alias-keys.json#L119

**Comment by sebmck** [comment]
PR? This shouldn't be an issue unless you're preprocessing the Babel source for some reason and adding strict mode (dunno why).
