### ISSUE TITLE
Spread operator doesn't unwrap generators and other iterable objects

### ISSUE THREAD

**Issue by awalGarg** [babel/babel#1735]
So AFAIK, the `...` spread operator should be unwrapping not just arrays but also any iterable object like generators etc. [relevant spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-array-initializer).

If it is not so, I am stupid and you can close this issue.

Else, babel is not doing that. [relevant fiddle](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=function%20*%20foo%20()%20%7B%0A%20%20yield%205%3B%0A%7D%0A%0Alet%20gen%20%3D%20foo()%3B%0A%0Alet%20arr%20%3D%20%5B...gen%5D%3B%0A%0Aconsole.log(arr%5B0%5D%20%3D%3D%3D%205)%3B).

Firefox logs `true` natively, OTOH.

I couldn't find any other relevant issue or this behavior documented anywhere so I put this here.
Thanks :)

**Comment by Dashed** [comment]
This works (loose mode **off**): http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20*%20foo%20()%20%7B%0A%20%20yield%205%3B%0A%7D%0A%0Alet%20gen%20%3D%20foo()%3B%0A%0Alet%20arr%20%3D%20%5B...gen%5D%3B%0A%0Aconsole.log(arr)%3B

**Comment by loganfsmyth** [comment]
@Dashed is correct. See the loose mode caveats, http://babeljs.io/docs/advanced/loose/, for `es6.spread`.

**Comment by awalGarg** [comment]
Ahh nice, thanks! :)
