### ISSUE TITLE
string.endsWith is not transpiled

### ISSUE THREAD

**Issue by clark800** [babel/babel#1739]
Running `babel --optional runtime script.js` where script.js contains `'a'.endsWith('a');` outputs

```
'use strict';

'a'.endsWith('a');
```

The result is the same without `--optional runtime`.

**Comment by sebmck** [comment]
This is expected behaviour. Those methods can't be statically determined to always reference strings so cannot be replaced to reference the `babel-runtime`.

**Comment by sebmck** [comment]
You can however use the included [polyfill](http://babeljs.io/docs/usage/polyfill).

**Comment by clark800** [comment]
I was thinking that the `--optional runtime` flag would automatically handle the polyfill since the docs say "Built-ins such as Promise, Set and Map are aliased to core-js so you can use them seamlessly without having to require a globally polluting polyfill."

Is there a reason why the runtime can't automatically handle the polyfill?

**Comment by sebmck** [comment]
> I was thinking that the --optional runtime flag would automatically handle the polyfill since the docs say

Those are built-ins, those are instance methods.

> Is there a reason why the runtime can't automatically handle the polyfill?

Nope, unfortunately. As I said before:

> Those methods can't be statically determined to always reference strings so cannot be replaced to reference the `babel-runtime`.

**Comment by clark800** [comment]
Well I was thinking along the lines of adding `require('polyfill');` to the top of every processed file and having a runonce check at the top of the polyfill file, which wouldn't require any static analysis.

But is there some reason why that's not good?

It's a bit confusing when the docs for `runtime` say "you can use built-ins such as Promise, Set, Symbol etc *as well use as all the Babel features that require a polyfill* seamlessly, without global pollution, making it extremely suitable for libraries."
