### ISSUE TITLE
Arrow functions inside object literals

### ISSUE THREAD

**Issue by Lokeh** [babel/babel#1742]
When I write an ES6 arrow function and transpile it to ES5, here's what happens
``` javascript
// ES6 code
this.B = 2;
const addB = (a) => a + this.B;

// Transpiled code
this.B = 2;
_this = this;
var addB = function (a) {
    return a + _this.B;
};
```
This behaves as expected in regards to lexically scoping `this` inside the arrow function. However, when I use an arrow function in an object literal:

```javascript
// ES6 code
const someObj = {
    B: 2,
    addB: (a) => a + this.B // referring to someObj's `this`
};

// Transpiled code
var _this = this;
const someObj = {
    B: 2,
    addB: function (a) { return a + _this.B; } // refers to _this outside of someObj
};
```

I would assume that the `this` inside of the arrow function should refer to the this inherited from the object.

I found a tangentially related bug report in the io.js project that at least seems to infer that arrow functions should work as I would expect inside of object literals: https://github.com/nodejs/io.js/issues/735

**Comment by sebmck** [comment]
[Just responded to you on Reddit](https://www.reddit.com/r/javascript/comments/39qs7e/es6_arrow_functions_inside_object_literals/cs5m1xr). Yes, Babel is behaving correctly. Why would the behaviour of arrow functions differ in an object literal? The io.js issue you linked to says that V8s implementation was buggy and not spec compliant (which was why it's behind a flag).

**Comment by Lokeh** [comment]
I think I understand why it was confusing to me; the same reason why `this` is always confusing to beginners, it changes depending on context.

in my head, I was thinking that with something like:
```javascript
const someObj = {
    someFunc() { return this; },
    someArrow: () => this
};
```
That `someObj.someFunc()` would return a `this` scoped to someFunc, and that `someObj.someArrow()` would return the `this` scoped to someObj.
 
But I'm wrong. When inside an object literal, every functions `this` is scoped to the object, and the arrow function specifically breaks out of the scope of the containing function, so the arrow functions `this` should refer to the parent scope (outside of the object).

Typical developer blaming the tool! Sorry for the hassle. At least I learned something - or rather, re-learned an old JS gotcha.

**Comment by eventualbuddha** [comment]
@Lokeh To clarify, this isn't quite correct:

> When inside an object literal, every functions `this` is scoped to the object.

When you have a function inside an object like either one of these:

```js
const someObj = {
  someFunc() { return this; },
  someOtherFunc: function() { return this; }
};
```

Inside these functions `this` isn't `someObj` unless it's called appropriately, e.g. `someObj.someFunc()` or `someObj.someFunc.call(someObj)`. If you call them a different way the result will be different:

```js
const fn = someObj.someFunc;
fn() !== someObj;
```

Inside non-arrow functions, `this` depends on how the function is called, not how the function is declared.

**Comment by Lokeh** [comment]
Thanks for the clarification. I swear I read the documentation on `this` all the time and still I get confused or miss some things that I just don't use in my day-to-day.

**Comment by damianobarbati** [comment]
I still don't get it.

a.js
```
export const obj = {
    handler: async () => {
         console.log(this); //<= prints this "file exports" as object instead of Component instance!
    }
}
```

b.js
```
import { obj } from './a';

class Component {
    invoke = async (handler) => {
        console.log('invoking', handler, this); //<= this is the current Component instance, fine so far
        handler();
    };
}
```

**Comment by nicolo-ribaudo** [comment]
Inside objects "this" refers to the "this" outside the object (the global "this"); inside classes to the instance itself.

**Comment by damianobarbati** [comment]
@nicolo-ribaudo so what I'm aiming to do is not possible?
Defining an arrow function as a property and invoking it within a class instance to use that instance as scope?

**Comment by nicolo-ribaudo** [comment]
If by "property" you mean "object property", you need to use a normal function.

**Comment by damianobarbati** [comment]
And manually bind it, got it: thanks @nicolo-ribaudo.
