### ISSUE TITLE
Circular dependency in core-js

### ISSUE THREAD

**Issue by erikras** [babel/babel#1745]
I'm building a project with webpack and `babel-runtime@5.5.8` and I'm getting a circular dependency in the `core-js` section of the bundle. It looks like it's due to the extra requires that babel is adding, not any problem in the `core-js` library, which is why I'm posting this here. These files require each other:

```./~/babel-runtime/~/core-js/library/modules/$.js
./~/babel-runtime/~/core-js/object/get-own-property-descriptor.js
./~/babel-runtime/~/core-js/library/fn/object/get-own-property-descriptor.js
./~/babel-runtime/~/core-js/library/modules/es6.object.statics-accept-primitives.js
./~/babel-runtime/~/core-js/library/modules/$.js
```

So when it gets back around to `$.js`, the object returned from the `__webpack_require__()`
call is just `{}`, which results in an error.

Any ideas? Is this a bug? If so, in which module? Could I be doing something wrong?

**Comment by sebmck** [comment]
There shouldn't be any issues with circular dependencies. cc @zloirock

**Comment by zloirock** [comment]
I saw it. I don't think it's core-js problems. Somewhat similar problems were solved correction configuration - `babel` transformed `core-js` modules.

Related https://github.com/zloirock/core-js/issues/71

**Comment by sebmck** [comment]
Yeah this would be a webpack or config issue then. Babel correctly outputs the `require`s and it should not be conflicting with anything.

**Comment by erikras** [comment]
Okay, thanks guys.

**Comment by zloirock** [comment]
@erikras maybe it will help https://github.com/babel/babel-loader/issues/50#issuecomment-93855935
