### ISSUE TITLE
Support for E4X

### ISSUE THREAD

**Issue by mitar** [babel/babel#1746]
[E4X is a deprecated](https://developer.mozilla.org/en-US/docs/Archive/Web/E4X) JavaScript standard and browsers do not support it anymore. It would be great if Babel could compile code in E4X into normal JavaScript?

Example of many E4X scripts are in Yahoo [YQL](https://github.com/yql/yql-tables/blob/master/yahoo/finance/yahoo.finance.quotes.xml).

**Comment by sebmck** [comment]
This is likely never going to happen. E4X is a dead standard. In the future you could implement this via a plugin but it's not really useful for a large majority of people so it can't be justified being in core. Thanks for the suggestion though!

**Comment by ming-codes** [comment]
I miss e4x 😞 

Perhaps someone in the community could write a Babylon plugin to parse it at least.
