### ISSUE TITLE
constructor super() transformation output can cause differing runtime if constructor is provided

### ISSUE THREAD

**Issue by jayphelps** [babel/babel#1748]
When a constructor is not provided to a class, the output code differs from that of when one is provided. This seems harmless but actually can have runtime differences because in the later, `_get(Object.getPrototypeOf(MyElement.prototype), "constructor", this).call(this);` the `constructor` property could be reassigned but in the former direct call `_HTMLElement.apply(this, arguments);` this is not possible.

In the case of extending from `HTMLElement` and similar, I'm attempting to sort of "mock" the ability to have a constructor by doing just that inside a decorator; overriding the super `constructor` to be noop so the browser does not throw `Uncaught TypeError: Illegal constructor`.

Regardless of whether what I'm doing is "good or bad", I don't believe it's intended for two possible runtime outcomes. Which is correct?

### No constructor provided
```js
class MyElement extends HTMLElement {
  
}
```
```js
var MyElement = (function (_HTMLElement) {
  function MyElement() {
    _classCallCheck(this, MyElement);

    if (_HTMLElement != null) {
      _HTMLElement.apply(this, arguments);
    }
  }

  _inherits(MyElement, _HTMLElement);

  return MyElement;
})(HTMLElement);
```
### Constructor provided
```js
class MyElement extends HTMLElement {
  constructor() {
    super();
  } 
}
```
```js
var MyElement = (function (_HTMLElement) {
  function MyElement() {
    _classCallCheck(this, MyElement);

    _get(Object.getPrototypeOf(MyElement.prototype), "constructor", this).call(this);
  }

  _inherits(MyElement, _HTMLElement);

  return MyElement;
})(HTMLElement);
```

**Comment by sebmck** [comment]
Should be the second.

**Comment by jayphelps** [comment]
Thank gawd.......my hack lives! :tada:

**Comment by camelmasa** [comment]
Hi. @sebmck 

Did you fix the problem :question:

```js
class MyElement extends HTMLElement {

}
```
 
Can we use above :question:

**Comment by sebmck** [comment]
@camelmasa Why don't you try it out? Should work.

**Comment by camelmasa** [comment]
@sebmck Thank you for response.

I tried that. but, the script occured error `Uncaught TypeError: Illegal constructor` on babel v5.6.4.
Is this specification :question:

**Comment by jayphelps** [comment]
@camelmasa Just to clarify--this issue was *not* about the *browsers* inability to extend `HTMLElement`. (e.g. `Uncaught TypeError: Illegal constructor`) this was a transpiling difference that affected any class extending another when you provided a constructor vs. not providing one.

```js
class Foo extends Bar {}
// vs.
class Foo extends Bar {
  constructor() {
    super();
  } 
}
```

The issue with not being able to invoke `HTMLElement`'s constructor is not related to babel in any way. I merely used it as a real-world example where I am using a hack to prevent the native constructor from firing.

**Comment by camelmasa** [comment]
@jayphelps I see... Thank you very much :octocat:
