### ISSUE TITLE
Clean up classes bare super

### ISSUE THREAD

**Issue by kittens** [babel/babel#1749]
- Add special case for single element `arguments` spread for loose and normal mode.
- Add additional helper for bare super constructor call.
  - Always return `this`

**Comment by elierotenberg** [comment]
As discussed on slack, this may make the return value of `super` consistently be the constructed object, enabling chaining `super` calls, eg
```js
constructor(param1, param2) {
  super()
    .method1(param1)
    .method2(param2);
}
method1(param1) {
  ...
  return this;
}
method2(param2) {
  ...
  return this;
}
```

**Comment by loganfsmyth** [comment]
I think is already works now.
