### ISSUE TITLE
"use strict" inserted between jsdoc comment and function declaration

### ISSUE THREAD

**Issue by erapoport** [babel/babel#1750]
From this:

     /**
     * Description
     */
     exports.greet = (name) => "hello " + name;
	
I get this

	/**
     * Description
     */
     "use strict"
     exports.greet = function(name) { return "hello " + name; }

Is this the expected behavior? I read that it's supposed to be either on top of the file, or inside functions. Do JSDoc parsers just ignore the "use strict" when placed like that?

I don't suppose there's a setting somewhere to put it on top of the file instead of between the comment and the function declaration?

Thanks

**Comment by sebmck** [comment]
See #1030, 1053 and #1533.

**Comment by erapoport** [comment]
I didn't have "use strict" anywhere. You mean I should manually add one on top of the file?

**Comment by sebmck** [comment]
If you don't want the comments being attached to the `"use strict";` statement then yeah.

**Comment by erapoport** [comment]
cool, thanks
