### ISSUE TITLE
System module transformer seems to do the wrong thing for mixed imports

### ISSUE THREAD

**Issue by kudos** [babel/babel#1751]
With an import statement that looked like this:

```js
import Router, {Route} from 'react-router';

console.log(Router);
console.log(Route);
```

In common.js this becomes:

```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _reactRouter = require('react-router');

var _reactRouter2 = _interopRequireDefault(_reactRouter);

console.log(_reactRouter2['default']);
console.log(_reactRouter.Route);
```

But the corresponding system.js that was being output looked like this: 

```js
System.register(['react-router'], function (_export) {
  'use strict';

  var Router, Route;
  return {
    setters: [function (_reactRouter) {
      Router = _reactRouter['default'];
      Route = _reactRouter.Route;
    }],
    execute: function () {

      console.log(Router);
      console.log(Route);
    }
  };
});
```

And so `Route` ends up being undefined.

I might attempt a fix for this myself next week.

**Comment by sebmck** [comment]
Nope, this is expected behaviour. SystemJS is supposed to be handling the normalisation internally. cc @guybedford

**Comment by kudos** [comment]
@sebmck I see what you mean. Sorry about the noise here then, I'll take a look at their code. Thanks!

**Comment by guybedford** [comment]
As of SystemJS 0.17, named exports for dynamic modules is supported.

**Comment by kudos** [comment]
@guybedford spotted that, thanks! :)
