### ISSUE TITLE
Some problems with a block scope

### ISSUE THREAD

**Issue by zhak55** [babel/babel#1756]
When I use block scope It gives me a wrong result. E.g.:
```javascript
{
 let { pow } = Math;
 
 function eq( x ) {
   return -pow( x, 2 ) + 5*x - 5;
 }
}
alert(eq(4))
```

And the result:
```javascript
{
  (function () {
    var eq = function (x) {
      return -pow(x, 2) + 5 * x - 5;
    };

    var pow = Math.pow;
  })();
}
alert(eq(5));
```

We got error - "eq is not defined". However, **function declaration** in a block scope should be available in alert.

**Comment by sebmck** [comment]
> We got error - "eq is not defined". However, function declaration in a block scope should be available in alert.

Nope. In previous versions of JavaScript function declarations were actually invalid anywhere but the **top** level. There was however pseudo-standard behaviour in functions/blocks were they were hoisted but in ES6 the behaviour was defined that function declarations are block scoped.
