### ISSUE TITLE
Decorators cause React.createClass({}) to lose displayName

### ISSUE THREAD

**Issue by Skalman** [babel/babel#1761]
As tested in the online REPL.

```js
// Input
const ComponentGood = React.createClass({
  func() {}
});

const ComponentBad = React.createClass({
  @decorator
  func() {}
});
```

```js
// Output
var ComponentGood = React.createClass({
  displayName: "ComponentGood",
  func: function func() {}
});

var ComponentBad = React.createClass(_createDecoratedObject([{
  key: "func",
  decorators: [decorator],
  value: function func() {}
}]));
```

`ComponentGood` has the `displayName` property as expected, but `ComponentBad` doesn't, because of the decorator. Is it a case of ordering the transformers differently?

**Comment by sebmck** [comment]
`es7.decorators` is being ran before `react` and causing the `displayName` check to fail since it's not a single `ObjectExpression` argument `CallExpression.
