### ISSUE TITLE
Can't transform Program node with a function call accepting another function

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#1762]
Since updating `5.5.8` our transform which wraps a `Program` into a function call started to fail:

```javascript
var privateData = 10;

module.exports = {
  getPrivate() {
    return privateData;
  }
};
```

Supposed to be transformed to:

```javascript
__d(function(module) {
  var privateData = 10;
  module.exports = {
    getPrivate: function() {
      return privateData;
    }
  };
});
```

Having (a simplified code snippet here):

```javascript
module.exports = new Transformer('fb-module', {
  Program: function(node, parent, scope, state) {
    return t.expressionStatement(
      t.callExpression(
        t.identifier('__d'), [
          // fails because of this function
          t.functionExpression(null, [t.literal('module')], node.body)
        ]
      )
    );
  }
});
```

Started to get the error:

```
/.../babel-core/lib/babel/transformation/file/index.js:628
      throw err;
            ^
Error: /Users/dmitrys/test.js: We couldn't find a Function or Program...
    at Scope.getProgramParent (....)
```

**Comment by sebmck** [comment]
Weird, I'm not actually sure why it would've previously worked.

**Comment by DmitrySoshnikov** [comment]
Yeah, definitely worked previously. I haven't yet dug it deeply, but it seems not related to usage of `node.body` (the body can be empty, `[]`). Also, if you have any other param (other than function expression, e.g. `t.literal('bar')`), it works.

**Comment by sebmck** [comment]
Replacing a `Program` with something that's not a `Program` doesn't make much sense. I'd assume the previous behaviour was just more lenient and it was actually making the `ExpressionStatement` the root node.

In the meantime you can fix up the plugin with:

```javascript
module.exports = new Transformer('fb-module', {
  Program: function(node, parent, scope, state) {
    node.body = [t.expressionStatement(
      t.callExpression(
        t.identifier('__d'), [
          // fails because of this function
          t.functionExpression(null, [t.literal('module')], node.body)
        ]
      )
    )];
  }
});
```

Two possible solutions:

1. Add special case handling for replacing `Program` with a non-`Program` node (Kinda dirty/hacky but will moreorless handle the lenient replacing of `Program` root nodes)
2. Make replacing a `Program` with a non-`Program` throw an error (keeping the current behaviour of a hard error but will be much more descriptive)

@DmitrySoshnikov What do you think?

**Comment by DmitrySoshnikov** [comment]
I see, yeah, the (2) option seems makes more sense, assuming either direct body modification, or returning new `t.program(...)`. Thanks for the clarifications!
