### ISSUE TITLE
Вопрос о стрелочных функциях

### ISSUE THREAD

**Issue by DmitryTrigonis** [babel/babel#1765]
Насколько мне известно стрелочные функции анонимны всегда. Так почему я получаю в результате - присвоение именованной функции? Есть сложность интерпретировать как function(){} ?
Я конечно смутно представляю как это сказывается на чем либо, но как минимум меня в замешательство ввело :)
![2222222](https://cloud.githubusercontent.com/assets/4435089/8179508/c0dceb48-141f-11e5-9319-a319bde768bd.png)

Я ожидал:
getSomething: function() {
            console.log('stuff');
        }

**Comment by zloirock** [comment]
Именованные функции используются для создания функций с корректным свойством `.name`. Свойство `.name` анонимной функции, заданной в литерале объекта, должно соответствовать ключу объекта. [12.2.5.8](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer-runtime-semantics-evaluation) -> [12.2.5.9](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer-runtime-semantics-propertydefinitionevaluation) -> [9.2.11](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-setfunctionname).

Для вопросов есть [slack](https://babeljs.slack.com/messages/general/).

И, пожалуйста, используйте здесь английский язык.

**Comment by DmitryTrigonis** [comment]
Это не ответ на мой вопрос - почему я не получил:
getSomething: function() {
console.log('stuff');
}

**Comment by sebmck** [comment]
Because ES6 has function name inference.

**Comment by RReverser** [comment]
@DmitryTrigonis 
Во-первых, вам как раз детально ответили.

Во-вторых,
> И, пожалуйста, используйте здесь английский язык.

Немного людей могут здесь ответить на русском, поэтому если Вы действительно хотите получить ответ, лучше сразу спрашивать на английском.

**Comment by DmitryTrigonis** [comment]
@RReverser 
"Во-первых, вам как раз детально ответили."

Я обращаю внимание на вторую функцию, объявленную стрелочным оператором. Почему на выходе я получил getSomething: function getSomething() {, а не  getSomething: function (){

**Comment by sebmck** [comment]
Please either talk in English or I'm locking this issue.

**Comment by DmitryTrigonis** [comment]
@sebmck lol? how about equality of language? haha

I did ask, why second function did interpreter in getSomething: function getSomething() {, and did not in getSomething: function (){

**Comment by sebmck** [comment]
How do you expect me to help you if you talk in Russian? This is an English project on and English website with majority English contributors.

> I did ask, why second function did interpreter

It's been explained to you. In ES6 there's a thing called funciton name inference where it bases the name of the function on the "code surrounding" it. What this means is that:

```javascript
var foo = function () {};
```

is compiled to:

```javascript
var foo = function foo() {};
```

Since it's inferred for the `name` to be `foo` based on the variable declaration.

**Comment by DmitryTrigonis** [comment]
Ok, thx i get it.
There is great post - http://bocoup.com/weblog/whats-in-a-function-name/

But i didn't get, why babel does it? As i get the interpeter does it by itself. 
I not need to write by myself somethink like - 
..{
name: function name(){}
} 

i just can write 
..{
name: function(){}
}

and it will be ok

**Comment by RReverser** [comment]
> But i didn't get, why babel does it? As i get the interpeter does it by itself.

Pre-ES6 engines don't, and it's what Babel is for (in general).

**Comment by DmitryTrigonis** [comment]
So, again, i can write in pre-ES6
...{
name: function(){}
}

and it will work

**Comment by RReverser** [comment]
So what? Again - of course it will work, but function's `.name` won't be compliant with ES6.

**Comment by DmitryTrigonis** [comment]
And where .name will be not be compliant with ES6? I mean where but spec? I can get some error or what?

**Comment by gaearon** [comment]
>I mean where but spec? I can get some error or what?

The point of Babel is to follow the spec as closely as possible.

**Comment by RReverser** [comment]
> And where .name will be not be compliant with ES6? I mean where but spec? 

ES6 **is** the spec. You can't choose some parts of it and ignore others "just because".

**Comment by DmitryTrigonis** [comment]
@gaearon @RReverser  I understand that, but really, just for curiosity, why?
Does it means that i will be have to write always, name: function name(){} ??!

**Comment by RReverser** [comment]
@DmitryTrigonis No you don't - Babel does it for you. Just don't touch it's output, and write normal ES6.

**Comment by gaearon** [comment]
In ES6-compliant browsers function's `name` will be inferred from context even if you write just `function () { }`. But most browsers don't do that yet.

Babel tries to emulate the behavior of ES6 compliant browsers. Because there is no other way to force the correct `name` to be there other than to name the function, it names your anonymous functions so they *appear* to have a name, as they would have in real ES6 browsers.

**Comment by RReverser** [comment]
@DmitryTrigonis You should also read this by @getify:

> I think it’s admirable that Babel is trying to stay true to the ES6 function name inference behavior. Unfortunately, adding a lexical name is the only way External Link to reliably set a function expression’s name property, so to do so, that’s why they put the lexical identifier foo in. 

(c) http://blog.getify.com/es6-concise-methods-lexical-or-not/

**Comment by DmitryTrigonis** [comment]
Ok, guys, I have no more questions. thx
