### ISSUE TITLE
Ability to change global identifier of UMD module

### ISSUE THREAD

**Issue by willemdewit** [babel/babel#1767]
Hi,

I'm trying to convert my globals-based application to a modules-based application. I already converted my code to only have one class (Function) per file. 
I immediately want to implement ES6 modules so that the code that is converted is in the most recent format. 
The code-base is pretty large and I cannot convert is all at the same time so I want to make an intermediate solution. All the files that are ES6 should be converted to a global based on the module name/path. 
I'm using Babel to transpile the ES6 modules to UMD. This is working fine, only the global identifier of the module is not in the format I want. It is now: `global.appUserController = mod.exports;` while I want it to be `global.app.User.Controller = mod.exports`.

Is there a way to change this global?

**Comment by sebmck** [comment]
You can only set it to a single identifier and that's unlikely to change.
