### ISSUE TITLE
Optimize `arguments`

### ISSUE THREAD

**Issue by benjamingr** [babel/babel#1768]
When writing a function like:

```js
function r(...rest){
  
}
```

Babel should probably not enumerate all the arguments into a variable in a for loop. In addition, when `rest` is only used for indexed access (which is the common case) or enumeration with for... of (arguments is enumerable) - babel should also not enumerate it into a new variable.

When `...rest` is not the first parameter, babel can still do index adjustments `rest[x]` becomes `rest[x + numArgs]` - so the optimisation equally applies.

When only used for delegation - babel should also not allocate and use a new array:

```
function r(...rest){
  f(...rest)  // no need to create an array for this common `.apply` case
}
```

**Comment by sebmck** [comment]
[It does?](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&code=function%20r(...rest)%7B%0A%20%20f(...rest)%3B%0A%7D&playground=false)

**Comment by benjamingr** [comment]
For example - this is the REPL code generated for:
```
function r(...rest){
  f(...rest)  // no need to create an array for this common `.apply` case
}
```

Output
```
"use strict";

function r() {
  for (var _len = arguments.length, rest = Array(_len), _key = 0; _key < _len; _key++) {
    rest[_key] = arguments[_key];
  }

  f.apply(undefined, rest);
}
```

**Comment by sebmck** [comment]
> In addition, when rest is only used for indexed access

This is already done when the expression is determined to always be a number.

```javascript
function r(...rest){
  rest[0];
  rest[1];
}
```

```javascript
"use strict";

function r() {
  arguments[0];
  arguments[1];
}
```

**Comment by benjamingr** [comment]
> This is already done when the expression is determined to always be a number.

Very nice! It's not done when the expression is not used at all (no `...rest` access) but it's good to know that that common case is optimized. Why would it matter if it's a number or not? Because it might be an `Array` prototype property?

**Comment by sebmck** [comment]
@benjamingr 

> Why would it matter if it's a number or not? Because it might be an `Array` prototype property?

Yep. See #889 for the PR that started the current member expression behaviour.

Also Babel does type inference so:

```javascript
function foo(...bar) {
  for (var i = 0; i < 5; i++) {
    bar[i];
  }
}
```

is handled.

**Comment by benjamingr** [comment]
Awesome, so what's left is:

 - Dealing with the case no indexed access is performed at all.
 - Forwarding `...rest` `f(...rest)` to `.apply` (this one actually matters for performance)

**Comment by sebmck** [comment]
> Dealing with the case no indexed access is performed at all.

What do you mean by this?

> Forwarding `...rest` `f(...rest)` to `.apply` (this one actually matters for performance)

Should be easy enough.

**Comment by benjamingr** [comment]
> What do you mean by this?


```js
function r(...rest){
    // empty, or `rest` is not accessed at all
}
```

> Should be easy enough.

Awesome :)

**Comment by sebmck** [comment]
I mainly kept the allocation when there are no references to avoid confusing people who type in the REPL to see what Babel compiles and end up getting an empty function since it's unlikely to come up in real code.

**Comment by benjamingr** [comment]
Elaborating a little on the first case. Basically, make the enumeration into an array happen when it is detected that it needs to be enumerated and not before - optimally never. So:

```js
function r(...rest){
    if(noNeedToWork) return 5;
    // do some stuff
    // some more stuff
    if(enoughThingsDone) return calculated;
    
    // FIRST TIME rest is accessed, so all the other branches of the function
    // pay the price of turning it into an array while they don't have to even if they're more common
    return rest.reduce((p, el) => p + el * 3, 0);
}
```

To be completely fair - the second option (delegating to `.apply`) is the much more common one and why I opened this issue in the first place (noticed it in my code).

**Comment by benjamingr** [comment]
> I mainly kept the allocation when there are no references to avoid confusing people who type in the REPL to see what Babel compiles and end up getting an empty function since it's unlikely to come up in real code.

What do you think about doing:

```js
function r(/*...rest*/){
    // body
}
```

Instead of 

```js
function r() {
  // body
}
```

In optimised cases?

**Comment by stefanpenner** [comment]
+1 for this opt. I thought it was already like this...

**Comment by sebmck** [comment]
@stefanpenner Only for the basic cases listed above.

**Comment by sebmck** [comment]
That was substantially more difficult than I imagined. There's not really any precedent in Babel for finding the common intersection/ancestor of a bunch of nodes which is required to get the lazy allocation. The implementation will needed to be vetted much more to ensure stability. I reconsidered my previous stance and if the rest binding is never referenced then the array is never allocated.

**Comment by Dashed** [comment]
Okay wow. That's slick! I had to defer the array loop to a separate function for an optimal code path. Then I saw this land.

Awesome stuff @sebmck! :+1:

**Comment by benjamingr** [comment]
Always a pleasure, thanks
