### ISSUE TITLE
[bug] "let" not handled as expected, overrides variable in outer scope.

### ISSUE THREAD

**Issue by trusktr** [babel/babel#1773]
I meant to post this bug here, but I accidentally posted it at meteor/meteor: https://github.com/meteor/meteor/issues/4571#issuecomment-112566022. Check it out there, but comment here. :laughing:

**Comment by sebmck** [comment]
[Not form what I can see?](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20blah%20%3D%20%22asdfasdf%22%0A%0Aif%20(!singleton)%20%7B%0A%20%20let%20blah%20%3D%20%22blah%22%0A%20%20singleton%20%3D%20this%0A%7D%0Aelse%20%7B%0A%20%20let%20blah%20%3D%20%22blahblah%22%0A%20%20%2F%2F%20return%20singleton%0A%7D%0A%0Aconsole.log(%22blah%22%2C%20blah)&playground=false)

**Comment by trusktr** [comment]
@sebmck Check out [this one](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=let%20guard%20%3D%20new%20WeakMap()%3B%0Alet%20singleton%20%3D%20null%0A%0Aclass%20Bar%20%7B%0A%20%20constructor%20(...args)%20%7B%0A%20%20%20%20var%20blah%20%3D%20%22asdfasdf%22%0A%20%20%20%20%0A%20%20%20%20if%20(!singleton)%20%7B%0A%20%20%20%20%20%20let%20blah%20%3D%20%22blah%22%0A%20%20%20%20%20%20singleton%20%3D%20this%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20let%20blah%20%3D%20%22blahblah%22%0A%20%20%20%20%20%20%2F%2F%20return%20singleton%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20console.log(%22blah%22%2C%20blah)%0A%20%20%20%20console.log(args)%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20private%20properties.%0A%20%20%20%20guard.set(this%2C%20%7Bfoo%3A%20'bar'%7D)%0A%20%20%7D%0A%7D%0A%0Aexport%20class%20Foo%20extends%20Bar%20%7B%0A%20%20constructor%20(...args)%20%7B%0A%20%20%20%20super(...args)%3B%0A%20%20%20%20guard.set(this%2C%20Object.assign(guard.get(this)%2C%20%7Blorem%3A%20'ipsum'%7D))%0A%20%20%7D%0A%20%20%0A%20%20someMethod()%20%7B%0A%20%20%20%20console.log(guard.get(this).lorem)%3B%0A%20%20%7D%0A%7D%0A%0Avar%20foo%20%3D%20new%20Foo(1%2C2%2C3)).

**Comment by trusktr** [comment]
Inside the constructor.

**Comment by trusktr** [comment]
@sebmck See it?

**Comment by fkling** [comment]
Please create a [minimal example](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&code=class%20Bar%20%7B%0A%20%20constructor%20()%20%7B%0A%20%20%20%20var%20blah%20%3D%20%22asdfasdf%22%0A%20%20%20%20%0A%20%20%20%20if%20(true)%20%7B%0A%20%20%20%20%20%20let%20blah%20%3D%20%22blah%22%0A%20%20%20%20%7D%0A%0A%20%20%20%20console.log(%22blah%22%2C%20blah)%0A%20%20%7D%0A%7D&playground=false).

**Comment by trusktr** [comment]
@fkling Noted for next time.

**Comment by benjamingr** [comment]
Note that babel handles this correctly in high compliancy mode.

**Comment by sebmck** [comment]
It handles this correctly in any mode. Also FWIW, there’s no “high compliancy” mode, that just toggles on a few optional transformers.

**Comment by benjamingr** [comment]
Oh I totally missed that the first one was `var` and not `bar` why do they differ?

**Comment by sebmck** [comment]
Whoops, thought I was in a different thread. The block scoping transformer differs extensively depending on context as it tries to generate the simplest code possible.

**Comment by trusktr** [comment]
So is there a bug here? @benjamingr I also noticed that checking the "High compliancy" checkbox makes it work properly.

**Comment by sebmck** [comment]
Yes there is. There's an issue with the scope tracking.

**Comment by trusktr** [comment]
Oh okay. I'll be careful with the class constructors for now. :smile:

**Comment by loganfsmyth** [comment]
I tracked this down last night, I'll try to submit a patch tonight.
