### ISSUE TITLE
Provable leak and error in _get

### ISSUE THREAD

**Issue by silkentrance** [babel/babel#1774]
Here you define desc = parent = getter = undefined without using var ...
Perhaps the semicolon between receiver = _x3 and desc is a typo?

And later on you redeclare desc using var desc = Object.getOwnPropertyDescriptor...

```
 var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; desc = parent = getter = undefined; _again = false; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };
```

**Comment by sebmck** [comment]
`var` declarations are hoisted so it's fine. That's also just the code after it's had TCO applied to it, the actual function is [here](https://github.com/babel/babel/blob/master/src/babel/transformation/templates/helper-get.js).

**Comment by silkentrance** [comment]
Considering multiple files with the same code, would it not be more efficient to just var declare the variables and then simply assign to them the value instead of first declaring them so that they would pose a possible leak and then redeclare them using the var keyword?

I wonder how current javascript engines handle such type of code...

**Comment by sebmck** [comment]
There's no leak. `var` declarations are hoisted.

**Comment by silkentrance** [comment]
@sebmck no leak true, i tried accessing these variables from my constructors, however, is it not advisable to first var declare them and then assign a value? Considering javascript engines, first declaring them as possible global variables and then var declaring them seems to me that this is not as efficient as it could be.

**Comment by sebmck** [comment]
What's not efficient about it? It's fine and it works. The compiled output would be even more verbose without them so it relies on hoisting to simplify it.

**Comment by silkentrance** [comment]
Would be even more verbose? I see replication of the var statement at least at three different times whereas a simple var desc = parent = getter = undefined would reduce it to just one.

**Comment by sebmck** [comment]
You're only declaring `desc` there, not `desc`, `parent` and `getter`. I'm not sure what the issue is. Do you have any tangible evidence that the hoisting behaviour is somehow unreliable?

**Comment by silkentrance** [comment]
Sigh, the example was incomplete of course xD. Not sure whether hoisting is correct term here, though. However, it actually does work but I still question its efficiency in regard to engines first attempting to establish a global and then "hoisting" it to a mere local. I think that the engines are doing more work than what would be required when first

var desc = undefined, parent = undefined, getter = undefined;

and then simply assign values to these locals.

**Comment by sebmck** [comment]
> Not sure whether hoisting is correct term here, though. 

It is :smile: 

> However, it actually does work but I still question its efficiency in regard to engines first attempting to establish a global and then "hoisting" it to a mere local

They don't establish a global first, JavaScript doesn't work like that. The declaration is literally hoisted:

```javascript
function foo() {
  bar();
  foo = "bar";
  var foo = "foo";
}
```

is the same as:

```javascript
function foo() {
  var foo;
  bar();
  foo = "bar";
  foo = "foo";
}
```

> var desc = undefined, parent = undefined, getter = undefined;
>
> and then simply assign values to these locals.

Yeah but that's more code for the exact same effect.

**Comment by silkentrance** [comment]
Ok I get it now, similar to prototyping in C or C++ with the difference that the declaration is reordered and moved to the top. Sigh, I am getting old :smile:

Thanks for taking and having the time.
