### ISSUE TITLE
Feature Request: Supporting hyphens in object literals

### ISSUE THREAD

**Issue by matthewmueller** [babel/babel#1775]
I doubt this is part of the ES6/7, but it'd be cool for Babel to support hyphens in object literals without quotes.

Example

```js
View({
  background-color: 'blue',
  color: 'red'
});
```

Or...

```js
View.background-color = 'blue';
```

**Comment by sebmck** [comment]
Babel follows standards as close as possible. Unfortunately, the syntax you're proposing is impossible to implement in JavaScript without introducing ambiguity eg. does `foo.foo-bar` mean `foo["foo-bar"]` or `foo.foo - bar`? This may be possible in the future with parser plugins (##1351) (the ambiguity will still remain though) but it's never going to be in core. Thanks for the suggestion! :smile:

**Comment by matthewmueller** [comment]
Ahh yah, good call. Yah, maybe I'll give a plugin a shot just for initializing object literals.
