### ISSUE TITLE
Inserting an `import` declaration via a transformer doesn't work

### ISSUE THREAD

**Issue by jmm** [babel/babel#1777]
This issue has been discussed some on [slack](https://babeljs.slack.com/messages/plugins/). babel v5.5.8. In short, this works:

```js
babel.transform("import x from 'x'; x();")
```

Output like (identifiers match):

```js
var _x2 = _interopRequireDefault(_x);

(0, _x2['default'])();

```

This does not:

```js
// import declaration equivalent to the above inserted via a `:before`
// transformer
babel.transform("x();")
```

Output like (identifiers don't match):

```js
var _x2 = _interopRequireDefault(_x);

x();
```

See https://gist.github.com/jmm/8f3fe314a1f7388f3847 for a complete repro.

Some snippets of the discussion from slack:

> **jmm**: The module formatter initialization can't run after user plugins (`:before` variety)?

> **sebastian**: the difference between internal and user transformers is going to be removed so i'd rather not

> **jmm**: can the module formatter initialization not just happen right before module transformers run?

> **sebastian**: not sure, it _might_ be able to

sebastian:
> the metadata collection need to be done before all the transformers
> since file transforms are split into `preprocess` and `process`
> the metadata needs to be available right after `preprocess`
> it would require doing two passes

**Comment by jmm** [comment]
Same problem occurs with `file.addImport()`.

FWIW the output is a bit different. That rewrites the import identifiers to different names -- `_something2` and `_something3` instead of `_something` and `_something2` -- and places `_interopRequireDefault()` after those vars in the generated output instead of before.)

**Comment by sebmck** [comment]
This problem wont occur in 6.0 as modules now operate as separate plugins and have no special state internally.

**Comment by jmm** [comment]
Awesome, thank you!
