### ISSUE TITLE
When inheriting from ES5 style klass, constructor function is lost if given a prototype

### ISSUE THREAD

**Issue by nhunzaker** [babel/babel#1779]
I'm hitting a strange bug where the constructor function for an ES5 style "klass" is only applied if no prototype is assigned to it. For example:

```javascript
function Parent() {
  this.name = 'Sally'
}

class Child extends Parent {
  constructor() {
    super()
  }
}

let child = new Child()

console.log('name' in child) // true
```

In the case above, the console.log will report `true`, however if we add a prototype to `Parent`:

```javascript
function Parent() {
  this.name = 'Sally'
}

Parent.prototype = {
  gender: 'female'
}

class Child extends Parent {
  constructor() {
    super()
  }
}

let child = new Child()

console.log('name' in child) // false
```

The result is false. Any idea what is going on here?

**Comment by nhunzaker** [comment]
It looks like the solution is to add the constructor to the prototype:

```
function Parent() {
  return Parent.prototype.constructor.apply(this, arguments)
}

Parent.prototype = {
  constructor() {
    this.name = 'Sally'
  },
  
  gender: 'female'
}

class Child extends Parent {
  constructor() {
    super()
  }
}

let child = new Child()

console.log('name' in child) // true
```

For my own sanity, have I missed something?

**Comment by eventualbuddha** [comment]
I don't believe this is a bug in Babel. If I were going to set `Parent.prototype`, I would write it like [this](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20Parent()%20%7B%0A%20%20this.name%20%3D%20'Sally'%0A%7D%0A%0AParent.prototype%20%3D%20%7B%0A%20%20constructor%3A%20Parent%2C%0A%20%20gender%3A%20'female'%0A%7D%0A%0Aclass%20Child%20extends%20Parent%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20super()%0A%20%20%7D%0A%7D%0A%0Alet%20child%20%3D%20new%20Child()%0A%0Aconsole.log('name'%20in%20child)%20%2F%2F%20true):

```js
function Parent() {
  this.name = 'Sally'
}

Parent.prototype = {
  constructor: Parent,
  gender: 'female'
}

class Child extends Parent {
  constructor() {
    super()
  }
}

let child = new Child()

console.log('name' in child) // true
```

**Comment by nhunzaker** [comment]
It's possible I've just been doing it the wrong way forever... if that is the case, I apologize for bugging you all with my mistake

**Comment by nhunzaker** [comment]
It is also worth noting that inheritence this way works in `loose` mode, however not in standard mode. For example, toggle loose mode in this code example on [http://babeljs.io/repl](http://babeljs.io/repl):

```javascript
function Parent() {
  this.name = 'Sally'
}

Parent.prototype = {
  gender: 'female'
}

class Child extends Parent {
  constructor() {
    super()
  }
}

let child = new Child()

console.log('name' in child) // true
```

I think that this is the root of my issue. That this is inconsistent between loose and strict mode. In my case, I was compiling to `loose` mode for a library however for a project not in `loose` mode, the error occurred.

**Comment by eventualbuddha** [comment]
The reason `loose` mode works as you're expecting is that it does not support having the `constructor` of an object change, so it simply sees that `Parent` is the superclass and calls it directly. In `standard` mode it makes sure to call the constructor by looking it up, since it may have changed since the class declaration. Because you're overwriting `Parent.prototype`, the `constructor` value will not be `Parent`, but `Object`, meaning that the body of the `Parent` constructor will never be called.

I hope that explanation makes sense. I encourage you to read the generated code for `loose` versus `strict` mode, and to ask questions in [the Slack channel](https://babel-slack.herokuapp.com/).

**Comment by nhunzaker** [comment]
:+1:  All clear, sorry to let this devolve into basic troubleshooting :)
