### ISSUE TITLE
FR: require modules.

### ISSUE THREAD

**Issue by hemanth** [babel/babel#1782]
Will be useful, if we could require modules, like what requirebin does?

**Comment by sebmck** [comment]
What does this mean? Please elaborate.

**Comment by hemanth** [comment]
In on of the old PR, I had done the changes to say the below when use types in require.

```sh
require is not supported in the browser, you need a commonjs environment such as node.js/io.js, browserify/webpack etc
```

But, it would be useful, if we can let the user require any npm module in the web based REPL, as in internal we need to make use `brcdn` or `wzrd` so the REPL becomes more powerful (:

**Comment by sebmck** [comment]
Oh this is a feature request for the REPL/website, please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

FWIW, what you're proposing would be impossible. How do you expect to dynamically import random npm modules?

**Comment by hemanth** [comment]
It's possible we could do it like [this](http://requirebin.com/) using one of the browserify cdns :)

**Comment by eventualbuddha** [comment]
@hemanth that is cool. I would argue that RequireBin should have an option to write using ES6 and transpile using babel ;)

**Comment by hemanth** [comment]
@eventualbuddha That's also a nice option ;)
