### ISSUE TITLE
problems with the encoding of Cyrillic

### ISSUE THREAD

**Issue by DmitryTrigonis** [babel/babel#1783]
Both files r in UTF-8
![32132132122222](https://cloud.githubusercontent.com/assets/4435089/8230712/7041a04a-15cb-11e5-8c70-d84218b3b019.png)

**Comment by sebmck** [comment]
I need more information. The source code of the files, Babel/Node version, commands/integrations that you're using to build the files etc.

**Comment by DmitryTrigonis** [comment]
Babel/Node version?


Here is my gulpfile:

```
gulp.task('watch', function() {
    gulp.watch("**/*.babel", ['babel']);
});

gulp.task("babel", function () {
    gulp.src("**/*.babel")
        .pipe(babel())
        .pipe(rename(function(src){
            src.dirname = src.dirname.replace("src" + path.sep, "");
            src.basename = src.basename.replace(".babel", ".js");
        }))
        .pipe(gulp.dest("./"));
});
```

**Comment by DmitryTrigonis** [comment]
In the left we have babel. Right it's after compiling

**Comment by sebmck** [comment]
I need the original source of the file you're compiling as well as your Node and Babel version so I can attempt to reproduce.

**Comment by DmitryTrigonis** [comment]
Babel:
```
'use strict';

define([
    'backbone'
], function (Backbone) {

    return Backbone.Model.extend({

        defaults: {
            name: 'input',
            title: 'Поле ввода',
            value: null,
            placeholder: null,
            label: null,
            help: null
        },

        validation: {
        }

    });
});
```
Output:
```
'use strict';

define(['backbone'], function (Backbone) {

    return Backbone.Model.extend({

        defaults: {
            name: 'input',
            title: '���� �����',
            value: null,
            placeholder: null,
            label: null,
            help: null
        },

        validation: {}

    });
});
```

Node: v0.12.3
"gulp-babel": "^5.1.0",  "version": "5.1.0",

**Comment by sebmck** [comment]
Likely a Gulp issue then. It works fine in the [REPL](http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code='use%20strict'%3B%0A%0Adefine(%5B%0A%20%20%20%20'backbone'%0A%5D%2C%20function%20(Backbone)%20%7B%0A%0A%20%20%20%20return%20Backbone.Model.extend(%7B%0A%0A%20%20%20%20%20%20%20%20defaults%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20'input'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20title%3A%20'%D0%9F%D0%BE%D0%BB%D0%B5%20%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20value%3A%20null%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20placeholder%3A%20null%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20label%3A%20null%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20help%3A%20null%0A%20%20%20%20%20%20%20%20%7D%2C%0A%0A%20%20%20%20%20%20%20%20validation%3A%20%7B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%7D)%3B%0A%7D)%3B&playground=false).

**Comment by DmitryTrigonis** [comment]
Yeap it's like not in babel. I close this
