### ISSUE TITLE
Website "eval" should be in an isolated environment to prevent redefinition errors

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [babel/babel#1787]
Type this:

```js
Object.defineProperty(Element.prototype, 'foo', {
  enumerable: true,
  get: function(){}
});
```

and hit space a few times.  You get errors saying `foo` can't be redefined.  This is because the code is being repeatedly executed in the same context and it's only an error after the first attempt.

You could argue that this should be wrapped in a `#ifndef`-ish statement, but then anything in that block would not be tested again.

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by sebmck** [comment]
Also this currently open issue would be relevant: babel/babel.github.io#161

**Comment by kaaaahhhhnnnn** [comment]
Sorry about that :)
