### ISSUE TITLE
[Request] loose mode to disable `(0, mod['default])(foo)`

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#1788]
today:

```
import foo from 'bar'

foo()
```

via `babel --modules amdStrict` becomes:

```js
define(['exports', 'bar'], function (exports, _bar) {
  'use strict';

  (0, _bar['default'])();
});
```

Although `(0, _bar['default'])();` prevents leaking the internal module POJO, this comes at a non-trivial increase in file-size and to a lesser degree adds extract AST size/source size which may prevent inlining.

It would be handy if the `amdStrict` disabled this by default, or even if an additional `loose` mode which disabled this could be added.

**Comment by benjamingr** [comment]
What would you like it to look like instead of that?
