### ISSUE TITLE
Make string template evaluation lazy

### ISSUE THREAD

**Issue by drepo** [babel/babel#1791]
Babel (5.0.4) expands string template in place using concatenation operator (+). The problem is this inhibits passing templates as function arguments (refer the attached screenshot for the example) - because parameters need by the template are not in scope. I do not know what the standard says on this one.

But it will be pretty handy if template strings are lazily evaluated, it will make passing them around easy and reusable too.

The implementation of string templates in languages like python differentiate between declaration and evaluation. 

```python
x = 'My name is {0}' # Declaration
print(x.format('Apple')) # Evaluation
```
This could have been a nice alternative, but I do not think the standard provides for it. 

I can, indeed, wrap the template inside a function. But then a simple operation of passing a variable is now transformed into a function call.

![screenshot from 2015-06-19 17 57 44](https://cloud.githubusercontent.com/assets/4113784/8253374/b8db7a7e-16ac-11e5-90fe-f3565a89dd47.png)

**Comment by sebmck** [comment]
This isn't how template literals works. You can learn about them [here](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en).

**Comment by sebmck** [comment]
To elaborate. Template literals aren't really templates, they're just a way to interpolate expressions within text. There are tagged template literals but they're still executed when they're evaluated instead of returning a representation that you can use lazily.

**Comment by drepo** [comment]
Hmm... I confess, I do not know the standard there. I guess, I will have to create such a representation myself then.
