### ISSUE TITLE
Root let variables within a function

### ISSUE THREAD

**Issue by kobezzza** [babel/babel#1792]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

> Redeclaration of the same variable in the same block scope raises a TypeError.
```js
if (x) {
  let foo;
  let foo; // TypeError thrown.
}
```
However, function bodies do not have this limitation!
```js
function do_something() {
  let foo;
  let foo; // This works fine.
}
```

**Babel**

```js
function do_something() {
  let foo;
  let foo; // Duplicate declaration "foo"
}
```

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=function%20do_something%28%29%20{%0A%20%20let%20foo%3B%0A%20%20let%20foo%3B%20%2F%2F%20This%20works%20fine.%0A}

**Comment by sebmck** [comment]
Do you have a spec reference?

**Comment by sebmck** [comment]
Tested this in all major browsers that support `let` and all other transpilers seem to agree. Happy to reopen if you provide a spec reference but it looks like those docs are outright wrong.
