### ISSUE TITLE
Arrow function doesn't correct.

### ISSUE THREAD

**Issue by xgrommx** [babel/babel#1795]
Hello @sebmck I use babel and arrow function like this:
```js
let x = () => {
  console.log(this);
};

x();
```
But in ```console.log``` output ```undefined```. This is very important problem in my project.

**Comment by sebmck** [comment]
See the [FAQ](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-) as well as #1700, #1667, #1573, #562, #814, #730 and #733.
