### ISSUE TITLE
No longer able to "import" from project

### ISSUE THREAD

**Issue by benderTheCrime** [babel/babel#1802]
Greetings,

I used to be able to import using the documented syntax

```javascript
import Sandwich from './Sandwich';
```

where `Sandwich` is a class in a file in the same directory:

```javascript
export default Sandwich {}
```

but this is no longer working. Is this intended? It seems unlikely that this would diverge from the spec at this point. I am using version `5.6.4`. Here is the actual traceback:

```javascript
events.js:141
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at Object.<anonymous> (**/src/Base.js:16:11)
    at Module._compile (module.js:410:26)
    at normalLoader (**/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (**/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (**/src/Server.js:10:32)
    at Module._compile (module.js:410:26)
```
where what is undefined is `Sandwich`

**Comment by sebmck** [comment]
```javascript
export default Sandwich {}
```

throws a syntax error. Going to need exact steps to reproduce, commands to run, exact files to use etc.

**Comment by benderTheCrime** [comment]
Thanks for getting back to me so quickly!
It's going to be a little tricky to reproduce exactly what's going on. It seems like you've recognized that I've tried to alias everything just to see if something very high level is going on. My apologies for the vagueries. The actual repo I'm experiencing this issue on is here: https://github.com/benderTheCrime/angie, but only in a feature branch of the repo, I'm going to explore a diff against master and see if I can track down what is going on. If nothing else, perhaps I've made a silly mistake and it will be useful to others to know what is causing the issue.

**Comment by benderTheCrime** [comment]
Even then, it's only the `gulp mocha` command that triggers the issue, all of the other application commands import properly. I will follow up shortly.

**Comment by benderTheCrime** [comment]
Ok, I am at the end of my rope with this one, I've been diagnosing the issue for a few days now to no avail:

Exact files to use: 
https://github.com/benderTheCrime/angie is the repo where I am experiencing the issue, in the `directive-parsing` branch. You should be able to pull down the repository. If you do not have time or do not want to go through the trouble, I totally get it. You should be able to run `npm install && gulp mocha` from the command line at the root of the project, which will inevitably reproduce the error. For exactness, I'm using iojs-v1.7.1.

You'll notice that if you try and run an `angie` command, even by itself, this error does not occur. For the best results, you may have to link angie and run the command from an external folder.

**Comment by sebmck** [comment]
@benderTheCrime Fixed it. There's some weird race conditions with your imports. Add:

```javascript
import '../../../src/index';
```

to the top of `test/src/services/$Compile.spec.js`. You may need to move around that import in the future (it's the first file to be loaded) to make sure everything is loaded in order.

**Comment by benderTheCrime** [comment]
Interesting, thank you for looking into this! Whenever you get the chance, I'm also curious as to how a race condition was imposed by my imports? Does the order that index specifies the packages are imported in get preserved in other packages? Even links to docs would be helpful. Thank you again!
