### ISSUE TITLE
Can't `npm test`

### ISSUE THREAD

**Issue by rvagg** [babel/babel#1803]
```
$ npm test
node test/acorn/run.js
module.js:339
    throw err;
          ^
Error: Cannot find module '../../lib/acorn'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/rvagg/git/iojs/iojs-smoke-tests/babel/test/acorn/tests.js:7:15)
...
```

I'd love to put babel in the io.js / Node.js [smoke tests](https://github.com/rvagg/iojs-smoke-tests) so we can confirm it works with new builds but I can't get past this. Are you manually importing acorn and not rewriting files properly? Thanks.

**Comment by sebmck** [comment]
You'll need to compile the source: 

```sh
$ make bootstrap
```

Should do the trick. It'll link all the necessary files and build Babel, then `npm test` should work. More information is available in [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#setup). Thanks!

**Comment by rvagg** [comment]
derp, sorry for being a noob, thanks!
