### ISSUE TITLE
"arguments" object attribute issue

### ISSUE THREAD

**Issue by helios1138** [babel/babel#1805]
Object literals containing an attribute called "arguments" get converted to "args$1$0" by babel

```js
action: {
   do: 'setUserStatus',
   arguments: 'checked'
}
```
converts to
```js
action: {
   'do': 'setUserStatus',
   args$1$0: 'checked'
}
```

**Comment by zloirock** [comment]
[Only in generators and async functions](https://goo.gl/7pQFMv). Looks like `regenerator` issue. \cc @benjamn

**Comment by helios1138** [comment]
@zloirock aparently not exactly, you can see that babel wraps attributes with in quotes, if attributes are reserved words like 'do', 'while', 'const' etc. then in generators it will not touch them. If you manually wrap "arguments" in quotes, [same thing](https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&playground=true&code=var%20h%20%3D%20async%20_%20%3D%3E%20%20(%7B%0A%20%20do%3A%20'setUserStatus1'%2C%0A%20%20'arguments'%3A%20'checked1'%0A%7D)%0A%0Avar%20h%20%3D%20async%20_%20%3D%3E%20%20(%7B%0A%20%20do%3A%20'setUserStatus1'%2C%0A%20%20arguments%3A%20'checked1'%0A%7D)) will happen.

So it seems that it can be solved by adding "arguments" to the list of reserved words for automatic wrapping.

**Comment by sebmck** [comment]
@helios1138 Nah this is indeed a `regenerator`/`ast-types` issue. It's not checking for referenced Identifiers in non-computed property keys position.

**Comment by helios1138** [comment]
@sebmck what I meant was that it can **also** be fixed on babel's side. But I guess that would be the wrong thing to do :)

**Comment by benjamn** [comment]
This seems easiest to fix in Regenerator.
