### ISSUE TITLE
When removing arguments, babel should add a comment instead

### ISSUE THREAD

**Issue by benjamingr** [babel/babel#1808]
Referencing the optimization here https://github.com/babel/babel/issues/1768

For example in:

```js
function foo(...args){
  bar(args[0])
}
```

Babel produces

```js
function foo() {
  bar(arguments[0]);
}
```

Which is great, but I think for readability it would be nice to produce:

```js
function foo(/*rest*/) {
  bar(arguments[0]);
}
```

So it's clear to the reader where rest 'went'. Opinion?

**Comment by sebmck** [comment]
Not sure how that's any more clear?

**Comment by sebmck** [comment]
There's actually no node for that comment to be attached too so it can't be reprinted in the AST.

**Comment by benjamingr** [comment]
> Not sure how that's any more clear?

It makes the fact that the argument was there and now it's gone more explicit.

It's not a big deal but at https://github.com/babel/babel/issues/1768#issuecomment-112436576 you said it can confuse people so I figured it'd be a nice addition.

If it's hard from a technical point of view (there was an argument there, that's not a node?) it's really not worth putting significant effort into.

**Comment by sebmck** [comment]
@benjamingr 

> there was an argument there, that's not a node?

Well there _was_ a node there. It was removed though to retain function arity.

> It's not a big deal but at https://github.com/babel/babel/issues/1768#issuecomment-112436576 you said it can confuse people so I figured it'd be a nice addition.

Yeah, I've thought about it some more and I've always been against people learning from Babel code, in the future there's probably going to be a disclaimer in the REPL.

**Comment by benjamingr** [comment]
>  I've always been against people learning from Babel code

Wait what? I thought one of the goal's projects was to produce readable output code, I think it's something that helps babel be successful. I agree that when tradeoffs need to be made and if readability is not worth it at certain times it can be (carefully) sacrificed but I was under the impression readable output is a project goal.

> Well there was a node there. It was removed though to retain function arity.

Then can't the comment node be added then and there?

------

Again, I don't feel strongly about this. Feel free to close if you don't want to support it I just figured it'd help readability and be relatively simple to do.

**Comment by sebmck** [comment]
> Wait what? I thought one of the goal's projects was to produce readable output code, I think it's something that helps babel be successful. I agree that when tradeoffs need to be made and if readability is not worth it at certain times it can be (carefully) sacrificed but I was under the impression readable output is a project goal.

It's a project goal but so is a ton of others. Learning from source isn't the same as readable. Babel simply has way too many cases that specialise how code is transformed for it to be an accurate representation for people to learn off.

> Then can't the comment node be added then and there?

Comment nodes are a different type of node that are attached to existing ones. See #483 for previous discussion on how the comment attachment works. They can't be inserted as normal nodes since they have no semantic meaning.

> Again, I don't feel strongly about this. Feel free to close if you don't want to support it I just figured it'd help readability and be relatively simple to do.

Yeah, can't really do this anyway due to the attachment issue. Thanks for the suggestion though!
