### ISSUE TITLE
JSX defaultChecked not working as expected

### ISSUE THREAD

**Issue by ddaza** [babel/babel#1809]
I am having an issue with the `defaultChecked` property in JSX. The HTML that is generated does not check the checkboxes when the attribute is set to true `defaultChecked = {true}`.

I've created a [jsfiddle](http://jsfiddle.net/7zvuegxy/) of what the functionality should look like. 

I am using  babel@5.6.4  

This is my ES6 code. 

``` javascript
export default class TagList extends React.Component {
  render() {
    let tags = this.props.tagsObject || ''; // this is an array 
    let activeTags = this.props.activeTagsObject; // this too is an array
    return (
        <div>
          {tags.map((tag, key)=> {
            let isChecked = activeTags.indexOf(tag) >= 0;
            return (<Tag key={tag + key}
              tagKey = {key}
              tagName={tag}
              isChecked = {isChecked}/>);
          })}
      </div>
    );
  }
}

class Tag extends React.Component {
  render() {
    let tagNameKey = this.props.tagName + this.props.tagKey;
    let isChecked = this.props.isChecked;
    return (
      <div>
        <input className='guide-tag-input'
          type='checkbox'
          name={tagNameKey}
          id={tagNameKey}
          defaultChecked={isChecked}/> // this is used per (https://github.com/facebook/react/issues/259)
        <label htmlFor={tagNameKey}>
          {this.props.tagName}
        </label>
      </div>
    );
  }
}

```

**Comment by sebmck** [comment]
I'm confused by what the issue is. Is there any issue with the compiled output, if so what is it?

**Comment by ddaza** [comment]
I might be wrong on this one. 

What I'm seeing is that the compiled output does not work like the React code in the jsfiddle. 

More specifically, the transpiled ES6 code with the `defaultChecked` should check the checkboxes on the `Render` whenever there is a match, but on the output none of the checks are there.  Basically, the `defaultChecked` attribute is ignored.

I double checked my data and I know there should be matches.
 
Also, I found that if i set the checkboxes to `checked={true}` the checkboxes work as expected. However,  I run into the same issue as in [259](https://github.com/facebook/react/issues/259) and that's is why i use `defaultChecked`.

**Comment by sebmck** [comment]
There's nothing special about that property and the Babel's output matches the now deprecated [jstransform](https://github.com/facebook/jstransform).

**Comment by qborreda** [comment]
It happens to me as well .. 

To clarify, the output shows a selected dom like 
`<input type="checkbox" checked .. />`, but if you inspect the element and try the `checked` value of the dom node (with chrome or firefox, this would be `$0.checked`) it returns false .. 

Not only that .. an associated css rule like `:checked` doesn't show the selected state styles, even if the rendered dom element shows the `checked` attribute ..
