### ISSUE TITLE
strict mode bleeds to global scope

### ISSUE THREAD

**Issue by sulmanen** [babel/babel#1813]
foo()

becomes

'use strict'
foo()

which bleeds 'use strict' to global scope

blacklisting and manual 'use strict' is an option. Opening discussion for scoping file with iife?

**Comment by monsanto** [comment]
This is intended. The input to Babel is an ES module, which implies strict mode. If you don't want strict mode you need to explicitly blacklist it.

**Comment by loganfsmyth** [comment]
Babel assumes that each file is a module, so it would be up to the module loading system to ensure this. Generally this would be Node, Browserify, Webpack, or SystemJS, and it would be up to them to ensure that the file is processed with a surrounding IIFE.

**Comment by monsanto** [comment]
Ref on this decision: https://github.com/babel/babel/issues/1049

**Comment by sebmck** [comment]
There’s no such thing as top-level Program strict mode in a file bleeding into another. What are you basing this on?

**Comment by monsanto** [comment]
@sebmck The only case AFAIK is if you concat files as a hacky module loader.
