### ISSUE TITLE
Prevent setter with default argument

### ISSUE THREAD

**Issue by ouhouhsami** [babel/babel#1816]
Hello, 

Babel transpiles this code below without any warnings, which is weird, as a setter without a value is a getter. (I found this trying to use traceur instead of babel).
I don't know if it's babel role to warn about that, may be?

```
class Test {
  constructor() {
    this._test = null;
  }

  set test(value = true) {
    console.log('setter');
    this._test = value;
  }

  get test() {
    console.log('getter');
    return this._test;
  }
}

var test = new Test();
test.test;

console.log(test._test);

```

Best

**Comment by sebmck** [comment]
Please report this upstream to [Acorn](https://github.com/marijnh/acorn).

cc @RReverser The setter can only be a single identifier, no patterns/rest.

**Comment by RReverser** [comment]
@ouhouhsami Setter without argument is not a getter, those are different slots of `PropertyDescriptor`.

@sebmck It can be pattern (it would be super weird if you couldn't use destructuring here).

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-method-definitions:
```
set PropertyName[?Yield] ( PropertySetParameterList ) { FunctionBody }

PropertySetParameterList :
  FormalParameter
```

And `FormalParameter` is nothing else but `BindingElement` which in turn is `BindingPattern` + optional `Initializer`.

**Comment by sebmck** [comment]
@RReverser Ah right, my bad. For some reason I thought the grammar that restricted rest also forbid patterns...

**Comment by RReverser** [comment]
Ah wait it's resolved, right :P
