### ISSUE TITLE
[bug] "for..of" crashes on iOS device

### ISSUE THREAD

**Issue by talexu** [babel/babel#1825]
Hi:

Recently, I write ES6 and compile to ES5 by webpack and babel.
I found that the compiled "for..of" crashes on all the browsers of iOS, including Safari, Chrome and UC.
By the way, it works fine on my PC, so I guess the bug should be related to iOS.

The following is my ES6 code:

	for (let dataEntity of dataEntities) {
		createTumblr(dataEntity);
	}

The following is compiled ES5 code:

	var _iteratorNormalCompletion = true;
	var _didIteratorError = false;
	var _iteratorError = undefined;

	try {
		for (var _iterator = dataEntities[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
			var dataEntity = _step.value;

			createTumblr(dataEntity);
		}
	} catch (err) {
		_didIteratorError = true;
		_iteratorError = err;
	} finally {
		try {
			if (!_iteratorNormalCompletion && _iterator['return']) {
				_iterator['return']();
			}
		} finally {
			if (_didIteratorError) {
				throw _iteratorError;
			}
		}
	}

The following is my configuration of webpack:

	module: {
		loaders: [
			{ test: /\.jsx?$/, exclude: /node_modules/, loader: "babel-loader" }
		]
	}

Hope this can help you!

**Comment by sebmck** [comment]
Not sure how this is a Babel issue? Not sure how this _could_ be fixed.

**Comment by kevinb7** [comment]
@talexu are you loading the polyfill?  Most desktop browsers support Symbol natively, but I'm guessing mobile WebKit doesn't yet.  Could you also post some more information like what version of iOS you're seeing this on.

**Comment by talexu** [comment]
@kevinb7 
I am using iOS 8.3 (12F70).
My current solution is replacing "for..of" by forEach.

**Comment by sebmck** [comment]
What do you mean by crash? Does the entire browser literally close or does it just throw an error?

**Comment by stefanpenner** [comment]
stacktrace?

**Comment by talexu** [comment]
@sebmck 
It should be an error thrown by JavaScript. But I don't know how to get the stack trace for Mobile Browser

**Comment by talexu** [comment]
@stefanpenner 
Is there any good way to get stacktrace on mobile device?

**Comment by kevinb7** [comment]
You should be able to see the stacktrace in desktop Safari if you're using remote debugging.
http://developer.telerik.com/featured/a-concise-guide-to-remote-debugging-on-ios-android-and-windows-phone/

If you don't have access to a Mac you might try this: https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by sebmck** [comment]
It would be because you aren't using the [polyfill](http://babeljs.io/docs/usage/polyfill) and are attempting to use `for...of`. The dependencies for specific transformers are specified in the [caveats](http://babeljs.io/docs/advanced/caveats/).

**Comment by talexu** [comment]
@sebmck Oh thank you, the issue is that I didn't use polyfill, it has been fixed :)
