### ISSUE TITLE
Minification plugins

### ISSUE THREAD

**Issue by sebmck** [babel/babel#1828]
Goal: Beat Uglify
Confidence: High

**Comment by chcokr** [comment]
What's your take on Closure Advanced Mode?

**Comment by novacrazy** [comment]
This would be an amazing feature. Compile and minify in a single development stage with Babel.

**Comment by RnbWd** [comment]
This is interesting. According to their [website](http://lisperator.net/uglifyjs/), `uglifyJS` consists of:

- A parser which produces an abstract syntax tree (AST) from JavaScript code.
- A code generator which outputs JavaScript code from an AST, also providing the option to get a source map.
- A compressor (optimizer) — it uses the transformer API to optimize an AST into a smaller one.
- A mangler — reduce names of local variables to (usually) single-letters.
- A scope analyzer, which is a tool that augments the AST with information about where variables are defined/referenced etc.
- A tree walker — a simple API allowing you to do something on every node in the AST.
- A tree transformer — another API intended to transform the tree.

There is *so much overlap* to begin with, and the compressor and mangler could definitely be implemented as plugins! 

@chcokr - Here's a chart from `uglifyJS`'s website comparing it to Closure:

<img width="574" alt="screen shot 2015-07-07 at 6 40 38 pm" src="https://cloud.githubusercontent.com/assets/5370305/8561297/142c4da2-24d8-11e5-8999-833e061f670a.png">

Closure does minify the codebase more than `uglify` on average, and the Advanced Mode may be even better than those benchmarks, but it's 2x-5x slower on average, and it's written in Java, which makes it very difficult to implement as a plugin.

**Comment by hzoo** [comment]
Compressor table: [uglify readme](https://github.com/mishoo/UglifyJS2#compressor-options) (probably missed some things)

Uglify | Babel plugin
------- | ----------------
sequences | 
properties | [babel-plugin-member-expression-literals](https://github.com/babel-plugins/babel-plugin-member-expression-literals)
dead_code | [babel-plugin-dead-code-elimination](https://github.com/babel-plugins/babel-plugin-dead-code-elimination)
drop_debugger | [babel-plugin-remove-debugger](https://github.com/babel-plugins/babel-plugin-remove-debugger)
unsafe | 
conditionals | 
comparisons | 
evaluate | [babel-plugin-constant-folding](https://github.com/babel-plugins/babel-plugin-constant-folding)
booleans | 
loops | 
unused | [babel-plugin-undeclared-variables-check](https://github.com/babel-plugins/babel-plugin-undeclared-variables-check) (throws compile-time error vs removing variables)
hoist_funs | 
hoist_vars | 
if_return | 
join_vars | [babel-plugin-merge-sibling-variables](https://github.com/babel-plugins/babel-plugin-merge-sibling-variables)
cascade | 
warnings | --
negate_iife | 
pure_getters | --
pure_funcs | --
drop_console | [babel-plugin-remove-console](https://github.com/babel-plugins/babel-plugin-remove-console)
keep_fargs | --
keep_fnames | --

Transform | Name
-------------- | --------
{ "foo": 1} -> { foo: 1} | [babel-plugin-property-literals](https://github.com/babel-plugins/babel-plugin-property-literals)
true -> !0, false -> !1 | [babel-plugin-minify-booleans](https://github.com/babel-plugins/babel-plugin-minify-booleans)
=== -> ==, !== -> != (if same type) | [babel-plugin-simplify-comparison-operators](https://github.com/babel-plugins/babel-plugin-simplify-comparison-operators)

**Comment by avesus** [comment]
What really does https://github.com/RReverser/babel-plugin-uglify ???

**Comment by sebmck** [comment]
Closing and tracking this elsewhere in separate issues/projects.
