### ISSUE TITLE
instanceof lies in isomorphic code

### ISSUE THREAD

**Issue by robhicks** [babel/babel#1834]
## Should instanceof act differently when transpiling for node and the browser?

I'm porting a Java library for genealogical interchange to Javascript. The library constructs interchange objects. 
I have chosen es6 as the target language and am using Webpack / Babel to transpile it. 
Because the code is isomorphic (just POJOS), I have written extensive tests for the library using mocha as the test runner and hooking babel into the tests through js:babel/register . The tests are run in node v.0.10.38.
The library makes heavy use of passing class instances to other class methods to add to the interchange object. For example, the main object (a gedcomx object), includes a method to add a sourceDescription, which defines the source of the genealogical information.  For example:
```Javascript
import { SourceDescription } from './source/SourceDescription';
class Gedcomx {
  constructor() {
    this.id = uuid();
    }
  }
addSourceDescription(sourceDescription) {
    this.sourceDescriptions = this.sourceDescriptions || [];
    if (sourceDescription instanceof SourceDescription) this.sourceDescriptions.push(sourceDescription);
    else throw new Error('Error: sourceDescription must be instance of SourceDescription');
  }
}
```
The SourceDescription class looks something like this:
```Javascript
class SourceDescription {
  constructor() {
    this.id = uuid();
  }
}
export { SourceDescription };
```
And to test the addSourceDescription method:
```Javascript
describe('addSourceDescription(sourceDescription)', function() {

    it('should throw an error if sourceDescription is not a SourceDescription instance', function() {
      var sourceDescription = {};
      var gedcomx = new Gedcomx();
      expect(function() {
        gedcomx.addSourceDescription(sourceDescription)
      }).to.throw('Error: sourceDescription must be instance of SourceDescription');
    });

    it('should set sourceDescription to array of SourceDescriptions', function() {
      var sourceDescription = new SourceDescription();
      var gedcomx = new Gedcomx();
      gedcomx.addSourceDescription(sourceDescription);
      expect(gedcomx.getSourceDescriptions()).to.be.an('array');
    });

  });
```
The test works as expected. 
However, when I attempt to use the library in a browser (developing with latest stable release of Chrome on Yosemite), the addSourceDescription method instanceof check returns false:
```Javascript
var model = new Gedcomx();
        var sd = new SourceDescription();
        model.addSourceDescription(sd);
```
resulting in the thrown error 'Error: sourceDescription must be instance of SourceDescription'.
As can be seen, I'm not doing odd things that tend to result in instanceof lies, such as creating instances using Object or creating instances in different frames. 

Any insight / help would be greatly appreciated.

**Comment by stefanpenner** [comment]
> As can be seen, I'm not doing odd things that tend to result in instanceof lies, such as creating instances using Object or creating instances in different frames.

If the module loader in does not "freeze" the initial invocation of a given module, subsequent  invocations will return new similarly shaped but not equal objects.

The other possible scenario, is the topology of modules shifts (do to the tool used for packaging) creating two discrete modules when one is expected.

I would hedge my bets this, or something like this is happening.

Is it possible for you to share a running example?

**Comment by sebmck** [comment]
As @stefanpenner said, this seems more like an issue with your module bundler.

**Comment by robhicks** [comment]
@stefanpenner Thanks for the response. I can try to work on getting something to share but it may be difficult. I'm not exactly sure how to mimic webpack building a bundle.

**Comment by sebmck** [comment]
@robhicks Any update?

**Comment by robhicks** [comment]
It was/is webpack. It creates a separate reference each time an import is used. It does a great job of only loading the code once but because a separate reference is used, instances created using the same code are different. So I have relaxed some of my instance checking while a search for a better solution.
