### ISSUE TITLE
Add linting task to Makefile to lint tests, babel-cli, and babel-runtime packages.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [babel/babel#1836]
Mostly to prevent mistakes such as https://github.com/babel/babel/pull/1832/files#r33310419, where a variable was used without being imported in a file that was not linted.

**Comment by sebmck** [comment]
Linting tests isn't really very productive. The styling of them is crazy and any errors in there will be caught.

**Comment by sebmck** [comment]
Oh and `babel-runtime` is dynamically generated so there's not much there either. Adding `packages/babel-cli/bin` to the `lint` `Makefile` task sounds good though.
