### ISSUE TITLE
Smoke tests

### ISSUE THREAD

**Issue by kittens** [babel/babel#1837]
- [ ] Ember
- [ ] react-bootstrap
- [ ] React
- [ ] test262
- [ ] everything.js

EDIT @hzoo
- [ ] react-native

**Comment by bloodyowl** [comment]
@substack has a good approach for this to test syntax while preventing code from running: https://github.com/substack/node-syntax-error/blob/master/index.js#L7-L15

**Comment by sebmck** [comment]
- [ ] Ember
 - [ ] react-bootstrap
 - [ ] React

**Comment by hzoo** [comment]
Would be nice to have a reverse https://greenkeeper.io (basically smoke/integration tests)

From slack http://babeljs.slackarchive.io/discussion/-/1475690057.003482/1475764305.003598/1475722841003580/

@ben-eb : https://www.npmjs.com/package/npm-list-package-dependents
@motiz88: Create a new repo with Babel + git submodules of dependents - use npm link and run test suites
Also: https://www.npmjs.com/package/dont-break

**Comment by motiz88** [comment]
@hzoo so basically `dont-break` for a monorepo, huh?

**Comment by motiz88** [comment]
Here's a first attempt at a CI setup designed to catch failures in third-party packages ahead of a babel/babylon release; [motiz88/babel-smoke-tests](https://github.com/motiz88/babel-smoke-tests). While implementing it I gave up on `npm link` and switched to fake-publishing a patch version to a local npm proxy.

Currently (see pain point 1 below) React is the only dependent tested, but the approach is applicable to other packages.

Likely pain points:

1. It's slow! Will definitely need to at least test each dependent separately, I guess using a Travis build matrix + env vars.
2. The need to manually (via PR) update both the third-party projects and Babel/Babylon. The former can be Greenkeeper'd with some trickery (list them in package.json & clone the appropriate commit in a postinstall script). As for the latter - I guess we can have a bot create PRs (or commit directly to `master`?) at the end of Babel's current CI script, for each successful build of Babel's `master`.

**Comment by hzoo** [comment]
Definitely want to do this, but not really anyone working on this atm. Going to make a new issue to cover at least building on itself (check if anything is broken before publish)
