### ISSUE TITLE
Automated browser tests

### ISSUE THREAD

**Issue by sebmck** [babel/babel#1838]
Long overdue. Using sauce labs preferably.

**Comment by samccone** [comment]
I can help with this

almost like I wrote the blog post on this
http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html

**Comment by samccone** [comment]
What browsers would we like?
What test cases would we like?

**Comment by sebmck** [comment]
There already exists a browser test suite. `$ make test-browser` will build all the tests files for delivery to the browser, then you can open `test/browser.html` and it's a standard mocha setup (No idea if it even still passes, been a while since I ran it and it's not a part of CI, hence this issue). No idea about browser support, whatever passes I guess :stuck_out_tongue:

**Comment by samccone** [comment]
Just a note, this ticket will mostly be blocked (since we can not run remote PRs on sauce) due to this ticket
https://github.com/travis-ci/travis-build/pull/356#issuecomment-124078458

I have gotten around this limitation on todomvc because we just test in chrome directly on travis, but for this case it seems like actually using sauce is pretty important

**Comment by samccone** [comment]
Ok, initially why don't I just set this up to work on travis in chrome to just run test-browser, and then when this travis ticket lands we can circle back and add in sauce :clap: :dog:

**Comment by sebmck** [comment]
Sounds good! :nail_care:

**Comment by samccone** [comment]
![screen shot 2015-07-28 at 10 03 21 pm](https://cloud.githubusercontent.com/assets/883126/8948362/7f032586-3574-11e5-8828-1f51cc250d09.png)

:grimacing:

**Comment by sebmck** [comment]
Oh...

**Comment by sebmck** [comment]
Looks to be a bug in my thing [mocha-fixtures](https://github.com/sebmck/mocha-fixtures). Options aren't properly being interpreted.

**Comment by samccone** [comment]
I can fix this also

**Comment by Dignifiedquire** [comment]
How about using [karma](https://github.com/karma-runner/karma) + karma-browserify + [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher)

**Comment by sebmck** [comment]
It's all in mocha at the moment and it's not really something I want to change.

**Comment by Dignifiedquire** [comment]
The idea would be to still have it in mocha, just using karma to run the tests in the browser instead of some other setup. (Karma only takes care of starting browsers, loading mocha and your code and then reporting about it)

**Comment by samccone** [comment]
/shrug not sure what it will save us ... plus @sebmck has already solved a fair number of issues with mocha-fixtures that we would have to redo :taxi: :fire: :e-mail:

**Comment by Dignifiedquire** [comment]
I've created #2163 to show how it would work. The main benefits would be, no more manual browser opening, it reuses the whole infrastructure that is already set up and it's very easy to add more browsers for any environment like sauce labs or locally to test multiple browsers.

**Comment by cesarandreu** [comment]
Maybe consider using [zuul](https://github.com/defunctzombie/zuul/)? It'll use SauceLabs and run your tests on all your specified browsers, based on your manifest. You can configure it to work with mocha by setting ui to `mocha-tdd` or `mocha-bdd` (whichever you're using).
