### ISSUE TITLE
Counter-hotlinking protection fails to transply regular ES6

### ISSUE THREAD

**Issue by koresar** [babel/babel#1842]
This exception is being thrown: https://github.com/babel/babel/commit/31c1286a3c9fdd7885c5e1974838b9b1e5a01327#diff-9c8bfd41ef9c341f0c726883c295dcceR7

The `module.parent.filename` and `root` values at this point are respectively:
```
/Users/vasylboroviak/code/base-rest-client/node_modules/babel/bin/babel/index.js
/Users/vasylboroviak/code/base-rest-client/node_modules/babel/node_modules/babel-core
```

This code causes regular ES6->ES5 transpilation to fail. We are not hotlinking any babel internal files (see the entire codebase below).
Our commad line: `babel src --out-dir dist -s`

Our `src` folder contains a single little `index.js` file:
```js
import url from 'url';
import requestOnPromises from 'request-promise';
import stampit from 'stampit';
import merge from 'lodash/object/merge';
import toPlainObject from 'lodash/lang/toPlainObject';

let ClientFactory = stampit({
  request(opts, callback) {
    opts = merge({}, this, opts);
    opts.url = url.format(opts.url);
    return requestOnPromises(opts, callback);
  }
}, {
  url: {
    port: 80,
    hostname: 'localhost',
    protocol: 'http'
  },
  json: true
}, function () {
  if (typeof this.url === 'string') {
    this.url = toPlainObject(url.parse(this.url, true));
  }
});

export default ClientFactory;
```

Please, unpublish the last babel from npm, or fix that.

Cheers.

**Comment by sebmck** [comment]
I've already unpublished that version and I have published a new version. As I replied to your comment in that commit, upgrade to 5.6.10.

**Comment by koresar** [comment]
Sorry for much texting. Thanks for the tip. I got that fixed.

**Comment by koresar** [comment]
The problem was in Travis-CI. It has the `5.6.9` cached at `@latest` as of yet.
