### ISSUE TITLE
Error: Symbol is not defined in Firefox and Chrome less than 38

### ISSUE THREAD

**Issue by fanhc019** [babel/babel#1843]
Yeah, I use babel-loader within webpack. And I found this Error within FireFox and Chrome 38-. The following is my config snippet:
```
var jsLoaders = ['babel?loose[]=all&stage=0'];
{
    test: /\.js$/,
    exclude: /node_modules/,
    loaders: jsLoaders,
},
```

**Comment by loganfsmyth** [comment]
You need to load a [polyfill](http://babeljs.io/docs/usage/polyfill/). The easiest way would be to add `import 'babel-core/polyfill';` in your application entry point.

**Comment by fanhc019** [comment]
@loganfsmyth I am very satisfied with your answer. And I have solved it.
