### ISSUE TITLE
Babel puts 'use strict'; in front of everything

### ISSUE THREAD

**Issue by marrs** [babel/babel#1844]
I've created the simplest babel programme I can think of, that I would expect to do nothing.

```javascript
var babel = require('babel-core');
var code = '"use strict;"';
var result = babel.transform(code);

// Expected result: "use strict";
// Actual result: "use strict"; "use strict";
```

I had presumed that a call to `transform` with no transformers specified would do nothing. At the very least it's forcing strict mode on me.  Is this a bug or a feature?  Are there other things babel forces on me by default?

**Comment by sebmck** [comment]
ES6 modules have an implicit strict mode so at the least you'll get `"use strict";` prepended to your program. Regarding:

> I had presumed that a call to `transform` with no transformers specified would do nothing.

Not sure what you mean by "no transformers specified", by default all the ES6/stable transformers are enabled.

Also FWIW, the strict directive is being duplicated because you've got the semicolon inside the string, moving it out results in the strict directive only being output once.

**Comment by marrs** [comment]
> Not sure what you mean by "no transformers specified", by default all the ES6/stable transformers are enabled.

Ah, can I disable them? I really only want Babel for its transpiling abilities.

> Also FWIW, the strict directive is being duplicated because you've got the semicolon inside the string, moving it out results in the strict directive only being output once.

I made a typo in the report above.  The original code implemented strict mode correctly, and still generated the duplicate declaration.

**Comment by sebmck** [comment]
> Ah, can I disable them? I really only want Babel for its transpiling abilities.

Strict mode is a part of that though?

> The original code implemented strict mode correctly, and still generated the duplicate declaration.

Nope?

```
> var babel = require('babel-core');
undefined
> var code = '"use strict";';
undefined
> var result = babel.transform(code);
undefined
> result.code;
'"use strict";'
```

**Comment by jmm** [comment]
@sebmck FWIW, there *is* a (different) `use strict` related bug that I noticed (that you very well may already know about). I decided not to mention it before because I didn't think you'd be terribly interested, but since there's already this discussion going on I figured I'd mention it (don't want to derail this though).

```
> var babel = require('babel-core');
undefined
> var code = '"use\\x20strict";';
undefined
> var result = babel.transform(code);
undefined
> result.code;
'"use strict";'
```

**Comment by sebmck** [comment]
@jmm Can you open a new issue? Should be easy enough to fix.

**Comment by jmm** [comment]
@sebmck Sure, see #1852.

**Comment by marrs** [comment]
@sebmck you're right, there was a bug in my test case.  I was echoing the output twice!
>>Ah, can I disable them? I really only want Babel for its transpiling abilities.

> Strict mode is a part of that though?

No. Why, should it be?  I'm experimenting with a superset of Javascript. For my own sanity, I'd like to be confident that the changes I get are just the changes I ask for.  I think I just made the case for that requirement at the top of this post :)

**Comment by sebmck** [comment]
@marrs 

> No. Why, should it be?

As I said before, ES6 modules have an implicit strict mode. Spec reference [here](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-strict-mode-code) if you don't believe me.

**Comment by marrs** [comment]
I see. It wasn't clear to me that Babel exclusively targets ES6. I deduced that it was written to enable ES6 compatibility in legacy browsers but the homepage gave me the impression it was also a general purpose transpiler.

**Comment by sebmck** [comment]
> It wasn't clear to me that Babel exclusively targets ES6.

It doesn't? Babel just has an comprehensive suite of ES6 transformers that are enabled by default.

> the homepage gave me the impression it was also a general purpose transpiler.

Yeah it is. There's a whole host of [plugins](https://github.com/babel-plugins). And [syntax extensions](https://github.com/babel/babel/issues/1351), [linting/static analysis](https://github.com/babel/babel/issues/1829) and [minification](https://github.com/babel/babel/issues/1828) is in the pipeline.

**Comment by marrs** [comment]
So can I disable them? It doesn't seem to be possible without modifying the code.  I have stripped them out of `transformation/index.js` in my fork to get the behaviour I want.  This seems to be the best I can do.

**Comment by sebmck** [comment]
You can disable any of the transformers. See the docs [here](http://babeljs.io/docs/advanced/transformers/) for a list of the built-in ones. And see the [strict transformer docs](http://babeljs.io/docs/advanced/transformers/other/strict/) on how to disable that particular behaviour.

**Comment by Wandalen** [comment]
Annoying issue, what a point to force "strict" mode?
@kittens links are dead!

**Comment by hzoo** [comment]
> ES6 module code, which Babel expects by default, is automatically Strict Mode according to the ES6 spec
