### ISSUE TITLE
100% test coverage

### ISSUE THREAD

**Issue by kittens** [babel/babel#1851]
Once this is done Travis should refuse to publish new versions unless it's at 100%.

**Comment by arthurvr** [comment]
Related: document how to run the coverage check (in `contributing.md`)

**Comment by sebmck** [comment]
FWIW, it's `make test-cov`.

**Comment by arthurvr** [comment]
Yeah, I knew. Still worth documenting don't you think? Happy to PR.

**Comment by sebmck** [comment]
Yeah definently, just noting in case someone is looking for it in the interim. PR would be awesome!

**Comment by hzoo** [comment]
Closing out some old issues - code coverage should be on everyone's mind
