### ISSUE TITLE
Error not forwarded when async function returns a promise

### ISSUE THREAD

**Issue by julien-f** [babel/babel#1853]
Code:

```javascript
async function f () {
  return new Promise((resolve, reject) => {
    reject(new Error('foo'))
  })
}

f().then(
  value => console.log('success', value),
  error => console.error('failure', error)
)
// Prints 'success undefined' instead of the error.
```

`.babelrc`:

```json
{
  "optional": [
    "es7.asyncFunctions",
    "runtime"
  ]
}
```

Tested on Node 0.10 with babel-runtime enabled and disabled.

> Note: the issue does not appear if the promise is `await`ed.

**Comment by julien-f** [comment]
Test repository: https://github.com/julien-f/test-babel-issue-1853

**Comment by julien-f** [comment]
And the link to the [repl](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=async function f %28%29 {%0A  return new Promise%28%28resolve%2C reject%29 %3D> {%0A    reject%28new Error%28'foo'%29%29%0A  }%29%0A}%0A%0Af%28%29.then%28%0A  value %3D> console.log%28'success'%2C value%29%2C%0A  error %3D> console.error%28'failure'%2C error%29%0A%29%0A%2F%2F Prints 'success undefined' instead of the error.). :)

**Comment by loganfsmyth** [comment]
Seems like this would be a `regenerator` issue rather than a Babel issue.

**Comment by sebmck** [comment]
Fixed via facebook/regenerator@5b9dd1086d03c96fd9bc9833f67314f98e63718e.

**Comment by domenic** [comment]
The linked regenerator fix doesn't seem to have anything to do with the OP. The linked commit is about async generators; this is about async functions.

**Comment by loganfsmyth** [comment]
@domenic Looks like the PR that addressed this issue had a few commits, one of which @sebmck referenced and one of which was https://github.com/facebook/regenerator/commit/29d81b69291bb51228fb9b5c930a3dc2eff444f9 which more directly addresses this issue.

**Comment by domenic** [comment]
Got it, thanks!
