### ISSUE TITLE
Automate commenting on issues saying fixed in X version

### ISSUE THREAD

**Issue by kittens** [babel/babel#1857]

**Comment by grabbou** [comment]
Is there already a bot/tool for that? If not, I can look into that and probably create another library as this is something we've been in a need of in few projects.

**Comment by sebmck** [comment]
Not that I know of. If you could look into it then that'd be rad. Would ideally just be able to provide a GitHub token, repo name, previous commit and current commit and find the issues closed in all commits in between.

**Comment by grabbou** [comment]
Yeah, that could work. Another entry point might just work automatically by getting latest and previous release and building up commits list based on that?

**Comment by hzoo** [comment]
I think this would still be cool to have!

**Comment by hzoo** [comment]
This would be great but doesn't need to be an issue in the repo - will try to do this though.

**Comment by zeke** [comment]
https://github.com/apps/release-notifier might do the trick. Feel free to give it a try and let me know how it goes.

**Comment by hzoo** [comment]
Yeah I'll give it a shot - does it use the github release event with git tags?

**Comment by jasonLaster** [comment]
Nice work!

**Comment by zeke** [comment]
> does it use the github release event with git tags

@hzoo yes. As long as you're using semver and GitHub Releases, it should work. In the process of adding tests, CI, etc right now.
