### ISSUE TITLE
[enhancement][plugins] builder API validation

### ISSUE THREAD

**Issue by amasad** [babel/babel#1858]
Not sure if it'll make things slower -- but it'll be great if the builder API validated it's inputs early on. Right now if you passed, for example null, as one of the required arguments you'll get an obscure error at the generation phase and it's really hard to debug.

**Comment by sebmck** [comment]
Performance hit would probably be negligible. It could be disabled via an environment variable or something for those who don't care. The node types/builders really need to rewritten since right now there's just a bunch of blobs of JSON.
