### ISSUE TITLE
Use function to filter ignore/only in babel/register

### ISSUE THREAD

**Issue by timoxley** [babel/babel#1859]
I'm using a lot of local npm dependencies. As an install-time optimisation I've pushed `babel` out of their dependencies and into the container application. 

Problem is, as these dependencies exist at various levels inside the node_modules tree, it's a pain in the ass to write a regex for `babel/register` that matches all my internal dependencies, while trivial to implement as a function. Unfortunately, there's currently no way to use custom logic to determine what gets included or not; must use regex edit: or glob. This problem would go away if it were possible to pass a function as `babel/register`'s `ignore/only` options.

Previously I was in a rush, so I'd simply monkeypatched `util.shouldIgnore` to implement the logic I needed, but this new internal api protection put the kibosh on that and reminds me that I should look into a less hacky solution.

**Comment by sebmck** [comment]
You can specify path globs, you don't **have** to only use a regex.

**Comment by timoxley** [comment]
oh yes, though glob still not great.
