### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by rblakeley** [babel/babel#1863]
I'm getting a `SyntaxError: Invalid regular expression` when using babel-browser.

From #340, I tried setting the character encoding to utf-8 where I could.

I'm running a simple python server.

```
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <script src="js/vendor/react.min.js"></script>
    <script src="js/vendor/babel-browser.js" charset="utf-8"></script>
    <script src="js/vendor/es6-module-loader.js"></script>
    <script src="js/vendor/sort-by.min.js"></script>
    <script type="text/babel" src="js/app.js"></script>
```

**Comment by sebmck** [comment]
As #340 says, use `<meta charset="utf-8">`.

**Comment by rblakeley** [comment]
@sebmck I showed in the copied code that I was already using that approach and it was not the missing piece. I ended up having to use the es6-module-loader api to pull in app.js. Referencing it in the html doc with a `<script type="text/babel"` never worked.

**Comment by jmm** [comment]
@rblakeley What, if any, `Content-Type` headers is your server sending for that page?

**Comment by rblakeley** [comment]
Looks like the `Content-Type` header is `text/html` despite the meta tag. 

Stupid `python -m SimpleHTTPServer` gets around cross-origin request blocks against using a library to load es6 modules, which is the only reason I am using a server at all.

And I read somewhere that babel only transpiles es6 __syntax__, not modules. Which is why I swapped out `<script type="text/babel" src="js/app.js"></script>` for:
```
<script src="js/vendor/es6-module-loader-dev.src.js"></script>
<script>
  System.transpiler = 'babel';
  System.import('js/app.js').catch(function (e) {
    console.error(e);
  });
</script>
```

**Comment by jmm** [comment]
@rblakeley The meta tag won't have any effect on the value of the `Content-Type` header, if that's what you mean. But the reason I asked is that if the header contains a `charset` param, that's what would be used, not the `charset` specified in the meta tag.

> And I read somewhere that babel only transpiles es6 **syntax**, not modules.

Well, it transpiles syntax including the module syntax, but module loading is a separate problem. For example, you can transpile to CommonJS modules and bundle them with browserify.
