### ISSUE TITLE
Preserve ASI 

### ISSUE THREAD

**Issue by GianlucaGuarini** [babel/babel#1866]
I know you have already answered to this question but I would like to ask you whether it makes sense at least to have an option to preserve the ASI in the output.
Input
```javascript
var Foo = (bar) => bar
```
Output
```javascript
"use strict";

var Foo = function Foo(bar) {
  return bar;
};
```
Desired
```javascript
"use strict"

var Foo = function Foo(bar) {
  return bar
}
```
We would like to use babel in [riot](https://github.com/riot/riot) but we need also to keep the riot codestyle in the output
Thanks

**Comment by novacrazy** [comment]
This has been up for a few days now, so I'll go ahead and ask. Is there a reason why you can't change your code style to use semicolons at the end of statements? Even though it's entirely optional in JavaScript, it can still prevent bugs in some places and make code clearer to read. That's just my opinion, though.

**Comment by GianlucaGuarini** [comment]
@novacrazy thanks for your answer but your solution is not a solution :smile: ! 
A babel user __should not be forced changing his/her codestyle__. I think __babel should preserve the codestyle of their users__. Stuff like semicolons, spaces before functions, single quotes vs double quotes... should be preserved in the output, or at least there should be an option to define the output code style.
@sebmck what do you think?

**Comment by novacrazy** [comment]
It wasn't meant to be a solution, I was just curious if you had anything against it. Though if your output isn't going to be read by humans, only by the interpreter, I'm not sure how much code style really matters. Especially if your output code is going to be minified, which also loses all code style. Still, I understand where you're coming from.

**Comment by sebmck** [comment]
ASI in a code generator is extremely complicated and not performant since it requires **a lot** of lookbehinds to determine if one is needed. I'm not completely sure how this would work.

**Comment by GianlucaGuarini** [comment]
@novacrazy As babel user I do not need always to minify my output check this example [dist](https://github.com/GianlucaGuarini/Caronte.js/blob/master/dist/Caronte.js) [src](https://github.com/GianlucaGuarini/Caronte.js/blob/master/src/index.js)

>  Still, I understand where you're coming from.

what do you mean?

> ASI in a code generator is extremely complicated and not performant since it requires a lot of lookbehinds to determine if one is needed. I'm not completely sure how this would work.

@sebmck I know I am just trying to understand whether there is a solution better than ``output.replace(/;/g, '')``

**Comment by sebmck** [comment]
I don't understand why it's a problem if it's in your output at all.

**Comment by Dashed** [comment]
> I think babel should preserve the codestyle of their users.

IMO, this shouldn't be babel's mandate. This is totally different from babel's mission to make the output **readable**. 

-----

You don't really need to read your output if you just work off of your original source code (assuming the babel transpiles correctly), and through sourcemaps when debugging.

**Comment by stefanpenner** [comment]
Seems high cost with little value. I believe there are tools that already do the asi transform, maybe just run that after babel to get your semi colon preference?

It does appear strange to have a strong feeling about this. Especially since babel ships with great sourcemaps.

**Comment by GianlucaGuarini** [comment]
@stefanpenner Ok so you suggest to parse the babel output with tools like https://www.npmjs.com/package/esformatter-asi
That's ok for me, I just wanted to know if this was directly possible in babel.

**Comment by Dashed** [comment]
@GianlucaGuarini it is possible. where there is a will, there is a way. it's just hard due to many edge cases that ASI impose.

**Comment by GianlucaGuarini** [comment]
Maybe this should be handled in a babel plugin something like babel-esformatter

**Comment by sebmck** [comment]
Closing this as it'd add **significant** complexity to the code generator and would make the performance of it worse than it already is. The very small benefits of having semicolons omitted in the output is negligible. The likelihood of plugins being able to effect code generator output in the future is unlikely.
