### ISSUE TITLE
[plugins] scope.push not traversing to the nearest scope

### ISSUE THREAD

**Issue by amasad** [babel/babel#1870]
I'm getting an error in certain cases using `scope.push({ id })`: 
`We don't know what to do with this node type. We were previously a statement but we can't fit in here?`

I can write a test case later but I wanted to log it so I don't forget. I'm currently working around it by doing `scope.getFunctionParent().push`.

This happens when I'm visiting node create from a previous visitor. In my case I have two visitors one is `ClassExpression` and the other is `ClassDeclaration`. The `ClassExpression` is converting itself to `ClassDecleration`. Inside the `ClassDeclaration` it's doing the scope.push and getting the error.

**Comment by sebmck** [comment]
@amasad Didn't get around to following up. Is it still an issue?

**Comment by amasad** [comment]
Don't know. Feel free to close it for now. Will look it up if it showed up again.
