### ISSUE TITLE
Value defaulting doesn't preserve nesting structure.

### ISSUE THREAD

**Issue by lxe** [babel/babel#1871]
```javascript
var {
  foo = 'foo should be this',
  bar = {
    foo = 'not this'
  } = {}
} = {}

console.log(foo) // 'not this'
```

Is this expected ES6 behavior?

**Comment by sebmck** [comment]
Yep, prior bindings have no influence over it.

**Comment by lxe** [comment]
@sebmck what do you mean 'prior bindings'? So nested default values just go to the top of the scope?

**Comment by sebmck** [comment]
The output is correct. `foo = 'not this` is the final binding. The previous one is shadowed. Why do you think it should fall back to the first one?

**Comment by lxe** [comment]
Yes, I think that values in the nested object should not override the ones at the parent scope. The resulting scope should possibly look like:

```
foo = 'foo should be this'
bar = {}
```

But I could be very wrong about this behavior.

**Comment by sebmck** [comment]
I'm confused by your usage of "scope". There's only one lexical scope at play here and it's the entire program. The Babel output is expected. Assignment patterns in object patterns assign the right side to the left if that property is `undefined`. This means that the second one shadows the first.

**Comment by lxe** [comment]
Aside: is it OK to default arbitrary values? I thought this should only apply to function arguments anyways?

It would make more sense in context of functions:

```
function destructuringDefault({
  foo = 'foo should be this',
  bar = {
    foo = 'not this'
  } = {}
} = {}) {
  console.log(arguments); // what should 'foo' be?
});
```

**Comment by sebmck** [comment]
What does `foo` have to do with `arguments`? It depends on the arguments that the function is called with.

**Comment by lxe** [comment]
> What does foo have to do with arguments? It depends on the arguments that the function is called with.

Sorry updated my example:

```javascript
function destructuringDefault({
  foo = 'foo should be this',
  bar = {
    foo = 'not this'
  } = {}
} = {}) {
  console.log(foo); // what should 'foo' be?
});
```

**Comment by sebmck** [comment]
It depends on the arguments that the function is called with.

**Comment by lxe** [comment]
> It depends on the arguments that the function is called with.

```javascript

destructuringDefault();
// foo is 'not this', I think it should be 'foo should be this'

destructuringDefault({bar: 'anything'});
// foo is 'foo should be this', as it should be
```

**Comment by sebmck** [comment]
> ```javascript
> // foo is 'not this', I think it should be 'foo should be this'
> ```

Why should it be `"foo should be this"`? The `foo = 'not this'` condition is the last to be executed and evaluate to `undefined`.

**Comment by lxe** [comment]
> Why should it be "foo should be this"? The foo = 'not this' condition is the last to be executed and evaluate to undefined.

That makes sense in a classic sense:

```
foo = 1;
{ // scope
  foo = 2;
}
```

But I thought scoping would work differently in the context of default function arguments. I took the example from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Function_argument_defaults and merely introduced nesting.

It is a bit wacky, but I think I get it.

**Comment by loganfsmyth** [comment]
@sebmck In his example shouldn't they BOTH be `'not this'`?

**Comment by sebmck** [comment]
@lxe I think you're confusing block scoping and destructuring. They're completely different and the fact that they share syntax is only consequent of objects and blocks using curly braces.

@loganfsmyth The `bar` default is never evaluated because it exists. I'll have to consult the spec.

**Comment by lxe** [comment]
> @lxe I think you're confusing block scoping and destructuring. They're completely different and the fact that they share syntax is only consequent of objects and blocks using curly braces.

Yes. The original example was wrong I think... I was trying to simplify it.

**Comment by loganfsmyth** [comment]
@sebmck Ah, I actually misread that snippet, that seems right to me nevermind.

**Comment by lxe** [comment]
I'm still confused. I updated the original example in the context of default function arguments. I still think it should not be overriding `foo`. 

What's the proper way to default nested parameters? Does this mean that the syntax of `function({ key = defaultValue } = {})` only works for top-level arguments?

**Comment by loganfsmyth** [comment]
@lxe If you'd like, feel free to join the [Slack channel](https://babel-slack.herokuapp.com/) to chat more. I'm still not  exactly sure I understand the confusion here but I'll try to elaborate.

Your code:
```
function destructuringDefault({
  foo = 'foo should be this',
  bar = {
    foo = 'not this'
  } = {}
} = {}) {
  console.log(foo); // what should 'foo' be?
});
```

As approximate ES6:
```
function destructuringDefault(opts = {}){
  var foo = opts.foo === undefined ? 'foo should be this' : opts.foo;

  // This means that here, when `opts.bar === undefined`, you will essentially do:
  // foo = {}.foo === undefined ? 'not this' : {}.foo
  var bar = opts.bar === undefined ? ({foo = 'not this'} = {}) : opts.bar;

  console.log(foo); // what should 'foo' be?
});
```

As approximate  ES5:
```
function destructuringDefault(opts){
  // Assign defaults based on the outermost `= {}` default argument value.
  opts = (opts === undefined ? {} : opts); 

  // Assign defaults based on the destructured 'foo' param.
  var foo = opts.foo === undefined ? 'foo should be this' : opts.foo;

  // Assign defaults based on the destructured 'bar' param.
  var bar = opts.bar;
  if (bar === undefined){
    var tmp = {};

    // Re-assign foo based on the temporary value.
    foo = tmp.foo === undefined ? 'not this' : tmp.foo;

    // Assign the default value to 'bar'
    bar = tmp;
  }

  console.log(foo); // what should 'foo' be?
});
````

which should explain why you get `'not this'` in the first case and `'foo should be this'` in the second.

The issue really seems to be that I have having a very hard time trying to understand exactly what you are trying to do. Why would you assign to a variable with the same name, `foo`, twice.

The other big question for me is, do you mean to do
```
function destructuringDefault({
  foo = 'foo should be this',
  bar: { // Note the `:` instead of the `=` here.
    foo = 'not this'
  } = {}
} = {}) {
```
