### ISSUE TITLE
async/await "all" behavior for bluebirdCoroutines

### ISSUE THREAD

**Issue by wavded** [babel/babel#1873]
I can do the following without any optional and I get the `Promise.all` behavior as per the spec.

```
await [ array, of, promises ]
```

I also get the correct behavior using the `asyncToGenerator` optional.  But it fails when using the `bluebirdCoroutines` option with:

```
A value [object Promise],[object Promise] was yielded that could not be treated as a promise
```

**Comment by sebmck** [comment]
How is this a Babel issue? Seems like it should be taken up with Bluebird.

**Comment by sebmck** [comment]
Actually, 99% sure Bluebird's behaviour is right. Please cite a reference for your "as per the spec" statement.

**Comment by benjamingr** [comment]
Actually, bluebird is correct here, yielding arrays isn't supported. 

What bluebird does is refuse to call `await` on non-thenables. You can of course `addYieldHandler` to bluebird and do this. 

On the other hand, the proposed async/await semantics would `Promise.resolve` (and __not__ `Promise.all` the array) which would bring you back the same array (where individual promises were not awaited).

**Comment by wavded** [comment]
My tip off was this discussion here... I'm confused what should be the behavior should be:

https://github.com/tc39/ecmascript-asyncawait/issues/46

**Comment by sebmck** [comment]
The issues referenced in the issue you linked discuss `await*` not `await`.

**Comment by wavded** [comment]
@sebmck how come `await [ array, of, promises ]` behavior is `Promise.all(array, of, promises)` in babel, are we saying that's a mistake and Bluebird behavior is correct?

**Comment by benjamingr** [comment]
That's likely an opinionated choice by regenerator that diverges from the spec.

**Comment by wavded** [comment]
Hmm.. `await*` does what I was expecting with bluebird.

**Comment by sebmck** [comment]
Both the `asyncToGenerator` transformer and `regenerator` use `Promise.resolve`, as the spec defines.

**Comment by benjamingr** [comment]
Yes, I just checked both transforms are correct here:

 http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=let%20delay%20%3D%20ms%20%3D%3E%20new%20Promise(r%20%3D%3E%20setTimeout(r.bind(null%2C3)%2C%20ms))%3B%0Aasync%20function%20foo()%7B%0A%20%20let%20res%20%3D%20await%20%5B1%2C2%2Cdelay(1000)%5D%0A%20%20console.log(res%2C%20await%20res%5B2%5D)%3B%0A%7D%0Afoo()%3B

**Comment by wavded** [comment]
OK, yeah, now I'm seeing it, I just get an array of promises back where `await *` gives me back the data.  I do like Bluebird's behavior best now as it warns that this isn't what you want.  Thanks for the discussion.
