### ISSUE TITLE
Array.prototype.includes is not a function

### ISSUE THREAD

**Issue by lovedota** [babel/babel#1875]
hi guys
i am using

```
"babel-core": "^5.6.15",
 "babel-eslint": "^3.1.19",
 "babel-loader": "^5.2.2",
"babel-runtime": "^5.6.15",
```

BabelJs is missing ```Array.prototype.includes is not a function```
Could you please help me to specify the option to use includes methods. Thanks !

**Comment by loganfsmyth** [comment]
Please see the [README](https://github.com/babel/babel#readme):

> For questions and support please visit the [slack channel](https://babel-slack.herokuapp.com/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs). The Babel issue tracker is exclusively for bug reports and feature requests.

Thank you!
