### ISSUE TITLE
Cannot get values from `await`

### ISSUE THREAD

**Issue by ajcrites** [babel/babel#1876]
It seems that you cannot do assignment with values in `await` in babel (using `--stage 1` or `--stage 0`):

    require("babel/polyfill");

    (async function () {
        let value = "value";
        let x = await new Promise(function (resolve) { resolve(value) });
        console.log(x); // undefined
    })();

However, using `regenerator` with the above, `x` will indeed be `'value'`.

[The async functions](https://github.com/lukehoban/ecmascript-asyncawait) proposal seems to indicate that you should be able to do assignments from `await`, so this seems like a bug.

This is most likely a related bug, so I'm also reporting it as part of this.  It also *seems* like `babel` will only run two `await`s and crash after the second is completed:

    require("babel/polyfill");

    (async function () {
        let value = "value";
        let x = await new Promise(function (resolve) { resolve(value) });
        let y = await new Promise(function (resolve) { resolve(value) }).then(function () { console.log("resolved second"); return true; });
        let z = await new Promise(function (resolve) { resolve(value) }).then(function () {  console.log("resolved third"); return true; });
        console.log(x, y, z); // undefined
     })();

With `babel --stage 1` the above will log `resolved second` and nothing else.  Using `regenerator`, `resolved second`, `resolved third`, and `value value value` are all logged.

**Comment by sebmck** [comment]
See tc39/ecmascript-asyncawait#41. This is how Promises work.

**Comment by ajcrites** [comment]
This is not the issue. I am not returning a promise from the `async` function. As I point out, `let x = ...` should ultimately result in `x` being set to `'value'`, but it's not -- it's `undefined` after the first `await` completes.

The spec indicates that `x` should be equal to `'value'`. When running the same code through `regenerator`, `x` does indeed equal `'value'`.

Please let me know if I can be clearer on the issue.

**Comment by sebmck** [comment]
Oh right, well I can't reproduce this:

```
$ babel-node test.js --stage 0
value
$ cat test.js
(async function () {
    let value = "value";
    let x = await new Promise(function (resolve) { resolve(value) });
    console.log(x); // undefined
})();
```

**Comment by ajcrites** [comment]
Updated babel from `5.4.7` to `5.6.14` -- appears fixed.  Thanks.
