### ISSUE TITLE
Class transform should retain constructor position

### ISSUE THREAD

**Issue by amasad** [babel/babel#1877]
In the compiled code the constructor is pushed on as the first item in the class closure body hence breaking `retainLines`. The constructor should appear in the place it was found. This works well because of hoisting.

Currently:
```
class x {
  f() {
    1
    2
    3
  }
  constructor() {
    4
    5
    6
  }
}
```

Compiles to:
```
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var x = (function () {
  function x() {
    4;
    5;
    6;

    _classCallCheck(this, x);
  }

  x.prototype.f = function f() {
    1;
    2;
    3;
  };

  return x;
})();
```

Should compile to:

```
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var x = (function () {
  x.prototype.f = function f() {
    1;
    2;
    3;
  };

  function x() {
    4;
    5;
    6;

    _classCallCheck(this, x);
  }

  return x;
})();
```

**Comment by sebmck** [comment]
This will work for loose mode but it wont do anything for normal mode.

**Comment by sebmck** [comment]
Actually, it probably could by splitting up the `createClass` calls. I'll look into it.

**Comment by amasad** [comment]
thanks!

**Comment by sebmck** [comment]
No problem! Still some weird failing tests that I'll fix and push out a new release. Do you think it'd be worth printing out a warning when `retainLines` is enabled and the buffer offset is already higher than the original source location to catch these quicker?

**Comment by amasad** [comment]
No rush, luckily most write the constructor as the first thing. Yes, a warning would be great.
