### ISSUE TITLE
Constant value can be changed in babel-node's REPL without error output

### ISSUE THREAD

**Issue by ggrks** [babel/babel#1879]
```
$ babel-node
> const PI = 3.14
'use strict'
> PI = 0 // Try to change a constant value
0
> PI
0
>
```
This problem only happens inside the REPL, it should throw an error since `babel` and `babel-node -e` can produce the error correctly.
*Babel version: v5.6.14*

**Comment by loganfsmyth** [comment]
The Babel CLI REPL pretty much just compiles one line at a time and runs it in node and `const` checking only happens at compile time. That means that by the time you run two separate lines, `PI` is just `var PI` and there is no const checking. Babel would have to somehow preserve scope info between line compilations, which would be difficult for what seems like minimal gains.

**Comment by ggrks** [comment]
@loganfsmyth 
The latest nodejs and iojs have basic support for these ECMAScript 6 features, so I'm wonder if it's possible to do some checks when open the REPL, and only compile the line of code contains syntaxes that current environment does not support?

**Comment by sebmck** [comment]
See discussion in #1728, #1488 and #1264.
