### ISSUE TITLE
Entry for Fly JS plugin => `fly-babel`

### ISSUE THREAD

**Issue by bucaran** [babel/babel#1880]
I have just [recently published](https://github.com/flyjs/fly) a new build system and task automator based in generators and co-routines written in ES6 and written a babel plugin for it. It is currently hosted at [`bucaran/fly-babel`](github.com/bucaran/fly-babel), but in the same vein of other build system tools such as gulp and grunt, I would like to nominate the repository for its incorporation into the babel organization.

Cheers

> EDIT: Changed babelify to babel.

**Comment by loganfsmyth** [comment]
I don't have any input for org inclusion, but I will say that I feel like including `ify` in the name is super confusing since that suffix is so strongly tied to Browserify. `fly-babel` or `babel-fly` seem like they would be much less confusing to users.

**Comment by bucaran** [comment]
@loganfsmyth That makes sense, and I agree with you. I will go update the name ASAP.

**Comment by bucaran** [comment]
@loganfsmyth [Done](https://www.npmjs.com/package/fly-babel).

**Comment by sebmck** [comment]
Not sure if such a young project should have official integration just yet.

**Comment by bucaran** [comment]
Young indeed. Thanks @sebmck, you are right I was just nominating the project for inclusion. As the days go by and more dev time is committed to the project I hope you can seriously consider the official integration then.

**Comment by loganfsmyth** [comment]
@bucaran Mind if this is closed for now then?

**Comment by bucaran** [comment]
Sure. I will reopen if it keeps keeps gaining attention. I thought the integration would be acceptable after seeing `gobble-babel` in the organization.

Regards.
