### ISSUE TITLE
async arrow functions and rest parameters

### ISSUE THREAD

**Issue by chtefi** [babel/babel#1882]
Hi,

It seems there is a bug when combining async + rest parameters syntax.
Here is a simplified version that reproduces the case with a simple async of value.

```javascript
const foo = async (...msgs) => {
  let t = await msgs[0];
  console.log(t);
}

foo('a'); // displays "{}" instead of "a" value
```

Just by adding `console.log(msgs)`, it makes it work.

```javascript
const foo = async (...msgs) => {
  console.log(msgs);
  let t = await msgs[0];
  console.log(t);
}

foo('a'); // displays "a" 
```

Basically, adding `console.log(msgs)` moves the args to a distinct array:

```
for (var _len = arguments.length, msgs = Array(_len), _key = 0; _key < _len; _key++) {
    msgs[_key] = arguments[_key];
  }
```

In the repl: 
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20asyncArg%20%3D%20async%20(msg)%20%3D%3E%20%7B%0D%0A%20%20let%20t%20%3D%20await%20msg%3B%0D%0A%20%20console.log(t)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20asyncArgs%20%3D%20async%20(...msgs)%20%3D%3E%20%7B%0D%0A%20%20let%20t%20%3D%20await%20msgs%5B0%5D%3B%0D%0A%20%20console.log(t)%3B%0D%0A%7D%0D%0A%0D%0AasyncArg('1')%3B%0D%0AasyncArgs('2')%3B%0D%0A

**Comment by sebmck** [comment]
Why are you `await`ing strings?

**Comment by chtefi** [comment]
I simplified my example.
Originally, I had a promise, such as:

```javascript
const echo = (msg, delay = 100) => new Promise((resolve) => setTimeout(()
=> resolve(msg), delay));

const asyncArgs = async (...msgs) => {
  let t = await echo (msgs[0]);
  console.log(t);
}

asyncArgs('foo'); // outputs {}

```

**Comment by chtefi** [comment]
I simplified my example.
Originally, I had a promise, such as:

```javascript
const echo = (msg, delay = 100) => new Promise((resolve) => setTimeout(()
=> resolve(msg), delay));

const asyncArgs = async (...msgs) => {
  let t = await echo (msgs[0]);
  console.log(t);
}

asyncArgs('foo'); // outputs {}
```

**Comment by sebmck** [comment]
It's because of the arrow function. I'll try and look further into it when I can.

**Comment by loganfsmyth** [comment]
@sebmck Played around with this a bit. It looks like regenerator is stripping off the `_shadowedFunctionLiteral` from the `arguments` node so it loses track of which function the `arguments` belongs to.

**Comment by sebmck** [comment]
Fixed in the `development` branch due out for Babel 6.
