### ISSUE TITLE
Mix babel CLI options with a .babelrc file

### ISSUE THREAD

**Issue by dbabaioff** [babel/babel#1886]
Would be nice if you can pass to the CLI a babelrc file with more options - this way you can customize different options based on different criterias.

Like this:
```
$ babel script.js --out-file script-compiled.js --babelrc PATH_TO_BABELRC_FILE
```

**Comment by sebmck** [comment]
The `.babelrc` file is already resolved relative to your input filename.

**Comment by Mark-Simulacrum** [comment]
I'm guessing that the request is to allow placing `.babelrc` files non-relative to input filename (input in `/home/user/projectA/a.js` and the `.babelrc` in `/home/user/rcfiles/.babelrc`.

Not sure how much of a use case I can see for this pattern.

If we're looking for precedent, ESLint provides this option ([`-c / --config`](http://eslint.org/docs/user-guide/command-line-interface#c-config)), JSHint does as well ([`--config`](http://jshint.com/docs/cli/#flags)).

**Comment by dbabaioff** [comment]
Exactly, I wanted to have on .babelrc file in a different path to input filename

**Comment by sebmck** [comment]
Added via 9efb02f60f8f15518e9e4636846f1563b2d73fe8. Will comment when this makes it into a release, thanks! :blush:

**Comment by dbabaioff** [comment]
:+1:

**Comment by thealjey** [comment]
@sebmck this does not work in Babel 6 any more, the "babelrc" option is type "boolean" (not "list")
Did this get reverted after v5.6.17?
I would really love to have this feature back, please... :blush:
