### ISSUE TITLE
Being prepared for getting hit by a bus

### ISSUE THREAD

**Issue by benjamingr** [babel/babel#1888]
So, I had a discussion with a colleague today about Babel, we're [very early adopters](https://github.com/babel/babel/issues/364#issuecomment-69474761) of babel and fans of the project. 

I get a strong feeling that @sebmck , [having amazing execution](https://github.com/babel/babel/graphs/contributors) and being a total baller _is_ babel in a sense. He makes the most commits and most contributions by far, has the most insight and knows the code base the best by far. This is not to take from the contributions others have made of course.

Now, I'm a fan of @sebmck and I've enjoyed interactions with him very much - but I wonder, what happens if he ever loses interest, has something else he has to take care of or just feels like taking a year-long trip around the world? 

I'm sorry if this comes off the wrong way - but what happens when @sebmck is no longer interested or able to take care of the project for whatever reason? I think given how much money people have invested in code that runs Babel it would be wise to at least have a clear plan for when/if that day comes.

**Comment by sebmck** [comment]
@thejameskyle has access to everything that I do. I've been very vocal about wanting more core contributors (#1347) so I'm unsure what else can be done?

**Comment by benjamingr** [comment]
I'm unsure either, I think it's important to discuss. Honestly what I'm rooting for is some company like Facebook or Yahoo that uses Babel extensively to step up and dedicate resources and people to work with/for you.

Pretty much the way the open source projects like NodeJS and io.js (or the Linux kernel for that matter) where there is a TC (which presumably you'll be in charge of) and companies contribute resources and people to maintain the project.

**Comment by jmm** [comment]
IMO the most helpful thing for delegating the workload in the short term would be more comprehensive documentation of the APIs and architecture (including in source code comments). I know it's probably a catch-22 for finding the time to do it, but I think it can really help get more people involved.

**Comment by sebmck** [comment]
@benjamingr I may have some relevant news in the next few weeks then.

**Comment by benjamingr** [comment]
@sebmck That's very reassuring, like I said - I have nothing but mad respect for your firm grip of the project, responsiveness and execution ability but babel's maintenance has become business-critical to a lot of companies - I hope this issue didn't come off the wrong way.

If you don't object - can we keep this issue open for a few days to see if anyone has anything to add to the discussion?

**Comment by sebmck** [comment]
I'm more than happy for this issue to be open for as long as it's a concern to you and the community. No problem about it coming off the wrong way, I know exactly what you mean and feel the same way.

**Comment by chicoxyzzy** [comment]
I think @jmm is right. Every time I trying to start learning Babel's internals I realise that it is very hard and I have no so much free time for reverse engineering. Would be cool if someone will add some docs for developers who are interested in contribution.

**Comment by sebmck** [comment]
Is there any precedent for this in existing projects? Would be good to have some references. It's a circular problem where if there's not enough time for core development then there's certainly not enough time to write docs.

**Comment by jmm** [comment]
Precedent regarding the documentation part of it? There's certainly a rich tradition of underdocumented open source software. I think this project is a pretty special combination of complexity and rapid adoption though, with the vast majority of knowledge about how it all works concentrated in one person.

> It's a circular problem where if there's not enough time for core development then there's certainly not enough time to write docs.

I think it'd be valuable to discuss how to chip away at that -- in my opinion it has to happen for contribution to rise significantly.

**Comment by sebmck** [comment]
Precedent for large documentation on project internals.

**Comment by benjamingr** [comment]
Well, there's linux, but that's hardly a good example. In terms of
compilers and runtimes the most common thing by far is blog post tutorials
like
http://blog.ircmaxell.com/2012/03/phps-source-code-for-php-developers_21.html



On Wed, Jul 1, 2015 at 4:56 PM, Sebastian McKenzie <notifications@github.com

**Comment by jmm** [comment]
@sebmck Right now it's kind of non-existent, so I would suggest focusing on going from that to "some", instead of thinking about going from that to "large".

**Comment by thejameskyle** [comment]
***If Seb Dies Contingency Plan:***
- Sell out.


Kidding aside, this has been a concern of mine for months. I've been hoping that the plugin ecosystem would kick off and pull in people who know about how ASTs/Compilers/Parsers/etc. work and are willing to contribute back.

In case of things going terribly wrong, I'd likely try getting people from the biggest users like Facebook, Netflix, Yahoo, etc. to help take it over. Although I haven't contributed to the babel codebase itself in awhile, I do try and keep myself familiar with the codebase and could give people introductions to it.

I think a good place to start would be to scatter some READMEs in the various directories explaining what's there and how they relate to each other. Once that is there we can dive into the most important files are start leaving code comments to explain them.

I'll start something now

**Comment by benjamingr** [comment]
@thejameskyle switch to a freemium model 😅😅😅

**Comment by mathieumg** [comment]
> switch to a freemium model

All stage 2+ transforms are free, open your wallet for the rest! :stuck_out_tongue_winking_eye:

**Comment by PinkaminaDianePie** [comment]
@sebmck good example, internal part of Angular.js: https://github.com/angular/angular.js/blob/master/src/auto/injector.js

it's really bad that babel dont have any internal documentation, i think many people want to help with some issues, but the cant. for example i still can't use native generators in iojs cause of one small bug with async-to-regenerator, but i can't fix it myself. @sebmck simply dont want to fix it (or have no time).

**Comment by sebmck** [comment]
We aren't talking abou internal documentation a. There are already a lot of
comments documenting how internal code works. Internal docs is referencing
design and architecture documentation.

On Friday, 3 July 2015, PinkaminaDianePie <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> good example, internal part of
> Angular.js:
> https://github.com/angular/angular.js/blob/master/src/auto/injector.js
>
> it's really bad that babel dont have any internal documentation, i think
> many people want to help with some issues, but the cant. for example i
> still can't use native generators in iojs cause of one small bug with
> async-to-regenerator, but i can't fix it myself. @sebmck
> <https://github.com/sebmck> simply dont want to fix it (or have no time).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1888#issuecomment-118346288>.
>


-- 
Sebastian McKenzie

**Comment by PinkaminaDianePie** [comment]
@sebmck just look at my link =) Angular.js have all needed documentation for contributing and this docs included in source files. If module doing something - that functionality are described in it. Babel for now have almost no documentation for code or its design.

**Comment by benjamingr** [comment]
Ok, looks like this inspired action (what I was hoping for). I think we can close it now, thanks!

**Comment by sebmck** [comment]
> I may have some relevant news in the next few weeks then.

This is very late but I'm now working at Facebook on Babel.
