### ISSUE TITLE
Unable to use await

### ISSUE THREAD

**Issue by koskimas** [babel/babel#1902]
I have this simple test script:

```js
async function test() {
  return 42; 
}

let x = await test();
```

And I run it using the command `babel-node --stage 0 await-test.js` and I get this:

```
SyntaxError: /Users/foo/bar/await-test.js: Unexpected token (5:14)
  3 | }
  4 |
> 5 | let x = await test();
    |               ^
```

```
babel-node --version
5.6.14
```

What am I doing wrong?

**Comment by sebmck** [comment]
`await` can only be on the inside of `async` functions.

**Comment by koskimas** [comment]
Well that was fast :D. Thanks! So from an non-async function we must resolve the returned promise. Makes sense now that I think about it.

```js
async function test() {
  return 42;
}

async function main() {
  return await test();
}

main().then(function (res) {
  console.log(res);
});
```

**Comment by sebmck** [comment]
Yup, there's no way to block execution outside of them.
