### ISSUE TITLE
Possible erroneous, definitely confusing behavior on async promise rejections

### ISSUE THREAD

**Issue by n1k0** [babel/babel#1903]
Using babel v5.6.14:

```js
async function test() {
  return Promise.reject(new Error("plop"));
}

async function run() {
  try {
    console.log(await test());
  } catch(err) {
    console.log(err);
  }
}

run();
```

Console prints "undefined" with a fulfilled promise.

I don't know if that's intended behavior, though:

- fulfilling the promise works as expected
- throwing instead of rejecting works as expected

I'm finding this behavior rather confusing, but couldn't determine if that's part of the spec or a Babel issue. Thoughts?

Edit: [Playground sample](http://tinyurl.com/pagzzaw).

**Comment by zloirock** [comment]
Looks like https://github.com/babel/babel/issues/1853 , update `regenerator` runtime.
