### ISSUE TITLE
JS generated by TypeScript compiler gives an error in Babel Repl

### ISSUE THREAD

**Issue by yfain** [babel/babel#1905]
Here's the TypeScript code http://bit.ly/1IRIkKc. It works fine if I run it in the playground or copy/paste the generated script to Traceur's repl: 

But in Babel's Repl it gives an error "Cannot read property '__extends' of undefined".

**Comment by loganfsmyth** [comment]
Babel treats each file that it compiles as an ES6 module, and in modules, the top-level `this` is `undefined`. That means that doing `this.__extends` will throw an error because it's actually `undefined.__extends`.

**Comment by yfain** [comment]
Thank you, Logan!
