### ISSUE TITLE
unterminated regular expression (works via constructor, but not as literal)

### ISSUE THREAD

**Issue by onelson** [babel/babel#1909]
Not sure who this bug belongs to, you or the folks at https://useiconic.com but babel is dying while trying to parse what boils down to this:

```
const element = document.body;
if (true){} /iconic-bg-/.test(element.getAttribute("class"));
```

If rewritten with a RegExp constructor, it compiles fine.
```
const element = document.body;
if (true){} new RegExp("/iconic-bg-/").test(element.getAttribute("class"));
```

Seems like this is a babel bug since 

Works:
```
/foo/.test("foobar");  // no if, just a regex literal
if(true) {}; /foo/.test("foobar");  // if, but with a semicolon after it.
``` 
but these break: 
```
// newline between if/regex has no effect
if(true) {
}
/foo/.test("foobar");

// the original case that brought this to light
if (true) {} /foo/.test("foobar");
``` 

See zurb/foundation-apps#625 for where this was encountered.

**Comment by sebmck** [comment]
cc @RReverser

**Comment by RReverser** [comment]
Thanks @sebmck. @onelson Can you please re-report to https://github.com/marijnh/acorn and someone of us will look into it asap?

**Comment by hzoo** [comment]
oops this can be closed because of https://github.com/babel/babel/pull/2194 too
