### ISSUE TITLE
resolve-rc.js not suitable for long running processes.

### ISSUE THREAD

**Issue by gandm** [babel/babel#1910]
My atom package - https://atom.io/packages/language-babel has an issue. When the editor starts I require babel-core and when files are are saved I transform a file. The core resolve-rc.js caches the existence of .babelrc file names which is great for a CLI but not so good for a long running editor session. Any deleted .babelrc files cause an error to throw as it tries to read a file that no longer exists.

I'm not sure what, if anything, can be done.

**Comment by mathieumg** [comment]
I have no idea how less efficient it would be, but you could call the babel CLI as a child process each time?

**Comment by gandm** [comment]
Yeah I could but the CLI is a larger dependency and it would be more difficult to get error messages, maps, etc back. It seems a bit silly having an API'l and not use it. I can't imagine deleting many babelrc files and a reload of the editor fixes this problem.

**Comment by mathieumg** [comment]
You could perhaps use the API in a child process with your own thin wrapper to communicate with the Atom plugin?

**Comment by eventualbuddha** [comment]
I'd be curious to know why the cache exists in the first place. Is that a particularly hot code path? I would guess that the file system cache would be sufficient to make this reasonably fast.

**Comment by gandm** [comment]
> You could perhaps use the API in a child process with your own thin wrapper to communicate with the Atom plugin?

Yes I could but Babel takes about a second to initialise and that's too long for each save in an editor.

> I'd be curious to know why the cache exists in the first place. Is that a particularly hot code path? I would guess that the file system cache would be sufficient to make this reasonably fast.

Yes so am I. Only the existence of a filename is cached not the actual file contents so it doesn't appear to do much. Seems weird  to me. Can't see it would add much to the overhead to ignore the check for existence and just check a failure on  the read.

**Comment by sebmck** [comment]
If you have a ton of transforms then that continuous file IO is pretty expensive.

**Comment by gandm** [comment]
Can't quite see that as babelrc's are still read for each file processed. The only caching is the existence of the file. But if that's how it works then fine.

**Comment by sebmck** [comment]
>  babelrc's are still read for each file processed

[Nope, The parsed JSON is cached too](https://github.com/babel/babel/blob/master/src/babel/transformation/file/options/resolve-rc.js#L36).

**Comment by gandm** [comment]
I must be missing something as the file is checked to see if it exists and then is read. https://github.com/babel/babel/blob/master/src/babel/transformation/file/options/resolve-rc.js#L32 after that that the JSON is handled. 

Anyway, thanks.

**Comment by gandm** [comment]
@sebmck Can you confirm that the JSON  is cached and used. I can see an attempt to cache but can't see it being used.

If it is cached I'll have to remove my package from atom or mark it as defective, as I can't know if people are changing babelrc files over a long editing session. It would be good to know.

**Comment by sebmck** [comment]
Yep, just double checked and file IO only occurs on either the first search of that directory or if any `.babelrc` files have been found. The idea is to do as little file IO as possible.

**Comment by gandm** [comment]
@sebmck  
> Yep, just double checked and file IO only occurs on either the first search of that directory or if any .babelrc files have been found. The idea is to do as little file IO as possible

OK just experimented with my Atom package and it doesn't bear that out! I'll close this as for my package no `.babelrc` files are cached by babel-core; which is great. See below for the test I did.

Load Atom & language-babel package
language-babel requires babel-core just once and hooks file save events to call `transformFile`

Two files in a directory. 
`foo.js`
```
const A = "babel rc test";
console.log(A);
```
and `.babelrc` initially containing
```
{
  "stage": 2
}
```
Save `foo.js` creates 
```
"use strict";

var A = "babel rc test";
console.log(A);
```
edit `.babelrc` as this:-
```
{
  "stage": 2,
  "optional": ["minification.removeConsole"]
}
```
Save `foo.js` creates this
```
"use strict";

var A = "babel rc test";
```
delete `.babelrc` and save `foo.js` gets
```
ENOENT: no such file or directory, open 'C:\Users\gandm\.atom\packages\language-babel\babel-source\.babelrc'
```

So as far as I can see `.babelrc` files aren't cached but the existence of the file is.

**Comment by sebmck** [comment]
@gandm 

> So as far as I can see `.babelrc` files aren't cached but the existence of the file is.

Yeah, that's what I meant by:

>  file IO only occurs on either the first search of that directory **or** if any `.babelrc` files have been found

**Comment by gandm** [comment]
@sebmck ok, I misunderstood your comment. It would be nice to have two methods of operation though. 

cached - where .babelrc files are cached at first read and then the cache is used from then on. Good for CLI, require hooks etc. The default mode.
NoCache - for IDE's, editors like mine, where nothing is cached. This would stop the ENOENT error I get when removing the .babelrc.

Maybe a option of cacheBabelrc: true/false could enable this.

Anyway thanks for a great package.
