### ISSUE TITLE
`ignore` and `only` don't work properly when using glob patterns with `**`

### ISSUE THREAD

**Issue by moretti** [babel/babel#1912]
``` js
> import transform from './lib/babel/transformation'
> transform("", {
      only: "node_modules/foobar/**/*.bar",
      filename: "node_modules/foobar/foo.bar"
}).ignored)
> true
```

This is a [bug](https://github.com/isaacs/minimatch/issues/67) of `minimatch.makeRe`, which is currently used in `utils.regexify`.

I'm opening an issue here to see if we can find an alternative solution to this problem, feel free to close it if you disagree.

**Comment by sebmck** [comment]
The result is expected, `**` implies a folder name, it's not optional.

**Comment by moretti** [comment]
`**` matches zero or more directories and subdirectories:
```js
> var minimatch = require('minimatch')
undefined
> minimatch('node_modules/foobar/foo.bar', 'node_modules/foobar/**/*.bar')
true
```

**Comment by sebmck** [comment]
Ah, my bad, I misunderstood.

**Comment by moretti** [comment]
An alternative to `minimatch` could be [`micromatch`](https://github.com/jonschlinkert/micromatch).
It has definitely more [test coverage](https://github.com/jonschlinkert/micromatch/tree/master/test) and `makeRe` is not affected by this bug.

**Comment by sebmck** [comment]
How does micromatch differentiate from minimatch and why is it a separate project?

**Comment by moretti** [comment]
Well, essentially it's just a different glob matcher implementation intended as drop-in replacement for minimatch and multimatch.
It's faster (according to these [benchmarks](https://github.com/jonschlinkert/micromatch#benchmarks)) and it has more test coverage (approx. 1,300 tests).

The code behind `makeRe` looks definitely more solid than minimatch:

https://github.com/isaacs/minimatch/blob/master/minimatch.js#L586
https://github.com/jonschlinkert/micromatch/blob/master/lib/expand.js

**Comment by sebmck** [comment]
Just trying to figure out why these improvements wouldn't have been contributed to the original project rather than just for the sake of having another implementation. cc @jonschlinkert

**Comment by moretti** [comment]
Related: https://github.com/isaacs/minimatch/issues/52

**Comment by jonschlinkert** [comment]
fwiw, this is really ot but that issue in minimatch is regrettable. @isaacs has always been a huge presence and driving force in the node.js community and in retrospect I think I completely misunderstood the motivation behind his decisions in that thread. which, IMHO was probably just "love of writing code", and nothing more... from that perspective, I was a jackass and I'd love to just move past that "unfortunately recorded moment in time". ...

regarding the actual code, thanks for the mention, I'm happy to answer any questions about micromatch. whatever helps you decide which lib makes the most sense for what you're doing.

**Comment by moretti** [comment]
@jonschlinkert Sorry about bringing back an old thread and thank you for your excellent project!

**Comment by jonschlinkert** [comment]
> Sorry about bringing back an old thread

no worries at all! it's there for the world to see, this one's on me. thanks for the kind words!

**Comment by hzoo** [comment]
This should be fixed in Babel 7 https://github.com/babel/babel/commit/39c862c1955041b3bfae72fda694c93657d8b73c

```
babel.transform("", { only: ["node_modules/foobar/**/*.bar"], filename: "node_modules/foobar/foo.bar" }).ignored
false
```

can test with "babel-core": "7.0.0-alpha.3", (or cli)
