### ISSUE TITLE
RegExp.flags not transformed

### ISSUE THREAD

**Issue by dwelle** [babel/babel#1914]
```
/ola/g.flags
```

is [not transformed](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=console.log(%2Fola%2Fg.flags)%3B), while being an [ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) feature. Causes node to fail.

**Comment by loganfsmyth** [comment]
Have you loaded the polyfill? The REPL page you linked to correctly logs `g`.

**Comment by dwelle** [comment]
Yea, my bad. Just found out polyfill solves that. I'm using `grunt-babel` which as it turns out doesn't include it by default. As for the REPL, I thought that it fell back to chrome which I thought already implemented it.

Anyway, might a be good idea to note this in the Learn ES2015 section (or maybe it's too small a feature).

**Comment by loganfsmyth** [comment]
I'm not sure it's worth it in this case. Babel only provides syntax-level conversions, anything at all that that is now in the language standard library like `Regex.prototype.flags` is the responsibility of a polyfill, not Babel, to support.
