### ISSUE TITLE
broken 'this' in arrow functions of anonymous objects

### ISSUE THREAD

**Issue by victorhaggqvist** [babel/babel#1917]
Lets say I have this module
```js
var mymod = (function() {
  return {
    func1: function(item){
      console.log('do stuff')
    },
    func2: function(){
      var someArray = [];
      someArray.map((item) => {
        this.func1(item);
      })
    }
  };
});
```
Gives
```js

var mymod = function mymod() {
  return {
    func1: function func1(item) {
      console.log('do stuff');
    },
    func2: function func2() {
      var _this2 = this; // this is undefined

      var someArray = [];
      someArray.map(function (item) {
        // which obviously makes _this2 is undefined
        _this2.func1(item);
      });
    }
  };
};
```
The `this` is undefined, according to Chrome 45.0.2438.3 dev and Chromium 43.0.2357.130.

This may or may not be related to https://github.com/babel/babel/issues/1340.
I'm running babel 5.6.14.
Everything works when I run tests using `mocha --compilers js:babel/register`.

**Comment by Dashed** [comment]
`this` isn't broken in the given example.

**Comment by Dashed** [comment]
see http://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-

**Comment by kevinb7** [comment]
```
function foo() {
return {
  a: function() { console.log('a'); },
  b: function() { this.a(); }
};
}
var obj = foo();
obj.b();    // print 'a' to the console
```
I would assume that ```this``` would be bound to the object being returned by ```mynod()```.

**Comment by Dashed** [comment]
yes. that's how `this` works. see: http://www.2ality.com/2014/05/this.html

For this pattern, you shouldn't rely on `this` as it can be changed through `.bind()` or `.call()`. It's better to explicitly reference the object:

```js
const obj = {
    a() {
        obj.b();
    },
    
    b() {}
};
```

or explicitly reference the functions directly:

```js
function a() { b(); };
function b() {};

const obj = {
    a,
    b
};
```

**Comment by kevinb7** [comment]
In section 1.3 it has this example:
```
var obj = {
    method: function () {
        console.log(this === obj); // true
    }
}
obj.method();
```
Is there another section with exceptions to this?

**Comment by kevinb7** [comment]
I agree that ```this``` inside ```function mymod() { ... }``` should be ```undefined``` or ```window```.  But the ```this``` in question should reference the object being returned.

**Comment by Dashed** [comment]
@kevinb7 

```js
'use strict';
var obj = {
    method: function () {
        console.log(this === obj);
    }
}

var something = obj.method;
something(); // => false
```

**Comment by kevinb7** [comment]
Ah... ```'use strict'``` changes that behavior.  @Dashed thanks for helping me understand.  :+1:

**Comment by Dashed** [comment]
np. with or without `'use strict';` though, `this` becomes something else, and there's no guarantee that it's still `obj`.

**Comment by kevinb7** [comment]
I re-read the link and all the info's there.  That what I get for skimming.

**Comment by victorhaggqvist** [comment]
Well that explains it, google apparently failed to direct me to the FAQ.
I ended up rewriting it with a explicitly reference, as @Dashed mentioned.
Thanks for educating me on that, closing this then.
