### ISSUE TITLE
minor issue: invalid es6 arrow function code accepted

### ISSUE THREAD

**Issue by lukeapage** [babel/babel#1919]
```
var a = ...a => a;  // babel - invalid
var a = (...a => a);  // babel - invalid
var a = (a) => a.a(...a => a);  // babel - valid
```
The last case should not be valid, but it is transpiled fine.

the spec says:

```
ArrowParameters[Yield] :
    BindingIdentifier[?Yield]
    CoverParenthesizedExpressionAndArrowParameterList[?Yield]
```

so without parenthesis, the parameter can only be an identifier.

Clearly a minor issue and upto you what you want to do with this info. from https://github.com/jshint/jshint/issues/2265

**Comment by sebmck** [comment]
You're spreading the function, it's not being interpreted as a rest parameter which is what I think you're reporting? This is basically what's happening:

```
a(...function (a) {
  return a;
});
```

and not:

```javascript
a(function (...a) {
  return a;
});
```

Grammer for `SpreadElement`:

```
SpreadElement[Yield] :
... AssignmentExpression[In, ?Yield]
```

part of the grammer of `AssignmentExpression`:

```
AssignmentExpression[In, Yield] :
ArrowFunction[?In, ?Yield]
```

so it looks like the current behaviour is valid.

**Comment by lukeapage** [comment]
I see, hadn't thought about that.

I guess the first 2 examples shouldn't be invalid then, even if they never make sense and will never work?

Please feel free to close this..
