### ISSUE TITLE
Relax on `this before super` when used inside of function

### ISSUE THREAD

**Issue by RReverser** [babel/babel#1920]
I'm trying following example:
```javascript
class DefaultParser extends Parser {
  constructor(input, opts) {
    var parserOpts = {
      onToken: token => {
        this._tokens.push(token);
      }
    };

    super(parserOpts, input);

    this._tokens = [];
  }

  parse() {
    // calls this.options.onToken somewhere inside
  }
}
```

Babel throws `'this' is not allowed before super()`. I know that this check is supposed to imitate the ES6 runtime behavior when someone tries to access `this` before calling `super` but this doesn't seem to be the case and might cause false positive (as this function isn't called before `super` in reality).

Maybe worth relaxing on function expression so that otherwise valid code would be accepted?

**Comment by sebmck** [comment]
This would allow otherwise invalid code to be valid though.

On Saturday, 4 July 2015, Ingvar Stepanyan <notifications@github.com> wrote:

> I'm trying following example:
>
> class DefaultParser extends Parser {
>   constructor(input, opts) {
>     var parserOpts = {
>       onToken: token => {
>         this._tokens.push(token);
>       }
>     };
>
>     super(parserOpts, input);
>
>     this._tokens = [];
>   }
>
>   parse() {
>     // calls this.options.onToken somewhere inside
>   }
> }
>
> Babel throws 'this' is not allowed before super(). I know that this check
> is supposed to imitate the ES6 runtime behavior when someone tries to
> access this before calling super but this doesn't seem to be the case and
> might cause false positive (as this function isn't called before super in
> reality).
>
> Maybe worth relaxing on function expression so that otherwise valid code
> would be accepted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1920>.
>


-- 
Sebastian McKenzie

**Comment by RReverser** [comment]
UPD: I know exactly this case can be workarounded by `var tokens = this._tokens = []` but I don't really want to workaround compiler for valid code.

**Comment by RReverser** [comment]
@sebmck True, but this can be added to caveats as Babel never promised to 100% reflect runtime checks (as it's not totally possible).

**Comment by RReverser** [comment]
In any case, I believe that ability to compile valid ES6 code is more important than linting.

**Comment by sebmck** [comment]
Well it is possible with an overzealous check (which is what this is).
Caveats should really only be for things that cannot be avoided whereas
this is something that can be implemented.

On Saturday, 4 July 2015, Ingvar Stepanyan <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> True, but this can be added to
> caveats as Babel never promised to 100% reflect runtime checks (as it's not
> totally possible).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1920#issuecomment-118527293>.
>


-- 
Sebastian McKenzie

**Comment by RReverser** [comment]
Not sure I understand your last point.

**Comment by RReverser** [comment]
What we could do would be adding setting some scoped boolean flag after `super` is called and checking it inside of such closures that reference `this`... or just allow them as-is. In any case, I believe this is a bug.

**Comment by sebmck** [comment]
Add caveats shouldn't be seen as a solution. There should be as few of them
as possible.

On Saturday, 4 July 2015, Ingvar Stepanyan <notifications@github.com> wrote:

> Not sure I understand your last point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1920#issuecomment-118527396>.
>


-- 
Sebastian McKenzie

**Comment by RReverser** [comment]
Of course, and if you see better solution, I'm all for it. But valid code should work in any case.

In any case, you can't really check all of references to instance before `super` call, there are always edge cases that can't be handled on compile-time.

**Comment by sebmck** [comment]
I'd consider disallowing valid code to be far better than allowing invalid
code. If you have a case that escapes the this before super check then
please report it.

On Saturday, 4 July 2015, Ingvar Stepanyan <notifications@github.com> wrote:

> Of course, and if you see better solution, I'm all for it. But valid code
> should work in any case.
>
> In any case, you can't really check all of references to instance before
> super call, there are always edge cases that can't be handled on
> compile-time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1920#issuecomment-118527667>.
>


-- 
Sebastian McKenzie

**Comment by RReverser** [comment]
Well, that's easy: http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=false&code=class%20A%20{%0A%20%20constructor%28%29%20{%0A%20%20%20%20console.log%28%27super%28%29%27%29%3B%0A%20%20}%0A%20%20%0A%20%20getInstance%28%29%20{%0A%20%20%20%20console.log%28%27this%27%29%3B%0A%20%20%20%20this%3B%0A%20%20}%0A}%0A%0Aclass%20B%20extends%20A%20{%0A%20%20constructor%28%29%20{%0A%20%20%20%20console.log%28%27new%28%29%27%29%3B%0A%20%20%20%20super.getInstance%28%29%3B%0A%20%20%20%20super%28%29%3B%0A%20%20}%0A}%0A%0Anew%20B%28%29%3B

Please hear me :) This is validation thing. Incomplete validation should not have higher priority than allowing valid code. Moreover, in other spec-related issues you said that those checks are less important, and now you're making the opposite point.

**Comment by RReverser** [comment]
Also, we can keep those more advanced checks (for closures) in optional validation transformer. That way, contexts in which we're not certain whether `this` is dangerous or not, will be left for validation/linter/whatever, but won't prevent users writing correct ES6 and thus will be in the same boat with spec transformers.

**Comment by loganfsmyth** [comment]
Perhaps the arrow function transformer could be special-cased for `constructor` functions to put the assignment of `var _this = this` after the `super` calls? Then attempts to use `this` would at least be undefined to make it clear there was an error (since it should never be undefined in a class constructor). They an optional spec transform could insert checks like the TDZ one does.

**Comment by sebmck** [comment]
@loganfsmyth There's no guarantee that `parseOpts.onToken` will be called before `super()` so there's not much benefit.
@RReverser That is indeed a bug then. (`super.*` before `super()`). Are there any other ways?

**Comment by sebmck** [comment]
Fixed the `super.*` before `super()` in derived class constructors via 0e4bb5ee3f32292563ed3fbfed863820748d91d0.

**Comment by sebmck** [comment]
@RReverser I know this doesn't address your specific concern but is there any reason in your first example that `parserOpts` has to be defined in the constructor and allocated each time? Are you relying on mutability?

**Comment by RReverser** [comment]
@sebmck What if we would at least fix subcase like this for now and then look for more generic solution? (as it's still a bug)

```javascript
class DefaultParser extends Parser {
  constructor(input, opts) {
    super({
      onToken: token => {
        this._tokens.push(token);
      }
    }, input);

    this._tokens = [];
  }

  parse() {
    // calls this.options.onToken somewhere inside
  }
}
```

This case doesn't seem to be dangerous as the only way function can be called is inside of `super(...)` and thus won't access `this` too early.

**Comment by RReverser** [comment]
> I know this doesn't address your specific concern but is there any reason in your first example that parserOpts has to be defined in the constructor and allocated each time? Are you relying on mutability?

@sebmck Yeah, `onToken` needs to push tokens into current instance of parser (Acorn expands options on `Parser` creation).

**Comment by sebmck** [comment]
What's the specific criteria that would exclude that case? Happy to add it. Need to be careful not to allow:

```javascript
class Foo extends Bar {
  constructor(input, opts) {
    var foo;

    super({
      bar: (foo = ((token) => this), foo())
    });
  }
}
```

etc.

**Comment by loganfsmyth** [comment]
@sebmck I mean, for this:

```
class DefaultParser extends Parser {
  constructor(input, opts) {
    var parserOpts = {
      onToken: function(token){
        _this._tokens.push(token);
      }
    };

    super(parserOpts, input);
    var _this = this;

    this._tokens = [];
  }
```

would only allow access to `this` after `super()` and then something separate could add tdz-like behavior to throw if the assignment hasn't happened yet.

Sorry if I'm missing some case in this.

**Comment by sebmck** [comment]
@loganfsmyth Oh right, that would work really well actually.

**Comment by RReverser** [comment]
@loganfsmyth Sounds good to me (basically it's pretty similar to my suggestion above with boolean flag, but probably even better as we don't need separate flag but can rely on `_this` being undefined).

**Comment by RReverser** [comment]
@loganfsmyth Fancy creating a PR?

**Comment by RReverser** [comment]
Thanks @sebmck! Always happy when we can find a solution instead of just arguing :)
