### ISSUE TITLE
Switch to normal Acorn

### ISSUE THREAD

**Issue by sebmck** [babel/babel#1923]
4 possible solutions for each.

1. Patch Acorn methods
2. Implement them as plugins
3. Add to Acorn core
4. Add additional Acorn methods to override

Todo

 - [ ] Exponentiation operator (Likely 3)
 - [ ] Strict mode option (Likely 3)
 - [ ] Decorators
 - [ ] Export extensions
 - [ ] Bind syntax
 - [ ] Do expressions
 - [ ] Class properties
 - [ ] Trailing arrow function commas
 - [ ] Async functions
 - [ ] Default parameter with flow type
 - [ ] Object rest/spread property (Likely 4)

cc @RReverser

**Comment by tobich** [comment]
@sebmck Does that mean that you're planning to separate acorn from the babel code? After the demise of esprima-fb, babel/acorn remains, as far as I know, the only advanced "ES-next" parser, so project which need parsing, but not the whole babel functionality are in trouble. Recent "Don't hotlink internal Babel files." protection made things even worse from this point of view. What are the plans?

**Comment by RReverser** [comment]
@tobich As you can see from the post, plan is to integrate stable ES7 features to [original Acorn](https://github.com/marijnh/acorn) itself, and move other to plugin (Acorn supports pluggable syntax extensions which Babel's Acorn currently makes use of). So it will be even easier to use parser on it's own without requiring entire Babel.

Even now, you can use [Acorn-JSX](https://github.com/RReverser/acorn-jsx) as a replacement to esprima-fb, as it will give you complete support for JSX+ES6 (and even esprima-fb didn't have complete one).

**Comment by tobich** [comment]
Didn't know about Acorn-JSX. Thanks a bunch for the clarification!

**Comment by RReverser** [comment]
@tobich It's mentioned in the same [article](http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html) where esprima-fb was deprecated :)

> As a result of no longer maintaining JSTransform, we no longer have a need to maintain our Esprima fork (esprima-fb). The upstream Esprima and other esprima-based forks, like Espree, have been doing an excellent job of supporting new language features recently. If you have a need of an esprima-based parser, we encourage you to look into using one of those.

> Alternatively, if you need to parse JSX, take a look at acorn parser in combination with acorn-jsx plugin which is used inside of Babel and thus always supports the latest syntax.

**Comment by sebmck** [comment]
@tobich 

> Recent "Don't hotlink internal Babel files." protection made things even worse from this point of view

Not really. The parser has always been publicly exposed via `require("babel-core").parse`.

@RReverser 

> As you can see from the post, plan is to backport stable ES7 features 

There aren't really any stable ES7 features though. The only thing that I'll likely feel comfortable PRing to Acorn is the exponentiation operator.

**Comment by RReverser** [comment]
I'm fine with few others as well (e.g. syntax of "trailing comma" is unlikely to change, and it's fine as soon as available only under `ecmaVersion: 7`).

**Comment by sebmck** [comment]
Things like that would require changes on the Acorn side as the `ecmaVersion` option isn't enough to reflect specific features and enabling them all by default isn't viable.

**Comment by RReverser** [comment]
@sebmck `features` thing can be implemented on plugin side by just filtering tokens or nodes that shouldn't be accepted when certain feature is off (as I did in Espree).

**Comment by sebmck** [comment]
If both Espree and Babel need this type of syntax flagging then doesn't it make sense to have it in Acorn itself? Hacking this type of stuff into Acorn is fairly painful.

**Comment by RReverser** [comment]
Most of users don't care about tuning on/off specific features, so adding this to the core and thus slowing down checks even more (boolean hash maps, yay) is not viable. What they both could do would be to use common plugin though.

**Comment by RReverser** [comment]
Sorry, got to run.

**Comment by sebmck** [comment]
Moving to #1928.
