### ISSUE TITLE
Feature Request: Arrow Function Enhancements

### ISSUE THREAD

**Issue by blakelapierre** [babel/babel#1925]
I'm not sure this is in the spec or in any plans, but I think it would be nice to allow the following transformations:

````js
names.map({first, middle} => {first, middle, last});
````

into (ES6/2015):

````js
names.map(o => {
  const {first, middle} = o;

  return {first, middle, last};
});
````

and ultimately into something like (ES3/5):
````js
names.map(function(o) {
  var first = o.first;
  var middle = o.middle;

  return {
    first: first,
    middle: middle,
    last: last
  };
});
````

There are two different transformations here and I think both will be very useful.

The first is sugar for destructuring a function argument:

````js
{first, middle} => {
  console.log(first, middle);
}

 is sugar for

arg => {
  const {first, middle} = arg;
  console.log(first, middle);
}
````

The second is sugar for returning a new object literal from an arrow function:

````js
const first = 'first',
      middle = 'middle';

() => {first, middle};

 is sugar for

() => {
  return {first, middle};
}
````

I think these would be valuable contributions to ECMAScript (or even as a non-standard transform pass), as I often find myself wanting to use them but being unable to. I'd like to implement these transformations so that I can run them on my own code, but I'm not familiar with Babel's codebase and I haven't found any relevant documentation in the small amount of exploring that I've done.

Does anyone know and care to give me some pointers about how to implement this in Babel? Which files would need to be touched? Which data structures would need to be added or modified?

I have some experience in working with compiler internals, but I'm mainly just looking for a point in the right direction. I'm also interested in discussion on the transformations themselves (eg. if anyone would find them useful; if something should be changed; if someone else has already implemented this; etc.).

**Comment by loganfsmyth** [comment]
names.map({first, middle} => {first, middle, last});

is just missing parens.

    names.map(({first, middle}) => ({first, middle, last}));

does exactly what you want.

In arrow functions, you need parens around arguments in all cases except simple identifiers, and `{}` are used to denote an arrow function with a body of statements rather than an expression, so you need to add parens around the `{}` to make it an expression.

**Comment by blakelapierre** [comment]
Oh, cool!

I wouldn't say it's *exactly* what I want. I'd prefer to not need the parenthesis wrap.

I wonder if the grammar can support the simplified syntax (I think it's easier to read)? `{}` being used for statement blocks would seem to be an issue :( I'll have to think more about it later though.

Thanks for the clarification!
