### ISSUE TITLE
Number constructor issue

### ISSUE THREAD

**Issue by f-xyz** [babel/babel#1927]
Babel somehow changes Number constructor behavior. It breaks number comparison in Chai.js assertion library.

### Example code: `1.js`

```js
'use strict';

var numberObject = new Number(1);

console.log(numberObject);
console.log('\n');

console.log(numberObject.constructor(numberObject));
console.log(Number(numberObject));
console.log(Number.prototype.constructor(numberObject));
console.log('\n');

console.log(typeof numberObject.constructor(numberObject));
console.log(typeof Number(numberObject));
console.log(typeof Number.prototype.constructor(numberObject));
console.log('\n');

console.log(numberObject.constructor === Number);
console.log(numberObject.constructor === Number.prototype.constructor);
console.log('\n');

console.log(Number.toString());
console.log(numberObject.constructor.toString());
console.log('\n');
```

### Output of `node 1.js` 
```
[Number: 1]


1 // it's a number
1
1


number // it's a number
number
number


true
true


function Number() { [native code] }
function Number() { [native code] }

```

### Output of `babel-node 1.js` (the same for require('babel/register'))
```
[Number: 1]


[Number: 1] // it shouldn't be an object
1
1


object // it shouldn't be an object
number
number


true
true


function Number() { [native code] }
function Number() { [native code] }
```

**Comment by zloirock** [comment]
Strange. Please, open issue in [core-js](https://github.com/zloirock/core-js) repo.

**Comment by zloirock** [comment]
Heh. Problem in constructor detection [here](https://github.com/zloirock/core-js/blob/master/modules/es6.number.constructor.js#L27). In your strange case `this instanceof Number`, like in `new Number`. Need add slow classof `Object#toString.call` check =\ As I say, please, open issue in `core-js` repo and it will be fixed in next release.

**Comment by f-xyz** [comment]
Opened https://github.com/zloirock/core-js/issues/89
