### ISSUE TITLE
loop variable not initialized when using modules system

### ISSUE THREAD

**Issue by lneumann** [babel/babel#1929]
Not sure if this is your bug. When calling babel for following example (loop.js) I got an unusable output.
```javascript
for (let i = 0; i < 10; i++) {
  console.log(i);
}
```
Using babel 5.6.14 (Windows) with modules system
```
babel loop.js --modules system
```

Output: Variable i is never initialized, console.log is never called
```javascript
System.register([], function (_export) {
  "use strict";

  var i;
  return {
    setters: [],
    execute: function () {
      for (i; i < 10; i++) {
        console.log(i);
      }
    }
  };
});
```

**Comment by sebmck** [comment]
`i` is initialised on line 4. The generated code is correct so with the information provided I can confirm that the problem doesn't lie with Babel.

**Comment by lneumann** [comment]
Sorry, I meant variable i is declared without a value (undefined). But in the loop initialization i is set to 0.
```javascript
for (let i = 0; i < 10; i++) {
```

I would expect something like 
```javascript
execute: function () {
i = 0;
for (i; i < 10; i++) {
```
