### ISSUE TITLE
High compliancy and loose mode used together

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#1930]
I find it confusing that there are two boolean options "loose mode" and "high compliancy", and that it's possible to enable both at once.

Loose mode is described as "Making your code faster (but less spec-compliant)" which sounds like the exact opposite of high compliancy. Why is it possible to use them both together?

Also, I can't find any docs about high compliancy, only a checkbox on the REPL.

https://www.google.com/search?q=babel+high+compliancy+site:babeljs.io

**Comment by sebmck** [comment]
This is a comment on the website/REPL and does not belong in this repo, please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

"High compliancy" mode is not documented anywhere and just enables all the `spec` transformers listed on [this](http://babeljs.io/docs/usage/transformers) page. It's not counter intuitive to enable both of them. The spec transformers opt in to certain semantics and loose mode opts out of others.
