### ISSUE TITLE
Fat arrows with a unique rest parameter aren't handled properly

### ISSUE THREAD

**Issue by nesk** [babel/babel#1932]
Babel should throw an error when writing the following code:

```js
console.log(...args => {});
```

The valid syntax is:

```js
console.log((...args) => {});
```

FYI, Firefox throws this error when trying the first code:

```
TypeError: (intermediate value)[Symbol.iterator] is not a function
```

**Comment by sebmck** [comment]
See #1919.

**Comment by nesk** [comment]
Woops, sorry for the duplicated issue.
