### ISSUE TITLE
Clarify babel homepage example

### ISSUE THREAD

**Issue by lusa** [babel/babel#1939]
One misunderstanding I have about Babel is why the example on the homepage has ```myOldWeirdJavaScript``` as the input and ```myNewTransformedJavaScript``` as the ouput. Isn't it the other way around, ES6->ES5? Nowhere on the site does it actually say babel compiles ES6 into ES5, as obvious at that may be. I confusingly thought it compiles ES5->ES6 based on the example.

**Comment by sebmck** [comment]
Duplicate of babel/babel.github.io#318.

**Comment by sebmck** [comment]
Also please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

Thanks! :blush:
