### ISSUE TITLE
Default values for nested object parameters using destructuring

### ISSUE THREAD

**Issue by andrewshawcare** [babel/babel#1940]
I would like to provide default values for nested object parameters using destructuring. Ideally, any value that a user does not provide will be set to a default value for all nested properties.

# ES6:

```javascript
let alertLink = ({
    title = "",
    description = "",
    link = {
      title = "",
      url = ""
    } = {}
} = {}) => alert(link.title);

alertLink({link: {url: "foo"}});
```

# Generated ES5:

```javascript
"use strict";

var alertLink = function alertLink() {
    var _ref2, _ref2$title, _ref2$url;

    var _ref = arguments[0] === undefined ? {} : arguments[0];

    var _ref$title = _ref.title;
    var title = _ref$title === undefined ? "" : _ref$title;
    var _ref$description = _ref.description;
    var description = _ref$description === undefined ? "" : _ref$description;
    var _ref$link = _ref.link;
    var link = _ref$link === undefined ? (_ref2 = {}, _ref2$title = _ref2.title, title = _ref2$title === undefined ? "" : _ref2$title, _ref2$url = _ref2.url, url = _ref2$url === undefined ? "" : _ref2$url, _ref2) : _ref$link;
    return alert(link.title);
};

alertLink({ link: { url: "foo" } });
```

# Ideal ES5:

```javascript
"use strict";

var alertLink = function alertLink() {
    var _ref = arguments[0] === undefined ? {} : arguments[0];

    var _ref$title = _ref.title;
    var title = _ref$title === undefined ? "" : _ref$title;
    var _ref$description = _ref.description;
    var description = _ref$description === undefined ? "" : _ref$description;
    var _ref$link = _ref.link;
    var link = _ref$link === undefined ? {} : _ref$link;
    link.title = link.title === undefined ? "" : link.title,
    link.url = link.url === undefined ? "" : link.url;
    return alert(link.title);
};

alertLink({ link: { url: "foo" } });
```

**Comment by sebmck** [comment]
Is there anything wrong with the current output is your criticism purely style? Your ideal output will execute a getter for `link.title` two times instead of once which can have a nuanced effect at runtime and is not spec compliant.

**Comment by loganfsmyth** [comment]
That's not quite how destructuring works, you are pulling values out of an object, but there is nothing in what you've written that would mutate the `link` object. I'd expect your code to be more like:

```
let alertLink = ({
    title = "",
    description = "",
    link: {
      title: linkTitle = "",
      url = ""
    } = {}
} = {}) => alert(linkTitle);
```

**Comment by sebmck** [comment]
Oh wait, I missed that @loganfsmyth. That's completely wrong. Destructuring does not mutate the target object. I'm closing this as the current behaviour is expected, correct and completely spec compliant.

**Comment by andrewshawcare** [comment]
Wrong as far as the spec? It seems _valuable_, if not spec compliant. I want to set defaults for an object, but not assign variable names to individual keys.

In other words, I wouldn't want to reference a variable named, `linkTitle`, but rather `link.title` and have it adopt the default value.

**Comment by sebmck** [comment]
Your proposed behaviour is counter intuitive to the specification.

**Comment by eventualbuddha** [comment]
Yes, wrong as far as the spec. It does seem like it might be a useful feature, but it's not a feature of ES6. The way @loganfsmyth suggested is the only really feasible way to do it with destructuring.

**Comment by andrewshawcare** [comment]
...and I suppose I should provide a reason for the preference. It would be ideal because I could operate on `link` knowing it had reasonable defaults. Right now I don't see how I can pass a nested object parameter to a function and have it adopt default values.

As I was typing people added more info. Thanks for your time.

**Comment by loganfsmyth** [comment]
It seems like like what you're really asking for is a coffee-script style `?=`. ES6 doesn't include something like that unfortunately. Defaults still don't really 100% address what you want anyway though, since they just check `undefined` and someone could pass `null` and blow everything up.

If you want 100% validation, manual is probably easier.

To get the behavior you are looking for out of destructuring, you'd have to do
```
let alertLink = ({
    title = "",
    description = "",
    link = {}
  } = {}) => {
    
  ({
    title: link.title = "",
    url: link.url = ""
  } = link);
  
  console.log(link.title);
}
```

which is super hard to read.

**Comment by andrewshawcare** [comment]
Yeah @loganfsmyth agreed, I was just writing that. I thought it might be spec-compliant because the top-level object literal defaults actually maps to different code, it splits the object literal default ternary:

```javascript
var _ref = arguments[0] === undefined ? {} : arguments[0];
```

from the property default value code:

```javascript
var _ref$title = _ref.title;
var title = _ref$title === undefined ? "" : _ref$title;
...
```

where the nested object attempts to do both operations at once:

```javascript
var _ref$link = _ref.link;
var link = _ref$link === undefined ? (_ref2 = {}, _ref2$title = _ref2.title, title = _ref2$title === undefined ? "" : _ref2$title, _ref2$url = _ref2.url, url = _ref2$url === undefined ? "" : _ref2$url, _ref2) : _ref$link;
```

I guess I was expecting something like:

```javascript
var _ref$link = _ref.link === undefined ? {} : _ref.link;
...
```

**Comment by eventualbuddha** [comment]
As @sebmck pointed out, you have to be very careful to only access the properties once because they may have side effects (i.e. they may be getters). For [example](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20link%20%3D%20%7B%20get%20title()%20%7B%20console.log(%22getting%20title%22)%3B%20return%20%22TITLE%22%3B%20%7D%20%7D%3B%0Alet%20%7B%20title%20%3D%20%22%22%20%7D%20%3D%20link%3B%0A):

```js
let link = { get title() { console.log("getting title"); return "TITLE"; } };
let { title = "" } = link;
```

This code must only log "getting title" once. If you did `_ref.title === undefined ? "" : _ref.title` it might access it twice.

**Comment by andrewshawcare** [comment]
@eventualbuddha So do you mean something like this (to accomplish what I am proposing while still accessing the original property getter only once)?:

```javascript
var _ref$link = _ref.link;
var _ref$link = _ref$link === undefined ? {} : _ref$link;
...
```
