### ISSUE TITLE
only one instance of babel/polyfill is allowed

### ISSUE THREAD

**Issue by cyberthom** [babel/babel#1943]
I am working on a complex site where multiple autonomous teams who have independent code bases are loaded onto the same page. (i.e. header is one build, main content another build). Depending on the page some of them require ES6 polyfills while others don't. I want to avoid implied global dependencies so would like to keep the decision as to whether polyfills are required or not in each codebase. The problem is that there could be a case where multiple builds include them which currently produces the following error with `babel/polyfill`:

```
Uncaught Error: only one instance of babel/polyfill is allowed
```

Is there a specific reason this was added? 

How would you recommend handling this use case? 

I'm happy to send a pull request to change the behaviour so that polyfills are no-ops without throwing any errors if they have already been loaded in. (Which in a way is how I would expect them to work anyways)

**Comment by sebmck** [comment]
Multiple global polyfills can sometimes collide causing very strange bugs that are extremely hard to track down. Even with a noop you'll still have the issue of multiple polyfills being included in your builds. It's safer to just throw a hard error.

**Comment by arcanis** [comment]
@sebmck I get this error when running mocha tests - even if I agree that it would be best to avoid this kind of thing, a hard error prevents some valid use cases to run :(

**Comment by wmertens** [comment]
@sebmck Can't this just output a warning? I have this problem with server side rendering (React), and I'm unsure how to work around it. I only include the polyfill in one place but somehow it gets loaded twice.

**Comment by sebmck** [comment]
It's a hard error because it causes environmental issues and if it's a warning then people will just ignore it instead of fixing it.

**Comment by wmertens** [comment]
Any hints on how to fix it?

On Sat, Oct 17, 2015, 22:18 Sebastian McKenzie <notifications@github.com>
wrote:

> It's a hard error because it causes environmental issues and if it's a
> warning then people will just ignore it instead of fixing it.
>
> On Sat, Oct 17, 2015 at 8:43 PM, Wout Mertens <notifications@github.com>
> wrote:
>
> > @sebmck Can't this just output a warning? I have this problem with
> server side rendering (React), and I'm unsure how to work around it. I only
> include the polyfill in one place but somehow it gets loaded twice.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/babel/babel/issues/1943#issuecomment-148942311
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1943#issuecomment-148948834>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by loganfsmyth** [comment]
@wmertens Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by codejamninja** [comment]
Idempotent Babel Polyfill can be imported multiple times

```sh
npm install --save idempotent-babel-polyfill
```

```js
import 'idempotent-babel-polyfill';
```
