### ISSUE TITLE
Strange code-generation in loop with defining function

### ISSUE THREAD

**Issue by lexich** [babel/babel#1944]
Source code
```js
for (let name of ["next", "prev"]) {
  (function() {
    console.log(name);
  })();
}
```
Result
```js
"use strict";

var _arr = ["next", "prev"];

var _loop = function () {
  var name = _arr[_i];
  (function () {
    console.log(name);
  })();
};

for (var _i = 0; _i < _arr.length; _i++) {
  _loop();
}
```

I think that `_i` should be argument of `_loop` function and sharing it is a bad idea.

REPL:
https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=true&spec=false&playground=false&code=for%20(let%20name%20of%20%5B%22next%22%2C%20%22prev%22%5D)%20%7B%0A%20%20(function()%20%7B%0A%20%20%20%20console.log(name)%3B%0A%20%20%7D)()%3B%0A%7D%0A

**Comment by sebmck** [comment]
`_i` is never used in a closure so is not required to be passed as a parameter. The evaluation of it is always going to be synchronous and it wont be overridden before it's bound.
