### ISSUE TITLE
Split the polyfill up by area and features

### ISSUE THREAD

**Issue by davidmarkclements** [babel/babel#1946]
For purposes of browserification, it'd be nice if polyfill.js become a polyfill directory, 
with subdirs for particular areas (e.g. Array, String, ... Async? (for generators and promises?))
and then individual features in the subdirs

Then I can do 

```js
require('babel/Array/from');
```

So instead of having an 84kb payload (or half that minified), 
I have around 2kb.

I don't want to include all the generator stuff etc, because I'm not using it

**Comment by zloirock** [comment]
[Already done](https://github.com/zloirock/core-js#commonjs).

**Comment by davidmarkclements** [comment]
...nice, clearly you are an awesome fellow. 

Are there plans to move this into babel ?

**Comment by davidmarkclements** [comment]
also - a browserify transform that statically analyse a code base and then injects only necessary polyfills would be amazing - @zloirock please tell you've done that as well

**Comment by zloirock** [comment]
`babel/polyfill` just includes full version `core-js` and `regenerator/runtime`, if you wanna single features - use `core-js` instead of `babel/polyfill`.

`runtime` transformer already uses static analyse and inject necessary features. Default version in this case can cause some conflicts.

**Comment by davidmarkclements** [comment]
interesting - thanks @zloirock
