### ISSUE TITLE
resolveModuleSource not working in babel/register

### ISSUE THREAD

**Issue by jprichardson** [babel/babel#1947]
Related: https://github.com/babel/babel/issues/1945 I'm not trying to be annoying. The bot flagged my issue submission as a "question" for support. I shouldn't have used passive voice. I'll be direct.

`resolveModuleSource` is not working `babel/register` when the documentation [register hooks](https://babeljs.io/docs/usage/require/) doesn't specify that it's limited to the options on that page and the documentation [options](https://babeljs.io/docs/usage/options/) doesn't list any caveats on `resolveModuleSource` which would lead me to believe that it's a bug. 

Code:

```js
require('babel/register')({
  resolveModuleSource: function (src) {
    console.log(src)
    return src
  },
  only: 'src/',
  extensions: ['.js'],
  optional: ['es7.decorators', 'es7.asyncFunctions']
})
```

Expectation: that each time a module is encountered, it would be printed out as seen by `console.log(src)`. Nothing is output. Thanks.

**Comment by sebmck** [comment]
In the future please comment on the closed issue instead of creating another one, it just adds unnecessary noise. Can you gist the code you're trying to run `resolveModuleSource` on? It only effects ES6 module declarations.

**Comment by sebmck** [comment]
Also note that the cache would effect the execution of this. Functions aren't included in the cache key as the options are JSONd meaning that if the file was compiled previously then it wont be recompiled unless it's been changed. `rm -rf ~/.babel.json` to clear the cache.

**Comment by jprichardson** [comment]
> In the future please comment on the closed issue instead of creating another one, it just adds unnecessary noise. 

I'm sorry about that. I was worried that after the bot closed the issue, it would disappear.

> It only effects ES6 module declarations.

That was my problem. I got so caught up in trying different Babel configurations I didn't stop and think about how I was using the module. It feels very obvious in retrospect. Sorry :(

> Also note that the cache would effect the execution of this.

Adjusting the cache flag does indeed have an impact.

Thanks for taking the time to respond. Hopefully this issue may be of some use for anyone encountering a similar issue.

**Comment by sebmck** [comment]
No problem :blush: Also feel free to check out the  <a href="https://babel-slack.herokuapp.com">slack community</a> if you need support for anything in the future, thanks!
