### ISSUE TITLE
convert shebang

### ISSUE THREAD

**Issue by shannonmoeller** [babel/babel#1948]
Would it make sense for babel to convert shebangs from `#!/usr/bin/env babel-node` to `#!/usr/bin/env node`?

**Comment by sebmck** [comment]
Can you explain why it does make sense?

**Comment by shannonmoeller** [comment]
It can be convenient to author CLI scripts using `babel-node` as the interpreter so they can be run directly using `./src/bin/cli.js`. Then, when compiled into ES5 for publication to npm, use the user's regular node interpreter.

It can be done with an additional step in the build chain, but I'm having a hard time thinking of a case where you wouldn't want this conversion to happen.

**Comment by sebmck** [comment]
It just seems weird to have the transformation logic so opinionated like this. It shouldn't care about what the hashbang contains.

**Comment by shannonmoeller** [comment]
I hear that. Just seemed like it may be helpful and natural given that babel-node is authored here.

**Comment by sebmck** [comment]
Closing this as I believe that manipulating shebangs is way too opinionated. Thanks for the suggestion though :blush:

**Comment by shannonmoeller** [comment]
Fair enough! Thanks for the consideration.

**Comment by shannonmoeller** [comment]
Could easily be a plugin at this point.
