### ISSUE TITLE
[plugins] refactor/implement `babel-plugin test` for tests in the same repo 

### ISSUE THREAD

**Issue by hzoo** [babel/babel#1950]
~~Move plugin test logic into `babel-plugin test`~~

Afterwards also move plugin tests in `/test/core/fixtures/transformation/` to separate `babel-plugin` repos.

Example: (`babel-plugin-remove-console`)
https://github.com/babel/babel/tree/master/test/core/fixtures/transformation/minification.remove-console test to 
https://github.com/babel-plugins/babel-plugin-remove-console repo

**Comment by hzoo** [comment]
Added in https://github.com/babel/babel/commit/15969a09046a50ae2ae0503725b7fb00cdd7137f

**Comment by thejameskyle** [comment]
@hzoo Can this be closed?
