### ISSUE TITLE
Repl in the browser

### ISSUE THREAD

**Issue by rektide** [babel/babel#1953]
Would love to use the amazing es.next capabilities Babel delivers in a browser repl.

For example, there is the beautiful site [Eloquent Javascript](http://eloquentjavascript.net/) that teaches JavaScript with interactive examples: this is a great place where it'd be lovely to not be pinned to whatever the browser supports, where Babel should/could be useful.

**Comment by sebmck** [comment]
Are you asking for a browser API/build?

**Comment by rektide** [comment]
I'm imagining an ideal resolution of this ticket as,
A) some ability to load/execute `babel-node` as a library,
B) and run that library in the browser.

Node's process and repl modules seem to be the primary Node modules not polyfilled, keeping from resolving B. Exporting the existing pieces of babel-node such that they can be used as a module would resolve A. 

This is just one potential form for this enhancement. I'd be open/overjoyed to have other good ways of using babel in an interactive browser context.

**Comment by sebmck** [comment]
I don't fully understand the request. Why would something like this belong in core? There are already websites like [JS Bin](http://jsbin.com/?html,js,output), [RequireBin](http://requirebin.com/) etc. Babel comes with a [browser build](http://babeljs.io/docs/usage/browser/) that will automatically compile `<script>` tags with a certain `type` which is kinda what I think you're requesting but a bit more?

**Comment by rektide** [comment]
This request is based off the presence of [_babel-node](https://github.com/babel/babel/blob/master/packages/babel-cli/bin/_babel-node) being provided by babel- a provided, core means of executing a read-print-eval-loop of Babel. My ask is to generalize the interactive means of executing Babel. *It should be easier for anyone to come along and build from or extend facilities provided by Babel to develop a repl.*

As for the examples, in jsbin if you open it's console (not your browsers, it's own interactive one) and type `class Point {` it will tell you `class is a reserved identifier`. They would be an example of someone I would expect to see consume the capability I am asking for. RequireBin is not quite applicable, as they execute in non-interactive batch mode- you have to complete your program before submitting: this is a limitation that `babel-node` does not have.

I've asked for (A) and (B) because it seemed like an isomorphic way to deliver what Babel already delivers for Node, transposed to the browser environment. There are other conceptual framings to this problem that could be applied- I'd be over the moon for a `babel.transform` that accepts an iterator for incremental code and returns an iterator with incremental results. That version of the  ask is complicated though by the other need repl's have to satisfy- dealing gracefully with invalid input, and asking for an iterating transform is a technical ask rather than a story, or use case, which I thought would make it harder to explain or justify.

Js Bin's console is a great example of what I want to see able to use Babel- I'd love if Babel provided facilities for online web environments to be used in consoles such as Js Bin's.

**Comment by sebmck** [comment]
Babel just exposes a `babel.transform` API that you can build anything on top of and use. What you're proposing is pretty big and I don't feel as if this has any place in core. `babel-node` is ridiculously simple and just utilises the Node [`repl`](https://nodejs.org/api/repl.html) module so there's really not a lot of magic there. Thanks for the suggestion but closing for the aforementioned reasons. :blush:
