### ISSUE TITLE
Loader.eval does not work as advertised

### ISSUE THREAD

**Issue by rafaelkaufmann** [babel/babel#1954]
Hi, in the docs it is claimed that `es6-module-loader`'s Loader will give you a sandboxed eval method.

```
// Create execution sandboxes – new Loaders
var loader = new Loader({
  global: fixup(window) // replace ‘console.log’
});
loader.eval("console.log(\"hello world!\");");
```

If you test this, you will get a `TypeError: Object [object Object] has no method 'eval']`.

I understand that providing this is `es6-module-loader`'s responsibility, but the docs should reflect the correct way to obtain this functionality or omit it...

**Comment by loganfsmyth** [comment]
Why are you filing this issue against Babel?

**Comment by rafaelkaufmann** [comment]
As I said, in order to fix the Babel docs. Of course, one could argue that the Babel docs shouldn't be claiming anything about an external module's API, but they are. So it should be fixed or removed, IMO. If I manage to find out what is the correct way to obtain the claimed functionality from es6-module-loader, I can post it here.

**Comment by loganfsmyth** [comment]
Ah okay, you are referring to the example here: https://babeljs.io/docs/learn-es2015/.

Please see the [README](https://github.com/babel/babel/blob/master/README.md) of this repo:

> The Babel issue tracker is exclusively for bug reports and feature requests. For documentation and website issues please visit the [babel.github.io](https://github.com/babel/babel.github.io) repo.

Please file this over there.

**Comment by rafaelkaufmann** [comment]
Ah, I missed that part. Sorry, thx.
