### ISSUE TITLE
Automatically adding some decorator(s) to React.createClass

### ISSUE THREAD

**Issue by timbur** [babel/babel#1955]
I'm an AST noob so I'm hoping maybe @sebmck or someone would be so kind as to help me out here.  Originally, to simulate a decorator, I was using something like this:
```js
function transform (babel) {
  var t = babel.types;

  return new babel.Transformer(pluginPath, {
    CallExpression: function (node, parent, scope, file) {
      var callee = this.get('callee');
      if (!callee.matchesPattern('React.createClass')) {
        return;
      }

      callee.getStatementParent().insertAfter(
        t.assignmentExpression(
          '=',
          t.identifier(parent.id.name),
          t.callExpression(
            someDecorator,
            [t.identifier(parent.id.name)]
          )
        )
      );
    }
  });
}
```

But as you might imagine, that doesn't work for stuff like this:
```js
export default React.createClass({...});
```

I'm aware of `node.decorators.push(t.decorator(...))`, but I can't figure out how to make this work for variations of `export default React.createClass({...})` and `const SomeComponent = React.createClass({...})`.

**Comment by timbur** [comment]
It looks like decorators can't be added to exports that aren't ES6 classes, but doing something like this should work:
```js
export default React.createClass({...});
```
Should become:
```js
export default someDecorator(etc)(React.createClass({...}));
```

I have no idea how to achieve this with AST.  O_O

**Comment by timbur** [comment]
Resorted to some pretty silly stuff to make this work in the short term.  I'm probably just being blind and dumb, but I can't find the docs/detailed examples for this kind of stuff anywhere, so I resorted to logging the nodes, paths, and their constructors and making some guesses as to which methods might do what I need.

This is what I have currently, which is definitely not optimal as it requires the decorator itself to call `React.createClass` (when it needs to just be wrapped around the result of `React.createClass`), but at least it works.  See [`babel-plugin-react-hot/index.js`](https://github.com/loggur/babel-plugin-react-hot/blob/master/index.js#L48-L73) and [`babel-plugin-react-hot/makeHot.js`](https://github.com/loggur/babel-plugin-react-hot/blob/master/makeHot.js).

I would love to know how to do this properly and/or see some detailed docs/examples.  I saw in another issue or PR from roughly 22 days ago that @sebmck is working on some docs for the transformers, which is awesome.  Looking forward to it!

**Comment by eventualbuddha** [comment]
The best thing to do is swing by the [Slack channel](https://babel-slack.herokuapp.com/) to ask questions like this. From the README:

> For questions and support please visit the [Slack community](https://babel-slack.herokuapp.com/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs). The Babel issue tracker is exclusively for bug reports and feature requests.

From looking at your code, you probably want to replace the entire `CallExpression`, using the node as the only argument to a doubly-nested `CallExpression`. Something like this pseudo-AST (based on your above example):

```
CallExpression
  callee =
    CallExpression
      callee = someDecorator
      arguments = [etc]
  arguments = [originalNode]
```

**Comment by eventualbuddha** [comment]
Also, when I was working on esnext I built a tool that I used to generate an ast-types compatible code snippet representing arbitrary JavaScript code. It's in ast-util:

```
~ » git clone https://github.com/eventualbuddha/ast-util.git
~ » cd ast-util
ast-util » npm install
ast-util » ./bin/make-builder <<EOS
> someDecorator(etc)(React.createClass())
> EOS
b.callExpression(
  b.callExpression(
    b.identifier('someDecorator'),
    [b.identifier('etc')]
  ),
  [
    b.callExpression(
      b.memberExpression(
        b.identifier('React'),
        b.identifier('createClass'),
        false
      ),
      []
    )
  ]
)⏎
```

**Comment by timbur** [comment]
I see.  Thanks for the help and sorry for adding some clutter to the issues.  Will use Slack in the future.  :)
