### ISSUE TITLE
Add note re. ES6 to Webstorm setup page

### ISSUE THREAD

**Issue by dandv** [babel/babel#1957]
To avoid any snags in getting started with Babel in WebStorm, https://babeljs.io/docs/setup/#webstorm should mention that one more setting needs to be changed: Languages & Frameworks -> JavaScript -> JavaScript language version -> ECMAScript 6.

By default, WebStorm ships with ES5.1.

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by dandv** [comment]
Thanks. Filed at https://github.com/babel/babel.github.io/pull/362.
