### ISSUE TITLE
babel use of non specific import (requires) causes issues in Atom editor

### ISSUE THREAD

**Issue by gandm** [babel/babel#1959]
I have an atom package https://atom.io/packages/language-babel  that has a dependency on the latest version of Babel-core; at this time 5.6.15. Atom itself uses Babel-core 5.1.11 and atom packages can  "use babel" 'pragma' to compile on the fly. Because Babel uses non specific imports I have a situation where my call to babel-core 5.6.15 'requires' modules in Babel-core 5.1.11 as these are cached by other packages prior.

Any chance on using relative ./ type imports across the board for internal Babel files?

**Comment by sebmck** [comment]
> Any chance on using relative ./ type imports across the board for internal Babel files?

It does? All of the imports are relative.

**Comment by gandm** [comment]
> Isn't it this way already? All of the imports are relative

My mistake. Must have misread a line! One of my users is getting a stack trace on a Babel transpile  at ast-types and I thought it was an internal not a dependency. https://github.com/gandm/language-babel/issues/17

Any ideas?

**Comment by gandm** [comment]
Seems that my user no longer has the issue. I'm pretty sure it was an issue where my package was being updated asynchronously and not all the node-modules (ast-types) were present so the atom provided one was used. However, I don't know why this didn't work as the ast-types dependency version hasn't changed from babel 5.1.13 to 5.6.15.  I did notice that babel package.json uses ^semver for all modules apart from a tilde ~semver for ast-types. I can think of no good reason this would cause an issue but who knows. 

Sorry for my error in reporting this as an issue.

**Comment by sebmck** [comment]
All good, better to be safe than sorry. :blush:

> I did notice that babel package.json uses ^semver for all modules apart from a tilde ~semver for ast-types.

It's because the same version of `ast-types` is required that `recast` uses and so it has to match the same range.
