### ISSUE TITLE
Constructor cannot be called as a function

### ISSUE THREAD

**Issue by jruchaud** [babel/babel#1966]
I wrote this code to extends KeyboardEvent from native API:
```js
class KeyEvent extends KeyboardEvent {
}
```
I use babel to transpile the code to ES5. But after, during executing the code, I get this error:
```
Uncaught TypeError: Failed to construct 'KeyboardEvent': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

**Comment by sebmck** [comment]
Show the code you're using to create a `KeyEvent` please.

**Comment by jruchaud** [comment]
It is just : new KeyEvent();

**Comment by sebmck** [comment]
It'd be because the super class is being called with `apply`. I don't think there's a way around this unless you just use native classes.

**Comment by jruchaud** [comment]
What's pity.
