### ISSUE TITLE
Async await bug on the client.

### ISSUE THREAD

**Issue by Atsman** [babel/babel#1968]
Hello guys. 

I have done a lot of work using async await. It was tested only on server and now i faced the problem, that block me at all. It doesn't work on the client side. :/

 Please see simple code fragment.

```javascript
(async function withSomeValue() {
  const value = await Promise.resolve('VALUE'); //RETURNS UNDEFINED
  console.log(value);
})();
```

Does somebody know some workarounds? 
Thank you.

**Comment by sebmck** [comment]
[I can't replicate this.](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=(async%20function%20withSomeValue()%20%7B%0A%20%20const%20value%20%3D%20await%20Promise.resolve('VALUE')%3B%20%2F%2FRETURNS%20UNDEFINED%0A%20%20console.log(value)%3B%0A%7D)()%3B&playground=false) Please provide a reproducible example in the REPL.

**Comment by Atsman** [comment]
Hello,

Sorry i miss require("babel/polyfill"); that was the reason.

Sorry.
