### ISSUE TITLE
Support different targets in .babelrc

### ISSUE THREAD

**Issue by mpal9000** [babel/babel#1970]
Hello, is there any way to specify via .babelrc that I want to blacklist some transformers based on the target environment eg. "node", "browser" etc.? This is different from the `env` option, because I want to use combinations of those two eg. "node/production", "browser/development" etc. This is useful because I can then blacklist the "arrow-functions" transformer for example, but only for io.js (with flag). Node/io will always support more features than all the browsers combined, because it is only one engine. Maybe a `process.env.BABEL_TARGET` or something similar that will work like `env`, could be useful.

**Comment by sebmck** [comment]
You can use `BABEL_ENV`.

**.babelrc**

```json
{
  "env": {
    "foobar": {}
  }
}
```

```sh
$ BABLE_ENV=foobar babel script.js
```

**Comment by mpal9000** [comment]
I would like to use combinations of `BABEL_ENV` and another "BABEL_TARGET" variable.

**Comment by sebmck** [comment]
I'm confused, why? Babel isn't a build system and the options currently provided are more than adequate for basic use-cases. If you need anything more sophisticated then I'd recommend using something like [Gulp](https://github.com/gulpjs/gulp) or [Grunt](https://github.com/gruntjs/grunt).

**Comment by mpal9000** [comment]
all right, thank you!

**Comment by sebmck** [comment]
No problem, feel free to check out the links in the README if you have an further questions :blush: 

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
