### ISSUE TITLE
[Blocker] Broken class transformation, wrong prototype assignment order

### ISSUE THREAD

**Issue by nktpro** [babel/babel#1972]
Before v5.6.16, this is transformed correctly:

    class Foo {

    }

    class Bar extends Foo {
      bar () {
        return 'bar';
      }

      constructor(whatever) {
        super();
      }
    }

    let test = new Bar();
    test.bar();

To:

    var Foo = function Foo() {
      _classCallCheck(this, Foo);
    };
    
    var Bar = (function (_Foo) {
      function Bar(whatever) {
        _classCallCheck(this, Bar);
    
        _Foo.call(this);
      }
    
      _inherits(Bar, _Foo);
    
      Bar.prototype.bar = function bar() {
        return 'bar';
      };
    
      return Bar;
    })(Foo);
    
    var test = new Bar();
    test.bar();

Since v5.6.16, it became:

    var Foo = function Foo() {
      _classCallCheck(this, Foo);
    };
    
    var Bar = (function (_Foo) {
      Bar.prototype.bar = function bar() {
        return 'bar';
      };
    
      function Bar(whatever) {
        _classCallCheck(this, Bar);
    
        _Foo.call(this);
      }
    
      _inherits(Bar, _Foo);
    
      return Bar;
    })(Foo);
    
    var test = new Bar();
    test.bar();

Notice that `Bar.prototype.bar = ...` assignment happens before `_inherits(Bar, _Foo);`, which wipes out `Bar.prototype` with its internal assignment of `subClass.prototype = ...`

This breaks all existing code that has sub-classes with methods defined above the constructors.

**Comment by gaearon** [comment]
To anyone having the same issue, you can verify whether *this* is the bug you have the problem by moving your constructor to be the first thing in your class.

**Comment by loganfsmyth** [comment]
Looks like this only affects loose-mode classes, with the new class code refactor.

**Comment by loganfsmyth** [comment]
This was fixed in v5.6.18 FYI.
