### ISSUE TITLE
Put configuration statement at the top of the file

### ISSUE THREAD

**Issue by ariporad** [babel/babel#1973]
Hi Everyone!

Love Babel, but I have one problem thought. I use app-module-path to make all requires (and in ES6/babel, imports), relative to the app base path. So I have the following line of code at the top of my main .es6 file (It's the second line, there's a comment above it):

    require('app-module-path').addPath(__dirname);

I have not found a way to make babel keep that at the top. Right now it moves all the imports to the top of the file, which means that not only does it not work for main.es6, none of the other modules get it either.

Is there some way to do this, or would a PR for this be accepted? (I think the auxiliary comment could be converted to auxiliary line or something).

Thanks!
Ari

**Comment by sebmck** [comment]
Yeah, imports are hoisted. This is to the spec and there's no way around it. See #1057, #1371 and #1676. In the future, please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thank you :blush:

**Comment by ariporad** [comment]
Oops... Sorry.

**Comment by ariporad** [comment]
Can I make a feature request based off this then? Or do I need to make a new issue?

**Comment by sebmck** [comment]
Sure, either works.

**Comment by ariporad** [comment]
Ok. I'd like to request a way to force Babel to import things relative to a directory. Similar to NODE_PATH. I think that'd be inline with the spec. Or no?

**Comment by sebmck** [comment]
Seems like a job for a module bundler. There's the `resolveModuleSource` option that you can use to intercept and rewrite module sources, docs are available [here](http://babeljs.io/docs/usage/options).
