### ISSUE TITLE
Flow: support `import typeof` construct 

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#1975]
Flow team recently introduced new syntax, `import typeof`, which looks like this:

```javascript
import typeof Foo from 'Foo';
```

Where `import type` is sugar for `type Foo = [[remote *type* export]]`, and `import typeof` is sugar for `type Blah = typeof [[remote *value* export]]`.

**Comment by DmitrySoshnikov** [comment]
According to [esprima-fb](https://github.com/facebook/esprima/blob/fb-harmony/esprima.js), new field `importKind` was added, which can be `type` (for `import type`) or `typeof` (for `import typeof`). The `isType` field seems is removed.

**Comment by DmitrySoshnikov** [comment]
Thanks for the quick fix, can we have this published please? (5.6.17 says "2 days ago").

**Comment by sebmck** [comment]
Just pushed 5.6.18, will be released once the Travis build is done: https://travis-ci.org/babel/babel/builds/70564316

**Comment by DmitrySoshnikov** [comment]
@sebmck, thanks!
