### ISSUE TITLE
Strings always output as double quotes?

### ISSUE THREAD

**Issue by DylanPiercey** [babel/babel#198]
This is a problem.

**Input**

```
    var foo = 'foo';
    var bar = "bar";
```

**output**

```
    var foo = "foo";
    var bar = "bar";
```

I can't switch?

**Comment by aexmachina** [comment]
Is there any way we can get 6to5 not to transform our quotes? I hate double quotes!

**Comment by sebmck** [comment]
@aexmachina See #694

**Comment by aexmachina** [comment]
Great, thanks.​
