### ISSUE TITLE
IE8 named functions

### ISSUE THREAD

**Issue by elijahdorman** [babel/babel#1980]
I just noticed that if I do something like

```javascript
var foo = function bar() {};
```

That Babel appears to leave that as-is which causes issues on IE8. Is there an option I'm missing somewhere?

**Comment by sebmck** [comment]
What do you expect to happen?

**Comment by elijahdorman** [comment]
IE8 doesn't know how to deal with named functions. I'm not sure of all the implications (I can't think of any problems at the moment), but I think something like the following would work as it simply moves the label from the name property to a closure.

```javascript
var foo = (function () {
  var bar = function () {};
  return bar;
}());
```

**Comment by darkyen** [comment]
:-1:  that doesnt seems to be logical at all, IE 8 is not even supported by Microsoft anymore.

Also named functions are used for callbacks instead of anonymous ones.
```javascript
function bar(){
}
var foo = bar;
```
Is closer to what you are willing to get.

**Comment by sebmck** [comment]
Yeah that's never going to be default behaviour. There is however an optional [`jscript`](http://babeljs.io/docs/advanced/transformers/other/jscript/) transformer that does exactly what you want.

**Comment by elijahdorman** [comment]
That is precisely the transformer I overlooked. Thank you very much!
