### ISSUE TITLE
Some problem with `babel-node` (cli) and repl

### ISSUE THREAD

**Issue by basecss** [babel/babel#1981]
First, say sorry for my poor English.

I have some code like this:

```javascript
let someObject = {
    * someGeneratorFunction() {
        // some code here
    }
}
let someGeneratorObject = someObject.someGeneratorFunction()
```

When I using `babel-node` (cli) to compile and run my code, there has a `ReferenceError: someGeneratorFunction is not defined`.

But, when I copy my code to online [repl editor](http://babeljs.io/repl/) and evaluate these code, they works fine.

Some other information:

- Mac OS X 10.10.4
- `babel --version` -> `5.6.14`
- Browser: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36`

Is there has a bug? Or, I missed some information?

**Comment by loganfsmyth** [comment]
I can't repro this with babel-node locally.

**Comment by basecss** [comment]
@loganfsmyth Thanks.

I also didn't repro this. Maybe I missed some info.

**Comment by loganfsmyth** [comment]
@basecss Okay, I'm going to close this then. If you run into it again, feel free to join to Slack channel and we can try to help figure it out.
