### ISSUE TITLE
With The Faithful 32 - Modded Edition Texture Pack

### ISSUE THREAD

**Issue by LaLamborghini** [babel/babel#1984]
With the broken items like broken iron ore, broken lead ore etc. and the crushed and powered items, the item is just a black box. Is there any known reason why its like this?

**Comment by sebmck** [comment]
What are you talking about?

**Comment by LaLamborghini** [comment]
the texture pack from www.f32.me, it says Assistance, comments, concerns, and issues on Github - (1.7.10) (1.6.4) and it was clickable

**Comment by sebmck** [comment]
What does this have to do with this project?

**Comment by LaLamborghini** [comment]
what project?

**Comment by sebmck** [comment]
This is the issue tracker for a JavaScript compiler called Babel.

**Comment by LaLamborghini** [comment]
sorry, i just realised that i must've went to a different page of this website when i went to typee my issue :(

**Comment by LaLamborghini** [comment]
why would u add the drunk label on to me?

**Comment by rlucha** [comment]
ROFL, +1
