### ISSUE TITLE
Let's document Babel!

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#1985]
Hello good people!

We recently start on [internal code documentation](https://github.com/babel/babel/pull/1897) for Babel. This is really important because it's extremely helpful for people getting into the code base to contribute.

We'll be adding more over time, but since it's a lot of busy work I thought I try to get others involved.

If you have a few minutes to spare and would like to contribute back to Babel, how about you take a few minutes find a function without a description and make a best attempt at describing the code below it.

These comments are [littered throughout the codebase](https://github.com/babel/babel/search?utf8=✓&q=Please+add+a+description.&type=Code) just waiting for you to fill them out.

```js
/**
 * [Please add a description.]
 */
```

So what are you waiting for? Go do that now! ... I said now!

**Comment by tmcw** [comment]
Hey, so I've been working on this project called [documentation.js](https://github.com/documentationjs/documentation): it's a modern documentation generator that consumes JSDoc-formatted snippets like these. If Babel is interested in using it, I'd love to help that happen, and prioritize tickets that are necessary for it to land!

**Comment by clarle** [comment]
I'd love to help.  Is there an example of what a good code documentation string looks like?

**Comment by thejameskyle** [comment]
Just a short description will do, we don't need anything with jsdocs.
