### ISSUE TITLE
Issue in printJoin method

### ISSUE THREAD

**Issue by chicoxyzzy** [babel/babel#1986]
I assume that something is wrong with [`printJoin`](https://github.com/babel/babel/blob/master/src/babel/generation/index.js#L266-L285) method

```javascript
printJoin(print, nodes, opts = {}) {
                                   // <-- DECLARED HERE
  if (!nodes || !nodes.length) return;

  var len = nodes.length;

  if (opts.indent) this.indent();

  var printOpts = {
    statement: opts.statement,
    addNewlines: opts.addNewlines,
    after: () => {
      if (opts.iterator) {
        opts.iterator(node, i);    // <-- USED HERE
      }

      if (opts.separator && i < len - 1) {
        this.push(opts.separator);
      }
    }
  };

  for (var i = 0; i < nodes.length; i++) {
    var node = nodes[i];           // <-- INITIALIZED HERE
    print.plain(node, printOpts);
  }

  if (opts.indent) this.dedent();
}
```
variable `node` is always undefined inside `printOpts.after()` because it is declared in scope of `printJoin` inside `for` loop at the end of `printJoin` (see comments)

**Comment by sebmck** [comment]
Variables are hoisted, `node` will never be `undefined`. Is this causing an actual issue because the code is fine.

**Comment by chicoxyzzy** [comment]
Yes `node` will be hoisted so it will be always `undefined` on line `opts.iterator(node, i);` just try to change var to let

**Comment by sebmck** [comment]
`opts.iterator` is supposed to be called on each child, not on the root one.

**Comment by sebmck** [comment]
No it wont. `printOpts.after` is only ever used after `node` is initialised so that's impossible.

**Comment by chicoxyzzy** [comment]
> No it wont. printOpts.after is only ever used after node is initialised so that's impossible.

Unfortunately no. Code will look like so
```javascript
printJoin(print, nodes, opts = {}) {
  var node, len, printOpts, i;                        // <-- DECLARED HERE
  if (!nodes || !nodes.length) return;

  nodes.length;

  if (opts.indent) this.indent();

  printOpts = {
    statement: opts.statement,
    addNewlines: opts.addNewlines,
    after: () => {
      if (opts.iterator) {
        opts.iterator(node, i);    // <-- IS STILL UNDEFINED THROUGH THE CLOSURE
      }

      if (opts.separator && i < len - 1) {
        this.push(opts.separator);
      }
    }
  };

  for (i = 0; i < nodes.length; i++) {
    node = nodes[i];               // <-- INITIALIZED HERE
    print.plain(node, printOpts);
  }

  if (opts.indent) this.dedent();
}
```

**Comment by sebmck** [comment]
Why do you think it's undefined throughout? It's clearly assigned and that function will never be called before the assignment. It will always be defined. Do you have anything suggesting otherwise? The print object is hoisted and not recreated each time for performance reasons (it saves on an allocation).

**Comment by chicoxyzzy** [comment]
Oops my bad. What I actually suggesting is using block scoping. But I think TDZ will lead to refactoring and performance decrease. Can we use block scoping without performance penalty somehow?

**Comment by sebmck** [comment]
Block scoping would require that the `printOpts` object be allocated for each child which will be worse for performance, there's no real reason to use it in this scenario.

**Comment by chicoxyzzy** [comment]
Yeah good point.
