### ISSUE TITLE
Unhelpful source map for module imports

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#1987]
Create an empty directory and run:

	npm install babel source-map-support
	mkdir src
	touch src/index.js src/module.js

index.js:

	import { assert } from './module'
	import { install } from 'source-map-support'
	install()

	const testMath = () => {
		assert(1 + 1 === 2)
		assert(2 + 2 === 5)
		assert(3 + 3 === 6)
	}

	testMath()

module.js:

	export const assert = cond => {
		if (!cond)
			throw new Error("Assertion failed.")
	}

Then:

	node_modules/babel/bin/babel/index.js src --out-dir js --source-maps
	node js

You'll see:

	Error: Assertion failed.
		at assert (/home/andy/programming/mason3/eslint-bugs/src/module.js:3:9)
		at testMath (/home/andy/programming/mason3/eslint-bugs/src/index.js:1:16)
		at Object.<anonymous> (/home/andy/programming/mason3/eslint-bugs/src/index.js:11:1)

It doesn't identify the line that failed.
It instead shows the line where the function was imported, which isn't helpful.

**Comment by sebmck** [comment]
Not sure what's causing this. Likely some weird issue with duplicate nodes pointing to a single location.
