### ISSUE TITLE
async/await in node v0.10.* - "Recursive process.nextTick detected" warning

### ISSUE THREAD

**Issue by helios1138** [babel/babel#1989]
the following code:
```
function sleep(delay) {
  return new Promise((resolve) => setTimeout(resolve, delay));
}

async function rAsync() {
  for (var i = 0; i < 1000; i += 1) {
    await sleep(0);
  }
}

var t3 = Date.now();
rAsync().then(() => console.log('async', Date.now() - t3));
```
throws warnings in node v0.10.*
```
...
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
...
```

**Comment by sebmck** [comment]
That warning is correct. That is a recursive `process.nextTick`. You're sleeping for no amount of time and constantly pushing onto the event loop.

**Comment by helios1138** [comment]
@sebmck then why I don't get that warning if the same code is written with co.js?
```
function sleep(delay) {
  return new Promise((resolve) => setTimeout(resolve, delay));
}

var rGenerator = co.wrap(function* () {
  for (var i = 0; i < 1000; i += 1) {
    yield sleep(0);
  }
});

var t2 = Date.now();
rGenerator().then(() => console.log('generator', Date.now() - t2));
```

**Comment by sebmck** [comment]
Because they probably have smarter detection or just removed it. It's impossible to change the way the code's generated to remove the warning being triggered since it's a fundamental consequence of the way your code is written.

**Comment by helios1138** [comment]
@sebmck why? aren't both generators and async/await are handled by regenerator module? why would there be a difference or would it be impossible to correct?

**Comment by sebmck** [comment]
Because that warning is consequence of you pushing lots of ticks onto the event loop recursively.

**Comment by helios1138** [comment]
@sebmck but I the same thing it in both cases but only get warnings in one. clearly there is some difference outside my code.

**Comment by sebmck** [comment]
Yeah, it's the difference in Node internals. The check would have changed between those versions of nodes. There's no way to stop that error without changing how your code works. This error would happen if you were doing the same operations regardless of if you were using Babel or regenerator.
