### ISSUE TITLE
Bring back `do` expressions

### ISSUE THREAD

**Issue by wycats** [babel/babel#1994]
They were advanced in [January 2014](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-01/jan-29.md#conclusionresolution-2).

I added them to the [Stage 0 proposal list](https://github.com/tc39/ecma262/blob/master/stage0.md).

**Comment by sebmck** [comment]
Thanks @wycats. Reverted via a286a86b6dd40d8da14f1b51271d0c946ef4157a and 2b32a2781e123ea11d8f3e2a5a868aa2adf8d805 and released as 5.6.20. Was under the impression they were "stage negative zero" from [this](https://twitter.com/domenic/status/620616240307011584) tweet:

> @dan_abramov lollll @babeljs is implementing stage negative one proposals now?? Hilarious.

**Comment by zenparsing** [comment]
@wycats anyone know Andreas' github handle?  Maybe he has a different link than something Dave wrote like 4 years ago.  : \

**Comment by dherman** [comment]
@zenparsing The wiki page is still accurate (it's a simple feature!). Andreas had proposed alternatives at one of the meetings and the committee agreed the original was better. I'll see if I can dig up those minutes.

**Comment by zenparsing** [comment]
@dherman Cool : )

**Comment by zenparsing** [comment]
@dherman 

> (it's a simple feature!)

famous last words  ; )

**Comment by dherman** [comment]
Oh ha @wycats already linked to the minutes above. The minutes aren't detailed but you can see some discussion of alternative scoping semantics (which were rejected) and reiterating the grammar restriction that eliminates the ambiguity (which is in the wiki page).

**Comment by dherman** [comment]
@zenparsing lol, at least I didn't say TC39's favorite "this should be a quick discussion" :P

**Comment by zenparsing** [comment]
![two_hours_later_in_squidtastic_voyage](https://cloud.githubusercontent.com/assets/5995084/8660535/8544937c-297f-11e5-9972-b01e951e7b33.png)

**Comment by rossberg-chromium** [comment]
@dherman, for the record, it's not entirely simple. The discussion at TC39 (not reflected in the notes) mostly revolved around various edge cases of non-local control transfer and var hoisting, in contexts that could not have that before. Some of that actually is rather surprising, or a pain to implement for little benefit. I doubt that Babel gets those right, since a full desugaring would be quite involved.

**Comment by sebmck** [comment]
@rossberg-chromium The Babel implementation is implemented with the information provided in the wiki page. If you have any corrections (whether now or in the future) then I'd be happy to fix them.

**Comment by rossberg-chromium** [comment]
@sebmck, to clarify, the wiki isn't wrong, it just glosses over a few complications (like strawmen tend to do). I haven't actually tried the Babel implementation, so I'm not sure I can provide useful feedback at this point.
