### ISSUE TITLE
Show error message if file is not in .babelrc#only

### ISSUE THREAD

**Issue by ceram1** [babel/babel#1997]
Currently, babel transparently print empty file without any message.

[Related issue](https://github.com/google/web-starter-kit/issues/713#issuecomment-121112429)

**Comment by sebmck** [comment]
This is intentional behaviour. It's meant to be a passthrough for tools and should not throw an error. Also it doesn't (or shouldn't if this is happening for you) output an empty file, it outputs the original file verbatim.
