### ISSUE TITLE
Empty optional transform

### ISSUE THREAD

**Issue by akre54** [babel/babel#1998]
Is there any way to insert an optional transform as intentionally left blank? I want to set the `react.inlineElements` transform to only run in production but there doesn't seem to be a nice way to handle a ternary.

```js
query: { optional: ['optimisation.react.constantElements', PROD ? 'optimisation.react.inlineElements' : null] } },
```

The logic for the pipeline appears to be [here](https://github.com/babel/babel/blob/v5.6.20/src/babel/transformation/pipeline.js#L163-L181), but it doesn't seem to handle any falsey values, instead falling through to the `Module build failed: ReferenceError: Unknown transformer null specified in optional` message.

Could we use some sentinel value, either `''`, `false`, or `null` to signify "this space intentionally left blank?

**Comment by sebmck** [comment]
The `env` option provided by [babelrc](http://babeljs.io/docs/usage/babelrc/#env-option) looks like what you want.

**.babelrc**

```json
{
  // my default options
  "env" : {
    "production": {
      // options that will be used when process.env.NODE_ENV === "production"
    }
  }
}
```

If that's not a solution then you can just do:

```javascript
query: { optional: PROD? ['optimisation.react.constantElements', 'optimisation.react.inlineElements'] : ['optimisation.react.constantElements'] } },
```

You're duplicating transformers but it's the only way.

**Comment by akre54** [comment]
Thanks for the quick reply. Is there any objection to ignoring falsey (or null) transforms instead of making them fall through to the error case?

I'd rather not add a whole extra file for babel when the rest of my config already lives in webpack.config.js, and duplicating the array (or pulling it out to a separate variable) is an ugly workaround. Would you reconsider if I opened a pull?

**Comment by sebmck** [comment]
The options are strict on purpose. The likelihood of a falsy value being the result of a bug is higher than your use-case. You can also alternatively do:

```javascript
query: { optional: ['optimisation.react.constantElements'.concat(PROD ? 'optimisation.react.inlineElements' : []) } },
```

**Comment by akre54** [comment]
Thanks. That's what I ended up doing.

For the record I disagree (see how JSX handles ternaries or webpack handles noop plugins, e.g.), but I appreciate the help.
