### ISSUE TITLE
[Feature request] babel register require hook

### ISSUE THREAD

**Issue by quirinpa** [babel/babel#1999]
Hello guys. Awesome job with babel. I'm so happy to be using es6 and jsx!
Anyway, i'd like to request a feature, not sure if it's possible.

I'd like to register my own loaders to babel's require hook, similarly to what webpack does.

I'm trying to make my first isomorphic app with react and recently i've noticed a warning in the console, indicating that the server side DOM is different from the initial client side DOM. That happens because i only "require" images in the client side (through webpack). File names change when i run them through webpack, but i could, theoretically, save webpack stats to a file, and if i could hook into babel's require and read that file, i could have the correct object (in this case a string, with the new image filename) returned by the require function, and it would easily solve my problem. I can think of a couple other use cases aswell.

I've tried looking into your source code and maybe make my own tool to deal with that but i'm afraid i lack the understanding to do so.

Do you guys think such a thing would be possible? Thanks anyway, and thank you for the awesome tool!

**Comment by sebmck** [comment]
No problem :blush: I'm not sure I completely understand what you're requesting. Do you want the option to call a callback whenever a new file is compiled via the require hook, do you want to arbitrarily alter the output or provide different options etc?

**Comment by quirinpa** [comment]
Hey! Thanks for the quick response! ^^

Well i'd like to alter the output, but not the output of js or jsx files which are compiled by babel, i'd like to have the ability to hook into some extensions which would be ignored by babel's compiler to instead run my callback function (for example for css files or images). In my particular case i'd just need to receive the file's path as an argument in my callback function.

**Comment by sebmck** [comment]
Not really related to Babel then. Node allows you to register arbitrary hooks for extensions. You can just do:

```javascript
require.extensions[".png"] = function (m, filename) {
  m.exports = "i'm a png of filename " + filename;
};
```

And every time you `require` a file that resolves to that extension it will return `"im a png of filename x"`.

**Comment by quirinpa** [comment]
Oh! I'm so sorry sebmck for my ignorance :P i love your work, thank you so much for your assistance!

**Comment by sebmck** [comment]
All good! :relaxed: Feel free to check out the [Slack community](http://babel-slack.herokuapp.com) if you need any help.

**Comment by quirinpa** [comment]
Thanks :) ur awesome
