### ISSUE TITLE
Experimental: Object Rest and Spread properties

### ISSUE THREAD

**Issue by ceane** [babel/babel#200]
Currently in with React 0.12, there are [Object rest and spread properties](http://facebook.github.io/react/docs/jsx-spread.html#whats-with-the-weird-...-notation) with JSX. Would you consider implementing this feature only for JSX files?

**Comment by omerts** [comment]
Hello,

Are you sure this is supported? I am trying the following, and it isn't working:
```javascript
let {tags, dropDownLabel, ...other} = this.props;
```
Getting the following error from the babel webpack loader:
![image](https://cloud.githubusercontent.com/assets/4996164/6603430/c571273c-c82a-11e4-9241-bb015ef504b8.png)

**Comment by zloirock** [comment]
@omerts [works](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=false&loose=false&spec=false&code=let%20%7Btags%2C%20dropDownLabel%2C%20...other%7D%20%3D%20this.props%3B) with [experimental flag](https://babeljs.io/docs/usage/experimental/).

**Comment by omerts** [comment]
@zloirock Thank you for your help
