### ISSUE TITLE
`runtime` transformer without core-js aliasing

### ISSUE THREAD

**Issue by impinball** [babel/babel#2001]
This would be really nice for larger applications that aren't libraries, where they could still use the full, globally polluting polyfill, but the helpers wouldn't be duplicated across several modules. It would make the compiled code faster to load, and a lot smaller overall. These benefits are nice for both Node applications and web applications, where the deduplication would make programs significantly smaller. As for the core-js aliasing, it could just require the module at the top of every file that needs a feature from it, which doesn't add a lot of size overhead to the files.

**Comment by loganfsmyth** [comment]
If you have an app, you can load the polyfill in your entry point and use [external helpers](http://babeljs.io/docs/advanced/external-helpers/) to avoid repeating the helpers.

**Comment by impinball** [comment]
Thanks! Didn't know that served my purpose!
