### ISSUE TITLE
this in object is to undefined

### ISSUE THREAD

**Issue by welefen** [babel/babel#2002]
```
export default {
  name: 'welefen',
  getName: () => {
    return this.name();
  }
}
```
compiled code is 
```
'use strict';

exports.__esModule = true;
exports['default'] = {
  name: 'welefen',
  getName: function getName() {
    return undefined.name();
  }
};
module.exports = exports['default'];
```

this in getName method is transform to undefined.

**Comment by eventualbuddha** [comment]
Please see the [FAQ](https://babeljs.io/docs/faq/) under "Why is `this` being remapped to `undefined`?"

In this particular case, you want this:

```js
export default {
  name: 'welefen',
  getName() {
    return this.name;
  }
}
```

Note that you were also using `this.name` As a method when it's a string.
