### ISSUE TITLE
Retrieve the filename of the script currently being processed from within a plugin

### ISSUE THREAD

**Issue by phpnode** [babel/babel#2003]
For many reasons it's useful to be able to get the name of the current filename from within a plugin, this used to be possible with `this.scope.file.opts.filename` but that has changed to `this.scope.hub.file.opts.filename`. Relying on such a deeply nest object is obviously going to be fragile, so please can we have a getter for this? e.g. `this.filename`?

**Comment by sebmck** [comment]
This will probably have to wait for 6.0.0 where the fourth argument of visitor methods will be a public API. This is one of those scenarios where enough people have decided to use the fourth argument to access private stuff that I can't change it without breaking a lot of stuff. Adding a getter onto each traversal path isn't really an option and it's not the right place for it.

**Comment by phpnode** [comment]
@sebmck until then is it safe to rely on `this.scope.hub.file.opts.filename`? There are certain types of plugin which are simply impossible to write without this feature.

**Comment by timbur** [comment]
@phpnode If you need the full path to the file, you can do something along these lines (assuming you're able to pass options to `babel.transform`):

```js
var pathname = getFilePathname();
var filename = getFilename();
var source = getFileSource();
var options = {
  _pathname: pathname,  // this is an unknown option so it needs an underscore
  filename: filename,   // babel uses this option, so no underscore needed
  ...etc                // and add your usual `babel.transform` options
};

var output = babel.transform(source, options);
```

Then within your transformer:
```js
function transform (babel) {
  var t = babel.types;

  return new babel.Transformer(pluginPath, {
    ClassDeclaration: function (node, parent, scope, file) {
      // you can get the full path for the file now via
      console.log(file.opts._pathname);
      // or just the filename via
      console.log(file.opts.filename);
    }
  });
}
```

**Comment by phpnode** [comment]
@timbur thanks for the suggestion but it doesn't sound ideal because then my plugin can't work with most people's workflows (e.g. stick `<plugin-name>` in your `.babelrc` and boom)

**Comment by timbur** [comment]
Is `file.opts.filename` not available by default via the `.babelrc` method?

**Comment by timbur** [comment]
Also, the `file` variable I'm referring to would be the 4th argument that @sebmck is referring to, I believe.

**Comment by phpnode** [comment]
@timbur wouldn't it refer to a single file? I'm interested in being able to run this on a directory full of files and get the name of the current one.

**Comment by timbur** [comment]
If you've been using `this.scope.file.opts.filename`/`this.scope.file.opts.filename`, I believe `file.opts.filename` is the same thing (where `file` is the 4th argument within `ClassDeclaration(node, parent, scope, file)`, for example), and it should be the "reliable" way to do it even though it won't exactly be the official way until `6.0.0` as @sebmck said in his comment.

**Comment by hzoo** [comment]
It can be `state.file.opts.filename` in babel 6 with `visitor(path, state)`

**Comment by yuri-karadzhov** [comment]
What about babel 7? Seems like that stops working and `state.file.opts.filename` is not defined, I tested it in beta 41 and 44.
