### ISSUE TITLE
Decorators in object literals should not use initializers

### ISSUE THREAD

**Issue by bergus** [babel/babel#2005]
Example (stolen from [here](http://stackoverflow.com/q/31433630/1048572)):
```js
function decorate(object, propertyName, desc) {
    console.log(desc);
    return desc;
}
let obj = {
  @decorate
  prop: 10
}
```
I would expect to get `{value: 10, writable: true, enumerable: true, configurable: true}`, but [currently it yields](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20decorate(object%2C%20propertyName%2C%20desc)%20%7B%0D%0A%20%20%20%20console.log(Object.keys(desc))%0D%0A%20%20%20%20console.log(desc)%3B%0D%0A%20%20%20%20console.log(desc.initializer)%0D%0A%20%20%20%20return%20desc%3B%0D%0A%7D%0D%0Alet%20obj%20%3D%20%7B%0D%0A%20%20%40decorate%0D%0A%20%20prop%3A%2010%0D%0A%7D) `{"initializer":function initializer() { return 10; }, "enumerable":true,"configurable":true,"writable":true}`.

I understand that the `initializer` is necessary for [class (instance) properties](https://github.com/wycats/javascript-decorators/blob/master/INITIALIZER_INTEROP.md), but it shouldn't be for plain object properties.

**Comment by sebmck** [comment]
Nope, this is expected behaviour. The [specification](https://github.com/wycats/javascript-decorators) just doesn't include an example of an object literal with a bare property. @wycats can confirm.

**Comment by bergus** [comment]
@sebmck Could you please point me to a discussion or other resource where this is laid out? I could not find anything, and would like to update my answer on SO with a reference.

**Comment by loganfsmyth** [comment]
@bergus https://github.com/wycats/javascript-decorators/blob/master/INITIALIZER_INTEROP.md covers the interop. For what it's worth, I lead toward your view of it. If you decorate a property, and that property isn't assigned until the constructor runs, it feels like that's when the decorator shouldn't run until then either, just for the same of simplifying the decorator interface.

It's the question of whether decorators run at declaration time, or always run with a standard descriptor.

**Comment by wycats** [comment]
> If you decorate a property, and that property isn't assigned until the constructor runs, it feels like that's when the decorator shouldn't run until then either, just for the same of simplifying the decorator interface.

I don't really understand this sentence. I presented my latest thinking at the last TC39, and it amounted to the fact that I'd like the same decorator to work for all of these cases:

```js
class A {
  @deco b = x;
  @deco static c = x;
}

let d = {
  @deco e: x,
  @deco f: x
}
```

And the same decorator to work for all of these cases:

```js
class A {
  @deco meth() {}
  @deco static meth() {}
}

let b = {
  @deco meth() {}
}
```

In short, you should be able to write a single decorator and have it work for the declarative constructs that look the same.

**Comment by loganfsmyth** [comment]
Yeah sorry, that was just a very poorly written sentence, I appear to have written part of a sentence and then reworded it and not deleted the previous part :(

>   If you decorate a property, and that property isn't assigned until the constructor runs, it feels like that's when the decorator shouldn't run until then either

should be 

>   If you decorate a property, and that property isn't assigned until the constructor runs, it feels like the decorator shouldn't run until then either

Basically I'm surprised that the decorator runs at class declaration time, causing it to need to know about initializers. Since the property initializer runs in the constructor, it seems more intuitive to have the decorator run at that point as well. That leads to potential confusion in decorator execution timing though, which I assume is part of the motivation to not do that in the current interop?

I can't tell from your example, is the expectation that decorators for your first group of examples would have to be aware of descriptors with initializer functions, and the second group would work on normal descriptors?

**Comment by wycats** [comment]
> If you decorate a property, and that property isn't assigned until the constructor runs, it feels like the decorator shouldn't run until then either

It's a critical constraint that decorators can run only once when the class is built and not add additional runtime cost unless the decorator chooses to add cost (by wrapping, for example). You can achieve both goals via initializer functions, but deferring the decorator until instantiation adds unavoidable cost.

> I can't tell from your example, is the expectation that decorators for your first group of examples would have to be aware of descriptors with initializer functions, and the second group would work on normal descriptors?

Right. Although it's conceivable that **all** decorators could work with initializers, including methods.

**Comment by loganfsmyth** [comment]
Interesting, I can see the reasoning behind it, but I worry that it's unintuitive for people using class properties. If this discussion has happened elsewhere, feel free to point me that way.

Is the additional runtime cost primarily around having to use defineProperty inside the constructor? By using class properties, you are already asking for something to be executed at initialization time, and the cost of executing the decorator and defining at that point in time seems like it would go along with that.

I'm just concerned that adding a new descriptor field will lead to more confusion and complexity.

**Comment by bergus** [comment]
@wycats I can see that you would want them to work the same, but I think that's a really bad idea. Modifying initialisers (with caching to reduce cost, or anything that adds cost to the initialisation, or whatever) is completely different from modifying descriptors (where you hold a `value` in your hand already, whether that is a function or not). Mingling those will add lots of confusion.
```
@deco b = x;
@deco static c = x;
```
should *not* work the same, otherwise I would expect
```
@deco m = function() {}
@deco m() {}
```
to have the same descriptors as well. Class properties (I begin to hate that term, "constructor-initialised instance properties" would be more descriptive) are vastly different from static and object properties, and I'd like to have that reflected in decorators as well.

Alternatively, I'd suggest to use only initialisers and no more `value` descriptors at all, as this would be much more powerful concept, leading towards a more macro-powered language given that the expression is represented as a function and can be evaluated by the decorator as often as it wants to. Hey, just think about `class { @lazy static val = costlyCall() }` :-)

It seems as if this wasn't discussed enough yet. Should we rather move the discussion to https://github.com/wycats/javascript-decorators?
