### ISSUE TITLE
Single-line comments break compact mode

### ISSUE THREAD

**Issue by jbt** [babel/babel#2006]
Tried with babel@5.6.23:

Compiling this:

```js
// hi there
foo();
```

with `compact: true`

outputs this, which doesn't look good :(

```js
// hi there"use strict";foo();
```

**Comment by sebmck** [comment]
Regression due to #1810. Workaround is to set `comments: false`.

**Comment by jbt** [comment]
Yup shoulda mentioned `comments:false` is fine and wonderful and works so I'm happy :) but obviously presumably still a Bad Thing that presumably shouldn't be happening.

**Comment by sebmck** [comment]
Fixed as of 5.7.1, thanks!
