### ISSUE TITLE
5.7.0 introduces an issue

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#2009]
builds works but the produced output includes malformed output.

The issue seems to be related to a file that is larger the 100KB. Going to try to reduce the problem to something easier to work with.

**Comment by sebmck** [comment]
It's probably #2006.

**Comment by stefanpenner** [comment]
Im having a tricky time narrow it down, beyond just the output of all of ember.js is broken.

I need to grab lunch, then I have a few meetings. I'll try to circle back and provide a reduced example.

**Comment by stefanpenner** [comment]
@sebmck you are likely correct, https://github.com/babel/babel/issues/2006 is most likely the issue.

**Comment by stefanpenner** [comment]
I'll confirm against master (which may have just gotten a fix)

**Comment by sebmck** [comment]
Just pushed out 5.7.1, let me know if that did the trick.

**Comment by stefanpenner** [comment]
5.7.2 fixes the issue, thank you kindlY
