### ISSUE TITLE
Support number literal type annotations for Flow

### ISSUE THREAD

**Issue by frankychung** [babel/babel#2013]
This is regarding [disjoint unions for Flow 0.13.1](http://flowtype.org/blog/2015/07/03/Disjoint-Unions.html) which allows string and number literals as types. Currently number literals such as `type Test = 1;` give an `Unexpected token` error. [Here is a simple example from the repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=type%20Test%20%3D%20'foo'%3B%0Atype%20Test2%20%3D%201%3B).

**Comment by hzoo** [comment]
Can close this now - nice job!

**Comment by sebmck** [comment]
Oh yeah, closed via #2035. Thanks @frankychung!
