### ISSUE TITLE
Decorators don't work with generator methods that use star syntax

### ISSUE THREAD

**Issue by SerpentJoe** [babel/babel#2014]
Babel supports generator methods on classes using star syntax, and also supports ES7 decorators (with that transformer applied). However it doesn't seem to support them used together.

Consider the following code:

```es6
'use strict';

function decorator(target, name, descriptor) {
    // TODO
}

class Asdf {
    
    @decorator
    nonGeneratorWithDecorator_noError() {
        return 0;
    }
    
    *generatorWithoutDecorator_noError() {
        yield 0;
    }

    @decorator
    generatorWithoutStarSyntaxButWithDecorator_noError() {
        return (function* () {
            yield 0;
        }());
    }
    
    @decorator
    *generatorWithDecorator_error() {
        yield 0;
    }
    
}
```

Babel version 5.6.23 (babel-core 5.7.2) throws the following syntax error:
```
SyntaxError: src/app.js: Unexpected token (26:36)
  24 |
  25 |     @decorator
> 26 |     *generatorWithDecorator_error() {
     |                                     ^
  27 |         yield 0;
  28 |     }
  29 |
```

After looking at the [decorators proposal](https://github.com/wycats/javascript-decorators) I don't see anything suggesting they shouldn't apply to generator methods, so I think this is a bug.

Any suggestions where to begin writing a fix?

**Comment by sebmck** [comment]
Not a bug, just ambiguous grammar, see wycats/javascript-decorators#10.

**Comment by SerpentJoe** [comment]
Ah, my mistake. Thanks for looking into it.

**Comment by santialbo** [comment]
@sebmck this has been fixed on the spec https://github.com/wycats/javascript-decorators/pull/34/files. Is it worth re-opening this issue or should we create a new one?

**Comment by sebmck** [comment]
@santialbo #2459
