### ISSUE TITLE
git tags after 5.6.20 are missing

### ISSUE THREAD

**Issue by tricknotes** [babel/babel#2019]
There are [required](https://github.com/babel/ruby-babel-transpiler/blob/master/script/build-gem#L19) to build [babel-source](https://github.com/babel/ruby-babel-transpiler) gem.
Could you tagged it?

**Comment by sebmck** [comment]
Looks like I messed up the build script and used the wrong command to push tags. The tags existed locally but they were never pushed, just pushed them now. Thanks!

**Comment by tricknotes** [comment]
Thanks too :dizzy:
