### ISSUE TITLE
Webstorm 10 settings

### ISSUE THREAD

**Issue by StevenTCramer** [babel/babel#2023]
On page https://babeljs.io/docs/setup/#webstorm
it says
"In Preferences | Tools | File watchers, click + button and select Babel file watcher from the list."

In webstorm 10 it is:
File->Settings->Tools->File Watchers

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
