### ISSUE TITLE
Prototype object of ES6 classes always non-writable

### ISSUE THREAD

**Issue by broadsw0rd** [babel/babel#2025]
If we try to [compile](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Foo%7B%7D%0A%0Aconsole.log%28Object.getOwnPropertyDescriptor%28Foo%2C%20'prototype'%29.writable%29) this snippet with babel, we will get `true` in our console. But if run it in Chrome 43, we will get `false`.

``` js
class Foo{}

console.log(Object.getOwnPropertyDescriptor(Foo, 'prototype').writable)
```

**Comment by sebmck** [comment]
Looks like this is the case:

[14.5.14 Runtime Semantics: ClassDefinitionEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-classdefinitionevaluation)

> 16. Perform MakeConstructor(F, false, proto).

Second argument to `MakeConstructor` is `writablePrototype`.

**Comment by sebmck** [comment]
I can do this for derived classes since they already use a helper and it wouldn't be much extra but I'm not sure if it's worth it for plain classes.

**Comment by broadsw0rd** [comment]
I`m sure this is exactly unnecessary for `loose mode`

**Comment by wentout** [comment]
Started an attempt to fix here: https://github.com/babel/babel/pull/12115
