### ISSUE TITLE
5.7.x breaks IIFE for async arrow functions

### ISSUE THREAD

**Issue by jRiest** [babel/babel#2027]
Not sure if this is a babel error or a regenerator error. Babel-core 5.7.x is throwing an error for IIFE's for async arrow functions if the parenthesis come right after the curly braces. Moving the parens outside works fine. However, both cases work in 5.6.x.

This only applies to async arrow functions as regular arrow functions work fine, and async normal functions also work fine.

This style does not work

```js
(async () => {
  await doThings();
}());
```

But moving the parens outside works fine

```js
(async () => {
  await doThings();
})();
```

**Comment by anba** [comment]
> This style does not work
> 
> (async () => {
>   await doThings();
> }());

That code should throw a syntax error,  but acorn/babylon accept a non-standard arrow function call syntax which allows `() => {}()`. Probably too many babel users already rely on that syntax extension, so aligning babel with the official spec can only happen when a new major version is released. :disappointed:

**Comment by sebmck** [comment]
@anba Ah really? Can you open another issue to track this, I agree that it's a serious issue that should be fixed in a major.

**Comment by jRiest** [comment]
@anba is that something special about async functions? Chrome Canary supports arrow functions natively and it runs this without complaint

```
(() => {
  return 42;
}())
```

**Comment by anba** [comment]
@jRiest No, it applies to all arrow functions. The v8 bug about this issue is tracked [here](https://code.google.com/p/v8/issues/detail?id=4211).  

SpiderMonkey (Firefox) and JavaScriptCore (WebKit) got this right:
```javascript
js> (() => { return 42; }())
typein:1:21 SyntaxError: missing ) in parenthetical:
typein:1:21 (() => { return 42; }())
typein:1:21 .....................^

>>> (() => { return 42; }())
Exception: SyntaxError: Unexpected token '('. Expected ')' to end a compound expression.
```
