### ISSUE TITLE
babylon ^5.7.2 failed to deal with flow typed async arrow function.

### ISSUE THREAD

**Issue by scv119** [babel/babel#2028]
```
async (foo: number) => {
}
```
Will raise exception.

**Comment by scv119** [comment]
looks like due this change https://github.com/babel/babel/commit/afacd627388dca3b04babd9b5a67d655c88d035d

**Comment by sebmck** [comment]
Consequence of the async arrow function parsing reusing the call expression parsing. Will need to implement a back fix to convert the nodes and throw a syntax error if there's no arrow.

**Comment by sebmck** [comment]
cc @bolinfest New release incoming in the next ~hour once I fix the final failing test.
