### ISSUE TITLE
babel-plugin test

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2029]
Exists here:
https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel-plugin/index.js#L90

But there's no command for it

**Comment by sebmck** [comment]
See #1950.

**Comment by hzoo** [comment]
I just did a separate test command and files for `babel-plugin-flow-comment` tests https://github.com/babel-plugins/babel-plugin-flow-comments/tree/master/test
