### ISSUE TITLE
Legacy block-level

### ISSUE THREAD

**Issue by monolithed** [babel/babel#2032]
#### Source
```js
{ function f(){} } f(); 
```

#### Output
```js
"use strict";

{
  var _f = function _f() {};
}f();
```
f is not defined.

https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=%7B%20function%20f()%7B%7D%20%7D%20f()%3B%20

https://bugs.ecmascript.org/show_bug.cgi?id=4428

**Comment by sebmck** [comment]
Those semantics only apply to scripts and thus do not apply to Babel which parses and transforms code under the assumption it's a module.
