### ISSUE TITLE
Parse flow comments

### ISSUE THREAD

**Issue by cassus** [babel/babel#2038]
Parse Flow comments ( http://flowtype.org/blog/2015/02/20/Flow-Comments.html )

To enable flow comment based type check support, eg. https://github.com/codemix/babel-plugin-typecheck/issues/11

**Comment by sebmck** [comment]
I don't think it's a good idea impose special syntactic requirements on comments and have them generate AST nodes since they aren't syntax, sorry.

**Comment by phpnode** [comment]
This could be implemented as a plugin relatively easily.

**Comment by sebmck** [comment]
Not really. Partial flow comments (eg. `function foo(bar/*: number */) {}`) would be particularly tricky.

**Comment by eventualbuddha** [comment]
It seems to me that a purely string-based pre-processor would be perfect for this kind of transform. I really ought to know this, but can plugins opt into that sort of transformation?

**Comment by sebmck** [comment]
@eventualbuddha Not currently, although that'd be possible with #1351.
