### ISSUE TITLE
Allow className and for in JSX element declaration

### ISSUE THREAD

**Issue by gajus** [babel/babel#2039]
> Since JSX is JavaScript, identifiers such as class and for are discouraged as XML attribute names. Instead, React DOM components expect DOM property names like className and htmlFor, respectively.

from: https://facebook.github.io/react/docs/jsx-in-depth.html

* Instead of `<div className='foo'>` we should be able to have `<div class='foo'>`.
* Instead of `<div htmlFor='bar'>` we should be able to have `<div foo='bar'>`.

It is true that `class` and `for` are [reserved keywords](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-keywords) in ECMAScript. However, JSX is not part of the ECMAScript. JSX is being transpiled to JavaScript. Just because JSX can be inlined with JavaScript, it should not be restricted by the same limitations. The transpiler should carry the weight of the incompatibilities.

**Comment by sebmck** [comment]
Have you tried either of those? [They both work without issue](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&playground=false&code=%3Cdiv%20class%3D'foo'%20%2F%3E%3B%0A%3Cdiv%20for%3D'bar'%20%2F%3E%3B&stage=0).

**Comment by gajus** [comment]
But they give warning. Whats the warning for?

**Comment by sebmck** [comment]
Babel doesn't output any warning for those?

**Comment by gajus** [comment]
I am using Babel and I am getting `Warning: Unknown DOM property class. Did you mean className?`.

**Comment by gajus** [comment]
To be precise, referring to [`babel-loader`](https://github.com/babel/babel-loader).

**Comment by gajus** [comment]
Ah, so its coming from React core.

**Comment by sebmck** [comment]
That's a React error and has nothing to do with Babel. Babel transforms those attribute names correctly. React uses `className` and `htmlFor` instead of `class` and `for` since using reserved names is fairly taboo so if you want to use React then you need to honour those rules.

**Comment by gajus** [comment]
@sebmck Thank you for prompt response.
