### ISSUE TITLE
babel CLI command inside NPM script fails silently

### ISSUE THREAD

**Issue by erykpiast** [babel/babel#2041]
I'm not sure if this issue should be reported here or in NPM channel, I'm doing it here after all. 

I encountered weird issue with Babel and NPM. `babel` command put in NPM script fails silently, but when running directly it works without errors. Example:

    babel -d dist/ src/

outputs

    src/file1.js -> dist/file1.js
    src/file2.js -> dist/file2.js

The same command inside NPM script

    "scripts": {
        "compile": "babel -d dist/ src/"
     }

runned by `npm run compile` outputs nothing except package name and command itself. 

What is more interesting here, on the same machine I can build different project through NPM, with exactly the same version of Babel. I suspected my code is broken,  but outside NPM script compilation goes smoothly. Another commands in this somehow broken project work perfectly. If you want to check:

 * here NPM & Babel don't want to work together: https://github.com/erykpiast/cyclejs-stream
 * here everything is working: https://github.com/cyclejs/cycle-core

I suppose it's because my project has less GitHub stars... No idea, to be honest, it was just working about month ago, I've not updated the machine since this time, just updated dependencies and `npm install` when I went back to the project.

Any help appreciated!

My environments description:
 * [linux](https://gist.github.com/erykpiast/d51d7658410f499f33cc#file-linux)
 * [windows](https://gist.github.com/erykpiast/d51d7658410f499f33cc#file-windows)

**Comment by jmm** [comment]
@erykpiast 
> I'm not sure if this issue should be reported here or in NPM channel, I'm doing it here after all.

Support requests should start in slack channel or stackoverflow, per the README:
>   For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Your "running it directly" snippet suggests you might be running a global install:

> babel -d dist/ src/

Are you sure you're running the local install in that case?

**Comment by jmm** [comment]
@erykpiast I just cloned `erykpiast/cyclejs-stream` and tried it and `npm run compile` works for me (Ubuntu@12.04, node@0.10.32, npm@2.12.0):

```
> babel -d dist/ src/

src/create-stream.js -> dist/create-stream.js
src/input-proxy.js -> dist/input-proxy.js
```

I would try blowing away your `node_modules` folder and reinstalling. Perhaps clear your npm caches as well.

**Comment by erykpiast** [comment]
Ok, somehow it started working after `npm cache clean && rm -rf ~/.npm && rm -rf node_modules && npm install`. I did it before too, so still don't have idea what was the issue.

Anyway, thank you for suggestions and your time!

**Comment by jmm** [comment]
@erykpiast You're welcome. Tough to say what the cause was unfortunately, but I'm glad you got it sorted out. If you haven't yet you might want to check out the slack community so you're familiar with it when you need support in the future.
