### ISSUE TITLE
babel/babel-core dependency mismatch

### ISSUE THREAD

**Issue by zpao** [babel/babel#2042]
In an attempt to work around https://github.com/babel/babel-eslint/issues/149, I tried to lock our `babel` dep at `~5.6.23`. We use `babel` instead of `babel-core` for some reason which might not be needed anymore but that's not the point. The problem though is that the dependency specification from `babel` on `babel-core` uses the `^5.6.23` range, which will install 5.6.23 <= n < 6.0.0. So babel 5.6.x will currently install babel-core 5.7, not actually allowing me to work around the issue. I would expect babel 5.6 to always use babel-core 5.6.

In the grand scheme of things this probably isn't a huge deal and it's solvable in user land, but it's one of those cases where versioning and dependencies are tricky. I don't necessarily know that using ~ ranges will be better but I wanted to raise the issue since I was surprised.

**Comment by sebmck** [comment]
There's not always a release of `babel` whenever there's one of `babel-core`. The `babel` CLI package just uses the public API for `babel-core` so it's not entirely unreasonable to use a `^` range.

**Comment by zpao** [comment]
Right, it's definitely a grey area in the whole versioning world. Even if the API stays the same, if output isn't, where does that fall on the semver scale?

> There's not always a release of babel whenever there's one of babel-core.

Sure, but I think that misses the point a little bit. They don't necessarily need to move in lockstep. It's more a question of what should happen when a minor version changes. The major version change is obvious. The patch version should be straightforward.

I don't have any horses in this race and like I said, my particular case is solvable. And it'll be fixed in 5.8 anyway. I'm totally fine with a wontfix here (just don't drunk tag me!) but I did want to bring it up.

**Comment by vdv73rus** [comment]
+
The same problem right now. I develop at webpack, so, I have only babel-loader and babel-eslint in my dependencies. But when I try to start my server…

    ~/ grunt serve
    Running "serve" task
    Running "open:dev" (open) task
    Running "webpack-dev-server:start" (webpack-dev-server) task
    webpack-dev-server on port 8000
    30% 1/3 build modulesFatal error: no templates directory - this is most likely the result of a broken `npm publish`. Please report to https://github.com/babel/babel/issues

And here is part of my '''package.json'''

    "babel-eslint": "^3.1.23",
    "babel-loader": "^5.3.2",

**Comment by sebmck** [comment]
@vdv73rus This is an unrelated issue. See #2045, #2044 and #2043.

**Comment by sebmck** [comment]
@zpao 

> Even if the API stays the same, if output isn't, where does that fall on the semver scale?

No idea, it's a tricky problem. If you consider the output public API then there's basically no changes that can be made that wont result in a backwards incompatibility. Every time I bump majors I run the test suite for each integration which uses a strict `assert.equal` to transform a class or something like that which obviously fails since the output changes _fairly_ often.

> I don't have any horses in this race and like I said, my particular case is solvable. And it'll be fixed in 5.8 anyway.

Released 5.8.0 a bit ago.

**Comment by vdv73rus** [comment]
@sebmck Oh, I'm sorry ) ¯\_(ツ)_/¯

**Comment by thejameskyle** [comment]
Is there anything we want to do about this?

**Comment by sebmck** [comment]
@thejameskyle Nope. As a part of 6.0 the versions are going to become even more disjointed. Hopefully renaming the `babel` package to `babel-cli` will help with this.
