### ISSUE TITLE
SystemJS Error

### ISSUE THREAD

**Issue by MrHalfman** [babel/babel#2051]
Hi everyone,

When using System.js modules I get this error in the console: "TypeError: Multiple anonymous System.register calls in the same module file." 
I checked all the generated files and there is only one System.register per file. So, where is my error?
In the generated code, my modules don't have names, unlike the examples given in the [Documentation](http://babeljs.io/docs/usage/modules/#system): is there a way to give them a name (Maybe it will fix my error?).

Thanks for your help!

**Comment by sebmck** [comment]
This doesn't appear to be a problem with Babel, and is instead a problem with your SystemJS environment. Please open an issue and seek assistance there. cc @guybedford

**Comment by guybedford** [comment]
@MrHalfman how are you loading your files? If you can share an example or post a SystemJS issue I can do my best to help.

**Comment by MrHalfman** [comment]
Thanks for your answer @sebmck.

@guybedford: I'm importing the modules using the ES6 import statement, then I do System.import("path/to/app.js"); (Named "build.js" in my configuration). 
Maybe it's not the good way to do this.

Here is the whole error :
```
uncaught exception: TypeError: Multiple anonymous System.register calls in the same module file.
	Evaluating http://[url]/static/js/build/objects/Planification.js
	Error loading http://[url]/static/js/build/objects/Planification.js from http://jdutriaux.orthonova.dtx:1337/static/js/build/pages/build.js
	Error loading http://[url]/static/js/build/objects/Planification.js
```

For more precision : the build.js file is a file transpiled with babel that imports classes I declare in other files and do some stuff with it.

Don't hesitate to tell me if you want further more information.
Thanks for your help.

**Comment by guybedford** [comment]
@MrHalfman can you confirm these modules are all transpiled as `system` format in Babel? Any chance you can share the repo?

**Comment by MrHalfman** [comment]
@guybedford: The code is under an NDA :unamused:, I can't share it but yes I transpile everything using Grunt and "module" is properly set to "system".

Maybe we can discuss a little bit more in private if it doesn't bother you.

**Comment by guybedford** [comment]
@MrHalfman if you're able to share a model test case that would help a lot here.

**Comment by MrHalfman** [comment]
@guybedford: Okay. I don't have much time right now but I will do this as soon as I can.
Thanks for your help.
