### ISSUE TITLE
spec.protoToAssign, __proto__ vs Object.setPrototypeOf

### ISSUE THREAD

**Issue by lukescott** [babel/babel#2053]
I'm currently targeting IE9+ in my project. I have to use `spec.protoToAssign` to get classes working. The `babelHelpers.inherits` helper uses `__proto__`, which requires the helpers to be transformed. So this forces me to either use inline helpers (a lot of duplication) or to use `babel.buildExternalHelpers`, which requires me to do a transform with a different set of options.

In the case of `babelHelpers.inherits`, and possibly even `spec.protoToAssign`, would it make sense to use Object.setPrototypeOf instead of `__proto__` and defer the functionality to a pollyfill?

**Comment by sebmck** [comment]
All environments that have `Object.setPrototypeOf` have `__proto__` but not all environments that have `__proto__` have `Object.setPrototypeOf`.

**Comment by sebmck** [comment]
Actually, I don't think that's the case for IE. Might be worth just changing it to:

```
Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
```

**Comment by lukescott** [comment]
I was thinking that `Object.setPrototypeOf` can be shimmed/shammed. It can be shimmed with `__proto__` when avaiable. It can be shammed w/ a defaults method.

**Comment by sebmck** [comment]
Yeah, that can totally be done now since if `Object.setPrototypeOf` is available then it just uses that and falls back to `__proto__`. All of the helpers have a trend of optimising for the common case so the user doesn't have to have a polyfill, iterable destructuring only requiring a polyfill for non-arrays is a good example.

**Comment by glued** [comment]
Not sure if this is related but `spec.protoToAssign` broke for me between 5.8.3 and 5.8.5, enabling it causes Browserify to error out **[Error: Parsing... Unexpected token** ?

**Comment by sebmck** [comment]
@glued It's definently related to the change in this issue. Can you post the full stack trace? Seems more like Browserify is using a broken parser.

**Comment by glued** [comment]
Possibly related to extending classes ?

```
class Polygon{
  constructor(width, height){
    this.height = height;
    this.width = width;
  }
}

export class Square extends Polygon{
  constructor(length) {
    super(length, length);
  }
}
```

```
Browserify Error 
/Users/glue/Desktop/babel-proto/public/js/geometry.js:11
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : ( = subClass, _defaults(superClass)); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ^
ParseError: Unexpected token
```

**Comment by sebmck** [comment]
Yeah it is. That helper is included when you inherit from a class. Can you open a new issue with the options that you're using to compile? Looks like it might be a transform issue, should be fairly straight forward to fix if it is.
