### ISSUE TITLE
auxiliaryComment not applied to _classCallCheck call in class constructor

### ISSUE THREAD

**Issue by phated** [babel/babel#2055]
As per https://github.com/nlf/lab-babel/pull/4#issuecomment-123840734

The auxiliaryComment before/after are working awesomely but they aren't applied to the `_classCallCheck` method call in a class constructor.  If they were applied to that line, lab would be able to report coverage correctly.

Thanks!

EDIT by hzoo: also https://github.com/babel/babel/issues/4450 + `_possibleConstructorReturn`

**Comment by sebmck** [comment]
I just thought of a way that will automatically wrap generated nodes in the auxiliary comment. It'll mean that nothing has to be individually special cased but it may produce more verbose code. Do you think it'll be worth it?

**Comment by jedireza** [comment]
> I just thought of a way that will automatically wrap generated nodes in the auxiliary comment.

Sounds like a win for most code coverage tools.

**Comment by phated** [comment]
@sebmck does it make it more verbose in all cases or just when auxiliary comments are in use?

**Comment by sebmck** [comment]
Just when auxiliary comments are in use. There may be scenarios where user nodes are converted to generated nodes but that shouldn't be too much of a problem.

**Comment by phated** [comment]
I'm :+1: for it then, I don't think anyone would mind the size of code generated for testing and getting closer to correct coverage makes it worth it

**Comment by sebmck** [comment]
Just realised that the technique that I was thinking of will be a breaking change. Istanbul has no "ignore start" and 'ignore end" equivalent which will mean that the current technique might have to stick around :disappointed:

**Comment by phated** [comment]
Maybe they can add it.  I'll open an issue over there

**Comment by phated** [comment]
@sebmck if you have anything to add to https://github.com/gotwarlost/istanbul/issues/413, it would be helpful.  I'm not familiar enough with AST stuff to discuss it with the author

**Comment by hzoo** [comment]
We're using https://github.com/istanbuljs/babel-plugin-istanbul in babel for coverage, will reopen if anyone needs this still

**Comment by jedireza** [comment]
Yep we'd like this for hapijs/lab.

**Comment by loganfsmyth** [comment]
Could you expand on what specifically your usecase is? The problem at the moment is there really isn't a great heuristic to place these comments. In a perfect world I'd love to see this feature removed entirely. "ignore next" specifically is super tough. If we do want to do this, I'd much prefer a general "start" and "end" comment that wraps tokens with no location defined in the original code.

**Comment by jedireza** [comment]
@loganfsmyth the quick summary is that not all non-user generated code is wrapped in before and after aux comments, which causes incorrect coverage results.

More details are in an old issue I created for this: https://github.com/babel/babel/issues/4450

**Comment by jetstarmedia** [comment]
why updates?

**Comment by loganfsmyth** [comment]
My comment above unfortunately still applies. Support for `auxiliaryComment*` flags is extremely limited. I think if you need reliable coverage reporting via Babel, using a plugin built to actually handle it consistently, like https://github.com/istanbuljs/babel-plugin-istanbul, is pretty necessary, otherwise you're basically just rolling the dice as to whether or not these comments end up in reasonable places.
