### ISSUE TITLE
Docco Plugin Request

### ISSUE THREAD

**Issue by TheJaredWilcurt** [babel/babel#2056]
# What is Docco

Docco is a Java Script documentation generator. It allows you to write all of your comments in your JS files as MarkDown and then have it processed to generate an easy to read, annotated source file.

A good example of Docco in use is the [annotated source code](http://underscorejs.org/docs/underscore.html) for Underscore.

The downside is that when Docco was created, they didn't want to have to write a whole new processing language to be able to interpret the comments as markdown and produce the appropriate HTML file. So instead they just used CoffeeScript.

Even though Docco was originally created for JavaScript, and has a since been ported to a dozen other languages, the one language it still doesn't work with is JavaScript itself.

* * *

# My Request

Can someone produce a plugin that allows you to take a plain JavaScript file, where the comments in the file are processed like they are MarkDown and then placed in an HTML file with the accompanying code to the right of the comment (as seen in the link above).

**Comment by sebmck** [comment]
Sorry but this is not an appropriate place to request new plugins. As the README says:

> The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

I'm closing this as it's neither a feature request nor a bug report but a request for someone to write a userland bit of code for you. Thanks :blush:

**Comment by TheJaredWilcurt** [comment]
Thanks for deleting this and not pointing me in the right direction. Super helpful.

**Comment by sebmck** [comment]
@TheJaredWilcurt Try reading the README where it points to several sources where you can get assistance.

**Comment by TheJaredWilcurt** [comment]
No. It doesn't. It points to a shitty, barely functional, exclusive, proprietary chat app that wants an email address I'm not going to share with it (just fucking use IRC, KiwiIRC is user friendly enough). Or I can go to stackoverflow, a place I associate to asking HOW to do something, not requesting something be made.

Meanwhile that same readme, explicitly says to use the Issues page to request features, which is what I was doing. If you don't consider plugin support to be a feature. Then put a link to where plugin support SHOULD go. Maybe a forum or subreddit or something for the community to use for discussions. This is just basic community management.

If someone, follows your instructions and puts content where you tell them to and decide you don't want that content there. Find the correct place for it, or make the correct place for it, THEN LINK THEM TO IT. Don't give a fucking snarky RTFM response. This is not how you treat users, or third party developers.

**Comment by sebmck** [comment]
As I said before, this isn't a core feature request, you're requesting someone to write you a userland module. The reason I didn't recommend any other way is because there isn't really an avenue for you to arbitrarily request someone to write you some code for free. You aren't even asking assistance in writing it yourself, you're blatantly asking for someone else to do all the work for you.

You're requesting someone commit a large portion of their free time to write you some free code, and then you're getting angry when I say that this isn't the right place to task, get a grip man. If you don't want to spend literally a minute signing up for Slack to ask the over 800 people for assistance then you clearly don't respect anybody else's time.

As any OSS contributor will tell you, this is a passion of love and the language and tone you just used are extremely inappropriate and completely out of line for any public community interaction. Come back with some manners and patience and maybe someone will assist you.

**Comment by jmm** [comment]
@TheJaredWilcurt Regarding the slack, perhaps those issues don't have to stand in the way of you utilizing it. I'm not sure what you mean by exclusive (my understanding is that if you complete the sign-up form you'll get access). But on the other points, GitHub and most forums are also proprietary platforms that require an email address to participate. (In my admittedly limited experience slack is pretty functional, and a nicer user experience than I've had with IRC, although I certainly sympathize with the proprietary vs. open argument.) I know you can't reply here, just wanted to note those things in case you may want to reconsider trying the slack.

@sebmck I've been wondering recently if perhaps an issues-only repo for general discussion about babel might make sense? Basically meant for anything & everything that people may want to discuss about it, like all the stuff that gets posted here that shouldn't, or general stuff that's fair game on slack (but perhaps not everything that would go in `#development`, for example). I know a lot of that stuff would still get posted here, but it might be a useful venue for discussions in general, and you could attempt to direct people to it from the `README`. The idea being that there's no expectation that you (or anyone else who doesn't want to) ever even looks at that issue tracker -- just totally opt-in for anyone who chooses to read it (but not totally opt-in for people posting stuff here that doesn't fit). Not sure if you feel that would detract from the utility of the slack or something. I hope you don't mind me suggesting this here and I understand if you choose not to reply here.

**Comment by eventualbuddha** [comment]
@jmm what you're describing sounds to me like a mailing list. Do you think that'd fit the need you're seeing?

**Comment by jmm** [comment]
@eventualbuddha I just tend to find mailing lists really annoying, and it's another thing someone has to setup and administer. For this scenario I personally would much prefer the UX of the GitHub issue tracker to a mailing list. That's just in general, but making it a GitHub issue tracker would make it easy to post code snippets, reference issues on GitHub repos, etc. And it gives you a lot of utility for free (as in beer and effort) -- just create a repo and anyone who has or is willing to create a GitHub account is good to go. People that want to can somewhat use it like a mailing list by enabling email notifications (but if I'm not mistaken that's all watched repos or none).

**Comment by thejameskyle** [comment]
As an alternative to a mailing list, I was thinking about setting up http://www.discourse.org

**Comment by jmm** [comment]
@thejameskyle In my limited experience with discourse (I've used it a little at http://discuss.atom.io/) I've found that a bit annoying too, although it's probably better than a mailing list. For instance, I just went there to copy the link, and, ironically, saw this thread:

[Join us on Slack](http://discuss.atom.io/t/join-us-on-slack/16638)

...After waiting an inordinate amount of time for a blank page with a spinning icon to be replaced with content.

 (And again, obviously something someone has to setup, host, administer.)

**Comment by RReverser** [comment]
@thejameskyle In fact, I like the idea of using Discourse as it seems to be the appropriate tool for such kind of questions and discussions.
