### ISSUE TITLE
Use babel-runtime when compiling from CLI

### ISSUE THREAD

**Issue by halt-hammerzeit** [babel/babel#2060]
I wrote a javascript library which is being transpiled with Babel to output ES5-compatilbe modules:

```sh
babel ./source --out-dir ./babel-transpiled-modules --source-maps inline
```

But it says "Symbol is not defined" in old browsers.
From what I've just read, if you don't want to include Polyfill in your library (which you shouldn't) you can still use a module called "babel-runtime" and everything will work in old browsers.
How can I tell `babel` to use the runtime?
Is there a command line argument for that purpose?

**Comment by sebmck** [comment]
```sh
$ babel ./source --optional runtime --out-dir ./babel-transpiled-modules --source-maps inline
```

See the [runtime docs](https://babeljs.io/docs/usage/runtime/#usage) for more info. Also in the future please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:

**Comment by halt-hammerzeit** [comment]
Oh, thanks.
This options is absent from the Usage docs so I didn't know it existed
https://babeljs.io/docs/usage/cli/
