### ISSUE TITLE
_createClass and_classCallCheck defined for each module

### ISSUE THREAD

**Issue by jbe456** [babel/babel#2063]
Is there an option to define once and for all the methods `_createClass` and `_classCallCheck`? It is currently redefined in each module.

We have several hundred modules thus defining it once would help reducing the size ... I'm already adding the `browser-polyfill.js` file. I would not mind adding a second one `babel-runtime.js` for that purpose.

**Comment by sebmck** [comment]
Yup, there sure is. There's two ways. One is via [external helpers](http://babeljs.io/docs/usage/external-helpers) which makes all the little helper functions reference a global variable and the other is the [runtime](https://babeljs.io/docs/usage/runtime/) which automatically imports the `babel-runtime` package that contains the helpers and uses them there so they're only referenced once.

If you run into anymore trouble feel free to check out our <a href="https://babel-slack.herokuapp.com">Slack community</a> . Thanks! :blush:
