### ISSUE TITLE
Printer: retainLines generates invalid code

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#2064]
```js
function foo() {
  return (
    1 && 2
  ) || 3;
}
```

Transforms to:

```js
function foo(){
return 
1 && 2 || 
3;}
```

with a broken semantics since returns `undefined`.

**Comment by sebmck** [comment]
Just a thought of a better way to handle this and clean up some other paren generation code for terminatorless nodes like that one.

**Comment by sebmck** [comment]
Woah, much nicer now, works like a charm. Will need to confirm that it doesn't break anything before pushing out a new version though.

**Comment by DmitrySoshnikov** [comment]
Perfect, thanks!
