### ISSUE TITLE
async/await + ...args = error

### ISSUE THREAD

**Issue by vslinko** [babel/babel#2070]
Found an error:

[Example 1](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%0Afunction%20safeAsync(fn)%20%7B%0A%20%20return%20async%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20await%20fn(...args)%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20handleError(err)%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Aasync%20function%20a%20(q)%20%7B%0A%20%20console.log(q)%0A%7D%0A%0Aasync%20function%20m()%20%7B%0A%20%20await%20safeAsync(a)(123)%0A%7D%0A%0Am()%0A)
```js
function safeAsync(fn) {
  return async (...args) => {
    try {
      await fn(...args)
    } catch (err) {
      handleError(err)
    }
  }
}

async function a(q) {
  console.log(q)
}

async function m() {
  await safeAsync(a)(123)
}

// should print 123, but prints [Function a]
m()
```

But if I add `console.log(args)`, it's working:

[Example 2](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%0Afunction%20safeAsync(fn)%20%7B%0A%20%20return%20async%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20console.log(args)%0A%20%20%20%20%20%20await%20fn(...args)%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20handleError(err)%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Aasync%20function%20a%20(q)%20%7B%0A%20%20console.log(q)%0A%7D%0A%0Aasync%20function%20m()%20%7B%0A%20%20await%20safeAsync(a)(123)%0A%7D%0A%0Am()%0A)

```js

function safeAsync(fn) {
  return async (...args) => {
    try {
      console.log(args)
      await fn(...args)
    } catch (err) {
      handleError(err)
    }
  }
}

async function a (q) {
  console.log(q)
}

async function m() {
  await safeAsync(a)(123)
}


// prints [123] 123 as expected
m()
```

**Comment by sebmck** [comment]
Duplicate of #1882.
