### ISSUE TITLE
babel-plugin init should include basic test setup

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2074]
This seems perfect: https://github.com/babel-plugins/babel-plugin-flow-comments/tree/master/test

Idk if you want to move this stuff into a module: https://github.com/babel-plugins/babel-plugin-flow-comments/blob/master/test/index.js

**Comment by sebmck** [comment]
Dupe of #2029 and #1950?

**Comment by thejameskyle** [comment]
I mean the files for it

**Comment by thejameskyle** [comment]
blarg, I guess they are the same thing
