### ISSUE TITLE
Variable declaration vanishes when adding predecessor sibling.

### ISSUE THREAD

**Issue by izaakschroeder** [babel/babel#2075]
Playing around with a code coverage tool for babel [here](https://github.com/izaakschroeder/adana).

The following block of code:

```javascript
function Statement(node, parent, scope, file) {
	if (!ignore(node)) {
		return [
			increment({ node: node, type: 'statement', file: file }),
			node
		];
	}
	return node;
}
```

Seems to destroy an ephemeral variable generated for this block of code:

```javascript
var z = {
	exit(w) {
		w.x.y(...x(file));
	}
}
```

Without the babel plugin the result is:

```javascript
var _node$x;
(_node$x = node.x).y.apply(_node$x, _toConsumableArray(x(file)));
```

With the plugin the result is:

```javascript
++_covorvdl24dd8fflxr[1]
++_covorvdl24dd8fflxr[2]
(_node$x = node.x).y.apply(_node$x, _toConsumableArray(x(file)));
```

As far as I am aware my transformation should simply replace the statement:

```javascript
w.x.y(...x(file));
```

with:

```javascript
++_covorvdl24dd8fflxr[1]
++_covorvdl24dd8fflxr[2]
w.x.y(...x(file));
```

I have also tried using `this.insertBefore` to no avail. `this.insertAfter` works as expected, however.

You should be able to reproduce this with:

```sh
git clone https://github.com/izaakschroeder/adana
cd adana
npm install
babel --plugins "."  test/fixtures/regression-1.fixture.js
```

Poking around in the internal scope handler:

```javascript
declar.declarations.push(t.variableDeclarator(opts.id, opts.init));
    var o = path.node.body;
    Object.freeze(o);
    console.log(o) // <-- everything looks good here, variable declaration IS present
    Object.defineProperty(path.node, 'body', {
      set: function(x) {

      },
      get: function() { return o; }
    })
```

Yet the output still is not present. Kind of at a loss right now. Thanks for any help :smile:

**Comment by sebmck** [comment]
I notice that:

```javascript
++_covorvdl24dd8fflxr[1]
++_covorvdl24dd8fflxr[2]
```

don't have semicolons after them. Are you wrapping them in an `ExpressionStatement` correctly?

**Comment by izaakschroeder** [comment]
Looking into this now. Might be what's causing it. Thanks for the fast reply!

**Comment by izaakschroeder** [comment]
Yup that was precisely it. Sorry for being an idiot. :frowning: Thanks again for your insight. It might be handy (if even possible?) to detect this kind of type error. Much :+1:

**Comment by sebmck** [comment]
No problem! Happy to help :blush: There's the issue #1858 that's tracking validation of nodes. Also feel free to check out our <a href="https://babel-slack.herokuapp.com">Slack community</a> if you want more realtime help, thanks! :smile:
