### ISSUE TITLE
Unable to set sourceRoot to value and moduleRoot to empty string.

### ISSUE THREAD

**Issue by mmoss** [babel/babel#2079]
The condition in [`_default.js`](https://github.com/babel/babel/blob/91fb64eaf53c67a7ed7605aab71f8dcaa4d39ae2/packages/babel/src/transformation/modules/_default.js#L343 ) appears to prevent being able to set moduleRoot to an empty string, while setting sourceRoot to an actual value. moduleRoot is always overridden since the condition does a simple falsey check--there doesn't appear any way to set it to an empty string to get source maps loading properly.

My use case: Transcompiling `src/js/module.js` to `dist/js/module.js`, serving files from `dist/`, and stripping the src/ prefix so bundles can be referenced as just `js/module` (or better, just `module`)

**Comment by jmm** [comment]
@mmoss I'll look into this when I get the chance. So in this scenario `moduleRoot` has already defaulted to the value of `sourceRoot` by the time the line you highlighted runs? What is your `modules` option value? Thanks!

**Comment by mmoss** [comment]
Thanks @sebmck! This was exactly what I was hoping for (but didn't get a chance to provide a good test case before you got to it already). Much appreciated!
