### ISSUE TITLE
Using async functions with Angular

### ISSUE THREAD

**Issue by Swiip** [babel/babel#2081]
I'm a huge fan of ES6+ and Babel, especially the async functions. But I use Angular and the promise implementation is quite specific. A quick overview of the problem is here: https://github.com/angular/angular.js/issues/11370#issuecomment-84005912

I imagined it could be as simple as having regenerator plugged with `$q` in place of the standard `Promise`. I'm the first impressed it actually worked! (I give the code bellow)

At this point, it works for me, but it's an ugly hack with the whole code of regenerator copied in my sources. Do you have any hint for me to make it a reusable solution, a plugin or something? I'm ready to invest a bit a publish something.

regenerator.js:
```javascript
  function regenerator($q) {
    var _Symbol = require("babel-runtime/core-js/symbol")["default"];
    var _Symbol$iterator = require("babel-runtime/core-js/symbol/iterator")["default"];
    var _Object$create = require("babel-runtime/core-js/object/create")["default"];
    $q.resolve = $q.when; // Only compatibility hack
    var _Promise = $q;

    !(function (global) {
// complete standard regenerator source code
    
  regenerator.$inject = [ '$q' ];
  angular.module('regenerator', []).run(regenerator);
```

Usage example:
```javascript
export class BreweryService {
  constructor($http) {
    Object.assign(this, { $http, breweryHost: '/brewerydb' });
  }

  async getList() {
    let result = await this.$http.get(`${this.breweryHost}/breweries`);
    return result.data;
  }
}
```

It could allow the whole Angular community to discover the magic of async functions, it would be great!

**Comment by benjamingr** [comment]
As an alternative, you can decorate $q to use the standard promise with `then` also calling `$evalAsync`. 

You might want to open an issue on regenerator for a pluggable promise implementation (although I think it just looks at the global IIRC).

**Comment by sebmck** [comment]
Async functions return ES6 promises, it doesn't really make any sense to allow anything else.

**Comment by Swiip** [comment]
Thanks for the hints, I'll try other approaches. I know it's not standard but it's how Angular 1 is and I just try to get the best of both worlds.

**Comment by stefanpenner** [comment]
> You might want to open an issue on regenerator for a pluggable promise implementation (although I think it just looks at the global IIRC).

it just looks for window.Promise

**Comment by Swiip** [comment]
I'm so ashamed, it actually work whithout any hack. I think I had a different bug and was confirmed in my error by the issue in Angular I linked.

Still a bit strange because, you know... "It should not work"

**Comment by darkbaby123** [comment]
I tried to set `window.Promise` to `$q` and it works. I tested to transform one function without any problem. But it seems a very hack way.

I thought many framework have the same issue to use async/await because they all don't use `window.Promise`. Angular uses `$q` and Ember use `Ember.RSVP.Promise` to do some extra things (integrate with their run loop). Is there a offical way to solve it?

**Comment by JianJiao** [comment]
@darkbaby123 I like your approach. Just curious, have you encountered any problems so far using this approach?

**Comment by westy92** [comment]
@darkbaby123 I like your approach too. I'd like to know the answer to @JianJiao's question as well--have you had any issues with this solution?
