### ISSUE TITLE
babel not compiling imported modules

### ISSUE THREAD

**Issue by Aweary** [babel/babel#2085]
Hello wonderful babel team!

I've run into an issue where babel doesn't seem to work with modules, and I'm hoping you can help me.
I setup a test case with the following structure:

```js
- babel-test
  - node_modules
  - foo.js
  - bar.js

```
within `foo.js` I have:

```js
  export default function(data) {
    console.log(data)
  }
```

and within `bar.js` I have:

```js
  import foo from './foo.js'
  foo('Hello, world!')

```

Then I run `babel bar.js > bundle.js` and use `node bundle`, to which I receive the error:

```js
/Users/myuser/.dev/babel-test/foo.js:1
(function (exports, require, module, __filename, __dirname) { export default f
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/myuser/.dev/babel-test/bundle.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Is this expected behavior? Does babel not compile imported ES6 modules? I've had some other folks try similar things on other projects that use this pattern, and they haven't had this problem, so I'm questioning why this may be happening.

**Comment by sebmck** [comment]
Hey @Aweary,

Babel's not a module bundler so the only file that is being compiled is `bar.js` and `foo.js` isn't "bundled". When you execute `bundle.js` it just tries to execute `foo.js` which isn't compiled. I'd suggest having a directory structure like:

```
- babel-test
  - node_modules
  - src
    - foo.js
    - bar.js
```

And running:

```sh
$ babel src --out-dir lib
$ node lib/bar.js
```

You can checkout the [README](https://github.com/babel/babel#readme) for some links on places to get further help if you need any:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

Thanks! :blush:

**Comment by Aweary** [comment]
Hey @sembck, thats what I thought! I knew I wasn't crazy. You can see from the referenced issue that I was the only one having this issue in that project, so I wanted a sanity check here. 

Thanks again.

**Comment by Wang-Kai** [comment]
Thank you every much , i have another question .

if i want to compile bar.js and foo.js into one file (eg: index.js ) , what should i do ?

**Comment by xtuc** [comment]
Babel will compile the files independently, unlike a bundler which will merge them to produce a single file (Webpack, Rollup etc)
