### ISSUE TITLE
Arrow function notation in decorators are broken

### ISSUE THREAD

**Issue by qimingweng** [babel/babel#2086]
Compare the output of these two to show the difference.

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%40decorate((arg)%20%3D%3E%20null)%0Aclass%20Example1%20%7B%0A%7D%0A%0A%40decorate(arg%20%3D%3E%20null)%0Aclass%20Example2%20%7B%0A%7D

```js
@decorate((arg) => null)
class Example1 {
}

@decorate(arg => null)
class Example2 {
}
```

**Comment by loganfsmyth** [comment]
@qimingweng Thanks for the report! I wish force-pushing didn't make the referenced issues full of extra info :(

**Comment by karudo** [comment]
Why you didnt release update with this fix?

**Comment by dubert** [comment]
:+1:

**Comment by pixeldrew** [comment]
Still broken with this example:

@decorate(() => ({
  
}))
class Example3 {
}

**Comment by jmm** [comment]
@pixeldrew Broken where -- did you build from `master`?

**Comment by pixeldrew** [comment]
yep, built from master.

**Comment by alinz** [comment]
It is still happening.

**Comment by loganfsmyth** [comment]
This fix has landed on master, it has not been published to NPM yet.

**Comment by alinz** [comment]
I think all of `react-native` projects will be effected if they are using decorators. Is there any temporary fix I can apply?

@loganfsmyth Do you know when it's going to be available on NPM?

Thanks

**Comment by pixeldrew** [comment]
I tested from master and i'm still getting that error.

**Comment by pixeldrew** [comment]
Note the notation (params are required for no function params and around returned literals): 
@decorate(()=> ({woot:'blah'}))
class Test2 {

}

**Comment by jmm** [comment]
@pixeldrew It looks like it's working for me when built from `master` (64e7164b558aeec289760445f1d4e853e81f4fdd). You're sure you're referencing the local build correctly and everything (e.g. have it `npm link`'ed or something)?

Also, please mark up code in your posts.

**Comment by pixeldrew** [comment]
ah, apologies. Was using the bootstrapped version inside of node_modules instead of node ./packages/babel-cli/bin/babel.js 

Yep, this works. Can we get a new version released?

**Comment by jmm** [comment]
Ok. When a release gets cut will be up to **sebmck**.

**Comment by pixeldrew** [comment]
Any idea on when this crept into the build? I was able to build my project correctly using 5.6.14. The only thing I can do to stop this from happening is to add babel-core to my project at that revision.
