### ISSUE TITLE
Decorator with Object Literal Expression Arrow Function parameter dropped from output

### ISSUE THREAD

**Issue by OscarMarshall** [babel/babel#2093]
It appears that Babel ignores decorators if they have a parameter that is an expression arrow function that returns an object literal.

The code:

```
@dec(a => ({a}))
class c {}
```

Produces:

```
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var c = function c() {
  _classCallCheck(this, c);
};
```

The decorator is completely forgotten.

On the other hand, if you explicitly return the object, the decorator reappears.

```
@dec(a => {return {a};})
class c {}
```

->

```
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var c = (function () {
  function c() {
    _classCallCheck(this, _c);
  }

  var _c = c;
  c = dec(function (a) {
    return { a: a };
  })(c) || c;
  return c;
})();
```

**Comment by jmm** [comment]
Thanks for the report! This appears to be the same issue as #2086 and #2088 and resolved by the commits referenced there.

**Comment by OscarMarshall** [comment]
Cool! I need to remember to search closed commits next time.

**Comment by jmm** [comment]
Yeah it's always great if you're able to recognize your problem in an existing issue, and things often move quickly here.
