### ISSUE TITLE
Arrow fun expr in decorator parameters doesn't work

### ISSUE THREAD

**Issue by elierotenberg** [babel/babel#2094]
Hey, sorry if this is a dupe, I looked for it and couldn't find.

Here's [the simplest example](http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=function%20decorate()%20%7B%7D%0Aconst%20a%20%3D%20()%20%3D%3E%20%7B%7D%3B%0A%0A%40decorate(a)%0Aclass%20Works%20%7B%7D%0A%0A%40decorate(()%20%3D%3E%20%7B%7D)%0Aclass%20DoesntWork%20%7B%7D%20%2F%2F%20%3F%3F%3F%20generated%20code%0A%0A) I could pull out to reprod a bug crippling my day:
```js
function decorate() {}
const a = () => {};

@decorate(a)
class Works {}

@decorate(() => {})
class DoesntWork {} // ???
```

It appears that passing arrow function expression as a decorator parameter messes the transpilation, as the decorator is purely and simply absent from the transpiled code for the second class. However, assigning the arrow fun expression to a variable and then passing it as a decorator parameter works.

Note that "some time ago" (maybe a few minors ago) it used to work perfectly fine. Is this a bug?

Thanks.

**Comment by zloirock** [comment]
#2086 #2088 #2090 #2093
