### ISSUE TITLE
Spread operator with generators in array

### ISSUE THREAD

**Issue by zerkms** [babel/babel#2100]
An example is taken from https://kangax.github.io/compat-table/es6/#spread_(...)_operator_with_generator_instances,_in_arrays

    var iterable = (function*(){ yield "b"; yield "c"; yield "d"; }());
    let r = ["a", ...iterable, "e"][3] === "d";
    console.log(r)

Expected to be `true`, returns `false`.

**Comment by sebmck** [comment]
[I can't reproduce this](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20iterable%20%3D%20(function*()%7B%20yield%20%22b%22%3B%20yield%20%22c%22%3B%20yield%20%22d%22%3B%20%7D())%3B%0Alet%20r%20%3D%20%5B%22a%22%2C%20...iterable%2C%20%22e%22%5D%5B3%5D%20%3D%3D%3D%20%22d%22%3B%0Aconsole.log(r)). Please make sure that "Loose mode" is turned off if you're using the REPL.

**Comment by zerkms** [comment]
Oh my god, the second fail in half an hour, sorry
