### ISSUE TITLE
Trying to install a specific version: `No name provided in package.json`

### ISSUE THREAD

**Issue by eTorAken** [babel/babel#2104]
I would like to know if that's possible to install a specific version of babel using npm. That's what I tried:
```sh
$ npm install git://github.com/babel/babel.git#v5.8.12
npm ERR! addLocal Could not install C:\Users\CLMENT~1\AppData\Local\Temp\npm-7516-254e9cdc\git-cache-ea5f49881c21\770e89d5378cc3a80ead911afa6b710ebacbe9d8
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git://github.com/babel/babel.git#v5.8.12"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp\www\npm-debug.log
```

Here is what might causes me troubles:
1) There is no `name` field in the root package.json
2) There is a `private: true` field in the root package.json
3) The package I'm trying to access is located in https://github.com/babel/babel/tree/master/packages/babel (not https://github.com/babel/babel) but I don't know here how to install a child directory from a repo.

Any help is welcome.

**Comment by sebmck** [comment]
Installing via npm isn't possible. This repo contains multiple packages and the compiled source isn't included. 5.8.12 is available from npm this shouldn't be necessary.

**Comment by eTorAken** [comment]
Thanks for making this to be clear, I was trying to install it from `master` branch too or from a specific commit. My example might not be that relevant tho

**Comment by jmm** [comment]
@eTorAken You can clone the repo, build it, and use `npm link` or whatever you want.

**Comment by eTorAken** [comment]
That's what I was looking for, thank you @jmm

**Comment by jmm** [comment]
@eTorAken No problem! See `CONTRIBUTING` for instructions if you haven't built it before (recently).
