### ISSUE TITLE
I use `runtime`, but get Promise is not defined

### ISSUE THREAD

**Issue by ustccjw** [babel/babel#2111]
So doubt about runtime:

I use .babalrc (webpack complile):

    {
        "stage": 0,
         "optional": ["runtime"]
    }

such as `Promise / startswith` (need polyfill) , webpack will load polyfill from `core-js` ? But i get `Promise is not defined` when the browser do not support `native Promise`.

**Comment by ustccjw** [comment]
I only instead of using `es6-promise` as follow

    import promise from 'babel-runtime/core-js/promise'
    import {Promise} from 'es6-promise'
    promise.default = Promise

**Comment by ustccjw** [comment]
https://github.com/babel/babel/issues/1739

**Comment by ustccjw** [comment]
aha, i think `import 'babel-core/polyfill'` is required, doc is not very clear.

**Comment by wmadden** [comment]
Isn't the idea with `runtime` that you don't need the "globally polluting polyfill" (quoting the docs)?

**Comment by ustccjw** [comment]
@wmadden if you have the same problem, you can try 'import 'babel-core/polyfill''. You can also see https://github.com/babel/babel/issues/1739. I do not understand clearly...

**Comment by zloirock** [comment]
@ustccjw `babel-core/polyfill` not required for `runtime`.

**Comment by wmadden** [comment]
@ustccjw I think I found the root of my problem: my project includes legacy CoffeeScript code that's not processed by Babel, so the `runtime` transformer has no effect on them.

@zloirock you are correct, my mistake.

For what it's worth, I'm finding that it's very easy to shoot yourself in the foot with webpack since it's so flexible.

**Comment by ustccjw** [comment]
@wmadden May be i encounter some pit... I will check myself.

**Comment by oguzbilgic** [comment]
I had to `import 'babel-core/polyfill'`. Adding `runtime` options wasn't suffice.

**Comment by loganfsmyth** [comment]
@oguzbilgic Were all of your files being processed by Babel? For `runtime` to work, everything that accesses ES6 functions needs to be transformed.

**Comment by oguzbilgic** [comment]
@loganfsmyth yeah, I think so. this basically processes everything with js and jsx extensions.

```js
     {
        test: /\.jsx?$/,
        loader: 'babel',
        include: path.join(__dirname, 'src')
      }
```
