### ISSUE TITLE
Fetch API feature request

### ISSUE THREAD

**Issue by camsong** [babel/babel#2113]
The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) provides an interface for fetching resources, would be a replacement of  XMLHttpRequest. Is there any plan to support that?

**Comment by keithamus** [comment]
Hey @camsong! `fetch` isn't part of EcmaScript, its part of the web platform. I'm not sure Babel really supports polyfiling the web platform/DOM. So you'd need to pull in a manual polypill. I've used https://github.com/github/fetch which is really nice. https://github.com/matthew-andrews/isomorphic-fetch works on the server side too.

**Comment by sebmck** [comment]
@keithamus is completely correct. Babel just deals with syntax. If you want a polyfill then feel free to use [core-js](https://github.com/zloirock/core-js) and [github/fetch](https://github.com/github/fetch).
