### ISSUE TITLE
Re-rexporting a module compiled to `export.default = ...`

### ISSUE THREAD

**Issue by alexlafroscia** [babel/babel#2117]
I've been doing some IE debugging and noticed a show-stopper that seems to fall into Babel's territory.  I keep getting the following issue:

> Expected Identifier

Which traces back to the following code:

```javascript
define('qualaris-mantra/components/ember-wormhole', ['exports', 'ember-wormhole/components/ember-wormhole'], function (exports, ember_wormhole) {

	'use strict';

	exports.default = ember_wormhole.default; // Error points to this line

});
```

I went and looked up the `ember-wormhole` code that corresponds to this module, and it can be found [here](https://github.com/yapplabs/ember-wormhole/blob/master/app/components/ember-wormhole.js#L1).  In case you don't feel like following the link, it's just re-exporting another module.

Is this an issue on Babel's end? To me, it seems like the problem is that Babel translates the re-export to

```javascript
exports.default = ember_wormhole.default;
```

instead of

```javascript
exports['default'] = ember_wormhole['default'];
```

I looked around at all the other modules and they all seem to use the `exports['default']` syntax.  It's only an issue with IE, and all the other modules seem to be OK.

**Comment by jmm** [comment]
That code is output from babel? What's the input? What babel version?

**Comment by alexlafroscia** [comment]
The first code snippet is the Babel output.  The code that I linked to [here](https://github.com/yapplabs/ember-wormhole/blob/master/app/components/ember-wormhole.js#L1) is the input.  The babel version is the latest, I just did a fresh `npm install`.

**Comment by jmm** [comment]
Ok, and how are you running babel?

**Comment by alexlafroscia** [comment]
This is an Ember CLI app, so it's being run through the `ember-cli-babel` package which uses `broccoli-babel-transpiler`, as far as I know.

**Comment by jmm** [comment]
That's a lot of layers. It's going to be hard to do anything about it here without a reproduction with just babel. There may be an issue in one of those wrappers.

**Comment by alexlafroscia** [comment]
Alright, no problem. I'll look into making a repo to isolate the problem.

**Comment by jmm** [comment]
Awesome, thank you. That should help narrow down where the problem lies.

**Comment by loganfsmyth** [comment]
Sounds like something somewhere is blacklisting the `es3` namespaced transformers: http://babeljs.io/docs/advanced/transformers/es3/member-expression-literals/ but +1 for a reproducible case.

**Comment by alexlafroscia** [comment]
Alright, so I tried to reproduce with _just_ Babel and was unable to, it all seems to work correctly. This prompted me to read more about `ember-cli-babel` and it turns out that it uses a custom module transformation, so I think it makes more sense to open this issue over there instead.

**Comment by jmm** [comment]
Yeah, without a reproduction with just babel it's not actionable here. If you think the custom module formatter in the other project is the culprit, raising it over there sounds like the way to go.

**Comment by alexlafroscia** [comment]
Alright, well thanks for the help!

**Comment by stefanpenner** [comment]
this is an issue with esperanto, pending a PR merge: https://github.com/esperantojs/esperanto/pull/176

(which i forgot to do last night)
