### ISSUE TITLE
appears there was a breaking change recently

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#2119]
https://github.com/esperantojs/esperanto/issues/185

It appears the rest arg does not get transpiled correctly. Note there is a warning that is printed, but this change has the potential to break projects with `^` dep.

**Comment by Rich-Harris** [comment]
Oh, could this be related to `es6.parameters.default` and `es6.parameters.rest` being combined as `es6.parameters`? I've encountered that a couple of times

**Comment by stefanpenner** [comment]
> Oh, could this be related to es6.parameters.default and es6.parameters.rest being combined as es6.parameters? I've encountered that a couple of times

yes

**Comment by sebmck** [comment]
Regression due to #1907. cc @samccone Appears to be [this](https://github.com/babel/babel/pull/1907/files#diff-254251bf3fc66da6a1bb6740bc4a0d3dR166) line, switching `arr` to `prev` makes it work, although I don't have time to investigate and make sure it's the right fix.

**Comment by samccone** [comment]
yes that it the correct fix, sorry initially I thought the intent was slightly different, this is my bad sorry guys

**Comment by jridgewell** [comment]
A full revert is needed. `#reduce` caches the array's length, preventing that line from working correctly.

Simply swapping the `arr` to `prev` won't allow the loop to lookup `aliases` or `namespaces` for the `deprecatedKey`.

**Comment by samccone** [comment]
@jridgewell yes, ok if we want to do a second pass over the array then yes, we should revert this.

**Comment by samccone** [comment]
I am a little bit concerned that there was no test case to catch this, I guess I was leaning too heavily on the suite here. my bad again sorry :crocodile:

**Comment by sebmck** [comment]
@jridgewell We don't need to lookup any of the aliases or namespaces?

**Comment by yesplease** [comment]
Yeah this broke our site too :) Thanks for the team here checking this out!

**Comment by jridgewell** [comment]
I'm not sure where they're defined, so I couldn't check. Just letting you know the original (before PRs) and the current code aren't equivalent.
