### ISSUE TITLE
Angular2 annotations appear to be undefined

### ISSUE THREAD

**Issue by blacksonic** [babel/babel#2120]
I have the following Angular2 code what i transpile with browserify and babel:
```
import {ComponentAnnotation, ViewAnnotation, bootstrap} from 'angular2/angular2';

@ComponentAnnotation({
  selector: 'hello-cmp'
})
@ViewAnnotation({
  template: 'Hello World!'
})
class HelloComponent {}

bootstrap(HelloComponent);
```
It transpiles well, but when i run the code iget the following error for annotations, but ```console.log``` show defined functions:
``` Uncaught TypeError: _angular2Angular2.ViewAnnotation(...) is not a function ```

I tried ES5 syntax and it works, so the annotation functions of Angular2 are really there:
```
var HelloComponent = function () {

};

HelloComponent.annotations = [
  new ComponentAnnotation({
    selector: 'hello-cmp'
  }),
  new ViewAnnotation({
    template: 'Hello World!'
  })
];
```

Here is the transpiled code also:
```
var _angular2Angular2 = require('angular2/angular2');

console.log(_angular2Angular2.ComponentAnnotation, _angular2Angular2.ViewAnnotation);

var HelloComponent = (function () {
  function HelloComponent() {
    _classCallCheck(this, _HelloComponent);
  }

  var _HelloComponent = HelloComponent;
  HelloComponent = _angular2Angular2.ViewAnnotation({
    template: 'Hello World!'
  })(HelloComponent) || HelloComponent;
  HelloComponent = _angular2Angular2.ComponentAnnotation({
    selector: 'hello-cmp'
  })(HelloComponent) || HelloComponent;
  return HelloComponent;
})();

_angular2Angular2.bootstrap(HelloComponent);
```

Am i missing something here?

**Comment by blacksonic** [comment]
I have a repository also where u can check it after ```npm install && gulp start```:
https://github.com/blacksonic/koan2do

**Comment by mgcrea** [comment]
@blacksonic `{optional: ['es7.decorators']}`?

**Comment by blacksonic** [comment]
@mgcrea  same error :(
based on the transpiled code it shouldnt be undefined

Ill clean up dependencies and might try es6ify if it is a problem with the built package or the code or the transpiler...but the code seems quite simple.

**Comment by blacksonic** [comment]
I checked it with traceur and it works, but generates different code for annotations:
```
Object.defineProperty(HelloComponent, "annotations", {get: function() {
    return [new Component({selector: 'hello-cmp'}), new View({template: 'Hello World!'})];
  }});
```
Maybe change the transpile implementation to this?

**Comment by sebmck** [comment]
> Maybe change the transpile implementation to this?

They aren't annotations, they're decorators. They have very different semantcis and compile differently. Annotations are something invented by Angular for AtScript, decorators are a formal standard that's being proposed for inclusion in ECMAScript. You can read about decorators [here](https://github.com/wycats/javascript-decorators).

Your code is throwing that error because when you do:

```javascript
@foo
class Foo {}
```

it really means:

```javascript
class Foo {}
Foo = foo() || Foo;
```

So it's trying to do:

```javascript
class HelloComponent {}
HelloComponent = ComponentAnnotation({
  selector: 'hello-cmp'
})() || HelloComponent;
HelloComponent = ViewAnnotation({
  template: 'Hello World!'
})() || HelloComponent;
```

Note the `()` after your functions are called.

If you have anymore questions in the future please don't hesitate to ask in one of the links referenced in the [README](https://github.com/babel/babel#readme):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>

Thanks! :blush:

**Comment by blacksonic** [comment]
Than it is more scarier than i thought....traceur transpiles to non standard compliant code :/ reminds me of IE
