### ISSUE TITLE
When compiling JSX files, source map links to JSX source file rather than compiled JS file

### ISSUE THREAD

**Issue by meglio** [babel/babel#2124]
Calling babel with the following options:

`--compact=true --source-maps=true --comments=false --out-file ../build/common.js common.jsx`

Extract from the `.map` file:

`"sources":["../src/common.jsx"]`

This makes no sense because the `.jsx` file is not even loaded into the browser. The compiled `.js` is loaded instead.

Can I configure babel to generate the `.map` file to the compiled `.js` file instead?

**Comment by jmm** [comment]
Hello @meglio. That's how source maps generally work. Do you just mean that you want the map to contain `"sources":["../src/common.js"]` instead?

In the future, please ask these kinds of questions in the slack chat or on stackoverflow, per the README. Thanks!

**Comment by meglio** [comment]
Sorry, would do as advised the next time. I just considered it's a bug and reported it here.

It is not always the case when JSX is loaded in the browser. What is loaded is the compiled JS, thus I expect the source map to link to the JS file, not the JSX file - or at least have it configurable.

For example, in some coffeescript -> js -> min.js tutorial for uglifyjs2 I saw this:

Step 1. Coffescript gets compiled into JS with its own map file
Step 2. A compiled JS gets then compiled into js.min with its own map file, (optionally) taking into account the first map file.

**Comment by lydell** [comment]
What's the difference to simply not generating a source map at all?

**Comment by jmm** [comment]
@meglio Help me understand what you're looking for: what do you want to be in the source map? In `coffeescript => js => min.js` some people would want the source map to refer to the coffeescript and some may want it to refer to the JS. But in this case it's just one step: `JSX => JS`, `input => output`.

> What is loaded is the compiled JS, thus I expect the source map to link to the JS file

I'm not quite sure what you mean. As you say, the compiled JS is already loaded, so in what fashion would the source map "link to the JS file"?

Phrasing your response as an answer to @lydell's question would also help me understand your meaning.

**Comment by sebmck** [comment]
Closing since as @jmm said, this is how you're supposed to use the `sources` property of a source map. Thanks! :blush:
