### ISSUE TITLE
Register doesn't monkey patch for Istanbul when register is called first

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2125]
https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js#L125-L144

Since this will only evaluate once, there's no way to get istanbul to work if `babel-core/register` is being required beforehand.

Related PR: https://github.com/babel/babel-library-boilerplate/pull/190

**Comment by sebmck** [comment]
It's not entirely clear what the issue is. What do you mean by if `babel-core/register` is required beforehand, before what exactly?

**Comment by thejameskyle** [comment]
Sorry, it was late when I was doing this.

Basically Gulp is requiring `babel-core/register` before requiring the `gulpfile.babel.js` file, so when Istanbul is required `babel-core/register` never finds out about it because it only looks for the global `process.env.running_under_istanbul` once.

**Comment by sebmck** [comment]
You aren't using the `istanbul` CLI so there's probably no way to handle this case. Open to suggestions though.

**Comment by thejameskyle** [comment]
Could we expose something to call when we know we're running istanbul?

**Comment by sebmck** [comment]
I've removed the monkeypatching.
