### ISSUE TITLE
Fails to parse angular2 parameter annotation

### ISSUE THREAD

**Issue by mgcrea** [babel/babel#2128]
I'm working on a babel plugin to parse angular2 custom annotations (fork from shuhei's work): https://github.com/mgcrea/babel-plugin-angular2-annotations

I'm struggling to add support for some parameters annotations:

```
export class Overview {
  constructor(@Optional() router: Router) {
  }
}
```

That should end up to something like:

```
__param(0, di_1.Optional()), 
__metadata('design:paramtypes', [router_1.Router])
```

However the above code fails to compile (` Unexpected token` error) due to the `@Optional()` annotation. I'm not familiar with the babel plugin pipeline, but it looks like my `ClassDeclaration` visitor is never called (babel does fail before) so I have no chance to drop the unsupported syntax.

Looks like it could be fixed by #1351, any chance there might be a workaround?

**Comment by mgcrea** [comment]
Hum, looks like `stage: 0`did the trick.

**Comment by loganfsmyth** [comment]
Unfortunately, as you saw in https://github.com/babel/babel/issues/1351, adding features into the parser isn't supported for plugins at the moment, so there isn't really any way to do this currently. Feel free to join the [Slack community](https://babel-slack.herokuapp.com/) if you want to chat more about it.
