### ISSUE TITLE
Extending Error doesn't work as expected

### ISSUE THREAD

**Issue by reinhrst** [babel/babel#2131]
For version 5.8.19, extending Error results in the parent constructor not being called (I suspect)
```
# /tmp/babel-5.8.19 > ./node_modules/.bin/babel-node 
> new Error("hello").message
'hello'
> class Error2 extends Error{}
'use strict'
> new Error2("hello").message
''
```

In version 5.1.13 things still work as I would expect them
```
# /tmp/babel-5.1.13 > ./node_modules/.bin/babel-node 
> new Error("hello").message
'hello'
> class Error2 extends Error{}
'use strict'
> new Error2("hello").message
'hello'
```

**Comment by reinhrst** [comment]
Actually, it looks like the `Error` constructor *is* being called, however the message field is not set on the `Error2` object.

Tests were done on node 0.12.2 and Chrome 44

**Comment by sebmck** [comment]
See the [caveats](https://babeljs.io/docs/advanced/caveats/#classes) page. There's no reliable way for this to be compiled that will work amongst all ES5-era engines. Extending from `Error` can be special cased as it's very easily statically verifiable but you get to extremely tricky cases with dynamic code.

**Comment by sebmck** [comment]
See also #1336 and #1424 for previous discussion.
