### ISSUE TITLE
JSX Transformer assumes React import

### ISSUE THREAD

**Issue by alex94puchades** [babel/babel#2135]
All JSX snippets get replaced by their React.createElement counterpart. However, the presence of React is assumed. This assumption falls apart in the presence of ES6 imports. The following code results in a ReferenceError:
```js
import {Component} from 'react';
```
Dependencies used by generated code should be pulled automatically, by means of `import * as React from 'react'` or equivalent. Thanks

**Comment by jmm** [comment]
Hi @alex94puchades, thanks for your interest in babel.

> Dependencies used by generated code should be pulled automatically, by means of `import * as React from 'react'` or equivalent.

That was considered and decided against in #586. There's a plugin designed to do that though: [babel-plugin-react-require](https://github.com/vslinko/babel-plugin-react-require).

> However, the presence of React is assumed. This assumption falls apart in the presence of ES6 imports. The following code results in a ReferenceError:
> 
>
  ```js
  import {Component} from 'react';
  ```

I'm not sure what you mean here. What's the significance of the ES6 import? How does that example import relate to transforming JSX?

**Comment by sebmck** [comment]
> However, the presence of React is assumed.

Yep, this is a dilberate decision. What if `React` is a global? It's a use-case that needs to be taken into consideration. As @jmm points out this behaviour was already considered and decided against because it's far too opinionated and if you want it then you can use capabilities of your module bundler.

> This assumption falls apart in the presence of ES6 imports.

It doesn't really. Just use:

```javascript
import React, {Component} from 'react';
```

**Comment by tschaub** [comment]
> `import React, {Component} from 'react';`

Unfortunately, this doesn't work if you want to run a linter that warns about [unused variables](http://eslint.org/docs/rules/no-unused-vars).

Here's a complete example that generates a `ReferenceError`:
```js
import {Component} from 'react';

class App extends Component {
  render() {
    return (
      <p>Hello world</p>
    );
  }
}

export default App;
```

**Comment by cesarandreu** [comment]
@tschaub [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)
