### ISSUE TITLE
Uncaught syntax error in class definition with babel-node

### ISSUE THREAD

**Issue by danmartinez101** [babel/babel#2139]
I would expect this code to show some error message in the console when running it with babel-node, but it just hangs with no output.

```
import assert from 'assert';

import {MongoClient} from 'mongodb';
const url = 'mongodb://localhost:27017/myproject';

class MongoRepository {

  constructor(db) {
    this._db = db;
  }

  add(messageType, item) {
    var tester = ggg;
    let collection = this._db.collection(messageType);
    return collection.insertOne(adds)
      .catch((error) => {
        console.log('ere');
        throw new Error('Error adding object');
      });

  }
}

MongoClient.connect('mongodb://localhost:27017/test')
  .then(db => {
    let repository = new MongoRepository(db);

    repository.add('aTestType', {aTest: 'object'})
      .then(response => {
        console.log(response.result);
      })
      .catch(error => {
        console.log(error);
      })
      .done();

  });
```

**Comment by sebmck** [comment]
Where's the supposed syntax error?

**Comment by danmartinez101** [comment]
var tester = ggg; and insertOne(adds)

ggg and adds are not defined anywhere but when I run 
```
function myFun(anArg) {
  var something = thatDoesNotExist;
}

myFun()
```

I get 
```
/Users/dmartinez/source/rm-js/source/gui/test.js:26
  var something = thatDoesNotExist;
                  ^
ReferenceError: thatDoesNotExist is not defined
    at myFun (/Users/dmartinez/source/rm-js/source/gui/test.js:24:19)
    at Object.<anonymous> (/Users/dmartinez/source/rm-js/source/gui/test.js:27:1)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/lib/_babel-node.js:144:25)
    at Module._compile (module.js:460:26)
```

**Comment by sebmck** [comment]
That's not a syntax error. I'm not sure what the Babel issue is here? Seems more like just a bug in your code.

**Comment by danmartinez101** [comment]
Sorry,  I misspoke; I meant a ReferenceError not a syntax error. It is quite possible that I'm missing something, but I expected that the code above `var tester = ggg;` would produce the same ReferenceError as ` var something = thatDoesNotExist;`

Is this indeed just me being obtuse?

**Comment by sebmck** [comment]
I'm not sure. There's not really enough information to debug anything. Do you have a minimal reproducible code snippet I can just execute without setting up mongo/dependencies etc?

**Comment by danmartinez101** [comment]
I'll put something together; should have done that in the first place.

**Comment by danmartinez101** [comment]
Does this help more?
```
class Collection {
  constructor(name) {}
  insertOne(value) {
    console.log(value);
  }
}
class Db {
  collection(name) {
    return new Collection(name);
  }
}
class MongoClient {
  static connect(url) {
    return Promise.resolve(new Db())
  }
}
export default class MongoRepository {

  constructor(db) {
    this._db = db;
  }

  add(type, item) {

    let collection = this._db.collection(type);
    return collection.insertOne(itemss)

  }

  remove(type, id) {

    let collection = this._db.collection(type);
    return collection

  }

}
MongoClient.connect('url').then(db => {
  let repository = new MongoRepository(db);
  repository.add('atype', 'avalue')
    .then((response) => {
      console.log('response.result');
    })
    .catch(error => {
      console.log('error');
    })
    .done();

})
```
In this dependency free example, itemss should be item

**Comment by danmartinez101** [comment]
And so yes, I'm probably wrong about this.

Adding `.catch(error=>{console.log(error)}` to the end of this makes `[ReferenceError: itemss is not defined]` show up in the console.

This is certainly not what I would expect, but if you can confirm this is not a babel issue but a ES6 promise issue, then this issue should probably just get closed.

**Comment by loganfsmyth** [comment]
@danmartinez101 Unfortunately, depending on your platform, promises swallow errors by default. Chrome for instance will automatically print a message. The behavior isn't part of the ES6 spec, but many platforms have started to adopt it. In iojs, you can use [`process.on('uncaughtRejection', ...`](https://iojs.org/api/process.html#process_event_unhandledrejection) to attach a listener to let you know when you have an unhandled rejection.

**Comment by danmartinez101** [comment]
It seems unfortunate that the default behavior would ever be to swallow errors un-announced. Sounds like a recipe for lost time... Thanks for the `uncaughtRejection` tip; I'll definitely be using that.
