### ISSUE TITLE
--watch only writes 14 bytes, sometimes

### ISSUE THREAD

**Issue by caspervonb** [babel/babel#2140]
Seems like `--watch` mode reads the file when its truncated instead of waiting for the second write event, resulting in empty an input file and and output file containing only "using strict"

![screen shot 2015-08-01 at 18 13 11](https://cloud.githubusercontent.com/assets/157787/9021568/ef561362-387a-11e5-94c2-8f3259e82e7e.png)

The writes here are logged when the input file is done being written to, babel is invoked as a child process with `--watch`

**Comment by sebmck** [comment]
This is probably due to your OS as these events are triggered by [chokidar](https://github.com/paulmillr/chokidar). I'd recommend opening an issue over there with your exact environmental setup. I don'ts ee anything that can or should be fixed on the Babel side.

**Comment by caspervonb** [comment]
Well, it's not like this is on an obscure operating system, this is how chokidar acts when using `fs.watch`
