### ISSUE TITLE
Rest properties destructuring

### ISSUE THREAD

**Issue by vieks** [babel/babel#2143]
**For Arrays** rest destructuring all works fine in all cases,

eg
```
let arr = [10, 20, 30];
let [...x] = arr;
console.log(x);
```

Same result if 'x' variable declared before:

```
let arr = [10, 20, 30];
let x;
[...x] = arr;
console.log(x);
```

**For Objects**, only the first case works properly,

eg

```
let obj = { x : 10, y : 20, z : 30 };
let {...x} = obj;
console.log(x);
```

Its OK.
But now, if 'x' previously declared it will fail:

```
let obj = { x : 10, y : 20, z : 30 };
let x;
{...x} = obj;
console.log(x); // Uncaught SyntaxError: repl: Unexpected token
```

Can fix this ?

Thanks.

**Comment by sebmck** [comment]
This is correct and expected behaviour. There's syntactic ambiguity because `{` is the start of a block statement. Wrap it in parentheses so instead of:

```javascript
{ x } = {};
```

do

```javascript
({ x } = {});
```

**Comment by sebmck** [comment]
Also see #1684 and #1023.

**Comment by vieks** [comment]
Indeed, and its also write in the MDN doc [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) at beginning in a colored frame and I miss it...
Thanks @sebmck for your quick answer :)
