### ISSUE TITLE
Comments order is broken

### ISSUE THREAD

**Issue by aksyonov** [babel/babel#2146]
I use `babel` and `ng-annotate` in my `angularjs` project. After updating to latest babel version I got `strict di` angular errors. Turns out `babel` adds some internal variables between comment and function and `ng-annotate` expects comment to be right before the function.

**Input:**
```js
'use strict';
import angular from 'angular';

/*@ngInject*/
function User(Restangular) {
}
```

**Expected:**
```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _angular = require('angular');

var _angular2 = _interopRequireDefault(_angular);

/*@ngInject*/
function User(Restangular) {}
```

**Actual:**
```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _angular = require('angular');

/*@ngInject*/

var _angular2 = _interopRequireDefault(_angular);

function User(Restangular) {}
```
The same bug with one-line comments.

**Comment by sebmck** [comment]
Fixed. Man, I really hate `ng-annotate` decision to use comments as directives. It makes it extremely hard and awkward to support.
