### ISSUE TITLE
Module double interop

### ISSUE THREAD

**Issue by guybedford** [babel/babel#2148]
This may be too soon, but its one of those things that if done is best done early.

Module interops need to be designed to support arbitrary levels of folding. It's no use being able to create a bundle, if you can't in turn bundle that bundle etc etc.

The particular double interop here is the following case:

1. Create an ES6 module
2. Compile to CommonJS with Babel
3. Load that module in an ES6 module environment
4. Have a dependency of that module that was initially ES6 transpiled to CommonJS be replaced by a real ES6 module in the environment `require` resolution process.

In the above scenario as soon as you have a "real" ES6 module, the interop check (for `module.__esModule`) fails and it treats it incorrectly.

It currently falls down pretty obviously - you get a module like  `{ default: { default: {..} }`, so users will usually know something went wrong and to not build an app that uses this (one hopes).

We can actually already today extend this interop check of `module.__esModule` to work against real ES6 modules thanks to http://www.ecma-international.org/ecma-262/6.0/#sec-@@tostringtag.

Thus, the check to tell if a module is an ES6 module or compatibility module becomes:

```javascript
if (m && m.__esModule || typeof m == 'object' && m == 'Module') {...} 
```

The string conversion seems completely definite as far as I can tell. So the only worry is perhaps if we can't assume `typeof m == 'object'` for a module. I'm not sure than any other type has been defined though that might be used by browsers instead?

I'm not sure how important this particular double interop is, but thought it would be worth mentioning as it forms part of the bridging boundary between polyfill assumptions and real modules, and since we're churning out code in the wild that may benefit one day from having a deep CommonJS dependency replaced with a real ES module, while leaving the rest of the transpiled CommonJS in tact, it's definitely worth making sure we've discussed it properly.

**Comment by guybedford** [comment]
From checking with AWB on Twitter, this may need to be modified slightly (https://twitter.com/awbjs/status/633657403481833472 and https://twitter.com/awbjs/status/633657958975430656):

> m == 'Module' will typically throw in ToPrimitive unless `valueOf` or `toString` is exported. You probably want to say: `m[Symbol.toStringTag]=='Module'` but false positives are possible

I guess some variation of the above would work in all scenarios. We could outright disallow these kinds of double interops, since they currently are discouraged by not working out. But would still be good to make that decision explicitly.

**Comment by thejameskyle** [comment]
I think this makes sense to do. @guybedford want to make a PR?

**Comment by guybedford** [comment]
Thanks @thejameskyle for the response here. With some help from Denis, it seems like a full `isModule` detection for both core-js polyfill environments and ES6 environments would be:

```javascript
var toStringTag = global.Symbol && Symbol.toStringTag || global['__core-js-shared__'] && global['__core-js-shared__'].wks && global['__core-js-shared__'].wks.toStringTag;
function isModule(m) {
  return typeof m == 'object' && (m.__esModule || toStringTag && m[toStringTag] == 'Module');
}
```

The question still remains if this is (a) useful (b) worth getting out now. The issue is that it is pointless doing (b) without being 100% sure of (a)!

The use case that this applies to is if I have a project on npm that uses Babel output to CommonJS, and one of my dependencies is updated to use real ES6 modules. This upgrade of my dependency would, I assume, be a breaking one. So that retranspiling the output of my sources through Babel when I do this upgrade should be fine.

So since (a) is uncertain, and the benefit of (b) doesn't quite seem to be there, I'm thinking we should wait to hit real use cases here. Lets watch out for it when it happens though (`{ default: { default: .. } }` modules in ES module environments would be the sign) and then at least not look completely uninformed for considering the basic upgrade path from polyfill workflows to real modules.

**Comment by zloirock** [comment]
@guybedford `'__core-js_shared__'` instead of `'__core-js-shared__'` :)

**Comment by timbur** [comment]
If doing this will make modules consistently work with little to no effort, I think it should be done, regardless of how common the use-cases are.  Prime example (and what led me here): I keep running into an issue where I configure `systemjs` to load a babel plugin which has been transpiled to `cjs` and then tries to import an `es6` module, but it won't work without significant effort (i.e., configuration and/or cloning the repo and manually fixing it for `systemjs` support) because it's importing all of the `someModule`'s `es6` exports as an object rather than `someModule.default`.
