### ISSUE TITLE
babel-core/browser.js transformation with options?

### ISSUE THREAD

**Issue by kenokabe** [babel/babel#2149]
https://babeljs.io/docs/usage/browser/

>A browser version of Babel is available from browser.js inside a babel-core npm release

> ```js
<script src="node_modules/babel-core/browser.js"></script>
<script type="text/babel">
//...............................
</script>
```

So far, I could not find any way to configure [options](https://babeljs.io/docs/usage/options/) for the above, therefore, I used the API

>babel.run(code, [opts])

and wrote the code like below:

```js

<body>
  <script src="./babel-browser.js" ></script>
  <script>
   var urls = ["./index.jsx"];
    xhrDoc = new XMLHttpRequest();
    xhrDoc.open('GET', urls[0])
    if (xhrDoc.overrideMimeType)
        xhrDoc.overrideMimeType('text/plain; charset=x-user-defined')
    xhrDoc.onreadystatechange = function() {
        if (this.readyState == 4) {
            if (this.status == 200) {
                var data = this.response; //Here is a string of the text data
                var out = babel.run(data, { stage: 0 });
            }
        }
    }
    xhrDoc.send() //sending the request
  </script>

</body>

```

To me, this is no problem, but the question is, is there any way to put *options* directly into the HTML code as attributes or so?

Just wanted to make sure, thanks.

**Comment by sebmck** [comment]
> is there any way to put options directly into the HTML code as attributes or so?

There's not.

If you have any further questions please don't hesitate to use one of the resources located in the [README](github.com/babel/babel#readme):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:
