### ISSUE TITLE
Decorator not getting called each time Class method is called

### ISSUE THREAD

**Issue by justinsthomas** [babel/babel#2155]
I'm running into an issue with decorators in that I've attached a decorator to a method of a class, and that decorator gets called each time the class is imported, not each time the method is invoked. For example:

My decorator
```javascript
class Decorator {
    constructor() {}

    myDecorator(someParam) {
        return function(target, name, descriptor) {
            console.log('do some decorating');
            return descriptorl
        }
    }
}

let decorator new new Decorator();
export default decorator;
```

My service I want to use the decorator
```javascript
import Decorators from '../decorators/myDecorators';

class Service{
    constructor(){}

    @Decorators.myDecorator(someParam)
    serviceMethod(options){
        // perform service functionality
    }
}

let service = new Service();
export default service;
```

I have several other files that import this base Service class, and every time one of those other classes is instantiated, the decorator gets called. However, this does not invoke the decorator:

API Services example
```javascript
import Services from '../services/myServices' // reference to 'Service' class, above

class APIService {
    constructor(){}

    getUserName() {
        let options = {
            method: 'POST',
            params: {},
            path: '/path/to/api/endpoint/name'
        }
        Services.serviceMethod(options);
    }

    getUserAddress() {
        let options = {
            method: 'POST',
            params: {},
            path: '/path/to/api/endpoint/address'
        }
        Services.serviceMethod(options);
    }
}
```

I have several instances where I'm making multiple API calls per page; each one relies on the original Service.serviceMethod. If the decorator is applied to the `serviceMethod` method of the `Service` class, shouldn't the decorator be called every time the method is invoked, or am I totally misunderstanding the implementation of decorators?

**Comment by loganfsmyth** [comment]
Class method decorators run when a class is defined, not when the method is called. You could however have your decorator return a new property descriptor that is a replacement for the original one, with the new one having a function that is called every time. Does that make sense?

**Comment by stefanpenner** [comment]
> You could however have your decorator return a new property descriptor that is a replacement for the original one, with the new one having a function that is called every time.

:+1:

**Comment by justinsthomas** [comment]
@loganfsmyth I'm not sure I 100% follow. Do you mean something like this?

```javascript
class Decorator {
    constructor() {}

    myDecorator(someParam) {
        return function(target, name, descriptor) {
            console.log('do some decorating');
            descriptor.myFunction = function(){
                // do whatever the decorator needs to do here
            }

            return descriptor;
        }
    }
}
```

So descriptor.myFunction() would get run every time? Is that correct?

**Comment by loganfsmyth** [comment]
I'd read up on the structure of descriptors: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Something like this:

```
myDecorator(someParam){
  return function(target, name, descriptor){
    const {value} = descriptor;
    descriptor.value = function(){
        // do whatever wrapping logic, then call through to the original method.
        return value.apply(this, arguments);
    };
  };
}
```

**Comment by justinsthomas** [comment]
Thanks @loganfsmyth, got it working properly now.
