### ISSUE TITLE
Avoiding try-catch emission in 'for of'?

### ISSUE THREAD

**Issue by ludamad** [babel/babel#2157]
I am aware try-catch is emitted in 'for of' for some compatibility reason; however, it can be a surprising performance-hit on eg V8. Is there a way to suppress its emission (at the cost of some compatibility)?

**Comment by zloirock** [comment]
[Loose mode](http://babeljs.io/docs/advanced/loose/#es6-for-of).

**Comment by loganfsmyth** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by sebmck** [comment]
Yep, see [loose mode](https://babeljs.io/docs/advanced/loose/). Usage:

```javascript
require("babel-core").transform("code", {
  loose: ["es6.forOf"]
});
```

**.babelrc**

```json
{
  "loose": ["es6.forOf"]
}
```

For more information see duplicate issue #1176, as well the [FAQ](https://babeljs.io/docs/faq/#why-is-the-output-of-for-of-so-verbose-and-ugly-). If you have anymore questions in the future please don't hesitate to use one of the links provided in the [README](github.com/babel/babel#readme).

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:

**Comment by ludamad** [comment]
Thanks a lot guys. Sorry for not reading carefully.
