### ISSUE TITLE
No runtime error for spreading non-iterables

### ISSUE THREAD

**Issue by webbedspace** [babel/babel#2160]
`console.log([...2]);` produces code which outputs an empty array, instead of throwing a runtime error. (Whether or not this is capable of being fixed is unknown to me.)

**Comment by zloirock** [comment]
Currently spread in `babel` uses `Array.from`. `Array.from` different from spread support array-like objects. Possible add checking `Symbol.iterator in it ? Array.from(it) : throwError()`, but it will create problems with `arguments` - by spec it should be iterable, but we can't add `Symbol.iterator` to `arguments` prototype - it's `Object.prototype`. Someone can use `[...arguments]`.

**Comment by hzoo** [comment]
Can we just check for `arguments`?

**Comment by ljharb** [comment]
`[...function* () {}]` is another example.
