### ISSUE TITLE
Istanbul ignore for for..of statement

### ISSUE THREAD

**Issue by pveyes** [babel/babel#2164]
Currently for..of statement is converted into iterator with try-catch-finally block with no istanbul ignore comment in catch and finally block, so istanbul report 'wrong' coverage .

This is a minor issue though

**Comment by loganfsmyth** [comment]
@sebmck I've thought about this a bit myself since I also saw it in our own coverage reports. Do you think it would make sense to have a plugin with the explicit goal of adding istanbul comments to the right places?

**Comment by sebmck** [comment]
@loganfsmyth There's the `auxiliaryComment` that does this already.

**Comment by loganfsmyth** [comment]
Ah okay, it didn't seem to cover everything, so it wasn't clear if it was expected to cover everything like this case.

**Comment by loganfsmyth** [comment]
Given Sebastian's comment, I'm going to close this. If that isn't working, feel free to reply or come onto the slack support channel to chat.
