### ISSUE TITLE
runtime should use existing implementations if they are preset

### ISSUE THREAD

**Issue by Gozala** [babel/babel#2165]
With `--optional [runtime]` babel uses own `Promise` implementation even if `Promise` implementation exists in the actual runtime. It would be great if runtime could leverage existing implementation of promise if available.

**Comment by sebmck** [comment]
Yep, it does. :blush: This is how `core-js` works. @zloirock can probably explain a bit better than I can.

**Comment by loganfsmyth** [comment]
Probably https://github.com/zloirock/core-js/issues/78

**Comment by zloirock** [comment]
`core-js` uses own `Promise` implemenation only if native missing or broken. For example, actual V8 `Promise` has bug with resolving thanables.

**Comment by Gozala** [comment]
hmmm, I see this on gecko which I believe has a non broken implementation, will look into how core-js detects if Promise implementation is broken.

**Comment by zloirock** [comment]
FF `Promise` has a problem with subclassing. [Code of detection](https://github.com/zloirock/core-js/blob/v1.0.1/modules/es6.promise.js#L31-L56).
