### ISSUE TITLE
babel-node interferes with CLI apps

### ISSUE THREAD

**Issue by jasonkuhrt** [babel/babel#2166]
For example:
```
❯ babel-node --version
5.8.20
```
```
❯ babel-node ./lib/cli.js --name foobar --env stage --version 0.0.2
5.8.20
```
Whoops, `babel-node` told me its version instead of running my CLI app.

**Comment by sebmck** [comment]
See the [docs](https://babeljs.io/docs/usage/cli/#usage):

> When arguments for user script have names conflicting with node options, double dash placed before script name can be used to resolve ambiguities
>
> ```sh
> $ babel-node --debug --stage 0 -- script.js --debug
> ```

In your case it's:

```sh
$ babel-node -- --version
```

and

```sh
babel-node ./lib/cli.js -- --name foobar --env stage --version 0.0.2
```

Thanks :blush:

**Comment by jasonkuhrt** [comment]
Ah thanks.

Blushing?

**Comment by sebmck** [comment]
idk that's just the emoji i use all the time to not look like a dick

**Comment by stefanpenner** [comment]
> idk that's just the emoji i use all the time to not look like a dick

or a duck

**Comment by jasonkuhrt** [comment]
Hm, still not working but probably not a babel issue. Maybe `commander`?

```
❯ babel-node ./lib/cli.js -- --name foobar --env stage --version 0.0.2
--name is required.
```
(`commander` failed to read `name`)

Anyways, thanks ya'll.

**Comment by jasonkuhrt** [comment]
Got it, wasn't paying attention before:

```
babel-node -- ./lib/cli.js --name foobar --env stage --version 0.0.2
```

:+1: 

@sebmck May want to edit your suggested fix above for future reference (it differs from what the docs say).

Cheers again.
