### ISSUE TITLE
Skip compilation if destination is newer than source (like make)

### ISSUE THREAD

**Issue by clark800** [babel/babel#2167]
Currently I'm compiling with this: `babel -D --optional runtime -d dist/npm/ src/`. This recompiles all source files every time it runs. It would be nice if it only compiled source files that changed since the last compilation.

**Comment by sebmck** [comment]
This seems like something a build system should do. I don't think it makes sense for the CLI should be making these kinds of decisions or even offer this sort of functionality.

**Comment by clark800** [comment]
That makes sense. It would be convenient for users, but not necessarily optimal for separation of responsibilities. Perhaps a sample build system configuration could be added to the usage documentation because it seems like something that almost everyone would want. For example, I spent a while searching for the best/simplest/recommended way to do it. If I were to write a Gulpfile or Makefile, I'd have to implement `-w` and `-D` separately. Maybe you could argue that those belong in the build system too.

**Comment by sebmck** [comment]
> Maybe you could argue that those belong in the build system too.

Yeah I'd say they do. I'm not very familiar with existing build systems but from what little I've seen of gulp and grunt, copying files and watching and compiling on changes is fairly trivial. Closing this as I consider it out of scope for the CLI. Thanks! :blush:
