### ISSUE TITLE
Define getModuleId in babelrc?

### ISSUE THREAD

**Issue by thgreasi** [babel/babel#2173]
I guess that the answer will probably be negative, but I couldn't find a reference.
It's there a way to devine the getModuleId function in .babelrc or package.json ?

**Comment by sebmck** [comment]
Unfortunately not. `.babelrc` files are serialisable so you can't represent native functions.

**Comment by sebmck** [comment]
If you have any further questions please don't hesitate to use one of the resources referenced in the [README](https://github.com/babel/babel#readme):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:

**Comment by thgreasi** [comment]
Ooops I'm really sorry for the spam!

On Thu, Aug 6, 2015 at 12:15 PM Sebastian McKenzie <notifications@github.com>
wrote:

> If you have any further questions please don't hesitate to use one of the
> resources referenced in the README <https://github.com/babel/babel#readme>
> :
>
> For questions and support please visit the Slack community
> <https://babel-slack.herokuapp.com> or StackOverflow
> <http://stackoverflow.com/questions/tagged/babeljs>. The Babel issue
> tracker is *exclusively* for bug reports and feature requests.
>
> Thanks! [image: :blush:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2173#issuecomment-128301956>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
