### ISSUE TITLE
Better error message for browser version

### ISSUE THREAD

**Issue by vjeux** [babel/babel#2175]
The current error message says the line and column but it's the one from the script and not the entire file, so it's hard to figure out which line it is. Would be nice to provide the actual line in the error message :)

<img width="753" alt="screen shot 2015-08-06 at 10 25 33 am" src="https://cloud.githubusercontent.com/assets/197597/9118492/94bf604e-3c25-11e5-8ede-ed35d9191cc8.png">

**Comment by sebmck** [comment]
What do you get in the stack trace? The normal code frame should be visible.

**Comment by vjeux** [comment]
This is a syntax error, so there's no stack trace related to my script.

<img width="986" alt="screen shot 2015-08-06 at 10 33 28 am" src="https://cloud.githubusercontent.com/assets/197597/9118625/9ac0f038-3c26-11e5-86fc-70c97b5c20a7.png">

**Comment by sebmck** [comment]
Oh weird. Might need to do a conditional to include the codeframe in `message` when `process.browser` is `true` instead of putting it in `stack` since Chrome seems to ignore that.

**Comment by vjeux** [comment]
The syntax error here is that I forgot a `,`

<img width="337" alt="screen shot 2015-08-06 at 10 34 21 am" src="https://cloud.githubusercontent.com/assets/197597/9118642/bdb268c4-3c26-11e5-9c3c-e53c0bcc443f.png">
