### ISSUE TITLE
UMD Module wrapper incorrectly importing * for globals

### ISSUE THREAD

**Issue by Joelkang** [babel/babel#2182]
Seem that when doing in a file ModuleB.js

``` javascript
import * as LocalA from 'ModuleA'
```

this gets transpiled into 

``` javascript
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define('ModuleB', ['exports', 'ModuleA'], factory);
  } else if (typeof exports !== 'undefined') {
    factory(exports, require('ModuleA'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, global.LocalA);
    global.ModuleB = mod.exports;
  }
})(this, function (exports, _ModuleA) {
```

For CJS and AMD the syntax looks correct, but for globals it's incorrectly trying to import LocalA and mapping it to _ModuleA instead of the reverse.

**Comment by compulim** [comment]
Confirm it still bugged in 5.8.24. Anyone working on this?

**Comment by hzoo** [comment]
Is this still an issue, can you confirm the actual/expected?

**Comment by loganfsmyth** [comment]
I don't see this behavior currently. If you can see it, feel free to reopen.
