### ISSUE TITLE
is it possible to run default transformation after an optional transformation in babel/register?

### ISSUE THREAD

**Issue by helios1138** [babel/babel#2183]
I've found that the code that uses **async/await** transformed through **bluebird coroutines** + **regenerator** is about 2x times faster then **co** + **regenerator** and about 6x times faster than **regenerator**'s own implementation of **async/await** (that is currently used in babel's **es7.asyncFunctions** transformation).

But if I run this code:
```
require('babel/register')({ optional: ['bluebirdCoroutines'] });
require('./');
```
it runs the transformer but for some reason disables the default transformation of generators so it only works with `node --harmony`, which is not an option for me.

Right now I was able to do this by first running babel from command line:
```
index.js --out-file index2.js --optional bluebirdCoroutines
```
and only then using **babel/register**:
```
require('babel/register');
require('./index2');
```

So my question is: is it possible to do this using only **babel/register**? So the code would look like this:
```
require('babel/register')({ optional: ['bluebirdCoroutines'] });
require('babel/register');
require('./index2');
```
or somehow like this:
```
require('babel/register')({ optional: ['bluebirdCoroutines', 'default'] });
require('./index2');
```

**Comment by sebmck** [comment]
You can't currently.

**Comment by helios1138** [comment]
@sebmck is it a design decision or is it simply yet to be implemented?

**Comment by loganfsmyth** [comment]
This seems beyond the scope of Babel to me. Why not skip the require hook and write your own build scripts?

**Comment by helios1138** [comment]
@loganfsmyth well, require hook is more convenient than build scripts

**Comment by loganfsmyth** [comment]
That's my point though. It's there for convenience for the standard usecase, but your goals seem fairly non-standard to me, at least as far as your PR goes.

**Comment by helios1138** [comment]
@loganfsmyth Well, reading the documentation, I actually thought it is standard. It says that these are `optional transformers for those who want to take their code that extra mile`. Now you would think that "extra mile" means regular regular babel transformation **plus** some more transformation. It's not entirely obvious that it actually means some more transformation **minus** some of the default transformation.

At least that's the expectation that is logically arises from how this thing is described.

**Comment by helios1138** [comment]
@loganfsmyth also, I'm talking about an inmprovement

**Comment by sebmck** [comment]
5.x is in a freeze and only bug fixes will be released. This is intentional behaviour. Once 6.x lands you will be able to compose transformers and plugins much better so you wont be subjected to this same requirement.

**Comment by helios1138** [comment]
I see, thanks
