### ISSUE TITLE
Flow arrow function return types with multiple arguments

### ISSUE THREAD

**Issue by danharper** [babel/babel#2185]
These compile:

```js
var w = (): string => 'xx'
var x = (foo): string => 'xx'
var y = (foo: string): string => 'xx'
```

but this fails (just having two arguments):

```js
var z = (foo, bar): string => 'xx'
```

```
SyntaxError: test.js: Unexpected token (2:18)
  1 | /* @flow */
> 2 | var z = (foo, bar): string => 'xx'
    |                   ^
  3 |
```

They compile and pass in Flow (and error if I return a number or something), so pretty sure I've got the syntax correct?

Tested on `5.8.21`. Related to #1991?

**Comment by sebmck** [comment]
Fixed in the `development` branch. There are ~100 or so failing parser tests because I'm stealing (copying) some test suites from other projects. Once those are passing I'll push out a new release with all the parser fixes.

**Comment by danharper** [comment]
Awesome, thanks.
