### ISSUE TITLE
Feature request: require in boilerplate instead of inlining it

### ISSUE THREAD

**Issue by jkroso** [babel/babel#2186]
So the definition of `_classCallCheck` for example would look like this:

```js
var _classCallCheck = require('/absolute/path/to/runtime/class-call-check.js')
```

Which looks better and could even be a 3rd party module if there is one. Additionally this method makes it practical to include polyfils for complex features like promises. Which means AOT compiled code could behave the same as runtime compiled.

**Comment by sebmck** [comment]
This is already a feature. See the [runtime docs](https://babeljs.io/docs/usage/runtime/). Thanks :blush:

**Comment by jkroso** [comment]
Oh okay well why is it not the default. I can see why some people might want to turn it off but for the sake of just works™ it should be the default

**Comment by sebmck** [comment]
Not everyone uses modules and forcing them to use a module bundler to use Babel isn't a sane default.

**Comment by jkroso** [comment]
Shouldn't the default be whatever __most__ people use?

**Comment by sebmck** [comment]
Most people don't need this.

**Comment by jkroso** [comment]
Okay well I guess its easy to make a wrapper anyway

**Comment by jkroso** [comment]
Why on earth though does babelify not use it by default?

**Comment by sebmck** [comment]
Because it does other things other than just the helper aliasing which is very opinionated.

**Comment by jkroso** [comment]
Reading through the documentation it looks like it has all the right opinions for me. The only issue is that it uses relative paths in the require calls instead of absolute ones. It should be an easy fix but I couldn't find the code. Can you point me to the source of the runtime transform?
