### ISSUE TITLE
Using let or const before declaration should error

### ISSUE THREAD

**Issue by SimenB** [babel/babel#2187]
Tried finding an issue for this, couldn't find one. Sorry if this is a dupe.

I was reading Airbnb [style-guide](https://github.com/airbnb/javascript/tree/master#14.1), and they pointed to [this](http://es-discourse.com/t/why-typeof-is-no-longer-safe/15) post about how using `typeof` is no longer safe in ES6. Summary: `let` & `const` are not accessible before they are declared, and doing so is a `ReferenceError`.
Babel happily transforms the `let` to `var`, and it works like it used to. Shouldn't it error out as well, like when using `import` anywhere else than at the top level?

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=if%20(condition)%20%7B%0A%20%20%20%20console.log(typeof%20value)%3B%0A%20%20%20%20let%20value%20%3D%20%22blue%22%3B%0A%7D

**Comment by sebmck** [comment]
See #2181 and #563 as well as the linked threads.
