### ISSUE TITLE
Avoid global variables and external helpers by introducing 'use babel'

### ISSUE THREAD

**Issue by staaky** [babel/babel#2188]
I got an idea while trying to avoid global helper variables which Babel currently adds to the top of a file (as mentioned in #898, #903).

To avoid globals you can use [external helpers](https://babeljs.io/docs/advanced/external-helpers/). Adding a file with all of them, or go through the metadata of a transpiled file to figure out which helpers you need and cherry pick those. To truly avoid all globals, you'll end up packing the external helpers back together with your other code, basically creating internal helpers.

What if you didn't have to go through all of that manually but could simply do this?:

```javascript
(function() {
  'use babel';

  class Foo {
    constructor() { this.bar = 'baz' }
  }
})();
```

It would allow for better placement of helpers in the transpiled code:

```javascript
(function () {
  'use babel';
  'use strict';

  function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

  var Foo = function Foo() {
    _classCallCheck(this, Foo);

    this.bar = 'baz';
  };
})();
```

As shown, it could also be used to avoid the global 'use strict', ensuring that nothing added by Babel is exposed.

I think it could be an elegant way to create actual internal helpers, saving a lot of time dealing with this through a build process.

**Comment by sebmck** [comment]
I don't think Babel-specific directives are a good idea in your source code (you can see previous discussion in #2097 and #670). If you want this behaviour then you can always just set `modules: "umd"` and you'll get a nice wrapper. You'll also get the bonus of module interopability. You can read more about modules [here](https://babeljs.io/docs/usage/modules/).

**Comment by staaky** [comment]
Thanks, adding a wrapper like that would be an alternative. But what if you didn't want to export anything but just run code in the browser as is? Using `modules: "umd"` you'll end up with a global `window.babel` or whatever is set as `moduleId`.
