### ISSUE TITLE
Investigate visitor and traversal inlining

### ISSUE THREAD

**Issue by sebmck** [babel/babel#2192]
I'm crazy.

**Comment by thejameskyle** [comment]
> I'm crazy.

You're completely insane.

**Comment by sebmck** [comment]
I remember when
I remember, I remember when I lost my mind
There was something so pleasant about that plase
Even your emotions had an echo
In so much space
And when you're out there
Without care
Yeah, I was out of touch
But it wasn't because I didn't know enough
I just knew too much

:musical_keyboard: :musical_note: :musical_score: :notes: :headphones: :musical_keyboard: :musical_note: :musical_score: :notes: :headphones: 

Does that make me crazy?
Does that make me crazy?
Does that make me crazy?
Possibly

:musical_keyboard: :musical_note: :musical_score: :notes: :headphones: :musical_keyboard: :musical_note: :musical_score: :notes: :headphones: 

And I hope that you are having the time of your life
But think twice
That's my only advice
Come on now, who do you
Who do you, who do you, who do you think you are?
Ha ha ha, bless your soul
You really think you're in control?

:musical_keyboard: :musical_note: :musical_score: :notes: :headphones: :musical_keyboard: :musical_note: :musical_score: :notes: :headphones: 

Well, I think you're crazy
I think you're crazy
I think you're crazy
Just like me

:musical_keyboard: :musical_note: :musical_score: :notes: :headphones: :musical_keyboard: :musical_note: :musical_score: :notes: :headphones: 

My heroes had the heart, to the lose the life I'd want to live
And all I remember is thinking I want to be like them
Ever since I was little
Ever since I was little, it looked like fun
And it's no coincidence I've come
And I can die when I'm done

:musical_keyboard: :musical_note: :musical_score: :notes: :headphones: :musical_keyboard: :musical_note: :musical_score: :notes: :headphones: 

But maybe I'm crazy
Maybe you're crazy
Maybe we're crazy
Probably

**Comment by thejameskyle** [comment]
![what-the-fuck-is-wrong-with-you gif w 700](https://cloud.githubusercontent.com/assets/952783/9188719/3af07d88-3f94-11e5-8b6f-b7f86a7edcc7.gif)
