### ISSUE TITLE
Installing babel from a docker container hangs

### ISSUE THREAD

**Issue by AntouanK** [babel/babel#2193]
See the issue I opened for `chokidar`.

https://github.com/paulmillr/chokidar/issues/333
video with example here
https://github.com/paulmillr/chokidar/issues/333#issuecomment-129581253

`chokidar` on itself works fine.
and `core-js` which is the next package ( at the point where it hangs ) also works fine when I install it alone.
Any idea why it hangs there when trying to install `babel`?

**Comment by sebmck** [comment]
Hey @AntouanK, The Babel issue tracker isn't for support queries or questions. You're more than welcome to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.


Thanks! :blush:
