### ISSUE TITLE
babel promise + facebook sdk

### ISSUE THREAD

**Issue by yonatanmn** [babel/babel#2198]
When using `Promise.then()` (I think that's what triggers the error), fb sdk starts spamming my console.
I think  ([according to this](http://stackoverflow.com/a/17930587/4391952)) that the problem is with this code:

```javascript
//$.task.js
...else if(global.addEventListener && isFunction(global.postMessage) && !global.importScripts){
    defer = function(id){
      global.postMessage(id, '*');
    };
    global.addEventListener('message', listner, false);
...
```
fb sdk is  listening to this, and warns:
`received message of type number from http://localhost:8000, expected a string`
(note: this is not due to localhost, and happens also with my real server)

I guess this is actually a FB bug, but since they haven't fixed it ([since 2012](http://stackoverflow.com/q/11675944/4391952)), and their widely usage, I guess it might be a good idea to fix this here.

**Comment by sebmck** [comment]
That isn't code from Babel. Looks like it's from [core-js](https://github.com/zloirock/core-js). i'd recommend opening an issue over there, thanks!

**Comment by yonatanmn** [comment]
right! sorry
