### ISSUE TITLE
Check for "default export only" does not consider exports added by Plugins

### ISSUE THREAD

**Issue by PSpSynedra** [babel/babel#2199]
When transforming a module that only contains one default export statement like in
```javascript
export default function foo() {
   return 1;
}
```
and a Plugin adds named exports to the AST, the transpiled code will still get a 
```javascript
module.exports = exports['default'];
```
appended by the CommonJSFormatter.transform function.
This hides the exports added by the Plugin.

As far as we could figure it out, this is because the check for exports aside from the default export is done before all the Plugins are run.

**Comment by sebmck** [comment]
Same as/similar to #1777.

**Comment by PSpSynedra** [comment]
We temporariliy fixed it with:
```js
file.moduleFormatter.hasNonDefaultExports = true;
```
