### ISSUE TITLE
Automatic JSDoc-style comments generation

### ISSUE THREAD

**Issue by yuchi** [babel/babel#220]
An idea that came after reading about #174. What about generating the JSDoc-style comments for classes and methods?

This is very provocative, and for sure something hard to maintain. Yet an interesting idea IMHO.

Please note I don’t personally use JSDoc, but I could start using it if it was somehow auto-generated.

I still think that

``` js
/**
 * A Klass
 * @class Klass
 * @extends Parent
 */
class Klass extends Parent {}
```

is a little too verbose. But if `6to5` mangled the code that follows accordingly it could be interesting.

``` js
/** A Klass */ // no need to use @class and @extends here
class Klass extends Parent {}
```

**Comment by yernende** [comment]
According to http://babeljs.io/blog/2015/02/15/not-born-to-die/, project has been redesigned from only translating ES6, so, what about reopening of this issue?

**Comment by sebmck** [comment]
@yernende Bigger things to deal with at the moment. Once the transformer API metioned in #883 is done then these kind of transformers can be pushed out to userland.
