### ISSUE TITLE
Array literals + splats behaves differently

### ISSUE THREAD

**Issue by somebody32** [babel/babel#2204]
Hi! Could you please tell me why this code behaves differently? Looks like the behaviour should be consistent for the both cases?

```javascript

// If these are the same
((x) => x)(1) //=> 1
((...[x]) => x)(1) //=> 1

// Why this is producing empty array on non-iterable arg
const wrongWrap = (x) => [...x]

wrongWrap(1) //=> []
wrongWrap([1, 2]) // => [1, 2]

// And this one is not?
const wrap = (...[x]) => [...x]

wrap(1) //=> [1]
wrap([1, 2]) // => [1, 2]
```

**Comment by zloirock** [comment]
`wrongWrap(1)` - #2160, `wrap(1)` looks like another bug.

**Comment by loganfsmyth** [comment]
As @zloirock said, both of your wrap examples are actually broken. I'd expect both to throw, because you cannot spread a number. The issue he referenced tracks the first issue. The second looks like an issue with the type inference. It's skipping the `_toConsumableArray()` wrapper, which means it must thing that `x` is an array, which is definitely incorrect.

**Comment by jmm** [comment]
In:
```
const wrap = (...[x]) => [...x]
```

What is `(...[x])` supposed to represent? Isn't that a syntax error? Doesn't it need to be `...BindingIdentifier`?

**Comment by loganfsmyth** [comment]
@jmm I swear I checked before I posted, but I think I just misread something. You are totally right, those are syntax errors since http://www.ecma-international.org/ecma-262/6.0/#sec-statements says 

```
BindingRestElement :
    ... BindingIdentifier
```

**Comment by jmm** [comment]
@loganfsmyth Ok, thanks for confirming. Checking this spec is tricky (I speak for myself first and foremost) so I'm glad we can consult each other on it :) I wasn't even sure what the intent of that code is, so that prompted me to take a close look. I guess the idea is something like:

```js
const wrap = (...x) => [].concat(x);
```

**Comment by sebmck** [comment]
I've opened #2207 to track the grammar incompatibility. The current version may indeed be from a prior draft. As for the others, the only thing that's wrong is that spreading non-iterables should throw an error, this is being tracked in #2160.
