### ISSUE TITLE
Better perf debugging

### ISSUE THREAD

**Issue by kittens** [babel/babel#2206]
Would be very useful to add better debugging to the transformer pipeline. Seeing what transforms take the longest, how many traversals are performed in total, how many nodes are visited, average time for a visitor method etc.

cc @amasad @DmitrySoshnikov

**Comment by hzoo** [comment]
@kittens basically did this in https://github.com/babel/babel/pull/3659

we did timing in babili in https://github.com/babel/babili/pull/91
and # visits in https://github.com/babel/babili/pull/93
