### ISSUE TITLE
Spread and extend props for JSX

### ISSUE THREAD

**Issue by timbur** [babel/babel#2209]
Apologies if this is the wrong place to ask about this or if maybe it pertains more to the ES7 proposal or JSX itself or if there's already a discussion on this topic elsewhere.  I'm also about to fall asleep so hopefully this makes sense.

I am expecting to be able to do this:
```js
<SomeComponent { ...props, foo, bar: 'baz' } />
```

But that results in an "unexpected token" error at the first comma.

This works, however:
```js
const someProps = { ...props, foo, bar: 'baz' };
<SomeComponent { ...someProps } />
```

And of course we can always do this:
```js
<SomeComponent {...props} foo={foo} bar="baz" />
```

But I feel the first one helps with conciseness and it would make me a happy camper if it worked.  :)

**Comment by keithamus** [comment]
Im not sure if it is the expected behaviour, but for now you could use this workaround:
```jsx
<SomeComponent { ...{ ...props, foo, bar: 'baz'} } />
```

**Comment by sebmck** [comment]
This is indeed invalid syntax and is not allowed as per the [JSX grammar spec](http://github.com/facebook/jsx). I'd recommend opening an issue over there although it's unlikely to be accepted as it's just adding more ways to do the same thing.
