### ISSUE TITLE
Issue with parsing/transforming a large emscripten file

### ISSUE THREAD

**Issue by cpojer** [babel/babel#2211]
Trying to transform this file https://gist.github.com/cpojer/4697624826b9f99446ca at FB and babel just hangs indefinitely.

If this doesn't repro (and it isn't due to babylon), I can walk you through how this failed at FB :)

**Comment by sebmck** [comment]
I can repro. Confirmed to be a bug in the parser.

**Comment by sebmck** [comment]
Wait nope, not sure what this is.

**Comment by sebmck** [comment]
Don't have time to fully dig into it but parsing it actually finishes, it just takes a long time. It's the result of the `lookahead` in the `parseParenAndDistinguishExpression` method overload in the Flow parser plugin.

**Comment by cpojer** [comment]
I'm not blocked on this, just wanted to track the issue :)

**Comment by sebmck** [comment]
For sure, looks to be a pretty serious bottleneck as the blocking happens multiple times throughout the file. The lookahead is used pretty often so the lag might actually be present in all files parsed and not just that one in particular. Thanks for flagging!

**Comment by mkonicek** [comment]
Not blocked on this either but might have just hit the same issue (on a much larger file). It's good the repro in this task is so small!

**Comment by sebmck** [comment]
I think I might know what's causing it. Might be because there are thousands of tokens that are being stored and on each look ahead it's cloning them. Hopefully that's it as I can easily optimise that.

**Comment by sebmck** [comment]
Yeah this is the cause. The tokens array for the file @cpojer provided gets up to 300,000 tokens and we're constantly cloning it for the lookahead.

**Comment by cpojer** [comment]
Nice!

>

-- 
Christoph Pojer
http://cpojer.net
