### ISSUE TITLE
currentQueue is null in drainQueue

### ISSUE THREAD

**Issue by DanFu9** [babel/babel#2213]
I'm getting an error in Firefox where `currentQueue` is `null` inside of `drainQueue` in `babel-core/browser.js`.  From stepping through the code, there appears to be a race condition between two instances of `drainQueue` running at once.  This is what is happening:

1. `drainQueue` starts the first time: `queueIndex` is -1, `queue` has one item in it
2. `draining` is set to true
3. `setTimeout(cleanUpNextTick)` called
4. `currentQueue` is set to `queue`, `queue` is set to an empty array
5. `queueIndex` compared to length of `queue` and then incremented
6. `currentQueue[queueIndex].run()` called
7. At this point, control goes to the `cleanUpNextTick` scheduled by `drainQueue`
8. `draining` set to false
9. `cleanUpNextTick` sets `queue` to `currentQueue` and calls `drainQueue`, starting a second instance of `drainQueue`
10. `currentQueue` set to a `queue` (which is just what it was before
11. Because `queueIndex` is already `1`, no new functions are run
12. `queueIndex` set to -1
13. `currentQueue` is set to null
14. Second `drainQueue` completes
15. First `drainQueue` regains control
16. `queueIndex` is -1, because of second `drainQueue`
17. `queueIndex` is less than `len`, so `currentQueue[queueIndex].run()` is called
18. Exception because `currentQueue` is null

I've only observed this problem in Firefox, and usually only under very specific conditions (usually only the first time the page is loaded).  We think this is causing problems for us downstream with React and Reflux, so a fix would be greatly appreciated!

**Comment by sebmck** [comment]
What's `currentQueue` and `drainQueue`?

**Comment by DanFu9** [comment]
I'm seeing this file in my `node_modules/babel/node_modules/babel-core` folder.

**Comment by sebmck** [comment]
That code is a part of the the [`process`](https://github.com/defunctzombie/node-process/blob/master/browser.js) package which browserify uses to shim the node `process` variable in a browser environment. I'd recommend reporting this over there as there's nothing that can really be done on the Babel side and it's not specific to anything Babel is doing. Thanks! :blush:

**Comment by DanFu9** [comment]
Thanks!
