### ISSUE TITLE
.babelrc cascade

### ISSUE THREAD

**Issue by dominicbarnes** [babel/babel#2214]
I'm having trouble with the cascading of `.babelrc` files when determining the config for a specific file. It is working as-designed right now, and I'm not sure if I'm the only one who's had trouble here.

I'm working on duo-babel, and I'm trying to handle differing `jsxPragma` options throughout many different projects. Until recently, just about everyone used the same pragma, however this is starting to change. It is making sharing/distributing these modules problematic, as all the modules in a build must agree on the exact same pragma.

I started looking into using `.babelrc` files to manage these variations. It turns out this works, but it's easily broken.

Due to how babel resolves configs, the config that is _furthest_ away is what is used. This is confusing, because usually the **closest** config is the one you want reflected. For example:

```
 - $HOME/project/index.js
 - $HOME/project/.babelrc (jsxPragma: "element")
 - $HOME/.babelrc (jsxPragma: "dom")
```

When processing `index.js`, the pragma will be `dom`, despite the fact that the intention is that the project wants to use `element`. I suspect many people using babel are also using React, so this particular scenario is not a problem for them. However, I think we can find a way to make this work without disrupting everyone else.

My proposal is to make the `jsxPragma` option "first-come, first-served". In other words, if a value has already been detected, it should not be overwritten. This has the benefit of accomplishing exactly what duo users need, while not needing to flip the current config cascade upside down. (as people probably already depend on the order it resolves things currently)

**Comment by grabbou** [comment]
Usually is a key word here, in e.g. React Native case, this is useful to `overwrite` .babelrc shipped with the library with your own configs.

**Comment by dominicbarnes** [comment]
@grabbou Yeah, I can see the utility in that, but sometimes (as in this case) overwriting the config can actually _break_ attempts at consuming the library.

The current approach precludes the possibility for multiple values to exist, making it impossible to get around. I would be fine with _only_ changing the behavior for `jsxPragma`, since that's the only config I currently forsee needing this change.

**Comment by grabbou** [comment]
Yeah, I have nothing against it. Just wanted to add in my few cents to the discussion with alternative point of view :)

**Comment by dominicbarnes** [comment]
Thanks @grabbou ! :D

**Comment by sebmck** [comment]
Behaviour in 6.0 is being changed to be inline with common tools. The closest config is used and the directory traversal upwards is stopped. If you want to inherit then you need to be explicit with an `extends` option.
