### ISSUE TITLE
Possibly preserve newlines in JSX transformer

### ISSUE THREAD

**Issue by novacrazy** [babel/babel#2219]
I recently decided to add some Markdown support to my application, and in the [React.js tutorial](https://facebook.github.io/react/docs/tutorial.html#adding-markdown), it mentions integrating [chjj/marked](https://github.com/chjj/marked) into components in a way that can transform text-only children as markdown. The only problem with this is that Babel currently strips newlines from text children.

For example, I have this component:
```javascript
import React from 'react';
import marked from 'marked';

class Markdown extends React.Component {
    render() {
        let {children} = this.props;

        let markup = marked( children.toString(), {smartypants: true, sanitize: true, breaks: true} );

        return (
            <div dangerouslySetInnerHTML={{__html: markup}}/>
        );
    }
}
```

And when used like this:
```
class MyComponent extends React.Component {
    render() {
        return (
            <Markdown>
                 Testing Header
                 ==============
            </Markdown>
        );
    }
}
```

The string that is passed to `marked` is `"Testing Header =============="`, which is parsed incorrectly because there it is not "below" the header. It's basically restricted to one-line markdown statements. Things like tables, headers, horizontal rules and so forth fail to render because there are no newlines.

Would it be possible to add an option to leave the newlines in?

**Comment by sebmck** [comment]
This is how JSX is parsed, the whitespace handling is based on how browsers parse HTML/XML and Babel isn't going to be more lenient in how it treats it. A more appropriate way to do what you want is through the use of [template strings](https://babeljs.io/docs/learn-es2015/#template-strings).

**Comment by novacrazy** [comment]
I just made a pseudo- require hook that will load in Markdown files and create functions that return the text as already processed HTML, then used `dangerouslySetInnerHTML` from there. Fun stuff.
