### ISSUE TITLE
Class functions `this` not bound when using multiple default params

### ISSUE THREAD

**Issue by wonnage** [babel/babel#2222]
Compare these two code samples:
[with a random this reference](http://bit.ly/1IYh2oc)
[without random this reference](http://bit.ly/1NoUQH4)

The generated code is missing the `.apply(this, arguments)` wrapper unless you happen to touch 'this', which is surprising.

**Comment by sebmck** [comment]
This doesn't make a difference and is deliberate as it doesn't have to bound like this unless `this` or `arguments` is touched.

**Comment by wonnage** [comment]
It definitely makes a difference - the inner function's `this` changes depending on whether the outer one referenced it.

**Comment by wonnage** [comment]
Seems somehow related to whether multiple default arguments are passed. See this example: http://bit.ly/1Nrqfc5

**Comment by jridgewell** [comment]
I can confirm. It's due to the `params2 = params` creating a new scope.
