### ISSUE TITLE
[Question] Is there any approach to inject or ignore global variables?

### ISSUE THREAD

**Issue by chentsulin** [babel/babel#2223]
There is a `__DEVTOOLS__` global variable in my source code. And I use webpack DefinePlugin to define it as boolean value.

```
new webpack.DefinePlugin({
    __DEVTOOLS__: true
})
```

But in my mocha test I only want to use `babel/register` and don't want to use wepack in my test. Is there any approach to inject global variables just like webpack DefinePlugin or at least ignore the global variables when it compile?

**Comment by sebmck** [comment]
Hi @chentsulin, As per the [README](http://github.com/babel/babel#readme), the Babel issue tracker is only for bug reports and feature requests:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:
