### ISSUE TITLE
Online Babel Repl console and output panel scroll overlap

### ISSUE THREAD

**Issue by bendtherules** [babel/babel#2224]
Open this [Repl with code]( http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20o%20%3D%20%5B1%2C2%2C3%5D%2C%0D%0A%20%20%20%20a%2C%20b%2C%20c%2C%20p%3B%0D%0A%0D%0Ap%20%3D%20%5B%20a%2C%20b%2C%20c%20%5D%20%3D%20o%3B%0D%0A%0D%0Aconsole.log(%20p%20)%3B%20%20%20%20%20%20%20%20%20%2F%2F%201%202%203%0D%0Aconsole.log(p%20%3D%3D%3D%20o)%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20true ) and see the first console.log output overlap with the output js panel scrollbars.

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
