### ISSUE TITLE
Preserve new lines in the single-line block statements without curly braces

### ISSUE THREAD

**Issue by inikulin** [babel/babel#2226]
E.g.:

``` js
if(foo) 
 bar();
else if(bar)
 baz();
else
 qux();
```

will be transpilled to:

``` js
if (foo) bar();else if (bar) baz();else qux();
```

It makes code unusable for the debugging purposes without source maps. Is this intended behavior? Or am I missing some options?

**Comment by Mark-Simulacrum** [comment]
Try using the `retainLines` option (`--retain-lines` on the CLI). For more information, see http://babeljs.io/docs/usage/options/.

**Comment by inikulin** [comment]
`retainLines` in general leads to the messy formatting, so it's not an option either

**Comment by hzoo** [comment]
Closing out some stale issues. At this point we would have to check the source code to retain previous newlines - I would suggest sourcemaps (which you aren't using), retainLines (which has issues), or even using recast as the parser/generator to retain formatting.

Example at https://babeljs.io/blog/2016/09/28/6.16.0#new-feature

```js
{
  "parserOpts": {
    "parser": "recast"
  },
  "generatorOpts": {
    "generator": "recast"
  }
}
```
