### ISSUE TITLE
Should --module-id respect module-root?

### ISSUE THREAD

**Issue by bradleypriest** [babel/babel#2227]
Currently if you provide a `--module-id` it completely ignores the `--module-root` option.

Given this file
`foo.js`
```es6
export function foo() {
  return 'bar';
}
```

`babel foo.js --modules amd --module-ids --module-root=baz`
returns
```js
define("baz/foo", ["exports"], function (exports) { 
...
```

`babel foo.js --modules amd --module-ids --module-root=baz --module-id=foo2`
returns
```js
define("foo2", ["exports"], function (exports) { 
...
```

I know this is pretty edge-case, but I was expecting the second one to return `baz/foo2`

Happy to put a patch together if so, WDYT?

**Comment by sebmck** [comment]
If you set the `moduleId` option and didn't want your `moduleRoot` how would this work? Seems unnecessarily inflexible and this would be a breaking change requiring a major version bump.

**Comment by bradleypriest** [comment]
I guess that was the question, there's definitely merits both ways, this didn't seem to me to follow the principle of least surprise.

If it's intentional it's easy enough to work around.

**Comment by sebmck** [comment]
Closing this as it's expected and intentional behaviour. Thanks! :blush:
