### ISSUE TITLE
Reassigning the local name of a default export assigns named export

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2228]
Was reading through http://www.2ality.com/2015/07/es6-module-exports.html and realized that reassigning the id of a default exported hoistable declaration or class actually updates the default export (cool!). I noticed however that it looks like the binding update code isn't updating the proper export.

```
export default class Foo {}
Foo = null;
```

generates

```
var Foo = function Foo() {
  _classCallCheck(this, Foo);
};

exports["default"] = Foo;

exports.Foo = Foo = null;
```

rather than the expected

```
var Foo = function Foo() {
  _classCallCheck(this, Foo);
};

exports["default"] = Foo;

exports["default"] = Foo = null;
```

**Comment by nicolo-ribaudo** [comment]
This works using Babel 7: http://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAYhBHAN4C-AUGRQLxwB2WmA3EA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&prettier=false&targets=&version=6.26.0
