### ISSUE TITLE
unreachable code after return statement in line 63812 browser.js

### ISSUE THREAD

**Issue by liangzai-cool** [babel/babel#2231]
please see this:

![qq 20150820132016](https://cloud.githubusercontent.com/assets/6807169/9376344/3a9e04e8-473e-11e5-935f-410f9a01fb69.png)

and my question is: can this code be removed?
thanks!

**Comment by sebmck** [comment]
That's a line in the [`to-fast-properties`](https://github.com/sindresorhus/to-fast-properties) package. It's there in order to trick V8 into deoptimising the function.
