### ISSUE TITLE
Reduce browser bundles size

### ISSUE THREAD

**Issue by zloirock** [babel/babel#2232]
Current size `browser-polyfill.min.js` ~80kb. Possible serious reduce it. Browserify, by default, saves modules path, it's not required.

Full shim version of `core-js` with `browserify` (w/o `bundle-collapser`) - 65kb, with `webpack` - 43kb.

Possible use `webpack` or add `bundle-collapser`.

I think, possible do the same with `browser.js`.

**Comment by zertosh** [comment]
Running `bundle-collapser` while `source-map` still depends on `amdefine` breaks the browser bundle. https://github.com/mozilla/source-map/pull/205 removes amdefine, now that it's merged, once it's published, and babel updates to it, we can do all sorts of nice things to bundles.

**Comment by zloirock** [comment]
[In `babel` 6 added `bundle-collapser` and `mangle` option to build process](https://github.com/babel/babel/blob/v6.1.1/packages/babel-polyfill/scripts/build-dist.sh#L11-L16).

**Comment by zertosh** [comment]
And it was in the last release of 5.x https://github.com/babel/babel/pull/2425
