### ISSUE TITLE
can i use babel to refer to external scripts?

### ISSUE THREAD

**Issue by liangzai-cool** [babel/babel#2233]
i write bellow:
```js
<script src="babel-core/browser.js" type="text/javascript"></script>
<script src="demo.js" type="text/babel"></script>
```
it can run, but just like es6, it means babel does translate the script to es5.

thanks!

**Comment by jmm** [comment]
Hi @liangzai-cool, thanks for your interest in Babel :smiley: I'm not sure if you have a question or if you're suggesting a documentation update. At any rate, this isn't a good fit for this issue tracker. Per the README:
>   For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

If this is a request to update the documentation, please see the Babel website repo: https://github.com/babel/babel.github.io

Thanks!
