### ISSUE TITLE
[repl] console.log(+undefined) is evaluated to null

### ISSUE THREAD

**Issue by kyldvs** [babel/babel#2237]
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=true&code=console.log(%2Bundefined)%3B%0A

**Comment by kyldvs** [comment]
I guess it's just console.log(NaN), not really anything to do with the conversion from undefined.

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by sebmck** [comment]
Also duplicate of #1231, #1373 and babel/babel.github.io#330. This is currently being tracked in babel/babel.github.io#172.
