### ISSUE TITLE
The require statement "core-js/library/fn/symbol" doesn't intuitively relate to anything in core-js

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [babel/babel#2239]
I'm trying to make use of babel-runtime with SystemJS, I've had to add the following mappings in it's config.js so that the imports make sense:

```json
    "babel-runtime/core-js/object/*": "node_modules/babel-runtime/core-js/object/*.js",
    "babel-runtime/regenerator" : "node_modules/babel-runtime/regenerator/index.js",
    "babel-runtime/core-js/*" : "node_modules/babel-runtime/core-js/*.js",
    "core-js/library/fn/symbol/*" : "node_modules/core-js/library/fn/symbol/*.js",
    "core-js/library/fn/object/*" : "node_modules/core-js/library/fn/object/*.js",
    "core-js/library/fn/*" : "node_modules/core-js/library/fn/*.js",
    "core-js/library/fn/symbol" : "node_modules/core-js/library/es6/symbol.js",
```

As you can see I mapped the last one to the es6 folder

```json
    "core-js/library/fn/symbol" : "node_modules/core-js/library/es6/symbol.js"
```

I would expect it to map to "library/fn/symbol.js" in core-js, but there is no such file.

Is what I did even right? It seems to work...

**Comment by zloirock** [comment]
?

**Comment by marthinus-engelbrecht** [comment]
Sorry, did in accidental post there.

**Comment by zloirock** [comment]
> I would expect it to map to `"library/fn/symbol.js"` in core-js, but there is no such file.

It should be maped to `"library/fn/symbol/index.js"`. Now it's equal `"library/es6/symbol.js"`, but it can be changed in the future - for example, additional symbols in ES7.

**Comment by marthinus-engelbrecht** [comment]
Thanks, that makes sense.
