### ISSUE TITLE
Reflect.construct does not work because of _classCallCheck

### ISSUE THREAD

**Issue by mariusGundersen** [babel/babel#2240]
It seems that the generated `_classCallCheck` prevents [Reflect.construct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct) from working. Here is a short example that throws an exception in the babel REPL:

```js
class One{}
class Two{}

Reflect.construct(One, [], Two);
```

**Comment by zloirock** [comment]
1. Yes, `_classCallCheck` is not correct way of detection calling internal `[[Construct]]` method, but I don't see any alternatives.
2. Anyway, `Reflect.construct` can't be completely polyfilled with 3 arguments in ES5 - the third argument should set `new.target` (BTW, I still didn't add fix for MS Edge which support only 2 arguments :).

With these limitations I don't think usage `Reflect.construct` with 3 arguments is a good idea w/o native classes and correct native `Reflect.construct`.

**Comment by mariusGundersen** [comment]
`new.target` can be faked using `this.constructor`, since in ES5 we can use `this` before calling `super`. So `Reflect.construct` could call the constructor (using `apply`) with an object where the constructor is the third parameter. 

`_classCallCheck` is there to ensure that the class has been called with `new`, right? If it is called as a normal function (without `new`) then `this` will be `window` or `null` (in a module), so couldn't that be the check in `_classCallCheck`? Sure, I don't see any way to differentiate between using `call`, `apply` or `Reflect.construct`.

**Comment by zloirock** [comment]
> `new.target` can be faked using `this.constructor`, since in ES5 we can use `this` before calling `super`. 

For many reason - can't, it's not equal.

> So `Reflect.construct` could call the constructor (using apply) with an object where the constructor is the third parameter.

https://github.com/zloirock/core-js/blob/master/modules/es6.reflect.construct.js#L26-L30 and it's not support native classes / constructors with different `[[Call]]` / `[[Construct]]`.

Also, see native FF `Reflect.construct` implementation - it supports `new.target`, but result isn't instance `new.target`.

> then `this` will be `window` or `null` (in a module)

~~`null`~~ `undefined`

**Comment by mariusGundersen** [comment]
Ok, I realize that we can't get it work 100%, I'm just trying to find the largest subset of features that we can get to work. So native classes/constructors I understand cannot be made to work (not with `extends` either). 

If the third argument isn't supported (and sorry if I should have made this issue in core-js), should `Reflect.construct` maybe throw an exception to indicate that it isn't supported?

**Comment by zloirock** [comment]
It's not only `core-js` issue - in your example with 3 arguments `core-js` works correct in most environments, problem in `_classCallCheck`. I don't see any reason throw an exception with 3 arguments - need add fix for environments where the third argument isn't supported (and explore FF problem before), but it will not be  full support.

I just said that usage `Reflect.construct` with 3 arguments currently is not a very good idea :)

**Comment by sebmck** [comment]
It's impossible to get around this. The same problem exists when you try and inherit from a native class from a transpiled one. I'd recommend blacklisting `es6.classes` for these environments.
