### ISSUE TITLE
runtime using unwrapped Object in core-js

### ISSUE THREAD

**Issue by staaky** [babel/babel#2241]
When transpiling code that uses `Object.assign` babel adds a require when using  `optional: ['runtime']`:

```
require('babel-runtime/core-js/object/assign')
```

Which in turn requires `$.js` from core-js:

```
var $Object = Object;
module.exports = {
  create:     $Object.create,
  getProto:   $Object.getPrototypeOf,
  isEnum:     {}.propertyIsEnumerable,
  getDesc:    $Object.getOwnPropertyDescriptor,
  setDesc:    $Object.defineProperty,
  setDescs:   $Object.defineProperties,
  getKeys:    $Object.keys,
  getNames:   $Object.getOwnPropertyNames,
  getSymbols: $Object.getOwnPropertySymbols,
  each:       [].forEach
};
```

It assumes things like `Object.keys` exist, so it errors out in IE8 and below.

Switching from runtime to polyfill works since it defines everything globally. The docs make it seem like the runtime and polyfill are interchangeable. Shouldn't `Object` have a wrapper in core-js to make that possible or am I missing something?

**Comment by zloirock** [comment]
What to say... Current `runtime` transformer not support ES3 environment. `core-js` contains ES5 polyfills, but `runtime` transformer not injects them. For most peoples it's not required and adds additional size.

**Comment by staaky** [comment]
Maybe a note in the docs about IE8 requiring the polyfill could do for now? Until a plugin becomes available. The [technical details](http://babeljs.io/docs/usage/runtime/) mention ES6 methods being mapped by the runtime, so you might expect `Object.assign` to work, but it uses ES5 internally.

**Comment by loganfsmyth** [comment]
@staaky Feel free to file an issue in https://github.com/babel/babel.github.io if you have specific suggestions for documentation improvements.
