### ISSUE TITLE
`this` is undefined when calling function through processor.nextTick()

### ISSUE THREAD

**Issue by CGavrila** [babel/babel#2243]
I am using Babel version 5.8.21 and Node v0.12.7.

First of all, I've never used ES6 or Babel before today, so I keep thinking that I might be doing something wrong. I'm not even sure if this is an issue with Babel, Node or something else.

Here is a reproducible test case:
```
'use strict';

class SomeClass {
  constructor() {
    this.someString = 'some text';
  }

  start() {
    process.nextTick(this._processNextInQueue);
  }

  _processNextInQueue() {
    console.log(this.someString);
  }
}

var someClass = new SomeClass();
someClass.start();
```

I am transpiling this by running:
```
$ babel test_es6.js --out-file test_es5.js
```

And then I get:
```
$ node test_es5.js 
/home/cgavrila/node/babel-issue/test_es5.js:22
      console.log(this.someString);
                      ^
TypeError: Cannot read property 'someString' of undefined
    at _processNextInQueue (/home/cgavrila/node/babel-issue/test_es5.js:22:23)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

However, if I remove the `process.nextTick()` in `start()` and simply call the function normally, then the error does not occur. 

Is there some scoping rule that I fail to respect?

**Comment by Mark-Simulacrum** [comment]
JavaScript does not carry the `this` special variable through in your case. This makes `process.nextTick(this._processNextInQueue)` call the `_processNextInQueue` function with a `undefined` `this` value.

You can overcome this by using `.bind` like this: `process.nextTick(this._processNextInQueue.bind(this))`.

**Comment by fkling** [comment]
This has nothing to do with Babel or ES6. Please have a look at http://stackoverflow.com/q/20279484/218196.

**Comment by CGavrila** [comment]
My bad. Thanks, guys!

**Comment by jmm** [comment]
Hi @CGavrila, welcome to the Babel community! For future questions like these please check out the resources listed in the `README`:
>  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
