### ISSUE TITLE
Default Value Expressions works wrong

### ISSUE THREAD

**Issue by DmitryAuine** [babel/babel#2244]
var w = 1, z = 2;

function foo( x = w + 1, y = x + 1, z = z + 1 ) {
    console.log( x, y, z );
}

foo(); //undefine but as es6 it needs to throw ReferenceError (TDZ)     

"
It's a subtle detail, but the formal parameters in a function declaration are in their own scope (think of it as a scope bubble wrapped around just the ( .. ) of the function declaration), not in the function body's scope. That means a reference to an identifier in a default value expression first matches the formal parameters' scope before looking to an outer scope. See the Scope & Closures title of this series for more information.

...

The w in the w + 1 default value expression looks for w in the formal parameters' scope, but does not find it, so the outer scope's w is used. Next, The x in the x + 1 default value expression finds x in the formal parameters' scope, and luckily x has already been initialized, so the assignment to y works fine.

However, the z in z + 1 finds z as a not-yet-initialized-at-that-moment parameter variable, so it never tries to find the z from the outer scope.

As we mentioned in the "let Declarations" section earlier in this chapter, ES6 has a TDZ, which prevents a variable from being accessed in its uninitialized state. As such, the z + 1 default value expression throws a TDZ ReferenceError error.
"
From: https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md#default-value-expressions

**Comment by loganfsmyth** [comment]
TDZ can only be determined at runtime, and as such introduces a runtime hit to performance. Babel supports TDZ but it must be explicitly enabled using the `es6.spec.blockScoping` transform. Your code fails as expected when that has been enabled.

http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&playground=false&code=var%20w%20%3D%201%2C%20z%20%3D%202%3B%0A%0Afunction%20foo(%20x%20%3D%20w%20%2B%201%2C%20y%20%3D%20x%20%2B%201%2C%20z%20%3D%20z%20%2B%201%20)%20%7B%0Aconsole.log(%20x%2C%20y%2C%20z%20)%3B%0A%7D%0A%0Afoo()%3B%20
