### ISSUE TITLE
Why `func || (..args) => {...}` not compile?

### ISSUE THREAD

**Issue by lijunle** [babel/babel#2245]
Not compile:

```js
const a = a || (...args) => {
  console.log(args);
}
```

Error message:

```
repl: Unexpected token (1:16)
> 1 | const a = a || (...args) => {
    |                 ^
  2 |   console.log(args);
  3 | }
```

I use this as a workaround:

```js
const a = a ? a : (...args) => {
  console.log(args);
}
```

**Comment by loganfsmyth** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
