### ISSUE TITLE
Automatically transpile things in node_modules if they contain a .babelrc

### ISSUE THREAD

**Issue by ashaffer** [babel/babel#2246]
Possibly only with an explicit option set, e.g. `{library: true}`.  This would allow people to start writing es6 libraries without the rather ugly step of having to build a release file, and not add too much weight to the compilation process.

If worried about this breaking backwards compatibility, or being undesirable for people writing large libraries who still want to build a release, the explicit flag would solve that problem.

**Comment by eventualbuddha** [comment]
This is sort of similar to the [`jsnext:main`](https://github.com/rollup/rollup/wiki/jsnext:main) field that other and I are attempting to push for. At the moment it's mainly being used so [rollup](https://github.com/rollup/rollup) can find the original source for libraries and correctly include only the things that are used, but in theory it could be used for this purpose as well.

**Comment by sebmck** [comment]
What do you mean by automatically transpile? What integration are you using? Babel compiles whatever you throw at it and it's only the specific integrations that have opinions on what is and what isn't compiled.

**Comment by ashaffer** [comment]
@sebmck I was using [babel-tape-runner](https://github.com/wavded/babel-tape-runner) in this particular case but that is just doing a `require('babel/register')`.

I know babel will compile my node_modules if I tell it not to ignore them, but won't it then try to compile *all* of my node_modules?  Which I don't want, because it'd be very slow, but I also don't want to have to specify each module to compile in the top-level module, I want the modules themselves to be able to indicate to babel that they should be compiled.

Sorry if i'm just misunderstanding and this already exists.

**Comment by timoxley** [comment]
Anything in `node_modules` should already be compiled (e.g. via prepublish script). If it's not, that's a bug with the package.

**Comment by ashaffer** [comment]
@timoxley I do understand that that is the current message.  I am proposing that it be changed, on an opt-in (perhaps by both the libraries and the thing calling babel) basis.

**Comment by sebmck** [comment]
@ashaffer `babel/register` already has the ability to require files from `node_modules`, see the [docs](https://babeljs.io/docs/usage/require/#usage) for instructions on how to include them. You can then use the `ignore` and `only` options to filter the files that you want, see the [option docs](https://babeljs.io/docs/usage/options/) for that.

Publishing uncompiled Babel code to npm is not a pattern that we want to encourage so it's unlikely that such support will be added. You can write your own require hook though if you want, the code for the current one is located [here](https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js). Thanks! :blush:

**Comment by ja-be** [comment]
I think that may be it will be a nice feature if you are linking your modules with npm link...I can't figured out how to config ```only``` option with nested modules yet
