### ISSUE TITLE
[BUG] Babylon fails parsing a valid template string.

### ISSUE THREAD

**Issue by trusktr** [babel/babel#2249]
In [this file](http://hastebin.com/usifabaxuv), on line 41, i get the following error: http://hastebin.com/raw/imemitemur. This is with babel/babylon version `5.8.22`.

**Comment by hzoo** [comment]
Looks like you're minimal case would be ``` `${/**/}` ``` - a comment in the template expression with nothing else? ``` `${}` ``` will error as well

**Comment by loganfsmyth** [comment]
Definitely seems like invalid syntax to me.

**Comment by fkling** [comment]
What makes you think the literal is valid? Only expressions are valid inside `${}`. A comment is not an expression. Spec: http://www.ecma-international.org/ecma-262/6.0/#sec-template-literals, http://www.ecma-international.org/ecma-262/6.0/#sec-template-literal-lexical-components

**Comment by trusktr** [comment]
@fkling @loganfsmyth @hzoo This used to work before. Here's the same code running, compiled with 6to5: http://trusktr.io. It takes a while to load because everything's compiled in the browser, but it works.

It's been a while since I wrote this code (hence 6to5), and I am now updating to Babel, etc, and came across this.

Maybe the spec changed? Or was 6to5 just doing it's own thing?

**Comment by sebmck** [comment]
I'm getting the same error using 6to5.

```bash
$ 6to5 test.js
SyntaxError: test.js: Unexpected token (5:17)
  3  |     ${/*<li class="sub menuitem">
  4  |         <a href="/hello">about me</a>
> 5  |     </li><br />*/}
     |                  ^
  6  |     <li class="sub menuitem frame">
  7  |         <a target="_blank" href="/mom2015">3D Mother's Day 2015</a>
  8  |     </li><br />
```

This is expected behaviour anyway, as @fkling said you need to have an expression inside of `${}`.

**Comment by trusktr** [comment]
@sebmck How about with `6to5@~3.3.2`?

**Comment by sebmck** [comment]
Doesn't really matter what the old behaviour was, it's not valid now.
