### ISSUE TITLE
Experimental in combination with whitelist

### ISSUE THREAD

**Issue by KnisterPeter** [babel/babel#2250]
When enabling experimental features (e.g. stage 0) at the same time as whitelisting only a few transforms, then the parser complains about features from stage 0 which are not whitelisted.

I would like to parse valid es7 code and only transform es6.modules. This is currently not possible with babel.

My expectation was that enabling stage 0 enables the parser and whitelisting filters the transforms. Currently this seem to be tangled too much.

**Comment by sebmck** [comment]
It's not currently possible to enable parsing of ES7 while not transforming it. This is a deliberate decision as there isn't really any usecase (I'd be interested to hear yours) for doing this as no engines support it. Thanks! :blush:

**Comment by KnisterPeter** [comment]
We build a tool which does some preprocessing of sources (https://github.com/sinnerschrader/patternplate).
In this case developers produce code fragments (called patterns) which could be of any ES-specification. But for the tool-internal dependency resolution we need to hook into the require mechanism (which is not possible with es6-modules since there are no hooks, imho). Therefore I would like to parse stage-0 but transform only es6-modules. The resulting code would be as close as possible to the original pattern code but we could hook into it.

In the final compilation result the pattern code would be transformed to a project specific target (e.g. es5).
