### ISSUE TITLE
Using babel to compile and run mocha tests when certain es7 features such as class properties have been enabled

### ISSUE THREAD

**Issue by ifyio** [babel/babel#2251]
I would like to use babel to compile mocha tests when es7 class properties as well as other es7 features have been enabled. How do I do this? How can I turn on additional options when doing...

```js
{
  "scripts": {
    "test": "mocha --compilers js:babel/register"
  }
}
```

**Comment by hzoo** [comment]
Have you tried using a `.babelrc` file? http://babeljs.io/docs/usage/babelrc/

**Comment by sebmck** [comment]
The Babel issue tracker is not for questions. Please see the [README](https://github.com/babel/babel#readme):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:
