### ISSUE TITLE
Babel should detect duplicate declarations properly when mixing let/const and var's

### ISSUE THREAD

**Issue by olov** [babel/babel#2252]
Thanks for Babel. I'd love for Babel to be a superset of defs.js so I can deprecate defs eventually. For that reason, I'm going through the defs test suite and will open up issues (for bugs and improvement) as I find them.

```js
~/projects/defs.js/tests % cat var-inside-let.js
"use strict";

// all three var x|y|z = 4 should be errors I believe so we error on all
//   v8 --harmony allows the first but not the second and last (2015-08-24: this has now been fixed in v8 so all errors)

if (true) {
    let x = 3;
    if (true) {
        var x = 4;
    }
}

let y = 3;
if (true) {
    var y = 4;
}

(function() {
    if (true) {
        let z = 3;
        if (true) {
            var z = 4;
        }
    }
})();
```

Babel should error on all three redeclaration, here you can see the output from defs.js.
```
~/projects/defs.js/tests % cat var-inside-let-stderr
line 9: x is already declared
line 15: y is already declared
line 22: z is already declared
```

However, Babel only errors on the middle one `TypeError: var-inside-let-copy.js: Line 15: Duplicate declaration "y"`

**Comment by sebmck** [comment]
Do you have any spec references?

**Comment by olov** [comment]
Last note on 15.1.8 https://people.mozilla.org/~jorendorff/es6-draft.html#sec-globaldeclarationinstantiation and then follow along to 15.1.1 https://people.mozilla.org/~jorendorff/es6-draft.html#sec-scripts-static-semantics-early-errors

**Comment by jmm** [comment]
@olov Spec references can now be made to [Standard ECMA-262 6th Edition / June 2015](http://www.ecma-international.org/ecma-262/6.0/) :smiley:

**Comment by sebmck** [comment]
Added this TDZ support in the `development branch due out for Babel 6.
