### ISSUE TITLE
Should detect reference used before declaration when used in same declaration

### ISSUE THREAD

**Issue by olov** [babel/babel#2253]
Another one from the defs test suite:

```js
~/projects/defs.js/tests % cat used-in-same-declaration.js
"use strict";
let x = x; // error
let y = 1, z = y; // ok
let a = b, b = 1; // error
```

Babel doesn't complain about this currently but should error something similar to
```
line 2: x is referenced before its declaration
line 4: b is referenced before its declaration
```

**Comment by zloirock** [comment]
Use `es6.spec.blockScoping` transformer, [your example](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&code=let%20x%20%3D%20x%3B%20%2F%2F%20error%0D%0Alet%20y%20%3D%201%2C%20z%20%3D%20y%3B%20%2F%2F%20ok%0D%0Alet%20a%20%3D%20b%2C%20b%20%3D%201%3B%20%2F%2F%20error&playground=true).

**Comment by olov** [comment]
Babel should be able to detect this test case with static analysis with no run-time cost (or analysis cost to speak of), just like defs. @sebmck do you agree with closing this issue? I wasn't half way through the defs test suite but I'm holding off opening new Babel issues until I know it's not a waste of work.

**Comment by passy** [comment]
> Babel should be able to detect this test case with static analysis with no run-time cost

Agreed. For obvious cases like this it would be great to get some more compile-time safety.

**Comment by olov** [comment]
Given the discussion on Twitter, is this issue still a dupe of another one and/or can it be reopened (pending any actions maybe)?

**Comment by sebmck** [comment]
@olov It's the exact same issue as #2254 (TDZ) which is itself a subset of #961 which I've since added with commit 171ba75140c645abf7d2ed5019066959ab762e3a. Thanks for the report! Finally got me to put in the dev time to support this more thoroughly.

**Comment by olov** [comment]
Thanks!
