### ISSUE TITLE
Babel should detect and error on use before definition

### ISSUE THREAD

**Issue by olov** [babel/babel#2254]
Another defs.js test:

```js
~/projects/defs.js/tests % cat use-before-definition.js
"use strict";

x; // error (unless disallowUnknownReferences=false)
if (true) {
    x; // error
    if (true) {
        x; // error
    }
    if (true) {
        let x;
        x; // ok
    }
    let f = function() {
        return x; // ok
    };
    f(); // ok from a static analysis standpoint but runtime error in ES6

    let x = 3;

    f(); // ok
    x; // ok
    if (true) {
        x; // ok
    }
}
```

Defs gives these errors.
```
line 3: reference to unknown global variable x
line 5: x is referenced before its declaration
line 7: x is referenced before its declaration
```

Babel produces no errors but probably should produce errors for line 5 and 7.

**Comment by sebmck** [comment]
What heuristic are you using in defs?

**Comment by olov** [comment]
I'm sorry, I pasted in the Babel output rather than the input file in the issue. I've updated it now.

**Comment by sebmck** [comment]
I meant what rules are you using to determine whether or not a reference is in TDZ?

**Comment by olov** [comment]
If the reference is inside a lambda (i.e. further lambda'ed than the declaration block) then I don't care to do further analysis because it might be a valid use or it might be a use before initialization and even though it's possible to take it further with static analysis, in many cases it will of course be impossible to statically prove whether it's ok or not. So I skip it. So line 14 (`return x`) is ok.

But if it's not, then it's just a matter of looking at the positional place. There is no way line 5 or 7 can occur after the line further down with `let x = 3` so the friendly thing to do for the user is to produce a static error. In defs every declaration has a `from` property (https://github.com/olov/defs/blob/3579c833fa100b13f8413fcddaf21b68eb9b78d3/scope.js#L104) and every reference is then checked against it (https://github.com/olov/defs/blob/3579c833fa100b13f8413fcddaf21b68eb9b78d3/defs-main.js#L229).

**Comment by sebmck** [comment]
Good call, thanks for the info! This is a subset of #961 so I'm merging it into there.

**Comment by olov** [comment]
Excellent, thanks!
