### ISSUE TITLE
babel build-dist.sh failing on browser.js in Linux environment 

### ISSUE THREAD

**Issue by sethcall** [babel/babel#2255]
On Linux, babel/packages/babel/scripts/build-dist.sh fails when running uglifyjs on browser.js.  

This change introduced this problem:

https://github.com/babel/babel/commit/beaff831d2c4b6c499581c6587e73999a5c18494#diff-729e8ddea0774d4b82a61a79615d6a9e

I believe this error got through because build-dist.sh still works on MacOSX. It's in a Linux environment where this fails.

If curious, I was made aware of this as a user of ruby-babel-transpiler, which uses build-dist.sh in it's travis scripts.  (you can see the build error here: https://travis-ci.org/babel/ruby-babel-transpiler/jobs/74334612#L1055)

**Comment by jmm** [comment]
@sethcall Welcome to the Babel community and thanks for the report! Confirmed, also failing here (Ubuntu linux). The problem, for me, is that it is writing the literal sequence `\xEF\xBB\xBF` to the file. A reduced test case that fails for me is to create the following:

`build-dist.sh`
```sh
#!/bin/sh
printf '\xEF\xBB\xBF' > dist/browser.js
```

```sh
$ ./build-dist.sh
```

Either of the following makes it work for me:

```sh
$ bash ./build-dist.sh
```

or 

```sh
env printf '\xEF\xBB\xBF' > dist/browser.js
```

I'm not too familiar with the `env` usage. Got the idea from here: http://www.gnu.org/software/coreutils/manual/html_node/printf-invocation.html#printf-invocation. Also discussed here: http://stackoverflow.com/a/12691550/1034448

I wonder though if the best solution is to just create a file containing the BOM and `cat` it with the other output....

**Comment by sethcall** [comment]
Hi jmm, thanks for looking at this. 

Your links got me here: http://stackoverflow.com/questions/28544423/unicode-characters-in-bin-sh-vs-bin-bash

I'm thinking then that this is a sh vs bash vs dash issue.   On Ubuntu 12, /bin/sh is a sym link to /bin/dash.    But but running bash explicitly, you hit a different printf.  

If I had to vote, I like the *env printf* with a comment explaining that printf in shells that are not bash 4.2 and above might not behave the way you expect.

**Comment by jmm** [comment]
@sethcall Thanks for the link; that seems to focus on the `\u` escapes though, so I think it's slightly different from this issue.

> I'm thinking then that this is a sh vs bash vs dash issue.

Yeah, agreed.

> If I had to vote, I like the *env printf*

I just wish I had a better sense of how portable that is. I just had a thought, maybe the best bet here is just a node one-liner:

```sh
node -e 'process.stdout.write("\uFEFF")' > dist/browser.js
```

I think that should be totally portable (on *nix)...what do you think?

**Comment by sethcall** [comment]
Since the issue appears to be environmently different behavior of printf, I like your node-based solution even better :+1:

**Comment by jmm** [comment]
@sethcall Ok, cool. Do you feel like making a PR? (If you do, feel free to wait for confirmation from **sebmck** first that he likes this solution.)

**Comment by lydell** [comment]
Even better:

```
node -p '"\uFEFF"' > dist/browser.js
```

I often find `node -p` very useful.

**Comment by sethcall** [comment]
Sure I can make a PR.  I'll wait a little for @sebmck  to weigh in.  No reason wasting time.   Thanks @lydell .

**Comment by jmm** [comment]
@lydell Thanks for the suggestion, that's a great idea! I am getting an extra char that way -- it's appending a newline I guess. Though I guess in this use case that doesn't matter.

@sethcall Ok, sounds good.

**Comment by sebmck** [comment]
What's the portability like for `echo -e '\xEF\xBB\xBF'`?

**Comment by sethcall** [comment]
@sebmck 

If you skim over this article: http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo

Echo seems to be worse off than printf in terms of it's capabilities over the years; also the user's environment can alter it's behavior.

**Comment by jmm** [comment]
@sebmck I'm no expert on the matter, but when I was reading stuff yesterday like the article @sethcall just linked I got the same impression, that it's worse than `env printf`. It seems to me like the node solution or saving a BOM to a file to `cat` with other output is more reliable.

**Comment by sethcall** [comment]
@sebmck  Are you feeling ok with the node-based write approach?

**Comment by sebmck** [comment]
Sure, feel free to submit a PR.

**Comment by sethcall** [comment]
PR open.

With the changes, and after running build-dist.sh successfully, I could confirm that node could parse BOM-encoded file after the fact.

**Comment by sebmck** [comment]
Thanks again @sethcall!

**Comment by sethcall** [comment]
Thanks all
