### ISSUE TITLE
[Promises] To declare .catch block before .then leads to call the two blocks at the same time when an error is rejected

### ISSUE THREAD

**Issue by grebett** [babel/babel#2258]
Hello there!

Thank you for your great work already.

I've encountered some issue which, if it may not be a bug, worths to be reported for other babel users.

Considering the code below, running with node:

```javascript
function fn () {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject('ko');
    }, 1000);
  });
}

fn()
.catch(error => {
  return console.log('catch =>', error);
})
.then(result => {
  console.log('then => ', result);
});
```

The .catch and .then blocks are put in this order because I wanted to handle errors first. Yet, even if there is one `reject` and no `resolve` call, the two blocks codes  are triggered. As a result, we hate this output:

```
catch => ko
then =>  undefined
``` 

If we invert the two blocks to follow the classics, only the catch block code is read by the control flow.

**Comment by forivall** [comment]
This seems like more of an issue for https://github.com/zloirock/core-js, which is where the promise polyfill comes from, and, if your described behaviour is in line with the spec (I don't know), then you should submit a PR to https://github.com/promises-aplus/promises-tests.

**Comment by zloirock** [comment]
It's correct `Promise` behavior. `Promise` `.catch` method returns new resolved promise with `undefined` value (result of calling `console.log`).

For questions use [slack](babeljs.slack.com).

Issues about standard library / polyfills, please, open in [`core-js` repo](https://github.com/zloirock/core-js).

**Comment by loganfsmyth** [comment]
To expand on the answers above, what you have is equivalent to this sync code

```
try {
  throw 'ko';
} catch (error){
  console.log('catch =>', error);
}

console.log('then => ', result);
```

**Comment by grebett** [comment]
Thx for the answer. I will try slack next time before posting an issue.
