### ISSUE TITLE
TypeError: undefined is not a function in code.trim()

### ISSUE THREAD

**Issue by haf** [babel/babel#2259]
Trying to transpile JS:

```
$ /usr/bin/env NODE_ENV=production babel-node node_modules/webpack/bin/webpack.js -p --config webpack-production.config.js
/usr/local/lib/node_modules/babel/lib/_babel-node.js:75
  code = code.trim();
              ^
TypeError: undefined is not a function
    at _eval (/usr/local/lib/node_modules/babel/lib/_babel-node.js:75:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/lib/_babel-node.js:106:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

```
$ babel-node --version
5.8.21
```

The code does `let Rx = require('rx')` and other than that it's a much smaller, partial copy of underscore.js but with `var` replaced for `let` and `function() { return EXPR; }` replaced with `() => EXPR` whereever possible.

**Comment by jmm** [comment]
Hello @haf, welcome to the Babel community. Can you please explain what you're trying to do? Why are you invoking `babel-node` on Webpack's bin? I have the feeling this is going to turn out not to be a bug in Babel and would be more appropriate for discussion on the slack, per the README:

>  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Have you looked at these [instructions for using Babel with Webpack](https://babeljs.io/docs/setup/#webpack)?

**Comment by haf** [comment]
Hello jmm,

Thank you. I'm trying to use newer JS features in files that I pull into the webpack.config.js file, i.e. I'm not just trying to compile files with webpack, but also configure webpack with babel.

Since node doesn't support the newer features out of the box, I figured I'd use the excellent command above, but that crashed, unfortunately.

In my opinion, and why I filed a bug report, when any program/software that crashes with a null reference exception, it's a bug.

**Comment by loganfsmyth** [comment]
Your command isn't quite right

    babel-node node_modules/webpack/bin/webpack.js -p --config webpack-production.config.js

passes all three of those arguments to `babel-node`. In this case, you are passing `-p`. You want

    babel-node node_modules/webpack/bin/webpack.js -- -p --config webpack-production.config.js

**Comment by jmm** [comment]
Thanks @loganfsmyth. I suspected that was part of the problem, but it still seems like a bit of an odd usage to me. I kind of think using the require hook in `webpack-production.config.js` would make a bit more sense. I just checked and it looks like an [`interpret`-based solution was merged into Webpack](https://github.com/webpack/webpack/pull/956), which I presume means you can do `node_modules/webpack/bin/webpack.js -p --config webpack-production.config.babel.js`. In any case, this issue can be closed right?

**Comment by loganfsmyth** [comment]
Yup. Didn't mean to say that there aren't other ways, just that the `-p` being read by `babel-node` is what is causing this problem.

**Comment by jmm** [comment]
Oh totally, that was the key point.
