### ISSUE TITLE
Decorator on method target.prototype undefined

### ISSUE THREAD

**Issue by grigory-leonenko** [babel/babel#2261]
I am trying to pass context of constructor to method, but then decorator function calls, target is empty object. 

```js
class Actions {
    @F
    foo(){
         
    }
}

function F(target, key, descriptor) {
    console.log(target.prototype) //undefined 
    return assign(descriptor, { value: new action(key, descriptor.value, target.prototype) });
}
```

**Comment by sebmck** [comment]
This is expected behaviour. The `target` is `Actions.prototype`, not `Actions`. Please see the [decorators proposal](https://github.com/wycats/javascript-decorators) for more info.
