### ISSUE TITLE
Option for JSX tagName parsing.

### ISSUE THREAD

**Issue by DylanPiercey** [babel/babel#2263]
The fact that Babel supports JSX natively is great however I think their should be more options exposed so that libraries other than react can extend the language.

Reacts lack of support for things like html comments could be improved upon by other libraries.

It would be helpful if Babel could expose an option that enabled custom parsing of tag names such as <!-- in the case of comments.

Currently html comments are syntax errors in JSX which is a common source of confusion for new comers.

This could allow other features such as namespacing (svg:circle).

**Comment by sebmck** [comment]
There isn't currently already the ability to plug into Babel's transformation later (see the [plugin docs](http://babeljs.io/docs/usage/plugins) for more info.). As for syntax, there's currently #1351 tracking that. Thanks! :blush:
