### ISSUE TITLE
IIFE issues.

### ISSUE THREAD

**Issue by jdalton** [babel/babel#2266]
```
()=>{}();
```
should error but instead translate into a valid IIFE:
```js
(function () {})();
```

and
```
(() => {
    console.log('hi');
}())
```
should error but produces a valid IIFE:
```
(function () {
    console.log('hi');
})();
```

**Comment by jmm** [comment]
Thanks for the report. I think this is a dup of #2118.

**Comment by jdalton** [comment]
No you're a dup!

![image](https://cloud.githubusercontent.com/assets/4303/9506424/e5d011b8-4bfc-11e5-8d4f-9bdfa4c3a0c5.png)

Thanks!

**Comment by jmm** [comment]
No problem!
