### ISSUE TITLE
Command line argument to not include babel/polyfill when running babel-node

### ISSUE THREAD

**Issue by mrmayfield** [babel/babel#2271]
I run babel-node to test my modules that I'm using in an express app. These modules are later compiled using grunt-babel and used as scripts. 

The issue is that when I'm creating the modules, I am booting them via the babel-node cli, which includes babel/polyfill out of the box. However, these modules also load babel/polyfill via the require syntax, which is necessary when they're called by the express app. Of course, this leads to an error, nothing new here.

My question is whether a feature can be added to babel-node that will *not* include babel/polyfill out of the box. The reason I ask is because at the moment I am commenting out the babel/polyfill require statement when testing, and then adding it when I am ready to call the script from the express app. Hasn't led to a bug yet but it is definitely fragile and a crappy workflow for me.

Forgive me/enlighten me if there is a CLI argument or better workflow for this that I'm not aware of, thanks! (PS: Babel is really awesome, thanks guys!)

**Comment by AgentME** [comment]
Similarly, I'd be interested in a way to not include the polyfill when `require('babel/register')` is used.

I've made a few javascript libraries which are transpiled with Babel's runtime flag before being published to NPM. It's assumed that the global Babel polyfill is not necessarily in use when people use the library. There are unit tests which operate directly on the ES6 source by telling mocha to require babel/register, however that causes the polyfill to be used for the tests. This means my tests won't let me know if I accidentally make my code rely on things which are supported by the polyfill but not the runtime transform.

**Comment by zloirock** [comment]
@AgentME `babel/register-without-polyfill`? :)

**Comment by AgentME** [comment]
@zloirock That fails for me.

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-runtime/core-js/array/from'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chris/Coding/braincrunch/test/format.js:3:19)
...
```

Seems like there's an explanation in https://github.com/babel/babel/issues/371:
>Except the polyfill is required in order for everything to work. 6to5 uses Array.from for example in quite a few transformers and it's not supported in even the latest unstable node.

So I guess babel(-node|/register) without the polyfill is a no-go.

On @mrmayfield's problem: If the polyfill didn't throw an error if it was already included, then that would solve your issue. Or you could detect whether the polyfill is in place first before you require it. That might require you to depend on some undocumented implementation detail though.

**Comment by zloirock** [comment]
@AgentME I don't understand the problem. You uses `babel` with `runtime` flag and wanna test it without polyfill *and without installed `babel-runtime`*?O_o

**Comment by AgentME** [comment]
No, I have babel-runtime installed.

Hm, that error doesn't actually match up with what I'd expected from what I understood the problem to be. ... Removing my project's node_modules directory and re-running `npm install` fixed it. I guess an old version of something in there had a bug making it not work.

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Babel 5.x is in a feature freeze so nothing will be added except critical bug fixes. Babel 6 is going to have a focus on having a much thinner external API so adding another option or flag is not a possibility. As @zloirock mentioned, you can use `babel/register-without-polyfill` and create your own entry file and just use `node` to load it.

**Comment by mrmayfield** [comment]
I had seen some code that conducts a conditional check of whether 'babel/polyfill' is already available to the script but I can't find it anymore. Does anyone have a lead on how I can achieve that: checking the runtime to see if 'babel/polyfill' is already available? (ie if I'm loading it through babel-node ? )

**Comment by AgentME** [comment]
Instead of using `babel-node foo.js`, use `node loader.js` where loader.js contains:

```javascript
require('babel/register-without-polyfill');
require('./foo.js');
```

**Comment by spalger** [comment]
Or `node -r babel/register-without-polyfill foo.js`
