### ISSUE TITLE
how to access decorator's metadata programmatically?  

### ISSUE THREAD

**Issue by xmlking** [babel/babel#2274]
I need to access metadata about method decorator in the implementation of class decorator as shown below.
is there way I can query metadata about about `index()` method's annotation i.e., ['/', 'GET']?

```js
@route('/users')
export default class UserController {
 constructor() {
    return this.router.routes();
 }

@route('/', 'GET')
 static index(next) {
    //
 }
```
```js
import Router from 'koa-router'
export function route(path, method, roles) {
  return (target,key,descriptor)  => {
    if(!key && path) {
      target.prototype.router = new Router({
        prefix: path
      });
      // TODO : how to get index method's decorator's metadata here? i.e.,  ['/', 'GET']
      //target.prototype.router
      //  .get('/', target.index)
    }

  }
}
```

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
