### ISSUE TITLE
Promise in core-js doesn't work with domain in nodejs

### ISSUE THREAD

**Issue by jiaz** [babel/babel#2275]
I use domain in nodejs to store data related to an async chain. Below is the code to demonstrate the concept.

**in index.js**

```javascript
require('babel/register');
require('./server');
```

**in server.js**

```javascript

import express from 'express';
import domain from 'domain';
import crypto from 'crypto';

const app = express();

app.use((req, res, next) => {
  const requestDomain = domain.create();
  requestDomain.add(req);
  requestDomain.add(res);
  requestDomain.trackingId = crypto.randomBytes(16).toString('hex');
  requestDomain.run(() => {
    next();
  });
});

app.get('/user/:id', (req, res) => {
  const trackingId = process.domain.trackingId;
  new Promise((resolve) => {
    setTimeout(resolve, 1000);
  }).then(() => {
    if (process.domain.trackingId !== trackingId) {
      throw new Error('ahhh, domain messed up!');
    }
    res.status(200).json({
      user: req.params.id,
    });
  }).catch((err) => {
    console.log(err.message);
    res.status(500).json(err.stack);
  });
});

app.listen(3000, () => {
  console.log('server started');
});
```

So the idea is when a request is being handled by express, a `trackingId` will be generated and bound to a domain scoped to the current request. According to nodejs' documentation `process.domain` will then always refer to that domain object during the whole async process chain.

In the code I added a check to verify that the `trackingId` is the same after the promise is resolved. However when I use the Promise provided by babel (core-js implementation) the Error will be thrown. So actually, somehow the Promise breaks the domain scope.

I then replace the Promise implementation with the bluebird one, everything then works well. Essentially, I changed the `index.js` to

```javascript
require('babel/register');
global.Promise = require('bluebird');
require('./server');
```

So it looks like the Promise comes with babel has some problem with nodejs' domain. Although I currently have a workaround on this, I think it might be good if someone can look at it.

**Comment by sebmck** [comment]
This is a [`core-js`](https://github.com/zloirock/core-js) issue. Please report it there.
