### ISSUE TITLE
babel/require ?

### ISSUE THREAD

**Issue by sonnyp** [babel/babel#2277]
I'm looking for a solution to require an es6 module from a es5 one in Node.js.
I don't want to use babel/register yet.

Is there any builtin way to do that?

Otherwise ```require('babel/require')(path)``` would be pretty straightforward.

**Comment by jmm** [comment]
Hello @sonnyp, welcome to the Babel community! This issue tracker isn't used for questions like this, per the README:
>  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Or is this a feature request? (And if so, please be aware that v5 is in a feature freeze.) What is `babel/require` -- a hypothetical module that does what you're asking about?

**Comment by thejameskyle** [comment]
There are other solutions depending on your particular situation. Please visit the [slack room](http://slack.babeljs.io) for support.
