### ISSUE TITLE
"require is not defined" with Transformer (browser.js)

### ISSUE THREAD

**Issue by brownieboy** [babel/babel#2281]
I'm trying to get to grips with the Babel Transformer file (browser.js or browser.min.js) without much success.

Here's a simple "Hello world" test.  I'm trying to use a module pattern with ES6, which works fine when I transpile with Babel via Webpack.

Here's my HTML:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Babel transformer test</title>
</head>

<body>
    Test 1 in root
    <div id="main"></div>
    <script src="libs/browser.min.js"></script>
    <script src="libs/react.min.js"></script>
    <script src="../app/app.jsx" type="text/babel"></script>
</body>
</html>
```

And here's that app.jsx:
```
import React from 'react';

class MainApp extends React.Component {
    constructor(props) {
    	super(props);
    }
	render() {
		return (
			<div>
			{this.props.message}
			 </div>
		)
	}
}
MainApp.defaultProps = {message: "Hello world!"};
React.render(<MainApp />, document.body);
```

This gives me the browser console error "Uncaught reference error: require is not defined".

What am I doing wrong?  Is Babel Transformer not even supposed to be used in this way?

**Comment by sebmck** [comment]
Babel isn't a module bundler, it just compiles your code to CommonJS modules and you'll need a module bundler/loader to make it work. I'd recommend looking into [webpack](https://webpack.github.io/) or [browserify](http://browserify.org/). If you need any help you're more than welcome to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!

**Comment by brownieboy** [comment]
@sebmck,

Many thanks for your reply.

**Comment by pinky321** [comment]
@kittens

I am getting same problem "Uncaught reference error: require is not defined".
If you have any solution then please post here.

**Comment by loganfsmyth** [comment]
@pinky321 Module syntax is converted into CommonJS by default, so you'd need a module bundler to make it work in the browser. Otherwise you'd need to set up a module loader like AMD and use Babel's AMD module transformation instead.
