### ISSUE TITLE
React 0.14 optimisation.react.inlineElements error

### ISSUE THREAD

**Issue by rchanou** [babel/babel#2282]
I might be doing something wrong here. [I made a simple project to demonstrate the issue.](https://github.com/rchanou/babel-react-opt-test) It builds fine, but when I open the web page, I get the error:

```
Uncaught Error: Invariant Violation: React.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React.
```
This is with beta 3 for React and React-DOM.

**Comment by sebmck** [comment]
The output isn't entirely compatible yet, AFAIK some changes need to be made. cc @spicyj

**Comment by spicyj** [comment]
Just tested and this works on React master (not beta3 though). We'll do an RC soon.

**Comment by rchanou** [comment]
Updated my test project to use React and ReactDOM 0.14 RC 1, still get `Uncaught Error: Invariant Violation: ReactDOM.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React.`. Any pointers?

**Comment by spicyj** [comment]
Due to the new XSS protection which landed last night, this is actually blocked on #2352 which @sebmck is going to merge and cut a release for soon.

**Comment by sebmck** [comment]
Released the XSS protection patch in 5.8.23.

**Comment by chentsulin** [comment]
should be 5.8.24 ?

**Comment by jmm** [comment]
@chentsulin correct, it's just a typo.
