### ISSUE TITLE
Multiple babel-core/require hangs

### ISSUE THREAD

**Issue by bucaran** [babel/babel#2283]
I would like to use babel to compile [Fly](https://github.com/flyjs) using tests written in ES6 (I was using a mix of ES5/ES6 until now by running tape with node —harmony)  and I am trying to use:

```
babel-node ./node_modules/tape/bin/tape test/*.js
```

which works fine until the part in Fly in which I use `require("babel-core/require”)` to compile `Flyfile.js` files in the _fly_.

 I don’t know if you can’t call `require(“babel-core/require”)` more than once, but all my tests pass except for the offending one where it hangs: (the debug messages are mine, you can see where it gets stuck)

```
  _: '/Users/b/dev/fly/node_modules/.bin/babel-node' }
  fly:bind register bind 'babel-core/register' +54ms
  fly:bind register bind 'babel/register' +184ms

・・・・
```

+ Is there any way to detect whether the "require hook" is “installed”?
+ or is it using babel to test a project using the `babel-core/require` ill-advised?

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by bucaran** [comment]
If multiple `babel-core/require` bindings is not advised against, then this could be a bug?

**Comment by bucaran** [comment]
@sebmck If multiple babel-core/require bindings is not advised against, then could it be a bug?
