### ISSUE TITLE
Can't "remove" decorators during a build

### ISSUE THREAD

**Issue by zyklus** [babel/babel#2285]
I realize this isn't babel's issue necessarily (it's more of an issue with the ES7 syntax), but I'm running into an issue where babel is needlessly dropping in an extra ~1kb of generated code that I don't want in production, so I'm opening this issue to start a discussion more than anything else (unless there is already some solution I just don't know about!)

I have a class:

```js
class Foo {
  @timer
  bar() {
  }
}
```

I only want the timer decorator to be there in production.  I can remove the functionality by replacing it with a no-op, but I still get an extra 1kb of generated code because the entire class is now a "decorated class".

What I'm really looking for is a way to write:

```js
class Foo {
  if (DEBUG) { @timer }
  bar() {
  }
}
```

with other statements, uglifyjs will just remove the entire statement.  It's obviously not valid code here though, so I'm not sure what to do.

The possible solution to my exact issue might be to optimize out no-op decorators:

```js
function decorator(target, key, descriptor) {
  return descriptor;
}
```

but a) I'm not sure if that's 100% safe, and b) there are probably other ESNext features that have similar issues.

**Comment by sebmck** [comment]
There's no way for Babel to tell what you mean so it obviously needs to include all the code to decorate a class. If file size is really an issue then you can use either the [runtime](babeljs.io/docs/usage/runtime) or [external helpers](babeljs.io/docs/usage/external-helpers) which both abstract out the helpers and improve file size. You can alternatively just use a plugin that strips these and only use it in production:

```sh
$ babel script.js --plugins ./strip-timer-decorator-in-production.js
```

**strip-timer-decorator-in-production.js**

```javascript
module.exports = function (babel) {
  return new babel.Plugin("strip-timer-decorator-in-production", {
    visitor: {
      Decorator: function () {
        if (this.get("expression").matchesPattern("timer")) {
          this.dangerouslyRemove();
        }
      }
    }
  });
};
```

If you need any further supports please use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!
