### ISSUE TITLE
Cannot assign to read only property 'Symbol(Symbol.hasInstance)'

### ISSUE THREAD

**Issue by Grandrath** [babel/babel#2286]
The following code causes the above error:
```javascript
function Foo() {}
Foo[Symbol.hasInstance] = (instance) => true;
```
[View in REPL](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&code=function%20Foo()%20%7B%7D%0AFoo%5BSymbol.hasInstance%5D%20%3D%20(instance)%20%3D%3E%20true%3B%0A&playground=false)

AFAICS according to [this comment on #1364](https://github.com/babel/babel/issues/1364#issuecomment-97053779) this should work. Is this a bug or a misunderstanding on my part?

**Comment by zloirock** [comment]
It was my mistake in comment, `Function#@@hasInstance` [non-writable](http://www.ecma-international.org/ecma-262/6.0/#sec-function.prototype-@@hasinstance), [use `defineProperty`](http://goo.gl/WzNyjT).
```js
function Foo() {}
Object.defineProperty(Foo, Symbol.hasInstance, {value: _ => true});
console.log(({}) instanceof Foo); // => true
```
For questions use [slack](https://babeljs.slack.com).

Issues about standard library / polyfills, please, open in [`core-js` repo](https://github.com/zloirock/core-js).

**Comment by getify** [comment]
NOTE: I've updated my inaccurate code in that linked thread. Sorry for the confusion.

**Comment by Grandrath** [comment]
Thank you @zloirock for the clarification. I'll use slack next time. :-)
