### ISSUE TITLE
Executing $ babel and $ babel-node does nothing

### ISSUE THREAD

**Issue by rohithpr** [babel/babel#2287]
I'm trying to get Babel running on Ubuntu 14.04. I've installed it using `sudo npm install -g babel`

However on running `babel` or `babel-node` the REPL is not launched. I simply get the prompt back. The same happens when I pass a file name as argument. (The file has just `console.log("Hello")`)

FWIW, `-v`, `--version`, `-h` and `--help` do nothing either. It shows `babel@5.8.23` at the end of the install process.

Some outputs that may be required:

```
$ which node
/usr/sbin/node
$ which nodejs
/usr/bin/nodejs
$ which babel
/usr/local/bin/babel
$ which babel-node
/usr/local/bin/babel-node
```

**Comment by sebmck** [comment]
Running just `babel` without passing a file and having it "hang" is expected behaviour. It's reading from stdin and waiting for you to close it. Can you post the exact commands you're using that do nothing?

**Comment by rohithpr** [comment]
![babel](https://cloud.githubusercontent.com/assets/10276811/9567748/1f59d40a-4f54-11e5-84ac-10da2237b4d0.png)

js.js has: `console.log('hello')`

**Comment by sebmck** [comment]
Seems like it's environmental then. Do you have issues running other npm installed scripts?

**Comment by rohithpr** [comment]
This is the first time that I'm using npm. Could you please suggest something that I can try to verify?

`nodejs js.js` works fine, in case it matters.

**Comment by sebmck** [comment]
Try installing `grunt` and running it to see if it works:

```sh
$ npm install -g grunt-cli
$ grunt
```

**Comment by rohithpr** [comment]
Okay, there seems to be an issue with npm! The same happened with grunt too.

**Comment by AluisioASG** [comment]
Could it be that the script is not being run by `nodejs` but by `node`?  What's the first line of `/usr/local/bin/babel`?

**Comment by rohithpr** [comment]
#!/usr/bin/env node

**Comment by AluisioASG** [comment]
Seems that npm won't adjust shebang lines, so you need to make `node` run Node.js rather than whatever it is on Ubuntu.  `ln -s /usr/bin/nodejs /usr/local/bin/node` should fix it.
