### ISSUE TITLE
Optional UMD global

### ISSUE THREAD

**Issue by jmeas** [babel/babel#2288]
When specifying the `modules` option as `umd`, I can't seem to find a way to get it to not set a global variable in the 'browser globals' part of the module definition.

For instance,

``` js
  // this is the browser globals section 
  else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, mod);
    // this line is always set, though it doesn't always need to be
    global.sandwich = mod.exports;
  }
```

Is there any way to prevent that `global.sandwich` from being written? The use case for this are plugins for libraries, like jQuery / Moment / Backbone plugins. Typically you use those libraries themselves as the namespace, and not the `global` object (`window`, in this case).

I tried setting `moduleId` to a variety of falsey values, but none of them seemed to work.

**Comment by sebmck** [comment]
I'm not sure what the behaviour is that you want. You want UMD without the browser global part? Isn't that the entire point of UMD?

**Comment by jmeas** [comment]
Sorry, I may not have been as clear as I could have been. This line should be optional: 

`global.sandwich = mod.exports;`

**Comment by sebmck** [comment]
Then it's effectively a noop?

**Comment by jmeas** [comment]
Mmm, a noop makes me think that nothing happens when the method is called, so I wouldn't quite call it that.

I'll try to elaborate more on the problem in an effort to make it more clear.

Imagine a $ plugin:

```js
// greater-than-ten.js
import $ from 'jquery';

$.fn.greaterThanTen = function() {
  return this.length > 10;
};
```

I would not expect this module to modify the global namespace in any environment, even a browser global environment. This is because jQuery is acting as the namespace – there's no reason to put it anywhere else.

However, if you compile this with Babel, then load it in a browser globals environment, you will end up with `window.greaterThanTen = {};`

This is because of this code:

```js
var mod = {
  exports: {}
};
factory(mod.exports, global.Mn);
global.greaterThanTen = mod.exports;
```

There are a few ways to solve this problem, but I can't find any of them in Babel. One way, which is what I proposed in this issue, is to make an option to toggle that last line.

**Comment by loganfsmyth** [comment]
The objective of Babel's module formatters is to facilitate a functional module system. The `umd` modules formatter exports globals because they are meant to then be used later by some other umd module which is importing it.

It really sounds like you don't want a module system at all in the final output, so it's not clear to me why you are trying to use `umd` at all. You would be better off using something like `browserify` alongside Babel to package and bundle the code for you. Browserify's goals are much more in line with what you seem to want, which is a single standalone file that will load a file into an existing jQuery instance. You can easily use `https://github.com/substack/browserify-handbook#browserify-shim` to package your JS so that CommonJS require calls will pick up the global jQuery reference.

**Comment by jmeas** [comment]
Allo @loganfsmyth!

> It really sounds like you don't want a module system at all in the final output

I do, though. Just because a file doesn't export a variable doesn't mean that it necessarily exists outside of a module system. If a user is using RequireJS, and they want my plugin, they should be able to `require('name-of-thing');` to permanently modify some other namespace, aside from the window (or whatever).

Consider [Underscore Contrib](https://github.com/documentcloud/underscore-contrib/). The goal of this library, if you're not familiar, is to provide a bunch of `_.mixin`s for Underscore. It's a great example of a library that could benefit from this feature.

Underscore contrib does not create a new variable to be exported. Instead, it modifies an existing namespace (`_`). At the moment, [it exports Underscore](https://github.com/documentcloud/underscore-contrib/blob/ee7acb93b9e62519098a92b13280e1cba32aa458/index.js#L15), but it could just as easily not export anything. I prefer the latter, which is why I want my UMD bundler to support that.

The reason for my preference is because I wouldn't want to do:

```js
var _ = require('underscore-contrib');
```

throughout my library/application. This is because it's not immediately obvious that I'm requiring Underscore here. I'd rather continue to do `var _ = require('underscore');`. Secondly, if you added a second extension library, say, `underscore-big-nums`, the system wouldn't scale.

Another idea would be to do...

```js
var _ = require('underscore');
require('underscore-contrib');
```

in every file that needs the extra methods. Also unnecessary, I think. The best way is to just have a plugins file that gets loaded once (at app start), and requires in all of your plugins.

I think your definition of what it means to "use" a module might be too narrow in scope. You can "use" a module by just doing:

```js
require('hello');
```

One doesn't need to store store it in a variable and continue using it. Oftentimes, as I've demonstrated, there's no variable to be stored!

It's of note that Underscore contrib is [not a UMD package](https://github.com/documentcloud/underscore-contrib/blob/ee7acb93b9e62519098a92b13280e1cba32aa458/index.js) right now, but it should be! Nothing I described above is unique to a Node/CJS environment.

> The umd modules formatter exports globals because they are meant to then be used later by some other umd module which is importing it.

Mmm, not quite. A `umd` module is agnostic to the environment that it's loaded in. It doesn't need to be consumed by another UMD module at all, which is why it's so valuable. A CJS module, on the other hand, is more like what you're describing. It is meant to later be used in another CJS module which imports it.

> You would be better off using something like browserify alongside Babel to package and bundle the code for you.

I understand Browserify's features and limitations, but it's not relevant to this discussion, I think. The tl;dr argument I'm trying to make is that if Babel supports exporting UMD, then it should include this feature.

@Rich-Harris, who knows a thing or two about module bundling, [also agreed that it's a good idea](https://github.com/esperantojs/esperanto/issues/96#issuecomment-72680324) as of a few months ago.

**Comment by jmm** [comment]
@jmeas So in other words you want a module that can be loaded via CJS or AMD, but doesn't create a global, correct?

My first thought was "that doesn't sound like UMD", but even in the UMD "spec" they have [this example](https://github.com/umdjs/umd/blob/master/amdWeb.js) that mentions removing "the browser global path" (which in the example would be truly pointless as then it'd just be an AMD module).

**Comment by jmeas** [comment]
> So in other words you want a module that can be loaded via CJS or AMD, but doesn't create a global, correct?

Yup. This may seem unusual, but it follows from a simple premise:

**Not every useful module needs to export a variable.**

If you agree with that, then it should be clear that this feature is useful. An example of a useful library that doesn't need to export a variable is Underscore contrib, as I described above. To see how this feature follows from this presmise, we can look at what "exporting" looks like in various environments.

```js
// CJS
module.exports = myVar;

// AMD
return myVar;

// Globals
window.myVar = myVar;
```

Not exporting a variable in a browser globals env. involves not setting anything on the window.

**Comment by loganfsmyth** [comment]
So something like:

```
 else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, window.someImport);

    if (Object.keys(mod.exports).length > 0) window.sandwich = mod.exports;
  }
```

to handle the `undefined` in both import and export cases?

**Comment by jmm** [comment]
@loganfsmyth Someone expecting a typical UMD module from input with no exports would still expect `window.sandwich` to be `{}` though, wouldn't they?

**Comment by loganfsmyth** [comment]
@jmm I honestly have no idea, I haven't used UMD modules much really.

**Comment by jmm** [comment]
@loganfsmyth I was just thinking that if the request here happens it might indeed need to be based on an option (as requested) rather than just lack of exports, or it would be surprising if that behavior wasn't wanted and the global was just undefined.

**Comment by jmeas** [comment]
> So something like:

That seems right! However, that code assumes that a variable name, `sandwich`, was given. A special UMD template would need to be generated that works without the user specifying a variable. Consider Underscore Contrib again...there would be no "contrib" or "underscoreContrib" value given, because, of course, it's working off of the Underscore namespace, so ya don't need to specify a variable name for something that doesn't exist.

> @loganfsmyth Someone expecting a typical UMD module from input with no exports would still expect window.sandwich to be {} though, wouldn't they?

I don't think this makes sense for the same reason above. This feature is for plugins that modify a namespace, and therefore don't even have a named variable that could be set on the `window`.

**Comment by jmm** [comment]
@jmeas OK, thanks, I see what you mean. I was just suggesting that lack of exports might not be an appropriate test for omitting the global, and with what you've suggested it wouldn't be necessary. I haven't generated UMD or AMD modules with Babel yet -- `moduleId` is how you specify the global var name for UMD? As you suggested, could allowing that to be a falsy value as a flag to not set the global be sufficient, or is that also used for AMD output sometimes?

On another note, Babel v5 is in feature freeze and my understanding is that these module formatters will be plugins in v6.

**Comment by jmeas** [comment]
> As you suggested, could allowing that to be a falsy value as a flag to not set the global be sufficient, or is that also used for AMD output sometimes?

I think a falsey flag makes sense.

> On another note, Babel v5 is in feature freeze and my understanding is that these module formatters will be plugins in v6.

Mhm. For that reason I think this could prob. be closed and marked as "will revisit," but I'll let @sebmck be the decider of that : P

**Comment by eventualbuddha** [comment]
Just to toss another possibility into the ring, rollup has an output format called `iife` for when you want a self-contained thing that wants to control how it is attached to some sort of global.

**Comment by thejameskyle** [comment]
This is definitely something to revisit after 6.0 comes out.

**Comment by lincolndbryant** [comment]
I encourage you guys to check out https://github.com/babel/babel/pull/2236 which would allow us to specify one global object (named `moduleRoot`) to attach all modules in a project 2, and to use keys that are not identifier safe (so that `/` and `.`) are allowed, via using string indexes.

@jmeas the best workaround to your issue right now is to specify the name of your project as `moduleRoot` in your config, and use `moduleIds: true`.  You still get globals for each module in your project, but they all start with your `moduleRoot`.  Not pretty, but should be collision-safe.  

I agree that it makes no sense for some modules to export anything, but the es6 module spec doesn't have features to indicate that.

**Comment by jmeas** [comment]
> but the es6 module spec doesn't have features to indicate that.

...wha? `import 'hello';` is valid syntax. Is there anything else that the spec would need to allow for modules that don't export anything?

I'm surprised that folks think this feature is something out of the ordinary. It seems pretty standard to me. Maybe I'm crazy :stuck_out_tongue: 

In any event, I think that the PR you opened fixes a different problem.

**Comment by thejameskyle** [comment]
To make a better argument for a non-exporting UMD format here...

Modules with side-effects are a valid use case and were considered in the spec. (see `import "foo"`)

These types of modules aren't entirely uncommon. Polyfills, plugins (ie. `$.fn.modal`), namespaced libraries (ie. `Backbone.Pageable`), and others all do this.

The purpose of a UMD for these is for compatibility when importing external libraries. For example, a jQuery plugin needs to import jQuery to extend it.

---

Now, if this were to be added, I think adding an additional option is unnecessary. It'd be better just do to do the following if there are no `export`s in the file.

```js
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['jquery'], factory);
  } else if (typeof exports !== 'undefined') {
    factory(require('jquery'));
  } else {
    factory(global.jquery);
  }
})(this, function (_jquery) {
  'use strict';
  // ...
});
```

**Comment by cesarandreu** [comment]
I'd argue modules with side-effects are generally an anti-pattern. (Although there's some good use-cases for em, such as polyfills.)

This sort of thing was done a lot because of the module situation in the browser, but now we have module bundlers that give us a superior solution.

If I'm using a module I'd expect it to export its functionality and not leech onto jquery or some other global. That makes code harder to test and reason about, and it makes it a pain to trace where that thing is coming from. I don't usually expect modules to be screwing around and polluting my global environment.

Does your module depend on jquery? Make it export a function that uses jquery inside.

Here's an example, though. Let's say you want to test `Foo`, but it depends on your `greater-than-ten` module. There's three variations:

```
// Foo.js Variation 1
import greaterThanTen from 'greater-than-ten'
export default function foo (x) {
  return greaterThanTen(x * 2)
}

// Foo.js Variation 2
import 'greater-than-ten'
import $ from 'jquery'
export default function foo () {
  return $.greaterThanTen(x * 2)
}

// Foo.js Variation 3
import $ from 'jquery'
export default function foo () {
  return $.greaterThanTen(x * 2)
}
```

Variation 1 is the best. It's taking advantage of modules so it's easy to test, and it's clear where its dependencies come from. You don't have to trace any magic to figure out where stuff is coming from.

Variation 2 is okay, it's explicitly declaring its dependencies, so testing this module isn't any harder than Variation 1, but it requires you to be aware that the `greater-than-ten` module generates a side-effect. I'd say this doesn't give you any benefits over the first variation.

Variation 3 is terrible. You can't import the file and use it, it requires the importer to have previously imported `less-than-ten` somewhere. This makes it harder to maintain and test. If I see this my first thought is going to be: Where is jquery getting this `greaterThanTen` thing from?

**Comment by jmeas** [comment]
> I'd argue modules with side-effects are generally an anti-pattern. (Although there's some good use-cases for em, such as polyfills.)

In general, I don't disagree with you. But there are some situations where it's much more preferable to use a module with side effects than the alternative. For instance, overriding `Backbone.sync` is commonly done by developers using Backbone. There's no other easy way to do this (that I can think of) that doesn't involve a module with side effects.

Opinions and examples aside, the ES2015 specification allows for this. For this reason alone Babel should also support it, I think. Then it's up to the developer to decide what a best practice is, or what works best for them in a given situation.

**Comment by hzoo** [comment]
I think we're going to close this unless we feel this needs to be reopened again.
