### ISSUE TITLE
electron, require class not known to babel

### ISSUE THREAD

**Issue by tdeheurles** [babel/babel#2289]
Hi, I'm trying to create a solution with github Electron and Babel.
I try to have a remote server that will serve the app (for normal browser and electron app).

Electron comes with special feature that you can import with require :
```javascript
// code example
if (insideElectronBrowser()) {
   var remote = require('remote');
   // ...
}
```
So when I build the app (with gulp), I encounter an error :
```
Error: Cannot find module 'remote' from 'C:\Users\...'
```

My question is the following :
- Is there anyway in babel to block/shunt this error or make babel to know these elements (as the elements won't be known before execution time) ?

**Comment by sebmck** [comment]
That error isn't being thrown by Babel.

**Comment by tdeheurles** [comment]
Thank you

**Comment by tdeheurles** [comment]
As you say, the problem did come from my use of babelify/browserify.
I was requiring at `build time` instead to require at `execution time`.

If someone create the same problem, here is a how to :
```javascript
export default class Tile extends React.Component {
  electronImport(name) {
    return require(name)
  }

  createTile(e) {
    var remote = electronImport('remote')
    var ipc = remote.electronImport('ipc')
    ipc.send('tile', "message")
  }
  
  render() {
    return (
      <Button onClick={this.createTile}>{this.props.Title}</Button>
     );
  }
}
```
