### ISSUE TITLE
Babel moves comment position in function arguments

### ISSUE THREAD

**Issue by willheslam** [babel/babel#2291]
This occurs with 5.8.23 (babel-core 5.8.23)
Babel moves comment position which matters for any parsers where comments have semantic meaning, e.g. flow.

For example:

    function foo(bar/*: string*/, baz/*: any*/){
	    console.log(bar, baz);
    }

put through babel turns it into:

    "use strict";

    function foo(bar, /*: string*/baz /*: any*/) {
	    console.log(bar, baz);
    }

This makes flow freak out, as flow expects the comma to be on the right hand side of the first comment:
    error      Unexpected token /*:

I've tried disabling all babel transformers and it still happens. This means we have to use flow's invasive syntax instead of the comment-based syntax for it to be totally valid.

This continues to happen for more than two arguments too:

    function foo(bar, /*: string*/baz, /*: any*/qux /*: number*/) {

**Comment by sebmck** [comment]
FWIW this is an issue but in regards to "invasive syntax", you can use the [flow-comments](https://github.com/babel-plugins/babel-plugin-flow-comments) plugin to convert type annotations to comments.

**Comment by willheslam** [comment]
Thanks for the recommendation - that's the fallback I've decided on. :)

For pure conservative reasons I'd like to write 'pure' ES6 JS that can be babel'd into flow-parseable code (for example safely transpiling let and const - though flow will support that any day now ( https://github.com/facebook/flow/pull/431 ), I am sure will always be new features babel supports but flow doesn't.

The flow-comments plugin means I can go from true ('invasive') flow to fake (flow-comments) flow whilst also safely transpiling flow-incompatible syntax, so that's good.
This also gives me an ejector button from the good ship flow - going permanently from true flow to fake flow if I decide it's a bad idea to maintain a true flow codebase. The problem with that, of course, is it puts me in the position I am now - that I can't then put that codebase through babel again without breaking the argument comments.

**Comment by willheslam** [comment]
Having looked deeper into this, it looks like it's an ongoing problem with resolving the requirement for 'lossless transforms' that maintain the (now semantically important) comment positioning with an AST that doesn't treat comments as a first class syntactical citizen (not an unreasonable assumption to make!).

I'm not familiar enough with the internals of Babel to change the comment attachment logic and I'm not going to create my own brand new CST anytime soon, so I have this (slightly hacky work around):

This turns commented flow syntax into naked flow syntax:
https://www.npmjs.com/package/uncomment-flow
(this may well be terrible)

Then during development of my project I'm using something along these lines:
https://gist.github.com/willheslam/21e62eb3a4b2c27d116a

So what that is doing is listening out for changes to my code (with flow comments) and, when something changes, stripping the comments so it's naked flow. Transpile the stuff flow doesn't like with babel (let and const etc.), readd the comments around the flow statements using the flow comments babel plugin and write to a new director called 'flowkay'. I can then run flow on that directory and check it for issues.

This is a pretty ugly workaround, but it is a workaround! I wanted to implement it as a babel plugin, but babel plugins (to my knowledge) act on the AST, so by that point it's too late. Feel free to correct me if I'm talking rubbish here :)

**Comment by hzoo** [comment]
Closing some inactive issues
