### ISSUE TITLE
Array destructuring not working

### ISSUE THREAD

**Issue by jackmatt2** [babel/babel#2294]
I am using the following array destructuring on a promise.
```javascript
    RSVP.all([
      promise
    ]).then((results) => {
      const { client } = results;
```

The trouble is that babel thinks the array is an object and compiles to object destructuring instead.

![babel-error](https://cloud.githubusercontent.com/assets/6348088/9596440/2c31fd32-50b8-11e5-9a53-64fad2da7167.png)

**Comment by sebmck** [comment]
It's compiling to object destructuring because you're using object destructuring. Use `const [client] = results;` rather than `const { client } = results;`. Note the use of `[]` rather than `{}`.

**Comment by jackmatt2** [comment]
:+1: cheers.
