### ISSUE TITLE
Increment and decrement operators (UpdateExpression) aren't handled correctly

### ISSUE THREAD

**Issue by kittens** [babel/babel#2295]
Migrated from https://github.com/babel-plugins/babel-plugin-constant-folding/issues/2:

> @jakepusateri
>
> Input
> ---
> ```
> var i = 0;
> i += 1;
> ++i;
> ```
> Output
> ---
> ```
> "use strict";
> 
> var i = 0;
> i += 1;
> ++1;
> ```
> Expected
> ---
> ```
> "use strict";
> 
> var i = 0;
> i += 1;
> ++i;
> ```
> Alternately
> ```
> "use strict";
> 
> var i = 0;
> i += 1;
> 2;
> ```
> 
> Either way ++1 isn't valid JS.

**Comment by thejameskyle** [comment]
This appears to be working fine in the current version of babel. @sebmck can this be closed or is there something I'm missing here?

**Comment by jakepusateri** [comment]
This is still happening for me with babel-plugin-constant-folding at 1.0.1 and babel --version of 5.6.23 (babel-core 5.7.4)

**Comment by hzoo** [comment]
This would be an issue for https://github.com/babel/babili, and it looks like it works fine.
