### ISSUE TITLE
repl returns the result 'use strict' unexpectedly

### ISSUE THREAD

**Issue by mikedmcfarland** [babel/babel#2299]
The result of some single undefined statements when using the repl via babel-node is `'use strict'` when I'd expect it to be `undefined`.
For example, using node's repl produces:

```
> node
> var s = ""
undefined
```

While babel's repl produces:

```
> babel-node
> var s = ""
'use strict'
```

I'd expect the result of the expression to also be `undefined`.

in case it's relevant, my versions are:

```
> node --version
v0.12.7

> babel --version
5.8.23 (babel-core 5.8.23)
```

**Comment by bradencanderson** [comment]
Repro with `babel-node -e "var a = 2;" -p`.

This feels like a bug in the strict transformer. Consistent output between node and babel-node seems like a reasonable thing to expect.

`babel-node -p` should print the result of the source program, regardless of what the source is transformed into.

**Comment by loganfsmyth** [comment]
> Consistent output between node and babel-node seems like a reasonable thing to expect.

This is actually the same as what node prints, if you include it all on one line.

```
> "use strict"; var a = 2;
'use strict'
> 
```

This doesn't have anything to do with the strict transformer specifically, what this essentially comes down to is some weirdness in the way `eval` works, e.g.

    eval('"use strict"; var a = 2;') === 'use strict'; 

Seems like you'd want a plugin to automatically add an expressionStatement to the end of the code if there wasn't one (assuming that is the logic `eval` follows).

    Program(node){
        if (!t.isExpressionStatement(node.body[node.body.length - 1)){
            node.body.push(t.expressionStatement(t.identifier('undefined')));
        }
    }

**Comment by thejameskyle** [comment]
@loganfsmyth That seems to be okay, I would just be worried about an edge case where the actual result isn't being output because `undefined` was being pushed to the end.

**Comment by hzoo** [comment]
I believe we did this in https://github.com/babel/babel/pull/4562
