### ISSUE TITLE
destructuring array

### ISSUE THREAD

**Issue by pgherveou** [babel/babel#2304]
Just found out about this dont know if you consider it as a bug or not

```
let foo, bar
let bim = boum
[ foo, bar ] =  ['foo', 'bar']
```
compile to 

```
'use strict';

var foo = undefined,
    bar = undefined;
var bim = boum[(foo, bar)] = ['foo', 'bar'];
```

whereas

```
let foo, bar
let bim = boum;
[ foo, bar ] =  ['foo', 'bar']
```
compile to 

```
'use strict';

var foo = undefined,
    bar = undefined;
var bim = boum;
var _ref = ['foo', 'bar'];
foo = _ref[0];
bar = _ref[1];
_ref;
```

debugger link: 
http://babeljs.io/repl/#?experimental=false&evaluate=false&loose=true&spec=false&code=let%20foo%2C%20bar%0Alet%20bim%20%3D%20boum%3B%0A%5B%20foo%2C%20bar%20%5D%20%3D%20%20%5B'foo'%2C%20'bar'%5D%0A%0A

**Comment by pgherveou** [comment]
might be a duplicate of https://github.com/babel/babel/issues/1576
but I still have the issue in 5.8.23

**Comment by eventualbuddha** [comment]
I believe this is expected behavior.

```
~ node <<EOS
> var a, b, c = Object
> [ a, b ] = [1, 2]
> console.log(a, b, c)
> EOS
undefined undefined [ 1, 2 ]
```

This is due to [ASI](http://jamesallardice.com/understanding-automatic-semi-colon-insertion-in-javascript/) not happening where you expect it to, and is the reason I always use semicolons to terminate non-block statements.

This code:

```js
var a, b, c = Object
[ a, b ] = [ 1, 2 ]
```

Is equivalent to:

```js
var a, b, c = Object[ a, b ] = [ 1, 2 ]
```

**Comment by pgherveou** [comment]
thks for the link @eventualbuddha
