### ISSUE TITLE
`this` is used in constructors with arrow functions before super() is called when 'es6.classes' is blacklisted

### ISSUE THREAD

**Issue by konistehrad** [babel/babel#2305]
Kind of a weird case, but if you're targeting Chrome 44 for native deployment, you can safely blacklist 'es6.classes', but you'll still need to transpile 'es6.arrowFunctions'. Unfortunately, in doing so in a constructor, you can end up in a case like this:

```javascript
// pre-transpilation
class A extends B {
    constructor() {
        super();
        let a = () => { this._b = false; };
    }
}

// post-transpilation
class A extends B {
    constructor() {
        var _this = this;

        super();
        var a = function a() {
            _this._b = false;
        };
    }
}
```

Chrome will throw 'this is not defined' in response to the use of `this` before super() is called.

Thanks again for the great work on Babel!

**Comment by impinball** [comment]
Sounds like an error in the emit. This would require a special case in the code generator, but this is definitely breaking. I'm surprised I hadn't run into that issue in an io.js project of mine, where I blacklisted `es6.classes` but not `es6.arrowFunctions`.

@sebmck?

**Comment by thejameskyle** [comment]
Looks like an edge case for the internal `shadow` function transformer.

https://github.com/babel/babel/blob/31a01cc4d257e8d9237b02c5469c2cd7ce2d2abb/packages/babel/src/transformation/transformers/internal/shadow-functions.js#L19

**Comment by sebmck** [comment]
Accidently fixed this when I did #2279.

**Comment by sebmck** [comment]
Wait nope.

**Comment by sebmck** [comment]
Fixed in the `development branch due out for Babel 6.
