### ISSUE TITLE
export foo from 'path/to/foo'

### ISSUE THREAD

**Issue by jdalton** [babel/babel#2308]
Babel seems to allow `export foo from 'path/to/foo'` but I don't think that's valid
(it's handy but not valid)

**Comment by cesarandreu** [comment]
That's a stage 1 experimental feature: [export extensions](https://github.com/leebyron/ecmascript-more-export-from). 

Do you have stage 1 or stage 0 features enabled?

**Comment by jdalton** [comment]
Ah thanks! I had the experimental checkbox enabled on the repl. My bad :D
