### ISSUE TITLE
JSX attributes should support backtick

### ISSUE THREAD

**Issue by gajus** [babel/babel#2309]
Where we do this:

```js
<div foo='lorem ipsum' />
<div foo={'a ' + b} />
<div foo={`a ${b}`} />
```

This should be possible:

```js
<div foo=`lorem ipsum` />
<div foo=`a ${b}` />
```

The benefits:

* This would make the code a lot more consistent when using ESLint quote style "backtick".
* This would get rid of the superfluous curly brackets when using backtick quotes.

**Comment by gajus** [comment]
I'd be happy to implement this if feature is agreed upon and help is needed.

**Comment by gajus** [comment]
I will write this as a plugin. If enough people like it, I will raise a PR.

**Comment by gajus** [comment]
Unfortunately, it appears that writing parser plugin is not possible at the moment. https://github.com/babel/babel/issues/1351

**Comment by sebmck** [comment]
Babel isn't going to add a feature because a lot of people like it. It will need to be added to the relevant specification. Please see facebook/jsx#25 for prior discussion on template literals as JSX attribute values.

**Comment by gajus** [comment]
@sebmck Is there a way I could do it? In a form of a plugin.
