### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by gsklee** [babel/babel#2310]
http://babeljs.io/docs/advanced/transformers/es6/spec-block-scoping/
http://babeljs.io/docs/advanced/transformers/es6/spec-modules/

Doc to these 2 transformers seem to be missing.

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
