### ISSUE TITLE
update to core-js.js 1.x.x

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babel#2311]
Hi, 
babel currently uses core-js.js 0.8.x !
Is any update release date for core-js 1.x.x there?

**Comment by zloirock** [comment]
Why do you think so? `babel-core` - [^1.0.0](https://github.com/babel/babel/blob/v5.8.23/packages/babel/package.json#L49), `babel-runtime` - [^1.0.0](https://github.com/babel/babel/blob/v5.8.23/packages/babel-runtime/package.json#L9), `browser-polyfill` build from `1.1.1`.

**Comment by sebmck** [comment]
As @zloirock said, all the packages use `^1.0.0`. Please update to the latest version of Babel if you're seeing older version of `core-js`.

**Comment by SerkanSipahi** [comment]
oh sorry, the only thing I found was that https://github.com/babel/babel/blob/8201ea0aa202db4825584c7f855cf4f444791312/packages/babel-runtime/package.json ! Unfortunately, I was probably careless when searching :(

**Comment by sebmck** [comment]
@SerkanSipahi That file is `^1.0.0` on `master`.

**Comment by alan2wong** [comment]
I pulled down the runtime (5.8.20) and it has turn.js with this contents:

```javascript
module.exports = { "default": require("core-js/library/fn/array/turn"), __esModule: true };
```

But this is removed since core-js 1.0.0: 

https://github.com/zloirock/core-js/releases/tag/v1.0.0

**Comment by zloirock** [comment]
Yep, need add some changes to `runtime`, I mention it [here](https://github.com/babel/babel/pull/2065#issuecomment-124555503), but it's not critical.

**Comment by SerkanSipahi** [comment]
I want to use the new "features" of Ecmascript 6/7 [ corejs ]( https://github.com/zloirock/core-js#features ). As noted by you( @zloirock @sebmck  ) is "core-js ^1.0.0" already included in the Babeljs( v5.8.23 ) but I cant use features like: ECMAScript 6: Array, ECMAScript 6: String, core.delay, ..., ... . Im using the lastest version of [ jspm ](https://github.com/jspm/jspm-cli)v0.16.2 . What am I doing wrong?

**Comment by zloirock** [comment]
`babel/polyfill` includes only standardized features and does not contain `core.delay` other features from your list should be available. Possible, you use `runtime` - it injects only static methods and some constructors - disable `runtime` transformer and include `babel/polyfill` or `core-js`.

**Comment by SerkanSipahi** [comment]
@zloirock thank you
