### ISSUE TITLE
Inconsistent class property/method name parsing

### ISSUE THREAD

**Issue by achicu** [babel/babel#2312]
The class property names can only be identifiers while the name of the methods can also be declared with ["name-of-method"] syntax. Should the two specifications be consistent?

    class A {
        ["my-property"] = 5; // Not valid syntax
        ["my-method"]() {  } // Valid syntax
    }

**Comment by sebmck** [comment]
That's invalid according to the current [class properties proposal](https://gist.github.com/jeffmo/054df782c05639da2adb). See the grammar definitions [here](https://gist.github.com/jeffmo/054df782c05639da2adb#145-class-definitions):

```
ClassPropertyInitializer : 
  IdentifierName ;
  IdentifierName = AssignmentExpression ;
```
