### ISSUE TITLE
Travis-CI, but not Mac: Super expression must either be null or a function

### ISSUE THREAD

**Issue by blesh** [babel/babel#2313]
[This PR on RxJS Next](https://github.com/ReactiveX/RxJS/pull/250) is a big issue in wish we had to use Babel to get proper CJS output because TypeScript wouldn't support it.

Unfortunately, it fails to build on Travis. Myself and my colleague @jayphelps have pulled down the PR and built locally (after having wiped out node_modules and a fresh `npm install`) and it builds just fine. It only fails on Travis.

This is a bit of a blocker for the project, so I'd appreciate any help you can provide.

Instructions to build the PR once you pull it down:  `npm run build_all`  ... basically it will use TS to build the ES6 files (stored in dist/es6), then it will use Babel to build the CJS files from those (stored in dist/cjs)

It seems to complain about the super expression in `dist/es6/schedulers/ImmediateScheduler`, which as best I can tell, is a valid super expression.

Here are the files in question (according to the build failure): 

ImmediateScheduler.js (transpiled from TS): 

```js
import Scheduler from './Scheduler';
import Action from './Action';
import FutureAction from './FutureAction';
export default class ImmediateScheduler extends Scheduler {
    constructor(...args) {
        super(...args);
        this.actions = [];
        this.active = false;
        this.scheduled = false;
    }
    flush() {
        if (this.active || this.scheduled) {
            return;
        }
        this.active = true;
        const actions = this.actions;
        for (let action; action = actions.shift();) {
            action.execute();
        }
        this.active = false;
    }
    schedule(delay, state, work) {
        return (delay <= 0) ?
            this.scheduleNow(state, work) :
            this.scheduleLater(state, work, delay);
    }
    scheduleNow(state, work) {
        return new Action(this, work).schedule(state);
    }
    scheduleLater(state, work, delay) {
        return new FutureAction(this, work, delay).schedule(state);
    }
}
```

and Scheduler.js (also transpiled from TS):
```js
import ImmediateScheduler from './ImmediateScheduler';
import NextTickScheduler from './NextTickScheduler';
export default class Scheduler {
    now() {
        return Date.now();
    }
    schedule(delay, state, work) {
        throw new Error("Scheduler.prototype.schedule not implemented.");
    }
}
Scheduler.immediate = new ImmediateScheduler();
Scheduler.nextTick = new NextTickScheduler();

```

**Comment by sebmck** [comment]
You seem to have an issue with circular dependencies. This isn't something that can be resolved by Babel and exists in the runtime execution order of your code. I'm closing this as there's nothing actionable from Babel here.

If you're in need of further support or have any questions please feel free to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

Thanks! :blush:

**Comment by sebmck** [comment]
btw the `module.exports` assignment for modules that only export a single default is being removed in 6.0.0, see #2212 for more info.

**Comment by blesh** [comment]
Ugh, I see the circular reference. This works fine in TypeScript, incidentally. I suspect they do some reference hoisting or the like. The removal of `module.exports` assignment is unfortunate.

**Comment by blesh** [comment]
@sebmck what's the explanation for it building fine on two Macs, but not within Travis?

**Comment by sebmck** [comment]
@blesh 

> I see the circular reference

I don't, where is it?

> This works fine in TypeScript

Then TypeScript is either doing something it shouldn't or Babel is, reopening until someone can confirm.

> what's the explanation for it building fine on two Macs, but not within Travis?

Are you using the same Node version? Only thing that would make Babel compile differently is enumeration order with different JavaScript engines. Other than that, if it's compiling the same but executing different then there's nothing that can be changed on the Babel side.

**Comment by blesh** [comment]
> I don't, where is it?

Scheduler imports ImmediateScheduler which imports Scheduler

> Are you using the same Node version?

Confirmed `v0.12.7` on both my machine and Travis. It only breaks at the Babel step on Travis.

On a different note: I find the removal of `module.exports` assignment troubling for projects like mine. I have a need to support output for TypeScript, ES6, CJS (mostly for Node), and ES5 globals (and reluctantly AMD). `require("something").default` is a deal breaker. If neither Babel or TypeScript will support module.exports assignment, I'm left with few options.

**Comment by thejameskyle** [comment]
You could set `module.exports` manually

**Comment by blesh** [comment]
Removing the circular references fixed this for me. Closing.
