### ISSUE TITLE
export + spread

### ISSUE THREAD

**Issue by jdalton** [babel/babel#2314]
I noticed in the Repl:

```js
let _export = {
  chunk, compact
};

export default _export // works
export _export // error

export default { ... _export } // works
export { ... _export } // error
```

**Comment by sebmck** [comment]
Expected behaviour. The dependency graph of ES2015 modules needs to be statically analysable and allowing arbitrary objects that can contain dynamic keys breaks this assumption.

**Comment by jdalton** [comment]
Wouldn't that mean that `export default { ... _export }` should error too?

At the moment I've trying to avoid double exporting to achieve:
```js
import { foo, bar } from "some/thing"
import thing from "some/thing"
```

**Comment by sebmck** [comment]
`export default` can accept any arbitrary expression. `export { foo }` isn't an object, it's an exports list.

**Comment by jdalton** [comment]
Hmm so is there a way to avoid double exporting?

**Comment by jmm** [comment]
Yeah, I don't think either of the snippets marked as `error` are valid syntax, are they?

**Comment by sebmck** [comment]
@jdalton There isn't.

@jmm Yeah, they're invalid.

**Comment by jdalton** [comment]
> There isn't.

So lame :cry:

**Comment by jmm** [comment]
@jdalton You wouldn't be able to use spread, you'd have to be explicit, but you should be able to do this I think:

```js
export {foo, bar, whatever as default}
```

Not sure if that's any better for your use case.

**Comment by jdalton** [comment]
Currently:
```js
export {
  chunk, compact, difference, drop, dropRight,
  dropRightWhile, dropWhile, fill, findIndex, findLastIndex,
  first, flatten, flattenDeep, indexOf, initial,
  intersection, last, lastIndexOf, pull, pullAt,
  remove, rest, slice, sortedIndex, sortedIndexBy,
  sortedIndexOf, sortedLastIndex, sortedLastIndexBy, sortedLastIndexOf, sortedUniq,
  sortedUniqBy, take, takeRight, takeRightWhile, takeWhile,
  union, uniq, uniqBy, unzip, unzipWith,
  without, xor, zip, zipObject, zipWith
};

export default {
  chunk, compact, difference, drop, dropRight,
  dropRightWhile, dropWhile, fill, findIndex, findLastIndex,
  first, flatten, flattenDeep, indexOf, initial,
  intersection, last, lastIndexOf, pull, pullAt,
  remove, rest, slice, sortedIndex, sortedIndexBy,
  sortedIndexOf, sortedLastIndex, sortedLastIndexBy, sortedLastIndexOf, sortedUniq,
  sortedUniqBy, take, takeRight, takeRightWhile, takeWhile,
  union, uniq, uniqBy, unzip, unzipWith,
  without, xor, zip, zipObject, zipWith
};
```

**Comment by loganfsmyth** [comment]
@jdalton You should double export like that. If your library users need an object with all of the functions, then should use

     import * as fns from 'mod';

     fns.chunk

**Comment by jdalton** [comment]
@loganfsmyth
> You shouldn't double export like that. 

Devs + opinions. Some want:
```js
{ chunk, compat } from "lodash/array"
```
and others want
```js
import array from "lodash/array"
```
and I want both :)

**Comment by loganfsmyth** [comment]
Haha true enough, I guess my point is by supplying that interface, you're bringing the issue of managing tons of exports as an object upon yourself.

    import * as array from "lodash/array"`

 is provided to avoid this type of problem.

**Comment by jdalton** [comment]
> you're bringing the issue of managing tons of exports as an object upon yourself

It's a build step for me so no management overhead, it just looks gross : P

**Comment by jmm** [comment]
FWIW, it looks like maybe you *could* do that with the [more export-from](https://github.com/leebyron/ecmascript-more-export-from) proposal, if you used 2 modules:

`lodash-es/_array`

```js
export {
  chunk, compact, /* ... */
}
```

`lodash-es/array`

```js
export * from "lodash-es/_array";
export * as default from "lodash-es/_array";
```

**Comment by anba** [comment]
@jmm Importing and then exporting the module (namespace object) itself should help here. 

```javascript
export { chunk, /* ... more */ };

import* as self from "lodash-es/array";
export default self;
```

**Comment by jmm** [comment]
@anba Oh, you're saying you can do that all self-referentially from the same module? I never thought of that. If that works and doesn't cause any weird cycle issues that's a pretty brilliant solution!

**Comment by jdalton** [comment]
@anba wow!

**Comment by jdalton** [comment]
I think when it transpiles though it would be a circular reference.
