### ISSUE TITLE
How to make React static work

### ISSUE THREAD

**Issue by jannavarro** [babel/babel#2315]
In my webpack config I use babel as loader for jsx files.

![image](https://cloud.githubusercontent.com/assets/4499051/9649691/e5cc858c-522a-11e5-9455-702ddfc2f47e.png)

When I try to use the new React static properties I get an error in babel saying it does not identify the equals sign.

![image](https://cloud.githubusercontent.com/assets/4499051/9649702/0d9baef8-522b-11e5-8586-26df70e816c8.png)

Question: Do I need to do additional steps to make it work? because I have seen other projects who uses babel as loader and they are able to make it work.

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
