### ISSUE TITLE
Request: Docpad plugin

### ISSUE THREAD

**Issue by williammalo** [babel/babel#2319]
It looks like babel is supported by most build systems, but not DocPad (http://docpad.org) It would be nice if it was.

**Comment by sebmck** [comment]
Closing this for the same reason as #2303. Integration support isn't really an issue with core and writing new integrations isn't being considered right now. Should be fairly easy to write one yourself though, you can see the [babel org](https://github.com/babel) as a reference for other integrations.

**Comment by williammalo** [comment]
ok thanks
