### ISSUE TITLE
Array.prototype[Symbol.iterator] is missing

### ISSUE THREAD

**Issue by d180cf** [babel/babel#2320]
This is why the JS code that Babel emits for most of for..of loops doesn't work by itself. However this can be easily fixed:

```js
// [1, 2, 3][Symbol.iterator]() needs to return an iterator
// that enumerates the items according to the es6 iterator protocol;
// otherwise the code generated by babel won't work
Object.defineProperty(Array.prototype, Symbol.iterator, {
    enumerable: false,
    value: function () {
        const items = this;
        let index = 0;

        return {
            next() {
                const i = index++;

                return {
                    done: i >= items.length,
                    value: items[i]
                };
            }
        };
    }
});
```

With a Symbol polyfill (I'm using the es6-symbol package), this is good enough to make the emitted JS code run in es5 environment.

**Comment by loganfsmyth** [comment]
Babel just transforms the syntax, it is the users responsibility to load a polyfill that covers iterables. This is all covered by Babel's default polyfill. If you load your own, yes, you'll need something like this.
