### ISSUE TITLE
Helper variables should be prefixed with something else

### ISSUE THREAD

**Issue by d180cf** [babel/babel#2321]
I'm extensively using generators and Babel does a great job transpiling my various es6 tricks into valid es5. However when I debug the es5 code, I often see in the Chrome's debugger the following picture:

```
Local
  _didIteratorError9: false
  _didIteratorError10: false
  ...
  color: 0
```

All these helper variables are prefixed with the underscore and thus stay on the top, shifting variables that I want to see to the very bottom. If Babel used a different prefix, i.e. `z`, all these "hidden" variables wouldn't distract my attention.

**Comment by Awk34** [comment]
Try using sourcemaps

**Comment by eventualbuddha** [comment]
@Awk34 that wouldn't help with Chrome's "Locals" list, would it?

**Comment by Awk34** [comment]
@eventualbuddha It would. If you set up source maps, none of the babel variables would show up in the dev tools.

**Comment by forivall** [comment]
Also, this is an issue with regenerator, not babel.

**Comment by sebmck** [comment]
@forivall No, this has nothing to do with `regenerator`.

@d180cf I don't really see this as an issue. You're asking for a pretty significant change to support the ordering of something very specific. Using an underscore to signify a private/autogenerated variable is extremely common and I'm not willing to change that.

**Comment by d180cf** [comment]
I am using source maps and that's actually the reason why I prefer Babel over Traceur - it's able to generate source maps based on preexisting source maps. However the underscored variables still show up in the Chrome's locals list.

If replacing the underscore with something like "z_" is a significant change then.. well.. you understand the Babel's internals better, so maybe it is a significant change.

**Comment by sebmck** [comment]
It's not a significant change technically, it would require literally adding one character. It's just a significant change in terms of the status quo.
