### ISSUE TITLE
Babel breaks in IE8 when using ES6 modules

### ISSUE THREAD

**Issue by kossnocorp** [babel/babel#2322]
Given code:

``` js
export {something as default}
```

… generates such snippet in the start of the file:

``` js
Object.defineProperty(exports, '__esModule', {
  value: true
})

// ...
```

… that leads to exception in IE8. There is no way to fix it using shims because in IE8 `Object.defineProperty` can only be used on DOM objects.

**Comment by stefanpenner** [comment]
You can ask babel to create amdStrict modules which don't use def prop and as such will work on ie8 although some cycle scenarios won't work as expected.

**Comment by kossnocorp** [comment]
@stefanpenner sounds like perfect solution, but it fails for me with `babel-node`:

<img width="715" alt="1__tmux___users_koss_src_tracker_front__tmux_" src="https://cloud.githubusercontent.com/assets/52201/9678467/0d486d7c-5318-11e5-8208-681a8faaccca.png">

`.babelrc`:
``` json
{
  "modules": "amdStrict"
}
```

**Comment by eventualbuddha** [comment]
@kossnocorp Both of these issues are expected. Node.js does not use AMD, but CommonJS instead. IE8 compatibility with modules is discussed in the [caveats](http://babeljs.io/docs/advanced/caveats/) on the website. I suggest checking out the Slack channel, since you'll be able to get help faster there:

>   For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by sebmck** [comment]
Enable loose mode for [`es6.classes`](https://babeljs.io/docs/advanced/loose/#es6-classes):

**.babelrc**

```json
{
  "loose": ["es6.classes"]
}
```

**Comment by kossnocorp** [comment]
@sebmck @eventualbuddha thanks!

**Comment by zloirock** [comment]
> There is no way to fix it using shims because in IE8 `Object.defineProperty` can only be used on DOM objects.

[Emm](https://github.com/zloirock/core-js/blob/master/modules/es5.js#L38-L45)?

**Comment by kossnocorp** [comment]
@zloirock sorry, I'm not sure that this code does and how it relates to my problem, I just quoting [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Internet_Explorer_8_specific_notes) & [Babel docs](http://babeljs.io/docs/advanced/caveats/#getters-setters-8-and-below-).

**Comment by zloirock** [comment]
@kossnocorp this code fixes your problem.

**Comment by kossnocorp** [comment]
@zloirock thanks, I'll take a look.
