### ISSUE TITLE
innerComment association lost from function with defaults args and no body

### ISSUE THREAD

**Issue by volny** [babel/babel#2326]
This is a minor issue, but with something like 
```
function foo(param='sth') {
  //some comment
};
```
the comment will appear outside the function.

**Comment by goto-bus-stop** [comment]
Yep, that's because comments are attached to other AST nodes, and there is no AST node _inside_ the block to attach to. see #1904, #758

**Comment by loganfsmyth** [comment]
@volny This seems to only happen when a function has default values and no body. I agree this behavior isn't perfect, but I'm curious if this caused a problem for you, or if it is just something interesting you noticed.

@goto-bus-stop That's no longer the case. Nodes can also now have an `innerComments` block, which attempts to address some issues like this.

**Comment by sebmck** [comment]
Fixed in the `development` branch.
