### ISSUE TITLE
ReferenceError: something is not defined when using eval

### ISSUE THREAD

**Issue by fundon** [babel/babel#2328]
Example, missing the `fs` module.

```js
import fs from 'fs';

const name = 'doit';

const doit = eval(`(function ${name} () {
  var c = fs.readFileSync('./eval.es6', 'utf-8');
  return c;
})`);

console.log(doit());
```

`$ babel-node eval.es6`
> ReferenceError: fs is not defined

**Comment by loganfsmyth** [comment]
`eval` usage isn't something that Babel guarantees. You could try:

```
import fs from 'fs';

const name = 'doit';

const doit = eval(`(function(fs){
  return (function ${name} () {
    var c = fs.readFileSync('./eval.es6', 'utf-8');
    return c;
  })
})`)(fs);

console.log(doit());
```

so the `fs` value is resolved and then explicitly passed in. Babel does variable renaming and rewriting, so if you're going to eval, you shouldn't rely on the outer variables keeping the same name.

What is your usecase where runtime-defined function names is so important?

**Comment by fundon** [comment]
My case is https://github.com/trekjs/trek/blob/master/src/Engine.js#L272-L282.
The function names is not important, but is very useful for debug and track.

**Comment by sebmck** [comment]
This isn't supported. I'm not going to break live bindings of modules just for `eval`. Thanks! :blush:

**Comment by fundon** [comment]
Okay, I hope you can add this to your todo list. 😁

**Comment by sebmck** [comment]
There's no way to support this.
