### ISSUE TITLE
es6.parameters without es6.arrowFunctions breaks rest params in arrow functions

### ISSUE THREAD

**Issue by mzgol** [babel/babel#2332]
With the `es6.parameters` transformer turned on and `es6.arrowFunctions` turned off, the following:
```js
const f = (...args) => args[1];
```
is transpiled to:
```js
 const f = () => arguments[1]; 
```
which is incorrect. I'd expect Babel to either force-apply the `es6.arrowFunctions` transformer in cases like the above that can't otherwise be transpiled correctly or to throw so that I know this code can't be transpiled with current settings.

Babel 5.8.23.

**Comment by sebmck** [comment]
Terminology nit but it's a rest parameter, not a spread.

**Comment by mzgol** [comment]
Yeah, I somehow missed the `es6.parameters` transformer and thought `es6.spread` applies to rest params as well. Thanks for the clarification.

**Comment by moretti** [comment]
I had a similar problem with default parameters.

Essentially something like:
```.js
const func = (param, opts = {}) => {
  const { a, b } = opts;
```

is (wrongly) transpiled to:

```.js
const func = (param) => {
  let opts = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

  const a = opts.a;
  const b = opts.b;
```
when `es6.arrowFunctions` is disabled.

**Comment by benmosher** [comment]
I am getting an error and failing to build from the `rest` transformer with this input:

```js
    const thenHide = (action, ...params) => () => {
      action(...params)
      this.refs.overlay.hide()
    }
```

Transforming (without `es6.arrowFunctions`) throws:
```
Module build failed: TypeError: /path/to/package/module.js: node.body.body.unshift is not a function
  at NodePath.Function (/path/to/package/node_modules/babel-core/lib/transformation/transformers/es6/parameters/rest.js:246:22)
```

**Comment by sebmck** [comment]
Fixed this in the `development` branch. I'm not going to be supporting this in 5.x because there are lots of other issues with interoperating transforms.
