### ISSUE TITLE
Recursive module auto resolving

### ISSUE THREAD

**Issue by felixpis** [babel/babel#2333]
Is there a way to give bable one entry point main js file that performs import of classes from other files and it will create one concantinated file? Also without dependency on requireJS or systemJS?
Means like in traceur there is a method recursiveModuleCompileToSingleFile.

**Comment by eventualbuddha** [comment]
Babel doesn't do this yet, so we recommend using [rollup](https://github.com/rollup/rollup) for this.

Also, in the future please use the Slack channel or StackOverflow for questions. Thanks!
