### ISSUE TITLE
await doesn't work for the array compressions

### ISSUE THREAD

**Issue by trikadin** [babel/babel#2335]
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=(async%20()%20%3D%3E%20%7B%0D%0A%20%20console.log(4%2C%20%5Bfor%20(el%20of%20%5B'%2F'%5D)%20await%20fetch(el)%5D)%3B%0D%0A%7D)()%3B%0D%0A

**Comment by kobezzza** [comment]
+1

**Comment by jaredly** [comment]
For reference, the code is
```js
(async () => {
  console.log(4, [for (el of ['/']) await fetch(el)]);
})();
```
And the `await fetch(el)` statement is preserved in the generated code
```js
          for (var _i = 0; _i < _arr.length; _i++) {
            var el = _arr[_i];

            _console$log.push(await fetch(el)); // <-- await is still there
          }
```

**Comment by sebmck** [comment]
Probably going to remove comprehensions in Babel 6 which wont make this issue relevant.

**Comment by thejameskyle** [comment]
@sebmck Do you want to add that to the Babel 6.0 issue and close this?

**Comment by sebmck** [comment]
Comprehensions are dead and are being removed in 6.0. Closing this as a wontfix.
