### ISSUE TITLE
Investigate (fix?) source map merging

### ISSUE THREAD

**Issue by sebmck** [babel/babel#2336]
cc @martinbigio

**Comment by martinbigio** [comment]
just verified this is not working with the latest source-maps version (0.4.4)

**Comment by ericvw** [comment]
I have verified this as well.  I have also found that when it was working back in `4.x` that the source map merging only worked for inline source maps.  I am happy to help work on this to get source map merging for inline and external source maps if that is a desired feature.  The other thing I thought about as well is if `babel` wants to forgo providing source map merging and leave that up to end users to script using [convert-source-map](https://github.com/thlorenz/convert-source-map) themselves.

**Comment by ericvw** [comment]
The option flag got disabled when there was a refactoring of the options.  I believe 5a319fd553ff28761488c29995d90545e7873c29 disabled the command-line option.
