### ISSUE TITLE
How to gt Babeljs class name

### ISSUE THREAD

**Issue by Alphapage** [babel/babel#2339]
Hello,
Here is a class:
class Test {}
I want to get Test.name , but I get "Test".

Babeljs changed to "_Test["default"]" because I use import modules.

How to get the Babeljs classname "_Test["default"]" instead of the generic one "Test" ?

Thanks in advance for your help.

**Comment by sebmck** [comment]
This rewriting is done for live bindings and circular dependencies. When you write `Test.name` and it references a `Test` default import then it is indeed rewritten to `_Test["default"]`, there is however some additional interop logic performed to get the `{ default }` object. However, you're asking a question and the Babel issue tracker is not an appropriate place for this. Please feel free to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
