### ISSUE TITLE
Plugin API for shared featured-based configuration

### ISSUE THREAD

**Issue by ef4** [babel/babel#2340]
(Opening a new issue at @sebmck's request, based on discussion that came out of #2338. cc @stefanpenner who was involved in that issue.)

I would like to propose a new plugin API for managing "features". A "feature" would just be an identifying name with documented semantics. Babel would maintain a central list of features, so that plugins could coordinate shared usage of features without naming collisions.

One example of a feature is an actual browser feature, like "supports arrow functions". But generic features could also be defined to express optional behaviors within the babel ecosystem. For example, perhaps a `debugBuild` feature could be established that allows any plugin to know whether it should generate less-performant-but-easier-to-debug output.

Babel would provide a way for end users to configure which features they want to enable within their _final build output_. For example, a user who enables the `arrowFunctions` feature is expressing the intention that their final build output is allowed to contain arrow functions, presumably because they only target browsers that have native implementations of that feature. A user who enables the `debugBuild` feature is expressing the intention that their final output should be easily debuggable.

Each plugin would be able to ask which features are enabled in _its own output_. This allows plugins to adapt their behavior dynamically to take advantage of downstream features. An example of this would be disabling certain transforms when native implementations are available. Another example would be making the plugin throw a helpful exception if it requires a downstream feature that is disabled (turning a runtime failure into a build time failure).

Each plugin would also be able to declare which features it _adds_ and _subtracts_ from its input. For example, the plugin that transpiles arrow functions into regular function expressions would _subtract_ the `arrowFunctions` feature, because its output no longer needs that feature. Whereas the plugin that transpiles `for ... of` would _add_ the `symbols` feature, because it has introduced a new dependency on the existence of `Symbol.iterator`.

Addition & subtraction is why I said that each plugin can query which features are enabled in _its own output_ and not just in _the whole application_.  Order of transformations matters, so the features available to each plugin's output can potentially depend on all the later plugins. If the user disables the `arrowFunctions` feature, but is using a plugin that subtracts `arrowFunctions`, earlier plugins who ask what features are available should see that they're allowed to use `arrowFunctions`.

(The directionality of "add" vs "subtract" is somewhat subjective. People can bikeshed on what nomenclature is less confusing. What I described as "subtraction" above is arguably really "adding" capabilities from the perspective of all earlier transforms. It really comes down to whether you're thinking about the process of removing features from the input code or adding features to the final environment.)

**Comment by thejameskyle** [comment]
> Each plugin would also be able to declare which features it adds and subtracts from its input. For example, the plugin that transpiles arrow functions into regular function expressions would subtract the arrowFunctions feature, because its output no longer needs that feature. Whereas the plugin that transpiles for ... of would add the symbols feature, because it has introduced a new dependency on the existence of Symbol.iterator.

This would be extremely messy and would most likely lead to transformers being unpredictably incompatible with one another. It's really best just to look at the AST that comes out.

Also, Babel in 6.0 is removing all of its transforms from core into separate plugins. I don't see what you are describing as being aligned with that.

I'm going to close this since I'm trying to cleanup issues right now, someone else can open it up again if they want to. Thanks for taking the time to write it out @ef4.

**Comment by sebmck** [comment]
@thejameskyle You missed the first line :wink: 

> Opening a new issue at @sebmck's request

**Comment by thejameskyle** [comment]
Just trying to clean out as many issues as possible

**Comment by hzoo** [comment]
Going to close this as it seems it was for Babel 5. With separate plugins now you could do this as a separate preset. https://github.com/babel/babel-preset-env/ does to the work of turning off plugins based on native support if that was what was asked so definetely add a issue there if it's not already supported @ef4!
