### ISSUE TITLE
async function problem when es6.properties.shorthand is blacklisted

### ISSUE THREAD

**Issue by tsing** [babel/babel#2341]
Enabled `es7.asyncFunctions` and `asyncToGenerator`, but disable the `es6.properties.shorthand`,  babel can not transform the code below correctly:

original code:
```
import {connect} from './db';

let obj = {
  async connectTo() {
    await connect();
  }
}
```

transformed code:

```
'use strict';

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { var callNext = step.bind(null, 'next'); var callThrow = step.bind(null, 'throw'); function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(callNext, callThrow); } } callNext(); }); }; }

var _db = require('./db');

let obj = {
  connectTo()
};
```

and this is my .babelrc 

```
{
  "whitelist": [
    "strict",
    "es6.destructuring",
    "es6.modules",
    "es6.parameters",
    "es6.spread",
    "es6.tailCall",
    "es7.asyncFunctions",
    "es7.objectRestSpread",
    "asyncToGenerator",
    "flow"
  ]
}
```

**Comment by thejameskyle** [comment]
For the record if you switch from `asyncToGenerator` to `regenerator` this is working for now.

**Comment by thejameskyle** [comment]
Babel is [looking for](https://github.com/babel/babel/blob/master/packages/babel/src/transformation/helpers/remap-async-to-generator.js#L64) `node.id` on the `FunctionExpression` without looking up that it is in the context of a shorthand `Property`. In which case [it never attaches the `CallExpression`](https://github.com/babel/babel/blob/master/packages/babel/src/transformation/helpers/remap-async-to-generator.js#L74-L82) for the `asyncToGenerator` helper.

It needs to lookup `path.parent.key.name`.

**Comment by willin** [comment]
@thejameskyle  https://github.com/babel/babel/blob/master/packages/babel/src/transformation/helpers/remap-async-to-generator.js#L74-L82 404 not found

**Comment by thejameskyle** [comment]
https://github.com/babel/babel/tree/master/packages/babel-helper-remap-async-to-generator
