### ISSUE TITLE
asyncGenerator on async arrow function when es6.arrowFunctions is blacklisted

### ISSUE THREAD

**Issue by tsing** [babel/babel#2342]
original code
```
import {connect} from './db';

setTimeout(async () => {
  await connect();
});
```

transformed code
```
'use strict';

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { var callNext = step.bind(null, 'next'); var callThrow = step.bind(null, 'throw'); function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(callNext, callThrow); } } callNext(); }); }; }

var _db = require('./db');

setTimeout(_asyncToGenerator(() => {
  yield (0, _db.connect)();
}));
```

This will cause error: `SyntaxError: Unexpected strict mode reserved word` in nodejs 4.0.0

The .bablerc is configured below:

```
{
  "whitelist": [
    "strict",
    "es6.destructuring",
    "es6.modules",
    "es6.parameters",
    "es6.spread",
    "es6.tailCall",
    "es7.asyncFunctions",
    "es7.objectRestSpread",
    "asyncToGenerator",
    "flow"
  ]
}
```

**Comment by PinkaminaDianePie** [comment]
+1, arrows unusable with babel for now

**Comment by dallonf** [comment]
Can also confirm this is a problem.

There might not be an obvious fix, though... there's no such thing as arrow generator functions afaik.

**Comment by dvlsg** [comment]
I also have this problem. @dallonf has a valid point, though.

I'm working around it by using `async function() {}` instead of `async () => {}` for now.

**Comment by tsing** [comment]
@dvlsg yes, I use the workaround too.

**Comment by PinkaminaDianePie** [comment]
```javascript
import {connect} from './db';

setTimeout(async (params) => {
  await connect();
});
```
i think we can transpile arrow generators this way:

```javascript
'use strict';

var _db = require('./db');

setTimeout(async (params) => {
  _asyncToGenerator(function * (params) {
    yield (0, _db.connect)();
  }).apply(this, arguments);
});
```
so our generator will work with binded context (```this``` and ```arguments```) like in arrows
i also request related fix for https://github.com/babel/babel/issues/1618 =D

**Comment by trikadin** [comment]
+1

**Comment by calebboyd** [comment]
It would seem that `bluebirdCoroutines` and `asyncToGenerator` should ​_always_​ use `es6.arrowFunctions` for their top level function,  since generator arrow functions are illegal. (but `async/await` arrow functions are not .

proposal reference: https://github.com/tc39/ecmascript-asyncawait/blob/master/spec/syntax.html#L20

**Comment by thejameskyle** [comment]
It seems like it'd be better to just transpile this one `ArrowFunctionExpression` to a `shadow` `generator` `FunctionExpression`, which should just be a combination of:

https://github.com/babel/babel/blob/31a01cc4d257e8d9237b02c5469c2cd7ce2d2abb/packages/babel/src/transformation/transformers/es6/arrow-functions.js#L28-L31

and 

```js
node.generator = true;
```

**Comment by PinkaminaDianePie** [comment]
@thejameskyle will it have lexical binding of ```this``` and ```arguments```?

**Comment by thejameskyle** [comment]
Yes that's what shadow functions are in Babel.

**Comment by trikadin** [comment]
+1

**Comment by FredericHeem** [comment]
+1
