### ISSUE TITLE
Segmentation fault on Node 4.0?

### ISSUE THREAD

**Issue by abritinthebay** [babel/babel#2343]
Might be something screwy on my system but if I switch down to say... v3.0 it still works. But if I do `nvm install 4.0` then run Babel fails with

`[1]    74859 segmentation fault`

I'm running it through an npm script but it's just the babel command `babel --stage 1 --optional es7.classProperties --external-helpers --modules common es6/ --out-dir lib/`

Ideas? Concerns? Debug info I can provide?

**Comment by carlosvillu** [comment]
I have the same problem.

**Comment by ahdinosaur** [comment]
https://github.com/nodejs/node/issues/2752#issuecomment-138773387

**Comment by iMasterAle** [comment]
I have the same problem even before npm rebuild
```babel --stage 0 -d build/ app/```

**Comment by carlosvillu** [comment]
For me work after a `npm rebuild`

Thx a lot!

**Comment by iMasterAle** [comment]
Now it's work!

I removed  ```/node_modules/``` and I do ```npm install``` then ```npm rebuild```

**Comment by sebmck** [comment]
Closing this as just like any module that has a native dependency, you need to rebuild if you switch to a different Node version.

**Comment by amrudesh-santhanam** [comment]
Had segmentation fault : 11. I did an npm install -g babel again to update babel and then it worked fine.
