### ISSUE TITLE
Feature Request: `document.currentScript.ownerDocument`, `with` statement

### ISSUE THREAD

**Issue by ilyaigpetrov** [babel/babel#2344]
#### `document.currentScript.ownerDocument`

Babel's `browser.js` is written so that it queries for `<script>`s of the global `window.document`. And if your `<script>` is under other `document`, e.g. inside html-imported web component (which may be implemented with `Google Polymer`) babel doesn't work.  

#### Get it Work with this Wrapper
__Not tested__ (events + async + different browsers = too much)  
If you are not a fan of _"we have new roads -- get a new car, rewrite your code"_ approach, you can do:
```js
function createProxyOf(target, overrides) {

  var props = [];
  for(var p in target)
    props.push(p);

  var proxy = overrides || {};

  props.forEach(
    function(prop) {
      if (proxy.hasOwnProperty(prop))
        return;
      var desc = Object.getOwnPropertyDescriptor(target, prop);
      if (desc) {
        if (desc.get)
          desc.get = desc.get.bind(target);
        if (desc.set)
          desc.set = desc.set.bind(target);
        Object.defineProperty(proxy, prop, desc);
      }
      else if (typeof target[prop] === 'function')
        proxy[prop] = target[prop].bind(target);
    }
  );

  Object.setPrototypeOf(proxy, target);
  return proxy;
};

var scriptDoc = document.currentScript.ownerDocument;

var windowProxy = {
  document: scriptDoc,
  addEventListener: scriptDoc.addEventListener.bind(scriptDoc)
};
windowProxy.window = windowProxy;
windowProxy = createProxyOf(window, windowProxy);
windowProxy.ifProxy = true;

+function() {
  var _global = window.global;
  window.global = windowProxy;
  with(windowProxy) {
    require('babel-core/lib/api/browser');
  }
  window.global = _global;
}.bind(windowProxy)();
```
`with` statement is deprecated but here it fits perfectly. I've just noticed Babel doesn't support `with` statement -- I hope my example will seduce Babel team to support it.  

Now you may browserify this code and then in your imported webcomponent add:
```html
<script src="./wrappedBabel.js"></script>
```
And anywhere in your imported document:
```html
<script type="text/babel">
  console.debug('You may use ES2015 below!');
  class Test {
    test() {
      console.log('From babel!');
    }
  }
  var test = new Test;
  test.test();
  Polymer({...});
</script>
```
Be aware that `text/babel` scripts are executed after normal script tags.

**Comment by tylerdmace** [comment]
I'm not sure if this is the right implementation but a solution to this is something I am interested in. Web components are going away and I'd really like to have something in place to facilitate ES2015 along side them.

**Comment by sebmck** [comment]
Feel free to submit a PR to [packages/babel-core/src/api/browser.js](https://github.com/babel/babel/blob/development/packages/babel-core/src/api/browser.js).

**Comment by thejameskyle** [comment]
Moving to #2354
