### ISSUE TITLE
Unnecessary loop with es6.parameters and single rest argument

### ISSUE THREAD

**Issue by andyearnshaw** [babel/babel#2348]
Quite a minor gripe, but the following:

```javascript
(...b) => {
  something.apply(this, b);
};
```

compiles to:

```javascript
(function () {
  for (var _len = arguments.length, b = Array(_len), _key = 0; _key < _len; _key++) {
    b[_key] = arguments[_key];
  }

  something.apply(undefined, b);
});
```

When it could just compile to:

```javascript
(function () {
    something.apply(undefined, arguments);
});
```

Could this be optimised?

**Comment by loganfsmyth** [comment]
There's no way of knowing that `something` is a function in this code, so `apply` could be anything, and passing `arguments` outside of a function can cause deoptimization.

**Comment by andyearnshaw** [comment]
Interesting, I wasn't aware of this pitfall. For anyone else's reference, there's some background on this over at https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#user-content-32-leaking-arguments.

**Comment by loganfsmyth** [comment]
@sebmck Is this worth considering as an optimization if we can statically know that `something` is a function?

**Comment by andyearnshaw** [comment]
If it can't be optimised this way, what about a loose mode option for those of us who are aware of the deopts?

**Comment by jmm** [comment]
@loganfsmyth Also only if nothing else (aside from `Function.prototype.apply` calls) in the function references the rest param, of course.
