### ISSUE TITLE
Use decorators in production

### ISSUE THREAD

**Issue by filipedeschamps** [babel/babel#2349]
@sebmck Is a good idea to use decorators in production?

Here where I work we are having a huge discussion about the ratio between the benefits/risks of this feature and we can't get to a conclusion. We are rebooting our api, and it's a big one.

What's your opinion about using a proposal feature?

Best regards

**Comment by loganfsmyth** [comment]
@filipedeschamps This seems like a discussion better suited for Slack.

From the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is exclusively for bug reports and feature requests.
