### ISSUE TITLE
bootstrap script hangs when a babel dependent is installed globally

### ISSUE THREAD

**Issue by spicyj** [babel/babel#2351]
This line was hanging (or at least, taking a very long while) on my machine:

https://github.com/babel/babel/blob/436ba9b6536ae194bd265f91311f411fe1ae1e82/scripts/bootstrap.js#L7

But I tried running the command manually and it completed quickly. I started to dig in to what was happening:

```
$ npm list --global --depth 1 babel
/usr/local/lib
└─┬ jscodeshift@0.3.4
  └── babel@5.8.21
```

Uninstalling jscodeshift globally seemed to fix the issue and the bootstrap script worked again. If this isn't trivially reproable I can try to dig more into my setup to see what's wrong.

**Comment by sebmck** [comment]
That line was just migrated from the original shell script and isn't really necessary. It's currently been changed to just [this](https://github.com/babel/babel/blob/development/scripts/bootstrap.js#L7-L9) in the `development` branch.

**Comment by spicyj** [comment]
:+1:
