### ISSUE TITLE
Requiring external module babel-core/register

### ISSUE THREAD

**Issue by CubixSystem** [babel/babel#2358]
```cmd
>node -v
v4.0.0

>babel --version
5.8.23 (babel-core 5.8.23)

>gulp -v
[07:58:34] Requiring external module babel-core/register
[07:58:34] CLI version 3.9.0
[07:58:34] Local version 3.9.0
```
This message appears after move from ```io.js v3.3.0``` to ```node v4.0.0```

**Comment by sebmck** [comment]
What's the question/problem here? There's not enough information.

**Comment by CubixSystem** [comment]
Thanks for fast response.
I can't run ```gulpfile.babel.js``` after switch from ```io.js``` to ```node```

In my project directory: 
```cmd
>gulp
[08:07:00] Requiring external module babel-core/register
```

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by CubixSystem** [comment]
Sorry for this Issue, ```npm rebuild``` works for me, as you say in #2343
