### ISSUE TITLE
async function w/ no await could be optimized to just promise.resolve

### ISSUE THREAD

**Issue by jaredly** [babel/babel#2360]
Unless I understand async/await insufficiently (which might well be the case), it seems like:

```js
async function hello() {
  return "world";
}
```

Could just be translated to:
```js
function hello() {
  return Promise.resolve("world");
}
```

as opposed to:
```js
function hello() {
  return regeneratorRuntime.async(function hello$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        return context$1$0.abrupt("return", "world");
      case 1:
      case "end":
        return context$1$0.stop();
    }
  }, null, this);
}
```

Now, it might be that nobody makes an async function that doesn't have `await` in it...

**Comment by stefanpenner** [comment]
I believe if this is to be addressed, it should likely be addressed in regenerator.

**Comment by loganfsmyth** [comment]
Also, this doesn't take potential exceptions into account. This would throw synchronously instead of returning a rejected promise.

**Comment by jaredly** [comment]
hmmm true.

**Comment by zloirock** [comment]
@stefanpenner `babel` has async functions transform w/o `regenerator`.

@loganfsmyth `Promise` constructor instead of `Promise.resolve` will solve this problem.

Some optimisations for async functions looks interesting, for example, simple promise chain if it's possible, but the current example does not look like very useful.

**Comment by stefanpenner** [comment]
> @loganfsmyth Promise constructor instead of Promise.resolve will solve this problem.

:+1: 

> @stefanpenner babel has async functions transform w/o regenerator.

ah did not realize this changed, good to know

**Comment by jaredly** [comment]
A more realistic example:

```js
async function doSomething() {
  // some stuff w/o await in it
  return await doSomethingElse()
}
```
Then all you need is
```js
function doSomething() {
  return new Promise(function (resolve, reject) {
    // some stuff w/o await in it
    resolve(doSomethingElse())
  });
}
```
