### ISSUE TITLE
regenerator buggy when pass falsy this value to async function

### ISSUE THREAD

**Issue by hax** [babel/babel#2362]
```js
function test1() {
	console.log(this, typeof this)
}

async function test2() {
	console.log(this, typeof this)
}

const x = 0
x::test1()
x::test2()
```

expect output both `0 'number'`, but got `0 'number'` and `null 'object'`.

All falsy values such as empty string will trigger this bug. 

asyncToGenerator/bluebirdCoroutines do not have this bug.

**Comment by jmm** [comment]
@hax Should this be reported on [`regenerator`](https://github.com/facebook/regenerator)?

**Comment by jmm** [comment]
Hmm, or maybe this doesn't even involve `regenerator`?: https://github.com/babel/babel/issues/2360#issuecomment-139592982.

**Comment by loganfsmyth** [comment]
Filed over in regenerator since it is their issue. They do

    self || null

so any falsy context value is coerced to `null`.

**Comment by zloirock** [comment]
@jmm in this comment I mean primarily `asyncToGenerator` transformer.

**Comment by loganfsmyth** [comment]
The regenerator fix has landed, looks like we need to bump the regenerator version in `babel-core` so this gets picked up?

**Comment by jmm** [comment]
@zloirock Oh, ok, thanks for cluing me in. I'll have to take a look at that sometime.

**Comment by loganfsmyth** [comment]
Closing this since the regenerator version was just bumped in https://github.com/babel/babel/pull/2414. Next release should have this all fixed.
