### ISSUE TITLE
block scoping wrapper function breaks arrow function arguments reference

### ISSUE THREAD

**Issue by jRiest** [babel/babel#2364]
Not sure what to title this bug as it seems like it's just some strange behavior in an edge case, and I'm not sure what in particular is causing the issue.

In the snippet below, the arguments that get passed to `fn` are the arguments from the outer (`wrapper`) function instead of the arguments to the inner function like I would have expected.

```js
function wrapper(fn) {
  return (...args) => {
    if (someCondition) {
      const val = fn(...args);
      return val.test(() => {
        console.log(val);
      });
    }
  };
}
```

Gets compiled to

```js
"use strict";

function wrapper(fn) {
  var _arguments2 = arguments;

  return function () {
    var _arguments = _arguments2;

    if (someCondition) {
      var _ret = (function () {
        var val = fn.apply(undefined, _arguments);
        return {
          v: val.test(function () {
            console.log(val);
          })
        };
      })();

      if (typeof _ret === "object") return _ret.v;
    }
  };
}
```

However, removing the `if (someCondition)` or removing the reference to `val` from the innermost function seems to restore expected behavior.

**Comment by jkoudys** [comment]
Seeing similar behaviour, where
```javascript
const t = str => {
  const args = Array.from(arguments);
  return args.shift().replace(/%(s|d)/g, () => args.shift());
};
```
compiles to
```javascript
var t = function t(str) {
  var args = Array.from(_arguments2);
  return args.shift().replace(/%(s|d)/g, function () {
    return args.shift();
  });
};
```
and while `arguments` could be `["Sign in to %s", "Foo's Site"]`, _arguments2 is `[function anonymous(e), > Object, > Object, function e(t, n, r), > Object, > Object, > Array[1]]`.

**Comment by loganfsmyth** [comment]
@jkoudys Could you clarify what you mean? That conversion seems reasonable to me.

**Comment by jkoudys** [comment]
It's pushing the locally scoped _arguments2 outside the actual scope of the function. e.g.
```javascript
function t(str) {
	const args = Array.from(arguments);
	return args.shift().replace(/%(s|d)/g, () => args.shift());
}

console.log('hello %s', 'world');
```
babels to:
```javascript
'use strict';

function t(str) {
	var args = Array.from(arguments);
	return args.shift().replace(/%(s|d)/g, function () {
		return args.shift();
	});
}

console.log('hello %s', 'world');
```
Which works just fine, but:
```javascript
const t = str => {
  const args = Array.from(arguments);
  return args.shift().replace(/%(s|d)/g, () => args.shift());
};

console.log(t('hello %s', 'world'));
```
becomes:
```javascript
'use strict';

var _arguments = arguments;
var t = function t(str) {
  var args = Array.from(_arguments);
  return args.shift().replace(/%(s|d)/g, function () {
    return args.shift();
  });
};

console.log(t('hello %s', 'world'));
```
In this simplified case, that's just an error because arguments isn't defined, but in practice (e.g. if browserify/webpack is wrapping my files in functions so it can use its client-side `require()`), it won't throw an error immediately, rather just give me a really bizarre error from using the browserify function's arguments.

**Comment by jkoudys** [comment]
```
$ babel --version
5.8.23 (babel-core 5.8.25)
```

**Comment by sebmck** [comment]
There are no 'arguments' inside of arrow functions. It behaves just the same as 'this'.

**Comment by jkoudys** [comment]
Huh you're right: http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions-runtime-semantics-evaluation

I was comparing it to my Firefox 39.0 console's behaviour, but it looks like Firefox is wrong and babel is right. I'll open the bug with them instead. Pretty impressed to see a transpiler actually implement the spec more accurately than Mozilla!

**Comment by jkoudys** [comment]
For those following along, looks like Moz has known about this for a while, but it's still being actively discussed: https://bugzilla.mozilla.org/show_bug.cgi?id=889158

**Comment by danez** [comment]
I created a PR for this: #4635
