### ISSUE TITLE
Build compatibility recommendations for modules

### ISSUE THREAD

**Issue by timdp** [babel/babel#2365]
Currently, I publish npm modules by running Babel from Gulp in a prepublish step. That means that my Babel config needs to be conservative enough for any version of Node that I want to support (usually >=0.10). All I really use is `{optional: ['runtime']}`.

However, with io.js and now Node 4 out there, more and more of Babel's work is becoming unnecessary. Evidently, I can't optimize for this by selectively disabling transformers, as that would break compatibility with older Nodes. I guess polyfills for `Promise`, `System` and such don't hurt that badly, but transpiling stuff like `class`, `const`, iterators, and generators can probably affect performance dramatically.

Hence my question: are there any recommendations for delivering code optimized for different versions of Node? (This mostly extends to the browser and other runtimes as well.)

Personally, I see a few options:

- Keep using ES6 in npm modules the way I (and many others) currently do it, with an upfront transpilation step that uses conservative Babel options. Not that great, as explained above.

- Only use ES6 features that don't rely on complex transpilation. Requires a lot of discipline, and not that scalable and future-proof.

- Deliver the module in ES6 as-is and move the build step to the installation phase. I've come across a few that do this, but I have to say I'm not a fan of it because of the massive dependency list, longer installation times, and increased risk of errors.

- Package multiple builds with varying Babel options into one npm module and select the best one at runtime. Kind of like a universal binary that dynamically selects x86 or x64. This is an idea that I've been mulling over for a while. The package size would increase, but performance could potentially benefit greatly.

If there's documentation on this already, I apologize for not finding it. At any rate, I think this will become more of an issue as ES and Node mature, so it seems like something that should be documented at some point, and probably supported by some build tool.

So ... what are your thoughts, guys and gals?

**Comment by jmm** [comment]
Hello @timdp. While these are good questions, this isn't a good venue for them. Per the README, the issue tracker is only for bug reports and feature requests. The README does have some suggestions for where to ask support / general questions. You may also find #2338 interesting. Thanks!

**Comment by timdp** [comment]
All right. Sorry about the noise.

**Comment by jmm** [comment]
No problem :smiley: There may eventually be a forum, which would make it easier to discuss this kind of stuff, even though this isn't exactly specific to Babel.
