### ISSUE TITLE
Cannot modify/override es6 class constructor

### ISSUE THREAD

**Issue by Alphapage** [babel/babel#2367]
Hello,
I use es7 decorators to modify the constructor of my class.
Here is my code:
```javascript
@constructorOverride
class Test{
    constructor(){
    console.log("constructor");
}
    functest(){
        console.log("functest");
    }
}

function constructorOverride(target){
    target.prototype.constructor=function(){
        console.log("modified constructor");
    }
    target.prototype.functest=function(){
        console.log("modified functest");
    }
}
```
The constructor is never modified and it seems the prototype.constructor is never called, but functest is modified as required.

Is it a Babeljs limitation ? or can I achieve my request using another way ?

Thanks in advance for your help.

**Comment by jmm** [comment]
Hello @Alphapage. As mentioned in #2339, the issue tracker isn't used for general questions like this. I *think* that the target passed to a decorator function is the prototype (and if I'm correct, that's not explained

**Comment by Alphapage** [comment]
Es7 decorators is not the problem: target is the class.
The problem is that I need to change my class to add Test.prototype.constructor() in constructor like this:
```javascript
@constructorOverride
class Test{
    constructor(){
    console.log("constructor");
    Test.prototype.constructor();
}
    functest(){
        console.log("functest");
    }
}
```
I can modify Test.prototype.constructor because I call it manually, but I can't override all the constructor.
So,I think Babeljs must only transpile constructor to prototype.constructor, but it uses another way to generate the constructor to es5.
Could you tell me if I'm right?

**Comment by Agamennon** [comment]
I have the same issue, you should be able to override the constructor, there are too many use cases for this, as far as i can tell, looking at the proposal this should be considered a bug

**Comment by loganfsmyth** [comment]
Class-level constructors can return a new constructor function that replaces the decorated, so instead of
```
@constructorOverride
class Test{
    constructor(){
        console.log("constructor");
    }
}

function constructorOverride(target){
    target.prototype.constructor=function(){
        console.log("modified constructor");
    }
}
```
you do

```
@constructorOverride
class Test{
    constructor(){
        console.log("constructor");
    }
}

function constructorOverride(target){
    return class extends target {
        constructor(...args) {
            console.log("modified constructor");
            super();
        }
    };
}
```

**Comment by Rob-pw** [comment]
@loganfsmyth wizardry! Thank you for that!
