### ISSUE TITLE
Allow object keys to be named using template string

### ISSUE THREAD

**Issue by gajus** [babel/babel#2368]
Please direct me to the correct resource if babel/babel is not the right place to raise this issue. I cannot find where this is described in the standard.

```js
{
    `top-left`: `value`
}
```

This produces an error in Babel at the moment.

```
repl: Unexpected token (2:14)
  1 | {
> 2 |     `top-left`: `value`
    |               ^
  3 | }
```

Even this does not work:

```js
{
    [`top-left`]: `value`
}
```

**Comment by zloirock** [comment]
[`ObjectLiteral`](http://www.ecma-international.org/ecma-262/6.0/#sec-object-initializer) supports as property names `IdentifierName`, `StringLiteral` and `NumericLiteral`, it does not contain template literal. [`StringLiteral`](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-string-literals) does not contain template literal too. Templates in computed property [works](https://goo.gl/2SaMQz).
