### ISSUE TITLE
can babel.transform.fromAst  without any transformer ?

### ISSUE THREAD

**Issue by rachardking** [babel/babel#2370]
like babel.transform.fromAst(result,{whitelist:[]})

**Comment by sebmck** [comment]
There's not enough information here. What is it you want to do?

**Comment by sebmck** [comment]
Regardless, this is a question. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by rachardking** [comment]
yes, i want use babel.parse(code), and modify ast, and transfrom to code
