### ISSUE TITLE
Babel places this (context) in the wrong place

### ISSUE THREAD

**Issue by equinox7** [babel/babel#2375]
The code I wrote:
```javascript
'use strict';

(function () {
	
	var app = {
		
		init: () => {
			var me = this;
			me.foo = me.getFoo();
		},
		
		getFoo: () => {
			return 'foo';
		}
		
	};
	
	return {
		init: app.init.bind(app)
	}
	
}()).init();
```

The code I get after using gulp-babel:
```javascript
'use strict';

(function () {
	var _this = this;

	var app = {

		init: function init() {
			var me = _this;
			me.foo = me.getFoo();
		},

		getFoo: function getFoo() {
			return 'foo';
		}

	};

	return {
		init: app.init.bind(app)
	};
})().init();
```

And I have an error in browsers's console: **Uncaught TypeError: Cannot read property 'getFoo' of undefined**. So, there is wrong **this**.
I think the line `var _this = this;` shouldn't be here and instead of line `var me = _this;` there should be `var me = this;`. Is it a bug ?

**Comment by sebmck** [comment]
Nope. This is how arrow functions work, please see the [FAQ](https://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-) as well as previous issues #842, #814, #733 and #730.

**Comment by equinox7** [comment]
Thank you for your answer. So, it should work so even when I bound that function to the object ?

**Comment by sebmck** [comment]
@equinox7 Binding an arrow function has no effect.

**Comment by equinox7** [comment]
Thanks, this is useful information. Sorry that I took your time.
