### ISSUE TITLE
Issue with shadowed bindings not being accurately renamed

### ISSUE THREAD

**Issue by bradencanderson** [babel/babel#2378]
The way that babel is renaming identifiers is a little flaky. This gets corrupted:

``` js
function foo(a) {
  var a = a;
  return {a: function() {return a;}};
}
```

It compiles to:

``` js
"use strict";

function foo(a) {
  var _a = _a;
  return { a: function a() {
      return _a;
    } };
}
```

**Comment by eventualbuddha** [comment]
Isn't this expected behavior? What would you expect to happen?

**Comment by bradencanderson** [comment]
The parameter name should be renamed to _a also.

**Comment by eventualbuddha** [comment]
@bradencanderson I believe you're right. Sorry for the confusion!

**Comment by hzoo** [comment]
outputs
```
function foo(a) {
  var a = a;
  return { a: function () {
      return a;
    } };
}
```

in the repl now

**Comment by danharper** [comment]
@hzoo It doesn't look like `function-naming` ran on that example. On the current live repl I still get:

```js
"use strict";

function foo(a) {
  var _a = _a;
  return { a: function a() {
      return _a;
    } };
}
```

**Comment by kangax** [comment]
Pretty bizarre how with Babili I get correctly renamed version:

```js
"use strict";function foo(b){var b=b;return{a:function a(){return b}}}
```

yet, it's still messed up w/o it:

"use strict";

```js
function foo(a) {
  var _a = _a;
  return { a: function a() {
      return _a;
    } };
}
```
