### ISSUE TITLE
Property initialisation caused "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by johnnyreilly** [babel/babel#2380]
I've encountered a problem when creating a class with a property whose value is initialised in the constructor.  Consider the following:

```
class ClassWithAProperty {
  constructor() {
    this.hasChanged = false;
  }

  get hasChanged() {
    return this.hasChanged;
  }

  set hasChanged(hasChanged) {
    this.hasChanged = hasChanged;
  }
}

var instance = new ClassWithAProperty();
```

Unsurprisingly, the initialisation of `hasChanged` in the constructor leads to a "Maximum call stack size exceeded" error.  Infinity welcomes careful drivers.  You can reproduce this in the playground [here](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20ClassWithAProperty%20%7B%0D%0A%20%20constructor()%20%7B%0D%0A%20%20%20%20this.hasChanged%20%3D%20false%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20get%20hasChanged()%20%7B%0D%0A%20%20%20%20return%20this.hasChanged%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20set%20hasChanged(hasChanged)%20%7B%0D%0A%20%20%20%20this.hasChanged%20%3D%20hasChanged%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20instance%20%3D%20new%20ClassWithAProperty()%3B)

It's easily worked around by ensuring that the field that actually contains the value does **not** share the same name as the property whose value it stores. Eg:

```
class ClassWithAProperty {
  constructor() {
    this._hasChanged = false;
  }

  get hasChanged() {
    return this._hasChanged;
  }

  set hasChanged(hasChanged) {
    this._hasChanged = hasChanged;
  }
}

var instance = new ClassWithAProperty();
```

However, I wonder if it might be possible / worth detecting this sort of error and providing a more meaningful error message?

Just a thought - thanks for all your work on Babel by the way; love it!! :tulip:

**Comment by bradencanderson** [comment]
The ES6 class syntax appears nice and declarative, but because it's just sugar over old behavior there's no way to guarantee compile-time correctness. (This is because of `Object.defineProperty`.) Trivial cases could probably be covered statically but those cases generally aren't the ones that cause bugs.

**Comment by loganfsmyth** [comment]
Yeah, this seems impossible to check for at compile time. What if this same code had some extra logic that redefined the `hasChanged` setter in the constructor before your assignment? There are just as many ways to programatically make your first case valid as there are ways to make your second case invalid.
