### ISSUE TITLE
How to customize imports?

### ISSUE THREAD

**Issue by finom** [babel/babel#2381]
I'm writing a JS library and the size of resulting .min.js is very important. My lib has a lot of submodules which I'd like to move to es6. The problem is Babel makes heavy codings where I just need simply import or export some AMD module.

Is it possible to customize exports and imports?
I'd like to get this code converted:
```js
import X from 'x';
let y = new X();
export default y;
```
to:
```js
define(['x'], function(X) {
var y = new X();
return y;
});
```

**Comment by jmm** [comment]
Hello @finom, welcome to the Babel community. The issue tracker isn't used for general questions and support, per the README, which also lists some resources for that. Thanks! And the short answer to your question is, not that easily.

**Comment by finom** [comment]
Thank you anyway.
