### ISSUE TITLE
Add "extends" property to .babelrc

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#2383]
For people working on a suite of related modules that share common base settings, it would be useful if `.babelrc` files had an `extends` property, similar to that in [`.eslintrc`](http://eslint.org/docs/user-guide/configuring#extending-configuration-files).

**Comment by sebmck** [comment]
This has already been implemented in the `development` branch with the new `.babelrc` behaviour and will be released with Babel 6.0

**Comment by callumlocke** [comment]
awesome

**Comment by dietergeerts** [comment]
Must this be used with the extends cli optoin, or can we use an extends property in the babelrc file?
