### ISSUE TITLE
subclassof statement

### ISSUE THREAD

**Issue by silkentrance** [babel/babel#2384]
How about a subclassof statement added to the language spec?

Having only instanceof or Object.prototypeOf seems to be incomplete to me, as both instanceof and Object.prototypeOf require instances.

Whereas a subclassof would only require a prototype inheritance chain.

Please see https://github.com/vibejs/vibejs-subclassof/blob/master/src/subclassof.coffee.

As of now, there seems to be no \__super__ or similar property defined on the class, so that I would be able to determine the super class of a given class, or is there?

**Comment by sebmck** [comment]
Babel isn't going to add any syntax that isn't on standards track, sorry.
