### ISSUE TITLE
[Flow] Typed arrow functions that return functions

### ISSUE THREAD

**Issue by JohnyDays** [babel/babel#2386]
The following fails compilation: 

```javascript
export default (x: string) : function => {
  return () => {}
}
```

with:

![image](https://cloud.githubusercontent.com/assets/4540763/9904741/1065dbf2-5c78-11e5-9db5-9c3bd120301f.png)

And if I omit the argument, it fails with a different error, e.g:

```javascript
export default () : function => {
  return () => {}
}
```

fails with:

![image](https://cloud.githubusercontent.com/assets/4540763/9904715/d8af2fd8-5c77-11e5-95cb-bc4c34ebc780.png)

If the return type is not `function`, they both compile correctly (tested with `any`)

Both of these examples parse correctly under flow, with working type-checking. I tested it in a more complex example I can show if necessary. 
I am using babel compiled from master, and also flow compiled from master

[Edit] 
After further testing, it appears doesn't support the `function` type, anywhere (i'm guessing because it's a reserved keyword?) 

I tried

``` javascript 
function t(x: function) : string { return x }
```
which also fails, and

``` javascript 
var t : function = () => {}
```
which also fails

**Comment by sebmck** [comment]
Both cases are because you're using the `function` keyword, I'm not even sure what that's supposed to mean in the context of a type annotation. Use `Function`.

**Comment by JohnyDays** [comment]
Flow appears to support it, which might confuse people (potentially). But `Function` did work, so i'll close it.
