### ISSUE TITLE
Better error output for await in non-async functions

### ISSUE THREAD

**Issue by SystemParadox** [babel/babel#2387]
```
function test() {
    await foo();
}
```

Throws:
```
Unexpected token(2:8)
```

This is a bit misleading. Can we change this to say something like "await can only be used in async functions"?

Thanks.

**Comment by zloirock** [comment]
+1. Too frequent issues about this case.

**Comment by sebmck** [comment]
@zloirock Do you have references? I can't recall any. There are a bunch of places where we could output more useful error messages for certain scenarios (but makes it much more confusing in others) but there's nothing misleading about this being an unexpected token.

**Comment by zloirock** [comment]
@sebmck I remember 5-10 in different chat rooms, will find in the tracker.

**Comment by zloirock** [comment]
In this repo found only #2180 and #1902, looks like most in chats / another repos.

**Comment by JohnyDays** [comment]
+1 ran into this myself, it's pretty easy to figure out once you're accustomed to working with async/await, but it can be a pain when you're starting out

**Comment by SystemParadox** [comment]
Unexpected token implies to me that it's a missing/incorrect symbol, or a
keyword somewhere random. In other words, a syntax error.

But this isn't a syntax error. It's a semantic error. It's only unexpected
because the function isn't in async mode. Apart from the absence of the
async specifier, it's a totally valid token.

If the parser thinks async functions and regular functions are completely
different things, fine (although I don't see why this would be the case),
but I seriously doubt the programmer does. An async function is a
particular type of function, but it's still a function.

**Comment by fkling** [comment]
@SystemParadox: You could make that argument for many other syntax errors, e.g. `function(){}`. Function declarations need names so this is a syntax error. Even though they create the same kind of object at runtime, the *syntax* of function declarations and function expressions are different. Similarly the syntax of an async function is different from a "normal" function. If you don't follow the syntax, it's a *syntax error*.

I do agree though that more detailed error messages are useful.

**Comment by thejameskyle** [comment]
This sounds like a job for a linting tool. I don't know that it belongs in Babel itself though.

**Comment by danez** [comment]
Moved to https://github.com/babel/babylon/issues/113
