### ISSUE TITLE
`arguments` used in arrow functions is not correctly compiled

### ISSUE THREAD

**Issue by leungwensen** [babel/babel#2388]
consider source code in ES6-format as below:

```javascript
function met(args) {
    return new Error(args);
}
let issue = {
    when: arrow => met(arguments)
};
export default issue;
```

babel compiles it into:

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
var _arguments = arguments;
function met(args) {
    return new Error(args);
}

var issue = {
    when: function when(arrow) {
        return met(_arguments);
    }
};

exports["default"] = issue;
module.exports = exports["default"];
```

which replaces `arguments` inside an arrow function with a global one, this is wired.

**Comment by sebmck** [comment]
This is expected behaviour, it's how arrow functions work. See the [FAQ](https://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-) and linked issues.

**Comment by leungwensen** [comment]
Oh I see, sorry, I should've read through FAQ first. Thank you for your help!
