### ISSUE TITLE
Question: I am having a hard time figuring out why babel generates code like (0, ...)()

### ISSUE THREAD

**Issue by silkentrance** [babel/babel#2390]
I am developing a small library and am wondering why upon

```
import {className} from './util';

class foo {}

console.log(className(foo));
``` 

such code will be generated (leaving out the import and class stuff)

```
console.log((0, _util.className)(foo));
```

What does the (0, ...) actually do? Isn't it kind of bogus?

**Comment by sebmck** [comment]
See the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by sebmck** [comment]
The issue that lead to that behaviour is #1514.

**Comment by silkentrance** [comment]
@sebmck thanks for the issue link
