### ISSUE TITLE
'use strict' placement causes /* istanbul ignore next */ to fail

### ISSUE THREAD

**Issue by elliottsj** [babel/babel#2391]
Similar to #1583:

This input:
```js
/* istanbul ignore next */
exports.directive = function(emAngular, OrganizerDetailsRest) {
  'ngInject';
  ...
};
```

causes the generated `'use strict';` statement to appear right below the leading `/* istanbul ignore next */`:

![screenshot 2015-09-16 18 17 35](https://cloud.githubusercontent.com/assets/2177366/9920120/6abd1a8a-5c9f-11e5-870a-d5909ba4386c.png)

Which causes istanbul to ignore the `'use strict';` instead of the intended function.

**Comment by elliottsj** [comment]
I'm using babel-core@5.8.24, babel-loader@5.3.2, istanbul-instrumenter-loader@0.1.3

**Comment by huston007** [comment]
I have same issue when using Babel with ng-annotate https://github.com/huston007/ng-annotate-loader/issues/13

I believe the 'use strict'; should be added before any comments.

**Comment by sebmck** [comment]
Fixed in the `development` branch. I really hate ng-annotate.

**Comment by elliottsj** [comment]
Awesome, thanks!

For anyone using v5.x stumbling upon this issue, my current workaround is to place the 'ignore' statement like this:

```js
export /* istanbul ignore next */ function directive() {
  // ...
}
```
