### ISSUE TITLE
Importing default where there is none or by (aliased) key where the key is missing gives users a very hard time finding out the actual error

### ISSUE THREAD

**Issue by silkentrance** [babel/babel#2392]
Consider having a foo module that

```
export default function foo() {}
```

and a second module that imports

```
import {foo} from './foo';
```

When using foo, it will always be undefined. Of course, the correct statement would have been

```
import foo from './foo';
```

However, the transpiler will not report the bogus usage as an error, leaving the user with a hard time figuring out the actual error.

How about reporting such misuse of the import statement, or better yet, not only export foo as the default but also as a named item of the module?

**Comment by loganfsmyth** [comment]
This sounds like a good idea to me, at least as an optional feature. The spec says unresolved imports should throw a `SyntaxError` in [12.d.iii](http://www.ecma-international.org/ecma-262/6.0/#sec-moduledeclarationinstantiation). At least for CommonJS, we'd need to pre-define all exports at the start of a module, e.g.

     exports.default = exports.blah = exports.other = undefined;

then add a check for every imported name via `hasOwnProperty`.

**Comment by sebmck** [comment]
> How about reporting such misuse of the import statement, or better yet

You can't tell.

> not only export foo as the default but also as a named item of the module?

This isn't spec compliant.

**Comment by eventualbuddha** [comment]
If babel were to look at the relationships between files then it could report on misuses like this, but it doesn't. Even if it wanted to it could likely only look at files imported relative to the files being processed, otherwise it'd have to divine your file resolution scheme.

For something like this I recommend rollup.

**Comment by silkentrance** [comment]
@loganfsmyth SyntaxError seems to be quite impossible to achieve, since it would require all imported modules/packages to be available at compile time.

@sebmck I think that this cannot be resolved at compile time, as it would require static analysis of all imports, and they would have to be available at compile time. Therefore I would suggest to put additional checks into the runtime, e.g. when import {...} something, the requested key must be present or a RuntimeError or similar error will be thrown by the helpers. Likewise, when trying to default import something from where there is no default export, a similar exception will be thrown.

**Comment by loganfsmyth** [comment]
@silkentrance `SyntaxError` doesn't mean it would have to be a transpile-time error. I'm simply saying that if we were being spec-compliant, running the code with an invalid import should throw an instance of `SyntaxError`.

I agree that this isn't easily solvable at compile time. The `additional checks` you mention is just what I tried to describe in my first comment.

**Comment by silkentrance** [comment]
@loganfsmyth OK, then I am all in for SyntaxError.

**Comment by thejameskyle** [comment]
>  I'm simply saying that if we were being spec-compliant, running the code with an invalid import should throw an instance of SyntaxError.

I don't know that this is reliably possible to do. You could attempt to add properties to generated output that could be read by helpers in other generated code, but theres all sorts of problems with that.

Since Babel doesn't do any cross-file compilation, I'm going to close this as a wontfix since it's the job of another tool today. Other contribs feel free to reopen this issue if you disagree.

**Comment by jacobp100** [comment]
Maybe we could skip the check in loose mode? This is something I do a lot, so it would be really useful to get some feedback when it happens (not to mention it is in the spec).
