### ISSUE TITLE
React inlining: children (if present) should overwrite props.children

### ISSUE THREAD

**Issue by spicyj** [babel/babel#2395]
```js
$ echo '<div children="foo">bar</div>' | babel -r --whitelist optimisation.react.inlineElements
({
  $$typeof: babelHelpers.typeofReactElement,
  type: "div",
  key: null,
  ref: null,
  props: {
    children: "bar",
    children: "foo"
  },
  _owner: null
});
```

but the children should actually be 'bar'. I think this can be fixed just by processing the children here after the props:

https://github.com/babel/babel/blob/5a5e72f0bdea731d96a703914f5a29d5777f1fff/packages/babel/src/transformation/transformers/optimisation/react.inline-elements.js#L66

See ReactElement.js for reference:

https://github.com/facebook/react/blob/e147c4942b6b0c5df426cadd1c7e88f3d2956233/src/isomorphic/classic/element/ReactElement.js#L144-L155

**Comment by thejameskyle** [comment]
Just a matter of looking for and replacing the `children` property if it exists.
