### ISSUE TITLE
await is a keyword in async functions

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#2396]
```js
async function foo () {
  let await = 1;
}
```
should throw unexpected token error

**Comment by thejameskyle** [comment]
Can you link to the relevant part of the spec? I'm not seeing anything that states that.

cc @bterlson

**Comment by loganfsmyth** [comment]
http://www.ecma-international.org/ecma-262/6.0/#sec-future-reserved-words

**Comment by bterlson** [comment]
[AsyncFunctionBody](http://tc39.github.io/ecmascript-asyncawait/#prod-AsyncFunctionBody) passes the Await parameter to FunctionBody. Per the rule at the start of [Clause 5](http://tc39.github.io/ecmascript-asyncawait/#modified-productions), this Await parameter will be propagated to statements and expressions inside the function (but not into nested functions or classes or other such things). You can only parse `await` as a BindingIdentifier when the Await parameter is not present (see the [modified BindingIdentifier production](http://tc39.github.io/ecmascript-asyncawait/#Identifiers)).

This should be identical to how yield is handled.

**Comment by bterlson** [comment]
Note that await is only reserved when module is the goal symbol (in order to preserve the option of allowing await at top-level of a module). It is not reserved in scripts in either strict or non-strict mode.

**Comment by thejameskyle** [comment]
Thanks

**Comment by sebmck** [comment]
Fixed in the `development` branch due out for Babel 6.
