### ISSUE TITLE
Flow plugin ignores intersection and union operators precedence

### ISSUE THREAD

**Issue by popham** [babel/babel#2397]
Under a fresh babel install from `npm` (5.8.23),  `babel -b flow` maps

``` js
function k(p: I & (J | K)) {
  p.m();
}
```

to

``` js
"use strict";

function k(p: I & J | K) {
  p.m();
}
```

Since `&` has higher precedence than `|` (see [intersection.exp](https://github.com/popham/flow/blob/intersect-prec/tests/intersection/intersection.exp#L2-L8), [assoc.js](https://github.com/popham/flow/blob/intersect-prec/tests/intersection/assoc.js), and [the passed test](https://travis-ci.org/popham/flow/jobs/80765062#L333)), this is causing errors in my code :(.

**Comment by sebmck** [comment]
It's even worse than that. We don't actually perform any sort of precedence checking when outputting flow types.

**Comment by popham** [comment]
Zoiks!  My reasoning for blacklisting Flow is to pretty print some generated code.  I've been doing a bit of algebra to get this working, e.g. `I & (J | K)` maps to `I & J | I & K`.  Not a big deal from my perspective.  (Unfortunately, Babel is still a black box to me: it'll be a long while before I get around to a pull request :(.)

**Comment by sebmck** [comment]
I think we only need to handle Intersections and unions so it should be fairly straight forward to support. I'll take a crack at it when I can.

**Comment by popham** [comment]
Caveat:

I've recently discovered that this works a little goofy under Flow: https://github.com/facebook/flow/issues/824.  The precedence for Flow is not documented.  

* From [this](https://github.com/facebook/flow/blob/70dfcfe09b8ebf4ca1cbb660a89ce7d5eb3319c6/src/parser/parser_flow.ml#L245-L246), I believe the intention is that `&` has higher precedence than `|`.
* It makes sense to me that Flow's precedence should match that of JS; this reasoning also implies that `&` has higher precedence than `|`.

**Comment by hzoo** [comment]
@popham what was the result of this? was this just a bug in flow?

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
