### ISSUE TITLE
Super calls in code transpiled with Babel is really slow.

### ISSUE THREAD

**Issue by trusktr** [babel/babel#2399]
Check out this perf test:

http://jsperf.com/es6-classes-super-es5-vs-transpiled/2

Can something be done about this?

**Comment by zloirock** [comment]
See #451. In loose mode it's enough fast.

**Comment by loganfsmyth** [comment]
Have you considered using `loose` mode classes? It outputs code like your ES5 version, it is just less spec compliant.

**Comment by thejameskyle** [comment]
Yup, not a lot that can be done working within the spec. If you need it, loose mode is there for you.
