### ISSUE TITLE
Compile error on Flow-Typed arrow function

### ISSUE THREAD

**Issue by jasonkuhrt** [babel/babel#2400]
This confuses babel (the compile error falls down the source file):

```js
const find = <X> (f: (x:X) => X, xs: Array<X>): ?X => (
  xs.reduce(((b, x) => b ? b : f(x) ? x : null), null)
)
```
```
SyntaxError: lib/utils.js: Unexpected token (25:2)
  23 |
  24 | const equalRecords = (o1, o2) => {
> 25 |   for (const key in o1) if (o1[key] !== o2[key]) return false
     |   ^
  26 |   return true
  27 | }
  28 |
```

But using `function` variant works just fine:

```js
const find = function <X> (f: (x:X) => X, xs: Array<X>): ?X {
  return xs.reduce(((b, x) => b ? b : f(x) ? x : null), null)
}
```

**Comment by sebmck** [comment]
Why are you under the assumption that it's valid? Does it work in Flow?

**Comment by sebmck** [comment]
Yeah this isn't valid. There's already ambiguity with a JSX expression starting tag. I've confirmed that this is invalid in the Flow parser too.

**Comment by jasonkuhrt** [comment]
Hm, but how are Flowtype annotations of arrow-function expressions supposed to work then?

**Comment by sebmck** [comment]
Just use a normal function.

**Comment by jasonkuhrt** [comment]
Yes, like:

```js
const find = function <X> (f: (x:X) => X, xs: Array<X>): ?X {
```

But that wasn't my question nor what this issue was about. Currently today babel will not parse a variant of type annotations of arrow-function syntax, correct? This is clearly a bug/missing feature. Is the problem that we don't have parser instructions from Flowtype on this?

**Comment by sebmck** [comment]
Flow doesn't support it so Babel doesn't, Babel supporting some type annotation syntax is pointless unless Flow does. It's impossible to support what you want too because of syntactic ambiguity with JSX.

**Comment by jasonkuhrt** [comment]
So once flow does support it then what? This abbreviated track of thought doesn't make much sense. Its valid JavaScript. One project will make accommodations for another unrelated technology? Ok. But anyways thanks I'll bring this issue to the flowtype repo since clearly if its not specified there then I don't expect babel too have it working either.

**Comment by sebmck** [comment]
> So once flow does support it then what?

Then the Flow team tell me and I add support for it to the Babel parser.

> One project will make accommodations for another unrelated technology?

It's a syntax extension. I'm not sure why you're making the connection that Babel supporting Flow syntax is unrelated?

> . But anyways thanks I'll bring this issue to the flowtype repo since clearly if its not specified there then I don't expect babel too have it working either.

Sorry but as I said it's impossible to support what you want because there's syntax ambiguity. You cannot start an expression with `<WHATEVER>` as it's already reserved for JSX.

**Comment by jasonkuhrt** [comment]
You are confused because you misunderstood me. JSX is unrelated to Flowtype.

**Comment by sebmck** [comment]
You're forgetting that Flow supports JSX.

**Comment by jasonkuhrt** [comment]
I've opened an issue there, we'll see what happens.

**Comment by samwgoldman** [comment]
Hi Sebastian! Flow does parse the following JS:

```
const find = <X>(f: (x: X) => bool, xs: X[]): ?X => {
  for (let x of xs)
    if (f(x))
      return x;
}
```

The `flow ast` output is reasonable, too.

Is it possible that Flow supports this annotation syntax in error?

**Comment by sebmck** [comment]
This is really weird. I'm not even sure how JSX is parsed in Flow then since this seems to be explicitly special cased?

```
const find = <X>(xs) => {}
```

and

```
const find = <X>(xs) => {}</X>
```

return completely different ASTs. Is this a return change? There weren't any tests for this in `esprima-fb` and I haven't been told of any syntax change. It seems like this should have been bought up alongside #1991.

**Comment by samwgoldman** [comment]
Here are some fun cases:

Here, find is a function:
```
declare var X: ReactClass;
const find = <X>(f: (x: X) => bool, xs: X[]): ?X => xs[0];
```

Now, as a ReactElement:
```
declare var X: ReactClass;
const find = <X>(f: (x: X) => bool, xs: X[]): ?X => xs[0];</X>
```

This is an error:
```
declare var X: ReactClass;
const find = <X>(f: (x: X) => bool, xs: X[]): ?X => {</X>
```

I know the parser has infinite lookahead support, but I haven't spent any time poking under the hood here. @gabelevi probably has more context on this.

**Comment by jasonkuhrt** [comment]
Has this issue been confirmed? Is it a bug? No labels yet, curious what I should expect in the future regarding this. Thanks the consideration to date.

**Comment by hzoo** [comment]
Looks like this parses now (on astexplorer/repl), not sure about generated output though

**Comment by danez** [comment]
Yes this seems to be solved in one of the latest babylon releases.

**Comment by hzoo** [comment]
The generated output is `const find = <X>(f, xs) => xs.reduce((b, x) => b ? b : f(x) ? x : null, null);`  so I guess we can call that a different bug

**Comment by danez** [comment]
Ok there is a minor range/location issue in babylon, reported it here https://github.com/babel/babylon/issues/111

@hzoo This is the output of strip-flow?

**Comment by hzoo** [comment]
Yeah the output of the repl with react preset - would be nice to specify specific stuff isntead

**Comment by danez** [comment]
ok i created https://github.com/babel/babel/issues/4483 as follow up
