### ISSUE TITLE
Double decimal points after hex numbers or numbers inside parentheses

### ISSUE THREAD

**Issue by toxicFork** [babel/babel#2402]
E.g. https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&code=0xffffff.toString(16) 

Expected output: 0xffffff.toString(16)
Actual output: 0xffffff..toString(16)

Edit: Also seems to be the case for (5).toString(16)
Gets turned into (5)..toString(16)

**Comment by alawatthe** [comment]
Hmm, the [repl](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&code=%285%29.toString%2816%29) turns ```(5).toString(16);``` to ```5..toString(16);``` which is correct.

I found the problem of the ```0xffffff.toString(16)``` error and am working on a fix.

**Comment by toxicFork** [comment]
Ah I see now why 5..toString(16) works... hmmm... not feeling great about that, but at least that's not too bad!

**Comment by toxicFork** [comment]
:+1:

**Comment by thejameskyle** [comment]
Moving to https://github.com/babel/babel/pull/2403
