### ISSUE TITLE
Double strict when using babel

### ISSUE THREAD

**Issue by rodoabad** [babel/babel#2404]
Here's the input file.

```javascript
(function () {

  'use strict';

  const angular = window.angular;

  function mainContainer() {

    return {
      restrict: 'E',
      templateUrl: 'packages/main-container/main-container.html'
    };

  }

  angular.module('app')
    .directive('mainContainer', [
      mainContainer
    ]);

}());
```

And here's the output.

```javascript
'use strict';

(function () {

  'use strict';

  var angular = window.angular;

  function mainContainer() {

    return {
      restrict: 'E',
      templateUrl: 'packages/main-container/main-container.html'
    };
  }

  angular.module('app').directive('mainContainer', [mainContainer]);
})();
```

I'm using the default settings.

**Comment by sebmck** [comment]
Nothing can really be done about this. The top level isn't in strict mode when it should be which is why the additional `"use strict";` is added. I guess a heuristic could be added to detect this specific case but it seems rather unnecessary and pointless. Also gzip will basically make the size difference 0.

**Comment by rodoabad** [comment]
But then you'll have multiple `'use strict';` when you concatenate files. Would that be a non-issue?

**Comment by sebmck** [comment]
You can't blindly concatenate files and have them work anyway. For example:

**a.js**

```
let foo = "foo";
```

**b.js**

```
let foo = "bar";
```


Running each of them independently will work fine but concatenating both of them and running the output will throw an error.

**Comment by rodoabad** [comment]
Oh, no. I'm not talking about that. I'm just saying that the concatenated unminified file will look like this.

```javascript
'use strict';

(function () {

  'use strict';

})();

'use strict';

(function () {

  'use strict';

})();

'use strict';

(function () {

  'use strict';

})();
```

But I realized that even if I move it up top it'll will just look like this.

```javascript
'use strict';

(function () {

})();

'use strict';

(function () {

})();

'use strict';

(function () {

})();
```

**Comment by sebmck** [comment]
Yeah I know. My point was that you shouldn't be blindly concatenating files like that anyway because it's unsafe. You're right that the subsequent directives will have no effect but any duplication is negated with the use of gzip.

**Comment by jmm** [comment]
@rodoabad 
> But then you'll have multiple 'use strict'; when you concatenate files. Would that be a non-issue?

As @sebmck has said, yes, it should be a non-issue. The spec does a say a warning could be issued if there are multiple Use Strict directives in the directive prologue, but in your examples there is only one in the directive prologue. The others are just no-op statements.

**Comment by rodoabad** [comment]
Shouldn't babel be aware of file concatenation?

It's a little unclear when you said repeated `'use strict';` directives are a non-issue but then concatenating files could be an issue.


No issue here.

```javascript

(function () {

  'use strict';

})();

(function () {

  'use strict';

})();

(function () {

  'use strict';

})();
```

Issue here.

```javascript
'use strict';

(function () {

  'use strict';

})();

'use strict';

(function () {

  'use strict';

})();

'use strict';

(function () {

  'use strict';

})();
```

Would blacklisting use strict solve this?

**Comment by sebmck** [comment]
@rodoabad Babel cannot generate concatenation-safe output, as demonstrated by my previous `let` collision example. That doesn't mean that concatenating useless `"use strict";` statements is dangerous, it's not, it's safe.

**Comment by thejameskyle** [comment]
Here's a good use for a Babel plugin.

You could easily build a plugin that takes:

```js
let foo = 1;
```

and outputs:

```js
(function() {
  'use strict';
  var foo = 1;
}());
```

This is pretty much it:

```js
export default function ({Plugin, types: t}) {

  // (function() {...}());
  function buildIIFE(body) {
    return t.expressionStatement(t.functionExpression(t.blockStatement(body), []));
  }
  
  return new Plugin('wrap-program-in-iife', {
    visitor: {
      Program: {
        exit(node) {
          node.body = [buildIIFE(node.body)];
        }
      }
    }
  });
}
```

You'll want to use it after all the built-in transformers:

```js
require('babel').transform('code', {
  plugins: ['wrap-program-in-iife:after']
});
```

Here's some documentation about plugins: http://babeljs.io/docs/advanced/plugins/

There's even a CLI tool for generating a plugin repo.

```sh
$ npm i -g babel
$ git init babel-plugin-wrap-program-in-iife && cd babel-plugin-wrap-program-in-iife
$ babel-plugin init
> Description (optional): Wrap Program in IIFE
> GitHub Repository (eg. sebmck/babel-plugin-foobar) (optional): rodoabad/babel-plugin-wrap-program-in-iife
```

This will create everything you need to get started.

**Comment by rodoabad** [comment]
@thejameskyle Thanks, that helps a lot.
