### ISSUE TITLE
this converts to undefined when used as a parameter for SEAF

### ISSUE THREAD

**Issue by Valve** [babel/babel#2406]
```javascript
(function(ctx){
  // code  
})(this);
```

gets transpiled to

```javascript
"use strict";

(function (ctx) {})(undefined);
```

Is this a bug? I use this pattern to refer to the global object from the SEAF

**Comment by zloirock** [comment]
[See FAQ.](https://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-)

**Comment by Valve** [comment]
thanks
