### ISSUE TITLE
Non-strict common output doesn't have exports = default when I have multiple exports

### ISSUE THREAD

**Issue by bfred-it** [babel/babel#2410]
> In order to encourage the use of CommonJS and ES6 modules, when exporting a default `export` **with no other exports** `module.exports` will be set in addition to `exports["default"].`

I found this behavior to be counter-intuitive: it works… until you export more variables. Definitely unexpected :(

This could be fixed by switching by having `module.exports = default` before other exports, added via `module.exports.doSomething = doSomething`

**Comment by jmm** [comment]
Hello @bfred-it, welcome to the Babel community! This seems to be a duplicate of #2047, so I'm going to close it. Please see the discussion there and also #2212.

**Comment by bfred-it** [comment]
Sorry about that! Searching completely slipped my mind :disappointed:

**Comment by jmm** [comment]
@bfred-it No problem, everybody forgets sometimes.

**Comment by forivall** [comment]
Your avatar is perfect for goof-ups like this.

**Comment by jmm** [comment]
@forivall I was thinking the same thing -- he looks duly chastened.

**Comment by bfred-it** [comment]
I goof up so often that I decided that everything I do online must be accompanied by that.
