### ISSUE TITLE
Destructuring transformer does not return ES5 code when destructuring function arguments

### ISSUE THREAD

**Issue by barlindhaug** [babel/babel#2411]
If I want to whitelist only the es6.destructuring transformer it uses lets and the output is no longer ES5 compliant. Should the es6.destructuring transformer be standalone?

Example script.js
```javascript
function add([a, b]) {
    return a + b;
}
```

Used like this

```
babel --whitelist es6.destructuring script.js
```

returns:

```javascript
var _slicedToArray = (function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; })();

function add(_ref) {
    var _ref2 = _slicedToArray(_ref, 2);

    let a = _ref2[0];
    let b = _ref2[1];

    return a + b;
}
```

My current workaround is including the es6.blockScoping transformer to the whitelist. Then Babel produces ES5 code.

```
babel --whitelist es6.destructuring,es6.blockScoping script.js
```

**Comment by sebmck** [comment]
This is intentional. Parameters are effectively treated as `let` as they have a TDZ. Converting them to `var`s would be inaccurate and would lose that important semantic.

**Comment by barlindhaug** [comment]
Ok, thanks for clearing this up.

I misunderstood, thinking that transformers can be whitelisted independently of each other, but destructuring depends on blockScoping to produce ES5 JavaScript.
