### ISSUE TITLE
static in babel

### ISSUE THREAD

**Issue by AnnatarHe** [babel/babel#2412]
I'm using babel now and I find a question.

when I run:
```js
class MyClass {
  static foo = 42;
}
```
and the I got an error:
```
repl: Unexpected token (2:13)
  1 | class MyClass {
> 2 |   static foo = 42;
    |              ^
  3 | }
```
I don't know how to fix it.

It is a bug or not?

node version: 4.1.0
babel version: 6.3.0

**Comment by JohnyDays** [comment]
Hey there @AnnatarHe, you need to activate. Static properties are still an early stage proposal for ES7, in order to use them with babel you need to activate stage 0. To do this, add a file called .babelrc to the folder in which you are using babel, with the contents:

/your-folder/.babelrc
```javascript
{
   "stage":0
}

**Comment by hzoo** [comment]
Docs are https://babeljs.io/docs/usage/experimental/. You can also do each one separately `{ optional: ["es7.classProperties"] }`

**Comment by AnnatarHe** [comment]
Thanks!
