### ISSUE TITLE
`super.foo()` only should work inside a method/arrow function in method

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2413]
```
class One {
    test() {
        console.log('test');
    }
 }

class Two extends One {
    test() {
        return new Promise(function(resolve, reject) {
          super.test();
        });
    }
}

var two = new Two();
two.test();
```

My understanding is that `super` should only work in this example for arrow functions, not for standard function expressions.

Came across this here: http://stackoverflow.com/questions/32710546/calling-super-methods-inside-separate-scope

**Comment by thejameskyle** [comment]
@loganfsmyth Can you link to the relevant part of that spec that describes this?

**Comment by loganfsmyth** [comment]
Should be http://www.ecma-international.org/ecma-262/6.0/#sec-makesuperpropertyreference and http://www.ecma-international.org/ecma-262/6.0/#sec-getsuperbase

My understanding is that only methods and arrow functions which inherit the `this` binding environment of a method are able to use `super.<foo>`.

**Comment by thejameskyle** [comment]
I'm confused about http://www.ecma-international.org/ecma-262/6.0/#sec-function-environment-records-hassuperbinding.

`HasSuperBinding ()`:

> If envRec.[[thisBindingStatus]] is "lexical", return false. [ref](http://www.ecma-international.org/ecma-262/6.0/#sec-function-environment-records-hassuperbinding)

`MakeSuperPropertyReference`:

> If env.HasSuperBinding() is false, throw a ReferenceError exception. [ref](http://www.ecma-international.org/ecma-262/6.0/#sec-function-environment-records-hassuperbinding)

`[[thisBindingStatus]]`:

> If the value is "lexical", this is an ArrowFunction and does not have a local this value. [ref](http://www.ecma-international.org/ecma-262/6.0/#sec-function-environment-records)

It seems like this is stating that it should only throw a ReferenceError if it's an ArrowFunction. Is the spec incorrect?

**Comment by jmm** [comment]
@thejameskyle It is super confusing, but I'm reading this the same way as @loganfsmyth. I think perhaps you're getting thrown off at `12.3.5.3 Runtime Semantics: MakeSuperPropertyReference(propertyKey, strict)`?:

> 1. Let env be `GetThisEnvironment( )`.

`8.3.2 GetThisEnvironment ( )`:

> The abstract operation `GetThisEnvironment` finds the Environment Record that currently supplies the binding of the keyword this.

So `HasSuperBinding()` is called on the environment record for the scope that contains the arrow function.

**Comment by loganfsmyth** [comment]
Yep, @jmm's point is the important part. Calling `HasSuperBinding` on an arrow function's environment does indeed fail, but `MakeSuperPropertyReference` explicitly calls `HasSuperBinding` on the `this` environment.

**Comment by thejameskyle** [comment]
Thanks @jmm @loganfsmyth that makes sense.

**Comment by sebmck** [comment]
Fixed in the `development branch due out for Babel 6.
