### ISSUE TITLE
whitelist is not working?

### ISSUE THREAD

**Issue by RobinQu** [babel/babel#2415]
Using babel 5.8.23

.babelrc

```
{
  "whitelist": [
    "es7.asyncFunctions",
    "es7.decorators"
  ]
}
```

My script:

```
class Foo {
static async load(options) {
   
 }
}
```

Compiles to:

```
class Foo {
static async load(options) {
   
 }
}
```

**Comment by sebmck** [comment]
The `es7.asyncFunctions` desugaring requires the `es6.classes` transformer. Please enable that if you want the expected behaviour.

**Comment by RobinQu** [comment]
Even for environments that support es6 classes?

**Comment by sebmck** [comment]
Yes.

**Comment by sebmck** [comment]
If you require any further assistance or have any other questions feel free to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

Thanks!

**Comment by RobinQu** [comment]
Where can I find the dependencies of a transformer?

**Comment by RobinQu** [comment]
And I don't understand why desugaring a async function requires es6 classes.

**Comment by felixfbecker** [comment]
I have the same issues. This needs to be documented. If I use Node 4 it makes no sense to me to transpile classes.

**Comment by felixfbecker** [comment]
This also doesn't work:
```
{
  "whitelist": [
    "es6.classes",
    "es7.asyncFunctions"
  ]
}
```
Input:
```js
app.use(async function (next) {

})
```
Output:
```js
app.use(async function (next) {

})
```

**Comment by thejameskyle** [comment]
> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by jmm** [comment]
@RobinQu @felixfbecker I agree that these kinds of dependencies shouldn't just be a mystery (required but undocumented). Not to mention that the FAQ describes things as if this situation doesn't exist:

> With Babel **every single** transformation can be turned off. Classes get supported in your target environment? Simply disable it and reap the benefits of all the other transformers.

My understanding is that the goal is to have less of these kinds of dependencies in v6.
