### ISSUE TITLE
logger not found in es6.promise.js of core-js

### ISSUE THREAD

**Issue by shreychaturvedi123** [babel/babel#2419]
At line 96 , I did a hack
 } catch(err){
        if(console){
        console.log(err);
          }
        react.rej(err);
      }
but if i use logger.log then it says logger is not defined and i am using winston logger globally and in catch also it is getting error that "logger is not defined".

**Comment by zloirock** [comment]
Sorry, I don't understand your issue. You you have changed `core-js` and it does not work as you expected? Why this question in `babel` repo, not in `core-js`?
