### ISSUE TITLE
class declaration hoisting problem

### ISSUE THREAD

**Issue by blai** [babel/babel#2420]
The following code causes runtime error `TypeError: Foo is not a function`.

```es6
let foo = new Foo();
export default foo;

class Foo {
  ...
}
```

If we do this in ES5

```js
var foo = new Foo();
module.export = foo;

function Foo() {
}
Foo.prototype.blah = ...
```

This would have worked.

Digging in and saw the generated ES5 code like so:
```js
var foo = new Foo();
exports['default'] = foo;

var Foo = (function () {
  function Foo () {
  }

  Foo.prototype.blah = ...
})();
```

I am wondering if letting class declaration fall into hoisting trap is by design.

**Comment by sebmck** [comment]
This is expected behaviour, classes aren't hoisted due to the `extends` clause allowing an arbitrary expression.

**Comment by loganfsmyth** [comment]
This type of thing is more obvious if you enable `es6.spec.blockScoping` for local development, as that would cause this code to throw a temporal dead zone error.

**Comment by blai** [comment]
Cool, thanks for the tip.
