### ISSUE TITLE
All exports should be initialized before processing imports

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2421]
If this is too nit-picky, we can close it, but figure'd I'd file and see. Came up in thinking about https://github.com/babel/babel/issues/2392.

A really simple circular dependency example

```
import * as self from './self';

console.log('foo' in self);

export var foo = 'thing';
```

This will log `false` because `foo` hasn't been exported yet, but my understanding is that it should be `true` since `self` will (in the spec anyway) essentially be an object of getter functions that are based on the table of exports, which is statically generated before execution.

Seems like we should explicitly set each export to `undefined` at the same place we're initializing the exports for hoistable declarations.

If I want to make a plugin for #2392, knowing at runtime exactly what all of the exports are, even if they aren't initialized yet, will be important. I can potentially inject this initialization in that plugin if needed, but the current behavior is different from the spec, so I figured I'd ask first.

**Comment by thejameskyle** [comment]
So you are suggesting that:

```js
import * as self from './self';
console.log('foo' in self);
export var foo = 'thing';
```

Should be changed to:

```diff
  Object.defineProperty(exports, '__esModule', {
    value: true
  });

+ exports.foo = undefined;

  var _self = require('./self');
  var self = _interopRequireWildcard(_self);

  console.log('foo' in self);
  var foo = 'thing';
  exports.foo = foo;
```

yes?

**Comment by loganfsmyth** [comment]
@thejameskyle Yeah exactly. It'd at least be a better approximation than the current one.

**Comment by hzoo** [comment]
Looks like this is done in v6 at least

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = undefined;

var _self = require('./self');

var self = _interopRequireWildcard(_self);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

console.log('foo' in self);
var foo = exports.foo = 'thing';
```

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-0&targets=&browsers=&builtIns=false&code=import%20*%20as%20self%20from%20'.%2Fself'%3B%0Aconsole.log('foo'%20in%20self)%3B%0Aexport%20var%20foo%20%3D%20'thing'%3B&experimental=true&loose=true&spec=true&playground=false&stage=0
