### ISSUE TITLE
Output optimization: spread operator in arrays, [...foo]

### ISSUE THREAD

**Issue by bfred-it** [babel/babel#2426]
```
let args = [...arguments];
```

becomes

```
var _slice = Array.prototype.slice;
args = [].concat(_slice.call(arguments));
```

but perhaps it could be optimized (i.e. avoid creating an empty array) as 

```
var _slice = Array.prototype.slice;
args = Array.prototype.concat(_slice.call(arguments));
```

or even better, when it only has one `...foo`

```
var _slice = Array.prototype.slice;
args = _slice.call(arguments);
```

**Comment by sebmck** [comment]
You shouldn't be spreading `arguments` anyway, it's going to cause an engine to deopt the entire function.

**Comment by bfred-it** [comment]
Ah… right. I forgot about this article saying so: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

I guess `function (...args) {}` is a better alternative in this specific case.

---

Suggestion still stands for other array and array-like objects

**Comment by hzoo** [comment]
Seems rare to do `[...arguments];` in user code

Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by bfred-it** [comment]
That was only an example. The suggestion still stands for other array and array-like objects: `[…arrayLikeObject]`
