### ISSUE TITLE
"export * from" should support live-binding with CommonJS

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2436]
Currently live-binding is supported for

    export {bar} from 'foo';

resulting in

```
var _foo = require('foo');
Object.defineProperty(exports, 'bar', {
  enumerable: true,
  get: function get() {
    return _foo.bar;
  }
});
```

however

    export * from 'foo';

is implemented as

```
var _foo = require('foo');

_defaults(exports, _interopExportWildcard(_foo, _defaults));
```

which copies over the properties at runtime, but does not account for live-binding.

**Comment by DrewML** [comment]
@erykpiast can you give an example of why you think it should be reopened? The code snippet above is what is necessary to support live bindings

**Comment by erykpiast** [comment]
@DrewML, I think the opposite! Sorry if my comment wasn't clear.
