### ISSUE TITLE
Named exports should take priority over indirect exports

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2437]
```
export var name = 4;
export {name} from 'mod';
```

should export `4`, because [ResolveExport](http://www.ecma-international.org/ecma-262/6.0/#sec-resolveexport) step 4 processes all `LocalExportEntries` before `IndirectExportEntries`.

At the moment it looks like exports are processed in declaration-order instead of in order of resolution priority.

**Comment by hzoo** [comment]
Now we just error because it was already declared

```js
repl: `name` has already been exported. Exported identifiers must be unique. (2:8)
  1 | export var name = 4;
> 2 | export {name} from 'mod';
    |         ^
```
