### ISSUE TITLE
Named exports should always take priority over star exports.

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2438]
Also related to the export priority in https://github.com/babel/babel/issues/2437, since this works if the `export var bar` comes after `export * from` and pre-assigning `undefined` https://github.com/babel/babel/issues/2421.

Given a named export `bar`, and another module `foo` that _also_ has an export named `bar`.

```
export var bar;
export * from 'foo';

function fn(){
  foo = 4;
}
```

Currently the `_defaults` helper assigns variables essentially checks if `exports[key] === undefined` for each exported name from `foo`, and overwrites it, but in an instance like this, the export hasn't been assigned yet, so the `export *` will assign `bar` as the value from `foo`, instead of properly preserving the value of `undefined`.

Once https://github.com/babel/babel/issues/2421 lands, seems like that check should be changed to use `hasOwnProperty`.

A secondary question on this:

`_defaults` also does `Object.getOwnPropertyDescriptor(defaults, key)`, shouldn't that be `Object.getOwnPropertyDescriptor(obj, key)`?

**Comment by sebmck** [comment]
Done in `development` branch with the commonjs module formatter rewrite.

**Comment by sebmck** [comment]
Wait, not sure.

**Comment by okonet** [comment]
I'm wondering what's the state of this issue?

**Comment by arcanis** [comment]
The PR is still waiting for review. In the meantime you can put the following code into a `npm-shrinkwrap.json` file, which is what we currently do on our application. Note that if you choose to do it, I strongly recommand that you fork my repository instead of using it directly, since I cannot guarantee that it will always stay up.

```js
{
  "dependencies": {
    "babel-plugin-transform-es2015-modules-commonjs": {
      "remove-when-fixed": "https://github.com/babel/babel/pull/3468",
      "resolved": "https://github.com/arcanis/babel-plugin-transform-es2015-modules-commonjs/archive/master.tar.gz"
    }
  }
}
```
