### ISSUE TITLE
Indirect and star exports should be hoisted

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2439]
```
console.log('two');
export * from './one';
export {foo} from './two';
console.log('three');
```

This currently prints `two` before loading `one` and `two`, but they should be hoisted to the top just like imports are.

**Comment by hzoo** [comment]
Looks like this is fixed?

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _one = require('./one');

Object.keys(_one).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _one[key];
    }
  });
});

var _two = require('./two');

Object.defineProperty(exports, 'foo', {
  enumerable: true,
  get: function get() {
    return _two.foo;
  }
});
console.log('two');

console.log('three');
```

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-0&targets=&browsers=&builtIns=false&code=console.log('two')%3B%0Aexport%20*%20from%20'.%2Fone'%3B%0Aexport%20%7Bfoo%7D%20from%20'.%2Ftwo'%3B%0Aconsole.log('three')%3B%0A&experimental=true&loose=true&spec=true&playground=false&stage=0

**Comment by loganfsmyth** [comment]
Looks like?
