### ISSUE TITLE
Custom plugins in browser

### ISSUE THREAD

**Issue by bjouhier** [babel/babel#2440]
Is it possible to register a custom plugin when babel is used in the browser. 

If this is not feasible via API, is it possible to build a custom browser.js which includes a custom plugin?

**Comment by sebmck** [comment]
> Is it possible to register a custom plugin when babel is used in the browser.

Yep. Just pass the plugin instance to `babel.transform` instead of a string.

Regardless, this issue is not appropriate for the issue tracker. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>

**Comment by bjouhier** [comment]
Thanks a lot. It solved my problem. And sorry for posting to the wrong place.
