### ISSUE TITLE
IE8 Expected identifier in browser.js

### ISSUE THREAD

**Issue by szarouski** [babel/babel#2442]
Hi, I don't think anyone reported this one yet. In current (5.8.25) babel-core/brower.js there are places like
```js
var isFunction = types.builtInTypes.function;
//...
builtin.null,
```
which fail to parse in IE8, as it thinks function and null are reserved words. Is there any way to fix this?

Thank you

**Comment by sebmck** [comment]
> it thinks function and null are reserved words

They are reserved words in ES3 IIRC which is basically what IE8 supports.

> Is there any way to fix this?

Nope. Even if it could parse, there's a whole bunch of other issues that make the compiler incompatible with IE8. Support for such an old browser isn't a thing we're willing to support, sorry.

**Comment by loganfsmyth** [comment]
@szarouski I'm curious, what's your usecase for needing the compiler in IE8? The generated code can be compatible, but the compiler itself isn't.

**Comment by szarouski** [comment]
@loganfsmyth, this is just a misunderstanding I guess. I started to use babel through [requirejs-babel](https://github.com/mikach/requirejs-babel) plugin and in dev mode in compiles on the fly. So once I was confident that my code is working like expected I checked in IE8 and found out that it will work only in production/compiled mode (which is totally fine, I just didn't know this).

Thanks
