### ISSUE TITLE
Compatibility with istanbul-middleware

### ISSUE THREAD

**Issue by epoberezkin** [babel/babel#2446]
If I insert `hookLoader` after `require('babel/register')` it doesn't work (logs errors).
If I insert `hookLoader` before `require('babel/register')` it seemingly works (no errors), although in some cases (but not in all - only 2 apps out of 7 in my case) no coverage is collected - the web page shows: `No coverage information has been collected`.
I will try to investigate what exactly is causing the issue.

Added issue in istanbul-middleware too: https://github.com/gotwarlost/istanbul-middleware/issues/21

**Comment by sebmck** [comment]
You're using two modules that are overloading `require`. It's impossible for them to interoperate due to these restrictions.
