### ISSUE TITLE
Decorators should have access to type annotations.

### ISSUE THREAD

**Issue by justinfagnani** [babel/babel#2447]
Could the property descriptors passed to decorators be extended to hold type information, like they are for initializers?

**Comment by sebmck** [comment]
I'm not willing to add this kind of interopability with a non-standard feature, sorry.

**Comment by justinfagnani** [comment]
Class properties, decorators and type annotations are all non-standard, yet there's interop between class properties and decorators. It seems like an omission that there's not interop between type annotations and decorators.

There's a whole class of decorators that need type information, and it's a shame to have to duplicate it, as in:

```javascript
class A {
  @serialize(Date)
  end : Date;
}
```

**Comment by sebmck** [comment]
Class properties and decorators are active proposals where interopability is essential for their progression in the specification. Type annotations are annotations and as to date, have no runtime precedence so making this addition is very dangerous and a slippery slope.
