### ISSUE TITLE
How to blacklist transforming let to var?

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#2448]
I assumed this would be the same transformer that compiles `const` to `var`, but apparently not.

**Comment by sebmck** [comment]
`es6.blockScoping`. This is not the current place to ask questions. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
