### ISSUE TITLE
override setter erases getter and vise versa

### ISSUE THREAD

**Issue by lukescott** [babel/babel#2449]
If you define a getter/setter in a class and then override the setter in a subclass without overriding the getter, the getter from the parent class gets erased. This is also an issue with Traceur.

Example:
```javascript
class Foo {
  get foo() {
    return this._foo || "";
  }
  
  set foo(foo) {
    this._foo = foo;
  }
}

class Bar extends Foo {
  set foo(foo) {
    super.foo = foo;
  }
}

let bar = new Bar();

console.log(typeof bar.foo); // undefined, should be string
```

Generates the following code:
```javascript
var _set = function set(object, property, value, receiver) { var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent !== null) { set(parent, property, value, receiver); } } else if ("value" in desc && desc.writable) { desc.value = value; } else { var setter = desc.set; if (setter !== undefined) { setter.call(receiver, value); } } return value; };

var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; desc = parent = getter = undefined; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; continue _function; } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: "foo",
    get: function get() {
      return this._foo || "";
    },
    set: function set(foo) {
      this._foo = foo;
    }
  }]);

  return Foo;
})();

var Bar = (function (_Foo) {
  _inherits(Bar, _Foo);

  function Bar() {
    _classCallCheck(this, Bar);

    _get(Object.getPrototypeOf(Bar.prototype), "constructor", this).apply(this, arguments);
  }

  _createClass(Bar, [{
    key: "foo",
    set: function set(foo) {
      _set(Object.getPrototypeOf(Bar.prototype), "foo", foo, this);
    }
    // <---- getter is erased here
  }]);

  return Bar;
})(Foo);

var bar = new Bar();

console.log(typeof bar.foo); // undefined, should be string
```

If this was intended as part of the spec that would be unfortunate as it is quite jarring.

**Comment by sebmck** [comment]
Did you verify that this is not intended behaviour?

**Comment by lukescott** [comment]
@sebmck I was hoping that you would know the answer to that :). I'm digging through the spec...

**Comment by loganfsmyth** [comment]
This seems like the expected behavior to me, since you're adding a new descriptor to `Bar.prototype`. I agree it's a little counterintuitive though. Otherwise [14.3.9](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation) would have to get the descriptor from the parent object first, then merge that with the new descriptor being created.

**Comment by sebmck** [comment]
This is indeed expected behaviour. I've verified this with the latest version of V8 and checked the spec. The internal method that's used to define getters and settings as specified in [14.3.9](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-method-definitions-runtime-semantics-propertydefinitionevaluation) delegates to [7.3.7 DefinePropertyOrThrow](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-definepropertyorthrow) which calls `O.[[DefineOwnProperty]]`. That essential internal method is defined as:

> Create or alter the own property, whose key is propertyKey, to have the state described by PropertyDescriptor. Return true if that property was successfully created/updated or false if the property could not be created or updated.

in [6.1.7.2. Table 5](http://www.ecma-international.org/ecma-262/6.0/#sec-object-internal-methods-and-internal-slots). Which clearly describes it as only inheriting from existing own properties.

**Comment by lukescott** [comment]
@loganfsmyth @sebmck  That is a very jarring expectation then. The getter and setter are expressed separately in the class AND you can call super, such as:

```javascript
class Bar extends Foo {
  set foo(foo) {
    super.foo = foo; // this shows that the setter is "inherited"
  }
}
```

I can understand if you just overrode the getter with the intent of making the property read-only. So it makes sense in that context that it shouldn't inherit the setter in that case. But in the case I provided there is no way to inherit the getter, and it looks like it should work, especially since the setter can use super.

Does this seem like an issue that is worth discussing on the mailing list?

**Comment by loganfsmyth** [comment]
Class syntax is still prototypal inheritance. A setter and getter function are conceptually a single property. It's just as weird that

    class Bar extends Foo {
        foo(){}
    }

would override _both_ the setter, and the getter.

I'm confused though, why is there no way to inherit the getter? You can add

     get foo(){ return super.foo; }

**Comment by lukescott** [comment]
> Class syntax is still prototypal inheritance. A setter and getter function are conceptually a single property. It's just as weird that would override both the setter, and the getter.

I see your point. Wouldn't this be considered ambiguous?
```javascript
class Foo {
  get foo() {
    return this._foo;
  }
  set foo(foo) {
    this._foo = foo;
  }
  foo() {}
}
```

Babel translates the above to this regardless of where `foo() {}` sits:
```javascript
var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: "foo",
    value: function foo() {}
  }, {
    key: "foo",
    get: function get() {
      return this._foo;
    },
    set: function set(foo) {
      this._foo = foo;
    }
  }]);

  return Foo;
})();
```

> I'm confused though, why is there no way to inherit the getter? You can add

I could do that. But I would then have to override the getter every time I override the setter. In my case I'm overriding the setter to fire off a change event. So overriding the getter is just boilerplate. It works until I forget to do it. And I have an unnecessary chain of getters.

Thankfully in my case I'm using a decorator in these cases anyway, so I can just restore the getter in the decorator. I just thought it was odd that my getter disappeared. Took a bit to debug to find out what was happening.

**Comment by loganfsmyth** [comment]
ES6 dropped the runtime duplicate property error that ES5 had, so properties are supposed to just be processed in order. Babel doesn't handle that perfectly for getters/setters. This specific example is solidly a bug though, `foo() {}` should overwrite the getter/setter pair.
