### ISSUE TITLE
Scoping issue with const/let and switch statement

### ISSUE THREAD

**Issue by travisperson** [babel/babel#2451]
Similar to #564, if you place brackets around the body of the case there is an undefined `_loop`. Removing the brackets fix the issue. This appears to be due to scoping.

```javascript
function reduce (state = {}, action) {
    switch(action.type) {
        case 'CLEAR_DISMISSED': {
            let newState = {
                ...state
            };

            Object.keys(newState).forEach(error => {
                let e = newState[error];
                if (e.dismissed) {
                    delete newState[e.id];
                }
            });

            return newState;
            break;
        }
        default: {
            return state;
        }
    }
}
```
Gives `Undefined label '_loop'`

[Repl Example](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=function%20reduce%20(state%20%3D%20%7B%7D%2C%20action)%20%7B%0A%20%20%20%20switch(action.type)%20%7B%0A%20%20%20%20%20%20%20%20case%20'CLEAR_DISMISSED'%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20newState%20%3D%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...state%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20Object.keys(newState).forEach(error%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20e%20%3D%20newState%5Berror%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(e.dismissed)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20delete%20newState%5Be.id%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20newState%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20default%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20state%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A)

------

Also, if there is a better way to perform this action in es6 I'd love to hear it. This is just what I came up with and ran into this issue.

Basically I want to remove all objects from state that have the `dismissed` flag set.

```json
{
  "1": {
    "id": 1,
    "message": "hello",
    "dismissed": true
  },
  "2": {
    "id": 2,
    "message": "world",
    "dismissed": false
  }
};
```
Should become
```json
{
  "2": {
    "id": 2,
    "message": "world",
    "dismissed": false
  }
};
```

**Comment by fanatid** [comment]
Yet one code that give `SyntaxError: Undefined label '_loop'`
```js
async function f () {
  while (true) {
    try {
      if (1) {
        continue
      }

      if (1) {
        break
      }

      let x = functionA()
      await functionB(async () => { await functionC(x) })
    } catch (err) {}
  }
}
```

**Comment by danez** [comment]
Cannot reproduce anymore, so this is probably fixed in one of the 6.x releases.
