### ISSUE TITLE
 Some imports fail with require hook

### ISSUE THREAD

**Issue by vkurchatkin** [babel/babel#2455]
I'm using require hook with node 4.1.1 and the following `.babelrc`: 

```json
{
  "stage": 1,
  "blacklist": [
    "regenerator",
    "es6.forOf",
    "es6.constants"
  ],
  "optional": [
    "asyncToGenerator"
  ]
}
```

At some point I started getting `ReferenceError: SomeImportedThing is not defined`. Strangely, I only get this during the first launch and only for some specific type of imports (classes with just a constructor). Everything looks good on the importing side and stack trace actually points at the imported file.

If I launch the same thing again right after that, everything works fine. If I `BABEL_DISABLE_CACHE=1` then it fails every time.

**Comment by sebmck** [comment]
There's not enough information here to reproduce. Please create an example with steps to reproduce.

**Comment by loganfsmyth** [comment]
Sounds like that potential V8 memory corruption issue ruby-random was investigating.

**Comment by vkurchatkin** [comment]
Here is the test case: https://github.com/vkurchatkin/babel-weird-bug
It's really weird

**Comment by loganfsmyth** [comment]
That's totally the same bug, since it involved unicode characters.

**Comment by vkurchatkin** [comment]
@loganfsmyth is there some link to this issue?

**Comment by sebmck** [comment]
Looks like an engine bug. There's nothing that we can really do. I've had multiple reports previously of this so I'd recommend reporting it to the V8 team.

```javascript
var Cls = function Cls() {
  _classCallCheck(this, Cls);
};
```

It's throwing a reference error to `Cls` which is literally impossible since it's locally scoped since it's a named function expression.

**Comment by vkurchatkin** [comment]
@sebmck just wondering, why precompiled version works fine

**Comment by sebmck** [comment]
@vkurchatkin There's no logical explanation which is why it's almost definently an engine bug.

**Comment by vkurchatkin** [comment]
Ok, closing, `v8` is definitely to blame. Here is minimal code to reproduce the issue:

```js
({})['XYй'.slice(0, 2)] = null;
require('vm').runInThisContext('var x=function XY(){XY};x()');
```

Conclusion: sliced strings in v8 are broken, and if you use them as keys, then something will break.
/cc @ruby-random

**Comment by loganfsmyth** [comment]
@vkurchatkin Nice job narrowing that down. Did you end up filling a V8 bug? I'd love to follow it.

**Comment by vkurchatkin** [comment]
Not yet, need to build recent v8 first. FWIW the issue reproduces with eval in node and doesn't reproduce in newish version of Chrome, so there is a chance it is fixed already.

**Comment by impinball** [comment]
It's broken in the latest release build of V8. Tried this with a compiled release version of v8/v8@759591d.

Source:

```js
({})['XYй'.slice(0, 2)] = null;
Function('var x=function XY(){XY};x()')()
```

Output:

```
undefined:2: ReferenceError: XY is not defined
var x=function XY(){XY};x()
                    ^
ReferenceError: XY is not defined
    at XY (eval at <anonymous> (test.js:2:1), <anonymous>:2:21)
    at eval (eval at <anonymous> (test.js:2:1), <anonymous>:2:25)
    at test.js:2:40
```

Same thing happened using `eval`. It doesn't repro when evaluated literally. [Here's the V8 bug for you all.](https://code.google.com/p/v8/issues/detail?id=4450)
