### ISSUE TITLE
bad arrow function transpile halts program

### ISSUE THREAD

**Issue by naomik** [babel/babel#2456]
Works in Chrome 45

```js
(() => this x).call({x:1});
//=> undefined
```

Yes, it's stupid to write/use an arrow function like this, but at least the output is expected.

However, Babel transpiles to

```js
"use strict";

(function () {
  return undefined.x;
}).call({ x: 1 });
```

Which evaluates with an error

```plain
Cannot read property 'x' of undefined
```

No good :cry:

**Comment by sebmck** [comment]
This is expected behaviour. Please see the [FAQ](https://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-) as well as previous issues #2337, #2141, #1988, #1700, #1667, #1573, #562, #814, #730 and #733.

**Comment by naomik** [comment]
@sebmck thanks. I searched the issues but wasn't able to find a relevant one.

:x: :o:

**Comment by jridgewell** [comment]
The issue is you're using a _module's_ scope for `this`. Babel will transform those into `undefined` (because it is `undefined`). If you instead wrap it in a function, you'll see expected results:

```js
function test() {
  (() => this.x).call({x:1});
}

// - - -
function test() {
  var _this = this;

  (function () {
    return _this.x;
  }).call({ x: 1 });
}
```

**Comment by naomik** [comment]
@jridgewell 

But that's just not true

```sh
$ echo "console.log(this);" > module.js
$ echo "require('./module');" | node
```

Output

```js
{}
```

Thus, we could expect `this.x` to be `undefined` just as `({}).x` is `undefined`

---

Cleanup

```sh
rm -iv module.js
```

**Comment by jmm** [comment]
@naomik you're illustrating CommonJS module behavior. Babel treats input as ES2015 modules by default, including implied strict mode. Did you take a look at the FAQ?
