### ISSUE TITLE
Update to latest class property proposal

### ISSUE THREAD

**Issue by sebmck** [babel/babel#2460]

**Comment by flying-sheep** [comment]
why does it depend on classes?

can’t we implement in a way that relies on native classes and just moves the class properties out of the class declaration if only `es7.classProperties` is enables?

**Comment by sebmck** [comment]
This issue isn't related at all to what you're saying.

**Comment by sebmck** [comment]
Semantics haven't changed. I rewrote the class property transformer to desugar to ES2015 though.

**Comment by flying-sheep** [comment]
> I rewrote the class property transformer to desugar to ES2015 though

that’s exactly what i wanted to say: if a platform can do ES2015 classes, babel should be (and now presumably is) able to desugar class properties into ES2015 classes and some assignments.

what was wrong?
