### ISSUE TITLE
ES6 classes late static binding using native language constructs

### ISSUE THREAD

**Issue by constb** [babel/babel#2461]
Is there a way to implement late static binding with ES6 classes using native language constructs?

Exhibit A. Shows ``abc``:
```
class Foo {
  static testStatic = "abc";
  getTestStatic() {
    return Foo.testStatic;
  }
}
alert((new Foo).getTestStatic());
```

Exhibit B. Shows ``abc`` whereas I want ``def``:
```
class Foo {
  static testStatic = "abc";
  getTestStatic() {
    return Foo.testStatic;
  }
}
class Bar extends Foo {
  static testStatic = "def";
}
alert((new Bar).getTestStatic());
```

Exhibit C. Shows ``undefined`` whereas I want ``def``:
```
class Foo {
  static testStatic = "abc";
  getTestStatic() {
    return this.testStatic;
  }
}
class Bar extends Foo {
  static testStatic = "def";
}
alert((new Bar).getTestStatic());
```

Exhibit D. Shows ``def`` but smells like a hack:
```
class Foo {
  static testStatic = "abc";
  getTestStatic() {
    return this.constructor.testStatic;
  }
}
class Bar extends Foo {
  static testStatic = "def";
}
alert((new Bar).getTestStatic());
```

Is there a better way to express this in ES6?
Is there native construct to access current class static properties without writing class name explicitly?
Is there native construct to access callee's class static properties similar to ``this`` but for statics?
Is this okay that ``this`` only accesses concrete object's properties but doesn't provide access to statics directly or through prototype chain?

**Comment by loganfsmyth** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Option D sounds reasonable to me. My question would be, why is it a static at all, if you need to know it per-instance?

**Comment by constb** [comment]
@loganfsmyth thanks, I'll stick with using ``this.constructor`` from now on. The idea behind this is all about using statics inside instance methods. It's somewhat influenced by Open-Closed Principle. I want to be able to configure behaviour of an abstract implementation in parent by overriding properties in children.
