### ISSUE TITLE
Duplicate keys in object literals transpile to ES5-incompatible JS

### ISSUE THREAD

**Issue by jussi-kalliokoski** [babel/babel#2462]
The following ES6 code:

```javascript
var x = {x: 1, x: 2};
```

generates the following code:

```javascript
"use strict";

var x = { x: 1, x: 2 };
```

which will result in an error for ES5-compliant engines. I'm not sure what should be done here instead as duplicate keys are back to being valid in strict mode in ES6, but maybe something like this:

```javascript
"use strict";

var x = { x: 1 };
x.x = 2;
```

This bug also occurs with JSX:

```javascript
var x = <x x={1} x={2} />;
```
becomes

```javascript
"use strict";

var x = React.createElement("x", { x: 1, x: 2 });
```

**Comment by sebmck** [comment]
This will have to be done with another transform. Seems easy enough.

**Comment by jussi-kalliokoski** [comment]
Yeah, something like this seems to produce working code (horribly inefficiently though) if placed after the JSX transforms and before other `ObjectExpression` related transforms:

```javascript
export default function ({Plugin, types: t}) {
  function getName (key) {
    if ( t.isIdentifier(key) ) { return key.name; }
    return key.value.toString();
  }
  
  return new Plugin('duplicate-property-keys-to-es5', {
    visitor: {
      ObjectExpression (node) {
        const plainProps = node
          .properties
          .filter(prop => !t.isSpreadProperty(prop))
          .filter(prop => !prop.computed);
        
        plainProps
          .filter((prop, index) =>
            plainProps
              .slice(0, index)
              .some(previousProp =>
                getName(prop.key) === getName(previousProp.key)
              )
          )
          .forEach(prop => {
            prop.computed = true;
            prop.key = t.literal(getName(prop.key));
          });
      }
    }
  });
}
```

**Comment by petetnt** [comment]
Maybe this should be an `option` with a sensible default (IMHO default being `error`, because one could argue that 99% of the times duplicate key is an (user) error)? Others being something like `warn` (current behavior + warning) and `overwrite`? Duplicated property values are allowed in ES6, though I think the restriction was removed because of duplicating being possible do to computed property values on runtime being possible, right? MDN says that:

> In ECMAScript 5 strict mode code, duplicate property names were considered a SyntaxError.  With the introduction of computed property names making duplication possible at runtime, ECMAScript 6 has removed this restriction.

**Comment by jussi-kalliokoski** [comment]
I think that sounds more like the job of a linter - there's plenty of other silly things you can do with the language that babel doesn't warn nor throw for. IMO what babel should do here is just produce valid JS.

**Comment by petetnt** [comment]
Yeah, I was thinking about that. I have always set my linters to throw on duplicated keys (and other duped ones like variable names) and I do agree that `babel` should produce is valid JS and that there are tons of silly things that are better left for the linter or coder to handle. 

But then again the *expected* outcome is hard to say in a transpiling cases like with `babel`: duplicate keys is most likely something that is not expected (especially with non-runtime, precomputed values). Consider something like

```
var x = {x: 1, x: 2};
```

Realistically, how often would the desired outcome be 

```
var x = {x:1}; 
x.x = 2; 
```
? 

But more I think about it; if you have linters properly set up this won't be an issue anyway like you said :hamburger:.

**Comment by AgentME** [comment]
Perhaps this could be simple to implement if duplicate keys were treated the same way as computed keys. `var x = {o: 5, o: 6};` could be treated like `var x = {o: 5, ["o"]: 6};` and transpiled to the same thing using the same logic.
