### ISSUE TITLE
Memoise virtual type checkers

### ISSUE THREAD

**Issue by kittens** [babel/babel#2463]
Multiple visitor methods will cause these to be executed multiple times.

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
