### ISSUE TITLE
Set() not polyfilled in ie8

### ISSUE THREAD

**Issue by zyllorion** [babel/babel#2467]
Hi,

Is there a reason why
```var aSet = new Set(a)```
Doesn't give ie8 compatible code?

Build environment is:
```
"ember-cli": "1.13.8"
"ember-cli-babel": "^5.1.3"
```
Thanks

**Comment by sebmck** [comment]
You need to use the polyfill. Please see the [docs](http://babeljs.io/docs/usage/polyfill). Also please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. >The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>
