### ISSUE TITLE
Spread property in object literal working: it shouldn't!

### ISSUE THREAD

**Issue by callumacrae** [babel/babel#2468]
```js
[].map((letter, index) => ({ ...letter, index }))
```

This works in babel, even when experimental mode is turned off. How come? It's not in ES6 and [the proposal](https://github.com/sebmarkbage/ecmascript-rest-spread) hasn't been accepted yet.

This compiled fine, so ended up in our codebase, but failed eslint because it doesn't exist yet.

**Comment by sebmck** [comment]
It's stage 2. Babel enables all transforms that are stage 2 or later.

**Comment by callumacrae** [comment]
Ah, I see. Thank you!
