### ISSUE TITLE
toString.call(new Set()) returns [object Object]

### ISSUE THREAD

**Issue by dvlsg** [babel/babel#2470]
This may be intended behavior, but I noticed some inconsistencies when using `Object.prototype.toString.call` with babel-core/register vs babel-runtime/core-js/set.

Here are some quick examples:

```js
var _Set = require('babel-runtime/core-js/set')['default']; // to match babel's transpiled output
var set = new _Set();
console.log(Object.prototype.toString.call(set)); // => "[object Object]"
```

When I add `require(babel-core/register)` at the top of the script, the log will output "[object Set]" instead. Is there a polyfill for `Object.prototype.toString` that gets written when requiring `babel-core/register`? I saw that node has toStringTag behind a harmony flag still, but I still receive the "[object Object]" output when flipping it to on when using the core-js sets. Using the native node Set outputs "[object Set]" as expected with the harmony flag both on and off.

Here are my specs:
Node: v4.1.0
babel-core: 5.8.25
babel-runtime: 5.8.25

Is this working as intended? If so, is there a way to blacklist transforms on built-in items such as Sets with Node ^4.0.0?

Side note, this also occurs for corejs maps, weakmaps, weaksets, and promises.

**Comment by loganfsmyth** [comment]
This expected behavior, because `runtime` does not polyfill anything global, which `Object.prototype.toString` is. `babel/register` loads a polyfill globally.

If you want global behavior, you'd need to stop using `runtime`, and use the global polyfill instead.
