### ISSUE TITLE
Ignore specified es6 features

### ISSUE THREAD

**Issue by ppoliani** [babel/babel#2472]
I wonder if it's worth it to pass a list of es6 features to babel which it should ignore when transpiling the source code. 

For example, I the current version of nodeJS supports generator functions I would like to let the native implementation to deal with it. In same manner I would like babel to transpile any class definitions or the rest operator or anything else that is not currently natively supported.

**Comment by sebmck** [comment]
You can already do this with the [blacklist](http://babeljs.io/docs/usage/options) option. See [transformers](https://babeljs.io/docs/advanced/transformers/) for a list of transformers.

**Comment by ppoliani** [comment]
That's perfect!

I must have missed that one.

Thank you
