### ISSUE TITLE
Whitelist es6.constants transforms `const` to `let` instead of `var`

### ISSUE THREAD

**Issue by mnpenner** [babel/babel#2473]
Running the command

    babel --whitelist es6.constants

Will convert `const` variable declarations into `let` statements instead of `var`.

Use case: I want to run my code through Babel, blacklisting es6.constants, then run it through UglifyJS which understands and will remove consts, and then run it through Babel one more time to clean up any consts and Uglify left behind.

I thought the `es6.constants` transformer converted consts to vars, but perhaps it converts it to lets and another transformer converts lets to vars? If so, which transformer should I be looking at?

Also, it would be helpful if Babel didn't introduce whitespace around operators when `--compact` is enabled.

**Comment by loganfsmyth** [comment]
`const` variables are block-scoped just like `let`, converting them directly to `var` would break that. You'd have to enable `es6.blockScoping` too to get all `var`s.

Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by mnpenner** [comment]
Sorry. I tried looking at the [transformers list](https://babeljs.io/docs/advanced/transformers/) but I couldn't figure out which transformer did the `let`/`const` → `var` conversion.

Should I open a new ticket to request that `--compact` doesn't introduce whitespace?

**Comment by sebmck** [comment]
> Sorry. I tried looking at the [transformers list](https://babeljs.io/docs/advanced/transformers/) but I couldn't figure out which transformer did the `let`/`const` → `var` conversion.

`es6.constants` transforms to `let` which is then transformed by the `es6.blockScoping` transform.

> Should I open a new ticket to request that `--compact` doesn't introduce whitespace?

It doesn't introduce whitespace.

**Comment by mnpenner** [comment]
> It doesn't introduce whitespace.

Where do spaces around the `+` operator come from then?

    $ echo "let x=1+2;" | babel --compact
    "use strict";var x=1 + 2;

**Comment by sebmck** [comment]
I haven't managed to get the heuristics right as you can't blindly ignore the space since

```javascript
++a + +b
```

Is still valid code.

**Comment by mnpenner** [comment]
Fair enough. I can see how that makes things complicated.

It's a shame though, because it de-minifies my code a bit. Is it something you're still working on, or should I just forget it? I don't want to trouble you over a few bytes.

**Comment by sebmck** [comment]
Yeah I plan on tackling a minifier after Babel 6 so it's definently something I want to get to :smile:

**Comment by mnpenner** [comment]
Okay, awesome! Thanks for your help. 

Babel is a fantastic tool BTW :)
