### ISSUE TITLE
Error using type cast expression with yield expression 

### ISSUE THREAD

**Issue by gabelevi** [babel/babel#2477]
The repro looks like

```JavaScript
function *test() {
  ((yield 4): number);
}
```

When I try the repl, I get `repl: unknown Expression of type "TypeCastExpression"`

On a related note I believe

```JavaScript
(yield 4: number);
```

should parse, but it doesn't.

**Comment by sebmck** [comment]
Looks like it's `regenerator` being picky.

**Comment by splodingsocks** [comment]
@sebmck I'd love to be able to help out with this, as it's making it very difficult for me to upgrade one of our projects to flow 0.16.

Any suggestions as to where I should start poking around with regenerator to see if I can help to get this resolved?

**Comment by splodingsocks** [comment]
I've just been writing codemods that use some of the same libraries that regenerator uses, it looks like. I'll dig around a bit in there to see if I can get something figured out.

**Comment by splodingsocks** [comment]
Looks like I maybe all I have to do is add another case here:

https://github.com/facebook/regenerator/blob/master/lib/emit.js#L984

**Comment by splodingsocks** [comment]
This should resolve it, I think:

https://github.com/facebook/regenerator/pull/221

**Comment by sebmck** [comment]
It won't. You're going to need to add support for it to ast-types too. Why aren't you stripping the flow annotations? They shouldn't be in the AST by the time regenerator transforms.

**Comment by splodingsocks** [comment]
ast-types already supports it. It ast-types parses the code correctly:

http://felix-kling.de/esprima_ast_explorer/#/6HUSxFWjdP/1

It appears that regenerator just didn't know what to do with that node type.

About the flow types being stripped, I don't know why they aren't stripped by this point. Should babel do that before passing the code along to regenerator?

**Comment by splodingsocks** [comment]
I've just taken a cursory glance, but it looks like there's already code in babel to recognize and strip typecast expressions:

https://github.com/babel/babel/blob/855ee71d5955d5ada39751e5469983da248ff550/packages/babel/src/transformation/transformers/other/flow.js

I'll look into it a bit more soon.

**Comment by splodingsocks** [comment]
I put a log statement inside of the function I liked above. The log statement is reached with I have the yield commented out (for line 3):

```javascript
function *test() {
  var a: string;
  a = ('a': string);
  // ((yield 4): number);
}
```

But when I uncomment line 4, the log statement never gets reached. This suggests to me that regenerator is running before the flow annotations get stripped. I'm looking around the code to see if I can find where the order of those operations is defined, but it's not immediately obvious to me. Can anyone point me in the right direction?

**Comment by sebmck** [comment]
Fixed in my regenerator fork which will hopefully be merged for Babel 6.
