### ISSUE TITLE
Disable 'use strict'

### ISSUE THREAD

**Issue by kobezzza** [babel/babel#248]
How i can disable 'use strict' mode by default? Can't find there https://6to5.github.io/usage.html#options :cry:

**Comment by tjcrowder** [comment]
@yuchi -

> And ES6 is AFAIK ‘strict by default/spec’ so it’s wrong to even want to disable it.

No, that's [incorrect](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-strict-mode-code). It's only modules that default to strict. Global code is loose unless it starts with a `"use strict"` prologue.
