### ISSUE TITLE
plugins: declarative before/after transform composition

### ISSUE THREAD

**Issue by benmosher** [babel/babel#2480]
This may be a bit half-baked, but as I'm writing my first plugin, I have a thought:

What if plugins could declare "dependencies"?

I think this might be the wrong way to name it, but it would be essentially a finer-grained way to determine plugin ordering.

Instead of (or in addition to) the coarse `:before`/`:after` ordering, I am imagining doing something declarative in my plugin spec like:

```es6
return new Plugin('foo-bar', { 
  visitor, 
  dependencies: {
    before: ['properties.shorthand', 'es3.*'], // run these transforms later, if ever
    after: ['strict']  // run this transform first, if ever
  }
})
```

For my plugin, I need to ensure the `'use strict'` is already part of the AST before it gets to mine, but it would also be simpler for my plugin to emit shorthand properties. 

Also, in this case, if either of these transformers is omitted, the order is irrelevant. This also means an application author can use explicit shorthand properties in the transpiled output if/when the environment permits, instead of requiring me as the plugin author to emit lowest-common-denominator `Object.defineProperties(...)` statements. With the current `before`/`after`, that is the only safe option, AFAICT.

Also, it would naturally be an error if there is no valid topo-sort of all requesting plugins/transforms (i.e. loops).

Does this make sense? or am I over-thinking it? I can imagine it being useful for ordering the internal transforms as well, and they could leverage the same sort of cascading transformations where any given transform can emit ES6 as long as it properly declares its `before` transforms.

**Comment by benmosher** [comment]
Having just read through #2168, it looks like this might be solved via presets?

**Comment by sebmck** [comment]
Plugins shouldn't have dependencies on requiring other transforms. If your transform has dependencies then it should be merged with those transforms.

**Comment by sebmck** [comment]
FYI `before` and `after` is going. All plugins are going to be executed at the same time in the same traversal. You shouldn't be relying on execution order.

**Comment by benmosher** [comment]
Here's the issue: I want to use `with` to expose imported names so that the proper semantics are preserved, but the names are accessible in the debugger. 

Therefore, I want to run _after_ `strict` to ensure the module is not put into strict mode outside my `with` statement. 

I can work around this by blacklisting `strict` and adding a plugin option to do this, but this feels like a step backwards. 

I also want to use object literal getters for the object passed to the `with` statement to allow reading without writing to the module names. It would be simpler and cleaner for me to actually emit `get` syntax and then let the appropriate transform turn that into Object.defineProperties--or not, if the target environment supports getters. 

That's the motivation for the request. Again, I think I was wrong to use "dependencies" as it evokes the wrong cognitive frame; I think it's more analogous to function composition. (Or in this case, transform composition)

**Comment by benmosher** [comment]
Simplified example, ignoring the getters for now:

content:
```js
import { foo } from 'mod'
export function bar(x) { return foo(x + 42); }
```

If modeled as `withModule(strict(ast))`:
```js
with({ get foo() { return require('mod').foo } }) {
  // withModules transform essentially wraps the program body in `with` with an IIFE, 
  // to (optionally) enforce strict mode for actual module contents
  (function(){
    'use strict';
    exports.bar = function bar(x) { return foo(x + 42); };
  })();
}
```

vs. `strict(withModules(ast))`:
```js
'use strict';
// this is invalid ES5, now
with({ get foo() { return require('mod').foo } }) {
  (function(){
    exports.bar = function bar(x) { return foo(x + 42); };
  })();
}
```

It's not clear to me which output should be expected from both transforms executing on the same traversal pass.

**Comment by sebmck** [comment]
You're producing an invalid construct for strict mode. I'm not sure how you expect that to behave even without everything happening in one traversal pass. If your transform automagically changes depending on strict mode then it shouldn't.

**Comment by benmosher** [comment]
To be clear: I would hope to emit the first block (`withModules(strict(ast))`), where `'use strict'` is inside the IIFE (and is thus valid ES5). This should result in strict mode being enabled for the full contents of the IIFE, while also allowing the `with` to happily function at the root of the module.

Again, all of this is in service of the goal that imported names (`import { foo } ...`) would be available as-imported at runtime, while also always properly requesting the current exported value from the module (and not the value the module had when the `import` was evaluated). As I've worked on it, it is becoming clear that hoisting all the imports into a single `with` is not going to work in general, so this specific point is becoming moot for this use case.

It's also not obvious to me how transforms could modify the AST during a single traversal with any mutations without potentially stomping all over each other, but you've certainly spent more time thinking about it than I have. 😅

That said, I think there is something simple and elegant about the notion of composing transforms (plugins) as a function from AST => AST, and allowing them to emit ES6 syntax that will be further transformed, only _if necessary_ or explicitly requested.

Using the getters in the `with(...)` as an example, I would rather emit the ES6 I intend (getters) instead of handrolling the lowest-common-denominator ES3 or ES5 (i.e. `Object.defineProperties`) that will ensure it works everywhere. (and isn't that one of the key problems that Babel solves, after all?)

Anyway, this issue was intended to air and discuss a few thoughts. I appreciate your quick responses and I don't think there are any action items, so I will close this issue. Thanks!
