### ISSUE TITLE
TDZ within destructured declaration

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#2482]
```js
let [ a ] = [ a ];
```

Babel should warn that `a is not defined - temporal dead zone` but it doesn't.

Test: http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&code=let%20%5B%20a%20%5D%20%3D%20%5B%20a%20%5D%3B&playground=true

**Comment by sebmck** [comment]
See #563 and linked threads.

**Comment by loganfsmyth** [comment]
@sebmck This issue is that even with the spec transformer enabled, isn't properly initializing one of the variables to `_temporalUndefined` so it doesn't throw when it should.

**Comment by sebmck** [comment]
Oh, my bad. This is fixed in the `development` branch anyway.
