### ISSUE TITLE
"sourceMaps" option in babelrc has no effect

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#2484]
Create an empty directory and do this:

	echo '{"sourceMaps": true}' > .babelrc
	mkdir src
	echo 'export default 1' > src/index.js
	babel src --out-dir lib

`lib/index.js` will be created but not `lib/index.js.map`.

Adding `--source-maps` to the command fixes the problem, but I want to do that through babelrc.

**Comment by sebmck** [comment]
I've thought about this and it doesn't make any sense. The behaviour of the CLI flags and API options are fundamentally different. Making an API option produce source maps on disk is very different to just populating a property. I'm going to close this as a wontfix.

**Comment by andy-hanson** [comment]
Maybe remove the option then? If I use `{"badOptionName": true}` it will tell me that's an unknown option.

**Comment by sebmck** [comment]
Except it's a perfectly valid API option.

**Comment by laggingreflex** [comment]
It works if you set it to "inline"

**Comment by olalonde** [comment]
Yeah, that's confusing, it works for "inline" but not for `true` :/
