### ISSUE TITLE
ReferenceError on import object undefined

### ISSUE THREAD

**Issue by yujinlim** [babel/babel#2487]
Hi, 

I'm using es6 imports via require hook but sometimes when i restart my app, i always have an error of undefined object, example as below
```
require('babel/register')
```

I have a file, file A.js
```
'use strict';

export let authenticate = function *(next) {
 //...
}
```
file B.js
```
'use strict';

import * as a as './A'

function *() {
  yield a.authenticate // is undefined
}
```

error
```
ReferenceError: authenticate is not defined
```
This does not happen all the time, it only happened sometimes when babel rebuild its cache. 

I'm using iojs 3.1. Please advice. Thanks

**Comment by sebmck** [comment]
There's not enough information here to diagnose your issue. Please provide a reproducible example or this will be closed.

**Comment by thomasfoster96** [comment]
Is the following in `B.js` a typo?
```js
import * as a as './A'
```

**Comment by loganfsmyth** [comment]
Do you happen to have any non-ASCII characters in that file? Any fancy unicode at all?

**Comment by yujinlim** [comment]
I found out the problem, apparently, It was es6 destructuring syntax on import statement on iojs3.1. Weird part is it happened once in awhile, when there is big rebuild of cache.

```
import { authenticate, logout } from '../handler/auth';
```
