### ISSUE TITLE
Resolve plugin paths relative to .babelrc

### ISSUE THREAD

**Issue by jmm** [babel/babel#2491]
This is somewhere between a feature request and bug fix. Per discussion on Slack, this is planned (perhaps even implemented) for v6. I'm creating this issue to track it.

Currently plugin paths from all `.babelrc`'s are resolved relative to CWD, which causes problems in certain scenarios. For example:

Package `dep` should be self contained, including any plugins it depends on when transformed by Babel. So it has a `.babelrc` like:

```json
{
  "plugins": ["./whatever.js"]
}
```

And a `package.json` like:

```js
{
  "browserify": {
    "transform": [
      "babelify"
    ]
  }
}
```

Package `app` is bundled with Browserify and depends on `dep`. Babel tries to resolve `./whatever.js` relative to the CWD where `app` runs Browserify, interfering with making `dep` self-contained.

**Comment by sebmck** [comment]
This is already implemented. Code is [here](https://github.com/babel/babel/blob/development/packages/babel-core/src/transformation/file/options/option-manager.js).

**Comment by sebmck** [comment]
[L160](https://github.com/babel/babel/blob/development/packages/babel- core/src/transformation/file/options/option-manager.js#L160) passes the `dirname` of the config to `normalisePlugins`.

**Comment by jmm** [comment]
Great, thank you! (Looks like it's currently [L174](https://github.com/babel/babel/blob/745f9fb5bd9dd5600ae0264d720ef0e16cc66228/packages/babel-core/src/transformation/file/options/option-manager.js#L174), in case anyone else is interested.)

**Comment by mnpenner** [comment]
How can I change which directory the plugins are resolved against? I don't see a `dirname` option in the [API](https://babeljs.io/docs/usage/api/).
