### ISSUE TITLE
flow type annotations with default parameters in arrow functions fail eslint due to Parsing error: Assigning to rvalue

### ISSUE THREAD

**Issue by davidjnelson** [babel/babel#2493]
If I have code like this:

```javascript
let hello = (greeting:string = ' world') : string => {
console.log('hello' + greeting);
};

hello();
```

I get this error when I run: ```node_modules/eslint/bin/eslint.js .```:

Parsing error: Assigning to rvalue

If I don't use arrow functions it works fine, ie:

```javascript
let hello = function (greeting:string = ' world') : string {
console.log('hello' + greeting);
};

hello();
```

I created a repo to help reproduce it:

https://github.com/davidjnelson/flow-issues

For now I'll workaround by not using arrow functions and manually binding the this context when using default parameters, but I'd sure like them together :-) Thanks so much!

**Comment by resistdesign** [comment]
Getting the same problem.

**Comment by marudor** [comment]
It works for number default Values. strings do not.

**Comment by davidjnelson** [comment]
Right on @sebmck !!  Thanks for fixing this 😄😄😄

**Comment by resistdesign** [comment]
Awesome!
