### ISSUE TITLE
like usedHelpers but for regeneratorRuntime

### ISSUE THREAD

**Issue by guybedford** [babel/babel#2495]
usedHelpers is great for knowing when to include the runtime, but if just using `regeneratorRuntime`, there is no indication after processing a given file that the runtime is needed.

If there was something like `usesRegeneratorRuntime` that would be useful to unify this reporting. Even a general option like `needsBabelRuntime` would be useful. No problem if it's low down on the list - I will just throw a regex at it otherwise, but something along these lines might complete the use case.

**Comment by sebmck** [comment]
Helpers are a Babel core concept so it makes sense to expose that kind of metadata. There's going to be nothing regenerator-specific in core so I'm not sure how or if it's a good idea to have plugins expose this kind of metadata.

**Comment by guybedford** [comment]
I guess the argument is simply that it would be nice if the async plugin that is responsible for adding the `regeneratorRuntime` global was able to inform that the transpiled file will now expect that global to be present, so we can understand what is needed to make the code work properly.

`runtime` transformation is certainly the best way to manage this stuff though, so it's not worth worrying too much about these global helpers workflows I agree - rather save effort for more worthwhile things!
