### ISSUE TITLE
addImport form question

### ISSUE THREAD

**Issue by guybedford** [babel/babel#2496]
We've hit an issue with ES interop (https://github.com/gaearon/babel-plugin-react-transform/issues/35) where the `addImport` call in a transform is generating code in the System transformer that is effectively the equivalent to:

```javascript
setters: [function(_transformAddedImport) {
  transformAddedImport = _transformAddedImport;
}]
```

The above is effectively the analog of `import * as transformAddedImport from 'transform-added-import'`.

My question is how can one use `addImport` in a way that would match the behaviour of `import transformAddedImport from 'transform-added-import'` since in this case the module being referenced is a react component on the `default` export.

My knowledge of the `addImport` and plugin API are very limited, so apologies for any oversights in the above in advance. Let me know if the use case is unclear though.

**Comment by sebmck** [comment]
They're using a private API so I'm not surprised this isn't working correctly.

**Comment by guybedford** [comment]
Thanks @sebmck what would be the suggested way for a plugin to add an extra import then? Via injecting the syntax somehow?

**Comment by thejameskyle** [comment]
Wait `file.addImport` is considered a private API?

**Comment by timbur** [comment]
Is there an official public method for adding imports?

**Comment by sebmck** [comment]
Nope.

**Comment by sebmck** [comment]
Closing as there's nothing actionable here. There is now a public `addImport` API that will eventually be documented.

**Comment by timbur** [comment]
Nice!
