### ISSUE TITLE
Babel sometimes keeps generating the same files in "watch directory" mode 

### ISSUE THREAD

**Issue by jbitoniau** [babel/babel#2497]
I'm using babel (on Windows) to produce javascript from React JSX files with the following command line arguments:
babel myFolder --watch --out-dir myFolder --extensions ".jsx"

It correctly detects any changes in my jsx files and automatically regenerates the corresponding js files.
but sometimes, it seems to be doing it multiple times for a single change.
and later, after more changes it seems to systematically keeps looping on the same file forever

**Comment by sebmck** [comment]
Babel doesn't use any magic for watching files. You can see the usage of the library that Babel uses called `chokidar` [here](https://github.com/babel/babel/search?utf8=%E2%9C%93&q=chokidar). I'd recommend reporting whatever issues you have over there as Babel just acts on events emitter by it.
