### ISSUE TITLE
**= operator triggers getter on global object twice

### ISSUE THREAD

**Issue by xfix** [babel/babel#2498]
Something like this should return ``true``, but it doesn't, as a getter was triggered two times. Could be easily fixed by assigning ``reader`` to a variable, I believe.

(it's extremely minor because who would put getters on global objects, but still it shouldn't work that way)

```javascript
let counters = 0
Object.defineProperty(window, 'reader', {
  get() {
    counters += 1
    return {x: 2}
  },
  configurable: true,
})
reader.x **= 2
console.log(counters === 1)
```

**Comment by sebmck** [comment]
This is expected behaviour. There's nothing to do with `**` or Babel here. You can see this by running the following:

```javascript
let counters = 0
Object.defineProperty(window, 'reader', {
  get() {
    counters += 1
    return {x: 2}
  },
  configurable: true,
})
reader.x = reader.x;
console.log(counters === 2);
```

**Comment by xfix** [comment]
I'm not sure if I understand. A variable should be accessed only once, not twice, because of an augmented assignment. If I put ``reader.x += 2``, ``reader`` is only accessed once (one get of ``reader``, one get of ``reader.x``, and one set.of ``reader.x``).

**Comment by sebmck** [comment]
Ah I see, nevermind. Tiring day.

**Comment by sebmck** [comment]
Fixed in the `development` branch due out for 6.0. Thanks for the report!
