### ISSUE TITLE
regenerator doesn't exist

### ISSUE THREAD

**Issue by natew** [babel/babel#2501]
After trying a few things with the CLI and checking this:

```
http://babeljs.io/docs/advanced/transformers/other/regenerator/
```

I can't seem to get regenerator to work using:

```
node node_modules/babel/bin/babel "$f/src" --out-dir "$f/lib" --stage 0 --optional bluebirdCoroutines regenerator --copy-files $1 &
```

I've tried a few variations, but i get:

```
regenerator doesn't exist
```

How does one enable it? I tried npm install regenerator in the same directory with no luck. Perhaps some documentation updates on the babel page showing how to use it?

**Comment by loganfsmyth** [comment]
Please see the README:

>  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Your question doesn't really makes sense anyway, because regenerator is on by default and `bluebirdCoroutines` will disable it.

**Comment by natew** [comment]
Ah, ok so I figured out the problem. I had babel configuration in my package.json *as well* as in .babelrc, and it was using the one in package.json over the .babelrc.

So if this could count towards a feature request:

Warn if it detects multiple babel configurations!

**Comment by sebmck** [comment]
The problem is that `optional` expects a single argument. Separate your transform list with commas.
