### ISSUE TITLE
babel.parse is underrated!

### ISSUE THREAD

**Issue by resistdesign** [babel/babel#2502]
I was hoping you might agree that `babel.parse` is underrated and should be documented here: https://babeljs.io/docs/usage/api/

**Comment by sebmck** [comment]
It's being removed in Babel 6 in favor of encouraging use of the `babylon` API directly.

**Comment by sebmck** [comment]
Also for future reference, please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

Thanks! :blush:

**Comment by resistdesign** [comment]
Ok, np :) Thank you :)

**Comment by resistdesign** [comment]
@sebmck Where do I find this elusive babylon API!?

**Comment by sebmck** [comment]
It wont be documented until Babel 6.

**Comment by resistdesign** [comment]
Will there be a way to get an output similar to what `parse` returns? Just wondering if I can code against `parse` and easily swap out some method later.

**Comment by sebmck** [comment]
`babel.parse` is literally just a wrapper around the parser `babylon`. The code for `babel.parse` is [here](https://github.com/babel/babel/blob/master/packages/babel/src/api/node.js#L81-L106). The output that you're referring to is called an AST and the specification for the Babel 5.x AST is [here](https://github.com/estree/estree).

**Comment by resistdesign** [comment]
Oh, I didn't know you had a spec for the AST, awesome! :)

**Comment by resistdesign** [comment]
Oh right duh, I've seen estree
