### ISSUE TITLE
Automatically Bring React Into Scope for JSX

### ISSUE THREAD

**Issue by cwarden** [babel/babel#2504]
When converting JSX to javascript, `React` is assumed to be in scope so you end up with a ReferenceError if it's not defined.  With the removal of `react/addons` and introduction of stateless functional components in react 0.14, it's more likely that `React` will not be in scope.

Here's a simple example:
```
var test = require('tape');
var TestUtils = require('react-addons-test-utils');

var Stateless = function() {
        return <div/>;
};

test('jsx test', function(t) {
        var renderer = TestUtils.createRenderer();
        renderer.render(<Stateless />);
        var output = renderer.getRenderOutput();
        t.equal(output.type, 'div');
        t.end();
});
```

If you try to run this test, you'll get an error:
```
> browserify test.js -t babelify | testling

TAP version 13
# jsx test
not ok 1 Error: Uncaught ReferenceError: React is not defined on line 32719
```

It would be nice if babel automatically injected the statement to require `React`.

**Comment by sebmck** [comment]
This is far too opinionated and isn't behaviour that we're likely going to want to enforce on users. Feel free to autorequire it with your module bundler though.

**Comment by loganfsmyth** [comment]
There is also https://www.npmjs.com/package/babel-plugin-react-require as a potential option.
