### ISSUE TITLE
Comprehensions with conditions are not parsed correctly

### ISSUE THREAD

**Issue by okigan** [babel/babel#2506]
Picked up example from mozilla webpage [1]: 

    var numbers = [ 1, 2, 3 ];
    var letters = [ "a", "b", "c" ];
    
    var result = [for (i of numbers) if (i > 1) for (j of letters) if(j > "a") i+j]

    result.forEach(r => console.log(r))

Produces error:

    repl: Unexpected token (4:44)
      2 | var letters = [ "a", "b", "c" ];
      3 | 
    > 4 | var result = [for (i of numbers) if (i > 1) for (j of letters) if(j > "a") i+j]
        |                                             ^
      5 | 
      6 | result.forEach(r => console.log(r))

[1] line 14 from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions#Browser_compatibility

**Comment by sebmck** [comment]
Array comprehensions are not on standards track and are being removed in Babel 6.
