### ISSUE TITLE
Suggestion for experimental IE8 support

### ISSUE THREAD

**Issue by Alhadis** [babel/babel#2507]
From [the docs](https://babeljs.io/docs/advanced/caveats/):
> In IE8 Object.defineProperty can only be used on DOM objects. This is unfortunate as it's required to set getters and setters. Due to this if you plan on supporting IE8 or below then the usage of getters and setters isn't recommended.

There is an easy (albeit ridiculous) workaround:
```js
/**
 * IE8 Property Patch
 *
 * This stupid hack attempts to circumvent IE8's inability to define properties on native JS
 * objects by merging their properties/methods into a detached DOM element and returning it.
 *
 * @param {Function|Object} obj - Native JS object before it's targeted by Object.defineProperty
 * @return {HTMLElement}
 */
function IE8PP(obj){

	if(obj instanceof Element)
		return obj;

	if("function" === typeof obj)
		return function(){
			var shadow = document.createElement("s");
			for(var p in obj.prototype)
				shadow[p] = obj.prototype[p];
			shadow.prototype = obj.prototype;
			obj.apply(shadow, arguments);
			return shadow;
		}

	else{
		var shadow = document.createElement("s");
		for(var p in obj)
			shadow[p] = obj[p];
		shadow.prototype = obj;
		return shadow;
	}
}
```

Usage:
```js
var Point = function(x, y){
	var x = x;
	var y = y;

	Object.defineProperty(this, "x", {
		get: function(){ return x },
		set: function(i){ x = i; }
	});

	Object.defineProperty(this, "y", {
		get: function(){ return y },
		set: function(i){ y = i; }
	});
};

Point = IE8PP(Point);

var p = new Point(20, 20);
console.log("[" + p.x + ", " + p.y + "]");
p.x += 50;
p.y += 20;
console.log("[" + p.x + ", " + p.y + "]");
```

What `IE8PP` does is redirect a constructor function to operate within the scope of a newly-created/detached DOM element, migrating all related prototype properties where necessary.

Obviously this is hazardous and weird; aside from not being the most performant solution, it also screws with the prototype chain for IE8 and makes things like `instanceof` impossible to rely on.

But for developers who're aware of the risks and are prepared to pen their code carefully to cater for antique browsers, this is a viable solution, since it allows existing code to run transparently... all one has to do is hit a class/object with IE8PP before it's targeted by `Object.defineProperty`.

**NB:** I haven't managed to get this technique working with Babel's compiled code yet, as IE8 seems to choke inside the `_get` function (where getOwnPropertyDescriptor is used, I think). Bottom-line is this **does** work, and there's a [demo here](http://s.codepen.io/Alhadis/debug/MaoeLX) where you can see for yourself (Have to link to the debugging version only, because the rest of CodePen doesn't work with IE8, heh).

**Comment by loganfsmyth** [comment]
This trades a sometimes-useful feature of ES5/6, getters/setters, for a core piece of the language, `instanceof`. Doesn't seem like a good trade to me.

What are you hoping to get out of the issue? As you've said, it doesn't work with class syntax because instanceof is broken, and it's not at all a general solution. If people want to hackily use getters and setters in IE8, then they should do it manually.

**Comment by Alhadis** [comment]
Sorry, I neglected to mention this should only target IE8. I've amended the code in the first block to reflect that.

Basically, this comes down to not forcing developers to write two sets of code for class models if they need to support crap browsers. Furthermore, this would be behind a flag, so it's not as though it'd be default behaviour.

**Comment by jmm** [comment]
@Alhadis 
> Even if this mode isn't workable as a feature, isn't there any way to customise the transformer Babel uses for transpiling class properties?

In v6 all of the transformers will be plugins, so you could make your own customised version and use that instead.

**Comment by Alhadis** [comment]
Ah, alright then. :) Sounds good! I suppose I'll need to wait then, haha.
