### ISSUE TITLE
Static methods should be not be enumerable

### ISSUE THREAD

**Issue by dalgard** [babel/babel#2513]
Static methods should not be enumerable in browsers that support property descriptors. This includes inherited static methods.

EDIT: I read up on the spec, and it turns out static methods should be writable and configurable.

**Comment by dalgard** [comment]
Note: `Object.assign` cannot be used to [copy over static methods](https://github.com/babel/babel/blob/master/packages/babel/src/transformation/templates/helper-extends.js), when they become non-enumerable:

**Comment by zloirock** [comment]
[They are non-enumerable](https://goo.gl/bazdaF) with default class transformer (not in loose mode).

**Comment by dalgard** [comment]
The same second you posted that, I discovered that the problem was with the newest version of Meteor (`1.2.0.2`) doesn't use the newest version of Babel. For shame......

Sorry for taking up your time.
