### ISSUE TITLE
runtime transformer + modules ignore

### ISSUE THREAD

**Issue by guybedford** [babel/babel#2514]
Is there anyway to have the runtime transformer output ES module import statements when applied alongside modules ignore?

The use case for this is that I want Babel to add its helper requires and everything, but still output ES modules so that I can run them through rollup for dead-code-elimmination optimizations, before doing the System.register thing after that separately.

**Comment by sebmck** [comment]
> alongside modules ignore?

Are you referring to the module formatter `ignore`?

**Comment by guybedford** [comment]
Yes exactly.

**Comment by sebmck** [comment]
> The use case for this is that I want Babel to add its helper requires and everything, but still output ES modules so that I can run them through rollup for dead-code-elimmination optimizations, before doing the System.register thing after that separately.

I'm very confused by this. The `ignore` module formatter **removes** module declarations. eg.

```javascript
export var foo = "";
```

becomes just

```javascript
var foo = "";
```

If you want to retain the original ES2015 module declarations then you can `blacklist` `es6.modules`.

**Comment by guybedford** [comment]
AMAZING! It works!

Sorry the confusion is all mine here, I just blindly assumed that no module output would be a module option not a transformer.
