### ISSUE TITLE
async sourcemaps

### ISSUE THREAD

**Issue by matthiasg** [babel/babel#2515]
I was experimenting with async support in our project and while the implementation works the generated source maps are not really helpful i think. To me its seems they are jumping around without actually following the code . When i compare this to the source maps from https://github.com/MatAtBread/browserify-nodent i think the babel ones are lacking a little. 

Does anybody else have the same issue ?

**Comment by sebmck** [comment]
Are you asking whether or not source maps are buggy for regenerator compiled async functions or are you making a statement that they are? There should not be any problem with source maps.

**Comment by sebmck** [comment]
BTW I'd heavily recommend against using nodent. It gets the semantics very wrong and doesn't handle abrupt completions and iteration pausing very well.

**Comment by matthiasg** [comment]
Well for me the source maps are not working well at all. At first glance it looked ok, but stepping through often results in quite weird jumps that don't follow the steps all the time...

Thanks about the nodent feedback. Is there anything else nodent gets wrong other than what you mentioned? 

----- Ursprüngliche Nachricht -----
Von: "Sebastian McKenzie" <notifications@github.com>
Gesendet: ‎11.‎10.‎2015 03:39
An: "babel/babel" <babel@noreply.github.com>
Cc: "matthiasg" <mgt576@gmail.com>
Betreff: Re: [babel] async sourcemaps (#2515)

BTW I'd heavily recommend against using nodent. It gets the semantics very wrong and doesn't handle abrupt completions and iteration pausing very well.

**Comment by lydell** [comment]
@matthiasg Tip: Upload your source map to this [online source map visualization] (https://sokra.github.io/source-map-visualization/), and share a link to it here. (There's even a [CLI tool to help doing so](https://github.com/lydell/source-map-visualize).) That's a great way of finding source map problems.

**Comment by matthiasg** [comment]
@lydell thats a great tip, thanks .. the code in question is not (yet) open source so i cannot simply link this here but i will look at it and if required i could link an excerpt or so ...

**Comment by matthiasg** [comment]
@lydell i tried it with source-map-visualize but from the command line it doesnt work (https://github.com/lydell/source-map-visualize/issues/2).

with the online tool its also not working well. on the left i see about two pages of script  and on the right the entire remaining code but  the moment i scroll down past the left two pages i dont get any highlights anymore.

i am not sure how this tool works anyway, when i cluck custom it asks me for the generated source file ... so i provide my compiled js file but then it doesnt ask me for the map file.. so how can i specify my map file anyway ?

then again i just realized that our gulp/babel/exorcist flow doesn't remove the `//# sourceMappingUrl=data:application ... ` lines, maybe thats screwing it up

**Comment by matthiasg** [comment]
ok when i removed the superflous old sourcemap lines (the inline ones) it did behave better and ask me for the map file, sadly now it complains about '..\node_modules\browserify\lib\_empty.js' missing just like in https://github.com/lydell/source-map-visualize/issues/2

**Comment by lydell** [comment]
As far as I remember the online visualizer never complains about missing source files, it merely asks you to upload them.

**Comment by matthiasg** [comment]
i found an error in my source (i renamed a file without renaming the appropriate import, tests where also failing, missed that).

**Comment by MatAtBread** [comment]
@sebmck - can you explain the semantic issues you're alluding to. Whereas the implementation is very different (syntax transformation as opposed to generators), I've tried to follow the syntactic and semantics of the spec, as far as I understand them.

**Comment by sebmck** [comment]
Try it over all the tests [here](https://github.com/facebook/regenerator/blob/master/test/async.es6.js). `await` has the same semantics as `yield` in generators so using the technique that regenerator uses isn't so far out of the ordinary.

**Comment by MatAtBread** [comment]
Thanks - I'll take a look

**Comment by sebmck** [comment]
Closing this issue as there's nothing actionable.

**Comment by danbucholtz** [comment]
@sebmck, I am seeing this issue as well.  The sourcemaps are horrible with await/async and make it very tough to use the debugger.  Is there any way we can improve them?

**Comment by talarari** [comment]
hey, any update on this?
source maps are incorrect so debugging doesn't work well, see
Microsoft/vscode#19973

**Comment by kylezinter** [comment]
@kittens Why was this closed? Was looking into an issue with debugging Babel compiled code in VS code and they also mentioned that the source maps being generated around async/await are incorrect by Babel. Is there a spec of some sort for source maps around async/await somewhere that we can compare against to verify this? [https://github.com/Microsoft/vscode/issues/45345](https://github.com/Microsoft/vscode/issues/45345)
