### ISSUE TITLE
'Static Properties' proposal doesn't match output

### ISSUE THREAD

**Issue by zyklus** [babel/babel#2516]
See [repl](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=class%20Base%20%7B%0A%20%20initialized()%20%7B%20return%20'base%20initialized'%3B%20%7D%0A%20%20uninitialized()%20%7B%20return%20'base%20uninitialized'%3B%20%7D%0A%7D%0A%0Aclass%20Child%20extends%20Base%20%7B%0A%20%20initialized%20%3D%20()%20%3D%3E%20'child%20initialized'%3B%0A%20%20uninitialized%3B%0A%7D%0A%0Avar%20child%20%3D%20new%20Child()%3B%0Achild.initialized()%3B%20%2F%2F%20'child%20initialized'%0Achild.uninitialized()%3B%20%2F%2F%20'base%20uninitialized'%0A%0ABase.prototype.initialized%20%3D%20()%20%3D%3E%20'new%20base%20initialized'%3B%0ABase.prototype.uninitialized%20%3D%20()%20%3D%3E%20'new%20base%20uninitialized'%3B%0A%0Aconsole.log(child.initialized())%3B%20%2F%2F%20Remains%20'child%20initialized'%0Aconsole.log(child.uninitialized())%3B%20%2F%2F%20Remains%20'base%20uninitialized'), which is a copy (with console.log statements) of the example on the [spec repo](https://github.com/jeffmo/es-class-static-properties-and-fields).  Notice that the output of the last line doesn't match what the spec says.

**Comment by sebmck** [comment]
Merging into #2460.
