### ISSUE TITLE
Decorators and plain object properties

### ISSUE THREAD

**Issue by fatfisz** [babel/babel#2519]
I understand that when it comes to property initializers, there might be a need to perform some hocus-pocus with the `initializer` property, which effectively prevents modifying descriptor's `value` (it is overwritten by the result of the `initializer` function in the end).

But for plain objects descriptor's `value` can be left intact. Accessing it by a decorator is currently unnecessarily prevented.

Could it be not so? If yes, then I volunteer to create a PR with a fix for that :)

**Comment by fatfisz** [comment]
For now I'm using a decorator that fixes this:
```js
function fixDescriptor(target, key, descriptor) {
  if (descriptor.initializer) {
    descriptor.value = descriptor.initializer.call(target);
    delete descriptor.initializer;
  }
}
```
... but remembering to put it in front of all properties isn't something I'm looking forward to.

**Comment by sebmck** [comment]
There's nothing to fix here. This is in the specification/proposal and it wont be changed unless it is there. See the [javascript-decorators repo](https://github.com/wycats/javascript-decorators) for more information.

**Comment by fatfisz** [comment]
Could you please point me to the right place, because in the README.md file there is nothing written about plain object properties, and INITIALIZER_INTEROP.md is only concerned with classes.

I've already read that spec carefully before. If you're not convinced, then maybe I'll take it to the spec so that this case will be clarified there.

**Comment by sebmck** [comment]
https://github.com/wycats/javascript-decorators/pull/36
