### ISSUE TITLE
Nested arrays on evalution includes '(' 

### ISSUE THREAD

**Issue by annamalai-saro** [babel/babel#2523]
Check this link 

http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=let%20%20a%3D%5B1%2C2%2C3%5B4%2C%5B5%2C%5B6%5D%5D%5D%5D%3B%0A%0Aconsole.log(a)%3B

I have a variable 

```js
let  a=[1,2,3[4,[5,[6]]]];
```

on evaluvating ,

```js
var a = [1, 2, 3[(4, [5, [6]])]];
```

**Comment by bloodyowl** [comment]
you are missing a comma after `3`

**Comment by annamalai-saro** [comment]
Very silly :+1:
