### ISSUE TITLE
test directory not being ignored by npm

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2525]
In the last few releases the `test` directory has been included in the npm package, including some generated fixtures.

**Comment by ericclemmons** [comment]
I was just about to open this same issue.

Not 100% sure why this would be happening, though:
> https://github.com/babel/babel/blob/71031be044d783704c356e4cbeeb54d5a37a223d/packages/babel/.npmignore#L5

**Comment by sebmck** [comment]
Are any of the other files that are in `.npmignore` being included?

**Comment by ericclemmons** [comment]
@sebmck Let's see...

```shell
~/tmp    node --version && npm --version
v4.1.1
2.14.1
~/tmp    npm install babel
...
~/tmp    tree node_modules/ -L 2
node_modules/
└── babel
   ├── README.md
   ├── bin
   ├── index.js
   ├── lib
   ├── node_modules
   ├── package.json
   ├── polyfill.js
   ├── register-without-polyfill.js
   ├── register.js
   ├── scripts
   ├── src
   └── test

7 directories, 6 files
```

So it looks like the following are erroneously included (perhaps do to paths being absolute in `.gitignore`?):

- scripts
- src
- test

**Comment by ericclemmons** [comment]
Also, with the latest NPM:

```shell
 ~/tmp    node --version && npm --version && tree -L 1 node_modules/babel
v4.2.1
3.3.6
node_modules/babel
├── README.md
├── bin
├── index.js
├── lib
├── package.json
├── polyfill.js
├── register-without-polyfill.js
├── register.js
├── scripts
├── src
└── test

5 directories, 6 files
```

The same offenders of `src`, `scripts`, and `test`.

**Comment by sebmck** [comment]
wtf npm

**Comment by sebmck** [comment]
Just republished a new version with no changes. Let me know if the files are still present.
