### ISSUE TITLE
Syntax error: return outside of function

### ISSUE THREAD

**Issue by forabi** [babel/babel#2526]
```
❯ babel . -o index.es5.js
SyntaxError: node_modules/babel/test/index.js: 'return' outside of function (1:40)
> 1 | if (process.env.running_under_istanbul) return;
    |                                         ^
  2 |
  3 | var readdir        = require("fs-readdir-recursive");
  4 | var helper         = require("mocha-fixtures");

```

Here is my .babelrc:
```json
{
  "stage": 1,
  "optional": ["es7.classProperties"],
  "ignore": [
    "node_modules"
  ]
}
```
Global babel version: 
```
❯ babel --version
5.8.23 (babel-core 5.8.25)
```

**Comment by loganfsmyth** [comment]
Dup of https://github.com/babel/babel/issues/1298

**Comment by loganfsmyth** [comment]
Babel ignores `node_modules` by default, leave that out of your `.babelrc`

**Comment by forabi** [comment]
Notice this line:
```
SyntaxError: node_modules/babel/test/index.js: 'return' outside of function (1:40)
```

The file `test/index.js` belongs to the babel module and is indeed inside `node_modules`. I'm not sure why Babel is trying to compile it.

**Comment by thejameskyle** [comment]
@forabi Something is incorrect about your setup. You should be ignoring the `node_modules` directory.

**Comment by loganfsmyth** [comment]
@forabi Sorry, my mistake for missing that. I'd recommend avoiding using `.` in favor of a subdirectory. as that is much more common.
