### ISSUE TITLE
Destructuring a function arguments within an array does not cause SyntaxError

### ISSUE THREAD

**Issue by jakecraige** [babel/babel#2527]
Today I came across what looks like a bug. 

If you try to destructure arguments to a function that's within an array it silently fails instead of giving a SyntaxError.

The failing code looks like:

```js
const doesntCompileProperly = [
  ...args => console.log(args)
];
```

and compiles to:

```js
var doesntCompileProperly = [].concat(_toConsumableArray(function (args) {
  return console.log(args);
}));
```

Here's a link to a few other examples in the Babel repl: [babeljs.io repl link](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=const%20compilesAsExpected%20%3D%20%5B%0A%20%20(...args)%20%3D%3E%20console.log(args)%0A%5D%3B%0A%0Aconst%20doesntCompileProperly%20%3D%20%5B%0A%20%20...args%20%3D%3E%20console.log(args)%0A%5D%3B%0A%0A%2F%2F%20const%20syntaxErrorInObject%20%3D%20%7B%0A%2F%2F%20%20%20something%3A%20...args%20%3D%3E%20console.log(args)%0A%2F%2F%20%7D%3B%0A%0A%2F%2F%20const%20syntaxErrorByItself%20%3D%20...args%20%3D%3E%20console.log(args))

**Comment by zloirock** [comment]
It should be runtime error - correct syntax, but functions are not iterable. Duplicate #2160.

**Comment by jakecraige** [comment]
@zloirock Is that valid ES6 syntax for defining a function?

**Comment by jridgewell** [comment]
You need to wrap a rest parameter with an arrow function, you have to wrap the parameters.

```js
(...args) => console.log(args)
```

**Comment by jakecraige** [comment]
@jridgewell That's what I was thinking, which is why I thought this should be a SyntaxError and was asking if the given example is valid ES6.

**Comment by jridgewell** [comment]
[It is](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&playground=false&code=...args%20%3D%3E%20console.log(args)%0A).

Babel interpreted yours as a spread operator and a single param arrow: `...((args) => console.log(args))`. Thats why @zloirock linked to #2160.

**Comment by loganfsmyth** [comment]
Yup! What @jridgewell said. Iterating a function should throw, but it doesn't at the moment.
