### ISSUE TITLE
IIFE of arrow functions is transpiled wrong if `--blacklist es6.arrowFunctions`

### ISSUE THREAD

**Issue by mysticatea** [babel/babel#2531]
Hello.

I have a problem.

```js
// test.js
var foo = (bar => bar)("hello");
assert(foo === "hello");
```

```
> babel --version
5.8.23 (babel-core 5.8.25)
> babel --blacklist es6.arrowFunctions test.js
"use strict";

var foo = bar => bar("hello");
assert(foo === "hello");
```

Parentheses which encloses an arrow function were lost.
I expected to not change code around that arrow function.

Do I need other setting here?

Thank you.

**Comment by sebmck** [comment]
Babel doesn't retain significant whitespace and parentheses.

**Comment by mysticatea** [comment]
@sebmck Does Babel remove parentheses even if it changes semantics? In this case, IIFE was changed to calling the first argument.

**Comment by sebmck** [comment]
Oh right. I didn't read the issue closely enough. The code gen needs to be updated.
