### ISSUE TITLE
Not all babel-plugin-* dependencies in babel-core are open-sourced/licensed

### ISSUE THREAD

**Issue by mkillianey** [babel/babel#2532]
I'd like to use packages that depend on the babel-core library, but I'm having trouble meeting the licensing requirements.  babel-core has dependencies on these babel-plugins that do not appear to be (currently) open-sourced and do not include license files.  From https://github.com/babel/babel/blob/v5.8.26/packages/babel/package.json#L30-L44 : 

    "babel-plugin-constant-folding": "^1.0.1",
    "babel-plugin-dead-code-elimination": "^1.0.2",
    "babel-plugin-eval": "^1.0.1",
    "babel-plugin-inline-environment-variables": "^1.0.1",
    "babel-plugin-jscript": "^1.0.4",
    "babel-plugin-member-expression-literals": "^1.0.1",
    "babel-plugin-property-literals": "^1.0.1",
    "babel-plugin-proto-to-assign": "^1.0.3",
    "babel-plugin-react-constant-elements": "^1.0.3",
    "babel-plugin-react-display-name": "^1.0.3",
    "babel-plugin-remove-console": "^1.0.1",
    "babel-plugin-remove-debugger": "^1.0.1",
    "babel-plugin-runtime": "^1.0.7",
    "babel-plugin-undeclared-variables-check": "^1.0.2",
    "babel-plugin-undefined-to-void": "^1.1.6",

Each of the package.json files from the above plugins suggest that these are located in repos named https://github.com/babel-plugins/babel-plugin-xxx, but looking at https://github.com/babel-plugins there seem to be only three public repos in that project:  babel-plugin-incremental-dom, babel-plugin-flow-comments, and babel-plugin-emojification.

Did the repos for these plugins get accidentally/intentionally taken private or moved elsewhere?  Can someone help me meet the licensing requirements for the above libraries, preferably by pointing me to a public home for the source for these dependencies?  Thanks in advance for any pointers!

**Comment by sebmck** [comment]
They've been moved into the `packages` folder in the [development](https://github.com/babel/babel/tree/development/packages) branch. They've all got the `package.json` `license` field of `MIT` and are inside of the main Babel repo which contains an explicit LICENSE file.

If you need any further assistance please feel free to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!

**Comment by mkillianey** [comment]
Ah, sorry to have raised this in the wrong place...I'll be sure to bring up any future issues there first.  To anyone else who runs into this same problem, please note that in addition to the location change, each of the plugins has also been renamed, from "babel-plugin-xxx" to "babel-plugin-transform-xxx".

Thanks for the great work -- I hope you take my licensing question as a compliment that what you have created/are creating is super-useful!
