### ISSUE TITLE
Mixing references to `some-plugin` and `babel-plugin-some-plugin` results in 'plugin {{plugin}} collides with another of the same name' error

### ISSUE THREAD

**Issue by jmm** [babel/babel#2533]
`babel-core@5.8.25`. I don't know if other changes have made this irrelevant for v6.

Suppose there's a babel plugin installed as `node_modules/babel-plugin-something` and identifying itself to babel as `something`. If there are multiple `.babelrc` that reference the same plugin consistently as either `babel-plugin-something` or `something` (but not both), no problem. However, if the two are mixed it causes:

> ReferenceError: The plugin "something" collides with another of the same name

Here is a [minimal repro](https://github.com/jmm/babel-same-plugin-collision-repro). Note that that is not the situation I actually ran into this with, it's the most reduced case I could think of. I ran into this while trying to browserify an app that has a depdendency on a package with a `.babelrc`, and `babelify` configured in its `package.json`.

On another note, picking up the browserify scenario: what if the app and dep depend on different versions of the same plugin? So each version of the plugin would try to register with babel using the same name, but they wouldn't resolve to the same package.

**Comment by sebmck** [comment]
This is pretty much expected behaviour. Two plugins can't have the same UID in 5.x. This is changing in 6.0 where there are no unique references to plugins.

**Comment by jmm** [comment]
@sebmck

> Two plugins can't have the same UID in 5.x.

In the repro there's only one plugin though. Both references resolve to the same package (absolute path).

> This is changing in 6.0 where there are no unique references to plugins.

That sounds good.

**Comment by sebmck** [comment]
> In the repro there's only one plugin though. Both references resolve to the same package (absolute path).

You're still defining them twice and they're colliding.

**Comment by jmm** [comment]
@sebmck 
> You're still defining them twice and they're colliding.

Can you please clarify what you mean by "defining"?

In one case there are 2 `.babelrc` that contain `plugins: ["something"]` and there's no error.

In the other case there are 2 `.babelrc`. One contains `plugins: ["something"]`, the other `plugins: ["babel-plugin-something"]`. This generates an error. But they both refer to the exact same package installation (absolute path). So where is the collision here that there isn't in the other case?

**Comment by sebmck** [comment]
@jmm It's resolving to the same plugin but internally all transformers are defined in a simple object map. Where the transformer key (in this case `"something"`) is used as the map key. The error is being thrown because internally transformers are tracked via this key which is required to be a UID.

**Comment by jmm** [comment]
@sebmck 

> It's resolving to the same plugin but internally all transformers are defined in a simple object map. Where the transformer key (in this case "something") is used as the map key. The error is being thrown because internally transformers are tracked via this key which is required to be a UID.

I understand, but there are not 2 or more plugins to collide: in all cases in the repro there is only one plugin. There's no more a collision between 2 plugins in the `something` / `babel-plugin-something` case than there is in the `something` / `something` case.

I don't know if this relates to how `.babelrc` are merged or something else, but if there's not considered to be a collision in the case of multiple `.babelrc` that reference `something`, I don't think there should be in the other case either. In other words, is there a good reason for referring to the same plugin as `something` or `babel-plugin-something` not to be treated as equivalent?

**Comment by sebmck** [comment]
@jmm 

> I understand, but there are not 2 or more plugins to collide: in all cases in the repro there is only one plugin

The plugin has been declared twice for the same file though which is the cause of the warning.

> is there a good reason for referring to the same plugin as `something` or `babel-plugin-something` not to be treated as equivalent?

The definitions themselves are treated as equals but internally we still need to construct two separate [`PluginPass`](https://github.com/babel/babel/blob/edae7970b182561f4a7e2b4de30330645914a02e/packages/babel/src/transformation/plugin-pass.js) instances and we use the transformer key as a UID to refer to them.

**Comment by jmm** [comment]
@sebmck 

So it doesn't get lost at the bottom, I'll lead with this:

https://github.com/babel/babel/compare/babel:master...jmm:no-same-plugin-collision

This basically illustrates the behavior that I'm suggesting should be happening in this situation. Tests pass after these changes and it eliminates the error in my repro. (This is just quick and dirty for illustration purposes.)


> The plugin has been declared twice for the same file though which is the cause of the warning.

Can you please help me understand how it's been declared twice in one case but not the other?

Case `A`. If there's this there's no error:
```
// somedir/.babelrc
{
  "plugins": ["something"]
}

// somedir/subdir/.babelrc
{
  "plugins": ["something"]
}
```

Case `B`. If there's this there's an error:
```
// somedir/.babelrc
{
  "plugins": ["something"]
}

// somedir/subdir/.babelrc
{
  "plugins": ["babel-plugin-something"]
}
```

I reiterate that in all cases there is only one plugin / package installation / absolute path involved.

If case `A` isn't declaring the plugin twice but case `B` is, then I guess my question is, why? Why is it not a bug that one is declaring it twice and the other isn't?

> The definitions themselves are treated as equals but internally we still need to construct two separate PluginPass instances and we use the transformer key as a UID to refer to them.

So does that not happen for case `A`?
