### ISSUE TITLE
babel renames jsx to js but does not change the imports

### ISSUE THREAD

**Issue by mg** [babel/babel#2535]
Hi,
Im using the following to compile my ES6/7 code in js and jsx files

babel --stage=0 --ignore=*.spec.js --ignore=*.spec.jsx -d builds/prod/ src/

Now every *.jsx file in src is renamed to *.js. But index.js is transformed from

``` 
import { Unwrap, Wrapper } from './wrapper.jsx'
import { Add, AddProp, AddParentContext, AddChildContext } from './modify.js'
import { AddToContext, PickFromContext } from './context.jsx'
import Expose from './expose.js'
export {
  Unwrap, Wrapper,
  Add, AddProp, AddParentContext, AddChildContext,
  AddToContext, PickFromContext,
  Expose,
}
``` 

to 

``` 
'use strict';
Object.defineProperty(exports, '__esModule', {
  value: true
});
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
var _wrapperJsx = require('./wrapper.jsx');
var _modifyJs = require('./modify.js');
var _contextJsx = require('./context.jsx');
var _exposeJs = require('./expose.js');
var _exposeJs2 = _interopRequireDefault(_exposeJs);
exports.Unwrap = _wrapperJsx.Unwrap;
exports.Wrapper = _wrapperJsx.Wrapper;
exports.Add = _modifyJs.Add;
exports.AddProp = _modifyJs.AddProp;
exports.AddParentContext = _modifyJs.AddParentContext;
exports.AddChildContext = _modifyJs.AddChildContext;
exports.AddToContext = _contextJsx.AddToContext;
exports.PickFromContext = _contextJsx.PickFromContext;
exports.Expose = _exposeJs2['default'];
``` 
Notice that it is require'ing 'jsx' files that babel has now renamed to 'js'.

I expected that since babel was renaming my jsx files to js, it would fix the imports from jsx to js. Is there an option Im missing?

Cheers,
mg

**Comment by sebmck** [comment]
There's no option. Babel wont touch your module sources as it has no opinion on how you structure your code or how you bundle it. I'd recommend not using any extensions to be agnostic to whatever file structure you use.

**Comment by thejameskyle** [comment]
_Should_ Babel be renaming jsx files to js?

**Comment by sebmck** [comment]
Depends on your tool. The CLI does but that's not the issue at hand.
