### ISSUE TITLE
Possible optimisation of ES7 function binding

### ISSUE THREAD

**Issue by HugoGiraudel** [babel/babel#2540]
Given the following code:

```js
[1, 2, 3].forEach(::this.foo)
```

Babel compiles into (roughly):

```js
[1, 2, 3].forEach(this.foo.bind(this));
```

Wouldn't it be better to use the `thisArg` parameter of the `.forEach(..)` method in order to avoid a function binding (which might be costly)?

```js
[1, 2, 3].forEach(this.foo, this);
````

Same goes for `.map(..)`, `.filter(..)` and possible other `Array.prototype` methods having a `thisArg` parameter.

**Comment by zloirock** [comment]
The same problem like with prototype methods in `runtime` transformer - usualy we don't know is object array or, for example, `{forEach:console.log}`.

**Comment by sebmck** [comment]
We have no way to know what the signature of the functions is. As @zloirock mentions, you could easily override it and it's dangerous and unreliable to assume that all methods named `forEach` are going to behave this way.

**Comment by HugoGiraudel** [comment]
Interesting. Thanks. :)
