### ISSUE TITLE
Feature Request: --expr option

### ISSUE THREAD

**Issue by mnpenner** [babel/babel#2542]
I would like an `--expr` option, just [like UglifyJS](https://github.com/mishoo/UglifyJS2).

Essentially, it would make something like this:

```js
function(row, data, index) {
    $(row).toggleClass('other_ecr_doc', !data.uploaded_to_current_app);
}
```

compile instead of throw a syntax error.

N.B. this errors because it's missing a function name, but I want to use fragments like these as part of a larger script.

**Comment by sebmck** [comment]
You can just wrap it in parentheses. I don't think this use case is significant enough to warrant the implementation and maintenance of such a feature.
