### ISSUE TITLE
Default Export with `es7.exportExtensions` Turned On

### ISSUE THREAD

**Issue by gsklee** [babel/babel#2544]
Think this is better illustrated with an example...

---

`./configs/a.js`

```javascript
export default {
  a: 42
};
```

---

`./configs/index.js`

```javascript
export * as a from './configs/a';
```

---

`./some-where-else.js`

```javascript
import * as configs from './configs';

console.log(configs);

// {default: {a: 42}, a: 42}
```

---

I think `configs` should simply be `{a: 42}` in this case, otherwise it can cause some subtle bugs.

**Comment by sebmck** [comment]
It's due to the CommonJS default export interop which is being removed in Babel 6, see #2212.

**Comment by gsklee** [comment]
@sebmck Read #2212 and not sure if I got the gist.

`./some-where-else.js`

```javascript
import {default} as configs from './configs';

console.log(configs.default);

// {a: 42}
```

Is this how we're expected to do it in Babel v6?

**Comment by sebmck** [comment]
That's invalid syntax but it would be:

```javascript

import * as configs from './configs';

console.log(configs);

// { default: {a: 42} }
```

**Comment by gsklee** [comment]
Hmm got it, updated my example. Thanks!
