### ISSUE TITLE
Compilation bug?

### ISSUE THREAD

**Issue by roman01la** [babel/babel#2545]
In the following snippet of code `sum` function returns `103`, when executed in browser's console. But Babel output makes `sum` to return `0`. Is it a bug?

```js
function sum () {
  return (function sum_iter (arr, a) {
    var a=a||0;
    if (!arr.length)
      return a;
    a+=arr.pop();
    return sum_iter(arr, a)
  })([].splice.call(arguments,0))
}

console.log(sum(10, 89, 4))
```

**Comment by RReverser** [comment]
Related to #2405 - @sebmck this was likely the case that I meant in comment to that PR :D
