### ISSUE TITLE
Duplicate 'default' level when use import

### ISSUE THREAD

**Issue by gdipkf1986** [babel/babel#2546]
My ES6 code:
```javascript
import Ember from 'ember';
import $ from 'jquery';

Ember.MODEL_FACTORY_INJECTIONS = true;

const App = Ember.Application.extend({});
```

I transformed it via gulp-babel, got this file:
```javascript
define('app', ['exports', 'module', 'ember'], function (exports, module, _ember) {
  'use strict';

  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

  var _Ember = _interopRequireDefault(_ember);

  _Ember['default'].MODEL_FACTORY_INJECTIONS = true;

  var App = _Ember['default'].Application.extend(); 
  // previous line will cause an error, because actual structure is _Ember['default']['default'].Application, why?

  module.exports = App;
});
```

![image](https://cloud.githubusercontent.com/assets/1468041/10546661/e73f33de-7461-11e5-95db-e515a7b44106.png)

And I tried change 
```javascript
import Ember from 'ember'
``` 
to 
```javascript
import * as Ember from 'ember'
// and this 
import {Ember} from 'ember'
```
but got same issue, could anyone can help give a tip how to resolve this problem?

**Comment by sebmck** [comment]
Ember does not use any CommonJS interop. Ember uses the `amdStrict` module formatter, not the `amd` one.

If you require any further assistance please don't hesitate to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:

**Comment by gdipkf1986** [comment]
Thanks @sebmck !!!!!
