### ISSUE TITLE
Tail call optimization doesn't work when using default values referring to other parameters

### ISSUE THREAD

**Issue by joshuacaron** [babel/babel#2547]
Tail call optimization doesn't work properly if you use a function which has a default parameter refering to another parameter, for example:

```javascript
function test(a, b = a){
  if(a === 0) {
    return b
  } else {
    return test(a - 1, b)
  }
}
```

compiles to:

```javascript
"use strict";

function test(a) {
  var b = arguments.length <= 1 || arguments[1] === undefined ? a : arguments[1];
  return (function () {
    if (a === 0) {
      return b;
    } else {
      return test(a - 1, b);
    }
  })();
}
```

**Comment by loganfsmyth** [comment]
This is a downside to the current approach to the context injected for default arguments. Definitely something that'll need to be looked at.

**Comment by sebmck** [comment]
TCO has since been removed from Babel 6 due to issues and will be redeveloped in the future.

**Comment by estaub** [comment]
@sebmck The status should be updated in http://babeljs.io/docs/learn-es2015/#tail-calls

**Comment by sebmck** [comment]
Open an issue on the babel.github.io repo.

On Sun, Nov 15, 2015 at 7:17 AM, Ed Staub <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> The status should be updated in
> http://babeljs.io/docs/learn-es2015/#tail-calls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2547#issuecomment-156817291>.
>



-- 
Sebastian McKenzie
