### ISSUE TITLE
CLI: "--source-maps false" incorrectly produces source map

### ISSUE THREAD

**Issue by bdkjones** [babel/babel#2548]
If you use the Babel CLI and pass the option: `--sourcemaps false`, Babel still creates an empty source map file with no mappings filled in, like this:

<img width="548" alt="screen shot 2015-10-16 at 20 36 38" src="https://cloud.githubusercontent.com/assets/926566/10556831/f7bd8452-7445-11e5-8fbe-fa58b3b03f38.png">

If you pass `--source-maps true`, the source map file has content filled in:

<img width="656" alt="screen shot 2015-10-16 at 20 37 03" src="https://cloud.githubusercontent.com/assets/926566/10556832/0961f260-7446-11e5-804d-24ecfbfa06ec.png">

This has to be incorrect behavior. If `false` is passed for the option, that should mean, "Don't create a source map file at all." It should NOT mean, "Create a broken source map file that won't do anything because I love extra, broken files in my projects!"

**Comment by thejameskyle** [comment]
> This has to be incorrect behavior. If false is passed for the option, that should mean, "Don't create a source map file at all." It should NOT mean, "Create a broken source map file that won't do anything because I love extra, broken files in my projects!"

No need to be such a dick about it. We're perfectly capable of understanding this problem.

---

The problem here is [`commander.sourceMaps` here](https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/file.js#L12) is a string and `"false"` is being treated as truthy.

**Comment by bdkjones** [comment]
Hi James. Hmm. It was not my intention to be rude. Thanks for giving me the benefit of the doubt, though. I'll do the same for you and not use similar language in response.

**Comment by sebmck** [comment]
This is weird behaviour but I dunno why you'd specify this at all when the default behaviour is to produce no source maps. This should be a noop.

**Comment by bdkjones** [comment]
I'm integrating Babel into an app and I simply followed the CLI documentation: pass true or false depending on whether you want the maps or not. There is no documentation (that I can find) that says the default action is to produce no source-maps.

**Comment by sebmck** [comment]
Fixed in the `development` branch.
