### ISSUE TITLE
Iterator malfuntion?

### ISSUE THREAD

**Issue by guipasmoi** [babel/babel#2549]
//************* code *************************
function* gen(a){
  yield 1;
  yield 2;
  yield 3;
  return 4;
}
for(var t of gen()){
  console.log(t)
}
//************* result in console *************
1
2
3
//************* What??? ***********************
I am confused the result should be 1,2,3,4 no?
by the way chrome give the same résult as babel

I am sorry, if i am misunderstanding something thx for your time

**Comment by loganfsmyth** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

This is the expected behavior.
