### ISSUE TITLE
--copy-files doesn't preserve file permissions

### ISSUE THREAD

**Issue by olalonde** [babel/babel#2551]
I'm using babel to compile src/ to lib/. I have `src/cli/somecli.js` which is `chmod u+x` but babel doesn't preserve that permission which means I can't do `./lib/cli/somecli.js` in bash. Would be nice if there was an option to tell babel to preserve that permission.

**Comment by sebmck** [comment]
Duplicate of #1586.

**Comment by sebmck** [comment]
Actually, may as well for 6.0 I guess.

**Comment by sebmck** [comment]
Done in the `development` branch.

**Comment by olalonde** [comment]
Thanks.
