### ISSUE TITLE
const declaration in switch statement improperly recognized as duplicate

### ISSUE THREAD

**Issue by azmenak** [babel/babel#2553]
Declaring a `const` a second time in a switch should be possible if the second statement is unreachable.

```js
testytest = () => {
  switch (foo) {
    case a:
      const bar = 'foo';
      return bar;
    case b:
      const bar = 'baz';
      return bar;
  }
}
```

Throws error `Duplicate declaration "bar"`

**Comment by sebmck** [comment]
Why do you think that error is incorrect? It's expected behaviour. Case clauses do not create a lexical scope.

**Comment by loganfsmyth** [comment]
Yup, as @sebmck said, the entire body of a switch statement introduces a new block scope, but individual case statements do not, unless you explicitly do so, e.g.

```
testytest = () => {
  switch (foo) {
    case a: {
      const bar = 'foo';
      return bar;
    }
    case b: {
      const bar = 'baz';
      return bar;
    }
  }
}
```

**Comment by stevenvachon** [comment]
Is this still invalid? Chrome, Firefox and Safari seem to create block scopes for each `case` because no error is thrown.

**Comment by loganfsmyth** [comment]
Do you have a specific example in mind?

> Chrome, Firefox and Safari seem to create block scopes

At least in my Chrome console, that does not appear to be true:

<img width="468" alt="screen shot 2018-04-05 at 3 03 07 pm" src="https://user-images.githubusercontent.com/132260/38394240-8c2f9a9a-38e2-11e8-9be0-3d8a041d8133.png">

**Comment by stevenvachon** [comment]
```js
const a=true; switch(a) { case true: { const b=true; break; } case false: { const b=false; break; } }
```

**Comment by stevenvachon** [comment]
Re-reading your previous comment, I see that you had added encapsulating `{` and `}` for each `case`. I often do this in my code, but for prettiness, not knowing that it created a block.

**Comment by loganfsmyth** [comment]
Yeah, adding the `{ }` is a new lexical scope, so using `const` and `let` will not conflict with other `case`s. This issue is for the case where the additional blocks are omitted.
