### ISSUE TITLE
babel-plugin-transform-object-assign doesn't exist

### ISSUE THREAD

**Issue by davidgilbertson** [babel/babel#2554]
The [official plugins page](https://github.com/babel-plugins) lists [babel-plugin-object-assign](https://github.com/babel-plugins/babel-plugin-object-assign) as one of the plugins. But that plugin's readme just points to [babel-plugin-transform-object-assign](https://github.com/babel/babel/tree/development/packages/babel-plugin-transform-object-assign) which has instructions to run `npm install babel-plugin-transform-object-assign` but that [isn't a valid npm module](https://www.npmjs.com/search?q=babel-plugin-transform-object-assign).

Edit: removed a separate issue from this text.

**Comment by loganfsmyth** [comment]
@davidgilbertson The Github page tells you where the code has moved to. Things are in a big of flux at the moment because things are being moved around to prep for the next version of Babel.

For now, you should use https://www.npmjs.com/package/babel-plugin-object-assign directly and not worry about Github pages.

If you have other questions, please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by davidgilbertson** [comment]
You may have misunderstood the issue I am describing.

The instructions in the readme say `npm install babel-plugin-transform-object-assign` but this results in an error.

**Comment by loganfsmyth** [comment]
Correct, that is because that code is for Babel 6, as it is on the `development` branch of the babel repo. You will eventually be able to do that, but it has not been released yet.
