### ISSUE TITLE
jsx transformed js but nothing display

### ISSUE THREAD

**Issue by futurist** [babel/babel#2555]
Below code transformed to `.js` but the page display nothing, and no error reported; But `.jsx` file works fine with babel-core/brower.js included

    //<body><div id="content"></div></body>
	var con =  document.querySelector('#content');

	var data = [
	  {author: "Pete Hunt", text: "This is one comment"},
	  {author: "Jordan Walke", text: "This is *another* comment"}
	];

	var CommentList = React.createClass({

		render:function(){
			var comList = this.props.data.map( v=> <Comment title="3" style={{color:'red'}} author={v.author}>{v.text}</Comment> );
			return(<div className="list">It's commentList
				{comList}
				</div>)
		}
	});

	var CommentForm = React.createClass({
		submit:function function_name (e) {
			e.preventDefault();

			var author = this.refs.author.value;
			var text = this.refs.text.value;
			this.props.submit({author:author, text:text});
			this.refs.author.value = '';
			this.refs.text.value = '';
		},
		render:function(){
			return(<div className="form">
				<form className="commentForm" onSubmit={this.submit}>
				<input type="text" placeholder="Your Name" ref="author"/>
				<input type="text" placeholder="Your Comment" ref="text"/>
				<input type="submit" value="OK"/>
				</form>
				</div>)
		}
	});

	var CommentBox = React.createClass(
		{
			getData:function () {
				$.get( this.props.url , data=> {
					this.setState( {data:data} );
				} );
			},
			onsubmit:function  (e) {
				console.log(e);
				//$.post(autho, text);
				this.setState( {data: this.state.data.concat(e) } )

			},
			getInitialState:function(){
				return {data:[]}
			},
			componentDidMount:function function_name () {
				this.getData();

			},
			render:function  () {
				return(
					<div className="box">
					<h1>The List</h1>
					hello world! this is a commentBox<br/>
					<CommentList data={this.state.data}/>
					<CommentForm submit={this.onsubmit} />
					</div>
					);
			}
		}
	);

	var Comment = React.createClass({
		propTypes: {
		    children: React.PropTypes.element.isRequired
		  },
		render:function  () {
			return(<div {...this.props} >
				<h2 {...this.props} className="author">{this.props.author}</h2>
				{this.props.align2} {this.props.children}
				</div>)
		}
	});

	ReactDOM.render( <CommentBox url="data.json" interval="2000" />, con, function finishRender (e) {
		console.log(this);
	} );

**Comment by forivall** [comment]
This probably should be asked in slack first. Also, with long code blocks like this, it's better to use a gist.
