### ISSUE TITLE
isReferenced is false for the left hand of AssignmentExpressions

### ISSUE THREAD

**Issue by sebmarkbage** [babel/babel#2557]
I'm a bit unclear as to what `isReferenced` is meant to do.

I understand that this should return false if I pass `t.isReferenced(theXId, theAssignmentExpression)`.

```js
x = 1;
```

However, shouldn't this return true?

```js
x += 1;
```

Because this is a read.

**Comment by sebmck** [comment]
The scenarios where you'd want to deal with referenced identifiers most of the time involves replacing them. In order to ensure safe transformations, it's safe to replace a referenced identifier with any other type of expression.

**Comment by sebmarkbage** [comment]
Fair enough.

**Comment by sebmarkbage** [comment]
What about `x++`? That's not safe to replace. Why is that different?

**Comment by sebmck** [comment]
That's true. Feel free to reopen. I can definently see the need.

**Comment by sebmck** [comment]
Will need to be queued for v6 since this would break existing transforms in interesting ways.
