### ISSUE TITLE
babel-runtime Class Call Check vs IE10

### ISSUE THREAD

**Issue by dallonf** [babel/babel#2558]
I don't know the cause of the problem, but I know of some easy repro steps:

1. Clone [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate) (Could probably do this with any React + Babel + Webpack project)
2. `npm install`
3. `npm install --save babel-runtime`
4. Add `"optional": ["runtime"]` to `.babelrc`
5. `npm start`, open `localhost:3000` in IE10 or earlier
6. Class Call Check throws

Works fine in IE11, Edge, Chrome, and Firefox. If you dig to the source a bit (IE10 stack traces leave something to be desired), it appears to be coming from rendering a React component class.

**Comment by glued** [comment]
see ie10 in caveats
https://babeljs.io/docs/advanced/caveats/

**Comment by sebmck** [comment]
Do you have a simpler repro?

**Comment by dallonf** [comment]
By "simple", I assume you mean less moving parts rather than less steps? I'll see if I can put together a minimal project later today.

**Comment by dallonf** [comment]
Shoot, turns out this is a problem with the `react-transform` ecosystem. My mistake! I could have sworn I diagnosed this in my app even with react-transform disabled.
