### ISSUE TITLE
Does this support whitespace?

### ISSUE THREAD

**Issue by limeblack** [babel/babel#2559]
Does this support whitespace?

**Comment by sebmck** [comment]
I don't know what this is supposed to mean.

**Comment by sebmck** [comment]
Anyway, this is the wrong place for this. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by limeblack** [comment]
@sebmck Tokenizing of whitespace?  Sorry it wasn't clear.

For example linebreaks.

**Comment by loganfsmyth** [comment]
@limeblack The second comment still applies. Questions are not handled through Github.

**Comment by limeblack** [comment]
@loganfsmyth @sebmck I will be reopening this issue if they are not supported so this is a little silly(being this is a yes or no question).

I do not understand slack Stackoverflow is not the appropriate place for a yes or no question.

Although I am not going to be overly critical it is a very direct question that would be an issue(in my opinion) if they are not supported(which it appears they are not).

**Comment by thejameskyle** [comment]
Tokenizing whitespace doesn't make any sense. If you have more questions, there are plenty of people who are happy to help you over in the slack channel, but again this is not the appropriate place for that as these types of issues make GitHub issues totally unmanageable.
