### ISSUE TITLE
Do you know how to use this polyfill with ie8 polyfill?

### ISSUE THREAD

**Issue by vdzundza** [babel/babel#2562]
Related issue https://github.com/WebReflection/ie8/issues/21
I investigated that babel polyfill check whether get/set methods are in attributes and throws exception. After ie8 polyfill get/set are defined and polyfill throws exception.
So can your delete throwing exception?

**Comment by zloirock** [comment]
`babel` compatible with IE8, but getters / setters can't be polyfilled in ES3. What do ou mean by "delete throwing exception"? That: https://github.com/zloirock/core-js/issues/74, https://github.com/zloirock/core-js/issues/84, https://github.com/zloirock/core-js/issues/119?

**Comment by sebmck** [comment]
This is not the right place for this. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
