### ISSUE TITLE
minification.deadCodeElimination shouldn't put regex literals inside loop conditions

### ISSUE THREAD

**Issue by seangenabe** [babel/babel#2563]
```javascript
babel.transform("var r = /(.)/g; var text = 'abcd'; var x;\n while (x = r.exec(text)) console.log(x[1]);", {
    optional: [ 'minification.deadCodeElimination' ],
    experimental: true
}).code
```

```
'use strict';

var x;
while (x = /(.)/g.exec('abcd')) console.log(x[1]);
```

**Comment by sebmck** [comment]
Why? All modern JS vms have a regex cache.

**Comment by seangenabe** [comment]
I'm not sure I know what you meant about 'regex cache' but people will try to `exec` regex objects and assume they are stateful. `exec` shouldn't be called on literals on loops because it [will reset the `lastIndex` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec). Try running the output above (with caution) and it should be an infinite loop--vs the original loop which should output a b c d.

**Comment by sebmck** [comment]
Oh right ok. The issue had nothing but code snippets so I thought you were referring to the overhead of regex object creation.

**Comment by sebmck** [comment]
The dead code elimination transform has been removed in Babel 6 pending release of a Babel-based minifier.
