### ISSUE TITLE
Function argument destructuring not working in node

### ISSUE THREAD

**Issue by blup** [babel/babel#2564]
I'm using node v4.2 with require('babel/register')(), with and without the experimental flag, and i'm getting 'Unexpected token {' at 'constructor({a, b}) {' . It works fine when i compile through babelify for web though.

**Comment by loganfsmyth** [comment]
A bit more code to reproduce would be good. Do you have any transformations blacklisted?

**Comment by blup** [comment]
Sorry, I missed the note that "requires to node_modules will be ignored", using {ignore: false} works.
