### ISSUE TITLE
Passthrough for currently supported syntax in evergreen browsers

### ISSUE THREAD

**Issue by lyptt** [babel/babel#2567]
As browsers are gradually adding support for the ES6 basics like `let`, `const`, and `class`, would it be possible at some point to allow simply passing through these features instead of transpiling them to ES5?

**Comment by topaxi** [comment]
Might be dangerous as other tooling needs to support ES6 too, linter like jshint, minifier like uglify-js and coverage reporter like istanbul currently don't support ES6 in their stable releases. 

You can however disable each transformer individually with a blacklist.

**Comment by lyptt** [comment]
Looks like blacklists are what I'm after. Thanks!
