### ISSUE TITLE
Invalid number error when parsing octal number

### ISSUE THREAD

**Issue by zhhz** [babel/babel#2569]
I'm using babel-node to load my node app.

Here is an example:

var fs = require('fs');
fs.chmodSync(6479, 0777);

The error occurs when it trying to parse 0777.

**Comment by hzoo** [comment]
I think you mean to put `0o777`?

**Comment by jridgewell** [comment]
That's being interpreted as a legacy octal literal, which is no longer allowed because we have real octals now.

**Comment by zloirock** [comment]
Octal literal without `o` [deprecated](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-additional-syntax-numeric-literals) and not allowed in the strict mode, all `babel` code in the stict mode.

**Comment by loganfsmyth** [comment]
Yup, as the others said, it should be `0o777` in strict mode code.

**Comment by zhhz** [comment]
Thanks guys. That fixes my issue.
