### ISSUE TITLE
export default instantiated object

### ISSUE THREAD

**Issue by heavyk** [babel/babel#2571]
foo.js:
```js
class Foo {
  constructor () {
    this.i = 1
  }
  bar () {}
}
var foo = new Foo;
export default foo;
```

main.js
```js
import { foo } from './foo';

assert.strictEqual(foo.i, 1);
assert.strictEqual(typeof foo.bar, 'function');
```

the first assert passes. the second will not. this is because babel generates for foo.js
```js
'use strict';
Object.defineProperty(exports, '__esModule', {
  value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);

    this.i = 1;
  }

  Foo.prototype.bar = function bar() {};

  return Foo;
})();

var foo = new Foo();
exports.default = foo;
module.exports = exports.default;
```

so, what happens is, in main.js it won't find `__esModule` property so it'll copy the object (the else-statement in `_interopRequireWildcard`).

```js
// expanded for demonstration:
function _interopRequireWildcard(obj) {
  if (obj && obj.__esModule) { return obj; }
  else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj['default'] = obj; return newObj; }
}

var _foo = require('./foo');

var foo = _interopRequireWildcard(_foo);

assert.strictEqual(foo.i, 1);
assert.strictEqual(typeof foo.bar, 'function');
```

so, you can see that `bar` will be defined on `foo` but not on `_foo`.

so, I'm thinking that maybe it it should define the `__esModule` property at the end of the file. it works if I move the defineProperty to the end and change it to define on `module.exports` instead of `exports`

is this a bug? I assumed it would work anyway

**Comment by loganfsmyth** [comment]
Are you on an old version of Babel? Please make sure to update. The example output you gave for `main.js` does not match the current version.

You are exporting a default

    export default foo;

but then trying to import a named export:

    import { foo } from './foo';

you should be doing:

    import  foo from './foo';

This whole process is going to be clearer in Babel version 6, where you'll actually get an error about an invalid import.

**Comment by heavyk** [comment]
```
babel --version
5.8.23 (babel-core 5.8.25)
```

and, you are totally right. I'm very sorry I didn't understand the module system correctly. that makes perfect sense.
