### ISSUE TITLE
ReferenceError: Unknown option: stage

### ISSUE THREAD

**Issue by brenolf** [babel/babel#2572]
It's similar to #1636, but I couldn't get it working. I have a file:

```js
require('babel/register')
require('./config/express')
.listen(process.env.PORT || 3000)
```

My `.babelrc` is as follows:

```json
{
  "stage": 0,
  "loose": ["all"],
  "optional": ["optimisation.flow.forOf", "es7.asyncFunctions"],
  "env": {
    "test": {
      "plugins": [
        "babel-plugin-rewire"
      ]
    }
  }
}
```

When I run `node app` I get 

```
/Users/breno/node_modules/babel/lib/babel/transformation/file.js:91
        throw new ReferenceError("Unknown option: " + key);
        ^

ReferenceError: Unknown option: stage
    at File.normalizeOptions (/Users/breno/node_modules/babel/lib/babel/transformation/file.js:91:15)
    at new File (/Users/breno/node_modules/babel/lib/babel/transformation/file.js:70:22)
    at transform (/Users/breno/node_modules/babel/lib/babel/transformation/index.js:18:14)
    at Object.transformFileSync (/Users/breno/node_modules/babel/lib/babel/api/node.js:73:10)
    at compile (/Users/breno/node_modules/babel/lib/babel/api/register/node.js:73:20)
    at normalLoader (/Users/breno/node_modules/babel/lib/babel/api/register/node.js:119:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/breno/node_modules/babel/lib/babel/api/register/node.js:132:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

It works if I run `babel-node app`, though. Using node 4.2.1 and babel-node 5.8.23.

**Comment by loganfsmyth** [comment]
@brenolf Could you try to put together a repo to reproduce this issue? As it is, I am not able to reproduce this.

**Comment by thejameskyle** [comment]
Stage is now a dead option in Babel 6

**Comment by cly** [comment]
What is the proper way to support this in babel 6 and in earlier versions with the same .babelrc?

**Comment by thejameskyle** [comment]
See the [presets](http://babeljs.io/docs/plugins/#presets) for each stage.

**Comment by digitarald** [comment]
As this is deprecation and probably affects a few developers it really could benefit from a better error message.

**Comment by cly** [comment]
@thejameskyle The problem is in my project I'm using babel 6 and when I try to run webpack with a reference to radium it barfs with:

```
Module build failed: ReferenceError: [BABEL]...Unknown option:....babelrc.stage
```

The error also references babel-core from my projects babel.

**Comment by thejameskyle** [comment]
Please see our README:

> For questions and support please visit the [Slack community](https://babel-slack.herokuapp.com) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

If you have further questions, feel free to ask them in Slack.

**Comment by cly** [comment]
Cool thanks James!

**Comment by thom-nic** [comment]
This seems to be a backward-incompatible change from Babel 5.x to 6, but I can't find any mention of it in the changelog.  In fact, this issue appears to be the only relevant result when I search for that error message.  Nothing on StackOverflow.

Is there a migration guide for Babel 5.x to 6?

**Comment by hzoo** [comment]
Check out slack for more questions - http://babeljs.io/blog/2015/10/31/setting-up-babel-6/

**Comment by thom-nic** [comment]
Thanks @hzoo !  

It also appears that `.babelrc.env.[env].extra` is no longer supported as well...  I will join Slack and ask there.  Unfortunately Slack conversations don't show up in search results!
