### ISSUE TITLE
Update auxiliaryComment in Documentation

### ISSUE THREAD

**Issue by destroyerofbuilds** [babel/babel#2573]
The documentation lists `auxiliaryComment`. However it seems that has been renamed to `auxiliaryCommentBefore`.

```bash
Deprecated option auxiliaryComment: renamed to auxiliaryCommentBefore
```

**Comment by sebmck** [comment]
This is not the right place. Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
