### ISSUE TITLE
Needlessly parenthesizing sequence expressions

### ISSUE THREAD

**Issue by amasad** [babel/babel#2575]
if there is a return with a sequence expression as an argument we're adding parenthesis for no reason:

Example: http://astexplorer.net/#/JgXjdbNWwu

**Comment by thejameskyle** [comment]
Note: this is _only_ when inside of a `ReturnStatement`

**Comment by DmitrySoshnikov** [comment]
What about this?

```javascript
function foo() {
  return ( // bar
    1,
    2
  );
}
```

**Comment by amasad** [comment]
This should be added on a per need basis, not every time
