### ISSUE TITLE
In compact mode, we shouldn't output more semicolons than needed

### ISSUE THREAD

**Issue by amasad** [babel/babel#2576]
Statements at the end of the block body shouldn't have a semicolon

**Comment by loganfsmyth** [comment]
This seems like a minuscule gain at best, and it's something you could already do with a separate minifier. Why bother?

**Comment by sebmck** [comment]
Because we're planning on eventually building a minifier on top of Babel. Raw byte size matters and anything we can do to reduce that is important.

**Comment by loganfsmyth** [comment]
Makes sense. My main concern is that until now `compact` has specifically been whitespace-only change to help performance in the code generator. By adding this by way of "compact", it would be toggled on suddenly when a file passes 100k, and depending on what users are doing with output code, that change in style could suddenly and unexpectedly break someone's workflow.

Not against this at all, but seems like it would need to be clearly documented and potentially the 100k limit should be dropped.

**Comment by amasad** [comment]
I agree that we should make sure that it's documented that compact is compact. The 100k limit needs to be removed once we make the printer more efficient. See #2601

**Comment by amasad** [comment]
closed via #2608
