### ISSUE TITLE
How test that function is generator?

### ISSUE THREAD

**Issue by savelichalex** [babel/babel#2577]
Is there a way to find out that target function is generator? Right now I test it by /regeneratorRuntime/g RegExp.

**Comment by zloirock** [comment]
By spec, `GeneratorFunction.prototype[@@toStringTag] === 'GeneratorFunction'`, so `({}).toString.call(function*(){})` should be `'[object GeneratorFunction]'`. [`core-js` adds `@@toStringTag` logic](https://github.com/zloirock/core-js#ecmascript-6-object), but `regenerator` does not set tag.

@benjamn can you add it? (and `'Generator'` to `Generator.prototype`)

**Comment by savelichalex** [comment]
How I understand babel use polifill to generators and it compile to function wich use `regeneratorRuntime` object. `Object.prototype.call(function* () {})` return `[object Function]`. And it's right, it's plain function which return `regeneratorRuntime.which(function...)`. But how test that function is generator? I think that test by RegExp is unreliably.

**Comment by zloirock** [comment]
@savelichalex [you can add in manually](https://goo.gl/N5OtKi), but it will work in IE10-.

**Comment by savelichalex** [comment]
@zloirock Thanks, nice decision! I cirrectly understand that it limited by Symbol realization?

**Comment by zloirock** [comment]
@savelichalex it's limited `Object.setPrototypeOf` / `__proto__` used in the `regenerator`. `core-js` `Symbol` shim should work enough correct anywhere (in IE8- with serious limitation).

**Comment by savelichalex** [comment]
It means that `regenerator` work in IE10-?

**Comment by zloirock** [comment]
@savelichalex sorry, was typo - missed "not" :) In IE10- `regenerator` generators propotype is `Function.prototype`, not `GeneratorFunction.prototype`.

**Comment by savelichalex** [comment]
@zloirock thanks!

**Comment by zloirock** [comment]
Should be available out of the box in `regenerator` `0.8.42` in all engines.
