### ISSUE TITLE
ignore and experimental options

### ISSUE THREAD

**Issue by mathieudutour** [babel/babel#2578]
With the options
```
require('babel/register')({
  ignore: /node_modules\/(?!common)/,
  stage: 0,
  optional: ['runtime'],
});
```
, files in the common directory (in node_modules) are indeed parsed by babel. However, they are not parsed with the `stage 0` option.

Funny thing, when developing, the common directory is only symlink inside node_modules and babel is behaving perfectly fine (with the `stage 0` option). On prod, the common directory is copied inside node_modules. That's when babel is "breaking".

**Comment by sebmck** [comment]
This isn't the right place. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by mathieudutour** [comment]
Well I believe it's a bug.
Babel should parse all the files not ignored (ok) and use the `stage` option with all of them (not ok).
