### ISSUE TITLE
CLI --ignore doesn't actually take regex

### ISSUE THREAD

**Issue by hatched** [babel/babel#2580]
According to https://babeljs.io/docs/usage/cli/ I should be able to:

```MakeFile
$(NODE_MODULES)/.bin/babel $(GUISRC)/app --out-dir $(GUIBUILD)/app \
	--ignore /assets/javascripts/.*.js
```

But it still tries to parse: `/static/gui/src/app/assets/javascripts/d3-wrapper-end.js`

Instead I have to modify the `--ignore` to:

```
--ignore /assets/javascripts/
```

Because of this it also appears that I'm not able to exclude multiple directories using the regex.

**Comment by sebmck** [comment]
Yep, the docs need to be updated. It takes a glob. This is not the right place for this anyway. Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by hatched** [comment]
Ahh sorry about that, I figured it was a code bug not a doc bug :) I'll file over there.
