### ISSUE TITLE
Preserve indentation in retainLines

### ISSUE THREAD

**Issue by spicyj** [babel/babel#2582]
When using retainLines at FB: debugging with the left (Chrome Sources panel) and right (vim in my terminal) views is a night-and-day difference.

![image](https://cloud.githubusercontent.com/assets/6820/10703840/a5974734-7987-11e5-9c9c-f38c86808d7b.png)

@sebmck says that comments should already be preserved and we can reenable that option but we can probably preserve indentation too after Babel 6 with not too much work.

**Comment by sebmck** [comment]
Looks like I already did this in the `development` branch due out for 6.0. We're hopefully to get roll out Babel 6 FB-wide ASAP. cc @DmitrySoshnikov.

**Comment by spicyj** [comment]
Nice, thank you!
