### ISSUE TITLE
function expressions are printed with names

### ISSUE THREAD

**Issue by amasad** [babel/babel#2583]
Example: http://astexplorer.net/#/9whV1Kbxsw

**Comment by thejameskyle** [comment]
Doesn't this have to do with the way `function.name` is set now?

**Comment by amasad** [comment]
Not sure if there something new. But AFAICT it shouldn't magically gain a name when a printing if it was nameless.

**Comment by amasad** [comment]
(also I'm worried about byte size :3)

**Comment by loganfsmyth** [comment]
Yeah, this is an ES6 feature. Function expressions that don't have names pick up names from the identifiers they are originally assigned to. I have a writeup here with spec links: http://stackoverflow.com/a/32830772/785065

**Comment by amasad** [comment]
Should be a transform not a printer feature though?

**Comment by loganfsmyth** [comment]
Yeah, I don't know where that logic is in 5.x. I've seen that https://github.com/babel/babel/tree/development/packages/babel-plugin-transform-es2015-function-name exists on `development` but @sebmck will have to answer if that's actually happening.

**Comment by sebmck** [comment]
@amasad AST explorer runs the code through all the Babel transforms. The transform that adds the inferred function names is [here](https://github.com/babel/babel/blob/master/packages/babel/src/transformation/transformers/spec/function-name.js). You can disable it with `--blacklist spec.functionName`.
