### ISSUE TITLE
_interopExportWildcard not working against ES Modules

### ISSUE THREAD

**Issue by guybedford** [babel/babel#2585]
When running code compiled from ES modules into CommonJS, it runs absolutely fine against real ES modules as in accordance with basic interop.

There is an issue though when running `export * from 'module'` that has been compiled into CommonJS as this uses the `_interopExportWildcard` function. If the object we're exporting from is a `Module` namespace instance as it is in SystemJS, its exports are not configurable, which fails the `configurable` check in the defaults function https://github.com/babel/babel/blob/master/packages/babel/src/transformation/templates/helper-defaults.js#L6 called by `_interopExportWildcard`. Thus, no exports get defined at all by this function.

Let me know if that is unclear at all. Related issue is https://github.com/systemjs/systemjs/issues/858.

**Comment by tanob** [comment]
I just bumped into this same issue, here's the original code:

```js
// helpers.js
import { intlShape, injectIntl } from 'react-intl';
export { defineMessages } from 'react-intl';
```

I'm using babel with webpack, the generated code looks like this:

```js
var _reactIntl = __webpack_require__(229);

Object.defineProperty(exports, 'defineMessages', {
  enumerable: true,
  get: function get() {
    return _reactIntl.defineMessages;
  }
});
```

In another module I do `export * from './helpers'` and when trying to use `defineMessages` from it the browser complains that `defineMessages` is not there.

I got it working by importing with a different name and then exporting:

```js
import { intlShape, injectIntl, defineMessages as _defineMessages } from 'react-intl';
export const defineMessages = _defineMessages;
```

Which generates the following:

```js
var _reactIntl = __webpack_require__(229);

var defineMessages = _reactIntl.defineMessages;

exports.defineMessages = defineMessages;
```

**Comment by loganfsmyth** [comment]
It's not immediately obvious to me why the `configurable` check is in there. Given https://github.com/babel/babel/issues/2436 this shouldn't be using `_defaults` anyway, so that point may be moot.

**Comment by hzoo** [comment]
is this still an issue?

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
