### ISSUE TITLE
Ignore imports by file extension

### ISSUE THREAD

**Issue by DominicTobias** [babel/babel#2589]
Hi,

It seems that with the advent of webpack loaders you can import things like css and take advantage of hot-reloading (as well as declaring it as a dependency for builds). However when making an isomorphic app and using `babel/register`, these imports throw an exception.

A common use case would be including an isomorphic router:

```js
Router.js > Routes.js > App/Home/About.js // Have things like import './Home.scss'
```

Is there a way of making Babel ignore certain file extensions? I couldn't get options like `only` to work for glob matching and nobody on SO seems to know the answer either, I would have thought this was a fairly common problem?

Thanks

**Comment by sebmck** [comment]
Babel doesn't handle module loading and dependency management. `babel/register` just overloads `require.extensions`. I'd recommend checking out [Backend Apps with Webpack](http://jlongster.com/Backend-Apps-with-Webpack--Part-I) by @jlongster if you're interested in this.

**Comment by DominicTobias** [comment]
@sebmck thanks will take a look
