### ISSUE TITLE
JSX ASI handling

### ISSUE THREAD

**Issue by natew** [babel/babel#2591]
Given this:

```js
function x() {
  <div />
}
```

compiles to (or some equivalent):

```js
function x() {
  React.createClass({})
}
```

I would expect this:

```js
function x() {
  let x
  <div />
}
```

Which gives an error, would be valid, assuming JSX works with ASI:

```js
function x() {
  let x
  React.createClass({})
}
```

Mostly curious why, as it seems to deviate from JS here a bit.

**Comment by azimgd** [comment]
Adding semicolon will solve the issue.
```
function x() {
  let x;
  <div />
}
```

**Comment by thejameskyle** [comment]
Yup, imagine it without the insignificant whitespace. This is invalid syntax:

```js
function x() {
  let x <div />
}
```

Also:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by natew** [comment]
Isn't it only invalid because we decide it though? Just wondering, wouldn't with ASI that be:

```js
function x() {
  let x;<div />
}
```

Edit: seeing that this should be on Slack. Though it seems a bad place to keep discussions, as they aren't easy to reference/search, and stackoverflow is not usually for discussing requests/features.

**Comment by sebmck** [comment]
Reopening until I can post a response/explanation/justification/whatever. I'll look into the stack trace on why it's invalid.

**Comment by jmm** [comment]
@azimgd He knows :)

@thejameskyle The `LineTerminator` *is* significant for ASI though isn't it? I'll be curious to see what @sebmck replies with too.

**Comment by sebmck** [comment]
The problem is that we're tokenising the `<` as a relational operator rather than the start of a JSX tag since we don't check that after tokenising `x` that we could allow an expression. Similarly we disallow:

```javascript
function x() {
  let x
  /wow/;
}
```

**Comment by natew** [comment]
@sebmck thanks!
