### ISSUE TITLE
Babel is trying to reach the parent frame causing a security error

### ISSUE THREAD

**Issue by oskarkrawczyk** [babel/babel#2593]
Hi,

We've added Babel to @jsfiddle some time ago, but with the latest Chrome update everyone started getting a security error:

```
Uncaught SecurityError: Failed to read the 'frame' property from 'Window': Blocked a frame with origin "http://fiddle.jshell.net" from accessing a frame with origin "http://jsfiddle.net". Protocols, domains, and ports must match.
```

Obviously we're rendering fiddles on a different domain for security reasons.

The block causing the problem:

```javascript
var hasAutomationEqualityBug = (function () {
	/* global window */
	if (typeof window === 'undefined') { return false; }
	for (var k in window) {
		if (!blacklistedKeys['$' + k] && has.call(window, k) && window[k] !== null && typeof window[k] === 'object') {
			try {
				equalsConstructorPrototype(window[k]);
			} catch (e) {
				return true;
			}
		}
	}
	return false;
}());
```

The exact line `!blacklistedKeys['$' + k] && has.call(window, k) && window[k] !== null && typeof window[k] === 'object'`

Is this a known issue? Any ideas how to patch this up?

Thanks!

**Comment by bloodyowl** [comment]
I think the issue should be in es5-shim https://github.com/es-shims/es5-shim/blob/bee855401c5d5f7e1d3db6aabbd671a5ce37396b/es5-shim.js#L855

**Comment by oskarkrawczyk** [comment]
@bloodyowl Thanks. Updated to the latest from babel-core and all seems to be working fine again. 

I'll go ahead and close this.
