### ISSUE TITLE
Async functions are at Stage 3

### ISSUE THREAD

**Issue by impinball** [babel/babel#2594]
[Relevant tc39/ecma262 commit.](https://github.com/tc39/ecma262/commit/2fa3ca4bbc8e9feece0cce363b076a1942e8c6ba)

Relevant here and on the website.

**Comment by loganfsmyth** [comment]
They are in v5.8.29: https://github.com/babel/babel/blob/master/packages/babel/src/transformation/transformers/es7/async-functions.js#L2

Website issues are tracked separately: https://github.com/babel/babel.github.io/pull/452
