### ISSUE TITLE
babel-runtime, I want to get core-js Object which has a thing of the minimum required

### ISSUE THREAD

**Issue by petamoriken** [babel/babel#2595]
When I use `babel-runtime`, I want to get `ponyfill` that my JavaScript code uses.

	// only use Promise and Symbol
	new Promise(function(resolve, reject) {
		// ...
	});
	let foo = Symbol("foo");

	import core from "babel-runtime/core-js";
	console.log(core);
	/* ->
		{
			Array: Object,
			Date: Object,
			Dict: function Dict(iterable),
			Function: Object
			... ( other 24 property )
		}
	*/

In this code `core-js` Object has all of `ponyfill` Object, can I get like below?

	{
		Array: Object,
		JSON: Object,
		Object: Object,
		Promise: function Promise(),
		... ( other 4 property )
	}

**Comment by zloirock** [comment]
You can add `core-js` as dependency to your project and use [commonjs api](https://github.com/zloirock/core-js#commonjs), `babel-runtime` uses the same.
