### ISSUE TITLE
Error when requiring babel-core in Webpack

### ISSUE THREAD

**Issue by munrocape** [babel/babel#2598]
I'd like to use the .transform method of the browser. When I attempt to import this, and the file is in turn processed by babel-loader, I get a bunch of errors.

[Here is the list of errors](https://gist.github.com/munrocape/fc2df28a7a3d0efa5f8c)

[Here are my package.json dependencies](https://gist.github.com/munrocape/4f2a2ce1bb48bb58aaba)

I saw [this issue](https://github.com/babel/babel/issues/1389) which seems very similar. However, I have tried updating to the most recent versions of babel-* to no avail.

**Comment by loganfsmyth** [comment]
@munrocape As that issue says, you'll need to do

    require('babel-core/browser');

and have

    module: {
        noParse: [
            /babel-core\/browser/
        ]
    }

in your webpack config.

As our README says:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

so I'm going to close this. If you have any further questions, please feel free to come ask on Slack, as you will get much quicker responses there.
