### ISSUE TITLE
Make Code Generation on Large Packages Faster

### ISSUE THREAD

**Issue by sebmarkbage** [babel/babel#2601]
This isn't super important but should be fixable. Large files can only be printed in compact mode (and even then it is pretty slow) because it is exponentially slower on large files.

When you do crazy experiments, like I do, then preserving source maps isn't always an option so pretty printing is nice for debugging the output. Even with source maps you often want to debug the output.

My current work around is to print using compact mode and then pipe it through `js-beautify` which is incredibly fast even on huge bundles.

**Comment by sebmck** [comment]
Yeah, we really need to work on the performance of the code generator. It does a lot of look behinds which are pretty expensive in places and it grows exponentially the longer the buffer. We'll need to do this if we plan to tackle an auto formatter in the future. cc @babel/facebook.

**Comment by amasad** [comment]
js-beautify is mind-numbingly fast.
Btw, I didn't get the notification for "cc @babel/facebook"

**Comment by sebmck** [comment]
> Btw, I didn't get the notification for "cc @babel/facebook"

You hadn't accepted the org invite when I commented.

**Comment by amasad** [comment]
ah, I just saw the invite.

**Comment by danez** [comment]
This is probably resolved now that logan did the massive refactoring of the generator.
