### ISSUE TITLE
Support for concise async generators

### ISSUE THREAD

**Issue by ruby-random** [babel/babel#2603]
Following code snippets should compile:

    class Query {
        async *queryAll(ids) {
            for (const id of ids) {
                yield await this.query(id);
            }
        }
    }
    
    const query = {
        async *queryAll(ids) {
            for (const id of ids) {
                yield await this.query(id);
            }
        }
    };

Now these are syntax errors, however full form is not:

    async function *queryAll(ids) {
        for (const id of ids) {
            yield await query(id);
        }
    }

**Comment by phpnode** [comment]
The last of your examples does compile but it didn't seem to actually work during my tests. Is this specced behaviour?
