### ISSUE TITLE
load events for script tag (browser mode)

### ISSUE THREAD

**Issue by quadroid** [babel/babel#2604]
onload, onreadystatechange and onerror events doesn't fired for scripts loaded by babel.

**Comment by sebmck** [comment]
Code/steps to reproduce please.

**Comment by loganfsmyth** [comment]
Is there an expectation that they would? Since the browser doesn't make any attempt to fetch scripts that have an unknown `type` attribute, the browser would not fire them, so Babel would have to synthetically dispatch them.

**Comment by quadroid** [comment]
@loganfsmyth yes, but when I change known type (text/javascript) to unknown (text/babel), default behaviour is broken, and code that worked earlier doesn't work now.
In my case, ExtJS loader doesn't work.

**Comment by quadroid** [comment]
Here is simple steps to reproduce:
```
<script type="text/babel" src="/" onload="alert('loaded')" onerror="alert('error')"></script>
```

**Comment by thejameskyle** [comment]
I don't think this is worth solving. It's a bad idea to compile in the browser this way.
