### ISSUE TITLE
Enumerable getter descriptors are not enumerable on the instance

### ISSUE THREAD

**Issue by jaap3** [babel/babel#2610]
I'm trying to make certain getters on a class instance enumerable, but am unable to get it to work. Using a decorator to set the enumerable property of a descriptor results in the getter being enumerable on the prototype, but not on the instance.

```javascript
function enumerable(cls, fname, descriptor) {
    descriptor.enumerable = true;
    return descriptor;
}

class Person {
    constructor(firstName, lastName) {
        this.firstName = firstName
        this.lastName = lastName
    }

    happy = true

    @enumerable
    get fullName() {
        return `${this.firstName} ${this.lastName}`
    }
}

console.log(Object.keys(new Person('John', 'Smith')))
// expected: [ 'happy', 'fullName', 'firstName', 'lastName' ]
// actual: [ 'happy', 'firstName', 'lastName' ]


console.log(Object.keys(Person.prototype))
// expected: []
// actual: [ 'fullName' ]
```

I'm unsure if this is correct according to the specs, but it's certainly unexpected.

**Comment by loganfsmyth** [comment]
This is the expected behavior. All method-style properties, even getters and setters, live on the class prototype, whether they are enumerable or not doesn't play into it. Only class properties live on the instance because they are evaluated at instantiation time rather than declaration time.

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by jaap3** [comment]
Can you point me to a spec where this behaviour is described? It seems very counterintuitive and makes it nearly impossible to implement custom getters/setters for instances. Feels almost like a language bug.

Should custom getters/setters always be defined in the constructor?

**Comment by loganfsmyth** [comment]
[14.5.14 step 21](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation) calls [`PropertyDefinitionEvaluation`](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation) with `Person.prototype` and `false`.

If you want an 'own' getter that is enumerable, you'd have to do it yourself. You haven't really said why you need it to be enumerable though, so it is hard to give you more info.

**Comment by jaap3** [comment]
My basic use case is that I want to change a simple field to a getter property and have downstream code serialize the object in the same way as it did previously.

**Comment by fkling** [comment]
If you want the define a property on the instance, you have to do it in the constructor.

**Comment by fkling** [comment]
> Should custom getters/setters always be defined in the constructor?

Only if you need them to be on the instance itself. But that was always the case, even before `class`es.

**Comment by zloirock** [comment]
@loganfsmyth it's ES6 logic, I think it should be changed after adding decorators. Proposal hasn't any spec text, but with desugaring examples it should be enumerable.

**Comment by loganfsmyth** [comment]
@zloirock Not sure I follow what you mean. This code will properly make it enumerable, but the act of decorating a property should not move it from being attached to a prototype to being attached to an instance.

**Comment by zloirock** [comment]
@loganfsmyth I mean step `14.5.14 step 21` with `false` that you mentioned. Sure, it's not related own properties and this issue.

**Comment by jaap3** [comment]
Just to reiterate the basic use case (and this is loosley based on what @wycats wrote in his high level explanation of decorators.

We start out with a simple class

```javascript
class Person {
    fullName = null
}

console.log(Object.keys(new Person()))
// [ 'fullName' ] expected / actual
```

Now we decide we want fullName to be a property, but have the instance behave exactly the same as before:

```javascript
function enumerable(cls, fname, descriptor) {
    descriptor.enumerable = true;
    return descriptor;
}

function nonenumerable(cls, fname, descriptor) {
    descriptor.enumerable = false;
    return descriptor;
}

class Person {
    @nonenumerable
    firstName = null

    @nonenumerable
    lastName = null

    @enumerable
    get fullName() {
        return `${this.firstName} ${this.lastName}`
    }
    set fullName(value) {
      let [first, last] = val.split(' ');
      this.firstName = first
      this.lastName = last
    }
}

console.log(Object.keys(new Person()))
// [ 'fullName' ] expected 
// [] actual
```

Surely you'll agree that's not the expected behaviour. If this is correct according the the specs I hope there's still a possibility it will be altered.

**Comment by loganfsmyth** [comment]
@jaap3 The only way to declaratively add something to an instance rather than a prototype is to use class properties, which you are already doing and are _not_ part of ES6. The ES6 class has no concept of declarative `own` properties on classes.

I'm not against the possibility, but the spec definitely isn't going to change here. If you wanted a declarative way to define `own` getters, that'd have to be a whole separate proposal with a new syntax for it.

**Comment by jaap3** [comment]
Decorators are not part of ES6 either, that's what makes this interesting :)

**Comment by jaap3** [comment]
@loganfsmyth you comment made me think of a possible method using class properties and a simple decorator. Sadly it doesn't work, but should it?

```javascript
function property(cls, fname, descriptor) {
    let accessors = descriptor.initializer()
    delete descriptor.initializer
    delete descriptor.writable
    descriptor.get = accessors.get
    descriptor.set = accessors.set
    descriptor.enumerable = true
    return descriptor
}

class Person {
    firstName = null
    lastName = null

    @property
    fullName = {
      get() {
        return `${this.firstName} ${this.lastName}`
      },

      set(value) {
        let [first, last] = value.split(' ')
        this.firstName = first
        this.lastName = last
      }
    }
}
```
