### ISSUE TITLE
Babel adds tabs to template literals when `es6.templateLiterals` is disabled

### ISSUE THREAD

**Issue by moretti** [babel/babel#2613]
For example, the following code:

```
function greeter() {
  return `Hello
${'world'}`;
}
```

is transpiled to:

```
'use strict';

function greeter() {
  return `Hello
  ${ 'world' }`;
}
```

**Comment by sebmck** [comment]
I can't reproduce this. There are tests to catch this and they all pass successfully. Please provide steps to reproduce beyond just input code such as options, integration etc.

**Comment by moretti** [comment]
I can reproduce the issue from the command line by running the example below:

`greeter.js`
```
function greeter() {
  return `Hello
${'world'}`;
}
```

babel 5
```
$ babel --version
5.8.29 (babel-core 5.8.33)
$ babel -b es6.templateLiterals greeter.js
'use strict';

function greeter() {
  return `Hello
  ${ 'world' }`;
}
```

babel 6
```
$ babel --version
6.1.1 (babel-core 6.0.20)
$ babel greeter.js
function greeter() {
  return `Hello
  ${ 'world' }`;
}
```

I can have a look at the tests and see why they do not catch the issue.

**Comment by moretti** [comment]
I've added some fixtures to `babel-generator` to reproduce the issue:
https://github.com/moretti/babel/commit/f5bbd09b49fd688e6b9411db753dabf1d7b34b84
and I've temporarily fixed the problem by inlining template strings:
https://github.com/moretti/babel/commit/232bf76b4d90791030105565129cffe8a690478f

Not sure if it is the right way, though.

**Comment by sebmck** [comment]
@moretti Ah right. That's definently the cause. Thanks for looking into it. That is indeed the right fix. Mind sending a PR?

**Comment by moretti** [comment]
Glad to help, PR submitted! :smile:
