### ISSUE TITLE
Regression: scope.getBinding should return function node

### ISSUE THREAD

**Issue by amasad** [babel/babel#2615]
Previously (as recent as 5.8.25) `scope.getBinding(name)` on a reference to a function returned the function node. Now (5.8.30) it returns the identifier node in the function declaration. Here is an example in ast explorer that works:

http://astexplorer.net/#/GGUQK5Y1DZ/1

**Comment by sebmck** [comment]
Fixed in the latest.

**Comment by amasad** [comment]
back in babel 6
