### ISSUE TITLE
Parse errors from valid javascript

### ISSUE THREAD

**Issue by prekolna** [babel/babel#2616]
As part of our build, we perform a Babel transform of a patched, minified third-party dependency, [chart.js](http://www.chartjs.org/) (it's pretty gnarly; I've [pasted the patched version](http://pastebin.com/M4ePFjc2) for reference)
Version 5.8.30 is throwing the error `Parse error. primary expression expected`, but v5.8.29 runs just fine.  The error is at 11:14674, which is the `a` in `var e=this.chart.data.datasets[t._datasetIndex],a=t._index;`, which seems fine to me, so I suspect the changes to parentheses handling for expressions in 5.8.30 broke this.

**Comment by sebmck** [comment]
cc @amasad

**Comment by thejameskyle** [comment]
Unable to reproduce: https://github.com/thejameskyle/__babel-bug-2616

@prekolna If you can fork that repo and reproduce it we can open this up again
