### ISSUE TITLE
Regression: scope.getBinding reports the wrong kind

### ISSUE THREAD

**Issue by amasad** [babel/babel#2617]
Previously (as recent as 5.8.25)  `scope.getBinding` would report kind `param` on `a` in the following example:
```
x(function y(a,b) {})
```
http://astexplorer.net/#/GGUQK5Y1DZ/3

In 5.8.30 I'm getting local on `a` in the example above.

**Comment by amasad** [comment]
Also `binding.path.node` is null o.O

**Comment by andrewimm** [comment]
I'm trying to track down a similar `binding.path.node` regression from *.25 to *.30.

When traversing a `ReferencedIdentifier` for a function call, `binding.path.node` used to be a `FunctionDeclaration`, but in .30 it is now that function declaration's `id` prop.

**Comment by amasad** [comment]
might be 0b71625440b247465f1ff981720782ac55ae69d1?

**Comment by sebmck** [comment]
Fixed in 5.8.31.

**Comment by sebmck** [comment]
Fixed the second issue in 5.8.32
