### ISSUE TITLE
babel-node cache to disk

### ISSUE THREAD

**Issue by mnpenner** [babel/babel#2618]
[The docs](https://babeljs.io/docs/usage/cli/#babel-node) say babel-node "... is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly."

Can babel-node be made to cache the compiled files to disk? This would reduce restart time during development. There's no need to recompile *all* my source files if I only edit one of them.

**Comment by sebmck** [comment]
It does cache your compiled files to disk, but it also stores it in memory.
