### ISSUE TITLE
Reference Error: 'Symbol' is undefined in IE whilst using for...of

### ISSUE THREAD

**Issue by celikmus** [babel/babel#2619]
I'm on 5.8.23 (babel-core 5.8.25), and getting the following error for for..of on IE9 and IE11. Haven't tested on IE10.
<pre>ReferenceError: 'Symbol' is undefined</pre>

**Comment by loganfsmyth** [comment]
Duplicate of #1913 #1825 #1679 #1574.

You need to load a polyfill.
