### ISSUE TITLE
runtime in webpack

### ISSUE THREAD

**Issue by 3LOK** [babel/babel#2623]
Hi,

I have a library called LIB. LIB uses Promises. LIB compiles using webpack and babel to ensure anyone can use it.

I have a project call PROJECT. PROJECT also compiles using wbepack and babel to work on browsers.

When using babel-polyfill in LIB - and opening the PROJECT file - everything seems to work, just the LIB webpack'ed file grows from 7K to 212K.

When using babel-runtime in LIB and opening the PROJECT file - everything works in Chrome, Firefox, IE11 but I get the following error IN SAFARI ONLY (mobile & web):

```
TypeError: __webpack_require__(67) is not a function. (In '__webpack_require__(67)(function (iter) {
  _Array$from(iter);
})', '__webpack_require__(67)' is an instance of Object)
```

The error seems to come from es6.array.from.js, with the following:

```
var _Array$from = __webpack_require__(68)['default'];

var ctx = __webpack_require__(40),
    $def = __webpack_require__(17),
    toObject = __webpack_require__(71),
    call = __webpack_require__(47),
    isArrayIter = __webpack_require__(48),
    toLength = __webpack_require__(49),
    getIterFn = __webpack_require__(50);
$def($def.S + $def.F * !__webpack_require__(67)(function (iter) {
  _Array$from(iter);
}), 'Array', {
...
  }
});
```

Help?

**Comment by zloirock** [comment]
> When using babel-polyfill in LIB - and opening the PROJECT file - everything seems to work, just the LIB webpack'ed file grows from 7K to 212K.

You didn't use compression? Minified it should be ~50kb, gzipped ~20kb. And, sure, you can add only needed features by [commonjs `core-js` API](https://github.com/zloirock/core-js#commonjs).

> When using babel-runtime in LIB and opening the PROJECT file - everything works in Chrome, Firefox, IE11 but I get the following error IN SAFARI ONLY (mobile & web)

Looks on your example - `babel` not ignores `babel-runtime`, but should do it.
