### ISSUE TITLE
Error when "npm install --global babel-cli'

### ISSUE THREAD

**Issue by bgnorlov** [babel/babel#2625]
I just tried to install bable-cli and got the following error:

npm install --global babel-cli
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "install" "--global" "babel-cli"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/babel-polyfill
npm ERR! 404 
npm ERR! 404 'babel-polyfill' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'babel-cli'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by loganfsmyth** [comment]
https://twitter.com/sebmck/status/659794068541734912

> 6.0 release is broken. Turns out live stage releases aren't such a good idea. Fixing now.

**Comment by loganfsmyth** [comment]
Should work fine now.
