### ISSUE TITLE
babel-preset-stage-x

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2626]
Since the `stage` option has gone way of the dodo, it might be nice to maintain official `babel-preset-stage-x` presets.

**Comment by andrelima** [comment]
Indeed!

**Comment by hzoo** [comment]
Sounds good to me

**Comment by hzoo** [comment]
So `babel-preset-stage-0` would require `babel-preset-stage-1`, 2, 3 etc?

**Comment by thejameskyle** [comment]
I imagine they would depend on each other.

**Comment by hzoo** [comment]
How would that work?

something like 
```js
module.exports = {
  presets: [
    require("babel-preset-stage-3")
  ],
  plugins: [
    require("babel-plugin-syntax-object-rest-spread"),
    require("babel-plugin-syntax-trailing-function-commas"),
    require("babel-plugin-transform-object-rest-spread")
  ]
};
```

or

```js
var stage3 = require("babel-preset-stage-3").plugins;

module.exports = {
  plugins: [
    require("babel-plugin-syntax-object-rest-spread"),
    require("babel-plugin-syntax-trailing-function-commas"),
    require("babel-plugin-transform-object-rest-spread")
  ].concat(stage3)
};
```

**Comment by thejameskyle** [comment]
presets can consume presets https://github.com/babel/babel/blob/0b88a89b87b18bddecbd9f6eae9eaa993e86bf1e/packages/babel-core/src/transformation/file/options/option-manager.js#L220

**Comment by hzoo** [comment]
Ok have a pr

**Comment by hzoo** [comment]
Can close this after npm publish since files/docs are in now.

**Comment by justinfagnani** [comment]
Did these get published? Installation is failing

**Comment by hzoo** [comment]
Not yet

**Comment by mfrye-intuit** [comment]
I really appreciate you guys working on this, but in the future it would be nice if if you could publish stuff before you announce it.  I just installed babel for a new project and I didn't realize a new version got released. I'm kind of blocked until this gets merged.

**Comment by loganfsmyth** [comment]
@mfrye-intuit There's nothing stopping you from still using v5 if you are having issues. This preset wasn't even part of the announcement. You can enable the features you want perfectly fine now, this is just a nicer way to do it.

**Comment by sebmck** [comment]
Published. The documentation PR was merged before I published the packages though which has resulted in this confusion.
