### ISSUE TITLE
CLI won't compile

### ISSUE THREAD

**Issue by greim** [babel/babel#2627]
Did the CLI have a breaking change as of 6.0? In 5.x this works:

```bash
$ babel my-es6-code.js
...outputs es5 code...
```

But 6.x seems to behave just like the `cat` command:

```bash
$ babel my-es6-code.js
...output still contains es6 code...
```

**Comment by thejameskyle** [comment]
http://babeljs.io/blog/2015/10/29/6.0.0/#opt-in-plugins

You need to specify your transforms.

**Comment by greim** [comment]
Are there any official docs for this, besides checking the blog?

**Comment by thejameskyle** [comment]
Working on it

**Comment by greim** [comment]
Ah, thanks!

**Comment by jhovgaard** [comment]
First time babel user here. Wasn't able to follow the "usage guide". Fortunately I found this issue. I think this "issue" is critical.
