### ISSUE TITLE
Is async PropertyDefinition valid syntax?

### ISSUE THREAD

**Issue by spket** [babel/babel#2629]
async function/method still in draft, I'm not sure it's babel or Spec issue for following code

```javascript
var o = {
  async a,
  async b : function() {},
  async c() {}
}
```
babel does not report any error

**Comment by loganfsmyth** [comment]
It would be `b: async function() {},`. That said, `async a,` doesn't make sense and is probably a bug so we should leave this open

**Comment by zloirock** [comment]
```js
var o = {
  async c() {}
}
```
[valid](http://tc39.github.io/ecmascript-asyncawait/#async-methods).

**Comment by sebmck** [comment]
It's not clear to me what the first would even do. Closing this as not allowing the first two is indeed expected behaviour and is to the specification. Please refer to the proposal grammar.

**Comment by thejameskyle** [comment]
@sebmck I think the issue as those are all invalid and apparently aren't throwing errors.

**Comment by sebmck** [comment]
Oh, that's a problem then...
