### ISSUE TITLE
6.0: Object rest destructuring in arrow-function params no longer work

### ISSUE THREAD

**Issue by joshq00** [babel/babel#2631]
**test-spread.js**
```es6
export default ( arg ) => {
	let { title, ...other } = arg;
	// do something
};
```
works fine

======

**test-fn-spread.js**
```es6
export default ( { title, ...other } ) => {
	// do something
};
```
fails with the output
```
SyntaxError: test-fn-spread.js: Binding rvalue (1:26)
> 1 | export default ( { title, ...other } ) => {
    |                           ^
  2 | 	// do something
  3 | };
```

**Comment by joshq00** [comment]
This also works:
```es6
export default ( { title }, ...args ) => {};
```

**Comment by toxickg** [comment]
@joshq00, did you install [babel-plugin-transform-es2015-spread](babel-plugin-transform-es2015-spread) or [babel-preset-es2015](https://www.npmjs.com/package/babel-preset-es2015) packages? Starting from version 6.0.0 Babel doesn't transpile ES2015 code by default, you need to include plugins that are required by your app.

**Comment by joshq00** [comment]
Yes. I have everything set up properly (as you can see above I'm successfully using arrow functions and spread and destructuring)

It's specifically when doing `{ ...opts }` in the function params

**Comment by sebmck** [comment]
This is object rest spread. Use [babel-plugin-transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread). In the future, please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.  The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by loganfsmyth** [comment]
I think is is an actual issue with arrow functions and object-rest-spread

    // Works
    var val = function({one, ...two}){};

    // SyntaxError: tmp.js: Binding rvalue (4:17)
    var val = ({one, ...two}) => {};

**Comment by joshq00** [comment]
yes, @sebmck, my first example shows that my configuration **has** object rest spread functioning properly. Again: it's specifically for function params.

@loganfsmyth, you're right. I just checked with my configuration and `function ( { a, ...xyz } )` also works

**Comment by matthiasak** [comment]
I had a similar issue @joshq00 @loganfsmyth:

```js
SyntaxError: /Users/matthiasak/Github Projects/rentvillas/js/state.js: Binding rvalue (214:51)
  212 |         SEARCH: resource({
  213 |             name: 'search',
> 214 |             get: ({id, sort, page, pageSize, hash, ...extraQueryParams}) =>
```

If you need a workaround for now, the array rest spread is a good replacement:

```js
get: (...args) => {
    let [id, sort, page, pageSize, hash, ...extraQueryParams] = args
    ...
},
```

**Comment by fundon** [comment]
Same issue:

```js

export default class Database {

  constructor({ dialect, driver, dsn, logger }) {

    this.dialect = dialect
    this.driver = driver
    this.dsn = dsn
    this.logger = logger

    Object.defineProperty(this.driver, 'db', {
      configurable: true,
      enumerable: false,
      writable: true,
      value: this
    })
  }

}

```

**Comment by quirinpa** [comment]
+1 Diddo.

**Comment by loganfsmyth** [comment]
@fundon Your issue seems unrelated. Make sure you've read the Babel 6 setup instructions: http://babeljs.io/blog/2015/10/31/setting-up-babel-6/

**Comment by fundon** [comment]
@loganfsmyth I have read. 

Below is my package.json

```js
  "babel": {
    "presets": [
      "stage-2",
      {
        "plugins": [
          "transform-es2015-modules-commonjs",
          "transform-es2015-spread",
          "transform-oject-rest-spread"
        ]
      }
    ]
  }

```

**Comment by loganfsmyth** [comment]
@fundon Your example is throwing because you are using destructuring, and you don't have the destructuring plugin enabled or a preset that enables it. That is why I said your issue is unrelated.

**Comment by quirinpa** [comment]
anxiously awaiting resolution for this. :P
