### ISSUE TITLE
browser.js and browser.min.js are empty files

### ISSUE THREAD

**Issue by smussell** [babel/babel#2635]
When I install the latest babel-core I end up with browser.js and browser.min.js as empty files with no content just some white space, each file is around 4 bytes, compared to babel-core 5.8 where browser.js is 2MB.  I am using npm 2.11.3.  I don't see any errors or warnings on install everything appears fine, except those files are empty.

![screen shot 2015-10-29 at 4 22 13 pm](https://cloud.githubusercontent.com/assets/90569/10834779/98826944-7e59-11e5-8d68-29c24694695f.png)

**Comment by jmm** [comment]
@smussell Thanks for the report! I'm seeing the same thing (`babel-core@6.0.2`).

**Comment by sindresorhus** [comment]
@sebmck Can you please leave these out of the `babel-core` package? They waste a lot of space. Babel is heavy enough dependency as is. Since they're not included in the first release of v6 anyways, just keep it that way and publish them as a separate package.

// @thejameskyle

**Comment by thejameskyle** [comment]
That seems like an okay idea to me

**Comment by zertosh** [comment]
I'm going to agree with that - anything to trim the size

**Comment by Julio-Guerra** [comment]
As an example, `es6-module-loader` cannot work without a browser version of babel (i.e. without `brower.js`). babel-polyfill has a `browser.js` file but the interface is not the same (I don't really know what it is).

**Comment by loganfsmyth** [comment]
Someone tracked down the cause: https://github.com/babel/babel/pull/2721

@sebmck thoughts on making this a standalone module?

**Comment by jiyinyiyong** [comment]
Also empty in `6.0.16`.

**Comment by azat-co** [comment]
Apparently they want us to use a stand alone package babel-browser from now on https://www.npmjs.com/package/babel-browser... however it fails on me with https://github.com/babel/babel/commit/c0afdfd1a83aab0c25a1fc23cee0b09d560f4d35#commitcomment-14371808
