### ISSUE TITLE
babel-cli confusion?

### ISSUE THREAD

**Issue by JacksonGariety** [babel/babel#2636]
I'm trying to figure babel 6 out.

My guess was that this:

    $ babel server.js -b=es2015

would turn this:

    import 'http'

into this:

    var http = require('http');

But instead I got this:

    import 'http';
    //#sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNlcnZlci5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxPQUFPLE1BQU0sQ0FBQSIsImZpbGUiOiJ1bmRlZmluZWQiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgJ2h0dHAnXG4iXX0=

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
