### ISSUE TITLE
6.0 changelog

### ISSUE THREAD

**Issue by STRML** [babel/babel#2640]
I understand 6.0 was a bit rushed - and the massive commit is a bit of a rabbit hole - it would be very nice to get a few changelog entries for this so I know what I'm dealing with.

**Comment by sebmck** [comment]
I'll do it in the next few days.

**Comment by hzoo** [comment]
This is added now https://github.com/babel/babel/blob/master/CHANGELOG.md#600

**Comment by sebmck** [comment]
It's not finished.

**Comment by hzoo** [comment]
Sorry my b
