### ISSUE TITLE
6.0 has babel 5.8.21 as devDependency

### ISSUE THREAD

**Issue by STRML** [babel/babel#2641]
Is this intentional? https://github.com/babel/babel/blob/ae7d5367f1c3d438667242d6925db024f875fccd/package.json#L5

**Comment by loganfsmyth** [comment]
> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

Babel is self-hosting and written in ES6. It uses the previous version to compile the new one.

**Comment by sebmck** [comment]
Yes. Babel 6 core is compiled with Babel 5. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
