### ISSUE TITLE
`babel-node app.js` doesn't run es6 node app anymore

### ISSUE THREAD

**Issue by reichert621** [babel/babel#2642]
I recently updated some of my babel dependencies, and running `babel-node app.js` in dev doesn't seem to work anymore:

```
babel-node app.js

import middlewares from 'koa-middlewares';
^^^^^^

SyntaxError: Unexpected reserved word
```

Also --and  this may be a noob question -- I'm not sure why running `npm start` (which also runs `babel-node app.js`) returns a different error:

```
npm start
> babel-node app.js

/.../node_modules/.bin/babel-node: line 1: syntax error near unexpected token `"The CLI has been moved into the package `babel-cli`."'
/.../node_modules/.bin/babel-node: line 1: `console.error("The CLI has been moved into the package `babel-cli`.");'
```

Is there a new improved way to do this?

**Comment by loganfsmyth** [comment]
@reichert621 Have you enabled the `es2015` preset?

**Comment by sindresorhus** [comment]
You probably want to start checking what's changed when you upgrade major versions.

http://babeljs.io/blog/2015/10/29/6.0.0/

> I'm not sure why running npm start (which also runs babel-node app.js) returns a different error:

`npm start` uses your local version of Babel. You need to `$ npm install --save-dev babel-cli`.
