### ISSUE TITLE
Implement: decorator proposal

### ISSUE THREAD

**Issue by kittens** [babel/babel#2645]

**Comment by SrMouraSilva** [comment]
(+1)

**Comment by SrMouraSilva** [comment]
``` javascript
//.babelrc
{
  "plugins": [
      "syntax-decorators",
      "transform-decorators"
  ]
}
```

Original
```javascript
function tester(a, b, c) {
    return c;
}

class Test {
    @tester
    test(a) {
        return a;
    }
}
```

Babelled
``` javascript
function tester(a, b, c) {
    return c;
}

class Test {}
Test;


```

**Comment by SrMouraSilva** [comment]
Decorating a class:

``` javascript
function classTester(target) {

}

function tester(a, b, c) {
    return c;
}

@classTester
class Test {
    @tester
    test(a) {
        return a;
    }
}
```

```
D:\Mateus\#evento\servidor\app\protocolo>babel ProtocoloComunicacao.js >> test.j
s
TypeError: ProtocoloComunicacao.js: Property right of AssignmentExpression expec
ted node to be of a type ["Expression"] but instead got "Decorator"
    at Object.validate (D:\Mateus\#evento\servidor\node_modules\babel-plugin-tra
nsform-decorators\node_modules\babel-types\lib\definitions\index.js:97:13)
    at validate (D:\Mateus\#evento\servidor\node_modules\babel-plugin-transform-
decorators\node_modules\babel-types\lib\index.js:267:9)
    at Object.builder (D:\Mateus\#evento\servidor\node_modules\babel-plugin-tran
sform-decorators\node_modules\babel-types\lib\index.js:243:7)
    at maybeMemoise (D:\Mateus\#evento\servidor\node_modules\babel-plugin-transf
orm-decorators\node_modules\babel-helper-explode-class\lib\index.js:29:32)
    at memoiseDecorators (D:\Mateus\#evento\servidor\node_modules\babel-plugin-t
ransform-decorators\node_modules\babel-helper-explode-class\lib\index.js:56:7)
    at Object.exports.default (D:\Mateus\#evento\servidor\node_modules\babel-plu
gin-transform-decorators\node_modules\babel-helper-explode-class\lib\index.js:61
:3)
    at PluginPass.ClassDeclaration (D:\Mateus\#evento\servidor\node_modules\babe
l-plugin-transform-decorators\lib\index.js:164:45)
    at newFn (C:\Users\JoséAntônio\AppData\Roaming\npm\node_modules\babel-cli\no
de_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\JoséAntônio\AppData\Roaming\npm\node_modules\bab
el-cli\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:7
2:18)
    at NodePath.call (C:\Users\JoséAntônio\AppData\Roaming\npm\node_modules\babe
l-cli\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44
:17)
```

**Comment by SrMouraSilva** [comment]
You need add a plugin for any you need functionality: http://babeljs.io/docs/plugins/

Unfortunately, the documentation of the plugins is not yet complete

**Comment by SrMouraSilva** [comment]
For methods:

In [babel-plugin-transform-decorators](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-decorators/src/index.js#L33-L50)

[Line 41](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-decorators/src/index.js#L41): Remove the decorator methods

[Line 47](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-decorators/src/index.js#L47): ???

I don't found a similar code in babel 5.x :/

**Comment by sebmck** [comment]
The Babel issue tracker is not for support queries.

**Comment by idchlife** [comment]
Any info when Decorators will be again available in babel?

**Comment by hzoo** [comment]
If we have an update we'll make a comment here - I don't think anyone has time to work on it

**Comment by just-boris** [comment]
@idchlife I'd like to mention that this is not about working on actual Babel plugin or something.
There needs to be done some work on the spec.

There were some questions left, the last update was on [July meeting](https://github.com/rwaldron/tc39-notes/blob/master/es7/2016-07/jul-28.md#9iiic-decorators).

For the time being, there is an external plugin [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy). The thing why it doesn't belong to core repo, because it likely will change, even [the `@`-symbol might be changed](https://github.com/rwaldron/tc39-notes/blob/master/es7/2016-09/sept-29.md#11iid-sigil-swap-decorators---private-fields)

**Comment by chicoxyzzy** [comment]
Recently Yehuda said that [proposal is waiting for implementations](https://twitter.com/wycats/status/803834475931115521). Symbol unlikely will be changed because a huge part of committee is opposed to sigil swap with private properties. So IMO it's best time to start hacking on this right now :)

**Comment by hzoo** [comment]
- relevant parser issues https://github.com/babel/babylon/issues?q=is%3Aissue+is%3Aopen+label%3A%22spec%3A+decorators%22

**Comment by DrewML** [comment]
I've started working on a new plugin for `Babylon` to implement the updated grammar for the Stage 3 version of the grammar. Once that is done, I can start hacking on the transform.

**Comment by Harris-Miller** [comment]
Decorators at Stage 2 since January 4th: http://tc39.github.io/proposal-decorators/

**Comment by langpavel** [comment]
:+1:

**Comment by hzoo** [comment]
Please don't +1, it's not going to make it happen any faster/sooner. If you have constructive comments to add you can comment in https://github.com/babel/babylon/pull/236

**Comment by hzoo** [comment]
@babel-bot move to babel/proposals
