### ISSUE TITLE
Presets make it impossible to plugins when order is important

### ISSUE THREAD

**Issue by bfrydl** [babel/babel#2648]
For example, if you add decorators to a class method, it will fail with the error "Method has decorators, put the decorator plugin before the classes one." But if you're using the es2015 preset, it's impossible to do this, meaning your only option is to install all of the plugins manually.

**Comment by hzoo** [comment]
Unless we decide to support allowing users to override presets, like mentioned the options are be to either use a preset (a fixed set of plugins), or to decide to specify what you need manually. Might of been discussed in the 6.0 issue/slack but I forgot.

But I guess this specific issue about decorators/classes can be fixed unrelated to that?

**Comment by bfrydl** [comment]
Presets should be overridable in some fashion. For example, if you're on node.js you don't need transform-regenerator, but there's no way to exclude it from the es2015 preset, so you either live with regenerator or install everything manually.

**Comment by hzoo** [comment]
In JSCS we allow presets to be overridden with new options or turned off. Right now babel is using an array of strings for the plugins.

If we went back to an object we could something like: (not sure)

```js
{
  "presets": {
    "es2015": true
  },
  "plugins": {
    "transform-regenerator": false
  }
}
```

This might be better especially if plugins may support options later like

```js
 "plugins": {
    "transform-plugin-x": {
      "optionA": true,
      "optionB": 1    
    }
  }
```

**Comment by thejameskyle** [comment]
If one of the defaults doesn't work for you, you can either specify them manually or you can always create your own preset. `babel-preset-bfrydl` (please be careful about what you name this, we all share a namespace). I fully expect people to create presets for all sorts of stuff. ie. `babel-preset-node-{version}`

**Comment by bfrydl** [comment]
It seems a little extreme to require people to create an entire new npm package for a preset just because they want to disable one plugin from an existing one. Perhaps in the future presets will have been made for every situation but at the moment if your needs aren't met by the two default ones, you're either creating your own npm package or installing dozens of plugins.

**Comment by thejameskyle** [comment]
I suggested making your own because you might prefer that so you can transport it across your projects easily. People do the same thing with eslint configuration.

**Comment by sebmck** [comment]
> Presets should be overridable in some fashion. For example, if you're on node.js you don't need transform-regenerator, but there's no way to exclude it from the es2015 preset, so you either live with regenerator or install everything manually.

The entire point of them is that they aren't overridable. You either take it or leave it. If you want fine grained control then you shouldn't be using a preset. Not only that but it's literally impossible for us to implement any sort of plugin modifying state variables like what were present in 5.x because plugins don't have an uid.

---

Regardless, that's a completely separate discussion, this issue can be solved by changing the order in which arrays are merged for presets.

**Comment by bfrydl** [comment]
> The entire point of them is that they aren't overridable. You either take it or leave it. If you want fine grained control then you shouldn't be using a preset.

Yeah, I originally thought they were aimed at reducing how much more effort Babel 6 setup and configuration takes than Babel 5, but if it's just for sharing configs between repos I see why there's no need for an override.

**Comment by shuhei** [comment]
It would work only if `plugins` comes **before** `presets` just like Babel 5's plugins ran before built-in transformers by default.

https://github.com/babel/babel/issues/2688#issuecomment-152696562

**Comment by twada** [comment]
I've met the same issue while making [babel-plugin-espower](https://github.com/power-assert-js/babel-plugin-espower) babel6 ready since it should run before `preset` plugins too.

**Comment by shuhei** [comment]
Found that we can control the order of plugins better by using only presets. Not sure it's the way to go though...

```json
{
  "presets": [
    {
      "plugins": [
        "transform-foo",
        "transform-bar"
      ]
    },
    "es2015"
  ]
}
```

**Comment by jeffijoe** [comment]
Soooo.. What do we end up with? I'm stuck on the

> Method has decorators, put the decorator plugin before the classes one.

I am using the stage-1 and es2015 presets.

```
presets: ['stage-1', 'es2015']
```

**Comment by shuhei** [comment]
By https://github.com/babel/babel/commit/2bdc222c0bbba1a161dcd406dd9d58ade1927259 presets' order has been reversed. What if you reverse the presets?

**Comment by jeffijoe** [comment]
Didn't help either

**Comment by Znegl** [comment]
I'm still getting the error described with these settings after updating to the newest version of Babel:
```javascript
{
	presets: [
		'es2015',
		'react'
	],
	plugins: [
		'syntax-decorators'
	]
}
```

**Comment by goodhyun** [comment]
I'm also having similar symptoms.
```
Decorators are not supported yet in 6.x pending proposal update.
  27 | @DragDropContext(HTML5Backend)
  28 | @connect(state => state.bricks)
> 29 | class
```

**Comment by sebmck** [comment]
@goodhyun Erm, how is that a similar problem at all? The error message is pretty clear that it's not implemented yet.

**Comment by goodhyun** [comment]
Even if presets include "stage-0"? 
Anyhow, I'm stuck at that old decorators, while moving onto Babel 6.

**Comment by impinball** [comment]
I have a problem where I want the same configuration, but I want to disable a single plugin for one use. Everything in my project is run with effectively `babel-preset-es2015` minus the typeof transformer, but I want to omit the CommonJS module formatter for a Gulp pipeline.
