### ISSUE TITLE
[Question] Babel v6: How/Can I write a plugin that adds a new operator?

### ISSUE THREAD

**Issue by gsklee** [babel/babel#2653]
I've checked files like [packages/babel-plugin-syntax-do-expressions](https://github.com/babel/babel/blob/development/packages/babel-plugin-syntax-do-expressions/src/index.js) and it seemed that these ES6+ new syntax/operators weren't actually defined in the plugin at all but perhaps being implemented in Babylon and simply being toggled on by these plugins, leaving the claim in the newest blog post that "Developers have built everything from debugging tools [...] to experimental new syntaxes [...] to enforce complex rules on their codebases" dubious - actually, I've searched the [entire plugin ecosystem](https://www.npmjs.com/search?q=babel-plugin) but found no plugin being able to offer new operators/syntax, and only exactly one plugin that's able to offer operator overloading for a few existing operators.

So, is it really true that with Babel v6 we'll be able to see new operators/syntax being defined in the userland, and how?

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>
