### ISSUE TITLE
Wrong version of `babel-runtime` used in dependencies

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2655]
We're using `5.x` to transpile all the files for `6.x`, but everything depends on `babel-runtime@^6.0.2`, which only by chance is working right now. They should all depend on `babel-runtime@5.x`.

**Comment by thejameskyle** [comment]
This causes fresh clones of Babel to be unable to build. https://github.com/babel/babel/issues/2662

**Comment by zertosh** [comment]
@sebmck would you be open to not using the runtime until babel 6 can be compiled with babel 6? even with deduping, every package ends up with its own runtime. i'd be more than happy to PR this.

**Comment by sebmck** [comment]
@zertosh 

> would you be open to not using the runtime until babel 6 can be compiled with babel 6?

No. The packages rely on the runtime as some of them use symbols.

> even with deduping, every package ends up with its own runtime

That shouldn't be the case. Any idea why?

**Comment by zertosh** [comment]
> That shouldn't be the case. Any idea why?

`babel-core` depends on `babel-runtime@^6.0.2`, and the `babel-plugins-*` depend on `babel-runtime@^5.0.0`. So in a project that depends on `babel-core` and the `babel-preset-es2015`, the dep tree looks like this:

```
my-project
├─┬ babel-core@^6.0.14
│ └── babel-runtime@^6.0.2
├─┬ babel-preset-es2015@^6.0.14
│ ├─┬ babel-plugin-transform-es2015-classes@^6.0.14
│ │ └── babel-runtime@^5.0.0
│ └─┬ babel-plugin-transform-es2015-arrow-functions@^6.0.14
│   └── babel-runtime@^5.0.0
...
```

And it gets deduped to:

```
my-project
├── babel-core@^6.0.14
├── babel-runtime@^6.0.2
├─┬ babel-plugin-transform-es2015-classes@^6.0.14
│ └── babel-runtime@^5.0.0
├─┬ babel-plugin-transform-es2015-arrow-functions@^6.0.14
│ └── babel-runtime@^5.0.0
├── babel-preset-es2015@^6.0.14
...
```

The plugin's old runtime can't be factored out because there's already a semver incompatible version further up the tree.

**Comment by sebmck** [comment]
> `babel-core` depends on `babel-runtime@^6.0.2`

[No it doesn't](https://github.com/babel/babel/blob/master/packages/babel-core/package.json#L36)

**Comment by thejameskyle** [comment]
@sebmck the latest version on npm still does.

**Comment by zertosh** [comment]
What @thejameskyle said. `npm info babel-core` (trimmed the versions and times):

```
{ name: 'babel-core',
  description: 'Babel compiler core.',
  'dist-tags': { beta: '5.0.0-beta4', latest: '6.0.14' },
  versions: 
   [ '6.0.14' ],
  maintainers: [ 'sebmck <sebmck@gmail.com>' ],
  time: 
   { '6.0.14': '2015-10-30T23:31:42.795Z' },
  homepage: 'https://babeljs.io/',
  keywords: 
   [ '6to5',
     'babel',
     'classes',
     'const',
     'es6',
     'harmony',
     'let',
     'modules',
     'transpile',
     'transpiler',
     'var' ],
  repository: 
   { type: 'git',
     url: 'https://github.com/babel/babel/tree/master/packages/babel-core' },
  author: 'Sebastian McKenzie <sebmck@gmail.com>',
  readmeFilename: 'README.md',
  users: 
   { rblopes: true,
     yodairish: true,
     borjes: true,
     wkaifang: true,
     taopaic: true,
     ugarz: true,
     daviddraughn: true,
     evertonrobertoauler: true,
     bdougherty: true,
     tcrowe: true,
     shangwenmo: true,
     draganhr: true,
     piecioshka: true,
     manxisuo: true },
  license: 'MIT',
  version: '6.0.14',
  browser: 
   { './lib/api/register/node.js': './lib/api/register/browser.js',
     'esprima-fb': false },
  scripts: { bench: 'make bench', test: 'make test' },
  dependencies: 
   { 'babel-code-frame': '^6.0.14',
     'babel-generator': '^6.0.14',
     'babel-helpers': '^6.0.14',
     'babel-messages': '^6.0.14',
     'babel-template': '^6.0.14',
     'babel-runtime': '^6.0.14',
     'babel-traverse': '^6.0.14',
     'babel-types': '^6.0.14',
     babylon: '^6.0.14',
     'convert-source-map': '^1.1.0',
     debug: '^2.1.1',
     esutils: '^2.0.0',
     'home-or-tmp': '^1.0.0',
     json5: '^0.4.0',
     lodash: '^3.10.0',
     minimatch: '^2.0.3',
     'path-exists': '^1.0.0',
     'path-is-absolute': '^1.0.0',
     private: '^0.1.6',
     regenerator: '0.8.35',
     'shebang-regex': '^1.0.0',
     slash: '^1.0.0',
     'source-map': '^0.4.0',
     'source-map-support': '^0.2.10' },
  devDependencies: { 'babel-polyfill': '^6.0.14' },
  dist: 
   { shasum: 'ec5fd5bf0e762a22cc031fcd4935b28db2969d38',
     tarball: 'http://registry.npmjs.org/babel-core/-/babel-core-6.0.14.tgz' },
  directories: {} }
```

**Comment by sebmck** [comment]
This will be fixed once I push out a new version then.

On Sun, Nov 1, 2015 at 8:28 PM, Andres Suarez <notifications@github.com>
wrote:

> What @thejameskyle <https://github.com/thejameskyle> said. npm info
> babel-core (trimmed the versions and times):
>
> { name: 'babel-core',
>   description: 'Babel compiler core.',
>   'dist-tags': { beta: '5.0.0-beta4', latest: '6.0.14' },
>   versions:
>    [ '6.0.14' ],
>   maintainers: [ 'sebmck <sebmck@gmail.com>' ],
>   time:
>    { '6.0.14': '2015-10-30T23:31:42.795Z' },
>   homepage: 'https://babeljs.io/',
>   keywords:
>    [ '6to5',
>      'babel',
>      'classes',
>      'const',
>      'es6',
>      'harmony',
>      'let',
>      'modules',
>      'transpile',
>      'transpiler',
>      'var' ],
>   repository:
>    { type: 'git',
>      url: 'https://github.com/babel/babel/tree/master/packages/babel-core' },
>   author: 'Sebastian McKenzie <sebmck@gmail.com>',
>   readmeFilename: 'README.md',
>   users:
>    { rblopes: true,
>      yodairish: true,
>      borjes: true,
>      wkaifang: true,
>      taopaic: true,
>      ugarz: true,
>      daviddraughn: true,
>      evertonrobertoauler: true,
>      bdougherty: true,
>      tcrowe: true,
>      shangwenmo: true,
>      draganhr: true,
>      piecioshka: true,
>      manxisuo: true },
>   license: 'MIT',
>   version: '6.0.14',
>   browser:
>    { './lib/api/register/node.js': './lib/api/register/browser.js',
>      'esprima-fb': false },
>   scripts: { bench: 'make bench', test: 'make test' },
>   dependencies:
>    { 'babel-code-frame': '^6.0.14',
>      'babel-generator': '^6.0.14',
>      'babel-helpers': '^6.0.14',
>      'babel-messages': '^6.0.14',
>      'babel-template': '^6.0.14',
>      'babel-runtime': '^6.0.14',
>      'babel-traverse': '^6.0.14',
>      'babel-types': '^6.0.14',
>      babylon: '^6.0.14',
>      'convert-source-map': '^1.1.0',
>      debug: '^2.1.1',
>      esutils: '^2.0.0',
>      'home-or-tmp': '^1.0.0',
>      json5: '^0.4.0',
>      lodash: '^3.10.0',
>      minimatch: '^2.0.3',
>      'path-exists': '^1.0.0',
>      'path-is-absolute': '^1.0.0',
>      private: '^0.1.6',
>      regenerator: '0.8.35',
>      'shebang-regex': '^1.0.0',
>      slash: '^1.0.0',
>      'source-map': '^0.4.0',
>      'source-map-support': '^0.2.10' },
>   devDependencies: { 'babel-polyfill': '^6.0.14' },
>   dist:
>    { shasum: 'ec5fd5bf0e762a22cc031fcd4935b28db2969d38',
>      tarball: 'http://registry.npmjs.org/babel-core/-/babel-core-6.0.14.tgz' },
>   directories: {} }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2655#issuecomment-152861021>.
>



-- 
Sebastian McKenzie

**Comment by zertosh** [comment]
6.0.15 fixed it! babel-core + babel-preset-es2015 is a temperate 17mb. Now, if only regenerator and regexpu didn't pull in recast, esprima, and commoner.
