### ISSUE TITLE
polyfill and runtime transformer documentation is lacking now

### ISSUE THREAD

**Issue by AgentME** [babel/babel#2656]
The old page about the [runtime transformer](https://webcache.googleusercontent.com/search?q=cache:XKCui6xrfpoJ:https://babeljs.io/docs/usage/runtime/+) seems to have disappeared. There's a [new page](https://babeljs.io/docs/plugins/transform-runtime/) about the runtime transformer, but it's less than useful. The [setup page](https://babeljs.io/docs/setup/#browserify) doesn't seem to mention the polyfill-or-runtime-transformer requirement at all. Nothing I found seems to link to the [polyfill page](https://babeljs.io/docs/usage/polyfill/), and that page doesn't do much to explain its necessity. Issues like #2654 seem inevitable for new users currently.

The polyfill page ought to explain its relationship to the runtime transformer and the necessity of one or the other being used for most es2015 transforms, and other pages (mainly the setup page and/or the transformers page) should link to it.

**Comment by sebmck** [comment]
See the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by AgentME** [comment]
Thanks, this is https://github.com/babel/babel.github.io/issues/491 now.
