### ISSUE TITLE
transform-async-to-generator doesn't change `await` to `yield` inside method

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#2661]
Here's the code I'm compiling:

	class Foo {
		async bar() {
			await baz
		}
	}

My package.json is:

	{
		"scripts": {
			"build": "babel src --out-dir dist"
		},
		"devDependencies": {
			"babel-cli": "6.0.12",
			"babel-plugin-transform-async-to-generator": "6.0.2"
		},
		"babel": {
			"plugins": ["transform-async-to-generator"]
		}
	}

The compiled code is:

	function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { var callNext = step.bind(null, "next"); var callThrow = step.bind(null, "throw"); function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(callNext, callThrow); } } callNext(); }); }; }

	class Foo {
		bar() {
			return _asyncToGenerator(function* () {
				await baz;
			})();
		}
	}

I would expect that to be `yield baz` in the compiled code.

**Comment by MarkTiedemann** [comment]
@andy-hanson Can you please show the output of the command? That might help find the cause of this issue. :)

Anyways, I had a similar or maybe the same issue yesterday. In my case, running babel from an npm script resulted in babel trying to transpile the src dir in the dir of the command line executable instead of the project dir. When I ran `babel src --out-dir dist` directly in the shell in my project dir, it worked. Hope this helps you as a temporary fix. :)

**Comment by MarkTiedemann** [comment]
Okay, I got `async` to be transpiled to `yield` by installing the following plugins:

`package.json`
```
"dependencies": {
   "babel-cli": "^6.0.12",
   "babel-plugin-syntax-async-functions": "^6.0.2",
   "babel-plugin-syntax-async-generators": "^6.0.2",
   "babel-plugin-transform-async-to-generator": "^6.0.2"
},
"plugins": [
   "syntax-async-functions",
   "syntax-async-generators",
   "transform-async-to-generator"
 ]
```

And then running: `babel src --out-dir dist`

`src/test.js`
```
async function foo() {
   await bar();
}
```

`dist/test.js`
```
let foo = function foo() {
   return _asyncToGenerator(function* foo() {
      yield bar();
   })();
};

function _asyncToGenerator(fn) { /* removed to shorten code */ }
```

**Comment by fixe** [comment]
I confirm that this bug was introduced in 6.0.0.
