### ISSUE TITLE
How is babel cache work ?

### ISSUE THREAD

**Issue by Pana** [babel/babel#2665]
I use babel(5.8) require hook in my code, occasionally i will got some method is not defined error, but which i has define, though i thought this is caused by babel cache !

**Comment by jmm** [comment]
Hello @Pana, for support please see the resources in the README:

> <p align="center">For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

> <p align="center">The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>

Thanks!

**Comment by loganfsmyth** [comment]
May be another instance of https://github.com/babel/babel/issues/2455 if you have non-ASCII characters in that file.

**Comment by Pana** [comment]
Yeah, this is caused by non-ASCII characters. Thanks @loganfsmyth
