### ISSUE TITLE
Unexpected token on html tags

### ISSUE THREAD

**Issue by DmitriyD** [babel/babel#2666]
I keep  getting this error when try to run cli babel on file with simple example from ReactJS docs.

    SyntaxError: manage.js: Unexpected token (2:2)
      1 | ReactDOM.render(
    > 2 |   <h1>Hello, world!</h1>,
        |   ^
      3 |   document.getElementById('example')
      4 | );

But the same file works fine when using browser babel.

**Comment by safareli** [comment]
what does your `.babelrc` looks like? If you are using babel ^6.0.0 it should be like this.
```
{
  "presets": ["es2015", "react"],
}
```

**Comment by jmm** [comment]
Hello @DmitriyD, welcome to the Babel community!

Please see the README for information about where to get support:

> <p align="center">For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

> <p align="center">The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>

If this is with v6 then @safareli has probably provided your solution.
