### ISSUE TITLE
is there a way to use loose modules when using es2015 preset?

### ISSUE THREAD

**Issue by zowers** [babel/babel#2668]
tried to use following babelrcs
---
1. 
```
{
  "presets": [
    ["es2015",{"transform-es2015-modules-commonjs":{"loose":true}}]
    ]
}
```
fails with "Invalid options type for foreign"

---
2.
```
{
  "presets": ["es2015"],
  "plugins": [["transform-es2015-modules-commonjs",{"loose":true}]]
}
```
ignores the "loose" option

---
3.
```
{
  "plugins": [["transform-es2015-modules-commonjs",{"loose":true}]]
}
```
does not use the preset

**Comment by safareli** [comment]
my .babelrc  looks like this might be helpful 
```
{
  "presets": ["es2015", "react"],
  "plugins": ["transform-decorators","transform-class-properties"]
}
```

**Comment by zowers** [comment]
not sure how it helps you, it does help me
loose modules must use 
```
exports.__esModule = true;
```

instead of
```
Object.defineProperty(exports, "__esModule", {
    value: true
});
```

**Comment by zowers** [comment]
btw, why is `Object.defineProperty` variant is used by default? es3 browsers do not have working `defineProperty()`

**Comment by forivall** [comment]
You should ask questions like that in the slack channel.

From **README.md**:
> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
> The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by zowers** [comment]
sure, off to http://stackoverflow.com/questions/33446318/is-there-a-way-to-use-loose-modules-when-using-es2015-preset

**Comment by jmm** [comment]
Thanks @forivall!
