### ISSUE TITLE
help me update .babelrc for babel 6.x

### ISSUE THREAD

**Issue by leecade** [babel/babel#2677]
```
{
  "stage": 0,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}
```

**Comment by jmm** [comment]
Hello @leecade, welcome to the Babel community!

Please see the README for information about where to get support:

> <p align="center">For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

> <p align="center">The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>

**Comment by sunghyunzz** [comment]
@leecade did you make it? I got into the same problem :(
