### ISSUE TITLE
Babel6 breaks module/commonjs interoperability

### ISSUE THREAD

**Issue by spudly** [babel/babel#2679]
Babel6 no longer includes `module.exports = exports["default"]` when you `export default` something. This means that when you upgrade a package from babel 5 to babel 6, any non-babel dependencies will break. To fix them they'd have to change `require('mymodule')` to `require('mymodule').default`.

Sample code:
```js
export default "test";
```

Babel5 Result:
```js
"use strict";

exports.__esModule = true;
exports["default"] = "test";
module.exports = exports["default"];
```

Babel6 Result:
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = "test";
```

**Comment by jmm** [comment]
Hello @spudly, welcome to the Babel community!

I don't know if it's properly documented, but that change is by design; see https://github.com/babel/babel/issues/2212.

**Comment by spudly** [comment]
Yes, please document this somewhere. Currently the changelog has this

> 6.0.0
> 
> TODO SEBASTIAN YOU'RE BAD

... which is totally not helpful, and there is no mention of this in the blog post either.

Thanks for your help!

**Comment by jmm** [comment]
@spudly I totally agree with you. Feel free to open an issue on the website repo (see the README here) to get this documented. It should of course be in the changelog for this repo also, but I think the best thing at the moment would be to note that in an issue on the website repo.

**Comment by toddself** [comment]
This has been vexing me for the past 48 hours -- why is babel6 outputting `export defaults` not under `module.exports` -- this bug, which you can only find if you look at closed issues, is the only thing that references it.

This should be definitely listed in a breaking changes section for changing from v5 to v6 -- the "6.0.0 released document" makes no reference of it at all and is quite a big change for people upgrading from v5 to v6

**Comment by loganfsmyth** [comment]
> Remove module.exports export interop for CommonJS module formatter.

I agree it's not super obvious what that means though.

**Comment by JustBlackBird** [comment]
Is there a workaround for this problem. I definitely don't want to use
```js
var m = require('my-module').default;
```
in the code.

Is there any plugin for this?

**Comment by ysmood** [comment]
@JustBlackBird +1
