### ISSUE TITLE
Where can I find v5 docs now that the website has been updated?

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#2680]

**Comment by jmm** [comment]
Hello @callumlocke, Please see the README for information about where to get support and open issues re: documentation:

> <p align="center">For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

> <p align="center">The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>

> <p align="center">
  For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
</p>

**Comment by sebmck** [comment]
There's a link in the footer of the website to 5.x docs.
