### ISSUE TITLE
Params after defaults are read from outer scope

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2682]
Reported on Slack:

```
export var collect = (since = 0, userid) => {
  console.log(userid);
}
collect(false, 'A0001'); // output script path
```

becomes

```
var _arguments = arguments;
Object.defineProperty(exports, "__esModule", {
  value: true
});
// babel 6.0.12
var collect = exports.collect = function collect() {
  var since = arguments.length <= 0 || arguments[0] === undefined ? 0 : arguments[0];
  var userid = _arguments[1];

  console.log(userid);
};
collect(false, 'A0001'); // output 'A0001'
```

Node that `var userid = _arguments[1];` reads from an outer `arguments` instead of the function's real arguments.

**Comment by ndaidong** [comment]
@loganfsmyth thank you, Logan. 

Do you have anyway to quickly fix this for all modules in my app? A global config or proto modification, or similar is OK.

**Comment by sebmck** [comment]
@ndaidong I already pushed a new version fixing this.

**Comment by ndaidong** [comment]
@sebmck thank you, Sebastian. I'm upgrading now.
