### ISSUE TITLE
"require(...) is not a function" error while using require dynamically in babel 6.0 with node

### ISSUE THREAD

**Issue by yamalight** [babel/babel#2683]
So, I tried migrating one of my projects to babel 6.0 and encountered the following error message:
```
TypeError: require(...) is not a function
    at other.js:7:48
    at Array.forEach (native)
    at Object.<anonymous> (other.js:7:7)
    at Module._compile (module.js:425:26)
    at loader (/Users/yamalight/Projects/js/test/babel/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/yamalight/Projects/js/test/babel/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

The error occurs when I try to read filenames from directory and then dynamically require all of them, i.e.:
```js
import fs from 'fs';

// get local files
const files = fs.readdirSync('./test');

// require and execute each
files.forEach(file => require('./test/' + file)());
```

Simplified version that also fails:
```js
require('./test.js')();
```

Here's the full code that reproduces the behavior with simplified case: https://gist.github.com/yamalight/7de2b4f8ec9a48a7782f

Switching back to babel 5.x resolves the issue.

**Comment by MarkTiedemann** [comment]
Hey @yamalight,

Looked at your gist.

The problem there seems to be that `export default` is not compatible with `require(...)`.

Not sure, though, whether this is a bug or intended behavior.

Anyways, to fix your problem, you can simply use `import` in combination with `export`.

`entry.js`
```
import test from './test';
test();
``` 

`test.js`
```
export default () => console.log('okay');
```

**Comment by yamalight** [comment]
@MarkTiedemann seems like a bug to me. babel es2015 preset does compile everything to commonjs in the end, so I don't see how it may not work. and it worked perfectly fine with babel 5.x

also, the problem for me is not that simple case that's easily fixable, but the larger one with dynamic file list imports. you cannot call `import` from within functions

**Comment by loganfsmyth** [comment]
With Babel 6, you need to do

    files.forEach(file => require('./test/' + file).default());

Babel 6.x has dropped some of the CommonJS interop behavior and ES6 modules transpiled to ES5 will now have their default exposed as `.default` instead of _sometimes_ `.default` and sometimes directly as the exported value.

**Comment by yamalight** [comment]
@loganfsmyth aha, thank you for clarification. is that documented somewhere?

**Comment by loganfsmyth** [comment]
@thejameskyle may be able to answer that. Not sure off the top of my head.

**Comment by yamalight** [comment]
if not, it definitely should be. somewhere like [transform-es2015-modules-commonjs](http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) plugin description (first place where I tried to look for answers)

**Comment by pswai** [comment]
To add on, if you are not using the return value of `require()`, then it actually works fine (default export will be imported).

**Comment by lijunle** [comment]
It is mentioned as [breaking change](https://github.com/babel/babel/blob/master/CHANGELOG.md#600) of 6.0.0 in change log.

> Remove `module.exports` export interop for CommonJS module formatter.

---

However, install transform-es2015-modules-commonjs as plugin does not resolve my same problem. @yamalight How is it going?

My `.babelrc`:

```json
{
  "plugins": [
    "transform-es2015-modules-commonjs"
  ],
  "presets": [
    "es2015",
    "stage-2"
  ]
}
```

**Comment by yamalight** [comment]
@lijunle I just used `require(module).default()` as mentioned above

**Comment by lijunle** [comment]
:cry: @loganfsmyth any way to resolve this without touching the existing code?

**Comment by VasilioRuzanni** [comment]
While `require(module).default()` is an option sometimes, the `default()` isn't a part of CommonJS (despite having nice semantics brought in by ES2015) and this change in Babel 6 breaks apart any libs/frameworks/apps that rely on dynamic `require()`ing (there are **a lot** for node) - I think this might seriously affect the adoption of the 6.x version on the node side unless this is fixed somehow.

Would love to see a way to come over this without messing with the existing code in a big way.

**Comment by fundon** [comment]
Maybe `babel-plugin-require` is good.

**Comment by lijunle** [comment]
There is no [babel-plugin-require](https://www.npmjs.com/search?q=babel-plugin-require) on NPM? :question:

**Comment by marckaraujo** [comment]
Use this https://www.npmjs.com/package/babel-plugin-module-resolver

**Comment by challenger532** [comment]
any updates?

**Comment by mannguyenzalora** [comment]
I have the same problem with this, Any ideas how to solve the issue?

**Comment by femanso** [comment]
This worked for me:
```
fs.readdirSync('./modulesDir').forEach(async function(file) {
  const importedModule = await import('../../modulesDir/' + file)
  importedModule.default() 
})
```

this runs the module start function
if exported like: module.exports = function(controller) {}
