### ISSUE TITLE
When load duplicate plugin babel-preset-es2015, sometimes will throw a error

### ISSUE THREAD

**Issue by zbinlin** [babel/babel#2687]
babel-core: **v6.0.12**
babel-preset-es2015: **v6.0.12**

**Code:**
```js
const babel = require("babel-core");

babel.transform("export default class App extends Array {};", {
    presets: ["es2015", "es2015"]
});
```

**Expect:**
 no errors

**Actually:**
 throw a error

>SyntaxError: unknown: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)

Other scene is when write in a .babelrc, and as a options pass to transform function.

Can automatic remove the duplicate plugins in buildPlugins function? 
Or has a scene that use multiple same plugins?

**Comment by sebmck** [comment]
> Can automatic remove the duplicate plugins in buildPlugins function? 

Probably not. It'd make it impossible to use a plugin more than once which might be necessary if the plugins were provided specific options.

**Comment by thejameskyle** [comment]
>  use a plugin more than once 

For those wondering, this does happen. ie. https://github.com/gaearon/babel-plugin-react-transform

**Comment by thejameskyle** [comment]
The error that was being reported here was actually a separate issue. Babel does not throw any errors when specifying a plugin more than once.
