### ISSUE TITLE
transforming class properties

### ISSUE THREAD

**Issue by mattstyles** [babel/babel#2688]
```
"babel-cli": "^6.0.12"
"babel-preset-es2015": "^6.0.12"
"babel-plugin-transform-class-properties": "^6.0.2"
```

Gets unhappy about the `export default class` with a class prop

```
export default class A {
  constructor() {}
  state = 42
}
```

Results in an `undefined` error

```
TypeError: ./prop.js: Cannot read property 'shadow' of undefined
```

Works fine without the class property. Also works fine with a cheeky `extend` in there

```
import EventEmitter from 'eventemitter3'

export default class A {
  constructor() {
    super()
  }
  state = 42 
}
```

Slightly, oddly, its not just the `export default class` that results in an error either

```
class A {
  constructor() {}
  state = 42
}
export default A
```

Doesnt seem to want to apply the transform

```
SyntaxError: ./prop.js: Missing class properties transform.
  16 | 
  17 | 
> 18 |     state = 42
     |     ^
  19 | }
  20 | 
  21 | export default A
```

This one doesnt survive being extended either.

**Comment by mattstyles** [comment]
It looks like it is the empty constructor, this works fine

```
export default class A {
  constructor() {
    console.log( 'A' )
  }
  answer = 42
}
```

Not sure whether you just want to close this one straight off, is an empty constructor a valid concern?

**Comment by sebmck** [comment]
Looking into it.

**Comment by sebmck** [comment]
What's your `.babelrc`?

**Comment by mfrye-intuit** [comment]
I have a similar issue.

```
class App extends React.Component {
  constructor(props) {
    super(props)  
  }

  static childContextTypes = {
    muiTheme: React.PropTypes.object.isRequired,
    router: React.PropTypes.func.isRequired
  }
}
```

```
SyntaxError: /Users/mfrye2/code/d3-mobile/client/es6/app.js: Missing class properties transform.
  27 |   // }
  28 |
> 29 |   static childContextTypes = {
     |   ^
  30 |     muiTheme: React.PropTypes.object.isRequired,
  31 |     router: React.PropTypes.func.isRequired
  32 |   }
```

my .babelrc
```
{
  "presets": ["react", "es2015", "babel-preset-stage-1"],
  "plugins": [
    "transform-class-properties"
  ]
}
```

**Comment by shuhei** [comment]
I guess it's because transformers in `plugins` runs **after** ones in `presets`. So `transform-es2015-classes` tries to compile classes into ES5 before `class-properties` runs and gets an error.

Possible fix would be listing up all the contents of the preset **after** `transform-class-properties` in `plugins`.

I think this is a fundamental issue of `preset` and `plugins`.

**Comment by mattstyles** [comment]
{ "presets": [ "es2015" ], "plugins": [ "transform-class-properties" ] }

It's like the constructor gets stripped as its empty, then there is nowhere for the class prop to go. But that makes no sense.

**Comment by hzoo** [comment]
With `babel src -d lib`, Also getting
```
SyntaxError: src/elements/types/utils/ElementSearchIndex.js: Missing class properties transform.
  72 |     }
  73 |
> 74 |     _index: Object;
     |     ^
```

```js
{
  presets: ["es2015"],
  plugins: [
    "transform-class-properties",
    "transform-flow-strip-types",
    "transform-object-rest-spread"
  ]
}
```

and @shuhei 's suggestion of

```js
{
  presets: [
    {
      plugins: [
        "transform-class-properties",
        "transform-flow-strip-types",
        "transform-object-rest-spread"
      ]
    },
    "es2015"
  ]
}
```
works

**Comment by sunjay** [comment]
@hzoo +1 Thanks. your solution works -- this should be in the docs somewhere. Took a very long time to find this.

**Comment by mfrye-intuit** [comment]
+1 This works for me too.

**Comment by sebmck** [comment]
Since 6.0.17, existing plugins in your `.babelrc` will take precedence meaning you don't need to resort to any hacks as @hzoo suggests.

**Comment by hzoo** [comment]
:+1: Thanks @sebmck

**Comment by elado** [comment]
Still happens to me with `6.1.4`

```json
{ "presets": ["es2015", "stage-0"] }
```

Source:

```js
class X extends Base {
  state = {}
  // constructor(...args) { super(...args) } // works if this line is uncommented
}
```

Tried adding `transform-class-properties` to plugins, didn't help (it's included in `stage-0` anyway).

`package.json`

```json
  "devDependencies": {
    "babel-core": "^6.1.4",
    "babel-plugin-transform-runtime": "^6.1.4",
    "babel-preset-es2015": "^6.1.4",
    "babel-preset-react": "^6.1.4",
    "babel-preset-stage-0": "^6.1.2",
    "babel-runtime": "^6.1.4",
  }
```

**Comment by hzoo** [comment]
What's the error you are getting? Otherwise it looks like https://github.com/babel/babel/issues/2775 - fixed in master https://github.com/babel/babel/commit/f91cfa68b93fb761c38e83ea8e335f401aec096c

**Comment by elado** [comment]
@hzoo getting same error,

`SyntaxError: a.js: 'super.*' is not allowed before super() (This is an error on an internal node. Probably an internal error)`

I can confirm that that fix works (changed manually `node_modules/babel-plugin-transform-es2015-spread/lib/index.js` to see). Hopefully it makes it to npm soon.

Thank you and @sebmck!
