### ISSUE TITLE
Babel 5.0 doc site?

### ISSUE THREAD

**Issue by eranimo** [babel/babel#2689]
My organization is unable to upgrade to Babel 6 for a while. It would be nice to have the old docsite up at a different url so that people using older versions of Babel can make use of the docs.

**Comment by sebmck** [comment]
See the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by sebmck** [comment]
Also a duplicate of #2680.
