### ISSUE TITLE
babel-cli doesn't transpile anything

### ISSUE THREAD

**Issue by denysdovhan** [babel/babel#2692]
I use [generator-tiny-es-nm](https://github.com/iamstarkov/generator-tiny-es-nm) by @iamstarkov. It has `"babel": "*"` dep and transpile `index.js` through:
```json
"transpile": "babel index.js --out-file index.es5.js"
```
Well, I know, after 6.0 there is `babel-cli` package, but if I install `babel-cli` and then run `npm run transpile`, it doesn't transpile anything. It just create new file and copy its content:

_index.js_
```
import pkg from './package'

console.log(pkg.version);
```
_index.es5.js_
```
import pkg from './package';

console.log(pkg.version);
```

So, I still use `babel@^5` and don't understand what's going on. Is that my mistake or whatever?

**Comment by loganfsmyth** [comment]
@denysdovhan http://stackoverflow.com/questions/33440405/compilation-problems-with-babel should explain.

In the future, please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by denysdovhan** [comment]
@loganfsmyth right. Sorry, that's my mistake.
