### ISSUE TITLE
Error when default exporting a decorated class

### ISSUE THREAD

**Issue by JacksonGariety** [babel/babel#2702]
This works as expected:

```javascript
@fooDecorator
export class Foo {...}
```

This does not:

```javascript
@fooDecorator
export default class Foo {...}
```

The error thrown is:

```
Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "Decorator"
```

The latter snippet is valid es7 syntax right now, right?

**Comment by eelkeh** [comment]
Might be related, with:
```javascript
function decorator(cls) {
  return cls;
}

@decorator
class B {
  constructor() {
    return;
  }
}
```
and `babel --presets stage-0 test.js` seems to be throwing the same error.

**Comment by JacksonGariety** [comment]
@eelkeh I am using the `es2015` and `react` presets and most of the plugins in stage 0 but not all.

**Comment by hzoo** [comment]
Not sure if it's the same exact issue but decorators are not working atm https://github.com/babel/babel/issues/2645

**Comment by eelkeh** [comment]
@JacksonGariety yes I guess I still need the `es2015` preset, with `babel --presets es2015,stage-0 test.js` and `export default class` I get the same error.

**Comment by jaylaw81** [comment]
Any update on this? I'm seeing this error as well.

**Comment by resistdesign** [comment]
Same issue here with decorated classes.

```
"devDependencies": {
    "babel-core": "^6.1.2",
    "babel-preset-stage-0": "^6.1.2"
  }
```

**Comment by diegoddox** [comment]
Same for me.

```
"devDependencies": {
    "babel-core": "^6.1.4",
    "babel-preset-stage-0": "^6.1.2",
  }
```

**Comment by alexbeletsky** [comment]
Same for me.

```
  "devDependencies": {
    "babel-core": "^6.1.2",
    "babel-preset-es2015": "^6.1.2",
    "babel-preset-react": "^6.1.2",
    "babel-preset-stage-0": "^6.1.2",
```

**Comment by geekyme** [comment]
same for me

```
    "babel-cli": "6.1.4",
    "babel-core": "6.1.4",
    "babel-loader": "6.1.0",
    "babel-preset-es2015": "6.1.4",
    "babel-preset-react": "6.1.4",
    "babel-preset-stage-0": "6.1.2",
    "babel-runtime": "6.0.14",
```

**Comment by khankuan** [comment]
+1

**Comment by pavelbinar** [comment]
+1

**Comment by dpwrussell** [comment]
+1

**Comment by rzschoch** [comment]
+1

**Comment by rthewhite** [comment]
+1

**Comment by LookLikeAPro** [comment]
+ 1

**Comment by ChrisCinelli** [comment]
Is this a general problem with Babel 6, or just an edge case using the decorator before `export` ?

I started getting:

      npm WARN deprecated babel-core@5.8.29: Babel 5 is no longer being maintained. Upgrade to Babel 6.

**Comment by daiheitan** [comment]
+1

**Comment by wizhippo** [comment]
+1

**Comment by shuhei** [comment]
Please stop `+1`ing. I want only meaningful updates.

**Comment by daiheitan** [comment]
I think this is related to #2645 , just have to wait for the Decorator fix.

**Comment by f3rno** [comment]
+1
