### ISSUE TITLE
Transforming czech characters

### ISSUE THREAD

**Issue by Huvik** [babel/babel#2704]
Hey, there is problem with transforming some czech characters. I saw topic with cyrilic strings and characters normalization i think is same problem here. https://github.com/babel/babel/issues/247 
`var name = 'Lukáš';`
->
`var name = 'Luk��';`

**Comment by loganfsmyth** [comment]
This seems to work for me, but it's hard to tell what the issue is. Could you perhaps make a demo repo to reproduce the issue? If

**Comment by Huvik** [comment]
I have UTF8 encoding and there is my czech strings in my repo: https://github.com/Huvik/InstagramScroll/blob/master/reducers/reducers.js

**Comment by Mark-Simulacrum** [comment]
I cannot reproduce this issue either. Can you tell us what version of babel you are using?

**Comment by Huvik** [comment]
its in package.json in repo, you can try clone repo and reproduce it i was trying it and it works how i said. i dont know maybe its problem on my end somehow

**Comment by Mark-Simulacrum** [comment]
I cannot reproduce this error. Can you try producing a smaller example (reduced test case) that still does this for you?

If you have a tool like `xxd` which shows the hexdump of a file/string, it might be helpful to compare the bytes in `'Lukáš'` with the bytes in `'Luk��'`, to see if there is a difference in the raw content, or if it is a display error. This would be a lot simpler if there was a smaller reproducible example.

**Comment by Huvik** [comment]
Ok, sorry i had bad meta tag in my html file so javascript was correct.
