### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by TheDeveloperXYZ** [babel/babel#2705]
I updated to latest babelify along babel and now I am getting this error:
`ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

.babelrc looks like this:
```javascript
{
    "presets": ["stage-0", "react"]
}
```
Now, when I replace "stage-0" with "es2015". The error disappears, however ES7 features are not there and thus produce syntax errors.

Any ideas, why using "stage-0" throw such error?

**Comment by hzoo** [comment]
stage-0 only adds stage 0 and higher so you still need the `es2015` preset

**Comment by TheDeveloperXYZ** [comment]
```javascript
{
  "presets": ["es2015", "stage-0", "react"]
}
```

Okay, now it works but class properties do not work when they should as it throws errors:
`Missing class properties transform`

It is react components where the class properties are used:
```javascript
class Frame extends Component {
  static propTypes = {
    title: PropTypes.string
  }

  static defaultProps = {
    title: 'Page Title'
  }
}
```

It is not hard to move that code to prototype but according to http://babeljs.io/docs/plugins/preset-stage-1/ the class properties transform is included.

**Comment by hzoo** [comment]
That's a seperate issue now https://github.com/babel/babel/issues/2688

**Comment by TheDeveloperXYZ** [comment]
Yes indeed.

This issue can be closed now.
