### ISSUE TITLE
babel-6 not finding presets 

### ISSUE THREAD

**Issue by MohhamedRafi** [babel/babel#2707]
This is weird. I am using babel-core@6.0.14 and for some reason it not registering the code .

```
/home/mohhamed/Documents/github/elements/generator-elements/generators/app/generator.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at loader (/home/mohhamed/Documents/github/elements/generator-elements/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mohhamed/Documents/github/elements/generator-elements/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mohhamed/Documents/github/elements/generator-elements/generators/app/index.js:5:28)
    at Module._compile (module.js:434:26)

```

**Comment by hzoo** [comment]
What is your `.babelrc` like? Did you add the es2015 preset? http://babeljs.io/blog/2015/10/29/6.0.0/#plugin-presets

```js
{
  "presets": ["es2015"]
}
```

**Comment by MohhamedRafi** [comment]
Thank you for the speedy response.  But now I am getting that it could not find the preset for some reason. I installed it but it not being found.

**Comment by divmgl** [comment]
To everyone who is having problems using `babel/register` in their configs, the Babel.js folks have made some pretty big breaking changes.

You will need some extra packages. 
```
$ npm install --save-dev babel-core
$ npm install --save-dev babel-preset-es2015
```

You will need to create a `.babelrc` file in your folder with this content:

```
{
  "presets": ["es2015"]
}
```

You will need to start your server with `babel-core` rather than `babel`.

```
$ node -r babel-core/register . # Replace the . with your script name
```

**Comment by MohhamedRafi** [comment]
I have babel-core and register. It still does not work with babel-core.

**Comment by Mark-Simulacrum** [comment]
How are you executing the file? How are you "registering" (`import`, `require`, `node -r babel-core/register`, etc.) `babel`?

**Comment by MohhamedRafi** [comment]
```javascript
require('babel-core/regster');

exports = module.exports = require('./generator');
```

I using this in a index file that exports a yeoman generator.

**Comment by Mark-Simulacrum** [comment]
It appears that the call to require `babel-core/register` is misspelled. To eliminate the possibility that this is the cause, can you confirm that the code you are running does not contain this misspelling (should be `require('babel-core/register')`)?

**Comment by MohhamedRafi** [comment]
Sorry yes I can confirm the code is not misspelled.

**Comment by divmgl** [comment]
Any luck @MohhamedRafi? I've got it working on my end. Are you still receiving the same error?

**Comment by MohhamedRafi** [comment]
@divmgl Yeah setting getting the not found error. I going create a repo and see if you guys can recreate the error.

**Comment by Mark-Simulacrum** [comment]
Can you create a smaller repository that still has the "not found" error?
From my testing with your repository, everything seems to work, except for Babel not being able to compile class extends (see #2700).

How are you running `babel`?
What `npm` and `node` versions are you using?

**Comment by MohhamedRafi** [comment]
Node v4.1.1 and Npm 2.14.4. Can you explain how you test it? It might help me. Also this a yeoman generator so when I tested with yo it calls the index.js file that has babel-core/register.

**Comment by MohhamedRafi** [comment]
Updated on the issue I updated to latest node and npm version which node v5 and npm v3 to see if the issue still is there.

**Comment by Mark-Simulacrum** [comment]
I run it using `node generators/app/generators.js`; and I do get an error, but not the error regarding the preset not being found. Can you tell me what `npm ls --depth 0` returns?

**Comment by MohhamedRafi** [comment]
Oh the way I test it was node  generators/app/index.js and npm ls --depth 0 it returns 

```
generator-elements@0.0.0 /home/mohhamed/Documents/github/elements/generator-elements
├── babel-core@6.0.14
├── babel-preset-es2015@6.0.14
├── babel-preset-stage-0@6.0.14
├── chalk@1.1.1
├── mocha@2.3.3
├── yeoman-generator@0.19.2
└── yosay@1.0.5

```

**Comment by MohhamedRafi** [comment]
@Mark-Simulacrum I have created a mini express server test and it seems like it working now (Node v5 and npm v3). The preset not found issue seems to lie in yeoman rather then babel so for now I am closing the issue.
