### ISSUE TITLE
Babel 6 doesn't handle destructuring of imports

### ISSUE THREAD

**Issue by aommm** [babel/babel#2709]
I have problems with babel-node when running Babel 6 on Windows 8.

I have installled `babel`, `babel-cli`, `babel-preset-es2015`, and added `{"presets": ["es2015"]}` both as a property in my project's `package.json` and to a new file I called `.babelrc`.

I can now evaluate things like `babel-node -e "class Test { }"`, but when I run `babel-node myScript.js` it fails.

__myScript.js__: `import { a } from './myScript2'` 
__myScript2.js__: `export default {a: "a"}`

My problem is that `a` always resolves to undefined in myScript.js above.

**Comment by loganfsmyth** [comment]
This is expected behavior. It used to work in Babel 5.x _some_ of the time, but it is not valid in ES6.

If you are importing via a name `{a}`, then you also need to export that name, e.g.

    export var a = "a";

You cannot export default object that contains that key.

Please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
