### ISSUE TITLE
How to define plugin settings in babel 6?

### ISSUE THREAD

**Issue by nkt** [babel/babel#2710]
For example for `async-to-module-method` plugin?
I've tried following, but it doesn't work.
```js
extra: {
  'transform-async-to-module-method': {
    module: 'bluebird',
    method: 'coroutine'
  }
}
```

**Comment by loganfsmyth** [comment]
Please check our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by nkt** [comment]
@loganfsmyth ok, but I guess this should be in docs

**Comment by loganfsmyth** [comment]
I agree. Also from the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by hzoo** [comment]
I'l try making a PR

**Comment by nkt** [comment]
@loganfsmyth nope. There is no option for plugin settings: https://babeljs.io/docs/usage/options/

**Comment by loganfsmyth** [comment]
@nkt Sorry, all I was saying is that if there are issues with the documentation, you should open a issue in that repo. This repo just for bugs and features.

**Comment by nkt** [comment]
@loganfsmyth ah. My bad. Thanks for explanation.
