### ISSUE TITLE
transform-es2015-constants does not work without transform-es2015-block-scoping

### ISSUE THREAD

**Issue by tellnes** [babel/babel#2712]
`transform-es2015-constants` transforms `const` to `let` and `transform-es2015-block-scoping` transforms it to `var`.

Not a problem, but it should be documented if that is intentional.

**Comment by sebmck** [comment]
It's intentional. It's to retain correct semantics. Documentation issues should be reported in another repo, see the README for more information:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by tellnes** [comment]
But is it possible to mark it as a dependency so this will work:

```shell
babel --plugins transform-es2015-constants script.js
```

**Comment by hzoo** [comment]
@thejameskyle added docs for it https://github.com/babel/babel/commit/2957bd7f2be31f94ffe143cc620cba64bc4373c4
