### ISSUE TITLE
Should stage-x presets include es2015 preset?

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2713]
re: https://github.com/babel/babel/issues/2705#issuecomment-152734852

**Comment by chicoxyzzy** [comment]
not necessary IMO.

one can use Babel on es2015-compatible environment

**Comment by GGAlanSmithee** [comment]
Agree with @chicoxyzzy

**Comment by TheDeveloperXYZ** [comment]
I think it would be great to add into documentation, that you need to include es2015 with stage-x as well if you want to use ES2015 features.

**Comment by mjetek** [comment]
It also looks like order in which presets are specified matters. In my case when I put `"presets": ["es2015", "stage-0"]` it doesn't recognise syntax from `"stage-0"` but when I change it to `"presets": ["stage-0", "es2015"]` it works.

**Comment by thetalecrafter** [comment]
I would recommend against including it, since you may want to use [es2015-node5](https://www.npmjs.com/package/babel-preset-es2015-node5) or some other selective group of transforms.

**Comment by thejameskyle** [comment]
I've lost interest in doing this
