### ISSUE TITLE
`export from` is pushed to the top of the file, breaking polyfill `require`

### ISSUE THREAD

**Issue by brandonhorst** [babel/babel#2717]
If you're using the polyfill, you have to `require` it before you use anything that relies on it (like generators).

However, when using `export {test} from './somefile'` syntax, the generated `require('./somefile')` call is trust to the top of the file, above the polyfill `require`.

I have a reproduction. Just clone https://github.com/brandonhorst/babel-polyfill-bug, then run `npm install && npm test`.

Basically, compiling

```js
console.log('before polyfill')
require('babel-polyfill')
console.log('between polyfill and import')
export {test} from './somefile'
console.log('after import')
```

results in

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _somefile = require('./somefile');

Object.defineProperty(exports, 'test', {
  enumerable: true,
  get: function get() {
    return _somefile.test;
  }
});
console.log('before polyfill');
require('babel-polyfill');
console.log('between polyfill and import');
console.log('after import');
```

Because `require('./somefile);` comes before `require('babel-polyfill');`, and `./somefile` uses generators, it throws

```
ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (/private/tmp/babel-polyfill-bug/lib/somefile.js:8:26)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/private/tmp/babel-polyfill-bug/lib/index.js:7:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
npm ERR! Test failed.  See above for more details.
```

Version Info

```
babel-polyfill-bug> node -v                                                                                                                           
v5.0.0
babel-polyfill-bug> npm -v                                                                                                                            
3.3.6
babel-polyfill-bug> cat package.json                                                                                                                  
{
  "name": "babel-polyfill-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "babel src --out-dir lib --presets es2015 && node lib/index.js"
  },
  "author": "@brandonhorst",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.0.14",
    "babel-preset-es2015": "^6.0.14"
  },
  "dependencies": {
    "babel-polyfill": "^6.0.14"
  }
}
```

**Comment by loganfsmyth** [comment]
This is expected behavior. ES6 module syntax is processed before the body of the module has executed, so this is what you'd get if this were real ES6 code.

For now, it is recommended that applications have a standalone entry point in ES5 that ensures the polyfill has loaded before loading the application, e.g.

    import 'babel-polyfill';
    import './app';

or that the polyfill be loaded via preloading

    node -r babel-polyfill app.js

if your Node version supports `-r`, (which 5.x does).

**Comment by brandonhorst** [comment]
That kinda sorta makes sense. But I don't have an app, I'm writing a library, and I want to be able to compile it to run in plain JS (node or Browserify). `-r` won't work either for this use case.

I have an "entry point" that looks something like this:

```js
import 'babel-polyfill'
export {default as Parser} from './parser'
export {default as Analytics} from './analytics'
/* ... */
```

What's the recommended way to handle this?

**Comment by loganfsmyth** [comment]
Libraries should not globally pollute their execution environment by loading the polyfill. The recommended method for libraries is to enable 

     "plugins": ["transform-runtime"]

and

     npm install --save babel-runtime
     npm install --save-dev babel-plugin-transform-runtime

This transformation will look for usage of global ES6 methods and replace them with explicit imports from a polyfill.

Please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

If you have further questions, feel free to ask them in Slack.
