### ISSUE TITLE
(Babel 6) `babel-plugin-transform-es2015-modules-commonjs` depends on `babel-plugin-transform-strict-mode`, causing problems in Node 5

### ISSUE THREAD

**Issue by timmolendijk** [babel/babel#2720]
It is unclear to me why (in Babel 6) the CommonJS module transform plugin enforces strict mode, because I don't see how the two are related.

On the contrary; they are potentially conflicting: strict mode is ES5, and some platforms actively complain when using native ES6 features alongside a `"use strict";` statement.

In my case I am using Node 5, which offers many ES6 features out of the box, such as `const`. So I don't want to transpile `const`, but I _do_ want to transpile ES6 module syntax into CommonJS. This is currently not possible, because Node 5 won't accept ES6 features such as `const` alongside `"use strict";` and strict mode cannot be disabled on its own.

Gridlock. I'd suggest simply getting rid of the strict mode dependency in the CommonJS transform plugin(?)

Also see [here](http://kangax.github.io/jstests/var-let-const/) for some related findings. The error message from Chrome 35, second row is exactly the one Node 5 is giving me as well.

**Comment by timmolendijk** [comment]
I'm running into [contradictory information](https://nodejs.org/en/docs/es6/#ref-1) about what strict mode means exactly in the context of ES6. It looks like v8 is just acting very inconsistently around the subject.

**Comment by matthiasak** [comment]
I'm not certain, but perhaps it is being used to explicitly allow only the values placed on `module.exports` to be exposed in a concatenated file: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Simplifying_variable_uses

**Comment by loganfsmyth** [comment]
I'm not sure what you mean by

> This is currently not possible, because Node 5 won't accept ES6 features such as const alongside "use strict";

If you are using V8's native `const` you absolutely want `use strict` enabled.

```
(function(){
  "use strict";
  const  foo = 4;
})();
```
works perfectly in Chrome and Node 5.

This essentially comes down to rules of ES6. Here's the spec: http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

ES6 defines two types of parsing/execution rules.

* Script
* Module

ES6 import/export syntax is only allowed in Modules, and Modules are required to be in Strict mode, hence the line in the spec above:

> Module code is always strict mode code.

**Comment by sebmck** [comment]
This is expected behaviour. ES2015 modules have an implicit strict mode.

**Comment by timmolendijk** [comment]
I can't reproduce this myself anymore. Strange. Will return here with more specific example in case it returns. Thanks folks!
