### ISSUE TITLE
Async function arguments are lost

### ISSUE THREAD

**Issue by optimistiks** [babel/babel#2725]
For some reason, this code

```
export const signUp = (username, password) => {

    return async function (dispatch, getState) {

        // do something with dispatch and getState
        
    };
};
```

gets transpiled into this

```
var signUp = exports.signUp = function signUp(username, password) {

	    return function () {
	        var _this = this;

            // arguments here contain dispatch and getState, but they are not being passed to the original function

	        return _asyncToGenerator(regeneratorRuntime.mark(function _callee(dispatch, getState) {
	            return regeneratorRuntime.wrap(function _callee$(_context) {
	                while (1) switch (_context.prev = _context.next) {
	                    case 0:

	                        // do something with dispatch and getState

	                    case 1:
	                    case "end":
	                        return _context.stop();
	                }
	            }, _callee, _this);
	        }))();
	    };
	};
```

As a result, ```dispatch``` and ```getState``` are undefined inside the function.

I use ```"babel-loader": "^6.0.0"```, ```presets: ['es2015', 'react', 'stage-1']``` and ```babel-polyfill```

**Comment by loganfsmyth** [comment]
Can you make sure you are on the most recent version of everything? I believe this was fixed in `6.0.15`.

**Comment by johngeorgewright** [comment]
Has `6.0.15` been released?

**Comment by sebmck** [comment]
Is now.

On Sun, Nov 1, 2015 at 9:50 PM, John Wright <notifications@github.com>
wrote:

> Has 6.0.15 been released?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2725#issuecomment-152868276>.
>



-- 
Sebastian McKenzie

**Comment by loganfsmyth** [comment]
(yeah my bad :P)
