### ISSUE TITLE
(6.0) transform-runtime doesn't work for helpers

### ISSUE THREAD

**Issue by yyx990803** [babel/babel#2726]
Reproduction: https://github.com/yyx990803/babel-6-runtime-repro

``` js
var babel = require('babel-core')

var code = babel.transform('class Test {}', {
  plugins: [
    'transform-runtime',
    'transform-es2015-classes'
  ]
}).code

console.log(code)
```

Expected the `_classCallCheck` to be using the runtime version, but it's still inlined:

``` js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

let Test = function Test() {
  _classCallCheck(this, Test);
};
```

**Comment by yyx990803** [comment]
Upon further testing, it seems currently only language polyfills in `core-js` are transformed, but not any `babel-runtime` helpers.

**Comment by loganfsmyth** [comment]
Confirmed. [this line](https://github.com/babel/babel/blob/9702ceb07476d9bf0da5eed8e236af8bd45ae8b3/packages/babel-plugin-transform-runtime/src/index.js#L12)

    state.set("helperGenerator", function (name) {

should be

    state.file.set("helperGenerator", function (name) {

I believe. But there's another issue that exposes

    class Example {}

then becomes

```
"use strict";

import _interopRequireDefault from "babel-runtime/helpers/interopRequireDefault";

var _classCallCheck2 = require("babel-runtime/helpers/classCallCheck");

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var Example = function Example() {
  (0, _classCallCheck3.default)(this, Example);
};
```

seems like there may be a circular dependency issue for `interopRequireDefault` ?

**Comment by dgreensp** [comment]
I ran into this bug, and I also just filed #2731, which seems related (in that `transform-runtime` ends up not doing what it's supposed to do) and may offer some clues.
