### ISSUE TITLE
Weird export default behavior in babel-node

### ISSUE THREAD

**Issue by devongovett** [babel/babel#2728]
Input file:

```javascript
export default class Resolver {
  constructor(options = {}) {
    this.options = options;
  }
}

console.log(Resolver.toString())
```

Output from `babel-node resolver.js`

```javascript
function Resolver(_x) {
  _classCallCheck(this, Resolver);

  this.options = options;
}
```

`options` is never defined in the constructor.

With just `export` instead of `export default`, it is correct:

```javascript
function Resolver() {
  var options = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

  _classCallCheck(this, Resolver);

  this.options = options;
}
```

When compiled with `babel`, and then run using `node` instead of using `babel-node` directly, it works even with `export default` (same output as above).

The same thing happens with the `babel-core/register` hook.

**Comment by deoxxa** [comment]
Yup, same deal here. I came across this when my tests (using `babel-core/require`) broke after upgrading from 5.x to 6.x. Perhaps some config isn't making its way through the `register` mechanics properly?

**Comment by deoxxa** [comment]
Confirmed this is a regression in 6.x. I just moved back to 5.x and all is well.

**Comment by devongovett** [comment]
Did a little digging in the code, and figured out that the `ClassDeclaration` [visitor](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-classes/src/index.js#L8-L19) in the class transform is called twice, even though the node is a `ClassExpression` the second time. The `ClassDeclaration` visitor converts the node to a `ClassExpression` the first time, but for some reason when the node is revisited after being replaced, the `ClassDeclaration` visitor is still called, instead of the `ClassExpression` one.

If I add `if (!path.isClassDeclaration()) return;` to the `ClassDeclaration` visitor, the problem goes away. Printing `path.type` within the visitor outputs `ClassDeclaration` both times, where `path.node.type` switches to `ClassExpression`. Manually overriding `path.type` before the replacement still does not fix it though. My guess is that some other internal cache is keeping the old node type around, so when it is revisited the `ClassDeclaration` visitor is called instead of `ClassExpression`.

I'll keep looking, but I thought I'd try to explain what I found so far so that others more familiar with the code might have an idea.
