### ISSUE TITLE
Error: Missing class properties transform.

### ISSUE THREAD

**Issue by kiki-le-singe** [babel/babel#2729]
Hello,

I get this error message in my terminal: 
Module build failed: SyntaxError: /path/.../.../projectName/src/components/myComponent.jsx: Missing class properties transform.

```javasctipt
 class MyComponent extends Component {
>  handleChange = (e) => {
   ^
      // My code here ...
   }

  ...
}
```

I use webpack:

```javascript
    loaders: [
      {
        test: /\.js[x]?$/,
        loaders: ['react-hot', 'babel?presets[]=es2015,presets[]=react,presets[]=stage-0&cacheDirectory', 'eslint'],
        exclude: /node_modules/
      },
      ...
   ]
```

package.json:

```javascript
  "devDependencies": {
    "babel-core": "^6.0.15",
    "babel-loader": "^6.0.0",
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-react": "^6.0.15",
    "babel-preset-stage-0": "^6.0.15",
    ...
  }
```

Thanks for your help

**Comment by shuhei** [comment]
The order of plugins matters. What if it's react, stage-0, es2015 or stage-0, react, es2015?

**Comment by kiki-le-singe** [comment]
Ok thanks I have tried but it doesn't work. I get this error:
Module build failed: TypeError: /path/.../src/components/MyComponent.jsx: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "Decorator"

**Comment by shuhei** [comment]
Ah, decorators are currently broken. https://github.com/babel/babel/issues/2645

**Comment by kiki-le-singe** [comment]
hum ok. I'll wait patiently that it be fixed.
Thanks :)

**Comment by hzoo** [comment]
Ok closing since it's the other issue

**Comment by optimistiks** [comment]
I ran into this issue as well.

ERROR in ./src/common/components/App/App.jsx
Module build failed: SyntaxError: /path.../src/common/components/App/App.jsx: Missing class properties transform.

```
  4 | class App extends React.Component {
  5 | 
> 6 |     contextTypes = {
    |     ^
  7 |         history: React.PropTypes.object
  8 |     };
  9 | 
```

Run npm update, got the latest version of everything.

Settings:

```
{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel',
                query: {presets: ['react', 'stage-0', 'es2015'], cacheDirectory: true}
}
```

I tried to play with preset ordering, but with no effect.

**Comment by MacgyverMartins** [comment]
Some problem here.
I build an app with babelify.
My code:
```javascript
class Home extends React.Component {
  state = {
    loopsRemaining: 1,
  }

  render() {
    return (
      <div>
        <p>{this.state.numbers}</p>
      </div>
    );
  }
}
```

And in my gulpfile, the task is:
```javascript
...
    browserify({
        entries: [filePath],
        extensions: extensions,
        debug: env === 'dev'
      })
      .transform("babelify", {
        presets: [
          { plugins: ["syntax-class-properties"] },
          "es2015",
          "react"
        ]
      })
      .bundle()
...
```

Sorry my bad english

**Comment by hzoo** [comment]
added to the docs: http://babeljs.io/docs/plugins/#pluginpreset-ordering

**Comment by hdngr** [comment]
This is broken again in babel 7...

.babelrc:
```
{
  "presets": [
    "@babel/es2015",
    "@babel/react",
    "@babel/stage-0"
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true,
      "moduleName": "@babel/runtime"
    }],
    ["@babel/plugin-transform-classes", { "spec": true }]
  ]
}

```

**Comment by loganfsmyth** [comment]
@hdngr How are you calling Babel? `babel-loader`? The CLI? Do you happen to have any config options anywhere else?

On an unrelated note, mind if I ask why you're passing `regenerator: true` and `moduleName: "@babel/runtime"`? Those are the default values, so passing them is potentially extra noise in your config.

**Comment by hdngr** [comment]
@loganfsmyth migrating from earlier version of babel, and using `babel-register` before calling server (node environment).

Thanks for pointing that out.  I've left it in so I can more easily get to the bottom of whatever is going on.

**Comment by rsolomon** [comment]
@hdngr you're using the wrong plugin, at least for the error referred to in this thread (`Missing class properties transform.`). You should be using `@babel/plugin-proposal-class-properties`
