### ISSUE TITLE
Async function reordering

### ISSUE THREAD

**Issue by eknkc** [babel/babel#2730]
On **6.0.15**;

With `transform-async-to-generator` babel seems to reorder async functions and place them at the top of output file:

```js
// Input

function a() {}

async function b() {
  await c();
}

async function c() {}
```

```js
// Output

let b = (function () {
  var ref = _asyncToGenerator(function* b() {
    yield c();
  });

  return function b() {
    return ref.apply(this, arguments);
  };
})();

let c = (function () {
  var ref = _asyncToGenerator(function* c() {});

  return function c() {
    return ref.apply(this, arguments);
  };
})();

function _asyncToGenerator(fn) { ... }

function a() {}
```

While this does not break anything, I think there is an issue with function `b` calling `let c` before c is declared. Is this intentional for a reason that I could not catch?

Thanks.

**Comment by eknkc** [comment]
I believe it should look more like this:

```js
function _asyncToGenerator(fn) { ... }

function a() {}

let _b = _asyncToGenerator(function* b() {
  yield c();
});

function b() {
  return _b.apply(this, arguments);
}

let _c = _asyncToGenerator(function* c() {});

function c() {
  return _c.apply(this, arguments);
}
```

**Comment by fkling** [comment]
Function declarations are hoisted. At the moment `b` calls `c`, `c` has a value.

**Comment by sebmck** [comment]
Closing as this is a non-issue. @fkling is correct and there are no runtime consequences to this hoisting.

**Comment by Kovensky** [comment]
This also affects cases where code tries to `import 'babel-runtime'`, which will also cause a runtime crash if using `transform-regenerator`.

[Sample in the REPL](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=latest&code=%2F%2F%20should%20always%2C%20definitely%2C%20run%20before%20any%20of%20the%20other%20code%20in%20the%20module%0D%0Aimport%20'babel-polyfill'%0D%0A%0D%0A%2F%2F%20generator%20function%20stays%20where%20it%20is%0D%0Afunction%20*%20bar%20()%20%7B%7D%0D%0A%0D%0A%2F%2F%20the%20async%20function%20definition%20IIFE%20is%20hoisted%20higher%20than%20the%20imports!%3F%0D%0Aasync%20function%20foo%20()%20%7B%7D%0D%0A%2F%2F%20normally%20that%20wouldn't%20be%20an%20actual%20problem%2C%0D%0A%2F%2F%20but%20it%20will%20crash%20if%20babel-polyfill%20doesn't%20run%20first%0D%0A%0D%0A%2F%2F%20adding%20an%20export%20doesn't%20help%20either%0D%0Aexport%20%7Bfoo%2C%20bar%7D%0D%0A).

**Comment by danharper** [comment]
Closing in favour of #4107. Current recommendation is:

> Have a separate entry point that loads the polyfill, and then the main application file.

**Comment by xialvjun** [comment]
Maybe **wrap the async function in an autorun function is a better way**

change
```
import 'babel-polyfill'
async function foo() {}
module.exports = foo
```
to
```
import 'babel-polyfill'
function foo() {
  return (async function(){})()
}
module.exports = foo
```
