### ISSUE TITLE
Object destructuring assignment for object extension not working

### ISSUE THREAD

**Issue by davegomez** [babel/babel#2732]
I have a code where I use computed property keys and destructuring assignment to extend some objects inside a for loop that work fine with Babel v5.8.29 but fails when I try to compile it with it.

This is the error I'm getting from Babel:

```
SyntaxError: Development/personal/grid/src/base-column.js: Unexpected token (21:12)
  19 |         if (index === 0) {
  20 |           properties[`.col-${bp}`] = {
> 21 |             ...col
     |             ^
  22 |           };
  23 |         } else {
  24 |           properties[`.col-${bp}-${index}`] = {
```

**Comment by hzoo** [comment]
Are you saying it was working with babel 5 and not with babel 6 or is this with babel 5 still? That syntax looks like object rest spread (http://babeljs.io/docs/plugins/transform-object-rest-spread/ for babel 6)

**Comment by davegomez** [comment]
It is working with Babel 5 even in the website REPL, but is not working with Babel 6, it throws that error I posted.

**Comment by hzoo** [comment]
Ok great what is your `.babelrc` like? Do you know about the changes made in babel 6? http://babeljs.io/blog/2015/10/31/setting-up-babel-6/ - I also mentioned the plugin above.

**Comment by loganfsmyth** [comment]
Object rest/spread is stage 2, so it would have been enabled by default in the most recent Babel 5.x. In 6.x you'll need to explicitly enable it or all stage 2.

**Comment by davegomez** [comment]
Thanks!
