### ISSUE TITLE
babel plugin transform minify booleans doesn't work

### ISSUE THREAD

**Issue by Eschon** [babel/babel#2736]
I updated to babel 6.0.0 and the plugins that I was using. When I transformed my code I noticed that my booleans no longer get minified.
I made sure that I have the right version of the plugin installed and that it is in the plugin configuration of my `.babelrc`. I get no error message, it just doesn't minify my booleans anymore.

Let me know if you need any additional information regarding this issue.

**Comment by thejameskyle** [comment]
Please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

If you have further questions, feel free to ask them in Slack.

**Comment by Eschon** [comment]
The plugin is part of this repository and does not work.
Doesn't this count as a bug report?

**Comment by thejameskyle** [comment]
Sorry, we have to go through lots of tickets. If something sounds like someone just doesn't know how to configure Babel we just close it right away. The fix is in #2737

**Comment by Eschon** [comment]
Understandable.
Thank you for looking into this.

**Comment by Eschon** [comment]
Ok I now updated the plugin and it still doesn't work for me.
With the plugin enabled I now get the following error:

```
Running "babel:main" (babel) task
Warning: ./tmp/skimap.js: t.numericLiteral is not a function Use --force to continue.
```

Should this issue be reopened or should I open a new one?

**Comment by thejameskyle** [comment]
There's already been several issues about that, and you just need to update. We're going through a lot of fixes right now, if something isn't working just keep updating to latest before anything else
