### ISSUE TITLE
Babel 6. Assertion error

### ISSUE THREAD

**Issue by ErrorPro** [babel/babel#2738]
Hello everybody. I got this error: 
```
AssertionError: app/models/note.js: false == true
    at explodeViaTempVar (/home/htk/projects/highrise/src/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:926:12)
```

my babel.rc looks: 

``` 
{
  "presets": ["es2015", "stage-0"]
}
```

What's the problem?

**Comment by thejameskyle** [comment]
Please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

If you have further questions, feel free to ask them in Slack.
