### ISSUE TITLE
babel-node not work using example in Document

### ISSUE THREAD

**Issue by javie007** [babel/babel#2739]
When I run the code in [Docs](http://babeljs.io/docs/usage/cli/):
```javascript
babel-node --debug --stage 0 -- script.js --debug
```
It prompts:
```
Error: Cannot find module '/Users/qqq/Documents/workspace/test/0'
```

**Comment by thejameskyle** [comment]
Out of date documentation issue. Please file an issue over in the [website repo](https://github.com/babel/babel.github.io).

If you have further questions, feel free to ask them in [Slack community](https://slack.babeljs.io) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
