### ISSUE TITLE
Add examples to each of the plugins

### ISSUE THREAD

**Issue by romeovs** [babel/babel#2740]
I really like how babel 6.0 makes babel a lot mor general-purpose! I'm moving some of my projects over to use the new version and this has been a breeze so for (the `presets` thing was a good call).

However, I feel there's one thing that could reduce the friction (especially for new developers coming
to the babel community): have every plugin and transformer show an example of input and expected output source code, much like [`postcss` asks its plugin developers to do](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#42-include-input-and-output-examples).

Of course, with `postcss` this approach is needed more because a lot of plugins provide custom syntax on top of css (that isn't necessarily based on a standards proposal). I also realise that the output of some babel plugins and transformers is very hard to comprehend, but even then I think it would be nice to have
a good input example that show what kind of source code that plugin enables one to write.

**Comment by thejameskyle** [comment]
From the README:

> **Want to report an issue with [babeljs.io](https://babeljs.io)?**
> 
> For documentation and website issues please visit the [babel.github.io](https://github.com/babel/babel.github.io) repo.
