### ISSUE TITLE
JSX transformation pragma : Inconsistent documentation

### ISSUE THREAD

**Issue by the8tre** [babel/babel#2741]
The doc (http://babeljs.io/docs/plugins/transform-react-jsx/) states :
```json
{
    "plugins": [
        ["transform-react-jsx", { "jsxPragma": "dom" }]
    ]
}
```
But the transformer code does :
`var id = state.opts.pragma || "React.createElement";`

One of the them should be renamed to pragma or jsxPragma.

**Comment by thejameskyle** [comment]
From the README:

> **Want to report an issue with [babeljs.io](https://babeljs.io)?**
> 
> For documentation and website issues please visit the [babel.github.io](https://github.com/babel/babel.github.io) repo.
