### ISSUE TITLE
can not require a module with `export default`

### ISSUE THREAD

**Issue by gitawego** [babel/babel#2742]
for moduleA
```
class Test{}
export default Test;
```
this will be transpiled to 
```
export.default = Test;
```

and in moduleB, this code
```
import Test from './moduleA';
class Toto extends Test{}
```
will be transpiled to 
```
var Test = require('./moduleA');
var Toto = (function (_Test) {
  _inherits(Toto, _Test);
....
})(Test);
```
_Test could never pass the inherits check, because, it's an object but not a function. the ``import`` part should be transpiled to
```
var Test = require('./moduleA')['default'];

```

**Comment by lijunle** [comment]
Same here...

Looking to the changelog, find this is [breaking change](https://github.com/babel/babel/blob/master/CHANGELOG.md#600) on 6.0.0.

> Remove `module.exports` export interop for CommonJS module formatter.

**Comment by gitawego** [comment]
thanks for the info :)
I've figured out, but nice to know in a official way :)

**Comment by lijunle** [comment]
And related discussion #2683
