### ISSUE TITLE
babel-plugin-transform-runtime 6.0.16: Symbol is not defined in helpers/classCallCheck.js (Node 0.10)

### ISSUE THREAD

**Issue by benmosher** [babel/babel#2745]
My [Node 0.10 build](https://travis-ci.org/benmosher/eslint-plugin-import/jobs/88737228#L306) is failing due to Symbol being undefined down in `classCallCheck.js`. Succeeds on 0.12+ presumably because V8 defines `Symbol` since then.

Not a problem in `transform-runtime@6.0.2`.

I tried adding `external-helpers-2` as a shot in the dark; it seemed to fail more tests for the same reason.

**Comment by pascalduez** [comment]
I don't want to open yet another issue about `Symbol` so I'm plugging here:

Agreed that using "advanced" features like ` for .. of` requires a polyfill.

But just a "simple" `ìf (typeof foo === 'object')` breaks node 0.10 support.

Compiled result: 

```js
function _typeof(obj) { return obj && obj.constructor === Symbol ? "symbol" : typeof obj; }

if ((typeof map === 'undefined' ? 'undefined' : _typeof(map)) === 'object') _extends(maps, map);
```

**Comment by benmosher** [comment]
Ah, yeah, as additional clarification:

- none of the original source code refers to `Symbol` directly
- `.babelrc` is just: 

```json
{
  "presets": ["es2015"],
  "plugins": ["transform-runtime"]
}
```

**Comment by benmosher** [comment]
FWIW, I think [`_instanceof`](https://github.com/babel/babel/blob/31a6cb9c5750253f30a6d3db6e441e5bdb879499/packages/babel-helpers/src/helpers.js#L182) is actually what triggered my issue.

**Comment by benmosher** [comment]
I suspect `slicedToArray` and `slicedToArrayLoose` are also potentially triggering something similar, but I can't be sure. All the stack traces I dug into from my failed tests point to `_instanceof`.

**Comment by benmosher** [comment]
Would this be solved by setting up a preset that includes `transform-runtime`?

It seems like checking for the existence of `Symbol` is just a patch for a larger problem: shouldn't the presence of Symbol in the output code result in an injected `require` of the `Symbol` polyfill?

Or: is there an execution ordering problem where the `runtime` transform has no opportunity to transform the injected helpers?

**Comment by tschaub** [comment]
> FWIW, I think _instanceof is actually what triggered my issue.

```
$ echo 'foo instanceof Bar' | babel --presets es2015
"use strict";

function _instanceof(left, right) { if (right != null && right[Symbol.hasInstance]) { return right[Symbol.hasInstance](left); } else { return left instanceof right; } }

_instanceof(foo, Bar);
```

See also babel/babel.github.io#491.  It is not clear to me whether this is a documentation issue or unexpected behavior.

**Comment by loganfsmyth** [comment]
@tschaub If you're still having issues with a separate helper, it'd be better to file a new issue rather than commenting on a closed one.

**Comment by tschaub** [comment]
@loganfsmyth see #2784.  This does for `instanceof` what 31a6cb9c5750253f30a6d3db6e441e5bdb879499 did for `typeof`.

**Comment by benmosher** [comment]
Also, upon reflection, I rescind all the thinking-out-loud about transform ordering--after some reflection and experimentation, I don't think it's relevant to this issue.

I _do_ think that #2784 fixes my issue. 😎 Thanks, @tschaub!

**Comment by kyriacos** [comment]
@tschaub Thanks i think #2784 fixes this issue. 

I'm getting a ```Uncaught ReferenceError: Symbol is not defined```. Only on our Jenkins build. Works fine locally.

**Comment by AgentME** [comment]
@benmosher 
```
{
  "presets": ["es2015"],
  "plugins": ["transform-runtime"]
}
```

The runtime transform should provide Symbol and allow es2015 features that require it to work. If you're getting the "Symbol is not defined" error while using the runtime transform, then I think something is wrong with the runtime transform.

**Comment by sebmck** [comment]
We should move the instanceof symbol stuff into a separate plugin.

On Tue, Nov 3, 2015 at 6:47 PM, Chris Cowan <notifications@github.com>
wrote:

> @benmosher <https://github.com/benmosher>
>
> {
>   "presets": ["es2015"],
>   "plugins": ["transform-runtime"]
> }
>
> The runtime transform should provide Symbol and allow es2015 features that
> require it to work. If you're getting the "Symbol is not defined" error
> while using the runtime transform, then I think something is wrong with the
> runtime transform.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2745#issuecomment-153451074>.
>



-- 
Sebastian McKenzie

**Comment by benmosher** [comment]
@AgentME so when I added `Symbol` to my original source, it was polyfilled _in the source module_ but the `instanceof` helper is in a separate module.

One possible solution: polyfill `Symbol` in the helper files? `classCallCheck.js` is the guy without a `Symbol` reference:
```
  5) default import foo from "./default-export";:
     ReferenceError: Symbol is not defined
      at _instanceof (node_modules/babel-runtime/helpers/classCallCheck.js:3:64)
```

Since this (and other external helpers) are bundled with the `babel-runtime` package, seems like it should be okay to add a polyfill line for `Symbol` where referenced.

**Comment by benmosher** [comment]
Also, seems okay to me that 
> 
```
$ echo 'foo instanceof Bar' | babel --presets es2015
"use strict";

> function _instanceof(left, right) { if (right != null && right[Symbol.hasInstance]) { return right[Symbol.hasInstance](left); } else { return left instanceof right; } }

> _instanceof(foo, Bar);
```

has no polyfill for `Symbol`; seems analogous to using `Map` or `Set` without the runtime transform (which currently leaves it up to the application/environment to polyfill, IIRC.)

And this would be fine, if the helper files had a `Symbol` polyfill:

```
➜  tmp  echo "foo instanceof bar" | $(npm bin)/babel --presets es2015 --plugins transform-runtime
"use strict";

var _instanceof2 = require("babel-runtime/helpers/instanceof");

var _instanceof3 = _interopRequireDefault(_instanceof2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

(0, _instanceof3.default)(foo, bar);
```
