### ISSUE TITLE
Loose option in Babel 6

### ISSUE THREAD

**Issue by ai** [babel/babel#2746]
Seems like `.babelrc` in babel 6 has no loose option. But looks like plugins still [use it](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-for-of/src/index.js#L98).

@sebmck How I can enable loose mode and maybe we need add it to docs?

**Comment by hzoo** [comment]
Oh @ai those look like plugin specific options. So like in http://babeljs.io/docs/plugins/#options you would specify loose per plugin instead of globally. 

Also in https://github.com/babel/babel/blob/80dfe05ffc21e84745ace8a05257579a11b3a4f9/CHANGELOG.md#600 

> Remove loose option in favor of plugin options.

**Comment by ai** [comment]
@hzoo how I can set this option for preset?

Also plugins miss this option docs.

**Comment by hzoo** [comment]
I don't think there's anyway to set the option for a preset (intentionally) so you will have to specify the plugins manually - and if they are missing docs can you make a issue in the babel.github.io repo?

**Comment by ai** [comment]
@hzoo will this code work:

```json
{
  "presets": ["es2015"],
  "plugins": [
    ["transform-es2015-for-of", { "loose": true }]
  ]
}
```

Can I set plugin option in this kind override?

**Comment by ai** [comment]
Done https://github.com/babel/babel.github.io/issues/532

**Comment by thejameskyle** [comment]
Thoughts on creating a loose preset? @babel/contributors?

**Comment by hzoo** [comment]
Sounds alright to me - same idea as creating the stage-x presets to replace "stage: x". So like `preset-es2015-loose`?

**Comment by thejameskyle** [comment]
Yeah, it's gonna be kinda weird to just start adding modifiers to every stage. For most of them I'd say no, but I'm certain someone else will create these exact packages and they'll be less well maintained.

```
babel-preset-stage-0-loose
babel-preset-stage-1-loose
babel-preset-stage-2-loose
babel-preset-stage-3-loose
babel-preset-stage-es2015-loose
babel-preset-stage-react-loose
```

**Comment by hzoo** [comment]
Oh but do the transformers in stage-x and react even use `ops.loose` though?

Yeah I guess that kind of sucks but that's what people will do. Having that many and then you wonder if you can `["preset-stage-0", { "loose": true }]`

**Comment by thejameskyle** [comment]
That would actually be really cool. If we could change the `preset` API so that it can also be a function that returns configuration you could do a lot more with it.

```js
export default function({ loose = false } = {}) {
  return {
    presets: [
      [require("babel-preset-stage-1"), { loose }]
    ],
    plugins: [
      [require("babel-plugin-transform-do-expressions", { loose }],
      [require("babel-plugin-transform-function-bind", { loose }]
    ]
  };
};
```

**Comment by jmm** [comment]
@hzoo @thejameskyle I brought up options for presets on slack when I first heard about them (and also the idea of just rolling the functionality into plugins so there's not 2 different concepts) and at the time Sebastian wasn't into it. I haven't really looked into it yet -- that's how it ended up, no options for presets?

**Comment by sebmck** [comment]
Adding options to presets just complicates things. Presets should have 1 purpose, and that's to provide standard configs.

**Comment by thejameskyle** [comment]
I think that also just leads to people creating more presets than necessary when simple options would suffice.

**Comment by sebmck** [comment]
Open another issue for discussion please.

**Comment by thejameskyle** [comment]
Done https://github.com/babel/babel/issues/2756
