### ISSUE TITLE
npm packages using `babel-core/register` do not work properly

### ISSUE THREAD

**Issue by mdibaiee** [babel/babel#2747]
Hey,

I'm using `babel-core/register` in a npm package, the package contains a `.babelrc` file and has `es2015` and `stage2` as dependencies.

Running the package manually (e.g. `node .`) works well, but if I install the module as dependency of another one and require it, `babel-core/register` doesn't work, I think that's because babel ignores `node_modules` by default, but I think it should only ignore each modules' own `node_modules` directory.

i.e. Installing a module places it in a directory like: `/some/path/project/node_modules/mymodule`, and babel ignores all the files because of `node_modules`. 

I think a solution would be to change the regular expression to something similar:
```
  ignore: new RegExp(__dirname + '/node_modules')
```

I will make a pull-request in case you agree on the case.

**Comment by loganfsmyth** [comment]
`babel-core/register` is meant as a helper to simplify local development. It isn't intended for use in production and because of that it would never be installed inside of `node_modules` of a subdependency.

If code is published as an npm package, it should be transpiled to ES5 ahead of time.

**Comment by mdibaiee** [comment]
@loganfsmyth: I see, it seems we're not going to have this.

Thanks, closing.
