### ISSUE TITLE
Incorrect renaming of scoped function

### ISSUE THREAD

**Issue by trikadin** [babel/babel#2752]
[Example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20bar%3B%0A%0A%7B%0A%20%20function%20foo()%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20bar%20%3D%20foo%3B%0A%7D%0A%0Aconsole.log(bar.name)%3B%0Aconsole.log(foo)%3B).

**Comment by loganfsmyth** [comment]
Would you please clarify? I'm guessing you're saying you expected

    var _foo = function foo() {};

in this case?

**Comment by trikadin** [comment]
Yes.

**Comment by thejameskyle** [comment]
This can be simplified to:

```js
let foo;
{ function foo() {} }
```
```js
var foo = undefined;
{ var _foo = function _foo() {}; }
```

**Comment by motiz88** [comment]
Closing in favor of #4020.
