### ISSUE TITLE
Auxiliary comment is badly broken

### ISSUE THREAD

**Issue by ariporad** [babel/babel#2757]
Hello everyone!

I have a rather large bug with babel, regarding the `auxillaryComment` (besides the other bug: babel/babel.github.io#527): Take a look at this snippet of code that babel outputted (ignore its content) (I removed some irrelevant parts):  
```javascript
/*istanbul ignore next*/'use strict';

module.exports = function Router() {
  return { /*istanbul ignore next*/
    route: function route(_route, handler) {
      // do stuff
    },
    /*istanbul ignore next*/run: function run(route) {
      route = cleanAndValidateRoute(route);
      var handler = routes.get(route);
      // TODO: We probobly shouldn't throw an error here. Although maybe it's the right thing to do.
      if (!handler) throw new Error('Route not found');
      /*istanbul ignore next*/
      for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
        args[_key - 1] = arguments[_key];
      }
 
      return (/*istanbul ignore next*/handler.apply( /*istanbul ignore next*/undefined, args)
      );
    }
  };
};
//# sourceMappingURL=data:application/json;base64,blahblahblah
 ```

That's generated from:

```es6
module.exports = function Router() {
  return {
    route(route, handler) {
      // do stuff
    },

    run(route, ...args) {
      route = cleanAndValidateRoute(route);
      const handler = routes.get(route);
      // TODO: We probobly shouldn't throw an error here. Although maybe it's the right thing to do.
      if (!handler) throw new Error('Route not found');
      return handler(...args);
    },
  };
};
```

Spot the problem? `/* istanbul ignore next */` ignores the next thing in the AST. Babel is putting it in front of the injected property name, from the short hand method syntax. The trouble is that istanbul then ignores the whole function.

It seems to me that this is a rather big problem. I'd try to fix it, but I don't know the first thing about babel or ASTs, so I'd probably just break it more.

Thanks!

**Comment by sebmck** [comment]
Looks like I didn't finish it before I shipped Babel 6. I just finished the remaining pieces and added a bunch of tests.

Although the new behaviour is still not going to perform the way you want. The new behaviour is going to output comments before (via `auxiliaryCommentBefore` option) and after (via `auxiliaryCommentAfter` option) any non-user code. This means that it wont be restricted to statements and transforms wont need to be constantly aware of that option and there will be zero false positives.

Istanbul will need to be adapted with the ability to specify ranges. You can see an issue tracking that here: gotwarlost/istanbul#413.

**Comment by kpdecker** [comment]
@sebmck is there anyway that we can have an option to restore the 5.x behavior? Coverage is unusable under 6 with these changes and I'm not holding my breathe for the istanbul folks to make any sort of changes any time soon.

**Comment by sebmck** [comment]
> is there anyway that we can have an option to restore the 5.x behavior? 

No. The APIs have been removed that functionality. It was never totally accurate anyway.

**Comment by kpdecker** [comment]
It may not have been accurate, but it worked. Under the 6.x behavior, outputs way too much that I'm not clear what the use case would be more often than not:
```
/*istanbul ignore next*/_temp2.default. /*istanbul ignore end*/open
```
from
```
import temp from 'temp';
...
temp.open(
```

And in some cases it still misses generated code:
```
/*istanbul ignore next*/
var /*istanbul ignore end*/Optimizer = exports.Optimizer = (function () {
  function Optimizer(file) {
    /*istanbul ignore next*/
    _classCallCheck(this, /*istanbul ignore end*/Optimizer);
```
from
```
export class Optimizer {
}
```

What use case was intended when the 6.x changes to the aux comment features were made?

**Comment by kpdecker** [comment]
It wouldn't be a cure all, but if it were possible to have a "before helper comment" sort of functionality (i.e. anything emitted through [here](https://github.com/babel/babel/blob/82a931c2893ad9275c7ce6641b88ab324060fe16/packages/babel-core/src/transformation/file/index.js#L262)) that would go a very long way to allowing ignores on the largest group of pertinent code without potential confusion that the aux comment has or hoping that istanbul lands a feature that the maintainer hasn't responded two since July.

**Comment by sebmck** [comment]
This isn't something I'm willing to support.

On Wed, Nov 11, 2015 at 11:45 PM, Kevin Decker <notifications@github.com>
wrote:

> It wouldn't be a cure all, but if it were possible to have a "before
> helper comment" sort of functionality (i.e. anything emitted through here
> <https://github.com/babel/babel/blob/82a931c2893ad9275c7ce6641b88ab324060fe16/packages/babel-core/src/transformation/file/index.js#L262>)
> that would go a very long way to allowing ignores on the largest group of
> pertinent code without potential confusion that the aux comment has or
> hoping that istanbul lands a feature that the maintainer hasn't responded
> two since July.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2757#issuecomment-156026796>.
>



-- 
Sebastian McKenzie

**Comment by kpdecker** [comment]
Can you explain why not? Would you accept a pull request if it's not something that can be injected via a plugin? Code coverage is vital and it's fundamentally broken right now with babel 6 and istanbul.
