### ISSUE TITLE
async function syntax not parsing using babel-cli 6.0.15

### ISSUE THREAD

**Issue by bsy** [babel/babel#2761]
using babel-cli 6.0.15
and my .babelrc has the following
```
{
  "presets": ["es2015"],
  "plugins": ["syntax-async-functions"]
}
```

When running babel-node:
```
async function getCombined(public_token) {
      ^^^^^^^^

SyntaxError: Unexpected token function
```

This was working before the weekend using 6.0.12, but today I `npm install`ed on a fresh checkout and the above is happening.

**Comment by bsy** [comment]
went back to babel 5.8.29 until this is all sorted out

**Comment by ndreckshage** [comment]
+1

**Comment by thelinuxlich** [comment]
This is happening for me too :(

**Comment by thelinuxlich** [comment]
How do I solve this with Babel 6?

**Comment by EricMCornelius** [comment]
:+1: - same issue

**Comment by sebmck** [comment]
You need to include the following:

```javascript
{
  plugins: ["transform-regenerator"]
}
```

```sh
$ npm install babel-plugin-transform-regenerator
```
