### ISSUE TITLE
transform-async-to-generator doesn't work for `this` inside arrow function.

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#2765]
**Input:**

```js
class Class {
  async method() {
    this;
    () => this;
  }
}
```

**Output:**

```js
class Class {
  method() {
    var _this = this;

    return _asyncToGenerator(function* () {
      _this;
      () => this; // << should be _this
    })();
  }
}
```

Note: this example is only with the `transform-async-to-generator` plugin.

Example repo: https://github.com/thejameskyle/__babel-bug-2765

**Comment by rolandjitsu** [comment]
I have the same [issue](https://github.com/babel/babel/issues/2982) with a simpler case.

**Comment by FourwingsY** [comment]
is this issue solved?

**Comment by Morglod** [comment]
this bug is now in preset-es2017
awesome

**Comment by hzoo** [comment]
preset-es207 is deprecated, and this is a bug then you need to provide reproduction steps (this issue over a year old so no idea if it's the same issue)
