### ISSUE TITLE
npm install -g babel-cli  error

### ISSUE THREAD

**Issue by jtHwong** [babel/babel#2767]
when i install babel-cli, the command line show error: "The CLI has been moved into the package `babel-cli`."  I retry install it,  the error also displays

**Comment by jtHwong** [comment]
when i use babel@5, it works well

**Comment by loganfsmyth** [comment]
@jtHwong Make sure you `npm uninstall babel`. `babel-cli` replaced it, but if you have both installed, you'll have problems.

Please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

I'd be happy to help with any other question you have there.
