### ISSUE TITLE
`babel.transformFromAst` doesn't work with ESTree compliant AST

### ISSUE THREAD

**Issue by lhorie** [babel/babel#2769]
```javascript
var babel = require("babel-core")

var code = babel.transformFromAst({
    "type": "Program",
    "body": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "Literal",
                "value": 1,
            }
        }
    ],
    "sourceType": "script"
}).code

//expected: code === "1;"
//actual: ReferenceError: unknown: unknown node of type "Literal" with constructor "Object"
```

**Comment by hzoo** [comment]
There are some changes from ESTree - https://github.com/babel/babel/blob/master/CHANGELOG.md#600, https://github.com/babel/babel/blob/master/CHANGELOG.md#6018. Specifically, that would be a `NumericLiteral` now.

**Comment by thejameskyle** [comment]
Here is the AST documentation https://github.com/babel/babel/blob/master/doc/ast/spec.md. Although it's currently missing some stuff related to JSX and Flow

**Comment by lhorie** [comment]
Right. My point though is that this breaks away from the [actual ESTree spec](https://github.com/estree/estree/blob/master/spec.md), thus making `babel.transformFromAst` fairly useless as an integration point with libraries that do follow ESTree to spec.

I can't use Babel as a drop-in replacement for Escodegen now, if, for example, I'm generating the AST from [eslisp](https://github.com/anko/eslisp) or something like that.

What's the rationale for this breaking change? Wouldn't it be possible to still have an overloaded `export function Literal` in `https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/types.js` and make it available to `Printer` while not breaking anything else?

**Comment by sebmck** [comment]
Not willing to support legacy ESTree constructs. These changes to the AST were made for stability and correctness and the additional maintenance burden of supporting a conversion layer is not worth it.

**Comment by hzoo** [comment]
I'l be making a conversion layer for babel-eslint/babel-jscs so I suppose we could make a package or something.

**Comment by lhorie** [comment]
@sebmck I see. That decision doesn't work for me, but thanks for taking the time to reply.
