### ISSUE TITLE
Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by ronak301** [babel/babel#2777]
The following code in my index.js produces the error in the title when I do -> node index.js :

require('babel/register');
require('./server.js');

And yes, I have babel installed as a node_module in the directory.
Further, when I changed the babel version to an older one (specifically, 4.7.16) in the package.json file, it worked without any errors.

**Comment by sebmck** [comment]
It's `babel-core/register`. Docs are [here](https://babeljs.io/docs/usage/require/). In the future, please see the README for support resources:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by AyubaMakoa** [comment]
you have to build the code locally first and then upload it to app engine pointing you npm start script from your package.json to the build directory. and make sure you are running on port 8080.
it should work.
babel-register should be a dev dependency
