### ISSUE TITLE
Tighter preset dependency versions

### ISSUE THREAD

**Issue by benmosher** [babel/babel#2778]
Due to some issues with `transform-runtime` (#2745), I was trying to stick with the 6.0 packages that worked for me (roughly 6.0.2-6.0.14) until the fixes were all achieved and released.

Because the `es2015` preset uses hat versions (`^6.0.15`, etc.), I can't lock down transform versions without abandoning the preset and manually installing all transforms.

Would it make sense to use non-hat versions inside the presets, and then let the hat on the preset dependency version allow all presets to update?

**Comment by benmosher** [comment]
i.e., `es2015` would be (as of today):

```json
{
  "name": "babel-preset-es2015",
  "version": "6.0.15",
  "description": "Babel preset for all es2015 plugins.",
  "author": "Sebastian McKenzie <sebmck@gmail.com>",
  "homepage": "https://babeljs.io/",
  "license": "MIT",
  "repository": "https://github.com/babel/babel/tree/master/packages/babel-preset-es2015",
  "main": "index.js",
  "dependencies": {
    "babel-plugin-transform-es2015-template-literals": "6.0.14",
    "babel-plugin-transform-es2015-literals": "6.0.15",
    "babel-plugin-transform-es2015-function-name": "6.0.14",
    "babel-plugin-transform-es2015-arrow-functions": "6.0.14",
    "babel-plugin-transform-es2015-block-scoped-functions": "6.0.14",
    "babel-plugin-transform-es2015-classes": "6.0.15",
    "babel-plugin-transform-es2015-object-super": "6.0.14",
    "babel-plugin-transform-es2015-shorthand-properties": "6.0.14",
    "babel-plugin-transform-es2015-computed-properties": "6.0.14",
    "babel-plugin-transform-es2015-for-of": "6.0.14",
    "babel-plugin-transform-es2015-sticky-regex": "6.0.14",
    "babel-plugin-transform-es2015-unicode-regex": "6.0.14",
    "babel-plugin-transform-es2015-constants": "6.0.15",
    "babel-plugin-transform-es2015-spread": "6.0.14",
    "babel-plugin-transform-es2015-parameters": "6.0.14",
    "babel-plugin-transform-es2015-destructuring": "6.0.14",
    "babel-plugin-transform-es2015-block-scoping": "6.0.14",
    "babel-plugin-transform-es2015-typeof-symbol": "6.0.15",
    "babel-plugin-transform-es2015-modules-commonjs": "6.0.15",
    "babel-plugin-transform-regenerator": "6.0.14"
  }
}
```

All hats removed from transforms.

**Comment by thejameskyle** [comment]
I think it might be good to be explicit like this

**Comment by hzoo** [comment]
So if we do fixed/explicit versions, will we be updating the preset whenever any of the packages in the preset update?

So if `"babel-plugin-transform-es2015-template-literals": "6.0.14",` -> `6.0.15` then you would update the preset to `6.0.16`? Same when minor versions? Sounds like a lot of updating for the preset

**Comment by benmosher** [comment]
Certainly more overhead on updates, yeah. Probably script-worthy; find all referencing presets, update referenced plugin version and bump preset version

I would think the preset version would match the highest included plugin versions--in your example, 6.0.15--assuming I understand the existing Babel package cluster versioning scheme. Wouldn't need to have its own independent version, per sé.

**Comment by Mark-Simulacrum** [comment]
While I'm not sure that Babel's versioning would work this way, but if two separate plugins are at `6.0.14`, and one updates to `6.0.15`, and then the other plugin updates to `6.0.15`, then what would the preset version be? With @benmosher's logic (as far as I could tell), the preset version would update to `6.0.15`, and then to `6.0.15` again? This would definitely go against semver (if even at all possible), so I'm not sure this is a good idea. 

It would seem to make more sense to keep the preset versions as a cumulative, semver, versioning of the plugins contained. This would make the preset versions be likely to be quite large, numerically speaking, e.g. `6.0.25` due to many small, incremental, plugin updates. However, since I'm not sure if Babel has a goal of keeping preset version number numerically small, I don't know if this is a concern.

**Comment by sebmck** [comment]
This isn't how Babel versioning works. Releases of packages are only done when there's an actual change to that package.

**Comment by benmosher** [comment]
Ah, yeah, if each package has an independent version, my suggestion would not work. 

However, it seems Babel packages get version numbers in "waves". i.e. 

 Preset x:
A: 6.0.14
B: 6.0.15
C: 6.0.2

If A is updated, it and any other package in this release cycle is updated to v6.0.16, skipping 6.0.15. Preset X would therefore always be the max of its contained plugin versions because it would always be updated as part of the same release cycle. 

So I think it works in practice because of the dependent, non-contiguous versioning of the component packages.

All that said, though: still plenty of overhead, and you can argue that the preset didn't "change" since the list didn't change. I think the overhead could be scripted away, too (a la `npm version`). 

Anyway, also totally fine if this level of control is not provided by the stock presets. I just figured it was worth discussing. 😄
