### ISSUE TITLE
nonASCIIidentifierChars not defined

### ISSUE THREAD

**Issue by dschnare** [babel/babel#2781]
Hello,

Just tried to run babel from the CLI with the es2015 preset and the transform-es2015-modules-commonjs plugin and I get this error:

```
ReferenceError: nonASCIIidentifierChars is not defined
    at Object.<anonymous> (/vagrant/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-types/node_modules/babel-traverse/node_modules/babylon/lib/util/identifier.js:49:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/vagrant/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-types/node_modules/babel-traverse/node_modules/babylon/lib/parser/index.js:15:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

To reproduce:

```
npm install babel-cli babel-preset-es2015 babel-plugin-transform-es2015-modules-commonjs --save-dev
echo '{ "presets": ["es2015"], "plugins": ["transform-es2015-modules-commonjs"] }' > .babelrc
./node_modules/.bin/babel src -d out
```

I am using Node 4.2.1. Put any ES6 source code in the `src` directory and let Babel try compiling it.

**Comment by dschnare** [comment]
I corrected the spelling mistakes I had when generating the .babelrc file, but I still get the same issues. Also, I tried downgrading Node to 0.12.7 and that's when I got error messages regarding the spelling mistakes in my .babelrc file. Node 0.12.7 still produces the error above.

**Comment by dschnare** [comment]
Tried running babel without the transform-es2015-modules-commonjs plugin and it produces the same error.

**babel-cli** 6.0.15
**babel-plugin-transform-es2015-modules-commonjs** 6.0.18
**babel-preset-es2015** 6.0.15

**Comment by sebmck** [comment]
`nonASCIIidentifierChars` is indeed declared in that file. I've manually inspected the source and I don't see why this error would be happening at all as there's nothing crazy going on in the code.

**Comment by dschnare** [comment]
Yeah I poked around in the source too and it is there, but Node can't find it (??) for whatever reason. It's a very weird error.

**Comment by dschnare** [comment]
Found something. There is no `nonASCIIidentifierChars` found in the `babel-plugin-transform-es2015-function-name`. I must have misread the error, it's actually complaining about the `babel-plugin-transform-es2015-function-name` dependent module in the `babel-preset-es2015` module.

**Comment by dschnare** [comment]
Here's the actual path to the error:

node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-types/node_modules/babel-traverse/node_modules/babylon/lib/util/identifier.js:49:74

It's a long one, but if you look at the identifier.js file the variable it's looking for is not defined. `nonASCIIidentifierChars`.

**Comment by dschnare** [comment]
I got it to work by uninstalling and re-installing babel-preset-es2015. Originally I had been using Node 4.2.1 and then downgraded. After downgrading I re-installed the commonjs modules plugin, but not the es2015 preset. **So this issue is related to Node 4.2.1.** More testing is needed.

**Comment by amasad** [comment]
sounds like this is resolved.
