### ISSUE TITLE
Wrong self-referencing in named async recursive functions

### ISSUE THREAD

**Issue by vadzim** [babel/babel#2782]
If named async function recursively calls itself by name then the compiled code is wrong.
Workaround is to assign anonymous async function to a variable and do recursive calls via that variable.

Problematic code:
```javascript
async function x( a ) { if ( a ) return a; else return await x( 42 ); }
x().then( a => console.log( a ) )
```
Output:
```
> GeneratorFunctionPrototype { _invoke: [Function: invoke] }
```

But:
```javascript
const x = async function ( a ) { if ( a ) return a; else return await x( 42 ); }
x().then( a => console.log( a ) )
```
Output:
```
> 42
```

**Comment by GGAlanSmithee** [comment]
Hmm, I wonder if this is related to #2776? Probably not, but the symptoms look kind of similar.

**Comment by amasad** [comment]
What plugins/preset does this use?

**Comment by vadzim** [comment]
@amasad, babel-preset-es2015. That's all.
