### ISSUE TITLE
babel-doctor issues

### ISSUE THREAD

**Issue by cameronjroe** [babel/babel#2785]
Ran `babel-doctor` and am getting these errors. How would I fix this? Not sure where babel-runtime would be.
```
✖ Found these duplicate packages:

- babel-runtime x 23
- babel-template x 7
- babel-traverse x 14
- babel-types x 11
- babel-helper-define-map x 1
- babel-helper-function-name x 2
- babel-helper-replace-supers x 1
- babel-helper-regex x 1
- babel-messages x 15
- babel-helper-get-function-arity x 3
- babel-code-frame x 15
- babel-helper-optimise-call-expression x 1

Recommend running `npm dedupe`

✖ We found some outdated packages:

- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29
- babel-runtime - Latest is 6.0.14. Local version is 5.8.29

Found potential issues on your machine :(
```

**Comment by kyrylkov** [comment]
Confirm the same issue.  Didn't find a way to fix it.  Back to Babel 5.

**Comment by thejameskyle** [comment]
Does this not fix the issue?

```
Recommend running `npm dedupe`
```

**Comment by kyrylkov** [comment]
@thejameskyle  no

**Comment by cameronjroe** [comment]
Nope.

**Comment by thejameskyle** [comment]
You might have dependencies that are preventing it from working. npm can be a bit frustrating with this stuff.

Try installing the latest of everything, preferably with npm3 as it does a better job of deduping deps.

**Comment by kyrylkov** [comment]
@thejameskyle  it doesn't work with Node.js 4.2.1 / npm 2.  That's LTS version so it MUST work with them before working with bleeding Node.js 5.0.0 / npm 3

**Comment by thejameskyle** [comment]
These aren't really errors, these are just warnings to diagnose common problems. npm 2 is fundamentally broken without dedupe, the solution is to update. If thats a problem then just ignore the warning

@kyrylkov On a personal note. Do yourself a favor and be a bit more polite as you comment on issues. I've read at least a dozen comments from you that solely existed to be mean, most of which I simply ignored and deleted. We're working our asses off here and you don't need to be such a jerk.

**Comment by kyrylkov** [comment]
@thejameskyle  I apologize if the comments offend you and I do appreciate the work being done.  However it doesn't mean that such utterly broken software can be released without alpha or beta label.  The damage this does far outweighs the benefits of pushing it out ASAP.

**Comment by thejameskyle** [comment]
@kyrylkov I understand what you are saying. That's not what I'm talking about here though, I'm talking about your attitude. You've been a complete jerk and you can't excuse that. So either contribute something meaningful to issues or don't say anything at all. None of us owe you anything

**Comment by kyrylkov** [comment]
@thejameskyle Honestly I don't know what you're referring to speaking about my attitude.  There is no attitude.  I opened a bunch of issues and commented on some.

**Comment by cameronjroe** [comment]
Let's keep it professional here. I'm sure you both are awesome engineers and can work through this minor issue. I just ran `npm i -g npm@latest` and knocked the error down to:

```
$ babel-doctor

Babel Doctor
Running sanity checks on your system. This may take a few minutes...

✔ Found config at /Users/cameronjroe/Dropbox/_projects/portfolio/awesome-metalsmith/.babelrc
✔ No duplicate babel packages found

✖ We found some outdated packages:

- babel-runtime - Latest is 6.0.14. Local version is 5.8.29

Found potential issues on your machine :(
```

**Comment by kyrylkov** [comment]
@cameronjroe  I had this error also.  The problem was that I removed ALL global and local NPM modules, installed them back and received the error you have, which shouldn't occur.

**Comment by sebmck** [comment]
This isn't the right place for this. See the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
>
> The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by cameronjroe** [comment]
Just joined the Slack. Thanks. @sebmck
