### ISSUE TITLE
babel-types error doesn't reference line number

### ISSUE THREAD

**Issue by myndzi** [babel/babel#2787]
In the error message thrown here:

https://github.com/babel/babel/blob/master/packages/babel-types/src/definitions/index.js#L57

A file reference is given, but not a line number, making it very difficult to track down. The information appears to be availableq in the 'node' object; it would be nice if this information was added to the output.

**Comment by sebmck** [comment]
The original builder call is included in the call stack. Showing the original source location isn't useful (and wont always be available) as these are dynamically created as a result of plugins and not the result of the input user code.
