### ISSUE TITLE
Arrow functions don't work with transform-async-to-module-method

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#2789]
With this config:

```json
{
  "plugins": [
    ["transform-async-to-module-method", {
      "module": "bluebird",
      "method": "coroutine"  
    }]
  ]
}
```

input:

```js
(async () => { await something(); })();
```

output:

```js
import { coroutine as _coroutine } from 'bluebird';
_coroutine(() => {
  yield something();
})();
```

Note the missing `*`, which means the `yield` statement is a syntax error because it's not in a generator.

This problem does not occur if you use a non-arrow `async function () {}`.

**Comment by amasad** [comment]
Did you mean to use async arrow functions in the input example?

**Comment by callumlocke** [comment]
Ha yes sorry

**Comment by amasad** [comment]
So the problem is that there is no such thing as arrow generator functions. I'm not sure if babel packages can take on dependencies on other packages. But this arrow function should be transformed for this to work.

**Comment by callumlocke** [comment]
My guess is that [this helper](https://github.com/babel/babel/blob/master/packages/babel-helper-remap-async-to-generator/src/index.js) needs to be updated to check if the node.type is `ArrowFunctionExpression` and, if so, apply similar logic to what the [arrow function transformer plugin](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-arrow-functions/src/index.js) does, i.e. change the node.type to `FunctionExpression` and do the this-binding and instantiation check.

Or maybe that logic should be extracted into a new helper module that can be shared by the remap-async-to-generator helper and the transform-es2015-arrow-functions plugin.

I would have a go at this myself if someone could confirm I'm thinking about it right. I'm new to this codebase though.

**Comment by amasad** [comment]
Yeah that's sounds right. #2793
