### ISSUE TITLE
babel-core is a blank file on cdnjs for all 6.x releases

### ISSUE THREAD

**Issue by awli** [babel/babel#2792]
If you try hitting a URL like http://cdnjs.com/libraries/babel-core/6.0.20, you don't get anything. My impression is that this probably has to do with the cdnjs auto-upload configuration, since it seems to be fine for the 5.x releases.

**Comment by jmm** [comment]
You mean if you hit a URL like https://cdnjs.cloudflare.com/ajax/libs/babel-core/6.0.20/browser.js? In any case, can you please report it [over there](https://github.com/cdnjs/cdnjs)? Thanks!
