### ISSUE TITLE
Plugins "async-to-module-method" and "es20150-modules-commonjs" are incompatible

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#2795]
When using [transform-async-to-module-method](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-to-module-method) together with [transform-es2015-modules-commonjs](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs), the output from a **named async function expression** is moved to the top (above require calls), resulting in broken code.

config:
```json
{
  "plugins": [
    "transform-es2015-modules-commonjs",
    ["transform-async-to-module-method", {
      "module": "bluebird",
      "method": "coroutine"  
    }]
  ]
}
```

input:
```js
async function foo() {}
```

output:
```js
"use strict";

let foo = (function () {
  var ref = (0, _bluebird.coroutine)(function* foo() {});
  return function foo() {
    return ref.apply(this, arguments);
  };
})();

var _bluebird = require("bluebird");
```

The output is broken because the expression `(0, _bluebird.coroutine)` is being evaluated while `_bluebird` is still undefined.

---

#### Workaround

Strangely it works OK if you assign the function to a constant (even if the function still has a name):

input:
```js
const foo = async function foo() {}
```

output:
```js
"use strict";

var _bluebird = require("bluebird");

const foo = (function () {
  var ref = (0, _bluebird.coroutine)(function* foo() {});
  return function foo() {
    return ref.apply(this, arguments);
  };
})();
```

**Comment by timmolendijk** [comment]
Ah right, I just submitted #2815 but I now see that the exact same issue is being reported here as well.

**Comment by thejameskyle** [comment]
Example repo: https://github.com/thejameskyle/__babel-bug-2795

**Comment by bakape** [comment]
Compiling with transform-async-to-module-method first and then with transform-es2015-modules-commonjs produces working output. So the problem is that the former calls `unshiftContainer()` before the latter calls `unshiftContainer()`.
