### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by IveWong** [babel/babel#2799]
I use *gulp-babel*, with this **.babelrc** file,
{ plugins: ['transform-runtime'] }

**Comment by loganfsmyth** [comment]
I have a feeling you may have `gulp-babel@6.x` and `babel-runtime@5.x`, which would be a version mismatch. Either way, we'll need more information here.

**Comment by sebmck** [comment]
Can't reproduce and there's not enough information provided. Make sure you have the module `babel-runtime` installed as `regenerator/index.js` certainly exists inside of `babel-runtime`.
