### ISSUE TITLE
babel-cli ignores --preset option

### ISSUE THREAD

**Issue by Niades** [babel/babel#2806]
Works only in plural, i.e. `--presets es2015`, while `--preset es2015` will be ignored. Still, all the docs I found, for example [babel-preset-es2015's README](https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/README.md) refer to the `preset` option.

**Comment by hzoo** [comment]
It should be `presets` - we need to change all those occurrences then.

**Comment by Niades** [comment]
Great, thanks a lot.
