### ISSUE TITLE
modules-commonjs changes this to undefined

### ISSUE THREAD

**Issue by appedemic** [babel/babel#2820]
I have the following file index.js:
```js
console.log(this)
```

When running through babel with the es2015 preset, the modules-commonjs plugin creates the following code:
```js
console.log(undefined)
```
I caught this when trying to compile riot templates with riotify, which pulls a part of a template through babel. (riot/compiler#15)

The cause is the line https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js#L126

**Comment by appedemic** [comment]
A solution would be to add _ThisExpression_ to THIS_BREAK_KEYS

**Comment by zloirock** [comment]
This is expected behaviour. See #2406, #2141, #1988, #1700, #1667, #1573, #562, #814, #730, #733, etc.
