### ISSUE TITLE
async await with es2015 and stage-0 presets

### ISSUE THREAD

**Issue by FredericHeem** [babel/babel#2825]
While trying to upgrade to babel 6 the boilerplate project [babel-mocha-test](https://github.com/FredericHeem/babel-mocha-test), There is an issue using async/await in mocha testing, the following error is returned:
```
/Users/frederic/babel-mocha-test/src/funcs.js:12
  var ref = _asyncToGenerator(regeneratorRuntime.mark(function fail(name) {
                              ^

ReferenceError: regeneratorRuntime is not defined
```

with the *babelrc*: 
```
{
  "presets": ["es2015", "stage-0"]
}
```
 
The code is run on node, not on the browser
Any ideas that issue ?

**Comment by preco21** [comment]
Similar issue.

I'm using `webpack` with `babel-loader`.

my .baberc:
```
{
  "presets": [
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

When I run my code, browser console returns this error:
![image 002](https://cloud.githubusercontent.com/assets/4936201/10956186/eb584ac4-839c-11e5-991a-81be4a28f64a.png)

![image 004](https://cloud.githubusercontent.com/assets/4936201/10956205/12457026-839d-11e5-8e32-64e313045204.png)

**Comment by preco21** [comment]
Related: #2744

**Comment by ZhengzhongZhang** [comment]
you need [babel-polyfill](http://babeljs.io/docs/usage/polyfill/) to provide regenerator runtime
but it seems current version of polyfill(6.0.16) has some error, [#2744](https://github.com/babel/babel/issues/2744)

**Comment by hzoo** [comment]
Above comments are correct you need to get the regenerator runtime somethow - https://babeljs.io/docs/usage/polyfill/.
