### ISSUE TITLE
Destructuring an array into itself causes overwrites.

### ISSUE THREAD

**Issue by YourDeveloperFriend** [babel/babel#2826]
If I want to swap two entries in an array, I can do this:

```javascript
// This works (Solved by #1241)
var array = [0, 1];
[array[1], array[0]] = [array[0], array[1]];
console.log('correct', array); // [1, 0]
```

However, if I wanted to simplify the code:

```javascript
// This doesn't work
var array = [0, 1];
[array[1], array[0]] = array;
console.log('wrong', array); // [0, 0]
```

This may be the intended behavior, but I wanted to bring it to your attention. Here's the [REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=%0A%2F%2F%20This%20works%0Avar%20array%20%3D%20%5B0%2C%201%5D%3B%0A%5Barray%5B1%5D%2C%20array%5B0%5D%5D%20%3D%20%5Barray%5B0%5D%2C%20array%5B1%5D%5D%3B%0Aconsole.log('correct'%2C%20array)%3B%0A%0A%2F%2F%20This%20doesn't%0Avar%20array%20%3D%20%5B0%2C%201%5D%3B%0A%5Barray%5B1%5D%2C%20array%5B0%5D%5D%20%3D%20array%3B%0Aconsole.log('wrong'%2C%20array)%3B).

**Comment by sebmck** [comment]
That's expected behaviour. You're mutating an array. It doesn't copy it before it destructures.
