### ISSUE TITLE
Regenerator relies on Function#name, breaks minifiers

### ISSUE THREAD

**Issue by monsanto** [babel/babel#283]
See [here](https://github.com/6to5/6to5/blob/55e2010311906a05e56b8c9ecd4e11d497b5e9f8/lib/6to5/transformation/transformers/es6-generators/runtime.js#L39).

The author of this code tries to be clever and set `GF.name` in the line above, but this actually isn't possible to do (try it in Chrome or Firefox, it will just ignore the assignment).

Having `"GeneratorFunction"` as the constructor name is mandated by the specification. However, I would argue it's not a very important part of the specification, and that convenient minification is much more important. At the very least, the `throw` line should be removed, so people who don't care what the constructor name is aren't affected. It's worth noting that Regenerator itself does not care what the constructor name is.

However, there is a case for removing the `"GeneratorFunction"` trick altogether: it would allow for removing the `mark()` call in the following, improving the readability of the generated code:

```
root@smogon-dev:~$ echo 'function* foo() { }' | 6to5
"use strict";

var foo = regeneratorRuntime.mark(function foo() {
  return regeneratorRuntime.wrap(function foo$(_context) {
    while (true) switch (_context.prev = _context.next) {
      case 0:
      case "end": return _context.stop();
    }
  }, foo, this);
});
```

Here's the issue which lead to `mark` being added: https://github.com/facebook/regenerator/issues/48. The primary reason seems to be allowing the `co`  library to perform some magic to distinguish between regular functions and generator functions. I guess I'm not swayed by this because `co` isn't very useful when you have async functions (like we do).

**Comment by aaronshaf** [comment]
In 6to5 2.13.3 I am still getting `GeneratorFunction renamed?` when using alongside uglifyjs.

**Comment by sebmck** [comment]
@aaronshaf Where are you getting the polyfill/runtime from? [regenerator/runtime.js](https://github.com/facebook/regenerator/blob/master/runtime.js) doesn't include the `GeneratorFunction renamed?` error anymore.
