### ISSUE TITLE
Babel-polyfill: genFun is undefined

### ISSUE THREAD

**Issue by ZhengzhongZhang** [babel/babel#2830]
I try to use async/await with babel
I installed babel-preset-es2015 babel-preset-stage-3 babel-polyfill

_.babelrc_

    {
        "presets": ["es2015", "stage-0"]
    }

and I got error in polyfill.js
>Uncaught TypeError: Object.setPrototypeOf called on null or undefined

chrome debugger said 
>genFun=undefined

      runtime.mark = function(genFun) {
        if (Object.setPrototypeOf) {
          Object.setPrototypeOf(genFun, GeneratorFunctionPrototype);// It's here, line 3738 in polyfill.js
        } else {
         genFun.__proto__ = GeneratorFunctionPrototype;
        }
        genFun.prototype = Object.create(Gp);
        return genFun;
      };

I think there is somethine wrong in babel-polyfill

My code is below
index.html 

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h1>Async test</h1>
        <script src="node_modules/babel-polyfill/dist/polyfill.js"></script>
        <script src="async.js"></script>
        </script>
    </body>
    </html>

async.es6.js

    async function api() {
        try {
            let response = await fetch('https://api.github.com');
            let data = await response.json();
            console.log(data);
        } catch (e) {
            console.log("Oops, error", e);
        }
    }
    api();

**Comment by zloirock** [comment]
Duplicate #2744.
