### ISSUE TITLE
Broken functionality and test coverage

### ISSUE THREAD

**Issue by PWKad** [babel/babel#2831]
We rely on babel.js to function through each release without breaking previous functionality.  Looking in to the latest release is a concern because there are so many broken pieces.  How can we run the test coverage tasks for this repository to see what is covered and what is not?

**Comment by sebmck** [comment]
See the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Also [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md).
