### ISSUE TITLE
error in new browser.js

### ISSUE THREAD

**Issue by aeosynth** [babel/babel#2836]
browser.js:15533 Uncaught TypeError: deps.map is not a function

babel-browser@6.1.2

**Comment by sebmck** [comment]
You have not provided enough information to debug. How are you using it? What is the full stack trace?

**Comment by aeosynth** [comment]
index.html:

```html
<html>
<head>
  <script src="browser.js"></script>
</head>
<body>
</body>
</html>
```

trace (chrome browser 46.0.2490.80 (64-bit)):

```
amdRequire	@	browser.js:15533
(anonymous function)	@	browser.js:14237
runFactory	@	browser.js:15598
define	@	browser.js:15692
162.155	@	browser.js:14235
s	@	browser.js:2
(anonymous function)	@	browser.js:2
154.161	@	browser.js:12481
s	@	browser.js:2
(anonymous function)	@	browser.js:2
(anonymous function)	@	browser.js:4322
38.12	@	browser.js:4956
s	@	browser.js:2
(anonymous function)	@	browser.js:2
47.273	@	browser.js:6053
s	@	browser.js:2
(anonymous function)	@	browser.js:2
32.1	@	browser.js:3935
s	@	browser.js:2
(anonymous function)	@	browser.js:2
(anonymous function)	@	browser.js:3793
31.274	@	browser.js:3889
s	@	browser.js:2
e	@	browser.js:2
(anonymous function)	@	browser.js:2
(anonymous function)	@	browser.js:2
(anonymous function)	@	browser.js:2
```

**Comment by sebmck** [comment]
cc @zertosh removing the plugins you added fixes this. Any obvious fix?

```
diff --git a/packages/babel-browser/scripts/build-dist.sh b/packages/babel-browser/scripts/build-dist.sh
index 2dd5d57..623af60 100755
--- a/packages/babel-browser/scripts/build-dist.sh
+++ b/packages/babel-browser/scripts/build-dist.sh
@@ -11,8 +11,6 @@ mkdir -p dist
 node -p '"\uFEFF"' > dist/browser.js
 node $BROWSERIFY_CMD ../babel-core/lib/api/browser.js \
   --standalone babel \
-  --plugin bundle-collapser/plugin \
-  --plugin derequire/plugin \
   $BROWSERIFY_IGNORE \
   >>dist/browser.js
```

**Comment by jochenberger** [comment]
Getting a similar error: `TypeError: Cannot find function map in object 156. (de.eddyson.tapestry.react.services.JSXCompiler$1@10002818#15533)`. The `amdRequire` is called with the single value `156` but an array is expected.

**Comment by jiyinyiyong** [comment]
Same here while requiring this bundle into Webpack.
![screen shot 2015-11-06 at 12 03 28 am](https://cloud.githubusercontent.com/assets/449224/10973783/e1e2b3ee-8419-11e5-90ab-41e12a6ef7ba.png)

**Comment by zertosh** [comment]
checking

**Comment by zertosh** [comment]
it's the old version of source-map. v5.0.0 got rid of this weird AMD wrapper that broke bundle-collapser. so just updating source-map to anything above 5.0.0 should fix it (and it's faster)

**Comment by zertosh** [comment]
ugh... shuttle wifi is impossible... i'm pretty sure it's that... it'll be another hour or two before i can submit a tested PR... and I meant v0.5.0.

**Comment by jiyinyiyong** [comment]
Got another strange error:
![image](https://cloud.githubusercontent.com/assets/449224/11090752/8b340756-88af-11e5-8fc8-6af7417fe9e5.png)

**Comment by aeosynth** [comment]
> You have not provided enough information to debug. How are you using it? What is the full stack trace?

**Comment by jiyinyiyong** [comment]
@aeosynth I just required code of `babel-browser@6.1.4` with Webpack and it threw this error. I really think `_dereq_(290).Object.keys` is strange before I looking into details.

**Comment by cime** [comment]
Same here... babel-browser@6.1.4:

	TypeError: Cannot read property 'keys' of undefined
		at Object.283.290 (babel.js?v=2.0.5793.27323:19839)
		at s (babel.js?v=2.0.5793.27323:2)
		at babel.js?v=2.0.5793.27323:2
		at Object.273.283 (babel.js?v=2.0.5793.27323:19817)
		at Object.656.273 (babel.js?v=2.0.5793.27323:31919)
		at s (babel.js?v=2.0.5793.27323:2)
		at babel.js?v=2.0.5793.27323:2
		at Object.646.635 (babel.js?v=2.0.5793.27323:30862)
		at s (babel.js?v=2.0.5793.27323:2)
		at babel.js?v=2.0.5793.27323:2

**Comment by hzoo** [comment]
Actually lets just track this in https://github.com/babel/babel/issues/2987 which is the same
