### ISSUE TITLE
Create an es7 polyfill and/or a polyfill generator?

### ISSUE THREAD

**Issue by AshCoolman** [babel/babel#2837]
The current polyfill is es6. It would be good to have a es7 one, and ultimately, it would be nice to be able to generate one from the CLI.

Is this something inline with the project?

Some context: http://stackoverflow.com/posts/33540804/edit

**Comment by zloirock** [comment]
`babel` polyfill  includes [`core-js` ES7 polyfills](https://github.com/zloirock/core-js#ecmascript-7) too.
