### ISSUE TITLE
Cannot call method "split" of undefined

### ISSUE THREAD

**Issue by jochenberger** [babel/babel#2839]
The problem is in babel-template: https://github.com/babel/babel/blob/740c76e53a1b5eae62f4bd18be76669be1615eef/packages/babel-template/src/index.js#L15
This will not work in every environment (will fail in IE11 for example), because IE11 does not initialize `Error.stack` until the object is thrown.
I suggest changing this to 
```javascript
let stack = new Error().stack;
if (!stack) {
  try {
    throw new Error();
  } catch (e) {
    stack = e.stack;
  }
}
stack = stack.split("\n").slice(1).join("\n");
```

**Comment by jochenberger** [comment]
Unfortunately the fix will not work when running the compiler inside a ScriptEngine in a Java. Maybe changing it to `(new Error().stack || "unknown source").split("\n").slice(1).join("\n");` would be the safest bet.

**Comment by sebmck** [comment]
I've added a compiler support document to better outline what environments the compiler does and doesn't support. Unfortunately this is not something we intend on fixing or hacking around.
