### ISSUE TITLE
environment awareness

### ISSUE THREAD

**Issue by leebenson** [babel/babel#2842]
Is there any way to have babel attempt feature detection prior to polyfilling?

Let's say I have the `es2015` preset loaded in my **.babelrc**, which `babel-node` uses Node 5.0 as well as browserify in my gulp file.

I'd expect this simple file...

**test.js**

```
let message = 'hello world';
```

... to correctly transpile down to the following in browserify (which it does)

```
'use strict';

var msg = 'hello';
```

... but to remain _exactly_ the same in the Node 5.0 version, since `let` is a V8 native declaration and doesn't need to 'drop down' to the `var` equivalent.

My main concern is performance. If V8 has already optimised, say, the spread operator, then it doesn't make much sense to work around it.

**Comment by hzoo** [comment]
Don't think we can do that - you'll have to specify what you need manually or someone will make a preset based on your environment

**Comment by sebmck** [comment]
There is no way and there wont be a way in core to facilitate this behaviour either. This has been discussed thoroughly before: #272, #462, #631, #686, #1918.

**Comment by GGAlanSmithee** [comment]
I've been thinking about this too.

The problem is that most feature detection libs perform feature detection based on the platform it is being run on. One solution would be to use [the caniuse api](https://www.npmjs.com/package/caniuse-api) to get a list of features for a specific target browser or platform and build a .babelrc file (list of plugins) based on that.

**Comment by leebenson** [comment]
@sebmck, sorry to drag up an old idea. I didn't trawl the closed issues, it was just something that struck me after switching to the Node 6.x track and possibly something to re-visit now you have an (excellently) modular system with v6.

> One solution would be to use the caniuse api to get a list of features for a specific target browser or platform and build a .babelrc file (list of plugins) based on that.

I really like that idea. It's what @alippai suggested in #272 and what Autoprefixer supposedly does.

At first glance this seems like it could be an admin nightmare to track all the different versions, but I think it's a very common use case to assume _some_ Node version of the server on the front (either 0.12, 4.x or 5x) and transpiling down to ES5 on the browser. With Can I Use, has the legwork been partly done?

**Comment by loganfsmyth** [comment]
@leebenson Keep in mind, the `preset` system in Babel 6 allows people to make bundles of transformations for specific environments very easily. There's nothing stopping someone from making presets driven by caniuse data, that'd be awesome.

At the end of the day though, the decision has to be made for how much of this should live in the babel repo and how much should be left to the community to build. If it's added to core but no-one has time to maintain it, that's not any more useful to people than not having it.

**Comment by GGAlanSmithee** [comment]
For node, you can use feature detection with [this](https://github.com/getify/es-feature-tests) for example. It will give you what you need for the node version you currently building on.

The CanIUse database is pretty complete and up to date as far as I know. Their API looks nice too, configurable but with a small surface area. I think the main work would be to map the (for the targeted platform) missing es6 features to the right babel plugin. Could be fully automated too since the CanIUse info is updated as browsers evolve.

**Comment by GGAlanSmithee** [comment]
@loganfsmyth I think that this is a community thing. Doesn't make sense for babel to maintain it given the direction babel is moving with version 6 and onwards

**Comment by leebenson** [comment]
I think this blurb from https://github.com/getify/es-feature-tests says it best:

> If all the JavaScript features/syntax your code uses are supported natively by the browser, why would you load up the ugly transpiled code? Why would you load dozens of kb of polyfills/shims if all (or most of) those APIs are already built-in?

I think there's a wider issue here. I'm betting 80%+ of your user base will look at babel's docs, add `es2015` to .babelrc, stick `require('babel-core/register')` at the top of their entry script, and call it a day. Since they never _see_ the transpiled code, it will never occur to them that their shiny new Node 5.x is running code designed for a Node release from 5 years ago.

To @loganfsmyth's point, yes, the modular new system of being able to require exactly what's missing is awesome, but I disagree that this is a community issue. If babel is doing the transpiling, and there are packages that can feature detect the local build env (which babel needs to run _inside_ of to actually _do_ the transpiling), why not automatically check at the point of instantiation via `require` hooks? Why require another package on top to pre-define those shims in .babelrc?

This may theoretically add a bit of extra compile time to babel (or maybe not, if AST can be skipped), but it should also speed up runtime because babel can intelligently skip compiling native features down to unnecessary code. I think that's a win for your user base that ought to be central to babel's functionality, and probably not relied on/farmed out to the community.

**Comment by sebmck** [comment]
I'm sorry but there's nothing more to be said about this topic. Babel core is not going to have this feature.
