### ISSUE TITLE
babel-browser does not have a main field

### ISSUE THREAD

**Issue by jiyinyiyong** [babel/babel#2846]
https://github.com/babel/babel/blob/5d61840c10f3270f01836bea263292926f806315/packages/babel-browser/package.json

**Comment by sebmck** [comment]
This is intentional. You should not be consuming `babel-browser` via node/webpack/browserify use `babel-core`.

**Comment by thejameskyle** [comment]
Could we detect if you are trying to include babel-browser in node/browserify/webpack and throw an error?

**Comment by jiyinyiyong** [comment]
Why throwing an error? I want to bundle babel-core into my project so I can debug with Chrome DevTools, but babel-core itself contains dependencies from Node.js and does not work there. babel-browser is my only choice.

**Comment by sebmck** [comment]
babel-browser is literally a browserified babel-core build so there's no
reason you can't use babel-core.

On Sun, Nov 8, 2015 at 6:39 PM, 题叶 <notifications@github.com> wrote:

> Why throwing an error? I want to bundle babel-core into my project so I
> can debug with Chrome DevTools, but babel-core itself contains dependencies
> from Node.js and does not work there. babel-browser is my only choice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2846#issuecomment-154905119>.
>



-- 
Sebastian McKenzie

**Comment by jiyinyiyong** [comment]
I'm using Webpack, maybe it uses a different algorithm from Browserify.
