### ISSUE TITLE
Local script to run babel scripts via package.json

### ISSUE THREAD

**Issue by KevinGrandon** [babel/babel#2850]
I don't want to have to have globally installed packages, so to accomplish this we require `babel` as a dependency and execute `node_modules/.bin/babel-node` from scripts within package.json.

This was working fine, until upgrading to v6.x.

```
The CLI has been moved into the package `babel-cli`.

$ npm install -g babel-cli
```

What is the new .bin file that we can use to run babel-node from a local project within node_modules? Can we also add it to the error message so it's easier to migrate?

**Comment by hzoo** [comment]
Did you try just installing babel-cli locally? `npm install babel-cli` and then `node_modules/.bin/babel-node` should be there?

**Comment by KevinGrandon** [comment]
> Did you try just installing babel-cli locally? npm install babel-cli and then node_modules/.bin/babel-node should be there?

Thanks, that does appear to bring the script back locally, but I think there's some problems with this approach, `--stage` doesn't appear to work as well as some of the other command line arguments.

**Comment by hzoo** [comment]
Ok that's a different issue - You should check out the blog posts, changelog, and all that since its a new version http://babeljs.io/blog/2015/10/31/setting-up-babel-6/. (There is no stage option anymore. There is a corresponding `presets` with babel-preset-stage-x though.)

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by KevinGrandon** [comment]
Thanks for the info here! I think the main problem here is that this is a pretty large change for an upgrade, and the error generated by babel-node was not too clear on migrations steps. Adding more content to that may help reduce user confusion. I'll think about it some more and submit a pull request to improve it if I have time.
