### ISSUE TITLE
babel is undefined

### ISSUE THREAD

**Issue by aeosynth** [babel/babel#2859]
test.js:

```js
import babel from 'babel-core'

console.log(babel)
```

.babelrc:

```json
{
  "presets": ["es2015"]
}
```

```
$ babel test.js -o build.js
$ node build.js
undefined
```

**Comment by forivall** [comment]
That should be `import {* as babel} from 'babel-core'`. `babel-core` doesn't have a default export, which is what that import statement is trying to import.

**Comment by hzoo** [comment]
Babel doesn't export anything named babel so I'm not sure the issue? https://github.com/babel/babel/blob/master/packages/babel-core/src/api/node.js

**Comment by hzoo** [comment]
Yeah you can do `import * as babel from 'babel-core'` if that's what you needed
