### ISSUE TITLE
how do babel 5 "whitelist" in babel 6 ?

### ISSUE THREAD

**Issue by raiscui** [babel/babel#2862]
how do like this:

`
babel({
          'whitelist': ['strict', 'es6.modules', 'es6.arrowFunctions', 'es6.parameters', 'es6.spread'],
          'optional': ['bluebirdCoroutines']
      }
`

**Comment by loganfsmyth** [comment]
@raiscui Sorry, please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
