### ISSUE TITLE
Class Property Initializers - Different transpilation on Mac and Windows

### ISSUE THREAD

**Issue by jstejada** [babel/babel#2863]
I've included `babel-preset-stage-0` and I'm using the require hook in my app as so:

```javascript
  require('babel-core/register')({
    sourceMaps: true,
    presets: ['es2015', 'react', 'stage-0'],
    extensions: ['.es6', '.es', '.jsx'],
  });
```

I'm writing a simple class and using property initializers to [autobind](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers) a method:

```javascript
class MyClass {

  onClick = ()=> {
    this.doStuff();
  }

}
```

This works fine when I run this in my Mac, but when I run on Windows the code gets transpiled differently:

**Mac:**
```javascript
var MyClass = function MyClass() {
  var _this = this;

  _classCallCheck(this, MyClass);

  this.onClick = function () {
    _this.doStuff();
  };
};
```

**Windows:**
```javascript
var MyClass = (function () {
  function MyClass() {
    var _this = undefined;

    _classCallCheck(this, MyClass);

    this._onClick = function () {
      _this.doStuff();
    };
  };
};
```

This is what my dependencies look like:

```json
    "babel-core": "^6.0.20",
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-react": "^6.0.15",
    "babel-preset-stage-0": "^6.0.15",
```

I am installing them via [apm](https://github.com/atom/apm), to use in [electron](https://github.com/atom/electron).

Any ideas what might cause this?

**Comment by loganfsmyth** [comment]
Could you make certain that both cases are using exactly the same versions of everything? Maybe worth comparing `npm ls` output or something to be extra certain.

That's certainly weird though.
