### ISSUE TITLE
!isFinite and !isNaN launching error "Cannot read property '_generated' of undefined"

### ISSUE THREAD

**Issue by timbergus** [babel/babel#2865]
I have been importing functions to create filters in Angular and when using `!isNaN` and `!isFinite` inside the filter I have the following error:

__Cannot read property '_generated' of undefined while parsing file__

The importing process is as follows:

#### index.js

    [...]
    filters.filter('myFilter', () => require('./my-filter'));
    [...]

#### my-filter.js

    export default function (number) {

        if (!isNaN(number)) {
            return !isFinite(number);
        } else {
            return 'NaN';
        }
    }

If I compare as usual, it works just fine (`isFinite === false`). Am I doing something wrong? Please help :(

Thanks in advance.

**Comment by hzoo** [comment]
What's your `.babelrc`/preset/plugins? Is this with babel 6?

**Comment by timbergus** [comment]
Sorry for answering so late (I've just read the mail), but yes, I'm using Babel 6 and my presets are `["es2015", "stage-2"]`. Thanks for the fix :)
