### ISSUE TITLE
Warning in Firefox about slow running code

### ISSUE THREAD

**Issue by SunboX** [babel/babel#2867]
Using the plugin `babel-plugin-transform-es2015-classes`

I'm using Firefox Developer Edition 44.0a2 (2015-11-04) and getting this warning message:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; 
instead create the object with the correct initial [[Prototype]] value using Object.create
```

**Comment by hzoo** [comment]
Looks like the same issue as https://github.com/babel/babel/issues/1099 so closing as a dup
