### ISSUE TITLE
`ignore` option in `.babelrc` no effect while compiling directory

### ISSUE THREAD

**Issue by soulwu** [babel/babel#2870]
My `.babelrc`
```json
{
  "presets": ["es2015", "stage-0"],
  "ignore": ["templates"]
}
```

when I run
```bash
$ babel src --out-dir lib
```
files in my `templates` directory are compiled.

only
```bash
$ babel src --out-dir lib --ignore templates
```
can behavior exactly

`babel-cli@6.1.2` installed

**Comment by sebmck** [comment]
Expected behaviour. The Babel options are not synonymous with the CLI flags. `ignore` on the CLI omits the files from being dealt with at all. The `ignore` API option skips any processing happening on the file.

**Comment by thejameskyle** [comment]
Oh man... that's confusing
