### ISSUE TITLE
Parse error at IIFE

### ISSUE THREAD

**Issue by tohashi** [babel/babel#2872]
Hello, I saw this error after update to 6.0 with babel-preset-es2015.

```javascript
// ok
(() => {})();
(function() {})();

// parse error (but enable to parse with babel 5.x)
(() => {}());
(function() {}());
```

Is this expected behavior or specification of es2015?

**Comment by jmm** [comment]
Hello @tohashi, welcome to the Babel community! That's expected behavior per ES2015. It was a bug that it worked in v5. See #2118. In your second example, the `FunctionExpression` should be fine, but not the `ArrowFunction`.

**Comment by tohashi** [comment]
@jmm I got it. Thanks!
