### ISSUE TITLE
broken link on Usage --> CLI page

### ISSUE THREAD

**Issue by scottaddie** [babel/babel#2874]
In the Options table at the bottom of the Usage --> CLI page, the experimental link in the Description column is broken.

**Comment by hzoo** [comment]
Well `-r, --stage [stage]	2	Set the experimental proposal stage` - stages options is gone and you have to use a preset for that so I'll just remove that.

**Comment by hzoo** [comment]
Also since this is a docs issue please report it in the https://github.com/babel/babel.github.io repo next time
