### ISSUE TITLE
Babel 6 seems to ignore Presets

### ISSUE THREAD

**Issue by resistdesign** [babel/babel#2876]
With this code:

```
require('babel-core/register')({
    presets: [require('babel-preset-stage-0')]
});

// Tests:
require('./validation');
```

And these deps:

```
  "devDependencies": {
    "babel-core": "^6.1.2",
    "babel-preset-stage-0": "^6.1.2"
  }
```

I get this error:

```
...tests/validation.js:1
(function (exports, require, module, __filename, __dirname) { import { Decorators, Types } from '../index';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)...
```

It's as if it's not even trying to transpile it or something.

**Comment by resistdesign** [comment]
I should add that I'm using Node v4.2.1.

**Comment by loganfsmyth** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by resistdesign** [comment]
@loganfsmyth Just out of curiosity are you not using GitHub for bug reports anymore?

**Comment by loganfsmyth** [comment]
It's not a bug, you just haven't enabled `es2015`.

**Comment by resistdesign** [comment]
You see what I just did there right? ;)

**Comment by loganfsmyth** [comment]
You circumvented a system we have in place to avoid spamming people with notifications to more quickly answer your question and inconvenience us.

**Comment by resistdesign** [comment]
Well explained, I'll use the other resources from now on :)
