### ISSUE TITLE
transform-runtime with export * from 'x' generates import statements in transpiled code

### ISSUE THREAD

**Issue by mdouglass** [babel/babel#2877]
I am attempting to use transform-runtime in combination with code that uses the export \* from 'x' statement. The code that is generated during transpilation includes an import statement for core-js' define-property. I'm using the es2015 preset, so I would expect that a require statement would be generated, not an import.

Small sample project at https://gist.github.com/mdouglass/a6a5c5aae68ac03a92d3

**Comment by thejameskyle** [comment]
You're missing this transform: https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-export-extensions

---

This is still a problem though because without the syntax plugin I assume this should be throwing SyntaxErrors?

**Comment by mdouglass** [comment]
Actually I had that in my original narrowed test case, but removed it since it did not matter to the repro. I've added it back to the gist and it's still doing the same thing.

**Comment by mdouglass** [comment]
Also updated the gist to 6.1.4 to check that it hadn't been addressed in the interim.

**Comment by mdouglass** [comment]
I've been trying to troubleshoot this problem and I *think* that it is being caused because babel-plugin-transform-es2015-modules-commonjs is running before babel-plugin-transform-runtime. So when babel-plugin-transform-runtime adds an import it's not being converted. 

However, I can't see in the code how dependencies between plugins are expressed. Or how to explicitly change the order between them. Assuming I am right, how should this be handled?

Note: this is my first foray into babel internals, so I could be way off here.

**Comment by wonyun** [comment]
@anjianshi，what the reason of commenting this line 'defineProperty: "object/define-property"' in babel-plugin-transform-runtime/lib/definitions.js?

**Comment by wadim** [comment]
Thanks @david-mitchell! Your workaround with `passPerPreset` (above) worked for me!

**Comment by nouh** [comment]
same here

**Comment by krukid** [comment]
Still an issue. I've tried to migrate to version 6 twice during the past year and had to roll back because of this problem. I thought I'd rewrite a bunch of my logic to use the working `export * as ns from ...` instead of `export * from ...`, but then I'm afraid it's going to be deprecated or broken as well, being a `stage-0` feature. Anyway, fingers crossed this gets fixed in 2017.

PS: The workaround suggested here doesn't seem to work for me.

**Comment by posva** [comment]
The workaround is a bit lost in the reposted comments so I'll just repost it here:

```js
  "plugins": [
    ["transform-runtime", { "polyfill": false }]
  ]
```

**Comment by krukid** [comment]
@julien-f @posva Thanks guys, I've tried the `{ "polyfill": false }` thing (must've missed it before) and it seems to work so far, though I'm not sure I fully understand what the implications of using it are. Also it may or may not be relevant to this particular issue, but having a default export seems to prevent `export * from` from working.

I.e.:
```es6
const FOO = 1;
export default FOO; // <------- this will break subsequent bulk exports

export * from './bar';
export * from './baz';
```

**Comment by trusktr** [comment]
@krukid You should make a new issue for that, with a repro.

**Comment by jaggerwang** [comment]
```
{
    "passPerPreset": true,
    "presets": [
        { "plugins": [ "transform-runtime" ] },
        {
            "passPerPreset": false,
            "presets": [ "es2015", "stage-1" ]
        }
    ]
}
```

This worked for me!

**Comment by matiasherranz** [comment]
@julien-f Your CommonJS workaround worked perfect for me. Thanks for sharing.

**Comment by cattermo** [comment]
I need the polyfills so I can't use that workaround. The "passPerPreset" workaround seems to be working but I don't understand how to use it if I have other plugins too. Where should the other plugins be put?
```
{
    "passPerPreset": true,
    "presets": [
        { "plugins": [ "transform-runtime" ] },
        {
            "passPerPreset": false,
            "presets": [ "es2015", "stage-1" ]
        }
    ]
}
```
I have tried adding `"transform-class-properties", "transform-es2015-modules-commonjs"` in different places but they are not getting applied. Can anyone supply an example using the passPerPreset together with other plugins than `transform-runtime`?

Please help...
