### ISSUE TITLE
ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by lookfirst** [babel/babel#2883]
Trying to run a gulpfile.babel.js with latest version of babel...

node 5.0.0 installed with brew on osx 10.11.

package.json:
```
  "devDependencies": {
    "babel": "^6.0.15",
    "babel-core": "^6.1.2",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.1.3",
    "babel-plugin-external-helpers-2": "^6.0.15",
    "babel-preset-es2015": "^6.1.2",
    "del": "2.0.2",
    "gulp": "^3.9.0",
    "gulp-helpers": "^3.0.0",
    "jspm": "0.16.14",
    "karma-jspm": "^2.0.2",
    "protractor": "^2.5.1"
  },
```

.babelrc
```
{
  "presets": ["es2015"],
  "plugins": ["external-helpers-2", "transform-es2015-modules-commonjs"]
}
```

```
gulp
[13:53:07] Requiring external module babel-core/register
/Users/jon/hub/gulpfile.babel.js:5
var _gulp2 = babelHelpers.interopRequireDefault(_gulp);
             ^

ReferenceError: babelHelpers is not defined
    at Object.<anonymous> (/Users/jon/hub/gulpfile.babel.js:5:14)
    at Module._compile (module.js:425:26)
    at loader (/Users/jon/hub/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jon/hub/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/Users/jon/hub/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/jon/hub/node_modules/liftoff/index.js:192:16)
```

**Comment by loganfsmyth** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

You need to build and load the helpers yourself if you use this plugin.

**Comment by lookfirst** [comment]
@loganfsmyth I see this as a documentation issue. This used to work just fine in babel 5.x. Now I can't seem to use gulp with ES6. Since there isn't any documentation that explains how to upgrade this, maybe this issue should be opened up again to provide such documentation.

**Comment by loganfsmyth** [comment]
Totally agree there. Also from the README though:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by MikaAK** [comment]
What's the solution to this? I've tried `import 'external-helpers-2'` and `import babelHelpers from 'external-helpers-2'`but both fail. How does one build/load helpers

**Comment by lookfirst** [comment]
@MikaAK Exactly. @loganfsmyth would rather close the issue than answer it.

**Comment by MikaAK** [comment]
@loganfsmyth While I agree it's a documentation issue, a simple answer so we can get this working and point to it as a reference till the docs are available would be most helpful :)
