### ISSUE TITLE
babylon should handle duplicate declaration errors (?)

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#2884]
Asked a bit in the IRC channel and it was suggested that this should be the case. Basically, if you imagine a real time linter (kind of like Babel's Try It) that just wants to show errors, or a syntax highlighter that also shows errors, it would be nice to show Duplicate Declaration Errors (let x = 10; let x = 10;).

As of right now it appears that the only way to get this is through going through a transform (as opposed to babylon.parse just throwing it). This is unfortunate since its a lot of extra work since I won't actually be using the transform, just wanting to get this one error. I might be wrong here and there is some in-between step you can do to get this but I don't know.

I am aware that this is kind of a strange error since it waits to happen until called, so its kind of in the middle, but again unfortunate to require the full sweep.

**Comment by sebmck** [comment]
This requires scope tracking and isn't something that belongs in a parser. You need to do a full tree traversal anyway in order to do scope tracking due to function hoisting, TDZ and more. You can get this behaviour with a noop traverse:

```javascript
require("babel-traverse").default(yourAstHere);
```

**Comment by loganfsmyth** [comment]
I get the reasoning behind this, but it really is too bad. The spec defines these things as early errors, I don't think I'd expect to have to traverse in order to get early errors.

**Comment by sebmck** [comment]
Early errors don't have to happen in the parser, it's an implementation detail.
