### ISSUE TITLE
`const` in `async function` or generator gives "read-only" error

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#2892]
Here's the code I'm compiling:

	export default class Foo {
		async bar() {
			const baz = 0
		}
	}

My package.json is:

	{
		"scripts": {
			"build": "babel src --out-dir dist --source-maps inline"
		},
		"devDependencies": {
			"babel-cli": "6.1.2",
			"babel-plugin-transform-async-to-generator": "6.0.14",
			"babel-preset-es2015": "6.1.2"
		},
		"babel": {
			"plugins": ["transform-async-to-generator"],
			"presets": ["es2015"]
		}
	}

This error occurs:

	SyntaxError: src/foo.js: "baz" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)
	  1 | export default class Foo {
	  2 | 	async bar() {
	  3 | 		const baz = 0
	  4 | 	}
	  5 | }
	  6 | 

Doing any of the following makes it work:

* `let baz`
* Remove `async`
* Remove `default`
* Make it a function (`export default async function bar() { ...`)

So this is an error specifically for `const` in `async` in `class` in `export default`!

**Comment by hzoo** [comment]
Might not be exactly the same but similar to https://github.com/babel/babel/issues/2843

**Comment by iv597** [comment]
Removing `default` temporarily fixed this for me but the issue quickly returned.

```
ERROR in ./static/js/spoton.js
Module build failed: SyntaxError: /Users/j/src/spoton/website/static/js/spoton.js: "querySelections" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)
```

**Comment by rightaway** [comment]
+1
