### ISSUE TITLE
Node 5.x preset - did I miss anything?

### ISSUE THREAD

**Issue by leebenson** [babel/babel#2894]
I've put together a very simple preset for Node 5.0. I'm using this in production and will keep it closely tracked to Babel 6 releases. So far, it seems to be working well, and is chipped a few ms off my response times and in some cases, knocked a few seconds of gulp times by avoiding unnecessary transpilation / using Node 5 native features.

https://www.npmjs.com/package/babel-preset-node5

Have I missed anything obvious in "key features"? I've used [this compatibility table](https://kangax.github.io/compat-table/es6/#node5)

**Comment by GGAlanSmithee** [comment]
https://www.npmjs.com/package/babel-preset-es2015-node5

**Comment by leebenson** [comment]
I saw that but I found a couple of things were missing and versions didn't track babel releases, which made it a bit confusing.

**Comment by GGAlanSmithee** [comment]
Ah,ok!

I think this brings up a potential issue with the current system, where there is no governing of presets and plugins. There will be lots of duplicate presets and hard for consumers to know wich one to use.

According to our conversation in your other issue, I started to hack away on a tool that will resolve plugins automatically for a target platform (using the same DB as you). I think that is a good way forward.

As for your key features, I can't see that you've missed anything. Buw why did you decide to support jsx but not flow?

**Comment by leebenson** [comment]
automatic plug-ins -- awesome! that's definitely the way to go. Throwing together random presets is probably only good for a stopgap. I published to npm mostly to match up with babel releases, and to keep deps current. It's mostly a private need that I thought might help others.

Flow vs. React -- this is the kind of feedback I wanted. Ideally (for now) a user can just include "node5" in their .babelrc presets and it'll transpile _any_ non-Node5 native function, even the stage 0 stuff. The only reason I left some of that out is a) I don't use some of it personally, so I don't know requirements and b) a few things are still broken - async/await, for example.

I'll add flow now.

**Comment by GGAlanSmithee** [comment]
Also. You mention compilation and build time benefits, but not script execution time benefits. An in-engine implemented feature will almost always be more performant than transpiled code

**Comment by leebenson** [comment]
That's what I meant by:

> The end result is nearly always a faster build and **runtime**.

But I'll make that more explicit.

**Comment by GGAlanSmithee** [comment]
My bad, I missed it.

**Comment by hzoo** [comment]
Thanks for making the preset but the issue tracker isn't for these kinds of questions. I'd just look through http://babeljs.io/docs/plugins/ again and the compat table is helpful too yeah

Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
