### ISSUE TITLE
How to make async/await functions work?

### ISSUE THREAD

**Issue by trusktr** [babel/babel#2896]
I've got this config for the babel-loader:

```js

                            test: /\.jsx?$/,
                            loader: 'babel',
                            exclude: /node_modules/,
                            query: {
                                cacheDirectory: true,
                                presets: [
                                    'es2015', // tc39 stage 4, currently es2015?
                                    'react'
                                ],
                                plugins: [
                                    'syntax-async-functions', // async/await syntax (transformer is in the es2015 preset)
                                    'transform-es5-property-mutators',
                                    'transform-es2015-modules-amd',
                                    'transform-es2015-modules-commonjs',
                                    //'transform-es2015-modules-systemjs', // needs System existing in global scope first (f.e. via SystemJS)
                                    'transform-es2015-modules-umd',
                                    'transform-async-to-generator',
                                ],
                            },
                        },
```

I'm getting an error like this: http://trusktr.io:7777/esobazefer

Somethings up with the async functions, because if I change a function back to synchronous without the async/await keywords, it compiles just fine.

**Comment by hzoo** [comment]
Your error `Expected type "Identifier" with option {}` sounds like https://github.com/babel/babel/issues/2835 which I should of fixed in master so I would wait for the next release?

Also `syntax-async-functions` only parses async and doesn't transform anything. I'm not sure why you have 3 transforms for modules?

**Comment by trusktr** [comment]
Hi @hzoo 

> Also syntax-async-functions only parses async and doesn't transform anything.

I know, which is why I included `transform-async-to-generator` and `es2015` which includes `transform-regenerator`. So, `syntax-async-functions` -> `transform-async-to-generator` -> `transform-regenerator` should work right? Or did I miss something? (It's not too clear from the docs).

> I'm not sure why you have 3 transforms for modules?

It's because I'm using Webpack/Babel in a generic tool: [rocket:module](https://github.com/meteor-rocket/module) for Meteor.

**Comment by hzoo** [comment]
I guess I mean that the transform plugins include the syntax ones so you don't have to specify it - https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-async-to-generator/src/index.js#L5 - I added a note in the docs http://babeljs.io/docs/plugins/#transform

**Comment by trusktr** [comment]
@hzoo That seems contrary to what it says here: http://babeljs.io/docs/plugins/transform-regenerator

That gives the impression that the syntax plugin should be manually added, and doesn't even mention the async-to-generator transform, which I think would be good.

**Comment by trusktr** [comment]
@hzoo 

> sounds like #2835 which I should of fixed in master so I would wait for the next release?

How might I test this out right now noting that I can't use NPM link for my project? I can use `git` urls in package.json instead of version numbers, but all these packages are in one single repo, which doesn't help that use case.

**Comment by trusktr** [comment]
I was able to test, and got past this error. Now I'm having the same error as https://github.com/babel/babel/commit/940b86dadbd0151c33c02e89f0b5ff61077c9214#commitcomment-14259015.
