### ISSUE TITLE
Conditionally running regenerator runtime?

### ISSUE THREAD

**Issue by trusktr** [babel/babel#2900]
Does babel make code that will conditionally run native generators instead of always using the performance cost of regenerator (when using `transform-regenerator`)?

f.e., something similar to (examples copied pasted from regenerator site):

```js
if (supportsGenerators()) {
    function *range(max, step) {
      var count = 0;
      step = step || 1;

      for (var i = 0; i < max; i += step) {
        count++;
        yield i;
      }

      return count;
    }

    var gen = range(20, 3), info;

    while (!(info = gen.next()).done) {
      console.log(info.value);
    }

    console.log("steps taken: " + info.value);
}
else {
    var marked0$0 = [range].map(regeneratorRuntime.mark);
    function range(max, step) {
      var count, i;

      return regeneratorRuntime.wrap(function range$(context$1$0) {
        while (1) switch (context$1$0.prev = context$1$0.next) {
        case 0:
          count = 0;
          step = step || 1;

          i = 0;
        case 3:
          if (!(i < max)) {
            context$1$0.next = 10;
            break;
          }

          count++;
          context$1$0.next = 7;
          return i;
        case 7:
          i += step;
          context$1$0.next = 3;
          break;
        case 10:
          return context$1$0.abrupt("return", count);
        case 11:
        case "end":
          return context$1$0.stop();
        }
      }, marked0$0[0], this);
    }

    var gen = range(20, 3), info;

    while (!(info = gen.next()).done) {
      console.log(info.value);
    }

    console.log("steps taken: " + info.value);
}
```

**Comment by hzoo** [comment]
Your code snippet is a bit messed up. If you mean something like in https://github.com/babel/babel/issues/2842 then it's a no - What you can do is make/find a preset that is per environment

**Comment by zloirock** [comment]
If generators not supported - `function*range(){}` will cause syntax error, if supported - second part of this snippet makes no sanse.

**Comment by trusktr** [comment]
@hzoo @sebmck IMHO, although Babel 6 has moved forward in configurable power, it has regressed in ease-of-use.

Asking end users to create a bunch of configurations (it took me long enough to create my first one) and manage them for different targets may keep the barrier to entry a lot higher that it can be.

So, now I need to write code outside of my bundle to detect features in order to even load a bundle, or I have to compile more than one bundle so the first bundle can load the appropriate bundle?

Why not just make this easy for end users, yet easily configurable for those who wish to do so.

**Comment by trusktr** [comment]
Most people don't care about including two versions of the code. Most people just want to start using ES6. If they're going to permis the performance loss from using regenerator, I'm sure they won't mind the harmless duplicate code, and will in fact appreciate the performance gain where features are supported natively without them having to worry about how that works.

**Comment by trusktr** [comment]
@zloirock You're right. How can it be done?

**Comment by trusktr** [comment]
One possible way to do it:

Place code into a fake file:

```js
var blobURL = URL.createObjectURL( new Blob([ '(',

"code goes here",

')()' ], { type: 'application/javascript' } ) ),
```

then load it conditionally.

**Comment by trusktr** [comment]
But how would we detect the feature? Possibly by creating test `Function` instances:

```js
var _supportsGenerators = new Function(`
  function* () {}
`)

function supportsGenerators() {
  try {
    _supportsGenerators
    return true
  }
  catch (e) { return false }
}
```

**Comment by trusktr** [comment]
Ah, there we go:

```js
var _supportsGenerators = 

function supportsGenerators() {
  try {
    new Function('function* gen() {}')
    return true
  }
  catch (e) { return false }
}
```

**Comment by zloirock** [comment]
@trusktr it's **impossible** without 2 versions of code. Dynamic code generation on runtime - `eval` / `Function` constructor / etc - definitely not `babel` way, so remains one way - generation config for a target, see issue above or, for example, #631.

**Comment by trusktr** [comment]
@zloirock I think that `Function` idea is complete fine for the benefits of the end user who simply wants to use the crazy new features introduced in ES2015 (more known as ES6). Babel 6 is more powerful but more difficult to use than Babel 5. Babel 5 was closer to letting people just use ES6 out of the box. 

I agree that Babel 6 should progress to be more configurable and powerful, but it should also progress in terms of how easy it is to use. That seems like a good idea for any software project.

**Comment by trusktr** [comment]
If you actually think about it, most people who try these new features just want it to work in all browsers. If you told them that they were receiving huge performance losses in Chrome and Firefox in order to support IE/Edge, I'm sure they wouldn't feel as good as if they knew it was performant in Chrome and Firefox, and only slow on IE out of the box.

**Comment by trusktr** [comment]
Source maps in url blobs are [also supported in Chrome](https://code.google.com/p/chromium/issues/detail?id=492586) at least. I'm haven't checked FF, and I'm not confident about Edge having even tested that scenario. Would that make debugging a pain?
