### ISSUE TITLE
es2015-destructuring doesn't work with parameters

### ISSUE THREAD

**Issue by slikts** [babel/babel#2902]
[Every](https://github.com/lukehoban/es6features#destructuring) [source](https://kangax.github.io/compat-table/es6/#test-destructuring) [about](https://babeljs.io/docs/learn-es2015/#destructuring) destructuring includes parameters, so why doesn't es2015-destructuring support it in parameters? It should at least say that destructuring in parameters needs es2015-parameters.

**Comment by hzoo** [comment]
Yeah we can definitely add some docs (still working out all that stuff) - It looks like it does say in the parameters transform that it transforms destructuring in params but not the other way around http://babeljs.io/docs/plugins/transform-es2015-parameters/ - use https://github.com/babel/babel.github.io to report any more docs issues.

**Comment by slikts** [comment]
It would make more sense if plugins would follow the established ES6 feature categories instead, so that destructuring would actually be the whole of destructuring, and the parameters could be rest + default, or even those could be put in separate plugins. It would also be more flexible.

**Comment by thejameskyle** [comment]
>  make more sense if plugins would follow the established ES6 feature categories instead [...] It would also be more flexible.

It'd actually be the complete opposite of flexible, as engines can easily support these features separately and you may want to compile one but not the other.

**Comment by slikts** [comment]
I didn't put it clearly, but the flexibility would come from separating the features out more. If not, it would be better to at least match the categories used in Babel's own docs.
