### ISSUE TITLE
release size issue for 'babel-cli' and 'babel-preset-es2015'

### ISSUE THREAD

**Issue by futagoza** [babel/babel#2904]
Over a week ago I installed (via npm) Babel 6:

 - babel-cli (v6.0.14)
 - babel-preset-es2015 (v6.0.14)

Over the last couple of days I've come to realise that compared to Babel 5, the ES6 to ES5 compiling time is slower. At first it wasn't that much of a problem but as my project grows and other tasks need to be integrated into my build process to handle other resources, the slow compile time is too much.

I decided to downgrade to Babel 5 and started deleting the folders for these 2 modules from my project's *node_modules* directory only for it to take **5+ minutes** to scan for **97,181** files, with a total size of **125+ mb**.  10 minutes later and its still only deleted just over **10%** of this.

I am doing my work on a Aspire V5-122p Laptop running Windows 10 Home x64, a Quad-Core A6-1450 CPU/GPU, 10GB RAM and a 1TB HDD (2 450GB partitions) with a 7200 RPM.

At first I thought it might be a problem with my HDD, but most other file handling tasks were pretty fast. There also seems to be no problem with my HDD after checking it with the chkdisk utility. No other applications running, and no extra background task running either.

From what I've concluded there seems to be no problem with my laptop, so the only problems I can point out are the abnormally large amount of files and their size (125+mb).

**Comment by hzoo** [comment]
Are you using npm 3?

**Comment by futagoza** [comment]
I'm using Node 4.0.0 and npm 2.14.2

**Comment by hzoo** [comment]
Maybe you can try `npm dedupe` or use npm 3 which should cut down on the node_modules size since they all use the same packages.

**Comment by futagoza** [comment]
Running 'npm dedupe' didnt do anything.

I'll try updating npm and then reinstalling it, but first I've got to delete the files again (60k+ left).

I originally didn't want to upgrade Node.js or NPM because the project I'm working on depends on Electron to run its published result, and I can't seem to find what version of Node.js the Electron source use, so I thought to play it safe, but I guess that isn't gonna cut it anymore :D

**Comment by thejameskyle** [comment]
There's really very little to be done, npm before 3 was really bad with creating too many files and bad deduping. I strongly recommend upgrading as it improves everything.

**Comment by futagoza** [comment]
Node 4.0.0 and npm 2.14.2:
- 97,181 files
- 125+ mb

Node 5.0.0 and npm 3.3.6:
- 3,877 files
- 18+ mb

Well, that is much better, but when I delete the *node_modules* folder now Windows scan reports 4K+ files instead instead of the 3,877 reported by the folder properties for *node_modules*.

Speed for the transpile processes is roughly the same still, so I'm still gonna be downgrading :D

**Comment by hzoo** [comment]
Ok closing - our recommendation is npm 3 for this particular issue.
