### ISSUE TITLE
Can't get await to work without throwing error

### ISSUE THREAD

**Issue by mrmayfield** [babel/babel#2905]
I am trying to use the `await` functionality in my code but can't get it to work with a new project.

Just running this line: 
`
  let docs = await users.findAsync({})
`

Fails with:

`Unexpected token (18:19)` at the beginning of `users`. What am I doing wrong? `users` is a monk collection promisified.

**Comment by hzoo** [comment]
Did you checkout http://babeljs.io/blog/2015/10/31/setting-up-babel-6/? I can't tell what your `.babelrc` or options are but I'm assuming you don't have that setup correctly?

**Comment by mrmayfield** [comment]
I've installed the stage-0 preset plugin, with this as my .babelrc file
`
{
  "presets": ["stage-0"]
}
`
running babel-node from the terminal and still the same error.

**Comment by hzoo** [comment]
Oh you are just running that single line? Well that's invalid syntax - you need to wrap it in an async function

```
async function a() {
  let docs = await users.findAsync({}); 
}
```
