### ISSUE TITLE
export default object not working

### ISSUE THREAD

**Issue by almasakchabayev** [babel/babel#2918]
I have a config file: where I have the following code:
```
export default {
  PARSE_APP_ID: 'some string',
  PARSE_JS_KEY: 'another string',
};
```
importing it in another file in the following manner 
```
import { PARSE_APP_ID, PARSE_JS_KEY } from './config';
```

`PARSE_APP_ID` and `PARSE_JS_KEY` are both undefined if `console.log`ed

If i use `module.exports = { ... }` instead everything works fine

**Comment by vkurchatkin** [comment]
This works as expected, you need to use named exports if you want to use named imports:

```js
export const PARSE_APP_ID = 'some string';
export const PARSE_JS_KEY = 'another string';
```

**Comment by geminiyellow** [comment]
@vkurchatkin yes, your code is ok,
but @almasakchabayev 's code works fine in babel 5.
witch is right? `babel6` or `babel5`

**Comment by sebmck** [comment]
This is a change in Babel 6 to make imports more compliant. See #2212 for more info.
