### ISSUE TITLE
Cannot call method directly in arrow function

### ISSUE THREAD

**Issue by tadeuzagallo** [babel/babel#2919]
```js
() => {}.bind(this)
```

fails with `SyntaxError: unknown: Unexpected token (1:8)`.

**Comment by hzoo** [comment]
Is this valid? Is that supposed to be the same as `(() => {}).bind(this)`?

**Comment by tadeuzagallo** [comment]
Not sure either to be honest, but I'm migrating some code, and apparently it used to compile with babel 5, so I thought I'd open an issue.

**Comment by hzoo** [comment]
Checking http://astexplorer.net/ quickly it does parse with babel 5 but not with esprima.

**Comment by sebmck** [comment]
It's not valid. Wrap it in parens, see #2118.
