### ISSUE TITLE
Tests fail when building with node v5.0.0 / npm v3.3.6

### ISSUE THREAD

**Issue by chalbert** [babel/babel#2922]
I've encountered the following problem when running `make test` after building from scratch using `node v5.0.0` / `npm v3.3.6`.

Running
```
$ nvm use v5.0.0
$ git clone git@github.com:babel/babel.git
$ cd babel
$ make bootstrap
$ make build
$ make test
```

I get
```
babel/node_modules/eslint/lib/rules/no-undef.js:59
    return parent.type === "UnaryExpression" && parent.operator === "typeof";
                 ^

TypeError: Cannot read property 'type' of undefined
    at hasTypeOfOperator (babel/node_modules/eslint/lib/rules/no-undef.js:59:18)
    at babel/node_modules/eslint/lib/rules/no-undef.js:84:21
    at Array.forEach (native)
    at EventEmitter.Program:exit (babel/node_modules/eslint/lib/rules/no-undef.js:80:33)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (babel/node_modules/eslint/lib/util/node-event-generator.js:51:22)
    at CommentEventGenerator.leaveNode (babel/node_modules/eslint/lib/util/comment-event-generator.js:111:23)
    at Controller.controller.traverse.leave (babel/node_modules/eslint/lib/eslint.js:774:36)
    at Controller.__execute (babel/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

Interestingly, if the project has been built first with an older version of node / npm, then it works. I suspect it is due to how the bootstrap is executed using npm 3.

This works
```
$ nvm use v4.1.1
$ git clone git@github.com:babel/babel.git
$ cd babel
$ make bootstrap
$ make build
$ make test
```

And again in the same directory, this works too
```
$ nvm use v5.0.0
$ make bootstrap
$ make build
$ make test
```

**Comment by hzoo** [comment]
That's odd because we have node ?5/npm 3 on travis and it builds fine https://travis-ci.org/babel/babel/builds/89947846

**Comment by chalbert** [comment]
Yeah, I was wondering about that.

Looking at the Travis build logs, I've spotted one thing:

When I build locally, the `gulp build` doesn't seem to run properly:
```
$ gulp build
[11:36:53] Using gulpfile ~/workplace/babel-node-5/Gulpfile.js
[11:36:53] Starting 'build'...
[11:36:53] Finished 'build' after 164 ms
```

Gulp is one of the things that seems to be pre-installed on the container, so I wonder if that couldn't explain the difference I see. I have `gulp v3.9.0` installed. 

Also, I can reproduce this issue from 2 different Mac.

**Comment by sebmck** [comment]
> When I build locally, `gulp build` doesn't seem to run properly:

No it's running properly. It's just not recompiling files that it doesn't need to.

**Comment by sebmck** [comment]
This is an error with ESLint so there's nothing really actionable here. Try running `make test-only` to skip the linting.

**Comment by chalbert** [comment]
Thanks, `make test-only` is a reasonable solution for now. Isn't it weird that eslint fails for a clean clone though?

I'd be interesting to know if anybody else can reproduce.

**Comment by sebmck** [comment]
It was due to a recent ESLint update, I fixed this by pinning the version. CI started failing for 5.0 because I cleared Travis' cache. Will need to investigate why ESLint was throwing that error.

**Comment by hzoo** [comment]
https://github.com/babel/babel-eslint/pull/206 It looks like they changed something with estraverse/estraverse-fb so our monkeypatching needed to change - pushed babel-eslint@4.1.5 which should work with eslint@1.9.0 now
