### ISSUE TITLE
Support for renaming extensions in import statements

### ISSUE THREAD

**Issue by markwoon** [babel/babel#2925]
I'm using babel to transform my *.es6 files into *.js files.  The problem comes in the import statement: `import { foo } from "foo.es6"`, which is no longer valid once transpiled.

I would like a way to transform extensions in import statements, so that the above gets changed  to `import { foo } from "foo.js"`.

**Comment by sebmck** [comment]
You can support this in your module bundler or use the `resolveModuleSource` option callback specified [here](https://babeljs.io/docs/usage/options/) to rewrite your module sources:

```javascript
babel.transform("code", {
  resolveModuleSource: function (source) {
    return source.replace(".es6", ".js");
  }
})
```

If you require any further help or assistance please don't hestitate to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!

**Comment by markwoon** [comment]
@sebmck Thanks for the quick response.

Would it be possible for you to also explain how to use this from the command line?  (I have tried asking in Slack but haven't had much success.)

**Comment by markwoon** [comment]
I took a quick look at the code and it doesn't appear to be possible using using babel-cli (among other things, `resolveModuleSource` is marked as a hidden property).

For anyone stumbling around needing something like this:  https://www.npmjs.com/package/babel-plugin-transform-import-extension-es6-to-js
