### ISSUE TITLE
When using default parameters, get Unexpected token =

### ISSUE THREAD

**Issue by chrisabrams** [babel/babel#2926]
Here is the contents of the file that runs through babel, but it would seem that babel does not parse it: http://stackoverflow.com/questions/33602366/unexpected-token

What babel plugin is needed to handle default parameters for functions? I'm using the `babel-preset-es2015` at `6.1.2`.

This worked in babel `5.x`.

**Comment by sebmck** [comment]
[See the README](https://github.com/babel/babel#looking-for-support).
