### ISSUE TITLE
use strict moved to top level with AMD module factory

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2929]
**5.0:**

```js
define(['exports'], function (exports) {
  'use strict';
```

**6.0**

```js
'use strict'
define(['exports'], function (exports) {
```

From @tkissing in https://github.com/babel/babel.github.io/issues/546

**Comment by tkissing** [comment]
Thanks for "moving" it. Not sure how I ended up filing in the other repo except "too many open tabs".
