### ISSUE TITLE
babel-preset-react hasn't been published correctly to npm

### ISSUE THREAD

**Issue by Joezo** [babel/babel#2930]
Looks like version 6.1.2 on [npm](https://npmcdn.com/babel-preset-react@6.1.2/package.json) doesn't match up with what's in the [repo](https://github.com/babel/babel/blob/master/packages/babel-preset-react/package.json)

The version on npm doesn't contain `babel-plugin-transform-react-display-name`.

It's possible to get around this for now by explicitly installing said plugin.

Thanks for all the work on babel :)

**Comment by sebmck** [comment]
If by "hasn't been published correctly" you mean "not at all" then sure. It'll be released when I push a version next which will be in the next couple days.

**Comment by Joezo** [comment]
That'll do it :) Thanks!
