### ISSUE TITLE
'this' undefined in class method even with arrow methods

### ISSUE THREAD

**Issue by tofagerl** [babel/babel#2932]
See code below. 

As expected, with this code the console.log statement in the constructor returns the class instance, while the console.log statement in the saveListener method (which is the only one triggered from the outside - that is from the listener set in setListener()) returns the button.

But if I change it to ```  saveListener = ()=> {``` the first log statement still returns the class instance, but the second one returns ```undefined```. the jQuery statement ```let formData...``` doesn't fail, it just returns empty, but all other statements fail including this.controller.model.getById().

Note that this compiles correctly via Webpack in both instances. I don't get the infamous 'this before super' thing, probably because I'm not extending anything.
I'm using stage-0 and es2015, and I'm on babel-core 6.1.2 and latest presets. No plugins. 

```
import { editElement as template } from './templates.js';
import { serializeObject, merge } from '../utils';
class EditElement {
  constructor(dom, controller) {
    if (!dom) {
      throw new Error('Invalid DOM element!');
    }
    this.controller = controller;
    this.dom = dom;
    console.log('constructor this', this);
  }
  show(element) {
    return this.refresh(element);
  }
  refresh(selectedElement, elements) {
    let html = template({
      selectedElement: selectedElement,
      elements: elements
    });
    $(this.dom).html(html);
    this.setListeners();
  }
  empty() {
    $(this.dom).empty();
  }
  setListeners() {
    $(this.dom).find('#saveElementButton').on('click', this.saveListener);
    $(this.dom).find('#cancelElementButton').on('click', this.empty);
  }
  saveListener() { // Save element:
    console.log('saveListener this', this);
    let formData = serializeObject($(this.dom).find('#editElement > form'));
    console.log(formData);
    // TODO: Split into method of Utils and Generalize.
    let selectedElement = this.controller.model.getById(formData.elementId);
    if (selectedElement.get('name') !== formData.name) {
      selectedElement.set('name', formData.name);
    }
    this.empty();
    this.refresh();
    this.controller.refresh();
  };
}
export default EditElement;
```

**Comment by sebmck** [comment]
This is expected behaviour. Methods aren't autobound. You're passing it off to an event listener and it's not retaining the context because it's not the callee.
