### ISSUE TITLE
ArrowFunctionExpression cannot be used as rhs for LogicalExpression

### ISSUE THREAD

**Issue by tadeuzagallo** [babel/babel#2934]
The following code fails with parse error:

```js
foo || () => {}
```

Error: `SyntaxError: unknown: Unexpected token (1:8)`

**Comment by jmm** [comment]
Hello @tadeuzagallo, welcome to the Babel community! This is the same issue as #2823.

**Comment by tadeuzagallo** [comment]
Oops, sorry, I did search, but failed to find it, thanks for the quick response.
