### ISSUE TITLE
Flow type imports generating commonjs requires if syntax-flow is included

### ISSUE THREAD

**Issue by tadeuzagallo** [babel/babel#2935]
The sample code is:

```js
import type Foo from './bar';
```

If you have the following config:

```js
{ plugins: [ 'syntax-flow', 'transform-es2015-modules-commonjs', 'transform-flow-strip-types' ] }
```

It will generate a require call to the `./bar` module (independent of the order of the plugins), but if you remove `syntax-flow` it'll generate an empty file as expected. Although I'm aware that the plugin is not really necessary I found it weird to generate erroneous code.

**Comment by flodiebold** [comment]
Not only that, if you don't have the module transformer, the flow transform will just remove the "type" from the import, resulting in
```javascript
import Foo from './bar';
```
You can also reproduce this by adding `syntax-flow` to the options.json in the strip-types test fixture and watching the tests fail.
