### ISSUE TITLE
Strict option on module transformers generates broken code

### ISSUE THREAD

**Issue by sorgloomer** [babel/babel#2939]
It looks like the strict option has multiple meanings on module transformers in `babe-core 6.1.2`.
First is related to `"use strict";` insertion, and the second is related to `__esModule`.

Switching strict to true adds `"use strict";` to the beginning, and removes the code that adds the `__esModule` marking to exports, but the `_interopRequireDefault` part stays, making the modules generated this way incompatible with themselves.

Gist: https://gist.github.com/sorgloomer/f86be2e62e2438a2ea72

**Comment by muzuiget** [comment]
It look like is the reason that translated code can't run Dojo 1.x. Dojo code complain the  

```
var childScripts = ctor && !ctor.prototype._noScript ? [] : null; // <script> nodes that are parent's children
```

`ctor.prototype` is `undefined`.

**Comment by sorgloomer** [comment]
In my case this code is generated by `[babel-plugin-transform-es2015-modules-amd,{strict:true}]`
```
'use strict';

define(['exports', '/Import'], function (exports, _Import) {
    var _Import2 = _interopRequireDefault(_Import);

    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

    exports.default = 'Export';
});
```

As you can see the only problem is that `_interopRequireDefault` will wrap all my modules in another object `{default: originalExports}`, because it still searches for the `__esModule` marker even in strict mode.

**Comment by muzuiget** [comment]
All right, I found the reason, it should be #2679, because Dojo 1.x don't has something like `interopRequireDefault()`.

**Comment by hzoo** [comment]
#2679 recommends https://www.npmjs.com/package/babel-plugin-add-module-exports to get around the `.default` issue but isn't needed if you are using module aware tool like webpack 2
