### ISSUE TITLE
Require hook not working with syntax in documentation.

### ISSUE THREAD

**Issue by constellates** [babel/babel#2944]
I was trying to use the require hook strategy for transpilation and kept getting errors relating to running es6 with node. I followed the documentation here http://babeljs.io/docs/usage/require/ . 

It specifies using

    require("babel-core/register");

It began working when I instead used

    require("babel/register");

Is this outdated documentation or are there other requirements to get this to work with only having the babel-core module?

**Comment by sebmck** [comment]
You're using 5.x when the documentation is for 6.x.
