### ISSUE TITLE
Which plugins are required with es2015 and stage-0 presets to use async/await?

### ISSUE THREAD

**Issue by rightaway** [babel/babel#2948]
To use async/await in the latest 6.1.2, I've seen different versions of how it should be set up.

Some people have just this

```
    "presets": [
      "es2015",
      "stage-0"
    ]
```

While others have

```
    "plugins": [
      "syntax-async-functions",
      "syntax-async-generators",
      "transform-async-to-generator"
    ],
    "presets": [
      "es2015",
      "stage-0"
    ]
```

I'm getting all kinds of errors when starting up the application so I thought I'd make sure my babelrc is correct before messing with it any further.

Have I added too much to babelrc or is there something I'm missing? I've tried looking at the babel website and github issues for guidance but I haven't been able to figure it out.

**Comment by hzoo** [comment]
If you look at the docs for http://babeljs.io/docs/plugins/preset-stage-3/ - it includes `"transform-async-to-generator"` so you shouldn't need to add it (stage 0 includes 1,2,3). You don't have to specify syntax-x either like it says here http://babeljs.io/docs/plugins/#transform

For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
