### ISSUE TITLE
Babel blacklist option gone in 6.x? 

### ISSUE THREAD

**Issue by Radivarig** [babel/babel#2951]
In webpack.config.js I was using `loaders:  ['babel', 'flowcheck', 'babel?blacklist=flow' ]` to combine babel with flowcheck-loader.

Because of the current `babel-plugin-typecheck` issue I have, I want to combine with `flowcheck`, and I see that there is no blacklist in [options API](http://babeljs.io/docs/usage/options/)

Is there some documentation on why is this removed, or how to achieve the same?

Thanks

**Comment by hzoo** [comment]
It was removed in updating the docs to 6.0 - http://babeljs.io/blog/2015/10/31/setting-up-babel-6/

**Comment by Radivarig** [comment]
Thanks

**Comment by Radivarig** [comment]
There is no mention of blacklist. That is why I asked

**Comment by hzoo** [comment]
Oh you wanted a reason why it was removed? http://babeljs.io/blog/2015/10/29/6.0.0/#opt-in-plugins - if you still want to use 5.x then it's there http://developit.github.io/babel-legacy-docs//docs/usage/options/

**Comment by Radivarig** [comment]
Yep, and looks like there is no way to replace the blacklist yet. Ty

**Comment by Radivarig** [comment]
"Remove optional, whitelist and blacklist options since plugins are now explicitly defined." [changelog](https://github.com/babel/babel/blob/f13ba90f17b6f561c7642dd5df74d4cb899b2cf9/CHANGELOG.md#600)

I define `presets: ['babel-preset-es2015']` but my type annotations get deleted, that is why flow needs to be blacklisted.

**Comment by hzoo** [comment]
They shouldn't be removed with only `es2015` (you would get a syntax error with only that anyway) - you would need http://babeljs.io/docs/plugins/transform-flow-strip-types/ enabled for it to be removed
