### ISSUE TITLE
Don't understand the test case of transform-es3-property-literals

### ISSUE THREAD

**Issue by hax** [babel/babel#2952]
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es3-property-literals/test/fixtures/property-literals/property-literals

The codes of `actual.js` and `expected.js` are just same and seems no relation with reserved words :astonished:

**Comment by sebmck** [comment]
See the README:

> The Babel issue tracker is exclusively for bug reports and feature requests.
