### ISSUE TITLE
TypeError: Converting circular structure to JSON _stringLiteral 

### ISSUE THREAD

**Issue by asendia** [babel/babel#2955]
Hi, I tried to slice string literal but get TypeError, is it intentional?
```javascript
`10`.slice(1); // TypeError`
'10'.slice(1); // OK
```

**Comment by asendia** [comment]
Got an exception when reverse splicing too
```javascript
[1, 2, 3, 4, 5].splice(-2, 1); // TypeError Cannot read property '_generated' of undefined
```

**Comment by hzoo** [comment]
First issue is the same as https://github.com/babel/babel/issues/2821 and 2nd is probably https://github.com/babel/babel/issues/2865 - should be fixed in the next release
