### ISSUE TITLE
compiler complains about comprehensions

### ISSUE THREAD

**Issue by rolandjitsu** [babel/babel#2956]
When I try to compile something that has a [generator comprehension](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Generator_comprehensions):
```js
let groups = new Set((for (item of items) item.group));
```
or an [array comprehension](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions):
```js
this.properties = [for (name of Object.keys(schema.properties)) {
	name,
	schema: schema.properties[name]
}];
```
The compiler complains about a syntax error:
```js
SyntaxError in plugin 'gulp-babel'
Message:
    /Users/rolag/Projects/iloop/src/app/common/directives/heatmap.js: Unexpected token (97:42)
```
The `.babelrc` file looks like:
```js
{
	"presets": [
		"es2015",
		"stage-0"
	],
	"plugins": [
		"syntax-async-functions",
		"syntax-async-generators",
		"syntax-class-properties",
		"syntax-do-expressions",
		"syntax-export-extensions",
		"syntax-object-rest-spread"
	]
}
```
Are comprehensions not supported yet? Or they are actually transformed but there is no syntax support yet?

**Comment by zloirock** [comment]
Comprehensions removed in `babel` 6. Looks like this proposal is dead.
