### ISSUE TITLE
I have the following error: ReferenceError: System is not defined - I am using module systemjs module plugin.

### ISSUE THREAD

**Issue by phenrigomes** [babel/babel#2957]
My class transformed is:

```javascript
'use strict';

System.register(['koala/util/cluster', 'koala/settings/SettingsLoader'], function (_export) {
    var cluster, SettingsLoader;
    return {
        setters: [function (_koalaUtilCluster) {
            cluster = _koalaUtilCluster.default;
        }, function (_koalaSettingsSettingsLoader) {
            SettingsLoader = _koalaSettingsSettingsLoader.default;
        }],
        execute: function () {
            cluster(function () {
                console.log(SettingsLoader, '#');
            });
        }
    };
});
```

Where System.register is loaded?

**Comment by silenceisgolden** [comment]
https://github.com/systemjs/systemjs/blob/master/dist/system-register-only.js and https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/production-workflows.md#systemregister-output

Include system-register-only.js before your systemjs-formatted module

**Comment by hzoo** [comment]
Babel just transforms import/exports to the module type you are using so you will need to look at the docs for the one you are using. Maybe check the links @silenceisgolden posted?

This isn't a bug so I'm going to close.

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.
>
> The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
>
> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.
