### ISSUE TITLE
ReferenceError: [BABEL]

### ISSUE THREAD

**Issue by cameronjroe** [babel/babel#2959]
Babel keeps throwing this and I have no idea why? The following plugins are clearly installed:

```
"babel-core": "^6.1.2",
"babel-preset-es2015": "^6.1.2",
"babelify": "^7.2.0",
"grunt-browserify": "^4.0.1",
```

.babelrc
```
{
  "preset": ["es2015"]
}
```

**Comment by hzoo** [comment]
There isn't enough information here - does the stack trace literally only say "ReferenceError: [BABEL]"? Can't really tell what's going on here - what are you running?

**Comment by cameronjroe** [comment]
```
Unknown option: /path/.babelrc.preset while parsing file: /path/js/_index.js
```

**Comment by hzoo** [comment]
Ok you need to use "presets"

**Comment by cameronjroe** [comment]
Wow... Thanks.

**Comment by hzoo** [comment]
For reference http://babeljs.io/docs/usage/options/
