### ISSUE TITLE
Sourcemap chain is broken with plugins prior to babel only for files in folders

### ISSUE THREAD

**Issue by EricABC** [babel/babel#2964]
When going from TypeScript -> (gulp-typescript) -> ES6 -> (gulp-babel ES2015) -> ES5, sourcemaps are incorrect only for files inside folders.  This is using gulp-sourcemaps.  I would have thought it has more to do with one of the gulp components, but despite all the parties involved I think I have narrowed it down to occurring inside babel.transform by watching correct values go in (the call made [here in gulp-babel](https://github.com/babel/gulp-babel/blob/master/index.js#L30)).  I also dropped in an uglify step at the end just to see if it was related to gulp-sourcemaps, but uglify was able to succesfully get back two stages.  I did vary path settings such as gulp.src base and sourcemap write paths, in case I was missing something with configuration, but all cases i tried seemed to reproduce the same issue.

```
var gulp = require('gulp');
var maps = require('gulp-sourcemaps');
var tsc = require('gulp-typescript');
var babel = require('gulp-babel');

gulp.task('dostuff', function () {
    return gulp.src(['./src/**/*.ts'])
        .pipe(maps.init())
        .pipe(tsc(tsc.createProject('tsconfig.json')))
        .pipe(babel({ presets: ["es2015"] }))
        .pipe(maps.write('.'))
        .pipe(gulp.dest('./src'));
});
```

Also, a gist for simple reproduction with tsconfig and such: https://gist.github.com/EricABC/5944557c5b54ddba7616
The _ in file names is the path (but basically just put any TS file in a root 'src' folder, and another in 'src/nested').

You will see the 'src/file.js.map' can map to the ts file, but 'src/nested/nestedfile.js.map' goes the the interim ES6 javascript.

Also of interest, [Here in gulp-typescript is a line of code with comments](https://github.com/ivogabe/gulp-typescript/blob/master/release/output.js#L82) that specifically addresses an issue where further plugins not in the root could be affected.

**Comment by hzoo** [comment]
Going to close for inactivity/old, maybe similar to https://github.com/babel/babel/issues/5408, otherwise can open a new issue with repro.
