### ISSUE TITLE
Patterns as operands of the rest parameters

### ISSUE THREAD

**Issue by vhf** [babel/babel#2965]
[regression][bug?]

These two used to work:

```javascript
const OK = Symbol();
function f(x, y, ...[arity=OK]) {
    if (arity !== OK) {
        throw new Error();
    }
}
```

```javascript
let [x, ...[y, z]] = [1, 2, 3, 4];
```

`SyntaxError: unknown: Unexpected token` pointing to the `[` immediately following the `...`.

This bug is present in `babel-cli 6.1.2 (babel-core 6.1.2)`. I did not trace this to the first faulty commit.

I discovered this while working on #2833, which I'll amend when this issue has been either fixed or wontfixed.

According to some sources [[0]] [[1]], the above code is valid ES2015 syntax/grammar. According to others [[2]], it's not.

[0]: http://www.2ality.com/2015/01/es6-destructuring.html
[1]: https://github.com/babel/babel/issues/550
[2]: https://github.com/Microsoft/TypeScript/issues/2519

**Comment by sebmck** [comment]
Neither. It's not valid. Grammar is define [here](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-statements) as `BindingRestElement`.
