### ISSUE TITLE
Cannot place a breakpoint with babel 6.x.x in node inspector

### ISSUE THREAD

**Issue by tsm91** [babel/babel#2968]
On the weekend i tried to upgrade my project to the newly relased babel 6. 

I am using the [require hook](https://babeljs.io/docs/usage/require/) approach. `require('babel-core/register')`

Everything transforms as before, but in node-inspector i am not allowed to place any breakpoints anywhere in the affected files which are being transpiled. For example in the bootstrap.js in which i place this require hook is not being transformed thus i can place a breakpoint there.

I am using:
node js v5.0.0
node-inspector v0.12.3 
babel v6.0.15 
babel-core v6.1.2 with es2015 and stage-0 presets

EDIT: 
Here you can find the [reproduction repo](https://github.com/tsm91/babel-bug-reproduction).
Also opened a ticket for the node-inspector repo [#771](https://github.com/node-inspector/node-inspector/issues/771)

**Comment by sebmck** [comment]
There's not enough information here. Please put together a reproduction repo with code and minimum steps to reproduce.

**Comment by tsm91** [comment]
@sebmck sorry for being late, there is the [reproduction repo](https://github.com/tsm91/babel-bug-reproduction). You can find instructions in the readme.

i update the original question too.

**Comment by tsm91** [comment]
@sebmck did you have the time to investigate this case?

**Comment by daviddahl** [comment]
What happens when you use `mocha debug --compilers, etc...` and use the node v8 debugger in the console?

**Comment by hzoo** [comment]
Going to close for inactivity, hopefully using the `node --inspect --debug` in latest node solves this?
