### ISSUE TITLE
using external helpers 2 in the browser

### ISSUE THREAD

**Issue by rolandjitsu** [babel/babel#2973]
Before the 6 release we could simply include the `node_modules/babel-core/external-helpers.js` file as a script and everything worked great, but with the latest release and external-helpers-2 I have no clue how to make it work.

How do I include external-helpers-2 in the browser when using Babel 6?

**Comment by sebmck** [comment]
See #2768. Also see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
