### ISSUE TITLE
requiring a file that has a default exported class gives an object instead of a function

### ISSUE THREAD

**Issue by julienvincent** [babel/babel#2975]
If I have a file `file1.js` that looks like this:

```javascript
export default
class File1 {

    constructor() {
        console.log('run')
    }
}
```

and I import this using `require()` from another file `file2.js`:

```javascript
class File2 {

    constructor() {

        let file1 = require('./file1.js');
        console.log(file1);
    }
}
new File2();
```

Then instead of getting a function I can call `new file1()` on, I get an object that looks like this:

```javascript
{ default: [Function: File1] }
```

Which means I need to instead call `new file1.default()` in order to instantiate it

**Comment by sebmck** [comment]
This is expected behaviour. See #2212.
