### ISSUE TITLE
who can tell me wtf is going on?

### ISSUE THREAD

**Issue by geminiyellow** [babel/babel#2976]
i use npm install babel-core, it tell me the latest version is 

```
babel-core  ^6.1.2  →  ^6.1.4 
```

install, it tell me `'babel-register' is not in the npm registry.`
then i delete the `node_modules`, re-install, 
it tell me 
```
No compatible version found: babel-types@^6.1.4
npm ERR! Valid install targets:
npm ERR! 6.1.2, 6.0.19, 6.0.18, 6.0.17, 6.0.15, 6.0.14, 6.0.13, 6.0.12, 6.0.2
```

**Comment by agdolla** [comment]
me too but I also get other errors like:
npm ERR! No compatible version found: babel-traverse@^6.1.4
npm ERR! Valid install targets:
npm ERR! 6.1.2, 6.0.20, 6.0.19, 6.0.18, 6.0.17, 6.0.16, 6.0.14, 6.0.2

**Comment by bpasero** [comment]
I cannot install babel-cli anymore... whats on?

**Comment by sebmck** [comment]
[I'm still publishing all the packages.](https://twitter.com/sebmck/status/664388201801388032)

**Comment by sebmck** [comment]
Done.
