### ISSUE TITLE
6.1.4 miss 'babel-runtime/helpers/typeof' ?

### ISSUE THREAD

**Issue by ustccjw** [babel/babel#2986]
error like:

````
Cannot resolve module 'babel-runtime/helpers/typeof'
````

**Comment by thelinuxlich** [comment]
Me too, same error

**Comment by tomkis1** [comment]
I guess it's same problem as https://github.com/babel/babel/issues/2984 here

**Comment by Poky85** [comment]
This issue references #2984 and #2984 is closed in favor of this issue :-)

Same problem here. I got this
```
Uncaught Error: Cannot find module "babel-runtime/helpers/extends"
```

I have these dependeces installed:

"babel-core": "^6.0.16",
"babel-loader": "^6.0.0",
"babel-plugin-transform-runtime": "^6.0.16",
"babel-preset-es2015": "^6.0.15",
"babel-preset-react": "^6.0.15",
"babel-runtime": "^6.0.14",

Fixing babel-runtime to previous version 6.0.14 fixed the problem.

**Comment by hzoo** [comment]
I closed it since the OP fixed since his original issue by including `plugins": ["transform-runtime"]` so it's a different issue at that point.

**Comment by manutenfruits** [comment]
I am having this issue as well. I added `transform-runtime` to the `plugins` in `.babelrc` but looking at `npm list` it appears that the version of `babel-runtime` being installed is `5.8.29`, even though the plugins dependant on it are on `6.1.4` (including `babel-plugin-transform-runtime`).
