### ISSUE TITLE
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'

### ISSUE THREAD

**Issue by thealjey** [babel/babel#2989]
I'm using the latest everything:
NodeJS 5.0.0
NPM 3.3.12
babel-runtime 6.1.4
babel-register 6.1.4

when running anything with `babel-node` I get the following errors:
```
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Object.<anonymous> (babel-register/lib/node.js:5:30)

Error: Cannot find module 'babel-runtime/helpers/interop-require-wildcard'
    at Object.<anonymous> (babel-register/lib/node.js:7:31)
```

The reason this happens is that the files are actually named `interopRequireDefault.js` and `interopRequireWildcard.js` respectively.
If I rename them to `interop-require-default.js` and `interop-require-wildcard.js` the errors go away.

Other than that everything seems to work just fine.

**Comment by thewillhuang** [comment]
Hello im trying to run mocha tests and i was getting the same error 
```
> mocha --compilers js:babel-core/register 'test/**/*.@(js|jsx)'

module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)

```
```bash
$ mocha --compilers js:babel-core/register 'test/**/*.@(js|jsx)'
```

it used to work until a few hours ago before the update

turns out renaming the two files inside node modules was the fix

**Comment by thealjey** [comment]
@sebmck I don't know why this issue was closed, because the problem still persists.
I did a complete reinstall of all the node modules and I'm still getting this error.

**Comment by thealjey** [comment]
It seems weird to me, that even though I'm the initial author of this issue, I cannot reopen it.
I realize that you are the owner of the repository, however, I guess then there should be an option for you to not only close it, but to also allow or forbid reopening it.

This is really a Critical bug for me (and I'm sure for other people as well), it just isn't right having to go into the node_modules directory to rename files in it.

**Comment by sebmck** [comment]
@thealjey It was closed because I fixed it in the attached commit. I've only just (in the last 20 minutes) been able to do a release.

**Comment by thealjey** [comment]
@sebmck it does indeed work now :blush: 
sorry for panicking, I just didn't expect for something like this to creep up into an npm build
especially not in a project like this
