### ISSUE TITLE
Settings to plugins in presets

### ISSUE THREAD

**Issue by kibin** [babel/babel#2990]
I can see from source code that preset now is a bunch of requires and there is no option to pass settings to specific plugin in it.
As a workaround I’m installing plugins that I want to pass settings separately, but it’s not convenient and such a way presets become quite meaningless.

**Comment by jmm** [comment]
Hello @kibin, welcome to the Babel community! That is the way it's designed to work. Because of that, and especially because there's already an issue for this, I'm going to close this one. See https://github.com/babel/babel/issues/2756.
