### ISSUE TITLE
jsx-source plugin breaks React PureRenderMixin

### ISSUE THREAD

**Issue by dandelany** [babel/babel#2994]
It looks like the `jsx-source` plugin was recently added to the `babel-preset-react` preset. This is causing performance problems for me on all my apps which use React's PureRenderMixin.

PureRenderMixin implements shouldComponentUpdate so that React components only get re-rendered if their old props === their new props. The `jsx-source` plugin adds a new prop called `__source` to all of my components, which has a new object reference on every update - therefore *all* of my components *always* get re-rendered since the `__source` prop always changes.

Am I doing something wrong here? This seems like a pretty major issue which would affect anyone using PureRenderMixin (ie. lots of people, as this is an FB-recommended optimization).

Thanks for your help!

**Comment by hzoo** [comment]
It does only run in dev mode so it won't be a problem elsewhere like in prod.

@jimfb

**Comment by spicyj** [comment]
@dandelany Are you on React 0.14? If so, React should pull `__source` out like it does `key` and `ref`.

We might need to do something else for React 0.13 users… I suppose we can just make it the same object each time which is probably good enough.

**Comment by dandelany** [comment]
Thanks for the responses @hzoo and @spicyj . My project is still on React 0.13.3, I didn't realize this had changed in 14. I'm going to see if I can update it to React 0.14 today, but you're right - it would be nice if this also worked for 0.13 users.

**Comment by spicyj** [comment]
Yes, we should obviously not regress 0.13 support.

**Comment by sebmck** [comment]
I've commented out the `env` config from `babel-preset-react` as there's multiple issues associated it. I'll talk with a few people and work out what to do in the next couple days.

**Comment by spicyj** [comment]
Thanks!

**Comment by dandelany** [comment]
Great, thanks again for the help.
