### ISSUE TITLE
Object rest spread not working correctly.

### ISSUE THREAD

**Issue by TylorS** [babel/babel#2996]
A few of us (@Frikki, @Cmdv) working on updating dependencies at https://github.com/cyclejs/cycle-dom, in particular the auto-scope branch, have run into a issue where object-rest-spread works with babel 5.8 but no longer works with 6.1.4.

.babelrc
```json
{
 "presets": [ "es2015" ],
 "plugins": [
    "syntax-object-rest-spread",
    "transform-object-rest-spread"
  ]
}
```

Using the above .babelrc does not allow for this usage

```js
import h from 'snabbdom/h'
const hh = require('hyperscript-helpers')(h)
....
...
export {
  h,
  ...hh
}

```

`hh` is an object which can be destructured like so and works as expected
```js
const { div, span, h1, p } = hh;
```

Thank you for your time, and hope to hear from you guys soon!

**Comment by hzoo** [comment]
Are you getting a syntax error? I'm getting a syntax error for that in the [repl](http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=import%20h%20from%20'snabbdom%2Fh'%0Aconst%20hh%20%3D%20require('hyperscript-helpers')(h)%0A%0Aexport%20%7B%0A%20%20h%2C%0A%20%20...hh%0A%7D%3B) and in http://astexplorer.net/ which both use babel 5.x

**Comment by TylorS** [comment]
Yes, I"m getting a syntax error with babel 6

**Comment by TylorS** [comment]
Ahh sorry this doesn't workin babel 5 either...closing

**Comment by hzoo** [comment]
Exports don't use destructuring like in `let {a} = b;` You could define a variable and then export it which would work
