### ISSUE TITLE
Missing class properties transform

### ISSUE THREAD

**Issue by tleunen** [babel/babel#3000]
Getting this error using Babel 6
```
SyntaxError: MyClass.js: Missing class properties transform.
  29 | 
  30 | class MyClass extends React.Compoennt {
> 31 |     static propTypes = {
     |     ^
```
with the babelrc like this. I heard the order was important?
```
{
  "presets": [
    "stage-0",
    "es2015",
    "react"
  ]
}
```
```
    "babel": "^6.0.15",
    "babel-cli": "^6.1.4",
    "babel-preset-es2015": "^6.1.4",
    "babel-preset-react": "^6.1.4",
    "babel-preset-stage-0": "^6.1.2",
```

class properties are inside stage-1 which is imported by stage-0... So I'm not sure to understand why I get this error...

**Comment by sebmck** [comment]
Can you try moving `stage-0` down to after `es2015`.

**Comment by tleunen** [comment]
Indeed, it works if `stage-0` is after `es2015`.
