### ISSUE TITLE
Throws error when compiling an expression like `1.0.toPrecision`

### ISSUE THREAD

**Issue by sherlock917** [babel/babel#3002]
When i tried to compile es5-js, babel throws an error of `Module parse failed`. The reason is this expression `1.0.toPrecision`.

More specific discussion is [here](https://github.com/es-shims/es5-shim/issues/343).

**Comment by ljharb** [comment]
Specifically: http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&code=1.0.toPrecision(3)%3B%0A1.1.toPrecision(3)%3B%0A1..toPrecision(3)%3B%0A(1.0).toPrecision(3)%3B&playground=false

**Comment by sebmck** [comment]
Fixing.

**Comment by ljharb** [comment]
Thanks!

**Comment by sebmck** [comment]
Fixed in Babel 6.1.5 (publishing it atm) and backported and released as 5.8.34.

**Comment by ljharb** [comment]
<3 for fixing both branches
