### ISSUE TITLE
babel-helper-plugin-test-runner does not work for third-party plugins

### ISSUE THREAD

**Issue by martinandert** [babel/babel#3007]
Given my `test/fixtures/options.json` looks like this:

```json
{
  "plugins": ["my-plugin"]
}
```

When running mocha, it tries to load my plugin from `/home/me/Projects/babel-plugin-my-plugin/node_modules/babel-helper-plugin-test-runner/node_modules/babel-helper-transform-fixture-test-runner/lib/../../babel-plugin-my-plugin`, which doesn't exist.

I'm currently hacking the `options.json` like this in order to make it work:

```json
{
  "plugins": ["syntax-jsx/../../../../../babel-plugin-my-plugin"]
}
```

**Comment by sebmck** [comment]
It's not meant to.
