### ISSUE TITLE
incorrect class compilation

### ISSUE THREAD

**Issue by Daniil-Pabolkov** [babel/babel#3008]
I have following.babelrc:
```
{
	"presets": [
		"es2015",
		"stage-0"
	],

	"plugins": [
		"transform-es2015-modules-umd",
		["transform-es2015-classes", { "loose": true }],
		"transform-class-constructor-call",
		"transform-regenerator"
	]
}
```
and gulpfile.js:
```
gulp.task('es7', () => {
	return gulp.src('./src/js/**/*.js')
		.pipe(babel())
		.pipe(concat('app.js'))
		.pipe(gulp.dest('./assets'))
	;
});
```
Also, I have following such javascript:
```
class IArr extends Array {

	push(...args) {
		for (let i = 0, il = args.length; i < il; ++i) {
			if (/^\d+/.test(args[i])) {
				super.push(args[i]);
			}
			else {
				console.error(`Value ${args[i]} not is integer`);
			}
		}
		return this;
	}
}
```
It compile to:
```
var IArr = (function (_Array) {
	_inherits(IArr, _Array);

	function IArr() {
		_classCallCheck(this, IArr);

		return _possibleConstructorReturn(this, _Array.apply(this, arguments));
	}

	IArr.prototype.push = function push() {
		for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
			args[_key] = arguments[_key];
		}

		for (var i = 0, il = args.length; i < il; ++i) {
			if (/^\d+/.test(args[i])) {
				_Array.prototype.push.call(this, args[i]);
			} else {
				console.error('Value ' + args[i] + ' not is integer');
			}
		}

		return this;
	};
```
And _possibleConstructorReturn look like that:
```
function _possibleConstructorReturn(self, call) {
		if (!self) {
			throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
		}

		return call && ((typeof call === 'undefined' ? 'undefined' : _typeof(call)) === "object" || typeof call === "function") ? call : self;
	}
}
```
What and why?
If I use inheritance, then constructor will return super class always!!! And all my life falling down...
```
let arr = new IArray;
console.log(arr instanceof IArray);    // print 'false';
console.log(arr.push);                       // print 'function push() { [native code] }';
console.log(IArray.prototype.push); 
/* print:
function push() {
			for (var i = 0, il = arguments.length; i < il; ++i) {
				if (!isNaN(parseint(arguments[i]))) {
					_Array.prototype.push.call(this, arguments[i]);
				} else {
					console.erro…
*/
```
I don't understand, where I make mistakes? Or, maybe, it's bug...

P.S.: Sorry for my English

**Comment by sorgloomer** [comment]
Based on this question on SO
http://stackoverflow.com/questions/4761000/is-this-a-reasonable-way-to-subclass-a-javascript-array

I am afraid you cannot subclass `Array`s in JavaScript. Depending on requirements you could use composition, define an array-like objects, or extend `Array.prototype`

The reason is that the `Array` constructor will return an array instance even when called with apply, no matter what object you supply as `this` arg. Calling apply on `Array` will not alter the object given as this arg.

disclaimer: the above information is based on a 2 minute research and my preconceptions about javascript so in fact I might be wrong

**Comment by mlegenhausen** [comment]
Take a look at: http://www.2ality.com/2015/02/es6-classes-final.html

There is also mentioned that the transpilation support seems poor. Take also a look at `Symbol.species`.

**Comment by adrianp** [comment]
I'm experiencing the same issue when sub-classing `Error`. The following code:

```
class Foo extends Error {
	constructor(message = 'Foo!') {
		super();
		this.name = 'Foo';
		this.message = message;
	}
}

const t = new Foo();
console.log(t instanceof Foo);
```

is transpiled to:

```
'use strict';

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var Foo = (function (_Error) {
        _inherits(Foo, _Error);

        function Foo() {
                var message = arguments.length <= 0 || arguments[0] === undefined ? 'Foo!' : arguments[0];

                _classCallCheck(this, Foo);

                var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(Foo).call(this));

                _this.name = 'Foo';
                _this.message = message;
                return _this;
        }

        return Foo;
})(Error);

var t = new Foo();
console.log(t instanceof Foo);
```

in Babel 6.1.4 (babel-core 6.1.4) and upon execution `false` is printed. In Babel 5 the code worked correctly:

![screenshot_2015-11-12_12-37-02](https://cloud.githubusercontent.com/assets/480478/11116253/1989a2b0-893a-11e5-9996-13de4d640586.png)

My .babelrc file is:
```
{
        "presets": ["es2015", "stage-0"]
}
```

with:
```
babel-polyfill@v6.0.16,
babel-preset-es2015@6.1.4,
babel-preset-stage-0@6.1.2
```

**Comment by Daniil-Pabolkov** [comment]
Ok, I understand. In case, when I use class CustomArray extends Array - it's not working because primitives return (if called <Primitive>.apply(this, arguments)) self instance. 
![node](https://cloud.githubusercontent.com/assets/15813062/11136697/98f2d2a2-89fc-11e5-90e1-7de48fe74f1e.png)
In the picture you can see, that node.js@5.0.0 correctly interprets class, which inherits from Array.

**Comment by loganfsmyth** [comment]
Babel does not support subclassing builtin objects like `Array`, `Error` and such. That can only be accomplished by using true native ES6 classes on a platform that supports them.

Subclassing arrays didn't work in v5 either, they just didn't work in a slightly different way.

```
class MyArray extends Array {}

var a = new MyArray();
var b = new Array();

a[4] = 4;
b[4] = 4;

// a.length === 0
// b.length === 5
```

Note, the `length` setter no longer works as expected.
