### ISSUE TITLE
Cannot install babel-cli

### ISSUE THREAD

**Issue by brickyang** [babel/babel#3014]
I was running `npm install -g babel-cli` and the shell shows `npm WARN install Couldn't install optional dependency: Unsupported`

When the process runs to about 7-80%, `extract → gunzTarPerm` it stoped and throw `killed`

My server is CentOS 6.5 with single core CPU and 1GB RAM. Npm version is 3.3.6(in fact I install latest npm which should be 3.3.12, but the `npm -v` just shows 3.3.6)

**Comment by forivall** [comment]
The `WARN` is just about [chokidar](https://github.com/paulmillr/chokidar) not being able to install the osx-specific file watcher. You can safely ignore that warning.

**Comment by sebmck** [comment]
What @forivall said.

**Comment by brickyang** [comment]
@forivall it's not just the `WARN`. I cannot complete the installation.

```
extract → gunzTarPerm     ▌ ╢██████████████████████████████████░░░░░░░░░░░░░░░╟
已杀死(killed)
```

the processing stopped here and quit. The `babel-cli` didn't been installed. Use `babel` command will show

```
The CLI has been moved into the package `babel-cli`.

$ npm install -g babel-cli
```
