### ISSUE TITLE
Allow disabling specific plugins in a preset

### ISSUE THREAD

**Issue by taion** [babel/babel#3016]
Apologies if this is a bit XY-problem-y.

I'd like to be able to generate a build with ES6 modules, that otherwise is transpiled into something run more broadly. This would be for webpack 2, rollup, &c.

It seems like the cleanest way to configure this would be to start with the `es2015` preset, but drop the transform of ES6 modules to CJS.

I understand that I can do this by defining my own alternative preset, but that seems suboptimal relative to applying a delta to the existing preset.

Am I missing something?

**Comment by hzoo** [comment]
Right now the intention of the preset is to allow people to use it without customization - if you want to modify it then you'll have to just define plugins yourself or make your own preset.

**Comment by taion** [comment]
Is that ideal? I can certainly copy/paste the `es2015` preset, or even define my own that strips out the exported module transform.

For the former, though, I'm concerned about drift; the latter just seems hacky.

**Comment by sebmck** [comment]
There's no way for us to identify a plugin since they have no UIDs and are indistinguishable from one another. As @hzoo said if you want to blacklist plugins from a preset then you probably shouldn't be using that preset.

**Comment by taion** [comment]
Fair enough, thanks.

The recommendation remains to make a copy of the es2015 preset and just delete the plugin I don't want?

In that case, is there a good way to ensure that things otherwise stay in sync?

**Comment by hzoo** [comment]
I guess to @taion's point the cjs transform wasn't in the preset initially but added I think since everyone was confused and it would be a good default. https://github.com/babel/babel/commit/198025aea91f8b1f36a1d95203eb8a25e61bee04

Also the es2015 preset probably won't change if at all

**Comment by taion** [comment]
IMO it makes perfect sense to have that in the preset for convenience (although I can see why it might not be the cleanest architectural choice). The pain point is in not being able to disable it if I want to target webpack 2 or rollup.

I guess in practice I'm getting worried about nothing though, since it would be really bizarre for es2015 to change. I'll just copy the preset as I need.

**Comment by kruncher** [comment]
Pity that there isn't a way to disable undesirable plugins since creating a fork of the preset seems undesirable just to disable a single plugin like this:
```
  "babel": {
    "presets": [
      "es2015"
    ],
    "disablePlugins": [
        "babel-plugin-transform-es2015-modules-commonjs"
    ]
  }
```

But since at least two people want this same thing; perhaps we should create a new preset: **es2015-without-commonjs** ?

**Comment by malyw** [comment]
https://www.npmjs.com/package/modify-babel-preset
