### ISSUE TITLE
"no writecb in Transform class" when trying to run gulp-babel

### ISSUE THREAD

**Issue by doberkofler** [babel/babel#3017]
I just upgraded to the latest version of gulp-babel and babel-preset-es2015 and when running gulp-babel, I now get the following error message: `no writecb in Transform class`.
I assume, it has something to do with npm dependencies but also uninstalling all modules, removing the node_modules directory and reinstalling did not solve the problem. Any help is appreciated!

node: 4.2.1, npm: 3.3.9, gulp: 3.9.0, gulp-babel: 6.1.0, babel-core: 6.1.4, babel-preset-es2015: 6.1.4

**Comment by sebmck** [comment]
This error cannot come from Babel. I'd recommend following it up with gulp.
