### ISSUE TITLE
'es2015-no-polyfill' preset

### ISSUE THREAD

**Issue by dburrows** [babel/babel#3019]
When and when not to use the babel-polyfill has always been a bit confusing. As Babel 6 has introduced presets can we add a 'es2015-no-polyfill' or similar preset that only enables features that don't require polyfilling?

I'd write it myself but I don't have a strong grasp of what does/doesn't require a polyfill in v6.

**Comment by hzoo** [comment]
The polyfill is just regenerator and core-js so I'm not sure why you can't just use the es2015 preset? If using the transforms in the es2015 preset requires the polyfill then it's probably a bug?

**Comment by dburrows** [comment]
The es2015 preset page* lists transform-regenerator as enabled, which says it uses the regenerator module. If I compile some code that uses generators is this inlined? Or do I need to use the polyfill?

On the v5 website it also mentioned some issues with for...of and super, that page seems to have disapeared on the v6 site. 


* http://babeljs.io/docs/plugins/preset-es2015/

**Comment by GGAlanSmithee** [comment]
If you don't use generators, there is no code to be transpiled to use regenerator, so then you don't need to include the polyfill?

**Comment by dburrows** [comment]
The point is to limit compilation to features that don't need the polyfill, not wait till runtime and be surprised. The environment I'm working in makes using the polyfill problematic at the moment

**Comment by sebmck** [comment]
This isn't something that's going to be supported. What requires a polyfill is completely arbitrary as it completely depends on what environment you intend on supporting. This is a decision that you need to make.

**Comment by dburrows** [comment]
That doesn't make sense - why supply an official polyfill at all if that's your stance?

**Comment by thejameskyle** [comment]
> why supply an official polyfill at all if that's your stance?

Because having a polyfill and not wanting to do something very specific with it are not incompatible.

**Comment by dburrows** [comment]
OK, all I really want is a list of what Babel transforms output code that needs a polyfill in a standard ES5 environment - if that's not available I'll do it myself.
