### ISSUE TITLE
Ignore some of the plugins defined in a preset

### ISSUE THREAD

**Issue by ppoliani** [babel/babel#3020]
It would be nice to have an option of ignoring some of the plugins that are in a preset. For example, If I want to ignore one of the plugins defined in the `es2015` preset I have to manually add all but that one to the `plugins` array. 

What would look better is to have something like the old `blacklist` option where you can put the plugins from a specific preset that you don't want to be used.

**Comment by hzoo** [comment]
This is the same as https://github.com/babel/babel/issues/3016
