### ISSUE TITLE
npm wierdness

### ISSUE THREAD

**Issue by guyellis** [babel/babel#3027]
I'm trying to understand why this is happening:

```
$ npm i babel --save
babel@6.1.5 node_modules/babel

$ npm outdated
Package  Current  Wanted  Latest  Location
babel      6.1.5  6.1.15   6.1.5  babel
```

Why is wanted 6.1.15 and the latest published according to NPM is 6.1.5?

**Comment by sebmck** [comment]
Apparently npm is weird and has different before for the npm tags `stable` and `latest`. The npm tags have been cleared and fixed as of 6.1.18
