### ISSUE TITLE
Object.entries polyfill

### ISSUE THREAD

**Issue by bluejamesbond** [babel/babel#3036]
How to enable Object.entries polyfill?

**Comment by zloirock** [comment]
Babel uses [`core-js`](https://github.com/zloirock/core-js), `core-js` [contains `Object.entries`](https://github.com/zloirock/core-js#ecmascript-7), so you can just use [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) or [`babel-runtime`](http://babeljs.io/docs/plugins/transform-runtime/). For questions use [slack](https://babeljs.slack.com).
