### ISSUE TITLE
--no-commens @ babel 6.1.18

### ISSUE THREAD

**Issue by vovagp** [babel/babel#3037]
vovagp@deb864:/tmp/test$ babel -V
	6.1.18 (babel-core 6.1.19)
	vovagp@deb864:/tmp/test$ babel --help | grep "no-comments"
	    --no-comments                        strip/output comments in generated output (on by default)

But --no-comments off by default :)

	vovagp@deb864:/tmp/test$ cat test.js 
	// comment 1
	// comment 2

	function hello(a, b = 1)
	{
		console.log(a + b)
	}

	vovagp@deb864:/tmp/test$ babel --presets es2015,stage-0 test.js -o test.out.js
	vovagp@deb864:/tmp/test$ cat test.out.js 
	"use strict";

	// comment 1
	// comment 2

	function hello(a) {
		var b = arguments.length <= 1 || arguments[1] === undefined ? 1 : arguments[1];

		console.log(a + b);
	}
	vovagp@deb864:/tmp/test$ babel --presets es2015,stage-0 --no-comments test.js -o test.out.js
	vovagp@deb864:/tmp/test$ cat test.out.js 
	"use strict";

	function hello(a) {
		var b = arguments.length <= 1 || arguments[1] === undefined ? 1 : arguments[1];

		console.log(a + b);
	}

**Comment by sebmck** [comment]
Huh? You've just proven that this option works as intended.

**Comment by SimenB** [comment]
(I think) he means that the option in help says `(on by default)`, while it's actually off

**Comment by t128** [comment]
but the *comments* are *on* by default ;)
