### ISSUE TITLE
Calling functions as MemberExpressions fails as invalid

### ISSUE THREAD

**Issue by AlexGilleran** [babel/babel#3038]
Hi, thanks for all the great work - really like the new direction of Babel. Currently I'm in the process of trying to upgrade my plugin http://www.github.com/valtech-au/jsx-control-statements to Babel 6, which involves changing pretend `<For of={anArray} each="item">` elements to `Array.map` calls like this:

```javascript
anArray.map(function (item) {
  // (returns child of element)
}, this);
```

Which I used to do like this:

```javascript
t.memberExpression(
  of.value.expression,
  t.callExpression(
    t.identifier('map'),
    [
      t.functionExpression(
        null,
        mapParams,
        t.blockStatement([
          t.returnStatement(child)
        ])
      ),
      t.identifier('this')
    ]
  )
);
```

However with Babel 6 I get `TypeError: E:/Workspaces/jsx-control-statements/spec/fixtures/for.jsx: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "CallExpression"`

Which appears to be as a result of how validation is setup in `MemberExpression` in `babel-types/lib/definitions/core.js`:

```javascript
property: {
  validate(node, key, val) {
    let expectedType = node.computed ? "Expression" : "Identifier";
    assertNodeType(expectedType)(node, key, val);
  }
}
```

... this seems to only let MemberExpressions use properties of objects rather than calling functions on them. If I go into my own node_modules and remove the validation it works fine for my use case. Is this intentional because there's some better way to do what I need to do, or is it a bug?

If it's the latter then it should be a quick fix, happy to do a PR.

**Comment by sebmck** [comment]
[See the README](https://github.com/babel/babel#looking-for-support). You're producing invalid AST nodes, the error is correct.
