### ISSUE TITLE
the latest release dose not support safari in ios8

### ISSUE THREAD

**Issue by lilee** [babel/babel#3039]
The bellow is the test code
```
import React from 'react'
import { render } from 'react-dom'

class Test extends React.Component {
    render() {
        return <div>hello</div>
    }
}

render(<Test />, document.getElementById('root'))
```

**Comment by sebmck** [comment]
We need more information. What do you mean by "not support"? Is it throwing an error? What is the actual problem.

**Comment by lilee** [comment]
because it's safari on mobile, I can't see the error. 

The page does not show the "hello" but is blank.

**When I degrade the babel-core to ^5.2.2 and then upgrade it to ^6.1.19 (not remove the babel-core of 5)。It works**

**Comment by jmarquis** [comment]
Assuming there are no compile errors, you can view the phone's Safari error console if you have a Mac...

1. On your phone, go to Settings → Safari → Advanced and turn on Web Inspector.
2. On your Mac, open Safari's preferences, tab to Advanced and check Show Develop menu in menu bar.
3. Plug your phone into your Mac and open the page on your phone.
4. In Safari on your Mac, go to Develop → [Your iPhone] → [whatever the tab is titled] and check out the console. You may need to refresh the page on the phone to get anything to show up.
5. Paste any errors you see here so @sebmck or someone else can figure out what's going on.

I'd do it myself but I only have iOS 9 and everything is working fine.

**Comment by lilee** [comment]
I do remove the ```babel-core``` and use ```npm install babel-core --save-dev``` it again, the version is ```^6.1.20``` and it's works
