### ISSUE TITLE
Assigning to rvalue in async/await functions

### ISSUE THREAD

**Issue by fanatid** [babel/babel#3040]
Code ([on babeljs.io/repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=%28async%20function%20%28%29%20{%0A%20%20let%20a%2C%20b%0A%20%20await%20Promise.resolve%28%29%0A%20%20[a%2C%20b]%20%3D%20[1%2C%202]%0A%20%20console.log%28a%2Cb%29%0A}%29%28%29)):
```js
(async function () {
  let a, b
  await Promise.resolve()
  [a, b] = [1, 2]
  console.log(a,b)
})()
```
Error:
```js
repl: Assigning to rvalue (3:2)
   1 | (async function () {
   2 |   let a, b
 > 3 |   await Promise.resolve()
     |   ^
   4 |   [a, b] = [1, 2]
   5 |   console.log(a,b)
   6 | })()
```
But this ok ([on babeljs.io/repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=%28async%20function%20%28%29%20{%0A%20%20let%20a%2C%20b%0A%20%20[a%2C%20b]%20%3D%20[1%2C%202]%0A%20%20await%20Promise.resolve%28%29%0A%20%20console.log%28a%2Cb%29%0A}%29%28%29)):
```js
(async function () {
  let a, b
  [a, b] = [1, 2]
  await Promise.resolve()
  console.log(a,b)
})()
```

**Comment by jmm** [comment]
That's the problem with not using semicolons; it's equivalent to:

```js
await Promise.resolve()[a, b] = [1, 2]
```
