### ISSUE TITLE
Parent constructor calls not working for IE <= 10

### ISSUE THREAD

**Issue by mairatma** [babel/babel#3041]
It seems like I can't call parent constructors on IE <= 10 anymore with babel 6. I can reproduce this when building the following code:

```javascript
class TestSuper {
	constructor() {
		console.log('TestSuper constructor');
	}
}

class Test extends TestSuper {
	constructor() {
		console.log('Test constructor');
		super();
	}
}

export default Test;
```

If I call `new Test()` on Chrome I get both constructor prints, but on IE9 I only get the console.log from `Test`. This used to work before I upgraded to babel 6.

From what I saw while debugging this is happening because the constructor call gets transpiled to  `babelHelpers.possibleConstructorReturn(this, Object.getPrototypeOf(Component).call(this, opt_config));`, which doesn't work on IE <= 10, since the `Object.setPrototypeOf` call inside inherits only works for other browsers.

I've tried using **babel-plugin-transform-object-set-prototype-of-to-assign**, but it didn't work. I think it's because the Object.setPrototypeOfcall to be replaced is inside the inherits helper, so maybe it's not affected by the plugin or it doesn't work due to plugin order. Is there a way around this?

I first commented on an existing similar [issue](https://github.com/babel/babel/issues/2450) about this, since the problem seems to be due to the same cause, but in the end it's a different problem, and it seems more serious too, so it makes more sense to make it a separate issue.

**Comment by olofd** [comment]
+1
