### ISSUE TITLE
Returning anonymous async function fails weirdly

### ISSUE THREAD

**Issue by williamboman** [babel/babel#3047]
Repro repo: https://github.com/williamboman/babel-errors/tree/arrow-func-async

**Valid** (return named func)
```js
function foo() {}

export default function () {
    return async function bar() {
        for (let id of ids) {
            const promise = promises.get(id)();
            foo(() => promise, id);
            await promise;
        }
    }
}
```

-

**Valid** (return anon func, comment out `foo()` invokation)
```js
function foo() {}

export default function () {
    return async function () {
        for (let id of ids) {
            const promise = promises.get(id)();
            // foo(() => promise, id);
            await promise;
        }
    }
}
```

-

**Invalid** (return anon func)
```js
function foo() {}

export default function () {
    return async function () {
        for (let id of ids) {
            const promise = promises.get(id)();
            foo(() => promise, id);
            await promise;
        }
    }
}
```

**Comment by motiz88** [comment]
Hi @williamboman, the Travis repro build you set up seems to [pass](https://travis-ci.org/williamboman/babel-errors/builds/90973979), about two months after this report. Can you confirm that the issue has been resolved? (I was going to try to fix it)

**Comment by williamboman** [comment]
> Hi @williamboman, the Travis repro build you set up seems to pass, about two months after this report. Can you confirm that the issue has been resolved? (I was going to try to fix it)

If you clone the repo and checkout the `arrow-func-async` branch and do;

```sh
$ npm install
$ npm test
```

you'll see it fails. Not sure why Travis CI marks it as green. I'll trigger a new build.

**Comment by motiz88** [comment]
Looks like it [passes](https://travis-ci.org/williamboman/babel-errors/builds/159548275) with the latest Babel packages.

By the way, @williamboman, your `babel-node *.js` command there doesn't run all three files, but rather runs _one_ of them with the other two passed to it as CLI arguments (as a result of shell glob expansion). This is however less relevant to the current issue, since the problem would have come up in the separate `babel` invocation that does transpile all three files.

**Comment by williamboman** [comment]
> By the way, @williamboman, your babel-node *.js command there doesn't run all three files, but rather runs one of them with the other two passed to it as CLI arguments (as a result of shell glob expansion).

Ah, derp. Cool.
