### ISSUE TITLE
How to use presets via babel cli

### ISSUE THREAD

**Issue by brickyang** [babel/babel#3056]
Because of unknown reason, I can not use `.babelrc` or `package.json` babel property with webpack. I can just use babel cli, but I don't know how to use multi presets like `react` and `es2015` in cli.

I can run `babel --presets react src -d lib` now, noway to add `es2015` into.

**Comment by hzoo** [comment]
Check the docs: http://babeljs.io/docs/setup/#webpack, https://github.com/babel/babel-loader. You can also do `babel --presets react,es2015` or `babel --presets react --presets es2015`

<p>For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

<p>The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.</p>
