### ISSUE TITLE
Options when using es2015 presets

### ISSUE THREAD

**Issue by doberkofler** [babel/babel#3058]
I did switch to version 6 of babel and (for simplicity) would like to use the es2015 presets but cannot see how to disable the 'use strict' plugin. How can I configure babel to exclude a single plugin or prevent a file from being processed when using the API available in gulp-babel?

**Comment by legomind** [comment]
Just include all of the plugins that es2015 preset does, except the 'use strict' plugin.

**Comment by doberkofler** [comment]
@legomind This is what I've tried first but does not seem to work. When I add the plugin property I can no longer use the presets and must also install each plugin separately.

```
const BABEL_OPTIONS = {
	highlightCode: false,
	compact: false,
	presets: [
		'es2015'
	],
	plugins: [
		'transform-es2015-arrow-functions',
		'transform-es2015-block-scoped-functions',
		'transform-es2015-block-scoping',
		'transform-es2015-constants',
		'transform-es2015-parameters',
		'transform-es2015-spread'
	]
};
```

My goal would be to use take advantage of the simplicity of the presets but still be able to disable an individual transformation.

**Comment by thejameskyle** [comment]
Create your own preset and put all of the plugins you want to use in it.

There isn't a way of disabling a plugin that's been added via a preset. We're not interested in doing it either.
