### ISSUE TITLE
debugging in node with require('6to5/register')

### ISSUE THREAD

**Issue by jfirebaugh** [babel/babel#306]
Is there a way to get expected behavior with respect to line numbers, breakpoints, etc. when debugging a node script that uses `require('6to5/register')` with `node --debug` or [node-inspector](https://github.com/node-inspector/node-inspector)?

`node --debug` doesn't have any understanding of source maps at all, so the answer there is probably "no".

node-inspector does have source map support, but AFAICT source maps aren't available when using `require('6to5/register')`. Is that correct?

**Comment by Xiot** [comment]
I was able to get debugging up and working using the `sourceMap: 'inline'` option above, but things are a little weird.  @jfirebaugh, @sebmck  I was wondering if these were the residual bugs that you mentioned?

My environment:
NodeJS: v0.12
Node Inspector: v0.9.1
BabelJS: v4.4.2

As soon as I go into the debugger, I get the following warning in the console
```
Your Node version (undefined) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to 0.11.13 or newer to get full support.
```

In the sources tab, it is showing 2 copies of each file, one is the original, and the other one is after it goes through babel

![image](https://cloud.githubusercontent.com/assets/1887318/6428493/3a5d0b18-bf72-11e4-8a50-6329a9f94bbc.png)

The two index.js files refer to the same file. The selected one is how it exists on disk, and breakpoints work fine.  The other one is what Babel spits out, and I am not able to create breakpoints.

Let me know if there is anything else you need.

**Comment by jfaissolle** [comment]
It seems that this is because the option `inline` is overwritten at https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L60 with value `true` (which does not produce inline source maps). I have managed to debug by modifying this line to `inline`.

**Comment by ashishsc** [comment]
Did you submit a patch for this @jfaissolle ?

**Comment by sebmck** [comment]
@ashishsc I fixed it.

**Comment by ashishsc** [comment]
Oh great, thank you!

**Comment by RyanPMcD** [comment]
If anyone is still struggling with this I had success launching node-inspector independently (https://github.com/node-inspector/node-inspector#advanced-use) and then running my app with `babel-node server --debug`
