### ISSUE TITLE
add hook for code coverage when using babel-register

### ISSUE THREAD

**Issue by bcoe** [babel/babel#3061]
using `babel-register` overrides require['js'] which breaks code-coverage tools such as nyc and Istanbul, see:

https://github.com/bcoe/nyc/issues/55

It would be awesome if a hook was provided for these purposes, making it easy to lazily compile ES6 features AND have code-coverage. I'd like to propose the following:

``````
function loader(m, filename, old) {
  var content = compile(filename)
  if (old.instrument) {
    content = old.instrument(filename, content)
  }
  m._compile(content, filename);
}```
``````

**Comment by hzoo** [comment]
We have https://github.com/babel/babel/pull/3670 open now

**Comment by hzoo** [comment]
Going to close since https://github.com/babel/babel/pull/3670 is open
