### ISSUE TITLE
require() not working when sourcing a plugin using babel-node (5.8.33)

### ISSUE THREAD

**Issue by dminkovsky** [babel/babel#3063]
[This line in plugin-manager.js](https://github.com/babel/babel/blob/v5.8.33/packages/babel/src/transformation/file/plugin-manager.js#L82) returns an empty object when loading a plugin via `babel-node`. I have inserted a log into the the plugin file, and the log does not take place which indicates that the file is not evaluated by `require()`.

When this same line is hit via webpack running `node` and `babel-loader`, the plugin file is evaluated and the plugin is returned.

So something is going on inside that `require` call. I would try to debug this further but I am not familiar enough with babel to know what function `require` actually is at that context.

I have tried [disabling babel cache](https://babeljs.io/docs/usage/require/) but that made no difference. What configuration settings are at play here? How can I figure out what's wrong?

Thanks.

**Comment by dminkovsky** [comment]
By the way, I did confirm that `require()` here gets the same exact input string in both cases.

**Comment by dminkovsky** [comment]
And finally—figured out why this works with webpack and the babel-loader: Plugins defined in `babel-loader` query-based configuration are not loaded via `PluginManager#subnormaliseString()`, so this issues doesn't happen doesn't happen in that case. So that is a workaround if you are working with webpack and babel-loader.

**Comment by motiz88** [comment]
Closing since this is a v5.x bug, and the plugin machinery has evolved considerably since then. @dminkovsky feel free to let us know if something similar is still happening for you with the latest version of Babel; then we can reopen and investigate.

**Comment by dminkovsky** [comment]
Thanks for closing.
