### ISSUE TITLE
es2015 preset is ultra-slow

### ISSUE THREAD

**Issue by voithos** [babel/babel#3067]
The following example `gulpfile` runs at **~5.5 seconds** on my machine when processing an empty file.

    var gulp = require('gulp');
    var babel = require('gulp-babel');

    var ENTRY_FILE = './test.js';
    var BUILD_PATH = './build';

    var build = function() {
        return gulp.src(ENTRY_FILE)
            .pipe(babel({ presets: ['es2015']}))
            .pipe(gulp.dest(BUILD_PATH));
    };

    gulp.task('build', build);

    gulp.task('default', ['build']);

Package versions:
- `gulp@3.9.0`
- `gulp-babel@6.1.0`
- `babel-preset-es2015@6.1.18`

Is this a known issue, or is it just a problem with my environment/machine?

**Comment by thejameskyle** [comment]
Most likely because you are running npm2. npm3 does a better job of flattening dependencies and it results in a massive performance difference.

**Comment by voithos** [comment]
Yep, that was exactly it. Thanks!
