### ISSUE TITLE
[Question] How to write es6 npm module

### ISSUE THREAD

**Issue by vekexasia** [babel/babel#3070]
Hello there,

i'm using babel to transpile es6 to js. I saw it's not recommended to use babel/register | babel-core/register but it's not specified how i structure my npm package to leverage babel transpilation.

Thank you.

**Comment by forabi** [comment]
Have babel transpile your library on [npm's prepublish script](https://docs.npmjs.com/misc/scripts). Use the transpiled version as your `main` script. You could also set the ES2015+ version as `jsnext:main` for people using [RollUp](https://github.com/rollup/rollup) or similar package managers.

**Comment by vekexasia** [comment]
Thanks :)

**Comment by thejameskyle** [comment]
In the future, this is not the place for support queries: https://github.com/babel/babel#looking-for-support
