### ISSUE TITLE
Class inheritance bug with es2015 and transform-es2015-modules-systemjs

### ISSUE THREAD

**Issue by francisberesford** [babel/babel#3071]
I'm trying to use ES6 class inheritance transpiled with the systemjs module loader, but there appears to be runtime bug.

The error I get is:

`Uncaught Error: Module http://localhost/es6-tutorial/dist/classes/ColorPoint.js interpreted as global module format, but called System.register.`

Caused by a function prepended to the class file which inherits the base. The offending line is this:

``` javascript
function _typeof(obj) { return obj && typeof Symbol !== "undefined" && obj.constructor === Symbol ? "symbol" : typeof obj; }
```

If I remove this line the code works.

For more information see: http://stackoverflow.com/questions/33718513/transpiling-es6-to-es5-with-module-loading-and-class-inheritance

**Comment by hzoo** [comment]
Going to close for inactivity, let us know if it's still an issue
