### ISSUE TITLE
Default arguments transpiled incorrectly for classes in babel6

### ISSUE THREAD

**Issue by goatslacker** [babel/babel#3073]
Here's a [gist](https://gist.github.com/goatslacker/a19461bc98263859d9b3) with the transpiled output as well as a minimal example that shows the error.

What's happening is that an `_arguments` variable gets created at the top of the file and then it is used in the class instead of `arguments` for the function.

**Comment by GGAlanSmithee** [comment]
Probably same as #2776?

What are your presets / plugins?
