### ISSUE TITLE
Incorrect rest operator behavior for async arrow function

### ISSUE THREAD

**Issue by alexeyraspopov** [babel/babel#3077]
Bug is reproducible in Babel 5.x REPL. I wasn't able to test it with Babel 6, sorry.

[Code example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&playground=true&code=function%20composeSync(f%2C%20g)%20%7B%0A%20%20return%20(...args)%20%3D%3E%20f(g(...args))%3B%0A%7D%0A%0Afunction%20composeAsync(f%2C%20g)%20%7B%0A%20%20return%20async%20(...args)%20%3D%3E%20f(await%20g(...args))%3B%0A%7D%0A)

```
function composeSync(f, g) {
  return (...args) => f(g(...args));
}

function composeAsync(f, g) {
  return async (...args) => f(await g(...args));
}
```

In first function everything is good: the result of `composeSync` will be an arrow function which uses rest operator for getting all arguments.

In the `composeAsync` function behavior is different (maybe because of regenerator's runtime?): arguments for rest operator are taken from outer scope, from `composeAsync` function.

Any thoughts?

**Comment by alexeyraspopov** [comment]
I hope I didn't duplicate an issue.

**Comment by thejameskyle** [comment]
I'm 99% sure the root of this problem is the same as #2765. (shadow functions for the informed)

@sebmck ?
