### ISSUE TITLE
Why some unnecessary code transformations

### ISSUE THREAD

**Issue by doberkofler** [babel/babel#3078]
In this simple example `babel --presets es2015 test.js` transforms:
```
'use strict'; // enable strict mode

(function () {
	const A = 3;
}());
```
to
```
'use strict' // enable strict mode
;
(function () {
	var A = 3;
})();
```
It's mostly out of curiosity but I would be interested to better understand why:
- the location of the semicolon in the first line has been moved into a separate line
- the syntax of the iife has been changed from `(function () {}());` to `(function () {})();`

**Comment by sebmck** [comment]
[See the README](https://github.com/babel/babel#looking-for-support).
