### ISSUE TITLE
Maintain Babel 5

### ISSUE THREAD

**Issue by AlicanC** [babel/babel#3082]
Today I got this message when installing a package:
```babel-core@5.8.21: Babel 5 is no longer being maintained. Upgrade to Babel 6.```

1- What does this mean? Can we still expect support, security updates and bug fixes or is it completely abandoned?
2- Isn't it too early to stop maintaining Babel 5? Babel 6 being very incompatible with Babel 5 makes the move harder and we rather do it on our next spring cleaning period. I am not expecting a 5 year LTS, but shouldn't it be maintained for at least another quarter or two?

**Comment by t128** [comment]
Also i tried babel 6 and it brakes on pretty much every of my babel 5 projects, so yeah i think babel 5 should be supported in the future.

+1

**Comment by sebmck** [comment]
> 1- What does this mean? Can we still expect support, security updates and bug fixes or is it completely abandoned?

No updates will be made.

> 2- Isn't it too early to stop maintaining Babel 5? Babel 6 being very incompatible with Babel 5 makes the move harder and we rather do it on our next spring cleaning period. I am not expecting a 5 year LTS, but shouldn't it be maintained for at least another quarter or two?

The core team is not big enough to support both major versions.

---

If you have any further questions please see the [README](https://github.com/babel/babel#looking-for-support).
