### ISSUE TITLE
Extending builtins like Error and Array doesn't work in 6.x

### ISSUE THREAD

**Issue by jacogr** [babel/babel#3083]
## Code
```
const defineError = function(name) {
  return class extends Error {
    constructor(message) {
      super();

      this.message = message;
      this.name = name;
    }
  };
};

const ErrorA = defineError('ErrorA');

console.log('new ErrorA() instanceof Error = ', new ErrorA() instanceof Error);
console.log('new ErrorA() instanceof ErrorA = ', new ErrorA() instanceof ErrorA);
```

## Babel ^5.8.21

package.json:

    {
      "name": "babel-instanceof",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "build": "node_modules/.bin/babel index.js -o compiled.js"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "babel": "^5.8.21",
        "babel-core": "^5.8.21"
      }
    }

.babelrc

    {
      "stage": 1
    }

output:

    new ErrorA() instanceof Error =  true
    new ErrorA() instanceof ErrorA =  true

## ^6.1.4

package.json:

    {
      "name": "babel-instanceof",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "build": "node_modules/.bin/babel index.js -o compiled.js"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "babel-core": "^6.1.4",
        "babel-cli": "^6.1.4",
        "babel-preset-es2015": "^6.1.4",
        "babel-preset-stage-1": "^6.1.4"
      }
    }

.babelrc

    {
      "presets": ["es2015", "stage-1"],
    }

output:

    new ErrorA() instanceof Error =  true
    new ErrorA() instanceof ErrorA =  false

**Comment by xpl** [comment]
Try this as a workaround:

```javascript
class DDoSProtectionError extends Error {
    constructor () {
        super ()
        // a workaround to make `instanceof DDoSProtectionError` work in ES5
        this.constructor = DDoSProtectionError 
        this.__proto__   = DDoSProtectionError.prototype
    }
}
```

**Comment by perekrestov-igor** [comment]
```
class DDoSProtectionError extends Error {
    constructor () {
        super ()
        // a workaround to make `instanceof DDoSProtectionError` work in ES5
        this.constructor = DDoSProtectionError 
        //this.__proto__   = DDoSProtectionError.prototype
    }
}
//For IE too
DDoSProtectionError.prototype = Error.prototype;
```

**Comment by avesus** [comment]
@xpl you saved my day! It's the only working solution.
