### ISSUE TITLE
Invalid striping flow type imports in react preset

### ISSUE THREAD

**Issue by mhagmajer** [babel/babel#3084]
Flow type imports aren't properly stripped by `react` preset:

```
$ echo "import type {Type1} from 'my-lib'" | ./node_modules/.bin/babel --presets react
import { Type1 } from 'my-lib';
```

This leads to `browserify` trying to include the `my-lib` module when used with `babelify` (https://github.com/babel/babelify/issues/152).

Interestingly, this works okay if `syntax-flow` plugin is removed from the preset (produces empty output):
```
$ echo "import type {Type1} from 'my-lib'" | ./node_modules/.bin/babel --plugins transform-react-jsx,transform-flow-strip-types,syntax-jsx,transform-react-display-name

```

Checked with 6.1.18.

**Comment by zertosh** [comment]
The `react` preset includes `babel-plugin-transform-flow-strip-types` and `babel-plugin-syntax-flow`. When they're both applied like that, it seems that type info isn't getting stripped.

**Comment by hzoo** [comment]
Should be fixed in https://github.com/babel/babel/releases/tag/v6.14.0 with https://github.com/babel/babel/pull/3655
