### ISSUE TITLE
Statement about browser support for compiled code

### ISSUE THREAD

**Issue by davidtheclark** [babel/babel#314]
Is there are already a clear statement about which browsers should be able to handle the compiled code, and I'm missing it? I can't seem to find one, though I do find issues like https://github.com/6to5/6to5/issues/116 suggesting that I should be worried. Also, I see that getters/setters use `Object.defineProperties()`, which I am worried about.

If not, this is something that I would like to see added to the documentation --- either a library-wide generalization or feature-specific documentation. I do not want to use features that will not compile to code that works in IE8+.

**Comment by attila226** [comment]
> 6to5 should output completely valid syntax ES3.

This statement seems to conflict with the following:

> Since 6to5 assumes that your code will be ran in an ES5 environment it uses ES5 functions. So if you're using an environment that has limited or no support for ES5 such as lower versions of IE then using the es5-shim along with the 6to5 polyfill will add support for these methods.

http://6to5.org/docs/usage/caveats/#es5

Can you please help clarify?

**Comment by sebmck** [comment]
@attila226 ES3 syntax does not mean ES5 functions and methods.

**Comment by attila226** [comment]
@sebmck So if I understand correctly, for IE8 support one will potentially need to use the es5-shim?

**Comment by sebmck** [comment]
@attila226 Yeah, also check out the [FAQ](http://6to5.org/docs/faq/#what-is-the-browser-compatibility-) which answers a similar question.

**Comment by chrisbateman** [comment]
Might be worth calling out the fact that modules won't work in IE 8 and below (due to defineProperty for __esModule). Getters/setters are called out for the same issue.

**Comment by sebmck** [comment]
@chrisbateman Ah crap, didn't even think of that. I'll add an option to [loose mode](http://babeljs.io/docs/usage/loose/).

**Comment by sebmck** [comment]
@chrisbateman Done, it'll be available in the next release later today.

**Comment by chrisbateman** [comment]
@sebmck That is fantastic - you made my day. Thanks!

**Comment by sebmck** [comment]
@chrisbateman No problem! Available as of 4.2.0.
