### ISSUE TITLE
Modules should export bindings, not values

### ISSUE THREAD

**Issue by yernende** [babel/babel#334]
Like

``` js
//------ lib.js ------
export let counter = 0;
export function inc() {
    counter++;
}

//------ main.js ------
import { inc, counter } from 'lib';
console.log(counter); // 0
inc();
console.log(counter); // 1
```

->

``` js
//------ lib.js ------
exports.counter = 0;
exports.inc = function inc() {
    exports.counter++;
}

//------ main.js ------
var lib = require("lib");
console.log(lib.counter); // 0
inc();
console.log(lib.counter); // 1
```

Proof - http://www.2ality.com/2014/09/es6-modules-final.html#cyclic_dependencies_in_ecmascript_6

**Comment by Arnavion** [comment]
@sebmck It doesn't need much boilerplate?

```javascript
// Boilerplate #1 - get ref to global object. Once per file
var __global = (typeof global !== "undefined") ? global : ((typeof window !== undefined) ? window : null);

var lib = require('./lib');

// Boilerplate #2 - Object.defineProperties. Once per file, one property per imported binding
Object.defineProperties(__global, {
    counter: { get: function () { return lib.counter; } /*, enumerable: false, etc. */ },
    inc: { get: function () { return lib.inc; } /*, enumerable: false, etc. */ },
});

console.log(counter);
inc();
console.log(counter);
```

**Comment by sebmck** [comment]
@Arnavion I know how to do live bindings but:

 - Every single import/export reference requires going through multiple getters which is terrible for performance.
 - No CommonJS interop.
 - Restricting modules to modern environments since getters and setters aren't supported in older browsers.

**Comment by sebmck** [comment]
If you want this behaviour then blacklist `es6.modules` and pipe your output through [esperanto](http://esperantojs.org/).

**Comment by Arnavion** [comment]
Cool, thanks.

**Comment by loganfsmyth** [comment]
@sebmck Came across this since I was curious to see if there had been discussions.

Couldn't we have an export expand from

    export var toggle = true;
    toggle = false;

to 
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
var toggle = true;
exports.toggle = toggle;
exports.__es6ModuleBinding('toggle');
toggle = exports.toggle = false;
exports.__es6ModuleBinding('toggle');
```

and have an import do like

```
var toggle = require("./toggle").toggle;
require('./toggle').__es6ModuleBinding('toggle', function(val){ toggle = val; });
```

It would only work for modules that aren't assigning directly to module.exports, but it seems like it'd avoid  performance hits in normal usage.

Are there edge cases I'm not considering?

**Comment by sebmck** [comment]
@loganfsmyth See #1117. I've already implemented live bindings in Babel 5.x :stuck_out_tongue_winking_eye:
