### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by ronag** [babel/babel#341]
I'm experiencing somewhat slow compilation times. Any tips/tricks on reducing compilation time?

**Comment by MatthewMueller** [comment]
Probably doing something wrong, but it doesn't seem like the optimization is working. I'm compiling a very simple file using babel:

```js
/**
 * Dependencies
 */

import Roo from 'roo';

/**
 * Setup
 */

let roo = Roo(__dirname);

/**
 * Export `roo`
 */

export default roo;
```

Using `require("babel/register")`.

Then by running `time BABEL_CACHE_PATH=cache.json ./bin/boot`:

```
real	0m3.746s
user	0m3.782s
sys	0m0.174s
```

And running `time BABEL_CACHE_PATH=cache.json ./bin/boot` again:

```
real	0m3.629s
user	0m3.659s
sys	0m0.180s
```

My current version of babel is: `4.4.6`

**Comment by sebmck** [comment]
@MatthewMueller Can you try running `$ DEBUG=babel ./bin/boot` to narrow down if it's really babel and if so what files may be adding to it. Thanks!

**Comment by MatthewMueller** [comment]
thanks for the quick response! 

actually already tried that, weirdly didn't print anything out:

![img](https://cloudup.com/ciHYrG9Qm80)

boot starts with this:

```js
/**
 * ES6 Runtime
 */

require("babel/register");
```

**Comment by sebmck** [comment]
If it's not displaying anything then babel will be loading the files from the cache so it wont need to compile anything. I'll add some debug output for cached files when they're loaded via babel/register in the next patch which should be out later today.

**Comment by MatthewMueller** [comment]
Ahh you're right. Actually the module I was loading is the bottleneck here. Thanks for the hasty debugging!
