### ISSUE TITLE
Add .6to5rc config file

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#351]
Since there are [a lot of options](https://6to5.org/usage.html#options) you can pass into 6to5 to customize the output with new ones being added [fairly often](https://github.com/6to5/6to5/issues/347#issuecomment-68224583), it might be good to add a `.6to5rc` file which can contain all of the options.

I imagine it would just be a `.jshintrc`-like file using json.

**Comment by phpnode** [comment]
+1 for this feature, also it would be pretty cool if calling `require('6to5/register')` would respect these files if no argument is specified, i.e. not if I write: `require('6to5/register')({...})`. This would allow easy integration with e.g. mocha

**Comment by calebboyd** [comment]
+1,  mocha use case

**Comment by chicoxyzzy** [comment]
just to remind `6to5-loader` should use config file too

**Comment by cesarandreu** [comment]
+1

**Comment by UltCombo** [comment]
I assume the `.6to5rc` file would be read using the excellent [`rc` package](https://www.npmjs.com/package/rc), right? It would be awesome to be able to have a project-wide config and subdirectory-specific overriding configs. `=]`

**Comment by sebmck** [comment]
@UltCombo That package looks awesome but there doesn't appear to be a way to specify anything directory to search for the rc file other than the cwd.

**Comment by UltCombo** [comment]
Interesting. We can take a look at how JSHint handles RC files, as JSHint does support `.jshintrc` in subdirectories IIRC.

**Comment by UltCombo** [comment]
Yeah, JSHint uses their own implementation to look for rc files:

- https://github.com/jshint/jshint/blob/33612f8cedce779d0d22571b72da4216d18bee9c/src/cli.js#L83
- https://github.com/jshint/jshint/blob/33612f8cedce779d0d22571b72da4216d18bee9c/src/cli.js#L164-L185

**Comment by sebmck** [comment]
I'd prefer to use a library as it takes out a lot of the legwork and would make it extremely easy to implement.

**Comment by pascalduez** [comment]
Allowing both JSON and YAML would be nice. 
ESLint [example](https://github.com/eslint/eslint/blob/master/lib/config.js#L56) using [js-yaml](https://github.com/nodeca/js-yaml)

**Comment by sebmck** [comment]
Added as of 4.5.0, thanks!

**Comment by UltCombo** [comment]
yay nice work!

**Comment by rblopes** [comment]
Is this supported "out-of-the-box" by task plugins, like `gulp-babel` too?
