### ISSUE TITLE
Users of Babel: Give us your logos

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#364]
Hello,

If you are reading this issue, then there's a distinct chance that you are a user of Babel. If you are not a Babel user, please [set it up](http://babeljs.io/docs/using-babel/) on your site/app/library and then continue reading this issue.

We have spent the last 48 hours building Babel a brand new website, which we will reveal to the world in just a few short days, that includes great new documentation in a very visually pleasing manner.

We would also like to include a list of companies and projects using Babel. See [Ember Users](http://emberjs.com/ember-users/) for an example. However, we do not currently have a list of companies and projects using Babel.

So this is where you come in. As a Babel user, we ask that you please help us make such a list.

#### Requirements:

- **Name** _(correctly formatted)_
- **Homepage Url** _(homepage/primary entry point for users)_
- **Brand Guidelines/Licensing** _(or anything we need to know before using your logo)_
- **Logo** _(full color, VECTOR OR HIGH RESOLUTION, transparent background)_

#### Example:

- **Name:** CloudFlare 
- **Homepage Url:** https://cloudflare.com/ 
- **Brand Guidelines/Licensing:** https://www.cloudflare.com/logo
- **Logo:**

<img src="https://cloud.githubusercontent.com/assets/952783/5594836/5e85fdfa-9214-11e4-9a90-da2bef0ea823.png">

Please comment directly on this issue with all of these things so we have a reference for them. If you have any questions feel free to comment or email me: me@thejameskyle.com.

Thanks!

**Comment by sairion** [comment]
Name: Spoqa Inc.
Homepage Url: https://spoqa.com/
Brand Guidelines/Licensing: (We don't have it currently.)
Logo: 
![spoqa-rgb-grey](https://cloud.githubusercontent.com/assets/484290/5594959/fc858bd0-92a8-11e4-88fc-631adf3b7a16.png)

**Comment by gabrielecirulli** [comment]
![logo small orange](https://cloud.githubusercontent.com/assets/886011/5605917/4946bdf4-9416-11e4-8231-dddad7e8f064.png)

Name: Impraise
Homepage Url: http://impraise.com
Brand Guidelines/Licensing: Please use our logo in the colors provided, and without modifications. The size can change, but please try to keep it within reasonable limits.
Logo (please use SVGs if applicable): https://dl.dropboxusercontent.com/u/2951174/Impraise%20Logo.zip

**Comment by kobezzza** [comment]
Name: Snakeskin
Homepage Url: https://github.com/kobezzza/Snakeskin
Brand Guidelines/Licensing: Please use logo in the colors provided, and without modifications. The size can change, but please try to keep it within reasonable limits.
Logo:
<img src="http://kobezzza.com/files/snakeskin/logo.svg?1" alt="Snakeskin" width="190px" />

**Comment by benjamingr** [comment]
**Name:** TipRanks
**Homepage Url:** http://www.tipranks.com
**Brand Guidelines/Licensing:**  Please ask for permission before making any adjustments to the logo apart for resizing. There is a separate logo for placement on dark backgrounds.
**Logo**: http://analysts.tipranks.com/Images/logo.png

![TipRanks logo for bright backgrounds](http://analysts.tipranks.com/Images/logo.png)

We use 6to5 on a new internal app and intend to keep using it in new projects.

**Comment by ai** [comment]
**Name:** Autoprefixer
**Homepage Url:** https://github.com/postcss/autoprefixer
**Brand Guidelines/Licensing:** MIT
**Logo:** http://postcss.github.io/autoprefixer/logo.svg

![](http://postcss.github.io/autoprefixer/logo.svg)

**Comment by ai** [comment]
**Name:** PostCSS
**Homepage Url:** https://github.com/postcss/postcss
**Brand Guidelines/Licensing:** MIT
**Logo:** http://postcss.github.io/postcss/logo.svg

<img src="http://postcss.github.io/postcss/logo.svg" width="200" height="200">

**Comment by assaf** [comment]
**Name:** Broadly
**Homepage Url:** https://broadly.com/
**Brand Guidelines/Licensing:** Please use our logo in the colors provided, and without modifications. If you need one to place against dark logo, let me know.
**Logo:** http://static.broadly.com/images/logo/broadly-logo-blue.svg

**Comment by mattma** [comment]
Name: Ember-Rocks
Homepage Url: https://github.com/mattma/ember-rocks
Brand Guidelines/Licensing: MIT
Logo: None

Description:

An Em(ber) command line utility to help you build an ambitious web application via `em` command.

**Comment by radubr** [comment]
**Name:** ProAppSoft
**Homepage Url:**http://proappsoft.com/
**Brand Guidelines/Licensing:** Please use our logo in the colors provided, and without modifications. The size can change, but please try to keep it within reasonable limits.
**Logo:** http://proappsoft.com/img/ProAppSoft-logo-300px.png
![ProAppSoft logo](http://proappsoft.com/img/ProAppSoft-logo-300px.png)

**Comment by pazguille** [comment]
**Name:** Mango
**Homepage Url:** https://getmango.com/
**Brand Guidelines/Licensing:** Please use logo in the colors provided, and without modifications. The size can change, but please try to keep it within reasonable limits.
**Logo:**
![Logo Mango](https://s3.amazonaws.com/uploads.hipchat.com/7792/854799/LIYC4xJC6926vlt/Hello%20copy.png)

We use 6to5 at https://panel.getmango.com.

**Comment by saulhoward** [comment]
- **Name:** Hailo
- **Homepage Url:** https://www.hailoapp.com
- **Brand Guidelines/Licensing:** https://www.hailoapp.com/press-kit/
- **Logo:** 
![hailo-logo](https://cloud.githubusercontent.com/assets/354048/5974767/f83c16ac-a86f-11e4-9d5c-2f71d4ef0a57.jpg)

**Comment by UltCombo** [comment]
@jaydson check this out. Should we submit ES6Rocks/Harmonic here?

**Comment by benmccormick** [comment]
- Windsor Circle
- http://www.windsorcircle.com/
- Please ask for permission before making any adjustments to the logo apart from resizing.
- Logo

![image](https://cloud.githubusercontent.com/assets/1899941/6094717/530e91ea-af05-11e4-881d-143c9a3218fe.png)

**Comment by cexbrayat** [comment]
Name: Ninja Squad
Homepage Url: http://ninja-squad.fr/
Brand Guidelines/Licensing: MIT
Logo: 
![](http://ninja-squad.fr/public/img/logo-flat-600.png)

**Comment by mattstyles** [comment]
**Name**: DotLabel
**Homepage URL**: http://dotlabel.co.uk/
**Brand Guidelines**: Please use our logo in the colors provided, and without modifications. The size can change, but please try to keep it within reasonable limits.
**Logo**:
![dotlabel-logo-300](https://cloud.githubusercontent.com/assets/1760429/6114784/6f94f720-b098-11e4-92e9-83e09231d2a7.png)

**Comment by jaydson** [comment]
Name: Harmonic (Static Site Generator)
Homepage Url: https://github.com/es6rocks/harmonic
Brand Guidelines/Licensing: WTFPL
Logo:  
![harmonic](https://raw.githubusercontent.com/es6rocks/harmonic/master/harmonic-logo.png)

**Comment by nhunzaker** [comment]
**Name**: Viget
**Homepage Url**: http://viget.com/
**Brand Guidelines/Licensing**: Please use our logo in the colors provided, and without modifications. The size can change, but please try to keep it within reasonable limits. [We have general guidelines here](http://viget.com/logos).
**Logo**: http://viget.com/assets/files/logos/dark-on-light-rgb.png

![Viget](http://viget.com/assets/files/logos/dark-on-light-rgb.png)

**Comment by EisenbergEffect** [comment]
**Name**: Aurelia
**Homepage Url**: http://aurelia.io/
**Brand Guidelines/Licensing**: Please use our logo in the colors provided, and without modifications. The size can change, though. You may also use it with or without the type face.
**Logo**:

![aurelia-logo](https://cloud.githubusercontent.com/assets/131485/6219600/b3475c90-b5f9-11e4-9988-7055619031fb.png)

Feel free to contact for alternate sizes. We can supply vector if needed, but would rather not submit that here. Thanks!

**Comment by HugoGiraudel** [comment]
**Name**: SassDoc
**Homepage URL**: http://sassdoc.com
**Brand Guidelines**: http://sassdoc.com/brand-guidelines/
**Logo**:
![SassDoc Logo](http://sassdoc.com/assets/images/logo_full_compact.svg)

Thanks. :)

**Comment by fundon** [comment]
**Name**: **Trek** (Next generation full-stack JavaScript open source solution, based on Koa)
**Homepage URL**: https://github.com/trekjs/trek
**Logo**: 
![trek_icon_512x512](https://cloud.githubusercontent.com/assets/27926/6692809/f9fd7d8c-cd09-11e4-8dd0-f101c0b79ad9.png)

**Comment by topaxi** [comment]
Name: Adfinis SyGroup AG
Homepage URL: https://adfinis-sygroup.ch/
Logo: 
![adfinissygroup_logo_600dpi_rgb_srgb](https://cloud.githubusercontent.com/assets/213788/6706136/347d88ca-cd5b-11e4-98c3-ba169e0c2784.png)

**Comment by ivanoats** [comment]
Name: University of Washington Foster School of Business
Homepage URL: http://foster.uw.edu
Logo: ![uw foster logo](https://pbs.twimg.com/profile_images/225928560/foster_icon_400x400.jpg)
Brand guidelines: http://www.washington.edu/brand/logo-guidelines/

**Comment by zertosh** [comment]
Name: SoundCloud
Homepage URL: https://soundcloud.com
Brand guidelines: https://soundcloud.com/press

![sc_st_gradient_460x290](https://cloud.githubusercontent.com/assets/830952/6716246/651a695c-cd7a-11e4-8cc6-3f0b10dd2823.png)

**Comment by benjamingr** [comment]
@zertosh nice! Any details on how you use it?

**Comment by zertosh** [comment]
@benjamingr We're using it on all of our React apps, so mostly internal apps and small advertising/promo public-facing sites.

**Comment by thejameskyle** [comment]
Thanks everyone for submitting logos. The [Users page](http://babeljs.io/users/) looks fantastic if I do say so myself (and I do). It's really cool to see the diversity of companies and projects using Babel.

I'm going to close this issue in favor of individual ones opened over on the website repo.

**If you would like to submit your logo, [please open an issue with this template](https://github.com/babel/babel.github.io/issues/new?title=New+User%3A+%5Binsert+name%5D%0A&body=Please+fill+the+following+out%3A%0A%0A-+Name%3A+%28correctly+formatted%29%0A-+Homepage+url%3A+%28homepage%2Fprimary+entry+point+for+users%29%0A-+Brand+Guidelines%2FLicensing%3A+%28or+anything+we+need+to+know+before+using+your+logo%29%0A-+Logo%3A+%28svg+if+possible%2C+pngs+over+500x200px+with+transparent+backgrounds+are+also+acceptable%29%0A%0A%3E+Example%3A%0A%3E%0A%3E+Name%3A+CloudFlare%0A%3E+Homepage+url%3A+https%3A%2F%2Fcloudflare.com%0A%3E+Brand+Guidelines%2FLicensing%3A+https%3A%2F%2Fwww.cloudflare.com%2Flogo%0A%3E+Logo%3A+https%3A%2F%2Fwww.cloudflare.com%2Fmedia%2Fdownloads%2Fcloudflare-logo-kit.zip%0A).**

Thanks again!
