### ISSUE TITLE
UMD/AMD with globals and non-object exports

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel#375]
How would one configure a module formatter to use [UMD with a global](https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js). Perhaps like so:

# In

```javascript
import foo from "foo";

export function bar() {
  return foo("foobar");
}
```

# Out

```javascript
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define(["exports", "foo"], function(foo) {
      return (root['someModuleName'] = factory(foo));
    });
  } else if (typeof exports !== "undefined") {
    module.exports = factory(require("foo"));
  } else {
    root['someModuleName'] = factory(foo);
  }
})(this, function (_foo) {
  "use strict";

  var _interopRequire = function (obj) {
    return obj && (obj["default"] || obj);
  };

  var foo = _interopRequire(_foo);

  return function bar() {
    return foo("foobar");
  }
});
```

Obviously `'someModuleName'` would need to be specified. Is this module format currently supported?

**Comment by thejameskyle** [comment]
Link to previous discussion: https://github.com/6to5/6to5/issues/119#issuecomment-61430514

**Comment by GianlucaGuarini** [comment]
I have developed https://github.com/GianlucaGuarini/es6-project-starter-kit also to avoid this issue. [Here](https://github.com/GianlucaGuarini/es6-project-starter-kit/tree/master/src/frag) you can specify simply how you want to export your script

**Comment by jmeas** [comment]
[Esperanto](https://github.com/esperantojs/esperanto) does this

**Comment by sebmck** [comment]
@jmeas Yep, it's trivial to do, I just need to get around to doing it.

**Comment by jmeas** [comment]
No prob @sebmck. I'm sure you're swamped with work. I just figured I'd post the link in case others come here looking for a way to do it until you've got some extra time on your hands.

**Comment by tomekwi** [comment]
@sebmck, I'm wondering how to make global output usable when multiple files are in the game. When we really target browsers without browserify/webpack/requireJS/anything, we wouldn't want to pollute the global scope with more than one variable.

How about good ol' JS namespacing?

Input:

```js
// File: foo.js
import baz from "./bar";

export default function foo () {} /*babel global: foo */
```

```js
// File: bar.js
export default "bar"; /*babel global: baz; namespace: foo */
```

Output:

```js
// File: foo.js
(function (root, factory) {
  if (/* require or AMD */) /* the usual stuff */
  else root.foo = factory(root.foo.baz);
})(this, function (baz) {
  return function foo () {};
})
```

```js
// File: bar.js
(function (root, factory) {
  if (/* require or AMD */) /* the usual stuff */
  else (root.foo || root.foo = {}).baz = factory();
})(this, function () {
  return "bar";
})
```

**Comment by tomekwi** [comment]
A couple of random thoughts to the idea:

* When we export directly to the `foo` namespace (like in `foo.js`), we have to take into account that the export will overwrite the namespace. So if we want access to baz, we'd have to make it explicit. For example:

```js
// File: foo.js
import baz from "./bar";

export default function foo () {} /*babel global: foo */
foo.baz = baz
```

* One simple way to use the package in a browser:

**Comment by jeffmicklos** [comment]
just wanna put my :+1: here...

**Comment by sebmck** [comment]
Long overdue but this will be in 5.0.0

**Comment by jmeas** [comment]
Woo! Thanks @sebmck

**Comment by sebmck** [comment]
Although the effort may be in vain once/if #1118 goes ahead :stuck_out_tongue:
