### ISSUE TITLE
Newline issues when using comma-separated vars

### ISSUE THREAD

**Issue by gaearon** [babel/babel#413]
We use comma-separated vars, it may have been a mistake but that's the way it is.

6to5 mangles them in two ways:

(before)

``` js
'use strict';

var React = require('react'),
    BackColorMixin = require('../mixins/BackColorMixin'),
    ClassNameMixin = require('../mixins/ClassNameMixin'),
    { PropTypes } = React;

function test() {
  var x = someReallyLongCalculation(),
      y = x + someOtherReallyLongCalculation(),
      z = x + y / lolThisIsGettingLong();
}
```

(after)

``` js
"use strict";

// 1. Note the extra newline after each line:

var React = require("react");

var BackColorMixin = require("../mixins/BackColorMixin");

var ClassNameMixin = require("../mixins/ClassNameMixin");

var PropTypes = React.PropTypes;


function test() {
  // 2. Note that newlines aren't preserved here at all
  var x = someReallyLongCalculation(), y = x + someOtherReallyLongCalculation(), z = x + y / lolThisIsGettingLong();
}
```

These two issues are what's blocking me now from switching, as 1. makes me scroll a lot when debugging and 2. makes it hard to debug multi-line var declarations.

I wouldn't mind if comma-separated vars were converted to a list of statements, that's up to you. What is important is that they shouldn't all be on the same line.

**Comment by sebmck** [comment]
Thanks! Now outputs:

```javascript
"use strict";

var React = require("react");
var BackColorMixin = require("../mixins/BackColorMixin");
var ClassNameMixin = require("../mixins/ClassNameMixin");
var PropTypes = React.PropTypes;

function test() {
  var x = someReallyLongCalculation(),
      y = x + someOtherReallyLongCalculation(),
      z = x + y / lolThisIsGettingLong();
}
```

Released as of 2.7.4

The reasoning for the the `require` declarations being split up is because of the destructuring. I might make it possible in the future for the destructuring transformer to check whether all the nodes it produced were all declarations with the same `kind` and then just concat them.

**Comment by sebmck** [comment]
Let me know if you run into any other issues where code readability can be improved. Always looking for ways to improve it :smile:

**Comment by gaearon** [comment]
One minor thing that bugs me is

```js
var AppDispatcher = require('../dispatcher/AppDispatcher'),
    ActionTypes = require('../constants/ActionTypes'),
    assign = require('react/lib/Object.assign'),
    ZineStore = require('./ZineStore'),
    update = require('react/lib/update'),
    { createStore } = require('../utils/StoreUtils');
```

outputting

```js
var AppDispatcher = __webpack_require__(19);
var ActionTypes = __webpack_require__(43);
var assign = __webpack_require__(41);
var ZineStore = __webpack_require__(93);
var update = __webpack_require__(48);var _require = __webpack_require__(49);

var createStore = _require.createStore;
````

(never mind `__webpack_require__`, it was a `require` when 6to5 ate it).

**Comment by sebmck** [comment]
Hmm, looks like a weird edgecase. I'll have a look into it.
