### ISSUE TITLE
What should the issue/PR templates be?

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4148]
Ref https://github.com/babel/babel/pull/3690

Maybe it shouldn't be too long?
- since there could be multiple versions do we want to ask users to run something like `npm ls | grep babel-`?
- add a comment about making a minimal repro, and maybe even just a repl link
- checkboxes/table?
- mention that you should search the existing issues before reporting

cc @danez

**Comment by hzoo** [comment]
Maybe add a section in the PR about new/removed dependencies?

**Comment by hzoo** [comment]
We could add another one for semver (or include that info using our tags)

**Comment by danez** [comment]
👍  for searching and minimal repo and new/removed dependencies (although not sure if this happens that often)

About the `npm ls | grep` this could be tricky, as it would tell us what version of babel are used, but there could also be multiple versions of the same dependency in there from other dependencies and it only works on mac/unix.

What I noticed that the codeblock for the options is marked as `js` syntax highlighting, should be `json`.

**Comment by hzoo** [comment]
It doesn't happen often but good to note for changelog, etc.

I usually do js because the comments look bad in json 😄

**Comment by hzoo** [comment]
We could say something like 

| Major: Breaking change?  | yes/no
| Patch: Bug fix?          | yes/no
| Minor: New feature?      | yes/no

**Comment by danez** [comment]
Fine with me.

**Comment by mnichols** [comment]
Can this be closed? I see this was added well after this discussion: https://github.com/babel/babel/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by hzoo** [comment]
Sure we can always update it.
