### ISSUE TITLE
super as the object of a member expression does not work with assignment or update expressions

### ISSUE THREAD

**Issue by eventualbuddha** [babel/babel#426]
### Examples

```js
super.x++;     // 1
--super.y;     // 2
super.z += 2;  // 3
```

### Strategy

In the case of 1, we need to store the current value of `super.x` in a temporary variable, set a new value for `super.x` by adding `1` to the previous value, and make the expression return the previous value. As an optimization we can omit the temporary variable when the update expression value is not used (i.e. its parent is an expression statement).

For 2, the value of the update expression is the value after the decrement (since it's a prefix update), so we don't need the temporary variable and can simply get the value of `super.y`, subtract `1`, and set the value of `super.y`.

Finally, for 3 we get the value of `super.z`, apply the operator to it with its argument, and use that to set the value of `super.z`.

### Likely Output

Assuming this appears in a class called `ClassName` in a non-static method, this might be the expected output:

```js
var _x;
_x = _get(Object.getPrototypeOf(ClassName.prototype), "x", this) + 1, _set(Object.getPrototypeOf(ClassName.prototype), "x", this, _x), _x; // not optimized to remove the temporary var, but could be in this case
_set(Object.getPrototypeOf(ClassName.prototype), "y", this, _get(Object.getPrototypeOf(ClassName.prototype), "y", this) - 1);
_set(Object.getPrototypeOf(ClassName.prototype), "z", this, _get(Object.getPrototypeOf(ClassName.prototype), "z", this) + 2);
```

### Super Helpers?

By using helpers to wrap the common cases of getting and setting values for super, we could have output like this instead but it would require additional `super-get` and `super-set` helper templates:

```js
var _x;
_x = _superGet(ClassName, "x", this) + 1), _superSet(ClassName, "x", this, _x), _x; // not optimized to remove the temporary var, but could be in this case
_superSet(ClassName, "y", this, _superGet(ClassName, "y", this) - 1);
_superSet(ClassName, "z", this, _superGet(ClassName, "z", this) + 2);
```

It is definitely more readable. We could also have `super-get-static` and `super-get-static` which would operate on static properties, or we could make the first argument to `super-get` and `super-set` be `ClassName` for static properties and `ClassName.prototype` for non-static.

Thoughts?

**Comment by sebmck** [comment]
The `super-get` and `super-set` helper idea is really good. The `*-static` helpers is probably pushing it a bit too much.
