### ISSUE TITLE
Destructuring array literals without helper

### ISSUE THREAD

**Issue by vigneshshanmugam** [babel/babel#431]
Array Destructuring is done by using a utility in 6to5. Check below

![array-dest](https://cloud.githubusercontent.com/assets/3902525/5677694/e152ec10-980f-11e4-88e7-56b826afcfbe.png)

While traceur does this by using a temp variable. 

Any Issue on doing by traceur way?.

**Comment by phpnode** [comment]
@sebmck a minor opt would be detect when an array literal is used and skip `_slicedToArray()` there, also could avoid the extra temp variable in this scenario

**Comment by sebmck** [comment]
@phpnode It should, at least it used to. May be a possible regression when I did some refactoring.

**Comment by sebmck** [comment]
Done.

**Comment by phpnode** [comment]
awesome!

**Comment by vigneshshanmugam** [comment]
Thanks :+1:
