### ISSUE TITLE
Self host, eventually.

### ISSUE THREAD

**Issue by benjamingr** [babel/babel#443]
Hey, just an idea:

It would be really cool if now that the project is more mature you could integrate code written in ES6 inside 6to5 - I think it would be great to show examples of features from the actual code base. 

Great work by the way.

**Comment by sebmck** [comment]
Thanks! I've considered bootstrapping in the past and it's been bought up quite a bit recently too. As of current I don't really have a strong opinion of it. Only thing I feel irky about is adding a build step to 6to5 development which I think would be a hassle.

**Comment by benjamingr** [comment]
Why do you need a build step? Anything wrong with the require hook?

**Comment by sebmck** [comment]
It's not suitable for libraries and the compilation overhead isn't something I'm comfortable with.

**Comment by benjamingr** [comment]
Oh I'm not suggesting you compile it on the fly in the distributed version - you said you feel irky about having a build step in development which using the require hook should solve - meaning you only have a build step in production.

**Comment by caspervonb** [comment]
@sebmck a build step is a really trivial issue isn't it? 6to5 is already using `make` to run tests and do browserify builds, so having a target dependency to build the library is pretty much transparent.

The only immediate trade-off i see however is that lodash can be dropped in favor of core, which based on recent commits seems to be the we're heading anyways?

**Comment by sebmck** [comment]
It's not really something I'm willing to do right now because it's not worth the hassle.

**Comment by benjamingr** [comment]
Hence the eventually :) This is not a priority by any standard.

**Comment by sebmck** [comment]
Yeah but I'm not sure if I want to ever do it because I'm pretty content with the current workflow i've got going.

**Comment by benjamingr** [comment]
Fair enough.

**Comment by sebmck** [comment]
Reopening. 6to5 is in a state where I feel it's appropriate.

**Comment by eventualbuddha** [comment]
Nice! What structure were you thinking of following for this? I believe TypeScript has a good setup, but I don't have a lot of experience with self-hosting.

**Comment by sebmck** [comment]
@eventualbuddha Probably just relying on an older stable version of 6to5 and then bumping that whenever there's a new stable version. Move `lib` to `src` and use `$ make watch-core` or `$ make build-core` for builds.

Prerequisites #351 and #780.

**Comment by sebmck** [comment]
Superseded by #883.

**Comment by sebmck** [comment]
Babel is now bootstrapped.

**Comment by benjamingr** [comment]
Awesome job :D

**Comment by sebmck** [comment]
This feels fucking amazing.

**Comment by azu** [comment]
Great work!!

**Comment by cesarandreu** [comment]
Awesome!! :D
