### ISSUE TITLE
Compiler bug with composite boolean logic?

### ISSUE THREAD

**Issue by mariogintili** [babel/babel#4479]
### Input Code

```javascript
quickReplies && !isConfident
```

### Babel Configuration (.bablerc, package.json, cli command)

I'm using Ember-CLI ` "ember-cli-babel": "^5.1.6",` and my config is

```js
  options.babel = {
    includePolyfill: true,
  };
```

### Expected Behavior

The boolean logic doesn't seem to be compiling correctly please see the following image, left hand side my code, right hand side the compiled code

![screen shot 2016-09-07 at 4 42 19 pm](https://cloud.githubusercontent.com/assets/3522106/18346173/e55ed630-75b6-11e6-86f5-969e76845f28.png)

**Comment by goto-bus-stop** [comment]
Regenerator output is always a bit tough to grasp! I think it's actually correct, though.

The `context$$.next = <number>; break;`  parts in regenerator output are used to "jump" to other parts of the function (other switch cases). These are used so regenerator can jump back to the right spot after waiting for a promise to resolve, for example. So, what the code is actually doing, is:

```js
if (!(quickReplies && !isConfident)) {
  jump to case 15 next;
  break;
}

jump to case 10 next;
return await bot.ask(i18n.t(…));
```

Or, the same thing written differently:

```js
if (quickReplies && !isConfident) {
  jump to case 10 next;
  return await bot.ask(i18n.t(…));
}
jump to case 15 next;
break;
```

Which seems right! You can see in `case 10:` that it calls `bot.understand`, and I bet in `case 15:` you'll see that it contains the `if (isConfident)` statement from input line 22.

**Comment by danez** [comment]
I think the answer of @goto-bus-stop is correct. In any way if you still have a problem with regenerator please report it there, because the people there might have better knowledge about how it works.
https://github.com/facebook/regenerator
