### ISSUE TITLE
babylon to babel-generator - problem with generating source parsed with quotes

### ISSUE THREAD

**Issue by marekyggdrasil** [babel/babel#4484]
I noticed I cannot use `babel-generator` to generate a javascript code from `ast` that previously has been parsed using `babylon`, this occurs only if input source contains quotes.

### Input Code
```javascript
'use strict';

import generate from 'babel-generator';
const babylon = require('babylon');

const ast_working = babylon.parse(`a`, {
  sourceType: 'module'
});

const ast_not_working = babylon.parse(`'a'`, {
  sourceType: 'module'
});

console.log(generate(ast_working).code);
console.log(generate(ast_not_working).code);
```

### Babel Configuration

.babelrc

```js
{
   "presets": ["es2015"]
}
```

package.json

```js
{
  "name": "no-name-package",
  "version": "0.0.1",
  "description": "",
  "main": "example.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "marekyggdrasil",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-core": "^6.14.0",
    "babel-generator": "^6.11.4",
    "babel-preset-es2015": "^6.14.0",
    "babel-template": "^6.15.0",
    "babel-types": "^6.14.0"
  },
  "dependencies": {
    "babel-literal-to-ast": "^0.1.2",
    "babel-traverse": "^6.15.0",
    "babylon": "^6.9.1"
  }
}
```

cli command

```
babel-node example.js 
```

### Expected Behavior

I use `babylon` to parse following sources:

`a`
`"a"`

Babylon provides me with `ast` which then I use in `babel-generator` and I expect to obtain again the same code as the input code.

### Current Behavior

Everything works until there is a quote or double quote in the parsed source.

```
$ babel-node example.js 
a;
/Users/marekyggdrasil/examples/node_modules/babel-generator/lib/index.js:131
    var raw = code.slice(token.start, token.end);
                  ^

TypeError: Cannot read property 'slice' of undefined
    at findCommonStringDelimiter (/Users/marekyggdrasil/examples/node_modules/babel-generator/lib/index.js:131:19)
    at normalizeOptions (/Users/marekyggdrasil/examples/node_modules/babel-generator/lib/index.js:84:28)
    at new Generator (/Users/marekyggdrasil/examples/node_modules/babel-generator/lib/index.js:52:18)
    at exports.default (/Users/marekyggdrasil/examples/node_modules/babel-generator/lib/index.js:19:13)
    at Object.<anonymous> (/Users/marekyggdrasil/examples/buildrep.js:15:13)
    at Module._compile (module.js:435:26)
    at loader (/Users/marekyggdrasil/.nvm/versions/node/v4.2.3/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marekyggdrasil/.nvm/versions/node/v4.2.3/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

### Possible Solution

I tried escaping the quotes, but problem is not related to parsing. When I examine the ast tree it appears to be correct.

Better way (preferably with some examples) to approach described in `context` section would also work as solution in my opinion.

### Context

I want to build a simple tool that parses a javascript source code then replaces tags with custom `ast` specified externally. I use input source as template and just want to compile specific components from it, for that `babel-traverse` is involved but not required to reproduce the issue so didn't mention it before.

### Your Environment

| software         | version
| ---------------- | -------
| Babel (babel-node)            | 6.14.0
| node             | v4.2.3
| npm              | 2.14.7
| Operating System | OSX El Capitan 10.11.3

**Comment by hzoo** [comment]
Looks the `findCommonStringDelimiter` issue would be fixed as part of https://github.com/babel/babel/pull/3623 which is a larger change

**Comment by marekyggdrasil** [comment]
Thank you for such quick response. Indeed I applied following change locally and it resolves the issue:

https://github.com/babel/babel/pull/3623/commits/dc8152dbed59ce1a47a7af2b834962250c0c599c

Strange thing was that it didn't work neither with double, neither with single quotes.
Closing, I hope people who have similar issue will find this fix.
