### ISSUE TITLE
Babel generated Error subclass produces instance of Error rather than instance of subclass

### ISSUE THREAD

**Issue by Gozala** [babel/babel#4485]
### Input Code

```js
class ReadError extends Error {}

new ReadError('Boom') instanceof ReadError // => false
```

### Babel Configuration (.bablerc, package.json, cli command)

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=true&loose=false&spec=false&playground=false&code=class%20ReadError%20extends%20Error%20%7B%7D%0A%0Aalert(new%20ReadError('Boom')%20instanceof%20ReadError)%20%2F%2F%20%3D%3E%20false

### Expected Behavior

should alert `true`

### Current Behavior

alerts `false`

**Comment by loganfsmyth** [comment]
https://stackoverflow.com/questions/33870684/why-doesnt-instanceof-work-on-instances-of-error-subclasses-under-babel-node/33877501#33877501 should cover it.

We mention it here in our Caveats: https://babeljs.io/docs/usage/caveats/#classes but if you have recommendations of a better place let us know.

**Comment by forivall** [comment]
It's also interesting to note that _somehow_, it works in node 0.10

https://gist.github.com/forivall/88d8056d87bcc566a5d02ef837d772c6

I'm curious as to how that works, and this could be noted on the caveats page as well.

As far as a better place, it could go in something like "known issues"?

**Comment by Gozala** [comment]
I would prefer if babel would just error and not compile on attempt to subclass built-ins that can't be. That being said I don't know if work required is worth the benefits.

**Comment by hzoo** [comment]
We can at least make an option for that (fail when subclassing built-ins)

**Comment by xpl** [comment]
Try this as a workaround:

```javascript
class DDoSProtectionError extends Error {
    constructor () {
        super ()
        // a workaround to make `instanceof DDoSProtectionError` work in ES5
        this.constructor = DDoSProtectionError 
        this.__proto__   = DDoSProtectionError.prototype
    }
}
```

**Comment by Leonid-Yeromin** [comment]
Almost year, the problem still exists. WTF?

**Comment by hzoo** [comment]
? You can use https://github.com/babel/babel/issues/4480#issuecomment-318817038

**Comment by rico345100** [comment]
@xpl Worked with 8.x, but not working with 6.9.5

**Comment by nicolo-ribaudo** [comment]
This should be fixed in Babel 7.

**Comment by rico345100** [comment]
@nicolo-ribaudo That's awesome. Note that I just fixed this issue.

1. Adding babel-plugin-transform-builtin-extend
2. Do what @xpl suggests

Now it works.
