### ISSUE TITLE
Default parameter not set correctly 

### ISSUE THREAD

**Issue by meikidd** [babel/babel#4486]
### Input Code

```js
function buildImageUrl(path = "/") {
  console.log(path)
}
buildImageUrl(null);
```
output is `null`, but expect `/`

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.7.4 babel-core
| node             |  6.2.2
| npm              |  3.9.5
| Operating System | osx

**Comment by loganfsmyth** [comment]
`null` will not cause default parameter values to be substituted, only an `undefined` value will.
