### ISSUE TITLE
RFC: Explicit plugin ordering

### ISSUE THREAD

**Issue by fab1an** [babel/babel#4488]
New issue from my comment here: #3281

I think many of the plugin-ordering issues could be easily solved by explicit configuration like this:
1. Adding configurable constraints so that the user could explicitly state their intention to fix bugs:
   
   ``` json
   {
       "presets": ["es2015"],
       "ordering": {
            "plugin-a": {
                  "before": "plugin-b"
            }
       }
   }
   ```
2. Another idea would to add transformation history and let plugins defer their execution, or output warnings.
   
   ``` js
   visitor: {
       CallExpression: function CallExpression(path, state) {
           if (state.history.indexOf("babel.plugin.x") >= 0) {
               return "RUN ME LATER";
           }
       }
   }
   ```
   
   `WARNING: Your configuration includes plugin-x, which conflicts with this plugin, please see <url>.`

I'm in the situation that I want to publish two independent 2 babel-plugins, where the A must run after B, if B is used as well. I'm planning on doing this by setting custom values in `state`, which seems very hacky.

Better would be to allow the user to specify configuration.

**Comment by hzoo** [comment]
passPerPreset was going to be a option for each preset to define originally. But yeah I think we need a better idea of doing ordering like mentioned.

@fab1an have you seen https://github.com/babel/notes/blob/master/2016-08/august-01.md#potential-api-changes-for-traversal?

**Comment by fab1an** [comment]
@hzoo Just read it. I don't understand fully, because I'm not familiar with the internals of babel, having only written a couple of plugins, but I'll try to comment anyway:

> * The visitor approach to AST mutation is baked directly into the core of our plugin system. This prevents us from iterating on the core transformation system because it is tied to the version of babel-core, it requires plugins to run overtop of eachother, because plugins all run in the same traversal pass (usually anyway).

> * We pass in the babel param, which our internal plugins at least, rely on for access to things like babel-types and babel-traverse. This also prevents us from modifying those easily, unless we want to lock babel-core to an old version of babel-traverse, with plugins using some new major version.

I don't know about these versioning issues. I `import` "babel-types" directly from node-modules.

> * Plugin ordering is user-defined based on their Babel configuration, which most don't realize, and makes it hard to reason about what could be affected by any given change to a plugin.

I think what more users don't realize is that babel picks up and merges `.babelrc`s. `react-native` falls into this trap a lot, because it uses babel at runtime. If any third-party libraries are used, react-native's packaging process will pick up, for example, `./node-modules/my-library/.babelrc`. 

> * Because transforms run overtop of eachother, it is hard to provide useful debug feedback, since anything could be mutating the AST at any time.

I think people running plugins most of the time know what they do. I, personally, don't need a generic solution for everything. 

Sample situation that I want to solve:

1. I'm writing a visitor for `JSXAttribute` because I want to do something with my JSX-code. So I put in my `.babelrc:`

   ```javascript
   {
        presets: ["es2015", "react"],
        plugins: ["./lib/my-jsx-fiddling-plugin"]
   }
   ```

2. It doesn't work. The visitor is never called, because the transform converts JSX into `React.createClass` before it reaches my plugin.

3. I realise that and adapt my configuration:

   ```javascript
   {
        presets: ["es2015", "react"],
        plugins: [
            ["./lib/my-jsx-fiddling-plugin", {runBefore: "transform-react-jsx"}]
        ]
   }
   ```

I think that would solve 99% of the cases. It's not possible to construct a generic transformer where every plugin plays nice with every other plugin.

Just let me tell babel how to fix it.

**Comment by fab1an** [comment]
Short comment to the proposal:

> ```
for (let i = 0; i < plugins; i++) {
  if (plugins[i](ast)) i = -1;
}
```
This would allow each plugin to have full control over the AST, while allowing plugins with higher priority to re-execute whenever something is changed in the AST.

Where does the priority come from and is the array already sorted by priority?

Because, in that code, what happens when plugin **[i-1]** is fine with the change, but **[i-2]** is not?

**Comment by fab1an** [comment]
Any news or comments on this? I still think explicit order-hints would be the best solution. It would enable developers and maintainers of libraries to fix issues in **one** line of code without constructing complex graphs about how babel works in their heads.

**Comment by fab1an** [comment]
Could anyone comment on this: Samples of bugs occuring with the current system: https://github.com/facebook/react-native/issues/9151

**Comment by hzoo** [comment]
Closing in favor of https://github.com/babel/babel/issues/4488, can leave ideas there too

**Comment by fab1an** [comment]
You linked to the wrong issue.

**Comment by hzoo** [comment]
Oops! https://github.com/babel/babel/issues/5623 (I tend to do that a lot 😅)
