### ISSUE TITLE
babel-register - re-requiring a changed file leads to bad stack traces

### ISSUE THREAD

**Issue by gabelevi** [babel/babel#4489]
### Input Code

``` js
require('babel-register');
var foo = require('./foo');
```

Then we change `foo.js` - maybe adding some blank lines to the top

``` js
delete require.cache[require.resolve('./foo')];
foo = require('./foo');
```
### Expected Behavior
- Before `foo.js` is re-required, stack traces should have the correct locations.
- After `foo.js` is re-required, stack traces should have the correct locations.
### Current Behavior
- Before `foo.js` is re-required, stack traces have the correct locations.
- After `foo.js` is re-required, stack traces have the **wrong** locations.
### Possible Solution

The problem is that source-map-support is caching source maps. So even when babel-register re-transforms a file, source-map-support is still using the old source maps.

I've submitted https://github.com/evanw/node-source-map-support/pull/149 to add a `removeFromCache(filepath)` API to source-map-support.

Then, babel-register could call `removeFromCache(filename)` right after it calls `transformFileSync(filename)`

**Comment by existentialism** [comment]
This looks fixed when testing locally with `source-map-support@0.4.4` via https://github.com/evanw/node-source-map-support/pull/118.

**Comment by aaronang** [comment]
@gabelevi Are you still able to reproduce the bad stack trace? If not, we can close this issue 😄
