### ISSUE TITLE
`exports ... from` syntax causes modules to get imported early

### ISSUE THREAD

**Issue by Retsam** [babel/babel#4493]
### Input Code

``` js
import "babel-polyfill";

export {default as foo} from "./foo"; //Foo depends on the babel-polyfill
```

[Example in REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=import%20%22babel-polyfill%22%3B%0A%0Aexport%20%7Bdefault%20as%20foo%7D%20from%20%22.%2Ffoo%22%3B%20%2F%2FFoo%20depends%20on%20the%20babel-polyfill%0A)
### Babel Configuration (.bablerc, package.json, cli command)

``` js
{
  "presets": ["es-2015"]
}
```
### Expected Behavior

The contents of the foo module should be exported on as foo on the current module
### Current Behavior

Fails with `ReferenceError: regeneratorRuntime is not defined`
The following code is generated by babel: 

``` js
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = undefined;

var _foo = require("./foo");

Object.defineProperty(exports, "foo", {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_foo).default;
  }
});

require("babel-polyfill");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

The `require("./foo")` call gets hoisted above the `require("babel-polyfill")` call, and so regeneratorRuntime is not defined when the contents of the foo module runs.  I found this issue with babel-polyfill specifically, but it could manifest with any import that performs a side-effect, followed by an `export ... from` with a module that relies on that side-effect.
### Possible Solution

It seems like the the `export ... from` should cause the module to be imported in the same order that it would be imported if the export statement were replaced with an import statement.
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.4.14 |
| node | 4.4.4 |
| npm | 3.9.0 |

**Comment by Drache93** [comment]
This issue isn't restricted to 'export' usage.

Any async function is also moved to the top of the file, meaning that babel-polyfill isn't used.

Same output error "ReferenceError: regeneratorRuntime is not defined".

**Comment by hzoo** [comment]
Similar to https://github.com/babel/babel/issues/4963 and others, I would recommend making the require polyfill it's own file/entry point to workaround hoisting issues.
