### ISSUE TITLE
spread operator doesn't use set function to assign property

### ISSUE THREAD

**Issue by funkjunky** [babel/babel#4497]
### Input Code

```js
let obj = {
    set a(val) { b.a = val; },
    b: {a: 1},
};
let obj2 = {...obj, a: 2}
//obj2 remains    { b: {a: 1} }
//obj2 should be { b: {a: 2} }
```

### Babel Configuration (.bablerc, package.json, cli command)

.babelrc
```js
{
  "presets": ["es2015", "stage-0"]
}
```
webpack.config.js
```js
var path = require('path');
var webpack = require('webpack');

var BUILD_DIR = path.resolve(__dirname, 'public');
var APP_DIR = path.resolve(__dirname, 'src');
var DATA_DIR = path.resolve(__dirname, 'json');

module.exports = {
    devtool: '#eval-source-map',
    entry: [
        'babel-polyfill',
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',

        APP_DIR + '/index.js',
    ],
    output: {
        path: BUILD_DIR,
        publicPath: '/static/',
        filename: 'bundle.js',
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
    ],
    module: {
        loaders: [
            {
                test: /.js?$/,
                loaders: ['babel'],
                include: APP_DIR,
            },
            {
                test: /\.json$/,
                loader: 'json',
                include: DATA_DIR,
            },
        ],
    },
};
```

### Expected Behavior

obj2 = { b: {a: 2} }

### Current Behavior

obj2 = { b: {a: 1} }

### Possible Solution

I dunno... I'm guessing this was just missed, probably not too difficult to fix.

### Context

In my game engine I'm attempting to use redux to reduce physics parameters through derivatives.
I do this by reducing acceleration into velocity into position.
This means my structure is acceleration: { _velocity: { _position.
I'd still prefer to access velocity and position on the root object, so I made getter and setter properties for them: ie:
```js
{
    set position(val) { this.acceleration._velocity._position = val; },
    get position() { return this.acceleration._velocity._position; }
    ...
}
```

### Your Environment

Chrome 52.0.2743.116
package.json for version:

```json
  "dependencies": {
    "redux": "^3.5.2"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.11.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-0": "^6.5.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.13.1"
  }
```

**Comment by hzoo** [comment]
Unless i'm missing something here,

The input example gives a syntax error: ` {...obj, {a: 2}}` needs a key unless you mean ` {...obj, a: 2}`.

```js
let obj = {
    set a(val) { b.a = val; },
    b: {a: 1},
};
let obj2 = {...obj, {a: 2}}
```

Spread is compiled to `Object.assign` so `obj2 = {...obj, a: 2}` -> `obj2 = Object.assign({}, obj, {a: 2}}`. All that does is overwrite the `a` property to be 2. so obj2 would be `{ a: 2, b: { a: 1} }`

And doing `obj.a = 3` to set it would give an undefined error for b unless it was `this.b.a`

**Comment by funkjunky** [comment]
(first: yes their were syntax error, I fixed em up)
Ok, so I did some more research on this given what you said. Here's the code I was playing with:

[babeljs conversion](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=let%20obj%20%3D%20%7B%0A%20%20%20%20set%20a(val)%20%7B%20b.a%20%3D%20val%3B%20%7D%2C%0A%20%20%20%20b%3A%20%7Ba%3A%201%7D%2C%0A%7D%3B%0A%0Alet%20obj2%20%3D%20%7B...obj%2C%20a%3A%202%20%7D)

[fiddle with conversion code, modified assign call](https://jsfiddle.net/wkjkj5qd/)

So, yes it converts it to Object.assign({}, obj, {a: 2});
If I remove the new object, mutating the original object, then the setter is called.

So more specifically, my question now is: Why doesn't Object.assign pass getters and setters with an object?

**Comment by funkjunky** [comment]
Ok, I read the definition of Object.assign and see it invokes setters and getters, but doesn't pass them along.

I'll simply need to use another method of copying the object. I think my use case is so rare, that there is no reason to argue for a chance in the functionality of Object.assign or the spread operator, because it's probably not worth the added code complexity.

Thanks for the help hzoo!
