### ISSUE TITLE
babel-plugin-transform-flow-comments does not preserve types for single parameter lambda functions

### ISSUE THREAD

**Issue by dchambers** [babel/babel#4503]
Single parameter lambda functions seem to have their type info stripped because they are transformed differently to take advantage of the fact that the round brackets are optional if there is only a single parameter.

**Comment by danharper** [comment]
Fixed with #4504 :)

**Comment by dchambers** [comment]
Whoa! I didn't realize I had the Gold-Level Premium Support package :smile:

Thanks so much, really appreicate it 👍
