### ISSUE TITLE
babel-plugin-transform-runtime: ability to select what to polyfill?

### ISSUE THREAD

**Issue by olalonde** [babel/babel#4505]
In Node v6, most polyfills provided by `babel-plugin-transform-runtime` are unnecessary. It would be nice if there could be an option to specify what needs to be polyfilled (e.g. only `Object.entries`).

**Comment by hzoo** [comment]
Yeah for sure, I'm not sure if we already made an issue for this but it was brought up and it is our intention to do so. At least https://github.com/babel/notes/issues/4

At a minimum be able to specify the year. (same with the polyfill). Otherwise you can polyfill: false but that's everything

**Comment by a324539017** [comment]
+1

**Comment by motiz88** [comment]
There's some discussion in #3934 too.

**Comment by schmod** [comment]
This also likely has synergies with https://github.com/babel/babel-preset-env (although I think this is mostly a dupe of #3934)

**Comment by hzoo** [comment]
I think we can probably consolidate these issues

**Comment by hzoo** [comment]
Ok lets move this into #3934 - basically the same ask (don't make polyfill/runtime an all for one thing)
