### ISSUE TITLE
Unhelpful error message when used preset is not a preset

### ISSUE THREAD

**Issue by danez** [babel/babel#4506]
### package.json

```json
{
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-eslint": "^6.0.0",
    "babel-plugin-transform-class-properties": "^6.11.5",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-latest": "^6.14.0"
  }
}
```

### Babel Configuration (.bablerc, package.json, cli command)

```json
{
  "presets": [
    ["latest", { "es2015": { "loose": true } }],
    "react"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread"
  ]
}

```

### Expected Behavior
An error saying something like: `You are using babel-preset-react but babel was not able to find it. Ensure the preset is correctly installed or remove the preset from the babel-config.`

### Current Behavior

`ReferenceError: [BABEL] src/components/Highlight.js: Unknown option: foreign.Children. Check out http://babeljs.io/docs/usage/options/ for more info`

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  see package.json
| node             | 4.5.0
| npm              | 3.10.8
| Operating System | macOS 10.11

**Comment by motiz88** [comment]
@danez Can I work on this?

**Comment by motiz88** [comment]
I can't seem to reproduce this, though (on Windows, npm 3.10.6, Node 6.2.0). I'm getting `Error: Couldn't find preset "react" relative to directory` [...] which seems fair enough.

**Comment by danez** [comment]
@motiz88 Feel free to work on this.

This is the repo where I encountered it, just remove the react-preset and run npm install and the error should show up.

**Comment by motiz88** [comment]
:+1: managed to repro this way. Having a look.

**Comment by motiz88** [comment]
Oh! It's because `react` is also a module!

**Comment by motiz88** [comment]
So there's probably a reasonable heuristic we can use to tell `react` from a Babel preset, but it's worth solving more generally than that :smile:

I could use input from someone moreknowledgeable than myself about the plugin/preset APIs, since - correct me if I'm wrong - they're not fully documented at the moment.

**Comment by motiz88** [comment]
Another idea that doesn't rely on duck typing: We could emit a warning if a
preset specified by name resolves to a module not named `babel-preset-*`.
And similarly for plugins.

**Comment by loganfsmyth** [comment]
Ahhhhhh thank you, I've always been so confused by where `Children` was coming from.

**Comment by motiz88** [comment]
I guess this can be closed now?
