### ISSUE TITLE
how to require AMD module?

### ISSUE THREAD

**Issue by alexey2baranov** [babel/babel#4510]
hello!

We use Hogan as a template engine and compiled templates with Hulk util. 
The Hulk disadvantage is that it compile templates into AMD style only. 
When we require this compiled AMD template with require() we get this error:

command:
> /usr/bin/node --use-strict /usr/lib/node_modules/mocha/bin/_mocha --timeout 2000 --compilers js:babel-register --ui bdd --reporter /home/alexey2baranov/WebStorm-162.1447.27/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /home/alexey2baranov/htdocs/kp-client/test/view/SlovoAsListItemView.Test.js

error:
> ReferenceError: define is not defined

and this is compiled Hogan template witch could not be loaded:
```javascript
if (!!!templates) var templates = {};
define(["hogan.js"], function (Hogan) {
    return new Hogan.Template({
        code: function (c, p, i) {
            var t = this;
            t.b(i = i || "");
            t.b("<div id=\"");
            t.b(t.v(t.f("io", c, p, 0)));
            t.b("\" class=\"Slovo SlovoAsListItem\">");
            t.b("\n" + i);
            t.b("    <div id=\"");
            t.b(t.v(t.f("io", c, p, 0)));
            t.b("_value\">");
            t.b(t.v(t.d("model.value", c, p, 0)));
            t.b("</div>");
            t.b("\n" + i);
            t.b("</div>");
            return t.fl();
        }, partials: {}, subs: {}
    });
});
```

package.json
```json
  "babel": {
    "plugins": [
      "fast-async",
      "transform-class-properties",
      "transform-es2015-parameters",
      "transform-es2015-destructuring"
    ],
    "ignore": [
      "./node_modules/**/*.js"
    ],
    "sourceMaps": "inline"
  }
```

**Comment by danez** [comment]
Node in general does not provide an amd environment this is why it does not know what define is.  Babel does not touch your `define()` call, because babel on transpiles es2015+ to es5. So babel is not involved in this error at all.

Besides this please do not use our issue tracker for support questions but rather look in one of the supported places in the readme https://github.com/babel/babel#looking-for-support
