### ISSUE TITLE
Using a Global transform does not use local babel in dependencies

### ISSUE THREAD

**Issue by kumavis** [babel/babel#4512]
### Context

I have a global transform `babel-preset-es2015` using Babel6 via Babelify.
[A dependency](https://github.com/vn38minhtran/react-tooltip-component) uses Babel5.
### Expected Behavior

I expect the dependency to be transformed normally per its `.babelrc` using its local Babel version. Then be transformed globally as I have configured.
### Current Behavior

Errors are thrown about the dependency's `.babelrc` being in Babel5. If `.babelrc` is monkey-patched, it complains that it uses Babel5 transforms.
### Input Code

```
var bundler = browserify({
  entries: [entryPoint],
  cache: {},
  packageCache: {},
  plugin: [watchify],
})

// lookups are relative if I dont give it a full path
var bablePreset = path.resolve(__dirname, '../node_modules/babel-preset-es2015')

bundler.transform(babelify, {
  global: true,
  presets: [bablePreset],
})
```
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.14.0 |
| node | 6.3.1 |
| npm | 3.10.3 |
| Operating System | OSX Yosemite 10.10.5 |

**Comment by loganfsmyth** [comment]
You could pass `babelrc: false` in your config to tell your global transform to skip looking at `.babelrc` files assuming you don't have any other `.babelrc` files you do want to read.

Also FYI

    var bablePreset = path.resolve(__dirname, '../node_modules/babel-preset-es2015')

could probably be

    var bablePreset = require.resolve('babel-preset-es2015')

**Comment by kumavis** [comment]
@loganfsmyth thanks for the quick response

I like the `require.resolve` trick, much cleaner

I'll try `babelrc: false` but I'd imagine this skips local transforms in all dependencies? - they may be necessary for the dependencies to function correctly.

**Comment by loganfsmyth** [comment]
> I'll try babelrc: false but I'd imagine this skips local transforms in all dependencies? - they may be necessary for the dependencies to function correctly.

Yeah, it would depend on your usecase. Using babelify as a global transform isn't super common. An alternative would also be to use `ignore` and `only` to target the actual deps you want to transpile, since it sounds like the one with the `.babelrc` is already converted: https://github.com/babel/babelify#additional-options

**Comment by kumavis** [comment]
@loganfsmyth I have some dependencies that are es2015 without any babelrc or transpile step. need to make sure they work in browsers like Safari, thus the global transform. would you recommend a different approach?

**Comment by loganfsmyth** [comment]
Normally I'd expect dependency modules to have been transpiled and published independently of the application using them, but whatever workflow works really :)

**Comment by hzoo** [comment]
looks like this is solved
