### ISSUE TITLE
Support new Flow syntax for exact object types

### ISSUE THREAD

**Issue by AgentME** [babel/babel#4513]
[Flow v0.32 adds a new syntax](https://github.com/facebook/flow/blob/master/Changelog.md) for exact object types. It uses {| and |} instead of { and }. It supports code like this now:

```js
type Foo = {|
  x: string;
  y: number;
|};
function foo(object: {| x: string, y: number |}) {
}
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
{
  "plugins": ["transform-flow-strip-types"]
}
```

### Expected Behavior

In Flow annotations, Babel should handle {| ... |} similarly to { ... } and the transform-flow-strip-types plugin should strip it out just the same. With transform-flow-strip-types, the code should compile to something like:

```js

function foo(object) {}
```

(And if the syntax-flow plugin is present and not the transform-flow-strip-types plugin, then Babel should be able to reproduce the original code with the {| ... |} syntax preserved.)

### Current Behavior

```
SyntaxError: test.js: Unexpected token (1:12)
> 1 | type Foo = {|
    |             ^
  2 |   x: string;
  3 |   y: number;
  4 | |};
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.14.0

**Comment by danez** [comment]
Thanks for reporting. This is already worked on in babel/babylon#104 and babel/babel#3702.

Closing this as duplicate.

**Comment by AgentME** [comment]
Oh awesome! I guess I wasn't nearly as thorough in my search as I thought I was.

**Comment by danez** [comment]
No problem.🙂
