### ISSUE TITLE
Support new flowtype syntax for exact object types in transform-flow-strip-types and babel-plugin-transform-flow-comments

### ISSUE THREAD

**Issue by Riim** [babel/babel#4522]
[flow v0.32.0](https://github.com/facebook/flow/releases/tag/v0.32.0):

> New syntax for exact object types: use {| and |} instead of { and }. Where {x: string} contains at least the property x, {| x: string |} contains ONLY the property x.

**Comment by danez** [comment]
Duplicate of #3702
