### ISSUE TITLE
feature request: babelrc: specify env via a CLI option

### ISSUE THREAD

**Issue by charlierudolph** [babel/babel#4525]
Currently to use different plugins / presets for different environments, you need to set an environment variable when running the CLI. I would like this instead to be an option you pass to the CLI (example: `--env production`). This would remove the difference in how you use it on unix / windows and feels more natural to me anyway.

Relevant documentation: https://babeljs.io/docs/usage/babelrc/

For  backward compatibility, it could still use the env variable as a fallback.

**Comment by motiz88** [comment]
Just pointing out that [cross-env](https://www.npmjs.com/package/cross-env) offers a clean solution to this in the context of `package.json` scripts.

**Comment by hzoo** [comment]
We recommend ^, we could think about a --env later but we are deprecating env in favor of babelrc.js
