### ISSUE TITLE
extensions error

### ISSUE THREAD

**Issue by xshua06** [babel/babel#4527]
/a/b.js
/a/b.web.js
/a/a.js
/a/c.js

```
//a.js
require('babel-register')({
  extensions: ['', '.web.js', '.js']
});
require('./c');

//c.js
require(''./b);
```

i want require b.web.js,  but b.js

| software         | version
| ---------------- | -------
| Babel            |  latest
| node             | latest
| npm              | latest
| Operating System |  mac

**Comment by danez** [comment]
The require logic is still handled by nodejs, `babel-register` just registers the compilation for javascript files. If you want to load `b.web.js` you need to `require('b.web')`

The extensions option is not describing the extension load order, but only which extension should be compiled with babel. `''` is not a valid extension, and  `'.web.js'` is already covered by `'.js'`, so actually your extension option is not doing anything different as if you would not supply it.

I hope this helps.
