### ISSUE TITLE
Babel throws error on compiling my json file. 

### ISSUE THREAD

**Issue by paulbartocillo** [babel/babel#4529]
Here is my json file:

```json
{
  "defaultEnv" : {"ENV": "NODE_ENV"},
  "development" : {
    "driver" : "pg",
    "user" : "paul",
    "password" : "",
    "host" : "127.0.0.1",
    "database" : "medfast-api"
  },
  "production" : {
    "driver" : "",
    "user" : "",
    "password" : "",
    "host" : "",
    "database" : "",
  }
}
```

And here is the part where gulp build throws error:

```js

let transpileServer = lazypipe()
    .pipe(plugins.sourcemaps.init)
    .pipe(plugins.babel, {
        plugins: [
            'transform-class-properties',
            'transform-runtime'
        ]
    })
    .pipe(plugins.sourcemaps.write, '.');
```

Here's the link of the screenshot of the error occur. 
https://gyazo.com/46896e06b64aea947addff55f47ab939

Seems that there is an error on parsing the ":" on json files.
It looks like babel is trying to parse the JSON file as JS.

Can someone help me through this. Thanks a lot.

**Comment by hzoo** [comment]
Babel cannot handle json files so it's erroring. You'll want to filter those out before giving it to Babel.

**Comment by paulbartocillo** [comment]
Oh I see. Thanks. That's why I was able to compiled it by excluding json files on .baberc. Thanks for the clarification.
