### ISSUE TITLE
'let' in output and lost 'this' context

### ISSUE THREAD

**Issue by alexander-dmitriev** [babel/babel#4530]
### Input Code

``` js
function wrongTranspile() {
    if (some)
        for (let i = 0; i < length; i++) {
            let localVar;
            let arrowFn = () => {
                this.doSomethingWith(localVar);
            };
        }
}
```
### Output Code

``` js
"use strict";

function wrongTranspile() {
    if (some) {
        var _loop = function (i) {
            var localVar = void 0;
            var arrowFn = () => {
                this.doSomethingWith(localVar);
            };
        };

        for (let i = 0; i < length; i++) {
            _loop(i);
        }
    }
}
```

[This example online](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=true&loose=true&spec=true&code=function%20wrongTranspile%28%29%20%7B%0D%0A%20%20%20%20if%20%28some%29%0D%0A%20%20%20%20%20%20%20%20for%20%28let%20i%20%3D%200%3B%20i%20%3C%20length%3B%20i%2B%2B%29%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20localVar%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20arrowFn%20%3D%20%28%29%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.doSomethingWith%28localVar%29%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%7D)

Reproduced in any configuration and any version (I tested 6.7.2 and 6.14.0).

**Comment by danharper** [comment]
Huh, that arrow isn't being transpiled either. But it is if I add braces to the `if` statement:

```js
function wrongTranspile() {
    if (some) {
        for (let i = 0; i < length; i++) {
            let localVar;
            let arrowFn = () => {
                this.doSomethingWith(localVar);
            };
        }
    }
}
```

```js
"use strict";

function wrongTranspile() {
    var _this = this;

    if (some) {
        var _loop = function _loop(i) {
            var localVar = void 0;
            var arrowFn = function arrowFn() {
                _this.doSomethingWith(localVar);
            };
        };

        for (var i = 0; i < length; i++) {
            _loop(i);
        }
    }
}
```

**Comment by hzoo** [comment]
It's probably the block scoping plugin but it would be good to know the minimal config to repro

**Comment by alexander-dmitriev** [comment]
@hzoo, 

`package.json`
```js
{
  /* ... */
  "scripts": {
    "build": "babel wrong.js -d out"
  },
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-preset-es2015": "^6.14.0"
  }
}
```

`wrong.js`
```js
function wrongTranspile() {
    if (some)
        for (;;) {
            let localVar;
            let arrowFn = () => {
                this.doSomethingWith(localVar);
            };
        }
}
```

`.babelrc`
```js
{
  "presets": ["es2015"]
}
```

**Comment by danharper** [comment]
Yep, minimal repro:

```js
if (1)
  for (let i;;) {
    function a() {i}
  }
```

```js
{
  "plugins": ["transform-es2015-block-scoping"]
}
```

Output:

```js
if (1) {
  var _loop = function (i) {
    function a() {
      i;
    }
  };

  for (let i;;) {
    _loop(i);
  }
}

```

Add the block for `if`, and the `let` becomes `var`:

```js
if (1) {
  var _loop = function (i) {
    function a() {
      i;
    }
  };

  for (var i;;) {
    _loop(i);
  }
}
```

Or, if you change the `i` within the function to another identifier, it's fine too.

```js
if (1) for (var i;;) {
  var a = function a() {
    q;
  };
}
```

**Comment by Ciantic** [comment]
having a lot's of issues because of this

**Comment by nicolo-ribaudo** [comment]
This issue has been fixed on master: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABAdwE4IOYBVUEMwDOADjADYCmAFAJSIDeAUIs4jMIpQXALbnVMtBwOKg4UorRAF5EABgDckgDyIKYDFAAWimAGpdtRoOMtxquBFykAarlTyBJwWbvpkAMSQya0gHz1HJxMtGAIAOgATOABlHnIQ9QB1GC1KUgsrW1RqByDBAF9cp3yGfKA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=7.0.0-beta.1
