### ISSUE TITLE
babel-plugin-minify-dead-code-elimination should remove unused arguments

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel#4531]
### Input Code

Here's [a reproduction repo](https://github.com/kentcdodds/temp-babel-issue-dce)

```js
const foo = (arg1, arg2) => arg1
```

**.babelrc** (or what it might look like)

```js
{
  "plugins": ["minify-dead-code-elimination"]
}
```

### Expected Behavior

I would expect the output to be:

```js
const foo = (arg1) => arg1
```

### Current Behavior

Instead, the plugin doesn't do anything with unused arguments

```js
const foo = (arg1, arg2) => arg1
```

### Possible Solution

I'm not certain whether this is totally the responsibility of `babel-plugin-minify-dead-code-elimination`, but I can't think of any other plugin that should do this.

### Context

I'm writing a program slicing tool that's using `babel-plugin-minify-dead-code-elimination` directly to remove dead code after I've manipulated the AST to remove sliced nodes.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.14.0
| node             | 6.5.0
| npm              | 3.10.7
| Operating System | Mac OSX

**Comment by hzoo** [comment]
Thanks for the report Kent, - I think this would be best under the [babili](https://github.com/babel/babili/issues) repo (we should set up the issue templates there)

**Comment by kentcdodds** [comment]
Migrated the issue: https://github.com/babel/babili/issues/163
