### ISSUE TITLE
Allow babel-node to be used with other loaders like ts-node

### ISSUE THREAD

**Issue by trainerbill** [babel/babel#4535]
I would like the ability to use ts-node to compile to es6 and then babel to es5.  currently this is only possible by writing the files to the filesystem and running the independently.  For test suites/dev environment this is not very optimal 
### Expected Behavior

 it would be nice to be able to do ts-node babel-node tape /test/*.spec.js or something similar.
### Current Behavior

Does not work
### Possible Solution

The maintainer of ts-node has a suggestion here:

https://github.com/TypeStrong/ts-node/issues/51#issuecomment-241303952
### Context

Will allow us to use TypeScript + Babel at runtime in test/dev environment.

**Comment by danielmoore** [comment]
For those here looking to hook up ts-node into babel, I've written a wrapper library, [ts-babel-node](https://www.npmjs.com/package/ts-babel-node).

To the babel maintainers - there's not a great way to pipeline transpilers into each other. You can take a look at [what I had to do to hack these things together](https://github.com/danielmoore/ts-babel-node/blob/master/index.js#L15-L55) as an example.

**Comment by ccschneidr** [comment]
With the PR it would generally work. Still, it would need a possibility to process the source map as well. Currently babel ignores the existing map and just overrides it with the new one.

**Comment by jridgewell** [comment]
This was fixed by #3670.
