### ISSUE TITLE
env is being ignored in preset

### ISSUE THREAD

**Issue by foray1010** [babel/babel#4539]
### Babel Configuration (.bablerc, package.json, cli command)

this is my preset config: https://github.com/foray1010/babel-preset-foray1010/blob/d86899e005cde00541251d193c1dce70df316217/react.js

``` js
{
  presets: [
    require('babel-preset-es2015'),
    require('babel-preset-stage-2')
  ],
  plugins: [
    require('babel-plugin-transform-decorators-legacy').default,
    [require('babel-plugin-transform-react-jsx'), {
      pragma: 'createElement'
    }]
  ],
  env: {
    production: {
      plugins: [
        require('babel-plugin-transform-react-constant-elements'),
        require('babel-plugin-transform-react-inline-elements'),
        require('babel-plugin-transform-react-remove-prop-types').default
      ]
    },
    test: {
      plugins: [
        require('babel-plugin-istanbul')
      ]
    }
  }
}
```

this is how I require this preset it in another repo

``` json
{
  "presets": [
    "babel-preset-foray1010/react"
  ]
}
```

I am sure I set correct NODE_ENV to production, I can see process.env.NODE_ENV => production when I console.log in the preset file
### Expected Behavior

`babel-plugin-transform-react-constant-elements`, `babel-plugin-transform-react-inline-elements`, `babel-plugin-transform-react-remove-prop-types` should be used
### Current Behavior

None of them are being used, but when I put env config into the project .babelrc directly, it works
### Context

I want to share my react babel config to all my react project, and there are some plugins that I will only run in production, so I don't want to repeat myself every time in the babelrc on how to handle different env
### Your Environment

| software | version |
| --- | --- |
| Babel-core | 6.14.0 |
| node | 4.5.0 |
| npm | 3.10.7 |
| Operating System | Ubuntu 16.04 |

**Comment by gaearon** [comment]
It looks like this was introduced in #3564. This behavior didn’t exist in `babel-core@6.10.4`, but exists in all versions after it. cc @jamestalmage

**Comment by hzoo** [comment]
There's a test for env in the PR as well but will have to investigate: https://github.com/babel/babel/pull/3564/files#diff-4e0bc531c318f2a21593a66c39f1fe54R157

**Comment by hzoo** [comment]
When moving `buildConfigChain` we don't resolve presets so the env options aren't merged (or vice versa). Or we resolve and then don't merge again later

**Comment by hzoo** [comment]
Workaround is what @gaearon did in create-react-app - https://github.com/facebookincubator/create-react-app/pull/716/files

Just write the env logic in the preset itself

**Comment by MoOx** [comment]
Is the workaround really needed since you pushed c3cf24bd2e5783b42a18ee272e8434cb7c810ef8 ?

**Comment by hzoo** [comment]
It's not in master since some other tests were failing

**Comment by hzoo** [comment]
We're going to go with deprecating "env" as an option in 7.0 and asking for users to use a `.babelrc.js` file to support this use case (https://github.com/babel/babel/pull/4892). Basically the workaround is the new suggestion since it's not too much of a pain to do. We can think about writing some utils or just recommending what's done for webpack like https://github.com/kentcdodds/webpack-config-utils.
