### ISSUE TITLE
Unknown plugin "syntax-async-functions" (npm 2.15.9)

### ISSUE THREAD

**Issue by mkozjak** [babel/babel#4540]
### Issue
Currently the project (https://github.com/qaap/pharos) is not transpiling if done on node 4.5.0, npm 2.15.9.

Works good on node 6.x.
If I do npm install -g npm (upgrade from npm 2.x to 3.x) it works correctly.

### Steps to reproduce
```
n lts
git clone https://github.com/qaap/pharos
cd pharos
npm install
npm test
```

### Warnings
There is a warning when installing via npm 2.x:
```
npm WARN peerDependencies The peer dependency babel-core@>6.0.0 included from jsdoc-babel will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.14
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
// .babelrc
{
    "presets": [
        "latest"
    ],
    "plugins": [
        "syntax-async-functions",
        "transform-async-to-generator",
        "transform-runtime",
        "transform-regenerator",
    ]
}
```

### Context
Transpiling my application to multiple Node.js environments.

### Your Environment
OS: Ubuntu 16.04 LTS
babel-cli 6.14.0
babel-plugin-transform-runtime 6.15.0
babel-preset-latest 6.15.0
jsdoc-babel 0.2.1
jsdoc-to-markdown 2.0.0-alpha.15
npm 2.15.9
node 4.5.0

**Comment by hzoo** [comment]
I don't see the error you made for the title in the description?

and latest includes `transform-async-to-generator`/syntax already because es2017 does http://babeljs.io/docs/plugins/preset-es2017/

**Comment by danez** [comment]
`jsdoc-babel` needs a peer dependency of `babel-core`. Did you install it when installing jsdoc-babel?

**Comment by loganfsmyth** [comment]
You don't have that syntax plugin in your deps, so it's working by chance because of Npm3's flattening, but not in Npm 2. Since you don't need it, just remove it. It'll load with the transform already.

**Comment by hzoo** [comment]
Should we be erroring if both syntax and something that enables syntax is specified?

**Comment by mkozjak** [comment]
If I include babel-core and remove all the plugins, I get ReferenceError: regeneratorRuntime is not defined with npm 2.x...

**Comment by hzoo** [comment]
when is that happening? when building? Yes it's better to use npm 3 but you'll need babel-runtime as a dependency if you didn't include that. If you are using transform-runtime you don't need transform-regenerator either.

```js
{
    "presets": ["latest"],
    "plugins": ["transform-runtime"]
}
```

is probably good

**Comment by mkozjak** [comment]
@hzoo Seems like mocha complains:

```module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/typeof'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mkozjak/pharos/dist/index.js:8:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mkozjak/pharos/test/index.spec.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/mkozjak/pharos/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/mkozjak/pharos/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/mkozjak/pharos/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/home/mkozjak/pharos/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3```

**Comment by mkozjak** [comment]
@danez This complains only on npm 2.x. I don't need to include babel-core on npm 3.x.

**Comment by danez** [comment]
Yes it works on npm 3 because you also have babel-cli which depends on babel-core, but you should even on npm3 install babel-core, because you shouldn't depend on dependencies of your dependencies.

About the babel-runtime error: You also need to install babel-runtime in your dependencies (not devDependencies), because when you use transform-runtime your code depends on babel-runtime being installed at runtime.

**Comment by mkozjak** [comment]
@danez Nice! Everything works as expected now!

package.json:
```js
  "dependencies": {
    "assert-args": "^1.2.1",
    "babel-runtime": "^6.11.6",
    "ws": "^1.1.1"
  },
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-core": "^6.14.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-latest": "^6.14.0",
    "chai": "^3.5.0",
    "js-beautify": "^1.6.4",
    "jsdoc-babel": "^0.2.1",
    "jsdoc-to-markdown": "^2.0.0-alpha.15",
    "mocha": "^3.0.2"
  }
```

.babelrc:
```
{
    "presets": [
        "latest"
    ],
    "plugins": [
        "transform-runtime"
    ]
}
```
