### ISSUE TITLE
Need two .babelrc: one for node server & other for react project

### ISSUE THREAD

**Issue by budarin** [babel/babel#4541]
I have a project based on node.
Node app uses babel for transpling es6 js to node6 js
In the same project I use react app and need to configure babel to use another presets and configuration options

I need to run server and run webpack builder using babel for react app at the same time, but I have only one babelrc and dont know how to setup it for different projects.

**Comment by hzoo** [comment]
Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

---

I would check out using the env options though http://babeljs.io/docs/usage/babelrc/#env-option

**Comment by budarin** [comment]
env option is about to use one config in different environments but not about use babel in one project to run two different instances  with different options
