### ISSUE TITLE
babel --language_out=ES5 does not work

### ISSUE THREAD

**Issue by kofifus** [babel/babel#4548]
babel --language_out=ES5 windows command line option does not seem to work

I try:

npm install babel-cli babel-preset-latest

`babel --presets babel-preset-es2015 --language_out=ES5 --compact true code.js > babled.js`

I get:

```
code.js:10: ERROR - This code cannot be converted from ES6. ES5 getters/setters (consider
using --language_out=ES5)
                set onoptchange(f) { optchangeFunc=f; }, 
```

why ?

**Comment by loganfsmyth** [comment]
Where did you come across that? That is not a valid Babel option. I believe that is for Closure Compiler maybe?

**Comment by kofifus** [comment]
you're right .. my bad
