### ISSUE TITLE
Bug: unexpected wrapper breaks switch-case

### ISSUE THREAD

**Issue by micooz** [babel/babel#4549]
### Input Code

``` js
function func(p1, p2) {
  return false;
}

function bug(options) {
  switch (1) {
    case 1: {
      const {array} = options;
      const items = [{v: 1}, {v: 2}, {v: 3}];

      for (const item of items) { // for-of
        const ret = func(item, () => array); // arrow-func reference up layer var

        if (ret) {
          return true;
        }
      }
      console.log(1);
      break; // doesn't work
    }
    case 2: {
      console.log(2);
      break;
    }
    default:
      break;
  }
}

bug({array: [1, 2, 3]});
// output:
// 1
// 2
```
### Babel Configuration (.bablerc, package.json, cli command)

``` js
// .bablerc
{
  "presets": [
    "latest"
  ]
}
```
### Expected Behavior

```
1
```
### Current Behavior

```
1
2
```
### Possible Solution

Remove `for-of` or `arrow function`.
### Context

Babel wraps my first `case` into a IIFE which returns `"break"`, in the following switch-case, `break;` just breaks that switch, not upper switch.

I have no idea why Babel creates a wrapper, it seems that `for-of` and `arrow-func` have side-effect in this case.

``` js
"use strict";

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };

function func(p1, p2) {
  return false;
}

function bug(options) {
  switch (1) {
    case 1:
      {
        var _ret = function () {
          var array = options.array;

          var items = [{ v: 1 }, { v: 2 }, { v: 3 }];

          var _iteratorNormalCompletion = true;
          var _didIteratorError = false;
          var _iteratorError = undefined;

          try {
            for (var _iterator = items[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
              var item = _step.value;
              // for-of
              var ret = func(item, function () {
                return array;
              }); // arrow-func reference up layer var

              if (ret) {
                return {
                  v: true
                };
              }
            }
          } catch (err) {
            _didIteratorError = true;
            _iteratorError = err;
          } finally {
            try {
              if (!_iteratorNormalCompletion && _iterator.return) {
                _iterator.return();
              }
            } finally {
              if (_didIteratorError) {
                throw _iteratorError;
              }
            }
          }

          console.log(1);
          return "break"; // doesn't work
        }();

        switch (_ret) {
          case "break":
            break;

          default:
            if ((typeof _ret === "undefined" ? "undefined" : _typeof(_ret)) === "object") return _ret.v;
        }
      }
    case 2:
      {
        console.log(2);
        break;
      }
    default:
      break;
  }
}

bug({ array: [1, 2, 3] });
// output:
// 1
// 2
```
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.14.0 (babel-core 6.14.0) |
| node | v6.6.0 |
| npm | 3.10.3 |
| Operating System | Ubuntu16.04 LTS |

**Comment by slavkur** [comment]
```
dispatcher.register(payload => {
  switch('test1') {
    case a: {
      const client = 1;
      if(a === 1) {
        return;
      }
      func(() => console.log(client.id), 1);
      break;
    }
    case b:
      break;
  }
});
```
has similar output with strange wrapper

**Comment by Asp3ctus** [comment]
+1
i think it's because it's transformed to 
case '1': {
		return 'break';
}();

**Comment by VictorQueiroz** [comment]
No solutions until here?

**Comment by smartynov** [comment]
Still struggling with this bug. Any chance to fix it?

I experimented a bit with https://babeljs.io and found somewhat minimum [code to reproduce the bug](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&experimental=false&loose=false&spec=false&playground=false&code=function%20f%20(a)%20%7B%0A%20%20switch%20(a)%20%7B%0A%20%20%20%20case%201%3A%20%7B%0A%20%20%20%20%20%20let%20b%20%3D%201%3B%0A%20%20%20%20%20%20if%20(a%20%3E%201)%20%7B%0A%20%20%20%20%20%20%20%20return%20i%20%3D%3E%20%7B%20return%201%20%2B%20b%20%7D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20return%202%3B%0A%20%20%7D%0A%20%20return%201%3B%0A%7D%0Aconsole.log(f(1))%3B%20%2F%2F%20expected%3A%201%0Aconsole.log(f(2))%3B%20%2F%2F%20expected%3A%202%0A):
```js
function f (a) {
  switch (a) {
    case 1: {
      let b = 1;
      if (a > 1) {
        return i => { return 1 + b };
      }
      break;
    }
    default:
      return 2;
  }
  return 1;
}
console.log(f(1)); // expected: 1
console.log(f(2)); // expected: 2
```

The function compiles to the following:
```js
function f(a) {
  switch (a) {
    case 1:
      {
        var _ret = function () {
          var b = 1;
          if (a > 1) {
            return {
              v: function v(i) {
                return 1 + b;
              }
            };
          }
          return "break";
        }();

        switch (_ret) {
          case "break":
            break;

          default:
            if ((typeof _ret === "undefined" ? "undefined" : _typeof(_ret)) === "object") return _ret.v;
        }
      }
    default:
      return 2;
  }
  return 1;
}
```

Note the `switch (_ret)` part: `break` goes inside it, which breaks the code. Replacing this `switch` with `if ... else if` chain in generated code should fix the issue.

Until someone fixed it, the possible workaround is to use named `break`, [as follows](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015&targets=&browsers=&builtIns=false&experimental=false&loose=false&spec=false&playground=false&code=function%20f%20(a)%20%7B%0A%20%20z%3A%20switch%20(a)%20%7B%0A%20%20%20%20case%201%3A%20%7B%0A%20%20%20%20%20%20let%20b%20%3D%201%3B%0A%20%20%20%20%20%20if%20(a%20%3E%201)%20%7B%0A%20%20%20%20%20%20%20%20return%20i%20%3D%3E%20%7B%20return%201%20%2B%20b%20%7D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20break%20z%3B%0A%20%20%20%20%7D%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20return%202%3B%0A%20%20%7D%0A%20%20return%201%3B%0A%7D%0Aconsole.log(f(1))%3B%20%2F%2F%20expected%3A%201%0Aconsole.log(f(2))%3B%20%2F%2F%20expected%3A%202%0A):
```js
function f (a) {
  z: switch (a) {
    case 1: {
      let b = 1;
      if (a > 1) {
        return i => { return 1 + b };
      }
      break z;
    }
    default:
      return 2;
  }
  return 1;
}
console.log(f(1)); // expected: 1
console.log(f(2)); // expected: 2
```

**Comment by rromanw** [comment]
The bug is still present on the latest babel-core 6.23.1 . It is really annoying.

**Comment by philippefutureboy** [comment]
I met a similar issue here:

```
const curried = console.log.bind(console);

const currier = (f, a, x) => {
  switch(arguments.length){
  case 0:
    throw new Error('currier expected at least one argument');
  case 1:
    return function (a, x) {
      return arguments.length >= 2
        ? curried(f, a, x)
        : currier(f, a);
    };
  case 2:
    return (x) => curried(f, a, x);
  case 3:
  default:
    return curried(f, a, x);
  }
};

```

Will cause `currier(f)` to return undefined rather than a function. The problem can be solved by replacing the declaration of currier by `const currier = function (f, a, x) {`.

```
const curried = console.log.bind(console);

const currier = function (f, a, x) {
  switch(arguments.length){
  case 0:
    throw new Error('currier expected at least one argument');
  case 1:
    return (a, x) => {
      return arguments.length >= 2
        ? curried(f, a, x)
        : currier(f, a);
    };
  case 2:
    return (x) => curried(f, a, x);
  case 3:
  default:
    return curried(f, a, x);
  }
};

```

Will cause case 1 to bind the function `(a, x) => { ... }` to the parameters `f`, with no further parameters possible. Can be solved by replacing  `(a, x) => {` with `function (a, x) {`.

**Comment by Andarist** [comment]
@philippefutureboy arrows do not their `arguments`, just how they do not get their `this`. Both those references point out to the objects from the closure.

**Comment by philippefutureboy** [comment]
Well, the more you know 🌈 
Thanks I didn't know that :)

**Comment by armano2** [comment]
i tested issue on latest version and code geenrated now seem to be correct, i'm unsure when this was fixed [REPL](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=entry&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABKSAKADgRgDSPQJgEpEBvAKEUQCcBTKEKpYAQwBsBnGgbjIF8yyKaPCQAjEAHNUcdLATti5SuwDuMKBAAWiVJkUVKiCM06JMALlIHDR-VFLMqVZgE9eiALyIZcsOx42lBB2iOo0ALbsnogA2iQAbpaYvLgJlvgppImIAMy8ALo81obAcFQ6wX72YeHewKFQEQqkiAD0rchlALRwwMU2lez2tPZeQqg1uKjEHgB8iI7OLoRcbR2LcCpdQtQ0wDS0kDSIIOiIrK4HiPGOAoGGMPWoI_r3NiMMSFBUINz9hvx7oDAoM4KwaAA6VhwKR6AKBUS0ZgAa1W7UQABM4DR2GAAOT2FRlZHFYFBEzHfCWJQg-RgyHQqREeE2RE0FEsxBkzF7ZggVhQcz_Nkcgz8fhkcRSEiLVyWGI4RD4XA5fK8FZkdFwEBQdA68xAA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.13.7&externalPlugins=)

**Comment by nicolo-ribaudo** [comment]
Thanks @armano2 for checking old issues :yellow_heart:
