### ISSUE TITLE
Cannot ignore node_modules when using --only

### ISSUE THREAD

**Issue by cyberwombat** [babel/babel#4558]
I am using babel to transpile my code. Tried a few version, latest I am using is 6.11.4. Posted on [SO](http://stackoverflow.com/questions/39581245/babel-only-always-includes-node-modules) but no answers.

Sample tree:
- lib
- data
- node_modules

My goal is to ignore `node_modules` and transpile the rest. I am currently doing:

```
babel --ignore node_modules --out-dir dist
```

This works. However I would like to selectively pick which directories to transpile so I see the `--only` option which states: "list of glob paths to **only** compile"

```
babel --only data,lib --out-dir dist
```

This results in all 3 directories (yes, node_modules as well) being compiled.

I have tried this as well:

```
babel --ignore node_modules --only data,lib --out-dir dist
```

Same result - all 3. 

I've toyed around with quotes/regex as Ive seen somewhat related discussions (ex: '/node-modules') to no avail.

I cannot find any docs or bug reports addressing this. Is this intentional?

| software | version |
| --- | --- |
| Babel | 6.11.4. |
| node | 6.4.0 |
| npm | 3.10.3 |
| Operating System | OSX Sierra |

**Comment by ianstormtaylor** [comment]
Running into the same thing, it doesn't appear possible to use `--only` without `./node_modules` being compiled as well...

**Comment by hzoo** [comment]
In https://github.com/babel/babel/pull/5487 and other prs we are fixing how only/ignore work and interact so this should be fixed in Babel 7

**Comment by hzoo** [comment]
@ianstormtaylor btw I think we'd be interested in the OSS fellowship 😁

**Comment by ianstormtaylor** [comment]
@hzoo haha awesome, you should apply!
