### ISSUE TITLE
Add description to all package.json files

### ISSUE THREAD

**Issue by danez** [babel/babel#4559]
We currently have a lot of npm packages that do not contain descriptions in `package.json`. It would be nice to add descriptions to all of them.

There is already a PR for this #3371 but the description added there is not really helpful. 

As a source for the descriptions the babel-handbook might be a good source: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/README.md

**Comment by sstern6** [comment]
@danez this would my first contribution to babel, would it be ok if I take this one on?

Thanks

**Comment by danez** [comment]
Sure, if you have any questions you can reach us all on the babel slack (see readme for connection info)

**Comment by sstern6** [comment]
Perfect thanks @danez

**Comment by kutyel** [comment]
Is this already fixed? Can I have a try? Thanks in advance! Happy **#hactoberfest!**

**Comment by sstern6** [comment]
@kutyel have already started working on this but got away from this over the last few days.  Should have a PR open in a day or so.  If I dont have this PR up by Friday would you like to take this over?

Thanks

**Comment by kutyel** [comment]
Sure don't worry, and even if you don't finish it by Friday you can just commit your progress and I'll continue where you left of 😉 no pressure!
