### ISSUE TITLE
Issue when a variable is exported before being declared

### ISSUE THREAD

**Issue by julien-f** [babel/babel#4567]
In other words: variable declarations are not correctly hoisted regarding export.

Using `const`, `let` or `var`, trigger the same issue.

### Input Code

``` js
export { foo }
var foo = 42
```
### Babel Configuration (.bablerc, package.json, cli command)

``` js
{
  "presets": [ "es2015" ]
}
```
### Expected Behavior

``` js
var foo
exports.bar = foo
exports.bar = foo = 42
```
### Current Behavior

``` js
exports.bar = foo
var foo = 42
```

### Your Environment

Code on [Babel's repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=true&loose=false&spec=false&code=export%20{%20foo%20}%0Avar%20foo%20%3D%203), same results locally with babel v6.15.

**Comment by DrewML** [comment]
To clarify, the report here isn't about hoisting, but ES module's "live bindings," right? Hoisting here would automatically be handled by the engine, since you're using a `var`. Based on your expected behavior, it seems like what you are expecting (and is not happening) here is for the live binding behavior.

**Comment by julien-f** [comment]
Yes, the issue is related to live binding, but AFAIU, the symbol can be exported prior to its declaration due to hoisting :smile:

**Comment by DrewML** [comment]
@julien-f Yep! I believe that is accurate - just wanted to make sure I fully understood the issue.

**Comment by nicolo-ribaudo** [comment]
This now works (`exports.foo` is correctly updated after `foo` is assigned): https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAbzgMwhOBfAUANwIZQppwC8cALAExA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=7.0.0-beta.1

**Comment by loganfsmyth** [comment]
Yup! Nice. Fixed in 7.x.
