### ISSUE TITLE
Fix invalid Bablyon parser options

### ISSUE THREAD

**Issue by danez** [babel/babel#4571]
We are currently sending invalid options to [babylon](https://github.com/babel/babylon). The valid options are documented in the README of babylon.

[lib/parser.js](
https://github.com/babel/babel/blob/master/lib/parser.js) This file contains outdated flow-types for babylon options.

[babel-core/src/transformation/file/index.js:51](
https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/index.js#L51) The same here.

Seems the test are failing when removing the invalid parser options. (according to #4570) Which would need to be investigated why.

**Comment by sstern6** [comment]
@danez seems like a solid first non-doc contribution/exploration.

Mind if i take this one?

**Comment by existentialism** [comment]
@sstern6 hope you don't mind, but I pushed a PR for this since I was needing to use one of the options locally

**Comment by sstern6** [comment]
Not a problem @existentialism, apologize i didnt get this up sooner

**Comment by kaicataldo** [comment]
Does this mean this issue has been resolved?

**Comment by danez** [comment]
True, closing.
