### ISSUE TITLE
Optionally compile flow types into assertions

### ISSUE THREAD

**Issue by phpnode** [babel/babel#458]
It would be really awesome if a declaration like this:
```js
function say (text:string, speaker:User) : string {
  return speaker.name + ' says ' + text;
}
```
could be *optionally* compiled into
```js
function _assert (assertion, message) {
  if (!assertion) {
    throw new TypeError(message);
  }
}
function say (text, speaker) {
  _assert(typeof text === 'string', "'text' should be a string");
  _assert(speaker instanceof User, "'speaker' should be an instanceof User");
 
  var ret = speaker.name + ' says ' + text;
 
  _assert(typeof ret === 'string', "say() should return a string");
 return ret;
}
```

This would be super useful in development or when debugging, and may be fast enough to be enabled at runtime in a lot of cases.

> Note: I'm not suggesting full type inference or anything like that here, I'm suggesting something more akin to design by contract. The transformation would only happen when the developer explicitly specifies types.

**Comment by sebmck** [comment]
Possible improvement would be to add a dynamic import as-is done with the optional `coreAliasing` and `bluebirdCoroutines` transformers. So you'd use nodes `assert`.

**Comment by monsanto** [comment]
Expanding on what I was saying in chat--such a transform would have to be limited to argument types and return types of functions. For anything more, you will have to deal with mutable objects and aliasing. Without the type inference & propagation that flow itself would do, you aren't really in a position to deal with that problem.

A transform that only dealt with argument/return types would be fairly easy to write. The only tricky parts are dealing with polymorphism and function types. Function types in particular need to be wrapped such that every usage checks their type. That is:

```
function foo(x: string, f : (number) => string) {
  // ...  calls to f ...
}

--->

function foo(x: string, f : (number) => string) {
  assert(x, string);
  f = wrapAssert(f, [number], string);
  // ... calls to f ... 
}
```

If you're interested in reading more, the academic literature has a lot to say about this subject if you search for "contract system", "manifest contracts", "higher-order contracts", etc. The Racket language probably has the best implementation of a contract system. [Here's a link to the paper that kicked off this field of research](http://www.eecs.northwestern.edu/~robby/pubs/papers/ho-contracts-techreport.pdf).

**Comment by sebmck** [comment]
My original position was actually that I didn't think this belonged in the 6to5 core. However I think of the scope of it can be restricted to just function parameters and return values then I'm fine with it.

**Comment by phpnode** [comment]
i believe it would be possible to do with variable declarations too without too much pain, 
```js
var name:string = "Bob";
var greeting:string;

greeting = foo();
greeting = bar();
```
could compile to
```js
var ref$name = "Bob",
      name = (_assert(typeof ref$name === "string", "'name' should be a string"), ref$name);

var greeting;
_assert(typeof (greeting = foo()) === "string", "'greeting' should be a string");
_assert(typeof (greeting = bar()) === "string", "'greeting' should be a string");
```
I think this is relatively similar to how `const` works at the moment, but I understand if you don't want to go this far, for me support for function parameters and return types would be awesome.

**Comment by monsanto** [comment]
@phpnode That's possible too, we'd just need to store the associated type in the scope. The reason I was loathe to suggest this is because often variable reassignment goes hand in hand with object mutation--users might be confused to find that we can ensure assignments to `greeting` can check types, but `greeting.x` or more generally `greeting[propName]` can't.

It's worth noting that we can check mutable objects (with a caveat for aliasing) when ES6 proxies land. You'd use a similar strategy to function wrapping.

**Comment by gcanti** [comment]
Hi there, I'm working on this as a separate step (using jstransform) if anyone is interested to share
some thoughts

https://github.com/gcanti/flowcheck

**Comment by lukescott** [comment]
Just wanted to point out that `console.assert` can be used instead of a custom assert function. These can also be (optionally) stripped out with Uglify's `drop_console` option for production code.

**Comment by sebmck** [comment]
@lukescott 6to5 actually has a `minification.removeConsoleCalls` optional transformer.

**Comment by lukescott** [comment]
@sebmck Either way having the flow type assertions use `console.assert` makes them, and other `console.*` methods easy to remove. Of course if you have two 6to5 build processes for staging/production you can simply not do the type assertions at all. Still, makes them easy to remove with other tools later.

**Comment by cesarandreu** [comment]
Maybe worth taking a look at [AtScript](https://docs.google.com/document/d/11YUzC-1d0V1-Q3V0fQ7KSit97HnZoKVygDxpWzEYW0U/edit), they're doing something similar. They made this [Assert.js](http://angular.github.io/assert/) library. 

No idea how mature any of that might be (or if it's even usable), but I figured it was worth sharing.

**Comment by timoxley** [comment]
FWIW this has a similar goal to the type-checking instrumentation proposed in "Safe TypeScript":

* http://research.microsoft.com/pubs/224900/safets.pdf
* http://research.microsoft.com/apps/video/default.aspx?id=226836

**Comment by sebmck** [comment]
Closing this in preparation for the plugin API as this is something I'd like to push out to userland #987.

**Comment by phpnode** [comment]
In case anyone's interested I've just released a plugin that implements this, (but you'll need bleeding edge babel in order to try it) - https://github.com/codemix/babel-plugin-typecheck
