### ISSUE TITLE
Allow async exec test to reject

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4583]
Ref https://github.com/babel/babel/pull/4576#discussion_r80736933 and commited in https://github.com/babel/babel/commit/5ea57d5e9cb1c049fba142930ba3acde9cc473c2

In an exec test, you can now return a promise. We use mochajs.org for tests and returning a promise will cause it to asynchronously call done.

https://github.com/babel/babel/blob/5ea57d5e9cb1c049fba142930ba3acde9cc473c2/packages/babel-plugin-transform-async-generator-functions/test/fixtures/for-await/async-generator-exec/exec.js#L22-L25

``` js
return forEach(genAnswers(), function(val) { output += val.value })
.then(function () {
  assert.equal(output, 42);
});
```

You need to add to options.json (to fix parser error)
```
{
  "parserOpts": {
      "allowReturnOutsideFunction": true
   }
}
```

The suggestion is to allow a rejection instead of just .then

**Comment by alxpy** [comment]
@hzoo hi, this issue is already possible to close)

**Comment by hzoo** [comment]
When did someone add it? I definetely don't remember adding it. There's no test with a `return a().catch()`

**Comment by alxpy** [comment]
@hzoo I can add this test

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/11740
