### ISSUE TITLE
Use "boolean" for BooleanTypeAnnotation in code generation

### ISSUE THREAD

**Issue by zpao** [babel/babel#4584]
### Expected Behavior
`t.booleanTypeAnnotation` should print as `boolean`

### Current Behavior
`bool`

### Possible Solution
Just change this line: https://github.com/babel/babel/blob/5ea57d5e9cb1c049fba142930ba3acde9cc473c2/packages/babel-generator/src/generators/flow.js#L14

### Context
`bool` is valid Flow but `boolean` is the officially supported type so we should use that. I don't know if the Flow team has any plans to deprecate the `bool` type but it is undocumented and IIRC only there for TypeScript compat.

**Comment by hzoo** [comment]
Should be a nice first contribution? Maybe fix the tests as well

**Comment by sugargreenbean** [comment]
Hi, I'd like to work on this! How do I begin contributing? @hzoo Where do I find the associated tests?

**Comment by hzoo** [comment]
@sugargreenbean Cool - after you setup with `make bootstrap` you can run the tests. Checkout our contributing doc https://github.com/babel/babel/blob/master/CONTRIBUTING.md#developing. You can basically just run `make watch` to build babel and then run `make test-only` to see which tests fail

**Comment by zpao** [comment]
Yay, thanks @sugargreenbean! As @hzoo said, running the tests after making the change should result in some failures. Primarily I expect the test changes would be localized to this directory: https://github.com/babel/babel/tree/master/packages/babel-generator/test/fixtures/flow. You might want to add a test or two to make sure input that has `bool` annotations gets re-printed as `boolean`.

**Comment by sugargreenbean** [comment]
@zpao Thanks! I'm trying to push to a feature branch off of Git, do I need to be granted permissions to the Babel repo to do this?

**Comment by hzoo** [comment]
So actually you don't - you clone the repo so you can make changes locally and then you can make a pull request. Usually the main repo remote is named `upstream` and your own is `origin`.

You'll want to make a pull request https://help.github.com/articles/about-pull-requests/. I would check out https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github as a resource.

**Comment by danez** [comment]
@sugargreenbean You can also join #development on [slack](https://slack.babeljs.io/) if you have more questions.

**Comment by sugargreenbean** [comment]
Hi! Thank you all for the help. I finished the work, but I am stuck behind a proxy and can't make a PR. I am looking for my older computer without proxy settings on it, and I will make a PR then. Thanks again for your patience! :)

**Comment by sugargreenbean** [comment]
When I try git push origin -u myFeatureBranch, I am getting URL error: 403. Do I need to be added as a contributor to this repo so I can make pull requests?

**Comment by hzoo** [comment]
You don't! what is `origin` for you? I'm assuming its `https://github.com/babel/babel` - what some people do is make upstream the main repo (`babel/babel` in this case) and origin your fork so `sugargreenbean/babel`. then you push to your own fork and then you can make a pull request.

**Comment by sugargreenbean** [comment]
@hzoo Thank you so much for your patience!!! I've finally figured it out and put in a pull request... :) Exciting!
