### ISSUE TITLE
Exporting decorated class error

### ISSUE THREAD

**Issue by Awk34** [babel/babel#4585]
### Input Code

``` js
@Decorator()
export class MyClass {}
```
### Babel Configuration (.bablerc, package.json, cli command)

``` js
{
    "plugins": [
        "syntax-decorators"
    ]
}
```
### Expected Behavior

``` js
@Decorator()
export class MyClass {}
```
### Current Behavior

``` js
export @Decorator()
class MyClass {}
```
### Possible Solution

What I'm currently doing to circumvent this:

``` js
export let MyClass = @Decorator()
class MyClass {}
```

¯\\\_(ツ)\_/¯
### Context

I've got a project where I'm trying to parse ES6 code with Flow types, and just take the types out. This minimal case reproduces the same issue, though.
### Your Environment

| software | version |
| --- | --- |
| Babel | babel-cli@6.14.0 |
| node | 6.5.0 |
| npm | 3.10.3 |
| Operating System | Win 10 x64 |

**Comment by Awk34** [comment]
This might be an issue for Babylon instead

**Comment by hzoo** [comment]
Is there a reason why you aren't using the transform? You can use https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy to transform decorators and https://babeljs.io/docs/plugins/transform-flow-strip-types/ to remove flow types

**Comment by loganfsmyth** [comment]
This should be a pretty self-contained code generator fix. We'll need the export declaration step to test what kind of declaration  it has to potentially render decorators, and the opposite logic to skip them when rendering the class declaration itself.

**Comment by Awk34** [comment]
@hzoo it goes alongside #4388 that I reported. I have a Yeoman generator that I want to have parse JS files, and then strip flow types, but leave the remainder of the code mostly unchanged.

**Comment by Awk34** [comment]
@loganfsmyth can you point me to where this might be fixed in the code?

**Comment by hzoo** [comment]
Yeah `babel-generator`. each node type has a function that prints it out. 

Example with decorator: https://github.com/babel/babel/blob/39c92160f7a0231ea60f4058469e21f44f3b372f/packages/babel-generator/src/generators/expressions.js#L79-L83

Probably need to fix something in babel/modules.js like at https://github.com/babel/babel/blob/39c92160f7a0231ea60f4058469e21f44f3b372f/packages/babel-generator/src/generators/modules.js#L70-L118

Can use http://astexplorer.net/#/pzoRIHiZyd to view the AST

**Comment by devongovett** [comment]
Fixed by https://github.com/babel/babel/pull/5020.

**Comment by hzoo** [comment]
This isn't allowed in Stage 2 decorators anymore so closing

https://github.com/babel/babylon/pull/587/files#diff-cd89c8d2f00940bd0d50120e23c326edR1

> 3.4. export keyword in between of class body and decorators
