### ISSUE TITLE
babel-traverse cache not initialized with TryStatement path?

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel#4586]
### Input Code

```js
export {tryCatch}

function tryCatch(shouldThrow) {
  const ret = {}
  try {
    if (shouldThrow) {
      throw new Error('throw error')
    }
    ret.noThrow = true
  } catch (error) {
    ret.error = error
    return error
  } finally {
    return ret
  }
}
```

### astexplorer.net

[Here](https://astexplorer.net/#/SPHNWQu0EQ/1) is the astexplorer.net example

The plugin:

```js
export default function () {
  return {
    visitor: {
      TryStatement(path) {
        // this plugin is intended to replace the try/catch with simply the code in the try and finally blocks
        path.parentPath.insertAfter([...path.node.block.body, ...path.node.finalizer.body])
        path.remove()
      } 
    }
  }
}
```

### Current Behavior

Getting error: `Cannot read property 'length' of undefined`
From [this line](https://github.com/babel/babel/blob/590ad4d24fef8268696149b3ae67aec54ee12fcc/packages/babel-traverse/src/path/modification.js#L139). It appears that the `pathCache` isn't primed with the paths it needs. I'm not sure I understand what's going on or how to fix it though...

### Context

I'm writing a plugin to create a program slice based on code coverage data. So I need to remove the `TryStatement` when the `catch` is uncovered.

**Comment by boopathi** [comment]
Maybe you can use this now - 

```js
path.replaceWithMultiple([ path.node.block, path.node.finalizer ])
```

Note: block scoped variables inside `block` and `finalizer` might give problems if the BlockStatement is removed without checking for those.

**Comment by kentcdodds** [comment]
That worked great! Thanks @boopathi! I think I'll leave this open anyway though because I think this should work right?

**Comment by danez** [comment]
I'm not entirely sure, but shouldn't `path.parentPath.insertAfter` be `path.insertAfter`. Because path.parentPath is the function body if I'm not mistaken. But I could also be totally wrong.

**Comment by kentcdodds** [comment]
Oh snap, [you're totally right](https://astexplorer.net/#/SPHNWQu0EQ/3) @danez. I could swear that I tried that. :face_palm: Thanks!
