### ISSUE TITLE
lerna bootstrap command fails on Windows

### ISSUE THREAD

**Issue by garyjN7** [babel/babel#4589]
Whilst trying to set up Babel for dev purposes on Windows - after running the npm install command the:
_./node_modules/.bin/lerna bootstrap_
command fails.
### Expected Behavior

All packages should be successfully bootstrapped.
### Current Behavior

Get error:
_Errored while running BootstrapCommand.execute
-4058_
### Possible Solution

After a bit of research, this problem appears to be because of a change in lerna version v2.0.0-beta.20 where the creation of a child process was changed from exec to spawn, which in turn causes the Windows npm command to fail.  This was later fixed in v2.0.0-beta.26 of lerna where the spawn process was changed to use cross-spawn.  However, babel is currently configured to use v2.0.0-beta.23 of lerna which still uses the standard spawn function.

I altered babel's package.json and lerna.json files to use v2.0.0-beta.26 of lerna in my environment and the bootstrap command executed successfully after the npm install.
### Context

Unable to build babel for development purposes in Windows.
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.15.0 |
| node | 6.5.0 |
| npm | 3.10.3 |
| Operating System | Windows 7 |

**Comment by hzoo** [comment]
Thanks for the report! - https://github.com/babel/babel/pull/4492 should fix it then

**Comment by garyjN7** [comment]
I have just tested the #4492 pull request to double-check it had the same problem as I had this morning when I tested the v2.0.0-beta.29 version of lerna with v6.15.0 of babel, and it does...  It gets to "Symlinking packages and binaries" but then errors with
Error: EPERM: operation not permitted, 'C:\...\babel\packages\babel-helper-fixtures' -> 'C:\...\babel\packages\babel-cli\node_modules\babel-helper-fixtures' at Error (native)
But I am happy to spend a bit of time debugging this to see if I can pin down the issue.

**Comment by hzoo** [comment]
Ok we also update to 28 for now since 29 added symlinks

**Comment by motiz88** [comment]
FYI lerna/lerna#348 (merged, unreleased) fixes the permissions issue on Windows.

**Comment by garyjN7** [comment]
Strangely, using v2.0.0-beta.28 also gets the symlink error, although using v2.0.0-beta.27 of lerna seems to work, albeit with some "Encountered a cycle in the dependency graph" warnings.  Here is the output from both versions...

![image](https://cloud.githubusercontent.com/assets/17061859/18920680/0b832ff8-859a-11e6-817f-5f686729a01c.png)

**Comment by garyjN7** [comment]
I have tested the latest version of babel - 16.6.1 with the latest master branch of lerna with motiz88's changes in and the lerna bootstrap successfully bootstrapped all the packages which is good.

However, one further issue I'm having is getting the various make commands to work in Windows which seems to be mainly to do with how the paths and commands are resolved.  I think it would be possible to port the Makefile to package.json scripts to get everything working cross-platform (by which I mean also on Windows :)). I realise this can be controversial so thought I'd check whether it's likely to be accepted before trying it?

**Comment by motiz88** [comment]
So I actually do have Babel building fine on Windows right now (though there are occasional spurious test failures I haven't debugged). Admittedly my system has a usable `make` and Bash in the PATH, so that's probably it.

I'm personally all for migrating away from Makefiles - just want to represent more accurately that building on Windows _is_ possible, and that a minimum / short-term fix could come in the form of documentation.

**Comment by garyjN7** [comment]
Thanks for the quick reply :-)  I did get my makefile working too with a quick-and-dirty fix of placing the paths in quotes e.g. **./"node_modules/.bin/lerna" bootstrap** but it's not really an ideal solution...

**Comment by danez** [comment]
@garyjN7 There is also beta30 now of lerna. Does this fix the problem?

**Comment by garyjN7** [comment]
@danez Yes, lerna30 (and 29 I think I also tested it with) allows the lerna bootstrap command to run successfully.

**Comment by garyjN7** [comment]
#4752 I have submitted this pull request which moves the build and test functionality from the makefile to package.json scripts.

**Comment by hzoo** [comment]
https://github.com/babel/babel/pull/4843#issuecomment-326368862

Hopefully this works better with linux subsystem now?
