### ISSUE TITLE
Updating our CONTRIBUTING.md

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4590]
How can we update this? Should it be on the website instead?

https://github.com/babel/babel/blob/master/CONTRIBUTING.md

Can learn from
- atom: https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- bootstrap: https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md
- react: https://facebook.github.io/react/contributing/how-to-contribute.html

adding emojis: https://github.com/babel/babel/pull/4545#issuecomment-250159311

**Comment by stevemao** [comment]
I don't think this is beginner-friendly 😅  Probably needs someone who understands the code base, the scope and some legal issue in open source well? At least needs a lot of guidance when writing it.

**Comment by hzoo** [comment]
I guess I meant for this to be more of a discussion on what didn't make sense etc (not that a beginner would have to make the actual changes)

**Comment by kaicataldo** [comment]
I agree it's important to get feedback from beginner users - I wonder how we can raise the visibility of this? I think it's unlikely that many beginners are going to come across this issue on their own.

**Comment by love4shen** [comment]
I'm new to contributing to open source software. My education background include B.S. in Comp Sci in the States and ongoing M.S. in Applied Computing. I am a active user of React with babel under the hood but I merely touch babel related stuff except adding `"presets": ["es2015"]` to my config file. Today's my first day to read babel's codebase and `CONTRIBUTING.md`. Here's are some of my thoughts:

1. In "Not sure where to start?" section, I am confused by the term ** ESTree**. Why is it mentioned here? It says that babel's spec is different from it. Do I need to learn both specs? I think some extra notations may be better clarify the problems I got when I first read.
2. In "Developing" section, "note" part, some quick shell commands for checking building environment requirement may be helpful.
3. Not sure whether experienced guys have the same feeling. I think add some expect running time for build process and test process may be helpful for beginners (well, at least me). I feel somewhat bored when I see the sentenses like `[xx:xx:xx] Compiling 'xxxxxxx'` or dots filling my screen and have no idea whether it will ends in 30 seconds or  5 minutes.

Hope these may be helpful :)

**Comment by hzoo** [comment]
I made some updates in https://github.com/babel/babel/commit/4b3aaae9c001c423a0a0cee438b86b370c06657f. Thanks for the feedback, we'll be updating this a lot more!
