### ISSUE TITLE
Babel-CLI 6.16.0 error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by kellyselden** [babel/babel#4595]
I just did an `npm update` to update everything. Then my express app wouldn't start with the error

```
$ babel-node server.js
/xxxxxxx/node_modules/babel-polyfill/lib/index.js:12
  throw new Error("only one instance of babel-polyfill is allowed");
  ^

Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/xxxxxxx/node_modules/babel-polyfill/lib/index.js:12:9)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/xxxxxxx/node_modules/babel-cli/node_modules/babel-register/lib/node.js:151:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/xxxxxxx/lib/server.js:12:1)
    at Module._compile (module.js:409:26)
```

Reverting to `"babel-cli": "~6.14.0",` fixed it.

### Babel Configuration (.bablerc, package.json, cli command)

`babel-node server.js`

```js
{
  "presets": ["es2015", "stage-2"],
  "plugins": []
}
```

relevant packages:

  "dependencies": {
    "babel-polyfill": "^6.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.0.0",
    "babel-eslint": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.0.0"
  }

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  most recent everything, just ran npm update
| node             | 4.4.7
| npm              | 2.15.8
| Operating System | osx 10.11.6

**Comment by danez** [comment]
`npm update` does not update all your dependencies, but just the ones that you specify in your package.json, afaik.
Could you try removing your node_modules folder and doing `npm install` again ?

**Comment by gztchan** [comment]
+1

**Comment by ianmk2** [comment]
+1

**Comment by gglee89** [comment]
+1

**Comment by Shane0531** [comment]
+1

**Comment by danez** [comment]
Instead of +1 maybe someone could create a reproducable example. I cannot reproduce with he exact config in the issue. It might be a problem of npm failing to deduplicate correctly, so running ` npm dedupe` might help.

**Comment by kellyselden** [comment]
With the babel-register 6.16.3 update that just went out, I can no longer reproduce.
