### ISSUE TITLE
No compatible version found: babel-types@^6.16.0

### ISSUE THREAD

**Issue by priyajeet** [babel/babel#4598]
Npm registry not showing version 6.16.0 for various babel packages...

https://www.npmjs.com/package/babel-types shows version 6.15.0
https://www.npmjs.com/package/babel-core shows version 6.14.0

https://www.npmjs.com/package/babel-preset-es2015 shows version 6.16.0
...

npm view babel-types dist-tags gives 6.15.0

**Comment by hzoo** [comment]
If you are on a cache or not using public npm it will be out of date - https://unpkg.com/babel-types@6.16.0/ it definitely should be there.

**Comment by stalniy** [comment]
Why then https://www.npmjs.com/package/babel-types shows the latest version as 6.15?

**Comment by danez** [comment]
The npmjs.com site has a fullpage cache that caches the pages for several days. So it will need some days till the correct version number shows up there.
