### ISSUE TITLE
Regression with async arrow functions

### ISSUE THREAD

**Issue by Kovensky** [babel/babel#4599]
Affects `babel-plugin-transform-async-to-generator@6.16.0`, and clean installations of previous versions, even with exact version specification (!).

`async () => await promise` produces invalid code, while `async () => { return await promise }` produces the correct result.

Config: `{ "plugins": ["transform-async-to-generator"] }`

Input (real code, but can be further simplified):

```js
const unfollowUser = createAction(UNFOLLOW_USER,
  async (userId) => await api.unfollowAsync(userId),
  (userId) => ({userId})
)
```

Output:
```js
const unfollowUser = createAction(UNFOLLOW_USER, (() => {
  var _ref = _asyncToGenerator(function* (userId) {
    return await api.unfollowAsync(userId);
  });

  return function (_x) {
    return _ref.apply(this, arguments);
  };
})(), userId => ({ userId }));
```

Note the leftover `await` that was not converted to `yield`.

Changing to an explicit return (`async (userId) => { return await api.unfollowAsync(userId) }`) produces the same code, but with the appropriate `yield`.

PS: the `return function (_x) { return _ref.apply(this, ...` portion also _loses_ the `this` binding, resulting in `this` being `undefined`!

**Comment by Kovensky** [comment]
This also interacts with `transform-class-properties` in combination with `react-hot-loader/babel`, even when implicit returns are not used.

Input:
```js
class Foo { method = async () => { await bar } }
```

Output:
```js
class Foo {
  constructor() {
    var _this = this;

    this.method = (() => {
      var _ref = _asyncToGenerator(function* (...params) {
        return await _this.__method__REACT_HOT_LOADER__(...params);
      });

      return function NAME(_x) {
        return _ref.apply(this, arguments);
      };
    })();
  }

  __method__REACT_HOT_LOADER__() {
    return _asyncToGenerator(function* () {
      yield bar;
    })();
  }

}
```

**Comment by danez** [comment]
Ok I'm gonna look into this now and do a git bisect.

**Comment by danez** [comment]
This is fixed as with #4600 and we create a bugfix release later.

**Comment by KarolAdamiec** [comment]
later like when? is there a way to be notified about a release?

**Comment by danez** [comment]
As soon as someone wakes up who has publish rights. 😐

I use https://libraries.io/ to get notified about releases of packages which I'm interested in.
