### ISSUE TITLE
Jsdom fools sourcemaps generation to think its in a browser environment

### ISSUE THREAD

**Issue by trmjoa** [babel/babel#4605]
A fix was applied to the node-source-map-support module that allows you to specify the environment. We are using Jsdom + mocha + react + babel. 

The problem is that if `source-map-support` think you are in a web environment it tries to accommodate for that and resolve sourcemaps by calling `XMLHttpRequest`. This is very slow since the `XMLHttpRequest` (and all other web related methods) will be the ones defined by the `jsdom` module. When running tests with libraries like `sinon` this becomes a problem because they use code like `new Error().stack` ( to trace `spy` calls and `source-map-support` hooks the `prepareStackTrace` method).

The result is that when tests is executde in mocha(`mocha --ui tdd --compilers js:babel-core/register --recursive tests/`) they are extremely slow. 
 

### Input Code

```js
1st script
require("babel-register");
var jsdom = require("jsdom")

// setup the simplest document possible
var doc = jsdom.jsdom("<!doctype html><html><body></body></html>", {
  url : "http://localhost"
});

// get the window object out of the document
var win = doc.defaultView

// set globals for mocha that make access to document and window feel
// natural in the test environment
global.document = doc
global.window = win

propagateToGlobal(win);

function propagateToGlobal (window) {
  for (var key in window) {
    if (!window.hasOwnProperty(key)) continue;
    if (key in global) continue;
    global[key] = window[key]
  }
}

//Used by Sinon.js among others
const GetStack = () => new Error().stack;

const Generate10000Stacks = () => {
  const start = new Date().getTime();
  //MyClass.Test = Sinon.spy();
  for(var i = 0; i < 100; i++){
    GetStack();
  }
  console.log("Generation took: " + (new Date().getTime() - start) / 1000);
}
Generate10000Stacks();
```

```js
#2nd script
require("babel-register");

//Used by Sinon.js among others
const GetStack = () => new Error().stack;

const Generate10000Stacks = () => {
  const start = new Date().getTime();
  //MyClass.Test = Sinon.spy();
  for(var i = 0; i < 100; i++){
    GetStack();
  }
  console.log("Generation took: " + (new Date().getTime() - start) / 1000);
}
Generate10000Stacks();

```

### Babel Configuration (.bablerc, package.json, cli command)

```js
{
  "retainLines" : true,
  "sourceMaps" : ["inline"],
  "presets": ["es2015"]
}

```

```
//Output
babel-test$ node WithJsDom.js 
Generation took: 3.783
babel-test$ node WithoutJsDom.js 
Generation took: 0.03

```

### Possible Solution
The solution is to pass "environment" : "node" to the sourcemapsupport.install in order to prevent it from thinking its in a browser environment

**Comment by hzoo** [comment]
Wow crazy. 👍

**Comment by danez** [comment]
Awesome 🎉 This should fix #4592

**Comment by trmjoa** [comment]
I made a really simple PR. Don't now anything about potential consequences =/

**Comment by trmjoa** [comment]
Fix is merged. Closing
