### ISSUE TITLE
No compatible version found: babel-preset-stage-2@^6.16.0

### ISSUE THREAD

**Issue by shanewhittaker** [babel/babel#4610]
`npm install` does not run succesfully and fails with the error
`No compatible version found: babel-preset-stage-2@^6.16.0`

package.json contains "babel-preset-stage-0": "^6.5.0"

`npm view babel-preset-stage-2 dist-tags` yields `{ latest: '6.13.0' }`

**Comment by hzoo** [comment]
Check your cache? Same as https://github.com/babel/babel/issues/4609, https://github.com/babel/babel/issues/4598

```
npm view babel-preset-stage-2 dist-tags
{ latest: '6.16.0' }
```

**Comment by shanewhittaker** [comment]
Thanks! it looks like the npm repo was out of date
