### ISSUE TITLE
Parenthesize IIFE

### ISSUE THREAD

**Issue by amasad** [babel/babel#4615]
According to this it's up to 60% faster.
https://github.com/nolanlawson/optimize-js?utm_source=javascriptweekly&utm_medium=email

**Comment by cassiozen** [comment]
Modern compilers are too smart for that. This "performance gains" won't sustain in real world scenario.

https://twitter.com/getify/status/777945853659152384

**Comment by amasad** [comment]
@kangax wrote about impact in the real world https://github.com/rollup/rollup/pull/774#issuecomment-236283183

**Comment by nolanlawson** [comment]
You want to be judicious about where to apply the parentheses; see [my response to getify here](https://gist.github.com/nolanlawson/e73c61da78ffb39e4fc034a62ce8b263).

**Comment by hzoo** [comment]
We added a retainFunctionParens option in babel-generator https://github.com/babel/babel/pull/4621, I don't think we decided to add 

> !function (){}() becomes !(function (){})() as expected. I don't know if it's Babel's job to do anything else? Seems like something Babili should take care of — remove negation if function is already parenthesized (probably as one of the simplify plugins) and so on.

**Comment by nolanlawson** [comment]
That seems prudent @hzoo . For the record ChakraCore and (soon, I'm told per @bmeurer) V8 recognize `!function` as a hint for an IIFE and will optimize accordingly.

**Comment by bmeurer** [comment]
Yes, V8 recognizes `!function` as IIFE since [crrev.com/2509143003](https://codereview.chromium.org/2509143003), as described in the relevant tracking bug [crbug.com/v8/5643](https://bugs.chromium.org/p/v8/issues/detail?id=5643), so by now it hit Chrome stable, and there shouldn't be any need to wrap `!function` into parens (as far as V8 is concerned).
