### ISSUE TITLE
Destructuring fails with Array-like non-iterators

### ISSUE THREAD

**Issue by bfred-it** [babel/babel#4616]
Destructuring does not work for Array-like objects whereas it works correctly in ES6 browsers like Chrome 53.

### Input Code

```js
const [foo, bar] = document.body.children;
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
  "babel": {
    "presets": [
      "es2015" // loose mode works
    ]
  },
```

### Expected Behavior

Destructuring should work with Array-like objects like `NodeList`

### Current Behavior

`NodeList` is Array-like, but `!Array.isArray()` and in Safari 9 doesn't have `Symbol.iterator`, so `sliceIterator` inside `_slicedToArray` ends up throwing `new TypeError("Invalid attempt to destructure non-iterable instance");`

### Your Environment

* babel-core@6.14.0 through babelify@7.2.0
* babel-preset-es2015@6.6.0

**Comment by zloirock** [comment]
Destructuring should not work with non-iterable array-like objects. The loose mode has a special case for arrays. `NodeList` should be iterable. Maybe you should use `core-js` / `babel-polyfill` for iterable `NodeList`? :-)

**Comment by zloirock** [comment]
Hmm... Nope, it's another case. It's not a `NodeList`, it's an `HTMLCollection` and I don't see any documents why it should be iterable and why it should work - it looks like a non-standard behavior. If you have any docs why it should work - please, show me it and iterator will be added to `HTMLCollection` in  `core-js` / `babel-polyfill`.

**Comment by bfred-it** [comment]
It works in Chrome 53 and Firefox 48.

It doesn't work in Edge 14 but there `const [foo, bar] = document.querySelectorAll('*')` doesn't work either.

**Comment by zloirock** [comment]
> It works in Chrome 53 and Firefox 48.

I know it. See https://github.com/zloirock/core-js/issues/137#issuecomment-159531781 thread.

**Comment by zloirock** [comment]
> `document.querySelectorAll`

It's `NodeList` and [it should be iterable](https://www.w3.org/TR/2015/REC-dom-20151119/#old-style-collections:-nodelist-and-htmlcollection).

**Comment by bfred-it** [comment]
I wonder why it was removed, it was there at some point :( 
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23212

**Comment by loganfsmyth** [comment]
Interesting, I agreed with @zloirock until you posted that link. It seems like they removed it there because https://heycam.github.io/webidl/#es-iterators specifies that anything with a length and an integer index getter qualifies as iterable in the DOM IDL language.

**Comment by loganfsmyth** [comment]
@bfred-it I'm curious, are the following properties `function`s in Edge?

    NodeList.prototype[Symbol.iterator]
    HTMLCollection.prototype[Symbol.iterator]

**Comment by bfred-it** [comment]
![Nope](https://cloud.githubusercontent.com/assets/1402241/19018247/42a906de-880f-11e6-85eb-4da12e592def.png)

**Comment by loganfsmyth** [comment]
Alright, good to know.
