### ISSUE TITLE
weird edge case for arrow functions

### ISSUE THREAD

**Issue by asafigan** [babel/babel#4619]
I get this error even on the website for babel. (https://babeljs.io/repl/)

these pieces of code work:
`const works = ({async}) => {return true}`
`const alsoWorks = (async=true) => {return true}`
`const worksAsWell = ([async=true]) => {return true}`

but this code doesn't work:
`const fails = ({async=true}) => {return true}`

even though it works with a function:
`const workingFunction = function ({async=true}) {return true}`

and any other argument name works:
`const differentArgumentName = ({different=true}) => {return true}`

So it looks like the error is coming from using the name `async` with a default value on a deconstructed object in an arrow function's arguments.

Here is a link to an [example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=const%20works%20%3D%20(%7Basync%7D)%20%3D%3E%20%7Breturn%20true%7D%0Aconst%20alsoWorks%20%3D%20(async%3Dtrue)%20%3D%3E%20%7Breturn%20true%7D%0Aconst%20worksAsWell%20%3D%20(%5Basync%3Dtrue%5D)%20%3D%3E%20%7Breturn%20true%7D%0Aconst%20workingFunction%20%3D%20function%20(%7Basync%3Dtrue%7D)%20%7Breturn%20true%7D%0Aconst%20differentArgumentName%20%3D%20(%7Bdifferent%3Dtrue%7D)%20%3D%3E%20%7Breturn%20true%7D%0Aconst%20fails%20%3D%20(%7Basync%3Dtrue%7D)%20%3D%3E%20%7Breturn%20true%7D%0A)

**Comment by Nolski** [comment]
Isn't `async` a reserved keyword? I don't think this should be expected to work.

**Comment by asafigan** [comment]
but it works on all the snippets but one. If it shouldn't be used, than none of them should work not just one. Also you can declare variable with the name async.

**Comment by danez** [comment]
Async is not a reserved word it seems at least I can't see it in the spec, seems our parser is misbehaving here.
http://www.ecma-international.org/ecma-262/6.0/#sec-keywords

**Comment by danharper** [comment]
Closing in favour of this in Babylon: https://github.com/babel/babylon/issues/118.
