### ISSUE TITLE
transform-flow-comments regression with 6.16.x

### ISSUE THREAD

**Issue by dchambers** [babel/babel#4622]
After upgrading from Babel `6.14.0` to `6.16.3` (happens with `6.16.0` too) the 'babel-plugin-transform-flow-comments' plugin seems to have a small regression which causes classes with typed member variables, for example:

~~~es6
/* @flow */

class C {
  x: number
}

new C();
~~~

to error like so:

~~~bash
/home/dominicc/dev/C.js:6
  x /*: number*/;
                ^
SyntaxError: Unexpected token ;
~~~

**Comment by danharper** [comment]
Ah no, that was a "feature": https://github.com/babel/babel/pull/4587

I guess that doesn't work if you're _only_ stripping Flow types..

I'll prep a PR to revert it for Flow comments.

**Comment by dchambers** [comment]
Awesome, thanks so much @danharper!

**Comment by danharper** [comment]
Tbh, I'm not too sure how Flow types on class properties, with initial values, should transpile.

```js
class X {
  foo = 2
  bar: number = 3
  baz: ?string
}
```

Used to:

**Comment by dchambers** [comment]
Okay, so the problem goes away if ES7 property initializer support is added
using the 'babel-plugin-transform-class-properties' plugin. So your change
isn't wrong I guess, it just relies on ES7 property initializer support,
which you don't otherwise need if you're only using that construct for
adding typing information, as I was. I personally am happy to just enable
support for that plugin and close the issue with an explanation that helps
anybody else that runs into the same thing.

Does that sound like the right thing to do?

**Comment by danharper** [comment]
For `flow-strip-types`, Babel allows you to use type annotations on class properties without the syntax plugin, as it's valid Flow code. But only if you don't have an initializer.

So I'll replicate that behaviour.

**Comment by dchambers** [comment]
Sound good :+1:

**Comment by danharper** [comment]
Opened a PR here: #4623.
