### ISSUE TITLE
babel-plugin-transform-async-generator-functions uses babel-runtime@5

### ISSUE THREAD

**Issue by billyjanitsch** [babel/babel#4624]
### Expected Behavior

I'd expect `babel-plugin-transform-async-generator-functions`, like other modern Babel plugins, to use `babel-runtime@6`.

### Current Behavior

It uses `babel-runtime@5`.

### Context

It's not a big deal; it just means that npm has trouble deduping `babel-runtime` and `core-js`. Looks like it's leftover from the plugin being created before the migration to 6.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  ^6.16.0
| node             | 6.6.0
| npm              | 3.10.8
| Operating System | OSX 10.12

**Comment by hzoo** [comment]
Oh thats really weird - definetely should be fixed - do you want to PR it now (or i'l do it real quick)

**Comment by hzoo** [comment]
We need a package.json validator 😛

**Comment by billyjanitsch** [comment]
I'm happy to PR if the only change is bumping the dependency but I'm not sure if there are incompatibilities that I should know about.

**Comment by hzoo** [comment]
I just didn't catch it during the PR since like you said it was before the switch - I went ahead and did it https://github.com/babel/babel/pull/4626/ oops

**Comment by billyjanitsch** [comment]
Great, thanks for the quick fix. :)
