### ISSUE TITLE
Spread is not calling iterators 

### ISSUE THREAD

**Issue by jacktuck** [babel/babel#4625]
It looks like when compiling with the es2015 presets spread ops do not call its iterator.

```
var col = [1,2,3]

col[Symbol.iterator] = function* () {
    var i = 0;
    while(this[i] !== undefined) {
      yield ++this[i];
      ++i;
    }
  };

console.log([...col])
```

`console.log([...col])` compiles to `console.log([].concat(col))` which does not call iterators.

_See in [babel REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=import%20%7B%20renderToString%20%7D%20from%20'react-dom%2Fserver'%0Aimport%20%7B%20match%2C%20RoutingContext%20%7D%20from%20'react-router'%0Aimport%20routes%20from%20'.%2Froutes'%0A%0Avar%20col%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0Acol%5BSymbol.iterator%5D%20%3D%20function*%20%28%29%20%7B%0A%20%20%20%20var%20i%20%3D%200%3B%0A%20%20%20%20while%28this%5Bi%5D%20!%3D%3D%20undefined%29%20%7B%0A%20%20%20%20%20%20yield%20%2B%2Bthis%5Bi%5D%3B%0A%20%20%20%20%20%20%2B%2Bi%3B%0A%20%20%20%20%7D%0A%20%20%7D%3B%0A%0A%0Aconsole.log%28%5B...col%5D%29%0A)_

```
Jacks-MacBook-Pro-2:Jack$ node index.js
[ 2, 3, 4 ]
Jacks-MacBook-Pro-2:Jack$ babel-node index.js
[ 2, 3, 4 ]
Jacks-MacBook-Pro-2:Jack$ babel-node --presets es2015 index.js
[ 1, 2, 3 ]
```

Not sure how to approach a fix for this, but I'd happily make a PR if someone could point me in the right direction!

**Comment by jacktuck** [comment]
#2160

**Comment by zloirock** [comment]
Also, here is one more bug - looks like a wrong optimisation - `babel` knows that it's an array and does not use `toConsumableArray`.

**Comment by jacktuck** [comment]
@zloirock Seems to be fixed if i use es2016 or es2016.
