### ISSUE TITLE
useBuiltIns option for react-jsx

### ISSUE THREAD

**Issue by klimashkin** [babel/babel#4627]
Property spread in jsx tags doesn't support `useBuiltIns` option as `transform-object-rest-spread` does.
Would be great to have it in jsx too, to eliminate `babel-runtime/helpers/extends` from result bundle completely.

**Comment by hzoo** [comment]
It's done in https://github.com/babel/babel/blob/master/packages/babel-helper-builder-react-jsx/src/index.js#L159

**Comment by danez** [comment]
Fixed by #4655

**Comment by hzoo** [comment]
http://babeljs.io/blog/2016/10/24/6.18.0
