### ISSUE TITLE
Only run eslint on latest node in CI

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4638]
We want to use the latest version of eslint but it dropped node < 4 already.

One solution is to only run eslint on node 6? (and not on circleci either which only runs node 0.10)

I'm not sure if you just change the https://github.com/babel/babel/blob/master/.travis.yml?

**Comment by ljharb** [comment]
https://github.com/ljharb/is-callable/blob/master/.travis.yml as an exemplar
