### ISSUE TITLE
babel-traverse throws on import and variable collisions

### ISSUE THREAD

**Issue by AsaAyers** [babel/babel#4640]
### Input Code

In a new folder run `npm install babel-core babylon`, then put the following code in `traverse-error.js`

``` js
var code = `
import foo from './foo'
const foo = undefined
`

var babelCore = require('babel-core')
var babylon = require('babylon')

var ast = {
    type: 'File',
    start: 0,
    end: code.length,
    program: babylon.parse(code, {
        sourceType: 'module'
    })
}

babelCore.traverse(ast, {})
```
### Expected Behavior

`node traverse-error.js` should run with no output. If you simply rename the `import foo` or `const foo` to avoid the collision, it will run as expected.
### Current Behavior

```
asa@asa:/tmp/babel-issue$ node traverse-error.js 
/tmp/babel-issue/node_modules/babel-traverse/lib/scope/index.js:397
      throw this.hub.file.buildCodeFrameError(id, messages.get("scopeDuplicateDeclaration", name), TypeError);
                    ^

TypeError: Cannot read property 'file' of undefined
    at Scope.checkBlockScopedCollisions (/tmp/babel-issue/node_modules/babel-traverse/lib/scope/index.js:397:21)
    at Scope.registerBinding (/tmp/babel-issue/node_modules/babel-traverse/lib/scope/index.js:579:16)
    at Scope.registerDeclaration (/tmp/babel-issue/node_modules/babel-traverse/lib/scope/index.js:483:14)
    at Object.BlockScoped (/tmp/babel-issue/node_modules/babel-traverse/lib/scope/index.js:185:28)
    at Object.newFn (/tmp/babel-issue/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/tmp/babel-issue/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/tmp/babel-issue/node_modules/babel-traverse/lib/path/context.js:44:14)
    at NodePath.visit (/tmp/babel-issue/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/tmp/babel-issue/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/tmp/babel-issue/node_modules/babel-traverse/lib/context.js:103:17)
```
### Context

I have an Atom plugin called [js-hyperclick](https://atom.io/packages/js-hyperclick). It parses your JS files and allows you to ctrl+click filenames or variables to jump to their definitions. Today I've been working on getting `js-hyperclick` to inform the user when it can't function. If you have a syntax error that causes `babylon.parse` to throw I can help the user:

![selection_019](https://cloud.githubusercontent.com/assets/324999/19017137/c1863948-87e4-11e6-8fca-4cccdbecc5f1.png)

Because this error happens when traversing and the error points to `babel-traverse` code, showing the user doesn't help them:

![selection_020](https://cloud.githubusercontent.com/assets/324999/19017179/8ae985ba-87e5-11e6-9cd4-6d852dc01d2f.png)

I tend to run into this when I'm trying to extract `foo` into its own file. I'll add `import foo from './new-file'`, then if this were able to parse I could ctrl+click the `./new-file` or `foo` to open a new editor at that path and cut/paste whatever `foo` needs.
### Your Environment

| software | version |
| --- | --- |
| Babel | 5.8.25 and 6.17.0 |
| node | 4 and 6 |

I wouldn't expect it to get fixed back in Babel5, but the code above also demonstrates the error with `npm install babel-core@5` and replace `babylon.parse` with `babelCore.parse`

**Comment by danez** [comment]
When I try this in the repl I get a proper parsing error now. Which version of babylon are you using? The latest version has duplicate checks.
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&experimental=true&loose=false&spec=false&code=import%20foo%20from%20'.%2Ffoo'%0Aconst%20foo%20%3D%20undefined%3B&playground=false

**Comment by AsaAyers** [comment]
This is what I got with `npm install babel-core@6 babylon@6`

```
asa@asa:/tmp/babel-issue$ npm ls babel-core babylon
/tmp/babel-issue
├── babel-core@6.17.0 
└── babylon@6.11.3 
```

**Comment by AsaAyers** [comment]
It seems like the line that's throwing is the one that would throw the duplicate declaration error. But it can't because `this.hub` is `undefined`.

I'm not seeing `File` on https://github.com/babel/babylon#output or the [Babel AST format](https://github.com/babel/babylon/blob/master/ast/spec.md). I removed the wrapper, it seems like I needed it for Babel 5 but not Babel 6.

Here is a simplified version that still errors on babel-core@6.17.0 and babylon@6.11.3 

```js
var code = `
import foo from './foo'
const foo = undefined
`

var babelCore = require('babel-core')
var babylon = require('babylon')

var ast = babylon.parse(code, {
    sourceType: 'module'
})

const tmp = babelCore.traverse(ast, {})
```

**Comment by danez** [comment]
I'm not entirely sure what'S wrong, but It might be worth looking at this location where babel itself is using traverse. Maybe you also have to create a scope, though it should be optional, but might be worth a try to workaround for now.

https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/index.js#L450...L478

**Comment by AsaAyers** [comment]
Thanks! I think I can make a workaround out of this.

```js
var code = `
import foo from './foo'
const foo = undefined
`

var NodePath = require('babel-traverse').NodePath
var Hub = require('babel-traverse').Hub
var babelCore = require('babel-core')
var babylon = require('babylon')

var hub = new Hub({
    buildCodeFrameError(node, message, Error) {
        var loc = node && (node.loc || node._loc);

        var err = new Error(message)

        if (loc) {
            err.loc = loc.start
        }

        return err
    }

})

var ast = babylon.parse(code, {
    sourceType: 'module'
})

var path = NodePath.get({
    hub: hub,
    parentPath: null,
    parent: ast,
    container: ast,
    key: "program"
}).setContext();
var scope = this.path.scope;

const tmp = babelCore.traverse(ast, {}, scope)
```

At this point it throws `TypeError: Duplicate declaration "foo"`. I was hoping to avoid a `try/catch` around the `traverse` call, because it's going to mix this `Duplicate declaration` error in with bugs in my visitor code.

I also don't know what other `hub` functions/properties I need to implement. Looking at the [search results for `hub.file`](https://github.com/babel/babel/search?utf8=%E2%9C%93&q=hub.file&type=Code)  without knowing the context, I might need:

* [`this.hub.file.metadata.marked.push(`](https://github.com/babel/babel/blob/dc1f40540de11045bb4714350350e012fee4f93e/packages/babel-traverse/src/path/index.js#L127)
* [`path.hub.file.scope.push(`](https://github.com/babel/babel/blob/8fa1174b32ec6bb31d32843334c921d0e97da663/packages/babel-plugin-transform-react-jsx-source/src/index.js#L53)
* [`this.hub.file.code.slice(`](https://github.com/babel/babel/blob/dc1f40540de11045bb4714350350e012fee4f93e/packages/babel-traverse/src/path/introspection.js#L238)

**Comment by jquense** [comment]
could we open this back up since the fixing PR was reverted?

**Comment by hzoo** [comment]
It looks like we can resubmit a similar pr to 7.x and it would be ok since it ended up being a dep issue?

**Comment by jquense** [comment]
That is my understanding :) I think the PR was good, it jsut constitueted a breaking change, so now is a good time to get it back in

**Comment by SkeLLLa** [comment]
Issue not fixed.
