### ISSUE TITLE
Question: Which `parentPath` should be passed into `babel-traversal` `traverse` function?

### ISSUE THREAD

**Issue by sompylasar** [babel/babel#4643]
Please sorry in advance for not following the outline of the issue description. I am investigating an issue in Atom `js-hyperclick` package, so this is a question for clarification.

Here is the issue: https://github.com/AsaAyers/js-hyperclick/issues/39

I've followed the program control flows and data flows, and found that the exception is caused by [an assumption that `Scope` has a non-empty `hub` property](https://github.com/babel/babel/blob/477a72a975fb1a37ec0b99b78d35b64459a938ff/packages/babel-traverse/src/scope/index.js#L351) [which comes via `NodePath`](https://github.com/babel/babel/blob/477a72a975fb1a37ec0b99b78d35b64459a938ff/packages/babel-traverse/src/scope/index.js#L159) [from the `TraversalContext`](https://github.com/babel/babel/blob/477a72a975fb1a37ec0b99b78d35b64459a938ff/packages/babel-traverse/src/context.js#L46).

But the root `TraversalContext` which is [created in the `traverse.node` function](https://github.com/babel/babel/blob/477a72a975fb1a37ec0b99b78d35b64459a938ff/packages/babel-traverse/src/index.js#L52) [accepts the `parentPath` from the outside](https://github.com/babel/babel/blob/477a72a975fb1a37ec0b99b78d35b64459a938ff/packages/babel-traverse/src/index.js#L48), consequently [from the `traverse` function arguments](https://github.com/babel/babel/blob/477a72a975fb1a37ec0b99b78d35b64459a938ff/packages/babel-traverse/src/index.js#L20).

[The documentation does not mention `parentPath`](https://github.com/thejameskyle/babel-handbook/blob/6f9509edaf1487a2b37e17caf2bb120c4ea5fceb/translations/en/plugin-handbook.md#toc-babel-traverse) to be an argument of `traverse`.

So, my questions are:
* Is this a `babel` bug or an invalid [usage of `traverse` in `js-hyperclick`](https://github.com/AsaAyers/js-hyperclick/blob/ba149e1b90e73484865a07071a0d16653a8a3bac/lib/make-cache.js#L71-L174)?
* How should `traverse` be used to make the `hub` property populated?
* Which `parentPath`, if any, should be passed into `babel-traversal` `traverse` function?

**Comment by danez** [comment]
refs #4640

**Comment by sompylasar** [comment]
@danez Wow absolutely missed that, thanks!

**Comment by hzoo** [comment]
Ok closing this one, we'll figure it out in the other one
