### ISSUE TITLE
Move transform-object-rest-spread to stage 3 preset?

### ISSUE THREAD

**Issue by olalonde** [babel/babel#4645]
https://github.com/tc39/proposals lists Rest/Spread properties as stage-3 but it is part of the [preset-stage-2](https://babeljs.io/docs/plugins/preset-stage-2/) instead of [preset-stage-3](https://babeljs.io/docs/plugins/preset-stage-3/).

**Comment by zloirock** [comment]
[It's already in stage-3 preset.](https://github.com/babel/babel/commit/efa0affea193a6ad4d9035a4292cff0d78b97376)

**Comment by olalonde** [comment]
Ah ok, guess the docs need updating then, still listed here https://babeljs.io/docs/plugins/preset-stage-2/

**Comment by zloirock** [comment]
Yep.

**Comment by zloirock** [comment]
Please, open an issue or a PR  [here](https://github.com/babel/babel.github.io), it's incorrect repo.
