### ISSUE TITLE
[Feature request] Add node 6 --inspect support to `babel-node`

### ISSUE THREAD

**Issue by bySabi** [babel/babel#4658]
Recently added v8_inspect support on node 6.x branch: https://github.com/nodejs/node/pull/6792 
is a huge improvement on debugger land and we need to take into consideration that projects like `node-inspect` probably will deprecated in favor of this.

**Comment by danez** [comment]
This is already available since version 6.11.4

**Comment by mwalkerwells** [comment]
What is the best way to debug breakpoints not working (latest node & babel version) & what information is essential for a bug report?

**Comment by loganfsmyth** [comment]
An installable github repo and steps to reproduce in a new issue please.
