### ISSUE TITLE
Error in IE11 when we extend HTMLElement

### ISSUE THREAD

**Issue by 4leem** [babel/babel#4659]
We are using babel-core (v6.14.0), babel-loader(v6.2.4) for webpack, babel-polyfill(v6.5.0) for our React based project.

I get error in IE 11 -

> Exception thrown and not caught

Sample code:

```
class SuperBtn extends HTMLElement {
    constructor() {
        super();
    }
    createdCallback() {
        this.innerHTML = "Invoke Ultron!";
        this.addEventListener('click', () => alert(this.textContent + ' has been clicked'));
    }
}
```

The `HTMLElement` is returned as object while the `_inherits()` method expects a function.

The Babel Documentation states,

> Built-in subclassability should be evaluated on a case-by-case basis as classes such as HTMLElement can be subclassed while many such as Date, Array and Error cannot be due to ES5 engine limitations.

..but it doesn't seem to work for us, is there something missing or work around?

**Comment by hzoo** [comment]
Sounds like https://github.com/babel/babel/issues/4480
