### ISSUE TITLE
Support auto-displayName on more types of react components

### ISSUE THREAD

**Issue by roncohen** [babel/babel#4663]
I'm opening this to gauge interest and immediate thoughts from you on whether it would be interesting to have https://github.com/opbeat/babel-plugin-add-react-displayname merged into the existing babel plugin `babel-plugin-transform-react-display-name`.

`babel-plugin-add-react-displayname` will automatically detect and set `displayName` for React components that are not using the `React.createClass` style. This is useful for having real component names show up in production builds of React apps.

This adds support for the two other kinds of component definitions not already covered by the existing displayName plugin:
- ES6-classes style components
- Stateless components that return JSX

In our testing, _a lot_ of code is being written with these two styles. This will not cover everything.  However, using the existing plugin that alters `React.createClass` along with this plugin covers a large majority of components we found in the wild.

The [tests](https://github.com/opbeat/babel-plugin-add-react-displayname/tree/master/test/fixtures) show more details about what is supported and what is not. 

Specifically, see https://github.com/opbeat/babel-plugin-add-react-displayname/blob/master/test/fixtures/passThrough/expected.js for examples that are left untouched by the plugin.

The code is here: https://github.com/opbeat/babel-plugin-add-react-displayname/blob/master/index.js

If you agree this is desirable and think it's viable approach, I'll work on merging them and aligning the tests to the existing style and submit a PR.

**Comment by roncohen** [comment]
A bit too early for this. I'll follow up later.

**Comment by danez** [comment]
I would be totally up for merging it into the babel plugin. But we have to make sure that we don't break code that already uses it. So we would need to add option(s) to enable disable the new behaviour and only enable the current behaviour by default.

Though I'm not sure what the others think?

**Comment by hzoo** [comment]
Supporting the other two kinds of component definitions sounds useful? cc @gaearon @spicyj

**Comment by roncohen** [comment]
Good to hear.
I closed this because I heard from a tester that there was a bug. Looking into it now.

**Comment by roncohen** [comment]
@danez What would really help me push this forward would be if i could get more people to run this over their code to help me find edge cases. The more the merrier. 
Please submit bugs over at: https://github.com/opbeat/babel-plugin-add-react-displayname/issues

Much appreciated! ✨

**Comment by hzoo** [comment]
Going to close, if we think this is good then we can accept as a PR
