### ISSUE TITLE
Return type is lost in transform-classes

### ISSUE THREAD

**Issue by arv** [babel/babel#4665]
### Input Code

```js
// @flow
class C {
  m(x: number): string {
    return 'a';
  }
}
```

## Output Code

```js
...
// @flow

var C = function () {
  function C() {
    (0, _classCallCheck3.default)(this, C);
  }

  (0, _createClass3.default)(C, [{
    key: 'm',
    value: function m(x: number) {  // <---
      return 'a';
    }
  }]);
  return C;
}();
```

### Expected Behavior

I expect the return type to be kept on the function expression.

### Current Behavior

Type annotation is removed.

| software         | version
| ---------------- | -------
| Babel            |  6.14.0 (babel-core 6.14.0)
| node             | v6.6.0
| npm              | 3.9.2
| Operating System | OS X

**Comment by hzoo** [comment]
Hmm we need to check if its just not printing it out (babel-generator) or the transform is dropping it for some reason (transform-class)

**Comment by arv** [comment]
I found it when trying out transform-flow-comments so I'm pretty sure it is not just the printer.

**Comment by hzoo** [comment]
Oh this is with flow-comments only? There are some issues with it because of the transforms - there was an old issue https://github.com/babel-plugins/babel-plugin-flow-comments/issues/17 and pr (https://github.com/babel-plugins/babel-plugin-flow-comments/pull/18) about this.

What about https://babeljs.io/docs/plugins/transform-flow-strip-types/?

**Comment by hzoo** [comment]
awesome @danharper made a fix https://github.com/babel/babel/issues/4668

**Comment by arv** [comment]
@hzoo No, this is not related to `transform-flow-comments`.

`transform-flow-strip-types` removes the types so that is not related. I want to keep the types.
