### ISSUE TITLE
Moving babel-doctor to a separate package/removing

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4678]
Ref https://github.com/babel/babel/pull/4661

https://github.com/babel/babel/tree/master/packages/babel-cli/src/babel-doctor

Or we just remove it since I don't think we'll be updating it anytime soon?

It's currently part of `babel-cli` and was released after 6.0 (http://babeljs.io/blog/2015/11/03/babel-doctor) due to a lot of people having issues upgrading from v5 to v6. I'm pretty sure it's not used and isn't a one-time use thing anyway.

We can remove a lot of dependencies from babel-cli if we do so as well to make it a bit smaller/faster to install.
https://github.com/babel/babel/commit/5ee8f7568bd626a28614e160b1881c5d1f1cbe85
https://github.com/babel/babel/commit/1c3b4aa41088a9167646143f5116a02af0b8d409

**Comment by kaicataldo** [comment]
Any way to get metrics on how many people are using this? Twitter poll? 

And I'm assuming you'd want it to be moved to another repo in the babel org? Just curious since it has the `help wanted` label, and moving it seems like something that would need to be done by someone in the org.

**Comment by hzoo** [comment]
We can but its not really necessary - most people don't even know what it is (and the people that do probably already used it and fixed their problem).

It's mostly just deleting the associated code and maybe throwing in the bin to say it's gone and maybe we can just replace it. (It can also be in this repo).

**Comment by kaicataldo** [comment]
Cool, thanks for clarifying :+1:
