### ISSUE TITLE
Problem fork with babel-node

### ISSUE THREAD

**Issue by maxcnunes** [babel/babel#4679]
### Input Code

https://github.com/maxcnunes/problem-fork-with-babel-node
### Babel Configuration

``` js
"babel": {
  "presets": ["stage-3"]
}
```
### Expected Behavior

Running a fork script with `execPath = 'babel-node'` should work the same way it works running `babel-node` in the main script.
### Current Behavior

The script does not work. Don't even show an error message.
### Possible Solution

Sorry. No idea.
### Context

I have a project that depend on some features not available in the latest Node js yet such as `async await`. In this project I work with fork process and the scripts executed by these forks also use `async await`. Running the project with `babel-node` it works pretty will. The `babel-node` automatically handle the compile for the fork scripts without need to set anything different during the fork such as `execPath = 'babel-node'`.
But running the tests with mocha I don't use `babel-node` to start the main script since mocha does that. Using the the flag `--compilers js:babel-register` on mocha it handle the compile of the main script. But it does not handle the compile of the fork scripts. Here is when I tried to set `execPath = 'babel-node'` to the fork scripts and find out it does not work. Even without running through the mocha.
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.16 |
| node | 6.5.0 |
| npm | 3.10.3 |
| Operating System | Ubuntu 16.04 |

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
