### ISSUE TITLE
Constructors default parameters break member functions

### ISSUE THREAD

**Issue by arcanis** [babel/babel#4687]
[Original code](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=true&loose=false&spec=true&code=import%20%7B%20opts%20%7D%20from%20'opts'%3B%0A%0Aclass%20Foo%20%7B%0A%20%20constructor%28opts%20%3D%20%7B%7D%29%20%7B%0A%20%20%7D%0A%20%20foobar%28%29%20%7B%0A%20%20%20%20return%20opts%28%29%3B%0A%20%20%7D%0A%7D):

``` js
import { opts } from 'opts';

class Foo {
  constructor(opts = {}) {
  }
  foobar() {
    return opts();
  }
}
```

When I call the `Foo#foobar()` method, I expect it to call the `opts` function exported by the `opts` module. Unfortunately, it instead throw an error saying that "opts is not defined". The problem disappear if we remove the `opts` default value from the constructor.

**Comment by hzoo** [comment]
yeah hm the import is renamed but the `opts()` call isn't

```js
var _opts = require('opts'); // renamed
var Foo = function () {
  function Foo() {
    var opts = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  }
  _createClass(Foo, [{
    key: 'foobar',
    value: function foobar() {
      return opts(); // not renamed
    }
  }]);
  return Foo;
}();
```

**Comment by typeetfunc** [comment]
@arcanis Its very very old bug :) First issue - https://github.com/babel/babel/issues/4209
Possible cause: https://github.com/babel/babel/pull/3495

**Comment by nicolo-ribaudo** [comment]
This works in Babel 7.0.0-beta.37 :tada: 

https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAbzhMMDOcC-cBmUIhwDkK6RA3AFCUDGANgIZoYBiEEilccNEAdmhhQArjRjQAFKQwBeRJgCUnbpi652AIwZQJShGu5QApjGFQ-yVGl1UVlTEA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-beta.37

```js
"use strict";

var _opts = require("opts");

function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return right[Symbol.hasInstance](left); } else { return left instanceof right; } }

function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

var Foo =
/*#__PURE__*/
function () {
  function Foo() {
    var opts = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: "foobar",
    value: function foobar() {
      return (0, _opts.opts)();
    }
  }]);

  return Foo;
}();
```
