### ISSUE TITLE
Stop supporting `babel-register`

### ISSUE THREAD

**Issue by lastmjs** [babel/babel#4689]
I suggest stopping promotion and support of `babel-register`, at least on Node.js. Looking at the source code, it seems like the transpiliation functionality is being attached through `require.extensions`, which according to [this](https://nodejs.org/api/globals.html#globals_require_extensions) is deprecated.

**Comment by hzoo** [comment]
A lot of folks are using babel-register (usually the questions are about using babel-register in production actually, which we warn against). 

We don't have to use `require.extensions` - we can just rewrite it using something else instead of entirely removing it.

**Comment by lastmjs** [comment]
Okay, I see

**Comment by motiz88** [comment]
There's also this comment from the same Node docs:

> Since the Module system is locked, this feature will probably never go away. However, it may have subtle bugs and complexities that are best left untouched.

**Comment by hzoo** [comment]
Going to close then
