### ISSUE TITLE
asyncToGenerator not preserving 'this' in async function

### ISSUE THREAD

**Issue by danielarias123** [babel/babel#4696]
While trying to use `this.setState()` in an async function, I get the following error `bundle.js:94381 Uncaught (in promise) ReferenceError: _this6 is not defined`.

It seems the runtime is overwriting 'this'.

### My function (in a React component):
```js
getOrder = async orderId => {
    this.setState({
       loading: true
    });
    const response = await OrderAPI.getOrder(orderId);
    if (response) {
      this.setState({
        loading: false,
        order: response
      });
    }
  }
```

### Output bundle.js
```js
...
 key: '__getOrder__REACT_HOT_LOADER__',
    value: function () {
      var _ref4 = _asyncToGenerator(regeneratorRuntime.mark(function _callee4(orderId) {

        return regeneratorRuntime.wrap(function _callee4$(_context4) {
          while (1) {
            switch (_context4.prev = _context4.next) {
              case 0:
                _this6.setState({
                  loading: true
                });

                return _context4.abrupt('return');

              case 'end':
                return _context4.stop();
            }
          }
        }, _callee4, this);

...
```

### Babel Configuration

I am importing `babel-polyfill` in my app entry file

.babelrc
```js
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": [
    "react-hot-loader/babel",
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

My webpack entry:

```js
entry: [ 'react-hot-loader/patch', 'hot-middleware/client', './src/client/js/app.js'],
```
If I remove the async await from the function, the bundles compile properly, making me think it might be an issue with `_asyncToGenerator`.

Any Ideas?
Thanks in advance.

**Comment by danharper** [comment]
Does it work if you disable `react-hot-loader`? Looks like #4550.

**Comment by danielarias123** [comment]
@danharper Thanks! Yea you are right, when I disable `react-hot-loader` it works as expected. Will create an issue there in favour of here.
