### ISSUE TITLE
Make babel-preset-react take an option for dev plugins

### ISSUE THREAD

**Issue by MoOx** [babel/babel#4702]
[Per this comment](https://github.com/babel/babel/pull/3540#issuecomment-228673661) I understand that it does not make sense to add `babel-plugin-transform-react-jsx-source` and `babel-plugin-transform-react-jsx-self` to `babel-preset-react`.

What about creating a `babel-preset-react-dev` that basically inherit `babel-preset-react` and includes some others (dev) plugins?

Since it will be really explicit (**-dev**) I think it can't cause any trouble.

Also, this will [this kind of code](https://github.com/facebookincubator/create-react-app/blob/c6428eaff91fd8dc71e20e9a3f6f38106f08ab7c/packages/babel-preset-react-app/index.js#L56-L63) more explicit imo.

cc @spicyj @sebmarkbage @jimfb @gaearon

If you are open too, I can handle a PR.

**Comment by zoontek** [comment]
Great idea 👍 
I like the idea of a babel preset option too:

```json
{
  "presets": [
    ["react", {
      "debug: true
    }]
  ]
}
```

**Comment by hzoo** [comment]
Because we have options now, we don't need a separate preset. A `development` option would work fine

**Comment by gaearon** [comment]
Can we just use `NODE_ENV` for this in the next Babel major?

**Comment by spicyj** [comment]
I don't think it makes sense to use NODE_ENV for this. NODE_ENV indicates what environment the *current* program should run in – that is, it should indicate whether webpack/browserify/babel itself should run in production mode or in development mode with extra logging and checks.

BABEL_ENV or something else separate seems better.

**Comment by hzoo** [comment]
I think @zoontek's suggestion is good - dono about the name (`dev`/`development` could work too)

**Comment by gaearon** [comment]
>BABEL_ENV or something else separate seems better.

My point was that Babel already has a mechanism for activating environment-specific behavior via `env` key. Whether it is wise for `env` to reflect `NODE_ENV` in addition to `BABEL_ENV` is a question for Babel. But it seems weird to have multiple plugins for a dev switch when Babel already supports this behavior out of the box. If the way switch is activated in Babel is counter-intuitive, maybe it's Babel's behavior that needs to be changed, e.g. to only honor `BABEL_ENV`.

**Comment by spicyj** [comment]
I'd support that.
