### ISSUE TITLE
Decorators support

### ISSUE THREAD

**Issue by markwain** [babel/babel#4704]
Hello. It seems that a new decorator proposal is already on stage 2. And I am just curious when can we expect the support of decorators in babel?

**Comment by hzoo** [comment]
Hey there's an existing issue for this https://github.com/babel/babel/issues/2645

**Comment by markwain** [comment]
Yeah, but it is locked(

**Comment by hzoo** [comment]
Oh ok I didn't see that. The issue is open though and we know about it. If we have progress we will update the issue (and you can ask in slack it's not necessary to make an issue for it)
