### ISSUE TITLE
Async iterator methods don't work in babel-preset-stage-3

### ISSUE THREAD

**Issue by Jamesernator** [babel/babel#4705]
### Input Code
Simple example using a minimal class
```js
"use strict"
class Foo {
    constructor(bar) {
        // Add an arbitrary this value
        this.bar = bar
    }

    async *values() {
        // Yield some arbitrary values
        yield this.bar
        yield 1
        yield 2
        yield 3
    }
}

async function main() {
    const foo = new Foo(10)
    for await (const x of foo.values()) {
        console.log(x)
    }
}

main() // Prints nothing should print 10, 1, 2, 3
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
{
    "presets": [
        "stage-3"
    ]
}
```

### Expected Behavior

The expected behaviour is that it should iterate over the values, it behaves correctly with:
```js
function Foo(bar) {
    this.bar = bar
}

Foo.prototype.values = async function*() {
    // Yield some arbitrary values
    yield this.bar
    yield 1
    yield 2
    yield 3
}

async function main() {
    const foo = new Foo(10)
    for await (const x of foo.values()) {
        console.log(x)
    }
}

main()

```

### Possible Solution
I took a look and found using this test case here that the *actual iterator* that we want is wrapped in a generator for some reason e.g.:

```js
class Foo {
    constructor(bar) {
        // Add an arbitrary this value
        this.bar = bar
    }

    async *values() {
        // Yield some arbitrary values
        yield this.bar
        yield 1
        yield 2
        yield 3
    }
}

async function main() {
    const foo = new Foo(10)
    const values = foo.values().next().value // This is the real async iterator we want
    for await (const x of values) {
        console.log(x)
    }
}

main() // Now it correctly prints 10, 1, 2, 3
```

My guess as to the cause is that `async *values() {...}` becomes a generator rather than a function, so it should be as simple as using a function instead of a generator when in the class context, I couldn't figure out how that arises in [the code](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-async-generator-functions/src/index.js) though.

| software         | version
| ---------------- | -------
| Babel            |  6.16.0
| node             |  v6.5.0
| npm              |  3.10.3
| Operating System |  Linux (Ubuntu 16.04)

**Comment by hzoo** [comment]
Looks like it works in the repl when you include the es2015 preset, not sure the issue yet

**Comment by Jamesernator** [comment]
Playing around without the repl I noticed that whenever an async method is turned into a function that returns the wrapped result it maintains the target:

e.g.

```js
class Foo {
    constructor(bar) {
        ...
    }

    async *values() {
         ...
    }
    
    async baz() {
        ...
    }
}
```

becomes:

```js
class Foo {
    constructor(bar) {
        ...
    }
    
    *values() { // This should just be values()
        var _this = this;
        return asyncGenerator.wrap(function*() {
            ...
        })
    }
    
    baz() {
        return asyncToGenerator(function*() {...})
    }
}
```

I worked out where the issue arises I think its in this code that turns an async method into a generator  ( [here](https://github.com/babel/babel/blob/master/packages/babel-helper-remap-async-to-generator/src/index.js) ). For a regular function `plainFunction` builds a new function with the appropriate name, but in the `classOrObjectMethod` it simply replaces the body with a new body without changing the class property name.

The solution seems to be just add `node.generator = false` once the body wrapped, I'll do a change and see if I can figure out how to run the tests then put in a pull request.

**Comment by Jamesernator** [comment]
I had a look, the tests themselves are invalid ([this](https://github.com/tc39/proposal-async-iteration/blob/master/Async%20Generator%20Rewrite.md) is the correct conversion). I'll fix them up add the fix line and put in a pull request.
