### ISSUE TITLE
.babelrc "ignore", "only" options are ignored if another config is scanned in subfolder

### ISSUE THREAD

**Issue by pdillon** [babel/babel#4707]
### Input Code

See https://github.com/pdillon/babel-options-demo
### Babel Configuration (.bablerc, package.json, cli command)

``` js
{
  "only": "/transpile",
  "ignore": "node_modules",
  "presets": ["es2015", "stage-0"]
}
```
### Expected Behavior

Only /src/transpile folder should be processed when running `babel ./src -d ./dest`
### Current Behavior

All folders under /src are processed since .babelrc file exists in a subfolder. Does not match behavior when using the command line --only option.
### Possible Solution

Read "only", "ignore" options from .babelrc or package.json config in process working dir (and above) and use as defaults (overridden by command line options).
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.17 |
| node | 6.7.0 |
| npm | 3.10.3 |
| Operating System | OS X |

**Comment by hzoo** [comment]
We're redoing ignore/only in Babel 7 https://github.com/babel/babel/pull/5487 and some other prs so should be fixed then. can run with babelrc false in the cli to not check other configs I believe
