### ISSUE TITLE
Object-destruction without assignment

### ISSUE THREAD

**Issue by luxferresum** [babel/babel#4712]
### A object destruction without an assignment can not be parsed

[can be reproduced in the online try it out](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=let%20a%3B%0A%7Ba%7D%20%3D%20%7Ba%3A12%7D%3B).

```js
let a;
{a} = {a:12}; // Unexpected token on the =
console.log(a); // expect 12
```

I've tried it with and without the `transform-es2015-destructuring` plugin.

It *does* work in node.js

The following code *is* working:

```js
let a;
({a} = {a:12}); // Unexpected token on the =
console.log(a); // expect 12
```

This really looks like a bug to me

**Comment by loganfsmyth** [comment]
It's not a bug. Unfortunately the parens are necessary. Otherwise your snippet is parsed like
```
let a;
{
  a;
}
= {a:12}; // Unexpected token on the =
console.log(a); // expect 12
```

e.g. a block, with an assignment to nothing after it.

**Comment by luxferresum** [comment]
Hm, interesting, the following works in node:

```
let a
{a}={a:12}
console.log(a) 
```

but this doesn't:

```
let a;
{a}={a:12};
console.log(a);
```

well, thanks for the info.
