### ISSUE TITLE
Run ESLint on test files + fix issues

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4714]
https://github.com/babel/babel/blob/c2387f044485a51bfed6e9ab8408fd0c3204ea09/Makefile#L21

`./node_modules/.bin/eslint packages/*/src` it currently only runs on src files but we would want to add `packages/*/test` or something like that.

Because it hasn't been run before we would need to fix the errors there. Don't know how many though

Can be fixed with `--fix` like `./node_modules/.bin/eslint packages/*/src --fix`

Maybe there's a better glob to do both src/test

**Comment by wdhorton** [comment]
I can work on this!
