### ISSUE TITLE
Can't cast (Flow) type of yield expression

### ISSUE THREAD

**Issue by AgentME** [babel/babel#4715]
### Input Code

```js
/* @flow */
function *foo() {
  const x = (yield 5: any);
}
```

### Babel Configuration

```json
{
  "presets": ["es2015"],
  "plugins": ["transform-flow-strip-types"]
}
```

### Expected Behavior

The code should parse, the transform-flow-strip-types plugin should remove the `:any` cast, and the code should compile as if the line were `const x = yield 5;`

### Current Behavior

```
$ ./node_modules/.bin/babel test.js 
SyntaxError: test.js: Unexpected token (3:20)
  1 | /* @flow */
  2 | function *foo() {
> 3 |   const x = (yield 5: any);
    |                     ^
  4 | }
  5 | 
```

### Context

When using Flow and redux-saga (or any similar kind of async-like generator wrapper, like say http://taskjs.org/), Flow doesn't really understand the types of yield expressions or the fact that different yield expressions in one function can have different types, so I usually want to cast the types of the expressions. However Babel fails to parse the most natural way to do this.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.16.0
| node             | 6.6.0
| npm              | 3.10.8
| Operating System | OS X 10.11.4

**Comment by AgentME** [comment]
Interestingly, there's no issue casting the type of an await expression. Babel works fine here:

```js
/* @flow */
async function foo() {
  const x = (await Promise.resolve(5): any);
}
```

**Comment by hzoo** [comment]
If it's a parsing issue then we can move the issue to https://github.com/babel/babylon

**Comment by AgentME** [comment]
I'll do that now.
