### ISSUE TITLE
babel transform this to undefined even it is valid

### ISSUE THREAD

**Issue by simongcc** [babel/babel#4720]
If in global environment,  `use-strict` is used and `this` is used to define variable like createjs
`this.createjs = this.createjs||{};`

`this` will be turned to `undefined`

I have tried presets like `es2015-loose`, `es2015-without-strict` or just `es2015`
none of them is working
I think the transformation is missing out and think that this situation is just invalid

I found this problem when I try to add preloadjs.combined.js and using babel to concat it with other codes.

**Comment by danez** [comment]
I can reproduce this here: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=this.createjs%20%3D%20this.createjs%7C%7C%7B%7D%3B&experimental=true&loose=false&spec=true&playground=false&stage=0

**Comment by DrewML** [comment]
@simongcc This is happening because the `es2015` preset includes `babel-plugin-transform-es2015-modules-commonjs`. When you use that plugin, it it assumed that the parsing goal for _all_ of your JavaScript is a module, which runs in strict mode per the specification.

If you are using the `ES2015` preset, but _not_ using modules, you can use the following configuration in your `.babelrc`:

```json
{
    "presets": [
        ["es2015", {
            "modules": false
        }]
    ]
}
```

**Comment by hzoo** [comment]
You can do `parserOpts: { sourceType: 'script' } }`

**Comment by hzoo** [comment]
Let us know if it still doesn't work for you @simongcc

**Comment by simongcc** [comment]
@hzoo Ok thanks, I will try it later. For I can only try at office, have to do it another time. I am currently using gulp-filter to filter out the script that will be affected by babel to compile first as a workaround.

**Comment by simongcc** [comment]
@DrewML Thanks for your suggestion. But I tried both, are not working. It still generate error when compiling.
```
presets: ["es2015", {
  "modules": false
}]
```

```
presets: ["es2015-without-strict", {
  "modules": false
}]
```

**Comment by simongcc** [comment]
@hzoo the `parserOpts: { sourceType: 'script' }` does not work neither, it still break.

**Comment by DrewML** [comment]
@simongcc I just tested this out locally. The following `.babelrc` will work for you:

```json
{
    "plugins": [
        "transform-es2015-arrow-functions",
        "transform-es2015-block-scoped-functions",
        "transform-es2015-block-scoping",
        "transform-es2015-classes",
        "transform-es2015-computed-properties",
        "transform-es2015-destructuring",
        "transform-es2015-duplicate-keys",
        "transform-es2015-for-of",
        "transform-es2015-function-name",
        "transform-es2015-literals",
        "transform-es2015-object-super",
        "transform-es2015-parameters",
        "transform-es2015-shorthand-properties",
        "transform-es2015-spread",
        "transform-es2015-sticky-regex",
        "transform-es2015-template-literals",
        "transform-es2015-typeof-symbol",
        "transform-es2015-unicode-regex",
        "transform-regenerator"
    ]
}
```

I am a bit surprised that the preset with `modules: false` still ends up wiping out the top-level `this`.

**Comment by DrewML** [comment]
Actually, this also works for me with the latest version:

```json
{
    "presets": [
        ["es2015", { "modules": "false" }]
    ]
}
```

**Comment by DrewML** [comment]
Alright, one more reply and I'll stop bombing your inbox 😄. The syntax you posted for your `.babelrc` is incorrect. Copy/paste the one from my last reply and you should be set.

**Comment by simongcc** [comment]
@DrewML It is working now. Thanks for your prompt reply. The syntax I post is config inside `gulp.babel.js`. Really thanks for your help.

**Comment by simongcc** [comment]
@DrewML I might need your help again, since I have to recreate the project from scratch for some reasons. Then, the latest babel does not allow me to use the previous tricks and throw this error:
`Using removed Babel 5 option`
I cannot use `modules: false` to solve the problem, how should I config the `gulp-babel` or the `.babelrc`?
Thanks in advance.

**Comment by simongcc** [comment]
I finally use `ignore` option to exclude those script files so that babel will not touch them
