### ISSUE TITLE
[7.0] Switch variance to be a separate node

### ISSUE THREAD

**Issue by danez** [babel/babel#4722]
Should be done with babel 7.

See https://github.com/babel/babel/pull/4697 and https://github.com/babel/babylon/pull/161

**Comment by danez** [comment]
@samwgoldman I just saw that flow now also outputs variances as string like `variance: "plus"`. Do you still want to introduce a the new node `Variance`? Or is this now off the table?

I could otherwise do it now (basically resurrecting the code from your PR) as we are starting to work on babylon/babel 7.

**Comment by samwgoldman** [comment]
@danez Thanks for the heads up. I changed Flow's AST output as well based on your feedback. Making a separate node would remove some hacks in the existing implementation, so I support it and will make the change on the Flow side as well when B7 lands.

I'll ping some other folks on the team as well, to see if they want to do any deprecations... cc @gabelevi @mroch

**Comment by hzoo** [comment]
@samwgoldman and just as FYI/context for Babel 7 the main gist is just dropping node 0.10/0.12 and general cleanup.

**Comment by hzoo** [comment]
Made https://github.com/babel/babel/pull/5317 so you can base your PR off of my branch

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/5320
