### ISSUE TITLE
transform-es2015-modules-commonjs - disallowed syntax is allowed

### ISSUE THREAD

**Issue by derekdreery** [babel/babel#4743]
### Input Code

```js
export MyClass from './MyModule'
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["es2015", "react", "stage-1"],
}

```

### Expected Behavior

Expected an error - all export from must include brackets *{* *}* (see https://tc39.github.io/ecma262/#sec-exports)

### Current Behavior

Currently re-exports the default export from './MyModule'

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.16
| node             | 6.7
| npm              | 3.10.8
| Operating System | linux

**Comment by hzoo** [comment]
You are using stage-1 in your babelrc - it includes http://babeljs.io/docs/plugins/preset-stage-1/ http://babeljs.io/docs/plugins/transform-export-extensions/ which is experimental. If you don't want that you'll need to use stage-2 or pick the specific transforms

**Comment by derekdreery** [comment]
My apologies - thanks for the quick response!
