### ISSUE TITLE
ES6 import breaks /* @flow */ position

### ISSUE THREAD

**Issue by philiiiiiipp** [babel/babel#4745]
Using the ES6 import / export functionality seems to break the position of /\* @flow */ in the transpiled .js file. E.g.

I have a .babelrc file containing
`{
  "presets": [
    "es2015",
    "stage-2"
  ],
  "plugins": [
    "transform-flow-comments"
  ]
}
`
### Input Code

If I am transpiling this code here

``` js
/* @flow */

export class test {}
```

``` js
/* @flow */

import { test } from './test';

module.exports.test = test;
```
### Expected Output - Expected Behavior

``` js
'use strict';
/* @flow */
var _test = require('./test');

module.exports.test = _test.test; 
```
### Current Output - Current Behavior

``` js
'use strict';

var _test = require('./test');

module.exports.test = _test.test; /* @flow */

```
### Context

If I am using the standard require directive,

``` js
/* @flow */

const test = require('./test').test;

module.exports.test = test;
```

it transpiles fine

``` js
'use strict';

/* @flow */

var test = require('./test').test;

module.exports.test = test;
```
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.16.0 |
| node | v4.4.7 |
| npm | 3.10.5 |
| Operating System | MacOS 10.11.6 |
| babel-plugin-transform-flow-comments | 6.17.0 |

**Comment by loganfsmyth** [comment]
In this case, what's the motivation for running Flow after Babel has processed your code? Generally Flow would be run on the original source code.

**Comment by philiiiiiipp** [comment]
I am using this for my libraries to have them type checked when I import them at another place.

**Comment by danharper** [comment]
There's a few issues with `transform-flow-comments` when combined with other transforms (especially some of the `es2015` ones).

One of the alternative ways to publish Flow typed packages is to use `transform-flow-strip-types`, but include your original source files alongside the transpiled ones with the extension `.js.flow`. e.g. `src/app.js` -> `dist/app.js` & `dist/app.js.flow`.

Flow will automatically use the `.js.flow` files for type information instead of the `.js` files.

**Comment by philiiiiiipp** [comment]
Ok, that would also be an option. I guess this is not even the right place to ask this, but is that the preferred way of doing it?

**Comment by danharper** [comment]
It seems so: https://github.com/facebook/flow/issues/1469#issuecomment-189767634

Also, I think a future plan is a Flow CLI tool which prints out type definitions with no implementation, so they can retain compatibility with past/future Flow releases. (see `flow gen-flow-files` which is experimental and not "released" yet).

**Comment by philiiiiiipp** [comment]
Great! I will change my configuration towards using .js.flow and keep an eye on ```gen-flow-files```.

I don't know if there will be any development going into ```transform-flow-comments``` then? Maybe you want to add a wontfix tag and close this issue?

**Comment by xtuc** [comment]
Can I close this issue with wontfix ?

**Comment by hzoo** [comment]
Not that there's no development but it's not a priority, closing
