### ISSUE TITLE
Setting --babelrc false do not work, --no-babelrc does.

### ISSUE THREAD

**Issue by moimael** [babel/babel#4749]
### Input Code

``` bash
babel --presets node6 --babelrc false dist -d dist
```
### Expected Behavior

Babel should ignore .babelrc
### Current Behavior

Babel use .babelrc
### Possible Solution

Setting --no-babelrc works, but the documentation for cli options do not mention it. It only mention --babelrc false.

In babel-cli `src/babel/index.js` this line seems to be the culprit : 

``` js
  if (option.type === "boolean" && option.default === true) {
    arg = "no-" + arg;
  }
```

**Comment by SimenB** [comment]
In yargs you have to set the type to `boolean` for it to work with `--babelrc false` (and it then does it automatically, seems like babel does some argument parsing themselves). Doesn't commander support that?

**Comment by hzoo** [comment]
Very weird and should be fixed? associated code seems to be https://github.com/babel/babel/blob/604fad1a7869f08e380bf674d23c298bd6e218c4/packages/babel-cli/src/babel/index.js#L24-L26

**Comment by kaicataldo** [comment]
Yeah, weird - [the `babelrc` option](https://github.com/babel/babel/blob/604fad1a7869f08e380bf674d23c298bd6e218c4/packages/babel-core/src/transformation/file/options/config.js#L149) should fit those requirements...

```js
  babelrc: {
    description: "Whether or not to look up .babelrc and .babelignore files",
    type: "boolean",
    default: true
  },
```

**Comment by kaicataldo** [comment]
@moimael 
> Setting --no-babelrc works, but the documentation for cli options do not mention it. It only mention --babelrc false.

Where are you seeing this? I've looked both through this repo and the Babel website repo and I'm only seeing reference to the `--no-babelrc` option.

**Comment by moimael** [comment]
Here : https://babeljs.io/docs/usage/options/

It has been changed recently by this commit (https://github.com/babel/babel.github.io/commit/1c1e389e133c14ac2004bebb6efa266005a39fd7) on https://babeljs.io/docs/usage/cli/ and it is now correct.

**Comment by kaicataldo** [comment]
Thanks again for this report. Opened up a [PR](https://github.com/babel/babel.github.io/pull/992) to clarify the docs
