### ISSUE TITLE
`parseInt(08)` should work in sloppy mode?

### ISSUE THREAD

**Issue by kangax** [babel/babel#4757]
### Input Code

``` js
parseInt(08);
```
### Babel Configuration (.babelrc, package.json, cli command)

``` js
{
  "sourceType": "script" // so that it's not strict
}
```
### Expected Behavior

Should evaluate to `8`.
### Current Behavior

Throws SyntaxError.
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.17 |

**Comment by danez** [comment]
Seems to be a problem in babylon http://astexplorer.net/#/3zWWI7ZQAf

**Comment by loganfsmyth** [comment]
Yeah, this probably should have been filed over there.

I commented on this on Slack originally, but the open question here is if we should add a "web compat" flag or something. Parser support for this is http://www.ecma-international.org/ecma-262/7.0/#prod-annexB-NonOctalDecimalIntegerLiteral, which is only needed for "web browsers".

**Comment by hzoo** [comment]
@babel-bot move to babel/babylon
