### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sebmck** [babel/babel#476]
With the awesome work by @gaearon with #432 and #433 6to5 has had massive performance boosts. There's still a variety of ways that things can be improved so this an issue for tracking future optimisations and performance. Would love to hear feedback, the faster the better!

**Comment by gaearon** [comment]
IMO optimizing this might give a perf boost:

https://github.com/6to5/6to5/blob/master/lib/6to5/transformation/transformer.js#L56

It's a very hot paths and it would be nice to eliminate closures there (e.g. inner function inside `build` closing over `exit`, `file` and `transformer`). Also, I'm sure perf can be better if there were less calls to `traverse` with anonymous objects a la

```js
  traverse(file.ast, {
    enter: build(),
    exit:  build(true)
  });
```

— calls like these are all over the place — and instead, where possible, it would be something like `traverse(file.ast, this)`. In other words, extract state from closures into dedicated objects that apply transformations and hold their state.

**Comment by gaearon** [comment]
Another thing worth keeping an eye on is whether V8 can effectively reuse types.
Again, having objects that set all their fields in constructors and don't add any dynamic fields, would help.

See also: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers

**Comment by sebmck** [comment]
@gaearon I'm confused by how you envision that code to be structured, can you give a brief overview? Pseudo-code is fine.

**Comment by gaearon** [comment]
@sebmck 

Imagine you weren't allowed to use closures at all.

6to5 API is stateless for consumer (she calls `transform` and gets the result). However, it is stateful inside, at least while transform is running. Some of this state is currently dispersed in various closures.

What I suggest is moving more state from closures into objects. This is similar to what I did in #433: instead of having a function inside a function, we have a dedicated object with a prototype. What was previously a closure variable, is now a field on that object. Thus we avoid potential leaks and function allocations in tight places.

I can't suggest pseudocode at the moment because I don't yet really understand how pieces come together (e.g. how transforms are run, what Scope does, etc).

For an example of codebase that tries hard to avoid closures and function allocations, check out [React](https://github.com/facebook/react/tree/master/src), they're really great at that.

**Comment by sebmck** [comment]
@gaearon Ah right, thanks! Some of the current code is pretty dense and I've been adding comments as I've been working on it to make things much more clearer. Hopefully I'll get around to documenting a lot more of the internals.

**Comment by sebmck** [comment]
Another strategy is replacing lodash methods with the equivalent native version, `contains` => `indexOf`, `_.each` => `for` etc.

**Comment by gaearon** [comment]
>Another strategy is replacing lodash methods with their equivalent native version, contains => indexOf, _.each => for etc.

Nah, not always. Replacing `_.each` gives some wins (but again, not always—I only left those that mattered in my bench in #432) but only because we save function allocation with a `for` loop.

It's a common misconception that “natives are faster”; more often they're not because they have to adhere to very complex semantics for edge cases.

See:

http://stackoverflow.com/a/18886242/458193
https://github.com/angular/angular.js/issues/6697#issuecomment-42771111

>>I'd expect native browser methods to be an order of magnitude faster.

>Built-ins need to adhere to ridiculous semantic complexity which only gets worse as more features get added into the language. The spec is ruthless in that it doesn't leave any case as "undefined behavior" - what happens when you use splice on an array that has an indexed getter that calls Object.observe on the array while the splice is looping?

>If you implemented your own splice, then you probably wouldn't even think of supporting holed arrays, observable arrays, arrays with funky setters/getters and so on. Your splice would not behave well in these cases but that's ok because you can just document that. Additionally, since you pretty much never need the return value of splice, you can just not return anything instead of allocating a wasted array every time (you could also make this controllable from a parameter if needed).

>Already with the above, you could probably reach the perf of "native splice" without even considering the fact that user code is actually optimized and compiled into native code. And when you consider that, you are way past any "native" except when it comes to special snowflakes like charCodeAt, the math functions and such.

**Comment by sebmck** [comment]
@gaearon For the scenarios where they're used, they almost certainly will give performance boosts. lodash calls `indexOf` for `_.contains` anyway, it has a lot of logic to handle different input types. Same goes for `_.each`.

**Comment by phpnode** [comment]
@sebmck [fast.js's](https://github.com/codemix/fast.js) `indexOf` beats `Array.prototype.indexOf` quite significantly - 

```
Native .indexOf() vs fast.indexOf() (3 items)
    ✓  Array::indexOf() x 15,648,086 ops/sec ±1.72% (89 runs sampled)
    ✓  fast.indexOf() x 32,152,806 ops/sec ±1.93% (85 runs sampled)
    ✓  fast.indexOf() v0.0.2 x 35,245,178 ops/sec ±1.53% (92 runs sampled)
    ✓  underscore.indexOf() x 30,916,655 ops/sec ±1.74% (91 runs sampled)
    ✓  lodash.indexOf() x 25,338,411 ops/sec ±1.33% (91 runs sampled)

    Result: fast.js is 105.47% faster than Array::indexOf().
```

**Comment by sebmck** [comment]
@phpnode Interesting. I'll have to sit down and do some thorough benchmarks. I also have to take into consideration maintenance costs with these changes, since if it makes things significantly harder then the trade-offs aren't worth it IMO.

**Comment by gaearon** [comment]
Personally I haven't seen perf improvements from replacing lodash methods in other code paths. Definitely needs benchmarking before complicating maintenance.

By the way another hot path is [`buffer.js`](https://github.com/6to5/6to5/blob/master/lib/6to5/generation/buffer.js) and `newline` method. I think there was quite some time spent on regex there.

**Comment by gaearon** [comment]
The way I benchmarked:

1. A script like https://gist.github.com/gaearon/69979b63d39b4d72cff5 to run 6to5 repeatedly on a complex file

2. After changes, run it several times to see if numbers drop consistently

3. To look what to change, do `node --prof bench.js` and run `nprof` later (from `npm install -g profiler`). Its output will show hot methods, first in a list, then in a tree. Don't waste time on anything below the first couple of tree entries. If you see a method name without a `*`, it's not optimized.

**Comment by sebmck** [comment]
@gaearon Yeah, the entire code generator needs to be optimised. Thanks for the profiling tips, I've been experimenting with different v8 options but that's much more helpful.

**Comment by stefanpenner** [comment]
cc @jdalton this thread may interest you

**Comment by Rich-Harris** [comment]
There are quite a few instances where 6to5 enumerates over an array with `for (var i in arr) {...}` during tree transformation and code generation. This came up in https://github.com/6to5/gobble-6to5/pull/1 because another library was adding enumerable properties to `Array.prototype`, which caused the for-in loop to fail, but I think this has potential performance implications as well - iterating is many times faster than enumerating.

**Comment by stefanpenner** [comment]
Ya for x in y over an array is currently a fail in v8

**Comment by gaearon** [comment]
>There are quite a few instances where 6to5 enumerates over an array with for (var i in arr) {...}

Indeed. I fixed a few of these which affected perf, but the rest I didn't touch because I couldn't squeeze any improvements out of them. Still, it's better to rewrite these.

**Comment by sebmck** [comment]
There are so many more low hanging fruit than pedantically worry about `for...in` loops.

**Comment by jdalton** [comment]
Can dig. @gaearon's got the right idea on profile based priority. With most things-ES5y it'll be faster to fallback to simplified vanilla js alternatives with exceptions of things like `Array.isArray` or `Object.keys` when wanting to avoid the for-in gotchas. Optimizations & techniques are scenario & context specific so there may not be a silver bullet. There's also engine intricacies which may mean having to get into ugly code to squeeze out perf.

You could break this issue into a profiled study of each of 6to5's components starting with ones you think are problem areas and working outward.

**Comment by jdalton** [comment]
Just as with game engines in tight loops it'll be beneficial to ditch general purpose methods, which includes lodash, for highly tuned scenario specific code.

**Comment by jdalton** [comment]
If you're wanting different takes on perf I know @stefanpenner has done a lot of perf work for Ember and has insight into property access and hash map perf. I've been refining my approach to Lo-Dash (getting overall 25-45% improvements) so I can speak to the techniques used there too.

**Comment by sebmck** [comment]
@jdalton Awesome, thanks for your help!

**Comment by gaearon** [comment]
OK I think I have a plan for potential optimization.

As I said I want `opts` passed to `traverse` to have a prototype. So its `enter` and `exit` will be defined on prototype and will not be closures.

Now that I think of it, this object takes the same role as `TraversalContext` from my refactor. So I suggest we extract `TraversalContext` from `traverse/index` and have all transforms build on top of its prototype (but also declaring `enter` and `exit`).

The natural consequence of this is we'll just call `this.enter` instead of `opts.enter.call(this, ...)`. So it's not just a performance refactor—I believe this will actually make existing code more comprehensive.

Thoughts?

**Comment by gaearon** [comment]
https://github.com/6to5/6to5/pull/494

**Comment by chicoxyzzy** [comment]
nice thread! but you guys should remember that if some js alternatives beat native functions today it may not be true for some tomorrow's build of v8. also readability matters

**Comment by jdalton** [comment]
In this case for things like ES5 implementations plain JS has been faster for going on 10 years now. Even if native one day V8 catches up, the current fast plain JS alternative won't likely be getting slower.

**Comment by chicoxyzzy** [comment]
yea I know I just wanna say don't be too fanatic

**Comment by jdalton** [comment]
> yea I know I just wanna say don't be too fanatic

I don't think anyone has said being fanatic is the best approach. I think profiled based investigations and optimizations are the way to go. As mentioned earlier optimizations are context specific so some bits may require uglier code. That seems like a grounded and reasonable approach which should avoid micro-opts & superstitious coding.

**Comment by gaearon** [comment]
https://github.com/6to5/6to5/pull/518

**Comment by Globegitter** [comment]
It seems the require times, using
```
require("6to5/register")({
  experimental: true
});
```
are quite slow using `3.0.10`. You can find them here: https://gist.github.com/Globegitter/3c7272a3f32d91833290
I have been comparing it to traceur with `asyncFunctions: true` and it takes about 1-1.5s more to load.

I know I could compile the code for better loading time, but I am trying to avoid a build step and traceur does perform decently.

**Comment by sebmck** [comment]
@Globegitter Caching is automatically done in 3.x with `6to5/register` and `6to5-node` so the performance you're likely experiencing is just due to loadtime in general.

**Comment by sebmck** [comment]
Or are you referring to the actual time spent actually executing `require("6to5/register");`.

**Comment by Globegitter** [comment]
Yep, it is the actual time spent executing the `require`.

**Comment by sebmck** [comment]
Only takes 280ms for me.

```sh
$ node
> var time = Date.now(); require("6to5/register"); Date.now() - time;
280
```

**Comment by Globegitter** [comment]
Yeah, that is odd. It was just some quick testing. Will do more and report back if the performance issues persist.

**Comment by sebmck** [comment]
Definently something weird going on, not sure if it's 6to5 related. This is the output of `node-require-timings` for me when requiring `6to5`:

```
/Users/sebastian/Projects/6to5/6to5/lib/6to5/helpers/object.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/helpers/to-fast-properties.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/esutils/lib/ast.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/esutils/lib/code.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/esutils/lib/keyword.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/esutils/lib/utils.js: 2ms
/Users/sebastian/Projects/6to5/6to5/node_modules/acorn-6to5/acorn_csp.js: 9ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/types/node.js: 10ms
/Users/sebastian/Projects/6to5/6to5/node_modules/lodash/index.js: 17ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/types/index.js: 39ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/traverse/scope.js: 43ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/traverse/index.js: 44ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformer-pass.js: 45ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformer.js: 45ms
/Users/sebastian/Projects/6to5/6to5/node_modules/detect-indent/node_modules/repeating/node_modules/is-finite/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/detect-indent/node_modules/repeating/index.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/detect-indent/index.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/whitespace.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/node_modules/amdefine/amdefine.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/base64.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/base64-vlq.js: 2ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/util.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/array-set.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/mapping-list.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/source-map-generator.js: 9ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/binary-search.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/source-map-consumer.js: 2ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map/source-node.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/source-map/lib/source-map.js: 13ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/source-map.js: 14ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/position.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/estraverse/estraverse.js: 2ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/types.js: 2ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/shared.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/def/core.js: 13ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/def/es6.js: 5ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/def/es7.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/def/mozilla.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/def/e4x.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/def/fb-harmony.js: 4ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/equiv.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/path.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/scope.js: 4ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/node-path.js: 7ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/lib/path-visitor.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/ast-types/main.js: 42ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/patch.js: 47ms
/Users/sebastian/Projects/6to5/6to5/node_modules/supports-color/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/js-tokenizer/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/escape-string-regexp/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/ansi-styles/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/strip-ansi/node_modules/ansi-regex/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/strip-ansi/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/has-ansi/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/node_modules/supports-color/index.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/chalk/index.js: 4ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/helpers/code-frame.js: 8ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/util.js: 93ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/buffer.js: 93ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/node/whitespace.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/node/parentheses.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/node/index.js: 3ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/template-literals.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/comprehensions.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/expressions.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/statements.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/playground.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/classes.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/methods.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/modules.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/types.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/flow.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/base.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generators/jsx.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/generation/generator.js: 125ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/helpers/clone.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/file.js: 127ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/_strict.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/_default.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/common.js: 3ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/common-strict.js: 3ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/amd.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/amd-strict.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/umd.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/umd-strict: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/use-strict.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/system.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/ignore.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/modules/index.js: 9ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/other/use-strict.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/validation/undeclared-variable-check.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/validation/no-for-in-of-assignment.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/validation/setters.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/spec/block-scoped-functions.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/explode-assignable-expression.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/build-conditional-assignment-operator-transformer.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/playground/mallet-operator.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/playground/method-binding.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/playground/memoization-operator.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/playground/object-getter-memoization.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/other/react.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/internal/modules-split.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/build-comprehension.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es7/comprehensions.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/arrow-functions.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/replace-supers.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/name-method.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/classes.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/remap-async-to-generator.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/other/bluebird-coroutines.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/other/async-to-generator.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es7/object-spread.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/helpers/build-binary-assignment-operator-transformer.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es7/exponentiation-operator.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/spread.js: 3ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/template-literals.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es5/properties.mutators.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/properties.shorthand.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/properties.computed.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/for-of.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regexpu/node_modules/regjsgen/regjsgen.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regexpu/node_modules/regjsparser/parser.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regexpu/node_modules/regenerate/regenerate.js: 4ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regexpu/data/character-class-escape-sets.js: 2ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regexpu/rewrite-pattern.js: 18ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/unicode-regex.js: 19ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es7/abstract-references.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/constants.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/block-scoping.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/block-scoping-tdz.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/node_modules/through/index.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/lib/hoist.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/lib/leap.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/private/private.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/lib/meta.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/lib/util.js: 0ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/lib/emit.js: 4ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/lib/visit.js: 6ms
/Users/sebastian/Projects/6to5/6to5/node_modules/regenerator-6to5/main.js: 8ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/other/regenerator.js: 9ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/parameters.default.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/parameters.rest.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/destructuring.js: 1ms
/Users/sebastian/Projects/6to5/6to5/node_modules/core-js/library.js: 10ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/other/self-contained.js: 13ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/es6/modules.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/internal/block-hoist.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/spec/proto-to-assign.js: 2ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/internal/declarations.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/internal/alias-functions.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/internal/module-formatter.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/spec/typeof-symbol.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/spec/undefined-to-void.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/minification/property-literals.js: 1ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/minification/member-expression-literals.js: 0ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transformers/index.js: 108ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/transformation/transform.js: 292ms
/Users/sebastian/Projects/6to5/6to5/lib/6to5/index.js: 293ms
```

**Comment by stefanpenner** [comment]
@sebmck this is why the `ember-cli-6to5` actually just lazily requires 6to5 https://github.com/6to5/ember-cli-6to5/blob/master/index.js#L12

**Comment by sebmck** [comment]
@stefanpenner I need something more substantial since I can't reproduce require times exceeding anything beyond 300ms.

**Comment by stefanpenner** [comment]
Some deps are just slow to require, this typically just affects command-line tools, the approach I have taken is to lazily require those deps so we only encure the penalty if they are used.

and extra 300ms for commandline tools is gnarly.

@sebmck maybe @Globegitter has a slow disk? HDD/thumbdrive or disk encryption

**Comment by sebmck** [comment]
@stefanpenner Ah yeah, understood. Not sure if there's anything that can be done as I can't seem to locate any problem files that can be optimised.

**Comment by stefanpenner** [comment]
@sebmck i can take a look for you after work,  the above tool helpers identify problematic areas, but does mask which specific modules are the problem. It is a good guide for further investigation.

**Comment by sebmck** [comment]
It'd be more helpful if `node-require-timings` dumped all the times/requires as a tree because it makes it hard to visualise.

**Comment by stefanpenner** [comment]
@sebmck i know the maintainer, he is open to PR's https://github.com/stefanpenner/node-require-timings

**Comment by sebmck** [comment]
@stefanpenner Haha, that'll teach me to not check out packages more thoroughly :stuck_out_tongue_winking_eye:

**Comment by sebmck** [comment]
Managed to cut the transpilation speed in ~half.

> 12738 passing (57s)

from 

> 12738 passing (2m)

**Comment by gaearon** [comment]
how?!

**Comment by sebmck** [comment]
I made all the transformers export a methods that check if an input `node` would require the transformer to be ran. Then before any of the transformers are ran I do a prepass of the ast and run all the transformer checks against each node. It's a little more complicated than that but that's the gist of it.

**Comment by sebmck** [comment]
Also the code generator is looking to be the bottleneck now. Plenty of places for potential optimisation.

**Comment by sebmck** [comment]
Most of the performance work I've had in mind has already been completed so I'm closing this. Superseded by #883 anyway since there are various architectural changes I'm making that will improve this even more.

**Comment by zdychacek** [comment]
Comparing the total time of the transpilation process with Traceur.

Our codebase consists of 83 files with average of 400 LOC.

We use this configuration:

```
{
	optional: [
		'es7.comprehensions'
	],
	blacklist: [
		'validation.react',
		'es7.exponentiationOperator',
		'es6.constants',
		'es6.blockScoping',
		'es6.tailCall',
		'es3.memberExpressionLiterals',
		'es3.propertyLiterals',
		'regenerator',
		'flow',
		'optimisation.flow.forOf',
		'spec.functionName',
		'spec.blockScopedFunctions'
	]
}
```

The transpilation process takes about 15s, which is too long compared with Traceur. Traceur can handle the transpilation in less than 2s.

I am wondering where could be another performance issues?

I think, there must be something slow with a parser or a code generatoration.

When I run transpilation with ```DEBUG=babel``` I can see a lot of useful information. I can see how much time each of the transformers took. And probably, I can see the total time spent on parsing each of the files as well. An output for one file follows (this file has 1022 LOC):

```
babel /controllers/groupsCtrl.spec.js +340ms
babel /controllers/groupsCtrl.spec.js: Running transformer strict +235ms
babel /controllers/groupsCtrl.spec.js: Running transformer _validation +0ms
babel /controllers/groupsCtrl.spec.js: Running transformer _modules +19ms
babel /controllers/groupsCtrl.spec.js: Running transformer es7.comprehensions +16ms
babel /controllers/groupsCtrl.spec.js: Running transformer es6.templateLiterals +17ms
babel /controllers/groupsCtrl.spec.js: Running transformer es6.properties.shorthand +17ms
babel /controllers/groupsCtrl.spec.js: Running transformer es6.forOf +17ms
babel /controllers/groupsCtrl.spec.js: Running transformer es6.modules +44ms
babel /controllers/groupsCtrl.spec.js: Running transformer _blockHoist +27ms
babel /controllers/groupsCtrl.spec.js: Running transformer _declarations +22ms
babel /controllers/groupsCtrl.spec.js: Running transformer _shadowFunctions +21ms
babel /controllers/groupsCtrl.spec.js: Running transformer _strict +49ms
babel /controllers/groupsCtrl.spec.js: Running transformer _moduleFormatter +20ms
babel /controllers/groupsCtrl.spec.js: Running transformer _cleanUp +69ms
babel /controllers/groupsCtrl.spec.js: Running transformer _declarations +24ms
```

I assume, the first line in the output above expresses a parsing time of the whole file (???). In this instance, running all transformers took 597ms.

So if I understand the log above correctly, it took 597+340=937ms for transpiling that particular file in total.

It can be seen that the parsing time of the file (again, assuming the first line expresses the parsing time) and strict transformer are most slowest operations.

This slowness makes using Babel unusable for us and for any larger projects in general. And that's a pitty :(

Is there any plan to do another optimizations?

Thanks for reply.

**Comment by sebmck** [comment]
> So if I understand the log above correctly, it took 597+340=937ms for transpiling that particular file in total.

No, the 235ms is the time from initial load to the file actually being transformed so it includes all the overhead from parsing **and** `require` calls.

> This slowness makes using Babel unusable for us and for any larger projects in general. And that's a pitty :(

It's working great for many ember-cli users :) You should be using incremental builds anyway (it's crazy not to), but there is definently room for improvement.

What version are you using? I recall cleaning up the debug output to be more clear.

> Is there any plan to do another optimizations?

There are always plans for optimisations.
