### ISSUE TITLE
Transitive assignment is broken

### ISSUE THREAD

**Issue by dbkaplun** [babel/babel#4760]
### Steps to reproduce
[`var {foo, baz} = src = {foo: 'bar', baz: 'quux'};`](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=true&spec=false&code=var%20%7Bfoo%2C%20baz%7D%20%3D%20src%20%3D%20%7Bfoo%3A%20'bar'%2C%20baz%3A%20'quux'%7D%3B%0A)

### Current Behavior
```js
'use strict';

var _src = src = { foo: 'bar', baz: 'quux' };

var foo = _src.foo;
var baz = _src.baz;

// src is not defined!
```

### Expected Behavior
```js
'use strict';

var src = { foo: 'bar', baz: 'quux' };

var foo = src.foo;
var baz = src.baz;
```

**Comment by loganfsmyth** [comment]
This is expected. It's not defined in your original snippet either. You're assigning to `src`, but since it's on the right hand side of the `var`, it's not one if the declared variables.

    var {foo, baz} = src = {foo: 'bar', baz: 'quux'};

is

    var {foo, baz} = (src = {foo: 'bar', baz: 'quux'});

e.g.

the right-hand side is just a normal assignment, in this case to a variable that isn't declared.
