### ISSUE TITLE
babel-node doesn't use the right node version

### ISSUE THREAD

**Issue by rightaway** [babel/babel#4761]
When running `babel-node /a/b/c/script.js` (script.js contains `console.log(process.version)`), I would expect to see the same version of node that would be printed by running plain `node /a/b/c/script.js`.

But this isn't the case, in some cases it prints the version of the globally installed node when PATHs (on linux) have been set up to use a different version.

I'm using https://github.com/nodenv/nodenv, where the `node` command point to their `~/.nodenv/shims/node` command, which executes the version of node that has been specified by a `.node-version` file.

If there's a `/a/b/.node-version` file containing 6.9.0, then running `node /a/b/c/script.js` from any directory will print 6.9.0. But running `babel-node /a/b/c/script.js` prints 6.9.0 when the current working directory is `/a/b/c` but if you run the command from `/a` for example, it prints the globally installed version of node, which is incorrect.

**Comment by hzoo** [comment]
Going to close for inactivity, but we'd appreciate a PR if you want to do it! https://github.com/babel/babel/blob/d33d02359474296402b1577ef53f20d94e9085c4/packages/babel-cli/src/_babel-node.js
