### ISSUE TITLE
minified flag incorrectly transforms SingleEscapeCharacters

### ISSUE THREAD

**Issue by HyeonuPark** [babel/babel#4767]
It prints additional backslash
### Input Code

``` js
const babel = require('babel-core')
console.log(babel.transform('"foo\\n\\t\\r"', {minified: true}).code)
```
### Expected Behavior

`"foo\n\t\r"`
### Current Behavior

`"foo\\n\\t\\r"`
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.17.0 |
| node | 6.1.0 |
| npm | 3.10.8 |
| Operating System | Linux Mint 17.3 |

**Comment by DrewML** [comment]
I _think_ this may have regressed [here](https://github.com/babel/babel/pull/3492/files?diff=split#diff-7fc590528f8200869849c2a7a2bc6360R99) in the `getPossibleRaw` method. Commenting out the check for `this.format.minified` that was added in that commit fixes the bug.

**Comment by aaronang** [comment]
I have done some investigation and it seems that the current library that we are using does not have any support for *not* escaping special characters, e.g. `\n`, `\r`, `\t`, etc.

Have a look here: mathiasbynens/jsesc#20.
