### ISSUE TITLE
babel-types 6.18.0 version is not published

### ISSUE THREAD

**Issue by thecodejack** [babel/babel#4779]
`babel-helper-builder-react-jsx` is asking for `babel-types` version `6.18.0`. Because of this I am getting following error.

```
npm ERR! Linux 3.10.0-327.36.1.el7.x86_64
npm ERR! argv "/usr/local/pkgs/node-4-4.7/bin/node" "/npm-globals/bin/npm" "install" "babel-types@6.18.0"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-types@6.18.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.16.0, 6.15.0, 6.14.0, 6.13.0, 6.11.1, 6.10.2, 6.10.0, 6.9.1, 6.9.0, 6.8.1, 6.8.0, 6.7.7, 6.7.2, 6.7.0, 6.6.5, 6.6.4, 6.6.0, 6.5.2, 6.5.1, 6.5.0, 6.5.0-1, 6.4.5, 6.4.3, 6.4.1, 6.4.0, 6.3.24, 6.3.21, 6.3.20, 6.3.18, 6.3.17, 6.3.14, 6.3.13, 6.3.0, 6.2.4, 6.2.3, 6.2.0, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.19, 6.0.18, 6.0.17, 6.0.15, 6.0.14, 6.0.13, 6.0.12, 6.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /.www/reporting-infra/code/frontend/npm-debug.log
```

As per https://www.npmjs.com/package/babel-types it is still in 6.16.0 version only.

**Comment by HenrikWM** [comment]
We have the same issue on the `babel-helper-function-name` package. Please publish 6.18.0 for this as well.

**Comment by witwit** [comment]
```
npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-register@^6.18.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.16.3, 6.16.0, 6.14.0, 6.11.6, 6.11.5, 6.9.0, 6.8.0, 6.7.2, 6.6.5, 6.6.0, 6.5.2, 6.5.1, 6.5.0, 6.5.0-1, 6.4.3, 6.3.13, 6.3.2, 6.2.4, 6.2.0, 6.1.18, 6.1.17, 6.1.4
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'babel-cli'
npm ERR! notarget
``` 

**babel-cli** wants non-existing **babel-register@^6.18.0** here...

**Comment by Braincompiler** [comment]
The version 6.18.0 was published 12 hrs ago (https://www.npmjs.com/package/babel-register): I guess this problem may happen if we use a company-internal npm registry which is not up-to-date. When I install `babel-cli` into a clean project it will be install `babel-cli 6.18.0` and a dependency of `babel-register` with the version `6.18.0`. I got also some problems with the domain npmjs.com where the DNS-Record couldn't be found. Maybe this is also a problem where the company-internal npm registry is not able to update itself.

**Comment by danez** [comment]
All this packages were successfully released:
```
❯ npm show babel-types dist-tags
{ latest: '6.18.0' }

❯ npm show babel-helper-function-name dist-tags
{ latest: '6.18.0' }

❯ npm show babel-register dist-tags
{ latest: '6.18.0' }
```

It might what @Braincompiler wrote, that you might need to check your own npm proxy which might be caching the package metadata.

**Comment by thecodejack** [comment]
ok Thanks. Yes Looks like issue with local npm registry.

**Comment by ncedric** [comment]
I don't think it is a company registry issue. 
If I browser to https://www.npmjs.com/package/babel-types 
the last version is 6.16.0
"6.16.0 is the latest of 49 releases". I can't see the 6.18.0 yet.

Do you already noticed than after publishing on npmjs the package is not directly available?

**Comment by danez** [comment]
The npmjs.com website is cached and it takes some days till the newest version shows up there.

try typing in your command line to see the latests version:
```
npm show babel-types dist-tags 
```

**Comment by thecodejack** [comment]
I can confirm that it's probably local npm registry issue. When I linked directly to `https://registry.npmjs.com` it downloaded correct version. i.e., 6.18.0

**Comment by ncedric** [comment]
npm installed worked for me 2 minutes ago but was not working 2 hours ago
Maybe an issue (update delay) with the enterprise registry in the end.

Thanks Danez
