### ISSUE TITLE
Unexpected function parameter rename in `transform-es2015-function-name`

### ISSUE THREAD

**Issue by stephank** [babel/babel#4782]
### Input Code

``` js
x => ({ x: () => x });
```
### Babel Configuration

``` sh
babel --plugins transform-es2015-function-name
```
### Expected Behavior

Unchanged output:

``` js
x => ({ x: () => x });
```
### Current Behavior

Function parameter is prefixed with an underscore:

``` js
_x => ({ x: () => _x });
```
### Context

In projects using babel-plugin-angularjs-annotate, the function parameter is used to determine the service to inject. The renamed parameter causes dependency injection to fail.

In a real world project I'm using, our configuration combines the es2015 preset with angularjs-annotate to get this issue.

Downstream discussion: https://github.com/schmod/babel-plugin-angularjs-annotate/issues/15

Some more scenario's:

``` js
// BAD: replace arrow function with regular function
function foo(x) { return { x: () => x }; };
// function foo(_x) {
//  return { x: () => _x };
// }

// GOOD: replace `x` return with something else
x => ({ x: () => 7 });
// x => ({ x: () => 7 });

// GOOD: replace property name with something else
x => ({ z: () => x });
// x => ({ z: () => x });

// GOOD: use method syntax
x => ({ x() { return x; } });
// x => ({ x() {
//     return x;
//   } });
```
### Your Environment

| software | version |
| --- | --- |
| babel | 6.18.0 |
| babel-plugin-transform-es2015-function-name | 6.9.0 |
| babel-plugin-angularjs-annotate | 0.6.0 |
| node | 6.9.1 |
| npm | 3.10.8 |
| Operating System | macOS 10.12.0 |

**Comment by loganfsmyth** [comment]
Preserving function parameter names is not a goal Babel can achieve, Babel changes parameter names in many cases, and has to in order to get the code to be as spec-compliant as possible. It would be the responsibility of the `angular-annotate` plugin to run early enough that the other Babel plugins had not yet executed.

**Comment by schmod** [comment]
> It would be the responsibility of the angular-annotate plugin to run early enough

Hi @loganfsmyth 

I'm the author of the angularjs-annotate plugin.  Is there any way for me to actually guarantee that my transformations run before others?  If not, is there a good mechanism to access the "untransformed" parameter values?

From what I was aware of, this isn't something that plugin authors can actually control...

**Comment by DrewML** [comment]
I'm not sure if it has changed since the plugin docs were written, but:


> Ordering matters for each visitor in the plugin. This means if two transforms both visit “Program”, the transforms will run in either plugin or preset order.

> Plugins run before Presets.

> Plugin ordering is first to last.

Have you tried running the sample code, with this plugin listed as the first in your config?

**Comment by schmod** [comment]
Jumping back to this very old issue: 

While I'm sympathetic to the fact that Babel sometimes has no choice but to rename function parameters, there are cases where `transform-es2015-function-name` is renaming parameters _for no reason_.  

For instance, take @stephank's original example:

```js
x => ({ x: () => x });
// transforms to
_x => ({ x: () => _x });
```

In this case, `transform-es2015-function-name` produces an output that is functionally-equivalent to the input, but unnecessarily renamed the function parameter.

This mutation _would be_ necessary when combined with `transform-es2015-arrow-functions`, but that's a separate issue -- neither transformation should necessarily assume that the other one is enabled.  

It's unclear why this transformation is run against arrow functions at all -- in practice, any engine that natively supports arrow functions also supports `Function.name`.

**Comment by hzoo** [comment]
I believe this was fixed in https://github.com/babel/babel/pull/5008 when we stopped running over arrow functions!
