### ISSUE TITLE
building async iterators with transform-runtime produces wrong build, but babel-node works properly

### ISSUE THREAD

**Issue by darsain** [babel/babel#4783]
Isolated issue here: https://gist.github.com/anonymous/dcbc9f57057724ee5ffe0650eedc9472

```
git clone https://gist.github.com/dcbc9f57057724ee5ffe0650eedc9472.git example
cd example
npm install
npm run execute
npm run build
```
### Input Code (`index.js`)

``` js
async function * values(iterable) {
    for (const item of iterable) {
        yield item;
    }
}

async function collect(asyncIterator) {
    const collection = [];
    for await (const value of asyncIterator) {
        collection.push(value);
    }
    return collection;
}

collect(values([5, 4, 3, 2, 1])).then(console.log, console.error);
```
### Babel Configuration (`package.json`)

``` js
{
  "scripts": {
    "build": "babel index.js --out-file build.js && node build.js",
    "execute": "babel-node index.js"
  },
  "babel": {
    "plugins": [
      ["transform-runtime", {"polyfill": false, "regenerator": true}]
    ],
    "presets": ["stage-3", "latest"]
  },
  "dependencies": {
    "babel-runtime": "^6.18.0"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-stage-3": "^6.17.0"
  }
}
```
### Expected Behavior

Both scripts in `package.json:scripts` should log the array `[5, 4, 3, 2, 1]`.
### Current Behavior

The `build` script that relies on `babel` command produces a build file that throws:

```
TypeError: Object is not async iterable
```

On the other hand, the `execute` script relying on `babel-node` works properly.
### Possible Solution

The fact that `babel-node` works might be a clue.

Also @hzoo on slack mentioned it might be related to #4768.
### Your Environment

Module versions are specified in `package.json` above.

| software | version |
| --- | --- |
| node | 6.7.0 |
| npm | 3.10.9 |
| Operating System | Win 10 |

**Comment by hzoo** [comment]
In https://github.com/babel/babel/blob/ec496480381d5c3ce9f14e5df186f2823c50c9b3/packages/babel-helpers/src/helpers.js#L66-L75

`if (typeof Symbol === "function") {` gets `"object"` instead of function

**Comment by taion** [comment]
This is related to https://github.com/babel/babel/issues/4418.

**Comment by taion** [comment]
This is happening because

```js
require("../core-js/symbol/async-iterator");
```

gets called before

```js
require("../core-js/symbol");
```

in the transpiled code for the helper.

It looks like this is happening because added imports are prepended rather than appended.

I wonder why the runtime transform can't be smarter and just use `Symbol.asyncIterator` from the core-js polyfilled `Symbol` anyway.

**Comment by taion** [comment]
Committers:

Would it make sense to update babel-runtime to not separately pull in `Symbol.asyncIterator`, `Symbol.iterator`, &c. if `Symbol` has already been pulled in?

This wouldn't fix the core-js bug in this case, but with the way core-js is currently set up, it will also have the nice side benefit of eliminating unnecessary imports in code that's gone through the runtime transform.

**Comment by hlehmann** [comment]
I think I have a similar issue now.
`Error: [object Object] is not iterable!`

I fixed it with 
`import "core-js/modules/es7.symbol.async-iterator";`
