### ISSUE TITLE
No compatible version found: babel-types@^6.18.0

### ISSUE THREAD

**Issue by lschuermann** [babel/babel#4785]
Hello,

when installing either babel-require or babel-core, npm complains about no compatible version of babel-types (^6.18.0) found.

Visiting [babel-type's npm-page](https://npmjs.com/package/babel-types), I can confirm that the highest available version is 6.16.0.

### Expected Behavior
Install the package and dependencies correctly.

### Current Behavior
Doesn't install babel-types because of a version-conflict.

### Possible Solution
* Upload a new babel-types version
* Modify babel-core & babel-require (maybe more?) to use an older version.

### Context
I'm trying to get Babel to work.

### Your Environment
| software         | version
| --------------  | -------
| babel-core            | Trying to install v6.18.0   
| node             | v6.9.1
| npm              | v3.10.8
| Operating System | Debian 8.6 Jessie

**Comment by lschuermann** [comment]
Okay, I just now saw that it may take a little time for npm to register the updates to all the packages from commit [`12f9cd0` (v6.18.0)](https://github.com/babel/babel/commit/12f9cd082614945b793493d9f341fd065b0f9497).

But is 2 days still normal?

Thanks!

**Comment by danez** [comment]
The npm page is heavily cached and it takes time till the newest version shows up there.

to proper check do:
```
 npm dist-tag ls babel-types
```

IF you have a npm proxy in place ensure it is correctly setup and not caching invalid old stale data.
