### ISSUE TITLE
Possible to represent reserved keywords using unicode escape sequences.

### ISSUE THREAD

**Issue by dashed** [babel/babel#4786]
### Input Code

```js
let n = 5;

while(n --> 0) {
  \u0062\u0072\u0065\u0061\u{006B};
}

console.log(n);
```

[In action in babel REPL (Babel 6.18.0)](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=true&loose=true&spec=false&playground=true&code=let%20n%20%3D%205%3B%0A%0Awhile(n%20--%3E%200)%20%7B%0A%20%20%5Cu0062%5Cu0072%5Cu0065%5Cu0061%5Cu%7B006B%7D%3B%0A%7D%0A%0Aconsole.log(n)%3B)

### Expected Behavior

It shouldn't be possible to represent reserved keywords using unicode escape sequences (e.g. `\uXXXX` or `\u{XXXX}`).

See: http://www.ecma-international.org/ecma-262/7.0/#sec-reserved-words

### Current Behavior

example:

`\u0062\u0072\u0065\u0061\u{006B}; => break;`

### Possible Solution

*TBD*

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0 (via REPL)
| node             |  n/a
| npm              |  n/a
| Operating System | n/a

-----

/cc @mathiasbynens (for his expertise 😄  )

**Comment by DrewML** [comment]
Nice catch! I think this is a bug in [Babylon](https://github.com/babel/babylon/), based on the [tree generated in ASTExplorer](http://astexplorer.net/#/3pWohxp2Yc). The escape sequences are being translated to an `Identifier` of `break`.

**Comment by mathiasbynens** [comment]
This is something that web browsers used to allow despite it not being mentioned in the spec. As of ES6/ES2015, this behavior is explicitly non-conforming. More background from <https://mathiasbynens.be/notes/javascript-identifiers>:

> […] For example, `var v\u0061r = 42; alert(va\u0072);` would alert `42`. This is very confusing, so I wouldn’t recommend relying on this hack. Luckily, it looks like the ECMAScript 6 spec [will explicitly make this behavior non-conforming](https://bugs.ecmascript.org/show_bug.cgi?id=277). Firefox/Spidermonkey, [Safari/JavaScriptCore](https://trac.webkit.org/changeset/185437), and IE/Chakra have already dropped this behavior.

**Comment by DrewML** [comment]
@dashed I made a copy of this issue [in the Babylon repository](https://github.com/babel/babylon/issues/206), since it is going to need a fix in the parser. Thanks again for the report!.
