### ISSUE TITLE
Sourcemaps fail with babel-core >=6.14

### ISSUE THREAD

**Issue by rhys-vdw** [babel/babel#4788]
Building via webpack, babel-loader. Updating babel-core to 6.14 or beyond breaks my existing config. There is a probably a complex interplay of modules here, but I don't have time to create a minimal failing example now. Happy to dig into this further if required.

6.13:
![image](https://cloud.githubusercontent.com/assets/822105/19754276/a3a47a02-9c57-11e6-84a9-ff616ce59108.png)

6.14:
![image](https://cloud.githubusercontent.com/assets/822105/19754241/6d854e7e-9c57-11e6-94b1-23771b9e719e.png)

**Comment by DrewML** [comment]
A minimal test case would be ideal. Without that, it's still important to know

- Version of `babel-loader`
- Sourcemap setting in `Webpack` config
- Version of `Webpack`
- Presets/Plugins being used

**Comment by rhys-vdw** [comment]
.babelrc

```
{
  "presets": [
    "es2015-loose",
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "lodash"
  ],
  "sourceMaps": true,
  "env": {
    "production": {
      "plugins": ["transform-react-remove-prop-types"]
    }
  }
}
```

And here is my full `devDependencies` (obv. they're not all relevant):

- babel-core: 6.13.0
- babel-loader: 6.2.5
- babel-plugin-lodash: 3.2.9
- babel-plugin-transform-object-rest-spread: 6.16.0
- babel-plugin-transform-react-remove-prop-types: 0.2.10
- babel-preset-es2015: 6.18.0
- babel-preset-es2015-loose: 8.0.0
- babel-preset-react: 6.5.0
- compression-webpack-plugin: 0.3.1
- eslint: 3.8.1
- eslint-import-resolver-webpack: 0.6.0
- eslint-loader: 1.6.0
- eslint-plugin-import: 2.0.1
- eslint-plugin-react: 6.4.1
- fixpack: 2.3.1
- raw-loader: 0.5.1
- react-hot-loader: 1.3.0
- stats-webpack-plugin: 0.2.1
- uh-erb-loader: 1.1.0 _this one is in-house, but [it's on github](https://github.com/usabilityhub/erb-loader)_
- webpack: 1.13.2
- webpack-combine-loaders: 2.0.0
- webpack-dev-server: 1.16.2

Changing the webpack `devtool` didn't seem to make much of a difference, but for what it's worth it's set to `'cheap-module-eval-source-map'`.

**Comment by Kovensky** [comment]
Webpack has also been having some source map reliability issues (https://github.com/webpack/webpack/issues/3165), but not sure whether it's webpack's fault, a loader's fault, or some browsers' fault.

It seems the only 'foolproof' settings are `inline-source-map` and `eval-inline-source-map`, but there are reports of even those having problems.

**Comment by rhys-vdw** [comment]
Hey everyone. I was consistently getting this error when I changed back and forth between babel-core versions, but now I get it at different versions. I have managed to get them working again via some permutations, but I no longer am convinced it's related to Babel (most likely Webpack as @Kovensky helpfully pointed out, thanks). Thanks for you time.
