### ISSUE TITLE
How to get constructor arguments when using babel-plugin-transform-class-properties

### ISSUE THREAD

**Issue by zhaoyao91** [babel/babel#4794]
I use a syntax with react component like this before:

```
class View extends React.Component {
  state = {
    someState: this.props.someProp   
  }
}
```

but now it doesn't works.
so the props are originally passed as constructor arguments, how to reference them when define class properties?

**Comment by danharper** [comment]
Could you paste your babelrc & the versions you're using? And the error message you're getting.

That should work.

**Comment by DrewML** [comment]
(Separate from the issue, but) it's also worth noting that the code you supplied can be a bit problematic in React. You're basically "forking" the state, but only on the initial construction of the component. If a parent component were to pass down a different value for `someProp` after the initial render, `someState` would not be updated. This is mentioned in the React docs [here](https://facebook.github.io/react/docs/react-component.html#constructor).

**Comment by baibing** [comment]
babelrc
{
  "presets": ["es2015", "stage-2", "react"],
  "plugins": ["react-require", "babel-root-slash-import", "transform-export-extensions", "antd"]
}

dependency versions:
$ meteor npm list | grep -e "^├─┬ babel"
├─┬ babel-core@6.18.0
├─┬ babel-plugin-transform-export-extensions@6.8.0
├─┬ babel-polyfill@6.16.0
├─┬ babel-preset-es2015@6.18.0
├─┬ babel-preset-react@6.16.0
├─┬ babel-preset-stage-2@6.18.0
├─┬ babel-root-slash-import@1.1.0

The error message is just NPE exceptions as this.props is undefined

**Comment by baibing** [comment]
@DrewML Thanks for pointing that out. We're trying to avoid initializing states with props as possible as we can, but we do have some rare cases that this is the simplest way to implement.

**Comment by DrewML** [comment]
The output I get with `es2015`, `stage-2`, and `react` presets is:

```javascript
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var View = function (_React$Component) {
  _inherits(View, _React$Component);

  function View() {
    var _ref;

    var _temp, _this, _ret;

    _classCallCheck(this, View);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = View.__proto__ || Object.getPrototypeOf(View)).call.apply(_ref, [this].concat(args))), _this), _this.state = {
      someState: _this.props.someProp
    }, _temp), _possibleConstructorReturn(_this, _ret);
  }

  return View;
}(React.Component);
```

Reading through it, it looks to me like it's transforming correctly, but it's always a bit hard to tell for things like this just trying to decipher it visually. That code _is_ invoking the constructor prior to the access of `this.props`, though, and React should be setting `this.props` in the parent.

Can you create a minimal sample project that can be used to replicate the issue?

**Comment by aaronang** [comment]
Hope you don't mind, but I am closing this issue due to long period of inactivity. If this issue remains unsolved, please provide an example repository that is able to reproduce the problem, or join our [Slack channel](https://slack.babeljs.io) for faster communication.
