### ISSUE TITLE
babel-plugin-transform-es2015-block-scoping@6.18.0 is very slow

### ISSUE THREAD

**Issue by rasom** [babel/babel#4795]
We are experiencing that `babel-plugin-transform-es2015-block-scoping@6.18.0` causes `TimeoutError` error when we are trying to generate release build of `react-native` project (https://github.com/status-im/status-react). 

As far as I can say this [line](https://github.com/babel/babel/commit/7a7704fea02d7e839fe412459730735bb64f1503#diff-775ae6452de339480d54604c7d217b5dL494) is the reason for the trouble. So changing of

``` js
let declarPath = this.blockPath.get("body")[i];
```

to

``` js
let declar = block.body[i];
```

fixes it.

We are totally fine with [`babel-plugin-transform-es2015-block-scoping@6.15.0`](https://github.com/status-im/status-react/commit/fc274a5e525288beea9e70e64117a5980c03b219), but maybe this information will be helpful for someone.

**Comment by aaronang** [comment]
Closing this issue due to long period of inactivity. If this issue remains troublesome, please provide an example repository that is able to reproduce the problem, or join our [Slack channel](https://slack.babeljs.io) for faster communication.
