### ISSUE TITLE
Implement Template Literals Revision proposal

### ISSUE THREAD

**Issue by TimothyGu** [babel/babel#4798]
The [Template Literals Revision](https://tc39.github.io/proposal-template-literal-revision/) proposal reached Stage 3 in July, but is not yet implemented.
### Input Code

Example derived from the proposal linked above.

``` js
function tag(strs) {
  assert(strs[0] === undefined);
  assert(strs.raw[0] === "\\unicode and \\u{55}");
}
tag`\unicode and \u{55}`;
```
### Expected Behavior

The above code should execute without throwing any error.
### Current Behavior

An [error](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Clatest%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&code=function%20tag%28strs%29%20%7B%0A%20%20assert%28strs%5B0%5D%20%3D%3D%3D%20undefined%29%3B%0A%20%20assert%28strs.raw%5B0%5D%20%3D%3D%3D%20%22%5C%5Cunicode%20and%20%5C%5Cu%7B55%7D%22%29%3B%0A%7D%0Atag%60%5Cunicode%20and%20%5Cu%7B55%7D%60%3B) is currently thrown by Babylon:

```
repl: Bad character escape sequence (5:6)
  3 |   assert(strs.raw[0] === "\\unicode and \\u{55}");
  4 | }
> 5 | tag`\unicode and \u{55}`;
    |  
```
### Possible Solution

First step would of course be adding support for it in Babylon.

Currently, the babel-plugin-transform-es2015-template-literals plugin transforms

``` js
tag`ab\\c`;
```

to

``` js
var _templateObject = _taggedTemplateLiteral(["ab\\c"], ["ab\\\\c"]);

function _taggedTemplateLiteral(strings, raw) {
  return Object.freeze(Object.defineProperties(strings, {
    raw: {
      value: Object.freeze(raw)
    }
  }));
}

tag(_templateObject);
```

To support this new syntax it could just convert

``` js
tag`\unicode and \u{55}`;
```

to

``` js
var _templateObject = _taggedTemplateLiteral([], ["\\unicode and \\u{55}"]);

function _taggedTemplateLiteral(strings, raw) {
  return Object.freeze(Object.defineProperties(strings, {
    raw: {
      value: Object.freeze(raw)
    }
  }));
}

tag(_templateObject);
```

**Comment by bakkot** [comment]
I'm interested in working on this. I expect I'll have a progress update or PR (at least to Babylon) within a week or so.

**Comment by hzoo** [comment]
Alright cool @bakkot, can join our slack if you haven't already if you need help with contributing and the process, etc

**Comment by hzoo** [comment]
Done in https://github.com/babel/babylon/pull/274.

Updating Babel in https://github.com/babel/babel/pull/5522, need to add the transform tests/changes

**Comment by hzoo** [comment]
@babel-bot move to babel
