### ISSUE TITLE
Plugin options via CLI subarg are not working (anymore?)

### ISSUE THREAD

**Issue by yvele** [babel/babel#4800]
Using `babel-cli@6.18.0` (with node v6) on Mac OSX:

```bash
babel ./src \
  --out-dir ./lib \
  --plugins [ babel-plugin-istanbul --all ]
```

Gives the following error:

> babel-plugin-istanbul doesn't exist

I found [no documentation](https://babeljs.io/docs/usage/cli/) about how to pass plugin options via cli but I found that:

- @kittens says that CLI have subarg for plugin options https://github.com/babel/babel/issues/1833#issuecomment-115695748
- Subarg was implemented in 2014 https://github.com/babel/babelify/issues/8 PR: https://github.com/babel/babelify/pull/9

Subarg seams broken.

-----

It would also be nice to add some documentation about subarg like [browserify](https://github.com/substack/node-browserify):

Passing arguments to transforms and plugins:

```text
  For -t, -g, and -p, you may use subarg syntax to pass options to the
  transforms or plugin function as the second parameter. For example:

    -t [ foo -x 3 --beep ]

  will call the `foo` transform for each applicable file by calling:

    foo(file, { x: 3, beep: true })
```

**Comment by Jokero** [comment]
@hzoo ping

**Comment by hzoo** [comment]
I'm not sure it might of gotten removed or changed (as a bug) in 6.0. I feel like if you are going to start using plugins + options the best you can do is to create a `.babelrc` or add `"babel": {}` to your package.json for now. You can use `babelrc: false` to make it not inherit or find any other configs.

**Comment by moimael** [comment]
@hzoo There are still cases where you cannot use .babelrc for example in the case of our isomorphic app, we have webpack + babel with .babelrc fro the client side, and command line babel for the server side, because we have a shared component directory and both need to process it differently, since they have different ES6/7 support (node vs the browser).

**Comment by pavel06081991** [comment]
@hzoo, have the same issue. Are you planning maybe to add opportunity to use two or more babelrc. config files?

**Comment by hzoo** [comment]
You can already use a js file that reads `process.env` via relative path config: `{ "presets": ["./file"] }` or in Babel 7 with .babelrc.js

Going to close unless some has time to make a PR to fix; babelrc is meant to cover complicated cases that are not just simply using a few presets/plugins.
