### ISSUE TITLE
custom quotes option is broken down

### ISSUE THREAD

**Issue by e-cloud** [babel/babel#4803]
### Input Code

```js
const aStr = "hi";
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "generatorOpts": {
    "quotes": "single"
  }
}
```

### Expected Behavior
```js
const aStr = 'hi';
```

### Current Behavior
```js
const aStr = "hi";
```

### Context

https://github.com/babel/babel/commit/528128f62d949edca0a564e8641d85ef3a8032cf#commitcomment-19483379

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             | 6.9.1
| npm              | 3.10.8
| Operating System | ubuntu 16.10

**Comment by hzoo** [comment]
Closing this via https://github.com/babel/babel/issues/5154 - in order to fix this were going to drop quotes in 7.0 given it has been broken for a while and we don't really want to support custom options for compiled output (quotes, tabs, spaces, etc).
