### ISSUE TITLE
tarball releases each modules 

### ISSUE THREAD

**Issue by lucascastro** [babel/babel#4809]
Would it be a good idea release one tarball for each modules? 
I'm planning to package these modules for Debian GNU/Linux, and the tarball is released with a version but not all modules are that version.  So there's no how to check when a modules really has a new version. 

--
Lucas Castro 
lucas@gnuabordo.com.br

**Comment by hzoo** [comment]
Not sure how we want to do that since most users just use npm? Not sure about how it would work - at least with the packages you can check packages/packge_name/package.json?

**Comment by lucascastro** [comment]
So, debian has robot to check for new version and then, the maintainer is notified about new version. 

But it'd be a good idea to maintain together with a distribution maintenance, so the it'll be easy to support software that depends on babel modules in distributions releases and maintenance. 

That's is just a hint from packagers, 
it'd be easier to check for updates, auto download and package.

**Comment by hzoo** [comment]
You can download the tar from npm directly - if you want all the packages you can run:

```bash
for package in packages/babel-* ; do npm view `basename $package` dist.tarball ; done
```

Example is `https://registry.npmjs.org/babel-cli/-/babel-cli-6.18.0.tgz`

**Comment by DrewML** [comment]
It seems like this has a solution based on @hzoo's comment. Closing this, but let us know if this isn't feasible @lucascastro.

**Comment by lucascastro** [comment]
that doesn't really solve.
I'll try to attempt in another way, it'll be really hard to check a new uptream version to update debian repositories. 

what @hzoo did, he already had the package. "for package in packages/babel-"

keep in mind that is not me who will check if it was released a new version [1].

[1] https://wiki.debian.org/debian/watch.

hints for uptream. 
https://wiki.debian.org/UpstreamGuide

**Comment by xtuc** [comment]
GitHub's releases or NPM are already providing tarballs, closing for now.
