### ISSUE TITLE
Anonymous arrays are used as index of previous variable if not preceded by a semicolon

### ISSUE THREAD

**Issue by thetylerwolf** [babel/babel#4810]
### Input Code

```js
var a = 1, b = 2, c = 3
[ a, b, c ].map(function() {...})
```

will cause an error. The code will transpile to:

```js
var a = 1, b = 2, c = 3[( a, b, c )].map(function() {...})
```

### Babel Configuration (.babelrc, package.json, cli command)

Webpack babel-loader
```js
module: {
            loaders: [
                { 
                  loader: 'babel-loader',
                  query: {
                    presets: ['es2015']
                  },
                  exclude: /node_modules/
              }
            ]
        }
```

### Expected Behavior
If there is a new line between a variable and a square bracket, treat the square bracket as an array being instantiated.

### Current Behavior

This will happen any time a semicolon is not used and it is proceeded by an anonymous array definition, even if the array is on a newline. This also produces an error when done in regular javascript, but babel will surround the array terms in parens, indicating this is intended behavior.

### Possible Solution
Adjustments to parsing. Maybe a configurable behavior.

### Context
One must make sure I use semicolons before instantiating an anonymous array. Not a major issue, but it can cause unintended bugs.

**Comment by hzoo** [comment]
That's just the way it's parsed though? it doesn't take into account whitespace or newlines etc

**Comment by loganfsmyth** [comment]
Yeah, this is standard ASI behavior and you'd see the same behavior in Chrome or Node6. You need a semicolon at the end of that line.

**Comment by hzoo** [comment]
> This also produces an error when done in regular javascript

Right you can also use a linter to make sure you have semicolons, etc http://eslint.org/docs/rules/semi - babel isn't going to know based on a newline. And what about minified code (you would have to have a semicolon)
