### ISSUE TITLE
arrow functions this works different than chrome & firefox

### ISSUE THREAD

**Issue by ducin** [babel/babel#4814]
### Input Code

I think there is something wrong, or maybe misleading, in how babel transpiles ES6 down to ES5. Look at the code below:

```js
var name = "MyName";
var version = "1.2.3";

var theThing = {
    name,
    version,
    run: () => {
        console.log(`You're using ${this.name}@${this.version}`);
    }
};

theThing.run();
```

Note the arrow function `run`, the issue relates to arrows reusing lexical this (arrows don't have their own `this` but use enclosing, *lexical* scope).

### Expected Behavior

I'd expect browsers and babel to work exactly the same way. And they don't.

The problem here is that in future, when babel ES6 -> ES5 is not needed anymore (all browsers implement entire ES6) and we switch from babel to native ES6 in browsers, we might get our ES6 code unexpectedly broken.

### Current Behavior

Chrome and Firefox output this:

    You're using MyName@1.2.3

![image](https://cloud.githubusercontent.com/assets/375027/20034261/2c172356-a3b7-11e6-9e7d-e7020427ae22.png)

However, babel throws this:

    VM121:10 Uncaught TypeError: Cannot read property 'name' of undefined

And that's because babel generates different code (see [babel.io/repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2017&experimental=false&loose=false&spec=false&playground=true&code=var%20name%20%3D%20%22MyName%22%3B%0D%0Avar%20version%20%3D%20%221.2.3%22%3B%0D%0A%0D%0Avar%20theThing%20%3D%20%7B%0D%0A%20%20%20%20name%2C%0D%0A%20%20%20%20version%2C%0D%0A%20%20%20%20run%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%60You're%20using%20%24%7Bthis.name%7D%40%24%7Bthis.version%7D%60)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%3B%0D%0A%0D%0AtheThing.run()%3B%0D%0A)):

```js
"use strict";

var name = "MyName";
var version = "1.2.3";

var theThing = {
    name: name,
    version: version,
    run: function run() {
        console.log("You're using " + undefined.name + "@" + undefined.version);
    }
};

theThing.run();
```

### Possible Solution

The global scope is a scope afterall, so an arrow function, that does not have it's own scope - and should reuse enclosing scope - should use global scope. It seems that browsers work this way. And babel - at least in this case, doesn't.

### Your Environment

I'm using latest chrome and latest firefox. Executing above code both in chrome devtools console & babel.io/repl.

**Comment by loganfsmyth** [comment]
You can use 

    presets: [
        ['es2015', {modules: false}],
    ]

instead of what you probably have now:

    presets: [
        'es2015',
    ]

to disable this treatment of `this`, but the default is to assume that the code being processed is modular code, and thus `var name` is module-scoped, not global-scoped.

**Comment by ducin** [comment]
@loganfsmyth thanks for your reply. So I guess this is not a bug, but expected behavior and the difference is ES6 is executed in global-scope (as I experienced in browsers) VS module-scoped (default babel). Is my understanding correct?

Could you please write any topic I could read about (or an article link perhaps) to get a better understanding of the topic?

**Comment by loganfsmyth** [comment]
I'm not sure I have a ton more I can add. Babel essentially assumes you'll be taking its output and bundling it with Browserify or Webpack by default, since that is the most common workflow. Not many people take Babel's output and run it directly in the browser, because most of the time codebases are big enough that you really want modular code.

**Comment by ducin** [comment]
thanks for the explanation @loganfsmyth
