### ISSUE TITLE
flow-strip-types should throw syntax error when annotations are in illegal positions

### ISSUE THREAD

**Issue by disnet** [babel/babel#4816]
### Input Code
```js
f(p: [])
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    "transform-flow-strip-types"
  ]
}
```

### Expected Behavior

Should throw a syntax error at the `:` since that is not a valid type annotation.

### Current Behavior

Outputs:

```js
f(p);
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.18.0
|  babel-plugin-transform-flow-strip-types |  6.18.0

**Comment by hzoo** [comment]
Thanks for the report @disnet! If we want a syntax error this would be a change to the parser (babylon - https://github.com/babel/babylon) not necessarily the plugin since it just strips the types.

**Comment by disnet** [comment]
Cool! Should I open an issue on babylon's repo then?

ps I do get a syntax error in babel if I just use the es2015 preset (or various other non-flow plugins). I'm guessing this plugin runs babylon in some kind of "flow mode"?

**Comment by hzoo** [comment]
Yep would be better in babylon - https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-flow-strip-types/src/index.js#L5 turns on the flow plugin in the parser which are https://github.com/babel/babylon#plugins

**Comment by disnet** [comment]
Thanks will do!

**Comment by michaelficarra** [comment]
ref: https://github.com/babel/babylon/issues/215
