### ISSUE TITLE
Setting env presets es2015 do not work

### ISSUE THREAD

**Issue by dalphyx** [babel/babel#4817]
### Babel Configuration (.babelrc, package.json, cli command)
```
{
  "presets": [
    ["es2015", { "loose": true }]
  ],
  "env": {
    "ava": {
      "presets": [
        ["es2015", { "modules": false }]
      ]
    }
  }
}
```

### Expected Behavior
When run babel with env ava, it's should not compile es2015 module code.

### Current Behavior
Compile es2015 module into commonjs.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             |  7.0
| Operating System | Mac 10.11

**Comment by hzoo** [comment]
http://babeljs.io/docs/usage/babelrc/#env-option

Ah yeah the presets without env are still all run so it still compiles to cjs. You would need to remove the presets from the top level option

```
{
  "env": {
    "prod": {
      "presets": [
        ["es2015", { "loose": true }]
      ],
     },
     "ava": {
      "presets": [
        ["es2015", { "modules": false }]
      ]
    }
  }
}
```
