### ISSUE TITLE
Can't disable strict mode

### ISSUE THREAD

**Issue by Janjuks** [babel/babel#4819]
I want to use babel in my gulp file so that it transform arrow functions before uglifying js.
Some of the code is not in strict mode so I want to disable it. I'v been back and forth between all the issues I could find, but none of them work for me.

The latest information I could find was that my config should look like this: 

```js
.pipe(babel({
    presets: ['es2015', { loose: true, modules: false }],
    plugins: ["transform-es2015-arrow-functions"]
}))
```

package.json: 

```js
{
  "babel": "^6.5.2",
    "babel-core": "^6.9.1",
    "babel-plugin-transform-es2015-arrow-functions": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-register": "^6.9.0",
}
```
When I provide preset options, I get error `Using removed Babel 5 option: foreign.loose - Specify the 'loose' option for the relevant plugin you are using or use a preset that sets the option.`

Tried specifying it to the arrow plugin: 
```js
plugins: [["transform-es2015-arrow-functions", { loose: true, modules: false }]]
```

Then I get error `Binding arguments in strict mode (17:54)` which also happens if I don't specify those options anywhere at all.

| software         | version
| ---------------- | -------
 Babel             |  ^6.5.2
 node             | v6.3.0
 npm              | 3.9.3
 Operating System | Win 10

**Comment by hzoo** [comment]
Presets is an array of presets - if you don't wrap the options with the preset then it will seem like the 2nd argument is also a preset

```
presets: ['es2015', { loose: true, modules: false }],
```

```
presets: [['es2015', { loose: true, modules: false }]],
```

**Comment by Janjuks** [comment]
I get the same `Binding arguments in strict mode (17:54)` error

**Comment by DrewML** [comment]
I'm not able to replicate the injection of the `use strict;` pragma with the following code/config:

**.babelrc**:
```json
{
    "presets": [
        ["es2015", { "modules": false }]
    ]
}
```

**index.js**:
```javascript
const foo = () => 'a';
```

**Output**:
```js
var foo = function foo() {
  return 'a';
};
```

To clarify, are you seeing that exception thrown in your code when you run it in the browser, or are you seeing that error when running `Gulp`?

**Comment by Janjuks** [comment]
I see that error when running Gulp

**Comment by xtuc** [comment]
Do you have still this issue ?

You could use the preset [babel-preset-es2015-without-strict](https://github.com/fancyboynet/babel-preset-es2015-without-strict)

**Comment by Janjuks** [comment]
I have moved on from this issue, but I tried your suggestion and got the same error: `Binding arguments in strict mode`. I will give this issue a deeper investigation from my side when I will have time as it seems that I'm the only one having this issue. Thanks!

**Comment by PuKoren** [comment]
I am also unable to disable strict mode, when using plugin `transform-es2015-modules-commonjs`

```json
{
    "plugins": [
        ["transform-es2015-modules-commonjs", {
          "strict": false
        }]
    ]
}
```

Is someone experiencing the same issue?

**Comment by loganfsmyth** [comment]
@PuKoren My recommendation at this point would be `"strictMode": false` but I wouldn't expect that to fix if it it already isn't working. You haven't really given enough info to help you though. What specifically are you seeing?

**Comment by PuKoren** [comment]
It is reporting errors on submodules, using strict mode for the whole project.
I use babel using `babel-register`, this may be the cause. I tried `strictMode` and I have the same issue

**Comment by loganfsmyth** [comment]
Generally when using `babel-register` you'll want to pass it `ignore: /node_modules/` so that it does not process any of your dependencies.

**Comment by aaronang** [comment]
Does this issue still remain a problem?

**Comment by Janjuks** [comment]
Hadn't touched this issue. I just tested with simple example and it worked fine.
