### ISSUE TITLE
Object.assign cannot be transformed correctly if using Object.assign by assign it to a variable.

### ISSUE THREAD

**Issue by NextSeason** [babel/babel#4822]
### Input Code

```js
const assign = Object.assign;
assign( {}, {} ); // this assign won't be transformed
```

**Comment by hzoo** [comment]
> Object.assign cannot be transformed

I assume you mean using babel-plugin-transform-object-assign since most would use the polyfill.

Right it's because it only runs on a CallExpression atm https://github.com/babel/babel/blob/e6901792a1951966efb5100a58a1645fab9ebb65/packages/babel-plugin-transform-object-assign/src/index.js#L4

**Comment by DrewML** [comment]
Opened a PR to add this caveat to the docs: https://github.com/babel/babel.github.io/pull/991

**Comment by DrewML** [comment]
Caveat now in the docs.
