### ISSUE TITLE
Rest parameters are empty when debugging function

### ISSUE THREAD

**Issue by ackerdev** [babel/babel#4823]
How to reproduce:
```javascript
function foo(...args) {
  debugger;
}

foo(1,2,3);
```

While in the debugger, args will be empty, as the transpilation builds the `args` collection inline when it is first referenced. Even when args is referenced in the function, if the debugger occurs before the statement referencing the rest parameters, it will be empty.

Can potentially cause some unexpected behavior when debugging.

**Comment by loganfsmyth** [comment]
I can explain why this is currently happening. We had a request to avoid initializing the `args` array on branches where it wasn't used, e.g.

```
function doThing(someParam, ...args) {
  if (someParam === "foo") {
    return args;
  }
  return [];
}
```
so to optimize the code if _most_ of the time the `if` doesn't run, it's a waist of time to initialize the `args` array and then throw it away, so we optimized it to only create `args` at the first location it is used in the function. This unfortunately means that `args` doesn't exist yet for the debugger to access.

Not sure what the right call in this case would be.

**Comment by xtuc** [comment]
Closing, out of scope for now.
