### ISSUE TITLE
transformFromAst loses mappings on rerun

### ISSUE THREAD

**Issue by sebdeckers** [babel/babel#4824]
### Input Code

```js
const {parse} = require('babylon')
const {transform, transformFromAst} = require('babel-core')

const opts = {babelrc: false, sourceMaps: true, minified: true}

const raw = '\nthis'
const ast = parse(raw)

// Fail: transformFromAst --------------------------------

const trAst1 = transformFromAst(ast, raw, Object.assign({inputSourceMap: null}, opts))
console.dir(trAst1.map.mappings) // 'AACA'

const trAst2 = transformFromAst(trAst1.ast, trAst1.code, Object.assign({inputSourceMap: trAst1.map}, opts))
console.dir(trAst2.map.mappings) // ''

// Okay: transform --------------------------------

const trStr1 = transform(raw, Object.assign({inputSourceMap: null}, opts))
console.dir(trStr1.map.mappings) // 'AACA'

const trStr2 = transform(trStr1.code, Object.assign({inputSourceMap: trStr1.map}, opts))
console.dir(trStr2.map.mappings) // 'AACA'
```

### Babel Configuration (.babelrc, package.json, cli command)
As per code above, no other `.babelrc` is used. No babel field in package.json either. Run code sample in plain `node` (REPL).

Demo repo at:
https://gitlab.com/sebdeckers/demo-babel-ast-sourcemaps

### Expected Behavior
The second call to `transformFromAst` should return a `map.mappings` field.

### Current Behavior
Iterative calls to `transform` are fine but `transformFromAst` loses the sourcemap's `map.mappings` property.

This happens with a leading newline, but also with a leading comment if `comments: true` (a very common case). The leading newline triggers it regardless of the `comments` option value.

E.g. both of these lose the `mappings` in the second pass through `transformFromAst` (but not with regular `transform`).
```js
const opts = {babelrc: false, sourceMaps: true, minified: true}
const raw = '\nthis'
```

```js
const opts = {babelrc: false, sourceMaps: true, minified: true, comments: false}
const raw = '//\nthis'
```

### Possible Solution
Use `transform` (slower), or use `minified: false, comments: true` (larger output).

### Context
Some plugins require multiple passes due to the way in which they parse the tree. E.g. `'transform-node-env-inline` must run before `minify-dead-code-elimination` (because `NODE_ENV` is substituted *after* removing dead code). This bug is causing sourcemaps to be lost.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.18.2
| babylon        | 6.13.1
| node             | 7.0.0
| npm              | 4.0.1
| Operating System | macOS Sierra 10.12.1

**Comment by edoardocavazza** [comment]
Any update on this? I am verifying the same behavior with `@babel/standalone` v7.0.0-beta.34

**Comment by loganfsmyth** [comment]
The second run should be more like
```
const trAst2 = transformFromAst(trAst1.ast, code, opts)
```

The location data in `trAst1.ast` still reflects the locations from `code`, not `trAst1.code`. Similarly, an input sourcemap corresponds with `code` so since there's no input map on the first call, there shouldn't be one on the second either.
