### ISSUE TITLE
Validate babel-cli program options

### ISSUE THREAD

**Issue by gajus** [babel/babel#4825]
It is frustrating that `babel-cli` program does not validate options that are passed to it, e.g.

```sh
babel ./src --out-dir ./dist --copy-files --spurce-maps
```

This will run the program without any error (note the spelling error in `--spurce-maps`; the intetended value is `--source-maps`).

Ideally, a CLI program should throw an error whenever an unknown property/ value is passed to it.

As far as I can tell, https://github.com/tj/commander.js does not support "strict" options parameter (like [yargs#strict](https://github.com/yargs/yargs#strict)). Therefore, this could be achieved by:

* switching the implementation to yargs; or
* implementing JSON schema validation of the options object

**Comment by sudo-suhas** [comment]
I would like to work on this. I am leaning towards switching to `yargs`. Any pointers would be appreciated. Would be my first PR to babel.

**Comment by mattt416** [comment]
I use commander in a personal project and recalled seeing different behaviour.  Sure enough:

```
$ ~/node_modules/.bin/babel script.js --out-dir ./dist --copy-files --spurce-maps
script.js -> dist/script.js
$ ~/node_modules/.bin/babel --spurce-maps

  error: unknown option `--spurce-maps'

$
```

It looks to only be an issue when you pass in an argument (`script.js` in the above example).  A quick search in commander's issue tracker returned a [bug](https://github.com/tj/commander.js/issues/561) for this specific issue.

**Comment by jridgewell** [comment]
That looks to be the cause, thanks for the investigation!
