### ISSUE TITLE
es2015-modules-amd and es2015-modules-systemjs conflict with each other and generate invalid modules

### ISSUE THREAD

**Issue by cristiingineru** [babel/babel#4828]
Every generated AMD or SystemJS modules are nested in a define([], ...) call making them unusable. For example: https://github.com/cristiingineru/rabbit/blob/amdIssue/build/amd/rabbit.js

### Babel Configuration (.babelrc, package.json, cli command)
.babelrc content:
{
  "presets": ["es2015"],
  "plugins": ["transform-es2015-modules-amd"]
}

package.json entries related to Babel:
    "babel-cli": "^6.18.0",
    "babel-plugin-transform-es2015-modules-amd": "^6.18.0",
    "babel-plugin-transform-es2015-modules-systemjs": "^6.18.0",
    "babel-preset-es2015": "^6.18.0",
    "karma-babel-preprocessor": "^6.0.1",
    "requirejs-babel": "0.0.9"

### Expected Behavior
When running Babel from the command line with the following commands:
babel src -d build/amd --presets=es2015 --plugins=transform-es2015-modules-amd
babel src -d build/systemjs --presets=es2015 --plugins=transform-es2015-modules-systemjs

I'm expecting it to generate valid AMD modules:
define(['exports', 'dep1', 'dep2'], function (exports, _dep1, _dep2) {
  // ...
});

and valid SystemJS modules:
System.register(['dep1', 'dep2'], function (_export, _context) {
  // ...
});

### Current Behavior
The generated AMD modules are nested in a define([], ...) call like this:
**define([], function () {**
   define(['exports', 'dep1', 'dep2'], function (exports, _dep1, _dep2) {
    // ...
  });
**});**

The generated SystemJS modules are nested in a define([], ...) call like this:
**define([], function () {**
   System.register(['dep1', 'dep2'], function (_export, _context) {
    // ...
  });
**});**

### Possible Solution
Workarounds:
* Delete the .babelrc file
* or remove the -es2015-modules-amd plugin from the .babelrc file
* use the --no-babelrc option

### Context
The goal is to distribute the AMD and SystemJS versions of the same modules. At this point it's no longer a showstopper since I there are multiple workarounds.

### Your Environment
Here is a branch created to reproduce this issue: https://github.com/cristiingineru/rabbit/commits/amdIssue

**Comment by DrewML** [comment]
This is working as intended. The `modules-amd` and `modules-systemjs` plugins are not designed to be run together. They both are going to make the assumption that they are the only module transform being run. If you need separate distributions for a library, you should be running a separate build for each.
