### ISSUE TITLE
babel-runtime/helpers/typeof requires itself - again

### ISSUE THREAD

**Issue by sheerun** [babel/babel#4829]
This issue happens again, in babel-runtime 6.11.6 when using rollup.

This is `rollup.config.js` to reproduce:

```js
import json from 'rollup-plugin-json';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'node_modules/babel-runtime/helpers/typeof.js',
  format: 'cjs',
  plugins: [
    json(),
    babel({ runtimeHelpers: true }),
    nodeResolve({ jsnext: true, main: true }),
    commonjs()
  ],
  dest: 'bundle.js'
};
```

Related: #3711, https://github.com/rollup/rollup-plugin-babel/issues/97

**Comment by tjclement** [comment]
This same issue also happens when transpiling a JSPM (0.17.0-beta.22) project with babel and rollup. Haven't been able to figure out why, so far.

**Comment by mfirmin** [comment]
I was running into the same problem, and spent most of yesterday trying to fix it.

Turns out, if you just add `exclude: 'node_modules/**'` (or in my case, make sure the path is correct...) to the babel plugin in your rollup config, it works perfectly:

```javascript
import json from 'rollup-plugin-json';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'node_modules/babel-runtime/helpers/typeof.js',
  format: 'cjs',
  plugins: [
    json(),
    babel({ runtimeHelpers: true, exclude: 'node_modules/**' }),
    nodeResolve({ jsnext: true, main: true }),
    commonjs()
  ],
  dest: 'bundle.js'
};
```

**Comment by chicoxyzzy** [comment]
Seems like this issue is related to `rollup-plugin-babel`, not Babel

**Comment by bdwain** [comment]
@chicoxyzzy  running `babel-external-helpers -t umd > es/babel-external-helpers.js` gives me a file that can't run in the browser. the error is babelHelpers.typeof is not a function. 

This seems to be the problematic code (at the very beginning of the function)

```js
  var babelHelpers = global;
  babelHelpers.typeof = typeof Symbol === "function" && babelHelpers.typeof(Symbol.iterator) === "symbol" ? function (obj) {
    return typeof obj === "undefined" ? "undefined" : babelHelpers.typeof(obj);
  } : function (obj) {
    return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj === "undefined" ? "undefined" : babelHelpers.typeof(obj);
  };

```

**Comment by loganfsmyth** [comment]
`babel-external-helpers` works on 7.x branch at least. Closing this otherwise since it does not seem like a babel issue. Compiling the helpers to reference themselves will indeed cause issues.
