### ISSUE TITLE
Flow plugin produces syntax array for nested arrays 

### ISSUE THREAD

**Issue by bxt** [babel/babel#4831]
Using the plugin [`babel-plugin-transform-flow-strip-types`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-flow-strip-types) this produces an error:

```js
const foo: number[][] = [[]];
```

I get `SyntaxError: /tmp/index.js: Unexpected token (1:19) while parsing file: /tmp/index.js`.

This works perfectly fine:

```js
const foo: Array<number[]> = [[]];
```

Flow parses both of them just fine, as you [can see here](https://flowtype.org/try/#0MYewdgzgLgBAZiEAuGYCuBbARgUwE4DaAusTALwwHFEDcAUHaJLFgIZ4oCCeerAngB502fMQB85StXpA).

### Babel Configuration (.babelrc, package.json, cli command)

`.babelrc`:

```js
{ "presets": ["es2015"], "plugins": ["transform-flow-strip-types"] }
```

`package.json`:

```js
{
  "main": "index.js",
  "dependencies": {
    "babel-cli": "^6.18.0"
  },
  "devDependencies": {
    "babel-plugin-transform-flow-strip-types": "^6.18.0",
    "babel-preset-es2015": "^6.18.0"
  },
  "scripts": {
    "start": "babel index.js --out-file index-compiled.js"
  }
}
```

cli command:

```
npm start
````

### Expected Behavior

No error and removes type declaration.

### Current Behavior

Various syntax errors depending on where in the code you use `type[][]`.

### Context

When using babel to strip the types form [flow](https://flowtype.org)-checked files.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0 (babel-core 6.18.2)
| node             | v7.1.0
| npm              | 4.0.2
| babel-plugin-transform-flow-strip-types | 6.18.0
| Operating System | macOS Sierra 10.12.1 (16B2555)

**Comment by hzoo** [comment]
You can make the issue in https://github.com/babel/babylon (the parser) - sounds like we just don't know how to to parse it correctly. Thanks!

**Comment by bxt** [comment]
I opened this as babel/babylon#217
