### ISSUE TITLE
Different transforms and output when using transformFileSync vs. transform

### ISSUE THREAD

**Issue by diervo** [babel/babel#4833]
### Problem

I have a plugin that does a simple transformation in JSX (attribute => arrow function).
When running it via `tranform()`  API the output is correct, if I use `transformFileSync` some of the transforms are overridden.

Specifically `t.arrowFunctionExpression` gets re-transformed to a regular function.

### CLI command:
`babel-node src/index.js`:

### Input Code

```javascript
import * as babel from 'babel-core';
import * as fs from 'fs';

const testFile = 'test/fixtures/template/actual.html';
const src = fs.readFileSync(testFile).toString();

const result1 = babel.transformFileSync(testFile, {
    plugins: [
        'babel-plugin-transform-my-plugin'
    ]
});

const result2 = babel.transform(src, {
    plugins: [
        'babel-plugin-transform-my-plugin'
    ]
});

console.log('R1: \n', result1.code);
console.log('R2: \n', result2.code);
```
### Source to transform:

```
<template>
   <section>
    <div class="my-list" x-for="(item, index) of items">
        {item}
    </div>
    </section>
</template>
```
### Output:

```
R1(transformFileSync):
 h(
    "section",
    null,
    [l(this.items, function (item, index) {
        return h(
            "div",
            { "class": "my-list" },
            [item]
        );
    })]
);
R2 (transform):
 h(
    "section",
    null,
    [l(this.items, (item, index) => {
        return h(
            "div",
            { "class": "my-list" },
            [item]
        );
    })]
);
```
**Note the difference in the function in Result2 is an arrow function (the right transform) and in Result1 is just a regular function.

### Context and some debugging:

I debugged a little bit and seems to be related to the fact that `transformFileSync` adds the `filename` option, which seems to enable a different codepath for `modules` and adds a bunch of plugins visitors (I guess the ones from .bashrc) apart from mine, that probably override somehow the AST later on.

### Expectations: 

Both APIs should produce the same final transform or at least I would like to know why they are different.

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["babel-preset-es2015-without-strict"],
  "plugins": [
        "transform-runtime",
        "transform-object-rest-spread"
  ],
  "ignore": ["node_modules"]
}
```

**Comment by DrewML** [comment]
It would be helpful if you could include the source to `babel-plugin-transform-my-plugin` here, so someone attempting to debug can quickly replicate.

**Comment by diervo** [comment]
Never mind, babel was defaulting to my babelrc file, which I wasn't expecting.
Adding `babelrc:false` fixed everything.
