### ISSUE TITLE
es2017 does not work with mocha

### ISSUE THREAD

**Issue by oprogramador** [babel/babel#4839]
Node version: 6.4.0
npm version: 3.10.3

In `package.json` I have:
```json
  "scripts": {
    "test": "mocha --compilers js:babel-core/register --recursive app/tests --timeout 5000"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.18.0",
    "babel-preset-es2017": "^6.16.0",
    "babel-register": "^6.18.0",
    "mocha": "^3.1.2",
```

.babelrc:
```json
{
  "presets": [
    "es2015",
    "es2017"
  ]
}
```

For the following line in a test:
```js
console.log(Object.entries({ foo: 22 }));
```
I obtain `TypeError: Object.entries is not a function`.

However when I run a script with `./node_modules/.bin/babel-node 1.js`, it works.

Additionally I don't know why when I type only es2017 (without es2015) in my `.babelrc`, the exports and imports do not work.

**Comment by hzoo** [comment]
babel itself usually only transforms syntax - you'll want to use an individual polyfill for something like Object.entries or babel-polyfill http://babeljs.io/#polyfill and  http://babeljs.io/docs/usage/polyfill/
