### ISSUE TITLE
when use require method to use babel-loader in js file

### ISSUE THREAD

**Issue by fromIRIS** [babel/babel#4841]
### Input Code

```js
require("!!./../../../../../plugins/node_modules/spon-weex-loader/lib/script.js!./../../../../../plugins/node_modules/babel-loader?presets[]=/Users/lvdada/.spon/plugins/node_modules/babel-preset-es2015&plugins[]=/Users/lvdada/.spon/plugins/node_modules/babel-plugin-transform-runtime&comments=false!./../../../../../plugins/node_modules/spon-weex-loader/lib/extract.js?index=0&type=scripts!./wxc-tabbar.we")
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true,
      "moduleName": "./dir/some"
    }]
  ]
}
```

### Expected Behavior

in my condition, i can not use webpack configuration, so i use the require method to use babel-loader, like what i show above. but i need specify the moduleName of the `transform-runtime`,  because i want to refrence anther babel-runtime folder. 

the question is how can i specify the `transform-runtime` in require way?

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

**Comment by DrewML** [comment]
@fromIRIS Can you attempt to clarify your question further, or provide an example repository and specify where you're having issues? It's not immediately clear from reading your report what the issue is, or whether it is a problem using Babel or Webpack.

**Comment by aaronang** [comment]
Closing this issue due to long period of inactivity. If this remains an issue, please provide an example repository that reproduces the problem, or join our [Slack channel](slack.babeljs.io) for faster back-and-forth support.
