### ISSUE TITLE
Is `transform-es2015-modules-commonjs` set top-level `this` to void in a file by design or not?

### ISSUE THREAD

**Issue by iamchenxin** [babel/babel#4845]
See [#9623](https://github.com/nodejs/node/issues/9623) in Nodejs.
The original behaviors of `this` is set to `{}`, which makes some one use `this` to export values.
and currently `transform-es2015-modules-commonjs` set `this` to `undefined`.

### Input Code
```js
console.log(this);
```

### Babel Configuration (.babelrc, package.json, cli command)
{
  "plugins": ["transform-es2015-modules-commonjs"]
}

### Current Behavior
The `this` in top-level of a file is set to `undefined`.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18
| node             |  7.10
| npm              |  3.10.9
| Operating System |  ubuntu

**Comment by hzoo** [comment]
Yeah with commonjs we assume the file is a module in strict mode - http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-

**Comment by iamchenxin** [comment]
@hzoo Thanks for your quick reply ~

**Comment by hzoo** [comment]
👍  closing

**Comment by gnimmelf** [comment]
I'm using the `es2015-riot` preset, and cannot get a top level `this`;
```
[require('babel-plugin-transform-es2015-modules-commonjs'), { "allowTopLevelThis": true, 'strict': false }],
```
I hope it's just the param names I got wrong, but suspect not. So any hint welcome. 

Cheers.
