### ISSUE TITLE
Object Rest Spread Expression - Missing semicolon

### ISSUE THREAD

**Issue by matthisk** [babel/babel#4855]
Babel can generate invalid syntax when given an object rest spread expression. The transformer does not output a semicolon on the line generated from this expression, which results in a syntax error when minified (using ``--compact true``). 

Weirdly the babel repl does output the code correctly [link](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015%2Cstage-2&code=(%7B%20%5BfieldName%5D%3A%20value%2C%20...rest%20%7D%20%3D%20values)%3B%0Alet%20error%3B%0A). I wasn't able to find out which configuration the Babel REPL uses to compare it to my own. It does however use the same version of Babel-Core.

### Input Code

Say that we have a 

```js
({ [fieldName]: value, ...rest } = values);
let error;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
babel --compact false --presets=es2015,stage-2 input.js
```

### Expected Behavior

```js
"use strict";

var _values = values;
value = _values[fieldName];
rest = _objectWithoutProperties(_values, [fieldName]); // <----- we need this semicolon

var error = void 0;
```

### Current Behavior

```js
"use strict";

var _values = values;
value = _values[fieldName];
rest = _objectWithoutProperties(_values, [fieldName]) // semicolon missing here

var error = void 0;
```

The above code parses correctly (because of ASI), however when babel is ran with ``--compact true`` the following code will be generated, which is invalid because the expression is followed immediately by the ``var`` keyword: 

```js
"use strict";function _objectWithoutProperties(obj,keys){var target={};for(var i in obj){if(keys.indexOf(i)>=0)continue;if(!Object.prototype.hasOwnProperty.call(obj,i))continue;target[i]=obj[i];}return target;}var _values=values;value=_values[fieldName];rest=_objectWithoutProperties(_values,[fieldName])var error=void 0;
```

### Possible Solution

Semicolon should always be appended at the end of this statement.

### Context

This piece of code is part of a webpack pipeline. The acorn parser (which parses Babel's output src) is unable to parse the syntax error described in the output above and thus fails.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.2
| node             |  6.7.0
| npm              |  3.10.3
| Operating System |  OS X 10.10.5

**Comment by hzoo** [comment]
Weird because if I do all those tests cases in unit tests alone it has the semicolon ☹️

**Comment by hzoo** [comment]
Ok the object rest transform in that case didn't change to a statement so the semicolon wasn't there. have a fix

**Comment by hzoo** [comment]
Ok fix in https://github.com/babel/babel/issues/4858
