### ISSUE TITLE
[Generate] ObjectTypeAnnotation without ObjectTypeProperty output miss a line break 

### ISSUE THREAD

**Issue by morlay** [babel/babel#4856]
```js
generate(
  t.typeAlias(
    t.identifier('T'),
    null,
    t.objectTypeAnnotation([], [
      t.objectTypeIndexer(
        t.identifier('key'),
        t.anyTypeAnnotation(),
        t.identifier('Test'),
      ),
    ]),
  )
).code;
```
Now output
```js
type T = { [key: any]: Test;
};
```
Expected Output
```
type T = { 
  [key: any]: Test;
};
```

| software         | version
| ---------------- | -------
| Babel            |  6.18.x
| node             |  7.1
| npm              |  3.9.x
| Operating System | MacOS

**Comment by hzoo** [comment]
Relevant code is https://github.com/babel/babel/blob/cd041541b8c0b1b486b77cfa9827bfdb653cf42e/packages/babel-generator/src/generators/flow.js#L270-L287
