### ISSUE TITLE
Array spread operator with an Array(n) in loose mode

### ISSUE THREAD

**Issue by kevinhikaruevans** [babel/babel#4859]
### Input Code

```js
var x = [...Array(3)];
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["es2015-loose", "react", "stage-1"],
    "plugins": [
        "add-module-exports"
    ],
    "env": {
      "development": {
        "plugins": [
          [
            "react-transform",
            {
              "transforms": [{
                "transform": "react-transform-hmr",
                "imports": ["react"],
                "locals": ["module"]
              }]
            }
          ]
        ]
      },
      "test": {},
      "production": {
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements"
        ]
      }
    }
}
```

### Expected Behavior
I'm expecting this to be equal to `[undefined, undefined, undefined]`, or an array of length 3 with each element as `undefined`.

Trying the expression in the Chrome debugger has it resulting in `[undefined, undefined, undefined]`.

![image](https://cloud.githubusercontent.com/assets/4730591/20402447/9d3dd270-acb1-11e6-9bba-ad90e209eed8.png)

### Current Behavior

It is being compiled to `[].concat(Array(3))`, which results in an array with length 3, `[undefined × 3]`

### Possible Solution
Maybe have it get transformed into: `Array.apply(null, Array(3))`? No idea.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  babel-core: 6.7.2
| node             | 6.3.0
| npm              | 3.10.6
| Operating System | win10

**Comment by hzoo** [comment]
`[...a]` in loose mode has issues - part of the caveats of loose https://github.com/babel/babel.github.io/issues/329

**Comment by hzoo** [comment]
If you want more spec compilant code, you'll need to not use loose mode in this case
