### ISSUE TITLE
"ENOENT: no such file or directory" error for none .js files

### ISSUE THREAD

**Issue by bkeetman** [babel/babel#4864]
Hey All,

I seem to run into an issue, not 100% sure it's mine because of missing configuration.

I build my code for production via these commands in my package.json

```
  "scripts": {
    "start": "npm run build && NODE_ENV=consul node ./build/index.js",
    "start:dev": "nodemon src/index.js --exec babel-node --legacy-watch",
    "clean": "rm -rf build && mkdir build",
    "build-server": "babel -d ./build ./src -s",
    "build": "npm run clean && npm run build-server"
  }
  ```
  
 When running `npm run start` the code get's build but I get the following error:
 
 ```
 fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/brian/dev/md/graphql/build/schema.graphql'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (/Users/brian/dev/md/graphql/build/index.js:34:31)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)    
 ```
 
 This seems to be caused by this line:
 ```
 const schemaFile = fs.readFileSync(path.join(__dirname, '/schema.graphql'));
 ```
 
 The file is in the same location as where this script is being executed.
 
 Seems the file is not copied to the build location, or at least the path is not changed to the actual location of the file.
 I know there are work arounds, converting the `.graphql` to a `.js` file that outputs the string, but isn't there a way to keep this file extension? So a way to readFiles from the correct location?

**Comment by bkeetman** [comment]
I seem to have found a solution by using:
https://www.npmjs.com/package/babel-plugin-static-fs

But I guess this is the way to go?

**Comment by danez** [comment]
How is your graphql schema generated? I'm not sure but this seems unrelated to babel, but rather to your build pipeline or to graphql. Why do you thin it is a babel issue?

**Comment by bkeetman** [comment]
As you can seen in the package.json example, I run a `npm run start` this builds the project into the build folder. When I execute this code it cannot find the `schema.graphql` file which is in my code base. This because the location where the code is executed is now `/build` and not `/src`. The `schema.graphql` file is not copied to the build folder, or the path is not changed (readFileSync expects an absolute patch and not a relative one) to the `/src/schema.graphql` file.

So the graphql file is not generated, it's part of my codebase, but it does not reference to it after a build. I am not sure wat is excepted to happen.. do I need to to specific hacks in my code to have babel working correctly, not really fond of that to be honest..

**Comment by danez** [comment]
In that case you might need to copy the schema from the src directory to the build directory. Babel is not resolving imports/requires or handles non js files by default.

babel-cli has an option to do that for you:

```
-D, --copy-files                     When compiling a directory copy over non-compilable files
```

So if you add `-D` to the call to babel it should copy the schema, though I have never used this option myself.

Let me know if it works.

**Comment by bkeetman** [comment]
Super! Seems to have done it, didn't see that flag. But indeed copying all files to the build folder seems a good solution.

So my new `package.json`

```
"scripts": {
    "start": "npm run build && NODE_ENV=consul node ./build/index.js",
    "start:dev": "nodemon src/index.js --exec babel-node --legacy-watch",
    "clean": "rm -rf build && mkdir build",
    "build-server": "babel -D -d ./build ./src -s",
    "build": "npm run clean && npm run build-server"
  }
  ```

Thanks!
