### ISSUE TITLE
Bug - decorator with computed name at end of class

### ISSUE THREAD

**Issue by arackaf** [babel/babel#4866]
It looks like Babel is erroring out when there's a decorated class property method as the last statement in a class.

```js
const mixin = options => Class => class sub extends Class {
    @action [options.foo] = () => true;
};
```

Which produces

> SyntaxError ......  You have trailing decorators with no method (68:1)

Adding a junk placeholder at the end fixes it, as a workaround

```js
const mixin = options => Class => class sub extends Class {
    @action [options.foo] = () => true;

    __junk;
};
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "transpiler",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-es2015": "6.18.0",
    "babel-preset-react": "6.16.0",
    "babel-preset-stage-2": "6.18.0",
    "del": "2.2.2",
    "gulp": "3.9.1",
    "gulp-babel": "6.1.2",
    "gulp-if": "2.0.0",
    "gulp-line-ending-corrector": "1.0.1",
    "gulp-notify": "2.2.0",
    "gulp-plumber": "0.6.6",
    "gulp-print": "1.1.0",
    "gulp-rename": "1.2.0",
    "jest": "15.1.1",
    "jest-cli": "15.1.1"
  },
  "jest": {
    "testPathDirs": ["test"],
    "modulePaths": ["2"],
    "testRegex": ".js$",
    "moduleNameMapper": {
      "^react$": "assets/react/react",
      "^react-dom$": "assets/react-dom/react-dom",
      "^mobx$": "assets/mobx/mobx",
      "^mobx-react$": "assets/mobx-react/index.js",
      "^bootstrap-dropdown-button$": "assets/react-bootstrap/buttonDropdown.js"
    },
    "testPathIgnorePatterns": [
      "test/mocks/"
    ]
  },
  "scripts": {
    "preinstall": "npm install -g gulp@3.9.1",
    "test": "jest"
  }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  see above
| node             | 4.4.5
| npm              | 3.9.5
| Operating System | Windows 10

**Comment by DrewML** [comment]
This is a bug in [Babylon](https://github.com/babel/babylon/). Would you be willing to re-open this issue on that repo?

**Comment by danharper** [comment]
Same as #4871 too. Looks like it's parsing the computed property _as_ the decorator.

https://astexplorer.net/#/jczWYoJoM5

**Comment by DrewML** [comment]
Looking at the latest decorators proposal, I believe this is actually invalid now.

http://tc39.github.io/proposal-decorators/

> The Decorator production is @ followed by a sequence of dotted identifiers (no  [] access is allowed due to grammar difficulties) and an argument list. Thus,  @foo.bar() is valid, while  @foo().bar() (and  @foo[bar]) are syntax errors.

**Comment by arackaf** [comment]
Thanks for the reply - lemme confirm that computed properties are disallowed and if so, will just close this whole issue as moot.

**Comment by DrewML** [comment]
@Kovensky pointed out to me that I may have read this backwards. Specifically:

> no [] access is allowed 

means that you just can't do property lookup on an object in the decorator expression, to _allow_ the ability to support decorating computed properties.

**Comment by arackaf** [comment]
Yeah - that's invalid code by as far as the new decorators proposal is concerned.

**Comment by DrewML** [comment]
It actually _is_ still allowed, as long as in this example, you're expecting `options.foo` to be the class prop name, _not_ a property on `action`:

```
const mixin = options => Class => class sub extends Class {
    @action [options.foo] = () => true;
};
```

**Comment by arackaf** [comment]
Correction to the above comment - computed property names are valid for decorators. `[]` syntax is just invalid in the decorator expression itself.

**Comment by arackaf** [comment]
Case filed

https://github.com/babel/babylon/issues/231

Thanks a ton for all your help.

**Comment by DrewML** [comment]
@arackaf Thank you! Closing this out and tracking will continue at babel/babylon#231
