### ISSUE TITLE
Using object destructuring rest parameters causes default argument to become evaluated before rest parameters are declared

### ISSUE THREAD

**Issue by pl12133** [babel/babel#4867]
### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "stage-2" ]
}
```

### Expected Behavior
One function accepts two arguments, and uses object destructuring for both. The first argument is destructured with the rest operator. It then assigns the value of the rest parameters as the default value of the destructured property of the second argument. This causes the default property of the second argument to become evaluated before the rest parameters of the first argument are declared.

```js
function example({ a, ...rest }, { b = rest }) {
  // assignment `b = rest` will happen before `rest` is declared.
  console.log(a, b);
}
```

The `rest` variable should be declared before attempting to assign it to a variable.

### Current Behavior
The second argument's default value is evaluated before the `rest` variable becomes declared.

```js
"use strict";

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }

function example(_ref, _ref2) {
  var _ref2$b = _ref2.b,
      b = _ref2$b === undefined ? rest : _ref2$b;

  var a = _ref.a,
      rest = _objectWithoutProperties(_ref, ["a"]);

  // assignment `b = rest` will happen before `rest` is declared.
  console.log(a, b);
}
```

### Workaround
Do not use default parameter syntax, move assignment of default values into the body of the offending function.

### Context
Originally caused by a render function which accepts `props` and `state`:
```js
function render({ label, ...props }, { quote = { symbol: props.symbol } }) { .... }
```

### Your Environment
Reproduced in the [Babel Repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&code=function%20example(%7B%20a%2C%20...rest%20%7D%2C%20%7B%20b%20%3D%20rest%20%7D)%20%7B%0A%20%20%2F%2F%20assignment%20%60b%20%3D%20rest%60%20will%20happen%20before%20%60rest%60%20is%20declared.%0A%20%20console.log(a%2C%20b)%3B%0A%7D&experimental=true&loose=true&spec=false&playground=false)

**Comment by hzoo** [comment]
Ok it's definetely a bug but we'll probably have some trouble fixing this

```
function example({ a, ...rest }, { b = rest }) {
  // assignment `b = rest` will happen before `rest` is declared.
  console.log(a, b);
}

example({a: 1, b: 2, c: 3}, { b: undefined });
```

```
function example(_ref, { b = rest }) {
  let {
    a
  } = _ref;

  let rest = _objectWithoutProperties(_ref, ["a"]);
  // assignment `b = rest` will happen before `rest` is declared.
  console.log(a, b);
}

example({a: 1, b: 2, c: 3}, { b: undefined });
```

Sounds like we need to track the use of the rest parameter in the other params and if it's used with defaults then we need to move a reference of that outside as well or something

**Comment by bluejamesbond** [comment]
What is the expected behavior if the two parameters are swapped?

`b = rest, {a, ...rest}`

**Comment by hzoo** [comment]
You shouldn't be able to reference later parameters - only goes one way?

**Comment by peey** [comment]
Hi, 

I'm working on a transformer which brings the function parameters to the function body. Are these the sort of transformations we're looking at? @hzoo 

```
function example(_ref, _ref2) { // ref1 and ref2 need to be here to maintain arity (function.length)
  var [{ a, ...rest }, { b = rest }] = arguments;
  // assignment `b = rest` will happen before `rest` is declared.
  console.log(a, b);
}
```

The transformer which does this [on astexplorer](https://astexplorer.net/#/gist/4b178d730e149f5b6e654f6d4516f165/b870b01c275fbbd410afa4b9a4bb89c5fc8a4627) (WIP)

**Comment by nicolo-ribaudo** [comment]
This has been fixed: https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUwB4EMC2AHANsgCgG9F0AaRAOmoCdkBnKRAXwpICNEBeROxlgJSIiAKESIA9BNL16MAOZhMyMEwAGnHnyhrEAdxi5ciABbps2FYnbJgcOojXbdMeogAmyCLnR13lMUQIBHo4fEpcOHkCcmsBAG4RZhEgA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=
