### ISSUE TITLE
Transpile outside of node_module 'root'

### ISSUE THREAD

**Issue by aphex** [babel/babel#4869]
When running babel through webpack and using paths that reach outside of the "node_modules" root folder babel is unable to resolve plugins and presets. This is because babel uses the path to the file it is trying to transpile to do the resolution.

So trying to hold code outside of a "node_modules" root folder but still in your project is not possible unless you configure webpack like this

webpack-config.js
```javascript
module: {
            loaders: [{
                test: /\.js$/,
                loader: 'babel',
                query: {
                    compact: false,
                    plugins: [
                        require('babel-plugin-transform-decorators-legacy').default //note the .default
                    ]
                }
            }]
        }
```

I propose we fallback to the sourceRoot folder if we are unable to resolve a plugin or preset in the cwd or current file path.

Here is a full test case setup if you would like to run this yourself.

**Folder Structure**
- project
  - _app_
    - _node_modules_
    - index.html
    - package.json
    - webpack-test.js
    - webpack.config.js
  - _framework_
    - index.js

**Code**

app/index.html
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>babel-webpack-issue</title>
    <script src='bundle.js'></script>
</head>
<body>

</body>
</html>
```

app/package.json
```javascript
{
  "name": "babel-webpack-test-issue",
  "private": true,
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack",
    "dev": "webpack-dev-server"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.18.0",
    "webpack": "^2.1.0-beta.25",
    "webpack-dev-server": "^2.1.0-beta.7"
  }
}
```

app/webpack-test.js
```javascript
import { TestClass } from '../framework'
console.log(TestClass);
```

app/webpack-config.js
```javascript
module.exports = {
    entry: "./webpack-test.js",
    output: {
        path: __dirname + "/build",
        filename: "bundle.js"
    },
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel-loader',
            query: {
                // presets: ["es2015"]
                plugins: ["transform-decorators-legacy"]
            }
        }]
    }
};
```

framework/index.js
```javascript
export class TestClass {
    constructor() {
        console.log('i am a test class');
    }
}
```

**Comment by aphex** [comment]
PR sent up here with fixes for this, should be pretty safe as code only runs if existing methods fail.

https://github.com/babel/babel/pull/4870

**Comment by loganfsmyth** [comment]
The approach of explicitly loading the preset and passing it in is already our recommended approach. Adding yet another possible location for string-based resolution will complicate things even more. For now we'd like to keep things as-is since workflows where `node_modules` is not at the top level are relatively uncommon. In your case, I'd have expected `framework` to be a separate module that gets compiled entirely separately.

**Comment by aphex** [comment]
The explicit import is not horrible and we can go that way if that is the only option. This gets a bit more annoying when using something like babel-plugin-transform-decorators-legacy as you then have to get the "default" property of the requirement to use it explicitly. So it ends up looking like this

```javascript
module: {
            loaders: [{
                test: /\.js$/,
                loader: 'babel',
                query: {
                    compact: false,
                    plugins: [
                        require('babel-plugin-transform-es2015-modules-commonjs'),
                        require('babel-plugin-transform-decorators-legacy').default
                    ]
                }
            }]
        }
```
Though not a babel's issue but maybe @loganfsmyth can comment on why this is different.

I do understand if this is not the route you're team would like to go but as far as over-complication I am not sure I agree. I do not see this list of resolvable locations growing as it seems like there should only be two places for this. It is either above where the src file is or above the directory that started the transpile. 

I agree that currently this is a uncommon workflow but I am hoping to see it become more common. Particularly in development as more people adopt the mono-repo structure. As each module is separated during development but will be interacting with other modules outside of it's "root" during that time. 

This gets even more complex as we expand on the design of mono-repo and look to open up the possibilities for larger projects to use multiple repositories and multiple locations for sub-packages. Which is currently the goal of our mondorepo project.

Again, if explicit requirements are the answer we can go that way for sure, just wanted to make sure I was explaining my use-case.

Thanks for the time taking a look at this.

**Comment by loganfsmyth** [comment]
We're planning to change things up a bit in Babel 7.x around this logic.

The current plan is to consistently resolve string-based arguments passed to `babel-loader` relative to the current working directory, rather than relative to the file being compiled.

Would that be helpful in your case? It means your code would have issues if you are running

    webpack app/webpack.config.js

but work work consistently as long as you do

    cd app
    webpack webpack.config.js

Thoughts?

Also I don't think I realized at the time you posted, but I don't _think_ the fact that you have to use `.default` may be fixed now? If not, it may be a Webpack-specific issue that may be fixed in Webpack 2.

**Comment by hzoo** [comment]
Should be fixed by https://github.com/babel/babel/issues/5466 by resolving from cwd combined with using require in the babelc plugins/presets

This should be fixed in Babel 7

can test with: 
"babel-core": "7.0.0-alpha.3"
"babel-cli": "7.0.0-alpha.3"
"babel-register": "7.0.0-alpha.5"

**Comment by Lokeh** [comment]
If we're using `babel-register`, how should we solve this?

I'm currently trying to do React server-side rendering with a structure like so:

```
components/
  pages/
    hello/
      index.js
      compile.js
      package.json
      .babelrc
      node_modules/
  layouts/
    Basic.js
app.js
```

`app.js` is just an express server that just serves up the rendered HTML. If someone were to e.g. request the `hello` page, then it does `require('components/pages/hello/compile')`. Compile is assumed to return a compiled (babel-ified) version of whatever React component should be exported; currently I'm just using `babel-register`, but later on (or for very complex pages) I might switch this to returning an AOT compiled version.

Using this `components/hello/index.js`:
```javascript
import React from "react";
import BasicLayout from "../../layouts/Basic";

export default function Hello() {
  return <BasicLayout><div>Hello, world!</div></BasicLayout>;
}
```

And this `components/layouts/Basic.js`:
```javascript
import React from "react";

export default function BasicLayout({ children }) {
  return (
    <html>
      <body>{children} </body>
    </html>
  );
}
```

I currently get this error:
```
SyntaxError: << snipped >>/components/layouts/Basic.js: Unexpected token (5:4)
  3 | export default function BasicLayout({ children }) {
  4 |   return (
> 5 |     <html>
    |     ^
  6 |       <body>{children} </body>
  7 |     </html>
  8 |   );
```
