### ISSUE TITLE
Computed class property with decorator, next to a constructor errors

### ISSUE THREAD

**Issue by arackaf** [babel/babel#4871]
```js
let x = 'x';
class Foo {
    @observable [x] = [];

    constructor(){}
}
```

raises the error 

> You can't attach decorators to a class constructor (38:4)

Similarly, 

```js
let x = 'x';
class Foo {
    constructor(){}

    @observable [x] = [];
}
```

raises 

> You have trailing decorators with no method (41:0)

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "transpiler",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-es2015": "6.18.0",
    "babel-preset-react": "6.16.0",
    "babel-preset-stage-2": "6.18.0",
    "del": "2.2.2",
    "gulp": "3.9.1",
    "gulp-babel": "6.1.2",
    "gulp-if": "2.0.0",
    "gulp-line-ending-corrector": "1.0.1",
    "gulp-notify": "2.2.0",
    "gulp-plumber": "0.6.6",
    "gulp-print": "1.1.0",
    "gulp-rename": "1.2.0",
    "jest": "15.1.1",
    "jest-cli": "15.1.1"
  },
  "jest": {
    "testPathDirs": ["test"],
    "modulePaths": ["2"],
    "testRegex": ".js$",
    "moduleNameMapper": {
      "^react$": "assets/react/react",
      "^react-dom$": "assets/react-dom/react-dom",
      "^mobx$": "assets/mobx/mobx",
      "^mobx-react$": "assets/mobx-react/index.js",
      "^bootstrap-dropdown-button$": "assets/react-bootstrap/buttonDropdown.js"
    },
    "testPathIgnorePatterns": [
      "test/mocks/"
    ]
  },
  "scripts": {
    "preinstall": "npm install -g gulp@3.9.1",
    "test": "jest"
  }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  see above
| node             | 4.4.5
| npm              | 3.9.5
| Operating System | Windows 10

**Comment by danharper** [comment]
Looks like it's parsing `[x] = []` as part of the decorator.

**Comment by arackaf** [comment]
Computed property names are not allowed with the new decorators proposal, so this code was never valid.

**Comment by arackaf** [comment]
Correction to the above comment - computed property names are valid for decorators. `[]` syntax is just invalid in the decorator expression itself.

**Comment by arackaf** [comment]
@DrewML - is this issue valid here, or should it, too, be moved to Babylon?

**Comment by DrewML** [comment]
This one is another parsing problem (still using the old spec's behavior, which has the ambiguities) - let's move it over.

**Comment by arackaf** [comment]
Done https://github.com/babel/babylon/issues/232
