### ISSUE TITLE
[types && generator] t.templateElement return simple value, and generator will print wrong code.

### ISSUE THREAD

**Issue by morlay** [babel/babel#4879]
```js
import * as babelTypes from 'babel-types';
import generate from 'babel-generator';

const ast = babelTypes.templateLiteral([
   babelTypes.templateElement('/user', false),
   babelTypes.templateElement('', true),
 ], [
   babelTypes.identifier('id'),
 ]);

generate(ast).code
```

Should generate 
```
`/user${ id }`
```

But got

```
`undefined${ id }undefined`
```

`babelTypes.templateElement` now return 

```yaml
type: 'TemplateLiteral'
value: '/user'
tail: false
```

But `generator` will pick `value.raw` https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/template-literals.js#L10

Should I have to use like `babelTypes.templateElement({ raw: 'VALUE' })` ?

| software         | version
| ---------------- | -------
| Babel            |  6.19
| node             | 7.1
| npm              | 3.9
| Operating System | MacOS

**Comment by TienDo1011** [comment]
Does this issue has been fixed?

**Comment by loganfsmyth** [comment]
The `value` field of TemplateElement is documented in https://github.com/babel/babel/blob/master/packages/babel-parser/ast/spec.md#templateelement

so my recomendation would be to do
```
.templateElement({ 
  raw: 'VALUE',
  cooked: 'VALUE',
})

**Comment by liuxingbaoyu** [comment]
This issue has been resolved in past releases.
