### ISSUE TITLE
plugins/presets order

### ISSUE THREAD

**Issue by pavel06081991** [babel/babel#4882]
In documentation it is written:
```

    Plugins run before Presets.
    Plugin ordering is first to last.
    Preset ordering is reversed (last to first).
```
I wrote my own plugin which works with const and let. It works good, but when I use "es2015" preset, my plugin does not work because all const and let become var. Why does my plugin run after presets?
Here is my babel config:
```
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "./babel-plugin-transform-const-name"
  ]
}
```
And I use "babel-cli": "^6.18.0"

**Comment by max-mykhailenko** [comment]
I'm also have this problem. I need run plugins at first and then presets. My `.babelrc` file

```json

{
  "presets": ["stage-1", "react"],
  "plugins": [
    "check-es2015-constants",
    "transform-es2015-arrow-functions",
    "transform-es2015-block-scoped-functions",
    "transform-es2015-block-scoping",
    "transform-es2015-classes",
    "transform-es2015-computed-properties",
    "transform-es2015-destructuring",
    "transform-es2015-duplicate-keys/",
    "transform-es2015-for-of",
    "transform-es2015-function-name",
    "transform-es2015-literals",
    "transform-es2015-modules-commonjs",
    "transform-es2015-object-super",
    "transform-es2015-parameters",
    "transform-es2015-shorthand-properties",
    "transform-es2015-spread",
    "transform-es2015-sticky-regex",
    "transform-es2015-template-literals",
    "transform-es2015-unicode-regex",
    "transform-regenerator"
  ]
}
```

**Comment by hzoo** [comment]
Plugins do go before presets, but it just adds the same visitors first before merging them. You may need to use the passPerPreset option but I'm not sure that will help. If you use es2015 ultimately the const/let will eventually turn into var anyway so if you didn't want that you would need to turn off/exclude that plugin (don't use es2015)

**Comment by hzoo** [comment]
FYI made https://github.com/babel/babel/issues/5623 to discuss plugin ordering
