### ISSUE TITLE
Polling watch mode

### ISSUE THREAD

**Issue by repkins** [babel/babel#4889]
Hello!

I have a issue relatied to watch option in Babel CLI. 

### Expected Behavior

I would like to suggest possibility in Babel CLI to set **polling** (legacy) watch mode

### Current Behavior

Currently it seems to listen to native filesystem events for changes, which is not available in network share/mounts.

### Possible Solution

Giving CLI a new option flag, like "-L", as `nodemon` package does.

**Comment by hzoo** [comment]
Going to close for inactivity, I would suggest using something like gulp or something else to handle watch - babel watch is just for a simple use cases atm
