### ISSUE TITLE
length property of function changes when declared async

### ISSUE THREAD

**Issue by damonmaria** [babel/babel#4891]
Given the following I'd expect the same result from both `length`s:

### Input Code

```js
const foo = (...args) => { }
console.log(foo.length)  // 0
const asyncFoo = async (...args) => { }
console.log(asyncFoo.length)  // 1
```

### Babel Configuration (.babelrc, package.json, cli command)

.bablerc:
```js
{
  "presets": [
    "react",
    "es2015",
    "stage-3"
  ],
  "plugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

Package.json:
```
    "babel-core": "^6.18.2",
    "babel-plugin-transform-class-properties": "^6.18.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-3": "^6.17.0",
```

### Context
I was tripped up because Mocha behaves differently depending on the test function's length. I couldn't figure out why everything stopped working when I changed a test wrapper function to `async`.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.2
| node             | v4.6.2
| npm              | 3.10.9
| Operating System | MacOS 10.12.1

**Comment by erikdesjardins** [comment]
[repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017&code=const%20t%20%3D%20async%20(...args)%20%3D%3E%20%7B%7D%0A&experimental=true&loose=false&spec=false&playground=false)

It appears that it tries to preserve the `length` by [adding dummy `_x` params](https://github.com/babel/babel/blob/53de56d069298a005da1021a244b2705c4983c02/packages/babel-helper-remap-async-to-generator/src/index.js#L125), but doesn't take into account that the last param could be a `RestElement`.

**Comment by loganfsmyth** [comment]
Definitely seems like a bug, good find.
