### ISSUE TITLE
Incorrect destructuring in for loops

### ISSUE THREAD

**Issue by julien-f** [babel/babel#4893]
### Input Code

```js
const f = range => {
  for (let [ i, n ] = range; i <= n; ++i) {
    console.log(i)
  }
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [ "es2015" ]
}
```

### Expected Behavior

```js
var f = function f(range) {
  var _range = _slicedToArray(range, 2);
  for (var i = _range[0], n = _range[1]; i <= n; ++i) {
    console.log(i);
  }
};
```

### Current Behavior

```js
var f = function f(range) {
  for (function () {
    var _range = _slicedToArray(range, 2);

    var i = _range[0],
        n = _range[1];
  }(); i <= n; ++i) {
    console.log(i);
  }
};
```

See in the [REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=const%20f%20%3D%20(range)%20%3D%3E%20%7B%0A%20%20for%20(let%20%5B%20i%2C%20n%20%5D%20%3D%20range%3B%20i%20%3C%3D%20n%3B%20%2B%2Bi)%20%7B%0A%20%20%20%20console.log(i)%0A%20%20%7D%0A%7D%0Af(%5B0%2C%2010%5D)).

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.2
| node             | 6.9.1
| npm              | 4.0.2
| Operating System | Debian

**Comment by hzoo** [comment]
Not the same issue but similar behavior to https://github.com/babel/babel/issues/3081 - I would use `var` as workaround atm.

**Comment by julien-f** [comment]
I destructed myself for now :)
