### ISSUE TITLE
transform-es2015-modules-amd assumes 'module' dependency

### ISSUE THREAD

**Issue by AndersDJohnson** [babel/babel#4895]
### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": ["latest"],
  "plugins": ["transform-es2015-modules-amd"]
}
```

### Expected Behavior

Perhaps should allow use of global `module` function for `angular-mocks`, maybe a configuration not to assume as an AMD dependency.

### Current Behavior

Assumes `module` as an AMD dependency, which results in `undefined`. Maybe this is for RequireJS's [CommonJS functionality](http://requirejs.org/docs/commonjs.html)?

### Possible Solution

For now, use `angular.mock.module` instead of shorthand `module` global.

### Context

AngularJS 1.x testing with Karma, Jasmine, and `angular-mocks`.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.11.4
| node             | 6.2.2
| npm              | 3.10.5
| Operating System | macOS Sierra 10.12.1

**Comment by loganfsmyth** [comment]
This should only have happened previously if you were using `module.exports` or something like that in your file, which isn't a usecase we really supported.

In Babel 7.x, if you wanted to access the AMD `'module'` import, you'd have to explicitly

    import module from 'module';

to get it.
