### ISSUE TITLE
Angular Error Module is not available - gulp babel

### ISSUE THREAD

**Issue by dtturcotte** [babel/babel#4898]
More on this issue [here](http://stackoverflow.com/questions/40820333/angular-error-module-is-not-available-gulp-babel):

I am getting the following error in my Angular app after adding gulp babel to my gulp file. I need this to transpile and minify my ES6. 

**Prior to adding `babel` through the gulp piping, the app runs fine without error.**

> angular.js:33 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
> Error: [$injector:nomod] Module 'app' is not available!

<img width="578" alt="screen shot 2016-11-26 at 12 06 20 pm" src="https://cloud.githubusercontent.com/assets/4550049/20641928/ddf1a6ae-b3d0-11e6-83aa-3016ad0ebc4a.png">

In the browser, I see the Angular module being loaded in the concatenated app.js:

<img width="617" alt="screen shot 2016-11-26 at 12 31 17 pm" src="https://cloud.githubusercontent.com/assets/4550049/20642094/57f7e6fe-b3d4-11e6-8cc6-9f1acbbdc952.png">

I'm lost...

**Gulp Task:** Note: this error only started occurring when I started piping through babel:

```
gulp.task('scripts-dev', () => {
  return gulp.src(paths.vendorJavascript.concat(paths.appJavascript, paths.appTemplates))
    .pipe(plugins.if(/html$/, buildTemplates()))
    .pipe(babel({
        presets: [['es2015', {modules: false}]]
    }))
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.concat('app.js'))
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest(paths.tmpJavascript))
    .pipe(plugins.connect.reload());
});
```

**.babelrc** Configuration:

```
{
  "presets": [
    ["es2015", { "modules": false }]
  ]
}

```

**Expected behavior:** I am using ES6 in my Angular and need to transpile it, and eventually minify it. It transpiles and minifies without any gulp errors as expected, but throws the Angular error above in browser. We have an existing gulp file so I thought using `gulp-babel` would be an easy transition. 

**Possible solution:** I saw "use strict" being prepended to the app.js output file, and thought that may have been screwing things up. I've applied `modules: false` to presets which successfully stops the prepending. This did not fix it. Angular isn't providing any other useful tips so I come to you.

**My environment:**

| software         | version
| ---------------- | -------
| Babel            |   "gulp-babel": "^6.1.2",
| node             |  node -v: v7.1.0
| npm              | npm -v: 3.10.9
| Operating System | OSX Yosemite 10.10.5

**Comment by loganfsmyth** [comment]
Angular's dependency injection system isn't always thrilled with the renaming of function arguments we sometimes have to do in Babel, so that could be causing trouble for you. Definitely hard to say though.

**Comment by dtturcotte** [comment]
@loganfsmyth do you know of any workarounds getting ES6 to work with Angular?

**Comment by loganfsmyth** [comment]
I have never tried to use Angular unfortunately, so I can't help a ton, sorry.

**Comment by hzoo** [comment]
Going to close for inactivity. I think you'll want to use a bundler like webpack/browserify instead of concating the files. modules: false isn't going to be useful if you use import/export

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
