### ISSUE TITLE
Issue: export class statement in combination with decorator(@)

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babel#4900]
Something gone wrong when tranforming export class statement in combination with decorators. Curiously the same code works on [[astexplorer]](https://astexplorer.net/#/DG3oIHIg5f/87) or [[babel playground]](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=&experimental=true&loose=true&spec=false&code=component()%0Aexport%20%20class%20Foo%20%7B%7D&playground=true). I have also tried the babylon version of astexplorer (babylon6-6.13.1). No effect! 

Is this a bug?

### Input code
```js
@component()
export class Foo {}
```

### Output code
```js
export @component()
class Foo {}
```

### Expected Behavior
```js
@component()
export class Foo {}
```

### Plugin Code
```js
function plugin({types: t}) {
    return {};
}
export default plugin;
```

### Babylon/Babel Configuration
```js
import assert from 'assert';
import { transform } from 'babel-core';
import syntaxDecorator from 'babel-plugin-syntax-decorators';

function transformCode(code){
    let generated = transform(code, {
        plugins: [
            syntaxDecorator,
        ]
    });
    return generated.code;
}
```

### Your Environment

| software         | version
| ---------------- | -------
| babylon          |  6.14.1
| babel-core          |  6.18.2
| babel-plugin-syntax-decorators | 6.13.0
| node             | 5.1.0
| npm              | 3.3.12
| Operating System | OS X El Capitan 10.11.6

**Comment by loganfsmyth** [comment]
This is an interesting one because in my understanding

```
@component()
export class Foo {}
```

is actually invalid syntax. Both [the old spec](https://github.com/wycats/javascript-decorators#grammar) and [the new spec](https://tc39.github.io/proposal-decorators/#sec-updated-syntax) add `DecoratorList` to the front of the class but make no mention of export handling, so I'd actually say the real bug here is that Babylon is failing to parse

```
export @component() class Foo {}
```

when it seems like it should be allowed.

**Comment by SerkanSipahi** [comment]
@DrewML please reopen https://github.com/babel/babylon/issues/239 and mark as bug, thanks.

**Comment by DrewML** [comment]
> This is an interesting one

Indeed. I noticed the same thing with the productions (at least in the newest draft). One thing I thought was a bit off was that one of the framework examples showed this usage, which made me second-guess the grammar. On second thought, though, that could have been an example using TypeScript.
