### ISSUE TITLE
Escaping Cyrillic text inside a JSX

### ISSUE THREAD

**Issue by wKich** [babel/babel#4909]
After #4478 PR I discovered that Cyrillic text inside a jsx tag transpiled to `\uXXXX`-style escape sequences. This leads to issues in debug and growing output bundle size. But if I have JSXExpression with StringLiteral all works as expected and text stay unescaped.
### Input Code

```jsx
<div>
  <Foo>Привет</Foo>
  <Foo>{"Привет"}</Foo>
</div>
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "react",
    ["es2015", { "loose": true, "modules": "commonjs", "spec": true }],
    "es2016",
    "es2017"
  ]
}
```

### Expected Behavior

```js
React.createElement(
  "div",
  null,
  React.createElement(
    Foo,
    null,
    "Привет"
  ),
  React.createElement(
    Foo,
    null,
    "Привет"
  )
);
```

### Current Behavior

```js
React.createElement(
  "div",
  null,
  React.createElement(
    Foo,
    null,
    "\u041F\u0440\u0438\u0432\u0435\u0442"
  ),
  React.createElement(
    Foo,
    null,
    "Привет"
  )
);
```

### Possible Solution

Add option to disable generating ASCII-safe code or fix escaping behavior.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.17.0
| node             | 6.9.1
| npm              | 3.10.8
| Operating System |  OS X 10.12.1

**Comment by odinmillion** [comment]
Same behaviour with simple ast without jsx. This annoys me 😈 
+1 for additional option to choose beahavior.

```javascript
const t = require('babel-types');
const generate = require('babel-generator').default;

const ast = t.program([
  t.variableDeclaration('const', [
    t.variableDeclarator(
      t.identifier('a'), t.objectExpression([
        t.objectProperty(t.stringLiteral('Абвгдеёжзик'), t.numericLiteral(123))
    ]))
  ])
]);
const code = generate(ast).code;

console.log(code);
```

Expected output:
```javascript
const a = {
  "Абвгдеёжзик": 123
};
```

Current output:
```javascript
const a = {
  "\u0410\u0431\u0432\u0433\u0434\u0435\u0451\u0436\u0437\u0438\u043A": 123
};
```

**Comment by hzoo** [comment]
Is this covered by https://github.com/babel/babel/pull/4827? `jsonCompatibleStrings`

**Comment by odinmillion** [comment]
Nope. This option was like a ray of hope for me several days ago. Result for `t.stringLiteral('©Абвг')`:

| jsonCompatibleStrings  | Output |
| ------------- | ------------- |
| true  | "\\u00A9\\u0410\\u0431\\u0432\\u0433"  |
| false  | "\\xA9\\u0410\\u0431\\u0432\\u0433"  |

In both cases each char converts into 6 chars (ex: '\\', 'u', '0', '0', 'A', '9') or 4 chars (ex: '\\', 'x', 'A', '9').

**Comment by hzoo** [comment]
cc @kangax, @mathiasbynens

**Comment by mathiasbynens** [comment]
> This leads to issues in debug […]

Could you clarify which issues you’re having, please?

> […] and growing output bundle size. 

Do you have any numbers here? In UTF-8-encoding, every character in your example string take up 2 bytes. The escaped output is 4 or 6 bytes. I doubt this makes a significant difference after gzip.

**Comment by wKich** [comment]
@mathiasbynens I try to say about inconsistent behavior when a JSXText is escaping, but a StringLiteral isn't.

> Could you clarify which issues you’re having, please?

If you don't see issues, then maybe you can easily read an escaped text without using any decoding tool. But I don't have such powerful mental ability. And more over it's hard to search text when `Привет` was encoded to something like this `\u041F\u0440\u0438\u0432\u0435\u0442`.

In your issue #4477 you said:
> non-ASCII symbols, leading to potential encoding issues (e.g. if the server is not configured to serve the file as UTF-8)

But what if I have configured server to correct serve UTF-8 files, I stuck with forceful escaped strings and nothing can do with that. Why you don't want give the option to other people that they can choose?

> Do you have any numbers here?

For minified bundle, I got correct unescaped text. For dev version, size is not critical. So, yes, size of bundle is not a problem.

**Comment by mathiasbynens** [comment]
> I try to say about inconsistent behavior when a JSXText is escaping, but a StringLiteral isn't.

I agree it should be consistent!

> If you don't see issues, then maybe you can easily read an escaped text without using any decoding tool. But I don't have such powerful mental ability. And more over it's hard to search text when Привет was encoded to something like this `\u041F\u0440\u0438\u0432\u0435\u0442`.

What I meant is, what is your use case? I don’t understand why you’d need to read the generated output, even while debugging (given source maps are a thing etc.).

**Comment by odinmillion** [comment]
> What I meant is, what is your use case? I don’t understand why you’d need to read the generated output, even while debugging (given source maps are a thing etc.).

Let me tell you my scenario. We use babel-types to build ast from the scratch. Then we use babel-generator to produce javascript code and commit this code to repository. As result git diff turns into hell. Sometimes it is hard to understand what is going on. And we don't have source maps.

**Comment by akzhan** [comment]
Yes, option needed to not escape anything more than JavaScript itself does.

Code should be UTF-8 friendly.

**Comment by mathiasbynens** [comment]
> Code should be UTF-8 friendly.

ASCII-only output *is* UTF-8 friendly.

**Comment by akzhan** [comment]
> ASCII-only output is UTF-8-friendly.

1) ASCII escaping is totally unreadable. Production environment will be unmaintained.
2) Native UTF-8 result: more performance on load, less size (both at 2-6%).
3) Behaviour of literals should be same.

**Comment by wKich** [comment]
I think there is another way. It's move ASCII-safe encoding functionality in a separate transform plugin. That allow users, who want get ASCII-only output can use these plugin.

@mathiasbynens please, we not want demagoguery here. You're trying to solve problems that do not apply to Babel. If you write UTF-8 (not ASCII-only) code and your server is not configured to correct serve UTF-8 files, it's not your problem, it's a server problem.

I think, that babel should solve problems for which it was created, it's allow you write code with new features of ECMAScript and transpiling it to get work on current or older browsers and not solve encoding problems or something else. If you want to solve your narrow use case, create a plugin and all be happy.

**Comment by mathiasbynens** [comment]
@wKich 

> please, we not want demagoguery here.

😮 Which of my comments would you consider demagogic?

> I think, that babel should solve problems for which it was created, it's allow you write code with new features of ECMAScript and transpiling it to get work on current or older browsers and not solve encoding problems or something else.

If Babel were to transpile…

```js
'\u{1D306}' // note: ASCII-safe
```

…into…

```
'𝌆'
```

…it might *introduce* encoding issues. Producing ASCII-safe output is not about “solving” a user’s problems, **it’s about avoiding creating them**.

> If you want to solve your narrow use case, create a plugin and all be happy.

Which “narrow use case” are you talking about? Wanting Babel to not break ASCII-safe code by default? Wanting Babel’s output to be usable without additional server configuration?

Committing generated code without matching source maps (the only use case for having an option to disable ASCII-safe output presented so far) sounds like more of an edge case to me.

As for the other arguments presented in this thread by @akzhan:

> Native UTF-8 result: more performance on load, less size (both at 2-6%).

Do you have any data/benchmarks on this? I’m sceptical about escape sequences having a non-negligible impact on parsing time in any JavaScript engine.

The same question goes for the file size comparison. Did you account for brotli/gzip compression? Could you please share the data you’ve tested this on?

**Comment by mathiasbynens** [comment]
I’m not opposed to adding an option to disable ASCII-safe output, but

1. we need a good reason to add it. IMHO we should make this decision based on facts rather than anecdotal evidence and uncommon use cases. So far the use cases presented in this thread aren’t very convincing to me (but then again, it’s not up to me to decide) and no data has been presented to back up the run-time perf claims
1. it should definitely not be the default

**Comment by wKich** [comment]
> Why not?

We not write code manually. As we said before, we use babel-generator for generate jsx source code and then compile bundle. Source map is not a solution in this case. But we want have a capability to read and search something in a generated code. The sequence like this `\u041F\u0440\u0438\u0432\u0435\u0442` is hard to read and unable to search.

> Which of my comments would you consider demagogic?

I think, you smart enough to understand that @akzhan wanted to say about UTF-8 friendly.

> Producing ASCII-safe output is not about “solving” a user’s problems, it’s about avoiding creating them.

So, are you try solve non-existent problems? Can you, for example, give a link to real project where authors faced with that problem while using `'\u{1D306}'` or something like this in their code? What server their use? What configuration of server their have?

> Wanting Babel’s output to be usable without additional server configuration?

And why Babel need to solve problem with invalid server configuration? Do you suggest we need to solve the our problem with ASCII encoding with source maps or everything else, but you try to avoid potential problems for people who use invalid server configuration through forcing ASCII encoding with inconsistent behavior? What's the point of this?

> sounds like more of an edge case to me.

And for me the invalid server configuration is an edge case. If you want to serve UTF-8 files you need to have a correct server configuration for that.

> no data has been presented

Do I understand correctly that you have real statistics data about how much servers without UTF-8 support and with, how much real projects use this `'\u{1D306}'` in code? Can you share it? Or we can apply same statement to your claims.

**Comment by mathiasbynens** [comment]
> We not write code manually. 

Ah, that’s what I was missing before. Thanks for pointing this out!

> Can you, for example, give a link to real project where authors faced with that problem while using `'\u{1D306}'` or something like this in their code? What server their use? What configuration of server their have?

+

> Do I understand correctly that you have real statistics data about how much servers without UTF-8 support and with, how much real projects use this '\u{1D306}' in code? Can you share it? Or we can apply same statement to your claims.

Trying to shift the burden of proof is a classic [fallacy](https://en.wikipedia.org/wiki/List_of_fallacies#Informal_fallacies).

Still, I’m happy to give a counter-example: d3.js once had a non-ASCII-safe release. See https://github.com/d3/d3/issues/1195 and the issues linked from there to get an idea of the trouble it causes.

The current solution ensures Babel’s output works in any of the supported environments, including on servers not configured to handle UTF-8. That’s a _fact_. I understand you’d like to see an option to change the escaping behavior (which is fair!) but challenging facts is not the way to get there. If you want this option and make claims in its defense, why not back them up?

So far the only argument in favor of adding this option has been “we like to read generated code”, which is fair. More arguments were made regarding file size / performance for which no source or data has been presented — so please share them, it will help your case!

> And for me the invalid server configuration is an edge case. If you want to serve UTF-8 files you need to have a correct server configuration for that.

The premise of that argument is incorrect: Babel has no documented requirement to use UTF-8. You want to add an option that would require serving the files as UTF-8 — if not, stuff breaks. Since this is more limiting than the current situation, it cannot be the default option.

**Comment by akzhan** [comment]
1.js - concatenated source code, only javascript, no PUG templates, no node modules etc.
2.js - same but unicode escaped like `\u0410`

uncompressed 1617841 vs 1899786
compressed (gzip defaults) 316957 vs 330107

code that build it:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Unicode::Escape qw( escape );
use File::Slurper qw( read_binary write_binary );
use File::Find qw( find );

my $content = '';

find( {
    wanted => sub {
        return  unless -f;
        my $name = $File::Find::name;
        return  if $name !~ m/\.js$/;
        $content .= read_binary( $File::Find::name );
    },
    no_chdir => 1,
}, '../frontend/src' );

write_binary( '1.js', $content );

write_binary( '2.js', escape( $content ) );
```

**Comment by akzhan** [comment]
Results - gzipped escaped scripts grow for 4% size in our case.

**Comment by akzhan** [comment]
Performance can be tested after recompilation of the application, but I have no time to bench it now.

Previously it takes 2-5% slower to compile escaped code (by Chrome timeline).

**Comment by igorushko** [comment]
@mathiasbynens i created PR for adding option to disable encoding. I want use minimal option in jsesc, but it not released. You have plans about release that?

**Comment by mathiasbynens** [comment]
@igorushko Sure! https://github.com/mathiasbynens/jsesc/releases/tag/v2.4.0 FWIW, I’ve added the `minimal` option only because of this thread.

**Comment by wKich** [comment]
>More arguments were made regarding file size / performance for which no source or data has been presented — so please share them, it will help your case!

@mathiasbynens how about that http://eprev.org/2017/01/04/the-importance-of-html-character-encoding/?

**Comment by wKich** [comment]
I think the PR #8143 allow to generate ASCII-unsafe code. So may be we should close this issue.

**Comment by hzoo** [comment]
Oh yes that would work, a more generic solution in https://github.com/babel/babel/pull/8143. So now it can be

```js
{
  "generatorOpts" {
    "jsescOption": {
      "minimal": true
    }
  }
}

and we can edit the docs https://babeljs.io/docs/en/next/babel-generator.html
