### ISSUE TITLE
babel-node cannot work on windows

### ISSUE THREAD

**Issue by cateradmin** [babel/babel#4911]
### Input Code

```js
var child_process = require('child_process');

child_process.execFile(./node_modules/.bin/babel-node,args,{
   timeout: 10000,
   env: {
           ...
    }
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Expected Behavior

bable-node could execute
### Current Behavior

API ERROR: Error: spawn ./node_modules/.bin/babel-node ENOENT

util.js:1026 exports._errnoException
util.js:1026:11

child_process.js:193 Process.ChildProcess._handle.onexit
internal/child_process.js:193:32

child_process.js:359 onErrorNT
internal/child_process.js:359:16

next_tick.js:74 _combinedTickCallback
internal/process/next_tick.js:74:11

next_tick.js:98 process._tickCallback
internal/process/next_tick.js:98:9
### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.1.6
| node             | 6.9
| npm              | 3.10
| Operating System | windows 7

**Comment by friedemannsommer** [comment]
This issue was previously created at nodejs/node#9835.

Just to be sure and exclude any misconceptions, have you "babel-cli" in your package.json?

**Comment by cateradmin** [comment]
yes. I'm sure babel-cli is installed

**Comment by friedemannsommer** [comment]
Sorry to disappoint you but i asked how you installed "babel-cli". It seems like you want to access it from a Node.js Project so it needs to be in your "package.json" dependencies (`npm i -s babel-cli`).

**Comment by cateradmin** [comment]
I have tried install it globally and install it in my project.. Both of ways don''t work on windows.

**Comment by samanime** [comment]
This is actually a pretty common quirk of Windows and Node.js (and it's process runner) that has nothing to do with babel-cli. When calling it on windows, you'll likely need to call it with '.cmd' at the end.

You can make it cross platform like this:

    const BABEL_PATH = './node_modules/.bin/babel-node' + (/^win/.test(process.platform) ? '.cmd' : '');

You'll get:
 - ./node_modules/.bin/babel-node on non-Windows
 - ./node_modules/.bin/babel-node.cmd on Windows

**Comment by OracPrime** [comment]
The + (/^win/.test(process.platform) ? '.cmd' : ''); fix is great inside a js file.  However is there a way to make something like BABEL_PATH apply to scripts inside package.json files?  It's causing problems over at https://github.com/yahoo/react-intl/issues/821

**Comment by loganfsmyth** [comment]
I'm not sure what you mean about inside `package.json`?

**Comment by OracPrime** [comment]
For example, one of the projects I'm working with has a scripts entry
  "scripts": {
    "clean": "../../node_modules/.bin/rimraf build",
.... other scripts removed
}
where they are using the local node_modules to be certain they know which version they're using.  However, on windows this fails.   A script entry of "rimraf build" works correctly, but once you specify the explicit path you need to make it say

  "scripts": {
    "clean": "../../node_modules/.bin/rimraf**.cmd** build",
...}

which clearly won't work on linux.

I'm looking for a way to harmonise the scripts.

**Comment by loganfsmyth** [comment]
Gotcha. Yeah, seems like just the pain of combining Windows + POSIX. I don't know if there is any standard way to do that.

**Comment by OracPrime** [comment]
I think there may be a way of doing it with cross-env - I'm raising an issure there that might sort it...

**Comment by nbrady-techempower** [comment]
I'm interested in this as well. For now I just have this in my `package.json` as a quick work around for when I'm on my windows box:
```

**Comment by OracPrime** [comment]
In fact it's easy don't try to do any path manipulation with cross-env, just put cross-env before the command

"scripts": {
    "start": "cross-env ./node_modules/.bin/babel-node server.js",
}

Will work on both

**Comment by loganfsmyth** [comment]
Closing since `cross-env` seems to be the solution here.
