### ISSUE TITLE
Add babel-code-frame supportsColor override

### ISSUE THREAD

**Issue by Timer** [babel/babel#4912]
Can we please add an option to `babel-code-frame` that allows us to override supportsColor?

I can put together a PR if desired.

**Comment by hzoo** [comment]
I know it's for create-react-app 😄, what should the option look like?

**Comment by Timer** [comment]
@hzoo the name doesn't matter to me, but adding an option, say `forceColor`:
```js
    const ansiHighlight = codeFrame(sourceCode, lineNum, columnNum, {
      highlightCode: true,
      linesAbove: CONTEXT_SIZE,
      linesBelow: CONTEXT_SIZE,
      forceColor: true
    })
```

Force color would then result in the following changes:
```js
let highlighted = opts.highlightCode && chalk.supportsColor;
//becomes
let highlighted = (opts.highlightCode && chalk.supportsColor) || opts.forceColor;
```
then `chalk` needs to be reassigned
```js
chalk = new chalk.constructor({ enabled: true })
```

**Comment by existentialism** [comment]
@Timer I can help with this + tests if you have other things to take care of?

**Comment by Timer** [comment]
My apologies @existentialism, I didn't see this any was already working on it.
Let me know if you see anything wrong with my PR or know a better way to do it!

Cheers! 🍻

**Comment by existentialism** [comment]
@Timer no worries at all! It's probably worth adding a test covering the option to ensure it doesn't break in the future.

**Comment by Timer** [comment]
I added a basic test, but it doesn't check to make sure the Chalk APIs haven't changed (e.g. the `enabled` option stops working). That seems like a complex test to perform because we have to fiddle with the environment variables then re-import chalk. I think I'll let it slide unless if you want to give it a whirl.

**Comment by Timer** [comment]
Cheers!

#4913
06820ca17df3aad6d0d18debef43bd6966196c5f

**Comment by Timer** [comment]
I do not mean to come off as impatient, but is there any timeline for this release (I just want to know the timeline to get cra's red box out the door)? Or can we get a patch version released?

Thanks!
