### ISSUE TITLE
Babel compiles illegal class statement

### ISSUE THREAD

**Issue by togakangaroo** [babel/babel#4918]
I found out today that Babel will compile the following

```
class ShouldNotWork {
 handleClick = () => console.log(this);
 render() { 
    return 'foo'
   }
}
```

As far as I've been able to find, assignment in a class body is not legal in javascript. Chrome confirms this

![babel compiles class-body assignment which chrome doesn't allow](http://content.screencast.com/users/togakangaroo/folders/Jing/media/b160ede4-d231-4eaf-98d4-0e1d3d78631f/00000094.png)

**Comment by hzoo** [comment]
Oh, You must be using the stage-x preset in the repl - it's part of stage-2 http://babeljs.io/docs/plugins/transform-class-properties/ so if you don't turn that on it will also error.

**Comment by togakangaroo** [comment]
Yup, this was whatever codepen.io does so makes sense. Any ideas if that's actually scheduled for the spec? Odd that it would work with arrow functions either way.

**Comment by hzoo** [comment]
Oh ok yeah it's stage 2 (in the spec at stage 4) http://babeljs.io/docs/plugins/#stage-x-experimental-presets-
