### ISSUE TITLE
Playground proposal: `classof` operator

### ISSUE THREAD

**Issue by zloirock** [babel/babel#492]
Universal classification operator based on ES6 modified [`toString` / `toStringTag` logic](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object.prototype.tostring). Like LiveScript [`typeof!`](http://livescript.net/#operators-object) operator or core-js [`Object.classof`](https://github.com/zloirock/core-js#object):
```javascript
var foo = classof bar;
// =>
var _toString = Object.prototype.toString;
var foo = _toString.call(bar).slice(8, -1);

// Result:

classof null                 // => 'Null'
classof undefined            // => 'Undefined'
classof 1                    // => 'Number'
classof true                 // => 'Boolean'
classof 'string'             // => 'String'
classof Symbol()             // => 'Symbol'

classof new Number(1)        // => 'Number'
classof new Boolean(true)    // => 'Boolean'
classof new String('string') // => 'String'

var fn   = function(){}
  , list = (function(){return arguments})(1, 2, 3);

classof {}                   // => 'Object'
classof fn                   // => 'Function'
classof []                   // => 'Array'
classof list                 // => 'Arguments'
classof /./                  // => 'RegExp'
classof new TypeError        // => 'Error'

classof new Set              // => 'Set'
classof new Map              // => 'Map'
classof new WeakSet          // => 'WeakSet'
classof new WeakMap          // => 'WeakMap'
classof new Promise(fn)      // => 'Promise'

classof [].values()          // => 'Array Iterator'
classof new Set().values()   // => 'Set Iterator'
classof new Map().values()   // => 'Map Iterator'

classof Math                 // => 'Math'
classof JSON                 // => 'JSON'

function Example(){}
Example.prototype[Symbol.toStringTag] = 'Example';

classof new Example          // => 'Example'
```

**Comment by fkling** [comment]
Is `classof` an official proposal?

**Comment by zloirock** [comment]
@fkling no. It's proposal for [playground](https://6to5.org/docs/usage/playground/).

**Comment by fkling** [comment]
Ah, I didn't look at the new playground page yet and didn't know about the

> These features are in no way endorsed by Ecma International and are not a part of any ECMAScript standard, nor are they necessarily on track to become part of any standard.

part.

What is the rational for the return values for primitives?

**Comment by zloirock** [comment]
@fkling What do you mean? It's only extracted standart `Object#toString` logic in a convenient form.

**Comment by fkling** [comment]
Ah I see, that's what I wanted to know.

From my understanding, if it really returned the "class" of the value, then it shouldn't return anything for primitives since they are primitives. However, I can understand if string, number and boolean primitives are converted to their object equivalent first. But that still wouldn't explain the output for `null` and `undefined` since  they have no object equivalent.

But if you are just extracting part of `Object#toString`, then it's all clear now.

**Comment by sebmck** [comment]
Not looking to pursue this at this time. Thanks for the suggestion!
