### ISSUE TITLE
useBuiltIns for transform-object-rest-spread has stopped working for 6.19.0

### ISSUE THREAD

**Issue by jprichardson** [babel/babel#4921]
When using `transform-object-rest-spread`, the option `useBuiltIns` no longer works with `babel-plugin-transform-object-rest-spread@6.19.0`.

I suspect this is a regression caused by: https://github.com/babel/babel/pull/4755

**babel.rc**:

```json
{
  "plugins": [
    ["transform-object-rest-spread", { "useBuiltIns": true }]
  ]
}
```

You can verify that this is the case by looking at the file installed in (for `6.19.0`) `node_modules/babel-plugin-transform-object-rest-spread/lib/index.js` and you don't see the text `useBuiltIns` anywhere, whereas in version `6.16.0` you do.

**Comment by hzoo** [comment]
If you look at #4755 though it doesn't modify that part of the code? The useBuiltIns part is at the end https://github.com/babel/babel/blob/c2b3ea793f55ef7e2315bea1059c09003c674c0c/packages/babel-plugin-transform-object-rest-spread/src/index.js#L235-L264 - same on unpkg https://unpkg.com/babel-plugin-transform-object-rest-spread@6.19.0/lib/index.js

**Comment by jprichardson** [comment]
I just got a new machine and in isolation, I am unable to reproduce this problem. I must have made a mistake elsewhere. I'm really sorry for wasting your time!
