### ISSUE TITLE
Using spread operator with arrays requires polyfills

### ISSUE THREAD

**Issue by idiotWu** [babel/babel#4922]
When trying to transform `[...array]` to es5 codes, it generates a `_toConsumableArray` helper which is using an incompatible array method `Array.from`. However, if we use spread operator with objects like `{...object}`, it generates a `_extends` helper that already includes a polyfill for `Object.assign` method.

In my view, since both `Array.from` and `Object.assign` are es6 features,  the two transformations should be done in the same way. If `[...array]` requires a polyfill for `Array.from` methods, then `{...object}` should also require a polyfill for `Object.assign`, or neither of them requires a polyfill.

### Babel Configuration (.babelrc and the online repl)

```js
{
    "presets": [ "es2015", "stage-0" ]
}
```

### Input Code

```js
const a = { ...object }
const b = [...array]
```

### Outputs

```js
var _extends = Object.assign || function(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i];
        for (var key in source) {
            if (Object.prototype.hasOwnProperty.call(source, key)) { 
                target[key] = source[key]; 
            } 
        } 
    }
    return target; 
};

function _toConsumableArray(arr) {
    if (Array.isArray(arr)) {
        for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { 
            arr2[i] = arr[i]; 
        }
        return arr2; 
    } else {
        return Array.from(arr); 
    } 
}

var a = _extends({}, object);
var b = [].concat(_toConsumableArray(array));
```

### Environment
| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             |  6.9.1
| npm              |  3.10.8
| Operating System | macOS 10.12.1

**Comment by idiotWu** [comment]
I took a look at [transform-object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) and found there's an option `useBuiltIns` to turn off the polyfill. But it seems that there isn't an option for [transform-es2015-spread](https://babeljs.io/docs/plugins/transform-es2015-spread/) to turn on a polyfill.

**Comment by hzoo** [comment]
You can use `external-helpers`
