### ISSUE TITLE
Error stack is different when transpiling with `es2015-classes`

### ISSUE THREAD

**Issue by mathieumg** [babel/babel#4923]
I'm not sure whether this is by design or just a limitation, but I get different error stacks whether I'm transpiling using `es2015-classes` or not; in other words the babel transform and native interpretation give different results. What I'm trying to achieve is for a class to have a consistent `name` at the top of its error stack. That being said, I don't know which one is "the right one" only that they're different whether transpiling or not.

### Input Code

```js
class ApplicationError extends Error {
  constructor(...args) {
    super(...args);
    this.name =  Object.getPrototypeOf(this).constructor.name;
  }
}

const test = new ApplicationError();

console.log(test.stack);
```

#### Without `es2015` ([REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=&experimental=false&loose=false&spec=false&playground=true&code=class%20ApplicationError%20extends%20Error%20%7B%0D%0A%20%20constructor(...args)%20%7B%0D%0A%20%20%20%20super(...args)%3B%0D%0A%20%20%20%20this.name%20%3D%20%20Object.getPrototypeOf(this).constructor.name%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20test%20%3D%20new%20ApplicationError()%3B%0D%0A%0D%0Aconsole.log(test.stack)%3B):

```
"ApplicationError
    at ApplicationError (eval at <anonymous> (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:384:7), <anonymous>:7:20)
    at eval (eval at <anonymous> (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:384:7), <anonymous>:12:14)
    at REPL.evaluate (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:384:36)
    at REPL.compile (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:339:12)
    at onSourceChange (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:415:12)
    at onPresetChange (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:409:5)
    at https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:151:7"
```

#### With `es2015` ([REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=false&loose=false&spec=false&playground=true&code=class%20ApplicationError%20extends%20Error%20%7B%0D%0A%20%20constructor(...args)%20%7B%0D%0A%20%20%20%20super(...args)%3B%0D%0A%20%20%20%20this.name%20%3D%20%20Object.getPrototypeOf(this).constructor.name%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20test%20%3D%20new%20ApplicationError()%3B%0D%0A%0D%0Aconsole.log(test.stack)%3B)):

```
"Error
    at ApplicationError.Error (native)
    at new ApplicationError (eval at <anonymous> (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:384:7), <anonymous>:25:154)
    at eval (eval at <anonymous> (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:384:7), <anonymous>:31:12)
    at REPL.evaluate (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:384:36)
    at REPL.compile (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:339:12)
    at onSourceChange (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:415:12)
    at onPresetChange (https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:409:5)
    at https://babeljs.io/scripts/repl.js?t=2016-12-01T10:31:25+00:00:151:7"
```

### Babel Configuration (.babelrc, package.json, cli command)

See the REPL links above, basically nothing else but `es2015` preset or not.

### Expected Behavior

I would expect the Babel transpilation to behave the same as the native interpretation.

### Current Behavior

The transpiled and native versions behave differently. (See REPL links above)

### Possible Solution

If this is a limitation, I would be welcome to suggestions that achieve a similar end result. If this is a bug, my JS knowledge doesn't go deep enough to be of much help. One "dirty" solution would be to enforce that `es2015-classes` gets loaded all the time, even when classes are supported natively. I'd like to avoid going down that road.

### Context

This first happened on the server side using Node 6/7 and `babel-preset-env`. The code would run fine on Node 6 but some tests would fail on Node 7. (I can provide them if you want) The gist of it was that `es2015-classes` gets loaded on Node 6, but not on Node 7. I want to support browsers and Node 4 as well, so I would expect using/not using that transform should give the same results.

Essentially what I'm trying to achieve is to setup a `Error` class hierarchy for different types of errors throughout applications, using https://github.com/joyent/node-verror.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.19.0
| node             | 6.0.0
| Chrome        | 53.0.2785.113
| npm              | 3.10.1
| Operating System | Linux x64 (Debian)

**Comment by mathieumg** [comment]
Turns out, even simply using `require("babel-register")();` without any parameters can alter the result, on Node 6 as well: https://github.com/mathieumg/babel-stack-repro

**Comment by zloirock** [comment]
I can say more:
```js
console.log(test instanceof ApplicationError); // => false
```
[`babel` does not suppot extending native constructors.](https://babeljs.io/docs/usage/caveats/#classes)

**Comment by mathieumg** [comment]
Thanks for the explanation! I understand the limitation, but isn't it still a problem that the output is different when I run `require("babel-register")();` with absolutely no parameters, no `.babelrc` file, no `package.json` field, etc. and the output is still different?
