### ISSUE TITLE
[Question] Import in ES2015

### ISSUE THREAD

**Issue by julien-f** [babel/babel#4933]
Hi,

I'm wondering, according to the spec, whether `import * as myModule from 'my-module'` creates `myModule` as an object with properties corresponding the exports in the module or if `myModule` is just a namespace.

What I really meant is, is it possible to use `myModule` as an object and doing something dynamic with its exports?

**Comment by xtuc** [comment]
Yes, `myModule` is an object. Its values are the modules you exported.

I don't really understand the issue because you can dynamicly select the module `myModule.foo`.

Could you show us your code or some example ?

**Comment by hzoo** [comment]
@julien-f we don't really use issues for discussion questions (as noted in our contributing.md + issue template), it would be better suited in our slack or somewhere else

**Comment by xtuc** [comment]
@julien-f https://github.com/babel/babel#looking-for-support.
You can ask your question on Slack. Thanks.

**Comment by julien-f** [comment]
Thanks, sorry for the noise 😳
