### ISSUE TITLE
Calling an async function with default parameter as function for arguments checking handled synchonous

### ISSUE THREAD

**Issue by rolfst** [babel/babel#4943]
Babel throws a synchronous exception during calltime evaluation of default params
### Input Code  

```js
function mandatory(paramName) {
    throw new Error(`Missing parameter: ${paramName}`)
}

async function foo({ a, b = mandatory('b') }) {
    return Promise.resolve(b)
}

// uses chai.assert and chai-as-promised
describe('foo', () => {
    it('should return a rejected promise', async () => {
        const promise = foo({ a: 'hi' })
        assert.isRejected(promise, /Error: Missing parameter: b/)
    })
})
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015"],
  "plugins": [
    "transform-object-rest-spread",
    "transform-async-to-generator"
  ]
}
```

### Expected Behavior

This test fails with an error:

```  
Error: Missing parameter: b
```  
because this exception is thrown outside the async flow. 
 
In the latest Chrome (which supports async functions with a flag) and in Firefox 52, this code works as expected (i.e. the promise is rejected):

### Possible Solution
currently this code will be compiled to:  

```js
var foo = function () {
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(_ref2) {
        var _ref2$a = _ref2.a,
            a = _ref2$a === undefined ? 'a' : _ref2$a,
            _ref2$b = _ref2.b,
            b = _ref2$b === undefined ? mandatory('b') : _ref2$b;
        return regeneratorRuntime.wrap(function _callee$(_context) {
            while (1) {
                switch (_context.prev = _context.next) {
                    case 0:
                        return _context.abrupt('return', Promise.resolve(b));

                    case 1:
                    case 'end':
                        return _context.stop();
                }
           }
       }, _callee, this);
    }));

    return function foo(_x) {
        return _ref.apply(this, arguments);
    };
}();

function _asyncToGenerator(fn) { 
    return function () { 
         var gen = fn.apply(this, arguments); 
         return new Promise(function (resolve, reject) { 
             function step(key, arg) { 
                 try { 
                     var info = gen[key](arg); 
                     var value = info.value; 
                 } catch (error) { 
                     reject(error); return; 
                 } 
                 if (info.done) { 
                     resolve(value); 
                 } else { 
                     return Promise.resolve(value).then(function (value) { 
                         step("next", value); 
                     }, 
                     function (err) { 
                         step("throw", err); 
                     }); 
                 } 
             } 
             return step("next"); 
         }); 
     }; 
 }
```
this code shows that the resolution is put in the wrong place of the code. it may be pushed to the
`regeneratorRuntime.wrap` callback function?

### Context
I am using async functions and default parameters with evaluation at call time.

With the default parameters I use a function to check if a value is provided or not.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.5.5
|babel-cli | 6.6.5 
|babel-eslint | 6.0.4 
|babel-plugin-transform-async-to-generator | 6.8.0 
|babel-plugin-transform-object-rest-spread | 6.8.0 
|babel-polyfill | 6.9.1 
|babel-preset-es2015 |  6.6.0 
|babel-register | 6.7.2 
| node             | 6.5.0
| npm              | 3.10.3
| Operating System | macosx 10.12.1

**Comment by hulkish** [comment]
I'd like to work on this today. Cool?

**Comment by hulkish** [comment]
Also, some questions..

Shouldn't all argument defaulting logic be wrapped in regeneratorRuntime.wrap when the function is marked as `async` before transform?

**Comment by loganfsmyth** [comment]
I believe 

         var gen = fn.apply(this, arguments); 
         return new Promise(function (resolve, reject) { 

should be

         return new Promise(function (resolve, reject) { 
             var gen = fn.apply(this, arguments);

**Comment by hulkish** [comment]
@loganfsmyth yup
