### ISSUE TITLE
Stop removing old versions on npmjs

### ISSUE THREAD

**Issue by airtonix** [babel/babel#4947]
It's really frustrating when I have to account for the time I spend fixing everything broken by missing packages.

**Comment by loganfsmyth** [comment]
More information would be helpful here. We don't remove old versions, so I have no idea what you are referring to.

**Comment by stefanpenner** [comment]
I don't believe `npm`'s recent retention policy allows for this anyways. Maybe @airtonix is being bit for a infraction from quite some time ago?

**Comment by hzoo** [comment]
> Stop removing old versions on npmjs

Definitely not removing them intentionally to make our users frustrated. If anything you probably mean https://github.com/babel/babel/releases/tag/v6.18.1 -> https://github.com/babel/babel/releases/tag/v6.18.2 where there was a publishing issue that caused the `lib` directory to be missing and thus not work so I first deprecated and then unpublished it.

**Comment by airtonix** [comment]
Apologies for sounding like an entitled child.

However v6.0.0 has gone. Probably as Stefan mentioned.

Since I can't commit modules to the repo, since there is a ton of native
modules. I guess setting up my own unpm or sinopia is a hard requirement
now.

The truth of the matter is that I switched over to windows morning, fresh
installed the project and was met with npm install error after npm install
error regarding everything Babel.

I only started this project around July.

Luckily I still have fedora installed with everything running there...

**Comment by hzoo** [comment]
@airtonix actually like @loganfsmyth mentioned it would be useful to have more information.

> However v6.0.0 has gone

Which package/packages do you mean? `babel` or `babel-core`, etc?

**Comment by airtonix** [comment]
@hzoo No it's not a stack trace error. I have lots and lots and lots and lots of code relying on that specific package getting installed.

Trust me, i tried updating each package that might use it. but that resulted in more Yak shaving.

**Comment by hzoo** [comment]
I meant can you show us the error message? And v6.0.0 of what package?

**Comment by loganfsmyth** [comment]
> relying on that specific package getting installed.

You still haven't answered any of our questions. What Babel module is failing? I don't know how you're expecting us to help without more info? `6.0.0` exists in npm for all of Babel's primary packages. Please show us what you are seeing.

**Comment by stefanpenner** [comment]
> However v6.0.0 has gone. Probably as Stefan mentioned.

I believe I was misunderstood, I intended to say: I **do not** believe  NPM allows for modules such as this to be removed. (they beefed up the yanking policies in light of the left-pad fiasco)

---

For me (all appears well) what do the following commands yield for you?:

```sh
npm info babel --json | jq '.versions' | grep '6.0.0'
> "6.0.0"
```

That being said, if I have a private registry (like at work) It may not include stuff. This often causes me grief.

Im curious if your registry is in-fact pointing at the primary registry.

```
npm config get registry
> http://registry.npmjs.org/
```

**Comment by airtonix** [comment]
Babel core

**Comment by hzoo** [comment]
so babel-core@6.0.0? Sounds like you might be using a different registry since I get this for the public one: 

https://unpkg.com/babel-core@6.0.0/

`npm view babel-core@6.0.0`

<details>
npm view babel-core@6.0.0

{ name: 'babel-core',
  description: 'A compiler for writing next generation JavaScript',
  'dist-tags': { latest: '6.20.0', old: '5.8.38' },
  versions:
   [ '4.0.1',
     '4.0.2',
     '4.1.1',
     '4.2.0',
     '4.2.1',
     '4.3.0',
     '4.4.1',
     '4.4.2',
     '4.4.3',
     '4.4.4',
     '4.4.5',
     '4.4.6',
     '4.5.0',
     '4.5.1',
     '4.5.2',
     '4.5.3',
     '4.5.4',
     '4.5.5',
     '4.6.0',
     '4.6.1',
     '4.6.3',
     '4.6.4',
     '4.6.5',
     '4.6.6',
     '4.7.0',
     '4.7.1',
     '4.7.2',
     '4.7.3',
     '4.7.4',
     '4.7.5',
     '4.7.6',
     '4.7.7',
     '4.7.8',
     '4.7.9',
     '4.7.10',
     '4.7.11',
     '4.7.12',
     '4.7.13',
     '4.7.14',
     '4.7.15',
     '4.7.16',
     '5.0.0-beta2',
     '5.0.0-beta3',
     '5.0.0-beta4',
     '5.0.0',
     '5.0.1',
     '5.0.2',
     '5.0.3',
     '5.0.4',
     '5.0.5',
     '5.0.6',
     '5.0.7',
     '5.0.8',
     '5.0.9',
     '5.0.10',
     '5.0.11',
     '5.0.12',
     '5.0.13',
     '5.1.0',
     '5.1.1',
     '5.1.2',
     '5.1.3',
     '5.1.4',
     '5.1.5',
     '5.1.6',
     '5.1.7',
     '5.1.8',
     '5.1.9',
     '5.1.10',
     '5.1.11',
     '5.1.12',
     '5.1.13',
     '5.2.0',
     '5.2.1',
     '5.2.2',
     '5.2.3',
     '5.2.4',
     '5.2.5',
     '5.2.6',
     '5.2.7',
     '5.2.9',
     '5.2.10',
     '5.2.11',
     '5.2.12',
     '5.2.13',
     '5.2.14',
     '5.2.15',
     '5.2.16',
     '5.2.17',
     '5.3.0',
     '5.3.1',
     '5.3.2',
     '5.3.3',
     '5.4.0',
     '5.4.1',
     '5.4.2',
     '5.4.3',
     '5.4.4',
     '5.4.5',
     '5.4.6',
     ... 124 more items ],
  maintainers: [ 'sebmck <sebmck@gmail.com>' ],
  time:
   { modified: '2016-12-08T23:26:02.089Z',
     created: '2015-02-15T14:15:48.555Z',
     '4.0.1': '2015-02-15T14:15:48.555Z',
     '4.0.2': '2015-02-17T02:14:19.635Z',
     '4.1.1': '2015-02-17T13:05:27.250Z',
     '4.2.0': '2015-02-18T00:32:53.715Z',
     '4.2.1': '2015-02-18T00:41:46.690Z',
     '4.3.0': '2015-02-18T02:19:53.440Z',
     '4.4.1': '2015-02-21T03:23:26.172Z',
     '4.4.2': '2015-02-21T03:31:29.227Z',
     '4.4.3': '2015-02-21T07:13:34.590Z',
     '4.4.4': '2015-02-22T11:50:26.387Z',
     '4.4.5': '2015-02-22T12:26:25.383Z',
     '4.4.6': '2015-02-24T11:17:36.044Z',
     '4.5.0': '2015-02-25T11:02:47.560Z',
     '4.5.1': '2015-02-25T11:56:18.089Z',
     '4.5.2': '2015-02-25T22:04:31.842Z',
     '4.5.3': '2015-02-25T22:10:58.646Z',
     '4.5.4': '2015-02-25T22:22:21.881Z',
     '4.5.5': '2015-02-26T02:03:28.147Z',
     '4.6.0': '2015-02-27T10:09:33.698Z',
     '4.6.1': '2015-02-28T00:57:12.557Z',
     '4.6.3': '2015-03-01T00:05:15.893Z',
     '4.6.4': '2015-03-02T04:35:57.960Z',
     '4.6.5': '2015-03-02T11:56:07.191Z',
     '4.6.6': '2015-03-03T11:45:07.881Z',
     '4.7.0': '2015-03-06T15:00:42.706Z',
     '4.7.1': '2015-03-06T15:53:48.989Z',
     '4.7.2': '2015-03-07T16:11:33.045Z',
     '4.7.3': '2015-03-07T17:34:16.625Z',
     '4.7.4': '2015-03-09T16:31:26.123Z',
     '4.7.5': '2015-03-10T02:24:34.311Z',
     '4.7.6': '2015-03-10T13:13:12.868Z',
     '4.7.7': '2015-03-10T14:25:25.060Z',
     '4.7.8': '2015-03-10T20:52:21.182Z',
     '4.7.9': '2015-03-13T02:32:03.874Z',
     '4.7.10': '2015-03-13T14:59:11.222Z',
     '4.7.11': '2015-03-13T15:31:30.634Z',
     '4.7.12': '2015-03-13T15:39:03.876Z',
     '4.7.13': '2015-03-17T01:13:02.066Z',
     '4.7.14': '2015-03-18T08:13:04.745Z',
     '4.7.15': '2015-03-18T08:17:38.096Z',
     '4.7.16': '2015-03-18T12:37:42.367Z',
     '5.0.0-beta1': '2015-03-27T18:41:45.992Z',
     '5.0.0-beta2': '2015-03-27T18:48:01.724Z',
     '5.0.0-beta3': '2015-03-28T14:53:55.734Z',
     '5.0.0-beta4': '2015-03-31T13:47:47.046Z',
     '5.0.0': '2015-04-02T18:37:39.230Z',
     '5.0.1': '2015-04-02T18:52:44.242Z',
     '5.0.2': '2015-04-02T19:54:31.194Z',
     '5.0.3': '2015-04-03T04:25:34.011Z',
     '5.0.4': '2015-04-03T04:31:57.602Z',
     '5.0.5': '2015-04-03T11:43:45.797Z',
     '5.0.6': '2015-04-03T12:14:37.703Z',
     '5.0.7': '2015-04-03T17:50:16.231Z',
     '5.0.8': '2015-04-04T06:06:38.663Z',
     '5.0.9': '2015-04-06T13:29:46.305Z',
     '5.0.10': '2015-04-07T20:05:08.097Z',
     '5.0.11': '2015-04-08T15:14:49.691Z',
     '5.0.12': '2015-04-08T15:55:25.327Z',
     '5.0.13': '2015-04-13T04:14:38.411Z',
     '5.1.0': '2015-04-13T04:22:48.340Z',
     '5.1.1': '2015-04-13T07:14:13.409Z',
     '5.1.2': '2015-04-13T07:53:07.746Z',
     '5.1.3': '2015-04-13T16:24:21.372Z',
     '5.1.4': '2015-04-13T16:36:46.265Z',
     '5.1.5': '2015-04-13T18:59:21.201Z',
     '5.1.6': '2015-04-13T21:28:43.372Z',
     '5.1.7': '2015-04-13T22:00:18.328Z',
     '5.1.8': '2015-04-13T22:46:07.318Z',
     '5.1.9': '2015-04-14T15:31:17.147Z',
     '5.1.10': '2015-04-15T22:24:22.789Z',
     '5.1.11': '2015-04-20T05:26:02.352Z',
     '5.1.12': '2015-04-25T17:22:09.269Z',
     '5.1.13': '2015-04-25T17:33:21.517Z',
     '5.2.0': '2015-04-30T22:15:40.760Z',
     '5.2.1': '2015-04-30T23:31:16.802Z',
     '5.2.2': '2015-04-30T23:44:13.723Z',
     '5.2.3': '2015-05-01T08:43:00.805Z',
     '5.2.4': '2015-05-01T10:29:34.683Z',
     '5.2.5': '2015-05-01T10:41:44.187Z',
     '5.2.6': '2015-05-01T12:08:55.654Z',
     '5.2.7': '2015-05-03T22:48:24.256Z',
     '5.2.9': '2015-05-04T03:03:05.911Z',
     '5.2.10': '2015-05-04T21:24:15.110Z',
     '5.2.11': '2015-05-04T21:33:04.371Z',
     '5.2.12': '2015-05-04T23:14:31.515Z',
     '5.2.13': '2015-05-05T07:58:14.329Z',
     '5.2.14': '2015-05-05T14:12:49.925Z',
     '5.2.15': '2015-05-05T14:41:32.074Z',
     '5.2.16': '2015-05-06T15:45:11.395Z',
     '5.2.17': '2015-05-07T19:13:32.255Z',
     '5.3.0': '2015-05-12T23:13:58.899Z',
     '5.3.1': '2015-05-13T02:21:11.301Z',
     '5.3.2': '2015-05-13T18:57:49.763Z',
     '5.3.3': '2015-05-13T21:09:12.876Z',
     '5.4.0': '2015-05-14T23:30:24.990Z',
     '5.4.1': '2015-05-15T01:00:59.046Z',
     '5.4.2': '2015-05-15T01:35:49.796Z',
     '5.4.3': '2015-05-16T00:59:35.669Z',
     '5.4.4': '2015-05-20T09:51:06.759Z',
     '5.4.5': '2015-05-21T00:45:08.959Z',
     '5.4.6': '2015-05-21T17:46:48.489Z',
     '5.4.7': '2015-05-21T17:59:56.753Z',
     '5.5.0': '2015-06-05T07:11:47.641Z',
     '5.5.1': '2015-06-05T08:56:53.933Z',
     '5.5.2': '2015-06-05T11:04:04.968Z',
     '5.5.3': '2015-06-05T11:20:49.413Z',
     '5.5.4': '2015-06-05T22:04:34.110Z',
     '5.5.5': '2015-06-08T00:28:23.399Z',
     '5.5.6': '2015-06-09T03:07:54.353Z',
     '5.5.7': '2015-06-13T01:22:58.529Z',
     '5.5.8': '2015-06-13T17:54:19.408Z',
     '5.6.0': '2015-06-20T22:36:28.330Z',
     '5.6.1': '2015-06-20T23:05:50.154Z',
     '5.6.2': '2015-06-21T23:09:28.242Z',
     '5.6.3': '2015-06-22T10:57:14.084Z',
     '5.6.4': '2015-06-22T19:38:49.319Z',
     '5.6.5': '2015-06-24T12:48:22.878Z',
     '5.6.6': '2015-06-24T22:28:20.023Z',
     '5.6.7': '2015-06-25T03:18:28.468Z',
     '5.6.8': '2015-06-25T22:35:12.084Z',
     '5.6.9': '2015-06-25T22:58:44.149Z',
     '5.6.10': '2015-06-26T00:12:10.030Z',
     '5.6.11': '2015-06-26T01:39:41.394Z',
     '5.6.12': '2015-06-26T10:41:11.230Z',
     '5.6.14': '2015-06-26T14:37:49.630Z',
     '5.6.15': '2015-06-26T23:16:41.443Z',
     '5.6.16': '2015-07-09T15:19:29.463Z',
     '5.6.17': '2015-07-09T18:09:29.168Z',
     '5.6.18': '2015-07-11T23:44:23.096Z',
     '5.6.19': '2015-07-13T15:46:08.785Z',
     '5.6.20': '2015-07-13T19:56:14.006Z',
     '5.7.0': '2015-07-15T10:53:56.323Z',
     '5.7.1': '2015-07-15T16:09:37.170Z',
     '5.7.2': '2015-07-15T19:36:14.563Z',
     '5.7.3': '2015-07-16T21:45:23.523Z',
     '5.7.4': '2015-07-17T00:02:53.756Z',
     '5.8.1': '2015-07-21T17:01:55.847Z',
     '5.8.2': '2015-07-21T17:12:28.699Z',
     '5.8.3': '2015-07-21T17:24:07.399Z',
     '5.8.4': '2015-07-24T20:32:14.496Z',
     '5.8.5': '2015-07-24T21:00:31.728Z',
     '5.8.6': '2015-07-26T20:52:33.030Z',
     '5.8.8': '2015-07-26T21:08:44.825Z',
     '5.8.9': '2015-07-26T23:15:41.856Z',
     '5.8.12': '2015-07-28T00:39:49.126Z',
     '5.8.14': '2015-07-28T17:46:25.625Z',
     '5.8.19': '2015-07-29T12:32:54.606Z',
     '5.8.20': '2015-07-31T20:24:25.410Z',
     '5.8.21': '2015-08-05T21:23:32.684Z',
     '5.8.22': '2015-08-11T00:01:42.132Z',
     '5.8.23': '2015-08-27T23:39:00.641Z',
     '5.8.24': '2015-09-10T19:13:57.847Z',
     '5.8.25': '2015-09-19T00:52:45.853Z',
     '5.8.29': '2015-10-24T16:27:44.775Z',
     '5.8.30': '2015-10-28T01:15:15.286Z',
     '5.8.31': '2015-10-28T22:58:34.178Z',
     '5.8.32': '2015-10-28T23:16:13.454Z',
     '5.8.33': '2015-10-29T08:41:27.851Z',
     '6.0.0': '2015-10-29T17:53:19.846Z',
     '6.0.1': '2015-10-29T18:05:06.720Z',
     '6.0.2': '2015-10-29T18:07:51.357Z',
     '6.0.12': '2015-10-30T04:54:43.283Z',
     '6.0.14': '2015-10-30T23:31:42.795Z',
     '6.0.15': '2015-11-01T22:07:58.311Z',
     '6.0.16': '2015-11-02T07:14:21.095Z',
     '6.0.17': '2015-11-02T19:54:18.249Z',
     '6.0.18': '2015-11-03T01:23:54.148Z',
     '6.0.19': '2015-11-03T03:15:12.403Z',
     '6.0.20': '2015-11-03T04:22:01.863Z',
     '6.1.2': '2015-11-05T11:11:00.360Z',
     '6.1.4': '2015-11-11T10:05:28.655Z',
     '5.8.34': '2015-11-12T06:28:08.495Z',
     '6.1.5': '2015-11-12T06:49:33.783Z',
     '6.1.6': '2015-11-12T07:33:20.822Z',
     '6.1.7': '2015-11-12T07:37:52.045Z',
     '6.1.8': '2015-11-12T07:40:52.610Z',
     '6.1.9': '2015-11-12T07:46:30.696Z',
     '6.1.10': '2015-11-12T07:53:21.362Z',
     '6.1.11': '2015-11-12T07:58:59.012Z',
     '6.1.12': '2015-11-12T08:49:24.331Z',
     '6.1.13': '2015-11-12T19:58:11.604Z',
     '6.1.14': '2015-11-12T20:04:23.131Z',
     '6.1.15': '2015-11-12T20:18:53.042Z',
     '6.1.16': '2015-11-12T21:33:43.089Z',
     '6.1.17': '2015-11-12T21:40:48.557Z',
     '6.1.18': '2015-11-12T21:46:53.820Z',
     '6.1.19': '2015-11-12T22:18:42.445Z',
     '6.1.20': '2015-11-13T11:40:07.999Z',
     '6.1.21': '2015-11-14T00:57:14.430Z',
     '6.2.0': '2015-11-19T04:34:00.631Z',
     '6.2.1': '2015-11-19T22:03:46.027Z',
     '6.2.4': '2015-11-25T03:12:32.405Z',
     '6.3.2': '2015-12-04T03:48:16.543Z',
     '6.3.13': '2015-12-04T11:56:57.801Z',
     '6.3.15': '2015-12-06T16:31:53.708Z',
     '6.3.17': '2015-12-11T01:20:39.291Z',
     '6.3.21': '2015-12-18T08:23:08.597Z',
     '6.3.26': '2015-12-23T07:12:08.623Z',
     '6.4.0': '2016-01-06T20:34:21.967Z',
     '6.4.5': '2016-01-19T23:02:41.575Z',
     '5.8.35': '2016-01-20T22:09:15.973Z',
     '6.5.0': '2016-02-07T00:06:46.070Z',
     '6.5.0-1': '2016-02-07T02:39:35.093Z',
     '6.5.1': '2016-02-08T02:18:16.980Z',
     '6.5.2': '2016-02-12T16:30:05.366Z',
     '6.5.2-canary.ab7533ed': '2016-02-24T05:17:33.516Z',
     '6.6.0': '2016-02-29T21:12:20.206Z',
     '6.6.4': '2016-03-02T21:29:24.740Z',
     '6.6.5': '2016-03-04T23:16:24.572Z',
     '6.7.0': '2016-03-09T00:52:52.376Z',
     '6.7.2': '2016-03-10T22:41:30.171Z',
     '5.8.38': '2016-03-22T22:50:05.900Z',
     '6.7.4': '2016-03-23T03:37:49.192Z',
     '6.7.5': '2016-04-08T03:24:51.881Z',
     '6.7.6': '2016-04-08T16:27:15.134Z',
     '6.7.7': '2016-04-21T03:09:23.425Z',
     '6.8.0': '2016-05-02T23:43:53.192Z',
     '6.9.0': '2016-05-17T18:49:24.475Z',
     '6.9.1': '2016-05-29T19:50:10.589Z',
     '6.10.4': '2016-06-21T16:43:38.221Z',
     '6.11.4': '2016-07-20T01:59:57.437Z',
     '6.13.0': '2016-08-04T23:34:54.539Z',
     '6.13.1': '2016-08-05T04:12:17.411Z',
     '6.13.2': '2016-08-05T13:51:37.993Z',
     '6.14.0': '2016-08-24T23:40:50.516Z',
     '6.16.0': '2016-09-28T19:38:48.367Z',
     '6.17.0': '2016-10-01T19:23:23.370Z',
     '6.18.0': '2016-10-24T21:18:40.028Z',
     '6.18.1': '2016-11-01T21:17:20.215Z',
     '6.18.2': '2016-11-01T21:30:55.993Z',
     '6.20.0': '2016-12-08T23:25:42.357Z' },
  homepage: 'https://babeljs.io/',
  keywords:
   [ '6to5',
     'babel',
     'classes',
     'const',
     'es6',
     'harmony',
     'let',
     'modules',
     'transpile',
     'transpiler',
     'var' ],
  repository: { type: 'git', url: 'git+https://github.com/babel/babel.git' },
  author: 'Sebastian McKenzie <sebmck@gmail.com>',
  readmeFilename: 'README.md',
  users:
   { rblopes: true,
     yodairish: true,
     borjes: true,
     wkaifang: true,
     taopaic: true,
     ugarz: true,
     daviddraughn: true,
     evertonrobertoauler: true,
     bdougherty: true,
     tcrowe: true,
     shangwenmo: true,
     draganhr: true,
     piecioshka: true,
     manxisuo: true,
     urbantumbleweed: true,
     fmoliveira: true,
     junjiansyu: true,
     iolo: true,
     koulmomo: true,
     ambdxtrch: true,
     po: true,
     abdihaikal: true,
     kytart: true,
     shelling: true,
     sergeymakoveev: true,
     cfleschhut: true,
     porreh: true,
     modao: true,
     kizzlebot: true,
     wangnan0610: true,
     vutran: true,
     abdul: true,
     seaseng: true,
     sternelee: true,
     nickeltobias: true,
     dhampik: true,
     wouter_vdb: true,
     walkerbe: true,
     princetoad: true,
     taronyu: true,
     strokirk: true,
     isik: true,
     eliaslfox: true,
     dskecse: true,
     asm2hex: true,
     alexjsdev: true,
     klimnikita: true,
     camirmas: true,
     lorenazohar: true,
     amirrustam: true,
     fchienvuhoang: true,
     tonyljl526: true,
     npm_gjj: true,
     yanyinhong: true,
     maninacan: true,
     vipergtsrz: true,
     leonardorb: true,
     mswanson1524: true,
     'langri-sha': true,
     sajera: true,
     yeoyou: true },
  license: 'MIT',
  version: '6.0.0',
  browser:
   { './lib/api/register/node.js': './lib/api/register/browser.js',
     'esprima-fb': false },
  scripts: { bench: 'make bench', test: 'make test' },
  dependencies:
   { 'babel-code-frame': '^6.0.0',
     'babel-generator': '^6.0.0',
     'babel-helpers': '^6.0.0',
     'babel-messages': '^6.0.0',
     'babel-template': '^6.0.0',
     'babel-runtime': '^6.0.0',
     'babel-traverse': '^6.0.0',
     'babel-types': '^6.0.0',
     babylon: '^6.0.0',
     'convert-source-map': '^1.1.0',
     debug: '^2.1.1',
     esutils: '^2.0.0',
     'home-or-tmp': '^1.0.0',
     json5: '^0.4.0',
     lodash: '^3.10.0',
     minimatch: '^2.0.3',
     'path-exists': '^1.0.0',
     'path-is-absolute': '^1.0.0',
     private: '^0.1.6',
     regenerator: '0.8.35',
     'shebang-regex': '^1.0.0',
     slash: '^1.0.0',
     'source-map': '^0.4.0',
     'source-map-support': '^0.2.10' },
  devDependencies: { 'babel-polyfill': '^6.0.0' },
  bugs: { url: 'https://github.com/babel/babel/issues' },
  dist:
   { shasum: '26c76dbbba53d36768d7d5e4c44e036dfe72038f',
     tarball: 'https://registry.npmjs.org/babel-core/-/babel-core-6.0.0.tgz' },
  directories: {} }
</details>

**Comment by danez** [comment]
I also cannot reproduce this. Can successfully download 6.0.0. https://registry.npmjs.org/babel-core/-/babel-core-6.0.0.tgz

**Comment by aaronang** [comment]
Closing this issue due to long period of inactivity. If this is still an issue, please provide us an example repository that reproduces this problem, or join our [Slack channel](https://slack.babeljs.io/) for faster back-and-forth.

**Comment by hzoo** [comment]
This is also fixed by https://github.com/lerna/lerna/pull/595 now (publishes packages in topological order)
