### ISSUE TITLE
Module bundler

### ISSUE THREAD

**Issue by juancabrera** [babel/babel#495]
One of the best features of Traceur that I'm missing here is the option for inline modules. As they [describe it](https://github.com/google/traceur-compiler/wiki/Options-for-Compiling#options-for-modules): 
> modules='inline': All dependencies of the root modules and/or scripts are compiled into a long script that creates modules upon execution then runs the dependents.

Doing this we don't have to use an AMD loader or Browserify to load the modules, which I think is a great option/feature.

**Comment by sebmck** [comment]
This is something that [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler) did with a "bundle" formatter. @eventualbuddha has been working on abstracting it out and I've been considering implementing it in the core.

**Comment by juancabrera** [comment]
I think this should be definitely in the core, I'd be happy to help!

**Comment by sebmck** [comment]
Ping @eventualbuddha. How's your progress on extracting out the module bundler and would it be trivial to integrate?

**Comment by developit** [comment]
I hate to leave +1 comments, but this would eliminate my only current problem working with Babel.

**Comment by sebmck** [comment]
@developit It's a non-trivial request and it's not something I'm willing to maintain or plugin if it's going to be extremely hard which it likely is. Is there a reason you just can't use browserify or webpack?

**Comment by developit** [comment]
No, those are the avenues I'm exploring now. My build process seems to be inverted, though. It's possible the solution here is just to switch from Gulp to Browserify.

**Comment by sebmck** [comment]
You wouldn't be able to use npm modules with the proposed module bundler anyway.

**Comment by developit** [comment]
In my case I'm bundling because the result is a standalone library. I think a plugin would be ideal - I have been trying to bandaid a solution together by having Babel output AMD modules, which then get inlined  and concatenated via amdclean/concat.  If I come up with a solution, I'll probably wrap it up into a blog post or a boilerplate repo of some kind to help out any others looking to build standalone libraries via Babel.

**Comment by sebmck** [comment]
Great, that'd be awesome! I'm still interested in the feasibility of including a built-in module bundler but so far it's not looking too good.

**Comment by sebmck** [comment]
Closing this as it's currently out of scope and is unnecessary baggage.

**Comment by Rich-Harris** [comment]
@developit (and anyone else who needs this feature) - @eventualbuddha and I have been working on an ES6 module bundler called [esperanto](https://github.com/esperantojs/esperanto/wiki) which does exactly what you need (and generates more compact output than browserify/requirejs+amdclean). My own workflow is ES6 -> babel (blacklist `es6.modules` option) -> esperanto. It's used by Ember among others.
