### ISSUE TITLE
asyncGenerator helper's output, in combination with transform-es2015-function-name, generates invalid module code

### ISSUE THREAD

**Issue by Kovensky** [babel/babel#4952]
### Input Code

https://github.com/babel/babel/blob/26e79c5/packages/babel-helpers/src/helpers.js#L166

See also http://astexplorer.net/#/Id14lx61E9. Disable transform (why is it enabling itself?) and change the parser to `acorn`, then uncomment the first line.

### More Information

https://github.com/webpack/webpack/issues/3432 https://github.com/ternjs/acorn/issues/486

### Possible Solution

Change the function-name transform to avoid naming a function with `await`.

Using `await` as an identifier anywhere is forbidden in the `module` parse goal, which may happen if the file uses `import` / `export` _without_ using a babel plugin to transform them: https://tc39.github.io/ecma262/#prod-AwaitExpression

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/4952 landed in master, need to release
