### ISSUE TITLE
Remove/Change the limit of the babel-generator deopt message

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4957]
[BABEL] Note: The code generator has deoptimised the styling of "app.js" as it exceeds the max of "100KB".

Code is at https://github.com/babel/babel/blob/39c92160f7a0231ea60f4058469e21f44f3b372f/packages/babel-generator/src/index.js#L80-L86

**Comment by apsdehal** [comment]
@hzoo I am planning to open up a PR for this, but I don't quite understand what exactly is expected change?

**Comment by hzoo** [comment]
@apsdehal Ah sorry for not being clear. The change was to either up the limit or to remove it entirely. It does seem that @existentialism made a PR already (if you'd like to review it would be swell)

**Comment by existentialism** [comment]
@apsdehal Sorry, I threw it together last night before seeing your message. If we wind up deciding to remove it, more than happy to pass the baton over to you!

**Comment by apsdehal** [comment]
No problem, I will pick something else.
