### ISSUE TITLE
useBuiltIns config for react and stage-x presets

### ISSUE THREAD

**Issue by insin** [babel/babel#4960]
I'd like to make use of `useBuiltIns` in the react and stage-x presets as I'm already polyfilling `Object.assign()` where not available.

In the speculative implementation commit below, is validating the config in the stage where it's actually used and passing it along from lower stage presets the correct approach for the stage-x part of this?

I'm using what the es2015 preset does as a template for backwards-compatibility.

https://github.com/insin/babel/commit/a47d870840c8c6ea6b60723bef54428694423770

**Comment by hzoo** [comment]
Sorry for delay @insin, yeah we can do this. Would be better to do it automatically in the future as part of core. I'm cool if you send the PR so closing in favor of that 👍
