### ISSUE TITLE
When using importScripts to import babel-polyfill inside web worker, the async and await will not work unless importScripts is at the top of the code

### ISSUE THREAD

**Issue by Genert** [babel/babel#4963]
When you import **babel-polyfill** with importScript in the web worker and you want to use async and await, that gets compiled, it will throw following error:
![123123123](https://cloud.githubusercontent.com/assets/1218788/21010698/3622683e-bd56-11e6-8ce1-d269ee4665f8.png)

This appears to be so because the importScript follows AFTER that code, thus making it not work.

However, when manually editing the code to following, it will work _(/.polyfill.min.js is babel-polyfill):_
![32133233](https://cloud.githubusercontent.com/assets/1218788/21010777/a7d8c9dc-bd56-11e6-9536-f7396dead559.png)

So it seems, that the importScripts has to be at the top of the compiled module code when using async and await.

Any ideas to fix this?

**Comment by zloirock** [comment]
cc @benjamn it can be the problem in detection global object [here](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L660-L667), see [this table](https://github.com/zloirock/core-js/issues/86#issuecomment-115759028).

**Comment by Genert** [comment]
I find it odd that if you print self to console before importScripts, it will show that babel polyfill is included.

This is ONLY if it is before async function.

![333333333333333](https://cloud.githubusercontent.com/assets/1218788/21024903/f4cfb9b6-bd8e-11e6-9cc6-f4871441c592.png)
![22222](https://cloud.githubusercontent.com/assets/1218788/21024909/f90461f8-bd8e-11e6-811a-1dbee59886ce.png)

Why it isn't global when included after async?

**Comment by loganfsmyth** [comment]
My guess would be your `parseBSP` function is a function declaration, which means it gets hoisted to the top, which could place it before the `importScripts` call. Your best bet would be to change the original code to be a variable with a function expression, or use a separate file to coordinate the loading.

**Comment by Genert** [comment]
@loganfsmyth Big thanks!

When changing in original code
`async function parseBSP (src, tesselationLevel) {`
to
`const parseBSP = async function (src, tesselationLevel) {`

It does indeed work as it does not get hoisted to the top.

**Comment by Kovensky** [comment]
@Genert that causes problems with module exports -- in ES6 modules, hoisted functions should always be available in the module object, even when being part of a circular dependency loop.

It works fine with regular functions, but async functions have that corner case because of the dependency on regeneratorRuntime...

One way to guarantee babel-polyfill (or whatever it is you want to polyfill) runs first is to replace your entry point with a wrapper that loads the polyfill and then loads the real entry point: `import 'the-polyfill'; import './entry.js'`

**Comment by hzoo** [comment]
I think the workaround is to make polyfill the entry point or in a separate file to get around this issue.
