### ISSUE TITLE
Retaining whitespace/pretty printing

### ISSUE THREAD

**Issue by leebyron** [babel/babel#497]
I use ternaries in a lot of my code, and ideally the transpiled source is as close to the original as possible, but right now ternaries are flattened onto one line:

```js
// source
var foo = condition ?
  then :
  otherwise;

// transpiled
var foo = condition ? then : otherwise;
```

Also, this is one specific example, but I find whitespace removal generally much more aggressive than `es6-transpiler`.

**Comment by gaearon** [comment]
+1

**Comment by gaearon** [comment]
Probably a separate issue but this:

```js
    var image = ImageStore.getInStamp(props.imageUuid, props.stampId),
        sourceImage,
        sourceStamp,
        sourceUser,
        stamp;
```

becomes this:

```js
    var image = ImageStore.getInStamp(props.imageUuid, props.stampId), sourceImage, sourceStamp, sourceUser, stamp;
```

**Comment by sebmck** [comment]
@gaearon It is a separate issue. I'll have to add in better pretty printing to get this kind of behaviour as 6to5 can't retain non-newline whitespace.

**Comment by sebmck** [comment]
Actually I can get:

```javascript
var foo = condition ?
  then :
  otherwise;
```

to turn into

```javascript
var foo = condition ?
then :
otherwise;
```

when newlines are present between the conditions but that's obviously not ideal.

**Comment by gaearon** [comment]
Do we need an umbrella issue to collect these problems, or would you rather have them all reported separately?

**Comment by sebmck** [comment]
@gaearon Umbrella would be easier to maintain as *some* of these are related.

**Comment by leebyron** [comment]
It might make sense to keep an umbrella issue open to track the higher-level issue (or constraint) that 6to5 is not yet capable of retaining non-newline whitespace from the original source. This umbrella issue may be open for a long time given that this is part of the architecture of the parser + transformer, but at least it can stand until a future major version where this could be taken into account.

It might also make sense to document this on 6to5.com in the section comparing different transpilers. es6-transpiler (and recast) preserve original formatting, where many transformers do not.

**Comment by sebmck** [comment]
The main reason that a lot of the original source formatting isn't maintained is performance. I'm considering delegating to code generation back to [recast](https://github.com/benjamn/recast) as was done in previous versions. Only issue is that it's notoriously slow the last time I used it.

**Comment by leebyron** [comment]
IMHO, performance is more important than white-space preservation. I'm aware of the performance issues with Recast. However, tracking this umbrella issue will just maintain honest awareness of the limitation (read: intentional tradeoff) and perhaps in the future some stroke of genius will allow for it to be closed by maintaining perf while enabling white-space preservation.

**Comment by sebmck** [comment]
I figured you'd be aware of it, just wanted to document it for the sake of future discussions.

A lot can be done to retain original formatting that wont introduce significant performance implications, it'd just require some intricate edgecases. For an example on where I've added such an edgecase you can see the quite hacky code with [VariableDeclaration generation](https://github.com/6to5/6to5/blob/master/lib/6to5/generation/generators/statements.js#L169-196). It indents `VariableDeclaration`s with multiple `VariableDeclarator`s while matching up to their `kind` keyword.

For example the ternary issue can be resolved by allowing `ConditionalExpression` `consequent` and `alternate` to be `UserWhitespacable` (only statements and a select [few node types](https://github.com/6to5/6to5/blob/master/lib/6to5/types/alias-keys.json#L47) are allowed to retain their newlines) however the indentation would require the code generator to detect if `ConditionalExpression` child nodes are going to include newlines and include indentation where necessary.

After I'm done working through the more major transformation and parser issues that will be resolved for 3.0.0 I'll hopefully be able to dedicate some time to the actual code generator, there's a lot to be cleaned up and it can definently be made faster and more flexible.

**Comment by sebmck** [comment]
Forgot to update this issue but I rewrote parts of the code generator a couple weeks ago and it's performance is much better and output much nicer. I'm confident I can optimise it further and introduce more heuristics.

**Comment by sebmck** [comment]
Once a CST is agreed upon (see estree/estree#41), input format retention can be done very easily and efficiently.

**Comment by sebmck** [comment]
Closing this until ESTree gets a standardised CST as this the only practical way I see style retention without adverse performance. Since this issue was created Babel now inherits string quotes and indentation.
