### ISSUE TITLE
Specifying a different file (different filename, same file type) for config other than .babelrc

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#4970]
I was looking through the Babel docs, and I don't see a way to specify a different file other than .babelrc for the Babel config.

My use case is I am writing a test runner. A project might use Babel in more than one way. For example, they may transpile their source with some Babel settings, but may transpile their tests with another Babel setting.

So ideally, what I would have in the project root, would be:

```
project-root/
  .babelrc          // used by project source 
   suman.babelrc     // used for transpiling tests
```

my thinking is that when I use babel-cli, I could pass the path to suman.babelrc to babel via the command line, or an env variable, either one.

Is this supported yet? Like I said, had trouble finding out if this is supported. Thanks!

**Comment by ORESoftware** [comment]
It looks like this issue is similar:
https://github.com/babel/babel-loader/issues/107

At the very least, I would like to be able to manually configure the search path for .babelrc, but I would also ideally like to be able to use a different name for the file.

**Comment by ORESoftware** [comment]
This issue is also semi-related:
https://github.com/babel/babel/pull/4892

**Comment by DrewML** [comment]
> my thinking is that when I use babel-cli, I could pass the path to suman.babelrc to babel via the command line, or an env variable, either one.

`.babelrc` supports an `env` key, which is an object with each key mapped to `process.env.NODE_ENV`. [Reference](https://babeljs.io/docs/usage/babelrc/#env-option).

**Comment by ORESoftware** [comment]
Thanks, that might work for me. What I want to avoid though is messing with users files. If someone has a project X and they install suman, suman will have to then write to the existing .babelrc file. It would be a much better experience, IMO, if suman could write out a different .babelrc file that was used for testing only. If the user wanted to manually merge suman.babelrc with .babelrc, that's fine.

Do you think my use case makes sense? 

I also so this:

> Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

That won't work for me, because I would like to put suman.babelrc in a directory that won't necessarily be on the path back to root from the file being run, hope that makes sense.

Please consider allowing babel-cli commands to specify the location/name of .babelrc manually. IMO if that location does not exist, it should be a fast-fail as well.

**Comment by DrewML** [comment]
Do you mind explaining a bit more how your test runner is going to tie in to Babel? Like, where Babel fits into the picture of the test runner? Would love to offer a suggestion, just think I'm missing some details.

**Comment by ORESoftware** [comment]
AVA pretty much as the same use case as mine:

https://github.com/avajs/ava/issues/448

they seem to try to solve it via the env methodology. But AFAICT, that's subpar for both my use case and theirs.

The reason being, user's want to use NODE_ENV=test...they don't really want to use NODE_ENV=ava or NODE_ENV=suman

does that make sense?

**Comment by ORESoftware** [comment]
@DrewML I can try to explain more about suman, but it's very similar to AVA wrt it's use of Babel.

A project has a test directory, which houses .js files which may need to be transpiled. If the user chooses to transpile their tests with Babel (in AVA it's required, with Suman it's very much optional), then they need to tell Babel how to transpile their tests (mostly a presets thing).

When suman is installed (npm install -D suman), it will write a new directory to the project filesystem, called ".suman". In most cases the user will manually move that directory into their test directory, so their project will look like:

// here is what the project looks 

```
project-root/
    node_modules/
    lib/
    test/
       .suman/
        test-src
        test-target
    .babelrc
    yarn.lock

```

what I want to do (ideally) would be to put a separate .babelrc file that corresponds only to the settings for running babel with Suman. Suman abstracts away most of Babel for the user's convenience. So Suman can easily handle the extra command to specify babelrc location.

This is what I want:


```
project-root/
    node_modules/
    lib/
    test/
       .suman/
           suman.babelrc
        test-src
        test-target
    .babelrc
    yarn.lock

```

then when running babel-cli, I would do:

`babel script.js --out-file script-compiled.js --babelrc-location=<project-root>/test/.suman/suman.babelrc`

likewise, with babel-register, I believe I would need this:

```js
require('babel-register', {
 babelrc-location: '<project-root>/test/.suman/suman.babelrc'
});
```

hope it makes sense

**Comment by DrewML** [comment]
Haven't read through that whole thread quite yet, but trying to think through what you've described so far. Just to make sure I'm grokking this:

- User _may_ or may not have a `.babelrc` anywhere in the tree
- Your test runner will transpile the _tests_ only, but not the application code
- You do not want to conflict with the users `.babelrc`, but you also do not want theirs to conflict with the file used by your test-runner.

Is that all accurate?

**Comment by ORESoftware** [comment]
@DrewML sure thing

> - User may or may not have a .babelrc anywhere in the tree

    => that's right

> - Your test runner will transpile the tests only, but not the application code

    => yes, I want to give the user the choice to transpile the test code differently than application code, there should be a separation. For example, if the user wants to run Babel against their tests, but *never* against their application code. Using babel-register, however, it would transpile some of their application code, and there's not much I can do about that. But with Babel-Cli, I believe I can control things so that only the test code is transpiled (right?)

> - You do not want to conflict with the users .babelrc, but you also do not want theirs to conflict with the file used by your test-runner.

     => That's right, I want a clear and bug-free demarcation between the possibly pre-existing .babelrc file that the user already has which dictates how to transpile their application code, versus the .babelrc configuration which they use for the tests. In all likelihood, they may use a more "futuristic" setting for their tests and a more conservative setting for their application code.

**Comment by ORESoftware** [comment]
In my use case, I handle whether they have a .suman directory or not. I will put .babelrc into the .suman directory, so if you want to enforce the name ".babelrc", I could live with that. But what I really need is to manually specify a fixed absolute path to the config, at the command line, at least.

WRT babel-register, that might be trickier to figure out. I guess we could use regex to prevent application code from being transpiled (duh, forgot about that).

**Comment by ORESoftware** [comment]
Just so this conversation doesn't get stale, @DrewML what do you think about this? I am very interested in a good solution to this problem, whatever it may be. The problem being of course, allowing for different babel configurations based off command line input.

**Comment by ORESoftware** [comment]
AFAICT, it should break nothing if Babel allows a new option at the command line: --babelrc-location=foo. I guess one caveat is should Babel keep walking the filesystem or not for more config files? I believe there is another option to tell Babel to walk or not. Right?

**Comment by hzoo** [comment]
I don't think we are going to support other config files/names. We are going to add a .babelrc.js file and deprecate the "env" option. And yes the option to not walk up the tree is `babelrc: false`

**Comment by ThiefMaster** [comment]
Here's a very valid usecase why there **needs** to be a way to set the babelrc path: An application that provides the build infrastructure for plugins. It's using a shared webpack config (that covers most cases) and you point it to a plugin directory that - among other things - contains assets that need to be built with webpack and transpiled with babel.

Obviously we don't want our plugin authors to just copy our babel config since that's messy - people aren't gonna update it whenever we do for example - and right now the only "solution" seems to be creating a symlink from our build script, which is also ugly of course...
