### ISSUE TITLE
6.20 regression for async function length

### ISSUE THREAD

**Issue by daltones** [babel/babel#4977]
### Input Code
```js
function foo({param}) {}
console.log(foo.length); // 1

async function bar({param}) {}
console.log(bar.length); // 0 (!)
```

### Babel Configuration (.babelrc, package.json, cli command)
```json
{
  "plugins": [
    "transform-async-to-generator"
  ]
}
```

### Expected Behavior
`bar.length` should be 1, as `foo.length` is.

### Current Behavior
Function `bar` is being transformed as a function without any params:
```js
let bar = (() => {
  var _ref = _asyncToGenerator(function* ({ param }) {});

  return function bar() {
    return _ref.apply(this, arguments);
  };
})();
```

### Possible Solution
I guess that's a regression from #4901.

### Your Environment
| software         | version
| ---------------- | -------
| Babel            |  6.20
| node             |  7.2.1
| yarn              |  0.17.10
| Operating System | Arch Linux

**Comment by hzoo** [comment]
Ah should be a simple fix as well, thanks for the report

**Comment by loganfsmyth** [comment]
Ugh, my bad.

**Comment by daltones** [comment]
Thanks for the quick response! 😃

**Comment by hzoo** [comment]
should be fixed by https://github.com/babel/babel/pull/4978 - once tests pass will merge/release

**Comment by hzoo** [comment]
Released https://github.com/babel/babel/commit/71a9e3275d49ece0cf34a8c7f84ebd47e28a7521, should just need to rm -rf and install async-to-gen plugin again or stage-4
