### ISSUE TITLE
No compatible version found: babel-types@^6.20.0

### ISSUE THREAD

**Issue by trigun539** [babel/babel#4981]
When installing babel-preset-latest

Getting following error on windows (for some weird reason, it works on Mac...):

No compatible version found: babel-types@^6.20.0

Latest it sees is 6.19.0

![image](https://cloud.githubusercontent.com/assets/508205/21051657/609504de-bdef-11e6-895c-3d08abdc330c.png)

**Comment by akzhan** [comment]
Looks like problem with your's local npm repostory.

See #4779 for example.

**Comment by hzoo** [comment]
Similar to ^ yeah, closing!
