### ISSUE TITLE
Infinite loop in babel-plugin-transform-object-rest-spread@6.20.x

### ISSUE THREAD

**Issue by leebyron** [babel/babel#4984]
Detected via a Greenkeeper update on graphql.js https://github.com/graphql/graphql-js/pull/617

Here's a link to the looping stack trace: https://travis-ci.org/graphql/graphql-js/jobs/182442044

No errors before the patch, so I expect the error to be a recent commit to rest-spread transformation.

**Comment by leebyron** [comment]
Ah, sorry. This is a dupe of #4972 - should have checked the closed issues :)

**Comment by hzoo** [comment]
Oh yea I see my 2 failed attempts 😄 , we should enable it again on Babel (or run latest babel on itself and test again before publish)
