### ISSUE TITLE
can I use deeply destructuring import in es6 syntax?

### ISSUE THREAD

**Issue by L-Jovi** [babel/babel#4996]
I notice that es6 destructuring import could implement like below way,

__foo.js__

```
export default () => {
  return {
    a: 'b'
  }
}
```

__index.js__

```
import foo from './foo';
export default foo;
export const bar = foo();
```

so I can use module,

```
import foo, { bar, } from 'my-module';
```

but how could I use deeply destructuring import from my-module, I always failed by following below way,

```
import foo, { bar: { a } } from 'my-module';
```

it seem like es6 already implement above syntax, but how to use it..

thanks for your time,

regards.

**Comment by milesj** [comment]
As I recall, ES2015 imports are not destructured objects. This syntax won't work nor do I believe it's supported. Just do this:

```
import foo, { bar } from 'my-module';

const { a } = bar;
```

**Comment by hzoo** [comment]
Yep the `{}` syntax in imports is for "named" imports and is not destructuring even though it looks like it or seems similar. You can always destructure in another statement though afterwards.

Maybe this should be a better error in babylon?

---

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by L-Jovi** [comment]
@milesj  @hzoo   thanks for your time and patience :)

**Comment by abhinavsingi** [comment]
@milesj is it officially documented (or in code) anywhere where you can recommend? https://github.com/babel/babel/issues/4996#issuecomment-266978120

**Comment by milesj** [comment]
@abhinavsingi Official docs are best: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by hzoo** [comment]
We have a better error message now:

https://github.com/babel/babylon/pull/288/files
