### ISSUE TITLE
Merge babel-plugin-transform-es2015-modules-strip into Babel's codebase.

### ISSUE THREAD

**Issue by bardiharborow** [babel/babel#5000]
While upgrading to Babel v6 over at [twbs/bootstrap](https://github.com/twbs/bootstrap), I ran into the missing [`modules: 'ignore'` functionality](http://henryzoo.com/babel.github.io/docs/usage/modules/#ignore) that was present in Babel v5. I published [babel-plugin-transform-es2015-modules-strip](https://github.com/bardiharborow/babel-plugin-transform-es2015-modules-strip) on npm to fix the issue. There is however no reason such a small package (literally just `ModuleDeclaration(path) { path.remove(); }`) should be maintained separately to Babel. Would the Babel team be interested in taking this over?

**Comment by loganfsmyth** [comment]
Given that the usecase is relatively uncommon, I'd probably vote for not including this as a core package.

I know there was talk of having a page in the docs for recommended third-party plugins, perhaps this could be linked in there?

**Comment by bardiharborow** [comment]
A bit more about our use-case:

> Over at Bootstrap, we store es6 source files in `js/src/*.js`. These are transpiled to `js/dist/*.js` as individual plugins and concatenated to form `dist/js/bootstrap.js`. End-users can either import the es6 sources files in their code (and have their transpiler deal with packaging issues), or simply include `dist/js/bootstrap.js` into their page. We trialed UMD builds at one stage but that resulted in a myriad of issues. Until v8 ships native module support (and probably for quite some time after that given browser support), we want to be able to simply strip the import/exports from the source files and rely on the classes being defined in the top scope, i.e. as globals.

It seems to me that it must be a fairly standard requirement to want to support es6, and es5 as a bundled file. The key part here is that this was even supported by Babel 5.x, but appears to have been dropped. Was there any particular rationale to this?

If I can't convince y'all, I'd be very happy if you'd link to the plugin. I'm around on Slack as well if anyone wants to discuss.

**Comment by DrewML** [comment]
> It seems to me that it must be a fairly standard requirement to want to support es6, and es5 as a bundled file

It is! But the way it is being done in Bootstrap is very unusual. For an example of how most projects handle this, take a look at [react-virtualized](https://github.com/bvaughn/react-virtualized/blob/ae38b6f/package.json#L17-L18). For those that want to use modules using ES6 import syntax, there is a build to leave import/export in. For those that want globals (or AMD or CommonJS), a UMD build is used, which satisfies all 3 of those use-cases with a single file.

**Comment by Kovensky** [comment]
See also the `"module"` field in that `package.json`, which should point to an ES5 build that still has `import` / `export` declarations left in. `"jsnext:main"` is similar but is for compatibility with rollup.

**Comment by hzoo** [comment]
I don't think we're going to take the plugin into the repo. Thanks for making a plugin though and really glad it's working for bootstrap though!

Maybe we can have another repo for 3rd party plugins or move to the org if you think it will have greater visibility but I don't think we will manage it. Let me know if you want to do something like that (can join slack and talk too)

**Comment by aaronang** [comment]
Maybe https://github.com/babel/awesome-babel?
