### ISSUE TITLE
babel-preset-react bug when using ignore option

### ISSUE THREAD

**Issue by mskec** [babel/babel#5002]
### Input Code
This is the repo which reproduces the problem: https://github.com/mskec/babel-preset-react-demo
To reproduce it:

1. clone repo: `git clone https://github.com/mskec/babel-preset-react-demo.git`
2. `npm install`
3. `npm start`
4. To see that the problem is with `babel-preset-react`, remove it from `npm start` command and run it again. Script should throw different error `Error: Options {"loose":true} passed to /Users/mskec/dev/babel-demo/node_modules/babel-preset-es2015/lib/index.js which does not accept options.`, but I think thats whole different problem as I am not passing this option.

### Expected Behavior
I am trying to run script with `babel-node`, in a way that it also transpiles one module from `node_modules`. To do this I am using `--ignore` option. Full command:  `babel-node --ignore='node_modules/(?!my_lib)' --presets=es2015,stage-0,react index.js`.
I except command to run script with `my_lib` from `node_modules` transpiled in runtime.

### Current Behavior
This is the error I am getting:
```> babel-node --ignore='node_modules/(?!my_lib)' index.js

/Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

TypeError: require(...) is not a function (While processing preset: "/Users/mskec/dev/babel-demo/node_modules/babel-preset-react/lib/index.js") (While processing preset: "/Users/mskec/dev/babel-demo/node_modules/babel-preset-react/lib/index.js") (While processing preset: "/Users/mskec/dev/babel-demo/node_modules/babel-preset-stage-0/lib/index.js") (While processing preset: "/Users/mskec/dev/babel-demo/node_modules/babel-preset-es2015/lib/index.js")
    at exports.default (/Users/mskec/dev/babel-demo/node_modules/babel-plugin-transform-react-jsx/lib/index.js:14:17)
    at Function.memoisePluginContainer (/Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:109:13)
    at Function.normalisePlugin (/Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:142:32)
    at /Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at /Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:260:14
    at /Users/mskec/dev/babel-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:329:22
    at Array.map (native)
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel-cli       |  6.18.0
| node             | v6.7.0
| npm              | 3.10.3
| Operating System | OSX 10.11.6

**Comment by jaylone** [comment]
Same problem.

**Comment by loick** [comment]
Same here too :/

**Comment by hzoo** [comment]
This should be fixed in Babel 7 with https://github.com/babel/babel/pull/5487

can test with: 
"babel-core": "7.0.0-alpha.3"
"babel-cli": "7.0.0-alpha.3"
"babel-register": "7.0.0-alpha.5"
