### ISSUE TITLE
[transform-modules-umd] Better exported name for main module

### ISSUE THREAD

**Issue by julien-f** [babel/babel#5003]
It would be nice if `babel-plugin-transform-modules-umd` would use the package name as exported name if the current file is `main` module of the package.

I would allow me to add this transform into all my modules and have them being usable in browsers (via [unpkg.com](https://unpkg.com/) for instance) without special config :)

**Comment by xtuc** [comment]
Could you provide an "Expected Behavior" and "Current Behavior" sections.

**Comment by julien-f** [comment]
### Expected Behavior

The `index.js` module of my `foo-bar` package should be expose as `global.fooBar`.

### Current Behavior

The `index.js` module of my `foo-bar` package is exposed as `global.index`.

**Comment by xtuc** [comment]
We need a generic approach, which doesn't depend on a given directory structure.

One possible solution could be to expose an option to be able to custom the final module name and use #4630 (babelrc.js) to resolve the `package.json` name.

**Comment by julien-f** [comment]
Hmm, I'm not sure it would be necessary, my use case is only for the entry point of the package.

**Comment by nicolo-ribaudo** [comment]
This can be easily done by using the `moduleId` option:

```js
const path = require("path");

module.exports = {
  // Your normal config
  presets: [
    ["@babel/preset-env", { modules: "umd" }],
  ],

  overrides: [{
    // Only apply these options to the entry point
    include: path.resolve(__dirname, "src/index.js"),

    moduleId: require("./package.json").name,
    // If you prefer, you can specify the exact global identifier:
    moduleId: "myLibrary",
  }],
};
```

By doing so, Babel transforms don't have to understand node's resolution algorithm and it doesn't have to read non-babel options from `package.json`.

**Comment by julien-f** [comment]
@nicolo-ribaudo It was a long time ago so I don't remember my exact needs anymore but the whole point was to avoid specific configuration for each package.

Anyway, I don't have this need anymore so I won't reopen.
