### ISSUE TITLE
Support for string padding in es2017

### ISSUE THREAD

**Issue by viebel** [babel/babel#5017]
According to this blog http://www.2ality.com/2015/11/string-padding.html, padding is part of es2017.

However it is not supported in babel yet.

```js
'x'.padStart(5, 'abx')
```
is transpiled to:

```js
'x'.padStart(5, 'abx')
```

Live demo: 
http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017&code='x'.padStart(5%2C%20'abx')

**Comment by hzoo** [comment]
Yep it certainly is, but Babel doesn't compile built-ins. It changes syntax only so you want a polyfill. http://babeljs.io/#polyfill - you can use babel-polyfill.

Also check out https://github.com/babel/babel-preset-env with the useBuiltIns option

**Comment by viebel** [comment]
Thanks a lot. It works!
