### ISSUE TITLE
Uncaught ReferenceError: __webpack_require__ is not defined when using with webpack/angular2

### ISSUE THREAD

**Issue by josefromsanjose** [babel/babel#5021]
### __webpack_require__
I am using Babel with Angular2 and Webpack. 
Whenever I use the webpack-server to develop the bundles are created and rendered fine. When try to build the bundle to be used in my .Net mvc application I get the following arrow when the page loads.

`Uncaught ReferenceError: __webpack_require__ is not defined`

### Webpack config
```js
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');
var path = require('path');
var context = path.resolve( __dirname, '..');
var distPath = helpers.distPath(path.join(__dirname, '../'));

module.exports = {
    context: context,
    entry: {
        main:  './main.js',
        polyfills: './resources/polyfills.js',
        vendor: './resources/vendors.js',
    },
    resolve: {
        extensions: ['', '.js', '.css', '.scss', '.html']
    },
    resolveLoader: {
        root: path.join(__dirname, '../', "node_modules")
    },
    output: {
        path: distPath,
        filename: '[name].js',
        chunkFilename: '[id].chunk.js',
        sourceMapFilename: '[name].map',
        pathInfo: true
    },

    module: {
        loaders: [
            { test: /\.js$/, exclude: /node_modules/, loader: "babel-loader"},
            { test: /\.html$/, loader: 'html' },
            { test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/, loader: 'file?name=assets/[name].[hash].[ext]' },
            {
                test: /\.css$/,
                exclude: helpers.root('components', 'root'),
                loaders: [ExtractTextPlugin.extract('style', 'css?sourceMap'), 'raw']
            },
            { test: /\.scss$/,  loader:'raw!sass?sourceMap!sass-resources'}
        ]
    },
    sassResources: [
        './components/root/mians.scss'
    ],
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({name: ['vendor', 'polyfills']}),
        new ExtractTextPlugin("main.min.css"),
    ]
};

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "angular2"],
  "plugins": [ "transform-es2015-modules-commonjs"]
}
```
### Babel packages

```
    "babel-cli": "6.18.0",
    "babel-core": "6.18.2",
    "babel-loader": "6.2.9",
    "babel-plugin-add-module-exports": "0.2.1",
    "babel-plugin-transform-es2015-modules-commonjs": "6.18.0",
    "babel-preset-angular2": "0.0.2",
    "babel-preset-es2015": "6.18.0",
```

### What I attempted
I am using Babel 6 and initially I tried adding the following following plugin but it made no difference. 
`transform-es2015-modules-commonjs`
In the generated bundle I see the declared `__webpack_require__` function

I am at a lost. I am not sure if I am not configuring Webpack or Babel correctly. Any help thanks in advance. 

| software         | version
| ---------------- | -------
| Babel            |  
| node             | v6.9.0
| npm              | v3.10.8
| Operating System |

**Comment by danez** [comment]
This seems more related to webpack than to babel.

But I think that the commons chunk might be setup incorrectly, maybe try without the commons chunk first. Also I think supplying an array as name is not doing what you expect todo, but not sure about that. Also the order that the final files are loaded with is important.
https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin

If you have more questions please use the support channels of webpack. https://github.com/webpack/webpack#contributing

**Comment by exvu** [comment]
Did you solve this problem? I encountered the same problem
