### ISSUE TITLE
babel-core should consume `debug/node` directly

### ISSUE THREAD

**Issue by thebigredgeek** [babel/babel#5024]
https://github.com/visionmedia/debug/issues/389

^ When releasing 2.5.0, we noticed in introduced a breaking change in babel-core which was referencing `debug/node` rather than simply `debug`.  I added a hook + hotfix that should prevent issues, but I think it would be wise to consume `debug` directly rather than referencing it's internal source files.  Is there anyway this could be fixed for an uncoming release?  I can put in a PR if necessary

**Comment by azu** [comment]
I dig changelog:

>  Use `debug/node` instead of `debug` to avoid browserify using the browser version that references `window`.
> https://github.com/babel/babel/blob/de975b9660014a4533c90190b297352495636530/CHANGELOG-6to5.md#3015

**Comment by golsan** [comment]
+1

**Comment by thebigredgeek** [comment]
@azu we stopped including built assets and assume that the end user is using some sort of module bundler.  The only case that we are still using browserify for is automated browser testing.  Are you saying that debug thinks that it's in a browser environment when it's not?

**Comment by ganbi-bor** [comment]
+1

**Comment by golsan** [comment]
fixed in debug v2.5.1

**Comment by loganfsmyth** [comment]
Thanks for the quick fix. We can absolutely fix this, at this point we'll have to look at the git history to figure out just what this was trying to resolve originally. No one involved with the project now is likely to know.

It'd be awesome if you're willing to leave in the `/node` file as a pass-through for backward-compat in this major version, so that people are still able to install old versions of `babel-core` without having to pin `debug` as well.

Sorry for the trouble.

**Comment by thebigredgeek** [comment]
@loganfsmyth yeah no worries.  Let's just see if we can work together to migrate away from that.  We definitely don't mind supporting it for now given how many people depend on babel, but it's something we will want to get rid of for our v3 release which should be within a month of so.

**Comment by xtuc** [comment]
There since a while, see https://github.com/babel/babel/commit/c60ad89937828f62641bbebe05fcddd8dc3b7c3d.

As pointed out by @azu, this was motivated. We should figure out if there is still such an issue.

**Comment by artemave** [comment]
Because of this issue, `debug` module doesn't log into the debug console in electron.
