### ISSUE TITLE
Generator function can't be transpilled if defined after async function

### ISSUE THREAD

**Issue by happylynx** [babel/babel#5032]
If input code contains definition of async function followed (not necessarily immediately) by generator function definition then transpilled result fails with following error:

```
/tmp/babel-demo/dist/main.bundle.js:8231
	var _marked = [foo].map(_regeneratorRuntime.mark);
	                        ^

ReferenceError: _regeneratorRuntime is not defined
    at Object.<anonymous> (/tmp/babel-demo/dist/main.bundle.js:8231:26)
    at __webpack_require__ (/tmp/babel-demo/dist/main.bundle.js:30:30)
    at Object.<anonymous> (/tmp/babel-demo/dist/main.bundle.js:58:19)
    at __webpack_require__ (/tmp/babel-demo/dist/main.bundle.js:30:30)
    at /tmp/babel-demo/dist/main.bundle.js:50:18
    at /tmp/babel-demo/dist/main.bundle.js:53:10
    at webpackUniversalModuleDefinition (/tmp/babel-demo/dist/main.bundle.js:3:20)
    at Object.<anonymous> (/tmp/babel-demo/dist/main.bundle.js:10:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

If the order of function definitions is inverted of only async or only generator functions are used, transpilled code runs ok.

[Downloadable repro project](https://uloz.to/!Ne1dMFw8lTvO/ar-zip).

[Transpilled bundle](http://pastebin.com/VGkWFZqA). It seems that for some reason even if module 300 (starting at line 8256) defines global variable `regeneratorRuntime`, line 8231 expects variable `_regeneratorRuntime`.

### Input Code

main.js (transpiles ok but fails during runtime)
```js
async function bar(p) {
}

function* foo(p) {
}
```
main.js, definitions swapped (transpiles ok, runs ok)
```js
function* foo(p) {
}

async function bar(p) {
}
```

### Babel Configuration (.babelrc, package.json, cli command)

babel.rc

```js
{
    "presets": ["es2015"],
    "plugins": [ "transform-async-to-generator", ["transform-runtime", {
        "helpers": false,
        "polyfill": false,
        "regenerator": true}]]
}
```

webpack.config.js

```js
module.exports = {
    entry: {
        main: ['babel-polyfill', './src/main.js']
    },
    output: {
        path: './dist',
        filename: "[name].bundle.js",
        publicPath: '/',
        libraryTarget: 'umd'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            }
        ],
    }
};
```

package.json

```js
{
  "name": "babel-demo",
  "version": "1.0.0",
  "scripts": {
    "build": "webpack",
    "test": "rm -rf dist && npm run build && node -p 'c = require(\"./dist/main.bundle.js\"); console.log(c)'"
  },
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-async-to-generator": "^6.16.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "webpack": "^1.14.0"
  }
}
```

### Expected Behavior

Transpilation success doesn't depend on order of definitions of functions.

### Current Behavior

If function definitions are wrongly sorted, it fails during runtime.

### Possible Solution

A workaround is to carefully order function definitions.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.21.0
| node             | v7.3.0
| npm              | 4.0.5
| Operating System | Fedora 24 x64

**Comment by chhetrisushil** [comment]
is ordering the function definition is the only solution? or is there another workaround?

**Comment by happylynx** [comment]
As far as I know it is the only workaround.

**Comment by loganfsmyth** [comment]
This should be fixed in Babel 7.x
