### ISSUE TITLE
leadingComments attached to function identifier if function body contains spread and flow annotation

### ISSUE THREAD

**Issue by tmcw** [babel/babel#5034]
### Input Code

```js
/* hi */
function commentsAttachedToIdentifier() {
  var x = (...args: any) => {};
}
```

### Babel Configuration (.babelrc, package.json, cli command)

Presets: **react**. No other configuration: [this behavior is visible in the repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=react&code=%2F*%20hi%20*%2F%0Afunction%20commentsAttachedToIdentifier()%20%7B%0A%20%20var%20x%20%3D%20(...args%3A%20any)%20%3D%3E%20%7B%7D%3B%0A%7D%0A%0A%2F*%20hi%20*%2F%0Afunction%20commentsAttachedToFunction()%20%7B%0A%20%20var%20x%20%3D%20(args%3A%20any)%20%3D%3E%20%7B%7D%3B%0A%7D)

### Expected Behavior

In both cases, the comment node should be attached to the FunctionDeclaration node, and in Babel's output, it should land at the same place as in the input: before the `function` keyword.

### Current Behavior

When the function contains a spread expression, the comment node is attached to the function's Identifier node, and on output, it lands _after_ the `function` keyword.

For the previous example the output is:

```js
function /* hi */commentsAttachedToIdentifier() {
  var x = (...args) => {};
}
```

* [behavior as shown in the REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=react&code=%2F*%20hi%20*%2F%0Afunction%20commentsAttachedToIdentifier()%20%7B%0A%20%20var%20x%20%3D%20(...args%3A%20any)%20%3D%3E%20%7B%7D%3B%0A%7D%0A%0A%2F*%20hi%20*%2F%0Afunction%20commentsAttachedToFunction()%20%7B%0A%20%20var%20x%20%3D%20(args%3A%20any)%20%3D%3E%20%7B%7D%3B%0A%7D)
* [behavior as shown in astexplorer](http://astexplorer.net/#/bsxdcJ0dy3)

### Possible Solution

Digging led to [the typecastToParameter](https://github.com/babel/babylon/blob/ba96b91f4093e994761217eb969c7d432b9491ab/src/plugins/flow.js#L775-L783) method in the react/flow parser, which calls finishNodeAt, which calls processComment. I think _maybe_ the way that this redefines the ArrowFunctionExpression, it causes the [comment re-assignment code](https://github.com/babel/babylon/blob/ba96b91f4093e994761217eb969c7d432b9491ab/src/parser/comments.js#L123-L136) to miss the comment later on.

### Context

For the documentation.js usecase, this led to [this downstream issue](https://github.com/documentationjs/documentation/issues/635): we expect a certain pattern in comment attachment, and when that pattern isn't what we expect, we miss the comment and code doesn't get documented.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.1.9
| node             | n/a (website)
| npm              | n/a (website)
| Operating System | n/a (website)

Thanks for your help!

**Comment by kaicataldo** [comment]
I can try to take a look at this since I seem to be working on comments in general right now :D

**Comment by kaicataldo** [comment]
I think this is most likely a Babylon bug since the incorrect comment attachment behavior happens at the AST level.

**Comment by kaicataldo** [comment]
Might not actually get to this for a while, so anyone should please feel free to take this on.

**Comment by aaronang** [comment]
I would like to work on this although I am not yet familiar with the Babel codebase.

**Comment by existentialism** [comment]
@babel-bot move to babel/babylon

**Comment by existentialism** [comment]
Will reopen if it turns out its not strictly a babylon issue
