### ISSUE TITLE
babel-cli npm package is not updated

### ISSUE THREAD

**Issue by pravi** [babel/babel#5044]
The latest version available on npmjs.com is 6.18.0 where as this repo has 6.21.1 tag.

**Comment by loganfsmyth** [comment]
Only packages that are updated get bumped. There have been no changes to `babel-cli` between `6.18` and `6.21.1`

**Comment by hzoo** [comment]
^ yeah, If you check that commit https://github.com/babel/babel/commit/1a8150ef973ccaeadef93d6d42aa8f562ace142f only 1 package is that. If you want to check a package you can just check the source https://github.com/babel/babel/blob/master/packages/babel-cli/package.json. Sorry it can be confusing
