### ISSUE TITLE
babel-types isBinding test fails on params of class methods/arrow functions

### ISSUE THREAD

**Issue by hax** [babel/babel#5049]
### Input Code

```js
const a1 = x => 0
const a2 = (x, [y], ...z) => 0
class T {
  method(x, [y], ...z) {}
}
function f(y) {}
```

### Expected Behavior

For all param identifiers in below code, with babel-traverse or babel-types,
`path.isBindingIdentifier(x)` should return `true`.

### Current Behavior

Currently, all `x` params return `false`. Aka, normal parameters of methods/arrow functions are buggy, but destructuring, rest params and normal functions are ok.

**Comment by nicolo-ribaudo** [comment]
This is fixed in Babel 7.
Demo (open the console): https://astexplorer.net/#/gist/d71bf777273cad02470f1802e3450fa5/latest
