### ISSUE TITLE
--copy-files doesn't copy dot-files

### ISSUE THREAD

**Issue by alecl** [babel/babel#5052]
### Input Code

```js
// A folder with dot-files (from dotenv NPM)
config/.env
config/.env.required
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015"
  ]
}

./node_modules/babel-cli/bin/babel.js functions -d build/ --copy-files --source-maps
```

### Expected Behavior

When using --copy-files dot-files and folders that contain them should be copied as well

### Current Behavior

Folders and dot-files are not copied

### Possible Solution

Files should be copied by default or provide an additional flag or config to include or exclude copying of dot-files

### Context

Wasn't able to run transpiled code without adding a post step to copy the dot-files.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             | 4.5.0
| npm              | 3.10.8
| Operating System | macOS 10.12.2

**Comment by alecl** [comment]
Yeah, I could see how copying dot-files by default which can be used for secrets may be an unintentional bad experience.

How about adding another flag to specifically enable copying these types of files?

`--copy-dot-files`

**Comment by DrewML** [comment]
Likely cause:

1. [We read all files in the directory here](https://github.com/babel/babel/blob/9c2794dc85af9ed1aa6bd319ba279d04fb34e392/packages/babel-cli/src/babel/dir.js#L54)
2. `util.readdir` is [fs-readdir-recursive](https://www.npmjs.com/package/fs-readdir-recursive).
3. The readme for `fs-readdir-recursive` says the default filter provided ignores dot files.

**Comment by xtuc** [comment]
The be clear, the idea here is to specify the flag : `--copy-dot-files` in addition to `--copy-files` to also copy files starting with a dot. In [fs-readdir-recursive](https://www.npmjs.com/package/fs-readdir-recursive#api) it is an option of the `read` API.

**Comment by shubheksha** [comment]
I'd like to work on this!

**Comment by xtuc** [comment]
Cool thanks :+1:. You can join our Slack if you need help ([#chat](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#chat)).

**Comment by shahriar-git** [comment]
Any News on this? I am not being able to copy .eslintrc file to my compiled directory :(

**Comment by sparcut** [comment]
Update? I'd also like an easier way of copying my `.env`

**Comment by Swivelgames** [comment]
Friendly poke. No, seriously, poke... What's the deal with this?

If you all need help, I'll gladly pitch in a PR! 😄

**Comment by Swivelgames** [comment]
Thanks @existentialism for working this! 😄 

Is it possible to get an ETA on when this would likely make it's way into a release?

**Comment by nischayv** [comment]
Any idea when this will be in the release?

**Comment by Swivelgames** [comment]
What @nischayv said... 😕

**Comment by Swivelgames** [comment]
@existentialism @danez @xtuc:

What @nischayv said... 😕

**Comment by existentialism** [comment]
You can check it out early in [7.0.0-beta.3](https://github.com/babel/babel/releases/tag/v7.0.0-beta.3) which we dropped yesterday.

**Comment by sparcut** [comment]
For anyone coming from google, `--include-dotfiles` is the flag to use this. (At the moment, you'll need to get 7.0.0-beta.3 as mentions above)

@existentialism Cheers, small feature but saves a lot of mucking around and hacky ways to move dotfiles. <3
