### ISSUE TITLE
transform-es2015-modules-commonjs outputs code that triggers warning in UglifyJS

### ISSUE THREAD

**Issue by fizker** [babel/babel#5054]
The warning in question is `Side effects in initialization of unused variable ...`.

### Input Code

```js
export var foo1 = 1;
export let foo2 = 2;
export const foo3 = 3;
```

### Babel Configuration (.babelrc)

```js
{
	"presets": [ "es2015" ]
}
```

### Expected Behavior

The outputted code should not trigger any warnings about unused variables, because the code pre-babel does not have any unused variables.

### Current Behavior

The code that is generated (as defined by [the tests](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs/test/fixtures/interop/exports-variable)) basically looks like

```js
var foo1 = exports.foo1 = 1;
let foo2 = exports.foo2 = 2;
const foo3 = exports.foo3 = 3;
```

While this is technically correct, it does create some vars which are never used.

### Possible Solution

I see two solutions:

1. Reorder the two assignments:

    ```js
    var foo1 = 1;
    exports.foo1 = foo1;
    let foo2 = 2;
    exports.foo2 = foo2;
    const foo3 = 3;
    exports.foo3 = foo3;
    ```

2. Don't create vars that are not used later on:

    ```js
    exports.foo1 = 1;
    exports.foo2 = 2;
    exports.foo3 = 3;
    ```

There is also a work-around:

```js
// pre-babel code
var foo1 = 1;
let foo2 = 2;
const foo3 = 3;

export { foo1, foo2, foo3 }
```

The workaround is suboptimal because it requires the developer to repeat all variable names.

### Context

In our codebase, we use the basic `export const bla = ...` construct quite a lot to create constants and the like. Unfortunately, this leaves a lot of warnings about unused vars that we cannot avoid without messing up our code.

And to make matters worse, we are running babel through VisualStudio, where the mere presence of the word `error` in stdout fails the build. And we just happened to make a logger with `export const error = generateErrorLogger()`, which broke our build because it generated the message `Side effects in initialization of unused variable error`.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.5.2, master (b443f3e158a32f7dc0f607697da8982915dd5ab3)
| node             | 6.9.2
| npm              | 3.10.9
| Operating System | macOS, windows

**Comment by Kovensky** [comment]
The generated exports are bad, but for a different reason (live binding).

However, I'd still suggest disabling the uglify warnings and using a linter like eslint ([no-unused-vars](http://eslint.org/docs/rules/no-unused-vars), [no-unused-expressions](http://eslint.org/docs/rules/no-unused-expressions)) to find dead code.
