### ISSUE TITLE
Allow specifying a range in babel-code-frame

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#5064]
code frame is used in TSLint. Lint errors have a range instead of a single character pointer. Can we extend the code frame to accept a range too? 

A lint error can have a range like this: 

```js
var f = ab => {};
        ~~             
```

I volunteer to make the change if it's an acceptable change from your side.

**Comment by hzoo** [comment]
That would be interesting! Errors can certainly have a range.. 👍 from me at least

**Comment by mohsen1** [comment]
Let's discuss the API for it then. To keep backward compatibility we can add an `end` option to options parameter:

```js
const rawLines = `class Foo {
  constructor()
}`;
const lineNumber = 2;
const colNumber = 2;

const result = codeFrame(rawLines, lineNumber, colNumber, { end: {line: 2, column: 16} });
```

Results to: 

```sh
  1 | class Foo {
> 2 |   constructor()
    |   ~~~~~~~~~~~~~
  3 | }
```


A multiline output example:

```sh
  1 | const fn = 
> 2 |   () => 
    |   ~~~~~
> 3 |   { /**/  }
    |   ~~~~~~~~~
```

**Comment by mohsen1** [comment]
The other option is to change the API with a major version bump. Most of ASTs have `start` and `end` objects with `line` and `column` in them. It's easier to pass a node from some AST to codeFrame. 

```ts
codeFrame(
  rawLines: string,
  start: {line: number; column: number;},
  end: {line: number; column: number;},
  options: {}
)
```

**Comment by hzoo** [comment]
Even though we are doing a major bump I'd rather go with the original api above. I don't think ranges are that common? We could do both and deprecate the old version

**Comment by mohsen1** [comment]
Ok cool. A few questions:

* How you do method arguments list overload in FlowType?
* How you throw a deprecation warning?

**Comment by okonet** [comment]
@hzoo I would break the API TBH and make it accept a `loc` object since it seem pretty common in different ASTs:

ASTs having `loc` object:
- babel-eslint
- babylon
- babylon6
- esformatter
- recast
- flow
- traceur (has `location`)

ASTs without `loc`:
- acorn
- espree
- esprima

So to me having this function accept objects as arguments seems like a better choice so I'm in favor of https://github.com/babel/babel/issues/5064#issuecomment-270290033 proposal

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/5646
