### ISSUE TITLE
Export * from 'module' generates import statements

### ISSUE THREAD

**Issue by posva** [babel/babel#5067]
The issue at #4273 was closed but the problem still exists. There is even a [repo](https://github.com/julien-f/babel-t7334) with a repro

### Input Code

```js
export * from 'module'
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "plugins": [
      "transform-runtime"
    ],
    "presets": [
      "es2015"
    ]
  }
```

### Expected Behavior

There should be no `import` statement in the output file

### Current Behavior

The file contains
```js
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
import _Object$keys from 'babel-runtime/core-js/object/keys';
```

### Possible Solution

A **workaround** is adding the `polyfill: false` in the transform config:

```js
{
  "presets": ["es2015"],
  "plugins": [
    [
      "transform-runtime",
      { "polyfill": false }
    ]
  ]
}
```

But this may not suit all cases

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.8.0
| node             | 6.9.1
| npm              | 3.10.10
| Operating System | osx

**Comment by loganfsmyth** [comment]
This is unfortunately a known issue that we haven't gotten to, which is likely why the other issue was closed. It seems like the reason for closure was not carried over when babel-bot created the linked issue, sorry about that. The duplicated issue is https://github.com/babel/babel/issues/2877

**Comment by posva** [comment]
@loganfsmyth Oh, thanks I couldn't find the duplicate issue 😅
