### ISSUE TITLE
Bug with parameters transform?

### ISSUE THREAD

**Issue by DarrylD** [babel/babel#5069]
### Input Code

```js
//for this function
var doStuff = ({ name='default' }) => console.log(name)

//This breaks 
doStuff()

//but this works
doStuff({})
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": [
        "next/babel",
        "es2015",
        "stage-2"
    ],
    "plugins": [
        ["transform-runtime"],
        ["transform-es2015-parameters"],
        ["transform-es2015-block-scoping"],
        ["transform-object-rest-spread"],
        ["transform-es2015-for-of", {
            "loose": true
        }]
    ]
}

```

### Expected Behavior

Both should work fine

### Current Behavior

only when i send an object as a param, it works

Not sure if this a bug or not.

**Comment by loganfsmyth** [comment]
This is expected behavior, destructuring reads properties off an object, if you don't pass an object, it will error. This is just like of you did

    var { name='default' } = undefined;

What you need to do is change

    var doStuff = ({ name='default' }) => console.log(name)

to 

    var doStuff = ({ name='default' } = {}) => console.log(name)

hence by giving it a default value of an empty object, it will destructure properly.

**Comment by DarrylD** [comment]
Well that was my initial impression, I tried `var doStuff = ({ name='default' } = {}) => console.log(name)`

I got `Cannot read property 'name' of undefined`

**Comment by DrewML** [comment]
@DarrylD Can you copy/paste the compiled output you're seeing from the example above when you run babel locally?

**Comment by mark0978** [comment]
You can see it working in the [Playground](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=%2F%2Ffor%20this%20function%0Avar%20doStuff%20%3D%20(%7B%20name%3D'default'%20%7D%3D%7B%7D)%20%3D%3E%20console.log(name)%0A%0A%2F%2FThis%20breaks%20%0AdoStuff()%0A%0A%2F%2Fbut%20this%20works%0AdoStuff(%7B%7D)&playground=true)

Once the default argument is applied as metioned by @loganfsmyth

**Comment by DarrylD** [comment]
Reinstalled the package, not sure why it wasn't working before but, it's fine now.

Thanks!
