### ISSUE TITLE
Babel Wraps Produced VariableDeclarations inside IIFE's

### ISSUE THREAD

**Issue by pretodor** [babel/babel#5072]
I was transforming an `AssignmentExpression` node to a `VariableDeclaration` via a plugin and I noticed Babel wrapped the newly-created node inside an IIFE making the variable inaccessible.

### Steps to Reproduce the Issue:

Project structure:
```
projectdir/
    .babelrc
    my-plugin.js
    script.js
    script-compiled.js
```

Command used:
```bash
$ babel script.js -o script-compiled.js
```

```js
// .babelrc

{
  "plugins": ["./my-plugin"]
}
```

```js
// my-plugin.js

export default function ({ types: t }) {
    return {
        visitor: {
            AssignmentExpression(path) {
                path.replaceWith(t.variableDeclaration("let",
                                    [ t.variableDeclarator(path.node.left, path.node.right) ]))
            }
        }
    }
}
```

```js
// script.js

x = 10
export { x }
```

### Expected Behaviour

```js
// script-compiled.js

let x = 10;
export { x };
```

### Current Behaviour

```js
// script-compiled.js

(function () {
  let x = 10;
})();

export { x };
```

### My Environment

| software         | version
| ---------------- | -------
| Babel            | 6.18.0
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | Linux Mint 18

**Comment by alexisvincent** [comment]
Seeing this as well :/

**Comment by pretodor** [comment]
@alexisvincent It turns out it's not Babel's fault. We're replacing an `AssignmentExpression` where in fact we should be replacing the `ExpressionStatement`. Here is a simple fix:

```javascript
// my-plugin.js

export default function ({ types: t }) {
    return {
        visitor: {
            ExpressionStatement(path) {
                path.replaceWith(t.variableDeclaration("let",
                                    [ t.variableDeclarator(path.node.expression.left, path.node.expression.right) ]))
                                                           // expression.type === 'AssignmentExpression'
            }
        }
    }
}
```

(Credit goes to @loganfsmyth for pointing this out.)

**Comment by mattbailey** [comment]
Just so this might get another google hit, I had the same problem with trying to transform this:

```javascript
foo.bar('baz', function() {})
```

into this:

```javascript
const Baz = function() {}
```

I was incorrectly using `CallExpression()` to identify the block, and also should have been using `ExpressionStatement()`

Thanks for this, I would have spent hours...
