### ISSUE TITLE
Class properties are not assigned when `super` is called from an arrow function

### ISSUE THREAD

**Issue by connec** [babel/babel#5073]
### Input Code

```js
class A {}
class B extends A {
  foo = 1
  
  constructor () {
    (() => super())()
  }
}
```
[REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-2&code=class%20A%20%7B%7D%0Aclass%20B%20extends%20A%20%7B%0A%20%20foo%20%3D%201%0A%20%20%0A%20%20constructor%20()%20%7B%0A%20%20%20%20(()%20%3D%3E%20super())()%0A%20%20%7D%0A%7D)

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["transform-class-properties"]
}
```

### Expected Behavior

`this` assignments should be inlined with the `super` call as normal, e.g.

```js
class A {}
class B extends A {

  constructor() {
    (() => {
      var _temp;

      return _temp = super(), this.foo = 1, _temp;
    })();
  }
}
```

### Current Behavior

Currently, the `this` assignments are not output at all, though a `temp` variable is being declared in the right scope to handle it.

### Possible Solution

I would have guessed the `super` lookup wasn't visiting arrow functions, except that the temporary variable has been declared in the right scope, so I have no guesses.

### Context

No real-world case. Exploring edge-cases as part of compiling CoffeeScript classes to ES2015. This came up as a possible solution to fixing `super` with inline assignments in a parameter (#5074).

**Comment by nicolo-ribaudo** [comment]
This bug has been fixed - https://babeljs.io/repl/build/master#?babili=false&browsers=last%202%20chrome%20versions%2C%20last%202%20chromeandroid%20versions%2C%20firefox%20esr%2C%20last%202%20firefox%20versions%2C%20edge%20%3E%3D%2015%2C%20safari%20%3E%3D%2011&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8C-AoUkYCFoFMAeALjgHYAmM8CK00AZgPb3QC80AjNdJ8PcRAQCcArsAL0B0ABQBKRJxoCcBIQOJSZLAHzQIQgA44BM6TM6okQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=stage-1&prettier=false&targets=&version=7.0.0-beta.44&envVersion=7.0.0-beta.40%2Bpr.7388
