### ISSUE TITLE
babel-types is losing `this` scope when building async AST node from existing one

### ISSUE THREAD

**Issue by wkwiatek** [babel/babel#5078]
I've investigated one of the issues of React Hot Loader and it turned out there is a new method class node created from the arrow function property node. So the general code transform flow is like these: 
- take property arrow function 
- get the body 
- create method class (with added suffix in the name) with the same body

### Input Code

Here is the whole repository with whole code: https://github.com/wkwiatek/babel-async-test

I wrote a very simple plugin:
```js
module.exports = ({ types: t }) => ({
  visitor: {
    Class(classPath) {
      const classBody = classPath.get('body')

      classBody.get('body').forEach(path => {
        if (path.isClassProperty()) {
          const node = path.node

          if (node.value && node.value.type === 'ArrowFunctionExpression') {
            const isAsync = node.value.async

            const params = node.value.params
            const newIdentifier = t.identifier('__' + node.key.name + '__COPY__')

            const newMethodBody = node.value.body.type === 'BlockStatement' ? node.value.body : t.blockStatement([t.returnStatement(node.value.body)])

            const newMethod = t.classMethod('method', newIdentifier, params, newMethodBody)
            newMethod.async = isAsync

            path.insertAfter(newMethod)
          }
        }
      })
    }
  }
})
```

Then executed following code to be transformed through it: 
```js
class TestClass {
  hello = async () => {
    console.log(this, 'hello')
  }
}

new TestClass().__hello__COPY__()
```

Here's the output code: 
```js

class TestClass {
  constructor() {
    var _this = this;

    this.hello = _asyncToGenerator(function* () {
      return _asyncToGenerator(function* () {
        console.log(_this, 'hello');
      })();
    });
  }

  __hello__COPY__() {
    return _asyncToGenerator(function* () {
      console.log(_this, 'hello'); // <-- runtime error
    })();
  }

}

new TestClass().__hello__COPY__();
```

`this` reference in the copy is not correctly scoped so that it produces a runtime error. 

### Babel Configuration (.babelrc, package.json, cli command)
Created it as a node program, and it looks like this: 

```js
const fs = require('fs')
const babel = require('babel-core')
const customPlugin = require('./plugin')

const fileName = process.argv[2]

fs.readFile(fileName, (err, data) => {
  if (err) throw err

  const src = data.toString()

  const out = babel.transform(src, {
    plugins: [customPlugin],
    presets: ['stage-0']
  })

  console.log(out.code)
})
```

### Expected Behavior
`this` should be correctly referenced with async functions. 

### Current Behavior
When using `async` in the code and `path.insertAfter(...)` in the plugin, there's a runtime error

### Context
The goal is to have copy of arrow function's body in the class method to be easily replaceable by the React Hot Loader. 

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.21.0
| node             | 6.9.1
| npm              | 3.10.8
| Operating System | MacOS 10.12.2

**Comment by FourwingsY** [comment]
I found very weird and temporary solution, for who are suffered with this issues.
```
hello = async () => {
    const _ = arguments // eslint-disable-line
    console.log(this, 'hello')
}
```
makes `this` works fine. I have no idea how does code works, but it works.

**Comment by wkwiatek** [comment]
@FourwingsY for me it's losing `arguments` too in the above scenario. So after creating new method using AST I have: 

```js
class TestClass {
  constructor() {
    var _arguments = arguments, // <-- arguments appeared here
        _this = this;

    this.hello = _asyncToGenerator(function* () {
      return _asyncToGenerator(function* () {
        const _ = _arguments;
        console.log(_this, 'hello');
      })();
    });
  }

  __hello__COPY__() {
    return _asyncToGenerator(function* () {
      const _ = _arguments;console.log(_this, 'hello'); // <-- however reference is also wrong
    })();
  }

}

new TestClass().__hello__COPY__();
```

**Comment by danez** [comment]
You cannot simple "copy" a node by taking it and reusing it. You need to clone it before you can reuse it, as otherwise if `this` is changed in the first function it is also changed in the second, as they reference the same nodes.
By changing the plugin to do this it works correctly:

```js
const newMethodBody = node.value.body.type === 'BlockStatement' ? t.cloneDeep(node.value.body) : t.blockStatement([t.returnStatement(t.cloneDeep(node.value.body))])
```

**Comment by loganfsmyth** [comment]
Can this be closed? It doesn't seem like something we can fix on our end.

**Comment by hzoo** [comment]
This should be correctly referenced after the PRs earlier? Ran in ast-explorer and then stage-0 in the repl

```
class TestClass {
  constructor() {
    var _this = this;

    this.hello = _asyncToGenerator(function* () {
      console.log(_this, 'hello');
    });
  }

  __hello__COPY__() {
    var _this2 = this;

    return _asyncToGenerator(function* () {
      console.log(_this2, 'hello');
    })();
  }
}

new TestClass().__hello__COPY__();
```
