### ISSUE TITLE
Declarations and ThrowStatement in an IfStatement within DoExpression breaks compilation

### ISSUE THREAD

**Issue by phpnode** [babel/babel#5080]
### Input Code

```js
let x = 100;

let a = do {
  if(x > 10) {
    true;
  } else {
    let a = 123; // does not compile
    throw "nope"; // does not compile
  }
};

```

[Example in the REPL](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&code=%0Alet%20x%20%3D%20100%3B%0A%0Alet%20a%20%3D%20do%20%7B%0A%20%20if(x%20%3E%2010)%20%7B%0A%20%20%20%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20throw%20%22a%22%3B%0A%20%20%7D%0A%7D%3B%0A)

### Babel Configuration (.babelrc, package.json, cli command)
Using `es2015` and `stage-0`

### Expected Behavior
It should wrap the body in an IIFE.

### Current Behavior
It doesn't think that an IIFE is required but when the plugin tries to get the completion record for the relevant if statement it finds undefined and passes that to either the `consequent` or `alternate` of a `ConditionalExpression`, which throws:
```
Property alternate of ConditionalExpression expected node to be of a type ["Expression"] but instead got undefined
```

### Possible Solution
Detect this scenario and wrap in an IIFE, or add a helper that turns `throw e` into `_throw(e)` and hoist + rename declarations.

**Comment by jridgewell** [comment]
Fixed by #5693.
