### ISSUE TITLE
Code size limit bump (#4965) in babel-generator causes issues for very large files

### ISSUE THREAD

**Issue by DrewML** [babel/babel#5081]
- [Original PR](https://github.com/babel/babel/pull/4965)
- [Report of Problem](https://github.com/babel/babel/pull/4965#issuecomment-271424121)

Report (copy/paste from comment by @dmitriiabramov):

> this change resulted in some issues in one of my builds.
I have a relatively large file that i'm instrumenting with `babel-plugin-istanbul`(length 141415)

> with this limit being raised to 500000 my babel process gets stuck on 100% and never exits.

> i was able to track it and the last babel line of code that gets frozen is this https://github.com/babel/babel/blob/master/packages/babel-generator/src/buffer.js#L43

> after that it leaves babel and goes into lodash code (https://github.com/lodash/lodash/blob/master/trimEnd.js#L32)
where the process gets stuck on `string.replace()` call that seems to be not able to process such a big string (string length here is 6449484)

> reverting this change solves the issue. Is there any way to configure it or can it be reverted?

**Comment by dmitriiabramov** [comment]
i think this is only a problem with transformations that add a lot of code. in my case, istanbul adds a LOT of code containing all statements/functions/expressions declarations, so the resulting file ends up being 10x bigger.
I think this become a problem if you try to instrument any file that is more than 3K LOC.

**Comment by DrewML** [comment]
I kind of think we should fix this in two ways:

1. Drop the default down to something smaller than 500kb. (Maybe we should run some tests on the lodash method that is choking).

2. Add a configuration option to make it possible to change this size

**Comment by dmitriiabramov** [comment]
i actually think that 100kb was the best threshold.
`string.replace` was sporadically choking on 140kb.
what was the reason behind bringing the limit up?

**Comment by DrewML** [comment]
I believe there were 2 reasons:

1. Lots of user questions re: deopt message (which could also be addressed w/ better messaging).
2. @loganfsmyth had done a lot of perf work on `babel-generator`, which made keeping formatting a lot less costly.

Just curious, have you tried commenting out that `string.replace` locally to see if that is the only issue? If it is, maybe we can make an optimization there.

It seems like we're only using `trimEnd` [here](https://github.com/babel/babel/blob/2907d66/packages/babel-generator/src/buffer.js#L43) to remove any trailing spaces from the end of the code _after_ converting it from an array to a joined string. We could probably just remove all empty/whitespace strings from end of the array up until a real value is found, and do a cheaper slice. Thoughts?

**Comment by existentialism** [comment]
@DrewML was thinking the same thing

Hopefully it's not a game of wack-a-mole with of finding the _next_ thing that times out. I'll try to run some experiments later today as well.

**Comment by dmitriiabramov** [comment]
i actually tried commenting out `string.replace` and it fixes the issue.
but at the same time, something else can start timing out and those thing are very very hard to debug :)

**Comment by DrewML** [comment]
@tgrochowicz is going to take a whack at improving the perf on this one for his first Babel PR 🎉. If we don't see any perf improvement there, or if timeouts still happen on large files, we can revert to disabling entirely at the previous threshold.

**Comment by dmitriiabramov** [comment]
any updates on this one?

**Comment by xtuc** [comment]
@dmitriiabramov I will also look at this. I wasn't able to reproduce it in Jest (with both PR mentioned here). Could you please provide some steps to reproduce the issue?

@DrewML @existentialism  I think we could, starting from the end `dropWhile` we find empty spaces.

Using a `reduce` we could both remove white spaces and actually join the string.

This will avoid using a replace with a Regex, which is a performance issue.

**Comment by jwbay** [comment]
@xtuc @tgrochowicz apologies for stepping on toes, but I took a crack at this in #5255. This issue is blocking another PR I'm trying to get in elsewhere.

**Comment by DrewML** [comment]
@jwbay don't think you're stepping on any toes. We're all pretty busy so contributions are greatly appreciated 😃
