### ISSUE TITLE
transform-es2015-modules-commonjs breaks UMD script

### ISSUE THREAD

**Issue by kt3k** [babel/babel#5082]
### Input Code

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global.foo = factory());
}(this, (function () {
  'use strict';

  class foo {}

  return foo;
})));
```

Or any umd script.

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["transform-es2015-modules-commonjs"]
}
```

### Expected Behavior

The script does not change because the input code doesn't have export keyword.

### Current Behavior

```js
'use strict';

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() : typeof define === 'function' && define.amd ? define(factory) : global.foo = factory();
})(undefined, function () {
  'use strict';

  class foo {}

  return foo;
});
```

This doesn't work as UMD script.

### Context

I use babel in combination with rollup.

My workflow is first rollup everything and then babel it.
When I setup rollup emits umd and use babel-preset-es2015, then the output script does not work as UMD module.

There is an obvious workaround for my use case (I can drop `transform-es2015-modules-commonjs` from the preset), but the behaviour seems strange to me.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             | v4.4.5
| npm              | 2.15.5
| Operating System | macOS 10.10.5

**Comment by loganfsmyth** [comment]
The CommonJS transform doesn't do any analysis to know that there is already an existing module format in the file. By default `es2015` treats a file as an ES6 module, which leads to the conversion you are seeing.

Your easiest option would be to use

    presets: [
      ['es2015', {modules: false}],
    ]

to disable module transpiling.

**Comment by kt3k** [comment]
The option looks handy! thanks.

> The CommonJS transform doesn't do any analysis to know that there is already an existing module format in the file.

OK. Now I understand the module transpilation better. Thanks for the quick response!
