### ISSUE TITLE
["es2015", { modules: false }] not overriding "es2015"

### ISSUE THREAD

**Issue by halt-hammerzeit** [babel/babel#5084]
I'm having this in one of the projects (though it seems to be working in another project):

`["es2015", { modules: false }]` specified as part of `env` doesn't override the default `"es2015"` preset.
If I remove the default preset then it compiles in ES6 modules correctly.

**Comment by hzoo** [comment]
env merges the two, there are issues with issuing env in this way. (it doesn't actually override) so yes  it doesn't work well atm

**Comment by halt-hammerzeit** [comment]
Ok, I found a workaround:

```
{
	"env":
	{
		"development":
		{
			"presets":
			[
				"es2015",
				"stage-2"
			],

			"plugins":
			[
				"transform-runtime"
			]
		},
		"commonjs":
		{
			"presets":
			[
				"es2015",
				"stage-2"
			],

			"plugins":
			[
				"transform-runtime"
			]
		},
		"es6":
		{
			"presets":
			[
				["es2015", { modules: false }],
				"stage-2"
			],

			"plugins":
			[
				"transform-runtime"
			]
		}
	}
}
```

Since it defaults to `development` then I can sorta make this work **if** `NODE_ENV` is always development.
I guess `development` could be copy-pasted into `production` and it would work in every case.
That would work.
But obviously a less hacky solution is required in the long term.
This issue can be closed if you feel like it's the intended behaviour.

**Comment by hzoo** [comment]
Yeah its "intended" although not ideal, there's also https://github.com/babel/babel/pull/4892 which should help, closing

**Comment by davidlygagnon** [comment]
I ran into this issue recently. Is the workaround the only solution if I don't want to use the latest beta version of babel that supports .babelrc.js file?
