### ISSUE TITLE
object rest property should not evaluate computed property while creating excluded property list

### ISSUE THREAD

**Issue by gsathya** [babel/babel#5087]
### Input Code
```js
var key = 1;
var { [key++]: y, ...x } = { 1: 1, a: 1 };
assertEquals({ a: 1 }, x);
assertEquals(key, 2);
assertEquals(1, y);
```
[Repro in REPL](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-3&experimental=false&loose=false&spec=false&code=var%20assertEquals%20%3D%20(expected%2C%20actual)%20%3D%3E%20%7B%20%0A%20%20if%20(actual%20!%3D%3D%20expected)%20%7B%0A%20%20%20%20console.log(%22found%3A%20%22%2C%20actual%2C%20%22%20expected%3A%20%22%2C%20expected)%3B%0A%20%20%7D%0A%7D%3B%0Avar%20key%20%3D%201%3B%0Avar%20%7B%20%5Bkey%2B%2B%5D%3A%20y%2C%20...x%20%7D%20%3D%20%7B%201%3A%201%2C%20a%3A%201%20%7D%3B%0AassertEquals(%7B%20a%3A%201%20%7D%2C%20x)%3B%0AassertEquals(key%2C%202)%3B%0AassertEquals(1%2C%20y)%3B%0A&playground=true)

### Babel Configuration (.babelrc, package.json, cli command)

Presets - stage3

### Expected Behavior

```
x === { a: 1 }
key === 2
```

### Current Behavior

```
x === { 1: 1, a: 1}
key === 3
```

### Possible Solution

In V8, I currently store the computed property in a temporary variable and reference the temporary variable in the excluded property list.

**Comment by hzoo** [comment]
Thanks for the report! I think this should be covered by https://github.com/babel/babel/pull/3675/files but haven't reviewed all of it yet

**Comment by gsathya** [comment]
> Are you implementing it in v8 now  ?

Yeah, I'm sanity checking my implementation with babel :smile:

**Comment by hzoo** [comment]
Fixed by https://github.com/babel/babel/issues/5757
