### ISSUE TITLE
Use cardinal for syntax highlighting code in babel-code-frame

### ISSUE THREAD

**Issue by mohsen1** [babel/babel#5089]
Currently, syntax highlighting is done inside babel-code-frame. Instead of maintaining your own colorizing use [cardinal](https://www.npmjs.com/package/cardinal) instead.

**Comment by DrewML** [comment]
@mohsen1 Will happily accept a PR if it's keeping feature parity but improving the output.

**Comment by Agathver** [comment]
Hi
We would like to work on this as the part of RGSoC 2017
@meghap9937 @lipsa7
This would be our teams first PR to get familiar with the code.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since we just updated `js-tokens` and we are happy with how syntax highlighting is currently handled.
