### ISSUE TITLE
Babel-cli: allow to install globally, with ability to invoke local babel

### ISSUE THREAD

**Issue by Strate** [babel/babel#5091]
As many nodejs-related tools, it would be good to allow global babel-cli installation, which will invoke local (related to `process.cwd()`) babel installation.

EDIT by @hzoo

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] Check out ava's implementation that @sindresorhus linked: https://github.com/avajs/ava/blob/ad5122d507bfaa044fc3a2e51e467238e16dba11/cli.js#L7-L16, https://github.com/broccolijs/broccoli-cli does something similar
- [ ] modify our `babel-cli`: https://github.com/babel/babel/tree/master/packages/babel-cli
  - https://github.com/babel/babel/blob/master/packages/babel-cli/bin/babel.js, https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/index.js
- [ ] a manual test
- [ ] possibly a unit test (we can help)

**Comment by sindresorhus** [comment]
👍 Feel free to borrow our implementation of this in @avajs: https://github.com/avajs/ava/blob/ad5122d507bfaa044fc3a2e51e467238e16dba11/cli.js#L7-L16

**Comment by varemenos** [comment]
I'd like to work on this

**Comment by varemenos** [comment]
I've got a couple of questions about this feature's implementation.

1) Should we inform the user every time they invoke a local copy of babel?

* will they get confused if we don't?
* will they get annoyed if we do this every single time?

2) Should the babel-cli try to resolve the `./node_modules/babel-core` based on the cwd only or should it try to find the closest package.json based on the cwd and then try to resolve the path `./node_modules/babel-core`?

**Comment by sindresorhus** [comment]
> Should the babel-cli try to resolve the ./node_modules/babel-core based on the cwd only or should it try to find the closest package.json based on the cwd and then try to resolve the path ./node_modules/babel-core?

Should walk up. That's how `require` works and would IMHO be the expected behavior.

**Comment by loganfsmyth** [comment]
Is the proposal here that this call a local `babel-core` or a local `babel-cli`? I don't think I'd want it to have any knowledge of `babel-core` at all, since then we're way more likely to run into versioning mismatches, whereas if it proxies through to a local `babel-cli` things will likely work alright.

> Should we inform the user every time they invoke a local copy of babel?

I'd be in favor of printing a message, we'll just have to make sure that we disable the message when Babel is set up to output transpiled output to stdout or else the message would corrupt the output JS.

**Comment by sindresorhus** [comment]
Call the local `babel-cli`.

**Comment by varemenos** [comment]
Sorry for the delay with this issue, I've had some personal issue the past few days.
Yep I misunderstood the purpose of the issue... Alright so, I'll replace the invocation from babel-core to babel-cli and add log a message when babel's is not set up to output transpiled output to stdout.

Are there any conflicts between this issue and #5258?

**Comment by loganfsmyth** [comment]
I don't think there are any conflicts, I wouldn't worry about it.
