### ISSUE TITLE
shouldn't allow trailing comma after rest parameter in objects

### ISSUE THREAD

**Issue by gsathya** [babel/babel#5092]
### Input Code

```js
var { ...y, } = { a: 1} 
```

### Babel Configuration (.babelrc, package.json, cli command)

Presets - stage3

### Expected Behavior

throws SyntaxError

### Current Behavior

No error

### Possible Solution

Check for trailing comma and record pattern error.

**Comment by xtuc** [comment]
I was not able to reproduce this in the Babel's REPL ([link](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=stage-3&code=var%20%7B%20...y%2C%20%7D%20%3D%20%7B%20a%3A%201%7D)).

Coud you please add more detail to the issue?

**Comment by gsathya** [comment]
> I was not able to reproduce this in the Babel's REPL (link).
> 
> Coud you please add more detail to the issue?

It's reproducible in your link. There should be a SyntaxError, but there is no error.

**Comment by hzoo** [comment]
@gsathya yep I had made this change as a patch and it broke react-native so I reverted. It will be a breaking change so we will do it in Babel 7.

**Comment by danez** [comment]
This is done in babel/babylon#290
