### ISSUE TITLE
object rest doesn't call Get()

### ISSUE THREAD

**Issue by gsathya** [babel/babel#5095]
### Input Code

```js
var x = {
  get a() { throw new Error(); },
};

(() => { var { ...y} = x; })();
```

[REPL](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=var%20x%20%3D%20%7B%0A%20%20get%20a()%20%7B%20throw%20new%20Error()%3B%20%7D%2C%0A%7D%3B%0A%0A(()%20%3D%3E%20%7B%20var%20%7B%20...y%7D%20%3D%20x%3B%20%7D)()%3B&playground=true)
### Babel Configuration (.babelrc, package.json, cli command)

Presets - ES6- stage3

### Expected Behavior

```
→ ./out.gn/x64.debug/d8 -harmony-object-rest-spread 
V8 version 5.7.0 (candidate)
d8> var x = { get a() { throw new Error(); } };
undefined
d8> (() => { var { ...y } = x; })();
(d8):1: Error
var x = { get a() { throw new Error(); } };
                    ^
Error
    at Object.get a [as a] ((d8):1:27)
    at (d8):1:19
    at (d8):1:30
```
 

### Current Behavior

No error

### Possible Solution
_objectWithoutProperties does not do `? Get(from, nextKey)`

**Comment by danez** [comment]
I just checked the transpiled code of the repl in node 6 and was not able to reproduce. The Error was thrown as expected.

Though it seems the repl is somehow misbehaving here and not evaluating the code correctly.

**Comment by danez** [comment]
Oh I found the issue, it seems the repl is catching the Error and printing it. But as in the example the Error has no msg nothing is printed.

**Comment by hzoo** [comment]
https://github.com/babel/babel/blob/672adba9a14aa3b4d4676ef6b8699616d2062a55/packages/babel-helpers/src/helpers.js#L430-L440 - doesn't handle getters

**Comment by danez** [comment]
I think it does.

```js
var x = {
  get a() { return 1; },
};

(() => { var { ...y} = x; console.log(y); })();
```

This code is printing
```json
Object {
  "a": 1
}
```

**Comment by gsathya** [comment]
> And I'm not sure about the specs, but that seems okay, unless the whole getter should be copied over.

The getter should not be copied over. `{ "a" : 1 }` is correct.

**Comment by nicolo-ribaudo** [comment]
This works on master: https://babeljs.io/repl/build/master#?babili=false&browsers=chrome%2060&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAHhC8EG8BQEIHMCmAXCIAUAlIhFgBZgD2A7hAHYY0CiYlYhA3BAL4A0SX7JEixgAnoiQBIPITgA-YqEgIIAOnWiucaJy4EOKXABsMYLHgBEAMRABLIxYKCtAYxBYXpCahAmzlgAUQAGdgx2cgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2%2Cenv&prettier=true&targets=Node-6&version=7.3.4
