### ISSUE TITLE
debugging apps with babel-node

### ISSUE THREAD

**Issue by lifeiscontent** [babel/babel#5098]
how do I debug an app that has been transformed using es2015 presets?

If I run `babel-node --debug index.js --presets es2015,react,stage-2`

it runs, but the console doesn't allow me to access the variables as they were written, it only allows me to access the variables after they've been transpiled.

is this possible to do?

**Comment by danez** [comment]
Afaik using the cli debugger is not possible with sourcemaps, so you always end up debugging the transpiled code.

You could try using [--inspect](https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html#debugger_v8_inspector_integration_for_node_js) instead, as the chrome dev tools support source-maps.

**Comment by DrewML** [comment]
> it runs, but the console doesn't allow me to access the variables as they were written, it only allows me to access the variables after they've been transpiled.

Pretty sure this is always the case, even with sourcemapped code.

**Comment by xtuc** [comment]
Have you tried with [babel-node-debug](https://www.npmjs.com/package/babel-node-debug)? As far as I remember it supports source-maps.

**Comment by hzoo** [comment]
Can try the above suggestions, or use babel-preset-env to only compile a minimal amount in development only so you don't need sourcemaps for most things
