### ISSUE TITLE
doesn't validate patterns correctly in destructuring target  

### ISSUE THREAD

**Issue by gsathya** [babel/babel#5099]
### Input Code

```js
var { ...{x =5 } } = {x : 1}; console.log(x);
```
[REPL](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=var%20%7B%20%20...%7B%20x%20%3D%205%7D%20%7D%20%3D%20%7Bx%20%3A%201%7D%3B&playground=true)

### Babel Configuration (.babelrc, package.json, cli command)

Presets - stage3

### Expected Behavior
``` 
→ ./out.gn/x64.debug/d8 -harmony-object-rest-spread -e "var { ...{x =5 } } = {x : 1}; print(x);" 
1
```

### Current Behavior

Syntax error

### Possible Solution
Doesn't validate patterns correctly in destructuring target

**Comment by DrewML** [comment]
@babel-bot move to babel/babylon
