### ISSUE TITLE
Option to limit line length

### ISSUE THREAD

**Issue by jmullo** [babel/babel#5102]
Babel transforms certain structures into a single line of code, which is then too long for lint rules. An option for maximum line length would be nice.

(Why lint after babel transformation? Because.)

**Comment by hzoo** [comment]
> Because.)

I think it's a good question? It's not one of Babel's goals to *output* every combination of style. I would use babel-eslint or something on your source code by linting before.

**Comment by jmullo** [comment]
Yep, I understand. But I still find it a bit annoying that Babel messes up a perfectly nice section of code that doesn't even need any transforming.

How about making the code generator selectable? If they have even remotely similar APIs...

**Comment by toddself** [comment]
This same issue was also occurred in original jsx transformation tools (archive here sadly without access to issues: https://github.com/facebookarchive/jstransform). 

JSX Transformer was outputting lines in excess of 72 characters, breaking linting.  The end of the discussion was essentially that you shouldn't be linting output -- the output of a code generator is supposed to by syntactically valid for the target engine on which it runs, but not prescribing to a set of arbitrary editing rules.

This also helps enforcing the "don't edit the output" rule.

**Comment by hzoo** [comment]
Ok going to close as this is low priority for us - you have the option of linting on source code, running a different prettifier, forking the generator and adding custom options). Usually you minify generated code as well. (I just closed 3 prs related to quotes, indentation, etc).
