### ISSUE TITLE
SyntaxError after transform-remove-console

### ISSUE THREAD

**Issue by brunolemos** [babel/babel#5106]
### Input Code
https://github.com/jayphelps/core-decorators.js/blob/master/src/time.js#L7

```js
var defaultConsole = {
  time: console.time ? console.time.bind(console) : function (label) {
    labels[label] = new Date();
  },
};
```

### Babel Configuration (.babelrc, package.json, cli command)
```json
{
  "presets": [
    "react-native",
    "react-native-stage-0/decorator-support"
  ],
  "plugins": [
    "transform-es2015-parameters",
    "transform-remove-console"
  ]
}
```

### Expected Behavior
Remove console.* without breaking the code

### Current Behavior
```shell
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1740):
SyntaxError: TransformError: /node_modules/core-decorators/lib/time.js: /node_modules/core-decorators/lib/time.js:
Property consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null
(node:47674) DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Context
Added `transform-remove-console` on a React Native application, but it crashes.

### Your Environment
| software         | version
| ------------- | -------
| Babel              |  6.18
| node               | 7.3.0
| npm                | 4.0.5
| React Native  | 0.39.2
| Operating System | macOS 10.12.3

**Comment by DrewML** [comment]
Moved to https://github.com/babel/babili/issues/374

**Comment by danez** [comment]
Also reported in babel/babili#300
