### ISSUE TITLE
[7.0] Removal of "class-constructor-call" from the repo

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5112]
Remove it from the repo (meaning delete the folder/files)! super fun 😄 

Proposal dropped in [2016-01-28 tc39 meeting](https://github.com/rwaldron/tc39-notes/blob/master/es7/2016-01/2016-01-28.md#progress-review-callable-class-constructors-allen) a while back so we should get rid of it.

I guess that removing the pkgs from the repo technically doesn't even have to be 7.0, only removing it from the stage-x preset (which is already up for removal too).

In detail:
- [ ] [babel-plugin-transform-class-constructor-call](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-class-constructor-call). (remove this folder)
- [ ] [babel-plugin-syntax-class-constructor-call](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-class-constructor-call). (remove this folder)
- [ ] remove this plugin from the [stage-1 preset](https://github.com/babel/babel/tree/master/packages/babel-preset-stage-1) (the package.json + main file)
- [ ] other references to constructor call (main readme? I would just grep the codebase)
- [ ] Reword the website pages to say its been removed in babel 7
  - [ ] https://github.com/babel/babel.github.io/blob/master/docs/plugins/syntax-class-constructor-call.md
  - [ ] https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-class-constructor-call.md
  - [ ] https://github.com/babel/babel.github.io/blob/master/docs/plugins/preset-stage-1.md

---

- [ ] use `npm deprecate` on the 2 transform/syntax pkgs (from @hzoo to do)

**Comment by danez** [comment]
Maybe also deprecate the package on npmjs with a message?

**Comment by hzoo** [comment]
Yeah the only real 7.0 is removing it from stage-1. I think I already did it but I'l add a checkbox for it for me

**Comment by ColinRTaylor** [comment]
@hzoo This seems pretty beginner friendly, can I give it a shot?

**Comment by hzoo** [comment]
Yep I thought it was too just wasn't sure 😄, go ahead

**Comment by ColinRTaylor** [comment]
Thanks!

Submitted a PR: https://github.com/babel/babel/pull/5119

Will submit the website changes in other repo.

**Comment by danez** [comment]
Closed by #5119
