### ISSUE TITLE
[7.0] It will be nice when babel v7 compile es6 to es5 based code that work with customElements v1 

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babel#5116]
Hi there,

There is many discusses about babel v6 and customElements v1, see:
- https://github.com/babel/babel/issues/4480
- https://github.com/w3c/webcomponents/issues/423
- https://github.com/w3c/webcomponents/issues/587
- http://stackoverflow.com/questions/41414034/transpiling-class-based-web-components-with-babel

... and there is some solution out there:
- https://github.com/WebReflection/classtrophobic
- https://github.com/github/babel-plugin-transform-custom-element-classes

So, it will be nice when this issue/problem will be resolved with babel v7

**Comment by DrewML** [comment]
@SerkanSipahi as you mentioned in your OP, there is already an open issue tracking this (#4480). Please refrain from creating duplication issues. There are no immediate plans to address this in the upcoming release.

**Comment by SerkanSipahi** [comment]
@DrewML 
1.) this is not a duplication issue! this is a suggestion for babel v7!
2.) i think this is an important thing/case/matter and many developers also think so.

Why did you close it so quickly? You dont give others the opportunity to debate on this issue/problem.

**Comment by DrewML** [comment]
@SerkanSipahi The Babel issue tracker is only for tracking technical issues. There is already an issue open tracking this defect. A separate issue to make a request for when we'll complete the work is unnecessary.

We're more than happy to accept a pull request, but all of our hands are full already with other commitments.

**Comment by SerkanSipahi** [comment]
@DrewML Well, i saw https://github.com/babel/babel/issues some issues are tagged as [ v7 ]. Therefore i open this issue as suggestion. What do you expect from me? What can i do? How can i help you guys? To make a plugin that solve that problem? There is a nice plugin from @WebReflection out there https://github.com/WebReflection/classtrophobic , maybe classtrophobic can be used as template for generating es6 code to es5 in babel v7?

**Comment by WebReflection** [comment]
> maybe classtrophobic can be used as template for generating es6 code to es5 in babel v7?

FWIW, https://github.com/WebReflection/classtrophobic-es5 targets ES5, while https://github.com/WebReflection/classtrophobic targets at least native `class` capable browsers
