### ISSUE TITLE
[7.0] Remove stage-4 plugins from stage-3 preset

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5117]
Files to modify

- [ ] https://github.com/babel/babel/blob/master/packages/babel-preset-stage-3/src/index.js
- [ ] https://github.com/babel/babel/blob/master/packages/babel-preset-stage-3/package.json

```js
    syntaxTrailingFunctionCommas, // in ES2017 (remove as a breaking change)
    transformAsyncToGenerator, // in ES2017 (remove as a breaking change)
    transformExponentiationOperator,  // in ES2016 (remove as a breaking change)
```

**Comment by hzoo** [comment]
Partially done in https://github.com/babel/babel/pull/3554

**Comment by varemenos** [comment]
I'd like to take a hit at this if no one else is interested

**Comment by hzoo** [comment]
I know @graingert did part of it already so many can coordinate on that (remove the other 2 and then he can fix merge conflicts?)

**Comment by insin** [comment]
In the meantime, can using both `stage-3` and one of the other presets which uses some of the same transforms cause any issues?

**Comment by varemenos** [comment]
Please let me know if you want me to squash the commits and whether there is anything else that needs fixing.

**Comment by hzoo** [comment]
Closed via https://github.com/babel/babel/issues/512
