### ISSUE TITLE
[7.0] Remove `babel-runtime` from babel-x packages (check if we can)

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5118]
### What

Almost every babel-x package right now has a dependency on `babel-runtime`.

Example with babel-plugin-check-es2015-constants: https://github.com/babel/babel/blob/3c2e9c002188104c556d61136cc2a33b44b55b24/packages/babel-plugin-check-es2015-constants/package.json#L12

Being able to remove this from all packages would help save time to install (especially npm 2/yarn).

> https://github.com/facebookincubator/create-react-app/issues/1397
> Yarn has known issues deduplicating dependencies, sometimes failing to hoist dependencies shared between a ton of packages (such as babel-runtime) and producing installs 5 times bigger than npm: yarnpkg/yarn#2306.

The reason for doing this in the first place has to do with wanting to use built-ins like Symbol/Promise, etc which are not native to node 0.10/0.12. Now that we are on >= Node 4 we should be able to use the native ones.

We don't want to use a polyfill, so we choose to use [babel-runtime + babel-plugin-transform-runtime](http://babeljs.io/docs/plugins/transform-runtime/#technical-detailscore-js-aliasing). For more context: http://babeljs.io/docs/plugins/transform-runtime/#why

I think if we don't do this there will be a babel-runtime 7.0 and that won't dedupe correctly etc or we rename to babel-runtime-internal

---

### How to:

- [ ] Use node 4 lts
- [ ] remove `transform-runtime` from the babel config
- [ ] check that tests all pass
- [ ] remove `babel-runtime` from the "dependencies" in each package's package.json and at the top level package.json
- [ ] EDIT: also need to remove it here: https://github.com/babel/babel/blob/7.0/packages/babel-runtime/scripts/build-dist.js

### Wins
- less dependencies, use native, might be faster to run/install

cc @sindresorhus, @insin since I think I recall both of you wanting a solution this even from https://github.com/babel/babel/pull/3438.

**Comment by hzoo** [comment]
And I think @kaicataldo said he might be interested

**Comment by sindresorhus** [comment]
Yes please. Babel is always the biggest dependency in my projects because deduping never works and I end up with a gadzillion copies of `babel-runtime`.

**Comment by hzoo** [comment]
Yep I realized this could probably work since we probably only use node 4 supported ones anyway. Might be hairy but just need to figure it out.

**Comment by loganfsmyth** [comment]
We should make extra sure our tests are running on native Node 4 with no polyfills loaded, otherwise we could run into issues.

**Comment by hzoo** [comment]
This part has to do with `babel-helper-transform-fixture-test-runner/src/index.js`:

```js
function runExec(opts, execCode, execDirname) {
  const sandbox = {
    ...helpers,
    babelHelpers,
    assert: chai.assert,
    transform: babel.transform,
    opts,
    exports: {},
    require(id) {
      return require(id[0] === "." ? path.resolve(execDirname, id) : id);
    }
  };

  const fn = new Function(...Object.keys(sandbox), execCode);
  return fn.apply(null, Object.values(sandbox));
}
```

we run tests with `new Function` and also use `require('babel-polyfill')` so one solution is to use `vm.runInNewContext` instead

**Comment by chicoxyzzy** [comment]
Does someone works on this already?

I think we should mention #5135 in the checklist

**Comment by hzoo** [comment]
^ Can be in 6.x since its internal so not necessary, not sure if anyone working on it, I just asked @kaicataldo if he wanted to look into

**Comment by chicoxyzzy** [comment]
@hzoo there are some other modules in `babel-core` where we extend `Store` from `store.js`. I'll try to realise how to refactor all these.

**Comment by hzoo** [comment]
Yeah was just talking to Logan about that yesterday haha it's everywhere

**Comment by kaicataldo** [comment]
I'm planning to start looking at this today

**Comment by chicoxyzzy** [comment]
classes which extend native Map are blocker for this :(

https://babeljs.io/docs/usage/caveats/#classes

**Comment by hzoo** [comment]
Yeah we need to make a wrapper instead of extending

**Comment by 4rlekin** [comment]
So what's the status here ? I'd be willing to help with that.

**Comment by hzoo** [comment]
If you'd like to start looking into this, can go ahead. Might need to do it myself if its too involved but we'll see how it goes for you?

Immediately you should see an error

> I did find we need to remove the `asf extends Map` { in `store.js`.

Basically for that we need to not extend a native built-in? Or I guess we could just not compile classes for that specific fix.

**Comment by 4rlekin** [comment]
Ok, so i'll look into that and do my best, but i'll proceed with caution and probably consult a lot.

**Comment by kaicataldo** [comment]
@4rlekin Please feel free to take this on if you're willing. I have some personal things that I have to attend to at the moment and won't be able to get to this until next week at the earliest.

**Comment by hzoo** [comment]
Oops done in https://github.com/babel/babel/issues/5218!
