### ISSUE TITLE
[7.0] Drop flowUsesCommas option from babel-generator

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5120]
We don't need to have all these options (and only added it earlier for backwards compat/non-breaking change).

Original PR for reference: https://github.com/babel/babel/pull/3547

> Currently there are 2 supported syntaxes (, and ;) in Flow Object Types. The use of commas is in line with the more popular style and matches how objects are defined in JS, making it a bit more natural to write. Recently FB added a lint rule that enforces the use of commas, so it would great to have this option in Babel as well. Thanks!

---

- [ ] remove the option for `flowUsesCommas` in the readme, code, tests
- [ ] just make the default commas (no more semi if its the enforced style at fb already anyway)

cc @sampepose as fyi

**Comment by ChauTNguyen** [comment]
I'd like to give this a try if possible.

**Comment by existentialism** [comment]
@ChauTNguyen awesome! feel free to join us on slack if you need any help or have questions!

**Comment by hzoo** [comment]
Closed via https://github.com/babel/babel/issues/5123
