### ISSUE TITLE
[7.0] Remove old code used for backwards compatibility in babel-polyfill

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5121]
This was only necessary when we updated core-js' major version but not Babel's

- [ ] remove old code in the comment that says to remove it for the next major version https://github.com/babel/babel/blob/3c2e9c002188104c556d61136cc2a33b44b55b24/packages/babel-polyfill/src/index.js#L11-L29

**Comment by Anderson-Vasques** [comment]
@hzoo This seems the perfect opportunity for my first contribution. Can I help ?

**Comment by hzoo** [comment]
Yep! can just remove that code and that is all that should be needed cc @zloirock

**Comment by Anderson-Vasques** [comment]
Nice. I'll do it.

**Comment by Anderson-Vasques** [comment]
@hzoo @zloirock PR made, I hope I have been useful.

**Comment by vagusX** [comment]
I am just wondering what does those code work for?
