### ISSUE TITLE
[7.0] Remove add-module-exports use internally

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5127]
This was added when upgrading Babel itself to use Babel 6 in #3438. I just wrote it interally since it was temporarily (https://github.com/59naga/babel-plugin-add-module-exports) which we don't recommend doing due to later modules/cjs interop issues.

Relevant for context:

- http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
- https://github.com/babel/babel/issues/2212 (Kill CommonJS default export behaviour)

aka we have to deal with it as well

---

Basically revert https://github.com/babel/babel/pull/3438/commits/d6576490314b0369f68b43aaaf7b49d615108ff8 + fix tests

- [ ] read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] removing the plugin from the .babelrc config in package.json https://github.com/babel/babel/blob/47bb77d35276a54016025bdc1621fb27be1f4baa/package.json#L61
- [ ] removing the plugin code itself in https://github.com/babel/babel/blob/master/scripts/add-module-exports.js
- [ ] run test with `make test-only` or `npm run test`
- [ ] tests will fail in a few places, so you'll need to fix those. Might have to change to use import or the easier way is just to add a `.default` where necessary. So where it's doing some kind of require, you want to do `require('a')` -> `require('a').default` if the test fails.

This also means the "public api" of the packages will change (one of the breaking changes) if not using modules.

**Comment by hzoo** [comment]
Kinda hesitant to add this as beginner-friendly but should be ok.

**Comment by chicoxyzzy** [comment]
I'll take this one

**Comment by hzoo** [comment]
Closed via https://github.com/babel/babel/issues/5131
