### ISSUE TITLE
[7.0] remove `quotes` option from babel-generator

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5139]
(breaking change)

Going to start out by saying `babel-generator` is the package that takes an AST from the babel plugin/presets and returns a string (your file). As a compile file you probably shouldn't be caring that much about the options here. You're going to minify it in prod as well and it's not the source code where you would use eslint, prettier, etc.

Thus out of the options currently in generator - https://github.com/babel/babel/tree/master/packages/babel-generator#options, the `quotes` one doesn't make sense because the others have to do with code coverage, minification, or sourcemaps.

This also would fix #4803 (fixing the issue by removing the option)

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] remove quotes option from babel-generator ([readme](https://github.com/babel/babel/blob/master/packages/babel-generator/README.md), src, tests)
  - [ ] https://github.com/babel/babel/blob/292c3ca2061c6b86a09622d6552621eb57ec3b38/packages/babel-generator/src/index.js#L61
  - [ ] https://github.com/babel/babel/blob/672adba9a14aa3b4d4676ef6b8699616d2062a55/packages/babel-generator/src/printer.js#L25
  - might not have tests in my initial check which is probably why https://github.com/babel/babel/issues/4803

**Comment by 4rlekin** [comment]
"I volunteer as tribute"

Seriously though, im looking for something to engage in open source.
So im willing to take this issue upon myself.

**Comment by existentialism** [comment]
@4rlekin awesome, and may the odds be ever in your favor :)

**Comment by 4rlekin** [comment]
First question then: i assume the branch i should be forking for my solution is the 7.0 (currently one commit behind master) ?

**Comment by hzoo** [comment]
Yeah 👍. sorry just haven't merged anything into 7.0 yet, that's all.

**Comment by ggilberth** [comment]
@4rlekin - Are you still working on this?

**Comment by 4rlekin** [comment]
I am, unfortunately didn't had much time to spend on it yet. I should report some progres in the next 12 hours i guess.

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel/issues/5154!
