### ISSUE TITLE
[7.0] Remove old code from transform-runtime

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5141]
Similar to https://github.com/babel/babel/issues/5121

- [ ] read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] remove deprecated stuff in https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/definitions.js
- [ ] test via `make build-dist` then `make test-only` https://github.com/babel/babel/blob/292c3ca2061c6b86a09622d6552621eb57ec3b38/Makefile#L10-L15
- [ ] ?

cc @zloirock

**Comment by shubheksha** [comment]
I'd like to work on this!

**Comment by hzoo** [comment]
Awesome thanks @shubheksha 😃! It should be straightforward (at least the part I was talking about) but I want to hear from @zloirock since he maintains core-js which is what we use for this.

**Comment by hzoo** [comment]
Yeah I think for this one you need to run

`cd packages/babel-runtime; node scripts/build-dist.js` so I added at the top about that

**Comment by shubheksha** [comment]
@hzoo, I made the changes. However, two tests keep failing even when I simply pull from master and run the tests. Not sure what's going on.

**Comment by chicoxyzzy** [comment]
@shubheksha I guess this is two flow tests failing? That should be OK on Travis CI. I remember same issue on my local machine (even on master branch without any changes)

**Comment by shubheksha** [comment]
@chicoxyzzy, yes, I'm facing exactly the same issue. Thanks for the quick response, I'll go ahead an open a PR. 😄

**Comment by hzoo** [comment]
It's possible we all need to re bootstrap with `make bootstrap` again

**Comment by hzoo** [comment]
Yep it passes for me now (I think we merged something related like yesterday), and the CI always make bootstrap from scratch so it didn't fail

**Comment by chicoxyzzy** [comment]
Yes, `make bootstrap` is exactly what fixed that issue for me

**Comment by hzoo** [comment]
Closed via https://github.com/babel/babel/issues/5142
