### ISSUE TITLE
should allow duplicate __proto__ keys in patterns

### ISSUE THREAD

**Issue by gsathya** [babel/babel#5145]
### Input Code

```js
result = { __proto__: x, __proto__: y } = value;
```

### Babel Configuration (.babelrc, package.json, cli command)

presets - latest

### Expected Behavior
No error

### Current Behavior
Error: `Redefinition of __proto__ property`

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

**Comment by xtuc** [comment]
Looking at the source code this is wanted [babylon/src/parser/expression.js](https://github.com/babel/babylon/blob/b918554d73ed20c847068243edf99d19ca146dbe/src/parser/expression.js#L53)

Could you please tell us what's the reason behind that? Can you reference a specification? I don't have much context there, sorry.

**Comment by gsathya** [comment]
> Could you please tell us what's the reason behind that? Can you reference a specification? I don't have much context there, sorry.

https://tc39.github.io/ecma262/#sec-__proto__-property-names-in-object-initializers

**Comment by existentialism** [comment]
@babel-bot move to babel/babylon
