### ISSUE TITLE
default derived constructor doesn't spread/rest the args in super call

### ISSUE THREAD

**Issue by gsathya** [babel/babel#5147]
### Input Code

```js
Array.prototype[Symbol.iterator] = function() {
  throw new Error();
}
class c {} ;
class b extends c {}
new b();
```

### Babel Configuration (.babelrc, package.json, cli command)

presets -latest

### Expected Behavior
```
→ cat test2.js
Array.prototype[Symbol.iterator] = function() {
  throw new Error();
}
class c {} ;
class b extends c {}
var y = new b();

→ ./out.gn/x64.debug/d8 test2.js
test2.js:2: Error
  throw new Error();
  ^
Error
    at Array.(anonymous function) (test2.js:2:9)
    at b (test2.js:5:1)
    at test2.js:6:9
```

### Current Behavior
No error

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

**Comment by nicolo-ribaudo** [comment]
Closing since https://github.com/tc39/ecma262/pull/2216 got consensus during the last TC39 meeting.
