### ISSUE TITLE
Babel Bot test issue number one million

### ISSUE THREAD

**Issue by DrewML** [babel/babel#5148]
Halp!

**Comment by DrewML** [comment]
@babel-bot move to babel/babylon

**Comment by hzoo** [comment]
@babel-bot move to babel/babylon

**Comment by DrewML** [comment]
Let's try this again:

@babel-bot move to babel/babylon

**Comment by DrewML** [comment]
@babel-bot move to babel/babylon

**Comment by DrewML** [comment]
@babel-bot move to babel/babylon

**Comment by xtuc** [comment]
@babel-bot make me a sandwich

**Comment by DrewML** [comment]
+1
