### ISSUE TITLE
[babel-plugin-syntax-flow] Bug with Webpack 2.2.0-rc.4 and later

### ISSUE THREAD

**Issue by echenley** [babel/babel#5155]
I believe there is some incompatibility between this plugin and webpack 2.2.0 starting at 2.2.0-rc.4. 2.2.0-rc.3 works as expected. With later versions, Webpack is able to bundle the code, but my app doesn't render and I receive the following runtime error.

![screen shot 2017-01-18 at 5 36 03 pm](https://cloud.githubusercontent.com/assets/6344219/22087690/fd8274fa-dda4-11e6-8b86-47ba8cd6c795.png)

It seems to be related to the `export type SomeType = Type` signature in flow. Using `type SomeType = Type` and `export type { SomeType }` seems to work as expected.

### Input Code

```js
// causes error
export type Props = {
  prop1: string,
}

// doesn't cause error
type Props = {
  prop1: string,
}
export type { Props }
```

### Babel Configuration (.babelrc)

```js
{
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-1"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "transform-flow-strip-types"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        "flow-react-proptypes"
      ]
    }
  }
}
```

### Possible Solution

Avoiding use of `export type` eliminates the error. I believe this has something to do with https://github.com/webpack/webpack/pull/3755.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.x
| babel-plugin-transform-flow-strip-types | 6.x
| node             | 6.3.1
| npm              | 3.10.3
| Operating System | Mac OS X 10.12.2

**Comment by hzoo** [comment]
This is odd because since they are types they should all the stripped out via `"transform-flow-strip-types"` and not bundled at all?

**Comment by echenley** [comment]
@hzoo I think I might have figured out where the issue lies. Removing https://github.com/brigand/babel-plugin-flow-react-proptypes/issues also resolves the issue. It must have something to do with the output of that plugin when exporting prop types.

**Comment by hzoo** [comment]
Ok yeah sounds like an issue with that plugin in that case :+1:

**Comment by echenley** [comment]
Thanks! Sorry for the noise.
