### ISSUE TITLE
ClassDeclaration has bindings in two scopes

### ISSUE THREAD

**Issue by boopathi** [babel/babel#5156]
ClassDeclarations have bindings in two scopes 

1. The scope in which it is declared 
2. The class's own scope

While all other bindings belong to only one scope.

### Example:
http://astexplorer.net/#/VstAUrU0JT

Here, you can see class `A` binding appears in the scope where the class is declared and class's own scope. FunctionDeclaration `B` is registered only in the scope where the function is declared.

### Possible Solution
Move class declaration binding to only the scope it is declared in.

Not sure if this will break other things in babel.

### Context
https://github.com/babel/babili/issues/365#issuecomment-273816687

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.20
| node             | 7
| npm              | 4

**Comment by hzoo** [comment]
We could do this in 7 if we go with your suggestion?

**Comment by boopathi** [comment]
Looks like this is not a bug. Explanation in #5209 - thanks @loganfsmyth
