### ISSUE TITLE
Write tests for #5162

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5163]
Fixed the code in that case, but we should add a test to make sure it doesn't regress.

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] write tests for https://github.com/babel/babel/pull/5162

**Comment by 4rlekin** [comment]
I could help with that.

I'd just need to now what babel's testing stack looks like (i only have experience with jasmine)

**Comment by existentialism** [comment]
@4rlekin check out [CONTRIBUTING](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#running-lintingtests) for some notes about running tests.

The (existing babel-node tests)[https://github.com/existentialism/babel/tree/master/packages/babel-cli/test/fixtures/babel-node] should serve as a great starting point, especially the (filename)[https://github.com/babel/babel/tree/master/packages/babel-cli/test/fixtures/babel-node/filename] test.

**Comment by outsideris** [comment]
Is it working on progress? If not, I could handle this.

**Comment by 4rlekin** [comment]
@outsideris oh shoot, i forgot about the matter, you are very welcome to pick things up
