### ISSUE TITLE
No compatible version found: babel-runtime@'>=6.22.0 <7.0.0'

### ISSUE THREAD

**Issue by cvrptn** [babel/babel#5166]
We've recently been running in the following issue. When running the npm install for our project on our CI (Jenkins) we receive the following error:
No compatible version found: babel-runtime@'>=6.22.0 <7.0.0'

However, when running everything locally, this does seem to work.
Seems like this is the same issue as in https://github.com/babel/babel/issues/4975
When running "npm view babel-runtime version" on our CI and locally, we respectively get version 6.20.0 and version 6.22.0
We have tried clearing caches for npm, but this doesn't seem to have any effect.
Any ideas?

**Comment by danez** [comment]
Are you using a private proxy repository for npm? If so maybe it caches too much? The version 6.22.0 was successfully released to npm.
http://registry.npmjs.com/babel-runtime

**Comment by cvrptn** [comment]
Not that I know of. However, the page at npmjs (https://www.npmjs.com/package/babel-runtime) lists 6.20.0 as the latest released version.

**Comment by mehtayash** [comment]
Getting this error too
No compatible version found: babel-code-frame@^6.22.0
npmjs page lists 6.20.0 as latest

**Comment by danez** [comment]
The npmjs.com page is heavily cached and it might take some days to refresh.

**Comment by cvrptn** [comment]
Ok, apparently we are using a local proxy that is serving use a stale version of babel-runtime. I'm sorry for the inconvenience. Refreshing its cache will probably fix my issues.
