### ISSUE TITLE
How to not maximize code?

### ISSUE THREAD

**Issue by trusktr** [babel/babel#5167]
I have some code (f.e. generated by TypeScript compiler), and when I run it through Babel it comes out prettified and less condensed. How can we prevent this from happening?

**Comment by trusktr** [comment]
I suppose I can use babili, but my concern is performance. f.e., will Babel prettify the code, then run it through babili again to minify it, in which case that's an extra step? What's the most performant way?

**Comment by chicoxyzzy** [comment]
I think you can use `compact` option http://babeljs.io/docs/core-packages/#options

**Comment by trusktr** [comment]
@chicoxyzzy Thanks. At first glance of the output, `babili` preset seems the same as `--compact=true`.

I'm compiling with three steps: typescript -> babel -> webpack. Should I even use the `compact` option or Babili at all? Maybe I should just minify in Webpack?

**Comment by trusktr** [comment]
Basically, without compressing anything, the `typescript -> babel` step converts

```
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
```

to

```
        function fulfilled(value) {
            try {
                step(generator.next(value));
            } catch (e) {
                reject(e);
            }
        }
```

I wonder if it could be more performant if it didn't do that. I mean, to just leave the formatting as is and replace inline (but not minify).

**Comment by hzoo** [comment]
@trusktr not to derail from this discussion (can continue) but we'd like if issues were for bug reports/issues rather than questions or support.
