### ISSUE TITLE
babel-core 6.22.1 npm ERR! notarget No compatible version found: babel-traverse@^6.22.1

### ISSUE THREAD

**Issue by hanieel** [babel/babel#5170]
using Babel-core as a dependency broke as of this morning due to "No compatible version found for babel-traverse@^6.22.1":

15:30:02 npm ERR! notarget Valid install targets:
15:30:02 npm ERR! notarget 6.22.0, 6.21.0, 6.20.0, 6.19.0, 6.18.0, 6.16.0, 6.15.0, 6.14.0, 6.13.0, 6.12.0, 6.11.4, 6.10.4, 6.9.0, 6.8.0, 6.7.6, 6.7.5, 6.7.4, 6.7.3, 6.7.2, 6.7.0, 6.6.5, 6.6.4, 6.6.3, 6.6.2, 6.6.0, 6.5.0, 6.5.0-1, 6.4.5, 6.3.26, 6.3.25, 6.3.24, 6.3.21, 6.3.19, 6.3.17, 6.3.16, 6.3.15, 6.3.14, 6.3.13, 6.3.2, 6.2.4, 6.2.0, 6.1.20, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.20, 6.0.19, 6.0.18, 6.0.17, 6.0.16, 6.0.14, 6.0.2

crucial fix needed!!!

**Comment by hzoo** [comment]
This is usually because of cache if you are using a proxy or different registry than the public npm.

The website is not updated immediately.

`npm view babel-runtime version`
https://unpkg.com/babel-core@6.22.1/
https://registry.npmjs.org/babel-core/

https://github.com/babel/babel/issues/5166
https://github.com/babel/babel/issues/5160

We will continue to investigate this moving forward.

**Comment by hanieel** [comment]
Thank you for the quick response, will reach out to our team to speed up cache on our registry.

**Comment by danrigsby** [comment]
`npm view babel-runtime version` is now showing 6.20.0 as the latest version as is https://www.npmjs.com/package/babel-runtime.  Did anything greater get unpublished?

**Comment by hzoo** [comment]
We don't unpublish anything unless the package is actually broken.

^ I mentioned above that the website is not updated immediantely and is usually out of date even a day later.

Again check that you are on the public registry. https://registry.npmjs.org/babel-runtime/

```
{"_id":"babel-runtime","_rev":"262-bc13e97cb92d64a6ef4db5655b3bbd27","name":"babel-runtime","description":"babel selfContained runtime","dist-tags":{"latest":"6.22.0","old":"5.8.38"},"versions":{"4.0.1":{"name":"babel-runtime","description":"babel selfContained runtime","version":"4.0.1","repository":{
```

**Comment by marcoblos** [comment]
:1 Waiting for publish 6.22.0 🙏 

Thanks.

**Comment by jimtom2713** [comment]
I also had this issue with babel-runtime and I believe they are related.
https://github.com/babel/babel/issues/5173

**Comment by loganfsmyth** [comment]
@marcoblos @jimtom2713 Sorry to hear you're both having issues. As mentioned above, it has definitely been published. It may be that you have a local npm package caches at your offices that are causing problems.

**Comment by hanieel** [comment]
This is resolved on my end. Cleared nexus repo cache and rebuild and all working again. !!

**Comment by marcoblos** [comment]
@loganfsmyth @hanieel You are right I use Nexus in my organization. Thanks for explanation, the problem is solved.

Just for share:

- Login in Nexus;
- Server administration and configuration
- Repositories
- Npm Registry
- Click on Rebuild Index

Thanks for quickly answer.

**Comment by priyajeet** [comment]
@marcoblos rebuilding indexes nukes all internal and local npms. Should not be done if people are using their internal repos for internal npms

**Comment by hzoo** [comment]
As an update: it looks like the solution for us is to publish all packages to a different `dist-tag` (which we already do: `lerna-temp`) and then wait like a few minutes or even an hour and then switch to `latest` rather than switching over immediately.

**Comment by priyajeet** [comment]
Yeah whatever you guys can do to help. This has lately been causing a lot of downstream grief.

**Comment by hzoo** [comment]
I think it's always been an issue but I never understood the issue or how to fix it, reached out to npm folks (@bcoe) today.

**Comment by fredbutters** [comment]
I'm getting a similar error that may be related. I've verified that the `npm-cache` directory is empty after cleaning the cache. 
`No compatible version found: babel-preset-es2015@^6.22.0
Valid install targets
6.13.1, 6.13.0, 6.9.0, 6.6.0...`

There is a .cache.json file for this package that references the `dist-tag`. In case this helps:

`{"name":"babel-preset-es2015","dist-tags":{"latest":"6.13.1"},"versions":{"6.0.2":{"name":"babel-preset-es2015","version":"6.0.2"...`

**Comment by bcoe** [comment]
@fredbutters are you using a private npm registry?

`npm config get registry`

**Comment by jimtom2713** [comment]
@fredbutters I was experiencing this issue with all the babel related repos. We are using an internal Nexus repository. The internal registry works for every module we use (so far) except anything having to do with babel. It may have something to do with their tagging system, but we're not really sure. We cleared our cache and rebuilt the internal registry index with no success.
We solved this by forking our own repo of babel, building all the modules under the packages folder and then publishing them to our internal registry. For the time, we are fixing our versions of babel related modules until this tag issue is resolved.

**Comment by fredbutters** [comment]
Wow thanks for the quick responses

@bcoe the result of `get registry` returned `http://127.0.0.1:5080` - do I need to change that?

@jimtom2713 thanks for the suggestion. We don't use Nexus that I'm aware of, but we might be able to do something similar to your solution.

**Comment by existentialism** [comment]
@fredbutters you might have [local-npm](https://github.com/nolanlawson/local-npm) installed?

Try:
```sh
npm set registry https://registry.npmjs.org
npm view package dist-tags
```

**Comment by fredbutters** [comment]
@existentialism 

Yes, I totally forgot we were using local-npm. I updated the registry to point to `https://registry.npmjs.org` but I still get the error. Actually the error is now showing different valid install targets:
`Couldn't find any versions for "babel-preset-es2015" that matches "^6.22.0". Possible versions: "6.0.2, 6.0.8, 6.0.11, 6.0.12`

 `npm view package dist-tags` returned `latest: '1.0.1'`

**Comment by fredbutters** [comment]
I'm pretty sure this is a problem with our TFS build server and not related to babel. Somehow that registry is still getting cached. Thanks for the suggestions though.

**Comment by hzoo** [comment]
Going to close since we understand it has to do with local npm cache/proxies.

For the next release, going to try waiting like an hour before switching the dist tag to `latest` to see if we get less/none of these issues. Probably have to change lerna to support this easily.

**Comment by jakub-bochenski** [comment]
In case somebody finds this useful: there is no "Rebuild Index" option in our Nexus, we tried "Update Index", "Repair Index" and "Expire Cache" -- the new dependency version only appeared after the last operation (expire)

**Comment by loganfsmyth** [comment]
I believe you can also go into the Nexus NPM mirror's list of files and manually delete the cached JSON metadata files for whatever babel-* packages you are having trouble with, to avoid having to expire the whole cache.

**Comment by abobwhite** [comment]
This just happened again with 6.26.... @hzoo Have you changed your procedure for this? Any recommendation on how often we should set our proxy to look for changes?

**Comment by hzoo** [comment]
Not planning to release with v6 anymore so shouldn't happen, and it doesn't seem to be the case with v7. We'll investigate the deps again but it's still hard to know what the issue has been (seemed to be an issue with publishing in the wrong order but I thought we fixed that in a newer version of lerna). It's possible we still have a cyclical dep in v6.

**Comment by abobwhite** [comment]
Thanks for the update. Does v7 use exact dependencies now? We got this to work by adjusting our refresh settings in our cache.

**Comment by hzoo** [comment]
v7 is using exact deps for the alpha because things can break but we'll be using `^` like in v6. We need to discuss how to do versioning, and maybe need to introduce peerDeps or some way for a plugin to know the target babel-core version possibly but really not sure.

**Comment by loganfsmyth** [comment]
Babel 7 doesn't have any cyclic dependencies, so we can ensure that we always publish things in order so there will never be a time when one of our modules in the registry could refer to a version we haven't published yet. In Babel 6 there is one cycle (if I remember right) so while we do our best to publish  carefully, it's technically possible for caches to pull in a version of Babel that depends on one that doesn't exist yet because it's still being published by our scripts.

When using the core registry, it's not really an issue, but if you have a cache that isn't smart enough, it'll happily cache this incorrect state for whatever lifetime you have your cache set to.
