### ISSUE TITLE
[7.0] Setup Yarn

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5172]
We dropped [Node 0.10/0.12](https://github.com/babel/babel/issues/4315) so we can use yarn now.

> can copy these steps into your pr if you want to show progress

- [ ] read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] check you are on 7.0 branch
- [ ] add yarn.lock
- [ ] check travis logs build with yarn

**Comment by ChauTNguyen** [comment]
Hello, can I try this one out?

**Comment by xtuc** [comment]
Yes sure :+1:

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel/issues/5175!
