### ISSUE TITLE
No compatible version found: babel-runtime@^6.22.0

### ISSUE THREAD

**Issue by jimtom2713** [babel/babel#5173]
Attempting to install babel dependencies for my project. The following error is what is presented. 

No compatible version found: babel-runtime@^6.22.0

I've seen this issue presented before with the release of babel-runtime 6.20.0. 
https://github.com/babel/babel/issues/4975

It appears that the versions were upgrading but they were never published to npm.

A general npm install on our project produces the error for babel-runtime@^6.22.0 as a required dependency for babel-plugin-transform-class-properties.

```
npm install babel-plugin-transform-class-properties
```
Produces:
No compatible version found: babel-helper-function-name@^6.22.0
Valid install targets:
npm ERR! notarget 6.18.0, 6.8.0, 6.6.0, 6.5.0, 6.5.0-1, 6.4.0, 6.3.15, 6.3.13, 6.2.4, 6.2.0, 6.1.18, 6.1.17, 6.1.16, 6.1.13, 6.1.12, 6.1.10, 6.1.9, 6.1.8, 6.1.7, 6.1.6, 6.1.5, 6.0.15, 6.0.14, 6.0.2, 6.0.0

### Babel Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
   "presets": ["es2015", "stage-0", "react"],
   "plugins": ["syntax-async-functions","transform-regenerator", "transform-runtime"]
}
```
package.json snippet
```
{
    "babel-cli": "^6.7.5",
    "babel-core": "^6.7.6",
    "babel-eslint": "^6.0.0-beta.6",
    "babel-loader": "^6.2.4",
    "babel-plugin-syntax-async-functions": "^6.5.0",
    "babel-plugin-transform-class-properties": "^6.19.0",
    "babel-plugin-transform-regenerator": "^6.5.0",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-polyfill": "^6.5.0"
}
```

### Possible Solution
npm does not appear to have the latest version of babel-runtime 6.22.0 however it seems to have been published ~17 hours ago.
![screen shot 2017-01-20 at 10 14 47 am](https://cloud.githubusercontent.com/assets/5955421/22160253/712896a0-def9-11e6-8830-96829c5a1864.png)
![screen shot 2017-01-20 at 10 15 39 am](https://cloud.githubusercontent.com/assets/5955421/22160252/7126b268-def9-11e6-9063-0c87a188eb22.png)

**Comment by snowblindroan** [comment]
bump

**Comment by hzoo** [comment]
Should be the same issue as https://github.com/babel/babel/issues/5170 and the others

if you are using non-public npm you'll need to remove cache/update again.
