### ISSUE TITLE
[7.0] Remove old babel-runtime code

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5184]
We can drop some more backwards-compat stuff in some packages.

- [ ] comment below you are going to do this (for others to know)
- [ ] read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] check you are on 7.0 branch
- [ ] remove old code referencing padLeft/padRight https://github.com/babel/babel/blob/d76092b2ddd86ecaa9df2a23610fd86a34ed379b/packages/babel-runtime/scripts/build-dist.js#L26-L36

> The comment says: `// Should be removed in the next major release:` so 👍 

- [ ] run `make test` or `npm test`

**Comment by vkbansal** [comment]
I'll take it

**Comment by vkbansal** [comment]
[ ] comment below you are going to do this (for others to know)
 [ ] read CONTRIBUTING.md
 [ ] check you are on 7.0 branch
 [ ] remove old code referencing padLeft/padRight
 [ ] run make test or npm test
