### ISSUE TITLE
[7.0] Drop Node 5

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5185]
We dropped Node 0.10/0.12 but 5 is also unmaintained so we should drop it from the travis matrix.

> You can simply do this from the github website as well

- [ ] comment below you are going to do this (for others to know)
- [ ] read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] check you are on 7.0 branch
- [ ] remove node 5 from travis.yml https://github.com/babel/babel/blob/7.0/.travis.yml

**Comment by scottarnold** [comment]
I'll take it!

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/5186!
