### ISSUE TITLE
Error when using for await with async iterator

### ISSUE THREAD

**Issue by OliverJAsh** [babel/babel#5190]
Running this in v6.18.0 with `stage-3` preset…

``` js
{
    async function* read() {
        yield await Promise.resolve(1)
        yield await Promise.resolve(2)
    }

    const iterator = read()

    async function main() {
        for await (const x of iterator) {
            console.log(x)
        }
    }

    main().catch(console.error)
}
```

… generates this error…

```
TypeError: iterable[Symbol.iterator] is not a function
```

Possibly related to https://github.com/babel/babel/issues/4639?

**Comment by OliverJAsh** [comment]
Fixed by ensuring I require `babel-polyfill` immediately before *any* transpiled code.

**Comment by hzoo** [comment]
Yeah for any polyfill you will need it to be run before any other code (entry point in webpack, top of the main file) http://babeljs.io/docs/usage/polyfill/#top
