### ISSUE TITLE
Missing Parens. Syntax Error after transforming ArrowFn as Callee

### ISSUE THREAD

**Issue by boopathi** [babel/babel#5192]
When transforming CallExpression with ArrowFn as the callee to TaggedTemplate, a pair of parens doesn't get outputted. 

http://astexplorer.net/#/K2CkvW8FLH

Edit: Also for FunctionExpression

### Input Code

```js
(() => {})("foo")
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  plugins: [
    ({types: t}) => ({
      visitor: {
        CallExpression(path) {
          path.replaceWith(
            t.taggedTemplateExpression(
              path.get("callee").node,
              t.templateLiteral(
                [ t.templateElement({ raw: path.get("arguments")[0].node.value }, true) ], []
              )
            )
          );
        }
      }
    })
  ]
}
```

### Expected Behavior

```js
(() => {})`foo`;
```

### Current Behavior

```js
() => {}`foo`
```

which is a SyntaxError.

### Context

Minify `foo("bar")` to 

```js
foo`bar`
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.21
| node             | 7
| npm              | 4

**Comment by loganfsmyth** [comment]
Definitely a `babel-generator` issue. Reproducible on the REPL with no transforms: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=&code=%22use%20strict%22%3B%0A%0A(()%20%3D%3E%20%7B%7D)%60%60&experimental=false&loose=false&spec=false&playground=false
