### ISSUE TITLE
[7.0] Tests: switch to jest

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5197]
I think we are using like 3 different testing frameworks and would like to move to use the same one for all projects? I believe the team agreed with choosing jest a good base (and is possible since we have dropped node 0.10/0.12 in 7.0).

Not sure how difficult this is but shouldn't be too bad and we can help.

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] modify dependencies https://github.com/babel/babel/blob/7.0/package.json#L41
- [ ] modify options https://github.com/babel/babel/tree/7.0/test
- [ ] each package in babel/packages/* has a test directory
  - [ ] might be a bit tricky but you can test with `make test-only` or `TEST_GREP=transformation make test` for a subset
  - [ ] https://github.com/babel/babel/tree/7.0/packages/babel-cli/test figure out if anything needs to be converted.

**Comment by geordidearns** [comment]
Hey @hzoo I'm keen to pick this one up please. I'll take a look and reach out with any questions ✌️

**Comment by wtgtybhertgeghgtwtg** [comment]
To clarify, does this apply to other Babel projects like `babylon`, as well?

**Comment by xtuc** [comment]
> would like to move to use the same one for all projects

Yes.

**Comment by danez** [comment]
> To clarify, does this apply to other Babel projects like babylon, as well?

I would not touch babylon right now, as it works perfectly fine with ava.

**Comment by montogeek** [comment]
Can I work on this?

**Comment by xtuc** [comment]
@montogeek yeah, it seems nobody is on its integration in Babel.

**Comment by sergiorojasa** [comment]
Can I also work on this?

**Comment by loganfsmyth** [comment]
Done!

**Comment by montogeek** [comment]
Cool!
