### ISSUE TITLE
[7.0] Default babel-register cache location to node_modules

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5198]
why: easier to find since it's in node_modules, easy to clear all cache for all the tools that use it.

Move register cache file location to `./node_modules/.cache/babel-register` via 

https://github.com/avajs/find-cache-dir

Ref previous babel-loader PR: https://github.com/babel/babel-loader/pull/301/files as well as the current file (https://github.com/babel/babel-loader/blob/e9e37029e0c5905d8846f69d9a0c348f3d49fe50/src/fs-cache.js#L170), https://github.com/babel/babel-loader/pull/318/files

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) (make sure you have yarn, and are on at least node 4)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing 
- [ ] Default to `findCacheDir({ name: "babel-register" })` and fallback to os/home/tmp dir.
- [ ] if there are already tests setup for that package, write another test (otherwise we'll do it or help)

**Comment by shubheksha** [comment]
I'll take this one!

**Comment by shubheksha** [comment]
What about the `BABEL_CACHE_PATH` variable? Currently the default with the fall back being implemented as a JSON file. Will that logic be removed completely? 
https://github.com/babel/babel/blob/master/packages/babel-register/src/cache.js#L6

**Comment by shubheksha** [comment]
Also, I guess I'll have to write a couple of tests for this package? I couldn't find any in it's folder. I'd appreciate any guidelines to get started.

**Comment by xtuc** [comment]
I think the cache location should still be overridable (`BABEL_CACHE_PATH`).

I tried to add some tests ([there](https://github.com/babel/babel/pull/5260/files#diff-0487592203c69bc80889d59b04ddbba4)).

**Comment by shubheksha** [comment]
@xtuc & @hzoo, does this look right?
`var FILENAME = process.env.BABEL_CACHE_PATH || findCacheDir({ name: 'babel-register' }) || os.tmpdir();`

I'll wait for #5260 to land before writing tests for this patch.

**Comment by hzoo** [comment]
Yeah 👍 (dono if we really want to support `BABEL_CACHE_PATH` anymore but just so it's one less thing to break we could keept it).

**Comment by xtuc** [comment]
@shubheksha The PR has been merged. Don't hesitate to tell me if anything is wrong with the tests.

**Comment by aaronang** [comment]
What is the current status of this issue?

**Comment by pwmckenna** [comment]
@shubheksha don't mean to step on your toes if you're still working on this. feel free to just close this pr, but its been a while and seemed simple enough that I thought I'd just make the PR. Not sure how this fits in with the long term cache plans, but would be a nice intermediate change.

**Comment by xtuc** [comment]
The config caching has a bit changed. @loganfsmyth worked on it.

See https://github.com/babel/babel/pull/5608 for ex.
