### ISSUE TITLE
Wrong TypeError: missing new keyword, although it is present 

### ISSUE THREAD

**Issue by marvinhagemeister** [babel/babel#5208]
Sample repository where the bug is easily reproduceable: https://github.com/marvinhagemeister/babel-bug/

Steps to reproduce:
1. Clone above repo
2. `npm install`
3. `npm run build && node dist/index.js`
### Input Code
```js
import { observable } from "mobx";
import { SimpleForm } from "mobx-form-reactions";

class TestForm extends SimpleForm {

}

class Model {
  @observable foo = "";
}

// Works
const foo = new SimpleForm(new Model());

// Doesn't work
const bar = new TestForm(new Model());
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015",
    "stage-1"
  ],
  "plugins": ["transform-decorators-legacy"]
}
```

### Expected Behavior

Extending a class with the `extends` keyword should work

### Current Behavior

I get a `TypeError` although the `new` keyword is present:

```
/Users/myuser/babel-class-bug/dist/index.js:64
    return _possibleConstructorReturn(this, (TestForm.__proto__ || Object.getPrototypeOf(TestForm)).apply(this, arguments));
                                                                                                    ^

TypeError: Class constructor SimpleForm cannot be invoked without 'new'
    at new TestForm (/Users/myuser/babel-class-bug/dist/index.js:64:101)
    at Object.<anonymous> (/Users/myuser/babel-class-bug/dist/index.js:86:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.2
| node             | 7.4.0
| npm              | 4.0.5
| Operating System | MacOS Sierra

**Comment by marvinhagemeister** [comment]
Found a simpler preset to reproduce the problem:

```json
{
  "presets": [
  ],
  "plugins": [
    "transform-decorators-legacy",
    "babel-plugin-transform-export-extensions",
    "babel-plugin-transform-class-properties",
    "transform-es2015-modules-commonjs",
    "babel-plugin-transform-es2015-classes"
  ]
}
```

**Comment by marvinhagemeister** [comment]
Managed to reduce the test case even further, see the latest commits to https://github.com/marvinhagemeister/babel-bug/

**Comment by danez** [comment]
Well most probably it happens because as long as the class is inside node_modules it won't be transpiled and used as native class. 
And the problem seems to be that babel-transpiled classes are calling the parent constructer in a way that works for other transpiled classes but not native classes.

Might be related to #4480

**Comment by marvinhagemeister** [comment]
@danez Might be. I'm afraid I'm not familiar enough with babel code.

Nonetheless I found a workaround for now. When the imported module is babelified to ES5 instead of a native ES6 class, everything works as expected.

**Comment by loganfsmyth** [comment]
Yup, there are two ways to fix this:

1. Compile the module in `node_modules` too, which isn't idea and could break that module.
2. Use `babel-preset-env` for your Node environment, so it'll skip compiling the class syntax since your local Node version obviously supports it.
