### ISSUE TITLE
regexify used in babel-core for globs matching does not check for the end of text

### ISSUE THREAD

**Issue by enterit** [babel/babel#5210]
Babel API documentation says that `only` option supports glob syntax - the same that `minimatch` provides.
But, Babel treats '*.js' glob as if it matches JSON files. Internally, it is an issue for all globs - Babel's `regexify` returns RegExp that does not check for the end of text in the matching text.

For instance, for '*.js' Babel generates RegExp `/(?:(?!\.)(?=.)[^\/]*?\.js)/i`.
Compare with the RegExp generated by minimatch: `/^(?:(?!\.)(?=.)[^\/]*?\.js)$/`
### Input Code
```js
require('babel-core/lib/util').regexify('*.js').test('file.json') // returns true
require('minimatch').makeRe('*.js').test('file.json') //returns false
```

### Expected Behavior
Babel should not ignore end of text in globs, '*.js' glob should not match JSON files in Babel's interpretation.

### Current Behavior
Babel ignores end of text in globs and treats '\*.json' files as if they match '\*.js' glob.

### Possible Solution
I think it is best to use `minimatch` directly from babel-core, instead of keeping a copy of `regexify` algorithm.

### Context
I am trying to make Babel ignoring JSON files in my project, where I use a mix of JS and JSON files.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.1
| node             | 6.9.2
| npm              | 3.10.9
| Operating System | Windows 10

**Comment by loganfsmyth** [comment]
`regexify` is dead in 7.x and this appears to work with the new matching logic.
