### ISSUE TITLE
[7.0] Move `legacy-decorators` into stage-1 preset 🎉

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5220]
Right now the transform-decorators plugin in [babel-preset-stage-2](https://github.com/babel/babel/blob/master/packages/babel-preset-stage-2) just errors because it hasn't been implemented. (It's in progress).

In the meantime we should just remove it from stage 2 and then move the [decorators legacy plugin](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) by @loganfsmyth into stage-1. I want to say stage-1 since it hasn't been updated. When we implement the stage-2 spec one we can move it into stage-2.

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing 

---

- [ ] remove references to the old [transform decorators plugin](https://github.com/babel/babel/blob/446b4a7dbd7e79fad8fcdfe374bbc04228dafee6/packages/babel-preset-stage-2/src/index.js#L4-L14) and [package.json](https://github.com/babel/babel/blob/446b4a7dbd7e79fad8fcdfe374bbc04228dafee6/packages/babel-preset-stage-2/package.json#L12)
- [ ] add decorators legacy instead to stage-1 preset in the same places (src/index.js and package.json) https://github.com/babel/babel/tree/master/packages/babel-preset-stage-1

**Comment by yavorsky** [comment]
I'll take this one 👌

**Comment by existentialism** [comment]
https://github.com/babel/babel/pull/5225 👍

**Comment by jharris4** [comment]
Should this maybe be documented on the README for https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-decorators?

I just tried using the non-legacy plugin and got the error, and only knew why by searching and finding this issue.

**Comment by xtuc** [comment]
@jharris4 Yes, I will update the documentation.

@existentialism @hzoo This is a breaking change, right?
