### ISSUE TITLE
[7.0] Use lerna's --independent mode + changes

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5221]
Ref https://github.com/babel/babel/issues/4950 (still need to figure out babel-core versioning/peer deps idea in another issue)

We'd like to do independent versioning for all experimental proposal packages, instead of the fixed versioning mode we use now. (Context: https://github.com/lerna/lerna#how-it-works)

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing
--- 
- [ ] edit [`lerna.json`](https://github.com/babel/babel/blob/master/lerna.json) and change to ` "version": "independent",`
- [ ] also add `"cacheDir": ".changelog"` (similar to https://github.com/facebookincubator/create-react-app/blob/master/lerna.json)
- [ ] `make bootstrap` and `make test-only` again to retest (CI will check as well)

**Comment by Anderson-Vasques** [comment]
I'll take this one.

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/5224
