### ISSUE TITLE
Add `path.getPrevSibling`, `path.getNextSibling`, etc.

### ISSUE THREAD

**Issue by kangax** [babel/babel#5223]
We have quite a few cases of `path.parentPath.getSibling(path.parentPath.key + 1)` in [Babili's DCE](https://github.com/babel/babili/blob/master/packages/babel-plugin-minify-dead-code-elimination/src/index.js).

It would be nice if Babel provided basic traversal methods like `getPrevSibling()`, `getNextSibling()`, `forEachPrevSibling()`, `forEachNextSibling()`, etc.

Naming subject to change, of course.

---

EDIT by @hzoo

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] This can be done on `master`
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing
- [ ] Check out the handbook if you need more context into what a ["sibling"](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#get-sibling-paths) is. Basically it's like the same idea with a DOM sibling (`$("a").siblings`) but instead its an AST node sibling.
---

- [ ] modify `babel-traverse/src/path/family.js` and add the methods  shown above ^ https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/family.js#L60-L67
- [ ] add tests in https://github.com/babel/babel/blob/master/packages/babel-traverse/test/family.js

**Comment by hzoo** [comment]
I like it! Names seem fine to me but maybe someone else has a better idea. We should just have the same api as jQuery haha.

**Comment by kangax** [comment]
Seems like a nice beginner-friendly task so I'm marking it as such.

**Comment by hzoo** [comment]
Yep! I'l update the issue for that stuff

**Comment by chitchu** [comment]
Hi @kangax, @hzoo 

If you don't mind I'll pick this one up.

I do have a suggestion. Instead of `getNextSibling(), getPrevSibling()`, would method chaining be better syntax wise? ie `getSibling().next(), getSibling().prev(), getSibling().prev().prev().next()`

**Comment by kangax** [comment]
@chitchu chaining would work automatically since the method will be defined on a path and will return another path (or `null`/`undefined`).

**Comment by chitchu** [comment]
@kangax I misunderstood what `getSibling` does. That makes it clear then.
