### ISSUE TITLE
--watch and --copy-files only copies files initially

### ISSUE THREAD

**Issue by possibilities** [babel/babel#5232]
My hope was that non-js files would be copied on change to avoid needing a separate tool for keeping them in sync when I'm `--watch`ing. Would this be considered a desirable improvement if I worked on it? Thanks!

**Comment by aaronang** [comment]
@possibilities I looked into this and found that it actually does write the changes. I did the following to investigate this.

1. Create a test project with the following npm script:
    ```json
    "scripts": {
        "watch": "babel src --copy-files --watch --out-dir lib"
    },
    ```
2. Run:
    ```bash
    $ npm run watch
    ```

3. Add `index.html`.

These steps actually copy the `index.html` to the `lib/`, even when `index.html` is changed. There is a catch though, in the CLI you won't see any notification that the file is actually being copied. I will propose a patch for this 😄

**Comment by xtuc** [comment]
Closing, out of scope for now.
