### ISSUE TITLE
shorthand reserved words

### ISSUE THREAD

**Issue by bounceme** [babel/babel#5234]
https://github.com/pangloss/vim-javascript/issues/644#issuecomment-275828980

**Comment by xtuc** [comment]
While you can use a reserved keyword in an ES6 property shorthand, you can't declare it:
```js
const while = true;
const i = { while };
```

```sh
repl: Unexpected token (1:6)
> 1 | const while = true;
    |       ^ 
```

See [REPL](http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=&experimental=false&loose=false&spec=false&code=const%20while%20%3D%20true%3B%0Aconst%20i%20%3D%20{%20while%20}&playground=true).

**Comment by bounceme** [comment]
Could you explain what is happening here please ?

https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Clatest%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&code=window.while%20%3D%201%0Ai%20%3D%20%7Bwhile%7D%0A

**Comment by hzoo** [comment]
What part? If you mean `{ while }` then it's es6 shorthand syntax http://babeljs.io/docs/plugins/transform-es2015-shorthand-properties/ and thus you end up making while an identifier which isn't allowed since it's a keyword

**Comment by bounceme** [comment]
Ohh , so I was initially right about this. the variable being used as a shorthand must be a valid identifier. Correct?

**Comment by hzoo** [comment]
Exactly because it actually means the property valid is that key.
