### ISSUE TITLE
[bug?] Unable to destructure object with rest operator inside parens expression list

### ISSUE THREAD

**Issue by trusktr** [babel/babel#5239]
### Input Code

```js
let o = {x:1, y:2, z:4}

function f (other) {
  console.log(o === other) // expecting false
}

let c
f( ({...c}=o, c) )
```

The intent is to pass a copied object, not the original. f.e., this would work too:

```js
f(Object.assign({},o))
```

Did I do the destructuring version wrong? If so, how would I destructure `o` to send a copy into `f()`?

Or is this a bug? 

### Babel Configuration (.babelrc, package.json, cli command)

Using the repl, Babel 6.22.1 at time of writing.

### Expected Behavior

I thought I could make a copy of `o` into `c`, then pass it into `f()`.

### Current Behavior

```
Uncaught TypeError: repl: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement"] but instead got undefined
```

### Possible Solution

Don't know

### Context

I thought I could copy an object with destructuring before passing it into a function (I was trying to do it in one line). f.e. I know I can do

```js
let {...c} = o
f(c)
```

but I was curious to see if I could do the destructuring in the same expression as `f()`.

### Your Environment

n/a

**Comment by trusktr** [comment]
I also tried

```js
f( ( ({...c}=o), c) )
```

and

```js
f( ( ({...c})=o, c) )
```

but no luck.

**Comment by existentialism** [comment]
Do you need `c`?

```
let o = { x:1, y:2, z:4 };

function f (other) {
  console.log(o === other) // expecting false
}

// if not...
f({...o});

// if so...
const c = {...o};
f(c);
```

**Comment by existentialism** [comment]
ping @trusktr

**Comment by existentialism** [comment]
@trusktr going to close this for now, but let us know if you run into any more issues!

**Comment by trusktr** [comment]
Thanks for that solution, I didn't know about argument destructuring at the time.
