### ISSUE TITLE
Babel uses strict mode even when modules: false

### ISSUE THREAD

**Issue by fatcerberus** [babel/babel#5240]
I have the following Babel transform:
https://github.com/fatcerberus/minisphere/blob/master/assets/system/cell_modules/transpile.js#L20-L29

When `modules: false` which I use for migrating old scripts, Babel doesn't prepend a strict mode directive and the transpiled code then runs in loose mode, which is correct.  However the transpiler still operates as though the code is strict, producing errors if it encounters, e.g. an octal literal or a `with` statement.  This breaks a lot of legacy code.  Is this a bug, or am I doing something wrong?

**Comment by loganfsmyth** [comment]
I believe you'll also want to set `sourceType: 'script'`

**Comment by fatcerberus** [comment]
Ah, thanks, I didn't see any reference to that option in the documentation for the es2015 plugin.  I'll try that and see if it works.

**Comment by fatcerberus** [comment]
`sourceType: 'script'` worked, thanks again.  I had to use it as an option for `transform()` rather than the ES2015 plugin specifically.  `sourceType` doesn't seem to be in the documented list of options supported by `transform()`:
https://babeljs.io/docs/usage/api/#options

So I never would have known about it if you didn't tell me.

**Comment by xtuc** [comment]
Good catch, I created an issue to update the documentation.

Do you mind If I close this issue? Feel free to reopen it if needed.
