### ISSUE TITLE
Export babel-cli as a Node API

### ISSUE THREAD

**Issue by arslivinski** [babel/babel#5245]
Would be nice to have the babel-cli API exposed through an Node API, like [eslint does](http://eslint.org/docs/developer-guide/nodejs-api#cliengine).
Some people, like me, writes his own build scripts to not depend on external tools like Grunt, Gulp or similar.
However, the Babel API is too simple and every time I need to write the build scripts for a new project I feel like I'm reinventing the wheel, since babel-cli has everything done.
Using babel-cli has some limitations too, since I can't use .babelrc from a custom location or use a dynamic .babelrc.js file.
I think that would be a nice add to the project.

**Comment by xtuc** [comment]
Closing, out of scope for now.
