### ISSUE TITLE
Object destructuring assigned as an object's property does not work as expected

### ISSUE THREAD

**Issue by olivierbeaulieu** [babel/babel#5257]
### Input Code
```
var foo = {bar:1, baz:2}
var a = {
  b: {bar,baz}=foo
}
console.log(a);
```

### Babel Configuration (.babelrc, package.json, cli command)
Presets 2015, using the babeljs.io website's REPL

### Expected Behavior
If you put the input code in Chrome's console, `console.log(a);` rightly prints the following:
```
{
  b: {
    bar: 1,
    baz: 2
  }
}
```

### Current Behavior
If you put the same input code through babel, you will get an error `bar is not defined`:
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&experimental=false&loose=false&spec=false&code=var%20foo%20%3D%20%7Bbar%3A1%2C%20baz%3A2%7D%0Avar%20a%20%3D%20%7B%0A%20%20b%3A%20%7Bbar%2Cbaz%7D%3Dfoo%0A%7D%0Aconsole.log(a)%3B

### Possible Solution
Looking at the transpiled code, it seems babel expects object destructuring to always be used to create a new variable (ex: `let  {bar,baz} =  foo`), although it seems that assigning this value to an object property directly is valid ES6

### Context
We're trying to stop using `_.pick`, and this pattern of object destructuring is a nice clean way to do it. If only it worked everywhere!

### Your Environment
Running on the babel website REPL (doesn't work) vs. running in Chrome 56's console (works)

| software         | version
| ---------------- | -------
| Babel            |  6.22.1

**Comment by loganfsmyth** [comment]
This is an issue with the code, rather than Babel. You'll see the same in Chrome if you mark the code strict

```
(function(){'use strict';
  var foo = {bar:1, baz:2}
  var a = {
    b: {bar,baz}=foo
  }
  console.log(a);
})()
```

Your issue is that in
```
var a = {
  b: {bar,baz}=foo
};
```
the `{bar,baz}=foo` is just an assignment, not a default value. Default values apply to destructuring, not object declaration. So you are essentially doing

```
({bar,baz}=foo);
var a = {
  b: foo
};
```
and the destructuring assignment of `bar` and `baz` attempts to assign to those variables, but they do not exist.

**Comment by olivierbeaulieu** [comment]
Ah, I should have noticed the REPL was adding a strict statement. Good answer, thank you for your time! I believe we can close this issue now.
