### ISSUE TITLE
Babel transpiles hoisted function to function expression

### ISSUE THREAD

**Issue by fatcerberus** [babel/babel#5262]
At least in some cases Babel seems to transpile fully hoisted function definitions into function expressions assigned to a hoisted `var`.  This changes the meaning of the code and sometimes causes difficult-to-diagnose bugs.

### Input Code

(Full disclosure: Yes, I know this code is questionable to begin with as it conditionally defines a hoisted function.  It's not my code, though, so I have no control over this; in any case transforming a hoisted function to a function expression is incorrect even without the `if`.)

```js
// INPUT CODE:
if (GetVersion() < 1.6) {
	function DoesPersonExist(name) {
		return Link(GetPersonList()).contains(name); 
	}
}
```

```js
// gets transpiled to:
if (GetVersion() < 1.6) {var
	DoesPersonExist = function DoesPersonExist(name) {
		return Link(GetPersonList()).contains(name);
	};
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    sourceType: 'script',
    comments: false,
    retainLines: true,
    presets: [
        [ 'latest', { es2015: { modules: false } } ]
    ]
}
```

### Expected Behavior
The function should remain as a fully hoisted function definition in the transpiled output.

### Current Behavior
Instead, Babel transpiles it to a `var` + assignment, which changes the behavior.

### Context
I'm developing a game engine, [miniSphere](https://github.com/fatcerberus/minisphere), which is backward compatible with the original Sphere game engine by Chad Austin while adding a bunch of new features (like ES2015 transpilation).  There exists a lot of legacy code that does rather... questionable things (see code snippet above) which happens to work anyway but in this case Babel did a transformation which broke it.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.1 (babel-standalone)
| node             | n/a
| npm              | n/a
| Operating System | Windows 10 Pro AU

**Comment by loganfsmyth** [comment]
> This changes the meaning of the code and sometimes causes difficult-to-diagnose bugs.

Would you be able to clarify what specific case is breaking? I have a guess, but it is hard to verify with your snippet. Is the code specifically relying on the function declaration being available outside the `if` statement?

**Comment by fatcerberus** [comment]
The code in question is a polyfill for older Sphere versions.  As noted it's not strictly correct because of hoisting, but ends up working anyway because the function definition is hoisted in its entirety.  Babel transforms it to a var statement, which means the function is now conditional (as originally intended) but the identifier binding is *not* due to hoisting, introducing a bug in the transpiled code.

**Comment by loganfsmyth** [comment]
Sorry, I'm having a hard time following what you're describing, could you make a standalone example that makes it clear what you are seeing vs what you expect?

**Comment by fatcerberus** [comment]
`DoesPersonExist()` is a native function provided by the Sphere platform.  The snippet is supposed to provide it for old versions that don't include it, but (due to hoisting) accidentally provides it for all versions.  Babel's transformation results in it the native function being shadowed by a hoisted `var`.

**Comment by loganfsmyth** [comment]
The existence of the `var` shouldn't hurt anything as long as the assignment inside the `if` doesn't run, as far as I'm aware.

I think at this point, I can still give you an answer. Pre-ES6, function declarations were not allowed in `if` statements officially. Some JS environments allowed them anyway, with each environment implementing slightly different behavior for the edge cases.

When ES6 became official, it added block-scoping with `let` and `const` and officially added support for function declarations inside blocks, with them being block-scoped. That means that in official ES6 code, 

```
if (true){
    function aThing(){}
}
```
behaves kind of like 
```
if (true){
    let aThing = function(){}
}
```
with hoisting (inside the if block, not the parent function), meaning that `aThing` is not accessible outside the `if`.

For backward-compatibility with browsers that implemented `function` support inside `if` statements, the ES6 spec includes a optional [Annex B.3.3](http://www.ecma-international.org/ecma-262/7.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics) that essentially adds extra logic around hoisting.

It sounds like in this case, Sphere is relying on this optional Annex B functionality, and unfortunately Babel does not implement this behavior, which is causing the issue you are seeing.

We don't generally recommend running third-party code through Babel's transformations, so recommendation would be to not run this third-party code through Babel.

**Comment by fatcerberus** [comment]
The problem specifically with the transformed code is that the `var` gets hoisted but the function does not, leading to it being `undefined` in environments that don't need the polyfill.

**Comment by loganfsmyth** [comment]
As I said, that is my guess based on what you've given me. I'm going to need a reproducible snippet of code that I can run to understand the issue, if we're going to make more progress. I understand what you are saying, but I disagree with your conclusion, so we need an example.

For example, in Node running

```
if (false){
	function fn(){ console.log('IF'); }
}
fn();
```

errors with `TypeError: fn is not a function` even though there is no `var fn`. 

Please put together a reproducible example.

**Comment by fatcerberus** [comment]
I understand.  I'll try to come up with a repro case later (I'm not near a computer at the moment), but does it matter that the function is defined in global code?  Node runs everything as a module, so under the hood even "global" code is actually part of a function body there.

**Comment by fatcerberus** [comment]
Okay, so I did some more digging.  Given the following (note: indirect eval is used to emulate global code because otherwise Node runs everything in function context):

```js
global.fn = function fn() { console.log("outside if"); };
(0, eval)(`
if (false) {
	function fn() { console.log("inside if"); }
}
`);
fn();
```

Node outputs:
```
outside if
```

In other words, the function is not hoisted out of the `if` block.  When the code inside the eval is passed to Babel, using the .babelrc provided above, it gets transformed to:
```js
if (false) {var
        fn = function fn() {console.log("inside if");};
}
```

However, Node output doesn't change in that case:
```
outside if
```

If one moves the `if` block out of the eval, however, that results in a TypeError for both cases in Node.  For Duktape, the JS runtime I'm using in minisphere, the code works as intended in the first case, but fails with a TypeError for the Babel-transpiled version (best I can tell, the `var` gets hoisted and overwrites the global function).  So this might actually be a bug in Duktape.

**Comment by loganfsmyth** [comment]
I think the right answer here is to not run that file through Babel. Playing around with Duktape, take a look at [this example link](http://duktape.org/dukweb.html#%0Avar%20global%20%3D%20new%20Function('return%20this')()%0A%0Aglobal.fn%20%3D%20function()%7B%20print('global')%3B%20%7D%3B%0A%0Aif%20(false)%20%7B%0A%20%20%20%20function%20fn()%7B%20print('if')%3B%20%7D%0A%7D%0A%0Afn()%3B), this snippet
```
var global = new Function('return this')()
global.fn = function(){ print('global'); };

if (false) {
    function fn(){ print('if fn'); }
}
fn();
```

prints `if fn`. It looks like Duktape hoists the `fn` into the parent scope even when the `if` is not evaluated. So my theory would be that your example

```
if (GetVersion() < 1.6) {
	function DoesPersonExist(name) {
		return Link(GetPersonList()).contains(name); 
	}
}
```

is always using that version of `DoesPersonExist`, even when `>= 1.6`. Then when the code is run through Babel, that becomes a `var`, and the code is only run when `< 1.6`.

That means that in both cases, while there may be a global `DoesPersonExist`, but it is always shadowed by the local version. The issue is that by processing it with Babel, it is always shadowed but then only initialized when `< 1.6`.

This difference is absolutely linked to the optional Annex B.3.3 behavior I mentioned above. Duktape isn't wrong in what it is doing, but Babel does not implement the behavior that this `DoesPersonExist` function relies on.

Not running that file through Babel should avoid the issue.

**Comment by fatcerberus** [comment]
What's curious to me is that the global function is *not* shadowed in Node, even with the `var` version.

**Comment by loganfsmyth** [comment]
I'd have to dig into the spec to remember how things are supposed to interact around `eval`, it probably adds additional weirdness.

**Comment by fatcerberus** [comment]
> Not running that file through Babel should avoid the issue.

Agreed, I just wanted to figure out what was going on.  The code in question seemed wrong to me from the start :-)

**Comment by loganfsmyth** [comment]
Yeah, if you didn't see, I filed an issue above ^ for us to track this particular case. I don't know that we'd implement it any time soon or ever, but it's at least something to keep in our list.

**Comment by fatcerberus** [comment]
Out of curiosity though, is there a reason Babel transforms the function definition into a function expression in the first place?  That changes the hoisting behavior in any case so it seems like kind of an odd transformation to do.

**Comment by loganfsmyth** [comment]
If it left it as a function declaration, the code could throw an exception in an ES5 environment, because support for function declarations inside `if` blocks wasn't part of the ES5 spec. It needs to convert it to an expression in order to be sure the code will not be considered a syntax error.

**Comment by fatcerberus** [comment]
Ah, that makes sense.  Anyway, since there's nothing for Babel to fix here, I'll close the issue.  Thanks!

**Comment by fatcerberus** [comment]
It turns out there was nothing wrong with Babel's transformation even for this questionable legacy code.  The cause of the error in my case was a hoisting bug in Duktape - a hoisted `var` at top level overwrites any global binding with the same name.  That doesn't happen in Node.

**Comment by bakkot** [comment]
For reference, the case of hoisting out of `eval` is a particularly complex one, and I wouldn't trust that node gets it right. Implementations differ, and in fact there's [an open spec question](https://github.com/tc39/ecma262/issues/753) about what the right behavior actually should be.

**Comment by fatcerberus** [comment]
Yeah, in my case it wasn't actually a hoisting issue at all - it was that in Duktape, e.g.:
```js
console.log(Math);  // undefined
var Math;
```

Which is a clear bug.  It's since been fixed.
