### ISSUE TITLE
I have this error, how solve it?

### ISSUE THREAD

**Issue by Shadowman4205** [babel/babel#5268]
ERROR in ./~/babel-core/lib/helpers/resolve.js
    Module not found: Error: Cannot resolve module 'module' in ......\node_modules\babel-core\lib\helpers
     @ ./~/babel-core/lib/helpers/resolve.js 34:14-31

**Comment by montogeek** [comment]
@Shadowman4205 Can you please post your Babel config?
Probably is just a typo when requiring the module

**Comment by hzoo** [comment]
There's not enough info here to help, please join the slack or paste relevant reproduction information  for us to debug

**Comment by anthony-skr** [comment]
I have the same error.

I'm trying to use babel `babel.transform(source, options);` function inside a React application :

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';

class App extends Component {
  render() {
    const babel = require('babel-core');
    return (
        <View>
          <Text>Hello.</Text>
        </View>
    );
  }
}

export default App;
```

Error :
```
Error in ./~/babel-core/lib/helpers/resolve.js
Module not found: 'module' in C:\Projects\react\appss\node_modules\babel-core\lib\helpers

 @ ./~/babel-core/lib/helpers/resolve.js 34:14-31
```

.babelrc / webpack configuration are untouched, they are React defaults.

**Comment by anthony-skr** [comment]
Ok I figured out. It's the error we face when using babel on a non-node environment.

Solution: https://github.com/babel/babel-standalone
