### ISSUE TITLE
Make babel-node a standalone package (similar to babel-register)

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5271]
> Ref https://twitter.com/thejameskyle/status/827993163348353025

https://unpkg.com/babel-node@6.5.2/message.js

This would be similar to how we used to have `babel-core/register` -> `babel-register`

I guess we don't have to remove `babel-node` from babel-cli unless we want to make that breaking change..

cc @JonnyBurger (can you transfer me the npm package (@hzoo))

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing 
- [ ] make a new package in the `packages` folder called babel-node and copy the package.json/npmignore/setup files from another package
- [ ] copy the files from babel-cli to the new package https://github.com/babel/babel/tree/master/packages/babel-cli/src. (after we release we can make babel-cli reference the new package)
- [ ] copy and test the babel-node test fixtures https://github.com/babel/babel/tree/master/packages/babel-cli/test/fixtures/babel-node

**Comment by chitchu** [comment]
Hi @hzoo,

If you don't mind I can pick this up.

**Comment by chitchu** [comment]
> ... copy the package.json/npmignore/setup files from another package

Would it be better if the target package is `babel-cli`?

And before I make the pull request. This what the `babel-node` folder looks like. Did I miss anything?

```sh
.
├── README.md
├── index.js
├── package.json
├── src
│   ├── _babel-node.js
│   ├── babel
│   ├── babel-external-helpers.js
│   └── babel-node.js
└── test
    ├── fixtures
    └── index.js

4 directories, 7 files
```

**Comment by hzoo** [comment]
> Would it be better if the target package is babel-cli?

Yeah good idea

Right, whatever is necessary to make it work on it's own. Can check that the necessary deps are in package.json since you might not need everything.

So this means you probably don't need src/babel/* or babel-external-helpers.js, and you'll want the bin folder https://github.com/babel/babel/blob/master/packages/babel-cli/bin/babel-node.js + add bin in package.json
