### ISSUE TITLE
Unexpected env option behaviour

### ISSUE THREAD

**Issue by vkbansal** [babel/babel#5275]
### Babel Configuration (.babelrc, package.json, cli command)
This config does not work.
```js
{
    "presets": [
      "react"
     ],
     "plugins": [
          "transform-class-properties"
     ],
    "env": {
      "es6": {
        "presets": [
          "es2016"
        ]
      },
      "es5": {
        "presets": [
          "es2015"
        ]
      }
    }
  }
```

But, this config works.
```js
{
    "presets": [
      "react"
    ],
    "env": {
      "es6": {
        "presets": [
            "es2016"
          ],
        "plugins": [
          "transform-class-properties"
        ]
      },
      "es5": {
        "presets": [
          "es2015"
        ],
        "plugins": [
          "transform-class-properties"
        ]
      }
    }
  }
```
Code in action:

Failing build:
https://travis-ci.org/vkbansal/react-contextmenu/builds/199246315

Working build:
https://travis-ci.org/vkbansal/react-contextmenu/builds/199253625

**Comment by mdarse** [comment]
I hit the same issue, would a PR fixing this behaviour be accepted?

**Comment by hzoo** [comment]
If you can manage, yes! Although we're also thinking about removing this option entirely ^ in favor of something like a `.babelrc.js`

**Comment by mdarse** [comment]
The merging strategy is often a problem because it doesn't always produces the expected result.
Is the expected behaviour to only do a shallow merge of the config options? I mean, trying to merge preset options for example is error prone.

**Comment by hzoo** [comment]
If we change behavior that isn't already an error, then even if it's a bug fix it may break other people's builds so then I'm not sure (although yeah it does make sense to replace the whole key like a shallow mere)

**Comment by hzoo** [comment]
Pasting what I wrote in the other issue:

We're going to go with deprecating "env" as an option in 7.0 and asking for users to use a `.babelrc.js` file to support this use case (https://github.com/babel/babel/pull/4892). Basically the workaround is the new suggestion since it's not too much of a pain to do. We can think about writing some utils or just recommending what's done for webpack like https://github.com/kentcdodds/webpack-config-utils.

**Comment by silvenon** [comment]
How did this issue happen? Why does `babel-preset-e2016` override `transform-class-properties`?  Until `.babelrc.js` becomes a thing, it would be nice to be able to avoid these issues.
