### ISSUE TITLE
[7.0] Deprecate env option in .babelrc

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5276]
~~## EDIT: We're just going to deprecate now~~
## Fixing merge behavior instead

Original issue details: 
<details>
http://babeljs.io/docs/usage/babelrc/#env-option

some env issues: https://github.com/babel/babel/issues/5275, https://github.com/babel/babel/issues/4539, https://github.com/babel/babel/issues/4013, https://github.com/babel/babel/issues/4817

```js
{
  "env": {
    "production": {
      "plugins": ["transform-react-constant-elements"]
    }
  }
}
```

Options specific to a certain environment are merged into and overwrite non-env specific options.

The env key will be taken from process.env.BABEL_ENV, when this is not available then it uses process.env.NODE_ENV if even that is not available then it defaults to "development".

- [ ] remove the merge behavior (each env needs to specify every config value again)
- [ ] drop the env option entirely and recommend using `.babelrc.js` using a combiation of ternaries + process.env manually (https://github.com/babel/babel/pull/4892)
- [ ] only allow a development, production, profiling env options https://twitter.com/dan_abramov/status/828997631561039872
- [ ] remove development as the default environment https://github.com/babel/babel/blob/badce969dafaf3128104cbc6d6bc605e2b47a3f5/packages/babel-preset-react/src/index.js#L22
- [ ] better validation from babel's side if plugins/presets use env
- [ ] ?

> true that allowing .js may lead to crazy configs but think it's better than confusing with babelrc/env
</details>

Because it's JS you could do this in a lot of ways

```js
var env = process.env.BABEL_ENV || process.env.NODE_ENV;
```

```js
// inline plugin
module.exports = {
  plugins: [
    env === 'development' && "transform-react-constant-elements"
  ].filter(Boolean)
};
```

https://github.com/facebookincubator/create-react-app/blob/65e63403952f4f3c7e872f707fb3736e339254d9/packages/babel-preset-react-app/index.js#L42-L51
```js
var plugins = [];
if (env === 'development') {
  plugins.push.apply(plugins, ["transform-react-constant-elements"]);
}
module.exports = { plugins };
```

**Comment by jharris4** [comment]
```drop the env option entirely and recommend using .babelrc.js using a combiation of ternaries + process.env manually```

Is the idea here to support a `.babelrc.js` file that works the same way as the existing `.babelrc` file?

**Comment by hzoo** [comment]
Yeah https://github.com/babel/babel/pull/4892 (added to the description) - it's the same thing

**Comment by xtuc** [comment]
Yes, the config would be moved there. You will have then the ability to write JavaScript.

**Comment by danez** [comment]
The more I think about this, the more I like it. We could even remove .babelrc  support completely and only support the js variant? 😈

**Comment by jharris4** [comment]
I like the idea of `.babelrc.js`, but this might not be compatible with having a babel config inside `package.json`.

I'd hate to see that feature be dropped, because it's very convenient to be able to specify & maintain babel plugins and their associated package dependencies all in one file.

The other bonus of using a babel config in `package.json` is that it doesn't have the side effect that `.babelrc` files do where the babel config might be unintentionally loaded by some consumer of the project that wants to do its own babel configuration...

**Comment by jharris4** [comment]
Also, just to chime in about the ```only allow a development, production, profiling env options``` idea, I think this might be a bit too limiting.

Several of our projects make use of custom `env` values, such as `es` (to support separate builds in the `jsnext:main`/`module` format) and `test` (to support custom plugins like `babel-plugin-rewire` that should **only** ever be included when building/running tests)

**Comment by hzoo** [comment]
> The other bonus of using a babel config in package.json is that it doesn't have the side effect that .babelrc files do where the babel config might be unintentionally loaded by some consumer of the project that wants to do its own babel configuration...

It should still because it reads from either babelrc/package.json - you would use `babelrc: false` to prevent that.

**Comment by hzoo** [comment]
Ok given the widespread use of use of this, let's go with deprecating this feature in 7.0 and then merging `babelrc.js`.

**Comment by kaicataldo** [comment]
So now we just want to print a warning about `env` is being deprecated and that it will be removed in v8.0.0 when it's used, yeah? Or does deprecation involve more than that?

**Comment by azu** [comment]
It will be big breaking change.
I think that it should have graceful migration plan.

> remove the merge behavior (each env needs to specify every config value again)  
> remove development as the default environment 

This breanking change may have a potential risk.
Existing `.babelrc` will continue to work, but it will be broken.
Concernedly. The user can't notice this changes.

IMHO, `.babelrc` keep going existing behavior and `.babelrc.js` adopt new algorithm.

**Comment by kaicataldo** [comment]
@azu I think the point of deprecation is that it won't be a breaking change

**Comment by hzoo** [comment]
The description of the issue is for the original issue which was about removing it not deprecating it, I'l update

**Comment by azu** [comment]
I see.

Is this behavior actually changed in v7 -> v8?
( I alreadly know that some user ignore deprecated warning... [My concern](https://github.com/babel/babel/issues/5276#issuecomment-284889496) will be revisited at that time )

**Comment by kaicataldo** [comment]
@azu No, `env` will remain as it is now. We will just be recommending using a .babelrc.js file instead of .babelrc with `env`.

**Comment by hulkish** [comment]
Is `babelrc.js` always expected to return an object? Ideally... I think it'd nice if it also supported exporting a function. This way you can really gain better control on babel configs for isomorphic apps.

**Comment by hulkish** [comment]
nevermind.. it appears tis is already the case: https://github.com/babel/babel/blob/7.0/packages/babel-core/src/config/loading/files/configuration.js#L105

woot!

**Comment by mastilver** [comment]
Shameless plug: I wrote this babel preset a few months ago: https://github.com/mastilver/babel-preset-when

Let's say you are doing that with babel@6:

```js
"env": {
  "development": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "last 2 versions"
            ]
          },
          "modules": false
        }
      ]
    ]
  },
  "production": {
    "presets": [
      [
        "env",
        {
          "modules": false
        }
      ]
    ]
  }
}
```

This will work with babel@7:

```js
{
  "presets": [
    "when": {
      "NODE_ENV=development": {
        "development": {
          "presets": [
            [
              "env",
                {
                  "targets": {
                    "browsers": [
                      "last 2 versions"
                    ]
                  },
                  "modules": false
                }
              ]
            ]
          },
          "production": {
            "presets": [
              [
                "env",
                {
                  "modules": false
                }
              ]
            ]
          }
        }
      }
    }
  ]
}
```

**Comment by danielbayley** [comment]
So, just to be clear, is the plan to eventually deprecate `.babelrc` also, or just `env`?

**Comment by xtuc** [comment]
@danielbayley The plan here is to deprecate only `env` for now.

**Comment by kittens** [comment]
This is disappointing. This makes it really hard to cache code from Babel. Including `BABEL_ENV` in a cache key was easy, but now any potential cache key would have to have some interop to specify the environment variables some plugins may be looking for.

**Comment by hzoo** [comment]
@kittens, @loganfsmyth was working on caching for configs - https://github.com/babel/babel/pull/5608

**Comment by OlegLustenko** [comment]
Hi, What do you think that updates require a deprecation warning in documentation and at compilation phase, in older versions.

in 7.0 alphas and 6?

**Comment by xtuc** [comment]
@OlegLustenko yes, this will require a proper  depreciation phase. I don't think it will be part of the first 7 release (or 6.x) but probably in 7.1.

**Comment by danielbayley** [comment]
So what happens with `package.json`.`babel`?

**Comment by xtuc** [comment]
@danielbayley We won't break existing configuration. We are just trying to discourage peoples to use the `env` key in their configuration (including in the package.json file).

**Comment by greggb** [comment]
As a data point - I had no idea that merging options between envs didn't work. Deprecating in favor of JS would make this much more clear.

**Comment by loganfsmyth** [comment]
Yeah, the only alternative that comes to mind for me is that we could keep this, but change the logic so that instead of merging, the `env` blocks replace the root config.

**Comment by loganfsmyth** [comment]
We've decided that this isn't necessary because we've changed how Babel 7 handles option merging to make this more reasonable for users, and that should be enough.

Config in `env` is given higher priority than root config items, and instead of just being a weird approach of using both, plugins and presets now merge based on their identity, so you can do

```
{
  presets: [
    ['env', { modules: false}],
  ],
  env: {
    test: {
      presets: [
         'env'
      ],
    }
  },
}
```
with `BABEL_ENV=test`, which would replace the root `env` config, with the one from `test`, which has no options.
