### ISSUE TITLE
Babel's color detection uses stdout for stderr output

### ISSUE THREAD

**Issue by thanatos** [babel/babel#5278]
When Babel outputs errors, it occasionally does beautiful syntax highlighting on the problematic section. Many programs that do this check if they're writing to a terminal prior to outputting color code, typically with a call to `isatty`. Babel appears to make this check, but appears to check whether *stdout* is a TTY prior to writing to *stderr*.

In particular, the following command, which outputs errors to a terminal, is not colored, despite the output being a terminal:

    % babel foo.js >foo_transpiled.js

Whereas the following outputs exactly the same information to stderr, but colored:

    % babel foo.js -o foo_transpiled.js

Ideally, the `isatty` check (or equivalent) needs to made on the file descriptor that you're trying to decide whether to emit colored output to.

### Expected Behavior

If the output is a terminal and the output for terminals should be colored, colored output.

### Current Behavior

If the output is stderr, and a terminal, but stdout is not a terminal, the output is not colored.

### Possible Solution

Check the same FD with `isatty` as you're writing to, if indeed that's the check that is made. (I haven't investigated into Babel's source far enough to know how/where Babel checks.)

### Context

I'm running an entire project through Babel with a `Makefile`. However, I'm also post-processing the output slightly, in order to make it both compatible with Node (for unit testing) and with Google Sheets (where my code is destined; Sheets has an extremely peculiar implementation of JS, which is partly why I'm transpiling to it). To that end, the actual command I end up running is something like,

```
{
    printf '<a short JS header for each file>'
    babel the_file.js
} > transpiled/the_file.js
```

Because of that structure, babel's `stdout` is a pipe, but `babel`'s stderr is still a TTY (my screen).

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.2 (babel-core 6.22.1)
| node             | 7.5.0
| npm              | 4.1.2
| Operating System | OS X 10.12.3 ("macOS Sierra")

**Comment by xtuc** [comment]
Closing, out of scope for now.
