### ISSUE TITLE
Transpile dependent files

### ISSUE THREAD

**Issue by pronebird** [babel/babel#5281]
Hi,

I use a plugin that enables to require CSS in javascript, so basically when required it's transpired into JS dictionary with keys that point to CSS classes. At the same time CSS file is being compiled on disk. 

The problem I face is to keep both CSS and JS files in sync, i.e if CSS file is being changed on disk, I'd like to find all files that require it and recompile them. 

Is there any way to be notified when "required" files are being changed and is it possible to ask babel to re-transpile files that require my CSS files?

I use babel with `--watch` option.

i.e:

```js
import styles from 'my.css';
```

Now when `my.css` is being changed I would like to 
1. be notified that it changed 
2. re-transpile JS file that imported `my.css`

Cheers,
Andrej

**Comment by hzoo** [comment]
This seems kind of out of scope for babel itself (--watch is useful for just basic tasks), I would recommend using something like gulp/webpack to handle these issues
