### ISSUE TITLE
IE8 Expected identifier - BlueBird Promise

### ISSUE THREAD

**Issue by codeuniquely** [babel/babel#5282]
IE8
Babel Version 6.13.2
BlueBird Version 3.4.7
WebPack Version 1.13.2

The Bluebird Promise library runs successfully in IE7/8 but specifically has the following line of code that is causing and issue after using WebPack / Babel JS to transpile the project code..

We include the bluebird promise library and the following line function exists in the library:
```
Promise.prototype["break"] = Promise.prototype.cancel = function() { ... }
```

but after generating the code for the project (through babel) the line emerges like this
```
Promise.prototype.break = Promise.prototype.cancel = function() { ... }
```

and of course IE8 responds with the following ERROR message
```
Promise.prototype.break
                 ^
Message: Expected identifier
Line: 3
Char: 15341
Code: 0
URI: https://test.site.com/app/v1/vendor.bundle.js?_=2ab201fef8b57f9ae729
```

as using a keyword is not allowed - 

Can the babel optimisation be tuned off so that we can keep the specific Array notation instead of switching to a dot notation ?

**Comment by hzoo** [comment]
Can join our slack ^ in the future for support questions

> Can the babel optimisation be tuned off so that we can keep the specific Array notation instead of switching to a dot notation ?

You shouldn't need to transpile Bluebird? I would just require the library and babel won't need to do anything do it since it would be touched at all. If you really have to you can add http://babeljs.io/docs/plugins/transform-es3-member-expression-literals
