### ISSUE TITLE
[7.0] move legacy-decorators into the repo, replacing current decorators

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5283]
https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy

Basically since the [current decorators transform](https://github.com/babel/babel/blob/f8ffe03e79d95b2b9ed3481dbb3e90b76c536d90/packages/babel-plugin-transform-decorators/src/index.js#L74-L86) throws an error, we should just move the implementation (even though it's the older stage-1 spec) into the babel repo. We'll do this in Babel 7 so it doesn't cause issues for anyone

We'll also want to change stage-1 to refer to the current transform again (reverting the previous pr) but we can do that.

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] Copy the contents of https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy into the transform-decorators folder under the `packages/` directory. Try to keep the structure of the current repo but then replacing with src/tests/readme and merge the correct things where possible.
- [ ] might need to change the structure of the tests to match how babel does things via fixtures, etc but we can help with this

**Comment by alxpy** [comment]
@hzoo I'd like to work on this

**Comment by hzoo** [comment]
Sounds good! I would recommend checking out our [slack community](https://slack.babeljs.io/) if you need help (or comment here)

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel/issues/5290!!
