### ISSUE TITLE
Class method is not a function when inherits from Error

### ISSUE THREAD

**Issue by shaunxu** [babel/babel#5284]
### Input Code

```js
class WTIMError extends Error {
    constructor () {
      super();

      console.log(`The error is: ${JSON.stringify(this.toObject(), null, 2)}`);
    }

    toObject () {
        return {
          name: 'Shaun'
        };
    }
}

const error = new WTIMError();
```

### Babel Configuration (.babelrc, package.json, cli command)

```
babel --presets es2015-node6,stage-3
```

### Expected Behavior
It should display 
```
The error is: {
  "name": "Shaun"
}
```

### Current Behavior
It reports an error said 
```
_this.toObject is not a function
```

This can also be repo-ed in Try-it page in babel site.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.1
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | macOS 10.12.3

**Comment by loganfsmyth** [comment]
See `Caveats` here: https://babeljs.io/docs/usage/caveats/#classes
