### ISSUE TITLE
[7.0] Change ForAwaitStatement node type to match ESTree

### ISSUE THREAD

**Issue by danez** [babel/babel#5286]
Ref https://github.com/estree/estree/pull/138

> Change to be `ForOfStatement with property "await": true`

Original PR: https://github.com/babel/babylon/pull/17
Babylon PR: https://github.com/babel/babylon/issues/348

---
- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] Remove ForAwaitStatement from `babel-type` and `babel-generator`
- [ ] Exchange ForAwaitStatement with ForOfStatement in `babel-helper-remap-async-to-generator`
- [ ] Use new field `await` from ForOfStatement in `babel-generator` and `babel-helper-remap-async-to-generator`
- [ ] Ensure the tests are still working.

**Comment by aweary** [comment]
@danez I'd love to follow up on https://github.com/babel/babylon/issues/349 and do this as well.

**Comment by aweary** [comment]
@danez is there a recommended way to integrate the changes made to babylon https://github.com/babel/babylon/pull/349? The version that `babel-core` depends on still generates the `ForAwaitStatement` node and I think that might be giving me trouble with the tests.

**Comment by hzoo** [comment]
Separately, babylon should just be in the monorepo to prevent this kind of issue! We just need to release a 7.0 prerelease and change 7.0 to depend on that

**Comment by existentialism** [comment]
@aweary you can [link them locally](https://github.com/babel/babylon/blob/master/CONTRIBUTING.md#cross-repository-changes)

**Comment by hzoo** [comment]
Made https://github.com/babel/babel/pull/5317 so you can base your PR off of my branch

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/5321
