### ISSUE TITLE
Clarify type of 'plugins' in options obj

### ISSUE THREAD

**Issue by hughrawlinson** [babel/babel#5295]
Lil' documentation issue [here](https://github.com/babel/babel/blob/160bd3924bcd36a714f70f57ceaf5959d7ccdb49/packages/babel-core/README.md#options). The 'options' object contains a property called 'plugins', which is described as 'List of plugins to load and use'. It'd be really great to clarify whether this means 'a list of plugin names that babel will use' or 'a list of required plugin objects that babel will use'. At the moment, it's not clear. Same goes for 'presets' property. Thanks! 😄

**Comment by hzoo** [comment]
Cool, yeah it takes in a few things but most likely you will just pass in a string.

```js
{
  "presets": ["env"]
}
```

**Comment by hughrawlinson** [comment]
@hzoo looks like it also takes in the instantiated plugin object as well 😄 If there's a category of types it accepts, it'd be really nice to document them. I'd do the PR myself, I just don't know what that category contains.

**Comment by hzoo** [comment]
Yeah I believe it would be those 3 - string, array (options), function, object https://github.com/babel/babel/blob/75ac320cf7b763a438afabb354820fe4806d5df4/packages/babel-core/src/transformation/file/options/option-manager.js#L106 - that part is rather confusing so not sure myself!
