### ISSUE TITLE
Better setup

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5299]
If a new contributor does `npm run test` or `make test` and expects it to work you are greeted with `Error: Cannot find module '../lib'` because they didn't run `make bootstrap`. @montogeek

Of course we could be like "You should read the contributing.md, etc" but why not just do it automatically then?

- Basic idea is that these commands should figure out whether the folder in `packages/*/lib` are empty or not and then run `make build`. If it's not bootstrapped properly it should run `make bootstrap`.

If we do this right they may not have to do anything other than git clone + npm install?

**Comment by chicoxyzzy** [comment]
Maybe we can use `postinstall` npm script?

**Comment by hzoo** [comment]
if that works in our top level package.json then 👍 , can just do `make bootstrap` there.

**Comment by chicoxyzzy** [comment]
Looks like `make bootstrap` will run `make clean:all` which will remove `node_modules` and run `npm install` again so maybe `preinstall` fits better here. I'll check if that works.

**Comment by chicoxyzzy** [comment]
Install process goes into infinite loop for both `preinstall` and `postinstall` because of `npm install` command in `make bootstrap`

**Comment by hzoo** [comment]
lol that's interesting.. yea we need to remove it one of them then

**Comment by chitchu** [comment]
You can skip the `preinstall` and `postinstall` by running `npm install --ignore-scripts` in `make bootstrap` to avoid recursion.

**Comment by hzoo** [comment]
Just going to close this in favor of the PR https://github.com/babel/babel/issues/5309 even though it's not merged
