### ISSUE TITLE
generator error in jasmine: ReferenceError: regeneratorRuntime is not defined 

### ISSUE THREAD

**Issue by feexon** [babel/babel#5314]
I tried to solve the problem in issuses,but I can't.I need your helps.I test under jasmine using babel,when I run the tests it throws exception below:
1) generators iterator
  Message:
    ReferenceError: regeneratorRuntime is not defined
  Stack:
    ReferenceError: regeneratorRuntime is not defined

my test code like this:
```js
describe('generators', function () {
    it('iterator', function () {
        var numbers = {
            [Symbol.iterator]: function*() {
                for (let i = 1; i < 3; i++) {
                    yield i;
                }
            }
        };

        let result = [];
        for (let v of numbers) result.push(v);
        
        expect(result).toEqual([1, 2]);
    });
});
```

**Comment by feexon** [comment]
I'm from China,I can't join your slack system.

**Comment by hzoo** [comment]
`regeneratorRuntime is not defined` occurs because when using generators or anything similar to that it expects `regeneratorRuntime` as a global variable. You can just import babel-polyfill at the entry point of all your test files http://babeljs.io/docs/usage/polyfill/

Looks like http://stackoverflow.com/a/28988642/724650.

**Comment by feexon** [comment]
thanks very much.I found polyfill not imported in jasmine automatically.when I use require('babel-polyfill') it makes tests run very slowly and the tests failed too.I solve the problem from your links:

```js
{
  "helpers": [
    "../node_modules/babel-register/lib/node.js",
    "../node_modules/babel-polyfill/browser.js",
    "helper/matchers.helper.js"
  ]
}
```

**Comment by hzoo** [comment]
if you only need regeneratorRuntime you can just import the specific file https://www.npmjs.com/package/regenerator-runtime
