### ISSUE TITLE
[7.0] Switch decorators-legacy to decorators in the Stage 1 Preset

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5318]
> We'll also want to change stage-1 to refer to the current transform again (reverting the previous pr) but we can do that.

Kinda revert part of https://github.com/babel/babel/pull/5225 due to https://github.com/babel/babel/pull/5290 (replace transform-decorators to be decorators-legacy)

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] change `babel-preset-stage-1` [package.json](https://github.com/babel/babel/blob/fa2a373acd54d8330a943d3c99cc2f2833391836/packages/babel-preset-stage-1/package.json#L11) and [src/index.js](https://github.com/babel/babel/blob/fa2a373acd54d8330a943d3c99cc2f2833391836/packages/babel-preset-stage-1/src/index.js#L3-L11)
- [ ] just need to remove the `-legacy` in both places

example

```diff
- "babel-plugin-transform-decorators-legacy": "^1.3.4",
+ "babel-plugin-transform-decorators": "^1.3.4",
```

**Comment by sashashakun** [comment]
Hello! I want to help with this:)

**Comment by hzoo** [comment]
Awesome! For this one, you technically can just make the patch from the website (if you know how) but I would follow the instructions above 👍

**Comment by sashashakun** [comment]
I know how, but I will follow the instructions👌

**Comment by hzoo** [comment]
Nice work @sashashakun! - https://github.com/babel/babel/issues/5319

**Comment by chicoxyzzy** [comment]
decorators are on stage 2

**Comment by hzoo** [comment]
@chicoxyzzy yes but the implementation is old so we aren't updating
