### ISSUE TITLE
[bug] Rest parameters in async function

### ISSUE THREAD

**Issue by laggingreflex** [babel/babel#5330]
### Input Code

```js
const a = async(...args) => console.log(args);
const b = async(...args) => a(...args);

b('1');
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
"presets": [
    "es2015",
    "stage-0"
  ]
```

### Expected Behavior

It should output `[ '1' ]`. Works with node 7 --harmony. Also works without async functions. Problem is only with async functions

### Current Behavior

It outputs something big I'm not sure what (global object?)

```
Module {
    id: 'C:\\...\\test\\utils\\memoize.js',
    exports: {},
    parent:
     Module {
       id: 'C:\\...\\test\\utils\\index.js',
       exports: [Object],
       parent: [Object],
       filename: 'C:\\...\\test\\utils\\index.js',
       loaded: false,
       children: [Object],
       paths: [Object] },
    filename: 'C:\\...\\test\\utils\\memoize.js',
    loaded: false,
    children: [ [Object] ],
    paths:
     [ 'C:\\...\\test\\utils\\node_modules',
       'C:\\...\\test\\node_modules',
       'C:\\...\\node_modules',
       'C:\\...',
       'C:\\...node_modules',
       'C:\\...
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             |  7
| npm              |  3
| Operating System |  win10

    "babel-cli": "^6.22.2",
    "babel-polyfill": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-0": "^6.22.0",

**Comment by laggingreflex** [comment]
related (dupe?) https://github.com/babel/babel/issues/4219

**Comment by hzoo** [comment]
Yeah I believe so 👍 , https://github.com/babel/babel/issues/4219
