### ISSUE TITLE
Cannot find module 'rc-util' 

### ISSUE THREAD

**Issue by yangchongduo** [babel/babel#5332]
Cannot find module 'rc-util'

**Comment by loganfsmyth** [comment]
This really isn't enough information to go on. What makes you say this is a Babel issue? Have you tried reinstalling?

**Comment by loganfsmyth** [comment]
Please re-open when you have more info. Closing for now.

**Comment by xtuc** [comment]
Please next time use our [issue template](https://raw.githubusercontent.com/babel/babel/master/.github/ISSUE_TEMPLATE.md).
