### ISSUE TITLE
Unknown option: base.presets[]

### ISSUE THREAD

**Issue by MatteoGabriele** [babel/babel#5345]
I can't access to the options of a preset without throwing an `Unknown option: base.presets[]` error

This is my setup for `babel` using `webpack@2.2.0`
Works perfectly without the presets options but would be nice to be able to access them.

```js
module.exports = {
  test: /\.js$/,
  loader: 'babel-loader',
  exclude: /node_modules/,
  options: {
    presets: [
      [require.resolve('babel-preset-latest'), {
        "es2015": {
          "modules": false
        }
      }],
      require.resolve('babel-preset-stage-3')
    ],
    plugins: [
      require.resolve('babel-plugin-transform-regenerator')
    ]
  }
}

```

This is the error in the console

```bash
Module build failed: ReferenceError: [BABEL] /web/matteogabriele/beta/src/app/page/home/home.js: Unknown option: base.presets[]. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
    at Logger.error (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at OptionManager.init (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/web/blocklevel/blue-next/packages/bcli/node_modules/babel-loader/lib/index.js:134:16)
 @ ./src/app/page/home/home.vue 8:2-472
 @ ./src/app/routes.js
 @ ./src/bootstrap.js
 @ multi ./src/bootstrap.js
```

The error itself is pretty nice when you write it wrong, but here I guess I'm doing in correctly.

Thanks in advance for you help

| software         | version
| ---------------- | -------
| Babel            |  v6.21.0
| node             |  v7.4.0
| npm              |  v4.1.1
| Operating System | MacOS Sierra 10.12.2

**Comment by aaronang** [comment]
Interesting, I tried to reproduce your error but got a different error instead, that says that `options` is not a valid property. Note that I am using `webpack@2.2.0`.

However, I did manage to get the options working as follows:

```JavaScript
var path = require('path');
var webpack = require("webpack");

module.exports = {
  entry: './app/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  options: {},
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: [
            [require.resolve('babel-preset-latest'), {
              "es2015": {
                "modules": false
              }
            }]
          ]
        }
      }
    ]
  }
};
```

**Comment by MatteoGabriele** [comment]
hi @aaronang I'm not using `.babelrc` because in this particular project doesn't suit my needs. Has to be like this.

I will try to add `query` instead of `options` even if it's really weird :)

thanks

**Comment by aaronang** [comment]
@MatteoGabriele Are you by the way sure that you are using `webpack@2.2.0`? I am asking this because I created a clean project using `2.2.0` and I got an error saying that `options` is not a valid property.

**Comment by MatteoGabriele** [comment]
Super sure :) 

https://github.com/Blocklevel/blue-next/blob/master/packages/bcli/package.json#L80

**Comment by MatteoGabriele** [comment]
@aaronang I tried the `query` instead of `options` and it does work, I don't have any errors.

if you read webpack2 documentation, `query` is there only for compatibility https://github.com/Blocklevel/blue-next/blob/master/packages/bcli/package.json#L80

**Comment by MatteoGabriele** [comment]
No...never mind! i wasn't linking the package and it was not executing my changes, so the issue is still there, with or without `query`. Sorry for the fake news 😄

**Comment by aaronang** [comment]
@MatteoGabriele You are right, you can use `options` too instead.

```JavaScript
var path = require('path');
var webpack = require("webpack");

module.exports = {
  entry: './app/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        options: {
          presets: [
            [require.resolve('babel-preset-latest'), {
              "es2015": {
                "modules": false
              }
            }],
            require.resolve('babel-preset-stage-3')
          ],
          plugins: [
            require.resolve('babel-plugin-transform-regenerator')
          ]
        }
      }
    ]
  }
};
```

Have you defined `output`?

**Comment by MatteoGabriele** [comment]
@aaronang yep! everything works. Just wanted to try to use this options because apparently reduces the size of the bundle.

**Comment by aaronang** [comment]
I guess we can close this issue?

**Comment by MatteoGabriele** [comment]
well actually is still not working for me, my setup works, but not when i put that option.

**Comment by existentialism** [comment]
@MatteoGabriele mind creating a small repo that repros the issue outside of your CLI project?

**Comment by MatteoGabriele** [comment]
@existentialism I've actually wrote a small test and it works, so must be  something in my project setup that is not working properly. No idea.

Thanks both for you time :)

**Comment by existentialism** [comment]
@MatteoGabriele no problem! Let us know if you find any issues!

**Comment by MatteoGabriele** [comment]
@existentialism I know we already closed the issue but it is something that i don't get it. Just look at this gif I made. I just add presets normally, which works, then when i add the options it crashes.

Thanks again! :)

![screen recording 2017-03-10 at 08 16 pm](https://cloud.githubusercontent.com/assets/5337152/23810101/7a42a5f2-05d0-11e7-8c68-b277c8054311.gif)

**Comment by congzhaoyang** [comment]
i am facing the same problem。

**Comment by pailoro** [comment]
+1
