### ISSUE TITLE
Calling Bound Class Methods In Property Initializer Throw Runtime Exception

### ISSUE THREAD

**Issue by iammerrick** [babel/babel#5346]
Calling bound class methods in property initializers throws a runtime exception that it can't be found.

### Input Code

[REPL Link](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=class%20Example%20%7B%0A%20%20%0A%20%20state%20%3D%20%7B%0A%20%20%20%20name%3A%20this.getName()%0A%20%20%7D%0A%20%20%0A%20%20getName%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20return%20'Merrick'%3B%0A%20%20%7D%0A%7D%0A%0Aconsole.log(new%20Example())%3B&experimental=false&loose=false&spec=false&playground=true)
```js
class Example {
  
  state = {
    name: this.getName()
  }
  
  getName = () => {
    return 'Merrick';
  }
}

console.log(new Example());
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": [
      "latest",
      "react"
    ]
}
```

### Expected Behavior

Because I can call unbound class methods in my initializers, I expected bound functions to work as well. Maybe this is a use case for a custom constructor, but perhaps this could throw a compiler error when you try to do this?

### Current Behavior
It compiles but throws an exception at runtime stating that the function couldn't be found.

### Possible Solution
This use case could be solved by putting bound methods above initializers in the constructor. I believe that would also keep the current expectations for unbound methods intact.

### Context
I am trying to use a function to compute some initial state, it does *not* have to be bound as I can refactor to not (optionally) leverage state on the class instance itself. Having a runtime error seemed like the wrong idea. I spent about 2 hours trying to resolve this before realising it wasn't an issue in my code. Imagine needing to call some function to compute state... and if there is state to work from, leverage it, if not return something default. That way I could use it for callbacks on events (thus binding it) and initialization.

Update: Here is a link to the pull request trying to leverage this: [Use Case](https://github.com/trevordmiller/trevordmiller-website/pull/25/files#diff-b8b164d3a70e245097ca7144ed137ed5R114)

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.16.0
| node             | 6.7.0
| npm              | 3.10.3
| Operating System | OXS Sierra

**Comment by loganfsmyth** [comment]
The issue here is ordering. Class properties are initialized in order, and from the classes standpoint, `state` and `getName` are both just class properties, there is no special treatment for class properties that are functions. So you'd have the same problem if you did

```
class Foo {
  state = {
    thing: this.thing
  }

  thing = 4;
}
```

this would attempt to create `this.thing` before `thing` has been assigned.

In your case you are trying to call the function `getName` before it exists. Your code would work if you flipped the ordering so `getName =` was before `state =`.

**Comment by iammerrick** [comment]
Hey, @loganfsmyth! Thanks for taking the time to explain that to me! That makes a lot of sense. It is surprising to me that "unbound" methods work as expected. Is that just due to semantics for how class methods work vs property initializers?

I am happy to close this issue, its one of those where I feel like a bit of a putz. Thanks for teaching me; I didn't realize using property initializers and arrow functions was just a trick to get bound class properties!

**Comment by loganfsmyth** [comment]
No problem. The class prototype, where the class methods (`foo(){}`) live, is initialized when the class is declared. So since class properties (`foo = () => {}`) run when each instance is instantiated, the prototype already fully exists so all methods are usable.
