### ISSUE TITLE
[7.0] Replace lodash/assign with Object.assign

### ISSUE THREAD

**Issue by danez** [babel/babel#5353]
We currently us lodash/assign in the codebase: https://lodash.com/docs/4.17.4#assign

For example here https://github.com/babel/babel/blob/454933ef7643dd30b625992cddc8420887cf510e/packages/babel-traverse/src/path/index.js#L7

This is unnecessary for babel 7 as node >4 has the same functionality built-in with `Object.assign`. : https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

<hr />

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] Search for imports of `lodash/assign` and its usages and change to use `Object.assign`
- [ ] Search for imports of `lodash` and usages (`lodsh.assign`) and change to use `Object.assign`
- [ ] In the packages where some lodash imports were removed due to the last two tasks, check if these usages were the last ones to use `lodash` and if so remove `lodash`dependency from package.json
- [ ] Base PR on branch 7.0

**Comment by mdapper** [comment]
I'd like to work on this one @danez if you don't mind!

**Comment by danez** [comment]
Sure, if you have any questions it is the best to join our slack and ask there in #development

**Comment by mdapper** [comment]
Great, I am already there. I made the changes but I want to test them first. If I have any questions I will ask there.

**Comment by hzoo** [comment]
Closed in https://github.com/babel/babel/issues/5356
