### ISSUE TITLE
Babel upgrade issue

### ISSUE THREAD

**Issue by svidhani** [babel/babel#5361]
I am trying to upgrade from Babel 5 to Babel 6 and i keep getting this error when i try to run tests with mocha

Property value expected type of string but got null
on node_modules/babel-core/lib/transformation/file/index.js:600

Mode details here http://stackoverflow.com/questions/42380736/babel-upgrade-error-property-value-expected-type-of-string-but-got-null

**Comment by loganfsmyth** [comment]
Closing since this can be discussed on SO. You tagged in `babel` instead of `babeljs` which is why it didn't get a comment sooner.
