### ISSUE TITLE
Default async functions fail with babylon@6.16.0

### ISSUE THREAD

**Issue by Joezo** [babel/babel#5366]
Exporting default async functions fails to parse with the latest release on babylon(6.16.0). It looks like babylon has fixed a bug https://github.com/babel/babylon/pull/324 in their latest release that babel perhaps relied on. This behaves as expected if I purposefully install babylon@6.15.0.

### Input Code
https://github.com/Joezo/babel-issue

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": 6
        }
      }
    ],
  ]
}
```

### Expected Behavior
The test in the above repo passes and doesn't get a syntax error.

### Current Behavior
You receive this error:
```
SyntaxError: /Users/joewarren/repos/babylon-issue/exportDefaultAsync.js: await is a reserved word (1:27)
> 1 | export default async () => await Promise.resolve(() => console.log('foo'))
    |                            ^
  2 |
  3 |
    at Parser.pp$5.raise (/Users/joewarren/repos/babylon-issue/node_modules/babylon/lib/index.js:4380:13)
```

### Possible Solution
Something to do with the babylon@6.16.0 release.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.1
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | MacOS 10.12.2

**Comment by Joezo** [comment]
Just seen that @martindoyleuk has opened the same issue in https://github.com/babel/babylon/issues/374 - not sure 100% where this issue belong so i'll leave this one as is. Please close if it's better suited elsewhere :)

**Comment by hzoo** [comment]
Yeah it's a babylon issue, same issue.

**Comment by daltones** [comment]
Actually that's not a babylon issue. Babylon v6.16.0 fixes https://github.com/babel/babylon/issues/257.

The build failing is a problem with `babel-plugin-transform-async-to-generator` or `babel-plugin-transform-async-to-module-method`. These transforms didn't expect the right AST for `export default async function` (again https://github.com/babel/babylon/issues/257).

All of this is related to https://github.com/babel/babel/issues/3786, which does not cause crashes but it is a bug.
