### ISSUE TITLE
dynamic string imports and incorrectly transpiled when using amd module loader

### ISSUE THREAD

**Issue by frederikbosch** [babel/babel#5370]
When using `babel-plugin-transform-es2015-modules-amd` in combination with `babel-plugin-syntax-dynamic-import`, dynamic imports with the module name as a string are incorrectly transpiled.

```js
import('script').then();
```
will now transpiles to

```js
define('es-next/dynamic-string-import', ['script'], function () {
  'use strict';
  return new Promise(function (resolve) { resolve(); });
});
```

where as I expect it to transpile to

```js
define('es-next/dynamic-string-import', [], function () {
  'use strict';
  return new Promise(function (resolve) { resolve(require('script')); });
});
```

package versions
```json
"babel-plugin-syntax-dynamic-import": "6.18.0",
"babel-plugin-transform-es2015-modules-amd": "6.22.0",
"babel-generator": "6.23.0",
"babel-core": "6.23.1"
```

environment
```
"npm": "3.10.10"
"nodejs": "6.10.0"
```

**Comment by loganfsmyth** [comment]
Are you using a specific plugin like https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/master/src/index.js to convert these? AFAIK the AMD transform does not support `import()`, and I'm not aware of any plugin yet that tries to support AMD yet.

Also I think for this usecase, I'd expect your example to become something like

```
define('es-next/dynamic-string-import', ['require'], function (require) {
  'use strict';

  return Promise.resolve()
    .then(() => new Promise(resolve => require(['script.js'], resolve)));
});
```

since the `import()` is an async request?

**Comment by frederikbosch** [comment]
@loganfsmyth I wrote [my own plugin for this](https://github.com/genkgo/dtk/blob/master/lib/dynamic-import.js). That originates from the webpack plugin.

And yes, you are right, what I expect maybe different. In any case, I do not expect the import to be picked up as a static import. And I believe that is what happens now. If I do not import a string but a variable dynamically, it works perfectly.

So this works with AMD + dynamic import.
```js
let x = 'script';
import(script).then();
```

But this fails with AMD + dynamic import.
```js
import('script').then();
```

**Comment by loganfsmyth** [comment]
Ah, gotcha. I know what's causing this then. The answer here is "the AMD transform is gross" unfortunately.

One of the big blockers for Babel 7.x is a rewrite of the module transforms, which would also stop this extra transformation from happening with your plugin. I unfortunately don't think there is anything we can do to easily get around this in 6.x at this point.

**Comment by frederikbosch** [comment]
While I do not "the AMD transform is gross", I am happy with your reply. Maybe I will have a look in the AMD module transform soon, and see if I can be of help. Otherwise, I will have to wait for Babel 7!

**Comment by frederikbosch** [comment]
@loganfsmyth Thanks a lot for your feedback. This is possible after all. Your comment made me zoom into the AMD module loader and that made me recognize [my mistake](https://github.com/genkgo/dtk/commit/d37ef5b522cda40c2af41aa6e11160858f620f9b). The `require` method should be called as an array instead of a string.

I will extract that script as a separate amd dynamic import loader to help other AMD loaders with dynamic imports.
