### ISSUE TITLE
Bug: `super.*` should be allowed before `super()`

### ISSUE THREAD

**Issue by zhanzhenzhen** [babel/babel#5371]
### Input Code

```js
"use strict";

class Cat {
    speak() {
        console.log("It speaks!");
    }
}

class Lion extends Cat {
    constructor() {
        setTimeout(() => {super.speak();}, 0);
        super();
    }
}

let lion = new Lion();
```

### Expected Behavior

This code is really legal. On every JS engine that support ECMAScript 2015, it doesn't throw error.

### Current Behavior

Babel does an early syntax check saying `super.*` is not allowed before `super()`.

### Possible Solution

Suppress this early check. The possible error should be runtime, not compile time. If `super.*` is called before `super()`, the JS engine itself will throw a runtime error.

### Context

The above example may be considered not very practical. Here's a more practical example, though a bit longer:

```js
"use strict";

class Cat {
    constructor(options) {
        let eventArg = {};
        setTimeout(() => {
            options.onWake(eventArg);
        }, 3000);
    }

    speak() {
        console.log("Cat speaks!");
    }
}

class Lion extends Cat {
    constructor() {
        let options = {
            onWake: e => {
                super.speak();
            }
        };
        super(options);
    }

    speak() {
        console.log("Lion speaks!");
    }
}

let lion = new Lion();
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  5, 6
| node             | 6
| npm              | 4
| Operating System | macOS

**Comment by zhanzhenzhen** [comment]
Anyone checked it? @loganfsmyth or @hzoo ?

**Comment by xtuc** [comment]
I can reproduice it with a smaller example:

```js
class Foo {}
class Bar extends Foo {
  constructor() {
    const t = () => super.test()
    super()
  }
}
```

[Try in REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=latest&targets=Node-4&browsers=&builtIns=false&code=class%20Foo%20%7B%7D%0Aclass%20Bar%20extends%20Foo%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20const%20t%20%3D%20()%20%3D%3E%20super.test()%0A%20%20%20%20super()%0A%20%20%7D%0A%7D)

This shouldn't throw the error. `t` is not even called.

**Comment by Kovensky** [comment]
That... is a really hairy case. I'm not sure it's possible to correctly transpile arrow functions and classes without violating _something_ about `super` in either one.

**Comment by xtuc** [comment]
I think we should remove the error if the parent node is a function like my example above. Since we can't really statically tell if it's going to be called before the super at runtime.

**Comment by lingsamuel** [comment]
This question maybe undecidable.
Probably it should be a runtime error, and give warnings in compile time instead.

**Comment by xtuc** [comment]
In Chrome 56.0.2924.87:

```js
class Foo4 extends Bar {
  constructor() {
    function t() {
      super.test()
    }
    super();
  }
}

// Error: VM280:4 Uncaught SyntaxError: 'super' keyword unexpected here
```

and 

```js
class Foo5 extends Bar {
  constructor() {
    const t = () => super.test()
    super();
  }
}

// No error
```

What do you think if we allow `super.*` calls before `super()` when the parent node is an `ArrowFunctionExpression`? @loganfsmyth @Kovensky

**Comment by loganfsmyth** [comment]
Does the class transform output something that works, if we remove the compile-time check? I agree that this should be a runtime check, or at least we should just let it throw with whatever error it would throw given the current compiled output.

**Comment by xtuc** [comment]
Ouputs looks like this: https://gist.github.com/xtuc/bc7caa2af9f919b64810f40a5984cf08 and seems to work fine.

If this is OK for your I will submit a PR.

**Comment by loganfsmyth** [comment]
Cool, it is using the right `_this`.

The only downside of that code right now is that it will execute without error when `_this` is `undefined` as far as I can tell.

I'm happy if you want to PR it so it won't error with a parent arrow.

**Comment by zhanzhenzhen** [comment]
That's great!

**Comment by zhanzhenzhen** [comment]
Hi, I see this bug still exists in the "try it out" page (v6.25.0). Is the fix only in v7?

**Comment by jridgewell** [comment]
Yes, we didn't backport it yet.

**Comment by xtuc** [comment]
It's fixed in the [v7 REPL](https://babeljs.io/7/#?evaluate=true&lineWrap=false&code_lz=MYGwhgzhAEBCYCdoG8C-AoUkYDED2eArNAKYAeALiQHYAmM8Sy600we1EFCArsBXgQAKAJQoWrNhy7QK0ALzRRCgHzQIPAA4kEAOipdRE1hu3CRAbgkZUQA).

**Comment by zhanzhenzhen** [comment]
@xtuc Thank you for giving the link!
