### ISSUE TITLE
Expose _babel-node

### ISSUE THREAD

**Issue by jaridmargolin** [babel/babel#5373]
In some instances it may be helpful to execute _babel-node directly. For instance, currently [inspect-process](https://github.com/jaridmargolin/inspect-process/blob/dev/bin/inspect.js) cannot debug child_processes. It implements similar logic to [handle node/v8 args](https://github.com/jaridmargolin/inspect-process/blob/dev/bin/inspect.js) and as a result should be able to side step the babel-node wrapper?

I saw there was an [open PR to make babel-node a standalone package](https://github.com/babel/babel/pull/5279). Perhaps after this work is completed, _babel-node could be [added to the list of executables](https://github.com/babel/babel/blob/master/packages/babel-cli/package.json#L40).

**Comment by xtuc** [comment]
Closing, out of scope for now.
