### ISSUE TITLE
Converting let to var

### ISSUE THREAD

**Issue by andrembpontes** [babel/babel#5387]
Babel is converting 'let' to 'var' in a wrong way. You can try this example in Chrome and see a correct behavior according with JS specification. If you run the result of babel transpilation you will get an erroneous behavior, as described bellow.

### Input Code

```js
var arr = [];

for(let i = 0; i < 5; i++){
  let a = a || { ex: 0 };
  
  a.ex = i;
}

console.log(arr);
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
empty file
```

### Expected Behavior

output: 
```js
[{ex: 0}, {ex: 1}, {ex: 2}, {ex: 3}, {ex: 4}]
```
or
```
Error: 'a' not declared
```

### Current Behavior

output: 
```js
[{ex: 4}, {ex: 4}, {ex: 4}, {ex: 4}, {ex: 4}]
```

| software         | version
| ---------------- | -------
| Babel            |  6.23.0 (babel-core 6.23.1)
| node             |  v7.3.0
| npm              |  3.10.10
| Operating System |  ArchLinux (a functional one :p)

**Comment by hzoo** [comment]
Are you sure your example code is correct? You aren't doing anything to arr in the code and then console.log it so it's just the empty array.

**Comment by loganfsmyth** [comment]
You can try enabling `tdz: true` on `transform-es2015-block-scoping` but Babel does not currently enable it by default because it had some bugs if I remember right. Not sure how easy they were to hit though.

**Comment by OlegLustenko** [comment]
```js
let a = a || { ex: 0 };
```
Seems that syntax is incorrect. `let a = a`. 
Variable 'a' is not defined in this scope, and can't access to upper scope

**Comment by xtuc** [comment]
Syntax seems invalid, I'm not able to run it on Chrome 56.0.2924.87.

```
Uncaught ReferenceError: a is not defined
    at <anonymous>:4:11
```

**Comment by aaronang** [comment]
Closing this issue due to long period of inactivity. If this issue remains troublesome, please provide an example repository that is able to reproduce the problem, or join our [Slack channel](https://slack.babeljs.io) for faster communication.
