### ISSUE TITLE
[...new Set([1,2,3])] returns [Set(1,2,3)] instead of [1,2,3]

### ISSUE THREAD

**Issue by vlad** [babel/babel#5388]
### Input Code

```js
[...new Set([1,2,3])];
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
        "presets": [["es2015", {"loose": true}]],
        "plugins": [
                "transform-async-to-generator",
                "transform-object-rest-spread",
                "syntax-flow",
                "transform-flow-strip-types"
        ]
}
```

### Expected Behavior

expecting to return [1,2,3] as in Chrome

### Current Behavior

[...new Set([1,2,3])] returns [Set(1,2,3)]
however, Array.from(new Set([1,2,3])) returns [1,2,3] as expected

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22
| babelify         | 7.3.0
| node             | 6.9.4
| npm              | 
| Operating System |

**Comment by hzoo** [comment]
It's because you are using loose mode, if you want Babel to be spec compliant you'll need to turn it off

**Comment by abhinavsingi** [comment]
Confirming here that removing loose option fixes the issue
