### ISSUE TITLE
babel-plugin-transform-runtime will not transform js in node_modules

### ISSUE THREAD

**Issue by yangmingshan** [babel/babel#5397]
### Babel Configuration
```js
{
  "presets": [
    ["latest", {
      "es2015": { "modules": false }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["latest", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
```

### Expected Behavior
transform-runtime will transform js in node_modules, for example, Promise in [axios](https://github.com/mzabriskie/axios)

### Current Behavior
It will not transform js in node_modules

### Context
I use axios for http requests, it depends on Promise. If I don't import Promise polyfill, only use babel-plugin-transform-runtime, it won't work in some devices which not support Promise. Is this intentional? If it is, why?

### Your Environment
| software         | version
| ---------------- | -------
| babel-core            |  6.23.1
| babel-plugin-transform-runtime            |  6.23.0
| node             | 7.6.0
| npm              | 4.1.2
| Operating System | macOS Sierra 10.12.3

**Comment by hzoo** [comment]
Babel only compiles what you tell it to. It includes node_modules by default since most libraries in node_modules are already ES5 so that would be slower than necessary. You'd include to include it in your way of telling babel to compile (cli/loader) or to use a polyfill.

**Comment by yangmingshan** [comment]
Thanks for your reply.
