### ISSUE TITLE
Why don't convert the third and later arguments of React.createElement to an array

### ISSUE THREAD

**Issue by NE-SmallTown** [babel/babel#5403]
I notice that the [official doc of createElement](https://facebook.github.io/react/docs/react-api.html#createelement):

```
React.createElement(
  type,
  [props],
  [...children]
)
```

The third argument should be an array.But I know we can pass something like `React.createElement('div', null, 'zzz', 'qqq');`,it does works.

But I check the src code of react when I debug:

![](http://i1.piimg.com/567571/f835a9a48907ca8e.png)

![](http://p1.bpimg.com/567571/c1a935464d7e2954.png)

![](http://p1.bqimg.com/567571/5a4bc245cdf17480.png)

And check the babel convert:

```
return (
    <div>
      zzz
      {}
      qqq
    </div>
 );
```

will convert to:

```
React.createElement(
   "div",
   null,
   "zzz",
   "qqq"
);
```

So it will cause react to convert the third and later argument of React.createElement to an array every time the `render` was called.**So I want to know why not babel converts it to:**

```
React.createElement(
   "div",
   null,
   ["zzz","qqq"]
);
```

Thanks.

**Comment by loganfsmyth** [comment]
It is possible earlier versions of React did not allow an array there, I vaguely remember something about that, but I'm not totally sure.

Another reason I could see it being is done that way is because it is easier to convert the elements during a standard traversal, e.g.

```
var component = <div><div></div><div></div></div>
```
to
```
var component = React.createElement(
  'div',
  null,
  <div></div>,
  <div></div>
);
```
to
```
var component = React.createElement(
  'div',
  null,
  React.createElement('div', null),
  <div></div>
);
```
to
```
var component = React.createElement(
  'div',
  null,
   React.createElement('div', null),
   React.createElement('div', null)
);
```

**Comment by NE-SmallTown** [comment]
@loganfsmyth Thanks for your reply,is there any way to ensure the reason?

**Comment by loganfsmyth** [comment]
I think someone who knows React better than I do would have to chime in.

Is there a specific problem you are facing because of this?

**Comment by NE-SmallTown** [comment]
@loganfsmyth Thanks.I will ask the member of react

> Is there a specific problem you are facing because of this?

No,I just want know.
