### ISSUE TITLE
Add option to copy-without-compilation in babel-cli

### ISSUE THREAD

**Issue by pronebird** [babel/babel#5404]
Some of scripts such as service workers throw "require() is not defined" when babel injects code in it. Therefore it would be great if some of javascripts could be left untouched but copied over. `ignore` option does not cut it.

Running babel with:

```
$ babel app/ --copy-files --out-dir build --source-maps true --watch
```

1. I tried to drop .js extension from service worker but then browser cannot load it because it's missing some mime-type information.

2. `--copy-files` does not work with `--ignore`, files are not being copied over.

**Comment by xtuc** [comment]
I think we could ignore your service worker file and copy it manually (with `cp`).

**Comment by hzoo** [comment]
This should be fixed in Babel 7 via https://github.com/babel/babel/pull/5487

> In babel-cli, --copy-files will now copy files that were ignored, where before it copied all non-compiled files, and skipped ignored files. Should be more what users expected anyway.

Can test with babel-cli@v7.0.0-alpha.3

**Comment by pronebird** [comment]
Works very well with `alpha.3`! 🎉

**Comment by nicolo-ribaudo** [comment]
@pronebird Note that you can aready use `beta.34`!

**Comment by pronebird** [comment]
@nicolo-ribaudo it's not on NPM

**Comment by nicolo-ribaudo** [comment]
We moved to scoped packages. Now they are `@babel/core`, `@babel/cli`, `@babel/preset-env`...

**Comment by JeffML** [comment]
What do I do if I want to ignore node-modules, but not have it copied?

**Comment by carkod** [comment]
@JeffML Move`--copy-files` before `--ignore`.
https://github.com/babel/babel/issues/6226

**Comment by pronebird** [comment]
@JeffML I may be wrong but I think if you move the `--ignore` call before `--copy-files` then it probably would completely ignore the folder and wouldn't copy it.
