### ISSUE TITLE
Can you register passing the module name?

### ISSUE THREAD

**Issue by janthonyeconomist** [babel/babel#5414]
I would like to concat my JS files into a single file; however, when you create your `System.register()` call, you don't pass the module name as the first param.  I'm a little confused because your code looks like it defines it:
```js
SYSTEM_REGISTER(MODULE_NAME, [SOURCES], function (EXPORT_IDENTIFIER, CONTEXT_IDENTIFIER) {
```
However, when everything is compiled down, there is no module name.  Am I missing something?  Am I supposed to set some kind of plugin option for you to output those?

**Comment by loganfsmyth** [comment]
Generally SystemJS already knows the name because it is responsible for loading the files. If you wanted a single file I believe you'd use https://github.com/systemjs/builder

**Comment by janthonyeconomist** [comment]
Ah.  I see if i just add `"moduleIds":  true,` do my babel config, it will add the module name.  That is all I needed.
