### ISSUE TITLE
Use babel-plugin into specific file via .babelrc?

### ISSUE THREAD

**Issue by rohmanhm** [babel/babel#5420]
I have lot of `.js` code in my project, but I want to use maybe `babel-plugin-add-module-exports` to my `main.js` file without affect to all `.js` files I have. How can I do that?

**Comment by xtuc** [comment]
Please take a look at our CLI documentation: [here](https://babeljs.io/docs/usage/cli/).
I would run a separate command against the `main.js` file with that plugin.

**Comment by rohmanhm** [comment]
but how about using it via `.babelrc` @xtuc 
I read the docs but can't figure out how to used it via `.babelrc`

**Comment by xtuc** [comment]
Ok, you can use the same option from the `.babelrc`: [see documentation](https://babeljs.io/docs/usage/babelrc/).

Do you already have a babelrc? Note that ignore will be applied to other plugins/presets.

**Comment by rohmanhm** [comment]
I have already read `.babelrc` docs from [here](https://babeljs.io/docs/usage/babelrc/), but still I can't found any documentation about implementing babel-plugin into specific file.

**Comment by xtuc** [comment]
Once you have your `.babelrc` setup we can use the Babel CLI.
Like:

```sh
babel FILE.js > OUT.js
```

Are you using Babel with Webpack, grunt or an alternative bundling tool?

**Comment by rohmanhm** [comment]
I'm using babel with webpack, I have problem with my `main.js` file. When I run without that plugin it's throw an error. But when I use it, It works. But affect to other `.js` files I have and make it throw new error. In my case I need use babel-plugin to just one file without affect to other file.

**Comment by loganfsmyth** [comment]
I _think_ what you're describing is something that we don't currently support. Are you thinking of something like:

```
{
  presets: ['es2015'],
  files: {
    "./main.js": {
      plugins: ['add-module-exports'],
    },
  }
}
```
so `es2015` and `add-module-exports` would run on `main.js` and all other files would only get `es2015`?

**Comment by rohmanhm** [comment]
@loganfsmyth yes, you're right 👍🏼

**Comment by xtuc** [comment]
As a workarround you could use this configuration in Wepack:
```js
[
  {
    test: /main.js$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
    options: {
      plugins: [
        'add-module-exports'
      ]
    }
  },
  {
    test: /\.js$/,
    exclude: /node_modules|main.js/,
    loader: 'babel-loader',
    options: {}
  },
]
```

(I didn't test that)

**Comment by rohmanhm** [comment]
@xtuc I tried but didn't work. 

```javascript
{
    test: /\.js$/,
    exclude: /node_modules|main.js/,
    loader: 'babel-loader',
    options: {}
  },
```
maybe overwrite
```javascript
{
    test: /main.js$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
    options: {
      plugins: [
        'add-module-exports'
      ]
    }
  },
```
since `main.js` still using `.js` extensions

**Comment by xtuc** [comment]
Yes I tried to exclude the `main.js` from regular loader. But I think you got the idea.

Do you mind if I close the issue since it is more a bundle issue? Feel free to reopen if needed.

**Comment by loganfsmyth** [comment]
I'd also be fine if we want to make this `[Feature Request] Configure based on file globs` and leave it open.

**Comment by xtuc** [comment]
@loganfsmyth I wanted to create a new issue for the feature request with a more explaining description.

**Comment by loganfsmyth** [comment]
That works!

**Comment by xtuc** [comment]
Closing this. I opened an issue with the feature request #5451.
