### ISSUE TITLE
 No compatible version found  babel-helper-function-name@^6.23.0  when installed babel-preset-stage-2

### ISSUE THREAD

**Issue by juan-urtazun** [babel/babel#5423]
Hi, when installed babel-preset-stage-2  get a No compatible version found  babel-helper-function-name@^6.23.0 specified as dependency of babel-plugin-transform-class-properties 

console output:
npm i --save-dev babel-preset-stage-2
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-helper-function-name@^6.23.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.0.0, 6.0.2, 6.0.14, 6.0.15, 6.1.5, 6.1.6, 6.1.7, 6.1.8, 6.1.9, 6.1.10, 6.1.12, 6.1.13, 6.1.16, 6.1.17, 6.1.18, 6.2.0, 6.2.4, 6.3.13, 6.3.15, 6.4.0, 6.5.0, 6.5.0-1, 6.6.0, 6.8.0, 6.18.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'babel-plugin-transform-class-properties'

Thanks.

**Comment by hzoo** [comment]
hey @juan-urtazun, can you try `rm -rf node_modules && npm install` again?

It's definetely published already: babel-helper-function-name

https://unpkg.com/babel-helper-function-name@6.23.0/
https://www.npmjs.com/package/babel-helper-function-name
https://registry.npmjs.org/babel-helper-function-name

**Comment by juan-urtazun** [comment]
Thanks!, thats work :)
