### ISSUE TITLE
Error thrown when using Sinon

### ISSUE THREAD

**Issue by jlecomte** [babel/babel#5426]
### Input Code

index.js:
```js
require('babel-register')();
require('./test.js');
```

test.js:
```js
var sinon = require('sinon');
sinon.stub(Math, 'random');
```

Command:

```
node index.js
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["es2015"]
}
```

### Expected Behavior

The output should be empty and node should exit cleanly.

### Current Behavior

An error is thrown:

```
/path/to/my/app/node_modules/sinon/lib/sinon/util/core.js:154
            method.stackTrace = (new Error("Stack Trace for original")).stack;
                                                                       ^
TypeError: Cannot read property 'generatedLine' of undefined
    at compareByGeneratedPositionsDeflated (/path/to/my/app/node_modules/source-map/lib/util.js:344:46)
    at doQuickSort (/path/to/my/app/node_modules/source-map/lib/quick-sort.js:88:11)
    at exports.quickSort (/path/to/my/app/node_modules/source-map/lib/quick-sort.js:113:3)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/path/to/my/app/node_modules/source-map/lib/source-map-consumer.js:519:5)
    at SourceMapConsumer.get (/path/to/my/app/node_modules/source-map/lib/source-map-consumer.js:68:12)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/path/to/my/app/node_modules/source-map/lib/source-map-consumer.js:606:11)
    at mapSourcePosition (/path/to/my/app/node_modules/source-map-support/source-map-support.js:196:42)
    at wrapCallSite (/path/to/my/app/node_modules/source-map-support/source-map-support.js:339:20)
    at /path/to/my/app/node_modules/source-map-support/source-map-support.js:374:26
    at Array.map (native)
```

### Possible Solution

By downgrading the `source-map` module to `0.4.2`, everything works. However, `source-map@0.4.3` onward shows the problem described here. I could not figure out what, in that version, causes this behavior.

Another weird thing: If I add the following line:

```js
new Error().stack;
```

right before [this line](https://github.com/sinonjs/sinon/blob/v1.17.7/lib/sinon/util/core.js#L136) in the sinon code, it "fixes" the problem. Very strange indeed!

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.0
| babel-preset-es2015 | 6.22.0
| node             | 6.9.1
| npm              | 3.10.8
| Operating System | Mac OS X
| Sinon            | 1.17.7 / 2.0.0-pre6

**Comment by loganfsmyth** [comment]
This appears to be because `source-map-support` uses `Math.random`, and because you are mocking it out, it is returning `undefined` when the sourcemap-based stack trace is generated.

It doesn't look like there is anything Babel could do for this. You could file this with `source-map-support` where they could grab a reference to the global before you mock it.

Tough one.

**Comment by jlecomte** [comment]
Thank you for the quick turnaround, @loganfsmyth ! Will do.

**Comment by loganfsmyth** [comment]
Yeah, unfortunately this seems like an argument against mocking globals honestly. There could be any number of things happening in the background when you mock. 

Another possible approach might be for Sinon to extract the stack data lazily, but yeah it's all kind of gross. It seems terrible to expose `source-map-support` to essentially use no global variables and use no npm modules that use no globals.

**Comment by loganfsmyth** [comment]
In this particular instance the `Math.random` that was failing is in `source-map`: https://github.com/mozilla/source-map/blob/master/lib/quick-sort.js#L43 so there is essentially nothing the maintainers of `source-map-support` could do about it either really, unless they wanted to detect that you mocked the function, unmock it while calling `source-map`, and then put the mock back again.

**Comment by fatso83** [comment]
> there is essentially nothing the maintainers of source-map-support could do about it either really

@loganfsmyth I might be missing a key technical aspect, but couldn't they simply maintain a reference to the globals on module startup? that's what most other libraries do (lodash, pinkyswear and underscore springs to mind) to avoid other libs interfering with them.

As in 
```javascript
const MyMath = global.Math;

function randomIntInRange(low, high) {
  return MyMath.round(low + (MyMath.random() * (high - low)));
}
```

Or is the problem that by the time the `source-map` module is invoked the Math global has already been modified? I don't have any insight into the internals of how the lib is used.

**Comment by loganfsmyth** [comment]
`source-map-support` is loading `source-map`, so either

1. `source-map` would have to store a reference to `Math.random` to harden its implementation against global mutation
2. `source-map-support` would have to store the reference, and then essentially do

    ```
    const mockRange = Math.range;
    Math.range = originalRange;
    try {
      // call all the stuff in `source-map`
    } finally {
      Math.range = mockRange;
    }
    ```

So either `source-map-support` would have to make assumptions about the inner works of `source-map`, which would be terrible, or `source-map` needs to be written to never use globals, which is also not really its responsibility.

No an obvious right fix/

**Comment by yanivefraim** [comment]
@loganfsmyth - so I understand there's no solution / workaround for that? (I want to stub `Math.random` and I'm having the exact same error...
