### ISSUE TITLE
Babel CLI fails to find presets when compiling files outside the project directory

### ISSUE THREAD

**Issue by Feuermurmel** [babel/babel#5434]
I'm trying to run `babel` on a JSX file outside the project root (this happens in unit test when using a temporary directory under `/private/tmp`). It seems that babel fails to find presets installed into the same `node_modules` directory as `babel-cli`:

```
michi ~/Documents$ mkdir babel-preset-issue
michi ~/Documents$ cd babel-preset-issue/
michi ~/Documents/babel-preset-issue$ npm install babel-cli babel-preset-es2015
[...]
michi ~/Documents/babel-preset-issue$ echo 'a = 123;' > ../foo.jsx
michi ~/Documents/babel-preset-issue$ node_modules/.bin/babel --presets=es2015 ../foo.jsx
Error: Couldn't find preset "es2015" relative to directory ".."
    at /Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/michi/Documents/babel-preset-issue/node_modules/babel-cli/lib/babel/util.js:50:22)
```

I've tested this with Babel 6.23.0 (babel-core 6.23.1) on OS X 10.11.6.

**Comment by aaronang** [comment]
For support questions I would highly recommend you to join our [Slack channel](https://slack.babeljs.io/).

It is not that `babel-cli` cannot find `babel-preset-es2015`; if you move `foo.jsx` to the project root, then it will work. To be honest, I think it is bad practice to create files during tests outside the project directory. Therefore, I would suggest you to create a `temp/` directory in the project directory and remove it once all tests have been executed. This is also how test fixtures in Babel are done.

**Comment by aaronang** [comment]
For support questions, I highly recommend you to join our [Slack channel](https://slack.babeljs.io) for faster communication.

I am not sure if this is a bug. However, a workaround is to create a `temp` directory in your project directory, and delete it after your tests. That's also how test fixtures in Babel are done.

Something unrelated to this issue; we highly recommend you to use `babel-preset-env`.

**Comment by aaronang** [comment]
I have investigated this issue a bit more. In https://github.com/babel/babel/blob/7.0/packages/babel-core/src/helpers/resolve.js we call `resolve` where `..` is bound `relative`. Then, `resolve.sync` is unable to resolve the given location `es2015` (and its alternative possible preset names).

**Comment by Feuermurmel** [comment]
@aaronang Thank you for your analysis. I'm not sure why I did not mention the version of babel I'm using, I've updated the description. I've already implemented a slightly different workaround: I'm just piping the file into babel for the moment. Seeing that this is considered a bug and not an oversight on my part is all I wanted.

**Comment by xtuc** [comment]
Would be great to be able to run the command like: `chdir=. node_modules/.bin/babel --presets=es2015 ../foo.jsx`.

This is also easily implementable in Babel.

**Comment by aaronang** [comment]
I was thinking for Babel 7, it should actually be able to use [`process.cwd()` which is the default](https://github.com/babel/babel/blob/7.0/packages/babel-core/src/helpers/resolve.js). We could basically make use of this default value when the normalized path to a file (`./../test/../foo.js` equals `./../foo.js`) is outside the project directory.

**Comment by loganfsmyth** [comment]
Having looked option processing a lot recently, there are definitely some changes we could think about to make this easier. Tempted to do it and add an option to revert back to the current behavior if people rely on it.

Currently, assuming I've got it right in my head, we look up config in a few ways:

If you pass an explicit filename:

1. Plugins explicitly passed resolve relative to the file being processed
2. Search for a .babelrc relative to the file, and find plugins in config relative to .babelrc

No filename:

1. Plugins explicitly passed resolve relative to CWD
2. Don't search for a .babelrc at all

Thinking at the moment that it would make more sense as

1. Plugins explicitly passed resolve relative to the current working directory
2. Search for a .babelrc relative to the file (or working directory if no file), and find plugins in config relative to .babelrc

This change means:

1. Plugins explicitly passed to Babel will work consistently, even if the file passed to Babel is somewhere else entirely
2. If you pass no filename, you'll still get the local .babelrc config, which means you can pipe things into Babel using the local config

**Comment by sethbergman** [comment]
I wondering if this would have anything to do with it?
https://github.com/babel/babel/pull/5449

**Comment by aaronang** [comment]
@sethbergman I don't see how this is related to the pull request you mentioned?

**Comment by loganfsmyth** [comment]
This issue should be resolved in https://github.com/babel/babel/pull/5466 for 7.x
