### ISSUE TITLE
Object keys are converted to lower case { A: 1 } becomes { a: 1 }

### ISSUE THREAD

**Issue by funkjunky** [babel/babel#5435]
{ A: 1 } becomes { a: 1 }, which is strange and annoying to me.

### Expected Behavior
maintain the case

### Current Behavior
converts keys to lower case

### Context
I don't want to have to wrap my keys in quotes

### Your Environment
react, es 2015, stage-0

**Comment by loganfsmyth** [comment]
That is not the current behavior on https://babeljs.io/repl/#?presets=es2015%2Creact%2Cstage-0&code=var%20foo%20%3D%20%7B%20A%3A%201%20%7D so we'd need a reproducible case.

**Comment by funkjunky** [comment]
ok it's working now, sorry. Perhaps webpack didn't update or something... Even though I never had lower case keys... doesn't matter. Sorry about this.

"try resetting the router" kind of instance.
