### ISSUE TITLE
nested plugin throwing error despite being ignored

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel#5441]
```
Error: Plugin 0 specified in "/project/node_modules/in-view/package.json" provided an invalid property of "__wrapped__" while parsing file: /project/node_modules/in-view/dist/in-view.min.js
```

I am using the `ignore` option:
```js
{ ignore: './node_modules/in-view/**/*' }
```
```js
{ ignore: require.resolve('in-view') }
```

`ignore` does not appear to be overriding the babel plugins listed in the package.json for "in-view".

**Edit**: [babelify#213](https://github.com/babel/babelify/issues/213) seems to be related.

**Comment by aaronang** [comment]
@stevenvachon Could you provide an example repository that reproduces your problem?

**Comment by stevenvachon** [comment]
@aaronang https://github.com/stevenvachon/babel-issue5441

**Comment by aaronang** [comment]
@stevenvachon Do you need `global: true`? Browserify ignores everything in `node_modules` by default.

By the way, come join our [Slack channel](https://slack.babeljs.io) for faster communication :)

**Comment by stevenvachon** [comment]
Yes, I import other internal dependencies within node_modules that have ES2015 code.

**Comment by stevenvachon** [comment]
@aaronang IRC would be much better

**Comment by stevenvachon** [comment]
@loganfsmyth Have you done anything with this at all in your work in "rewriting `ignore`"?

**Comment by loganfsmyth** [comment]
Hmm, this is a tough one in Babel 6.x. Currently we load all the plugins before checking `ignore` which means that for cases like this ignore is executed too late, and the missing plugin causes the error you are seeing. 

I'm changing the application order of `ignore` in 7.x so this should work as expected in `7.x`.

In 6.x, unfortunately you don't have tons of options. The simplest would be to actually install `babel-plugin-lodash`, which is [what in-view uses](https://github.com/camwiegert/in-view/blob/master/package.json#L31). Unfortunately there is always the possibility that a change to in-view would break your build.

You could also consider a wrapper around `babelify` to put things in your control, e.g.

```
const stream = require('stream');
const babelify = require('babelify');

const babelTransform = babelify.configure({
  presets:["es2015"]
});

// ...

// pass your own wrapper transform to Browserify.
.transform(function(filename, opts) {
  if (/\/node_modules\/in-view\/.test(filename)) return new stream.PassThrough();

  return babelTransform(filename, opts);
}, { global:true })
```

not pretty, but probably safer.

**Comment by stevenvachon** [comment]
Thanks! That works.

Minor corrections (and changes for quick replacement when 7.x ls released):
```js
.transform( function(filename, opts) {
  if (require.resolve("in-view") === filename) {
    return new (require("stream").PassThrough)();
  }
   return require("babelify").configure(opts)(filename);
}, { global:true, presets:["es2015"] })
```

**Comment by loganfsmyth** [comment]
Ah yeah, for some reason I was thinking that wouldn't work, but I'm totally wrong

You could even skip the `.configure` with

    return require("babelify")(filename, opts);

I think.

Keep in mind that explicitly checking `in-view`'s filename like that could fail if they refactor the module into multiple files or something though.

**Comment by stevenvachon** [comment]
That's true, but very unlikely, I'd think, because the file has already been browserified. If they were to split the main file out to multiple files, it'd probably wouldn't be a bundle. A regex/glob might be best anyway, but this is temporary in my project.
