### ISSUE TITLE
Missing variable name

### ISSUE THREAD

**Issue by blade254353074** [babel/babel#5443]
### Input Code

```js
import { message } from 'antd'

class App {
  constructor () {
    axios.interceptors.response.use(
      res => {
        const { code, message } = res.data
        if (code !== 2000) {
          const err = new Error(message)
          err.response = res
          throw new Error(message)
        }
        return res
      },
      err => Promise.reject(err)
    )
  }
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```JSON
{
  "presets": [
    ["env", {
      "targets": { "chrome": 52 },
      "modules": false,
      "loose": true
    }],
    "stage-2",
    "react"
  ],
  "plugins": [
    "transform-runtime",
    ["import", { "libraryName": "antd", "style": true }],
    "transform-decorators-legacy"
  ]
}
```

### Expected Behavior

`const err = new Error(message)` execute successfully.

### Current Behavior

BUT IT WILL THROW ERROR: `ReferenceError: message is not defined`

Because of the code was transformed to:

![image](https://cloud.githubusercontent.com/assets/9346008/23788615/40689468-05b2-11e7-98a8-d05c2797dfe8.png)

And `import { message } from 'antd'` was transformed to:

`/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_antd_lib_message___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2_antd_lib_message__);`

**So it will cause ReferenceError**

### My Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.1
| node             | 7.7.1
| npm              | 4.1.2
| Operating System | macOS 10.11.6

**Comment by aaronang** [comment]
@blade254353074 Could you provide an example repository that reproduces this problem? This will make it easier for us to help you out. In addition, for faster communication you could join our [Slack channel](https://slack.babeljs.io).

Based on what you provided, what is returned by `res.data`?

**Comment by existentialism** [comment]
It looks like an issue with `babel-plugin-import` and it not properly handling the fact that you have a named import and a destructure with the same name?

You probably want to just rename `message` from `res.data` anyway.

This works:

```jsx
import { message } from 'antd'

const info = function () {
  message.info('This is a normal message');
};

class App {
  constructor () {
    axios.interceptors.response.use(
      res => {
        const { code, message: resMessage } = res.data
        if (code !== 2000) {
          const err = new Error(resMessage)
          err.response = res
          throw new Error(resMessage)
        }
        return res
      },
      err => Promise.reject(err)
    )
  }

  render() {
      return <button onClick={info}>test</button>;
  }
}
```

Results in:

```jsx
import _Promise from 'babel-runtime/core-js/promise';
import { style as _style } from 'antd/lib/message/style';
import _default from 'antd/lib/message';


const info = function () {
  _default.info('This is a normal message');
};

let App = class App {
  constructor() {
    axios.interceptors.response.use(res => {
      const { code, message: resMessage } = res.data;
      if (code !== 2000) {
        const err = new Error(resMessage);
        err.response = res;
        throw new Error(resMessage);
      }
      return res;
    }, err => _Promise.reject(err));
  }

  render() {
    return React.createElement(
      'button',
      { onClick: info },
      'test'
    );
  }
};
```

**Comment by blade254353074** [comment]
Thank you guys @existentialism @aaronang 
I removed `["import", { "libraryName": "antd", "style": true }]`, but the error still happen.
It has nothing to do with `babel-plugin-import`.

---

When I comment the `import { message } from 'antd'`,
the transformed code will turn to normal.

```js
// import { message } from 'antd'

class App {
  constructor () {
    axios.interceptors.response.use(
      res => {
        const { code, message } = res.data
        if (code !== 2000) {
          const err = new Error(message)
          err.response = res
          throw new Error(message)
        }
        return res
      },
      err => Promise.reject(err)
    )
  }
}
```

![image](https://cloud.githubusercontent.com/assets/9346008/23820403/9196e880-0652-11e7-863a-6febd70ac251.png)


Sorry, I'm a little busy right now, can't provide an example repository.

**Comment by existentialism** [comment]
You're saying that without `babel-plugin-import` the code is the same? I'm not seeing that:

With:

```jsx
```

**Comment by existentialism** [comment]
You're saying without `babel-plugin-import` the transformed code is the same? I'm not seeing that...

With:

```jsx
import _Promise from 'babel-runtime/core-js/promise';
import { style as _style } from 'antd/lib/message/style';
import _default from 'antd/lib/message';
let App = class App {
  constructor() {
    axios.interceptors.response.use(res => {
      const { code, message: _default } = res.data;
      if (code !== 2000) {
        const err = new Error(message);
        err.response = res;
        throw new Error(message);
      }
      return res;
    }, err => _Promise.reject(err));
  }
};
```

Without:

```jsx
import { message } from 'antd'

class App {
  constructor () {
    axios.interceptors.response.use(
      res => {
        const { code, message } = res.data
        if (code !== 2000) {
          const err = new Error(message)
          err.response = res
          throw new Error(message)
        }
        return res
      },
      err => Promise.reject(err)
    )
  }
}
```

**Comment by aaronang** [comment]
Closing this issue as it has been inactive. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

>If you just have an usage issue or want help, I would recommend checking out our [Slack community](https://slack.babeljs.io/) or StackOverflow.

**Comment by blade254353074** [comment]
The issue is finally closed, I have been thinking about it...
