### ISSUE TITLE
Henry Zhu on Request For Commits!

### ISSUE THREAD

**Issue by adamstac** [babel/babel#5445]
Howdy, I'm Adam from Changelog.com.

We're kicking off season 2 of our podcast Request For Commits hosted by @nayafia and @mikeal and we'd like to have you on as guest to talk about your experiences maintaining/sustaining Babel.

If you haven't heard of the show (yet), Request For Commits is a podcast that explores different perspectives in open source sustainability. It's about the human side of code.

Listen to the show here https://changelog.com/rfc

Feel free to send an email to editors@changelog.com to coordinate.

Looking forward to talking to you. Thanks!

Adam, EIC

(pls forgive me for posting this as an issue ~ I couldn't find an email address to email)

**Comment by hzoo** [comment]
I wanted to have some fun with this issue, but sounds awesome! Thanks for the opportunity
