### ISSUE TITLE
getters within object initializers not transformed

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel#5446]
```js
const a = ['a'];
const obj = {
  a,
  get b(){ return 1 }
};
```

*should* transform to:
```js
var a = ['test'];
var obj = { a:a };
Object.defineProperty(obj, 'b', {
  get: function(){ return 1 }
});
```

but instead, merely produces:
```js
var a = ['a'];
var obj = {
  a:a,
  get b(){ return 1 }
}
```

Tried "es2015" and "es2017" presets.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Defining_a_getter_on_new_objects_in_object_initializers

**Comment by loganfsmyth** [comment]
That code is valid ES5, so it does not need to be transformed.

**Comment by stevenvachon** [comment]
Whoa! Awesome. Thanks.
