### ISSUE TITLE
Add [Symbol.iterator]() methods to NodeList, TouchList, etc.

### ISSUE THREAD

**Issue by kevinbarabash** [babel/babel#545]
I was reading this MDN page on for...of: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of and they mentioned that you could use it with stuff from the DOM like NodeList.  I tried it and it didn't work so I ended up polyfilling it with this code:
```
if (NodeList.prototype[Symbol.iterator] === undefined) {
    NodeList.prototype[Symbol.iterator] = function () {
        var i = 0;
        return {
            next: () => {
                return { done: i >= this.length, value: this.item(i++) };
            }
        }
    };
}
```
It actually works and lets do stuff like:
```
for (let { id } of document.querySelectorAll("div")) {
    console.log(`elem.id = ${id}`);
}
```
I'd like to create a pull request for this and the other DOM lists.  Where's a good place to put browser only polyfills?

**Comment by zloirock** [comment]
`core-js` adds only cross-platform features. You can simple add to your code
```javascript
NodeList.prototype[Symbol.iterator] = [][Symbol.iterator]
```

**Comment by kevinb7** [comment]
@zloirock I tried the code you posted and it works, but I don't know why.  What does ```[][Symbol.iterator]``` do?

Another question: There is/was a "browser-polyfill.js" file.  Would it be okay to add this code there so that everyone can use iterators with DOM lists out of the box?

**Comment by kevinb7** [comment]
After thinking about it I realized that ```[][Symbol.iterator]``` is equivalent to ```Array.prototype[Symbol.iterator]```.

**Comment by sebmck** [comment]
It's not the responsibility of 6to5 to polyfill this behaviour. This is better suited for [core-js](https://github.com/zloirock/core-js) that 6to5 uses.

**Comment by kevinb7** [comment]
@sebmck I guess that makes sense.  6to5 is just repackaging existing polyfills.  I'll create an issue with core-js and see what they say.

**Comment by kevinb7** [comment]
@zloirock I didn't realize you were the maintainer of core-js.  Is this polyfill something you'd be interested in as a optional include with core-js or should I start a separate project for stuff like this?

**Comment by fkling** [comment]
@kevinb7 
> What does `[][Symbol.iterator]` do?

It accesses the iterator method of an array. Maybe this is easer to understand:

```js
var arr = [];
NodeList.prototype[Symbol.iterator] = arr[Symbol.iterator];
// or
NodeList.prototype[Symbol.iterator] = Array.prototype[Symbol.iterator];
```

I assume (didn't look at the code), just like other array methods, this method is agnostic and works on values that are *array-like*.

**Comment by zloirock** [comment]
@kevinb7 As I wrote above, `core-js` adds only cross-platform features. You can add all of these iterators in 1 line of user code. Although as these iterators are directly related to the iterator array, I can change my position.

**Comment by gaearon** [comment]
@zloirock 

Just my two cents: I also assumed these would be provided by core-js. If you *do* decide to have them, please also include them in Nodish polyfill behind `typeof` checks since that's what Browserify/Webpack folks are using.

**Comment by zloirock** [comment]
Show me spec, I can't find it.

**Comment by kevinb7** [comment]
I found something in the whatwg DOM spec that mentions NodeLists having "iterable<Node>" as part of their interface in the IDL: https://dom.spec.whatwg.org/#nodelist.

**Comment by fkling** [comment]
Just to expand on the ["iterable" declaration](https://heycam.github.io/webidl/#idl-iterable): 

> **Note**
> In the ECMAScript language binding, an interface that is iterable will have “entries”, “keys”, “values” and [@@iterator](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-well-known-symbols) properties on its [interface prototype object](https://heycam.github.io/webidl/#dfn-interface-prototype-object).

**Comment by zloirock** [comment]
Ok, I will add `NodeList.prototype[Symbol.iterator]`, but currently only it - core-js is not DOM polyfill.

**Comment by zloirock** [comment]
Avaliable in 0.4.6.

**Comment by kevinb7** [comment]
Thanks!
