### ISSUE TITLE
[Feature Request] feature similar to ESLint "overrides" (config based on glob)

### ISSUE THREAD

**Issue by xtuc** [babel/babel#5451]
Following a discusion from #5420.

It would be usefull to provide an alternative configuration based on the path of the file being transpiled.

In the following example, only the `main.js` file would be using the `add-module-exports` plugin. The es2015 presets in used on all files.

```js
{
  presets: ['es2015'],
  files: {
    "./main.js": {
      plugins: ['add-module-exports'],
    },
  }
}
```

We should also be able to provide globs as path:

```js
{
  presets: ['es2015'],
  files: {
    "./*.js": {
      plugins: ['transform-remove-console'],
    },
  }
}
```

**Comment by perrin4869** [comment]
Any progress with this feature? Would be incredibly useful to have!

**Comment by Josema** [comment]
This feature would be amazing. Because it makes faster the building process and sometimes smaller bundles.
