### ISSUE TITLE
grunt-babel adds "Use Strict"; at the global level?

### ISSUE THREAD

**Issue by cssagogo** [babel/babel#5455]
Not sure if it's an issue with grunt-babel or babel itself, but "Use Strict" is getting added at the global level when applied.  Is there an option to disable it?

**Comment by loganfsmyth** [comment]
ES6 modules are always strict, and Babel assumes files passed through it are modules by default. When you configure your presets, like if you have `es2015`, you'll want to make your config

```
{
  sourceType: 'script',
  presets: [
    ['es2015', {modules: false}],
  ],
}
```

to disable ES6 module syntax and tell Babel to process the file as a script rather than a module.
