### ISSUE TITLE
Stage 2 preset docs missing documentation of dynamic import plugin inclusion

### ISSUE THREAD

**Issue by lourd** [babel/babel#5471]
The stage 2 preset includes the syntax-dynamic-import plugin (https://github.com/babel/babel/blob/master/packages/babel-preset-stage-2/package.json), but [the documentation](https://babeljs.io/docs/plugins/preset-stage-2/) does not mention it.

I'm also curious, when do the TC39 stage presets get updated? It appears that the [dynamic import proposal](https://github.com/tc39/proposal-dynamic-import) is at stage 3 now. What's the process for updating that in Babel?

**Comment by lourd** [comment]
I'd be happy to open a PR updating it, but I couldn't figure out how the top section of the docs are generated, i.e. `This preset includes the following plugins...`

**Comment by existentialism** [comment]
@lourd feel free to send an update to https://github.com/babel/babel.github.io/blob/master/docs/plugins/preset-stage-2.md

**Comment by lourd** [comment]
Nice, thanks for the pointer. Here's a PR https://github.com/babel/babel.github.io/pull/1197

**Comment by hzoo** [comment]
Moving to https://github.com/babel/babel.github.io/pull/1197
