### ISSUE TITLE
[7.0] Remove aliased helpers from babel-runtime

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5472]
`babel-runtime`'s built files currently contain several aliases that are unused as far as I can tell. I haven't done any checks on the history, so I'd be curious to see why they existed in the first place. We basically output:

```
helpers/
  someHelper.js
  some-helper.js
  _some-helper.js
```

where the last two just `module.exports = require('./someHelper')`.

---

- [ ] Comment below you are going to do this (for others to know): `"I'd like to work on this"`
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) (make sure you have yarn, and are on at least node 4)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] remember to run `make build` after a source code change or better just run `make watch` in another terminal window to auto run babel while you are developing

**Comment by JulianJason** [comment]
I'd like to work on this

**Comment by hzoo** [comment]
Closed in https://github.com/babel/babel/pull/5516
