### ISSUE TITLE
Static method cannot call another static method.

### ISSUE THREAD

**Issue by janzenz** [babel/babel#5478]
I was trying to call another static method from another static method using `this.constructor` or even just `this.` but it throws an error.
### Input Code
```js
class ChildComponent extends Component {
    static heavyCalculation() { console.log('Calculating') }

    static listenerFunc() { 
        console.log('Resize')
        this.heavyCalculation()
    }

    componentDidMount() {
        window.addEventListener('resize', this.constructor.listenerFunc, false)
    }

    componentWillUnmount() {
        window.removeEventListener('resize', this.constructor.listenerFunc, false)
    }

    render() {
        return <div>ChildComponent</div>
    }
}
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  presets: ['env', 'es2015', 'react']
}
```
```json
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "babel-cli": "^6.24.0",
    "babel-loader": "^6.4.1",
    "babel-preset-env": "^1.2.2",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.2"
  }
```

### Possible Solution
Possible solution is by using the class name itself
```js
class ChildComponent extends Component {
    static heavyCalculation() { console.log('Calculating') }

    static listenerFunc() { 
        console.log('Resize')
        ChildComponent.heavyCalculation() // This works
    }

    componentDidMount() {
        window.addEventListener('resize', this.constructor.listenerFunc, false)
    }

    componentWillUnmount() {
        window.removeEventListener('resize', this.constructor.listenerFunc, false)
    }

    render() {
        return <div>ChildComponent</div>
    }
}
```

### Context
I'm using static methods to implement my listener functions. The listener adds fine, however, when unmounting the component, the function doesn't seem to get removed, and still triggering my static method. I thought  `this.constructor.listenerFunc === this.constructor.listenerFunc` since it's a class method, but in my example it doesn't seem so. 

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.24.0
| node             | 6.10.0
| npm              | 3.10.10
| Operating System | OSX Sierra

**Comment by hzoo** [comment]
aside: You don't need to have both `'env', 'es2015'`, env covers everything.

**Comment by janzenz** [comment]
@hzoo Oh thanks for the info!

**Comment by loganfsmyth** [comment]
You need `this.constructor.listenerFunc.bind(this.constructor)` otherwise you're going to get the wrong `this`, just like any other function.
