### ISSUE TITLE
babel-register cannot use import

### ISSUE THREAD

**Issue by yoyeung** [babel/babel#5479]
### Input Code

```js
{
  "presets": ["latest"]
}

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
'use strict';

require('babel-register');

import AWS from 'aws-sdk';
```

Error:
Unexpected reserved word

am i missing somthing?

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.24
| node             | 7.60
| npm              | 4.1.2
| Operating System | Mac

**Comment by hzoo** [comment]
Yep just a small issue, @yoyeung. You can't use the syntax you are transpiling in the same file you are calling babel-register. So you would need to either use regular require, or require another file that uses import.

aside: I would switch out ['latest'] for ['env'] https://github.com/babel/babel-preset-env
