### ISSUE TITLE
Remove lodash dep from babel-helper-builder-react-jsx

### ISSUE THREAD

**Issue by segphault** [babel/babel#5482]
The babel-helper-builder-react-jsx package (https://www.npmjs.com/package/babel-helper-builder-react-jsx) takes a dependency on all of lodash, but doesn't appear to actually use lodash. At present, the lodash package accounts for about 38% of the total install size of the Babel React preset.

**Comment by hzoo** [comment]
Awesome, would you like to make a PR to remove it?

**Comment by segphault** [comment]
Sure, will do. Thanks!
