### ISSUE TITLE
Returned async fat-arrow function with argument destructuring gets the parent function's arguments

### ISSUE THREAD

**Issue by jetpacmonkey** [babel/babel#5485]
It seems like something's going wrong with a combination of canonical `arguments`, argument destructuring, and `async-to-generator`.

### Input Code

```js
// This one calls the inner function with the outer function's arguments
function breaks(fn) {
  return async (...args) => {
    return fn(...args);
  };
}

// This passes the arguments along as expected
function works(fn) {
  return async (...args) => {
    const dummy = args;
    return fn(...args);
  };
}
```

[REPL link](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=function%20test(fn)%20%7B%0A%20%20return%20async%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20return%20fn(...args)%3B%0A%20%20%7D%3B%0A%7D%0A%0Afunction%20test2(fn)%20%7B%0A%20%20return%20async%20(...args)%20%3D%3E%20%7B%0A%20%20%20%20const%20dummy%20%3D%20args%3B%0A%20%20%20%20return%20fn(...args)%3B%0A%20%20%7D%3B%0A%7D%0A%0Atest((a)%20%3D%3E%20(%7B%20data%3A%20%60_%24%7Ba%7D_%60%20%7D))('str').then(console.log.bind(console))%0Atest2((a)%20%3D%3E%20(%7B%20data%3A%20%60_%24%7Ba%7D_%60%20%7D))('str').then(console.log.bind(console)))

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "stage-2"]
}
```

### Expected Behavior

Both calls should log `{ data: "_str_" }` to the console

### Current Behavior

The first one, which doesn't access `args`, is logging

```javascript
{
  "data": `_function (a) {
  return { data: \'_\' + a + \'_\' };
}_`
}
```

### Possible Solution

It seems like something in `async-to-generator` is conflicting with... something else. Sorry, I'm not very familiar with babel's internals.

### Context

I was trying to write a wrapper function, which would work regardless of whether the inner function returned a promise or not. I noticed the inner function was getting the wrong arguments, so I added a `console.log(args)` in there to try and debug, and... all of the sudden everything worked as expected.

### Your Environment

Reproduced in the REPL, so I'm not sure how relevant this is, but here you go...

| software         | version
| ---------------- | -------
| Babel            |  6.22.0
| node             | 7.7.1
| npm              | 4.1.2
| Operating System | macOS 10.12.3

**Comment by existentialism** [comment]
Thanks for the issue @jetpacmonkey, we're actively tracking this issue in https://github.com/babel/babel/issues/4219 (and all the linked issues, including https://github.com/babel/babel/issues/5330 are related).

**Comment by jetpacmonkey** [comment]
Whoops, thanks! I blame Github's weak issue search for my oversight 😏

**Comment by hzoo** [comment]
All good, we really should of fixed this earlier 😄
