### ISSUE TITLE
【Question】Invalid number

### ISSUE THREAD

**Issue by Aladdin-ADD** [babel/babel#5490]
### Input Code

```js
var i = 00;
var j = 01;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  presets: ['es2015']
}
```

the output is `Invalid number`.
I know it is not a good practice, but it works in most browsers. 
Is this  intentional, or a bug? 

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.1
| node             | v6.9.4
| npm              | 
| Operating System |

**Comment by danez** [comment]
babel and its parser babylon are usually operating in strict mode and module-scope. In strict mode using number like this is not allowed and you should instead use `var j = 0o4567;` for octal numbers.

If your intention is that the example code is decimal numbers, then the code is wrong as they are actual octal numbers.

In future please use our slack or stackoverflow for support..
