### ISSUE TITLE
Env preset with targets ">5%, last 2 versions" throws an error @regeneratorRuntime is not defined"

### ISSUE THREAD

**Issue by budarin** [babel/babel#5500]
I use env preset in my react app

```
presets: [
        'react',
        ['env', {
            targets: {
                browsers: ['> 5%', 'last 2 versions'],
            },
            cacheDirectory: true
        }],
    ],
```
and I try to use such code:

```
function* doSomth() {
    ......
}
```
when I run transpiled code in IE11 it throws me the error:
**regeneratorRuntime is not defined**

why? babel in debug mode says that it includes regeneratorRuntime plugin, but there is no an effect!
Help me please

Webpack 2.2.1
Babel 6.24.0
Node 7.7.1
yarn 0.21.3
Windows

**Comment by hzoo** [comment]
regeneratorRuntime isn't included or is a plugin. `regeneratorRuntime` is a runtime meaning it needs to be in your source code at runtime. The way you can include this with preset-env is with using babel-polyfill, can also use the https://github.com/babel/babel-preset-env#usebuiltins option. Or include `regeneratorRuntime` directly: https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime.
