### ISSUE TITLE
Cannot change syntax per file extension 

### ISSUE THREAD

**Issue by sheerun** [babel/babel#5505]
Forgive me if it is possible, but I cannot find any documentation on it.

Here's what I want to do: Write a babel plugin that transcompiles `.css` files (but not only, in general any file other than .js) to es6 module, as so babel can track dependencies when this file is changes, and webpack can later tree shake it, and there's no inlining duplication.

> Q: Why babel plugin and not webpack loader? A: To support server-side rendering

To give an example, I want to transcompile following `style.css`:

```css
.foo {
  color: red;
}
```

to 

```js
export const foo = {
  color: 'red';
}
```

and then somewhere else do:

```js
import { foo } from 'foo.css';
```

I have also other use-cases for it, but all of them have following in common: **I don't want to inline these files** similarly to how for example [babel-plugin-inline-import](https://www.npmjs.com/package/babel-plugin-inline-import) works. I want to transcompile file to es6 module, or to put it differently, I want babel to use totally custom syntax per file extension (such syntax would be able to convert some raw like .css or .json into babel's ast). This way I could achieve following:

1. The same raw file can be re-used by different .js files (with inlining I get duplication)
2. Babel can track changes in raw file, and track it as dependency of any .js files that import it (with inlining the dependency link is lost, and changing raw file doesn't reload anything)
3. Webpack can additionally tree shake this dependency, if I decide to use it

From my current understanding babel uses the same syntax  for all files (it can be extended with plugins), but you cannot change it based on imported file extension.

Could you guide me how to write such plugin? How to change used syntax per-extension?

**Comment by sheerun** [comment]
To be completely clear: I don't want to replace transformer per-file, I just want to replace parser per-file. If you don't want to allow it, I'd ask for even less: allow for custom preprocessing step for syntax for per-extension (i.e. transform input file even before it's passed to syntax parser, a `string => string` function).

**Comment by rattrayalex** [comment]
Here's how I accomplish that in my plugin: 

https://github.com/lightscript/babel-plugin-lightscript/blob/master/src/index.js#L1001 changes the parser depending on filename

https://github.com/lightscript/babel-plugin-lightscript/blob/master/src/index.js#L670 activates/deactivates the visitor depending on filename

It's a bit messy, especially for cases when you don't have filenames (eg; source string coming from tests), but it works.

**Comment by sheerun** [comment]
@rattrayalex Awesome! Let me try this and report if it's enough

**Comment by sheerun** [comment]
@rattrayalex It seems `manipulateOptions` manipulates options globally, not per-file, isn't it?

**Comment by rattrayalex** [comment]
I'm not sure; since it has a file path I assume it's per file, but perhaps
the changes persist? I haven't looked. If so, perhaps an `else` case can
reset things?

**Comment by hzoo** [comment]
K closing then
