### ISSUE TITLE
Getting weird error - Use the `babel-core` package not `babel`.

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#5506]
Just wondering why I see this error:

```
Error: Use the `babel-core` package not `babel`.
    at Object.<anonymous> (/Users/alexamil/.suman/global/node_modules/babel-cli/index.js:1:69)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/lib/diagnostics/run-diagnostics.js:33:9
    at Array.forEach (native)
```

it's coming out of babel-cli

these are the only babel packages I am loading/requiring:

```
      'babel-cli': 'latest',
      'babel-core': 'latest',
      'babel-loader': 'latest',
      'babel-polyfill': 'latest',
      'babel-runtime': 'latest',
      'babel-register': 'latest',
      'babel-plugin-transform-runtime': 'latest',
      'babel-preset-es2015': 'latest',
      'babel-preset-es2016': 'latest',
      'babel-preset-react': 'latest',
      'babel-preset-stage-0': 'latest',
      'babel-preset-stage-1': 'latest',
      'babel-preset-stage-2': 'latest',
      'babel-preset-stage-3': 'latest',
```

seems like a weird error to me

**Comment by aaronang** [comment]
This error message is returned when you import `babel-cli`: https://github.com/babel/babel/blob/d33d02359474296402b1577ef53f20d94e9085c4/packages/babel-cli/index.js.

**Comment by ORESoftware** [comment]
@aaronang ok thanks, so I should not import `babel-cli` at all?

**Comment by aaronang** [comment]
@ORESoftware Nope, you should import `babel-core` instead as the error message says 😄

**Comment by ORESoftware** [comment]
Thanks, but it says use babel-core instead of babel.

It does not say "use babel-core instead of babel-cli"

Right?

**Comment by aaronang** [comment]
@ORESoftware Would you like to submit a pull request for this? 😄

**Comment by ORESoftware** [comment]
Sure, let me first verify that it works

**Comment by ORESoftware** [comment]
Is there some documentation that shows that babel-cli is deprecated in favor of babel-core?

**Comment by aaronang** [comment]
@ORESoftware I already made a PR for it. It is not deprecated, it is just not meant for use in a programmatic manner.

**Comment by ORESoftware** [comment]
You mean it's for internal use and not for developers to install directly?

**Comment by aaronang** [comment]
@ORESoftware It is meant for external use. In specific, the package enables developers to use the CLI: https://babeljs.io/docs/usage/cli/. So you do need it in `package.json` to be able to use CLI commands. However, you should not do something like `import * from 'babel-cli'` in your source code. That will result in the error you received.

**Comment by hzoo** [comment]
babel-cli was never intended to be used programmatically, `babel-cli` is just a CLI tool that wraps babel-core. If you want to use babel in your own code you'll want to use babel-core. The error message is just saying babel probably since it's a legacy message from when there was just the `babel` package and no one else has reported this "error message typo"
