### ISSUE TITLE
babel-runtime is 'unrequireable' - breaks require/require.resolve()

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#5509]
I opened this issue with Node.js

https://github.com/nodejs/node/issues/11928#issuecomment-287660448

I have a script that checks to make sure all modules are installed correctly in a particular directory. The problem is that babel-runtime module (and perhaps others in the babel ecosystem) are not requireable.

They do not have a main property on package.json and/or do not have an index.js file.

This breaks require and require.resolve()

I'd really like all babel modules (and every module in the node.js ecosystem) to at least be requireable even if it's a noop or even if an error is thrown when requiring.

At the very least, `require.resolve() `should work as expected.

**Comment by loganfsmyth** [comment]
The tough part is runtime just doesn't really need an index. Isn't throwing the right behavior in that case? It seems like you're using require.resolve for a case it wasn't intended for. This is one specific case, but any package could lack an index.

If you need to see if a module exists, why not implement that specific behavior? The behavior is well-defined afaik.

**Comment by ORESoftware** [comment]
I could could implement it myself, but the next person that calls require.resolve() on a babel ecosystem module and gets an unexpected error will face the same issue.

WRT to implementing it myself, I suppose I could just check for the existence of the package.json file.

However I think it would be a lot easier to not have to re-implement a specific require.resolve() function for modules that don't want to be modules. 

It would be nice if Babel modules could at least work with require.resolve().

**Comment by ORESoftware** [comment]
Here is what I think should happen:

require('babel-runtime') => throw an error
require.resolve('babel-runtime') => if the package exists in the right directory, should not throw

you can achieve the above by creating an index.js file and throwing an error in there.

**Comment by hzoo** [comment]
Thanks for the report and suggestions. So it's not that we aren't going to do it, but again I'm skeptical this is necessary? There are plenty of other npm modules that are also not requireable because they aren't meant to (and do not have an index.js file), especially any cli tool.

> but the next person that calls require.resolve() on a babel ecosystem module and gets an unexpected error will face the same issue.

I don't believe this has ever been a reported issue or heard of anything like this in slack, twitter, or slackoverflow for the last 2 years I've been involved with the project. This is probably the case because most people don't require babel in their code unless they are trying to make their own plugin or tool on top of Babel.

**Comment by hzoo** [comment]
Going to close, doesn't seem like anyone will hit this (and if they do we can reopen)

**Comment by ORESoftware** [comment]
sure np

**Comment by hkjpotato** [comment]
BABEL-RUNTIME, better be regarded as a set of utilities helpers function instead of as a module. Thats why you should cant simply use webpackDLL to bundle it!
