### ISSUE TITLE
Babel website don't support react

### ISSUE THREAD

**Issue by NE-SmallTown** [babel/babel#5513]
Recent months I have many times to test something at [babel website](https://babeljs.io/repl/),but today when I test something like before,the babel website doesn't work.

the error pic:

http://ogitl0zvo.bkt.clouddn.com/2017-03-122230.jpg

So I want to ask what happened?

**Comment by hzoo** [comment]
If you just have a question, please check our slack. We leave the issues for bug reports and feature requests. If you have an issue with the website check https://github.com/babel/babel.github.io. This repo is for the code

**Comment by hzoo** [comment]
@babel-bot move to babel/babel.github.io
