### ISSUE TITLE
babel-plugin-transform-export-extensions doesn't work on React Native

### ISSUE THREAD

**Issue by xareelee** [babel/babel#5514]
I followed [the instruction](https://babeljs.io/docs/plugins/transform-export-extensions/) to install and set up `babel-plugin-transform-export-extensions`.

The `export * from ...`  syntax should work after installing in a React Native project, but the syntax only exports `undefined`.

### Input Code

Try to load `index.js` which is just a bundle of components.

```js
import components from 'index.js';
console.log('components:', components);
```

This `index.js` works:

```js
import CodeView from './CodeView';
export default CodeView;    // export the CodeView
```

This `index.js` doesn't work:

```js
export * from './CodeView';  // export `undefined`
```

### Babel Configuration (.babelrc, package.json, cli command)

`package.json`:

```json
{
  "devDependencies": {
    "babel-plugin-transform-export-extensions": "^6.22.0",
  }
}
```

`.babelrc`:

```json
{
  "presets": ["react-native"],
  "plugins": ["transform-export-extensions"]
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             |  7.2.1
| npm              |  4.4.1
| yarn              | 0.21.3
| react-natvie | 0.42.0
| Operating System | macOS 10.12.3

**Comment by Kovensky** [comment]
`export * from` is not one of the extended syntaxes, it is part of ES2015. The export called `default` is also the one export that `export * from` specifically does _not_ reexport.

If you want to re-export the default export as a default export, then you can use `export { default } from`.

**Comment by xareelee** [comment]
@Kovensky Thanks for your reply.

How do I export multiple components with `export ... from ...` syntax per line per component? The following doesn't work:

```js
export { default } from './CodeView';
export { default } from './CompatButton';
```

**Comment by Kovensky** [comment]
In that case, you can use something like `export { default as CodeView } from './CodeView'`.

What the extended syntax should do for you is allow using `export CodeView from './CodeView'`, with the `CodeView` as a shorthand for `{ default as CodeView }` just like when `import`ing.

**Comment by hzoo** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave a comment requesting this issue be reopened if needed. Thanks! 🙂

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
