### ISSUE TITLE
babel-plugin-transform-decorators: Property is readonly if no value set

### ISSUE THREAD

**Issue by SPAHI4** [babel/babel#5519]
Original issue here https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/issues/57

It's still not solved on `7.0.0-alpha.1`

**Comment by hzoo** [comment]
We haven't announced Babel 7, it's still alpha, and the pr to move legacy into transform-decorators was simply porting the code over so no work has been done. So I didn't expect it to have solved any of the issues from the repo. I would just follow the issues there until we do a release and we can port that stuff over.
