### ISSUE TITLE
Plugin transform-flow-strip-types  does not remove :Iterator<T>

### ISSUE THREAD

**Issue by ea167** [babel/babel#5521]
`Iterator<K2>` is not stripped in the code below

### Input Code

```js
class MapOfMaps<K1,K2,V>
{
    ...

    innerKeys( key1:K1 ) :Iterator<K2> {
       ...
    }
    ...
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.1",
    "babel-plugin-transform-flow-strip-types": "^6.22.0"
}
```

**Comment by existentialism** [comment]
@ea167 what's your .babelrc / webpack loader config look like?

Seems to work via the repl (though it's via the preset-react):

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=react&targets=&browsers=%0A&builtIns=false&code=class%20MapOfMaps%3CK1%2CK2%2CV%3E%20%7B%0A%20%20innerKeys(key1%3A%20K1)%3A%20Iterator%3CK2%3E%20%7B%7D%0A%7D%0A&experimental=false&loose=false&spec=false&playground=true&stage=0

**Comment by ea167** [comment]
@existentialism thank you very much! You pointed me to the source of my problem.

My mistake, fully, there are no bugs, I apologize, sorry for the issue :(

Actually, _Eslint_ was complaining. What is weird is that Eslint did not report any error about flow until I used `Iterator<T>`, and that misled me. Installing eslint-plugin-flowtype solved the issue.

**Comment by existentialism** [comment]
@ea167 no need to apologize! glad your issue got resolved.
