### ISSUE TITLE
Ternary expression fails parsing when react preset is present

### ISSUE THREAD

**Issue by adrianton3** [babel/babel#5529]
### Input Code

```js
a ? () => ({}) : b => c
```

[repl link](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact&targets=&browsers=&builtIns=false&code=a%20%3F%20()%20%3D%3E%20(%7B%7D)%20%3A%20b%20%3D%3E%20c
)
### Babel Configuration (.babelrc, package.json, cli command)

See the link to the repl

### Expected Behavior

The code should compile to

```js
a ? function () {
  return {};
} : function (b) {
  return c;
};
```

as it does if the react preset is not mentioned

### Current Behavior

```
repl: Unexpected token, expected : (1:23)
> 1 | a ? () => ({}) : b => c
    |                        ^
```

### Your Environment

Getting this in the online repl; the latest release as of 23 mar 2017 is 6.24.0 assuming the repl is using that.

**Comment by hzoo** [comment]
Thanks for reporting, this is a parser issue. React currently adds flow automatically so it parses with the flow plugin.

@babel-bot move to babel/babylon
