### ISSUE TITLE
Babel doesn't ignore node_modules directory, although it is in “ignore” config

### ISSUE THREAD

**Issue by wzup** [babel/babel#5532]
For some reason `babel` doesn't ignore `node_modules` directory, although I specified it in `"ignore"` field of `.babelrc` file. Why does it happen? How to make `babel` act as expected?

My goal is to compress and mangle all `.js` files in my ExpressJS app (particularly my all back end code) before I push my app to remote repo and then to server. So I use `babel` and `babili`.

Here is my `.babelrc` config:

    {
        "presets": [
            ["latest", {
                "modules": false
            }]
        ],
        "env": {
            "development": {
                "presets": ["stage-0", "react", "babili"]
            },
            "production": {
                "presets": ["stage-0", "react", "babili"]
            }
        },
        "ignore": [
            "node_modules",
            "assets",
            "view",
            "public",
            "test",
            "spec",
            "logs",
            "lib/jasmine_examples",
            "db"
        ]
    }

And I run `babel` from command line like this:

    ./node_modules/.bin/babel . -d ~/app_compressed/

And `babal` starts compressing `node_modules` directory:

    node_modules\apache-crypt\gensrc\index.js -> C:\Users\user\app_compressed\node_modules\apache-crypt\gensrc\index.js
    node_modules\apache-md5\gensrc\index.js -> C:\Users\user\app_compressed\node_modules\apache-md5\gensrc\index.js
    node_modules\babel-preset-env\data\built-in-features.js -> C:\Users\user\app_compressed\node_modules\babel-preset-env\data\built-in-features.js
    node_modules\babel-preset-env\data\plugin-features.js -> C:\Users\user\app_compressed\node_modules\babel-preset-env\data\plugin-features.js
    node_modules\babel-preset-env\lib\default-includes.js -> C:\Users\user\app_compressed\node_modules\babel-preset-env\lib\default-includes.js
    node_modules\babel-preset-env\lib\index.js -> C:\Users\user\app_compressed\node_modules\babel-preset-env\lib\index.js

Literally wrong behavior. How to fix it? How to make `babel` ignore folders specified in config?

SO: http://stackoverflow.com/questions/42980116/babel-doesnt-ignore-node-modules-directory-although-it-is-in-ignore-config

**Comment by hzoo** [comment]
There are some issues with ignore/only that we are fixing in 7.0 like with https://github.com/babel/babel/pull/5467, similar to https://github.com/babel/babel/issues/4558.

Will do another alpha release today that you can test!

**Comment by wzup** [comment]
While you can't help much, @hzoo,  with your "There are some issues with ignore/only that we are fixing", I found that if I pass ignored directories in command line, they are accepted.

I'm curious, you're a member of the dev group, and you didn't know that? You could say that passing ignored as cli options is a solution. Thanks for nothing

**Comment by hzoo** [comment]
Yeah I didn't know that actually, or forgot. I mentioned on slack I haven't really used `ignore` so I haven't had to deal with this issue. Glad you figured it out.

**Comment by loganfsmyth** [comment]
> I'm curious, you're a member of the dev group, and you didn't know that? You could say that passing ignored as cli options is a solution. Thanks for nothing

Dang dude, we're humans not robots, if you insult the people trying to help I'm not sure how you expect to get help in the future.

**Comment by mikesherov** [comment]
Please block and report that user.

**Comment by loganfsmyth** [comment]
To me, that seems like an unnecessarily aggressive approach, for this specific case.

**Comment by mikesherov** [comment]
You're right! I just get upset when I see folks taking your hard work for granted. Keep up the great work @hzoo and @loganfsmyth

**Comment by wikiwong** [comment]
@wzup If you don't see how @hzoo has made your life easier, maybe you should stick with ES5 syntax
