### ISSUE TITLE
Enhanced object literal on a reused variable that is a cloned plain object leads to unexpected behaviour

### ISSUE THREAD

**Issue by szilveszter99** [babel/babel#5533]
### Input Code (content of test.js)
```js
(function workingUnexpectedly() {
    let i = 0;
    let someobject = {a: 1};
    let solution = { someobject };

    while(i<4) {
        console.log(solution.someobject);
        if(i===0) {
            someobject = Object.assign({}, someobject);
            solution = {
                someobject,
            };
        }
        someobject['a'] += 1;
        i++;
    }
}());
// unexpected result: {a:1} {a:2} {a:3} {a:4}

(function workingAsExpected() {
    let i = 0;
    let someobject = {a: 1};
    let solution = { someobject };

    while(i<4) {
        console.log(solution.someobject);
        if(i===0) {
            solution = {
                someobject: Object.assign({}, someobject),
            };
        }
        someobject['a'] += 1;
        i++;
    }
}());
// expected result: {a:1} {a:1} {a:1} {a:1}
```

### Babel Configuration (.babelrc, package.json, cli command)
no configuration, fresh directory and npm i babel-cli (version 6.24.0)
```shell
babel-node test.js
```

### Expected Behavior
I would expect that the first function prints {a:1} {a:1} {a:1} {a:1}

### Current Behavior
The first function prints {a:1} {a:2} {a:3} {a:4} despite the fact we don't change the solution and its attribute 'someobject' is a cloned plain object.

| software         | version
| ---------------- | -------
| Babel            |  6.24.0
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | OSX El Captain

**Comment by loganfsmyth** [comment]
This is expected behavior
```
            someobject = Object.assign({}, someobject);
            solution = {
                someobject,
            };
```
vs
```
            solution = {
                someobject: Object.assign({}, someobject),
            };
```

are very different things. One reassigns `someobject` and one does not.

**Comment by szilveszter99** [comment]
@loganfsmyth yes, the second one is my workaround, but I would expect the first to behave exactly the same as the second one in the context seen above.

**Comment by loganfsmyth** [comment]
The two pieces of code do different things. In this case it seems that your expectations don't match the code. Because in the first you change the object that `someobject` references, your `someobject['a'] += 1;` will update the property on that object, whereas in the second, that line will always update the `a` property on the original object.

If you changed it to

```
            const tempSomeobject = Object.assign({}, someobject);
            solution = {
                someobject: tempSomeobject,
            };
```

it would also work.

**Comment by szilveszter99** [comment]
yes, I see that is also working, but I am cloning the object and passing the cloned someobject to the solution object, that is why I am not expecting any changes in the solution object in the next loop when I am console.logging it

**Comment by szilveszter99** [comment]
hmm, I have to rethink this.

**Comment by szilveszter99** [comment]
haha, alright, not sure how I confused myself so deeply, obviously I am not freezing it and reusing the previous reference
