### ISSUE TITLE
Exporting imported types fails using babel-plugin-transform-flow-comments

### ISSUE THREAD

**Issue by gajus** [babel/babel#5538]
### Input Code

```js
// @flow

import type {
  DatabaseConnectionType
} from './types';

export type {
  DatabaseConnectionType
};

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["transform-flow-comments"]
}
```

### Expected Behavior

Not sure. I cannot figure out whats the expected syntax.

```js
// @flow

export type DatabaseConnectionType = {};

```

produces:

```js
"use strict";

// @flow

/*:: export type DatabaseConnectionType = {};*/
//# sourceMappingURL=index.js.map

```

According to this [source](http://stackoverflow.com/a/32727530/368691), the expected syntax is:

```js
export type {DatabaseConnectionType}
```

### Current Behavior

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
// @flow

/*:: import type {
  DatabaseConnectionType
} from './types';*/
exports.DatabaseConnectionType = DatabaseConnectionType;
//# sourceMappingURL=index.js.map

```

This results in an error saying that `DatabaseConnectionType` is undefined.

### Context

Trying to export internal types via public library interface.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  ^6.24.0
| node             | v7.7.1
| npm              | 4.1.2
| Operating System | N/A

**Comment by gajus** [comment]
I might be wrong, but this appears to be a deficiency in the Flowtype spec. I cannot find an example of exporting and imported type in https://flowtype.org/docs/modules.html documentation.

**Comment by gajus** [comment]
After some digging in Flow issues, I [found](https://github.com/facebook/flow/issues/1379) that this works:

```js
export type {
  DatabaseConnectionType
} from './types';

```

Which translates to:

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _types = require('./types');

Object.defineProperty(exports, 'DatabaseConnectionType', {
  enumerable: true,
  get: function () {
    return _types.DatabaseConnectionType;
  }
});
//# sourceMappingURL=index.js.map

```

Using this logic, then:

```js
import type {
  DatabaseConnectionType
} from './types';

export type {
  DatabaseConnectionType
};

```

should produce the same output.

**Comment by Kovensky** [comment]
It looks like the transform only deals with `ExportNamedDeclaration` that have a `declaration` (so something like `export type Foo = {}`), but not ones that have `specifiers` (like `export type { Foo, Bar as Baz }`). Is that supported in the flow spec?

**Comment by gajus** [comment]
> Is that supported in the flow spec?

I cannot find a reference in the spec, but it works.

https://flowtype.org/try/#0C4TwDgpgBAYg9nKBeKA7ArgWwEYQE4DcAUERAB5hx7BSiRQDe8cAvgUA
