### ISSUE TITLE
Understanding usecases of manual .babelrc lookups and OptionManager use

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5541]
In an ideal world, it makes no sense for third parties to reimplement `.babelrc` lookups in their own tools, and I think that fact that it isn't uncommon points to missing features from babel-core. I think it is important that we, as a team, understand _why_ that approach is currently taken by tools using `babel-core` so that we can ensure the babel-core API provides the primitives that third parties need.

The cases I know of:

* [`babel-loader`](https://github.com/babel/babel-loader/blob/7.0/src/resolve-rc.js) resolves `.babelrc` for cache invalidation purposes
* [`babel-jest`](https://github.com/facebook/jest/blob/master/packages/babel-jest/src/index.js#L28) uses the file for cache busting
* [`babel-brunch`](https://github.com/babel/babel-brunch/pull/53) is currently trying to use OptionManager to inject default behavior for 
* [`next.js`](https://github.com/zeit/next.js/pull/969) previously resolved `.babelrc` and now uses the private config-chain API to decide when to inject a default preset vs rely on a user's local config

There may be other cases, but those at least make two points clear:

* Caching is hard right now because `babel-core` doesn't expose caching primitives. We may be able to address this as part of https://github.com/babel/babel/issues/5372
* Users want to know if there is a config so that they can inject there own configs when there are none added by the user.

The second case I don't think we adequately expose currently. We have OptionManager but it's not a pretty API, and while it exposes the final config, it doesn't allow users to know if there was a config file, or if the config just came from the defaults. You can check if there a plugins/presets present, which may be enough in this case though, so I'd consider that an open question.

I'd be curious to hear from @arunoda since I've already had some back and forth about OptionManager in the Brunch PR, but the Next.js usecae is one I'm less clear on.

**Comment by arunoda** [comment]
@loganfsmyth Thanks for opening this issue.
Actually, we wanted to get the default lookup system without implementing our own logic.
But, we wanted to detect which `.babelrc` is going to use. If not, we wanted to use our own defaults.

We can easily do fix and remove the private API use, if babel has a public API to resolve the `.babelrc` file.

**Comment by loganfsmyth** [comment]
I'm curious, do you need to detect the presence of a `.babelrc` specifically, or just the presence of plugins? The `OptionManager` API we currently expose allows you to fully resolve Babel's config into a set of options and a set of plugins, so you could for instance use that as a proxy. The primary difference that comes to mind is:

* You can't really differentiate between plugins enabled via a preset vs plugins enabled directly, which is fine in your case
* You can't know if a config file exists, just what the final config was, so checking for plugins means that technically you'd change behavior if a user had a config file but didn't enable any plugins in it.

We could certainly explore exposing an API to check if a file-based config file exists. One of the reasons I'm looking to explore this is that most manual implementations aren't consistent, like while a `.babelrc` may exist, config can also just as well be in `package.json`, and in Babel 7 there will also be a `.babelrc.js`, so all of these manual implementations are going to get even more inconsistent.

**Comment by arunoda** [comment]
@loganfsmyth We need to check the existence of an exiting babel config file.
If there's a such a file (even a package.json) we need log it when running next.js.

So, users know what's there babel config file and how it looks like.
Usually, that helps to find issues where a wrong babelrc file (in a top level directory) messed up Next.js.

**Comment by hzoo** [comment]
There's also:

https://www.npmjs.com/package/find-babel-config @tleunen
https://www.npmjs.com/package/babel-load-config @egoist

**Comment by danez** [comment]
Here is also a list of packages that use `find-babel-config` https://github.com/tleunen/find-babel-config/network/dependents?dependent_type=PACKAGE

As for babel-loader: I think we should not do caching there at all and instead point people to use `cache-loader`. Which would solve the need to lookup the config at all. Only problem with this is the cache validation which users would need to do on their own. So we could have a helper that generates a cache key based on babel configs for the file to be compiled.

**Comment by egoist** [comment]
> @arunoda: We need to check the existence of an exiting babel config file.
If there's a such a file (even a package.json) we need log it when running next.js.

Yeah [babel-load-config](https://www.npmjs.com/package/babel-load-config) is extracted from Next.js and born for the same use case in [Poi](https://github.com/egoist/poi)

**Comment by loganfsmyth** [comment]
@arunoda I was exploring this issue a bit more and noticed that `next.js` allows users to opt out of `babelrc` searching from _inside_ their `.babelrc` for https://github.com/zeit/next.js/pull/1094. Would you be able to elaborate on the motivation behind allowing that?

**Comment by loganfsmyth** [comment]
I've posted https://github.com/babel/babel/pull/7472 which I think will go a long way toward allowing tooling to use Babel's builtin config processing without having to re-implement it.

**Comment by loganfsmyth** [comment]
Alright, I'm closing this as done.
