### ISSUE TITLE
babel-polyfill: generate individual files for each shim

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5553]
Choose one: is this a bug report or feature request?: feature request

### Expected Behavior

it would be more intuitive and also less weird (for npm 2, yarn?) if babel-preset-env just changed into babel-polyfill still

```js
import "core-js/string.pad-start";
import "core-js/string.pad-end";
```

### Current Behavior

Currently https://github.com/babel/babel-preset-env/#usebuiltins turns

```js
import "babel-polyfill";
```

into

```js
import "core-js/modules/es7.string.pad-start";
import "core-js/modules/es7.string.pad-end";
```

### Possible Solution

Generate the extra module files to be used by preset-env instead of just the one polyfill.js file in https://github.com/babel/babel/blob/7.0/packages/babel-polyfill/src/index.js.

Need to modify https://github.com/babel/babel/blob/7.0/packages/babel-polyfill/scripts/build-dist.sh to generate the individual polyfills

**Comment by andimarek** [comment]
Hi,

I would help with this issue, but I need a bit guidance. :-)

Shouldn't the expected behavior to be imports from `babel-polyfill`:

```javascript
import "babel-polyfill/string.pad-start";
import "babel-polyfill/string.pad-end";
```
instead from `core-js`?

Otherwise generating new module files in `babel-polyfill` wouldn't make much sense, I think.

Thanks,
Andi

**Comment by hzoo** [comment]
@andimarek yeah must of been my typo

Done in https://github.com/babel/babel/pull/5584 and released with alpha 7
