### ISSUE TITLE
A slash followed by a leadingComment is not generated correctly in compact mode

### ISSUE THREAD

**Issue by tgecho** [babel/babel#5557]
I'm prepending certain expressions with leadingComments, but when Babel generates in compact mode it lets the comment bleed into forward slashes, creating an invalid result.

```js
var maybeNotUsed = 2 / pureFunction(1);
// becomes
var maybeNotUsed=2//* #__PURE__ */pureFunction(1);
```

Demonstration: https://jsfiddle.net/Ltgfmnh0/

### Expected Behavior
Ideally, the generator would ensure a space exists between the slash and the comment.

### Current Behavior
The rest of the line becomes commented out :(

| software         | version
| ---------------- | -------
| Babel            |  6.24.0
| node             | v7.7.4
| npm              | 4.1.2

**Comment by loganfsmyth** [comment]
Sounds like a bug to me! Good find.

**Comment by loganfsmyth** [comment]
I don't have time to tackle this now, but if someone wants to, I _think_ it's just on this line: https://github.com/babel/babel/blob/0c2ac9d907364958fc0f71b656c3ce9255dfef62/packages/babel-generator/src/printer.js#L559 we should have `if (this.endsWith("/")) this._space();`

**Comment by tgecho** [comment]
I should be able to take a stab at a PR tomorrow. Thanks for the pointer in the right direction!
