### ISSUE TITLE
AST will run twice

### ISSUE THREAD

**Issue by vicwang163** [babel/babel#5559]
```js
module.exports = function (babel) {
  var t = babel.types; // AST模块
  return {
    visitor: {
      Class: function Class(path, state) {
        var node = path.node;
        // why it will run twice
        console.log(node.id.name)
      }
  };
};
```
any method in visitor will run twice, anyone can help me

**Comment by vicwang163** [comment]
@thejameskyle I need your help

**Comment by goto-bus-stop** [comment]
Can you share your `.babelrc` and your input code?

**Comment by xtuc** [comment]
Could you please use the [issue template](https://raw.githubusercontent.com/babel/babel/7.0/.github/ISSUE_TEMPLATE.md) ?

**Comment by hzoo** [comment]
@vicwang163 please follow the issue template, don't ping people randomly in the issue, and ask this question in our slack instead.

Your code snippet has a syntax error (missing }). Maybe you just have 2 classes in the code so it console.logs twice.

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by vicwang163** [comment]
@xtuc thank you for your suggestion
my plugin is here : https://github.com/vicwang163/babel-plugin-react-perf
the .babelrc in my project is
```json
{
  "presets": ["es2015","react"],
  "plugins": [
    ["react-perf",{
        "maxExecuteLimit": 3,
        "needAddPerfRule": {
          "superClass": ["Component"]
        }
      }
    ]
  ]
}

```
I found that my injected code will added twice
at first, I doubt that there is something wrong with my code,
so then I simplified my visitor code, as below

```js
module.exports = function (babel) {
  var t = babel.types;
  return {
    visitor: {
      Class (path) {
        console.log(path.node.id.name)
      }
    }
  };
};
```
there is no extra logic, console.log will run twice for the same class too

the package.json looks like that
```json
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-react-transform": "^1.0.3",
    "babel-polyfill": "^6.20.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.0.0"
}
```

**Comment by loganfsmyth** [comment]
That is likely expected behavior. We don't provide any guarantees that a given visitor will be called only once. As the various plugins move things around in the AST, it is possible for the same nodes to be encountered more than once.

Generally we recommend people add the nodes to a Set, or include logic to check if the code you're injecting is already present.

I don't disagree that this behavior is less than ideal for many cases, but it is what we currently have and it will be a while before that changes.

**Comment by vicwang163** [comment]
@loganfsmyth thanks for your reply
I am just looking for a better solution that I don't know,
ok,I will add some logic to check in my project for now
