### ISSUE TITLE
Compiled with Syntax error - Invalid regular expression 

### ISSUE THREAD

**Issue by MatusSkerlik** [babel/babel#5564]
When i run project in "developing" mode everything works as it should.
`npm run dev`
But when i bundle code into Electron and run application, i am getting error in /app/dist/bundle.js
`npm run package`

_Syntax error: Invalid regular expression: missing /_

my repository [rep](https://github.com/MatusSkerlik/Prezior)

Compilation of source code is made by babel-pollyfill
OSX 10.12.3, node v6.9.2, npm 4.2.0

**Comment by loganfsmyth** [comment]
I think you'll need to narrow this down a bit, there isn't nearly enough information to go on. What code is failing? Do you have a sense for what the error is? What makes you say this is a Babel issue?

The link to your repo also doesn't work.

**Comment by MatusSkerlik** [comment]
Sorry for that link, it works now.
Like i said everything works until i run bundled application.
 I think it is problem with babel or my babel configuration because code is converted from es6 to es5 and that is babel functionality. I really dont know where is the problem, but when i use syntax validator to test file /app/dist/bundle.js there is a syntax error.

**Comment by loganfsmyth** [comment]
I'm happy to help if this is a Babel issue, but it would be great if you could narrow it down. That file is 2MB. What regex is broken? What does it look like in the original source? What change happened to make it break, at least from what you can tell?

**Comment by MatusSkerlik** [comment]
it is on 12 line, it is loadash.js 1.8.3 section of code i think, please go to [http://esprima.org/demo/validate.html](http://esprima.org/demo/validate.html) and copy contents of bundle.js in it so you can see. When i fix this line another syntax error will show up on line 37, modernizr.js section, and it continues for ever.

**Comment by loganfsmyth** [comment]
Line 12 is 90000 characters long. Please include the working vs failing regexes here so we can compare.

**Comment by MatusSkerlik** [comment]
This lines don't work.
generated code -> line 12 `var W=//g;`,
generated code -> line 36 `Fe=//g`, `He=//g` and so on.
I think that first slash is representing something like new line because everything is form end of line.
It is helpful in some way ?

**Comment by loganfsmyth** [comment]
If you remove the `BabiliPlugin` from your Webpack config, does it work? It's possible that's causing some issue.

**Comment by MatusSkerlik** [comment]
Yes, it works now. Thank you so much, you have saved my ass 👍

**Comment by loganfsmyth** [comment]
Babili is still beta-level, so it's certainly possible there is some bug you are hitting here.

**Comment by MatusSkerlik** [comment]
Thank you again, i would not use it if i knew it. It took my so much time.

**Comment by boopathi** [comment]
@MatusSkerlik looks like some bug with Babili in regexp. Might be the same as https://github.com/babel/babili/issues/440. Can you try with [Babili Option](https://github.com/babel/babili/tree/master/packages/babel-preset-babili#1-1-mapping-with-plugin) - `regexpConstructors` set to `false`

```js
new BabiliPlugin({
  regexpConstructors: false
})
```

in your webpack config.

**Comment by Slapbox** [comment]
For me, the package [Chrono-Node](https://github.com/wanasit/chrono) 1.3.1 and 1.2.5 both cause this error. Adding `regexpConstructors: false` makes no difference unfortunately.

**Comment by merges** [comment]
Ditto the chrono-node issue
