### ISSUE TITLE
Assume array option for transform-es2015-for-of

### ISSUE THREAD

**Issue by andyearnshaw** [babel/babel#5569]
I'm working on a library that has to remain as small as possible.  As such, we aren't including most of `babel-polyfill`.  However, I'd still like to permit `for..of` loops in the codebase.

https://github.com/babel/babel/pull/3485 added an optimisation path for array literals or explicitly type-hinted variables.  I'd like to add an option that forces the assumption that all `for..of` statements target arrays.  Before I take it on, would a pull request be accepted for that?

There is an [NPM module](https://github.com/webconnex/babel-plugin-for-of-array-only) that works with Babel 5.x, but not 6.x.  I guess I'm not the only one with the requirement, so hopefully we can get this option into the official transform plugin.

**Comment by hzoo** [comment]
> for..of statements target arrays

If you pass an array it already does this; try `for (let a of []) {}` in the repl, and we already have a "loose" mode. If we do this the option name would have to signify that it isn't spec/dangerous

**Comment by andyearnshaw** [comment]
And indeed it could. There are already several options that "aren't spec".
For instance spread's loose mode forces array assumption.

**Comment by hzoo** [comment]
I'm not sure if we want to do this still (would have to be named appropriately), but I think it can go in https://github.com/babel/babel/pull/3485 if we do.

**Comment by jridgewell** [comment]
Why not leave it to a transform plugin? It'd be pretty simple.

**Comment by hzoo** [comment]
Yeah, does it have to go in the "for of" transform though? Could just be another transform too, and not in this repo/official

**Comment by jridgewell** [comment]
I went ahead and did it because I could use something similar. https://github.com/jridgewell/babel-plugin-transform-for-of-as-array

**Comment by hzoo** [comment]
Cool, thanks @jridgewell! If we want it as an option, we can move it in later if the community wants that.
