### ISSUE TITLE
Support for scoped presets

### ISSUE THREAD

**Issue by alexindigo** [babel/babel#5570]
Would be nice to have support for scoped presets. Especially valuable for those of us with internal npm instances, where we can publish only scoped modules.

Current syntax to include module `babel-preset-mypreset` into babel config looks like this:

```
{
  "presets": ["mypreset"]
}
```

But there is no syntax to use module `@mycorp/babel-preset-mycorppreset`.

As a suggestion, something like this seems pretty straightforward:

```
{
  "presets": ["@mycorp/mycorppreset"]
}
```

Thank you.

**Comment by alexindigo** [comment]
@bcoe this one :) Thanks.

**Comment by loganfsmyth** [comment]
We do have this currently: https://github.com/babel/babel/blob/7.0/packages/babel-core/src/config/helpers/get-possible-preset-names.js#L5, we don't have it for plugins though: https://github.com/babel/babel/blob/7.0/packages/babel-core/src/config/helpers/get-possible-plugin-names.js

**Comment by exogen** [comment]
I'm running into this issue currently. I switched a module of ours from non-scoped to scoped, and things confusingly stopped working – finally tracked it down to Babel.

This works:

```json
 "presets": ["our-dev-scripts/babel"]
```

But this does NOT work:

```json
 "presets": ["@scope/our-dev-scripts/babel"]
```

It does appear to work if the babel config is our `main` entry point, but I don't want that – we have multiple types of configs in there, like `react-scripts`.

As a workaround, I found that this works, but is ugly:

```json
 "presets": ["@scope/our-dev-scripts/babel.js"]
```

I'm not sure why it can't just be resolved like a normal module would be (both with `.js` and without would work), but I'm sure there's some complexity I don't understand.

**Comment by loganfsmyth** [comment]
This has been fixed in Babel 7, so I'm actually going to close this. It should work exactly how you'd like there.

For now if your workaround works then I'd say go with that. Otherwise you could also create a local file, e.g. `./dev-preset.js`, use that as your preset, and have it do

```
module.exports = require('@scope/our-dev-scripts/babel');
```
