### ISSUE TITLE
Invalid repository in package.json

### ISSUE THREAD

**Issue by satazor** [babel/babel#5574]
### Expected Behavior

package.json repository field should be a valid cloneable URL.

### Current Behavior

All packages repository field are invalid, e.g.: https://github.com/babel/babel/tree/master/packages/babel-helper-fixtures

### Context

I was improving npms.io to handle mono repositories better and I was testing it against babel, but then I discovered this..

**Comment by xtuc** [comment]
The only clonable git repository contains all the packages (monorepo).

I don't see what could be the repository of a single package.

**Comment by futagoza** [comment]
How about:

```json
{
  "homepage": "https://github.com/babel/babel/tree/master/packages/babel-cli",
  "repository": "https://github.com/babel/babel.git"
}
```

Within the `README.md` in each package there should be a link to the main babel site, as well as a note saying the package is part of a monorepo based project.

Additionally, if the package is a plugin/preset/etc, there should also be a link to the related plugin page on the site.

**Comment by hzoo** [comment]
Looks like it's handled in https://github.com/npms-io/npms-analyzer/issues/147 now? Thanks!

**Comment by satazor** [comment]
Yes it is handled. Still I wanted to give you guys an heads up about the invalid URL.
