### ISSUE TITLE
Error: watch null UNKNOWN

### ISSUE THREAD

**Issue by TomYeoman** [babel/babel#5576]
Hi all, 

I'm having an issue where babel has randomly stopped working for a team member. I've tried reinstalling babel-cli, reinstalling project dependencies etc with no luck.

The build is always successfull but upon trying to start a watch it bombs out with the "Error: watch null UNKNOWN" error.

My "npm run build" script which runs on my identical machine, but does not run on my colleagues:

  "scripts": {
    "build": "babel -w js_uncompiled --out-dir js --source-maps",

| software         | version
| ---------------- | -------
| Babel            |   We've tried babel-cli@6.6.5   / 6.24.0  - Both work for me but not for colleague
| node             |   4.4.0
| npm              |  2.14.20
| Operating System |  Windows 7

# 
package.json

{
  "name": "babeltest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "babel -w js_uncompiled --out-dir js --source-maps",
	"build_ces": "babel -w scripts/CES_uncompiled --out-dir scripts/CES --source-maps",
    "build_jenkins": "babel js_uncompiled --out-dir js --source-maps",
	"build_jenkins_ces": "babel scripts/CES_uncompiled --out-dir scripts/CES --source-maps"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.16.0",
    "babel-plugin-check-es2015-constants": "^6.2.0",
    "babel-plugin-transform-es2015-arrow-functions": "^6.1.18",
    "babel-plugin-transform-es2015-block-scoped-functions": "^6.1.18",
    "babel-plugin-transform-es2015-block-scoping": "^6.1.18",
    "babel-plugin-transform-es2015-classes": "^6.2.2",
    "babel-plugin-transform-es2015-computed-properties": "^6.1.18",
    "babel-plugin-transform-es2015-destructuring": "^6.1.18",
    "babel-plugin-transform-es2015-for-of": "^6.1.18",
    "babel-plugin-transform-es2015-function-name": "^6.1.18",
    "babel-plugin-transform-es2015-literals": "^6.1.18",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.2.0",
    "babel-plugin-transform-es2015-object-super": "^6.1.18",
    "babel-plugin-transform-es2015-parameters": "^6.1.18",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.1.18",
    "babel-plugin-transform-es2015-spread": "^6.1.18",
    "babel-plugin-transform-es2015-sticky-regex": "^6.1.18",
    "babel-plugin-transform-es2015-template-literals": "^6.1.18",
    "babel-plugin-transform-es2015-typeof-symbol": "^6.1.18",
    "babel-plugin-transform-es2015-unicode-regex": "^6.1.18",
    "babel-plugin-transform-es3-member-expression-literals": "^6.5.0",
    "babel-plugin-transform-es3-property-literals": "^6.5.0",
    "babel-plugin-transform-minify-booleans": "^6.5.0",
    "babel-plugin-transform-regenerator": "^6.2.0",
    "babel-plugin-transform-simplify-comparison-operators": "^6.5.0",
    "babel-plugin-uglify": "^1.0.2"
  },
  "dependencies": {
    "babel-polyfill": "^6.7.4"
  }
}

# .babelrc

{
  "plugins": [
	"transform-minify-booleans",
	"transform-simplify-comparison-operators",
    "transform-es3-property-literals",
	"transform-es3-member-expression-literals",
    "check-es2015-constants",
    "transform-es2015-arrow-functions",
    "transform-es2015-block-scoped-functions",
    "transform-es2015-block-scoping",
    "transform-es2015-classes",
    "transform-es2015-computed-properties",
    "transform-es2015-destructuring",
    "transform-es2015-for-of",
    "transform-es2015-function-name",
    "transform-es2015-literals",
    "transform-es2015-object-super",
    "transform-es2015-parameters",
    "transform-es2015-shorthand-properties",
    "transform-es2015-spread",
    "transform-es2015-sticky-regex",
    "transform-es2015-template-literals",
    "transform-es2015-typeof-symbol",
    "transform-es2015-unicode-regex",
    "transform-regenerator",
    ["transform-es2015-modules-commonjs", {"strict": false}]
  ]
}

Thanks

**Comment by loganfsmyth** [comment]
Could you include the full error with stack trace?

**Comment by TomYeoman** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild babeltest@1.0.0
6 info build babeltest@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info babeltest@1.0.0 Failed to exec build script
9 verbose stack Error: babeltest@1.0.0 build: `babel -w js_uncompiled --out-dir js --source-maps`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid babeltest@1.0.0
11 verbose cwd T:\PortalStephen
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error babeltest@1.0.0 build: `babel -w js_uncompiled --out-dir js --source-maps`
17 error Exit status 1
18 error Failed at the babeltest@1.0.0 build script 'babel -w js_uncompiled --out-dir js --source-maps'.
18 error This is most likely a problem with the babeltest package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel -w js_uncompiled --out-dir js --source-maps
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs babeltest
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls babeltest
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by hzoo** [comment]
Hm we might have some issues with --watch and windows but not sure if we can really do anything here?

Closing this issue as it's been inactive! Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
