### ISSUE TITLE
babel-generator does not 

### ISSUE THREAD

**Issue by vihanb** [babel/babel#5578]
I'm creating a transformer with babel 6 and it looks like the following generates broken code:

```
path.replaceWith(t.memberExpression(t.numericLiteral(1), t.identifier('foo')))
```

This generates:

```
1.foo
```

but this is a SyntaxError in JS, the correct code would be:

```
(1).foo
```

**Comment by existentialism** [comment]
https://github.com/babel/babel/issues/5579
