### ISSUE TITLE
babel-generator does not correctly handle numeric literals

### ISSUE THREAD

**Issue by vihanb** [babel/babel#5579]
I'm creating a transformer with babel 6 and it looks like the following generates broken code:

```
path.replaceWith(t.memberExpression(t.numericLiteral(1), t.identifier('foo')))
```

This generates:

```
1.foo
```

but this is a SyntaxError in JS, the correct code would be:

```
(1).foo
```

**Comment by loganfsmyth** [comment]
Do you have a sample repo? AFAIK, babel converts `(1).foo` to `1 .foo`. Note that the space there is enough to fix the parsing issue.

https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=&targets=Node-7.4&browsers=&builtIns=false&code=(1).foo&experimental=true&loose=true&spec=false&playground=false&stage=0

**Comment by vihanb** [comment]
This is on AST explorer:
<img width="866" alt="screen shot 2017-04-03 at 6 59 28 pm" src="https://cloud.githubusercontent.com/assets/15314511/24638721/b35cc8e0-189f-11e7-8d98-693da8fdb837.png">

**Comment by loganfsmyth** [comment]
Gotcha. Opened a PR: https://github.com/benjamn/recast/pull/393
