### ISSUE TITLE
Unexpected token import only at Travis

### ISSUE THREAD

**Issue by angeloocana** [babel/babel#5593]
Hi!

After removing gulp-babel from my project, i started getting this error 'Unexpected token import' only at Travis.
When I test in my machine works fine.

This error happens only with node_mudules at travis, could any one help me?

Project:
https://github.com/polutz/ptz-user-domain

Travis:
https://travis-ci.org/polutz/ptz-user-domain/jobs/219081105

Npm Scripts:
"mocha": "mocha ./dist/**/*.js --require babel-polyfill --compilers js:babel-register",
"test": "nyc npm run mocha && nyc report --reporter=text-lcov > coverage.lcov && codecov --token=7a80ed20-dee8-4343-83a9-8dc25398a34c",

"devDependencies": {
    "babel-core": "^6.24.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.0",
    "babel-register": "^6.24.0",

Thanks!

**Comment by loganfsmyth** [comment]
It would appear your `ptz-core-domain` module in node_modules contains `import` statements that have not been transpiled before the module was published.

**Comment by angeloocana** [comment]
Thanks @loganfsmyth 
So is it not possible to publish to npm with imports, just because of Travis?

**Comment by angeloocana** [comment]
I was using gulp, in order to compile to ./dist/ with typescript and babel:

```
var gulp = require("gulp");
var ts = require("gulp-typescript");
var babel = require("gulp-babel");

gulp.task("js", function () {
    var tsProject = ts.createProject(__dirname + "/tsconfig.json");

    return tsProject.src()
        .pipe(tsProject())
        .pipe(babel())
        .pipe(gulp.dest("dist/"));
});
```

What is the recommend way? All the examples that i found, babel runs on the fly or by webpack.
This package ptz-core-domain must run on browser and sever.

**Comment by loganfsmyth** [comment]
The issue is that `babel-register` by default will not compile things in `node_modules`. I'm not sure why switching from Gulp to the CLI would affect that, if it is being published the same both ways.

**Comment by angeloocana** [comment]
Thanks =D
Is there some way to force babel to compile node_modules?

If I use the .babelrc bellow, i get the same error as travis in my machine:
```
{
    "presets": [
        ["es2015", {"modules": false}]
    ]
}
```
SyntaxError: Unexpected token import

If I use the .babelrc bellow, travis still fails but i can run it locally with no errors:
```
{
    "presets": [
        ["es2015", {"commonjs": true}]
    ]
}
```
From: https://babeljs.io/docs/plugins/preset-es2015/


__________________________

When I was using gulp, I was exporting to ./dist/ all files compiled by typescript and babel.
Today I'm using only typescript 'tsc' without gulp.

What should I do? Export real files to dist or run on the fly setting --compilers to mocha?

**Comment by loganfsmyth** [comment]
You'd need to explicitly configure `babel-register`, e.g.

```
const register = require('babel-register');

register({
    ignore: /node_modules\/(?!ptz-core-domain)/,
});
```
then instead of `js:babel-register` do `js:./custom-babel-register.js` or whatever filename you put ^ in.

What is your reason for publishing ES6 modules? Generally publishing a module without a CommonJS build isn't good form, since it means users of your library can't use it in standard Node.

**Comment by angeloocana** [comment]
It worked!!! Thank you!!!

I removed gulp because gulp-typescript wasn't generating source-map and throwing typings errors.
If there is some way to output babel compiled files without gulp i can think about it.

And again: Thank you!!! =D
