### ISSUE TITLE
ERROR in unknown: 'super' outside of function or class

### ISSUE THREAD

**Issue by Reinmar** [babel/babel#5594]
## Bug

I'm not sure where to report this issue because the problem is that I get so little info that I don't know how to debug it.

So, when using Webpack + Babili + babel-preset-env I get this error:

```
(babel-error a55c35d M5 ?3) p@m /workspace/ckeditor5.github.io> npm run build

> ckeditor5.github.io@1.0.0 build /workspace/ckeditor5.github.io
> rm -rf build/ && webpack

(node:64541) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: e3278e80fb05df4a5667
Time: 26310ms
 [337] ./js/app.js 1.54 kB {0} [built]
 [338] ./~/@ckeditor/ckeditor5-autoformat/src/autoformat.js 4.47 kB {0} [built]
 [353] ./~/@ckeditor/ckeditor5-core/src/editor/standardeditor.js 4.06 kB {0} [built]
 [355] ./~/@ckeditor/ckeditor5-editor-classic/src/classic.js 3.76 kB {0} [built]
 [357] ./~/@ckeditor/ckeditor5-editor-classic/src/classiceditoruiview.js 2.07 kB {0} [built]
 [394] ./~/@ckeditor/ckeditor5-heading/src/heading.js 6.01 kB {0} [built]
 [396] ./~/@ckeditor/ckeditor5-image/src/image.js 1.34 kB {0} [built]
 [398] ./~/@ckeditor/ckeditor5-image/src/imagecaption.js 1.09 kB {0} [built]
 [401] ./~/@ckeditor/ckeditor5-image/src/imagestyle.js 2.99 kB {0} [built]
 [409] ./~/@ckeditor/ckeditor5-link/src/link.js 9.52 kB {0} [built]
 [416] ./~/@ckeditor/ckeditor5-list/src/list.js 3.81 kB {0} [built]
 [431] ./~/@ckeditor/ckeditor5-presets/~/@ckeditor/ckeditor5-basic-styles/src/bold.js 1.83 kB {0} [built]
 [433] ./~/@ckeditor/ckeditor5-presets/~/@ckeditor/ckeditor5-basic-styles/src/italic.js 1.88 kB {0} [built]
 [524] ./~/@ckeditor/ckeditor5-presets/src/article.js 2.6 kB {0} [built]
 [694] multi ./js/app 28 bytes {0} [built]
    + 691 hidden modules

ERROR in unknown: 'super' outside of function or class (65789:36)
````

If you want to reproduce it, just clone https://github.com/CKEditor5/ckeditor5.github.io/tree/babel-error:

```
git clone https://github.com/CKEditor5/ckeditor5.github.io.git
cd ckeditor5.github.io
git co babel-error
npm i
npm run build
```

Important facts:

* If I build the code without babel-preset-env everything works (including the build). I can open the page in Chrome and there are no errors either so I think that there's no bug in the code.
* If I build the code with babel-preset-env configured to support a browser which doesn't support ES6 classes, everything works fine, including the build.
* This bug only occurs when babel-preset-env is configured to support modern browsers only. Actually, I think that with [these settings](https://github.com/CKEditor5/ckeditor5.github.io/blob/babel-error/webpack.config.js#L41-L50) Babel doesn't need to load any plugins because those browsers support all ES6 features that my code uses. However, I guess it tries to load plugins for ES7+ support... which is unnecessary in my case (I decided to report it https://github.com/babel/babel-preset-env/issues/250).

As I wrote, I got very little info about the error, so I don't even know how to check which `super()` call causes the problem. If you could tell me how to get higher verbosity, I may be able to provide more info.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.0
| node             | 6.9.1
| npm              |  4.0.3
| Operating System | MacOS

More details in https://github.com/CKEditor5/ckeditor5.github.io/blob/babel-error/package.json

**Comment by hzoo** [comment]
You should run preset-env with `debug: true` to see what transforms are run. And you should try removing plugins/code/babili to get a minimal repro.

**Comment by Reinmar** [comment]
Thanks for the tips.

So, the debug option gave me:

```
babel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": 56,
  "edge": 13,
  "firefox": 51
}

Modules transform: commonjs

Using plugins:
  transform-es2015-block-scoping {"edge":13}
  check-es2015-constants {"edge":13}
  transform-es2015-destructuring {"edge":13,"firefox":51}
  transform-es2015-for-of {"edge":13,"firefox":51}
  transform-es2015-function-name {"edge":13,"firefox":51}
  transform-es2015-literals {"firefox":51}
  transform-es2015-parameters {"edge":13,"firefox":51}
  transform-regenerator {"firefox":51}
  transform-exponentiation-operator {"edge":13,"firefox":51}
  transform-async-to-generator {"edge":13,"firefox":51}
  syntax-trailing-function-commas {"chrome":56,"edge":13,"firefox":51}
```

I'll try to check how removing plugins help later on.

**Comment by hzoo** [comment]
And it's possible the browsers ^ do support those plugins but aren't implementing 1 part of compat-table so we just defer to compiling it. If you are sure you can use include/exclude

**Comment by Reinmar** [comment]
I have more findings.

If I disable the Babili plugin (and keep babel-preset-env), the build passes, but it doesn't work. I found out that this is the code which then causes it to fail:

```js
	*getRanges() {
		if ( this._ranges.length ) {
			yield *super.getRanges();
		} else {
			yield this._document._getDefaultRange();
		}
	}
```

Source: https://github.com/ckeditor/ckeditor5-engine/blob/3a8ebed444d9b04304536ce88ddc370125de2a0f/src/model/liveselection.js#L126-L135

The same code works fine in the browser when I disable both – Babili and babel-preset-env.

So, it seems that babel-preset-env, with those settings I have, transpiles that specific module to something which is incorrect.

**Comment by Reinmar** [comment]
This is the transpiled version of that function which:

```js
	getRanges() {
		return regeneratorRuntime.wrap(function _callee$(_context) {
			while (1) {
				switch (_context.prev = _context.next) {
					case 0:
						if (!this._ranges.length) {
							_context.next = 4;
							break;
						}

						return _context.delegateYield(super.getRanges(), 't0', 2);

					case 2:
						_context.next = 6;
						break;

					case 4:
						_context.next = 6;
						return this._document._getDefaultRange();

					case 6:
					case 'end':
						return _context.stop();
				}
			}
		}, _callee, this);
	}
```

Now it's clear – the generator cannot be transpiled if `super` is not saved somewhere, because in the `regeneratorRuntime.wrap()`'s callback `super` is not valid.

**Comment by Reinmar** [comment]
Apparently, generator's transpiler depends on classes transpiler. I'm afraid that there are more dependencies like this which makes babel-preset-env pretty risky to use :(.

**Comment by hzoo** [comment]
There are very few - class/async/generators/rest just can't be transpiled in that way. You could just explicitly blacklist regenerator

**Comment by hzoo** [comment]
Closing some old issues, might be fixed in 7, feel free to reopen/new issue with another repro.
