### ISSUE TITLE
Object literal shorthand not getting transpiled?

### ISSUE THREAD

**Issue by jpfiorilla** [babel/babel#5598]
Hello,

I'm trying to sort out compatibility with Internet Explorer 11, and I'm running into an issue with object literals. IE11 stops at this line, saying it expected a colon:
```
var particles = { some: "object" }
module.exports = {
imagesFolder: '/wp-content/themes/reactify/images/',
  particles, <-- this line
  serialize,
  dateParse,
  slugify,
  titleAppend
}
```

This indicates that my babel isn't transpiling the object literal shorthand in my bundle.js like I expected. I've tried using `babel-polyfill` to solve this (see below) but no such luck. I've also tried using the "env" preset.

As a result, the site simply renders nothing on Internet Explorer. What can I use to have babel transpile this syntax for IE11?

webpack.config.js:
```
var config = {
      entry: ["babel-polyfill", APP_DIR + '/index.jsx'],
```

.babelrc:
```{
  "presets" : ["es2015", "react"],
  "plugins": ["transform-class-properties"]
}
```

index.jsx (entry):
```
import "babel-polyfill";
```

| software         | version(s)
| ---------------- | -------
| Babel            |  "babel-core": "^6.22.1", "babel-loader": "^6.2.10", "babel-preset-es2015": "^6.22.0", "babel-preset-react": "^6.22.0"
| node             |  7.4.0
| npm              |  4.0.5
| Operating System |  OSX 10.11.6

**Comment by loganfsmyth** [comment]
Do you have babel-loader in your webpack config? If so, how is it configured? And what is the path of the file containing the content triggering the error?

**Comment by jpfiorilla** [comment]
Hi Logan, thank you for responding. I do have babel-loader in my config, as below:

```
config = {
        ...
	module: {
		devtool: 'source-maps',
		preLoaders: [
			{
				test: /\.jsx?$/,
				loader: 'eslint',
				exclude: /node_modules/
			}
		],
		loaders: [
			{
			 	test:/\.jsx?$/,
				include : APP_DIR,
				loaders : ['babel-loader'],
				exclude: /node_modules/
			},
```

**Comment by loganfsmyth** [comment]
And what is `APP_DIR`, and are you sure the file that is getting skipped is inside that folder?

**Comment by jpfiorilla** [comment]
Ah, that was it! That file was outside the `APP_DIR` folder. Thank you very much!
