### ISSUE TITLE
Feature request: ability to preprocess js source in plugins with a fork of babylon

### ISSUE THREAD

**Issue by Alphapage** [babel/babel#5603]
Hello,

This is a long running limitation of babylon parser which doesn't provide a way to create a custom syntax: you want to keep control of babylon which I understand.

The problem is that we need to use a fork of babylon then modify its source code. Finally, we replace the original babylon package with our fork: most of the time the package will never be updated and could result in cascading errors in plugins.

It would be better to be able to modify the js source from a plugin. As far as I know, we can only play with the ast in a plugin.

Why not export such a function in plugin:
``` 
function preprocess(jsSource) {
jsSource=jsSource+'// comment added to the source (without using a babylon fork for now)'
// returns the modified source
return jsSource;
}
```

If a plugin implements such a function , then the js source will be modified before babylon execution and the parser will hang if it finds errors.

This will solve the babylon fragmentation too if there are too much babylon forks and you could also implement new syntax very quickly by checking babylon fork diffs.

I hope you will implement my request as soon as possible.

Thank you in advance for your answers.

**Comment by hzoo** [comment]
Thanks for the request!

Sorry, yes we have a lot of requests for this but it's not currently a priority for us as a project at the moment. We are focusing on providing a tool that helps developers use the latest version of JavaScript as well as move forward TC39 proposals to make it into JavaScript.

We currently aren't focused on letting anyone make whatever syntax they want to use, so I think forking is an ok solution for now. We don't want to have to maintain that API or whatever that results in for the whole ecosystem if everyone is using their own custom syntax. If a proposal is dropped then we deprecate. We will accept/encourage PRs for actual proposals in https://github.com/tc39/ecma262#current-proposals though.

Ref https://github.com/babel/babel/issues/1351

**Comment by Alphapage** [comment]
Thank you for pointing me to this "parserOpts".
```
{
  parserOpts: {
    parser: "babylon-fork-npm-pkg-here"
  }
}
```
I was waiting something like this to modify the js source sequentially, then let official babylon do its job:
```
{
  parserOpts: {
    preparsers: ["babylon1-fork-npm-pkg-here","babylon2-fork-npm-pkg-here",...]
  }
}
```
This will help me anyway. Thanks again.
