### ISSUE TITLE
Async + arrow + rest parameters doesn't work

### ISSUE THREAD

**Issue by alippai** [babel/babel#5604]
Choose one: is this a bug report or feature request?

Bug report

### Input Code
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2016%2Ces2017&targets=&browsers=ie%2011&builtIns=false&code=function%20logged(errorName%2C%20functionName%2C%20asyncFn)%20%7B%0D%0A%20%20return%20async%20(...params)%20%3D%3E%20%7B%0D%0A%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20return%20await%20asyncFn(...params)%3B%0D%0A%20%20%20%20%7D%20catch%20(rejection)%20%7B%0D%0A%20%20%20%20%20%20logEvent(errorName%2C%20functionName%2C%20rejection)%3B%0D%0A%20%20%20%20%20%20throw%20rejection%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20logged2(errorName%2C%20functionName%2C%20asyncFn)%20%7B%0D%0A%20%20return%20async%20function%20(...params)%20%7B%0D%0A%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20return%20await%20asyncFn(...params)%3B%0D%0A%20%20%20%20%7D%20catch%20(rejection)%20%7B%0D%0A%20%20%20%20%20%20logEvent(errorName%2C%20functionName%2C%20rejection)%3B%0D%0A%20%20%20%20%20%20throw%20rejection%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%3B%0D%0A%7D

### Expected Behavior
The rest parameters should work with async + arrows. (first example)

### Current Behavior
The rest parameters are lost, the function is called with wrong parameters. (second example)

**Comment by hzoo** [comment]
Duplicate of https://github.com/babel/babel/issues/4219

**Comment by hzoo** [comment]
Releasing v6.24.1 to fix
