### ISSUE TITLE
[Q] How to disable strict mode, if babel.transform() is used

### ISSUE THREAD

**Issue by szachara** [babel/babel#5614]
Hi, i want to ask, if it's possible to disable strict mode, when babel.transform() is used.

```
return babel.transform(
    contents, { presets: ['env'] }
).code;
```

Options are described in this doc http://babeljs.io/docs/plugins/transform-strict-mode/

But I don't know, how to pass this options to `env preset`.

Thank you for advices. 😃

**Comment by hzoo** [comment]
transform-strict-mode isn't part of the env preset - strict mode is turned on via the modules transform like http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs, so you would have to use `modules: false` to turn off compiling import/export. Then you can just add other plugins in your plugins option

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by szachara** [comment]
Ok, thx, I knew about `modules: false` and also that strict mode is enabled by `transform-es2015-modules-commonjs`, so there isn't any chance to somehow pass `strict: false` or `strictMode: false` to `transform-strict-mode` transform?

**Comment by szachara** [comment]
Ok, thx, I knew about `modules: false` and also that strict mode is enabled by `transform-es2015-modules-commonjs`, so there isn't any chance to somehow pass `strict: false` or `strictMode: false` to `transform-strict-mode` transform?
Thank you for answer @hzoo

**Comment by loganfsmyth** [comment]
That's generally not a good idea because it means your code will not be ES6 compliant. If your code doesn't work in strict mode, you should be writing it using normal CommonJS.

**Comment by szachara** [comment]
Ok, this morning I get it 😃 ES6 modules are always in strict mode, so that behavior is absolutely right, so disabling modules is all we need. Thx for direct me on right way @loganfsmyth
