### ISSUE TITLE
babel-node is missing a --no-babelrc flag

### ISSUE THREAD

**Issue by MrLoh** [babel/babel#5616]
Hi, I'm building an app with next.js and need different babel configurations for the react part and node part. 

My Problem ist that `babel-node` always ignores the the presets set in the `--presets` flag and uses whatever is in the babelrc file. I can't find a way to stop this behavior. There seems to be no `--no-babelrc` flag for babel node.

**Comment by xtuc** [comment]
As a current workarround you can use https://babeljs.io/docs/usage/cli/#babel-ignoring-babelrc

**Comment by mbrookes** [comment]
Ironically I'm having the opposite problem. 🙃 

`babel-node` is ignoring `.babelrc` (or at least plugins) when called from a `package.json` script (`npm run ...`).

It works fine when I run:
```sh
./node_modules/.bin/babel-node ./path/to/script.js
```

(cc @loganfsmyth since you reviewed the connected PR.)

Thanks guys!

**Comment by loganfsmyth** [comment]
If you can put together a reproducible example repository I can take a look.

**Comment by mbrookes** [comment]
Thanks. It's rather deeply entangled in https://github.com/mui-org/material-ui, and I didn't write the script that's being run, (just using it for a use-case that requires a plugin); but I'll see if I can strip it back to something more manageable.

**Comment by loganfsmyth** [comment]
This is done in #5621

**Comment by cbjs** [comment]
babel-node version 6.26.0, still no --no-babelrc option
