### ISSUE TITLE
class implements translate err

### ISSUE THREAD

**Issue by zenjava** [babel/babel#5626]
Choose one: is this a bug report or feature request?

### Input Code

```js
interface IPCMessager{
   send(): void;
}
class IPC implements IPCMessager {
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
"devDependencies": {
     "flow": "^0.2.3",
    "flow-bin": "^0.41.0",
    "flow-webpack-plugin": "^0.3.5",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-async-to-generator": "^6.22.0",
    "babel-plugin-transform-flow-comments": "^6.22.0"
}
```
```js
{
  "plugins": [
    "transform-flow-comments",
    "transform-async-to-generator"
  ]
}
```

### Expected Behavior
translate to 
```js

/*:: interface IPCMessager{
  send(): void;
}*/

class IPC  /*implements:: IPCMessager*/ {}
```

### Current Behavior

translate result is 
```js
/*:: interface IPCMessager{
  send(): void;
}*/

class IPC implements /*:: IPCMessager*/ {}
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.18.0
| node             | 6.9.1
| npm              | 3.10.8
| Operating System | osx 10.12.4

**Comment by hzoo** [comment]
Can you follow the issue template? Thanks! I believe you are asking about the flow-comments plugin but not sure.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by zenjava** [comment]
Ok ,I have changed the way to the template!

**Comment by loganfsmyth** [comment]
I'm curious, have you explored using `.js.flow` files instead of comments? The `transform-flow-comments` plugin is definitely buggy.

**Comment by zenjava** [comment]
Yes, I'm used transform-flow-comments plugin.
