### ISSUE TITLE
export loses inferred anonymous function name

### ISSUE THREAD

**Issue by srajko** [babel/babel#5630]
Choose one: is this a bug report or feature request?

Bug

### Input Code
```js
export const f1 = function () {};
export const f2 = () => {};
```

### Babel Configuration (.babelrc, package.json, cli command)
```
--plugins transform-es2015-modules-commonjs
```

### Expected Behavior
To preserve inferred names of anonymous functions, I would expect:
```js
// ...
const f1 = function () {};
exports.f1 = f1;
const f2 = () => {};
exports.f2 = f2;
// f1.name === 'f1'
// f2.name === 'f2'
```

### Current Behavior
```js
// ...
const f1 = exports.f1 = function () {};
const f2 = exports.f2 = () => {};
// f1.name === ''
// f2.name === ''
```

### Context
Especially for arrow functions (since there is no explicitly named alternative), it would be very helpful to preserve the inferred function name.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 7.3.0
| npm              | 3.8.9
| Operating System | Windows

**Comment by xtuc** [comment]
Seems related to babel/babel#5620

cc @Kovensky

**Comment by Kovensky** [comment]
Hm, 5620 is about the arrow transform itself. That is already handled correctly by non-spec arrow functions, but 5620 would fix the spec mode arrow functions.

This bug is about losing the arrow function name when the arrow function is not transformed, only modules is. Probably can't be fixed without using getters (spec modules).

**Comment by errorx666** [comment]
This is affecting the output of gulp.

![image](https://user-images.githubusercontent.com/1048542/30178977-7cf0f7a2-93d0-11e7-997d-88b5c37a8f16.png)

![image](https://user-images.githubusercontent.com/1048542/30178928-519fec70-93d0-11e7-893f-c20cbd4c5922.png)
