### ISSUE TITLE
Babel Bombs when using `babel-preset-react` with React `^15.5.0`

### ISSUE THREAD

**Issue by Swivelgames** [babel/babel#5631]
I'm getting the following error now that my latest version of `react` is `v15.5.0`. I'm assuming something inside one of the plugins in `babel-preset-react` is attempting to utilize `React.PropTypes`? This is a breaking change.

```
$ babel src --out-dir lib
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
ReferenceError: [BABEL] src/builder.js: Unknown option: /****/node_modules/react/react.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.
```

Halp!

**Comment by loganfsmyth** [comment]
That error means you've forgotten to install `babel-preset-react` and it's trying to use `react` itself as a preset. We're hoping to have a better error message in Babel 7.x for this type of thing.

**Comment by Swivelgames** [comment]
Wow! How embarrassing :) Thanks @loganfsmyth!
