### ISSUE TITLE
babel-generator: Unnecessary parentheses when returning regexp

### ISSUE THREAD

**Issue by andy-ms** [babel/babel#5633]
### Input Code

```js
const babylon = require("babylon");
const gen = require("babel-generator");
const src = "() => { return /a/; }";
const ast = babylon.parse(src);
const out = gen.default(ast);
console.log(out.code);
```

### Babel Configuration

N/A

### Expected Behavior

Output same as input.

### Current Behavior

```js
() => {
  return (/a/
  );
};
```

### Possible Solution

Review code for where parentheses are necessary.

### Context

I was running tests to compare generated code vs input code and ran into this.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel-generator  |  `7.0.0-alpha.7`
| Babylon        | `7.0.0-beta.8`
| node             | `7.9.0`
| npm              | `4.2.0`
| Operating System | Linux Mint 18

**Comment by hzoo** [comment]
Code is in https://github.com/babel/babel/blob/7.0/packages/babel-generator/src/node/parentheses.js
