### ISSUE TITLE
npm link utility

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#5634]
Would the following NPM utility be useful to Babel developers?

https://github.com/ORESoftware/npm-link-up

I am wondering if you already use something like this. I figure with more than 10 modules in existence, that you would run into problems developing locally.

**Comment by hzoo** [comment]
Thanks, we use https://github.com/lerna/lerna for this

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by ORESoftware** [comment]
@hzoo thanks, yeah I was on slack, and got the answer there too, Lerna is neat, I here it was original developer for Babel
