### ISSUE TITLE
Deprecate some packages

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5637]
- [ ] Remove the packages from this repo
- [ ] Move the packages to https://github.com/babel/babel-archive

---

- [ ] flow-comments?
- [x] babel-preset-latest (already deprecated in favor of preset-env)
- [x] https://github.com/babel/babel/tree/7.0/packages/babel-helper-builder-conditional-assignment-operator-visitor

**Comment by quanganhtran** [comment]
I have noticed that there is npm warnings for yearly preset as well (2016, 2017...), are they going to be/already deprecated?

**Comment by jridgewell** [comment]
Yup, use `babel-preset-env` instead.
