### ISSUE TITLE
Making it possible to detect ES6 classes, arrow functions

### ISSUE THREAD

**Issue by Download** [babel/babel#5640]
This is a feature request that includes (I'm not sure) a related bug.

The feature request is to make it possible / easy to detect ES6 classes and arrow functions. 

The bug (I am not sure) is that Babel transpiled arrow functions have a prototype, which they should not have if [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Use_of_prototype_property) is correct.

For a generic library ([mics](https://github.com/download/mics)) I want to detect whether the function I was given is a regular ES5 (constructor) function, an ES6 class or an arrow function.

For example, one cannot invoke ES6 class constructors without `new`. Likewise, one cannot invoke arrow functions *with* `new`. This is a pretty big change to ES5 where you could do whatever you wanted (at your own peril). In ES6 it will actually throw. So I want my mixin library to feature detect this.

To detect an ES6 class, we should be able to call `toString` on the function and if the result starts with `class` we know it's an ES6 class. This does not work with Babel (I am not saying it should), but we can still detect transpiled classes using the fact all Babel transpiled classes start with `_classCallCheck`.

To detect an ES6 arrow function we should be able to test for the function having a prototype. Arrow functions should not have one. Unfortunately, Babel transpiled arrow functions do have a prototype so we cannot successfully detect it. 

Now I am not saying that Babel should start overriding `toString` etc. And technically, the transpiled class is not actually an ES6 class... However, Babel does enforce (some of) the restrictions that ES6 puts on the calling code, so it would be nice if there was some way to feature-detect whether those restrictions apply to a a given function or not. I don't think that's currently possible. 

### Input Code
```js
function test() {
  var arrow = x => {
    return x
  }
  if (arrow.prototype) {
    console.info('Breaking spec? SEE https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Use_of_prototype_property')
  }  
}

test()
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": ["es2015"]
}
```

### Expected Behavior
No output is expected.

### Current Behavior
Logs an info message to the console:
> Breaking spec? SEE https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Use_of_prototype_property

### Possible Solution
One option would be to wipe out the prototype of any arrow function by adding `arrow.prototype = undefined` to the transpiled code. Another option would be to introduce some other mechanism so that we can feature detect arrow functions like we can with `_classCallCheck`. However note there is a feature request to [make `_classCallCheck` optional](https://github.com/babel/babel/issues/798) (which would break the feature detect). It would be great if we could come up with a performant system to allow feature detecting ES6 classes and arrow functions (generators? others?). 

Imho it would be ok (maybe even preferable) if this was separate from the 'real' feature detects as they are transpiled features and not 'real' anyway.

### Context
I have a function that accepts an optional 'factory' argument. I want to detect this factory's presence but, apart from the fact that it has only one argument, there aren't many distinguishing features so I thought I would mandate the use of arrow functions for it and check those (should be easy I thought, and is easy in 'real' ES2015) but it does not work for Babel transpiled code.

Anyway, being able to feature detect stuff is a fundamental part of the 'living standard' paradigm, so I think it's a feature worth having for Babel transpiled code.

**Comment by hzoo** [comment]
There is a spec mode for arrow-functions that adds a similar runtime check as classes. http://babeljs.io/docs/plugins/transform-es2015-arrow-functions

**Comment by loganfsmyth** [comment]
My general position is that feature detection on this kind of this is a bad idea. If you have two different types of inputs, you're way better off exposing two different functions for your users, one for callable types and one for `new`able types.

For a normal ES5 function, it could be either type and you have no way of knowing, and if you're calling a ES5 function as a constructor when it isn't meant to be, you're allocating a whole "instance" object that is then immediately discarded, and if the function was bound, you're discarding whatever `this` it already had bound.

We currently support a "spec" option for arrow functions that disables `new` usage on them, but it is opt-in and only applies in certain cases.

**Comment by Download** [comment]
Actually, I want to be able to take a bunch of functions and for each one determine, is it an ES6 class, an arrow function, or an ES5 function?

I understand the downsides to having a heavily 'overloaded function, but I prefer this style to having more functions. It can be a matter of taste. In true ES2015 I have a reliable way to detect the difference between these three types of functions, but for Babel transpiled code I have not.

**Comment by loganfsmyth** [comment]
Babel in no way supports `toString`. If you want to relying on searching for `_classCallCheck` you are asking for pain. We could literally change the name of that at any time.

> To detect an ES6 arrow function we should be able to test for the function having a prototype. 

Looking for a function without a `.prototype` is not a safe way to detect an arrow. A user could be doing
```
class Foo {
  constructor(boundArg){ }
}

yourApi(Foo.bind(null, {someBoundData: true}));
```
Bound functions also have no `.prototype` property, but they are perfectly safe, and in fact might _need_ to be called with `new` like any class.

This will also fail your `.toString` check because `.toString` doesn't pass through to the original unbound function.

> for each one determine, is it an ES6 class, an arrow function, or an ES5 function?

I just don't think there is any way to do that accurately when used alongside a compiler like Babel.

**Comment by loganfsmyth** [comment]
Alternatively you could never use `new` and require your users to pass `(...args) => new Foo(...args)` if they need to instantiate something? It makes tracking where things are instantiated dramatically easier to hunt for in your code.

**Comment by Download** [comment]
> This will also fail your .toString check because .toString doesn't pass through to the original unbound function.

AFAIK, `bind` returns a *new* function. This new function calls the ES6 class constructor, but it is itself not a class, so the `toString` check actually is correct.

I am not saying my check for arrow functions would not give false positives. I have not investigated it for long enough. The check for classes is rigorous though. The spec mandates the result of `toString` to start with `'class'`.

> If you want to relying on searching for _classCallCheck you are asking for pain. We could literally change the name of that at any time.

I am aware. However, that is a choice. The Babel team could choose to implement a strategy to actively support feature detecting ES6 classes. Either by promising not to remove that function call, or change it's name, or by adopting some other method that would allow client code to feature detect.

Feature detection is the foundation of the Living Standard paradigm so I think it is a worthwhile feature to have. Looking at a library like [is-class](https://www.npmjs.com/package/is-class), I think it demonstrates there is a demand for this kind of functionality. (he checks for `_classCallCheck` after checking for `class` so his code works with Babel.... for now)

BTW I think `We could literally change the name of that at any time` is not the best attitude for projects with the scale of adoption of Babel. You should be wary of change 'for the sake of change'. Changing a function name should not be done lightly even if it's technically a 'private' function. You are breaking peoples code. Unless there is a real good reason, doing so isn't very cool.

Anyway what I am asking for is a reliable way to feature detect, so hopefully it would not use private functions as it's basis. But maybe something as simple as setting `babelClass = true` and `babelArrow = true` etc.

**Comment by Download** [comment]
@loganfsmyth Your suggestion is exactly what I am trying to do. My function `mix` should always return a function that can be called with or without `new`. It should make no difference. To achieve that I need to know what the wrapper I am generating should do with the given function(s):

1. If it's a class, generate code similar to your suggestion to call the constructor with new in all cases
2. If it's an ES5 constructor, do the same as in 1.
3. If it's an arrow function, call it to create a class, then do 1.

**Comment by loganfsmyth** [comment]
> The check for classes is rigorous though. The spec mandates the result of toString to start with 'class'.

My point is that

```
const Foo = class { constructor(one, two){ } }.bind(null, "first");

// Instantiating is expected, "Foo()" without "new" would fail
new Foo();

// Length is reduced by 1 because of the .bind
Foo.length === 1

// "Foo" is a bound function so has no "class" token at its start
Foo.toString() === "function () { [native code] }"
```
so your class check will fail if someone is using `.bind` to partially apply arguments to a class constructor.

> BTW I think "We could literally change the name of that at any time" is not the best attitude for projects with the scale of adoption of Babel. 

My concern is entirely that we have no way of knowing what random things people are relying on. Maybe we change that name in Babel 7.x. Maybe we decide to pick shorter names for helpers to specifically make our bundles smaller for people using minifiers. Maybe the function being passed to you has been run through a minifier that has mangled all of its function names entirely outside your control.  If you choose to use `.toString` you are asking for pain. 

> Anyway what I am asking for is a reliable way to feature detect, so hopefully it would not use private functions as it's basis. But maybe something as simple as setting babelClass = true and babelArrow = true

We already hear from plenty of users that our output is verbose, I can only imagine how many people we would hear from if we added that to every arrow.

> My function mix should always return a function that can be called with or without new. It should make no difference.

I get that this is the behavior you want, but I think that ship has already sailed. ES6 makes a clear distinction here, some things can work with `new` and some can't. Trying to make everything work with either one is a battle that has already been lost.

**Comment by Download** [comment]
> so your class check will fail if someone is using .bind to partially apply arguments to a class constructor.

What I am saying is that the check won't fail. It will do what it's supposed to do. The result of calling `bind` is a *new* function. Not a class. The check will reflect that. I'm ok with that. It is to be expected if you understand what `bind` does.

> I get that this is the behavior you want, but I think that ship has already sailed.

To be frank, it looks like you actually don't get it. I understand that ship has sailed. I don't want it to change. All I want is to be able to feature detect babel's classes and arrow functions like I can ES6 classes and arrow functions. My particular use case is an example. In real ES6 my code is simple to write (finished and working as I want it), but I want to support Babel so I am looking at ways to achieve the same for babel-transpiled code.

> We already hear from plenty of users that our output is verbose

Yeah I get that. I fear it is a very good reason not to implement my proposal. I myself want to get rid of `_classCallCheck`!.... But I also want to feature detect... (yeah I know I want it all :)  Maybe there is an efficient way to do it. I don't know. Hoping someone here has a smart idea!

**Comment by loganfsmyth** [comment]
> What I am saying is that the check won't fail. It will do what it's supposed to do.

You original question asked:

> To detect an ES6 arrow function we should be able to test for the function having a prototype.

The above example would pass in a `Foo` without a prototype, because bound function objects have no `.prototype`, and would thus detect it as an arrow, and try to call it without `new`, which will fail.

```
var fn = (() => null).bind();  // `fn()` works, `new fn()` throws
var fn = (class {}).bind();  // `new fn()` works, `fn()` throws
```
take these two examples. Programmatically they are identical. There is no introspection you can perform to know ahead of time which needs `new` and which does not, even in a native ES6 environment.

I just don't think there is a way for us to achieve what you're asking. I'm open to suggestions, but extra properties is almost certainly a no-go for size reasons, and `.prototype` being missing also applies to other types of functions.

**Comment by Download** [comment]
I already admitted the arrow check was maybe not satisfying. It just behaves differently in Babel transpiled code than in real ES6 code,

I was saying the class detect works. It works on your example because `bind` does not actually produce a class.

> I'm open to suggestions, but extra properties is almost certainly a no-go for size reasons

I am not sure it has to be that expensive to add extra properties. Just use a function to do the wrapping and give it a short name:

```js
const arrowFunction = x => x + 5;
```

could transpile to:
```js
var arrowFunction = _baf(function(x){return x+5});
```

with `_baf` defined as:

```js
function _baf(fn) {
  fn.prototype = undefined
  fn.babelArrowFunction = true
}
```

But it would of course bring *a* cost. But so does `_classCallCheck`. I'd just like for the suggestion to be entertained for a while before being dismissed  👍

**Comment by loganfsmyth** [comment]
I remain unconfident that there is any way for us to do this in a good way. Relying on arrow vs normal function differentiation should be avoided.

**Comment by Download** [comment]
Thanks for keeping it open for so long!

**Comment by mgol** [comment]
Note that the upcoming [`Function.prototype.toString` revision](https://tc39.github.io/Function-prototype-toString-revision/) requires proper `toString()` output for classes so Babel will be non-conforming.

It so happens AngularJS detects native classes via `toString()` as (due to legacy design reasons) it's calling regular functions directly and treats classes differently; Babel setting proper `toString()` output would help here.

**Comment by Download** [comment]
Yeah, there are use case for it. But thinking about making the `toString` 'proper' would actually be that much harder because you would have to replace the actual `toString` with one that simulates what the `toString` of an ES6 constructor *would have* returned... I guess when you get to this level of detail you are going to have to choose between compact, fast, practical and rigorously correct (but at bigger size and less performance).
