### ISSUE TITLE
Add more tests for ignore and only

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5645]
We've got a TODO here: https://github.com/babel/babel/blob/6af8e647114d533c4191653199347921b2f90e40/packages/babel-core/test/config-chain.js#L35

our coverage for general ignore and only behavior is a little lacking.

**Comment by aardito2** [comment]
I am currently working on this.

**Comment by xtuc** [comment]
Good news :+1: You can join our slack (https://slack.babeljs.io/) if you need some help.

**Comment by nish17** [comment]
May I work on this? Or is there anyone already working on this issue?

**Comment by xtuc** [comment]
@aardito2 do you need help? are you blocking on something?

@nish17 We could ask him directly on Slack.

**Comment by aardito2** [comment]
I submitted a PR for this a few months ago that was never merged - https://github.com/babel/babel/pull/5647

I won't have time to work on Babel anymore, so if @nish17 wants to take over this issue that's fine.

**Comment by nish17** [comment]
@loganfsmyth here in this issue what do you mean by "our coverage for general ignore and only behavior is a little lacking." What is coverage?

**Comment by existentialism** [comment]
@nish17 coverage === test coverage, see https://github.com/babel/babel/pull/5647#issuecomment-294972833 as an example of coverage report, and the [contributing docs](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md#running-lintingtests) for how to get the report locally.
