### ISSUE TITLE
transform-es2015-parameters: arguments deoptimized when shadowed in nested function

### ISSUE THREAD

**Issue by jpommerening** [babel/babel#5656]
This is a feature request (I think). Arguments are not optimized if an inner function shadows the name with a parameter (or rest parameters in my case).

### Input Code

```js
const log = (...args) => console.log(...args);

function test_opt(...args) {
  log(...args);
}

function test_deopt(...args) {
  const fn = (...args) => log(...args);
  fn(...args);
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [ "es2015" ]
}
```

### Expected vs. Current Behavior

I'd expect the code to be optimizable to use `.apply( thisArg, arguments )` throughout.
However, in `test_deopt` the outer `...args` gets copied just to be passed into the inner `fn`.
I can verify that the problem disappears if I rename either the `...args` of `test_deopt` or of the `fn` arrow function.

### Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 6.9.5
| npm              | N/A (yarn 0.20.3)
| Operating System | macOS

**Comment by Qantas94Heavy** [comment]
I hope I'm not being stupid, but is this really meant to be "expected"?

[**Test code:**][actual.js]

```js
var y = function (foo, ...bar) {
  var x = function z(bar) {
    bar[1] = 5;
  };
};
```

[**Current "expected" result:**][expected.js]

```js
var y = function (foo) {
  for (var _len2 = arguments.length, bar = Array(_len2 > 1 ? _len2 - 1 : 0), _key2 = 1; _key2 < _len2; _key2++) {
    bar[_key2 - 1] = arguments[_key2];
  }

  var x = function z(bar) {
    bar[1] = 5;
  };
};
```

I would have thought that given the inner `bar` shadows the outer rest `bar`, we wouldn't need to copy the arguments.

[actual.js]: https://github.com/babel/babel/blob/5633e3c4f61f86c9c9563dbf4943f58c1a378234/packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/rest-member-expression-deoptimisation/actual.js
[expected.js]: https://github.com/babel/babel/blob/5633e3c4f61f86c9c9563dbf4943f58c1a378234/packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/rest-member-expression-deoptimisation/expected.js

**Comment by jpommerening** [comment]
Hey @Qantas94Heavy, thanks for pointing that out!
I was under the impression that this was merely an oversight / missing optimization. I didn't know there was actually a test verifying the (arguably) incorrect behavior. I'm as confused as you are that the transform is expected to copy the arguments in the test case you linked.
