### ISSUE TITLE
Babel async bug. 

### ISSUE THREAD

**Issue by xialvjun** [babel/babel#5657]
### Input Code

[REPL LINK](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=function%20delay(time)%20%7B%0A%20%20return%20new%20Promise((resolve%2C%20reject)%3D%3E%7B%0A%20%20%20%20setTimeout(()%3D%3Eresolve()%2C%20time)%3B%0A%20%20%7D)%3B%0A%7D%0A%0A%5B1000%2C2000%2C3000%2C4000%5D.forEach(async%20(time)%20%3D%3E%20%7B%0A%20%20await%20delay(time)%3B%0A%20%20console.log(time)%3B%0A%7D)%0A%0Aconsole.log(%5B100000%5D)%0A)

```js
function delay(time) {
  return new Promise((resolve, reject)=>{
    setTimeout(()=>resolve(), time);
  });
}

[1000,2000,3000,4000].forEach(async (time) => {
  await delay(time);
  console.log(time);
})

console.log([100000])
```

### Expected Behavior
Output: 
```js
Array [100000]    // at 0s
1000  // at 1s
2000  // at 2s
3000  // at 3s
4000  // at 4s
```

> And the Chrome newest version just act like this.

### Current Behavior

Output:
```js
// at 0s
Array [100000]

// at 1s
Array [100000]
1000

// at 2s
Array [100000]
1000
2000

// at 3s
Array [100000]
1000
2000
3000

// at 4s
Array [100000]
1000
2000
3000
4000
```

> I thought the problem is at the function `_asyncToGenerator`.

**Comment by xialvjun** [comment]
Well, I have run this code on nodejs v7, and it act right. So the problem should be in the `regenerator-runtime` polyfill.

```js
"use strict";

function _asyncToGenerator(fn) {
  // just a copy of the babel generated function
  ...
}

function delay(time) {
  return new Promise((resolve, reject)=>{
    setTimeout(()=>resolve(), time);
  });
}

[1000,2000,3000,4000].forEach(_asyncToGenerator(function*(time) {
  yield delay(time);
  console.log(time);
}))

console.log([100000])
```

**Comment by loganfsmyth** [comment]
The function is working fine, if you open the browser console it logs the correct output too, it is the REPLs UI logging that is having issues with duplication.

@yavorsky Looks like this is a regression from the changes here https://github.com/babel/babel.github.io/pull/1225/files#diff-abe23564b3ea7bb6b8680951a5f778d3R567 because we're now always appending to what was there before.

**Comment by yavorsky** [comment]
@loganfsmyth thanks! On it.
