### ISSUE TITLE
JSON.stringify transpiled with babel-plugin-transform-runtime

### ISSUE THREAD

**Issue by brokentone** [babel/babel#5658]
Bug report

When the `transform-runtime` plugin is used (not when only env presets or individual transformations are applied), all calls to `JSON.stringify` get transformed to calls to the core-js JSON stringify wrapper module. This appears to be added back in this PR: https://github.com/babel/babel/pull/2953 with little discussion or detail provided.

It doesn't seem to be anything to do with actual browser / spec support / adherence, in that `JSON` is a solid ES5/5.1 feature, and `JSON.parse` does not get altered in any way.

Digging in deeper on `core-js` it appears that this is needed for some part of Symbol support.

> Also wrapped some methods for correct work with Symbol polyfill.
https://github.com/zloirock/core-js
### Input Code

```js
JSON.parse('{ "one": "1" }');
JSON.stringify({ one: 1 }); 
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "targets": {
        "node": 4
      }   
    }]  
  ],  
  "plugins": [
    "transform-runtime"
  ],  
}
```

### Expected Behavior

No transforming.

```js
JSON.parse('{ "one": "1" }');
JSON.stringify({ one: 1 }); 
```

### Current Behavior

Brings in a reference to core-js runtime:

```
'use strict';

var _stringify = require('babel-runtime/core-js/json/stringify');

var _stringify2 = _interopRequireDefault(_stringify);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

JSON.parse('{ "one": "1" }');
(0, _stringify2.default)({ one: 1 }); 
```

When then the dependencies are resolved (in webpack in this situation), our nice little 2 line module becomes this:

```
/***/ (function(module, exports, __webpack_require__) {

module.exports = { "default": __webpack_require__(2), __esModule: true };

/***/ }), 
/* 1 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var _stringify = __webpack_require__(0);

var _stringify2 = _interopRequireDefault(_stringify);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

JSON.parse('{ "one": "1" }');
(0, _stringify2.default)({ one: 1 }); 


/***/ }), 
/* 2 */
/***/ (function(module, exports, __webpack_require__) {

var core  = __webpack_require__(3)
  , $JSON = core.JSON || (core.JSON = {stringify: JSON.stringify});
module.exports = function stringify(it){ // eslint-disable-line no-unused-vars
  return $JSON.stringify.apply($JSON, arguments);
};

/***/ }), 
/* 3 */
/***/ (function(module, exports) {

var core = module.exports = {version: '2.4.0'};
if(typeof __e == 'number')__e = core; // eslint-disable-line no-undef

/***/ })
/******/ ]); 

```

### Possible Solution

1. It is possible that based on a complete transpile, this feature is not needed at all.
2. Perhaps it could only be applied to symbol runtime functions (which likely are already external in core-js), and this could be entirely removed from this plugin.
3. If it needs to be consistently applied for some reason I'm not groking, it could be necessary for ALL uses of `JSON.stringify` to be wrapped if Symbols are at use anywhere in a module / build -- perhaps this transform could only be activated if Symbols are spotted?

### Context

This isn't *breaking* anything persay for me, but it's one of MANY things in my build chain right now adding extra weight. If I can fix them ALL, then I get a better performing site! Same goes for all users of this plugin.

### Your Environment

Should be irrelevant, but for completeness:

| software         | version(s)
| ---------------- | -------
| babel-cli            |  6.24.1
| babel-plugin-transform-runtime            |  6.23.0
| babel-preset-env            |  1.4.0
| node             | 6.9.5
| npm              | 3.10.10
| Operating System | OS X 10.10.5

**Comment by loganfsmyth** [comment]
Unfortunately Babel just doesn't have enough information to know how to handle cases like this any other way. If you have one file with

```
export default {
  prop: 4,
  *[Symbol.iterator](){
    yield 1234;
  },
}
```
and another with
```
import obj from "./mod";

console.log(JSON.stringify(obj));
```
you need the polyfill in there and Babel doesn't really have any way to know if `obj` has a Symbol property.

**Comment by hzoo** [comment]
You'll probably want https://github.com/babel/babel/issues/3934 to exclude JSON.stringify but otherwise there is no way to know at build time. Otherwise I'd suggest using babel-polyfill and useBuiltIns in https://github.com/babel/babel-preset-env but that can have similar issues

**Comment by chrisjyap** [comment]
so we ran into this problem too. one quick workaround that we ended up doing was window.JSON.stringify

**Comment by Daniel-Khodabakhsh** [comment]
Tried window.JSON.stringify but babel gets to that too.

Isn't this actually a broken implementation of JSON.stringify?

`JSON.stringify({test:[{one: "2"}]})`
Outputs: `'{"test":"[{\"one\": \"2\"}]"}'`
instead of: `'{"test":"[{"one": "2"}]"}'`

Looks like extra escaping is taking place.

**Comment by nicolo-ribaudo** [comment]
Which babel version are you using?

With Babel 7, that code is transpiled to
```js
var _JSON$stringify = require("@babel/runtime/core-js/json/stringify");

_JSON$stringify({
  test: [{
    one: "2"
  }]
});
```
(https://runkit.com/embed/174iq457416o)

Which logs the correct output (without the quotes around the array):
```
"{\"test\":[{\"one\":\"2\"}]}"
```
(https://runkit.com/embed/u7byn631ku0d)

**Comment by Daniel-Khodabakhsh** [comment]
@nicolo-ribaudo Thanks for your reply,
I'm using Babel 6.
I later realised that the array was having JSON.stringify recursively applied to it and wrote a bug. I just updated original my comment now.
