### ISSUE TITLE
[npm] Prerelease versions should not be tagged as latest

### ISSUE THREAD

**Issue by SystemParadox** [babel/babel#5661]
I install babel from npm and get this:

```
> npm install babel-preset-es2015
├── babel-preset-es2015@7.0.0-alpha.9
```

This is not what I was expecting. Please can we make sure that prerelease versions are not tagged as `latest`, so that only stable versions get installed by default?

In many ways this is due to silly default behaviour from npm (see https://github.com/npm/npm/issues/13248). It automatically updates the `latest` tag whene you `npm publish`, so you would have to `npm publish --tag next` or something.

Thanks.

**Comment by loganfsmyth** [comment]
`latest` is `6.24.1`?
```
$ npm dist-tags ls babel-preset-es2015
latest: 6.24.1
next: 7.0.0-alpha.9
```

**Comment by SystemParadox** [comment]
Aha! It turns out that this is partly sinopia's fault (a local npm caching server). When accessed directly from npm the tags are indeed correct.

Thanks very much for your help, that was exactly what I needed to realise what was going on.

**Comment by loganfsmyth** [comment]
Cool!
