### ISSUE TITLE
ignore not work again in package.json and .babelrc

### ISSUE THREAD

**Issue by cula** [babel/babel#5664]
folder cannot be ignored by using 'ignore' config in package.json or .babelrc. But --ignore works in the command line. Babel version is 6.24.0.

The above happend on [T6726](https://github.com/babel/babel/issues/3789) and should have been fixed at [ ignore config option](https://github.com/babel/babel/pull/3644). 

However, it happened again

**Comment by hzoo** [comment]
https://github.com/babel/babel/pull/4708#issuecomment-292824191

It's fixed in 7.x (alpha atm)
