### ISSUE TITLE
babelrc.js exporting a function which accepts an environment

### ISSUE THREAD

**Issue by k15a** [babel/babel#5665]
Hey,

webpack introduced a new way to change the config with version 2. You can now export a function which will be called with an [environment](https://webpack.js.org/configuration/configuration-types/#exporting-a-function-to-use-env). In regards of the [deprecation of the env option](https://github.com/babel/babel/issues/5276) and the [new  `babelrc.js` file](https://github.com/babel/babel/pull/4892) I could imagine that Babel@8 could benefit of such a feature too.

Basically you can pass environments into the config with cli arguments for example:
```
babel src --out-dir lib --env.node --env.modules
```
The `babelrc.js` file will export a function which will be called with the environment:
```js
module.exports = function config(env) {
  return {
    presets: [
      ['env', {
        modules: env.modules,
        node: env.node,
      }]
    ]
  }
}
```

One thing that needs to be figured out is how to pass an environment with `babel-loader` or `rollup-plugin-babel`.

**Comment by SpainTrain** [comment]
> One thing that needs to be figured out is how to pass an environment with babel-loader or rollup-plugin-babel.

With webpack, I think you could do

```js
const babelrc = require('./babelrc.js')
...
                test: /\.js$/,
                use: {
                    loader: 'babel-loader',
                    options: Object.assign({},
                        {babelrc: false},
                        babelrc(env),
                    ),
```

though I agree first class support is a nice-to-have

**Comment by loganfsmyth** [comment]
In Babel 7.x you can do

    module.exports = function config(api) {
      const env = api.env();

and you can pass `envName: "foo"` programmatically or `--env-name foo` on the CLI and toggle various config behaviors based on that.

Not sure we should go beyond that since it makes caching a lot harder.
