### ISSUE TITLE
'this' in global context converted to 'undefined'

### ISSUE THREAD

**Issue by ThomasBrierley** [babel/babel#5668]
Using https://babeljs.io/

```JavaScript
this
````
is converted into:
```JavaScript
undefined;
````

Is this a bug? or is there some way of configuring babel to not mess with ```this``` in the global context.

I'm trying to use babel in my build for browser components but this is breaking Snap.svg (which doesn't actually use ES6) because it has an IIFE which passes ```this``` like so:

```JavaScript
(function (glob) {
    // stuff
})(this);
```

(where ```this``` ends up being ```window``` in the browser)

**Comment by loganfsmyth** [comment]
To avoid this behavior in 6.x, you need to do two things:

1. Set `sourceType: "script"` in your Babel config
2. Pass `modules: false` in the options for the preset you are using, e.g.
    ```
    presets: [
      ['env', {modules: false}], // assuming babel-preset-env
    ],
    ```

**Comment by loganfsmyth** [comment]
Additionally, I don't know about Snap specifically, but generally you should not run Babel on code that you don't own, like `node_modules`, so if that is the real issue, you should configure Babel to skip those.

**Comment by boopathi** [comment]
Related: https://github.com/babel/babili/issues/190

**Comment by ThomasBrierley** [comment]
Thanks @loganfsmyth I will give that a go.

Sorry for not finding the original issue before posting.

> generally you should not run Babel on code that you don't own

I'm running this over all of my browser components, some of these are written in ES6 and some in ES5, picking them out manually is going to get messy.

I presumed that passing ES5 through babel would be ok. Are there reasons for not doing this?

**Comment by ThomasBrierley** [comment]
```modules: false``` works for me, thanks.
