### ISSUE TITLE
Incorrect transpile for rest params with arrow functions.

### ISSUE THREAD

**Issue by jsearles** [babel/babel#5670]
Bug Report which occurs with a combination of rest parameters and arrow functions.

### Input Code

```js
function combine(responses)
{
  return $.when(...responses)
    .then(...args => args);
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "es2015-loose"]
}
```

### Expected Behavior

```js
"use strict";

function combine(responses) {
  var _$;

  return (_$ = $).when.apply(_$, responses).then(function () {
    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return args;
  });
}
```

### Current Behavior

```js
"use strict";

function combine(responses) {
  var _$$when, _$;

  return (_$$when = (_$ = $).when.apply(_$, responses)).then.apply(_$$when, function (args) {
    return args;
  });
}
```
### Possible Solution

Wrapping the rest parameter in parentheses produces the correct results, so i have a workaround. As far as i know the parentheses are not required there. 

I suspect that the arrow transformation needs to occur before the spread transformation, but i did not do any deep analysis. That is just speculation.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 4.4.5
| npm              | 4.0.5
| Operating System | Windows 7

(This can be easily reproduced in the repl at https://babeljs.io/repl/)

**Comment by loganfsmyth** [comment]
You need parens. From

    .then(...args => args);

to

    .then((...args) => args);

what you have now is
    
    .then(...(args => args));

**Comment by jrsearles** [comment]
I see - thanks for the quick response.
