### ISSUE TITLE
babel-register slow in node7 when generating Error stack.

### ISSUE THREAD

**Issue by scinos** [babel/babel#5672]
Bug report.

### Description

When using `babel-register` in node 7.x, it is very slow if the code is generating Errors and using `Error#stack` or `Error.captureStackTrace`. The same code in node 6.x is ~10x faster.

The above scenario is quite common when using `jsdom`. They generate lots of `DOMException` errors, that internally does `Error.captureStackTrace(this, DOMException);` (https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/web-idl/DOMException.js#L29). All those DOMExceptions are silently ignored later, but the performance penalty has already been paid.

I tested this in several versions of node 7.x and 6.x and it is always way slower in node 7.x. I think the error is related to the function `prepareStackTrace` in `source-map-support`: if you transform that function in a no-op, then node 7.x performance is on par with node 6.x

### Input Code
```js
//index.js
require('babel-register');

function MyError (message) {
    Error.call(this, message);
    Error.captureStackTrace(this, MyError);
}

function error() {
    throw new MyError('Fake error')
}

for (let i = 0; i < 100000; i++) {
    try{
        error()
    }catch(e){
   }
}
```

```bash
$ nvm use 6.10.2 && time node index.js
Now using node v6.10.2 (npm v3.10.10)
node index.js  0.96s user 0.05s system 100% cpu 1.007 total

$ nvm use 7.9.0 && time node index.js
Now using node v7.9.0 (npm v4.2.0)
node index.js  11.47s user 0.30s system 100% cpu 11.708 total
```

### Babel Configuration
No configuration specified

### Possible Solution

To be honest, I'm not sure if this should be fixed in `jsdom`, `babel-register` or `source-map-support` (or all of them). Having an option in `babel-register` to disable source maps would definitely help. If nobody is opposed to introduce that option, I can work in a PR to add it.

### Environment

| software         | version(s)
| ---------------- | -------
| babel-register            |  6.24.1
| node             | 7.9.0 and 6.10.2
| Operating System | OSX 10.12.4

**Comment by loganfsmyth** [comment]
Closing in favor of https://github.com/babel/babel/issues/5890, though yours was open first, sorry :)
