### ISSUE TITLE
Destructuring rest parameters

### ISSUE THREAD

**Issue by kopach** [babel/babel#5673]
Based on ES6 documentation from [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/rest_parameters#Destructuring_rest_parameters) it should be possible to destruct rest parameters. For example:

```
function f(...[a, b, c]) {
  return a + b + c;
}
```
or
```
function a (...[, secondParamOnly]) {
  // use second param
}
```

Is there any plugin/version of babel I can use to accomplish this? Thanks.

**Comment by hzoo** [comment]
Parser fixes were in https://github.com/babel/babylon/pull/424 but we need to make sure it transforms correctly.
