### ISSUE TITLE
Array.from is used when transpiling to es5 from es2015

### ISSUE THREAD

**Issue by dotnetCarpenter** [babel/babel#5682]
Choose one: is this a bug report or feature request? **Bug report.**

When I transpile via `babel --presets es2015`, the output has `Array.from' which is es2015 and doesn't work with a es5 engine.

### Input Code

```js
function elem(a, [b,...c]) {
  if(a == b) return true
  if(c.length === 0) return false
  else return elem(a, c)
}
```
_elem_ name is taken from Haskell, it's the equivalent of `Map.has()`.

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=function elem(a%2C [b%2C...c]) {%0A if(a %3D%3D b) return true%0A if(c.length %3D%3D%3D 0) return false%0A else return elem(a%2C c)%0A}&experimental=true&loose=true&spec=false&playground=false&stage=0)

### Babel Configuration (.babelrc, package.json, cli command)

Using babel-preset-es2015 version 6.24.1 - no configuration file.

### Expected Behavior

If I use the es2015-loose preset, I get a result that is much closer to what I expect.

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose&targets=&browsers=&builtIns=false&debug=false&code=function elem(a%2C [b%2C...c]\) {%0A if(a %3D%3D b) return true%0A if(c.length %3D%3D%3D 0) return false%0A else return elem(a%2C c)%0A}&experimental=true&loose=true&spec=false&playground=false&stage=0

```js
function elem(a, _ref) {
  var b = _ref[0],
      c = _ref.slice(1);

  if (a == b) return true;
  if (c.length === 0) return false;else return elem(a, c);
}
```
### Current Behavior

```js
function _toArray(arr) { return Array.isArray(arr) ? arr : Array.from(arr); }

function elem(a, _ref) {
  var _ref2 = _toArray(_ref),
      b = _ref2[0],
      c = _ref2.slice(1);

  if (a == b) return true;
  if (c.length === 0) return false;else return elem(a, c);
}
```
_Obviously `Array.from(arr)` will fail_

### Possible Solution

Perhaps, it's better to use the implementation from es2015-loose preset. Or create a transformation for `Array.from`. I looked through the *packages* directory but I didn't see it and you need it.

### Context

I was just trying to get an idea about how much work, it would take to port my code from es2015 to es5.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 7.8.0
| npm              | 4.6.1
| Operating System | Linux Ubuntu 16.04

**Comment by hzoo** [comment]
Thanks for reporting the issue!

This is intentional, we have a caveats section to describe certain syntax that uses polyfillable methods in http://babeljs.io/docs/usage/caveats/#polyfills.

Maybe read https://github.com/necolas/react-native-web/issues/409#issuecomment-295057475? A similar question. I would use loose mode if you have to but otherwise use the polyfill, or transform-runtime, or don't use that syntax.
