### ISSUE TITLE
[transform-react-inline-elements / docs] Note not in the repo

### ISSUE THREAD

**Issue by Andarist** [babel/babel#5684]
So I've wanted to send a PR for - https://babeljs.io/docs/plugins/transform-react-inline-elements/ with some extra informations regarding the note put at the top of this section, but it is nowhere found in the repo. 

Could u point me out where should I search for this?

**Comment by existentialism** [comment]
@Andarist feel free to make a PR to https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-react-inline-elements.md, thanks!

**Comment by Andarist** [comment]
Oh thanks! that wasnt clear from the docs page as it was redirecting to this repository and its README which was only part of the whole page.

Maybe something could be done about it so it becomes more clear?

**Comment by xtuc** [comment]
The best option is to use the "Edit this page" link on the website.
