### ISSUE TITLE
Custom path to .babelrc or configuration file

### ISSUE THREAD

**Issue by milesj** [babel/babel#5689]
This is a feature request.

After scouring the docs and source code, it seems the path to the `.babelrc` file cannot be customized, or passed as an option on the command line. It currently traverses the file system automatically. This is unfortunate.

I've been working on a personal project that houses all my build tool configuration files in a single re-usable repository: babel, jest, eslint, webpack, etc. Babel is the one tool that doesn't allow the `.babelrc` file path to be customized. I would love to be able to do this: 

```
babel --config ./node_modules/my-repo/babel.js -d ./lib ./src
// OR locally
babel --config ./conf/babel.js -d ./lib ./src
```

**Comment by loganfsmyth** [comment]
Currently your best option for loading another config file would be to make a `.babelrc` in your project with this:

```
{
    extends: "my-repo/babel"
}
```

There's definitely work to be done around our config story moving forward.

**Comment by xtuc** [comment]
You can also add it directly to your package.json to avoid creating a .babelrc file :ok_hand:

**Comment by milesj** [comment]
@loganfsmyth That works. @xtuc Even better, didn't think of that!

Thanks guys. I'll leave this open as a possible 7.0 feature.

**Comment by milesj** [comment]
For reference: https://github.com/milesj/build-tool-config

**Comment by bdwain** [comment]
I have PR open to fix this for babel 6. #6117
