### ISSUE TITLE
Lock down `.mjs` parsing to sourceType: "module"

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5690]
Just a reminder to myself, I landed https://github.com/babel/babel/pull/5624, but we still need to lock down `.mjs` parsing so it is always parsed as module, whereas right now it'll default to `module` but be toggleable based on config params along with `.js`.

**Comment by xtuc** [comment]
Does it affect only babel-register resolver hooks and maybe the CLI?

This seems relatively simple, would you mind adding more informations and someonelse could work on this?

**Comment by hulkish** [comment]
Can you share a short example of when this is an issue?

**Comment by xtuc** [comment]
When Babel is parsing a file with the new `.mjs` extension. It should automatically be a module.

**Comment by hulkish** [comment]
Im not sure i follow.. you mean to assume its commonjs2 format?

**Comment by loganfsmyth** [comment]
The ES6 spec splits JS into two related but separate grammar definitions, with `script`, and `module`.

Babel currently defaults to `module`, but it is configurable based on the `.babelrc`. Like this: https://github.com/babel/babel/blob/c307bbb3a93011dd71ebe2cffe8a6d6ec4b8d20c/packages/babel-core/src/config/option-manager.js#L482

So ideally if Babel knows the filename of the file is `.mjs`, it should ignore the `sourceType` value configured in the `.babelrc` and force the value to be `module` even if the user has `{sourceType: "script"}`

**Comment by hulkish** [comment]
@loganfsmyth thanks for explaining.. i only recently learned of mjs format so wanted to understand better.
