### ISSUE TITLE
regenerator src linked to in docs is deprecated

### ISSUE THREAD

**Issue by nebulousdog** [babel/babel#5692]
regenerator src linked to in docs says it is deprecated

https://github.com/facebook/regenerator/blob/master/runtime.js

Found on the following pages:
* https://babeljs.io/docs/plugins/transform-regenerator/
* https://babeljs.io/docs/usage/polyfill/

**Comment by existentialism** [comment]
@nebulousdog thanks for the report, would you like to update the [polyfill](https://github.com/babel/babel.github.io/blob/master/docs/usage/polyfill.md) and transform-[regenerator docs](https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-regenerator.md) on the website?

**Comment by nebulousdog** [comment]
sure, made a quick [PR](https://github.com/babel/babel.github.io/pull/1242).
