### ISSUE TITLE
Transforming basic import into aliased import does not work

### ISSUE THREAD

**Issue by DanielSWolf** [babel/babel#5696]
I'm trying to convert a basic import into an aliased import.

According to the [AST documentation](https://github.com/babel/babylon/blob/master/ast/spec.md#importspecifier), basic and aliased imports are modeled identically. The only difference is that for a basic import, the `imported` and `local` fields contain identical IDs, while they differ for an aliased import. So I wrote plugin code that changes only the `local` ID, while maintaining the `imported` ID. I expected the transformed code to be an aliased import. Instead, it is a basic import which has lost its original imported ID.

### Input Code

Here's my code ([try it out in the AST explorer](https://astexplorer.net/#/gist/266ed196abbd95d77ef9be7c5d0b97a9/1c514feef07b167a4b5b3117b7383e8048e99972)).

```js
function transformImportDeclaration(path) {
  const importSpecifierPaths = path.get('specifiers');
  for (const importSpecifierPath of importSpecifierPaths) {
    const node = importSpecifierPath.node;
    const id = node.local;
    node.local = path.scope.generateUidIdentifier(id.name);
  }
}

export default function (babel) {
  const t = babel.types;

  return {
    visitor: {
      Program(programPath) {
        const declarations = programPath.get('body').filter(path => t.isImportDeclaration(path));
        declarations.forEach(transformImportDeclaration);
      },
    },
  };
}
```

### Babel Configuration (.babelrc, package.json, cli command)

I'm using the online AST explorer, which tells me the following:

* Parser: babylon6-6.16.1
* Transformer: babelv6-6.24.0

### Expected Behavior

This line:

```js
import { member } from "module-name";
```

should be transformed into this:

```js
import { member as _member } from "module-name";
```

### Current Behavior

Instead, the line is transformed into this:

```js
import { _member } from "module-name";
```
The basic import isn't converted to an aliased import. Instead, it stays a basic import, which now points to the wrong export. I don't understand why this is, because the `imported` ID of the AST still contains the original ID (`"member"`, in this case).

### Your Environment

I'm using the online AST explorer, see above.

**Comment by hzoo** [comment]
There's some kind of bug related to the fact that for `import { member } from "module-name";` the local/imported is the same identifier and it's not adding (or printing) it correctly.

Using replaceWith will work though. http://astexplorer.net/#/gist/2f3a941a44b3ef670b238be430fd4ce6/aec7a918238a6916a1ef2f940ddd415683ec76d3

**Comment by DanielSWolf** [comment]
Thank you for your answer! Your code not only shows me how work around the problem; I also learned that there's a `t.clone` function. :smile:

**Comment by loganfsmyth** [comment]
@benjamn Is this an issue with Recast potentially? Not sure how it decides when to render the `as foo` part and when not too, but this seems to print okay locally in my test.

**Comment by nicolo-ribaudo** [comment]
This works in Babel 7: https://astexplorer.net/#/gist/2f3a941a44b3ef670b238be430fd4ce6/6542646dbc272a3e4da277ebd00e471666635139
