### ISSUE TITLE
react v15.5.4 warning

### ISSUE THREAD

**Issue by 39Er** [babel/babel#5705]
I used babel-preset-react,but it  shows the follow warning:

> react.js:3287
> 
>  Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
> 
> Warning: LazyRenderBox: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in `replacement.

- node.js v4.4.5 

- react v15.5.4

- babel 6.24.0

**Comment by loganfsmyth** [comment]
These warnings are not Babel related, they are just warnings that React itself shows because you are using features that React is changing.

**Comment by 39Er** [comment]
Oh,I see ,thank U

**Comment by adammunoz** [comment]
@loganfsmyth 

I do think it's related to Babel.

React implements the following check in order to trigger warnings for every access to the `PropTypes` key in the React object:
```Javascript
Object.defineProperty(React, 'PropTypes', {
  get: function() {
    lowPriorityWarning(didWarnPropTypesDeprecated, 'Accessing PropTypes via the main React package is deprecated,' + ' and will be removed in  React v16.0.' + ' Use the latest available v15.* prop-types package from npm instead.' + ' For info on usage, compatibility, migration and more, see ' + 'https://fb.me/prop-types-docs');
    didWarnPropTypesDeprecated = true;
    return ReactPropTypes;
  }
});
```

As you can see below because Babel iterates over all properties in the React object, it reads the `PropTypes` key, triggering the warnings.

```Javascript
function _interopRequireWildcard(obj) {
        if (obj && obj.__esModule) {
            return obj;
        } else {
            var newObj = {};
            if (obj != null) {
                for (var key in obj) {
                    if (Object.prototype.hasOwnProperty.call(obj, key))
                        newObj[key] = obj[key];
                }
            }
            newObj.default = obj;
            return newObj;
        }
    }
```

**Comment by jridgewell** [comment]
This shouldn't be Babel. Try this:

```js
const React = {};
Object.defineProperty(React, 'PropTypes', {
  get: function() {
    throw new Error('PropTypes');
  }
});

function _interopRequireWildcard(obj) {
  if (obj && obj.__esModule) {
    return obj;
  } else {
    var newObj = {};
    if (obj != null) {
      for (var key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key))
          newObj[key] = obj[key];
      }
    }
    newObj.default = obj;
    return newObj;
  }
}

_interopRequireWildcard(React);

**Comment by julienw** [comment]
FTR It's been fixed in https://github.com/babel/babel/pull/6850
