### ISSUE TITLE
transformFromAst with a Node instead of the AST root

### ISSUE THREAD

**Issue by simondel** [babel/babel#5707]
### Input Code
I'm the developer of a mutation testing framework for JavaScript which involves parsing, modifying and generating code. In order to stay up to date with the latest JavaScript features, I've decided to switch to Babel.

Unfortunately, I can't find any API that allows me to generate code based on a Node instead of the entire AST. I created the code below to change `1 + 2` into `1 - 2`:
```TypeScript
import * as _ from 'lodash';
import * as babel from 'babel-core';

class Mutator {
  mutate() {
    const code = `1 / 2; 1 + 2;`;
    let input = babel.transform(code);
    console.log('input:', input.code);

    const ast = input.ast as babel.types.File;
    let mutatedAst = _.cloneDeep(ast) as babel.types.File; //Create a backup that we can use to generate code

    if (ast) {
      let statement = ast.program.body[1];
      if (babel.types.isExpressionStatement(statement)) {
        let expression = statement.expression;
        if (babel.types.isBinaryExpression(expression)) {
          let mutatedNode = _.cloneDeep(statement) as babel.types.ExpressionStatement; // Clone the Node so we don't modify the original object
          ((mutatedNode.expression) as babel.types.BinaryExpression).operator = '-'; // Modify the operator
          mutatedAst.program.body = [mutatedNode]; // Create a Program with only our statement
          let output = babel.transformFromAst(mutatedAst); // Generate the code!
          console.log('output:', output.code);
        }
      }
    }
  }
}

new Mutator().mutate();
```

Would it be possible to do this without emptying the body of the `program`? If would be great if I could call something like `babel.transformFromAst(mutatedNode)`.

**Comment by loganfsmyth** [comment]
You could create a new `File` node with your single node in it, if I'm understanding you properly, e.g.

```
var t = babel.types;
var ast = t.file(t.program([mutatedAst));
```

That said, I don't quite understand what you're trying to do. For instance you're usage of `transform` and `transformFromAst` are a bit strange. I'd expect something more like

```
const code = `1 / 2; 1 + 2;`;

const output = babel.transform(code, {
  plugins: [
    function() {
      return {
        visitor: {
          BinaryExpression(path) {
            if (path.node.operator === "+") path.node.operator = "-";
          }
        },
      }
    },
  ],
});
console.log('input:', input.code);
console.log('output:', output.code);
```

This may be an easier discussion to have on out Slack if you're interested.

**Comment by loganfsmyth** [comment]
Gonna close this since there aren't any clear next steps. Feel free to hop on slack if you have more questions.
