### ISSUE TITLE
[transform-object-rest-spread] incorrect remaining object

### ISSUE THREAD

**Issue by adi1133** [babel/babel#5712]
The following code snippets behave differently, is this working as intended?

### Input Code
Unexpected behaviour:
```js
var obj = { 2: 3, 4: 5 };
var {[2] : first, ...remaining} = obj
console.log('first', first)
console.log('remaining', remaining) //remaining contains first
```

This behaves as expected:
```js
var obj = { 2: 3, 4: 5 };
var {"2" : first, ...remaining} = obj
console.log('first', first)
console.log('remaining', remaining)
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "stage-3"
  ]
}

```

### Expected Behavior
I expect both code snippets to behave identically

### My Environment

| software         | version(s)
| ---------------- | -------
| babel-core            |  6.24.1
| babel-plugin-transform-object-rest-spread | 6.22.0
| node             |  7.9.0
| npm              |  n/a
| yarn              |  0.23.4
| Operating System |  macOS Sierra 10.12.4 (16E195)

**Comment by adi1133** [comment]
Sorry, this seems to be a duplicate of #4196, should I close this issue ?

**Comment by Qantas94Heavy** [comment]
@adi1133 yeah, they seem the same to me -- go ahead and close it.
