### ISSUE TITLE
Provide some documentation for `babel-traverse`

### ISSUE THREAD

**Issue by EmpireWorld** [babel/babel#5715]
Hi.

I have found `babel-traverse` and i don't know how to use it in the first.

But when i searched in the source files i know how to use it. so it could be hard for newbies and noobs because they couldn't find out how to use it from source code.

So provide some **Usage** and **Installation** guide for users. and if is possible provide an **API Documentation**.

Here is an example usage that does not included in `README.md` file:

```javascript
const traverse = require('babel-traverse').default;
const babylon = require('babylon');

let code = /* ... */;
let ast = babylon.parse(code);
traverse(ast, {
    enter(path) {
        console.log(path);
    }
});
```

Wait! what is `path`? i don't know.

[babel-traverse](https://github.com/babel/babel/tree/master/packages/babel-traverse)

If you need help, i can help.

Thanks.

Best Regards.

**Comment by xtuc** [comment]
PR is here #5717
