### ISSUE TITLE
URGENT: update babel-polyfill to coreJS 2.4.1 (sumbol issue)

### ISSUE THREAD

**Issue by malliapi** [babel/babel#5716]
CoreJS 2.4.1 fixes a critical symbol polyfill issue. Please update babel-polyfill dependency :-)

**Comment by loganfsmyth** [comment]
It is currently using `^2.4.0`, so `2.4.1` is already included in that range.

**Comment by malliapi** [comment]
Yes indeed I realised after I opened it. Please feel free to close. :-)
