### ISSUE TITLE
[REPL ?] minify+es2015 preset gives broken code

### ISSUE THREAD

**Issue by georgir** [babel/babel#5719]
Entering some simple code in the REPL, with any pre-es6 preset and minify checkbox produces code referencing undefined Z.
Entered code:
```
let a=[];
for(let Z=0;Z<5;Z++) a[Z]=()=>Z;
```
Resulting broken code:
```
"use strict";for(var a=[],_loop=function(b){a[b]=function(){return b}};5>Z;Z++)_loop(0);
```
Without the minify checkbox, the resulting code seems ok:
```
"use strict";

var a = [];

var _loop = function _loop(Z) {
  a[Z] = function () {
    return Z;
  };
};

for (var Z = 0; Z < 5; Z++) {
  _loop(Z);
}
```
Entering this nonminified correct output as input and then clicking minify produces correct minified version:
```
"use strict";for(var a=[],_loop=function(c){a[c]=function(){return c}},Z=0;5>Z;Z++)_loop(Z);
```
So the issue is not just in the minifier, but in the combination of es6->es5 transform and minification.
The version shown on the REPL page is Babel 6.24.0
Sorry that I can not test this outside of the REPL to say if it's a but only with it or with Babel in general.

**Comment by boopathi** [comment]
There are issues with the minifier when using with `es2015-block-scoping` transforms, you can find these issues here - https://github.com/babel/babili/issues?q=is%3Aissue+is%3Aopen+label%3A%22with+es2015%22 .. 

Closing this as this is not related to babel itself.
