### ISSUE TITLE
let/const scope transform in a loop doesn't pick up on continue inside 'switch'

### ISSUE THREAD

**Issue by EdisonGao** [babel/babel#5725]
Bug Report

### Input Code
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=%20%20const%20entries%20%3D%20%5B%5D%3B%0A%0A%20%20for%20(let%20ii%20%3D%200%3B%20ii%20%3C%20entries.length%3B%20ii%2B%2B)%20%7B%0A%20%20%20%20const%20resource%20%3D%20entries%5Bii%5D%3B%0A%0A%20%20%20%20switch%20('foo')%20%7B%0A%20%20%20%20%20%20case%20'css'%3A%20break%3B%0A%20%20%20%20%20%20default%3A%0A%20%20%20%20%20%20%20%20continue%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20forEachObject(ResourceTimingMetricsEnumJS%2C%20(metric)%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20ts%20%3D%20resource%5Bmetric%5D%3B%0A%20%20%20%20%7D)%3B%0A%0A%20%20%7D&experimental=true&loose=true&spec=false&playground=false&stage=0

### Babel Configuration (.babelrc, package.json, cli command)
I'm just using the repl on babeljs.io,
so, es2015, react, stage-2, babel 6.24.0

### Expected Behavior
Expected the  _loop transform to pick up on the fact that there was a continue inside the switch statement. Since its a function and no longer a for-loop, a continue is illegal syntax. 

Changing the decl on line 4 from const to var solves the issue. 

### Current Behavior
I get a function decl _loop that wraps the loop body, that has a continue in the same place in the switch statement. See line 12. 

### Possible Solution
I see that you can also transform the switch to return 'continue' or something, but I'm not sure why that transform isnt applied in this case. 

For other people coming across this bug, as a workaround, if you can get rid of the lambda, the transform "Just Works"

### Context
I wanted to use const to show that the resource is const in the scope of the loop. To my surprise, another part of the code caused a syntax error. One that wasn't even caught by the syntax checker built into my code editor. I suspected the transform, and stripped away code until I got a small repro

### Your Environment
This repros on the repl on babeljs.io,
so, es2015, react, stage-2, babel 6.24.0

**Comment by mattflix** [comment]
+1

I have encountered this issue too.  Same scenario... loop containing consts and a switch with continue statements.  Babel moves everything into a _loop() function, but leaves continue statements untouched, which become invalid.
