### ISSUE TITLE
Replace "check-es2015-constants" plugin with injected `throw` statements

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5728]
The "check-es2015-constants" plugin is technically not spec-compliant. Nothing about the spec says that Babel should throw an error at compile-time about assigning to a constant binding.

```
(function(){
  const a = "foo";

  if (false) a = "false";

  return a;
})();
```
for instance is perfectly valid code and will run to completion. It's weird and probably won't come up in real code, but I don't see a reason that Babel should be diverging in behavior here.

There are two cases where this plugin currently applies, to my knowledge

1. Assigning to `const` like the example above
2. Assigning to module bindings like `import foo from "foo"; foo = 4;`

In the first case, I'd vote for the block-scoping transform to automatically rewrite every Assignment/UpdateExpression to insert a `throw` into the output code.

In the `import` case, I'd vote for the module transform to be responsible for injecting `throw` statements into the code.

This doesn't strictly need to happen for Babel 7.x, I don't think, since if anything it is relaxing restrictions that are currently _too_ strict, but it would certainly be a nice-to-have.

This is also a reasonably self-contained task, so it would be a good first task for someone to tackle.

**Comment by Qantas94Heavy** [comment]
Would an option to preserve the current behaviour be necessary, or would that be out of scope for Babel (leave it to some other tool)?

**Comment by loganfsmyth** [comment]
ESLint and other tools already do this anyway, so I'd say drop the current behavior entirely.

**Comment by xtuc** [comment]
I'm fine with both behaviors. I think we should keep the compile-time failure (optionally) for online editors like the Babel's REPL.

`throws` in output can also be optional for the same reasons.

**Comment by kaicataldo** [comment]
I'm going to try to take a look at this :)
