### ISSUE TITLE
`babel-register` screws up `babel-polyfill`

### ISSUE THREAD

**Issue by halt-hammerzeit** [babel/babel#5731]
If `require('babel-register')` is called first and then `require('babel-polyfill')` then the `regeneratorRuntime` is not set in the `global` scope.

**Comment by hzoo** [comment]
Not sure we can anything here, maybe we just need some better language in the docs http://babeljs.io/docs/usage/polyfill/#usage-in-node-browserify-webpack - the polyfill should always come before everything?

**Comment by hzoo** [comment]
Ok I updated the language too https://github.com/babel/babel.github.io/commit/3fd040238b1e28533fcfbb34c2a7541659062f48 😄
