### ISSUE TITLE
typeof with variable is redundant

### ISSUE THREAD

**Issue by musicode** [babel/babel#5737]
source

```js
typeof window === 'undefined'
```

output

```js
'use strict';

typeof window === 'undefined';
```

if I change literal to a variable, the output is so redundant.

```js
typeof window === a
```
output

```js
"use strict";

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

(typeof window === "undefined" ? "undefined" : _typeof(window)) === a;
```

**Comment by Qantas94Heavy** [comment]
I don't think this is redundant. In the first case, Babel knows that we are not expecting `typeof` to return `"symbol"`. In the latter case, Babel introduce a check to see if `window` is a polyfilled symbol, as we don't know that we aren't checking `window` is a symbol.

**Comment by hzoo** [comment]
If you don't like the output of http://babeljs.io/docs/plugins/transform-es2015-typeof-symbol you can turn off that specific plugin or use https://github.com/babel/babel-preset-env which might remove it based on your browser
