### ISSUE TITLE
Destructuring is not working

### ISSUE THREAD

**Issue by JWo1F** [babel/babel#5744]
Hello! When I type `if(true) [a, b] = [b, a];` babel insert ; into body.
Just see this: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=function%20x()%20%7B%0A%20%20let%20a%20%3D%201%3B%0A%20%20let%20b%20%3D%202%3B%0A%20%20%0A%20%20%2F%2F%20broken%0A%20%20if(true)%20%5Ba%2C%20b%5D%20%3D%20%5Bb%2C%20a%5D%3B%0A%20%20%0A%20%20%2F%2F%20ok%0A%20%20if(true)%20%7B%0A%20%20%20%20%5Ba%2C%20b%5D%20%3D%20%5Bb%2C%20a%5D%3B%0A%20%20%7D%0A%7D

This breaks my code

**Comment by Qantas94Heavy** [comment]
Obviously you wouldn't normally add an empty statement (`;`) into your code, but this technically isn't invalid (and seems to run fine). Could you explain how this breaks your code?
