### ISSUE TITLE
Feature Request: Specify node version in options.json

### ISSUE THREAD

**Issue by peey** [babel/babel#5752]
### Feature Request

Currently, the code on CI runs on multiple node versions. Some tests may not work on lower node versions. For such tests we need to check for `process.version` in the test and optionally wrap the code in an eval (to avoid SyntaxErrors) ([example](https://github.com/peey/babel/blob/06bd58b40bf75e576f6e26121716d50c2cb336ca/packages/babel-traverse/test/fixtures/parameters/arity/exec.js))

There could be a semver-style key in `options.json` to specify which node versions a particular test is meant to be run on.

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/5765: `minNodeVersion`, thanks @buunguyen!
