### ISSUE TITLE
babel-plugin-transform-es3-property-literals conflicts with babel-plugin-react-css-modules

### ISSUE THREAD

**Issue by pbarbiero** [babel/babel#5754]
Choose one: is this a bug report or feature request?
Bug

More info here: https://github.com/gajus/babel-plugin-react-css-modules/issues/89

### Quick summary:

`babel-plugin-react-css-modules` creates an export mapping like this:

```
var _styleModuleImportMap = {
  'random-0.5302329839985043': {
    'offset': 'Wrapper_offset_1W5nM',
    'full': 'Wrapper_full_U8Ofk'
  }
}; 
```

Once `babel-plugin-transform-es3-property-literals` hits it, it turns into this:

```
var _styleModuleImportMap = {
  '\'random-0.5302329839985043\'': {
    '\'offset\'': 'Wrapper_offset_1W5nM',
    '\'full\'': 'Wrapper_full_U8Ofk'
  }
};
```

### Expected Behavior
Non reserved keys are not touched

### Current Behavior
Non reserved keys output by `babel-plugin-react-css-modules` are not modified

### Possible Solution
N/A

### Context
Airbnb preset includes `babel-plugin-transform-es3-property-literals`, and when moving to CSS modules, we discovered this issue for the run time classes (non runtime classes are not affected, this is specific to `babel-plugin-react-css-modules`

### Your Environment
Node 6.10.2
React 15.5
Latest Babel 6 and associated plugins/presets

I dont have it at the moment, but if necessary I can provide a minimal repo to reproduce this, but https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo will reproduce it if you add 
`babel-plugin-transform-es3-property-literals` to the `.babelrc` file.

**Comment by loganfsmyth** [comment]
Will comment on the other issue. This plugin is getting passed a corrupted AST, so it is doing what it is supposed to do, it just isn't getting passed good data.
