### ISSUE TITLE
class inheritance: uses `super` to access the properties of the parent class

### ISSUE THREAD

**Issue by justjavac** [babel/babel#5769]
The following code:

    class Point {
      getX() {
        console.log(this.x); // C
      }
    }
    
    class ColorPoint extends Point {
      constructor() {
        super();
        this.x = 2;
        super.x = 3;
        console.log(this.x)   // A
        console.log(super.x)  // B
      }
      
      m() {
        this.getX()
      }
    }
    
    const cp = new ColorPoint();
    cp.m();

On chrome 58.0.3029.110 64bit (V8 5.8.283.38), the result is: `3`, `undefined`, `3`.

But on babel 6.24.2, the result is: `2`, `undefined`, `2`.

[![][1]][1]

- Chrome 58.0.3029.110 64bit (V8 5.8.283.38)
- Babel Repl 6.24.2

links:

- https://stackoverflow.com/questions/44149248/es6-inheritance-uses-super-to-access-the-properties-of-the-parent-class
- [gist](https://gist.github.com/justjavac/82494287bb25cd671c781242bce975e1)
- [babel](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=class%20Point%20%7B%0D%0A%20%20getX()%20%7B%0D%0A%20%20%20%20console.log(this.x)%3B%20%2F%2F%20C%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ColorPoint%20extends%20Point%20%7B%0D%0A%20%20constructor()%20%7B%0D%0A%20%20%20%20super()%3B%0D%0A%20%20%20%20this.x%20%3D%202%3B%0D%0A%20%20%20%20super.x%20%3D%203%3B%0D%0A%20%20%20%20console.log(this.x)%20%20%20%2F%2F%20A%0D%0A%20%20%20%20console.log(super.x)%20%20%2F%2F%20B%0D%0A%20%20%7D%0D%0A%20%20%0D%0A%20%20m()%20%7B%0D%0A%20%20%20%20this.getX()%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20cp%20%3D%20new%20ColorPoint()%3B%0D%0Acp.m()%3B%0D%0A)

  [1]: https://i.stack.imgur.com/Y5gkp.png

**Comment by bergus** [comment]
Trying this out in the online repl yields
```js
var _set = function set(object, property, value, receiver) { var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent !== null) { set(parent, property, value, receiver); } } else if ("value" in desc && desc.writable) { desc.value = value; } else { var setter = desc.set; if (setter !== undefined) { setter.call(receiver, value); } } return value; };
```
which looks quite wrong. I haven't looked at the spec yet what the correct behaviour is, but at least `desc.value = value;` doesn't make sense without also calling `Object.defineProperty(receiver, property, desc)`.

**Comment by justjavac** [comment]
@bergus so it is a Babel bug?

**Comment by hax** [comment]
It's really a Babel bug, and I will send a PR soon.
