### ISSUE TITLE
es6.regexp.constructor polyfill moves RegExps onto slow path in V8

### ISSUE THREAD

**Issue by schuay** [babel/babel#5771]
See https://medium.com/@schuay/js-regexp-fast-and-slow-d29d6b77b06 and https://github.com/mishoo/UglifyJS2/issues/1964 for more context.

es6.regexp.constructor (and possibly other regexp polyfills) cause all regexps to take the slow path in V8 by modifying RegExp.prototype.

Repro instructions here: https://github.com/mishoo/UglifyJS2/issues/1964#issuecomment-302287505

### Input Code

```js
require("babel-polyfill");
var str = "fooBar";
console.log( str.split(/(?=[A-Z])/) );
```

### Expected Behavior
RegExp.prototype remains unmodified when possible:

```js
$ d8 --allow-natives-syntax

%DebugPrint(RegExp.prototype)
DebugPrint: 0x3abc271141d1: [JS_OBJECT_TYPE]
 - map = 0x2a00e4885ab9 [FastProperties]
 - prototype = 0x3abc27104631
 - elements = 0x215b0e102241 <FixedArray[0]> [FAST_HOLEY_ELEMENTS]
 - properties = 0x215b0e102241 <FixedArray[0]> {
    #constructor: 0x3abc27113209 <JSFunction RegExp (sfi = 0x215b0e157f71)> (const data descriptor)

// Note the value of the constructor property.
```

### Current Behavior
RegExp.prototype.constructor is set by es6.regexp.constructor.

```js
DebugPrint: 0x2cfbf37141d1: [JS_OBJECT_TYPE]
 - map = 0x17891b2272a1 [FastProperties]
 - prototype = 0x2cfbf3704631
 - elements = 0x3bcb3a802241 <FixedArray[0]> [FAST_HOLEY_ELEMENTS]
 - properties = 0x3bcb3a802241 <FixedArray[0]> {
    #constructor: 0x286c311dcaa9 <JSFunction $RegExp (sfi = 0x13170d6ca299)> (data field 0)

// constructor is the '$RegExp' function.
```

### Environment

See https://github.com/mishoo/UglifyJS2/issues/1964
babel-polyfill@6.23.0 browserify@14.3.0 uglify-js@3.0.7

### Possible fix

Avoid modifying RegExp.prototype if possible.

**Comment by hzoo** [comment]
Thanks for the report and article @schuay! I mentioned in https://twitter.com/left_pad/status/866691698306539520, but at the moment babel-polyfill is basically an alias for  https://github.com/zloirock/core-js (https://github.com/babel/babel/blob/7.0/packages/babel-polyfill/src/index.js) so we can move it to that repo if that's cool

**Comment by zloirock** [comment]
What can I say... It should be an issue only for old V8 versions, it should not be a problem in modern V8, and I don't see any ways for fix it.

**Comment by littledan** [comment]
Created a new bug at https://github.com/zloirock/core-js/issues/306 .

**Comment by schuay** [comment]
@zloirock it also triggers on current chrome / current v8.
Let's close this one and continue discussion on the bug opened in the previous comment.
