### ISSUE TITLE
Destructuring an array of outer scope variables to variables with the same name in an inner scope causes incorrect destructuring

### ISSUE THREAD

**Issue by lozlow** [babel/babel#5772]
## Bug report

When destructuring an array of values using variables defined in an outer scope to variables of the same name in the inner scope, babel will assign the variables in the inner scope the values of that variable in the inner scope (`undefined`).

This is valid javascript and does work when using native destructuring.

### Input Code
REPL Link: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=function%20reverseArgs%20(c%2C%20d)%20%7B%0A%20%20return%20%5Bd%2C%20c%5D%0A%7D%0A%0Aconst%20a%20%3D%201%0Aconst%20b%20%3D%202%0A%0A%7B%0A%20%20const%20%5Ba%2C%20b%5D%20%3D%20reverseArgs(a%2C%20b)%0A%7D%0A%0A%7B%0A%20%20const%20%5Ba%2C%20b%5D%20%3D%20%5Bb%2C%20a%5D%0A%7D

```js
const a = 1
const b = 2

{
  const [a, b] = [b, a]
}
```

### Expected Behavior
```js
var a = 1;
var b = 2;

{
  var _ref = [b, a],
      _a = _ref[0],
      _b = _ref[1];
}
```

### Current Behavior
```js
var a = 1;
var b = 2;

{
  var _ref = [_b, _a],
      _a = _ref[0],
      _b = _ref[1];
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| babel-preset-es2015 | 6.24.1

**Comment by peey** [comment]
I do not think the behavior you are expecting is the correct behavior. The code in the block should result in a `ReferenceError` as it does in Firefox 53 and Chromium 58. You cannot access shadowed bindings from inner scope.

**Comment by buunguyen** [comment]
I agree with @peey. In this case, I suppose Babel should throw error instead of transpiling to invalid code? So it's indeed a bug?

**Comment by peey** [comment]
@buunguyen In that case, should we close this in favor of https://github.com/babel/babel/issues/5728??

**Comment by jridgewell** [comment]
I don't think #5728 applies here. We're not redefining a constant here (because of the new scope), but rather referencing an undeclared variable. Unfortunately, because `const` gets compiled to `var`, the declaration is hoisted and it works.

Rather, this is an issue with block scoping.

**Comment by nicolo-ribaudo** [comment]
I don't think this is an issue, since it throws if you enable the `tdz` options (like for `let x = x;`, it doesn't throw by default).
