### ISSUE TITLE
Paramters transform: add loose option for default params

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5776]
> Ref https://github.com/necolas/react-native-web/pull/490#issuecomment-303998034 cc @necolas

## Input

```js
function bar1 (arg1 = 1) {}
bar1.length // 0
```

## Current
```js
function bar2() {
  var arg1 = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 1;
}
bar2.length // 0
```

## Expected (`loose` option)
```js
function bar3(arg1) {
  if (arg1 === undefined) {
    arg1 = 1;
  }
  // cannot change Function.protoype.length
}
bar3.length // 1
```

## Change
- [ ] Adding a plugin option: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#plugin-options
- [ ] https://github.com/babel/babel/blob/7.0/packages/babel-plugin-transform-es2015-parameters/src/default.js
- [ ] update the readme
- [ ] tests with the loose option

**Comment by peey** [comment]
@hzoo I'm planning to add a "ignoreArity" option to https://github.com/babel/babel/pull/5751 . After it gets merged it's planned to be used by the parameters transform, so this functionality could be easily added there

**Comment by maurobringolf** [comment]
I started working on this, but its more of a sketch up to now. Feedback appreciated!
