### ISSUE TITLE
Numeric Separator: Stage 1

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5783]
Original issue submitted by @hzoo in https://github.com/babel/babylon/issues/538

> Advance Numeric separators proposal to Stage 1 slides (Sam Goto) (@samuelgoto)
cc @ajklein and @domenic

## Info
Proposed at TC39 Meeting: [May 2017](https://github.com/tc39/agendas/blob/master/2017/05.md)
Slides at the meeting: https://docs.google.com/presentation/d/1hcajTemZB2Ruo4EePOyFiva1xpyv5ukKk4aQ0B83dUA/edit#slide=id.p
Proposal Repo: https://github.com/samuelgoto/proposal-numeric-separator

## Example
```js
var thousands = 10_000; // Instead of 10000.
var credit_card_number = 1234_5678_9012_3456; // Instead of 123456789012345.
var social_security_number = 999_99_9999; // Instead of 999999999.
var pi = 3.14_15; // Instead of 3.1415
var bytes = 0b11010010_01101001_10010100_10010010; // Instead of 0b11010010011010011001010010010010.
var 0xCAFE_F00D; // Instead of 0XCAFEF00D.
```

## Basic Rules
- to use the `_` character.
- only one consecutive underscore is allowed.
- only between digits (not allowed at the beginning or end of literals)

## Parser

> Done in https://github.com/babel/babylon/pull/541 by @rwaldron

Plugin: `numericSeparator`
```js
0b0_1_1;
```

```json
{
  "type": "NumericLiteral",
  "extra": {
    "rawValue": 3,
    "raw": "0b0_1_1"
  },
  "value": 3
}
```

## Transform
- if the AST is simple (just the value/raw) would be trivial to remove

https://github.com/babel/babel/wiki/Adding-a-new-Proposal-to-Babel

**Comment by rwaldron** [comment]
@left_pad With a little guidance, I could take this on as well

**Comment by hzoo** [comment]
Does https://github.com/babel/babel/wiki/Adding-a-new-Proposal-to-Babel make sense? I can move it to contributing otherwise.

**Comment by rwaldron** [comment]
I'll try to have a look this weekend—thanks!

**Comment by rwaldron** [comment]
Blocked by https://github.com/babel/babylon/pull/549

**Comment by samuelgoto** [comment]
Just wondering: will this automatically fix the Number() constructor parsing too?
