### ISSUE TITLE
Bug report: Import order changed ?

### ISSUE THREAD

**Issue by nico-onmap** [babel/babel#5789]
I am trying to port an existing ES5 project using ES6 and imports and it seems Babel is moving imports at the top of the file, which breaks my code.

The issue was reported on the [Webpack](https://github.com/webpack/webpack/issues/1343) repo but it seems to be related to Babel.

### Input Code

```js
angular.module('foo', []);
import bar from 'module2';
export default 'fish';
```

### Babel Configuration (.babelrc, package.json, cli command)

I am using babel version 6.24.1 with the following configuration file:

```js
{
    "presets": [
        [
            "es2015",
            {
                "modules": false
            }
        ]
    ]
}
```

### Expected Behavior

The order of the code should not be changed, so the transpiled import should happen after the `angular.module()`

### Current Behavior

The import is moved before the `angular.module()`call. This is the generated code:

```js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_module2_bar__ = __webpack_require__(208);
angular.module('foo', []);
/* harmony default export */ __webpack_exports__["a"] = ('fish');
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             |  7.8.0
| npm              |  4.2.0
| Operating System | Windows 10

**Comment by joshwnj** [comment]
@nico-onmap unless I misunderstood, the module spec indicates that `imports` always appear before statements: https://tc39.github.io/ecma262/#sec-modules

With that in mind, it's correct for babel to move the import above the `angular.module()` call. 

Perhaps an easy way to make it do what you want is to use `require` instead. Eg:

```js
angular.module('foo', []);
const bar = require('module2');
export default 'fish';
```

In this case the order will not be changed.  Does that work?

**Comment by loganfsmyth** [comment]
Indeed. ES6 import statements are processed before the body of the module is executed, so you cannot execute `angular.module` before the import, in the same file. You could make a separate file to do `angular.module` and then import that file beforehand though.
