### ISSUE TITLE
Compiled for...of generating 'ToString' error in Edge

### ISSUE THREAD

**Issue by Octavector** [babel/babel#5794]
Bug Report (my first on GitHub)

I was asked to report this issue by Sven on Twitter

When creating a for...of loop, the compiled code runs perfect on Firefox and Chrome however the error:
`Object doesn't support property or method 'ToString' ` displays in Edge (EdgeHTML 14.14393).

This is my example:
**HTML**
```
<p>This</p>
<p>is</p>
<p>a</p>
<p>test</p>
```
**JavaScript**
```
for(let i of document.querySelectorAll('p')){
  console.log(i.innerText);
}
```

Here it is on JS Bin, fails only in Edge:
http://jsbin.com/legonokija/edit?html,js,console

I first noticed using Babel on Codepen however JS Bin produces the same results.
Hope that helps!

**Comment by xtuc** [comment]
Thanks for this issue.

The generated code uses `document.querySelectorAll('p')[Symbol.iterator]` which is `undefined` on Edge 15.

The transformation assumes that `Symbol.iterator` is preset. I think that a safer way would be to use `Array.from` if the input isn't a real array.

A current workarround is:
```js
for(let i of Array.from(document.querySelectorAll('p'))){
  console.log(i.innerText);
}
```

Tested in Chrome and Edge 15.

**Comment by loganfsmyth** [comment]
I think `babel-polyfill` is supposed to add iterator to `NodeList`. Are you loading that?

**Comment by hzoo** [comment]
Yeah, it's just a polyfill issue: babel-polyfill loads core-js/shim -> https://github.com/zloirock/core-js/blob/8cf8d1e0cba3601fc533f8b27a3966d0d6100daf/shim.js#L184

http://babeljs.io/docs/usage/polyfill
