### ISSUE TITLE
undefined is not a function (evaluating 'String.raw(_templateObject)')

### ISSUE THREAD

**Issue by vincejah** [babel/babel#5799]
I need to use the String.raw\`MyString\` syntax on my react-native application with very long strings.

Bundle generation is ok on both iOS and Android. But when it comes to launching the apk for Android, I systematically get the following error:

undefined is not a function (evaluating 'String.raw(_templateObject)')

My config:
"devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-preset-es2015": "^6.24.1",
    ...
}

and my .babelrc file:
{
"presets": ["react-native"],
"sourceMaps": true
}

**Comment by hzoo** [comment]
if `String.raw` is undefined isn't not defined in the environment being run so you need a polyfill like http://babeljs.io/docs/usage/polyfill/#top
