### ISSUE TITLE
Why do I need to add dependencies babel plugin to my project?

### ISSUE THREAD

**Issue by benweizhu** [babel/babel#5803]
When I add third party react component to my project, I always find out this: 

```
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "/Users/apple/Documents/.../react-z/node_modules/react-slick/.babelrc" at 0, attempted to resolve relative to
```
The third party component that I imported need a babel plugin that I don't need.

I can add to my project, of course, then I add another third party react component, which needs babel-plugin-transform-replace-object-assign.

This quite embarrass me that they do similar things, but I need to add them both to my project to make them work.

```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-object-assign",
    [
      "transform-replace-object-assign",
      "object.assign"
    ]
  ]
}
```

Can someone explain why or show me how to do it in right way?

Thanks a lot.

**Comment by benweizhu** [comment]
Ok, I exclude the node_modules, but I still need to add this two plugin to my project as dependencies.
`module: {
  rules: [
    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      use: {
        loader: 'babel-loader',
      }
    }
  ]
}`

**Comment by hzoo** [comment]
You shouldn't have to use either transform to make object rest spread to work. It already polyfills it and otherwise you would use the `useBuiltIns` option. http://babeljs.io/docs/plugins/transform-object-rest-spread
