### ISSUE TITLE
Add node 8 to travis config

### ISSUE THREAD

**Issue by danez** [babel/babel#5804]
We currently only test babel with node 7,6 and 4. 

We should also test against node 8: 
- [ ] edit `.travis.yml` and add node 8 there. 
- [ ] use node 8 locally and run tests to see if it works (see [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) )
- [ ] if tests fail try to figure out why and fix
- [ ] if not clear why tests fail, ask here or create PR and ask in PR.

We also want to check babel 6.x works with node 8 so this changes can be done for the following branches:
- [ ] master
- [ ] 7.0

---
- [ ] Comment below you are going to do this (for others to know): `"I'd like to work on this for branch <BRANCHNAME>"`
- [ ] Check you are on the correct branch with `git checkout 7.0` or `git checkout master` and then make a branch off of that to PR

**Comment by egoroof** [comment]
I'd like to work on this for branch 7.0

Should node 7 be replaced with node 8 or just add another one?

**Comment by egoroof** [comment]
It's free now :)

**Comment by sarupbanskota** [comment]
@danez from what I can tell, this is still open? I'd like to take it up!

**Comment by harshaiitr** [comment]
@danez if this issue is still open then I will like to work on this and also this will be my first contribution in open source.

**Comment by hzoo** [comment]
@harshaiitr thanks for checking this out! @sarupbanskota ^ already has a PR open though so I would check another issue (better yet would like the PR review)
