### ISSUE TITLE
babel-plugin-transform-object-assign does not follow the spec of Object.assign

### ISSUE THREAD

**Issue by EJTH** [babel/babel#5806]
Choose one: Bug

### Input Code

```js
Object.assign(obj1,obj2,obj3);
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "react", "stage-0"]
}
```

### Expected Behavior
obj1 is merged together with obj2 and obj3

### Current Behavior
obj1 is merged only with obj2

### Possible Solution
Implement the extend function so it can handle multiple extra arguments.

### Context
I just want to create a shallow copy of an obj and merge it with another object like so:
```js
Object.assign({}, originalObject, extensionObject);
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  ???
| node             |  Archaic version ( 0.10 - Not my decision im afraid )
| npm              |  ???
| Operating System |  *nix

**Comment by buunguyen** [comment]
So the input code is `Object.assign(obj1,obj2,obj3);`. What do you expect the output code to be?

The [repl](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0&targets=&browsers=&builtIns=false&debug=false&code=Object.assign(obj1%2Cobj2%2Cobj3)%3B) seems to work as (I would) expect, so I'm not sure what the problem is.

**Comment by forivall** [comment]
@EJTH if you need a fix quickly, and you use lodash, you can use https://github.com/forivall/babel-plugin-transform-object-assign-lodash . Does the problem still occur if you use that instead?

looking at the source of the helper at https://github.com/babel/babel/blob/7.0/packages/babel-helpers/src/helpers.js#L320 , which was last modified for 6.0.0, it should be correct.

**Comment by jridgewell** [comment]
You're using an archaic node version, you'll need to polyfill `Object.assign`. http://babeljs.io/docs/usage/polyfill/

**Comment by forivall** [comment]
@EJTH Actually, the problem is probably that something else is adding a bad `Object.assign` polyfill, and the babel transform is using that instead of its (better) inline polyfill that is used in the transform here.
