### ISSUE TITLE
adding argument in function of false branch in ternary in default arg

### ISSUE THREAD

**Issue by alex-wilmer** [babel/babel#5809]
### Bug

I have an argument in a function that defaults to a ternary where both left and right hand sides are functions. As long as the *right* branch doesn't have an argument in its function, the code compiles, but otherwise not

### Input Code

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=react%2Cstage-0%2Cstage-1&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=false&spec=false&playground=false&code=%2F%2F%20Works!%0A%0Alet%20x1%20%3D%20(%0A%20%20a%20%3D%20true%20%0A%20%20%20%20%3F%20(b)%20%3D%3E%20(%7B%20test%3A%20b%20%7D)%20%0A%20%20%20%20%3A%20()%20%3D%3E%20(%7B%20test%3A%20''%20%7D)%20%2F%2F%20adding%20an%20arg%20here%20crashes%0A)%20%3D%3E%20a%0A%0Aconsole.log(x1()('foo'))%0A%0A%2F%2F%20Doesn't%20Work%20%3A%20(%0A%0A%2F*%20uncomment%20to%20see%20crash%20*%2F%0A%0A%2F%2F%20let%20x2%20%3D%20(%0A%2F%2F%20%20%20a%20%3D%20true%20%20%0A%2F%2F%20%20%20%20%20%3F%20(b)%20%3D%3E%20(%7B%20test%3A%20b%20%7D)%20%0A%2F%2F%20%20%20%20%20%3A%20(v)%20%3D%3E%20(%7B%20test%3A%20''%20%7D)%0A%2F%2F%20)%20%3D%3E%20a%0A%0A%0A

```js
// Works!

let x1 = (
  a = true 
    ? (b) => ({ test: b }) 
    : () => ({ test: '' }) // adding an arg here crashes
) => a

console.log(x1()('foo'))

// Doesn't Work : (

let x2 = (
  a = true  
    ? (b) => ({ test: b }) 
    : (v) => ({ test: '' })
) => a

```

### Expected Behavior

Should be allowed to have any function as RHS of ternary in default argument

### Current Behavior

In the REPL I get `unexpected token`.. in my code where I noticed it I get `Invalid left-hand side in object destructuring`

**Comment by maurobringolf** [comment]
As far as I can tell the given example does not apply es2015 parameter transformation. It seems like the React preset breaks it:

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=react&targets=&browsers=&builtIns=false&debug=false&code=%2F%2F%20Works!%0A%0Alet%20x1%20%3D%20(%0A%20%20a%20%3D%20true%20%0A%20%20%20%20%3F%20(b)%20%3D%3E%20(%7B%20test%3A%20b%20%7D)%20%0A%20%20%20%20%3A%20()%20%3D%3E%20(%7B%20test%3A%20''%20%7D)%20%2F%2F%20adding%20an%20arg%20here%20crashes%0A)%20%3D%3E%20a%0A%0Aconsole.log(x1()('foo'))%0A%0A%2F%2F%20Doesn't%20Work%20%3A%20(%0A%0A%2F%2F%20uncomment%20to%20see%20crash%0A%0Alet%20x2%20%3D%20(%0A%20%20%20a%20%3D%20true%20%20%0A%20%20%20%20%20%3F%20(b)%20%3D%3E%20(%7B%20test%3A%20b%20%7D)%20%0A%20%20%20%20%20%3A%20(v)%20%3D%3E%20(%7B%20test%3A%20''%20%7D)%0A)%20%3D%3E%20a%0A%0A&experimental=true&loose=false&spec=false&playground=false

**Comment by Ltrlg** [comment]
The react plugins enable the “flow” module in babylon, which expects the
colon to introduce a type, I guess.

With “flow“ enabled:
http://astexplorer.net/#/gist/a822e6838eb3be4f634e5aa058282098/
8e2c570eeb623f3ee07e59bcb117dace59dbd869
Disable “flow”, it will work.

**Comment by jridgewell** [comment]
Yup, this is a parser issue.

**Comment by existentialism** [comment]
@babel-bot move to babel/babylon
