### ISSUE TITLE
Cannot assign to read only property 'prototype' of function 'class ... 

### ISSUE THREAD

**Issue by capaj** [babel/babel#5816]
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=env&targets=Node-8&browsers=&builtIns=false&debug=true&code=class%20StubArray%20%7B%0A%7D%0AStubArray.prototype%20%3D%20%5B%5D%3B

### Expected Behavior
it works

### Current Behavior
throws `Cannot assign to read only property 'prototype' of function 'class StubArray {}'`

### Possible Solution
maybe `prototype` should not be read only?

### Context
I encountered it when trying to run mobx es module build in babel. Here: https://github.com/mobxjs/mobx/pull/1027

### Your Environment
node.js 8, babel-cli 6.24.1 (babel-core 6.24.1)

| software         | version(s)
| ---------------- | -------
| npm              |  5.0.1
| Operating System |  ubuntu 17.04

**Comment by hzoo** [comment]
The output you are looking at in the REPL is just a regular class. It's just the native/spec behavior that you can't do it. Babel assumes strict mode so it would act the same in Chrome/Node. So not a bug but a result of adding `"use strict";`

**Comment by capaj** [comment]
@hzoo super fast! You must have much of the ES6 spec well memorized. I guess we'll have to refrain from using such hacks in mobx. Thanks!

**Comment by hzoo** [comment]
@capaj nah I just saw that the output was the same except the use strict, then I tested in Chrome and got the same error 🙂
