### ISSUE TITLE
[Babel 7] _possibleConstructorReturn incorrectly added to lambdas created in constructor

### ISSUE THREAD

**Issue by niieani** [babel/babel#5817]
**Bug report**

Lambda functions created in a constructor of a class that extends another one cause babel to use **_possibleConstructorReturn** _inside_ the lambda. This is a regression (does not happen in Babel 6).

### Input Code

```js
class Parent {}

class Table extends Parent {
  constructor() {
    super()
    this.returnParam = (param) => {
      return param // <-- problem will be in the emit here
    }
  }
}

const table = new Table()

// returnParam should return the input, but returns "this" instead,
// hence the following assertion is false, but should be true!
console.log(
  table.returnParam(false) === false
)
```

### Output code

```js
"use strict";

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Parent = function Parent() {
  _classCallCheck(this, Parent);
};

var Table = function (_Parent) {
  _inherits(Table, _Parent);

  function Table() {
    _classCallCheck(this, Table);

    var _this = _possibleConstructorReturn(this, (Table.__proto__ || Object.getPrototypeOf(Table)).call(this));

    _this.returnParam = function (param) {
      var _ret;

      return _ret = param, _possibleConstructorReturn(_this, _ret);
                           // ^^ this is the problem, 
                           // ^^ instead of returning _ret, babel returns 'this'
    };
    return _this;
  }

  return Table;
}(Parent);

var table = new Table();

// returnParam should return the input, but returns "this" instead,
// hence the following assertion is false, but should be true!
console.log(table.returnParam(false) === false);
```

### Babel Configuration (.babelrc, package.json, cli command)

```shell
cat ./babel-problem.js |./node_modules/.bin/babel --presets env
```

### Expected Behavior
The return value is correct :)

### Current Behavior
The assert fails, all returned values are replaced with `this`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-alpha.12
| babel-preset-env | next
| node             | 8.0.0
| npm              | 5.0.0
| Operating System | OS X 10.12

**Comment by hzoo** [comment]
Hm not sure what would of caused this one.. @loganfsmyth @xtuc ?

History: https://github.com/babel/babel/commits/7.0/packages/babel-plugin-transform-es2015-classes

https://github.com/babel/babel/commit/bf9b4347366cc61e00944ac22cf061bff4b17a19
https://github.com/babel/babel/commit/819056e94a333affe3aadd482b965abab69c48d7
https://github.com/babel/babel/commit/14584c218cd8f61490c31d8bee3de34024fe32d1

**Comment by existentialism** [comment]
Likely from https://github.com/babel/babel/pull/5802, I think we need to not include these returns in https://github.com/babel/babel/blob/7.0/packages/babel-helper-replace-supers/src/index.js#L53?

**Comment by rockmacaca** [comment]
Is this still being investigated? This regression makes is making it pretty tough for me to use classes that use `extends`.

**Comment by nicolo-ribaudo** [comment]
@babel-bot `Has PR`?
