### ISSUE TITLE
[bug] Wrong behavior of `let` and `const`

### ISSUE THREAD

**Issue by SuperPaintman** [babel/babel#5823]
This is a bug request.

### Input Code

[babeljs.io repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=console.log(bomb)%3B%0A%0Alet%20bomb%20%3D%20'boooom!!!'%3B)

```js
console.log(bomb);

let bomb = 'boooom!!!';


console.log(otherBomb);

const otherBomb = 'BOOOOOM!!!!';
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015"]
}
```

### Expected Behavior

```js
'use strict';

console.log(bomb); // ReferenceError: bomb is not defined

var _bomb = 'boooom!!!';


console.log(otherBomb); // ReferenceError: otherBomb is not defined

var _otherBomb = 'BOOOOOM!!!!';
```

### Current Behavior

```js
'use strict';

console.log(bomb); // => undefined

var bomb = 'boooom!!!';


console.log(otherBomb); // => undefined

var otherBomb = 'BOOOOOM!!!!';
```

### Possible Solution

Rename the declared variables, if they are already used in the current scope (like `for (;;) {}`):

```js
for (let i = 0; i < 2; i++) {}

for (let i = 0; i < 2; i++) {}

for (let i = 0; i < 2; i++) {}
```

`=>`

```js
"use strict";

for (var i = 0; i < 2; i++) {}

for (var _i = 0; _i < 2; _i++) {} // like this

for (var _i2 = 0; _i2 < 2; _i2++) {} // and this
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.2
| node             | Chrome Browser
| npm              | (in website repl)
| Operating System | Fedora

**Comment by javislaterlp** [comment]
As far as I know, let and const are hoisted too, but scoped inside a block (not a function like var). I mean, you are calling those variables before they are instantiated, but they are on the same block. Your are not preventing hoisting with let and const.

**Comment by SuperPaintman** [comment]
@javislaterlp
![image](https://cloud.githubusercontent.com/assets/8445785/26780044/4d906448-4a01-11e7-8100-765f1364479e.png)

<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone_and_errors_with_let>

**Comment by hzoo** [comment]
There's a `tdz` option in the block scoping plugin, it's just not by default since it would be really slow (and our implementation has some issues I think). We add some more docs but otherwise would need a PR.

https://twitter.com/left_pad/status/867598953180790785

**Comment by Kovensky** [comment]
Renaming the vars also would not do what you think it would. `var` declarations are valid _and_ initially set to `undefined` at any point inside the same function (or module).

That particular behavior is partially implemented by the `tdz` option.

**Comment by jridgewell** [comment]
It's also pending https://github.com/babel/babel/pull/5741.

**Comment by nicolo-ribaudo** [comment]
Can this issue be closed? The `tdz` option already handles this.
