### ISSUE TITLE
getFunctionParent returns Program if there is no fn parent

### ISSUE THREAD

**Issue by boopathi** [babel/babel#5828]
The current implementation of `path.getFunctionParent` returns either a Function or a Program. 

Source: https://github.com/babel/babel/blob/c142bbc429f1e169e4420efd2ff7d9cadc796b12/packages/babel-traverse/src/path/ancestry.js#L36

The problem is that the name is `getFunctionParent` and when using this API, it is not obvious that it can be a Program and that a workaround like - `p = path.getFunctionParent(); p.isFunction()` checks are required when we want only Function parent.

+ Is this used this way in all plugins that use this API?
+ Can we break this to return only FunctionParent or null if there is no Function parent?

I'm not sure if existing plugins will break because of this change. I don't have a strong use case for breaking this. But do we want to consider this gotcha for 7 or next versions?

**Comment by hzoo** [comment]
Another reason to make a tool that searches github for method usage 😄

**Comment by Andarist** [comment]
PR has been merged some time ago already.
