### ISSUE TITLE
Bug: `**` removes parens where it shouldn’t

### ISSUE THREAD

**Issue by rauschma** [babel/babel#5829]
Choose one: is this a bug report or feature request? Bug

Reproduce via this repo: https://github.com/rauschma/babel-exponentation-bug

---

Invocation:

```
$ npm run --silent b exponentiate.js
"use strict";

console.log(Math.sqrt(3 ** 2 + -5 ** 2));
```

The parentheses around `-5` shouldn’t be removed. Input file `exponentiate.js`:

```
console.log(Math.sqrt(3**2 + (-5)**2));
```

---

Excerpt from `package.json`:

```
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ]
  }
```

---

```
$ node --version
v8.0.0
```

**Comment by hzoo** [comment]
Might be fixed in 7.x alpha, but yeah a bug in the printer then, most likely https://github.com/babel/babel/blob/7.0/packages/babel-generator/src/node/parentheses.js.
