### ISSUE TITLE
NPM errors

### ISSUE THREAD

**Issue by megamindbrian** [babel/babel#5831]
When does it end!?

```js
npm install babel-preset-env
```

ENOENT: no such file or directory, rename 'C:\Users\brian.cullinan\Documents\portal\node_modules\babel-plugin-transform-async-to-generator' -> 'C:\Users\brian.cullinan\Documents\portal\node_modules\.babel-plugin-transform-async-to-generator.DELETE'

**Comment by hzoo** [comment]
Thanks!

> When does it end!?

Starting the issue like that doesn't help at all. Is that only the error you are getting? What version of npm are you using, can you make a repro (does an empty project causes this issue?)

This is also part of https://github.com/babel/babel-preset-env not in this repo.

**Comment by megamindbrian** [comment]
I want you to know that the experience of the user is more important than a
bug in the code.  How are you supposed to know that babel creates a bad
user experience?  I don't think we need a diaspora of language features we
just need 1 to work really well by default.
