### ISSUE TITLE
import.meta: Stage 2

### ISSUE THREAD

**Issue by hzoo** [babel/babel#5832]
Original issue submitted by @hzoo in https://github.com/babel/babylon/issues/539

> import.meta for stage 2 (Domenic Denicola) (@domenic)

## Info
Proposed at TC39 Meeting: [May 2017](https://github.com/tc39/agendas/blob/master/2017/05.md)
Spec Repo: https://github.com/tc39/proposal-import-meta
Spec Text: https://tc39.github.io/proposal-import-meta/

## Example

```js
(async () => {
  const response = await fetch(new URL("../hamsters.jpg", import.meta.url));
  const blob = await response.blob();

  const size = import.meta.scriptElement.dataset.size || 300;

  const image = new Image();
  image.src = URL.createObjectURL(blob);
  image.width = image.height = size;

  document.body.appendChild(image);
})();
```

## Parsing

- Done in : https://github.com/babel/babylon/pull/544

## Transform
- Not sure, maybe webpack should handle? Or in node?

**Comment by FredKSchott** [comment]
To also consider for a transform:
- `import.meta.url = __filename` in Node
- `__filename` & `__dirname` will no longer exist in local scope for Node ESM

**Comment by guybedford** [comment]
Note that file URLs will be used when the Es module system is implemented in Node, so correctly it should probably be along the lines of `import.meta.url = \`file://${isWin ? '' : '/'}${__filename.replace(/\\/g, '/')}\`;`.

Also just to note, the SystemJS transform here is:

```js
console.log(import.meta.url, import.meta.x);
```

```js
System.register([], function (_export, _context) {
  return {
    setters: [],
    execute () {
      console.log(_context.meta.url, _context.meta.x);
    }
  };
});
```

The implementation is all set up for this, so I will aim to PR the transform in due course.

**Comment by Jamesernator** [comment]
Babel itself probably shouldn't add properties to the `import.meta` by default as it's up to hosts how to add that data, it could be useful to have it just replace it with some reference to an object e.g.:

```js
console.log(import.meta.url)
```

Would become:

```js
const __importMeta /* auto-generated of course */ = {}

console.log(__importMeta.url)
```

Specific plugins (e.g. SystemJS, Webpack, etc) could do their own behaviour, but that transform alone is enough to allow for injection of meta-data into the source e.g.:

```js
// Inject automatically by some basic build tool before running babel
import.meta.url = '/lib/foo/bar.js'

// The normal application
console.log(import.meta.url)
```

Would become:

```js
const __importMeta = {}

// The auto-inserted line from the build tool
__importMeta.url = '/lib/foo/bar.js'

// Their code
console.log(__importMeta.url)
```

**Comment by hzoo** [comment]
Yeah I don't think babel should be "adding" anything just whether it made sense for Babel to transform the `import.meta.*` part. If we think it's better suited for webpack and Babel only needs to parse then we can close.

**Comment by jridgewell** [comment]
I think leaving it alone is the best bet, let the bundler take care of it.

**Comment by hzoo** [comment]
Ok, might as well move to the other repo anyway!

@babel-bot move to babel/proposals
