### ISSUE TITLE
only and ignore options do not seem to co-exist

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#5834]
I have this simple setup. I am trying to copy all files from public directory to public-production directory, and I want to transpile all .js files, except for those in the public/lib directory.

```js

let gulp = require('gulp');
let pump = require('pump');
let babel = require('gulp-babel');

gulp.task('compress', function (cb) {
  pump([
      gulp.src('public/**/*'),
      babel({
        ignore: ['public/lib/**/*'],
        only: ['*.js'],
        minified: false,
        plugins: ['transform-remove-console'],
        presets: ['env']
      }),
      gulp.dest('public-production')
    ],
    cb
  );
});
```

As you can see, I have used

```
        ignore: ['public/lib/**/*'],
        only: ['*.js'],
```

one would think that this would ignore anything in public/lib dir and only attempt to tranpile .js files, but in fact, in now attempts to transpile stuff in the public/lib.

It looks like the only option overrides the ignore option, this is PLAIN BAD! These two options should be able to co-exist.

thanks

**Comment by ORESoftware** [comment]
I also tried this:

 ignore: ['public/lib/**/*'],
 only: /\.js$/            // use a regex

didn't work

**Comment by loganfsmyth** [comment]
Yeah, the logic in 6.x is that it uses `only` if `only` is present, and ignores `ignore`.

This has been fixed in our 7.x alpha releases, where both will be applied.

For now you'll need to use one or the other.
