### ISSUE TITLE
babel-generator ignores multiple whitespaces

### ISSUE THREAD

**Issue by JPeer264** [babel/babel#5838]
**feature request**

I am using `babylon` in combination with `babel-generator`. I want to transform some code to AST, modify it and turn it back into code. But when transforming back to code with `babel-generator` it will remove all multiple whitespaces (the ASTs are fine). There is also no option to prevent this behavior. It works for whitespaces before and after comments (just inside of comments).

### Input Code

```js
const babylon = require('babylon');
const generator = require('babel-generator').default;

const code = `
    //       my comment
        var one = 1;
    var two =    2;
`;
const ast = babylon.parse(code);
const generated = generator(ast, {}, code);
```

### Expected Behavior

```
// generated.code (in this specific case input === output)
"
    //       my comment
        var one = 1;
    var two =    2;
"
```
### Current Behavior

```
// generated.code (whitespaces removed)
"
//       my comment
var one = 1;
var two = 2;"
```

### Possible Solution

Add the option `whitespaces: <boolean>` (Defaults: `false`). In the class `Printer` it could add all whitespaces which are needed, if `true`.

### Context

In the project [rcs-core](https://github.com/JPeer264/node-rcs-core) I have to transform JS code via ASTs to replace CSS selectors. I wanted to transform the code, but not "format" it.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-alpha.12
| Babylon | 7.0.0-alpha.13
| node             | v6.10.3
| npm              | v3.10.10
| Operating System | macOS Sierra 10.12.5

**Comment by hzoo** [comment]
babel-generator is used for babel - to compile code down. It is intended to not care about whitespace/quotes/etc. You shouldn't need to read output code (and it will usually be minified anyway). If you want to transform source code, you should use https://github.com/square/babel-codemod (which uses https://github.com/benjamn/recast instead of babel-generator) as the printer to retain formatting.

**Comment by hzoo** [comment]
also @eventualbuddha would you want to move babel-codemod to the babel org? Would be nice to release alpha version of 7.x too 😄

**Comment by jridgewell** [comment]
We In the process of removing this. It's a ton of code and actually hinders performance. https://github.com/babel/babylon/pull/563

**Comment by hzoo** [comment]
Other issues:

https://github.com/babel/babel/issues/5139, https://github.com/babel/babel/issues/5120, https://github.com/babel/babel/issues/4391, https://github.com/babel/babel/issues/4190
