### ISSUE TITLE
preset es2015 to es5, pass "this" as parameter, "this" output to undefined

### ISSUE THREAD

**Issue by iSunlei** [babel/babel#5839]
Choose one: is this a bug report or feature request?

### Input Code

```js
// main.js
define(function(require, exports, module) {
    require("./lib/vue/vue-swipe");       //  require lib with sea.js
    ......
})

// vue-swipe.js
! function (t, e) {
    "object" == typeof exports && "object" == typeof module ? module.exports = e() : "function" == typeof define && define.amd ? define([], e) : "object" == typeof exports ? exports.VueSwipe = e() : t.VueSwipe = e()
}(this, function () {
    ......
});
Why the parameter "this" convert to "undefined" after parse to es5?
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
// gulpfile.js
.pipe(babel({  
      presets: ['es2015']
}));
```

### Current Behavior

```js
// vue-swipe.js
"use strict";
/* This is added the by babel */
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function(obj) {
    return typeof obj;
}
: function(obj) {
    return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
};
/* This is added the by babel  */

! function (t, e) {
    "object" == typeof exports && "object" == typeof module ? module.exports = e() : "function" == typeof define && define.amd ? define([], e) : "object" == typeof exports ? exports.VueSwipe = e() : t.VueSwipe = e()
}(undefined, function () {
    ......
});
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  gulp-babel@6.1.2
| node             |  v6.10.1
| npm              | 3.10.10
| Operating System | window7 x64

**Comment by hzoo** [comment]
http://babeljs.io/faq/#why-is-this-being-remapped-to-undefined-

By default we assume everything is a module (since with es2015 you use the es2015-modules-commonjs transform). You'd need to parse it as script but if you have other questions 

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or ask in another comment below this
