### ISSUE TITLE
Babel doesn't insert necessary ";" if "[" comes in next line after ")"

### ISSUE THREAD

**Issue by squidfunk** [babel/babel#5840]
### Input Code

```js
// works
if ("foo" === "bar")
  throw new TypeError()
console.log("foo")

// doesn't work
if ("foo" === "bar")
  throw new TypeError()
["a", "b"].forEach(item => {
  console.log(item)
})

```

### .babelrc

none, plain Babel.

### Expected Behavior

The statements should not be considered a single statment due to the line break.

``` js
// works
if ("foo" === "bar") throw new TypeError();
console.log("foo"

// doesn't work
);if ("foo" === "bar") throw new TypeError();
[("a", "b")].forEach(item => {
  console.log(item);
});
```

### Current Behavior

The statements are considered to be a single statement.

``` js
// works
if ("foo" === "bar") throw new TypeError();
console.log("foo"

// doesn't work
);if ("foo" === "bar") throw new TypeError()[("a", "b")].forEach(item => {
  console.log(item);
});
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v6.24.1
| node             |  v6.9.5
| npm              |  v4.1.2
| Operating System | Mac OS 10.12.1

**Comment by goto-bus-stop** [comment]
This is correct behaviour, JavaScript doesn't insert a semicolon itself there either.

![image](https://user-images.githubusercontent.com/1006268/26923679-15aa8448-4c43-11e7-8185-fcf5f89cdd2d.png)
This was parsed as `new TypeError()["a", …].forEach(…)` by Chrome.

Lines starting with `[`, `(`, and binary operators are generally parsed as a continuation of the previous line. https://standardjs.com/rules.html#semicolons has some examples of when exactly this happens.

**Comment by squidfunk** [comment]
Oh okay, wasn't aware of that - never encountered it. Thanks!
