### ISSUE TITLE
Exception has occurred: RangeError

### ISSUE THREAD

**Issue by Beven91** [babel/babel#5850]
import "babel-polyfill"
import v8 from "v8";

on nodejs 8.0.0

Exception has occurred: RangeError
RangeError: Wrong length!

**Comment by nicolo-ribaudo** [comment]
Simplified test case:
```js
require("babel-polyfill");
new ArrayBuffer();
```

**Comment by hzoo** [comment]
babel-polyfill is mostly https://github.com/zloirock/core-js so unlikely an issue with babel-polyfill itself? https://github.com/babel/babel/blob/master/packages/babel-polyfill/src/index.js

**Comment by nicolo-ribaudo** [comment]
It's an issue with core-js, I'm sending a pr later

**Comment by hzoo** [comment]
Closing

**Comment by Beven91** [comment]
Thanks a lot!

**Comment by nicolo-ribaudo** [comment]
As a quick workaround (not tested, just an idea), you can try to do something like this:

```js
// array-buffer-fix.js
const OriginalArrayBuffer = global.ArrayBuffer;
global.ArrayBuffer = function ArrayBuffer(length) {
  return new OriginalArrayBuffer(length || 0);
};
```

```js
import "babel-polyfill";
import "./array-buffer-fix"; // must be loaded after babel-polyfill and before anything else
import v8 from "v8";
```

**Comment by Beven91** [comment]
ok,i can use this before core-js released, thanks!

**Comment by Beven91** [comment]
i testd array-buffer-fix.js ：
`
var OriginalArrayBuffer = global.ArrayBuffer;

function ArrayBuffer(length) {
  return new OriginalArrayBuffer(length||0);
}
global.ArrayBuffer = ArrayBuffer;`

`OriginalArrayBuffer.call(this, length || 0);// has a instanceof  Constructor probolem`

**Comment by Beven91** [comment]
I tested array-buffer-fix , there has an **`instance of Constructor`** problem on
`(OriginalArrayBuffer.call(this, length || 0);)` , and i resolve it like this:

```js
var OriginalArrayBuffer = global.ArrayBuffer; 

function ArrayBuffer(length) {
    return new OriginalArrayBuffer(length||0);
}

global.ArrayBuffer = ArrayBuffer;
```
