### ISSUE TITLE
Is babel-register still not recommended for production use?

### ISSUE THREAD

**Issue by bdadam** [babel/babel#5851]
The [Using Babel](https://babeljs.io/docs/setup/#installation) page says (when require hook is clicked) that `babel-register` is
> Not meant for production use

Is this still true?

If so then what is the reason behind it? What are the hidden costs/drawbacks of using `babel-register` in production?

Wouldn't it be worth to document it on the (https://github.com/babel/babel/blob/7.0/packages/babel-register/README.md) as well? Maybe also the [example-node-sever](https://github.com/babel/example-node-server#getting-ready-for-production-use) could be linked to in the documentation to make the transition into production easier. 

Thanks in advance for any responses.

**Comment by nicolo-ribaudo** [comment]
babel-register compiles files at runtime, so it will always make your app slower and memory-consuming.
It is recommended to compile your file before running the server, as described at https://github.com/babel/example-node-server#getting-ready-for-production-use

**Comment by bdadam** [comment]
Is that only a one-time cost only which occurs at the application startup all at once? (With the assumption every module was written with import/export module syntax and there are no dynamic calls to require.)

**Comment by hzoo** [comment]
Yeah there's a small cost, and the caching isn't the best at the moment (a few bugs when the cache key since it doesn't update when you change package.json versions). Some of these problems will be fixed in 7. https://github.com/babel/example-node-server is pretty old

**Comment by wangyun1517** [comment]
@hzoo @bdadam So what's the conclusion？ Still not recommended?

**Comment by nicolo-ribaudo** [comment]
I'd suggest looking at this question on HashNode! https://hashnode.com/ama/with-babel-team-cj7awmk5e00ij54wu6onnyc5w#cj7be3u8e00t554wu7nti3iiu

**Comment by fgarcia** [comment]
According the answer on HashNode it looks like the cost is mostly just on loading. Is that right? And with Babel 7 the only concern is start-up time. Right?

I am confused because everywhere it looks like the compilation step is a simple 1 line command. However in my current case I have a project broken in 27 sub-projects. Transpiling into a new folder will mess up my resolve paths, loose asset files... etc. 

So far I am surviving with a webpack build, but I would love being able to avoid that step and just use babel-register

**Comment by episodeyang** [comment]
@fgarcia I feel you. using webpack build for debugging is terrible for development productivity b/c of the bad error traces. In this regard lack of good source map (from babel) for async function and generators is equally damaging.
