### ISSUE TITLE
iOS 9.x missing transformation / plugin? 

### ISSUE THREAD

**Issue by gkatsanos** [babel/babel#5859]
I just realized the code below works everywhere as expected except iOS 9.x . I know this isn't the support forum, but I was simply wondering if there is a known iOS 9.X (Safari 9.x) problem with the ES2015 preset for which I have to add additional transformations/plugins.

```javascript
import { addClass, removeClass, dataAttr } from '../../common/js/vendor/helpers';
/* eslint-disable no-param-reassign */
const data = [];
const filters = {};
// caching selectors
const clearFiltersBtn = document.querySelector('.js-clear-filters');

// caching & converting NodeList to array
const tableRows = [...document.querySelectorAll('table tbody tr')];
const dropdownLinks = [...document.querySelectorAll('.js-dropdown-link')];
const activeFiltersText = [...document.querySelectorAll('.selection')];
const tableHeaders = [...document.querySelectorAll('th')];

// initializing filters keys taken from table headers
tableHeaders.forEach((element) => {
  filters[$(element).attr('class').toString()] = [];
});

// we save all information as data attributes on the <tr>'s
// so here we parse all <tr>s and save all jobs metadata on the data array
tableRows.forEach((element) => {
  data.push(dataAttr(element));
});

const emptyFilters = function emptyAndCreateInitialFilters() {
  Object.keys(filters).forEach((key) => {
    filters[key] = [];
  });
  activeFiltersText.forEach((element) => {
    element.textContent = 'all';
  });
  clearFiltersBtn.classList.remove('in');
};

const toggleFilter = (key, filterIndex, filterData) => {
  // toggle filter : if it exists add it otherwise remove it
  if (filterIndex === -1) {
    filters[key].push(filterData[key]);
  } else {
    filters[key].splice(filterIndex, 1);
  }
};

const setActiveFiltersText = (key, currentFilter) => {
  if (filters[key].length > 0) {
    [...document.querySelectorAll(currentFilter)].forEach((element) => {
      element.textContent = filters[key].join(', ');
    });
  } else {
    [...document.querySelectorAll(currentFilter)].forEach((element) => {
      element.textContent = 'all';
    });
  }
};

const prepareFilters = function updateTableHeaderFilters(filterData) {
  if (!filterData) {
    emptyFilters();
  } else {
    clearFiltersBtn.classList.add('in');
    Object.keys(filterData).forEach((key) => {
      const filterIndex = filters[key].indexOf(filterData[key]);
      const currentFilter = `th.${key} .selection`;
      toggleFilter(key, filterIndex, filterData);
      setActiveFiltersText(key, currentFilter);
    });
  }
};

const filterRow = function getEnabledFiltersAndReturnValidRows(tableData, activeFilters) {
  const filtersEnabled = Object.keys(activeFilters).filter(element => activeFilters[element].length !== 0);
  return tableData.filter(row => filtersEnabled.every(k => activeFilters[k].indexOf(row[k]) !== -1));
};

const updateDisplay = function showOnlyValidRows() {
  const visibleRows = filterRow(data, filters);
  removeClass(tableRows, 'hidden');
  const hiddenRows = tableRows.filter((row) => !visibleRows.some((job) => Number(job.id) === Number(row.dataset.id)));
  addClass(hiddenRows, 'hidden');
};

const toggleFilterMode = function enableFilteringAndAdaptTable() {
  prepareFilters();
  updateDisplay();
  removeClass(dropdownLinks, 'active');
};


const updateFilters = function adaptActiveFiltersViaDropdown(e) {
  e.stopPropagation();
  const filterData = dataAttr(this);
  this.classList.toggle('active');
  prepareFilters(filterData);
  updateDisplay();
};


clearFiltersBtn.addEventListener('click', toggleFilterMode);
dropdownLinks.forEach((element) => {
  element.addEventListener('click', updateFilters);
});

if (document.getElementById('job-positions') && window.innerWidth > 767) {
  toggleFilterMode();
}

// clicking on an entire row changes the current url
$('tbody tr[data-href]').click((e) => {
  window.location = $(e.currentTarget).data('href');
});
```

My webpack config for babel:

```javascript
          use: [
            {
              loader: 'babel-loader',
              options: {
                presets: [
                  ['es2015', /*{ loose: true, modules: false }*/]
                ]
              }
            },
            'eslint-loader'
          ]
```

No errors thrown in the console.

**Comment by peey** [comment]
What do you mean no errors thrown in console? Where are you getting the errors then? Is it transpiling correctly? 

If it's transpiling correctly and throwing no errors in console but fails to perform the desired function then it might be an error in your logic. It should throw if the compiled code causes error.

It would also help if you could reduce the code you posted to something minimal that can be reproduced

**Comment by reaktivo** [comment]
I saw this at the slack channel, I've been bitten before by trying to use the spread syntax with NodeList, you should ideally switch all your `[...document.querySelectorAll(x)]` into `Array.from(document.querySelectorAll(x))`.

**Comment by gkatsanos** [comment]
> If it's transpiling correctly and throwing no errors in console but fails to perform the desired function then it might be an error in your logic. It should throw if the compiled code causes error.

Indeed, it is transpiling correctly, no errors, but I assume that since it's working correctly _everywhere_ except (mobile) Safari 9.x it's some part of the code that behaves differently in that browser.

What happens is in this part: 

```javascript
const updateDisplay = function showOnlyValidRows() {
  const visibleRows = filterRow(data, filters);
  removeClass(tableRows, 'hidden');
  const hiddenRows = tableRows.filter((row) => !visibleRows.some((job) => Number(job.id) === Number(row.dataset.id)));
  addClass(hiddenRows, 'hidden');
};
```

all rows are hidden .. so, the `const hiddenRows` should be empty but it's not..

**Comment by reaktivo** [comment]
I hope it's not `window.innerWidth > 767`.

**Comment by gkatsanos** [comment]
> I hope it's not window.innerWidth > 767.
nah, this was added only later in a desperate attempt to not run the script at all on mobile devices, but same bug applied to tablets so..

**Comment by nicolo-ribaudo** [comment]
Can you show the transpiled code?

**Comment by gkatsanos** [comment]
@nicolo-ribaudo yes, but it's uglified :( let me try to disable uglification

**Comment by gkatsanos** [comment]
webpackJsonp([1],{

/***/ 10:
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var _helpers = __webpack_require__(39);

/* eslint-disable no-param-reassign */
var data = [];
var filters = {};
// caching selectors
var clearFiltersBtn = document.querySelector('.js-clear-filters');

// caching & converting NodeList to array
var tableRows = Array.from(document.querySelectorAll('table tbody tr'));
var dropdownLinks = Array.from(document.querySelectorAll('.js-dropdown-link'));
var activeFiltersText = Array.from(document.querySelectorAll('.selection'));
var tableHeaders = Array.from(document.querySelectorAll('th'));

// initializing filters keys taken from table headers
tableHeaders.forEach(function (element) {
  filters[$(element).attr('class').toString()] = [];
});

// we save all information as data attributes on the <tr>'s
// so here we parse all <tr>s and save all jobs metadata on the data array
tableRows.forEach(function (element) {
  data.push((0, _helpers.dataAttr)(element));
});

var emptyFilters = function emptyAndCreateInitialFilters() {
  Object.keys(filters).forEach(function (key) {
    filters[key] = [];
  });
  activeFiltersText.forEach(function (element) {
    element.textContent = 'all';
  });
  clearFiltersBtn.classList.remove('in');
};

var toggleFilter = function toggleFilter(key, filterIndex, filterData) {
  // toggle filter : if it exists add it otherwise remove it
  if (filterIndex === -1) {
    filters[key].push(filterData[key]);
  } else {
    filters[key].splice(filterIndex, 1);
  }
};

var setActiveFiltersText = function setActiveFiltersText(key, currentFilter) {
  if (filters[key].length > 0) {
    Array.from(document.querySelectorAll(currentFilter)).forEach(function (element) {
      element.textContent = filters[key].join(', ');
    });
  } else {
    Array.from(document.querySelectorAll(currentFilter)).forEach(function (element) {
      element.textContent = 'all';
    });
  }
};

var prepareFilters = function updateTableHeaderFilters(filterData) {
  if (!filterData) {
    emptyFilters();
  } else {
    clearFiltersBtn.classList.add('in');
    Object.keys(filterData).forEach(function (key) {
      var filterIndex = filters[key].indexOf(filterData[key]);
      var currentFilter = 'th.' + key + ' .selection';
      toggleFilter(key, filterIndex, filterData);
      setActiveFiltersText(key, currentFilter);
    });
  }
};

var filterRow = function getEnabledFiltersAndReturnValidRows(tableData, activeFilters) {
  var filtersEnabled = Object.keys(activeFilters).filter(function (element) {
    return activeFilters[element].length !== 0;
  });
  return tableData.filter(function (row) {
    return filtersEnabled.every(function (k) {
      return activeFilters[k].indexOf(row[k]) !== -1;
    });
  });
};

var updateDisplay = function showOnlyValidRows() {
  var visibleRows = filterRow(data, filters);
  (0, _helpers.removeClass)(tableRows, 'hidden');
  var hiddenRows = tableRows.filter(function (row) {
    return !visibleRows.some(function (job) {
      return Number(job.id) === Number(row.dataset.id);
    });
  });
  (0, _helpers.addClass)(hiddenRows, 'hidden');
};

var toggleFilterMode = function enableFilteringAndAdaptTable() {
  prepareFilters();
  updateDisplay();
  (0, _helpers.removeClass)(dropdownLinks, 'active');
};

var updateFilters = function adaptActiveFiltersViaDropdown(e) {
  e.stopPropagation();
  var filterData = (0, _helpers.dataAttr)(this);
  this.classList.toggle('active');
  prepareFilters(filterData);
  updateDisplay();
};

clearFiltersBtn.addEventListener('click', toggleFilterMode);
dropdownLinks.forEach(function (element) {
  element.addEventListener('click', updateFilters);
});

if (document.getElementById('job-positions') && window.innerWidth > 767) {
  toggleFilterMode();
}

// clicking on an entire row changes the current url
$('tbody tr[data-href]').click(function (e) {
  window.location = $(e.currentTarget).data('href');
});

/***/ }),

/***/ 18:
/***/ (function(module, exports) {

// removed by extract-text-webpack-plugin

/***/ }),

/***/ 39:
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, "__esModule", {
  value: true
});
var addClass = function addClass(elements, className) {
  elements.forEach(function (element) {
    element.classList.add(className);
  });
};

var removeClass = function removeClass(elements, className) {
  elements.forEach(function (element) {
    element.classList.remove(className);
  });
};

var toggleClass = function toggleClass(elements, className) {
  elements.forEach(function (element) {
    element.classList.toggle(className);
  });
};

var dataAttr = function dataAttr(element) {
  return Object.assign({}, element.dataset);
};

exports.addClass = addClass;
exports.removeClass = removeClass;
exports.toggleClass = toggleClass;
exports.dataAttr = dataAttr;

/***/ }),

/***/ 4:
/***/ (function(module, exports, __webpack_require__) {

"use strict";


/* eslint-disable */
/* ========================================================================
 * Bootstrap: dropdown.js v3.3.7
 * http://getbootstrap.com/javascript/#dropdowns
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */

+function ($) {
  'use strict';

  // DROPDOWN CLASS DEFINITION
  // =========================

  var backdrop = '.dropdown-backdrop';
  var toggle = '[data-toggle="dropdown"]';
  var Dropdown = function Dropdown(element) {
    $(element).on('click.bs.dropdown', this.toggle);
  };

  Dropdown.VERSION = '3.3.7';

  function getParent($this) {
    var selector = $this.attr('data-target');

    if (!selector) {
      selector = $this.attr('href');
      selector = selector && /#[A-Za-z]/.test(selector) && selector.replace(/.*(?=#[^\s]*$)/, ''); // strip for ie7
    }

    var $parent = selector && $(selector);

    return $parent && $parent.length ? $parent : $this.parent();
  }

  function clearMenus(e) {
    if (e && e.which === 3) return;
    $(backdrop).remove();
    $(toggle).each(function () {
      var $this = $(this);
      var $parent = getParent($this);
      var relatedTarget = { relatedTarget: this };

      if (!$parent.hasClass('open')) return;

      if (e && e.type == 'click' && /input|textarea/i.test(e.target.tagName) && $.contains($parent[0], e.target)) return;

      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget));

      if (e.isDefaultPrevented()) return;

      $this.attr('aria-expanded', 'false');
      $parent.removeClass('open').trigger($.Event('hidden.bs.dropdown', relatedTarget));
    });
  }

  Dropdown.prototype.toggle = function (e) {
    var $this = $(this);

    if ($this.is('.disabled, :disabled')) return;

    var $parent = getParent($this);
    var isActive = $parent.hasClass('open');

    clearMenus();

    if (!isActive) {
      if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
        // if mobile we use a backdrop because click events don't delegate
        $(document.createElement('div')).addClass('dropdown-backdrop').insertAfter($(this)).on('click', clearMenus);
      }

      var relatedTarget = { relatedTarget: this };
      $parent.trigger(e = $.Event('show.bs.dropdown', relatedTarget));

      if (e.isDefaultPrevented()) return;

      $this.trigger('focus').attr('aria-expanded', 'true');

      $parent.toggleClass('open').trigger($.Event('shown.bs.dropdown', relatedTarget));
    }

    return false;
  };

  Dropdown.prototype.keydown = function (e) {
    if (!/(38|40|27|32)/.test(e.which) || /input|textarea/i.test(e.target.tagName)) return;

    var $this = $(this);

    e.preventDefault();
    e.stopPropagation();

    if ($this.is('.disabled, :disabled')) return;

    var $parent = getParent($this);
    var isActive = $parent.hasClass('open');

    if (!isActive && e.which != 27 || isActive && e.which == 27) {
      if (e.which == 27) $parent.find(toggle).trigger('focus');
      return $this.trigger('click');
    }

    var desc = ' li:not(.disabled):visible a';
    var $items = $parent.find('.dropdown-menu' + desc);

    if (!$items.length) return;

    var index = $items.index(e.target);

    if (e.which == 38 && index > 0) index--; // up
    if (e.which == 40 && index < $items.length - 1) index++; // down
    if (!~index) index = 0;

    $items.eq(index).trigger('focus');
  };

  // DROPDOWN PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this = $(this);
      var data = $this.data('bs.dropdown');

      if (!data) $this.data('bs.dropdown', data = new Dropdown(this));
      if (typeof option == 'string') data[option].call($this);
    });
  }

  var old = $.fn.dropdown;

  $.fn.dropdown = Plugin;
  $.fn.dropdown.Constructor = Dropdown;

  // DROPDOWN NO CONFLICT
  // ====================

  $.fn.dropdown.noConflict = function () {
    $.fn.dropdown = old;
    return this;
  };

  // APPLY TO STANDARD DROPDOWN ELEMENTS
  // ===================================

  $(document).on('click.bs.dropdown.data-api', clearMenus).on('click.bs.dropdown.data-api', '.dropdown form', function (e) {
    e.stopPropagation();
  }).on('click.bs.dropdown.data-api', toggle, Dropdown.prototype.toggle).on('keydown.bs.dropdown.data-api', toggle, Dropdown.prototype.keydown).on('keydown.bs.dropdown.data-api', '.dropdown-menu', Dropdown.prototype.keydown);
}(jQuery);

/***/ }),

/***/ 41:
/***/ (function(module, exports, __webpack_require__) {

"use strict";


__webpack_require__(10);

__webpack_require__(18);

__webpack_require__(4);

/***/ })

},[41]);
//# sourceMappingURL=department.js.map

**Comment by nicolo-ribaudo** [comment]
This is defintely not a babel issue, since your code matches almost 1:1 the output (except for the arrow functions, babel doesn't do almost anything).
You could try to connect Safari to the Mac's debugger, or to place lots of `alert()`s in your code to see what is going on.
Anyway, I'd also suggest to ask the same question on Stackoverflow (or similar sites), with a reduced test case.

**Comment by gkatsanos** [comment]
@nicolo-ribaudo one thing, when I enable "loose" mode, it works. 
(something else breaks but generally logic works)

**Comment by jridgewell** [comment]
Your issue is `dataAttr`. `dataset` doesn't have enumerable properties in Safari 9.

**Comment by gkatsanos** [comment]
Thank you @jridgewell , can you elaborte? the support tables seem ok all the way back to safari 8.. http://caniuse.com/#feat=dataset

**Comment by reaktivo** [comment]
@gkatsanos It means you that in iOS <= 9, `Object.keys(el.dataset)` will always return an empty object. You should replace your `dataAttr` function with:

```
function dataAttr(element) {
  const data = {};
  for(let key in element.dataset) {
    data[key] = element.dataset[key];
  }
  return data;
};
```
