### ISSUE TITLE
"Uncaught ReferenceError: this hasn't been initialised - super() hasn't been called     at _possibleConstructorReturn"  When extending a singleton

### ISSUE THREAD

**Issue by Tatsujinichi** [babel/babel#5862]
bug report

I think that this code should be valid, but it blows up when importing / instantiating this.

```js
import EventEmitter from 'events';

let _instance;

export default class Scene extends EventEmitter {
	constructor() {
		if (_instance) {
			return _instance;
		}
		super();
		_instance = this;
	}
```

.babelrc
```js
{
  "presets" : ["es2015", "react"]
}
```

**Comment by buschtoens** [comment]
Minimal test case. [View in online REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=MYGwhgzhAEBCkFMDC4rQN4F8BQ3SRgBEEAnASwDcEATFA6BADwBcEA7ameCZVGdbNGjAA9mwjMSAV2DMRJABQBKDIKHQSCZlJJtoAIgBGYAF5k2AczD6A3GqEQpAB1LK7QnDmxsEAd2jE5FS0fDZAA)
```js
class BaseClass {}

class DerivedClass extends BaseClass {
  constructor() {
    return "bazinga";
    super();
  }
}

new DerivedClass;
```

**Comment by jridgewell** [comment]
@buschtoens: Thanks for the test case. I made a slight edit to return a object instead (you can't return a non-object in constructors).

**Comment by nicolo-ribaudo** [comment]
Which babel version are you using? That PR has been merged in Babel 7

**Comment by ziofat** [comment]
latest, v6.26.0.
