### ISSUE TITLE
Context not properly set when transpiling binary bind operator (babel-plugin-transform-function-bind)

### ISSUE THREAD

**Issue by johanneslumpe** [babel/babel#5864]
Choose one: is this a bug report or feature request? bug report

When using the bind operator (https://github.com/tc39/proposal-bind-operator) the chained functions are not called with the proper context

(I've searched through the open and closed issues for the bind operator but couldn't find an existing issue for this.)

### Input Code
REPL test case: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code_lz=MYewdgzgLgBA5gUygNQIYBsCuCIwLwwAUAlPgHwwDaAjADQBMtAzALoDcAUKJLALabooASwAO6AJ74i_QaPRCEAJ1owAbhmyk8FdVgQA6XqhGEAHuRjmAVDBnCxCxcU7doMdCDhTd2C65DoBh5whD4IxBwciCgaOCQcAFwJdnLihACsEUnB8UA

Source:
```js
const getValues = () => [1,2,3];
const multiply = (value, multiplier) => value.map(x => x * multiplier);
const log = value => console.log(value)

getValues()
::multiply(5)
::log()

```

Transpiled:
```js
var _context;

const getValues = () => [1, 2, 3];
const multiply = (value, multiplier) => value.map(x => x * multiplier);
const log = value => console.log(value);

(_context = (_context = getValues(), multiply).call(_context, 5), log).call(_context);
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  "plugins": ["transform-function-bind"]
}

```

### Expected Behavior

`[5, 10, 15]` should be logged to the console.
### Current Behavior

The above code throws an error: `Cannot read property 'map' of undefined` due to the missing first argument to `.call()`.

### Possible Solution

The `.call()` calls are missing the context within which the functions should be called. Adding the context within which to call the function as the first argument fixes this:

```js
(_context = (_context = getValues(), multiply).call(undefined, _context, 5), log).call(undefined, _context);
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.25.0, 7.0.0-alpha.12
| node             |  8.1.2
| npm              | 5.0.3
| Operating System | macOS

**Comment by jridgewell** [comment]
The transform operates correctly. The bind operator does not pass in a parameter, it uses `this` context.

```js
const getValues = () => [1,2,3];
function multiply(multiplier) {
  return this.map(x => x * multiplier);
}
function log() {
  console.log(this)
}

getValues()
  ::multiply(5)
  ::log()

**Comment by johanneslumpe** [comment]
@jridgewell Oh I wasn't aware of that. Thanks for the clarification. Knowing this, the operator seems a lot less useful for functional programming now.

**Comment by hzoo** [comment]
I think you'd want https://github.com/gilbert/es-pipeline-operator but it's not proposed as part of TC39

**Comment by johanneslumpe** [comment]
Exactly! I was hoping the bind operator could cover that use case too. Thanks for linking that proposal!
