### ISSUE TITLE
babel-traverse: Where we can find `path` API documentation?

### ISSUE THREAD

**Issue by EmpireWorld** [babel/babel#5868]
As i checked the below example:

https://github.com/babel/babel/tree/master/packages/babel-traverse

I didn't find anything complete. we need a complete documentation about `path` the gives us a complete list of methods and properties.

It is a little example that i found:

```javascript
if (path.isIdentifier({ name: "n" })) {
  path.node.name = "x";
}
```

But we need to know the power of `path` object.

Thanks for this awesome package.

Thanks again.

**Comment by hzoo** [comment]
Sorry we don't really have one atm 😄!

some resources:
- actual babel-traverse source (not a good answer but one way of finding out)
- https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md
- checking plugins in the repo or example plugins online.

**Comment by EmpireWorld** [comment]
Can i make one for this?
