### ISSUE TITLE
[bug] transform-es2015-modules-commonjs incorrect default "strict" behavior

### ISSUE THREAD

**Issue by R1ZEN** [babel/babel#5870]
If we use module transformation like __transform-es2015-modules-commonjs__. [By default strict option is false](https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-es2015-modules-commonjs#strict) and all modules after code generation should not have "use strict" string. But all modules have.

### Input Code
```js
// module.js
export var foo = 'foo';
export var bar = 'bar';
```
```js
// index.js
import {foo, bar} from './module';
```
### Babel Configuration (.babelrc, package.json, cli command)
```json
{
  "plugins": ["transform-es2015-modules-commonjs"]
}
```
### Expected Behavior
```js
// module.js
Object.defineProperty(exports, "__esModule", {
  value: true
});
var foo = exports.foo = 'foo';
var bar = exports.bar = 'bar';
```
```js
// index.js
var _module = require('./module');
```
### Current Behavior
```js
// module.js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var foo = exports.foo = 'foo';
var bar = exports.bar = 'bar';
```
```js
// index.js
'use strict';

var _module = require('./module');
```
### Possible Solution
I think the problem in [transform-strict-mode](https://github.com/babel/babel/blob/7.0/packages/babel-plugin-transform-strict-mode/src/index.js#L7) condition:
```js 
if (state.opts.strict === false || state.opts.strictMode === false) return;
```
and we can change it on:
```js 
if (Boolean(state.opts.strict) === false || Boolean(state.opts.strictMode) === false) return;
```
or
```js
if (!state.opts.strict || !state.opts.strictMode) return;
```

### Environment

| software         | version(s)
| ------------------ | -------
| babel-cli         |  6.24.1
| transform-es2015-modules-commonjs | 6.24.1
| node              | v6.10.3
| npm               | 3.10.10
| Operating System | Fedora 25

**Comment by hzoo** [comment]
Thanks for the issue 🙂! However, there's a difference between the "strict" option and strict mode.

And ES modules are always strict mode ("use strict") so that part is at least correct (having the option is a separate question) - https://stackoverflow.com/a/31685340

**Comment by R1ZEN** [comment]
Thanks for the quick response. :simple_smile:

I understand that ES modules are always strict mode. But when we use strict option is false, all modules don't have strict mode. Maybe the documentation is incorrect explains strict option, because I understand that we should have the same result when:
```json
{
    "plugins": ["transform-es2015-modules-commonjs"]
}
```
and when strict is false
```json
{
    "plugins": [
        ["transform-es2015-modules-commonjs", {
            "strict": false
        }]
    ]
}
```
