### ISSUE TITLE
babel-cli does not copy all files when doing a build

### ISSUE THREAD

**Issue by alexandruluca** [babel/babel#5871]
I am trying to use the following command to transpile my app.

`babel src --out-dir lib --source-maps inline --copy-files`

My .babelrc file looks like this:

```
{
  "presets": ["es2015"],
  "plugins": ["add-module-exports", "transform-decorators"],
  "ignore": [
  ]
}
```

My src directory looks like:
--- index.js
--- app.js
--- com

After running the command, The lib folder contents looks like this:
--- app.js
--- com

Isn't the expectiation that index.js should also be copied? The purpose is to use this version of the app in a production environment and don't transpile it with babel-node

**Comment by hzoo** [comment]
I can't reproduce this? And you shouldn't even need to run copy files because it would compile all js files in the src folder either way?

**Comment by alexandruluca** [comment]
Thanks, I think it was my fault. I started with a smaller project and edited my working project based on that one. Many thanks!
