### ISSUE TITLE
In 2017 we should easily be able to consume node modules that are not pre-compiled.

### ISSUE THREAD

**Issue by resistdesign** [babel/babel#5872]
We should be able to export pure ES6+ and not have to pre-compile dependencies at this point, it's 2017.

There should be a simple switch that says "I KNOW WHAT I'M DOING, PLEASE TRANSPILE/COMPILE EVERYTHING I GIVE YOU" without having to fiddle with `ignore` and `only` regex globs or what have you.

ES6+ IS HERE!
IT IS TIME!

**Comment by egoroof** [comment]
JFYI we still support IE8 :)

**Comment by hzoo** [comment]
This isn't a feature request or anything so closing.

What's the issue with only/regex? Sounds like we just want some better docs on how to handle this better? There's a good amount of discussion in other threads and http://2ality.com/2017/06/pkg-esnext.html, etc. Ideally we could read package.json or something related to the module to know whether to compile (compiling everything in node_modules would be rather slow and unncessary if it is still ES5 anyway)

**Comment by resistdesign** [comment]
@hzoo It's like `dangerouslySetInnerHTML` in React, if you use it it's because you absolutely know what you're doing.

I think `"ignore": false` works when passed in code, but not in `.babelrc`.

Another unfortunate thing is that when you use babel plugins in a node environment, they get parsed and they fail.

I'm trying to setup multiple isomorphic ES6+ library packages without all the *crazy pre-compile boilerplate* repeated in every single one. YOU MUST AGREE THAT IT'S A MASSIVE CODE STENCH to do that, right? C'mon!

**Comment by resistdesign** [comment]
@hzoo Yes, we will keep the slogan! :)

> ES6+ IS HERE!
> IT IS TIME!

**Comment by resistdesign** [comment]
@hzoo There seems to be ABSOLUTELY NOTHING that I can put in `.babelrc` that allows me to transpile even one thing in the `node_modules` folder. THIS CAN'T BE RIGHT!

**Comment by resistdesign** [comment]
@hzoo Nevermind, I just switched all my extensions to `.jsx` and did this in `.babelrc`:
```
"only": [
    "**/*.jsx",
    "node_modules/**/*.jsx"
  ],
```

**Comment by hzoo** [comment]
Great, glad you figured it out

**Comment by resistdesign** [comment]
@hzoo Actually, it was the wrong project, that did NOT really work :P

**Comment by resistdesign** [comment]
If I ignore with `"!/a/full/specific/node_modules/path.jsx"` it will transpile that file BUT then it won't transpile anything in my direct package. THAT has to be a bug!

**Comment by hzoo** [comment]
There actually are some bugs with ignore/only and even using them in combination which are fixed in 7.x (you'll need to update packages to v7.0.0-alpha.12 though like https://github.com/babel/babel/blob/7.0/package.json#L13) or wait for the major release later.

**Comment by resistdesign** [comment]
hmm, interesting, how long until the release, roughly?
