### ISSUE TITLE
[babel-runtime] await is a reserved word failure on asyncGenerator.js

### ISSUE THREAD

**Issue by rosskevin** [babel/babel#5873]
Bug

Webpack compilation now fails.  It appears that `asyncGenerator.js` names a function `await` and that is now a failure with the most recent babel release.  This appears to be generated from a [babel-helpers template.](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L166)

```
/node_modules/babel-runtime/helpers/asyncGenerator.js
Module build failed: SyntaxError: await is a reserved word (122:20)

  120 |       };
  121 |     },
> 122 |     await: function await(value) {
      |                     ^
  123 |       return new AwaitValue(value);
  124 |     }
  125 |   };
```

```
yarn list babel-runtime babel-helpers                                                                                                                                                                                    yarn list v0.24.6
├─ babel-helpers@6.24.1
├─ babel-runtime@6.23.0
└─ es-collections@0.0.2
   └─ babel-runtime@5.8.38
```

### Input Code
Not applicable, failing on babel-runtime itself.

### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": "> 5%"
        },
        "modules": false,
        "debug": true
      }
    ],
    "stage-2",
    "react"
  ],
  "plugins": [
    "react-hot-loader/babel",
    ["relay", {"compat": true, "schema": "./schema.json"}],
    "transform-flow-strip-types",
    ["lodash", { "id": ["lodash", "recompose"] }]
  ],
  "env": {
    "development": {
      "sourceMaps": "inline"
    }
  }
}
```

### Expected Behavior
Doesn't fail on babel-runtime

### Current Behavior
Webpack compile fails as indicated above

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel-core            |  6.25.0
| node             | 8.1.2
| yarn              | 0.24.6
| Operating System | OSX

**Comment by rosskevin** [comment]
From slack:

hzoo
[1:17 PM] 
https://github.com/babel/babel/issues/4952? I thought that was what https://github.com/babel/babel/pull/4954 was doing by @kovensky (edited)

[1:19] 
I guess we didn't release a new version of babel-runtime on 6.x https://unpkg.com/babel-runtime@7.0.0-alpha.12/helpers/asyncGenerator.js

**Comment by athanasiosem** [comment]
I have the same bug. 

When I try to `npm run build` i get 
`SyntaxError: node_modules/babel-runtime/helpers/asyncGenerator.js: await is a reserved word (122:20)`.
 
**Babel Configuration (.babelrc, package.json, cli command)**

`{
  "name": "tempproj",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "babel-preset-env": "^1.5.2",
    "babel-cli": "^6.24.1"
  },
  "devDependencies": {},
  "scripts": {
    "build": "babel src -d lib"
  },
  "author": "",
  "license": "ISC"
}
`

**Expected Behavior**

To transpile directory without errors.

**Current Behavior**

`SyntaxError: node_modules/babel-runtime/helpers/asyncGenerator.js: await is a reserved word (122:20)`.

**Your environment**

- babel-core 6.22.1
- node 7.6.0
- npm 4.1.2
- OS Windows 10

**Comment by rosskevin** [comment]
I'm seeing the same thing on `relay` `master`, @hzoo can we get a maintenance release of `babel-runtime` to solve this?

**Comment by EirikBirkeland** [comment]
I got this exact error today when running `babel index.js ./`.
However, when I simply run `babel index.js` without the `./`, the error does not occur.

@rosskevin  Out of sheer curiosity, can you share the contents of your `npm run build`?

**Comment by rosskevin** [comment]
Now I get this with babili-webpack-plugin.

It is an error that babel-runtime was not released in sync with the other 0.6.25 babel packages.  This is really causing a headache for myself and others.  Any attention to this matter is greatly appreciated.

**Comment by jridgewell** [comment]
We just need to add a function id to the template.

```js
await: function awaiter(value) {
}

**Comment by jridgewell** [comment]
Confirmed this a problem with the latest babel-runtime@6.23.0. I'm not sure how, but our function namer didn't realize `await` is a reserved name (it should name it `_await`).

**Comment by hzoo** [comment]
Ok I'l just release this manually, sorry

**Comment by hzoo** [comment]
Hope this doesn't break it even more..

**Comment by hzoo** [comment]
Should be fixed, let me know

**Comment by tkshnwesper** [comment]
Happens when async/await is used incorrectly.

**Comment by EirikBirkeland** [comment]
I have left the office for the day. I will get back to you tomorrow.

**Comment by purefan** [comment]
@EirikBirkeland how far away is your office? :open_mouth:

**Comment by EirikBirkeland** [comment]
@purefan Beetlejuice
