### ISSUE TITLE
Allow babel to enable a debug mode when running 

### ISSUE THREAD

**Issue by gagoar** [babel/babel#5879]
**Choose one: is this a bug report or feature request?**
Feature

**Provide a general summary of the issue in the title above**
Babel is one of the most important parts of my system, and as such I would like to have more control over what is being loaded when it runs (particularly  when I use it with other tooling indirectly like webpack).
to summarize,  I would like to have the ability to see

- What configuration is being used 
- source of the configuration (directly provided by arguments, rc files, package.json)
- Plugins used to produce the transformations
- configurable output of this log

**Comment by hzoo** [comment]
There is a `DEBUG` mode but it's way too specific and to debug for bugs not configuration.

This is basically the same as https://github.com/babel/babel/issues/2960, so going to close as a duplicate. If you want to help out with that effort that would be great, can add your suggestions in that thread.
