### ISSUE TITLE
module resolving is not working  on babel-node

### ISSUE THREAD

**Issue by kennethmervin01** [babel/babel#5881]
So in my webpack i resolve app folder(inside my app folder are the "container" and "component" folder) 
```code
resolve:{
    modules:[
      path.join(process.cwd(), 'app'),
     path.join(process.cwd(), 'node_modules'),
    ],
    extensions: ['.js', '.jsx']
  },
```
Then I'm using babel node for testing in my server.js
```js
import path from 'path'
import { Server } from 'http'
import Express from 'express'
import React from 'react'
import { renderToString } from 'react-dom/server'
import { match, RouterContext } from 'react-router'
import Routes from 'containers/App/Routes'
```
The error is that node can't find  'containers/App/Routes'  but if I change  server.js like this, it works.
```js
import Routes from './containers/App/Routes'
```
Do I need to add some configuration so that node  also read my  webpack reslove modules??  It's working fine in  webpack devserver

**Comment by jridgewell** [comment]
`resolve` is a webpack feature, so it'd never work with Babel. Seems like there's a babel-plugin if you really want aliases, but it'd be better to just specify the real path.

**Comment by kennethmervin01** [comment]
yes  @jridgewell your right.. I think it will work using babel-plugin-resolver..  but for your suggestion  I can't use their real path.. My react application is already working in webdev server using webpack-resolver. Now I want a server rendering to my app using node.   So  If i will do that,  I need to edit all my react component to specify  each real path....
