### ISSUE TITLE
babel-runtime imports a library that is not permissively licensed.

### ISSUE THREAD

**Issue by krotscheck** [babel/babel#5898]
## Bug report

`babel-runtime` imports `regenerator-runtime`, which is licensed under Facebook's BSD-plus-patent-revocation-clause license.

https://github.com/facebook/regenerator/blob/master/LICENSE
https://github.com/facebook/regenerator/blob/master/PATENTS

### Input Code
```
> yarn why regenerator-runtime

info This module exists because "babel-runtime" depends on it.
info Disk size without dependencies: "44kB"
info Disk size with unique dependencies: "44kB"
info Disk size with transitive dependencies: "44kB"
info Number of shared dependencies: 0
```

### Expected Behavior
Babel and all its dependencies should be permissively licensed.

### Current Behavior
Babel imports a package that is not permissively licensed.

### Context
Using babel is denied by legal.

**Comment by hzoo** [comment]
As an aside, in Babel 7 no packages have babel-runtime as a dependency so regenerator-runtime wouldn't be included in anything other than transform-runtime which you don't have to use. And babel-polyfill is just core-js + regenerator-runtime so you can exclude it yourself. You can also exclude the regenerator plugin in preset-env with https://github.com/babel/babel-preset-env#include-and-exclude-specific-pluginsbuilt-ins.

And regarding the use of generators we can always look into reviving https://github.com/babel/kneden and/or recommending https://github.com/MatAtBread/fast-async but it requires a lot of work and seems like no one will atm.

**Comment by hzoo** [comment]
Can try babel 7 alpha, doesn't use babel-runtime itself.
