### ISSUE TITLE
babel-preset-flow doesn't check for errors??

### ISSUE THREAD

**Issue by sebdelvalle** [babel/babel#5903]
bug

It just strips types but doesn't even check if a type is validly used

### Input Code

```js
let name: string;
name=30;
```

### Babel Configuration (.babelrc, package.json, cli command)

```bash
babel --presets flow a.js
```

### Expected Behavior
Should throw an error about using a `number` instead of the expected type `string`.

### Current Behavior
Just strips the types.

```js
let name;
name = 30;
```
### Possible Solution
Should run an actual flow server and show errors.

### Context
Testing the CLI

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1 (babel-core 6.25.0)
| node             | v5.11.1
| npm              | 3.8.6
| Operating System | Linux Elementary

**Comment by hzoo** [comment]
Yep that's what it does. http://babeljs.io/docs/plugins/preset-flow/#example

It only runs the strip types plugin. It wasn't intended to check, you need to run flow
