### ISSUE TITLE
Generator and decorators are not compatible

### ISSUE THREAD

**Issue by jokerapi** [babel/babel#5904]
https://astexplorer.net/
![2017-06-30 11 07 08](https://user-images.githubusercontent.com/19544032/27719345-4b48ded6-5d84-11e7-85f3-0137f74078e1.png)

**Comment by hzoo** [comment]
It's a parser issue - https://github.com/babel/babylon/issues/13

Will be fixed (https://github.com/babel/babylon/pull/587) in Babel 7.x alpha in the new decorators plugin.
