### ISSUE TITLE
how to add syntax-optional-chaining plugins?

### ISSUE THREAD

**Issue by zongwan** [babel/babel#5905]
babel-plugin-syntax-optional-chaining
https://github.com/babel/babel/tree/7.0/packages/babel-plugin-syntax-optional-chaining

**Comment by hzoo** [comment]
Sorry it's not released yet! (and you want the transform plugin not the syntax one) - been busy, so soon!

**Comment by hzoo** [comment]
https://github.com/babel/babel/releases/tag/v7.0.0-alpha.15

**Comment by thomasyonug** [comment]
@hzoo
 I notice the Installation

`npm install --save-dev babel-plugin-syntax-optional-chaining`

in this package [https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-optional-chaining](url)

Is that correct?

I got one parsing error in my project which babel-x version is 7.0.0-alpha.17 all , and try to use transform-optional-chaining but throw the same error neither.

Look forward to your reply.

**Comment by alessbelli** [comment]
Should I install the entire babel revision? The npm package babel-plugin-transform-optional-chaining does not seem to work, and also seems to be behind (7.0.0 alpha.13.1).
And what's the difference with the syntax plugin? if I install the transform plugin, should I declare it as transform under .babelrc?

**Comment by hzoo** [comment]
@alessbelli the npmjs docs page is always out of date - if you check https://unpkg.com/babel-plugin-transform-optional-chaining@7.0.0-alpha.17/ and the dropdown you'll see there is an alpha.15/17.

**Comment by youngfreezy** [comment]
Hello, this plugin isn't working for me. This is what I have in my `package.json` in `devDependencies`: "babel-plugin-transform-optional-chaining": "^7.0.0-alpha.17", and in my `.babelrc`: ``` "plugins": [
        "transform-class-properties",  
        "transform-object-rest-spread",
        "transform-es2015-template-literals",
        "transform-optional-chaining",
        ["module-alias", [
            { "src": "./src", "expose": "~" },
            { "src": "./src/common", "expose": "common"},
            { "src": "./src/helpers", "expose": "helpers"},
            { "src": "./src/services", "expose": "services"},
            { "src": "./test", "expose": "~test" }
        ]]
    ],```

**Comment by lilijialiang** [comment]
@hzoo can use it with babel 6 ?

**Comment by xtuc** [comment]
@lilijialiang no, optional chaining is also available since Babel 7.

**Comment by lilijialiang** [comment]
I try to use it like this:

package.json
```json
"devDependencies": {
    "babel-core": "^7.0.0-beta.2",
    "babel-plugin-syntax-optional-chaining": "^7.0.0-alpha.17",
  }
```

index.js
```js
const babel = require('babel-core');
const babelPluginChaining = require('babel-plugin-syntax-optional-chaining');

const code = `
const obj = {
    foo: 1,
};
const baz = obj?.foo?.bar;
`

const result = babel.transform( code, {
    plugins: [ babelPluginChaining ],
});

console.log( result.code );
```

why the output is not changed ？

**Comment by hzoo** [comment]
@lilijialiang because the syntax plugin parses it. you just need to use the `transform` plugin.

meaning swap out `babel-plugin-syntax-optional-chaining` with `babel-plugin-transform-optional-chaining`

Seems like people do this a lot, although I'm not sure what we can do to prevent it..

**Comment by jridgewell** [comment]
Maybe change them from plugins? So a new key in the config (`syntaxes`) that'll hold them, with transform plugins still enabling.

**Comment by vjpr** [comment]
I really think `babel-plugin-syntax-optional-chaining` should be back-ported.

Babel 7 is a huge change, and many people are bound to babel@6 via frameworks, libraries, tools.

E.g. ava is tightly bound with babel@6, including some of its dependencies.

**Comment by vjpr** [comment]
@hzoo 

How hard would `babel-plugin-transform-optional-chaining` be to back-port? I can't seem to find it in the code base. Would be interested in doing a PR.

**Comment by swrobel** [comment]
@vjpr https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-optional-chaining

**Comment by Balasnest** [comment]
How can we use optional chaining for babel 6 version?

**Comment by vjpr** [comment]
The parsing code is in babylon, so that would have to be back-ported here: https://github.com/babel/babylon/blob/6.x/src/parser/expression.js

This would be difficult.

Back-porting the transform plugin looks straight-forward though, maybe just some v7 to v6 plugin api changes.

**Comment by hzoo** [comment]
Sorry this is not something we'd be interested in doing. We are trying to release v7 and have tried to help others upgrade etc with an upgrade guide and tooling. We haven't done a v6 backport in a long time. We're still just a volunteer group and it is unreasonable to expect multiple release branches without a team and basically enterprise support. I'd much rather see support in upgrading to v7 which already has support vs. backporting anything especially if it's a feature vs. a bug fix/security issue. This overestimates the amount of effort which includes maintenance not just merging a PR

**Comment by huchenme** [comment]
@hzoo how far are we away from Babel 7 release?

**Comment by xtuc** [comment]
@huchenme you can already use the beta/alpha of Babel 7

**Comment by huchenme** [comment]
I see, what I mean is non beta version
