### ISSUE TITLE
`make test-ci-coverage` & `make test-only` seem to install deps differently

### ISSUE THREAD

**Issue by sarupbanskota** [babel/babel#5910]
Was trying to look at the failing tests on https://github.com/babel/babel/pull/5735, and encountered strange (_at least I find it so_) behaviour in the process:

While on the [currently last commit](https://github.com/babel/babel/pull/5735/commits/3e27d174ee85f24919aed0d78227ba2015dc6117) of https://github.com/babel/babel/pull/5735, if I locally ran `make test-ci-coverage`, I see `dag-map` is present in the `node_modules` within `packages/babel-core`. If I locally ran `make test-only`, it isn't. Needless to say, the test results vary based on this fact.

Haven't investigated anything, just thought to report this in case somebody had pointers, else I'll come back to it.

Node 8 / npm 5

**Comment by sarupbanskota** [comment]
unrelated, but on this build https://travis-ci.org/babel/babel/builds/249831533, I'm not sure why the prettier stuff isn't applicable to all node versions ...?

**Comment by sarupbanskota** [comment]
Looks like I found the answers myself to some degree:

> unrelated, but on this build https://travis-ci.org/babel/babel/builds/249831533, I'm not sure why the prettier stuff isn't applicable to all node versions ...?

Of the four Node versions Travis utilises, just one looks for linting, and the rest run the actual tests. This is sufficient: running the lint on all versions would slow down the build.

> While on the [currently last commit](https://github.com/babel/babel/pull/5735/commits/3e27d174ee85f24919aed0d78227ba2015dc6117) of https://github.com/babel/babel/pull/5735, if I locally ran `make test-ci-coverage`, I see `dag-map` is present in the `node_modules` within `packages/babel-core`. If I locally ran `make test-only`, it isn't. Needless to say, the test results vary based on this fact.

`make test-ci-coverage` runs `make bootstrap`, whereas `make test-only` doesn't. So in the specific event that one pulls a branch that they didn't create, and runs `make test-only` without installing any new dependencies that branch introduces, the `node_modules` isn't gonna be as expected since `make bootstrap` wasn't run.

----------

I guess it's expected that one installs packages again if they switch branches, so there's not much to do to fix this.

Did I analyse correctly? :-)

**Comment by jridgewell** [comment]
Does someone own the build-steps?

**Comment by existentialism** [comment]
@jridgewell not really.

@sarupbanskota IIRC one reason why `test-only` (as its name implies) doesn't run `make build` is I know some workflows (mine included) just run it with `make watch` running simultaneously. I don't know anyone who _wouldn't_ be open to making changes tho.

**Comment by sarupbanskota** [comment]
@existentialism ah, makes sense

basically in my head, if you run `make watch`, then you're "safe", because you do not forget to build. but if you aren't running it, then you're prone to forget and get into a situation where your tests should have failed, but you think they pass since you're only testing off your prev build

lemme know if that's an overkill of a thought though 😅 it did happen to me a couple of times, since I don't normally run `make watch`

**Comment by jridgewell** [comment]
We could add a check that builds if `make watch` isn't running? Basically use a pid and test for it.

**Comment by peey** [comment]
@sarupbanskota This is a common gotcha and I recently documented it in [CONTRIBUTING.md](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md#troubleshooting-tests).

> In case you're locally getting errors which are not on the CI, it may be due to
>  -  Updates in Dependencies: Make sure you run make bootstrap before you run make build or make watch before you run the tests.

I don't think adding `make build` to `make test-only` is a good idea because sometimes I just add new test cases without making any modifications to the source, so it would unnecessarily build the source it doesn't need to.

**Comment by nicolo-ribaudo** [comment]
`make test-ci-coverage` install deps because it runs on CI, while `make build` is meant to be used locally. As @peey mentioned, installing deps every time would just slow doen development.

If you need to install deps and build, you can use `make bootstrap` instead.
