### ISSUE TITLE
Global variable object destructuring broken

### ISSUE THREAD

**Issue by lifeiscontent** [babel/babel#5912]
Choose one: Bug
### Input Code

```js
let foo;
let bar;

// valid
[foo, bar] = [0,1];

// invalid???
{foo, bar} = {foo: 0, bar: 1};
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015"]
}
```

### Expected Behavior
I expect the same behavior as array destructuring.

### Current Behavior
throws an error unless you specify const, let, or var.

### Possible Solution
don't throw an error when not specifying a var, let or const.

### Your Environment
http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=Node-8&browsers=&builtIns=false&debug=false&code_lz=DYUwLgBAZg9jDcAoUkBGBDATkxB6XEAbusAJYAmiA2rDADQQaYC6EAvBFQAx0CMzOfBFIA7YmXIB-aYgDetBkwC-7CPLgAuCD0ZYtvJfCA&experimental=false&loose=false&spec=false&playground=true

**Comment by nicolo-ribaudo** [comment]
You must wrap the object destructuring in parentheses, otherwise the `{` is parsed as the opening brace of a block.

```js
let foo;
let bar;

[foo, bar] = [0,1];

({foo, bar} = {foo: 0, bar: 1});
```

**Comment by jridgewell** [comment]
Yup.
