### ISSUE TITLE
Allow UMD to import directly to global object without wrapper

### ISSUE THREAD

**Issue by rmehlinger** [babel/babel#5921]
### Context
I have a module with a pre-existing UMD export structure that I would like to replicate using Babel. It exports a single object, called `rx`. Following the pattern [here](http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/), if neither AMD nor UMD is present, we simply load our module into a single field of the global object

```
else {
        // Browser globals (root is window)
        root.rx = factory(root._);
    }
```

I am attempting to move this package away from CoffeeScript, and the Babel UMD module seemed like a a simple way to strip out what is essentially boilerplate. 

### Current Behavior
Currently, the browser section of the babel UMD exports looks like this:
```
  // this is the browser globals section
  else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, mod);
    global.rx = mod.exports;
  }
})(this, function (exports, _underscore) {
// ...
  var rx = exports.rx = rxFactory(_underscore2.default);
});
```
And using exports.default doesn't work, as explained [here](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0).

As a result, what could once be accessed in a browser with `window.rx` must now be accessed with the considerably clunkier `window.rx.rx`. This feels like a bit much, considering that I am only exporting a single object.

### Desired Behavior

I would propose adding an `extendGlobal` flag, which would switch the output to something like the following:

```
  // this is the browser globals section
  else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, mod);
    _.extend(global, mod.exports);  // this could of course be rewritten without the reference to _.extend
  }
```

Calling _.extend on the global object is of course potentially dangerous--who knows what will get clobbered--but this shouldn't be default behavior anyway. I'm aware that I could (and probably should) rewrite my code to dispense with the intermediate object, but that would itself be a non-trivial amount of work.

**Comment by jridgewell** [comment]
What you're asking for, you need to rewrite it to use `export default rx` and `import rx from "wherever"`. If you mix ES6 module exports with AMD imports, you're stuck with this. (This was reasoning for this is explained in the [post](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0) you linked to)

**Comment by rmehlinger** [comment]
Yeah, as I came back and thought about it in the morning I decided to just rewrite the package to export its members individually. Thanks!
