### ISSUE TITLE
Flow parser doesn't support async functions with generic output

### ISSUE THREAD

**Issue by kohver** [babel/babel#5928]
### Code
The code looks valid, but `babel-node` throws error.

 Looks like this happens only with `async` and `<T>` combination.

```js
const foo = async <T>() => {};
```

### Error
```
repl: Unexpected token (1:22)
> 1 | const foo = async <T>() => {};
    |                       ^
```

👉 [Babel REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2017%2Creact&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code_lz=MYewdgzgLgBAZiEMC8MCGECeZgwDwAqAfABQCUKRMA3gL4DcQA) (the error)
👉 [Flow REPL](https://flow.org/try/#0MYewdgzgLgBAZiEMC8MCGECeZgwDwAqAfABQCUKRMA3gL4DcQA) (no errors)

### Successful parsed code
without generic
```js
const foo = async () => {};
```
without async
```js
const foo = <T>() => {};
```

From my `package.json`:
```
    "babel-cli": "^6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-flow": "^6.23.0",
```

**Comment by nicolo-ribaudo** [comment]
Hi, this bug is tracked in the parser's repository: babel/babylon#235
