### ISSUE TITLE
Something is calling for ./bin/babel-plugin but there is no such package

### ISSUE THREAD

**Issue by binarykitchen** [babel/babel#5944]
When running Jest tests and having the node-inspector in the background, I can see this weird error: 

```
Node Inspector v1.1.1
Visit http://127.0.0.1:8080/?port=5858 to start debugging.
Access to /Users/michael-heuberger/code/some-project/node_modules/.bin from ResourceTree denied. (Error: ENOENT: no such file or directory, stat '/Users/michael-heuberger/code/some-project/node_modules/.bin/babel-plugin')
```

There is no npm package that would place an `babel-plugin` executable in that bin folder. My environment is:
npm 2.15.5
node 4.4.5
babel-cli + -core 6.24.1
jest-cli 20.0.4

**Comment by jridgewell** [comment]
This isn't a babel issue?

**Comment by binarykitchen** [comment]
no idea, it is asking for `.bin/babel-plugin` which is weird

**Comment by loganfsmyth** [comment]
Without a reproducible example it'll be hard to say. Nothing babel-related has a bin named that.
