### ISSUE TITLE
Incorrect generated import order when a generator/async function is in the same file as babel-polyfill

### ISSUE THREAD

**Issue by niieani** [babel/babel#5946]
**Bug report**

<details>
<summary><b>Input Code</b></summary>

```js
import 'babel-polyfill'

function *generator() {
  yield 1
  yield 2
  yield 3
}

const aGenerator = generator()

// will break in IE 11 or browsers without Symbol support:
for (const a of aGenerator) {
  console.log(a)
}
```
</details>

----

<details>
<summary><b>Output Code</b></summary>

```js
import _regeneratorRuntime from 'babel-runtime/regenerator';

var _marked = [generator].map(_regeneratorRuntime.mark);

import 'babel-polyfill';

function generator() {
  return _regeneratorRuntime.wrap(function generator$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return 1;

        case 2:
          _context.next = 4;
          return 2;

        case 4:
          _context.next = 6;
          return 3;

        case 6:
        case 'end':
          return _context.stop();
      }
    }
  }, _marked[0], this);
}

var aGenerator = generator();

for (var _iterator = aGenerator, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  var a = _ref;

  console.log(a);
}
```

</details>

----

<details>
<summary><b>Babel Configuration (.babelrc, package.json, cli command)</b></summary>

```js
{
  "presets": [
    ["es2015", {"loose": true, "modules": false}],
    "stage-2"
  ],
  "plugins": [
    ["transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": true,
      "moduleName": "babel-runtime"
    }]
  ]
}
```

</details>

----

### Expected Behavior
The `import 'babel-polyfill'` statement should remain on the top of the file. This will ensure that the Symbol polyfill is loaded BEFORE `regenerator-runtime`, because `regenerator` depends on the polyfill being present [at the time of its load](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L17-L20).

### Current Behavior

Currently, `import _regeneratorRuntime from 'babel-runtime/regenerator';` gets placed at the very top of the file, which causes regenerator to create Generator objects with the property named `@@iterator` instead the value of `Symbol.iterator.toString()` generated by the `Symbol` polyfill.

### Possible Solution

Change the order of imports so that `'babel-runtime/regenerator'` is _appended_ to the list of imports, rather than prepended to it.

### Context

I bumped into this bug after adding an `async` function to my entry file. This is when iterators suddenly stopped working in IE 11. Before they worked, since the `babel-polyfill` was executed first, and `Symbol` was already polyfilled. After adding the function, babel started loading `regenerator` before `babel-polyfill`, thus causing `regenerator` to behave differently. This started causing this issue https://github.com/babel/babel/issues/1534. Suffice to say, this was not easy to debug and wasted me a bunch of time, esp. since IE11's debugger is not very friendly. :(

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1 (babel-core 6.25.0)
| node             | 8.1.4
| npm              | 5.2.0
| Operating System | OS X 10.12

**Comment by jridgewell** [comment]
This is a regenerator transform issue, specifically https://github.com/facebook/regenerator/blob/83c5cec9a7945daa82e7431d0ab894d2058ef935/packages/regenerator-transform/src/visit.js#L231. Unshifting into the `Program` body breaks ES6 module semantics.
