### ISSUE TITLE
Support for depreciation [DEP0062] in babel-cli

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [babel/babel#5960]
Hello,

In the version 8 of node, depreciation `DEP0062`, the `--debug` flag has been removed. If we run:

```
$ babel-node --debug --debug-brk myFile.js 
(node:10876) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
```

Which is the expected behavior. However, if we run this (new way to do it):

```
$ babel-node --inspect-brk myFile.js 
  error: unknown option `--inspect-brk'
```

As a result it is impossible to debug a script and pause the debugger before the script starts.

**Comment by jridgewell** [comment]
This is [supported](https://github.com/babel/babel/pull/5785) in v7, but never backported.
