### ISSUE TITLE
Support for configurable 'dirname' in babel-core

### ISSUE THREAD

**Issue by maplecumt** [babel/babel#5961]
Traditionally, if we want to use babel in the current project, we just write this in the gulpfile of current directory:

```
  gulp.task('default', () => {

      return gulp.src('src/app.js')

        .pipe(babel({

            presets: ['es2015']

        }))

        .pipe(gulp.dest('dist'));

});
```

But if I want to use babel in other directory just like this:

```
gulp.task('default', () => {

      return gulp.src('src/app.js')

        .pipe(babel({

            babeldir: 'other/directory/that/installed/babel'              

            presets: ['es2015']

        }))

        .pipe(gulp.dest('dist'));

});
```

How can I do? Does babel support this way? If not, will babel support this?

**Comment by loganfsmyth** [comment]
Could you clarify what qualifies as "installed babel" here? you mean where `es2015` is installed? Since you're doing `.pipe(babel({`, you'll be using the version of babel that is bundled with `gulp-babel`. If it's about the preset install location, that's a different question.

**Comment by maplecumt** [comment]
I have some tool in `Desktop/sometool/` and `babel-preset-es2015` `gulp-babel` has been installed in this path. The gulp file in this path writes `.pipe(babel({` to transform js. 

Now, I want to use sometool to transform my workspace js files such as `Desktop/workspace/js/index.js`. But it comes with error message like `Couldn't find preset "es2015" relative to directory "/Users/username/Desktop/workspace/js"`.

The babel API tries to find "es2015" preset in my workspace directory other than my tool directory. How can I set this? 

Thank you for your attention.

**Comment by hzoo** [comment]
Going to close, we'd ask that you install the preset in the current working directory, not from somewhere else.
