### ISSUE TITLE
Wrong await parsing

### ISSUE THREAD

**Issue by droooney** [babel/babel#5966]
Babel version: **6.25.0**.
NodeJS and NPM version is irrelevant (the issues can be reproduced at http://babeljs.io/repl/).

1. `const await = foo;` throws a syntax error because it is a reserved word, though it is a reserved word only inside an async function.

2. `await` cannot appear inside function arguments (inside default values or computed keys).

```
async function foo(bar = await baz()) {}
```

or

```
async function foo({ [await baz()]: bar }) {}
```

Here Babel throws an error because `await` is an unexpected reserved word (see 1, apparently Babel thinks that `await` is not inside a function). Though the reason why it's a syntax error is because it's not allowed to use `await` inside arguments (it is a function body actually). That's why the following snippet does not throw any error (though it should).

```
async function foo() {
  async function bar(a = await baz()) {}
}
```

Chrome (as well as NodeJS) throws for this "Illegal await-expression in formal parameters of async function".
Firefox throws "await can't be used in default expression".

3. The same as for 2 goes for class properties:

```
async function a() {
  class Foo {
    bar = await baz();
  }
}
```

is also should be a syntax error because the `bar = await baz()` part is actually inside a constructor which can't be an async function.

Probably, there are more similar cases.

P.S.: actually all of these "work" for `yield` as well.

**Comment by hzoo** [comment]
Thanks for the detailed report! Did you try v7? parser issues are reported at https://github.com/babel/babylon/

@babel-bot move to babel/babylon

**Comment by droooney** [comment]
For some reason I thought that babylon is among babel packages in this repo.

No, haven't tried the new one actually. I can take a look tomorrow.
