### ISSUE TITLE
Remove the `check-es2015-constants` plugin and move code

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5967]
Continuing from the fix for https://github.com/babel/babel/issues/5728 done in https://github.com/babel/babel/pull/5930, we should move that logic out into the two places it actually needs to be used.

* ~~`transform-es2015-modules-*` - `import`ed variables are constant, so assignments to them should throw~~ (This is now handled in `babel-helper-modules`)
* `transform-block-scoping` - `const` variables are constants, so assignments to them should throw

We currently have a plugin that doesn't really correspond to one specific part of the spec, meaning someone looking in `block-scoping` would probably expect it the handling to be in there, but it is not currently.

**Comment by maurobringolf** [comment]
I havent looked into the module side of things yet so I am not sure what needs to be done there, but I agree that a separate plugin is a somewhat weird place for this logic. When I first saw the issue I expected the code to be in the block scoping plugin.

**Comment by reznord** [comment]
I'd be happy to take this on if this is still up for grabs.

**Comment by loganfsmyth** [comment]
I'm assuming @maurobringolf has not taken this on, but might be good to wait a few hours to see? Your call.

**Comment by reznord** [comment]
> might be good to wait a few hours to see

sure, no worries 😄

**Comment by maurobringolf** [comment]
No I am currently not working on this, but on a related PR for more consistent const violations https://github.com/babel/babel/pull/6100. This one also affects updates the logic discussed in here (to me moved out into block-scoping and modules plugin), but I am still debugging the last failing test so feel free to start on this one 😉

**Comment by loganfsmyth** [comment]
FYI edited this issue body. The ES6 module syntax part of this is now done in https://github.com/babel/babel/pull/6230 so this issue is even easier, we just need to move the logic from this module into `block-scoping`.

**Comment by maurobringolf** [comment]
Thanks, I will give this a try today.

**Comment by maurobringolf** [comment]
I looked into `block-scoping` but would need quite some time to understand its working pieces and put the constants check in the right place. Don't expect a PR from me soon, someone with experience in `block-scoping` will probably be a lot more efficient at this task.

**Comment by maurobringolf** [comment]
Update: Started working on this again, looks like I figured out where to put it 😀  Hopefully PR is ready soon.
