### ISSUE TITLE
es6 translation change this to _this

### ISSUE THREAD

**Issue by marcnetiq** [babel/babel#5974]
Within the transfer from ES6 to Javascript Babel changes a `var this` to `var _this`, which seems wrong.
Can I change a config file to avoid that transfer or do you have to change the babel transfer?

### ES6 Input Code:
```js
function setup() {
  foo.bar = foo.bar.extend({
      init: a => {
          let _t = this;
          _t._fselect(a);
      }
  });
}
```

### Expected Behavior:
within the init-function I expected that `var _t = this`, not  `var _t = _this`.

```js
"use strict";
function setup() {
    var _this = this;
    foo.bar = foo.bar.extend({
        init: function init(a) {
            var _t = this;
            _t._fselect(a);
        }
    });
}
```

### Current Behavior:
```js
"use strict";
function setup() {
    var _this = this;
    foo.bar = foo.bar.extend({
        init: function init(a) {
            var _t = _this;
            _t._fselect(a);
        }
    });
}
```

### Environment
| software         | version(s)
| ---------------- | -------
| Babel            |   6.25.0

**Comment by hzoo** [comment]
You are using an arrow function so that's expected, it takes the "this" of surrounding function scope. Otherwise use a function expression like before

```js
function setup() {
  foo.bar = foo.bar.extend({
      init: function(a) {
          let _t = this;
          _t._fselect(a);
      }
  });
}
```

**Comment by marcnetiq** [comment]
Thank You.
