### ISSUE TITLE
Can't export a top-level async function

### ISSUE THREAD

**Issue by lukealbao** [babel/babel#5977]
### Input Code

```js
// src/file.js

'use strict';

const regeneratorRuntime = require('regenerator-runtime');

async function demo () {
  // pass
}

module.exports = demo;

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "env"
  ],
  "plugins": [
    "transform-regenerator"
  ]
}

```

### Expected Behavior
Transpiled file should have the `regeneratorRuntime` and `_asyncToGenerator` variables declared and assigned before that of the exported function, which uses them.

### Current Behavior
Declarations and assignments appear after declaration/assignment of exported function, leading to an error:

`TypeError: Cannot read property 'mark' of undefined`

when attempting to access the not-yet-declared `regeneratorRuntime` variable.

### Possible Solution
Wrapping the async function in an IIFE produces the expected behavior. This leads me to believe it's a bug somewhere in the parsing procedure.

### Context
Wrapping the function in an IIFE (`module.exports = (() => async function () {})()`) will work, but it seems a little hacky, and I'm just looking to learn if I'm doing something wrong or if in fact this is a bug in the transpilation.

#### Reproducing
You can clone a minimal repo I created to demonstrate the error ([link](https://github.com/lukealbao/babel-async-bug)). There are two source files using each strategy, with the hope that you can reproduce the error. 

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 7.2.0
| npm              | 3.10.9
| Operating System | Mac 10.2.5

**Comment by hzoo** [comment]
I think this is just that the function gets hoisted before the require to regeneratorRuntime (out of order) - you can solve this by requiring the runtime/polyfill before this file is loaded (a separate entry file).

**Comment by jridgewell** [comment]
Why is this hoisted at all? It's in the same function scope.

**Comment by loganfsmyth** [comment]
It's a function declaration, so we always hoist it. We could potentially do static analysis to see if it can skip hoisting, but we don't have that at the moment.

**Comment by hzoo** [comment]
Other wise this is similar to https://github.com/babel/babel/issues/5977 and https://github.com/babel/babel/issues/5085#issuecomment-277544677 where logan recommended

```
import 'babel-polyfill';
import './app';
````

**Comment by lukealbao** [comment]
Thanks, folks. This leads me to another case where this should cause a problem:

```js
// someFile.js
'use strict';

let someClosure = 0;

function someEnclosingFn () {
  return someClosure++;
}

module.exports = somEnclosingFn;
```

This seems like a pretty reasonable thing to do (Node's util.debuglog does it), but the exported function would be hoisted above the closure it relies on, right? If this is is something that you all might want to pursue, I'd be happy to help in any way.

**Comment by loganfsmyth** [comment]
Since that isn't async, we won't touch it, but if it was, that should still work, since the order of the declarations don't make a difference.

**Comment by lukealbao** [comment]
D'oh, of course. No one will use it until after export. Thanks. :)
