### ISSUE TITLE
CatchClause and Catch's BlockStatement have separate scopes

### ISSUE THREAD

**Issue by boopathi** [babel/babel#5979]
```js
try { bar(); }
catch (err) { // <----- errPath.scope = CatchClause    (and) scope.uid = 1
  const foo = 1; // <-- fooPath.scope = BlockStatement (and) scope.uid = 2
}
```

For a functionExpression, the variables inside the function have the same scope as the function name.

```js
var f = function foo() { // <-- scope.uid = 42
  const a = 1; // scope.uid = 42
}
```

**Context:**

This causes a bug in babili's mangling - https://github.com/babel/babili/issues/635 - where the logic is to traverse through Scopables in BFS and rename ids. So it mangles for CatchClause and reuses the same name for BlockStatement since these are recognised as 2 different scopes.

I'd like to get a confirmation that this is a bug. I'll find a fix for this and send a PR soon.

**Comment by jridgewell** [comment]
I think this would also apply to `ForStatement`, `ForInStatement`, and `ForOfStatement`?

**Comment by boopathi** [comment]
I guess for `ForStatement` it's different - 

```js
for (let x = 1; console.log("x1", x) || x<10 ; x++ /* x1 */) {
  let x = 2; // x2
  console.log("x2", x)
}
```

and for `catch` we can make a similar one, but the binding/scope still has to be one.

```js
try {
  throw "asdf";
} catch ([ err, { message = err } ]) {
  console.log(err); // should log "a"
  // let err, message; // should throw
}
```

I guess it is the same for `ForInStatement` and `ForOfStatement` - at least in browsers (checked in chrome, firefox and safari latest stable), this doesnt throw - (Have to check the spec.)

```js
for (let a in {}) { let a; }
for (const a of []) { let a; }
```

**Comment by boopathi** [comment]
http://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements-static-semantics-early-errors

```ecmarkup
ForDeclaration[Yield] :
LetOrConst ForBinding[?Yield]

IterationStatement :
for ( ForDeclaration in Expression ) Statement
for ( ForDeclaration of AssignmentExpression ) Statement
```

> It is a Syntax Error if any element of the BoundNames of ForDeclaration also occurs in the VarDeclaredNames of Statement.

**Comment by jridgewell** [comment]
Never mind then. 😄
