### ISSUE TITLE
Destructuring assignment result onto an new object fail when compiling to ES5 from ES6

### ISSUE THREAD

**Issue by Jancat** [babel/babel#5982]
ES6 can assign destructuring assignment result to an new object, like this: 
```js
let obj = { a:1, b:2, c:3 };
let newObj = {a, b} = obj;
console.log(newObj);
```
I can run the above example normally and output `Object {a:1, b:2}`.

But when compiled to ES5，it show error `a is not defined`
[online babel example](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=DYUwLgBA9gRgVhAvBA3hAhgLgIwBoIyYBM-AxpgMwQC-A3ALABQokAdiAO4Dy8Sq6-GNT6w4DRqSisAzlFAA6YFADmACnbd4ASlpA)

**Comment by Ltrlg** [comment]
AFAICT this is the correct behaviour as `a` and `b` are not part of
the declared `let` bindings and Babel assumes module code by default
(i.e. in strict mode). If you run it outside strict mode, it creates
`a` and `b` as globals and `newObj` will be a reference to the same
object as `obj` (with all three props).

What you want here is:

```
let {a, b} = obj, newObj = {a, b}
```

**Comment by jridgewell** [comment]
This is correct. Try running

```js
(function() {
  "use strict";
  let obj = { a:1, b:2, c:3 };
  let newObj = {a, b} = obj;
})()
```

In Chrome.
