### ISSUE TITLE
Bug report: Comments breaks trasform-react-jsx

### ISSUE THREAD

**Issue by ftaiolivista** [babel/babel#5987]
Bug report

I'm transpiling with gulp, rollup-stream, rollup-plugin-babel and transform-react-jsx

The problem is that adding code commets in inline format (in jsdoc3 format) breaks compilation

For example this will transpile:

```
'use strict';

/** 
 * @module Component
 */

export default class Component {
    view (vnode) {
        return <div>test</div>
    }
}
```

this even transpile good:

```
'use strict';

/** 
 * @module Component
 */

export default class Component {
    view (vnode) {
        return m('div', 'test')
    }
}
```

This not:

```
'use strict';

/** @module Component */

export default class Component {
    view (vnode) {
        return <div>test</div>
    }
}
```

giving error :
```

SyntaxError: Unexpected token (7:15) in /home/vista/www/armatura/src/Component.js
    at error (/home/vista/www/armatura/node_modules/rollup/dist/rollup.js:177:12)
    at /home/vista/www/armatura/node_modules/rollup/dist/rollup.js:9417:6
    at <anonymous>
  pos: 108,
  loc: Position { line: 7, column: 15 },
  raisedAt: 109,
  plugin: 'commonjs',
  id: '/home/vista/www/armatura/src/Component.js' }

```

I see in error that commonjs plugin is mentionated (rollup-plugin-commonjs 8.0.2)
but I don't think the problem is in commonjs because if I replace `<div>test</div>` the
code will transpile with the two types of comments

### Babel Configuration 

```js
{
'presets': [
       ['es2015-rollup']
   ],
   'plugins': [
       [
           'transform-react-jsx',
           {
               'pragma': 'vnode.state.m'
           }
       ]
   ],
   'exclude': 'node_modules/**'
}
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| gulp-babel    |  6.1.2
| node             |  v8.1.3
| npm              | 5.3.0
| Operating System |  Linux

**Comment by jridgewell** [comment]
This isn't caused by Babel. Something is wrong with your setup that's preventing JSX syntax from loading.

**Comment by ftaiolivista** [comment]
Solved. Was a problem with commonjs setup togher with babel. solved changing plugin order. Thank you
