### ISSUE TITLE
[transform-es2015-classes] loose mode shouldnt add function names

### ISSUE THREAD

**Issue by Andarist** [babel/babel#5998]
**feature request**

I think the loose mode shouldnt add function names to generated class methods, or new option should be added so this behaviour can be prevented with it. Happy to provide a PR if you give this green light and we establish what should be done.

### Expected Behavior versus Current Behavior
```diff
var Klass = function () {
  function Klass() {
    _classCallCheck(this, Klass);
  }

-  Klass.prototype.method = function method() {};
+  Klass.prototype.method = function () {};

  return Klass;
}();
```

**Comment by loganfsmyth** [comment]
> I think the loose mode shouldnt add function names to generated class methods

Hard to really judge this without knowing the motivation behind it. Why is this something we'd want to support?

**Comment by Andarist** [comment]
@loganfsmyth 
i was under strong impression that those were not eliminated by the uglifyjs, but ive checked now and it seems they are eliminated, so its non issue, sorry for raising the issue before thorough check 🙈
