### ISSUE TITLE
JSX allows elements as attribute values, but the transform throws

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6004]
Input:
```
<div attr=<div /> />
```
should become

```
React.createElement(
  "div",
  { attr: React.createElement("div", null) }
);
```

but Babel currently throws

> Property value of JSXAttribute expected node to be of a type ["JSXElement","StringLiteral","JSXExpressionContainer"] but instead got "CallExpression"

I assume because we're going through the intermediate
```
<div attr=React.createElement("div", null) />
```
which is indeed invalid. Probably the easiest fix would be to wrap it, e.g.
```
<div attr={React.createElement("div", null)} />
```

**Comment by hzoo** [comment]
This means:

- [ ] modifying https://github.com/babel/babel/blob/7.0/packages/babel-plugin-transform-react-jsx/src/index.js
- [ ] adding test cases with elements as attributes (fixtures to expect the behavior Logan describes)
- [ ] maybe doc in the readme about this case?
- [ ] target 7.0 branch
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) 
- [ ] comment below you are working on this for others to know
- [ ] join our slack/follow our twitter for help other than this issue.

**Comment by kedromelon** [comment]
I'm interested in taking a crack at this if no one else has started on it yet!

**Comment by existentialism** [comment]
@kedromelon all yours!

**Comment by ljharb** [comment]
Can someone cite a source for where jsx allows this?

**Comment by nicolo-ribaudo** [comment]
https://facebook.github.io/jsx/ JSXAttributeValue includes JSXElement.

**Comment by ljharb** [comment]
Thanks!
