### ISSUE TITLE
[Feature Request]: html mode for template literal transformation

### ISSUE THREAD

**Issue by bigopon** [babel/babel#6007]
Feature request

### Current Behavior
Currently the following block:

```js
render`
    <div>
      <h1>Hello, world!</h1>
      <h2>It is ${new Date().toLocaleTimeString()}.</h2>
    </div>
  `;
```

will result into:

```js
"use strict";

var _templateObject = _taggedTemplateLiteral(
  ["\n    <div>\n      <h1>Hello, world!</h1>\n      <h2>It is ", ".</h2>\n    </div>\n  "],
  ["\n    <div>\n      <h1>Hello, world!</h1>\n      <h2>It is ", ".</h2>\n    </div>\n  "]
);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

render(_templateObject, new Date().toLocaleTimeString());
```

Clearly this is not ideal, as it is not only longer, but also contains unwanted characters, which make the bundle little tiny bit heavier.

### Possible Solution

Allow dev to optionally pass in `html` together with `loose` / `spec`. From the [following line](/babel/babel/blob/7.0/packages/babel-plugin-transform-es2015-template-literals/src/index.js#L38):

```js
strings.push(value);
```

Can it be changed to:

```js
strings.push(value.replace(/\r\n\t/g, ''));
```

when `html` === true ?

| software         | version(s)
| ---------------- | -------
| Babel            |  latest

**Comment by goto-bus-stop** [comment]
The template literal transform should adhere to the spec, so it can't just change the contents of strings. This would be a good candidate for a custom transform, though. I don't think it's exactly what you need, but you could look at something like [this plugin](https://github.com/DylanPiercey/babel-plugin-as-html) for inspiration at least.

**Comment by bigopon** [comment]
I see, thanks for helping. It does give me some hint where to start for a custom transformation. I couldn't find it, hence the feature request.

**Comment by jridgewell** [comment]
We could definitely cleanup the output a bit (removing the duplicated arrays), but we wouldn't be able to trim whitespace from the inside.
