### ISSUE TITLE
In operator always returns true for ES6 Symbols in phantomjs

### ISSUE THREAD

**Issue by bdwain** [babel/babel#6010]
Choose one: is this a bug report or feature request?
bug report

When using the babel polyfill in phantomjs and using the in operator to determine if a symbol is a property on an object, it always seems to return true.

### Input Code
```js
    let sym = Symbol('foobar 123');
    let obj1 = {
      hello: 123,
      [sym]: ['a', 'b', 'c']
    };
    let obj2 = {
      hello: 123
    };
    console.log('test1', sym in obj1); //logs true
    console.log('test2', sym in obj2); //also logs true, should be false
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": ["react", ["latest", {
    "es2015": {
      "modules": false 
    }
  }]],
  "plugins": ["transform-object-rest-spread"]
}

    "babel-polyfill": "6.23.0",
    "babel-core": "6.25.0",
    "babel-loader": "7.1.1",
"karma-webpack": "^2.0.1",
"phantomjs-prebuilt": "^2.1.5",
"karma-phantomjs-launcher": "^1.0.0",

karma start ./config/webpack/test/karma.conf.js --single-run --browsers PhantomJS
```

### Expected Behavior
in operator returns false for symbols on objects that do not have them

### Current Behavior
in operator returns true for symbols on all objects

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.23.0
| node             | 7.10.0
| npm              | 4.2
| yarn .           | 0.27.5
| Operating System | OSX Sierra

**Comment by loganfsmyth** [comment]
This is a known limitation of `Symbol` polyfills. https://github.com/zloirock/core-js#caveats-when-using-symbol-polyfill

**Comment by bdwain** [comment]
got it. thansk for getting back so quickly.
