### ISSUE TITLE
babel-preset-flow@^6.23.0 does not support flow's opaque type aliases 

### ISSUE THREAD

**Issue by Gozala** [babel/babel#6014]
With the latest release version of `babel-cli@6.24.1` & `babel-preset-flow@^6.23.0` syntax for [Opaque Type Aliases](https://flow.org/en/docs/types/opaque-types/)  in flow causes parse errors.

Example:

```js
opaque type ID = string;
//     ^ Unexpected token, expected ; (1:7)
```

**Comment by loganfsmyth** [comment]
https://github.com/babel/babel/pull/5990
