### ISSUE TITLE
npm i babel-preset-stage-2@7.0.0-alpha.16 failed

### ISSUE THREAD

**Issue by deangoku** [babel/babel#6016]
Choose one: bug report

### Input Code

```bash
npm i babel-preset-stage-2@7.0.0-alpha.16
```

### Current Behavior
![tim 20170726122306](https://user-images.githubusercontent.com/6375486/28604449-52f21822-71fd-11e7-9246-b5f7cf048245.png)

### Possible Solution
babel-plugin-transform-function-sent should be babel-plugin-transform-function-sent2 I guess. Seems like branch 7.0 had fixed it, but npm hasn't.

**Comment by hzoo** [comment]
I didn't know someone already published it earlier so I didn't have access to publish it. I already emailed @hax about this too. I'm just renaming so I can publish again. But in the meantime I found some other issues so waiting till those are fixed. update devdeps to latest, update babylon

**Comment by hzoo** [comment]
published 7.0.0-alpha.17
