### ISSUE TITLE
File.addImport doesn't provide a way to create an ImportDeclaration with no specifiers

### ISSUE THREAD

**Issue by chocolateboy** [babel/babel#6021]
| software         | version(s)
| ---------------- | -------
| Babel            | 6.25.0 and v7.0.0-alpha.17
| node             | v8.1.4
| npm              | 5.0.3
| Operating System | Linux (Arch)

`PluginPass.file.addImport` doesn't provide a way to create an `ImportDeclaration` node with an empty `specifiers` array (i.e. the [`import ModuleSpecifier`](https://www.ecma-international.org/ecma-262/6.0/#sec-imports) form) i.e. a plugin can't create a node like this:

```javascript
import "source-map-support/register";
```
The method doesn't have a branch for the no-specifiers case so the array always ends up non-empty:

```javascript

File.prototype.addImport = function addImport(source, imported) {
    // ...
    if (imported === "*") {                                                    
       specifiers.push(t.importNamespaceSpecifier(id));                         
     } else if (imported === "default") {                                       
       specifiers.push(t.importDefaultSpecifier(id));                           
     } else {                                                                   
       specifiers.push(t.importSpecifier(id, t.identifier(imported)));          
     }                                                          
    // ...
}
```

Omitting the `imported` parameter, or passing `null` or `undefined`, results in the following error when the node is printed:

### source

```javascript
const id = file.addImport('source-map-support/register')
```

### error

    TypeError: input.js: Cannot read property 'length' of null

Passing it as an empty string produces the following (invalid) output:

### source

```javascript
const id = file.addImport('source-map-support/register', '')
```

### output

    import {  as _ } from 'source-map-support';

**Comment by hzoo** [comment]
I actually encountered this at one point as well 😛 , ended up doing it manually probably but I forgot
