### ISSUE TITLE
Regression from alpha.17

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6025]
Tried to make a smaller repo from a file in our codebase: (this is with env no loose mode)

might just be our setup though, need to check when we get the alpha.17 repl

## Input
```js
for (let path of c) {
  path;
  () => path;
}

if (true) {
  let path = false;
}
```

## Output

```js
var _loop = function _loop(_path) {
  path; // should be _path

  (function () {
    return path;
  });
};

var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
  for (var _iterator = c[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var _path = _step.value;

    _loop(_path);
  }
} catch (err) {
  _didIteratorError = true;
  _iteratorError = err;
} finally {
  try {
    if (!_iteratorNormalCompletion && _iterator.return) {
      _iterator.return();
    }
  } finally {
    if (_didIteratorError) {
      throw _iteratorError;
    }
  }
}

if (true) {
  var path = false;
}
```

**Comment by hzoo** [comment]
Is it possible it came from https://github.com/babel/babel/pull/5745 @peey?

**Comment by peey** [comment]
It shouldn't be, because that only affects bindings and not references. I'll still run this example before and after #5745 to see if it makes a difference. 

For that, can you share your env please? Either that or names of plugins / presets being used if you can figure that out.

**Comment by hzoo** [comment]
basically using https://github.com/behance/babel-preset-behance

**Comment by hzoo** [comment]
Fixed by https://github.com/babel/babel/issues/6046
