### ISSUE TITLE
feat(babel-node): regex for 'only' and 'include' args

### ISSUE THREAD

**Issue by AndersDJohnson** [babel/babel#6033]
Feature request:

Add support for specifying regular expressions to match files on the command line, instead of globs, for arguments `--only` and `--include`. Reasons to support regex include:
* More power than globs, e.g., support negative lookaheads to include specific node modules but exclude the rest.
* Some tools generate regular expressions so it'd be nice to be able to compose with those.

I've provided a possible implementation [here](https://github.com/babel/babel/compare/7.0...AndersDJohnson:babel-node-only-include-regex), but decided not to open a PR without feedback on the idea.

In this implementation, regexes are specified by including `/` prefix and suffix on the string passed to the arguments, e.g. `/node_modules/(?!some-es6-module)/`. There is some risk of this being a breaking change, if anyone is using absolute file paths prefixed with `/` and also targeting entire directories with trailing `/` on them. I am open to a different approach, e.g., a more unique syntax, a separate argument to indicate regex patterns instead of globs for these arguments, or separate but parallel options (e.g. `--include-regex`, `--only-regex`, etc.). Let me know your thoughts.

**Comment by loganfsmyth** [comment]
It'd probably be best to use a JS config file and include the regular expressions in there. Would that be sufficient for your usecase?

**Comment by xtuc** [comment]
No info, closing for now.
