### ISSUE TITLE
babel-preset-stage-3 from Babel v7 pulls in bits of Babel v6 via transitive dependencies in babel-plugin-transform-unicode-property-regex

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#6034]
`babel-preset-stage-3` pulls in `babel-plugin-transform-unicode-property-regex` v2.0.2: https://github.com/babel/babel/blob/7.0/packages/babel-preset-stage-3/package.json#L15-15

`babel-plugin-transform-unicode-property-regex` v2.0.2 pulls in `babel-runtime` v6.23.0, as well as `babel-cli`, `babel-core` and `babel-preset-es2015` as dev dependencies: https://github.com/mathiasbynens/babel-plugin-transform-unicode-property-regex/blob/master/package.json#L36-L36

This means that Babel v7 is confusingly still loading code from Babel v6, and `babel-standalone` v7 has bits of v6 floating around in it 😃

**Comment by hzoo** [comment]
Ah yeah since babel-runtime was a v6 thing so all packages did this. And being outside of the repo its more likely to be the case.. cc @mathiasbynens (https://github.com/mathiasbynens/babel-plugin-transform-unicode-property-regex), can we move this into the monorepo or publish a new version without (major/alpha)?

**Comment by mathiasbynens** [comment]
What is needed exactly? Can I just remove those dependencies from `package.json` without making any other changes?

**Comment by hzoo** [comment]
@mathiasbynens yeah this is from https://github.com/babel/babel/issues/4315 (which you made 😄 ) , basically since now you can use stuff like map/set/promise/symbol

**Comment by mathiasbynens** [comment]
Yeah, but what about `import`/`export` etc.?

**Comment by hzoo** [comment]
? You still need to compile that, I just mean you don't need to have babel-runtime as a dep, and regexp-core and other dependencies can be on the latest versions

**Comment by mathiasbynens** [comment]
I was wondering because e.g. https://github.com/babel/babel/blob/7.0/packages/babel-plugin-syntax-exponentiation-operator/package.json doesn’t seem to have any compilation steps (despite using `import`/`export` etc.)

**Comment by hzoo** [comment]
it's in the monorepo, so the build step is at the top level https://github.com/babel/babel/blob/7.0/Gulpfile.js#L14.

> can we move this into the monorepo or publish a new version without (major/alpha)?

**Comment by hzoo** [comment]
Did you have an issue with moving the package into this repo?

**Comment by mathiasbynens** [comment]
Sorry I haven’t been able to do this myself. The package can be moved into the repo long-term.

**Comment by mathiasbynens** [comment]
babel-plugin-transform-unicode-property-regex@2.0.4 drops the dependency on babel-runtime!

**Comment by hzoo** [comment]
Awesome thanks @mathiasbynens! I see that 1 it didn't use it since transform-runtime plugin wasn't used, and 2 it can be a patch because it dropped node 0.10/0.12 in v2 already
