### ISSUE TITLE
a weird lodash warning emitted by babel

### ISSUE THREAD

**Issue by njleonzhang** [babel/babel#6041]
My project do not import `lodash`, but babel aways shows this warning.

```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/leon/Documents/git/my-react-starter/node_modules/lodash/lodas
h.js" as it exceeds the max of "500KB".
```

Event after removing all code in the webpack entry `main.js`, this warning still exists.

The following log shows when I build a empty webpack entry file:

```
➜  my-react-starter git:(master) ✗ npm run build

> my-react-starter@1.0.0 build /Users/leon/Documents/git/my-react-starter
> node build/build.js

⠼ building for production...[BABEL] Note: The code generator has deoptimised the styling of "/Users/leon/Documents/git/my-react-starter/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
⠧ building for production...[copy-webpack-plugin] WARNING - unable to locate '/Users/leon/Documents/git/my-react-starter/static' at '/Users/leon/Documents/git/my-react-starter/static'
Hash: 3aaccd59898b347efa91
Version: webpack 3.4.1
Time: 20732ms
                                     Asset       Size  Chunks             Chunk Names
     static/js/app.b967cc05005e01ed2083.js   40 bytes       0  [emitted]  app
static/js/manifest.4c9a97b3d8d959b8d136.js     1.4 kB       1  [emitted]  manifest
                                index.html  327 bytes          [emitted]

ERROR in [copy-webpack-plugin] unable to locate '/Users/leon/Documents/git/my-react-starter/static' at '/Users/leon/Documents/git/my-react-starter/static'

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

```
The output file's size is only 40bytes, and `lodash` is definitely not bundled in it, but I can aways get `lodash` warning. I am curious what happened? 
 
reproduce project:  [my-react-starter](https://github.com/njleonzhang/my-react-starter) 
 

babel-core version: 6.25.0

**Comment by loganfsmyth** [comment]
You're missing `exclude: /node_modules/` on your other loader: https://github.com/njleonzhang/my-react-starter/blob/47f5066b17d30600d2cca76bac188361f074e7c8/build/webpack.base.conf.js#L53

**Comment by njleonzhang** [comment]
@loganfsmyth thanks....

**Comment by njleonzhang** [comment]
I know this question may be stupid, but why `webpack` try to bundle `lodash` without exclude `node_modules`

**Comment by loganfsmyth** [comment]
One of your dependencies for the application likely depends on Lodash. Loading it from `node_modules` without the `exclude` will make Babel try to run on all of the stuff in `node_modules` which is rarely what you want.

**Comment by njleonzhang** [comment]
here the `dependencies`, do you indicate the `dev dependencies`?
