### ISSUE TITLE
Gulp-babel and babelrc easy question

### ISSUE THREAD

**Issue by badman-rodriguez** [babel/babel#6042]
I have a simple question.
Can gulp-babel be able to transpile into ES5 without a babelrc file? is it possible?

```

var gulp = require('gulp');
var babel = require('gulp-babel');

gulp.task('babel-not-working', function() {
gulp.src([
  'file-glob/**/**/*.js'
])
.pipe(plugins.babel({
  compact: true,
  babelrc: false,
  presets: ['es2015']
})))
```

I do this, and all i get is this error:
`SyntaxError: Unexpected token import`

**Comment by hzoo** [comment]
If you use another tool yes you can pass in the preset/options directly. We don't have the time/resources to reproduce just from that, can you make a repo that shows this behavior?

**Comment by badman-rodriguez** [comment]
Not a problem, here is the repo:
https://github.com/badman-rodriguez/gulp-example

**Comment by hzoo** [comment]
Awesome, so just looking at the repo though all the files in https://github.com/badman-rodriguez/gulp-example/blob/master/dist are transformed from using import, so not sure where that error comes from? What command are you running?

**Comment by badman-rodriguez** [comment]
`MB-C02TF1VHGTFM:gulp-example brodriguez$ gulp
[09:55:26] Using gulpfile ~/Documents/projects/gulp-example/gulp-example/gulpfile.js
[09:55:26] Starting 'default'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
/Users/brodriguez/Documents/projects/gulp-example/gulp-example/js/test.js:1
(function (exports, require, module, __filename, __dirname) { import test2 from './test2.js';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/brodriguez/Documents/projects/gulp-example/gulp-example/node_modules/require-uncached/index.js:28:9)`

**Comment by hzoo** [comment]
Ok there's an issue with passing the output of babel to tape directly like that. I would ask whether you need gulp? You should be able to just run tape with babel-node? I would google for a tutorial on doing that? I see there's https://www.npmjs.com/package/babel-tape-runner. Or really you should be moving the tape call after you build it with babel.

**Comment by badman-rodriguez** [comment]
Oh i understand that tape can run independently with tape babel-register fileglob/**.js but i needed some to add a module-resolver for pathing issues which can only be done while it's testing. 

Wish it was that easy.. but work tasks are never that easy! LOL! thanks for help but i did find a solution for it!

step 1 transpile and send to a test folder, step 2: run tests on folder.
Done!

Actually doing this helped me out to get to this idea! thanks!
