### ISSUE TITLE
7.0 and babel-plugin-espower

### ISSUE THREAD

**Issue by TrejGun** [babel/babel#6043]
I'm not sure where is error here but they were playing nice before

detailed description is here
https://github.com/power-assert-js/babel-plugin-espower/issues/21

**Comment by hzoo** [comment]
It's not intentional for Babel 7 to be backwards compatible (it might be), the plugin needs to update, could be a few things http://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors.

**Comment by TrejGun** [comment]
they have already fixed

**Comment by hzoo** [comment]
Awesome, making https://github.com/babel/notes/issues/30 to document these changes better
