### ISSUE TITLE
Error while destructuring and returns from arrow function

### ISSUE THREAD

**Issue by srameshr** [babel/babel#6047]
Choose one: is this a bug report or feature request?
Bug Report

### Input Code

[REPL Link](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=&browsers=&builtIns=false&debug=false&code_lz=MYewdgzgLgBAJgQygmBeGBtGBvBAuARgBoYAjPGAJhOAoGYBfGAXQDoBbBABwAoeBLKAFN2ASjQA-GDwBQASGwwEJUjRhN0gkTNGiA3EA)
```js
const data = [ {a:1, b: 2, c: 3} ].map((item) => (
	{ a, b, c } = item
));
```

### Expected Behavior

The same code works fine with latest TS compiler and Chrome 59.0

### Current Behavior

Undefined var access error

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  Latest -- On babel REPL
| node             | 
| npm              | 
| Operating System |

**Comment by nicolo-ribaudo** [comment]
a, b and c are not declared. You should add `var/let a, b, c;`

**Comment by srameshr** [comment]
@nicolo-ribaudo I was trying to just return the object without declaring any variables. 
```
(() => {
  "use strict";
  const dev = [ {a:1, b: 2, c: 3} ].map((item) => (
    { a, b, c } = item
  ));
})();
```
It works in the chrome console and TSC compiler.

**Comment by TrejGun** [comment]
doesn't work in my chrome console

**Comment by srameshr** [comment]
@TrejGun This is my version: ```Version 59.0.3071.115 (Official Build) (64-bit)```
![Check this screen shot](https://user-images.githubusercontent.com/8149408/28918456-f1fb18dc-7866-11e7-9f7c-3cc4104191fe.png)

**Comment by nicolo-ribaudo** [comment]
It should throw an error per the specification. Can you try to run that code in an empty page (`about:blank`) instead of in GitHub?

The you don't need to destructuring, since your code is equivalent to
```js
const data = [ {a:1, b: 2, c: 3} ].map((item) => {
    ({ a, b, c } = item);
    return item;
});
```

**Comment by srameshr** [comment]
😯 Under blank page it throws an error.

**Comment by nicolo-ribaudo** [comment]
Maybe GitHub has `var a, b, c;` somewhere so they are declared.

If you need to get only some properties, you have to return a new object, since assignments return the left value (and thus the original object)

```js
const data = [ {a:1, b: 2, c: 3} ].map(({ a, b, c }) => ({ a, b, c }));
```

**Comment by jridgewell** [comment]
This is because of `"use strict"`. Try the following:

```js
(function() {
"use strict";

var data = [{
  a: 1,
  b: 2,
  c: 3
}].map(function (item) {
  var _item;

  return _item = item, a = _item.a, b = _item.b, c = _item.c, _item;
});
})()
```
