### ISSUE TITLE
babel-node cli question

### ISSUE THREAD

**Issue by badman-rodriguez** [babel/babel#6049]
I was trying to do this:

`babel-node --babelrc=path/to/.babelrc **/tests/*.js | faucet`

I based this off the example noted:
http://henryzoo.com/babel.github.io/docs/usage/options/

I know it's weird to have a nested config file, but im trying to use this particular babelrc just for testing purposes only.

When i run this command i end up with an error stating: 
`(function (exports, require, module, __filename, __dirname) { import test from 'tape';
                                                              ^^^^^^
SyntaxError: Unexpected token import`

Which means it can't find the babelrc, but when i put it in the root folder it works just fine.

Any idea on why?

Environment:
- "babel-core": "^6.25.0"
- node: 6.11.0

**Comment by xtuc** [comment]
The documentation you was looking at is for Babel 5. 

The `babelrc` option doesn't exists anymore, see babeljs.io/docs/usage/cli
