### ISSUE TITLE
Feature request: Allow disabling escaping

### ISSUE THREAD

**Issue by kdex** [babel/babel#6055]
I've recently [brought this up](https://github.com/mathiasbynens/jsesc/issues/41) with `jsesc`: Essentially, there are valid scenarios where unescaped (or: non-ASCII-safe) code is required to prevent transpiled files from exploding in size.

Allow me to copy the gist of it over with some slight edits:

> One of my projects requires me to have a binary blob (synchronously) ready at `require` time. Hence, part of the build pipeline is to load the blob into a string in the build step, and then read the string and convert it to a `TypedArray` during runtime.
> 
> When running the files through babel, the `119 KiB` blob and `64 KiB` source bundle up to `408 KiB` after minification. One might have (very rougly) expected a total of around `64 KiB + 119 KiB = 183 KiB`.
> 
> The problem is that most of the binary blob, which is loaded into the bundle, is *escaped* once babel has processed it, and the escaped representation takes up a lot of space. This limitation seems to be known and has been brought up in [this discussion](https://github.com/babel/babel/issues/4909) already.
> 
> I see you've implemented a `minimal` mode which only escapes very few characters. Since my payload contains a good amount of null bytes, this wouldn't help me a lot. My best option would be to specify an option such as `none` (feel free to bikeshed!), once babel allows passing options to `jsesc`.

@michaelficarra then rightfully argued:

>  Asking a dependency for an option which effectively disables it so that the consuming application doesn't need to avoid calling it seems inappropriate. Just have babel not call jsesc.

One solution to this problem would be to specify a boolean flag in the configuration that allows turning off escaping entirely.

**Comment by JLHwung** [comment]
Closing this as it has been fixed in https://github.com/babel/babel/pull/11384.
