### ISSUE TITLE
Preset ordering with babel-cli --presets.

### ISSUE THREAD

**Issue by blieque** [babel/babel#6059]
I've searched but can't find another report of this problem.

### Input Code

I've included the problematic part, but I can include the rest if needs be.

```
(() => {
    ...
    const submitHandler = function submitHandler(event) {
        ...
        const fields = {};
        ...
        const xhr = new XMLHttpRequest();
        xhr.addEventListener('load', ...);
        xhr.open('POST', event.target.action);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send(JSON.stringify({fields})); // <-- here's the problem
    };
    ...
})();
```

### Babel Configuration (.babelrc, package.json, cli command)

I'm using `make` and compiling via command line:

    babel --presets babili,es2015 -o ./dist/app.min.js ./src/public/scripts/app.js

### Expected Behavior

Babel would run the presets in reverse order, as documented (e.g., `es2015`, then `babili`).

### Current Behavior

Babel instead runs `babili` first, which minifies `fields = {}` to `f = {}`, but leaves the later reference alone (as it's being sent to an API). *Then* `es2015` expands `{fields}` in the request to `{ fields: fields }`, as it should. This causes an error though, as `fields` has been minified to `f`.

### Possible Solution

Switch the order of the arguments around? Same result.

Run babel twice, first using only `es2015` and then only `babili`:  
```
    ./node_modules/.bin/babel --presets=es2015 -o ./dist/app.min.js ./src/public/scripts/app.js 
    ./node_modules/.bin/babel --presets=babili -o ./dist/app.min.js ./dist/app.min.js
```

This works, but is cumbersome.

### Context

I'm trying to run a `make` build.

```
output = ./dist
public = ./src/public
babel_args = --presets babili,es2015

$(output)/app.min.js: $(public)/scripts/app.js
	@echo "Transpiling and minifying scripts"
	@babel ${babel_args} -o $(output)/app.min.js $(public)/scripts/app.js
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1 (CLI), 6.25.0 (core)
| node             | 6.7.0
| npm              | 3.10.3
| Operating System | Ubuntu 17.04

**Comment by jridgewell** [comment]
@babel-bot move to babel/babili.

**Comment by xtuc** [comment]
@babel-bot move to babel/babili

**Comment by xtuc** [comment]
The bot was maybe down yesterday. I'm closing this since it has been moved in Babili's repo.
