### ISSUE TITLE
babel-register does not load external source maps

### ISSUE THREAD

**Issue by OliverJAsh** [babel/babel#6060]
I am compiling my code with TypeScript prior to piping it through babel via babel-register.

When I enable TypeScript external source map files, babel-register does not seem to pick these up.

When I enable TypeScript inline source map files, babel-register does seem to pick them up.

I believe this could be because of the `retrieveSourceMap` option specified to `source-map-support`. It overrides the default behaviour and does not attempt to load source maps from disk. See https://github.com/babel/babel/blob/2dba910b9e32679fb0adbfb89f00d5ef30e0b715/packages/babel-register/src/node.js#L13.

Is there any reason for this? If so, can this be documented somewhere to avoid confusion?

**Comment by OliverJAsh** [comment]
Any updates on this? If the `retrieveSourceMap` override is not intentional, this is an easy fix. Could we get some more information on why this is the case?

**Comment by loganfsmyth** [comment]
I believe this should be fixed in 7.x as of #7980 .
