### ISSUE TITLE
Exporting of TypeScript types separate from their declarations doesn't get erased

### ISSUE THREAD

**Issue by pelotom** [babel/babel#6065]
Hi, I just tried out the new `babel-preset-typescript` in version 7.0.0-alpha.19 with much anticipation. Unfortunately I discovered that it doesn't erase types that are exported separate from their declaration:

```ts
type Foo = number
export { Foo }
```

gets transformed to

```ts
export { Foo }
```

which of course generates an error if you try to run it: `ReferenceError: Foo is not defined`. It correctly deletes the export if you write

```ts
export type Foo = number
```

**Comment by andy-ms** [comment]
Hi @pelotom, we haven't written the guide for this yet, but this plugin needs to be used with the `--isolatedModules` option. If you have that enabled (and a recent enough version of the `typescript` package), you should get a compile error, because we don't support re-exports of types in that mode. The reason being that in general, in order to determine whether something is a type, we need information about other modules.
```ts
import { T } from "./other-module";
export { T }; // Is this a type export?
```
In babel we transpile files independently so we can't access the information we would need there.

**Comment by Kovensky** [comment]
@andy-ms is something like `import { T as ImportedT } from './other-module'; export type T = ImportedT` (intended to be) supported?

**Comment by andy-ms** [comment]
Yes, that should work since we can use local information to determine that it's a type-only import.

**Comment by rodrigopivi** [comment]
Experiencing the same error:
```
export type IExecuteGQL = <T>({ persistedQueryId, variables }: IGQLPersistedQuery<T>) => Promise<T>;
```
Valid typescript that does not work with current babel-preset-typescript `7.0.0-beta.3`

**Comment by andy-ms** [comment]
Hi @rodrigopivi, see https://github.com/babel/babylon#768. In the meanwhile you could replace the binding pattern `{ persistedQueryId, variables }` with a single name, e.g. `<T>(query: IGQLPersistedQuery<T>) => Promise<T>;

**Comment by alangpierce** [comment]
@andy-ms it seems like the original code should be reasonable to handle even in `isolatedModules` mode:
```typescript
type Foo = number
export { Foo }
```

I realize that `isolatedModules` currently gives an error, but seems like that error is overly aggressive here. This isn't really a re-export, it's just an exported type across two statements.

Just like how Babel (and TS) will remove imported identifiers that are only used as types in the file, couldn't it also remove exported identifiers that are only declared as types in the file? It looks to me like the TypeScript compiler already does this with `transpileModule`, so seems like a case where Babel/`isolatedModules` is more limited than it needs to be.
