### ISSUE TITLE
stage-0 and stage-1 don't play well with typescript around exporting types

### ISSUE THREAD

**Issue by pelotom** [babel/babel#6066]
With this `.babelrc`:

```json
{
  "presets": ["stage-1", "typescript"]
}
```

attempting to compile

```ts
export type Foo = number
```

gives an error:

```
SyntaxError: src/index.ts: Unexpected token (1:12)
> 1 | export type Foo = number
    |             ^
  2 |
```

Same for `stage-0`. `stage-2` and `stage-3` are not affected.

**Comment by nicolo-ribaudo** [comment]
Thank you for testing the TypeScript support!
I'm moving this issue to the parser's repository.

@babel-bot move to babel/babylon

**Comment by xtuc** [comment]
@babel-bot move to babel/babylon

**Comment by xtuc** [comment]
Thanks @nicolo-ribaudo, I closing this since I moved it in Babylon.
