### ISSUE TITLE
Babel transpiles any folder containing strings specified using `--only`

### ISSUE THREAD

**Issue by ockham** [babel/babel#6067]
I'm using `--only` to tell babel to transpile only a defined set of subdirectories (`button/` and `main/` in my case). I'm using the pattern specified below. Note that Babel seems to ignore the leading `./` and thus ends up including any folder whose name _contains_ either `button/` or `main/`, e.g. `forms/clipboard-button/`, or `reader-main/`.

### Babel Configuration (package.json)

```js
  "scripts": {
    "build": "babel --only ./button/,./main/ --out-dir cjs .",
  },
```

### Expected Behavior
```
button/docs/example.jsx -> cjs/button/docs/example.js
button/index.jsx -> cjs/button/index.js
button/test/index.js -> cjs/button/test/index.js
main/index.jsx -> cjs/main/index.js
```

### Current Behavior
```
button/docs/example.jsx -> cjs/button/docs/example.js
button/index.jsx -> cjs/button/index.js
button/test/index.js -> cjs/button/test/index.js
forms/clipboard-button/docs/example.jsx -> cjs/forms/clipboard-button/docs/example.js
forms/clipboard-button/index.jsx -> cjs/forms/clipboard-button/index.js
forms/form-button/index.jsx -> cjs/forms/form-button/index.js
main/index.jsx -> cjs/main/index.js
reader-main/index.jsx -> cjs/reader-main/index.js
spinner-button/docs/example.jsx -> cjs/spinner-button/docs/example.js
spinner-button/index.jsx -> cjs/spinner-button/index.js
```

### Possible Solution
I know there's #5487 which fixes this in Babel 7 (by interpreting `--only` and `--ignore` args as relative paths instead of glob patterns), but I'd argue this is broken enough to warrant a fix in Babel 6. I think it's fine to continue to treat them as glob patterns, but Babel should respect the leading `./`.

### Context
See https://github.com/Automattic/wp-calypso/pull/16782#discussion_r131103930

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.25.0
| node             | 6.11.2
| npm              | 3.10.10
| Operating System | macOS

**Comment by hzoo** [comment]
Is it possible to try upgrading to babel 7? We're in the process of doing a beta before the actual babel 7 release, and it should be a simple upgrade for most projects (Babel itself is using it).

> but I'd argue this is broken enough to warrant a fix in Babel 6

I think the issues with only has always been an issue for a while now and people gotten around that (its clearly an issue but we don't have resources to backport and fix everything in 6.x).

**Comment by ockham** [comment]
Okay, I might wait for Babel 7 (beta) then.

**Comment by hzoo** [comment]
beta.0 is out, so closing
