### ISSUE TITLE
Cannot find module 'caniuse-db'

### ISSUE THREAD

**Issue by An0nymous0** [babel/babel#6068]
I'm not sure if it's related to babel, but I've found a similar problem in github.
https://github.com/Fyrd/caniuse/issues/3073

Recurrence steps and procedures：https://github.com/An0nymous0/error-demo

**Comment by hzoo** [comment]
At first glance, I don't think we have a dependency on caniuse-db anywhere? Thanks for the issue/repro though, just seems unlikely.

**Comment by hzoo** [comment]
https://unpkg.com/babel-preset-env@1.6.0/lib/index.js

Module build failed: Error: Cannot find module 'caniuse-lite' (While processing preset: "/home/data/demo/error-demo/node_modules/babel-preset-env/lib/index.js")

there shouldn't be a reference to caniuse in any of the code in preset-env https://github.com/babel/babel-preset-env/tree/master/src. I would clear your npm/yarn cache and remove node_modules?

**Comment by hzoo** [comment]
Ok it might be an issue with browserslist, either way sounds like a yarn/npm issue? We haven't had any other reports of this and we haven't released in a while

**Comment by An0nymous0** [comment]
@hzoo  I tried to delete node_modules，Also tried to clear npm cache,And finally through the relegation caniuse-lite can be resolved,

**Comment by An0nymous0** [comment]
@hzoo 如果确定跟babel无关，我将关闭它，避免浪费更多人的时间。

**Comment by hzoo** [comment]
ok looks like its from browserslist which is a dependency in preset-env but not sure why it would fail to install
