### ISSUE TITLE
BlockScoped bindings refer references used before declaration

### ISSUE THREAD

**Issue by boopathi** [babel/babel#6069]
Choose one: is this a bug report or feature request?

**Bug**

### Input Code

```js
function foo() {
  let a = 1;
  function bar() {
    console.log(a); // Should be a ReferenceError here
    let a = 2;
    console.log(a);
  }
  bar();
}
foo();
```

Reproduced here - http://astexplorer.net/#/gist/086005439d9d323af24081811578a85e/af255c454f68a59cf1a487f94fc8ff1cd464044b

### Expected Behavior

1. ReferenceError
1. binding of first referenced `a` should be null.

### Current Behavior

1. No Error
1. binding of first referenced `a` is the `let` declaration - `let a = 2`

### Context

Babili

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6 and 7

**Comment by nveenjain** [comment]
The Reference Error you are talking about is TDZ ( temporal dead zone ) and this is a feature, you can turn on the error reporting here, but the implementation for that code is slow. So it is not enabled by default.

**Comment by boopathi** [comment]
Ah! yeah. Thanks.
