### ISSUE TITLE
Transformer API

### ISSUE THREAD

**Issue by sebmck** [babel/babel#607]
Details/discussion to come.

**Comment by ooflorent** [comment]
I'm working on a project where we need to instrument some parts of our code. Since we are using 6to5 and it generates an AST, we though it would be great to be able to add a custom transformer without having to re-parse the JS.

Is there any way to do it?
Doing this would help a lot:

```js
to5.transform(file, {
  custom: [
    require('my-transformer')
  ]
})

**Comment by sebmck** [comment]
@ooflorent Not currently, hence this issue.

**Comment by ooflorent** [comment]
Well, I hope this feature will land soon! Second parsing is total pain with our codebase...

**Comment by sebmck** [comment]
@ooflorent Hopefully. You can already get the transformed ast if that's useful to you:

```javascript
var result = require("6to5").transform("code here", {
  code: false // doesn't generate the code from the ast
});
result.ast;

```

**Comment by ooflorent** [comment]
@sebmck Thanks for the trick but it does not fit to our needs since we use 6to5ify :disappointed: 
If I implement custom transformers to 6to5, would the PR be merged?

**Comment by lukescott** [comment]
@ooflorent This is sort of already possible now, it's just a bit hackish, and you have to update it when the structure of the code changes:
```javascript
var lib6to5 = "6to5-core/lib/6to5";
var util = require(lib6to5 + "/util");
var types = require(lib6to5 + "/types");
var transform = require(lib6to5 + "/transformation");
var Transformer = require(lib6to5 + "/transformation/transformer");

var templateName = "myTemplate";
util.templates[templateName] = util.parseTemplate(templateName, "... js code ...");
var transformerName = "myTransformer";
transform.transformers[transformerName] = new Transformer(transformerName, {
// ... transformer code here
});
```
Just make sure to require that file before you require 6to5ify, gulp-6to5, etc.

I'm sure that sebmck is still working out how he wants to expose an API for this.

What ever that looks like it would be nice to be able to reference a node module or file. I have some custom transformers that I use in a couple projects that I'd like to put in a separate repo. For now I'm using a local file.

**Comment by sebmck** [comment]
@ooflorent 

>  If I implement custom transformers to 6to5, would the PR be merged?

Not at the time, no. I don't want to support this prematurely.

**Comment by sebmck** [comment]
Prerequisites are #780 and a stable [ESTree spec](https://github.com/estree/estree).

**Comment by sebmck** [comment]
Superseded by #883.
