### ISSUE TITLE
Babel doesn't validate Promise.all as a function, allows Promise.all[]

### ISSUE THREAD

**Issue by abritinthebay** [babel/babel#6072]
Choose one: is this a bug report or feature request?
Potential bug.

Babel parses `Promise.all[]` fine, but ideally it should error like like does with `Promise.all{}` as this is incorrect syntax.

### Input Code
```js
const foo = Promise.resolve();
let bar = Promise.all[foo];
```

Example REPL:
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code_lz=MYewdgzgLgBAZiEMC8MAKAnEBbAlhAUwDoMCIQAbANwIAoBKAKAoNgCMBDDFdLPQohwoUA2ghABdIA

### Babel Configuration (.babelrc, package.json, cli command)
Any. Inc repl.

### Expected Behavior
Should error with `Unexpected token`, as it does with `{}`. This is assuming Babel wants to validate the built ins. 

### Current Behavior
Parses the incorrect syntax into the output file (which will then error in browsers or node when executed).

### Possible Solution
This is almost certainly because there is no validation for Promise as a built-in in ES2015. It's just treating it as `obj.arr` but it seems like built-ins should be validated.

If the answer to that is "this is out of scope", that's fine. Just wanted to raise the question, this seems like an ideal test as it's an instant error in browsers.

### Context
Noticed this when debugging an error in production code.

### Your Environment
Can be reproduced in REPL so not relevant.

**Comment by hzoo** [comment]
`let bar = Promise.all[foo];` wouldn't be a syntax error? The error you get is a runtime error. This seems better as a linting rule, unless we think babel should start doing this sort of behavior (eslint covers this although we could integrate better)

**Comment by loganfsmyth** [comment]
> Should error with Unexpected token, as it does with {}. This is assuming Babel wants to validate the built ins.

It's not an unexpected token from a syntax standpoint, it is accessing a property on the `all` function.

**Comment by abritinthebay** [comment]
Absolutely fair enough. Wanted to double check what the stance would be on validating these type of things.

Perfectly reasonable as a lint rule.
