### ISSUE TITLE
Update Class Fields to Stage 3 and change default behavior

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6073]
Reference: https://github.com/babel/proposals/issues/19

- [ ] Move class properties from Stage 2 to 3. This means making a change similar to https://github.com/babel/babel/commit/5492fe130a682afe3a63d3e2ff16b10ed4c8b51e where you move the plugin to the next stage
- [ ] Change the spec option to be the "normal" option. You can find the references to `"spec"` with `state.opts.spec` or just grepping for `spec`. This means we want the default behavior to become what is currently "spec". Similarly we want the "normal option to be "loose" now.
  - In essence we are removing the spec option entirely and adding a loose option.
  - spec -> default, default -> loose
---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] check the class properties package/folder: https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-class-properties
- [ ] follow the steps above in changing the behavior for src/
- [ ] test/ fixtures folder https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-class-properties/test/fixtures. I guess you could rename general/ to loose/ and spec/ to general/?
- [ ] update the readme as well

**Comment by kedromelon** [comment]
i can work on this later!

**Comment by cilice** [comment]
Hey! I’d like to take this, even if I’ve never contributed to Babel before.
