### ISSUE TITLE
Split the export-extensions plugin into two

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6075]
Reference: https://github.com/babel/proposals/issues/19

The proposal has been split for a long time now but we haven't changed it. Now's an opportunity!
There is https://github.com/babel/proposals/issues/16 and https://github.com/babel/proposals/issues/17.

- [ ] export-ns-from is moving to Stage 2 (and potentially later skipping the process but irrelevant atm)
- [ ] export-default-from is staying at Stage 1 and also having some other changes
- [ ] moving the stages is similar to https://github.com/babel/babel/pull/5877
- [ ] splitting the package in 2 however means you need to make a new folder for each, etc.

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md)
  - [ ] at minimum you'll need to run `make bootstrap` after cloning.
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR
- [ ] make the changes above

**Comment by kedromelon** [comment]
interested in helping out here!

**Comment by echo304** [comment]
@kedromelon If you haven't started it, can I tackle this issue? 😄

**Comment by kedromelon** [comment]
@echo304 go for it!

**Comment by existentialism** [comment]
@echo304 feel free to join our slack if you have any questions!

**Comment by echo304** [comment]
@existentialism I don't know why but I couldn't join slack. I have a question BTW 😄 
After I create new directory inside `packages` directory for new plugin(here...for `export-default` and `export-namespace`), do I need to do something with the package setting...?
I've done `make build` but it seems that my test code couldn't find new package `babel-plugin-transform-export-default` and `babel-plugin-transform-export-namespace` ... 😢

**Comment by hzoo** [comment]
@echo304 ahh http://slack.babeljs.io/ is down 😛

**Comment by echo304** [comment]
I've done `make bootstrap` again but it still couldn't find new plugins...hmmm...it's weird... 🤔 
<img width="634" alt="2017-08-10 12 25 25" src="https://user-images.githubusercontent.com/16456651/29129652-788c5e4c-7d62-11e7-87c2-31ca285e91d5.png">

**Comment by hzoo** [comment]
I think I added your email so you can join slack if you didn't see it already
