### ISSUE TITLE
Error in IE9 by babel-plugin-transform-es2015-spread

### ISSUE THREAD

**Issue by songguangyu** [babel/babel#6077]
In babel-plugin-transform-es2015-spread/src/index.js line 99。
`
  In ie9 console.log(...args) parse console.log.apply(console, arguments)
`

But in IE9 console.log is not instance Function 
So in loose model, it should parse
`
Function.prototype.apply.call(console.log, console, arguments);
`

**Comment by loganfsmyth** [comment]
I'd qualify this as something for a polyfill should resolve. Babel expects code to behave according to the ES specs, generally it is up to polyfills to standardize that interface to meet expectations expectations.

I assume there are polyfills available, but even just a simple

```
(function(){
  window.console = {
    log: Function.prototype.bind.call(window.console.log, window.console)
  };
})();
```
would address this, though obviously there are other properties.

**Comment by songguangyu** [comment]
It shoud be add in babel-polyfill ?

**Comment by jridgewell** [comment]
No, this is an IE specific screw up and should be handled by some shim.

**Comment by songguangyu** [comment]
thank you
