### ISSUE TITLE
require.extensions is not supported by webpack. Use a loader instead.

### ISSUE THREAD

**Issue by Tin-Nguyen** [babel/babel#6089]
Hi all,

I got a WARNING when build with webpack on some babel components

```sh
WARNING in ./~/babel-register/lib/node.js
6:19:51 AM watch.1 |  require.extensions is not supported by webpack. Use a loader instead.
6:19:51 AM watch.1 |   @ ./~/babel-core/register.js 3:17-42
6:19:51 AM watch.1 |   @ ./src/index.js
```

Do you have any solution to fix it?

**Comment by Tin-Nguyen** [comment]
Hi all,

It's my mistake, I still keep `require('babel-core/register')` in my code. After removed it, the build works well without any warnings.

Hope this can help others out soon.

**Comment by existentialism** [comment]
👍
