### ISSUE TITLE
Polyfil NodeList.forEach?

### ISSUE THREAD

**Issue by ericandrewlewis** [babel/babel#6091]
This is a question, sorry if this is the wrong place to ask it!

I believe that `NodeList.forEach` is in the WhatWG DOM spec, but is not polyfilled by the Babel polyfill. This makes sense because the Babel polyfill is for JavaScript language built-ins, not Web APIs. Is there a suggestion for what polyfill folks should use for DOM built-ins?

**Comment by loganfsmyth** [comment]
Could you file this on https://github.com/zloirock/core-js?

As a general question, I agree that it's hard to say if Babel should be responsible for polyfilling DOM stuff, but since `core-js` already does `values` and `keys` and `entries` it should probably do `.forEach` too.

**Comment by loganfsmyth** [comment]
Alright someone else filed it: https://github.com/zloirock/core-js/issues/329
