### ISSUE TITLE
babel-preset-react includes Flow, which conflicts with babel-preset-typescript.

### ISSUE THREAD

**Issue by threehams** [babel/babel#6095]
When trying out babel-preset-typescript with babel-preset-react, I learned that the React preset comes bundled with Flow. This hasn't caused any problems in Babel <7, as Flow doesn't conflict with anything else.

With Babel 7 and the Typescript preset, the current experience is to see an error about the conflict between Flow and Typescript, then search the documentation for each of the presets used, figure out which one is including Flow, and replace it with the three React plugins.

```js
{
  plugins: [
    "syntax-jsx",
    "transform-react-jsx",
    "transform-react-display-name"
  ],
  presets: ["typescript"],
}
```

My question is: should Flow still be bundled in this preset? Or, should the error message describe what is causing Flow to be included? It's strange to have a type system unrelated to React to be included in the React preset. This was a quick fix for me, but the "me" from one year ago may have spent hours trying to figure out why Typescript and React together result in an error.

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  presets: [
    "typescript",
    "react"
  ]
}
```

### Current Behavior
Error: "Cannot combine flow and typescript plugins".

### Possible Solution
Include extra information in error message (flow is included in babel-preset-react, use React plugins instead)
Remove preset-flow from babel-preset-react in v7.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-alpha.19
| node             | 8.1.4
| npm              | 5.0.3
| Operating System | Windows 10

**Comment by yenshih** [comment]
Same problem!
Here's my webpack config:
```js
{
    test: /\.tsx?$/,
    use: [{
        loader: 'babel-loader',
        options: {
            presets: [
                ['env', {
                    modules: false,
                    useBuiltIns: true,
                    targets: {
                        browsers: ['last 2 versions', 'ie >= 9']
                    },
                }],
                'typescript',
                'react'
            ],
            plugins: [
                'syntax-dynamic-import',
                ['transform-runtime', {
                    polyfill: false,
                    regenerator: true
                }]
            ],
        }
    }],
    exclude: /node_modules/
}
```

### Expected Behavior
It may works.

### Current Behavior
Module build failed: Error: *Entry file path*: Cannot combine flow and typescript plugins.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  ^7.0.0-alpha.19
| node             | 8.1.2
| npm              | 5.3.0
| Operating System | macOS Sierra 10.12.6

**Comment by yenshih** [comment]
May I ask why did you close this issue? @nicolo-ribaudo

**Comment by loganfsmyth** [comment]
I'm gonna assume it was accidental.

**Comment by loganfsmyth** [comment]
I'm not sure I understand that argument. React and JSX are also usable in Typescript.

**Comment by ljharb** [comment]
Of course they are; you can use React and Angular with Flow, TypeScript, or neither. However, Flow is still "related" to React in that it's commonly used through the majority of the React community, and is endorsed by the React team - just like TypeScript is commonly used through the majority of the Angular community, and is endorsed by the Angular team.

"related" doesn't mean "inextricably entangled" - but the two pairs are surely related.

**Comment by loganfsmyth** [comment]
Right, but I still don't hear an argument in here for why enabling `react` should auto-enable Flowtype parsing. For the average user what is wrong with needing to do `'react', 'flow'` in your presets instead?

> it's commonly used through the majority of the React community

I feel like that's an exaggeration. The majority of the community uses no type checking at all.

**Comment by ljharb** [comment]
I think it makes sense for babel-preset-react to have an *option* that controls flow. I think that a default of "use flow" also makes sense, and that it's better for TypeScript users to have to do an extra step with React than for Flow users to have to do so.

Users who use no type checking (hi, that's me!) really aren't affected either way, so they don't have to be part of the discussion.

**Comment by loganfsmyth** [comment]
> I think it makes sense for babel-preset-react to have an option that controls flow.

Babel's plugin architecture does not currently allow that. It's all or nothing for Flow parsing until we can change that. Either the `react` preset always works with `typescript`, or never, and never seems like an extremely confusing behavior for users.

**Comment by ljharb** [comment]
I'm confused, babel-preset-airbnb [takes options](https://github.com/airbnb/babel-preset-airbnb/blob/master/index.js#L44) - why couldn't babel-preset-react?

**Comment by loganfsmyth** [comment]
Ugh fair, sorry, I said a dumb thing. There are cases that can't be handled with options, but this case isn't one of them.

So that is an option, we could do

```
presets: [
  ['react', {noFlow: true}],
]
```
for this case.

I still think it's super weird to include Flowtype handling in a preset that in no way implies usage of Flow, but I guess that's been an existing issue.

Babel's entire model at the moment is based on opting _into_ transforms as a whole, and opting _out_ of specific details of transformation, but the `react` preset is the one case we have right now where you opt into JSX transformation and automatically also get transformation of Flow, and then have to opt out of the Flow transform as a whole, rather than toggling how the transform itself behaves.

**Comment by ljharb** [comment]
It seems like the expedient course of action is to first add an option disabling Flow (semver-minor) to unblock typescript users, and then debate whether the default could/should change (semver-major)?

**Comment by hzoo** [comment]
This is 7.0 alpha though, and we knew there were going to be some issues (not necessarily this one though)

**Comment by chicoxyzzy** [comment]
Most of React people I know are TypeScript developers. I can't guarantee that's a good sample though. Flow as default seems fine to me, but actually I think most of people prefer to use ES by default. Flowtype and TypeScript people do some configuration anyway. As for me, I use TS, Flow or untyped ES depending on project.

**Comment by arvigeus** [comment]
When I first set up a project using babel-preset-react, I was surprised to see that it includes flow. I think it should be dropped.

**Comment by ramasilveyra** [comment]
Just created two prs with the solutions discussed until now:
- Remove Flow support in React preset #6118
- Add `noFlow` option to React preset #6119

**Comment by Kovensky** [comment]
Wasn't one of the very early decisions in the babel 7 process (even before `typescript` parsing was a thing) to separate the `react` and `flow` presets?

**Comment by existentialism** [comment]
@Kovensky the initial version of https://github.com/babel/babel/pull/5468 did essentially what #6118 is doing, but after some discussions with the React team we wound up adding the `requireDirective` option on `transform-flow-strip-types` by default.
