### ISSUE TITLE
_guessExecutionStatusRelativeTo bug

### ISSUE THREAD

**Issue by dounan** [babel/babel#6097]
I was looking through introspection.js and noticed a potential issue with `_guessExecutionStatusRelativeTo`.

https://github.com/babel/babel/blob/75808a2d14a5872472eb12ee5135faca4950d57a/packages/babel-traverse/src/path/introspection.js#L273

The `type` property to the t.VISITOR_KEYS should be `commonPath.type`, and not the types of the relationship paths right?

**Comment by hzoo** [comment]
I think @jridgewell made a PR about this https://github.com/babel/babel/pull/5741

**Comment by jridgewell** [comment]
Yup, this'll be fixed by #5741.
