### ISSUE TITLE
The alpha version still does not support decorators and generator

### ISSUE THREAD

**Issue by jokerapi** [babel/babel#6101]
<img width="726" alt="2017-08-14 2 25 35" src="https://user-images.githubusercontent.com/19544032/29260442-7b1c4684-80fc-11e7-9665-2fd28c7e5065.png">

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-alpha.19
| node             |  8.0.0
| npm              |  5.0.0
| Operating System |

**Comment by xtuc** [comment]
Could you please share your Babel configuration?

**Comment by nicolo-ribaudo** [comment]
Decorators on generators are not yet supported because, even if the parser now supports them, `babel-plugin-transform-decorators` still uses the old parser plugin.

I think @peey is working on the new implementation.

**Comment by peey** [comment]
Yep. I'll soon open a PR, in the meantime you can check out my [WIP branch on the transform decorators](https://github.com/peey/babel/tree/decorators-2-transform-wip/packages/babel-plugin-transform-decorators-2)

**Comment by jokerapi** [comment]
@xtuc 
.babelrc
```
{
  "presets": [
    "es2015",
    "stage-0",
    "flow"
  ],
  "plugins": [
    "lodash",
    "transform-decorators-legacy"
  ],
  "env": {
    "production": {
      "plugins": [
        "transform-remove-console"
      ]
    },
    "staging": {
      "plugins": [
        "transform-remove-console"
      ]
    }
  }
}
```
| software         | version(s)
| ---------------- | -------
| es2015            |  7.0.0-alpha
| stage-0             |  7.0.0-alpha
| flow              |  7.0.0-alpha
| Operating System |

**Comment by hzoo** [comment]
It never did since we are in the process of implementing decorators in https://github.com/babel/babel/pull/6107, closing
