### ISSUE TITLE
this es5 not same _this

### ISSUE THREAD

**Issue by AdrianHastro** [babel/babel#6105]
React.createElement("input", { id: "inp_city_id", name: "inp_city_id", defaultValue: 137, onFocus: function onfocus() { hlentry(_this); });

why "_this" not element input ?

**Comment by nicolo-ribaudo** [comment]
What is the original (uncompiled) code?

**Comment by AdrianHastro** [comment]
@nicolo-ribaudo 
<input id="inp_city_id" name="inp_city_id" value="137" onfocus="hlentry(this)" type="Text">

**Comment by nicolo-ribaudo** [comment]
We also need your configuration (babelrc and package.json).

Are you using some plugin to transform string event handlers to functions (since Babel doesn't do that by default)? If yes, probably it is a bug with that plugin

**Comment by AdrianHastro** [comment]
i'm used htmltojsx for convert html, then the result of htmltojsx to be convert using babel.

{presets:['es2015','stage-2','react'], plugins:['transform-es2015-destructuring','transform-es2015-arrow-functions','transform-jscript','transform-object-set-prototype-of-to-assign','transform-object-rest-spread']}

**Comment by nicolo-ribaudo** [comment]
What is the output of htmltojsx?

**Comment by AdrianHastro** [comment]
var NewComponent = React.createClass({
  render: function() {
    return (

        <input id="inp_city_id" name="inp_city_id" defaultValue={137} onFocus="hlentry(this)" type="Text" />
    );
  }
});

**Comment by nicolo-ribaudo** [comment]
Babel is working correctly: the `this` inside an arrow function should refer to the outer `this` (thus,  to the outer class). Infact, there shouldn't be a `var _this = this` somewhere to store the correct `this` used by the arrow function.

If you think that it should refer to the HTML element, you should open an issue in the htmltojsx repository.

Anyway, usually it is expected that, when using react, `this` refers to the react component and not to the html element. To get a reference to the element, you may use the [ref](https://facebook.github.io/react/docs/refs-and-the-dom.html) property.

**Comment by AdrianHastro** [comment]
ok thanks @nicolo-ribaudo 
i think, i will be use the <code>ref</code> property
