### ISSUE TITLE
Class fields should be configurable:true

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6108]
Spec updated: https://github.com/tc39/proposal-class-fields/issues/35

It defaults to false in Babel here: https://github.com/babel/babel/blob/7.0/packages/babel-plugin-transform-class-properties/src/index.js#L28 We should add `configurable: true` to that config.

```js
    Object.defineProperty(REF, KEY, {
      // configurable is false by default
      enumerable: true,
      writable: true,
      value: VALUE
    });
```

---

> We'd ask that if you've already made a PR you'd let someone new take this 😄 , thanks!

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR (this might be down, we can add you manually)
- [ ] check the class properties package/folder: https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-class-properties
- [ ] follow the steps above in changing the behavior
- [ ] fix tests https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-class-properties/test/fixtures
- [ ] update the readme if necessary

**Comment by reznord** [comment]
I'd love to take this issue.

**Comment by existentialism** [comment]
@reznord go for it!

**Comment by littledan** [comment]
Thanks for picking this up, and sorry about my typo!

**Comment by reznord** [comment]
That's real quick :sweat_smile:
