### ISSUE TITLE
event es2015 is undefined

### ISSUE THREAD

**Issue by AdrianHastro** [babel/babel#6122]
how to use the <code>event</code> ?

**Comment by xtuc** [comment]
Could you provide more context about your issue? The important informations we need are in the [ISSUE_TEMPLATE](https://raw.githubusercontent.com/babel/babel/7.0/.github/ISSUE_TEMPLATE.md).

**Comment by nicolo-ribaudo** [comment]
If the context of this issue is the same of #6105, you should ask to the htmltojsx repository: it's their job to generate the JS and thus to provide the event variable.
