### ISSUE TITLE
Is using arrow function define the class method an official proposal?

### ISSUE THREAD

**Issue by zheeeng** [babel/babel#6129]
Hi, there. Maybe this topic has been issued, but it's too hard to find out through searching. I'm noticed that when I enable stage-0 syntaxes, I can use arrow function to define the class method in babel.

I did an experiment on this feature:

```
class Base {
  constructor (props) {
    this.log2 = this.log2.bind(this)
  }
  log1 = () => { console.log('base log1'); }
  log2 () { console.log('base log2'); }
  log3 = () => { console.log('base log3'); }
}

class Child extends Base {
  log1 () { console.log('children log1');  };
  log2 () { console.log('children log2') }
  log3 () { super.log3() }
  log33 () { super.log3() }
}

var v = new Child()
v.log1() // "base log1"
v.log2() // "children log2"
v.log3() // "base log3"
v.log33() // Cannot read property 'call' of undefined
```

v.log2() and v.log3() is same as what I expected. But v.log1() and v.log33() make me confused. I can't find that official es-next proposal allows us using arrow function to define the class method. I know that this usage is convenient for using React, but I wonder does it is an official proposal and is this implement correct(sorry for I didn't look up the details of es-next specifications, I just read it thoroughly from https://github.com/tc39/ecma262)?

**Comment by hzoo** [comment]
I don't get the question, are you asking if using class properties syntax is a proposal? Then yes.

**Comment by zheeeng** [comment]
@hzoo Thx for letting me know it calls class properties syntax, I have seen it many times exclude using arrow function as property in the feature demonstrations. I'm wondering whether it breaks the extends behavior is reasonable.

**Comment by hzoo** [comment]
Oh well yeah it shouldn't be breaking anything, so it may be a bug

**Comment by zheeeng** [comment]
@hzoo can you re-open it and append a bug tag?

**Comment by loganfsmyth** [comment]
The code is working as expected.

     log33 () { super.log3() }

says "call the 'log3' method on the `Base.prototype` object, but there isn't one. `log3` in `Base` is a class field, so it is an instance property, not one stored on the prototype.

**Comment by zheeeng** [comment]
@loganfsmyth Thx, I finally figured it out! Babel implements it exactly correct. In `Base`, log1 and log3 aren't be extended by Child, they are the properties, which initialized by implicit Child constructor, of Child instance. The only inheritable methods are log2.
