### ISSUE TITLE
register & preset-env: Error: Options {"loose":true} passed to ...

### ISSUE THREAD

**Issue by sdgluck** [babel/babel#6130]
Hello- I think am reporting a __bug__, but I can't be sure. Maybe I'm using the tools incorrectly.

- I am in the process of splitting out a large CLI application to make use of Lerna.
- I have one "entry" package that uses `babel-register` and `babel-preset-env` which requires the other modules (linked by Lerna).
- The other modules are all written using ESnext.
- My thinking was: instruct `babel-register` to only compile packages whose name have the namespacing prefix (`wpk`) so that I don't have to manage a compile-step for each package as they more or less all rely on being invoked from the "entry" package anyway.

However when setting `ignore=false` for `babel-register` an error is thrown (see below). And of course without it the packages won't be compiled on-the-fly and syntax errors are aplenty. 

Edit: I was pointed to [this issue](https://github.com/babel/babel-preset-env/issues/334) but the solutions there are not working for me. (Or I am doing it wrong?)

### Repro

[Please see here for a repro of the problem](https://github.com/sdgluck/__babel-repro-sdgluck-1).

To save you looking at the repro:

__index.js__
```js
require('babel-polyfill')
require('babel-register')({
  ignore: false, // this seems to cause the error
  only: /wpk/ // this can be removed and the error still occurs
})
//...
```

__.babelrc__
```json
{
  "presets": [
    ["env", {
      "debug": true,
      "targets": {
        "node": "0.12"
      }
    }]
  ]
}
```

### Current Behavior

When I run the application it errors:

```sh
C:\xampp\htdocs\__babel-repro\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to C:\xampp\htdocs\__babel-repro\node_modules\babel-preset-env\lib\index.js which does not accept o
ptions. (While processing preset: "C:\\xampp\\htdocs\\__babel-repro\\node_modules\\babel-preset-env\\lib\\index.js") (While processing p
reset: "C:\\xampp\\htdocs\\__babel-repro\\node_modules\\babel-preset-env\\lib\\index.js")
    at C:\xampp\htdocs\__babel-repro\node_modules\babel-core\lib\transformation\file\options\option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (C:\xampp\htdocs\__babel-repro\node_modules\babel-core\lib\transformation\file\options\option-manage
r.js:275:20)
    at OptionManager.mergePresets (C:\xampp\htdocs\__babel-repro\node_modules\babel-core\lib\transformation\file\options\option-manager.
js:264:10)
    at OptionManager.mergeOptions (C:\xampp\htdocs\__babel-repro\node_modules\babel-core\lib\transformation\file\options\option-manager.
js:249:14)
    at OptionManager.init (C:\xampp\htdocs\__babel-repro\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:1
2)
    at compile (C:\xampp\htdocs\__babel-repro\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\xampp\htdocs\__babel-repro\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\xampp\htdocs\__babel-repro\node_modules\babel-register\lib\node.js:15
4:7)
    at Module.load (module.js:503:32)
```

Edit:

I have also tried with `7.0.0-alpha.19` versions of `babel-register`, `babel-polyfill`, and `babel-core`.

__.index.js__
```js
//...
require('babel-register').default({
  ignore: [/node_modules\/(?!wpk.*)/]
})
//...
```

I then get this error:

```sh
C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:139
      throw e;
      ^

TypeError: [BABEL] C:\xampp\htdocs\wpk\packages\wpk\node_modules\semver\semver.js: Cannot read property 'default' of undefined (While pro
cessing: "C:\\xampp\\htdocs\\wpk\\packages\\wpk\\node_modules\\babel-preset-env\\lib\\index.js")
    at buildPreset (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-preset-env\lib\index.js:139:48)
    at loadDescriptor (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:248:14)
    at loadPresetDescriptor (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:330:14)
    at C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:76:14
    at Array.map (native)
    at OptionManager.mergeOptions (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:75:34)
    at OptionManager.init (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:131:14)
    at manageOptions (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\option-manager.js:59:30)
    at loadConfig (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\config\index.js:20:38)
    at loadOptions (C:\xampp\htdocs\wpk\packages\wpk\node_modules\babel-core\lib\index.js:114:37)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.25.0
| node             | 8.0.0
| npm              | 5.0.0
| Operating System | Windows 10

**Comment by jridgewell** [comment]
In order for me to debug this, I'm going to need a minimal repo that produces the error.

**Comment by sdgluck** [comment]
Hey Justin- thank you for looking at this. There is a link to a repro in the issue body. If you need any more information I would be happy to assist.

**Comment by sdgluck** [comment]
Link to repro again here: https://github.com/sdgluck/__babel-repro-sdgluck-1

**Comment by jridgewell** [comment]
Perfect, somehow missed that.

**Comment by loganfsmyth** [comment]
@sdgluck @jridgewell `ignore: false` is rarely a good idea. `babel-preset-env` is inside `node_modules`, and since you've told `babel-register` to compile _everything_ with that `ignore: false`, `babel-preset-env` is going to try to compile _itself_ which leads to a cyclic dependency, and an exported value of `undefined`, which causes the error above.

We can definitely make better error messaging around this. This _may_ also be caught by https://github.com/babel/babel/pull/5586.

The short answer here is, don't use `ignore: false` when using `babel-register`, ever. It's reasonable in other usecases for Babel, but it's a recipe for disaster with `babel-register`.

If you need to compile specific node modules, explicitly whitelist them, e.g.

```
ignore: /node_modules\/(?:some-module|some-other-module)/,
```

**Comment by sdgluck** [comment]
@loganfsmyth Thanks for the explanation- useful to know. I had already tried that workaround as it was suggested to me by @hzoo on Babel's Slack. I have put in a [branch on my repro called `ignore-modules`](https://github.com/sdgluck/__babel-repro-sdgluck-1/tree/ignore-modules) to demonstrate that it does not work, unfortunately. But if you have time to look it would be much appreciated, because I may be doing something wrong!

Still using `babel-preset-env`, and with this `babel-register`  configuration...

```js
// index.js
require('babel-polyfill')
require('babel-register')({
  ignore: /node_modules\/(?:__test__)/
})

require('__test__').hello()
```

```
// node_modules/__test__/index.js
export function hello () {
  console.log('hello from __test__')
}
```

```
// .babelrc
{
  "presets": [
    ["env", {
      "targets": {
        "node": "0.12"
      }
    }]
  ]
}
```

...the error I get is:

```sh
SyntaxError: Unexpected token export
```

As I understand, the `__test__` module should be being passed through Babel?

**Comment by loganfsmyth** [comment]
@sdgluck Sorry, I had a typo, it's `?!`, not `?:`. So `ignore: /node_modules\/(?!__test__)/`

**Comment by existentialism** [comment]
@sdgluck I tested your repo/branch with @loganfsmyth' suggestion and it works:

> hello from __test__

Going to close for now, but let us know if you continue to have issues!

**Comment by MadRabbit** [comment]
this is still happening for me with babel-preset-env if do the following

```js
require('babel-register')({
  cache: true,
  ignore: /\.(css|svg)/
});
```

**Comment by loganfsmyth** [comment]
@MadRabbit That is expected behavior. You need to ignore the presets and plugins themselves when compiling using `babel-register` otherwise you'll get this error.
