### ISSUE TITLE
Infra: build/test master before publish

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6134]
Similar to smoke tests: https://github.com/babel/babel/issues/1837

Basically we should setup a test such that Babel itself would be able to compile itself with the latest built version in master (currently 7.0). Then we can find basic issues without having to publish first. Basic idea would be to just write so some temporary folders and then link something?

It would need to be able to revert back if something fails since otherwise it wouldn't even be able to compile anymore.

---

Context: Babel uses Babel to compile itself (we write using ES6+ and compile to ES5 for npm). However do that, we download the last version of Babel on npm. This also means that we have to publish to npm before testing that last published version on Babel itself. Ideally we would have a setup where before we publish (or on every PR if we wanted), we could switch out compiling Babel with the version of itself on master. Maybe it means doing an npm pack/link etc, but we should also check that it works with the monorepo/yarn/lerna setup that we have?

**Comment by ljharb** [comment]
You should definitely be able to use `npm link`; or even `file://./` or similar. Not sure about working with lerna, but it should work.

Worst case, you could set up a separate package folder like `babel-test`, that on `postinstall` does the link/copy, and imports and re-exports babel.

**Comment by jkarttunen** [comment]
Test scripts maybe need to edit package.json?
