### ISSUE TITLE
Remove old @jsx pragma check from the react transform plugin

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6141]
You used to have to have a `// @jsx` pragma at the top of the file to transpile, but that's been gone since React `0.12`. We already throw an error about this being deprecated so we should just drop this in Babel 7 (esp. since React is v16)

Can just remove this code (and the regex), and maybe can delete a test or two. 
https://github.com/babel/babel/blob/cee4cde53e4f452d89229986b9368ecdb41e00da/packages/babel-plugin-transform-react-jsx/src/index.js#L27-L38

---

> We'd ask that if you've already made a PR you'd let someone new take this 😄 , thanks!

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] [Join our slack](http://slack.babeljs.io/) if you haven't already if you need more immediate help or just comment in this issue/PR (this might be down, we can add you manually)
- [ ] check the package/folder: https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-react-jsx
- [ ] follow the steps above in changing the behavior
- [ ] fix tests https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-class-properties/test/fixtures
- [ ] ~~update the readme if necessary~~
- [ ] come up with a changelog message for https://github.com/babel/website/blob/master/_posts/2017-03-01-upgrade-to-babel-7.md (extra)

**Comment by echo304** [comment]
Let me tackle this issue ✋

**Comment by hzoo** [comment]
@echo304 if it's ok with you, I'd like someone new to take this one 😄

**Comment by echo304** [comment]
@hzoo sure! no problem 😄

**Comment by asthas** [comment]
@hzoo I'd like to contribute!

**Comment by existentialism** [comment]
@asthas go for it!

**Comment by asthas** [comment]
@hzoo and @existentialism I have prepared a PR for this issue. Please review it. #6145

**Comment by hzoo** [comment]
Closed by https://github.com/babel/babel/pull/6145

**Comment by maranomynet** [comment]
I'm curious: Why is this removed?
This feature is generally, incredibly useful when using non-React hyperscript libraries. To be able to casually use JSX without having to resort to editing a project-wide config file.
The explicit marker at the top of file seemed like a nicely readable, explicit way of configuring the JSX behavior, and is especially useful if a project happens (for some reason) to use more than one hyperscript library.

**Comment by hzoo** [comment]
@maranomynet I think you may be confused? Maybe you need to check the PR/code, but basically this removes the React.DOM check, not `@jsx` option

**Comment by kzc** [comment]
@hzoo I'm confused. It looks like the parsing of the `/* @jsx override */` in comments has been removed instead of just the React.DOM check. Only the babel options are inspected as of this PR.

https://github.com/babel/babel/pull/6145/files#diff-18da325252fa9074bd50f8b406413a01L5

https://github.com/babel/babel/pull/6145/files#diff-18da325252fa9074bd50f8b406413a01L30

Or has comment pragma parsing has been centralized elsewhere?

**Comment by hzoo** [comment]
Ohh ok I was confused myself then lol.

Ok then we need to add the `id = matches[1]` part back in and we only needed to removed the ` if (id === "React.DOM") {` check, good catch

**Comment by kzc** [comment]
@hzoo I'm not a Babel user. Just noticed this change on the Babel twitter feed and its implications to Buble.

**Comment by hzoo** [comment]
Yeah I know, just wanted to ask if someone wanted to make the change https://github.com/babel/babel/issues/6191

**Comment by maranomynet** [comment]
Yay! :-)

**Comment by asthas** [comment]
@hzoo  I will be able to revert this PR.

**Comment by hzoo** [comment]
Basically instead of what I said above in the original post,

```
     if (id === "React.DOM") { 
       throw file.buildCodeFrameError(comment, 
         "The @jsx React.DOM pragma has been deprecated as of React 0.12"); 
     } else { 
```

only that needs to be removed
