### ISSUE TITLE
Flow comments plugin creates incorrect code

### ISSUE THREAD

**Issue by diligiant** [babel/babel#6142]
(I opened an issue on the affected repository [react-leaflet#363](https://github.com/PaulLeCam/react-leaflet/issues/363))

Flow-comments output incorrect code when transforming consecutive flow "statements". As shown in the issue linked above,
```
import { GeoJSON as LeafletGeoJSON, type LatLng, type Layer } from 'leaflet';
```
"renders" as 
```
import { GeoJSON as LeafletGeoJSON, /*:: type LatLng*/, /*:: type Layer*/ } from 'leaflet';
```
You'll notice the 2 hanging commas.

Reproducible on the repository @1.6.2

**Comment by hzoo** [comment]
Similar to https://github.com/babel/babel/issues/5626, https://github.com/babel/babel/issues/5600

We haven't really updated the plugin in a while (it's pretty buggy). I think we would recommend .js.flow files, I think we want to continue to use this we will need to rethink how it would work. Comments in general are hard to do

**Comment by diligiant** [comment]
Solid reasoning ;) I thought they (.js.flow) were deprecated based on SO questions. Thank you.

**Comment by simlu** [comment]
Are you planning to continue supporting this plugin? For us this plugin is pretty central and impacts if we want to proceed using flow.
