### ISSUE TITLE
tansform error

### ISSUE THREAD

**Issue by ppeerit** [babel/babel#6147]
```js
const {xxx} = props

['aaa', 'bbb'].forEach(xxx)
```

if dont't use `;` will to

`props['aaa', 'bbb'].forEach(xxx)`

and has a error: forEach not a function 

presets: es2015, stage-0, react

**Comment by loganfsmyth** [comment]
That's expected behavior. You need that semicolon there. You'd get the same behavior if you run it in a browser directly.
