### ISSUE TITLE
[7.0] Wrong `this` with class properties and arrow function

### ISSUE THREAD

**Issue by lixiaoyan** [babel/babel#6153]
Babel version: 7.0.0-alpha.19
This bug only happens when using these two plugins together.

### Input Code

``` javascript
const fn = () => {
  return class {
    fn = () => console.log(this);
  };
};
```

### Babel Configuration (.babelrc, package.json, cli command)

``` shell
--plugins transform-class-properties,transform-es2015-arrow-functions
```

### Expected Behavior

``` javascript
const fn = function () {
  return class {
    constructor() {
      var _this = this; // <--
      this.fn = function () {
        return console.log(_this);
      };
    }
  };
};
```

### Current Behavior

``` javascript
var _this = this; // <--
const fn = function () {
  return class {
    constructor() {
      this.fn = function () {
        return console.log(_this);
      };
    }
  };
};
```

**Comment by kedromelon** [comment]
hm, interesting. trying to wrap my head around this. certainly seems like a bug to me, but perhaps someone more confident in their understanding of the spec could chime in

[here's a REPL instance where i was playing with recreating this](https://babeljs.io/7#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code_lz=PTAEAMBcAsEsGdygE4FMBmrn1JA9qAOYA2eARgIbGjRaoBQAFAJSgC8AfKAN72igBjYhXg4AYngK9-_dADt2oFuy4C8c-HmKoAdKUKMYCZgG4-oAL5mr9eiAhHEKDFhz5QAIQrJBw0TTp6dABXOQFIWHVQSh9laV8RHC8feNkFNiVWTkF1TW09PANHU3MbC1t7KDgnNExsXAIvAC8E_1o0egA3b2iKFoyQsIj1OPMhRM8-nnM0xWVstQ0tXX1DapL-Mp0yWDkAEzXjIA)

**Comment by loganfsmyth** [comment]
Certainly seems like a bug to me. Good find.

**Comment by kedromelon** [comment]
think I've found a fix! will get a PR together in a bit.

**Comment by jridgewell** [comment]
Ah damn @kedromelon, I fixed it as part of my work today. See #6158.

**Comment by kedromelon** [comment]
@jridgewell ah darn! well, learned quite a bit in the process anyway 😄
