### ISSUE TITLE
Invalid arrow function destructuring allowed

### ISSUE THREAD

**Issue by jeremybini** [babel/babel#6161]
Bug Report/Spec Compliancy

### Input Code
[Example REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-3&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=false&spec=false&playground=true&code_lz=MYewdgzgLgBAJiAKgCwJZgOYwLwwBQDeMAdKQIYA2FACgE4gAOEANDGawEYwC-AlDgD4YBAFAwYoSCAoBTYhRAY8lGvSa8xE8BGlyFSshvGSds-YrwcN3ESIQp0SomQBcMAIyc3AJh4aRAPQBMCj0AO4QMDK09LRskTIAHgwywFAycIHBAGYArmBpqODwIADyUMjRDpiEJORUdIwsbJx-wlniWlJm-soNahAaQZ0muuYGQ8HG2mO9Vh02HQjllbTVTmxunjAcPn4iQA&stage=0)

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015", "stage-3"]
}
```

### Expected Behavior
Destructuring of arrow function params should comply with the [object rest spread spec](https://github.com/tc39/proposal-object-rest-spread).
```js
const doThing => ({ ...allProps, a, b }) => {} // Should throw error
```

### Current Behavior
Currently, the order is not enforced for destructured arrow function arguments. The destructured argument behaves as described in this previously addressed [issue](https://github.com/babel/babylon/issues/148) for object destructuring.

```js
const doThing = ({ ...allProps, a, b }) => {  // Does not throw error
  console.log(allProps)
  console.log(a)
  console.log(b)
}

doThing({ a: 1, b: 2 })
//  {a: 1, b: 2}
//  1
//  2
```

**Comment by existentialism** [comment]
@jeremybini thanks for the report! this is fixed via https://github.com/babel/babylon/pull/696!

**Comment by jridgewell** [comment]
It'll also be fixed by https://github.com/babel/babel/pull/5971.

**Comment by hzoo** [comment]
So this is already fixed in master?
