### ISSUE TITLE
Some packages missing test coverage 

### ISSUE THREAD

**Issue by kedromelon** [babel/babel#6165]
I noticed there a quite a few packages within the repo with no tests whatsoever. I understand many of these may not necessarily _need_ tests of their own (given the added maintenance effort they would require, etc) but I wanted to open the question -- are there any areas that _are_ worth expanding test coverage on?

In particular, I was thinking that the few transforms that do not yet have tests could perhaps benefit from some. maybe some of those could make decent `beginner-friendly` issues too?

packages without tests:
- babel-helper-bindify-decorators
- babel-helper-builder-binary-assignment-operator-visitor
- babel-helper-builder-react-jsx
- babel-helper-call-delegate
- babel-helper-define-map
- babel-helper-explode-assignable-expression
- babel-helper-explode-class
- babel-helper-fixtures
- babel-helper-function-name
- babel-helper-get-function-arity
- babel-helper-hoist-variables
- babel-helper-optimise-call-expression
- babel-helper-plugin-test-runner
- babel-helper-regex
- babel-helper-remap-async-to-generator
- babel-helper-replace-supers
- babel-helper-wrap-function
- babel-helpers
- babel-messages
- babel-plugin-external-helpers
- babel-plugin-syntax-async-functions
- babel-plugin-syntax-async-generators
- babel-plugin-syntax-class-properties
- babel-plugin-syntax-decorators
- babel-plugin-syntax-do-expressions
- babel-plugin-syntax-dynamic-import
- babel-plugin-syntax-exponentiation-operator
- babel-plugin-syntax-export-extensions
- babel-plugin-syntax-flow
- babel-plugin-syntax-function-bindify
- babel-plugin-syntax-function-sent
- babel-plugin-syntax-jsx
- babel-plugin-syntax-numeric-separator
- babel-plugin-syntax-object-rest-spread
- babel-plugin-syntax-optional-catch-binding
- babel-plugin-syntax-optional-chaining
- babel-plugin-syntax-typescript
- babel-plugin-transform-async-functions
- babel-plugin-transform-es2015-block-scoped-functions
- babel-plugin-transform-es2015-literals
- babel-plugin-transform-eval
- babel-plugin-transform-object-assign
- babel-plugin-transform-object-set-prototype-of-to-assign 
- babel-polyfill
- babel-preset-es2016
- babel-preset-es2017
- babel-preset-stage-0
- babel-preset-stage-1
- babel-preset-stage-2
- babel-preset-stage-3
- babel-preset-typescript
- babel-runtime

**Comment by xtuc** [comment]
Closing, out of scope for now.
