### ISSUE TITLE
update transform-es2015-arrow-functions to default to spec mode

### ISSUE THREAD

**Issue by kedromelon** [babel/babel#6170]
Similar to https://github.com/babel/babel/pull/6076 and https://github.com/babel/babel/pull/6098, `transform-es2015-arrow-functions` can be updated to default to spec mode

the current `spec` mode should become the default, while the current default behavior should be accessible via a `loose: true` option.

- [ ] switch default options behavior and implement "loose" option (https://github.com/babel/babel/blob/7.0/packages/babel-plugin-transform-es2015-arrow-functions/src/index.js#L18)
- [ ] reorganize test fixtures into `default` and `loose` directories
- [ ] update readme description and examples

should be a beginner-friendly issue, i believe!

**Comment by kedromelon** [comment]
after/if this is implemented, should `babel-preset-es2015` also be updated to follow the new pattern of defaulting to `spec` mode?

**Comment by jridgewell** [comment]
This will be a big performance penalty. 👎

**Comment by kedromelon** [comment]
aw darn :/ sorry, didn't realize!

**Comment by jridgewell** [comment]
It's worth a discussion, I'm just against it.

**Comment by hzoo** [comment]
Nah we decided before not to do it a long time ago, yeah it would be very slow and not worth doing I believe as well? The template string one isn't that much worse, and same with class properties

**Comment by kedromelon** [comment]
knowing now that the performance hit would be significant, i'm probably against it too
