### ISSUE TITLE
Error no key found for value is-integer in Babel-Core

### ISSUE THREAD

**Issue by swissums** [babel/babel#6173]
Bug Report:

On running `npm-install babel-core`

I receive the error 
```
npm ERR! No value found for key is-integer at 1:30762
npm ERR! 1.6","fs-readdir-recursive":"^0.1.0","globals":"^6.2.0","is-integer":
```
### My Environment 
| node             | 6.10.3
| npm              | 5.0.4
| Operating System | Windows 10

**Comment by loganfsmyth** [comment]
Sounds like some kind of issue with npm rather than Babel. I'd recommend clearing out any npm caches you may have and trying again.
