### ISSUE TITLE
babel-standalone version number runs behind the actual version number

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#6174]
The version number is inserted into `babel.js` (and `babel.min.js`) as part of the build. If the version is bumped **after** building (like what happens when publishing with Lerna), it will contain the old version number. The new `alpha.20` release is actually `alpha.20`, but it returns `alpha.19` as its version (so `Babel.version` returns `alpha.19`, and the REPL shows alpha.190 as the version number).

I solved that in the standalone babel-standalone repo by bumping the version number before building, but it might be trickier in this case. Suggestions appreciated.

**Comment by jridgewell** [comment]
Can't this be part of the prepublish script?

**Comment by hzoo** [comment]
Yeah other than the fact you don't know the version that it should be right? it should just be the version chosen when choosing in lerna

**Comment by Daniel15** [comment]
> Can't this be part of the prepublish script?

It likely could be, but how would you set the version? I guess we could `sed` it in the built file or something. Unless you mean re-build babel-standalone as part of the pre-publish script?

**Comment by existentialism** [comment]
From https://github.com/babel/babel/issues/7016, babel-preset-env-standalone also exhibits this
