### ISSUE TITLE
cannot extend pipeline operator

### ISSUE THREAD

**Issue by willin** [babel/babel#6176]
Choose one: is this a bug report or feature request?

### Input Code

https://unpkg.com/babel-plugin-transform-pipeline-operator@1.0.2/lib/index.js

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

exports.
default = function(_ref) {
    var t = _ref.types;

    return {
        visitor: {
            BinaryExpression: function BinaryExpression(path) {
                var _path$node = path.node,
                    operator = _path$node.operator,
                    left = _path$node.left,
                    right = _path$node.right;

                if (operator !== '|>') return;

                path.replaceWith(t.callExpression(right, [left]));
            }
        }
    };
};
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["transform-pipeline-operator"]
}
```

### Current Behavior

```js
65 |> console.log;
```

```
SyntaxError: /Users/willin/Desktop/transform/index.js: Unexpected token (1:4)
> 1 | 65 |> console.log
    |     ^
  2 |
    at Parser.pp$5.raise (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOp (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3435:42)
    at Parser.pp$3.parseExprOps (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3408:17)
    at Parser.pp$3.parseMaybeConditional (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/willin/Desktop/transform/node_modules/babylon/lib/index.js:3306:19)
error Command failed with exit code 1.
```

**Comment by jridgewell** [comment]
We don't support custom syntaxes in babylon. You'll need to fork it and add support yourself, or wait till the pipeline operator has been officially accepted as a stage 0 proposal.

**Comment by willin** [comment]
how to???? there is no doc

**Comment by loganfsmyth** [comment]
Until the proposed pipeline syntax is accepted [Stage 0](https://tc39.github.io/process-document/) proposal, we will not implement support for it. The `babel-plugin-transform-pipeline-operator` plugin that you linked to is not one the Babel team maintains.

**Comment by willin** [comment]
how to implement by myself  for private use?

**Comment by jridgewell** [comment]
https://github.com/babel/babylon#will-babylon-support-a-plugin-system

**Comment by willin** [comment]
.babelrc:

```json
{
  "parserOpts": {
    "parser": "transform-pipeline-operator"
  }
}
```

still no use


TypeError: /Users/willin/Documents/w2fs/esnext-pipeline-biolerplate/src/index.js: parseCode is not a function

**Comment by jridgewell** [comment]
You have to fork the babylon parser, implement the features in your fork, then use that fork in your `.babelrc`. We don't support people who do this.

**Comment by willin** [comment]
thanks, 
![wx20170831-155535](https://user-images.githubusercontent.com/1890238/29912616-e5f42816-8df7-11e7-9707-444c429bbcdb.png)

it works now.


```js
{
  "parserOpts": {
    "parser": "@airdwing/babylon"
  },
  "plugins": [
    "transform-pipeline-operator"
  ]
}
```

here's my eslint config

```js
module.exports = {
  root: true,
  extends: 'dwing',
  parser: 'babel-eslint'
};
```

```
file: 'file:///Users/willin/Desktop/pipeline/code.js'
severity: '错误'
message: 'Parsing error: Unexpected token

> 1 | 63 |> console.log;
    |     ^
  2 |'
at: '1,5'
source: 'eslint'
```

how to fix this?

**Comment by nicolo-ribaudo** [comment]
I think you also have to fork babel-eslint an replace Babylon there

**Comment by loganfsmyth** [comment]
@willin Keep in mind, the point of this feature is to allow people to experiment with new features, not to officially support them. As stated, we don't officially aim to support extra syntax until it's accepted as a proposal.

**Comment by lilijialiang** [comment]
babel-plugin-proposal-pipeline-operator will support `await` ?

```js
const hello = function ( name ) {
    return new Promise(( resolve, reject ) => {
        setTimeout(() => {
            console.log( `hello, ${ name }` );
            resolve( name );
        }, 1000);
    });
}

const world = function ( name ) {
    console.log( `world, ${ name }` );
}

const foo = async () => {
    'foo' |> hello |> await |> world;
};

foo();
```

**Comment by xtuc** [comment]
@lilijialiang Babel follows the spec/proposal, it isn't part of the spec atm. We can open an issue there if you want.

**Comment by lilijialiang** [comment]
@xtuc I see. but I think if it can support `await` is a good thing, just like [proposal-pipeline-operator](https://github.com/tc39/proposal-pipeline-operator#use-of-await).

**Comment by xtuc** [comment]
ah sorry, I was wrong. **it is** actually part of the spec.
