### ISSUE TITLE
Can't find variable: Symbol in js

### ISSUE THREAD

**Issue by ramakrishnaj** [babel/babel#6190]
I am getting error "Can't find variable: Symbol"

here

for (var _iterator = this.state.submissionContentSymbol.iterator, _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {

any body can help ?

**Comment by nicolo-ribaudo** [comment]
Are you using babel-polyfill?

**Comment by ramakrishnaj** [comment]
Hello Sir, Thank you for response.
not using babel-polyfill. above error with wpac.js.
can you help to fix ?

**Comment by nicolo-ribaudo** [comment]
In order to use es2015+ built-in objects (like, in your case, `Symbol`) in old browsers, you need to import `babel-polyfill`.

Here are listed various ways of including it: https://babeljs.io/docs/usage/polyfill/
Be sure to include it before anything else.

**Comment by hzoo** [comment]
http://babeljs.io/docs/usage/caveats/#polyfills
