### ISSUE TITLE
Revert removal of comment check

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6191]
Ref https://github.com/babel/babel/issues/6141

I was mistaken in the actual removal of the `React.DOM` pragma (so we deleted too much code)

So a partial revert of https://github.com/babel/babel/pull/6145/files such that we keep everything but we continue to exclude the code that does 

```js
if (id === "React.DOM") { ... }
```

and remove those tests with `/* @jsx React.DOM */` but keep everything else that got removed in the PR we merged originally.

**Comment by asthas** [comment]
@hzoo I want to take this up! I really want to fix it, it is my mistake.

**Comment by hzoo** [comment]
Ok great, nah it was totally my mistake for saying that was needed to be done. Does what I said make sense though?

**Comment by asthas** [comment]
@hzoo I got your point.

**Comment by asthas** [comment]
@hzoo  I have created a pull request https://github.com/babel/babel/pull/6195 but it has merge conflicts with babel:master. I cannot resolve these since I am not a member of babel:master, so what do I do in this case?

**Comment by nicolo-ribaudo** [comment]
You can rebase it:

```
# If you haven't already done it, add the original babel repo to the remotes list. I called it "upstream", but you can choose whatever name you want
git remote add upstream https://github.com/babel/babel.git

git checkout master

# download "master" from babel/babel
git pull upstream master

git checkout your-branch

# rebase your branch on master. If there are conflicts, git will tell it you. You can solve them in your editor (search for something like <<<HEAD).
git rebase master

# When you have solved the conflicts, ensure that everything is ok and continue the rebase operation
git add .
git rebase --continue

# when you have finished, force-push to update your pr
git push -f
```

**Comment by asthas** [comment]
Thank you so much @nicolo-ribaudo!

**Comment by asthas** [comment]
Hey @nicolo-ribaudo, your steps helped me rebase the PR. Please review my PR #6195 @hzoo.

**Comment by hzoo** [comment]
Why isn't it auto closing anymore.. https://github.com/babel/babel/pull/6195
