### ISSUE TITLE
process.argv shows empty

### ISSUE THREAD

**Issue by ssi-anik** [babel/babel#6197]
I am trying to run `node bundle.js arguments` and using `process.argv` returns an empty array. where running `node index.js arguments` gives the arguments list.

Using docker: `Linux 37901bca5bc7 4.10.0-041000-generic #201702191831 SMP Sun Feb 19 23:33:19 UTC 2017 x86_64 GNU/Linux`
Using: 
```
"babel-core": "^6.23.1",
"babel-loader": "^6.2.10",
"babel-preset-es2015": "^6.22.0",
"babel-preset-stage-2": "^6.22.0",
```
Bundler: Webpack.
Thanks in advance.

SO Question here: https://stackoverflow.com/questions/46027581/process-argv-shows-empty-for-babel-transpiled-codes?noredirect=1#comment79015343_46027581

**Comment by jridgewell** [comment]
This isn't a babel issue, since we don't transform `process.argv`. Might be a webpack issue.

**Comment by ssi-anik** [comment]
Ok, thanks then. :)
