### ISSUE TITLE
t.callExpression question

### ISSUE THREAD

**Issue by willin** [babel/babel#6198]
### Input Code

```js
exports.default = function (_ref) {
  var t = _ref.types;

  return {
    visitor: {
      BinaryExpression: function BinaryExpression(path) {
        var _path$node = path.node,
            operator = _path$node.operator,
            left = _path$node.left,
            right = _path$node.right;

        if (operator !== '|>') return;
        path.replaceWith(t.callExpression(right, [left]));
      }
    }
  };
};
```

i searched `callExpression` but did not found any docs about it.

### Expected Behavior

```js
a |> b
// => (b(a))
a |> await b
// => (await b(a))
```

### Current Behavior

```js
a |> b
// => (b)(a)
a |> await b
// => (await b)(a)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  latest
| node             |  latest
| npm              | latest
| Operating System |  os x 10.12.6

**Comment by hzoo** [comment]
aside: if it's a parens issue and the ast is correct it may be a babel-generator issue. Can check babel-types for types - first arg is the caller/identifier/ and second is the array of arguments 

`|>` isn't an operator for a binary expression (at least in the current parser) any kind of transform like that shouldn't work.

**Comment by willin** [comment]
习惯性答非所问, 差评.

**Comment by willin** [comment]
```js
'use strict';
/** Requires */
import syntax from 'babel-plugin-syntax-pipeline';
import template from 'babel-template';


/** Visitor */
export default function ({ types: t }) {
  return {
    inherits: syntax,
    visitor: {
      BinaryExpression(path, state) {
        if (!path.isBinaryExpression({ operator: '|>' })) {
          return;
        }

        path.replaceWith(
          template('(FUNCTION(ARGUMENTS))')({
            FUNCTION: path.node.right,
            ARGUMENTS: path.node.left
          })
        );
      }
    }
  };
}
```


舍不得写文档, 差评+1.

**Comment by willin** [comment]
Spend more time writing documents rather than writing less nutritious codes.
