### ISSUE TITLE
[Proposal] Array.prototype.slice reference

### ISSUE THREAD

**Issue by jamiebuilds** [babel/babel#62]
Currently, spreads and rest parameters compile using `Array.prototype.slice`. Which makes sense in a browser environment where you wouldn't want the global namespace polluted as part of the 6to5 philosophy.

However, in certain cases it might make sense to store `slice` as a variable in the topmost context and reuse it throughout a single file. This would help save on bytes in the browser, which is why [many](http://underscorejs.org/docs/underscore.html#section-7) [libraries](https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L514) [do](https://github.com/angular/angular.js/blob/master/src/Angular.js#L166) [this](https://github.com/jquery/jquery/blob/master/src/var/slice.js#L4).

Currently,

``` js
(function() {
  function bar(...items) {
  }

  function foo() {
    return bar("test", ...arguments);
  }
}());
```

Compiles to:

``` js
(function() {
  function bar() {
    var items = Array.prototype.slice.call(arguments);
  }

  function foo() {
    return bar.apply(null, ["test"].concat(Array.prototype.slice.call(arguments)));
  }
}());
```

However, I think the following would be more readable, and would save on bytes.

``` js
(function() {
  var slice = Array.prototype.slice;

  function bar() {
    var items = slice.call(arguments);
  }

  function foo() {
    return bar.apply(null, ["test"].concat(slice.call(arguments)));
  }
}());
```

Thoughts?

**Comment by sebmck** [comment]
As of 2.6.0, 6to5 now uses a for loop instead of `Array.prototype.slice`.
