### ISSUE TITLE
Enable BuildSize to track size of babel-standalone

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#6200]
Over the weekend, I started working on a small GitHub App to automatically track build/artifact size on pull requests: https://buildsize.org/. It posts comments like this on pull requests (although I want to make the commenting optional, since it also posts a 'status'):
![](https://ss.dan.cx/2017/09/Example_of_increasing_size_of_the_build_by_Daniel1_04-11.57.50.png)

I'd like to test it with Babel as I think it would be useful for tracking the size of added dependencies in babel-standalone (plus it'd be a good test for the app and I could learn what I need to improve), but only org admins can install GitHub Apps, so I'd need an admin to enable it.

Let me know what you think!

cc @xtuc (https://twitter.com/Daniel15/status/904948320384172032)

**Comment by Daniel15** [comment]
Ping... Can we enable this?

**Comment by nicolo-ribaudo** [comment]
Done (https://github.com/babel/babel/pull/10376#issuecomment-526714440)
