### ISSUE TITLE
Does babel support to resolve a plugin from antoher directory

### ISSUE THREAD

**Issue by Gcaufy** [babel/babel#6201]
babel-core: `v6.24.1`

Currently if you need to use a babel plugin, you need run npm install to install the plugin in `node_module` directory.

But I need a option, like [webpack resolve](https://webpack.js.org/configuration/resolve/#resolve-modules).

Then I can install all plugins in a common directory like: `E:/bablePlugins`, and in my projects, added following options:
```
resolve: {
    modules: ['E:/babelPlugins']
}
```

**Comment by nicolo-ribaudo** [comment]
Currently it isn't possible to specify the plugins folder, but you can use absolute paths:
```json
{
  "plugins": [ "E:/babelPlugins/your-plugin" ]
}
```

**Comment by jridgewell** [comment]
No, we don't support this yet.

**Comment by Billy-** [comment]
Please could this be re-opened in a merge request?

My current predicament is that I am trying to create an npm module which provides some bin helper functions for our day-to-day dev. One of those helpers uses babel and the react-intl babel-plugin, which extracts strings from files.

Now, the process needs to run in the directory of the consuming app, but I want to resolve the modules from my helper module. Currently it looks in node_modules in the directory of the consuming project, not the helper module.

Kind regards,

**Comment by nicolo-ribaudo** [comment]
Whith Babel 7 you can use `.babelrc.js` instead of `.babelrc`, so you can use something like https://www.npmjs.com/package/resolve-from

**Comment by loganfsmyth** [comment]
@Billy- Hard to say without seeing your code, but you should be able to use `require` normally to require any plugins that you need to resolve in your utility.

**Comment by Billy-** [comment]
@nicolo-ribaudo could you please expand on that a bit, specifically how you would use that package in conjunction with babel configuration to solve the problem? I am running babel-core from within js so I have control over the configuration anyway.

@loganfsmyth quick pseudo-code would be 
`babel.transform(data, { babelrc: false, plugins: [‘react-intl’] })`

**Comment by nicolo-ribaudo** [comment]
Oh, I didn-t understand that you were using it within js. You can pass the plugin instead of the plugin name. e.g.
```js
babel.transform(data, {
  babelrc: false,
  plugins: [
    require("babel-plugin-require-intl")
  ]
});
```

**Comment by Billy-** [comment]
I didn't realise you could do that. Many thanks!
