### ISSUE TITLE
Async/await avoids error messages in the browser console

### ISSUE THREAD

**Issue by Hanterdro** [babel/babel#6202]
Hey,

I have a strange issue.

Erroneous code inside a transpiled async function is not shown in the Webbrowsers console.
This is bad for debugging.

Example:

```
async function foobar() {
    console.log("before error");
    let foo;
    console.log(foo.bar);
    console.log("after error");
}
foobar();
```

Should show in the Webbrower something like:

<img width="616" alt="bildschirmfoto 2017-09-05 um 10 51 57" src="https://user-images.githubusercontent.com/7668392/30053212-4efd1abe-9228-11e7-82a5-a6d6f3d4c7e9.png">

But inside the async function every error message is missing, but the code stops working (because of the error :-)
Only  `before error` is  shown.

I've tested this in Chrome ( 60.0.3112.113) and Safari (10.1.2 (12603.3.8)) on macOS Sierra.

Using 

```
    "babel-core": "6.25.0",
    "babel-loader": "7.1.1",
    "babel-polyfill": "6.26.0",
    "babel-plugin-syntax-async-functions": "6.13.0",
    "babel-plugin-syntax-dynamic-import": "6.18.0",
    "babel-plugin-transform-regenerator": "6.26.0",
    "babel-plugin-transform-react-jsx": "6.24.1",
    "babel-preset-es2015": "6.24.1",
```

in Webpack "3.4.0" with this config:

```
, {
                        test: /\.js$/,
                        exclude: /node_modules\/(?!(([^\/]+?\/){1,2}(src|es6)))/,
                        use: {
                            loader: 'babel-loader',
                            options: {
                                plugins: ['transform-react-jsx', 'syntax-dynamic-import', 'syntax-async-functions', 'transform-regenerator'],
                                presets: [
                                    [
                                        'es2015',
                                        {
                                            modules: false
                                        }
                                    ]
                                ],
                                cacheDirectory: true
                            }
                        }
                    }
```

**Comment by hzoo** [comment]
I don't understand, what is the error that it is showing?

> But inside the async function every error message is missing

If it errors it would only show the error itself and nothing after?

aside: I would switch out preset-es2015 with preset-env and then you can remove syntax-async-functions and transform-regenerator since they are included

**Comment by Hanterdro** [comment]
The problem is that the error is **not** shown, when the code was transpiled with babel.

That means that no JS errors are shown in `async` functions, which makes it impossible to debug.

I will try `preset-env` tomorrow, but I think it will make no difference, after I tried today also ` preset-es2017` instead of syntax-async-functions and transform-regenerator.

**Comment by nicolo-ribaudo** [comment]
Can you show the compiled output for that function? Are you sure you aren't using `.catch()` or the `unhandledrejection` event somewhere?

When I run the transpiled code in Chrome, I get the error as expected:
![babel-issue-6202](https://user-images.githubusercontent.com/7000710/30069277-9b123c3a-9260-11e7-84b8-116035105671.png)

**Comment by loganfsmyth** [comment]
It's also possible you're adding a different `Promise` polyfill that is introducing this issue. Might be worth checking `Promise.toString()` to see what the promise constructor looks like.

**Comment by Hanterdro** [comment]
@loganfsmyth 
yeah thanks... an other Promise polyfill was the issue.

In my webpack config is the plugin

```
        plugins: [
                new webpack.ProvidePlugin({
                    Promise: 'es6-promise-promise'
                })
            ]
```

which causes this behavior.
