### ISSUE TITLE
How does Symbol.hasInstance + instanceof work (or does it even work?) in IE11 and below?

### ISSUE THREAD

**Issue by trusktr** [babel/babel#6210]
I'm looking at [this output in the repl](http://babeljs.io/repl#?babili=false&browsers=ie%2010&build=&builtIns=true&code_lz=MYGwhgzhAEBiD29oG8C-AodD4G0DKAngLYBG8IAdABaQCSAdhAC5j3ACmAutALzQBmAVzZMAlvHoAKeEyrsATgEoU6aNGASI5dhRDwA5pIDkoxizbt4_dXOABrI4vQZ0GswN7R67AO5xEmNamzKwcVv5IAPSR0Hr6MABEweZh1sC2dglAA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=react%2Cstage-0%2Cstage-2%2Cenv&prettier=false&targets=&version=6.26.0).

From what I can tell, it requires a `Symbol.hasInstance` polyfill.

However, the `instanceof` check isn't being transpiled into anything.

So, in an older browser like IE 10, how can this possibly work if the native `instanceof` operator will not know to look for `Symbol.hasInstance` on a constructor?

In otherwords, doesn't 

```js
f instanceof Foo;
```

need to be transpiled to something like

```js
__instanceOf(f, Foo);
```

where `__instanceOf` is a helper that can use `Symbol.hasInstance` (polyfilled or not)?

**Comment by jridgewell** [comment]
Does `babel-polyfill` not handle this?

**Comment by zloirock** [comment]
@jridgewell `core-js` provide only `Symbol.hasInstance` and `Function.prototype.@@hasInstance`, but can't override `instanceof` operator logic.

**Comment by nicolo-ribaudo** [comment]
This is handled by the [`babel-plugin-transform-es2015-instanceof`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-instanceof) plugin. It needs to be added to `babel-preset-es2015` and `babel-preset-env`

**Comment by ajaymathur** [comment]
Hi, Can I take this up please?

**Comment by loganfsmyth** [comment]
This is an interesting one. I wonder if it was left out on purpose? I could see this being a performance issue, but I honestly don't know. Seems like we'd need to dig into the git history?

**Comment by ajaymathur** [comment]
@loganfsmyth I did a search on git log and found following commit:

commit a9ac3b0c94057922430335dfe833284012e370df
Author: Sebastian McKenzie <sebmck@gmail.com>
Date:   Tue Nov 3 19:22:51 2015 +0000

    move instanceof functionality to separate plugin - fixes #2745


direct link to issue https://github.com/babel/babel/issues/2745

**Comment by jridgewell** [comment]
Likely just an oversight then, I don't see it being any more of a penalty than `typeof`.

**Comment by msdark** [comment]
So this is basically re-add the functionality to preset-env preset-es2015 as mentioned in https://github.com/babel/babel/issues/6210#issuecomment-328337803

**Comment by jridgewell** [comment]
Yup.

**Comment by ajaymathur** [comment]
Cool, so can I please take this up ?

**Comment by nicolo-ribaudo** [comment]
@ajaymathur Yes 👍
