### ISSUE TITLE
Add babel-cli option for preserving .mjs extension

### ISSUE THREAD

**Issue by n1ru4l** [babel/babel#6211]
This is a **Feature Request**

Since the mjs extension will be supported in node.js soon and can also today be used trough packages like @std/esm it would be awesome to have a option for preserving that extension.

I asked about this on Slack and was told to use some custom gulp configuration. I am aware that that works, but I would prefer to not having that extra dependency for transpiling my files 😅 

Depending on the complexity of the solution to implement this I could volunteer to do a PR for this 😊

Also, could this potentially be blocked by https://github.com/babel/babel/pull/5511 ?

Thanks you for this awesome library 🎉

**Comment by n1ru4l** [comment]
Okay I will do a PR for this, any suggestions for the option flag?

I thought about something like `--keep-modules`

**Comment by tbranyen** [comment]
Hi @n1ru4l I understand your motivation for this flag, but I'm a little worried this is of limited use for most users who will still author in `.js` files and see `.mjs` as a build step. Seems your use case and even more could be solved with an output extension flag.

```
babel lib -d dist/node --ext ".mjs"
```

**Comment by n1ru4l** [comment]
I see your point, but I think both options solve different problems. I think that both options should be available (but not be used together). Furthermore since .mjs will become the main extension (that will be consumable by almost all JavaScript clients beside .js) the keep-module-extension option should become enabled by default at some point in the future.

**Comment by tbranyen** [comment]
I thought more and can see value in having both. Preserve original works better which mixed extensions in an input glob :+1:

**Comment by xtuc** [comment]
I think we should also merge https://github.com/babel/babel/pull/5700. It will ensure that the module is parsed correctly.

**Comment by hhg2288** [comment]
is this issue claimed right?

**Comment by n1ru4l** [comment]
@hhg2288 Yes https://github.com/babel/babel/pull/6221 is the PR
