### ISSUE TITLE
BUG? if (typeof exports == 'object')

### ISSUE THREAD

**Issue by achun** [babel/babel#6215]
config:

```js
{presets: ["es2015"]}
```

source:

```js
if(typeof exports==='object'){
}
```

output:

```js
if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') {
}
```

See: [babeljs repl](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYMwFALgngDgpgexAAjgDxggThAzgXkIHIEAjAKzgGMIiBKAbwF8g&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015&prettier=false&targets=&version=6.26.0)

**Comment by goto-bus-stop** [comment]
This is expected behaviour, it's the [babel-plugin-transform-es2015-typeof-symbol](https://www.npmjs.com/package/babel-plugin-transform-es2015-typeof-symbol) transform at work. `typeof xyz` should return "symbol" if `xyz` is a Symbol, the `_typeof` function does that in environments that don't have Symbol natively.

**Comment by nicolo-ribaudo** [comment]
That output is needed to prevent polyfilled `Symbol`s to return true for `typeof x === "object"`.

**Comment by achun** [comment]
Are you sure?

```js
typeof exports === 'undefined' ? 'undefined' : ......
```
...? quote undefined quote : ...

**Comment by jridgewell** [comment]
It's to prevent a reference error (since typeof won't throw if `exports` is undeclared). This is the expected output.

**Comment by brookslee** [comment]
where, I have the same problem, I do think this is a bug！

my code: 

`if (typeof startPageY == undefined) {
                startPageY = evt.changedTouches[0].pageY;
            }`

output:
`
if ((typeof startPageY === 'undefined' ? 'undefined' : _typeof(startPageY)) == undefined)  {  
   startPageY = evt.changedTouches[0].pageY; 
 }
`

when `startPage` is undefined, `if (typeof startPageY === 'undefined' ? 'undefined' : _typeof(startPageY)) == undefined` ->  `if ('undefined' == undefined) {}` 

the if statement will not excute!

**Comment by nicolo-ribaudo** [comment]
typeof returns a string. You should write `"undefined"` and not `undefined` in your code.
