### ISSUE TITLE
Incorrect capturing of stacktrace in custom errors

### ISSUE THREAD

**Issue by rostik404** [babel/babel#6216]
After babel transformation, custom error loses its stacktrace because of incorrect value in `_this.constructor`.

### Input Code
Here is a simple example  of custom js Error:
```js
Test = class Test extends Error {
    constructor() {
        super();
        Error.captureStackTrace(this, this.constructor)
        console.log('Constructor: ', this.constructor);
    }
}

const e = new Test('some-error')
console.log('Stack: ', e.stack);
```
I'm expecting to get `Test` in constructor and full stacktrace in `e.stack`, and everything works as I expect:
```
Constructor:  class Test extends Error {
    constructor() {
        super();
        Error.captureStackTrace(this, this.constructor)
        console.log('Constructor: ', this.constructor);
    }
}
Stack:  Error
    at Object.<anonymous> (/Users/rostik404/projects/test-project/test-error.js:42:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

After babel transformation, I'm getting this code:

```js
var Test = function (_Error) {
    _inherits(Test, _Error);

    function Test() {
        _classCallCheck(this, Test);

        var _this = _possibleConstructorReturn(this, (Test.__proto__ || Object.getPrototypeOf(Test)).call(this));

        Error.captureStackTrace(_this, _this.constructor);
        console.log('Constructor: ', this.constructor);
        return _this;
    }

    return Test;
}(Error);

var e = new Test('some-error');
console.log('Stack: ', e.stack);
```
And in this code, I'm getting `Error` in `_this.constructor` instead of `Test` and because of this `Error.capturestacktrace` cuts the whole stacktrace:
```
Constructor:  function Error() { [native code] }
Stack:  Error
```

### Babel Configuration (.babelrc, package.json, cli command)
Using [babel online](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAKgU2jAvDYAbAhhC8mwIAeUCYAJngKIBONINMA3gFAzvrjQ0CuwUDABQBKZmw4SIPAA4IaIgNziJ7WvRoA6YFmlQeNBAGUoWYAGs4NUwkFQAFgEsIAGhj2nWrlF78Gw5SqgkCAYCBoYIADmto4QnpDefAI0wkoSAL4smSxByAioMGAIAO740IIA5BAgALYIALRy6hX-uSFhEdEVxqZmAFwwFa5h0L2pQA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0) 

### Expected Behavior
Full stacktrace in custom Error

### Current Behavior
Cut stacktrace and incorrect value in `_this.constructor`

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | v6.26.0
| node             | v8.4.0
| npm              | v5.3.0
| Operating System | macOS Sierra v10.12.4

**Comment by loganfsmyth** [comment]
`.name` is `Error` because we don't support extending builtin types out of the box: https://babeljs.io/docs/usage/caveats/#classes

That said, even using that extension, which makes `.name` `Test`, the stack trace itself does seem to still contain `Error`. I'm not sure there's anything we can do there, I have no idea how Chrome decides what to use when building traces.

**Comment by hzoo** [comment]
I guess we'll close then? Can try https://github.com/babel/babel/issues/4480#issuecomment-311357113
