### ISSUE TITLE
Export async function not working

### ISSUE THREAD

**Issue by danez** [babel/babel#6225]
Choose one: is this a bug report or feature request?

bug

### Input Code
```js
export default async function top () {}
```

or

```js
export async function top () {}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["env"]
}
```

https://babeljs.io/repl/build/7.0/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29UGcCeAdgMZzLokwCWEhcMEYcAFAJRwDeAvkA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=env&prettier=false&targets=&version=7.0.0-alpha.20

https://babeljs.io/repl/build/7.0/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBHAhgZwJ4DsDGcBmBXLGASwnThgjDgAoBKOAbwF8g&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=env&prettier=false&targets=&version=7.0.0-alpha.20

Seems the second case with export async ...  only breaks in babel-preset-env but works with the es201x presets.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0

**Comment by jridgewell** [comment]
Looks like this is a mismatched repl bug. It's somehow loaded `babel-preset-env-standalone@0.0.6`, which uses `babel-plugin-transform-es2015-block-scoping@6.6.0`, which is incompatible with `babel-core@7.0.0-alpha.20`

**Comment by hzoo** [comment]
If this is a repl bug we should maybe just move to the website repo? sounds like v7 is fine

**Comment by jridgewell** [comment]
@babel-bot move to babel/website
