### ISSUE TITLE
babel-polyfill adds a variable called "global" to browser runtime (regression?)

### ISSUE THREAD

**Issue by cagdastulek** [babel/babel#6227]
### Bug
When using babel-polyfill 6.23, typing "global" to the browser console throws undefined error, which is the correct behavior.

After upgrading to 6.26, "global" is set to an object.

This sounds dangerous as checking if "global" is set or not is one of the common ways to check if a script runs inside Node or Browser environment.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7
| webpack             |  2.6.1
| node             |  6.11
| npm              | 3.10

**Comment by jridgewell** [comment]
Sounds like core-js implemented the global polyfill, which should be expected. /cc @zloirock

**Comment by zloirock** [comment]
@jridgewell yep.

@cagdastulek about dangerous of this feature you can talk with @ljharb as with the champion of this proposal.

**Comment by ljharb** [comment]
@cagdastulek the proper way is to check `typeof process !== 'undefined'`, because browserify and webpack all transpile `global` to `window` - so there's not actually any danger there.

**Comment by cagdastulek** [comment]
All, thanks for explanations. @ljharb what if someone defines a `process` global variable in browser? Is there any more robust way to determine if I am in Node or not? We use the following code snippet which breaks if we use the latest core-js, of course:
```
const isBrowser = new Function(
  "try {return this===window;}catch(e){ return false;}"
)();
const isNode = new Function(
  "try {return this===global;}catch(e){return false;}"
)();
```

**Comment by loganfsmyth** [comment]
What's your usecase you're trying to solve by making this distinction? Usually it's best to check for the thing you actually care about like the existence of a given API or something. That would help make suggestions for you.

**Comment by ljharb** [comment]
@cagdastulek if someone does that, then a lot of node checks would suddenly start failing, sure.

I'd echo @loganfsmyth's question - why does it matter if you're in node? Feature detection is much more robust than useragent sniffing (or the equivalent).

**Comment by cagdastulek** [comment]
We use these flags in various parts of our code base. I guess for each of our uses case, we can go one by one and make such checks by checking the APIs instead. The challenge on our end is time and resource, of course.

By the way, I thought, with babel, I can enable/disable the features/proposals by configurations. Is it possible to disable this proposal?

**Comment by loganfsmyth** [comment]
@cagdastulek Currently while Babel's syntactic transformations can be toggled off and on easily, it's separate from `babel-polyfill`. `babel-polyfill` includes whatever `core-js` decides to implement, which in this case includes a few experimental things.

**Comment by ljharb** [comment]
@cagdastulek what would be the point, if it ends up landing in the language you'd be stuck anyways. Best to make the fix now.

**Comment by cagdastulek** [comment]
This is also what we figured out. Thanks a lot for all comments and help.
