### ISSUE TITLE
How we can save 100 data into DB at the same time using MSSQL

### ISSUE THREAD

**Issue by dijotcr222** [babel/babel#6228]
function savedata(session,response){
   var conn = new sql.ConnectionPool(connection);
var reqs = new sql.Request(conn);
conn.connect(function(err){
 
 if(err){
console.log(err)
 
 
}else{
    
var SqlSt = "INSERT into saveDB$ (CHAT_ID,QUESTION,DATE_TIME,RESPONSE,USER_NAME,FUND_TYPE,USERAGE) VALUES";
SqlSt += util.format("(%s,%s,%s,%s,%s,%s,%s)","'"+session.message.address.id+"'","'"+RESPONSE+"'","'"+session.message.timestamp+"'","'"+response+"'","'"+globalnameid+"'","'"+globalFundType+"'","'"+globalAge+"'");
    
// var SqlSt = "INSERT into saveDB$ (CHAT_ID,QUESTION,DATE_TIME,RESPONSE,USER_NAME,FUND_TYPE) VALUES";
//SqlSt += util.format("(%s,%s,%s,%s,%s,%s)","'"+session.message.address.id+"'","'"+session.message.text+"'","'"+session.message.timestamp+"'","'"+response+"'","'"+globalnameid+"'","'"+globalFundType+"'" );
 
reqs.query(SqlSt, function(err, data){
 
if(err){
 
 session.send(JSON.stringify(err));
 
}else{
    
// session.send(JSON.stringify(suc));
 
}
});
}
});
 
}

**Comment by dijotcr222** [comment]
what !!! closed

**Comment by hzoo** [comment]
Your issue doesn't have to do with Babel or using it, I would ask on stackoverflow.com or another forum. The issue tracker is for Babel specifically.
