### ISSUE TITLE
V8 can't optimize Array with initial size

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#6233]
> https://v8project.blogspot.com/2017/09/elements-kinds-in-v8.html

> Let’s say we’re trying to create an array, for example:

```js
const array = new Array(3);
// The array is sparse at this point, so it gets marked as
// `HOLEY_SMI_ELEMENTS`, i.e. the most specific possibility given
// the current information.
array[0] = 'a';
// Hold up, that’s a string instead of a small integer… So the kind
// transitions to `HOLEY_ELEMENTS`.
array[1] = 'b';
array[2] = 'c';
// At this point, all three positions in the array are filled, so
// the array is packed (i.e. no longer sparse). However, we cannot
// transition to a more specific kind such as `PACKED_ELEMENTS`. The
// elements kind remains `HOLEY_ELEMENTS`.
```

> Once the array is marked as holey, it’s holey forever — even if it’s packed later! Any operation on the array from then on is potentially slower than it could be. If you plan on performing lots of operations on the array, and you’d like to optimize those operations, avoid creating holes in the array. V8 can deal with packed arrays more efficiently.

Cool, so we'll just reallocate space after pushes. 🙄 

--- 

## EDIT: Check https://github.com/babel/babel/issues/6233#issuecomment-329164507

**Comment by hzoo** [comment]
Oh, do we ever do `new Array` instead of `[]`?

**Comment by jridgewell** [comment]
Rest elements.

**Comment by hzoo** [comment]
Hmm ok like http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=NoOjEMBoAICMF0DcQ&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.0.0-alpha.19 in the helper: `arr2 = Array(arr.length)`

cc @bmeurer though since v8 is trying to optimize tooling code like Babel anyway

**Comment by bmeurer** [comment]
You should never emit calls to `Array(len)`. Always use `new Array(len)`, because the *[[Call]]* syntax doesn't have *elements kind tracking* in the most recent V8 versions (and was always a bit broken before).

Besides that, holey arrays aren't the end of the world and it's usually faster to just do `new Array(len)` and live with the holeyness, rather than starting with `[]` and having to reallocate subsequently.

**Comment by hzoo** [comment]
Alright, sounds like an easy fix to just use `new Array()` instead of `Array` and forget using `[]` like you said. Would be a nice beginner contribution too.

**Comment by bmeurer** [comment]
Nice. Yeah indeed a good starter project. cc @mathiasbynens

**Comment by mathiasbynens** [comment]
> it's usually faster to just do `new Array(len)` and live with the holeyness, rather than starting with `[]` and having to reallocate subsequently.

As always, It Depends™.

I’m going to give newcomers to the Babel project a chance to submit a patch for [this change](https://github.com/babel/babel/issues/6233#issuecomment-329164507). If no one picks it up by early next week, I’ll contribute a patch myself.

**Comment by Andarist** [comment]
I can take it :) going to send PR in following days.

**Comment by keustma** [comment]
Hi @Andarist , I was tinkering with this before I saw your comment. Is it OK if I create a PR for this?

**Comment by gs-akhan** [comment]
I would love to see how it was fixed and learn on how to go about making this.

Thanks @Andarist

**Comment by Andarist** [comment]
@keustma sure, go for it

**Comment by jridgewell** [comment]
@bmeurer: How hard would it be for Chrome to handle this case? Something like the following:

```js
// Somehow, internally, a MAYBE_PACKED with [[packingIndex]] = 0
const a = new Array(3);

// increments [[packingIndex]]
a[0] = {};
// increments [[packingIndex]]
a[1] = {};
// [[packingIndex]] === length, transition to PACKED
a[2] = {};

// - - -
// some internal class replacement so from MAYBE_PACKED to HOLEY

// deopts, has to check proto chain
deopt1[0];

// deopts, setting to index that's not [[packingIndex]]
deopt2[1] = {};

// deopts, has to check proto chain
delete deopt3[0];

// deopts, length manipulation
deopt4.length = any_number;
deopt5.shift();
deopt6.pop();

// deopts, not setting [[packingIndex]]
deopt7.unshift({})
deopt8.push({})

**Comment by mathiasbynens** [comment]
@jridgewell If transitioning back up the lattice were possible, we could end up in elements kind transition loops. (Also, technically, it wouldn’t be a lattice anymore.)

This is something I (naively) brought up as well. Especially in cases where things like `Array.prototype.fill()` are used, e.g. `new Array(3).fill(42)`, it would seem the elements kind should be able to transition back from `HOLEY` to `PACKED`. However, V8’s entire lattice implementation would have to be changed to something else just to allow for this… It’s not technically impossible to do this, but it would be a huge architectural change that would likely not be worth the limited gains for these particular cases.

**Comment by mathiasbynens** [comment]
> Cool, so we'll just reallocate space after pushes. 🙄

Allow me to clarify what I tried to convey in that last paragraph you quoted. There’s two ways to go:

1. Either you choose to optimize the *array creation* itself by using `new Array(n)` so it can be preallocated. 
2. Or, you choose to optimize the later *operations on the array*. In this case it makes sense to avoid `HOLEY` elements kinds.

It’s a trade-off for sure, and as the choice depends on the exact use case, it’s difficult to make choices for generic code generators such as Babel.

**Comment by mathiasbynens** [comment]
Also: it’s not like every single `.push(x)` triggers reallocation. Implementation details time! In V8, an empty array gets a buffer of 16 elements. This gives it a little bit of room to grow without needing reallocation. Once you add a 17th element, the buffer expands by 50%. This formula continues after that every time reallocation is needed.

**Comment by jridgewell** [comment]
>  if transitioning back up the lattice were possible, we could end up in elements kind transition loops, which seems bad

My thought is that the `MAYBE_PACKED` would sit above `PACKED` and `HOLEY` on the lattice, something like:

| SMI | DOUBLE | ELEMENT |
| --- | --- | --- |
| `MAYBE_PACKED` | | |
| `PACKED` | | |
| `HOLEY` | | |
| | `MAYBE_PACKED` | |
| | `PACKED` | |
| | `HOLEY` | |
| | | `MAYBE_PACKED` |
| | | `PACKED` |
| | | `HOLEY` |

With that added stipulation that you can't transfer to a `MAYBE_PACKED`, it has to start as one. If the all the indices are filled (in order), it transitions the the `PACKED` variant. Otherwise (due anything that isn't explicitly "set the indices (in order)"), it transitions to the `HOLEY` variant (hopefully without allocating anything new).

> Once you add a 17th element, the buffer expands by 50%. This formula continues after that every time reallocation is needed.

Yah, I figured it'd follow some exponential pattern.
