### ISSUE TITLE
Named exports + destructuring for env preset doesn't work.

### ISSUE THREAD

**Issue by Kerrick** [babel/babel#6234]
This is a bug report.

### Input Code
```js
const exports = {};
exports.Foo = 'hello';

export const { Foo } = exports;

export default exports;
```
[Babel REPL link](http://babeljs.io/repl#?babili=false&browsers=last%201%20chrome%20version&build=&builtIns=false&code_lz=MYewdgzgLgBApgDwA4gE5QjAvDA3gXwG4AoRFdCAOgDEQRsYByACzgBs2RGTTk1ZQkWLhi16-BmX4QeU9DAAmcAGYBDAK5tYcjISA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=senv&prettier=false&targets=&version=6.26.0)

### Babel Configuration (.babelrc, package.json, cli command)
The babel configuration as shown in the REPL above is to compile with the Env preset, set to `last 1 chrome version`.

### Expected Behavior

With the code above, `import { Foo } from 'that-file'` should give you access to the string `'hello'`.

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
const _exports = {};
_exports.Foo = 'hello';

const { Foo } = _exports;
exports.Foo = Foo;
exports.default = _exports;
```

In this imaginary case, you can see that `Foo` would be attached to `exports`.

### Current Behavior

With the code above, `import { Foo } from 'that-file'` means that `Foo` is undefined.

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
const _exports = {};
_exports.Foo = 'hello';

const { Foo } = _exports;

exports.default = _exports;
```

In this case, you can see that `Foo` is not attached to `exports`.

**Comment by loganfsmyth** [comment]
This will be fixed in 7.x with https://github.com/babel/babel/issues/6234
