### ISSUE TITLE
Computed class fields evaluated during construction

### ISSUE THREAD

**Issue by gsathya** [babel/babel#6240]
> Choose one: is this a bug report or feature request?

bug report

### Input Code

```js
var x = 'x';

class F {
  [x] = 1;
  constructor() { 
    console.log(this.x);
  }
}

new F;
x = 'y';
new F;
```

### Babel Configuration (.babelrc, package.json, cli command)

stage3, stage2 presets

### Expected Behavior
1
1

### Current Behavior
1
undefined

### Your Environment
[REPL](https://babeljs.io/repl/build/4898/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAHhC8EHIoINwCg0GMA2IDOeEAYhAN5oQQDaUAunBAIzqWYD2AdngC5gCumbmzAAKAJRkIFShHZc22AKYA6bGwDmI7gAsAlnmVQxLCAF805tB0UB3YuhjwEAT1RXb9oA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=stage-2%2Cstage-3&prettier=false&targets=&version=7.0.0-beta.0)

**Comment by gsathya** [comment]
Actually, I think this is WAI. @littledan, can you confirm?

**Comment by littledan** [comment]
To be clear: I think the original post is right, and Babel has a bug.

**Comment by hzoo** [comment]
PR https://github.com/babel/babel/pull/6466

[repl](https://babeljs.io/repl/build/5264/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAHhC8EHIoINwCg0GMA2IDOeEAYhAN5oQQDaUAunBAIzqWYD2AdngC5gCumbmzAAKAJRkIFShHZc22AKYA6bGwDmI7gAsAlnmVQxLCAF805tB0UB3YuhjwEAT1RXb9oA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=stage-0&targets=&version=7.0.0-beta.2%2Bpr.6466)
