### ISSUE TITLE
Class fields don't work when super() is called in a different scope

### ISSUE THREAD

**Issue by gsathya** [babel/babel#6241]
> Choose one: is this a bug report or feature request?

bug report

### Input Code

```js
var x = 1;

class F extends Object {
  c = x;

  constructor() { 
    f = () => super();
    f();
    console.log(this.c);
  }
}

new F;
```

### Babel Configuration (.babelrc, package.json, cli command)

stage3, stage2 preset

### Expected Behavior
1

### Current Behavior
undefined

### Your Environment
[REPL](https://babeljs.io/repl/build/4898/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAHhC8EEYDcAoFBjANiAzjiAYhAKZQAuxAdgCb4DyARgFbHpkQDeKEE6c0qbrwD2lHGTABXNsLAAKAJScIQngDN-iuAD4IOSQAdi8hah7rFZ8-lE5hmYgDpMwgOZyyACwCWOR-lMhAF8UEJRKYgB3QiQgA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=stage-2%2Cstage-3&prettier=false&targets=&version=7.0.0-beta.0)

**Comment by Qantas94Heavy** [comment]
This should be fixed by #6337 -- you can check this in the REPL here: https://babeljs.io/repl/build/5096

**Comment by gsathya** [comment]
I see `f is not defined` in the REPL

**Comment by hzoo** [comment]
is it because you should have the `var f` instead anyway?

**Comment by gsathya** [comment]
Ah, ofc. Class body is all strict mode. Closing, thanks!

**Comment by hzoo** [comment]
Awesome 🙂 thanks again for the report!
