### ISSUE TITLE
new.target is not allowed in class field initializer

### ISSUE THREAD

**Issue by gsathya** [babel/babel#6243]
> Choose one: is this a bug report or feature request?

bug

### Input Code

```js
class F {
  x = new.target;
}
```

### Babel Configuration (.babelrc, package.json, cli command)

stage3, stage2

### Expected Behavior
no error

### Current Behavior
Error

### Your Environment
[REPL](http://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEBi0G8BQ1oA9oF5oDsCmA7gHQAuYATgOZ4kDcSAvkkA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=react%2Cstage-2&prettier=false&targets=Node-4&version=7.0.0-beta.0)

**Comment by Kovensky** [comment]
It seems it is supposed to evaluate to `undefined` (each initializer runs in the equivalent of `(function () { return initializer }).call(this)`).

**Comment by perinikhil** [comment]
Hi guys, could i get some more information on this issue please?

**Comment by jridgewell** [comment]
Closing as allowed (and fixed in https://github.com/babel/babylon/pull/759).
