### ISSUE TITLE
when babel presets es2015 opts modules set false, got the error Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ckrad** [babel/babel#6245]
when babel presets es2015 opts modules set false, got the error Uncaught SyntaxError: Unexpected token import
```js
presets: [
  ['es2015', {modules: false}],
  'stage-2',
  'react'
]
```

can anyone help me?

**Comment by nicolo-ribaudo** [comment]
Can you show a code snippet which reproduces the issue? Are you getting that error from Babel or from node/the browser?

**Comment by jridgewell** [comment]
You can't use `import` or `export` in script mode.
