### ISSUE TITLE
Can't use object-rest-spread in a function

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6247]
Original issue submitted by @tolmasky in https://github.com/babel/babylon/issues/724

Here's the REPL example: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FAMwrgdgxgLglgewgAgB4AoCUwDewCQAbgIYBOyxyAvMujsgHROkCmAzjMgL7XJsIBbFjAAWcCAHNMAbmBcgA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-0&prettier=false&targets=&version=6.26.0

```js
function x()
{
	var a = ({ ...rest } = something);
}
```

If you comment out "function x()" it works fine. The actual example from my code was 

```js
function *x() { yield { capture:({ ...rest } = s) } }
```
### Input Code

```js
var your => (code) => here;
```

### Babylon/Babel Configuration

```js
plugins:["objectRestSpread"] for parser.
and transform-object-rest-spread.
```

**Comment by tolmasky** [comment]
In 6 this seems to happen because of this: https://github.com/babel/babel/blob/6.x/packages/babel-plugin-transform-object-rest-spread/src/index.js#L183

That is false and thus ref is never set, causing undefined to be used into createObjectSpread. Does the REPL use 7-beta? This code looks very different there.

**Comment by tolmasky** [comment]
I guess its fixed in 7? https://runkit.com/tolmasky/59bac814a0dafb0012fb9954

Would it be possible to backport these changes to the 6 branch or are they 7 reliant? We've got users running into this now, and even after 7 ships we'll probably have to start on 6 for a while.

**Comment by jridgewell** [comment]
Yup, fixed in 7.

**Comment by tolmasky** [comment]
Would it be possible to backport these changes to the 6 branch or are they 7 reliant? We've got users running into this now, and even after 7 ships we'll probably have to start on 6 for a while.

**Comment by jridgewell** [comment]
I don't think we're cutting any more 6 releases, mainly because there's not enough of us to fix 6 bugs and work on 7.
