### ISSUE TITLE
babel-register should passthru for other handlers.

### ISSUE THREAD

**Issue by jdalton** [babel/babel#6248]
At the moment `babel-register` hooks into `require.extensions` but doesn't passthru to previous `require.extensions` compilers. This makes order important for things like [@std/esm](https://github.com/standard-things/esm) *(related issue [here](https://github.com/standard-things/esm/issues/62))*.

`@std/esm` will passthru to existing `require.extensions` handlers so folks can load `@std/esm` after `babel-register` but it would be rad if `babel-register` would also passthru so order wasn't important.

**Comment by jridgewell** [comment]
Can you make a PR? I'm not familiar enough with the require hooks to make the fix myself.

**Comment by jdalton** [comment]
Totally 💯 !

**Comment by jridgewell** [comment]
I know we had [previous issues](https://github.com/babel/babel/issues/4535) where babel would recompile the file from disk, but that's been fixed in 7. Is that the same issue as this?

**Comment by jdalton** [comment]
> Is that the same issue as this?

No this is a different issue where previous handlers aren't called. It requires a couple more hooks to be added but it's doable to passthru to existing compilers to build on each other.

**Comment by jdalton** [comment]
Actually with the move to `pirates` I've found a way to support `babel-register` and others that use `pirates` without any work from you all :yum:! Look for it in the v0.13.0 release of `@std/esm`.

**Comment by danez** [comment]
If you have ideas for improvements or better ways of how pirates could work, let us know I also have access there.

**Comment by jdalton** [comment]
Thanks @danez! I'll be sure to!
