### ISSUE TITLE
optimize for of Object.keys

### ISSUE THREAD

**Issue by lukescott** [babel/babel#6252]
> Choose one: is this a bug report or feature request?

Feature request.

### Input Code

```js
for (let key of Object.keys(object)) {	

}
```

### Expected Behavior

Built-in functions that always return an array should be optimized like an inline `[...]`:

```js
var _arr = Object.keys(props);
for (var _i = 0; _i < _arr.length; _i++) {
	var key = _arr[_i];
}
```

### Current Behavior

Built-in functions that always return an array are not optimized:

```js
var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
	for (var _iterator = Object.keys(object)[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
		var key = _step.value;
	}
} catch (err) {
	_didIteratorError = true;
	_iteratorError = err;
} finally {
	try {
		if (!_iteratorNormalCompletion && _iterator.return) {
			_iterator.return();
		}
	} finally {
		if (_didIteratorError) {
			throw _iteratorError;
		}
	}
}
```

### Possible Solution
Check for commonly used built-in functions such as Object.keys. If these functions are used, optimize "for of".

### Context
I often use for of + Object.keys to iterate over an object. This is cleaner than for in + object.hasOwnProperty.

### Your Environment

https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=GYewTgBAFANgpgFwgazgTwiYEDyAjAKzgGMEA6VNAZyhEJIQEpGIBvAKAEh2BfIA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26

### Other

With TypeScript support coming in 7.0 and with existing Flow support, could the optimization be made if a variable is defined as an array?

**Comment by hzoo** [comment]
hey @lukescott this is already done in v7 😄  so maybe upgrade https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=GYewTgBAFANgpgFwgazgTwiYEDyAjAKzgGMEA6VNAZyhEJIQEpGIBvASAChOBfIA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-beta.0

**Comment by lukescott** [comment]
Oh, sweet! TY @hzoo !
