### ISSUE TITLE
'babel-generator' should not inject newlines before the update suffix operator

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6253]
In JS, there are a few places where it's explicitly defined that newlines may not exist. We recently reworked some logic in https://github.com/babel/babel/pull/5950 for instance so we can explicitly declare "no newlines" for instance, and it will reformat comments to skip newlines.

In https://github.com/babel/babel-loader/issues/513, it was reported that we don't respect the no-newline insertion logic for `i++` and `i--`.

Looking at [the ECMAScript spec](https://github.com/babel/babel-loader/issues/513), it seems like we handle the other cases. We don't explicitly handle `() [no LineTerminator here] => {}` for arrow functions, but there's no way to represent a comment at that position in our AST so we're safe from that one.

### Input Code

```js
obj.foo/*comment*/++;
```

### Expected Behavior
```
obj.foo/*comment*/++;
```

### Current Behavior
```
obj.foo
/*comment*/
++;
```
### Possible Solution
The _think_ the quickest fix is to just call `.startTerminatorless(true)` on all suffix-operator `UpdateExpression` nodes. Since update expressions are usually small anyway, that seems like it'd have a minimal effect on the readability of things.

It's not quite how that helper was originally intended to be used, but nothing pops to mind as a big downside in this case.

**Comment by zestime** [comment]
It looks simple. I can do it. By the way, two tests in babel-generator are broken. They are related to 7f390b028212b49dffc371989e92d972545b33fa about parentheses.
