### ISSUE TITLE
Question: 7.0.0-beta.0 - babel-register exports with __esModule - intentional?

### ISSUE THREAD

**Issue by Ambroos** [babel/babel#6266]
The package `babel-register@7.0.0-beta.0` no longer does `module.exports = exports["default"]` but instead does:

```js
exports.__esModule = true;
exports.revert = revert;
exports.default = register;
```

While this makes revert available it also means that compatibility with existing implementations breaks. `interpret` for example (used for config.babel.js in projects like webpack) currently relies on the default export pointing to the register function.

It's patchable in interpret, of course, but I wonder if it's intentional. It's not currently an issue in `webpack` since it ignores failures and hopes for the best (and just `require('babel-register')` is enough to trigger register() with the default extensions). `parallel-webpack` fails hard as it assumes [the register call](https://github.com/js-cli/js-interpret/blob/master/index.js#L5) succeeds.

Is this an intentional breaking change and will the exports stay the same? If yes, I'll make some PR's for other projects to use `module = module && module.__esModule ? module.default : module;` instead.

**Comment by loganfsmyth** [comment]
I'll PR a fix. It's a change we knew about but mostly forgot to go back and fix, sorry about that.

**Comment by loganfsmyth** [comment]
Fix: https://github.com/babel/babel/pull/6268

**Comment by Ambroos** [comment]
Awesome, thanks a lot for the fast response!
