### ISSUE TITLE
Bind single function definition in loose mode 

### ISSUE THREAD

**Issue by kurtextrem** [babel/babel#6272]
Feature Request
Twitter Thread: https://twitter.com/aweary/status/908114184130281472 & https://twitter.com/left_pad/status/910219061174337537

![](https://pbs.twimg.com/media/DJpFCPCVYAAfEjw.jpg)

**Comment by Andarist** [comment]
I might try working on this.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since "make some non-compliant things work" is not a goal of `loose` mode (ideally, it only changes things where you don't notice them because your code does not rely on them).

Instead, you can use something like this:
```js
class Foo {
  bar = this.bar.bind(this);
  
  bar() {
  	return 19
  }
}
```
