### ISSUE TITLE
7.x regression with env

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6273]
bug report

```
{
  "dependencies": {
    "babel-cli": "7.0.0-beta.1",
    "babel-preset-env": "2.0.0-beta.1"
  }
}
```

Ok looks like it works in 2.0.0-alpha.20 so it happened between `alpha.20` and `beta.0` https://github.com/babel/babel/releases/tag/v7.0.0-beta.0

Error: a.js: Couldn't find a Program
    at Scope.getProgramParent (/b/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/scope/index.js:836:11)

### Minimal Input Code

```js
for (let art of c) {
  () => art;
}

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["env"]
}
```

**Comment by jridgewell** [comment]
Repl?

**Comment by hzoo** [comment]
we need to fix env in the repl

**Comment by hzoo** [comment]
jk incompatible versions since i forgot to update preset-env packages to beta.1..

**Comment by brokentone** [comment]
I'm currently getting this error as described here. What was the resolution?
