### ISSUE TITLE
Babel 7.0.0 beta 1 transform-es2015-modules-commonjs plugin: "default" and "member" import broken

### ISSUE THREAD

**Issue by dnalborczyk** [babel/babel#6275]
_not sure if this counts as a bug, since the following is not spec anyways, but it was working in Babel 6.x.x and 7.0.0 beta 0 -- unless it's intendet behavior now?_

importing a default member and member from a common js module throws exception.

```
import express, { Router } from 'express';

const router = Router();
```

exception:
```
const router = (0, _express.Router)();
                                   ^
TypeError: (0 , _express.Router) is not a function
```

configuration
```
{
    "plugins": [
        "babel-plugin-transform-es2015-modules-commonjs"
    ]
}
```

**Comment by loganfsmyth** [comment]
Looks like a bug to me! Thanks for reporting, I'll take a look.
