### ISSUE TITLE
Maybe a better module system

### ISSUE THREAD

**Issue by xialvjun** [babel/babel#6277]
I don't know where to make an ecmascript rfc, so I put it here.

Js is a dynamic language, I don't think we should use the concept of static importing.
If it's static importing, just consider `import { a, b, c } from 'http://www.google.com/abc.js';`, how can you believe the imported must have fields `a, b, c`: google can respond `foo.js` this time and 'bar.js' next time.

The duty of tree shaking and do some minification should be put on tools like `google clojure compiler`...

Then, where is [the better module system](https://github.com/xialvjun/async-module/tree/master/exports):

```js
// a.js
exports.sayHello = () => console.log('a_hello');
const b = await import('./b.js');
b.sayHello();
```

```js
// b.js
const [a, c, d] = await Promise.all(['./a.js', './c.js', './d.js'].map(import));
a.sayHello();
exports.sayHello = () => console.log('b_hello');
```

If `a.js` is the entry module, then it will log `a_hello\nb_hello\n`.
If `b.js` is the entry module, then it will throw a runtime exception since `b.sayHello` is undefined and undefined can not be used as a function.

And what is more?
```js
let a;
try {
  a = await import('./a.js');
} catch(e) {
  console.error(e);
}
if (!a) { alert('import a wrong') }
```

**Comment by loganfsmyth** [comment]
Sorry, this isn't the place for this. I'd recommend posting on https://esdiscuss.org/ if you feel strongly about this.

I think you should also clarify your arguments because as it is I don't think it is clear from your examples what you feel is lacking in the current syntax and proposed `import()`.
