### ISSUE TITLE
Optimize `let a;` - skip explicit undefined when possible

### ISSUE THREAD

**Issue by Andarist** [babel/babel#6278]
**Feature request**

### Input Code
```js
let a;
```

### Expected Behavior
```js
var a;
```

### Current Behavior
```js
let a = void 0;
```

### Context
Just a small optimization. Need to be checked if `let` declaraction is within loop - if yes then it cannot get optimized, but if not it should be ok to skip explicit undefined. 

Posting this as a reminder, I plan to work on this, but not right now, because I have more pressing issues to do.

**Comment by jridgewell** [comment]
This is a good beginner-friendly bug.

**Comment by Andarist** [comment]
There are many gotchas with this - https://github.com/babel/babel/issues/255 . So need to be checked carefully

**Comment by ajaymathur** [comment]
Checking if it is declared in loop, should be the only check?

**Comment by jridgewell** [comment]
I'm like 90% sure that's all that's needed. If it's not, it's a bug much deeper in the codebase.

**Comment by Andarist** [comment]
like mentioned in the linked thread, we need to be careful for such cases:
```js
if (true) {
  let foo = true;
} 

if (true) {
  let foo;

  if (foo) {
    alert(foo);
  }
}
```

We can probably check binding identifiers to determine if:
- explicit undefined is needed (would cause some false positives for sure)
- just rename the identifier if there is a clash name + loop check as mentioned

**Comment by jridgewell** [comment]
I believe those errors were wayyyyy back in babel history. Now, those two `foo`s should always be different bindings, and be renamed (if possible) or closed over (if not possible) to ensure they're different `var` bindings.

**Comment by Andarist** [comment]
Ok, thanks for the clarification - I have started working on this.
