### ISSUE TITLE
"sh: 1: ./node_modules/.bin/babel: not found" while deploying to heroku

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [babel/babel#6281]
I get the error "sh: 1: ./node_modules/.bin/babel: not found" while deploying to heroku.

<pre>
Counting objects: 37, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (31/31), done.
Writing objects: 100% (37/37), 9.85 KiB | 0 bytes/s, done.
Total 37 (delta 1), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  ~8.5.0
remote:        engines.npm (package.json):   ~5.4.2
remote:        
remote:        Resolving node version ~8.5.0...
remote:        Downloading and installing node 8.5.0...
remote:        Bootstrapping npm ~5.4.2 (replacing 5.3.0)...
remote:        npm 5.4.2 installed
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (not-found)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > uws@0.14.5 install /tmp/build_4a0d9a1cc22127994edbcb3f94942f23/node_modules/uws
remote:        > node-gyp rebuild > build_log.txt 2>&1 || exit 0
remote:        
remote:        
remote:        > shielded-anchorage-57783@1.0.0 postinstall /tmp/build_4a0d9a1cc22127994edbcb3f94942f23
remote:        > npm run build
remote:        
remote:        
remote:        > shielded-anchorage-57783@1.0.0 build /tmp/build_4a0d9a1cc22127994edbcb3f94942f23
remote:        > npm run clean && ./node_modules/.bin/babel server.js --out-dir dist && ./node_modules/.bin/babel app --out-dir dist/app && cp secrets.json dist
remote:        
remote:        
remote:        > shielded-anchorage-57783@1.0.0 clean /tmp/build_4a0d9a1cc22127994edbcb3f94942f23
remote:        > rm -rf dist
remote:        
remote:        sh: 1: ./node_modules/.bin/babel: not found
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! shielded-anchorage-57783@1.0.0 build: `npm run clean && ./node_modules/.bin/babel server.js --out-dir dist && ./node_modules/.bin/babel app --out-dir dist/app && cp secrets.json dist`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the shielded-anchorage-57783@1.0.0 build script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /app/.npm/_logs/2017-09-20T18_22_39_721Z-debug.log
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! shielded-anchorage-57783@1.0.0 postinstall: `npm run build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the shielded-anchorage-57783@1.0.0 postinstall script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /app/.npm/_logs/2017-09-20T18_22_39_749Z-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: ! Push rejected to shielded-anchorage-57783.
remote: 
To https://git.heroku.com/shielded-anchorage-57783.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shielded-anchorage-57783.git'
</pre>

### my package.json
```
{
  "name": "shielded-anchorage-57783",
  "version": "1.0.0",
  "private": true,
  "main": "server.js",
  "scripts": {
    "postinstall": "npm run build",
    "start": "node ./dist/server.js",
    "dev": "npm run clean && ./node_modules/.bin/nodemon server.js --exec ./node_modules/.bin/babel-node",
    "test": "./node_modules/.bin/_mocha --require babel-core/register ./test/**/*.spec.js",
    "build": "npm run clean && ./node_modules/.bin/babel server.js --out-dir dist && ./node_modules/.bin/babel app --out-dir dist/app && cp secrets.json dist",
    "clean": "rm -rf dist"
  },
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ]
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.0.0",
    "babel-preset-env": "^1.6.0",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "chai": "^4.1.2",
    "chai-http": "^3.0.0",
    "eslint": "^4.7.1",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-html": "^3.2.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.3.0",
    "eslint-plugin-standard": "^3.0.1",
    "express-list-endpoints": "^3.0.0",
    "mocha": "^3.5.3",
    "nodemon": "^1.12.1"
  },
  "dependencies": {
    "body-parser": "^1.18.1",
    "cluster": "^0.7.7",
    "cors": "^2.8.4",
    "dotenv": "^4.0.0",
    "express": "^4.15.4",
    "express-jwt": "^5.3.0",
    "express-validator": "^4.1.1",
    "jsonwebtoken": "^8.0.1",
    "method-override": "^2.3.9",
    "mongoose": "^4.11.12",
    "os": "^0.1.1",
    "socket.io": "^2.0.3",
    "token-extractor": "^0.1.6"
  },
  "engines": {
    "node": "~8.5.0",
    "npm": "~5.4.2"
  }
}
```
other users reported similar issues in [40980790](https://stackoverflow.com/questions/40980790/node-app-application-error) [45143298](https://stackoverflow.com/questions/45143298/babel-node-is-not-getting-installed-on-heroku) stackoverflow..

**I do not have a possible solution** :sleepy:

**Comment by loganfsmyth** [comment]
Heroku does not install dev dependencies since the server sounds as "production" by default: https://stackoverflow.com/questions/43463204/deploy-to-heroku-gulp-not-found-error

**Comment by carvalhoviniciusluiz** [comment]
I understand! in that case then have to create the variable NPM_CONFIG_PRODUCTION = false in heroku to deploy :+1: it would be the only way

```
heroku config:set NPM_CONFIG_PRODUCTION=false
```
