### ISSUE TITLE
`var`s which conflicts with a `let` declared in an outer block aren't reported.

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#6283]
This issue only appears if the let declaration is inside a block. If it is a direct child of a function body/program, babel throws correctly.

  [REPL](https://babeljs.io/repl/build/4985#?babili=false&browsers=&build=&builtIns=false&code_lz=N4KABGA2CmAuYEMDc4zDANwQJ0UsAviAUA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=stage-2&prettier=false&targets=&version=7.0.0-beta.1)

### Input Code
  ```js
  {
    let a;
    { var a; }
  }
  ```

### Expected Behavior
  ```
  Duplicate declaration "a"
  ```

### Current Behavior
No error

### Possible Solution

`Scope` should check the block scopes that variable declarations visit while they "walk up" the scope.
It should also keep track of them, in the case that the variable declaration comes before the lexical declaration (e.g. `{ { var a; }; let a; }`)

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.1
| node             | 
| npm              | 
| Operating System |

**Comment by arthurchipdean** [comment]
I would like to claim this bug. I have narrowed the issue down to the Declaration method in the CollectorVisitor on line 65 in scope/index.js

If I comment out the if statement at that line the bug an error is correctly thrown:
```
    // delegate block scope handling to the `BlockScoped` method
    if (path.isBlockScoped()) return;
```

I just have to figure out why that code is there and what effects removing it may have. ( I think the solution may be adding another condition to that if statement. ) I'm confident I'll be able to solve it with a bit more time though.

**Comment by arthurchipdean** [comment]
Can I claim this bug? I have narrowed the issue down to the Declaration method in the CollectorVisitor on line 65 in scope/index.js

If I comment out the if statement at that line an error is correctly thrown:

    // delegate block scope handling to the `BlockScoped` method
    if (path.isBlockScoped()) return;

I think the solution will be some modification to the BlockScoped method?

**Comment by jridgewell** [comment]
@arthurchipdean: it's yours.

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=N4KABGA2CmAuYEMDc4zDANwQJ0UsAviAUA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.23.3&externalPlugins=&assumptions=%7B%7D

This problem is no longer existing.
