### ISSUE TITLE
support --experimental-modules flag with node v8.5.0

### ISSUE THREAD

**Issue by dnalborczyk** [babel/babel#6285]
I tried to use Babel (6.26.0/7.0.0 beta 1) with native ES6 modules in node v8.5.0 with the new **--
experimental-modules** flag set, and noticed a couple issues which would need to be addressed in order to make it work.

_reference:_
https://nodejs.org/dist/latest-v8.x/docs/api/esm.html

1. one would need to pass in the new **--experimental-modules** flag to node (unsupported by Babel). I added the flag to the babel-node.js package:
https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel-node.js

addressed with PR: https://github.com/babel/babel/pull/6286

2. (for now) node v8.5.0 expects ES6 modules with an *.mjs file extension, unfortunately Babel renames all file extensions after transpilation to *.js.

after renaming all files back to *.mjs ...

3. _I'm not quite sure about this one, haven't looked into it:_ it seems that the transpilation step is being executed after node is loading the modules natively, as I get an exception when I try to use newer syntax (e.g. optional-chaining, tried other plugins as well), with babel.js and babel-node.js.

```
const x = null;
x?.foo;

(node:41228) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: Unexpected token .
    at StandardModuleRequest.createModule (internal/loader/resolveRequestUrl.js:35:12)
    at <anonymous>
```

babel options:
```
{
    "plugins": [
        "babel-plugin-transform-optional-chaining"
    ]
}
```

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 and 7.0 beta 1
| node             |  8.5.0
| npm             |  5.3.0
| Operating System |  macOS High Sierra 10.13 Beta (17A362a)

**Comment by hzoo** [comment]
for 2, We landed https://github.com/babel/babel/pull/6221

**Comment by bmeck** [comment]
@dnalborczyk what command are you using to run `node`? `babel-node` doesn't hook into ESM loading and is using `require.extensions` which has been deprecated for a few years.

**Comment by dnalborczyk** [comment]
@bmeck first, thank you for getting the ball rolling and the implementation for supporting ESM in node!

Yeah, I think this issue can be closed for the time being, till the node _ESM_ implementation and/or the deprecated _require.extensions_ get a proper replacement - if ever. At the time of opening this issue, I wasn't aware of node's _require.extensions_, though on the way of digging through this issue I found [_standard/esm_](https://github.com/standard-things/esm). Unfortunately it doesn't work with Babel as well - for a different reason (related issues: https://github.com/standard-things/esm/issues/109 and https://github.com/babel/babel/issues/6248).

I also like that standard/esm supports .js file extensions. Both, Babel and standard/esm, build their functionality on top of the deprecated _require.extensions_ - I suppose for the lack of a replacement.

**Comment by dnalborczyk** [comment]
closing this issue as the _--experimental-modules_ flag wouldn't be useful as of now, though I think it would generally better to pass *all* possible flags to node, not just a handful whitelisted.
