### ISSUE TITLE
babel-preset-2015: 'don't make yearly presets' message is hard to read and messes up the console

### ISSUE THREAD

**Issue by ankon** [babel/babel#6290]
### Expected Behavior
`npm install` output is reasonable.

### Current Behavior
Noisy and messy output from babel-preset-es2015 (see screenshot)
![screen-babel-messy-output](https://user-images.githubusercontent.com/1210641/30735843-be2934bc-9f80-11e7-9604-bc4d233456ae.png)

### Possible Solution
1. Use less fancy emojis that simply might not exist everywhere
2. Shorten the message so it fits into a reasonable terminal size (maybe use multiple lines and explicit line breaks?)

### Your Environment
~~~~
$ node -v
v7.10.1
$ npm -v
4.2.0
$ uname -a
Linux XXXXXXXX 4.12.12-300.fc26.x86_64 #1 SMP Mon Sep 11 17:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
rxvt-unicode-256color
~~~~

**Comment by loganfsmyth** [comment]
The fact that it prints out on multiple lines as the progress spinner updates seems like a bug in `npm` to me. I agree that part of the output is unfortunate, but it'd happen no matter what deprecation warning we put in there.

For the message itself, I'd say it is just as large as we want it to be. The fact that you noticed it is pretty much an indication that it's working. 

> Use less fancy emojis that simply might not exist everywhere

What does that gain us? The emoji don't provide semantic value, so if they don't render, then no information is lost, and if they do render, they are fun.

> Shorten the message so it fits into a reasonable terminal size

Why does the size of the message make any appreciable difference in this case?

**Comment by hzoo** [comment]
Thanks for reporting, I made it a bit shorter. The multiple prints seems like a separate issue like Logan said 

> maybe use multiple lines and explicit line breaks?

I don't think there is a way to do this, otherwise I would of tried to format it better earlier. We'd like to get users to switch from babel-preset-es2015 to babel-preset-env while explaining the reasoning there, which doesn't really fit into a single line and most people ignore it.

```
npm install babel-preset-env --save-dev
```

```js
{
  "presets": ["env"] // instead of "es2015"
}
```

**Comment by ankon** [comment]
Fair enough. 

> What does that gain us? The emoji don't provide semantic value, so if they don't render, then no information is lost, and if they do render, they are fun.

It looks ugly, and at least for me having ugly text in the very first message I see from a tool is a bit of an indication of other issues hidden in the tool. This heuristic guided me well so far, but obviously it's just a very rough heuristic. :)
