### ISSUE TITLE
Potential issue transpiling the RegExp unicode constructor?

### ISSUE THREAD

**Issue by Nickersoft** [babel/babel#6291]
Hi guys, I'm building an app via React Native and seem to be running into an issue supporting Unicode in my regex. After I saw that Unicode regex was part of the ES6 standard, I figured I'd reach out to the Babel community over the RN one, as I presume that's where the issue may lie.

Choose one: is this a bug report or feature request?
Bug report

### Input Code

```js
str.match(new RegExp(`(?!\\s)(.*?([${terminators.join('')}]|$))`, 'gu'));
```

where `terminators` is a list of all potential Unicode sentence terminators (periods, question marks, etc.) across multiple languages.

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["react-native", "flow"],
  "plugins": ["transform-decorators-legacy", "transform-es2015-unicode-regex"]
}

```

### Expected Behavior

The regex operation should return any matches (works as expected on iOS).

### Current Behavior

On Android, a warning is thrown that halts my app:

```
 SyntaxError: Invalid flags supplied to RegExp constructor.
```

From my understanding, Babel [uses regexpu](https://github.com/mathiasbynens/regexpu) to support ES6 Unicode regex, so technically this error shouldn't be thrown, should it?

### Possible Solution

Removing the 'u' flag makes the warning go away... but I don't want to leave any room for my app to not find matches in the future because this flag is missing.

### Context

I'm trying to find matches in multilingual strings, so it's important my regex doesn't exclude Unicode.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 (via React Native)
| node             | 8.5.0
| npm              | 5.4.2
| Operating System | macOS Sierra

**Comment by nicolo-ribaudo** [comment]
Babel can't transpile that regex, since its value is dynamic and it is not known at compile time. It should be handled by a polyfill.

**Comment by jridgewell** [comment]
Yup, you need to add `core-js` to your runtime, it already [supports](https://github.com/zloirock/core-js/blob/master/modules/es6.regexp.constructor.js) this.

**Comment by Nickersoft** [comment]
Thanks for the help guys!

**Comment by zloirock** [comment]
@jridgewell not exactly. It's for another regex features.

**Comment by jridgewell** [comment]
I should have read at the source. Isn’t this a runtime polyfill `core-js` would do?
