### ISSUE TITLE
Add `Promise#finally` to `babel-preset-stage-3`

### ISSUE THREAD

**Issue by johnhaley81** [babel/babel#6292]
Now that https://github.com/tc39/proposal-promise-finally is in stage 3. Are there any plans to add `Promise#finally` to the preset?

**Comment by zloirock** [comment]
`Promise#finally` is a part of standard library, not syntax, so it can't be added to presets. [It's a part of `core-js`](https://github.com/zloirock/core-js#stage-3-proposals), so it's available in `babel-polyfill`.

**Comment by existentialism** [comment]
@johnhaley81 as a sidenote, we have support for this in babel-preset-env@2.x (currently in beta), with the recently added [`shippedProposals` option](https://github.com/babel/babel-preset-env/#shippedproposals).

**Comment by malixsys** [comment]
Docs for `shippedProposals` have moved [here](https://github.com/babel/babel/tree/master/packages/babel-preset-env#shippedproposals).
