### ISSUE TITLE
babel.transform API is not using .babelrc

### ISSUE THREAD

**Issue by jordanbtucker** [babel/babel#6296]
## Bug

`babel.transform` should use `.babelrc` as indicated at https://babeljs.io/docs/usage/api/.

> All transformations will use your local configuration files (.babelrc or in package.json).

### Input Code

```js
const {strictEqual} = require('assert')
const {transform} = require('babel-core')

// This should use the configuration in .babelrc.
const withOptions = transform('code()').code

// The configuration is explicitly provided here.
const withoutOptions = transform('code()', {presets: ['env']}).code

// The two should match.
strictEqual(withOptions, withoutOptions)
```

### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    "env"
  ]
}
```

### Expected Behavior

The code should run without error.

### Current Behavior

The following output is displayed:

```
assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: 'code();' === '"use strict";\n\ncode();'
```

Note that `babel.transformFile` does not suffer from this bug.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | 6.11.2
| npm              | 5.3.0
| Operating System | Windows 10 / Ubuntu 16.04

**Comment by pudility** [comment]
They are not the same. The first is:
```js
code();
```
The second is:
```js
"use strict";

code();
```

When you use `strictEqual` it will error if they are not the same, however if you want to check if they are the same you can use `===`. Here is an example:
```js
const {strictEqual} = require('assert')
const {transform} = require('babel-core')

// This should use the configuration in .babelrc.
const withOptions = transform('code()').code
console.log(withOptions);

// The configuration is explicitly provided here.
const withoutOptions = transform('code()', {presets: ['env']}).code
console.log(withoutOptions);

console.log(withOptions === withoutOptions);

// This should error if the above is true.
strictEqual(withOptions, withoutOptions)
```

[More documentation on `strictEqual `](https://nodejs.org/api/assert.html#assert_assert_strictequal_actual_expected_message)

**Comment by jordanbtucker** [comment]
@pudility You're missing the point. `withOptions` and `withoutOptions` *should* be the same if `transform` was pulling the configuration from `.babelrc`. The reason I used `strictEqual` is to provide a test for this case.

**Comment by pudility** [comment]
I see what you are saying now. You are saying that they should either both or neither have `"use strict";`. I don't know why that is happening, sorry.

**Comment by jordanbtucker** [comment]
It turns out that if I specify a `filename` option, then it will use `.babelrc`.

```js
// This works (even if `code.js` doesn't actually exist).
const withFilename = transform('code()', {filename: 'code.js'}).code

// This doesn't.
const withoutFilename = transform('code()').code
```

**Comment by xtuc** [comment]
It works with `filename` because the `.babelrc` file is resolved relatively to the file location. Alternatively you can pass your configuration in the transform API.

Can I close this issue? Feel free to open it if needed later.

**Comment by jordanbtucker** [comment]
Thanks for the validation. I think the docs should be updated to make this more clear.

**Comment by xtuc** [comment]
Yes, that would be great. Do you want to contribute? Would you mind updating the documentation [here](https://github.com/babel/babel/blob/master/packages/babel-core/README.md).

**Comment by pudility** [comment]
I can also update the documentation if you don't want to.

**Comment by jordanbtucker** [comment]
I'm happy to contribute, but it might be better to let someone more familiar with the internals update the docs. If @pudility wants to take that on, it's fine with me.

**Comment by tbranyen** [comment]
@xtuc this issue doesn't look to ever have been resolved, by updating documentation. What do you mean by:

> It works with filename because the .babelrc file is resolved relatively to the file location. Alternatively you can pass your configuration in the transform API.

Do you have a quick example you could paste in here, so future confused folks like myself have a reference?

I tried:

``` js
    const { ast } = transform(code, {
      sourceType: 'module',
      sourceFileName: path,
      plugins: ['transform-object-rest-spread'],
    });
```

And this didn't do anything. From what I can tell the argument is ignored. Shouldn't `sourceFileName` be enough to resolve a `.babelrc`?

**Comment by loganfsmyth** [comment]
@tbranyen The argument name you want is just `filename`. I don't know what `loadBabelRc` in your example is.
```
const { code } = transform(code, {
  filename: path
});
```
would be the normal approach.

**Comment by tbranyen** [comment]
@loganfsmyth works great, updated my comment :+1:
