### ISSUE TITLE
Having Class issue with custom elements

### ISSUE THREAD

**Issue by arguiot** [babel/babel#6297]
# Bug

I'm trying to create custom elements ([MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements)), but it returns me something unexpected.

### Input Code

```js
function component (name, callback) {
	class component extends HTMLElement {
		constructor () {
			super();
			callback(this);
		}
	}
	customElements.define(name, component);
}
```
Link : [REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABBOBbADggpmKiAUYAhqlgDTJEA2VARkRANYCUiA3gFACQEVRAzv2RpMYHHiwAPKDgAmQgBIAVALIAZAKJUspXO248E_KACcQ0OCYKtOXO_xDosJ_MwDcBntToNG-KAAWMPzuBgC-3BE8IMZoWjri_AB0sljAMGKEJOTCGNi4oWFAA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0)

My tests: https://codepen.io/arguiot/pen/KvVdOV

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
	presets: ["env"]
}
```

### Expected Behavior

It shouldn't return any error like:
```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

### Current Behavior

Returns an error, and display nothing (in my tests (link upper))

### Possible Solution

I'm not a pro, I don't have any solutions.

### Context

I'm trying to create a function to create custom elements / components.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  Gulp Babel v6.1.2
| node             | v8.4.0
| npm              | 5.4.1
| Operating System | macOS 10.12.6

**Comment by jridgewell** [comment]
https://github.com/babel/babel/issues/4480.
