### ISSUE TITLE
In babel-cli add a short log option when compiling

### ISSUE THREAD

**Issue by SamFromDaUk** [babel/babel#6303]
Choose one: is this a bug report or feature request? feature request

### Input Code

N/A

### Babel Configuration (.babelrc, package.json, cli command)

```
{
  "babel-cli": "^6.24.1"
}
```

`node_modules/.bin/babel ./app/src -w -p -d ./app/scripts --modules amd --extensions '.es6,.jsx' --source-maps`

### Expected Behavior

When compiling a project with a large number of files there can be an excessive amount of logs produced.

The `--quiet` option removes all logs, however something in between may be of use. Perhaps a `x of x files compiled` or a percentage based option would be useful?

![screen shot 2017-09-25 at 16 31 34](https://user-images.githubusercontent.com/2401212/30816875-1842fb14-a20f-11e7-85f3-a427555f993c.png)

### Current Behavior

For large projects either a large amount of logs are shown, or none at all with the `--quiet` option.

### Possible Solution

Add another method of logging the progress of the compiler to show percentage complete or `x of x compiled` message.

### Context

Build step of my project, I can choose between 500+ lines of output or 0.

### Your Environment

N/A

**Comment by derwaldgeist** [comment]
+1 Would love to see this, too. BTW, this has already been proposed as #1931.

**Comment by hzoo** [comment]
Do we want the files to be logged at all, we could even change the default behavior to not show logs too depends on what we want?

**Comment by derwaldgeist** [comment]
I don't see any reason to log these files. It just clutters up my terminal. If something goes wrong, ok, then please output an error. But otherwise...

**Comment by thymikee** [comment]
Hey, would something like this ok?

Default:
<img width="422" alt="screen shot 2018-02-27 at 12 38 39" src="https://user-images.githubusercontent.com/5106466/36726774-3bc125ea-1bbb-11e8-9520-333361e5c0e2.png">

`--quiet`:
<img width="478" alt="screen shot 2018-02-27 at 12 38 49" src="https://user-images.githubusercontent.com/5106466/36726775-3be37a96-1bbb-11e8-8e62-4bde05053734.png">

Also, on Node >=8 we can easily adjust error message to not include unhelpful stacktrace:
<img width="429" alt="screen shot 2018-02-27 at 12 40 32" src="https://user-images.githubusercontent.com/5106466/36726875-83c48666-1bbb-11e8-8ca1-7fbc20d2d093.png">
(but with or without my changes, the error message on node <=6 is a mess and doesn't tell anything)

**Comment by existentialism** [comment]
@thymikee thanks for the pr!

> Do we want the files to be logged at all, we could even change the default behavior to not show logs too depends on what we want?

Making `--quiet` the default gets a 👍 from me.

**Comment by derwaldgeist** [comment]
@existentialism I want to second this. You'd only need the verbose stuff once in a while.

**Comment by hzoo** [comment]
Yeah this is what I meant in https://github.com/babel/babel/issues/6303#issuecomment-369722283

**Comment by thymikee** [comment]
Ok, I'm happy to update the PR accordingly :)
