### ISSUE TITLE
Generate blacklist based on targets

### ISSUE THREAD

**Issue by sebmck** [babel/babel#631]
Possibly through a `blacklistUserAgent` option or something. Would use the kangax compat-table. Important to note that it does not guarantee complete spec compliancy on the vendors end.

References:

 - https://github.com/kangax/compat-table
 - https://github.com/Fyrd/caniuse
 - https://github.com/3rd-Eden/useragent

**Comment by monsanto** [comment]
#272 lives? :+1:

**Comment by sebmck** [comment]
@monsanto Kind of. You'd pass a user agent instead of a more vague range. At least that's what I have in mind.

**Comment by cesarandreu** [comment]
:+1: This is awesome!

Maybe having something similar for node and iojs? It could be a manually maintained list instead of trying to do feature detection. 

For example, iojs claims the following ES6 features are available:
- const
- Map
- WeakMap
- Set
- WeakSet
- Generators
- Binary and Octal literals
- Promises
- New String methods
- Symbols
- Template strings


Based on kangax compat-table, you could take the safe route and only blacklist features that are marked as complete fully implemented:

- Template Strings
- For..Of (not iterators, though; I'm not sure if the transformer does both)
- Map + Set + WeakMap + WeakSet
- Binary and Octal Literals
- Promises

I thought you could disable Generators too, but it seems that it's not fully implemented.

**Comment by sebmck** [comment]
@cesarandreu I'll probably add a different API that you can just pass in something like `{ blacklistBasedOnEnvironment: { engine: "io", version: "1.0.0" } }` or something.

**Comment by timoxley** [comment]
This is a great idea.

**Comment by neformal13** [comment]
One more reference: 
https://www.npmjs.com/package/caniuse-db
This repo contains raw data from the caniuse.com support tables.

**Comment by sebmck** [comment]
Superseded by #883.

**Comment by deepsweet** [comment]
hey guys.

I'm trying to maintain [Can I ES?](https://github.com/canies/canies) – semi-automated ES6/7 features database and test suite based on [kangax/compat-table](https://github.com/kangax/compat-table) (at this time) and built on top of semver, mocha and karma. Database itself is plain JSON so it can be easily used to generate babel's `--blacklist`.

if anyone is interested – help is appreciated: 1) port the rest of tests from compat-table to mocha 2) test it in any necessary Node.js/io.js and browsers version.

@sebmck you're free to suggest database format or anything else.

**Comment by sebmck** [comment]
Hey @deepsweet, sorry for taking so long to get back to you. I don't really think individual compatibility tests are very useful. The only way Babel could disable a certain feature transformation is if it was **totally** supported by the target environment, partial support isn't a good quantifier for that.

**Comment by deepsweet** [comment]
we can easily filter "totally" with `.every()`  and "partial" with `.some()`:

```js
var semver = require('semver');
var data = require('./data');

var target = {
    name: 'io.js',
    version: '1.0.3'
};

var every = Object.keys(data.es6.let).every(function(subtestName) {
    var targetInSubtest = data.es6.let[subtestName][target.name];

    return targetInSubtest &&
           semver.satisfies(target.version, targetInSubtest.version) &&
           target.flag === targetInSubtest.flag
});

if (every) {
    console.log('totally let');
}
```

**Comment by sebmck** [comment]
The tests aren't quite comprehensive enough to verify the compliancy of any implementation. Here's a [snippet](https://github.com/babel/babel/tree/master/test/core/fixtures/transformation/es6.block-scoping-exec) of just some of the block scoping tests required.

**Comment by deepsweet** [comment]
so let's try to adopt babel tests instead of kangax for this. I'll take a look at your fixtures and try to convert some of them to mocha.

**Comment by sebmck** [comment]
Also all the Traceur tests are ran against Babel too so [these](https://github.com/google/traceur-compiler/tree/master/test/feature/Scope) may be helpful as well.

**Comment by deepsweet** [comment]
even if It's possible to collect them all in one place and wrap in "canies" stuff like semver, db filtering, reporters and so on, it should be constantly maintained to keep in sync with all the tests sources... ideally – become the main source that is focused on Babel (and shared with it), so you can maintain it by yourself by adding new tests to Babel.

**Comment by deepsweet** [comment]
how exactly Babel using Traceur tests suite?

**Comment by deepsweet** [comment]
I'm thinking about using https://saucelabs.com/ (there is a free plan for open source) to autogenerate database (across a bunch of browsers versions with Karma) as Babel prepush hook :) it's possible. but question about tests source is still open.

**Comment by sebmck** [comment]
@deepsweet 

> how exactly Babel using Traceur tests suite?

It's literally running it. https://github.com/babel/babel/blob/master/test/core/traceur.js

**Comment by daliwali** [comment]
+1

I would really like this for Node builds, so that I don't have to package a `dist` folder of compiled js, there could be a script like `"postinstall": "babel lib --out-dir dist"`.

**Comment by sebmck** [comment]
Considering this out of scope and closing for the timebeing.

**Comment by hax** [comment]
@deepsweet I just write https://github.com/hax/babel-features . Any suggestion?
