### ISSUE TITLE
path.traverse : recursive or not ?

### ISSUE THREAD

**Issue by Alphapage** [babel/babel#6313]
Hello,

When using `path.traverse({CallExpression: ... })` in my babel plugin where path is a FunctionDeclaration, I expect it to recursively traverse the tree as stated in the handbook.
It seems to work except for:
- `for (const t of tt) return test()`
- `[].forEach(t=>{return test2()})`
Is it the expected behaviour ? 
If so, why the handbook tells that path traverses the tree recursively ?
Or how do you traverse 'really recursively' the tree ?

Thank you in advance for your help.

**Comment by nicolo-ribaudo** [comment]
The AST is traversed recursively, following these steps:
```
Traverse(node):
    1. For each child of node:
        a. Call the enter visitors for the child's type
        b. Traverse(child)
        c. Call the exit visitors for the child's type
```

In your first example you should see the `test()` call, while in the second example the `[].forEach()` call and then `test2()`.
What is the wrong behavior you are experiencing?

**Comment by Alphapage** [comment]
`[].forEach()` is reached, but neither nested `test()`, nor `test2()` are reached.
If I test with a FunctionDeclaration, the nested CallExpression is reached as expected, but not inside my `for .. of`  or `[].forEach()` body

**Comment by jridgewell** [comment]
Can you provide an example on [AST Explorer](http://astexplorer.net/)? This is what how all babel plugins transform, so I'm confident it's working correctly.

**Comment by Alphapage** [comment]
My big mistake: I was using a ReturnStatement which skipped the nested CallExpression.
So sorry, thank you very much for your help.
