### ISSUE TITLE
Provide option in flow plugin to strip only type word in import type statements

### ISSUE THREAD

**Issue by TrySound** [babel/babel#6314]
Choose one: is this a bug report or feature request?

Feature

### Input Code
```js
import type { .Action } from './actions';
import { store } from './store';
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ['flow']
}
```

### Expected Behavior
```js
import {} from './actions';
import { store } from './store';
```

### Current Behavior
```js
import { store } from './store';
``

### Possible Solution

As an option in plugin/preset and even enable by default

### Context
The problem is skipping such import by bundlers (webpack, rollup), so these files cannot be checked by linters.

| software         | version(s)
| ---------------- | -------
| Babel            |  6
| node             |  6
| yarn              |  1
| Operating System | macosx

**Comment by nicolo-ribaudo** [comment]
You should use `import { type Action } from './actions';`: `import type` statements should be considered side effects free and thus removable.

**Comment by TrySound** [comment]
@nicolo-ribaudo Good suggestion, thanks.

**Comment by pascalduez** [comment]
I guess I could use some explanations here.

I just ran into this: 
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAbzjAnmApnAYhCcC-ABQGZQQhwDkxulA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=react%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

`import { type Foo } from 'foo';`

get transpilled into:

`require('foo');` or `import 'foo';` depending of the config.

Which seems plain wrong to me.

While `import type { Foo } from 'foo';` get removed completely as expected.

**Comment by loganfsmyth** [comment]
@pascalduez 
```
import { type Foo } from 'foo';
```
means "import `foo`, and also get the type `Foo` from it.", whereas
```
import type { Foo } from 'foo';
```
means "import types from `foo`, and get `Foo`".

Only statements that strictly limited to _only_ types, e.g. `import type ...` are guaranteed to not have side-effects and can be safely removed.

For example
```
import { type Foo } from 'foo';
```
could expand to
```
import { someValue, type Foo } from 'foo';
```
which imports a real value from `foo` meaning that the `foo` file has to be executed. Given that, it would be very weird if adding/removing `someValue,` changed whether or not the `foo` module was executed or not.

**Comment by pascalduez** [comment]
@loganfsmyth Thanks a bunch for the explanations, it all makes sense now :) 
I was getting a bit worried.
