### ISSUE TITLE
Self-redefining helpers broken

### ISSUE THREAD

**Issue by Andarist** [babel/babel#6315]
**bug report**

`typeof` and `extends` helpers are designed at the moment in a way that they should redefine themselves (assign to their name's identifier) within their body during first call. This is broken at the moment, because somehow local variable declaration is added in their body (with the same identifier in declarator)

### Input Code
Anything using object spread transform.

### Babel Configuration (.babelrc, package.json, cli command)
latest babel beta, using latest rollup + appropriate plugin and external-helpers

### Expected Behavior
They should redefine themselves.

### Current Behavior
Can be observed in [this commit](https://github.com/redux-saga/redux-saga/blob/1bba77af2fefae9b722ac9adf3c847a61d88df3b/dist/redux-saga.js#L64 
). Whole configuration can be also easily checked.

cc @loganfsmyth

**Comment by Andarist** [comment]
Probably [rollup's plugin](https://github.com/rollup/rollup-plugin-babel/blob/a5f16de276c9a55bf6989797c2d6cda46201d5ed/src/index.js#L50) issue. Gonna head there with a fix

**Comment by Andarist** [comment]
Part of the fix in babel has landed already, closing this in favor of keeping only rollup's PR open.

**Comment by worc** [comment]
landed where?

**Comment by Andarist** [comment]
@worc, yeah - the issue was about babel 7 beta. It's fixed in babel already, we need still to land https://github.com/rollup/rollup-plugin-babel/pull/170 though. It's usable if you are using npm5 and specify `rollup-plugin-babel` dep as:
```
"rollup-plugin-babel": "rollup/rollup-plugin-babel#fix/external-helpers-babel-7"
```
