### ISSUE TITLE
Optimize computed properties in spec mode in object literals

### ISSUE THREAD

**Issue by Andarist** [babel/babel#6316]
**feature request**

### Input Code
```js
foo = {
  [bar]: "foobar"
};
```

### Babel Configuration (.babelrc, package.json, cli command)
latest babel@beta
using standard `babel-preset-env` configuration

### Expected Behavior
What gets outputted in `loose` mode:
```js
var _foo;

foo = (_foo = {}, _foo[bar] = "foobar", _foo);
```

### Current Behavior
```js
foo = babelHelpers.defineProperty({}, bar, "foobar");
```

### Possible Solution
Detect being in object literal and do what loose transform would do (probably just call it instead of the `spec` callback)

**Comment by jridgewell** [comment]
Can't, due to setters on `Object.prototype`. This shouldn't log anything:

```js
Object.defineProperty(Object.prototype, 'foo', { set(v) { console.log('foo setter'); } });
Object.defineProperty(Object.prototype, 'bar', { set(v) { console.log('bar setter'); } });

const obj = {
  foo: 1,
  ['bar']: 2,
};
