### ISSUE TITLE
Babel 7.0.0 beta 2 removed babel-node

### ISSUE THREAD

**Issue by dnalborczyk** [babel/babel#6319]
Babel 7.0.0 beta 2 removed babel-node with this commit: https://github.com/babel/babel/commit/2374062bbdfe8815892d64bd797298805db8b150

I was wondering what is the recommended way to achieve the same functionality going forward? babel-register?

**Comment by existentialism** [comment]
@dnalborczyk it's been moved to [its own package](https://github.com/babel/babel/tree/master/packages/babel-node)

https://unpkg.com/babel-node@7.0.0-beta.2/

**Comment by dnalborczyk** [comment]
thank you @existentialism !
