### ISSUE TITLE
taggedTemplateLiterals prevent tree shaking

### ISSUE THREAD

**Issue by brikou** [babel/babel#6324]
Choose one: is this a bug report or feature request?

I don't know if bug or feature (maybe both)

when using taggedTemplateLiteral with css fe. the generated code is not tree shakable anymore by webpack. When not imported, the transformed code is visible in source. With 1000's of css export it is a big problem.

### Input Code

```js
export const active = css`.active { color: red; }`;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["env"]
}
```

### Possible Solution

If I replace my var export by a function, the shim should be within the function (and not on top). Not perferct solution but a workaround for now. 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26
| node             | 8.5
| npm              | 5.4.2
| Operating System | linux

**Comment by Andarist** [comment]
Hi @brikou. We have started adding `#__PURE__` annotations for cases like that which will help with the dead code elimination story. This one is already on my list which I'd like to have annotated, gonna create a PR for this in following days - keep in mind that this will be babel7 feature and won't be back-ported to babel6 branch.

**Comment by Andarist** [comment]
If you use UglifyJS you can also leverage `pure_funcs` setting to achieve your goal
