### ISSUE TITLE
Strange destructive assignment operator behavior

### ISSUE THREAD

**Issue by 6graNik** [babel/babel#6329]
I want to **Report Bug**
I don't really know is bug on your side or not, or may be it is not event real bug;

In this case the parser will fail trying to work through this code. Lower you can see side by side es6 vs transpiled es5 on babeljs.io 
```js
const product = {
  countersByWeek: 12
}
    
let countersByWeek = []
let countersByMonth = []
    
({ countersByWeek, countersByMonth } = product) 

console.log(countersByWeek)
```

![image](https://user-images.githubusercontent.com/6370221/30957410-c48987e6-a442-11e7-9aa9-69b858a71cd9.png)

So we can fix this error by just adding semicolon at the end of `let countersByMonth` statement or wrapping assignment this some block, two examples below

![image](https://user-images.githubusercontent.com/6370221/30957516-29a40b9c-a443-11e7-856e-083450c21ef2.png)

![image](https://user-images.githubusercontent.com/6370221/30957526-327e5646-a443-11e7-8f81-a44387843a1a.png)

Again dosen't really know is that an issue in general, but seems like strange and unpredictable behavior.

**Comment by nicolo-ribaudo** [comment]
That code is a function invocation: you are calling `{}` as a function.
You should always use a semicolon when the line starts with (, [, + or - to prevent this kind of surprising errors.

**Comment by Andarist** [comment]
@6graNik Note that you can use [`eslnt`](https://github.com/eslint/eslint) to warn you against such erros or you can use [`prettier`](https://github.com/prettier/prettier) to have your code formatted consistently and when its used with `--no-semi` option it will protect you against such errors by inserting `;` at the start of possibly problematic line
