### ISSUE TITLE
convert isNaN(value) to value === NaN

### ISSUE THREAD

**Issue by RyukiKaneko** [babel/babel#6336]
find bug
there is defference result from expective result

isNaN(NaN) => true
NaN === NaN => false

please confirm

**Comment by loganfsmyth** [comment]
That is expected. `NaN` means "a totally unknown result" essentially, so even though both are unknown, one unknown is not the same as another unknown. You might also consider using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is if you want `0 !== -0`.

**Comment by nicolo-ribaudo** [comment]
Yes, `isNaN`and `=== NaN` are different.
Babel doesn't covert `isNaN(x)` to `x === NaN`, so I don't understand what the issue is about. If Babel does covert it, please show your `.babelrc` and `package.json` files.

**Comment by nicolo-ribaudo** [comment]
Too slow 😆
