### ISSUE TITLE
Babel-cli not install

### ISSUE THREAD

**Issue by ednx** [babel/babel#6339]
Choose one: Hi Babel-cli not install 

### Input Code

```js
npm install --save-dev babel-cli
 Error: EPERM: operation not permitted, unlink 'C:\InnovaFrontEnd\Termontasajero\prueba\node_modules\fsevents\node_modules\aws-sign2\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\InnovaFrontEnd\Termontasajero\prueba\node_modules\fsevents\node_modules\aws-sign2\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\InnovaFrontEnd\\Termontasajero\\prueba\\node_modules\\fsevents\\node_modules\\aws-sign2\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\InnovaFrontEnd\\Termontasajero\\prueba\\node_modules\\fsevents\\node_modules\\aws-sign2\\package.json' }
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["env"]
}

```

### Context
Any idea why I can not install babel-cli

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6
| node             | 8.4.0
| npm              | 5.4.1
| Operating System | Window 10

**Comment by yavorsky** [comment]
@ednx Hi! Have you checked https://github.com/npm/npm/issues/18380 ?

**Comment by hzoo** [comment]
If it's simply an install issue then it shouldn't be an issue with Babel since we aren't releasing 6.x, and doing 7.x betas so not a regression from a release at least
