### ISSUE TITLE
Incorrect renaming of variables in object destructuring assignment.

### ISSUE THREAD

**Issue by oliverchang** [babel/babel#6344]
Choose one: is this a bug report or feature request? Bug report

### Input Code

```js
'use strict';

const babelGenerator = require('babel-generator').default;
const babelTraverse = require('babel-traverse').default;
const babylon = require('babylon');

var ast = babylon.parse(`

var {a, b} = {a: 1, b: 2}

`);

var cur = 0;

babelTraverse(ast, {
  Scope(path) {
    for (let [name, binding] of Object.entries(path.scope.bindings)) {
      path.scope.rename(name, 'v' + cur++);
    }
  }
});

console.log(babelGenerator(ast).code);
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
 "dependencies": {
    "babel-generator": "^7.0.0-beta.2",
    "babel-template": "^7.0.0-beta.2",
    "babel-traverse": "^7.0.0-beta.2",
    "babel-types": "^7.0.0-beta.2",
    "babylon": "^7.0.0-beta.25",
  }

```

### Expected Behavior

The expected output is something like:

```js
var {
  v0,
  v1
} = {
  v0: 1,
  v1: 2
};
```

### Current Behavior

Instead I see:

```js
var {
  a: v0,
  b: v1
} = {
  a: 1,
  b: 2
};
```

This seems to still work as intended in that v0 and v1 both get the expected values (1 and 2), but the expected output makes a lot more sense.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.2
| node             | v8.5.0
| npm              | 5.3.0
| Operating System | Linux

**Comment by nicolo-ribaudo** [comment]
`Scope#rename()` only renames the variable and its references, without transforming anything else.
If you want to rename also the object keys, which are not related to the variable name, you should do it manually using `objectKeyPath.replaceWith`.
