### ISSUE TITLE
Internal: remove inlined plugin from Babel's .babelrc

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6346]
Just need to remove the lines in 

https://github.com/babel/babel/blob/9418945a1f3a8a1fafaacde00bce4ec4c866c5e5/.babelrc.js#L9-L26

Basically I had a bug and updated Babel itself, so needed a temporary workaround. Because it's fixed, we can remove this (now unnecessary) code.

I guess you could just do this change in github as well, should be ok if tests pass.

- Please only work on this if you are new to contributing to babel/open source (thanks 😄 )!
- Comment below you are working on this!
- Read our [contributing.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) guide!

**Comment by xjlim** [comment]
@hzoo I can work on this
