### ISSUE TITLE
[BUG] babel-node does not transform TypeScript source.

### ISSUE THREAD

**Issue by alloy** [babel/babel#6353]
As the title says, currently babel-node does not appear to transform TypeScript source. I did not find any CLI options related to this either, so expected it to work out of the box.

cc @andy-ms 

### Input Code

```ts
interface SomeTSInterface {
  foo: string
}

const x: SomeTSInterface = { foo: "bar" }
console.log(x.foo)
```

### Babel Configuration (.babelrc, package.json, cli command)

```
~/t/babel-7 » node --version
v8.4.0
```

```
~/t/babel-7 » ./node_modules/.bin/babel --version
7.0.0-beta.2 (babel-core 7.0.0-beta.2)
```

```
~/t/babel-7 » ./node_modules/.bin/babel-node --version
7.0.0-beta.2
```

### Expected Behavior

```
~/t/babel-7 » ./node_modules/.bin/babel --presets typescript index.ts 
const x = {
  foo: "bar"
};
console.log(x.foo);
```

```
~/t/babel-7 » ./node_modules/.bin/babel --presets typescript index.ts | node
bar
```

### Current Behavior

```
~/t/babel-7 » ./node_modules/.bin/babel-node --presets typescript index.ts 
/Users/eloy/tmp/babel-7/index.ts:1
(function (exports, require, module, __filename, __dirname) { interface SomeTSInterface {
                                                                        ^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Module._extensions..js (module.js:584:10)
    at Object.newLoader [as .js] (/Users/eloy/tmp/babel-7/node_modules/pirates/lib/index.js:93:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at Object.<anonymous> (/Users/eloy/tmp/babel-7/node_modules/babel-node/lib/_babel-node.js:156:22)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.2
| node             | 8.4.0
| npm              | 5.3.0
| Operating System | Mac OS X 10.12.5

**Comment by andy-ms** [comment]
You need to specify `--extensions ".ts"`.
There was a PR adding these at #6027, but there was concern specifically that it would change the default behavior of `babel-register` (used by `babel-node`).

**Comment by alloy** [comment]
Aha, thanks for pointing me to that 👍

**Comment by hzoo** [comment]
Can't make some doc changes in various places if that helps?
 https://github.com/babel/babel/pull/6365/files

**Comment by alloy** [comment]
Documentation is obviously good for when there’s really no other option, but [I do think](https://github.com/babel/babel/pull/6027#issuecomment-333657409) that in my case it’s reasonable to expect that I want Babel to process my TS sources.
