### ISSUE TITLE
Use of this.constructor inside ES6 class constructor fails

### ISSUE THREAD

**Issue by leftmostcat** [babel/babel#6360]
Choose one: is this a bug report or feature request?

### Input Code

From https://github.com/bookbrainz/bookbrainz-site/blob/061d62f97d13d33d3e745b378b62c34b04234c7f/src/client/components/pages/error.js

```js
export class SiteError extends Error {
	constructor(message) {
		super();

		// We can't access the subclass's default message before calling super,
		// so we set it manually here
		this.message = message || this.constructor.defaultMessage;

		this.name = this.constructor.name;
		this.status = this.constructor.status;
	}

	static get defaultMessage() {
		return 'An unhandled error occurred';
	}

	static get status() {
		return status.INTERNAL_SERVER_ERROR;
	}
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    "lodash",
    "transform-es2015-modules-commonjs",
    "transform-object-rest-spread",
    "transform-class-properties",
    "array-includes",
    [
        "transform-runtime", {
            "polyfill": false,
            "regenerator": true
        }
    ]
  ],
  "presets": [
	  "flow",
	  "es2015",
	  "es2016",
	  "es2017",
	  "react"
  ]
}
```

### Expected Behavior

`this.constructor` in the above snippet should reference `SiteError`, and `const err = new SiteError()` should result in an error with `err.message = "An unhandled error occurred"`, etc.

### Current Behavior

When run through babel-preset-es2015, `this.constructor` in the above snippet references `Error` (and continues to do so for derived classes) and `const err = new SiteError()` results in an error with `err.message = undefined`.

### Context

When run directly in recent enough node or desktop browsers, the above code produces the expected result of statically accessing the appropriate derived class and setting message, status code, etc. This is used by HTTP handlers to appropriate set response status code and provide a useful error message.

| software         | version(s)
| ---------------- | -------
| Babel            | 6.24.1
| node             | 6.11.3
| npm              | 3.10.10
| Operating System | Linux 4.12.13, Fedora 26

**Comment by nicolo-ribaudo** [comment]
You can look for a solution in https://github.com/babel/babel/issues/4480
