### ISSUE TITLE
[BUG] Babel 7 with es2015 preset incorrectly destructures from imported module.

### ISSUE THREAD

**Issue by alloy** [babel/babel#6373]
### Input Code

Cloneable/runnable example can be found [here](https://github.com/alloy/babel-7-destructuring-imported-variable-bug).

Given a module that exports an object:

```js
export const NestedObjects = {
  Foo: "whatevs",
  Bar: "whatevs",
}
```

And a module that imports the object and then destructures it into multiple objects:

```js
import { NestedObjects } from "./some-module"
const { Foo, Bar } = NestedObjects
```

### Babel Configuration

```js
{
  "presets": ["es2015"]
}
```

### Expected Behavior

I would expect both `Foo` and `Bar` to be taken from `_someModule.NestedObjects`.
### Current Behavior

Only the first destructured object is resolved correctly `_someModule.NestedObjects.Foo`, the following object loses the module reference `NestedObjects.Bar`.

### Possible Solution

I have not had the time yet to drill it down to the specific plugin in the `es2015` preset that causes this, so that should probably be the first avenue to explore. I will update this ticket if I do find time to debug more before someone else has had the opportunity to do so.

### Context

Our React Native project tries to use [this library](https://github.com/getsentry/react-native-sentry/blob/9001c5c0dc9314a264650704b90141a50fe5e999/lib/Sentry.js#L1-L2), which currently fails the build.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.2
| node             | 8.4.0
| npm              | 5.3.0
| Operating System | Mac OS X 10.12.5

**Comment by orta** [comment]
Nice response @babel-bot , I should steal this and get it on CocoaPods' peril.

**Comment by hzoo** [comment]
[REPL on master](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAbzgOQKYGcaoCYHkBGAVqgMYzpwC-cAZlBCHAEQB0A9Og6gLQgTYBXADaomAKBIQAdpkRwAYhAgAaOACEAhlCpwAvCgxY8RUuSA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015&targets=&version=7.0.0-beta.2)

<img width="991" alt="screen shot 2017-10-03 at 9 29 32 am" src="https://user-images.githubusercontent.com/588473/31127586-6a9da670-a81d-11e7-9485-95b4655b8f1e.png">
