### ISSUE TITLE
Centralize each plugin's option processing to the top of the function.

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6376]
As of https://github.com/babel/babel/pull/6350, plugins have changes from

```
module.exports = function(babel){
```
to
```
module.exports = function(babel, options){
```

Now that the options are easily accessible in the top-level scope, alongside the old `this.opts` and `state.opts` methods, it would help readability and validation if we move the accesses to these options to the top of the plugin functions.

In some places the references are already nicely grouped, like https://github.com/babel/babel/blob/91cde0148d16afe9f9192953084f0b668885cdf4/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js#L93

so they are easy to move.

Some places they are generally scattered around the plugins, like in https://github.com/babel/babel/blob/91cde0148d16afe9f9192953084f0b668885cdf4/packages/babel-plugin-transform-runtime/src/index.js#L111

Once everything is centralized at the top, we can start adding validation for the config values to give better feedback to users if they pass unknown options or invalid values for the options. That said, it is up to whoever takes this on for whether they want to tackle the validation too.

**Comment by nveenjain** [comment]
Is there any way, i can help with the issue, i know that it has PR, but can i be of any help there?

**Comment by hzoo** [comment]
@nveenjain yeah for sure! you can help review the PR or just try to make a branch yourself to compare if you want to learn it yourself (although we may not merge it specifically)
