### ISSUE TITLE
Modules transforms incorrectly rewrites array reference in transpiled for-of loop

### ISSUE THREAD

**Issue by MattiasBuelens** [babel/babel#6378]
When using the (unofficial) [babel-plugin-transform-for-of-as-array](https://github.com/jridgewell/babel-plugin-transform-for-of-as-array) on a `for..of` loop that iterates over an imported array variable, the AMD (and CommonJS) modules transform fail to rewrite all of the array references.

Repro: https://github.com/MattiasBuelens/babel-for-of-modules-regression

### Input Code
```js
import {array} from 'foo';

for (let elem of array) {
    console.log(elem);
}
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
  "plugins": [
    "transform-for-of-as-array",
    "transform-es2015-modules-amd"
  ]
}
```

### Expected Behavior
Babel version 7.0.0-beta.0 generates this code:
```js
define(["foo"], function (_foo) {
  "use strict";

  for (let _i = 0; _i < _foo.array.length; _i++) {
    let elem = _foo.array[_i];
    console.log(elem);
  }
});
```

### Current Behavior
Babel version 7.0.0-beta.2 generates this code instead:
```js
define(["foo"], function (_foo) {
  "use strict";

  for (let _i = 0; _i < _foo.array.length; _i++) {
    let elem = array[_i];
    console.log(elem);
  }
});
```
Note the `let elem = array[_i];` inside the loop.

The same problem also occurs with the CommonJS modules transform, which generates:
```js
"use strict";

var _foo = require("foo");

for (let _i = 0; _i < _foo.array.length; _i++) {
  let elem = array[_i];
  console.log(elem);
}
```

### Context
Our code base only uses `for..of` on arrays (or array-like objects), so we'd like to keep using the optimized transformation provided by this unofficial plugin.

I've tried to reproduce this issue with the standard `for..of` transform, but that plugin always creates a temporarily variable for the imported array.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.2
| node             | 7.10.0
| npm              | 5.4.2
| Operating System | Windows 10

**Comment by nicolo-ribaudo** [comment]
@Andarist Is this fixed by https://github.com/babel/babel/pull/6374?

**Comment by Andarist** [comment]
Dont think so, the fix there is directly in the destructuring plugin, so it shouldnt fix this one.

I suspect the underlaying issue is the same - reusing node and thus interfering with cache optimization in module helper.

I can track this one too, once i get home

**Comment by MattiasBuelens** [comment]
#6374 is indeed very interesting. Simply changing [line 16 in the `for-of-as-array` transform](https://github.com/jridgewell/babel-plugin-transform-for-of-as-array/blob/fd2b1482d433d46d45e5b25fed5aa4ea14fd45e7/src/index.js#L16) from this:
```js
const item = t.memberExpression(array, i, true);
```
to this:
```js
const item = t.memberExpression(t.clone(array), i, true);
```
already solves this particular problem.

Would this be a correct fix for the plugin? When exactly should a plugin need to use `t.clone`?

**Comment by nicolo-ribaudo** [comment]
A node should never be used twice, so you should always clone it when it is duplicated.
If the node is nor an identifier nor a literal, the correct function to clone it correctly is `t.deepClone`.

**Comment by Andarist** [comment]
@MattiasBuelens this is a correct fix. The issue got introduced by recent improve caching. Probably the plugin has reused `array` node and when `babel-helper-module-transforms` got into rewriting live bindings (what u have imported) it has marked this node as seen in its [`ReferencedIdentifier visitor`](https://github.com/babel/babel/blob/68182bd69fe7b6f3d1deac0efb16fc6ff9098363/packages/babel-helper-module-transforms/src/rewrite-live-references.js#L166), so when it met it again it recognized it as already rewritten and skipped the rewritting.

Nodes inserted in AST should be unique and not re-used for exactly such reasons.

**Comment by hzoo** [comment]
We should note that in the upgrade docs for tool authors since it may happen a lot

**Comment by MattiasBuelens** [comment]
Thanks for the help! I'll open a pull request in `babel-plugin-transform-for-of-as-array` to get this fixed. :)

**Comment by hzoo** [comment]
Funny since @jridgewell made that plugin..

**Comment by jridgewell** [comment]
What'd I do?

**Comment by jridgewell** [comment]
Oh yah, but that was way before I realized there was an issue with reusing nodes.
