### ISSUE TITLE
babel-preset-typescript doesn't work

### ISSUE THREAD

**Issue by nojvek** [babel/babel#6392]
Followed the documentation at: https://www.npmjs.com/package/babel-preset-typescript

Getting this error:
```
node node_modules/babel-cli/bin/babel --presets typescript src/models/result.ts
Error: You gave us a visitor for the node type "TSDeclareFunction" but it's not a valid type (While processing preset: "/Users/nojvek/mp/insights/node_modules/babel-preset-typescript/lib/index.js")
    at verify (/Users/nojvek/mp/insights/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Function.explode (/Users/nojvek/mp/insights/node_modules/babel-traverse/lib/visitors.js:72:3)
    at Plugin.normaliseVisitor (/Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:155:29)
    at new Plugin (/Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:66:27)
    at Function.memoisePluginContainer (/Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:119:21)
    at Function.normalisePlugin (/Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/nojvek/mp/insights/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
```

```
    "babel-cli": "6.10.1",
    "babel-core": "6.3.17",
    "babel-eslint": "6.0.2",
    "babel-loader": "6.2.0",
    "babel-plugin-syntax-async-functions": "6.13.0",
    "babel-plugin-transform-regenerator": "6.22.0",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-typescript": "^7.0.0-alpha.19",
```

End goal is to get this working with webpack with babel-loader.

**Comment by nojvek** [comment]
@andy-ms  @hzoo

**Comment by existentialism** [comment]
@nojvek thanks for the issue! You'll need to upgrade all your babel deps to the latest betas to match `babel-preset-typescript`, as it depends on some changes in our parser.

(p.s. no need to ping, the team will respond asap!)

**Comment by hzoo** [comment]
Would appreciate it if you provided the source for the error?

However I see it's because you are using the typescript preset when everything else is Babel 6. It's using some APIs only in Babel 7 so you just need to update everything else as well.

I would change everything to `7.0.0-beta.2` (eslint/loader are different)

**Comment by plmrry** [comment]
I'm getting:
```bash
You gave us a visitor for the node type "TSDeclareFunction" but it's not a valid type
```
Using:
```json
"babel-cli": "7.0.0-beta.2",
"babel-preset-typescript": "7.0.0-beta.2",
```

**Comment by hzoo** [comment]
I would clear node_modules and make sure you don't have any other plugins/deps that are using v6

**Comment by nojvek** [comment]
I made the following changes to the package.json

![image](https://user-images.githubusercontent.com/1018196/31249913-fbe12fec-a9cd-11e7-964d-51a2fd1125c6.png)

webpack.config

```
var BABEL_LOADER = `babel?presets[]=typescript`;

    loaders: [
      {
        test: /\.(js|ts)$/,
        loader: BABEL_LOADER,
      },
```

Although I still get an error like this.

```
ERROR in ./src/index.js
Module parse failed: /Users/nojvek/mp/insights/node_modules/babel-loader/lib/index.js?presets[]=typescript!/Users/nojvek/mp/insights/node_modules/eslint-loader/index.js!/Users/nojvek/mp/insights/src/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
```

**Comment by hzoo** [comment]
babel-loader can be `^7.1.2` and preset-typescript should also be `beta.2`

If you only run typescript loader it will probably fail for unknown syntax, you should still run with es2015?

**Comment by galenjiang** [comment]
@hzoo Does this preset only remove type syntax, but it does not run a ts language server for type checking?

**Comment by TrySound** [comment]
@galenjiang Yes. This is the only reason for new tool.

**Comment by hzoo** [comment]
It works the same as `babel-preset-flow`. You still need to run flow/ts separately.

**Comment by hzoo** [comment]
If you get that it's not a valid node type it's because some package is on v6.
If it still unexpected token it's probably because the syntax after stripping types is a proposal

Either way we don't have the code or a repro so going to close for now from inactivity, can link to a repo or something and we can help

**Comment by rodrigopivi** [comment]
I am experiencing this exact same problem.

```
    "babel-cli": "^7.0.0-beta.3",
    "babel-core": "^7.0.0-beta.3",
    "babel-loader": "^7.1.2",
    "babel-preset-typescript": "^7.0.0-alpha.20",
```

```
{
  "presets": ["typescript"]
}
```

**Comment by hzoo** [comment]
>  "babel-preset-typescript": "^7.0.0-alpha.20",

Can you make sure that the version are the same? They should all match (in this case beta.3). Also don't use `^` because each update can be breaking and incompatible with the previous

**Comment by rodrigopivi** [comment]
thanks for the quick reply. updated to test with this, still not working:
```
    "babel-cli": "7.0.0-beta.3",
    "babel-core": "7.0.0-beta.3",
    "babel-loader": "7.1.2",
    "babel-preset-typescript": "7.0.0-beta.3",
```
```
{
  "presets": ["typescript"]
}
```
Error:
```
You gave us a visitor for the node type "TSDeclareFunction" but it's not a valid type (While processing preset: "/XX/node_modules/babel-preset-typescript/lib/index.js")
```

**Comment by rodrigopivi** [comment]
just using babel works, i get the error with babel-cli

**Comment by nicolo-ribaudo** [comment]
Are you using a globally installed babel-cli? Does `./node_modules/.bin/babel ...` (instead of `babel ...`) work?

**Comment by rodrigopivi** [comment]
im using `npx babel-cli`, so i think now the problem is tsx, it compiles fine, but fails when there is a react tag. any workaround, typescript should have jsx support be default right?

**Comment by andy-ms** [comment]
No, they're separate plugins.

**Comment by nojvek** [comment]
Could someone post an actual example with all the npm modules required to
get typescript-babel working and playing nicely. A sample project as part
of documentation would help so many people.

**Comment by rodrigopivi** [comment]
ok after updating to:
```
    "babel-cli": "7.0.0-beta.3",
    "babel-core": "7.0.0-beta.3",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-react-jsx": "7.0.0-beta.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-typescript": "7.0.0-beta.3",
```

I get a new error at:
`https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/src/index.js#L5`

```
Uncaught TypeError: Cannot read property 'pragma' of undefined
    at _default (/Users/rodrigo/Trabajo/doc/doc.pe-server/node_modules/babel-plugin-transform-react-jsx/lib/index.js:14:23)
    at Function.memoisePluginContainer (/Users/rodrigo/Trabajo/doc/doc.pe-server/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
```

Any ideas?

**Comment by rodrigopivi** [comment]
i was able to get TS work with babel running directly on nodejs, but seems like the TS transpiling still has a lot of errors, so that i was unsuable atm for actual applications. Needed to also add "env" preset, and also plugins/presets for class transformations, decorators, spread operator and jsx.

At the end, i had problems related to exporting types, and also other ts parsing bugs, at the end i hit a wall with a `TODO` exception that seems like someone left something incomplete. Getting back to TSC for now.

**Comment by hzoo** [comment]
@rodrigopivi fyi the ts preset only strips types away like flow, it's expected that you need env and other plugins

**Comment by hzoo** [comment]
If you want help we need a minimal reproduction with code snippet and config, we can't guess how to fix it just from an error message

**Comment by rodrigopivi** [comment]
I´m sorry but i lost all the changes i did to my code to try to get it working, but one of the endpoints was this exception thrown:

`https://github.com/babel/babel/blob/830c527bb7873b29f671a3568b21b4a6af98ceda/packages/babel-traverse/src/path/conversion.js#L15`

This is valid Typescript, that got me an exception at work (so had to coment it out of my code):
```
export type ISomeType = <T>({ someParam, anotherParam }: IHaveSomeParams<T>) => Promise<T>;
```
I also posted some screenshots and the steps i went through at the Typescript channel on the babel slack. thanks for being so helpful.

**Comment by andy-ms** [comment]
@rodrigopivi babel/babylon#768
