### ISSUE TITLE
Select browsers based on particular feature support 

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6396]
---

Migrated from https://github.com/babel/babel-preset-env/issues/157
Originally created by @graingert on *Fri, 27 Jan 2017 08:51:43 GMT*

---
Eg all browsers that support async await,  would select Chrome or all browsers that support arrow functions, would select most modern browsers

**Comment by graingert** [comment]
@hzoo can we re-open this?

I'd like to be able to configure webpack+babel to generate two bundles, one for currently supported browsers that support native "import/export" and one for all currently supported browsers

**Comment by graingert** [comment]
I'd also like to be able to configure two babel configs, one for supported versions of node (to generate .js files), and one for supported versions of node that support ".mjs" (to generate .mjs files)
