### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6401]
---

Migrated from https://github.com/babel/babel-preset-env/issues/112
Originally created by @osenvosem on *Fri, 30 Dec 2016 07:10:07 GMT*

---
I use the latest Chrome 55, it supports generators. It works well if only I exclude `transform-generator` explicitly. With `useBuiltIns: true` I also got the issue. It seems to be a bug.

```js
// webpack.config.js
  module: {
    rules: [{
      test: /\.jsx?$/,
      include: SRC,
      loader: 'babel-loader',
      options: {
        "presets": [ "react",
          [ "env", {
            "targets": {
              "browsers": [ "last 2 versions" ]
            },
            //exclude: [ 'transform-regenerator' ],
            "modules": false
          }]
        ]
      }
    }]
  }
```
I suppose the preset should include `babel-plugin-transform-regenerator` if it needed, but it doesn't for some reason.

**Comment by zhouyu1993** [comment]
hello~

I first write `.bablerc` like this:

``` json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "> 1%",
            "last 3 versions",
            "ie >= 9",
            "ios >= 8",
            "android >= 4.2"
          ]
        },
        "useBuiltIns": "usage"
      }
    ],
    "stage-2"
  ]
}
```

And I don't add `import 'babel-polyfill'` in my entry file `app.js`.

It show the error `regeneratorRuntime is not defined`.

So I add `import 'babel-polyfill'` in my entry file `app.js`. It works.

But the file is big.

So I use the option like this:

``` json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "> 1%",
            "last 3 versions",
            "ie >= 9",
            "ios >= 8",
            "android >= 4.2"
          ]
        },
        "useBuiltIns": false
      }
    ],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

It don't need to add `import 'babel-polyfill'` in my entry file `app.js`. And the file is smaller.

I guess that the option `useBuiltIns` is something wrong.
