### ISSUE TITLE
Promise seems to be polyfilled in environments that support promises

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6405]
---

Migrated from https://github.com/babel/babel-preset-env/issues/105
Originally created by @matthewmueller on *Sun, 18 Dec 2016 23:55:13 GMT*

---
Just messing around with the new polyfill stuff, but not sure it's working for promises. Here's my `.babelrc`:

```json5
{
  "presets": [
    [ "env", { loose: true, modules: false, useBuiltins: true, targets: { chrome: 55 } } ],
    [ "react" ]
  ],
  "plugins": [
    "transform-runtime",
    "transform-class-properties",
    ["transform-react-jsx", { "pragma": "h" }]
  ]
}
```

Here's my file:

```js
export default class Callout extends Component {

  construct () {
    new Promise((reject, resolve) => {
      resolve('hi!')
    })
  }

  render () {
    return (
      <div>hello world!</div>
    )
  }
}
```

And here's my output (from `babel index.js`):

```js
import _Promise from 'babel-runtime/core-js/promise';

export default class Callout extends Component {

  construct() {
    new _Promise((reject, resolve) => {
      resolve('hi!');
    });
  }

  render() {
    return h(
      'div',
      null,
      'hello world!'
    );
  }
}
```

Based on the data, Promises have been supported since chrome 51. 

It's doing something though, because it's not polyfilling classes, and if I change it to `{ ie: 8 }`, it'll include a bunch more deps.

**Comment by g0t4** [comment]
FYI comments from the original issue (https://github.com/babel/babel-preset-env/issues/105) are missing here.
