### ISSUE TITLE
Dont work arrow function in class and transform-do-expressions

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6426]
---

Migrated from https://github.com/babel/babel-preset-env/issues/217
Originally created by @khotey on *Sat, 18 Mar 2017 16:36:24 GMT*

---
I have class:
```
class App extends Component {

  setName = () => {
    this.props.setName('Test')
  };

  render() {
    return (
      <div onClick={this.setName}>
        <h1>Wolcome to React</h1>
        <p>
          Test <b>HRM</b>. {this.props.user.name}
        </p>
      </div>
    )
  }
}
```

Webpack modules config:
```
module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use:[
          { loader: 'babel-loader' },
          { loader: 'eslint-loader' }
        ]
      }
    ]
  }
```

.babelrc:
```
{
  "presets": [
    "env",
    "stage-2",
    "stage-0",
    "react",
  ],
  "plugins": ["react-hot-loader/babel"]
}
```

When build scripts I have error:
  `8:11  error  Parsing error: Unexpected token =`
And the same problem with bind(transform-do-expressions), If I use `onClick={e => ::this.someAction}` construction have error: `Parsing error: Unexpected token :`

Сan I have not properly configured the Babel?

**Comment by toddhay** [comment]
What was your solution for resolving this as I'm seeing the same error?  Thank you.
