### ISSUE TITLE
useBuiltIns: figure out how to remove polyfills that aren't actually used in the codebase

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6431]
---

Migrated from https://github.com/babel/babel-preset-env/issues/84
Originally created by @hzoo on *Mon, 12 Dec 2016 17:04:39 GMT*

---
### Don't include if supported environments support it natively #20
- Use preset-env config to determine what parts of core-js to pull in (original PR, #55)

```js
import "babel-polyfill";
```

gets transformed to

```js
import "core-js/modules/es6.map";
import "regenerator-runtime/runtime";
...
```

### Don't include if you have blacklisted it yourself (regenerator for example) #60
- Be able to blacklist transforms or specific builtIns? 

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      },
      "blacklist": [
        "transform-regenerator" // won't include "regenerator-runtime/runtime"
      ]
    }]
  ]
}
```

---

### Don't include if the codebase doesn't actually use the builtIn (this)

> this would need to be a whole codebase transformation so it probably won't work in this preset/plugin

The problem with the first heading ^ is that even if you remove the polyfills supported natively in the environment, you might not actually use them in your codebase anyway.

Possible solution: run an analyzer (separate babel pass like [transform-runtime](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime)) on the whole codebase and remove imports that aren't used anywhere.

EDIT: A big problem atm is that Babel runs per file. So unless we understand the whole codebase it sounds like something webpack could do? cc @TheLarkInn @keyanzhang

**Comment by chrisdothtml** [comment]
> EDIT: A big problem atm is that Babel runs per file. So unless we understand the whole codebase it sounds like something webpack could do?

Not sure what the status of this effort is, but this is definitely a big problem when using babel with webpack. For example, if I have 6 files that get transformed to replace `Object.assign` with the `_extends` polyfill, all 6 of those files will have the polyfill in them.

This is the perfect opportunity for a complimentary webpack babel **plugin** that has access to the webpack babel **loader** information and swoops in to dedupe across all the files.

I've come across a few webpack babel plugins that say they're meant to dedupe/minimize babel output, but I haven't found one that actually does it well.

**Comment by Andarist** [comment]
@chrisdothtml you can brainstorm with others in the new open thread about this - https://github.com/babel/babel/issues/6328
