### ISSUE TITLE
Import transform not listed in REPL Debug output

### ISSUE THREAD

**Issue by qm3ster** [babel/babel#6441]
This is a bug report

### Input Code
[REPL Link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=true&code_lz=JYWwDg9gTgLgBAbwIIF84DMoRHA5AOgHoBDfAKwGdcg&debug=true&circleciRepo=&evaluate=true&lineWrap=true&presets=env&targets=&version=6.26.0
)
```js
import {Wow} from './tada.js'
```

### Babel Configuration (.babelrc, package.json, cli command)

**Enable "Debug" checkbox (currently not serialized in link)**

Default `env` preset from placeholder
```js
{
  "env": "> 2%, ie 11, safari > 9"
}
```

### Expected Behavior
Listing all transforms used

### Current Behavior
Not listing `transform-es2015-modules-commonjs` (?) or whatever else is transforming the import statement
While outputting
```js
'use strict';

var _tada = require('./tada.js');
```

**Comment by existentialism** [comment]
@babel-bot move to babel/website

**Comment by xtuc** [comment]
Since it has been moved https://github.com/babel/website/issues/1412, i'm going to close this. Thanks @existentialism
