### ISSUE TITLE
file compiled with babel-cli throws an error

### ISSUE THREAD

**Issue by Kreha6** [babel/babel#6444]
I'm compiling my client side using webpack with env, stage-0 and react presets. It was working just fine but now I started working on server-side rendering, so I had to use some es6 and jsx syntax in my server file. I'm compiling it using exact same presets as in webpack, but after running compiled file it throws me an error in one of client files that are being imported inside server file. Here is my packege.json so you could see my command: [GitHub](https://github.com/Kreha6/ReactBookstore/blob/ssr/package.json)
 (look for "build:s" command)

The error I'm getting is in attached image
![bez tytulu](https://user-images.githubusercontent.com/20362919/31318016-60c82198-ac4b-11e7-8009-57c9e158f75e.png)

**Comment by loganfsmyth** [comment]
I responded here https://stackoverflow.com/questions/46632151/file-compiled-using-babel-cli-throws-an-error/46632702#46632702
