### ISSUE TITLE
Calling super methods doesn't always work, if method is missing in the proto chain.

### ISSUE THREAD

**Issue by trusktr** [babel/babel#6446]
Unfortunately, this [simple example](http://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8BQ1rAPYDsIBcBOArsDungBQCUiKq0OAFgJYQB0jmjOlNAvje50rVaaLBHQgApixDoA5mQDksNhxyKKvJHyShIMAELRJADxyTMAExjxkOvVGgBhY2YvXoR5KgFcq32ggCAAdJPFVBTREMbAlpWQVFJwj1KOg-HUxJAHdnIA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0) it works.

But my code base is much more complicated: all the classes are class-factory mixins. If I leave out a method on one of the classes, which may be mixed in any order, then when the call stack reaches a prototype that doesn't not have the called method, I get an error like:

```
Uncaught TypeError: Cannot read property 'call' of undefined
```

The line on which this happens is transpiled to look like this:

```js
                (ref = _get(Observable.prototype.__proto__ || _Object$getPrototypeOf(Observable.prototype), 'init', this)).call.apply(ref, [ this ].concat( args ));
```

The problem is that the `_get()` function is failing to traverse the prototype to find a more-parent `init` method.

I am 100% sure that this is the case, but I'm not able to provide a reproduction yet.

If I simply add the missing method to the intermediate class, then it works:

```
function SomeClassMixin(Base) {
  class SomeClass extends Base {
    init() { super.init() } // this unnecessary place holder makes it work.
  }
}
```

Let me see if I can post back with a repro...

**Comment by loganfsmyth** [comment]
If we don't have a repro case I definitely can't see us keeping this open, so that'd definitely critical to get.

**Comment by trusktr** [comment]
@loganfsmyth I've got the tab open, will post a repro soon!

**Comment by jridgewell** [comment]
Ping.

**Comment by trusktr** [comment]
Alright, here's a repro. [This branch](https://github.com/trusktr/infamous/tree/babel-issue-6446-working) works and [this one](https://github.com/trusktr/infamous/tree/babel-issue-6446-not-working) doesn't.

To run, check out one of the branches, and

```
npm i
npm run build-global
```

which outputs `global.js` in the root of the project (compiled with Babel). Then open `test.html` in your browser; it should work statically, but you can use optionally `http-server` or similar.

**Comment by trusktr** [comment]
I should mention that the lines changed from working to not-working are [in `src/html/HTMLNode.js`](https://github.com/trusktr/infamous/commit/04a2ac340c14a7edcbeb036ebcbe96b545f15cfe).

**Comment by loganfsmyth** [comment]
Potentially the useful link is https://github.com/trusktr/infamous/compare/babel-issue-6446-working...babel-issue-6446-not-working

This doesn't appear to be a Babel issue. Stepping through your code shows that the `.construct` value is set to `undefined` by your own code in https://github.com/trusktr/infamous/blob/04a2ac340c14a7edcbeb036ebcbe96b545f15cfe/src/html/DeclarativeBase.js#L336 which does indeed seem to do just that. https://github.com/trusktr/infamous/blob/04a2ac340c14a7edcbeb036ebcbe96b545f15cfe/src/html/DeclarativeBase.js#L390 runs even if there are no getters or setters added unto the object and

```
var o = {};
Object.defineProperty(o, 'prop', {});
```
is essentially
```
o.prop = undefined;
```

**Comment by trusktr** [comment]
@loganfsmyth Ah, thanks, and sorry for wasting your time! I knew that blacklist was going to bite me at some point. I've been meaning to change to an explicit whitelist. I guess now's the time!
