### ISSUE TITLE
Add new pragma to transform-es2015-modules

### ISSUE THREAD

**Issue by DrewML** [babel/babel#6449]
![image](https://user-images.githubusercontent.com/5233399/31345486-820f56e2-acdb-11e7-8fa8-10a458658a5a.png)

**Open Question**: Should we make this default behavior, or put it behind a flag? If it is indeed on its way to being a part of node core, it makes sense to just make it default to `on`.

**Comment by bmeck** [comment]
You should be able to validate stuff against https://github.com/bmeck/node/tree/named-export-core , but I need time to cleanup/write tests/write docs.

**Comment by jridgewell** [comment]
What is this being used for?

**Comment by bmeck** [comment]
@jridgewell it is a way for CJS to declare the shape they represent before evaluation/instantiation. This would allow Node to create named exports from CJS, which is not possible to do if it requires evaluation to know the list of exports.

**Comment by benjamn** [comment]
Why does ESM need to know the shape of CJS module exports? The `exports` object is canonical in CJS, so an `import` declaration in some other ESM module should just access properties of that `exports` object, without knowing anything about its shape. I'm sure I'm missing something, but this proposal seems headed in a bizarre direction.

**Comment by styfle** [comment]
I suspect it’s the way ESM imports fail. I believe the import statement should throw if the named export was not found rather that return ‘undefined’ and throw unexpectedly at first usage of that variable.

**Comment by bmeck** [comment]
@benjamn 

> Why does ESM need to know the shape of CJS module exports?

In order to create a Module Record and link it in ESM graph prior to evaluation.


> The exports object is canonical in CJS, so an import declaration in some other ESM module should just access properties of that exports object, without knowing anything about its shape.

That is the current behavior and the reason there are no named imports from CJS in the Node implementation.

**Comment by bmeck** [comment]
I do see a problem looking at this with indirect exports. Since ESM is async and CJS is sync, any implementation would need to synchronously resolve any indirect exports in the pragma, which is not doable if using ESM based resolve. In a sense, using CJS based resolve is ok, but it doesn't act like a URL and does not go through ESM hooks, which would be bad.

I originally was thinking only of direct exports, but am not unsure if indirect exports can be supported in a complete and robust way.

**Comment by jdalton** [comment]
@bmeck 
Can you expand on indirect exports a bit. Do you mean those specified in a `setTimeout` or something?

**Comment by benjamn** [comment]
@jdalton I think he means exports that come from another module, via `export ... from ...`.

If that's correct, then it may increase the appeal of a statically analyzable `exports.__esModule = {...}` syntax, where the resolved source module identifiers are the values of the object literal:
```js
exports.__esModule = {
  foo: "/absolute/module/id/of/module/that/orginally/exported/foo.js",
  default: true // shorthand for a locally defined export
};
```
You (@bmeck) pushed back on this in the PR, but I don't think that objection is final: https://github.com/babel/babel/pull/6455#issuecomment-337926863

**Comment by bmeck** [comment]
@jdalton `export {foo} from '';` , `export * from '';` https://tc39.github.io/ecma262/#table-38 has 2 entries for differentiating Star from Named, but the same purpose.

**Comment by bmeck** [comment]
@benjamn if it is purely statically analyzable and not cost prohibitive, I don't mind either approach. I just need to setup the Proxy Invariants/Module Record before any instantiation or evaluation.

**Comment by bmeck** [comment]
@benjamn I do still have concerns about parsing a full AST to check the pragma if it is just any JS Object / can be in any part of the file.

**Comment by jdalton** [comment]
With complexity and perf issues growing I'm wondering if maybe trying to shoe-horn everything into a standards box is the best way forward here. Have non-💯 spec routes been explored or has runtime enhancements that v8 or Node could expand on been dug into?

**Comment by bmeck** [comment]
> Have non-💯 spec routes been explored or runtime enhancements that v8 or Node could expand on been dug into?

Expand on this?

**Comment by bmeck** [comment]
Also, landing https://github.com/nodejs/node/pull/16261 should speed things up a bit.

**Comment by jdalton** [comment]
> Expand on this?

Everything you've worked on seems to be in the context of how to make something work within spec'ed constraints. Have you considered going outside of that?

>  Also, landing nodejs/node#16261 should speed things up a bit.

Rock, improvements are needed for sure.

**Comment by Kovensky** [comment]
I kinda like that the pragma is more costly than actual ESM, encourages people to actually write ESM :trollface:

**Comment by nicolo-ribaudo** [comment]
Node.js now has a native method of handling libraries compiled by Babel.
