### ISSUE TITLE
babel-preset-typescript doesn't work with object casts

### ISSUE THREAD

**Issue by pbadenski** [babel/babel#6450]
This is a bug.

# Current behaviour

For all following (valid) TypeScript babel-typescript-preset throws an error: ```Unexpected token, expected }```.

# Input Code
```typescript
const o = <any> { a: 2 };
```

```typescript
const f = () => (<any> {
  property: "value"
});
```

```typescript
const f = () => {
  return <any> {
    property: "value"
  };
};
```

# Babel configuration (.babelrc, package.json, cli command)

```babel --extensions '.ts' --presets typescript```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.2 (babel-core 7.0.0-beta.2)
| babel-preset-typescript | 7.0.0-beta.2
| node             | v8.4.0
| npm              | 5.3.0
| Operating System | Mac OS X 10.12.6

**Comment by hzoo** [comment]
@andy-ms was this meant to be supported or is that new?

**Comment by andy-ms** [comment]
Hm, this is working fine for me. Clone https://github.com/andy-ms/babel-typescript-sample and run `npm run transpile` and it works.

**Comment by hzoo** [comment]
Going to close since it doesn't repro?

`babel --extensions '.ts' --presets typescript` in this command you aren't actually specifying a src or out? `babel --extensions '.ts' --presets typescript src -d lib` would work?

**Comment by pbadenski** [comment]
I did some triangulation and I figured it out, adding "babel-react-env" triggers that issue.. Although I'm not sure which preset causes this exactly. Failing sample here: https://github.com/pbadenski/babel-typescript-sample (based on @andy-ms example, you need to run `npm run transpile`).

**Comment by andy-ms** [comment]
@pbadenski `npm run transpile` works for me there too, although I can't perfectly reproduce your installed package versions due to npm/npm#17979.

**Comment by pbadenski** [comment]
I'm not sure what could be wrong then :( I just tested and saw this error it on a fresh ubuntu installation. If you could try `rm -rf node_modules/ package-lock.json` - I did that, and still getting the error. Otherwise I'd have to throw in the towel.

**Comment by andy-ms** [comment]
Hi @pbadenski, I messed and and wasn't actually transpiling anything. (#6502)
Is it possible that "react" is enabling JSX syntax, so that `<any>` is parsed as an opening tag? You can work around by using `{ a: 2 } as any` instead -- that has equivalent semantics, but a jsx-compatible syntax.

**Comment by pbadenski** [comment]
Workaround works great, really good suggestion.

As to your other point, having cursory look at what babylon is doing seems you're right. I know very little about the mechanics of this. Seems like this is an impossible issue to resolve, as TS and JSX syntax are clashing.

**Comment by andy-ms** [comment]
Yep, that's why we added the `as` syntax.

**Comment by pbadenski** [comment]
Understood. Thanks!
