### ISSUE TITLE
Uncaught TypeError: Constructor Map requires 'new'.

### ISSUE THREAD

**Issue by pmunin** [babel/babel#6453]
### Input Code

Here is link  to [babel playground](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECyCeswAdoFMAeAXNA7AJjEqgN4BQ0l0wA9rhFgE4CuwWNjAFAJTTlUDoEZsjRduAbgpUAvtMo4GPPvMGM0WZo1zQARAAkwIEDWgB3DiHy6pAuXIBuYRtAC2iFNAC80XGjNwHsg8UrT0NCBoAHQmAOac7sTQAJb0WGC4wGg0AGaBxJJkYRAR0XEJQVGKWDyFAPR1AMRCNFpZxMipsQCqAEoAMl7E3bjJdFEAVhBRrihAA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015&targets=&version=6.26.0)

```js
class MyMap extends Map {
    constructor() {
        super();
    }
    test() {
        return "Hallo world";
    }
}
var myMap = new MyMap();
console.log(myMap instanceof MyMap);
console.log(myMap.test());
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
"presets": [
        "env"
    ]
}
```

### Expected Behavior

Should output in console:
true
"Hallo world"

### Current Behavior

If I run it in Chrome v61 directly - works fine, but if I precompile it with babel then the following error logged:
```
Uncaught TypeError: Constructor Map requires 'new'
    at MyMap.Map (<anonymous>)
    at new MyMap (<anonymous>:17:99)
    at <anonymous>:30:13
```

### Possible Solution

There is a way to identify if the function is class by executing ".arguments" or ".caller". For regular functions it will return a value or undefined. But for classes (custom or system, like Map or Set) it will throw error `'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them` - maybe this can be used to solve this

### Context

Cannot extend Map class

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 latest available online at 10/9/2017
| node             |  n/a
| npm              |  n/a
| Operating System |  Win7 x64

**Comment by hzoo** [comment]
Thanks for reporting, Babel doesn't handle extending natives in that way still, https://babeljs.io/docs/usage/caveats/#classes

**Comment by najuste** [comment]
Sorry guys to disturb you, but I didn't understand what is the solution in such case. 
Using leaflet interests me in particular.
