### ISSUE TITLE
.babelrc gets overwritten on install

### ISSUE THREAD

**Issue by no23reason** [babel/babel#6459]
Bug report.

My existing `.babelrc` file gets overwritten if I do a fresh install.

### Input Code

```
rm -rf node_modules
rm yarn.lock
yarn
```

### Babel Configuration (.babelrc, package.json, cli command)
Original `.babelrc`:
```
{
  "presets": [
    [
      "env",
      {
        "useBuiltIns": "entry"
      }
    ],
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-decorators",
    "transform-react-constant-elements",
    "transform-react-inline-elements"
  ]
}
```
Replaced by:
```
{
  "presets": [
    "env",
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-decorators",
    "transform-react-constant-elements",
    "transform-react-inline-elements"
  ]
}
```

Relevant part of the `package.json`:

```js
{
  "devDependencies":
  {
    "babel-core": "^6.26.0",
    "babel-env": "^2.4.1",
    "babel-loader": "^7.1.2",
  }
}
```

### Expected Behavior
`.babelrc` is left alone.

### Current Behavior
`.babelrc` gets overwritten.

### Your Environment

This bug is manifested both on Windows and on macOS:

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             |  8.2.1
| npm              |  5.4.1
| Operating System | Windows 10

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             |  6.10.0
| npm              |  5.3.0
| Operating System | macOS X High Sierra

**Comment by hzoo** [comment]
There isn't anything in Babel that changes your babelrc config file.

 "babel-env": "^2.4.1", - this is not an officially supported module (not really sure what it does other than what you described). I would not use this? I believe you mean't to install `babel-preset-env` (and maybe that's why we need `@babel/` to show what is official or not

**Comment by no23reason** [comment]
Thank you @hzoo, that really was the issue, I missed the `preset` part. My bad, thanks again for your advice.

**Comment by hzoo** [comment]
all good @no23reason! Hopefully scoped packages in v7 will prevent this kind of thing in the future 🙂
