### ISSUE TITLE
optional-chaining does not work in babel@6 with webpack(3)

### ISSUE THREAD

**Issue by a-x-** [babel/babel#6460]
**bug report**

either 
babel-plugin-transform-optional-chaining@6 and babel-plugin-syntax-optional-chaining@6 don't work with babel@6 and webpack@3 (also, why two plugins are there?)

webpack uses my .babelrc (I tried to remove `.babelrc` and errors did change)
I tried place .babelrc content into webpack.config.js
I tried run development build.

### Input Code
```js
const a = {b:1};
const b = a?.b;
```

### Babel Configuration (.babelrc, package.json, cli command)
<details><summary>.babelrc</summary>

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 Chrome versions", "last 1 Safari version"]
      },
      "useBuiltIns": false,
      "modules": false
    }],
    "stage-1",
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-react-jsx-source",
    "transform-react-jsx-self"
  ]
}
```
</details>

### Expected Behavior
optional chaining operator will transpile

### Current Behavior
webpack error: `Module build failed: SyntaxError: Unexpected token (9:2)`

```
>  9 | a?.b
     |   ^
  10 |
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6 (latest)
| node             | 8 (latest)
| npm              | 5 (latest)
| webpack | 3 (latest)
| babel-loader | latest
| Operating System |  macOS

**Comment by existentialism** [comment]
@a-x greetings!

`babel-plugin-transform-optional-chaining` was added in 7.x, so it won't work with Babel@6. Also, you don't need both the transform and the syntax plugin, as using the transform automatically enables the syntax.

Also, not sure if it's just a copypasta issue, but the .babelrc you included above doesn't actually have it listed in `plugins`.

**Comment by a-x-** [comment]
Thank you for clarification about syntax-optional-chaining vs transform-optional-chaining 

I tried each single plugin of them.

**Comment by a-x-** [comment]
I should issue it to babel-loader may be, because babel understand optional-chaining, but webpack with babel does not

**Comment by hzoo** [comment]
Going to close because optional chaining shouldn't work with v7

**Comment by vjpr** [comment]
@hzoo 

> Going to close because optional chaining shouldn't work with v7

*should only

**Comment by Balasnest** [comment]
will it work with v6?
