### ISSUE TITLE
Unexpected completion value using `insertAfter` in nested JSXElement

### ISSUE THREAD

**Issue by DrewML** [babel/babel#6464]
### Input Code

```js
<div>
  <span>foo</span>
</div>
```

### Babel Configuration (.babelrc, package.json, cli command)
Custom Plugin

```js
export default function ({ types: t }) {
  const myJSXElementMarker = Symbol(); // prevent inifinite loop
  return {
    visitor: {
      JSXElement(path) {
		const tagName = path.node.openingElement.name.name;
        if (tagName !== 'span') return;
        if (path.node[myJSXElementMarker]) return;
        path.node[myJSXElementMarker] = true;
        
        const newDiv = t.JSXElement(
        	t.JSXOpeningElement(t.JSXIdentifier('div'), [], false),
          	t.JSXClosingElement(t.JSXIdentifier('div')),
          	[]
        );
        
        path.insertAfter(newDiv);
      }
    }
  };
}

```

### Expected Behavior

Expected the `div` `JSXElement` to be inserted within the parent `JSXElement`'s `children` array, after the currently visited node.

```js
<div>
  <span>foo</span>
  <div></div>
</div>
```

### Current Behavior

An assignment expression + sequence expression is injected, which changes the completion value and loses the newly-inserted element at runtime.

```js
var _temp;
<div>
  (_temp = <span>foo</span>, <div></div>, _temp)
</div>
```

### Possible Solution

Special-case `JSXElement` usage in `insertAfter` when it's within the `children` of a parent `JSXElement`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7
| node             | N/A (babel-standalone in ASTExplorer)
| npm              | N/A
| Operating System | N/A

**Comment by jridgewell** [comment]
Want to work on the PR?

**Comment by DrewML** [comment]
Yeah, forgot to update that I have this mostly fixed locally, just need to
add some test cases and open the PR once I'm not traveling.

**Comment by SmallComfort** [comment]
Hi!
I have also encountered this problem, is there any way to solve it ?

**Comment by dhruvdutt** [comment]
@DrewML Any update on this?

**Comment by jridgewell** [comment]
@dhruvdutt: It's yours.

**Comment by kevintab95** [comment]
Hi can I take a look a look at this? I think I have a fix.

**Comment by dhruvdutt** [comment]
@kevintab95 You can work on this. 👍
