### ISSUE TITLE
babel@7/preset-env@2: Destructuring assignment fails when modules 'commonjs'

### ISSUE THREAD

**Issue by tleunen** [babel/babel#6465]
### Input Code
```js
import { MESSAGE_TYPE } from './src/constants/message';

const { TYPING, AGENT } = MESSAGE_TYPE;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
presets: [
        [
            'env',
            {
                targets: {
                    forceAllTransforms: true
                },
                modules: 'commonjs',
                loose: true,
                useBuiltIns: 'usage',
                debug: false,
                exclude: ['transform-regenerator', 'transform-async-to-generator'],
            },
        ],
    ],
}
```

### Expected Behavior
This should be compiled into:
```js
var _message = __webpack_require__("./src/constants/message.js");
var TYPING = _message.MESSAGE_TYPE.TYPING,
    AGENT = _message.MESSAGE_TYPE.AGENT;
```

### Current Behavior
```js
var _message = __webpack_require__("./src/constants/message.js");
var TYPING = _message.MESSAGE_TYPE.TYPING,
    AGENT = MESSAGE_TYPE.AGENT;
```
This results in an error: `ReferenceError: MESSAGE_TYPE is not defined` because `MESSAGE_TYPE` only exists on `_message`. (See line with `AGENT`)

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.2
| Babel-preset-env            |  2.0.0-beta.2
| node             | 8.6.0
| npm              | 5.5.1
| Operating System | Mac OS 

I tried to reproduce it on the [REPL with v7](https://babeljs.io/repl/build/7.0), but I get an error if I enable preset-env with a browser like ie 9.
```
repl: Cannot read property 'bindings' of null
```

**Comment by existentialism** [comment]
Think this is due to plugin ordering in preset-env =/

I'll push a fix.

**Comment by Andarist** [comment]
I'm pretty sure that this got fixed by https://github.com/babel/babel/pull/6374

**Comment by existentialism** [comment]
@Andarist oh derp, that's right 👍

**Comment by existentialism** [comment]
@tleunen closing this, as this will be fixed in beta.3 (shipping soon!)
