### ISSUE TITLE
Meta: Rename references for `beginner-friendly` to `good first issue`

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6470]
I searched for `beginner-friendly` since github is giving first-class support for two specific labels

![screen shot 2017-10-12 at 6 03 43 pm](https://user-images.githubusercontent.com/588473/31521478-a73d23d8-af77-11e7-81bb-45cc1aa7270d.png)

---

![screen shot 2017-10-12 at 6 01 53 pm](https://user-images.githubusercontent.com/588473/31521410-77cc272a-af77-11e7-9444-740767450c4b.png)

So we just need to edit those 2 files to use `good first issue` instead of `beginner-friendly` 😊

- note below if you are going to work on this (you can also edit through github via https://github.com/babel/babel/edit/master/CONTRIBUTING.md or https://github.com/babel/babel/edit/master/README.md)

**Comment by wehelie** [comment]
can I jump on this ?

**Comment by nveenjain** [comment]
can i work on this, although this is not my first contribution?

**Comment by hzoo** [comment]
@wehelie go ahead 👌!

@nveenjain I would ask if you could be a reviewer (approve/leave comments) 👍

**Comment by hzoo** [comment]
Good work from everyone to tackle this together @wehelie @nveenjain @clarksandholtz!
