### ISSUE TITLE
Number.isFinite() is not lowered to global.isFinite()

### ISSUE THREAD

**Issue by dulinriley** [babel/babel#6472]
Bug report:

Babel does not lower the ES6 function `Number.isFinite()` to `isFinite()` from earlier ES versions.

### Input Code
[Demo of the Number.isFinite() bug](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABMOcAUAPAlIg3gKAEgAnAUyhGKQDkQBbAI1OIDoYBnAMRjBilMxYA3PgC-QA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015&targets=&version=6.26.0)

```js
function foo(x) {
	return Number.isFinite(x);
}
```

### Babel Configuration (.babelrc, package.json, cli command)
Used the es2015 preset from the babel repl

### Expected Behavior
The expected behavior is that it should be lowered to `isFinite`, which does mostly the same thing, except it is ES5 compliant (for all inputs in which `Number.isFinite` does not throw in ES6, those same inputs are correct in ES5).

### Current Behavior
It is not lowered, as the REPL shows it remains the same function call.
`Number.isFinite()` does not exist in ES5 and lower, so it becomes a runtime error.

### Possible Solution
Detect direct usages of `Number.isFinite` and convert to `isFinite`.
It can't catch when it's passed as a variable function, but it should catch the case where
it is literal.

### Context
Wanted to test if a number was finite, and had assumed babel would allow ES6 features.

### Your Environment
N/A, reproducible in the REPL

**Comment by nicolo-ribaudo** [comment]
Babel only transpires syntax, not functions. You should use a polyfill (e.g. `babel-polyfill`), which implements the built-in functions in old browsers.

**Comment by hzoo** [comment]
@nicolo-ribaudo is correct, that is a built-in so Babel has never had a plugin to compile those things down (although you could make a plugin that does so)

Something similar as been done for Object.assign/Array.includes. Not sure we should be doing that, and if so it would be something preset-env should handle
