### ISSUE TITLE
TypeError: loaderUtils.getOptions is not a function

### ISSUE THREAD

**Issue by itsMeBender** [babel/babel#6475]
Bug report : babel-core 6.26.0

I upgraded from babel-core 6.25.0 to babel-core 6.26.0 and now I got WebPack build errors; like

ERROR in ./src/components/howto-home.html
Module build failed: ModuleBuildError: Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (Q:\steps\node_modules\file-loader\index.js:12:26)
    at runLoaders (Q:\steps\node_modules\webpack\lib\NormalModule.js:195:19)
    at Q:\steps\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at Q:\steps\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at runSyncOrAsync (Q:\steps\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (Q:\steps\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (Q:\steps\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (Q:\steps\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40:15)
    at Q:\steps\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:77:9
    at Q:\steps\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
 @ ./src/main.js 5:0-38

ERROR in ./src/components/bg.png
Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (Q:\steps\node_modules\file-loader\index.js:12:26)
 @ ./src/components/howto-home.html
 @ ./src/main.js

When I switch back from 6.26 to 6.25 no problems occur.

### Package,.json 
```json
{
  "name": "steps",
  "version": "1.0.0",
  "main": "index.js",
  "private": true,
  "scripts": {
    "start": "webpack-dev-server --inline --hot --port 3000",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "itsMeBender",
  "license": "MIT",
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-preset-es2015": "^6.24.1",
    "cross-env": "^5.0.5",
    "expose-loader": "^0.7.3",
    "file-loader": "^0.11.2",
    "wc-loader": "^1.1.12",
    "webpack": "^3.5.2",
    "webpack-dev-server": "^2.7.1"
  }
}
```

### Possible Solution
Use version 6.25.0

### Context
Working with WebPack to bundle an web application.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | 6.10.2
| npm              | 5.4.2
| Operating System | Win7.pro

**Comment by loganfsmyth** [comment]
This doesn't appear to be a Babel issue.
