### ISSUE TITLE
[Feature Request] Add "preserveConstEnums" option to transform-typescript

### ISSUE THREAD

**Issue by ForbesLindesay** [babel/babel#6476]
When using the typescript compiler, there is an option to "preserve const enums", which essentially just treats const enums exactly the same as non-const enums.  It would be really useful to have the same feature in the babel transform.

### Input Code

```js
export const enum E {
    A = 1
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    ["transform-typescript", {"preserveConstEnums": true}]
  ]
}
```

### Expected Behavior

```js
export let E;

(function (E) {
  E[E["A"] = 1] = "A";
})(E || (E = {}));
```
### Current Behavior

Throws: 'const' enums are not supported

### Possible Solution

Add an option that makes const enums behave exactly the same as regular enums.

### Context

I want to be able to use babel to transform my typescript in development, as this will be much faster than doing a babel pass and a typescript pass, and babel is needed for other plugins.  In production, I can use the slower typescript transform, which handles const enums properly.

**Comment by Kovensky** [comment]
I'm not sure if this would be a good thing to support... in my opinion, `export const enum {...}` should actually be a compile error in TypeScript too, as it's impossible to use it correctly with `--isolatedModules`.

**Comment by azz** [comment]
I've always been confused by that flag. Why not just remove `const` from the `enum` rather than using a compiler flag?

**Comment by ForbesLindesay** [comment]
The reason is that const enums are a useful optimisation in production, and I can handle them by just using the full typescript compiler for the prod build.

In development. I want to make the build as fast as possible by using babel for everything and compiling each module independently.

**Comment by zheeeng** [comment]
I use const enum in declaration files(not exporting it), it is useful for distinguishing custom obj type.

**Comment by tschoartschi** [comment]
The `const enum` feature of Typescript is really nice. If file size is a concern, it makes sense to use `const enums` where possible. Just compare the output of the Typescript compiler: 

![image](https://user-images.githubusercontent.com/1695329/38013332-1bc55980-3265-11e8-923d-9afa26079197.png)

For us, loosing the `const enum` feature would be almost a dealbreaker. We use a lot of enums and if they would be all compiled to the "regular" enum syntax this would add a considerable amount of bytes to our code. Which is not neglectable in our case.

**Comment by nojvek** [comment]
const string enums are even more fantastic, because then you're essentially just dealing with strings.

**Comment by alloy** [comment]
@andy-ms Do you see any possibility to support this?

**Comment by nicoburns** [comment]
@nojvek Is there any advantage to a string const enum type over a union of string literal types?
```typescript
type COUNTRIES = "austria" | "germany" | "greece" | "brazil";
```

**Comment by fbartho** [comment]
@nicoburns Autocomplete / usability by the developers?

**Comment by mattkrick** [comment]
@nicoburns 

here's an example where it'd be useful: 

`const defaultCountry = COUNTRIES.GERMANY` 

in my own app, I use `const enums` for my color palette, where it's really nice to avoid hex strings

**Comment by nicoburns** [comment]
@mattkrick Can't you also do `const defaultCountry = "germany";`, which will typecheck just as strictly? Is it about keeping the code size down with an integer rather than a string?

**Comment by majelbstoat** [comment]
As @mattkrick says, sometimes the values are not as clear as "germany" and const string enums can be very clarifying, while still compiling to the raw string, avoiding any overhead. 

But partly, it's an expectations thing. const string enums are part of typescript, they're useful and not having them is surprising to developers (even if the reason for their current absence is reasonable). It also means, for example, babel-node can't be a drop-in replacement for ts-node, which is a shame.

**Comment by IljaDaderko** [comment]
I came across an issue related to this today. Imagine if you are in a monorepo project that has `firebase`, `react-native` and `types` packages.

Using normal `enum` causes issue inside `firebase` package if you use their serverless functions that run `npm install` during deployment. Since enums are transpiled to something like

```ks
const types_1 = require("@MyApp/types");
// ...
types_1.SIZE.BIG
```

and `@MyApp/types` is not available on npm, we get an error. Using `const enum` solves this as it is now transpiled to just `"BIG"`

But now, we get an issue in `react-native` project that uses babel to transpile typescript unless we add additional step to run typescript compiler, which feels like an overkill for this one feature. Falling back to `type SIZE = "BIG" | "SMALL" | "MEDIUM"` is only solution now, but we loose nice auto complete and devs will always need to spell these string correctly.

**Comment by karlhorky** [comment]
Prior art (sucrase): https://github.com/alangpierce/sucrase/issues/423#issuecomment-467085280

> For example, TypeScript const enums are treated as regular enums rather than inlining across files.

**Comment by dosentmatter** [comment]
Is it possible to write a babel plugin to run before `transform-typescript` that removes the `const` before enum? You can have the plugin only run in development. I don't know how to write babel plugins, converting all `const enum` into `enum` sounds simple.

**Comment by dosentmatter** [comment]
I went through the [babel-handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-introduction). It's pretty simple. The `const` is just controlled by a boolean in the AST:

```
Node {
  type: 'TSEnumDeclaration',
  start: 159,
  end: 203,
  loc:
   SourceLocation {
     start: Position { line: 7, column: 0 },
     end: Position { line: 10, column: 1 } },
  const: true, // BOOLEAN HERE
...
```

Just traverse the whole AST and set them all to `false`.

Here is what I have so far (you guys can run it in node). I still need to read the part on how to create a plugin.

```sh
$ npm install @babel/parser @babel/traverse @babel/types @babel/generator
```

```js
// const-enum.js
const parser = require('@babel/parser');
const { default: traverse } = require('@babel/traverse');
const types = require('@babel/types');
const { default: generate } = require('@babel/generator');

const code = `
const enum Enum {
  A = 1,
  B = A * 2
}
`.trim();
console.log(`Before:
${code}
`);

const ast = parser.parse(code, {
  sourceType: 'module',
  plugins: ['jsx', 'typescript']
});

traverse(ast, {
  enter(path) {
    if (types.isTSEnumDeclaration(path.node, { const: true })) {
      path.node.const = false;
    }
  }
});

console.log(`
After:
${generate(ast).code}
`.trim());
```

```sh
$ node const-enum.js
```

**Comment by nicolo-ribaudo** [comment]
You can experiment here: https://astexplorer.net/
It's a playground where you can create your own plugin and use it online in real time.

**Comment by dosentmatter** [comment]
@nicolo-ribaudo I saw that site, but I don't see TypeScript support, only JavaScript.

**Comment by nicolo-ribaudo** [comment]
You can click on the gear next to the parser (in the header), and enable TypeScript support for Babylon 7. (which is the old name of @babel/parser)

**Comment by dosentmatter** [comment]
Using JavaScript + babylon7, I get `Unexpected reserved word 'enum' (1:6)` for the following code:

```
const enum Enum {
  A = 1,
  B = A * 2
}
```

I tried on the [babel site](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYOwrgtgBAou0G8BQUoEEoF4oEYA0KUAQlulAFRQBMSAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.0&externalPlugins=%40babel%2Fplugin-syntax-typescript%407.3.3%2C%40babel%2Fplugin-transform-typescript%407.5.0) and noticed that enabling `preset-typescript` doesn't do anything. I need to manually add `plugin-syntax-typescript` to allow `enum` syntax and `plugin-transform-typescript` to transform it to JS.

The only combinations that work on AST explorer are JavaScript + one of the following:

- flow
- typescript-eslint-parser
- @typescript-eslint/parser
- typescript

The only transformer that works is `tslint`. `babelv7` transformer doesn't work with any parser. It complains about `enum`.

I wonder why I don't have any problems in node, without having to enable `plugin-syntax-typescript`.

![image](https://user-images.githubusercontent.com/5732253/60691068-a94ee300-9e81-11e9-8143-328b60ff5a0e.png)

**Comment by nicolo-ribaudo** [comment]
Did you click on the gear next to "babylon7" and enable it's TypeScript plugin?

**Comment by dosentmatter** [comment]
Oh, my mistake. I misunderstood the UI and what you said earlier. I thought parser dropdown and the gear was the same thing. Didn't notice the gear was separate settings for the parser. Thanks!

**Comment by dosentmatter** [comment]
Actually, I figured out a workaround. I just cloned their repo to run locally with modified code. I changed `'flow'` to `'typescript'` since both can't be enabled together.

Now everything works:
![image](https://user-images.githubusercontent.com/5732253/60701166-a2d76000-9eaf-11e9-9025-3fa9b9e2cf3f.png)

**Comment by dosentmatter** [comment]
Yay! I finished my plugin, [babel-plugin-const-enum](https://www.npmjs.com/package/babel-plugin-const-enum).

Add to your `.babelrc`:
```json
{
  "plugins": [
    "const-enum"
  ]
}
```

The README has more information.

It also has a transform for #8741 if you use the option `"transform": "constObject"`.

Feel free to file issues or send in PRs at the [GitHub Repo](https://github.com/dosentmatter/babel-plugin-const-enum). This is my first time writing a plugin so there are things that can be improved.

**Comment by karlhorky** [comment]
Really awesome @dosentmatter ! 

@ForbesLindesay is this enough to close this issue? Or maybe first this plugin should be documented in some FAQ or something in the Babel TypeScript docs?

**Comment by karlhorky** [comment]
Really awesome @dosentmatter ! 

@ForbesLindesay, considering there are some tradeoffs / footguns with the approach in your original description, is this plugin enough to close this issue?

Maybe along with some documentation about enums and this plugin in some FAQ or something in the Babel TypeScript docs?

**Comment by nicolo-ribaudo** [comment]
Yes, we should definitely link it in our docs.

**Comment by qm3ster** [comment]
Why is `removeConst` the default? What are the tradeoffs? (considering the `transform-typescript` doesn't typecheck anyway)

**Comment by dosentmatter** [comment]
> Why is `removeConst` the default? What are the tradeoffs? (considering the `transform-typescript` doesn't typecheck anyway)

@qm3ster, the reason I chose `removeConst` to be default is because it relies on regular `enum` transpilation of `@babel/plugin-transform-typescript` and it is just the simpler solution.
I didn't want the default to be `constObject`, because that may be unexpected for developers. They have to wrap their head around why the `constObject` works, when they may just want `const enum` to work and not care about how. I left `constObject` for more "advanced" users.
Although, `constObject` should still work correctly without a minifier to inline `enum` access.

**Comment by vegerot** [comment]
What's the status on this?  Would really like to use `const enum`s in my TypeORM `enum` columns

**Comment by dosentmatter** [comment]
@vegerot, I saw you commented https://github.com/babel/babel/issues/8741#issuecomment-624234808 and you got a reply on that issue to use `babel-plugin-const-enum`. That issue is talking about using `constObject` option of `babel-plugin-const-enum`. If you want to `removeConst`, `babel-plugin-const-enum` allows you to do that. See https://github.com/babel/babel/issues/6476#issuecomment-509039884.

If you need the plugin to only run on TS files, you can use the [`babel-preset-const-enum`](https://github.com/dosentmatter/babel-preset-const-enum). I am the author of the plugin so you can file an issue if you have any problems.

**Comment by vegerot** [comment]
Thank you.  I'll look into it
