### ISSUE TITLE
Create an ES3 transform to rename identifiers that match ES3 reserved words

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6477]
From https://stackoverflow.com/questions/46713720/how-to-transpile-variable-names-that-are-reserved-words

The ES3 spec includes a bunch of reserved words that are allowed in ES5 and ES6, so we should have a transform that walks through all the variables in a file and renames them if they match those.

I'd go with `babel-plugin-transform-es3-reserved-words`.

**Comment by maurobringolf** [comment]
I am giving this a shot. Should the list of reserved keywords be imported from somewhere or literally be put into the plugin?
