### ISSUE TITLE
incorrect static class field initialization order

### ISSUE THREAD

**Issue by gsathya** [babel/babel#6493]
> Choose one: is this a bug report or feature request?

bug report

### Input Code

```js
function one() {
  console.log("one");
  return "one";
}

function one_init() {
  console.log("one init");
  return 1;
}

function two() {
  console.log("two");
  return "two"
}

function two_init() {
  console.log("two init");
  return 2;
}

class X {
  static [one()] = one_init();
  static [two()] = two_init();
}

new X;
```

### Babel Configuration (.babelrc, package.json, cli command)

stage2, stage3

### Expected Behavior
one
two
one init
two init

### Current Behavior

one 
one init
two
two init

### Your Environment
[REPL](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABAgpgCgJSIN4ChGIQIDOcANigHRlwDmaARKgxgNz6IBOKUInSTMCgbsAvrlyhIsBMiEB9GGBhRMODkTCkK1Oo1SIlKluwLde_RAEYxEqdHhIoAdzhq8BTdqo16DF3AmHOZ8AgEMuOKS4A6yAYrKqlgehCTkPnr-roaJQWY8oYgATLa4EGQAhsTEiAAa6gTEUBWwEIgA2qiYALqIALxyKAkqmKaITS0wbe0BPf2I8UZJpULOdaxAA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=stage-2%2Cstage-3&targets=&version=7.0.0-beta.3)

**Comment by Andarist** [comment]
Im going to work on fixing this in few days.

**Comment by xtuc** [comment]
Good news @Andarist and thanks @gsathya for the report.
