### ISSUE TITLE
please clarify license for packages/Babel-preset-es2015/test/fixtures/traceur

### ISSUE THREAD

**Issue by pravi** [babel/babel#6497]
Is the files under this directory taken from traceur project and hence under apache license or are they under the global MIT license? Please add a clarification in LICENSE file in this directory.

This clarification is required for adding Babel package to debian.

**Comment by loganfsmyth** [comment]
Not that I'm against trying to address the licensing question, but I'm not sure we'd really want Babel to be packaged for Debian. Can you clarify why that would be desirable? We generally don't recommend Babel be installed anywhere except a `node_modules` folder.

**Comment by pravi** [comment]
@loganfsmyth you are not the first one I have encountered who did not want their software to packaged (or in general have their software not installed globally at all). While it is certainly your choice whether to support such installations or not, since these are Free Software and its users decide how they want to use the software, not its developers.

In debian, we want all software to be buildable from their source and packaging babel will help us build a lot of node modules from their sources rather than take their prebuilt es5 files from npmjs.com This is important from a security stand point and supportability stand point. Just to give an example, we'd like to build all d3 modules using babel (and they all pass their functionality test). I know this means we are deviating from the upstream build process and we need to support it ourselves. By ensuring all the tests are passing and having their source available, we take that responsibility.

Though most users will only likely install software like gitlab, which will use these modules internally. Basically we want apt-get install gitlab work and d3, babel are only parts of that process. As long as we can make sure all functionality tests of gitlab are passing, we are ready to support these packages ourselves.

**Comment by jridgewell** [comment]
I think they're under Apache 2.0 license.

**Comment by loganfsmyth** [comment]
@pravi You're certainly free to use the code as you see fit. My concern is entirely around concern for potential user confusion if people install Babel from Debian and then get confused if it doesn't work the same as the version from npm. Babel's `.babelrc` files expect plugins to be installed in `node_modules` for instance, so using a globally installed version of Babel will fail to find the plugins.

If you want to pursue bundling, it seems like you'll want to write your own wrapper around Babel to expose the functionality you're looking to use, while disabling config file processing like `.babelrc`. If you do go that route, it seems like it'd be ideal to give the package a name that makes that clearer, like `simple-babel` or something, so people are less likely to get confused if they install both somehow or something.

**Comment by hzoo** [comment]
There is a license for the fixtures in https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/test/fixtures/traceur/LICENSE, and these are tests not what Babel packages itself

**Comment by pravi** [comment]
@loganfsmyth debian package installs babel command as babeljs (mainly to avoid conflict with openbabel which also provides babel command), so even if both debian packaged and npm installed babel-cli is present, someone needs to explicitly choose babeljs command to get debian packaged version. As for plugins, it is working fine right now with globally installed plugins (in debian all modules are installed under /usr/lib/nodejs). Since we don't make any functionality changes (.babelrc just works) I don't think a rename is necessary. What we mainly want to achieve is to build all modules we package in debian with a single version of babel, it means sometimes we need to patch those modules as well. For example https://github.com/wycats/handlebars.js/issues/1386 handlebars.js currently needs babel5 but we only support babel6 in debian, so we need to patch handlebars to work with babel6. Usually most projects are receptive to updating dependencies to latest version.
