### ISSUE TITLE
Cannot assign to read only property 'history' of object '#<Window>'

### ISSUE THREAD

**Issue by pldg** [babel/babel#6498]
### Input Code

`index.html`

```html
<body>
  <div class="history"></div>
  <script type="text/javascript" src="./main.compiled.js"></script>
</body>
```

`main.js`

```js
const history = document.querySelector('.history');
```

`shell command`

```shell
npm run compile
```

Full code at [jsbin](https://jsbin.com/miqulihogu/edit?html,css,js,output).

### package.json

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "compile": "babel main.js --out-file main.compiled.js"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.0"
  }
}
```

### .babelrc

```js
{
  "presets": ["env"]
}
```

### Expected Behavior
Transpile without console errors.

### Current Behavior
The transpile works:

```js
'use strict';

var history = document.querySelector('.history');
```

but there is an error in browser console: `Cannot assign to read only property 'history' of object '#<Window>'`.

### Solution
Changing variable name from `history` to something else, for example:

```js
const h = document.querySelector('.history');
```

solve the problem.
Why?!

### My Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 6.11.2
| npm              | 5.5.1
| Operating System | Windows 10

Folder structure:

```
/app
  /node_modules
  .babelrc
  index.html
  main.compiled.js
  main.js
  package-lock.json
  package.json
```

**Comment by hzoo** [comment]
hi @pldg, thanks for making an issue. This seems to have nothing to do with Babel itself or the compile. It's an error from the browser (if you didn't use babel and wrote the transpiled output yourself it still has that error).

It would be weird if babel compiled the name differently 😛

**Comment by pldg** [comment]
Seems that if I delete `'use strict';` in `main.compiled.js` then it works... I still don't understand why, but you can delete this topic if is not related to Babel. Thanks for your answer @hzoo

**Comment by hzoo** [comment]
in the future I would suggest using a bundler later if you are going to load a script(s) into the browser instead of using babel-cli

**Comment by pldg** [comment]
Thanks @hzoo, I'm new to Babel, I'll definitely start to learn a bundler soon.

Regard the bug above, I found another bug related to that one...
If I change `main.compiled.js` contents to
`var history = document.querySelector('.history');`
without `'use strict';`
the console does not throw any error, but I inspect the variable `history` and it's not selecting the element in the DOM but it said `History {length: 2, scrollRestoration: "auto", state: null}`.
If I change the name of the variable to something else than it works as expected, it select the DOM and I can add method and property on it...

Any suggestion?

**Comment by hzoo** [comment]
`history` is a global variable on window so thats the original issue you had

**Comment by pldg** [comment]
Didn't know that!
Just found https://developer.mozilla.org/en-US/docs/Web/API/Window/history
Thanks a lot for your help @hzoo
