### ISSUE TITLE
super() outside of class constructor [not sure if bug?]

### ISSUE THREAD

**Issue by damianobarbati** [babel/babel#6501]
Not sure if this is up to webpack or babel.
BTW:
```
static constructor = props => {
    super(props);
};
```
triggers:
```
Module build failed: SyntaxError: super() outside of class constructor (71:8)
```

Shouldn't this syntax be allowed?

**Comment by nicolo-ribaudo** [comment]
IIRC super() is only allowed in class constructors.

**Comment by damianobarbati** [comment]
@nicolo-ribaudo I agree but `constructor` is just a static class method which is called with the `new` keyword.
So is the following the same?
```
static constructor = props => {}
same as
constructor () {}
```

**Comment by nicolo-ribaudo** [comment]
No, they aren't. `constructor() {}` isn't a static class method: it is an instance method with a special meaning.
You can check that it is not a static method with the following code:
```js
class A {
  constructor() { "foo" }
}

console.log("Static constructor:", A.constructor); // Something like "[native code]", because it is Function.constructor
console.log(A.constructor === Function.constructor);

console.log("Prototype constructor: ", A.prototype.constructor); // "constructor() { "foo" }"
```

**Comment by hzoo** [comment]
yeah a static class property (Stage 3 proposal) isn't the same as a constructor method
