### ISSUE TITLE
Misc Cleanup from #6495

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6504]
I forgot to remove the whole folder in the previous PR

Task is just to remove this 😎: https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-functions

- [ ] Comment below you are working on this (multiple people will see this but we'd ask that you would allow the first person to complete the task and for you to help review* that it's correct 👌)
- [ ] Read through our [contributing](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [ ] Submit a PR
- [ ] Ask questions below or [join our slack](slack.babeljs.io) and ask in #development

**Comment by willsoto** [comment]
I'll work on this!
