### ISSUE TITLE
More Cleanup from #6495

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6505]
Readme in preset-env still needs some cleanup, https://github.com/babel/babel/blob/master/experimental/babel-preset-env/README.md

We changed to scoped packages in #6495, but the readme still has references to `babel-`. We need to change those to `@babel/` (unless it's referring to the file path itself).

EDIT: ok I think there's only one instance left to change

<img width="553" alt="screen shot 2017-10-18 at 7 36 18 pm" src="https://user-images.githubusercontent.com/588473/31747549-7d9c72ea-b43b-11e7-9810-639a36f6de38.png">

Where it says `npm install babel-polyfill --save`, should be `npm install @babel/polyfill --save`

- [ ] Comment below you are working on this (multiple people will see this but we'd ask that you would allow the first person to complete the task and for you to help review* that it's correct 👌)
  - [ ] I would note there might be other places in the codebase that are also still `babel-`. Some of them are referring to the name of the folder in the repo itself which hasn't changed so those are ok (since test are all passing)
- [ ] Read through our [contributing](https://github.com/babel/babel/blob/master/CONTRIBUTING.md), feel free to use `[skip ci]` in the commit to skip ci since the only file changing is markdown
- [ ] Submit a PR
- [ ] Ask questions below or [join our slack](slack.babeljs.io) and ask in #development

**Comment by knittingcodemonkey** [comment]
Looks like a quick change. I'll take this one.
