### ISSUE TITLE
More Cleanup from #6495 (renames)

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6506]
## Change the below relative references to babel packages to `@babel/`

https://github.com/babel/babel/blob/2311ddbe67ca0170195d1a8e3b7648f8e518b8fd/packages/babel-runtime/scripts/build-dist.js#L6-L7

https://github.com/babel/babel/blob/2311ddbe67ca0170195d1a8e3b7648f8e518b8fd/packages/babel-runtime/scripts/build-dist.js#L50-L54

So `"../../babel-core"` -> `@babel/core`

## Add those 4 dependencies above as devDeps in the package.json for babel-runtime.

https://github.com/babel/babel/blob/2311ddbe67ca0170195d1a8e3b7648f8e518b8fd/packages/babel-runtime/package.json#L12-L15

> Oh and can change preset-es2015 to preset-env

- [ ] Comment below you are working on this (multiple people will see this but we'd ask that you would allow the first person to complete the task and for you to help review* that it's correct 👌)
- [ ] Read through our [contributing](https://github.com/babel/babel/blob/master/CONTRIBUTING.md), feel free to use `[skip ci]` in the commit to skip ci since the only file changing is markdown
- [ ] Submit a PR
- [ ] Ask questions below or [join our slack](slack.babeljs.io) and ask in #development

**Comment by knittingcodemonkey** [comment]
I got this 👍
