### ISSUE TITLE
IE11: SCRIPT438:Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by hezhongfeng** [babel/babel#6511]
### Input Code

```js
      let topicsDoc = document.querySelectorAll(".topic");
      let topicList = "";
      topicsDoc.forEach(function(element) {
        topicList += element.innerText;
        console.log(element.innerText);
      });
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "ie >= 11"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}

```

### Expected Behavior

console some text
### Current Behavior

IE11 will has en error
`SCRIPT438:Object doesn't support property or method 'forEach'`

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.22.1
| node             | 6.11.0
| npm              |  3.10.10
| Operating System | win10

**Comment by hzoo** [comment]
This looks to be unrelated to using Babel or not? Does ie11 not support forEach on querySelectorAll? It's not anything related to changing the syntax from let to var, so you'd need to add a polyfill

**Comment by Andarist** [comment]
Yeah, it's not supported in IE - https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility

**Comment by hezhongfeng** [comment]
@Andarist 
Thank you for your answer.
Has any way to resolve it?

**Comment by loganfsmyth** [comment]
The easiest thing to do would be 

    let topicsDoc = Array.from(document.querySelectorAll(".topic"));

since `Array` will have `.forEach`.

**Comment by hezhongfeng** [comment]
@loganfsmyth 
tks.
I will try it.

**Comment by hezhongfeng** [comment]
@loganfsmyth 
I test it and I found this is okay.
1. for
```
for(var **index=0;index<nodeList.length;index++)**
```
2. slice.call
```
var arr = Array.prototype.slice.call(nodeList);
```

**Comment by loganfsmyth** [comment]
Yup, those are options too. They do pretty much the same thing as `Array.from`, assuming you have `Array.from` or a polyfill for it.
