### ISSUE TITLE
Pipeline operator destructuring

### ISSUE THREAD

**Issue by craigayre** [babel/babel#6514]
Choose one: is this a bug report or feature request?
**Bug report**

### Input Code

```js
// Array destructing
a |> ([x]) => x

// Object destructuring
b |> ({ y, z }) => y + z
```

### Babel Configuration (.babelrc, package.json, cli command)

Stage-0 preset set on the [REPL](https://babeljs.io/repl/build/5099/#?babili=false&browsers=&build=&builtIns=false&code_lz=IYAgPgfCAUDaAeBdAlCAvFeAoLAjcU0A3iAJ4A0IAXiAL6oZkgDU1QA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=stage-0&targets=&version=7.0.0-beta.2%2Bpr.6335)

### Expected Behavior

Expected `a` to be destructured and return the first element.

Expected `b` to be destructured and to return the sum of `a` and `b`

### Current Behavior

The output contains the variables that were intended to be destructured but they do not exist causing a `ReferenceError`

**Ouput**:
```
var _ref, _y$z;

_ref = a, x;
_y$z = b, y + z;
```

### Context

The issue was discovered when experimenting with the new syntax in a [dimensions converter](https://babeljs.io/repl/build/5099/#?babili=false&browsers=&build=&builtIns=false&code_lz=PTAEFMDoHNNAiArAcgAz1AWgHykQKAGMB7AOwGcAXUAM3HEoEFSATASVMIAtxyBlSgCcAlqWgAVYgDF61ALy1Zzdpx78ho6KDnZ8oRQ2UduvASLF79oSOQAOAG2GUAFPGTwAlJf2QAtgENbZwA5AFdfACNwQS8rUAAfXGcAbToGABpQURNyAF0PbVw06gBqLNVeUDAARgAmAG4gA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=stage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=&version=7.0.0-beta.2%2Bpr.6335)

### Your Environment

The bug was discovered while using the babel REPL with the following settings:

| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.2+pr.6335
| node             | 7.4
| npm              | N/A
| Operating System | Windows 7

**Comment by jridgewell** [comment]
Ruh roh.
