### ISSUE TITLE
babel-helper-annotate-as-pure not found (Travis/Node.js v4)

### ISSUE THREAD

**Issue by futagoza** [babel/babel#6516]
I have my own preset ([babel-preset-futagozaryuu](https://github.com/futagoza/babel-preset-futagozaryuu)) which I use and update when Babel releases a new version.

Today, after I realised Babel 7 (Beta 3) was out, I updated my preset and made sure it works on my Laptop (Windows 10 Home x64) using Node.js 8.6, and then released it (v2.11) but Travis choked while running the [job](https://travis-ci.org/futagoza/babel-preset-futagozaryuu/builds) on Node.js v4, complaining about `babel-helper-annotate-as-pure` not being found.

Not sure if this is a `support request` or a `bug`

### Babel Configuration (.babelrc, package.json, cli command)

To build the package: [babel-preset-futagozaryuu/src/.babelrc.js](https://github.com/futagoza/babel-preset-futagozaryuu/blob/master/src/.babelrc.js)

### Expected Behavior

Node.js v4 to find the module `babel-helper-annotate-as-pure`

### Current Behavior

Node.js v4 not finding the module `babel-helper-annotate-as-pure`, and throwing: `{ [Error: [BABEL] src/buildOptions.js: Cannot find module 'babel-helper-annotate-as-pure'] code: 'MODULE_NOT_FOUND' }`

Check the [1st job in the last 2 Travis builds](https://travis-ci.org/futagoza/babel-preset-futagozaryuu/builds) for the actual error:

- Job 35.1: https://travis-ci.org/futagoza/babel-preset-futagozaryuu/builds/290096103
- Job 36.1: https://travis-ci.org/futagoza/babel-preset-futagozaryuu/builds/290116099

### Possible Solution

After staying awake for over 24 hour's I'm brain dead, so I'm hoping some has a solution for me when I wake up 😆 

### Context

Running `babel src --out-dir lib` through the script `npm run build`

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  Babel 7 (Beta 3)
| node             | Node.js v4 / Node.js v4.2.6
| npm              | 2.14.2 / 2.14.12
| Operating System | Travis - Ubuntu 14.04.5 LTS

**Comment by hzoo** [comment]
https://unpkg.com/babel-helper-annotate-as-pure@7.0.0-beta.3/ is definetely on npm, so it must be another issue? Or specifically with npm 2.

**Comment by loganfsmyth** [comment]
This is fixed in https://github.com/babel/babel/pull/6490 I believe, so it should go out in the next beta release.

**Comment by hzoo** [comment]
Oh right, it's not a dependency.. although next release is with scoped packages 😛

**Comment by jridgewell** [comment]
Closing as fixed.
