### ISSUE TITLE
[7.0.0-beta.3] problems with jsx pragma

### ISSUE THREAD

**Issue by drcmda** [babel/babel#6518]
We have a project in which we use react, but also, in the same project, a custom jsx renderer that we drive using `h` as the jsx pragma (`/** @jsx h */`). Something in beta.3 starts to mix up pragmas leading to situations where react components are reliant on `h` when they should alias to `React.createElement`. beta.2 had no problems whatsoever.

<img width="723" alt="screen shot 2017-10-20 at 00 20 21" src="https://user-images.githubusercontent.com/2223602/31797210-793556d4-b52d-11e7-91bc-00d979d7c639.png">
<img width="355" alt="screen shot 2017-10-20 at 00 20 34" src="https://user-images.githubusercontent.com/2223602/31797211-794e3302-b52d-11e7-8276-c6e044c735de.png">
<img width="975" alt="screen shot 2017-10-20 at 00 21 07" src="https://user-images.githubusercontent.com/2223602/31797212-79695cc2-b52d-11e7-8919-bc88be1c51b6.png">
<img width="892" alt="screen shot 2017-10-20 at 00 21 43" src="https://user-images.githubusercontent.com/2223602/31797213-7982c658-b52d-11e7-9fac-0536904e9b43.png">

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.3
| node             | 8.7.0
| npm              | 5.4.2
| Operating System | High Sierra

**Comment by loganfsmyth** [comment]
Good find. I see what has gone wrong. PR incoming. Regression from https://github.com/babel/babel/commit/fcdfc61bdbf8898c9cf872fa4f615bddd4cd3548#diff-18da325252fa9074bd50f8b406413a01L25
