### ISSUE TITLE
optional-chaining plugin: Cannot read property 'loose' of undefined w/ Webpack 3

### ISSUE THREAD

**Issue by iEchoic** [babel/babel#6520]
When I try to build, I get this error in Webpack 3:

```
Module build failed: TypeError: Cannot read property 'loose' of undefined
    at _default (<path redacted>/node_modules/babel-plugin-transform-optional-chaining/lib/index.js:12:31)
```

Here are my plugins:

```
plugins: [
                "transform-optional-chaining",
                'transform-decorators-legacy',
                'transform-class-properties',
                'transform-runtime',
              ],
```

I edited `12:31` in index.js from `options.loose` to `(options || {}).loose`, but then the plugin just didn't work and said that the period in `?.` is unexpected character. On latest beta version of optional chaining plugin. Any ideas?

**Comment by loganfsmyth** [comment]
That plugin is new Babel 7.x-beta, but it sounds like you may be trying to use it with Babel 6.x.

**Comment by iEchoic** [comment]
Oh, that sounds likely. I'll upgrade right now and will update with results, thank you!

**Comment by OKNoah** [comment]
Same issue with Babel 7 and no Webpack.

**Comment by OKNoah** [comment]
Another troublesome issue I had that lead to a similar error.

```js
use: { loader: 'babel-loader' }
```

The solution ended up being to install `babel-loader@^8.0.0-beta.0`. Since it's a beta, it will not install by default when doing `yarn add babel-loader`.
