### ISSUE TITLE
Backporting debug package DDoS Fix to babel 6.xx.x

### ISSUE THREAD

**Issue by dkotin-cs** [babel/babel#6521]
Hi, 

Nsp check reveals https://nodesecurity.io/advisories/534 for any project using babel-core v6.26.0. Vision media has resolved the issue in v2.6.9 and v.3.1.0 of their package (https://github.com/visionmedia/debug/pull/504 )

Is it possible to release a corresponding update to babel core for those of us on 6.xx.x while v7 is getting stabilized? 

Thanks

**Comment by nicolo-ribaudo** [comment]
Hi,
Babel the dependency on the debug package is specified as `^2.6.8`, so if you delete the `node_modules` folder and run `npm install`, it should download v2.6.9

**Comment by dkotin-cs** [comment]
Thanks! I'll give that a crack and report on what happens

**Comment by dkotin-cs** [comment]
It worked!
