### ISSUE TITLE
Add a 'throwIfNamespace' option for JSX transform that defaults to 'true'

### ISSUE THREAD

**Issue by DanielRuf** [babel/babel#6535]
As far as I understand the JSX spec allows namespace tags and they make sense in specific use cases.

Is there another reason to not support it than React alone (which does not implement it, but it's still valid JSX)?

---
EDIT by @hzoo:

- Comment below if you are going to try to work on this and if someone is already working on this, you can still do it yourself but instead of making a PR you can help review

**Comment by loganfsmyth** [comment]
What would it transform to that can't be achieved with the existing `.`-separated syntax?

**Comment by DanielRuf** [comment]
Well, we use / need tags like `<f:image>` which is valid namespaced XML but not allowed by the JSX helper builder.

https://github.com/babel/babel/blob/830c527bb7873b29f671a3568b21b4a6af98ceda/packages/babel-helper-builder-react-jsx/src/index.js#L16-L20

Reference:
https://github.com/facebook/react/issues/11321

**Comment by loganfsmyth** [comment]
I mean, Babel converts
```
<div>
```
to
```
React.createElement("div", null);
```
so what should it convert the namespace to? As far as I know `.createElement` does not handle namespaces.

**Comment by DanielRuf** [comment]
JSX is not just about React afaik.

**Comment by loganfsmyth** [comment]
So it's clear, you'd like it to pass through as `h("f:image", null)` or something along those lines then?

I think that's a fair request. Maybe we can add a `throwIfNamespace` option that defaults to `true`, so that if people are using frameworks that can handle namespaces, they have an option?

**Comment by DanielRuf** [comment]
Exactly. That would be a useful solution which we could build upon.

**Comment by jukben** [comment]
If it's possible I would like to give a try. It sounds pretty straightforward.

**Comment by existentialism** [comment]
@jukben awesome! it's yours!

**Comment by rajzshkr** [comment]
I was about to comment in this. Good luck @jukben
