### ISSUE TITLE
Consider moving away from Slack?

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#6536]
Ref: https://github.com/babel/notes/issues/38

Let's consider moving away from Slack. It's not really suited for our use case of an open chat room where anyone can join, and lacks proper moderation tools to protect against spammers (banning by IP, rate limiting of signups, allowing users to report spammy DMs, ability to totally disable DMs, etc.). It also doesn't allow searching of archives, and will hit scaling issues if the room size increases (see what happened to FreeCodeCamp: https://medium.freecodecamp.org/so-yeah-we-tried-slack-and-we-deeply-regretted-it-391bcc714c81)

A lot of communities are on Discord now. I haven't really used Discord much so I'm not sure whether it's actually better or not, but at least it allows open registration, different permission groups, and has [verification levels](https://support.discordapp.com/hc/en-us/articles/216679607-What-are-Verification-Levels-) to deter spammers.

**Comment by azz** [comment]
> doesn't allow searching of archives

Doesn't Slack stand for Searchable Log of All Communication and Knowledge?

**Comment by hzoo** [comment]
We don't have the same issues with scaling and archives so that's not an issue. We have slack archive and now an instance so we do have search so those cons aren't a thing for us. Only real concern is what happened with spam and we'll talk to Slack more about what they can do before we decide to move off

**Comment by hzoo** [comment]
There's still issues (people can still spam) but we turned on signups again and we have search now, etc.
