### ISSUE TITLE
transform-unicode-property-regex tests failing on master

### ISSUE THREAD

**Issue by xtuc** [babel/babel#6537]
Choose one: is this a bug report or feature request?
bug report
```
1) babel-plugin-transform-unicode-property-regex/with unicode flag emoji:
 /home/travis/build/babel/babel/packages/babel-plugin-transform-unicode-property-regex/test/fixtures/with-unicode-flag/emoji/actual.js !== /home/travis/build/babel/babel/packages/babel-plugin-transform-unicode-property-regex/test/fixtures/with-unicode-flag/emoji/expected.js
 + expected - actual
 var regexEmojiModifier = /[\u{1F3FB}-\u{1F3FF}]/u;
 -var regexEmojiComponent = /[#\*0-9\u{1F1E6}-\u{1F1FF}\u{1F3FB}-\u{1F3FF}]/u;
 +var regexEmojiComponent = /[#\*0-9\u200D\u20E3\uFE0F\u{1F1E6}-\u{1F1FF}\u{1F3FB}-\u{1F3FF}\u{E0020}-\u{E007F}]/u;
 at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:184:46)
 at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:231:13)
 at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:260:15)

 2) babel-plugin-transform-unicode-property-regex/without unicode flag emoji:
 /home/travis/build/babel/babel/packages/babel-plugin-transform-unicode-property-regex/test/fixtures/without-unicode-flag/emoji/actual.js !== /home/travis/build/babel/babel/packages/babel-plugin-transform-unicode-property-regex/test/fixtures/without-unicode-flag/emoji/expected.js
 + expected - actual
 var regexEmojiModifier = /(?:\uD83C[\uDFFB-\uDFFF])/;
 -var regexEmojiComponent = /(?:[#\*0-9]|\uD83C[\uDDE6-\uDDFF\uDFFB-\uDFFF])/;
 +var regexEmojiComponent = /(?:[#\*0-9\u200D\u20E3\uFE0F]|\uD83C[\uDDE6-\uDDFF\uDFFB-\uDFFF]|\uDB40[\uDC20-\uDC7F])/;
 at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:184:46)
 at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:231:13)
 at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:260:15)
```

You can see the [full log here](https://travis-ci.org/babel/babel/jobs/291325091#L1013)

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  master
| node             | 8, 6 and 4
| npm              | 
| Operating System | CI

Changes were introduced in https://github.com/babel/babel/pull/6499

cc @mathiasbynens

**Comment by existentialism** [comment]
Looks like [regenerate-unicode-properties@5.1.3](https://github.com/mathiasbynens/regenerate-unicode-properties) causes the test change, verified locally that 5.1.1 passes.

**Comment by mathiasbynens** [comment]
`Emoji_Component` support has been removed from the proposal. The test should just be removed.

**Comment by hzoo** [comment]
Can be a good first issue to remove the test then

**Comment by syldlb** [comment]
Looking for a first issue, can I take this one?

**Comment by xtuc** [comment]
Yes sure. You can join our Slack if you have questions or need some help (I'll need your email address).

**Comment by loganfsmyth** [comment]
@mathiasbynens Looking this over, I noticed the README says

> Compile [Unicode property escapes](https://github.com/mathiasbynens/regexpu-core/blob/master/property-escapes.md) (`\p{…}` and `\P{…}`) in Unicode regular expressions to ES5 or ES6 that works in today’s environments.

but this plugin appears to transform a bunch more stuff that `regexpu-core` handles that is unrelated to `\p` and `\P`, thoughts?
