### ISSUE TITLE
TypeError when compiling with webpack

### ISSUE THREAD

**Issue by edargham** [babel/babel#6538]
I am getting this error when I compile with webpack:

<img width="968" alt="screen shot 2017-10-23 at 1 40 39 pm" src="https://user-images.githubusercontent.com/29617612/31886910-fb053f02-b7fe-11e7-9840-c331e67fdbc6.png">

please help...

**Comment by nicolo-ribaudo** [comment]
Can you share your webpack configuration, babelrc and package.json?

**Comment by edargham** [comment]
**.babelrc:**

`{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "ie >= 9"]
      }
    }],
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "react-hot-loader/babel"
  ]
}`

**webpack config:**


[webpack.config.txt](https://github.com/babel/babel/files/1406915/webpack.config.txt)


**package.json**

[package.txt](https://github.com/babel/babel/files/1406918/package.txt)

**Comment by loganfsmyth** [comment]
```
    plugins: [
        ignore,
        babelPluginTransformObjectRestSpread
      ],
```
is in the wrong place, it should be in the same object as `presets`

**Comment by loganfsmyth** [comment]
Actually I should be clearer, `ignore` is in the right place, but you should have
```
{
    presets:['react']
    plugins: [babelPluginTransformObjectRestSpread]
}
```
and you can also just do
```
{
    presets:['react']
    plugins: ['transform-object-rest-spread']
}
```

**Comment by edargham** [comment]
Okay perfect if worked! ty
