### ISSUE TITLE
compile error when use babel-plugin-transform-do-expressions

### ISSUE THREAD

**Issue by stoneyallen** [babel/babel#6544]
Choose one: is this a bug report or feature request?

### Input Code

```js
let a = do {
      if(x > 10) {
        'big';
      } else {
        'small';
      }
};
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["react", "latest"],
  "plugins": ["transform-do-expressions"]
}
```

### Expected Behavior

compile sucessfully

### Current Behavior

has a error warning:
Module build failed: SyntaxError: Unexpected token, expected ;

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 7.6.0
| npm              | 4.1.2
| Operating System | macOS

**Comment by loganfsmyth** [comment]
Please include the full error output. Just the message isn't enough. If you're using Webpack, it sounds like your Webpack config is has issues.

**Comment by stoneyallen** [comment]
yes,my project is compiled by Webpack,but I just rebuild a new project without webpack.I just use babel-core,and my code is blow:

```js
const {transform,generate}=require('babel-core');
const myPlugin=require('./1.js');

var es5Code = transform(code, {})
console.log(es5Code.code);
```

```js
let a = do {
    if(x > 10) {
      'big';
    } else {
      'small';
    }
  };
```
and then,I get the result:
```js
/Users/jianshi/Desktop/1/1.js:1
(function (exports, require, module, __filename, __dirname) { let a = do {
                                                                      ^^
SyntaxError: Unexpected token do
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jianshi/Desktop/1/compile.js:2:16)
    at Module._compile (module.js:571:32)
```
the babel config is like this:
```js
{
    "plugins": [
        "transform-do-expressions"
    ]
}
```

**Comment by stoneyallen** [comment]
Thanks,I found that this error is related with webpack, because I rebuild a new project without webpack, like this:
```js
const {transformFile}=require('babel-core');

var es5Code = transformFile('./1.js', {plugins: ["transform-do-expressions"]},(err,result)=>{
    console.log(result.code);
})
```
```js
let a = do {
    if(x > 10) {
      'big';
    } else {
      'small';
    }
  };
```
so I can get correct result,But I am so doubt that why my config is not correct in webpack.
.babelrc
```js
{
  "presets": ["react", "latest"],
  "plugins": ["transform-do-expressions"]
}
```
and I think this problem is caused by execution sequence of  plugins.Can you give some suggestions, thank you so much!

**Comment by linonetwo** [comment]
I'm using ```"babel-standalone": "^6.26.0"```, and ```"babel-preset-stage-0": "^6.24.1",``` where
```javascript
do {
  if(false) { 'aaa' }
  else if(true) { 'bbb' }
  else { 'ccc' }
}
```
will throw
```
SyntaxError: unknown: Unexpected token, expected while (7:0)
  5 |   else { 'ccc' }
  6 | }
> 7 | 
    | ^
```

**Comment by linonetwo** [comment]
I get to know why,

```javascript
true ? do {
  if(false) { 'aaa' }
  else if(true) { 'bbb' }
  else { 'ccc' }
} : ''
```
is working, while
```
do {
  if(false) { 'aaa' }
  else if(true) { 'bbb' }
  else { 'ccc' }
}
```
will eager for a 'while'.

Is this a bug?

**Comment by tanhauhau** [comment]
@linonetwo yes you are right, that's because the ambiguity between do-expression and do-while.
do expression cannot be a statement by itself. a better workaround would be

```
(do {
  if(false) { 'aaa' }
  else if(true) { 'bbb' }
  else { 'ccc' }
})
```
