### ISSUE TITLE
Try it out doesn't respect presets from URI

### ISSUE THREAD

**Issue by xixixao** [babel/babel#6545]
Go to https://babeljs.io, click on Try it out, check react under Presets, reload the page, the preset is gone. Hence, the link to babel from https://reactjs.org/docs/jsx-in-depth.html is broken and cannot be fixed.

**Comment by existentialism** [comment]
@babel-bot move to babel/website

**Comment by existentialism** [comment]
@xixixao thanks for the report, we'll get this fixed!
