### ISSUE TITLE
Can't install the newly moved @babel/preset-env

### ISSUE THREAD

**Issue by chrisregner** [babel/babel#6547]
Choose one: is this a bug report or feature request?

A Bug. Can't install the latest and newly moved @babel/preset-env

### Input Code

```
// copied from https://github.com/babel/babel/tree/master/experimental/babel-preset-env#install
// tried the npm counterpart and failed too
yarn add @babel/preset-env --dev
```

### Babel Configuration (.babelrc, package.json, cli command)

not applicable, I think.

### Expected Behavior

Expected to be installed/added

### Current Behavior

I get this error instead:
![image](https://user-images.githubusercontent.com/26005158/31944643-59c04b30-b8ff-11e7-956f-f54d1fe98e5d.png)

### Possible Solution

Sorry, don't know.

### Context

I think it is self-explanatory.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  n/a
| node             | 8.7.0
| npm              | 5.5.1
| yarn             | 1.2.1
| Operating System | Win 10

**Comment by nicolo-ribaudo** [comment]
It has not been released yet, you should still use `babel-preset-env`

**Comment by sparcut** [comment]
Arrg, why does it say to use it's been moved! Should be warned that `babel-preset-env` is still the current version.

**Comment by loganfsmyth** [comment]
@sparcut Sorry about the confusion. Could you clarify which page you were looking at? If you were looking at the repository itself, then I'd definitely recommend explicitly looking at the 6.x branch. In 6.x though the `env` preset is in a separate repository anyway though.

**Comment by sparcut** [comment]
@loganfsmyth Sorry, I am referring to the [`babel-preset-env`](https://github.com/babel/babel-preset-env),
as it says at the top that its been moved to the main repo. Thus, I'd assumed it could be installed with the provided command in [`@babel/preset-env`](https://github.com/babel/babel/tree/master/experimental/babel-preset-env).

From what I understand at the moment, `preset-env` is _moving_ to the main babel repo but staying as separate package, and `@babel/preset-env` with be usable to install it next release?

**Comment by loganfsmyth** [comment]
The `master` branch of this repository is for Babel's beta releases, so `@babel/preset-env` will exist on npm after our next release, but it will be version `7.0.0-beta.4`. If you're using Babel 6, which I'd assume you are, you'd want to just use `babel-preset-env`.

**Comment by loganfsmyth** [comment]
@hzoo maybe we can clarify that in the README?
