### ISSUE TITLE
how to upgrade dependency 'minimatch' when it's deprecated

### ISSUE THREAD

**Issue by MAYDAY1993** [babel/babel#6553]
### Your Environment

| software         | version(s)
| ---------------- | -------
| node             | 6.11.2
| npm              | 4.6.1
| Operating System | Mac ox

Hi, I came up a problem when I run 'npm install' to build my app ,from the dependency tree we can see as follows:

![screen shot 2017-10-25 at 3 54 05 pm](https://user-images.githubusercontent.com/14831051/31987128-7506e878-b930-11e7-9997-3a8463ac8a90.png)
 
there are two versions' minimatch and I want to upgrade,but I'm not sure if it is safe to upgrade minimatch ,do I have to upgrade bable-core to some version or not.Thank you for suggestions 😄

**Comment by keithamus** [comment]
Hey @MAYDAY1993 thanks for the issue!

It is completely safe to upgrade `minimatch` at your leisure; `npm` will be able to correctly pick the right versions for both your app and babel. Don't worry about that log 😄

I do not think this is an issue with babel and so @babel/babel can close this.

**Comment by MAYDAY1993** [comment]
@keithamus hi, perhaps  I didn't express my doubt clearly.My question is ,since bable-core is dependent on two versions' minimatch, and it is deduped ,so I want to upgrade bable-core to some version to upgrade minimatch to 3.0.2 or higher,because I CAN'T manually upgrade minimatch ,it is because install bable-core that thus install minimatch, so what version can I upgrade bable-core to avoid deduping minimatch dependency.thank you .

<img width="827" alt="25" src="https://user-images.githubusercontent.com/14831051/32032964-698ece26-b9cf-11e7-8856-66bcd7bcbca0.png">

**Comment by loganfsmyth** [comment]
The danger of a DoS attack is if you allow inputs to pass through from an attacker into a library. None of the inputs to minimatch via Babel are things you'd expose to a user, so there's no security risk you need to worry about. The fact that there are multiple versions of the packages installed is a non-issue for usage in Babel.

**Comment by nicolo-ribaudo** [comment]
@MAYDAY1993 Have you tried updating `babel-core`? v6.9.0 is really old, minimatch has been updated in Babel 6.10.4 (but I'd recommend install v6.26.0)

**Comment by MAYDAY1993** [comment]
@nicolo-ribaudo oh ,I updated `babel-core` to `6.26.0` and `minimatch` version became  `3.0.4`,thank you for your suggestion. 😃
