### ISSUE TITLE
Incorrect compilation of class properties

### ISSUE THREAD

**Issue by andyjansson** [babel/babel#6555]
**bug report**

### Input Code

```js
class Foo {
	constructor(opts = {}) {
      	for (const key in opts) {
            this[key] = opts[key];
        }
    }
}

class Bar extends Foo {
 	baz = "bat";

	constructor(opts = {}) {
      super(opts);
    }
}

const bar = new Bar({ baz: "quux" });
const bazValue = bar.baz;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{ "plugins": [ "transform-class-properties" ] }
```

### Expected Behavior
`bazValue` should equal `quux`.

### Current Behavior
`bazValue` equals `bat`.

| software         | version(s)
| ---------------- | -------
| Babel            |  6.25.0
| node             | 7.10.0
| npm              | 4.2.0
| Operating System | Windows 10

**Comment by loganfsmyth** [comment]
This is expected behavior. The parent constructor runs, assigns `this['bazValue'] = "quux";`, and then the child class's class property is evaluated and assigns the value to `bat`.

**Comment by andyjansson** [comment]
Surely that can't be the expected spec behaviour?

**Comment by loganfsmyth** [comment]
Class properties are initialized at the end of each call to `super` after the parent constructor runs.
