### ISSUE TITLE
Feature request: allow passing config file to babel-node

### ISSUE THREAD

**Issue by Billy-** [babel/babel#6560]
I would like to switch from babel-register to babel-node, however there is one limitation I am facing; babel-register allows passing config on the fly, allowing things like using a function as the `ignore` parameter. It would be good if you could pass the name of a file as a `--config` option to `babel-node` which then gets required and assumes the default export is the desired config. This can then be merged with any command line params.

**Comment by Billy-** [comment]
I had a quick try at hacking something in. I did it in the GitHub editor so it's totally untested, but it should work.

**Comment by Bastorx** [comment]
babel-cli use --config-file
It should be interesting to normalize it

What's the advancement of this issue?
