### ISSUE TITLE
Emitting interop require wildcard function when transpiling TypeScript imports differs from the TS idiom.

### ISSUE THREAD

**Issue by phyllisstein** [babel/babel#6562]
### Choose one: is this a bug report or feature request?
Bug report.

### Input Code

```ts
import * as chroma from 'chroma-js'
import { inspect } from 'util'

console.log(inspect(chroma))
```

### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      },
      "loose": true
    }],
    "stage-0",
    "typescript"
  ]
}
```

### Expected Behavior
If I'm understanding the TypeScript idiom correctly, its use of `import *` isn't quite the same as Babel's---or, for that matter, the spec's. `tsc` transpiles the code snippet above to look like this:

```js
"use strict";
exports.__esModule = true;
var chroma = require("chroma-js");
var util_1 = require("util");
console.log(util_1.inspect(chroma));
```

...emitting a straightforward `require` statement for the whole Chroma package and placing its exports at the top level of the script's `chroma` variable. Babel, on the other hand, emits this:

```js
"use strict";

var chroma = _interopRequireWildcard(require("chroma-js"));

var _util = require("util");

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

console.log((0, _util.inspect)(chroma));
```

...which stashes the export on `default` key. If I try to actually use the export in TypeScript, it works as documented; if I try to use it after running it through Babel's TypeScript preset, it fails.

Normally I'd be happy to just replace the wildcard imports with what's specced and expected by Babel, but that breaks TypeScript's typing information in my lovely editor and obviates the use of TS in the first place.

### Current Behavior
☝️ That.

### Possible Solution
In all honesty I'd say this is a bug in Babel's TypeScript preset. I would suggest that the correct behavior is the one that maintains parity with `tsc`, and that that behavior is to emit an `_interopRequireDefault` for wildcard imports.

### Context
I've been migrating a couple of different code bases to TypeScript, and hoping to take advantage of the new Babel integration both to avoid failing builds for type drifts and to continue enjoying Babel's wonderful configurability, lovely emitted code, and thriving plugin ecosystem. Mostly I'm in it for the editor integrations at time of development, which won't work if I deviate from the TypeScript module idiom.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.3
| node             | v8.8.0
| npm              | v5.5.1
| Operating System | macOS v10.13

**Comment by nicolo-ribaudo** [comment]
Babel outputs that code because it is the most similar to the spec.

If you use `import * as chroma from "chroma-js";`, `chroma` must be an object.
Looking at the chroma documentation I think it should be a function, so the only right way to import it is `import chroma from "chroma-js"`.

Also, it is officially supported (https://github.com/gka/chroma.js/commit/ea2bd0129f513d00dda5133d626c6ab667b26371)

**Comment by Kovensky** [comment]
If you are writing typescript that targets commonjs, you should use the `import foo = require('bar')` syntax.

However, if you are targeting es2015/esnext for your emit, you're kinda stuck with `import`s only -- for now, we are stuck with using `--allowSyntheticDefaultImports` and making sure we write our imports correctly.

TypeScript will _have_ to fix their stuff eventually; but I suspect they are waiting until they start a big sprint for a 3.0 release.

@nicolo-ribaudo that is most definitely **not** how you add a default export 🤦‍♂️

**Comment by phyllisstein** [comment]
Agreed that it's not right, I was very careful to be no more generous than "idiomatic" 😛 . Thanks for the suggestion about `allowSyntheticDefaultImports`, that seems to help resolve the conflict! Probably more sensible to hew to the ES spec than to the TypeScript patterns anyway. Appreciate the feedback.
