### ISSUE TITLE
Named exports should take priority over star exports

### ISSUE THREAD

**Issue by gdborton** [babel/babel#6564]
Choose one: is this a bug report or feature request?

Bug report.

### Input Code

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAG2PAnnAvHAZgVwHYDGMAlhHgBQCUA3gL4DcAUKJLHAFTZQQC2cA5ADoA9AEMAzgBMs_ekA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015&targets=&version=6.26.0

```js
export let y = function(){};
export * from './asdf';
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["2015"]
}
```

### Expected Behavior

As per the [ResolveExport](https://tc39.github.io/ecma262/#sec-resolveexport) step 4, named exports should be taking priority over star exports.

### Current Behavior

As is, the keys from * exports are iterated over and defined in an immutable way on the `exports` object before named exports are added.

### Possible Solution

Moved named exports up in the transpiled output, and add a check in the * export loop to check whether the exported keys are already being used.

```js
var y = exports.y = function y() {};
Object.keys(_asdf).forEach(function (key) {
  if (key === "default" || key === "__esModule" || Object.prototype.hasOwnProperty.call(exports, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _asdf[key];
    }
  });
});
```

### Context

This isn't affecting me yet, I just stumbled on it while trying to understand how import/export work in greater detail.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  repl
| node             | repl
| npm              | repl
| Operating System | repl

**Comment by loganfsmyth** [comment]
This has been addressed in 7.x already. The 7.x output for your snippet is
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var _exportNames = {
  y: true
};
exports.y = void 0;

var _asdf = require("./asdf");

Object.keys(_asdf).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _asdf[key];
    }
  });
});

var y = function y() {};

exports.y = y;
```
so it explicitly checks `_exportNames`

**Comment by ljharb** [comment]
Any chance of backporting?

**Comment by loganfsmyth** [comment]
I think technically an old PR exists for 6.x somewhere, but I think we've been hoping to avoid landing more backports in favor of focusing on 7.x.
