### ISSUE TITLE
Warn when loading a plugin that doesn't look like a plugin

### ISSUE THREAD

**Issue by sw-yx** [babel/babel#6565]
Choose one: is this a bug report or feature request? Feature request

### Summary
In this Twitter thread: <https://twitter.com/left_pad/status/923668076620664832> @hzoo and others discussed why @wesbos was confused when trying to use babel-preset-styled_components. The poor DX came from the fact that babel automatically loads the `styled-components` if `babel-preset-styled-components` is not installed, and `styled-components` is not a babel plugin. This seems to be a common error especially with react and other similar JS modules that have matching babel preset names. There is an easy opportunity here to introduce a warning that should materially improve DX when dealing with this bug.

### Possible Solution
I am not yet familiar with babel internals or the interfaces of plugins. but basically if we are in the path of loading the base module -AND- an error like this happens we could print a warning. A poorer solution but its there if we need it: check a registry at runtime to see if `babel-preset-x` exists and is not installed when loading `x` as a plugin, then warn.

### Context
<https://twitter.com/left_pad/status/923668076620664832> real world example, very senior developer

### Your Environment
 n/a

**Comment by loganfsmyth** [comment]
This should be fixed in 7.x via https://github.com/babel/babel/pull/5547 which made the resolution of plugins a 1-1 deterministic mapping rather than trying multiple possibilities. I agree it's definitely a pain point in 6.x.
