### ISSUE TITLE
`babel-node --version` is super slow (>40 secs)

### ISSUE THREAD

**Issue by Kosta-Github** [babel/babel#6568]
Bug report

```Shell
$ time DEBUG=* babel-node --version
6.26.0

real	0m40.732s
user	0m1.489s
sys	0m0.456s
```
I already tried to reinstall `node`, `npm`, and `babel` several times, and the only global installed packages are `npm` and `babel-cli`:

```Shell
$ node --version
v8.7.0

$ npm --version
5.5.1

$ npm list -g --depth=0
/usr/local/lib
├── babel-cli@6.26.0
└── npm@5.5.1
```
Note that the commands above have been executed in my home folder which does not contain any `node_modules` subfolder.

The same slow startup behaviour (>30 secs warmup time/delay) can be observed when starting `mocha` tests which require `babel-core/register` and `babel-polyfill`.

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 8.7.0
| npm              | 5.5.1
| Operating System | OSX (Sierra)

Any advice help is very much appreciated!

**Comment by nicolo-ribaudo** [comment]
Related: https://github.com/babel/babel/issues/5702 (but 40s is a lot worst than 0.4s)

**Comment by hzoo** [comment]
> node bin/babel-node.js --version  0.23s user

**Comment by hzoo** [comment]
> node bin/babel-node.js --version  0.23s user

It's faster in v7.
