### ISSUE TITLE
Remove extraneous console output when running preset-env tests

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6571]
> Didn't look into this much though (it's with the debug option which prints to the console though and it must be doing that

We're getting this from the @babel/preset-env test output, and it shouldn't be there (if there is a way to mock/remove from console output we should do it

```
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "55"
}
```

**Comment by xjlim** [comment]
i'd like to work on this
