### ISSUE TITLE
babel-plugin-async-to-generator should add #__PURE__ comment

### ISSUE THREAD

**Issue by winstonewert** [babel/babel#6572]
Request: add pure comments to async function helpers to aid in dead code elimination.

### Input Code

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsLwKbKgCwAVgBzbAEWGWAAoAHU7AShgG8AoGGAJ1wW6ysAvuyFA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0

```js
async function fetchPageData(page) {
  return {}
}
```

### Expected Behavior
Generated code should be able to be removed as dead by uglifyjs/similiar if the async function is not called.

### Current Behavior
```js
var fetchPageData = function () {
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(page) {
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            return _context.abrupt("return", {});

          case 1:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function fetchPageData(_x) {
    return _ref.apply(this, arguments);
  };
}();
```

Note that while regeneratorRuntime.mark is marked as #__PURE__, the call to _asyncToGenerator and the IIFE aren't.

### Possible Solution

Generated code should start with:
var fetchPageData = /*#__PURE*/ function () {

### Context
I have a react app which runs on both client and server. However, I have various async functions that only run on the server. I want to have them removed during the minification process.

**Comment by rshah03** [comment]
Hey, I'd like to give this a shot. Any recommendations on how I would start/approach this? I'm new to open-source contributions.

**Comment by Eric-Zayas** [comment]
Hello, It seems no one has offered to provide a solution. Would you mind if I had a go at it? It is my first time contributing to open software, but I think I can manage something. :)

**Comment by nicolo-ribaudo** [comment]
@Eric-Zayas Go for it!

**Comment by kzc** [comment]
@Eric-Zayas Perhaps you could try something like this?
```patch
--- a/packages/babel-helper-remap-async-to-generator/src/index.js
+++ b/packages/babel-helper-remap-async-to-generator/src/index.js
@@ -4,6 +4,7 @@ import type { NodePath } from "@babel/traverse";
 import wrapFunction from "@babel/helper-wrap-function";
 import * as t from "@babel/types";
 import rewriteForAwait from "./for-await";
+import annotateAsPure from "@babel/helper-annotate-as-pure";
 
 const awaitVisitor = {
   Function(path) {
@@ -71,4 +72,5 @@ export default function(path: NodePath, file: Object, helpers: Object) {
   path.node.generator = true;
 
   wrapFunction(path, helpers.wrapAsync);
+  annotateAsPure(path.isDeclaration() ? path.get("declarations.0.init") : path);
 }
```
I didn't run the test suite due to unrelated errors in my environment.

**Comment by Andarist** [comment]
@Eric-Zayas Have you found some time to work on the issue? Should we keep it as claimed for you? No rush, just let us know :)

**Comment by satya164** [comment]
I'd like to work on this if you don't have time @Eric-Zayas

**Comment by xtuc** [comment]
@Eric-Zayas FYI a PR has been merged for this. Sorry if you was working on it but you didn't answer.
