### ISSUE TITLE
`sourcemaps: "inline"` ignored when "inputSourceMap" specified

### ISSUE THREAD

**Issue by cspotcode** [babel/babel#6577]
This is a bug.  Using the Babel API, when specifying an `inputSourceMap`, the `sourcemaps` option is forced to `true`, ignoring if it was set to `"inline"` or `"both"`.

### Input Code

```js
import * as ts from 'typescript';
import * as babel from 'babel-core';

const input = `
    export default 0;
`;
// Create an input sourcemap (doesn't have to be via typescript)
const tsOutput = ts.transpileModule(input, {
    fileName: 'input.ts',
    compilerOptions: {sourceMap: true}
});

function transpile(withInputSourceMap) {
    const babelOutput = babel.transform(tsOutput.outputText, {
        sourceMaps: 'inline',
        inputSourceMap: withInputSourceMap ? JSON.parse(tsOutput.sourceMapText!) : undefined
    });
    console.log(babelOutput.code);
    console.log(babelOutput.map);
}

console.log('====Transpiling====');
transpile(false);
console.log('====Transpiling, passing an inputSourceMap====');
transpile(true);
```

### Expected Behavior

In both cases, babel returns an inlined, base64-encoded sourcemap.

### Current Behavior

In the second case, babel does not return an inlined sourcemap.

### Possible Solution

I believe this code is to blame: https://github.com/babel/babel/blob/6.x/packages/babel-core/src/transformation/file/index.js#L141-L143

### Context

I'm using a babel transformation to post-process compiled Typescript.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-core            |  6.26.0
| typescript    | 2.5.3
| node             | 8.7.0
| npm              | 5.5.1
| Operating System | Windows 10

**Comment by xtuc** [comment]
Closing, out of scope for now.
