### ISSUE TITLE
babel-preset-env: Classes should not be transformed for latest Opera versions

### ISSUE THREAD

**Issue by tech4him1** [babel/babel#6583]
Choose one: is this a bug report or feature request?
bug report

### Input Code

https://babeljs.io/repl/#?babili=false&browsers=Opera%2043&build=&builtIns=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoa14A8wFsAHEeACgEo0BfdKoA&debug=true&circleciRepo=&evaluate=false&lineWrap=true&presets=env&targets=&version=6.26.0

### Expected Behavior

Classes should not be transformed be `babel-preset-env` for versions of Opera that support them natively.

### Current Behavior

Classes are transformed to ES5 for the latest Opera versions.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 (REPL)
| node             | REPL
| npm              | REPL
| Operating System | REPL

**Comment by Kovensky** [comment]
The problem is that Opera is not recognized at all as a target. 

Compare `Opera 43`:
![image](https://user-images.githubusercontent.com/73085/32140272-3db80cf0-bc9e-11e7-9f74-05ea36ce4896.png)

and `Chrome 58`:
![image](https://user-images.githubusercontent.com/73085/32140275-6f244c90-bc9e-11e7-8aca-1b3bafec1476.png)

**Comment by existentialism** [comment]
This likely depends on what version of browserslist (and subsequently caniusedb) is installed. Unfortunately, the version of preset-env on the REPL is fairly outdated (which we hope to get fixed soon via https://github.com/babel/babel/pull/6438)

Locally:

package.json

```json
{
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  }
}
```

.babelrc

```json
{
   "presets": [
       ["env", {
           "targets": {
              "opera": 43
           },
           "debug": true
       }]
    ]
}
```

Debug output:

```sh
Using targets:
{
  "opera": "43"
}

Modules transform: commonjs

Using plugins:
  syntax-trailing-function-commas {"opera":"43"}
```

`npm ls browserslist`:

```sh
└─┬ babel-preset-env@1.6.1
  └── browserslist@2.5.1
```

**Comment by tech4him1** [comment]
@existentialism Good point, I should have checked the debug output on my project first. I'm going to close this issue. Here is a new issue with my actual problem: #6643. Thank you for your help!
