### ISSUE TITLE
`babel --watch` does not have good unix-style stdout support

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#6590]
Choose one: is this a bug report or feature request? **Feature request**

`babel --watch` should write to stdout (1) when a file has changed and (2) when a file has finished compilation. 

At the moment, the only output when a file changes is something like this:

`@src/index.js -> @target/index.js`

I would like to make a request that Babel adds more stdout output so that tools in the ecosystem can hook into `babel --watch` more easily. Here is my basic proposal:

_Upon a file change, write to stdout:_

> `babel --watch` will attempt to transpile the following file
> src: x
> destination: y 

_If the transpilation failed for some reason, write to stdout and stderr, the same message:_

> `babel --watch` failed to transpile the following file
> src: x
> destination: y 
> reason: [the error stack]

_if the transpilation succeed_

> `babel --watch` successfully transpiled the following file
> src: x
> destination: y 

**If you want, more verbose output could simply be turned on with a flag, such as --verbose or -v**

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |   6.4.0
| node             |  8.2.3
| npm              |  4.6.1
| Operating System |  Darwin

**Comment by ORESoftware** [comment]
My thinking with regard to the formatting of the above output, it's both human readable and machine readable, however another option would be to use a flag to make the output machine readable, something like this:

`babel -w --machine-stdio`

in that case, writing JSON to stdout/stderr, makes it much easier to read if other processes want to act on the output of `babel -w`.

**Comment by aprieels** [comment]
Hi,

Would that be an interesting issue for a first contribution? If so, I'd be happy to give it a try!

**Comment by ORESoftware** [comment]
@aprieels yes that would be great, I am going to include all the need info here. Like I said, when `babel -w` first sees a file change, it would be useful to write a message to stdout, something like:

```js
const data = {'source': '@babelwatch',event: 'file_change', filePath: filePath, willTranspile: true/false};
console.log(JSON.stringify(data);
```

then after transpilation finishes, write something like this to stdout:

```js
const data = {'source': '@tscwatch', event: 'compilation_complete', errors: null / errors:[]};
console.log(JSON.stringify(data));
```


if it's behind a flag (`--machine-stdio`) then it won't affect any current users, so should be safe.
I need a truly unique field value like '@babelwatch' so that I know that the JSON is coming from a certain process.  In general, it's possible to be parsing more than one JSON stream from a process, so having a unique field in each JSON object makes this better.

**Comment by loganfsmyth** [comment]
What are your thoughts on https://github.com/babel/babel/pull/6320 ? I have not had time to think about this kind of thing.

**Comment by ORESoftware** [comment]
@loganfsmyth thanks, I commented on that thread, it might solve this issue

**Comment by ORESoftware** [comment]
It looks like that PR adds this output:

```js
const startMsg = "Detected change to watched files. Rebuilding..";
const endMsg = "Rebuild complete. Waiting for changes.";
```

the problem that @jmunson is solving is the same problem that I have.

the one thing that I would like to add to tools in general is JSON output to stdout that is more machine readable. But it's not strictly imperative for my use case. @jmunson's PR should solve my current problem.

**Comment by xtuc** [comment]
Closing, out of scope for now.
