### ISSUE TITLE
Inheritance doesn't work

### ISSUE THREAD

**Issue by novellizator** [babel/babel#6592]
# BUG REPORT

Inheritance doesn't work.

### Input Code

```
class NetworkError extends Error {
  constructor(...params) {
    super(...params)
  }
}

class InvalidTokenError extends Error {
  constructor(...params) {
    super(...params)
  }
}
let ee = new InvalidTokenError()
console.warn('check: ', ee instanceof NetworkError, ee instanceof InvalidTokenError, ee instanceof Error)
// returns false false true
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["react-native"]
}

```

### Expected Behavior

should return true false true

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

**Comment by xtuc** [comment]
> Built-in classes such as Date, Array, DOM etc cannot be properly subclassed due to limitations in ES5

See https://babeljs.io/docs/usage/caveats/#classes.
