### ISSUE TITLE
Include more types in isConstantExpression logic

### ISSUE THREAD

**Issue by Andarist** [babel/babel#6645]
Polish [isConstantExpression](https://github.com/babel/babel/blob/a1c7449a9276987ead4788c4333190c922ba0658/packages/babel-traverse/src/path/introspection.js#L402) used [here](https://github.com/babel/babel/blob/a1c7449a9276987ead4788c4333190c922ba0658/packages/babel-plugin-proposal-class-properties/src/index.js#L97). Many useful cases to polish can be found in [this](https://github.com/babel/babel/blob/a1c7449a9276987ead4788c4333190c922ba0658/packages/babel-traverse/src/path/evaluation.js#L73)

**Comment by xtuc** [comment]
Closing, out of scope for now.
