### ISSUE TITLE
parameter spread on import results in usage of undeclared variable

### ISSUE THREAD

**Issue by jeysal** [babel/babel#6647]
### Bug Report
In the current 7.0.0-beta.5, a combination of parameter spread and an imported variable causes usage of an undeclared variable as the first argument to `apply` due to a missing variable name substitution
### Input Code
```javascript
import abc from 'abc';
const arr = [1, 2, 3];
abc.xyz(...arr);
```

### Babel Configuration (.babelrc, package.json, cli command)
Used REPL. Also tested locally with:
```bash
npx babel --preset=env index.js
```
```json
{
  "presets": [
    [
      "env or @babel/preset-env, depending on beta version",
      {
        "useBuiltIns": "usage",
        "targets": {
          "browsers": ["> 2%"]
        }
      }
    ]
  ],
  "plugins": []
}
```

### Expected Behavior
Something equivalent to this output from 6.26.0 (value of the default import passed as first argument to `apply`)
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAQwEYGM4DMoRHA5MlXAbgCgUIA7AZ3gSijgF44BtARgBo4AmLgZgC6pAgDoAHgE8AXgAoR8ulACUpIA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0

### Current Behavior
Variable name not substituted => undeclared variable passed as first argument to `apply` => error
https://babeljs.io/repl/build/5552#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAQwEYGM4DMoRHA5MlXAbgCgUIA7AZ3gSijgF44BtARgBo4AmLgZgC6pAgDoAHgE8AXgAoR8ulACUpIA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&version=7.0.0-beta.5

### Your Environment
In addition to the REPL, I've tested this with the CLI.
7.0.0-beta.1 still works: `_abc2.default.xyz.apply(_abc2.default, arr);`
7.0.0-beta.2 is broken: `_abc.default.xyz.apply(abc, arr);`

**Comment by hzoo** [comment]
[Minimal repro link (even in loose mode)](https://babeljs.io/repl/build/master#?babili=false&browsers=Opera%2043&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAQzgMyhEcDkDMG4BQ-CAdGFAKYBuw5A7gBTFMDGAlAUA&debug=true&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015-loose&targets=&version=7.0.0-beta.5)

```js
import a from 'a';
a.preview(...c);
```

```js
"use strict";

var _a = _interopRequireDefault(require("a"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

_a.default.preview.apply(a, c);
```
