### ISSUE TITLE
Implicit return of JSX conflicts with ES7 bind operator

### ISSUE THREAD

**Issue by kyleramirez** [babel/babel#6648]
#### This is a bug report.

I'm running into an issue shortly after switching to `babel-preset-env` from `babel-preset-es2015`, where I noticed some props were never being transformed from JSX to `React.createElement` calls. I realized this is an issue due to my use of the ES7 bind operator, although I'm not using it incorrectly. If you write a fat arrow function that implicitly returns JSX, and you have a bind operator in one of the props, it will completely remove that prop after transformation. This is not expected.

Take the following example:
### Before (in source code)
```js
function toClassName() {
  return this.filter(Boolean).join(" ")
}

function BlueBox({ className }) {
  return (
    <div className={["bg-blue", className]::toClassName()} />
  )
}

const YellowText = () => (
  <BlueBox
    className={["yellow"]::toClassName()}
  />
)
```

### After transformations
```js
function toClassName() {
  return this.filter(Boolean).join(" ");
}

function BlueBox({ className }) {
  var _context;

  return React.createElement("div", { className: (_context = ["bg-blue", className], toClassName).call(_context) });
}

const YellowText = () => {
  var _context2; //<--- What in the world!

  return <BlueBox />; //<--- Not even transformed in the REPL!
};
```
You can see it for yourself in the [REPL](https://babeljs.io/repl/#?babili=false&browsers=last%201%20Chrome%20version&build=&builtIns=false&code_lz=FAMwrgdgxgLglgewgAhggwgGwIYGdcBy2AtgKYAUAlMgN7DLIBOpMYjKMAFnLgHQhxMMUo3IAhBAkylsESrwBWCOBHIAiZGsrAAvsFCRYiFGMxhSEgB7kayKDnxEyyHdToNmrdsnL0GyAB4AEzgANzsHQhJSAF4aAG01ACMAcwBaJLNSNQAaCLwosgBdAC4StCwCpwpKHWQAegA-P209YCgkXBhkAE1STEwEAHcAFVJLbpifahjGnz8A03MrPwZ7Kui4xIBPfsGhtVLyjEjqqj0GJuBtIA&debug=true&circleciRepo=&evaluate=true&lineWrap=false&presets=react%2Cstage-0%2Cenv&targets=&version=6.26.0)

I can get around this issue by not doing an implicit return.
```js
// Where this
const YellowText = () => {
  return(
    <BlueBox
      className={["yellow"]::toClassName()}
    />
  )
}
//Becomes this
const YellowText = () => {
  var _context2;

  return React.createElement(BlueBox, {
    className: (_context2 = ["yellow"], toClassName).call(_context2)
  });
};
```

#### Expectation
I would expect it to be able to handle this syntax without ignoring the props. Any suggestions are welcome, however I would like to use this syntax, as it makes perfect sense to me. If it's just not ready, it's not ready.

### Babel configuration in `package.json`
```js
{
  loader: "babel-loader",
    options: {
      presets: [
        [
          "env",
          {
            "modules": false,
            "targets": {
              "browsers": ["last 1 Chrome version"]
            },
            include: ["transform-es2015-classes"]
          }
        ],
        "stage-0",
        "react"
      ],
      plugins: development ? ["react-hot-loader/babel"] : ["transform-runtime"]
    }
}
```

**Comment by existentialism** [comment]
@kyleramirez due to plugin ordering, since items in the `include` key get appended at the end :( if you remove the targets + include keys (or adjust targets so you don't need to use the include key) it transforms just fine.

I'll push a PR with a temporarily fix for this by ensuring any items in the `include` key get added in the original order, at least until we get https://github.com/babel/babel/issues/5854 resolved.
