### ISSUE TITLE
Behavior of spread operator within Set() constructor (loose mode)

### ISSUE THREAD

**Issue by jasonphillips** [babel/babel#6649]
There appears to be a bug in transformation of spread operator within Set() constructor in loose mode.

When using spread syntax to create a new Set containing elements of a prior Set, the resulting code is not functionally equivalent, and creates a Set containing the original Set as an element.

### Input Code

```js
const priorSet = new Set(['a','b']);
const withSpread = new Set([...priorSet, 'e']);
```

This code should create a new set containing the elements of the prior set (and another element), and works normally when typed as above in node environments that support spread / Set(), without babel.

### Babel Configuration

```json
{
  "presets": [
    ["env", {
      "loose": true
    }]
  ]
}
```

### Expected Behavior
Valid syntax that produces a new Set() containing the elements of the prior set (and, in this case above, one more element).

### Current Behavior

Babel produces the following code:

```js
var withSpread = new Set([].concat(priorSet, ['e']));
```

- which ends up creating a Set() containing the first Set.

### Context

Is it simply not supported to use Set() / spread liberally in loose mode? I've found ways to merely rewrite my code (`new Set(Array.from(priorSet).concat(['e']));`, but it's surprising to see something not throw an error and instead produce radically different behavior in the built application.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-cli            |  6.26.0
| babel-preset-env | 1.6.1

**Comment by loganfsmyth** [comment]
The `loose` flag for spread explicitly means "I will only spread arrays". https://babeljs.io/docs/plugins/transform-es2015-spread/#optionsloose Generally I'd only recommend using `loose` if you plan to only write ES5-like code.

**Comment by jasonphillips** [comment]
Thanks - so, it is evidently the case that one must carefully limit relying on certain syntax in loose mode. Good to know; in this case, a large, pre-existing project (https://github.com/gatsbyjs/gatsby) was set to `loose` mode, and a PR was added which used the Set() syntax at one point -- and of course, it tested fine, since the tests run against the src rather than the babel-compiled output code. The result of this silent problem was code that tested yet broke down the line when distributed via npm.

I suppose I would have expected babel to at least throw an error, or warning, during build to indicate that a type of syntax was being used which could not be translated reliably under the current configuration; but this simply might not be possible from what I'm hearing. 

So perhaps the takeaway is that projects in `loose` mode should seek out linter rules to prevent these edge cases from creeping into the code? I haven't sought out an appropriate lint that would flag this case.

**Comment by Andarist** [comment]
> and of course, it tested fine, since the tests run against the src rather than the babel-compiled output code

To prevent such situations in the future you could tweak your test setup to test against transpiled code.

**Comment by jasonphillips** [comment]
I think it's fair to close this now, since the behavior above has been confirmed to be the current expectation of `loose` mode (meaning: there will be no warning for these edge cases, just a responsibility on the developer side to avoid any syntax falling into these gaps if loose is enabled). 

For reference, the most helpful discussion of the relative strengths (speed, chiefly) and dangers (ambiguous code, as shown above) of loose mode that I have found upon further research is in `create-react-app`:

https://github.com/facebookincubator/create-react-app/issues/198

One thing suggested by several persons in that thread, and for which I was likewise searching prior to reading it, is some safe mechanism for ensuring these cases are not allowed into in a codebase when developing with loose mode on a larger collaborative project. 

A lint rule or rules to accompany loose mode would be ideal -- but the suggestion in the thread is that static analysis could not determine most of these edge cases, so it falls somewhere between the capabilities of a linter and that of transpiling.  This means that the only route forward may be to follow the suggestion above and simply run the test suite against the final transpiled code, and thereby to always treat the build step under loose mode as a non-neutral action that has the real potential to succeed without evident build error while generating dramatic differences in functionality if edge syntax cases have crept in.
