### ISSUE TITLE
Add option to keep flow types

### ISSUE THREAD

**Issue by sebmck** [babel/babel#665]

**Comment by DavidSouther** [comment]
I've been pleased with how Traceur handles type assertions - behind a flag, either leaving them in using an Assert polyfill (eg [angular/assert](http://angular.github.io/assert/)). This allows development runtime assertions for testing, while pulling out the longer code in production.

**Comment by sebmck** [comment]
@DavidSouther #458 would be more relevant.

**Comment by DavidSouther** [comment]
Gotcha! Still a bit unsure of what the current issue list looks like here, apologies for missing that. How does this issue differ?

**Comment by sebmck** [comment]
@DavidSouther All good! Basically right now if you currently pass in flow types:

```javascript
function foo(bar: string) {}
```

They're stripped from the output:

```javascript
function foo(bar) {}
```

Basically there might be scenarios where you actually want the flow types to be retained (ie. the output would be the same as the input).

**Comment by DavidSouther** [comment]
Gotcha. Say ES7 does decide to do some kind of inference type assertions in the language itself. Or probably a dozen other reasons.

**Comment by kim3er** [comment]
If I understand correctly, this is a feature I'd like to see.

I would like to type check my ES6 code using Flow, as part of a Gulp chain. Unfortunately Flow doesn't appear to have complete support for ES6 and 6to5 strips out the type annotations, before the ES5 code is generated.

**Comment by tav** [comment]
+1 for this. I have the same use case as @kim3er.

**Comment by u-nikos** [comment]
+1 This would be awesome, it would will us to use babel as preprocessor for both Flow and TypeScript.

**Comment by sebmck** [comment]
Boom, done. In the next release you can blacklist the `flow` tranformer and output will retain all flow types:

```javascript
require("babel").transform("foo", { blacklist: ["flow"] });
```

```sh
$ babel --blacklist flow test.js
```

Ping @amasad, I believe you were interested in this at one stage. Any ideas on how to make Babel -> Flow type checking seamless and retain correct location info?

**Comment by kim3er** [comment]
Fantastic.

**Comment by amasad** [comment]
What ES6 doesn't the flow parser understand? I know it doesn't work with Es7 features like async/await but they're working on that.

Anyways you can probably write a script that compiles everything but the types and then run it through flow, parse the output, and run it through the source map to get the correct line and column number. If someone wants to write this I'm sure it'll be useful to a lot of people, and maybe babel can include it as a script with Flow as an optional dependency

**Comment by sebmck** [comment]
@amasad IIRC facebook/flow#252 and a few others, not too sure. As ES7 ramps up in frequency I don't think it'd be very practical to support such early proposals in Flow so this is just a part of future proofing Babel. There's also the [playground](https://babeljs.io/docs/usage/playground) that Flow will never support.

**Comment by tav** [comment]
Nice one @sebmck — thanks! :+1:
