### ISSUE TITLE
Support XDG basedir specification for user config files and caches

### ISSUE THREAD

**Issue by legoktm** [babel/babel#6653]
This is a re-submission of #4407.

This is a feature request.

Babel should respect the $XDG_CACHE_HOME and $XDG_CONFIG_HOME environment variables if set. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html is the full specification of how this should work. If these aren't set then Babel should fallback to some reasonable default.

### Expected Behavior
I expect that Babel respects those variables by default and tries to write cache to e.g. $XDG_CACHE_HOME/babel/cache.json.

### Current Behavior
Babel tries to write to the home directory regardless of whether it exists or is writable instead of checking the XDG variables to see if it should write somewhere else.

### Possible Solution
I believe https://www.npmjs.com/package/xdg-basedir makes it easy to use XDG, but I've never used the library before.

### Context
Wikimedia's containerized CI system runs under a user that does not have a home directory, so babel fails as that directory is not writable. We have the relevant XDG variables set, and I was expecting those to be respected. [Original ticket](https://phabricator.wikimedia.org/T179425#3724363).

**Comment by xtuc** [comment]
To determine which is the home directory for the current user we use https://github.com/sindresorhus/home-or-tmp.

It seems to me that this logic has nothing to do with Babel and it should probably be implemented in this module instead.

Could you please fill the environment section of the issue template?:



| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System | 

As far as I understand $HOME is not available at all?

**Comment by hashar** [comment]
We have tests being run in a Docker container as user `nobody`.  It has `HOME=/nonexistent` but the directory does not exist.

The test environment sets `XDG_CACHE_HOME=/cache`, which is where the build writes anything that should be cached between runs. At end of build we then save that whole directory which can be restored for the next build.

--------

Now for the code `packages/babel-register/src/cache.js` relies on [find-cache-dir](https://www.npmjs.com/package/find-cache-dir).  It seems to returns a path based on `$NODE_PATH/.cache`.   If it fails, babel fallsback to `home-or-tmp`.

[app-cache-dir](https://www.npmjs.com/package/app-cache-dir) seems to be a drop in replacement and does support `XDG_CACHE_HOME` (and `LOCALAPPDATA` on Windows) Eg:

```
appCacheDir('hi'); //=> '/Users/shinnn/.cache/hi'
 
process.env.XDG_CACHE_HOME = '/foo/bar/';
 
appCacheDir('hi'); //=> '/foo/bar/hi'
```

Would you consider replacing `find-cache-dir` by `app-cache-dir`?

**Comment by xtuc** [comment]
Closing, out of scope for now.
