### ISSUE TITLE
{modules: false, useBuiltIns: 'usage'} will insert es6 import in amd/commonjs modules.

### ISSUE THREAD

**Issue by chbdetta** [babel/babel#6658]
Choose one: is this a bug report or feature request? bug report

When using { modules: false, useBuiltIns: 'usage' }, the transformed code of a `amd` module looks like below, which webpack will complain about having both `es6` and `amd` in the same file.

### transformed codes
```js
import "babel-polyfill/lib/core-js/modules/es6.regexp.search";
import "babel-polyfill/lib/core-js/modules/es6.regexp.match";
define(function (require, exports, module) {
  require("jquery");
  var myModule = "test";
  module.exports = myModule;
});
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "loose": true,
        "useBuiltIns": "usage",
        "forceAllTransforms": true,
        "shippedProposals": true
      }
    ],
    "typescript",
    "react",
    "stage-3"
  ],
  "plugins": [
    "transform-decorators",
    ["transform-class-properties", { "loose": true }],
    "syntax-dynamic-import"
  ]
}

```

### Expected Behavior

useBuiltIns: 'usage' should try to adapt to the files module system.

### Current Behavior

All polyfill imports are es6 modules

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  ^7.0.0-beta.3
| node             | v6.11.3
| npm              | 3.10.10
| Operating System | macOS 10.13

**Comment by nicolo-ribaudo** [comment]
`"modules": false` means "Do not transform my modules to anything", so babel outputs untranspiled `import/export` statements.

Babel only supports ES modules as input (and works with commonjs, since it can be considered like ES modules with no imports/exports which are then transplied to commonjs), so you would need some custom plugin to make amd modules work with injected `import` statements.

**Comment by nicolo-ribaudo** [comment]
I have just found https://www.npmjs.com/package/amd-to-es6, it could work for you (amd -> es modules -> babel with amd output)

**Comment by chbdetta** [comment]
I understand the reason why the setting wont work but I thought the `env-preset` will magically detect the current module system and inject polyfills in corresponding way.
Thanks for the amd -> es package. I agree that updating my modules to ES6 is the proper way to solve this.
