### ISSUE TITLE
transform-export-extensions hoists spread exports above preceding imports

### ISSUE THREAD

**Issue by bernardmcmanus** [babel/babel#6660]
This is a __bug report__.

* [`transform-export-extensions`](https://babeljs.io/docs/plugins/transform-export-extensions/) hoists spread exports above preceding imports.
* export ns from tc39 proposal: https://github.com/tc39/proposal-export-ns-from
* export default from tc39 proposal: https://github.com/tc39/proposal-export-default-from

### Input Code
```js
import './_common';

// eslint-disable-next-line import/first
export * from 'react';
export default from 'react';
```

#### .babelrc
```js
{
  presets: [
    ['env', {
      targets: {
        browsers: ['last 2 versions', 'ie >= 10']
      },
      useBuiltIns: true
    }]
  ],
  plugins: [
    'transform-export-extensions'
  ]
}
```
#### cli
```bash
NODE_ENV=production babel src --copy-files --out-dir dist --source-maps inline
```

### Expected Behavior
Import order should be maintained.

### Current Behavior
This input code above currently transpiles to:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = undefined;

var _react = require('react');

Object.keys(_react).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _react[key];
    }
  });
});

require('./_common');

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// eslint-disable-next-line import/first
exports.default = _react2.default;
```

### Possible Solution
Currently we can work around this by changing `import './_common'` to `export * from './_common'` to ensure the proper order.

### Context
Import order is particularly important in this case because `./_common` contains polyfills that need to be required before `react`.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | 8.9.0
| npm              | 5.5.1
| Operating System | OSX 10.11.6 (15G31)

**Comment by loganfsmyth** [comment]
This is fixed in Babel 7.x Beta.

The output there is
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var _exportNames = {};
Object.defineProperty(exports, "default", {
  enumerable: true,
  get: function get() {
    return _react.default;
  }
});

require("./_common");

var _react = _interopRequireDefault(require("react"));

Object.keys(_react).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _react[key];
    }
  });
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

**Comment by bernardmcmanus** [comment]
@loganfsmyth perfect, thank you for the quick response

**Comment by loganfsmyth** [comment]
No problem. I did essentially a complete rewrite of the module transforms for 7.x because they were full of edge cases like this.
