### ISSUE TITLE
Add supporting environment variable to search node_modules

### ISSUE THREAD

**Issue by liminspace** [babel/babel#6664]
By default babel is looking for `node_modules` in current directory.
But sometimes we need to use `node_modules` from some child or other directory.
I tried to use `NODE_PATH` env, but it doesn't work.
So, maybe it's good idea to add supporting some environment variable, for example `BABEL_NODE_MODULES` with list of path to search `node_modules` directory.
Let's make babel more flexible!

**Comment by xtuc** [comment]
It seems that this is a duplicate of https://github.com/babel/babel/issues/5618 or https://github.com/babel/babel/issues/6558. 

This brings up a common issue which is the way the current working directory is set when running Babel.

> Let's make babel more flexible!

Flexibility is great but it adds complexity.

**Comment by liminspace** [comment]
> Flexibility is great but it adds complexity.

Complexity is when anything is very inflexible and you spend a lot of time to do basic things.
JS is not the main technology in my projects and I hate to put everything into root directory.

**Comment by nicolo-ribaudo** [comment]
Duplicate of #5618, pr at https://github.com/babel/babel/pull/9520
