### ISSUE TITLE
Possible to represent reserved keywords using unicode escape sequences

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6717]
> Issue originally reported by @DrewML in babel/babylon#206

(Original report from @dashed in https://github.com/babel/babel/issues/4786).

### Input Code

``` js
let n = 5;

while(n --> 0) {
  \u0062\u0072\u0065\u0061\u{006B};
}

console.log(n);
```

[In action in babel REPL (Babel 6.18.0)](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&experimental=true&loose=true&spec=false&playground=true&code=let%20n%20%3D%205%3B%0A%0Awhile%28n%20--%3E%200%29%20%7B%0A%20%20%5Cu0062%5Cu0072%5Cu0065%5Cu0061%5Cu%7B006B%7D%3B%0A%7D%0A%0Aconsole.log%28n%29%3B)
### Expected Behavior

It shouldn't be possible to represent reserved keywords using unicode escape sequences (e.g. `\uXXXX` or `\u{XXXX}`).

See: http://www.ecma-international.org/ecma-262/7.0/#sec-reserved-words
### Current Behavior

example:

`\u0062\u0072\u0065\u0061\u{006B}; => break;`
### Possible Solution

_TBD_
### Your Environment

| software | version |
| --- | --- |
| Babel | 6.18.0 (via REPL) |
| node | n/a |
| npm | n/a |
| Operating System | n/a |

---

/cc @mathiasbynens (for his expertise 😄  )

**Comment by danez** [comment]
This is fixed in babel 7.0
