### ISSUE TITLE
Fix reserved keywords

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6719]
> Issue originally reported by @danez in babel/babylon#134

http://www.ecma-international.org/ecma-262/6.0/#sec-keywords

Some throw correctly: `for`, `implements`, ...

- [x] Some don't: `enum`, `await`
- [ ] Some are supposed to be usable in script mode (non-strict) but don't: `let` (need to test other envs if this is true)

This list is probably not complete.

**Comment by mmckeaveney** [comment]
Is this still available? I can address it if so

**Comment by mannanali413** [comment]
@mmckeaveney  sure you can take this up
