### ISSUE TITLE
Implement better comment attachment algorithm

### ISSUE THREAD

**Issue by sebmck** [babel/babel#672]
Currently using estraverse for comment attachment. Has proven to have multiple issues associated with attaching comments and it'd be nice to be able to retain comments inside of empty blocks etc through an `insideComments` property or something.

Reference: #459

**Comment by Dashed** [comment]
So, I went down the rabbit hole via https://github.com/estools/estraverse/issues/23 and https://github.com/estools/escodegen/pull/133. There doesn't seem to be movement on their side. 

But there's some consensus on a CST standard where there isn't much activity for some time: https://github.com/getify/concrete-syntax-tree

There doesn't seem to be a trivial solution to this.

**Comment by sebmck** [comment]
@Dashed Roll our own.

**Comment by sebmck** [comment]
Superseded by #883.
