### ISSUE TITLE
Better error output for await in non-async functions

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6720]
> Issue originally reported by @danez in babel/babylon#113

> Issue originally made by @SystemParadox on babel/babel#2387

``` js
function test() {
    await foo();
}
```

Throws: `Unexpected token(2:8)`

This is a bit misleading. Can we change this to say something like "await can only be used in async functions"?

Thanks.

**Comment by hzoo** [comment]
From https://twitter.com/sebmck/status/1031978115881291776

`You can just add a check for state.inFunction in checkReservedWord`

We can just cover the basic case for now

**Comment by aulisius** [comment]
Is something working on this right now? Are there any open PRs?

**Comment by existentialism** [comment]
@aulisius not at the moment!

**Comment by aulisius** [comment]
Cool! I'll like to take a crack at it, then :D !

**Comment by existentialism** [comment]
@aulisius awesome! feel to free to join us on slack if you haven't already!

**Comment by brodeynewman** [comment]
Awesome 😄

**Comment by danez** [comment]
The output is now `await is a reserved word (2:4)` and #7727 might have an effect on this.

Closing as I think the output is better now.
