### ISSUE TITLE
Cannot handle large js file

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6721]
> Issue originally reported by @lxfind in babel/babylon#84

the babylon.js uses `console.log(JSON.stringify(ast, null, "  "));` to dump the ast output, which will run out of memory if the js file is roughly more than 1M (the AST text becomes close to 1G).
It would be nice to provide an option to babylon.js to strip the tokens from the output, as they take up most of the space and are often useless.

**Comment by xtuc** [comment]
Closing, out of scope for now.
