### ISSUE TITLE
Significant but hard-to-find bug in parsing arrow functions

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6723]
> Issue originally reported by @Lucretiel in babel/babylon#58

As of a recent release (Don't know when, exactly, but this issue broke code that was working fine around June 4), babylon's parsing of arrow functions has broken in a very peculiar way. When babylon encounters the following pattern:

```
<some expression> :
    <a parenthesized arrow expression> ?
    <an unparenthesized arrow expression>
```

It reports an error parsing the parenthesized arrow expression:

```
Module build failed: SyntaxError: <path to file>: Assigning to rvalue (23:3)
```

For example:

```
let x = foo() ?
    (value => true) :
    value => false
```

The contents of the condition don't seem to matter, nor does parenthesizing the entire conditional expression. However, if the parenthesis around the first arrow function are removed, or parenthesis are added to the second arrow function, or either arrow function is something other than an arrow function, it is parsed fine. This specific pattern is the only one that triggers the error.

For what it's worth, I'm running babylon via babel via webpack, but the stack trace I get is entirely from babylon.

This seems implausible, I know, so I've created a git repo which reproduces the error, available here:

https://github.com/Lucretiel/babylon-error

The specific file I'm trying to pack is [index.js](https://github.com/Lucretiel/babylon-error/blob/master/index.jsx) with no dependencies or requires. The raw output from `webpack` is in [build_result](https://github.com/Lucretiel/babylon-error/blob/master/build_result).

**Comment by nicolo-ribaudo** [comment]
This issue had been fixed by https://github.com/babel/babylon/pull/596
