### ISSUE TITLE
Incorrect "keyword" value for the key of object property which looks like an boolean

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6724]
> Issue originally reported by @markelog in babel/babylon#18

For the case like 

``` js
({true: 1})
```

token for the key, will look like this -

``` json
{
  "type": {
    "label": "true",
    "keyword": "true",
    "beforeExpr": false,
    "startsExpr": true,
    "rightAssociative": false,
    "isLoop": false,
    "isAssign": false,
    "prefix": false,
    "postfix": false,
    "binop": null,
    "updateContext": null
  },
  "value": "true"
}
```

I believe `"keyword": "true"` bit should look like this - `"keyword": undefined` or `"keyword": false`

**Comment by mmckeaveney-r7** [comment]
I can pick this if its available. Looks like there's still some discussion required around the solution though, judging by the previous (closed) issue.

**Comment by debugpai2** [comment]
Is this issue still open and/or is anyone looking at it?

**Comment by xtuc** [comment]
Given the age of the issue I would prefer closing it. I don't think it's still valid tho.
