### ISSUE TITLE
babel-polyfill: Please add copyright statement

### ISSUE THREAD

**Issue by martinpitt** [babel/babel#6728]
I am doing a copyright review for packaging a project that includes the babel-polyfill code and noticed that there are no copyright statements at all:

```
❱❱❱ grep -ir copyright node_modules/babel-polyfill/
node_modules/babel-polyfill/dist/polyfill.js: * Copyright (c) 2014, Facebook, Inc.
```
That only hit is from a bundled dependency, not for babel-polyfill itself.

The only clue is in package.json's `author` (Sebastian McKenzie), but one cannot assume that Sebastian owns the copyright (could be owned by his employer, for example). The MIT license also specifies that a Copyright statement must be given and not removed on modification.

**Comment by martinpitt** [comment]
https://github.com/babel/babel/commits/master/packages/babel-polyfill seems to indicate that at least @hzoo (plus some contributors) also have some copyright here.

**Comment by hzoo** [comment]
https://github.com/babel/babel/blob/master/packages/babel-polyfill/src/index.js

The source code for polyfill is 2 import statements, one is https://github.com/zloirock/core-js, and the other is regenerator-runtime which is a part of https://github.com/facebook/regenerator.

Currently regenerator is under the BSD license + PATENTS clause, can follow https://github.com/facebook/regenerator/issues/316. I asked @zpao to look into switching so waiting for that. If you can't use it you can just import core-js yourself until we have a version that doesn't include it. (That dependency is not used unless you are compiling generator functions)

**Comment by hzoo** [comment]
Added licenses to the publish step in https://github.com/babel/babel/pull/8409
