### ISSUE TITLE
Class variable should be under TDZ during ClassFieldDefinitionEvaluation 

### ISSUE THREAD

**Issue by gsathya** [babel/babel#6732]
> Choose one: is this a bug report or feature request?

bug report

### Input Code

```js
class C {
  static [C] = new C;
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

stage2,stage3

### Expected Behavior

ReferenceError

### Current Behavior

no error

### Your Environment

[REPL](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEDCDeAoa0IBcxoJbGgbVgF1oBeaAOwFMB3OAbkQF8g&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=stage-2%2Cstage-3&targets=&version=7.0.0-beta.5)

**Comment by maurobringolf** [comment]
Should this also throw without the computed property name?

```javascript
class C {
  static x = new C;
}
```

**Comment by gsathya** [comment]
No, that's valid. Only ClassFieldDefinitionEvaluation observes the TDZ, not InitializeStaticFields.

Sorry about the confusing example, a better example is

```
class C {
  static [C];
}
```

**Comment by maurobringolf** [comment]
I would like to try this. I tried adding a subtraversal checking all references to the class name inside the property key computation and inserting runtime errors there. It seems to work but I wonder what the preferred approach would be though. The extra traversal seems unnecessary to me, could it possibly also be done via some scoping mechanism?
