### ISSUE TITLE
Cannot "export type * from './other-file'" with Flow preset

### ISSUE THREAD

**Issue by hawkrives** [babel/babel#6743]
Choose one: is this a **bug report** or feature request?

### Input Code

I made an example repository that demonstrates my bug: https://github.com/hawkrives/babel-flow-export-star.

I included more detailed instructions about how to reproduce in the README in that repository.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

The sample repository includes a `.babelrc`.

### Expected Behavior

I would expect babel to either strip the `export type * from` line, if using `transform-flow-strip-types`, or to convert it into a comment, if using `transform-flow-comments`.

### Current Behavior

```
> babel-flow-export-star@1.0.0 babel ~example/babel-flow-export-star
> babel *.js --out-dir compiled/

SyntaxError: export.js: Unexpected token (3:12)
  1 | // @flow
  2 | 
> 3 | export type * from './typedef.js';
    |             ^
  4 | 
```

It currently dies.

### Possible Solution

What I _do_ know is that Flow, as of at least v0.56, can parse and typecheck this example, and Babel (as of v6.26) cannot.

### Context

I would like to use normal Flow syntax instead of the comment syntax, especially in https://github.com/react-community/react-navigation/pull/2903 which is where I discovered this bug.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v6.26.0
| node             | v8.8.1
| npm              | v5.5.1
| Operating System | macOS 10.13

**Comment by existentialism** [comment]
@hawkrives this is fixed in 7.0 via https://github.com/babel/babylon/pull/617

**Comment by hzoo** [comment]
Ok we'll ask that you try out Babel 7 beta

**Comment by hawkrives** [comment]
Sounds good!
