### ISSUE TITLE
transform-react-constant-elements may hoist vars into unreachable code

### ISSUE THREAD

**Issue by Jessidhia** [babel/babel#6751]
In certain circumstances involving a combination of locally scoped components and hoisted function declarations written inside unreachable code, the transform may write the hoisted jsx inside the unreachable code region.

I have placed the code in this report in astexplorer so the input/output can be played with (transform copied from `master`):

http://astexplorer.net/#/gist/a03cd893007f6c4ebb6a2bc7e56ef6f3/ce2d32e0aa49941e47fd1761971c76bedff81fc1

### Input Code

```jsx
function AComponent () {
  const CComponent = () => <div/>
  return <BComponent/>
    
  function BComponent () {
    return <CComponent/>
  }
}
```

This example is slightly contrived as the actual locally-scoped components in the RWC are function evaluation results.

### Output Code

```jsx
var _ref = <div/>;
function AComponent () {
  const CComponent = () => _ref
  return <BComponent/>

  var _ref2 = <CComponent/>;

  function BComponent () {
    return _ref2;
  }
}
```

Note how the `_ref2` is declared after the return and, thus, is unreachable code. This will cause React to throw at runtime as `BComponent` returns `undefined`.

(This would rightly be a `ReferenceError` if the transform used `let`/`const` instead of `var`)

---

This may be somewhat low priority as _actual_ components are never written with nested components inside their render functions; this case in RWC is a JSX factory function that just generates static JSX that is only rendered once.

**Comment by Kovensky** [comment]
Given how what the transform does is just call `path.hoist()` on the JSX fragment that it detects as hoistable, this seems like a bug in `babel-traverse` rather than a bug in `transform-react-constant-elements`.

Here is an astexplorer demonstrating this issue in a more contrived, but simpler example: http://astexplorer.net/#/gist/dce75ff8c622adafdd37786ea37db0c7/feb48dcf027fdda4df25b2f360e9e4df4927d315
