### ISSUE TITLE
cli pipe not working

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [babel/babel#6758]
When piping into babel the script is not compiled.

When using the cli it works as expected when not piping in the file.

### Expected Behavior
Working when referencing a file:
```shell
$ npx babel ./try_babel.js
'use strict';

var a = 'hi';
```

I would expect all commands
```shell
$ npx babel ./try_babel.js
$ cat try_babel.js | npx babel
$ npx babel < ./try_babel.js 
```
to do the same thing

### Current Behavior
Does not work when piped in:
```shell
$ cat try_babel.js | npx babel
const a = 'hi';

$ # nor with "<" like docs from https://babeljs.io/docs/usage/cli/#babel-piping-files
$ npx babel < ./try_babel.js 
const a = 'hi';

```

### Test File
File to compile (try_babel.js)
```javascript
const a = 'hi'
```

### Context
Trying to pipe output of browserify into babel for some quick tests.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 (babel-core 6.26.0)
| node             | v8.5.0
| npm              | 5.5.1
| Operating System | Mac 10.11.6

**Comment by victordidenko** [comment]
I've faced similar issue with @babel/cli version 7.0.0-beta.37:
When I piping file into babel, it ignores .babelrc.
But if I add parameter -f <anyname.js> everything is working fine:

> -f, --filename [filename]                   filename to use when reading from stdin - this will be used in source-maps, errors etc

Try it

```
$ npx babel ./try_babel.js
$ cat try_babel.js | npx babel -f try_babel.js
$ npx babel -f try_babel.js < ./try_babel.js
$ echo 'const a = "hi"' | npx babel -f 1.js
```

**Comment by BebeSparkelSparkel** [comment]
Thanks for the work around. Would not have expected that

**Comment by nicolo-ribaudo** [comment]
This is by design: if Babel doesn't know where the file comes from, it can't choose the correct `.babelrc` file.
So `cat try_babel.js | npx babel` will run Babel with an empty configuration, without any plugin.

You can make it work in three ways:
1. By providing the input file name, as suggested by @victordidenko 
2. By specifying which `.babelrc` should be used:
    ```
    cat try_babel.js | npx babel --config-file ./config/.babelrc
    ```
3. By setting the `--plugins` and `--presets` options:
    ```
    cat try_babel.js | npx babel --presets babel-preset-env
    ```

I have opened https://github.com/babel/website/issues/1512 to update the documentation.

**Comment by BebeSparkelSparkel** [comment]
It would be nice if an error could be thrown when the .babelrc file cannot be found.
