### ISSUE TITLE
Allow specifying "mergeMode" for config merging?

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6765]
We've got https://github.com/babel/babel/issues/5276 filed, but the main reason for removing `env` is that users simply don't understand how the merge logic works. (And I don't blame them, _I_ barely understand it, and might not be able to describe it to you.

That said, there are other places where we merge, so we should still figure out a better story around how configurations get merged together. Primary cases where we merge now:

* Config files can `extends: "./other-config"` and things get merged
* Programmatic options to `babel.transform` are merged with `.babelrc` options
* "env" blocks are merged with their parent configs
* If we do https://github.com/babel/babel/issues/5451, we need a clear story around merging for specific files.

**Comment by clemmy** [comment]
From reading the related issues, I'm unsure of what `mergeMode` would look like, and how you propose it would solve the story about how configurations are merged together. Can you elaborate?

**Comment by loganfsmyth** [comment]
I'm in the process of implementing a prototype of this right now. I kind of decided making an option to toggle was just not worth it, so Babel 7 may very well just stabilize with an entirely different config merging process :D

What I'm exploring would essentially allow for users to do

```
{
  plugins: [
    ['some-plugin', {one: true, two: true}],
  ],
  env: {
    test: {
      plugins: [
        ['some-plugin', {two: false, three: false,}],
      ],
    }
  }
}
```
would only be a single instance of the plugin, with the options from `test` merged into the once from the root, essentially being
      
```
{
  plugins: [
    ['some-plugin', {one: true, two: false, three: false}],
  ],
}
```
when the environment was set to `test`.

**Comment by clemmy** [comment]
Interesting, I am digging this change. One thing, however, is I don't see how it solves https://github.com/babel/babel/issues/5451.

**Comment by nicolo-ribaudo** [comment]
@clemmy One step at time :smile: Getting the config merging logic right is necessary for that proposal.

**Comment by loganfsmyth** [comment]
Yeah, doesn't solve that, it's just a blocker because without better merging, having override behavior would be an absolute minefield for users.

**Comment by clemmy** [comment]
Okay! Thanks for the context.

**Comment by Andarist** [comment]
More and more I think about it - it seems like unnecessary complication. While some might dig the proposed merge strategy, some will certainly find it confusing. IMHO it's better to have people to specify exactly what they want in @loganfsmyth's example for `test` env and that is `{one: true, two: false, three: false}`.

Babel7 will come with first class support for `.babelrc.js` and that means that anyone can implement his/her own merging strategy with custom javascript logic. Leaving auto-merges out of Babel's codebase would simplify it and would be easier to maintain.

**Comment by loganfsmyth** [comment]
True! That's certainly an option too. I guess I was thinking that merging would be a more flexible strategy, like if someone wanted to do a full replace they could do

```
plugins: [
  ['some-thing', { some: {nested: 'thing'}}],
],
env: {
  test: {
    plugins: [
      ['some-thing', false],
      ['some-thing', { some: {nested: 'thing'}}, 'newname'],
    ],
  }
}
```
so use `false` to disable the one at the root, and then make a new one with the name `newname`.

Doing a full replace does have some nice benefits though, since it means we'd have a clear 'dirname' for the options given to the plugin, so I'd definitely be open to it if people think it would be a better bet for people. I definitely agree that it would be simpler to describe.

**Comment by Andarist** [comment]
Also in most cases when things are simpler to describe they are also easier to grok by people which in turn should spare us more questions on the issues from confused people.
