### ISSUE TITLE
transform-flow-comments + transform-es2015-classes bug

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel#6767]
Choose one: is this a bug report or feature request?

Bug

### Input Code

I made a reproduction repository here: https://github.com/kentcdodds/babel-flow-comments

### Possible Solution

First we need to find out what the output code _should_ look like to satisfy flow. I'm not sure who the right person to ask that... Maybe @gabelevi who wrote [The Flow Comments blog post](https://flow.org/blog/2015/02/20/Flow-Comments/)?

I'm guessing the fix will be in the es2015 classes transform to make it preserve the comment in wherever it should go.

### Context

I'm trying to write a reusable react component with inline flow type definitions. I can't use a tool like [`flow-copy-source`](https://github.com/AgentME/flow-copy-source) because I'm using rollup to bundle the module, so using the comments syntax is best for me.

### Your Environment

I'm pretty sure the only relevant bits here are that I'm using the latest stable versions of everything.

**Comment by hzoo** [comment]
This should be a known bug, because if you compile the class it doesn't know where to put the comment I think, - like https://github.com/babel/babel/issues/5626?

**Comment by kentcdodds** [comment]
Thanks for responding @hzoo. Hmmm... I think that's a different bug. That one is an issue with `transform-flow-comments` alone. In my case, `transform-flow-comments` is working just fine. However, when the `transform-es2015-classes` bug runs, the comment is removed entirely.

**Comment by kentcdodds** [comment]
Ok, I've simplified the example a bit and updated [the repo](https://github.com/kentcdodds/babel-flow-comments).

> You can see the output in `only-flow.js` and `both.js`. Interestingly, if I run babel with `transform-es2015-classes` on `only-flow.js` then I get `flow-then-classes.js` which is correct I think.

**Comment by kentcdodds** [comment]
Simplified it a little further :+1:

Here's the relevant stuff:

```javascript
// index.js
// @flow

type A = {}

class B extends C<Props> {}
```

```javascript
// only-flow.js
// @flow

/*:: type A = {}*/


class B extends C /*:: <Props>*/ {}
```

```javascript
// flow-then-classes.js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

// @flow

/*:: type A = {}*/

let B = function (_C) {
  _inherits(B, _C);

  function B() {
    _classCallCheck(this, B);

    return _possibleConstructorReturn(this, (B.__proto__ || Object.getPrototypeOf(B)).apply(this, arguments));
  }

  return B;
}(C /*:: <Props>*/);
```

```javascript
// both.js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

// @flow

/*:: type A = {}*/

let B = function (_C) {
  _inherits(B, _C);

  function B() {
    _classCallCheck(this, B);

    return _possibleConstructorReturn(this, (B.__proto__ || Object.getPrototypeOf(B)).apply(this, arguments));
  }

  return B;
}(C);
```

You'll notice that the only difference between `both.js` and `flow-then-classes.js` is the last line:

```diff
- }(C);
+ }(C /*:: <Props>*/);
```

I'm not 100% certain what's causing this, but I may be able to dig a little bit and submit a PR to preserve that comment :+1:

**Comment by loganfsmyth** [comment]
>  I can't use a tool like flow-copy-source because I'm using rollup to bundle the module

I'm not sure I understand why Rollup is a blocker for this, but I may just be missing something. Why won't it work?

I personally consider `transform-flow-comments` to be absolutely avoided unless you're transforms are super minimal.

**Comment by kentcdodds** [comment]
Unless I'm misunderstanding how `flow-copy-source` works, this is the problem:

**Input module files**:
- src
  - index.js
  - utils.js

**Output rollup bundle**:
- dist
  - my-lib.esm.js
  - my-lib.cjs.js
  - my-lib.umd.js

So what I need is a tool that can either apply flow types defined in my source to the rollup version of my module or I need the flow types to be defined inline. Does that make sense?

**Comment by loganfsmyth** [comment]
I think you could have a `my-lib.cjs.js.flow` file that did like

```
export * from "../src/";
export { default } from "../src/";
```
to basically link your bundled file back to the source for Flowtype to process?

**Comment by kentcdodds** [comment]
Hmmm... That's an interesting thought. I'm giving something else a try right now, I'll let you know!

**Comment by kentcdodds** [comment]
So yeah, that totally works! :tada: I'm going to go ahead and close this because I don't need this anymore :smile: Thanks!
