### ISSUE TITLE
@babel/preset-env: Can't use useBuiltIns: 'entry' with es6 object polyfills

### ISSUE THREAD

**Issue by specialkk** [babel/babel#6771]
### Babel/Babylon Configuration (.babelrc, package.json, cli command)

I'm using a browserslist query of "last 1 versions". Any query that requires object polyfills should also have this issue.

### Expected Behavior

The project should compile successfully

### Current Behavior
My Webpack output gives
```
Module not found: Error: Can't resolve '@babel/polyfill/lib/core-js/modules/es6.object.freeze' in ...
Module not found: Error: Can't resolve '@babel/polyfill/lib/core-js/modules/es6.object.get-own-property-descriptor' in ...
Module not found: Error: Can't resolve '@babel/polyfill/lib/core-js/modules/es6.object.get-own-property-names' in ...
...
```

### Possible Solution

I think something needs to be updated with `@babel/polyfill`, or the preset should just read from `core-js` modules directly (why isn't it doing this already?).

### Context

I hit this issue while trying to upgrade from beta 2, which I believe is the latest build I can use before my existing setup breaks. I think it was introduced with d80fea4. 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.31
| Babylon          | -
| node             | 8.5.0
| npm              | 5.3.0
| Operating System | Windows

**Comment by existentialism** [comment]
@specialkk

> or the preset should just read from core-js modules directly (why isn't it doing this already?)

Fixed as of https://github.com/babel/babel/pull/6755, (see the linked issue to get an answer to your question).

**Comment by specialkk** [comment]
Oh cool, bad timing on my part. I'll check for that in the next beta!

**Comment by existentialism** [comment]
@specialkk no worries, thanks for reporting the issue!
