### ISSUE TITLE
Remove the `.expression` field from `ArrowFunctionExpression`

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6773]
Context: https://github.com/babel/babel/issues/6772#issuecomment-342935685

As far as I can see, there's no reason to have this flag, so my vote would be to kill it instead of expecting us (and anyone else writing transforms) to remember to always keep it in sync with the type of the body node.

Thoughts?

**Comment by loganfsmyth** [comment]
References:

https://github.com/babel/babel/blob/c440f045f548ab60d15880a60b34511a7ffec931/packages/babylon/src/parser/expression.js#L1468 and a few other places in this file, not sure if elsewhere.

https://github.com/babel/babel/blame/c440f045f548ab60d15880a60b34511a7ffec931/packages/babylon/ast/spec.md#L630

**Comment by mmckeaveney** [comment]
I can pick this up, if that's ok?

**Comment by Andarist** [comment]
Sure thing. If you have any questions, you can always reach us on Slack.
