### ISSUE TITLE
babel-register documentation examples throwing errors

### ISSUE THREAD

**Issue by blakew** [babel/babel#6774]
@babel/core, @babel/register
version: 7.0.0-beta.31

Using the syntax in the documentation ie.

```ignore: /regex/```

and 

```ignore: false```

Both throw the error

```Error: .ignore must be an array, or undefined```

Am I doing something wrong or is the documentation incorrect?

Thanks

**Comment by loganfsmyth** [comment]
Ah! Those probably need to be updated. That should now be

```
ignore: [ /regex ]
```
and 
```
ignore: []
```
I believe. The docs should be updated.

**Comment by lostpebble** [comment]
Ran into this today as well.

Are ignore functions still allowed in v7 ?

**Comment by loganfsmyth** [comment]
`ignore` is an array, so you'd want `ignore: [function(){}]`
