### ISSUE TITLE
Update babel-cli to use the async version of babel.transform

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#6784]
As of https://github.com/babel/babel/pull/6780, Babel has both `babel.transform` and `babel.transformSync`. For backward-compat you can leave the callback off of `babel.transform` and it'll behave synchronously, but ideally for all the places that _can_ shift to using the async version, they should.

The `babel` command in babel-cli is one of the places that can easily use the async version. The hard thing will be updating all of the surrounding code to to handle things asynchronously too.

This should be pretty self-contained, so I'm marking it as a `good first issue`, but it'll definitely involve a good bit of refactoring.

**Comment by aprieels** [comment]
I'ld like to work on this issue as my first contribution to Babel, if it's ok for you.

**Comment by loganfsmyth** [comment]
@aprieels Go for it. I'd recommend joining our Slack if you haven't, so we can answer any questions you have.
