### ISSUE TITLE
strang behavior with es6 re-export syntax. defect?

### ISSUE THREAD

**Issue by bochen2014** [babel/babel#6795]
I ran into a very strange issue today. here is my code
```javascript
// index.js
export * from './actions'; // can only be put in the front
export { default as QuizListContainer } from './containers/quizListContainer';
export { default as QuizListReducer } from './reducers';
// if you put it at the bottom, it won't work
// export * from './actions';
```
this also works
```javascript
import  QuizListContainer  from './containers/quizListContainer';
import QuizListReducer  from './reducers';
export {
    QuizListContainer,
    QuizListReducer
}
export * from './actions';
```

but they should all be the same. Is this a known issue?

```bash
$ yarn list babel-core babel-loader babel-preset-es2015 babel-preset-react
yarn list v1.0.2
warning package.json: No license field
warning server@1.0.0: No license field
├─ babel-core@6.26.0
├─ babel-loader@7.1.2
├─ babel-preset-es2015@6.24.1
├─ babel-preset-react@6.24.1
Done in 1.35s.
```

**Comment by bochen2014** [comment]
i had a quick look at the transpiled code for `export * from './actions'`
```javascript
var _actions = require('./actions');
Object.keys(_actions).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _actions[key];
    }
  });
});
```
it seems all right to me. I couldn't think of a reason why putting in at the top or at the bottom would make a difference. any clue??

**Comment by bochen2014** [comment]
I digged a bit deeper in it. It seems to me that it's **not** an export issue, but an import issue
it depends on where you do the import. 
```
project
│   
│   
│
└───folder1
│   +   actions.js
│   +   index.js  ** in question **
│   │
│   +─── containers
│       +   component.js
│       │   ...
│       │   ...
│   
└───app.js
```
if I import within my `folder1`, using something like `import { action1 } from './' ` then I got an undefined error;
however, if I import outside of `folder1`, using `import { action1 } from './folder`' then everything is fine

I think this is a defect

**Comment by bochen2014** [comment]
I figured it out. it was because circular dependency. 
```
├── folder
│   ├── index.js
│   └── actions.js
|     |_____component.js
|
``` 
`index.js` was re-export `actions.js` and `component.js`; 
`component.js` was referring to `actions.js` via ` import { actions1 } from './index.js'`

I would say, don't refer to `actions.js` via `index.js` within `folder`, especially when the module that does the import is part of `index.js` exported modules...

https://github.com/bochen2014/babel-6759

**Comment by bochen2014** [comment]
I'm not sure if I should close it or not.  es6 should support circular import/export. 

it would be great if someone can share some thoughts on it, as it's a very strange behavior

**Comment by loganfsmyth** [comment]
This is most likely fixed by the module transform rewrite in 7.x
