### ISSUE TITLE
Confused "export function" when the function has the same name as inner variable

### ISSUE THREAD

**Issue by 0326** [babel/babel#6797]
### Input Code
My original code is here:
```js 
var add = 1;
export function add() {
  add += 1;
  return add;
}
```
And after babel-transform (you can try it on [babel/repl](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBAhgJjEF4IEYDcAoEAPADgewCdIAzAVwDsBjMASz3OjgAoBKCAb3QkfgGok0XCAXCkCDWDAwBfdEA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0)):
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.add = add;
var add = 1;
function add() {
  exports.add = add += 1;
  return add;
}
```

### Expected Behavior
When I import `add` function, I wanna this result: 
```js
add(); // return 2
add(); // return 3
```
### Current Behavior
```js
add(); // return 2
add(); // Uncaught TypeError: add is not a function
```
I see the transformed code, when the first time I called `add` , it's a function, but in the function, the expression `exports.add = add += 1` makes `exports.add` become a number. So I was confused Why babel think the "add" in my origin code "add += 1" is meaning "exports.add" not the inner varible add ? It's a bug or a feature?

**Comment by nicolo-ribaudo** [comment]
I *think* that it should throw also on the first call, since `import { add } from "....."` should return `2`. (node actually throws `SyntaxError: Identifier 'add' has already been declared`, so I may be wrong)

Your code is equivalent to this one, which throws.
```js
var add = 2;
function add() {}
export { add };

console.log(add); // 2
```

---

Note that exported declarations are added to the scope, so you code in a CommonJS word would be
```js
var add = 2;
function add() {
  // ...
}
exports.add = add;
```
and not
```js
var add = 2;
exports.add = function add() {
  // ...
}
```

**Comment by nicolo-ribaudo** [comment]
@0326 I'm clising this since it is the expected behavior. If I misunderstood the issue, comment and I'll reopen it.
