### ISSUE TITLE
Static properties doesn't support

### ISSUE THREAD

**Issue by khoden** [babel/babel#68]
``` javascript
class B {
  static field = 23;
}
```

throws syntax error:

```
SyntaxError: test\file.es6: Line 8: Unexpected token =
  7   |     class B {
> 8   |         static field = 23;
      |                      ^
  9   |     }
```

**Comment by yordis** [comment]
@sebmck why I can't add that. I am following this https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html and they have some example using this syntax.

Are you going to add it or it's just speculations about it?

**Comment by sebmck** [comment]
@yordis http://babeljs.io/blog/2015/03/31/5.0.0/#stage-0:-class-properties

**Comment by yordis** [comment]
thank you very much
