### ISSUE TITLE
--watch flag does not watch .mjs files

### ISSUE THREAD

**Issue by jacksonrayhamilton** [babel/babel#6800]
I've tried compiling continuously with babel-cli's `--watch`.  It will continuously compile a file with a ".js" extension.  But when I change the source file's extension to ".mjs", continuous compilation does not work; changes to files are not compiled.

I expect that any file I have specified to compile will automatically be watched, regardless of what extension it has.

**Comment by jacksonrayhamilton** [comment]
For the record, I found that I could work around this with `--extensions ".mjs",".js"`.

Still, I believe that it'd be more intuitive if the files specified in the command were watched, regardless of their extensions.  Seems like changing [this code](https://github.com/babel/babel/blob/9cd4716cb45d90730025d954539bb9a970c10c65/packages/babel-cli/src/babel/file.js#L188) would effect that change?

Also, I think [the documentation for the `--extensions` flag](https://github.com/babel/babel/blob/830c527bb7873b29f671a3568b21b4a6af98ceda/packages/babel-node/src/_babel-node.js#L39) should be more precise.  "List of extensions to hook into" is not an informative description.

Also, I think the default value for the `--extensions` flag should be updated to include ".mjs", since this the extension that Node is using now.

**Comment by jaydenseric** [comment]
I'm using v7.0.0-beta.39 and this issue seems to be fixed, can it be closed?
