### ISSUE TITLE
[transform bug] !may because of the function in the for loop;

### ISSUE THREAD

**Issue by yinsang** [babel/babel#6809]
I have find a bug in  babel;
You can see it here:
[Babel](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBAJghmMQLwQNoEYA0ECsWDke-hEA7EQLoDcAUNQGYCuAdgMZgCWA9kxAE7MAKWPACUEAN7UI0iHU68IA0JHZMoIAB5IIABkoRV6rQB5ocGADpQTAOZgAFvsOaA1C7GSZXiMoNgQALbawjAozhpUUt7S7HSK7P5BiMkQBB5R0V4hFgDOAA7A7CwgAuFYaCI0md7h2rUAtBBoVdUyLNwcTAwgLdEAvhnevjBQUADi2oysHNyK6a1e7Uw5nKBWnDaliZWDXn29EAOL3CtrwBtC5jtevOAMvDwhNAP8TJeiQA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0)
when it runs in es6 it's right;
when it runs in es5 that had transformed by babel, it's wrong!
the code is 
```js
let data = [1, 5, '', '', 7, ''];

function run(data) {
    for (let index = 0; index < data.length; index++) {
        let item = data[index];
        if (item === '') {
            data.splice(index, 1);
            index = index - 1;
            continue;
        }
        let addG = function () {
             console.log(item);
        };
    }
    console.log(data);
    return data;
}
run(data)
```

**Comment by loganfsmyth** [comment]
Good find, definitely looks like a bug to me. I don't think we really have logic to handle updating the index at all, when `_loop` is split out. We'll need to add that.
