### ISSUE TITLE
@babel/cli babel-node not found

### ISSUE THREAD

**Issue by javascriptonian** [babel/babel#6810]
Choose one: is this a bug report or feature request?
Bug

"scripts": {
"start": "nodemon --exec babel-node app/index.js",
}

### Expected Behavior
babel-node should be working.

### Current Behavior
Says "sh: babel-node: not found"

I'm using @babel/cli v7.0.0-beta.32

**Comment by yavorsky** [comment]
I suppose you created your app according to the [babel/example-node-server](https://github.com/babel/example-node-server/blob/master/package.json). It is outdated.
From recently, [babel-node is a standalone package](https://github.com/babel/babel/pull/6023).

So, you need to install it:
`yarn add @babel/node` or `npm install --save-dev @babel/node`

and then you could use it:

`babel-node [options] [ -e script | script.js ] [arguments]`

**Comment by hzoo** [comment]
Yep! It's a separate package, I did say I wanted it to be part of cli still though*

**Comment by shtse8** [comment]
I think we should update the readme
https://github.com/babel/babel/tree/master/packages/babel-cli

**Comment by xtuc** [comment]
@shtse8 would you mind doing a PR for that?

**Comment by javascriptonian** [comment]
Thanks guys for the quick response.
