### ISSUE TITLE
Document that inline-elements and constant-elements transforms are unsuitable for development

### ISSUE THREAD

**Issue by gaearon** [babel/babel#6813]
We keep getting issues in the React repo from people who try to apply `inline-elements` or `constant-elements` in development, and then get surprising warnings or false positives. They are not meant for usage in development, but it seems like people miss this information. I wonder if we could highlight it better.

For example, I noticed that:

* [constant-elements website page](http://babeljs.io/docs/plugins/transform-react-constant-elements/) mentions this.
* [constant-elements README](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements) **doesn't** mention this.
* [inline-elements website page](http://babeljs.io/docs/plugins/transform-react-inline-elements/) **doesn't** mention this.
* [inline-elements README](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements) mentions this.

I would send a PR, but I don't quite understand why the README content on GitHub does not match the website README content.

**Comment by existentialism** [comment]
@gaearon the website imports READMEs from the 6.x branch for now, as we have an outstanding task to add version switching. We hope to get this fixed asap =/

**Comment by gaearon** [comment]
>that blurb of text is actually in the website docs:

I said that in the OP post :-). Two pages mention it, two pages don't.

**Comment by existentialism** [comment]
> I don't quite understand why the README content on GitHub does not match the website README content.

Sure, I was actually just validating your confusion :)

I think we should add the warnings to both plugin's README and remove it from the website markdown, no reason for it to be split, IMO.

**Comment by hzoo** [comment]
yeah @gaearon we don't have versioned docs, that's why it's different because `master` is 7.x and ya I guess for some reason the docs aren't all contained in the readme
