### ISSUE TITLE
New Feature: move https://github.com/jridgewell/babel-plugin-transform-for-of-as-array into this repo as an option

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6816]
Basically just port/implement this as a plugin option

https://github.com/jridgewell/babel-plugin-transform-for-of-as-array, option name can just be `forOfAsArray` or some other thing we can bikeshed (buble does dangerousForOf)

cc @jridgewell since you made it?

**Comment by jridgewell** [comment]
Sure.

**Comment by rajzshkr** [comment]
I'll pick this

**Comment by AkshatSrivastava2** [comment]
Hello,

I am new to open source.
I want to contribute to babel.
Guide me

**Comment by loganfsmyth** [comment]
@AkshatSrivastava2 Welcome! Take a look at https://github.com/babel/babel/blob/master/CONTRIBUTING.md which should get you started. I believe someone else has already started work on this specific issue though.

**Comment by AkshatSrivastava2** [comment]
@loganfsmyth Thank you for your response.

**Comment by rajzshkr** [comment]
@AkshatSrivastava2 already working on this. Please pick other issues. Thanks.

**Comment by existentialism** [comment]
Fixed in https://github.com/babel/babel/pull/6914
