### ISSUE TITLE
Allow boolean parameters for inputSourceMap

### ISSUE THREAD

**Issue by gilbsgilbs** [babel/babel#6827]
Choose one: is this a ~~bug report~~ or **feature request**?

`inputSourceMap` should accept booleans.

### Expected Behavior
According to [documentation](https://github.com/babel/babel/blame/1165ecc6160f053d5023b3c63fc01202dfe4d47e/packages/babel-core/README.md#L158), `inputSourceMap` option accepts an “object that the output source map will be based on.”

### Current Behavior
According to [source](https://github.com/babel/babel/blob/e44cef34734b59d26b2f090acd7ab16d5570b05c/packages/babel-core/src/transformation/normalize-file.js#L29), it seems a bit trickier, but anyways, it doesn't accept booleans.

### Possible Solution
`inputSourceMap` should accept boolean values. `false` would act the same as today, `true` would try to get the source map from the input file.

It shouldn't be to hard to do fix. I can spend some time on a PR if needed. Just let me know what is the proper implementation according to you.

**Comment by loganfsmyth** [comment]
As far as I know, `true` already attempts to read the map from the source file, were you seeing something different? The `if` you linked will pass if given a `true` value, and since it fails the `typeof options.inputSourceMap === "object"` check, it will just do the `.fromSource(code)` part.
