### ISSUE TITLE
Extend `only` option to allow for specifying presets/plugins to run on specific file globs

### ISSUE THREAD

**Issue by lelandrichardson** [babel/babel#6833]
This is a feature request.

I believe there is a need for different babel configurations to be run on different file extensions or directories (or arbitrary globs).  Currently, we can only have one .babelrc for everything. For the most part, I think people have just put everything they need into one configuration and it "just works". This is great, except for a couple of things:

1. By having to run all babel plugins you possibly might need on all files, babel is slower and doing extra work.
2. some babel plugins have been known to conflict with one another
3. Some babel plugins actually can't be run at the same time (ie, "flow" and "typescript" strip types plugins).

Babelrc has the `only` configuration option which allows you to specify a file glob that babel will run on only those files.  I'm proposing extending this configuration option to accept an object map in addition to a string, such as this:

```
{
  "only": {
    "**/*.{js, jsx}": {
      "presets": ["flow"]
    },
    "**/*.{ts,tsx}": {
      "presets": ["typescript"]
    }
  },
  "presets": ["@babel/env"]
}
```

the object would be of type `fileGlobString : babelRcObject` and the babelrc object inside of the file glob would get "merged" with the overall babelrc for the files that it matched.

**Comment by hzoo** [comment]
Sounds like eslint overrides or the same thing as https://github.com/babel/babel/issues/5451? If so we have have less option names/combine these ideas

**Comment by lelandrichardson** [comment]
@hzoo ah yes. i just saw #5451 as soon as i opened this! whoops!

**Comment by lelandrichardson** [comment]
Any idea as to the difficulty of implementing something like this in babel? would this be a huge refactor?

**Comment by hzoo** [comment]
Not sure, it don't think it would be too bad because babel looks up the config per file already so seems like just an extra check as long as we determine the correct merging behavior. If this makes less need more extra babelrc files I'm for it (in additional to switching to a root config resolve in #6766)

**Comment by loganfsmyth** [comment]
The big questions for me are spelled out in https://github.com/babel/babel/issues/6765

**Comment by loganfsmyth** [comment]
I think we can close this in favor of #5451
