### ISSUE TITLE
How to use flow declarations outside of the project?

### ISSUE THREAD

**Issue by loyd** [babel/babel#6839]
Hi. Thanks for the incredibly awesome tool.

I'm writing [some project](https://github.com/loyd/flow2schema), which actively uses babylon, and I want to use flowtype to check my code.

But
1. npm packages (`babylon`, `types` etc) doesn't provide flow defs.
2. flow-typed repo contains no defs for babel.
3. I found [lib/types.js](https://github.com/babel/babel/blob/master/lib/types.js), generated by a script, but global and prefixed types (`BabelNode...`) confuse me.

So, what is the right way to use flow declarations from the packages?

**Comment by nicolo-ribaudo** [comment]
You could use this file:

https://github.com/babel/babel/blob/master/packages/babylon/src/types.js

**Comment by loyd** [comment]
But it's not included in npm package.

**Comment by mjomble** [comment]
> You could use this file:
>
> https://github.com/babel/babel/blob/master/packages/babylon/src/types.js

Should I copy this file, commit it with my code and manually keep it up to date when updating babylon?
Seems to me too that having this file available directly from the babylon npm package would be preferrable.

**Comment by nicolo-ribaudo** [comment]
I also think it should be added to the npm package. In the meanwhile you can copy it.

**Comment by Andarist** [comment]
What's the best practice for publishing flow typings when the package is using flow already?

**Comment by loyd** [comment]
@Andarist `.js.flow`. But `flow gen-flow-files` works incredibly bad, so you can use [flow-copy-source](https://github.com/AgentME/flow-copy-source) instead.

**Comment by loyd** [comment]
Now I use the [compilation](https://github.com/loyd/flow2schema/blob/master/declarations/babel.js) of typescript definition, `lib/types.js` and `baylon/src/types.js`

**Comment by Andarist** [comment]
@loyd isn't using `.js.flow` files causing any troubles? I mean - flow changes quite fast and distributed typings like that are targeting a specified flow's version (developer's version) where users (who need the typings) might have completely different, incompatible, version of flow

**Comment by Andarist** [comment]
Interesting read - https://blog.kentcdodds.com/distributing-flow-type-definitions-for-node-and-browser-modules-3952ad38b357
