### ISSUE TITLE
Somewhat "console" is undefined in babel-ruby-transpiler bridge.

### ISSUE THREAD

**Issue by FlowerCannon** [babel/babel#6840]
Ok, this actually seems a issue I should open on ruby-babel-transpiler repo, and I'm actually facing this problem inside Rails. However, this issue here would get more attention and it seems that the problems is inside Babel itself.

The summary is: Babel somewhat fails and raises an error when transpiling a Javascript file that is bigger than 100K. And the error is `TypeError: unknown: Cannot read property 'error' of undefined`. And reading the code, the "error" is the error method of the `console` object.

This is the snippet of code taken directly from the babel source that ruby-babel-transpiler uses and where the error arises:

    if (format.compact === "auto") {
      format.compact = code.length > 100000; // 100KB

      if (format.compact) {
        console.error("[BABEL] " + messages.get("codeGeneratorDeopt", opts.filename, "100KB")); //here
      }
    } 

### Expected Behavior

`console` object should not be undefined 

### More details and how I traced the bug

I'm developing an web application with Rails 4.2.6, and I wanted to write the scripts in ES6, so I used the sprockets 4.x gem (even being beta) + babel-transpiler so I could do it. it was working fine until mysteriously I couldn't precompile the assets or even run my application in development environment anymore because this strange error was popping up on tests and in development:

    # Running:

    .............................................E......E.................................

    Finished in 22.975805s, 3.7431 runs/s, 9.6188 assertions/s.

      1) Error:
    ProjectsControllerTest#test_must_get_index:
    ActionView::Template::Error: TypeError: /[project path]/app/assets/javascripts/[script].es6: Cannot read property 'error' of undefined
        Function.normalizeOptions ((execjs):6045:16)
        new CodeGenerator ((execjs):6000:33)
        Object.module.exports [as default] ((execjs):6462:13)
        File.generate ((execjs):8838:42)
        File.transform ((execjs):8667:17)
        (execjs):13515:19
        File.wrap ((execjs):8681:16)
        Pipeline.transform ((execjs):13512:17)
        eval (eval at <anonymous> ((execjs):67513:8), <anonymous>:1:18)
        (execjs):67513:8
        execjs (2.7.0) lib/execjs/external_runtime.rb:39:in `exec'
        execjs (2.7.0) lib/execjs/external_runtime.rb:21:in `eval'
        execjs (2.7.0) lib/execjs/external_runtime.rb:46:in `call'
        babel-transpiler (0.7.0) lib/babel/transpiler.rb:28:in `transform'
        sprockets (4.0.0.beta5) lib/sprockets/babel_processor.rb:57:in `block in call'
        sprockets (4.0.0.beta5) lib/sprockets/cache.rb:92:in `fetch'
        sprockets (4.0.0.beta5) lib/sprockets/babel_processor.rb:43:in `call'
        ...  

What was really strange is that apparently nothing was wrong with the script. I wondered if there was some arcane syntax error my eye was not seeing. I've read the code a thousand times till I convince myself there was nothing wrong. Then I noticed something very strange: If I removed some lines of code of the script, it would work again.

I started to insert `byebug` statements directly on the gems to see what the heck was happening, and learned how Sprockets was calling external processors and discovered that ruby-babel-transpiler gem just bundles my code with a single-file babel.js, put it in a temp file and ran it on NodeJS to get the results:

    > node execjs-output.js 
    ["err","TypeError: /[path to project]/app/assets/javascripts/[script].es6: Cannot read property 'error' of undefined","TypeError: ...

Finally I decided to look inside this file and see what was causing this behavior, and finally found out that the "error" property was the property of the console object.

My script was so big that it was triggering an error message that babel could not display.

Why is `console` undefined inside the babel source used by ruby-babel-transpiler?

And also: Why do Babel complains on files bigger than 100K?

**Comment by loganfsmyth** [comment]
> Why do Babel complains on files bigger than 100K?

Generally Babel gets slower on larger files, so we show a warning about it unless you explicitly say essentially "I don't care" by passing `compact: true` or `compact: false`.

> Why is console undefined inside the babel source used by ruby-babel-transpiler?

It looks like `execjs`, the JS runtime used there, does not support `console`. See https://github.com/babel/ruby-babel-transpiler/issues/284 and https://github.com/sstephenson/execjs/issues/91

To avoid that specific error, you can configure babel explicitly with the `compact` option like I mentioned above. I'm not sure where I'd draw the line on this. Babel generally targets NodeJS and browsers, which have `console` available. The `ruby-babel-transpiler` project hasn't been updated in an extremely long time.

**Comment by FlowerCannon** [comment]
@loganfsmyth thanks for answering.

I see that's actually not a bug. But there's another: It seems that there's no way to pass `compact: false` or any option to babel through `ruby-babel-transpiler`, `execjs`, `sprockets` or `rails` itself.
How am I supposed to at least mitigate this issue?

Maybe I could make a pull request on any of these repos, but this would take a long time.
