### ISSUE TITLE
shouldPrintComment not working as of 7.0.0-beta.31

### ISSUE THREAD

**Issue by futagoza** [babel/babel#6841]
Choose one: is this a bug report or feature request? __Bug Report__

### Input Code (__src/index.js__)
```js
/* a comment */
var your = ( code ) => "here";
```

### Babel Configuration (__.babelrc.js__)
```js
module.exports = {
    shouldPrintComment( comment ) {
        return false;
    }
};
```

### Expected Behavior
Running `babel src -d lib` should generate _lib/index.js_ without any comments, just as if I was using `comments: false` in _.babelrc.js_ instead of `shouldPrintComment( comment ) { return false; }`

### Current Behavior
Comments remain in generated code (in this case _lib/index.js_).

### Possible Solution
I'm not sure, I've checked the source out for Babel and can't find any problem, so I'm not even sure what's causing this weird bug.

### Context
I sometimes use `shouldPrintComment` in a project's _.babelrc.js_ to remove any comments that don't contain JSDoc and in my preset to just ignore ESLint comments.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.31+
| node             | v8.9.0
| npm              | v5.4.2
| Operating System | Windows 10 Home x64

**Comment by loganfsmyth** [comment]
Ahh good catch, totally my fault, fix incoming.
