### ISSUE TITLE
Bug: Wrong code transpiled incorrectly

### ISSUE THREAD

**Issue by rramaa** [babel/babel#6846]
### Expected Behavior
```js
function t(){
a=2
let a = 4;
}
t()
```
This should produce a Reference Error as I am trying to use `a` before defining it

### Current Behavior
Babel is transpiling the code to
```js
"use strict";

function t() {
  a = 2;
  var a = 4;
}
t();
```
This is not producing an error as any variable declared with `var` is hoisted. According to [ECMAScript 2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let), let bindings are not subject to variable hoisting

### Possible Solution
My suggestion would be to throw an error at the time of transpiling the code. This code should not be transpiled at all.

### Context
I was using babel to transpile my server side code . But I removed babel after upgrading node and the code broke as I had written some of the code like this. 

| software         | version(s)
| ---------------- | -------
| Babel            |  6.18.1

**Comment by nicolo-ribaudo** [comment]
The correct behavior is to transpile that code and throw at runtime.  In fact, if you write only the function declaration (but you don't call it) it shouldn't throw an error.

**Comment by nicolo-ribaudo** [comment]
The correct behavior is to transpile that code and throw at runtime. In fact, if you write only the function declaration (but you don't call it) it shouldn't throw an error.

You can use `babel-plugin-transform-es2015-block-scoping`'s `tdz` option to enable that behavior.

**Comment by nicolo-ribaudo** [comment]
@rramaa You can see how that option works in this demo: https://runkit.com/embed/6x1nrwbmk31d.
Documentation will be added by https://github.com/babel/babel/pull/6782.

**Comment by rramaa** [comment]
@nicolo-ribaudo 
I gave the example in the function. But what if I write the code globally. Then it would execute throw the error natively.
I think that this plugin should be included in babel by default
