### ISSUE TITLE
Babel development: watch should compile individual files

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6847]
Currently we run rollup on babylon and webpack on babel-standalone which means watch is weird since it takes a lot longer and can't only compile what's changed.

We should just compile the individual files just like the rest of the code in watch mode. This means less make commands (my opinion is the less of those the better and the less random build code 👍 ). So the bundling only happens for a publish or CI.

**Comment by nicolo-ribaudo** [comment]
How would we compile only single files for babel-standalone? It's meant to be usable in the browser, so we should build it with webpack anyway.

**Comment by hzoo** [comment]
It's just for local dev and tests to pass

**Comment by hzoo** [comment]
I think we did this?
