### ISSUE TITLE
transform-block-scoping's tdz crashes

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#6848]
### Demo

https://runkit.com/embed/wx1vpm3rag2x

### Input Code

```js
a = 2;
let a = 4;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  plugins: [
    [require("@babel/plugin-transform-block-scoping"), { tdz: true }]
  ]
}
```

### Current behavior

```
TypeError: _this.addHelper is not a function
  at Object.addHelper in @babel/plugin-transform-block-scoping/lib/index.js — line 564
  at buildTDZAssert in @babel/plugin-transform-block-scoping/lib/tdz.js — line 21
  at Object.exit in @babel/plugin-transform-block-scoping/lib/tdz.js — line 71
  ...
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by nairicode** [comment]
Hi, @nicolo-ribaudo thanks for reporting issue, I will work on this issue.

**Comment by uni-zheng** [comment]
Hi, there is same problem.

There is a `.babalrc` I use:
```
{
  "presets": [
    ["@babel/preset-env", {
      "ignoreBrowserslistConfig": true
    }]
  ],
  "plugins": [
    ["@babel/plugin-transform-block-scoping", {
      "tdz": true
    }]
  ]
}
```

and libs:
```
"@babel/cli": "^7.2.3",
"@babel/core": "^7.2.2",
"@babel/plugin-transform-block-scoping": "^7.2.0",
"@babel/preset-env": "^7.2.3"
```

Input code:
```
{
  b = 'abc';
  let b = 1;
}
```

Use cli in terminal and throw with an error:
```
TypeError: this.addHelper is not a function
```

I checked my babel-cli version in terminal that is 7.2.3 (@babel/core 7.2.2)

If you have any idea please let me know.
Thank you.
