### ISSUE TITLE
FR: Allow for easier babelrc debugging

### ISSUE THREAD

**Issue by hulkish** [babel/babel#6856]
Choose one: is this a bug report or feature request? 
**Feature request**

### Summary
The desired outcome of this feature is essentially identical to what `babel-preset-env`'s `debug: true` provides. Except, it would instead apply to the **entire** babelrc config.

I foresee the logic for this behavior likely to live along side the "babel config chain" code.

### Problem
When debugging your babelrc config; you have no reliable avenue to derrive which plugins you are using in a format that is human readable.

Sure, If you are using a json-based babel config (eg; `.babelrc` file or `babel` property in your `package.json` file) - you can just simply read that file.

However, if you are working on a js-based preset/plugin of your own and attempt to:
- console.log the config
- use node inspector to set a breakpoint and look at your config.

The result will be:
- Each plugin actually resolves to a function. This is not helpful in terms of *"what is this plugjn?"*.
- If you are new to babel and are using various presets, etc - solving this problem on your own can be a big undertaking as a surprise.
- You can't truly say "ok now my babel is correctly configured" until you can confirm certain things.

### Proposed Solution:
- Introduce a common spec that plugins may use to allow them to.be identified. 
- For example; here is what this might look like, if we were to implement this spec onto `@babel/plugin-external-helpers`:
```js
import { types as t } from "@babel/core";

function externalHelpersPlugin() {
  return {
    pre(file) {
      file.set("helpersNamespace", t.identifier("babelHelpers"));
    },
  };
}

// maybe "debug" instead of "identify"? 
externalHelpersPlugin.indentify = function() {
  const { name, version } = require('../package.json');

  return {
    name,
    version,
    filename: __filename
  };
};

export default externalHelpersPlugin;
```

**Note:** Should not be a breaking change.

**Note:** In a later minor or major release; log a deprecation warning to user in the event that they are using plugins that do not meet the spec. But, still not a breaking change.

**Note:** This concept is certainly open to suggestion.

**Comment by loganfsmyth** [comment]
> Introduce a common spec that plugins may use to allow them to be identified.

We currently allow an optional `name` field for plugins, and expose a `loadOptions` function so you could potentially call that and use the `name` field when it is given. The `name` isn't really used anywhere useful right now, but we could fix that.

> The desired outcome of this feature is essentially identical to what babel-preset-env's debug: true provides. Except, it would instead apply to the entire babelrc config.

If we want to expose more of that data, we could probably think about tying it to https://github.com/babel/babel/pull/6786 rather than having it be a separate function like in your example. I think the more we separate things from the core plugin function itself, the harder things are for users to follow and look up. Let me think about that a bit.

**Comment by hzoo** [comment]
We definetely want better debugging, we should have better insight into what babel is doing/running - config locs, preset/plugin locations/options, versions, etc. Makes our job helping easier too - this is tied to caching, naming, ordering, etc also https://github.com/babel/babel/issues/2960

**Comment by jasonkarns** [comment]
Strong agree on needing better debugging. Between babelrc, CLI params, and API invocations, it is difficult to see what exact configuration babel is actually running under. (_Especially_ because babel's config merging scheme is not 100% shallow, nor really 100% recursive.)

**Comment by xtuc** [comment]
That's a recurrent issue we get, we should probably prioritize it somehow.

Let's add an item to our next Babel meeting?

**Comment by zachlendon** [comment]
This would be a great feature to have.  What's the best workaround folks are using for this in the interim?

**Comment by fabiomcosta** [comment]
This is not a solution to the mentioned issue, but one thing that you can do today to at least see if babel is reading your config file is to prepend `DEBUG='babel:config:loading:files:configuration'` to your command.
It will log what config file it found and loaded, but won't give you details on what's its content.

**Comment by lostpebble** [comment]
Please, to re-iterate what I said a year ago now (https://github.com/babel/babel/issues/2960 - in an issue that is almost 4 years old now about this)... This would make debugging **SO much easier**.

All I want is an output of the config file to know for sure what is being used. Right now you can never really have an idea of what is actually being used in babel's processing, unless you are 100% sure you have configured things properly. Is it really that difficult for Babel to just spit the final config file out with all its values before processing starts?

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/pull/11588 makes it easier to see how Babel is loading the config.
