### ISSUE TITLE
Optimize const violations?

### ISSUE THREAD

**Issue by xtuc** [babel/babel#6857]
Choose one: is this a bug report or feature request?

### Input Code

```js
const t = true

{
  t = false
}

{
  t = false
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  presets: ['es2015']
}
```

### Current Behavior

```js
var t = true;
{
  t = (function () {
    throw new Error("\"t\" is read-only");
  }(), false);
}
{
  t = (function () {
    throw new Error("\"t\" is read-only");
  }(), false);
}
```

### Possible Solution

```js
var _tReadonlyError = new Error("\"t\" is read-only");

var t = true;
{
  t = (function () {
    throw _tReadonlyError;
  }(), false);
}
{
  t = (function () {
    throw _tReadonlyError;
  }(), false);
}
```

### Context

It's just an idea. We can hoist the error (or even the function) to avoid duplicating code so much. Minifiers probably won't catch it in more complex condition.

### Your Environment

[REPL](http://babeljs.io/repl#?babili=false&browsers=IE%2011&build=&builtIns=false&code_lz=MYewdgzgLgBLC8cBOBXApgKAwbwzOMiAZgIYA2EmAvlrvgjKRdUA&debug=true&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015&targets=&version=7.0.0-beta.31)

What do you think about that @maurobringolf?

**Comment by maurobringolf** [comment]
Sounds reasonable 👍  Do you propose this as the standard behavior or only when multiple violations are present?

What about a general helper function for the error? Something like this:

```javascript
function _readonlyError(identifier) {
  throw new Error(`${identifier} is read-only`);
}

var t = true;
{
  t = (_tReadonlyError('t'), false);
}
{
  t = (_tReadonlyError('t'), false);
}
```

**Comment by xtuc** [comment]
@maurobringolf yes a helper function is even better! We can either use this technique for every transformation or count the number of assignments on that binding and activate it or not.

**Comment by maurobringolf** [comment]
Okay cool. I think I should have time to PR today or tomorrow 👌

**Comment by xtuc** [comment]
Awesome, I can also work on this.  Let me know if you need something.

**Comment by Andarist** [comment]
Same thing could happen (or maybe it's already happening somewhere?) for TDZ, right?

**Comment by maurobringolf** [comment]
I used the same approach in https://github.com/babel/babel/pull/6855, not sure if its appropriate there. TDZ in block-scoping uses the same approach if I remember correctly. Could probably be generalized to a `throwErrorBeforeExpression()` helper?

**Comment by xtuc** [comment]
I'm 💯 for the helper.

**Comment by maurobringolf** [comment]
TDZ in `block-scoping` has its own helper already. I will define a new one for const violations and see if I can use the existing tdz one for #6855 .
