### ISSUE TITLE
Config extends with Plugins and preset-env

### ISSUE THREAD

**Issue by digitalkaoz** [babel/babel#6861]
# Bug

hey, somehow `@babel/plugin-proposal-class-properties` fails to get loaded from extending config when using `@babel/preset-env`:

# Code 

```js
// .babelrc.js
module.exports = {
    extends: "./vendor_babelrc.js",
    plugins: [],
    presets: [
        "@babel/preset-env"
    ]
}
```

```js
// vendor_babelrc.js
module.exports = {
    plugins: [
        ["@babel/plugin-proposal-class-properties", { "loose": true }],
    ],
    presets: [
        "@babel/preset-typescript", 
    ]
}
```

```ts
// index.ts
class Example {
  private variable:string;
}
```

# expected behavior

```js
class Example {
  constructor() {
    this.variable = void 0;
  }
}
```

# actual behavior

```
SyntaxError: src/index.ts: Missing class properties transform.
```

# BUT

 if i remove the `@babel/preset-env` from the `.babelrc.js` everything works:

```js
// .babelrc.js
module.exports = {
    extends: "./vendor_babelrc.js",
    plugins: [],
    presets: []
}
```

will give me:

```js
class Example {
  constructor() {
    this.variable = void 0;
  }
}
```

why is that, is this some ordering problem between the extended and the main config? should the extended config element all have precedence over the main config?

> its working with other plugins in `vendor_babelrc.js` like `@babel/plugin-proposal-object-rest-spread`

# Environment

```json
{
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.32",
    "@babel/core": "^7.0.0-beta.32",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.32",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.32",
    "@babel/preset-env": "^7.0.0-beta.32",
    "@babel/preset-typescript": "^7.0.0-beta.32"
  }
}
```

```
$ node --version
8.9.0
$ npm --version
5.5.1
```

**Comment by loganfsmyth** [comment]
This is "expected" in that it is how the Babel's code is in fact written, but I think we all agree it's not what the average human expects. We're hoping we can rework some of this logic in future Babel 7 betas.

Currently, I'd recommend using a single config file, rather than `extends`, because Babel's merge logic is not doing what you'd expect. If you want to keep the multiple files, you'd be better off writing the other file as a normal module then handling the config merging yourself.

**Comment by digitalkaoz** [comment]
To be honest, the current behavior is what nobody expects. If its not working correctly it should be disabled. Im curios to find out why it works with object-rest-spread but not with class-properties??? So i should do the config merging myself and use the node api to solve this? Is there some deeper documentation in config merging? Can it be fixed without deep Babel knowledge? Then im willing to craft a PR...

**Comment by loganfsmyth** [comment]
> So i should do the config merging myself and use the node api to solve this?

I should have clarified more, sorry. No need to use the Node API. I just mean you could do:

```
const vendor = require("./vendor_babelrc.js");

module.exports = Object.assign({}, vendor, {
    presets: ["@babel/preset-env"].concat(vendor.presets),
});
```
to build it programmatically.

> If its not working correctly it should be disabled.

I don't think that's worth doing since this has existed through Babel 6's existence. As I said though, I 100% agree that it's not a good merge strategy and we're working on it.

> Is there some deeper documentation in config merging?

I literally don't even think I could explain it. It's terrible. The documentation would just end up describing the code, which is also just as hard to read.

> Can it be fixed without deep Babel knowledge?

Nope, but I'm on it.

**Comment by digitalkaoz** [comment]
@loganfsmyth thanks for your explanations! 

unfortunately i cant give up config merging entirely (they are unknown from my perspective, just want to add/replace things in whatever config they give me), so im merging them myself (hopefully correct if its so complicated), and wait until it is solved correctly...

**Comment by digitalkaoz** [comment]
@loganfsmyth i hacked a working workaround:

```js
    build() {
        if (this.localConfig) {
            // TODO remove manual merging once https://github.com/babel/babel/issues/6861 is solved
            return this._mergeWithLocalConfig();
        }

        return {
            // http://babeljs.io/docs/usage/api/#options
            exclude: ["node_modules/**"],
            externalHelpers: true,
            plugins: this._plugins(),
            presets: this._presets()
        };
    }

    _mergeWithLocalConfig() {
        const config = this.localConfig;

        config.externalHelpers = true;

        if (!config.exclude) {
            config.exclude = [];
        }
        config.exclude.push("node_modules/**");

        this._mergePlugins(config);
        this._mergePresets(config);

        return config;
    }

    _mergePlugins(config) {
        if (!config.plugins) {
            config.plugins = [];
        }

        // remove the plugins we ship ourself
        config.plugins = config.plugins.filter((plugin) => {
            if (Array.isArray(plugin) && plugin[0].indexOf("external-helpers") !== -1) {
                return false;
            }
            if (typeof plugin === "string" && plugin.indexOf("external-helpers") !== -1) {
                return false;
            }

            return true;
        });

        config.plugins = [...this._plugins(), ...config.plugins];
    }

    _mergePresets(config) {
        if (!config.presets) {
            config.presets = [];
        }

        // remove the presets we ship ourself
        config.presets = config.presets.filter((preset) => {
            if (Array.isArray(preset) && preset[0].indexOf("env") !== -1) {
                return false;
            }
            if (typeof preset === "string" && preset.indexOf("env") !== -1) {
                return false;
            }

            return true;
        });

        config.presets = [...this._presets(), ...config.presets];
    }
```

i think the algorithm is very simple (at least in my use case):

* remove all plugins/presets from extended config that are present in parent config
* inject parent plugins/presets before extended plugins/presets

a lot of edge cases are not handled correctly i think, but its working for simple config extends

**Comment by loganfsmyth** [comment]
With the new merging logic in 7.x this should be treated like

```
{
    plugins: [
        ["@babel/plugin-proposal-class-properties", { "loose": true }],
    ],
    presets: [
        "@babel/preset-typescript", 
        "@babel/preset-env"
    ]
}
```
which I think is enough to close this since it means the class properties will run before `env`

**Comment by digitalkaoz** [comment]
with the latest version it seems to be fixed, thanks @loganfsmyth  for your awesome work!
