### ISSUE TITLE
7.0.0-beta.3 Minify inlining incorrectly 

### ISSUE THREAD

**Issue by smozely** [babel/babel#6867]
Bug report

### Input Code

https://github.com/smozely/babel7-minify-issue

```js
export const funcy = name => {
    const dontInline = {};
    if (name === 'foo') {
        dontInline.bar = {
            baz: 'baz',
        };
    }

    return {
        ...dontInline,
    };
};
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
	"presets": [
		"react",
		[
			"minify",
			{
				"mangle": false,
				"guards": false
//				 "evaluate": false
			}
		]
	],
	"plugins": [
		"transform-object-rest-spread"
	]
}
```

### Expected Behavior
```js 
export const funcy = name => {
    const dontInline = {};
    return "foo" === name && (dontInline.bar = {baz: "baz"}), _extends({}, dontInline)
};
```

### Current Behavior
```js
export const funcy = name => {
    return "foo" === name && ({}.bar = {baz: "baz"}), _extends({}, {})
};
```

### Context
This just leads to incorrect behaviour, as the code does nothing with the result for the if statement.

Un-commenting `"evaluate": false` in the config results in the correct output, with the downside of losing that minification.

### Your Environment
Note this is because of using the beta version `7.0.0-beta.3` using the latest `6` version doesn't exhibit this behaviour.

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.3
| node             | 8.4.0
| npm              | 5.5.1
| Operating System | MacOS Sierra

**Comment by hzoo** [comment]
https://github.com/babel/minify has it's own repo and issues, also I don't believe it's updated to use babel 7 yet?

**Comment by smozely** [comment]
@hzoo Cheers yeah, I wasn't sure which repo to raise it against since its updating Babel that breaks the behaviour to minify. 
Plus I don't/didn't know the expected state of Minify wrt Babel 7, like wondered if it was intended to be no-change for babel-minify to be compatible with 7. Most of it seems to be working correctly 😬 ? 

You reckon I should move this issue over to there?

**Comment by hzoo** [comment]
Minify has moved to v7 (beta) in the last release so closing since an issue is more relevant there
