### ISSUE TITLE
IE9/10/11 babel is not working

### ISSUE THREAD

**Issue by katesherry** [babel/babel#6869]
I have installed babel-cli, babel-core, babel-loader,babel-preset-env, and babel-polyfill
then, I import babel-polyfill in the entry:
```js
entry: Object.assign({
        'vendor': ['babel-polyfill', './src/public/js/app.js']
    },entries()),
```
this is my webpack config:
```js
{
      test: /\.js?$/,
       include: /node_modules/,
       loader: 'babel-loader'
}
```
this is my .babelrc file:
```js
{
    "presets": [
        "env",
        "stage-2"
    ],
    "plugins": [
        ["transform-es2015-classes", {
            "loose": true
        }],
        "transform-es2015-arrow-functions"
    ]
}
```
but, when I use ES6 /class and ES6/String template.It does not recognize in IE browser, but it work fine in chrome and firefox:
```js
class HomeApp{}
```
```js
let temp = `<h1>Header</h1>`;
```
Did I miss something or configure something wrong?

**Comment by nicolo-ribaudo** [comment]
```js
{
      test: /\.js?$/,
       include: /node_modules/,
       loader: 'babel-loader'
}
```

`include` means that you only want to transpile `node_modules`, not your files. Did you mean `exclude`?

Also, I have a few minor comments about your configuration:
- `test: /\.js?$/,` means "include every file which ends with `.j` or `.js`. I think you only want to transpile js files, so you can remove the `?`.
- `transform-es2015-*` plugins are already included in `preset-env`, so you don't need them in your `.babelrc`.

**Comment by katesherry** [comment]
I fixed my configuration file, like this:
```js
{
     test: /\.jsx$/,
     exclude: helpers.root('src/public/js/lib'),
     loader: 'babel-loader'
 }
```
and remove transform-es2015-* plugins
It works !!!
thank for your help. And I think I need to read Docs more carefully

**Comment by nicolo-ribaudo** [comment]
Glad that it worked!
Note that `exclude: helpers.root('src/public/js/lib')` doesn't exclude `node_modules`: this may cause unnecessary work by Babel and thus make your build process slow. I'd suggest using `exclude: [helpers.root('src/public/js/lib'), /node_modules/]` (unless you are not requiring libs installed from npm).
