### ISSUE TITLE
Show deprecation warnings on install rather than dependency resolve

### ISSUE THREAD

**Issue by czukowski** [babel/babel#6871]
**Feature request**

### Context

If a lock file is already present, deprecation messages are not displayed (seems to be the same with yarn or npm install), because the dependencies are not being resolved in that case, so when creating a new local copy of a project that uses deprecated presets, the developer will not see the warnings. Even if a deprecated preset is added for the first time, a developer might want to get back to fixing it later, but the lack of messages may cause the developer to forget about until packages update, which doesn't have to be frequent. It may be even worse if there are multiple developers involved.

If deprecation warnings were displayed on package install, then constant reminders would make somebody fix the issue sooner or later. _Especially CI users will benefit because the warnings would be present in every build log until it is fixed_. As of now, from looking at build logs, everything seems okay while in fact something is not.

Unfortunately, I don't know whether emitting a warning on package install is in the package developers powers.

### Expected Behavior

Example of yarn output I would like to see in build logs whenever outdated Babel preset is installed: 

```
[1/4] Resolving packages...
[2/4] Fetching packages...
warning babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
warning babel-preset-latest > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning babel-preset-latest > babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning babel-preset-latest > babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```

### Current Behavior

Example of actual yarn output:

```
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```

**Comment by xtuc** [comment]
Closing, out of scope for now.
