### ISSUE TITLE
Using inline function expression with abreviated object syntax yields wrong function name

### ISSUE THREAD

**Issue by jjant** [babel/babel#6878]
Choose one: is this a bug report or feature request?
Bug

Inline function expression inside object definition yields a function with a wrong name.

### Input Code
Repl link: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=IYAgvA3iBmCuB2BjALgSwPbwBQEoIF8R8AoYAOjiTUzPmAFsBTcMMEAIkpQ3naA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose%2Cenv&targets=&version=6.26.0

```js
  a = { function(){} }
  a.function.name === "function"
```

### Expected Behavior
`a.function.name` should be `"function"`

### Current Behavior
`a.function.name` is `"_function"`

### Possible Solution
Just set the created function's name to `function` if it didn't have a name.

**Comment by gmmorris** [comment]
hmm this is an interesting one.
You can't name the function "function" as that isn't valid syntax.
`
const a = {
  function: function function() {} // "SyntaxError: Unexpected token function"
};
console.log(a.function.name);
`

But, if you leave it anonymous, it seems to inherit the name from the property:
`
const a = {
  function: function() {}
};
console.log(a.function.name); //prints "function"
`

**Comment by jjant** [comment]
Ah, I had thought of doing something more complicated, in case the function created by Babel had to be named (for some reason):

```
const a = {
  function: (function(){
    const myFunc = function _function(){};
    Object.defineProperty(myFunc, 'name', { value: 'function', writable: false });
    return myFunc;
  })
}
```

But this is clearly way more complicated.

**Comment by xtuc** [comment]
Closing, out of scope for now.
