### ISSUE TITLE
Comments inside call brackets goes outside it

### ISSUE THREAD

**Issue by rifler** [babel/babel#6884]
### Input Code

```js
const obj = {
    field: ((json) => json)(
        // MUST be spaces from line start before gulp-include directive
        /*=include ./data.json */
    ),
};
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    compact: false,
    ast: false,
    plugins: ['external-helpers'],
    presets: [['es2015', {modules: false}]],
}
```

### Expected Behavior
```js
var obj = {
    field: (function (json) {
        return json;
    })({"data": {"from": "data.json file"}}),
};
```

### Current Behavior
```js
var obj = {
    field: function (json) {
        return json;
    }
    {"data": {"from": "data.json file"}}
    (),
};
```

### Possible Solution
1) Ignore this file and write es5 in it;
2) Call `gulp-include` before `gulp-babel`.

### Context
For some reasons we don't use general module systems like `commonjs` or `es6 modules` (don't ask why :disappointed:), just concatenate files.
In rare cases we use `gulp-include` plugin to include external code (from npm for example) or generated data files.
As I wrote above in `Possible Solution`, we can call `gulp-include` before `gulp-babel`, but in case of including code (not data) it will be processed by babel and we won't to do this.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  gulp-babel@6.1.2, babel-core@6.25.0
| node             | 6.5.0
| npm              | 3.10.3
| Operating System | ubuntu 14.04

**Comment by loganfsmyth** [comment]
Unfortunately, comment placement is only kind of a best-effort thing for us. Since there are no function params, there's nothing for the comment to attach to between the `()`, so the comment gets associated with the next closest thing, which breaks your code. I think running include before would be your best option.

**Comment by rifler** [comment]
ok, thanks for quick answer
