### ISSUE TITLE
transformFile generates incorrect AMD ids

### ISSUE THREAD

**Issue by nico29** [babel/babel#6885]
I am not sure the following behavior is intended or not, hence this issue is more a question than a bug report. 

When using babel-core `transformFile` to perform async code conversion from es modules to AMD modules (with the `babel-plugin-transform-es2015-modules-amd` plugin), the generated AMD module ID is incorrect.
Let's take the following exemple:

### Input Code

```js
const { promisify } = require('util');
const babel = require('babel-core');
const transformFile = promisify(babel.transformFile);

const config = {
    presets: 'env',
    plugins: ['transform-es2015-modules-amd'],
    moduleRoot: 'ROOT',
    moduleIds: true,
    getModuleId (moduleName) {
        return moduleName;
    }
};

async function transpile () {
    const files = [
        './src/a.js',
        './src/b.js',
        './src/c.js'
    ]
    return Promise.all(files.map(async file => {
        let { code } = await transformFile(file, config);
        console.log(code);
        return Promise.resolve(code);
    }));
}
transpile();
```

### Current Behavior

The previous code outputs : 

```js
define("ROOT/./src/c", [], function () {
  "use strict";
});
define("ROOT/./src/c", [], function () {
  "use strict";
});
define("ROOT/./src/c", [], function () {
  "use strict";
});
```

### Expected Behavior

where you would expect it to be:

```js
define("ROOT/./src/a", [], function () {
  "use strict";
});
define("ROOT/./src/b", [], function () {
  "use strict";
});
define("ROOT/./src/c", [], function () {
  "use strict";
});
```

### Possible Solution

I've found that `transformFile` stores the file name inside the configuration object by modifying the reference of the user provided object.
Since this bit is done synchronously the configuration object will have the last file name (in our case './src/c.js'.

I would like to know if the "cloning" of the config is to be done by the user or by `transformFile`: that is to say turn my code from what is was to something like:

```js
async function transpile () {
    const files = [
        './src/a.js',
        './src/b.js',
        './src/c.js'
    ]
    return Promise.all(files.map(async file => {
        let { code } = await transformFile(file, {...config});
        console.log(code);
        return Promise.resolve(code);
    }));
}
```

or turn [this line](https://github.com/babel/babel/blob/master/packages/babel-core/src/transform-file.js#L21) into something like `let options = Object.assign({}, opts, { filename })`. `options` being used to keep the user provided object intact.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | MacOS 10.12.6

Thank you 😸

**Comment by loganfsmyth** [comment]
This should be fixed by https://github.com/babel/babel/commit/98969b8a7335e831c069164f5c56132111847224#diff-d0ac609d428f3a4e7713be3f2713ced4L17 on Babel's 7.x beta since we no longer mutate the options object that are passed in.

I think for now on Babel 6 your explicit `{...opts}` is probably the best bet.

**Comment by loganfsmyth** [comment]
Oh wait I'm dumb :P It was supposed to be fixed by that, but I totally didn't do it right :P Missed your comment.

    opts = Object.assign(opts, { filename });

should absolutely be

    opts = Object.assign({}, opts, { filename });

**Comment by mmckeaveney** [comment]
I can take a look at this one.

**Comment by nico29** [comment]
@mmckeaveney oups sorry, I did not see your comment and opened a PR 😥

**Comment by mmckeaveney-r7** [comment]
no problem @nico29  :smile:
