### ISSUE TITLE
How to import @babel/standalone?

### ISSUE THREAD

**Issue by wangdicoder** [babel/babel#6887]
Hi, I'm trying to import the standalone package into my project, but it seems doesn't work. 
my code is `import Babel from '@babel/standalone';`

I tried to log the variable `Babel`, and it shows **undefined**, so what's the right way to declare it?
Actually, I want to use `transform()` function.

Cheers,

**Comment by loganfsmyth** [comment]
For those coming across this, you need to do `* as`

    import * as Babel from '@babel/standalone';
