### ISSUE TITLE
[pipeline operator] support await

### ISSUE THREAD

**Issue by xtuc** [babel/babel#6889]
Choose one: is this a bug report or feature request?

### Input Code

```js
promise |> await
```

which is the equivalent of

```js
await promise
```

### Expected Behavior

```js
var _promise;

_promise = promise, await _promise;
```

### Current Behavior

```
Parse error: await is a reserved word (1:11)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System | 

As described in the spec [here](https://github.com/tc39/proposal-pipeline-operator#use-of-await).

**Comment by lilijialiang** [comment]
Will not continue to support `await` ? sorry to disturb.

**Comment by xtuc** [comment]
Sorry I don't understand your point @lilijialiang. This is only an addition to the existing support in Babel.

**Comment by ksmithbaylor** [comment]
Does the spec actually support this? The example in the README only shows

```javascript
x |> await f
```

which is an equivalent of

```javascript
await f
```

And in the current grammar defined in the spec draft, there is no option for a RHS without a *LogicalORExpression* expansion.

**Comment by mAAdhaTTah** [comment]
This is not currently specced yet but will be supported in the parser in #7458 and eventually added as an option in the pipeline plugin.

**Comment by mAAdhaTTah** [comment]
@thiagoarrais I'll be implementing this as part of the F# parsing. It's not strictly necessary to track but isn't technically "resolved". Up to the maintainers what they want to do here.

**Comment by thiagoarrais** [comment]
Sorry for the noise. I interpreted that this was already implemented in F#.

**Comment by nicolo-ribaudo** [comment]
I added this to https://github.com/babel/babel/projects/9#card-17016058 so we don't forget to close it when it is fixed

**Comment by nicolo-ribaudo** [comment]
Supported by https://github.com/babel/babel/pull/9984
