### ISSUE TITLE
JSON.stringify converts certain object members to strings before stringifying

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [babel/babel#6891]
This is a bug report.

JSON.stringify is converting certain member objects into strings before applying JSON.stringify on the target object.
In other words, it appears that JSON.stringify is recursively applying itself to children objects, resulting in those objects being represented as strings before the final stringification.

This only happens for parent-most array members of the supplied object to JSON.stringify.

### Input Code

```js
JSON.stringify({
	test: [
		{
			one: "2"
		}
	]
});
```

#### package.json
```js
{
	...
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"build": "webpack"
	},
	"dependencies": {
		"react": "^16.0.0",
		"react-dom": "^16.0.0"
	},
	"devDependencies": {
		"babel-core": "^6.26.0",
		"babel-loader": "^7.1.2",
		"babel-preset-env": "^1.6.1",
		"babel-preset-react": "^6.24.1",
		"webpack": "^3.8.1"
	},
	"babel": {
		"presets": [
			"env",
			"react"
		]
	}
}

```

#### webpack.config
```js
module.exports = {
	... 
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'babel-loader'
			}
		]
	}
};
```

### Expected Behavior

Output string: `{"test":[{"one": "2"}]}`
Converting back to object:
```js
{
	test: [
		{
			one: "2"
		}
	]
}
```

### Current Behavior

Output string: `{"test":"[{\"one\": \"2\"}]"}`
The array object assigned to 'test' is converted into a string, and then that is stringified.

When converting this back into an object, you'll get:
```js
{
	"test": "[{\"one\": \"2\"}]"
}
```

### Possible Solution

Refactoring of JSON.stringify polyfill.

### Context

Trying to serialise data for communication.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-core | 6.26.0
| babel-loader | 7.1.2
| babel-preset-env | 1.6.1
| babel-preset-react | 6.24.1
| node | 6.11.0
| npm | 3.10.10
| Operating System | Windows 10 Enterprise 64-bit

**Comment by Daniel-Khodabakhsh** [comment]
Seems to be fixed in Babel 7? https://runkit.com/embed/u7byn631ku0d
Does anyone know when Babel 7 will be released?

**Comment by hzoo** [comment]
Yeah can close then. You can test it out with v7 or easiest you can use the repl on the master build https://babeljs.io/repl/build/master which usually should work!

**Comment by hzoo** [comment]
Closing if it's fixed in v7 beta
