### ISSUE TITLE
'Jest' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by daniel-234** [babel/babel#6892]
Choose one: is this a bug report or feature request?
Bug report.

After installing Babel Env preset with npm, Jest is deleted from the **package-lock.json** file. 

### Input Code

```
npm install --save-dev babel-preset-env
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

**.babelrc**
```js
{
  "presets": ["env"]
}
```

**package.json**
```js
{
  "devDependencies": {
    "babel-preset-env": "^1.6.1"
  },
  "scripts": {
    "test": "jest"
  }
}
```

### Expected Behavior

If I run `npm test`, the output should be:
```
> @ test C:\Users\Daniel\testing-with-jest\test-npm
> jest

 PASS  __tests__\sum.js
  √ the sum of 1 and 3 returns 4 (16ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.265s
Ran all test suites.
```

### Current Behavior

When I run `npm test`, the actual output is: 
```
> @ test C:\Users\Daniel\testing-with-jest\test-npm
> jest

'jest' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```

### Possible Solution

The Jest package should not be deleted from the **package-lock.json** file when installing the Env preset with _npm_. 
One possible solution would be to add Jest to the _devDependencies_ options in the **package.json** file, similar to what _yarn_ does. In fact this problem only affects _npm_ and not _yarn_. 
I solved this issue by manually adding a _devDependencies_ section to the **package.json** file when I added the _scripts_ section. At this point the Env preset has not yet been installed.
```js
{
  "devDependencies": {
    "jest": "^21.2.1"
  },
  "scripts": {
    "test": "jest"
  }
}
```
If I install the Env preset now with _npm_, my **package.json** file looks like this:
```js
{
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "jest": "^21.2.1"
  },
  "scripts": {
    "test": "jest"
  }
}
```
and Jest is not deleted anymore from the **package-lock.json** file. 

### Context

I am trying to clarify how to get started with Jest and configure the environment to use Babel, by following the Introduction section of the official Jest documentation and the Env preset Docs. 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 6.11.5
| npm              | 5.5.1
| Operating System | Windows 10 Home

**Comment by nicolo-ribaudo** [comment]
This isn't a bug with babel or npm. If you want to use a package, you must always add it to either `dependencies` or `devDependencies` in your package.json. I'm actually surprised that it worked bfore installing `babel-preset-env`.

**Comment by nicolo-ribaudo** [comment]
Probably it worked with yarn because it adds the packages you install to your package.json file by default.
When using npm, you should do `npm install --save-dev jest` (or just `--save`, depending if it is a devDependency or a runtime dependency)
