### ISSUE TITLE
There is no way to traverse the top level path.

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#6894]
```js
path.traverse({
  "AnyNode"(p) {
    console.log(p);
  }
});
```

`path` is never visited, only its children. I think this behavior is useful sometimes, but I'd expect `path` to be visited (except when it is a `File` maybe). What do you think?

https://astexplorer.net/#/gist/d9ea66043a67ff29ac46f661081d3945/59a81b02985e1b14881491b655172bb3f51948ef

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32

**Comment by maurobringolf** [comment]
Yes 👍  I experienced this in #6855  and built a weird workaround instead. The specific use case I had:

Traverse the key expression in a computed property. In this case it was a class property, but I guess it would be the same with object properties. My intuition would have been to use `path.get("key").traverse(someVisitor)` on the property node. But this skips the top level node of the property computation. The current workaround is to traverse the complete property node and use `path.skip()` on the value node.

**Comment by nicolo-ribaudo** [comment]
Yes, I built that example based on our discussion :smile:

**Comment by xtuc** [comment]
Closing, out of scope for now.
