### ISSUE TITLE
Breaks conditional extends

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#6895]
> Original issue submitted by @johanjisu in https://github.com/babel/minify/issues/739

minify breaks code with conditional extends, such as this:

```js
export default Target => class Events extends (Target || Base) {

}
```

Minification removes () around Target || Base, which breaks it.

(the code above is used for mixins, Base is an existing class)

**Comment by nicolo-ribaudo** [comment]
Reproduction: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjAFAIWgB9DoBhASmgG8BfIA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=&prettier=false&targets=&version=7.0.0-beta.32

**Comment by Andarist** [comment]
JavaScript still amazes me 😂
