### ISSUE TITLE
transform-flow-strip-types removes all jsdoc comments.

### ISSUE THREAD

**Issue by ozum** [babel/babel#6898]
This is a bug report.

`babel-plugin-transform-flow-strip-types` removes all `jsdoc` comments, if source file contains only `flowtype` code and no regular javascript. When there is some regular javascript code i.e. `const a = 1`, jsdoc comments are preserved.

### Input Code

```js
// @flow
/**
 * Description of type
 * @typedef  {Object} SomeType
 * @property {string} name - name
 */
export type SomeType = {| name: string |};
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": [
    "flow", ["env", { "targets": { "node": "current" }, "useBuiltIns": true }]
  ],
  "plugins": [
    "add-module-exports",
    "transform-export-extensions"
  ],
  "env": {
    "test": {
      "plugins": [
        ["istanbul", { "useInlineSourceMaps": false }]
      ]
    }
  }
}
```

### Expected Behavior
```js
"use strict";
//# sourceMappingURL=rule-config.js.map
/**
 * Description of type
 * @typedef  {Object} SomeType
 * @property {string} name - name
 */
```

### Current Behavior
```js
"use strict";
//# sourceMappingURL=rule-config.js.map
```

### Possible Solution
Comments should be preserved, even there is no js code.

### Context
I'm using `flow` for static type checking and `jsdoc` for documentation purposes. Since `babel-plugin-transform-flow-strip-types` removes all jsdoc comments, documentation affected negatively.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 9.2.0
| npm              | 5.5.1
| Operating System | macOS 10.12.6

**Comment by Arfey** [comment]
Are you sure that it's `transform-flow-strip-types` remove comments?
`transform-flow-strip-types` remove only comments that including `@flow`.

You can see test for your case:
**actual**
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-flow-strip-types/test/fixtures/strip-types/strip-directive/actual.js
**expected**
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-flow-strip-types/test/fixtures/strip-types/strip-directive/expected.js

**Comment by nicolo-ribaudo** [comment]
It's because that comment is attatched to the tpe declaration node, which is removed.

**Comment by ozum** [comment]
@Arfey, I'm sure it's from `transform-flow-strip-types`, I tried by removing all other plugins.

@nicolo-ribaudo, yes it is a type declaration comment, but not a flow comment. As @Arfey said, only comments that includes `@flow` should be removed. Also if I add a single expression, comments are not deleted. Please see two examples below:

## Without regular JS

```js
// @flow
/**
 * Description of type
 * @typedef  {Object} SomeType
 * @property {string} name - name
 */
export type SomeType = {| name: string |};
```

is transpiled to

```js
"use strict";
//# sourceMappingURL=fields.js.map
```

## With regular JS

```js
// @flow
/**
 * Description of type
 * @typedef  {Object} SomeType
 * @property {string} name - name
 */
export type SomeType = {| name: string |};
1;
```

is transpiled to:

```js
"use strict";

1;

/**
 * Description of type
 * @typedef  {Object} SomeType
 * @property {string} name - name
 */
//# sourceMappingURL=fields.js.map
```

**Comment by loganfsmyth** [comment]
Hmm, this is a tough one. We probably can address this with special logic if we decide to, but no matter what you'll kind of be walking a fine line. We don't generally guarantee that comments will pass through as-is, for Babel transforms because our parsed representation isn't exact for comments.

**Comment by xtuc** [comment]
Closing, out of scope for now.
