### ISSUE TITLE
Why is Babel putting my imports after my exports?

### ISSUE THREAD

**Issue by JLRishe** [babel/babel#6919]
Choose one: bug report (possibly)

I'm new to Babel and trying to figure out the correct way to make use of babel-external-helpers in a project that uses ES6 modules and targets Node and browsers.

I have a [lengthy question about this](https://stackoverflow.com/questions/47504438/trouble-using-babel-external-helpers-with-es6-modules-babel-reordering-imports) on StackOverflow, and [a repo](https://github.com/JLRishe/babel-helpers-e6-modules-issue) demonstrating the issue, but the SO question hasn't received much attention yet. In the interest of brevity, I'll give the condensed version here.

I've created a babel-external-helpers file with the `-t global` option, so I am referencing it in my index.js file like this so that it can run before everything else and add the helpers to the global scope:

```js
import './babel-helpers';

export * from './fileThatNeedsExternalHelpers';
```

If I run this through Babel with the `env` preset and the `external-helpers` plugin, I get this output:

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _fileThatNeedsExternalHelpers = require('./fileThatNeedsExternalHelpers');

Object.keys(_fileThatNeedsExternalHelpers).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _fileThatNeedsExternalHelpers[key];
    }
  });
});

require('./babel-helpers');
```

We can see that what corresponds to the `import` has been moved to the end of the file, and my code won't run because my `fileThatNeedsExternalHelpers` needs the external helpers to be in the global scope when it executes (e.g. it uses syntax which, when transpiled, uses the `defineProperty` helper). If I manually edit the output file to move `require('./babel-helpers');` above the `var` line, everything runs fine.

So my questions are:
- What is the reason for rearranging imports and exports like this, and is there a (simple) way to control/suppress it?
- Am I going about using external helpers the wrong way? Is there a better approach? I believe I could put the helpers in a module and explicitly `import` them in each file that needs them, but that doesn't seem like a very good solution.

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | 8.9.1
| npm              | 5.0.3
| Operating System | Win 10

**Comment by loganfsmyth** [comment]
The reordering bug is a duplicate of https://github.com/babel/babel/issues/6468, which has been fixed in Babel's 7.x beta.

> What is the reason for rearranging imports and exports like this, and is there a (simple) way to control/suppress it?

100% a bug.

> Am I going about using external helpers the wrong way?

Not necessarily, but I do have questions. Are you writing a library or an application? Using global `babelHelpers` in an application is reasonable, and you'd be unlikely to see a `export * from ""` in an application. That makes me think you're writing a library. Given that, I'd personally recommend against using `external-helpers`, because it greats a global, and usually creating globals in libraries is dangerous since it can make things conflict.

**Comment by JLRishe** [comment]
@loganfsmyth Thank you very much for the fast reply. I tried to search for existing issues about this but probably didn't search well enough.

Re: your question, I am creating a library, and now that you point it out, I realize that I hadn't fully thought through the implications of adding the helpers to the globals. Is there a straightforward way to use the helpers non-globally without explicitly `import`ing them in each file that needs them?

**Comment by loganfsmyth** [comment]
Unless you're library's really huge, I'd probably just rely on the normal behavior of including them in each file.

You could also explore using `babel-plugin-transform-runtime`, but it may make your library even heavier than just including them in each file. We're hoping to address some of that in future Babel versions, but things are limited right now.

You could also explore building with Rollup. Rollup with the Babel plugin can be a bit better at handling the helpers without duplicating them.

**Comment by JLRishe** [comment]
@loganfsmyth Awesome. Thank you for the advice. As a matter of fact, I am planning to use Rollup, but thought I would need to use it sequentially with Babel as I didn't know it had a Babel plugin. I will look into that.

Thanks again!
