### ISSUE TITLE
atchtoProps

### ISSUE THREAD

**Issue by sumanair** [babel/babel#6925]
Choose one: is this a bug report or feature request?

### Input Code

```js
var your => (code) => here;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by xtuc** [comment]
I'm going to close this since it looks like it was unintentional.
