### ISSUE TITLE
Babel returns invalid code when using `arguments.callee`.

### ISSUE THREAD

**Issue by jjant** [babel/babel#6927]
Choose one: is this a bug report or feature request?
Bug

### Input Code
repl: https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=GYAgvCAUwK4HYGMAuBLA9nSAPANASgG8BuAJwFMkYS4psA-ABjxAH4osAqSSAQxIHMYAWzJwkAZwB0CHgBtZZMnjzdsAWgCMy_MwBcILUSIBfPACgzwSACY8QA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Cbabili&prettier=false&targets=&version=6.26.0

```js
f = (function(x,){;return ((x>0) ? (x*((arguments.callee))(((x-1)),)) : 1);;})

f(2)
```

### Expected Behavior
Returns working code.

### Current Behavior
Returns the following code:
```js
"use strict";f=function f(a){return 0<a?a*arguments.callee(a-1):1},f(2);
```

Which is invalid code because it uses `arguments.callee` in strict mode.

### Possible Solution
Change `arguments.callee` to the function name (`f`) in this case.

**Comment by jjant** [comment]
@nicolo-ribaudo But I want to have my code compiled to **valid** strict code, and this should be (sort of easily) doable.

**Comment by loganfsmyth** [comment]
`arguments.callee` is not available in strict code, and it is not something that Babel handles. It is generally a feature that should be avoided. I assumed the issue here was that you were compiling old existing ES5 code. If you're writing new ES6, you should not use it.

**Comment by loganfsmyth** [comment]
I guess this is something we could support, but it's generally dramatically more readable to just name the function yourself.

**Comment by nicolo-ribaudo** [comment]
This is correct. If you are parsing your code as a module, `arguments.callee` should throw. If you want it to work you need to parse your code as a script ([docs](https://babeljs.io/docs/en/options#sourcetype)) and disable the modules transform.
