### ISSUE TITLE
[Babylon] API to manually generate AST?

### ISSUE THREAD

**Issue by bcherny** [babel/babel#6928]
Is there a stable API to generate a TypeScript/Flow AST, which I can then stringify with [https://github.com/babel/babel/tree/master/packages/babel-generator](babel-generator)?

What I'm looking for is a more general (ie. also supports Flow) and stable version of [TypeScript's AST API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#creating-and-printing-a-typescript-ast).

**Comment by nicolo-ribaudo** [comment]
I'm not sure about what you are asking, but I hope that one of this snippets might be delivered answer:
```js
// Generate the AST without Babel

var babylon = require ("babylon");
var ast = babylon.parse("a + 2;");
```

```js
// Generate an AST without starting from the code
var t = require("babel-types");
var ast = t.expressionStatement(
  t.binaryExpression("+",
    t.identifier("a"),
    t.numberLiteral(2)
  )
);
```

**Comment by bcherny** [comment]
Thanks @nicolo-ribaudo - [babel-types](https://github.com/babel/babel/tree/master/packages/babel-types) is what I was looking for. I didn't see it mentioned in the docs as the way to build ASTs manually.

**Comment by hzoo** [comment]
also https://github.com/babel/babel/tree/master/packages/babel-template
