### ISSUE TITLE
Spread operator does not implement iterator

### ISSUE THREAD

**Issue by ksashikumar** [babel/babel#6930]
Choose one: is this a bug report or feature request?

**Bug**

### Input Code

```js
Array.prototype[Symbol.iterator] = function() {
  throw new Error();
}
var parts = ['shoulders', 'knees']; 
var lyrics = ['head', ...parts, 'and', 'toes']; 
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
presets -latest

### Expected Behavior

```js
➜ cat index.js
Array.prototype[Symbol.iterator] = function() {
  throw new Error();
}
var parts = ['shoulders', 'knees']; 
var lyrics = ['head', ...parts, 'and', 'toes'];                                                                                                                              

➜ d8 index.js
index.js:2: Error
  throw new Error();
  ^
Error
    at Array.(anonymous function) (index.js:2:9)
    at index.js:5:26
```

### Current Behavior
No Error

### Possible Solution
[`SpreadElement`](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-arrayaccumulation) specification states, the AssignmentExpression's iterator is used to iterate. This should be transpiled to something similar to `for...of` ?
`plugin-transform-spread` should be rewritten?

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by hzoo** [comment]
We assume you aren't going to modify built-ins, especially for an array like that. If you use our [repl](https://babeljs.io/repl/) you'll find it compiles to a concat. Also `babel-preset-latest` is deprecated so I'd recommend using preset-env instead.

http://babeljs.io/docs/usage/caveats/ I'd say that is another caveat, we assume you haven't modified it in that way

**Comment by ksashikumar** [comment]
@hzoo Actually, I was trying to find the root cause of this bug: https://github.com/babel/babel/issues/5147. I was playing around with spread operator and found this issue. `babel-plugin-transform-spread` just transpiles the spread in array to `concat`. My question is, if v8's internal implementation of `SpreadElement` uses the `iterator` of the expression, should babel also not transpile using iterator?

**Comment by apapirovski** [comment]
I wonder if Babel should always use `Array.from` in these situations? That will then use the iterator without the need for writing any customs code on Babel's part. Of course, the problem is that this will be significantly worse for performance than the current `concat` or `for` loop code.

**Comment by Andarist** [comment]
`Array.from` is a part of es6 and forcing people to use global polyfills to use spread operator doesn't seem to be right.

**Comment by apapirovski** [comment]
@Andarist I mean, it's already using `Array.from` in the helper, it just checks whether it's an Array first and branches based on that. Just musing here...

**Comment by Andarist** [comment]
Oh, I always forget about normal mode :D using `loose` exclusively in my projects.
