### ISSUE TITLE
Cannot build Typescript AST

### ISSUE THREAD

**Issue by dpoindexter** [babel/babel#6933]
_Is this a bug report or feature request?_
Bug report

I'm writing a plugin to add Typescript type annotations to existing code. Some of the `@babel/types` builders seem to be configured to expect Flow nodes as arguments instead of the Typescript equivalents. In particular, nodes with `typeParameters` fields expect `TypeParameterDeclaration`.

### Input Code

```js
path.node.init.returnType = path.node.init.returnType = t.tSTypeAnnotation(
  t.tSTypeReference(
    t.tSQualifiedName(t.identifier('React'), t.identifier('SFC')),
    t.tSTypeParameterInstantiation([t.tSAnyKeyword()])
  )
);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    sourceType: 'module',
    allowImportExportEverywhere: false,
    allowReturnOutsideFunction: true,
    allowSuperOutsideMethod: true,
    plugins: [
        "typescript",
        "jsx",
        "asyncGenerators",
        "classProperties",
        "doExpressions",
        "exportExtensions",
        "functionBind",
        "functionSent",
        "objectRestSpread",
        "dynamicImport"
    ]
}
```

### Expected Behavior

I would expect the code above to generate a type annotation like this:

```js
... React.SFC<any> ...
``` 

### Current Behavior

When running the plugin via `@babel/traverse`, I get the following stack trace:
```
TypeError: Property typeParameters of TSTypeReference expected node to be of a type ["TypeParameterInstantiation"] but instead got "TSTypeParameterInstantiation"
    at Object.validate (C:\Users\dpoindexter\Dev\Experiments\babel-codemod\node_modules\@babel\types\lib\definitions\index.js:86:13)
    at validate (C:\Users\dpoindexter\Dev\Experiments\babel-codemod\node_modules\@babel\types\lib\index.js:512:9)
    at Object.builder (C:\Users\dpoindexter\Dev\Experiments\babel-codemod\node_modules\@babel\types\lib\index.js:476:7)
```

### Possible Solution

It looks like `@babel/types` hasn't been comprehensively updated, but I don't know it well enough to be sure of intent. It seems that node types like `TypeParameterDeclaration` need to either become a shared alias, or everywhere that expects a `TypeParameterDeclaration` needs to become a union `TypeParameterDeclaration | TSTypeParameterDeclaration`.

I'm happy to create a PR with a fix if that seems like the right approach!

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  @babel/core 7.0.0-beta.32
| node             | 8.4.0
| yarn              | 1.3.2
| Operating System | Windows 10

**Comment by existentialism** [comment]
@dpoindexter I think we just need to update the [TS-related types](https://github.com/babel/babel/blob/master/packages/babel-types/src/definitions/typescript.js) with `TSTypeParameterDeclaration` since we split the types in https://github.com/babel/babylon/pull/710.

Would love a PR for this, let us know if you hit any snags! (Or join our slack!)

**Comment by loganfsmyth** [comment]
@existentialism Seems like a good first issue?

**Comment by existentialism** [comment]
@loganfsmyth yep, was just taking up @dpoindexter's offer for a PR... but we can open it up as GFI if he's interested

**Comment by loganfsmyth** [comment]
Woops! Missed

> I'm happy to create a PR with a fix if that seems like the right approach!

@dpoindexter it's all yours if you want it :P

**Comment by dpoindexter** [comment]
@loganfsmyth Yep, I'll take a shot at it.
