### ISSUE TITLE
[Babylon] [TypeScript] Error parsing upper bounded generic

### ISSUE THREAD

**Issue by bcherny** [babel/babel#6934]
Choose one: is this a bug report

Repro case: https://astexplorer.net/#/gist/acb2e22639dd2bb80c91629efdffc089/c624fe282ae9cdb4ef05948ad8bc025404246ce0

### Input Code

```ts
type A = <B extends string>(b: B) => number;
```

### Expected Behavior

It should parse similarly to its Flow equivalent:

```js
type A = <B: string>(b: B) => number
```

### Current Behavior

```
Unexpected token, expected , (1:12)
```

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 7.0.0-beta.31
| node             | 
| npm              | 
| Operating System |

**Comment by nicolo-ribaudo** [comment]
It should be fixed by https://github.com/babel/babel/pull/6828

**Comment by bcherny** [comment]
My mistake - I failed to enable TypeScript mode when parsing.
