### ISSUE TITLE
[Babylon] [TypeScript] Error parsing type assertion

### ISSUE THREAD

**Issue by bcherny** [babel/babel#6935]
Choose one: is this a bug report

Repro case: https://astexplorer.net/#/gist/53298b2de259a44b60d431a0cc29b0ee/c2191729041b2fd8f1003c768d9e7382337799f7

### Related Issues

- https://github.com/babel/babel/issues/1152

### Input Code

```ts
let a = (4 as any)
```

### Expected Behavior

It should parse similarly to the Flow equivalent:

```js
let a = (4 : any)
```

### Current Behavior

```
Unexpected token, expected , (1:11)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 7.0.0-beta.31
| node             | 
| npm              | 
| Operating System |

**Comment by nicolo-ribaudo** [comment]
You need to enable the `typescript` plugin, not `flow`.

https://astexplorer.net/#/gist/53298b2de259a44b60d431a0cc29b0ee/97ae07184294f3bd7c63a26bd3c0423a2b25b241

**Comment by bcherny** [comment]
My silly mistake - thanks @nicolo-ribaudo.
