### ISSUE TITLE
Infer string quotes

### ISSUE THREAD

**Issue by sebmck** [babel/babel#694]

**Comment by eventualbuddha** [comment]
Is this for preserving the original quotes?

**Comment by sebmck** [comment]
@eventualbuddha Yeah. If a file contains single quotes then the code generator will just adopt that for all string literal generation.

**Comment by awerlang** [comment]
+1

**Comment by aexmachina** [comment]
:+1: :)

**Comment by sebmck** [comment]
Superseded by #883.
