### ISSUE TITLE
Computed default value in destructuring assignment not working correctly

### ISSUE THREAD

**Issue by hokennethk** [babel/babel#6940]
Bug Report

### Input Code

```js
const {
  foo = !!foo
} = {}

foo // should be reference error, but is false from babel
```
tested in babel repl v.6.26.0, using all presets

### Expected Behavior

If I copy paste the above code into a node repl (v.8.2.0), I get a ReferenceError.
If I copy paste the above code into the chrome console (Chrome v. 62.0.3202.94), I get a ReferenceError

### Current Behavior

The output from the babel REPL is 

```js
"use strict";

var _ref = {},
    _ref$foo = _ref.foo,
    foo = _ref$foo === undefined ? !!foo : _ref$foo;


foo; // should be reference error, but is false from babel
```
If I copy paste this into a node repl or chrome console, I get `false` instead of a ReferenceError

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             |  8.2.0

**Comment by nicolo-ribaudo** [comment]
Can you try to enable the `tdz` option in `babel-plugin-transform-block-scoping`? It is not documented and has some bugs, but it should handle that errors

**Comment by hokennethk** [comment]
@nicolo-ribaudo that works for me. Thanks for the quick reply!

For reference, here's my `.babelrc` which properly throws the `ReferenceError`:
```json
{
  "presets": ["env"],
   "plugins": [
    ["transform-es2015-block-scoping", {
      "tdz": true
    }]
  ]
}
```

The new output code with the plugin:
```javascript
"use strict";

var _ref = {},
    _ref$foo = _ref.foo,
    foo = _ref$foo === undefined ? !!function () {
  throw new ReferenceError("foo is not defined - temporal dead zone");
}() : _ref$foo;


foo;
```
