### ISSUE TITLE
async function hoisted above import 'babel-polyfill' ⇒ ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by andersk** [babel/babel#6956]
### Input Code

```js
import 'babel-polyfill';
async function foo() {}
```

([REPL link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAcgEYEMkFMA2BaSmCeAZsJpggNwBQKAzvgHYDGchArkzMBPSxBABQBKOAG8AvkA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Ces2016%2Ces2017&prettier=false&targets=&version=6.26.0))

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{"presets": [["env"]]}
```

### Expected Behavior

The `import` should be evaluated before the translation of the `async function` (which uses `regeneratorRuntime` and `_asyncToGenerator` from `babel-polyfill`).

```js
'use strict';

require('babel-polyfill');

var foo = function () {
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(…));
  return function foo() {…};
}();

function _asyncToGenerator(fn) {…}
```

### Current Behavior

The current output fails with `ReferenceError: regeneratorRuntime is not defined`.

```js
'use strict';

var foo = function () {
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(…));
  return function foo() {…};
}();

require('babel-polyfill');

function _asyncToGenerator(fn) {…}
```

Although I’m not an expert on the ES7 specification, I believe this violates [“NOTE: Before instantiating a module, all of the modules it requested must be available.”](https://www.ecma-international.org/ecma-262/7.0/#sec-moduledeclarationinstantiation)

### Possible Solution

Both `import` and `async function` are already hoisted; `import` should simply be hoisted to before hoisted functions.

### Context

This came up before as #5085, which was closed because you can work around it by moving the `async function` to a separate module. But that workaround should not be necessary. If nothing else, it’s an unnecessary trap for new users who probably think they have the wrong preset (I know I did). @loganfsmyth [commented](https://github.com/babel/babel/issues/5085#issuecomment-343375381):

> The interaction here is confusing and has a few cases. That said, either way I agree with you that getting the error your getting, just by declaring the code this way, is poor handling on our part. Changing the behavior of imports in our case would not be the right fix, but there *is* a fix we could do that we haven't done yet, which we probably should.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | Ubuntu 18.04

**Comment by Andarist** [comment]
As a workaround you might structure your entry point like this:
```js
import 'babel-polyfill'
import './app' // where your async is
```
Bundlers should preserve order and by the moment when the async gets run there already should be `regeneratorRuntime` available.

**Comment by zhouyu1993** [comment]
hello~

I first write `.bablerc` like this:

``` json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "> 1%",
            "last 3 versions",
            "ie >= 9",
            "ios >= 8",
            "android >= 4.2"
          ]
        },
        "useBuiltIns": "usage"
      }
    ],
    "stage-2"
  ]
}
```

And I don't add `import 'babel-polyfill'` in my entry file `app.js`.

It shows the error `regeneratorRuntime is not defined`.

So I add `import 'babel-polyfill'` in my entry file `app.js`. It works. But the file is big.

So I write `.bablerc` like this:

``` json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "> 1%",
            "last 3 versions",
            "ie >= 9",
            "ios >= 8",
            "android >= 4.2"
          ]
        },
        "useBuiltIns": false
      }
    ],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

It don't need to add `import 'babel-polyfill'` in my entry file `app.js`. And the file is smaller.

I guess that the option `useBuiltIns` is something wrong.

**Comment by loganfsmyth** [comment]
This should behave better in 7.x. It will only fail if you actually _call_ the function before the polyfill loads, instead of breaking because of function hoisting.

**Comment by tkrotoff** [comment]
@zhouyu1993 > don't need to add `import 'babel-polyfill'` [...] the file is smaller

Of course!!! you don't have any polyfill!
Check https://github.com/tkrotoff/babel-preset-env-example
