### ISSUE TITLE
Simple Typescript: "Unexpected token" with Babel 7

### ISSUE THREAD

**Issue by danielg2002** [babel/babel#6959]
Using Babel7 an error arise on a simple sentence, like "let result: string;"

"Unexpected token"

How i should configure Babel7 with ts?

**webpack.config:**
{
test: /\.(js|jsx|ts|tsx)$/,
loader: require.resolve('babel-loader'),
exclude: /(node_modules)/
},

**.babelrc**
{
    "presets": [
        [
            "@babel/env",
            {
                "targets": {
                    "browsers": [
                        "last 2 versions",
                        "safari >= 10"
                    ]
                },
                //"useBuiltIns": "usage",
                "debug": false
            }
        ],
        "@babel/stage-3",
        "@babel/react",
        "@babel/typescript"
    ],
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd",
                "style": true
            }
        ]
    ]
}

**partial package.json:**

"@babel/core": "7.0.0-beta.34",
"@babel/polyfill": "7.0.0-beta.34",
"@babel/preset-env": "7.0.0-beta.34",
"@babel/preset-react": "7.0.0-beta.34",
"@babel/preset-stage-3": "7.0.0-beta.34",
"@babel/preset-typescript": "7.0.0-beta.34",
"babel-core": "7.0.0-bridge.0",
"babel-jest": "21.2.0",
"babel-loader": "8.0.0-beta.0",
"ts-loader": "3.2.0",
"typescript": "2.6.2",

**tsconfig.json**

"module": "commonjs",
"target": "es5",
"lib": [
    "es6",
    "dom"
],
"moduleResolution": "node",
"jsx": "preserve",
"noEmit": true

**Comment by loganfsmyth** [comment]
Please include the full error message and stack trace, and webpack config if possible.

**Comment by danielg2002** [comment]
@loganfsmyth attached the files:
[webpack.config.dev.js.txt](https://github.com/babel/babel/files/1524148/webpack.config.dev.js.txt)

[tsconfig.json.txt](https://github.com/babel/babel/files/1524149/tsconfig.json.txt)

**Comment by loganfsmyth** [comment]
The full error message and stack trace is the most important part that we'll need.

**Comment by danielg2002** [comment]
How can i get a full stack info ?
Just says unexpected token over "let"

________________________________

**Comment by loganfsmyth** [comment]
Hmm, so there's nothing on the next line after than message? Maybe just show us exactly what output you see. I'd at least expect Webpack itself to have printed for instance the name of the file on the line above the error.

**Comment by danielg2002** [comment]
@loganfsmyth here the output:

Compiling...
Failed to compile.

./src/core/models/ContainerItemHelper.ts
Syntax error: /Users/daniel/Code/SnowflakeWeb2/src/core/models/ContainerItemHelper.ts: Unexpected token (177:8)
  175 | 
  176 |     static imageSourceBasedOnType(type: ContainerItemType): string {
> 177 |         let result: string;
      |         ^
  178 | 
  179 |         switch (type) {
  180 |             case ContainerItemType.Folder:

**Comment by loganfsmyth** [comment]
And there's no other text after that message?

That error seems strange to me, since there's clearly type annotations on the line before that. https://babeljs.io/repl/build/7.0/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oQC5iwS2GjwFswBzAUwGV4BXAJ2AoCFIKATAeQDsAVATwAOFABRYhFAFzQAwvG4483CvQCSWCsQHCAlNOz0lZFOgzQQFLNHoUItEFn1ZD3MgG5TAX1SegA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.0.0-beta.34 for instance seems to work fine.

When you said `let result: string;` was the error, I thought you meant it was a file containing `let result: string;` on its own. If there's a bunch more stuff, we need to see what that code is. Ideally you could reproduce the error on https://babeljs.io/repl/build/7.0/#?babili=false&browsers=&build=&builtIns=false&code_lz=Q&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.0.0-beta.34 and give us a link.

**Comment by danielg2002** [comment]
@loganfsmyth Hi Logan, more info after I turned on debug info...

Please, review attached image
<img width="1247" alt="error" src="https://user-images.githubusercontent.com/11050021/33589978-ef42ea0c-d95a-11e7-8a7a-1a91240d9e90.png">


My actual presets:

presets: [
        [
            '@babel/es2015',
            {
                targets: {
                    browsers: [
                        'last 4 Chrome versions',
                        'last 4 FireFox versions',
                        'last 2 Safari versions',
                    ],
                },
                debug: true
            }
        ],
        '@babel/typescript',
        '@babel/stage-3',
        '@babel/react',
    ]

**Comment by Kovensky** [comment]
I see. This reproduces your issue:

https://babeljs.io/repl/build/7.0/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYOwLgpgTgZghgYwgAgEJwF7IN4F8BQCANnAM6nIBiA9tTvssgEZxTIC8yAPOhgHx4GjYUIAW1AOYoAFAEp6w5EQhhkMAK4S4QggSA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.0.0-beta.34

Unlike TypeScript, Babel makes no distinction between `.ts` and `.tsx` files. You should write all your TypeScript files as if they are `.tsx`, which forbids the angle brackets cast.

You should change all your angle bracket casts to use `as` instead. In the reproduction example, `<Baz>{}` should be changed to `{} as Baz`.

Never use the `<type>` cast syntax if you can help it, as it is _impossible_ to distinguish it from JSX. It is why TypeScript forbids it in `.tsx` files, and forbids JSX in `.ts` files.

**Comment by danielg2002** [comment]
@Kovensky Hi, I did your suggestion and the unexpected token was fixed! thanks!

BUT, now says "`import =` is not supported."

Please, review attached screen...

I don't have any "import =" in my code, what that means?
<img width="1331" alt="erro2" src="https://user-images.githubusercontent.com/11050021/33591757-176fdfa2-d966-11e7-97be-d7b26b05fd4b.png">

**Comment by simonbuchan** [comment]
@Kovensky Untested, but with #7091 babel should now be able to behave like `tsc`:

```js
const common = ["@babel/env"];
module.exports = {
  overrides: [
    { test: /\.js$/, presets: common },
    { test: /\.jsx$/, presets: [...common, "@babel/react"] },
    { test: /\.ts$/, presets: [...common, "@babel/typescript"] },
    { test: /\.tsx$/, presets: [...common, "@babel/typescript", "@babel/react"] },
  ]
}
```

Babylon is perfectly happy to parse '<type> expr` with `syntax-typescript` so long as `syntax-jsx` is not also enabled.

Probably something to suggest in whatever typescript docs get added?

**Comment by danielg2002** [comment]
Hi @simonbuchan, my project is working very well from beta.35.

thanks!
I will close this issue.

**Comment by simonbuchan** [comment]
This was regarding the initial cast issue, not whatever the `import =` thing was.

To be fair to this issue, it's plausible that babylon could give an error with guidance like `tsc` when both typescript and JSX are enabled and it hits a syntax error after a old-style cast, but it's not obvious that it could do so in every case, for example the original issue here. Perhaps if it is "directly" inside a JSX opening element and it hits a "generic" syntax error it could try reparsing without JSX and if that passes (at least, further than the original error) issue similar guidance to `tsc`? Sounds flakey, but you already hit a parse error.
