### ISSUE TITLE
How to parse import() in dead code

### ISSUE THREAD

**Issue by mqklin** [babel/babel#6966]
I'm trying to dynamic import a module if I'm not in production mode:

    if (process.env.NODE_ENV !== 'production') {
      import('bugsnag-js');
    }

The problem is that in the dev mode I get this error:
`Uncaught SyntaxError: Unexpected token import`.

I noticed that babel doesn't transform `import` to webpack's `require`:
[![enter image description here][1]][1]

Howewer, it does, if condition is truly:
[![enter image description here][2]][2]

How can I avoid the mistake?

  [1]: https://i.stack.imgur.com/abFOL.png
  [2]: https://i.stack.imgur.com/Phnqa.png

ps I asked the question in [stackoverflow](https://stackoverflow.com/questions/47570829/how-to-parse-import-in-dead-code) and [slack](https://babeljs.slack.com/archives/C0DFJT81H/p1512043467000115) but nobody answered

**Comment by nicolo-ribaudo** [comment]
Babel doesn't transform `import()`s: webpack should do it. Can you reopen this issue at https://github.com/webpack/webpack/issues?

**Comment by mqklin** [comment]
Thanks, I will.

**Comment by nicolo-ribaudo** [comment]
Oh, it looks like there is already https://github.com/webpack/webpack/issues/4857

**Comment by mqklin** [comment]
Oh, thank you, Nicolo! I should search better next time
