### ISSUE TITLE
Using babel 7 with env preset: object spread causes error about missing objectRestSpread parser plugin

### ISSUE THREAD

**Issue by acusti** [babel/babel#6970]
This is a bug report.

### Input Code

First up, here’s my minimal reproducible repo for this issue: https://github.com/acusti/babel-7

Steps to reproduce:

- Clone the repo
- Run `npm install`
- Run either `npm run app` (uses webpack-dev-server) or `npm run build`

Result:
```
Module build failed: SyntaxError: /src/index.js: This experimental syntax requires enabling the parser plugin: 'objectRestSpread' (7:4)
```

The codes:

```js
const foo = { bar: true };
// Following line causes `Module build failed: SyntaxError: /src/index.js: This experimental syntax requires enabling the parser plugin: 'objectRestSpread'`
const bar = {
    ...foo,
    baz: false,
};
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

Occurs while using babel-loader with webpack 3.x and the following weback.config.js (no .babelrc in this case):

```js
module.exports = {
    entry: [
        path.resolve('./src'),
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env'],
                        },
                    },
                ],
                include: path.resolve('./src'),
            },
        ],
    },
    output: {
        path: path.resolve('./build'),
        filename: '[name].js',
    },
};
```

Error occurs when running `webpack-dev-server` and plain `webpack`.

### Expected Behavior
I expected the spread / rest parser plugins to be available by default when using `@babel/preset-env`. Failing that, I expected to be able to manually add the `@babel/transform-spread` plugin to get the code to compile.

Note that my use case and the minimal reproducible repo I created is based on using webpack with `babel-loader`.

### Current Behavior
When babylon encounters a use of the spread operator, it generates the following error:

```
ERROR in ./src/index.js
Module build failed: SyntaxError: /Users/andrew/Projects/babel-7/src/index.js: This experimental syntax requires enabling the parser plugin: 'objectRestSpread' (7:4)
```

### Possible Solution
My best guess is this is related to removing the `RestProperty` and `SpreadProperty` AST-nodes and reusing the `RestElement` and `SpreadElement` nodes in its place ([reference](https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors#ast-changes-removal) and babel/babylon#384), but I may be way off base.

I noticed that #6461 mentions issues with rest / spread with babel 7, but the resolution there was a misconfiguration, so I guess it’s unrelated.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.34
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | macOS 10.13.1
| babel-loader | 8.0.0-beta.0
| webpack      | 10.13.1

**Comment by existentialism** [comment]
@acusti currently, using `@babel/preset-env` without targets, is equivalent to babel-preset-latest, in that it enables es2015, es2016, and es2017 syntax support. Since [object rest/spread](https://github.com/tc39/proposal-object-rest-spread) is still a proposal, it is not available by default.

You can either add `@babel/plugin-proposal-object-rest-spread` to your project, or use the [`shippedProposals` option](https://github.com/babel/babel/tree/master/packages/babel-preset-env#shippedproposals) available in `@babel/preset-env` to enable object rest/spread and other proposals that browser vendors have committed to shipping.

**Comment by acusti** [comment]
@existentialism Thanks very much, adding `@babel/plugin-proposal-object-rest-spread` fixes it! I couldn’t find mention of that plugin in any of the docs and actually didn’t know about any of the `proposal-*` plugins or the `shippedProposals` option, so thanks for letting me know.

When first trying to research resolve this issue, I tried a lot of googling for the `This experimental syntax requires enabling the parser plugin: 'objectRestSpread'` part of the error message, then `babel 7 objectRestSpread parser plugin` and similar phrases, but without any success. Maybe it would be helpful to have a doc that maps parser errors, or parser plugin identifiers (like `objectRestSpread`), to the actual parser plugin name that needs to be used to enable that plugin (like `@babel/plugin-proposal-object-rest-spread`).

Thanks again for your help!

**Comment by existentialism** [comment]
@acusti great minds think alike, we've been planning on adding better error messages in babel 7 to alleviate some of the headaches when setting up tooling. That error message you got was the first part, and the second (your suggestion) will be handled by https://github.com/babel/babel/pull/6961.

Maybe one day it can even offer to fix up your config and install the plugin too 😆

**Comment by acusti** [comment]
@existentialism Oh boy, that would be sooooo nice (the auto-fixing). And great to hear that those docs are in the works.

Looking back at my original repo, I just realized that I had defined `targets` and still ran into this issue. Using one of the example `browsers` configs from the @babel/preset-env readme:

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      },
    }]
  ]
}
```

I still get the parser plugin error, which seems wrong. Looking at the [kangax compatibility tables](http://kangax.github.io/compat-table/esnext/), object spread properties are only supported in Safari Technology Preview, so versions 7-11 should require the transforms. Actually, I don’t think I fully understand the distinction between the targets enabling the appropriate `transform-*` plugins vs targets enabling the needed `proposal-*` plugins. Seems like the former should require the latter to also be available. Is that the case?

**Comment by existentialism** [comment]
Without the `shippedProposals` option, object rest/spread isn't considered at all.

**Comment by phil-lgr** [comment]
@existentialism thanks for your reply, in my case I had long traces coming from @babel\traverse\lib\index.js about SpreadProperty switching to https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-object-rest-spread fixed it 👍

**Comment by olstenlarck** [comment]
Damn logic.
Shouldn't it work if `targets` is Node 8 or Node 9? It is shipped there too.

**Comment by darkadept** [comment]
@olstenlarck How does your config look for excluding? I can't get mine to work. I'm using Node 9 and cannot get object rest spreads working with webpack v3.11 & babel 7 env preset.

**Comment by trevorlitsey** [comment]
Only way I could make this work was to add babel-preset-stage-2. Not sure why that did it but neither shippedProposals nor @babel/plugin-proposal-object-rest-spread worked for me.
