### ISSUE TITLE
Error: Options {"loose":true} when compiling from within npm package

### ISSUE THREAD

**Issue by aamorozov** [babel/babel#6974]
Choose one: is this a bug report or feature request?

Bug(unless i'm doing it wrong).

### Input Code

**exportFunc.js**
```js
export default function main() {
console.log('Function that is being exported')
}
```

**main.js**
```js
require('babel-register')();
const main = require('./exportFunc.js')
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    "add-module-exports",
    "transform-object-rest-spread",
    [
      "transform-runtime",
      {
        "regenerator": true
      }
    ]
  ],
  "presets": [["env", {"targets": {"node": "current"}}]]
}
```

### Expected Behavior

It should compile the module. 
### Current Behavior

Upon installing the package within the post-install script it throws an error: 
```
./node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to ./node_modules/babel-preset-env/lib/index.js which does 
not accept options. (While processing preset: "./node_modules/babel-preset-env/lib/index.js") 
(While processing preset: "./node_modules/babel-preset-env/lib/index.js")
```
### Context

I've tried all suggestions in this repo/stack related to `Error: Options {"loose":true}` but can't make it work.
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  "babel-register": "^6.26.0", "babel-preset-env": "^1.6.1",
| Babylon          |  Not using directly
| node             | v8.9.1
| npm              | 5.5.1
| Operating System | MacOS Sierra v. 10.12.6

**Comment by nicolo-ribaudo** [comment]
Can you provide your package.json and the post-install script?

**Comment by aamorozov** [comment]
@nicolo-ribaudo Script itself is internal to the org, so can only provide how i call it and babel related packages, but inside the script is the exact same structure i noted in the code example in the issue - requiring functions that are being exported with `export default` and on top of the file is require('babel-register')(): 
```
  "scripts": {
    "postinstall": "node setupConfig.js"
  },
```

babel packages
```
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-register": "^6.26.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.3.21",
    "babel-eslint": "^8.0.3",
    "babel-polyfill": "^6.3.14",
    "babel-runtime": "^6.26.0",
```

**Comment by nicolo-ribaudo** [comment]
Can you try to update babel-core to 6.26.x? Preset options where added in version 6.13.0.

If it doesn't solve the problem, can you check if `loose` is set somewhere in your

**Comment by aamorozov** [comment]
@nicolo-ribaudo
Just tried, getting the same error. `{"loose": true}` is not being set from anywhere in my code, double checked that.

**Comment by loganfsmyth** [comment]
I don't think we have enough to answer as-is, but to me this sounds like an issue with `babel-register` being used in a place where it is actually trying to run `babel-preset-env` on _itself_, which usually happens if people do `ignore: false`, but you don't appear to be doing that. e.g. `Babel's own `require("babel-preset-env")` triggers `babel-register`, which then tries to use `env` to compile itself. Now sure why it'd be happening with what you've shown so far.

**Comment by jojohappy** [comment]
I also meet this problem, the `babel-register` configuration is
```javascript
{
  only: [ './views', './src' ],
  presets: [ 'react', [ 'env', [Object] ] ]
}
```
In babel-core, the regular expression of only will be generated by `babel-core/util/regexify` as following below
```javascript
{ only: [ /(?:(?=.)views)/i, /(?:(?=.)src)/i ] }
```
I run the app in `/usr/src/app`, the `/usr/src/app/node_modules/babel-preset-env/lib/index.js` will be matched the expression and compile itself.

Is it a bug to generate the regular expression?

**Comment by npahucki** [comment]
I'm running into this as well when using react-static. It works fine if you run in the root directory, but running in the `npm postintstall` fails with ```Error: Options {"loose":true} passed to /xxx/test/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/xxx/test/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/xxx/test/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/xxx/test/node_modules/react-static/babel-preset.js")
    at /xxx/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
``` 
`babel-core` is 6.26.0

Has there been any progress on this?
@aamorozov did you ever find a solution?

**Comment by loganfsmyth** [comment]
@npahucki As mentioned earlier, generally it is an issue with `babel-register` or `babel-node`'s configuration. If you include that we can try to direct you, but the error on its own is not enough information.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since in every Babel 7 release options are supported.
