### ISSUE TITLE
[BUG] access to this in class properties in extended classes

### ISSUE THREAD

**Issue by syabro** [babel/babel#6977]
Now it's possible to use variables set in parent constructor calls using `this`

### Input Code
[REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC3QN4CgEQC5nQU2gXiWgDcwQBXbALmnQAsBLCAOhPNwF9lVpgB7AOwwAnMsHS8hAClYBKJNwR1GLUhXzFS3Tp2R9BvENiYheAc0kByWEwxYjrChYA00ftgDucS7AsybmHBU2GS5dcChoACEABTAhbH50BBQEPWFRcSlZeQRFBmYHXAJWLWQdUEgYSOhsAA8cfgATKtj4xJzoWxx1RELqJQLVbG0uNIMjE3MLSP87IMcXN09Iy0jfWcDCmSA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0)

```js
class A  {
  state = { value: this.value }

  constructor(val) {
    this.value = val
  }
}

console.log('A.state.value', new A('A').state.value)


class BParent  {
  constructor(val) {
    this.value = val
  }
}

class B extends BParent {
  state = {value: this.value}
}

console.log('B.state.value', new B('B').state.value)

```

produces

```
A.state.value undefined
B.state.value B
```

### Expected Behavior
It must generates an error `You can't use "this" in class properties definition`

### Current Behavior
Ignores value for unextended class and sets the value if it was set in constructor in parent class

### Possible Solution
Add compilation rule?

### Context
When https://github.com/tc39/proposal-class-fields will be accepted `this` will refer to `window` or other global namespace mostly.

**Comment by Kovensky** [comment]
Actually, the example code is "correct" and should not produce an error.

For `class A`, https://tc39.github.io/proposal-class-fields/#[[construct]] will do `OrdinaryCallBindThis` before initializing the instance fields, so the `this` will refer to the new instance. All initializers run before the constructor, so your initializer is just reading a non-existing `.value` key, and the constructor is just creating a new `this.value` property.

For `class B`, the implicit constructor will call `super`. A subclass' property initializer only runs during `super()` (right before it "returns"), so it will see the `this.value` as initialized by `BParent`.

**Comment by syabro** [comment]
@Kovensky  I think it's not about call ordering, it's about `this` binding

> so the `this` will refer to the new instance

I can't find it in the specification. Am I missing something?

**Comment by Kovensky** [comment]
@syabro that is done by Step 8.a of the `[[Construct]]` internal method. The initializers are only called on Step 8.b.

**Comment by syabro** [comment]
@Kovensky thank you, I've created an issue here
https://github.com/tc39/proposal-class-fields/issues/62

Will reopen it again if `babel`'s behavior will differ from the proposal

**Comment by Kovensky** [comment]
There actually is a divergence with how babel currently works, but it can be worked around by setting `spec: true` in the plugin options. It is the default in babel 7.

**Comment by syabro** [comment]
@Kovensky thanks
I will discuss the behavior and check it against `spec: true` :)
