### ISSUE TITLE
Allow to specify options for separate plugins in `preset-env`

### ISSUE THREAD

**Issue by th0r** [babel/babel#6978]
It's a feature request.

### Context

Sometimes you need to specify options for some plugins inside `preset-env` e.g. when you want to enable `loose` mode only for some of them.
The only way to do it right now is to include those plugins separately under the `plugins` section of babel config, but in this case they will be used even for the targets that don't actually need them.

Here is the concrete example:

I want to use `preset-env` in loose mode but I can't enable loose mode for `transform-spread` because in this case it doesn't transform code like this `[...someMap.value()]` properly.

So the only solution right now is to use config like that:

```json
{
  "presets": [
    ["@babel/preset-env", {"loose": true}]
  ],

  "plugins": [
    ["@babel/plugin-transform-spread", {"loose": false}]
  ]
}
```

But in this case spread operator will be transformed even if target browser supports this syntax natively.

### Possible Solution

Introduce an option for `preset-env` that will contain options for separate plugins:

```json
{
  "presets": [
    ["@babel/preset-env", {
      "loose": true,
      "pluginOptions": {
        "@babel/plugin-transform-spread": {"loose": false}
      }
    }]
  ]
}
```

They will override any options provided by `preset-env` by itself e.g. in the case above `loose: false` will override `loose: true` for `transform-spread` plugin.

### Your Environment

babel: 7.0.0-beta.32
preset-env: 7.0.0-beta.32

**Comment by th0r** [comment]
I can try to implement this feature, I just need confirmation that this proposal makes sense.

**Comment by loganfsmyth** [comment]
I've generally been against this in the past, but I'm also happy to continue the discussion. I'm kind of split on it. 

Requests for this, to me, usually imply that our current options have flaws and/or aren't granular enough. That is _definitely_ the case for `loose` because no one knows what they are actually opting into because it has no consistent goal.

To me, the preferred approach to that problem would be to make better options with clear names.

That said, you could certainly also make an argument that it is better to let users to whatever, and make better options to do what users want later. I worry that we'll end up hearing less from users when they want features because they will just do workarounds using this instead.

**Comment by th0r** [comment]
@loganfsmyth Well, if I understood you correctly, your main target is to make `preset-env` as simple and user-friendly as possible and ideally `loose` option should be smart enough to switch off loose mode for plugins automatically if codebase contains code that won't be transformed properly, right?

So from your point of view `pluginOptions` is a workaround and not the true solution?

**Comment by loganfsmyth** [comment]
> ideally loose option should be smart enough to switch off loose mode for plugins automatically if codebase contains code that won't be transformed properly

The issue for me is that there isn't a definition of "properly transformed". There's no way to turn if off loose if things won't transform properly because whatever loose happens to do by definition matches what it seems as "proper". The definition of `loose`, as far as it exists, is essentially "do some stuff that isn't spec compliant". The fact that you want to use it on some plugins and not others means that we should have better options with names that align with a particular compilation goal. I personally wouldn't recommend `loose` mode to anyone ever because of how poorly defined it is, and I see the fact that people use it as indication that we aren't properly aligning our options with user expectations.

> So from your point of view pluginOptions is a workaround and not the true solution?

I think for the case of `loose` it is almost certainly a workaround. I'd much rather we add more options that actually had well-defined behavior.

**Comment by th0r** [comment]
> I personally wouldn't recommend loose mode to anyone ever because of how poorly defined it is, and I see the fact that people use it as indication that we aren't properly aligning our options with user expectations.

I use loose mode because it results in more clean, readable and performant code. I have carefully read all the warnings about it and I'm perfectly fine with them.

> I'd much rather we add more options that actually had well-defined behavior.

But it will be just renaming of plugin options.

**Comment by loganfsmyth** [comment]
> I use loose mode because it results in more clean, readable and performant code.

I think I could be clearer with examples. I'm all for options that simplify the code, but I'm assuming in your case you actually want to use iterables, right? So I'd be way more motivated to have an option like `assumeArray` to make Babel's output assume all places that iterables come up are just arrays. That's what `loose` does, and what you're opting out of for `spread` right? Similarly a lot of people want to avoid `Object.defineProperty` so we could have an option to avoid that, which simplifies readability of classes and things.

**Comment by th0r** [comment]
That's exactly what I meant by "it will be just renaming of plugin options and their list will only grow when preset-env will support next ES versions".

Do you want `preset-env` to be some kind of black box that doesn't reveal its internals and plugins that are used under the hood? I mean what you propose is just renaming e.g. `loose` option for `transform-spread" into `assumeArray`.

So I have the following concerns here:
1) Are you sure that we'll be able to find nice names for all the existing and future plugin options? Do you really want to do this work?
2) Let's assume that there are people, that currently use manually created list of es2015 plugins with options and who want to move to `preset-env`. Renamed options will only introduce extra difficulties and confusion.

**Comment by th0r** [comment]
@loganfsmyth if I still couldn't convince you let's then try to find better names for options?

**Comment by ylemkimon** [comment]
Currently only `loose` option can be passed to the preset configuration, which is passed globally to the plugins and their behavior is different per plugin. I think we should be at least able to pass other options to plugins.

**Comment by eps1lon** [comment]
I think having at least a debug output for what plugins are switched into `loose` mode would already help. We'd like to use optional-chaining (and can in loose mode) but it requires looking through each plugin individually to get an overview over the potential impact.

I collected the plugins for the following targets:
```bash
ie 11
edge >= 14
firefox >= 52
chrome >= 49
safari >= 10
node 8.0
```

<details>
<summary>plugins grouped by `loose`, `spec` and no mode in `@babel/preset-env@7.9.0`</summary>

## loose

- [`proposal-nullish-coalescing-operator`](https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator#loose)
- [`proposal-optional-chaining`](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining#loose)
- [`transform-parameters`](https://babeljs.io/docs/en/babel-plugin-transform-parameters#loose)
- [`proposal-object-rest-spread`](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#loose)
- [`transform-template-literals`](https://babeljs.io/docs/en/babel-plugin-transform-template-literals#loose)
- [`transform-classes`](https://babeljs.io/docs/en/babel-plugin-transform-classes#loose)
- [`transform-computed-properties`](https://babeljs.io/docs/en/babel-plugin-transform-computed-properties#loose)
- [`transform-for-of`](https://babeljs.io/docs/en/babel-plugin-transform-for-of#loose)
- [`transform-spread`](https://babeljs.io/docs/en/babel-plugin-transform-spread#loose)
- [`transform-destructuring`](https://babeljs.io/docs/en/babel-plugin-transform-destructuring#loose)

## none

- [`proposal-json-strings`](https://babeljs.io/docs/en/babel-plugin-proposal-json-strings#options)
- [`proposal-optional-catch-binding`](https://babeljs.io/docs/en/babel-plugin-proposal-optional-catch-binding#options)
- [`proposal-async-generator-functions`](https://babeljs.io/docs/en/babel-plugin-proposal-async-generator-functions#options)
- [`transform-dotall-regex`](https://babeljs.io/docs/en/babel-plugin-transform-dotall-regex#options)
- [`proposal-unicode-property-regex`](https://babeljs.io/docs/en/babel-plugin-proposal-unicode-property-regex#options)
- [`transform-named-capturing-groups-regex`](https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex#options)
- [`transform-async-to-generator`](https://babeljs.io/docs/en/babel-plugin-transform-async-to-generator#options)
- [`transform-exponentiation-operator`](https://babeljs.io/docs/en/babel-plugin-transform-exponentiation-operator#options)
- [`transform-literals`](https://babeljs.io/docs/en/babel-plugin-transform-literals#options)
- [`transform-function-name`](https://babeljs.io/docs/en/babel-plugin-transform-function-name#options)
- [`transform-object-super`](https://babeljs.io/docs/en/babel-plugin-transform-object-super#options)
- [`transform-shorthand-properties`](https://babeljs.io/docs/en/babel-plugin-transform-shorthand-properties#options)
- [`transform-duplicate-keys`](https://babeljs.io/docs/en/babel-plugin-transform-duplicate-keys#options)
- [`transform-sticky-regex`](https://babeljs.io/docs/en/babel-plugin-transform-sticky-regex#options)
- [`transform-unicode-regex`](https://babeljs.io/docs/en/babel-plugin-transform-unicode-regex#options)
- [`transform-block-scoping`](https://babeljs.io/docs/en/babel-plugin-transform-block-scoping#options)
- [`transform-typeof-symbol`](https://babeljs.io/docs/en/babel-plugin-transform-typeof-symbol#options)
- [`transform-new-target`](https://babeljs.io/docs/en/babel-plugin-transform-new-target#options)
- [`transform-regenerator`](https://babeljs.io/docs/en/babel-plugin-transform-regenerator#options)
- [`syntax-dynamic-import`](https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import#options)

## spec

- [`transform-arrow-functions`](https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions#spec)

</details>

-- https://gist.github.com/eps1lon/af33d56c2124b1efc66bd32925b4cc64

**Comment by eps1lon** [comment]
> I think we should be at least able to pass other options to plugins.

A concrete example for this is `for-of`. Would be nice to tell babel to `assumeArray` though ideally it would check the type (jsdoc or TypeScript).

I could pass the code through typescript first which would prevent triggering the full iterator transpilation. But I don't know how/if source maps work if I have two transpilation steps.

**Comment by nicolo-ribaudo** [comment]
You can now use [assumptions](https://babeljs.io/docs/assumptions) to finely tweak behavior of the various transforms, regardless of where they are included in your config.
