### ISSUE TITLE
--ignore not work

### ISSUE THREAD

**Issue by cybermerlin** [babel/babel#6981]
Choose one: is this a bug report?

### Input Code

package.json
```json
{
"build.front": "set DEBUG= && cross-env BABEL_ENV=front babel src --out-dir dist/front --ignore \"scr\/back_overrides\""
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
	"env": {
		"front": {
			"presets": [
				[
					"es2015",
					{
						"modules": false
					}
				]
			],
			"plugins": [
				"transform-decorators-legacy",
				"transform-decorators",
				"transform-class-properties",
				"transform-exponentiation-operator",
				"syntax-trailing-function-commas",
				"syntax-async-functions",
				"transform-async-to-generator"
			]
		}
	}
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.23.0
| Babel-cli        |  6.26.0
| Babylon          | 
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | win10x64

**Comment by cybermerlin** [comment]
after compilation dist/front has back_overrides directory

**Comment by loganfsmyth** [comment]
Unfortunately `ignore` is quite unreliable in Babel 6.x. We've improved it in 7.x's beta a bunch.
