### ISSUE TITLE
TODO: Remove t.jSX* and t.tS* builders aliases

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#6989]
> EDIT: make this change on the final release.

#6967 makes the `jsx` and `ts` prefixes in node builders lowercase (e.g. `t.jsxExpression()` instead of `t.jSXExpression()`).

We can remove the old `t.jSX*` and `*.tS` builders. It is a breaking change, but
1) `t.tS*` aren't used yet by third party plugins because it has never been in a stable release
2) There aren't many plugins which build JSX nodes (actually, the only one I could find uses `t.JSXIdentifier`, so it would't be influenced by this change).

---

https://github.com/babel/babel/blob/a2aabbd33d373ff9ede75f9d23cdf52249b13165/packages/babel-types/scripts/generators/generateBuilders.js#L18-L23
https://github.com/babel/babel/blob/a2aabbd33d373ff9ede75f9d23cdf52249b13165/packages/babel-types/scripts/generators/generateBuilders.js#L34-L39

**Comment by existentialism** [comment]
Fixed in v8 branch via https://github.com/babel/babel/pull/11095
