### ISSUE TITLE
export * from './MyClass' returns undefined

### ISSUE THREAD

**Issue by pirsplus** [babel/babel#6995]
### Issue
```js
export * from './MyClass'
```
`export *` returns `undefined`

Note: `MyClass.js` is a normal ES6 Class with a constructor (that worked perfectly before i update it from a previous version).

###  Solution
```js
export {default} from './MyClass'
```
`export {default}` return `[Function: MyClass]`

### .babelrc
```js
{
  "presets": ["env"]
}
```

### package.json
```js
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  }
```

Have you a fix to do `export * from 'Class'` instead of `export {default} from 'Class'` ?

**Comment by loganfsmyth** [comment]
This is expected behavior. `export * from` only re-exports named exports.

**Comment by pirsplus** [comment]
Why only named ? Is `default` not a name ...?

**Comment by nicolo-ribaudo** [comment]
`default` is explicitely excluded. (https://tc39.github.io/ecma262/#sec-getexportednames - step 7.c.i)
Unfortunatly the only way of re-exporting the default export is using `{ default }`:
```js
export * from "mod";
export { default } from "mod";
```

If you want it to behave differently, you can use a custom plugin: http://astexplorer.net/#/gist/460a578ed51aef829935ff18ff39d8ec/9be8fbfd0191fb04dcff51d56bcc35053a72c501
