### ISSUE TITLE
assignment to readonly properties is not allowed in strict mode

### ISSUE THREAD

**Issue by goonwzz** [babel/babel#7000]
Choose one: is this a bug report or feature request?

### Input Code

谷歌没有现实错误，但是在IE edge 浏览器有这个错误出现。。定位不到是哪段代码。引起的，是不是BabelRC 少配置了什么？

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-decorators-legacy",
    [
      "import",
      {
        "libraryName": "antd",
        "style": false
      }
    ]
  ]
}

```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.1.2
| Babylon          | 
| node             | 7.3.0
| npm              | 3.10.10
| Operating System |

**Comment by rajzshkr** [comment]
Can you translate the description into english?

**Comment by goonwzz** [comment]
error show at  IE and edge but google is well

**Comment by nicolo-ribaudo** [comment]
Can you provide a small example of code which doesn't work before and after the compilation?

**Comment by lensbart** [comment]
Not sure if this is the same issue, but I ran into the following bug which is present in beta 34 and 35, but not beta 31 (I resolved the issue by reverting).

```
export default class Header extends Component {
  constructor(props) {
    super(props)
    this.references = []
    this.positions = []
  }
  componentDidMount() {
    const update = returnValueFromSomeFunction()
    this.positions = update.positions
    this.references = update.refs
  }
  componentDidUpdate() {
    const update = returnValueFromSomeFunction()
    this.positions = update.positions
    this.references = update.refs
  }
```

This gave a TypeError for the last line (`this.references = update.refs`): "Attempted to assign to readonly property". Note that this error only manifested itself in the componentDidUpdate method and didn't show when commenting out this last line -- i.e. neither `this.positions = update.positions` nor `componentDidMount()` gave the same error.

**Comment by nicolo-ribaudo** [comment]
@lensbart Can you share your babelrc and package.json?

**Comment by lensbart** [comment]
Sure! By the way, I forgot to mention that I updated & reverted all of the following (copied from console:) `yarn add @babel/cli@7.0.0-beta.31 @babel/preset-env@7.0.0-beta.31 @babel/preset-flow@7.0.0-beta.31 @babel/preset-react@7.0.0-beta.31 @babel/preset-stage-1@7.0.0-beta.31 @babel/core@7.0.0-beta.31`

**babelrc**
```
{
	"plugins": [
		"transform-decorators-legacy",
		[
			"react-intl",
			{ "messagesDir": "./build/messages/" }
		]
	],
	"presets": [
		"@babel/preset-env",
		"@babel/preset-react",
		"@babel/preset-stage-1",
		"@babel/preset-flow"
	],
}
```

**package.json**
```
// ...
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.31",
    "@babel/core": "7.0.0-beta.31",
    "@babel/preset-env": "7.0.0-beta.31",
    "@babel/preset-flow": "7.0.0-beta.31",
    "@babel/preset-react": "7.0.0-beta.31",
    "@babel/preset-stage-1": "7.0.0-beta.31",
    "apollo-codegen": "^0.18.2",
    "babel-eslint": "^8.0.1",
    "babel-jest": "^22.0.1",
    "babel-loader": "^8.0.0-beta.0",
    "babel-plugin-react-intl": "^2.3.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "compression-webpack-plugin": "^1.0.1",
    "css-loader": "^0.28.4",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "eslint": "^4.9.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-graphql": "^1.4.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-prettier": "^2.3.1",
    "eslint-plugin-react": "^7.4.0",
    "file-loader": "^1.1.5",
    "flow-bin": "^0.61.0",
    "flow-typed": "^2.2.3",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^22.0.1",
    "json-loader": "^0.5.7",
    "jsx-loader": "^0.13.2",
    "node-sass": "^4.5.3",
    "nodemon": "^1.12.1",
    "prettier": "^1.9.0",
    "react-styleguidist": "^6.0.31",
    "react-test-renderer": "^16.0.0",
    "regenerator-runtime": "^0.11.0",
    "sass-extract": "^2.0.0",
    "sass-extract-loader": "^1.0.0",
    "sass-loader": "^6.0.6",
    "style-ext-html-webpack-plugin": "^3.4.5",
    "style-loader": "^0.19.0",
    "uglifyjs-webpack-plugin": "^1.0.1"
  },
// ...
```

**Comment by nicolo-ribaudo** [comment]
I'm having truble reproducing the issue... Can you post the full stack trace of the error?

**Comment by lensbart** [comment]
<img width="1069" alt="screen shot 2017-12-19 at 22 35 54" src="https://user-images.githubusercontent.com/20876627/34179913-0a51517c-e50d-11e7-9aab-99f3109099af.png">

**Comment by nicolo-ribaudo** [comment]
Sorry, I really can't find anything wrong in the code that Babel generates :disappointed: 

Can you try to run that code in a modern browser without transpiling classes? If it works, this probably isn't an issue with Babel. Otherwise I need a repository which reproduces the issue (If you found the bug in a public repo you can just link it)
