### ISSUE TITLE
babel cannot issue

### ISSUE THREAD

**Issue by bhxabdou** [babel/babel#7004]
Choose one: is this a bug report or feature request?

### Input Code

```js
var your => (code) => here;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by nicolo-ribaudo** [comment]
@bhxabdou It looks like you submitted this by accident?
