### ISSUE TITLE
Destructuring rest parameters (2nd edition)

### ISSUE THREAD

**Issue by DarKDinDoN** [babel/babel#7011]
I'd like to use this syntax:

```js
const func = (...[foo, bar]) => {
    console.log(foo)
    console.log(bar)
}

func('foo', 'bar')
```

But I can't find the proper syntax plugin (actually, I don't want this to be transformed, I just want babel to not crash on this syntax).
Related to #5673 but still no clue

**Comment by nicolo-ribaudo** [comment]
Which version are you using? Iirc it should be parsed by default in Babel 7

**Comment by DarKDinDoN** [comment]
Ok, I'm using Babel 6.
I'll wait for the release. Thx !
