### ISSUE TITLE
babel-standalone/babel-preset-env-standalone contains previous version

### ISSUE THREAD

**Issue by yavorsky** [babel/babel#7016]
Bug report:

It's issue related rather to standalone packages. For bundles processed before version update, it takes the previous version.

Seems like when we are deploying a new version and making `bootstrap`, it bundles standalone version before `version`s in `package.json` for all packages were updated.
As a result, for https://unpkg.com/@babel/standalone@7.0.0-beta.33/babel.js we will receive instance with `Babel.version // beta.32`.
It affects REPL also: https://babeljs.io/repl/#?version=7.0.0-beta.33 will show beta.32 in the left bottom corner.
<img width="199" alt="screen shot 2017-12-12 at 12 09 49" src="https://user-images.githubusercontent.com/1521229/33878888-6436fb84-df35-11e7-82bd-2491d13edcbd.png">
👆
<img width="193" alt="screen shot 2017-12-12 at 12 09 45" src="https://user-images.githubusercontent.com/1521229/33878886-601df336-df35-11e7-9109-f0740855aa3b.png">

### Expected Behavior
It should show an actual version.

### Possible Solution
Check bundling process for new releases.

### Your Environment
All environments.

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.x
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by yavorsky** [comment]
Didn't see this before, but we have already similar issue: https://github.com/babel/babel/issues/6174

**Comment by existentialism** [comment]
@yavorsky let's merge with #6174 and add a note that `babel-preset-env-standalone` needs to get fixed as well

**Comment by yavorsky** [comment]
@existentialism Sure!

**Comment by Daniel15** [comment]
Yeah when babel-standalone was in its own repo, I avoided this issue by bumping the version number **before** building.

There's two possible ways to fix it:
1. Update the build process to bump the version number before building, like the old one did
2. Have a placeholder for version number, and add a post-version-number-bump step that injects the new version number.
