### ISSUE TITLE
@babel/plugin-syntax-class-properties-tranform not provided

### ISSUE THREAD

**Issue by Kielan** [babel/babel#7018]
I believe this package is missing, could be wrong though

**Comment by rajzshkr** [comment]
This one https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-class-properties ?

**Comment by Kielan** [comment]
@rajzshkr I have included that in my babelrc plugins but I am still getting the err "Missing class properties transform." on my class files in js

**Comment by nicolo-ribaudo** [comment]
That is for pasing only. You are looking for `@babel/plugin-proposal-class-properties` - https://www.npmjs.com/package/@babel/plugin-proposal-class-properties

**Comment by Kielan** [comment]
@nicolo-ribaudo Adding @babel/plugin-proposal-class-properties had no effect on the compilation error

**Comment by Kielan** [comment]
I don't why why this could possibly now work.
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
  ],
  "plugins": [
    "@babel/core",
    "@babel/register",
    "@babel/plugin-transform-runtime",
  ],
}
```
```
"plugins": [
    "@babel/core",
    "@babel/register",
    "@babel/plugin-transform-runtime",
  ],
```
I am using the newest versions in package.json in order to get a functioning recipe (a failure up until this point)

I worry my webpack dependency itself is reliant on babel-loader rather than @babel/core. The problem has to do with adding the plugin 'apply' Hooks in the Tapable module of my webpack process.

https://github.com/babel/babel-bridge

I am using, up until now adding plugins into my webpack config has caused a series of errors, on different version setups. I should be able to use the most up to date of these common plugins and not have an internal error ideally.

I had it working, generating styles, scss, and js up until using ExtractTextPlugin
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/681

now I have since broken the webpack process at 
```
Module build failed: Error: Cannot find module 'babel-core
```

**Comment by Kielan** [comment]
I have now upgraded to babel-loader@v8
```
Module build failed: Error: .inputSourceMap must be a boolean, object, or undefined
    at assertInputSourceMap (/dirspace/project/node_modules/@babel/core/lib/config/option-assertions.js:41:11)
```

**Comment by existentialism** [comment]
After a conversation in slack, closing this as it looks like this wound up being a webpack configuration issue.

**Comment by Kielan** [comment]
error had to do with another package's support

**Comment by uppal101** [comment]
@existentialism or @Kielan which package was this? Maybe a brief synopsis of the conversation could be helpful for other viewers as well?

**Comment by garrensweet** [comment]
I know I'm resurrecting a dead thread here -- but some information as @uppal101 stated, would be supremely useful. Can we get you to chime in here @Kielan and give some insight?
