### ISSUE TITLE
Missing license for plugin-proposal-unicode-property-regex

### ISSUE THREAD

**Issue by msurekci** [babel/babel#7021]
Hi, it appears that there is no license set for this package. Is this intentional? I've seen MIT being set for some of the packages.

Is it possible to add the MIT license to this package too?

**Comment by xtuc** [comment]
If I remember correctly this plugin is from by @mathiasbynens. What should be the licence for this one?

**Comment by mathiasbynens** [comment]
The one in this repository is licensed just like the rest of Babel.

The old stand-alone plugin [has its own license](https://github.com/mathiasbynens/babel-plugin-transform-unicode-property-regex/blob/master/LICENSE-MIT.txt).

**Comment by xtuc** [comment]
Ok, so the licence is MIT.

Do you want to contribute and make the PR @msurekci?
