### ISSUE TITLE
how to Support IE8

### ISSUE THREAD

**Issue by mailylqj** [babel/babel#7023]
I set  '@babel/preset-env' to
presets: [['@babel/preset-env', {targets: {browsers: ['last 2 versions', 'ie >= 7']}}]],

but in IE8 not work

**Comment by mailylqj** [comment]
i use webpack transform my project, in my webpack config file, i set like this
``` 
{
				test: /\.(es6|js)$/,				
				loader: 'babel-loader',
				exclude: /(node_modules|bower_components)/, // no bower_components $export is not a function
				query: {
					presets: [['@babel/preset-env', {targets: {browsers: ['ie >= 7']}}]],
					plugins: ['@babel/transform-runtime']
				}
			}
```
but i use this static js in my page, is not work.
show me error like this:
SCRIPT1002: Syntax error
![image](https://user-images.githubusercontent.com/10206627/33991325-30213cc6-e109-11e7-9484-6769412629a8.png)

**Comment by azz** [comment]
Try `@babel/env`

**Comment by mailylqj** [comment]
@azz the same error
this is my package.json
![image](https://user-images.githubusercontent.com/10206627/33991799-141c0180-e10b-11e7-96a8-4e0bd893a318.png)

**Comment by mailylqj** [comment]
sorry, it`s dev server. close it.
