### ISSUE TITLE
babel not working with parent folders

### ISSUE THREAD

**Issue by nimo23** [babel/babel#7024]
I use these versions:
```

"babel-core": "^6.26.0",
"babel-plugin-transform-react-constant-elements": "^6.23.0",
"babel-plugin-transform-react-jsx": "^6.24.1",
"babel-preset-env": "^1.6.1",
"babel-preset-react": "^6.24.1",
"gulp": "^3.9.1",
"gulp-babel": "^7.0.0",
```
with this gulp-task:

```
const gulp = require('gulp');
const babel = require("gulp-babel");

gulp.task("babel", function(){
// index.jsx is within the same directory as node_modules
    return gulp.src("index.jsx")
	    	.pipe(babel())
// the output is in a "parent folder" of the "actual folder"
// the "actual folder" has "package.json", "node_modules" and "gulpfile.js"
	    	.pipe(gulp.dest("../resources/script/build"));
});
```

The above solution works without problems. index.jsx is converted by babel and placed in "./resources/script/build".

However, when I change gulp.scr to "../resources/script/index.jsx" and move index.jsx to this folder:

```
gulp.task("babel", function(){
    return gulp.src("../resources/script/index.jsx")
	    	.pipe(babel())
	    	.pipe(gulp.dest("../resources/script/build"));
});
```

then I get this error:

Starting 'babel'...

```
events.js:136
      throw er; // Unhandled 'error' event
      ^
SyntaxError: usr/test/app/res/script/index.jsx: Unexpected token (18:2)
  16 | 		const {type} = this.props;
  17 | 		return (
```

Why?

(Using other gulp-plugins, like css-autoprefixer and getting and putting these files in parent folders works without problems, so I guess, it s a babel issue)

**Comment by mailylqj** [comment]
please show me full of you project directory.

**Comment by nimo23** [comment]
folder-structure **(parent folder a contains two child-folders b1, b2)**:
a->b1
a->b2

- "a" contains the subfolder b1 and the subfolder b2
- "b1" (the src-folder): contains package.json/babelrc/gulp-file, html/css/js-files
- "b2" (the dist-folder): contains all output generated by npm/gulp/babel

**Comment by nimo23** [comment]
was my fault: it works with presets "es".
