### ISSUE TITLE
clamd babel-source-5.8.35/lib/babel.js

### ISSUE THREAD

**Issue by kaliaev** [babel/babel#7025]
Hey Im not sure if its you. Can be my box. I found this after clamd run: **babel-source-5.8.35/lib/babel.js: Txt.Downloader.Generic-639 8289-0 FOUND** and **cache/babel-source-5.8.35.gem: Txt.Downloader.Generic-6398289-0 FOUND** 

Any idea?

**Comment by jakef** [comment]
Howdy. I also received the sme alert via clamav this morning. 

```
babel-source-5.8.35.gem: Txt.Downloader.Generic-6398289-0 FOUND
babel-source-5.8.35/lib/babel.js: Txt.Downloader.Generic-6398289-0 FOUND
```

**Comment by kaliaev** [comment]
Definitely them. Thanks for your response. 

TEAMPROS
My pool.sks-keyservers.net public RSA certificate fingerprint 86AF 973F FC57 140E 16EB 3093 582A 38E1 BBAF 7C09
CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by hzoo** [comment]
Uh I have no idea what that is? This repo is also for Babel 7, we aren't updating Babel v6 let alone babel 5 anymore?

Is `babel-source` some other project?

**Comment by existentialism** [comment]
https://rubygems.org/gems/babel-source

**Comment by hzoo** [comment]
Oh ok so https://github.com/babel/ruby-babel-transpiler, well that hasn't been updated in a year or so and in that repo not this one so closing.
