### ISSUE TITLE
reduce code generated of plugin-proposal-decorator break compilation...

### ISSUE THREAD

**Issue by simonjoom** [babel/babel#7027]
we need to reopen this;
https://github.com/babel/babel/issues/6965#event-1385806305

this update break the compilation for me with Babel v7.0.0-beta.35
i have got lot of message: Cannot read property 'node' of undefined

**Comment by hzoo** [comment]
I would kindly ask that you provide more information above 😄 , what code, whats the stack trace, can you provide a repo.

**Comment by modosc** [comment]
i see this as well, will try to come up with an example case.

**Comment by nicolo-ribaudo** [comment]
@modosc Is this the same as #7030?

**Comment by simonjoom** [comment]
yes i think it s the same, the code problem is from  "on right side of assignment " 
but if i use the code from beta.34 of plugin-proposal-decorator  i see no one problem
