### ISSUE TITLE
Methods should not have "prototype" property

### ISSUE THREAD

**Issue by TimothyGu** [babel/babel#7029]
bug report

### Input Code

```js
console.log(typeof ({ a() {} }).a.prototype);

console.log(typeof (new class { a() {} }).a.prototype);
```

[REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgziA2CmB00QHMAUAXAngB1iAZgASoDehAhqgJSEkC-hdV8582ATiOlzrFQNwAoQaEgwESNFlwFiYWAHdCwaOQgRaFarQZMWbTt2l9-QA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-beta.0)

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

es2015 preset enabled in the REPL

### Expected Behavior

The code should print "undefined" and "undefined", as it does in all modern JavaScript engines.

### Current Behavior

The code prints "object" and "object".

### Possible Solution

The only way I can think of is `delete` the prototype property after function creation, which can pretty awkward in object literals. Maybe a runtime function could be added that basically does `(func) => { delete func.prototype; return func; }`.

### Context

N/A

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.0 (REPL)
| Babylon          | 
| <del>node</del> Browser | Google Chrome 63.0.3239.84 (Official Build) beta (64-bit)

**Comment by zloirock** [comment]
It's impossible since we can't delete prototype of usual function:
![image](https://user-images.githubusercontent.com/2213682/55122003-b4ca9980-512f-11e9-855b-354cf9dda7c1.png)
Kinds of functions without prototypes are unavailable in old ES versions and can't be applicable in this case.
