### ISSUE TITLE
response.getHeaders is not a function after transpile from ES7 to ES6 using transform-runtime plugin

### ISSUE THREAD

**Issue by hekod777** [babel/babel#7033]
### Choose one: is this a bug report or feature request?

This is a bug. 

I was using babel-preset-es2015, babel-plugin-transform-runtime, babel-preset-stage-2, babel-runtime to transpile a javascript application From ES7 to ES6 last week, because the application is using async await function.

It worked out very well.

But starting 2 days ago, I am getting an error saying that `response.getHeaders is not a function` when I am running the transpiled code in Node 6 environment.

If I am running the transpiled code in Node 8, it doesn't have this problem and worked out well.

I'd like to know what might be the problem

### Input Code
below is the part of the codes that has the problem.

```js
        response.end = async function(content, ...args) {
          if (response.statusCode == 200) {
            accumulateContent(content);
            await this.cacheContent(key, response.getHeaders(), body);
          }
          return methods.end.apply(response, [content].concat(args));
        }.bind(this);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": ["es2015", "stage-2"],
  "plugins": [
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ]
  ]
}

```

### Expected Behavior
The transpiled code should be running in Node 6 Environment without error.

### Current Behavior
Node 6 Environment : `response.getHeaders is not a function` error
Node 8 Environment: no errors. working very well.

### Context
I am trying to downgrade this app from node 8 environment to node 6
https://github.com/GoogleChrome/rendertron

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  babel-runtime 6.26.0
| Babylon          | 
| node             | node 6.11.5
| npm              | npm 5
| Operating System | mac OS

**Comment by xtuc** [comment]
I was able to reproduce it in the [REPL](http://babeljs.io/repl#?babili=false&browsers=Android%204&build=&builtIns=false&code_lz=E4UwzgDg9gdmIDoQwCYAIC8aCGYCeMAxmgGYCuRALgJawAUhslylANGgp9sAOZgCUaAN4AoNGmok0dUJFjwEYStkpkwAYSgoQmLACYADAcGjx47IUJkAtmQA2KkJpjMXDJi34BuMWewB3bGpKNEoAC2owBEILMKcPNwBrEDx2WWg4RB4QSgAJEGxtYDA6fnYAIy08b18AX19QVWAYNGscsK0o5BQEbAgIOzwZcAz4dgBtRhcWAF1o2BjKOm4-fhrahHLqVDpwyJqgA&debug=true&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.0.0-alpha.20) and here is the issue:

```diff
"use strict";

response.end = async function (content) {
  if (response.statusCode == 200) {
    accumulateContent(content);
    await this.cacheContent(key, response.getHeaders(), body);
  }

  for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
    args[_key - 1] = arguments[_key];
  }

  return methods.end.apply(response, [content].concat(args));
+ }.bind(void 0);
- }.bind(this);
```

One of our transformation causes that.

**Comment by xtuc** [comment]
Could you please send the corresponding generator code?

**Comment by nicolo-ribaudo** [comment]
The `response.getHeaders` function has been added in node v7.7.0 (https://nodejs.org/api/http.html#http_response_getheaders, https://github.com/nodejs/node/pull/11562). 

Babel only transpiles syntax, so you will either have to polyfill that function or not use it.

**Comment by xtuc** [comment]
Thanks @nicolo-ribaudo  :+1:
