### ISSUE TITLE
useBuiltIns not import specified polyfills

### ISSUE THREAD

**Issue by kakuyogy** [babel/babel#7036]
hi, now i wrote some code snippet to test babel-preset-env, i try useBuiltIns and test `Promise` and `Generator`, i hope runtime import like `import "babel-polyfill/lib/core-js/modules/es6.promise";`, when babel transform my code with `Promise`, but apparently not.

raw code: 
```js
const promise = new Promise((resolve) => {
  resolve('hi promise!');
});

promise.then((word) => {
  console.log(word);
});
```

babel transform options
```js
module.exports = {
  babelrc: false,
  presets: [
    ['env', {
      "useBuiltIns": "usage",
      "module": false,
    }],
  ],
  plugins: [],
};
```

transform script
```js
vfs.src('./src/**/*.js')
    .pipe(through.obj(function (f, enc, cb) {
      f.contents = new Buffer(babel.transform(f.contents, babelConfig).code);
      cb(null, f);
    }))
    .pipe(vfs.dest('./lib/'))
```

at last the transformed code is
```js
'use strict';

var promise = new Promise(function (resolve) {
  resolve('hi promise!');
});

promise.then(function (word) {
  console.log(word);
});
```

thanks for your help.

**Comment by agalatan** [comment]
In .babelrc, Shouldn't it be **"modules": false** ? 
https://babeljs.io/docs/plugins/preset-env/

**Comment by xtuc** [comment]
@agalatan is right but this issue doesn't seem to be related to modules.
