### ISSUE TITLE
babel 7 does not work as expected with nyc latest

### ISSUE THREAD

**Issue by palaniichukdmytro** [babel/babel#7048]
![screenshot_7](https://user-images.githubusercontent.com/14881178/34042243-582b6fe8-e1a4-11e7-97a0-0589d6a23336.png)

## Expected Behavior
Expected to cover all test with babel-preset-env.
## Observed Behavior
I migrated to babel 7 beta, where I use babel-preset-env, after new configuration, looks like nyc not cover arrow function, or env for testing not working as expected. Looks like nyc starts to test before babel transpiler. is it possible. 
node 9.3.0
## Bonus Points! Code (or Repository) that Reproduces Issue
_.babelrc.js_
```
const config = {
    'presets': [
        ['@babel/preset-env', {
            'targets': {
                'browsers': ['last 2 versions', 'ie >= 10']
            },
            'modules': false,
        }],
        '@babel/react',
        '@babel/stage-1'
    ],
    'plugins': ['react-hot-loader/babel']
}
```
_package.json_
```
  "nyc": {
    "exclude": [
      "config.js",
      "test/**/*.js"
    ],
    "require": [
      "@babel/register"
    ],
    "sourceMap": false,
    "instrument": false
  },
  "scripts": {
    "test": "watch \"cross-env NODE_ENV=test mocha -b --reporter dot\" src test",
    "cover": "cross-env NODE_ENV=test nyc --reporter=cobertura --reporter=html --reporter=text-summary node_modules/mocha/bin/_mocha --reporter mocha-junit-reporter --reporter-options mochaFile=../Televic.Mirfus/TestOutput/JUnitResults/ui-unit-tests.xml",
  },
  "dependencies": {
    "@babel/core": "^7.0.0-beta.34",
    "@babel/polyfill": "^7.0.0-beta.34",
    "@babel/preset-env": "^7.0.0-beta.34",
    "@babel/preset-react": "^7.0.0-beta.34",
    "@babel/preset-stage-1": "^7.0.0-beta.34",
    "@televic/react-components": "^0.0.75",
    "babel-loader": "8.0.0-beta.0",
....},
"devDependencies": {
    "@babel/cli": "^7.0.0-beta.34",
    "@babel/register": "^7.0.0-beta.34",
    "babel-eslint": "^8.0.3",
    "babel-plugin-istanbul": "^4.1.5",
    "babel-register": "^7.0.0-beta.3",
 "nyc": "^11.3.0",
}
```

```
const nodeEnv = process.env.NODE_ENV || 'development'
if (nodeEnv === 'test')
    config.plugins.push('istanbul')
    delete config.presets[0][1].modules
module.exports = config
```

In case I run with configuration:
```
 'targets': {
                'browsers': ['last 2 versions', 'ie >= 10']
            }, 
```
Looks like it does not cover only arrow function, on rest of the code cover
![screenshot_7](https://user-images.githubusercontent.com/14881178/34042254-5ecc4f20-e1a4-11e7-9e31-4e7311357faf.png)
![screenshot_6](https://user-images.githubusercontent.com/14881178/34042255-5ee776c4-e1a4-11e7-870f-09d706e2ae97.png)

I suppose that is something wrong with babel-plugin-istanbul

**Comment by hzoo** [comment]
If it is an issue with that plugin I would make the issue there, not in the babel repo. It hasn't been updated to test against v7 at least so it's possible there is an issue https://github.com/istanbuljs/babel-plugin-istanbul but that is expected if you are using non scoped babel plugins that are 3rd party that haven't updated yet
