### ISSUE TITLE
Documentation on how to use @babel ?

### ISSUE THREAD

**Issue by hekod777** [babel/babel#7051]
I am trying to figure out how to use @babel/preset-env and @babel/polyfill to add polyfill for an app runs in Node 8. so that after transpiling, it can be run in Node 6.

But the official babel documentation seems a bit outdate on this. Is there any @babel documentation there that I can follow?

**Comment by hekod777** [comment]
ah...

I was getting an error of `Cannot read property 'loose' of undefined` when trying to use `babel-preset-env`. And the answer was to use babel v7.

I will give it another try.

Thank you for clarifying!

**Comment by loganfsmyth** [comment]
Perhaps you were using `@babel/preset-env`? `babel-preset-env` is for Babel 6, `@babel/preset-env` is Babel 7 and would get that error if used on Babel 6.
