### ISSUE TITLE
response.getHeaders babel polyfill

### ISSUE THREAD

**Issue by hekod777** [babel/babel#7052]
I am trying to use babel to transpile an app from running in Node 8 to Node 6.

but getting this error:

```
response.getHeaders is not a function
```

the reason is that response.getHeaders is a function introduced in node 7.7.0. I need a polyfill for this getHeaders function.

Then I looked into `babel-preset-node7`

And it redirected me to `babel-preset-env` which is saying that `if you're targeting Node.js instead of the browser, you can configure @babel/preset-env to only include the polyfills and transforms necessary for a particular version:`

So I used the following code in the .babelrc file

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "node": "6.12.0"
      }
    }]
  ]
}

```

After babel transpiling, I am still getting `response.getHeaders is not a function` error. Any idea how to get this `getHeaders()` polyfilled?

**Comment by nicolo-ribaudo** [comment]
Babel only polyfills JavaScript features defined in the ECMAScript specifications (available both in the browser and in node and in any other JavaScript engine).
For api specific of an enveironement (like node modules, or DOM) you will need additional polyfills not provided by Babel.

**Comment by hekod777** [comment]
got it. wrote my own polyfill for the function. 

Thank you very much!

**Comment by nicolo-ribaudo** [comment]
Good :smile:
