### ISSUE TITLE
to-fast-properties use es6 cause lower version android throw error

### ISSUE THREAD

**Issue by paranoidjk** [babel/babel#7054]
see https://unpkg.com/to-fast-properties@2.0.0/index.js

This bug is introduced in https://github.com/babel/babel/pull/5997 to-fast-properties@1 is fine

**Comment by paranoidjk** [comment]
I will open a PR to fix `to-fast-properties` later

**Comment by loganfsmyth** [comment]
I'm not sure I understand the issue. Are you actually running Babel itself on the Android device?

What is the error you are getting? You haven't given enough information for us to diagnose the issue.

**Comment by paranoidjk** [comment]
This issue is to say that `to-fast-property` is somehow being build to users dist bundle, but it use es6 const and let.

and since it's a dep of babel, users's project won't set any compile for it.

We temporary fixed it by compile it during build. https://github.com/ant-design/ant-design-mobile/commit/c14bc44ff7ee918c077e0a53eda030580822904a

**Comment by loganfsmyth** [comment]
Babel 6 uses `to-fast-properties@1` and is fine.

Babel 7 only supports Node >= 6.9.x so many ES6 features like this are expected. It's only `@babel/standalone` that we try to support on ES5 environments, and even that isn't quite working properly yet (#7607).
