### ISSUE TITLE
babel-preset-env doesn't support Number.parseInt, Number.parseFloat

### ISSUE THREAD

**Issue by ajhyndman** [babel/babel#7055]
Choose one: is this a bug report or feature request?

Bug report.

In ES2015, the global functions `parseInt` and `parseFloat` were added to the Number global in an attempt to modularize some of the global features JS provided.

To date, IE11 doesn't support the usage `Number.parseInt`.  `babel-polyfill` does polyfill this feature, but using `babel-preset-env` appears to never include this particular feature.

### Input Code

```js
// This will fail in IE11
Number.parseInt("10");
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "plugins": ["babel-plugin-ramda", "babel-plugin-relay", "babel-plugin-idx"],
  "presets": [
    [
      "babel-preset-env",
      {
        "modules": false,
        "useBuiltIns": "entry",
        "exclude": ["babel-plugin-transform-regenerator"]
      }
    ],
    "babel-preset-react",
    "babel-preset-stage-2"
  ],

  "env": {
    "test": {
      "plugins": ["babel-plugin-transform-es2015-modules-commonjs"]
    }
  }
}
```

```bash
## .browserslistrc

# This list is consumed by babel-preset-env to determine which
# polyfills and transforms to include.

> 1% in my stats

# App versions
Explorer 11
iOS 9

# We claim to support these in our technical requirements docs
last 2 Chrome versions
last 2 ChromeAndroid versions
last 2 iOS versions
last 2 Safari versions
last 2 Firefox versions
last 2 Edge versions

```

### Expected Behavior

`import 'babel-polyfill';` should be transpiled and include import statements requiring the `core-js` shims for `Number.parseFloat` and `Number.parseInt`.

https://github.com/zloirock/core-js/blob/master/es6/number.js#L11-L12

### Current Behavior

`import 'babel-polyfill';` is transpiled but **does not** include import statements requiring the `core-js` shims for `Number.parseFloat` and `Number.parseInt`.

### Possible Solution

I looked into the code to see that there seems to be a list of supported vs released features.  I think it's probably possible to update these lists to include support for these modularized globals.

### Context

We introduced a bug in production code, by using `Number.parseInt` and assuming that any browsers that didn't support this would be managed by `babel-preset-env`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-preset-env | 1.6.0
| Babel            |  6.26.0
| node             | v8.3.0
| npm              | v5.3.0
| Operating System | MacOS High Sierra

**Comment by existentialism** [comment]
@ajhyndman thanks for the issue! this is already fixed (see https://github.com/babel/babel-preset-env/pull/391). Unfortunately, this is currently only available in the 7.x betas.

**Comment by ajhyndman** [comment]
Ooh, great news!  Thanks!

**Comment by kleinph** [comment]
I am experiencing this issue, but I use @babel beta.40.

My _package.json_:
```json
{
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Firefox versions",
    "last 2 Edge versions",
    "last 2 ChromeAndroid versions",
    "last 2 FirefoxAndroid versions",
    "last 2 iOS versions",
    "IE 11"
  ],
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "babel-loader": "^8.0.0-beta.0",
    ...
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0-beta.40",
    ...
  }
}
````
My _.babelrc_ file:
````json
{
    "presets": [
        ["@babel/preset-env", {
            "useBuiltIns": "usage",
            "debug": true,
            "modules": false
        }]
    ],
    "plugins": ["angularjs-annotate"]
}
````

**Comment by kleinph** [comment]
I am experiencing this issue, but I use @babel beta.40.

My _package.json_:
```json
{
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Firefox versions",
    "last 2 Edge versions",
    "last 2 ChromeAndroid versions",
    "last 2 FirefoxAndroid versions",
    "last 2 iOS versions",
    "IE 11"
  ],
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "babel-loader": "^8.0.0-beta.0",
    ...
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0-beta.40",
    ...
  }
}
````
My _.babelrc_ file:
````json
{
    "presets": [
        ["@babel/preset-env", {
            "useBuiltIns": "usage",
            "debug": true,
            "modules": false
        }]
    ],
    "plugins": ["angularjs-annotate"]
}
````

**Comment by existentialism** [comment]
@kleinph looks like we're missing mappings for this in `usage` mode, just pushed https://github.com/babel/babel/pull/7421 to fix. thanks for the report!
