### ISSUE TITLE
Babylon plugins

### ISSUE THREAD

**Issue by Archcry** [babel/babel#7056]
We are using babylon to get the abstract syntax tree from javascript code in Stryker. What we basically do in Stryker is use the AST to generate mutants in the users source-code. Some users use proposal features in JavaScript that do not work out of the box in Babylon, we'll have to add them to the options object as plugins.

I have two questions about this:
1. Are there any disadvantages to including every single plugin regardless of what the user uses?
2. If yes, if there some kind of wildcard that can do this automatically for each plugin??

**Comment by nicolo-ribaudo** [comment]
> Are there any disadvantages to including every single plugin regardless of what the user uses?

Users might start depending on features which they don't now are just proposals (thus very unstable). If the proposal changes, their code might be broken without them knowing that it could happen.

> If yes, if there some kind of wildcard that can do this automatically for each plugin??

There was (`{ plugins: ["*"] }`), but it was removed because
1. Some plugins are incompatible (for example, `decorators` and `decorators2`)
2. Whenever a new plugin was addedd, enabling it by default would be a possible breaking change.

**Comment by Archcry** [comment]
> Users might start depending on features which they don't now are just proposals (thus very unstable). If the proposal changes, their code might be broken without them knowing that it could happen.
That's a fair point, in case of babel this is a valid argument. I think enabling every plugin by default is not going to harm Stryker though but we will have to discus with our team how we want to keep babylon up-to-date in our project. To bad the wildcard is no longer available.

**Comment by loganfsmyth** [comment]
We've added a `babel.parse` function that takes Babel's normal options, so you could consider using that and as long as your users have their Babel config in the places Babel knows to look, it will pick up their Babylon plugins from the Babel plugins.

**Comment by Archcry** [comment]
That's awesome, I think that helps us out a lot because we also rely on the babelrc file within Stryker. Thanks a lot :D

**Comment by loganfsmyth** [comment]
Oh good to know. Assuming you're fine forcing your users to use Babel 7, you'll also be interested in keeping an eye on https://github.com/babel/babel/pull/7472 since we're adding more ways to configure things that you really won't want to implement yourself.
