### ISSUE TITLE
Return FunctionDeclaration in Do

### ISSUE THREAD

**Issue by xtuc** [babel/babel#7057]
Choose one: is this a bug report or feature request?

### Input Code

```js
const val = do {
  function t() {
  }
}
```

### Expected Behavior

val should be a function. I couldn't find a reference to the specification.

### Current Behavior

val is undefined.

### Possible Solution

In speudo code, something like:

```diff
const val = do {
+ return function t() {
-  function t() {
  }
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System | 

In stage-0, here's the example in the [REPL](http://babeljs.io/repl#?babili=false&browsers=Android%204&build=&builtIns=false&code_lz=MYewdgzgLgBAbgQwDYwLwwCYhgbwFAwwBmArmMFAJbgxQAUAlLgTAL56tA&debug=true&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Cstage-0%2Cstage-2&prettier=false&targets=&version=7.0.0-alpha.19).

**Comment by nicolo-ribaudo** [comment]
I don't think it should. When usin eval (which has the same semantics of `do {}`, you get undefined:

```js
> eval("if (true) 2; else 3");
2

> eval("fuction fn() {}")
undefined
```

**Comment by nicolo-ribaudo** [comment]
Function declarations' return value is `empty` (which means "keep the previous copletion value"), because they are hoisted:

```js
> eval("2; function fn() {}")
2
```

**Comment by xtuc** [comment]
Indeed, that make sense. I couldn't find the spec and didn't know it has the same semantics than `eval`. The difference between completion value and return value is not _super super_ clear to me.

**Comment by nicolo-ribaudo** [comment]
I just found https://github.com/tc39/proposal-do-expressions/issues/13.

**Comment by rajzshkr** [comment]
yeah, in do expression last evaluated statement should be returned.

**Comment by nicolo-ribaudo** [comment]
No, they should return the value of the block, which is its completion value. If you look at the es2017 spec, for every statement is defined it's completion value.

**Comment by xtuc** [comment]
Sorry I should have looked at the issue tracker first! Closing this since there's nothing to do in Babel for now.
