### ISSUE TITLE
[TypeScript]: Some syntax fails to compile when using an abstract class

### ISSUE THREAD

**Issue by mastilver** [babel/babel#7060]
:wave: Hi

Choose one: is this a bug report or feature request? 

bug

When using an abstract class it along side with another syntax (like export or annotation) the compilation fails

### Input Code

[Export example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29UCMDOMUqAxvCZqvvnACrCFwDeAvkA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.0.0-beta.32):  
Fails:
```
export default abstract class Test {}
```
Works:
```
abstract class Test {}
export default Test
```

[Annotation example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=AIQwdmD2AuCmAmAoEAjAztATiAxtABDgDYhpr4AqsG-A3ogL6KIBmArmHgJaRj7hQ48ABTQQmAOaxoASjqJ8-MZOkA6AA6YYMAJ7rYqrmgCCEGAnwBeJZjawA3I2Y5eNAtbCwA7pWrRhMs6ukEQGRJASooYmZkIyQA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=stage-1%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.0.0-beta.32):  
Fails:
```
@annoted
abstract class Test {
}
```

### Expected Behavior

the `abstract` keyword should just be ignored at all time

### Current Behavior

The `abstract` is not recognised by babel and the compilation fails

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.35
| node             | v8.3.0
| npm              | 5.6.0
| Operating System | Linux

**Comment by nicolo-ribaudo** [comment]
@andy-ms 
https://github.com/babel/babel/blob/5f8a1a2613eccc81a2b06e5758b003ce830f0171/packages/babylon/test/fixtures/typescript/class/abstract/actual.js#L5
Is that comment wrong? It works in the playground (https://www.typescriptlang.org/play/index.html#src=export%20default%20abstract%20class%20%7B%20%7D)

**Comment by andy-ms** [comment]
I'm sure it was invalid at some point, but that might have changed.
If Microsoft/TypeScript#18628 goes in we should just allow all of these to be default exports.

**Comment by Bnaya** [comment]
I have similar issue.
It has something to do with babel transforming decorators and the abstract keyword, and 
`@babel/plugin-proposal-class-properties`
It seems that babel is making a pass before the abstract entities are striped from the  code.

**Comment by danez** [comment]
I cannot reproduce the examples in the original report anymore with babel 7.4.4. Seems they were fixed
