### ISSUE TITLE
Test fixtures: rename actual/expected to input/output

### ISSUE THREAD

**Issue by hzoo** [babel/babel#7063]
Ref https://github.com/babel/babel/pull/7059#issuecomment-352766948

`actual.js` and `expected.js` isn't as intuitive as `input.js` and `output.js`. If someone wants to change this, that would be great.

Going to have to change the references (more than just what I linked) in at least these 2 packages:

https://github.com/babel/babel/blob/68476b6dddfdfc0941142cc45687c5b33c0cfe37/packages/babel-helper-fixtures/src/index.js#L87-L88

https://github.com/babel/babel/blob/68476b6dddfdfc0941142cc45687c5b33c0cfe37/packages/babel-helper-transform-fixture-test-runner/src/index.js#L134

Then all the tests need to be renamed. So this is a lot of work but relatively simple.

---

We might want to consider making https://github.com/babel-utils/babel-plugin-tester the official package or something, or merging that with our current setup eventually. Then we can move toward recommendation + standardization of quality of plugins via tests + use it as a way to upgrade plugins better. I should probably make a separate issue for this @kentcdodds

**Comment by kentcdodds** [comment]
I think that having a recommended/standard tool would be good for the ecosystem. It makes sense to me for `babel-plugin-tester` to be this tool.

**Comment by mathiasbynens** [comment]
Is the comment link in OP pointing to the right comment? I was expecting it to point to https://github.com/babel/babel/pull/7059#issuecomment-352764488

**Comment by hzoo** [comment]
Yeah I suggested this earlier because we can use that as a way to vet "quality" plugins and also enforce certain standards. For the project we need to make sure we can transition ourselves to use `babel-plugin-tester` then or to merge functionality into it that we need

**Comment by Anderson-Vasques** [comment]
@hzoo I would like to help. Is that okay? (Maybe it's a good first issue, too)
I guess I need to update README and CONTRIBUTING too?

**Comment by nicolo-ribaudo** [comment]
> I guess I need to update README and CONTRIBUTING too?

Yes! If you need any help, feel free to reach me on Slack (https://slack.babeljs.io/)

**Comment by Anderson-Vasques** [comment]
Nice. I will begin it tomorow

**Comment by Anderson-Vasques** [comment]
@nicolo-ribaudo @hzoo I was wondering from wich branch this change should be done. I guess I should checkout from master since the [ref](https://github.com/babel/babel/pull/7059#issuecomment-352766948) was merged to master?

**Comment by nicolo-ribaudo** [comment]
Yes, it should be master. I suggest not editing directly master in your fork, but creating a new branch based on master. Otherwise you can't work on anything else until your PR gets merged :slightly_smiling_face:
