### ISSUE TITLE
Improve error message for `typescript` parsing of `import =`

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7067]
See discussion in https://github.com/babel/babel/issues/7062#issuecomment-352836023

The current error message of 

> `import =` is not supported.

is not enough information for users to know what their next step should be. Ideally we'd make that more descriptive.

**Comment by gs-akhan** [comment]
Hi, 
Should I add a message like this ?

"import = is not supported. please consider changing your Typescript code to have ```import <specifier> from "resource" instead of ```import <specifier>  = require("resource");
refer link : https://www.typescriptlang.org/docs/handbook/modules.html#native-ecmascript-2015-modules-simplemodulejs"

**Comment by gs-akhan** [comment]
Any thoughts? I can send a PR if that works .. :)
Thanks

**Comment by loganfsmyth** [comment]
Maybe we can say

> "import =" is not supported in Babel's Typescript parser because there is no valid ES6 implementation for it. Please consider using `import <moduleName> from "<moduleName>";` alongside Typescript's `--allowSyntheticDefaultImports` option.

?

**Comment by gs-akhan** [comment]
Sounds good. With a link to the TSDocs ?

**Comment by loganfsmyth** [comment]
I don't think there are any good doc pages explaining `--allowSyntheticDefaultImports` other than http://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by gs-akhan** [comment]
Hmm yes. They can take user to some other level of confusion.
Should I send a PR ?

**Comment by toubou91** [comment]
Shouldn't we close this one?

**Comment by nicolo-ribaudo** [comment]
Yup
