### ISSUE TITLE
Validation error when using JSXSpreadChild

### ISSUE THREAD

**Issue by simonbuchan** [babel/babel#7069]
Choose one: is this a bug report or feature request?

Seems like a bug, since it's throwing validation errors from internal code on valid(ish) input, but given #3575 my _preferred_ behavior would probably be a feature request.

### Input Code
```js
// test.js
import React from "react";
import ReactDOM from "react-dom";

const content = ['Hello ', <b>cruel</b>, ' world'];
const target = <div>{...content}</div>;
ReactDOM.render(target, document.body);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// .babelrc.js
module.exports = {
  presets: ["@babel/react"]
}
```

```json
// package.json
{
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.35",
    "@babel/cli": "7.0.0-beta.35",
    "@babel/preset-react": "7.0.0-beta.35",
    "@types/react": "^16.0.31",
    "@types/react-dom": "^16.0.3"
  }
}
```

```
$ babel test.js
```

### Expected Behavior

I'd prefer output something like:

```js
const content = ['Hello ', React.createElement('b', null, 'cruel'), ' world'];
const target = React.createElement('div', null, ...content);
ReactDOM.render(target, document.body);
```

but `tsc --jsx react` emits without the `...`, i.e. `React.createElement('div', null, content)`.

More likely, given the discussion in #3575, simply giving a user-facing error message would be preferred? Something like `transform-react-jsx does not support '{...children}', use '{children}'`?

### Current Behavior

```
C:\code\personal\babel-tsx-parsing>yarn babel src\index.js
yarn run v1.3.2
$ C:\code\personal\babel-tsx-parsing\node_modules\.bin\babel src\index.js
TypeError: Property arguments[2] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName"] but instead got "JSXSpreadChild"
    at validate (C:\code\personal\babel-tsx-parsing\node_modules\@babel\types\lib\definitions\utils.js:88:13)
    at validator (C:\code\personal\babel-tsx-parsing\node_modules\@babel\types\lib\definitions\utils.js:47:7)
    at Object.validate (C:\code\personal\babel-tsx-parsing\node_modules\@babel\types\lib\definitions\utils.js:143:10)
    at validate (C:\code\personal\babel-tsx-parsing\node_modules\@babel\types\lib\validators\validate.js:15:9)
    at builder (C:\code\personal\babel-tsx-parsing\node_modules\@babel\types\lib\builders\builder.js:40:27)
    at Object.CallExpression (C:\code\personal\babel-tsx-parsing\node_modules\@babel\types\lib\builders\generated\index.js:276:27)
    at buildElementCall (C:\code\personal\babel-tsx-parsing\node_modules\@babel\helper-builder-react-jsx\lib\index.js:131:28)
    at PluginPass.exit (C:\code\personal\babel-tsx-parsing\node_modules\@babel\helper-builder-react-jsx\lib\index.js:25:22)
    at newFn (C:\code\personal\babel-tsx-parsing\node_modules\@babel\traverse\lib\visitors.js:223:21)
    at NodePath._call (C:\code\personal\babel-tsx-parsing\node_modules\@babel\traverse\lib\path\context.js:64:19)
```

### Context

React seems to distinguish between dynamic array contents (e.g. `{arrayProp.map(toChild)}`) and direct children only in that the latter do not warn on `key`, so the simple workaround is remove the `...` and add keys, or to convert rendering a component.

I ran into this while converting some `document.createElement()` calls that walk a JSON description, so I was trying to avoid changing structure too much, and I don't have meaningful keys in the source yet.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32 ... .35
| node             | v6.11.4
| npm              | yarn 1.3.2
| Operating System | Windows 10

**Comment by loganfsmyth** [comment]
Good find! This should be a relatively self-contained fix. We need to handle `JSXSpreadElement` in https://github.com/babel/babel/blob/4f534965465add7f653a04e96c0b30de27552508/packages/babel-types/src/builders/react/buildChildren.js#L9 so that it gets converted into a normal spread AST node instead of a JSX one.

**Comment by mannanali413** [comment]
@loganfsmyth I can work on this issue. Thanks

**Comment by existentialism** [comment]
@mannanali413 it's yours! feel free to join us on slack!

**Comment by simonbuchan** [comment]
@sebmarkbage looks like you picked the original design here, do you have any feedback?

**Comment by sebmarkbage** [comment]
For React, this is an intentional decision. We explicitly don't want people to spread things into the rest arguments because that is our heuristic to indicate that these children are static.

The way to define this in React is:

```js
<div>{content}</div>
```

In this case we will notice that an array is passed and issue a warning if not all children have explicit keys defined.

In React it is incorrect to pass children like this:

```js
var content = data.items.map(item => <Item />);
```

This is because the items can change order over time and therefore need a `key` prop specified.

However, if you do it like this then it probably won't change over time so can get away with not adding a key:

```js
<div><Item /><Item /></div>
```

The spread in this case would only work to foil the heuristic, and if that became a common practice we'd have to come up with some other way of informing you of the need for keys.

**Comment by simonbuchan** [comment]
> We explicitly don't want people to spread things into the rest arguments because that is our heuristic to indicate that these children are static.

This is in fact was why I was using child spread: to indicate that I know the children won't change, even though they are generated. React 16 fragments handle the case of simplifying returning multiple elements without keying them, but not the generative case. My context is generating SVG elements, where I know (to slightly simplify) the stuff in `<defs>` won't change, but the displayed elements will be (and thus will be keyed). Here the only thing to do for keys is take the index of the source array, which is no better than just not providing them - but this isn't a request for React to document and support that usage :)

At minimum, the user should get a meaningful error: I don't think babel transforms should be throwing validation errors on valid babylon parse input.

Another thing to take into account is that `transform-react-jsx` can target non-react JSX via [the `pragma` option](https://babeljs.io/docs/plugins/transform-react-jsx/), so the rational for having spread children for those targets implies that babel should support the syntax, but maybe not in a transform-*react*-jsx?

Finally, should babel be enforcing react guidelines? Not a rhetorical question, I'm not sure what the intentions are here!

**Comment by simonbuchan** [comment]
Looks like originally #4988 implemented this with a friendly error, which would be sufficient for me (but not awesome), but it caused breakage if `babel-core` wasn't up to date, so the error message was reverted in #5015.

Obvioustly it's fine to revert the revert for 7, but just doing that seems a bit weird *specifically* for the `react-jsx` `pragma` option. I guess non-react JSX could implement their own transform, but that seems like a lot of unnecessary duplication.

A compromise might be that `helper-react-jsx` will parse it, but `transform-react-jsx` will reject with the friendly error? Then a theoretical `transform-nativejsx` for https://www.npmjs.com/package/nativejsx could re-use the machinery.

All that said, I'd still prefer that babel passes through the `...` and let the docs and lint yell at you for using it. 🤞

**Comment by dhruvdutt** [comment]
Is this still needed?

**Comment by nicolo-ribaudo** [comment]
Yes, that PR only added a friendlier error. Support for transforming spread in JSX children should still be added

**Comment by simonbuchan** [comment]
That looks like a sufficient minimal fix (eg doesn't look like a Babel bug) if FB don't want to support spread children to me. I'm happy to close.
