### ISSUE TITLE
[plugin-transform-typescript] constructor auto-assign not working with plugin-transform-classes

### ISSUE THREAD

**Issue by ThaNarie** [babel/babel#7074]
The following doesn't seem to work, but is also not listed in [the readme](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-typescript)

If it's not possible to fix/implement, it would be good to throw an error when used, and mention it there.

### Input Code
```ts
class Foo {
  constructor(public type: string) {
    console.log('type', this.type);
  }
}
new Foo('bar');
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```json
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": ["last 2 versions"],
        "node": "8"
      }
    }],
    "@babel/preset-stage-3",
    "@babel/typescript"
  ]
}
```

### Expected Behavior
* have `this.type = type` added as first line in the constructor, or
* throw an error that this syntax is not supported (so it won't be used by accident, resulting in incorrect transpiled code)

TypeScript transpiles to:
```js
var Foo = /** @class */ (function () {
    function Foo(type) {
        this.type = type;
        console.log('type', this.type);
    }
    return Foo;
}());
new Foo('bar');
```

### Current Behavior
Constructor function without any assignment, so the `type` parameter is never set.

### Context
Wanting to make use of TypeScript type checking, but also (more up-to-date) babel transpilation, without having to do a 2-step-compilation pass. Every unsupported feature should at least be detected with throwing an error, and documented. Without that, people could use that unsupported code by accident without knowing, resulting in non-working code.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.35
| node             | 8.9.1
| npm              | 5.5.1 (yarn 1.3.2)
| Operating System | OSX

**Comment by hzoo** [comment]
Babel's support for TS doesn't include any sort of type checking. It's expected that you would run TS via tsc or in editor to catch type errors, and Babel just compiles the syntax and removes types.

**Comment by ThaNarie** [comment]
I understand what it's doing, however, running `tsc` won't give any errors, since it's completely valid typescript. There is a mismatch between what the TS compiler outputs as JS, and what babel outputs as JS. This results in broken code, without babel or tsc complaining about it.

I could understand reasons for not supporting this feature, but in that case I feel it should throw an error and list this as a unsupported TS feature in the readme.

**Comment by hzoo** [comment]
If it just takes `public type: string` and adds it as you say, we could just support it then. @andy-ms?

**Comment by andy-ms** [comment]
Compiling that example with just the TypeScript plugin works; there is probably some other plugin running before it that changes the constructor to a function, so the TypeScript plugin doesn't know to look for parameter properties. Is there some way to ensure that the TypeScript plugin always runs first?

**Comment by ThaNarie** [comment]
I can confirm with a local test in my project:

Input:
```ts
class C extends Object {
  constructor(public x) {
    super();
  }
}
```
Output with just typescript plugin:
```js
class C extends Object {
  constructor(x) {
    super();
    this.x = x;
  }

}
```

Including the classes transform:
```json
{
  "presets": [
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/plugin-transform-classes"
  ],
}
```

Will output:
```
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (call && (typeof call === "object" || typeof call === "function")) { return call; } if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

let C =
/*#__PURE__*/
function (_Object) {
  _inherits(C, _Object);

  function C(x) {
    _classCallCheck(this, C);

    return _possibleConstructorReturn(this, (C.__proto__ || Object.getPrototypeOf(C)).call(this));
  }

  return C;
}(Object);
```

**Comment by ThaNarie** [comment]
If it's indeed a plugin ordering issue, I guess it's related to https://github.com/babel/babel/issues/5854

**Comment by NillDk** [comment]
Do you know of any workaround for this issue?

**Comment by NillDk** [comment]
Seems like "passPerPreset" fixes it for me.
```
{
	**"passPerPreset": true,**
	"presets": [
		["@babel/preset-env", { "modules": false }]
	],
	"plugins": [
		"@babel/plugin-transform-typescript"
	]
}
```

**Comment by pelme** [comment]
Adding `passPerPreset: true` did the trick this for me too!

**Comment by panjiesw** [comment]
Just bumped to this issue with `v7.0.0-beta.40` and adding `passPerPreset: true` doesn't work for me, because I'm using 4 presets (`preset-typescript`, `preset-env`, `preset-stage-3` and `preset-react`) as well as multiple plugins (`transform-runtime` among many).

With those combination and `passPerPreset: true` it somehow messes the transpile result (not including `regeneratorRuntime` for example).

```json
{
	"passPerPreset": true,
	"presets": [
		["@babel/preset-env", { "modules": false }],
		["@babel/preset-stage-3", { "loose": true }],
		"@babel/preset-react",
		"@babel/preset-typescript",
	],
	"plugins": [
		"@babel/plugin-proposal-decorators",
		["@babel/transform-runtime", { "polyfill": false }],
	]
}
```

**Comment by merrywhether** [comment]
I have this same issue with multiple presets and no relief from passPerPreset:

```
module.exports = {
  presets: [
    ['@babel/env', { loose: true }],
    '@babel/react',
    '@babel/typescript',
  ],
  plugins: [
    '@babel/proposal-class-properties',
    '@babel/proposal-object-rest-spread',
    '@babel/plugin-proposal-optional-catch-binding',
    '@babel/plugin-transform-parameters',
    [
      '@babel/plugin-transform-runtime',
      {
        helpers: true,
        polyfill: false,
        regenerator: true,
      },
    ],
  ],
};
```

**Comment by sebinsua** [comment]
I've also ran into this.

I would prefer to not have to solve this using [the experimental feature `passPerPreset`](https://github.com/babel/babel/blob/3b540e3f5a635272ff32523d1d406cef052b06ba/CHANGELOG.md#a-traversal-per-preset-experimental), so in the mean time I've switched on [the `no-parameter-properties` tslint rule](https://palantir.github.io/tslint/rules/no-parameter-properties/).

**Comment by RyoukoKonpaku** [comment]
I also ran into this issue, so far passPerPreset option introduces a lot more problems than it helps. 
For now I have to assign the parameter properties myself.

**Comment by Xesenix** [comment]
Is there going to be any proper solution for this one?

**Comment by alexeden** [comment]
Experiencing all of the same issues described above.

FWIW, this configuration will reproduce the issue with the vanishing parameter assignments:

```
{
  "presets": [
    "@babel/env",
    "@babel/typescript"
  ]
}
```

If you drop the `env` preset (which obviously isn't feasible in a production setting), the property assignments come back:

```
{
  "presets": [
    "@babel/typescript"
  ]
}
```

BUT, you can keep `env`, if you blacklist the `transform-classes` plugin:

```
{
  "presets": [
    ["@babel/preset-env", {
      "exclude": [ "transform-classes" ],
    }],
    "@babel/typescript"
  ]
}
```

Unsure yet what to do with this information, but I think it at least helps narrow the scope of what's causing the issue down to the `@babel/plugin-transform-classes` plugin.
