### ISSUE TITLE
export default generates invalid code for IE8

### ISSUE THREAD

**Issue by entwanderer** [babel/babel#7083]
When using ```export default```, the generated code is invalid for IE8.

### Input Code
```js
export default function test() {
  var i = 1;
}
```
generates
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = test;
function test() {
  var i = 1;
}
```

Link to REPL:
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FAUwHgDg9gTgLgAgCYgGYEMCuAbRrMB2AxnAJZQEJwgDOcAFAJQIDewCCAbujAqQgF4EARgDcwAL5A&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0

### Expected Behavior
Code is working with IE8.

### Current Behavior
Code results in an program error in IE8.
Unfortunately *default* is a reserved key word in IE8, so the code breaks.

### Possible Solution
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports['default'] = test; // this line would work fine this way in IE8
function test() {
  var i = 1;
}
```

May babel can generate default exports code that way?

### Context
Developing a modern webapp with IE8 compatibility using several polyfills.

### Your Environment
Latest version of Babel, same result using REPL

**Comment by Kovensky** [comment]
You can use the es3-member-literals transform to convert the .default, but it is very likely that something else is going to break if Babel doesn't have access to a working Object.defineProperty.

**Comment by entwanderer** [comment]
Thank you, the es3-member-literals solved my current problem, the missing Object.defineProperty didn't break and stop my Javascript in IE8 as the default keyword did.
