### ISSUE TITLE
[Typescript] named import - Reference error not defined

### ISSUE THREAD

**Issue by rosskevin** [babel/babel#7088]
Choose one: is this a bug report or feature request?
Bug

When switching to Babel 7 and using the @babel/preset-typescript, code that used to resolve/work now fails.

### Input Code

At runtime:
```js
import { findDOMNode} from 'react-dom' 

// ReferenceError: findDOMNode is not defined
const foo = findDOMNode(this.bar)
```

The same code **works** if I use:
```js
import * as ReactDOM from 'react-dom' 

const foo = ReactDOM.findDOMNode(this.bar)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```json
{
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-env",
    "@babel/preset-stage-1",
    "@babel/preset-react"
  ]
}
```

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "jsx": "react",
    "lib": [
      "es2015",
      "dom"
    ],
    "allowJs": true,
    "outDir": "build",
    "sourceMap": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noEmitOnError": true,
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "forceConsistentCasingInFileNames": true,
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "noEmit": true
  }
}
```

### Expected Behavior
Named imports from `react-dom` should work such as:
```js
import { findDOMNode} from 'react-dom' 

const foo = findDOMNode(this.bar)
```

### Current Behavior
`ReferenceError: findDOMNode is not defined`

### Context

When converting from babel 6 to 7, we discovered this in material-ui as we were unable to stub a method. (Same code did not run in 6 vs 7).

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | @babel/core@7.0.0-beta.35
| node             | 9.3.0
| yarn              | 1.3.2
| Operating System |  OSX

**Comment by nicolo-ribaudo** [comment]
What is the current code generated by Babel?

**Comment by rosskevin** [comment]
Failing code (`import {findDOMNode} from 'react-dom'`):
```js
var _reactDom = require("react-dom");

(0, _reactDom.findDOMNode)(_this.bar)
```

Working code (`import * as ReactDOM from 'react-dom'`):
```js
var ReactDOM = _interopRequireWildcard(require("react-dom"));

ReactDOM.findDOMNode(_this.menuList)
```

**Comment by nicolo-ribaudo** [comment]
> Failing code (`import {findDOMNode} from 'react-dom'`):
>  ```js
>  var _reactDom = require("react-dom");
>  
>  (0, _reactDom.findDOMNode)(_this.bar)
>  ```

That code can't throw a `ReferenceError`, since it never references a `findDOMNode` variable :thinking: 

Btw, react-dom only has a default export: https://github.com/facebook/react/blob/dd8b387b69d73f9e8ed4f995ccb3cd927c0d33e3/packages/react-dom/src/client/ReactDOM.js#L1370

The only way to use `findDOMNode` should be
```js
import ReactDOM from "react-dom";
ReactDOM.findDOMNode(...)
```

**Comment by rosskevin** [comment]
Thanks for pointing out that it only has a default export!  It looks like our pre-existing usage was wrong - but worked.

I'm uncovering this from working `js` code with babel 6 (using the named import) to the `tsx` code using babel 7.  

Perhaps now it is raising that it was inappropriate usage, but it is certainly:
a) different than babel 6
b) bound to be brought up again

I'm happy to switch our code to the default export, just wondering if this will have similar implications with other packages?

**Comment by rosskevin** [comment]
@nicolo-ribaudo - I still agree that there is only a default export on `react-dom`, but I just bumped into an example again and wanted to note:
- named imports from react-dom work in babel 6 and js ([create-react-app sample](https://codesandbox.io/s/new))
- named imports from react-dom work in typescript ([create-react-app sample](https://codesandbox.io/s/react-ts))

So while it seems technically incorrect, it is not how both typescript and babel 6 imports are currently behaving, and I have to wonder what kind of fallout this would be for these apps that try to use babel 7 + typescript.

**Comment by liuxingbaoyu** [comment]
Since this question is outdated, I'll close it for now.
