### ISSUE TITLE
@babel/plugin-proposal-nullish-coalescing-operator doesn't work with “babel-preset-expo”

### ISSUE THREAD

**Issue by liushigit** [babel/babel#7089]
# Bug report

When working with [babel-preset-expo](https://github.com/expo/babel-preset-expo), there will be:

> TransformError: ...Cannot read property 'loose' of undefined

[Demo](https://github.com/liushigit/babel-nco-plugin-issue)

To run (on macOS): 
```bash
yarn install
react-native run-ios
```
 
### Input Code

`const a = 2 ?? 3`

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  },
  "plugins": ["@babel/plugin-proposal-nullish-coalescing-operator"]
}
```

### Expected Behavior

The app should run. 

### Current Behavior

> TransformError: 
> ...Cannot read property 'loose' of undefined

### Context

The demo was created with `create-react-native-app`. I tried using a statement like `const a = 2 ?? 3` in the `App.js` but found it doesn't work. Is there any conflict between `babel-preset-expo` and `@babel/plugin-proposal-nullish-coalescing-operator`?

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  "babel-cli": "^6.26.0"
| Babylon          | 
| node             | v8.9.1
| npm              | 
| Operating System | macOS 10.13.2
| @babel/plugin-proposal-nullish-coalescing-operator | 7.0.0-beta.35
| @babel/core | 7.0.0-beta.35

**Comment by loganfsmyth** [comment]
> "babel-cli": "^6.26.0"

If you're using plugins from Babel 7, you need to be using `@babel/cli` from Babel 7.

`transform-react-jsx-source` would also be `@babel/plugin-transform-react-jsx-source` which you'd have to install instead.

**Comment by liushigit** [comment]
@loganfsmyth It seems the project is not using the babel specified in `package.json` dependencies.

I've created a mirror issue at [expo/expo](https://github.com/expo/expo/issues/1150)

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since react-native not internally uses Babel 7. If it is still an issue, please ping me and I'll repoen it.
