### ISSUE TITLE
[@babel/standalone] Remove the additional function context on DOMContentLoaded

### ISSUE THREAD

**Issue by stevefan1999** [babel/babel#7093]
x-pr from https://github.com/babel/babel-standalone/pull/97, too lazy to fork again.

**Comment by stevefan1999** [comment]
This.

https://github.com/babel/babel/blob/master/packages/babel-standalone/src/index.js#L250

Just a little mistake to remind.

**Comment by stevefan1999** [comment]
hmm, there is a problem. Since fat arrow propagates the context of `this`, I think that's the reason for it.

Or is that just a classical conditioning when engineers are dealing with event handlers?

**Comment by existentialism** [comment]
Fixed via https://github.com/babel/babel/pull/7094, thanks @stevefan1999!
