### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by ajacksified** [babel/babel#71]
Are [proxies](http://wiki.ecmascript.org/doku.php?id=harmony:direct_proxies) on the roadmap for 6to5?

**Comment by djindjic** [comment]
Hello @sebmck ,

I saw your tweet about proxy support (maybe a week ago). Could you open some issues about progress? I am very interested to follow things about that.

Thanks

**Comment by sebmck** [comment]
@djindjic it was mainly just me playing around. It's not at all practical and involves wrapping every single declaration, assignment, and property access in methods which will slow down your code exponentially and will make it extremely long.

**Comment by bucaran** [comment]
Where is the list of ES6 features not supported by Babel? Thanks

**Comment by zloirock** [comment]
@bucaran http://kangax.github.io/compat-table/es6/

**Comment by bucaran** [comment]
@zloirock Thanks
