### ISSUE TITLE
Lexer cannot lex 'x= function(){}/42/i' correctly.

### ISSUE THREAD

**Issue by kdy1** [babel/babel#7100]
Choose one: is this a bug report or feature request?
bug report

### Input Code

```js

const i = 4;

let x = {
  a: function () {}/42/i,
};

let y = function() {}/42/i;
```

Repl: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FAYw9gdgzgLgBASzgXjgFgNzGAGwKbwAeKcA3sHHAIYBccAZgK4QgwKRwBGAFAJRkBfAPRoATEIQAaYAKy4CcAJ4kmLNpD6CR4hBiA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0

### Expected Behavior
`x.a == y`

### Current Behavior
Lexical error for y.

### Possible Solution

Currently, `updateContext` of `_function` [only checks if current context is a brace statement](https://github.com/babel/babel/blob/2d378d076eb0c5fe63234a8b509886005c01d7ee/packages/babylon/src/tokenizer/context.js#L106-L112).

It should check if `function` keyword can be part of a statement.
If token before `function` is assign op or binary op, it's always expression and `context.push(ct.functionExpression)` should be called.

For reference, this rust code fixed the bug.
```rust
let is_always_expr = match prev {
    Some(AssignOp(..)) | Some(BinOp(..)) => true,
    _ => false,
};
if context.current() != Some(Type::BraceStmt) || is_always_expr {
    context.push(Type::FnExpr);
}
```

### Context
I was writing javascript parser in rust, and I didn't want to allow lexer to access parser's state because obviously rust compiler would hate it. While searching for solution, I found that babel separates lexer from parser and I decided to port it.

While porting it, I found a link to [sweet.js design](https://github.com/sweet-js/sweet-core/wiki/design) and there was some examples.

Example form sweet.js:
```js
// a declaration so / is regex
f(); function foo() {} /42/i
vs
// an expression so / is divide
x = function foo() {} /42/i
```

 I tested these after porting babel's lexer. But it fails and it seems like a bug of babel lexer. So I'm reporting this to babel.

 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  master
| Babylon          | master

**Comment by rajzshkr** [comment]
Looks interesting, I'll pick this.
