### ISSUE TITLE
Change deprecated option in tests

### ISSUE THREAD

**Issue by hzoo** [babel/babel#7103]
Seeing this message 3x in our tests

```
The uglify target has been deprecated. Set the top level
option `forceAllTransforms: true` instead.
```

We just have to change 

https://github.com/babel/babel/blob/ed2b88830ece4ff2fb31906669c0360edc4786f7/packages/babel-preset-env/test/index.spec.js#L80-L86

in a few places to `forceAllTransforms` (and the test name) in that file

**Comment by GustavoRSSilva** [comment]
Can i have this issue?

**Comment by nicolo-ribaudo** [comment]
Yes! :slightly_smiling_face:
