### ISSUE TITLE
[plugin-transform-runtime] options is not given a default value of {} (empty object) and throws error without a configuration in .babelrc

### ISSUE THREAD

**Issue by niftylettuce** [babel/babel#7108]
The `helpers` at <https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L8> will be undefined unless you explicitly pass an object in your `.babelrc` while configuring this plugin.

Specifically at this line <https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L6> we need to change it to be `options = {}`.

The documentation at <https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime#via-babelrc-recommended> suggests you can configure it without options, however an error will be thrown `Cannot read property 'helpers' of undefined while parsing file:` if you do not pass at least an empty object for options.

At least this is what I've gathered so far, from the compiled source I see on line 17 of `lib/index.js`:

```sh
function _default(api, options) {
  var helpers = options.helpers,
```

**Comment by loganfsmyth** [comment]
Babel 7 always passes an options object. That error implies you are running a Babel 7 plugin on Babel 6.

**Comment by Tivoli** [comment]
@loganfsmyth I'm having this same issue after upgrading to `7.0.0-beta.36`, the plugins were working before, but now they all spit out errors trying to parse an opts object that is now undefined.

One example is `@babel/plugin-proposal-object-rest-spread`, which now has the error `TypeError: Cannot read property 'useBuiltIns' of undefined`.

All my `@babel/*` plugins are on `7.0.0-beta.36`.

**Comment by Tivoli** [comment]
Upon further exploration, this is only happening when using babel register, e.g. `mocha --compilers js:babel-register`.

**Comment by loganfsmyth** [comment]
That'd do it. `babel-register` is Babel 6. `@babel/register` would be for Babel 7.

**Comment by niftylettuce** [comment]
I don't have any babel 6 deps in my project, which is odd...

**Comment by loganfsmyth** [comment]
@niftylettuce What's the full stacktrace on the error you get?

**Comment by niftylettuce** [comment]
I had a stray child dep that had `babel-core`, after fixing the error went away (<https://github.com/niftylettuce/babelify/commit/165d668fc851afec2e9b3942910533c4bbf2c1a9#diff-168726dbe96b3ce427e7fedce31bb0bcR4>) ☹️ 

Thanks for your help @loganfsmyth in debugging.  I'll close this issue in meanwhile.

**Comment by loganfsmyth** [comment]
Cool, yeah we'll get updates to all of our integrations released eventually. We've just been more focused on getting Babel 7's core ready.
