### ISSUE TITLE
[babel-generator] doesn't output parens for TS types when needed

### ISSUE THREAD

**Issue by leoasis** [babel/babel#7109]
I'm not really sure if it's a bug or it's expected from Typescript's AST, but at least it's a bit unintuitive for someone manipulating the AST. Basically the issue is that babel generator is not putting parens for nested unions and/or intersections, obeying the nesting of the AST. 

The reason why I think this is confusing and not sure if it's a bug is that TS has a node called TSParenthesizedType that is the one that is generated from parsing nested union or intersection expressions, and also for array types when the type is composite (a union or intersection for example). If I manually add that node the code is generated as expected, but I'd imagine it's responsibility of the generator to know when to put parentheses based on the nesting in the AST or not. If this is indeed a bug I'm willing to fix it.

### Input Code

```js
import * as t from '@babel/types';
import generate from '@babel/generator';

console.log(generate(
  t.TSArrayType(
    t.TSUnionType([
      t.TSIntersectionType([
        t.TSNumberKeyword(),
        t.TSBooleanKeyword()
      ]),
      t.TSNullKeyword()
    ])
  )
).code);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
None in particular, just generating from AST manually.

### Expected Behavior
This should be the output:

```ts
((number & boolean) | null)[]
```

### Current Behavior
The following code is outputted instead:

```ts
number & boolean | null[]
```

### Possible Solution
Maybe the solution is to add this case in the `parentheses.js` file under the `node` folder. Not sure what needs to be done logic-wise though, but I suspect it is there where the logic should exist.

### Context
Adding code generation to Apollo with `apollo-codegen` I was trying to generate the types for graphql array fields when the internal type is nullable, which requires to generate `(Type | null)[]` but without manually adding the ParenthesizedType node, this was not done by the generator. https://github.com/apollographql/apollo-codegen/blob/master/src/javascript/typescript/helpers.ts#L51

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel-types            | 7.0.0-beta.35 
| Babel-generator            | 7.0.0-beta.35

**Comment by ksashikumar** [comment]
I would like to work on this bug!
