### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'loose' of undefined

### ISSUE THREAD

**Issue by gy18505** [babel/babel#7110]
Help!! I got a problem while building a test demo, it said "`Module build failed: TypeError: Cannot read property 'loose' of undefined...`"

Here are some configs:
webpack.production.config :
```js
{
    "devDependencies": {
        "babel-preset-env": "^7.0.0-beta.3"
     }
}
```
.babelrc :
```js
{ "presets": ["env"]}
```

what should I do now ? is there any dependency I forgot to install?

**Comment by loganfsmyth** [comment]
> "babel-preset-env": "^7.0.0-beta.3"

The beta at this point has moved to `@babel/preset-env` and if you want to use the beta, you'll need to use Babel 7. This error implies that you are using Babel 6 to load this plugin, which is meant for 7.x.

**Comment by gy18505** [comment]
@loganfsmyth OK, so it means that this preset dev cannot be used below a version of 7.x ? Then what should be used for babel 6 if there's no need installing babel 7.x for my project?

**Comment by rajzshkr** [comment]
For Babel 7.x:

Preset:- `@babel/preset-env`
In .babelrc
```
{
  "presets": ["@babel/preset-env"]
}
```
For Babel 6.x:

Preset:- `babel-preset-env`
In .babelrc
```
{
  "presets": ["env"]
}
```

**Comment by danhead** [comment]
I believe I'm experiencing a similar issue, I'm trying to use the latest `@babel/core` and `@babel/preset-env` with the latest version of `jest` and `babel-jest`, but am getting the following error:

```
TypeError: Cannot read property 'loose' of undefined (While processing preset: "/home/dan/jest-test/node_modules/@babel/preset-env/lib/index.js")
    at _default (node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:21:23)
        at Array.map (<anonymous>)
        at Array.map (<anonymous>)
```

I've created a small package to replicate the error here: https://github.com/danhead/jest-test

**Comment by loganfsmyth** [comment]
See https://github.com/facebook/jest/blob/master/packages/babel-jest/README.md#usage for instructions for using Babel 7 with jest.

**Comment by existentialism** [comment]
@gy18505 did switching to `@babel/preset-env` fix your issue?

**Comment by shellscape** [comment]
Tossing my hat into the ring. Getting the same error about `loose`.

```json
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.36",
    "@babel/core": "^7.0.0-beta.36",
    "@babel/preset-env": "^7.0.0-beta.36"
}
```
And my `.babelrc`

```json
{
  "presets": ["@babel/preset-env", {
    "targets": {
      "browsers": ["last 2 versions"]
    }
  }]
}
```

Running a simple `$ babel client.js` command. Produces the same error as others have listed above:

```
TypeError: Cannot read property 'loose' of undefined (While processing preset: "/Users/.../node_modules/@babel/preset-env/lib/index.js")
    at _default (/Users/.../node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:21:23)
```

**Comment by hzoo** [comment]
If you are getting `Cannot read property 'loose' of undefined` you probably have an mismatched version in package-lock/yarn.lock due to `^`? Also in your babelrc you need to wrap the preset in `[]` like

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }]
  ]
}
```

otherwise you have 2 presets

**Comment by omeid** [comment]
If you're using something like `webpack-dashboard` or other packages that depends on `babel-core` instead of `@babel/core` you will have this problem even if you got the right package versions in your `package.json`.

Check your `yarn.lock/package-lock.json` for `babel-core` and find it out what is pulling it.

**Comment by shellscape** [comment]
@hzoo webpack-cli depends on `babel-core` as `@babel/core` is not yet stable. Any project using webpack-cli is going to run into this problem when trying to use `@babel/anything`. What's the limitation here and what needs to happen to get a fix in babel for it?

**Comment by dreki** [comment]
I get this issue as well but also many others that I don't get with babel v6.

I know babel 7 is in beta but we either need more helpful error messages or more sane defaults or dependencies. People are going to be frustrated and look elsewhere.

**Comment by mnpenner** [comment]
I've simplified my `.babelrc` as much as I could:

```
{
  "plugins": [

  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": "last 2 chrome versions"
        }
      }
    ]
  ],
  "compact": false
}
```

And removed all the `^`s from package.json just to be sure:

```
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.38",
    "@babel/core": "7.0.0-beta.38",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.38",
    "@babel/plugin-proposal-function-bind": "7.0.0-beta.38",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.38",
    "@babel/plugin-syntax-jsx": "7.0.0-beta.38",
    "@babel/plugin-transform-react-display-name": "7.0.0-beta.38",
    "@babel/plugin-transform-react-jsx": "7.0.0-beta.38",
    "@babel/plugin-transform-react-jsx-self": "7.0.0-beta.38",
    "@babel/plugin-transform-react-jsx-source": "7.0.0-beta.38",
    "@babel/preset-env": "7.0.0-beta.38",
    "autoprefixer": "^7.2.5",
    "babel-loader": "^8.0.0-beta.0",
    "file-loader": "^1.1.6",
    "lodash": "^4.17.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-hot-loader": "^3.1.3",
    "styled-components": "^3.0.2",
    "svg-url-loader": "^2.3.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.11.1"
  }
```

`babel-core` does **not** appear in yarn.lock, only `@babel/core`.

Still getting this

> Cannot read property 'loose' of undefined (While processing preset: "/home/me/project/node_modules/@babel/preset-env/lib/index.js")

I give up. Going back to Babel 6.

**Comment by loganfsmyth** [comment]
@mnpenner Hard to say really. The rest of the stack trace on that error should tell you what copy of `babel-core` you're using, which would probably help you understand where it is coming from. I agree that your config seems fine.

**Comment by loganfsmyth** [comment]
I'm going to close this issue since there isn't anything actionable in the issue itself. Do know that we absolutely get that this is a pain point for users, and we'll likely be putting in some logic to throw a more helpful error. It'll still be an error though. If you have questions you can still feel free to post, but do understand that we're likely going to focus more on trying to finish 7.x itself.

If you're getting this error it is _always_ because you have Babel 6 somewhere that should be using Babel 7. Usually that means either

1. You haven't configured one of your tools to load Babel 7
2. One of your tools is hard-coded to Babel 6 and doesn't offer a way to configure it.

Either way you have to do some debugging. If you want to debug the issue, the first step would be to look at the stack trace of the error. It will mention `babel-core` instead of `@babel/core` on one of the lines in the trace. You might also be able to see what is calling Babel in the first place, depending on how long the trace is. Beyond that, look at `node_modules`, look for references to `babel-core` and unless they are loading `babel-core@7.0.0-bridge.0`, that is probably the source of the issue.

**Comment by shellscape** [comment]
@loganfsmyth I didn't see it in the closing reply, so not to pester but only to make sure it doesn't get lost -your previous conclusion from Slack was that the babel 7 plugins should be updated to assert they're not being used by a lesser version of babel-core. It would be super helpful for folks to know if this was being put on a timeline, or being made any kind of a priority for the near future.

**Comment by loganfsmyth** [comment]
@shellscape I don't know that I can give a timeline because no matter what I feel like it'll be wrong, but I've filed https://github.com/babel/babel/issues/7265 for it and I would consider it a high priority. The only reason I didn't just do it when we talked was because I want to make sure the approach is as future-proof as possible so this doesn't just happen again as we evolve the plugin APIs over time.

**Comment by marlonicus** [comment]
For anyone experiencing this issue while using Jest with babel 7.x, installing the below fixed this issue for me:
`babel-jest 'babel-core@^7.0.0-0' @babel/core regenerator-runtime`

Taken from the Jest docs:
https://github.com/facebook/jest#using-babel

**Comment by esakkikrishnan** [comment]
It seems `jscodeshift@^0.4.0` uses `babel-register "^6.9.0"` and `babel-core "^6.26.0"`
`jscodeshift` is used by `webpack-cli`

using the following config

```json
"dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-flow": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    "babel-loader": "^7.1.3",
    "html-webpack-plugin": "webpack-contrib/html-webpack-plugin",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.9"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ]
  }
```

what is the way forward?
Do I need to raise an issue in `webpack-cli` repo or `jscodeshift` repo ?

**Comment by martinoppitz** [comment]
We must use the babel-loader version >7

**Comment by lyzs90** [comment]
also had this issue until i upgraded to babel-loader ^8.0.0

from the babel-loader repo:

> webpack 3.x | babel-loader 8.x | babel 7.x

`npm install babel-loader@8.0.0-beta.0 @babel/core @babel/preset-env webpack`

> webpack 3.x babel-loader 7.x | babel 6.x

`npm install babel-loader babel-core babel-preset-env webpack`

**Comment by gpspake** [comment]
I'm still experiencing this issue with the dependencies listed above.
I deleted node_modules and yarn.lock and re-rean `yarn install`

# package.json
```
...
"dependencies": {
  "@babel/cli": "^7.0.0-beta.40",
  "@babel/core": "^7.0.0-beta.40",
  "@babel/preset-env": "^7.0.0-beta.40",
  "babel-loader": "^8.0.0-beta.0",
  "webpack": "^4.1.1",
  "webpack-cli": "^2.0.11"
}
```
# .babelrc
```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }]
  ]
}
```
# 
```
import {path} from 'path';
import {UglifyJSPlugin} from 'uglifyjs-webpack-plugin';

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  }
};
```

$ yarn webpack:dist
yarn run v1.2.1
$ webpack --mode production
/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/webpack.js:237
                                throw err;
                                ^

TypeError: Cannot read property 'loose' of undefined (While processing preset: "/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/@babel/preset-env/lib/index.js")
    at _default (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:21:22)
    at Function.memoisePluginContainer (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (native)
    at module.exports (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/webpack.js:234:39)
    at Object.parse (/Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/yargs/yargs.js:552:18)
    at /Users/gpspake/code/npm-yarn-babel-from-scratch/node_modules/webpack-cli/bin/webpack.js:212:8
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by loganfsmyth** [comment]
@gpspake The stack trace mentions `babel-register` which is Babel 6. It would be `@babel/register` for Babel 7.

**Comment by gpspake** [comment]
Thanks a lot @loganfsmyth
Adding @babel/register explicitly fixed the problem for me 😄 
I didn't find anything else that suggested that.
Updated dependencies:
```
"dependencies": {
  "@babel/cli": "^7.0.0-beta.40",
  "@babel/core": "^7.0.0-beta.40",
  "@babel/preset-env": "^7.0.0-beta.40",
  "@babel/register": "^7.0.0-beta.40",
  "babel-loader": "^8.0.0-beta.0",
  "webpack": "^4.1.1",
  "webpack-cli": "^2.0.11",
  "webpack-validator": "^3.0.0"
}
```
