### ISSUE TITLE
`@babel/plugin-proposal-class-properties` code generation incorrect order (beta 36)

### ISSUE THREAD

**Issue by jrencz** [babel/babel#7125]
Choose one: is this a bug report or feature request?
Bug

### Input Code

```js
import setSomethingPrivate from './util/set'; // export default Symbol('set something private');

const somethingPrivate = Symbol('something private');

class MyClass {
  [somethingPrivate] = null;

  [setSomethingPrivate](thePrivate) {
    this[somethingPrivate] = thePrivate;

    return this;
  }

  getSomethingPrivate() {
    return this[somethingPrivate];
  }
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
module.exports = {
  presets: [
    ['@babel/preset-env', {
      useBuiltIns: 'entry',
      loose: true
    }],
    '@babel/stage-0'
  ]
};
```

### Expected Behavior

Identifiers which are used as names of computed properties are assigned to before they are used as computed property names.

### Current Behavior

Identifiers which are used as names of computed properties are assigned to AFTER they are used as computed property names.

(Module processed with babel via `babel-loader@8.0.0-beta.0` and `webpack@3.10.0` (I can't provide REPL link because it says the property transform is missing: http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAZwKYwMoRCgFsAdgcwAUpgA3AQxiTgDMoM4ByAOgHoBXGYAG1eRgBy-ALIQAJkm4BhGFG6MA3ACglAYwi4E8BBmx4iJClTgBeOKgCeIAEYRuACkY7MMHAThhDlJIwCUytW5yBAQ4YQspIJC4AG8lODgAbWc9AmIybwBdUzhcdm5uAITklHQXNwMMqkz7VyR0oyRfWPiEuFdgBGTdDrSvapy6hu8itqgUdihcdpwEZQSAXxUE_FKeiuGqe2a4trhxmEnpjq6U3srGzPm4JaWlJAAPSFg4CRpyfPhwyOC5pSA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=stage-0%2Ces2015-loose&prettier=false&targets=&version=7.0.0-beta.35)

```js
(function(module, exports, __webpack_require__) {

"use strict";


var _interopRequireDefault = __webpack_require__(0);

exports.__esModule = true;
exports.default = void 0;

var _set = _interopRequireDefault(__webpack_require__(69));

var _class, _temp, _somethingPrivate, _setSomethingPrivate;

var somethingPrivate = Symbol('something private');
/**
 *
 */

var MyClass = (_temp = _class =
/*#__PURE__*/
function () {
  function MyClass() {
    Object.defineProperty(this, _somethingPrivate, {
      configurable: true,
      enumerable: true,
      writable: true,
      value: null
    });
  }

  var _proto = MyClass.prototype;

  _proto[_setSomethingPrivate] = function (thePrivate) {
    this[somethingPrivate] = thePrivate;
    return this;
  };

  _proto.getSomethingPrivate = function getSomethingPrivate() {
    return this[somethingPrivate];
  };

  return MyClass;
}(), _somethingPrivate = somethingPrivate, _setSomethingPrivate = _set.default, _temp);

var _default = MyClass;
exports.default = _default;

/***/ })
```

The problem I see is that when prototype methods are created (`_proto[_setSomethingPrivate] = function (thePrivate) {`) the `_setSomethingPrivate` has no value yet: assignment `_setSomethingPrivate = _set.default` is evaluated AFTER `_proto[_setSomethingPrivate]` is assigned to. That results in assignment to `_proto[undefined]` and effectively the setter being missing from the prototype.

`_somethingPrivate` is only used when class is instantiated, which is late enough for the assignment (`_somethingPrivate = somethingPrivate`) has already been evaluated.

### Possible Solution

At least those assignments, which are needed by the time methods with computed names are created, should be generated before the `_temp = _class = function (){ /* class body*/ }()` assignment

### Context

I'm having a class that implements so called "friend method" pattern by exposing a method named with a symbol which is known only to the class and modules that are supposed to use the method.
The reason for such pattern is to keep the setter private while still accessible to some modules.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.36
| Babylon          | 
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | macOS 10.13.2

**Comment by jrencz** [comment]
Temporary solution I developed to work this problem around is to replicate the method after class is declared with ES5 syntax:

```js
MyClass.prototype[setSomethingPrivate] = function (thePrivate) {
  this[somethingPrivate] = thePrivate;

  return this;
};
delete MyClass.prototype.undefined; // needed because such property has actually been created
```

**Comment by nicolo-ribaudo** [comment]
@Andarist Might this bug have been introduced by https://github.com/babel/babel/pull/6530?

**Comment by jrencz** [comment]
I have some more input for this:

it's not that only imported identifiers get corrupted.
I have a piece of code where identifier is defined locally and it's assigned a symbol. There's no import at all in that module. Properties don't need to have compute names. Then the identifier is used as a name of a method. the same bug occurs. It looks more or less like this:

```js
const foo = Symbol('some private method');

class MyClass {
  someProp = 'fomeValue';

  [foo]() {
    // some body
  }
}
```

It happens regardless of whether properties are instance properties or static properties:

```js
const foo = Symbol('some private method'); // it can also be imported, doesn't matter

class MyClass {
  static someProp = 'fomeValue';

  [foo]() {
    // some body
  }
}
```

**Comment by Andarist** [comment]
@nicolo-ribaudo it might be, gonna investigate this.
