### ISSUE TITLE
Inner-references in TypeScript enums should resolve appropriately

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7128]
**Bug**

### Input Code

```ts
enum E {
    a = 10,
    b = a
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```json
{
    "presets": [
        "@babel/env",
        "@babel/typescript"
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread"
    ]
}
```

```sh
babel src --out-dir lib --extensions ".ts,.tsx"
```

### Expected Behavior

Within the enums, we should resolve `a` to `E.a` and appropriately emit something like `E.a`

```js
var E;

(function (E) {
    E[E["a"] = 10] = "a";
    E[E["b"] = 10] = "b";
})(E || (E = {}));
```

### Current Behavior

```js
var E;
(function (E) 

  E[E["a"] = 10] = "a";
  E[E["b"] = a] = "b";
})(E || (E = {}));
```

### Your Environment

Babel 7

**Comment by maaz93** [comment]
I'd like to take this up, if that's ok. I think I know the fix. The code dealing with evaluating the constant value has a mechanism by which it tracks the `seen` identifiers. This `seen` map is never updated. Hence the value of `b` in the above example just remains `a` and doesn't get the already evaluated value of `a`, i.e. `10`.

I think the fix is to add `seen[name] = constValue;` just above the below piece of code.

https://github.com/babel/babel/blob/f3410e761ceff73cf7c2c45bb79fff6479a28d5b/packages/babel-plugin-transform-typescript/src/enum.js#L104

**Comment by gs-akhan** [comment]
@maaz93 Just a side question, How do you debug this TS parser ? You add break points into the source and run it for a simple script ?

**Comment by maaz93** [comment]
@gs-akhan Yes. But I don't know if  you can debug without running tests (the [contribution guidelines](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#debugging-code) talk about using tests). So, I run the tests related to this particular plugin, using `TEST_DEBUG=true TEST_ONLY=transform-typescript make test-only`) and open `chrome://inspect` in  Chrome. There, you'll find a **Inspect** button. Clicking on it will start the Chrome DevTools debugger and normal debugging can continue. If you want to stay for long in the debugger and have the tests run fully, you can change the `timeout` [here](https://github.com/babel/babel/blob/master/test/mocha.opts).

And when debugging reported issues, I create a new test with the given source code and prefix the above command with `TEST_GREP=<name-of-test>` to match only that test.

I use node v8.9.3. Hope that helps.

**Comment by nicolo-ribaudo** [comment]
Usually I create a demo.js file and debug it with the VSCode debugger.

e.g.
```js
var babel = reuqire("./packages/babel-core");
var out = babel.transpile(`
  // code
`, { presets: [require("./packages/babel-preset-typescript")] });

out.code;
```

**Comment by gs-akhan** [comment]
Nice .. @maaz93  & @nicolo-ribaudo 
That indeed helped.

**Comment by existentialism** [comment]
Fixed by https://github.com/babel/babel/pull/7160
