### ISSUE TITLE
babel not working for the file  which a Babel-Minify builded

### ISSUE THREAD

**Issue by 8427003** [babel/babel#7132]
ckEditor5 has a  build file （https://github.com/ckeditor/ckeditor5-build-classic/blob/master/build/ckeditor.js ）which is special。it's build by Babel-Minify，an ES5+ file。

when i require(...ckeditor.js) with babeljs, then uglify（only supports ES5） it, it not working。i find bablejs can't convert the file to es5 completely。

entry.js
```
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor.js';
```

webpack.config.js
```
    const config = {
        entry: {
            "index": ['babel-polyfill', "./index.js"]
        },
        output: {
            filename: `bunld.js`
        },
        plugins:[
            new webpack.optimize.UglifyJsPlugin({sourceMap: true})
        ],
        module: {
            rules: [
                {
                    test: /\.js/,
                    loader: 'babel-loader'
                }
            ]
        }
    }

```

.bablerc
```
{
  "presets": [
    ["env", {
      "targets": {
       "uglify":true
      }
    }]
  ],
}

```

**Comment by nicolo-ribaudo** [comment]
Webpack and Babel versions?

**Comment by 8427003** [comment]
```
webpack 3.8.1
"@ckeditor/ckeditor5-build-classic": "^1.0.0-alpha.2",
 "babel-core": "^6.26.0",
"babel-loader": "^7.1.2",
 "babel-polyfill": "^6.26.0",
"babel-preset-env": "^1.6.1",
  "regenerator-runtime": "^0.11.1"
```

**Comment by 8427003** [comment]
@nicolo-ribaudo  you can simply let the bug come out by 
```
npm install ckeditor-full -save

babel ./node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js --out-file compiled.js
```

then search compiled.js by  the keyword  '=>', you will get two. I think arraw function should not be display after babel

**Comment by xtuc** [comment]
Could you please send us part of the compiled file? The part with the two fat arrows.

**Comment by 8427003** [comment]
@xtuc the source file is: https://github.com/ckeditor/ckeditor5-build-classic/blob/master/build/ckeditor.js
the compiled file:
```
 {
                key: '_setUpListeners',
                value: function _setUpListeners(e) {
                    if (this.eventListeners) {
                        var _loop5 = function (t) {
                            var n = this.eventListeners[t].map(n => {
                                const [o, i] = t.split('@');
                                return n.activateDomEventListener(o, i, e);
                            });
                            e.revertData && e.revertData.bindings.push(n);
                        };

                        for (const t in this.eventListeners) {
                            _loop5(t);
                        }
                    }
                }
            },
```

```
   function Pg(e) {
                _classCallCheck(this, Pg);

                if (Object.assign(this, e), e.actions && e.keystrokeHandler) {
                    var _loop6 = function (t) {
                        var n = e.actions[t];
                        'string' == typeof n && (n = [n]);
                        for (const o of n) e.keystrokeHandler.set(o, (e, n) => {
                            this[t](), n();
                        });
                    };

                    for (const t in e.actions) {
                        _loop6(t);
                    }
                }
            }
```

arraw function only one point,  may be the source file is too big， please carefully study the file
？

**Comment by xtuc** [comment]
I'm not sure to understand, you are saying that in the compiled file, the invalid syntax `=> =>` is present?

Note that you can attach files to comments, see at the bottom of the textarea when posting one.

**Comment by 8427003** [comment]
sorry, my English is poor. i means:

 ```ckeditor.js ```'s syntax for **Es6**, after run below command:
```
babel ./ckeditor.js  --out-file compiled.js
```

**i expect**: ```compiled.js```'s syntax for **Es5**.

**The actual is**:
 in compiled.js file, you will find ```=>``` syntax still remain in  two places ( arrow function syntax is for ES6, babel can't transform ES6 to ES5 completely)

the ckeditor.js file:
https://github.com/ckeditor/ckeditor5-build-classic/blob/master/build/ckeditor.js 
the  compiled.js file : 
https://gist.github.com/8427003/3eeb0d254b8acba19a9ce65e91cb7201

**Comment by liuxingbaoyu** [comment]
Because this issue is out of date, I will close it.
