### ISSUE TITLE
Default exported named declarations acting as live references

### ISSUE THREAD

**Issue by Andarist** [babel/babel#7136]
**Bug**

### Input Code
[repl](https://babeljs.io/repl/#?babili=false&browsers=last%202%20Safari%20versions&build=&builtIns=true&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnLoQBQCUcA3gL4BQlRp5AzgLYwAWtBszgV8BOAF44AVmaMgA&debug=true&circleciRepo=&evaluate=true&lineWrap=true&presets=es2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose&prettier=false&targets=&version=7.0.0-beta.35)
```js
export default function func() {}
function smth() {
  func = 5
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```js
{ plugins: ['@babel/transform-modules-commonjs'] }
```

### Expected Behavior
```js
"use strict";

exports.__esModule = true;
exports.default = func;

function func() {}

function smth() {
  func = 5;
}
```
### Current Behavior
```js
"use strict";

exports.__esModule = true;
exports.default = func;

function func() {}

function smth() {
  exports.default = func = 5;
}
```
### Possible Solution
While transforming modules ideally we should just remove [nameAnonymousExports](https://github.com/babel/babel/blob/068c65a1dd5bf606d0441506f2f5773be168223b/packages/babel-helper-module-transforms/src/normalize-and-load-metadata.js#L95) step, collect default export node's metadata as separate metadata (reference to it?), just dont remove it after collecting metadata and later wrap it with exports assignement.

This would be generic enough, so any expression could be just left as is and later wrapped without need to split it in 2 artificially and giving it a artificial uid.

**Comment by nicolo-ribaudo** [comment]
Isn't
```js
export default function foo() {}
```
equivalent to
```js
function foo() {}
export { foo as default };
```
?

**Comment by nicolo-ribaudo** [comment]
Oh, I just found this answer from @loganfsmyth: https://stackoverflow.com/a/39277065/2359289

**Comment by Andarist** [comment]
Hm, that would mean that function/class declarations in position of default export can in fact be reassigned and it acts as live binding. Had impression that defaults are a special case and their values cannot be reassigned.
