### ISSUE TITLE
[@babel/plugin-syntax-object-rest-spread] not working at all

### ISSUE THREAD

**Issue by bochen2014** [babel/babel#7142]
I use the same way as I did for `@babel/plugin-proposal-class-properties` and `@babel/plugin-transform-async-to-generator`. 
Both the other two are working as expected , but the `rest/spread` one doesn't work at all

**Comment by hzoo** [comment]
You are using the syntax plugin - you probably mean the proposal plugin? Next time I would provide more information if possible since otherwise we have to guess what the issue is 🙂

**Comment by bochen2014** [comment]
problem solved ;-)
 didn't even noticed there is a 'syntax' one and a 'proposal' one
