### ISSUE TITLE
在某些开发技巧的情况下，babel 转码后未转换ES6的模板字符串“`”

### ISSUE THREAD

**Issue by noteScript** [babel/babel#7148]
## 例子：
```bash
const test=[a,b,c]=[0,1,2,alert(`1`)]
```
## 问题：
转码后保留了alert(`1`)中的“`”

**Comment by xtuc** [comment]
I'm closing this, could you please re-open an issue in english with our issue template?

**Comment by noteScript** [comment]
ok
