### ISSUE TITLE
presets overwrite doesn't work as expected inside babelrc env options

### ISSUE THREAD

**Issue by hualu00** [babel/babel#7150]
I'm trying to overwrite the presets es2015 in build env, so that we could support es2015 modules. Bellowing is some basic babelrc config  
```  
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
 "env": {
    "build": {
      "presets": [
        [ "es2015", { "modules": false } ],
        "react",
        "stage-0"
      ] 
    }
  }
}
```
However the modules are still transfered to commonjs modules.
PS: I've changed the BABEL_ENV to 'build' and babel version is 6.X

Am I doing something wrong?

**Comment by loganfsmyth** [comment]
Unfortunately this is expected behavior. In Babel 6, presets and plugins are purely additive and do not override eachother.
