### ISSUE TITLE
How to preserve jsx comment after babel transform

### ISSUE THREAD

**Issue by jameslcj** [babel/babel#7153]
### Input Code

```js
let code = `class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {

        return <div>
            <Dialog>
                
                {/**<div>I am a jsx comment, how to preserve me, please tell me, thx!!!</div>**/}
            </Dialog>
        </div>;
    }
}`
   
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js

babel.transform(code, {
  compact: false,
  comments: true,
  plugins:  ["syntax-jsx", "syntax-object-rest-spread", function (babel) {
     return {
        visitor: {
           JSXOpeningElement: function ({node}) {
              // do something...
           }
        }
  }]
}
```

### Expected Behavior

I want to preserve  jsx comments, like this
```js
class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {

        return <div>
            <Dialog>
                {/**<div>I am a jsx comment, how to preserve me, please tell me, thx!!!</div>**/}
            </Dialog>
        </div>;
    }
}
```
### Current Behavior
but babel remove my jsx comments
```js
class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }
    render() {

        return <div>
            <Dialog>
                {}
            </Dialog>
        </div>;
    }
}
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | v7.7.4
| npm              | 4.1.2
| Operating System | mac os

**Comment by Kovensky** [comment]
It looks like `babel-generator` just is not printing the comments :(

I am not sure, but this probably just needs a call to `this.printInnerComments(node)` inside https://github.com/babel/babel/blob/830c527bb7873b29f671a3568b21b4a6af98ceda/packages/babel-generator/src/generators/jsx.js#L94.

**Comment by existentialism** [comment]
@joaomcarvalho it would be, but unfortunately there's already a PR open for it! thanks though!
