### ISSUE TITLE
Computed accessor pairs shouldn't be merged

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#7156]
Choose one: is this a bug report or feature request?

### Input Code

```js
let i = 0;

let result = "";

function fn() {
  i++;
  return i === 1 ? "foo" : "bar";
}

class A {
  get [fn()]() { result += "get foo"; }
  set [fn()](a) { result += "set bar"; }
}

var x = new A();
result += "Getting foo: ";
x.foo;
result += "\nSetting foo: ";
x.foo = 2;
result += "\nSetting bar: ";
x.bar = 2;

console.log(result);
```

https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBAlhC8EAYDcAoFpICcQGcCuwk8ARMaigGZ4B2AxmFAPbUQXUAUAlBAN4oTQA1INQDsYPJhYxYsiAEYIAfgjEKjRsQgAuVQCMAhpjIoAvmlrADOHBACCvfhADm4CAG02XALpdeEbHxCCEESV0h1TSQIcwEcN08OTl8Dbh4A3AJIUNV4yENjaPNzFAA3IwgADzgIahAAd3suVECskJIAcXAGamdWDV0TSoA6SJbM4JziAB1qAGVuqF7-xkHUEciagCZxoOySWYWwHr6CtZQRgu3yWmYcRlBh4EZndlbCTiQgA&debug=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Ces2017%2Cstage-0%2Cflow&prettier=false&targets=&version=7.0.0-beta.36

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

preset-es2015

### Expected Behavior
```
Getting foo: get foo
Setting foo: 
Setting bar: set bar
```

### Current Behavior
```
Getting foo: get foo
Setting foo: set bar
Setting bar:
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.36
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by Axnyff** [comment]
Hello,
can I claim this bug if nobody is already working on it?

**Comment by Andarist** [comment]
Go for it! If you need any help you can always reach to us at slack.
