### ISSUE TITLE
TypeScript 2.7 introduces the definite property assignment assertion operator (!)

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7157]
While I am actually enthusiastic, the `!` in the title actually has more to do with the syntax. TypeScript 2.7 permits a bang following any class property declaration.

```ts
class C {
  foo!: number;
  constructor() {
  }
}
```

The above is an example of such usage. It asserts that `foo` will be initialized even if it is not initialized within the constructor.

On the other hand, this is only allowed on class instance properties

```ts
class C {
  static foo!: number; // TypeScript errors: A definite assignment assertion '!' is not permitted in this context.
}
```

@andy-ms, can you take this on before the 7.0 release?

**Comment by hzoo** [comment]
Done with https://github.com/babel/babel/pull/7159?

**Comment by epeli** [comment]
Yeah it's good! 💪
