### ISSUE TITLE
transform-react-inline-elements throws on JSX fragments

### ISSUE THREAD

**Issue by mdebbar** [babel/babel#7165]
Choose one: is this a bug report or feature request? **bug report**

When using the `@babel/transform-react-inline-elements` plugin, it throws an exception when it encounters a JSX fragment (i.e. `<>...</>`).

### Input Code

```js
export default class MyFragComp extends React.Component {
  render() {
    return <><div /><span /></>;
  }
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  // ...
  "plugins": [ "@babel/transform-react-inline-elements" ]
}
```

### Expected Behavior

Transpilation should succeed with no errors.

### Current Behavior

Transpilation fails on JSX fragments.

### Possible Solution

Quick solution: Bail out on JSX fragments (will send a PR for this now).
Better solution: Optimize fragments the same way we optimize normal JSX tags.

### Context

I use this plugin for production builds. Suddenly, builds started failing and I found out that a jsx fragment was causing it.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.36
| Babylon          | 
| node             | 8.7.0
| npm              | 5.4.2
| Operating System | macOS Sierra 10.12.6

**Comment by Andarist** [comment]
While babel 7 is still in beta I'd say it would be better to just take more time and implement full solution of optimizing them, instead of bailing out tempprarily

**Comment by mdebbar** [comment]
@Andarist I agree. But at the moment, this plugin is unusable with fragments. A non-ideal solution is way better than a broken experience.

Also, I wouldn't be surprised if the bug remains open for a very long time, and no one has the time to implement the "proper" solution. So I would prefer to have the quick fix merged ASAP, and if a better solution is implemented later, that would be awesome!

**Comment by jorrit** [comment]
I am in favor of avoiding now and fixing later. What would be a proper optimization for fragments?

**Comment by mdebbar** [comment]
> avoiding now and fixing later

and leave everyone using Babel7 with a broken plugin? I would agree with you if there was already a plan for fixing it. But there's no plan now and nobody knows how long it will take to fix it.

The responsible thing to do IMHO is to unbreak the plugin so people can continue using it until someone figures out and implements the optimizations for fragments.

**Comment by jorrit** [comment]
@mdebbar I think I did not explain my position well enough. I think we're on the same side of the argument. I meant: _avoid_ the error for now using a workaround and _fix_ it with a proper implementation later.

**Comment by nicolo-ribaudo** [comment]
If you want I can look for a proper fix to this bug during the upcoming week.

**Comment by jorrit** [comment]
When looking at what `babelHelpers.jsx()` improves over `React.createElement()`, I think the transform-react-inline-elements does not need to support JSXFragments at all. According to [this source](https://medium.com/doctolib-engineering/improve-react-performance-with-babel-16f1becfaa25) the improvement is in the way props are handled. Fragments have no props and the `config` argument to `React.createElement()` is `null`, which skips the part of the code that is optimized.

See https://github.com/facebook/react/blob/65aeb701955521551848a8a9cc8e9f279ef2e73c/packages/react/src/ReactElement.js#L170

I think PR #7166 should be merged.

**Comment by nicolo-ribaudo** [comment]
cc @babel/react

**Comment by sophiebits** [comment]
Can we have it output `babelHelpers.jsx(React.Fragment, {}, void 0, ... children ...)`?

**Comment by jorrit** [comment]
I think passing `null` instead of `{}` as props is better becausr that triggers a faster path in the helper code.

**Comment by nicolo-ribaudo** [comment]
Would something like this work?
```js
// Input
<><Foo /><Bar /></>

// Output

_jsxFragment(null, [ <Foo/>, <Bar/> ]); // Foo and Bar should become _jsx(...)

function _jsxFragment(key, children) {
  return {
    $$type: REACT_FRAGMENT_TYPE,
    key: key,
    children: children.
  };
}
```

**Comment by jorrit** [comment]
I was thinking about a fragment-specific helper too. If something like this works in practice it would be great.

**Comment by nicolo-ribaudo** [comment]
> ```
> babelHelpers.jsx(React.Fragment, {}, void 0, ... children ...)
> ```

This isn't straightforward because `React.Fragment` is set by the `pragmaFrag` option of `babel-plugin-transform-react-jsx`, which runs _after_ `babel-plugin-transform-react-inline-elements`.

> Would something like this work?
> ```js
> // Input
> <><Foo /><Bar /></>
> 
> // Output
> 
> _jsxFragment(null, [ <Foo/>, <Bar/> ]); // Foo and Bar should become _jsx(...)
> 
> function _jsxFragment(key, children) {
>   return {
>     $$type: REACT_FRAGMENT_TYPE,
>     key: key,
>     children: children.
>   };
> }

I have tested and it doesn't (https://codepen.io/nicolo-ribaudo/pen/XVVEoJ).

@sophiebits Are `<>...</>` and `[ ... ]` equivalent? I'm having trouble in understanding it by myself from the react source :sweat_smile:
 e.g.
```js
// Input
<>
  <Foo />
  <Bar />
</>

// Output
[
  <Foo />,
  <Bar />
]
```

**Comment by mdebbar** [comment]
> Are `<>...</>` and `[ ... ]` equivalent?

I believe they are almost equivalent with one difference: the former doesn't require the `key` prop on each element. Worth double-checking with @sophiebits though.

**Comment by nicolo-ribaudo** [comment]
Since it is a static array, we can just use an incrementing index. e.g.
```js
// Input
<>
  <Foo />
  <Bar />
</>

// Output
[
  <Foo key={1} />,
  <Bar key={2} />
]
```

**Comment by bvaughn** [comment]
> Are `<>...</>` and `[ ... ]` equivalent?

@clemmy put together a Gist that you might find useful to glance at: https://gist.github.com/clemmy/b3ef00f9507909429d8aa0d3ee4f986b

**Comment by sophiebits** [comment]
They are not quite equivalent. Adding keys manually like that is also not correct.
