### ISSUE TITLE
Bug: Unnecessary Whitespace When Using @babel/plugin-external-helpers

### ISSUE THREAD

**Issue by julmot** [babel/babel#7167]
The following is generated at the top of a file when using `@babel/plugin-external-helpers`, even when specifying `compact: true` (note how many empty lines are generated):

```javascript

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
  return typeof obj;
} : function (obj) {
  return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
};











var classCallCheck = function (instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
};

var createClass = function () {
  function defineProperties(target, props) {
    for (var i = 0; i < props.length; i++) {
      var descriptor = props[i];
      descriptor.enumerable = descriptor.enumerable || false;
      descriptor.configurable = true;
      if ("value" in descriptor) descriptor.writable = true;
      Object.defineProperty(target, descriptor.key, descriptor);
    }
  }

  return function (Constructor, protoProps, staticProps) {
    if (protoProps) defineProperties(Constructor.prototype, protoProps);
    if (staticProps) defineProperties(Constructor, staticProps);
    return Constructor;
  };
}();








```

(Currently available here: https://github.com/julmot/mark.js/blob/67cabf70f6dda91d334fe1332c1512e20a5f7d61/dist/mark.js)

### Input Code

Doesn't matter.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
      compact: true,
      exclude: 'node_modules/**',
      presets: [
        ['env', {
          'modules': false
        }]
      ],
      plugins: [
        'external-helpers',
        'transform-object-assign'
      ]
}
```

### Expected Behavior
There should be max. one empty line for separation.

### Current Behavior
There are many empty lines, even in compact mode.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 6.11.3
| npm              | 3.10.10
| Operating System | Win 10

**Comment by nicolo-ribaudo** [comment]
That code is inserted by rollup, not by Babel. `external-helpers` only writes `import _typeof from "@babel/runtime/helpers/es6/_typeof.js"`, and than Rollup replaces the import with the content of the file.

If you don't want whitespaces in your bundle, I suggest using [rollup-plugin-babel-minify](https://github.com/Comandeer/rollup-plugin-babel-minify) or [rollup-plugin-uglify](https://github.com/TrySound/rollup-plugin-uglify).
