### ISSUE TITLE
Self-executing, anonymous async functions break following code

### ISSUE THREAD

**Issue by pentaphobe** [babel/babel#7172]
Bug report

### Input Code

Unless the anonymous self-executing function is followed by a semicolon, the next statement is compiled as an argument *to the result* of the first

[REPL link showing issue](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=PQKhCgAIUgVALAppAZgewDYbQdwJYB2A5pAC45qQaGIDOkFATgNao2QBGiAxgIYCutZGhRkkkIQFs83TGgJQQwcOAAUvWgE8C3SKoCUkALwA-SLxy88pSAAVGaaUIB0jOpgBuiVQHIc8XlJEL0YffX0DAG4VdS0dPUNTSFkCWkxEZ2widUtrOwcnDLc0jC9ff0DgxFDwyAj9FRVQCGg4cXQsXEISckpqAjpoABNKAjRSGCZWFBoAGnMCIYkeeSXaUkrJRAIbRUg8ekIgxgAHNyCljQXzRiJ-LZ2ySlJ2vEZ1xWU1DW1dA2MzBYrDZ7I4DkV3KVvH4AkEQmF6jEfvF_kkUiUMlkcsD8mCXMVPNCKnDqgi6gYVEA&debug=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=6.26.0)

```js
/**
 * The following two lines work fine because of the semicolon
 */

(async () => await Promise.resolve('whatever'))();

(async () => console.log(await Promise.resolve('whatever')) )()

```

```js
/**
 * The following two lines *do not* work fine, and second statement 
 * is interpreted as an argument to the first
 */

(async () => await Promise.resolve('whatever'))()

(async () => console.log(await Promise.resolve('whatever')) )()

```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

Configurations are all default on REPL: `es2015`, `stage-2`, `react`

### Expected Behavior

Both snippets should produce identical output

### Current Behavior

First statement breaks second statement, compiler reports `_asyncToGenerator(...)(...) is not a function`

### Possible Solution

*May* be related to #5032

### Context

This emerged on client work, hence the simplified example herein

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 
| npm              | 
| Operating System | Mac, but reproducible in babeljs.io REPL

**Comment by nicolo-ribaudo** [comment]
Babel is correct: you can test it by pasting this code in you browser's console:
```js
(() => 'whatever')()

(() => 'whatever')()
```

**Comment by pentaphobe** [comment]
Good catch, @nicolo-ribaudo - thanks

This actually occurred to me after the fact - but we've gotten so used to no-semicolon style that it had a few of us scratching our heads!


Sorry for erroneous bug report

**Comment by nicolo-ribaudo** [comment]
When you use a no-semicolon style, I suggest to always insert `;` at the start of lines whose first character is one of `([+-`, to avoid this kind of bugs. e.g.
```js
var a = 2
console.log(a)
;(() => console.log(a))()
```

**Comment by pentaphobe** [comment]
That's a nice workaround, thanks @nicolo-ribaudo - still gives flashbacks to 2012, but it's the lesser of a few evils 👍

**Comment by Andarist** [comment]
Id suggest using prettier which will insert those automatically when needed or at least use eslint to warn u about such lines

**Comment by pentaphobe** [comment]
@Andarist embarrassingly, we actually use both of these tools in our build environment - but this emerged when we were prototyping a code snippet in an online editor

Thanks for the tip though!
