### ISSUE TITLE
[TS] Add support for "type cast and assign"

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#7175]
```js
(<number> foo) = 0;
```
---
https://github.com/babel/babel/pull/7098 can be used as an example of what needs to be done.

**Comment by joaomcarvalho** [comment]
Is that a good first issue @nicolo-ribaudo ? I would like to help. Do you think you can point me a starting point?

**Comment by nicolo-ribaudo** [comment]
Here are the parts of Babylon (Babel's parser) which check the left node of an assignment expression:
- In the `parseAssignmentExpression`, you can see that there is a call to the `checkLVal` method.
 https://github.com/babel/babel/blob/5f8a1a2613eccc81a2b06e5758b003ce830f0171/packages/babylon/src/parser/expression.js#L162
 It is defined in https://github.com/babel/babel/blob/master/packages/babylon/src/parser/lval.js.
- `checkLval` checks that the left node is a node that can be assigned to.
  e.g. in `(<Type> NODE)` it should `checkLVal` `NODE`.

Since the typescript grammar is defined as an internal Babylon plugin, that methods shouldn't be modified directly, but it should be overwritten in https://github.com/babel/babel/blob/master/packages/babylon/src/plugins/typescript.js to work with `TSTypeAssertion`

#7098 fixes a bug very similar to this one, so I'd suggest looking at that PR!

If you need any additional help, feel free to contact me on [slack](https://slack.babeljs.io/)
