### ISSUE TITLE
ERROR in runtime.js, Module not found: Error: Can't resolve 'imports' when using @babel/polyfill or runtime

### ISSUE THREAD

**Issue by pathsny** [babel/babel#7190]
Issue: Bug Report

When attempting to use @babel/polyfill or @babel/runtime the compiler throws the following error
ERROR in ./node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js
Module not found: Error: Can't resolve 'imports' in '/project_path/node_modules/@babel/polyfill/node_modules/regenerator-runtime'

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
Please see attached here https://gist.github.com/pathsny/af270f61390380c8d948973ed9e09787
my .babelrc, package.json, package-lock.json, and webpack.config.js

### Input Code
In the above gist, either uncommenting the line with the async function inside the file "offending file" or uncommenting the entry @babel/polyfill in the webpack.config.js and then running

```bash
NODE_ENV=development webpack-dev-server --color --hide-modules
clean-webpack-plugin: /project/build has been removed.
Project is running at http://0.0.0.0:9494/
webpack output is served from http://0.0.0.0:9494/build/
Content not from webpack is served from /project/build
404s will fallback to /index.html
   899 modules

ERROR in ./node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js
Module not found: Error: Can't resolve 'imports' in '/project_path/node_modules/@babel/polyfill/node_modules/regenerator-runtime'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'imports-loader' instead of 'imports',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
webpack: Failed to compile.
```
The same is seen when using webpack -p

### Expected Behavior
It should build correctly (or report an actionable error if something is wrong in my config)

### Current Behavior
it does not compile :(

### Context
Use polyfills and/or async functions

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  ^7.0.0-beta.36 
| Babylon          | 
| node             | 9.3.0
| npm              | 5.6.0
| Operating System | OSX 10.12.6

**Comment by rajzshkr** [comment]
First thing, change @babel/react -> @babel/preset-react in .babelrc

**Comment by pathsny** [comment]
Found the root cause here. Closing this out here https://stackoverflow.com/questions/48182990/module-not-found-error-cant-resolve-imports-when-using-babel-polyfill-or
