### ISSUE TITLE
es2015 preset doesn't pick up *.mjs per default and there is no warning/explanation either

### ISSUE THREAD

**Issue by JonasT** [babel/babel#7198]
Please note I'm an absolute utter beginner, so treat this ticket more as a kind of usability feedback that might not make too much sense.

I noticed that es2015 preset of babel doesn't make it pick up *.mjs per default and there is no warning/explanation either.

I think this should be changed: .mjs seems to be the default extension for es6 modules, and compiling es6 modules away to older javascript implementations seems to be a common task, hence I would expect `./node_modules/.bin/babel src -d lib --presets=es2015` to either pick up on *.mjs modules and translate them, or give me some hint on why it doesn't want to do so.

**Comment by nicolo-ribaudo** [comment]
I think it works in Babel 7. Which version are you using?

**Comment by xtuc** [comment]
According to https://github.com/babel/babel/pull/5624, yes it's in Babel 7.
