### ISSUE TITLE
Requiring es6 node modules

### ISSUE THREAD

**Issue by ajacksified** [babel/babel#72]
re: https://github.com/sebmck/6to5/blob/master/lib/6to5/register.js#L11-13

If I write a module using es6, I can't import it from another node project (using es6 or otherwise) unless I remove these lines or if I include the compiled source in the module, which doesn't always happen cleanly.

Coffeescript uses special file extensions (`.coffee`, like your `.es6`) that solve this problem. To make it easy to require es6 modules, I propose either:
- _Only_ allow requires to work on .es6, like coffeescript, and allow to run on node-modules;
- Have `register` return a function that accepts options, so I can define a regex (or file extension, or both) for files that should be compiled.

I can make a PR if you think this is a good idea.

**Comment by chrisabrams** [comment]
For anyone who comes across this issue, here are the updated options for `6to5/register`: https://6to5.org/docs/usage/require/
