### ISSUE TITLE
Argument named `args` breaks the transpilation, but if is renamed to `x` works

### ISSUE THREAD

**Issue by hackhat** [babel/babel#7203]
Source code:
```js
  setState = (state, fn) => {
    super.setState(state, (...args) => {
      fn(...args)
    });
  };
```

transpiles to:

```js
  this.setState = function (state, fn) {
    super.setState(state, function () {
      fn.apply(undefined, arguments);
    });
  };
```

with error `Uncaught SyntaxError: 'super' keyword unexpected here`.

Looks like if you access the `...args` it breaks the transpiler somehow.

If I change the argument `args` to `x` works:

```js
  setState = (state, fn) => {
    super.setState(state, (...x) => {
      fn(...x);
    });
  };
```

Strange but somehow the variable name affects the code. Is there any way to see the transpiled code? I only able to see the `eval` string. I was able to see the code after eval, but only once and I'm not able to do it again.

I'm using:

 - https://github.com/react-boilerplate/react-boilerplate
 - babel-core @ 6.24.1
 - babel-cli @ 6.26.0

**Comment by jridgewell** [comment]
This was fixed some time in Babel 7.
