### ISSUE TITLE
babel-node throws "Error: Plugin/Preset files are not allowed to export objects, only functions."

### ISSUE THREAD

**Issue by karlas** [babel/babel#7204]
By using 

`babel-node --presets=@babel/env scripts/index.js`

or

`babel-node --presets @babel/env scripts/index.js`

or

`babel-node scripts/index.js`

This error always appears.

All babel packages installed on my devDependencies:

`    
"@babel/cli": "7.0.0-beta.37",
 "@babel/core": "7.0.0-beta.37",
 "@babel/node": "^7.0.0-beta.37",
 "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.37",
 "@babel/preset-env": "7.0.0-beta.37"
`

**Comment by loganfsmyth** [comment]
Including the full error output would be a big help. It sounds like you probably have a `.babelrc` file in it with bad configuration, so please also include that.

**Comment by karlas** [comment]
Indeed, it was a an error with .babelrc (it was placed on the wrong path).

Sorry, and thanks for your time
