### ISSUE TITLE
Rename babel-* folder in packages/

### ISSUE THREAD

**Issue by xtuc** [babel/babel#7209]
We could remove the `babel` prefix from all the folder in `packages/`, since we use the scoped packages everywhere it looks a bit redundant. Also that will be more consistent with Babylon.

**Comment by rajzshkr** [comment]
This is not just rename, also we have to change in file level.
1. scripts/gulp-tasks.js
2. scripts/generate-interfaces.js
3. scripts/generate-babel-types-docs.js
4. Makefile

**Comment by hzoo** [comment]
I'd rather not focus on this given the work required

**Comment by xtuc** [comment]
Closing, out of scope for now.
