### ISSUE TITLE
`export default @bar class Foo { }` doesn't generate ClassDeclaration

### ISSUE THREAD

**Issue by mysticatea** [babel/babel#7223]
Choose one: is this a bug report or feature request?

A bug report.

### Input Code; Babel/Babylon Configuration (.babelrc, package.json, cli command)

This test: https://github.com/babel/babel/tree/64dfb7574e924be3ad737c33cbc81d619dbc14c6/packages/babylon/test/fixtures/experimental/decorators-2/export-default-decorated-class

### Expected Behavior

Babylon generates `ClassDeclaration` node.

### Current Behavior

Babylon generates `ClassExpression` node.

### Possible Solution

Modifies this condition: https://github.com/babel/babel/blob/64dfb7574e924be3ad737c33cbc81d619dbc14c6/packages/babylon/src/parser/statement.js#L1369

### Context

To fix https://github.com/babel/babel-eslint/issues/567.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  master
| Babylon          | master
| node             | 9.2.0
| npm              | 5.6.0
| Operating System | Windows 7

**Comment by Kovensky** [comment]
https://github.com/babel/babel/pull/7189 fixes this

**Comment by mysticatea** [comment]
Oh sorry. I had not found it via https://github.com/babel/babel/issues?q=is%3Aissue+ClassExpression
