### ISSUE TITLE
The plugin "dynamic-import-webpack" didn't export a Plugin instance

### ISSUE THREAD

**Issue by kjda** [babel/babel#7224]
getting 

> Module build failed: TypeError: The plugin "dynamic-import-webpack" didn't export a Plugin instance

.babelrc
```
{
	"plugins": ["dynamic-import-webpack"],
	"optional": ["es7.decorators", "es7.classProperties", "es7.objectRestSpread"]
}
```

dependencies:
```
"babel-core": "^6.26.0",  
"babel-loader": "^7.1.2",  
"babel-plugin-syntax-dynamic-import": "^6.18.0",  
"webpack": "^3.10.0",  
```

**Comment by nicolo-ribaudo** [comment]
1) `dynamic-import-webpack` version?
2) `optional` was removed in Babel 6, you should use plugins.

**Comment by nicolo-ribaudo** [comment]
Also, webpack handles `import()`s, so you don't need to transform it.

**Comment by kjda** [comment]
thank you @nicolo-ribaudo yes, i'm trying to upgrade to B6 to make this work, 
`dynamic-import-webpack` the same error

if I don't use transform i get the following error 
> Module build failed: SyntaxError: ... Unexpected token

pointing to the line where I used import

**Comment by kjda** [comment]
I was reading that this error shows up when one uses a B6 module with B5, but I'm sure I'm using B6

**Comment by TrySound** [comment]
@kjda You need to enable it with `babel-plugin-syntax-dynamic-import`.

**Comment by kjda** [comment]
@TrySound Module build failed: TypeError: The plugin "babel-plugin-syntax-dynamic-import" didn't export a Plugin instance

**Comment by TrySound** [comment]
Show babel config

**Comment by kjda** [comment]
.babelrc
```
{
	"plugins": ["babel-plugin-syntax-dynamic-import"]
}
```

**Comment by nicolo-ribaudo** [comment]
@kjda Have you resolved this problem on Slack? Can this issue be closed?
