### ISSUE TITLE
[babel-preset-env] Missing Object.assign transform

### ISSUE THREAD

**Issue by raphaelokon** [babel/babel#7228]
### Input Code

```js
const meow = Object.assign(
  {foo: 1}, 
  {bar: 2}
);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
The `.babelrc` config

```js
{
	"presets": [
		["@babel/preset-env", {
			"targets": {
				"browsers": ["last 2 versions", "ie >= 10"]
			},
			"modules": false

		}]
	],
	"plugins": [
		"@babel/external-helpers"
	]
}
```

### Expected Behavior
I expect the Object.assign to be poly filled/transformed when applying the preset-env

### Current Behavior
Everything else is well transformed, but `Object.assign` is kept untouched thus breaking one of the env targets `ie >= 10` yielding the following code:

```js
'use strict';

var meow = Object.assign(
  {foo: 1}, 
  {bar: 2}
);
```

### Possible Solution
Include `@babel/plugin-transform-object-assign`

**Comment by rajzshkr** [comment]
Can you mention the IE version?

**Comment by existentialism** [comment]
Object.assign must be polyfilled, since it's a built-in.

You can use the `useBuiltIns: entry` option with `babel-polyfill`, or `useBuiltIns: usage`.

**Comment by raphaelokon** [comment]
@existentialism Ah thanks! This was the missing bit.
