### ISSUE TITLE
Babel-polyfill adds recursive property to Window object

### ISSUE THREAD

**Issue by index23** [babel/babel#7232]
When I build my code with babel-polyfill imported, babel-poliyfill adds property `global` to `Window` object which consists `Window` object itself which further consists itself again and so on into infinite loop. I have just added babel-polyfill to entry in webpack configuration:

`entry: ["babel-polyfill", "../main.js"]`

Is this regular behavior?

I have notice that on Chrome 63.0.3239.132 and Firefox 57.0.3. on Windows 10 and Mac OS X.

**Comment by loganfsmyth** [comment]
That is generally expected, though it is possible `global` will be removed in the future. The fact that it is self-referential however is definitely a non-issue. There are many existing places where that is also the case. That `window.self === window` for instance.

**Comment by index23** [comment]
Thanks for quick response.
