### ISSUE TITLE
Flow property declarations are not removed

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#7233]
### Input Code

https://github.com/babel/babel/blob/master/packages/babylon/src/parser/lval.js

```js
export default class LValParser extends NodeUtils {
  // Forward-declaration: defined in expression.js
  +checkReservedWord: (
    word: string,
    startLoc: number,
    checkKeywords: boolean,
    isBinding: boolean,
  ) => void;
  +parseIdentifier: (liberal?: boolean) => Identifier;
  +parseMaybeAssign: (
    noIn?: ?boolean,
    refShorthandDefaultPos?: ?Pos,
    afterLeftParse?: Function,
    refNeedsArrowPos?: ?Pos,
  ) => Expression;
  +parseObj: <T: ObjectPattern | ObjectExpression>(
    isPattern: boolean,
    refShorthandDefaultPos?: ?Pos,
  ) => T;
  // Forward-declaration: defined in statement.js
  +parseDecorator: () => Decorator;

  // ...
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

https://github.com/babel/babel/blob/master/.babelrc.js

```js
const config = {
  comments: false,
  presets: [
    ["@babel/env", envOpts],
    "@babel/flow"
  ],
  plugins: [
    ["@babel/proposal-class-properties", { loose: true }],
    "@babel/proposal-export-namespace-from",
    "@babel/proposal-numeric-separator",
    ["@babel/proposal-object-rest-spread", { useBuiltIns: true }],
  ]
};
```

### Expected Behavior

```js
function LValParser() {
  return _NodeUtils.apply(this, arguments) || this;
}
```

### Current Behavior

```js
function LValParser() {
  var _temp, _this;

  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }

  return (
    ((_temp = _this =
      _NodeUtils.call.apply(_NodeUtils, [this].concat(args)) || this),
    (_this.checkReservedWord = void 0),
    (_this.parseIdentifier = void 0),
    (_this.parseMaybeAssign = void 0),
    (_this.parseObj = void 0),
    (_this.parseDecorator = void 0),
    _temp) || _assertThisInitialized(_this)
  );
}
```

### Context

I was trying to build Babylon with gulp

**Comment by nicolo-ribaudo** [comment]
Probably this is a plugin ordering issue, since `flow-strip-types` should run before `class-properties`

**Comment by nveenjain** [comment]
Is this a good first issue in context of flow? As i'm new to flow, i would love to learn that while solving this PR.

**Comment by nicolo-ribaudo** [comment]
Actually this is a bit more complex, since the real fix is plug-in ordering (https://github.com/babel/babel/pull/5735)

**Comment by malectro** [comment]
Looks like you can solve this by using the `@babel/plugin-transform-flow-strip-types` plugin instead of the preset. Not ideal, but fairly easy to switch.

**Comment by psychobolt** [comment]
I have the same issue as @dlebedynskyi . Reordering plugins does not work. 

.babelrc plugin order:
```
"plugins": [
    "transform-flow-strip-types",
    ["lodash", {"id": ["lodash", "recompose"]}]
]
```

Babel plugins, package.json:

    "babel-core": "^6.26.0",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-preset-env": "^1.6.1",

**Comment by malectro** [comment]
@dlebedynskyi @psychobolt here's my setup
`.babelrc.js`
```js
module.exports = {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              browsers: [
                'last 2 Chrome versions',
                'last 2 Safari versions',
                'last 2 Firefox versions',
                'last 2 Edge versions',
              ],
            },
            useBuiltins: 'entry',
            modules: false,
            debug: false,
          },
        ],
        '@babel/preset-react',
      ],
      plugins: [
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-transform-flow-strip-types',
        ['@babel/plugin-proposal-class-properties', {loose: true}],
        '@babel/plugin-transform-exponentiation-operator',
      ],
    };
```

**Comment by dlebedynskyi** [comment]
@malectro You set up looks fine. and it seem to work fine.  I think issue is related to babel-plugin-lodash conflicting with `@babel/plugin-transform-flow-strip-types`

**Comment by jeremejevs** [comment]
In case of Lodash, I don't think Babel is at fault. See https://github.com/lodash/babel-plugin-lodash/issues/215.

**Comment by malectro** [comment]
in light of babel7 being released, are we safe to use `@babel/preset-flow`? it still doesn't seem to be working for me, but i'm worried my setup is bad

**Comment by sepehr** [comment]
> _"in light of babel7 being released, are we safe to use `@babel/preset-flow`? it still doesn't seem to be working for me, but i'm worried my setup is bad" — @malectro_ 

Doesn't work for me either.

**Comment by armano2** [comment]
This issue no longer affects babel@7.13.7 as types reported in ticket are correctly striped now when flow present on plugin is used [REPL](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=usage&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAMgGqqYAKqUBwUcoMwAdgsQHIRICqMAS0zEA3gCg4cAPRS4AMWgB3WggC0SPLVSCIrAFyIUA1sARxjTcFGBEBugHQArAhLgBqHAAtgOANYAlGwYAN1MAdWgEAwAKV0lFSIMCGChjAHMAGji4ZNoYEggcA1Z0AFsAIwYsyUkvH18AaWAATwSoDgNyiAhMYFRWapqBAgAhYwR0zu7e_sGASjgAXgA-OGCIAQQAblc3MFp6AEkkVkFkAQYYzAFKqEoAfimevtYFlbhjtjOLqB3JPYOwAAsqhmpUAIK2NL6OCxGpwVgQQ6sR5we5dZ6zbLWZAAZU80Bgnn6CAAIigMNgqBACKj7tSCINJKhkCwoCQUDAaHRgKi5OhWDgdANsShOMBTARwVAoBBFAy6Qz5ktVgBRKw2Ah2Vh_dz7HkAeXKjgMAB4ACoGI2OHxc7Rs1hwAA-cGttvVYGstl0yzhQwINBgDqeMxF8Jx-MJxPY5LQWC5NMVNOV73Nupk8iUKnUPnwd2FBiQ5xMZgsuRYpS-Thc_319HJOGg2mgMTeqwbTZg0B2AF8gA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=false&presets=env%2Cflow&prettier=false&targets=&version=7.13.7&externalPlugins=)
