### ISSUE TITLE
[babel-preset-react] Bug: arrow function in ternary operator causes syntax error

### ISSUE THREAD

**Issue by uber5001** [babel/babel#7234]
Using an arrow function inside of a ternary operator can cause a syntax error in `babel-preset-react` if parenthesis are not placed well. However, all other presets (and no preset!) will parse such a scenario jsut fine.

[There's a related question on Stackoverflow](https://stackoverflow.com/questions/48309694/why-cant-i-use-a-ternary-operator-and-arrow-function-in-this-way-in-jsx)

### Input Code

The following case [**fails** to compile with `babel-preset-react`](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=C4JwrgpgBA_FAUAiYEDOxEEooC4oA8oBeAPigBYAmIA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact&prettier=false&targets=Electron-0.3%252CNode-7.4&version=6.26.0) but [works without it](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=C4JwrgpgBA_FAUAiYEDOxEEooC4oA8oBeAPigBYAmIA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=Electron-0.3%252CNode-7.4&version=6.26.0)

```js
    true ? ("test") : x => 42    // This is the problem. This fails, but only on babel-preset-react
```

If parenthesis are _removed_, it works both [with](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=C4JwrgpgBA_FBEwIGdjygLigDygXgD4oAWAJiA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact&prettier=false&targets=Electron-0.3%252CNode-7.4&version=6.26.0) and [without](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=C4JwrgpgBA_FBEwIGdjygLigDygXgD4oAWAJiA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=Electron-0.3%252CNode-7.4&version=6.26.0) `babel-preset-react`:

```js
    true ? "test" : x => 42
```

If parenthesis are _added_, it works both [with](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=C4JwrgpgBA_FAUAiYEDOxEEooC4EA8oBeAPigBYAmTIA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact&prettier=false&targets=Electron-0.3%252CNode-7.4&version=6.26.0) and [without](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=C4JwrgpgBA_FAUAiYEDOxEEooC4EA8oBeAPigBYAmTIA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=Electron-0.3%252CNode-7.4&version=6.26.0) `babel-preset-react`:

```js
    true ? ("test") : (x => 42)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

.babelrc :

```js
{
  "presets": ["react"]
}
```

### Expected Behavior

Each listed above should either:

- successfully compile with AND without `babel-preset-react`
- fail to compile with AND without `babel-preset-react`

### Current Behavior

The case `true ? ("test") : x => 42`:

- successfully compiles without `babel-preset-react`
- **fails** to compile **with `babel-preset-react`**

### Possible Solution

I can only assume that everything after `?` and before `=>` (in other words: `("test") : x`) is being interpreted as the parameters part of the arrow function. I don't know how to fix this.

### Context

This tripped me up when changing from webpack's default js compilation to `babel-preset-react`'s compilation when attempting to add React to an existing project. I had to make a few small changes to get my project to work again.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v6.23.0 (and v6.26.0 on the online repl)
| node             | v9.2.0
| npm              | 5.5.1
| Operating System | Windows 10

**Comment by nicolo-ribaudo** [comment]
This bug has been fixed in Babel 7 :slightly_smiling_face: 

https://babeljs.io/repl/build/master#?babili=false&browsers=chrome%20%3E%2054%20%20&build=&builtIns=false&code_lz=C4JwrgpgBA_FAUAiYEDOxEEooC4oA8oBeAPigBYAmIA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Cflow&prettier=false&targets=&version=7.0.0-beta.38

**Comment by uber5001** [comment]
@nicolo-ribaudo Thanks for the quick response!

It seems that the issue has, uh, moved. If you [use the typescript preset in the repl](https://babeljs.io/repl/build/master#?babili=false&browsers=chrome%20%3E%2054%20%20&build=&builtIns=false&code_lz=C4JwrgpgBA_FAUAiYEDOxEEooC4oA8oBeAPigBYAmIA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Ctypescript&prettier=false&targets=&version=7.0.0-beta.38) instead of react, the issue is back. I'm guessing this is known, and possibly expected behavior?

**Comment by nicolo-ribaudo** [comment]
Ugh, can you open a new issue about it?

**Comment by uber5001** [comment]
Can do.
