### ISSUE TITLE
Code placement within file affects generation of runtime methods

### ISSUE THREAD

**Issue by lscspirit** [babel/babel#7251]
I have two pieces of logically identical code below with differences only in the order of class definitions. However, that resulted in two different ways being used to define the `defineProperty` method in the compiled output. 

**Version 1** compiled into:
  `import _Object$defineProperty from "babel-runtime/core-js/object/define-property";` 

**Version 2** compiled into:
  `var _defineProperty = require("babel-runtime/core-js/object/define-property");`

### Input Code

**Version 1**
```js
"use strict";

class Test2 {}
class Test1 {
  async test() {}
}
```

**Version 2**
```js
"use strict";

class Test1 {
  async test() {}
}
class Test2 {}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets": ["env", "stage-2"],
  "plugins": [
    ["transform-runtime", {
      "helpers": false,
      "polyfill": true,
      "moduleName": "babel-runtime"
    }]
  ]
}
```

### Expected Behavior

The two different versions of the code here should be compiled in the same way. 

### Current Behavior

Compiled **Version 1**
```js
"use strict";

import _Object$defineProperty from "babel-runtime/core-js/object/define-property";

var _promise = require("babel-runtime/core-js/promise");
var _promise2 = _interopRequireDefault(_promise);
var _regenerator = require("babel-runtime/regenerator");
var _regenerator2 = _interopRequireDefault(_regenerator);

/* ... skipping the rest of the file */
```

Compiled **Version 2**
```js
"use strict";

var _promise = require("babel-runtime/core-js/promise");
var _promise2 = _interopRequireDefault(_promise);
var _defineProperty = require("babel-runtime/core-js/object/define-property");
var _defineProperty2 = _interopRequireDefault(_defineProperty);
var _regenerator = require("babel-runtime/regenerator");
var _regenerator2 = _interopRequireDefault(_regenerator);

/* ... skipping the rest of the file */
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             |  6.10.3
| npm              | 3.10.10
| Operating System | macOS 10.12.6

**Comment by loganfsmyth** [comment]
Not an exact duplicate, but this is likely the same core issue as https://github.com/babel/babel/issues/2877, which is fixed in Babel 7's beta.
