### ISSUE TITLE
[babylon] async arrow functions with rest params with typescript type annotation causes SyntaxError

### ISSUE THREAD

**Issue by cameron-martin** [babel/babel#7253]
Choose one: is this a bug report or feature request? Bug report.

### Input Code

https://astexplorer.net/#/gist/948cebd2ff64c4f3bdf6c5f839a6aac6/56567f051e14f81dcccdc17c238bdaf1a5838852

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
Configuration in above url.

### Expected Behavior
The above code should parse.

### Current Behavior
The above code does not parse.

### Context
Trying to compile typescript files using babel.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.38
| Babylon          | 7.0.0-beta.38
| node             | 8.6.0
| npm              | 5.3.0
| Operating System | Windows 10

**Comment by ksashikumar** [comment]
I will work on this bug.
