### ISSUE TITLE
BrowserslistError: Unknown browser query 'last 1 years'

### ISSUE THREAD

**Issue by ipsips** [babel/babel#7260]
While the documentation clearly states:

> you can use any valid query format supported by browserslist.

I get the error `Module build failed: BrowserslistError: Unknown browser query 'last 1 years'`

### Input Code
My `.browserslistrc` file contains:
```
last 1 year
IE >= 11
```

**Comment by nicolo-ribaudo** [comment]
It was introduced in BrowserList v.2.11 (https://github.com/ai/browserslist/blob/master/CHANGELOG.md#211), which is supported: https://github.com/babel/babel/blob/180eda3211faa855654757bc44aeaf3961a8be05/packages/babel-preset-env/package.json#L49

You should update your `node_modules` folder.

**Comment by qm3ster** [comment]
@nicolo-ribaudo it's still happening to me :o
```
yarn list --pattern browserslist
yarn list v1.3.2
├─ @babel/preset-env@7.0.0-beta.38
│  └─ browserslist@2.11.3
├─ autoprefixer@7.2.5
│  └─ browserslist@2.11.3
└─ browserslist@1.7.7
```

**Comment by qm3ster** [comment]
Now, this is bizarre!
```
"browserslist": [">2%", "not <0.5%"]
```
results in
```
BrowserslistError: Unknown browser query `<0.5%`
```

**Comment by qm3ster** [comment]
Basically, it works in `.browserslistrc`, in tools and `browserslist` cli tool, but not anywhere in the js api, including node REPL and putting it in `package.json` instead of `.browserslistrc`
