### ISSUE TITLE
Make the babel instance configurable in babel-register

### ISSUE THREAD

**Issue by Janpot** [babel/babel#7263]
The version of babel that is bundled with `babel-register` might not always be the same one as the one I want to register 
like in [this thread](https://github.com/kentcdodds/babel-plugin-macros/issues/48#issuecomment-359734120): a dependency (a babel plugin) wants to load modules of the dependant with the babel version of the dependant.

I propose to make it configurable like for instance

```js
require('babel/register')({ babel: babelFromSomewhereElse });
```

I wouldn't mind making a PR for something like this if you agree.

**Comment by Andarist** [comment]
This would require some refactoring, as `@babel/register` is effectful module. To preserve old API and provide a new option it would have to be imported from other directory (i.e `@babel/register/custom`).

**Comment by Janpot** [comment]
@Andarist I might not think of all intricacies involved, but to me it seems like it's sufficient to plumb a babel through the options and select it [here](https://github.com/babel/babel/blob/63d9998aa45387af1216e3514598b54120fc4f1c/packages/babel-register/src/node.js#L51) instead of using the imported babel:

```js
import babelCore from '@babel/core';

// ...

// inside compile()
const babel = opts.babel || babelCore
```

Wouldn't that be backwards compatible? I can make a PR for that if the babel team agrees.

**Comment by Andarist** [comment]
Oh yeah, it might very well be that easy. Was looking quickly at the source code and thought that [`register`](https://github.com/babel/babel/blob/63d9998aa45387af1216e3514598b54120fc4f1c/packages/babel-register/src/node.js#L96) is more tied to to babel's instance. 

> I might not think of all intricacies involved,

Me neither 😅 You can start a PR to get ball rolling faster.
