### ISSUE TITLE
[babel 7] class.method(arg = this.something) becomes: arg = undefined.something

### ISSUE THREAD

**Issue by drcmda** [babel/babel#7264]
Choose one: is this a bug report or feature request?

bug

<img width="806" alt="screen shot 2018-01-23 at 20 56 08" src="https://user-images.githubusercontent.com/2223602/35297629-dd8409c6-007f-11e8-8a10-00b40e1cadfc.png">

It seems to transpile `this` in args to `undefined`, but only if an import is made above it. I tried several, always crashes, if i remove the import, it's fine again ... 

### Input Code

```js
import React from 'react'

class A {
    constructor() {
        this.bla = 1
    }
    heck(bla = this.bla) {
        console.log(bla)
    }
}

const a = new A()
a.heck()
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
const options = {
    babelrc: false,
    cacheDirectory: true,
    presets: [
        ['@babel/preset-env', { modules: false, loose: true, targets: { chrome: 60 } }],
        '@babel/preset-stage-0',
        '@babel/preset-react',
    ],
    plugins: [
        '@babel/plugin-proposal-decorators',
    ],
}
```

PS. There seems to be a problem with plugin-proposal-decorators as well, without it yields:

```
Module build failed: Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.38
| Babylon          | 
| node             | 9.4.0
| npm              | 5.6.0
| Operating System | MacOS high sierra

**Comment by Andarist** [comment]
Could u run `node` in ur project and execute this code?
```js
var res = require('@babel/core').transform(`

import React from 'react'

class A {
    constructor() {
        this.bla = 1
    }
    heck(bla = this.bla) {
        console.log(bla)
    }
}

const a = new A()
a.heck()

`, { 
  presets: [
    ['@babel/preset-env', { modules: false, loose: true, targets: { chrome: 60 } }],
    '@babel/preset-stage-0',
    '@babel/preset-react',
  ],
  plugins: [
    '@babel/plugin-proposal-decorators',
  ]
});
res.code
```

Would be helpful to see a result, Im suspecting this might a webpack issue - would be great to rule this out (or confirm).

**Comment by drcmda** [comment]
Returned:

```
'import React from \'react\';\n\nclass A {\n  constructor() {\n    this.bla = 1;\n  }\n\n  heck(bla = this.bla) {\n    console.log(bla);\n  }\n\n}\n\nconst a = new A();\na.heck();'
```

Do you have any idea how webpack (4) could have done this? I thought it's never going to touch code like that ...

**Comment by Andarist** [comment]
@drcmda according to [latest announcement](https://github.com/webpack/webpack/issues/6357) webpack:
> [new] this is now undefined in ESM

I suspect that webpack thought that `this` was referring here to "top level", but actually it refers to the class' instance. You can file a bug issue on their boards.

**Comment by Andarist** [comment]
I see you have started rolling ball on webpack's board - going to close this issue then.

**Comment by drcmda** [comment]
@Andarist thanks for your help!
