### ISSUE TITLE
Ensure that plugins throw helpful errors if used on versions of Babel that they do not support

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7265]
Feedback on various options would be appreciated!

Issues like https://github.com/babel/babel/issues/7110 are tripping up users pretty often, so making the transition from 6 to 7 smoother for users should be considered a blocker for the release of 7.x.

I think there are a bunch of ways to approach this. The simplest being that we literally go through each plugin and change

```
export default function(api, options){
  const { loose } = options; // or whatever options the plugin has
```
to

```
export default function(api, options){
  if (!/^7\./.test(api.version))) {
    throw new Error(
      `This plugin requires Babel 7 and appears to be running on version ${api.version}`,
    );
  }
  const { loose } = options; // or whatever options the plugin has
```

Obviously the downside here would be having to copy-paste this between modules. It also means we'll still throw when `options` is `undefined` on early versions of the 7.x beta, though that may be acceptable.

Alternatively a more complex solution might be more like

```
import declare from "babel-helper-plugin-utils";

export default declare((api, options) => {
  const { loose } = options; // or whatever options the plugin has
```
with `declare` wrapping the logic encapsulated above like as
```
function declare(handler) {
  return (api, options, dirname) => {
    if (!/^7\./.test(api.version))) {
      throw new Error(
        `This plugin requires Babel 7 and appears to be running on version ${api.version}`,
      );
    }
    return handler(api, options, dirname);
  };
}
```

The downsides here being that if we publicize this pattern, then `babel-helper-plugin-utils` ends up hard-coding the current stable version of Babel, and third-party plugins using this would potentially be locking themselves to version 7 if we eventually release a version 8.x that still supports plugins that work on 6 and 7, which seems likely to happen.

So then my question is, should we consider something like

```
import declare from "babel-helper-plugin-utils";

export default declare((api, options) => {
  api.assertVersion("^7.0.0-0");
  const { loose } = options; // or whatever options the plugin has
```
with `declare` wrapping the logic encapsulated above like as
```
function declare(handler) {
  return (api, options, dirname) => {
    if (!api.assertVersion)
      api = {
        ...api,
        assertVersion(version) {
          throw new Error(
            `This plugin requires at least Babel ${version} and appears to be running on version ${api.version}.`,
          );
        },
      };
    }
    return handler(api, options, dirname);
  };
}
```
and `babel-core` itself exposing an `assertVersion` function that uses semver to check a value vs its own version. I propose that as opposed to having `semver` a dependency of the helper itself so that if people don't want to use the helper, they still have access to the API, just with fewer guarantees and helpful warnings. It also means `npm` will have to do less work deduplicating packages, and ideally we have a goal of keeping the helper utils module as small as possible.

Personally I like the approach the most because it gives us a base to build on if we want to add functionality to the API, while still offering useful errors when plugins access things that they don't support.

**Comment by Andarist** [comment]
There is also an option of specifying required version as static property of the plugin. Dunno if I actually like it, but thought I will mention it.

**Comment by rajzshkr** [comment]
https://github.com/babel/babel/issues/7247
