### ISSUE TITLE
babel-preset-env runtime requirements check

### ISSUE THREAD

**Issue by doberkofler** [babel/babel#7266]
**feature request**
The concept of babel-preset-env is absolutely great, but seems very difficult to adopt if there is no way to make sure that the runtime actually supports all features.
I think, it would be most useful to add some functionality to the babel-preset-env package allowing to check if the minimal runtime requirements are met when running the code generated by babel.
I would guess that it should be possible to generate some stub code that checks all minimal requirements and reports any missing features.

**Comment by zloirock** [comment]
I'm not completely sure what do you mean. By "runtime" you mean an engine or available built-ins? Could you add an example of how you wanna use it?

**Comment by nicolo-ribaudo** [comment]
@doberkofler Can you explain what do you mean? Our data sources for browsers support (compat-table and corejs@3) already run tests in various engines.

**Comment by doberkofler** [comment]
I have switched to TypeScript in the meantime but what I still believe would benefit Babel (and TypeScript) would be "some" sanity check when running an application that has been compiled to a certain target version of JavaScript. If for example the target is ES2016 but the browser does not yet support all ES2016 features it fails silently instead of informing that the used browser does not fulfill the requirements.
