### ISSUE TITLE
Issue between preset-env useBuiltIns and plugin-runtime

### ISSUE THREAD

**Issue by julien-f** [babel/babel#7268]
### is this a bug report or feature request?

Bug report

### Input Code

```js
// importing library compiled with plugin-runtime triggers the import of `regenerator-runtime`
require('lib-plugin-runtime')()

// importing library compiled with preset-env and useBuiltIns triggers the import of `regenerator-runtime/runtime`
require('lib-preset-env')()
```

[Reproduction repository](https://github.com/julien-f/issue-babel-env-runtime).
Related `regenerator-runtime` issue: facebook/regenerator#337

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Expected Behavior

Both functions should work fine.

### Current Behavior

```
regeneratorRuntime.mark(function _callee() {
^

ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (/issue-babel-env-runtime/lib-preset-env/dist/index.js:13:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/issue-babel-env-runtime/index.js:5:1)
    at Module._compile (module.js:660:30)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.38
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by julien-f** [comment]
I eventually used [@babel/plugin-transform-runtime](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/README.md) as a work-around.

Feel free to weight in on the regenerator issue.

**Comment by reggi** [comment]
This is what I was trying to fix when I discovered https://github.com/babel/babel/issues/7457

Thanks @julien-f for pointing to `@babel/plugin-transform-runtime` and not `babel-plugin-transform-runtime`.

Here's the fix:

```json
{
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "4.0.0"
          },
          "shippedProposals": true
        }
      ]
    ],
    "plugins": ["@babel/plugin-transform-runtime"]
  }
```

**Comment by jquense** [comment]
this definately seems like regenerators fault

**Comment by jquense** [comment]
also a bit annoying you can't have preset-env include the transform but also exclude the polyfill...

**Comment by creeperyang** [comment]
`@babel/plugin-transform-runtime ` helps to solve the `ReferenceError: regeneratorRuntime is not defined` error.

However use `preset-env` with `plugin-transform-runtime `, when I compile code below:

```js
async function test() {}
```

I will get:

```js
"use strict";

var _interopRequireDefault = require("@babel/runtime-corejs2/helpers/interopRequireDefault");

var _regenerator = _interopRequireDefault(require("@babel/runtime-corejs2/regenerator"));

// No need to require again!
require("regenerator-runtime/runtime");

// ...
```

It looks like the compiled code **require** `regenerator-runtime` twice:

- `require("@babel/runtime-corejs2/regenerator")` , it will require `regenerator-runtime`
- `require("regenerator-runtime/runtime");` require again!

**Comment by zloirock** [comment]
Seems it's fixed on `regenerator`'s side, https://github.com/facebook/regenerator/issues/337.
