### ISSUE TITLE
README for plugin-syntax-async-generators incorrect

### ISSUE THREAD

**Issue by njlr** [babel/babel#7269]
**bug report**

`plugin-syntax-async-generators` does not seem to work without `plugin-transform-regenerator`. The [README](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-async-generators) should reflect this. 

### Input Code

```js
const main = async () => {

  const f = async function * () {
    yield * [ 1, 2, 3 ];
  };

  for await (const x of f()) {
    console.log(x);
  }
};

main().catch(error => console.error(error));
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/preset-env", {
      "targets": {
          "node": "6.10"
        }
      }
    ]
  ],
  "plugins": [ 
    "@babel/plugin-syntax-async-generators"
  ]
}
```

### Expected Behavior

```
1
2
3
```

### Current Behavior

> SyntaxError: Unexpected token *

### Possible Solution

Add `plugin-transform-regenerator` to the `.babelrc` file. 

```js
{
  "presets": [
    [
      "@babel/preset-env", {
      "targets": {
          "node": "6.10"
        }
      }
    ]
  ],
  "plugins": [ 
    "@babel/plugin-syntax-async-generators", 
    ["@babel/plugin-transform-regenerator", {
      "asyncGenerators": true,
      "generators": true,
      "async": true
    }]
  ]
}
```

### Your Environment

```
    "@babel/cli": "^7.0.0-beta.38",
    "@babel/core": "^7.0.0-beta.38",
    "@babel/node": "^7.0.0-beta.38",
    "@babel/plugin-syntax-async-generators": "^7.0.0-beta.38",
    "@babel/plugin-transform-regenerator": "^7.0.0-beta.38",
    "@babel/preset-env": "^7.0.0-beta.38",
```

**Comment by hzoo** [comment]
`@babel/plugin-syntax-async-generators` is a plugin for syntax so it would just parse it and return the same code. You would use the other plugin (-proposal or -transform)
