### ISSUE TITLE
Cannot compile code, in builtins, into my codes?

### ISSUE THREAD

**Issue by LvChengbin** [babel/babel#7270]
I just want to use some features like `Object.assign`, but I cannot find out a way to use it directly. I tried `include: [ 'es6.object.assign' ]`, `useBuiltIns: 'usage'`, `useBuiltIns: 'entry'` and `import` the file in my code, some of them add some code like `require( 'xxx/xx/xx' )` into my code, but that's not what I need, how can I config `@babel/preset-ent` will make babel inject the builtin code into my code directly?

**Comment by xtuc** [comment]
Closing, out of scope for now.
