### ISSUE TITLE
`retainLines` breaks `no LineTerminator` requirements in single-arg async arrows and decorated methods

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7275]
```js
var fn = async (
  arg
) => {}
```

with `retainLines: true` becomes

```js
var fn = async 
  arg => {}
```
which is a syntax error since `async` and `arg` need to be on the same line when there aren't parens.

We need to detect that `retainLines` is enabled, and that the identifier will insert new lines, and if so, wrap parens around the argument. We've got some existing logic in place for noLineTerminator but I don't think it would apply very well to this case. :(

Edit: A second example of this issue can also be found in https://github.com/babel/babel/issues/8650, so if we fix this issue, we should fix that one at the same time.

**Comment by Kovensky** [comment]
The latest version of Jest is supposed to have source map support; maybe babel-jest can be fixed to use that instead and we can finally get rid of `retainLines`.

**Comment by loganfsmyth** [comment]
Maybe. Basically all I ever knew was "something in Facebook relies on it". Was that specifically Jest? Maybe @kittens would know?

**Comment by julien-f** [comment]
Hey, is it related to facebook/jest#5326

**Comment by SimenB** [comment]
Opened up a PR in Jest removing `retainLines`: https://github.com/facebook/jest/pull/5594

I have no idea if other parts of FB requires it, though
