### ISSUE TITLE
Type errors for valid code after switching from preset-es2015 to preset-env

### ISSUE THREAD

**Issue by adamreisnz** [babel/babel#7276]
I am getting the following two type errors after switching to preset-env;

### Issue 1
```
Duplicate declaration "activities" (This is an error on an internal node. Probably an internal error)
```

Related relevant code with the various (valid) declarations of `activities`:
```js
.run((Page, Filters, moment, $store, $state, $transitions) => {
  $transitions.onEnter({to: 'bookings'}, transition => {
    const params = {};
    if (!params.activity) {
      const activities = transition.injector().get('activities');
      //...
    }
    //...
  });

  //Page setup
  $transitions.onSuccess({to: 'bookings'}, transition => {
    //...
    const activities = transition.injector().get('activities');
    //...
  });

  Page.defineOption('switchActivity', {
    async click() {
      //...
      const activities = await $store.activities.query();
      //...
    },
  });
});
```

They are all defined in their own function scope, so perfectly valid.

### Issue 2

`Cannot read property '0' of null`

Related code:
```js
      //Set relevant option
      if (last && this.reminderOptions.some(o => o.value === last)) {
        this.booking.reminderTime = last;
      }
      else {
        this.booking.reminderTime = this.reminderOptions[0].value;
      }
```

No idea why the latter error would be thrown as babel can't know what the value of `this.reminderOptions` will be at runtime, or whether it is `null`.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["chrome >= 60"]
      }
    }]
  ],
  "plugins": [
    "syntax-async-functions",
    "transform-regenerator",
    "angularjs-annotate"
  ]
}
```

### Expected Behavior
The code should compile and no errors should be thrown

### Current Behavior
Error is thrown as described above.

### Context
Can't build, had to revert back to es2015

### Your Environment
```
    "babel-core": "^6.26.0",
    "babel-plugin-angularjs-annotate": "^0.8.2",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-transform-regenerator": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
```
| software         | version(s)
| ---------------- | -------
| node             | 8.9.4
| npm              | Yarn 1.3.2
| Operating System |  OS X

**Comment by adamreisnz** [comment]
The first error is possibly related to https://github.com/babel/babel/issues/6923

**Comment by existentialism** [comment]
@adamreisnz can't repro this locally with just the info you provided, can you create a small repo that throws these errors?

**Comment by adamreisnz** [comment]
I'll try to make some time for it soon.

**Comment by adamreisnz** [comment]
Sorry, I can't find the time to do this. I can't post the complete source code for the page either, as it's proprietary code and it would expose too much of it.

Can you work out from the errors what may have been the source of these errors, or is that not viable?

I'll just keep using preset-es2015 for the time being, because present-env seems to be too buggy to use for production for now. If you can't analyse these issues further feel free to close this, as I won't be able to provide any more information at present.

**Comment by existentialism** [comment]
@adamreisnz no worries!

> I'll just keep using preset-es2015 for the time being, because present-env seems to be too buggy to use for production for now.

This seems a _little_ unfair, as preset-env@1.6.x has been out and in use for quite a while. I find _most_ issues related to switching from es2015 are due to the fact that since you're now not running every transform from the preset, your particular mix might just have some edge case bugs.

I'll try to find some time to look into this further, but keep in mind most of the team's time is focused on shipping 7.0!

**Comment by adamreisnz** [comment]
Sorry, didn't mean to put it that way. Just that for us, we have our hands full developing features, so we can't spend too much time on changing our build tools. I would have expected switching to present-env would have worked out of the box, but it either needs more time to setup or more time to find out why these issues are happening. That means that for us it's not production ready yet :)

One thing I noticed with both of these errors is that there wasn't really any meaningful stack trace. Do you think it's being swallowed in the rest of our build process? If that's the case I might try to run babel on it without the rest of the build tools and see if I can extract more information that way.

**Comment by jimousse** [comment]
any update on this issue? :(

I'm having the same problem with:
```
		"@babel/core": "7.0.0-beta.50",
		"@babel/plugin-proposal-class-properties": "7.0.0-beta.50",
		"@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.50",
		"@babel/plugin-transform-regenerator": "7.0.0-beta.50",
		"@babel/polyfill": "7.0.0-beta.50",
		"@babel/preset-env": "7.0.0-beta.50",
		"@babel/preset-flow": "7.0.0-beta.50",
		"@babel/preset-react": "7.0.0-beta.50",
```

having the error:
```
    TypeError: /someFile.js: Duplicate declaration "someVariable" (This is an error on an internal node. Probably an internal error.)

      at File.buildCodeFrameError (../../node_modules/par-bundler/node_modules/@babel/core/lib/transformation/file/file.js:209:12)
      at Scope.checkBlockScopedCollisions (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/scope/index.js:295:27)
      at Scope.registerBinding (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/scope/index.js:477:16)
      at Scope.registerDeclaration (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/scope/index.js:396:14)
      at Object.Declaration (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/scope/index.js:89:12)
      at NodePath._call (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/path/context.js:64:19)
      at NodePath.call (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/path/context.js:38:17)
      at NodePath.visit (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/path/context.js:99:12)
      at TraversalContext.visitQueue (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/context.js:139:18)
      at TraversalContext.visitMultiple (../../node_modules/par-bundler/node_modules/@babel/traverse/lib/context.js:93:17)
```

**Comment by nicolo-ribaudo** [comment]
Do you see the same problem when using an updated version of Babel? We have fixed some duplicate declaration bugs in the last releases.

**Comment by nicolo-ribaudo** [comment]
Closing, since the "duplicate declaration" bugs have been fixed in different Babel 7 versions. If you still see this bug, please open a new issue.
