### ISSUE TITLE
Bug when destructuring parameters in @babel/plugin-transform-flow-comments

### ISSUE THREAD

**Issue by navbruce** [babel/babel#7278]
### Input Code

```js
// @flow

function add({ a, b }: {a: number, b: number}): number {
  return a + b;
}

module.exports = add;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["@babel/plugin-transform-flow-comments"]
}
```

### Expected Behavior
```js
// @flow

function add({ a, b }/*: {a: number, b: number}*/) /*: number*/{
  return a + b;
}

module.exports = add;
```

### Current Behavior

```js
// @flow

function add({/*: {a: number, b: number}*/ a, b }) /*: number*/{
  return a + b;
}

module.exports = add;
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| @babel/plugin-transform-flow-comments | 7.0.0-beta.38
| babel-cli        |  6.26.0
| node             | 8.9.4
| npm              | 5.6.0
| Operating System | Ubuntu 16.4

**Comment by nicolo-ribaudo** [comment]
This is probably related to https://github.com/babel/babel/issues/5600
