### ISSUE TITLE
Now that both "Rest/Spread Properties" and "Async Iteration" have moved to Stage 4, what is the timeline for moving them from the stage-3 preset to preset-env?

### ISSUE THREAD

**Issue by gotofritz** [babel/babel#7285]
Hi. I am not too familiar with the process babel follows to keep its presets in sync with TC39's work, but a couple of proposals have moved from Stage 3 to Stage 4. 
https://github.com/tc39/proposals/blob/master/finished-proposals.md#finished-proposals
When can we expect them to move into the env-preset?

(In fact I see that currently not a single plugin in babel-preset-stage-3 is actually a stage 3 proposal, so I guess the answer is "not soon" :-) ... I understand these things take time, I was just curious that's it. Thanks for your work and the free code.

**Comment by nicolo-ribaudo** [comment]
Done: https://babeljs.io/repl/build/master#?babili=false&browsers=chrome%2060&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsICp4AoCUMA3gL4BQuRMAdLcDCfkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env&prettier=true&targets=Node-6&version=7.3.4
