### ISSUE TITLE
strange export import behavior

### ISSUE THREAD

**Issue by TrejGun** [babel/babel#7286]
Choose one: is this a bug report or feature request?
probably bug

### Input Code

so when i export with `export default` it can't find `inner` property

```js
// export.obj.js
import inner from "./inner";

const Obj = {
	inner: {a: 1}
};

export default Obj;
// module.exports = Obj;

// index.js
import Obj, {inner} from "./exports.obj";

console.log(Obj, inner); // prints `{ inner: { a: 1 } } undefined`
```
but when i change `export default` to `module.exports` it prints `{ inner: { a: 1 } } { a: 1 }`

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}
// package.json
{
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js"
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.38",
    "@babel/core": "7.0.0-beta.38",
    "@babel/node": "7.0.0-beta.38",
    "@babel/preset-env": "7.0.0-beta.38"
  }
}
// bash
npm start
```

### Expected Behavior

it should find inner property

### Current Behavior

it can't find inner property

### Even more
let say i want to export `function`
```
const Func = function () {}
export default Func;
// module.exports = Func;
```
and import 
```
import Func, {prototype} from "./exports.func";

// console.log(Obj, innerObj);
console.log(Func, prototype); // prints `[Function: Func] undefined`
```
none of export types will give me `prototype`

Does it work as intended? 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.b38
| node             | 8.9.4
| npm              | 5.6.0
| Operating System |  mac

**Comment by nicolo-ribaudo** [comment]
It is the expected behavior. Imports don't use destructing, so you have to explicitly `export const inner = Obj.inner`.

**Comment by TrejGun** [comment]
@nicolo-ribaudo 
but this works

```
import {prototype} from "./exports.func";
console.log(prototype);
``

as well as
```
import {inner} from "./exports.obj";
console.log(inner);
```

they are just not woking together
