### ISSUE TITLE
babel-cli to transpile parent folder jsx files

### ISSUE THREAD

**Issue by jai1331** [babel/babel#7287]
I'm using babel-cli to transpile JSX files. Folder structure goes like this:

**Main Folder** 

          - build
                 - config
                 - node_modules   // babel-cli, presets es2015,react, plugins installed here
                 - src_JSX               // this works as expected
                      - demo.jsx
                 - generated_JSX
                     - demo.jsx
                 - package.json

          - JSX                          // it's not working
                 - demo.jsx
          - JSX_generated
                 - expected JSX output file

          - App.js
          - index.html

while transpiling the JSX files placed under build folder by using the below command, works as expected.
`babel src_JSX  --out-dir generated_JSX`

Above code working as expected, but if I changed it as `babel ../JSX  --out-dir ../JSX_generated`,
 this throws error as SyntaxError: ../src/demo.jsx: Unexpected token 

Is there a way to transpile files one level up from the node have been installed ?

**Comment by nicolo-ribaudo** [comment]
This is working with Babel 7's new `babel.config.js` file. You can see an example at https://github.com/babel/babel-configuration-examples/tree/master/05-compile-from-subfolder__babel-cli (run `npm i && cd build && npm run build`)
