### ISSUE TITLE
Assigning to process.env doesn't work

### ISSUE THREAD

**Issue by caub** [babel/babel#7289]
file `a.js`:
```js
console.log(process.env.FOO);
```

file `b.js`:
```js
process.env.FOO = 'test';

import './a'; // outputs undefined
```

When running `npx babel-node path/to/b.js` (or `babel-node path/to/b.js` if installed globally) it outputs `undefined` instead of `test`

Running `FOO=test2 npx babel-node path/to/b.js` would make it output `test2` though

Versions: 
```
"@babel/core": "^7.0.0-beta.38",
"@babel/node": "^7.0.0-beta.38",
```

**Comment by nicolo-ribaudo** [comment]
Imports are hoisted, so that file will be required before that `process.env.FOO = 'test';` line is run.
