### ISSUE TITLE
'export default from' can not be correctly compiled

### ISSUE THREAD

**Issue by leaves4j** [babel/babel#7293]
Choose one: bug

### Input Code

```js
var from = 'test';
export default from;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  presets: [
        [
          '@babel/preset-env', {
            targets: { browsers: ['android>=4', 'ios>=7'] },
            modules: false,
          },
        ],
      ],
      plugins: [
        '@babel/plugin-transform-runtime',
      ],
}
```

### Expected Behavior
Compiled correctly

### Current Behavior
Throw an error
```bash
[!] (babel plugin) SyntaxError: /xxx/node_modules/@babel/runtime/core-js/array/from.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (6:8):

  4 | var from = require$$0;
  5 |
> 6 | export default from;
    |        ^
  7 | export { from as __moduleExports };

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
```

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.38|
| Babylon          | 
| node             | 9.4 |
| npm              | 
| Operating System | mac os|

**Comment by nveenjain** [comment]
I think that's a bug in babylon. I'll look into it.
```js
export default from;
```
This code should throw an Reference error as `from` is not defined, but rather it asks for additional(experimental) plugin to be added, which in turns does not accept this code either. Will try to solve and open a PR asap..

**Comment by KFlash** [comment]
@nveenjain Look at [this line](https://github.com/babel/babel/blob/master/packages/babylon/src/parser/statement.js#L1375) and add a check for the contextual keyword `from`. If it exist, simply just throw an error. Should solve this issue if it's Babylon related.

**Comment by nveenjain** [comment]
@KFlash , i think [this line](https://github.com/babel/babel/blob/eb38ea2b10d07b3451e4f68b6505cb4730aa5311/packages/babylon/src/parser/statement.js#L1312) is causing the error in babylon as [this line](https://github.com/babel/babel/blob/eb38ea2b10d07b3451e4f68b6505cb4730aa5311/packages/babylon/src/parser/statement.js#L1398) in `isExportDefaultSpecifier` function does not consider the possibility that `from` might be lineTerminator..

**Comment by KFlash** [comment]
Ok. I just pointed out to you where this maybe could be solved. At least this is how  V8, FF, Esprima among others solve similiar issue. I'm not so familiar with Babylon siurce code so I will not be surprised if I'm totally wrong in this case.

**Comment by nveenjain** [comment]
@kFlash , exactly, i was going to do the same.. I didn't know how V8, Esprima or SM implement it though. Thanks for the feedback..

**Comment by KFlash** [comment]
@nveenjain If you care about performance you could only parse out the `from` keyword and validate. Than either throw an error or create a identifier node without consuming the `from` keyword instead of resetting the parser state and consume the same token multiple times.

**Comment by nveenjain** [comment]
@KFlash , i've submitted a PR, would really appreciate review.

**Comment by vzaidman** [comment]
also on 7.0.0 it seems like there is no way to make
```

**Comment by vzaidman** [comment]
i did many things and cant recall which of them helped.

make sure to use `@babel/plugin-proposal-export-namespace-from`.
make sure to upgrade `babel-loader`

sorry - no better advices

**Comment by vzaidman** [comment]
i did many things and cant recall which of them helped.

make sure to use `@babel/plugin-proposal-export-namespace-from`.
make sure to upgrade `babel-loader`

sorry - no better advice

**Comment by vzaidman** [comment]
i did many things and cant recall which of them helped.

make sure to use `@babel/plugin-proposal-export-namespace-from`.
make sure to upgrade `babel-loader`

sorry - no better advice

**Comment by vzaidman** [comment]
i did many things and cant recall which of them helped.

make sure to use `@babel/plugin-proposal-export-namespace-from`.
make sure to upgrade `babel-loader`

sorry - no better advice

**Comment by johanazhu** [comment]
https://babeljs.io/docs/en/babel-plugin-proposal-export-default-from

**Comment by alex-cory** [comment]
@vzaidman do you think you could maybe post a snippet of your babel setup so we can see what presets/plugins you used and what babel dependencies you have to make everything work? Been stuck on this one for a little bit. I know order matters with some so that would also be helpful to see

**Comment by vzaidman** [comment]
not sure it's the best possible but still:
`babel.config.js`:
```
module.exports = function (api) {
  api.cache(true)

  return {
    presets: [
      ['@babel/preset-env', {
        useBuiltIns: 'entry',
        loose: true
      }],
      '@babel/preset-react'
    ],
    plugins: [
      '@babel/plugin-proposal-export-default-from',
      '@babel/plugin-proposal-export-namespace-from',
      '@babel/plugin-proposal-object-rest-spread',
      ['@babel/plugin-proposal-decorators', {legacy:true}],
      ['@babel/plugin-proposal-class-properties', {loose: true}]
    ]
  }
}
```
notice we use decorators so `plugin-proposal-class-properties` must be loose.

**Comment by anoopmd** [comment]
Adding the plugins '@babel/plugin-proposal-export-namespace-from' and '@babel/plugin-proposal-export-default-from' worked for me.
