### ISSUE TITLE
ESM that imports CJS can't be transpiled for both CJS and native ESM environments

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#7294]
Bug…

[This issue arises](https://github.com/jaydenseric/apollo-upload-server/issues/40#issuecomment-361271674) when attempting to create a package that:

- Transpiles both ESM (`.mjs`) for recent versions of Node.js run with `--experimental-modules` enabled, and CJS (`.js`) as a fallback.
- Imports a CJS package that contains `exports.__esModule`.

When imported CJS in `.mjs`, [Node.js provides a single default export representing the value of `module.exports`](https://nodejs.org/api/esm.html#esm_interop_with_existing_modules), so the syntax to use in source is:

```js
import graphql from 'graphql'
console.log(graphql.GraphQLScalarType) // Class
```

This syntax survives transpilation when [using `preset-env` with `modules: false`](https://github.com/jaydenseric/apollo-upload-server/blob/v4.0.2/.babelrc.js#L13) for [the `.mjs` target](https://github.com/jaydenseric/apollo-upload-server/blob/v4.0.2/package.json#L64) and works ok when running `--experimental-modules`. When transpiled with `modules: 'commonjs'` for the `.js` target, it creates syntax like this:

```js
'use strict'

var _graphql = _interopRequireDefault(require('graphql'))

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj }
}

console.log(_graphql.default.GraphQLScalarType) // Undefined
```

`_graphql.default.GraphQLScalarType` becomes causes an error as `_graphql.default` is undefined, because `_interopRequireDefault` found `__esModule` in the imported module and didn't wrap the exports under `default`.

Trying either of these approaches syntax in the source results in a functional `.js` target:

```js
import { GraphQLScalarType } from 'graphql'
console.log(GraphQLScalarType)
```

```js
import * as graphql from 'graphql'
console.log(graphql.GraphQLScalarType)
```

But breaks the `.mjs` target, because with `--experimental-modules` CJS can only be imported using default syntax.

The only workaround that seems to work in the source for both CJS and ESM targets:

```js
import graphqlDefault, * as graphqlExports from 'graphql'

const graphql = graphqlDefault || graphqlExports

console.log(graphql.GraphQLScalarType)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

`.babelrc.js`:

```js
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        targets: { node: '6.10' },
        shippedProposals: true,
        modules: process.env.MODULE ? false : 'commonjs',
        useBuiltIns: 'usage'
      }
    ]
  ]
}
```

`package.json` scripts:

```json
{
  "scripts": {
    "build": "npm run build:js && npm run build:mjs",
    "build:js": "babel src --out-dir lib",
    "build:mjs": "MODULE=true babel src --out-dir lib --keep-file-extension"
  }
}
```

### Context

I have been struggling to find an elegent solution to solve https://github.com/jaydenseric/apollo-upload-server/issues/40. `apollo-upload-server` is run by users in both traditional CJS environments and with native ESM using `--experimental-modules`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.38
| node             | 8.9.3
| npm              | 5.6.0
| Operating System | macOS

**Comment by jaydenseric** [comment]
Slack discussion: https://babeljs.slack.com/archives/C0DFJT81H/p1517292607000083.

**Comment by Andarist** [comment]
Because babel operates on files (not projects) this is currently not possible to fix in Babel itself, because it's output has to "reflect" input structure. And because of interoperability issues we cannot just change what's outputted from cjs transform.

What could possibly be done is to introduce in projects additional entry file, targeting cjs consumers which would look something like this:
```js
"use strict";

exports.__esModule = true;

var _ = require("./");

var libStar = _interopRequireWildcard(_);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

var lib = libStar.default;
Object.entries(libStar).forEach(function (_ref) {
  var key = _ref[0],
      val = _ref[1];
  // all named exports get applied to the `lib`
  // including `default`
  lib[key] = val;
});
exports.default = lib;
```

You'd have to write a custom script or a tool to handle this:
- rename original cjs entry (generated by babel)
- generate this "interop" file and name it like cjs entry before it got renamed
- rewrite require call so it points to renamed cjs entry

**Comment by nicolo-ribaudo** [comment]
@bmeck Would libraris transpiled wih https://github.com/babel/babel/pull/6455 work in the same way when imported in `.js` and `.mjs` files?

**Comment by bmeck** [comment]
@nicolo-ribaudo if node could land that pragma it would, yes. However, if you omit file extensions in your `"main"` it should also use the `.mjs` file instead of the `.js` file when being loaded by ESM.

**Comment by guybedford** [comment]
Getting alignment with Node and Babel does seem important on this.

One option might even be to get Node.js to recognize __esModule in its CommonJS loading interop, to ensure the same shape in that case (ie provide named exports only, without setting the default`).

With some luck we may be able to provide named exports for all CommonJS imports in Node.js, and if this does work, such a check would simply skip the "default" assignment.

Will argue for this in the modules group!

**Comment by bmeck** [comment]
@guybedford `__esModule` is not statically analyzable, as has been stated before. The dynamic modules spec could not change based upon such unless we want to allow some complex behaviors regarding tracking synthetic vs not `default` values.

**Comment by guybedford** [comment]
@bmeck my comment applies assuming the dynamic modules spec. Currently we're proposing to reflect the CommonJS module in ES as `{ ...exports, ...{ default: exports } }` if dynamic modules can move forward. __esModule could then possibly be used as an indicator to only provide `{ ...exports }` instead, thus ensuring the default export doesn't need to be accessed at `x.default.default`.

**Comment by jkrems** [comment]
> Currently we're proposing to reflect the CommonJS module in ES as `{ ...exports, ...{ default: exports } }` if dynamic modules can move forward.

Bit rot prevention measure / narrator: It didn't move forward.

CommonJS modules are currently exposed strictly as a `default` binding without support for named exports.

**Comment by ExE-Boss** [comment]
> CommonJS modules are currently exposed strictly as a `default` binding without support for named exports.

This is now partially supported using [cjs‑module‑lexer](https://github.com/guybedford/cjs-module-lexer): <https://nodejs.org/api/esm.html#esm_commonjs_namespaces>
