### ISSUE TITLE
ULR class not properly polyfilled

### ISSUE THREAD

**Issue by kevipapo1** [babel/babel#7300]
### Input Code (src/app.js)

```js
const URL = require('url').URL;

const url = new URL('https://www.google.com/');
console.log(url);
```

### Babel/Babylon Configuration (.babelrc)

```js
{
    "presets": [
        ["env", {
            "targets": {
                "browsers": [
                    "last 2 years"
                ]
            }
        }]
    ]
}
```

### Webpack Configuration (webpack.config.js)

```js
const path = require('path');

module.exports = {
    entry: [path.join(__dirname, 'src', 'app.js')],
    output: {
        path: path.join(__dirname, 'lib'),
        filename: '[name].js'
    }
}
```

### Expected Behavior

URL object should be printed to console. (This happens when `src/app.js` is run in Node.)

### Current Behavior

Error in console: `TypeError: URL is not a constructor`

### Context

MDN page on `URL`: https://developer.mozilla.org/en-US/docs/Web/API/URL

The `URL` class is global in the latest version of Chrome. The polyfilled (?) version of the `URL` class in the webpacked JavaScript has an entirely different interface from the one described in the MDN article. It has a different set of methods (`#parse`, `#format`, `#resolve`, and a couple others), some that return what resembles a `URL` object (not all properties are the same), and no constructor.

The issue also occurs when:

- Adding `'babel-polyfill'` to the beginning of the `entry` array in the Webpack configuration
- Making `require('babel-polyfill')` the first line of `src/app.js`

I can upload a Node project to GitHub that contains all the code to reproduce this issue, if that's helpful.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon        |  N/A
| Webpack      |  3.8.1
| node             | 8.8.0
| npm              | 5.5.1
| Operating System | Windows 10 Home x64

**Comment by zloirock** [comment]
`babel-polyfill` is [`core-js`](https://github.com/zloirock/core-js). `core-js` already have an issue about `URL` - https://github.com/zloirock/core-js/issues/117. At this moment, `core-js` mainly about ECMAScript. `URL` class is not a part of ECMAScript, but recently has been proposed to move `URL` to ECMAScript - https://github.com/jasnell/proposal-url, so feel free to add a PR to `core-js`.
