### ISSUE TITLE
babel-preset-env should support .browserslistrc amongst other browserslist configurations

### ISSUE THREAD

**Issue by vaxul** [babel/babel#7307]
Currently babel-preset-env require the browserslist configuration within the JSON-configuration like:
```json
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions"
          ]
        }
      }
    ]
  ]
```

It should be considered that babel-preset-env uses the global .browserslistrc too.

## Steps to reproduce the current situation:
1. Download the example [babel-dummy.zip](https://github.com/babel/babel/files/1685317/babel-dummy.zip)
1. `yarn install`
1. run `gulp process` to process the example CSS and JS file

The default setup .browserslistrc is `last 2 versions` which results in:
- dist/example.css
```css
body {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
```
- dist/example.js
```js
"use strict";

var numbers = [1, 2, 3];
var firstNumber = numbers[0];


console.log(firstNumber);
```

Now edit the .browserslistrc and comment `last 2 versions` and insert last `2 Chrome versions` and rerun `gulp process` which results in:
- dist/example.css
```css
body {
    display: flex;
}
```
- dist/example.js
_Same as before_

Now copy the Babel configuration from `.babelrc_current-required` into `.babelrc` (use `last 2 Chrome versions` instead) and rerun `gulp process` which results in:
- dist/example.js
```js
"use strict";

const numbers = [1, 2, 3];
const [firstNumber] = numbers;

console.log(firstNumber);
```
This result should be the same if I configure my browserslist only with the .browserslistrc file.

Since browserslist support configuration besides .browserslistrc f.e. in the [package.json](https://github.com/ai/browserslist#packagejson) I think babel-preset-env should it too.

Would this be possible?

Best regards

**Comment by jaydenseric** [comment]
The cutting edge version supports `browserslist` in your `package.json`, I assume the other ways to set browserslist would work too.

**Comment by vaxul** [comment]
Thank you for the hint. I can confirm that it works with the current beta (39) with the following setup:
- package.json
```json
{
  "name": "babel-example",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.39",
    "@babel/register": "7.0.0-beta.39",
    "autoprefixer": "^7.2.5",
    "babel-preset-env": "^7.0.0-beta.3",
    "gulp": "^4.0.0",
    "gulp-babel": "^8.0.0-beta.1",
    "gulp-load-plugins": "^1.5.0",
    "gulp-postcss": "^7.0.1"
  }
}
```
- .babelrc
```json
{
  "presets": [
    [
      "env"
    ]
  ]
}
```
- .browserslistrc
```
#last 2 versions
last 2 Chrome versions
```

`babel-preset-env` is currently necessary for `@babel/register` which is necessary to get gulpfile.babel.js to work.

Here my testcase:
[babel-beta-dummy-working.zip](https://github.com/babel/babel/files/1688471/babel-beta-dummy-working.zip)

**Comment by vaxul** [comment]
Closed, since it's available in the latest beta.

**Comment by thasmo** [comment]
Ah, that explains why it's probably not working with the current stable.
