### ISSUE TITLE
Generate Program body with regenerator runtime

### ISSUE THREAD

**Issue by Alphapage** [babel/babel#7316]
Hello,

I can't find any option to use regenerator runtime to transform Program body.
For now, regenrator runtime can transform functions like this:
```
function *(){
    yield 0;
    yield 1;
}
```
But I need it to transform `Program` body like this to use it during an `eval`:
```
yield 0;
yield 1;
```
Is there an option or do you plan to implement one ?

Thank you in advance for your help.

**Comment by loganfsmyth** [comment]
What would it transform into? To make things work, Babel needs to transform the function as a whole.

**Comment by Alphapage** [comment]
As far as I understand Babel plugin extension, Program body is not considered as a function. So regenerator doesn't transform the Program part.
I Just need it to transform yield as if it was in a function body.

**Comment by loganfsmyth** [comment]
Right but that's by my question, what would it convert it to? Babel's exact output there depends a lot on what the outer function itself was converted into. There is nothing for an individual `yield` to be converted into that would allow it to function properly. The generator transform only works because it can transform a whole function at a time.

**Comment by Alphapage** [comment]
I thought regenerator only care about function body. But You tell me it needs the whole function. Am I right?

**Comment by loganfsmyth** [comment]
Take for example https://babeljs.io/repl/#?babili=false&browsers=chrome%20%3E%2055%20%20&build=&builtIns=false&code_lz=FANwhgTgBAZgdlAvLArnAxgFwJYHsEBUUAFAJQDewUUVUAntgKYA2AJtQCwDcwAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

It replaces the whole function, not just the body.

**Comment by Alphapage** [comment]
OK, Thank you very much for your assistance. I will close be it seems impossible to implement.
