### ISSUE TITLE
Missing implementation for ... SpreadProperty in generator

### ISSUE THREAD

**Issue by nathancahill** [babel/babel#7318]
### Input Code

```js
import {parse} from 'babylon';
import generate from '@babel/generator';

const code = 'var a = { ...b }';
const ast = parse(code, { plugins: ['objectRestSpread'] });

const output = generate(ast);
```

### Expected Behavior
This should output similar code to the Babylon input.

### Current Behavior
`ReferenceError: unknown node of type "SpreadProperty" with constructor "Node"`

### Possible Solution
Submit a PR with the implementation of `SpreadProperty` in https://github.com/babel/babel/tree/278cd5e/packages/babel-generator/src/generators. I'm willing to write this.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-generator          | 7.0.0-beta.39

**Comment by loganfsmyth** [comment]
You're using `@babel/generator` so are you using Babylon 7.x? `SpreadProperty` was renamed `SpreadElement` in 7.x, so it sounds like your parser is still creating the old name and this probably is 6.x?

**Comment by nathancahill** [comment]
You're exactly right, thanks for your time.
