### ISSUE TITLE
With to5Options.moduleIds: true module names include whole path

### ISSUE THREAD

**Issue by johlrich** [babel/babel#732]
Originally from https://github.com/6to5/karma-6to5-preprocessor/issues/5

With to5Options.moduleIds: true module names are including the entire path. I tried setting the sourceRoot, but then the path was duplicated before the desired module portion.

The only way I was able to get just the module portion was to add filenameRelative to the per file options and assign it a function to strip the initial path. I feel like I'm missing something simple over this being a bug. Thoughts?

Not sure if this matters, but I am on windows.

**Comment by sebmck** [comment]
Can you provide a sample `filename` and `sourceRoot/moduleRoot` that I can use to test with?

**Comment by johlrich** [comment]
```
  var to5Options = {
      sourceMap: true,
      modules: 'system',
      moduleIds: true,
      sourceRoot: process.cwd(),
  };
```

`filename` on disk: `C:\Dev\bitbucket\ng-devenv\workform\workform.spec.js`

After you mentioned moduleRoot I tried setting it to `''` in the to5Options and that actually worked. After re-reading the options docs and the description of moduleRoot I suppose that makes sense. At the same time having the default moduleRoot = (sourceRoot) would make me think the system knew to carve off the sourceRoot from the moduleRoot when creating the final paths. I guess I'm a bit confused at what proper values are for this setting.

**Comment by sebmck** [comment]
Oh right, this is intended behaviour as far as I can understand. Sorry for taking so long to get back to you. Do you have any suggestions for how to make this clear in the docs?
