### ISSUE TITLE
Polyfilling ResizeObserver

### ISSUE THREAD

**Issue by ZeeCoder** [babel/babel#7328]
I was just about to start babel-plugin-transform-runtime, and realised it doesn't polyfill ResizeObserver yet.
Is there any specific reason for it, or is it just not implemented yet?

If it's the latter, I'd be more than glad to help out. 🎉

**Comment by loganfsmyth** [comment]
Generally Babel's polyfill goals only apply for the actual language standard. Polyfills for other specifications are considered beyond the goal of the project.

**Comment by ZeeCoder** [comment]
Ah, thought babel polyfills any spec that was implemented by a browser, based on this file: https://github.com/babel/babel/blob/master/packages/babel-preset-env/data/shipped-proposals.js

I must've just misunderstood the goal of that file then. 👍
Thanks for the quick answer btw. 🎉

**Comment by nicolo-ribaudo** [comment]
@ZeeCoder Babel only polyfills ECMAScript features.

What is ECMAScript? It is the core of the JavaScript that you can use in the browser. Browsers implements ECMAScript, and on top of it there are lots of expansions (Dom objects, service workers, Ajax, ...). `ResizeObserver` is one of those expansions.

How can you know if a feature is part of ECMAScript or not?
I'd suggest searching for that function on [MDN](https://developer.mozilla.org/), and look at the `Specifications` section ([ArrayBuffer example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Specifications)).

**Comment by ZeeCoder** [comment]
Cool tips, thanks @nicolo-ribaudo ! I'm sure it'll come in handy.

**Comment by ZeeCoder** [comment]
Actually, one more question.
Is there any way I can polyfill the ResizeObserver using transform-runtime and a polyfill of my choosing?

To be exact, I would like to convert this:
```js
const ro = new ResizeObserver();
```
to something like this:
```js
import _ResizeObserver from 'resize-observer-polyfill';

const ro = new _ResizeObserver();
```

..automatically, the same way it does for actual language standard features.

**Comment by loganfsmyth** [comment]
You'd have to write your own plugin to handle that, but it's certainly doable.

**Comment by ZeeCoder** [comment]
Great, thanks.
That's actually a good excuse for me to finally write a babel plugin. 👍
