### ISSUE TITLE
[bug] Destructuring with preset-env, can cause "Assignment to constant variable" errors

### ISSUE THREAD

**Issue by caub** [babel/babel#7329]
```js
const { data: { courses: oldCourses = [] } = {} } = getState();
```
gets transpiled to:

```js
const _getState = getState(),
        _getState$data = _getState.data;

  _getState$data = _getState$data === void 0 ? {} : _getState$data;
```
which obviously throws `TypeError: Assignment to constant variable.`

`.babelrc`: 
```json
{
  "presets": [
    "@babel/preset-react",
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": ["last 2 versions", "not ie > 0", "not Android > 0"] // skip IE for this quick thing, else need babel-polyfill
        }
      }
    ],
    "@babel/preset-stage-3"
  ],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

| software         | version(s)
| ---------------- | -------
| Babel            |  ^7.0.0-beta.39
| node             |  9.4
| npm              |  5.6
| Operating System |  Linux

**Comment by existentialism** [comment]
Related: https://github.com/facebook/create-react-app/issues/3891

**Comment by nveenjain** [comment]
we should expect variables to be `var` type right? Seems like the variables are `var` type when 
```js
"browsers": ["last 2 versions", "not ie > 0"]
```
but `const` type when `"not android >0 " is added to array.
I'm willing to take this up

**Comment by caub** [comment]
@nveenjain It's intentional, doing so skip all browsers not supporting `let/const`
