### ISSUE TITLE
babel-plugin-transform-runtime browserslist support

### ISSUE THREAD

**Issue by ZeeCoder** [babel/babel#7330]
For some reason I thought this is how it worked already, but I think this plugin doesn't check for browserslist like preset-env do, and just injects the require/import statements for everything.

For example ideally it should add the import statement for `Promise`, when my target browsers have a native implementation.

**Comment by nicolo-ribaudo** [comment]
Maybe a `"useBuiltIns": "runtime"` option in preset-env?

**Comment by ZeeCoder** [comment]
Is that a thing @nicolo-ribaudo ?
I only see "entry", "usage" and false for that option: https://github.com/babel/babel/tree/master/packages/babel-preset-env#usebuiltins

As far as I know transform-runtime is a bit different from preset-env, in that the latter polyfills the environment, while the former adds require statements pointing to "polyfilling" modules where needed.
🤔

I can't use preset-env useBuiltins, because that would alter globals, which is a big no for a library.

**Comment by nicolo-ribaudo** [comment]
Yup, I was proposing a new value for that option :slightly_smiling_face:

**Comment by ZeeCoder** [comment]
transform-runtime's useBuiltIns option is a bit confusing to me, it basically seems like you can disable this scoped polyfilling stuff alltogether.

**Comment by existentialism** [comment]
We can move discussion of this into: https://github.com/babel/babel/issues/6629 :)

**Comment by ZeeCoder** [comment]
aaaaaah right.
Sorry @nicolo-ribaudo thought I was just not understanding something.
Yeah that would work for me I think.

So then "entry" and "usage" would still mean the same thing (polyfilling the global env) and "runtime" would do the same conditional polyfilling as "usage" does, only that it injects import / require statements pointing to polyfills instead of patching the globals.
(As transform-runtime does it)

Essentially either preset-env is made smarter, so that it's suitable for libs too, or transform-runtime could be made smarter to detect browserslist config the same way preset-nev does.

Not sure which is the smarter / easier way, I have a gut feeling though that making transform-runtime smarter might be the better option.

Not sure who's the best to answer that though, @hzoo could advise?

**Comment by ZeeCoder** [comment]
Yep that makes sense

**Comment by existentialism** [comment]
@ZeeCoder thanks again for the report, gonna close this so we can merge discussion with https://github.com/babel/babel/issues/6629
