### ISSUE TITLE
Can you explain why does Babel copy an array before passing it to concat?

### ISSUE THREAD

**Issue by lomaster1** [babel/babel#7332]
My code:
`const allMessages = [ ...resultMessages, ...oldNotErrorMessages ];`
Babel convert to
```
function _toConsumableArray(arr) {
  if (Array.isArray(arr)) {
    for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) {
      arr2[i] = arr[i];
    }
    return arr2;
  } else {
    return Array.from(arr);
  }
}
var allMessages = [].concat(
  _toConsumableArray(resultMessages),
  _toConsumableArray(oldNotErrorMessages)
);
```
Why not `if (Array.isArray(arr)) return arr; else return Array.from(arr)`?
Why does Babel copy an array if it array before passing it to concat?

**Comment by maaz93** [comment]
I don't think this is an issue as such. You're actually looking for the [`loose`](https://babeljs.io/docs/plugins/transform-es2015-spread/#loose) mode for the spread transform.

See [this](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAhgGwQWQKYQnA5umBeGAbRgDoyAndAVwSjQ23QBpSyQEATAORCgFFy5EOXqYcEGAF0A3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015-loose&prettier=true&targets=&version=6.26.0&envVersion=) for what it transpiles to in loose mode.

You can change your `.babelrc` as follows if you want `loose` mode only for the spread

```js
{
  presets: [...],
  plugins: [
    ["transform-spread", { loose: true }],
  ],
}
```

I'm not aware of why this was designed this way, but I can only guess that there are a few corner cases which can be avoided by using the `for` loop. You should probably ask the reasons in the above mentioned slack channel. 😃

**Comment by nicolo-ribaudo** [comment]
I think that it is for two reasons:
1) `[ ...foo ]` is compiled to `_toConsumableArray(foo)`, which can't be `=== foo`
2) Holes needs to be conveted to `undeifned`:
```js
> [ 0, ...[ 1, , 2 ] ]
[0, 1, undefined, 2]

> [ 0 ].concat([ 1, , 2 ])
[0, 1, empty, 2]

> [ 0 ].concat(_toConsumableArray([ 1, , 2 ]))
[0, 1, undefined, 2]
```

**Comment by lomaster1** [comment]
Thanks @maaz93 and @nicolo-ribaudo.
