### ISSUE TITLE
[CLI] Watch mode exits when compiling a file with an error

### ISSUE THREAD

**Issue by VojtechStep** [babel/babel#7334]
Choose one: is this a bug report or feature request?
**Bug report**

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    "@babel/plugin-syntax-typescript",
    "@babel/plugin-proposal-optional-chaining"
  ],
  "sourceMaps": "inline"
}

```

### Expected Behavior
Babel stays in watch mode, showing the code frame with the error

### Current Behavior
Babel exits with a stack trace

### Possible Solution
Probably caused by #6826. `pacakges/babel-cli/src/babel/util.js#compile` calls the callback with `{ ignored: true }` instead of `undefined` for the result when in watch mode. Fixing this should be as easy as changing
```js
if (!res) return callback(); 
```
to 
```js
if (!res || res.ignored) return callback();
```
at https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/dir.js#L35 (or at least it worked for me)

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.39
| Babylon          | 
| node             | 
| npm              | 
| Operating System | Windows 10 FCU

**Comment by VojtechStep** [comment]
I can do a PR if necessary

**Comment by loganfsmyth** [comment]
return callback(null, { ignored: true });

should just be

    return callback(null, null);

`ignored: true` is leftover from a refactoring of how ignoring works.

If you'd like to PR it, go for it!

**Comment by jaydenseric** [comment]
@VojtechStep godspeed! This fix will really improve DX; I'm constantly manually restarting my watch script.
