### ISSUE TITLE
Babel CLI returning non-zero if directory is empty?

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7337]
From https://github.com/gatsbyjs/gatsby/pull/3785#discussion_r164922293. Haven't investigated but assuming it is accurate, it doesn't seem ideal to me. If I do
```
babel src -d lib
```
I'd say as long as the `src` directory exists, the fact that it has no files in it shouldn't be considered an error.

**Comment by xadhix** [comment]
I would like to work on this issue if its ok? Could you give me a starting point?

**Comment by rajzshkr** [comment]
@loganfsmyth so it should create an empty lib folder?

**Comment by loganfsmyth** [comment]
To be clear, this is specifically for `babel src -d lib`. We'd want to error if `src` doesn't exist I think, but if the folder is there and is just empty, I don't think it should be an error. Since I haven't investigated I'm not 100% it even _is_ an error, so someone will need to check.

As for if we create `lib`, it depends on if we create the lib folder now or rely on it being there, but if we create it already, then I'd say we should create it even if there are no files.

@xadhix If you'd like to join our Slack, it'd be a good place to have these conversations a bit quicker.

**Comment by rajzshkr** [comment]
Thanks for the clarification. 

@xadhix Error happens [here](https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/dir.js#L87). Let me know if you have any doubts in fixing this issue.

**Comment by Qantas94Heavy** [comment]
I'm not sure what the issue is here, could someone please clarify?

I just tried this in an empty test directory:

```
qantas94heavy@laptop:~/test> ls
qantas94heavy@laptop:~/test> babel src -d lib
src doesn't exist
qantas94heavy@laptop:~/test> ls
qantas94heavy@laptop:~/test> mkdir src
qantas94heavy@laptop:~/test> babel src -d lib
qantas94heavy@laptop:~/test> ls
qantas94heavy@laptop:~/test> cd lib
bash: cd: lib: No such file or directory
qantas94heavy@laptop:~/test> cd src
qantas94heavy@laptop:~/test/src> ls
# (nothing)
qantas94heavy@laptop:~/test/src> echo "const a = 1;" > test.js
qantas94heavy@laptop:~/test/src> cd ..
qantas94heavy@laptop:~/test> babel src -d lib
src/test.js -> lib/test.js
```

There was only an error if `src` does not exist. An empty `src` directory produced no error.

Tested with babel-cli@7.0.0-beta.3.

**Comment by loganfsmyth** [comment]
Fix has landed on master.
