### ISSUE TITLE
Babel --source-maps - resulting source map has "sources" path to the non-transpiled file in source folder, not to the transpiled file in output folder

### ISSUE THREAD

**Issue by Aremyst** [babel/babel#7338]
Bug

### Input Code
_main.js_:
```js
let greeting = "Hi";
console.log(`-- ${greeting} Aremyst`);

// After transpiling and using source map, I would like to be navigated
// to this exception inside this non-transpiled original ES6 JS file.
throw "my exception";
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
_package.json_:
```js
{
  "name": "babeldemo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1"
  }
}
```

_CLI command_:
```
npx babel src --presets es2015 --out-dir build --source-maps
```

### Expected Behavior
Resulting _main.js.map_ should point to transpiled _main.js_ file, which is inside _build_ folder.
So, I would expect the _"sources" property_ inside _main.js.map_ to be _"main.js"_ or _"./main.js"_.
_Expected main.js.map_:
```js
{
  "version": 3,
  "sources": [
    // This is the path I expect, not "../src/main.js"
    "main.js"
  ],
  // . . .
  "file": "main.js",
  "sourcesContent": [
    "let greeting = \"Hi\";\r\nconsole.log(`-- ${greeting} Aremyst`);\r\n\r\n// After transpiling and using source map, I would like to be navigated\r\n// to this exception inside this non-transpiled original JS file.\r\nthrow \"my exception\";"
  ]
}
```

### Current Behavior
Resulting main.js.map points to original(source) _main.js_ file, which is inside _src_ folder.
So, the _"sources" property_ inside _main.js.map_ is _"../src/main.js"_.

_Actual main.js.map after CLI command_:
```js
{
  "version": 3,
  "sources": [
    // This path I do not expect, because it points to source  non-transpiled JS file, instead of the output transpiled one.
    "../src/main.js"
  ],
  // . . .
  "file": "main.js",
  "sourcesContent": [
    "let greeting = \"Hi\";\r\nconsole.log(`-- ${greeting} Aremyst`);\r\n\r\n// After transpiling and using source map, I would like to be navigated\r\n// to this exception inside this non-transpiled original JS file.\r\nthrow \"my exception\";"
  ]
}
```

### Context
I execute the transpiled _main.js_ file(by referencing it from simple _.html file_) in Chrome.
When exception is thrown, I would expect to be able to navigate to original ES6 code, but currently source map has wrong path, so I can only see transpiled ES5 code, because source map _"sources" attribute is wrong.

**If it's still not clear, please see this small reproduction video**:
https://www.screencast.com/t/VihpvO1CE

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             |  v6.10.1
| npm              | 5.6.0
| Operating System | Windows 10
| Chrome | 63.0.3239.132

**Comment by flapjackfritz** [comment]
I am seeing this happen too.

I think it's related to this line.
https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/dir.js#L28

**Comment by loganfsmyth** [comment]
The objective of the `sources` fields are to show a useful filename when debugging errors. Generally that translates to the original filepath of the code, since when you are debugging you are generally thinking in context of the original files.

> When exception is thrown, I would expect to be able to navigate to original ES6 code, but currently source map has wrong path, so I can only see transpiled ES5 code, because source map _"sources" attribute is wrong.

I'm not sure I understand this.

> I would expect to be able to navigate to original ES6

If that is the case, then having `sourcea` be the path of the original file is the expected behavior.

> I can only see transpiled ES5 code

Could you maybe make a recording demonstrating what you are seeing? If you click the name of the original file, I'd expect you to see the original code.

**Comment by flapjackfritz** [comment]
I figured out what I was doing wrong.  `--source-map` does not seem to work.  I needed to be writing `--source-maps`.

Whoopsies :)

**Comment by Aremyst** [comment]
Thanks for attention to this issue and responses.

> Could you maybe make a recording demonstrating what you are seeing? If you click the name of the original file, I'd expect you to see the original code.

Sure, here's the video with full voice explanation of Expected and Actual Behaviors.
https://www.screencast.com/t/GjtokP7JNT

**Comment by loganfsmyth** [comment]
Weird! The biggest question for me is why it takes you to `Application` instead of `Sources`. If you look at the file in `Sources` does it show both mapped and unmapped? I'm gonna guess no, but I am curious.

I don't know what's up with yours, but as a contradicting example, here's a recording of what I see with a similar sample.

http://recordit.co/1Oy29GjO18

You can see that the map still contains `../src/main.js`, but Chrome follows it just fine.

**Comment by Aremyst** [comment]
> Weird! The biggest question for me is why it takes you to Application instead of Sources.

That's a good catch.
I've investigated and now I understand why source maps weren't working as I expected.

I didn't know that source maps are only downloaded by Chrome if Developer Tools are already opened.
In my video you can see that I've opened Developer Tools only after the page was loaded.
If I simply refresh, it's working just like in your case.

This [StackOverflow answer](https://stackoverflow.com/a/44316255/1433660) explains this a bit.

Also I had doubts what if I move folder "build" to some place(production), where src folder doesn't exist.
But in this case everything is fine too: clicking on exception in Chrome console gets me navigated to non-transpiled code, which is expected.

So, thank you, @loganfsmyth , we can close this issue.
