### ISSUE TITLE
this is null when trying to reach module.exports using es2015 preset

### ISSUE THREAD

**Issue by juanda99** [babel/babel#7339]
Bug
----

index.js file:

```
exports.token = {
  expiresIn               : 60 * 60,
  calculateExpirationDate : () =>
    new Date(Date.now() + (this.token.expiresIn * 1000))

};

console.log (this.token.calculateExpirationDate());
```

### Expected Behavior
```
babel-node  --presets es2015 index.js
2018-02-06T11:19:04.015Z
```
### Current Behavior
```
babel-node index.js
2018-02-06T11:19:04.015Z

babel-node  --presets es2015 index.js
/Users/juandaniel/Code/kk/index.js:11
console.log(undefined.token.calculateExpirationDate());
                     ^

TypeError: Cannot read property 'token' of undefined
    at Object.<anonymous> (/Users/juandaniel/Code/kk/index.js:8:14)
    at Module._compile (module.js:569:30)
    at loader (/Users/juandaniel/.nvm/versions/node/v8.2.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/juandaniel/.nvm/versions/node/v8.2.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/juandaniel/.nvm/versions/node/v8.2.1/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:569:30)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| babel-preset-es2015 | 6.24.1
| node             | 8.2.1
| npm              | 5.6.0
| Operating System | MacOS

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (180/150 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 5588 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:54781 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0R9-001bsN-PU
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:16 -0700
Date: Tue, 06 Feb 2018 02:25:04 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912704;
	bh=rgjIqPsLM1PjbVvC/gu/uUfIFDeI6lDiVhK+SaIpZd4=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=kpmcNqNXNtsfqFToFptWW/dJaWvFnlH3epMGF5C7yWjSjS9B35LyhRFQW3XvhPNgm
	 OytyU/dRaNrzx95wCvNuJg5ElqYoon4NE5bzFP+vlHIICzpXxS7jfwcHDzoedsVTbG
	 byn6oV2o+dGahCEqLuTuqcjDVlCZwlrtxDAiDHA8=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (182/150 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:60981)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0RA-001bsu-P5
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:18 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=FfuQAxrnuHkl4BhAmgad/7x8ucA=; b=pcl2Dlp+vwdKyLxQ
	SeQtsF0uNhDBWsQTvYDBG0BxfrpBFhpWkRYJUtKQ+7zC2TwoSeTLsugwe+Hz5jO3
	EauhcOINKfOPrB9797pQx1MdqHrJQM6NoEhMH79C25nlvCPTLGFjb0q2tL7MYPNF
	s3Y4LcQsTnjDEndQZ50JDjEagxY=
Received: by filter0943p1mdw1.sendgrid.net with SMTP id filter0943p1mdw1-28019-5A798281-8
        2018-02-06 10:25:05.460136955 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad2.sendgrid.net (SG) with ESMTP id ndxqlCUGTbmL1qUuepY3fQ
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:25:05.457 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:25:05 +0000 (UTC)

**Comment by zloirock** [comment]
Global `this` in the strict mode / ES modules is `undefined`, so it's expected behaviour.
