### ISSUE TITLE
From 'requireJS' format to 'es6' style modules

### ISSUE THREAD

**Issue by vsnikkil** [babel/babel#7346]
Is there a maintained plugin to go from _requirejs_ modules to _es6_ styled modules? I wish to apply the transformation for +500 files. This is not trivial task at all and prune to errors!

**Comment by hzoo** [comment]
Thanks for the issue, but this isn't really a Babel feature/bug report? I would ask these kinds of questions on stackoverflow, twitter, or our slack next time. I would look into https://www.npmjs.com/package/amd-codemod or something similar on google.

**Comment by vsnikkil** [comment]
Thanks for redirecting me to help @hzoo. You may also add a 'feature request' label as this is a feature request now.
