### ISSUE TITLE
MobX decorators don't work with Babel 7

### ISSUE THREAD

**Issue by houshuang** [babel/babel#7348]
There is something in Babel 7 which is interfering with the `@computed` decorator from MobX - code which works in Babel 6 with babel-plugin-transform-decorators-legacy to @babel/plugin-proposal-decorator in Babel 7, and I get no errors, but also no reactivity.

If you look at [this example repo](https://github.com/houshuang/meteor-crash-babel-repro) (you need Meteor to run it), I have a very simple Mobx store/component in [imports/ajs](https://github.com/houshuang/meteor-crash-babel-repro/blob/master/imports/ajs).

I then compiled this with Babel manually, twice - once with Babel 6 ([this file](https://github.com/houshuang/meteor-crash-babel-repro/blob/master/imports/b.js)) and once with Babel 7 ([this file](https://github.com/houshuang/meteor-crash-babel-repro/blob/master/imports/a.js)). I include both of these components on the screen. When I click on the link, the text should change (and I console log the computed value updating). With the Babel 6 compiled code, it works, with the Babel 7 compiled code, it doesn't.

I was trying to look at the compiled code to see if there were any differences, but apart from some formatting, it was very hard to tell the difference. However, hopefully this somewhat minimal example could help others look into this - I would really appreciate your help!

**Comment by billyvg** [comment]
For babel7 you need to use loose mode and decorators plugin must come before `class-properties`. See https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-decorators#usage

**Comment by edsrzf** [comment]
This is now documented on MobX's site: https://mobx.js.org/best/decorators.html#enabling-decorator-syntax (scroll down to "Babel 7")

Can we close this issue?

**Comment by nicolo-ribaudo** [comment]
Yes @edsrzf, thanks!
