### ISSUE TITLE
Ensure that class bodies have 'use strict' if the parent scope wasn't already

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7349]
ES6 class scopes are automatically strict-mode. In Babel 6 the module transform pretty much just _always_ made modules strict, but now that people are more likely to be using `sourceType: "unambiguous"`, we'll want to make sure the class transform injects `use strict` if the file isn't a module and doesn't have a `use strict` directive in a parent scope.

### Input Code

```js
class Foo {
  method(){

  }
}
```

### Expected Behavior
```
var Foo = function () {
  "use strict";
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: "method",
    value: function method() {}
  }]);

  return Foo;
}();
```

### Possible Solution

We likely want to walk up the parent paths, and any time a BlockStatement that is a function body is passed, we can check if `path.node.directives` has a `use strict` or not. If we get all the way to the top and didn't find one, and the root `Program` node doesn't have `sourceType === "module"`, we should add a Directive node to the classes wrapper function expression.

**Comment by MarkusToe** [comment]
Hello, first-timer here. Can I help you with this issue? Maybe you can guide me through my first PR?

**Comment by loganfsmyth** [comment]
Sure! If you'd like to join our Slack we can help answer questions for you there: https://github.com/babel/notes/issues/38

**Comment by Kovensky** [comment]
Would it be harmful to just always add the directive anyway? It increases output size, but I believe a minifier should be able to deal with it?

**Comment by loganfsmyth** [comment]
@Kovensky If someone can check to see if Uglify handles that, we could explore it. The only downside is it means we can't optimize

```
class Foo {}
```
to 
```
var Foo = function Foo(){}
```
anymore because there wouldn't be a place for it, so we'd nee
```
var Foo = (function(){
  "use strict";
  function Foo(){}

  return Foo;
})();
```

that said, I don't think that optimization comes up that often really.

**Comment by nieroda** [comment]
@MarkusToe are you working on this issue? Otherwise I will take it

**Comment by nieroda** [comment]
I think I will claim this

**Comment by MarkusToe** [comment]
Ok, I made myself familiar with the code but there are still some things which are unclear to me. Am I right that the `"use strict"` directive should be placed/or is found in the `closureParams`?

**Comment by loganfsmyth** [comment]
The `t.blockStatement` at https://github.com/babel/babel/blob/7e90d56024e0f6a3387647fcd1dafbeedc2348c2/packages/babel-plugin-transform-classes/src/vanilla.js#L168 is the important part because BlockStatements have a `directives` array: https://github.com/babel/babel/blob/master/packages/babylon/ast/spec.md#blockstatement, so you'll want to create a `use strict` directive item, and include it in that array. The directives are the second argument, so you can do something like

```
t.blockStatement(body, [t.directive(t.directiveLiteral("use strict"))])
```
to make a block statement with `use strict`.

**Comment by graingert** [comment]
> We likely want to walk up the parent paths, and any time a BlockStatement that is a function body is passed, we can check if path.node.directives has a use strict or not. If we get all the way to the top and didn't find one, and the root Program node doesn't have sourceType === "module", we should add a Directive node to the classes wrapper function expression.

Wouldn't it be easier to just add the "use strict" on every class, and then rely on a minifier to remove it?

**Comment by loganfsmyth** [comment]
@graingert Addressed above in https://github.com/babel/babel/issues/7349#issuecomment-363968744

If someone wants to verify if minifiers actually do this, we can certainly have that discussion.

**Comment by dantman** [comment]
I quickly dumped the third snippet in https://github.com/babel/babel/issues/7349#issuecomment-363968744 into the online minifier services:

- [Closure Compiler](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520Foo%2520%253D%2520(function()%257B%250A%2520%2520%2522use%2520strict%2522%253B%250A%2520%2520function%2520Foo()%257B%257D%250A%250A%2520%2520return%2520Foo%253B%250A%257D)()%253B) removes the `"use strict";`.
- [Uglify JS](https://skalman.github.io/UglifyJS-online/) does not.
- [Babili/babel-minify](https://babeljs.io/repl#?babili=true&browsers=&build=&builtIns=false&code_lz=FANwhgTgBAYg9nKBeKAKAZgVwHYGMAuAlnNqgJQDewUUARJgM4CmUD-EhBtA3NVFniIlYCchQC-wPhCb5MEbCLi9xZcryA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&lineWrap=false&presets=babili&prettier=false&targets=&version=6.26.0&envVersion=1.6.2) does not.
- [Prepack](https://prepack.io/repl.html) does not.

**Comment by loganfsmyth** [comment]
@dantman Nice, thanks for checking that. That's pretty much what I would have guessed. It is such an uncommon occurrence that I'm not surprised few things optimize for it.
