### ISSUE TITLE
Spec change: Tagged template literals are no longer cached globally

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7350]
Spec PR: https://github.com/tc39/ecma262/pull/890

Babel has never been able to implement a true global cache anyway, but now we can remove the file-level caching. e.g.

Currently say we have [this example](https://babeljs.io/repl/#?babili=false&browsers=chrome%20%3E%2055%20%20&build=&builtIns=false&code_lz=MYewdgzgLgBFCGBzGBeGA3VA-DBuAUPgBQBmArmMFAJbhECUA3vjHEgAYQgC2ApnL24AHADbwovdgVYJEnHvwnCxEqfgC-9BriA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)
```
const tag = v => v;

(function(){
  tag`some template`;
  tag`some template`;
})();
```
we generate
```
var _templateObject = _taggedTemplateLiteral(["some template"], ["some template"]);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var tag = function tag(v) {
  return v;
};

(function () {
  tag(_templateObject);
  tag(_templateObject);
})();
```
Note how the `_taggedTemplateLiteral` call is hoisted to the top of the function, and _both_ tagged examples reference the same `_templateObject` object.

With the current spec changes we'd at least want to change this logic to be
```
var _templateObject = _taggedTemplateLiteral(["some template"], ["some template"]);
var _templateObject2 = _taggedTemplateLiteral(["some template"], ["some template"]);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var tag = function tag(v) {
  return v;
};

(function () {
  tag(_templateObject);
  tag(_templateObject2);
})();
```
so that each template literal has its own `_templateObject`.

But now that that things aren't shared anymore, there's really no reason to hoist the initialization at all, so I'd like to see us update this to
```
var _templateObject, _templateObject2;

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var tag = function tag(v) {
  return v;
};

(function () {
  tag(_templateObject || (_templateObject = _taggedTemplateLiteral(["some template"], ["some template"])));
  tag(_templateObject2 || (_templateObject2 = _taggedTemplateLiteral(["some template"], ["some template"])));
})();
```
so we only initialize the template literal object when it is needed.

All of this should be doable in https://github.com/babel/babel/blob/dd0337cc85c341b36b0657e05964532a650fd088/packages/babel-plugin-transform-template-literals/src/index.js#L73

Marking as good first issues because it is relatively self-contained, but it will likely require some time to understand what needs to change in the AST.

**Comment by DZuz14** [comment]
I will work on this. Any chance I can chat with someone on Slack on how to proceed with this?

**Comment by loganfsmyth** [comment]
Yup! Join our slack and we can help out with any questions you have.

**Comment by DZuz14** [comment]
Will do. Ill hop on tomorrow at work. Thanks.

**Comment by bashmish** [comment]
We have a related issue here with HTML Imports https://github.com/Polymer/polymer-cli/issues/950 and a need to fix it on the Babel side in the best case.

I do understand that this is likely not Babel's responsibility to deal with such edge cases, but at the same time I ask myself: are there many cases where caching of a template literal is really helpful? Also TypeScript compiler doesn't cache and calls a helper creating a template object directly in place of it like this:

```
function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var tag = function tag(v) {
  return v;
};

(function () {
  tag( _taggedTemplateLiteral(["some template"], ["some template"]));
})();
```

My draft implementation for Babel 6 doing exactly the same is here https://github.com/babel/babel/compare/6.x...bashmish:template-literals-in-html-imports?expand=1

I can make a proper MR with fixed tests and also do the same for Babel 7, **fixing this issue as a side effect** as well.

Is there any chance to reconsider this optimisation strategy and take my (ok, TypeScript's) approach instead?

**Comment by bashmish** [comment]
Learned a lot about the underlying spec and now see how naive my previous comment was, sorry guys :D just started exploring the rationale behind transpilers implementations.

Also looked in depth at how TypeScripts implements it. Interesting read here https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#cache-tagged-template-objects-in-modules

The most confusing part is how TypeScript compiles the same code without `export`.

```
// original example for TS 2.6 changelog

export function id(x: TemplateStringsArray) {
    return x;
}

export function templateObjectFactory() {
    return id`hello world`;
}

console.log(templateObjectFactory() === templateObjectFactory()); // true in TS 2.6
```

```
// without module exports 

function id(x: TemplateStringsArray) {
    return x;
}

function templateObjectFactory() {
    return id`hello world`;
}

console.log(templateObjectFactory() === templateObjectFactory()); // still false in TS 2.6
```

I'm still trying to grasp the spec and if it somehow implicitly dictates this difference in TS behavior (or it's just a bug there), especially latest changes mentioned in the issue description https://github.com/tc39/ecma262/pull/890

**Comment by DZuz14** [comment]
Just letting anyone looking at this that I won't be working on this issue. I am instead going to take some time go get acclimated to the Babel codebase before focusing on any specific issue.  Feel free to take a whack at it.

**Comment by UtkarshGupta-CS** [comment]
@loganfsmyth I can work on this issue. Thanks

**Comment by loganfsmyth** [comment]
@UtkarshGupta-CS Go for it!

**Comment by SathishKumar140** [comment]
@UtkarshGupta-CS Are able to fix the issue? I would like to work on it.This would be my first PR.

**Comment by DanielRosenwasser** [comment]
FYI TypeScript caches in modules for simplicity, and we're planning on using the helper function as the cache map in the future. Feel free to loop me in on issues relating to this.

**Comment by loganfsmyth** [comment]
@DanielRosenwasser I'm not 100% sure you followed what I'm saying with this issue, so to clarify, the spec is changing to drop the global caching entirely in favor of per-call-site caching. Given that, I'm not sure I follow what you mean about using the helper function as a map.

**Comment by DanielRosenwasser** [comment]
Sorry, the context has sort of been lost. I just wanted to explain why we do things the way we do.

There was a comment above from @bashmish about why it's werid that TypeScript doesn't cache the template object when a file isn't a module (i.e. when you don't have imports or exports in a module). I was mainly responding to that.

The reason is that in a module, you can always ensure you have a unique variable that won't collide with anything else for a template object, but in the global scope, you're susceptible to collisions. So we kept the no-caching behavior to avoid name clashes

```ts
(function () {
  tag(__makeTemplateObject(["some template"], ["some template"]));
})();
```

as opposed to the behavior you might encounter in a module:

```ts
var _a;
(function() {
    tag(_a || (_a = __makeTemplateObject(["some template"], ["some template"])));
})();
```

I was explaining our eventual strategy for dealing with name clashes in the global scope. We were thinking of using our `makeTemplateObject` function as a map to have an easy way to reference these objects, but maybe generating a very long global identifier that's sufficiently distinguished by its contents would be good enough.

This would actually give you the old spec-compliant behavior in the global scope, with the new spec-compliant behavior in modules. I think that's good enough for most use-cases.

**Comment by jridgewell** [comment]
> I was explaining our eventual strategy for dealing with name clashes in the global scope. We were thinking of using our makeTemplateObject function as a map to have an easy way to reference these objects

Careful, that'll lead to very easy memory leak. Now any template literal in scope will cause all template literals in scope to remain in memory, even if the callsites are long GC'd.

```js
(function() {
    tag(__makeTemplateObject._a || (__makeTemplateObject._a = __makeTemplateObject(["some template"], ["some template"])));
})();

window.someExport = function() {
  return tag(__makeTemplateObject._b || (__makeTemplateObject._b = __makeTemplateObject(["long lived template"], ["long lived template"])));
};
```

Here, `_a` template will never be cleaned up (as long as `someExport` is alive).

**Comment by DanielRosenwasser** [comment]
True, thanks for pointing that out :)

**Comment by debugpai2** [comment]
I see multiple people commented that they're picking this up. Can someone confirm that they're working on it still?

**Comment by UtkarshGupta-CS** [comment]
@debugpai2 I'm working on this, I worked my way through the codebase. 
Sorry, it's taking so long. I'll post here if I'm not up for it.
