### ISSUE TITLE
Tagged Template Literal: Size Optimization

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#7352]
Just noticed with https://github.com/babel/babel/issues/7350, we're making a bunch of very long string arrays. What's more, they're (mostly) duplicated between the `strings` and `raw`.

```js
tag`some template`;
// "some template" "some template"
_taggedTemplateLiteral(["some template"], ["some template"]);
```

The only (I think) time that string arrays aren't duplicated is when an "invalid" escape sequence comes up (which are now valid, due to template literal revision).

```js
tag`test${1}\xhello`;
// "invalid" string becomes undefined
_taggedTemplateLiteral(["test", void 0], ["test", "\\xhello"]);
```

At worst, we could optimize the "all valid strings" case using slice:

```js
// default raw value to a slice of strings
function _taggedTemplateLiteral(strings, raw = strings.slice()) {
  return Object.freeze(Object.defineProperties(strings, {
    raw: { value: Object.freeze(raw) }
  }));
}

// all valid
tag`some template`;
_taggedTemplateLiteral(["some template"]);

// some invalid
tag`\xhello`;
// "invalid" string becomes undefined
_taggedTemplateLiteral([void 0], ["\\xhello"]);
```

But, realistically, we could just reuse the same string array (it's being frozen, anyways):

```js
function _taggedTemplateLiteral(strings, raw) {
  return Object.freeze(Object.defineProperties(strings, {
    raw: { value: raw ? Object.freeze(raw) : strings }
  }));
}
```

**Comment by loganfsmyth** [comment]
> Just noticed with #7350, we're gonna be making a bunch of very long string arrays.

I don't know that it'll be much difference from now size-wise since the majority of tagged templates will have different strings for each invocation.

> The only (I think) time that string arrays aren't duplicated is when an "invalid" escape sequence comes up (which are now valid, due to template literal revision).

The primary time where they aren't duplicated is when there are escapes in general, not just invalid escapes, e.g.

```
tag`hello\nworld`
```
becomes
```
_taggedTemplateLiteral(["hello\nworld"], ["hello\\nworld"]);
```
one with escaped `\` and one without.

> At worst, we could optimize the "all valid strings" case using slice:

100% agree there. If both sets of strings will be the same, just passing one array and slicing it to make a copy would be a solid optimization.

> But, realistically, we could just reuse the same string array (it's being frozen, anyways)

It has the downside that things might be caching based on object identity of the arrays. I think that would break spec compliance, so I don't think we should reused them.

**Comment by jridgewell** [comment]
> I don't know that it'll be much difference from now size-wise

That's just what caused me to notice it.

> where they aren't duplicated is when there are escapes in general, not just invalid escapes

That makes better sense.

**Comment by loganfsmyth** [comment]
> That's just what caused me to notice it.

That it'll be a big difference? If so, can you expand on how you see it changing with that issue?

**Comment by jridgewell** [comment]
> That it'll be a big difference?

No, I don't imagine #7350 will cause much difference for anyone (who includes the same template literal's text in multiple locations?). The issue's code samples are what caused me to notice it.

**Comment by loganfsmyth** [comment]
Gotcha, sounds good them.

**Comment by jridgewell** [comment]
Hi @debugpai2:

1. First we need to determine if all our `strings` and `raw` strings are equal (so basically a deep equality check on the arrays, or do the checking during the for-of loop).
2. If they're the same, we no longer need to pass `raws` to the call expression (we'll be slicing `strings` at runtime to generate it)
3. We need to modify the taggedTemplateHelpers to slice the `strings` array if `raw === undefined`.
