### ISSUE TITLE
NS_ERROR_XPC_BAD_OP_ON_WN_PROTO: Illegal operation on WrappedNative 

### ISSUE THREAD

**Issue by nickbar86** [babel/babel#7354]
File a bug.
This problem is caused in Firefox version 20.
The error is thrown by core.js  in file es6.symbol.js at line 
10583:  var D = gOPD(it, key);

```
var $getOwnPropertyDescriptor = function getOwnPropertyDescriptor(it, key) {
  it = toIObject(it);
  key = toPrimitive(key, true);
  if (it === ObjectProto && has(AllSymbols, key) && !has(OPSymbols, key)) return;
  var D = gOPD(it, key);
  if (D && has(AllSymbols, key) && !(has(it, HIDDEN) && it[HIDDEN][key])) D.enumerable = true;
  return D;
};
```
This is a blocking issue.

**Comment by loganfsmyth** [comment]
Do you mind if I ask why upgrading Firefox isn't an option? Given the age of Firefox 20, I can only assume there must be know security vulnerabilities in it at this point.

**Comment by zloirock** [comment]
It's a duplicate of https://github.com/zloirock/core-js/issues/374 and https://github.com/zloirock/core-js/issues/254, why you add it also here?
