### ISSUE TITLE
Inconsistent JSX whitespace handling

### ISSUE THREAD

**Issue by mindplay-dk** [babel/babel#7360]
It appears the whitespace handling of the JSX transform is inconsistent.

For example:

```jsx
let content = <div>
  Some inline <code>code</code> and some other
  <code>inline code</code> right here.
</div>
```

The two `<code>` tags in this example end up rendering differently - it appears the line-break before the word "other" on the first line gets discarded, while the actual spaces before/after the first code-tag, and after the second one, do get rendered.

This currently forces me to make sure I never start an inline tag at the beginning of a line of text.

Here's the output of [a fiddle](https://jsfiddle.net/mindplay/kcgg80ny/) to illustrate why whitespace is important to HTML rendering in this case:

![image](https://user-images.githubusercontent.com/103348/36027321-1b8bf7d8-0d9b-11e8-9440-09eb23cad825.png)

[Here's a fiddle demonstrating the transform problem](https://jsfiddle.net/mindplay/gbvkcq7q/).

And here's `console.log()` output from that fiddle illustrating the problem:

![image](https://user-images.githubusercontent.com/103348/36026549-e372fe58-0d97-11e8-9b39-93b9f5dfe56f.png)

While this behavior may be consistent with XML whitespace handling, it's a real problem when you're trying to render HTML where inline whitespace means something.

HTML, as far as I know, collapses whitespace-only sequences, and collapses leading/trailing serial whitespace to a single whitespace.

I also tested this with Typescript, and it does look like it's transform is identical to babel's:

```
{
	"type": "div",
	"props": null,
	"children": [
		"Some inline ",
		{
			"type": "code",
			"props": null,
			"children": [
				"code"
			]
		},
		" and some other",
		{
			"type": "code",
			"props": null,
			"children": [
				"inline code"
			]
		},
		" right here."
	]
}
```

Since the 99% use-case for JSX is rendering HTML, I'd like to suggest that both babel and Typescript ought to be consistent with HTML on this point.

---

@gaearon I wonder if the whitespace issues you mentioned in passing [here](https://github.com/babel/babel/issues/369#issuecomment-69020226) got filed/fixed?

**Comment by LucaColonnello** [comment]
Hello! I'm just joined the community on Slack and like to contribute.
I already found where this would be handled:

https://github.com/babel/babel/blob/6f3be3a5438739453510ea969136894c9cae12d8/packages/babel-helper-builder-react-jsx/src/index.js#L84

This strips out all the spaces after any new line.

**It should be easy as replace with 1 single space space instead of empty, only if there are other characters (to prevent printing every new line without text as a new text node with just a space).**

Can I claim it and give it a go?

Thanks!

**Comment by LucaColonnello** [comment]
@gaearon do you have any time to comment on this one? It would be very much appreciated to get some input from a React team member.

I hope you can help us :)

**Comment by nicolo-ribaudo** [comment]
This is correct. If https://github.com/facebook/jsx/issues/19 is revised, we can reopen this issue.
