### ISSUE TITLE
Where is the best place to see which JS functions are not transpiled by Babel?

### ISSUE THREAD

**Issue by joetidee** [babel/babel#7361]
Where is the best place to see which JS functions are not transpiled by Babel?

**Comment by hzoo** [comment]
> JS functions

Can you be specific what you mean here? I can't tell if you mean syntax or something like Array.prototype.includes which you would use a polyfill for: https://babeljs.io/docs/usage/polyfill/

**Comment by joetidee** [comment]
So, just asking if there is a quick reference page to see which syntax / functions are supported by Babel.

**Comment by hzoo** [comment]
I'll just say again that Babel doesn't compile any functions, and babel-polyfill is just core-js which you can import manually and lookup here: https://github.com/zloirock/core-js.
