### ISSUE TITLE
Float32Arrays seems to getting much slower after loading babel polyfills

### ISSUE THREAD

**Issue by vlajos** [babel/babel#7362]
I noticed that PIXI.js's webgl implementation is much slower with loaded babel polyfills.
* http://lavela.hu/sp/d.html Without babel
* http://lavela.hu/sp/d2.html With babel.

I guess all the PIXI stuff is not really important. Maybe the flame graphs from the related pixi bug ticket: https://github.com/pixijs/pixi.js/issues/4662

(On Firefox I did not notice this problem, just on Chrome.)

### Input Code

I think internally PIXI does something like this:
  WebGLGraphicsData.prototype.upload = function upload() {
    this.glPoints = new Float32Array(this.points);
...
In my profiled cases points contains 320k float numbers.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

Nothing? Or default?

### Expected Behavior

Normal speed.

### Current Behavior

Roughly 100x slower operations.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel-polyfill            |  6.2.26
| Pixi.js          | 4.7.0
| Chrome             |  63.x
| OS | Debian Linux(sid) and different Windows versions.

**Comment by hzoo** [comment]
Hmm interesting! This would mostly be an issue for https://github.com/zloirock/core-js since that's more or less what babel-polyfill is

**Comment by vlajos** [comment]
@hzoo Should I recreate the bug there?

**Comment by zloirock** [comment]
Interesting. Please, open an issue in the `core-js` repo.

**Comment by zloirock** [comment]
`core-js` does not replace/wrap typed array constructor in this case, but theoretically, it can be deoptimized in V8 because of adding some additional properties.

**Comment by vlajos** [comment]
Thanks. Done: https://github.com/zloirock/core-js/issues/377
