### ISSUE TITLE
Combine multiple files into one

### ISSUE THREAD

**Issue by ygoe** [babel/babel#7367]
I'm trying to replace uglify-es with babel to make use of newer JavaScript features. uglify cannot convert ES6+ to ES5 so it's not suitable for browsers in the wild. From what I've read, babel can transpile ES6+ to ES5. And now it can also minify the code, which is what I'm looking for.

uglify can process multiple input files and generate a single output file. Single output files are important because loading each file takes extra time in the browser/network. And HTTP/2 isn't widely used either.

After all, minifying and bundling is only useful for web pages (no need for server apps), and IE 11 is still widely used and supported by Microsoft, so I don't really see the point in delivering ES6 to browsers.

I've tried installing babel-minify as global npm package and run it like this: `babel-minify source1.js source2.js source3.js` But it gives me an error message "TypeError: outputDir is falsy. Got "undefined"" which seems totally unrelated. So unfortunetely it isn't helpful and I have to ask here.

How can I transpile, bundle and minify multiple source files into one? I can't just concatenate the source files before passing them to babel because I'll also need proper source maps for the end result.

I don't have a Slack account, StackOverflow doesn't like my support questions and the linked Discourse forum is not available anymore, that's why the only place I can ask is here.

**Comment by Andarist** [comment]
You are looking for a bundler - depending on your needs I'd recommend looking into rollup or webpack.

**Comment by ygoe** [comment]
Thank you, rollup seems to work for me. I had to reorganise my source files for modules instead of plain text including, but it's maybe even a bit better now. It introduces yet another tool though.

webpack is unusable for me. I couldn't find a good explanation of how to use it, then it generated a large pile of something from my tiny example and the result didn't even work.

**Comment by existentialism** [comment]
Closing this as there isn't anything actionable on Babel's side!
