### ISSUE TITLE
[Feature Request] Mathematical comparison

### ISSUE THREAD

**Issue by BrodaNoel** [babel/babel#7368]
Hi guys!
Is there a way to create a plugin or whatever (maybe add it as a feature?) to be able to make this "mathematical" comparison:

```js
const a = 2;
const b = 2;

// here the important
if (a === b === 2) {
}
// meaning:
if (a === b && a === 2) {
}

// and another similar feature:
const x = 10;
if (8 < x < 12) {
}
// meaning
if (x > 8 && x < 12) {
}
```

**Comment by Andarist** [comment]
It is possible to create a plugin doing such transformation, as those conditions are parseable. Babel is focused only on standard syntax & proposals though, so this won't be included in any of our official plugins.

This should not be too hard to create though, you could learn a little bit about AST transformations done by babel to create your own custom plugin doing this. If you'd have any questions regarding this you can join our slack to ask for some guidance.
