### ISSUE TITLE
object-rest-spread doesn't prevent prototype mutation via a __proto__ property

### ISSUE THREAD

**Issue by mgol** [babel/babel#7382]
Choose one: is this a bug report or feature request?

A bug report.

### Input Code

```js
var o = Object.create(null);
o.a = 'foo';
o.__proto__ = [];
var o2 = {...o};
console.log(Array.isArray(Object.getPrototypeOf(o2))); // true, expected: false
```

See [this test case](https://babeljs.io/repl/#?babili=false&browsers=IE%2011&build=&builtIns=false&code_lz=G4QwTgBA9hC8EHkBGArApgYwC4DoNjRCzQAoA7AVwBsqBKAbgChGocQ4IByAMyik6asA-kIAOYKFigiOAbQC6TRqEhQAjB2TpsbAM66AlgHMyJAN4BfADTQGzFdABMHMzjdQLSjFDK6oVNBwqKCMSTnUIcUkYcDAQAE8AfggSNAAPUUxiABMALggsMAo0Wk4bAEEwOPicA11K6pItLJwjNCwABQkpLHjMhG4SdVoRpm9ff0Dg0PDnKKkIWITk1IystDyIbhAqXRKyiAaE2vqqhKbUFrbO7sk-tAGhxxG7IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=stage-3%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2).

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

N/A, see the REPL link (basically, you need the `proposal-object-rest-spread` transform enabled).

### Expected Behavior

You should see `true` & `false` logged as it behaves when invoked directly in a Chrome/Firefox console.

### Current Behavior

If you open a console, you'll see `true` logged twice but it should be logged only for `o1`. If you paste this code directly in a browser console it prints `true` & `false`.

This is because object spread is desugared by Babel to a bare `Object.assign` which behaves differently: `Object.assign` invokes property setters and object spread shouldn't (see https://github.com/tc39/proposal-object-rest-spread/blob/master/Issues.md#setters for an example).

### Possible Solution

A custom modified implementation of `Object.assign` that changes regular assignment:
```js
target[key] = source[key];
```
should be changed to one that invokes `Object.setProperty`:
```js
Object.defineProperty(target, key, {value: source[key]});
```

### Context

I was merging default options values with one received from a user via `Object.assign` with `Object.create(null))` as the first parameter (see https://github.com/angular/preboot/pull/71). It has been pointed out that I could change the implementation to use regular objects with object spread but since the code is transpiled I can't do it (this particular repo uses TypeScript but you may easily imagine a pure-JS scenario).

### Your Environment

N/A, the REPL example says it all.

**Comment by mgol** [comment]
May be related to #6735 although I'm not sure if it's exactly the same.

**Comment by jridgewell** [comment]
This is unrelated to #6735.

**Comment by jridgewell** [comment]
Whaaaaaaat. @littledan: Is there a reason they are different?

@mgol: Are you interested in tackling this one? We'll need to add an `extendsSpec` helper, that doesn't use `Object.assign`, and does `Object.defineProperty` (but with `enumerable`, `writable`, and `configurable` all `true`).

**Comment by Andarist** [comment]
There is already PR with this - https://github.com/babel/babel/pull/7034

**Comment by littledan** [comment]
@jridgewell Yes, it was a deliberate design decision to use own properties and DefineProperty rather than Set in object spread. See [this commit](https://github.com/tc39/proposal-object-rest-spread/commit/7acb89a127b6a967f33a6a0b988da92d0bc5e07f) and the [meeting notes](http://tc39.github.io/tc39-notes/2014-09_sept-25.html#58-object-rest-destructuring-and-spread-properties) that led to it.

**Comment by Andarist** [comment]
While we are at this edge case. Is there a reasonable explanation for this?
```js
var o = Object.create(null)
o.__proto__ = []
Object.getOwnPropertyDescriptors(o) // {}
Object.getOwnPropertyDescriptor(o, '__proto__') // {value: Array(0), writable: true, enumerable: true, configurable: true}
```

**Comment by Kovensky** [comment]
That sounds like a (hilarious?) spec bug.

`__proto__` is a setter/getter in `Object.prototype`, so `o.__proto__ = []` correctly created a data property. It doesn't show up in the result of `getOwnPropertyDescriptors`, though, because when the property key `__proto__` is set in the result, it ends up invoking the setter.

`Object.getPrototypeOf(Object.getOwnPropertyDescriptors(o)) === o.__proto__` 😆

**Comment by Kovensky** [comment]
It looks even more fun in Firefox:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/73085/36253009-b5e84348-1289-11e8-89f0-017751aeb0c8.png">

**Comment by Andarist** [comment]
Yeah, I've checked FF too 😂

**Comment by littledan** [comment]
It sounds like you're talking about devtools, rather than V8. You can file a devtools bug at https://bugs.chromium.org/p/chromium/issues/entry using the Platform>DevTools>JavaScript component
