### ISSUE TITLE
--preserve-symlinks option breaks babel-node

### ISSUE THREAD

**Issue by machineghost** [babel/babel#7384]
### Input Code
babel-node  --preserve-symlinks

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

.babelrc

{
      "plugins": [
        [
          "module-resolver",
          {
            "alias": { "~": "./" },
            "cwd": "babelrc",
            "symlinks": true,
            "transformFunctions": ["proxyquire", "resolvePath"]
          }
        ],
        "transform-class-properties",
        "transform-decorators-legacy",
        "transform-es2015-destructuring",
        "transform-object-rest-spread"
      ],
      "presets": ["es2015"],
      "ignore": ["node_modules"]
    }

### Expected Behavior

Babel-node should work just like Node (only with transpiling), presumably by passing `--preserve-symlinks` along to Node behind the scenes

### Current Behavior

>  error: unknown option `--preserve-symlinks'

### Possible Solution
Add it to a "passed through options list" of some sort

### Context
babel-node wasn't transpiling a file that was inside a symlink, and I had hoped that using this option would fix things.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 8.9.4
| npm              | 5.6.0
| Operating System |  Linux
| Other Babel Packages |

    "babel-loader": "^7.1.2",
    "babel-plugin-module-resolver": "^3.0.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.18.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-destructuring": "^6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.16.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-node": "^5.1.1",

**Comment by khanghoang** [comment]
@machineghost I have the same issue. I'm working on a PR to support this https://github.com/babel/babel/pull/7739. Stay tuned.
