### ISSUE TITLE
Feature: transform function calls to match arity

### ISSUE THREAD

**Issue by dbkaplun** [babel/babel#7396]
Matching function call arity with function definition results in a significant speedup in V8. See http://mrale.ph/blog/2018/02/03/maybe-you-dont-need-rust-to-speed-up-your-js.html#profiling-the-pure-javascript-version:
> It turns out that ArgumentsAdaptorTrampoline is V8 mechanism for coping with JavaScript’s variadic calling convention: e.g. you can call function that has 3 parameters with 2 arguments - in which case the third parameter will be filled with undefined. V8 does this by creating a new frame on the stack, copying arguments down and then invoking the target function:
>
> [omitted]
>
> While such costs might be negligable for cold code, in the sort code comparator was invocated millions of times which made overheads of arguments adaptation quite pronounced.

It would be nice if this functionality was available to Babel, perhaps opt-in behind a flag.

**Comment by hzoo** [comment]
That would be cool (I saw it too), and thought of this a long time ago but it doesn't really match how Babel works atm. It operates per file, so you would need to make sure that all call sites change the arity? What functions are we transforming? Seems better as a lint rule in that sense.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since, as explained by @hzoo, there is currently no way for Babel to know how many parameters a function expects.
