### ISSUE TITLE
suggestion: Add README to `babel` package

### ISSUE THREAD

**Issue by aikar** [babel/babel#7399]
re: https://www.npmjs.com/package/babel

Suggesting addition of a readme to this package, explaining the deprecation and where users should go.

This page is the first result (At least for me) on google, as well as a lot of people will end up going directly there. So would be good for some information to be shown.

**Comment by xtuc** [comment]
The Babel package isn't deprecated, I believe it was never used? 

Maybe we can just link to our website. Would you mind doing a PR for that?

**Comment by hzoo** [comment]
It's the v6 version, we don't update it anymore and haven't published a version of v6 in a long time.

I was planning on doing something for v7 though.

**Comment by aikar** [comment]
@xtuc from the npm metadata:
```  deprecated: 'In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers' }```

**Comment by xtuc** [comment]
Yes that's correct, sorry.

**Comment by hzoo** [comment]
npm shows the deprecation message now so this works. Might reuse the package later as well.
