### ISSUE TITLE
`defaults` browserslist query breaks preset-env

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#7405]
Bug.

`@babel/preset-env` does not work correctly when the browserslist query is `defaults` (a valid query). The result is that most of the expected transforms don't happen. It doesn't matter if the browserslist string is set via `package.json` `browserslist` field, or directly in `targets.browsers`.

### Input Code

```js
const test = () => ''
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "browsers": ["defaults"]
        }
      }
    ]
  ]
}
```

### Expected Behavior

```js
var test = function test() {
  return ''
}
```

### Current Behavior

```js
const test = () => ''
```

### Context

Unfortunately the [default behavior for `@babel/preset-env`](https://github.com/babel/babel/tree/master/packages/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest) if you do not provide targets or set a browserslist query is to replicate `@babel/preset-latest`. I want to transpile to the browserslist default/recommended level of browser support, without having to manually copy and paste whatever their default query is, which may change.

If you set `targets.browsers` to what `defaults` represents (`['> 0.5%', 'last 2 versions', 'Firefox ESR', 'not dead']`) then the output is correct. This means it is a bug with `@babel/preset-env` using the `defaults` browserslist query; not the actual transpilation.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40
| node             | 9.5.0
| npm              | 5.6.0
| Operating System | macOS

**Comment by Arfey** [comment]
In my case
```
"devDependencies": {
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1"
  }
```
with your environment, for

```
"browsers": ['> 0.5%', 'last 2 versions', 'Firefox ESR', 'not dead']
```
and 
```
"browsers": ["defaults"]
```
returned equal results

```
var test = function test() {
  return '';
};
```
Is your issue still relevant?

**Comment by hzoo** [comment]
Can you make sure you aren't using the `babel-` packages/ 6.x ones? I think you could run https://github.com/babel/babel-upgrade with `npx babel-upgrade` to remove them.

**Comment by existentialism** [comment]
@jaydenseric thanks for the report. this should be do-able, but we'll need to rework a few things, as we're [overwriting](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/targets-parser.js#L126) browserslists `defaults` in a few cases. will add to the TODO list!

**Comment by ScottRudiger** [comment]
@jaydenseric thanks for pointing out this issue.
I experienced the same issue in webpack with:
```javascript
...
plugins: ['@babel/plugin-transform-runtime'],
presets: [
  ['@babel/preset-env', {
    modules: false,
    targets: {
      node: 'current',
      browsers: ['defaults', 'not ie <= 10'],
    },
  }],
...
```
If you'd like details on another instance of the bug, see #7567.

**Comment by alexturpin** [comment]
Just ran into this issue while upgrading from Babel 6 to 7. Was working fine in version 6!
