### ISSUE TITLE
Release new version of babylon

### ISSUE THREAD

**Issue by xixixao** [babel/babel#7410]
Can we push a new version of babylon to npm, so that we can support JSX fragments in `jscodeshift`?

cc @hzoo 

Thanks!

**Comment by hzoo** [comment]
I'm confused? Babylon supported it a long time ago so you just need to update

**Comment by hzoo** [comment]
We released this in beta.30 https://github.com/babel/babylon/releases/tag/v7.0.0-beta.30 at least but you should use the latest

**Comment by xixixao** [comment]
Hey @hzoo, I guess I don't know how to install it. If I look at npm: https://www.npmjs.com/package/babylon the latest version is 6.18.0. The same version is reported here: https://github.com/babel/babel/blob/master/packages/README.md . `yarn upgrade --latest babylon` also leaves me at 6.18.0

**Comment by loganfsmyth** [comment]
Since it is still in beta, you'd have to install the version explicitly. `latest` is still the current stable release, which is in the 6.x range.

**Comment by xixixao** [comment]
Thanks @loganfsmyth, makes sense.

**Comment by xixixao** [comment]
@hzoo We bumped jscodeshift and recast, jscodeshift now has
```
"babylon": "7.0.0-beta.30"
```
in its package.json,

but when I add `jscodeshift`, its `node_modules` includes version `"7.0.0-beta.40"`, and it's `lib` code doesn't actually include the changes for support fragments.
