### ISSUE TITLE
babel-preset-env - how to disable node target for browser-only (.browserslistrc)

### ISSUE THREAD

**Issue by niftylettuce** [babel/babel#7414]
I have the following `.babelrc` file and am using `@babel` 8.x+ packages.

```js
{
  "env": {
    "server": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "useBuiltIns": "usage",
            "targets": {
              "browser": false
            }
          }
        ]
      ]
    },
    "client": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "useBuiltIns": "usage",
            "targets": {
              "node": false
            }
          }
        ]
      ]
    }
  },
  "plugins": [
    "lodash",
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-object-rest-spread"
  ],
  "compact": false
}
```

My `BABEL_ENV` when compiling for browser bundle is `BABEL_ENV=client`.

How can I manually toggle on/off compilation for either node or browser, and for browser/client-only, how can I make it read `.browserslistrc` automatically?

Related to https://github.com/babel/babel/issues/6607

**Comment by niftylettuce** [comment]
Here is my `.browserslistrc` file contents - I'd prefer to have it specified here than as a string passed to `.babelrc` option.

```sh
last 2 versions
ie >= 9
```

**Comment by thymikee** [comment]
As mentioned in the [docs](https://babeljs.io/docs/usage/babelrc/#env-option), you should rather set your `NODE_ENV` instead of `BABEL_ENV`, since the former will be used in case the later is missing.

**Comment by niftylettuce** [comment]
@thymikee I'm specifically asking how to disable the node target and enable only browsers target with Booleans without having to manually specify and have to repeat myself and re-use the same lines from browserslistrc.

**Comment by thymikee** [comment]
Oh, then I'm not in the position to answer if that's currently possible.

**Comment by Andarist** [comment]
According to [README](https://github.com/babel/babel/tree/master/packages/babel-preset-env#browserslist-support) those files are supported, although support for it might have been added recently. Which version of babel@7 r u using?

**Comment by niftylettuce** [comment]
Babel 8.x+ and the @babel/preset-env etc.

**Comment by niftylettuce** [comment]
```
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.40",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/runtime": "^7.0.0-beta.40",
```

**Comment by Andarist** [comment]
You'd have to check if in your opinion your config is correct according to rules described [here](https://github.com/babel/babel/tree/master/packages/babel-preset-env#targets-merging). If you believe your config should work after reading that section, it would be super nice if you could prepare a simple sample repository with the issue reproduced so I could debug it more quickly.
