### ISSUE TITLE
BUG: Array.prototye.includes poyfill broken?

### ISSUE THREAD

**Issue by cvlmtg** [babel/babel#7419]
Choose one: is this a bug report or feature request?

bug report

### Input Code

this happens on IE11

![schermata 2018-02-23 alle 10 33 20](https://user-images.githubusercontent.com/6401008/36587291-01eaf474-1885-11e8-98c5-6ed76c139614.png)

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

we are bundling our app with browserify/babelify and the following config specified inside package.json

```js
  "browserify": {
    "transform": [
      [
        "babelify", {
          "presets": [
            [ "env", { "targets": { "ie": 11, "ios": 8 }, "useBuiltIns": true } ],
            "stage-1",
            "react"
          ],
          "plugins": [ "external-helpers" ]
        }
      ],
      [ "envify", { "global": true } ]
    ]
  },
```

### Expected Behavior

`[].includes()` should return the correct result

### Current Behavior

`[].includes()` seems to always return false

### Your Environment

| software         | version(s)
| ---------------- | -------
| node             |  6.12.2
| npm              |  3.10.10
| Operating System | macOS 10.13.3

    "babel-plugin-external-helpers": "^6.22.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babelify": "^8.0.0",
    "babelify-external-helpers": "^1.1.0",
    "browserify": "^16.1.0",

**Comment by zloirock** [comment]
![image](https://user-images.githubusercontent.com/2213682/36592944-5b3efefe-18ca-11e8-9235-c03c60b9a0ed.png)
That defenitly not `core-js` version of `Array#includes`, so seems you also load an incorrect alternative `Array#includes` polyfill.
