### ISSUE TITLE
 table

### ISSUE THREAD

**Issue by danielwalczak** [babel/babel#7420]
Choose one: is this a bug report or feature request?

### Input Code

```js
var your => (code) => here;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by existentialism** [comment]
@danielwalczak this looks empty? closing for now, but feel free to open another issue!
