### ISSUE TITLE
Env target Node 9.5 fails with object spread?

### ISSUE THREAD

**Issue by reggi** [babel/babel#7426]
I'm using node 9.5, this code runs perfectly fine.

```js
const v = {'meow': true}
const x = () => () => ({...v})

console.log(x)
```

If I'm using babel to transpile it and it's breaking.

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAGwgEwIYGcAWcBmUIhwDkSaWRAUBQMYQB268AbnALxwDeRIAphAO5EAXHBhQArjwC-NeozgAPNnAAUASjYA-VRtbaVHAHTGmUtVVoMICHoaQBzFQrVA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=env&prettier=false&targets=Node-9.5&version=6.26.0&envVersion=1.6.2

**Comment by existentialism** [comment]
@reggi you need to add and enable `babel-plugin-syntax-object-rest-spread`, even though you don't need to transform it, our parser needs to understand it.

**Comment by reggi** [comment]
@existentialism I was under the assumption that if something was _in_ node, that it would be _in_ babel `env` as a default. After all, isn't it the job of `babel-preset-env` to take code a build for a given target? If the authoring code is a later verison of node (9.5.0) it would build for 4.0.0 if that was the current target. But to say that babel doesn't understand node 9.5.0 natively is odd.

**Comment by nicolo-ribaudo** [comment]
Things used to be added to preset-env when they are included in the ECMAScript standard, not when they are implemented.
In version 7, there is a `shippedProposals` option that enables proposals that are already implement in node/browsers.

**Comment by reggi** [comment]
@nicolo-ribaudo Thanks for the clarification, I had no clue about `shippedProposals`. This looks like a doup of https://github.com/babel/babel/issues/6970 closing.

**Comment by reggi** [comment]
Anyone looking for a fix:


```json
{
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40"
  },
  "babel": {
    "presets": [
      [
        "@babel/env",
        {
          "targets": {
            "node": "current"
          },
          "shippedProposals": true
        }
      ]
    ]
  }
}
```
