### ISSUE TITLE
babel-preset-env: enable es2018 features by default

### ISSUE THREAD

**Issue by frenzzy** [babel/babel#7430]
[ECMAScript 2018 was finalized](http://2ality.com/2017/02/ecmascript-2018.html), what do we need to enable these features by default for `preset-env`?

```bash
SyntaxError: /path/to/file.js:
Support for the experimental syntax 'objectRestSpread' isn't currently enabled (11:9):

  10 |       {
> 11 |         ...example,
     |         ^
  12 |         key: 'value',
  13 |       },
```

The `proposal` keyword was removed from `@babel/plugin-syntax-object-rest-spread` package name but `babel-preset-env/data/plugins.json` still have:

https://github.com/babel/babel/blob/6f3be3a5438739453510ea969136894c9cae12d8/packages/babel-preset-env/data/plugins.json#L232

**Comment by reggi** [comment]
Had the same issue: Duplicates here:
https://github.com/babel/babel/issues/7426
https://github.com/babel/babel/issues/6970

**Comment by existentialism** [comment]
I have a PR for ES2018 in @babel/preset-env nearly finished... will publish soon.

**Comment by JacquesBonet** [comment]
I have always he problem, and its 3 april 2018.

I don't understand how the spread operator is not by  default on babel 7.

Its quite like the "import" for node (but its another problem.

Spread operator is a core operator for ES6, it must be by default on.

**Comment by existentialism** [comment]
> and its 3 april 2018

Sorry we aren't moving at the pace you'd like (remember, we're a purely volunteer effort!).

It's not always obvious, but there are many moving pieces going on... namely, I was holding off until we had solidified how we were going handle the process of transitioning `plugin-proposal-*` -> `plugin-transform-*`; as well as some awesome work by @zloirock upgrading to core-js@3.

That said, I published in the meantime, since I agree... we should get this out there :)

**Comment by JacquesBonet** [comment]
Sorry for my abrupt observation which don't take account all the works you are doing.

**Comment by michaelwclark** [comment]
@JacquesBonet I'd also like to point out that spread is core to ES6...but for arrays... ES2018 is introducing Object Spread which is different. 

@existentialism  Is there a contribution guide, docs, slack, etc? I'd like to volunteer some time on babel. You guys have been doing great things for the community. I'd like to help that continue.

**Comment by existentialism** [comment]
@michaelwclark there is all of the above! check out the README in the repo root for links!
