### ISSUE TITLE
Figure out the status of function name binding verification in the parser

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7432]
In https://github.com/babel/babel/pull/7431/files#diff-fca1cacaed72b5d331b53e0a5d46503cR1681 I commented out a broken check, but we should figure out what changes need to be made to re-enable it properly.

**Comment by ksashikumar** [comment]
I will work on this bug! 😃

**Comment by aminmarashi** [comment]
@loganfsmyth Seems like this issue is already resolved.

**Comment by loganfsmyth** [comment]
Yup!
