### ISSUE TITLE
package.json missing "main" entry for @babel/types.

### ISSUE THREAD

**Issue by Rohit-L** [babel/babel#7437]
[Bug Report]

When I install `npm install @babel/types`, I am unable to `require('@babel/types')`. Looking in the `node_modules/@babel/types` and inspecting the `package.json`, I see that it's missing the `'main'` (the reason I'm not able to require it in node) field, and I'm not sure why.

```
{
  "_args": [
    [
      "@babel/types@7.0.0-beta.40",
      "/root/test"
    ]
  ],
  "_from": "@babel/types@7.0.0-beta.40",
  "_id": "@babel/types@7.0.0-beta.40",
  "_inBundle": false,
  "_integrity": "sha512-uXCGCzTgMZxcSUzutCPtZmXbVC+cvENgS2e0tRuhn+Y1hZnMb8IHP0Trq7Q2MB/eFmG5pKrAeTIUfQIe5kA4Tg==",
  "_location": "/@babel/types",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@babel/types@7.0.0-beta.40",
    "name": "@babel/types",
    "escapedName": "@babel%2ftypes",
    "scope": "@babel",
    "rawSpec": "7.0.0-beta.40",
    "saveSpec": null,
    "fetchSpec": "7.0.0-beta.40"
  },
  "_requiredBy": [
    "/",
    "/@babel/generator",
    "/@babel/helper-function-name",
    "/@babel/helper-get-function-arity",
    "/@babel/template",
    "/@babel/traverse"
  ],
  "_resolved": "https://registry.npmjs.org/@babel/types/-/types-7.0.0-beta.40.tgz",
  "_shrinkwrap": null,
  "_spec": "7.0.0-beta.40",
  "_where": "/root/test",
  "bundleDependencies": [],
  "dependencies": {
    "esutils": "2.0.2",
    "lodash": "4.17.5",
    "to-fast-properties": "2.0.0"
  },
  "devDependencies": {},
  "name": "@babel/types",
  "optionalDependencies": {},
  "version": "7.0.0-beta.40"
}
```

My own `package.json` looks like so:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/types": "^7.0.0-beta.40"
  }
}
```

| node             | 9.3.0
| npm              | 5.6.0
| Operating System | ubuntu 14.04

**Comment by Andarist** [comment]
That's quite weird as this package has ["main"](https://github.com/babel/babel/blob/cb4f4f4d5f84135133bdef4ffa762d6969dad8a6/packages/babel-types/package.json#L9). Could you try reinstalling?

**Comment by Rohit-L** [comment]
Yes, I've delated my `node_modules` folder, `package-lock.json` and even `.npm` folder and did a clean `npm install` from my project root. Unfortunately, that didn't seem to do it either.

**Comment by thymikee** [comment]
Downloaded locally but cannot repro. `"main"` field is there, along with `lib/index.js` file present.
Yarn:
<img width="615" alt="screen shot 2018-02-27 at 18 21 04" src="https://user-images.githubusercontent.com/5106466/36743640-054d579c-1beb-11e8-809c-05d95a3fbd08.png">
npm:
<img width="606" alt="screen shot 2018-02-27 at 18 23 21" src="https://user-images.githubusercontent.com/5106466/36743752-53adb008-1beb-11e8-9869-40cefd9410ca.png">

This is probably something with your local npm installation, not related to Babel project.

**Comment by Andarist** [comment]
@Rohit-L without being able to reproduce the issue we are not unfortunately able to help you, I'd suggest investigating your machine - is your setup special in any way? have you tried it on another machine?

Closing as not actionable on our side.

**Comment by Andarist** [comment]
And ofc thanks @thymikee for checking this one!
