### ISSUE TITLE
Strange array and semi-colon bug

### ISSUE THREAD

**Issue by davidnormo** [babel/babel#7440]
Can be replicated in the REPL (v6.26.0):

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBAhhC8EG8C-AoUkBGdGvRAxtsigNpQA0G5-AugHQBmA9gE4CiU-AFgBQ8CUcAHw5-KIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

In summary, it seems semi-colons aren't being inserted properly and also parens added inside of array declarations.

Input
```
let x = []
[1,2,3].forEach
```

Output
```
var x = [][(1, 2, 3)].forEach; // Cannot read property 'forEach' of undefined
```

Expected
```
var x = [];[1, 2, 3].forEach
```

**Comment by xtuc** [comment]
That's not a bug. A semi-colon is required in that case.

It's defined in the [automatic-semicolon-insertion spec](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-rules-of-automatic-semicolon-insertion).

**Comment by davidnormo** [comment]
Oh.

Ok thanks, sorry for wasting your time!
