### ISSUE TITLE
Usability issue: @babel/preset-env ignores errors in targets spec

### ISSUE THREAD

**Issue by joliss** [babel/babel#7445]
@babel/preset-env silently ignores errors in the `targets` spec in several places ([sample repo to run this](https://github.com/joliss/babel-preset-env-issue)):

```js
        targets: {
          browsers: 59, // silently ignored
          // browsers: "invalid123", // this fails however
          invalid123: "invalid123" // silently ignored
        }
```

```js
        targets: "invalid123" // silently ignored
```

When it encounters such invalid targets, babel-preset-env seems to fall back to some ES3-type baseline target.

Ignoring `browsers: 59` seems to be intentional ([test case](https://github.com/babel/babel/blob/f0049726253178d7d97c6790f03b35628eee86f4/packages/babel-preset-env/test/targets-parser.spec.js#L67)), though I'm not sure why.

This seems like a usability issue to me: When I was trying to figure out on my project whether preset-env did anything at all, my first instinct was to put some invalid strings in there, and I was very confused when nothing changed. I even accidentally misspelled "browsers" at one point. 

I think preset-env should throw an error (ideally) or a warning (if throwing an error is not possible for some reason).

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.40
| node             | 9.5.0
| npm              | 5.6.0
| Operating System | Linux

**Comment by vadim-ch** [comment]
I would like to do this

**Comment by hzoo** [comment]
Ahh ok. Yeah we can totally do something like this, in the meantime I had added a `debug` option earlier which does try to log what plugins are being run.

**Comment by existentialism** [comment]
@vadim-ch it's yours, let us know if you have any questions!

**Comment by vadim-ch** [comment]
@existentialism i need help.

`browsers: 59, // there really is not enough warning`
`invalid123: "invalid123" // behavior seems correct`

**Comment by existentialism** [comment]
@vadim-ch you'll want to update the [targets parser](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/targets-parser.js) to:

1. validate `options.targets` (and update the `Targets` flow type)
1. throw if browserslist query is not valid (right now it sets it to null if not)
1. add/update tests

**Comment by vadim-ch** [comment]
@existentialism I understand it. Question is how to check the non-valid `option.target`? To check this, I need to have a list of valid parameters

**Comment by existentialism** [comment]
iirc, should be:

`node | browsers | chrome | opera | edge | firefox | safari | ie | ios | android | electron`
