### ISSUE TITLE
Bug in wrapNativeSuper: Cannot assign to read only property 'constructor' of object

### ISSUE THREAD

**Issue by zerkalica** [babel/babel#7447]
Class, extended from Error class, throws exception in runtime in strict mode. Bug demo: https://github.com/zerkalica/babel-bug-demo

Configs:

package.json:
```
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-es2015": "^7.0.0-beta.40"
  }
```

.babelrc:
```
{
    "presets": [["@babel/es2015", {"loose": true}]]
}
```

Source:

index.js:
```js
'use strict';
class MyError extends Error {}
```

Steps to reproduce:

1. babel index.js > index-out.js
2. Copy-paste index-out.js content to browser console and run.

Result:

``` subClass.prototype.constructor = subClass ``` in inheritLoos helper throws error:

```
Uncaught TypeError: Cannot assign to read only property 'constructor' of object 'Error'
    at _inheritsLoose (app.js:41)
    at eval (eval at _wrapNativeSuper$1 (app.js:1809), <anonymous>:18:3)
    at eval (eval at _wrapNativeSuper$1 (app.js:1809), <anonymous>:25:2)
    at _wrapNativeSuper$1 (app.js:1809)
    at app.js:1862
    at app.js:11039
_inheritsLoose @ app.js:41
(anonymous) @ VM3290:18
(anonymous) @ VM3290:25
_wrapNativeSuper @ app.js:1809
(anonymous) @ app.js:1862
(anonymous) @ app.js:11039
```

Reproduced on Ubuntu linux, Chrome 64.0.3282.186 

PS: I don't need thick native class wrapper (i use tiny custom hack), but i can't disable it in https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-classes/src/loose.js. May be add some option to disable wrapNativeSuper or disable it in loose mode?

PPS: Bug appears only in strict mode.

**Comment by nicolo-ribaudo** [comment]
I can't reproduce the issue :thinking: 

![schermata da 2018-02-28 18-48-49](https://user-images.githubusercontent.com/7000710/36803547-20d27844-1cb8-11e8-9cb1-8d04241b9872.png)

**Comment by zerkalica** [comment]
Sorry, i forgot to add 'use strict' in my example. Bug works only in strict mode.
![result](https://raw.githubusercontent.com/zerkalica/babel-bug-demo/master/result.png)
