### ISSUE TITLE
undefined is not a function (evaluating 'rules[targetField].split('|')[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()') babel

### ISSUE THREAD

**Issue by aprilmintacpineda** [babel/babel#7448]
### Input Code
https://github.com/aprilmintacpineda/smart-input-validator/blob/28511f855c01b61df36927798bc062dab01f0076/src/index.js

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [ "env" ],
  "plugins": [ "babel-plugin-transform-object-rest-spread" ]
}
```

### Expected Behavior
No errors should be encountered.

### Current Behavior
throwing the error.

### Context
The tests run completely without failing. I assume it works on web or NodeJS that's why the tests did not show the error. I used the library with a mobile. On iOS emulator, I did not encounter the error, but on an android emulator with lollipop 5.1, I did.

It is related to `for-of` as seen here:

__raw:__ https://github.com/aprilmintacpineda/smart-input-validator/blob/28511f855c01b61df36927798bc062dab01f0076/src/index.js#L19
__build:__ https://github.com/aprilmintacpineda/smart-input-validator/blob/28511f855c01b61df36927798bc062dab01f0076/build/index.js#L43

I replaced the `for-of` with a regular for loop as seen here:

__raw:__ https://github.com/aprilmintacpineda/smart-input-validator/blob/1.1.5/src/index.js#L20
__build:__ https://github.com/aprilmintacpineda/smart-input-validator/blob/1.1.5/build/index.js#L39

and the error went away.

### Your Environment

Android Emulator: Android Lollipop 5.1. I also tried it with `API 27` and the error persisted.
babel-cli^6.26.0
babel-loader7.1.3
babel-plugin-transform-object-rest-spread^6.26.0
babel-preset-env^1.6.1

You can clone the repo here:

`1.1.5`: uses `for-loop` https://github.com/aprilmintacpineda/smart-input-validator/tree/1.1.5
`1.1.3`: uses `for-of` https://github.com/aprilmintacpineda/smart-input-validator/tree/1.1.3

**Comment by aprilmintacpineda** [comment]
I saw `transform-es2015-for-of` and thought I need to use it. So I did and the error still persisted.

see https://github.com/aprilmintacpineda/smart-input-validator/tree/46a82e282c9b02b7df19b6f0aef3cc6b01a37931

```
undefined is not a function (evaluating 'rules[targetField].split('|')[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
<unknown>
    index.delta?platform=android&dev=true&minify=false:61061:122
validator
    index.delta?platform=android&dev=true&minify=false:61054:34
email
    index.delta?platform=android&dev=true&minify=false:60923:46
default
    index.delta?platform=android&dev=true&minify=false:60903:40
default
    index.delta?platform=android&dev=true&minify=false:61433:76
default
    index.delta?platform=android&dev=true&minify=false:60806:38
combination
    index.delta?platform=android&dev=true&minify=false:60556:38
dispatch
    index.delta?platform=android&dev=true&minify=false:60263:38
<unknown>
    index.delta?platform=android&dev=true&minify=false:60015:13
<unknown>
    index.delta?platform=android&dev=true&minify=false:67344:28
<unknown>
    index.delta?platform=android&dev=true&minify=false:60595:22
onChangeText
    index.delta?platform=android&dev=true&minify=false:74285:53
onChangeText
    index.delta?platform=android&dev=true&minify=false:75571:45
_onChange
    index.delta?platform=android&dev=true&minify=false:56791:57
_invokeGuardedCallback
    index.delta?platform=android&dev=true&minify=false:2777:21
invokeGuardedCallback
    index.delta?platform=android&dev=true&minify=false:2739:39
invokeGuardedCallbackAndCatchFirstError
    index.delta?platform=android&dev=true&minify=false:2742:54
executeDispatch
    index.delta?platform=android&dev=true&minify=false:2982:64
executeDispatchesInOrder
    index.delta?platform=android&dev=true&minify=false:3002:26
executeDispatchesAndRelease
    index.delta?platform=android&dev=true&minify=false:3097:35
executeDispatchesAndReleaseTopLevel
    index.delta?platform=android&dev=true&minify=false:3110:43
forEachAccumulated
    index.delta?platform=android&dev=true&minify=false:3089:18
processEventQueue
    index.delta?platform=android&dev=true&minify=false:3200:29
runEventQueueInBatch
    index.delta?platform=android&dev=true&minify=false:4126:26
handleTopLevel
    index.delta?platform=android&dev=true&minify=false:4131:29
<unknown>
    index.delta?platform=android&dev=true&minify=false:4194:25
batchedUpdates
    index.delta?platform=android&dev=true&minify=false:10558:22
batchedUpdates
    index.delta?platform=android&dev=true&minify=false:4110:37
_receiveRootNodeIDEvent
    index.delta?platform=android&dev=true&minify=false:4193:23
receiveEvent
    index.delta?platform=android&dev=true&minify=false:4199:32
__callFunction
    index.delta?platform=android&dev=true&minify=false:2364:49
<unknown>
    index.delta?platform=android&dev=true&minify=false:2134:31
__guardSafe
    index.delta?platform=android&dev=true&minify=false:2326:13
callFunctionReturnFlushedQueue
    index.delta?platform=android&dev=true&minify=false:2133:21
```

**Comment by loganfsmyth** [comment]
You're likely missing `babel-polyfill`, which would support `Symbol.iterator` for you.
