### ISSUE TITLE
Failed to package with env preset: Cannot find module './_shared-key'

### ISSUE THREAD

**Issue by ddombrowsky** [babel/babel#7456]
Choose one: is this a bug report or feature request?  **Bug**

### Input Code

After running `electron-forge package`, I see these errors:

```
⠹ Compiling ApplicationFailed to compile file: /tmp/electron-packager/linux-x64/x64/resources/app/src/evusb.html
Cannot find module './_shared-key' (While processing preset: "/tmp/electron-packager/linux-x64/x64/resources/app/node_modules/babel-preset-env/lib/index.js")
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

There is no special configuration.  Only defaults that come with installing `babel-preset-env`.
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |      "babel-preset-env": "^1.6.1",
| node             |     node: '8.9.4',
| npm              |   npm: '5.6.0',
| Operating System | linux-x64

**Comment by loganfsmyth** [comment]
To me that sounds like something didn't fully install properly. Maybe delete node_modules and try again?

**Comment by ddombrowsky** [comment]
I've reinstalled node modules multiple times.    Guess it's just me.  

Wouldn't surprise me.  I have a tendency to find these edge cases that no one else has.
