### ISSUE TITLE
@babel/plugin-transform-runtime emits "require" instead of "import" when input has no import/export statements

### ISSUE THREAD

**Issue by joliss** [babel/babel#7464]
`@babel/plugin-transform-runtime` can be used to produce ES modules with `import` statements (`import _getIterator from ...`). But whenever the input source contains no `import` or `export` statements, it will emit `require` calls instead (`var _getIterator = require(...)`);

### Issue description

I'm using Babel with `@babel/plugin-transform-runtime` to produce output that is ES5 compatible but can be fed into Rollup; in other words, the output only uses ES5 syntax, except for ES6 `import`/`export` statements.

The `transform-runtime` plugin is capable of emitting `import` statements, but it seems to use some problematic auto-detection logic that causes it to insert CommonJS `require` calls if the input contains no `import` or `export` statements. (You can use the code below to reproduce this behavior.)

It is rare but possible for ES modules to contain no `import` or `export` statements; examples are empty modules or modules that are imported only for their side-effects.

I'd therefore like to argue that this auto-detection logic is harmful: In an ES module environment, it will *seem* to work most of the time, but then suddenly if one of your modules contains no `import` or `export` statement, things will break because `transform-runtime` inserts a `require` call. So if we don't know for certain whether we are expecting CommonJS or ES modules, I'd like to suggest that it's better to throw an error than try to auto-detect.

#### Root cause

The behavior seems to be implemented in `@babel/helper-module-imports`; possibly [is-module.js](https://github.com/babel/babel/blob/master/packages/babel-helper-module-imports/src/is-module.js) is the culprit.

`@babel/helper-module-imports` is used by not only `@babel/plugin-transform-runtime`, but also `@babel/plugin-transform-async-to-generator` and `@babel/helper-module-transforms`, which might therefore suffer from a similar issue.

### Code to reproduce

```sh
yarn add @babel/core @babel/preset-env @babel/plugin-transform-runtime
```

```js
let babel = require("@babel/core");

function showImport(s) {
  let code = babel.transform(s, {
    babelrc: false,
    sourceType: "module",
    presets: [
      [
        "@babel/preset-env",
        {
          targets: {
            browsers: "since 2012"
          },
          modules: false
        }
      ]
    ],
    plugins: [
      [
        "@babel/plugin-transform-runtime",
        {
          useESModules: true
        }
      ]
    ]
  }).code;

  console.log(code.match(/^.*@babel\/runtime.*/)[0]);
}

// prints: import _getIterator from "@babel/runtime/core-js/get-iterator";
showImport(`
  import "foo";
  for (let a of b) { }
`);

// prints: var _getIterator = require("@babel/runtime/core-js/get-iterator");
showImport(`
  for (let a of b) { }
`);
```

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40
| node             | 9.5.0
| npm              | 5.6.0
| Operating System | Linux

**Comment by loganfsmyth** [comment]
This should be fixed in our next beta release now that https://github.com/babel/babel/pull/7417 has landed.
