### ISSUE TITLE
Figure out why core and cli dropped in coverage

### ISSUE THREAD

**Issue by danez** [babel/babel#7478]
In #7455 the coverage of `core`, `cli` and `register` dropped a little bit https://codecov.io/gh/babel/babel/compare/fdfbd9a6f787f13f1674e9b6836b94413e632470...e417be4e436eb7a7cfc4b6e3146a0c895a4f62ef/changes

`babel-register` dropped because all its tests are currently deactivated (will be handled in #7477)

We should figure out why it happened for `core` and `cli`.

**Comment by danez** [comment]
This i because all the tests which spawn child processes (babel-cli, babel-node, babel) do not count against coverage anymore. Currently there is no way in jest to do this out of the box, maybe we can come up with a workaround. I leave it open for now

https://github.com/facebook/jest/issues/3190

**Comment by shellscape** [comment]
I'm watching this issue and the mentioned jest issue with a keen eye. The workaround mentioned by disabling jest reporting and wrapping with nyc does work, but it's god-awful ugly. Please do update this issue should you find another way around this.

**Comment by danez** [comment]
Closing as we now know why it happened and can't really do anything about it.
