### ISSUE TITLE
Pipeline operator doesnt await properly

### ISSUE THREAD

**Issue by dacz** [babel/babel#7480]
`await` in pipeline doesn't translate to working code as described in specs.

### Input Code
```js
const f1 = async x => x + 1;
const f2 = async x => Promise.resolve(x + 1);

// this is ok
const runOk = async () =>
  5 |> async(_) => await f1(_) |> async (_) => await f2(_);

runOk().then(v => console.log('runOk returns:', v));

// this will not await fir the results
const runFail = async () =>
  5 |> await f1 |> await f2;

runFail().then(v => console.log('runFail returns:', v))
```
[repl](https://babeljs.io/repl#?babili=false&browsers=ie%2010&build=&builtIns=usage&code_lz=MYewdgzgLgBAZgRhgXhgQwgTzMGAPFAPnxgGoYEBuAKFEljgCYV0scTliAFAJxAFsAlhACmAOh4iIIADYA3EQAoC5BAEoa1APRaYUABbCYRkAGta4aDB4BXMAHlTLDNlyK1RajBgBWGAB9iFxxFAH0PTnQAdzRBBgQwj0DWVxhEomjYhkZEzVsHU3cxAxEwRTkMumkZcRkQAHNFAHJ8x2sRKBseSAAuJoAaGDk1DWptXQMjIzAQWDMLems7ADFYmWc2NwjCL18AoJi4-CRktEPsvJW1opKyisiq2VqG5vzVwXXJTu6IPsHhtRjahAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=stage-0&prettier=false&targets=&version=7.0.0-beta.39&envVersion=)

babel v7.0.0.-beta39

### Expected Behavior
translates to 
```
...
return _ref2 = (_3 = 5, (await f1)(_3)), (await f2)(_ref2);
...
```

should translate to

```
return _ref2 = (_3 = 5, (await f1(_3)), await f2(_ref2);
```

**Comment by mAAdhaTTah** [comment]
I'd be happy to take a look at this after we land #7458.

**Comment by nicolo-ribaudo** [comment]
This will be fixed by https://github.com/babel/babel/pull/7154

**Comment by dacz** [comment]
@nicolo-ribaudo thanks. Do you have any idea when it will be released? You requested changes in #7154 in Jan and it is kind of stalled since then and with conflicts with master.

**Comment by mAAdhaTTah** [comment]
So we're going to ban `await` in the basic, "minimal proposal" spec here: https://github.com/tc39/proposal-pipeline-operator/pull/108 and solve `await` in each of the proposals we're working on currently working on. This is not going to be the final semantics of pipeline in any of the proposals, given the ambiguity between whether `x |> await f` becomes `await f(x)` or `(await f)(x)`.

**Comment by mAAdhaTTah** [comment]
Yes, although not "probably"; those two different plugins are in progress already, representing two different proposals for the pipeline operator. We're doing this to solicit feedback from the community on them.

**Comment by mAAdhaTTah** [comment]
Edit: Excuse me, one babel plugin, flags for the various "modes".

**Comment by mAAdhaTTah** [comment]
I believe we can close this, as we banned `await` in the minimal and are working on implementing await properly in each of the proposals.

**Comment by js-choi** [comment]
I dunno; maybe it’d be good to keep it open until we finish actually implementing it in them. It’s “in progress”, at least. But either way is probably fine.

**Comment by thiagoarrais** [comment]
Given the current incarnation of the proposals, I think this may be closed with a WONTFIX.

IIRC, this input code is a syntax error both in `smart` as in `f#`:

```javascript
 5 |> await f1 |> await f2;
```
And if we put parentheses around the `await` clause, f# will translate it to:

```javascript
return _ref2 = (_3 = 5, (await f1)(_3)), (await f2)(_ref2);
```
Which doesn't seem to be the intention of the OP.
