### ISSUE TITLE
Unexpected change of Math operators: - to +

### ISSUE THREAD

**Issue by marvinhagemeister** [babel/babel#7488]
Choose one: is this a bug report or feature request? Bug

### Input Code

Repo where the bug can be reproduced: https://github.com/marvinhagemeister/babel-bug-export

```js
export let diffLevel = 0;

export function diff() {
  if (!--diffLevel) {
    console.log("hey");
  }
}

diff();
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/env",
      {
        "loose": true,
        "targets": {
          "browsers": ["last 2 versions", "IE >= 9"]
        }
      }
    ]
  ]
}
```

### Expected Behavior

```js
if (!(exports.diffLevel = diffLevel = diffLevel - 1)) {
```

### Current Behavior

```js
if (!(exports.diffLevel = diffLevel = diffLevel + 1)) { // note the `+ 1` instead of `- 1`
```

### Context

Currently trying to upgrade preact's toolchain to `babel 7` for jsx-fragment support: https://github.com/developit/preact/pull/879

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.40 
| Babylon          | 
| node             | 9.4.0
| npm              | yarn 1.5.1
| Operating System | MacOS High Sierra

**Comment by nicolo-ribaudo** [comment]
As a workarounnd you can use
```js
export let diffLevel = 0;

export function diff() {
  if (!(diffLevel -= 1)) {
    console.log("hey");
  }
}

diff();
```

**Comment by marvinhagemeister** [comment]
@nicolo-ribaudo Gave that ago since the fix is really trivial, but I cannot get the tests to work :/
