### ISSUE TITLE
unpacking optimisations

### ISSUE THREAD

**Issue by simonzack** [babel/babel#749]
The following code:

    let [x, y] = [w, x];

could be optimized to:

    var y = x;
    var x = w;

when the lengths are fixed.

It's currently compiled to:

    var _ref = [w, x];

    var x = _ref[0];
    var y = _ref[1];

Temporary variables are needed for `let [x, y] = [y, x]`.

I don't know if this problem has a name, but I've thought of a simple algorithm. We can represent each pair (x, w) (y, x) in the first case as edges on a digraph, and a value is "taken" once we go from one node to another. The graph is composed of cycles and paths. For cycles, we can just assign in the reverse direction, and have a temporary variable. For paths, we can do the same, without temporary variables. This gives at most `n/2` extra assignments (where we only have 2-cycles, i.e. swaps) and `1` temporary variable (shared), and a O(n) algorithm.

I don't know whether this conflicts with the "readability" criteria, though. But imho the generated code should be readable enough.

**Comment by sebmck** [comment]
> I don't know if this problem has a name, but I've thought of a simple algorithm. We can represent each pair (x, w) (y, x) in the first case as edges on a digraph, and a value is "taken" once we go from one node to another. The graph is composed of cycles and paths. For cycles, we can just assign in the reverse direction, and have a temporary variable. For paths, we can do the same, without temporary variables. This gives at most n/2 extra assignments (where we only have 2-cycles, i.e. swaps) and 1 temporary variable (shared), and a O(n) algorithm.

I'm not quite sure what this means but I can just add some logic that will unpack the right side of a destructuring assignment differently if it's an `ArrayExpression`.

**Comment by simonzack** [comment]
Hmm I didn't get the algorithm right anyway, the graph's a bit more complicated than I thought.

**Comment by simonzack** [comment]
I think I should try my hand at implementing this, where should it belong, is 6to5/lib/6to5/transformation/transformers/ the right place?

**Comment by sebmck** [comment]
`lib/6to5/transformation/transformers/es6/destructuring.js` `Destructuring.prototype.pushArrayPattern`

**Comment by sebmck** [comment]
Rewrote most of the destructuring transformer, now takes into account both of those edge cases and more.

**Comment by ooflorent** [comment]
Awesome! :+1:
