### ISSUE TITLE
Internal: making tests run faster

### ISSUE THREAD

**Issue by hzoo** [babel/babel#7497]
A lot of things to look into/have changed that may of resulted in this

- Adding Node 9 (do we have to test against this?)
- Switching to jest - is it slower or faster?
  - It's nice that it splits by test so we can check the slow tests
- cli tests are really slow (can we consolidate, or mock)
- we added preset-env
- we added babylon
- we have babel-standalonee/env webpack build
  -is it possible to just use `@babel/core` and merge standalone api into it so we don't have to build it out? With the new repl we would be able to get new deps? Although not sure how it works in regards to per PR builds/artifacts.
- investigate not running or only running certain tests if only certain files change. (although we tried multiple times to not run if it was only a markdown change but that had so many issues for us earlier)

**Comment by ksashikumar** [comment]
Can we try jest's workers to parallelize the test suite? 
I could see we have [`--runInBand`](https://facebook.github.io/jest/docs/en/cli.html#runinband) flag in `scripts/test.sh`.

**Comment by danez** [comment]
I think jest recommends running tests serially because Travis boxes are very weak. But we can try and see if it changes anything.

One thing I haven't figured out is why sometimes the tests run for 30mins on Travis and sometimes 8 minutes although it is the same job.

**Comment by danez** [comment]
Travis also currently has degraded performance reported for linux container builds on there status page.
<img width="980" alt="screen shot 2018-03-06 at 00 20 50" src="https://user-images.githubusercontent.com/231804/37005448-650f3a4a-20d4-11e8-9659-aac98f2e3517.png">
