### ISSUE TITLE
preset-env with shippedProposals does not load builtIn 'Symbol.asyncIterator'

### ISSUE THREAD

**Issue by yaelhe** [babel/babel#7505]
Choose one: is this a bug report or feature request? Bug

Looks like shippedProposals is not loading a polyfill for Symbol.asyncIterator. I got errors on Safari 11 & IE 11.
It worked when I imported the polyfill:
`import 'core-js/modules/es7.symbol.async-iterator';`

### Input Code

```js
const iterate = async () => {
  for await(const chunk of asyncIterable()) {
    console.log(chunk);
  }
};
async function* asyncIterable() {
  yield await Promise.resolve(1);
  yield await Promise.resolve(2);
}
iterate();
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["@babel/preset-env",
    {
      "shippedProposals": true,
      "debug": true,
      "useBuiltIns": "usage",
      "targets": {
        "browsers": [
          "last 2 versions"
        ]
      }
    }]
  ]
}
```

### Expected Behavior

should console log
```
1
2
```
### Current Behavior

Safari 11: `Unhandled Promise Rejection: TypeError: iterable[Symbol.iterator] is not a function. (In 'iterable[Symbol.iterator]()', 'iterable[Symbol.iterator]' is undefined)`
IE 11: `Unhandled promise rejection TypeError: Object doesn't support property or method 'Symbol(Symbol.iterator)_5.8jkmimeocnj'`
### Possible Solution

preset-env with shippedProposals and useBuiltins- usage, does not add es7.symbol.async-iterator module.
I think it should be here: https://github.com/babel/babel/blob/5d615dd1983817952cce103ab05b0b6bb174d915/packages/babel-preset-env/data/shipped-proposals.js#L4
I can submit a PR, if this is indeed the problem :)

### Context

Being able to run async iteration on all supported browsers with preset-env, shippedProposals and useBuiltins-usage.
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40
| Babylon          | 
| node             | v8.9.2
| npm              | 5.5.1
| Operating System | OSX

**Comment by existentialism** [comment]
> I can submit a PR, if this is indeed the problem :)

@yaelhe sure! I believe we can just map it to "Asynchronous Iterators".
