### ISSUE TITLE
Babylon: plugins option should support '*'

### ISSUE THREAD

**Issue by hax** [babel/babel#7508]
Babylon 6 used to support `{plugins: ['*']}` to denote all plugins. It stopped working in Babylon 7.

### Expected Behavior

Allow use `*` to denote all plugins except `estree`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babylon          | 7

**Comment by loganfsmyth** [comment]
We've added a `babel.parse` function in Babel 7.x, so you can parse code by using the same plugins people have enabled in their `.babelrc`. Is that a valid solution in your case?

The reason we removed `*` is that various plugins can conflict. Do you want `flow` or `typescript` for instance? We can't enable both. Do you want `decorators` or `decorators2`? They are also incompatible.

**Comment by hax** [comment]
As the maitainer of https://github.com/hax/js-refactor , which is a atom plugin provide the function of renaming bindings when you edit js files, what I expect is a way to enable all possible official plugins so we can support any new js syntax when I upgrade to new babylon version, without looking into babylon README or code to find whether there is new plugin and add it to my own plugin list.

> The reason we removed * is that various plugins can conflict. Do you want flow or typescript for instance? We can't enable both. Do you want decorators or decorators2? They are also incompatible.

I see the conflict.

Could we just use `flow` as default if enable both is impossible, (but I think `flow` should have a `/* @flow */` in the top, so if no such code we can enable `typescript`, can we?) and use `decorator2` as default.

Another choice is just leave all conflict plugins, so I could use `plugins: ['*', 'flow', 'decorator2']`. I need  to look into Babylon README to check whether there is new conflict plugin, but I suppose it's rarely happen.

Thank you.

**Comment by loganfsmyth** [comment]
We could consider expose the list of available plugins, and you can copy it and filter it to remove the ones you don't want. Then it would be up to you to avoid introducing incompatibilities?

**Comment by hax** [comment]
That's great! Thank you.

**Comment by loganfsmyth** [comment]
Thinking on that more though, there's be a high risk of breaking changes, so it would be up to you to make sure you're locked to a specific Babylon version. Like if we add a new plugin and it conflicts with another one, it'd potentially break your code if Babylon just updated in a normal semver range, since adding a new plugin is not a major-version change.

**Comment by hax** [comment]
@loganfsmyth Yeah, it seems I need a "safe" plugin list. Is that add too much burden on babylon side?
