### ISSUE TITLE
function.name not working on minification

### ISSUE THREAD

**Issue by klintmane** [babel/babel#7509]
_* Not providing any environment/config info, because this persists on the online REPL as well._

## Code snippet
```js
const myFunctions = [
  function hello() {
    return "hello";
  },
  function world() {
    return "world";
  }
]

const myResults = myFunctions.reduce((fns, fn) => {
  return {
    ...fns,
    [fn.name]: fn()
  }
}, {});

console.log(myResults);
```

## Expected behavior
The result of the code snippet above should be:
```js
{ hello: "hello", world: "world" }
```

## Current behavior
The result is correct when transpiling. If we minify during tranpilation, the result is:
```
{ "": "world" }
```

**Comment by nicolo-ribaudo** [comment]
@klintmane I'm moving this issue to the minifier repository.

@babel-bot Move to babel/minify
