### ISSUE TITLE
Why babel-types so large

### ISSUE THREAD

**Issue by axetroy** [babel/babel#7512]
Choose one: is this a bug report or feature request?

- [x] Question

### Input Code

```js
import {
  File,
  Program,
  Identifier,
  RegExpLiteral,
  StringLiteral,
  NumericLiteral,
  BooleanLiteral,
  IfStatement,
  EmptyStatement,
  BlockStatement,
  WithStatement,
  DebuggerStatement,
  LabeledStatement,
  BreakStatement,
  ContinueStatement,
  ReturnStatement,
  VariableDeclaration,
  isFunctionDeclaration,
  isVariableDeclaration,
  VariableDeclarator,
  FunctionDeclaration,
  ExpressionStatement,
  ForStatement,
  ForInStatement,
  DoWhileStatement,
  WhileStatement,
  CatchClause,
  ThrowStatement,
  TryStatement,
  SwitchStatement,
  SwitchCase,
  UpdateExpression,
  ThisExpression,
  ArrayExpression,
  ObjectExpression,
  FunctionExpression,
  BinaryExpression,
  UnaryExpression,
  CallExpression,
  MemberExpression,
  AssignmentExpression,
  LogicalExpression,
  ConditionalExpression,
  NewExpression,
  ArrowFunctionExpression,
  TemplateLiteral,
  Node,
  TemplateElement,
  ClassDeclaration,
  ClassMethod,
  ClassProperty,
  LVal,
  Super,
  SpreadElement,
  ObjectProperty,
  isIdentifier,
  isObjectPattern,
  isObjectProperty,
  isArrayPattern,
  isArrayExpression,
  isObjectExpression,
  isMemberExpression,
  isSpreadElement,
  isObjectMethod,
  isSpreadProperty,
  isSuper,
  isClassMethod,
  isClassProperty
} from "babel-types";
```

I am build a lib with ``babylon`` and ``babel-types``, pack them up with webpack

All I need is ``validator`` from ``babel-types``

But why it so large.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

None

### Expected Behavior

Webpack should pack it with tree-shaking.

All I need is ``validator`` from ``babel-types``

But it pack them all.

### Current Behavior

After Webpack build.

``babel-types`` take **123.3K**, It seem all the code have been pack in bundle even that I didn't import.

Is it package's code design problem? I am pretty sure Webpack's tree shaking have work

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  none
| Babylon          | 6.18.0
| node             | v8.9.4
| npm              | 5.7.1
| Operating System | MacOS

**Comment by loganfsmyth** [comment]
Maybe you'd want to explore https://github.com/indutny/webpack-common-shake ? We don't publish Babel in ESM, so Webpack's normal tree shaking is not something that will work.

**Comment by axetroy** [comment]
@loganfsmyth 
I have load ``webpack-common-shake `` as plugin, but It don't work.

Because when I require ``babel-types``, All the code have run(in used).

So ``tree-shaking`` will found that code have been used. It will not be remove.

I am develop a lib which run in client side, using ``babel-types``. But unfortunately, I have load all ``babel-types``'s package even I only use few method.

**Comment by loganfsmyth** [comment]
It may just be that our package is not compatible with what `webpack-common-shake` is looking for then.

Optimizing for bundle size isn't really a goal we have currently, so I don't think it is something we'd be likely to get to any time soon.
