### ISSUE TITLE
6.22.1 miss 'babel-runtime/helpers/typeof' ?

### ISSUE THREAD

**Issue by listingzhao** [babel/babel#7514]
Error like 
`Module not found: Error: Can't resolve 'babel-runtime/helpers/typeof' `

package.json

"babel-core": "^6.22.1",
"babel-loader": "^7.1.1",
"babel-plugin-transform-runtime": "^6.22.0",
"babel-preset-env": "^1.3.2",
"babel-preset-stage-2": "^6.22.0"

**Comment by loganfsmyth** [comment]
If you're using `babel-plugin-transform-runtime`, you also need to install `babel-runtime`. It sounds like you haven't.

**Comment by listingzhao** [comment]
Error like
```ERROR in ./src/js/lib/jquery.SuperSlide.js
Module not found: Error: Can't resolve 'babel-runtime/helpers/typeof' in '/Users/xavier/Documents/projects/webpack-seed/src/js/lib'
 @ ./src/js/lib/jquery.SuperSlide.js 1:0-51
 @ multi jquery slide
```


my jquery.SuperSlide.js


```
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define(['jquery'], factory)
  } else if (typeof exports === 'object') {
    // Node, CommonJS-like
    module.exports = factory(require('jquery'))
  } else {
    // Browser globals (root is window)
    root.CityPicker = factory(root.jQuery)
  }
})(this, function(a = jQuery) {
  function SuperSlide() {}
  a.fn.slide = function(b) {}

  //    exposed constructor
  return SuperSlide
}),
  (jQuery.easing.jswing = jQuery.easing.swing),
  jQuery.extend(jQuery.easing, {})
```


webpack.base.conf.js


```
module: {
 rules: [{
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      }]
}
```

.babelrc file:

```
{
  "plugins": ["transform-runtime"]
}
```

**Comment by loganfsmyth** [comment]
Do you have `webpack-seed/node_modules/babel-runtime`? It really sounds like you didn't install it.

**Comment by listingzhao** [comment]
@loganfsmyth I'm sorry, brother, this is not a problem for Babel, because my webpack write wrong configuration.

`
resolve: {
modules: [srcDir, nodeModPath]
}
`
