### ISSUE TITLE
Should we leave the module transform enabled by default for `env` and `es2015` in 7.x?

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7517]
@TheLarkInn asked, and it seems like a discussion worth having. 

Leaving it off by default would lead to people being more likely to get errors in things like Node by default, but it would potentially make the workflow easier for people using Webpack, since it's usually easier to add additional plugins than it is to remove them, since opting out first is more verbose, so people could do

```
{
  presets: ['@babel/env'],
  env: {
    test: {
      plugins: ['@babel/transform-modules-commonjs'],
    }
  }
}
```
which is a lot nicer than 

```
{
  presets: [['@babel/env', { modules: false }]],
  env: {
    test: {
      plugins: ['@babel/transform-modules-commonjs'],
    }
  }
}
```
or even 
```
{
  presets: [['@babel/env', { modules: false }]],
  env: {
    test: {
      presets: ['@babel/env'],
    }
  }
}
```
at least in my view?

**Comment by Andarist** [comment]
In general I like this because having to use `modules: false` confuse people a lot and many misconfigure it without noticing. 

OTOH it's kinda a weird exception for this case, maybe it's a matter of perspective - what is the lowest "baseline" that plugins need to consider? If we include es2015/env preset we are supposed to get es5 code, but actually CJS is not an es5 thing - it's a module format. So maybe it's ok to leave modules out of those presets? 🤔 

OYAH (on yet another hand 😄) with the new API for inspecting configuration before loading it, it will be trivial and fail-proof for babel-loader to use it and actually warn people about misconfiguration. In the same way that rollup-plugin-babel does it, only now it won't have to implement some weirdo hoops to detect what transforms are used.

**Comment by probablyup** [comment]
I'd personally leave it off and enable it in Babel 8. We have at least a year to go until usage of ESM-capable node versions are widespread.

**Comment by xtuc** [comment]
I think that Babel-loader is the perfect place for that kind of logic since exclusively used by Webpack. 

We can force `off` for specific versions of Webpack (don't remember which exactly)

**Comment by theJian** [comment]
Will it be a pain for people who write code targeted to node?

**Comment by loganfsmyth** [comment]
Personally I feel like I'm leaning toward leaving it on by default as a general case, but exposing the ability for presets to get information about the utility that called Babel, so `preset-env` could explicitly leave the module transform disabled when running via babel-loader or any other tool that decides to enable some flag. e.g.

```
const caller = {
  name: "babel-loader",
  supportsImport: true,
  supportsDynamicImport: true,
};

// ...

babel.transform(code, { caller /* ... */ })
```

thoughts?

We could for instance expose this to presets as

```
module.exports = function(){ 
  return {
    overrides: [{
      test: (filename, caller) => caller.supportsImport,
      plugins: [
        transformModulesCommonJS,
      ],
    }],
  };
};
```

the nice thing there is that then you could always have preset-env skip that if there was a `modules` module passed in still, so anyone could still say `modules: "commonjs"` and the preset could just have the `test` return `true` or something.

**Comment by SimenB** [comment]
I like that last idea. We get a lot of issues on Jest with people having `modules: false` in their config, and getting syntax errors when running their tests with Jest.
And if and when we do support ESM, there'd be no change for the people using Jest to take advantage of it.

**Comment by xtuc** [comment]
Thanks @SimenB that's a good input.

Good idea Logan, we could call it the environment the caller sounds a bit confusing to me. That should ideally be hidden from the user? Also it seems to force the user using the js version. 

Another idea could be to pass a forbidden configuration from the host/environment (babel-loader or jest) and strongly assert against what the user configured.

**Comment by Andarist** [comment]
@loganfsmyth wouldnt `loadOptions` (or how the API was called) be enough for tools to achieve the same result? A tool could `loadOptions` before transforming and optionally warn user or manipulate those and get the job done. Kinda feeling like that your "caller" proposal duplicates ways of doing the same, which ofc increases API surface - which is already huge.

**Comment by loganfsmyth** [comment]
@xtuc 

> Good idea Logan, we could call it the environment the caller sounds a bit confusing to me.

I worry that `environment` is already pretty overloaded since we've already got `envName`, `env`, and `preset-env`. I'm definitely open to other names though.

> That should ideally be hidden from the user?

Yes it would be a programmatic-only option, so not available in config files. It would be up to babel-loader and such to just ignore if it the user passed it in as a babel-loader option or something.

**Comment by loganfsmyth** [comment]
@Andarist 

> Wouldnt loadOptions (or how the API was called) be enough for tools to achieve the same result?

Personally I'm 100% against tooling aggressively manipulating the config that users have specified. The only reason `loadOptions` exists as far as I'm concerned is that it existed historically because it demonstrated usefulness for building cache keys for fully loaded configs. I'd love to delete it entirely, but there isn't a good replacement for it yet, and at this point we're not really trying to do that for 7.x.

Given that, there's only `babel.loadPartialConfig` and I very purposefully made that API _only_ process the user config and _not_ flatten presets, because I don't think we should encourage tooling that calls Babel to manipulate configuration at that level.

I think tooling should be free to:

* Add extra plugins
* Perform validation on the config as the user specified it
* Replace a preset/plugin with another equivalent preset/plugin

The `loadPartialConfig` API allows removal and such because it felt unnecessarily aggressive to disallow other operations, but I don't think it's are a good idea to manipulate too much. As far as I'm concerned, once a plugin is added, it should be there permanently, or else we're confusing user expectations a lot by having them specifying config that doesn't actually get used.

I'd also add that if it were the responsibility of `babel-loader` to strip out the `modules-commonjs` plugin, there'd be no way for users to force-enable it in their config, say if they want to specifically enable it with options that Webpack's own implementation doesn't handle, like the `lazy` option.

**Comment by loganfsmyth** [comment]
@Andarist Gotcha, I guess we could use `loadPartialConfig` and then check if `preset-env` is loaded with `modules: false`.

Since `loadPartialConfig` doesn't flatten the presets into plugin lists, there's no way to explicitly look for `modules-commonjs` in the list, so we'd be hard-coding a list of presets that we essentially know expose a given API. It also means that if there are third-party presets that wrap `env` we lose the ability to give meaningful warnings to users, which seems less than ideal to me.

If people feel strongly about going to warning route, we can still pretty easily make preset-env warn instead of auto-removing the CommonJS, even with the `caller` approach.

**Comment by the-spyke** [comment]
I like the idea that `env` preset will use module transformation only if the `environment` (webpack/browser/node/etc) needs it. But, of course, it should be overridable in the config. Modules aren't really different to, lets say arrow functions.

But if Webpack team suggest to turn off module transformation by default, maybe it time for them to deal with the `__WEBPACK_IMPORTED_MODULE_` problem 😅

**Comment by loganfsmyth** [comment]
Once https://github.com/babel/babel-loader/pull/660 lands, this should be fully resolved.
