### ISSUE TITLE
babylon typescript error: cast + assignment

### ISSUE THREAD

**Issue by cruzdanilo** [babel/babel#7521]
### Input Code
```typescript
let a: string = 'a';
(<any>a) = null;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  sourceType: 'module',
  plugins: [
    'typescript',
  ],
}
```

### Expected Behavior
no error

### Current Behavior
```
 ERR ../main.ts Transformation error
SyntaxError: Invalid left-hand side in assignment expression (2:2)
```

### Possible Solution
?

### Context
i need to parse typescript to codemod it using [jscodeshift](https://github.com/facebook/jscodeshift) and [ast-types](https://github.com/benjamn/ast-types). it is already working, except for this error.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | -
| Babylon          | 7.0.0-beta.40
| node             | 9.5.0
| npm              | 5.7.1
| Operating System | macOS 10.12.6

**Comment by loganfsmyth** [comment]
Duplicate https://github.com/babel/babel/issues/7175
