### ISSUE TITLE
Babylon's `unambiguous` mode should also consider a file 'module' if it uses import.meta

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7522]
Per @jdalton's comment in https://github.com/babel/babel/commit/432a9b5092591d523ae5b1e8131038749bbc8160#commitcomment-27943829, in https://github.com/babel/babel/pull/6789 we landed `sourceType: unambiguous` that chooses a sourceType based on the actual usage of `import` or `export` within the file.

We should also consider a file `module` if it uses `import.meta`, but right now a file using it without also using `import` or `export` will be marked `script`.

The big thing here is that this will have to change the implementation I had originally. Instead of walking the AST after parsing, we should probably just change it so that during parsing, we track whether we have seen any `import` or `export` stuff.

Then instead of the current `hasModuleSyntax` from that PR, we could do

```
if (!parser.sawESM) {
  ast.program.sourceType = "script"
}
```

**Comment by jdalton** [comment]
Rock!
