### ISSUE TITLE
polyfill docs confused me!

### ISSUE THREAD

**Issue by xgqfrms-gildata** [babel/babel#7523]
# polyfill docs confused me!

https://babeljs.io/docs/usage/polyfill/

> why not show it in an easy reading steps?

## method (2 steps)

1. `import "babel-polyfill";`
2. setup `webpack.config.js`

**OR**

## method (1 steps)

1. `import "babel-polyfill";` / 1. setup `webpack.config.js`

Which are the right steps for using this `polyfill`?

**Comment by xtuc** [comment]
Are you referring to this part of the doc?

![screenshot from 2018-03-08 11-54-51](https://user-images.githubusercontent.com/1493671/37147533-86ac7e84-22c7-11e8-90a0-35bdd41ec470.png)

As you can see you have 3 alternatives for require'ing `babel-polyfill`.
I would recommend you to setting `babel-polyfill` in the entrypoints of Webpack.

**Comment by mAAdhaTTah** [comment]
@xtuc Do we want to keep that recommendation? My understanding is `babel-preset-env` won't modify the polyfills if it's imported that way.

**Comment by xtuc** [comment]
@mAAdhaTTah that's a very good point. That way ensures that it's the first thing that will be loaded, but we can't see them in `babel-preset-env`, and even worst it can add them (again)?

**Comment by xgqfrms-gildata** [comment]
Thanks for your time!

# my solution

add `import "babel-polyfill";` in my `index.js`.

![image](https://user-images.githubusercontent.com/29531779/37267169-7ff9ef06-25f9-11e8-87bf-dac9eb97241e.png)

**Comment by xtuc** [comment]
Ok, i'm closing this since it's not an issue. Feel free to send a PR to help us clarify the doc.
