### ISSUE TITLE
Object spread calls getter function in declaration after transform

### ISSUE THREAD

**Issue by Stupidism** [babel/babel#7524]
Choose one: is this a bug report or feature request?
Bug

Object spread calls getter function after transform

### Input Code

```js
const addGetter = ({ desc, textTitle, textUnit, ...rest }) => ({
   ...rest,
   textTitle: textTitle || rest.title,
   textUnit: textUnit || rest.unit,
   get desc() {
     console.warn('desc is deprecated');
     return desc;
   },
})
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

I'm using a tool like create-react-app, so the babel config is probabily https://github.com/insin/nwb/blob/master/src/config/babel.js;

### Expected Behavior

The property desc should change to a getter function that returns itself with a warning console log.
It would be called every time the property is accessed but not when it's defined.

### Current Behavior

the getter function is excuted when the property is defined.

```
function (_ref) {
  var desc = _ref.desc,
      textUnit = _ref.textUnit,
      textTitle = _ref.textTitle,
      rest = _objectWithoutProperties(_ref, ['desc', 'textUnit', 'textTitle']);

  return _extends({}, rest, {
    textTitle: textTitle || rest.title,
    textUnit: textUnit || rest.unit,
    get desc() {
      console.warn('[clarity-utils/measurementTypes]: desc is deprecated');
      return desc;
    }
  });
}
```

### Possible Solution

Don't use extend?

### Your Environment

nwb v0.21.5

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by Stupidism** [comment]
I excuted the same function in chrome and node
![image](https://user-images.githubusercontent.com/5801015/37142401-f30bc9ba-22f2-11e8-8ab3-7459729ddf40.png)
![image](https://user-images.githubusercontent.com/5801015/37142409-fa9dcf16-22f2-11e8-93f1-956b025afd5e.png)

**Comment by Kovensky** [comment]
This should be fixed by https://github.com/babel/babel/pull/7034 in babel 7

**Comment by Stupidism** [comment]
@Kovensky Thank you for quich response

**Comment by hzoo** [comment]
Going to close then, wonder if we should make a label for these kinds of issues.
