### ISSUE TITLE
Spread operator not compiled in js files

### ISSUE THREAD

**Issue by frlinw** [babel/babel#7525]
Choose one: is this a bug report or feature request?
Bug

### Input Code
in a js file

```js
let test = {
  bonjour: "hello"
}
let mapping = {
  ...test
}
```

### Babel/Babylon Configuration (.babelrc)

```js
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "useBuiltIns": "usage"
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-object-rest-spread"]
  ]
}
```

### Webpack config
```js
{
  // ....
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: "vue-loader",
        options: {
          extractCSS: false
        }
      },
      {
        test: /\.js$/,
        include: [ `${rootPath}/src` ],
        loader: "babel-loader"
      },
    ]
  }
}
```

### Expected Behavior
spread operator shouldn't throw error

### Current Behavior
spread operator throw an error

### Context
Spread & rest operator don't throw error if used in a .vue file but if used in a .js file, it throws:
```
Module parse failed: Unexpected token (49:4)
You may need an appropriate loader to handle this file type.
|   }
|   let mapping = {
|     ...test
|   }
|
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/private/notification/NotificationList.vue 10:41-72
```
I don't know if it's a webpack or babel issue or if it's because of my conf...

### Your Environment
Webpack 3.11

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40
| node             | 8.9.x
| npm              | 5.5
| Operating System |  windows / linux

**Comment by rajzshkr** [comment]
Can you update babel-loader config as follow and check.

```
{
      test: /\.js$/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env'],
          plugins: [require('@babel/plugin-proposal-object-rest-spread')]
        }
      }
    }
```

**Comment by nicolo-ribaudo** [comment]
Can you write some invalid code in your `.babelrc`, to check if it is correctly loaded?

**Comment by frlinw** [comment]
@nicolo-ribaudo I already tried to remove rest-spread plugin from .babelrc and it break spread operator in my .vue files. So .babelrc seems to be loaded, it compiles rest/spread operators in .vue files but not in .js files

**Comment by frlinw** [comment]
After migration to webpack 4.x, it works as expected
