### ISSUE TITLE
Update docs on running tests w/ TEST_ONLY

### ISSUE THREAD

**Issue by wuweiweiwu** [babel/babel#7529]
Feature Request

### Expected Behavior

`TEST_ONLY=whatever` as described in docs should run tests for that specific plugin/package

### Current Behavior

Runs all the tests  even if `TEST_ONLY` is specified
### Possible Solution

Update docs to remove `TEST_ONLY`

### Context

Trying to run tests with `TEST_ONLY` but runs all the tests so now using `TEST_GREP`

**Comment by danez** [comment]
Currently as a workaround you can use `yarn jest babylon` for example.

**Comment by danez** [comment]
This was fixed by @loganfsmyth
