### ISSUE TITLE
Beta 40 dropping imports added by helper-module-imports.

### ISSUE THREAD

**Issue by phyllisstein** [babel/babel#7551]
### Choose one: is this a bug report or feature request?
Bug report.

### Summary
Hey folks! I've been [working on](https://github.com/phyllisstein/babel-plugin-ramda) upgrading [`babel-plugin-ramda`](https://github.com/megawac/babel-plugin-ramda) to support the v7 betas, and I've noticed some funky behavior with `@babel/core@7.0.0-beta.40`. The plugin tries to create a new import statement for individual modules of Ramda, much as `babel-plugin-lodash` does for Lodash. I added the following code:

```js
selectedMethods[methodName] = addDefault(file.path, path, { nameHint: methodName });
```

...and found that it only worked under versions of `@babel/core` _below_ `7.0.0-beta.40`. That is, given input like this:

```js
import R from 'ramda'

const obj = { a: 1, b: 2, c: 3 }
const values = R.values(obj)
```

...Babel produces output like this:

```js
var _values = _interopRequireDefault(require("ramda/src/values")).default;

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var obj = {
  a: 1,
  b: 2,
  c: 3
};

var values = _values(obj);
```

When I upgrade `@babel/core` to beta 40, however, the same input code produces the following output:

```js
var obj = {
  a: 1,
  b: 2,
  c: 3
};
var values = R.values(obj);
```

It seems as though the transformation just isn't being applied.

I fiddled with the versions a bit and found that the version of `@babel/helper-module-imports` doesn't seem to matter, nor the version of `@babel/preset-env` or `@babel/preset-stage-3`, which the package was also using.

I know it's not your role to maintain plugin packages, so I'll naturally keep poking at it on my own, but if you had any insight into where this might have broken down between `beta.39` and `beta.40`, I'd be grateful for the help.

**Comment by loganfsmyth** [comment]
This appears to be from https://github.com/babel/babel/pull/7326. You are using `scope.hasBinding`, but by that point in time the import has already been removed, so there actually isn't a binding. It just happens that we weren't properly removing the binding data when the import declaration was deleted, before.

Seems like you'd potentially want to delay removing the `import`, or do an explicit iteration in Program to collect all of the data you want and remove them up front.

**Comment by loganfsmyth** [comment]
No problem :)
