### ISSUE TITLE
[Question] How to make babel parse JSX and spreads while developing plugin?

### ISSUE THREAD

**Issue by RIP21** [babel/babel#7554]
I'm writing a plugin using babel-core ver 6.26, and it should be able to make an AST from objects/arrays spreads and JSX but it's just arguing with me with "unexpected token" when I add `{...getSomething()}` or JSX.

In the same time, if I make AST from code without spreads or JSX and then replace or add some new nodes to its AST using `t.SpreadProperty()` and some JSX, it successfully outputs the correct code.

How to write or setup plugin, so it will understand such tokens? I'm testing my plugin using code like that.

```jsx
const result = babel.transform(
    `const SomeJsx = (props) => <div {...props} />`,
    {
      plugins: [
        "./src/index.js"
      ]
    }
  ).code

console.log(result);
```
Where `./src/index.js` is dir to my plugin code.

Purpose of this plugin is to be a codemod, so I can't just add object-spread/react plugin which will transpile down all spreads and JSX calls to the `_extend()` and `React.createElement` calls.

I wasn't able to find how to tackle that, so I ask here :) 

Thanks a lot. And hope it's a correct place to ask such question.

**Comment by hzoo** [comment]
I'd use https://github.com/square/babel-codemod or https://github.com/facebook/jscodeshift. You just need to turn on the syntax plugin or use that in your own plugin.

In your plugin:

```
  return {
    inherits: require("syntax-plugin-here"),
    visitor: {}
  }
```

**Comment by RIP21** [comment]
@hzoo what about if my codemod should be able to read any supported by those syntax plugins files. So it not fails if he doesn't know what static class fields are.
Or `babel-codmod` is smart and have all syntaxes switched on for all of the plugins automatically?
Or I should import to `inherits` all syntaxes that I plan to cover so it works with "any" supported by babel code?

**Comment by RIP21** [comment]
@hzoo just tried to pass an array of requires into the `inherits` but got an error. How to pass multiple syntaxes?

**Comment by loganfsmyth** [comment]
If this is intended to be a codemod, would the actual final code live in a directory where the `react` and `object-rest-spread` plugins are enabled? Otherwise you're codemod is just creating code that the user won't actually be able to run.

**Comment by RIP21** [comment]
@loganfsmyth this codemod mode will not add any spreads etc. But will move stuff around.
Basically this one.
https://github.com/RIP21/babel-plugin-hyperscript-to-jsx
I just want to be sure that user will call it simply like
`codemod --plugin hyperscript-to-jsx ./src`
Without any thinking on which syntax he has. Cause, for example, he uses `create-react-app` and doesn't really cares.

**Comment by loganfsmyth** [comment]
I don't think we have a great solution for this currently.

**Comment by RIP21** [comment]
@loganfsmyth okay then.
What about to pass multiple inherits into the plugin object? Or impossible too?

**Comment by loganfsmyth** [comment]
You can't inherit multiple syntax plugins, but if you look at what the syntax plugins do you can just do that yourself, e.g.
```
https://github.com/babel/babel/blob/master/packages/babel-plugin-syntax-jsx/src/index.js#L8
```
and just `.push` multiple things.

**Comment by RIP21** [comment]
@loganfsmyth thanks for the suggestion :) I thought it's something more complex, didn't even check their internals :) 

Thanks. It solves my issue. I close that one.
