### ISSUE TITLE
CLI for compiling directories doesn't work as described

### ISSUE THREAD

**Issue by gaearon** [babel/babel#756]
http://6to5.org/docs/usage/cli/ says:

>Compile the entire src directory and output it to the lib directory.

>```
>$ 6to5 src --out-dir lib
>```

When I try to do that, I get a weird error:

```
$ ./node_modules/.bin/6to5 modules --out-dir dist-modules
filenames required for --out-dir
```

Changing `modules` to `./modules` helps.
What's the problem?

**Comment by sebmck** [comment]
> filenames required for --out-dir

is output when you provide an `--out-dir` but don't provide it any target filenames/directories.

I can't manage to replicate this, are you doing anything specific?

**Comment by gaearon** [comment]
Seems like `modules` as source folder name is the issue. Maybe there's an argument called `modules` and options parser swallows it.

**Comment by eventualbuddha** [comment]
Yeah, it looks like commander is registering internal listeners for each normalized option name (i.e. `--modules` turns into `modules`), and simply [emits each argument that wasn't an option as an event if there are listeners for it](https://github.com/tj/commander.js/blob/6135fbcdf35083d3015f5e47a900f53e764fc601/index.js#L565-L566). To me this seems like a bug in commander, and is one of the reasons I usually end up rolling my own command-line option parsing.

This is why you're correct that using `./modules` instead works around the issue.

**Comment by sebmck** [comment]
Hm, might need to switch CLI modules then. Any suggestions? Rolling our own potentially brings in more issues.

**Comment by sebmck** [comment]
Superseded by #836.
