### ISSUE TITLE
Author for babel-plugin-transform-regenerator

### ISSUE THREAD

**Issue by SilviaIenciu** [babel/babel#7564]
In package.json the author for this package is Ben Newman <bn@cs.stanford.edu> but Sebastian McKenzie has the copyright for the entire project; so can I  use the copyright of Sebastian McKenzie for all packages or should I put in this case the author Ben Newman?
Thanks.

**Comment by xtuc** [comment]
While Sebastian McKenzie created the project, Ben Newman wrote the `babel-plugin-transform-regenerator` package, so the copyright should be preserved.

**Comment by hzoo** [comment]
Yeah that is correct ^

Thanks for asking!

**Comment by SilviaIenciu** [comment]
Thanks for answering this issue.. But still, the name of Ben Newman appears ony as an author in the package.json and no other copyleft in the package babel-plugin-transform-regenerator. Could you please tell me which copyright should remain? or maybe give me a link to the copyright? 

Thank you once again
