### ISSUE TITLE
preset-env doesn't seem to find the lowest common denominator in this case

### ISSUE THREAD

**Issue by ScottRudiger** [babel/babel#7567]
First, I'm not positive this issue is specifically related to `@babel/preset-env`; the problem could also lie in `between-chair-and-keyboard`, `webpack`, `@babel/plugin-transform-runtime`, or `browserlist`. But, I thought I'd try here.

I configured `@babel/preset-env` in the webpack config as follows:

```javascript
...
plugins: ['@babel/plugin-transform-runtime'],
presets: [
  ['@babel/preset-env', {
    modules: false,
    targets: {
      node: 'current',
      browsers: ['defaults', 'not ie <= 10'],
    },
  }],
...
```

With that configuration, I noticed that the transpiled file retains `destructuring parameters` from my original, ES6+-filled code. According to [the compat tables](http://kangax.github.io/compat-table/es6/#test-destructuring,_parameters), this is not supported in several environments IE 11+.

However, when I remove `node: 'current'` from `targets`:
```javascript
...
targets: {
  browsers: ['defaults', 'not ie <= 10'],
},
...
```

the transpiled file then shows webpack pulling in an `__webpack_require__` for `_slicedToArray` to support `destructuring parameters` (with arrays):
```javascript
var _slicedToArray = __webpack_require__(/*! @babel/runtime/helpers/slicedToArray */ "./node_modules/@babel/runtime/helpers/slicedToArray.js");
```

Now, I'm running Node v9.7.1, which natively supports `destructuring parameters` (with arrays); but I would think that if `@babel/preset-env` is considering the lowest common denominator, that the `_slicedToArray` `__webpack_require__` would actually be pulled in for _**both**_ configurations since the lowest common denominator should be the browsers target either way.

However, because `_slicedToArray` only shows up when the node target is omitted, (to me) it seems like the lowest common denominator is not being found correctly, as described in [the @babel/preset-env README](https://github.com/babel/babel/tree/master/packages/babel-preset-env#determine-the-lowest-common-denominator-of-plugins-to-be-included-in-the-preset).

Am I missing something? Or, is this a bug?

\- Sincerely Confused

Details:
```
node: v9.7.1
@babel/core: 7.0.0-beta.40
@babel/plugin-transform-runtime: 7.0.0-beta.40
@babel/preset-env: 7.0.0-beta.40
@babel/runtime: 7.0.0-beta.40
babel-loader: 8.0.0-beta.2
webpack: 4.1.1
webpack-cli: 2.0.11
```

**Comment by jaydenseric** [comment]
I can see you're using `defaults` in the browserslist query; does this issue relate to https://github.com/babel/babel/issues/7405?

**Comment by ScottRudiger** [comment]
@jaydenseric it appears so, if I instead list out the default settings rather than `'defaults'`:
```javascript
targets: {
  node: 'current',
  browsers: ['> 0.5%', 'last 2 versions', 'Firefox ESR', 'not dead', 'not ie <= 10'],
},
```
I see the appropriate behavior.

**Comment by jaydenseric** [comment]
Awesome, this duplicate issue can be closed then 🙌
