### ISSUE TITLE
"interface is a reserved word in strict mode" error when TypeScript is transpiled with Babel

### ISSUE THREAD

**Issue by donaldpipowitch** [babel/babel#7585]
Choose one: is this a **bug** report or feature request?

### Input Code

```ts
// index.ts
interface Foo {} 
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// allow yarn/npm to link build scripts
function resolveByKey(config, key) {
  if (Array.isArray(config[key])) {
    config[key] = config[key].map((item) => {
      if (Array.isArray(item)) {
        item[0] = require.resolve(item[0]);
        return item;
      } else {
        return require.resolve(item);
      }
    });
  }
}

function resolve(config) {
  resolveByKey(config, 'presets');
  resolveByKey(config, 'plugins');
}

module.exports = resolve({
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          browsers: 'last 2 versions, Firefox ESR, ie >= 11',
          node: '6.10' // still v6, because of AWS Lambas
          // ...android, ios, electron
        },
        modules: false,
        useBuiltIns: 'usage'
      }
    ],
    '@babel/preset-react',
    '@babel/preset-stage-0',
    '@babel/preset-typescript'
  ],
  plugins: [
    '@babel/plugin-proposal-decorators',
    ['@babel/plugin-proposal-class-properties', { loose: true }]
  ]
});
```

### Expected Behavior

Parses without errors, because it should be treated as TypeScript.

### Current Behavior

Throws error "interface is a reserved word in strict mode", because it is treated as plain JavaScript in strict mode.

### Context

I try to transpile TypeScript code with Babel.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |   7.0.0-beta.40
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by donaldpipowitch** [comment]
Hi @andy-ms, can you point me to a direction how to solve this or who to ask? I'd make a PR then. Thank you

**Comment by andy-ms** [comment]
May be a bug in the configuration? Could you try with `.babelrc` to see if there is still a problem?

**Comment by donaldpipowitch** [comment]
You're right. Thank you for responding. I don't know what causes the problem in my setup, but when I created a new example from scratch `@babel/preset-typescript` was able to parse it correctly.
