### ISSUE TITLE
Flow + React => import * as React from 'react' => _interopRequireWildcard, which iterates

### ISSUE THREAD

**Issue by agalatan** [babel/babel#7589]
It's not a bug, but it's not great either. I'd recommend creating a small plugin in the flow preset, which I can write.

When using **Flow + React** in ES6, it is recommended to import React as a namespace, i.e. 
                                             ```import * as React from 'react';```

See https://flow.org/en/docs/react/components/ , the paragraph:
```Note: We import React as a namespace here with import * as React from 'react' instead of as a default with import React from 'react'. When importing React as an ES module you may use either style, but importing as a namespace gives you access to React’s utility types.```

When Babel transpiles these imports to ES5, it uses ```_interopRequireWildcard```.
I see this problematic, because **it contains a for-iteration**. React's minified bundle does not contain the key ___esModule_, so it always executes the "else" branch. I think React 16.2.0 in production environment has 11 keys. The boilerplate is also unpleasant.

### Possible Solution
My suggestion is: write a Babel plugin, and add it in @babel/preset-flow. This plugin should simply convert the ```import * as React from 'react';``` into ```import React from 'react';```

**Comment by Andarist** [comment]
Isn't scope hoisting a.k.a ModuleConcatenationPlugin (on by default in production mode in webpack@4, opt-in in webpack@3) a solution for your problem? Or is your concern about SSR in node?

**Comment by agalatan** [comment]
I can't use Webpack4 right now, but I did try with ModuleConcatenation in Webpack3. I also set **modules: false** for the babel-preset-env (the 6.x.x version).
I disabled the uglifier, so that I can look in the dist folder and analyze visually the output. This ```js var _react = __webpack_require__("./node_modules/react/index.js");
var React = _interopRequireWildcard(_react); ``` occurs as often as it did if I disabled ModuleConcatenationPlugin.

**Comment by loganfsmyth** [comment]
The behavior you're raising about looping isn't related to React or Flow specifically, it is just how Babel's interoperability behavior between CommonJS and ES module syntax is defined. Given that, it wouldn't make sense to special-case it for those.

> I also set modules: false for the babel-preset-env (the 6.x.x version). I remember this option being flaky in Babel, for the whole preset, though.

Setting that option should tell Babel to skip processing module syntax entirely which would leave it to Webpack to process the modules, so if you see `_interopRequireWildcard` in your files anywhere then the option hasn't been configured properly.
