### ISSUE TITLE
useBuiltIns: true is broken in plugin-proposal-object-rest-spread

### ISSUE THREAD

**Issue by egoist** [babel/babel#7590]
Choose one: is this a bug report or feature request?

**bug report**

### Input Code

```js
const a = {...v}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "plugins": [
    ["@babel/plugin-proposal-object-rest-spread", {"useBuiltIns": true}]
  ]
}
```

### Expected Behavior

```js
const a = Object.assign({}, v);
```

### Current Behavior

```js
function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; var ownKeys = Object.keys(source); if (typeof Object.getOwnPropertySymbols === 'function') { ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function (sym) { return Object.getOwnPropertyDescriptor(source, sym).enumerable; })); } ownKeys.forEach(function (key) { _defineProperty(target, key, source[key]); }); } return target; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

const a = _objectSpread({}, v);
```

### Possible Solution

Seems you always add `objectSpread` when not in loose mode:

https://github.com/babel/babel/blob/d260bfaec47f1c34933ff2abdf1fd4ffded4875d/packages/babel-plugin-proposal-object-rest-spread/src/index.js#L414-L419

### Your Environment

7.0.0-beta.40 for both `@babel/core` and `@babel/plugin-proposal-object-rest-spread`

**Comment by egoist** [comment]
Oh thanks, seems that's a new change and I didn't read the README carefully 😄

**Comment by nicolo-ribaudo** [comment]
@egoist I was wrong :slightly_smiling_face: 

https://github.com/babel/babel/commit/d682e32529db0c39137cecd04dabce142f3f9b93#r28145350 (This commit has landed in beta.42)

**Comment by Andarist** [comment]
Not entirely, `Object.assign` might get used without `loose` mode at some more rare occasions, but `loose` is still necessary to replace `objectSpread` with it (in combination with `useBuiltIns` ofc)
