### ISSUE TITLE
[babel-standalone] feature: support <noscript><script> tag

### ISSUE THREAD

**Issue by futurist** [babel/babel#7591]
Choose one: is this a bug report or feature request?

**Feature Request**

### Package: babel-standalone

Support code inside `noscript` tag.

Most of online code editor not support `<script type="text/babel">` syntax highlight, it's better to put code inside standard `<script>` tag, which can be embed inside `<noscript>`.

### Input Code

```html
<noscript data-type="text/babel"><script>
const you_code = 'here'
</script></noscript>
```

### Expected Behavior

Please check [an example](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8AQgAiAeQDCAFQCaABQCiAAnZQAfAB06gtVp1YIDJPsHN4DZY2YBeTSCQQwsAE5kADvDK97ynnwg+OxAXIwQAWlgwMG4AIwArZQgADyZ3GHtTc0tYLAYXSHhggFd4EnCADkztMwgLKyYIYIA3MggAd3duF3hff34i+3ayJHgsG0dW2Ahw4dGsap0veBh1UIYIqJiEpNTcdIhBAHpl1ZrnN09lMBdYYJx4dzBUI6PiuncAawBzDB5cI7rBAAAQAjAA2DAAJgwAAY3rgkICwvAMJNoNx3Mw+Bh4mBMscLh54KYiVcbnd7A8ni83h8fn9uACgfBwkgmWDITD4cVEciNqz2bgMO4XNwkMUEN46BhcGQZXiCUcySTzq5iddbvd4I9nq93l9fv9+ZtonF4kqVaT1eStVSdTT9fSjUyjrEGLFoOEwBY6EgGFBeBBgeC3R7oLL5bj8SB1ISbaq6DUjoZjKZYuKAJ7qZTaGqIZIWdbKEba-B9bhQMA2UFQ2HKMXtasAZjjJxSRaMpiQZGaJaQwTF3F6saH8GOPea+hqdG4Kv7wR4jgJVu0-h9ymAW0IylwDHckigDGiAF9lDZlAAlFGSADKt-ECQAFMBtMplAByDD79wf1Cbt932Ud1YB+MV3iQf8Px4FwAw-QCT0IQCvx-aQyBWCA-wAuggM-AAyDAjxcb5MNQV8cNw5QSF4eBbzIAAvCBUA-ZtQlweCKPfRDAPfHhAxcKDYigYpMKQzjd3yb55Sgut3GSDiuLEk8AEpcyTOhYCPaJlAAQXcdxdn4JAwCvFEMEkJkujoQJ4Gw99Qj9CAXCfZTyNw9dbOAIiSLPC8xjIMAMB9BhEAAH1C4ATx4hs6mKFwcL3A8tJMp9lFeZRBEy8JwivbhQLAYRovfXQjEcFw-GSgA5Rpz0-H8P30SigN0KEKuPMBquYWrgGAD9UPQmAsPgFwRJ3byIGUE8ovEpr314Q8yFA7qXPPHM3NmpqtiCuon2oFD9I-ABdHdgBAsDuAg-9xuUAB+T8YLg5QoMzaBA3aD8VKKjblH8wLClvCxEBfcb-2EcbELU77KJcmx1AAEifD8AGI1A-ZSMHlayXAACWkABZAAZGwEeRsc0YxugsdxwnlK+pqpsa76FqWvGIDpjKUyhRncOOVMyu5oDotpiiz20abtGvAUJDxjAHLKp9BD09wjnUHcSaRsnlOF7QSHeKVeGUBHICgVyYvgOKcPZWBeRsjAAEcRJcTNb2gOB4G6J9jdU6b40uEljlnVd1NiTMMssLBQhIbVdVpKSxmKWJGQBXXzbcH0TVZLZzV8IsSKKD8AH0hIYOhPgallIjNBJjgYAXcOTDMkGzZM9BARD6EaVho04fobNYZp8hLD5Slqq2bZxB2nOd12EA9j9A4TcnyAKeBJCwCgkAwAtV5o22wHSdDEc0bRybAKBFogJ9QUIcJQXR+JuHlI+T+Fgfyoux4R4vAAhcMoC32CdAwDURcLgJ88p3ClBOsoUUTg6jPGUHtJwdZQQAFYPyEA-CyI6k10ZLggAAbm0BAAeUAnwf0gfAYWbdCAd2YF3LYPdd4CHQG3Q6J4gA)

### Current Behavior

`type=text/babel` no syntax highlight, and may [lead to problem](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8AQgAiAeQDCAFQCaABQCiAAnZQAfAB06gtVp1YIDJPsHN4DZbCwMATpHgBeTSACu8EgFoAHC9PnLRmZnEAA3MggAdwAHblt4FyteficXSLIkeCxHJAhw2AhPdMysP21BAHpDY1MAI24kAE99cqQyUOUMkO53aPc-SrbQ02FPT2UAGW5jZQAhBlroZTHTMFhbMmj4ZTBbWBCceGiwVAqK1zpogGsAcwweXAqAAVqF6AqwCzokBiheCCeAHYMAAGUGeRYWDAAFgATBVXosoBgAFZgAYfdabeAjMbKWQ9WxWVyfbi4HZYraqCC2CDLTyrSnbeCNaIQEKIAAe8ARbygZToPDon2UNwg8AAshAwGAGGLlI5lAAKACUCvUyhcAAloH9lAB1OJQJAuADc2iQ3FgrmYfAwYvgihgtvgs0aAEkkEqAOQ9I7ub0qjBkOh0Gla6QSiYK0XiqUyuUQVXmnSYjZbfTKLPZrPlBENZp5vQgAC+hHoTBY6FRVGIQpSrFL5ZAQSrmFgMs49YgAnQpYAuiWgA)

### Possible Solution

add `<noscript data-type="text/babel"><script>` tags support.

### Your Environment

Browser

**Comment by nicolo-ribaudo** [comment]
This problem should be fixed by syntax highlighters, not by Babel.

**Comment by futurist** [comment]
Not only for syntax highlight, but this may also [lead to problems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8AQgAiAeQDCAFQCaABQCiAAnZQAfAB06gtVp1YIDJPsHN4DZbCwMATpHgBeTSACu8EgFoAHC9PnLRmZnEAA3MggAdwAHblt4FyteficXSLIkeCxHJAhw2AhPdMysP21BAHpDY1MAI24kAE99cqQyUOUMkO53aPc-SrbQ02FPT2UAGW5jZQAhBlroZTHTMFhbMmj4ZTBbWBCceGiwVAqK1zpogGsAcwweXAqAAVqF6AqwCzokBiheCCeAHYMAAGUGeRYWDAAFgATBVXosoBgAFZgAYfdabeAjMbKWQ9WxWVyfbi4HZYraqCC2CDLTyrSnbeCNaIQEKIAAe8ARbygZToPDon2UNwg8AAshAwGAGGLlI5lAAKACUCvUyhcAAloH9lAB1OJQJAuADc2iQ3FgrmYfAwYvgihgtvgs0aAEkkEqAOQ9I7ub0qjBkOh0Gla6QSiYK0XiqUyuUQVXmnSYjZbfTKLPZrPlBENZp5vQgAC+hHoTBY6FRVGIQpSrFL5ZAQSrmFgMs49YgAnQpYAuiWgA)

You can see nothing rendered if the code inside `type=text/babel`, moved to `<noscript data-type="text/babel"><script>` is a more stable way.

**Comment by loganfsmyth** [comment]
I would consider syntax highlighting issues outside the realm of our responsibility. For the other issue with the code that isn't being run, it looks like `flems.io` does all kinds of transformations on the HTML before it is executed and I honestly can't tell what is causing it to fail.

If you can narrow down what is causing it to fail there, we can certainly look into that specifically, but I don't think using `noscript` would be an appropriate fix.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since syntax-highlighting bugs are not Babel's responsibility.

Regarding fems.io, it transforms the script tag so Babel can't find it.
