### ISSUE TITLE
Babel Munges Prototype Chain Across Import To Cause instanceof To Fail

### ISSUE THREAD

**Issue by aksuska** [babel/babel#7593]
Reduction:

```
// MyObject.js
export default class MyObject {}
```

```
// MySubObject.js
import MyObject from "./MyObject";
export default class MySubObject extends MyObject {}
```

```
// Index.js
import MyObject from "./MyObject";
import MySubObject from "./MySubObject";

let chain = [];
let targetClass = MySubObject;
do {
  chain.unshift(targetClass);
  console.log(
    "Adding %s, next: %s (%s), is ours: %d", 
    targetClass.name, 
    Object.getPrototypeOf(targetClass).name, 
    MyObject.name, 
    Object.create(Object.getPrototypeOf(targetClass)) instanceof MyObject
  );
} while (
  Object.create(
    targetClass = Object.getPrototypeOf(targetClass)
  ) instanceof MyObject
);
```

Outputs:            
```
Adding MySubObject, next: MyObject (MyObject), is ours: 0
```
But should be:  
```
Adding MySubObject, next: MyObject (MyObject), is ours: 1 
```

Configuration is completely vanilla:
```
{
	"presets": [
		["env", {
			"targets": {
			"node": "current"
			}
		}],
		"flow"
	],
	"plugins": [["transform-class-properties", { "spec": true }]]
}
```

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26
| node             | 9.5.0
| npm              | 5.7.1
| Operating System | Mac OS X 10.13.3

**Comment by loganfsmyth** [comment]
As far as I can tell, your snippet does not print what you claim it does, since it contains a syntax in that

    let chain = [],

should end in a semicolon. 

Separately, your format string uses `%d` and but the data passed to the logger isn't a number, so it just prints `NaN`. Perhaps you forgot to paste in an updated version?

**Comment by aksuska** [comment]
Sorry, cut and paste issue. Is corrected. And it prints exactly what I show for me:
`  console.log index.test.js:39
    Adding MySubObject, next: MyObject (MyObject), is ours: 0`

Are you replicating the multiple file/import structure? Also are you transpiring for only Node 9.5, as my config shows? I haven't tried to do it all in one file but I hear Babel works that out better. I can reproduce this issue every time.

Also the result of instanceof is boolean, which %d is coercing into a numerical equivalent, and is never undefined unless you are doing something different than my code shows. `undefined instanceof MyObject` produces false, and `MySubObject instanceof undefined` produces a TypeError.

**Comment by loganfsmyth** [comment]
> Also the result of instanceof is boolean, which %d is coercing into a numerical equivalent

Ahh I see. Since you were coercing it to a number instead of just printing `true`/`false` I thought there was supposed to be some counter or index or something. I was trying to do a simple reproduction of your claim that it should be `1` by running your code without Babel at all, and I was doing it in Chrome's console, which does _not_ coerce the type so `console.log("%d", false);` will log `NaN`, whereas Node prints `0` apparently.

From my test without Babel, the following snippet in Chome
```
class MyObject {}
class MySubObject extends MyObject {}

let chain = [];
let targetClass = MySubObject;
do {
  chain.unshift(targetClass);
  console.log(
    "Adding %s, next: %s (%s), is ours: %s", 
    targetClass.name, 
    Object.getPrototypeOf(targetClass).name, 
    MyObject.name, 
    Object.create(Object.getPrototypeOf(targetClass)) instanceof MyObject
  );
} while (
  Object.create(
    targetClass = Object.getPrototypeOf(targetClass)
  ) instanceof MyObject
);
```
prints

> Adding MySubObject, next: MyObject (MyObject), is ours: false

What makes you say that this should log `true`? `targetClass` is a constructor function, not an instance, so it is not an instance. Maybe what you want is

```
Object.create(targetClass.prototype) instanceof MyObject
```
instead of your code:
```
Object.create(Object.getPrototypeOf(targetClass)) instanceof MyObject
```

**Comment by Kovensky** [comment]
`Object.getPrototypeOf(targetClass)` is an `instanceof` `Function`, because the prototype of a subclass' constructor is the superclass' constructor.

**Comment by aksuska** [comment]
@loganfsmyth it would that I am passing the wrong argument to Object.create(), as your example works in Chrome console, but I get this from Node:
`TypeError: Object prototype may only be an Object or null: undefined
        at Function.create (<anonymous>)

      69 | 		}
      70 | 		targetClass = Object.getPrototypeOf(targetClass);
    > 71 | 	} while (Object.create(targetClass.prototype) instanceof MyObject);`

**Comment by aksuska** [comment]
@Kovensky In chrome console at least, Object.getPrototypeOf(targetClass) == MyObject is true. targetClass.prototype == MyObject is false. Maybe that is your point.

**Comment by loganfsmyth** [comment]
You haven't really explained what this code is trying to do, so it is hard to give suggestions. That said, you need to keep in mind that at some point you're `getPrototypeOf` will walk up the chain to a point where the result isn't a function anymore at all, so `targetClass.prototype` is `undefined`. So you'd at least want
```
class MyObject {}
class MySubObject extends MyObject {}


let chain = [];
let targetClass = MySubObject;
do {
  chain.unshift(targetClass);
  console.log(
    "Adding %s, next: %s (%s), is ours: %s", 
    targetClass.name, 
    Object.getPrototypeOf(targetClass).name, 
    MyObject.name, 
    Object.create(targetClass.prototype) instanceof MyObject
  );
} while (
  targetClass = Object.getPrototypeOf(targetClass),
  targetClass.prototype && Object.create(targetClass.prototype) instanceof MyObject
);
```

I'll also say that your code would be a lot easier to read as a `for` loop:
```
class MyObject {}
class MySubObject extends MyObject {}

let chain = [];
for (
  let targetClass = MySubObject; 
  targetClass.prototype && Object.create(targetClass.prototype) instanceof MyObject; 
  targetClass = Object.getPrototypeOf(targetClass)
) {
  chain.unshift(targetClass);
  console.log(
    "Adding %s, next: %s (%s), is ours: %s", 
    targetClass.name, 
    Object.getPrototypeOf(targetClass).name, 
    MyObject.name, 
    Object.create(targetClass.prototype) instanceof MyObject
  );
}
```

**Comment by aksuska** [comment]
I have a root class from which all of my other classes derive. Every class has a one-time initialization that needs to be called but must always be called on the parent class _before_ the child class. The shown snippet is supposed to create an array of the class objects (_not_ instances, but the classes themselves) in hierarchical order, and then (not shown) a static method is called on each and a static field flag is set so it won't do it again. Because only my classes support this I am trying to stop walking up the chain as soon as I hit my root class.

I can certainly work around this by simply checking for the existence of the flag property, but I use similar code with Object.create() and Object.getPrototypeOf() so I would like to determine whether I am hitting a Babel/Node issue or just my own ignorance.

**Comment by aksuska** [comment]
I can confirm your example is working under Node at least, though I am confused that Chrome shows that the ProtoType of MyObject is a function, not undefined or null. Maybe it is a Chrome peculiarity.

**Comment by loganfsmyth** [comment]
Oh, if all you're doing is trying to walk up the class hierarchy without instances, I wouldn't use `instanceof` at all. I'd do

```
class MyObject {}
class MySubObject extends MyObject {}

let chain = [];
for (
  let targetClass = MySubObject; 
  targetClass !== Object.getPrototypeOf(MyObject); 
  targetClass = Object.getPrototypeOf(targetClass)
) {
  chain.unshift(targetClass);
  console.log(
    "Adding %s, next: %s (%s), is ours: %s", 
    targetClass.name, 
    Object.getPrototypeOf(targetClass).name, 
    MyObject.name, 
    Object.create(targetClass.prototype) instanceof MyObject
  );
}
```

**Comment by aksuska** [comment]
Brilliant! Makes no assumptions about the root class prototype, so should work in any environment.

**Comment by loganfsmyth** [comment]
Cool!
