### ISSUE TITLE
spec: `decorator` property should should be nullable

### ISSUE THREAD

**Issue by gabejohnson** [babel/babel#7598]
### Input Code

```js
require('babylon').parseExpression('class Foo {}', { plugins: ['decorators'] });
```
results in
```js
Node {
  type: 'ClassExpression',
  start: 0,
  end: 12,
  loc:
   SourceLocation {
     start: Position { line: 1, column: 0 },
     end: Position { line: 1, column: 12 } },
  id:
   Node {
     type: 'Identifier',
     start: 6,
     end: 9,
     loc: SourceLocation { start: [Object], end: [Object], identifierName: 'Foo' },
     name: 'Foo' },
  superClass: null,
  body:
   Node {
     type: 'ClassBody',
     start: 10,
     end: 12,
     loc: SourceLocation { start: [Object], end: [Object] },
     body: [] } }
```
Note the lack of a `decorators` property on the `ClassExpression` node. This contradicts the [spec](https://github.com/babel/babel/blob/master/packages/babylon/ast/spec.md#classes).

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  ...
  "dependencies": {
    "babel-plugin-transform-decorators": "^6.24.1",
    "babylon": "^6.18.0"
  }
}
```

### Expected Behavior
The `ClassExpression` node should contain a `decorators` property with a value set to `[]`.

### Current Behavior
The `decorators` property is missing.

### Possible Solution
One of:
1. Add the property with an empty array for the associated value
2. Modify the spec to have `decorators` be nullable (i.e. `[Decorator] | null`)
3. Add a note to the spec stating that experimental features have nullable properties
4. Drop `Decorator` from the spec until it's reached stage 3 or 4

### Context
I'm writing PureScript [bindings](https://github.com/gabejohnson/purescript-babylon) for `babylon` and got an error when I encountered the missing property. My definition included the data constructor:

```hs
data Node = ...
          | ClassDeclaration     {..., decorators :: Array Node }
            ...
```
To get it working I had to modify `Array Node` to `Maybe (Array Node)`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babylon          | 6.18.0
| node             | 8.1.2
| npm              | 5.6.0
| Operating System | macOS 10.12.6 (16G1212)

**Comment by xtuc** [comment]
> Drop Decorator from the spec until it's reached stage 3 or 4

I don't see why we would do that, we're working actively on the decorator support right now.

> Add the property with an empty array for the associated value

I think this is the good solution (only when the `decorator` and `decorator2` plugins are enabled).

**Comment by nicolo-ribaudo** [comment]
I'd actually prefer to make that property nullable, to avoid creating unnecessary arrays.

**Comment by xtuc** [comment]
In my experience it's easier to assume that there's always an array instead of having to do an additional check. 

The property with the array will only be present if the plugin is activated. Usually you have only one class per file so I guess it won't cause any noticeable slowdown.

**Comment by JLHwung** [comment]
Closing this as won't fix, however, PR to AST/spec.md is welcome.
