### ISSUE TITLE
babel-preset-env failing to use Node's native async/await support?

### ISSUE THREAD

**Issue by tdd** [babel/babel#7601]
This is a bug report.

### Input Code

Check out [this tiny demo repo](https://github.com/tdd/demo-babel-preset-env-async-issue). Here's the core trigger code for the issue:

```js
(async () => {
  const source = await readFilePromise(__filename, 'utf-8')
  console.log('Successfully read source file using async/await:')
  console.log(source)
})()
```

### Babel/Babylon Configuration (package.json)

```js
{
  "babel": {
    "presets": [["env", { "node": "current" }]]
  }
}
```

### Expected Behavior

I'm running this on Node 9.3, so it should detect native async/await support and go with it.

### Current Behavior

It tries to transpile it to generators, therefore requiring `regeneratorRuntime`, which isn't loaded (as I intentionally didn't load `babel-polyfill` or a more granular part of it).

### Possible Solution

It should detect native support properly, and not transpile this aspect!

### Context

We're using a lot of `async`/`await` in Node-side code for request handlers, all on recent Node (8.x LTS or 9.3+). Native support has been around since Node 7.6+, I think. It sure works when Babel isn't in the loop. This forces us to bring in a polyfill for no good reason and also decreases performance significantly.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 / babel-preset-env 1.6.1 (both `latest` npm tags)
| node             | 9.3.0
| npm              | 5.6.0
| Operating System | OSX High Sierra 10.13.3

**Comment by danez** [comment]
The options should be
```json
{
  "babel": {
    "presets": [["env", { "targets": { "node": "current" } }]]
  }
}
```

Does that solve the problem?

**Comment by tdd** [comment]
Hey @danez !

Thanks for pitching it. OK, so that's weird. It **does** solve the problem, but I still have the issue (despite correct options from the get-go) on my production project. Will investigate further and close this as soon as I'm confident the issue lies elsewhere.

**Comment by tdd** [comment]
I got it. It tries to regen as soon as I have a `browsers` target too, that would require transpiling, even if it's code that is required on the Node side, not the browser side.

Doesn't seem useful to me. If it has a `node` setting, it should be able to detect that it's running in Node and not transpile.

**Comment by tdd** [comment]
Will update my demo repo anyway.

**Comment by tdd** [comment]
There, the demo repo is updated.

**Comment by tdd** [comment]
This is actually nominal: Node / Browser configs combine to create a lowest common denominator; this is by design and can be worked around by using separate configs or (in v7) overrides. Closing this.
