### ISSUE TITLE
standalone does not work in ES5

### ISSUE THREAD

**Issue by arv** [babel/babel#7607]
I'm trying to run @babel/standalone in an ES5 environment. I'm not sure this is target platform or not?

Anyway, one way to try this out is to use a really old version of node (0.10 for example)

### Input Code

```sh
yarn add @babel/standalone
nvm install 0.10
nvm use 0.10
node node_modules/@babel/standalone/babel.js
```

### Expected Behavior

I was hoping this would work. It works on the 6.x branch

### Current Behavior

```sh
$ node node_modules/\@babel/standalone/babel.js

/src/test-babel/node_modules/@babel/standalone/babel.js:6578
var BLOCK_SCOPED_SYMBOL = Symbol.for("var used to be block scoped");
                          ^
ReferenceError: Symbol is not defined
    at Object.<anonymous> (/src/test-babel/node_modules/@babel/standalone/babel.js:6578:27)
    at __webpack_require__ (/src/test-babel/node_modules/@babel/standalone/babel.js:30:30)
    at Object.<anonymous> (/src/test-babel/node_modules/@babel/standalone/babel.js:9308:18)
    at __webpack_require__ (/src/test-babel/node_modules/@babel/standalone/babel.js:30:30)
    at Object.<anonymous> (/src/test-babel/node_modules/@babel/standalone/babel.js:5258:1)
    at __webpack_require__ (/src/test-babel/node_modules/@babel/standalone/babel.js:30:30)
    at Object.exports.__esModule (/src/test-babel/node_modules/@babel/standalone/babel.js:9266:20)
    at __webpack_require__ (/src/test-babel/node_modules/@babel/standalone/babel.js:30:30)
    at Object.<anonymous> (/src/test-babel/node_modules/@babel/standalone/babel.js:8151:38)
    at __webpack_require__ (/src/test-babel/node_modules/@babel/standalone/babel.js:30:30)
```

### Possible Solution
Are we not including the ES6 polyfills?

### Context
Trying to run @babel/standalone in an ES5 engine (nashorn)

**Comment by jpsc** [comment]
Node 4.0 is a month of being discontinued so I think that babel will strive to be at least only 6 if not 8.

**Comment by loganfsmyth** [comment]
@jpsc Babel 7 will likely target Node 6, but this issue is specifically around babel/standalone, which is targeted more at users with ES5 environments since it is often run in browsers.

**Comment by jpsc** [comment]
Oh okay. Gotcha. 0.10 was just used as an example.

**Comment by hzoo** [comment]
Yeah that's true, we do want to target ES5 for standalone. I think it's different though, I guess we weren't using polyfillable things like Symbol before? But yeah I don't think standalone would include the polyfill for you unless we have a good way of doing so

**Comment by loganfsmyth** [comment]
It seems like standalone should bundle babel-runtime? That was honestly my assumption until this was filed.

**Comment by Daniel15** [comment]
babel-standalone should support ES5, we should load any polyfills/runtimes that are required to do so.

**Comment by danez** [comment]
But that means babel is not producing es5 code anymore but using some newer stuff?

**Comment by hzoo** [comment]
Oh ^ the babel-runtime thing makes sense.

I think it's that babel itself used to be compiled with `transform-runtime` which would include things like Symbol. But we dropped that since we dropped Node 0.10/0.12. In the case of older browsers we would want to add it back in. Although, I think we could probably do another bundle that doesn't need that too for modern browsers like everyone else is doing.

**Comment by arv** [comment]
Manually loading the polyfills first works. I just wasn't sure what the intent was/is?

**Comment by loganfsmyth** [comment]
I don't have a problem with `babel-standalone` including everything needed to compile in ES5. 

> Although, I think we could probably do another bundle that doesn't need that too for modern browsers like everyone else is doing.

Is there any demand for that? It's only really the REPL usecase and the non-Node usecases where we recommend standalone, so it seems fine to aim for ES5 for it.

**Comment by loganfsmyth** [comment]
Posted a PR for this FYI: https://github.com/babel/babel/pull/8024

**Comment by nicolo-ribaudo** [comment]
Fixed by #8024

**Comment by TrevorBurnham** [comment]
I'm trying to get @babel/standalone@7 running in IE11 and getting the error:

> `WeakSet` is undefined

Polyfilling `WeakSet` is simple enough, but when I do so I get a different error:

> Object.keys argument is not an object

Can you tell me what I need to do to get the new version of babel-standalone running in an ES5 environment? I had no trouble with babel-standalone@6.

**Comment by ktor** [comment]
I'm trying to run 7.8.3 version in Java Nashorn (jdk1.8) and it fails with the same error. Version 6.26.0 works (https://registry.npmjs.org/babel-standalone/-/babel-standalone-6.26.0.tgz).
