### ISSUE TITLE
Website - Please merge https://babeljs.io/docs/plugins/preset-env/ and https://babeljs.io/env

### ISSUE THREAD

**Issue by rajaraodv** [babel/babel#7611]
Website - Please merge https://babeljs.io/docs/plugins/preset-env/ and https://babeljs.io/env
I think the latter is for upgrade from ES2015. But I think it would be useful to simply have a section in the /docs/plugins/preset-env/ so it's easier to find.

**Comment by existentialism** [comment]
@babel-bot move babel/website
