### ISSUE TITLE
error installing babel-polyfill  NPM in laravel 5.6

### ISSUE THREAD

**Issue by murilolivorato** [babel/babel#7612]
I am trying to install babel-polyfill in Laravel 5.6 ;
but it is giving this error -

$ npm install --save babel-polyfill
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path E:\xampp\htdocs\testnoagent\node_modules\.staging\node-notifier-549a8a15\vendor\notifu\notifu.exe
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'E:\xampp\htdocs\testnoagent\node_modules\.staging\node-notifier-549a8a15\vendor\notifu\notifu.exe'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'E:\xampp\htdocs\testnoagent\node_modules\.staging\node-notifier-549a8a15\vendor\notifu\notifu.exe'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'E:\\xampp\\htdocs\\testnoagent\\node_modules\\.staging\\node-notifier-549a8a15\\vendor\\notifu\\notifu.exe\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'E:\\xampp\\htdocs\\testnoagent\\node_modules\\.staging\\node-notifier-549a8a15\\vendor\\notifu\\notifu.exe' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

**Comment by loganfsmyth** [comment]
Since this is a filesystem permissions error, it doesn't seem to be anything specific about Babel that we could help you with.
