### ISSUE TITLE
error 500 Internal Server Error: @babel/code-frame@^7.0.0-beta.35

### ISSUE THREAD

**Issue by zingforever** [babel/babel#7613]
**i come across the error when npm install:**
npm ERR! code E500
npm ERR! 500 Internal Server Error: @babel/code-frame@^7.0.0-beta.35

**part of run log is:**
4557 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
4558 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
4559 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4559 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4559 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4559 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4560 verbose stack Error: 500 Internal Server Error: @babel/code-frame@^7.0.0-beta.35
4560 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
4560 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
4560 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
4560 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
4560 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
4560 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
4560 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
4560 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
4560 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
4560 verbose stack     at runCallback (timers.js:789:20)
4560 verbose stack     at tryOnImmediate (timers.js:751:5)
4560 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
4561 verbose cwd C:\work\ma.content.mdc.web.issuer.summary
4562 verbose Windows_NT 6.1.7601
4563 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
4564 verbose node v8.9.4
4565 verbose npm  v5.6.0
4566 error code E500
4567 error 500 Internal Server Error: @babel/code-frame@^7.0.0-beta.35
4568 verbose exit [ 1, true ]

**Comment by xtuc** [comment]
This error is coming from npm's servers. 

Are you using a proxy for the registry? Could you please try again?

**Comment by dan2k3k4** [comment]
This is because the last published version on NPM was beta 3
https://www.npmjs.com/package/babel-code-frame?activeTab=versions

So all versions above beta 3 (i.e. beta 35 that you're trying to request) will fail.

**Comment by nicolo-ribaudo** [comment]
The last version is beta 44 https://www.npmjs.com/package/@babel/code-frame?activeTab=versions

**Comment by zingforever** [comment]
It is "@babel/code-frame", not "babel-code-frame",  The last version of @babel/code-frame is beta 44 [https://www.npmjs.com/package/@babel/code-frame?activeTab=versions](url)

**Comment by zingforever** [comment]
It is "@babel/code-frame", not "babel-code-frame", The last version of @babel/code-frame is beta 44 [https://www.npmjs.com/package/@babel/code-frame?activeTab=versions](url)  @dan2k3k4

**Comment by hzoo** [comment]
Not sure what actionable thing we can do atm so closing.

**Comment by zingforever** [comment]
the error was caused by error web proxy.
