### ISSUE TITLE
babel-cli: build single file/sub-dir, keep path

### ISSUE THREAD

**Issue by a-x-** [babel/babel#7616]
we're have to rebuild single file sometimes

**expected**:

`babel -d build --source-root src src/path/to/file.js src/another/path`

src/path/to/file.js --> build/path/to/file.js
src/another/path/a.js --> build/another/path/a.js
src/another/path/b.js --> build/another/path/b.js

**babel --version**:
6.26.0 (babel-core 6.26.0)

**Comment by a-x-** [comment]
<details><summary>currently I have to use weird workaround</summary>

```
#!/usr/bin/env bash
dir="$1"
src="$(node -p "'$dir'.replace(/^src\//, '')")"
build="$(node -p "'../build/' + '$dir'.replace(/[^.\/]+\.[^.]+$/, '')")"

echo DEBUG input: $dir src: $src build: $build

cd src
NODE_ENV=production ../node_modules/.bin/babel $src --copy-files -d $build
```

test cases:
```
build-dir src/index.js
build-dir src/components
build-dir src/components/component
build-dir src/components/component/component.js
```

</details>

**Comment by loganfsmyth** [comment]
I'm not sure I understand what's being described here. Is this still an issue?

**Comment by a-x-** [comment]
I have no idea how to reword the issue.

There is inconvenient CLI for frequent case. See details above.

I see that at least 2 people have this issue too

**Comment by nicolo-ribaudo** [comment]
1) You provided the expected behavior. What is the actual behavior?
2) Does this affect Babel 7?
