### ISSUE TITLE
babel-node not transpiling monorepo shared code

### ISSUE THREAD

**Issue by renatonmendes** [babel/babel#7618]
Choose one: is this a bug report or feature request?
A bug report

### Input Code
Zip Sample file: 
[monorepo.zip](https://github.com/babel/babel/files/1838669/monorepo.zip)

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["env"]
}
```

### Expected Behavior
I expected both imported modules to be transpiled when running the `pageserver`, but just one of them `graphql` is being transpiled.

### Current Behavior
Just one package is being transpiled (`graphql`). The second one (`authenticator`) is issuing errors:

Steps to reproduce:

a) Download ZIP code and extract in a folder (in my case  `monorepo`)

b) Build monorepo (`$ yarn`) and run `pageserver` (`$ yarn start`). Follow the steps below:

```
C:\>cd monorepo

C:\monorepo>yarn
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-d1cff77e-9c18-4634-b5f7-6d6f3083df08 > @monorepo/graphql > graphql-relay@0.5.4" has incorrect peer dependency "graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0".
[4/4] Building fresh packages...
Done in 11.39s.

C:\monorepo>cd packages/pageserver

C:\monorepo\packages\pageserver>yarn start
yarn run v1.5.1
$ nodemon --exec "cd ./src && babel-node server.js
[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `cd ./src && babel-node server.js`
C:\monorepo\packages\authenticator\src\index.js:2
import passport from "passport";
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at loader (C:\monorepo\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\monorepo\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/monorepo/packages/pageserver/src/server.js:24:1)
[nodemon] app crashed - waiting for file changes before starting...


```
### Context
Without this my monorepo will break.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | v6.9.2
| npm              | 5.7.1
| Operating System | Windows 10

Important: I cannot migrate to Babel7 due to other packages limitations.

**Comment by loganfsmyth** [comment]
In Babel 6, you'd have to put the `.babelrc` in the monorepo root if you need it to apply to all packages in the monorepo.
