### ISSUE TITLE
CLI --extensions ignored when traversing subdirectories

### ISSUE THREAD

**Issue by katrotz** [babel/babel#7620]
Choose one: is this a bug report or feature request?
Bug report

Given a project using Babel 7 with preset-typescript
When it is configured to compile all `.ts` files under a directory to a single output file via CLI command
Expected it creates a single output file with all sources compiled and concatenated
Actual it compiles only the first level directory, ignoring the `.ts` files in the nested directories.

### Input Code
The directory structure
```
src
   index.ts
   services
      service.ts
```

```js
// CLI command
node_modules/.bin/babel src/* --out-file dist/output.js --extensions .ts
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
The configuration is based on Babel 7 with env and typescript presets

```js
// package.json
{
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.42",
    "@babel/core": "^7.0.0-beta.42",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.42",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.42",
    "@babel/preset-env": "^7.0.0-beta.42",
    "@babel/preset-typescript": "^7.0.0-beta.42",
    "typescript": "^2.6.2"
  }
}

// .babelrc.js
module.exports = {
  "presets": [
    ["@babel/preset-env", {
      "modules": "umd"
    }],
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ],
  "only": [
    "src/**"
  ]
};

```

### Expected Behavior
Expecting that all typescript files under `src/` will be compiled and concatenated into a single file `dist/output.js`

### Current Behavior
The process compiles only files found in the first level directory `src/` ignoring the nested directory files eg. `src/services/service.ts`

### Possible Solution
The extensions override passed via CLI args is not propagated when filtering the files during dir walking, the filter method defaulting to `.js` extensions ignoring the `.ts`
https://github.com/babel/babel/blob/840ba187a7d6d4c29b56217b50d8b15fe73dd900/packages/babel-cli/src/babel/util.js#L30

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7
| node             | 6.2.2
| npm              | 3.9.5
| Operating System | MacOS

**Comment by sanohin** [comment]
Hi, you should run `node_modules/.bin/babel src/**/* --out-file dist/output.js --extensions .ts`, use http://www.globtester.com/ for twsting file matching

**Comment by katrotz** [comment]
Thanks for the input, but this does not fix the problem
The glob matching nested directories ignores parent directories:
- `src/**/*` will transpile only `src/services/service.ts`
- `src/*` will transpile only `src/index.ts`

As mentioned in the ticket, I think this is a Babel CLI bug.
Here is a [possible solution](https://github.com/babel/babel/compare/master...katrotz:issue-7620-babel-cli-extensions-override?expand=1) to correctly propagate the file extensions to file walker

**Comment by loganfsmyth** [comment]
I think you'd be able to do `src` without the `/*` and it would work fine.

**Comment by loganfsmyth** [comment]
You're right, this does seem like a bug. Do you want to make a PR with your proposed changes?
