### ISSUE TITLE
passPerPreset and babel-traverse cache

### ISSUE THREAD

**Issue by awto** [babel/babel#7621]
I use own traverse framework running on babel AST and so integrating well into all the babel toolchains. I use `passPerPreset` to delimit frameworks and it works pretty well on babel 6.

But now, I'm porting everything into babel 7, and I've got problems with a not invalidated babel-traverse cache. Basically if, say, my transform changes some variable declaration next babel-traverse based pass thinks it is the new one and complains about double declarations.

I can workaround the problem with `require("@babel/traverse").default.cache.clearScope()` but shouldn't there be some simpler solution, i.e. if it is `passPerPreset` invalidate the cache after each separate pass? or maybe some other option?

**Comment by awto** [comment]
I found the answer in babel-plugin-macros
```javascript
    /**
     * Other plugins that run before babel-plugin-macros might use path.replace, where a path is
     * put into its own replacement. Apparently babel does not update the scope after such
     * an operation. As a remedy, the whole scope is traversed again with an empty "Identifier"
     * visitor - this makes the problem go away.
     *
     * See: https://github.com/kentcdodds/import-all.macro/issues/7
     */
    state.file.scope.path.traverse({
      Identifier() {},
    })
```

**Comment by loganfsmyth** [comment]
Our scope caching is definitely not great right now, sorry. `passPerPreset` is a bit of an ugly hack too :(
