### ISSUE TITLE
How to polyfill using babel env target node 4?

### ISSUE THREAD

**Issue by reggi** [babel/babel#7630]
I am using array includes, and because I have my target set to node 4 I expected it to be polyfilled. 

```js
const i = ['john', 'mary', 'sue']
i.includes('john')
```

How can I get this working in node 4?

**Comment by theJian** [comment]
You can just import the specific polyfill.
https://github.com/zloirock/core-js

**Comment by existentialism** [comment]
@reggi what version of babel? are you using `useBuiltIns`? what does your babel config look like? (please fill out our issue template next time :D)

**Comment by hzoo** [comment]
yeah `@babel/preset-env` doesn't just add a polyfill randomly unless you use the new `usage` option
