### ISSUE TITLE
[Typescript] es6 import of JSX pragma is being removed

### ISSUE THREAD

**Issue by calebeby** [babel/babel#7631]
Bug Report

### Input Code

```js
import { h } from 'preact'
import Button from '.'

const foo = <Button type="submit" />
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
module.exports = {
  plugins: [
    '@babel/plugin-transform-modules-commonjs',
    ['@babel/plugin-transform-react-jsx', { pragma: 'h' }],
    '@babel/plugin-transform-typescript'
  ]
}
```

### Expected Behavior
I expect Babel to transform the es6 import of 'preact' into a require() call

### Current Behavior
Right now Babel removes the preact import because it sees it as unused, even though it is the jsx pragma. When I remove the typescript plugin, it works fine, except then it is unable to parse/transform typescript.

Here is what it does right now:
```js
"use strict";

var _ = _interopRequireDefault(require("."));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

const foo = h(_.default, {
  type: "submit"
});
```
As you can see, it removes the import of {h} from preact, instead of transforming it to a require

### Possible Solution
I'm not 100% sure about this, but it seems like the typescript plugin is doing some react-specific things for jsx, which makes it not work with preact and other jsx pragmas.
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/src/index.js#L269

### Context
I want to use these things together:
- Typescript
- JSX
- ES6 imports
- Preact

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | ^7.0.0-beta.42
| node             | v9.9.0
| npm              | 5.7.1
| Operating System | Arch Linux

**Comment by hzoo** [comment]
Sounds like it just doesn't take into account the pragmas and we didn't think about that case

**Comment by calebeby** [comment]
Sure, I'd be willing to look into fixing this. So would I need to retrieve the jsx pragma from the jsx transform plugin, and somehow use that in the typescript transform plugin?

**Comment by calebeby** [comment]
Or should I add an option to babel plugin typescript that specifies the jsx pragma?

**Comment by hzoo** [comment]
Yeah I think so, you would just read that (which now that I think about, I'm not sure how that would work) and then use that instead of the hardcoded value.

It brings up the idea of shared data/state in plugins @loganfsmyth @danez
