### ISSUE TITLE
allowAwaitOutsideFunction parser option

### ISSUE THREAD

**Issue by jdalton** [babel/babel#7634]
Just as there's a loose mode to allow top-level `return` it would be nice to have some kind of loose mode, `allowAwaitEverywhere`, or `allowAwaitOutsideFunction` option for top-level `await`.

**Comment by nicolo-ribaudo** [comment]
What would it be used to? I'd suggest wrapping your code in an async function before parsing it.

**Comment by jdalton** [comment]
There is now environments like REPLs which support top-level await. Being able to parse it would be great.

**Comment by hzoo** [comment]
Sounds fine to me, if someone wants to PR it

**Comment by jdalton** [comment]
🤘 Do you have an option name preference?

**Comment by hzoo** [comment]
Any of those work, open to ideas:

`allowAwaitEverywhere`
`allowAwaitOutsideFunction`
`allowTopLevelAwait`?

**Comment by jdalton** [comment]
Ok.

**Comment by jdalton** [comment]
Ok. I can prep a PR.

**Comment by jdalton** [comment]
WIP PR opened at #7637.

**Comment by hzoo** [comment]
Found some related issues as reference

https://github.com/babel/babel/issues/6703
https://github.com/babel/babel/issues/6720

**Comment by nicolo-ribaudo** [comment]
Implemented in #7637
