### ISSUE TITLE
babel-types validation only accepts Identifiers for ObjectTypeProperty.key

### ISSUE THREAD

**Issue by unconfident** [babel/babel#7635]
This is a bug report.

Say, we want to build type annotation like shown below with `@babel/types` 

```jsx
type Locales = {
  en: Object;
  "en-US": Object;
}
```

this is what it would look like:

```js
const t = require("@babel/types");

t.typeAlias(
  t.identifier('Locales'),
  null,
  t.objectTypeAnnotation([
    t.objectTypeProperty(
        t.identifier('en'),
        t.genericTypeAnnotation(t.identifier('Object'))
    ),
    t.objectTypeProperty(
        t.stringLiteral('en-US'), // spoiler: results in TypeError
        t.genericTypeAnnotation(t.identifier('Object'))
    )
  ]),
);
```

[This code on RunKit](https://runkit.com/unconfident/babel-types-7.0.0-beta.42-bug) 

And this is the error we get on version version 7.0.0-beta.42:

```
TypeError: Property key of ObjectTypeProperty expected node to be of a type ["Identifier"] but instead got "StringLiteral"
```

Not very confident in what I'm saying now but `StringLiteral` and `NumericLiteral` are perfectly valid keys afaik and they should be allowed there. Could be wrong

Relevant code: https://github.com/babel/babel/blob/a36525be45b905f8830a215f277c72f21481623a/packages/babel-types/src/definitions/flow.js#L290-L301

Slightly related issue: #6507

**Comment by nicolo-ribaudo** [comment]
@unconfident Would you mind opening a PR?

**Comment by unconfident** [comment]
> Not very confident in what I'm saying now but `StringLiteral` and `NumericLiteral` are perfectly valid keys afaik and they should be allowed there. Could be wrong

Looks like I was wrong after all. `NumericLiteral`s aren't supported by Flow. 
But `StringLiteral`s are

> Would you mind opening a PR?

I'll see what I can do, no promises

**Comment by nicolo-ribaudo** [comment]
> Looks like I was wrong after all. NumericLiterals aren't supported by Flow.
But StringLiterals are

This might be a bug with flow.
