### ISSUE TITLE
[plugin-transform-typescript] Default or named exported interface result in runtime error

### ISSUE THREAD

**Issue by ThaNarie** [babel/babel#7640]
### Input Code
```ts
interface IEvent {
  type: string;
}

export default IEvent;
```
### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": ["last 2 versions"],
        "node": "6"
      },
      "loose": true,
      "useBuiltIns": false
    }],
    "@babel/preset-stage-3",
    "@babel/typescript"
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": false,
      "moduleName": "@babel/runtime"
    }]
  ]
}
```

### Expected Behavior

Either:
* Not referencing (thus exporting) IEvent at all
* Or, setting IEvent to undefined/null/anything so parsing the file doesn't result in a runtime error

### Current Behavior

TS compilation results in:

```js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _default = IEvent; // <<< IEvent doesn't exist!
exports.default = _default;
```

Which results in the runtime error:
```js
Uncaught ReferenceError: IEvent is not defined
```

### Possible Solution
When stripping interfaces (or probably any non-value types), either:
* leave a placeholder value for exports
* or, detect references in exports and remove those exports

### Context
I'm using and re-exporting interfaces in my node modules' 'index.ts' file, so you can use them in other TypeScript projects, e.g.:

```ts
// index.ts
import { default as IEvent } from "./lib/IEvent";

// app.ts
import { IEvent } from "seng-event";
```

When publishing the package, the `tsc` also runs to generate `d.ts` files, which makes the code above work in a TS project (babel strips types and generates JS code, tsc generates the definitions).

**Workaround**
A workaround is to use named exports, since the faulty generated code only happens when using default exports.

```ts
export interface IEvent {
  type: string;
}
```

When using a named export, the export itself will be removed along with the interface, since it's a single statement. The (now empty) file will be imported somewhere, but will just result in an undefined value. This shouldn't matter, since Interfaces themselves are not used at runtime.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.42
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | macOS 10.13.3

### Related

Different but related to https://github.com/babel/babel/issues/7118 (where that's a syntax/parsing error, while this current issue is a runtime error)

---

Edit by @nicolo-ribaudo

This also doesn't work with `export { interface }` (https://github.com/babel/babel/issues/7641) - [repl](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FASwdgLgpgTgZgQwMZQAQEkCyBPAwgGwQGcjUBvYVVADwC5UwBXAWwCNYBuS1beptzsAC-wYEkIlUOAsVJRq0MABNSWPBNJkRweQAcA9jAjkp62QBoM0jaiFcgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=typescript%2Cenv&prettier=false&targets=Node-8&version=7.0.0-beta.34&envVersion=7.0.0-beta.33)

**Comment by nicolo-ribaudo** [comment]
Related: https://github.com/babel/babel/issues/7118

**Comment by ThaNarie** [comment]
@nicolo-ribaudo I noticed you changed the topic to include `or named`, but using named exports does work (and is a current workaround to keep using interfaces) :)

**Comment by infctr** [comment]
btw this also doesn't work
```js
export { IProps as IComponentProps }
```

**Comment by btmorex** [comment]
Not sure if what I'm seeing is related or a separate bug, but I experience the same behavior when there is anything else, but an exported interface in the file (but I'm not re-exporting imported interfaces). For example:

```typescript
interface A {}
export default A;
```

works fine, but:

```typescript
export const a = () => {};
interface A {}
export default A;
```

gives me a runtime error.

Note: I haven't tested the above in particular, but my cases are just as trivial.

**Comment by leethree** [comment]
I'm getting this as a compile time error: `SyntaxError: Export 'xxx' is not defined`

**Comment by nicolo-ribaudo** [comment]
There is an open PR for that error.

**Comment by rifler** [comment]
I've updated 
```
    "@babel/cli": "7.2.3",
    "@babel/core": "7.2.2",
    "@babel/plugin-proposal-class-properties": "7.3.0",
    "@babel/plugin-transform-runtime": "7.2.0",
    "@babel/preset-env": "7.3.1",
    "@babel/preset-react": "7.0.0",
    "@babel/preset-typescript": "7.1.0",
```

to the latest versions and code below stopped working with `SyntaxError: xxx.ts: Export 'MyType' is not defined`

```typescript
type MyType = { field: string };

export { MyType };
```

> There is an open PR for that error.

Where I can see it?

**Comment by rifler** [comment]
Oh, it breaks even if I do `npm i` instead of `npm ci`. Probably some indirect dependency updates in `package-lock.json`

**Comment by nicolo-ribaudo** [comment]
It's https://github.com/babel/babel/pull/9766. Sorry if I forgot to link it!

**Comment by leethree** [comment]
@nicolo-ribaudo The named exports are fixed but the default export is still broken in v7.4.5. Please reopen this issue.

REPL: https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgJIFEBuFzIN4BQyyYAngA4QBcyAzmFKAOYDcBAvgQRAB7kD2UMMgAmEeAFcANsIzZwbIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.4.5

**Comment by nicolo-ribaudo** [comment]
cc @airato do you want to take a look at this again?

**Comment by airato** [comment]
Yes, I'll take a look
