### ISSUE TITLE
[TypeScript]: Syntax error on "export { InterfaceName }" syntax

### ISSUE THREAD

**Issue by bodia-uz** [babel/babel#7641]
Choose one: is this a bug report or feature request?
bug report

`repl: Exporting local "InterfaceName", which is not declared.` error when exporting interface

### Input Code

http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FASwdgLgpgTgZgQwMZQAQEkCyBPAwgGwQGcjUBvYVVADwC5UwBXAWwCNYBuS1beptzsAC-wYEkIlUOAsVJRq0MABNSWPBNJkRweQAcA9jAjkp62QBoM0jaiFcgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=typescript%2Cenv&prettier=false&targets=Node-8&version=7.0.0-beta.34&envVersion=7.0.0-beta.33

**Comment by nicolo-ribaudo** [comment]
Can I merge this issue with https://github.com/babel/babel/issues/7640? They are not exactly the same thing, but I think that the fix is the same

**Comment by bodia-uz** [comment]
Hey. Yes. Please merge
