### ISSUE TITLE
Bug: Incorrect variable renaming with plugin-proposal-optional-chaining and plugin-transform-block-scoping

### ISSUE THREAD

**Issue by AndyBarron** [babel/babel#7642]
### Input Code

```js
if (true) {
  const foo = 'shadowed';
}
if (true) {
  const bar = {
    foo: 'foo',
  };
  const foo = bar?.foo;
}
```

### Babel Configuration

`.babelrc.js`
```js
module.exports = {
  plugins: [
    '@babel/plugin-transform-block-scoping',
    '@babel/plugin-proposal-optional-chaining'
  ],
};
```

### Expected Behavior
Local variable `foo` is set to the string 'foo'

### Current Behavior
Local variable `foo` is set to `undefined`

#### Compiled output:
```js
if (true) {
  var foo = 'shadowed';
}

if (true) {
  var bar = {
    foo: 'foo'
  };

  var _foo = bar === null || bar === void 0 ? void 0 : bar._foo;
}
```
You can see that **not only is the local variable `foo` getting renamed to `_foo`, but the property access on `bar` is getting renamed to `_foo` as well!**

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40 and 7.0.0-beta.42
| node             | 8.9.4 and 8.10.0
| npm              | 5.6.0 and 5.7.1
| Operating System | macOS 10.12.6 and 10.13.3

\* _Edited to reflect @existentialism's [comment](https://github.com/babel/babel/issues/7642#issuecomment-377120291)_

**Comment by cyrdax** [comment]
seeing this as well.  spent a lot of time debugging, very hard to find.

**Comment by jasongornall** [comment]
I got burned pretty hard by this a few hours ago.

**Comment by existentialism** [comment]
Reduced test case, with same input code:

```
{
  "plugins": [
    "@babel/plugin-transform-block-scoping",
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```
