### ISSUE TITLE
Testing preset-env with package.json, arrow functions not converted

### ISSUE THREAD

**Issue by hannwong** [babel/babel#7647]
**UPDATE**: The [API docs](https://babeljs.io/docs/usage/api/) does not say this, but I've confirmed that the JS API does not pick up anything from `package.json` at all.

---

Could be a bug report, but the bug could be me!

No matter how I tweak `targets.browsers`, the arrow function does not get converted.

Asked the same question on: https://stackoverflow.com/questions/49594252/testing-babel-preset-env-using-package-json

### Input Code

I create a JS script to test:

```js
    fs.readFile('my.js', 'utf8', (err, data) => {
      if (err) throw err;

      let babel = require("babel-core");
      let result = babel.transform(data).code;
    });
```

I test with arrow functions in `my.js`:

```js
    new Promise((resolve, reject) => {
      console.log('whatever');
    });
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

My `package.json` has:

```js
    "babel": {
      "presets": [
        [
          "env",
          {
            "targets": {
              "browsers": [
                "IE >= 8"
              ]
            }
          }
        ]
      ]
    },
```

### Expected Behavior

Converts arrow function to plain function.

**I'm assuming IE 8 does not support arrow functions.**

### Current Behavior

Does not convert arrow function to plain function.

### Context

Trying to assure myself that `babel-preset-env` works.

### Your Environment

I install `babel-core` and `babel-preset-env`:

    yarn add --dev babel-core
    yarn add --dev babel-preset-env

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0 (core)
| Babylon          | 
| node             | 8.11.1
| npm              | 5.6.0
| Operating System |  Mac OS High Sierra

**Comment by jdmallen** [comment]
I ran into this same issue, except mine was more specific. It converts them correctly for me everywhere except within return statements in exported functions.

## Example that works:

Source:

    const mapStateToProps = state => ({
        list: state.listReducer.list,
        hasErrored: state.listReducer.hasErrored,
        isLoading: state.listReducer.isLoading,
    });

Bundle:

    var mapStateToProps = function mapStateToProps(state) {
        return {
            list: state.listReducer.list,
            hasErrored: state.listReducer.hasErrored,
            isLoading: state.listReducer.isLoading
        };
    };

## Example that doesn't:

Source:

    export function listFetchData(url) {
        return (dispatch) => {
            dispatch(listIsLoading(true));
    
            axios.get(url)
                .then((response) => {
                    dispatch(listIsLoading(false));
                    return response;
                })
                .then(response => dispatch(listFetchDataSuccess(response.data)))
                .catch(() => dispatch(listHasErrored(true)))
                .finally(() => dispatch(listIsLoading(false)));
        };
    }

Bundle:

    function listFetchData(url) {
        return (dispatch) => {
            dispatch(listIsLoading(true));
    
            axios__WEBPACK_IMPORTED_MODULE_0___default.a.get(url)
                .then((response) => {
                    dispatch(listIsLoading(false));
                    return response;
                })
                .then(response => dispatch(listFetchDataSuccess(response.data)))
                .catch(() => dispatch(listHasErrored(true)))
                .finally(() => dispatch(listIsLoading(false)));
        };
    }

Note the arrow functions still present in the bundle, which blows up IE 11.

## Relevant files

Here's my `.babelrc`:

    {
        "presets": [["env", { "targets": { "browsers": ["defaults"] } }], "react"]
    }

And my `webpack.config.js`:

    const path = require("path");
    const ExtractTextPlugin = require("extract-text-webpack-plugin");
    const CleanWebpackPlugin = require("clean-webpack-plugin");
    
    const BUILD_DIR = path.resolve(__dirname, "wwwroot");
    const APP_DIR = path.resolve(__dirname, "ClientApp");
    
    const isProd =
      process.argv.indexOf("--optimize-minimize") > -1 ||
      process.argv.indexOf("-p") > -1;
    
    module.exports = {
        devtool: isProd ? "" : "source-map",
        entry: `${APP_DIR}/index.jsx`,
        module: {
            rules: [
                {
                    test: /\.(js)$/,
                    use: [
                        "eslint-loader"
                    ],
                    exclude: /node_modules/,
                },
                {
                    test: /\.(jsx)$/,
                    use: [
                        "babel-loader",
                        "eslint-loader"
                    ],
                    exclude: /node_modules/,
                },
                {
                    test: /\.scss$/,
                    use: ExtractTextPlugin.extract({
                        fallback: "style-loader",
                        use: [
                            {
                                loader: "css-loader",
                                options: {
                                    modules: true,
                                    localIdentName: "[name]__[local]___[hash:base64:5]"
                                }
                            },
                            "sass-loader"
                        ]
                    })
                },
            ]
        },
        output: {
            path: BUILD_DIR,
            filename: isProd ? "js/[name].bundle.min.js" : "js/[name].bundle.js"
        },
        plugins: [
            new ExtractTextPlugin("css/[name].css", { allChunks: true }),
            new CleanWebpackPlugin([BUILD_DIR] + "/*.*"),
        ],
        resolve: {
            extensions: [".js", ".jsx"]
        },
    };

And my `package.json` dependencies:

    "dependencies": {
        "@fortawesome/fontawesome": "^1.1.4",
        "@fortawesome/fontawesome-free-brands": "^5.0.8",
        "@fortawesome/fontawesome-free-regular": "^5.0.8",
        "@fortawesome/fontawesome-free-solid": "^5.0.8",
        "@fortawesome/react-fontawesome": "^0.0.18",
        "axios": "^0.18.0",
        "babel-plugin-transform-object-rest-spread": "^6.26.0",
        "lodash": "^4.17.5",
        "material-ui": "^0.20.0",
        "prop-types": "^15.6.1",
        "react": "^16.2.0",
        "react-dom": "^16.2.0",
        "react-redux": "^5.0.7",
        "redux": "^3.7.2",
        "redux-logger": "^3.0.6",
        "redux-thunk": "^2.2.0"
    },
    "devDependencies": {
        "babel-core": "^6.26.0",
        "babel-eslint": "^8.2.2",
        "babel-loader": "^7.1.4",
        "babel-preset-env": "^1.6.1",
        "babel-preset-react": "^6.24.1",
        "clean-webpack-plugin": "^0.1.19",
        "css-loader": "^0.28.10",
        "eslint": "^4.18.2",
        "eslint-config-airbnb": "^16.1.0",
        "eslint-loader": "^2.0.0",
        "eslint-plugin-import": "^2.9.0",
        "eslint-plugin-jsx-a11y": "^6.0.3",
        "eslint-plugin-react": "^7.7.0",
        "extract-text-webpack-plugin": "next",
        "file-loader": "^1.1.11",
        "husky": "^0.14.3",
        "lint-staged": "^7.0.0",
        "node-sass": "^4.7.2",
        "prettier": "1.12.0",
        "sass-loader": "^7.0.1",
        "style-loader": "^0.20.3",
        "url-loader": "^1.0.1",
        "webpack": "^4.5.0",
        "webpack-cli": "^2.0.14"
    },

I call webpack with `webpack --debug --mode "development" --config webpack.config.js`.

**Comment by loganfsmyth** [comment]
In order to load `.babelrc` and `package.json`-based configs, `babel.transform(data)` would need to also be given the filename, e.g.

```
babel.transform(data, { filename: 'my.js' })
```
