### ISSUE TITLE
ReferenceError: dataGlobal is not defined ???

### ISSUE THREAD

**Issue by elissaioskon** [babel/babel#7649]
i use webpack that use babel and i have an express server that is compiled from es6 with webpack nice.After add async await to my code there is an error regeneratorRuntime is not defined. After adding babel-polyfill as first line of the expressjs code i have an error ReferenceError: dataGlobal is not defined.
I also tried transform-runtime plugin but i have the same error.Any idea?

**Comment by xtuc** [comment]
The `dataGlobal is not defined` error isn't caused by Babel, but likely your application code.

**Comment by elissaioskon** [comment]
Finally it was my fault. I hadnt enable retain line and the bundle from webpack didnt show me the original line in code for the error. Thanks for the answer.

**Comment by xtuc** [comment]
No worries! I'm closing this.

**Comment by loganfsmyth** [comment]
@elissaioskon FYI `retainLines` isn't something I'd recommend. If you want real locations, best to rely on sourcemaps.
