### ISSUE TITLE
Space after commas not recognized when giving list to Babel CLI

### ISSUE THREAD

**Issue by karansingh1559** [babel/babel#7650]
# BUG REPORT
When adding presets for Babel from the babel CLI,  the following command works
    ```babel src/app.js --out-file=public/scripts/app.js --presets=env,react```
but, 
```babel src/app.js --out-file=public/scripts/app.js --presets=env, react```
doesn't work. 
The space between *env* and *react* makes babel throw the error:
```react doesn't exist```

Babel version -6.26.0 (babel-core-6.26.0)

**Comment by nicolo-ribaudo** [comment]
Is there any other cli app which supports spaces in parameters' value? I would expect `react` to be considered as a different parameter.

**Comment by loganfsmyth** [comment]
This seems like expected behavior to me. We could technically allow it if you put quotes around the whole parameter, but I don't see a ton of benefits to doing that.
