### ISSUE TITLE
[transform-modules-amd] Add option to add 'require' to amdArgs

### ISSUE THREAD

**Issue by justinfagnani** [babel/babel#7657]
Choose one: is this a bug report or feature request?: Feature request

I'm writing a dynamic import transform for AMD, and while the transform is quite simple, it requires the AMD module definition to depend on the `"require"` module ID. There's no easy way to add AMD dependencies with the current transform.

Here's the dynamic import transform for reference.

```ts
export const dynamicImportAMD = {
  inherits: dyanamicImportSyntax,
  visitor: {
    CallExpression(path: NodePath<CallExpression>) {
      if (path.node.callee.type as string === 'Import') {
        const specifier = path.node.arguments[0];
        path.replaceWith(ast`(new Promise((res, rej) => require([${specifier}], res, rej)))`);
      }
    },
  },
};
```

### Possible Solution
One solution is to add an option for extra module IDs to add to `amdArgs`. Another is to implement dynamic import directly in the AMD transform.

**Comment by loganfsmyth** [comment]
Would it work to add `import require from "require"` to the ES6 file?

**Comment by rictic** [comment]
The ES6 file shouldn't need to know that it's going to be transformed to AMD, should it? Different bundling strategies might want to use different ways of implementing dynamic import.

**Comment by loganfsmyth** [comment]
I think it kind of depends on the goals here. My comment is based on

> I'm writing a dynamic import transform for AMD

so presumably it would be safe to assume that importing `"require"` is safe.

That said, if this transform is _also_ meant to handle AMD modules written by hand, and not converted from ES6 modules, or needs to handle things that might run after the ES6 transform has already executed, things are more complicated.

Realistically it seems like adding the `import` or manually traversing up the AST looking for a `define` call would be necessary.

**Comment by rictic** [comment]
Ohhhh, injecting an ES6 import for `require` as part of the `dynamicImportAMD` pass. Yes, +1 to that solution. I thought you meant requiring that the original source code import 'require'.

**Comment by justinfagnani** [comment]
Ok, injecting ES6 imports totally works: https://github.com/Polymer/polymer-build/pull/348

**Comment by nicolo-ribaudo** [comment]
@justinfagnani Can this issue be closed?
