### ISSUE TITLE
async function work not properly.

### ISSUE THREAD

**Issue by vipcxj** [babel/babel#7672]
Choose one: is this a bug report or feature request?

### Input Code

```js
const sleep = async t => new Promise(resolve => setTimeout(resolve, t));

const delayReturn = (v, t) => {
  console.log(`v:${v}`);
  return async () => {
    await sleep(t);
    console.log(`v:${v}`);
    return v;
  };
};

//this is called by a callback trigger by user.
delayReturn(0, 500);
//after some seconds, this is called by a callback trigger by user.
delayReturn(1, 500);
//after some seconds, this is called by a callback trigger by user.
delayReturn(2, 500);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
  {
    presets: [
      [ '@babel/env', {
        modules: false,
        loose: true,
      } ],
      '@babel/react'
    ],
    plugins: [
      '@babel/proposal-object-rest-spread',
      ['@babel/proposal-class-properties', {
        loose: true,
      }],
    ]
  }
```

### Expected Behavior

This should be printed by the console.
```
v:0
v:0
v:1
v:1
v:2
v:2
```

### Current Behavior

However this is printed by the console.
```
v:0
v:0
v:1
v:0
v:2
v:1
```

### Possible Solution

I don't know.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.44
| Babylon          | 
| node             | v9.9.0
| npm              | v5.7.1
| Operating System | windows 10

**Comment by nicolo-ribaudo** [comment]
This code works on master:
```js
const sleep = async t => new Promise(resolve => setTimeout(resolve, t));

const delayReturn = (v, t) => {
  console.log(`v:${v}`);
  return async () => {
    await sleep(t);
    console.log(`v:${v}`);
    return v;
  };
};

(async function main() {
  delayReturn(0, 500)();
  await sleep(1000);
  delayReturn(1, 500)();
  await sleep(1000);
  delayReturn(2, 500)();
  await sleep(1000);
})();
```

**Comment by vipcxj** [comment]
@mAAdhaTTah  I don't understand your expected.
@nicolo-ribaudo I am sorry. I doesn't expain clearly. The function 'delayReturn' is triggered by a real person. So the person promise that the next call is after the previous call completed. They are not inside another async method.

**Comment by mAAdhaTTah** [comment]
@vipcxj I don't think we understand what your intention is. Can you provide a short, self-contained example?

**Comment by vipcxj** [comment]
[problem project](https://github.com/vipcxj/react-async-wrapper)
check code [here](https://github.com/vipcxj/react-async-wrapper/blob/master/stories/index.js#L262)
change the function to `delayReturn(this.state.value, 500)`.
start the story book server using script commond defined in the package.json. and in the last story, click the button. this trigger the function call. I have removed the `console.log` in the function.

**Comment by vipcxj** [comment]
I have publish the storybook which contain the problem
[story book](https://vipcxj.github.io/react-async-wrapper/)
[update async component/test1](https://vipcxj.github.io/react-async-wrapper/?selectedKind=update%20async%20component&selectedStory=test%201&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) work properly.
[update async component/test2](https://vipcxj.github.io/react-async-wrapper/?selectedKind=update%20async%20component&selectedStory=test%202&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) work not properly.

**Comment by loganfsmyth** [comment]
It's still not clear here what behavior is a Babel issue rather than an issue with async function usage. Could you write a self-contained example that prints `false` when it fails, or something?

**Comment by xtuc** [comment]
Not enough informations were provided, closing for now.
