### ISSUE TITLE
Top-level arrows that mistakenly use 'arguments' can cause unexpected runtime errors where there are none in an ES6 engine

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7673]
Reported on Slack yesterday.

### Input Code

```js
var foo = () => {
  console.log(arguments);
};
```

### Expected Behavior

Should be a silent no-op.

### Current Behavior

```js
var _arguments = arguments;
var foo = function() {
  console.log(_arguments);
};
```

throws an exception because there is no global `arguments` binding.

### Possible Solution
Maybe explicitly add extra logic when the arrow is top-level, e.g.
```js
var _arguments = typeof arguments === "undefined" ? undefined : arguments;
var foo = function() {
  console.log(_arguments);
};
```
this wouldn't throw properly if `foo` is actually called through, so possibly expand to

```js
var _arguments = typeof arguments === "undefined" ? undefined : arguments;
var foo = function() {
  console.log(_arguments === undefined ? throw new ReferenceError("...") : _arguments);
};
```
Still not 100% safe since sloppy code might technically have declared a variable named `arguments` that actually has `undefined` as a value? Not super likely though.

**Comment by nicolo-ribaudo** [comment]
Can't we just replace `argument` with `_arguments` when `arrowPath.getFunctionParent()` is `undefined`?

e.g.
```js
// Input
var foo = () => { arguments }; // Doesn't throw
foo(); // Uncaught ReferenceError: arguments is not defined

// Output
var foo = function() { _arguments }; // Doesn't throw
foo(); // Uncaught ReferenceError: _arguments is not defined
```

**Comment by loganfsmyth** [comment]
I think it depends on how many assumptions we want to make about how the output code will be executed. For instance of the code is being built and run via `eval` or something, there might actually be an `arguments` binding in the outer scopes, or maybe someone has done `window.arguments = "foo"` and is explicitly trying to get that value.

I don't think this case is super common either way, so personally I don't mind making the output extra verbose for this case.
