### ISSUE TITLE
DefaultFormatter code cleanup

### ISSUE THREAD

**Issue by eventualbuddha** [babel/babel#768]
Inside `DefaultFormatter` it seems that the [`hasLocalExports`](https://github.com/6to5/6to5/blob/fdc05cb977b80185a00ba05d6b8b682b6dfa7cc6/lib/6to5/transformation/modules/_default.js#L17) value is never used, and inside `exportsVisitor` it's setting `formatter.hasLocalImports = true` instead of `hasLocalExports`. I can't help feeling that this is a copy-paste error, but I don't have enough context to know whether `hasLocalExports` simply stopped being used, or whether there's a bigger issue here.

Removing the initial `this.hasLocalExports = false` in the constructor has no effect on the tests, but replacing `formatter.hasLocalImports = true` with `formatter.hasLocalExports = true` as described above actually does cause test failures.

**Comment by sebmck** [comment]
It's legacy code from when it handled binding collisions, this is now
handled in the scope tracking so It can safely be removed.

On Friday, 13 February 2015, Brian Donovan <notifications@github.com> wrote:

> Inside DefaultFormatter it seems that the hasLocalExports
> <https://github.com/6to5/6to5/blob/fdc05cb977b80185a00ba05d6b8b682b6dfa7cc6/lib/6to5/transformation/modules/_default.js#L17>
> value is never used, and inside exportsVisitor it's setting formatter.hasLocalImports
> = true instead of hasLocalExports. I can't help feeling that this is a
> copy-paste error, but I don't have enough context to know whether
> hasLocalExports simply stopped being used, or whether there's a bigger
> issue here.
>
> Removing the initial this.hasLocalExports = false in the constructor has
> no effect on the tests, but replacing formatter.hasLocalImports = true
> with formatter.hasLocalExports = true as described above actually does
> cause test failures.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/6to5/6to5/issues/768>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
What's the specific thing that this issue is tracking?

**Comment by eventualbuddha** [comment]
I was using code cleanup as an excuse to go through and learn how the project is setup. As far as I know there are no bugs caused by this. I'm thinking I might delete `this.hasLocalExports = false` and rename the `hasLocalImports` property to `hasLocalImportsOrExports`, since that seems to be how it's used. Can you think of a better name?

**Comment by sebmck** [comment]
@eventualbuddha Ah, it's all good. Just wanted sure if you were proposing some refactoring or something like that. The module formatter code is a like wonky and could definently use some cleanup since it's a little all over the place and some of the methods have undescriptive names and could also use comments.

**Comment by sebmck** [comment]
Closing this as this issue doesn't appear to be tracking a specific issue.
