### ISSUE TITLE
Preserve some comments in special scenarios?

### ISSUE THREAD

**Issue by sancarn** [babel/babel#7686]
This is a feature request/query

I'm running registering ruby scripts as javascript functions in my NodeJS application:

```js
rb["hello"] = function(){/*
    puts "hello world"
*/}
```

Can I tell babel to preserve specific comments? E.G.:

```js
/*
 Delete this comment
*/
// Also delete this comment
rb["hello"] = function(){/*#rb Preserve this comment
    puts "hello world"
*/}
```

**Comment by sancarn** [comment]
Someone on the Slack forum told me that my best bet was to use template strings instead.

**Comment by xtuc** [comment]
Closing, out of scope for now.
