### ISSUE TITLE
Setter default value

### ISSUE THREAD

**Issue by nikolayemrikh** [babel/babel#7688]
Default value in setter argument causes an error:

```js
const obj = {
	set field(num = 1) {this._num = num;},
	get field() {return this._num;}
};
```

Got unhandled error `setter should have exactly one param`, cause setter transpiled as:
```js
set field() {
	var num = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 1;
	this._num = num;
}
```

And it hasn't any argument.

Perfectly works in chrome without transpiling:

<img width="320" alt="2018-04-07 22 33 29" src="https://user-images.githubusercontent.com/11134770/38459556-b9f021d4-3ab3-11e8-8dd2-fd2c51f9d7fe.png">

**Comment by nikolayemrikh** [comment]
That would be good

**Comment by jridgewell** [comment]
Looks like setter methods can just opt into the loose transform?

**Comment by nikolayemrikh** [comment]
Working on this

**Comment by nicolo-ribaudo** [comment]
If you need help feel free to ask on slack.
