### ISSUE TITLE
Installing babel-preset-3 fails due to missing dep babel-plugin-transform-async-generator-function

### ISSUE THREAD

**Issue by csvan** [babel/babel#7696]
Running `yarn add babel-preset-stage-3` currently fails with:

```
error An unexpected error occurred: "Couldn't find package \"babel-plugin-transform-async-generator-functions@^6.24.1\" required by \"babel-preset-stage-3@^6.24.1\" on the \"npm\" registry.".
```

It seems like this package has been replaced with `babel-plugin-transform-async-to-generator`, but this is not reflected in the latest stable release.

**Comment by xtuc** [comment]
Could you please confirm that this is still an issue?
