### ISSUE TITLE
stringLiteralTypeAnnotation node creation function accepts no arguments but should accept 1

### ISSUE THREAD

**Issue by hendrikniemann** [babel/babel#7697]
Choose one: is this a bug report or feature request?

Bug!

### Input Code

```js
import * as T from '@babel/types';

T.stringLiteralTypeAnnotation('literal');
```

### Expected Behavior

This should create a new node of type string literal. String literals are literal types and need a value. In code this would look like this:

```js
const literal: 'literal' = 'literal';

// This is different from StringTypeAnnotation which needs no args:
const literal: string = 'literal';
```

This should create a node of this shape:

```json
{
  "type": "StringLiteralTypeAnnotation",
  "start": 15,
  "end": 24,
  "loc": null,
  "extra": {
    "rawValue": "literal",
    "raw": "'literal'"
  },
  "value": "literal"
}
```

### Current Behavior
Exception is thrown:
```
StringLiteralTypeAnnotation: Too many arguments passed. Received 1 but can receive no more than 0
```

### Possible Solution

I have no idea what I am doing but when I add the visitor `"value"` to the definition in `packages/babel-types/src/definitions/flow.js` it works as expected. Maybe I can prepare a PR but I really don't know if this is the actual fix. There are some more types that have the same mismatch of fields and visitors.

```diff
 defineType("StringLiteralTypeAnnotation", {
+  visitor: ["value"],
   aliases: ["Flow", "FlowType"],
   fields: {
     value: validate(assertValueType("string")),
```

### Context

I am building a type generator to create Flow type definitions for GraphQL queries. I use `@babel/types` to build ASTs and then `@babel/generator` to create the code. This is working so well so far, awesome work on babel 7. I absolutely love it ❤️ 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | @babel/types@7.0.0-beta.44

**Comment by nicolo-ribaudo** [comment]
`visitor` is used for properties which are nodes. IIRC you should use `builder`, you can check the `StringLiteral` definition. Di you want to open a PR?
