### ISSUE TITLE
@babel/register (by default) cannot apply .babelrc to files located on upper directories than cwd 

### ISSUE THREAD

**Issue by shinout** [babel/babel#7701]
This is a bug report. Occured on Babel7 (beta.44).

I've created a reproduction environment [here(github)](https://github.com/shinout/babel-register-with-upper-dir). Please see there for detail.

### Problem
`@babel/register` by default cannot apply `.babelrc` to files located on upper directories than current working directory.

Similar situations will be occurred when using [Yarn Workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) .

`babel-register` first creates default options (named `transformOpts` [here](https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L135)) which contains `ignore` and `only` fields based on the current working directory.

After that, `babel-core` filters files upper than cwd by `programmaticChain` [here](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/config-chain.js#L126) **before loading `.babelrc`**.

### Workaround
To avoid this behavior, passing babelrc-compatible options to `@babel/register` works fine.

**Comment by loganfsmyth** [comment]
I can leave this open now so that we can update it later, but this is essentially what the work around https://github.com/babel/babel/issues/6766 is attempting to address.

**Comment by shinout** [comment]
@loganfsmyth Thanks, I understood the essence of problem. Hope It will be fixed soon.

**Comment by vjpr** [comment]
I'm running into something similar. When trying to run a cli tool for example:

```
#!/usr/bin/env node

require('@babel/register')
require('./index')
```

It does not read the `package.json#babel` field.

This also doesn't work because it searches for programmatic presets from the cwd.

```
require('@babel/register'){
  presets: ["my-preset"],
}
```

This doesn't work either because it will search for presets within `my-preset` relative to cwd.

```
require('@babel/register'){
  presets: [require.resolve("my-preset")],
}
```

**Comment by loganfsmyth** [comment]
@vjpr Could you give more information about your directory structure and where files like `package.json` and `.babelrc` and `node_modules` and your preset are?

**Comment by vjpr** [comment]
@loganfsmyth 

```
/monorepo/packages/cli
/monorepo/packages/cli/index.js
/monorepo/packages/cli/package.json (preset is babel-preset-mine which is symlinked to by lerna)

/monorepo/babel.config.js
/monorepo/babelrc.js

/monorepo/packages/babel-preset-mine/index.js
```

And I want to run the package by simply running:

```
/monorepo/packages/cli/index.js
```

And I would expect it to transpile with local config.

**Comment by loganfsmyth** [comment]
Is the CLI tool expected to work after it is published? Is it supposed to use the monorepo-root config at all?

**Comment by vjpr** [comment]
> Is the CLI tool expected to work after it is published?

Yep.

> Is it supposed to use the monorepo-root config at all?

Nope.

**Comment by loganfsmyth** [comment]
You probably need to make sure that Babel has the right working directory, e.g.

    require('@babel/register')({ cwd: __dirname });

since you may or may not be running your CLI command with the same working directory.

It might be easier to work through this on Slack, if you're up for joining us there. Constant back and forth on Github is kind of slow.
