### ISSUE TITLE
Error: Options {"loose":true} passed to node_modules/babel-preset-env/lib/index.js which does not accept options.

### ISSUE THREAD

**Issue by Hendeca** [babel/babel#7702]
Hello!

I'm trying to update some of the dependencies for a project I made using React and Express and I'm running into the following error when I run `babel-node server.js --ignore public/`:

```
Error: Options {"loose":true} passed to <project_directory>/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "<project_directory>/node_modules/babel-preset-env/lib/index.js") (While processing preset: "<project_directory>/node_modules/babel-preset-env/lib/index.js") (While processing preset: "<project_directory>/node_modules/babel-preset-react/lib/index.js")
    at <user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (<user_directory>/.nvm/versions/node/v7.7.4/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
```

I've already tried solutions from [this issue](https://github.com/jhen0409/babel-preset-es2015-node6/issues/7) and issue #6130 which address a similar problem.

I'm using the babel react preset and the babel env preset in an express and react project with Webpack 4. Here is my .babelrc file:

```
{
    "presets": [
        ["react"],
        ["env", 
            {
                "targets": { "node": true }
            }
        ],
    ],
    "plugins": [
        ["transform-class-properties"],
    ],
}
```
My webpack.config.js:
```
let path = require('path');
let ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: './webpack.js',
  output: {
    path: __dirname + '/public',
    filename: 'bundle.js'
  },
  devtool: 'source-map',

  module: {
    rules: [
      {
        test: /\.js$/, // include .js files 
        exclude: /node_modules/, // exclude any and all files in the node_modules folder 
        use: {
          loader: 'jshint-loader',
          options: {
            browser: true,
            esversion: 6,
            node: true
          }
        }
      },
      {
        test: /\.js$/,
        use: 'babel-loader'
      },
      {
        test: /\.jsx$/,
        use: 'babel-loader'
      },
      { 
        test: /\.scss$/, 
        use: ExtractTextPlugin.extract({ 
          fallback: 'style-loader', 
          use: 'css-loader?sourceMap!postcss-loader!sass-loader?sourceMap'
        })
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin("./style.css")
  ]
};
```

And my environment:
| software         | version(s)
| ---------------- | -------
| babel                      | 6.26.0
| node                       | 7.7.4
| npm                        | 4.1.2
| webpack                | 4.5.0
| babel-preset-env | 1.6.1
| babel-loader         | 7.1.4
| Operating System | Mac OS X 10.13.3

Any help would be much appreciated! I haven't worked with Webpack 4 much and newer versions of Babel so it seems very possible I'm missing something small. Thanks!

**Comment by existentialism** [comment]
```
{
  test: /\.js$/,
  use: 'babel-loader'
},
{
  test: /\.jsx$/,
  use: 'babel-loader'
}
```

Looks like you're trying to compile babel-preset-env _with_ babel-preset-env? Consider excluding `node_modules` to your babel-loader config?

**Comment by loganfsmyth** [comment]
The stack trace shows `babel-register`, but you haven't shown the logic that is loading it. It sounds like it is probably being passed incorrect options.

**Comment by Hendeca** [comment]
@existentialism Ah, that makes sense! I've now changed the webpack.config.js file to:

```
let path = require('path');
let ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: './webpack.js',
  output: {
    path: __dirname + '/public',
    filename: 'bundle.js'
  },
  devtool: 'source-map',

  module: {
    rules: [
      {
        test: /\.js$/, // include .js files 
        exclude: /node_modules/, // exclude any and all files in the node_modules folder 
        use: {
          loader: 'jshint-loader',
          options: {
            browser: true,
            esversion: 6,
            node: true
          }
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.jsx$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      { 
        test: /\.scss$/, 
        use: ExtractTextPlugin.extract({ 
          fallback: 'style-loader', 
          use: 'css-loader?sourceMap!postcss-loader!sass-loader?sourceMap'
        })
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin("./style.css")
  ]
};
```

I'm still getting the error and I realized I was mistaken, the error actually occurs when I run `babel-node server.js --ignore public/` and not when I'm compiling with Webpack. I'll edit the original issue.

**Comment by Hendeca** [comment]
@loganfsmyth Yes, actually I'm not loading it and I don't really understand where it is being loaded. It's not in my package.json and isn't included in any of my files. I was under the impression that babel-cli was calling it but I don't know why that would be.

**Comment by loganfsmyth** [comment]
Ah yeah that makes sense then if you're using `babel-node`. `ignore` like that is dangerous currently, because the plugin itself will try to load. Maybe try `--ignore public,node_modules`?

**Comment by Hendeca** [comment]
@loganfsmyth Thanks this solved the problem! I almost forgot I was passing that option. I'm actually a bit confused about babel-node. I recently read that it should not be used in production. What is the proper way to start the server in production?

**Comment by loganfsmyth** [comment]
Most of the time the recommendation would be to have a `src` and `lib` directory, then compile the files first. Then in production you'd run `node` normally.

**Comment by loganfsmyth** [comment]
Also for what it's worth, this issue won't happen in Babel's next major version, since it is such a common issue for people.

**Comment by Hendeca** [comment]
@loganfsmyth Thank you very much for your help!
