### ISSUE TITLE
Unable to get current file name state.file.opts.filename is undefined

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/babel#7715]
*[bug report] Unable to get current file name in babel plugin*

### Input Code
```js
// part of my-awesome-plugin.js
...
   visitor: {
      StringLiteral(nodePath, state) {
        console.log(state.file.opts.filename);
      }
   }
...
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```js
import babelPresetEnv from '@babel/preset-env';

...

{
  {
    ast: false,
    babelrc: false,
    comments: true,
    compact: false,
    plugins: [
      'my-awesome-plugin'
    ],
    presets: [
    [ babelPresetEnv, {
      loose: true,
      modules: false,
      shippedProposals: true,
      targets: { chrome: 63 },
      useBuiltIns: false,
    }],
  ],
    retainLines: false,
  }
}
```

### Expected Behavior
`state.file.opts.filename` should have currently processed file name, but there is no sign of it anywhere.

### Current Behavior
`state.file.opts.filename` is undefined

### Possible Solution
It seems like it this info is not passed anymore during ast traverse

### Context
I'm trying to write my own plugin for babel that suppose to know current filename and do some transformation based on it

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  "7.0.0-beta.44" (also tested with "7.0.0-beta.41")
| node             | v9.5.0
| npm              | 5.7.1
| Operating System | macOS High Sierra 10.13.1

**Comment by loganfsmyth** [comment]
Would you be able to put together an example repo demonstrating this? As far as I know, it should still be there.

**Comment by yuri-karadzhov** [comment]
Sorry, my fault, I did pass the code instead of the file in that specific case, so no wonder it has no filename defined.

**Comment by loganfsmyth** [comment]
@probablyup Your test in https://github.com/styled-components/babel-plugin-styled-components/blob/master/test/no-tags/index.test.js#L9 doesn't pass Babel a filename.

**Comment by probablyup** [comment]
@loganfsmyth gotcha, thanks. Why was this working before though?

**Comment by loganfsmyth** [comment]
In Babel 6 I believe it auto-defaulted the name to `"unknown"`.
