### ISSUE TITLE
Lazy Init Tagged Template Literal Strings

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#7723]
Background
----------

The `strings` of a Tagged Template Literal (``` tagger`some${value}` ```) are cached, so that repeated invocations of the same Tagged Template Literal return the same `strings` instance:

```js
// Using tagger as a Tagged Template Literal will return the
// underlying Strings object that the JS language generates.
const tagger = (strings) => strings;

function text(value) {
  return tagger`some ${value} strings`;
}

const foo = text(); // => ["some ", " strings"]
const bar = text('hello'); // => ["some ", " strings"]

assert.ok(Array.isArray(foo));
assert.ok(Array.isArray(bar));

// Yes, even though bar was passed "hello".
// The expressions passed to the template literal (inside the `${}`)
// are not part of the Strings array. Only the literal strings are in it.
assert.equal(foo, bar);
```

The way Babel currently handles this Strings caching is by hoisting the array to the top of the file:

```js
// input
function text(value) {
  return tag`some ${value} strings`;
}

// output
var _templateObject = _helper_function_taggedTemplateLiteral(["some ", " strings"]);

function text(value) {
  // Notice, _templateObject.
  // That's the Strings
  return tag(_templateObject, value);
}
```

Notice how `_templateObject` is an array of strings that's hoisted to the top of the file? That means they're parsed and initialized long before they're actually used.

For very long strings, this can take up a lot of memory. And it's it's not used until much later in the application's lifecycle, it's just blocking initial renders.

Proposal
--------

We should make `_templateObject` (the Strings) lazy load:

```js
// input
function text(value) {
  return tag`some ${value} strings`;
}

// output
// No longer parsed or initialized
var _templateObject;

function text(value) {
  return tag(
    // Now that it's needed, we'll init
    // Next time it's called, it'll reuse the same Strings
    (_templateObject = _templateObject || _helper_function_taggedTemplateLiteral(["some ", " strings"])),
    value
  );
}

**Comment by kaushik94** [comment]
@jridgewell can I take this up?

**Comment by xtuc** [comment]
@kaushik94 yes sure! 

I would suggest you to join our Slack if you need any help.

**Comment by kaushik94** [comment]
Awesome, I will try to implement this and get back on it in 2-3 days.

**Comment by loganfsmyth** [comment]
We'll want to implement this on top of the changes in https://github.com/babel/babel/pull/7722. Make sure you're working off of that rather than `master`.

**Comment by kaushik94** [comment]
@loganfsmyth oh ok. I just took a look at the PR. So what I understood was that the `_templateObject`x variables need to be initiated but should only be assigned when required. Are there any more prerequisites I should know?

**Comment by kaushik94** [comment]
@jridgewell yes that's what I was thinking. Sure. I took a look at the PR, will be done by tomorrow.

**Comment by jridgewell** [comment]
How's it going @kaushik94?

**Comment by dczombera** [comment]
@kaushik94 If you don't have time to work on it I'd like to take over. ☺️ @jridgewell

**Comment by jridgewell** [comment]
Let's give him another day to respond.

**Comment by nicolo-ribaudo** [comment]
@dczombera You can take this

**Comment by jridgewell** [comment]
Yup, feel free to take it.
