### ISSUE TITLE
incompatibility between babel-cli and babel-preset-env versions  

### ISSUE THREAD

**Issue by ImanMh** [babel/babel#7738]
Bug Report

### Input Code

```
npm run transpile
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
// .bablerc
{
    "presets": [
      ["@babel/preset-env", {
        "modules": false
      }]
    ],
    "env": {
      "test": {
        "presets": [["@babel/preset-env"]]
      }
    }
}
```

```js
// package.json
  "scripts": {
    "babel": "babel",
    "transpile": "babel --out-file generators/app/index.js generators/app/index.es6"
  },
 "devDependencies": {
    "@babel/core": "^7.0.0-beta.41",
    "@babel/preset-env": "^7.0.0-beta.44",
    "babel-cli": "^7.0.0-beta.3"
  }
```

### Expected Behavior

To successfully transpile the code.

### Current Behavior

Outputting this error:
```
{ Error: [BABEL] generators/app/index.es6: Requires Babel "^7.0.0-beta.41", but was loaded with "7.0.0-beta.3". You'll need to update your @babel/core version. (While processing: "/Users/iman/Documents/github/yo-es-latest/node_modules/@babel/preset-env/lib/index.js")
```

### Possible Solution

Sounds like babel-cli is using it's own core not the core I installed with my package json. The core inside babel cli is version 7.0.0-beta.3. releasing a beta or alpha version of babel-cli with core 7.0.0-beta.41 will fix the issue. 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | v8.9.4
| npm              | 5.8.0
| Operating System | Mac Os

**Comment by loganfsmyth** [comment]
```
"@babel/preset-env": "^7.0.0-beta.44",
"babel-cli": "^7.0.0-beta.3"
```
should be
```
"@babel/preset-env": "^7.0.0-beta.44",
"@babel/cli": "^7.0.0-beta.44"
```

Also make sure you're using a lockfile or ditch `^`, since we're still making breaking changes to the beta, and using `^` here without a lockfile will automatically make you use the newest beta.

**Comment by ImanMh** [comment]
OMG I was searching in `babel-cli` npm for a day where I should look into `@babel/cli`. A depricated message would be helpful in `babel-cli` README.

**Comment by loganfsmyth** [comment]
@ImanMh Babel 7 still in beta. All of the website documentation is still for Babel 6. Once 7 is stable, we'll be doing a pass to update everything though.

**Comment by existentialism** [comment]
@ImanMh it is closed?

![image](https://user-images.githubusercontent.com/56288/39431426-4b39b3cc-4c56-11e8-94dc-979f1d4cde25.png)
