### ISSUE TITLE
[bug] Incorrect polyfills loaded with @babel/preset-env (useBuiltIns: 'usage')

### ISSUE THREAD

**Issue by independentgeorge** [babel/babel#7740]
Targeting any version of Edge with `useBuiltIns: "usage"` includes `Symbol` polyfill, which is fully supported in Edge 13.

`useBuiltIns: false` does not include it, as expected.

### Input

```js
const babel = require("@babel/core")

const code = "console.log(Symbol)"

const options = {
   presets: [["@babel/preset-env", { useBuiltIns: "usage", targets: { browsers: ["Edge 16"] } }]]
}

console.log( babel.transformSync(code, options).code )
```

### Output

```js
"use strict";

require("core-js/modules/es6.symbol");

console.log(Symbol);
```

### Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.44
| node             | 8.9.4
| npm              | 5.8.0
| Operating System | Windows 7

**Comment by zloirock** [comment]
`Symbol` polyfill added for Edge 13 target because it's required for unsupported in Edge 13 well-known symbols.

**Comment by zloirock** [comment]
I'm thinking about splitting `Symbol` polyfill in `core-js` to constructor, methods and well-known symbols definition, so in the future, in this case, can be loaded only required part of this polyfill. However, it will increase the size of the full bundle.
