### ISSUE TITLE
[TypeScript] Generic callable interface is not parsed correctly

### ISSUE THREAD

**Issue by Cu3PO42** [babel/babel#7742]
In TypeScript, it is possible to have callable interfaces and in particular the call signature can include generic type parameters. This might look like this:

```ts
interface Foo {
    <T>(bar: T): T;
}
```

When using the latest Beta version (v7.0.0-beta.44 at the time of writing) with `preset-typescript` and `preset-react`, this causes the following error:

```
repl: Unexpected token (2:2)

  1 | interface Foo {
> 2 |   <T>(bar: T): T;
    |   ^
  3 | }
```

When using only `preset-typescript`, this works as expected.

Also see this in the REPL [here](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIA8AKgHwAUARnFAFzLECU9xA3LgL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.0.0-beta.44&envVersion=).

Clearly this is an incompatibility between the two presets, I suspect `preset-react` gets to the `<` first, before `preset-typescript` has a chance to properly parse it.  
I can't think of any reason there would be JSX inside an interface definition, so it might be possible to temporarily 'disable' `preset-react` while inside such a scope?

A possible workaround is to not define the interface as callable and then build a union type with a function:

```ts
interface Foo_ {
  // Other properties...
}
type Foo = Foo_ & (<T>(bar: T) => T);
```

**Comment by chinesedfan** [comment]
I find it is due to jsx plugin parses `<>` as the start tag of jsx. But I don't know how to fix it.

**Comment by danez** [comment]
We had the same issue before with flow and jsx. I will try to find the old issue and see how it was fixed.
