### ISSUE TITLE
Type arguments on tagged templates

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7746]
TypeScript 2.9 *may* support providing type arguments to tagged template invocations. See the current pull request at https://github.com/Microsoft/TypeScript/pull/23430 for more details. I would advise nobody send any pull requests until the original PR lands in `master`.

To support this, Babel will likely need to implement

- [ ] Parsing support
- [ ] Emit support

**Comment by hzoo** [comment]
This is fixed by https://github.com/babel/babel/pull/7754 then 😁?
