### ISSUE TITLE
TypeScript type arguments on JSX tags

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7748]
TypeScript 2.9 will support passing type arguments to JSX tags. See the original pull request at https://github.com/Microsoft/TypeScript/pull/22415 for more details.

To support this, Babel will likely need to implement

- [ ] Parsing support
- [ ] Emit support

**Comment by majelbstoat** [comment]
I'm excited to see this fixed. It would greatly simplify a bunch of things within React, most notably for me usage of Apollo's `<Query>` and `<Mutation>` components.

**Comment by DanielRosenwasser** [comment]
Yup, hoping we can get it in soon. (P.S. does Medium use TypeScript? 😃)

**Comment by majelbstoat** [comment]
It uses Flow, but I recently left and am working on something new ;)
