### ISSUE TITLE
TypeScript import(...) types

### ISSUE THREAD

**Issue by DanielRosenwasser** [babel/babel#7749]
TypeScript 2.9 will support a new `import("foo")` syntax for referencing types in modules which have not been imported. See the original pull request at https://github.com/Microsoft/TypeScript/issues/14844 for more details.

To support this, Babel will likely need to implement

- [x] Parsing support
- [x] Emit support

**Comment by sebinsua** [comment]
Has any work been done on this?

**Comment by xtuc** [comment]
@sebinsua I think that no progress has been made yet. Do you want to work on it? Feel free to ask questions on our Slack.

**Comment by sebinsua** [comment]
@xtuc Where's the Slack?

**Comment by nicolo-ribaudo** [comment]
https://babeljs.slack.com/ (https://slack.babeljs.io/)

**Comment by lostfictions** [comment]
Confirming that Babel with `@babel/plugin-transform-typescript` throws with a parsing error when attempting to use a `let x: typeof import('foo')` annotation, as described [here](https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/).
