### ISSUE TITLE
Babel online repl issue

### ISSUE THREAD

**Issue by markpradhan** [babel/babel#7751]
Hi i skipped the template because this issue is very simple:

In the babel repl website the following doesn't log the right result in the console:

const helperArr = [...Array(4)].map((x, i) => i)
console.log(helperArr) // logs: [empty x 4]

But when you paste this in the console itself, it logs: [0, 1, 2, 3]

**Comment by nicolo-ribaudo** [comment]
Which version are you using? I can't reproduce this bug neither on v6 nor on master.

**Comment by markpradhan** [comment]
Hi!

I thought it was concise enough! But it looks like i can't replicate it either..
I'm not sure what went wrong before, now it logs correctly.

Thx for taking your time, and apologies for wasting it from my part 😅.

Closing.
