### ISSUE TITLE
transformAST formatting JSX differently

### ISSUE THREAD

**Issue by sreevisakh** [babel/babel#7756]
Bug Report

I am trying to a generate es6 code from ast. using transformFromAst.  
I have enabled jsx plugin for babylon for generating ast,
I have babel-eslint,airbrb, in my original code and eslint autofix enabled.

When I generate from ast JSX syntax looks different. Its not honouring attributes in seperate line, paranthesis in one line and jsx in next line etc

### Input Code
```
return (
  <div 
     className="test"
   >
     <div 
        className="sub"
     >
        Test
     </div>
   </div>
)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
bable.transformFromAst, plugins ['jsx']

### Expected Behavior
```
return (
  <div 
     className="test"
   >
     <div 
        className="sub"
     >
        Test
     </div>
   </div>
)
```
### Current Behavior
```
return (<div className="test" >
  <div className="sub">Test</div>
</div>)
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  babe-core : 6.26.0
| Babylon        | 6.18.0
| node             | 6.14.1
| npm              | 5.8.0 
| Operating System | macOS Sierra 10.12.6

**Comment by nicolo-ribaudo** [comment]
Keeping the original formatting isn't a goal of Babel. I suggest using `recast` for this, or passing the Babel output to prettier or to `eslint --fix`.
