### ISSUE TITLE
babel-preset-env always applies transform-async-to-generator and transform-regenerator

### ISSUE THREAD

**Issue by asazernik** [babel/babel#7757]
Bug Report

It does this even when the target browsers support the both async/await and generators.

Reproduction setup is [here](https://github.com/asazernik/babel-bug-repro); run `npm test` to see the error pop up (because I know bash better than NPM, the error message is "Failed to exec test script" if the test fails).

### Input Code

Contents of repo below for reader convenience

```js
async function thingy() {
  return await fetch('http://example.com/');
}

thingy();
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": [
        ["env", { "targets": "last 1 chrome versions" } ]
    ]
}

```

### Expected Behavior
Input code should be unmodified in output.

### Current Behavior
Babel transforms async/await to a generator, then the generator to use of regenerator-runtime.

### Context
I have a related bug (haven't reproduced it nicely, possibly bad usage) where I'm unable to get regenerator-runtime to set up a global variable before modules use the global to define their exported functions. This causes my web app to fail to load if I use async/await anywhere. Since I'm able to require users to be on new browsers, and I want to cut down my build size anyway, I'm trying to remove this dependency.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  ^6.26.0
| babel-preset-env          | ^1.6.1
| node             |  8.11.1
| npm              | 5.6.0
| Operating System | Linux (Ubuntu 17.10)

**Comment by hzoo** [comment]
Thanks for the question.

You need to do `targets.browsers`. Right now it's like if you didn't pass any options at all so it fails. https://github.com/babel/babel-preset-env/tree/1.x#targetsbrowsers

```
{
    "presets": [
        ["env", {
        	"targets": {
        		"browsers": "last 1 chrome versions"
    		}		
        }]
    ]
}

```

**Comment by asazernik** [comment]
Derp.
