### ISSUE TITLE
Feature: It would be awesome if we have a flag to add `// istanbul ignore next` before auxilary code.

### ISSUE THREAD

**Issue by ikarienator** [babel/babel#777]
For example, the comment can be added before `_slicedToArray` or `_classCallCheck`; or it can be added before object literal return wrapper: `if (typeof _ret === "object") return _ret.v;`;

**Comment by sebmck** [comment]
Hm, good idea. Just need to figure out what's the best way to implement this in case there's another comment that needs to be attached and what other auxilary code there is that'd need it.

**Comment by sebmck** [comment]
Added.

```sh
$ 6to5 script.js --auxilary-comment istanbul ignore next
```

```javascript
require("6to5").transform("code", { auxilaryComment: "istanbul ignore next" });
```

Only prepends it to helpers though currently so I'll need to work out what other code needs to be prepended.

**Comment by sebmck** [comment]
Whoops, forgot to close this. Available as of 3.6.6, let me know if there's any generated code that should be handled.

**Comment by michaelficarra** [comment]
It's spelled `auxiliary`. :bowtie: :abc:

**Comment by sebmck** [comment]
Fuck my life.

**Comment by sebmck** [comment]
Fixed as of 4.2.0 :relaxed:

**Comment by jayphelps** [comment]
![yougotthis](https://cloud.githubusercontent.com/assets/762949/6240728/4a9a8ba8-b6c7-11e4-9425-ddccddbaae80.gif)

**Comment by ikarienator** [comment]
Whoops... my fault...
