### ISSUE TITLE
Getters/Setters in Superclass called when loose defining Subclass

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#7771]
[Given](http://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=usage&code_lz=MYGwhgzhAEBCkFNoG8BQ1oHMEBdo4QhwAoBKFdaAX1RtVEhgHkAjAK2gQA8CA7AExjwISNBgD046ACUE_BADMAlrxWZoAW1wALAPb9o2hACcElAkTIoaNIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015-loose&prettier=false&targets=Node-4&version=7.0.0-beta.44&envVersion=7.0.0-beta.44):

```js
class Base {
  get test() {
  }
}

class Obj extends Base {
  // Redefining method here
  test() { }
}
```

This outputs:

```js
var Base = function () {
  function Base() {}

  _createClass(Base, [{
    key: "test",
    get: function get() {}
  }]);

  return Base;
}();

var Obj = function (_Base) {
  _inheritsLoose(Obj, _Base);

  function Obj() {
    return _Base.apply(this, arguments) || this;
  }

  var _proto = Obj.prototype;

  // Redefining method here
  _proto.test = function test() {};

  return Obj;
}(Base);
```

Notice we do `_inheritsLoose(Obj, _Base)` immediately, then do `Obj.prototype.test = function() {}`. This tries to set to a inherited property that's only a getter, so it throws in strict mode.

We could just do the `_inheritsLoose` after defining the prototype methods?

**Comment by nicolo-ribaudo** [comment]
> We could just do the _inheritsLoose after defining the prototype methods?

If it would work, yes. If we would need to use `Object.defineProperty` I think that we could keep this bug as a "loose mode thing", since it isn't very common to overwrite a setter with a method.

**Comment by jridgewell** [comment]
I can't think of any behavior that requires the prototype chain to be set so soon.

In strict mode, we have to use `defineProperty` to set non-enumerable methods, so they don't run into edge cases like this. But in loose, we don't care about enumerability. We could define the inheritance as the last step and everything would still be the same.

Even static class properties are defined after the class closure, so they would still get the same error treatment as now.

But we can get closer to spec behavior by just moving the inherit call later.
