### ISSUE TITLE
Bad insertion of `_possibleConstructorReturn` causes `ReferenceError: _this is not defined`

### ISSUE THREAD

**Issue by rattrayalex-stripe** [babel/babel#7781]
bug report

### Input Code

```js
class Target {}
class Parent {}
class X extends Parent {
  constructor(x) {
    if (true)  {
      return new Target(x)
    }
    super(x)
  }
}

new X(1)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

es2015 preset
babel v6.26.0 (I don't see a way to set it to 7 on the repl)

### Expected Behavior

When pasted into the chrome console, the result is 
```
> Target {}
```

### Current Behavior

```
ReferenceError: _this is not defined
```
which occurs at this line in the compiled output: 
```
return _ret = new Target(x), _possibleConstructorReturn(_this, _ret);
```
### Context

I'm doing some dark magic 😈(conditionally mocking react components). 

I worked around by using old-school class definition with function prototypes.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v6.26.0 (repl)

**Comment by nicolo-ribaudo** [comment]
> babel v6.26.0 (I don't see a way to set it to 7 on the repl)

You can try https://babeljs.io/repl/build/master

(Sorry for the short answer but I'm from the mobile)

**Comment by rattrayalex-stripe** [comment]
Ah, thanks! Looks like [it works](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEAqYCcDmBTALtA3gXwFCkhgAVEUA7DHfcKaADWhQA81yATY0irXaaYAPZkIaBAFdgaAQgAUTAJQ8-fAJYAzaDNFiUipcr4J0YhGWhkUAdziJUaOfN7K8BiGIAOKWQqd48-IQgBEBQAOhABJBkLazoZAEZ5eSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-beta.46&envVersion=1.6.2) on master; should we close this?
