### ISSUE TITLE
On update to version 7.00-beta.46 Get Decorators Support Error [BUG]

### ISSUE THREAD

**Issue by adeelibr** [babel/babel#7786]
This is error I get,
`
The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 (While processing`

**Comment by hzoo** [comment]
This is a specific/intentional breaking change we made to beta.45

https://github.com/babel/babel/pull/7734

This is because we want the Stage 2 behavior to be default before the final 7.0 release but we currently want people to opt-into decorators legacy instead. However We have a side effect of the stage presets having to pass all the options down (and why Logan is suggesting we also do https://github.com/babel/babel/issues/7770)

**Comment by adeelibr** [comment]
Can you kindly update the docs, as to how to resolve this breaking change. As to what changes are required to make in `.babelrc` file.

**Comment by adeelibr** [comment]
My `.package.json` file's dev dependencies look something like this.

`"devDependencies": {
    "@babel/core": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.44",
    "@babel/preset-react": "^7.0.0-beta.44",
    "@babel/preset-stage-2": "^7.0.0-beta.44",
    "babel-loader": "^8.0.0-beta.2",
    "css-loader": "^0.28.11",
    "copy-webpack-plugin": "^4.5.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.8.3",
    "sass-loader": "^6.0.7",
    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14",
    "webpack-dev-server": "^3.1.3"
  },`

and my `.babelrc` file looks like this

`
{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
    "@babel/preset-stage-2"
  ]
}
`
This was working fine 2-3 days ago, but today when I shipped I got the error for 

`The new decorators proposal is not supported yet. You must pass the"decoratorsLegacy": trueoption to @babel/preset-stage-2 (While processing`

**Comment by hzoo** [comment]
> The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2

I think the error message is correct? I believe I made it pretty clear above, but it's

```diff
{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
+    ["@babel/preset-stage-2", { "decoratorsLegacy": true }]
-    "@babel/preset-stage-2"
  ]
}
```

Also like I mentioned if you use `"@babel/core": "^7.0.0-beta.44",` and we make an intentional breaking change it will break the build automatically. That's why I'm suggesting people pin the version while in beta (we've tried to suggest this since it's not released but difficult to get that message across especially when it's the default)

**Comment by adeelibr** [comment]
Thank you so much for reaching out & helping with this, I'll write an article about this with a publication like freeCodeCamp & try to spread the word out.

**Comment by hzoo** [comment]
> I'll write an article about this with a publication like freeCodeCamp & try to spread the word out.

I'm a bit confused, is this article about this bug, about Babel 7, or my comment about pinning the version in beta?

Was the error message not clear enough in your opinion? I know it assumes knowledge about presets/options.

I'm going to close this either way though! Thanks.

**Comment by loganfsmyth** [comment]
So everyone's on the same page here. Babel is still in beta, and we are still making breaking changes. If you are using a prerelease version of any package, you should be using a lockfile and only upgrading it when you're ready to test out the new version, just like if it were a new major version release.

Personally I wouldn't use `^` in the version at all, but if you want to, you _must_ at least use a lockfile.

**Comment by adeelibr** [comment]
By writing an article I meant about this that if you are using babel 7 in beta mode you should not use `^` because at any time there can be breaking changes. @hzoo

**Comment by AdamKochanski** [comment]
I just try to make fresh installation and I have same errors. It's a little bit confused for new people. :/

**Comment by markusenglund** [comment]
This doesn't make any sense to me. I'm not using decorators anywhere in my code but still getting this error. Is that intentional?

**Comment by nicolo-ribaudo** [comment]
Yes. If you are using a stage <= 2 preset, you are asking Babel to transpile decorators, even if you actually don't use them

**Comment by hzoo** [comment]
Due to that consequence ^ we are considering removing the stage presets https://github.com/babel/babel/issues/7770.

**Comment by markusenglund** [comment]
I see. Still, it doesn't seem reasonable that the default behaviour of stage <= 2 presets is to crash the build.

**Comment by loganfsmyth** [comment]
@markusenglund The idea initially was that we'd require the flag in the short-term until we finished implementing the standard-compliant version of decorators as a replacement, and then that would be the default behavior. Now that we're removing the preset, it'll be up to people to do the right thing when they use the individual plugins.

**Comment by markusenglund** [comment]
Are you definitely gonna drop the stage <= 2 presets?

**Comment by Tsury** [comment]
So what configuration do I need to use now if I'd like to use decorators as I've previously used (I use decorators for mobx).

**Comment by nicolo-ribaudo** [comment]
`["@babel/plugin-transform-decorators", { "legacy": true }]`

**Comment by Tsury** [comment]
@nicolo-ribaudo There's no such thing as `@babel/plugin-transform-decorators`, only `babel/plugin-transform-decorators`. Did you mean this one?

**Comment by vuldin** [comment]
Don't want to speak for @nicolo-ribaudo but he probably meant `@babel/plugin-proposal-decorators`

**Comment by Tsury** [comment]
Well that's the one I was already using. Adding `legacy = true` makes babel complain that the decorators experimental feature is not turned on...

**Comment by nicolo-ribaudo** [comment]
@vuldin Tuo, thank you!

@Tsury Can you show your configuration and the error message?
