### ISSUE TITLE
babel-preset-env with useBuiltins neglects es7 promise features for some targets

### ISSUE THREAD

**Issue by cmswalker** [babel/babel#7795]
### is this a bug report or feature request?
Bug

babel-preset-env with useBuiltins neglects es7 promise features for some targets.

`Promise.finally` and `Promise.try` are not included from `core-js`

### Input Code

```js
Promise.resolve().then().catch().finally();
```

### Babel Configuration (.babelrc)

```json
{
    "plugins": [
        "transform-object-rest-spread",
        "transform-class-properties",
        "lodash"
    ],
    "presets": [
        [
            "env",
            {
                "debug": true,
                "useBuiltIns": true,
                "modules": false,
                "targets": {
                    "browsers": [
                        "last 2 versions",
                        "Explorer >= 10",
                        "iOS >= 8.3"
                    ]
                }
            }
        ],
        "react"
    ]
}

```

### Expected Behavior
Because this is meant to support IE >= 10, es7 promise features should be imported.

### Current Behavior
However they are not. Here is debug output

```sh
...
...
es6.math.tanh {"android":"4.4.3","ie":"10"}
es6.math.trunc {"android":"4.4.3","ie":"10"}
es7.array.includes {"android":"4.4.3","ie":"10","ios":"9"}
es7.object.values {"android":"4.4.3","ie":"10","ios":"9"}
es7.object.entries {"android":"4.4.3","ie":"10","ios":"9"}
es7.object.get-own-property-descriptors {"android":"4.4.3","ie":"10","ios":"9"}
es7.string.pad-start {"android":"4.4.3","ie":"10","ios":"9"}
es7.string.pad-end {"android":"4.4.3","ie":"10","ios":"9"}
web.timers {"chrome":"64","android":"4.4.3","edge":"15","firefox":"58","ie":"10","ios":"9","safari":"10.1"}
...
...etc
```

### Possible Solution
Not sure why, but it seems like the builtins for IE assume a different Promise.prototype

### Context
I have fixed it by directly adding additional imports directly from core-js in my entrypoint

```js
import 'babel-polyfill';

// babel -> core-js shims that aren't yet fully supported
import 'core-js/modules/es7.promise.finally'; // eslint-disable-line import/no-extraneous-dependencies
import 'core-js/modules/es7.promise.try'; // eslint-disable-line import/no-extraneous-dependencies
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  ^6.26.0
| node             |  8.9.1
| npm              |  5.5.1
| Operating System |  Mac OS X 10.12.6

**Comment by nicolo-ribaudo** [comment]
That are not part of es7.

ES7 features are marked as `2016`  at https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by cmswalker** [comment]
I don't understand. Promise.finally appears in that link you provided along with the majority if the other es7 features I posted

**Comment by cmswalker** [comment]
Thanks for the clarification

**Comment by bsuh** [comment]
@existentialism Doesn't seem like it's supported using `useBuiltIns: "usage"`. Will https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/built-in-definitions.js be updated to add finally to `instanceMethods`? I can open a PR if you'd like, not sure if you'd want to just add Promise.prototype.finally to built-in-definitions.js or add other ES2018 things (not sure if there's other stuff that'd need to be added) in there in one go.

**Comment by zloirock** [comment]
@bsuh it's added in #7646

**Comment by Cicicok** [comment]
@cmswalker is your 'fix' working in Edge as well? I'm using this solution because of IE11 compatibilty, but can't get it working in Edge.

Another funny thing is, if I change the import order to:
import "core-js/modules/es7.promise.finally";
import "babel-polyfill";

Edge is working, but IE11 no.

**Comment by bradennapier** [comment]
This doesnt work for node...

### .babelrc

```javascript
{
  presets: [
    "@babel/preset-flow",
    [
      "@babel/preset-env",
      {
        debug: true,
        useBuiltIns: "usage",
        targets: {
          node: "8.10"
        }
      }
    ]
  ],
  plugins: ["@babel/plugin-proposal-class-properties"]
}
```

### Debug Output:

```
Using plugins:
  proposal-async-generator-functions { "node":"8.10" }
  syntax-object-rest-spread { "node":"8.10" }
  proposal-unicode-property-regex { "node":"8.10" }

Using polyfills with `usage` option:

[/Users/Shared/Development/projects/aws-lambda-runner/lib/plugin.js] Based on your code and targets, none were added.

[/Users/Shared/Development/projects/aws-lambda-runner/lib/runner.js] Based on your code and targets, none were added.
```

### Transpiles To:

```javascript
if (typeof runner === 'function') {
      return runFunctionInstance(runner, config, event, context, callback).then(({
        result: _result,
        data: _data
      } = {}) => {
        // code
      }).catch(err => {
        // code
      }).finally(async () => {
        // code
    }
```

### When Run by Node 8.10 as specified:

```
2018-07-10T01:41:09.326Z	5181d267-83e2-11e8-8df6-5bb8f152a769	TypeError: runFunctionInstance(...).then(...).catch(...).finally is not a function
    at runAWSLambdaRunnerStartupEvaluation (/var/task/node_modules/aws-lambda-runner/dist/runner.js:162:17)```

**Comment by jsnajdr** [comment]
@bradennapier That indeed seems to be a bug. In order for `useBuiltIns: "usage"` to add the `finally` polyfill, there would need to be a record for `finally` in the `instanceMethods` map [here](https://github.com/babel/babel/blob/6dca0ff9bf75bc71039ca4eca045a7f17e93a25e/packages/babel-preset-env/src/built-in-definitions.js#L32). But it's missing.
