### ISSUE TITLE
@babel/cli throws: “Unknown option: .configFile”

### ISSUE THREAD

**Issue by davidaurelio** [babel/babel#7797]
Choose one: bug

Minimal invocation of @babel/cli v7.0.0-beta.46 throws `Unknown option: .configFile`

### Input Code

```sh
echo | npx babel --no-babelrc
echo | npx babel -f x.js
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

No configuration

### Expected Behavior

empty output

### Current Behavior
```
ReferenceError: Unknown option: .configFile. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    at buildUnknownError (.../node_modules/@babel/core/lib/config/validation/options.js:97:11)
    at .../node_modules/@babel/core/lib/config/validation/options.js:83:57
    at Array.forEach (<anonymous>)
    at validate (.../node_modules/@babel/core/lib/config/validation/options.js:61:21)
    at loadConfig (.../node_modules/@babel/core/lib/config/index.js:37:48)
    at .../node_modules/@babel/core/lib/transform.js:26:33
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

### Your Environment

@babel/cli@7.0.0-beta.46

**Comment by davidaurelio** [comment]
This works in beta.44

**Comment by loganfsmyth** [comment]
Sounds like you may be using a `beta.46` of the `@babel/cli`, but using a mismatched `beta.44` for `@babel/core`?

Since we're still in beta and making breaking changes, it is important that the versions match up.

**Comment by davidaurelio** [comment]
I actually messed up the peerDependency. Sorry about the fuzz, let me close this…

**Comment by gajus** [comment]
FYI You get this error as well if you forget to install `@babel/core`.
