### ISSUE TITLE
Babel Preset Env with Loose produces invalid code (variable redeclaration) [v7]

### ISSUE THREAD

**Issue by swernerx** [babel/babel#7817]
## Bug Report

When transpiling `for...of` loops with `@babel/preset-env` it produces code with a redeclaration of the loop iterator. This problematic code might produce issues with follow-up plugins like `fast-async` which logs warnings about this issue. This issue happens to be in `loose: true` mode only!

### Input Code

```js
async function executeTasks(tasks) {
  for (const taskName of tasks) {
    try {
      await executeCommands()
    } catch (error) {
      console.error("Error")
    }
  }
}
```

I made a small repository for reproduction: https://github.com/swernerx/babel-for-of-loose-redeclared

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [ "@babel/env", {
      "loose": true,
      "exclude": [ "transform-regenerator", "transform-async-to-generator" ]
    }]
  ]
}
```

### Expected Behavior

The preset should produce valid code. I know that it is not really broken - but I figure we can agree on the fact that such a core preset should not produce such code.

### Current Behavior

There is a redeclaration of the `_iterator` variable.

```js
async function executeTasks(tasks) {
  for (var _iterator = tasks, _isArray = Array.isArray(_iterator), 
    _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
...
```

### Possible Solution

Most trivial solution would be to use a new variable for the first assignment - see `iteratorInput`:

```js
"use strict";

async function executeTasks(tasks) {
  for (var _iteratorInput = tasks, _isArray = Array.isArray(_iteratorInput), 
    _i = 0, _iterator = _isArray ? _iteratorInput : _iteratorInput[Symbol.iterator]();;) {
    var _ref;

    if (_isArray) {
      if (_i >= _iterator.length) break;
      _ref = _iterator[_i++];
    } else {
      _i = _iterator.next();
      if (_i.done) break;
      _ref = _i.value;
    }

    var taskName = _ref;

    try {
      await executeCommands();
    } catch (error) {
      console.error("Error");
    }
  }
}
```

### Context

I am working on my Babel Preset Edge: https://github.com/sebastian-software/babel-preset-edge

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.46
| node             | 6
| npm              | 10
| Operating System | macOS 10.13.4

**Comment by swernerx** [comment]
Sure it's valid in the technical sense, but marginally. I figure most eslint presets would regard this as bad style.

**Comment by nicolo-ribaudo** [comment]
Closing since Babel is producing correct output here. Babel's output shouldn't follow best practice desined for humans, but what it is best for itself.
