### ISSUE TITLE
Babel transform hide ReferenceError with non-hoisted variables

### ISSUE THREAD

**Issue by djfdev** [babel/babel#7823]
Bug report

### Input Code

The following will build without error in Babel:

```js
const fn = () => {
  if (x) return x
  let x = true
}

fn() // ReferenceError: x is not defined
```

However, when ES6 transform is applied, the `let` declaration transpiles into a `var`, which is hoisted and run without error

```js
var fn = function fn() {
  if (x) return;
  var x = true;
};

fn(); // OK
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["babel-preset-env", {
      "targets": {
        "browsers": ["last 2 Chrome versions"],
        "uglify": true
      }
    }]
  ]
}
```

### Expected Behavior

I would expect Babel to warn me that my un-transpiled code would have caused an error, but the transpiled code prevents that error.

### Current Behavior

I can introduce a bug in my code without realizing it, because the transpiled version fixes said bug.

### Context

I actually removed the `uglify` option from my Babel configuration because I did not want to transpile everything into ES5 syntax. Suddenly, I was getting a `ReferenceError` in my code that previously worked fine.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 8.11.1
| npm              | 5.6.0
| Operating System | High Sierra

**Comment by xtuc** [comment]
Yes that's a known-issue, probably a duplicated one. Could you please search for existing issue?

**Comment by loganfsmyth** [comment]
We talked on Slack, so I think this is good to close.
