### ISSUE TITLE
Need to help: Template literals, backticks on IE 11 not working 

### ISSUE THREAD

**Issue by hieuhuynhtps** [babel/babel#7836]
hello everyone,
At the moment, I have an issue with template literals, backticks are not working on IE 11.
I have research and found Babel, tried to add my app, but it's not working.
Can anyone please help me how to apply it to my app?

Info:
- Angular: 4.0.1
- Webpack: 2.3.2

Thanks.

**Comment by nicolo-ribaudo** [comment]
Can you show how you are currently applying it? You should have a `.babelrc` file on your project root, `babel-loader` in your webpack config and babel-preset-env to transpile all currently standard JavaScript so that it is supported by the specified browsers.

**Comment by hieuhuynhtps** [comment]
I tried to add:
.babelrc
`{
    "presets": ["es2015"]
}`

package.json
`
....  
"devDependencies": {
    "@angular/cli": "^1.5.2",
    "@angular/compiler-cli": "^5.0.1",
    "@angular/platform-server": "^5.0.1",
    "@ngtools/webpack": "^1.8.0",
    "@types/core-js": "0.9.40",
    "@types/highcharts": "5.0.12",
    "@types/jasmine": "2.5.47",
    "@types/node": "7.0.12",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.1.2",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-es2015": "^6.24.1",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "^2.1.2",
    "file-loader": "0.10.1",
    "html-loader": "0.4.5",
    "html-webpack-plugin": "2.28.0",
    "jasmine-core": "2.5.2",
    "json-loader": "0.5.4",
    "karma": "1.5.0",
    "karma-jasmine": "1.1.0",
    "karma-mocha-reporter": "2.2.3",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.3",
    "node-sass": "^4.5.3",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "^2.1.0",
    "rimraf": "2.6.1",
    "sass-loader": "^6.0.6",
    "script-loader": "^0.7.2",
    "style-loader": "^0.18.2",
    "ts-helpers": "1.1.2",
    "typescript": "2.2.2",
    "uglifyjs-webpack-plugin": "^1.0.1",
    "webpack": "2.3.2",
    "webpack-dev-server": "2.4.2",
    "webpack-merge": "4.1.0"
  }`


webpack.config.js
`const webpack = require('webpack');
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin')
const helpers = require('./helpers');
const AotPlugin = require('@ngtools/webpack').AotPlugin;

module.exports = function() {
    return {
        resolve: {
            extensions: ['.ts', '.js', '.json'],
            modules: [
                helpers.root('src'),
                helpers.root('node_modules')
            ],
        },
        // Entry points the bundles
        entry: {
            'polyfills': helpers.root('src', 'polyfills.ts'),
            'vendor': helpers.root('src', 'vendor.ts'),
            'app': [
                helpers.root('src', 'main.ts'),
                helpers.root('src', 'assets', 'styles', 'main.scss'),
            ],
        },
        module: {
            loaders: [{
                    test: /\.ts$/,
                    loader: '@ngtools/webpack'
                },
                {
                    test: /\.html$/,
                    loader: 'html-loader'
                }
            ],
            rules: [{
                    test: /\.js$/, // files ending with .js
                    exclude: /node_modules/, // exclude the node_modules directory
                    loader: "babel-loader" // use this (babel-core) loader
                },
                // Compiles all .ts files
                {
                    test: /\.ts$/,
                    loaders: ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular-router-loader'],
                    exclude: /\.spec\.ts$/
                },
                // Injects all html templates into their components and loads referenced assets
                {
                    test: /\.html$/,
                    loader: 'html-loader',
                    exclude: helpers.root('src/index.html')
                },
                // Copies all images and fonts into dist/assets
                {
                    test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|otf)$/,
                    loader: 'file-loader?name=assets/[name].[ext]'
                },
                // Puts all styles from assets/styles/main.scss in a separate file
                {
                    test: /\.scss$/,
                    exclude: helpers.root('src', 'app'),
                    use: ExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        //resolve-url-loader may be chained before sass-loader if necessary
                        use: [
                            'css-loader',
                            'resolve-url-loader',
                            'sass-loader?sourceMap'
                        ]
                    })
                },
                // Injects all angular styles into their components
                {
                    test: /\.scss$/,
                    include: helpers.root('src', 'app'),
                    loaders: ['raw-loader', 'sass-loader']
                },
                // Loads all "required" json files into their components
                {
                    test: /\.json$/,
                    loader: 'json-loader'
                },
                {
                    test: /\.css$/,
                    exclude: helpers.root('src', 'app'),
                    loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap' })
                },
                {
                    test: /\.css$/,
                    include: helpers.root('src', 'app'),
                    loader: 'raw-loader'
                }
            ]
        },
        plugins: [
            // File name for the extracted styles
            new ExtractTextPlugin("ontrack.css"),
            // File name for the extracted styles
            new webpack.optimize.CommonsChunkPlugin({
                name: ['app', 'vendor', 'polyfills']
            }),
            // Provides context to Angular's use of System.import
            // See: https://github.com/AngularClass/angular2-webpack-starter/issues/993#issuecomment-283423040
            new ContextReplacementPlugin(
                /angular(\\|\/)core(\\|\/)@angular/,
                helpers.root('src')
            ),
            // Generates an HTML5 file that includes all webpack bundles
            new HtmlWebpackPlugin({
                template: helpers.root('src', 'index.html'),
                favicon: helpers.root('src', 'favicon.ico')
            }),
            new CopyWebpackPlugin([{
                from: 'node_modules/monaco-editor/min/vs',
                to: 'vs',
            }]),
        ],
        performance: {
            hints: false
        }
    };
};`

and run with code:
`new Function("var text = `Welcome`; return console.log(text)")();
`
it's show error message: "Invalid character"

**Comment by nicolo-ribaudo** [comment]
Babel doesn't transpile `Function` and `eval`, because it can't be done statically but it needs to be done at runtime. This means that the whole Babel code (several MBs) would be included as a polyfill in your application.

If you use
```js
(function () { var text = `Welcome`; return console.log(text) })();
```
it should work.

PS. I formatted your comment, you should use three ``` for code blocks.
