### ISSUE TITLE
Array.prototype.find and .findIndex call callback for unassigned array items

### ISSUE THREAD

**Issue by epoberezkin** [babel/babel#784]
According to spec, callback should not be called for such items
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by zloirock** [comment]
New `Array.prototype` methods should not ignore holes. See [spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-array.prototype.find).

**Comment by epoberezkin** [comment]
Thanks! Interesting...
