### ISSUE TITLE
Babel-polyfill polyfills on window.location.search

### ISSUE THREAD

**Issue by anselmbradford** [babel/babel#7841]
Bug report

When I run a script through webpack that has `useBuiltIns: 'usage'` and `debug: true` set, I see the following polyfill added:

```bash
Added following polyfill:
  es6.regexp.search { "android":"62", "edge":"15", "ie":"8" }
``` 

### Input Code

I stripped the code down to the following and still saw the polyfill message:

```js
console.log( window.location.search );
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
…
    use: {
      loader: 'babel-loader?cacheDirectory=true',
      options: {
        presets: [ [ 'babel-preset-env', {
          configPath: __dirname,
          useBuiltIns: 'usage',
          debug: true
        } ] ]
      }
    }
…
```

### Expected Behavior

Expect `window.location.search` not to be polyfilled with `es6.regexp.search`.

### Current Behavior

` es6.regexp.search` polyfill appears to be added for `window.location.search`.

### Context

Came up while removing polyfill requirements from some scripts.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.3
| node             | v8.11.1
| npm              | 5.6.0
| Operating System | Sierra 10.12.6 (16G1212)

**Comment by zloirock** [comment]
I don't think that we should have any special exceptions for something like this.

**Comment by nicolo-ribaudo** [comment]
Babel can't statically know that `windows.location.search` is not a string, so it must include the polyfill.
Consider this (convoluted, but valid) code, run in a node environment:
```js
global.window = { location: "foo" };
window.location.search(/o/); // <-- The polyfill must be included!!!
```

**Comment by xtuc** [comment]
You can manually exclude the plugin if you don't need it.

**Comment by anselmbradford** [comment]
Is it possible to ignore particular lines of code from the plugin?

**Comment by hzoo** [comment]
yeah, you can use the `exclude` option for now
