### ISSUE TITLE
[plugin-transform-react-jsx-source] Missing documentation for stable release

### ISSUE THREAD

**Issue by Domiii** [babel/babel#7845]
The current documentation is only for Babel 7+ (which apparently is still in beta). Since I am using Babel 6.*, I had to take different steps:

1. `npm install --save-dev babel-plugin-transform-react-jsx-source@6.22.0` (or best matching version for your current babel installation - see [history version here](https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source?activeTab=versions))
1. Correspondingly, the `plugin` name in `.babelrc` must also be modified: `{ "plugins": ["babel-plugin-transform-react-jsx-source"] }`

## Disclaimer: This is an amazing plugin!
As explained [here](https://github.com/facebook/react/issues/6062#issuecomment-256641386), `plugin-transform-react-jsx-source` is an unbelievably important tool in everyone's fight against React render bugs - thank you guys so much for building it!

**Comment by billyjanitsch** [comment]
Documentation for the 6.x plugins is available on the [6.x branch](https://github.com/babel/babel/blob/6.x/packages/babel-plugin-transform-react-jsx-source/README.md).
