### ISSUE TITLE
[plugin-transform-react-jsx-source] Minor feature request: display full file paths instead of file names

### ISSUE THREAD

**Issue by Domiii** [babel/babel#7846]
The plugin only displays file names, no full file paths, and they are not clickable links either. That is a bit of a problem when I see an error in `index.js` in a project that has hundreds of `index.js`.

e.g.:

> debugUtil.js:13 Warning: Failed prop type: Invalid prop `active` of type `number` supplied to `Button`, expected `boolean`.
>     in Button (at index.js:108)
>     in InjectedComp (at dataBind.js:482)
>     in ErrorBoundary (at dataBind.js:481)
>     in WrapperComponent (at app.js:91)
>     in div (at app.js:90)
>     in InjectedComp (at dataBind.js:482)
>     in ErrorBoundary (at dataBind.js:481)
>     in WrapperComponent (at root.js:18)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (at root.js:17)
>     in DataSourceProvider (at root.js:16)
>     in Root (at main.js:77)
>     in AppContainer (at main.js:76)

Otherwise, an amazing tool!

**Comment by billyjanitsch** [comment]
The Babel plugin does provide the full file path, but React does not currently use it. See [this React PR](https://github.com/facebook/react/pull/12059) which attempts to make the errors more useful.

**Comment by xtuc** [comment]
Thanks @billyjanitsch
