### ISSUE TITLE
plugin transform-es2015-modules-umd fails with Babel 6

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#7847]
_From @cristianbogdan on April 23, 2018 11:27_

I think this is a bug.

The code indicated here:
https://github.com/babel/babel-standalone/pull/92

Fails with Babel 6:
```
<html>
<head>
  <title>Babel Test</title>
</head>
<body>
  <script type="application/javascript" src="https://unpkg.com/babel-standalone@6.26.0/babel.js"></script>
  <script  data-plugins="transform-es2015-modules-umd" data-module="cube" type="text/babel">
    export default function cube(x) {
      return x * x * x;
    }
  </script>
  <script data-plugins="transform-es2015-modules-umd" type="text/babel">
    import cube from 'cube'
    console.log(cube(3))
  </script>  
</body>
</html>
```

This seems related to Babel 6 treating exports as per the ES6 spec

> Inline Babel script (2):3 Uncaught TypeError: (0 , _cube2.default) is not a function
>     at <anonymous>:24:36
>     at <anonymous>:10:9
>     at <anonymous>:13:3
>     at run (babel.js:61531)
>     at check (babel.js:61597)
>     at loadScripts (babel.js:61638)
>     at runScripts (babel.js:61668)
>     at transformScriptTags (babel.js:336)
>     at babel.js:327
> (anonymous) @ Inline Babel script (2):3
> (anonymous) @ VM6913:10
> (anonymous) @ VM6913:13
> run @ babel.js:61531
> check @ babel.js:61597
> loadScripts @ babel.js:61638
> runScripts @ babel.js:61668
> transformScriptTags @ babel.js:336
> (anonymous) @ babel.js:327

_Copied from original issue: babel/babel-standalone#100_

**Comment by nicolo-ribaudo** [comment]
Babel 6 isn't supported anymore.
