### ISSUE TITLE
Support only turning amd transform off, when imports/exports are used

### ISSUE THREAD

**Issue by cromefire** [babel/babel#7859]
**Is your feature request related to a problem? Please describe.**
I use es2015 to amd, but have some files that should compiled, but without putting a define() wrapper around it. You can see that they don't need a wrapper, because they don't use export or import keywords (for example my service worker, with define it's broken).

**Basic Example**
_serviceworker.js_
```javascript
self.addEventListener("fetch", function (event) {
    [...]
}
```

transforms to 
```javascript
define([], function() {
    self.addEventListener("fetch", function (event) {
        [...]
    }
})
```

If this is loaded as service worker it would error and not execute and is essentially useless.

**Describe the solution you'd like**
If an option is enabled, let's say there is an option like:
`all` which is `true` by default,
 but if false only transform, if anything is imported or exported.

**Describe alternatives you've considered**
Don't let it transpile with babel and hope everything works

**Teachability, Documentation, Adoption, Migration Strategy**
See _solution you'd like_ above

**Additional context**
Nothing to add

**Comment by loganfsmyth** [comment]
With Babel 7, we only compile to UMD if the file is an ES6 module. While Babel's default behavior is to assume _everything_ is a module, you can also use `sourceType: "unambiguous"` in the instruct Babel to guess the type based on the presence of `import`/`export` statements, which is applicable to this case.
