### ISSUE TITLE
Enable playground/experimental features by default

### ISSUE THREAD

**Issue by sebmck** [babel/babel#786]
Since Babel is no longer just an ES6 transpiler it makes sense to consider enabling the playground by default. This wouldn't be a breaking change and could be done in a minor as it doesn't break any existing syntax.

**Comment by sebmck** [comment]
There are things such as `es7.objectSpread` etc that I'd really like to enable by default. It doesn't make much sense to have them behind a flag, as while their grammar and behaviour may change, a major version bump will suffice.

**Comment by Dashed** [comment]
What's the protocol for introducing/removing features? semver?

**Comment by sebmck** [comment]
Yep, I follow semver very strictly. The only times I accidentally deviate is when I forget that I've added a new feature and release it in a patch instead of a minor.

**Comment by douglasduteil** [comment]
:+1:
