### ISSUE TITLE
Unable to Install  "babel-plugin-transform-exponentiation-operator"

### ISSUE THREAD

**Issue by BharathSH** [babel/babel#7864]
trying to install  babel-plugin-transform-exponentiation-operator ,getting below error , and the error is while creating the react app aswell .
i am a newbee and could find solution by googling aswell.

\React>npm i babel-plugin-transform-exponentiation-operator
npm ERR! code E500
npm ERR! 500 Server Error: babel-plugin-transform-exponentiation-operator@latest 

any help is greatly appreciated.
thanks,
Bharath

**Comment by hzoo** [comment]
I would just try again? It's a valid package name and works on unpkg https://unpkg.com/babel-plugin-transform-exponentiation-operator@6.24.1/  and https://www.npmjs.com/package/babel-plugin-transform-exponentiation-operator. You might have a proxy or npm issue?
