### ISSUE TITLE
export * from not working as expected - 7.0.0-beta.44

### ISSUE THREAD

**Issue by dunika** [babel/babel#7865]
**Current Behavior**
I am trying to upgrade from 6 - 7 and have ironed out most issues but I can't seem to get around this one.

I have a file similar to this

```
// constants/greetings.js
export const hello = 'hello'

export const goodbye = 'goodbye'
```

Then I have my root index file which imports/exports these like so 

```
// constants/index.js
export const random = 123

export * from './greetings'
```

Now when I try to import from this file elsewhere

```
import { random, hello, goodbye } from '../../constants

```

`random` will give me `123` but both `hello` and `goodbye` will give me `undefined`. 

My relevant `dependencies` are as follows

```
 "dependencies": {
    "next": "^6.0.0",
  }
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.44",
    "@babel/core": "7.0.0-beta.44",
    "@babel/node": "7.0.0-beta.44",
    "@babel/plugin-proposal-export-default-from": "7.0.0-beta.44",
    "@babel/plugin-proposal-export-namespace-from": "7.0.0-beta.44",
    "@babel/plugin-syntax-export-default-from": "7.0.0-beta.44",
    "@babel/plugin-syntax-export-namespace-from": "7.0.0-beta.44",
    "@babel/plugin-transform-modules-commonjs": "^7.0.0-beta.46",
    "@babel/plugin-transform-runtime": "7.0.0-beta.44",
    "@babel/preset-env": "7.0.0-beta.44",
    "@babel/preset-stage-0": "7.0.0-beta.44",
    "babel-plugin-inline-import": "^2.0.6",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-styled-components": "^1.4.0",
    "babel-plugin-transform-imports": "^1.5.0",
  },
```

And hers my `.babelrc`

```
{
  "presets": [
    ["next/babel", {"preset-env": {
      "modules": "commonjs"
    }}],
    "@babel/preset-stage-0"
  ],
  "plugins": [
    "@babel/plugin-syntax-export-namespace-from",
    "@babel/plugin-syntax-export-default-from",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from",
    [ "styled-components", { "ssr": true } ], 
    [ 
      "module-resolver", { 
        "root": [ "./src" ]
      } 
    ],
    [
      "transform-imports",
      {
        "lodash": {
          "transform": "lodash/${member}",
          "preventFullImport": true
        },
        "lodash/fp": {
          "transform": "lodash/fp/${member}",
          "preventFullImport": true
        },
        "recompose": {
          "transform": "recompose/${member}",
          "preventFullImport": true
        }
      }
    ], [ "inline-import", {
        "extensions": [ ".css" ]
        }
      ]
  ]
}
```

Running on `node 8.4.0` and `npm 6.0.0`

**Comment by xtuc** [comment]
Could you please provide the generated code?

**Comment by loganfsmyth** [comment]
Usually my expectation, when things are unexpected `undefined` in imports, is that there is a dependency cycle somewhere. Would it be possible for you to post a reproducible repository?

**Comment by xtuc** [comment]
@loganfsmyth yes, but even if they are transpiled to cjs?

**Comment by loganfsmyth** [comment]
Maybe you were relying on the buggy behavior in https://github.com/babel/babel/issues/4356 accidentally?

**Comment by loganfsmyth** [comment]
It was buggy compared to the spec is all I mean. Files didn't actually import in the order they were referenced in some cases due to that bug, so it is possible that your code was relying on the incorrect loading order to avoid the dependency cycles. When you updated to 7.x, the order changed, so that could be what broke your code.

**Comment by dunika** [comment]
Sorry that was meant to be a joke but I guess it wasn't a good one

**Comment by loganfsmyth** [comment]
Ahhh, sorry I was in a rush when I responded, so totally missed that :P
