### ISSUE TITLE
babel  IE10 and below  Report：Map is not defined

### ISSUE THREAD

**Issue by TonyGGC** [babel/babel#7866]
**Current Behavior**
Using babel for es6 to es5， it report map undefined error

[**Development language**]
reactjs

[**Environment**](url)
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-react-transform": "^3.0.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",

**Comment by existentialism** [comment]
@TonyGGC thanks for the issue! Babel transpiles _syntax_, features like `Map` (and `Set`) requires a polyfill like `babel-polyfill` or `core-js` (ref: https://reactjs.org/docs/javascript-environment-requirements.html).

**Comment by TonyGGC** [comment]
@existentialism   I do like this, but it also show me the 'map' error
My Code:
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import store from "./store";
import "./app/home/style/index.css";
import './app/common/style/antd-mobild.css';
import routes from "./routes";
// import 'babel-polyfill';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/shim';
// import 'raf/polyfill';

ReactDOM.render(
  <Provider store={store}>{routes}</Provider>,
  document.getElementById("react")
);

**Comment by TonyGGC** [comment]
@zloirock  
I have already loaded the 'core-js' in my package.json

**Comment by zloirock** [comment]
@TonyGGC and?... `core-js` imports should be placed before any other.

**Comment by TonyGGC** [comment]
@zloirock 
I do it ,  but lt also show me the 'Using babel for es6 to es5， it report map undefined error' problem.
