### ISSUE TITLE
Manually provide data for core-js web.* features in babel-preset env

### ISSUE THREAD

**Issue by realityking** [babel/babel#7868]
## Feature Request

Babel itself should provide data for the 3 web polyfills in core-js to avoid loading unnecessary polyfills.

The 3 core-js modules in question are
* web.timers
* web.immidiate
* web.dom.iterable

I'm willing to implement this but I want to see first if this is undesired complexity.

**Is your feature request related to a problem? Please describe.**

`babel-preset-env` loads polyfill code that is not needed by the target platform. This negatively affects both bundle size and start up time. In the extreme case it's the difference between completely removing core-js from a bundle - or not.

Relates to #6639.
 
**Describe the solution you'd like**

Analogus to `build-modules-support.js`, `build-data.js` should have the information which environments need these polyfills. Collecting this information is straight forward for `web.timers` and `web.immidiate`, I'd start here. `web.dom.iterable` would be significantly more complex and could follow later.

**Describe alternatives you've considered**

Do nothing. It's a bit larger bundle, not the end of the world.

**Teachability, Documentation, Adoption, Migration Strategy**

This is the best part - it would benefit all projects using `babel-preset-env` with core-js or `babel-polyfill` without any effort on their part.

**Comment by zloirock** [comment]
I agree.

**Comment by zloirock** [comment]
Fixed in #7646.
