### ISSUE TITLE
Deprecate `6to5` npm module

### ISSUE THREAD

**Issue by jesstelford** [babel/babel#787]
With the name change (#780), you should [deprecate](https://docs.npmjs.com/cli/deprecate) the `6to5` npm module so those who install it from command line will be warned:

```bash
npm deprecate 6to5@">= 0.0.2" "6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die"
```

Note that only the package owner (@sebmck) can deprecate via npm.

**Comment by sebmck** [comment]
Done, thanks! I didn't do this at first because a lot of people got pissy when I deprecated 2.x and they got a warning message in their console. Benefits outweigh the extremely minimal cons though. Thanks again!

**Comment by jesstelford** [comment]
:+1: Keep up the excellent work!
