### ISSUE TITLE
having error when installing packages related with babel

### ISSUE THREAD

**Issue by zhatongning** [babel/babel#7870]
<img width="786" alt="screen shot 2018-05-05 at 2 57 03 pm" src="https://user-images.githubusercontent.com/20442118/39661870-c3f79b4c-508b-11e8-9806-eb392ca520ff.png">
<img width="693" alt="screen shot 2018-05-05 at 5 43 37 pm" src="https://user-images.githubusercontent.com/20442118/39661878-e33e2dfe-508b-11e8-9e4d-8e042a54b705.png">

content in .log file
<img width="781" alt="screen shot 2018-05-05 at 2 59 17 pm" src="https://user-images.githubusercontent.com/20442118/39661890-1a71a6ca-508c-11e8-8c2f-9c9e97e258ff.png">

platfom: 
Mac
node: v8.9.4
npm v6.0.0 / v5.8.0

I keep having the problem. But When I use the company computer, I work perfectly.

**Comment by loganfsmyth** [comment]
This seems more like an `npm` issue. I don't think there's anything we can do from our side. It sounds like something is probably corrupting your downloads somehow.

**Comment by zhatongning** [comment]
@loganfsmyth  Thank you for your help.I switched the registry from `taobaonpm` to `npm`. Then It worked. I wanted to report the bug for the taobaonpm, but I had no idea who or which organization should I look for.
