### ISSUE TITLE
Disallow plugin/preset shorthand names from babel@7 onwards

### ISSUE THREAD

**Issue by vjpr** [babel/babel#7872]
## Feature Request

Currently you can drop the `babel-preset` and `babel-plugin` prefixes. https://babeljs.io/docs/plugins/#pluginpreset-shorthand

```
"presets": ["@org/babel-preset-name"]

shorthand

"presets": ["@org/name"]
```

I propose for babel@7 we prevent this and only allow full names to be used.

### Why?

- It makes it more difficult when refactoring because you have to search for two names instead of one. 

  - This makes removing all instances of a plugin in a monorepo harder than it should be.

  - There is the potential for clashes such as `@babel/foo` and `@babel/babel-preset-foo`.

  - Say you develop your own plugin, and want to rename it, and its used in every package in a monorepo. This because very difficult when you cannot rely on every usage being named the same.

- It adds complexity to parsing babel plugin/preset names. Other tooling has to parse these names such as `ava`, and they need to implement this complicated logic.

- The way it works with package @scopes makes it awkward, because its no longer dropping a prefix, its dropping from the middle.

**Teachability, Documentation, Adoption, Migration Strategy**

babel@7 would be a great time to do this because everyone is already renaming everything to be `@babel` prefixed anyway.

**Comment by loganfsmyth** [comment]
In my mind, a lot of this seems like an issue for a linter. If you want your codebase to only use the fully-expanded version, that's 100% cool, but it's not clear to me what we gain by requiring that users type our the full name whenever something is referenced, especially now that the transform rules are 100% deterministic.

> There is the potential for clashes such as @babel/foo and @babel/babel-preset-foo.

Babel 7 will always load `@babel/babel-preset-foo`, so I'd almost call this a feature since it allows you to have a preset or plugin that is directly tied to the namespace of the package itself.

> It adds complexity to parsing babel plugin/preset names. Other tooling has to parse these names such as `ava`, and they need to implement this complicated logic.

We've exposed functions to resolve these for a while now to avoid this issue: https://github.com/babel/babel/blob/master/packages/babel-core/src/index.js#L7 Also in 7.x we've exposed several new APIs to aid in working with the config data without requiring implementations to do the parsing themselves. If tooling decides to continue doing it manually in 7.x, they are deciding to take on that burden.

**Comment by vjpr** [comment]
> but it's not clear to me what we gain by requiring that users type our the full name whenever something is referenced, especially now that the transform rules are 100% deterministic.

Say I have a tool to check if a package specified in my `package.json` is used in my codebase. Babel will always be a special case, and makes a simple checker quite complicated.

Imagine you use `@babel/runtime` with some presets and use shorthand.

```
require('@babel/runtime')({
  presets: ['foo'],
})
```

Now when I want to check whether `babel-preset-foo` is used in my codebase I have to search for `foo`. Because we allow for programmatic presets/plugins, a string search must be used. Searching for `foo` would potentially generate a lot of false positives as the name may be used as a variable etc. By using dashes in the name which is a solid npm convention, its easy to search for preset/plugin usages.

**I think its a foot-gun for a lot of people**, who initially like the brevity, but then only later realize that when they are refactoring it can be painful.

My own monorepo migration from babel 6 -> 7 would have greatly helped from never using the shorthand, and I will be enforcing non-shorthand in the code base from now on.

I think this was a long-shot anyway, seeing as the usage is already very widespread and people are starting to adopt babel@7 already in a big way.

**Comment by loganfsmyth** [comment]
> Say I have a tool to check if a package specified in my package.json is used in my codebase. Babel will always be a special case, and makes a simple checker quite complicated.

I think no matter what that will require linting guidelines. If we changed to requiring the prefix, users could just as easily turn around and do

    presets: [
      'env',
      'react',
      'flow'
    ].map(n => `@babel/preset-${n}`)

and you'd have the same issue, and it's now more painful for users.

Ignoring that usecase and the edge cases though, I do understand where you're coming from. I just think you'll encounter this issue with any package that implements a plugin system. ESLint for example also does not reference the prefix in their config.

**Comment by vjpr** [comment]
> users could just as easily turn around and do...

Good point.

I guess linting will be fine.

**Comment by hzoo** [comment]
> seeing as the usage is already very widespread and people are starting to adopt babel@7 already in a big way.

Yeah I think we don't get much but we can definetely try to lint either in a tool like https://github.com/sonarwhal/sonarwhal or if we introduce our own type of thing
