### ISSUE TITLE
Unexpected token: name (absPath) 

### ISSUE THREAD

**Issue by goonwzz** [babel/babel#7876]
## Bug Report

**Current Behavior**
`util/const/index.js`:
```js
var linkReplaceFunction = function () {
  let absPath = arguments[0];
  // ...
```
`util/.babelrc:`
```json
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-stage-0",
      {
        "decoratorsLegacy": true
      }
    ]
  ]
}
```

`App/webpack.config.js:`
```js
   [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|aliyun-sdk)/,
        use: [{
          loader: 'babel-loader',
        }],
      },
   ]
```
`App/.babelrc`:
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    ["@babel/preset-stage-0",{"decoratorsLegacy": true}]
  ],
  "plugins": [
    "transform-decorators-legacy",
    [
      "import",
      {
        "libraryName": "antd",
        "style": false
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.47
- Node/npm version: 7.3
- webpack 3.11.0

**Possible Solution**
babel doesn't work on util  but work well on app 

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by goonwzz** [comment]
ERROR in js/expert.8bc4eef556f32a1e86fa.js from UglifyJs
Unexpected token: name (absPath) [js/expert.8bc4eef556f32a1e86fa.js:8557,6]

![image](https://user-images.githubusercontent.com/18460670/39697020-1c3faa82-5222-11e8-90b2-ab5c9fd6a737.png)

**Comment by goonwzz** [comment]
under App File  

before build

![image](https://user-images.githubusercontent.com/18460670/39697139-81d82b9e-5222-11e8-9aa2-d2dba9eed090.png)


after build 
![image](https://user-images.githubusercontent.com/18460670/39697103-65dc9a42-5222-11e8-84a9-144036d4353e.png)

**Comment by goonwzz** [comment]
but under util File  as the same before or after build

**Comment by goonwzz** [comment]
I'm new  。Thank you for any suggestion

**Comment by nicolo-ribaudo** [comment]
How do you compile the files under `util/`? Do you use the webpack config in App for them?

**Comment by goonwzz** [comment]
yes webpack in App

**Comment by goonwzz** [comment]
my tiny demo https://github.com/goonwzz/needHelp.git

**Comment by xtuc** [comment]
Does uglifyjs not support let? Could you please try with a var?

**Comment by goonwzz** [comment]
@xtuc so I use babel to change let to var

**Comment by goonwzz** [comment]
@nicolo-ribaudo webpack used in App

**Comment by goonwzz** [comment]
@xtuc 
![image](https://user-images.githubusercontent.com/18460670/39741571-0d2a096a-52cd-11e8-9ee3-39d243131d60.png) babel transforms under App/*

**Comment by xtuc** [comment]
Ok that's right. It seems to be related to the new config resolution. 

Could you please try to use the new config: https://github.com/babel/babel/blob/master/babel.config.js in the root of your project (it's new to me too).

**Comment by goonwzz** [comment]
![image](https://user-images.githubusercontent.com/18460670/39743406-623ea0d6-52d3-11e8-89b6-3f1b17f348fc.png)

yes  babel 7 doesn't transpile the files in the util folder!   think you  anyway @xtuc  

I would change the file path  to solution my problem

**Comment by goonwzz** [comment]
change the file path   all file paths cannot be on the upper layer of .Babelrc
