### ISSUE TITLE
useBuiltIns no longer respecting "includes" option in webpack config

### ISSUE THREAD

**Issue by kaidjohnson** [babel/babel#7877]
## Bug Report

**Current Behavior**
As of v7.0.0-beta.45, transforms are not applying to additional files specified in the "includes" option in my webpack config. Perhaps there is a mismatch between modules, but when I downgrade to v7.0.0-beta.44, everything works as expected, so I'm relatively sure this is a regression in babel somewhere.

**Input Code**

```js
// webpack.config.js
...
module: {
  rules: [{
    test: /\.js$/,
    include: [
      '/path/to/src',
      '/path/to/node_modules/file_i_need_transformed'
    ],
    use: {
      loader: 'babel-loader'
    }
  }]
}

```

**Expected behavior/code**
When running the build, I see (via debug setting in babelrc):

```
Using targets:
{
  "android": "4.2",
 ... [removed for clarity]
}

Using modules transform: commonjs

Using plugins:
  transform-template-literals { "android":"4.2", "chrome":"29", "ie":"8" }
  ... [removed for clarity]

Using polyfills with `usage` option:

[/path/to/src/index.js] Added following polyfill:
  es6.date.now { "ie":"8" }

// webpack output
```

But I am expecting to see

```
Using targets:
{
  "android": "4.2",
 ... [removed for clarity]
}

Using modules transform: commonjs

Using plugins:
  transform-template-literals { "android":"4.2", "chrome":"29", "ie":"8" }
  ... [removed for clarity]

Using polyfills with `usage` option:

[/path/to/src/index.js] Added following polyfill:
  es6.date.now { "ie":"8" }

[/path/to/node_modules/file_i_need_transformed] Added following polyfill:
  es6.array.is-array { "ie":"8" }

// webpack output
```

The result is a broken package in legacy browsers, since the `Array.isArray` entries were not transformed in my third-party dependency.

Thanks in advance!

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
	"presets": [
		["@babel/preset-env", {
			"loose": true,
			"useBuiltIns": "usage",
			"debug": true
		}]
	],
	"plugins": [
		"@babel/transform-runtime"
	]
}
```

**Environment**
- Webpack version: 4.6.0
- Babel version(s): v7.0.0-beta.45, v7.0.0-beta.46
- Node/npm version: Node 8/npm 5
- OS: Ubuntu 16.04
- Monorepo: yes
- How you are using Babel: babel-loader (webpack)

**Comment by eubenesa** [comment]
@kaidjohnson Hello! Could you please try changing `.babelrc` to `babel.config.js`:

```javascript
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        loose: true,
        useBuiltIns: 'usage',
        debug: true
      }
    ]
  ],
  plugins: ['@babel/transform-runtime']
};
```

**Comment by kaidjohnson** [comment]
@eubenesa Thanks! That did the trick. Sorry for the delay in getting back to you. Switching to `babel.config.js` with the latest (now v7.0.0-beta.52) seemed to do the trick.
