### ISSUE TITLE
@babel/plugin-proposal-object-rest-spread not being detected at beta.46

### ISSUE THREAD

**Issue by karlas** [babel/babel#7879]
### Babel/Babylon Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    ["@babel/env", {
      "targets": { "node": "6.11.5" }
    }]
  ],
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}
```
CLI Command

`babel 'functions/src' --out-dir 'functions/bundle' --copy-files --ignore 'functions/src/node_modules'
`

### Expected Behavior
Files are correctly built, as it did with beta.44

### Current Behavior
With beta.46, following error arises:
```
Error: SyntaxError: functions/src/common/getLocations.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (77:19):

  75 |         if (key === 'viewport'){
  76 |           const { northeast, southwest } = geometry.viewport;
> 77 |           return {...prev, bounds : {
     |                   ^
  78 |             ne : {
  79 |               lat : northeast.lat,
  80 |               lng : northeast.lng

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
    at /Users/karlas/project/node_modules/@babel/cli/lib/babel/dir.js:185:22
    at /Users/karlas/project/node_modules/@babel/cli/lib/babel/dir.js:148:23
    at /Users/karlas/project/node_modules/@babel/cli/lib/babel/dir.js:120:23
    at /Users/karlas/project/node_modules/@babel/cli/lib/babel/dir.js:82:23
    at /Users/karlas/project/node_modules/@babel/cli/lib/babel/util.js:126:16
    at runAsync (/Users/karlas/project/node_modules/@babel/core/lib/transformation/index.js:37:12)
    at /Users/karlas/project/node_modules/@babel/core/lib/transform-file.js:56:36
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Possible Solution
Can't help...

### Context
Just transpiling about 20 files to be used on Firebase Functions

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.46
| node             |  8.11.1
| npm              |  5.6.0
| yarn              | 1.6.0
| Operating System | macOS High Sierra

**Comment by nicolo-ribaudo** [comment]
Can you try to rename `babel.config.js` and `module.export` the configuration? We changed how config loading works and it is causing a bunch of problems.

**Comment by loganfsmyth** [comment]
More specifically, where is your `package.json`? If the `.babelrc` is outside the directory containing the `package.json`, it is now ignored.

**Comment by karlas** [comment]
Yes, it's outside the directory where `package.json` is. Will this be a definitive change?

**Comment by loganfsmyth** [comment]
@karlas Yeah, the assumption now is that `.babelrc` files are scopes to a package. For broader configuration of many packages in a single repo, we now expect a `babel.config.js` file that exports the config to be in the project root working directory. Sounds like that is probably what you'd want.

**Comment by karlas** [comment]
Ok! Will try. Thanks!

**Comment by karlas** [comment]
Mmm i can´t get it work. What i made:

1) Rename `functions/src/.babelrc`to `functions/src/babel.config.js`
2) Add the `module.exports` to this file, resulting: 
```js
module.exports = {
  "presets": [
    ["@babel/env", {
      "targets": { "node": "6.11.5" }
    }]
  ],
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}

```

I'm doing something wrong?

**Comment by Draccoz** [comment]
Just for clarification: are we no longer able to use `.babelrc` file? I have the exact same issue as above, here are my `.babelrc` and `@babel/*` versions:
```
{
  "ignore": [
    "node_nodules/**/*"
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "@babel/external-helpers",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```
```
{
  "scripts": {
    "rollup": "rollup -c rollup.config.js"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.44",
    "@babel/core": "7.0.0-beta.44",
    "@babel/plugin-external-helpers": "7.0.0-beta.44",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.44",
    "@babel/plugin-syntax-dynamic-import": "7.0.0-beta.44",
    "@babel/preset-env": "7.0.0-beta.44",
    ...
    "rollup": "^0.58.2",
    "rollup-plugin-babel": "^4.0.0-beta.4",
    "rollup-plugin-node-resolve": "^3.3.0"
  }
}
```

**Comment by karlas** [comment]
Ok I finally could fix it, by adding `--config-file './functions/src/babel.config.js'` to the npm script, resulting: 

`babel 'functions/src' --config-file './functions/src/babel.config.js' --out-dir 'functions/bundle' --copy-files --ignore 'functions/src/node_modules'`

Note i had to add the `./`before the route, without it it didn't work

**Comment by ajhaupt7** [comment]
@karlas I think @loganfsmyth was saying by default babel looks for a `babel.config.js` in the project root directory, so rather than putting it at `./functions/src/babel.config.js`, you would put it at `./babel.config.js`. I'm setting up a project for firebase cloud functions (as it looks like you are ;-)) and that works without having to specify the config file

**Comment by rifler** [comment]
`.babelrc.js` in prj root worked until beta.44, but doesn't in 45 and above

![](http://geexfiles.com/wp-content/uploads/2015/06/ewan-gif.gif)

**Comment by felippepuhle** [comment]
thanks @nicolo-ribaudo

**Comment by geminiyellow** [comment]
oh... why `babel.config.js` , looks so bad.

**Comment by JamesTheHacker** [comment]
2 hours wasted pulling my hair out with this one. This should probably be in big bold letters at the head of the repo 🤣 It's going to trip a lot of people up.

**Comment by Sin360** [comment]
Same for me, it was a lot of pain for me to upgrade babel version and make everything work.
After a lot of searches, I renamed .babelrc to babel.config.js et voila !

```json
{
  "devDependencies": {
    "@babel/cli": "^7.1.0",
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-transform-async-to-generator": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "babel-loader": "^8.0.2"
  }
}
```
