### ISSUE TITLE
Rewrite whitespace handling in code generator

### ISSUE THREAD

**Issue by sebmck** [babel/babel#788]

**Comment by sebmck** [comment]
Looks like it's the price you have to pay for pretty output.

**Comment by sebmck** [comment]
This sucker needs to be rewritten.

**Comment by marcominetti** [comment]
Hi, I just post here before opening a dedicated issue.

Assuming the sourcemap generation works correctly, I'm not able to add breakpoints in node-inspector cause most of the code is not "new-line" formatted when the compact mode is disabled.

I had similar problems with my previous transpiler ;)... and the solution to preserve debug-ability in instrumented/generated code was to keep lines structure whenever possible (twisted code works too with sourcemap protocol).

In my old transpiler, I implemented an "execution" block detection and decorator just to have debug-able code (statement/etc) as a separate line. Do you have any other idea or can I add the fix to my backlog for second week of March (or weekend relax time)?

Do you suggest a starting point? I've browsed the code and found that the CodeGenerator class were (3.x) not aware of previous/next AST node to be stringified (this causing other bugs I'd investigate later on the new 4.x branch).

**Comment by sebmck** [comment]
@marcominetti 

> Assuming the sourcemap generation works correctly, I'm not able to add breakpoints in node-inspector cause most of the code is not "new-line" formatted when the compact mode is disabled.

Are you saying that you're only having issues when you've enabled the `compact` option?

> I had similar problems with my previous transpiler ;)...

Ok.

> I've browsed the code and found that the CodeGenerator class were (3.x) not aware of previous/next AST node to be stringified (this causing other bugs I'd investigate later on the new 4.x branch).

I'm not sure what you mean by this, can you elaborate?

**Comment by marcominetti** [comment]
I'll send u more details and examples tomorrow when at office.

**Comment by sebmck** [comment]
Great.

This issue can also be closed since I've rewritten large parts of the code generator and fixed the issue that I opened this one with in mind.
