### ISSUE TITLE
plugin-transform-es2015-function-name and babel-plugin-transform-es2015-arrow-functions conflict

### ISSUE THREAD

**Issue by thecontstruct** [babel/babel#7894]
## Bug Report

**Current Behavior**
According to the docs here https://babeljs.io/docs/plugins/transform-es2015-arrow-functions, 
assigned arrow functions should produce anonymous function expressions. When only this transform is present, it works as expected. Add in `plugin-transform-es2015-function-name` and it breaks the expected results.

**Input Code**
[REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=usage&code_lz=MYewdgzgLgBAhjAvDAFASiQPhgbwL4BQRQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=&prettier=false&targets=Node-8.9&version=6.26.0&envVersion=1.6.2)

(NOTE - Turn on the 2 plugin transforms since the url hash doesn't capture that info)

```js
const foo = () => {}
```

**Expected behavior/code**

```js
var foo = function () {}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
     "plugin-transform-es2015-function-name",
     "babel-plugin-transform-es2015-arrow-functions"
    ]
}
```

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: Node 8.9.4/npm 5.8.0
- OS: OSX 10.13.4
- How you are using Babel: grunt

**Possible Solution**
From my investigations I've found that `plugin-transform-es2015-function-name` is renaming the anonymous function to match the assigned variables id in the following change 248f00fe826e443825653bb906049eaeebd50c14. From the looks of things this was done to help with navigating the call stack during debugging. 

One would think that the order of the defined plugins would be the order that their transforms are executed, however, I suspect there's a loop hole because `plugin-transform-es2015-function-name` does it's transform on `exit` while `babel-plugin-transform-es2015-arrow-functions` does its on `enter`.

Basically, even though the arrow transform is listed second, it gets executed first when that arrow function expression is visited, after which the function name transform renames the now assigned anon function when the visitor exits the node.

Changing `plugin-transform-es2015-function-name` to execute on `enter` breaks other functionality and same if you changed `babel-plugin-transform-es2015-arrow-functions` to be on `exit` so I'm definitely not versed enough to figure out a better solution. Hope my pre-investigation has helped though.

**Additional context/Screenshots**
As nice of a feature it might be to rename anon functions for stack trace purposes, I fear might be going against the spec. The rename changes the meaning of the function from a FunctionExpression to a FunctionDeclaration which, for one thing, changes it's hoisting behaviour (FunctionExpressions aren't hoisted). 

How did we find this easter egg you may wonder?

The unfortunate answer is IE11 in IE7/8 mode 😭. 
You can try this to see what I mean:

```js
function foo(test) { 
  if (test == null) {   
    test = function test(){ 
      alert('fallback');
    } 
  } 
  test(); 
}

foo(function() { alert('you should see this') });
```

I realize babel isn't in the business of supporting shitty IE bugs, but I think this warrants at least some consideration since it seems to me to conflict with the expected spec behaviour already mentioned.

**Comment by loganfsmyth** [comment]
So that I understand the sample code you've provided, are you saying that the `test == null` check returns `true` because the function expression is given a name?

I'm not sure there's a way for us to address this, other than you disabling the `function-name` transform. The behavior you're describing is actually a feature, because arrow functions in ES6 do have names, just like function expressions, and they follow the same rules for adopting names from the surrounding context.

**Comment by thecontstruct** [comment]
No, as far as I can tell, the 
```js
  if (test == null) {   
    test = function test(){ 
      alert('fallback');
    } 
  } 
```
`test function` part gets hoisted to the top of the `foo function` (outside of the if stmt) and overrides the incoming `test` parameter. The if stmt gets skipped since `test` is defined, it's just pointing at the function declared in the if instead of the incoming parameter.

After some more research and I suspect that `IE11 in IE7 mode` is exhibiting the gotcha explained here [function-declarations-vs-function-expressions](https://javascriptweblog.wordpress.com/2010/07/06/function-declarations-vs-function-expressions/) in the `What else should I watch out for?` section.

I still have my suspicions that automatically naming a function could have unforeseen hoisting implications in compiled code but I don't have time to go further down this rabbit hole. From the sounds of it, modern JS engines deal with this case intelligently enough to avoid it.

I guess ultimately you're probably right that the only way around it is to disable the `function-name` transform when supporting shitty IE browser configurations. 😢

**Comment by loganfsmyth** [comment]
Doesn't seem like there is more to do unfortunately. Babel doesn't do well on < IE8 in lots of weird edge-casey ways.
