### ISSUE TITLE
Rename "Babylon" to "@babel/parser"

### ISSUE THREAD

**Issue by hzoo** [babel/babel#7901]
## Feature Request

**Is your feature request related to a problem? Please describe.**

It's cool to have fun names, but in the end new people don't know what they do, and if even if you are new you get confused if you aren't in the weeds doing all this. I suggested we do this a while ago and just didn't get around to doing it yet.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/588473/39872090-d0b59c10-5434-11e8-838b-f947c5e70f56.png)

I made a poll and it's 2/3 for yes: https://twitter.com/left_pad/status/959918310451277831

> I didn't know babylon is the parser until now (sorry never check it before) 😅
> The name "parser" tells us what it does. IMO it will be helpful for novice

The name says what it does so it should be better in the long run.

**Describe alternatives you've considered**

Docs, talks, etc. Still not enough. Same problem as `babili` -> `babel-minify` which I changed earlier.

**Teachability, Documentation, Adoption, Migration Strategy**

This is just annoying because all of our docs and other people's docs/articles are going to change.
- We should probably mention the name change in the readme and other places, not just switch it.
- And also PRs are going to have merge conflicts as well. I'm not sure if we want to just make a new folder and have both to land some PRs or just simply rename it? Maybe I'm thinking too much about it.
- This could be help-wanted but might be easier for someone more attuned to the codebase to do it (or maybe just review). I just know it will need to be rebased a lot unless we review it asap, depends.

**Comment by kamthamc** [comment]
@hzoo i started working on this but not sure how to test/commit it before publishing @babel/parser. I tried yarn link but looks like its not working.

**Comment by loganfsmyth** [comment]
@kamthamc `link` should be the way to go. If you join us on our Slack, might be easier to chat and figure things out.
