### ISSUE TITLE
retainLines does not work with shebang

### ISSUE THREAD

**Issue by zavr-1** [babel/babel#7905]
## Bug Report

**Current Behavior**
A line numbers retention does not work properly with a shebang in a JS file.

**Input Code**

The following code with `shebang`

```js
#!/usr/bin/env node
import { readdirSync, lstatSync, watchFile, unwatchFile } from 'fs'
import { join, resolve } from 'path'
```

will have incorrect lines

```js
#!/usr/bin/env node
"use strict";
var _fs = require("fs");
```

The code without `shebang` is fine

```js
import { readdirSync, lstatSync, watchFile, unwatchFile } from 'fs'
import { join, resolve } from 'path'
```

```js
"use strict";var _fs = require("fs");
var _path = require("path");
```

**Expected behavior/code**

Produces code should respect `shebang` comment.

```js
#!/usr/bin/env node
"use strict"; var _fs = require("fs");
var _path = require("path");
```

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "plugins": [
    "@babel/plugin-syntax-object-rest-spread",
    "@babel/plugin-transform-modules-commonjs"
  ],
  "retainLines": true
}
```

**Environment**
- Babel version(s): 7.0.0-beta.46
- Node/npm version: Node 8/npm 5
- OS: OSX 10.13.1
- Monorepo no
- How you are using Babel: cli, register

**Possible Solution**

**Additional context/Screenshots**
I need to debug the code using VS Code however if lines are not retained it's impossible.

**Comment by loganfsmyth** [comment]
I've posted #7928, which will fix this case.

That said, generally we recommend debugging with sourceMaps, or accepting that line numbers will not match up. `retainLines` is only a best effort, and there are other cases where it does not, and cannot, accurately retain the line numbers.
