### ISSUE TITLE
"npm audit" reports vulnerabilities of dependent packages

### ISSUE THREAD

**Issue by lll000111** [babel/babel#7907]
## Bug Report

**Current Behavior**

My package.json contains these dev. dependencies:

```
    "babel-core": "*",
    "babel-plugin-transform-flow-strip-types": "*",
    "babel-preset-es2017": "*",
```

Running npm 6.0.1 `npm audit` results in several reported vulnerabilities:

[report.txt](https://github.com/babel/babel/files/1995549/report.txt)

**Environment**
- Babel version(s): 6.23.3
- Node/npm version: 10.1.0
- OS: Windows 10
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
No vulnerabilities with Babel 7:
```
Documenti/dev/babel-npm-audit is 📦 v1.0.0 via ⬢ v10.0.0 
➜ npm i --save-dev @babel/core @babel/preset-env @babel/plugin-transform-flow-strip-types
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-npm-audit@1.0.0 No description
npm WARN babel-npm-audit@1.0.0 No repository field.

+ @babel/core@7.0.0-beta.46
+ @babel/plugin-transform-flow-strip-types@7.0.0-beta.46
+ @babel/preset-env@7.0.0-beta.46
added 142 packages from 95 contributors in 19.035s
[+] no known vulnerabilities found [1458 packages audited]

```

**Comment by lll000111** [comment]
I use "*" in package.json and get version 6.23.3. Version 7 isn't out yet?

**Comment by lll000111** [comment]
So... what now? We wait for v7?

**Comment by loganfsmyth** [comment]
If someone wants to submit a PR to update `6.x` I'm fine doing another release of 6.x for this.

**Comment by zhuangya** [comment]
`npm audit` requires `package-lock.json`

that would be a big problem for using npm audit :/
