### ISSUE TITLE
babel-plugin-transform-async-generator-functions doesn't unpack promises recursively

### ISSUE THREAD

**Issue by sithmel** [babel/babel#7912]
## Bug Report

**Current Behavior**
```js
async function * execute (func, ...args) {
  while (true) {
    yield func(...args)
  }
}

async function () {
    const iter = execute(() => Promise.resolve(1))
    assert.deepEqual(await iter.next(), { value: 1, done: false })
}
```
I would expect the assertion to be true. I suspect that when yielding a promise in an async function (equivalent of a promise, waiting another promise), only the first promise gets yielded.
Everything works without transpilation on node 10.

**Input Code**
- REPL or Repo link if applicable:
https://github.com/sithmel/iter-tools/blob/master/tests/execute.test.js#L24
Just remove the "skip" from the mocha test and run the tests.
Here's the commit in case the master diverge: https://github.com/sithmel/iter-tools/blob/bbd4c60ad5c916e110839f5143a4a20d65e5d2a7/tests/execute.test.js#L24

**Expected behavior/code**
I expect the code runs like the node 10 native implementation.

**Babel Configuration (.babelrc, package.json, cli command)**
Everything contained in the repository

**Environment**
- Babel version(s):
```
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-async-generator-functions": "^6.24.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",

```
- Node/npm version: node 10 npm 5.6
- OS: ubuntu 18.04
- Monorepo no
- How you are using Babel: `cli`

**Possible Solution**
:man_shrugging: 

**Additional context/Screenshots**
//

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/6452, it is included in Babel 7.
