### ISSUE TITLE
`gulp-babel` does not install `babel-core` causing it to throw errors

### ISSUE THREAD

**Issue by dextermb** [babel/babel#7915]
## Bug Report

**Current Behavior**
After following the _Using Babel_ guide on the website for gulp, and only installing `gulp-babel`, I then ran my gulp file which gave the error `Cannot find module 'babel-core'`. 

**Input Code**

```js
const gulp  = require('gulp');
const babel = require('gulp-babel');

gulp.task('default', () => {
	return gulp.src('src/Collection/collection.js')
			   .pipe(babel())
			   .pipe(gulp.dest('dist'));
});
```

**Expected behavior/code**
If `gulp-babel` depends on `babel-core` then it should install it as a dependency?

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["env"]
}
```

**Environment**
- Node/npm version: Node 6.11.3/NPM 6.0.1

**Additional context/Screenshots**
It seems that it is down as a dev dependency but did not install when following the guide.

**Comment by nicolo-ribaudo** [comment]
Babel Core is a peer dependency: this allows you to choose your preferred version, but you must install it. Doesn't `npm i gulp-babel` warn about `babel-core` not being installed?

**Comment by dextermb** [comment]
@nicolo-ribaudo Ah yes.That's true, it does give off a warning to install manually. Is it possible for it to install a default version, and then suggest to install a preferred version?
