### ISSUE TITLE
@babel/core `cwd` option is not documented

### ISSUE THREAD

**Issue by novemberborn** [babel/babel#7918]
Looking at https://github.com/babel/babel/blob/cec93c01ce406b144181f683fb282c32e52b3bc5/packages/babel-core/README.md#options the `cwd` option is not documented.

Even if this option is added the documentation for `root` should clarify that it is *only* used for resolving config, not relative `filename` paths. The default value could be changed to `(cwd)` rather than `"."`.

I wonder if it should be renamed to `configRoot`, even.

**Comment by BeniCheni** [comment]
Hello, recently did a "_good first issue_" labelled issue and had a lot of fun. So after checking "_good first issue_" issue again, I'll give this one a spin.

Just did `npm i --save-dev babel-cli` to learn about the `cwd` option in some tests first. Hopefully, I could understand the usage, and try to leverage of the previous comments here as hit to "_land_" on a potential PR. Will shadow y'all in Slack `#discussion` channel if any question. Thanks.

**Comment by rakelblujeans** [comment]
https://github.com/babel/website/pull/1701

**Comment by rakelblujeans** [comment]
https://github.com/babel/website/pull/1704

**Comment by adoi** [comment]
Hey @loganfsmyth is this still open? I would like to work on this

**Comment by loganfsmyth** [comment]
@rakelblujeans Agreed!
