### ISSUE TITLE
@babel/core's loadPartialConfig() and loadOptions() do not set configFile to false

### ISSUE THREAD

**Issue by novemberborn** [babel/babel#7922]
## Bug Report

From <https://github.com/babel/babel/blob/cec93c01ce406b144181f683fb282c32e52b3bc5/packages/babel-core/README.md#babelloadoptionsoptions-object>:

> It can be safely passed back to Babel. Fields like babelrc have been set to false so that later calls to Babel will not make a second attempt to load config files.

It does not seem like `configFile` is set to `false`.

**Comment by loganfsmyth** [comment]
This one I've got you covered on! https://github.com/babel/babel/pull/7911/files#diff-cb314fadefa9c421a4f746b01e4e716aR52
