### ISSUE TITLE
@babel/core's loadOptions() drop presets that have options

### ISSUE THREAD

**Issue by novemberborn** [babel/babel#7923]
## Bug Report

With `v7.0.0-beta.46`, `loadOptions()` does not explode (is that the term?) presets that have options. They're dropped instead.

I'm wrapping up my coding for the weekend so I do not yet have a reproduction handy, sorry.

**Comment by loganfsmyth** [comment]
`explode` is 100% my favorite technical term :) 

`loadOptions` fully flattens the presets into an array of plugins, unless the config is using `passPerPreset`. Is that potentially the misunderstanding?

**Comment by novemberborn** [comment]
It's https://github.com/avajs/babel-preset-stage-4/blob/master/index.js which is a plain `return {plugins}`.

This is part of https://github.com/avajs/ava/pull/1798. I'm running out of time to look at this today, sorry.

**Comment by novemberborn** [comment]
Aha! The preset is being dropped because it doesn't return any plugins given the `options` I was testing with.

Which makes this a variant of #7920.
