### ISSUE TITLE
Flow "double nullable" type can't be parsed

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#7924]
## Bug Report

**Current Behavior**

It throws a syntax error.

**Input Code**

```js
type A = ??T;
```

https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=C4TwDgpgBAglC8UD8SAqBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=flow&prettier=false&targets=&version=7.0.0-beta.46&envVersion=

**Expected behavior/code**
It is the same as
```js
type A = ? ?T;
```

**Environment**
- Babel version(s): v7.0.0-beta.46
- How you are using Babel: repl

**Comment by j-f1** [comment]
Note that using the `syntax-flow` plugin (i.e. not stripping the types) with `type A = ? ?T;` outputs this:

```ts
type A = ??T;
```

which will fail to parse.

**Comment by HassanAli321** [comment]
i would like to work on it

**Comment by nicolo-ribaudo** [comment]
If you need help, join our Slack!
