### ISSUE TITLE
Babel compiled ES5 doesn't work in IE11

### ISSUE THREAD

**Issue by volokolamskspb** [babel/babel#7935]
## Babel compiled ES5 doesn't work in IE11

**Current Behavior**
I compiled my ES6 code with babel and Webpack and it doesn't work in Internet Explorer browser.

**Input Code**
http://iml.ru/new-widget

And I receive such Error in console:
```Syntax Error on in  /js/newPvz-compiled.js line 37```

**Expected behavior/code**

It should work in IE

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc
```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "ie >= 11"]
      },
        "useBuiltIns": true
    }],

  ]
}
```
package.json 
```js
{
  "scripts": {
    "minify": "node minify.js"
  },
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "less": "^3.0.1",
    "minifier": "0.8.1",
    "vue2-filters": "^0.3.0",
    "watch": "^1.0.2",
    "webpack": "^4.6.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-es2015-ie": "6.7.0"
  },
  "devDependencies": {
    "babel-preset-env": "^1.7.0"
  }
}
```
cli 
```bash
$ webpack
$ ./babel-cli/bin/babel.js --presets babel-preset-es2015-ie /js/newPvz-webpack.js  -o /js/newPvz-compiled.js
```

**Environment**
- Babel version(s): babel-1.4.0
- Node/npm version: v4.2.6
- OS: Windows 10
- Monorepo [e.g. yes/no/Lerna]
- cli

**Possible Solution**
I tried to add babel-preset-es2015 and configure IE as supported browsers in .babelrc

**Comment by loganfsmyth** [comment]
So what is on line 37 for you? You haven't shown us any code, so that would be the place to start. What specific syntax is not getting converted, and thus causing the issue? Also, is IE running in compatibility mode, or running as proper IE 11?

**Comment by zhuangya** [comment]
IE11 does not recognize `let`

**Comment by loganfsmyth** [comment]
What is your Webpack config?

**Comment by volokolamskspb** [comment]
@loganfsmyth 
here's screenshot
https://imgur.com/a/Ks5IP0O

The problem is probably in Webpack. I included script which is compiled by webpack and it throws an error on line 189 where ```eval ``` starts.
https://imgur.com/a/NTzYgl6

Here's my Webpack config:

```js 
const path = require('path');
module.exports = {
  entry: ['babel-polyfill', path.resolve(__dirname, './draft.iml.ru/static/main/js/newPvz.js')],
  mode: 'development',
  output: {
    path: __dirname+'/draft.iml.ru/static/main/js/',
    filename: 'newPvz-webpack.js'
  }
};```

**Comment by volokolamskspb** [comment]
I'm sorry, this problem is not related to Babel.
I found the solution. Had to add ```devtools``` to webpack.config to remove ```eval```
```js 
const path = require('path');
module.exports = {
  devtool: "source-map",
  entry: ['babel-polyfill', path.resolve(__dirname, './yourjs.js')],
  mode: 'production',
  output: {
    path: __dirname+'/draft.iml.ru/static/main/js/',
    filename: 'yout.js'
  }
};
```
You can close this issue.

**Comment by RinkAttendant6** [comment]
@zhuangya 

> IE11 does not recognize `let`

That's not what the docs say: https://docs.microsoft.com/en-us/scripting/javascript/reference/let-statement-javascript
