### ISSUE TITLE
Official docs for babel-preset-env is outdated

### ISSUE THREAD

**Issue by heejongahn** [babel/babel#7939]
## Bug Report

**Current Behavior**
Current doc for env preset, https://babeljs.io/docs/plugins/preset-env/, seems outdated.

**Input Code**
N/A

**Expected behavior/code**
It should reflect the content of the latest doc, which I believe is https://github.com/babel/babel/blob/master/packages/babel-preset-env/README.md. Please correct me or just close the issue if I'm wrong.

**Babel Configuration (.babelrc, package.json, cli command)**
N/A

**Environment**
N/A

**Possible Solution**
Update the doc?

**Additional context/Screenshots**
N/A

**Comment by existentialism** [comment]
@heejongahn thanks for the issue!

Currently, babeljs.io represents the v6 documentation, and as you pointed out... `master` represents the current v7 beta (you can check out the docs at new.babeljs.io). We're working on getting the docs merged into a single site with version switching!

**Comment by heejongahn** [comment]
Ah, that makes sense. Sorry for the confusion. Besides, v7 is reeeeeeally great. I really appreciate the babel team's effort. Thanks!

**Comment by existentialism** [comment]
@heejongahn no need to apologize, we totally understand it's confusing :(

(and also, thanks for the kind words!)
