### ISSUE TITLE
Babel-cli is invalid for directory deep folder compilation.

### ISSUE THREAD

**Issue by jweboy** [babel/babel#7942]
## Bug Report

**Current Behavior**
When I tried the files on the deep directory of babel-cli, I found that compilation failed.

This is my specific file directory, the file hierarchy is deep, and when I compile it, I find that it doesn't compile.

```js
// package dir

├── index.js
├── package.json
└── src
    ├── actions
    │   └── swagger.config.js
    ├── components
    │   ├── RoomCard
    │   │   └── index.js
    │   ├── RoomFilter
    │   │   └── index.js
    │   └── RoomInfo
    │       └── index.js
    ├── containers
    │   ├── BodySetRoomPromotion
    │   │   └── index.js
    │   ├── BodySingleRoomPromotion
    │   │   └── index.js
    │   ├── ModalRoom
    │   │   └── index.js
    │   └── RightRoom
    │       └── index.js
    └── index.js
```

This is my specific file directory, When my file directory is simpler, compilation is normal.

```js
// test dir
└── src
    └── index.js
```

**Input Code**

```js
npx babel package -d lib
npx babel test -d es
```

**Expected behavior/code**
In the directory that you want to compile, the directory hierarchy is deep, and all the js files in the directory execute the es5 syntax to compile and output.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/env",
    "@babel/preset-es2015",
    ["@babel/preset-stage-0", {
      "decoratorsLegacy": true
    }]
  ],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

**Environment**
- Babel version(s): ^7.0.0-beta.47
- Node/npm version: Node 8/npm 5
- OS: macOS v10.13.4
- Monorepo: No
- How you are using Babel: cli

**Comment by loganfsmyth** [comment]
I'm not sure I fully understand. What specifically are you seeing?

**Comment by jweboy** [comment]
@loganfsmyth Such as the above package directory, I perform the Babel compilation, expect the catalog all the js to compile and the output of a es5 grammar, but I output directory is still a source file, not compile

**Comment by loganfsmyth** [comment]
@jweboy Ah, you never mentioned you have multiple separate packages in the same repo. `.babelrc` files, as of recently, only apply to the package they are inside of. Your `package` folder is its own sub-package, so the `.babelrc` in your project root will not apply to it.

Given the small snippet you've given, the easiest fix would be to rename the `.babelrc` to `babel.config.js` and do `module.exports = {` with your config object.

**Comment by jweboy** [comment]
@loganfsmyth The original problem is that I ignore the correspondence between the file directory and the babel configuration file. I understand, thank you. I would like to ask again, according to the idea you provided, is not to create a babel.config.js file in the package and preset two directories, and then export through module.exports, and create a babel.config.js in the root directory Import the corresponding two Babel configurations.
