### ISSUE TITLE
Unicode, "new RegExp(rx_string, 'u')"

### ISSUE THREAD

**Issue by mikecardwell** [babel/babel#795]
Babel handily converts unicode regexes like this:
```javascript
var rx1 = /^.$/u;
```
To:
```javascript
var rx1 = /^(?:[\0-\t\x0B\f\x0E-\u2027\u202A-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])$/;
```
However, it does not modify these:
```javascript
var rx2 = new RegExp('^.$', 'u');
```
In my particular case, the regular expression is stored in a string, so I can't use the first method.

**Comment by mikecardwell** [comment]
Ah, I think I understand why this is happening. The first method will work because it calculates the regular expression at transpile time. The second method would need to calculate the regex at run time. Damn.

**Comment by sebmck** [comment]
Yep. I mean, we could handle your example of:

```javascript
var rx2 = new RegExp('^.$', 'u');
```

but then how would we handle:

```javascript
var flag = 'u';
var rx2 = new RegExp('^.$', flag);
```

or even:


```javascript
var rx2 = new RegExp(buildPattern(), 'u');
```

It's easier to just confine the unicode regex transpilation to literals.
