### ISSUE TITLE
resolvePlugin for babel-cli

### ISSUE THREAD

**Issue by Globegitter** [babel/babel#7952]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I am working on writing a js rule for bazel (https://github.com/bazelbuild/rules_nodejs) and it sets up an environment where babel is executed in one folder and `node_modules` is in a subdirectory, e.g. `external/name/node_modules` so babel can not find the plugins etc specified in the babel.rc

**Describe the solution you'd like**
I would be great to get a flag that is similar to the `resolvePlugin/resolvePreset` function, e.g. `babel --resolve-plugin @babel/plugin-transform-modules-amd=external/js_library_deps/node_modules --resolve-plugin @babel/...=external/js_library_deps/node_modules` and so on.

Or maybe it is even possible to have this in the `babel.rc`, that would imo make it even nicer. One way I could imagine is just reusing the plugins key like:

```
{
  "plugins": [
       {"@babel/plugin-transform-modules-amd": "external/js_library_deps/node_modules"}
    ],
}
```

And under the hood it could just use `resolvePlugin` if it finds an object within the array.

**Describe alternatives you've considered**
I can use the nodejs api like 

```
const babel = require("@babel/core");

const pluginLoc = babel.resolvePlugin('@babel/plugin-transform-modules-amd', 'external/js_library_deps/node_modules')
babel.transformFileSync("path/to/file/file.js", {
    plugins: [pluginLoc]
});
```

But that seems like it could quickly turn inefficient, especially if I want to transform more than one file in a go.

**Teachability, Documentation, Adoption, Migration Strategy**
The functionality would be exactly the same as the existing `resolvePlugin`/`resolvePreset` api just exposing it to the CLI.

**Comment by loganfsmyth** [comment]
Could you elaborate a bit more on exactly what your project structure is? I think allowing config files and programmatic paths to resolve relative to arbitrary directories would likely add a lot of confusion. We do expose a bit of control over it, but not a ton. Also, the objective of `resolvePlugin` is to allow resolution of user-specified plugins and presets, but if you're hardcoding them in your build tool, it seems like using `require.resolve` would be fairly straightforward.

I can try to give other suggestions, but more specifics would help.

**Comment by Globegitter** [comment]
The way bazel works is that one has a workspace root (usually equal to the git root) and bazel symlinks your whole workspace (and all third party dependencies and files bazel generates, like compiled files) into a sandboxed area where it then executes things. It is executing/invoking commands in that sandboxed workspace root and third party dependencies, i.e. node_modules are there put into an `external/name` subfolder. Where-as the name is dependent on user-definition. `require.resolve` does indeed work when I use babel in nodejs. Does that make some more sense? I am happy to give more details and background if required.

The way it works in rollup for example (and that is how bazel uses rollup currently), is that one can specify
`customResolveOptions: {moduleDirectory: 'node_modules_path'}` in the config, which is read by the rollup cli, which in turn is invoked by bazel.

**Comment by loganfsmyth** [comment]
I feel like an example repository, or a written-out example of the structure would make it easier to visualize for me.

Am I understanding that you're running Babel on the files _after_ they are copied into this sandbox then?

**Comment by Globegitter** [comment]
@loganfsmyth yeah will create an example repo, will probably make it easier :)

**Comment by excavador** [comment]
@loganfsmyth 

after copying to sandbox it has following structure:
```
external/NAME_OF_THE_DEPS_IN_THE_BAZEL_BUILD_FILE_SPECIFIED_BY_USER/node_modules
# the rest of source code
```

**Comment by Globegitter** [comment]
@loganfsmyth Sorry it took a while, but I managed to get an example repo together and also figured out what the issue is. Bazel provides a patched `require`: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_loader.js#L18 and babel further down the line tries to load the plugin using the `resolve` module which ignores this patch. It is actually quite straight forward to fix the issue, by just providing a `babel.rc.js` and `requiring` the plugin in there rather than leaving the resolving to babel. 

Here is the example repo to demonstrate: https://github.com/ecosia/rules_nodejs/tree/babel-example-repo
Steps to reproduce:
 - install bazel: https://docs.bazel.build/versions/master/install-ubuntu.html
 - clone repo
 - cd `examples/devserver`
 - `bazel build --verbose_failures //src:test`

And the way babel is invoked can be found here: https://github.com/ecosia/rules_nodejs/tree/babel-example-repo/internal/js_library/v2

The only I could see within babel is to use require rather than the resolve module. Other than that, this could now also be closed given that there is a workaround via the `babel.rc.js` file.

**Comment by loganfsmyth** [comment]
Alright, I'm not sure this is something we'd want to expose, so I think I'll recommend the workaround for others running into this.
