### ISSUE TITLE
Incorrect parse error thrown for unexpected Flow code

### ISSUE THREAD

**Issue by taion** [babel/babel#7954]
## Bug Report

**Current Behavior**
An incorrect parse error is thrown when unexpected Flow code is present.

For the below, I see:

```
SyntaxError: node_modules/some-package/test.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (3:8):

  1 | /* @flow */
  2 |
> 3 | export type Foo = number;
    |        ^
  4 |

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
```

**Input Code**
```js
/* @flow */

export type Foo = number;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

N/A (I think?)

**Environment**
- Babel version(s): `7.0.0-beta.46 (@babel/core 7.0.0-beta.46)`
- Node/npm version: v10.0.0
- OS: OSX 10.12.6
- Monorepo: N/A
- How you are using Babel: `cli`

**Comment by loganfsmyth** [comment]
Thanks! Yeah, instead of references to `exportDefaultFrom` and `@babel/plugin-proposal-export-default-from` this should really be an error about `flow` and the Flow plugin.

**Comment by dczombera** [comment]
I can work on that one.

**Comment by loganfsmyth** [comment]
@dczombera Go for it. Feel free to join our Slack if you have questions.

**Comment by dczombera** [comment]
FYI I haven't found time yet to work on it. I will do it in the next couple of days. 🙂

**Comment by AkshatSrivastava2** [comment]
Hello there, I want to work with the issue. I am a first-time contributor. 
Help me with how to do this task.

**Comment by dczombera** [comment]
@AkshatSrivastava2 It's all yours. I don't have time right now to work on it.

**Comment by HassanAli321** [comment]
Hi if still there is no one working on it i would like to work on it.

**Comment by dantesolis** [comment]
hey @HassanAli321  if you are not taking this and or if you want to do it together, let me know I would like to take it or help with it :)

**Comment by existentialism** [comment]
@dantesolis there's a PR for this already, thanks tho!
