### ISSUE TITLE
Does not recognize browserlist in package.json and output all pollyfills

### ISSUE THREAD

**Issue by pldg** [babel/babel#7964]
Reference to the original webpack loader ticket [babel/babel-loader#622](https://github.com/babel/babel-loader/issues/622)

**Comment by existentialism** [comment]
@pldg [support for this landed](https://github.com/babel/babel-preset-env/pull/161) in the old babel-preset-env 2.x-alphas, which later transitioned into the same version scheme as babel 7 betas when we merged it into the monorepo.

**Comment by pldg** [comment]
@existentialism I've installed `@babel/core` `@babel/preset-env` `@babel/polyfill` 7.0.0-beta.47 and changed my config accordingly but it trow an error in console: *Cannot read property 'target' of undefined*.

*package.json* `"browserlist": [ "last 2 Chrome versions" ]`


```javascript
// babel.config.js
presets: [
  ['@babel/preset-env', {
    modules: false,
    useBuiltIns: 'entry'
  }]
]
```

```javascript
// my only entry point
import '@babel/polyfill';
const p = new Promise( resolve => resolve() );
```

Maybe Webpack *babel-loader* does not support babel 7.0-beta yet?

**Comment by existentialism** [comment]
@pldg it does! hard to know more without seeing your setup... can you create a small repo that reproduces your problem?

**Comment by pldg** [comment]
@existentialism [test-babel-beta](https://github.com/pldg/test-babel-beta)

**Comment by existentialism** [comment]
@pldg sorry for the delay, finally took a look.

Replace `babel-loader@^7.1.4` with `babel-loader@8.0.0-beta.3`, and rename the `browserlist` key to `browserslist` and your repo builds fine.
