### ISSUE TITLE
Readme location in @babel/helper-plugin-utils

### ISSUE THREAD

**Issue by larsgw** [babel/babel#7971]
The README file in the [`@babel/helper-plugin-utils`](https://github.com/babel/babel/tree/master/packages/babel-helper-plugin-utils) package is not in the root directory of that package, but in the [`src` directory](https://github.com/babel/babel/tree/master/packages/babel-helper-plugin-utils/src). This doesn't seem to follow the pattern of other packages.

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR?

**Comment by larsgw** [comment]
Just did, thanks for the suggestion. I didn't know you could move files in the GitHub editing interface.
