### ISSUE TITLE
optional _classCallCheck?

### ISSUE THREAD

**Issue by vectorsize** [babel/babel#798]
Hello,

Would it be possible to have a flag for the command line to set your automatic `_classCallCheck` on or off as needed? (I can't seem to find it if it is already there)

It's fairly common among the node community to deliver "self-constructing" objects using some sort of code like the following:

`if (!(this instanceof Constructor)) return new Constructor(options);`

This way your objects can be used in an OOP way or a rather more functional approach – leaving that decision up to the user – for instance, when working with node streams and pipes the latter is often preferred to avoid passing a constructor into a pipe method:

```js
myStream
  .pipe(reverse())
  // vs
  .pipe(new reverse())
  //...
  .pipe(process.stdout)
```

**Comment by sebmck** [comment]
I don't want to encourage non-spec usage and disabling of behaviour, sorry.

**Comment by vectorsize** [comment]
oh…ok, I meant more as an option, not the default behaviour.

**Comment by sebmck** [comment]
Yeah but that's still an option that endorses this usage. If you want non-ES6 classes then you can just write non-ES6 classes.

**Comment by vectorsize** [comment]
I understand.
Is this something that would be possible to do via a transform? I've been reading through the docs and couldn't find information on how to write one.

**Comment by sebmck** [comment]
There's isn't a public transformer API yet, #607. Although even if there was you'd basically have to write your own entire class transformer.

**Comment by vectorsize** [comment]
Ok :)
I'm piping the stdout and commenting that line out at the moment.
Will check the transformers option when it's ready.

cheers!

**Comment by jamm** [comment]
Please implement it - currently it conflicts with ng-annotate. It's not your fault, nor ng-annotate, but in result I have to use non-minified files on production.

**Comment by fkling** [comment]
I think the solution is rather that if devs want to allow functions to be called as `Foo()` and `new Foo()`, they should not use a `class` declaration but stick with constructor + prototype.

**Comment by jamm** [comment]
@fkling I'm all for purism and perfectionism, but when 2 tools (ng-annotate and babel) fighting somewhere inside minified and concatenated code, I just want see it working. My source code will be with real ES6 classes and pure as crystal.

So  currently I have to put "replace" step into gulp pipe... It works, so no worries :)

**Comment by thejameskyle** [comment]
What exactly is wrong with ngAnnotate? This seems irrelevant.

**Comment by thejameskyle** [comment]
See: https://github.com/olov/ng-annotate/issues/64#issuecomment-61549469

ngAnnotate doesn't have support for ES classes. This isn't an issue with Babel.

This is the solution they proposed:
```js
class MainCtrl {
    constructor($http) {
        this._$http = $http;
    }
    get name() {
        return "World$%#";
    }
}

export ngInject(function($http) {
  return new MainCtrl($http);
});
```

**Comment by jamm** [comment]
@thejameskyle this solution is too verbose. If you don't mind to repeat list of dependencies (as you do), you can just 
```
MainCtrl.$inject = ['$http'];
```
ng-annotate support ES6 classes by `@ngInject`, it's requirement of AngularJS to wrap result into array.

**Comment by thejameskyle** [comment]
sounds like you have your solution then

**Comment by olov** [comment]
@jamm @thejameskyle there's no clash between ng-annotate and babeljs - quite the opposite. Use this style: `class MyCtrl { constructor($a, $b) { "ngInject"; ... } }` and things will work just fine with recent ng-annotate and recent babel. @jamm if you have any remaining issues then feel free to open an ng-annotate issue.

**Comment by jamm** [comment]
@olov it's not true. 
First of all, 'ngInject'; sometimes doesn't work (not always, what is annoying).  //ngInject works always.
Second: try to run compiled code in IE8. Issue will be exactly because of purism of BabelJS. As workaround, I use
```
.pipe(replace('throw new TypeError("Cannot call a class as a function");', ''))
```
in gulpjs file. 
Ugly, but works and we don't have anything better.

**Comment by olov** [comment]
@jamm "'ngInject'; sometimes doesn't work" - well that sounds weird. If you have any remaining issues then feel free to open an ng-annotate issue.

**Comment by nikolowry** [comment]
I was facing a weird problem - everything would compile great but if I minified my 'main.js' w uglify then the app was completely broken in IE8 only. 

I'm all for "purism" and following spec - but I'd also like to use this in production with no worries.  It be much appreciated if you could accommodate a "transitional" period, you could even pre-plan depreciation dates in advance.

Regardless great work!

**Comment by sebmck** [comment]
@nikolowry #1369 #1382

**Comment by nikolowry** [comment]
@sebmck thanks it was late - should have poked around more

**Comment by timoxley** [comment]
I made a module you can use to wrap classes as factories thus allowing them to be called with or without `new`: https://github.com/timoxley/to-factory

**Comment by damassi** [comment]
@olov - this is popping up for us in IE8 and your fix seems to have handled it.  Only arose after the latest npm install of babel 5.6.15.

**Comment by Download** [comment]
Is there anyone else that cares about bundle size? Can we please have the option to skip this function call? I just checked some transpiled code and it really adds a lot of overhead to class-heavy code. Everywhere I see this same line....

Before transpilation:

```js
class MyClass extends MyMixin(class {}) {}
```

After:

```js
var MyClass = function (_MyMixin) {
  _inherits(MyClass, _MyMixin);

  function MyClass() {
    _classCallCheck(this, MyClass);

    return _possibleConstructorReturn(this, _MyMixin.apply(this, arguments));
  }

  return MyClass;
}(MyMixin(function () {
  function _class2() {
    _classCallCheck(this, _class2);
  }

  return _class2;
}()));
```

**Comment by loganfsmyth** [comment]
Keep in mind that once you account for gzip the difference is probably much less.

**Comment by hzoo** [comment]
> Yeah but that's still an option that endorses this usage. If you want non-ES6 classes then you can just write non-ES6 classes.

Also https://github.com/babel/babel/pull/4850 (we can add to loose mode)
