### ISSUE TITLE
babel-polyfill is outdated

### ISSUE THREAD

**Issue by bifunctor** [babel/babel#7983]
Hi babel team
The doc [polyfill](https://babeljs.io/docs/usage/polyfill/#usage-in-node--browserify--webpack) seems to be outdated. 

Old:
```
module.exports = {
  entry: ["babel-polyfill", "./app/js"]
};
```
New 
```
entry: ['@babel/polyfill', './src/index.js'],
```

Thanks

**Comment by loganfsmyth** [comment]
`@babel/polyfill` is for Babel 7's beta. The website docs are still all for Babel 6 since that is the stable version.
