### ISSUE TITLE
'transformFromAst' should avoid mutating the AST passed into it

### ISSUE THREAD

**Issue by jonhartnett** [babel/babel#7987]
## Bug Report

**Current Behavior**
The description in the documentation for `transformFromAst` in `@babel/core` does not make it obvious that the input AST object is transformed *in-place*. A cursory reading would imply that the input is readonly and only under closer inspection hints that the input might be changed.

**Possible Solution**
Add a simple blurb that says 

> The AST object passed in is transformed in-place. To preserve the original object, make a deep copy before passing it in.

**Comment by loganfsmyth** [comment]
Good point, I'd probably say we should clone the AST before transforming, rather than leaving the in-place mutation logic.

**Comment by thiagoarrais** [comment]
Anyone tackling this? I'd like to give it a try.

**Comment by thiagoarrais** [comment]
Do you folks have any preferred method for deep cloning? I'm currently using JSON.stringify -> JSON.parse

**Comment by loganfsmyth** [comment]
I wonder how that would do on larger ASTs, since we could potentially end up with an extremely large string as an intermediate value. If we could clone following those semantics without actually creating the intermediate, that seems like it would be ideal.

**Comment by jonhartnett** [comment]
Preferably, include a boolean option to disable cloning so that external cloning can be done in performance-sensitive contexts.

**Comment by loganfsmyth** [comment]
@jonhartnett My preference would probably be to wait and see if people bring it up as a real performance concern. I'd expect 99% of people to be using the non-AST version anyway.

**Comment by thiagoarrais** [comment]
Found another method for cloning: `t.cloneNode`. I'm not sure if that is better (memory and CPU-wise) than the JSON method, though... Any ideas?

**Comment by loganfsmyth** [comment]
I think a generic deep clone is the best way to go for this usecase. `t.cloneNode` only copies a specific whitelist of fields.

**Comment by thiagoarrais** [comment]
Ended up opting for lodash's cloneDeep. See the [discussion on the PR](https://github.com/babel/babel/pull/8342#discussion_r203967259) for details.
