### ISSUE TITLE
Feature Request: Closure elimination

### ISSUE THREAD

**Issue by phpnode** [babel/babel#799]
There are many scenarios where it's convenient to use a closure or an arrow function, but it's not required. For instance:
```js
function doSomething (items) {
  return items.map(item => item.toUpperCase());
}
```

In cases like this, where the closure doesn't actually reference anything else in `doSomething`'s scope, it should be possible to automatically hoist that into a separate top level function. This avoids allocating a new function on every `doSomething` invocation, and will provide a nice speed boost.

It should be compiled into something like:

```js
function $$_doSomething_map1 (item) {
  return item.toUpperCase();
}

function doSomething (items) {
  return items.map($$_doSomething_map1);
}
```

it'd be awesome if this could be done via an optional transformer.

**Comment by sebmck** [comment]
This is actually on my list of transformer ideas :stuck_out_tongue_winking_eye: 

> Hoist function expressions and wrap their calls with local variables etc

Just hesitant on rushing into these kinds of transformations because there are a lot of things that need to be handled.

**Comment by benjamingr** [comment]
This would be great among other optimizations. Is there a place listing all the optimizations babel does, can do, will do, might do and won't do?

**Comment by sebmck** [comment]
@benjamingr Only optimisations that are done currently are tail recursion optimisation and the type optimisation stuff detailed [here](https://github.com/babel/babel/issues/653#issuecomment-74050432). I've currently got a big list of potential optimisations that I want to look into to see how viable they are, ie. whether there'd be potential issues with implementing them or enabling them by default etc.

**Comment by domenic** [comment]
I don't know how this could ever be safe. The implementation of `items.map` could be

```js
items.map = function (f) {
  if (this.oldF === f) {
    throw new Error("you used the same f twice!");
  }
  this.oldF = f;
};
```

which would throw an error with this "optimization" and would throw no errors given normal ES6 semantics.

**Comment by sebmck** [comment]
@domenic It isn't which is why it'd be behind a flag and documented extensively like loose mode. In the next major there's going to be a transformation API so I can push this out to userland so I don't need to support or endorse it.

**Comment by sebmck** [comment]
Closing this in preparation for the plugin API as this is something I'd like to push out to userland (see #987).

**Comment by gaearon** [comment]
Also interested in experimenting with this for a smarter non-React-specific version of Hot Loader.
