### ISSUE TITLE
@babel/plugin-transform-modules-commonjs incorrectly assumes default exists when importing an __esModule

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#7998]
## Bug Report

When running native ESM in Node.js (via `.mjs`) you are supposed to be able to use an ESM default import to import the module exports of a CJS module:

https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs

Babel will cause the default import to be `undefined` at runtime in the following situation:

- Your source is ESM being compiled with `@babel/plugin-transform-modules-commonjs`.
- The CJS being imported was compiled for distribution using Babel from ESM named exports without a default export. The CJS module exports `__esModule` but no `default`.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAcygQzACwI4Bs4DMoQhwDkSqmWA9MAHYAmApgB4B0AVgM7EBQ3AxhBocIWBiywQEACjLpsLAOIp0ARQAyAZT5oGIZAEogA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=&prettier=false&targets=&version=7.0.0-beta.46&envVersion=

Input:

```js
// Contains CJS with __esModule, but no default.
import graphql from 'graphql/index.js'

// Should not log undefined.
console.log(graphql.GraphQLSchema)
```

Flawed output:

```js
"use strict";

var _index = require("graphql/index.js");

var _index2 = _interopRequireDefault(_index);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log(_index2.default.GraphQLSchema);
```

**Expected behavior/code**

At runtime, `GraphQLSchema` should log instead of `undefined`.

**Babel Configuration (.babelrc, package.json, cli command)**

Default usage of `@babel/plugin-transform-modules-commonjs` or `@babel/preset-env`.

**Environment**
- Babel version(s): v7.0.0-beta.47
- Node/npm version: Node v10.1.0/npm v6.0.1
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: No
- How you are using Babel: `cli`

**Possible Solution**

**Additional context/Screenshots**

The example input demonstrates a workaround to https://github.com/graphql/express-graphql/issues/425.

**Comment by jaydenseric** [comment]
At the moment, I am having to do this workaround-for-a-workaround…

In `graphql.js`:

```js
const {  __esModule, ...graphql } = require('graphql')
module.exports = graphql
```

In `index.mjs`:

```js
import graphql from './graphql'
console.log(graphql.GraphQLSchema)
```

**Comment by nicolo-ribaudo** [comment]
Would this be fixed by https://github.com/babel/babel/issues/6449?

**Comment by loganfsmyth** [comment]
Yeah the short answer here is just that from Node's standpoint, a Babel-compiled module is still just a CommonJS module, and it's probably right to do so.

I'm happy to leave this open because I do think there could be ways to fix this as long as we limit things to default-only exports, but since node's support is so new, it's not really something we've worked on yet.

**Comment by guybedford** [comment]
FWIW this was originally brought up in https://github.com/babel/babel/issues/2148.

**Comment by guybedford** [comment]
Sorry previous comment was incorrect here - deleted. I'm not sure I follow this issue though, if `graphql/index.js` contains __esModule then all will work out fine. Not sure why the workaround is necessary to add __esModule either?

**Comment by guybedford** [comment]
Ahh, reading https://github.com/babel/babel/issues/7294 makes more sense here. Will respond there.
