### ISSUE TITLE
-0 gets printed as 0 in Babel

### ISSUE THREAD

**Issue by mjesun** [babel/babel#8001]
## Bug Report

**Current Behavior**
`t.numericLiteral` does not support `-0`.

**Input Code**
http://astexplorer.net/#/gist/c5f83ae7704f4089946202031abba218/3c1d2aa4249f46f18aa4b58c0b995d353d0d5186

**Possible Solution**
Check that `0` is `-0` with `Object.is` before printing it.

**Comment by loganfsmyth** [comment]
Interesting, I that's something we should treat as a bug in `valueToNode`, good catch.

**Comment by mjesun** [comment]
Sounds good to me! Having `valueToNode` take care of it looks like a good strategy.

**Comment by loganfsmyth** [comment]
Alright, here's a PR: https://github.com/babel/babel/pull/8005

Also probably a reasonable candidate for backporting but it'd be best to let it bake on 7.x for a few days after our next publish.
