### ISSUE TITLE
Make babel tell me the minimum version of target that supports my code without transformation

### ISSUE THREAD

**Issue by benjamincburns** [babel/babel#8008]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It would be nice if babel could tell me the minimum version of a target (starting with nodejs) which supports my code without transformation or polyfill.

This would enable me to do three things:

1. Set the `engine` field in my package.json to the exact minimum version required for my code.
2. Scan my project's dependencies so that I can minimize the number of project dependencies which I must transform and package into my build in order to meet my desired target version. 
3. Detect when dependencies have forgotten to update their own `engine` field. 

**Describe the solution you'd like**
A minimum viable solution (for my use case) would be an argument to babel-cli or some plugin which spat out the minimum version of node required for the code it processed, preferably transformations would not be applied when this argument is specified.

An ideal version of this tool would be able to handle this task for multiple targets (ie. browsers as well as node), and also be able to accept an argument specifying the desired minimum engine version which would generate a listing of language features or built-ins used which are not compliant with the desired target version.

**Comment by loganfsmyth** [comment]
The difficulty with all of this is, generally this is super difficult to know up front. If your code contains the function

```
export function hasThing(value, item) {
  return value.includes(item);
}
```

what is this referring to? If could require an ES2015 engine if `value` is a String, but it could also require an ES2016 engine if `value` is an Array.

For a large portion of code, Babel has to assume the worst, or expect uses to load a large general polyfill, which will check the environment at runtime. Even things like `Object.keys` have changes in ES2015, but we can't tell if your code relies on that or not, so as soon as your code uses `Object.keys` we'd have to say your code relies on ES2015 features.

**Comment by benjamincburns** [comment]
Thanks for the reply, @loganfsmyth - this sounds like something type hints could help out with. Is there a TypeScript-aware babel?

**Comment by loganfsmyth** [comment]
You could likely build something using type information from TS or Flowtype, and you could certainly explore using Babel's parsing and general AST tooling to build something like that, but you wouldn't want to do it as a Babel plugin.

**Comment by benjamincburns** [comment]
Thanks for weighing in. With that info, I suppose I'll close this.
