### ISSUE TITLE
False positive?: core.log.js

### ISSUE THREAD

**Issue by rubenhazelaar** [babel/babel#801]
Was just installing babel, however I got - what I think/presume is - a false positive from my antivirus. 

Some logging:

node_modules\babel-core\node_modules\core-js\src\core.log.js
Heur.Dual.Extensions@4294967295

Hope it helps others, with the same issue.

**Comment by sebmck** [comment]
That's crazy, definently a false positive. Doubt there's anything that can be done. /cc @zloirock

**Comment by zloirock** [comment]
Wow... If it will be a often problem, I'll think about renaming the file.
