### ISSUE TITLE
Fallback to babel-core. You might want to upgrade to @babel/core soon.

### ISSUE THREAD

**Issue by B1nke** [babel/babel#8014]
## Bug Report

**Current Behavior**
Some time after 7th of may our builds started to fail with this message in CI

> Fallback to babel-core. You might want to upgrade to @babel/core soon.

Usually this is probably not an issue but when then sending the output to uglify-js, an error occurs when it's trying to parse the text.
Because babel 7 is still in beta, there's no preset for Riot yet and I have to use babel 6.

**Expected behavior/code**
Just outputting the file content with no extra message

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc
```js
{
  "presets": ["es2015-riot"]
}
```
package.json script that is executed
```js
{
   "build:js": "browserify -t [ babelify ] -t [ riotify -c --type es6 --exclude css ] -t [ envify --NODE_ENV production ] -e src/index.js -v -d | uglifyjs -mc > ../dist/index.js"
}
```

**Environment**
- Babel version(s): v6.26.0
- Node/npm version: any I tried (using node 10.1.0, npm: 5.3.0)
- OS: Multiple (Windows)
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
Remove the message about updating to a beta version

**Additional context/Screenshots**
```
[14:34:41][Step 1/1] npm info ok 
[14:34:43][Step 1/1] Parse error at -:1,9
[14:34:43][Step 1/1] Fallback to babel-core. You might want to upgrade to @babel/core soon.
[14:34:43][Step 1/1]          ^
[14:34:43][Step 1/1] SyntaxError: Unexpected token: name (to)
[14:34:43][Step 1/1]     at JS_Parse_Error.get (eval at <anonymous> (..\Web\Apps\registerNewUnit\node_modules\uglify-js\tools\node.js:27:1), <anonymous>:86:23)
[14:34:43][Step 1/1]     at ..\Web\Apps\registerNewUnit\node_modules\uglify-js\bin\uglifyjs:384:39
```

**Comment by loganfsmyth** [comment]
> Fallback to babel-core. You might want to upgrade to @babel/core soon.

That message isn't something that Babel displays. It looks like it comes from [the riot compiler](https://github.com/riot/compiler/blob/87e051095af77b230664dd1ea8f40d411d6ec364/lib/parsers/es6.js#L16), so you'd have to raise this with them.

For what it's worth, I understand what they are doing there, but it seems like a ugly thing to be doing. They shouldn't be trying to load Babel at all unless they've got their own dependency on it, or implemented a plugin system where you as a user would opt in.

**Comment by hzoo** [comment]
Yeah not sure there is anything actionable on our side so going to close, thanks!
