### ISSUE TITLE
`path.evaluate` wrongly returning with confidence on && expression

### ISSUE THREAD

**Issue by mjesun** [babel/babel#8017]
## Bug Report

**Current Behavior**
`z() && undefined` is `path.evaluate`'d to `undefined` with confident set to `true`

**Input Code**
http://astexplorer.net/#/gist/52894896cb2e791ec2f5b4f405175ec1/1cc1f21330b2b8bc0df178bea039da61c9305af6

**Possible Solution**
Don't return `true` when there can be side-effects 😄

**Comment by mjesun** [comment]
I think the root of the issue is [here](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/evaluation.js#L258):

> If we are confident that one side of an && is false, or the left side of an || is true, we can be confident about the entire expression

The "one side of an &&" is not correct, it should be "the right side of an &&".

**Comment by mjesun** [comment]
@loganfsmyth Just a friendly ping, this popped up after the `-0` bug 🙂

**Comment by mjesun** [comment]
Btw, [this affects Babel's minifier too](https://babeljs.io/repl/#?babili=true&browsers=ie%206&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABARwBQEpEG8BQjEBOAplCAUsAIYA2AzkQNw4C-OOAbpQYgF6IC8KDIgBkIxOAAmRYDDBFJTHDGCJUffpsRU6RTLnwQEtONSIA6anADmqAMzomzIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Cstage-0%2Cstage-1%2Ces2015-loose%2Cbabili&prettier=true&targets=&version=6.26.0&envVersion=1.6.2).

**Comment by liuxingbaoyu** [comment]
Has been fixed.
