### ISSUE TITLE
Babel Transform `+=` with `await`

### ISSUE THREAD

**Issue by ICELI** [babel/babel#8027]
## Bug Report

**Current Behavior**
Babel transform `x += await 2`  different with `x = x + await 2`
but  node v8.9.4 or chrome 66.0 that also be the same 

**Input Code**
- REPL or Repo link if applicable:
```js
let x = 0

let log = function() {
  console.log(x, 'log')
  return 2;
}

async function test() {
  // x += await log() // case 1
  x = x + await log() // case 2
  console.log(x, 'test')
}

test()

x += 1
console.log(x, 'global')

// case1
// 0 "log"
// 1 "global"
// 3 "test"


// case2
// 0 "log"
// 1 "global"
// 2 "test"

```

http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBAHhC8EAYBQTSWAewOZwgMwFcA7AYzAEsMiAKASggG8kIISqBnDUAOky2qgAaCAHI-I2swgAncAWlEIAJgDcSAL4oAhuwCepfMTKVFYEOzB1GUgPQ3oEANTwtAdy3l02K3dY6QEACMUjDwMI4Qbh5e_PS-JP7KUmxEnDx8AsIiZhYSGig5lpJI4fDBKWkgvN5ColiYAEZawHlI8f7BvggQAER8PW32gb31GE3AA74AzL2FAyjt7CBKg4i9_avDPaPjk_ZKs-Zg80A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=latest%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

**Comment by nicolo-ribaudo** [comment]
Moved to facebook/regenerator#345. Thank you for the bug report!
