### ISSUE TITLE
beta48 decorators regression

### ISSUE THREAD

**Issue by natew** [babel/babel#8041]
Using @babel/preset-stage-2 with decoratorsLegacy on 47 was fine, with 48 it complains that it doesn't see the transform:

```
SyntaxError: src/effects/poof.js: Decorators transform is necessary.
```

**Comment by loganfsmyth** [comment]
Without knowing the specifics of your config, it's not really possible to give direction on the issue here. You seem to have deleted our issue template, but if you have a minute to fill that out it would make a big difference.

**Comment by natew** [comment]
I'll add in the details.

Using Node 9 on High Sierra. Babel 7 beta 48.

Config is dynamically generated but it looks like this, everything on latest version (48):

```
'react-hot-loader/babel'
'@babel/plugin-transform-runtime',
'@mcro/babel-plugin-if'
'@mcro/gloss/transform',
'@babel/plugin-proposal-export-default-from'
'@babel/plugin-proposal-class-properties',
'@babel/plugin-proposal-decorators',
'babel-plugin-root-import',
'babel-plugin-transform-react-jsx',
'babel-plugin-lodash'
'@babel/preset-react'
'@babel/preset-stage-2',
'@babel/preset-typescript'
```

**Comment by loganfsmyth** [comment]
Can you try putting `'@babel/plugin-proposal-decorators',` before `'@babel/plugin-proposal-class-properties',`?

**Comment by dnalborczyk** [comment]
I'm having the same problem. switching the order didn't help.

reverting @babel/plugin-proposal-class-properties to beta 47 worked.

**Comment by the-simian** [comment]
I think I'm experiencing this as well, I was getting the error: `Support for the experimental syntax 'decorators' isn't currently enabled`, and then it was prompting me to add the `@babel/plugin-proposal-decorators` package

I do this (and I am mindful to add this before the proposal-class-properties  plugin), and then it says I need to set the legacy flag to true. So I do this and then...

i get the first error again, in an endless loop.

I am setting back to .47 to see if this resolves my issue.

**Comment by loganfsmyth** [comment]
Is one of you working on a public codebase I could look at, or potentially able to put put together a reproduction repository example?

**Comment by the-simian** [comment]
Yo. going back to .47 totally fixes it.

**Comment by hzoo** [comment]
Thanks for the info, it's weird that the error stack trace says Babylon because we renamed it to `@babel/parser`. So it seems like a dep mismatch?

**Comment by dnalborczyk** [comment]
@loganfsmyth I'll try to create a repo

@the-simian 

> once you'd configured it as you see, there was an error thrown in the missing-plugins-helper... and it would say you need to add @babel/plugin-proposal-decorators. The weird thing was that if you added it and did NOT put legacy:true it would detect it and say you need to add the legacy: true config... but once you added it.. it was like it wasn't there at all.

the errors are being thrown by different plugins. the `legacy` option was added to the decorators plugin to shield from the new/changed decorators proposal. the `decorators transform necessary` is being thrown by the class-properties proposal, and was recently added (with private properties).

**Comment by existentialism** [comment]
@dnalborczyk 

From @the-simian:

```
    at _class.raise (E:\Users\Simian\Desktop\RadProject\node_modules\@babel\core\node_modules\**babylon**\lib\index.js:779:15)
```

**Comment by the-simian** [comment]
You all seem surprised by the presence of babylon in the dependency graph. Heres what was installed:
![image](https://user-images.githubusercontent.com/954596/40523103-b609d8f2-5f99-11e8-9be6-95bb0f6af61c.png)

my `node_modules` on the left, my `package.json` on the right

**Comment by loganfsmyth** [comment]
@the-simian The issue is that you said your issue was with `beta.48`, but `babylon` was renamed to `@babel/parser` in `beta.48`, so any stack trace mentioning `babylon` either must be from `@babel/core < beta.48`.

**Comment by the-simian** [comment]
Oh man, am I in the wrong place?

**Comment by dnalborczyk** [comment]
@hzoo I totally missed that :smiley:

@loganfsmyth here is a reduced repro:

```javascript
export default class {
  @foo
  bar() {}
}
```

```javascript
const plugins = [
  ['@babel/plugin-proposal-decorators', { legacy: true }],
  ['@babel/plugin-proposal-class-properties', { loose: true }]
]
```

**Comment by loganfsmyth** [comment]
Alright, I've tracked down the primary issue causing the 

> Decorators transform is necessary.

error. It appears that validation added in the current beta is catching an edge case that was introduced way back in beta.37, but didn't actually cause any issues.

@nicolo-ribaudo The issue is the loss of this visitor: https://github.com/babel/babel/commit/b93184e430c5785dad197f53f73904a2a06fc1ed#diff-9edac3b7447086939a48e78f20989ef8L218 in favor of this logic https://github.com/babel/babel/commit/b93184e430c5785dad197f53f73904a2a06fc1ed#diff-9edac3b7447086939a48e78f20989ef8R230 that reaches into the parent. Because the transform reaches into the parent to replace the _parent_ instead of itself, traversal of the AST has already reached the class declaration by the time it is replaced. This means that even though it is replaced, the class property transform will still try to process it, which means the new validation added in https://github.com/babel/babel/pull/7842/files#diff-58f25136e574c8f618d51c7e6a454270R275 will throw.

The best fix, in my mind, would be to go back to using a `ExportDefaultDeclaration` visitor there if we can.

I don't have to jump on this now, but I can give it a shot tomorrow if you haven't gotten to it yet.

**Comment by dnalborczyk** [comment]
thanks @nicolo-ribaudo !  I can confirm, beta.49 fixes it!

_just a note for everyone still experiencing the issue:_

`decorator-plugin` has to be loaded BEFORE `class-properties-plugin` now. otherwise the error still appears.

**Comment by vjpr** [comment]
@dnalborczyk Can confirm this simple change worked for me.

**Comment by liubin915249126** [comment]
@the-simian but i got this "You gave us a visitor for the node type PrivateName but it's not a valid type"

**Comment by TWry** [comment]
I had the same issue which could be fixed by changing the order of the plugins (decorator before class-properties). This should really be documented in a prominent way.

**Comment by nicolo-ribaudo** [comment]
It is :slightly_smiling_face: https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babel-plugin-proposal-class-properties
