### ISSUE TITLE
beta.48 dynamic import path regression

### ISSUE THREAD

**Issue by KevinGrandon** [babel/babel#8042]
# v7 Regression

**Describe the regression**
Upgrading from beta.47 -> beta.48 broke dynamic import paths in our build system. It seems that the import paths may be getting messed with somehow.

I believe it's changing a relative path into an absolute path, and will try to narrow this down further.

I will continue to investigate this and update this issue during the investigation. Opening this in case other people are seeing breakage.

**Input Code**
We are making the upgrade in this pull request: https://github.com/fusionjs/fusion-cli/pull/373

**Babel Configuration**

We have a pretty complex build, but have presets here:
https://github.com/fusionjs/fusion-cli/blob/master/build/babel-transpilation-preset.js
https://github.com/fusionjs/fusion-cli/blob/master/build/babel-fusion-preset.js

**Expected behavior/code**
Dynamic imports with relative paths continue to work.

**Environment**
- Babel version(s): [v7.0.0-beta.48]
- Node/npm version: [Node 8.10/yarn 1.7]
- OS: [OSX 10.13.4]

**Comment by loganfsmyth** [comment]
Could potentially be a regression from https://github.com/babel/babel/pull/7956 but it's hard to say what specifically would have been affected by that.

**Comment by KevinGrandon** [comment]
This is now most likely fixed by #8044. Will test this out after the next patch version, thanks so much for the quick fix.

**Comment by existentialism** [comment]
@KevinGrandon beta.49 is out!

**Comment by loganfsmyth** [comment]
@existentialism Beat me to it!

**Comment by KevinGrandon** [comment]
It looks like our failing test case here is now passing, thanks all!
