### ISSUE TITLE
Babel don't transpiling code in local package

### ISSUE THREAD

**Issue by perevezencev** [babel/babel#8048]
## Bug Report

My folders structure looks like this:
```
/testproject
    /local-package
      package.json
    /src
package.json
```
/testproject/package.json
```
  "dependencies": {
    "local-package": "file:./local-package",
```

/testproject/webpack.config.js
```
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules(?!\/local-package)/,
        use: ["babel-loader"]
      }
    ]
  },
```

**Current Behavior**

When I am run `webpack --mode production` I get an error

```
ERROR in ./local-package/components/NotFound.jsx
Module build failed: SyntaxError: /Users/pavel/Projects/JS/testproject/local-package/components/NotFound.jsx: Unexpected token (4:2)

  2 |
  3 | const NotFound = () => (
> 4 |   <div>
    |   ^
  5 |     <h3>404 page not found</h3>
  6 |     <p>We are sorry but the page you are looking for does not exist.</p>
  7 |   </div>
```

**Steps to reproduce**

1. clone repo `git clone https://github.com/perevezencev/webpack-error.git`
2. run `yarn link` inside `/webpack-error/local-package`
3. run `yarn link "local-package"` inside `/webpack-error`
4. run `yarn` inside `/webpack-error`
5. run `yarn build` inside `/webpack-error`

https://gist.github.com/perevezencev/2c985c5a4f2c2ab9a89b9afd2989d409

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc
```
{
  "presets": [
    "@babel/react",
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "modules": false
      }
    ]
  ]
}
```
npm command
```
  "scripts": {
    "build": "webpack --mode production"
  },
```
[webpack.config.js](https://pastebin.com/XxsqcUzn)
```
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules(?!\/local-package)/,
        use: ["babel-loader"]
      }
    ]
  },
```
**Environment**
- Babel version(s): 

1. @babel/core: 7.0.0-beta.48
2. @babel/preset-env: 7.0.0-beta.48
3. @babel/preset-react: 7.0.0-beta.48
4. babel-loader: 8.0.0-beta.2
5. webpack: 4.8.3
6. uglifyjs-webpack-plugin: 1.2.5

- Node/npm version: 

1. Node: v9.3.0
2. npm: 5.5.1

- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: loader

**Comment by xtuc** [comment]
It's likely due to the new configuration resolution. If you transform your configuration to [`babel.config.js`](https://github.com/babel/babel/blob/master/babel.config.js) it will be applied in all the files of your project.

**Comment by perevezencev** [comment]
Yes, it works. Thank you 🙏
