### ISSUE TITLE
Static Class Features: Stage 3

### ISSUE THREAD

**Issue by rricard** [babel/babel#8052]
# Static Class Features: Stage 3

> Advance Static Class Features for Stage 3 (Shu-yu Guo @syg) (Daniel Ehrenberg @littledan)

Proposal co-written with @tim-mc and @robpalme. We also intend to follow up and implement it with @rpamely,  @tim-mc, @mkubilayk .

## Info

Proposed at TC39 Meeting: [May 2018](https://github.com/tc39/agendas/blob/master/2018/05.md)

Slides at the meeting: https://docs.google.com/presentation/d/1YzFr7EIGiX2YagfFMjkI-lVR6ouoRfPbTNLY--NGbC4/edit?usp=sharing

Proposal Repo: https://github.com/tc39/proposal-static-class-features/

Complete article on the subject by Shu-yu Guo: https://rfrn.org/%7Eshu/2018/05/02/the-semantics-of-all-js-class-elements.html

Babel contribution recommended by @jridgewell to @robpalme

The work to be done towards Stage 3 will be added in [`plugin-proposal-class-properties`](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-class-properties).

### Static Public Fields

```javascript
class Account {
  static routingNumber = 1017;
  get transactionIdPrefix() {
    return `${Account.routingNumber}-${this.uuid}`;
  }
}
```

### Static Public Methods

```javascript
class Account {
  static convertToEuro(dollars) {
     return util.USDToEuro(dollars);
  }

  get euroConversionDisplayAmt () {
    return `Current Balance (EUR): ${Account.convertToEuro(this.accountBalance)}`
  }
```

### Static private fields

```js
class Account {
  static #transactions = [];
  static get nbTransactions() {
    return Account.#transactions.length;
  }
  getDollars() {
    return Account.#transactions.reduce(/* ... */);
  }
}
```

### Static private methods

```js
class Account {
   // ...
  static #makeTransaction(dollars, from, to) {
    Account.#transactions = this.#transactions.concat(/* ... */);
  }
  
  transfer(dollars, targetAccount) {
    return Account.#makeTransaction(dollars, this, targetAccount);
  }
}
```

## Basic Rules

- Check that the `<Class Name>.#<static private field/method>` notation is within the lexical scope of `<Class Name>` - Checked during transform
- Check that the `this.#<static private field/method>` has a _provenance_ of `<Class Name>` - See Subclassing Hazard in the [slides](https://docs.google.com/presentation/d/1YzFr7EIGiX2YagfFMjkI-lVR6ouoRfPbTNLY--NGbC4/edit?usp=sharing) (around slide 13) - Checked at runtime

## ESTree/Parsing

- For the `static` keyword, we use the existing parser
- For the `#` character, we use (or enhance) the existing parser (thanks to the work done in #7842 - Class private properties)

### Public

- Public static fields/methods will be added to the `<Class Name>` object
- Accessors will be added using `Object.assign`

### Private

- Transform to use helper functions similar to private instance fields: `classStaticPrivateFieldGet` and `classStaticPrivateFieldSet`
- Add an in-closure `_<static private fields/method>` variable outside of the class that will be manipulated by the helper functions
- Here is a potential output of the two last examples put together, in order to explain how to achieve privacy:

```js
var Account =
/*#__PURE__*/
function () {
  "use strict";

  function Account() {}

  babelHelpers.createClass(Account, [{
    key: "transfer",
    value: function transfer(dollars, targetAccount) {
      babelHelpers.classStaticPrivateFieldGet(Account, _makeTransaction)(dollars, targetAccount);
    }
  }, {
    key: "getDollars",
    value: function getDollars() {
      babelHelpers.classStaticPrivateFieldGet(Account, _transactions).reduce(/* ... */);
    }
  }]);
  
  Object.assign(Account, {
    get nbTransactions() {
      return babelHelpers.classStaticPrivateFieldGet(Account, _transactions).length;
    }
  });

  var _makeTransaction = function(dollars, from, to) {
    babelHelpers.classStaticPrivateFieldSet(Account, _transactions, babelHelpers.classStaticPrivateFieldGet(this, _transactions).concat(/* ... */));
  };

  var _transactions = [];

  return Account;
}();
````

Note that those implementation details **are not final** but a way to start the conversation and the actual implementation.

cc @jridgewell, @robpalme, @rpamely,  @tim-mc, @mkubilayk

**Comment by jridgewell** [comment]
Thanks for the write up!

A few notes:

> For the # character, we use (or enhance) the existing parser 

This we should already parse everything, including private methods/accessors. We just don't yet have a transformer for them.

> Accessors will be added using Object.assign

Babel already has the helpers to assign public static accessors using `createClass`'s third param. In fact, all transforms necessary for public fields/methods/accessors should already be done.

If you can find any non-spec behavior, though, please correct it!

> Here is a potential output of the two last examples put together, in order to explain how to achieve privacy:

Your output looks great. I just want to confirm that the static private helpers will be using strict equality on the class (and should be using a const reference to the class). This is a neat optimization we can make for them, avoiding the `WeakMap`s necessary for instance privates.

- - -

For the design of private methods/accessors, I had originally thought we could fall back to the fields behavior without any issues. But this won't account for accessors, which which is difficult to handle correctly. We'd have to store them as some object with `get`/`set` keys, and call them appropriately:

```js
const _accessor  = {
  get() {
    // user's getter code
  },
  set(v) {
    // user's setter code
  }
};

_accessor.get.call(ClassName)
```

**Comment by rricard** [comment]
Thank you for the information, that will help us a lot. I'll start fiddling around with an implementation this weekend.

**Comment by hzoo** [comment]
I usually post this in https://github.com/babel/proposals/issues/12 but all good since we are already about implementing at this point!

**Comment by rricard** [comment]
I opened #8205 for early feedback. Keep in mind that this is far from finished (see prev. comment) but it gives an idea of the architectural choices made and we can discuss them here before going further. Next goal is to be able to run that against test-262 and make sure it passes for that feature (and backport some missing tests in babel from 262)

**Comment by nikolay** [comment]
The semantics of `#` are quite far from 'private'. I recommend using another character (for example, `~`) or better yet - the `private` modifier. Is many language the convetion is using leading underscores - I don't get why this has to be a different character!

**Comment by nicolo-ribaudo** [comment]
You can find many discussions about it at https://github.com/tc39/proposal-class-fields

**Comment by franktopel** [comment]
Any updates with this? As of now, using `@babel/plugin-proposal-class-properties` along with `babel-loader` for this code:

```javascript
class A {
  #name="A";
  constructor() {
    console.log(this.#name);
  }
}
```
gives me 

```
SyntaxError: [...] : Unknown PrivateName #name

```

This is my `.babelrc`:

```json
{
    "presets": [
        "@babel/preset-env"
    ],
    "plugins": [
        "@babel/plugin-transform-classes",
        "@babel/plugin-proposal-class-properties"
    ]
}
```
This feature has already been shipped in Chrome 74 if I remember correctly.
