### ISSUE TITLE
`return` in `do` expressions error instead of .

### ISSUE THREAD

**Issue by dead-claudia** [babel/babel#8055]
## Bug Report

**Current Behavior**
A syntax error:

```
repl: 'return' outside of function (6:6)
  4 |       foo();
  5 |     } catch (e) {
> 6 |       return bar();
    |       ^
  7 |     }
  8 |   };
  9 |   return wrap(x);
```

**Input Code**
- REPL or Repo link if applicable: http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABKSAKAlIg3gKEYgNwEMAnRAD0QF5EATObPfRKEgT0eeeDjgwG4m-AL6IIRKBAAWiVAFNMuLvhJyoIEkgBGpAUMTCmwwSrUakAdxJEADqnLpBwoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-0%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

```js
function func() {
  var x = do {
    try {
      foo();
    } catch (e) {
      return bar();
    }
  };
  return wrap(x);
}
```

**Expected behavior/code**
I expected it to generate something functionally close to this:

```js
function func() {
  var x;
  try {
    x = foo();
  } catch (e) {
    return bar();
  }
  return wrap(x);
}
```

**Comment by loganfsmyth** [comment]
Yeah the do expression transform could probably use a full rewrite. What's there was basically thrown in randomly ages ago using Babel's existing logic for conversing statements to expressions, and is just whatever logic existed at the time. That logic is _very_ lacking once you get past the absolute basics.
