### ISSUE TITLE
Top Level Await: Stage 2

### ISSUE THREAD

**Issue by leimonio** [babel/babel#8056]
> top-level `await` proposal for ECMAScript to Stage 2 (Myles Borins) [@MylesBorins](https://github.com/MylesBorins)

# Info
Proposed at TC39 Meeting: [May 2018](https://github.com/tc39/agendas/blob/master/2018/05.md)
Slides at the meeting: https://docs.google.com/presentation/d/1lTTiNosXlqk78FO7Ze_CdMbF3PhO36kCk-mT783wpi8/edit#slide=id.p
Proposal Repo: https://github.com/tc39/proposal-top-level-await

# Example
**1.1**
```
function foo() {
    await bar();
}
```

instead of:
```
async function foo() {
    await bar();
}
```

**1.2**
```
import a from 'aDynamicModule.js';

console.log(a);
```

instead of:
```
(async () => {
  const a = await import('./aDynamicModule.js');
 
  console.log(a);
})();
```

# Basic Rules
* function and IIAFEs that are utilizing `await` don't have to use the top-level `async` function
* import dynamic modules as usual imported modules ex. `import a from './aDynamicModuls.js'`

**Comment by nicolo-ribaudo** [comment]
We are keeping track of it at https://github.com/babel/proposals/issues/44!

**Comment by leimonio** [comment]
@nicolo-ribaudo Thanks for letting me know! Babel is really big as repo, so it's really difficult to keep track of what is going on!
