### ISSUE TITLE
Error extending builtin: "ReferenceError: _construct is not defined"

### ISSUE THREAD

**Issue by chocolateboy** [babel/babel#8061]
### Current Behavior

A typo was introduced in `@babel/runtime/helpers/wrapNativeSuper.js` in #7533 which results in an error when trying to extend a builtin type: `ReferenceError: _construct is not defined`.

Interestingly, the error only occurs if the external helpers are used (i.e. via `@babel/plugin-transform-runtime`), which suggests that there's a discrepancy between the inlined and external implementations of `wrapNativeSuper` (and other helpers?).

#### Input Code

```js
class Test extends Array {
    foo () {
        return 42
    }
}

const test = new Test()

console.log(test.foo())
```

#### Expected output

```
42
```

#### Actual output

```
./node_modules/@babel/runtime/helpers/wrapNativeSuper.js:28
      return _construct(Class, arguments, getPrototypeOf(this).constructor);
      ^

ReferenceError: _construct is not defined
    at Test.Wrapper (./node_modules/@babel/runtime/helpers/wrapNativeSuper.js:28:7)
    at new Test (./test.js:24:95)
    at Object.<anonymous> (./test.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module._compile (./node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.newLoader [as .js] (./node_modules/pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

#### package.json

```json
{
  "devDependencies": {
    "@babel/core": "7.0.0-beta.49",
    "@babel/node": "7.0.0-beta.49",
    "@babel/plugin-transform-runtime": "7.0.0-beta.49",
    "@babel/preset-es2015": "7.0.0-beta.49",
    "@babel/runtime": "7.0.0-beta.49"
  }
}
```

#### .babelrc

```js
{
    presets: ['@babel/preset-es2015'],
    plugins: ['@babel/plugin-transform-runtime'],
}
```

#### Test

```
$ ./node_modules/.bin/babel-node ./test.js
```

#### Environment
- Babel version(s): v7.0.0-beta.48, v7.0.0-beta.49
- Node/npm version: v10.1.0/npm 5.6.0
- OS: Linux (Arch)
- How you are using Babel: `cli`, `loader`

**Possible Solution**

```diff
--- node_modules/@babel/runtime/helpers/wrapNativeSuper.js
+++ node_modules/@babel/runtime/helpers/wrapNativeSuper.js.new
@@ -25,7 +25,7 @@
     }
 
     function Wrapper() {
-      return _construct(Class, arguments, getPrototypeOf(this).constructor);
+      return construct(Class, arguments, getPrototypeOf(this).constructor);
     }
 
     Wrapper.prototype = _Object$create(Class.prototype, {
```

**Comment by loganfsmyth** [comment]
Good catch. Not sure why it wouldn't also be an issue with the inlined helpers.

Would you be interested in submitting a PR? If not that's totally fine.

**Comment by fantasywind** [comment]
Workaround: 

```javascript
const ErrorClass = Error;

class Permission extends ErrorClass {
  /* ... defines */
}
```

Waiting for PR, thanks!

**Comment by benjamn** [comment]
Are most folks not using `@babel/plugin-transform-runtime`? Seems like this would be a much bigger problem, if they were. Is there some other best practice that I've missed, or are people really just inlining helpers in every module?

Either way, it would be great to see a `7.0.0-beta.50` release soon!
