### ISSUE TITLE
Class method is undefined

### ISSUE THREAD

**Issue by throrin19** [babel/babel#8063]
## Bug Report

**Current Behavior**

In update @babel/core from `7.0.0-beta.47` to `7.0.0-beta.48`, I have a problem with my classes. Declared methods are undefined in beta.48 and beta.49 version.

If I rollback babel version, the code works correctly

**Input Code**

```js
class MyClass extends Collection {
    setPageSize(pageSize) {
        this._pageSize = pageSize;
    }
}

const obj = new MyClass();

obj.setPageSize(12); // TypeError: obj.setPageSize is not a function
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "plugins": [
        "lodash"
    ],
    "presets": [
        "poi",
        ["@babel/env", {
            "targets": {
              "browsers": [
                ">0.25%",
                "not ie 10",
                "not op_mini all"
              ]
            }
        }]
    ]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.48, 7.0.0-beta.49
- Node/npm version: Node v8.11.1 / NPM v5.8.0
- OS: OSX 10.13.4
- Monorepo: yes
- How you are using Babel: `loader`

**Comment by dnalborczyk** [comment]
can't repro, tested with `@babel/register` as well as `webpack` with `babel-loader`

```javascript
class Collection {}

class MyClass extends Collection {
  setPageSize() {}
}

const obj = new MyClass()

console.log(typeof Object.getPrototypeOf(obj).setPageSize) // function
```

@throrin19  could you create a minimal repository to reproduce the issue?

**Comment by loganfsmyth** [comment]
What is `Collection` in this context? If `Collection` is an uncompiled class, and `MyClass` is being compiled, that would likely explain it.

**Comment by throrin19** [comment]
@loganfsmyth After that, I include directly source files into my project (and not autobuild vue-mc) to see if the problem is in my side or in their side.

I have another error this time.

In my Collection, if I call an instancied method in the constructor, I have the error `TypeError: _this.clearState is not a function`. This is my class :

```js
class Collection extends Base {
    constructor(models = [], options = {}, attributes = {}) {
        super(options);

		// error, this contains only Base function
        this.clearState();
    }
}
```

This is the compilated result for this constructor (it's same on beta 47 and beta 51)

```js
function Collection() {
    var _this;

    var models = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];
    var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
    var attributes = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};

    _classCallCheck(this, Collection);

    _this = _possibleConstructorReturn(this, _getPrototypeOf(Collection).call(this, options));

    _this.clearState(); // Set all given attributes.

    return _this;
}
```

I check methods called to generate `_this` :

- `_possibleConstructorReturn` : same on babel 7 beta47 and 51
- `_assertThisInitialized` : same on babel 7 beta47 and 51
- `_getPrototypeOf` : I have a difference in that. I think the problem is here
    - Beta 47 :
        ```js
        function _getPrototypeOf(o) { _getPrototypeOf = Object.getPrototypeOf || function _getPrototypeOf(o) { return o.__proto__; }; return _getPrototypeOf(o); }
        ```
    - Beta 51 : 
        ```js
        function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }
        ```

**Comment by throrin19** [comment]
The bug is already present in Beta 52

**Comment by throrin19** [comment]
Ok, I found the bug. After research I try to update the preset I use : `babel-preset-poi` but the package use old versions (7.0.0.beta.40).

I try to reproduce configuration with last versions packages and it works fine :)
