### ISSUE TITLE
Babel not finding `filename` when upgrading from beta46 to beta49

### ISSUE THREAD

**Issue by aryzing** [babel/babel#8065]
## Bug Report

**Current Behavior**
The following error is being thrown when using babel:

```
[BABEL] unknown: Configuration contains explicit test/include/exclude checks, but no filename was passed to Babel
```

**Input Code**

The following is part of a Jest transformer responsible for transpiling the code before running the tests:

```js
const babel = require('@babel/core')
const babelConfig = require('../babel/.babelrc.test.js')
const fs = require('fs');
const path = require('path')

// https://babeljs.io/docs/usage/api/#options
const compilerOptions = {
  ast: false,
  sourceMaps: 'inline',
  ...babelConfig,
}

module.exports = {
  process(src, path) { // path is source file path
    if (path.endsWith(".js") || path.endsWith(".jsx") || path.endsWith(".ts") || path.endsWith(".tsx")) {
      return babel.transform(src, { ...compilerOptions, sourceFileName: path }).code
    } else {
      console.log("Unknown file extension received for transforming.")
    }
    return src
  }
}
```

**Expected behavior/code**
It wasn't failing before, and I don't think the error is accurate: there are no test/include/exclude tests in the config.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  "presets": [
    ["@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/typescript",
    ["@babel/preset-react", {
      "development": true
    }]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-dynamic-import"
  ],
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49]
- Node/npm version: v10.0.0 / 5.6.0
- OS: OSX
- Monorepo no
- How you are using Babel: api

**Possible Solution**
Improve the error message by
* removing the "`unknown`" part, it's not useful, and frankly it's confusing.
* remove the part about test/include/exclude if that's not the case.
* although in this particular example no test/include/exclude options were set, if there are default ones under the hood, let devs know what those are.
* possible (although very simplified) proposal error message: 
> You must include `filename` in the compiler options for test/include/exclude checks to work. Note that although you may not have specified any, the default ones are being applied

and specify which ones they are, or where to find them.

**Comment by loganfsmyth** [comment]
We can make that error message more helpful. Ideally it should tell you where it found `test`/`include`/`exclude` at least. The message is because you're using `"@babel/typescript"`, which requires the filename because it needs to know if it gets a `.ts` or `.tsx` file now.

Due to that, you need to provide a filename to Babel. The issue is that you're currently using `sourceFileName` which is unrelated and does not affect the config loading process. Probably all you need is to do `filename: path`.

**Comment by malbernaz** [comment]
I'm having the same trouble here. But it doesn't make sense to me to specify a filename since I'm compiling for jest and therefore will have potentially more then one file to test.

**Comment by aryzing** [comment]
Great, thanks for that. Did not know that `@babel/typescript` used the path file extension as a trigger.

I was under the impression that the transforms used were a function of the AST, even for typescript.

`filename: path` did the trick, thank again!
