### ISSUE TITLE
@babel/template tries to replace uppercase strings

### ISSUE THREAD

**Issue by djfarly** [babel/babel#8067]
# v7 Regression

> First check out: https://new.babeljs.io/docs/en/next/v7-migration.html
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Potential Commit/PR that introduced the regression**
Somewhere between v6 and v7 - not quite sure though… also the cafe is closing so i don't have time to investigate further, sorry! 

**Describe the regression**
AST generation fails for ALLCAPS strings. I think it should not.  🤔 

**Input Code**

[Reduced test case here.](https://repl.it/repls/GaseousMindlessTests)
```js
var template = require("@babel/template");

const string = "var a = { a: 'NormalString', b: 'UPPERCASESTRING' };"

console.log(template.default(string)())
```
This throws:
```
Error: @babel/template placeholder "UPPERCASESTRING": Expected string substitution
```

[Working v6 here.](https://repl.it/repls/ObeseHotpinkAddition)
```js
var template = require("babel-template");

const string = "var a = { a: 'NormalString', b: 'UPPERCASESTRING' };"

console.log(template(string)())
```
This works flawlessly.

**Babel Configuration (.babelrc, package.json, cli command)**
none

**Expected behavior/code**
It should create an AST normally, taking into account that 'UPPERCASESTRING' is just a string.

**Environment**
- Babel version(s): In REPL 7.0.0-beta.49
- Node/npm version: Tested in node 9 + 10
- OS: OSX (local) + linux/amd64 (REPL)
- Monorepo (does not matter?)
- How you are using Babel: babel/template directly in [babel-plugin-codegen](https://github.com/kentcdodds/babel-plugin-codegen)

Thanks a ton! 🎉 ❤️

**Comment by loganfsmyth** [comment]
This was a breaking change in the API, but it was purposeful. If you're interested you can read over the docs in the README. https://github.com/babel/babel/blob/7846eaebaa69662134782b35d9bdff9b71616aa1/packages/babel-template/README.md

In this case, you have two easy options:

* Use `placeholderPattern: false` so it stops searching for replacement patterns entirely.
  * ```console.log(template(string, { placeholderPattern: false })())```
* Use an ES6 template literal with `.ast`
  * ```console.log(template.ast`var a = { a: 'NormalString', b: 'UPPERCASESTRING' };`)```

**Comment by djfarly** [comment]
Awesome! Thank you @loganfsmyth.
That was rather quick. 🤐👍
