### ISSUE TITLE
babel-runtime buildin issue with Edge

### ISSUE THREAD

**Issue by oliviertassinari** [babel/babel#8068]
## Bug Report

**Current Behavior**
I think that the following logic has some edge cases:
https://github.com/babel/babel/blob/7846eaebaa69662134782b35d9bdff9b71616aa1/packages/babel-runtime/helpers/builtin/iterableToArray.js#L2

`Symbol.iterator in Object(document.querySelector('div').children)` is `true` on Chrome 66 but `false` on Edge 17. 

**Input Code**

For instance, let's say you are writting:
```jsx
const list = [...document.querySelector('div').children];
```

The following code can be transpiled by Babel@7.0.0-beta.42 into:
```jsx
var _toConsumableArray2 = _interopRequireDefault(require("@babel/runtime/helpers/builtin/toConsumableArray"));

var items = (0, _toConsumableArray2.default)(document.querySelector('div').children);
```

https://github.com/babel/babel/blob/2af7a33c4e41d6f45daf84a366e80757ad7d4d81/packages/babel-helpers/src/helpers.js#L801-L809

**Expected behavior/code**

`TypeError Invalid attempt to spread non-iterable instance` error shouldn't be thrown when running the code in Edge (all versions between 15-17).

https://github.com/babel/babel/blob/2af7a33c4e41d6f45daf84a366e80757ad7d4d81/packages/babel-helpers/src/helpers.js#L881-L885

**Environment**
- Babel version(s): 7.0.0-beta.42
- Node/npm version: v10.0.0
- OS: Windows 10
- How you are using Babel: runtime

**Context**

The issue was first reported in https://github.com/mui-org/material-ui/issues/11607.

**Comment by zloirock** [comment]
That means only that you should load `core-js` / `@babel/polyfill` because you need a polyfill for `HTMLCollection` iterator.

**Comment by loganfsmyth** [comment]
How are you handling polyfilling? Are you loading Babel's polyfill, or using preset-env, not doing nothing? As mentioned, it's generally up to the polyfill to ensure that things are iterable, though how people load polyfills varies.

**Comment by oliviertassinari** [comment]
> How are you handling polyfilling?

@loganfsmyth We don't load any polyfill nor we plan on loading any. To be fair, I have no idea what to expect. In order to make my code work, I would need to call `Array.from` on a `HTMLCollection`. I can live with the fact that `Symbol.iterator in Object(iter)` isn't supported yet on Edge and that it will eventually work like it does on Chrome. 

Thanks for taking the time to answer my issue.

> Are you loading Babel's polyfill, or using preset-env, not doing nothing?

We are using babel-runtime builtin with no polyfill in order to save bundle size.

**Comment by loganfsmyth** [comment]
Gotcha, yeah if you're treating anything as an general iterable rather than working specifically with arrays, polyfills become necessary for older environments.
