### ISSUE TITLE
Drop Node 0.11 support

### ISSUE THREAD

**Issue by shinnn** [babel/babel#807]
https://github.com/babel/babel/blob/5156574bf27d8d14ca42ddb3205ae73d73a34ecf/.travis.yml#L5

We don't need to support *older and unstable* version, I think.

**Comment by sebmck** [comment]
There's no harm in leaving it in there.

**Comment by shinnn** [comment]
Also correct.

**Comment by sebmck** [comment]
I completely glossed over the fact that 0.11 was unstable. I've removed it from travis, thanks!

**Comment by shinnn** [comment]
@sebmck Yay, really nice!
