### ISSUE TITLE
Parallel CLI processes outputting to the same non-existent dir cause intermittent "file already exists" mkdir error

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#8077]
### Current Behavior

Parallel CLI processes outputting to the same non-existent dir cause intermittent "file already exists" mkdir error. This was not an issue a few beta versions back.

Sometimes the error occurs 50% of the time, probably due to a race condition. Perhaps a CLI process errors when the directory is created by another process before it can complete it's own mkdir operation.

### Babel Configuration (.babelrc, package.json, cli command)

With this package.json (extract):

```json
{
  "scripts": {
    "clean": "rimraf lib",
    "mjs": "BABEL_ESM=1 babel src -d lib --keep-file-extension",
    "js": "babel src -d lib",
    "prepublishOnly": "npm-run-all clean --parallel mjs js"
  }
}
```

[Here are the docs for the npm-run-all dependency/CLI](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md.).

This command will cause the `file already exists` mkdir error on random occasions:

```sh
npm run prepublishOnly
```

Don't be confused by the `mjs` script; if it was identical to the `js` script the issue would arise the same. I just wanted to show a realistic example.

### Environment
- Babel version(s): v7.0.0-beta.49
- Node/npm version: Node.js v10.2.1 / npm v6.1.0
- OS: macOS v10.13.4
- Monorepo: No
- How you are using Babel: `cli`

### Possible Solution

The CLI should gracefully ignore the error if a directory is created by another process before it can complete it's own mkdir operation, and just use the directory now it exists.

### Additional context/Screenshots

I would like to be able to compile the same source to both `.js` and `.mjs`, in the same `lib` directory for distribution. As the Babel CLI does not support multiple targets, it must be run twice with an env var dictating the target type. Although this issue does not arise when running the scripts in series, compile time can be halved by running these scripts in parallel.

<img width="1008" alt="screen shot 2018-05-30 at 12 44 04 pm" src="https://user-images.githubusercontent.com/1754873/40696013-3657186e-6407-11e8-9a97-400ff66b0eb3.png">

**Comment by loganfsmyth** [comment]
Good catch! No idea why it just popped up now, but should be fixed.
