### ISSUE TITLE
Why adding promise-polyfill for IOS9

### ISSUE THREAD

**Issue by Genuifx** [babel/babel#8078]
## Bug Report
Here is the support of Promise in [caniuse](https://caniuse.com/#search=promise)
![image](https://user-images.githubusercontent.com/10156994/40712405-3e9e6f6c-6430-11e8-8c3f-d20dce62f3c9.png)

i use babel7 and preset-env to polyfill my project, while with the following configs:
```javascript
{
    "sourceMap": false,
    "presets": [
        ["@babel/preset-env", {
            "targets": {
                "browsers": ["last 2 Chrome versions", "last 3 iOS major versions"]
            },
            "useBuiltIns": "usage",
            "debug": true
        }],
        ["@babel/preset-stage-2", {
            "decoratorsLegacy": true
        }]
    ],
    "plugins": [
        "@babel/plugin-transform-async-to-generator",
        "@babel/plugin-transform-spread"
    ],
    "ignore": ["node_modules", "src/main.js"]
}

```

with debug ouput:

![image](https://user-images.githubusercontent.com/10156994/40712574-a0fdea66-6430-11e8-8775-c973fbf09d9c.png)

So, why we need promise-polyfill here.

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: node8
- OS: macos
- How you are using Babel: js api

**Comment by zloirock** [comment]
> Why adding promise-polyfill for IOS9

Because iOS9 fails 2 from 8 `compat-table` test. `compat-table` definitely is not a perfect tests source here, but `caniuse` much worse.
