### ISSUE TITLE
Object rest spread syntax error when supported by env

### ISSUE THREAD

**Issue by Billy-** [babel/babel#8084]
## Bug Report

**Current Behavior**
I am transpiling a node application running on node V9.9.0 - which supports object rest spread out of the box. I am using `babel-preset-env` targeting `node: "current"`. I expect the object rest spread to not be transpiled and work without a problem. However, babel seems to be tripping up on it (SyntaxError).

**Input Code**
An object rest spread

**Expected behavior/code**
The code is not transpiled and works fine because it's running in a node environment which supports it

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ],
  "retainLines": true,
  "plugins": [
    "lodash",
    "transform-runtime"
  ]
}
```

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: Node v9.9.0/ npm v5.6.0 / yarn v1.5.1
- OS: Running in node-alpine docker image...
- Monorepo: no
- How you are using Babel: register for development, but build production code with cli, both have the same issue

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/4316168/40776731-91133cbc-64c3-11e8-8ca6-0d9cd558cf52.png)

**Comment by existentialism** [comment]
@Billy- thanks for the issue!

preset-env support for object-rest-spread was added to, and is available, in the v7 betas (@babel/preset-env).

To enable this in v6, you can add `babel-plugin-syntax-object-rest-spread`.

**Comment by Billy-** [comment]
Sounds like this is misunderstanding on my part  so I will close the issue (although it is unintuitive because I would expect something that works in the version of node I'm running to "just work" :stuck_out_tongue_closed_eyes:).

**Comment by greim** [comment]
@Billy - It threw me for a loop too at first, but given Babel has its own syntax parser—which is completely separate from the underlying JS engine's parser—it makes sense how the two can get out of sync.

**Comment by hzoo** [comment]
@greim good points, can certainly be confusing. To be clear, the reason is that the default behavior of the parser is to fail the syntax in v6 that data wasn't updated given work on v7 (since last year)
