### ISSUE TITLE
preset-env needlessly transforms async functions for Firefox 52

### ISSUE THREAD

**Issue by stasm** [babel/babel#8086]
## Bug Report

**Current Behavior**
When `preset-env` is configured to support Firefox 52+, it needlessly transforms async functions to `regeneratorRuntime`-compatible code.

**Input Code**
- [REPL](https://babeljs.io/repl/#?babili=false&browsers=Firefox%2052&build=&builtIns=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsI2QJwcgCwAoBKGAbwCgYaYcBTZBHLXBegbkoF8g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

**Expected behavior/code**
`async function` should stay written as `async function`.

Note that for other browser versions listed in the snippet below (e.g. `Chrome 55`), async functions are not transformed, which is the expected behavior.

https://github.com/babel/babel/blob/ab62a9439918edf97eeea730a444a622542696ff/packages/babel-preset-env/data/plugins.json#L211-L220

For Firefox versions before 52, it should be also possible to use `_asyncToGenerator` which doesn't require the `regeneratorRuntime`. Firefox has supported generators since version 26.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    ["@babel/preset-env", {
      modules: false,
      targets: {
        browsers: [
          "Firefox >= 52",
        ]
      }
    }]
  ],
}
```

**Environment**
- Babel version(s): `v7.0.0-beta.47`
- Node/npm version: Node 9.11.1, npm 6.1.0
- OS: Windows 10, using WSL
- How you are using Babel: `rollup-plugin-babel`.

**Comment by hzoo** [comment]
Guess this ended up being the same as https://github.com/babel/babel/issues/8204? Issue unfortunately or not is that we are using compat-table for data and it's saying it doesn't meet requirements for supporting generators until 53 even if it was supported earlier (say the syntax vs rest of the semantics)
