### ISSUE TITLE
Problem with the new, "decoratorsBeforeExport" option

### ISSUE THREAD

**Issue by gordon-matt** [babel/babel#8088]
I am getting started with webpack for the first time ever (version 4) and relatively new to babel as well (only used it with JSPM for Aurelia for a short while before now wanting to move to webpack).

Anyway, I am having a problem with the new, **decoratorsBeforeExport** option. I keep getting this error message:

`Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead, or set the 'decoratorsBeforeExport' option to true.`

I have the following Babel packages listed in my package.json:

```
"@babel/core": "^7.0.0-beta.5",
"@babel/plugin-proposal-class-properties": "^7.0.0-beta.5",
"@babel/plugin-proposal-decorators": "^7.0.0-beta.5",
"@babel/plugin-transform-runtime": "^7.0.0-beta.5",
"@babel/preset-env": "^7.0.0-beta.5",
"@babel/preset-stage-2": "^7.0.0-beta.5",
"@babel/runtime": "^7.0.0-beta.5",
"babel-loader": "^8.0.0-beta.3",
"babel-plugin-transform-decorators": "^7.0.0-beta.3"
```

and the following setup in my **webpack.config.js**:

```
test: /\.js?$/,
use: {
    loader: 'babel-loader',
    options: {
        //presets: ['@babel/preset-env'],
        //plugins: ['transform-decorators']
        presets: [
            ["@babel/preset-env", { "modules": false }],
            "@babel/preset-stage-2"
        ],
        plugins: [
            "@babel/plugin-transform-runtime",
            ["@babel/plugin-proposal-decorators", { "legacy": true, decoratorsBeforeExport: true }],
            ["@babel/plugin-proposal-class-properties", { "loose": true }]
        ]
    }
}
```

I'm not sure if I even have **decoratorsBeforeExport** in the right place. I have also tried adding it directly under the **plugins** section to no avail. I guess I am doing something stupid here, but not sure what.

**Comment by nicolo-ribaudo** [comment]
Can you set your `@babel/*` dependencies to `7.0.0-beta.49` (without `^`). Different beta versions may not be compatible which eachother.

**Comment by gordon-matt** [comment]
@nicolo-ribaudo Thanks for the response. I just did as you suggested, but then I got this error:

**The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2**

So, I tried doing this:

```
test: /\.js?$/,
use: {
    loader: 'babel-loader',
    options: {
        //presets: ['@babel/preset-env'],
        //plugins: ['transform-decorators']
        presets: [
            ["@babel/preset-env", { modules: false }],
            ["@babel/preset-stage-2", { decoratorsBeforeExport: true }]
        ],
        plugins: [
            "@babel/plugin-transform-runtime",
            ["@babel/plugin-proposal-decorators", { legacy: true }],
            ["@babel/plugin-proposal-class-properties", { loose: true }]
        ]
    }
}
```

It still gave the same message. So, I tried this instead:

```
test: /\.js?$/,
use: {
    loader: 'babel-loader',
    options: {
        //presets: ['@babel/preset-env'],
        //plugins: ['transform-decorators']
        presets: [
            ["@babel/preset-env", { modules: false }],
            "@babel/preset-stage-2"
        ],
        plugins: [
            "@babel/plugin-transform-runtime",
            ["@babel/preset-stage-2", { decoratorsBeforeExport: true }],
            ["@babel/plugin-proposal-decorators", { legacy: true }],
            ["@babel/plugin-proposal-class-properties", { loose: true }]
        ]
    }
}
```
 
But of course that gives a new error as well:
 
**Module build failed: Error: Cannot find module '@babel/plugin-preset-stage-2**

**Comment by gordon-matt** [comment]
OK it seems this problem has been solved, but there's a new error. So I will close this issue and open a new one.
