### ISSUE TITLE
Make the plugin naming less strict

### ISSUE THREAD

**Issue by malbernaz** [babel/babel#8091]
I would like to publish a babel plugin named following the pattern `@scope/babel-plugin`. Currently this is not possible. My opinion is that this could be accepted.

**Comment by loganfsmyth** [comment]
Seems reasonable to me.

**Comment by xtuc** [comment]
Isn't possible in 7 already?

**Comment by malbernaz** [comment]
I'm using beta 47 and it is not.

**Comment by loganfsmyth** [comment]
You'd have to explicitly say `module:@scope/babel-plugin`, otherwise Babel will see `@scope/babel-plugin` and look for `@scope/babel-plugin-babel-plugin`. We explicitly expect `babel-plugin-` as the prefix.

**Comment by malbernaz** [comment]
I'm aware, it works with `module:`. But what I'm proposing is that a pattern like that should be accepted

**Comment by loganfsmyth** [comment]
Sorry, that reply was meant for @xtuc :) I agree with what you're proposing.
