### ISSUE TITLE
Method override is not working as it should be while using transform class properties

### ISSUE THREAD

**Issue by vimal1083** [babel/babel#8093]
## Bug Report

**Current Behavior**
Method override is not working as it should be while using transform class properties

**Input Code**
- [REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8BQ1oBcCmE3QLzQAoBKPAPkRVWmAHsA7CGkDAOhBoHMCByDYACxrQAZgCcaAW2rgYsbkUoBfJMqShIMAELQMAD0x0AJrIqpM2Yqaq0GTVuy68BQsZOmRom-UpVI_N7GgaACMAKzxoOgwAd09iJBDQlnM0YgBuaAB6TJ1nEXEpdVkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

```js
class A {
  test = () => {
    console.log('echo from clas A')
  }
}

class B extends A {
  test() {
    console.log('echo from clas B')
  }
}


const obj = new B()
obj.test(); // echo from clas A
```

**Expected behavior/code**
It should print `echo from clas B` instead it prints the other. Basically, method override has not happened

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["es2015"],
  "plugins": [
      "transform-object-rest-spread",
      "transform-async-to-generator",
      "transform-class-properties"
    ]
}
```

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: v8.11.1
- OS: OSX 10.13.4
- How you are using Babel:  `register`

**Comment by loganfsmyth** [comment]
> Method override is not working as it should be while using transform class properties

It's not working because class fields aren't methods, so there is no method to override. Class fields are assigned to the _instance_ of a class, which means that any class property will take priority over something that lives on the class prototype, like a method.

Your sample is no different than if you did

```
class A {
  constructor() {
    this.test = () => {
      console.log('echo from class A');
    };
  }
}
class B extends A {
  test() {
    console.log('echo from class B');
  }
}
```
so assigning `this.test` will hide any `test` on `B.prototype`.
