### ISSUE TITLE
Compile Bug in math compute function. 

### ISSUE THREAD

**Issue by weifuchuan** [babel/babel#8097]
## Bug Report

**Current Behavior**
I write a program that has a class and some functions for calculations. It works normally in the development environment and does not work in the production environment. Through the positioning, I found the wrong place, which may be a bug in babel.

**Input Code**

My code: 

```js
class Color{
    // ... other code
    xyz() {
       return LinearRgbToXyz(...this.linearRgb());
    }
}
function LinearRgbToXyz(r, g, b) {
  let x = 0.4124564 * r + 0.3575761 * g + 0.1804375 * b;
  let y = 0.2126729 * r + 0.7151522 * g + 0.0721750 * b;
  let z = 0.0193339 * r + 0.1191920 * g + 0.9503041 * b;
  return [x, y, z];
}
```

Compiled code：

```js
xyz(){
  return function(e, t, n){
      return [.4124564 * e + NaN + NaN, .2126729 * e + NaN + NaN, .0193339 * e + NaN + NaN];
  }(...this.linearRgb());
}
```

**Expected behavior/code**

I hope to compile the normal code. 

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc
```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": 7
        },
        "useBuiltIns": true
      }
    ],
    "stage-0",
    "react"
  ],
  "plugins": [
    "add-module-exports"
  ],
  "env": {
    "production": {
      "presets": [
        "react-optimize"
      ],
      "plugins": [
        "dev-expression"
      ]
    },
    "development": {
      "plugins": [
        "transform-class-properties",
        "transform-es2015-classes",
        [
          "module-resolver",
          {
            "alias": {
              "app": "./app",
              "main": "./app/main",
              "renderer": "./app/renderer",
              "common": "./app/common"
            }
          }
        ]
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 6.26
- Node/npm version: 8.1.12
- OS: Windows 10
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: `register`

**Comment by jridgewell** [comment]
Bebel doesn’t provide a compile math transform.

**Comment by weifuchuan** [comment]
Just now I used TypeScript to rewrite this class and then tsc was compiled and used. It works fine.

**Comment by weifuchuan** [comment]
@jridgewell My question is why the normal calculation function is compiled to be abnormal.  : (

**Comment by nicolo-ribaudo** [comment]
This is not a bug with any official Babel plug-in. You are using some plug-in which does function inlining but it's doing it wrong.

**Comment by nicolo-ribaudo** [comment]
Probably it is `react-optimize`
