### ISSUE TITLE
Proxy plugin is missing for ios_safari 9

### ISSUE THREAD

**Issue by leonprou** [babel/babel#8102]
## Bug Report

**Current Behavior**
I use the [Proxy object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) in my app. This proxy object doesn't supported on the ios safari, as seen in [caniuse](https://caniuse.com/#search=proxy). But babel doesn't use any polyfill plugin, so the app's not working on IOS safari 9.0.

**Expected behavior/code**
 I expect that the babel will add a polyfill plugin for that Proxy, a [babel-plugin-proxy](https://www.npmjs.com/package/babel-plugin-proxy) I guess.

**Babel Configuration (.babelrc, package.json, cli command)**

```
{
  "presets": [["env", {
      "targets": {
        "browsers": ["last 2 versions", "ios >= 9"]
      }
    }], "react", "stage-2"]
}
```

**Environment**
- Babel version(s): v6.26.3
- Node/npm version: Node 8/npm 6
- OS: OSX 10.13.4
- Monorepo yes
- How you are using Babel: I use webpack with babel-loader

**Comment by nicolo-ribaudo** [comment]
Unfortunately proxies can't be polyfill, and that plugin explicitly warns about using it in production because it will make your whole app super slow.
I suggest not using proxies if you want to support old browsers. If you really need them, you can enable the plug-in you linked.
