### ISSUE TITLE
Babel v7, Nextjs v6 upgrade: .ignore is not allowed in preset options

### ISSUE THREAD

**Issue by TawKhoury** [babel/babel#8103]
# v7 Regression

**Describe the regression**
I am trying to upgrade to babel v7 to work with NextJs v6. I am using Lerna to manage multiple packages. All packages run babel.js in `react-base` package to set .babelrc for each package. 
 * `.babelrc` file at each package root::
 ` { "presets": ["@app/react-base/babel.js"] }`

**I get an unexpected error of**  : ' .ignore is not allowed in preset options'.
When adding "ignore" to each .babelrc it does partially work, for example: 
  * `.babelrc` file at each package root:
 ` { "presets": ["@app/react-base/babel.js"],
      "ignore": ["**/*.{spec,test}.{js,jsx}", "**/{__tests__/,__mocks__/,__snapshots__/}"]
    }`

**My question is why ignore not supported with a preset option in the first place like it worked with babel v6 before the upgrade. And how we could include the ignore option in `presets` in a better way to work with babel.js as before**

**Babel Configuration (.babelrc, package.json, cli command)**

`package.json` dependencies in `react-base`.
```js
"dependencies": {
    "@babel/cli": "7.0.0-beta.44",
    "@babel/core": "7.0.0-beta.44",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.44",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.44",
    "@babel/preset-env": "7.0.0-beta.44",
    "@babel/preset-flow": "7.0.0-beta.44",
    "@babel/preset-react": "7.0.0-beta.44",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.2",
    "babel-jest": "^20.0.3",
    "babel-loader": "^8.0.0-beta.0",
    "chalk": "^2.3.0",
    "commitizen": "^2.9.6",
    "config": "^1.26.2",
    "cross-spawn": "^5.1.0",
    "cz-lerna-changelog": "^1.2.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.0",
    "enzyme-to-json": "^3.3.1",
    "eslint": "^4.18.2",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jest": "^21.13.0",
    "eslint-plugin-jsdoc": "^3.5.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "flow-bin": "^0.58.0",
    "globby": "^6.1.0",
    "inquirer": "^3.3.0",
    "jest": "^22.1.1",
    "jest-environment-jsdom": "^22.3.0",
    "jest-environment-jsdom-global": "^1.0.3",
    "jest-fetch-mock": "^1.4.1",
    "jest-localstorage-mock": "^2.2.0",
    "prettier": "^1.11.1",
    "react-styleguidist": "^6.0.20",
    "react-test-renderer": "^16.3.2",
    "resolve-from": "^3.0.0",
    "rimraf": "^2.6.2",
    "serialize-javascript": "^1.4.0",
    "webpack": "^3.5.5"
  },
```
`babel.js` in `react-base`.

```
const presets = [ '@babel/react', '@babel/flow', ];
const plugins = [ '@babel/plugin-proposal-class-properties', '@babel/plugin-proposal-object-rest-spread', ];
const ignore = [];

switch (process.env.BABEL_ENV) {
  case 'commonjs':
    presets.push([
      '@babel/env',
      {
        targets: {
          node: '8',
        },
      },
    ]);
    break;

  case 'esm':
    presets.push([
      '@babel/env',
      {
        targets: {
          browsers: require('./browsers'),
          forceAllTransforms: true,
        },
        modules: false,
      },
    ]);
    break;
  case 'esnext':
  default:
    break;
}

switch (process.env.NODE_ENV) {
  case 'test':
    break;
  default:
    ignore.push('**/*.{spec,test}.{js,jsx}');
    ignore.push('**/{__tests__/,__mocks__/,__snapsh

module.exports = function htzReactBasePreset(api, opts) {
  return {
    presets,
    plugins,
    ignore, // **Not working correctly with babel v7**
  };
```

**Environment**
- Babel version(s): [v7.0.0-beta.44]
- Webpack version: [v3.5.5]
- Node/npm version: [Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [Lerna]
- How you are using Babel: [`cli`, `loader`]

**Comment by loganfsmyth** [comment]
Can you elaborate on what your goal is with the ignore? `ignore` in this context disables _all_ Babel processing in those files, even if other presets are active.

On recent version of `@babel/core` (not sure if Next uses that yet), you can tell Babel to ignore a specific configuration object (like your set off plugins/presets), using `exclude`. Would that be sufficient? e.g.
```
module.exports = function htzReactBasePreset(api, opts) {
  return {
    exclude: [
      // ...
    ],
    presets,
    plugins
  };
}
```
This will _specifically_ skip this set of `presets` and `plugins`, but allow other config data passed to Babel to be processed still.

**Comment by TawKhoury** [comment]
Thanks, but still not working. Ignore should work with preset options to ignore compiling test files/snapshots. Preset options not allowing exclude/ignore.

**Comment by loganfsmyth** [comment]
Yes, at the moment they are now allowed to use `ignore` and `exclude`, the reasoning being that it should likely be up to the user to decide what is and isn't ignored.

On the other hand, presets _are_ allowed to use the new `test`/`include`/`exclude`. My question is, is that sufficient to address your usecase? I have a hard time imagining a case where a preset dictate what files are processed and which are entirely skipped. It seems like `test`/`include`/`exclude` would be more in line with user's expectations.

**Comment by TawKhoury** [comment]
Thanks for your help.

How does the new preset's `test`/`exclude` ignore the test/snapshot files? Didn't work for me.

To be more clear:
Each package in the project has a .babelrc file.
For example, `.babelrc` at `css-tools` package looks like this: 
```
{
  "presets": ["@app/react-base/babel.js"], // generated from babel.js (see above).
  "ignore": ["**/*.{spec,test}.{js,jsx}", "**/{__tests__/,__mocks__/,__snapshots__/}"]  // added this now but not working either 
}

```

All I need that test/snapshot files to be ignored when building them packages like it was before with babel v6.
