### ISSUE TITLE
.babelrc doesn't seem to work correctly after 7.0.0-beta.45

### ISSUE THREAD

**Issue by specialkk** [babel/babel#8105]
## Bug Report

**Current Behavior**
 When I attempt to build my Webpack project with a working directory outside of the project root, Babel seems to completely ignore the `.babelrc` at the project root. For example, I have a project configured to use `@babel/preset-stage-3` in `.babelrc`, but building results in 

```
ERROR in ./bootstrap.js
Module build failed: SyntaxError: W:\projects\babel-bug\src-44\bootstrap.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (3:18):

  1 | const test = { a: 1, b: 2, c: 3 };
  2 |
> 3 | const spread = { ...test };
    |                  ^
  4 |

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
```

**Input Code**
[Repo link](https://github.com/specialkk/babelrc-beta45-bug)

**Expected behavior/code**
I don't think `.babelrc` should be ignored under these circumstances. This was last working on v7.0.0-beta.44.

**Environment**
- Babel version(s): v7.0.0-beta.45+
- Node/npm version: Node 8/npm 6
- OS: Windows 10/Linux
- How you are using Babel: babel-loader

**Comment by loganfsmyth** [comment]
You can do `cwd: __dirname` in the options for `babel-loader` to lock down Babel's working directory to your project root, which would fix this.

Babel now uses the working directory to decide what packages are considered "root" and which ones aren't, so if you run Webpack from outside of your root package, Babel will think your nested package is just some random dependency, like any `node_module` for instance, and ignore any configuration it defines for itself.

**Comment by XhmikosR** [comment]
Are there any official docs about the cwd change? I'm hitting this with our Bootstrap repo and karma. It's the only thing preventing me from updating babel.

**Comment by xtuc** [comment]
@XhmikosR we are currently documenting it, see https://new.babeljs.io/docs/en/next/babelconfigjs.html#merging-behavior. Let's us know if there anything to change.

**Comment by XhmikosR** [comment]
@xtuc: thanks! I need to see why our karma coverage breaks with babel after beta 45 and onward.

**Comment by XhmikosR** [comment]
@xtuc: I tried using `--config-file ./.babelrc.js` for babel-cli but it doesn't seem to work for beta51. Going back to beta 44 works fine.

Here's where we are calling babel https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L41-L42. I'm probably missing something, but shouldn't this transition be more smooth?

**Comment by XhmikosR** [comment]
Never mind, sorry for the noise. Our issue was because of rollup-plugin-babel. Updating to 4.0.0-beta-5 fixes the issues :)

**Comment by XhmikosR** [comment]
Spoke too soon. For starters we are hitting #8182. After that is sorted I'll see if we need any other options.

**Comment by XhmikosR** [comment]
I think this is the same as #8184. @loganfsmyth pinpointed the cause: after the recent micromatch update things broke on Windows.

I made #8201 so that we test things on Windows.

**Comment by loganfsmyth** [comment]
I think this issue is resolved, right @specialkk ?

@XhmikosR I think the issue in https://github.com/babel/babel/issues/8184 is separate, so let's continue this over there.
