### ISSUE TITLE
babel-core cannot be imported in browser due to regression in 'debug'

### ISSUE THREAD

**Issue by tvooo** [babel/babel#8109]
## Bug Report

**Current Behavior**
Bundling babel-core and importing it (not even using it) inside the web bundle causes an error:

> process.stderr is undefined

Bundle and run this in a web browser:

```js
const babel = require('babel-core');
```

**Expected behavior/code**
Babel is imported without errors, and usable thereafter.

**Babel Configuration (.babelrc, package.json, cli command)**
n/a

**Environment**
- Babel version(s): v6.26.3
- Node/npm version: Node 10/npm 5/yarn
- OS: OSX 10.12.6
- Monorepo: lerna + yarn workspaces
- How you are using Babel: Bundled using webpack, run in browser

**Possible Solution**
This is due to a regression in the 'debug' package, in which the "node" path is taken even though we're running in a browser. It happens in babel-core 6.26.3 (and most likely also 7.x). It used to work fine in 6.26.0.

There is a PR to fix this: visionmedia/debug#563

I suppose you wouldn't backport this into 6.x?

**Additional context/Screenshots**
n/a

**Comment by loganfsmyth** [comment]
Do you know what change introduced this issue? It's certainly worked in the past. Is this new on Webpack 4?

It certainly seems like something that should just be fixed in `debug`.

**Comment by tvooo** [comment]
I believe this was introduced with this PR, which updated `debug` to a version containing the regression: https://github.com/babel/babel/pull/6390

You are right, this should be fixed in`debug`; `debug` should then be upgraded in `babel-core`. It is most likely going to be fixed in `debug`s current major 3.x which should get into `babel-core` 7, but `babel-core` 6.x is still on `debug` 2.x. Would it be possible to update  to latest `debug` major in `babel-core` 6.x too? Hope that makes sense :)

**Comment by tvooo** [comment]
As this was fixed in `debug` and Babel 7 is now stable, I'm closing this issue.
