### ISSUE TITLE
Typescript preset does nothing in current REPL beta

### ISSUE THREAD

**Issue by simonbuchan** [babel/babel#8117]
## Bug Report

**Current Behavior**

The typescript preset in the repl since 7.0.0-beta.48 doesn't enable any plugins, leading to syntax errors on any typescript syntax.

**Input Code**
- [Working on beta.47](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYOwLgpgTgZghgYwgAgGIHt3IN4F9lA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.0.0-beta.47&envVersion=)
- [Broken on beta.48](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYOwLgpgTgZghgYwgAgGIHt3IN4F9lA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.0.0-beta.48&envVersion=)

Note the UI shows a version behind due to #6174 - is something still holding up #7039?

Searching for and enabling (the second?) `syntax-typescript` allows parsing again, so it's something about the preset, not the plugins being broken or something.

**Comment by loganfsmyth** [comment]
This is pending https://github.com/babel/website/issues/1666 because the filename is currently hard-coded to "repl", so the presets doesn't see it as a `.ts` file.

**Comment by loganfsmyth** [comment]
This was a change from https://github.com/babel/babel/pull/7955/files#diff-a31d321b4911bbbc31e1d19a726637c6R30 so that Babel differentiates `.js`, `.ts`, and `.tsx`.

**Comment by simonbuchan** [comment]
Alternative fix is to provide `allExtensions: true` in the preset (and presumably `isTSX: true` if `react` is provided, though wouldn't it already?)

#7955 seems a little odd to force this, since you could use `overrides` for the same behavior (though, obviously for more work)

**Comment by loganfsmyth** [comment]
We could, but the more we do stuff like that, the more the REPL diverges from what users would actually see in their own project, which I'd rather avoid.

What specifically makes that PR seem odd?

**Comment by loganfsmyth** [comment]
> Sorry, probably "surprising" is a better term?

Fair!

> I just didn't expect plugins to have the power to apply presets per file

Yeah, it's all relatively new, but where we're ending up is that presets are allowed to set configuration like that, but plugins don't have nearly as much access to that kind of thing.

**Comment by dusan-dragon** [comment]
@loganfsmyth 
Are you talking about https://babeljs.io/repl ?  I really have no clue how to enable typescript support there

**Comment by danez** [comment]
Closing as this is website related and there is already discussion in the linked PR.

**Comment by JLHwung** [comment]
It is now [fixed](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBCBcEHYFcC2AjAppAvBAjAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.7.3&externalPlugins=).
