### ISSUE TITLE
Add more labels in our READMEs

### ISSUE THREAD

**Issue by xtuc** [babel/babel#8118]
We now generate the READMEs of all our packages! It includes a link to the issues related to that package, for example see the [babel-preset-typescript/README.md](https://github.com/babel/babel/blob/master/packages/babel-preset-typescript/README.md).

We maintain a map of package -> label, here: https://github.com/babel/babel/blob/master/scripts/generators/readmes.js#L23-L35. It would be great to add more labels to it and even use the `spec: xx` labels (you can see all the labels [here](https://github.com/babel/babel/labels)).

**Comment by BeniCheni** [comment]
Hello, @xtuc, giving this "_good first issue_" a try to add more labels to [it](https://github.com/babel/babel/blob/master/scripts/generators/readmes.js#L23-L35). Hopefully, I could accomplish to return around quickly with a PR soon.

Simple question: what does the mentioned "_spec_" key-value pair mean in previous comment?
> even use the spec: xx labels

If there's a more dynamic way to adapt something called "_spec_", I'd like to learn about that to handle labels for the READMEs. Happy to try the "_spec_" concept after learning it. 🙏

**Comment by xtuc** [comment]
Hey @BeniCheni, good news. The `spec: xx` labels are used to label issues with a specific JavaScript specification. For example: https://github.com/babel/babel/issues/8076 related to the Decorator specification.

I don't think we can do it dynamically, note that we don't have every specification as a labels.

You should be able to tell the what specification a plugin is based on the name or maybe in the README.

If it's not clear to you, I would be happy to chat on our Slack.

**Comment by BeniCheni** [comment]
Hi @xtuc, open a PR (#8144) for the packages in the `/package` directory and the "pkg: *" prefixed labels, which I was only able to map the relationship so far.

Happy to update more under advice from code review. Also still trying my best judgement to map the `spec: xx` labels to existing packages in the `./packages`.

Will do another PR, if I understand the mapping for "spec" labels correct, or I'd ask a simple, related question in #discussion channel of Babel Slack, if I run into any question.

🙏to reviewers for reviewing in advance.

**Comment by xtuc** [comment]
Thanks for your PR.

You can also ping me on slack (username: `sven`).
