### ISSUE TITLE
Incorrect code generated when running for-of after block-scoping

### ISSUE THREAD

**Issue by rubennorte** [babel/babel#8128]
## Bug Report

The following examples can be found in this gist: https://gist.github.com/rubennorte/f121ed807a1e0bff803ee62cb8783662

**Current Behavior**

Babel generates assignments to undeclared variables when specifying the for-of plugin after block-scoping:

```javascript
var _loop = function (_result) {
  _result = otherValue;
  fn(() => {
    _result;
  });
  //<<<<<<<<<<<< ASSIGNMENT TO UNDECLARED VARIABLE result
  result = _result;
};

for (var _iterator = results, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  var _result2 = _ref;

  _loop(_result2);
}
```

**Input Code**

```javascript
for (let result of results) {
  result = otherValue;
  fn(() => {
    result;
  });
}
```

**Expected behavior/code**

Something like:

```javascript
var _loop = function (result) {
  result = otherValue;
  fn(() => {
    result;
  });
};

for (var _iterator = results, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  _loop(_ref);
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["@babel/plugin-transform-block-scoping", {"loose": true}],
    ["@babel/plugin-transform-for-of", {"loose": true}]
  ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.48
- Node/npm version: Node 4.3.2 and Node v9.3.0
- OS: Linux
- How you are using Babel: `cli` and `core`

**Possible Solution**

Inverting the order of the plugins solves the issue, but it shouldn't matter (should it?).

**Additional context/Screenshots**

This seems to happen when there are re-assignments of the variable used to iterate over the values and a function that used it inside the loop. If the value is declared with `var` OR it isn't reassigned OR there isn't a function inside the loop, the issue doesn't happen.

**Edit**: when running Babel with the block-scoping plugin and then **again** with the for-of plugin, the generated code is correct, so it must be an issue traversing the AST with both transforms at the same time.

**Comment by nicolo-ribaudo** [comment]
Currently plugins order matter, but it isn't documented anywhere :pensive: 
Do you want to open a PR to add thid caveat to https://github.com/babel/website/blob/master/docs/plugin-transform-for-of.md, similarly to https://github.com/babel/website/blob/master/docs/plugin-proposal-decorators.md#note-compatibility-with-babelplugin-proposal-class-properties?

**Comment by kzc** [comment]
This is actually a genuine bug in `transform-block-scoping`. 

The transformed AST is fine, but the internal variable bindings are no longer correct (as per https://github.com/babel/babel/issues/4130#issuecomment-245411113) which can cause subsequent plugin transforms to fail.

Given:

```
$ node_modules/.bin/babel -V
7.4.4 (@babel/core 7.4.5)
```
```
$ cat ex.js
"use strict";
for (let x of (() => [7])()) {
    x = "PASS";
    console.log((() => {
        return x;
    })());
}
```

Expected output when run:
```
$ cat ex.js | node
PASS
```
Shell shorthand to invoke the babel CLI:
```
$ B="node_modules/.bin/babel --no-babelrc --plugins"
```
Notice that when both plugins are applied serially within one babel process it generates incorrect code:
```
$ cat ex.js | $B @babel/transform-block-scoping,@babel/transform-for-of | node
[stdin]:32
      throw _iteratorError;
      ^
ReferenceError: x is not defined
```

But if JS is generated via `transform-block-scoping` and piped to a second babel process running `transform-for-of` with newly regenerated internal bindings it succeeds:

```
$ cat ex.js | $B @babel/transform-block-scoping | $B @babel/transform-for-of | node
PASS
```

Related issue: #10027
