### ISSUE TITLE
Safari TP has lower version then Safari 11 according to getLowestVersion

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/babel#8129]
Safari TP has lower version then Safari 11 according to getLowestVersion
https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/targets-parser.js#L37-L68

All unreleased and released version should be compared together and released version should be < the unreleased. Instead versions are compared with semver that throws when comparing tp and 11 that cause the issue.

**Comment by xtuc** [comment]
Thanks for the report, would you mind sending a PR?
