### ISSUE TITLE
Docs: change label link to only open issues?

### ISSUE THREAD

**Issue by hzoo** [babel/babel#8131]
> Kinda related to https://github.com/babel/babel/issues/8118

I noticed now that we generate the readme's to the website docs, the issues link points to all issues (open or closed). I'm not sure how useful that is so figured we should change it to only point to open issues?

This would be doing something like adding this query to the current url `+is%3Aopen` 

https://github.com/babel/babel/blob/9f4e2f81d8c1780ba435e880479427f45213421a/scripts/generators/readmes.js#L19

which you can test manually as well or even in the preview of the branch/PR.

make sense @xtuc? should be a good first issue if we want to do this (I believe so)

**Comment by xtuc** [comment]
Yes, that's ok to me. Thanks for the issue.

**Comment by alexzherdev** [comment]
Opened a PR with an update to the script and newly generated readmes.
