### ISSUE TITLE
babel 7 preset-env has extra targets

### ISSUE THREAD

**Issue by bugzpodder** [babel/babel#8134]
# v7 Regression

**Describe the regression**
When I target an environment for @babel/preset-env it ended up having extra targets

**Input Code**
https://github.com/bugzpodder/demo-babel-preset-env-async-issue

**Babel Configuration (.babelrc, package.json, cli command)**

```js
 "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current"
          },
	  "debug": true
        }
      ]
    ]
  }
```
I also tried .babelrc and babel.webpack.config.js

**Expected behavior/code**
Only target node

** Current behavior **
```
yarn run v1.6.0
$ node server.js
@babel/preset-env: `DEBUG` option

Using targets:
{
  "android": "4.4",
  "chrome": "49",
  "edge": "16",
  "firefox": "52",
  "ie": "11",
  "ios": "9.3",
  "node": "8.9.3",
  "safari": "10.1"
}

Using modules transform: commonjs

Using plugins:
  transform-template-literals { "android":"4.4", "ie":"11" }
  transform-literals { "android":"4.4", "firefox":"52", "ie":"11" }
```
In the docs, https://new.babeljs.io/docs/en/next/babel-preset-env.html#export-with-various-targets
it shows safari 10 only actually targets safari 10 and nothing else.  I tried this config as well and I got a list of things similar to above.

**Environment**
- Babel version(s): [v7.0.0-beta.49]
- Node/npm version: [e.g. Node 8.9.3]
- OS: [e.g. OSX 10]
- How you are using Babel: [`register`]

**Comment by bugzpodder** [comment]
So it doesn't repo in a clean docker container.  so it means babel is reading some configs from my disk that I don't know about?

**Comment by bugzpodder** [comment]
Looks like I have an errorneous ~/package.json that had browserslist...

**Comment by existentialism** [comment]
@bugzpodder ok to close?

**Comment by bugzpodder** [comment]
@existentialism I feel the behavior is a bit weird.  I have a package.json in my source code and that should be used.  I am not sure why babel is walking up the tree and finding the root package.json.
