### ISSUE TITLE
babel-node run files with unexpected extension without processing it

### ISSUE THREAD

**Issue by mokevnin** [babel/babel#8135]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

Today I spent about 3 hours trying to fix `unexpected token` for this run `babel-node bin/server`.

**Input Code**
- REPL or Repo link if applicable:

```js
// bin/server
import something from '...';
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

`babel-node` will stop execution with the message about an unexpected extension or at least will show a warning.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "current"
      }
    }],
    ["@babel/stage-0",
      {
        "decoratorsLegacy": true
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: node 10/npm 6
- OS: docker
- Monorepo no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by loganfsmyth** [comment]
What is an example of an unexpected extension? What should this warning say?

**Comment by mokevnin** [comment]
This happens with files without extension

**Comment by loganfsmyth** [comment]
Please give more information. There is not enough here to reproduce or understand the issue. Files without extensions are treated as `.js` files, that is Node's standard behavior, not just specific to `babel-node`.
