### ISSUE TITLE
spread-operator doesn't transform to ES5

### ISSUE THREAD

**Issue by dislido** [babel/babel#8136]
## Bug Report

**Current Behavior**
spread-operator doesn't transform to ES5 

```js
"use strict";

var _arr;

_arr = [1, 2, 3].map(function (e) {
  return Math.pow(e, 2);
}), Math === null || Math === void 0 ? void 0 : Math.max(..._arr);
```
**Input Code**
```js
[1, 2, 3].map(e => e ** 2) |> (arr => Math?.max(...arr))
```

**Expected behavior/code**
```js
"use strict";

var _arr;

_arr = [1, 2, 3].map(function (e) {
  return Math.pow(e, 2);
}), Math === null || Math === void 0 ? void 0 : Math.max.apply(Math, _arr);
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
const presetEnv = require('@babel/preset-env');
const presetStage0 = require('@babel/preset-stage-0');
{
  presets: [
    [presetEnv, { targets: { browsers: ['ie >= 9'] } }],
    [presetStage0, { decoratorsLegacy: true }],
  ],
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: Node 10.0.0/npm 5.6.0
- OS: Windows 7
- Monorepo yes
- How you are using Babel: `babel.transform`

**Possible Solution**

**Additional context/Screenshots**

**Comment by std4453** [comment]
Spread syntax is not included in `@babel/preset-env`, you need `@babel/plugin-proposal-object-rest-spread`, see [this](https://new.babeljs.io/docs/en/next/babel-plugin-proposal-object-rest-spread.html) for details.

**Comment by nicolo-ribaudo** [comment]
That is not object spread, it should work.

**Comment by existentialism** [comment]
@std4453 this is actually incorrect, @babel/preset-env _does_ support object-rest-spread as of https://github.com/babel/babel/pull/7658

**Comment by microbouji** [comment]
I'd like to give this a try if it's not urgent. It would be my first PR so it will probably take some time.

**Comment by std4453** [comment]
I've did some research and it turns out that `Math?.max(...args)` will output with spread syntax unchanged, might be of some help. My apologies for the previous mistake.
