### ISSUE TITLE
this in es6 object

### ISSUE THREAD

**Issue by gorodinskiy** [babel/babel#814]
```javascript
var A = {
    test: () => {this}
};
```

why is **this** in code above translated to **undefined** instead of pointing to object itself?

**Comment by sebmck** [comment]
Because you're using a fat arrow function and it infers to the outer `this`.

**Comment by sebmck** [comment]
Duplicate of #733 and babel/babelify#37.

**Comment by gorodinskiy** [comment]
I know about arrow functions, but wouldn't the «outer this» be object in this case?

**Comment by sebmck** [comment]
The outer this is `undefined`.

**Comment by gorodinskiy** [comment]
It depends on where do you execute function. I.e. outer this can be window object.

**Comment by sebmck** [comment]
Nope. In ES6 modules the top `this` is `undefined`.

**Comment by sebmck** [comment]
See #562.
