### ISSUE TITLE
Cannot transform class properties with "stage-2"

### ISSUE THREAD

**Issue by boringer** [babel/babel#8141]
## Bug Report

**Current Behavior**

```sh
Missing class properties transform.
  10 |     }
  11 | 
> 12 |     static propTypes = {};
     |     ^
  13 | 
  14 |     static defaultProps = {};
  15 | }
```

**Input Code**

```js
class App extends React.Component {
    static propTypes = {};

    static defaultProps = {};
}
```

**Expected behavior/code**

Can transform correctly.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
    "presets": [
        "env",
        "stage-2"
    ]
}
```

**Environment**

- Babel version(s): 6.26.3
- Node/npm version: Node 10.3.0, NPM 6.1.0
- OS: macOS 10.13.5
- How you are using Babel: with Parcel

**Possible Solution**

I tried to add `plugins`:

```json
{
    "presets": [
        "env",
        "stage-2"
    ],
    "plugins": [
        "transform-class-properties"
    ]
}
```

Then it works well.

**Comment by nicolo-ribaudo** [comment]
We are tracking it at https://github.com/babel/babel/issues/8052
