### ISSUE TITLE
Determine if site is using Babel

### ISSUE THREAD

**Issue by acconrad** [babel/babel#8147]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I spoke with @hzoo and one thing we realized is that it's currently very difficult to determine if a site is using Babel or not.

**Describe the solution you'd like**
I see two solutions:

1. **Prepend the AST to have a `__babelVersion` global variable**. This is the most intuitive and simple solution. Simply make this string variable the first thing to output to the AST so that someone can go into the console of their browser and type `__babelVersion` to get something like `7.0.0-beta49`. **Drawbacks:** bloating the AST and adding a global variable is not exactly desirable.
2. **Create a plugin for a version string**. This fits into the more traditional model of "everything is a plugin first" approach and sort of gates this as a feature. There is also no global variable so it's still searchable via something like BigQuery without having to pollute the global scope. **Drawbacks:** plugins require opt-in (unless we auto-include this plugin along with `babel-core`) and it's really only useful for the Babel team. It won't be nearly as transparent to the end user for their own debugging purposes, and isn't nearly as easy for our own purposes to determine if Babel is in use.

**Describe alternatives you've considered**
Currently you can determine Babel through some convoluted mechanisms of searching for particular strings in the outputted code.

**Teachability, Documentation, Adoption, Migration Strategy**
As mentioned above, for end users, solution 1 is as simple as typing out `__babelVersion` into the console. For solution 2, it's more about being able to grep in the output for a babel version string so people can see it is in use. Nothing really too complicated here.

**Comment by hzoo** [comment]
Example of checking the syntax with Google BigQuery: https://twitter.com/sebmck/status/911336494824132608 (current way).

My other suggestions
- License comment like `@license babel` which won't get removed by a minifier
- Directive like `"use babel"`
- Just a string "babel v7.0.0" etc

And for implementation we can either auto add it in something like `babel-loader` or `@babel/cli` vs. `@babel/core`, make a plugin and include it in preset-env; many different options.

Future: opt-in to debug info, analytics on proposal plugins, etc.

**Comment by loganfsmyth** [comment]
I think the hardest part of this is that without an opt-in, we don't know which file to add it to, and adding it to _every_ file doesn't seem ideal, but if it's opt-in I imagine most people wouldn't bother.

**Comment by hzoo** [comment]
I don't think it matters as long as we do it once? Or we do it with babel-loader as an entry. We just need it once so it could be a `if (check) { print }` type of thing

**Comment by loganfsmyth** [comment]
The hard part is defining what "once" is qualified with. 

* If an application is built with 10 entry points in Webpack, the comment might well need to be in each one if each one is a separate application.
* If you use `babel-cli`, files are just processed in alphabetical order, do we just put it in whichever file ends up at the start?

**Comment by loganfsmyth** [comment]
Injecting real code worries me because it's hard to detect and strip out if a user wanted to. Using a directive would be easier, but I still think it'd be annoying for most users since stripping directives is uncommon. Personally, if we wanted to do this, I think we'd have to inject a comment, even if it were just `// @babel-version v7.0.0-beta.49`.

That said, it's also hard because it's not clear what we're trying to measure. If I bundle a `node_module` build with one version of Babel, and then also use another version, should it report both/all versions?

**Comment by hzoo** [comment]
I don't think we need to go that far yet? The initial question was just a matter of knowing what website is using babel via a simple directive (doesn't even need a version). I don't think that there's anything we need to strip out there, and it's not printing the whole config or something.

**Comment by loganfsmyth** [comment]
> The initial question was just a matter of knowing what website is using babel via a simple directive

What counts as using Babel though? If they import a `node_module` that was compiled with Babel, does that count as using Babel? To me it seems like it shouldn't.

> I just suggested the directive since the comment would get removed from the minifier

I think that's part of my concern here. If a minifier can't remove something that tooling has injected, I'd personally be frustrated by that tool.

**Comment by acconrad** [comment]
Just checking in - did we reach some consensus here? Feels like we still have a bunch of unanswered questions, but I am eager to contribute.

**Comment by xtuc** [comment]
I'm not a fan of injecting specific code into the generated code and we'll likely have many duplicates on a single page. 

I just want to mention that GitHub has a great code analysis tool/team.
