### ISSUE TITLE
Import Export

### ISSUE THREAD

**Issue by nairihar** [babel/babel#8150]
Hi I have some issue, can you plese help to undestand the problem, and how can I resolve it.

I have two files

First
```javascript
import Promise from 'bluebird';
global.Promise = Promise;

import { redisClient } from './clients';
```

Second
```javascript
import redis from 'redis';
Promise.promisifyAll(redis.RedisClient.prototype);
```

I am getting error, 
"Promise.promisifyAll is not a function",
why second file executes first, and First file executes after Second ?

**Comment by nairihar** [comment]
Is babel moves all imports to top ?
Then how I can fix problems like this ?

**Comment by dnalborczyk** [comment]
@nairihar yes, es6 imports are hoisted.

I assume `bluebird` would be responsible for installing their Promise implementation onto the global object - they probably had a reason why not to do so.

anyhow, what you can do:

```javascript
// index.js
import './install'
import { redisClient } from './client'
```

```javascript
// install.js
import * as bluebird from 'bluebird'

global.Promise = bluebird
```


```javascript
// client.js
import redis from 'redis'

Promise.promisifyAll(redis.RedisClient.prototype)
```

**Comment by Andarist** [comment]
Closing because it got answered. Feel free to comment further though. Thanks @dnalborczyk for answering this!
