### ISSUE TITLE
babel-preset-env errors on spread operator

### ISSUE THREAD

**Issue by pronebird** [babel/babel#8151]
## Bug Report

**Current Behavior**
Spread operator is supported in node v8.9 from what I can tell, but babel fails to compile it.

That's the error output from babel:

```
SyntaxError: app/components/Accordion.js: Unexpected token (70:6)
  68 |       children,
  69 |       animationDuration: _animationDuration,
> 70 |       ...otherProps
     |       ^
  71 |     } = this.props;
  72 |     const containerStyles = [style];
  73 | 
error Command failed with exit code 1.
```

The piece where it errors:

```
    const {
      style: style,
      height: _height,
      children,
      animationDuration: _animationDuration,
      ...otherProps
    } = this.props;
```

The same code runs in electron CLI:

```
yarn run electron -i                                  
yarn run v1.7.0
$ /black-hole/node_modules/.bin/electron -i
> process.versions
{ http_parser: '2.7.0',
  node: '8.9.3',
  v8: '6.1.534.41',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2n',
  electron: '2.0.2',
  chrome: '61.0.3163.100' }
> var a = { ...{ a: 1 }, ...{ b: 2 } };
undefined
> a
{ a: 1, b: 2 }
> const { a: a2, ...rest } = a
undefined
> a2
1
> rest
{ b: 2 }
```

**Input Code**
- REPL or Repo link if applicable:
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBCELwQ3hAdCxIBcECMEC-AaZVCAI0wCY88BuAKCA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=react%2Cenv&prettier=false&targets=Electron-2&version=6.26.0&envVersion=1.6.2

**Expected behavior/code**

Expected to emit spread as is.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "env": {
    "electron": {
      "presets": [
        ["env", {
          "targets": { "electron": "2.0" },
          "useBuiltIns": true
        }], "react"
      ],
      "plugins": [
        "transform-class-properties",
        ["babel-plugin-transform-builtin-extend", { "globals": ["Error"] }]
      ]
    },
}
```

**Environment**
- Babel version(s): 6.26.3
- Node/npm version: 8.9.3
- OS: macOS
- Monorepo [e.g. yes/no/Lerna] no
- How you are using Babel: cli

Running with 

```
BABEL_ENV=electron yarn run babel app/ --copy-files --out-dir build
```

**Possible Solution**

Adding `transform-object-rest-spread` is a workaround.

**Additional context/Screenshots**

**Comment by pronebird** [comment]
I was told that this was resolved in babel 7

**Comment by liamfd** [comment]
If it helps anyone else, I was running into this issue even with the Babel 7 beta. In my case, it was specific to `webpack`/`babel-loader`, as `babel-node` worked fine. Upgrading from webpack 3 to 4 solved the issue, I'd make sure you're on the latest `babel-loader` as well.
