### ISSUE TITLE
Preset flow regression after version 7.0.0-beta.47

### ISSUE THREAD

**Issue by thealjey** [babel/babel#8157]
## Bug Report

**Current Behavior**
I am using `@babel/preset-flow` and the code below works with versions of the preset up to and including `7.0.0-beta.47`, the newer versions all result in a `Syntax Error: Unexpected token, expected ";" (1:8)`.

**Input Code**

```js
declare var process: { browser: boolean; };
```

**Expected behavior/code**
I expect it to transpile like before.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "env": {
    "development": {
      "presets": ["next/babel", "@babel/preset-flow"]
    },
    "production": {
      "presets": ["next/babel", "@babel/preset-flow"]
    }
  }
}
```

**Environment**
- Babel version(s): 7.0.0-beta.51
- Node/npm version: Node v10.4.1/npm 6.1.0
- OS: OSX 10.13.5
- Monorepo: no
- How you are using Babel: Next.js

**Comment by existentialism** [comment]
@thealjey you'll likely want to match the version of the flow preset with the one used in the `next/babel` preset (beta.42 I believe?), as it's a bad idea to mix beta versions.

**Comment by thealjey** [comment]
@existentialism wow, that totally makes sense. Thanks for the explanation!
