### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'babel' of undefined

### ISSUE THREAD

**Issue by AlbertRui** [babel/babel#8159]
Above all，some code segments in the configuration file of package.json is as follows:
`"scripts": {
    "dev": "WEBPACK_ENV=dev webpack-dev-server --port 8086 --inline",
    "dev_win": "set WEBPACK_ENV=dev && webpack-dev-server --port 8086 --inline",
    "dist": "WEBPACK_ENV=online webpack -p",
    "dist_win": "set WEBPACK_ENV=online && webpack -p"
  },
"dependencies": {
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.6.3",
    "rc-pagination": "^1.7.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-fileupload": "^2.4.0",
    "react-router": "^3.0.2",
    "sb-admin-2": "^3.3.8",
    "simditor": "^2.3.6"
  },
  "devDependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "github:jantimon/html-webpack-plugin",
    "jsx-loader": "^0.13.2",
    "node-sass": "^4.5.0",
    "sass-loader": "^5.0.1",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^4.8.3",
    "webpack-cli": "^3.0.4",
    "webpack-dev-server": "^3.1.4"
  }`
when I run 'npm run dev_win',the following error occurred(my webpack version is 4.x)
ERROR in ./src/index.jsx
Module build failed: TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (E:\WorkSpaces\Sublime\admin-fe\node_modules\babel-loader\lib\index.js:103:35)
 @ multi (webpack)-dev-server/client?http://localhost:8086 ./src/index.jsx

how can I fix this error? thanks!
Has anyone encountered this problem?

**Comment by existentialism** [comment]
@AlbertRui please fill out the issue template, we're going to need a lot more information to help you!

**Comment by xtuc** [comment]
I'm closing this because of the lack of issue template and activity since. Feel free to open a new one.
