### ISSUE TITLE
Async functions should be a transformer option

### ISSUE THREAD

**Issue by dallonf** [babel/babel#816]
From the [FAQ](http://babeljs.io/docs/faq/#toggleable-transformers):

> With babel **every single** transformation can be turned off.

However, currently async functions (that is, `async`/`await`) seem to be enabled only by the `experimental: true` flag, along with every other experimental feature. In my use case, I'd like to use async functions (preferably with the [bluebirdCoroutines](http://babeljs.io/docs/usage/transformers/#bluebird-coroutines) option), but I don't really want all the other experimental features. It seems odd that this isn't an `es7.*` option, along with all the other [experimental features](http://babeljs.io/docs/usage/transformers/#es7-experimental-).

**Comment by jquense** [comment]
You can use the whitelist or blacklist options to pick the specific transformers you want to use. In your case perhaps you want to blacklist all the experimental transformers except async functions.

**Comment by dallonf** [comment]
What is the transformer name for async functions? It isn't listed in the docs [in the place I would expect](http://babeljs.io/docs/usage/transformers/#es7-experimental-).

**Comment by jquense** [comment]
Its seems to be  under Other as `regenerator`

**Comment by sebmck** [comment]
> However, currently async functions (that is, async/await) seem to be enabled only by the experimental: true flag, along with every other experimental feature. In my use case, I'd like to use async functions (preferably with the bluebirdCoroutines option), but I don't really want all the other experimental features. 

Just don't use the other experimental features then?
