### ISSUE TITLE
babel-preset env does not compile getter setter on object

### ISSUE THREAD

**Issue by NathanGrimaud** [babel/babel#8160]
## Bug Report

**Current Behavior**
It looks like babel-preset env (version ^1.7.0) does not compile getters / setter when used on objects.

**Input Code**
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBA7gJ3AcxgXhgbwFAEhkCmsUAFAJQ4xUy4JECuCYMArANzbUwC-ANJzQhEYpMPQC2FAVygALAJYQAdAH1YGMeI65u2XdmAAbAIYQIMZCBAATSheGkpXWgyYwAbNJ4ChxEpqcaOUVVdRgxQ0MBXW4gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

**Expected behavior/code**
The output code should be the same for objects and classes.

**Comment by loganfsmyth** [comment]
I don't think there is anything we can compile it to. If an environment doesn't support the syntax, it's unlikely that it would support `Object.defineProperty` either.

**Comment by NathanGrimaud** [comment]
Hello :) 
My issue was not about an environment doesn't support the syntax, but the closure-compiler that does not. I was just a bit surprised that both class and object doesn't compile the same way ;) 
Nevermind i will find an other way.

**Comment by nicolo-ribaudo** [comment]
Closing, since it's not possible to compile accessors down to es3 and now closure compiler hopefully supports es5 syntax.
