### ISSUE TITLE
Config validation regression?

### ISSUE THREAD

**Issue by Crashthatch** [babel/babel#8167]
I've just updated to babel 7.0.0-beta.51 (from 7.0.0-beta.49) and I'm now getting an error when I try to build with webpack: 

```Error: [BABEL] /<SNIP>/src/testEnvironment.ts: Invalid Option: 'l' is not a valid value for 'targets.0'. (While processing: \"/<SNIP>/node_modules/@babel/preset-env/lib/index.js\")
    at semverifyTarget (/<SNIP>/node_modules/@babel/preset-env/lib/targets-parser.js:148:11)
...more stack trace omitted
```

I've traced it down to my config being: 
```
presets: [
    ['@babel/preset-env', { "targets": "last 2 versions, ie 11", "modules": false }]
]
```

rather than:
```
presets: [
    ['@babel/preset-env', { "targets": {"browsers": "last 2 versions, ie 11"}, "modules": false }]
]
```

Presumably this failure is a result of the new validation introduced here: https://github.com/babel/babel/pull/8031 by @sun1x 

Does this mean that my previous config was always invalid and was previously failing silently / being ignored, or is this a valid config that should validate correctly in the new version (ie. new version incorrectly fails on a valid config)?

**Comment by hzoo** [comment]
https://github.com/babel/babel/issues/7445, yeah targets should take an object 👍

**Comment by Crashthatch** [comment]
Ok, thanks. Well done to @sun1x who added the validator. You've uncovered an unnoticed bug that's been in my code for months!
