### ISSUE TITLE
babel-plugin-external-helpers break on locally linked packages

### ISSUE THREAD

**Issue by JohannesMerz** [babel/babel#8168]
## Bug Report

**Current Behavior**

If you have multiple packages locally linked together (like with lerna for example) the babel-plugin-external-helpers package (and babel-plugin-external-helpers-2, i tried both with the same results) break. 

It always results in a `ReferenceError: babelHelpers is not defined`. 

My best guess is that it looses some references as the linked module doesn't have access to the parent module.

I tried following attempts to fix the issue without success:

- move all babel releated node_modules out of the packages in a parent directory so both modules use the same modules
- when hard cp&p the child module instead of linking it the issue goes away, but thats not a valid solution as we need those links to work.

**Input Code**

- Repo: https://github.com/JohannesMerz/babel-helper-error

Instructions to reproduce are in the readme of the repository.

**Expected behavior/code**

babelHelpers are found correctly.

**Babel Configuration (.babelrc, package.json, cli command)**

It comes down to having two modules, one linked into the other. 

```
├── lerna.json
├── package.json
├── packages
│   ├── app
│   │   ├── node_modules
│   │   ├── package.json
│   │   └── src
│   └── es6-package // this module gets linked into packages/app
│       ├── dist
│       ├── node_modules
│       ├── package.json
│       ├── rollup.config.js
│       └── src
```

- babel config for both modules

```json
{
  "presets": [
    [ "env", {
      "targets": {
        "browsers": "> 2%"
      },
      "modules": false
    }]
  ], 
  "plugins": [
    "external-helpers"
  ],
  "env": {
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }]
      ]
    }
  }
}
```

- parent package.json:

```js
{
  "name": "app",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "babel-core": "^6.26.3",
    "babel-jest": "^23.0.1",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "es6-package": "^1.0.0", // this is the locally linked package!
    "jest": "^23.1.0"
  },
  "scripts": {
    "test": "jest"
  }
}
```

- linked module package.json

```json
{
  "name": "es6-package",
  "version": "1.0.0",
  "main": "dist/index.js",
  "license": "MIT",
  "dependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "rollup": "^0.60.4",
    "rollup-plugin-babel": "^3.0.4"
  },
  "scripts": {
    "build": "rollup -c",
    "prepublish": "npm run build"
  },
  "files": [
    "dist"
  ],
  "module": "dist/index.es6.js",
  "jsnext:main": "dist/index.es6.js"
}
```

**Environment**
- Babel version(s): 6.26.3
- Node/yarn version: Node v9.11.1/yarn 1.7.0
- OS:  OSX 10.13.5
- Monorepo Lerna
- How you are using Babel: `rollup`, `babel-jest`

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![screen shot 2018-06-14 at 14 16 04](https://user-images.githubusercontent.com/11529353/41411553-92e02666-6fdd-11e8-95b8-148998df392f.png)

**Comment by loganfsmyth** [comment]
You haven't stated where your config file is, but if it's a `babel.config.js`, they apply across all files that are passed to Babel, so it may be that Jest is running the transforms on files in `es6-package` which may be undesirable. One thing you can do is insert `test: "src/"` in the top-level of your Babel configuration, which will specifically limit the scope of the plugins to files inside `src`. If the config is at the root, you'd need to pass the appropriate relative path.
