### ISSUE TITLE
Make file name extensions configurable

### ISSUE THREAD

**Issue by cburgdorf** [babel/babel#817]
I'm trying to use babel with Angular 2. I'm aware I won't be able to use AtScript for now but that doesn't worry me much. The way I approach it is that I pick the the raw ES6 build of Angular2 so that I should be able to use `import` all required modules.

Here comes the problem though. All the source files of Angular2 have a `.es6` file name extension. However, `import`s don't name the `.es6` part explicitly, they just look like this: `export * from './directives';`. But then the file is called `directives.es6` which doesn't seem to be a problem for traceur. Unfortunately it seems to be a problem for babel.

So, my question is: Is it possible to make the file name extensions configureable?

**Comment by sebmck** [comment]
6to5 doesn't support any specific extensions, it just transpiles whatever you throw at it. Where are you having difficulties importing it, node, browser etc?

**Comment by cburgdorf** [comment]
Interesting. The error may be somewhere in between then.

You can see that this import works:

https://github.com/cburgdorf/ng2-app/blob/2003f5bdde46f3b4ee45cc8eae1199329f88cb9f/src/app.js#L6

But then those do not:

https://github.com/cburgdorf/ng2-app/blob/2003f5bdde46f3b4ee45cc8eae1199329f88cb9f/angular2/angular2.es6#L1-L3

They work as soon as you add `.es6` to the import statement

**Comment by sebmck** [comment]
Try [specifying a custom extension](https://github.com/cburgdorf/ng2-app/blob/2003f5bdde46f3b4ee45cc8eae1199329f88cb9f/gulpfile.js).

**Comment by cburgdorf** [comment]
Thanks for the pointer. Still it doesn't seem to the trick even if I set `extensions` to `['.es6', '.js']`. It still can't find the module and still works if I explicitly add the `.es6` to the import statement :/

**Comment by sebmck** [comment]
Fixed it. Change

```javascript
bundler = watchify(browserify(config.entryFile, _.extend({ debug: true }, watchify.args)));
```

to

```javascript
bundler = watchify(browserify(config.entryFile, _.extend({ debug: true, extensions: [".es6"] }, watchify.args)));
```

Also you might want to upgrade to `babelify` because I'm not porting changes/fixes to the old 6to5 version.

**Comment by cburgdorf** [comment]
Ah, damn it. When I tried it, I changed it at the very top `var to5ify = require('6to5ify').configure({ extensions: [".js", ".es6"] });`.

Your change seems to do the trick. Still running in lots of (unrelated) problems now. Let's see if I can get an Angular2 setup running with babel. Closing here, thanks for your help!

**Comment by sebmck** [comment]
No problem! Let me know if you run into anymore problems.
