### ISSUE TITLE
TypeScript abstract classes break decorators, abstract keyword remains in compiled code

### ISSUE THREAD

**Issue by AlexanderOMara** [babel/babel#8172]
Bug report.

I wasn't sure if I should open a new bug or not, but I previously created [a bug report about how Babel was unable to compile decorators on TypeScript abstract classes](https://github.com/babel/babel/issues/7837). Since that update has been released, today I tried it out, and while it now compiles the code, it doesn't quite work due to it leaving the `abstract` keyword in the compiled code.

### Input Code
[GitHub Gist with all code](https://gist.github.com/AlexanderOMara/9301d66ac9f147a1940432f835318fbb).

```js
function decorate() {
	return (Class: Function) => {
		console.log(Class);
	};
}

@decorate()
abstract class Test extends Object {
	constructor() {
		super();
	}
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
	"presets": [
		["@babel/preset-env", {
			"modules": "commonjs",
			"targets": {
				"node": "10"
			}
		}],
		["@babel/preset-typescript"]
	],
	"plugins": [
		["@babel/plugin-proposal-decorators", {
			"legacy": true
		}]
	]
}
```

### Expected Behavior
Expect this code to compile to valid code successfully, like it does when using the official TypeScript compiler.

### Current Behavior

Attempting to run the code produces a syntax error:

```
$ node index.js
.../index.js:11
let Test = (_dec = decorate(), _dec(_class = abstract class Test extends Object {
                                             ^^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
```

### Possible Solution
N/A

### Context
Just trying to use decorators on abstract classes, which should be possible in TypeScript.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.51
| node             | v10.4.0
| npm              | 6.1.0
| Operating System | macOS 10.13.5

**Comment by xtuc** [comment]
ping @babel/typescript

**Comment by calebj0seph** [comment]
Seems to happen when using decorators on any of the methods of the abstract class too, even if there are no decorators on the class itself.

**Comment by rhyek** [comment]
Any workaround for this?

**Comment by nicolo-ribaudo** [comment]
You can rewrite your code like this:
```js
@decorator
abstract class My class {}

// ->

let MyClass = decorator(abstract class MyClass {});
```

**Comment by akonyer** [comment]
I am having the same issue. All abstract classes are not working.

Everything works fine using the following libraries:

    "@babel/plugin-syntax-dynamic-import": "7.0.0",
    "@babel/preset-env": "7.1.5",
    "@babel/preset-react": "7.0.0",
    "@babel/core": "7.2.2",
    "@babel/preset-typescript": "7.1.0",
    "@babel/plugin-proposal-decorators": "7.1.2",
    "@babel/plugin-proposal-class-properties": "7.1.0",

But updating certain ones seems to break it. I.e. upgrading @babel/preset-react to 7.2.0 makes the issue show up. So anyone struggling with this issue should be able to work around this using the versions above for now.

**Comment by akonyer** [comment]
I am having the same issue. All abstract classes are not working.

Everything works fine using the following libraries:

"@babel/plugin-syntax-dynamic-import": "7.0.0",
"@babel/preset-env": "7.1.5",
"@babel/preset-react": "7.0.0",
"@babel/core": "7.2.2",
"@babel/preset-typescript": "7.1.0",
"@babel/plugin-proposal-decorators": "7.1.2",
"@babel/plugin-proposal-class-properties": "7.1.0",

But updating certain ones seems to break it. I.e. upgrading @babel/preset-env to 7.2.0 makes the issue show up. So anyone struggling with this issue should be able to work around this using the versions above for now.

**Comment by nicolo-ribaudo** [comment]
Does it work if you use `@babel/plugin-transform-typescript` instead of the preset? (Try placing it before or after the decorators plugin)

The problem here is that TypeScript should run before decorators.

**Comment by akonyer** [comment]
Perfect! That is exactly what I needed.

Not sure why it was working before without that plugin, but happy to be able to keep this up to date again.

Thank you so much.
