### ISSUE TITLE
Cannot run https://babeljs.io/repl/ on IE11

### ISSUE THREAD

**Issue by paiboonpa** [babel/babel#8174]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
Enter https://babeljs.io/repl/ with IE11. It will show "An error occurred while loading Babel :("

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
Can load up the editor just like in Chrome/Edge

I'm running IE11 on Windows 10 Home

**Comment by xtuc** [comment]
@babel-bot move to babel/website
