### ISSUE TITLE
'with' and 'eval' compile without warning, yet fail to run

### ISSUE THREAD

**Issue by manvalls** [babel/babel#818]
When building an in-browser javascript console `with` and `eval` come in handy. These two aren't allowed in strict mode though, as a result we get fake successful compilations which fail to run no matter what browser. At least a warning would be much appreciated. Allowing non strict es6 code would make me happy :)

**Comment by sebmck** [comment]
It'd require telling the parser to parse in strict mode which would be a breaking change. I'd been meaning to do this for 4.x but completely forgot because I wasn't expecting to have had to change the name so soon. I'll investigate to see if I can do it in a minor.

**Comment by eventualbuddha** [comment]
Adding warnings for these is certainly a good idea. Using them, especially `with`, is a terrible, terrible one though :wink:

**Comment by sebmck** [comment]
As of 4.2.0 the parser now parses in strict mode by default and I've added a warning for `eval();` usage. This will probably break stuff but the code wouldn't run in a proper strict mode environment anyway.

Note to anyone finding this: If you blacklist the `useStrict` transformer then your code wont be parsed in strict mode and all the strict mode validation tests will be disabled.

**Comment by manvalls** [comment]
I know `with` and `eval` are evil, but they've got their use cases, e.g Google Chrome's javascript console uses both. The blacklist thing together with the warnings seems ok to me, feel free to close this, thanks!

**Comment by sebmck** [comment]
Great, thanks!
