### ISSUE TITLE
babel/parser: augment tokenization via parser plugins or brute-force cloning?

### ISSUE THREAD

**Issue by GerHobbelt** [babel/babel#8180]
### **Is your feature request related to a problem?**

I am using / intend to use babel to parse, validate and transform JS code written in 'action code blocks' in JISON grammar files. JISON (a grammar generator like old-skool `GNU bison` 😁 ) recognizes special variables in the action code such as `$1` and `@​1` to represent grammar-specific values. Currently these variable formats are expected: `$$`, `$1`, `$name`, `@​$`, `@​1`, `@​name`, `#​1`, `#​name`, `#​ID​#` and the advanced-use 'negative index reference' variables `$-1` and `@​-1`, which introduce another tokenization challenge. 😁

Of course `1`, `name` and `ID` can be any number or identifier name. 

The problem is that vanilla babel/parser doesn't recognize any of these except the `$`-prefixed ones. :cry:

The toolchain this is part of looks like this: 

```
jison-grammar-parse --> 
  loop over action set: foreach( 
    babel/parse --> 
    transform jison vars and functions (yyerror(), YYCONTINUE et al)
    hoist `import` statements from jison `%code` sections
  ) -->
  the usual babel ES* transforms (babel plugins as we know them today) --> 
  prettier/print
```

### **Describe the solution you'd like**

I wonder if the parser can be augmented with a plugin system which would replace/augment `readToken`, `readWord`, et al, though I do admit it's not as simple as that as I have [a patched babel running](https://github.com/GerHobbelt/babel) and a [few tugs & tweaks](https://github.com/GerHobbelt/babel/commits/patch-jison-var-tokenization) in other member functions were needed to make this co-exist with `@@​iterator` and friends.

I wonder if brighter minds than me can see this working (at speed = with minimal or no performance loss) via a parser-plugin mechanism?

Another way I *can* imagine is to turn `babel/parser` into a facade, which loads a `babel/parser-vanilla` or `babel/parser-your-patched-alt`. In other words: the parser *becomes* a plugin itself: one can go and patch babel/parser any way they want/need, then register/alias it into `babel/parser` so that the entire babel foodchain imports/requires this patched parser everywhere `@​babel/parser` is imported in the code. That approach at least would have zero performance cost at run-time; anyone with a custom parser will have to track the babel/parser development and make sure their patches/API stay in sync. 
Which is a big win compared to today, as it would mean only loading a single (patched) parser at least. (*now* I have to go through the entire dep-chain and make sure my forked=patched babel is loaded by everyone; with the parser being a plugin like that, this wouldn't need to be done anymore, reducing maintenance overhead for augmented/patched parsers 😄 )

### **Describe alternatives you've considered**

The current alternative is what I do now: forking babel to kingdom come. :laugh: This is currently doable thanks to scoped npm packages, as this alternative means either carrying multiple parsers around (heavy page load!) or moving everything that depends on the patched babel/parser into the same npm scope range (see `@​gerhobbelt/babel-***` packages: that's taking a 12 gage sawed-off shotgun and just... pull.)

Other alternatives I have considered are using a different toolchain, e.g. patched esprima+recast, followed by vanilla babel. It's nightmare and a double parser/compiler load, as the jison-specific code rewrites can be done using custom babel ast-walker plugins, which babel already provides an API for.
I've tried to mix babel and recast, but then that's still loading two engines for the same purpose: when you consider the jison features in the code as being yet another set of language features, everything in babel except the tokenization phase already provides for these.

**I guess the bottom line is this feature request: allow using non-standard babel/parsers, feeding the entire babel toolchain.**

#### Migration

If you want no migration pain, one way would be to implement the second idea: babel/parser as facade. Then have @​babel/parser always load the default babel parser, userland code can register an alternative parser they created from scratch or cloned off babel/parser and from that point onward babel uses the register parser.

This would make migration simple: anyone not using a custom parser gets exactly the same thing as they got before, no fuss, while the parser customizers have a double parser load: vanilla + patched. That bit can be solved by having rollup or eqv. build processes strip off the default parser code; that burden lies with the ones who inject a patched/alternative parser, if they want minimal page load cost.

#### Teachability, Documentation, Adoption

Not much to it I suppose. Anyone who wants to write a parser might benefit from some internals' documentation, but in the end it always RTFC if you're going to augment/patch something.
Anyone who does *not* need this type of functionality is not bothered by it as babel would always load the default 'vanilla' parser anyway, so for anyone else, nothing changes.

**Comment by xtuc** [comment]
Extending Babylon is not possible, see http://babeljs.io/docs/en/next/babel-parser.html#will-the-babel-parser-support-a-plugin-system.

**Comment by GerHobbelt** [comment]
Got it. That works for me, swapping out the parser via `parserOpts.parser`. Case closed. 😄 

(I'll have a look later if I can strip out the regular parser, but that's secondary now. First to get this stuff working.)
