### ISSUE TITLE
Recent betas don't create output full directory hierarchy with --out-dir

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#8182]
## Bug Report / Regression

Reported via https://github.com/twbs/bootstrap/pull/26658#issuecomment-397739198

**Current Behavior**
```
babel src --out-dir other/nested/dir
```
will attempt to create `dir` and throw if `other/nested` doesn't already exist.

**Expected behavior/code**

It should create all parent directories of the output directory. We should probably just replace `outputDestFolder` with `mkdirp`.

**Where did this come from**

This is a regression from the refactoring in https://github.com/babel/babel/pull/7929/files#diff-f93fbf6dce06b5cbf6cc65f5f7dac101L86 that essentially exposed an edge case that was already present but unlikely.

In that PR, I made the code _always_ call `outputDestFolder`, where before it was only called if there were `0` files found to write to the output.

The issue is that where the logic for writing _files_ uses `mkdirp` semantics, `outputDestFolder` uses `mkdir` semantics (no `-p`).

So essentially that PR takes a bug that would previously only have happened if there were no files found, and makes it happen all the time.

**Comment by himanish-star** [comment]
Hey @loganfsmyth, I would like to take up this issue. May I?

**Comment by loganfsmyth** [comment]
@himanish-star Go for it!
