### ISSUE TITLE
Issue with `only` after beta 44 on Windows

### ISSUE THREAD

**Issue by XhmikosR** [babel/babel#8184]
# v7 Regression

**Describe the regression**
After beta 44 (>beta44), `only` doesn't transpile the files. Removing `only` works like it does up until beta 44.

**Babel Configuration `.babelrc.js`**

```js
{
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        loose: true,
        modules: false,
        exclude: ['transform-typeof-symbol']
      }
    ]
  ],
  plugins: [
   'transform-es2015-modules-strip',
   '@babel/proposal-object-rest-spread'
  ].filter(Boolean)
};

}
```

**Expected behavior/code**
The input files should be transpiled.

**Environment**
- Babel version(s): v7.0.0-beta.51

  ```
  "@babel/core": "7.0.0-beta.51",
  "@babel/preset-env": "7.0.0-beta.51",
  "babel-plugin-transform-es2015-modules-strip": "^0.1.1",
  "gulp-babel": "8.0.0-beta.2",
  ```

- Node/npm version: 10.4.1, npm 6
- OS: Windows 10 / 7
- Monorepo: no
- How you are using Babel: gulp

I can't share the source, so here's my folder structure:

```
-.babelrc.js
  gulpfile.js
  --gulp\{config,tasks}
  --scripts\
  ----vendor\
```

I specify the `only` option in `gulp/config.js` like this:

```js
babelOnly: [
    './scripts/vendor/bootstrap/*.js',
    './scripts/*.js'
],
```

and use it in my gulp scripts task like this:

```js
function build(bundle) {
    return gulp.src(bundle.src)
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(babel({
            only: config.babelOnly
        }))
        .pipe(concat(bundle.destName))
        .pipe(gulp.dest(config.destDir))
        .pipe(browsersync.stream());
}

gulp.task('scripts', (done) => {
    const tasks = config.bundles.map((bundle) => {
        return build(bundle);
    });

    es.merge(tasks).on('end', done);
});
```

Now, this works fine up until beta 44. Any version after that doesn't transpile the files I have specified with `only`.

I might be missing something from the recent changes, but going back to beta 44 everything works again.

Thanks in advance for any help!

**Comment by vipcxj** [comment]
The same issue, but there is no problem on mac os, but trigger issue on windows. Because of operation system?

**Comment by XhmikosR** [comment]
I can't try another OS so I don't know if it's OS-related.

@hzoo: have you thought about using AppVeyor for Windows CI?

**Comment by vipcxj** [comment]
I have debug into it. and found this issue maybe related to [issue 118](https://github.com/micromatch/micromatch/issues/118). And in the babel side. it maybe the side effect of changing from relative path to absolute path at recent update.

**Comment by XhmikosR** [comment]
@vipcxj: did you manage to make `only` work with some workaround? I tried using absolute paths, still the same.

**Comment by loganfsmyth** [comment]
I can take a look at this, but if someone can throw together a simple repository to reproduce, it'd make life much easier.

**Comment by XhmikosR** [comment]
@loganfsmyth: is there a gulp + babel boilerplate I can try using to make a repro repo for you?

**Comment by XhmikosR** [comment]
Also, this issue is quite dangerous because I don't get any error when building.

**Comment by loganfsmyth** [comment]
@XhmikosR The easiest is usually to use `@babel/cli` and skip Gulp. It seems unlikely that this is a Gulp-specific, but if that's the case it does complicate the reproduction steps.

**Comment by XhmikosR** [comment]
I'll see what I can do and ping you. I will try to make a repo with Gulp though, so that we meet the exact same conditions.

**Comment by XhmikosR** [comment]
@loganfsmyth: https://github.com/XhmikosR/babel-only-test

Install gulp, do `npm i` and then `gulp`. Notice how the _site/assets/js files are not transpiled, at least not for me on Windows with node 10.4.1. Going back to beta.44 works again.

**Comment by loganfsmyth** [comment]
We could also ditch generic string-based pattern matching in favor of our own specific whitelist, e.g. handle paths ending with `*` and `**/` and `*.extension` and such, then leave it up to people to use regexes for anything more complicated.

**Comment by Kovensky** [comment]
`*` is definitely _not_ a valid filename character on Windows, which is the only system that uses `\` as a separator. Fortunately, windows also accepts `/` as a path separator...

**Comment by loganfsmyth** [comment]
Alright, that's good to know about `*` at least. It supports special logic for `+` and `{}` and `()` and such too, which are allowed in Windows: https://www.npmjs.com/package/micromatch#matching-features

Maybe we can turn off the rest of the micromatch stuff and only allow `*`-based expansion matching?

**Comment by XhmikosR** [comment]
Just some notes

* `/` paths are not Windows valid. It works in Node.js because I guess they handle this themselves.
* `*` isn't allowed in Windows paths. In fact none of these is allowed: `\/:*?"<>|`

**Comment by Kovensky** [comment]
`/` paths are valid when they are processed by the shell or the standard C library. Only "super-absolute" paths that start with `\\?\` do not accept `/` as a separator.

**Comment by XhmikosR** [comment]
The rule of thumb is do not use `/` on Windows.

There is absolutely no reason for you guys to risk things. Just follow the rule.

For reference

```
C:\Users\XhmikosR\Desktop>mkdir foo/bar
The syntax of the command is incorrect.
```

**Comment by Kovensky** [comment]
That is a limitation of `command.com` / `cmd.exe`, not a windows thing. Node is not doing anything special when `/` paths work; it's `command.com` / `cmd.exe` that break it to support CP/M-style switches.

I'm not saying we're going to require `/` in paths but the assertion that `/` is invalid in paths on windows is wrong. It's a `cmd.exe` problem; it's valid anywhere else on windows.

**Comment by XhmikosR** [comment]
Thanks for the explanation, but either way, as long as the issue is fixed I personally don't really care what might work or not. `cmd` is the default shell as you already know.

**Comment by hzoo** [comment]
I believe we are going with 3 now: Disallow pattern matching entirely and treat strings as explicit paths.

https://github.com/babel/notes/blob/master/2018/2018-07/july-02.md#rc and ask to use a regex in a `.js` config file otherwise

**Comment by gengjiawen** [comment]
@hzoo Is there a hotfix to fix this issue ?

**Comment by hzoo** [comment]
Yeah, this was introduced due to https://github.com/babel/babel/pull/8038, but since this is a regression and don't have the time to properly implement ^, we can do a revert.

Sorry for the churn, didn't understand the upgrade and ecosystem affect.

**Comment by XhmikosR** [comment]
Closing this since #8281 has been merged.
