### ISSUE TITLE
Auxiliary code `if (typeof _ret === "object") {` is not attached with auxiliary code comment.

### ISSUE THREAD

**Issue by ikarienator** [babel/babel#819]
This code shows up when you return objects with shorthand object properties in it.

**Comment by sebmck** [comment]
Added as of 4.2.1. Just an FYI but `if (typeof _ret === "object") {` is only used when you're using `return` inside a block that has been wrapped in a closure to scope the contained let bindings that were used inside of another closure (if that makes any sense).
