### ISSUE TITLE
`exclude` is invalid when i set in .babelrc

### ISSUE THREAD

**Issue by stevennzhou** [babel/babel#8191]
Hi~Now I have a question that I use `Promise` in entry.js, but I wouldn't like `babel-preset-env` to help me polyfill it.Then I try to add `exclude` setting.Nothing is changed. Just like this.
```javascript
// .babelrc
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": ["last 2 versions", "safari >= 7"]
        },
        "debug": true,
        "exclude": ["es6.promise"]
      }
    ]
  ],
  "plugins": [
    "transform-vue-jsx",
    "transform-runtime",
    "transform-object-assign"
  ]
}
```
And my entry.js is:
```javascript
Promise.resolve().then(() => {
  console.log('hahha')
})
```
Could you help me solve this problem?
Thx~

**Comment by nicolo-ribaudo** [comment]
Is this still a problem in Babel 7?

**Comment by nicolo-ribaudo** [comment]
I'm closing this PR, since in the posted config polyfills (`useBuiltIns` option) aren't enabled.
