### ISSUE TITLE
Labels are not being treated properly when declared as Strings

### ISSUE THREAD

**Issue by MatthewHerbst** [babel/babel#8199]
## Bug Report
babel is removing expressions after labels that are declared as string identifiers within another expression. This causes unexpected behavior. Further, babel allows string-declared labels within an expression, but not outside of one.

**Current Behavior**
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEBkEMCMFMBtQGcAOsDGAuAUCUALAF0JSUxAHcqA6DAW0gFoBLAO0NgCdXJDmB7HvGr9OAc2D0mAJgBs04LOoAGYAGIkGRvBgJ4sACaMkhXrDqx2SbLjBQ4iSKwOhYADxSdYSJANbYAQUxQAEYAbhs8ABV8ZiRQADNIZnh4wnx-AFcxfFBmQgByeMhkWHM2MXgAT1AAN0h4ZhdoL0gAa1BCfk78WFAdB1tE0QAKfUI80ABeUGUwyYAeUPnmAGpVgEpQAG8h0FAW2HbQAIi8AF9IsBi4xOTUnqycvMLi0vLWSpr6xpd0QT4rEyfS6PT6AwQQwSo3Gkxmc0Wyzy6y2uzw-3-7DYwJOZzAlyGAAVOPw0JxqncUmluv86CgUrAhgUAEIFYLhK6gAAGIS5rg8Xh8fjy8TY_04XnQhApBhJKDQBmwIwAwuyNhEhlyCgARAp826QdDoWAoDguSBvH5Nfq6eAAGke2Vy-SKoEyrHQ-kgnE63QseQSL2QGUy8GajLwACVYGJvQZ9D4HTz9aKPaJJdKarLSQqlTq2aF1ZyABL8CigACSoE4Tjy7G66VubFAnn4Lgo-VyJUIVRQ3UwIyGN3iFAtoFY_Am6EgTom0BqAFEAMrgNgTDvpA62xjeRrsUAD7CYkwEI4GLjxGasWDl4tni8jIu9SDnzhIaiQeWWAwjAoBI0moUwQFAAVMAIEFEWeAAOLMLU3hgq4EqiDgeAAKoejOOQTFEvawAuyGcMEABi9yGL6_IYJkHCgAUn5oM4BSgIItF3i-F4FtIoDemImQWFY1awAAjpkzBeAYDrQNRzGsBSIQtoKliENQQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=false&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=

**Expected behavior/code**
I would expected the code not to transpile, and to throw a SyntaxError.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["fast-async", {
      "runtimePattern": "directive"
    }],
    "transform-runtime",
    "syntax-trailing-function-commas",
    "transform-class-display-name",
    ["relay", { "schema": "../brigade-core/data/schema.json" }]
  ],
  "presets": [
    "es2015",
    "react",
    "stage-2"
  ]
}
```

**Environment**
- Babel version(s):
```js
    "babel-core": "^6.26.3",
    "babel-plugin-relay": "^1.6.0",
    "babel-plugin-syntax-trailing-function-commas": "^6.22.0",
    "babel-plugin-transform-class-display-name": "^0.0.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
```
- Node/npm version: Node 8.11.1, npm 6.1.0
- Monorepo: Lerna

**Possible Solution**
Properly fail with a SyntaxError. This would alert the dev that the did something wrong.

**Additional context/Screenshots**
If you read through the notes in the repl link I think it gives a pretty good sense of what is happening. Chrome dev tools does not allow this to pass, nor does Firefox:

```js
const h = new Headers();
h.append('Accept': '*/*'); // SyntaxError: missing ) after argument list[Learn More]
```

I would argue babel shouldn't either. And if for some reason it wants to, it should at least standardize how it handles labels. For example:

```js
// Does not work with babel settings above
'A': 1;

// Kind of works with babel settings above*
('A':1)
// * the label is identified, but then the expression after is dropped (which causes it to transpile when it should throw a SyntaxError)
```

**Comment by loganfsmyth** [comment]
> // This fails though it's a seemingly valid break to the label

These two `break` and `continue` examples are invalid because labels need to be direct parents, but in this case they are siblings. For example
```
G: for(let i = 0; i < 1; i++) {
  break G;
}
```
compiles fine.

> `(C: 1);`
> `('D': 1);`

These aren't LabelledStatements, they are Flowtype casts. In Babel 6 this is enabled by default as part of `preset-react`. In Babel 7 it has been split into a separate preset explicitly to make it harder to run into issues like this when you aren't expecting Flowtype to be enabled.

> headers.append('Accept': '*/*');

This is a bug in the Flowtype parser, but is already tracked in #6698.

**Comment by MatthewHerbst** [comment]
@loganfsmyth ah, thanks for the link. We initially suspected a Flow issue, but then we thought about it and didn't think we had Flow anywhere in our repo.

I'm guessing the handling of string labels within `()` and without being different also related to that bug?

We're excited for Babel 7 to come out of beta!

**Comment by loganfsmyth** [comment]
> I'm guessing the handling of string labels within () and without being different also related to that bug?

`(C: 1);` is valid Flowtype code. You can look at https://flow.org/en/docs/types/casting/

What it's saying is, cast the variable `C` to the type `1`, and your other example is casting the string `"D"` to the type `1`. That's not exactly something that is useful, but it is valid Flowtype code.

> didn't think we had Flow anywhere in our repo.

Yeah that's not uncommon with Babel 6. I'm glad it is separate from `preset-react` for `7.x`.

**Comment by loganfsmyth** [comment]
Is there anything left to track here? It seems like the only real issue was the one in https://github.com/babel/babel/issues/6698.

**Comment by MatthewHerbst** [comment]
I guess not. Thanks for the help!

**Comment by loganfsmyth** [comment]
No problem!
