### ISSUE TITLE
Star and local exports with duplicate names cause an error

### ISSUE THREAD

**Issue by jakzo** [babel/babel#8202]
## Bug Report

**Current Behavior**
When `export * from` and named `export` statements in the same file both export a value with the same name a runtime error is thrown.

This happens because Babel adds a getter to the `exports` variable when transpiling `export * from` but doesn't add a setter. The `export` statement simply assigns the property on `exports`. This is an error in strict mode, and would not overwrite the value even if it wasn't in strict mode.

**Input Code**
- [REPL link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgMyhAtnA5AOgPQCeWA3HHnnAAYE4BWAzpXKJLPVQIaUBQL08AYwgA7evA5wAvNhAkyFADwBaZlDRQgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

```js
// x.js
export * from './y';
export const a = 'x'; // <- throws error (but should export `a` as `'x'`)

// y.js
export const a = 'y';
```

**Expected behavior/code**
The local export should be exported instead of the star export with no error being thrown.

ECMA spec: http://www.ecma-international.org/ecma-262/6.0/#sec-getexportednames

Similar older issue: https://github.com/babel/babel/issues/3986

**Environment**
- Babel version(s): v6.x (probably affects v7.x too)

**Possible Solution**
Add a setter which removes the property descriptor and overwrites the value.

I think the helper comes from here:
https://github.com/babel/babel/blob/master/packages/babel-helper-module-transforms/src/index.js#L246
https://github.com/babel/babel/blob/6.x/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js#L37

**Comment by Kovensky** [comment]
There should not be a setter at all; the problem is that the star export helper is not filtering which exports to provide.

**Comment by jakzo** [comment]
@Kovensky Correct, though that would require some refactoring of the helper. Maybe something like moving star exports to the end of the file after all other exports have been added so it knows which to filter?

**Comment by nicolo-ribaudo** [comment]
Babel 7 keeps track of the exported bindings and filters them when using `export *`:
https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgMyhAtnA5AOgPQCeWA3HHnnAAYE4BWAzpXKJLPVQIaUBQL08AYwgA7evA5wAvNhAkyFADwBaZlDRQgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.56&envVersion=7.0.0-beta.56
