### ISSUE TITLE
preset-env needlessly transforms generator functions for Firefox 52

### ISSUE THREAD

**Issue by stasm** [babel/babel#8204]
## Bug Report

**Current Behavior**
Generator functions are transformed using the `regeneratorRuntime` when Firefox is set to version 52. This is incorrect; Firefox 52 supports generators.

**Input Code**
- [REPL with preset-env set to Firefox 52](https://babeljs.io/repl/#?babili=false&browsers=Firefox%2052&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAKkQcwKZgBQEpEDeAUIogJ4wYA2AJogIwDcRAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)
- [REPL with preset-env set to Firefox 53](https://babeljs.io/repl/#?babili=false&browsers=Firefox%2053&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAKkQcwKZgBQEpEDeAUIogJ4wYA2AJogIwDcRAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

```js
function * gen() {
  yield 1;
}
```

**Expected behavior/code**
No transformation should happen.

**Environment**
- Babel version(s): v6.26.0, v7.0.0-beta51
- How you are using Babel: REPL

**Additional context/Screenshots**
At first I thought this was a but in `compat-table`. I checked the data there and it says that generators are supported since [Firefox 27](https://github.com/kangax/compat-table/blob/fcaa9e9cfe1c53de12dae4ddaa5dcb7a3ab3f6bd/data-es6.js#L3806). According to MDN, it's actually [Firefox 26](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*#Browser_compatibility).

I think this might be related, or possible the root cause, of #8086, which I filed a few weeks ago.

**Comment by stasm** [comment]
Oh, I think I just found the reason:

https://github.com/babel/babel/blob/9283efaeb7a8c5b505b19332c3407dc44c668777/packages/babel-preset-env/data/plugins.json#L198-L207

I ran `npm run build-data` but `53` persists. Where does it come from?

**Comment by existentialism** [comment]
@stasm our data is generated from compat-table:
https://kangax.github.io/compat-table/es6/#test-generators, and resolves to v53 since 52 doesn't pass a couple tests.

**Comment by nicolo-ribaudo** [comment]
Closing per https://github.com/babel/babel/issues/8204#issuecomment-398815244
