### ISSUE TITLE
Missing quotes?

### ISSUE THREAD

**Issue by hemanth** [babel/babel#821]
```js
export default {
  'bind' (value, f) {},
  'null' () {},
  'for' () {},
  'return' () {}
}
```

Gets converted to:

```js
"use strict";

module.exports = {
  bind: function bind(value, f) {},
  "null": function _null() {},
  "for": function _for() {},
  "return": function _return() {}
};
```

Not the missing quotes for `bind`

**Comment by sebmck** [comment]
Yes, this is because the quotes around `bind` aren't necessary as it's not a reserved word. Blacklist the `es3.propertyLiterals` transformer if you don't want this behaviour.

**Comment by hemanth** [comment]
Ah, was suspecting that. Thanks.
