### ISSUE TITLE
TypeScript: Typed template literal syntax issue

### ISSUE THREAD

**Issue by kachkaev** [babel/babel#8216]
## Bug report / Feature Request

With TypeScript 2.9.2 and `styled-components` 3.3.3, it is possible to declare a typed template literal the following way:
 
```ts
const Item = styled.div<{
  selected?: boolean;
}>`
  color: ${p => p.selected ? 'red' : 'black' };
`;
```

This is parsed and linted by TypeScript well (e.g. writing something like `p => p.xyz` causes a TS error).

When the same code is parsed with babel 7 & `babel-preset-typescript@7.0.0-beta.51`, the following syntax error shows up:

```
SyntaxError: /path/to/file.tsx: Unexpected token, expected "," (42:10)
const Item = styled.div<{
  selected?: boolean;
          ^
}>`
```

This situation has created a pretty hard-to-investigate situation for me in a Next.js project. VSCode and `yarn lint` did not report any any problems, but the app was not building.

~~~Meanwhile, this workaround is possible:~~~

```ts
interface ItemProps {
  selected?: boolean;
};
const Item = styled.div<ItemProps>`
  color: ${p => p.selected ? 'red' : 'black' };
`;
```


↑ this transpiles, but resulting code is wrong. Something like:

```js
var Item = __WEBPACK_IMPORTED_MODULE_3_styled_components___default.div.div < ItemProps > "...".concat(function (p) {...
```

Because `ItemProps` was not supposed to be there at all, we get ` ReferenceError: ItemProps is not defined` 😱 

---
It'd be great if syntax parsing by babel could be improved when it comes to typed template literals.

**Comment by kachkaev** [comment]
This seems to be an issue only when a field in the interface is optional (followed by `?`). After it is removed, transpilation works:

```ts
const Item = styled.div<{
  selected: boolean;
}>`
  color: ${p => p.selected ? 'red' : 'black' };
`;
```

**Comment by kachkaev** [comment]
Great! Sorry that I failed to find those. Feel free to close this issue if you think it's a duplicate or we can close it once #7754 is merged / new babel version released.

**Comment by existentialism** [comment]
@kachkaev no need to apologize! let's close this and keep the conversations together :)
