### ISSUE TITLE
Babel 7 runtime causing issues with GRPC

### ISSUE THREAD

**Issue by majelbstoat** [babel/babel#8221]
## Bug Report

Using babel-loader causes an error with GRPC where identical code using ts-loader does not. I can't be certain it's the runtime, but the error looks suspicious.

```
 (node:121) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_getCoreRepresentation' of undefined
     at handleError (/usr/src/service/node_modules/grpc/src/server.js:64:36)
     at sendUnaryData (/usr/src/service/node_modules/grpc/src/server.js:597:9)
     at Service._callee3$ (/usr/src/service/dist/bundle.js:1146:17)
     at tryCatch (/usr/src/service/node_modules/regenerator-runtime/runtime.js:62:40)
     at Generator.invoke [as _invoke] (/usr/src/service/node_modules/regenerator-runtime/runtime.js:296:22)
     at Generator.prototype.(anonymous function) [as next] (/usr/src/service/node_modules/regenerator-runtime/runtime.js:114:21)
     at step (/usr/src/service/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
     at _next (/usr/src/service/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
```

This is triggered by returning a simple `Error()` from a GRPC server handler. The code compiles with tsc, and is loaded correctly with ts-loader.

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc
```js
{
  presets: ['@babel/env', '@babel/typescript'],
  plugins: [
    '@babel/proposal-class-properties',
    '@babel/proposal-object-rest-spread',
    '@babel/plugin-transform-runtime',
  ],
}
```

tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "lib": ["es2015", "es2016"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "dist/",
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext",
    "typeRoots": ["./node_modules/@types", "./lib/@types", "./app/@types"]
  }
}
```

Relevant package.json:
```json
{
    "@babel/cli": "7.0.0-beta.51",
    "@babel/core": "7.0.0-beta.51",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.51",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.51",
    "@babel/plugin-transform-runtime": "7.0.0-beta.51",
    "@babel/preset-env": "7.0.0-beta.51",
    "@babel/preset-typescript": "7.0.0-beta.51",
    "@babel/runtime": "7.0.0-beta.51",
    "grpc": "1.12.4"
}
```

**Comment by loganfsmyth** [comment]
The error seems likely to be whatever user code is at

```
     at Service._callee3$ (/usr/src/service/dist/bundle.js:1146:17)
```
so we don't have enough to go on. The only way https://github.com/grpc/grpc-node/blob/3fc29c46e77ebab59739d6d048dafa6d2ca514ea/packages/grpc-native-core/src/server.js#L64 would be throwing that error is if https://github.com/grpc/grpc-node/blob/3fc29c46e77ebab59739d6d048dafa6d2ca514ea/packages/grpc-native-core/src/server.js#L62 assigned it to null, so it sounds like something is triggering an error that has a `metadata` property, but has a value of `undefined`.

**Comment by loganfsmyth** [comment]
Ah that makes sense then. 

Babel's implementation's of experimental features aims to track the spec, rather that behave identically to Typescript, so that causes the distinction here.

In Babel 7, `metadata?: Metadata` is logically identical to `metadata?: Metadata = undefined`, meaning that even though `this.metadata = m` will be skipped, the property will still be `undefined` and will pass a `.hasOwnProperty` check.
