### ISSUE TITLE
ignore options not working

### ISSUE THREAD

**Issue by tw0517tw** [babel/babel#8224]
## Bug Report

**Current Behavior**

Running `babel src -d lib --ignore __tests__` not ignoring files in `__tests__` folder.

**Input Code**

See https://github.com/tw0517tw/babel-ignore for reproducing repository.

**Expected behavior/code**

Not to compile `src/__tests__/index.spec.js` to `lib/__tests__/index.spec.js`.

**Babel Configuration (.babelrc, package.json, cli command)**

None

**Environment**
- Babel version(s): v7.0.0-beta.51
- Node/npm version: Node 8 / Node 10, Yarn 1.5.1 / Yarn 1.3.2
- OS: Travis CI and Appveyor
- Monorepo: No
- How you are using Babel: cli

**Additional context/Screenshots**

See this Repo: https://github.com/tw0517tw/babel-ignore and the failing CI results.
https://ci.appveyor.com/project/tw0517tw/babel-ignore
https://travis-ci.org/tw0517tw/babel-ignore/

**Comment by loganfsmyth** [comment]
You'll need to ignore `src/__tests__` specifically. Your logic as-is would ignore a `__tests__` that was a sibling of `src`.

**Comment by tw0517tw** [comment]
Thanks @loganfsmyth ,

I tried `src/__tests__` and it's good (https://github.com/tw0517tw/babel-ignore/pull/3). 
But usually we have many other folders under `src` so I tried `src/**/__tests__` but it fails on Windows (https://github.com/tw0517tw/babel-ignore/pull/2).

**Comment by loganfsmyth** [comment]
Yeah, `ignore` and `only` and such are totally busted on Windows at the moment :( https://github.com/babel/babel/issues/8184

**Comment by loganfsmyth** [comment]
The Windows issue is resolved now, so I'm going to close this. If there are still issues feel free to re-open though.
