### ISSUE TITLE
Add envinfo to ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by tabrindle** [babel/babel#8227]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Babel gets an incredible number of issues, and managing and triaging them takes a lot of people and time, especially when issues are missing critical environment or setup info. 

**Describe the solution you'd like**
I'd like to add [envinfo](https://www.npmjs.com/package/envinfo) to babel in some way to help facilitate developers to write better, more complete issues. envinfo can get all of your environment details quickly, all in one command. Like this example for React Native
```
  System:
    OS: macOS High Sierra 10.13
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 97.59 MB / 16.00 GB
    Shell: 5.4.2 - /usr/local/bin/zsh
  Binaries:
    Node: 8.11.0 - ~/.nvm/versions/node/v8.11.0/bin/node
    Yarn: 1.5.1 - ~/.yarn/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 11.0, macOS 10.13, tvOS 11.0, watchOS 4.0
    Android SDK:
      Build Tools: 27.0.3
      API Levels: 26
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 9.0/9A235 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.3.2 => 16.3.2
    react-native: 0.55.0 => 0.55.0
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
```

So far React Native (react-native info), Create React App (create-react-app --info), Expo (exp diagnostics), Webpack (webpack-cli info), Solidarity (solidarity report), styled-components, Jest, Apollo and Gatsby have all started using it.

**Describe alternatives you've considered**
There are a number of ways to implement this:

1. Use npx to call envinfo with a preconfigured preset, a command like `npx envinfo --preset jest` . Styled components also uses this strategy, generally because of the lack of a CLI. Not everyone has npx yet, some don't know about it, can sometimes be problematic. But mostly, it works and helps!
2. Integrate envinfo into the babel cli - generally preferable and means the command can be whitelabled, and already available to most using your library. Expo, Webpack, React Native all use this method. Means options are a little more customizable and controlled by your repo. 

**Teachability, Documentation, Adoption, Migration Strategy**
envinfo should be extremely easy to use and enforce in issue templates - and since development is ongoing, if you have ideas, I can always add new features!

**Comment by xtuc** [comment]
I don't want to force peoples to use an additional tool for submitting a bug report. 

I would prefer something in Babel/cli itself.

**Comment by tabrindle** [comment]
Normally I agree; It is worth considering that npx is preinstalled on node 8+ so for the most part it wouldn't require installing anything. 'npx envinfo' takes about 2 seconds to fetch.

**Comment by Pay0801590664** [comment]
https://www.npmjs.com/package/envinfo

**Comment by Pay0801590664** [comment]
https://www.npmjs.com/package/envinfo
