### ISSUE TITLE
Use Browserslist 4

### ISSUE THREAD

**Issue by ai** [babel/babel#8228]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Browserslist 4 with Node.js versions support was released

**Describe the solution you'd like**

1. Use Browserslist 4
2. Use Browserslist to load Node.js versions as well
3. If Babel config has `target`, do not use Browserslist config (even if `target` contains only Node.js)

**Describe alternatives you've considered**

We already discussed it with @yavorsky and few people in Twitter and GitHub

**Teachability, Documentation, Adoption, Migration Strategy**

We need to change `babel-preset-env` docs as well

**Comment by ZeeCoder** [comment]
I've just bumped into this one after upgrading to Babel7.
@babel/preset-env uses v3 still, and doesn't recognise my "node 8" query.

Are there any blockers apart from maybe lack of time / manpower? 
I'm happy to help out.

**Comment by ai** [comment]
@ZeeCoder I think it is lack of the time. We already agreed about `node X` queries with Babel team.

I think you can make PR.

**Comment by ZeeCoder** [comment]
Cool, I'll add a reminder to do so next week then.
I'm building, an internal package which takes care of building by using webpack babel and postcss, and it would be important to accept node 4.

Also, I might have to use the BROWSERSLIST env var, since in the same project dir I have different bundles with different env targets, which means I can't have a root browserslist file.

(Currently I'm just cd'ing in to the right folder, but I'm not sure if that's the right solution. 🤔)

**Comment by existentialism** [comment]
> Are there any blockers apart from maybe lack of time / manpower?

I have a branch with some initial work on this, and it's on my list of things to do after Babel 7 ships.

Just a couple things to think through regarding the `targets` option and cleaning that up now that we'll be able to accept queries for both browsers and node.

**Comment by ai** [comment]
> to do after Babel 7 ships

Should we add it to Babel 7?

**Comment by existentialism** [comment]
> Should we add it to Babel 7?

It's not a blocker for it, IMO, and can be added as a feature in a minor bump, since we should be able to add this in a non-breaking way.

**Comment by ai** [comment]
> add this in a non-breaking way.

There was the idea that we discussed with @yavorsky: if Babel finds any `target` in `.babelrc` it should ignore Browserslist even if `target` doesn’t contain browsers. So Babel should use only `target` or only Browserslist.

This behavior could be more explicit and flexible, that merging configs.

But this behavior is breaking change.

**Comment by ai** [comment]
@existentialism should we added Browserslist 4 in Babel 7 RC2?

**Comment by ai** [comment]
@existentialism if your PR is almost done, maybe I can send a help you to finish it?
