### ISSUE TITLE
@babel/node Cannot resolve module with --require

### ISSUE THREAD

**Issue by sanchitgn** [babel/babel#8229]
## Bug Report

**Current Behavior**
`@babel/node` cannot seem to resolve node modules, when using `--require` flag. Needed to [preload environment variables](https://github.com/motdotla/dotenv#preload) with `dotenv`

**Input Code**

`package.json`
```json
{
	"scripts": {
		"dev": "nodemon ./src/index.js --exec babel-node -r dotenv/config"
	}
}
```

```
# Sample .env
PORT=3000
NODE_ENV=development
```

Running `npm run dev` throws the following error

```
Error: Cannot find module '/Users/sanchit.nevgi/projects/test/dotenv/config'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sanchit.nevgi/projects/test/node_modules/@babel/node/lib/_babel-node.js:209:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

**Expected behavior/code**
The module resolution should work as expected

**Babel Configuration**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "9"
        }
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.51
- Node/npm version: node 9.4.0
- OS: OSX
- How you are using Babel: cli

**Comment by dnalborczyk** [comment]
works for me ...

```console
node -r dotenv/config ./node_modules/.bin/babel-node
```

or

```console
npx @babel/node -r dotenv/config
```

or

```console
node -r @babel/register -r dotenv/config
```

**Comment by MNITD** [comment]
@sanchitgn I have the same problem as you have, I found sush workaround https://github.com/motdotla/dotenv/issues/89#issuecomment-182147361

**Comment by jacogreyling** [comment]
In the above examples it requires you to add `import "@babel/polyfill";` to your index.js file which might not be ideal.

**Comment by HauntedSmores** [comment]
@dnalborczyk answer did not work for me. From the error message, its trying to find `dotenv/config` in your project folder, rather than the behavior displayed by native `node` command which is aware to check `node_modules` folder.

```
node -r dotenv/config your-server.js // Works
babel-node -r dotenv/config your-server.js // Does not work
```

Adding `node_modules` to the path to dotenv seems to work, but is not the syntax expected by native `node` command:
```
babel-node -r node_modules/dotenv/config your-server.js // Works
node -r node_modules/dotenv/config your-server.js // Does not work
```

This behavior should be consistent.

**Comment by tomasfrancisco** [comment]
If in monorepo, the workaround can become even more nasty.
```
babel-node -r ../../node_modules/dotenv/config your-server.js
```

**Comment by dteiml** [comment]
+1

**Comment by starkana** [comment]
How come this hasn't been patched yet? I still have to add node_modules to the path to make it work.
