### ISSUE TITLE
Generate less opinionated code

### ISSUE THREAD

**Issue by JedWatson** [babel/babel#823]
Given that one of the project goals for Babel is to generate source code that's familiar to the pre-transpiled code, there are some aspects that could be nicer (e.g when switching from `react-tools`)

Specifically, in addition to #694, code style changes like the space in `function ()` and line breaks in `React.createElement` statements really stuck out.

Not really a big issue but it feels opinionated, and would be nice if it could be avoided.

**Comment by sebmck** [comment]
It would require adding in edge cases for every single possible grammar production where whitespace will vary. Note the whitespace in the following examples:

```javascript
function foo() {}
function foo(){}
var foo = function() {};
var foo = function () {};
var foo = function(){};
```

This would complicate the code **significantly** and it's very hard to do without a [CST](https://en.wikipedia.org/wiki/Parse_tree) unless the tokens are directly found and compared which is bad for performance.

An approach similar to [recast](https://github.com/benjamn/recast) could be taken but it's very performance intensive and there are already issues with the code generator (on megabytes of Javascript, see #788) let alone adding even more by checking nodes for changes and using their original source and normalising indentation.

`jstransform` (which `react-tools` uses) modifies the source code and uses jumps to append/prepend the code. The added benefit is that it's extremely fast but the transformation code looks like shit and it's extremely hard to introduce bugs and you have to support every single node property when doing the transformation even if it's not related.

Marking this as wontfix as there are bigger fish to fry and the potential codebase complications aren't worth it.

**Comment by JedWatson** [comment]
Fair enough, thanks for the explanation!
