### ISSUE TITLE
`interopRequireDefault` required by windows absolute path

### ISSUE THREAD

**Issue by JunreyCen** [babel/babel#8231]
**Describe the regression**
When compiled esmodule to commonjs, i got `interopRequireDefault` required by windows absolute path instead of npm address

**Input Code**
```js
var _interopRequireDefault = require("D:\\develop\\FS\\plugins\\delta-meta-ts\\node_modules\\@babel\\runtime/helpers/builtin/es6/interopRequireDefault");
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [['@babel/env', {
      modules: 'commonjs'
  }]]
}
```

**Expected behavior/code**
```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
or
```js
var _interopRequireDefault = require("@babel/runtime/helpers/builtin/es6/interopRequireDefault");
```

**Environment**
- Babel version(s): [7.0.0-beta.47]
- Node/npm version: [Node 8/npm 6]
- OS: [Windows 7]
- How you are using Babel: [`gulp`]

**Comment by loganfsmyth** [comment]
As far as I know, there's no current code in Babel itself that would use an absolute path. Would you be able to provide a reproducible repository?
