### ISSUE TITLE
es6 class to es5

### ISSUE THREAD

**Issue by ariran5** [babel/babel#8232]
## Bug Report
hi
I found to not work correctly

if I transpilie this (es6 -> es5)

```js
class A {
  static B(){
    alert(1)
  }
}

new A.B()
```
it work, but it not work in browser.
console said to me `function is not a constructor`
http://jsfiddle.net/8ouqLr9d/23/

I check this here https://babeljs.io/repl/

**Comment by hzoo** [comment]
Thanks for the question!

If you have a static method, then you don't need to create an instance of it with `new`. So it's just `A.B()` which should work fine.

**Comment by ariran5** [comment]
But if I use babel `new A.B()` work!!!

**Comment by loganfsmyth** [comment]
@ariran5 Babel does its best to behave like real ES6 code, but there are always edge cases that we can't fully handle. This is one of them. A function created with method syntax can't be instantiated as a constructor.
