### ISSUE TITLE
[Feature Request] Support for 'self' keyword in classes which is more specific than 'this' keyword

### ISSUE THREAD

**Issue by devssh** [babel/babel#8233]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Using 'this' is confusing in classes as it could refer to the class or the current function in the class.
I have spent a lot of time writing code where there is an error and it turns out to be an oversight of the scope for 'this' when refactoring code to a function.

**Describe the solution you'd like**
The same solution provided by Scala which is to add a keyword called 'self'
So 'self.function1' refers to the class.function1 while 'this.function1' refers to the local scope of the function. 

**Describe alternatives you've considered**
a simple hack for this is to create a variable 'self' in every class and assign it to 'this' in the beginning, another solution would be to use 'class1.function1' instead of 'this.function1' but working in a team means that other people end up writing 'this.function1' leaving me to figure out the scope and this restricts readability

**Teachability, Documentation, Adoption, Migration Strategy**
Users will understand this if they have worked in languages like scala or if they do a quick search for the keyword

**Comment by loganfsmyth** [comment]
Since this doesn't appear to require new parser support, you could explore writing your own plugin to do this.

It's not something that I'd expect to land in the language though, and definitely not something Babel would implement without a language proposal.

**Comment by devssh** [comment]
Ya can you tell where I could suggest this as a language proposal for ES2018? I could only think of Babel as the best place to suggest this
