### ISSUE TITLE
What to use to run node script now?

### ISSUE THREAD

**Issue by dschinkel** [babel/babel#8234]
I don't want to use babel-node so with babel 7 how should my script look to run node .js files?

**Comment by loganfsmyth** [comment]
If you don't want to use `babel-node` to compile files on the fly, you can use `@babel/cli`'s `babel` command to compile your files first.

**Comment by dschinkel** [comment]
right.  I've been trying to find the right command for the cli..but no luck

**Comment by loganfsmyth** [comment]
What specifically doesn't work? The `babel` command will compile a file and either print it or save it, but not run it, so you'd save it to a script and run that with `node`.

**Comment by dschinkel** [comment]
well when I use `babel myscript.js` it's outputting my ES6 module as literal text instead of executing it.

**Comment by loganfsmyth** [comment]
If you want to execute the code, that is what `babel-node` is for. Why don't you want to use it?

**Comment by dschinkel** [comment]
yea I will I just figured there was a new way to do that in babel 7 but guess not.

**Comment by loganfsmyth** [comment]
The module is now called `@babel/node`, but the command is the same name.

**Comment by dschinkel** [comment]
yea got it working now thx
