### ISSUE TITLE
`logger.debug` causes "Unexpected token" error

### ISSUE THREAD

**Issue by mocheng** [babel/babel#8235]
# v7 Regression

**Describe the regression**

After migration to  v7.0.0-beta.51, most of features are OK except one case. The original code in one library is like this.

```
      logger.debug(`calling ${this.name} GET`, {path, query});
```

This code is transpiled into.
```
                logger.debug("calling ".concat(this.name, " GET"), {
                  path: path,
                  query: query
                }); 
```

When this code is referenced by another repo built with babel v7.0.0-beta.51. It fails with error message as below.

```
Module parse failed: Unexpected token (172:23)
You may need an appropriate loader to handle this file type.
|
|                   path: path,
|                   query: query
|                 });
|                 
```

**Input Code**

So, the input code is below

```js
                logger.debug("calling ".concat(this.name, " GET"), {
                  path: path,
                  query: query
                }); 
```

The `logger.debug` is basically a wrapper of `console.log`. It is interesting that replacing `logger.debug` with `console.log` fix the issue as below.

```js
                console.log("calling ".concat(this.name, " GET"), {
                  path: path,
                  query: query
                }); 
```

Or, I can just assign `logger` to another variable to fix it.

```js
                const l = logger;
                l.debug("calling ".concat(this.name, " GET"), {
                  path: path,
                  query: query
                }); 
```

It looks babel treats `logger` in some special way.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-env",
    "next/babel",
    [
      "@babel/preset-stage-0",
      {
        "decoratorsLegacy": true
      }
    ]
  ]
}
```

**Expected behavior/code**

It should build pass, because the syntax has no problem.

**Environment**
- Babel version(s): v7.0.0-beta.51
- Node/npm version: node v6.13.0; npm v5.6.0
- OS: 10.13.5
- How you are using Babel: webpack loader

**Comment by loganfsmyth** [comment]
Would you be able to put together an example repository? From what you've shown, it's not clear how I'd go about reproducing this issue. The snippets of code you've included all see to be valid. It seems more likely that it is something else in your build process that is causing this code to fail.
