### ISSUE TITLE
public properties is not defined in a class (es 8,9rd edition)

### ISSUE THREAD

**Issue by cybermerlin** [babel/babel#8240]
## Bug Report

**Current Behavior**
property is not defined in a prototype.

**Input Code**
- REPL or Repo link if applicable:

```js
class Some {
    prop1 = 123;
    prop2;
}
console.log(Some.prototype.prop1); // -> undefined
console.log(Reflect.ownKeys(Some.prototype)); 
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oAcBO9MEZoBeafAJgGYBudaCACgDcBKZASwDNp6AXACzYQAdH0gB5AO4A7AAq5MAU2w8AnvQDkOPPnXNm3foKFaCxaCyoBfVNYD0t4PCkR4IBUJDwA5vQDK8AFt3LR54VUVjeXxmGjA3ZXoEeEiwsJUIk2iaIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2017%2Cstage-2%2Cstage-3&prettier=true&targets=&version=6.26.0&envVersion=

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
That is the expected behavior. Public properties are not defined on the prototype, but on `this` at construction time.

e.g. 
```js
console.log(new Some().prop) // 123
```

**Comment by cybermerlin** [comment]
@nicolo-ribaudo typescript is to better (more correct) working.
