### ISSUE TITLE
[babel-register] doesn't transpile import syntax, "Unexpected token import" error

### ISSUE THREAD

**Issue by sw-yx** [babel/babel#8241]
## Bug Report

**Current Behavior**
Hello! I am trying to use the `import` syntax in node. I think `babel-register` should help me with that. However when I try running my node script it gives me the `SyntaxError: Unexpected token import` error as though `babel-register` isn't set up right.

**Input Code**
- REPL or Repo link if applicable: https://github.com/sw-yx/boring-SSG/tree/babelbugreport/test1

```js
// in index.js
require('ignore-styles');
const babelRegister = require('babel-register');

babelRegister({
  ignore: /\/(build|node_modules)\//,
  presets: ['react-app'],
});

const fs = require('fs');

fs.writeFileSync('output.html', require('./render').default);
```

```js
// in render.js
import React from 'react'; // immediately errors here
// rest of the file
```

**Expected behavior/code**

based on what i expected it should compile the `import` syntax for me in the background.

**Babel Configuration (.babelrc, package.json, cli command)**

none, the preset is set through babel-register

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] v6.3.2
- Node/npm version: [e.g. Node 8/npm 5] Node 8.5/npm 6.0
- OS: [e.g. OSX 10.13.4, Windows 10] OSX 10.12.6
- Monorepo [e.g. yes/no/Lerna] no
- How you are using Babel: [e.g. `cli`, `register`, `loader`] `register`

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/6764957/42126969-9dd7cfe6-7c5e-11e8-9b1c-a79b4db831ff.png)

**Comment by IzaGz** [comment]
i am seeing the same error tryed also babel-plugin-syntax-dynamic-import ,  babel-plugin-dynamic-import-node - no changes same error

**Comment by robbporto** [comment]
Check if you referencing correctly your folders in the `start` task. We had a similar problem and we fixed by changing this:

`node -r babel-register ./node_modules/.bin/webpack-dev-server --config ./config/webpack.config.dev.js  --hot --open --colors`

to this:

`node -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config ./config/webpack.config.dev.js  --hot --open --colors`

**Comment by sw-yx** [comment]
i am no longer working on this project, pretty much just gave up on making sense of babel 6 and 7 interop issues. so i am closing pls feel free to reopen and reference this if you need it

**Comment by brettz9** [comment]
It's working for me as long as I have the Babel plugin plugin-transform-modules-commonjs
