### ISSUE TITLE
Babylon doesn't parse trailing commas correctly for function call generics

### ISSUE THREAD

**Issue by vjeux** [babel/babel#8242]
## Bug Report

This was found because prettier outputs trailing comma and it no longer parses with babylon.

**Input Code**

```js
call<
  A,
  B,
>()
```

http://astexplorer.net/#/gist/dffec8c8a6f66e9fcc260ee76dd68119/5eb2048db26cff01ad2eda5cdac682a1079a54ff

**Current Behavior**
```js
Unexpected token (4:0)
```

**Expected behavior/code**
It parses. flow-0.72.0 parses it fine.

**Environment**
- Babel version(s): babylon7-7.0.0-beta.44

**Possible Solution**
Needs to accept trailing comma

**Comment by zertosh** [comment]
This has already been fixed. https://github.com/babel/babel/pull/7934

**Comment by vjeux** [comment]
@zertosh This PR adds support for `<>`, which appears to be working fine. What this issue is specifically about is trailing commas. I don't believe that trailing commas in this context are working. cc @samwgoldman

**Comment by zertosh** [comment]
@vjeux, I just tested (and confirmed) that trailing commas in type arguments work in 7.0.0-beta.51

**Comment by vjeux** [comment]
Thanks for double checking, so it is therefore on us to fix!
