### ISSUE TITLE
disable emojis in cli output

### ISSUE THREAD

**Issue by brainkim** [babel/babel#8243]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Emoji output is causing subtle bugs in my terminal.

**Describe the solution you'd like**
`🎉  Successfully compiled 11 files with Babel.` <- I want that 🎉  gone with a flag like `--no-emoji`

**Describe alternatives you've considered**
Being fun and chill. But I can't do it 😡.

**Teachability, Documentation, Adoption, Migration Strategy**
I dunno. Does babel have a man page?

**Comment by xtuc** [comment]
I would like to remove them, many terminal environment will have trouble displaying them (CI for example?).

maybe we can detect it using the TERM variable or something similar. Could you please add more information about your environment?

**Comment by brainkim** [comment]
This is in the regular terminal for OSX high sierra. I'm encountering a bug where when I try to repeat the previous command the cursor is off by however many emojis were in the output and I don't find out until I run the command again and get an error.

**Comment by brainkim** [comment]
It works when I strip my terminal of all emojis (yarn is acting like a dick and disregarding emoji false in .yarnrc) and pipe babel output to /dev/null. I sincerely do not understand why JavaScript™️ tools feel the desire to make their cli outputs memeable (oh god remember yeoman?) ![](https://i.stack.imgur.com/9VMFG.png)

**Comment by nicolo-ribaudo** [comment]
There is the irrational part of me which thinks that emoji are cool and we should add the `--no-emoji` flag, but probably we should just remove them if they cause problems.

**Comment by brainkim** [comment]
I think a `--no-emoji` flag is fine!

**Comment by jridgewell** [comment]
Removing it would probably be better. Even good terms break because of it.

**Comment by xtuc** [comment]
I would be against adding a new flag
