### ISSUE TITLE
toString method of custom class extending Array strips string line feed

### ISSUE THREAD

**Issue by Zorgatone** [babel/babel#8245]
## Bug Report

**Current Behavior**
With the ES6 example when extending Array and defining a toString method code in the browser I get the correct output, with the code transpiled by Babel I don't get the correct output (multiline string should be printed to the console).

**Input Code**
- REPL or Repo link if applicable:

```js
class MultiArray extends Array {

  constructor(x = 0, y = 0, fill) {
    if (![x, y].every((p1) => 'number' === typeof p1)) {
      throw new Error('Invalid params: ' + [x, y].map((p) => String(p)).join(', '));
    }

    super(x);
    
    if (undefined !== fill) {
      this.fill(fill);
    }

    this.length2 = y;

    for (let x1 = 0; x1 < x; x1++) {
      this[x1] = new Array(y);
    
      if (undefined !== fill) {
        this[x1].fill(fill);
      }
    }
  }

}

class Matrix extends MultiArray {

  constructor(rows = 0, columns = 0, fill = 0) {
    if ('number' !== typeof fill) {
      throw new Error('Invalid fill param');
    }

    super(rows, columns, fill);

    this.rows = rows;
    this.columns = columns;
  }

  toString() {
    return this.map((row) => row.join(', ')).join('\n');
  }

}

console.log((new Matrix(3, 4, 1)).toString()); // Expected multi-line string

```

Babel transpiled output code:
```js
'use strict';

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var MultiArray = function (_Array) {
  _inherits(MultiArray, _Array);

  function MultiArray() {
    var x = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;
    var y = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 0;
    var fill = arguments[2];

    _classCallCheck(this, MultiArray);

    if (![x, y].every(function (p1) {
      return 'number' === typeof p1;
    })) {
      throw new Error('Invalid params: ' + [x, y].map(function (p) {
        return String(p);
      }).join(', '));
    }

    var _this = _possibleConstructorReturn(this, _Array.call(this, x));

    if (undefined !== fill) {
      _this.fill(fill);
    }

    _this.length2 = y;

    for (var x1 = 0; x1 < x; x1++) {
      _this[x1] = new Array(y);

      if (undefined !== fill) {
        _this[x1].fill(fill);
      }
    }
    return _this;
  }

  return MultiArray;
}(Array);

var Matrix = function (_MultiArray) {
  _inherits(Matrix, _MultiArray);

  function Matrix() {
    var rows = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;
    var columns = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 0;
    var fill = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : 0;

    _classCallCheck(this, Matrix);

    if ('number' !== typeof fill) {
      throw new Error('Invalid fill param');
    }

    var _this2 = _possibleConstructorReturn(this, _MultiArray.call(this, rows, columns, fill));

    _this2.rows = rows;
    _this2.columns = columns;
    return _this2;
  }

  Matrix.prototype.toString = function toString() {
    return this.map(function (row) {
      return row.join(', ');
    }).join('\n');
  };

  return Matrix;
}(MultiArray);

console.log(new Matrix(3, 4, 1).toString()); // Expected multi-line string
```

**Expected behavior/code**
I expect this output to be printed (typing the non-transpiled ES6 code in the browser console works, doing the same with the babel-transpiled ES5 code doesn't):

```
1, 1, 1, 1
1, 1, 1, 1
1, 1, 1, 1
```

This is the single-line output that is printed instead:

`1,1,1,1,1,1,1,1,1,1,1,1`

**Babel Configuration (.babelrc, package.json, cli command)**
Default config of try babel website http://babeljs.io/repl with babel 6.x

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): 6.x (v6.26.0)
- Node/npm version: n/a
- OS: n/a
- Monorepo n/a
- How you are using Babel: website

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Zorgatone** [comment]
More precisely (after some testing), it looks like you cannot add custom methods when extending Array, and in this case the toString custom method is ignored and Array.prototype.toString is called instead.

I tried creating another custom method with a new name which is not existing on Array.prototype and when calling it it throws that it's not a function

**Comment by Zorgatone** [comment]
Not sure if it's a browser issue or Babel, because the ES6 syntax doesn't give this error

**Comment by nicolo-ribaudo** [comment]
Extending built-ins (like `Array`) is not supported in Babel 6.
It works in Babel 7 :tada: 

https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECyCuIAuBLAggJw2AntApgB5L4B2AJjJtngN4BQ900wA9qREhvMEqxgApC0ALzQADABpoeMVOgAzFCBABKaA2bMUC6AICEAbULScAXQB0-AG74MOAQIAOARnUiAfNADkpeAFsAIztvURExJBwnfFZdV1V1TS1mJAALDFYAd2hSfGyAUSx-AW8ASVJrMBAUcmgnMGx_CAAuH2gAamhjU0t_MCdHJ3cvAGUuFFIAc2cEiwArVgmS6W8EgG4mLQBfRmSIeGjBQlUN5M3tXQF4CnwlXNr9cMVlNQ1zrTSUCAslFQFftSnba7D6pL4WEBkSZpABMohkG3eCn4ekhSGghBc8PEawxWIAPBjcZj2u1Eu8UmCIMYXGZ4blstRcAIcCd3hToDo9NdyLcJvgHk8AeTkslPtTMZYAf8XmzRdAdslFQrGDt6KBIDBYGBxsIiCQKFrEKgmXQQWwOFweHxBBlMjA5NI2CAAhxsdIAdiRVouSU_EEQtBHhEojFdMK3vK0nacnloIUMoIyhUqjVnio6g0wP5VkDmGq9gc7AI7RAnawXf4OB7ZYixVSLKX4aW89BxRZna6HSwK12gQW26wxhgJtNvcwMPgkPAMKQ2w2-gMS1lhtA7fNFqRlj5Zgslt4ADqkXObNVqqp2JCOBlwHUjwgCADM0gALNI3KoLHxh6OBOtoAA9AB8aENEvACtA_jGigAC01S5NAnAjlM9BAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-beta.51&envVersion=7.0.0-beta.51
