### ISSUE TITLE
Change extensions of Babel source from .js to .fjs

### ISSUE THREAD

**Issue by justinfagnani** [babel/babel#8247]
## Bug Report

**Current Behavior**
Non-JavaScript syntax is used in .js files.

**Expected behavior/code**
.js files should contain standard JavaScript, or at least syntax actually proposed to TC39.

**Possible Solution**
Change extensions of Babel source from .js to .fjs

**Comment by jridgewell** [comment]
What nonstandard syntax do we use?

**Comment by nicolo-ribaudo** [comment]
I guess that he talks about flow? Flow expects by default to find type annotations in `.js` files: https://flow.org/en/docs/config/options/#toc-module-file-ext-string

**Comment by loganfsmyth** [comment]
As far as I can tell there's zero reason for us to do something like this? Using experimental syntax in `.js` files is extremely common in the community. A feature request like this really needs to elaborate the why something should be considered.

**Comment by nicolo-ribaudo** [comment]
`.js` is the default extension for flow. Also, code contining flow annotations uses `.js` in every other project.
