### ISSUE TITLE
New Flow typecasting/upcasting/typed-expression syntax and import type syntax

### ISSUE THREAD

**Issue by jeffmo** [babel/babel#825]
Just a heads up that we've recently landed support for two new syntactic features in Flow and we're shooting to announce them today or tomorrow.

The first new syntax is a typed-expression syntax that looks like this: `(<expr>: <typeannotation>)` (note that parens are required). This can go in any position that a regular expression can go.

Examples:
```javascript
class Base {}
class Child extends Base {}
var child: Child = new Child();
var base: Base = new Child(); // upcast

(child: Base); // upcast
(base: Child); // downcast -- valid syntax, but Flow will error as it does not allow downcasts
((base: any): Child); // work around Flow with escape hatch `any`
```

The second new syntactic feature is the import-type syntax which is a tiny extension to all existing forms of `ImportDeclaration`. It basically just allows for a new `type` keyword to sit immediately after the `import` keyword.

Examples:

ModuleA.js
```javascript
export class MyNamedClass {
  // ...
}

export default class MyDefaultClass {
  // ...
}
```

ModuleB.js
```javascript
import type {MyNamedClass} from "./ModuleA";
import type MyDefaultClass from "./ModuleA";

function takesAMyNamedClass(inst: MyNamedClass): void {}
function takesAMyDefaultClass(inst: MyDefaultClass): void {}
```

(For context: The details of why `import type` is important will go out with a blog post soon -- but the primary semantic distinction is that `import type` declarations should get stripped and have no runtime effects whereas regular `import` declarations do not get stripped because they have runtime effects)

We've just updated the react-tools `jsx` script as the source-of-truth for the transformation (EDIT: at `react-tools@0.13.0-beta.2` for now). Feel free to use it as a reference implementation. I know a lot of people prefer to use 6to5 though since it's a more holistic tool than just `jsx`

**Comment by jeffmo** [comment]
Correction (edited inline as well): The updated version of the `jsx` tool is available via the `react-tools@0.13.0-beta.2` version of react-tools on npm.

**Comment by jeffmo** [comment]
One more clarification: I mentioned `import type {MyNamedClass}` and `import type MyDefaultClass` but we also support the `import type * as Whatever from "MyModule";` variant of import as well.

(This is mostly just useful for people in the middle of converting a codebase from CommonJS-style `module.exports = Whatever` to ES6 modules)

**Comment by jeffmo** [comment]
Welp...@sebmck just pointed out that this is already done: https://github.com/babel/acorn-babel/issues/26

such fast. much ship.

**Comment by sebmck** [comment]
Passes all the `esprima-fb` tests :dancer:
