### ISSUE TITLE
About @babel/polyfill Document

### ISSUE THREAD

**Issue by GHLandy** [babel/babel#8251]
I'm learning babel for personal configuration recently, and I want more details about @babel/polyfill.
I'v seached it on <www.npmjs.com> which info me to <https://babeljs.io/docs/en/next/babel-polyfill>，but there is nothing.

When the missing document will be udpated?

**Comment by hzoo** [comment]
https://github.com/babel/website/pull/1678 wasn't merged correctly for some reason, it should definitely be there, so I just updated it.

**Comment by GHLandy** [comment]
Got it, thanks!
