### ISSUE TITLE
@babel/preset-env loading unneeded polyfill

### ISSUE THREAD

**Issue by brokenmass** [babel/babel#8253]
## Bug Report

**Current Behavior**
When using node 10.4.1 and the latest @babel/preset-env with targets `{node: 'current'}` the polyfill for `es6.array.sort` is used

**Expected behavior/code**
`es6.array.sort` polyfill should not be loaded as Array.sort is already supported in node.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    presets: [
      [
        '@babel/env',
        {
          targets: {
            node: 'current'
          },
          debug: true,
          modules: false,
          useBuiltIns: 'usage'
        }
      ]
    ]
  }
```

```bash
@babel/preset-env: `DEBUG` option

Using targets:
{
  "node": "10.4.1"
}

Using modules transform: false

Using plugins:
  proposal-async-generator-functions { "node":"10.4.1" }
  syntax-object-rest-spread { "node":"10.4.1" }
  proposal-unicode-property-regex { "node":"10.4.1" }

Using polyfills with `usage` option:

[/path/to/my/project/index.js] Added following polyfill:
  es6.array.sort { "node":"10.4.1" }
```
**Environment**
- Babel version(s): 7.0.0-beta.51
- Node/npm version: 10.4.1 / 6.1.0
- OS: 10.13.4
- Monorepo: No
- How you are using Babel:webpack babel-loader

**Possible Solution**
fix`packages/babel-preset-env/data/built-ins.json` compatibility map

**Comment by existentialism** [comment]
@brokenmass preset-env uses [compat-table](https://github.com/kangax/compat-table) for its data, which currently does not have node 10 mappings.

**Comment by brokenmass** [comment]
@existentialism well I don't think it's not node 10 specific. 
It applies to any `node > 0.10` I guess

**Comment by zloirock** [comment]
@brokenmass as you can see in `compat-table`, it was fixed only in v8 6.3. Latest node result in  `compat-table`  for node 8.10 which use v8 6.2. So feel free to add to `compat-table` node 10 results.

**Comment by bsuh** [comment]
built-ins.json doesn't have any key for node for es6.array.sort
https://github.com/babel/babel/blob/55295cc54553c8f8c0f688238c1397a2918e8fb6/packages/babel-preset-env/data/built-ins.json#L202

compat-table shows .prototype.sort is supported on node 4.
https://github.com/kangax/compat-table/blob/7cf30ce6410c12855539dd7151d5115a0518f36d/data-es6.js#L6444

**Comment by zloirock** [comment]
@bsuh your link to `compat-table` related `%TypedArray%.prototype.sort`. `Array.prototype.sort` tests / results placed in es5 table / data.
