### ISSUE TITLE
Call to regeneratorRuntime precedes the requiring of babel-polyfill

### ISSUE THREAD

**Issue by eranikid** [babel/babel#8258]
## Bug Report

**Current Behavior**
Upon transpiling a file of code with async function, babel generates the following line:
```js
var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(// ...
```
`regeneratorRuntime` is undefined by default, from my research I found that you need to add a `babel-polyfill` for it to be defined:

```js
import 'babel-polyfill';

async function test() {
  // ...
}
```
However in a transpiled code, call to `require('babel-polyfill');` goes after the call to `regeneratorRuntime`, thus `regeneratorRuntime` is still undefined. If I manually move `require('babel-polyfill');` to the top of the transpiled file, code works as expected.

**Input Code**
[Link to an example](https://github.com/Eranikid/babel-mcve)

**Expected behavior/code**
Call to `require('babel-polyfill');` in transpiled code precedes the first call to `regeneratorRuntime`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
"scripts": {
  "build": "babel ./ --ignore node_modules,dist -s -D -d dist --presets env"
}
```

**Environment**
- Babel version(s): `cli`: 6.26.0, `core`: 6.26.3
- Node/npm version: Node 8.11.3, npm 5.6.0
- OS: Windows 10

**Comment by Andarist** [comment]
This is somewhat hack-ish, but you should be able to trick this issue by separating this into 2 files like this:
```js
// entry.js
import 'babel-polyfill';
import './my-entry';
```

```js
// my-entry.js
async function test() {
  // ...
}
```
