### ISSUE TITLE
Re-export default?

### ISSUE THREAD

**Issue by jasonkuhrt** [babel/babel#826]
It appears that this is not possible:

```js
export windex from './windex'
```

But these are:
```js
export { default as windex } from './windex'
export * from './windex' // This will not do anything if windex only exports a `default`
```

I'm wondering if this is to-spec `JS2015` behaviour? I find this annoying because I have a case where many modules internally should act like `module.exports = foo` but the larger library should act like `exports.<name> = foo`.

**Comment by jasonkuhrt** [comment]
For details about `JS2015` exports see http://www.2ality.com/2014/09/es6-modules-final.html.

**Comment by fkling** [comment]
As far as I can tell, it's [spec compliant](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports).

```
ExportDeclaration :
    export * FromClause ;
    export ExportClause FromClause ;
    export ExportClause ;
    export VariableStatement
    export Declaration
    export default HoistableDeclaration[Default]
    export default ClassDeclaration[Default]
    export default [lookahead ∉ {function, class}] AssignmentExpression[In] ;

ExportClause :
    { }
    { ExportsList }
    { ExportsList , }

ExportsList :
    ExportSpecifier
    ExportsList , ExportSpecifier

ExportSpecifier :
    IdentifierName
    IdentifierName as IdentifierName
```

**Comment by jasonkuhrt** [comment]
I find it hard to believe that `export { default as windex } from './windex'` is the best we can get in a freshly minted spec. Are we sure sure sure about this?

Regarding the use-case, is there another solution/pattern someone can recommend?

**Comment by jasonkuhrt** [comment]
@rauschma since you wrote the excellent article I'm referencing if you could lend your brief thoughts I'd appreciate it.

**Comment by sebmck** [comment]
This is spec compliant. As @fkling pointed out, the grammar doesn't allow it.

**Comment by jasonkuhrt** [comment]
@sebmck Thanks. Sigh.

**Comment by aeosynth** [comment]
my pattern:

```
import foo from './foo'
import bar from './bar'
export default { foo, bar }
```

i agree that the spec should support this case. @jasonkuhrt you can bring this up in [es-discuss](https://mail.mozilla.org/listinfo/es-discuss)

**Comment by jasonkuhrt** [comment]
@aeosynth Thanks, did so.
