### ISSUE TITLE
GenericTypeAnnotation.id should allow QualifiedTypeIdentifier

### ISSUE THREAD

**Issue by burnnat** [babel/babel#8260]
## Bug Report

**Current Behavior**
Current `babel-types` [documentation for GenericTypeAnnotation](https://babeljs.io/docs/en/next/babel-types.html#generictypeannotation) indicates the `id` property is of type `Identifier` but in some parsed expressions it can also have type `QualifiedTypeIdentifier`.

**Input Code**
- See the [parsed AST](https://astexplorer.net/#/gist/e79570d7bcf37d607b354b43baea6353/9fd63768edce6c409dcc8fed083ab12c788aab55) for this example:

```js
interface Test {
  property: typeof Other.child.value;
}
```

**Expected behavior/code**
The documentation should specify `GenericTypeAnnotation.id` as having type `QualifiedTypeIdentifier | Identifier`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["flow"]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.51
- Node/npm version: 6.1.0
- OS: Windows 10]
- How you are using Babel: Node API

**Comment by existentialism** [comment]
Fixed by https://github.com/babel/babel/pull/9396
