### ISSUE TITLE
With the latest Beta51 version (which is automatically pulled in by another module).... traces, traces,...

### ISSUE THREAD

**Issue by richtera** [babel/babel#8263]
## Bug Report

**Current Behavior**
When I use @babel/types there are a bunch of validators that now output console.trace with messages like "The node type SpreadProperty has been renamed to SpreadElement". I get thousands of them and I am not sure how to get rid of them. The calling parent is "babel-plugin-transform-object-rest-spread"

**Input Code**
I am not doing anything special other than using a nextjs project which pulls this all in. I'll try to remove all my node_modules and start again, but this seems left over debugging code.

**Expected behavior/code**
Maybe one validation message like that or none should display.

**Babel Configuration (.babelrc, package.json, cli command)**

The babel config is auto generated by next.js

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] v7.0.0-beta.51
- Node/npm version: [e.g. Node 8/npm 5] 9.11.1
- OS: [e.g. OSX 10.13.4, Windows 10] Mac OS X 10.13.5 (17F77)
- Monorepo [e.g. yes/no/Lerna] no
- How you are using Babel: [e.g. `cli`, `register`, `loader`] webpack with next-babel-loader

**Possible Solution**

I think these messages were added to debug something but should probably not be in the production code.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
Can you show the auto-generated babel config and `package-lock.json`/`yarn.lock`?

**Comment by nicolo-ribaudo** [comment]
Beta packages should all be used with the same version, because we might have introduced breaking changes in the various betas. 😉

Babel 7 plugins will throw a nice error when they are used with the wrong babel/core version.
