### ISSUE TITLE
Patterns as rest arguments - unexpected token

### ISSUE THREAD

**Issue by ddivin-sc** [babel/babel#8269]
## Bug Report

**Current Behavior**
Babel didn't understand spread operator in function as argument

**Input Code**

```js
let f = (...[,,c]) => console.log(c); f('aa', 'bb', 'cc')
```

> This code works is fine in latest Chrome

**Expected behavior/code**
I'am expected return 'cc' in console, but BabelJS throw an error

```
repl: Unexpected token (1:12)
> 1 | let f = (...[,,c]) => console.log(c); f('aa', 'bb', 'cc')
    |             ^ 
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Comment by dnalborczyk** [comment]
> Babel didn't understand spread operator in function as argument

you probably mean `rest parameters`.

it doesn't seem to be limited to function args though.
```javascript
const [...[a]] = [1] // fails as well
```

**Comment by Andarist** [comment]
Interestingly this doesnt work in Chrome
```js
// Uncaught SyntaxError: `...` must be followed by an identifier in declaration contexts
var f = ({ a, ...{ c } }) => console.log(c)
f({ a: 'aa', c: 'cc' })
```

**Comment by nicolo-ribaudo** [comment]
Closing in favor of https://github.com/babel/babel/issues/8396
