### ISSUE TITLE
Uncaught ReferenceError: _extends is not defined

### ISSUE THREAD

**Issue by arnsa** [babel/babel#8270]
## Bug Report

**Current Behavior**
Hello everyone,

I've been googling for the whole day and I can't seem to find a solution to my issue. Here's the part I am struggling with: https://gist.github.com/arnsa/5c75fcd226bfdb6a52769a2ec1bfe017

So when webpack tries to compile this, I get this error: Uncaught ReferenceError: _extends is not defined

I checked the compiled code and I saw that there's no _extends defined in the output: https://gist.github.com/arnsa/9b3c19126482f210004701625e584b89

However, if I remove the import type... part, the code works perfectly and I can see _extends defined in the output. I assume it's something related to the spread operator? If yes, just so you know, I am using babel's transform-object-rest-spread v6 in my project. Also, I've been using spread operator all over my project and it worked perfectly.

P.S. I tried upgrading to babel v7, but that didn't solve my issue

**Input Code**

```js
// @flow

import React from 'react';
import { Form } from 'antd';
import type { ColProps } from 'antd';

type ComponentType = {
    input?: {},
    touched?: bool,
    children?: React$Node,
    label?: string,
    error?: string,
    hasFeedback?: bool,
    formItemLayout?: ColProps,
}

function makeField(Component: React$ComponentType<any>) {
    const FormItem = Form.Item;

    return ({
        input,
        touched,
        children,
        hasFeedback,
        label,
        error,
        formItemLayout,
        ...rest
    }: ComponentType) => {
        const hasError = touched && error;

        return (
            <FormItem
                label={ label }
                validateStatus={ hasError ? 'error' : 'success' }
                hasFeedback={ !!(hasFeedback && hasError) }
                help={ hasError }
                { ...formItemLayout }
            >
                <Component { ...input } { ...rest }>
                    { children }
                </Component>
            </FormItem>
        );
    };
}

export {
    makeField,
};

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc:
```js
{
  "presets": [
      "env",
      "react",
      "es2015",
      "flow"
  ],
  "plugins": [
    "transform-es2015-destructuring",
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-async-to-generator",
    ["import", { "libraryName": "antd", "style": true }]
  ],
  "env": {
    "development": {
      "compact": false
    }
  }
}
```

package.json:
```js
{
  "name": "admin-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "flow": "./node_modules/.bin/flow",
    "flow:coverage": "./node_modules/.bin/flow-coverage-report -i 'src/**/*.js' -t html -t json -t text --threshold 75",
    "build": "./node_modules/.bin/webpack --mode production",
    "dev:docker": "./node_modules/.bin/webpack --mode development --watch",
    "dev:local": "./node_modules/.bin/webpack-dev-server --mode development",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "antd": "^3.6.1",
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "file-loader": "^1.1.11",
    "formik": "^0.11.11",
    "iban": "0.0.10",
    "moment": "^2.22.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1",
    "url-loader": "^1.0.1",
    "validator": "^10.3.0",
    "yup": "^0.25.1"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-webpack": "^0.10.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-flowtype": "^2.49.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.9.1",
    "faker": "^4.1.0",
    "flow-bin": "^0.75.0",
    "flow-coverage-report": "^0.5.0",
    "html-webpack-plugin": "^3.2.0",
    "image-webpack-loader": "^4.3.1",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "less-vars-to-js": "^1.2.1",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.9.0",
    "optimize-css-assets-webpack-plugin": "^4.0.2",
    "sass-loader": "^7.0.2",
    "style-loader": "^0.21.0",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^4.4.1",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.3",
    "webpack-dashboard": "^2.0.0",
    "webpack-dev-server": "^3.1.4",
    "webpack-notifier": "^1.6.0"
  }
}
```

**Environment**
- Babel version(s): 6.26.3
- Node/npm version: node 8.11.3 / npm 6.1.0
- OS: macOS 10.13.5
- Monorepo no? Not sure about this one.
- How you are using Babel: loader (using webpack)

**Comment by dnalborczyk** [comment]
@arnsa could you assemble a simple minimal repro repository?

**Comment by loganfsmyth** [comment]
Does it still fail if you remove `["import", { "libraryName": "antd", "style": true }]`? It could be that this plugin is doing something wrong.

As mentioned, it'd be helpful to have a functional example repository to reproduce the issue.

**Comment by arnsa** [comment]
@loganfsmyth I tried removing that line, but it still fails.

@loganfsmyth @dnalborczyk here's the repo where you can reproduce the error: https://github.com/arnsa/babel-extends-error-test

To run it, run `npm install && ./node_modules/.bin/webpack-dev-server --mode development`

**Comment by existentialism** [comment]
@arnsa you'll want to remove the unnecessary `plugins` in your [webpack config for babel-loader](https://github.com/arnsa/babel-extends-error-test/blob/master/webpack.config.js#L40).

Also, you can remove simplify your babelrc a bit by removing es2015 (since you're using env), and es2015-destructuring (since it's already included).

**Comment by arnsa** [comment]
@existentialism that's a good catch! Even though after I removed babel-loader plugins from the webpack config, I am still getting this error. The only way this error is gone is when I remove BOTH babel-loader plugins from webpack config AND `["import", { "libraryName": "antd", "style": true }]` from my `.babelrc` file. But then there's another problem - ant design's styles are not being imported. It seems really weird to me that importing styles makes babel not generate __extends in some cases. Any solutions to this? :(

**Comment by existentialism** [comment]
@arnsa I'm not terribly familiar with `antd`, but from the looks of `babel-plugin-import`, it has a dep on @babel/helper-module-imports@7.0.0-beta.34... we recommend using matching versions of the betas, so I'd start there?

Ref:
https://github.com/ant-design/babel-plugin-import/blob/master/package.json

**Comment by arnsa** [comment]
@existentialism just tried to update babel packages to @7.0.0-beta.34, but I get the same error. Here's my package.json:

`
{
  "name": "admin-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "flow": "./node_modules/.bin/flow",
    "flow:coverage": "./node_modules/.bin/flow-coverage-report -i 'src/**/*.js' -t html -t json -t text --threshold 75",
    "build": "./node_modules/.bin/webpack --mode production",
    "dev:docker": "./node_modules/.bin/webpack --mode development --watch",
    "dev:local": "./node_modules/.bin/webpack-dev-server --mode development",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "antd": "^3.6.1",
    "axios": "^0.18.0",
    "file-loader": "^1.1.11",
    "formik": "^0.11.11",
    "iban": "0.0.10",
    "moment": "^2.22.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1",
    "url-loader": "^1.0.1",
    "validator": "^10.3.0",
    "yup": "^0.25.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.34",
    "@babel/core": "^7.0.0-beta.34",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.34",
    "@babel/plugin-transform-async-to-generator": "^7.0.0-beta.34",
    "@babel/plugin-transform-destructuring": "^7.0.0-beta.34",
    "@babel/polyfill": "^7.0.0-beta.34",
    "@babel/preset-env": "^7.0.0-beta.34",
    "@babel/preset-es2015": "^7.0.0-beta.34",
    "@babel/preset-flow": "^7.0.0-beta.34",
    "@babel/preset-react": "^7.0.0-beta.34",
    "@babel/preset-stage-2": "^7.0.0-beta.34",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^8.0.0-beta.2",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-webpack": "^0.10.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-flowtype": "^2.49.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.9.1",
    "faker": "^4.1.0",
    "flow-bin": "^0.75.0",
    "flow-coverage-report": "^0.5.0",
    "html-webpack-plugin": "^3.2.0",
    "image-webpack-loader": "^4.3.1",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "less-vars-to-js": "^1.2.1",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.9.0",
    "optimize-css-assets-webpack-plugin": "^4.0.2",
    "sass-loader": "^7.0.2",
    "style-loader": "^0.21.0",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^4.4.1",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.3",
    "webpack-dashboard": "^2.0.0",
    "webpack-dev-server": "^3.1.4",
    "webpack-notifier": "^1.6.0"
  }
}
`

**Comment by arnsa** [comment]
Ok, I've finally found a solution: just downgraded babel-plugin-import version to 1.6.0 and now it works :D. Thank you all for your help!

**Comment by bkniffler** [comment]
Just to make the connection, the related issue to this is: https://github.com/ant-design/babel-plugin-import/issues/210

I've published babel-plugin-import-7 which works well as a workaround.
