### ISSUE TITLE
Implement tinier, even looser transforms (like buble)

### ISSUE THREAD

**Issue by markusenglund** [babel/babel#8271]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The output of some babel transforms is much larger than the equivalent output when using [buble](https://github.com/Rich-Harris/buble), even when using babel with loose mode. I assume babel's output is more accurate or spec-compliant or something, but the buble output works completely fine. Here's an example of using the class syntax:
[buble](https://buble.surge.sh/#class%20Circle%20extends%20Shape%20%7B%0A%20%20constructor%20(%20radius%20)%20%7B%0A%20%20%20%20super()%3B%0A%20%20%20%20this.radius%20%3D%20this%3B%0A%20%20%7D%0A%0A%20%20area%20()%20%7B%0A%20%20%20%20return%20Math.PI%20*%20Math.pow(%20this.radius%2C%202%20)%3B%0A%20%20%7D%0A%7D)
[babel](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAEDCCWAnUBTaKAeAXFA7AJjAMoAWYADmgN4BQ00wA9rhFogK7BaOLQAU0RGHzx2MAJTRa9ehHaVEfcQG46MrCXgQAdEJFjoAXmgatq-gF8aasIhRh-k6TLtZ2iXNACyYDdoAKAJLQAFTeviTa5IwA7gKmOnqiEAA00ABM0CpqVhZAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=react%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

**Describe the solution you'd like**
Add these very loose transformations to babel somehow.

**Describe alternatives you've considered**
Add transforms either as stand-alone plugins or as part of the official plugins where they could be enabled by an `"extremelyLoose": true` flag or something like that. 

The advantages of having these transforms available in babel is that buble is a pain to adopt since it lacks a lot of features. It would be nice if app and library devs could easily get the smallest possible output by simply enabling a flag.

I have no idea how babel actually works internally. Does anyone else think that this is a worthwhile thing to implement? Should it be available as stand-alone plugins or part of the officially supported ones? Would it be a lot of work to implement?

**Comment by hzoo** [comment]
On mobile, but real quick. In general we will implement loose mode when people send a PR, or ask for it. For the class syntax it already is a lot less in v7 so you should check that output.

**Comment by loganfsmyth** [comment]
In Babel 7 it's going to be easier to centralize the functions like `_inherits` into a single location, so I wouldn't really include the size of that function when considering the size of the output of Babel vs Buble. Given that, we're essentially comparing

```
// Babel
var Circle = function (_Shape) {
  _inherits(Circle, _Shape);

  function Circle(radius) {
    _classCallCheck(this, Circle);

    var _this = _possibleConstructorReturn(this, _Shape.call(this));

    _this.radius = _this;
    return _this;
  }

  Circle.prototype.area = function area() {
    return Math.PI * Math.pow(this.radius, 2);
  };

  return Circle;
}(Shape);
```
vs
```
// Buble
var Circle = (function (Shape) {
  function Circle ( radius ) {
    Shape.call(this);
    this.radius = this;
  }

  if ( Shape ) Circle.__proto__ = Shape;
  Circle.prototype = Object.create( Shape && Shape.prototype );
  Circle.prototype.constructor = Circle;

  Circle.prototype.area = function area () {
    return Math.PI * Math.pow( this.radius, 2 );
  };

  return Circle;
}(Shape));
```

I'm not sure I see a ton of difference. 

Is it the size of the helper functions that is your primary concern, and would centralizing them to a single copy address your concerns?

**Comment by TrySound** [comment]
Error messages adds too much bytes.

**Comment by hzoo** [comment]
Sure, we could implement a mode that is specifically for libraries. We could implement the options individually and have an option that does the loosest thing possible if you wanted it for a lib, but of course it's a case by case basis to determine what is "loose" to some and what is required for others.

**Comment by loganfsmyth** [comment]
@TrySound Which error messages? What qualifies as too many bytes? It is hard to discuss this stuff without specifics.

**Comment by TrySound** [comment]
I'm okay with current implementation. I think the critic is about messages in `_classCallCheck`, `_possibleConstructorReturn` and `_inherits` helpers
```
throw new TypeError("Cannot call a class as a function")
throw new ReferenceError("this hasn't been initialised - super() hasn't been called")
throw new TypeError("Super expression must either be null or a function, not " + typeof superClass)
```

My point is these messages produces more safe code. And since helpers are reused there's no reason to care about size even more. Project shouldn't be considered with only one number via final bundle size. There is a size of library code and reusable vendors. Reusability is better than unsafe behaviour.

**Comment by loganfsmyth** [comment]
@TrySound Ahh gotcha, thanks for clarifying :)

**Comment by Andarist** [comment]
Most (all of them?) are not produced by loose mode, so either way it doesn't matter much at this point.

[loose output](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAEDCCWAnUBTaKAeAXFA7AJjAMoAWYADmgN4BQ00wA9rhFogK7BaOLQAU0RGHzx2MAJTRa9ehHaVEfcQG46MrCXgQAdEJFjoAXmgatq-gF8aasIhRh-k6TLtZ2iXNACyYDdoAKAJLQAFTeviTa5IwA7gKmOnqiEAA00ABM0CpqVhZAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015-loose&prettier=false&targets=&version=7.0.0-beta.50&envVersion=7.0.0-beta.49)
```js
"use strict";

function _inheritsLoose(subClass, superClass) { subClass.prototype = Object.create(superClass.prototype); subClass.prototype.constructor = subClass; subClass.__proto__ = superClass; }

function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

var Circle =
/*#__PURE__*/
function (_Shape) {
  _inheritsLoose(Circle, _Shape);

  function Circle(radius) {
    var _this;

    _this = _Shape.call(this) || this;
    _this.radius = _assertThisInitialized(_assertThisInitialized(_this));
    return _this;
  }

  var _proto = Circle.prototype;

  _proto.area = function area() {
    return Math.PI * Math.pow(this.radius, 2);
  };

  return Circle;
}(Shape);
```

The only thing that could be changed about this is removing `assertThisInitialized` calls in loose mode, but this is not much anyway.

Also - I've noticed `assertThisInitialized` being inserted twice here, need to investigate it - seems like it should be called one time.

**Comment by TrySound** [comment]
I get it. repl uses babel6 :)

**Comment by hzoo** [comment]
You can actually change the repl build to point to a different version like another tag or master which is v7. https://babeljs.io/repl/build/master/

**Comment by TrySound** [comment]
![image](https://user-images.githubusercontent.com/5635476/42337510-b0aad728-808f-11e8-9813-0b807817048f.png)

**Comment by markusenglund** [comment]
@loganfsmyth I assume you're referring to `@babel/runtime` when you're talking about centralizing helpers? The problem I've had with that package is that it seems to produce larger output than the normal internal helpers. It also imports bunch of corejs polyfills for features, some of which are supported back to IE 9. Any word on why the helpers are different in `@babel/runtime`?

**Comment by TrySound** [comment]
useBuiltIns: true produces exactly the same output as rollup plugin babel by default and do not import any polyfills.

**Comment by hzoo** [comment]
This is something we are fixing in v7 right now 🙂: https://github.com/babel/babel/pull/8266

It is confusing for people to use so we are splitting it ^, you can check the PR. It won't use anything in core-js by default unless you need it.

**Comment by markusenglund** [comment]
Going off-topic a little but here, but I still don't get why `@babel/runtime` has different helpers than the normal ones. Is this being changed?

Example: This is the objectWithoutProperties helper in `@babel/runtime 7 beta`:

```js
``

**Comment by TrySound** [comment]
https://github.com/babel/babel/pull/8261

**Comment by markusenglund** [comment]
Ok, it sounds to me like using `@babel/runtime` with `useBuiltIns: true` should be the recommended way to use babel for libraries?

**Comment by TrySound** [comment]
Yes. And according the latest issues/PRs it will be default soon.
