### ISSUE TITLE
@babel/preset-env adds polyfills based on import names

### ISSUE THREAD

**Issue by otbe** [babel/babel#8285]
## Bug Report

**Current Behavior**
It adds polyfills for things that dont need ones. It looks like it adds these polyfills solely based on the import name.

For example:
```js
import { link } from './test';
console.log(link);
```
will be translated to
```js
"use strict";

require("core-js/modules/es6.string.link");

var _test = require("./test");

console.log(_test.link);
```
Please have a look at my test repo. If you change the name to "link2" no polyfill is added.

**Input Code**
Repo
https://github.com/otbe/babel-7-preset-env-wrong-polyfills

**Expected behavior/code**
No polyfill should be added in this case.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [">2%"]
        },
        "debug": true,
        "useBuiltIns": "usage"
      }
    ]
  ]
}

```

**Environment**
- Babel version(s): 7.0.0-beta.52
- Node/npm version: node9
- OS: OSX 10.13.6
- How you are using Babel: `cli`

**Comment by rtsao** [comment]
I suppose this is a case that demonstrates how broken the `"usage"` option is:  https://github.com/babel/babel/pull/8183#issuecomment-398931001.

**Comment by nicolo-ribaudo** [comment]
What if `./test` contains this code?
```js
module.exports = "foo";
```

**Comment by zloirock** [comment]
Babel does not know what exports `./test` module, it could be a string as @nicolo-ribaudo wrote, we can't determinate that it's something else. So it's expected behavior.
