### ISSUE TITLE
Unexpected token with nested object spread

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel#8295]
## Bug Report

**Current Behavior**
```
repl: Unexpected token (4:4)
  2 |   params: {
  3 |     arg1,
> 4 |     ...arg2
    |     ^
  5 |   }
  6 | };
  7 | 
```

**Input Code**
```js
const wtf = (arg1, arg2) => {
  params: {
    arg1,
    ...arg2
  }
};

let test;
const ok = { ...test };
```

**Expected behavior/code**
It should accept the code as valid input.

**Babel Configuration (.babelrc, package.json, cli command)**
I can reproduce it with the public Babel repl with "babel-plugin-syntax-object-rest-spread" plugin.

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: Node 10.3.0/npm 6.1.0
- OS: OSX 10.13.5
- Monorepo: no
- How you are using Babel: loader (karma)

**Comment by hzoo** [comment]
Thanks for the report, but I think it's expected that it errors? I assume you are trying to return an object? For that, you'll need to wrap the `{}` in parens because otherwise the syntax looks like it's a block and it's ambiguous. Something like this

```js
const wtf = (arg1, arg2) => ({
  params: {
    arg1,
    ...arg2
  }
});
```

**Comment by stevenvachon** [comment]
Sorry, typo. It still errors with the parenthesis.

**Comment by stevenvachon** [comment]
My project is using [abel-plugin-transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread) and my repl is using [babel-plugin-syntax-object-rest-spread](https://www.npmjs.com/package/babel-plugin-syntax-object-rest-spread). Which one should we be using?

**Comment by jeaye** [comment]
I'm seeing this as well. Looks like @stevenvachon just made a typo in the report and this shouldn't be closed.

**Comment by existentialism** [comment]
Can you create a small repo that reproduces the problem?

I just tried this locally and it worked?

```json
{
  "dependencies": {
    "babel-cli": "6.26.0",
    "babel-core": "6.26.3",
    "babel-preset-env": "~1.7.0",
    "babel-plugin-transform-builtin-extend": "1.1.2",
    "babel-plugin-transform-object-rest-spread": "6.26.0"
  }
}
```

```json
{
  "plugins": [
    ["transform-builtin-extend", {
      "globals": ["Error"]
    }],
    "transform-object-rest-spread"
  ],
  "presets": [
    ["env", {
      "targets": {
        "browsers": "last 2 versions"
      },
        "test": {
            "plugins": [
                ["istanbul",
                    {
                        "exclude": "*.+(test|stub|spec).*",
                        "useInlineSourceMaps": false
                    }
                ]
            ]
        },
      "useBuiltIns": true
    }]
  ]
}
```

```js
"use strict";

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var wtf = function wtf(arg1, arg2) {
  return {
    params: _extends({
      arg1: arg1
    }, arg2)
  };
};

var test = void 0;
var ok = _extends({}, test);
```

**Comment by stevenvachon** [comment]
It's fixed in v7.x, so it's no longer an issue for me.
