### ISSUE TITLE
Optimization oppertunity: Rewrite call() with spread to apply

### ISSUE THREAD

**Issue by realityking** [babel/babel#830]
I think there's an optimzation oppertunity when code uses `call` with the spread operator. Since both `call` and `apply` are relativly slow, this might be intresting.

My test code
```javascript
function Canceller() {
  this.a = {};
  this.callback = function() {
    console.log(this);
  }
}
Canceller.prototype.test = function () {
  var args = []
  
  return this.callback.call(undefined ,...args, this.a);
};

var c = new Canceller();
c.test();
```

This currently generates the following code
```javascript
"use strict";

function Canceller() {
  this.a = {};
  this.callback = function () {
    console.log(this);
  };
}
Canceller.prototype.test = function () {
  var _callback;
  var args = [];

  return (_callback = this.callback).call.apply(_callback, [undefined].concat(args, [this.a]));
};

var c = new Canceller();
c.test();
```

However the `test` function would be better written like this:

```javascript
Canceller.prototype.test = function () {
  var _callback;
  var args = [];

  return this.callback.call(undefined, args.concat([this.a]));
};
```

**Comment by sebmck** [comment]
There's no way to do this without knowing for sure whether or not `this.callback` is a function.

**Comment by sebmck** [comment]
Also in your proposed output you've got `this.callback.call(undefined, args.concat([this.a]));` when I take it the `call` should be `apply`?

**Comment by realityking** [comment]
Yes, that's a typo. My bad.

If I understand you corretly, this would be a problem if `this.callback` was an object or class with a method called `call`? That's indeed something I hadn't thought about.

**Comment by sebmck** [comment]
Yep. You'd be breaking code in very subtle ways that would be a nightmare for people to debug since it wouldn't be a result of their code.

Also

```javascript
return this.callback.call(undefined ,...args, this.a);
```

can be rewritten as

```javascript
return this.callback.apply(undefined, [...args, this.a]);
```

Which basically gives you exactly what you want.

**Comment by realityking** [comment]
True, but not what I'd consider nice ES6 code. Thank you for your insight.
