### ISSUE TITLE
Typescript type checking in Babel 7

### ISSUE THREAD

**Issue by matteoferigo** [babel/babel#8301]
When I run babel 7 on typescript files it simply transpile them but doesn't type-check.

How can I check that types are matching? Is there a plugin for babel 7?
I tried to use [tsc](https://www.npmjs.com/package/tsc) but... it's deprecated. Any solutions?

Thanks

**Comment by TrySound** [comment]
`tsc` is deprecated in favour of `typescript` package
![image](https://user-images.githubusercontent.com/5635476/42563147-2df7518c-8506-11e8-9cad-74aadf67b33d.png)

Babel is only for faster transpiling. Use ide and `typescript` package cli to check types.

**Comment by nicolo-ribaudo** [comment]
@TrySound is right: Babel is only meant for transportation (it supports things that typescript doesn't). You still need to use typescript to check your types.
