### ISSUE TITLE
babel-register ignore is not ignoring node_modules

### ISSUE THREAD

**Issue by prakashsanker** [babel/babel#8302]
**Current Behavior**

When I use babel-register in order to do server side rendering with react, I get TypeErrors that are inside my node_modules.

**Input Code**
I have an express server that looks like this -
```
import express from "express";

// we'll talk about this in a minute:
import serverRenderer from "./middleware/renderer";

const PORT = 3000;
const path = require("path");

// initialize the application and create the routes
const app = express();
const router = express.Router();

// root (/) should always serve our server rendered page
router.use("^/$", serverRenderer);

// other static resources should just be served as they are
router.use(
  express.static(path.resolve(__dirname, "..", "build"), { maxAge: "30d" })
);

// tell the app to use the above rules
app.use(router);

// start the app
app.listen(PORT, error => {
  if (error) {
    return console.log("something bad happened", error);
  }

  console.log("listening on " + PORT + "...");
});
```

This is started like so

```
NODE_ENV=production REACT_APP_ENV=production node server/bootstrap.js
```

My bootstrap.js looks like this
```
require("ignore-styles");

require("babel-register")({
  ignore: [/(node_modules)/],
  presets: ["es2015", "react-app"]
});

require("./index");
```

**Expected behavior/code**
I expect the code to transpile properly. However, I get this

```
/<path>/node_modules/emotion/dist/index.cjs.js:49
  tag.setAttribute('data-emotion', '');
      ^

TypeError: tag.setAttribute is not a function
    at makeStyleTag (/<path>/node_modules/emotion/src/sheet.js:41:7)

```

I have already tried these variations

```
  ignore: ["/(node_modules)/"],
  ignore: /\/node_modules\//,
```
and without the ignore (as this is supposed to default to ignoring node modules).

**Babel Configuration (.babelrc, package.json, cli command)**

I'm using create-react-app, so whatever configuration is there. 

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/yarn version: node v10.4.1/ yarn 1.7.0

- OS: OSX 10.13.4
- Monorepo - no. 
- How you are using Babel: `register`

**Comment by nicolo-ribaudo** [comment]
The `tag.setAttribute` error is not coming from Babel, but from `emotion`.

**Comment by rgranger** [comment]
I have the exact opposite behavior, but i'll post the issue here :

When I use `@babel/register`, the `ignore` option of my .babelrc.js file is overriden.

.babelrc.js

```js
module.exports = {
  ignore: [
    /node_modules[\\/](?!some-es6-repo)/
  ],
  plugins: [
    "@babel/plugin-transform-modules-commonjs"
  ]
}
```

My script entry point :

```js
require('@babel/register')
const es6Func = require('some-es6-repo') // File in node_modules with import syntax

es6Func()
...
```
And i got the following error : `unexpected syntax import`

### Expected behavior

The imports in `node_modules/some-es6-repo` should be babelised according to the regex in the `ignore` option of the .babelrc.js file.
