### ISSUE TITLE
[babel-traverse] there need an error handler when call getKey of non-object

### ISSUE THREAD

**Issue by dingziqi** [babel/babel#8303]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s):  6.26.3
- Node/npm version: Node 8.11.3/npm 5.6.0
- OS: OSX 10.12.5
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: `loader`

**Possible Solution**

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/16345383/42581897-624dbbc4-8560-11e8-8d8b-c188597b87a2.png)

**Comment by loganfsmyth** [comment]
This sounds like a bug in `add-module-exports`. It shouldn't be calling `.get` if the path doesn't point at a valid node.
