### ISSUE TITLE
Babel 7: Re-exporting both default and named symbols fails to export named symbols

### ISSUE THREAD

**Issue by haggholm** [babel/babel#8306]
## Bug Report

**Current Behavior**
A module is importing both the default and named (via wildcard) symbols from a non-ES module, and re-exporting them. We use this in various scenarios either to have internal packages that can synchronise versions of 3rd parties, or for platform selection with React Native.

Since `import { Foo } from "react"` works, I would expect `export * from "react"` to work the same way—and it does, *unless* the default is also imported. Once there’s a default import, Babel uses `_interopRequireDefault()` to import the package, which means that any properties on the object become unavailable on the imported object.

*Note: Although `babel-preset-react-native` forces all `@babel` packages to `7.0.0-beta.47`, I tried forcing `7.0.0-beta.53` (latest) with the same results.*

**Input Code**
- REPL or Repo link if applicable: https://github.com/haggholm/babel-re-export-failure

```js
import _default from 'react';
export default _default;
export * from 'react';
```

**Expected behavior/code**
The output should export the default `react` import *and* the named exports.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["babel-preset-react-native"]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.47, 7.0.0-beta.53
- Node/npm version: Node 8.11.1/npm 6.1.0
- OS: Ubuntu 18.04 LTS
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**

Currently, the import interop helper looks like this:

```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
Maybe it could do something along these lines?
```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : Object.assign({ default: obj }, obj); }
```
This is just a conceptual suggestion, I have not (yet) tested it.

**Additional context/Screenshots**

See https://github.com/facebook/react-native/issues/20083

**Comment by smerat** [comment]
Any luck with this?

**Comment by haggholm** [comment]
…Or use `_interopRequireWildcard`, or…well, something. At any rate, it seems to me that `export * from "react"` should work the same regardless of whether or not there’s a default import!

**Comment by loganfsmyth** [comment]
Good catch! Posted a PR: https://github.com/babel/babel/pull/8316
