### ISSUE TITLE
Cannot read property 'join' of undefined ( preset-stage-0 )

### ISSUE THREAD

**Issue by joepuzzo** [babel/babel#8307]
## Bug Report

**Current Behavior**
When i try to run webpack I am getting the following error

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
  TypeError: [BABEL] SomeFile.js: Cannot read property 'join' of undefined (While processing: "informed/node_modules/@babel/preset-stage-0/lib/index.js")
      at "informed/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
```

**Input Code**
- https://github.com/joepuzzo/informed

```js
// webpack config snippit
  rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              "@babel/preset-env",
              ["@babel/preset-stage-0", { "decoratorsLegacy": true }],
              "@babel/preset-react"
            ],
          }
        }
      },
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: Node: 9.5.0 NPM: 5.8.0
- OS: OSX 10.13.5
- Monorepo NO
- How you are using Babel: Webpack 

**Additional context/Screenshots**
My project uses storybook and after updating to the latest beta release i started to have issues with babel. I tracked it back to an issue where there latest version started to use `@babel/core` instead of the old V6. I have a seprate webpack config for my tests and for distribution/production and they are failing with the error above.

**Comment by mAAdhaTTah** [comment]
First, stage-# plugins are deprecated, so you should definitely move off of those.

Second, this is definitely on me; I exported the list of pipeline proposals from the syntax plugin but imported it from the proposal plugin.

However, given that those are deprecated, do we want to fix it?

**Comment by joepuzzo** [comment]
Ok so basically i should stop using stage-0 preset? I attempted to remove it and now im getting `Plugin/Preset files are not allowed to export objects, only functions. In node_modules/babel-preset-stage-0/lib/index.js` Even though i removed it from the babel config.

**Comment by joepuzzo** [comment]
And also side question. If i remove stage zero how else can i achive this syntax in side of classes
```
class Foo {
  bar = () => {}
}
```

**Comment by hzoo** [comment]
```["@babel/plugin-proposal-class-properties", { "loose": false }],

**Comment by joepuzzo** [comment]
@hzoo Thanks!

**Comment by a1p4ca** [comment]
Are stage-# plugins really deprecated? I can't find any documentation about that.

**Comment by damianobarbati** [comment]
@hzoo we now have to manually include every plugin listed in https://babeljs.io/docs/en/babel-preset-stage-3 and https://babeljs.io/docs/en/babel-preset-stage-2?

**Comment by rickbeerendonk** [comment]
If the plugins are deprecated, they should still work without an error, right? Otherwise remove them completely.

**Comment by hzoo** [comment]
I'm working on a PR https://github.com/babel/babel/pull/8293. You don't need every plugin manually, you can include the ones you are using like described in https://github.com/babel/babel/blob/479d0b58271ae70887292b55072e5479611fc60b/packages/babel-preset-stage-0/README.md. If it feels like a lot, then I would recommend making your own preset and then including that instead so you only need to do that once.

**Comment by bradennapier** [comment]
Should definitely make sure its working - do you have any idea how many apps will break with this due to odd configurations that people do?

Also not a huge fan of deprecating these anyway.  At minimum another option similar to preset-env should be available to automatically apply the staged plugins in this case.

Babel seems to be int he habit lately of making things FAR harder to implement and requiring way more configuration. There was another major thing like this with preset-env requiring a crap load of new configuration to work the same way as well.

Babel 7 is becoming a "Webpack 4 --> Webpack 1" update.

**Comment by mAAdhaTTah** [comment]
> Should definitely make sure its working - do you have any idea how many apps will break with this due to odd configurations that people do?

Yeah, I'll fix this; I haven't had a chance to get back to it. But just to note, the error message is produced at the point the configuration is failing, so it's not like it'll magically fix people's configuration.

> That being said, I do understand the desire that people dont just add `stage-0` to everything. Forcing people to spend way longer to get their applications operating and causing even more developer fatigue doesnt seem to be the way to enforce what y'all believe is the way people must develop though.

It's not quite that; we don't want people blinding adding stage-0 to their configuration because the proposals contained within on inherently unstable, may not make it into the language at all, and may cause confusion / conflicts with expected syntax. We _want_ people to think about which proposals (and they are proposals, not specified language features) they're adding to their babel  configuration.

Also, just to clarify, I wrote up the specific justification for the new configuration in the pipeline plugin in [this comment](https://github.com/babel/babel/issues/8277#issuecomment-403673581), if you're interested. I should write this up someone public for reference though.

**Comment by nicolo-ribaudo** [comment]
> Forcing people to spend way longer to get their applications operating

I think that the ideal developement cycle would be something like

```
     +-------------------------------------------+
     | Add @babel/preset-env to the babel config |
     +-------------------------------------------+
                         |
             +------------------------+
             | Write code as you wish |
             +------------------------+
                         |
+----------------------------------------------------+
| Babel crashes with a nice error message:           |
| "You need to enable the @babel/plugin-proposal-foo |
|  plugin to use this new shiny syntax!"             |
+----------------------------------------------------+
                         |
                         |
   Do you really need that sytax? Are you 100% sure?
           |                            |
          YES                           NO
      Danger zone                   Safe zone
           |                            |
+----------------------+        +------------------+
| Copypaste the plugin |        | Rewrite the last |
| name from the error  |        | lines you wrote  |
| message to the       |        +------------------+
| babel config.        |
+----------------------+
```

It doesn't take much more time than using the stage presets, since Babel helps the user by actually saying what to do.

**Comment by bradennapier** [comment]
I do like this.  Any time that you can walk the user through simple questions and automate the process is ideal in my mind.  This makes preset-env really powerful for the whole project in general (more so than now). 

Although there is obviously a lot more needed on your end to accomplish the task above, DX++

**Comment by mAAdhaTTah** [comment]
> On another note (I like this other notes I guess), I think Webpacks philosophy of "sane defaults that can be extended and overwritten" is a really nice approach for developer experience.

I generally agree; in this case, we can't do that because there is no "default" for the pipeline operator that won't be a breaking change when one of the three proposals becomes the _actual_ default, accepted behavior.

**Comment by mAAdhaTTah** [comment]
Opened a PR to resolve this #8317.

**Comment by destinatis** [comment]
This issue is fucking annoying.

**Comment by hzoo** [comment]
https://github.com/babel/babel/releases/tag/v7.0.0-beta.54

I also removed the requirement to specify the decorators/pipline plugin options (default to true/"minimal"). We are going to remove the Stage presets next which will require them but at least now you won't have to specify anything, especially if you aren't using them. You can always pin to an older version or use beta.54.
