### ISSUE TITLE
Experimental Immutable Data Structures support

### ISSUE THREAD

**Issue by arian** [babel/babel#831]
@sebmarkbage wrote https://github.com/sebmarkbage/ecmascript-immutable-data-structures.

It would be cool if we could parse that syntax and transform it to Immutable.js code.

Of course one big issue would be actual compliance with future specs as that might not align with the immutable.js API.

**Comment by sebmck** [comment]
I don't really see the benefits. As far as I can tell the syntax transformations would just be a 1:1 mapping so I don't really see the value in tracking such an early standard when you can just use immutable.js and not worry about future compatibility issues.

**Comment by Dashed** [comment]
Unfortunately, I agree with @sebmck. The transformation doesn't seem worth the effort. And the spec doesn't seem to be complete to be able to implement this.

Plus the spec isn't fleshed out to cover one other important structure: Lists.

Let's put a pin on this.

**Comment by arian** [comment]
It might be a bit too early yet. The main benefit would be that it would be extremely simple to just add a `#` before a `[]` or `{}` to make it immutable.

**Comment by sebmck** [comment]
Still skeptical. Curious to hear what @leebyron and @sebmarkbage think as they're the ones with the skin in the game and I don't want the possibility of negative impact.

**Comment by leebyron** [comment]
I don't think this is a good idea. Immutable.js and the immutable values proposal have enough significant differences that mixing the syntax and behavior will only cause problems down the line

**Comment by sebmarkbage** [comment]
The best you could do is `#{ foo: bar }` -> `Object.freeze({ __proto__: null, foo: bar })` but that still doesn't have the value equality semantics. Value equality semantics is very difficult to polyfill in a performant way and without making sure you're compiling your entire program.

If you're willing to live with not having those, it might be worth while playing with.

**Comment by sebmck** [comment]
Thanks @leebyron and @sebmarkbage! Closing this as there aren't any compelling benefits at this stage.
