### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by mcampa** [babel/babel#8311]
The following code throws an error as expected:
```js
const arr = [...false];
```
![image](https://user-images.githubusercontent.com/1934727/42647167-088ec5ee-85b8-11e8-8000-fce1a1c5f024.png)

However, babel transpiled code does not:
```js
"use strict";

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

console.log([].concat(_toConsumableArray(false)));
```

which returns an empty array

**Babel Configuration (.babelrc, package.json, cli command)**

Any babel configuration. It also happens in https://babeljs.io/repl

**Comment by loganfsmyth** [comment]
This should be fixed by #7491 on our 7.x beta release.
