### ISSUE TITLE
babel-transform-react-jsx fails to install (npm keys)

### ISSUE THREAD

**Issue by intolerance** [babel/babel#8312]
## Bug Report

**Current Behavior**
npm install fails due to invalidated keys.

**Input Code**

```
npm install babel-transform-react-jsx@6.24.1
```

**Expected behavior/code**
NPM installs babel-transform-react-jsx successfully

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    "transform-react-jsx"
  ],
  "presets": [
    "es2015",
    "react"
  ],
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ]
    }
  }
}
```

**Environment**
- Babel version(s): v6.23.0
- Node/npm version: Node 8.11.1/npm 5.6.0
- OS: OSX High Seirra 10.13.5
- How you are using Babel: loader

**Possible Solution**
Re-issue keys on npm

**Additional context/Screenshots**
```
npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".
npm ERR! code E404
npm ERR! 404 Not Found: babel-transform-react-jsx@6.24.1
```

**Comment by jsg2021** [comment]
you have a typo in your package name. `babel-transform-react-jsx` should be `babel-plugin-transform-react-jsx`

**Comment by intolerance** [comment]
Thanks @jsg2021
