### ISSUE TITLE
Song needs audio version

### ISSUE THREAD

**Issue by rugk** [babel/babel#8319]
## Feature Request

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Someone has to transform [this text](https://github.com/babel/babel/blob/master/SONG.md) into a song.

**Describe alternatives you've considered**
Computer-generated voice, but that's not yet so nice to hear.

**Teachability, Documentation, Adoption, Migration Strategy**
They can hear it + it needs no docs, but is self-documenting. (or, say, the docs, i.e. lyrics, are already there)

**Comment by xtuc** [comment]
We have a one: https://youtu.be/40abpedBKK8

**Comment by rugk** [comment]
Wow cool! Then you just need to link it somewhere. E.g. [here](https://github.com/babel/babel#is-there-a-babel-song) and [here](https://github.com/babel/babel/blob/master/SONG.md) it is not linked.

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR?
