### ISSUE TITLE
polyfill require statement must be at the top.

### ISSUE THREAD

**Issue by hemanth** [babel/babel#832]
```js
require("babel/polyfill");
function *hello () {};
```

After babelification:

```js
"use strict";

var hello = regeneratorRuntime.mark(function hello() {
  return regeneratorRuntime.wrap(function hello$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
      case "end":
        return context$1$0.stop();
    }
  }, hello, this);
});

require("babel/polyfill");
;
```
 
This would result in `ReferenceError: regeneratorRuntime is not defined` was found when discussion this issue with @zeusdeux

**Comment by zeusdeux** [comment]
:+1:

**Comment by sebmck** [comment]
Yes this has been bought up before and there's no way around it due to needing to hoist function declarations. You have two options:

1. Split up your code into two files and require your main app from your entry file.
2. Use a function expression ie. `var hello = function*() {};`.

**Comment by hemanth** [comment]
Yikes, okies. That reminded me about [IIGFE](http://h3manth.com/new/blog/2014/immediately-invoked-generator-function-expression-iigfe/) ;)

**Comment by zeusdeux** [comment]
My love hate relationship with hoisting reached another level.

Ty for the quick help @sebmck :)

**Comment by mohsen1** [comment]
You can also use a IIFE wrapper to go around this. I figured it out while I was dealing with #2095

```js
require("babel/polyfill");
()=>{
  function *hello () {};
}()
```

works with `import` also

```js
import "babel/polyfill";
()=>{
  function *hello () {};
}()
```
