### ISSUE TITLE
@babel/preset-env doesn't seem to transpile with target of node v6

### ISSUE THREAD

**Issue by IljaDaderko** [babel/babel#8324]
## Bug Report

**Current Behavior**
I've set up babel with flow and env presets to target node `6.14`. It seems to work fine because it creates `lib` folder from input `src` folder, but code inside `lib` folder is not transpiled it seems (it has some empty lines cleaned up etc... though)

**Input Code**
```js
// @flow
import functions from 'firebase-functions'

console.log(functions)
```

**Expected behavior/code**
Output code should be transpiled, particularly the `import` bit, as its not supported in node v6, but output looks like this

```
// @flow
import functions from 'firebase-functions';
console.log(functions);
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-flow",
    [
      "@babel/preset-env", {
        "targets": { 
          "node": "6.14"
        }
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): -
- Node/npm version: My machine runs v10, I am targeting v6
- OS: macOS High Sierra
- Monorepo: yes, via yarn workspaces
- How you are using Babel: via `@babel/cli` running `./node_modules/.bin/babel src --out-dir lib`

**Aditional context**
Probably not too relevant but same setup using v6 packages works fine.

```js
{
  "presets": [
    "flow",
    [
      "env", {
        "targets": { 
          "node": "6.14"
        }
      }
    ]
  ]
}
```

**Comment by existentialism** [comment]
Couldn't repro this locally.

> Monorepo: yes, via yarn workspaces

Curious, is _anything_ getting transpiled? If not, I wonder if this is more related to some of the config-file-resolution changes in v7?

**Comment by IljaDaderko** [comment]
@existentialism Well, I get success message from babel, it removes empty lines, but as a whole nothing much changes.

Transpiles fine with v6 setup.

There is a project outside of this one that has another .babelrc and uses v7 plugins. Everything transpiles there fine.

**Comment by bugzpodder** [comment]
I've had a similar issue here: https://github.com/babel/babel/issues/8134
Can you enable the debug option to see what is the output?

**Comment by nicolo-ribaudo** [comment]
In Babel 7, `.babelrc`s don't affect inner packages. Can you try to rename it to `babel.config.js`?
