### ISSUE TITLE
Unexpected output when de-structuring a class property in an if-block with no braces 

### ISSUE THREAD

**Issue by scriptspry** [babel/babel#8331]
## Bug Report

**Current Behavior**

Babel outputs unexpected, incorrect(_probably_?) es5 code for a pretty basic es6 code snippet.

**Input Code**

[Link to REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQBIYB7AdhALgJwFdgd08AKASkVRRwAsBLCAOgH0APaAXkWgAcAXNACMAGmgBHIQCZoAXwDcSGvSZsARt2iVuAPmopDIAKY5-4iUpooA9DegB3UgGsI1hgDNt-AsarJDQzIEc0l5LVUWDgolQLllQLtHPCwAc2h8MGw-BnAcBix3LzIfP2sUYNCJcJ5ItnYYmkVUeNQcY1wdANpGKPVKWPjWsC1MYwc4AaQwZnbOmKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=)

```js
class A {
	constructor() {
		this._x = { p: 1, q: 2 };

		this._b = () => {
			let p, q;

			// works
			if (true) {
				({ p, q } = this._x);
			}

			// wrong transpilation
			if (true)
				({ p, q } = this._x);
		};
	}

	test() {
		this._b();
	}
}

a = new A();
a.test();
```

**Expected behavior/code**

Expected the second if to be handled correctly - it should output `_this._x` instead of `this._x`.

**Comment by nicolo-ribaudo** [comment]
It works with the latest version, if you are willing to use a beta. In case you don't,  w will release an RC soon.

https://babeljs.io/repl/build/master/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQBIYB7AdhALgJwFdgd08AKASkVRRwAsBLCAOgH0APaAXkWgAcAXNACMAGmgBHIQCZoAXwDcSGvSZsARt2iVuAPmopDIAKY5-4iUpooA9DegB3UgGsI1hgDNt-AsarJDQzIEc0l5LVUWDgolQLllQLtHPCwAc2h8MGw-BnAcBix3LzIfP2sUYNCJcJ5ItnYYmkVUeNQcY1wdANpGKPVKWPjWsC1MYwc4AaQwZnbOmKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.0.0-beta.53&envVersion=
