### ISSUE TITLE
Plugin helper should check version semantically but not literally

### ISSUE THREAD

**Issue by IhostVlad** [babel/babel#8334]
# v7 Regression

**Potential Commit/PR that introduced the regression**
https://github.com/babel/babel/pull/7450
https://github.com/babel/babel/issues/7265

**Describe the regression**
There is issue in `helper-plugin-utils`: it tries to check if babel version satisfies plugin requirements, but instead semver check, directly regular expression comparation is performed (
https://github.com/babel/babel/blob/master/packages/babel-helper-plugin-utils/src/index.js#L67
https://github.com/babel/babel/blob/master/packages/babel-helper-plugin-utils/src/index.js#L52
)

For example, some plugin requires `^7.0.0-0` semver version, but if in package.json there is directly version, which covers that semver, for example, `7.0.0-bridge.0` - nothing works.

**Expected behavior/code**
Instead regex comparation, some semver check should be performed. Pseudocode:
```js
const expectedPluginBabelVersion = '^7.0.0-0'
const actualBabelVersion = '7.0.0-bridge.0'
if(!semverCheck(expectedPluginBabelVersion, actualBabelVersion )) {
 throw new Error(`Expected ${expectedPluginBabelVersion } but get ${actualBabelVersion } version`)
}
```

**Environment**
- Babel version(s): v7.0.0-beta.54
- Node/npm version: Node 8/npm 5

**Comment by nicolo-ribaudo** [comment]
Babel already uses semver to perform that check: https://github.com/babel/babel/blob/a4795408b47e713aa2635d54197343be77e30f35/packages/babel-core/src/config/helpers/config-api.js#L60


`7.0.0-bridge.0` uses another Babel version under the hood (the `@babel/core` version that you installed). `babel-helper-plugin-utils` checks the version of that package, not of `7.0.0-bridge`. Do you have an example repo which should work but doesn't?
