### ISSUE TITLE
Redundant call to `assertThisInitialized` for classes in loose mode

### ISSUE THREAD

**Issue by rubennorte** [babel/babel#8335]
## Bug Report

**Current Behavior**

There are duplicated calls to the `assertThisInitialized` helper. 

```js
let Foo =
/*#__PURE__*/
function (_Bar) {
  _inheritsLoose(Foo, _Bar);

  function Foo() {
    var _this;

    _this = _Bar.call(this) || this;
    something(_assertThisInitialized(_assertThisInitialized(_this)));
    return _this;
  }

  return Foo;
}(Bar);
```

**Input Code**

```js
class Foo extends Bar {
  constructor() {
    super();
    something(this);
  }
}
```

**Expected behavior/code**

```js
let Foo =
/*#__PURE__*/
function (_Bar) {
  _inheritsLoose(Foo, _Bar);

  function Foo() {
    var _this;

    _this = _Bar.call(this) || this;
    something(_assertThisInitialized(_this));
    return _this;
  }

  return Foo;
}(Bar);
```

**Environment**
- Babel version(s): v7.0.0-beta.48
- Node/npm version: Node 8
- OS: OS X
- Monorepo: no
- How you are using Babel: core

**Comment by allex** [comment]
still not fixed?

**Comment by hzoo** [comment]
@allex, I would kindly ask you don't ping just to ask, if someone is working on it there will be a PR or a comment. There are plenty of things to be working on, and if you'd like to offer to help that would be appreciated too.
