### ISSUE TITLE
Array.prototype.find is undefined

### ISSUE THREAD

**Issue by paglias** [babel/babel#834]
I have this code:

```
import Reflux from 'reflux';

export default Reflux.createStore({
  findOne(id){
    return this._accounts.find(account => account.id === id);
  },
});
```

where `this._account` is an empty array.

Calling `findOne` causes an error because Array.prototype.find is undefined while according to [this table](http://kangax.github.io/compat-table/es6/#Array.prototype_methods) it's supported

**Comment by paglias** [comment]
Same for findIndex

**Comment by fkling** [comment]
I guess you are not including the [polyfill](https://babeljs.io/docs/usage/polyfill/)?

**Comment by paglias** [comment]
@fkling yeah, thanks for the help. But I think it's not very clear for which features you need the polyfill, at least Array.prototype.{find|findIndex} aren't listed here https://babeljs.io/docs/usage/caveats/

**Comment by fkling** [comment]
The caveats section only lists cases for which babel itself needs the polyfill to function properly (afaik). But in your example you are using `.find` yourself, so it's on you to provide that polyfill.
