### ISSUE TITLE
Unable to fix Unexpected token import, without recloning repo

### ISSUE THREAD

**Issue by againksy** [babel/babel#8343]
I have server side rendering
webpack 4.16 react 16.4
in wbepack config i have
`		rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          plugins: ["transform-decorators-legacy", "syntax-dynamic-import"],
          presets: [ 'react', [  'es2015'  ],  'stage-0',  ]
        }
      },
`
in package.json on client i have
`  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-dynamic-import-node": "^2.0.0",
    "babel-plugin-react-transform": "^3.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "css-loader": "^1.0.0",
    "file-loader": "^1.1.11",
    "mini-css-extract-plugin": "^0.4.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-router": "^3.2.1",
    "redux": "^4.0.0",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "transform-loader": "^0.2.4",
    "url-loader": "^1.0.1",
    "webpack": "^4.16.1",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.1.0",
    "webpack-livereload-plugin": "^2.1.1"
  }
`

on server side in package.json i have
`  "dependencies": {
    "babel-register": "^6.26.0",
    "body-parser": "^1.18.3",
    "cookie-parser": "^1.4.3",
    "ejs": "^2.6.1",
    "express": "^4.16.3",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-livereload-plugin": "^2.1.1"
  }
`
in server.js i have
`require('babel-register')({
  plugins: ["transform-decorators-legacy", "dynamic-import-node"],
  presets: ['es2015', 'stage-0', 'react'],
  extensions: [".es6", ".es", ".jsx", ".js"]
});
`
as you see i dont have `babel-plugin-syntax-dynamic-import` as dependency - but it occurs inside node_modules in client side and it works.
If i set on server side  i set "syntax-dynamic-import" instead of "dynamic-import-node"
i got
`components/InitialComponent.js:44
      import( /* webpackChunkName: "ToggleComponent", webpackPrefetch: true */'./ToggleComponent').then(function (ToggleComponent) {
      ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at loader (/Users/z/project/webpack4-serverside-react16/_server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/z/project/webpack4-serverside-react16/_server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
`
ok - if i trying to change it back - i got the same error , even if before that change everything wroked not it does not work!=(
i can only fix it if i reclone this repo. 
But i cant do this for big project=( sadly=( how to fix it? without recloning this repo?
here is the repo https://github.com/againksy/webpack4-serverside-react16 . 
### **Steps to reproduce:** 
_you can try clone it npm i in root and inside _server_
- everything will work
_but when you try to change "syntax-dynamic-import" instead of "dynamic-import-node" inside the _server/server.js - you got error_ - then , please try reset changes , and you will see error does not go away. 
Please help. i

**Comment by nicolo-ribaudo** [comment]
You can delete node_modules and reinstall them.

**Comment by againksy** [comment]
@nicolo-ribaudo i have tried this , off course at the first time.
 -it does not help

**Comment by nicolo-ribaudo** [comment]
This is the expected behavior. `syntax-dynamic-import` only allows Babel to parse dynamic import, but it doesn't transpile anything: node will still throw. `dynamic-import-node` is the correct package to use.
