### ISSUE TITLE
6.x transform-es2015-modules-commonjs loose option doesn't work as expected

### ISSUE THREAD

**Issue by yshing** [babel/babel#8347]
## Bug Report

**Current Behavior**
babel-plugin-transform-es2015-modules-commonjs
`loose` option doesn't work as [README](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs).

With the `loose` option on, babel 6 is still producing code using Object.defineProperty. And would cause re-export to fail due to the use of `Object.defineProperty`

Also related to #6795

**Expected behavior/code**
As the README

**Babel Configuration (.babelrc, package.json, cli command)**

**Environment**

**Possible Solution**
Make the `loose` option work as it suggested in [README](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs)

Add `loose` option handling for `buildExportAll` at
https://github.com/babel/babel/blob/6.x/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js

**Comment by nicolo-ribaudo** [comment]
Is this still a bug in Babel 7?
