### ISSUE TITLE
babel-preset-env doesn't support destructuring of default parameters in arrow functions for Edge

### ISSUE THREAD

**Issue by vyazadji** [babel/babel#8349]
## Bug Report

Support of Edge via *babel-preset-env* doesn't cover the destructuring of default parameters in arrow functions. 

**Current Behavior**
I add the support of Edge via *babel-preset-env*

.babelrc
```
{
  "presets": [
    ["env", {
       "targets": {
          "browsers": [
            "Edge >= 17"
          ]
        },
       "debug": true,
      }
    ]
  ]
}
```
 
**Input Code**

An example with destructuring from [compat-table](http://kangax.github.io/compat-table/es6/#test-destructuring,_parameters_defaults,_arrow_function) https://github.com/kangax/compat-table/issues/1076 which produces an error in Edge: 
```js
((a, {b = 0, c = 3}) => {
  return a === 1 && b === 2 && c === 3;
})(1, {b: 2});
```
[example 1](http://babeljs.io/repl/#?babili=false&browsers=edge%20%3E%3D%2016%0A&build=&builtIns=false&spec=false&loose=false&code_lz=BTCGBoAIG8CNILyQAxQMaMgZgL4EpEA-GAKEkgCcBTAFwFcKA7SURBJARkgDJvJ52SAEw8-GQdgDcJfMA5Q4ALkhD8koA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=Node-6.12&version=6.26.0&envVersion=1.6.2)

output: 

```
babel-preset-env: `DEBUG` option

Using targets:
{
  "edge": "17"
}

Modules transform: commonjs

Using plugins:
  transform-es2015-destructuring {"edge":"17"}
  transform-es2015-function-name {"edge":"17"}
"use strict";

((a, { b = 0, c = 3 }) => {
  return a === 1 && b === 2 && c === 3;
})(1, { b: 2 });
```

The plugin *transform-es2015-destructuring* doesn't cover this case and output is the same as the original code. And I as mentioned above this isn't valid for Edge and produces the error:
```
Error: Expected ':'
```

**Expected behavior/code**
When add support of Edge it works properly and add all necessary babel plugins.  

**Environment**
- Babel version(s): 6.26.0 (babel-core 6.26.0)
- Node/npm version: Node v8.11.3/npm 5.6.0
- OS: Docker, alpine (https://hub.docker.com/_/node/)  
- Monorepo: no
- How you are using Babel: `cli`,`webpack`

**Possible Solution**
Use *transform-es2015-parameters* plugin. 

.babelrc
```
{
  "presets": [
    ["env", {
       "targets": {
          "browsers": [
            "Edge >= 17"
          ]
        },
       "include": ["transform-es2015-parameters"],
       "debug": true
      }
    ]
  ]
}
```

[example 2](http://babeljs.io/repl/#?babili=false&browsers=edge%20%3E%3D%2016%0A&build=&builtIns=false&spec=false&loose=false&code_lz=BTCGBoAIG8CNILyQAxQMaMgZgL4EpEA-GAKEkgCcBTAFwFcKA7SURBJARkgDJvJ52SAEw8-GQdgDcJfMA5Q4ALkhD8koA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=Node-6.12&version=6.26.0&envVersion=1.6.2)

```
babel-preset-env: `DEBUG` option

Using targets:
{
  "edge": "17"
}

Modules transform: commonjs

Using plugins:
  transform-es2015-destructuring {"edge":"17"}
  transform-es2015-function-name {"edge":"17"}
  transform-es2015-parameters {}
"use strict";

((a, _ref) => {
  var _ref$b = _ref.b;
  let b = _ref$b === undefined ? 0 : _ref$b;
  var _ref$c = _ref.c;
  let c = _ref$c === undefined ? 3 : _ref$c;

  return a === 1 && b === 2 && c === 3;
})(1, { b: 2 });
```

***Suggestions:***
* For the Edge *babel-preset-env* should automatically add *transform-es2015-parameters* plugin.  
* *transform-es2015-destructuring* should handle this case.

**Comment by benmosher** [comment]
Thanks for this excellent bug report! I just ran into this as well and since you already figured out that running the `parameters` plugin resolves it, I have submitted a PR to capture that Edge needs that transform. 🤞
