### ISSUE TITLE
AMD: option for always setting .default

### ISSUE THREAD

**Issue by chrisbateman** [babel/babel#835]
Considering a module with a single default export:
```
export default class {
    // ...
}
```

Here's what loading it looks like:

**Loading transpiled AMD with RequireJS**
```
require(['MyClass'], function(MyClass) {
    var demo = new MyClass();
});
```

**Loading native ES6 with the (future) native Loader**
```
System.import('MyClass').then(function(MyClass) {
    var demo = new MyClass.default();
});
```

Currently in Babel - the default export becomes available with `.default` only after you add a named export to the module.

Would there be any value in having an option to always use `.default` - in order to be more consistent with how the native Loader will work?

**Comment by sebmck** [comment]
Use the `amdStrict` module formatter.
