### ISSUE TITLE
`only` option no longer supports functions

### ISSUE THREAD

**Issue by pwmckenna** [babel/babel#8350]
# v7 Regression

@babel/register's `only` argument no longer supports functions that take a path and return a bool.

```js
require('@babel/register')({
    only: path => true
})
```

**Expected behavior/code**
I would expect my function to gate whether a file is compiled, but I get the following error
```
Error: .only must be an array, or undefined
at assertArray (/@babel/core/lib/config/validation/option-assertions.js:87:11)
    at assertIgnoreList (/@babel/core/lib/config/validation/option-assertions.js:94:15)
    at Object.keys.forEach.key (/@babel/core/lib/config/validation/options.js:99:20)
    at Array.forEach (<anonymous>)
```
**Environment**
- Babel version(s): [v7.0.0-beta.54]
- Node/npm version: [e.g. Node 8/npm 5.6.0]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [no]
- How you are using Babel: [`register`]

**Comment by loganfsmyth** [comment]
It can be an array with a single functions, it just can't be a single function. I'm happy to leave this open since it's not an unreasonable request, it just got changed when we were locking down the options by adding validation, and leaving it as an array seemed relatively straightforward.

**Comment by pwmckenna** [comment]
ah, don't know how I missed that. easy enough to fix on my end. thanks!
