### ISSUE TITLE
preset-env loads unnecessary polyfills

### ISSUE THREAD

**Issue by tommytroylin** [babel/babel#8352]
## Bug Report

I'm targeting chrome >= 40 and I notice that preset-env imports `es6.promise` polyfill

but [caniuse](https://caniuse.com/#feat=promises) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) tell that it's supported since chrome `32`

after some digging I find this
https://github.com/babel/babel/blob/adae1501aca6b6107477ea61b47f72cee43a4438/packages/babel-preset-env/data/built-ins.json#L823-L825

is it intentionally? Should we upgrade this mapping or find a better way to solve this?

**Comment by zloirock** [comment]
Nope. See `compat-table` tests. And seems it should be stricter and equal [`core-js` feature detection](https://github.com/zloirock/core-js/blob/56f1360f7ca5104b98216bcbcacfb2ffcb9d8cf0/packages/core-js/modules/es.promise.js#L44-L62) results - [Node 10 and Chrome 66 bug](https://bugs.chromium.org/p/chromium/issues/detail?id=830565), engines without unhandled rejection tracking, etc.

**Comment by tommytroylin** [comment]
got it, thank you
