### ISSUE TITLE
"Container is falsy" when combining optional chaining with template literals

### ISSUE THREAD

**Issue by Daniel15** [babel/babel#8354]
## Bug Report

These work:
```
localStorage.getItem(`shuttle_${key}`);
localStorage?.getItem('shuttle_' + key);
```

But combining the two throws "Container is falsy":
```
localStorage?.getItem(`shuttle_${key}`);
```

REPL: https://d.sb/1f

**Babel Configuration (.babelrc, package.json, cli command)**
Internal FB configuration

**Environment**
- Babel version(s): v7.0.0-beta.47
- Node/npm version: v9.11.2
- OS: CentOS Linux release 7.5.1804
- Monorepo: N/A
- How you are using Babel: CLI

**Comment by dnalborczyk** [comment]
according to the [proposal docs](https://github.com/tc39/proposal-optional-chaining) the suggested syntax for optional method/function calls seems to be:

```javascript
localStorage.getItem?.(`shuttle_${key}`);
```

might be still a parser bug - though not sure if or what the proposal suggests - as the following syntax should maybe be disallowed. if you run the following:

```javascript
const obj = {}
obj?.foo()
```

generates:
```javascript
var obj = {};
obj === null || obj === void 0 ? void 0 : obj.foo();

// Uncaught TypeError: obj.foo is not a function
//    at <anonymous>:2:47
```

vs.

```javascript
const obj = {}
obj.foo?.()
```

generates:
```javascript
var _obj$foo;

var obj = {};
(_obj$foo = obj.foo) === null || _obj$foo === void 0 ? void 0 : _obj$foo.call(obj);
```

**Comment by Daniel15** [comment]
@dnalborczyk `localStorage` is the thing that's nullable, not `getItem`. What I want is the equivalent of:
```
if (localStorage) {
  localStorage.getItem(`shuttle_${key}`);
}
```

**Comment by dnalborczyk** [comment]
aaah, you're right. I looked too quickly... :smiley:

**Comment by jakewhelan** [comment]
I've reproduced this

Really arbitrary example using `String.prototype.replace()`
```js
// foo undefined
const foobar = foo?.replace('bar', '');
```

**Comment by jakewhelan** [comment]
I've reproduced this

Really arbitrary example using `String.prototype.replace()`
```js
// foo undefined
const foobar = foo?.replace(`bar`, '');
```

**Comment by jakewhelan** [comment]
I've reproduced this

Really arbitrary example using `String.prototype.replace()`
```js
// foo undefined
const bar = 'bar';
const foobar = foo?.replace(`${bar}`, '');
```

**Comment by jakewhelan** [comment]
I've reproduced this

Really arbitrary example using `String.prototype.replace()`
```js
// foo undefined
const bar = 'bar';
const foobar = foo?.replace(`foo${bar}`, '');
```
