### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by pirix-gh** [babel/babel#8357]
## Bug Report

**Current Behavior**
Import token not recognized

**Input Code**

**package.json:** 
```
{
...
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.54",
    "@babel/node": "^7.0.0-beta.54",
    "@babel/register": "^7.0.0-beta.54",
    "@babel/polyfill": "^7.0.0-beta.54",
    "@babel/preset-env": "^7.0.0-beta.54",
    "@babel/preset-flow": "^7.0.0-beta.54",
    "@babel/preset-react": "^7.0.0-beta.54",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.54"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.54"
  },
  "directories": {}
}
```
**.babelrc:**
```
 {
  "presets": [
    ["@babel/preset-env"]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime"]
  ]
}
```

Changing the preset (eg. preset-env) does not solve the problem

**Then run:**
`npx @babel/node src/index.js ` or
`node -r @babel/register src/index.js `

**Outputs:**
```
(function (exports, require, module, __filename, __dirname) { import {Test1, Test2} from '../../project/src/dev'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

```

**Expected behavior/code**
The code is supposed to run

**Environment**
- Babel version(s): [7.0.0-beta.54]
- Node/npm version: [Node 8/npm 5]
- OS: [Ubuntu 14.04]
- How you are using Babel: [`cli`, `register`, `loader`]

**Comment by hadnet** [comment]
Same thing here, but using @babel/register with Electron.

**Comment by dnalborczyk** [comment]
@pirix-gh  it would be always helpful to create a repro repository.

I copied everything from above, and everything seems to work as intended.

babel register works for me
```shell
node -r @babel/register index.js
```

interesting is how npx works, or _should work_ with scoped packages?

with `npx`, as far as I know, you have to use the name of the script file in ./node_modules/.bin

meaning:
```shell
node ./node_modules/.bin/babel-node index.js
```
would be equivalent to:
```shell
npx babel-node index.js  # not @babel/node
```

**the question** though now is, since it's a scoped package, that if @babel/node is not installed, I assume `npx` would install `babel-node` v6 in that case? how would it know otherwise? that might be a bug ... for `@babel/node` or `npm`, or both.

**Comment by pirix-gh** [comment]
@dnalborczyk @hadnet The problem happens in this case. Let's suppose:
```
- *LibNetwork*
 - babel.config.js
 - src/Index: Import Socket.io

- *LibDatabase*
 - babel.config.js
 - src/Index: Import Mongo

- *TestProject* (Network + DB)
 - babel.config.js
 - src/ModuleN: Import LibNetwork
 - src/ModuleD: Import LibDatabase
 - src/Index: Run all (ModuleN + ModuleD)
```

The import in this case fails on LibDatabase/LibNetwork because they are outside of the scope.
The import does not work after a ***breaking change in v7.x***, Babel does not lookup for .babelrcs that are not in the scope (project folder).

In order to ***bring back the behaviour***, we must use dynamic conf ***babel.config.js*** instead of ***.babelrc***. The option ***babelrcRoots*** has to be set to ***true***:

```
module.exports = function (api) {
    api.cache(false);

    const presets = [["@babel/preset-env"]];
    const plugins = [["@babel/plugin-transform-runtime"]];

    return {
         presets: presets,
         plugins: plugins,
         babelrcRoots: true,
    };
};
```

But even with that, I still get the same error

**Comment by dnalborczyk** [comment]
sorry, I have no idea how your setup looks like (even with the above description).

does this help? --> https://github.com/babel/babel/pull/7358

if not, could you create a minimal repro repository?

**Comment by pirix-gh** [comment]
Yes, I will do that

**Comment by hadnet** [comment]
Thanks, @pirix-gh, using babel.config.js instead of .babelrc solved my problem. I was trying to update the electron-react-boilerplate to Babel 7 and now it works perfectly.

**Comment by pirix-gh** [comment]
@hadnet do you have a similar project structure as described above ?

**Comment by hadnet** [comment]
@pirix-gh just same structure as electron-react-boilerplate.

**Comment by brettz9** [comment]
Got this working through the following (the first one only if you need dynamic `import()`):

```json
{"plugins": [
    ["babel-plugin-dynamic-import-node-babel-7"],
    ["@babel/plugin-transform-modules-commonjs"]
]}
```

...and only with `node -r @babel/register ...`, not the `npx @babel/node ...`

**Comment by nicolo-ribaudo** [comment]
Is this still a problem?

**Comment by brettz9** [comment]
Yes, my comment above was after your last release.

**Comment by pirix-gh** [comment]
Can't reproduce this bug anymore, so I consider it as closed.
