### ISSUE TITLE
babel-node does not parse arguments correctly

### ISSUE THREAD

**Issue by chbrown** [babel/babel#836]
The `babel-node` CLI argument parser is not positionally sensitive; it does not differentiate between flags that come before or after the target script filename.

Suppose I have a plain Node.js file at `bin/server`.
* `node bin/server --version` correctly runs that file, `--version` shows up in `process.argv`, my script returns "3.1.4" and exits, life is good.
* `babel-node bin/server --version` doesn't run `bin/server`, but does output a version, "4.3.0", which I know is not _my_ program's version. Turns out `babel-node --version` produces the same output.
* Oddly, `babel-node bin/server -- --version` doesn't work either; it runs my `bin/server` script, but with an empty `process.argv`. 
* `babel-node -- bin/server --version` behaves correctly, but I'd prefer not to need the `--`.

**Comment by sebmck** [comment]
Superseded by #836.

**Comment by chocolateboy** [comment]
Typo fixlet: superseded by #859.

**Comment by sebmck** [comment]
Whoops, thanks @chocolateboy!
