### ISSUE TITLE
[babel v7] Object.entries are not transformed

### ISSUE THREAD

**Issue by mocheng** [babel/babel#8362]
# v7 Regression

The [upgrade documentation](https://babeljs.io/docs/en/next/v7-migration.html) claims that `@babel/preset-env` includes `babel-preset-es2017` which is deprecated. However, `@babel/preset-env` doesn't transform code of `Object.entries`.

**Input Code**

```js
const entries = Object.entries(obj);
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  {
      "presets": [
         "preset-env": {"modules": "commonjs"}
      ]
  },
```

**Expected behavior/code**

Code `Object.entries` and `Ojbect.values` should be transformed.

**Environment**
- Babel version(s): v7.0.0-beta.42
- Node/npm version: Node 6.13.0/npm 5.6.0
- OS: OSX 10.13.4

**Comment by existentialism** [comment]
@mocheng `Object.entries` needs to be _polyfilled_, you can do this via preset-env's [`useBuiltIns` option](http://babeljs.io/docs/en/next/babel-preset-env#usebuiltins) alongside `@babel/polyfill`.

**Comment by mocheng** [comment]
@existentialism  Thanks for your info. I'm wondering whether this is a temporary solution. To support a ES2017 feature with polyfill doesn't looks solid to me.

**Comment by nicolo-ribaudo** [comment]
Preset and plugins are for _syntax_, polyfills are for _methods_. Why doesn't it look solid?
