### ISSUE TITLE
[TypeScript]: Short parameter type definition fails in function signature

### ISSUE THREAD

**Issue by thekip** [babel/babel#8365]
## Bug Report

**Input Code**
```ts
class MyClass {
  changeCallback: ({params: any}) => void;
}
```

**Current Behavior**
`SyntaxError: Unexpected token, expected ";"`

**Expected behavior/code**
Should parse without errors (Typescript compiler does)

**Babel Configuration (.babelrc, package.json, cli command)**
```js
const babylon = require('@babel/parser');
const parse = source => babylon.parse(source, {
        sourceType: 'module',
        plugins: ['typescript', 'decorators', 'classProperties'],
    });
```

**Environment**
- babel/parser version(s): 7.0.0-beta.54
- Node/npm version:  Node 8/npm 5
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: use parser via API

**Comment by xtuc** [comment]
cc @babel/typescript

**Comment by danez** [comment]
No error is thrown with babel 7.4.4.
