### ISSUE TITLE
Prototype pollution

### ISSUE THREAD

**Issue by Berkmann18** [babel/babel#8368]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Lately, NPM flagged some prototype pollution vulnerabilities that traced back this package's `lodash` dependency and I wanted to flag this up as it didn't seem to have been reported.

**Describe the solution you'd like**
It would be good if this package upgrades to using `^lodash@4.17.5` in order to cut down on the several vulnerabilities that also affect `babel-core`, `babel-generator` and `babel-types`.
**Describe alternatives you've considered**
Bumping the dependencies to using the latest versions mainly for `lodash`.

**Teachability, Documentation, Adoption, Migration Strategy**
It won't change much and shouldn't break anything.

**Comment by xtuc** [comment]
Would you mind sending a PR?

**Comment by dnalborczyk** [comment]
it seems every package is using ^4.17.5 already (which will be 4.17.10 with ^)

https://github.com/babel/babel/search?utf8=%E2%9C%93&q=%22lodash%22%3A+%22%5E4.17.5%22&type=

**Comment by Berkmann18** [comment]
@xtuc Sure.
@dnalborczyk I suppose it would despite the fact that usually means "install the version specified or above" the presence of vulnerabilities I found in `lodash@4.17.10` (which I flagged to them).

**Comment by dnalborczyk** [comment]
not sure if I follow. the link you provided from your other reference [https://nodesecurity.io/advisories/577](https://nodesecurity.io/advisories/577) points to a vulnerability in `lodash` **lower than** v4.17.5. 

> quote
Versions of lodash before 4.17.5 are vulnerable to prototype pollution.

Babel (generator and types) and everything else as far as I can tell already use v4.17.5.

**Comment by Berkmann18** [comment]
@dnalborczyk I submitted a PR (#8377) in which I explain that even tho 4.17.10 is less vulnerable to the aforementioned vulnerability I found out [here](https://github.com/lodash/lodash/issues/3882) that there's still a considerable amount of them which would possibly require another version bump.

I noticed after running `npm-check` on the latest version of this repo that a lot of other dependencies could be updated but realised that some of the other PRs were dealing with that (e.g.: webpack, eslint, ...).

**Comment by Berkmann18** [comment]
@hzoo Have you read my comments regarding the fact that some of the security vulnerabilities still persist even if the version change get submitted?
