### ISSUE TITLE
transform-class-properties doesn't let child class call parent method via super

### ISSUE THREAD

**Issue by Floriferous** [babel/babel#8369]
## Bug Report

**Current Behavior**
When inheriting from a class with arrow functions, calling `super.theArrowFunction()` does not work, whereas the same version without arrow function works.

**Input Code**
```js
class Calculator {
  doStuff = data => data;
}

class Calculator2 extends Calculator {
  doStuff = data => super.doStuff(data + 2);
}

const calc = new Calculator();

const calc2 = new Calculator2();

console.log(calc.doStuff(2)); // 2
console.log(calc2.doStuff(2)); // TypeError: Cannot read property 'call' of undefined

```

**Expected behavior/code**
I expect the second call to return 4.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

**Environment**
- Babel version(s): [v7.0.0-beta.54]
- Node/npm version: [Node 8/npm 5]
- OS: [e.g. OSX 10.13.6]

**Comment by loganfsmyth** [comment]
`super` is used for accessing values that are stored on the class prototype, but class properties are not tracked in the prototype, they behave as if they are assignments within the constructor function, so it is expected behavior that `super.doStuff === undefined` in this context.

**Comment by Floriferous** [comment]
I could've guessed that I probably don't understand the spec very well.

Why would class properties not be tracked in the prototype? 

Any other way I can "simply" use arrow functions everywhere and modify a parent class like in my example?

**Comment by loganfsmyth** [comment]
```
class Calculator {
  doStuff = data => data;
}

class Calculator2 extends Calculator {
  doStuff = data => super.doStuff(data + 2);
}
```
is fairly close to this:
```
class Calculator {
  constructor(){
    this.doStuff = data => data;
  }
}

class Calculator2 extends Calculator {
  constructor(){
    this.doStuff = data => super.doStuff(data + 2);
  }
}
```
since class fields are per-instance, they don't exist on the prototype.

**Comment by nicolo-ribaudo** [comment]
As Logan explained, class fields are replaced by derived instances. If you want to access them using super, you need to define them as class methods.
