### ISSUE TITLE
ANSI color codes in chrome console output

### ISSUE THREAD

**Issue by xcoderzach** [babel/babel#837]
I'm getting this in my chrome console on error
```
Module build failed: SyntaxError: Unterminated JSX contents (266:12)
  264    |           [1m[37m<[39m[22m/[37mdiv[39m[1m[37m>[39m[22m
  265    |         [1m[37m<[39m[22m/[37mdiv[39m[1m[37m>[39m[22m
> 266    |       [1m[37m<[39m[22m/[37mdiv[39m[1m[37m>[39m[22m
         |             ^
  267    |     [1m[34m)[39m[22m
  268    |   [32m}[39m
  269    | [32m}[39m[1m[34m)[39m[22m
```

**Comment by sebmck** [comment]
Can I have some more information, what plugin you're using etc?

**Comment by xcoderzach** [comment]
* Babel 4.3.0
  * babel loader 4.0.0
  * react hot loader 1.0.7

Using webpack these loaders
```
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ['react-hot', 'babel?experimental=true,modules=common']
      },
```
and this plugin
```
webpack.NoErrorsPlugin()
```

**Comment by sebmck** [comment]
There's not really anything that can be done besides removing the ANSI syntax highlighting altogether.

**Comment by xcoderzach** [comment]
Is this default behavior, or is it due to some part of my configuration?

**Comment by sebmck** [comment]
It's default behaviour. It automatically ANSI syntax highlights if the terminal [supports-colors](https://github.com/sindresorhus/supports-color/). You should be able to disable the colors with the following command:

```sh
$ TERM=dumb INSERT_YOUR_COMMAND_HERE
```

**Comment by xcoderzach** [comment]
I really like the terminal colors :-D , so I think I'll just patch my console.error to strip ansi with https://github.com/sindresorhus/strip-ansi

Thanks for your help!

**Comment by sebmck** [comment]
Ah great, no problem!

**Comment by marijnh** [comment]
This problem still exists, and I don't think expecting users to use strip-ansi is a real solution. Could you reopen this issue?

**Comment by sebmck** [comment]
Just thought of a way I could make it work:

```javascript
err.stack = {
  inspect: function () { return coloredStack; },
  toString: function () { return noncoloredStack; },
  toJSON: function () { return noncoloredStack; }
};
```

Will dump colored output for the console but if it's serialised it'll be a non-colored string. Only issue is consumers that expect `err.stack` to be a string.

**Comment by sebmck** [comment]
It's really hacky so I'll have to do some testing to see if it's practical. I'm hesitant on adding an additional option if it can be done some other (albeit hacky) way.

**Comment by sebmck** [comment]
In the next version you'll be able to set the `highlightErrors` option to `false`.

**Comment by frederickfogerty** [comment]
:+1:

**Comment by joliss** [comment]
Chiming in on an old issue... How about having `err.message` be always non-colorized (so other tools can easily log and display them), but adding something like `err.colorMessage` (or `ansiColorMessage`) so consumers can decide whether what to print into their terminals?

Consumers seem better-equipped to know whether to print color (e.g. by parsing a `--color={always,auto,never}` argument). The chalk library that babel uses calls [this argv sniffing code](https://github.com/sindresorhus/supports-color/blob/master/index.js) to automatically turn color on and off - that seems like it's going to be brittle.
