### ISSUE TITLE
[Babel 6] [preset-env]: Include stage 4 object rest spread by default

### ISSUE THREAD

**Issue by justinhelmer** [babel/babel#8370]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The [Object Rest/Spread properties proposal](https://github.com/tc39/proposal-object-rest-spread) is now Stage 4. Babel's [preset-env](https://github.com/babel/babel/tree/master/packages/babel-preset-env) is designed to include the latest presets, which should include the finalized (stage 4) proposals.

**Describe the solution you'd like**

With the new published non-proposal package, it would be ideal if this plugin were included by default as part of [preset-env](https://github.com/babel/babel/tree/master/packages/babel-preset-env) (for babel 6 and babel 7).

**EDIT:** Per @hzoo (reference #7658 by @existentialism) - This is already true for babel@7

Also, this would mean removal of the plugin from babel's [Stage 3 preset](https://babeljs.io/docs/en/babel-preset-stage-3.html)

**EDIT:** Per @hzoo - It would be a breaking change to remove from the stage 3 preset, which is why the change was made to babel@7. These types of challenges are one of the main reasons "stage-x" presets are going away: #8293 

Since it's no longer a stage 3 proposal, [@babel/plugin-proposal-object-rest-spread](https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread) likely should be renamed (to `@babel/plugin-object-rest-spread`). This is true only for the babel 7 (scoped) package.

**Describe alternatives you've considered**

A workaround is setting `shippedProposals` to `true`, or configuring [@babel/plugin-proposal-object-rest-spread](https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread) directly (or `babel-plugin-transform-object-rest-spread on babel 6).

However this is only needed because the base package has not yet absorbed this stage 4 change.

**Teachability, Documentation, Adoption, Migration Strategy**

After absorbing the latest version, consumers would no longer need to install or configure `babel-plugin-transform-object-rest-spread` or `@babel/plugin-proposal-object-rest-spread` directly. This should be backwards compatible, since still having the config will not cause things to break.

**Comment by hzoo** [comment]
👋Thanks for the issue! The proposal should already be included as part of preset-env without `shippedProposals` in v7 (if not that's a bug). If we removed the plugin from Stage 3 preset it would be a breaking change which is why we made the change in v7. This is also why we are removing the Stage presets in v7 due to these kinds of issues https://github.com/babel/babel/pull/8293.

This is great, I'm writing a blog post about these issues right now 😁!

**Comment by existentialism** [comment]
Ref: https://github.com/babel/babel/pull/7658

**Comment by justinhelmer** [comment]
Awesome, makes sense @hzoo. I really appreciate the quick reply; I know how busy you are.

I'll admit we are still stuck on babel@6 and I made a false assumption that changes roll out to both versions at the same time. Thanks @existentialism for the cross-reference indicating this has been merged into babel@7.

I'll attempt to clarify where we stand to see if we're on the same page (please correct me if I'm wrong and I'll make edits):

- For babel@6, consumers currently must continue to use `babel-preset-env`
   and `babel-plugin-transform-object-rest-spread` in conjunction (or use `shippedProposals`).
- The purpose of this issue is to track `babel-plugin-transform-object-rest-spread` being configured/enabled by default when using `babel-preset-env` (for babel@6).
- For babel@7, consumers can simply use `@babel/preset-env`, which by default already includes `@babel/plugin-proposal-object-rest-spread`

There is also the discussion point of renaming `@babel/plugin-proposal-object-rest-spread` to `@babel/plugin-object-rest-spread` per "[Switch to -proposal- for TC39 Proposals](https://new.babeljs.io/docs/en/next/v7-migration.html#switch-to-proposal-for-tc39-proposals-blog-2017-12-27-nearing-the-70-releasehtml-renames-proposal)" but I don't want to pollute this issue thread.

Since this is babel 6 specific, I have updated the issue title

**Comment by nicolo-ribaudo** [comment]
This is fixed in Babel 7
