### ISSUE TITLE
@babel/types TypeScript definitions is missing some exported functions

### ISSUE THREAD

**Issue by mgroenhoff** [babel/babel#8375]
## Bug Report

**Current Behavior**
I am trying to use the TypeScript definitions from `@babel/types` but I am missing some functions:
https://github.com/babel/babel/blob/a811cf78e19442bbc10b05be2076c330fb702087/packages/babel-types/src/index.js#L96-L111

**Environment**
- Babel version(s): 7.0.0-beta.54

**Comment by xtuc** [comment]
Would you mind sending a PR?

**Comment by mgroenhoff** [comment]
I am not really sure where to start TBH. I know those types are automatically generated but that's about it. Can you give me some directions on how to approach this?

**Comment by brandonkal** [comment]
cloneNode is also missing from the type definitions

**Comment by nicolo-ribaudo** [comment]
@brandonkal Added!

**Comment by JLHwung** [comment]
Fixed by #10098

**Comment by brandonkal** [comment]
Looking through my babel plugins, I found some more types that are missing:
```ts
declare module '@babel/core' {
  namespace types {
    type VisitorKeys = {
      [T in keyof AllNodes]: Extract<
        keyof AllNodes[T],
        {
          [Key in keyof AllNodes[T]]: AllNodes[T][Key] extends (
            | t.Node
            | t.Node[]
            | null)
            ? Key
            : never;
        }[keyof AllNodes[T]]
      >;
    };

    const VISITOR_KEYS: { [T in keyof VisitorKeys]: VisitorKeys[T][] };
    const FLIPPED_ALIAS_KEYS: {
      [T in keyof t.Aliases]: t.Aliases[T]['type'][];
    };

    function shallowEqual(actual: object, expected: object): boolean;
  }
}
```
I'll post this here as it is related, but I can open new issue if desired.

**Comment by mgroenhoff** [comment]
Thanks all for taking this over!
