### ISSUE TITLE
`babelrcLoadEnabled` and/or `findPackageData` seem to prevent compiling files in node_modules dir

### ISSUE THREAD

**Issue by quinn** [babel/babel#8378]
As far as I can tell, because of the boundary this line creates in `package.js`

```
while (!pkg && _path().default.basename(dirname) !== "node_modules") {
```

when `babelrcLoadEnabled` runs:

```
if (babelrcRoots === undefined) {
    return pkgData.directories.indexOf(absoluteRoot) !== -1;
}
```

it returns false which, from what I can tell, prevents the file from being compiled.

**Comment by xtuc** [comment]
Hey @quinn, could you fix your issue?
