### ISSUE TITLE
Closing iterators

### ISSUE THREAD

**Issue by rauschma** [babel/babel#838]
In the latest spec, `for-of` (and others) close iterators (by calling `someIterator.return()`).

```js
function* foo() {
  yield 'a';
  yield 'b';
}
foo.prototype.return = function (...args) {
  console.log('RETURN');
  return super.return(...args);
};
for (let x of foo()) {
  console.log(x);
  break; // should trigger `return` method
}
```

**Comment by sebmck** [comment]
Should be easy enough.

**Comment by sebmck** [comment]
Although I'll have to make it match this too:

```javascript
foo: for (let x of foo()) {
  console.log(x);
  break foo; // should trigger `return` method
}
```

**Comment by sebmck** [comment]
Done, handles labels perfectly.

**Comment by sebmck** [comment]
Released as of 4.4.0, thanks!

**Comment by zloirock** [comment]
@sebmck [double](https://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=var%20iter%20%3D%20%5B1%2C2%2C3%5D.values()%3B%0D%0Aiter.return%20%3D%20()%20%3D%3E%20console.log('return')%0D%0Afor%20(let%20x%20of%20iter)%20%7B%0D%0A%20%20console.log(x)%3B%0D%0A%20%20if(1)break%3B%0D%0A%7D)

**Comment by sebmck** [comment]
@zloirock Oh jeez, weird.

**Comment by sebmck** [comment]
@zloirock Easy fix, thanks!

**Comment by zloirock** [comment]
@sebmck iterators may not have this method, see [IteratorClose](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-iteratorclose)

**Comment by sebmck** [comment]
@zloirock Fixed.

**Comment by rauschma** [comment]
Note that *any* kind of abrupt completion leads to `return()` being called (including exceptions!).

**Comment by sebmck** [comment]
Not sure if wrapping the entire block in a try-catch is a good idea.

**Comment by rauschma** [comment]
Yes, not an easy decision.

**Comment by sebmck** [comment]
I'll push out a patch that fixes the issues @zloirock raised and I'll consider the viability of wrapping it in a try-catch although it doesn't look good.

**Comment by sebmck** [comment]
`for...of` loops now close their iterator on abrupt completions. In loose mode this isn't the case.
