### ISSUE TITLE
const is too verbose! Make it default when assignment is done by :=

### ISSUE THREAD

**Issue by Kimilhee** [babel/babel#8386]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In es6 and above, more than 95% of the variables is declared as const.
Then, let's make it default!

**Describe the solution you'd like**
Instead of this 
```
const id = 123;
```

This is far better! concise and shorter!
```
id := 123;
```

I know that this one declaration seems not so much difference.

But, you con easily find the following case!
```
const id = 123;
const str = 'ABC'
const time = new Date();
const reg = /abc/;
const ....
```

Let's do it just like this.
```
id := 123;
str := 'ABC'
time := new Date();
reg := /abc/;
....
```

That's it.
Done.

**Describe alternatives you've considered**
Nope.

**Teachability, Documentation, Adoption, Migration Strategy**
It's straightforward.
I don't think we need any other explanation.

**Comment by nicolo-ribaudo** [comment]
Babel is not the place to propose new ECMAScript features. You can read https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md

**Comment by nicolo-ribaudo** [comment]
Btw, I don't think that a proposal whose only goal is to omit 5 characters is going to be considered. You can use gzip or another compression tool.

**Comment by nicolo-ribaudo** [comment]
Btw, you could write
```js
const
  id = 123,
  str = 'ABC',
  time = new Date(),
  reg = /abc/;
```
Which is as short as your example.

**Comment by Kimilhee** [comment]
@nicolo-ribaudo
Your idea is quite nice, but I can't use that.
Because my company's coding convention disallow that kind of declaration.

We're following this coding style.
https://github.com/airbnb/javascript#variables--one-const
```
// bad
const items = getItems(),
    goSportsTeam = true,
    dragonball = 'z';

// bad
// (compare to above, and try to spot the mistake)
const items = getItems(),
    goSportsTeam = true;
    dragonball = 'z';

// good
const items = getItems();
const goSportsTeam = true;
const dragonball = 'z';
```

**Comment by nicolo-ribaudo** [comment]
Well, it's easier to change your company's stylistic conventions than to introduce a new language feature 😆
