### ISSUE TITLE
v7 Regression - IE10 inheritance fix broke inheritance in chrome

### ISSUE THREAD

**Issue by TikiTDO** [babel/babel#8392]
# v7 Regression

> First check out: https://new.babeljs.io/docs/en/next/v7-migration.html
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Potential Commit/PR that introduced the regression**

Issue was introduced on the linked line of the linked PR:

https://github.com/babel/babel/commit/2af7a33c4e41d6f45daf84a366e80757ad7d4d81#diff-ba75bd4d116cc90ad8c8002e3010e821R402

**Describe the regression**

Code to fix class inheritance in IE10 broke prototype inheritance for Chrome (and possibly otheres)

**Input Code**
```js
import { Component } from React
class Example extends Component {
  constructor(props) {
    super(props)
    this.render // This is undefined
    this.handleSomething // This is undefined
    this.setState // This is defined and inherited from Component
  }

  handleSomething() {
    // Do Something Else
  }

  render() {
    // Do Something
  }
}
```

Parsing the above code with the options below creates a class which **does** contain methods inherited from `Component` but **does not** contain methods defined in the `Example` class.

The root cause appears to be that the code linked above overwrites the `Example` prototype chain, replacing the prototype that contains the methods created by `defineProperty`. I was able to work around the issue by switching to beta 47.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["react-native"],
  "plugins": ["react-native-web", {}]
}
```

**Expected behavior/code**

Expect a class which extends a superclasses to be able to access methods defined in the class, and in the super class while in chrome.

**Environment**
- Babel version(s): v7.0.0-beta.48+
- Node/npm version: Node 8/npm 6.1
- OS: OSX, Arch LInux
- Monorepo: Yes
- How you are using Babel: loader

**Comment by loganfsmyth** [comment]
Would be possible to include a sample of the code being produced and executed?

**Comment by TikiTDO** [comment]
@loganfsmyth Is there a tool you can recommend for generating such samples? We ended up just hacking up our project for debugging.

**Comment by TikiTDO** [comment]
@loganfsmyth I tried doing it in repl as follows:

```js
class A {
  foo() {}
}

class B extends A {
  bar() {} 
}

let b = new B()
console.log(b.foo)
console.log(b.bar)
```

Which was compiled to: 

```js
"use strict";

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var A = function () {
  function A() {
    _classCallCheck(this, A);
  }

  _createClass(A, [{
    key: "foo",
    value: function foo() {}
  }]);

  return A;
}();

var B = function (_A) {
  _inherits(B, _A);

  function B() {
    _classCallCheck(this, B);

    return _possibleConstructorReturn(this, (B.__proto__ || Object.getPrototypeOf(B)).apply(this, arguments));
  }

  _createClass(B, [{
    key: "bar",
    value: function bar() {}
  }]);

  return B;
}(A);

var b = new B();
console.log(b.foo);
console.log(b.bar);
```

This ended up working properly, because the `_inherits(B, _A);` got compiled above `_createClass(B, [{...}])`.

In our repo this was the other way around, it would first to `_createClass`, then it would call `_inherits`.

**Comment by loganfsmyth** [comment]
It's possible you have mismatched versions. The PR you linked relies on changes to two different parts of Babel's build logic, some of which lives in `@babel/helpers` and some of which lives in `@babel/plugin-transform-classes`.

If _one_ of those was on `beta.47` and one of them was on `beta.48`, that would likely cause the issue that you're seeing.

**Comment by TikiTDO** [comment]
Ah, yeah. Looking at the lockfile it's pulling in `@babel/helpers@7.0.0-beta.54` from an explicit define, but `@babel/plugin-transform-classes@7.0.0-beta.47` from the `react-native` preset.

I'll double check that this fixes the problem and close the issue. Sorry about that.

**Comment by loganfsmyth** [comment]
No problem, it's definitely frustrating. The partly our fault for being in beta for so long :(

**Comment by TikiTDO** [comment]
We bringing it on ourselves too; we're trying to use the same babel config across half a dozen apps on 3 different platforms. Now there's another lever I can check if there's unexpected behavior in the future. Anyway, seems using the correct preset fixes the problem completely. Thanks for taking the time to clarify the issue.

If anyone else hits this problem, it can be checked in your lock file (be it yarn or npm), by ensuring `@babel/helpers` and `@babel/plugin-transform-classes` are the same version. 

The following diff resolved it for me:

```
--- a/app/package.json
+++ b/app/package.json
  "devDependencies": {
-    "@babel/cli": "7.0.0-beta.47",
-    "@babel/core": "7.0.0-beta.47",
-    "@babel/node": "7.0.0-beta.47",
+    "@babel/cli": "7.0.0-beta.54",
+    "@babel/core": "7.0.0-beta.54",
+    "@babel/node": "7.0.0-beta.54",
@@ -49,7 +49,7 @@
     "babel-loader": "^8.0.0-beta",
     "babel-plugin-react-intl": "2.x",
     "babel-plugin-react-native-web": "0.x",
-    "babel-preset-react-native": "^5",
+    "metro-react-native-babel-preset": "0.x",


-- a/app/webpack.config.js
+++ b/app/webpack.config.js
@@ -59,7 +59,7 @@ const babelLoaderConfiguration = {
     loader: "babel-loader",
     options: {
-      presets: ["react-native"],
+      presets: ["module:metro-react-native-babel-preset"],
```

**Comment by deecewan** [comment]
I'm not sure how you managed to get all the deps to the same version. It seems every package I'm using at the moment has a different explicitly pinned version of the Babel 7 Beta.
