### ISSUE TITLE
Recipe for disabling strict mode using Babel 7 and coffee-loader

### ISSUE THREAD

**Issue by binarykitchen** [babel/babel#8394]
I can see the breaking change adding use strict everywhere since Babel v7.0

This is breaking my legacy code using `callee`. Looking for solutions to switch that off globally but all my attempts failed. Using babel-env and babel-preset-es2015. 

Webpack rule to load coffee files is

```
{
  test: /\.coffee$/,
  use: [
    {
      loader: 'coffee-loader',
      options: {
        transpile: {
          presets: ['es2015']
        }
      }
    }
  ]
}
```

But that always injects `use strict`. Suggestions?

**Comment by loganfsmyth** [comment]
To clarify, are you looking for a 6.x or 7.x solution? You mention `7.0`, but you listed the `6.x` preset names.

**Comment by binarykitchen** [comment]
A v7 solution if possible

Or should I downgrade Babel to v6?

**Comment by loganfsmyth** [comment]
By default, Babel assumes that all files are ES modules, which are strict by default. If your files aren't always ES modules, you'll need to tell Babel that via one of:

```
sourceType: "script" // never modules
sourceType: "unambiguous" // it's a module if it uses `import`/`export`
```

**Comment by binarykitchen** [comment]
Actually `presets: [['es2015', { modules: false }]]` did the trick!

Thanks @loganfsmyth for helping me on Slack
