### ISSUE TITLE
parse error on BindingPattern in BindingRestElement

### ISSUE THREAD

**Issue by ajafff** [babel/babel#8396]
## Bug Report

**Current Behavior**
Doesn't parse BindingPattern in BindingRestElement

**Input Code**

```js
let [...[a]] = [1];

function foo(...{length}) { console.log(length); }
```

**Expected behavior/code**
BindingRestElement can contain BindingPattern. Therefore the variable declaration should parse without problems.
FunctionRestParameter is basically a BindingRestElement and therefore also allows BindingPattern.

https://tc39.github.io/ecma262/#prod-BindingRestElement
https://tc39.github.io/ecma262/#prod-FunctionRestParameter

Note that BindingPattern is not allowed in BindingRest**Property**. Therefore the following code doesn't need to parse correctly:

```js
let {...{}} = {};
```

**Babel Configuration (.babelrc, package.json, cli command)**

whatever the default in the REPL is

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: repl

**Possible Solution**

**Additional context/Screenshots**

**Comment by microbouji** [comment]
I'll look into this and see if I can make a PR to add it at least for v7 first.

**Comment by xtuc** [comment]
Thanks @microbouji. I would recommend joining our Slack if you have any questions.

**Comment by nicolo-ribaudo** [comment]
```js
let [...[a]] = [1];
```
already works with Babel 7.

**Comment by microbouji** [comment]
@nicolo-ribaudo yes, and in `transform-parameters/src/rest.js` I was thinking of just converting it to that and let the destructuring plugin handle it correctly.

Just need to better understand that whole `state.deopted` thing in there now so I can be confident that a simple `node.body.body.unshift()` is all that's needed to insert it at the right place.
