### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions. 

### ISSUE THREAD

**Issue by sridharpanneer** [babel/babel#8399]
Hi all,

i get below error while running grunt in Babel 

Running "browserify:dev" (browserify) task
>> Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/sridhar/Documents/Projects/Rimowa/Build/node_modules/babel-preset-es2015/lib/index.js while parsing file: /js/storelocator.js
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

**Comment by nicolo-ribaudo** [comment]
Babel version/configuration?

PS. Didn't GitHub show an issue template? 🤔

**Comment by loganfsmyth** [comment]
You appear to be using `babel-preset-es2015` (a Babel 6 preset), with Babel 7. Either downgrade to Babel 6, or use `@babel/preset-env`.
