### ISSUE TITLE
REPL triggers URIError

### ISSUE THREAD

**Issue by raganwald** [babel/babel#840]
![urierror](https://cloud.githubusercontent.com/assets/17715/6276021/babbc128-b851-11e4-9987-56e511df9843.png)

To reproduce: Go to the home page, and click on the [REPL](http://babeljs.io/repl/) link.

1. Put some JavaScript in the left pane.
2. Note that the right pane is blank.
3. Open the error console, and note the URIError.

Browsers: Reproduced in Safari and Chrome on OS X.

**Comment by raganwald** [comment]
FYI, the link http://babeljs.io/repl/ causes the error, but if I navigate to http://babeljs.io/repl.html, I do not get the error.

**Comment by sebmck** [comment]
Can't manage to reproduce this. http://babeljs.io/repl.html redirects to http://babeljs.io/repl/ so that wouldn't be related. Does the browser URL include a hash when it outputs the URI error?

**Comment by sebmck** [comment]
Also issues with the site and REPL should be reported on [babel.github.io](https://github.com/babel/babel.github.io).

**Comment by raganwald** [comment]
Thanks, I will report it there later today. And yes, http://babeljs.io/repl.html redirects to http://babeljs.io/repl/ for me too, it’s just that if I type http://babeljs.io/repl.html directly, I get the URIError, whereas if I type the .html and it redirects, I get no error and it prefills my pane with whatever I used to be working on.

**Comment by sebmck** [comment]
Just pushed a patch that wraps the url decoding in a try-catch. Obviously not a permanent fix but at least it wont cause the entire page to error. Thanks for the report @raganwald!

**Comment by raganwald** [comment]
![worksonmymachine](https://cloud.githubusercontent.com/assets/17715/6289766/7890319a-b8f0-11e4-8800-f929597a646f.jpg)
