### ISSUE TITLE
babel-plugin-transform-modules-commonjs default undefined

### ISSUE THREAD

**Issue by SkeLLLa** [babel/babel#8400]
## Bug Report

**Current Behavior**
Babel transpile sources to not working code, due to adding `default`.

**Input Code**
- REPL or Repo link if applicable:

```js
import config from 'config';
config.get('foo')
```

Transformed to 
```js
var _config = require("config");
_config.default.get('foo')
```

**Expected behavior/code**
Code should be transpiled into something like this (if required module has no `default` or it just commonjs module)
```js
var _config = require("config");
_config.get('foo')
```
**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["env", {
      "modules": "commonjs",
      "targets": {
        "node": "10"
      }
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-object-rest-spread", {"loose": true, "useBuiltIns": true }],
    ["@babel/plugin-transform-modules-commonjs", {
      "loose": true,
      "noInterop": true
    }]   
  ]
}

```

**Environment**
- Babel version(s): v7.0.0-beta.5*
- Node/npm version: Node 10
- OS: Linux
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
You are explicitly disabling compatibility with commonjs module by using the `noInterop` option.

**Comment by SkeLLLa** [comment]
So if I understand correctly this module can't do
Is there any way to do something like this:
```js
var module = require("module").__esModule? require("module").default :  require("module");
// or
var module = require("module").default || require("module");
module.doSomething()
module.doSomethingElse()
module.doSomethingAgain()
module.doSomethingMore()
```
instead of 
```js
var module = _interopRequireDefault(require("module"));
module.default.doSomething()
module.default.doSomethingElse()
module.default.doSomethingAgain()
module.default.doSomethingMore()
```

**Comment by xtuc** [comment]
I don't understand the issue with Babel "pollution", the generated code shouldn't matter to you?

I'm not really sure to know how it works but you could use https://babeljs.io/docs/en/babel-plugin-external-helpers.html to have a single module with all our helpers. Would that help you?

**Comment by SkeLLLa** [comment]
@xtuc the thing is that I want to use the generated code and continue development without babel.

**Comment by nicolo-ribaudo** [comment]
You can try this plugin: https://github.com/finom/babel-plugin-transform-es2015-modules-simple-commonjs/
