### ISSUE TITLE
preset-env beta>=50 has incorrect behavior with `ignoreBrowserslistConfig: true`

### ISSUE THREAD

**Issue by yyx990803** [babel/babel#8402]
## Bug Report

**Current Behavior**

When using `ignoreBrowserslistConfig: true` in `preset-env`, it causes `targets` to be ignored for polyfills injected by `useBuiltIns: 'usage'`.

**Input Code**

```js
const babel = require('@babel/core')
const preset = require('@babel/preset-env')

let { code } = babel.transformSync(`
  const a = new Map()
`.trim(), {
  babelrc: false,
  presets: [[preset, {
    modules: false,
    targets: { esmodules: true },
    useBuiltIns: 'usage',
    ignoreBrowserslistConfig: true
  }]]
})

console.log(code)
```

**Expected output**

With `targets: { esmodules: true }`, should only inject minimal polyfills:

``` js
// beta.49 and before
import "core-js/modules/web.dom.iterable";
const a = new Map();
```

However the presence of `ignoreBrowserslistConfig: true` seems to cause Babel to ignore `targets`:

**Actual output**
``` js
// beta.50 and above
import "core-js/modules/web.dom.iterable";
import "core-js/modules/es6.array.iterator";
import "core-js/modules/es6.string.iterator";
import "core-js/modules/es6.map";
var a = new Map();
```

**Environment**
- Babel version(s): v7.0.0-beta.50 ~ 55

**Possible Solution**

**Additional context/Screenshots**
Maybe related: https://github.com/babel/babel/pull/8391

**Comment by existentialism** [comment]
I see the issue, lol... incoming fix

**Comment by yyx990803** [comment]
@existentialism thanks!
