### ISSUE TITLE
IE: Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by cis-ankity** [babel/babel#8406]
Hello I'm facing the following issue in a react application when I'm testing it with IE -11

It is throwing the following error - 
 **Object doesn't support property or method 'remove'**
Although, when I've tested the same thing on any other browser then It was not throwing any such type of error. 

Could you please help me or tell me if any transform plugin is available for object properties?

**Comment by nicolo-ribaudo** [comment]
`Object.remove` doesn't exist. Can you share an example to reproduce the error?

**Comment by cis-ankity** [comment]
For example, you can use the following code - 
create a div with the class name 'test' and button and call a function removeTest on button click - 
Html -> 
<div class="test">
  <p>example for IE error</p>
<div>
<button onclick="removeDiv">Remove Div</button>

JS - 
function removeDiv(){
const divRef = document.getElementByClassName('test');
divRef[0].remove(); // this line will through error in IE and works on other browsers.
}

**Comment by demurgos** [comment]
This not a Babel issue: `ChildNode.prototype.remove` is part of the web API, not the language.

This distinction means that this is not a feature defined by the ES spec (so in the scope of Babel) but an API specific to web browsers (outside of the scope of Babel).

To solve your issue, you should use a polyfill. You can check [the MDN article](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) or look on npm.

**Comment by cis-ankity** [comment]
Thank you @demurgos, But current issue occurring in React application and for that, I've needed a bable polyfill. If you know about any bable polyfill which can help me in this issue please suggest.

**Comment by nicolo-ribaudo** [comment]
You should use a dom polyfill (e.g. https://github.com/WebReflection/dom4).
Btw, when using react you shouldn't manipulate the dom directly.
