### ISSUE TITLE
Make JSX transform generic

### ISSUE THREAD

**Issue by anthonyshort** [babel/babel#841]
The JSX transform is currently coupled to React, but other libraries could potentially make use of the syntax. There are libraries like jsx-transform (https://github.com/alexmingoia/jsx-transform) that make the transform more generic and allow you to specific how the output should look:

```js
/** @jsx React.createElement */
var React = require('react');

var profile = <div>
  <img src="avatar.png" class="profile" />
  <h3>{[user.firstName, user.lastName].join(' ')}</h3>
</div>;
```

Transforms it to:

```js
var React = require('react');

var profile = React.createElement('div', null, [
  React.createElement('img', { src: "avatar.png", class: "profile" }),
  React.createElement('h3', null, [[user.firstName, user.lastName].join(' ')])
]);
```

Alternative virtual DOM libraries can then use it:

```js
/** @jsx dom */
var {dom} = require('deku');

var profile = <div>
  <img src="avatar.png" class="profile" />
  <h3>{[user.firstName, user.lastName].join(' ')}</h3>
</div>;
```

And get the same benefits of using JSX.

You could easily just add a setting for it rather than using the comment format too. If this is something that would be useful I can look at opening a PR for it.

**Comment by sebmck** [comment]
This used to be available but I removed it when the `react` transformer was upgraded to React 0.12 because I wasn't sure how it's supposed to map when specifying a custom prefix. I can possibly add it to the `reactCompat` transformer since AFAIK all the alternate JSX libraries use that format.

In your example:

```javascript
/** @jsx dom */
var {dom} = require('deku');

var profile = <div>
  <img src="avatar.png" class="profile" />
  <h3>{[user.firstName, user.lastName].join(' ')}</h3>
</div>;
```

what would that transform into?

**Comment by anthonyshort** [comment]
Most of the libraries use the same syntax, including React

```
Function (type String, attrs Object, children Array)
```

so it would turn it into:

```js
 var profile = dom('div', null, [
  dom('img', { src: "avatar.png", class:"profile" }),
  dom('h3', null, [[user.firstName, user.lastName].join(' ')]])
]);
```

So you can actually replace `dom` there with `React.createElement`, or `h`, or any of the other virtual DOM libraries. All the transform is really doing is setting the name of the function to add there.

**Comment by sebmck** [comment]
I meant more along the lines of:

```javascript
<Foo></Foo>;
```

**Comment by anthonyshort** [comment]
Ah, those are just custom components in all cases too:

```js
dom(Foo, {}, [])
h(Foo, {}, [])
React.createElement(Foo, {}, [])
```

**Comment by sebmck** [comment]
Ah right okay, I guess that was my main question as I wasn't sure if it was method calls directly to the custom component or not.

**Comment by anthonyshort** [comment]
Wow that was quick! Thanks :)

**Comment by joshthecoder** [comment]
This may bite you if you have pre-0.12 jsx comments in your code base, but are using React 0.12.
Now that the transform honors these comments, it will bust your code. Our fault for not scrubbing these
out a long time ago, so guess it was a good breaking change. :)

**Comment by ivan-kleshnin** [comment]
So **babel** don't use** jsx-transform** right now? The reason I ask is because **jsx-transform** has the ability to specify transformations in input options. I don't like those pesky pragmas and would prefer to pass option object to **babel** / **babelify**.

**Comment by sebmck** [comment]
No, Babel has its own JSX transformer. It's currently not possible to pass
options to transformers although that may change in the next major, just
need to think of a good way to do it.

On Saturday, 14 March 2015, Ivan Kleshnin <notifications@github.com> wrote:

> So *babel* don't use** jsx-transform** right now? The reason I ask is
> because *jsx-transform* has the ability to specify transformations in
> input options. I don't like those pesky pragmas and would prefer to pass
> option object to *babel* / *babelify*.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/841#issuecomment-80200553>.
>


-- 
Sebastian McKenzie
