### ISSUE TITLE
Figure out plan for polyfilling library functionality stage < 4

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#8416]
Now that we've removed the stage presets, there's still the question of how we want to handle stage < 4 proposals for _library_ functionality, rather than syntax.

In Babel 6 (and 7 for now), we just load `core-js@2`, which meant we auto-loaded anything that `core-js` decided to polyfill, including anything that is still experimental.

Given the precedent for `7.x` with the presets, it seems like we should consider having the default `@babel/polyfill` only polyfill things that are stage 4/standard. We can still for instance expose specific features, once they land in `core-js`, as like

```
import "@babel/polyfill/some-experimental-feature";
```
which would likely be enough?

As with syntax, this would also things safer for us as proposals evolve over time, because we can leave the existing polyfill files, but add additional ones alongside when things change.

**Comment by hzoo** [comment]
Yeah I think we can emulate what we are doing with proposals in transforms?

So in v7 "import "@babel/polyfill" is only what is Stage 4? and opt into specific ones.

later: I guess the other question (really need to think about this), is whether we really need the alias if it's just core-js (also related is switching out core-js for other polyfills for transform-runtime/preset-env)
