### ISSUE TITLE
Transpile Number.isInteger() ?

### ISSUE THREAD

**Issue by senner007** [babel/babel#8422]
Is babel not supposed to transpile Number.isInteger() ? 

It is part of es2015 and doesn't work in IE.

**Comment by xtuc** [comment]
Transpile to what? It's an API that needs to be polyfilled, Babel doesn't do that.

**Comment by senner007** [comment]
Transpile to es5. Why are arrow functions being transpiled and not isInteger ? They are both part of es2015

**Comment by xtuc** [comment]
Arrow function is a new syntax, it needs to be transformed because it can't be polyfilled.
`Number.isInteger` is just an API, it can be Polyfilled.

Have you tried to use https://github.com/babel/babel/tree/master/packages/babel-preset-env?

**Comment by senner007** [comment]
Doesn't seem to work. I did the following:

npm install --save-dev @babel/core @babel/cli @babel/preset-env
npm install --save @babel/polyfill

babel.config.js:

```
const presets = [
    ["@babel/env", {
      targets: {
        ie: "11"
      }
    }]
  ];
  
  module.exports = { presets };
```

**Comment by senner007** [comment]
So is there an easy way to detect/transpile browser compatibility problems without running it?

**Comment by existentialism** [comment]
@senner007 you will want to use the [useBuiltIns option](http://babeljs.io/docs/en/babel-preset-env#usebuiltins).

**Comment by senner007** [comment]
Ok. Thanks for your support. 
I managed to convert with webpack, wit import ‘babel-polyfill’ in the entry file. Then I found that it only includes ecmascript polyfills an not the missing dom polyfills that ie needed. After copying them manually from the mozilla site, it now works.
