### ISSUE TITLE
`module` not passed to `factory` function (@babel/plugin-transform-modules-umd)

### ISSUE THREAD

**Issue by lukehorvat** [babel/babel#8423]
Hi. I'm trying to transform the following CommonJS module into UMD:

```js
module.exports = { hello: "world" };
```

Using the old `transform-es2015-modules-umd` plugin:

```js
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define(["module"], factory);
  } else if (typeof exports !== "undefined") {
    factory(module);
  } else {
    var mod = {
      exports: {}
    };
    factory(mod);
    global.main = mod.exports;
  }
})(this, function (module) {
  "use strict";

  module.exports = { hello: "world" };
});
```

Using the new `@babel/plugin-transform-modules-umd` plugin (v7.0.0-beta.56):

```js
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory);
  } else if (typeof exports !== "undefined") {
    factory();
  } else {
    var mod = {
      exports: {}
    };
    factory();
    global.main = mod.exports;
  }
})(this, function () {
  "use strict";

  module.exports = {
    hello: "world"
  };
});
```

As you can see, the `@babel/plugin-transform-modules-umd` plugin does not pass `module` as an argument to the `factory` function. Is this a regression or by design? Is exporting via `module.exports` no longer respected?

**Comment by nicolo-ribaudo** [comment]
Babel transpiles es modules to umd, not commonjs modules. In an es module `module` would be a global variable, so it is correct that it isn't shadowed by the umd factory.

**Comment by loganfsmyth** [comment]
Yeah, @nicolo-ribaudo is correct. The `umd` transform is intended to transform ES6 module syntax into UMD syntax. The fact that it supported converting CommonJS to UMD in 6.x was essentially an accidental side-effect of the way it was implemented, and failed in many cases.

You could almost certainly fork the old plugin to get them to keep doing what they were doing in 6.x, but it's not something we're likely to maintain as part of Babel's core plugins.
