### ISSUE TITLE
[BUG] @babel/register does not compile anything from node_modules, even if not ignored.

### ISSUE THREAD

**Issue by trusktr** [babel/babel#8424]
## Bug Report

**Current Behavior**

I've got `ignore: []` in my config:

```js
require('@babel/register')({
	ignore: [],
	extensions: ['.ts', '.tsx'],
	cache: true,
})

require('./main.ts')
```

however when it reaches a file of a linked node module (the symlink is inside `node_modules`), it doesn't seem to be able to transpile the file.

It was all working fine until I moved the files out of my project into a separate package, then `npm link`ed them into my project.

**Input Code**

n/a

**Expected behavior/code**

I'm expecting it to be able to transpile the linked module files. I get an error like

```
Uncaught SyntaxError: /Users/trusktr/src/location/of/linked/modules/someFile.ts: Unexpected token, expected "{" (13:62)

  11 | const log = Logger(__filename)
  12 | 
> 13 | export default class WindowActions extends ActionFactory<AnnotatedSceneState, ActionMessage<AnnotatedSceneState>> {
     |                                                               ^
  14 | 	constructor() {
  15 | 		super(SceneState)
  16 | 	}
    at Parser.raise (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:3893:15)
    at Parser.unexpected (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:5222:16)
    at Parser.expect (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:5210:28)
    at Parser.parseClassBody (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:7838:10)
    at Parser.parseClass (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:7812:10)
    at Parser.parseExportDefaultExpression (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:8171:19)
    at Parser.parseExport (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:8136:31)
    at Parser.parseStatementContent (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:7202:27)
    at Parser.parseStatement (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:7115:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/trusktr/src/my-project/node_modules/@babel/parser/lib/index.js:7666:23)
```

Looks like it's tripping up on the type args, `<AnnotatedSceneState, ActionMessage<AnnotatedSceneState>>`.

**Babel Configuration (.babelrc, package.json, cli command)**

This is my `babelrc` file, which was working fine before I moved these files out into a separate package an `npm link`ed them:

```js
{
	"presets": [
		"@babel/preset-typescript",
	],
	"sourceMaps": "both",
	"plugins": [
		"@babel/plugin-proposal-object-rest-spread",
		["@babel/plugin-proposal-decorators", { "legacy": true }],
		"babel-plugin-transform-class-properties",
		"@babel/plugin-transform-modules-commonjs",
		"@babel/plugin-transform-react-jsx"
	]
}
```

**Environment**
- Babel version(s): `v7.0.0-beta.51`
- Node/npm version: `Node 9.11.2` / `npm 6.1.0`
- OS: `OSX 10.13.4 (17E199)`
- Monorepo: no
- How you are using Babel: `register`

**Possible Solution**

No ideas yet.

**Additional context/Screenshots**

**Comment by trusktr** [comment]
Oh wait a second, I misinterpreted the error: `@babel/register` is hitting that file, but it's making an error with the parser. Still, this all worked before I moved the files into a package and linked them.

Any ideas why this may happen? I'd share the repo, but it's private.

**Comment by trusktr** [comment]
Okay, hmmmm 🤔, I manually placed the files into a folder in node_modules, so they aren't linked, and I still get the error.

I'm stumped: I haven't changed my `babelrc` config, and this was all working before I put the files into a separate package.

**Comment by trusktr** [comment]
I tried emptying babelrc so that it contains

```js
{}
```

and this caused Babel to trip on the first `.ts` file. So the config works, but when I restore the content of babelrc it trips on the first file in node_modules, which is the one in the error.

What do I have to do to make it work on node_modules?

**Comment by trusktr** [comment]
As a workaround for now, I switched to `ts-node`. It has a similar `ignore` option, which works as expected.

**Comment by loganfsmyth** [comment]
Putting the `.babelrc` in the module itself should work, but otherwise this is essentially expected. In Babel 6, `.babelrc` files are resolved relative to the file being compiled, so if you move a file into a sibling directory, instead of `node_modules`, the `.babelrc` won't apply there anymore. The only option there would be to put a separate `.babelrc` in the linked module, or pass the options programmatically to `babel-register`.

I'll be the first to admit that the 6.x behavior is weird. In an effort to make this weirdness clearer, 

In Babel 7, `.babelrc` files are limited to a single package. As an alternative in 7.x, we've also added a `babel.config.js` file format that loads from the working directory instead of relative to the file being compiled, which makes it much easier to have a config that applies across multiple files. So for your case, you should be able to rename your `.babelrc` to `babel.config.js` and have it export the config, and it should all work.

**Comment by sberney** [comment]
I had this error too. My project imports `lodash-es`, but the `ignore: ` field doesn't apply to `node_modules` in any way. I haven't done anything funny with linking or custom projects or anything like that at all -- just installed `lodash-es` with yarn.

So when I process my project through `mocha` or `gulp`, I get a bunch of syntax errors (they can't handle `import` syntax).

I renamed my `.babelrc` to `babel.config.js` and added `module.exports = ` to it, and now `@babel/register` transpiles `lodash-es`. It's fortunate in my case that I didn't rely on the functionality of using `.babelrc` versus `babel.config.js`. It seems like bizarre behavior, but I successfully worked around it.

**Comment by ianstormtaylor** [comment]
@sberney @trusktr did either of you ever figure this out? I'm seeing the exact same thing. Nothing I seem to do with the `ignore:` option does anything. Even with:

```js
require('@babel/register', {
  cache: false,
  ignore: [
    file => {
      console.log('IGNORE?', file)
      return false
    }
  ],
})

...
```

Nothing will ever be logged to the console.
