### ISSUE TITLE
use babel to parse .babelrc.js

### ISSUE THREAD

**Issue by graingert** [babel/babel#8425]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Have a simple set of defaults that allow `.babelrc.js` to use a default `babel-preset-env` with `node: 'current'`

**Describe the solution you'd like**
I want to use modern JS inside my `.babelrc.js`

**Describe alternatives you've considered**
allow `.babelrc.mjs` and use node's built in ESM and other features

**Teachability, Documentation, Adoption, Migration Strategy**
it should be transparent

**Comment by jaydenseric** [comment]
I would love `babel.config.mjs` support!

**Comment by nicolo-ribaudo** [comment]
There are some problems with this proposal:
1) One of the reasons to move every transformation to a separate plugin in Babel 6 was to make `babel-core` smaller. In we include `@babel/preset-env` by default, it would be super big again.
2) I think that it could be confusing that in your babelrc you can use features different from what you can use in your code. For example, in your code you might have enabled some proposal plugins which you couldn't use in your babelrc.

**Comment by deecewan** [comment]
your second point is the current state of play tho, isn't it? currently, babel transforms all our JS, but we can't use those same language features in our config.

**Comment by nicolo-ribaudo** [comment]
This is impossible to do, since we can't know which Babel plugins we should use to read the config file until we have read it. :chicken: :egg:

**Comment by graingert** [comment]
> This is impossible to do, since we can't know which Babel plugins we should use to read the config file until we have read it. chicken egg

It could use a default config
