### ISSUE TITLE
The stage-0 readme contradicts the babel documentation

### ISSUE THREAD

**Issue by marcofugaro** [babel/babel#8427]
In the [README of babel-preset-stage-0](https://github.com/babel/babel/tree/master/packages/babel-preset-stage-0) this is written

```json
{
  "plugins": [
    // Stage 0
    "@babel/plugin-proposal-function-bind",

    // Stage 1
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    ["@babel/plugin-proposal-optional-chaining", { "loose": false }],
    ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
    ["@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false }],
    "@babel/plugin-proposal-do-expressions",

    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}
```

Whereas in the [babel-plugin-proposal-decorators documentation](https://babeljs.io/docs/en/next/babel-plugin-proposal-decorators.html):

> When using the legacy: true mode, @babel/plugin-proposal-class-properties must be used in loose mode to support the @babel/plugin-proposal-decorators.

```json
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ]
}
```

Which one is right? Also I didn't understand why are all the proposals passed `loose: false` if that's the default behaviour?

**Comment by nicolo-ribaudo** [comment]
We can just add an inline comment in the stage 0+ readmes.

**Comment by lidoravitan** [comment]
Can I help with that?

**Comment by nicolo-ribaudo** [comment]
Yes!

**Comment by lidoravitan** [comment]
@nicolo-ribaudo Thanks!
Can you give me some directions about where to start?
If I understood correctly, I have to make a change inside [README of babel-preset-stage-0](https://github.com/babel/babel/tree/master/packages/babel-preset-stage-0). 
    ["@babel/plugin-proposal-class-properties", { "loose": false }] to     ["@babel/plugin-proposal-class-properties", { "loose": true }] ?

**Comment by nicolo-ribaudo** [comment]
Yes, and also for stage-2 and stage-1. You should also mention that if they aren't using decorators, loose mode isn't needed.

**Comment by lidoravitan** [comment]
@nicolo-ribaudo I opened PR for this issue, Hope it fits the requirements :) let me know if any changes needed.
