### ISSUE TITLE
Project Name: Babel

### ISSUE THREAD

**Issue by Hydra9268** [babel/babel#8430]
I'm curious. Why "Babel?" בָּבֶל means confusion. Your JavaScript compiler is called "Confusion" in Aramaic. Was that intentional?

**Comment by demurgos** [comment]
I was not there when the name was chosen, but I suppose it refers to the story of [the tower of Babel](https://en.wikipedia.org/wiki/Tower_of_Babel):

> an origin myth meant to explain why the world's peoples speak different languages.

In this case, there are many variants of Javascript or Javascript-derived languages, each with their own versions and optional features. It may cause some confusion, but `babel` is here to solve it. The name references more that there are many languages (versions) supported by Babel.

(Yeah, I know that the multitude of languages prevented the tower from being finished and is probably why it means "confusion" in your language, but hopefully `babel`-the-lib is more successful :stuck_out_tongue: )
