### ISSUE TITLE
[beta.56 cli] TypeError: Path must be a string

### ISSUE THREAD

**Issue by wKovacs64** [babel/babel#8431]
## Bug Report

**Current Behavior**

Upgrading `@babel/cli` from 7.0.0-beta.55 to 7.0.0-beta.56 now errors when trying to build:

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object`

This does not happen all my projects, but it does happen in more than one of them, so it might be something in the project structure that triggers it. It seems to be a bug in the latest implementation of the [`readdir` function in `util.js`](https://github.com/babel/babel/blob/6476a0d08906c2da2b2b8b1d0bb5ace9cef461f6/packages/babel-cli/src/babel/util.js#L13) introduced in #8418, but I'm not sure. `path.join` seems to be receiving an array of all the files and directories in my source directory as opposed to a single entry. See the excerpt from a failed Travis CI build at the bottom of this issue for an example.

**Input Code**

This has happened in several repositories, but here is one public example:

- REPL or Repo link if applicable: https://github.com/wKovacs64/hibp
- Relevant PR: https://github.com/wKovacs64/hibp/pull/41

**Expected behavior/code**

I expected it to continue building successfully, or alert me to what I need to change if there was an intentional breaking change.

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc.js:
```js
const test = process.env.NODE_ENV === 'test';
const cjs = process.env.BABEL_ENV === 'commonjs' || test;

module.exports = {
  plugins: [cjs && '@babel/transform-modules-commonjs'].filter(Boolean),
  presets: [
    [
      '@babel/env',
      {
        loose: true,
        modules: false,
        targets: test
          ? { node: 'current' }
          : {
              browsers: ['> 1%', 'last 2 versions'],
              node: 6,
            },
      },
    ],
  ],
};
```

package.json build script:
```
cross-env NODE_ENV=production BABEL_ENV=commonjs babel src --out-dir lib --source-maps --ignore \"src/__mocks__/**/*\",\"**/*.test.js\"
```

**Environment**
- Babel version(s): v7.0.0-beta.56
- Node/npm version: Node 6-10, npm v5.6.0-latest, yarn v1.3.2-latest
- OS: macOS 10.12.6, Windows 10, Linux (Travis CI)
- Monorepo: no
- How you are using Babel: cli

**Additional context/Screenshots**

<details>
  <summary>Related excerpt from failed build on Travis</summary>
  <pre>
> cross-env NODE_ENV=production BABEL_ENV=commonjs babel src --out-dir lib --source-maps --ignore "src/__mocks__/**/*","**/*.test.js"
TypeError: Path must be a string. Received [ '__mocks__',
  '__snapshots__',
  '__tests__',
  'breach.js',
  'breach.test.js',
  'breachedAccount.js',
  'breachedAccount.test.js',
  'breaches.js',
  'breaches.test.js',
  'dataClasses.js',
  'dataClasses.test.js',
  'hibp.js',
  'hibp.test.js',
  'internal',
  'pasteAccount.js',
  'pasteAccount.test.js',
  'pwnedPassword.js',
  'pwnedPassword.test.js',
  'pwnedPasswordRange.js',
  'pwnedPasswordRange.test.js',
  'search.js',
  'search.test.js' ]
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at /home/travis/build/wKovacs64/hibp/node_modules/@babel/cli/lib/babel/util.js:77:57
    at Array.filter (<anonymous>)
    at read (/home/travis/build/wKovacs64/hibp/node_modules/fs-readdir-recursive/index.js:15:6)
    at Object.readdir (/home/travis/build/wKovacs64/hibp/node_modules/@babel/cli/lib/babel/util.js:76:44)
    at /home/travis/build/wKovacs64/hibp/node_modules/@babel/cli/lib/babel/dir.js:179:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/travis/build/wKovacs64/hibp/node_modules/@babel/cli/lib/babel/dir.js:74:103)
    at _next (/home/travis/build/wKovacs64/hibp/node_modules/@babel/cli/lib/babel/dir.js:76:194)
  </pre>
</details>

**Comment by loganfsmyth** [comment]
Definitely looks like a regression, sorry about that.

**Comment by TrySound** [comment]
I get the same. The regression comes from [fs-readdir-recursive](https://www.npmjs.com/package/fs-readdir-recursive) package. Actually the problem was solved with reinstalling cli; the package had newer minor version.
```js
yarn remove @babel/cli && yarn add @babel/cli --dev
```
