### ISSUE TITLE
[beta.56 loader]: Module parse failed: Unexpected token You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by miran248** [babel/babel#8433]
## Bug Report

**Current Behavior**
Compilation fails because a class in different package (same monorepo) uses class properties.
That class is a dependency of a node app, which is then transpiled.

**Input Code**
- https://github.com/miran248/babel-test

**Expected behavior/code**
Compilation should succeed

**Babel Configuration (.babelrc, package.json, cli command)**

```
{
  "presets": [
    [ "@babel/preset-env", {
      modules: false,
      targets: {
        node: "current"
      }
    } ]
  ],
  "plugins": [
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    [ "@babel/plugin-proposal-class-properties", { "loose": true } ],
    "@babel/plugin-proposal-json-strings",
    "@babel/plugin-transform-arrow-functions"
  ]
}
```

https://github.com/miran248/babel-test/blob/35e313f151585b5aca317087a2097d629ae89646/server/webpack.config.js#L60

**Environment**
- Babel version(s): 7.0.0-beta.56
- Node/npm version: Node v9.2.1/npm 6.2.0/yarn 1.7.0
- OS: OSX 10.13.6
- Monorepo yes (yarn workspaces, without Lerna)
- How you are using Babel: loader (webpack 4)

**Possible Solution**

**Additional context/Screenshots**
![screen shot 2018-08-07 at 22 22 09](https://user-images.githubusercontent.com/32389245/43800364-605fe676-9a90-11e8-8b43-6b702ad25004.png)

**Comment by mAAdhaTTah** [comment]
There doesn't appear to be a `.babelrc` in your example repository.

**Comment by miran248** [comment]
It's part of the `webpack.config.js` ( https://github.com/miran248/babel-test/blob/35e313f151585b5aca317087a2097d629ae89646/server/webpack.config.js#L60 )

I've extracted it above for clarity.

**Comment by mAAdhaTTah** [comment]
Ah, my bad. Looking at that closer, I _think_ your webpack configuration is setup to only parse files under the `server/src` directory:

```js
const rootPath = path.resolve(__dirname, ".");
...
const sourcePath = path.resolve(rootPath, "src");
...
{
        test: /\.js$/,
        include: sourcePath,
        use: [
          {
            loader: "echo-loader",
          },
          {
            loader: "babel-loader",
...
```

The error is actually coming from webpack, rather than babel. Webpack uses Acorn to parse the JS, which generally doesn't get updated w/ proposed features until they've shipped.

**Comment by miran248** [comment]
Awesome.

Will try `rollup` tomorrow - haven't used it yet so..

Thank you!

**Comment by miran248** [comment]
Tried it and it works! I've pushed the [rollup branch](https://github.com/miran248/babel-test/tree/rollup)

I guess we can close the issue. :)
