### ISSUE TITLE
Running babel <directoryname> -d <output directory> results in 'Path must be a string' error (Babel 7b56)

### ISSUE THREAD

**Issue by Sinistralis** [babel/babel#8439]
## Bug Report

**Current Behavior**

`npx babel src -d lib`

Results in the following:
```
TypeError: Path must be a string. Received [
  ...array of file/directory names
]
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at C:\Users\User\Documents\Project_Name\node_modules\@babel\cli\lib\babel\util.js:77:57
    at Array.filter (<anonymous>)
    at read (C:\Users\User\Documents\Project_Name\node_modules\fs-readdir-recursive\index.js:15:6)
    at Object.readdir (C:\Users\User\Documents\Project_Name\node_modules\@babel\cli\lib\babel\util.js:76:44)
    at C:\Users\User\Documents\Project_Name\node_modules\@babel\cli\lib\babel\dir.js:179:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\User\Documents\Project_Name\node_modules\@babel\cli\lib\babel\dir.js:74:103)
    at _next (C:\Users\User\Documents\Project_Name\node_modules\@babel\cli\lib\babel\dir.js:76:194)
```

**Expected behavior/code**

Expected that the directory is transpiled correctly and output in the lib folder.

**Babel 6 on the same machine works as expected.**

**Environment**
- Babel version(s): [v7.0.0-beta.56]
- Node/npm version: [e.g. Node 8.11.1/npm 5.5.1]
- OS: [e.g. Windows 10]
- Monorepo [e.g. no]
- How you are using Babel: [`cli`]

**Possible Solution**
The easiest solution I can see would be for fsReaddirRecursive (don't think this is your dependency to manage unfortunately) to invoke the filter function by additionally passing in the new dirName when it recurses, which it what it looks like the readDir function under babel/util expects.

Instead, it is currently passing the entire array of filenames for that current directory, so you are calling path.join on an array, which is failing.

```js
function readdir(dirname, includeDotfiles, filter) {
  return (0, _fsReaddirRecursive().default)(dirname, (filename, _index, currentDirectory) => {
    // Example of the problem code. CurrentDirectory is an array of file strings, not a current path string.
    const stat = _fs().default.statSync(_path().default.join(currentDirectory, filename));

    if (stat.isDirectory()) return true;
    return (includeDotfiles || filename[0] !== ".") && (!filter || filter(filename));
  });
}
```

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/8436!
