### ISSUE TITLE
import 'class' constructor, console ok, but new class is not defined

### ISSUE THREAD

**Issue by Yueyun** [babel/babel#8441]
I'm using babel-plugin-component
here's my import
`import {CanvasPoster} from 'ui-lib'
`
but when I using this: `new CanvasPoster()`
it says 

> myPoster.vue?7d2b:33 Uncaught (in promise) ReferenceError: CanvasPoster is not defined

but i can console.log(CanvasPoster)

i can fix this problem to change import CanvasPoster from 'ui-lib/lib/CanvasPoster', does anyone know thy this happen?

**Comment by nicolo-ribaudo** [comment]
You should ask to the `babel-plugin-component` repo (https://github.com/ElementUI/babel-plugin-component) 😉
