### ISSUE TITLE
Deprecation warning on babel-polyill.

### ISSUE THREAD

**Issue by andrewplummer** [babel/babel#8442]
## Feature Request

The `babel-polyfill` npm package still gets a large number of downloads a week but it looks like the official package is now `@babel/polyfill`. Would be nice to have a banner there so it's clear that this one is old, if not deprecated.

**Comment by nicolo-ribaudo** [comment]
`@babel/*` packages are still in beta. We wouldn't deprecate `babel-*` until `@babel/*` is stable.

**Comment by andrewplummer** [comment]
Ah ok I figured that out a bit too late. The thing is I was somehow directed to [this page](https://babeljs.io/docs/en/next/babel-polyfill.html) from somewhere and assumed that it was the main page, so `@babel/polyfill` was the official release... a big red banner somewhere saying "this is the beta version" might be helpful...
