### ISSUE TITLE
Promise has not been converted

### ISSUE THREAD

**Issue by lilijialiang** [babel/babel#8447]
## Bug Report

**Current Behavior**
In v7.0.0-rc.1 and v7.0.0-beta.56, Promise has not been converted. But in v7.0.0-beta.55/54, the same configuration, been converted.

**Input Code**
```js
window.Promise = Promise
```

**Expected behavior/code**
Promise should be converted

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["android >= 4"]
      }
    }]
  ],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.56, v7.0.0-rc.1
- Node/npm version: Node v8.9.1/Npm 5.5.1
- OS: OSX 10.12.5
- How you are using Babel: cli

**Possible Solution**
null

**Additional context/Screenshots**

package.json
```json
{
  "name": "test",
  "main": "index.js",
  "scripts": {
    "build": "babel a.js"
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-rc.1",
    "@babel/core": "7.0.0-rc.1",
    "@babel/preset-env": "7.0.0-rc.1",
    "@babel/plugin-transform-runtime": "7.0.0-rc.1"
  }
}
```

**Comment by nicolo-ribaudo** [comment]
After beta 56, Babel runtime only inserts helpers by default. If you want it to insert the core-js polyfills, you should pass the `corejs: 2` option. This is needed so that we can add core-js 3 support without breaking changes.

```json
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["android >= 4"]
      }
    }]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "corejs": 2
    }]
  ]
}
```

**Comment by hzoo** [comment]
Yeah, this is an intentional breaking change that was done in https://github.com/babel/babel/releases/tag/v7.0.0-beta.56

Updated in the guide here https://babeljs.io/docs/en/next/v7-migration#babel-runtime-babel-plugin-transform-runtime

**Comment by lilijialiang** [comment]
@hzoo @nicolo-ribaudo Thanks for your reply, it’s my negligence, thx!
