### ISSUE TITLE
core-js/fn/symbol/iterator.js not being loaded in IE11

### ISSUE THREAD

**Issue by liegeandlief** [babel/babel#8449]
I am using babel-preset-env and babel-polyfill with `useBuiltIns` set to `usage`, via Webpack. My browserslist query is "> 1%" which includes IE11. I import babel-polyfill in my app's main entry point file.

I'm using the following babel packages in my application:

```
"babel-polyfill": "^6.26.0",
"babel-core": "^6.26.3",
"babel-eslint": "^8.2.6",
"babel-jest": "^23.4.0",
"babel-loader": "^7.1.5",
"babel-minify-webpack-plugin": "^0.3.1",
"babel-plugin-syntax-dynamic-import": "^6.18.0",
"babel-plugin-transform-class-properties": "^6.24.1",
"babel-plugin-transform-object-rest-spread": "^6.26.0",
"babel-plugin-transform-react-remove-prop-types": "^0.4.13",
"babel-preset-env": "^1.7.0",
"babel-preset-react": "^6.24.1",
```

When I run my application in IE11 I get errors like `Object does not support property or method Symbol(Symbol.iterator)` which suggests that this feature is not getting polyfilled correctly.

If I remove `useBuiltIns` and just import all of babel-polyfill the errors stop. They also stop if I leave `useBuiltIns` set to `usage` and also import `core-js/fn/symbol/iterator.js` in my app's main entry point.

Should `core-js/fn/symbol/iterator.js` not be being imported automatically based on my configuration?

**Comment by zloirock** [comment]
This error is not related to `Symbol.iterator` and `core-js/fn/symbol/iterator` module. That means just that you try to iterate on something non-iterable.

**Comment by nicolo-ribaudo** [comment]
Closing per https://github.com/babel/babel/issues/8449#issuecomment-477422898
