### ISSUE TITLE
Aync iteration not working if Symbol.asyncIterator doesnt exist

### ISSUE THREAD

**Issue by julien-f** [babel/babel#8450]
## Bug Report

**Current Behavior**

Async iteration does not work if `Symbol.asyncIterator` does not exist.

**Input Code**
- REPL or Repo link if applicable: https://github.com/julien-f/babel-issue-async-iteration

```js
async function* gen() {
  yield 1;
}

async function main() {
  for await (const value of gen()) {
    console.log(value);
  }
}
main().catch(console.error.bind(console));
```

**Expected behavior/code**

Should display `1` and terminate.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "babel": {
    "plugins": [
      "@babel/plugin-proposal-async-generator-functions"
    ]
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-rc.1",
    "@babel/core": "7.0.0-rc.1",
    "@babel/plugin-proposal-async-generator-functions": "7.0.0-rc.1"
  },
  "main": "./dist/",
  "scripts": {
    "build": "babel -d ./dist/ ./src/"
  }
}

```

**Environment**
- Babel version(s): v7.0.0-rc.1
- Node/npm version: Node 8 & 10 / npm 6
- OS: Fedora 28
- Monorepo no
- How you are using Babel: CLI

**Possible Solution**

If `Symbol.asyncIterator` is not present, generated code should fallback to `'@@asyncIterator'`.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by julien-f** [comment]
Is there any news on this?

It currently is very difficult to create a library with async iterators/generators working on Node 6.

**Comment by wincent** [comment]
@julien-f, that's a nice and simple repro case. I came here when I found that this async generator function which works in Node v11 (untranspiled) didn't work when running it through `@babel/plugin-proposal-async-generator-functions`:

```javascript
async function* walk(directory, predicate = () => true) {
  const entries = await readdirAsync(directory, {withFileTypes: true});
  for (const entry of entries) {
    if (entry.isDirectory()) {
      for await (const nested of walk(
        join(directory, entry.name.toString()),
        predicate,
      )) {
        yield nested;
      }
    } else if (predicate(entry)) {
      yield join(directory, entry.name.toString());
    }
  }
}
```

Callers use it like this:

```javascript
for await (const file of walk(directory, isSourceFile)) {
  await callback(file);
}
```

So I rewrote it with callbacks instead:

```typescript
async function walk(
  directory: string,
  predicate: (entry: Dirent) => boolean,
  callback: (entry: string) => void,
) {
  const entries = await readdirAsync(directory, {withFileTypes: true});
  for (const entry of entries) {
    if (entry.isDirectory()) {
      await walk(join(directory, entry.name.toString()), predicate, callback);
    } else if (predicate(entry)) {
      await callback(join(directory, entry.name.toString()));
    }
  }
}
```

And you call it like this:

```javascript
await walk(directory, isSourceFile, callback);
```

**Comment by nicolo-ribaudo** [comment]
This is the expected behavior. `for await` should call `Symbol.asyncIterator` (and fallback to `Symbol.iterator`), and it should throw if it isn't defined.
You can check it by running this code in any modern browser:

```js
for await (const x of {}) console.log(x);
```

You need to provide a polyfill for `Symbol.asyncIterator`, either by including it directly or by asking your library's consumer to include it.
In the future, we will support polyfilling instance methods without polluting the environment with a global polyfill.
