### ISSUE TITLE
MeteorJS support & underscore

### ISSUE THREAD

**Issue by grigio** [babel/babel#846]
Hi, I've integrated [Babel in Meteor](https://github.com/grigio/meteor-babel) via NPM.
It seems underscore 1.0.2 is required, but Meteor already have it, are there alternative installations to avoid the [underscore compilation issue](https://github.com/grigio/meteor-babel/issues/3)?

**Comment by sebmck** [comment]
Sure is! Use the `babel-core` package that's a build of `babel` but without the CLI so it wont require the `chokidar` package which is what's causing the native dependency issues.

**Comment by grigio** [comment]
Thanks for the quick reply. Are you interested if I update your doc to add Meteor as platform where babel is integrated?

**Comment by sebmck** [comment]
As in moving it to the GitHub org?

**Comment by grigio** [comment]
I think here https://github.com/babel/babel.github.io/blob/master/docs/using-babel.md Just to mention how to install Babel in Meteor

**Comment by sebmck** [comment]
Ah yeah, sure.
