### ISSUE TITLE
Detecting derived `Error` class

### ISSUE THREAD

**Issue by ghostoy** [babel/babel#8460]
## Bug Report

**Current Behavior**
Some libraries, like `vue-router`, detect `Error` class by using `Object.prototype.toString.call(err).indexOf('Error') > -1`. Babel transformed code doesn't behave the same as native ES6 syntax.

**Input Code**

```js
class CustomError extends Error {
  constructor(...args) {
    super(...args);
  }
}
const err = new CustomError();
console.log(Object.prototype.toString.call(err)); // outputs: [object Object], expecting: [object Error]
```

**Expected behavior/code**
In native ES6 environment, it outputs `[object Error]`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@vue/app"]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.47
- Node/npm version: 10.7.0
- OS: Windows 10
- Monorepo yes
- How you are using Babel: vue-cli

**Possible Solution**

`CustomError.__proto__ = Error` will work.

**Additional context/Screenshots**

**Comment by nicolo-ribaudo** [comment]
What version are you using? Can you share an example? (e.g. on the repl)

**Comment by jungor** [comment]
I got undefined when accessing the `message` property on customError instance obj.
But it works on the repl. :smile:  
[repl here](http://babeljs.io/repl/#?babili=false&browsers=chrome%2068&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEDCCuEAuB7AtgUQE5ZV6ApgB5IEB2AJjNrvgN4BQ00wKZyW8wqWAFGhADmAGhYoKBAJTRGzZhHgAHAnwGDJTOUgAWASwgA6VhOgBeMRM0BfBjYYAzeGW6620eyhS9pjAJA7cAHdoMgJghGR0GjxeAHJSZFjRWIBONNiNOyQsAE8ZBl8PL0yWMCRgbWheKXzfMBAVJGqDNAIoMEEpWyYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Cflow&prettier=false&targets=&version=7.0.0-rc.4&envVersion=7.0.0-rc.1)
I was using version 7.0.0-beta.47, which generated by Vue Cli 3.0.1. Will goto the vue-cli project to suggess updating babel version. 3Q ~@nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
> Will goto the vue-cli project to suggess updating babel version. 

Thank you!

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/7020
