### ISSUE TITLE
class-private-methods aren't working in latest release

### ISSUE THREAD

**Issue by marcofugaro** [babel/babel#8484]
## Bug Report

**Current Behavior**
Whenever I try to set a private method babel complains with `Support for the experimental syntax 'classPrivateMethods' isn't currently enabled`

I am using all `-rc.1`, 

Wierd because I thought they were implemented in the parser [in this PR](https://github.com/babel/babylon/pull/703)

**Input Code**
```js
export default class AssetManager {
  #queue = []

  #getQueued(url) {
    return this.#queue.find(item => item.url === url)
  }
}

```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "useBuiltIns": "usage"
    }]
  ],
  "plugins": [
     "@babel/plugin-proposal-class-properties",
  ]
}
```

**Environment**
- Babel version(s): v7.0.0-rc.1
- Node/npm version: Node 10.7.0/npm 6.2.0
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: `loader`

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/7217420/44214335-2ee57980-a170-11e8-9293-c433e7b9b10a.png)

**Comment by nicolo-ribaudo** [comment]
Tracked at https://github.com/babel/babel/issues/8052!
