### ISSUE TITLE
"debug": true, "useBuiltIns": "usage" - Based on your code and targets, none were added.

### ISSUE THREAD

**Issue by joacim-boive** [babel/babel#8489]
## Feature Request

**Is your feature request related to a problem? Please describe.**
As our project is quite large and has many files - this message spams the terminal and drowns any useful information.

**Describe the solution you'd like**
I'd like an option to simply ignore this message - as I only care about what files have polyfills injected.
It would be great to have all the messages bunched up in one go and not printed as files are being processed, for easy scanning by a developer, but I suppose that would be hard to implement.

**Comment by xtuc** [comment]
The `debug` option is only meant for debug.

From what I understand, you're looking for a way to get a list of injected polyfill?
