### ISSUE TITLE
Export Class Throws an Error

### ISSUE THREAD

**Issue by john-cheesman** [babel/babel#849]
Don't know if this is an issue with Babel or Babelify. Apparently this doesn't work:

```
export class MyClass {
    ...
}
```

but this does:

```
class MyClass {
    ...
}

export default MyClass;
```
In the first example if you import the class and instantiate it you get something like:

```
TypeError: MyClass is not a constructor
```

**Comment by sebmck** [comment]
Do you have the entire stacktrace?

**Comment by sebmck** [comment]
That code compiles and runs fine so it's likely you're doing something wrong elsewhere. See the [REPL](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=export%20class%20MyClass%20%7B%7D).

**Comment by john-cheesman** [comment]
Sorry, didn't explain it very well. It compiles fine, no errors there. It's when you import it into another file and create a new instance that you get errors in the browser. If you try and extend it in another class you get an error about the parent constructor being an object when it should be a function or null.

I'll do an example and show the complied code when I get chance, thanks.

**Comment by sebmck** [comment]
You're likely importing it incorrectly. With your first example of:

```javascript
export class MyClass {
    ...
}
```

you'd request a named export called `MyClass` like so:

```javascript
import { MyClass } from "script.js";
```

and with your second example of:

```javascript
export default class MyClass {
    ...
}
```

you'd import it with a default import of:

```javascript
import MyClass from "script.js";
```

**Comment by john-cheesman** [comment]
yep! I was using the last example for both, thanks for clearing that up :smile:

**Comment by sebmck** [comment]
Ah great. No problem, more than happy to help! Feel free to open another issue if you run into anymore issues or check out our [gitter room](http://gitter.im/babel/babel).
