### ISSUE TITLE
alternative for airbnb/babel-plugin-dynamic-import-node

### ISSUE THREAD

**Issue by againksy** [babel/babel#8492]
## Feature Request
The problem is that the https://github.com/airbnb/babel-plugin-dynamic-import-node does not work with babel 7

Maybe there are some alternatives to this repo? Or maybe babel 7 will make it compatible ?

Today i tried to remove and install node_modules - and everything become broken - i assume its caused some updates in babel repositories. Because i have versions with caret symbols in babel plugins like here:
`    
{
"babel-plugin-dynamic-import-node": "^2.0.0",
    "babel-plugin-react-transform": "^3.0.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-runtime": "^6.11.6",
}
`
Also i have server side rendering and on server side this deps
`    "babel-plugin-dynamic-import-node": "^2.0.0",
    "babel-register": "^6.26.0",
    "babel-preset-es2015": "^6.24.1"
`
and now i should change every babel to 7  like mentioned in issue here https://github.com/react-bootstrap/react-bootstrap/issues/3231#issuecomment-414090514 
but the ` airbnb/babel-plugin-dynamic-import-node`  does not work with babel 7 =(
 
in https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/ it says that it cam be used Via Node API - but it does not alternative for airbnb/babel-plugin-dynamic-import-node ?

**Comment by nicolo-ribaudo** [comment]
You can use https://github.com/shelldandy/babel-plugin-dynamic-import-node-babel-7.

**Comment by againksy** [comment]
@nicolo-ribaudo seems i tried this repo> it does not work too

**Comment by againksy** [comment]
anyone can suggest what changed in v7 - that brokes support for that plugin? where to look for fix and support both v6 and v7 babel?

**Comment by vikr01** [comment]
airbnb/babel-plugin-dynamic-import-node#64 will resolve this.
