### ISSUE TITLE
Having hard time compiling async/await to polyfills [babel + webpack]

### ISSUE THREAD

**Issue by hyphen-wrex** [babel/babel#8495]
Having hard time tinkering with babel + webpack to make it compile to support older browsers. Babel plugins are not working, I bet there's problem in webpack config. Or may be some weird edge case bug crawled in the rc version of babel (7.0.0-rc1).

**Steps to reproduce:**

follow instructions in readme:
https://github.com/hyphen-wrex/babel-bug

**Expected result:**

code (async/await) is compiled down to es5 + polyfills are present

**Actual result:**

code is not compiled, older browsers (chrome 48, for instance) aren't able to pick up the code

*Thank you!*

**Comment by loganfsmyth** [comment]
What specifically are you seeing? When I run the steps in your repo, things appear to build properly and compile the async functions.

**Comment by loganfsmyth** [comment]
Could you post a gist of the `bundle.js` after `npm run build`? For me it loads and does not have any async functions in it.

**Comment by loganfsmyth** [comment]
(or alternatively just commit `bundle.js` into your repo.

**Comment by hyphen-wrex** [comment]
@loganfsmyth I've included `bundle.js` and couple of screenshots of what I'm seeing to the repo.

**Comment by loganfsmyth** [comment]
That's so strange. The only thing that comes to mind is https://github.com/hyphen-wrex/babel-bug/blob/master/webpack.common.js#L21

You're project isn't checked out somewhere inside of a `node_modules` or `bower_components` folder, is it?

If you want, you can try to add a tiny plugin that throws an exception, to make sure it actually runs and fails properly, e.g.

```

            plugins: [
              {
                visitor: {
                  Program(){
                    throw new Error("Something went wrong processing " + this.file.opts.filename);
                  }
                }
              }
            ],
```
at https://github.com/hyphen-wrex/babel-bug/blob/326241256fa64720fe7f050e07af300697f6b178/webpack.common.js#L42

**Comment by nicolo-ribaudo** [comment]
That `async` function comes from `react-dom`, I think (accordingly to the license comment). Maybe they are publishing untranspiled code?

**Comment by loganfsmyth** [comment]
Oh shoot, I'm not sure what I screwed up in my test, but this is just a mistake in the config. The async function is in https://github.com/hyphen-wrex/babel-bug/blob/master/src/config.js#L17 but the Webpack config in https://github.com/hyphen-wrex/babel-bug/blob/326241256fa64720fe7f050e07af300697f6b178/webpack.common.js#L20 only compiles `.jsx` files and that is a `.js` file. The test should just be

```
test: /\.jsx?/
```
