### ISSUE TITLE
`this.constructor` incorrect inside wrapped native constructors.

### ISSUE THREAD

**Issue by bicknellr** [babel/babel#8496]
## Bug Report

**Current Behavior**
`this.constructor` is incorrect inside wrapped native constructors on browsers that don't support `Reflect.construct`.

**Input Code**
https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAUCcFMBdoHYBNSwBYENagAYCVoAzAG2gGNYA6MgewQGdZIBXCnUAS3oQHJt7mAB0E1I8JJQBQAdw7Ia0ygRLlsAXlDNkROdCQBuSTLlIFlABIAVALIAZAKKkAtonWhCWihzoAKAJSgAN6SoKAgoObQMAA0uLLyilZ2jtAuCLDsXKhoWR4IXnSxCDTY6NCgohwA5nIYxBE2Ds6uIWFgtAxMrLCilLjoXNR0jCwUouz0aDTMxCgARuUD9O6esN4IqDQ0sXPM2Fy8VK0d9DSklMQ0VT5LQ52jPZCgai-g8aaJjSlp2AD8oAAiQgYDjEAGgABcgMEGHo9ABfkMAF9DJIyMxGDQnN9XPRKEgdAhoD4eE4AJ4AWmgzXSPFiZGIsOW0AAHvBkMskk1Uq4gkjEZJTOiftQYFhoDj0iTyVSabAeIigA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017&prettier=false&targets=&version=7.0.0-rc.1&envVersion=

**Expected behavior/code**
`this.constructor` should refer to the original constructor for the object.

**Babel Configuration (.babelrc, package.json, cli command)**
Whatever is used by the REPL.

**Environment**
- Babel version(s): v7.0.0-rc.1
- How you are using Babel: REPL

**Additional context**
This seems to be a result of the replacement used for `Reflect.construct`: https://github.com/babel/babel/blob/f8b0a5579f9765dc959658759f895e4e01820189/packages/babel-helpers/src/helpers.js#L486-L493
This bug prevents our [custom elements polyfill](https://github.com/webcomponents/custom-elements) from knowing the original constructor being called, which prevents it from looking up the definition of the element and upgrading it properly.

cc @justinfagnani

**Comment by TimvdLippe** [comment]
Please also note that this was a regression introduced in beta 36. For more info see https://github.com/Polymer/tools/pull/216

**Comment by nicolo-ribaudo** [comment]
We could add a check in `_wrapNativeSuper`: if the argument isn't actually a native function, it should be returned without wrapping.
