### ISSUE TITLE
wrong behavior in for loop

### ISSUE THREAD

**Issue by uni-zheng** [babel/babel#8498]
## Bug Report

**Current Behavior**
Just print log once.

**Input Code**
- REPL or Repo link if applicable:

```js
for (let i = 0; i < 3; i++) {
  let i = 'abc';
  console.log(i);
}
```

**Output Code**
```js
"use strict";

for (var i = 0; i < 3; i++) {
  var i = "abc";
  console.log(i);
}
```

**Expected behavior/code**
print log 3 times

**Environment**
use https://new.babeljs.io/repl
set presets both es2015 and stage-3
version v6.26.0

**Possible Solution**
Should create temporary variable in body.

**Comment by byronluk** [comment]
Hi I'm going to try to look at this. Thanks!

**Comment by byronluk** [comment]
@nicolo-ribaudo Is it a better choice to add a closure inside the block scope or to rename the block scoped variable that is colliding with the for loop initializer?

**Comment by nicolo-ribaudo** [comment]
Renaming the variable would be better, but if it is too complex we can just wrap the for body in a block, like in https://github.com/babel/babel/pull/8920, since it isn't a common case.
