### ISSUE TITLE
[v7.0.0-rc.1] Wrong function name exported in some cases

### ISSUE THREAD

**Issue by dtinth** [babel/babel#8499]
## Bug Report

**Current Behavior**
When certain conditions are met, Babel **renames** the exported function name, making the module unusable.

**Input Code**

```js
export function problem(problem) { return 42 }
void { problem: () => problem() }
```

> Note: The unary `void` is not part of the issue. The problem appears whenever `{ problem: () => problem() }` is present in the source code:
>
> ```js
> export function problem(problem) { return 42 }
> ;({ problem: () => problem() })
> ```

**Expected behavior/code**
This module should export a binding named `problem`.

```js
function _problem(problem) {
  return 42;
}

export { _problem as problem };
void {
  problem: function problem() {
    return _problem();
  }
};
```

**Actual behavior/code**
A binding named `_problem` is exported instead, causing users of this module to encounter an error when importing the `problem` binding.

```js
export function _problem(problem) {
  return 42;
}
void {
  problem: function problem() {
    return _problem();
  }
};
```

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{ "presets": [ [ "@babel/env", { "modules": false } ] ] }
```

**Environment**
- Babel version(s): v7.0.0-rc.1
- Node/npm version: Node v10.8.0
- OS: macOS 10.13.2
- Monorepo: no
- How you are using Babel: `cli`

```json
{
  "dependencies": {
    "@babel/cli": "^7.0.0-rc.1",
    "@babel/core": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1"
  }
}
```

**Additional context**
If I change any instance of the word `problem` to something, the problem is gone.

1. Change function name

    ```js
    // in
    export function noProblem(problem) { return 42 }
    void { problem: () => noProblem() }

    // out
    export function noProblem(problem) {
      return 42;
    }
    void {
      problem: function problem() {
        return noProblem();
      }
    };
    ```

2. Change parameter name

    ```js
    // in
    export function problem(noProblem) { return 42 }
    void { problem: () => problem() }

    // out
    function _problem(noProblem) {
      return 42;
    }

    export { _problem as problem };
    void {
      problem: function problem() {
        return _problem();
      }
    };
    ```

3. Change method name

    ```js
    // in
    export function problem(problem) { return 42 }
    void { noProblem: () => problem() }

    // out
    export function problem(problem) {
      return 42;
    }
    void {
      noProblem: function noProblem() {
        return problem();
      }
    };
    ```

4. Change called function name

    ```js
    // in
    export function problem(problem) { return 42 }
    void { problem: () => noProblem() }

    // out
    export function problem(problem) {
      return 42;
    }
    void {
      problem: function problem() {
        return noProblem();
      }
    };
    ```

If I use `export const` instead of `export function`, the problem is gone:

5. Example

    ```js
    // in
    export const problem = function problem(problem) { return 42 }
    void { problem: () => problem() }

    // out
    var _problem = function problem(problem) {
      return 42;
    };

    export { _problem as problem };
    void {
      problem: function problem() {
        return _problem();
      }
    };
    ```

**Comment by xtuc** [comment]
The `void { ... }` is definitely not a common use case. It seems to work on v7.0.0-beta.41, so it's a regression. Also note that It seems to work without the Unary void. (I did my tests in the REPL, where I could disable the module transform).

**Comment by dtinth** [comment]
@xtuc You are correct. The unary `void` is not part of this issue. I updated the issue with this note.

> Note: The unary `void` is not part of the issue. The problem appears whenever `{ problem: () => problem() }` is present in the source code:
>
> ```js
> export function problem(problem) { return 42 }
> ;({ problem: () => problem() })
> ```

Also including these cases:

```js
export function problem(problem) { return 42 }
f({ problem: () => problem() })
```

```js
export function problem(problem) { return 42 }
let x = { problem: () => problem() }
```

```js
export function problem(problem) { return 42 }
function f() {
  return { problem: () => problem() }
}
```

**Comment by loganfsmyth** [comment]
Definitely a bug, nice catch.

I can dig in more in the morning if no-one else gets to it, but stepping through things, if we change https://github.com/babel/babel/blob/f8b0a5579f9765dc959658759f895e4e01820189/packages/babel-traverse/src/scope/lib/renamer.js#L111 to `getOuterBindingIdentifiers` (with `Outer`), your snippet transforms properly. Seems like we might just be missing that case.
