### ISSUE TITLE
TCO malfunction with SwitchStatement

### ISSUE THREAD

**Issue by ikarienator** [babel/babel#850]
```js
function a() {
  switch(a) {
    case 0:
      return a();
  }
}
```

generates:
```js
function a() {
  _function: while (true) {
    switch (a) {case 0:
        continue _function;
    }
  }
}
```

whereas it should generate:
```js
function a() {
  var _again = true;
  _function: while (_again) {
    _again = false;
    switch (a) {
    case 0:
        _again = true;
        continue _function;
    }
  }
}
```

**Comment by sebmck** [comment]
Same issue as #822 I take it?

**Comment by sebmck** [comment]
Although I like your suggestion rather than just slapping on a `return`. I'll push out a patch.

**Comment by ikarienator** [comment]
Cool! It's exciting to see TCO working in babel!

**Comment by sebmck** [comment]
Fixed as of 4.4.0, thanks!

Ping @disnet, may be the issue that you were running into.

**Comment by disnet** [comment]
@sebmck sadly no, still a problem for me.

**Comment by ikarienator** [comment]
@disnet Can you make an example of the failed case?

**Comment by sebmck** [comment]
@ikarienator It's somewhere in [this](https://github.com/mozilla/sweet.js/blob/es6-modules/src/expander.js#L638) function...
