### ISSUE TITLE
@babel/register does not respect the .babelrc file in a node_module/

### ISSUE THREAD

**Issue by alexrhogue** [babel/babel#8503]
## Bug Report

**Current Behavior** 
@babel/register does not seem to respect the .babelrc file in a node_module.  This causes babel to not use the specified presets and plugins to compile the code, resulting in errors.  Attached is a simple project that demonstrate this behavior.  

**Input Code**

See the README for instructions on how to test
https://github.com/alexrhogue/babel-7-rc-test

When we try to run the code we get the following error in babel:
```bash
~/github/babel-7-rc-test (master) $ npm start

> babel-7-rc-test@1.0.0 start /Users/alexhogue/github/babel-7-rc-test
> node index.js

/Users/alexhogue/github/babel-7-rc-test/node_modules/fake-module/target.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/Users/alexhogue/github/babel-7-rc-test/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/alexhogue/github/babel-7-rc-test/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Expected behavior/code**
@babel/register should successfully find and use the .babelrc of a node_module as described here: https://babeljs.io/docs/en/next/babelrc

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
	"presets": [
		["env", {
			"targets": {
			  "node": "current"
			}
		}]
	],
	"plugins": [
		"@babel/plugin-syntax-export-default-from",
		"babel-plugin-syntax-dynamic-import"
	]
}
```
**Babel register**

```js
require('@babel/register')({
	ignore: []
});
```

**Environment**
- Babel version(s): ^7.0.0-rc.1
- Node/npm version: Node v8.11.1 / npm 5.6.0
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: register

**Comment by loganfsmyth** [comment]
> `@babel/register` does not seem to respect the .babelrc file in a node_module.

This is a purposeful change in Babel 7, because we have no way to know if a random `.babelrc` in `node_modules` is for Babel 7 instead of Babel 6, or if the plugins referenced in it are even installed, since often they are only `devDependencies`.

You can opt into the behavior you're looking for with the `babelrcRoots` options, e.g.

```
require('@babel/register')({
  ignore: [],
  babelrcRoots: [
    ".",
    "./node_modules/fake-module",
  ],
});
```

**Comment by alexrhogue** [comment]
Thank you. I did not see anything about this in the upgrade guide (https://babeljs.io/docs/en/next/v7-migration.html)  Maybe I missed it.  If not, do you think it may be helpful to add?

**Comment by loganfsmyth** [comment]
Good call. I'll take a look and see what I can add.

**Comment by loganfsmyth** [comment]
FYI, new docs coming in https://github.com/babel/website/pull/1787

**Comment by alexrhogue** [comment]
Awesome!
