### ISSUE TITLE
classes extends Object lost their functions after compile

### ISSUE THREAD

**Issue by zhangmin93** [babel/babel#8506]
## Bug Report

**Current Behavior**
Compling `class A extends Object` into es2015 stander, make functions defined in A no longer accessable for A's instances

**Input Code**

```js
class A extends Object{
    foo(){
      console.log(123)
    }
}
```
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjA8gIwCsFgUBvAKAEgAzAe1oAoBKC6N94W9CWkBAOhC0A5gwCMAJgDMTcu2gBfckqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-0%2Ces2015-loose&prettier=false&targets=&version=6.26.0&envVersion=

**Expected behavior/code**
As class A defined above, following usage shoule be legal
```js
var a = new A()
a.foo()
```
But using the compile result code, `a.foo` is `undefined`

**Babel Configuration (.babelrc, package.json, cli command)**
i was using the offically online compiler

**Environment**
- Babel version(s): [6.26.0]

**Comment by nicolo-ribaudo** [comment]
Babel 6 didn't support extending built-in objects; this feature has been implemented in Babel 7 (https://babeljs.io/repl/build/master).

**Comment by suchipi** [comment]
I'll close this since this has been fixed in 7.
