### ISSUE TITLE
Non default exporting ES6 Module

### ISSUE THREAD

**Issue by iammerrick** [babel/babel#851]
The new __esModule flag is great but unfortunately doesn't offer true interoperability with traceur generated source as promised. This happens when a traceur module doesn't export a default property, perhaps it exports a collection of properties and tags the module __esModule. Babel then reads the flag __esModule and requires a default property, even if one doesn't exist.

# Example

Traceur Compiled Module

```javascript
function hi() {
}

export { hi }
```

Compiles to:

```javascript
function hi() {}

module.exports = {
  hi: hi,
  __esModule: true
}
```

Babel then attempts to read the default property even though one does not exist.

**Comment by iammerrick** [comment]
Ahhh named imports.... :-)

**Comment by sebmck** [comment]
:stuck_out_tongue_winking_eye:
