### ISSUE TITLE
Child class properties are assigned after parent constructor is executed

### ISSUE THREAD

**Issue by jedlikowski** [babel/babel#8510]
## Bug Report

**Current Behavior**
Let's say we create a class named **A** with default class property `name='123'` . Class A also sets the `name` property to `456` if `setName` argument is passed to it's constructor. Then we create a class named **B** which extends class **A** and has default value for `name` set to `null`. After we create a new instance of **B** and pass `true` as the `setName` argument to the constructor, `name` is still `null`.

Basically class properties in child classes are assigned to the instance of the child class after the parent constructor is executed. They are not treated as default values.

**Input Code**
```js
class A {
  name = '123';

  constructor(setName = false) {
    if (setName) {
      this.name = '456';
    }
  }
}

class B extends A {
  name = null;
}

console.log(new B(true)); // {name: null} <-- bad
console.log(new B(false)); // {name: null} <-- good
```

**Expected behavior/code**
I expected the child class properties to be defined after parent class properties (maybe even instead of them if there would be double declaration with different values), but before parent constructor is executed.
I would expect and instance of `B(true)` to have `name` property set to `456` and `B(false)` to have `name` property set to `null`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry"
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-react-jsx",
    "@babel/plugin-transform-runtime", 
    ["@babel/plugin-proposal-class-properties", {"spec": true}],
    [     
      "module-resolver",
      {
        "root": [
          "./resources/src/"
        ],
        "extensions": [
          ".js",
          ".jsx"
        ]
      }
    ]
  ],
  "env": {
    "development": {
      "plugins": [
        "inline-dotenv"
      ]
    },
    "production": {
      "plugins": [
        "transform-inline-environment-variables"
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 7.0.0-rc.1
- Node/npm version: Nodee v8.11.3, npm 5.6.0
- OS: OSX 10.13.6
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
It is correct. Class fields should be initialized after calling the paren't `super()`, so after that the parent constructor is executed.

You can tes it on the latest node verson:
```
~ via ⬢ v10.9.0 
➜ cat demo.js
class A {
  name = '123';

  constructor(setName = false) {
    if (setName) {
      this.name = '456';
    }
  }
}

class B extends A {
  name = null;
}

console.log(new B(true)); // {name: null} <-- bad
console.log(new B(false)); // {name: null} <-- good


~ via ⬢ v10.9.0 
➜ node --harmony-class-fields demo.js 
B { name: null }
B { name: null }

```

**Comment by jedlikowski** [comment]
If I applied the same pattern for example in PHP, the result would be how I expected. So this counter-intuitive behaviour is actually by design in the spec?

**Comment by nicolo-ribaudo** [comment]
Yes. It can't be done before calling `super()` because `this` is the return value of super. Before, `this` doesn't exists so class fields can't be defined.
