### ISSUE TITLE
Minified babel Standalone package throws error on legacy non-UTF8 encoding environment

### ISSUE THREAD

**Issue by kphillisjr** [babel/babel#8515]
## Bug Report

**Current Behavior**
The minified babel.js ( babel.min.js ) fails to run properly on local machines. 

**Input Code**

```HTML
<html><head></head><body>
<div id="output"></div>
<script src="scripts/babel.min.js" > </script>
<script type="text/babel">
const getMessage = () => "Hello World";
document.getElementById('output').innerHTML = getMessage();
</script>
</body></html>
```

**Expected behavior/code**
The text "Hello world" to appear in my browser window like what happens when I use the large copy of babel.js.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 5 versions", "safari >= 7", "firefox >=61"]
      }
    }]
  ]
}
```

**Environment**
- Babel version(s): (Standalone 1.0.0), 6.4.4,  6.26.0
- Node/npm version: Not applicable. Standalone package.
- OS: Windows 10
- Monorepo - No. Downloaded copy.
- How you are using Babel: standalone package
- Runtime Environment: 
  - Mozilla Firefox version 61.0.2 (64-bit)
  - Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
  - Microsoft Edge version 42.17134.1.0
  - Internet Explorer 11 version 11.228.17134.0

**Possible Solution**
No idea.

**Additional context/Screenshots**

I was trying to use local copies of the standalone babel.js package. This means I had the following Files:

**File 1:** scripts/babel.min.js - This is a copy of https://unpkg.com/babel-standalone@6.26.0/babel.min.js
**File 2:** scripts/babel.js - This is a copy of https://unpkg.com/babel-standalone@6.26.0/babel.js (as a quick note, this file works oddly enough)

As a quick note, when I use babel.js the script works regardless of browser.

**Edit** Updated the minimum version. The problem appears to effect all versions of the standalone babel.min.js since I even tried version babel-standalone version 1.0.0, and 6.4.4 with failures in both cases.

**Comment by loganfsmyth** [comment]
Could you try
```
<script src="scripts/babel.min.js" > </script>
```
as
```
<script src="scripts/babel.min.js" charset="utf-8"> </script>
```

**Comment by HiteshRajpal** [comment]
Hi Team , I am also facing the same error , Access to XMLHttpRequest at 'file:///D:/path/to/index.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https., 

any solution is there then please help

**Comment by ssakethraj** [comment]
@HiteshRajpal Run your html file on http web server. Just like @joe-oli mentioned  babel-standalone need web server to access javascript in external `.js` file

**Comment by JLHwung** [comment]
The OP's issue is resolved by adding `charset="utf-8"` to the `<script>` tag. For those who can not load `@babel/standalone` due to CORS restriction, see [here](https://dev.to/dengel29/loading-local-files-in-firefox-and-chrome-m9f) for how to allow access for local files.
