### ISSUE TITLE
IE errors: Object doesn't support property or method 'Symbol(Symbol.iterator)_8.9s04yyuxk19 (T7087) #4075

### ISSUE THREAD

**Issue by ibama2** [babel/babel#8521]
Bug information
Babel version: 6.0.12
Node version: 5.4.1
npm version: 3.3.12
Options
sourceMap: false,
presets: ['es2015']
Input code
for (let frame of <array>) {
  ..
}
Description
Hi,

this happens on Internet Explorer only. babel-polyfill is included.

**Comment by ibama2** [comment]
don't use for XX of, i changed it then this error vanished

**Comment by loganfsmyth** [comment]
Would you be able to create a reproducible example? That very much sounds like `babel-polyfill` has not been loaded, but it's hard to give more specific advice without a functional example.

**Comment by zloirock** [comment]
Sounds like at least a part of `core-js` has been loaded, but you try to iterate over something non-iterable.
