### ISSUE TITLE
Breaks the swapping of variable values using array destructuring.

### ISSUE THREAD

**Issue by plegner** [babel/babel#8528]
## Bug Report

**Current Behavior**
Babel breaks the swapping of two variable values using array destructuring. This only seems to happen if the two values to be swapped are also function arguments.

**Input Code**
Correct Behaviour: [REPL version 7.0.0-beta.39](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgIQKZQO4Y2ACgA8AaRAQzICMBKRAbwChFlhEDzEA-RWxAbUq8AuogC8AqmXLCA3M0QAnLCEVIi3CogBk2xBoA8veQF9GQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.39&envVersion=7.0.0-beta.39)

Incorrect Behaviour: [REPL version 7.0.0-rc.2](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgIQKZQO4Y2ACgA8AaRAQzICMBKRAbwChFlhEDzEA-RWxAbUq8AuogC8AqmXLCA3M0QAnLCEVIi3CogBk2xBoA8veQF8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-rc.2&envVersion=7.0.0-rc.2)

```js
function isBetween(x, a, b) {
  if (a > b) [a, b] = [b, a];
  return x > a && x < b;
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [['@babel/preset-env', {
    targets: {browsers: ['> 1%', 'not ie <= 11', 'not ios < 10']},
    modules: false,
    useBuiltIns: false,
    loose: true
  }]]
};
```

**Environment**
- Babel version: v7.0.0-rc.2
- Node/npm version: Node 8/npm 5

**Comment by hzoo** [comment]
Great thanks for the report, can you determine the first version that it doesn't work to figure out which commit/pr caused the issue? Based on the info you gave it's between `7.0.0-beta.39` and `rc.2`, not necessarily introduced in `rc.2`

**Comment by plegner** [comment]
It seems to be working correctly in [beta.43](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgIQKZQO4Y2ACgA8AaRAQzICMBKRAbwChFlhEDzEA-RWxAbUq8AuogC8AqmXLCA3M0QAnLCEVIi3CogBk2xBoA8veQF9GQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.43&envVersion=7.0.0-beta.42), but no longer in [beta.45](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgIQKZQO4Y2ACgA8AaRAQzICMBKRAbwChFlhEDzEA-RWxAbUq8AuogC8AqmXLCA3M0QAnLCEVIi3CogBk2xBoA8veQF9GQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.45&envVersion=7.0.0-beta.44).

**Comment by rickbeerendonk** [comment]
It happens to me with normal variables as well, not only function arguments:

```js
let a = 1;
let b = 2;
	
[a, b] = [b, a]; 
	
console.log(a); // 2
console.log(b); // 2
```

**Comment by nicolo-ribaudo** [comment]
@rickbeerendonk Can you share an example on the REPL? It seems to work: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAhhC8EEYDcAoUkBGcICZUEgUBtKAGggwF1siNypKkIVCBjAewDsBnd0AOmDsA5gAooASiYB6abhQcefEIJGiMUiLNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-rc.3&envVersion=7.0.0-rc.3
