### ISSUE TITLE
@babel/plugin-syntax-pipeline-operator rc.3 is not published to npm

### ISSUE THREAD

**Issue by vicapow** [babel/babel#8532]
`@babel/plugin-syntax-pipeline-operator` version rc.3 is not published to npm but `@babel/plugin-proposal-pipeline-operator` rc.3 which is published depends on it. This fails installations when using yarn and pure-lock file.

`yarn --frozen-lockfile --non-interactive`

````
documentation (update-babel) $ yarn --frozen-lockfile --non-interactive
yarn install v1.9.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "@babel/plugin-syntax-pipeline-operator@7.0.0-rc.3". Ignoring it.
error Couldn't find any versions for "@babel/plugin-syntax-pipeline-operator" that matches "7.0.0-rc.3"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
````

**Comment by loganfsmyth** [comment]
Oh weird, let me take a look now.

**Comment by vicapow** [comment]
fwiw, I was able to work around this by using yarn resolutions

````
  "resolutions": {
    "@babel/plugin-syntax-pipeline-operator": "7.0.0-rc.2"
  },
````

**Comment by loganfsmyth** [comment]
Cool. I'm going to manually publish that single package since it somehow failed to publish, just running the local build now.

**Comment by loganfsmyth** [comment]
It's now been published.
