### ISSUE TITLE
babel-cli not getting installed in local node_modules/.bin

### ISSUE THREAD

**Issue by macdougall** [babel/babel#8538]
## Bug Report

npm install --dev-save babel-cli

**Expected behavior/code**
Would have expected the babel cli be located in node_modules, it wasn't.
The babel symlink wasn't placed in the node_modules/.bin
The folder for babel was not created.

If I run this as:

npm install -g babel-cli 

It will get installed in my global npm location.

If I run with:

sudo npm install --dev-save babel-cli

It will install -- of course this is not really the right way to do things.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0"
  }
}```

**Environment**
- Babel version(s): 6.0
- Node/npm version: 6.4.0
- OS: OSX 10.13.6
- Monorepo no
- How you are using Babel: 'cli`

**Comment by macdougall** [comment]
Just tried the same action on Ubuntu, same npm version (6.4.0) and it worked fine.

**Comment by loganfsmyth** [comment]
Babel doesn't really control this, it's an `npm` feature. Sounds like maybe you have the wrong permissions set somewhere, but I'm not really sure. I'd delete your whole `node_modules` and reinstall without `sudo`.
