### ISSUE TITLE
cli and register: sub-packages are not compiled, .babelrc ignored

### ISSUE THREAD

**Issue by michael-brade** [babel/babel#8550]
## Bug Report

**Current Behavior**
Using the following directory structure:
```
package.json
server.js
components/cmp1/package.json
components/cmp1/.babelrc
components/cmp1/core.js
```
Babel CLI and babel register ignore the sub-package in `components/cmp1`. For some reason, the only way to get it to work is if the contents of `.babelrc` are passed directly to `@babel/register`. Below you will find the code, but first the detailed errors and outputs.

It is not possible to compile `core.js` from the root directory using the CLI:
```
$ babel components/cmp1/core.js
import path from 'path';
console.log(path.basename("test.js"));
```
This should have transformed the `import` statement.

Neither is it possible to `require` the file using `@babel/register` if you don't pass any options to it:
```sh
$ npm start
> babel-bug@ start /babel-bug
> node server.js

/babel-bug/components/cmp1/core.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (/babel-bug/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/babel-bug/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babel-bug@ start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-bug@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-08-27T11_02_54_837Z-debug.log
```

**Input Code**

`server.js`:
```js
require('@babel/register')
// ({        // BUG: without options, core.js is not transformed! Even thought there is a .babelrc
//     "presets": [
//       [
//         "@babel/preset-env",
//         {
//           "targets": {
//             "node": "current",
//             "browsers": "> 0.5%, not dead"
//           }
//         }
//       ]
//     ]
// });

require('./components/cmp1/core.js');
```

`components/cmp1/core.js`:
```js
import path from 'path';
console.log(path.basename("test.js"));
```

**Expected behavior/code**
I would expect the following:
* `@babel/register` looks into the closest `.babelrc` and/or `package.json` and uses that config
* babel CLI works from the root directory and compiles the given file(s) according to the nearest config

After I `cd components/cmp1`, babel CLI correctly complains about multiple configuration files  (package.json and .babelrc), so I would also expect it to do the same when called from the root, but it doesn't, it just ignores both.

**Babel Configuration (.babelrc, package.json, cli command)**

`package.json`
```js
{
  "name": "babel-bug",
  "scripts": {
    "start": "node server.js"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-rc.3",
    "@babel/preset-env": "7.0.0-rc.3",
    "@babel/register": "7.0.0-rc.3"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current",
            "browsers": "> 0.5%, not dead"
          }
        }
      ]
    ]
  }
}
```

`components/cmp1/package.json`
```js
{
  "name": "component",
  "devDependencies": {
    "@babel/core": "7.0.0-rc.3",
    "@babel/register": "7.0.0-rc.3",
    "@babel/preset-env": "7.0.0-rc.3"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current",
            "browsers": "> 0.5%, not dead"
          }
        }
      ]
    ]
  }
}
```

`components/cmp1/.babelrc`
```js
{
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current",
            "browsers": "> 0.5%, not dead"
          }
        }
      ]
    ]
}
```

**Environment**
- Babel version(s): v7.0.0-rc.3
- Node/npm version: Node 10.9/npm 6.2
- OS: Linux
- How you are using Babel: `cli`, `register`

**Comment by slyshadow** [comment]
Nice release candidate guys! I'm having the same problem too

**Comment by rzr** [comment]
workaround run babel with:

```
 ./node_modules/.bin/babel 
--no-babelrc \
--config-file "${PWD}/.babelrc" \
--delete-dir-on-start \
--ignore 'node_modules/**,dist/**' \
-d "dist" \
--verbose 
```

My 0.02 EUR

**Comment by jsg2021** [comment]
@michael-brade as of 7, it's not supposed to. It was explicitly removed so that we can compile node_modules safely using the ROOT config.

**Comment by michael-brade** [comment]
@jsg2021 hm, I don't quite understand... it is not supposed to do what? To read the nearest `.babelrc` if there is a `package.json`? What does that have to with `node_modules`? It could still ignore the local configs if the current path contains `node_modules`, but that is not the case here.

**Comment by michael-brade** [comment]
@jsg2021 plus, simply calling `$ babel components/cmp1/core.js` doesn't work at all. I don't think this is intentional since I do have a ROOT config... (in `package.json`)

**Comment by jsg2021** [comment]
@michael-brade babel 7 will not resolve config per file, it will use the config it was started with. So, no it will not read the nearest config when reading your sub-modules... it will read the root and use that config for all compiles.

**Comment by loganfsmyth** [comment]
Hey all, mostly this is an issue of documentation. It is indeed expected behavior, because we ask people to opt into more complex `.babelrc` setups now.

Babel 7 has a concept of the "root" package, which is the only one that will have `.babelrc` files used, and this root is defined by the current working directory of the CLI command. This is why changing directory affects your config.

I'm going to be working on expanding the docs around all this today.

**Comment by michael-brade** [comment]
@loganfsmyth Great, that helps indeed! The docs currently don't explain that.

But that does leave the question if you can still have a babel config in the root `package.json`, and if so, why neither babel CLI nor babel-register will read it (see the report).

**Comment by michael-brade** [comment]
Ah, yes, I got distracted by other work. Thank you very much for your explanations and the docs! I now understand the reason behind the change and I think I like it.

To confirm my understanding regarding merging: merging of configs only happens in subdirectories that do not contain any additional `package.json` (or if those packages are added to the roots), so in my case, if I deleted the `components/cmp1/package.json`, then `components/cmp1/.babelrc` would be read and merged without having to add another root or any other configuration. Correct?

Some more fixes for the docs:

- Another typo probably: [here](https://babeljs.io/docs/en/babelconfigjs) at the end of the first paragraph, the link "specifying the root folder" is dead

- https://babeljs.io/docs/en/babel-register still claims: "But note that the closest .babelrc to each file still applies, and takes precedence over any options you pass in here." Maybe add here that this is the case only if the file belongs to the root package? Or something like that.

Then I have one question left: 

Why doesn't `babelrcRoots` work in the root `package.json`, nor the root `.babelrc`? Where can it be used, and where is that documented? The reason I would like it to read those files is because then I could keep all my configuration in one place (package.json) instead of having one roots definition for the CLI and one for babel-register, and then yet another location with the actual babel config.

**Comment by loganfsmyth** [comment]
> if I deleted the components/cmp1/package.json, then components/cmp1/.babelrc would be read and merged without having to add another root or any other configuration. Correct?

That's correct, though definitely not something I'd recommend actually doing.

> Why doesn't babelrcRoots work in the root package.json, nor the root .babelrc? Where can it be used, and where is that documented?

That option can be used either in Babel's programmatic options, or in a project-wide config file. The placement is called out in https://babeljs.io/docs/en/next/options#babelrcroots but I'll get that copied over to the `7.0.0` docs soon. It can't work in a `.babelrc` or `package.json` file because Babel wont have even tried to load those files.

> The reason I would like it to read those files is because then I could keep all my configuration in one place (package.json) instead of having one roots definition for the CLI and one for babel-register, and then yet another location with the actual babel config.

The easiest way to have one central config is to use a `babel.config.js` file and then ensure that it is used during all your compilation steps.

**Comment by michael-brade** [comment]
Nice, the docs are pretty good now! Thanks, I will move to a `babel.config.js`. 

Now, just for good measure, here is another typo in https://babeljs.io/docs/en/next/options#babelrcroots :)

> For example, a monorepo setup that wishes to allow individual packages to have their own configs might with to do

=> s/with/want/
