### ISSUE TITLE
@babel/register uses an outdated version of source-map-support

### ISSUE THREAD

**Issue by novemberborn** [babel/babel#8551]
## Bug Report

**Current Behavior**
`@babel/register` uses an outdated version of `source-map-support`. It's pinned to `^0.4.2` which excludes the latest release: `0.5.9`. This also means an outdated version of `source-map` is used.

**Input Code**
https://github.com/babel/babel/blob/1ac46a256d5e78ff83e150f46cf05acfb9489967/packages/babel-register/package.json#L19

**Expected behavior/code**
`source-map-support` should be pinned to `^0.5.9` which in turn would update `source-map` to `0.6.1`, the latest version that supports Node.js 6.

This is causing rather confusing behavior with AVA. See https://github.com/avajs/ava/issues/1899#issuecomment-416204989 for my latest investigation.

**Comment by LinusU** [comment]
Hello 👋 

Maintainer of `source-map-support` here. The only breaking change was bumping `source-map` to `^0.6.0`: https://github.com/evanw/node-source-map-support/compare/v0.4.18...v0.5.0

**Comment by hzoo** [comment]
Hey Linus! I'm curious what the changelog for source-map itself is for 0.6 😂https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#056, I know 0.7 is webassembly and dropping node 6. We'd have to update babel's use of `source-map` as well

**Comment by novemberborn** [comment]
We could do a `source-map` fork and republish it, so that we can have a wrapper that supports Node.js 6 as well as newer releases.

Looking at the commits I don't think there were any breaking changes: https://github.com/mozilla/source-map/compare/0.5.7...0.6.1

**Comment by hzoo** [comment]
Ok then I think we can go ahead and just update everything 0.6.x and also source-map-support?

**Comment by novemberborn** [comment]
Thanks for getting this in at the last minute, @hzoo ❤️
