### ISSUE TITLE
.plugins must be an array, or undefined

### ISSUE THREAD

**Issue by vyushin** [babel/babel#8564]
### Bug report

It happens after upgrade Babel to 7.0

```
ERROR in ../node_modules/css-loader/lib/css-base.js
Module build failed: Error: .plugins must be an array, or undefined
```

**Comment by loganfsmyth** [comment]
You'll need to include your Babel config and Webpack configuration for `babel-loader`.

**Comment by vyushin** [comment]
@loganfsmyth, thanks! You're right, it's string instead an array in webpack.config.js
