### ISSUE TITLE
TypeScript -> Tsickle -> Babel 7 ->  Google Closure Compiler = "God Mode" compression

### ISSUE THREAD

**Issue by orenmizr** [babel/babel#8568]
**problem**- huge codebase for large applications. 
typescript files **transformed by babel** + **annoated by tsickle** +  **transformed by babel 7** than **compressed by closure compiler** is without a doubt the greatest compression ratio we can achieve today. 

the setup and edge cases made it very hard solution to implement. i am hoping the integration with typescript team will allow **plugins that will help with this described pipeline**. 

has anyone attempted this ?

**Comment by nicolo-ribaudo** [comment]
I'm cleaning up old issues, and I'm closing this since it's not a bug or feature request for Babel.
