### ISSUE TITLE
'decoratorsBeforeExport' can't be used with legacy decorators.

### ISSUE THREAD

**Issue by mspoerer** [babel/babel#8569]
## Bug Report

**Current Behavior**
As the documentation describes, the @babel/plugin-proposal-decorators can be configured through the parameters: decoratorsBeforeExport and legacy.
Somehow the combination of decoratorsBeforeExport: true & legacy: true throws an error.

Line of Code:
https://github.com/babel/babel/blob/eac4c5bc17133c2857f2c94c1a6a8643e3b547a7/packages/babel-plugin-proposal-decorators/src/index.js#L25

**Comment by mspoerer** [comment]
It seems that the documentation is somehow wrong. The default value of the parameter *decoratorsBeforeExport* is true and not false.

**Comment by nicolo-ribaudo** [comment]
The documentation is wrong because it doesn't have a default value. It can only be used if you are using `legacy: true` (so it can never be used until we support `legacy: false`).
