### ISSUE TITLE
/* jsx React.DOM */ comment - unnecessary?

### ISSUE THREAD

**Issue by tmcw** [babel/babel#857]
```jsx
<Foo />
```

compiles into

```js
"use strict";
React.createElement(Foo, null);
```

whereas

```jsx
/** @jsx React.DOM */
<Foo />;
```

compiles into

```js
"use strict";
/** @jsx React.DOM */
React.DOM(Foo, null);
```

Is this desired behavior? I'm not totally sure but it seems like this may have cropped up recently, and I'm not sure whether the change means that we should stop using the comment everywhere - React's components should be autodetectable as DOM vs not via the casing, and `React.DOM` isn't a function, so it'll always throw an error.

**Comment by cesarandreu** [comment]
The comment is not needed as of React v0.12, see [here](http://facebook.github.io/react/blog/2014/10/28/react-v0.12.html#jsx-changes).

**Comment by sebmck** [comment]
Yep, the comment is honoured to support use such as #841. As @cesarandreu said, the comment isn't necessary as of React 0.12.
