### ISSUE TITLE
Plugin 'transform-flow-comments' does not transform React context type

### ISSUE THREAD

**Issue by mrtnzlml** [babel/babel#8570]
## Bug Report

**Current Behavior**
`babel-plugin-transform-flow-comments` does not generate correct code for React context. It generates the following which is wrong:

```js
const Theme = React.createContext < "light" | "dark" > "light";

// Prettier:
const Theme = (React.createContext < "light") | ("dark" > "light");
```

_(`babel-plugin-transform-flow-strip-types` is broken as well)_

**Input Code**
[REPL](https://goo.gl/ea4Fpk) - don't forget to add the `babel-plugin-transform-flow-comments` plugin

```js
const Theme = React.createContext<"light" | "dark">("light");
```

See: https://flow.org/en/docs/react/context/

**Expected behavior/code**
It should generate something like this (similar to other generics):

```js
const Theme = React.createContext /*:: <"light" | "dark">*/("light");
```

**Comment by mrtnzlml** [comment]
Seems like this is still an issue. Can you please give us a hint where in Babel codebase could be the problem?

**Comment by loganfsmyth** [comment]
The issue is likely that you are missing the `// @flow` comment in this file.

**Comment by mrtnzlml** [comment]
OK, I actually cannot reproduce this issue in real application anymore so I will just accept I did such an incredibly stupid mistake (or it's fixed already)... 😬

Thanks. :)
