### ISSUE TITLE
Sometimes decorators get incomplete class bodies.

### ISSUE THREAD

**Issue by jsg2021** [babel/babel#8572]
## Bug Report

**Current Behavior**
I'm getting some test failures caused by some of my classes not having their static fields defined before being passed to decorators... the odd thing is when I run the babel cli on individual files or run rollup it looks fine... when I break and inspect the file while jest is running its transformed using _defineProperty instead of ClassName.StaticField = Value... and comes after the calls to the decorators.

I've been trying to come up with a minium reproduction that I can share, but the repl is still v6... and I'm still trying to nail down factors.  But jest is using the same preset/config :|

**Expected behavior/code**
@babel/plugin-proposal-class-properties  `loose: true` is respected on each file.

**Babel Configuration (.babelrc, package.json, cli command)**
my `.babelrc`s all just point to this preset:
```js
'use strict';
const browsers = require('./browserlist');
const env = process.env.BABEL_ENV || process.env.NODE_ENV;
module.exports = function (api, opts) {
	const isTest = (env === 'test');
	const envOpts = {
		targets: isTest ? {
			node: 'current'
		} : {
			browsers
		},
	};

	if (!isTest) {
		envOpts.modules = false;
	}

	return {
		compact: false,
		presets: [
			['@babel/preset-env', envOpts],
			['@babel/preset-flow'],
		],
		plugins: [
			['@babel/plugin-proposal-decorators', { legacy: true }],
			['@babel/plugin-proposal-class-properties', { loose: true }],
			['@babel/plugin-proposal-export-default-from'],
			['@babel/plugin-proposal-export-namespace-from'],
			['@babel/plugin-proposal-object-rest-spread'],
		].filter(Boolean)
	};
};
```

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node 10.7
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: jest

**Comment by jsg2021** [comment]
It may have been a cached transform? I cleared jest's cache and now it seems fine :/

**Comment by loganfsmyth** [comment]
Okie doke, well feel free to reopen if you run across it again :)
