### ISSUE TITLE
React Native - TypeError: Cannot read property 'bindings' of null at Scope.moveBindingTo

### ISSUE THREAD

**Issue by to175** [babel/babel#8575]
Hello,

I have babel in my node_modules and when i do react-native run-android I have an error :

> error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/Theo/Documents/React Native/HuberApp/node_modules/@babel/traverse/lib/scope/index.js:978:13)
    at BlockScoping.updateScopeInfo (/Users/Theo/Documents/React Native/HuberApp/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/Theo/Documents/React Native/HuberApp/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/Theo/Documents/React Native/HuberApp/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/Theo/Documents/React Native/HuberApp/node_modules/@babel/traverse/lib/visitors.js:237:21)
    at NodePath._call (/Users/Theo/Documents/React Native/HuberApp/node_modules/@babel/traverse/lib/path/context.js:65:20)
    at NodePath.call (/Users/Theo/Documents/React Native/HuberApp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/Theo/Documents/React Native/HuberApp/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/Theo/Documents/React Native/HuberApp/node_modules/@babel/traverse/lib/context.js:142:16)
 BUNDLE  [android, dev] ../../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

Can you help me please ?

Here is my package.json
`  "devDependencies": {
    "@babel/preset-env": "^2.0.0-alpha.20",
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "^5",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"`

**Comment by loganfsmyth** [comment]
What is in your Babel configuration? Also `"@babel/preset-env": "^2.0.0-alpha.20"` is not an existing version. Perhaps that is a mistake?

**Comment by to175** [comment]
Thanks a lot :)

How can I discover my Babel config please ?

I have put v2 alpha because I saw in a thread it could help... Before I had v7

**Comment by tejomayonline** [comment]
please use version 5.0.2 of babel-preset-react-native, it will work,

**Comment by nicolo-ribaudo** [comment]
Could you also try to use `metro-react-native-babel-preset` (you need to use the `module:` prefix in your config)? It seems that React Native uses that one now (https://github.com/facebook/react-native/issues/20327)

**Comment by to175** [comment]
Thanks,

I have changed the package.json to
`"devDependencies": {
    "@babel/preset-env": "^7.0.0",
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "5.0.2",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },`

But I have still the error.

What do I have to do with metro-react-native-babel-preset ? How to use this and use module: prefix please ?

I did an npm install metro-react-native-babel-preset but the error is still there

**Comment by nicolo-ribaudo** [comment]
I think that this could work:

```json5
// package.json

"devDependencies": {
  "@babel/preset-env": "^7.0.0",
  "babel-jest": "22.4.3",
  "metro-react-native-babel-preset": "(I don't know, the one installed by npm)",
  "jest": "22.4.3",
  "react-test-renderer": "16.3.1"
},

// .babelrc
{
  "presets": [
    "@babel/preset-env",
    "module:metro-react-native-babel-preset"
  ]
}
```

If it doesn't, run `npx nls why babel-plugin-transform-es2015-block-scoping` to see what is pulilng in Babel 6 modules.

**Comment by to175** [comment]
Thx, I have this package.json already.

I don't know where is .babelrc

**Comment by nicolo-ribaudo** [comment]
What does `npx nls why babel-plugin-transform-es2015-block-scoping` print?

**Comment by to175** [comment]
Oh, it gives me :

> macbook-pro-de-theo:HuberApp Theo$ npx nls why babel-plugin-transform-es2015-block-scoping
npx : 8 installé(s) en 1.781s
Cannot read property 'requires' of undefined

It seems to be bad 😞 it sais 8 npx installed but... What can I do please ?

**Comment by nicolo-ribaudo** [comment]
If it doesn't work, can you create a gist whth your `package-lock.json` or `yarn.lock` file?

**Comment by to175** [comment]
Thank, how can I do that please ?

**Comment by to175** [comment]
Oh yeah here they are :
https://gist.github.com/to175/e22cab07ac1cc3a50d9fa0bab156a353
https://gist.github.com/to175/4e27ef01d8165bd84de311afd6ab5322

**Comment by nicolo-ribaudo** [comment]
Why do you still have `babel-preset-react-native`? :thinking:  (Also, `metro-react-native-babel-preset` should probably be in your `devDependencies`). Does your error still mention babel-plugin-transform-es2015-block-scoping?

**Comment by to175** [comment]
You are right the error is now
Error: Cannot find module 'metro-react-native-babel-present' from '/Users/Theo/Documents/React Native/HuberApp'

But if I add something manually, I'm afraid it can break...

Do I have to delete the line with babel-preset-react-native ?
Do I have to move metro-react-native-babel-preset to devDependencies ?

**Comment by shilch** [comment]
I'm getting ".overrides is not allowed in preset options" as well. Did you fix it @to175?

**Comment by to175** [comment]
@shilch nope

But just remove your "@override" in MainApplication and MainActivity :)

**Comment by danilojpferreira** [comment]
I'm with the same problem...
For me works downgrade the RN version to 0.55.4 and babel-preset-react-native version to 4.0.1

if you wanna try:
npm install react-native@0.55.4 --save && npm install babel-preset-react-native@4.0.1 --save

**Comment by brunolemos** [comment]
> @shilch: I'm getting ".overrides is not allowed in preset options" as well

Does anyone know how to fix this? Got this after upgrading babel from beta to stable.

**Comment by zedtux** [comment]
I'm also facing this issue. I followed what @nicolo-ribaudo suggested, but I got the `.overrides is not allowed in preset options` error.

I ran the `npx nls why babel-plugin-transform-es2015-block-scoping` command and got :

```
npx: installed 8 in 13.127s

  Who required babel-plugin-transform-es2015-block-scoping:

  Companion > react-native > fbjs-scripts > babel-preset-fbjs > babel-plugin-transform-es2015-block-scoping@^6.8.0
  Companion > react-native > metro > babel-preset-fbjs > babel-plugin-transform-es2015-block-scoping@^6.8.0

```

**Comment by nicolo-ribaudo** [comment]
What is your package.json?

**Comment by zedtux** [comment]
```javascript
{
  "name": "Companion",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "flow": "flow",
    "flow-stop": "flow stop",
    "postversion": "react-native-version",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "aws-sdk": "^2.245.1",
    "axios": "^0.18.0",
    "base-64": "^0.1.0",
    "dot-prop-immutable": "^1.4.0",
    "jwt-decode": "^2.2.0",
    "moment": "^2.22.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-autogrow-textinput": "^5.1.1",
    "react-native-camera": "^1.1.4",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "^0.22.5",
    "react-native-document-scanner": "^1.4.2",
    "react-native-elements": "^0.19.1",
    "react-native-icon-badge": "^1.1.3",
    "react-native-image-to-pdf": "^1.0.0",
    "react-native-ionicons": "^0.2.2",
    "react-native-iphone-x-helper": "^1.0.3",
    "react-native-joi": "^0.0.5",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-md5": "^1.0.0",
    "react-native-numeric-input": "^1.3.1",
    "react-native-orientation": "^3.1.3",
    "react-native-pdf": "^5.0.3",
    "react-native-progress": "^3.5.0",
    "react-native-redux-i18n": "^1.0.5",
    "react-native-render-html": "^3.10.0",
    "react-native-sensitive-info": "^5.2.4",
    "react-native-slack-webhook": "^0.0.5",
    "react-native-swipeable": "^0.6.0",
    "react-native-tag-autocomplete": "^1.0.21",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.4.1",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-logic": "^1.0.2",
    "redux-persist": "^5.10.0",
    "redux-persist-sensitive-storage": "^1.0.0",
    "redux-persist-transform-filter": "^0.0.18",
    "redux-thunk": "^2.2.0",
    "rn-fetch-blob": "^0.10.13",
    "rn-sliding-up-panel": "^1.2.1",
    "seamless-immutable": "^7.1.3",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.1.0",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^23",
    "eslint": "^5.5.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "flow-bin": "0.75.0",
    "gulp": "^4.0.0",
    "gulp-awspublish": "^3.3.3",
    "gulp-env": "^0.4.0",
    "gulp-rename": "^1.2.3",
    "gulp-util": "^3.0.8",
    "jest": "^23",
    "keys-diff": "^1.0.5",
    "merge-json": "^0.1.0-b.3",
    "metro-react-native-babel-preset": "^0.46.0",
    "onesky-utils": "^1.2.0",
    "react-native-version": "^2.6.0",
    "react-test-renderer": "16.5.0",
    "through2": "^2.0.3",
    "xmlhttprequest": "^1.8.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by zedtux** [comment]
Thank you @nicolo-ribaudo, I tried it but I still have the same error 😞

**Comment by nicolo-ribaudo** [comment]
Which command are you using to run Babel? For some reason it is using an old beta version of `@babel/core` (before ca1c98b255f519724023a0fbaaf47a7339c5fa8b) which isn't compatible with `metro-react-native-babel-preset`

**Comment by zedtux** [comment]
I'm building from Xcode or with `react-native run-android`.

**Comment by zedtux** [comment]
Oh ... I just realised that I'm on a non react native repo ... sorry about the lack of info. 🤦‍♂️.

So I'm building a React Native app and I did the upgrade from 0.56 to 0.57.1 this morning and it imports babel 7.
I don't know how RN is executing babel when I'm pushing the build button from Xcode, sorry.

**Comment by nicolo-ribaudo** [comment]
What does `npx nsl why @babel/core` log?

**Comment by zedtux** [comment]
```
npx: installed 8 in 5.06s

  Who required @babel/core:

  Companion > @babel/core@^7.1.0
  Companion > react-native > metro > @babel/core@7.0.0-beta.47
```

**Comment by nicolo-ribaudo** [comment]
For some reason you have an old version of `metro`: the last one depends on `@babel/core@^7.0.0` (https://github.com/facebook/metro/blob/bba48f068c6e709187d36170d3e5d49b7e9f6169/packages/metro/package.json#L16).
Could you try to delete your `node_modules` folder and reinstall it? (`npm install` or `yarn install`)

**Comment by zedtux** [comment]
Well well ... so let's enable the shame mode ... 😅.

First thing I did the upgrade this morning and got a working version which I committed and pushed within the dedicated branch.
Then I switched to the `develop` branch and didn't `pull` it again 🤦‍♂️. That's why I'm saying I'm migrating `react-native` to 0.57, but in the posted `package.json` the version is 0.56 ....
After I saw that I did the `git pull` and received the updates.
Enough, switch off the shame mode.

Now the app starts 😇. Sorry for the noise @nicolo-ribaudo and thank you for your help !! 💯

**Comment by nicolo-ribaudo** [comment]
Glad that it works :smile:

**Comment by anuragdhunna** [comment]
Try:
`npm i babel-preset-react-native --save-dev`

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since it was a configuration problem. If someone else has the same problem, please install the last version of every package.

**Comment by ionush** [comment]
I'm just adding to this issue as I spent the whole day with the same problem. If you're using webpack, check that your babel-loader is > version 7 and that the plugins reference the new @babel ones.

Also, if you're RN 0.56.0, you should be importing all @babel plugins @7.0.0-beta.47 and babel-preset-react-native @5.0.2, not metro-react-native-babel-preset. Check the RN changelog for peace of mind https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#056
