### ISSUE TITLE
after adding @babel/plugin-proposal-class-properties in  same error

### ISSUE THREAD

**Issue by tejomayonline** [babel/babel#8577]
## Bug Report

**Current Behavior**
currently showing  

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

when I add `@babel/plugin-proposal-class-properties` in node_modules, .babelrc plugins no effect, same message shows

**Input Code**
- REPL or Repo link if applicable:
### package.json

![screen shot 2018-08-29 at 13 21 32](https://user-images.githubusercontent.com/25108668/44773593-9945e300-ab8e-11e8-8bf6-f23ddedd1737.png)

`
.babelrc 
`
![screen shot 2018-08-29 at 13 21 50](https://user-images.githubusercontent.com/25108668/44773623-a662d200-ab8e-11e8-80f1-2c1d07dedf5f.png)

`
![screen shot 2018-08-29 at 12 50 39](https://user-images.githubusercontent.com/25108668/44773487-5e43af80-ab8e-11e8-8041-ecb0bc4c6583.png)
please help

**Comment by ngyikp** [comment]
Check your `.babelrc`, it's `@babel/plugin-proposal-class-properties`, not `@transform-class-properties`

**Comment by tejomayonline** [comment]
![screen shot 2018-08-29 at 13 44 09](https://user-images.githubusercontent.com/25108668/44774972-19ba1300-ab92-11e8-813b-107f965b16d9.png)
![screen shot 2018-08-29 at 13 44 21](https://user-images.githubusercontent.com/25108668/44774983-1e7ec700-ab92-11e8-82f2-b54cad3fa964.png)
![screen shot 2018-08-29 at 13 43 56](https://user-images.githubusercontent.com/25108668/44774988-20e12100-ab92-11e8-9ef2-f4783db6f1cc.png)


this is the updated one, same error happen

**Comment by tejomayonline** [comment]
@nicolo-ribaudo  
dir structure is
![screen shot 2018-08-29 at 13 56 34](https://user-images.githubusercontent.com/25108668/44775497-681be180-ab93-11e8-9e70-4dea219acc1b.png)

**Comment by arman-mukatov** [comment]
same error, disappointed((

[https://monosnap.com/file/Hd1hUgPvt1kxyFxrYIcrfWEBMs6654](url)

**Comment by tejomayonline** [comment]
don't get you @arman-mukatov , I added class properties plugin

**Comment by tejomayonline** [comment]
sure @nicolo-ribaudo

**Comment by kirkol** [comment]
I have the same issue. It totally block latest React syntax (static state with no constructor and all arrow functions)
![image](https://user-images.githubusercontent.com/32139097/44849340-19854a80-ac5a-11e8-88cb-4b8e291231a5.png)

**Comment by loganfsmyth** [comment]
It's possible these issues step from the changes to config file application. I'd recommend folks take a look at http://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading, which may help.

**Comment by tejomayonline** [comment]
ok , thanks @loganfsmyth . it will help

**Comment by arman-mukatov** [comment]
I get the following error even after adding the plugin:

![frontend desktop projects 24travel kz frontend - package json frontend 2018-09-12 17-16-04](https://user-images.githubusercontent.com/4972562/45463948-0a110180-b730-11e8-90b6-76ed40991dc9.png)

i confused...

package.json
![frontend desktop projects 24travel kz frontend - package json frontend 2018-09-13 08-31-35](https://user-images.githubusercontent.com/4972562/45463899-d9c96300-b72f-11e8-807c-0f8d7882e1d1.png)

.babelrc
![frontend desktop projects 24travel kz frontend - babelrc frontend 2018-09-13 08-29-50](https://user-images.githubusercontent.com/4972562/45463927-f2397d80-b72f-11e8-9017-0304213b6cec.png)
![frontend desktop projects 24travel kz frontend - babelrc frontend 2018-09-13 08-30-20](https://user-images.githubusercontent.com/4972562/45463929-f5346e00-b72f-11e8-942d-82bbd4605ce7.png)

**Comment by hodgef** [comment]
If you are using create-react-app and have ejected, add this as your config (in both your webpack.config for webpack-loader and package.json):

```
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        [
          "@babel/plugin-proposal-class-properties"
        ]
    ]
}
```

That means installing `npm install --save-dev @babel/preset-env @babel/preset-react @babel/plugin-proposal-class-properties`

Source: https://stackoverflow.com/a/52504340/1467941

**Comment by buildbreakdo** [comment]
Working in a large mono-repo had to do three things to get this to work:

**package.json**
```
{
  "name": "lambda-starter",
  "version": "1.0.0",
  "description": "Minimalist AWS API Gateway and AWS Lambda starter kit",
  "main": "build/index.js",
  "scripts": {
    "build": "NODE_ENV=production webpack --display-error-details --display-modules",
    "watch": "webpack --watch",
    "test": "jest --verbose --config ./jest.config.js",
    "test:watch": "jest --watch --verbose --config ./jest.config.js",
    "start": "sam local start-api --port 5000",
    "dist": "rm -f dist.zip && zip -jq dist.zip build/index.js",
    "update:dev": "aws lambda update-function-code --function-name DevExample --zip-file fileb://dist.zip --publish",
    "update:prod": "aws lambda update-function-code --function-name ProdExample --zip-file fileb://dist.zip --publish",
    "deploy:dev": "npm run build && npm run test && npm run dist && npm run update:dev",
    "deploy:prod": "npm run build && CI=true npm run test && npm run dist && npm run update:prod"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/buildbreakdo/lambda-starter.git"
  },
  "keywords": [
    "starter",
    "starter-kit",
    "aws-api-gateway",
    "aws-lambda"
  ],
  "author": "Your Name Here",
  "bugs": {
    "url": "https://github.com/buildbreakdo/lambda-starter/issues"
  },
  "homepage": "https://github.com/buildbreakdo/lambda-starter#readme",
  "devDependencies": {
    "@babel/core": "^7.1.6",


    "@babel/plugin-proposal-class-properties": "^7.1.0",


    "@babel/preset-env": "^7.1.6",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "^7.1.4",
    "jest": "^23.6.0",
    "jest-cli": "^23.6.0",
    "webpack": "^4.8.1",
    "webpack-cli": "^3.1.2"
  },
  "dependencies": {
    "node-fetch": "^2.3.0"
  }
}
```

**webpack.config.js**

```
const path = require('path');
const webpack = require('webpack');

module.exports = {
  target: 'node',
  mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
  entry: [ './src/index.js' ],
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'index.js',
    library: 'index',
    libraryTarget: 'commonjs2'
  },
  plugins: [
    new webpack.IgnorePlugin(/^pg-native$/),
    new webpack.DefinePlugin({
      'process.env.BROWSER': false,
      __DEV__: process.env.NODE_ENV !== 'production',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(mjs|js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',


        options: {
          presets: [
            '@babel/preset-env',
            {
              plugins: [
                '@babel/plugin-proposal-class-properties'
              ]
            }
          ]
        },


      }
    ],
  }
};
```

**.babelrc**
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.10"
        }
      }
    ]
  ],


  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]


}
```

What was causing this to not work in the monorepo was working in was not explicitly stating the plugins in the webpack.config.js.

Base project with this setup is here: https://github.com/buildbreakdo/lambda-starter

**Comment by zevaverbach** [comment]
Echoing @hodgef but only had to update `package.json`, not `webpack.config.js`.

**Comment by cooperka** [comment]
I'm trying to run Jest tests and getting the `Support for the experimental syntax 'classProperties' isn't currently enabled` error due to code in `node_modules/react-native/jest/mockComponent.js`.

This fixed it for me in `package.json`:

```json
  "jest": {
    "preset": "react-native",
    "transform": {
      "node_modules/react-native/.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
  }
```

Latest recommendations can also be found here: https://jestjs.io/docs/en/tutorial-react-native

**Comment by guitorioadar** [comment]
The above solution are important. But if it doesn't fix the issue then this might help you...

If some one working on monorepo following [react-native-web-monorepo][1] than you need to `config-overrides.js` file in `packages/web`. you need to add `    resolveApp('../../node_modules/react-native-ratings'),` in that file...

My complete `config-override.js` file is 

    const fs = require('fs');
    const path = require('path');
    const webpack = require('webpack');
    
    const appDirectory = fs.realpathSync(process.cwd());
    const resolveApp = relativePath => path.resolve(appDirectory, relativePath);
    
    // our packages that will now be included in the CRA build step
    const appIncludes = [
        resolveApp('src'),
        resolveApp('../components/src'),
        resolveApp('../../node_modules/@react-navigation'),
        resolveApp('../../node_modules/react-navigation'),
        resolveApp('../../node_modules/react-native-gesture-handler'),
        resolveApp('../../node_modules/react-native-reanimated'),
        resolveApp('../../node_modules/react-native-screens'),
        resolveApp('../../node_modules/react-native-ratings'),
        resolveApp('../../node_modules/react-navigation-drawer'),
        resolveApp('../../node_modules/react-navigation-stack'),
        resolveApp('../../node_modules/react-navigation-tabs'),
        resolveApp('../../node_modules/react-native-elements'),
        resolveApp('../../node_modules/react-native-vector-icons'),
    ];
    
    module.exports = function override(config, env) {
        // allow importing from outside of src folder
        config.resolve.plugins = config.resolve.plugins.filter(
            plugin => plugin.constructor.name !== 'ModuleScopePlugin'
        );
        config.module.rules[0].include = appIncludes;
        config.module.rules[1] = null;
        config.module.rules[2].oneOf[1].include = appIncludes;
        config.module.rules[2].oneOf[1].options.plugins = [
            require.resolve('babel-plugin-react-native-web'),
            require.resolve('@babel/plugin-proposal-class-properties'),
        ].concat(config.module.rules[2].oneOf[1].options.plugins);
        config.module.rules = config.module.rules.filter(Boolean);
        config.plugins.push(
            new webpack.DefinePlugin({ __DEV__: env !== 'production' })
        );
    
        return config
    };


  [1]: https://github.com/brunolemos/react-native-web-monorepo

**Comment by guitorioadar** [comment]
The above solution are important. But if it doesn't fix the issue then this might help you...

If some one working on monorepo following [react-native-web-monorepo][1] than you need to `config-overrides.js` file in `packages/web`. you need to add `    resolveApp('../../node_modules/react-native-ratings'),` in that file...

My complete `config-override.js` file is 

    const fs = require('fs');
    const path = require('path');
    const webpack = require('webpack');
    
    const appDirectory = fs.realpathSync(process.cwd());
    const resolveApp = relativePath => path.resolve(appDirectory, relativePath);
    
    // our packages that will now be included in the CRA build step
    const appIncludes = [
        resolveApp('src'),
        resolveApp('../components/src'),
        resolveApp('../../node_modules/@react-navigation'),
        resolveApp('../../node_modules/react-navigation'),
        resolveApp('../../node_modules/react-native-gesture-handler'),
        resolveApp('../../node_modules/react-native-reanimated'),
        resolveApp('../../node_modules/react-native-screens'),
        resolveApp('../../node_modules/react-native-ratings'),
        resolveApp('../../node_modules/react-navigation-drawer'),
        resolveApp('../../node_modules/react-navigation-stack'),
        resolveApp('../../node_modules/react-navigation-tabs'),
        resolveApp('../../node_modules/react-native-elements'),
        resolveApp('../../node_modules/react-native-vector-icons'),
    ];
    
    module.exports = function override(config, env) {
        // allow importing from outside of src folder
        config.resolve.plugins = config.resolve.plugins.filter(
            plugin => plugin.constructor.name !== 'ModuleScopePlugin'
        );
        config.module.rules[0].include = appIncludes;
        config.module.rules[1] = null;
        config.module.rules[2].oneOf[1].include = appIncludes;
        config.module.rules[2].oneOf[1].options.plugins = [
            require.resolve('babel-plugin-react-native-web'),
            require.resolve('@babel/plugin-proposal-class-properties'),
        ].concat(config.module.rules[2].oneOf[1].options.plugins);
        config.module.rules = config.module.rules.filter(Boolean);
        config.plugins.push(
            new webpack.DefinePlugin({ __DEV__: env !== 'production' })
        );
    
        return config
    };


  [1]: https://github.com/brunolemos/react-native-web-monorepo

**Comment by rcarletto67** [comment]
Hi i'm building an react ionic app and after all your help I still struggle with this error. 
![Cattura](https://user-images.githubusercontent.com/62461613/81587833-df20fa00-93b7-11ea-9584-957d1ff00bc7.PNG)
It happened when I tried to ionic serve after importing the react native calendar component. 
Thanks for the attention

**Comment by akzone** [comment]
> Hi i'm building an react ionic app and after all your help I still struggle with this error.
> ![Cattura](https://user-images.githubusercontent.com/62461613/81587833-df20fa00-93b7-11ea-9584-957d1ff00bc7.PNG)
> It happened when I tried to ionic serve after importing the react native calendar component.
> Thanks for the attention

I've the same problem.

**Comment by akshgods** [comment]
> The above solution are important. But if it doesn't fix the issue then this might help you...
> 
> If some one working on monorepo following [react-native-web-monorepo](https://github.com/brunolemos/react-native-web-monorepo) than you need to `config-overrides.js` file in `packages/web`. you need to add ` resolveApp('../../node_modules/react-native-ratings'),` in that file...
> 
> My complete `config-override.js` file is
> 
> ```
> const fs = require('fs');
> const path = require('path');
> const webpack = require('webpack');
> 
> const appDirectory = fs.realpathSync(process.cwd());
> const resolveApp = relativePath => path.resolve(appDirectory, relativePath);
> 
> // our packages that will now be included in the CRA build step
> const appIncludes = [
>     resolveApp('src'),
>     resolveApp('../components/src'),
>     resolveApp('../../node_modules/@react-navigation'),
>     resolveApp('../../node_modules/react-navigation'),
>     resolveApp('../../node_modules/react-native-gesture-handler'),
>     resolveApp('../../node_modules/react-native-reanimated'),
>     resolveApp('../../node_modules/react-native-screens'),
>     resolveApp('../../node_modules/react-native-ratings'),
>     resolveApp('../../node_modules/react-navigation-drawer'),
>     resolveApp('../../node_modules/react-navigation-stack'),
>     resolveApp('../../node_modules/react-navigation-tabs'),
>     resolveApp('../../node_modules/react-native-elements'),
>     resolveApp('../../node_modules/react-native-vector-icons'),
> ];
> 
> module.exports = function override(config, env) {
>     // allow importing from outside of src folder
>     config.resolve.plugins = config.resolve.plugins.filter(
>         plugin => plugin.constructor.name !== 'ModuleScopePlugin'
>     );
>     config.module.rules[0].include = appIncludes;
>     config.module.rules[1] = null;
>     config.module.rules[2].oneOf[1].include = appIncludes;
>     config.module.rules[2].oneOf[1].options.plugins = [
>         require.resolve('babel-plugin-react-native-web'),
>         require.resolve('@babel/plugin-proposal-class-properties'),
>     ].concat(config.module.rules[2].oneOf[1].options.plugins);
>     config.module.rules = config.module.rules.filter(Boolean);
>     config.plugins.push(
>         new webpack.DefinePlugin({ __DEV__: env !== 'production' })
>     );
> 
>     return config
> };
> ```

thanks for solution but i'm getting error after updating your code with same repo
Cannot read property 'oneOf' of undefined, can please help
