### ISSUE TITLE
How do I know if Lerna made my use of Babel illegal?

### ISSUE THREAD

**Issue by StoneCypher** [babel/babel#8580]
Recently, [lerna](https://github.com/lerna/lerna/pull/1616) decided to make itself illegal for anyone dealing with the American immigration agency `ICE`.  This means that basically every hosting provider (including AWS) is now `lerna`-intolerant.  

Problematically, I use `babel 6` and `babylon` to parse a custom programming language.  These are, unsurprisingly, very heavily tested.  I can't find a continuous integration provider that is not blocked by the new `lerna` license.

Notably, this also means that `github` is now `lerna` intolerant.

Ripping out `babel` would be catastrophic.  Ripping out continuous integration would be very bad as well.

How do I know whether `lerna` has changed the legal situation around using your tools?

**Comment by mAAdhaTTah** [comment]
If you're not using lerna directly, and you're not using it in service of one of the companies listed in the new license clause specifically (it's not as broad as you suggest), you have nothing to worry about. See #8579.

**Comment by xtuc** [comment]
Duplicated https://github.com/babel/babel/issues/8579#issuecomment-416968197
