### ISSUE TITLE
Babel ignore/disable strict mode | npm package

### ISSUE THREAD

**Issue by shashank-13** [babel/babel#8585]
![screenshot 11 _li](https://user-images.githubusercontent.com/16037295/44835464-e76fea80-ac51-11e8-900f-4ad411e86a2b.jpg)

A syntax error is thrown while transpiling es6 code to es5 using babel cli, as it operates in strict mode. Is there any npm package which I can use to transpile with strict mode disabled.

I am adding the two commands that I have run (neither of which worked) along with the screenshot of the error.

babel --presets env table_csv.js --out-file new_table_csv.js

babel table_csv.js --presets es2015-without-strict --out-file new_table_csv.js

**Comment by loganfsmyth** [comment]
By default, Babel parses files as ES6 modules, which are strict by default. You'll want to enable `sourceType: "script"` in your Babel config file to tell Babel to treat files as scripts.

**Comment by shashank-13** [comment]
Okay I will look into that ..can you explain how can I apply this change in case I am just transpiling a set of js files in a directory through command line with babel installed and no additional  project set-up.

**Comment by loganfsmyth** [comment]
Unfortunately, the newly-stable Babel 7 release has a `--source-type` flag for the CLI, Babel 6's CLI does not, so you'd either have to use a config file, or upgrade to Babel 7.

**Comment by shashank-13** [comment]
Then I will try using cli after upgrading to babel7 ..once I get back to work tomorrow.I hope this will resolve the issue.Thanks for this.

**Comment by shashank-13** [comment]
I upgraded to babel 7 release and tried to transpile a single js file using cli and set the --source-type flag to script but it again gave a BABEL_PARSE_ERROR on the delete keyword line.

![screenshot 12 _li](https://user-images.githubusercontent.com/16037295/44893510-15643600-ad09-11e8-8c94-7f047432fa7f.jpg)

**Comment by loganfsmyth** [comment]
@shashank-13 That screenshot does not show `--source-type script`, are you sure you added it?

If you can include an example repository, I can took into this more.

**Comment by shashank-13** [comment]
Yeah I did add the **--source-type:"script"** in the cli,it's just that I have added a different screenshot.But the error remains same in both cases.

**Comment by loganfsmyth** [comment]
I don't believe having a `:` in there is correct.

**Comment by loganfsmyth** [comment]
Nope, that seems strange. If you'd like to file another bug about that, I'd be happy to have someone look into it eventually.

**Comment by shashank-13** [comment]
Okay let me do that.
