### ISSUE TITLE
[Documentation search] Update the search in order to handle different versions and languages.

### ISSUE THREAD

**Issue by s-pace** [babel/babel#8587]
👋 team,

I am working on [DocSearch](https://community.algolia.com/docsearch/) , an algolia tool. We are proud to feature the search from your documentation website.

Congrats for the v7 👏 

It needed [an update from our side](https://github.com/algolia/docsearch-configs/commit/6563a0730d9a51ff3a3c0b44f7ed0ecb1d7952eb) in order to avoid having duplicates from v7 and the latest 6.26.3. No worries, everything is proactively updated (we monitor big changes)

If you want, we do offer filtering over `language` and `version`. Since you are using Docusaurus, the `version` and `language` filters are handled automatically from the Search-UI.  We will need you to enable it and check that your Docusaurus instance is updated.

Please ping me if you want to enable this feature. I will PR the required changes from [your DocSearch configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/babeljs.json). 

Your website will have an adaptive search instead of only retrieving the latest version.

**Comment by existentialism** [comment]
@babel-bot move to @babel/website

**Comment by existentialism** [comment]
^ Or not? lol

@s-pace thanks for reaching out, and I think we'd want to enable this (though we haven't yet officially enabled translations _yet_).

**Comment by existentialism** [comment]
@babel-bot move to babel/website

**Comment by existentialism** [comment]
@s-pace moving this issue over to the website repo, we can continue the convo over there!
