### ISSUE TITLE
Async transpiling buries exceptions.

### ISSUE THREAD

**Issue by joeyhub** [babel/babel#8588]
I'm using webpack to transpile ES8 to es2015/stage-0. I've got a lot of async in there.

    "babel-loader": "^7.1.5",
    "babel-polyfill": "^6.26.0",

When I transpile using the above to provide things like Promises, conversion for async, etc then suddenly try catch stops working.

I get uncaught exception in promise.

**Comment by joeyhub** [comment]
It's also possible that the implementation is broken because of confusion about how async functions work.

If you call an async function from a non-async context then there's no where for the exception to go.

However whenever you have await, the exception has a place to go.

Either:

```await aFunctionThatsAsync();```

Or:

```aFunctionThatsAsync().catch(error => doStuff)```

Should *NEVER* swallow exceptions. It's only when you don't have one of those that exceptions should hit an "unhandled" handler.

**Comment by joeyhub** [comment]
Sorry, I'm confusing a few things.

I had this originally:

    func().catch(error => {
        if(error instanceof MyLittleError) doSomething();
    });

This was with core js promie and babel generator runtime to keep the load low. Same thing happened though with babel-polyfill (so not some compatibility mismatch).

I switched to:

    (async () => {
        try {func()}
        catch(error) {if(error instanceof MyLittleError) doSomething()}
    });

Throwing myself off with the missing await.

It turns out that what's actually happening is for some reason when I'm transpiling, error becomes an instance of something else.

I think that somewhere you have error wrapping which is generally a bad practice when really all you need to be doing is passing the parcel, not unwrapping it, taking out the contents and wrapping again.

However that's an assumption and it might not be your fault. I'm going to have to look into it further because it's also possible that minification is renaming the definition of MyLittleError but not realising it's the same one on the instanceof giving them different names.

Doing some digging around, I'm not sure I see any obvious signs of either of those.

What I'm seeing instead looks like the transpiler for "class" might break instanceof in at least some cases?

Given it seems like that, can close the ticket if you want as it's not the issue I originally thought it was.

**Comment by joeyhub** [comment]
It looks like this:

https://www.npmjs.com/package/babel-plugin-transform-builtin-extend

Something like this that breaks (where what you compiled is different from before compile in terms of runtime outcome) should really be a halting error by default when compiling?

**Comment by loganfsmyth** [comment]
Babel 6 in general does not support extending builtin types: http://babeljs.io/docs/en/6.26.3/caveats#classes

Using that plugin may well address your issue. Otherwise you could potentially explore using Babel 7.x which I believe does a better job of handling builtins.
