### ISSUE TITLE
[6.x polyfill package]Throwing error is annoying for loading polyfill module by different components

### ISSUE THREAD

**Issue by balab2020** [babel/babel#8590]
## Bug Report

**Current Behavior**
I have different components being pulled into one project. Every component has different bootstrap with it's own dev packages.  I am getting error from babel polyfill pacakge if it is loaded multiple components.

**Input Code**
https://github.com/babel/babel/blob/6.x/packages/babel-polyfill/src/index.js#L2

```js
if (global._babelPolyfill) {
  throw new Error("only one instance of babel-polyfill is allowed");
}
```

**Expected behavior/code**

```js

if (global._babelPolyfill && typeof console !== "undefined" && console.warn) {
  console.warn(
    "@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended " +
      "and may have consequences if different versions of the polyfills are applied sequentially. " +
      "If you do need to load the polyfill more than once, use @babel/polyfill/noConflict " +
      "instead to bypass the warning.",
  );
}

```

**Environment**
- Babel version(s): v6.0.0

**Possible Solution**
https://github.com/babel/babel/pull/8589

**Comment by nicolo-ribaudo** [comment]
At this point, we aren't going to release v6 anymore.
