### ISSUE TITLE
d3 dons't work expected.

### ISSUE THREAD

**Issue by xinggangling** [babel/babel#8595]
# v7 Regression

> First check out: https://new.babeljs.io/docs/en/next/v7-migration.html
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Potential Commit/PR that introduced the regression**
     
**Describe the regression**
     I am so happy, babel 7 has come, and I update my project's package.json. after it builds perfectly.
i login in my system.everything seems be expected; but when i handle a component which is dependence with d3.js@4.11.0, it told me transition is not a function. 

**Input Code**

it is part of my code below:
```js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import * as d3 from 'd3';

this.svg = d3.select(this.refs.container)
this.svg.transition() // transition is not a function. here, it works well before.
<svg ref="container">
</svg>
````

this is my update:
```js
-    "@babel/core": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-class-properties": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-decorators": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-export-default-from": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-export-namespace-from": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-function-sent": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-json-strings": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-numeric-separator": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-rc.1",
-    "@babel/plugin-proposal-throw-expressions": "^7.0.0-rc.1",
-    "@babel/plugin-syntax-dynamic-import": "^7.0.0-rc.1",
-    "@babel/plugin-syntax-import-meta": "^7.0.0-rc.1",
-    "@babel/plugin-transform-react-constant-elements": "^7.0.0-rc.1",
-    "@babel/plugin-transform-react-inline-elements": "^7.0.0-rc.1",
-    "@babel/polyfill": "^7.0.0-rc.1",
-    "@babel/preset-env": "^7.0.0-rc.1",
-    "@babel/preset-flow": "^7.0.0-rc.1",
-    "@babel/preset-react": "^7.0.0-rc.1",
+    "@babel/core": "^7.0.0",
+    "@babel/plugin-proposal-class-properties": "^7.0.0",
+    "@babel/plugin-proposal-decorators": "^7.0.0",
+    "@babel/plugin-proposal-export-default-from": "^7.0.0",
+    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
+    "@babel/plugin-proposal-function-sent": "^7.0.0",
+    "@babel/plugin-proposal-json-strings": "^7.0.0",
+    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
+    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
+    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
+    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
+    "@babel/plugin-syntax-import-meta": "^7.0.0",
+    "@babel/plugin-transform-react-constant-elements": "^7.0.0",
+    "@babel/plugin-transform-react-inline-elements": "^7.0.0",
+    "@babel/plugin-transform-runtime": "^7.0.0",
+    "@babel/plugin-transform-template-literals": "^7.0.0",
+    "@babel/polyfill": "^7.0.0",
+    "@babel/preset-env": "^7.0.0",
+    "@babel/preset-flow": "^7.0.0",
+    "@babel/preset-react": "^7.0.0",
````

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    // [
    //   "@babel/plugin-register"
    // ],
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": false
      }
    ],
    "@babel/plugin-proposal-json-strings",
    "@babel/plugin-proposal-export-default-from",
    "react-loadable/babel",
    [
      "import",
      {
        "libraryName": "antd",
        "style": true
      }
    ],
    "react-hot-loader/babel"
  ]
}
```

**Expected behavior/code**
I really want to get your help. thanks.

**Environment**
- Babel version(s):v7.0.0
- Node/npm version: node 8.9.4/npm 5.6.0
- OS: OSX 10.13.4
- Monorepo yes // https://github.com/xinggangling/githubIssueDemo
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
Global `this` in es modules is `undefined`, I'm surprised that your code doesn't throw `Cannot read property 'svg' of undefined.`.
If you are using webpack, it could be that now Babel doesn't transpile es modules when used through `babel-loader`: WebPack is more spec-compliant, so it might show bugs that where accepted by Babel. You can re-enable Babel's module transform by passing `"modules": "commonjs"` to `"@babel/preset-env"`.

**Comment by nicolo-ribaudo** [comment]
I don't get that error, but I get an error two lines after because you `this.transition` is undefined. Where do you expect it to be defined?

**Comment by xinggangling** [comment]
hi! nicolo. It is my expect. it is undefined after I config it with babel 7. it worked well when i use @babel/core": "^7.0.0-rc.1.

**Comment by loganfsmyth** [comment]
Does it work if you change
```
"@babel/preset-env",
```
to
```
["@babel/preset-env", { modules: "commonjs" }],
```
?

**Comment by xinggangling** [comment]
hello, loganfsmyth. I have try it, it also dons't work well. I have try other releases.None of them seems to work.Now I am not sure whether it is because of upgrading the problem caused by Babel.But I'm sure I just upgraded Babel.
![image](https://user-images.githubusercontent.com/18533687/44924763-ee484b80-ad7e-11e8-8ecd-325b0d7b4a4f.png)
![image](https://user-images.githubusercontent.com/18533687/44924850-2cde0600-ad7f-11e8-9325-7ebfe07bf5b0.png)

**Comment by loganfsmyth** [comment]
Strange. If you create a repository to reproduce the issue, I can take a look at it.

**Comment by nicolo-ribaudo** [comment]
@xinggangling I meant, in your repository you aren't defining it anywhere.

**Comment by xinggangling** [comment]
yes nicolo. it is not defined,In d3 source code, transition can be defined under many conditions.Maybe my code is not satisfied. it cause transition property disappear.
![image](https://user-images.githubusercontent.com/18533687/44929621-3f137080-ad8e-11e8-8429-937c5d5a78e7.png)
thinks for your answer! loganfsmyth and nicolo-ribaudo, It's 2:40am now, It's time for 😪.

**Comment by loganfsmyth** [comment]
I agree with @nicolo-ribaudo, I don't think your issue is with `.transition`. I think it's just the debugger itself showing `undefined` because it doesn't know about the transformation Babel performed, because the first one uses `_this` and the second one uses `this` (which probably won't work). 

You haven't actually shown us the error that you're actually seeing. What do you actually see when your code runs?
