### ISSUE TITLE
decorators (legacy) enforce decorators after export

### ISSUE THREAD

**Issue by jsg2021** [babel/babel#8598]
The babel 6 legacy decorators transform allowed decorators on either side of the export...  after upgrading to babel 7 using the new decorators transform with `legacy: true`, code that used decorators before the export are failing with:

> error  Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

**Comment by jsg2021** [comment]
Oh... the error is not from babel cli, its from eslint, & babel-eslint@9.0.0 :/

**Comment by loganfsmyth** [comment]
Ah, yeah `babel-eslint` has its own option for that, it's just not documented well yet :( https://github.com/babel/babel-eslint/issues/679

```
ecmaFeatures: {
  legacyDecotators: true
}
```
in your ESLint config should resolve it for you.

**Comment by jsg2021** [comment]
awesome... i was off creating a repro... thanks!

**Comment by the-simian** [comment]
heads up to anyone copy pasting this.... @loganfsmyth typed 'decotators' (not decorators) which while I'm still laughing about was initially very confused when it seemed to do nothing...

**Comment by nicolo-ribaudo** [comment]
I uppdated his comment
