### ISSUE TITLE
Update Babel Integrations

### ISSUE THREAD

**Issue by Sibiraj-S** [babel/babel#8600]
After Babel 7 is released few integrations were updated sooner and few are not. The two more commonly used packages `grunt-babel` and `babebily` weren't updated.

Those modules seems 100% compatible with babel7 but still in beta. Just a release is needed. No major changes required

To help release process, I created few PR's which may assist the release.

* https://github.com/babel/grunt-babel/pull/93
* https://github.com/babel/babelify/pull/273

and respective issues for that.
* https://github.com/babel/grunt-babel/issues/94
* https://github.com/babel/babelify/issues/274

This Issue is just to draw attention. Since that repos seems not that active.

**Comment by xtuc** [comment]
Since issues are already tracked on their own repos, i'm going to close this.
