### ISSUE TITLE
Comma expression (Sequence expression) incorrectly allowed as JSXAttributeValue

### ISSUE THREAD

**Issue by RyanCavanaugh** [babel/babel#8604]
## Bug Report

**Current Behavior**

Code like `<div>{3, 1}</div>` is not treated as a parse error, but it should be.

[REPL link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwEwlgbgfA3gzAGgAQEYC-wD05oG4BQokSAZgPZkC8MKyATGkplAUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

**Input Code**
```js
// No error
<div>{3, 1}</div>;
// No error
<div foo={1, 2} />;
```

**Expected behavior/code**

Expected a parse error.

The [JSX Spec](https://facebook.github.io/jsx/) specifies `JSXChildExpression` and `JSXAttributeValue` as being `{` *AssignmentExpression* `}`, but the comma expression is [above `AssignmentExpression` in the grammar](https://www.ecma-international.org/ecma-262/5.1/#sec-11.14)

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: N/A (repl)
- OS: N/A (repl)
- Monorepo N/A (repl)
- How you are using Babel: N/A (repl)

**Possible Solution**

**Additional context/Screenshots**

https://stackoverflow.com/questions/52139174/comma-operator-in-typescript-jsx-expressions

**Comment by macabeus** [comment]
@RyanCavanaugh Currently, Babel compile these expressions to same code:

```js
const Foo = props => <div>{console.log(props), JSON.stringify(props)}</div>;
const Bar = props => <div>{(console.log(props), JSON.stringify(props))}</div>;
```

Then, the correct is to raise an error on the `Foo`?

**Comment by RyanCavanaugh** [comment]
@macabeus correct; the JSX specification says the `expr` in `{ expr }` is `AssignmentExpression`, but the ECMAScript grammar does not allow `e1, e2` to be produced from that production.

**Comment by macabeus** [comment]
@RyanCavanaugh I just opened a PR fixing this issue. I would like if you review it. Thank you.
