### ISSUE TITLE
@babel/core version not been consumed by any of presets and plugins in .babelrc file

### ISSUE THREAD

**Issue by alonfai** [babel/babel#8609]
## Bug Report

I'm trying to migrate the @babel project settings from v6 to v7. I've used the babel-upgrade tool and install the new dependencies. However when trying to run the "jest" cli command, I'm getting the following error in the console:

The package.json changes are:

    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.4.0",

**Current Behavior**

The problem occurs when trying to run the jest cli command:

```

Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the
wrong version. Inspect the stack trace of this error to look for the first entry that doesn't
mention "@babel/core" or "babel-core" to see what is calling Babel.

      at throwVersionError (node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
      at Object.assertVersion (node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
      at _default (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
      at node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
          at Array.map (<anonymous>)
```

It doesn't change the error whether I'm consuming just the @babel/preset-env and @babel/preset-react packages without the plugins, as the error still indicates it tries to load the babel-core v6 instead of 7.0.0-bridge.0 version

**Comment by loganfsmyth** [comment]
Can you try clearing `node_modules` and reinstalling your deps?

**Comment by alonfai** [comment]
@loganfsmyth Tried that already, as well delete and recreate the package-lock.json file but with no help.

**Comment by loganfsmyth** [comment]
I'm not sure. If you look at the lockfile, is `babel-core@6` still in there? Would you be able to produce a reproduction case in a repo to look at?

**Comment by alonfai** [comment]
It's still there, as a dependency for the "jest-config" and "jest-runtime" packages.  Our git repo application also uses typescript so ts-jest and babel-jest are been used as well in the config. I'll create a new repo and submit the link here.

**Comment by loganfsmyth** [comment]
Weird, as long as `"babel-core": "^7.0.0-bridge.0",` is installed next to `"babel-jest": "^23.4.0",`, it should work.

**Comment by alonfai** [comment]
@loganfsmyth Do you have a suggestion how to enforce this in the lock file?

**Comment by loganfsmyth** [comment]
Having then both in `package.json` should be enough, so I'm surprised.

**Comment by otorrillas** [comment]
@alonfai installing the bridge (`"babel-core": "^7.0.0-bridge.0"`) solves the issue, even in `jest@21`.

These are my babel and jest related dependencies:
```
{
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-transform-classes": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.0.1",
    "jest": "^21.2.1"
}
```
