### ISSUE TITLE
Add static Math methods to plugin-transform-runtime

### ISSUE THREAD

**Issue by rjgotten** [babel/babel#8611]
The transform-runtime plugin does not yet polyfill static methods of the `Math` object, which are not yet supported everywhere, such as `Math.trunc`. I suggest that these are added.

Without transform-runtime covering these, it's necessary to either polyfill manually or to write your own transform plugin which basically does what transform-runtime already does, but at a more limited scope.
The first is a pain - and avoiding it one of the reasons you'd be using the transform-runtime plugin's polyfilling ability to begin with - and the second, while a one-time investment, just feels wrong.

**Comment by zloirock** [comment]
Seems it was mistakenly removed in https://github.com/babel/babel/commit/508bfad55a47cd72e2fdc780310f4fee9efe38a9#diff-bb1584ad79ba30b51f843278cc5a4e39L71, cc @loganfsmyth

**Comment by rjgotten** [comment]
@loganfsmyth 
Any time-window on when the fix for this will be available? `@babel/core` has been updated to 7.0.1 but the transform-runtime plugin has not. Is it lagging behind?

**Comment by nicolo-ribaudo** [comment]
We had to release 7.0.1 with only one urgent commit, it is almost the same as 7.0.0. The fix will be in the next release.

**Comment by rjgotten** [comment]
@nicolo-ribaudo 
And is there a time-window for that next release?

I'm having to deal with a project that is breaking in IE11 inside a third-party library on `Math.trunc` not being available. We use a light-weight (no preset-env; only transform-runtime plugin) pass of Babel on third-party code to apply polyfills.

Worked great in Babel 6.
Now breaks in Babel 7.

This is holding up our ability to further test developed features of our application for IE 11.
I'm wondering if it will be worth the effort of reverting everything back to Babel 6.x

**Comment by nicolo-ribaudo** [comment]
In the meantime you could load a polyfill for that Math function

**Comment by rjgotten** [comment]
> In the meantime you could load a polyfill for that Math function

The application in question uses non-global polyfilling. This is why we were using transform-runtime over babel-polyfill in the first place.

I could load a polyfill for Math trunc... if I write a custom transform for it which basically does the same as what transform-runtime does. (Inject an import and rewrite static function calls to the imported function.)

**Comment by nicolo-ribaudo** [comment]
You can manually patch the `trunc` function in your entry point:
```js
Math.trunc = Math.trunc || v => {
  v = +v;
  return v - (v % 1) || (v < 0 ? -0 : 0);
};
```

It's a workaround that would make your app work until the next Babel release.

**Comment by loganfsmyth** [comment]
@rjgotten The breakage for this happened in `v7.0.0-rc.4`, so you can also try using the `v7.0.0-rc.3` version of `@babel/plugin-transform-runtime` and `@babel/runtime` for now.

**Comment by rjgotten** [comment]
hmm.. good one.

Thanks. That gives me some options :+1:

**Comment by rjgotten** [comment]
@nicolo-ribaudo
@loganfsmyth 

Version 7.1.0 adds back in support for polyfilling `Math.trunc` and other methods.
But it breaks when using the `corejs` option. Apparantly `@babel/runtime-corejs2` was not updated to have `modules/math/trunc` etc. re-added...

**Comment by rfreitas** [comment]
Are the Array methods removal considered a mistake as well? Will they get reinstated? Technically no browser actually has `Array.filter`, since it's a prototype method. So I guess that is the motivation for the removal. If that is the case, I do wonder what is the alternative, since instance methods are for sure not transformed by the plugin.

**Comment by loganfsmyth** [comment]
They won't be reinstated as-is, though there may be more experimentation to handle instance methods in a better way. https://github.com/babel/babel/pull/7646 has some logic to attempt to address instance methods, for example, it just hasn't landed yet.
