### ISSUE TITLE
[transform-class-properties] `super` support

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [babel/babel#8615]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Here is my use-case: 

```js

class MyFoo extends React.Component {
    static defaultProps = { foo: 42 }
}

class MyBar extends MyFoo {
    static defaultProps = Object.assign({}, super.defaultProps, { bar: 42 })
}
```

But when I do so, I got a Syntax Error ('super' outside of function or class (320:37))

**Describe the solution you'd like**

I would love to be able to use `super` in the context of class properties.

**Describe alternatives you've considered**

I can write `Object.assign({}, MyFoo.defaultProps, { bar: 42 })`, but this is far less refactoring-proof.

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9508
