### ISSUE TITLE
what about types ? 

### ISSUE THREAD

**Issue by allan-simon** [babel/babel#862]
The documentation seems to talk about types, but the following example compile without problem

```
{
    let plop = function (a: Numeric) : Numeric {
        console.log(a);
    };

    plop("aaaa");
}
```

(so it seems that  Babel is aware of the `: Numeric`  but does nothing with it)

the documentation https://babeljs.io/docs/compare/  however seems to put babel to the same point than Typescrit. I have search through the documentation and I haven't seen anything about types.

So is it a feature that will be implemented or just here for compatibility issue ?

**Comment by sebmck** [comment]
Babel supports parsing flow type annotations and they can be checked via
the flow type checker.

I completely agree that it should be documented but lack of contributors
leaves me doing almost everything myself. Could you please open an issue on
the babel.github.io repo for flow type docs, thanks!

On Sunday, 22 February 2015, Allan Simon <notifications@github.com> wrote:

> The documentation seems to talk about types, but the following example
> compile without problem
>
> {
>     let plop = function (a: Numeric) : Numeric {
>         console.log(a);
>     };
>
>     plop("aaaa");
> }
>
> (so it seems that Babel is aware of the : Numeric but does nothing with
> it)
>
> the documentation https://babeljs.io/docs/compare/ however seems to put
> babel to the same point than Typescrit. I have search through the
> documentation and I haven't seen anything about types.
>
> So is it a feature that will be implemented or just here for compatibility
> issue ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/862>.
>


-- 
Sebastian McKenzie

**Comment by allan-simon** [comment]
done, feel free to close this issue.

**Comment by sebmck** [comment]
Great, thanks!

**Comment by allan-simon** [comment]
just one thing, right now it's not possible to use flow type checker if our javascript file use  let , const etc. , right ?  (or is it just me) 

I perfectly understand it's an issue on flow-type checker to support ES6 syntax.

**Comment by sebmck** [comment]
Yeah it is, pending #665 you'll be able to pass your compiled ES5 input to flow.
