### ISSUE TITLE
Setup page didn't update to Babel&

### ISSUE THREAD

**Issue by DanielWLam** [babel/babel#8625]
https://babeljs.io/en/setup#installation

![image](https://user-images.githubusercontent.com/8369212/45016931-c562d780-b058-11e8-8d46-e608c0fd0beb.png)

**Comment by existentialism** [comment]
@babel-bot move to babel/website

**Comment by existentialism** [comment]
@DanielWLam thanks for the issue! moving over to our website repo.

https://github.com/babel/website/issues/1804 is related as well.
