### ISSUE TITLE
Parse error: export default let obj = {}

### ISSUE THREAD

**Issue by xlaywan** [babel/babel#863]
```export default let obj = {}```
throws
```
repl: Unexpected token (1:15)
> 1  | export default let obj = {}
     |                ^
```

**Comment by sebmck** [comment]
This is expected behaviour. See this esdiscuss thread:
https://esdiscuss.org/topic/why-is-export-default-var-a-1-invalid-syntax

On Sunday, 22 February 2015, xlaywan <notifications@github.com> wrote:

> export default let obj = {}
> throws
>
> repl: Unexpected token (1:15)
> > 1  | export default let obj = {}
>      |                ^
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/863>.
>


-- 
Sebastian McKenzie
