### ISSUE TITLE
`@babel/cli` ignores `--ignore` flag

### ISSUE THREAD

**Issue by sto3psl** [babel/babel#8631]
# v7 Regression

With the update of Babel to version 7.0.0 it seems like the `--ignore` flag of @babel/cli doesn't do anything. Using the same command with `babel-cli@6` works just fine.

**Input Code**

```sh
babel src --out-dir lib --ignore ignore.js
```

A standalone repository with the bug and scripts for `@babel/cli` and `babel-cli` can be found here: https://github.com/sto3psl/test-babel-ignore

```
❯ npm run start

> test-babel-ignore@1.0.0 start /Users/fabian/code/test-babel-ignore
> ./node_modules/@babel/cli/bin/babel.js src --out-dir lib --ignore ignore.js

Successfully compiled 3 files with Babel.
```

Expected result: 

```
❯ ls lib
index.js      index.test.js
```

Actual result:

```
❯ ls lib
index.ignore.js index.js        index.test.js
```

All 3 files get compiled even though `@babel/cli` should ignore `index.ignore.js`.

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node@8.11.0 | npm@6.4.1
- OS: macOS 10.13.6
- How you are using Babel: `cli`

**Comment by loganfsmyth** [comment]
In Babel 7 the ignore patterns need to be proper matches, so you'd need to do `--ignore src/*.ignore.js` for that to be ignored.

**Comment by xtuc** [comment]
@sto3psl Would you mind sending a PR on https://github.com/babel/website or opening a new issue there?

I'm closing this for now.

**Comment by sto3psl** [comment]
Yes I will do that! Thanks again for the help.
