### ISSUE TITLE
Non string keys are not excluded from rest object

### ISSUE THREAD

**Issue by exe-dealer** [babel/babel#8632]
## Bug Report

rest object contains destructured non-string keys. Following test fails alter compilation

```js
const source = { 1: 'one', 2: 'two' };
const { 1: _, ...rest } = source;
console.assert(!(1 in rest));
```

**Expected behavior/code**
rest object does not include destructured keys

**Babel Configuration (.babelrc, package.json, cli command)**

default config on babeljs.io/repl v6.26.0

**Possible Solution**
use String(k) conversion before checking key in exclusion set

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/5757, it works in Babel 7
