### ISSUE TITLE
[TypeScript] typescript plugin removes parameter decorators imports

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/babel#8634]
It seems like typescript plugin has some side effects while working with decorators - it removes parameter decorators imports.

Source file:
```ts
// test.ts
import { NgModule, Optional, SkipSelf } from '@angular/core';

@NgModule({})
export class CoreModule {
  constructor(@Optional() @SkipSelf() parentModule) {}
}
```
Babel config:
```json
// .babelrc
{
  "plugins": [
    [ "@babel/plugin-proposal-decorators", { "legacy": true }],
    "babel-plugin-transform-function-parameter-decorators",
    "@babel/plugin-transform-typescript"
  ]
}
```
Result (note that there are no `Optional` and `SkipSelf` imports):
```js
var _dec, _class;

import { NgModule } from '@angular/core';
export let CoreModule = (_dec = NgModule({}), _dec(_class = class CoreModule {
  constructor(_parentModule) {
    var _parentModule2 = Optional()(SkipSelf()(_parentModule));
  }

}) || _class);
```
Expected result (can be obtained by removing typescript plugin):
```js
var _dec, _class;

import { NgModule, Optional, SkipSelf } from '@angular/core';
export let CoreModule = (_dec = NgModule({}), _dec(_class = class CoreModule {
  constructor(_parentModule) {
    var _parentModule2 = Optional()(SkipSelf()(_parentModule));
  }

}) || _class);
```

Environment:
```
node: v10.9.0
npm: 6.2.0
@babel/cli@7.0.0
@babel/core@7.0.0
@babel/plugin-proposal-decorators@7.0.0
babel-plugin-transform-function-parameter-decorators@1.2.0
@babel/plugin-transform-typescript@7.0.0
macOS: 10.13.6 
```

**Comment by xtuc** [comment]
Would you mind sending a PR?

**Comment by yuri-karadzhov** [comment]
Sure, I found why it happens.

**Comment by yuri-karadzhov** [comment]
Here is the snippet https://astexplorer.net/#/gist/2b057a3981fcf7dddf6ffbd9952809e7/5c2bd29c2a8bdb48e22deea6bb0577f9fe223f50

**Comment by yuri-karadzhov** [comment]
So problems caused by `path.scope.crawl();` It feels like it should not be there or it works just wrong. I will remove it from test because it has no sense to have it.

**Comment by yuri-karadzhov** [comment]
@xtuc Can anyone review corresponding PR?

**Comment by jezzgoodwin** [comment]
Hello. Is it possible to get this issue re-opened? There is an additional case whereby parameter decorator imports are lost. When combined with a `public` or `private` keyword inside a class constructor.

Eg:
```javascript
import { inject } from "./inject";
import { UserService } from "./UserService";

export class Store {
    constructor(@inject(UserService) private userService: UserService) {}
}
```
Both `inject` and `UserService` are are not included in the imports. (If the `private` keyword is removed, the imports will work)

Can this issue be re-opened, or should I create a new issue?

Many thanks
