### ISSUE TITLE
npm run dev error:node_modules\@babel\runtime\helpers\esm\extends.js SyntaxError  Unexpected token export

### ISSUE THREAD

**Issue by shangchuan123** [babel/babel#8638]
npm run dev error:node_modules\@babel\runtime\helpers\esm\extends.js SyntaxError  Unexpected token export
## Bug Report

**Current Behavior**
"@babel/runtime": "^7.0.0",

**Input Code**
- REPL or Repo link if applicable:

```js
(function (exports, require, module, __filename, __dirname) { export default function _extends() {
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**
(function (exports, require, module, __filename, __dirname) { export default function _extends() {
                                                              ^^^^^^

SyntaxError: Unexpected token export
```js
"dependencies": {
    "@babel/runtime": "^7.0.0",
```

**Environment**
- Babel version(s):v7.0.0  "@babel/core": "^7.0.0",
- Node/npm version: [e.g. Node 8.11.4]
- OS: [e.g.  Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]
cli
**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/3632165/45131409-69ff2980-b1bf-11e8-9f6d-4ac21aa75319.png)

**Comment by loganfsmyth** [comment]
Are you enable `useESModules` for `transform-runtime`? If so, best to not do that.

**Comment by nicolo-ribaudo** [comment]
As mentioned by Logan, if you are not bundling your code with webpack/rollup you should disable `useESModules`.
