### ISSUE TITLE
Decorated async class methods generating invalid code with `retainLines`

### ISSUE THREAD

**Issue by tidychips** [babel/babel#8650]
## Bug Report

**Current Behavior**
Code containing a syntax error is generated for `async` class methods when decorated and the `retainLines` option is true.

**Input Code**
[Example repo](https://github.com/tidychips/babel7-decorator-codegen-issue)

```js
class Problem {
    @decorator
    async method () {
    }
}
```

when targeting Node 10,  yields:

```js
class Problem {
  async
  method() {
  }}
```

**Expected behavior/code**
The generated code does not contain syntax errors.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
    "retainLines": true,
    "presets": [
        ["@babel/preset-env", {
            "modules": "commonjs",
            "targets": { "node": "10" }
        }]
    ],
    "plugins": [
        [ "@babel/plugin-syntax-decorators", { "legacy": true } ],
        [ "@babel/plugin-proposal-decorators", { "legacy": true } ]
    ]
}
```

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node 10.8.0/npm 6.2.0/yarn 1.9.4
- OS: OSX 10.12.6
- Monorepo: no
- How you are using Babel: cli

**Comment by loganfsmyth** [comment]
Thanks for the report. This is mostly the same as https://github.com/babel/babel/issues/7275, though this is a non-arrow case. Probably best to merge them.

Out of curiosity, why are you using `retainLines`? It's a feature that I'd love to remove personally.

**Comment by tidychips** [comment]
Apparently we enabled `retainLines` way back in the day when source map support wasn't the greatest, and it was just never removed from our project's config.  With the upgrade to babel 7 we're planning on dropping it.

Feel free to merge this with the existing issue.

**Comment by loganfsmyth** [comment]
Cool, closing in favor of #7275
