### ISSUE TITLE
Babel-loader could not find .babelrc or babel.config.js in multi-package repositories if cwd is in subfolder

### ISSUE THREAD

**Issue by FL0RIANMEYER** [babel/babel#8651]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

Babel-loader could not find .babelrc or babel.config.js in multi-package repositories if cwd is not in the root folder.

My Repo Structure like:
```
root
 -  package.json
 -  babel.config.js
 -> packageA 
    -  package.json
    -  webpack.config.js
 -> packageB
 ...
```
When I start Webpack with cwd = packageA, babel.config.js is not recognized.
I have to copy babel.config.js to packageA/babel.config.js to get the settings in babel-loader

It seems to be a bug in 
_babel/packages/babel-core/src/config/config-chain.js : buildRootChain_ or 
_babel/packages/babel-core/src/config/files/configuration.js_

Maybe it breaks at the first package.json or just run to cwd?

**Expected behavior/code**

Resolve first configs in the path to system root ```/```. 

**Environment**
- Babel version(s): v7.0.0-beta.34
- Node/npm version: 10.7.0
- OS:  Windows 7
- How you are using Babel: webpack -> babel-loader -> babel-core

**Comment by loganfsmyth** [comment]
This is currently "expected", but it is definitely a bug pain. You'd have to configure `configFile: "../../babel.config.js"` or `root: "../.."` in your Webpack options for `babel-loader`.

We're currently exploring ways to improve this so that it's easier, but that work isn't done yet. You're welcome to track #8636 if you like.

**Comment by FL0RIANMEYER** [comment]
Setting cwd in options also works.

```
{
    test: /\.js$/,
    loader: 'babel-loader',
    exclude: /node_modules/,
    options: {
        cwd: '../',
    },
},
```


Similar behavior in ```require('@babel/register')```.
Leads babel/register to stop the compilation of shared libraries in root.

```require('@babel/register')({ cwd: '../' })``` also solve this issue.

**Comment by nicolo-ribaudo** [comment]
Closing, replied at https://github.com/babel/babel/issues/8651#issuecomment-419601535
