### ISSUE TITLE
runtime with `useESModules` import commonjs corejs

### ISSUE THREAD

**Issue by pascalduez** [babel/babel#8657]
## Bug Report

**Current Behavior**
Using `@babel/plugin-transform-runtime` with the `useESModules` set to `true` and `corejs` set to `2` will try to import commonjs modules from corejs as ES modules.

**Input Code**

```js
new Map();
```

**Output Code**

```js
import _Map from "@babel/runtime-corejs2/core-js/map";
new _Map();
```

**Expected behavior/code**
Since there's no ES modules version of corejs shipped in `@babel/runtime-corejs2` maybe use `require` instead? :thinking: 

**Babel Configuration (.babelrc)**

```js
{
  "presets": [
    ["@babel/preset-env", { 
      "targets": {
        "browsers": ["IE 6"],
      },
      "modules": false 
    }],
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "corejs": 2,
      "helpers": true,
      "regenerator": true,
      "useESModules": true,
    }],
  ]
}
```

**Environment**
- Babel version: v7.0.0
- Node/npm version: 10 / 6.4.1
- OS: Linux
- Monorepo: no
- How you are using Babel: `cli`

**Comment by loganfsmyth** [comment]
Using `require` inside an ES module is not allowed. The only way to import it is with `import` currently.

**Comment by xtuc** [comment]
This seems to be resolved, closing for now.

**Comment by pascalduez** [comment]
@loganfsmyth Thanks for the replies!

Yes, I ran some tests and Webpack/Rollup are fine.
Also Node seems to accept it: 

```js
// test.mjs
import _Set from "@babel/runtime-corejs2/core-js/set";
const test = new _Set();
console.log(test.size);
````
`node --experimental-modules test.mjs`

All fine.

**Comment by loganfsmyth** [comment]
Yeah, it should all work for now, just keep in mind that it's experimental for a reason :)
