### ISSUE TITLE
Code should not be generating `undefined` as it isn't safe

### ISSUE THREAD

**Issue by zyklus** [babel/babel#866]
`undefined` should never be generated in favor of `void 0` as `undefined` can be overridden.

Example:

```js
function foo( bar=42 ){
}
```

generates:

```js
function foo() {
  var bar = _temporalUndefined;
  bar = arguments[0] === undefined ? 42 : arguments[0];
}
```

**Comment by monsanto** [comment]
I think this is slippery slope. You can redefine all sorts of things that will break Babel, like `Array.isArray`, `Array.from`, `Object.prototype.hasOwnProperty`, ... `undefined` is actually in a better spot than most, because strict mode disallows assignment to it.

**Comment by eventualbuddha** [comment]
I generally agree with @monsanto on this one. You can also use the optional `spec.undefinedToVoid` transformer to turn `undefined` into `void 0`:

```js
function foo() {
  var bar = arguments[0] === void 0 ? 42 : arguments[0];
}
```

**Comment by zyklus** [comment]
Wasn't aware of `spec.undefinedToVoid`, thanks :)
