### ISSUE TITLE
preset-env with loose mode array deconstruction with es6 Set maybe generate wrong code

### ISSUE THREAD

**Issue by HairyRabbit** [babel/babel#8662]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**

```sh
node -r @babel/register -e "var res = require('@babel/core').transformSync('[...[...new Set(1)], ...[...new Set(2)]]' , { presets: [['@babel/env', { loose: true }]] }); console.log(res.code)"
```

generate:

```js
"use strict";

new Set(1).concat().concat(new Set(2).concat());
```

**Expected behavior/code**
The generate code is not same as babel@6 [try](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=NoOjrA7BTB3ACAytALgCgIwEoC6AaeMECEGBZdAJlxyA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

generate code:

```js
"use strict";

[].concat(new Set(1)).concat([].concat(new Set(2)));
```

**Environment**
- Babel version(s): 7
- Node/npm version: v10.3.0/6.1.0
- OS: win10

**Comment by nicolo-ribaudo** [comment]
They both are wrong. Loose mode assumes that you are only spreading arrays: I suggest either disabling loose mode or wrapping your Sets in `Array.from()`.

**Comment by HairyRabbit** [comment]
:) yea sure, disable loose mode always right, and this behavior was a bug, or a feature?

**Comment by nicolo-ribaudo** [comment]
If loose mode was 100% correct it wouldn't be loose 😛
Assuming that everything is an array is a trade-off we must make in order to make the output smaller & faster.

**Comment by HairyRabbit** [comment]
Yeap, I love the pretty code. I think may add more docs about this mode.

**Comment by joseds** [comment]
At least for the current @babel/core 7.2.2 and @babel/preset-env 7.3.1, I found that the result **is** the 
expression the OP expected.

Since, as @nicolo-ribaudo already said (I found it afterwards in some babel legacy docs, too), loose mode transform makes some assumptions on what you put in, e.g. that "All iterable destructuring are assumed to be arrays." (and not Sets), so I see no bug here.

Can we therefore close the current issue?

**Comment by nicolo-ribaudo** [comment]
Yes, I'm closing this issue.

1. https://babeljs.io/docs/en/babel-plugin-transform-spread#options mentions that all the spread elements are assumed to be arrays
2. While different, the Babel 6 output was wrong so this isn't a regression.
