### ISSUE TITLE
Typescript: Constructor property shorthand not perserved with @babel/preset-env

### ISSUE THREAD

**Issue by Retsam** [babel/babel#8669]
## Bug Report

**Current Behavior**
When `@babel/babel-preset-typescript` is used with `@babel/babel-preset-env`, constructor shorthand properties (e.g. `constructor(public someProp: type)`) are not preserved in the output. 

**Input Code**
- REPL or Repo link if applicable:  (I don't think the repl currently supports 7.0)

```ts
class Person {
    constructor(public name: string) {}
}
```

**Expected behavior/code**

This should compile to something like:

```js
var Person = function Person(name) {
    _classCallCheck(this, Person);
    this.name = name;
}
```

instead, it compiles to 

```js
var Person = function Person(name) {
  _classCallCheck(this, Person);
};
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": [
        // {modules: false}, only for cleaner output, does not affect bug
        ["@babel/preset-env", {"modules": false}],
        "@babel/preset-typescript"
    ]
}
```

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: Node 8/npm 6
- OS: OSX 10.13.6
- Monorepo: ? (Not sure what this is asking)
- How you are using Babel: `cli` & `loader`

**Additional context/Screenshots**
I've noticed this only happens when it's compiled with both the presets at the same time: if I compile it with the typescript preset first, then take the output and compile that with preset-env, I get the correct output.

**Comment by ajozwik** [comment]
+1

**Comment by Retsam** [comment]
I did a bit more digging, and this `.babelrc` also reproduces the issue:

```js
{
    "presets": [
        "@babel/preset-typescript"
    ],
    "plugins": [
        "@babel/transform-classes"
    ]
}
```
