### ISSUE TITLE
Change of behavior with _interopRequireWildcard when doing both a wildcard and a named import from a module

### ISSUE THREAD

**Issue by empyrical** [babel/babel#8670]
# v7 Regression

In Babel 6 if you used `import * as Foo` from a module and then later in the same module made an explicit `import {Bar}` import from a module, the generated code would get `{Bar}` directly from the module's exports.

In Babel 7, the generated code will try and get `{Bar}` from the generated `Foo` object, which is not directly from a module's exports object - it's an object that was generated with `_interopRequireWildcard`.

This is an issue if a module's exports have some entries that are not `enumerable`. Previously, you could explicitly import after a wildcard import and still be able to use the unenumerable export - but in Babel 7 you can't.

**Input Code**

```js
import * as wildcard from 'test';
import {explicit} from 'test';

wildcard.func();
explicit();
```

[REPL link (as of writing, Babel REPL is 6.26.0)](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAKjgQwM5wO7ADYBMDGyUucAZlBCHAOQwCmqM1A3AFCiSxwDedAHmGzB8wGAF8yFKrQZM2rLHkLEAdKQCuAO3wAKAJRt-g4aP1sgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=)

**Babel 7 output**
```js
var wildcard = _interopRequireWildcard(require("test"));

// Snipped _interopRequireWildcard definition

wildcard.func();
(0, wildcard.explicit)();
```

**Babel Configuration (.babelrc, package.json, cli command)**

Default `es2015` preset in both. I got the example Babel 7 output using `@babel/cli`:

```sh
> babel --compact false example.js
```

**Expected behavior/code**

Behavior in Babel 6:

```js
var _test = require('test');

var wildcard = _interopRequireWildcard(_test);

// Snipped _interopRequireWildcard definition

wildcard.func();
(0, _test.explicit)();
```

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: Node 10.5.0/NPM 6.1.0/Yarn 1.9.4
- OS: macOS 10.13.6
- Monorepo: no
- How you are using Babel: Both `cli` and `loader`

**Comment by loganfsmyth** [comment]
It seems like this was more of an inconsistency in 6.x. Why should the presence of `import * as Foo` influence the behavior of an unrelated import? It seems more like the issue is the non-enumerability of the property.

**Comment by Kovensky** [comment]
If you are doing imports with non-enumerable properties you are doing something fundamentally wrong with ES modules.

I really recommend avoiding trying to import plain commonjs modules as if they are ES modules or even fake ES modules. If a module is not an ES module only ever import its `default`.

**Comment by empyrical** [comment]
My use case for unenumerable imports is this:

React Native exports its API as getters, so the modules are lazily initialized:

https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-implementation.js

And if you scroll to the bottom, you can see that it has removed API getters that will throw if called. Unfortunately, this breaks doing `import * as Foo from 'react-native';`. I would like to make a pull request for React Native that fixes this by making these deprecated exports unenumerable - but still be able to be explicitly imported, in the case of a deprecated but not fully removed API.

If this is out-of-scope for Babel, I could try and figure out a different solution for this.

**Comment by empyrical** [comment]
Oh hey, that's right! Looks like I didn't notice that the `_interopRequireWildcard` was updated that way. Closing this issue.
