### ISSUE TITLE
Update debug package to version 4.0.0

### ISSUE THREAD

**Issue by ryanelian** [babel/babel#8674]
## Bug Report

**Current Behavior**

I am getting warnings in my CI due to updated debug package:

- https://github.com/visionmedia/debug/issues/603#issuecomment-420237335

- https://github.com/visionmedia/debug/releases/tag/4.0.0

```
warning @babel/core > debug@3.2.4: `debug` versions 3.2.0-3.2.2 break Node 4. Users of node LTS and onward (modern Node versions): please upgrade to `debug@4` or above as soon as possible. Node 4 users: please pin to `debug@>=3.2.3 <4` as it will be the last version range that supports Node@4.
warning @babel/core > @babel/traverse > debug@3.2.4: `debug` versions 3.2.0-3.2.2 break Node 4. Users of node LTS and onward (modern Node versions): please upgrade to `debug@4` or above as soon as possible. Node 4 users: please pin to `debug@>=3.2.3 <4` as it will be the last version range that supports Node@4.
```

**Input Code**

```
npm install
```

**Expected behavior/code**

No warnings in my CI.

**Babel Configuration (.babelrc, package.json, cli command)**

Not applicable

**Environment**
- Babel version(s): @babel/core@7.0.0, @babel/traverse@7.0.0
- Node/npm version: 10/6.2.0
- OS: Linux, Windows
- Monorepo [e.g. yes/no/Lerna]: no
- How you are using Babel: Node API

**Possible Solution**

```
npm install debug
```

On both `@babel/core` and `@babel/traverse` packages.

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/8892187/45360445-d3d16600-b5f9-11e8-8e8b-bb64d93941b3.png)

**Comment by andikaauliaptr** [comment]
Got same error while trying to create new Angular project

**Comment by existentialism** [comment]
Fixed in https://github.com/babel/babel/pull/8989
