### ISSUE TITLE
@babel/parser typescript parse error

### ISSUE THREAD

**Issue by benjamn** [babel/babel#8687]
Reproduction: https://astexplorer.net/#/gist/c50664fe6ed16811a99e07aafccdeaa0/91638046f6e05c70182023ba34e2964a3c34001d

```typescript
type Props = {
  answerToUltimateQuestion: ({ question }: { question: string }) => int;
};
```

Parsing this code with `@babel/parser@7.0.0` and options `{ plugins: ["typescript"] }` gives the following error:
```
Unexpected token, expected ")" (2:41)
```

**Comment by nicolo-ribaudo** [comment]
We are tracking this bug at https://github.com/babel/babel/issues/6667.
