### ISSUE TITLE
how can solve this problem

### ISSUE THREAD

**Issue by xcsweb** [babel/babel#8690]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---
![image](https://user-images.githubusercontent.com/20693737/45412349-fe2e2c80-b6a8-11e8-929b-c771ca41d67c.png)
![image](https://user-images.githubusercontent.com/20693737/45412388-0c7c4880-b6a9-11e8-93f1-4c36d4dba39f.png)

* Slack Community Chat: https://babeljs.slack.com (you can sign-up at https://slack.babeljs.io/ for an invite)
* StackOverflow: https://stackoverflow.com/questions/tagged/babeljs using the tag `babeljs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/babeljs
* Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by xtuc** [comment]
Please re-open a new issue with our issue template. Or at least post your configuration here, so we can modify it.

**Comment by nicolo-ribaudo** [comment]
You should delete the `[]` around the last three plugins.
