### ISSUE TITLE
`export default async function foo() {}` does not declare `foo`

### ISSUE THREAD

**Issue by mroch** [babel/babel#8697]
## Bug Report

**Current Behavior**
```
export default async function foo() { return "foo" }
foo().then(console.log)
```
in node 10.10 with `--experimental-modules`, this logs `"foo"`. in babel 7.0.0, it says `foo` is not defined.

**Expected behavior/code**
I think `foo` should be in scope.

it's in scope if you remove `async`. the spec has the same rules for all `ExportDeclaration: export default HoistableDeclaration` productions, which also leads me to believe that if it's in scope for non-async functions, it should work the same for async functions as well.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  ["@babel/plugin-transform-regenerator", {
      "asyncGenerators": false,
      "generators": false,
      "async": false
  }]
```

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: 10.10
- OS: macOS 10.13.6
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
What is the code enerated by Babel?

**Comment by danez** [comment]
I just tested this and I'm not able to reproduce this. If it is still a problem please reopen and provide an example that triggers the error.
