### ISSUE TITLE
syntax-object-rest-spread should be merged

### ISSUE THREAD

**Issue by bfred-it** [babel/babel#8699]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Object rest spread is part of ES2018 so its **syntax** should be supported natively, without plugins.

**Describe the solution you'd like**

Merge and deprecate `@babel/plugin-syntax-object-rest-spread`

**Teachability, Documentation, Adoption, Migration Strategy**

Deprecate it on npm, spit out _"this plugin isn't necessary anymore"_ warning during babel compilation.

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/8448

**Comment by bfred-it** [comment]
Excellent! I’ll close this one and track that PR. Thanks for your work!
