### ISSUE TITLE
Setting __proto__ optionally

### ISSUE THREAD

**Issue by willsoto** [babel/babel#87]
When extending a class, the following code is output:

``` js
Bar.prototype = Object.create(Foo.prototype, {
  constructor: {
    value: Foo,
    enumerable: false,
    writable: true,
    configurable: true
  }
});

Bar.__proto__ = Foo;
```

The problematic line is `Bar.__proto__ = Foo;` as this is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) and actually results in a jshint error. 

I'm guessing this is there to support older browsers. But with `Object.create()` being supported by IE > 9, I'm wondering if some sort of mechanism can be introduced for omitting that particular pattern of inheritance for those of us that don't need to support older browsers.

**Comment by sebmck** [comment]
6to5 now features a `protoToAssign` transformer that will transform all `__proto__` assignments into a shallow copy. See [caveats](https://6to5.org/docs/caveats/?1) for more info.
