### ISSUE TITLE
Member functions with same name as global functions will infinite loop

### ISSUE THREAD

**Issue by hansl** [babel/babel#871]
The following code will recursively call the hello member of the World class (without the proper `this`). This was not the case a couple of version ago, and is improper (since we don't actually call `this.hello()`). Using Loose mode works but our code rely on some other tricks.

```javascript
function hello() {
  console.log('hello');
}


class World {
  hello() {
    hello();
  }
}
```

**Comment by topaxi** [comment]
Well i guess this is right, i mean

```javascript
function hello() {
  console.log('hello')
}

function World() { }
World.prototype.hello = function hello() {
  hello()
}
```

behaves the same way, and the way i would expect it.

**Comment by hansl** [comment]
Yes, that's what you would expect if you coded the ES5 like that, but the ES6 expectation is that if you want to call `this.hello` you need to use `this.hello()`, not `hello()`. Note that the above code works in other transpilers/browsers that have class support.

The generated code should be 

```javascript
World.prototype.hello = function() {
    hello();
};
```
(it was like this in prior versions of Babel/6to5).

I'm not sure what you gain by naming the member function, since most browsers will be smart enough to show it properly in stacks and traces.

**Comment by fkling** [comment]
@topaxi: Nope, that behavior is definitely wrong here. While the function generated through the method definition should have the **name** `hello`, it **doesn't** create a binding with that name in the scope of function (like function expressions do).

**Comment by sebmck** [comment]
Named self referencing functions are supposed to be handled. The `nameMethod` helper is being given the incorrect `scope`.

**Comment by neVERberleRfellerER** [comment]
Something like splitting name-method.js into name-function.js (for use with spec/function-name.js) and name-method.js (for use with es6/classes.js) and removing binding check in visit for name-method (so the scope is traversed everytime) would not do the trick?

**Comment by sebmck** [comment]
@neVERberleRfellerER No, it'd require passing the actual function scope to `nameMethod` in `es6/classes` transformer instead of the class scope.

**Comment by neVERberleRfellerER** [comment]
Oh, I though that it is what is happening. Howewer, are there any traps?

    function f() {
        console.log('outer');
    }

    class A {
        f() {
            console.log('inner');
            f();
        }
        g() {
            f();
        }
    }

    var a = new A();
    console.log('a.f name is', a.f.name);
    a.f();

Generates

    function f() {
        console.log("outer");
    }

    var A = (function () {
        function A() {
            _classCallCheck(this, A);
        }

        _prototypeProperties(A, null, {
            f: {
                value: (function (_f) {
                    var _fWrapper = function f() {
                        return _f.apply(this, arguments);
                    };

                    _fWrapper.toString = function () {
                        return _f.toString();
                    };

                    return _fWrapper;
                })(function () {
                    console.log("inner");
                    f();
                }),
                writable: true,
                configurable: true
            },
            g: {
                value: function g() {
                    f();
                },
                writable: true,
                configurable: true
            }
        });

        return A;
    })();

    var a = new A();
    console.log("a.f name is", a.f.name);
    a.f();

Outputs

    a.f name is f
    inner
    outer

And with the split these would be used only in this case.

**Comment by hansl** [comment]
Looking at the current REPL, this is not what's happening.

```javascript

function hello() {
  console.log('hello');
}


class World {
  hello() {
    hello();
  }
}
```

generates (on REPL):

```javascript
"use strict";

var _prototypeProperties = function (child, staticProps, instanceProps) { if (staticProps) Object.defineProperties(child, staticProps); if (instanceProps) Object.defineProperties(child.prototype, instanceProps); };

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

function hello() {
  console.log("hello");
}

var World = (function () {
  function World() {
    _classCallCheck(this, World);
  }

  _prototypeProperties(World, null, {
    hello: {
      value: function hello() {
        hello();
      },
      writable: true,
      configurable: true
    }
  });

  return World;
})();
```

in Loose mode:
```javascript
"use strict";

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

function hello() {
  console.log("hello");
}

var World = (function () {
  function World() {
    _classCallCheck(this, World);
  }

  World.prototype.hello = function hello() {
    hello();
  };

  return World;
})();
```

**Comment by neVERberleRfellerER** [comment]
Indeed. What I have written applies to my fix (https://github.com/babel/babel/issues/871#issuecomment-75756926 ; sebmck reaction suggests, that it should not work, but it does. maybe there are conerner cases I don't see).

**Comment by hansl** [comment]
Oh sorry, I thought you were talking about the latest version.  /ignore

**Comment by neVERberleRfellerER** [comment]
My fault. The mesage was written in unfortunate way. I have updated it.

**Comment by sebmck** [comment]
@neVERberleRfellerER The own binding check is necessary as you can safely name:

```javascript
var f = function () {
  var f = 2;
};
```

as there's a local variable that will shadow it so we can just name the function.

**Comment by neVERberleRfellerER** [comment]
@sebmck This thing is a beast. Thank you for info.

**Comment by sebmck** [comment]
Just temporarily disabled the own binding check. It wont have any consequences on the functionality of the transpiled output, it'll just output more verbose output if you have an own binding. Pending #883, this will be properly addressed.
