### ISSUE TITLE
@babel/plugin-proposal-class-properties is ignored in .babelrc

### ISSUE THREAD

**Issue by StephanBijzitter** [babel/babel#8711]
## Bug Report

**Current Behavior**
Babel complains that "Support for the experimental syntax 'classProperties' isn't currently enabled" and tells me to "Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation."

**Input Code**
Massive private codebase, but the following code is more than 2 years old and did work with Babel 6:
<img width="1359" alt="screen shot 2018-09-14 at 15 47 24" src="https://user-images.githubusercontent.com/1649903/45554040-b8529f00-b835-11e8-9a4c-2c1a53eb8bec.png">

**Expected behavior/code**
I don't expect this error to be thrown, seeing I've done exactly what it's proposing I do. Furthermore, I did not expect to need to add this plugin, as I assumed it to be part of preset-env already.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs"
      }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

**Environment**
I'm running jest (23.6.0) with babel-jest (23.6.0) babel 7 (core at 7.0.1)

- Node/npm version: NodeJS 10.9.0 with Yarn 1.9.4
- OS: OSX 10.13.6 (latest at time of writing)
- Monorepo: difficult to say
- How you are using Babel: it's being loaded by Jest

**Additional context/Screenshots**
The following .babelrc did work with version 6 on the same codebase:
```json
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ]
}
```

**Comment by nicolo-ribaudo** [comment]
We don't transpile node_modules by default anymore in Babel 7. You can find some info about the different configs in Babel 6 and Babel 7 at https://babeljs.io/docs/en/config-files.

**Comment by jengo** [comment]
I'm stuck on this problem as well, using react native.  I upgraded to 0.57 which was fine, but now unit tests don't work :(

**Comment by summerangel** [comment]
I've found the solution and tested it, we should create an babel config file named as babel.config.js instead of .babelrc. https://babeljs.io/docs/en/configuration

**Comment by jengo** [comment]
I tried creating a babel.config.js instead of .babelrc and now react-native run-android doesn't work.

error: bundling failed: Error: Cannot find module .babelrc

It also hasn't helped with running unit tests either, still fails with Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

**Comment by summerangel** [comment]
@jengo I'm so sorry,I just use babel.config.js fixed my problem,I'm not react-native environment,I'm using react.and for your project,I think you can still keep the file .babelrc, the .babelrc and babel.config.js can both exists, following is my babel.config.js file looks like, hope can help you:
![babel](https://user-images.githubusercontent.com/12829659/45602341-14444000-ba4f-11e8-826e-82c5ddaa98ec.png)

**Comment by StephanBijzitter** [comment]
@nicolo-ribaudo 
>We don't transpile node_modules by default anymore in Babel 7. You can find some info about the different configs in Babel 6 and Babel 7 at https://babeljs.io/docs/en/config-files.

Part of Jest config:
```js
    transformIgnorePatterns: [
        '/node_modules/(?!@)/'
    ],
```

I assumed this would simply pass on this pattern to Babel as part of the config. However, as it seems it only allows Jest to parse the expression and then send all files that it deems need to be transpiled over to Babel, which in turn decides to ignore the requests from Jest to transpile certain files because they're part of the `node_modules`.

**Indeed changing `.babelrc` into `babel.config.js` worked for me and resolved all my issues.**

This however was not clear to me from the documentation until you emphasised the documentation, as we don't have a mono-repo (or at least not this repo) and as we only have one package.json, I initially thought this part of the documentation didn't apply to my situation as well.

Final config `babel.config.js`:
```js
module.exports = {
    presets: [
        '@babel/preset-env',
        '@babel/preset-react',
        '@babel/preset-typescript'
    ],
    plugins: [
        '@babel/plugin-proposal-class-properties'
    ]
};
```

**Comment by ronilitman** [comment]
@StephanBijzitter Thanks, this worked for me.

**Comment by buildbreakdo** [comment]
Still had issues in spite of having the correct package names. Working in a large mono-repo had to do three things to get this to work:

**package.json**
```
{
  "name": "lambda-starter",
  "version": "1.0.0",
  "description": "Minimalist AWS API Gateway and AWS Lambda starter kit",
  "main": "build/index.js",
  "scripts": {
    "build": "NODE_ENV=production webpack --display-error-details --display-modules",
    "watch": "webpack --watch",
    "test": "jest --verbose --config ./jest.config.js",
    "test:watch": "jest --watch --verbose --config ./jest.config.js",
    "start": "sam local start-api --port 5000",
    "dist": "rm -f dist.zip && zip -jq dist.zip build/index.js",
    "update:dev": "aws lambda update-function-code --function-name DevExample --zip-file fileb://dist.zip --publish",
    "update:prod": "aws lambda update-function-code --function-name ProdExample --zip-file fileb://dist.zip --publish",
    "deploy:dev": "npm run build && npm run test && npm run dist && npm run update:dev",
    "deploy:prod": "npm run build && CI=true npm run test && npm run dist && npm run update:prod"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/buildbreakdo/lambda-starter.git"
  },
  "keywords": [
    "starter",
    "starter-kit",
    "aws-api-gateway",
    "aws-lambda"
  ],
  "author": "Your Name Here",
  "bugs": {
    "url": "https://github.com/buildbreakdo/lambda-starter/issues"
  },
  "homepage": "https://github.com/buildbreakdo/lambda-starter#readme",
  "devDependencies": {
    "@babel/core": "^7.1.6",


    "@babel/plugin-proposal-class-properties": "^7.1.0",


    "@babel/preset-env": "^7.1.6",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "^7.1.4",
    "jest": "^23.6.0",
    "jest-cli": "^23.6.0",
    "webpack": "^4.8.1",
    "webpack-cli": "^3.1.2"
  },
  "dependencies": {
    "node-fetch": "^2.3.0"
  }
}
```

**webpack.config.js**

```
const path = require('path');
const webpack = require('webpack');

module.exports = {
  target: 'node',
  mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
  entry: [ './src/index.js' ],
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'index.js',
    library: 'index',
    libraryTarget: 'commonjs2'
  },
  plugins: [
    new webpack.IgnorePlugin(/^pg-native$/),
    new webpack.DefinePlugin({
      'process.env.BROWSER': false,
      __DEV__: process.env.NODE_ENV !== 'production',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(mjs|js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',


        options: {
          presets: [
            '@babel/preset-env',
            {
              plugins: [
                '@babel/plugin-proposal-class-properties'
              ]
            }
          ]
        },


      }
    ],
  }
};
```

**.babelrc**
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.10"
        }
      }
    ]
  ],


  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]


}
```

What was causing this to not work in our monorepo was not explicitly stating the plugins in the webpack.config.js, even after `yarn add @babel/plugin-proposal-class-properties -D` and adding `@babel/plugin-proposal-class-properties` under plugins in `.babelrc` webpack babel was still not picking up the presence of the plugin. Only after explicitly stating the plugin in webpack.config.js did the project build (even after rm -rf node_modules, yarn).

Base project with this setup is here: https://github.com/buildbreakdo/lambda-starter
