### ISSUE TITLE
Install for Grunt Documentation Not Comprehensive

### ISSUE THREAD

**Issue by rhroyston** [babel/babel#8712]
Following the instructions at [Setup](https://babeljs.io/setup#installation) (for Grunt), one gets the following errors:

```
├── UNMET PEER DEPENDENCY @babel/core@^7.0.0
├── UNMET PEER DEPENDENCY grunt@>=1
```

As an aside, it appears the `#` functionality baked in to web is broken, i.e., I was unable to point you to the `Grunt` specific section of the `Setup` page.

**Comment by existentialism** [comment]
@babel-bot move babel/website

**Comment by existentialism** [comment]
@rhroyston thanks for the issue, going to move this over to the website repo!
