### ISSUE TITLE
REPL throws error when adding @babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by apieceofbart** [babel/babel#8717]
## Bug Report

**Current Behavior**
1. Goto https://babeljs.io/repl. 
2. In plugins sections add `@babel/plugin-proposal-class-properties`.
3. Observer error:
```
[BABEL] repl: Requires Babel "^7.0.0-beta.41", but was loaded with "7.0.0-beta.38". You'll need to update your @babel/core version. (While processing: "base$0")
```

**Input Code**
- REPL or Repo link if applicable:
https://babeljs.io/repl
```js
// no code is needed
```

**Expected behavior/code**
I would expect no error to be thrown
**Babel Configuration (.babelrc, package.json, cli command)**
Default config on babel repl

**Environment**
- Babel version(s): it depends on the repl, sometimes it shows v7.0.0-beta.38, somtimes v7.0.0-beta.39...
- Node/npm version: [e.g. Node 8/npm 5] N/A
- OS: [e.g. OSX 10.13.4, Windows 10] Ubuntu/Chrome
- Monorepo [e.g. yes/no/Lerna] N/A
- How you are using Babel: [e.g. `cli`, `register`, `loader`] REPL

**Possible Solution**

It looks like from the error that REPL should be upgraded to use higher version or not use beta at all.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
This is working now.
