### ISSUE TITLE
`_objectSpread` is not working properly on Chrome Mobile 39

### ISSUE THREAD

**Issue by asuka999** [babel/babel#8721]
## Bug Report

**Current Behavior**
`_objectSpread` is not working properly on Chrome Mobile 39. (which throw `Object.getOwnPropertySymbols called on non-object`) 

**Input Code**
[repl of example code](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBCELwQ3gOmQCgGYgDYGcCmEAyAhAC100wHsAuCAcgHdKxMATOgXwEoOg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-0%2Cenv&prettier=false&targets=&version=7.0.0-beta.56&envVersion=7.0.0-beta.55)

```js
var a = { ... (false && ({hello: 'world'})}
```
will transform to
```js
function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; var ownKeys = Object.keys(source); if (typeof Object.getOwnPropertySymbols === 'function') { ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function (sym) { return Object.getOwnPropertyDescriptor(source, sym).enumerable; })); } ownKeys.forEach(function (key) { _defineProperty(target, key, source[key]); }); } return target; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

var a = _objectSpread({}, false && {
  hello: 'world'
});
```

**Expected behavior/code**

I know that there is no bug in babel, cause https://bugs.chromium.org/p/v8/issues/detail?id=3443 

 
**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
   "plugins": [
     ["@babel/plugin-proposal-object-rest-spread", {"loose": false}]  // if loose false, use objectSpread
   ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.56
- Node/npm version: Node 8/npm 5
- OS: OSX 10.10.5
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: cli

**Possible Solution**
Though this is the bug of chrome, but I really recommend that remind people import the ponyfill of 'Object.OwnPropertySymbols' If necessary.

**Comment by milesj** [comment]
ChromeM v39 is *30* versions ago and was released over 4 years ago. Is this something that really needs to be supported?

**Comment by asuka999** [comment]
em.. That's the reason why I say if necessary. Since Babel is widely used today, it is unavoidable to encounter such a situation that the host application run on ChromeM 39.

**Comment by nicolo-ribaudo** [comment]
Is this still a problem? We refactored that helper a few months ago.
