### ISSUE TITLE
[Solved] ReferenceError: Unknown option: .rootMode.

### ISSUE THREAD

**Issue by lukebatchelor** [babel/babel#8722]
## Bug Report

Just posting this in case someone else finds themselves in this very obscure situation.

If you, for whatever reason have @babel/core 7.0.0 installed and also @babel/cli 7.1.0, you'll get this error as they are incompatible.

This might happen, for example, if you have a mono-repo where one package uses @babel/core 7.0.0 (before 7.1.0 was released) then go to upgrade the rest of the repo to use babel 7 at a later date (after 7.1.0 is released).

I realised it's probably super unlikely now, but just in case, I hope this helps

**Current Behavior**

Fixed in 7.1.0

**Environment**
- @babel/core 7.0.0
- @babel/cli 7.1.1
- Node/npm version: 8
- OS: OSX 10.13.4
- Monorepo yes (bolt)
- How you are using Babel: cli

**Comment by loganfsmyth** [comment]
FYI, I've posted #8728 to fix this. While it's a super easy thing to fix anyway, it is still regression, so thanks for reporting it :)
