### ISSUE TITLE
@babel/runtime missing LICENSE file

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [babel/babel#8729]
Recently, LICENSE files were added to packages/* for Babel 7 and Babel 6 (I think). However, packages/babel-runtime appears to be missing its LICENSE file.

Can a LICENSE file please be added to packages/babel-runtime, like with the other packages?

**Comment by xtuc** [comment]
Duplicated https://github.com/babel/babel/pull/7308.

The latest versions of `@babel/runtime` includes a license.

**Comment by Bosch-Eli-Black** [comment]
Hi @xtuc,

Thanks for the response. I'm aware of the change where LICENSE files were added to the packages, but I'm still not seeing a LICENSE file in @babel/runtime. All of the other package have them, but @babel/runtime doesn't.

**Comment by loganfsmyth** [comment]
@Bosch-Eli-Black It seems to be there from what I can see: <img width="602" alt="screen shot 2018-09-18 at 11 41 04 pm" src="https://user-images.githubusercontent.com/132260/45735324-5b8c1700-bb9c-11e8-926a-8effe5097cbd.png">

**Comment by Bosch-Eli-Black** [comment]
Hi @loganfsmyth,

Hmm... strange.

I just tried out the 7.0.0-rc.1 release of @babel/runtime and I'm not seeing the LICENSE file. (I was going to post a picture, but I'm getting a "No 'Access-Control-Allow-Origin' header present" error message when I try :\)

I'm seeing LICENSE files in all of the other packages/* directories, though.

**Comment by loganfsmyth** [comment]
`7.0.0-rc.1` was before we added the LICENSE files.

**Comment by Bosch-Eli-Black** [comment]
@loganfsmyth Ah, okay, my bad. Thanks for helping out with this :)
