### ISSUE TITLE
Explicit type arguments in call expressions produce a syntax error

### ISSUE THREAD

**Issue by gomesalexandre** [babel/babel#8732]
## Bug Report

**Current Behavior**
Trying to use a type argument in a call expression, however this produces a syntax error. Flow itself and my editor don't produce any.
**Input Code**
```js
  const { someProp } = await callApi<{}>(
     // Awesome logic here 
  );
```

**Expected behavior/code**
As per [flow 0.72](https://github.com/facebook/flow/blob/master/Changelog.md#0720) update, this syntax is now parsed. However, it seems that `babel` isn't able to parse it yet
**Babel Configuration (.babelrc, package.json, cli command)**

```shell
$ grep "babel" package.json
```
```js
    "@babel/plugin-syntax-flow": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/types": "7.0.0-beta.44",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.1.2",
    "babel-jest": "^23.0.1",
    "babel-loader": "^8.0.2",
    "babel-plugin-flow-react-proptypes": "^10.0.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-object-entries": "^1.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.10",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.11.1",
    "@babel/core": "^7.1.0",
    "babel": "^6.23.0",
    "babel-polyfill": "^6.13.0",
    "babel-runtime": "^6.23.0",
```

**Environment**
- Babel version(s): [e.g. v6.26]
- Node/npm version: v8.11.3 / 6.1.0
- OS: OSX 10.13.6
- Monorepo: No
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
It has been fixed in Babel 7 (https://github.com/babel/babel/pull/7934).
Why are you mixing Babel 6 and 7?

**Comment by gomesalexandre** [comment]
Thanks for the answer  @nicolo-ribaudo 
Still using Babel 6 mostly in the project, will switch to 7 then 👍
