### ISSUE TITLE
Question: What can I do if I want to add/overwrite a helper

### ISSUE THREAD

**Issue by Gcaufy** [babel/babel#8736]
For example, If I want to overwrite the [typeof helper](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L13) in a 3rd party plugin, What can I do?

I checked the code, and seems there isn't a way for user to customize the helpers.
https://github.com/babel/babel/blob/master/packages/babel-helpers/src/index.js#L232

**Comment by Gcaufy** [comment]
Similar issue: https://github.com/babel/babel/issues/6487

**Comment by nicolo-ribaudo** [comment]
Why would you want to do that? Helpers are an internal details of how plugins work: we could decide to not use the `_typeof` helper anymore at any time, or to replace it with a different helper.
If you want to use a smaller helper, we could add it to the `loose` mode of the `typeof` plugin.
If you just want to transform the code with a different helper, you need a new Babel plugin.
