### ISSUE TITLE
[TypeScript] Unexpected token, expected ")"

### ISSUE THREAD

**Issue by brunolemos** [babel/babel#8745]
## Bug Report

**Current Behavior**
Code fails with Babel, works with TSC.

**Input Code**

  - [Babel REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=C4TwDgpgBAsiAq5oF4oAoDeVgAsIFtoBfALii1wIjIGdgAnASwDsBzKIgSimQD4o6TNgChhAYwD2zOlAAeZOIkg9yRIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.0.0-beta.54&envVersion=) (ps: needs to install the `@babel/plugin-transform-typescript` plugin)
  - [TypeScript Playground](http://www.typescriptlang.org/play/#src=type%20MyType%20%3D%20(%7B%20theme%20%7D%3A%20%7B%20theme%3A%20string%20%7D)%20%3D%3E%20string%0D%0A%0D%0Aconst%20x%3A%20MyType%20%3D%20%7B%7D)

This code fails on Babel but not on TSC:
```ts
type MyType = ({ theme }: { theme: string }) => string

const x: MyType = {}
```

This code works on both:
```ts
type MyType = (param: { theme: string }) => string

const x: MyType = {}
```

**Expected behavior/code**

Support this syntax, because tsc supports it.

**Babel Configuration (.babelrc, package.json, cli command)**

The one inside Create React App v2, plus typescript preset. ([file](https://github.com/brunolemos/create-react-app/blob/next-typescript/packages/babel-preset-react-app/create.js))

**Environment**
- Babel version(s): 7.1.0
- Node/npm version: 5.6.0
- OS: macOS 10.14
- Monorepo yes (yarn workspace)
- How you are using Babel: CRA

**Additional context**

Possibly related: #8365

**Comment by milesj** [comment]
I'm curious what use case you have for destructuring in a type?

**Comment by brunolemos** [comment]
@milesj none, this is how I write functions, so I wrote this way in the type, both ways are fine for me. But it should work.

**Comment by jshearer** [comment]
I just got caught on this upgrading my react-native version to 0.57, which uses babel 7. I see this was merged 9 days ago (thank you @danez !), any idea when 7.1.7 will be released?
