### ISSUE TITLE
The lack of runtime error in babel 6. Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by Whispers12** [babel/babel#8747]
## Bug Report

**Current Behavior**
In babel 6, i havent runtime error when call function with spreaded object (look at js snippet where i call test2).

**Input Code**
```js
const a = { k1: 1221 };

function test2(a1, a2, a3, a4) {
  console.log(a1, a2, a3, a4);
}

function test({ b, ...rest }) {
  const result = {
    b,
    ...rest
  };
  console.log("test", result);
  test2(...rest);
}

test(a);

```

**Expected behavior/code**
I think it would be better if we have runtime error like in babel 7. Invalid attempt to spread non-iterable instance.

```js
{
  "babel-cli": "^6.26.0",
   "babel-core": "^6.26.3",
   "babel-eslint": "^8.2.3",
   "babel-loader": "^7.1.2",
}
```

**Environment**
- Babel version(s): [e.g. v6.2.6, v7.0.0]
- Node/npm version: [e.g. Node 8.9.4/npm 6.2.0]
- How you are using Babel: loader

**Possible Solution**
Implement same exceptions like in babel 7

**Comment by nicolo-ribaudo** [comment]
Babel 6 hasn't been not been maintained for a few months; I'm closing this issue since, as noted, correctly throws in Babel 7.
