### ISSUE TITLE
Spread operator mismatches native behavior when getter is used

### ISSUE THREAD

**Issue by Draccoz** [babel/babel#8749]
## Bug Report

**Current Behavior**
When using object spread on an object with a getter, the function is triggered only once, and the result is copied to the output object.

**Input Code**

```js
let counter = 0;

const x = { a: 1 };
const y = { ...x, get b() { counter++; return 2; } };
y.b;
y.b;

console.assert(counter === 2);
```

**Expected behavior/code**
Getter should be created in the output object so it can be triggered on each property access, as it happens with native browser implementation.

**Babel Configuration (.babelrc, package.json, cli command)**
Anything that compiles to ES5.

**Environment**
Any

**Possible Solution**
Use `Object.getOwnPropertyDescriptors(input)` to get a configuration of each input object and in case of getters/setters define them in the output object.

**Additional context/Screenshots**
This bug happens in both Babel and TypeScript, looks to be pretty common.

**Comment by mathieutu** [comment]
The same here:
```ts
{
  ...attributes,
  get fullName() {
    return `${this.firstName} ${this.lastName}`.trim()
  },
}
```

Will transpile to (pseudo code): 
```js
Object.assign({}, attributes, {
   get fullName() {
    return `${this.firstName} ${this.lastName}`.trim()
  }
})
```

so all this.* parameters will be undefined.

Works well in browser with direct spread operators.

**Comment by mathieutu** [comment]
Actually I found: 
https://github.com/babel/babel/issues/7524
https://github.com/babel/babel/pull/7034
https://github.com/babel/babel/issues/9322
and https://babeljs.io/docs/en/next/babel-plugin-proposal-object-rest-spread.html

About this topic.
This should be handled by now, I don't understand why it isn't working on our own.

I'm using a brand new create-react-app... 🤔

**Comment by nicolo-ribaudo** [comment]
This has been fixed: https://babeljs.io/repl#?browsers=node%205.0.0&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAxg9grgOzCAThAvBADAbgFB6wIDOkAHhhAN4QCGAXBAIwQC--RpEAnpTQHSCyAGggBzcBABGACgCU1aPCSoA1KpwQU4OCgQQATJtZt83flLMX8hGCRih-tYsVRgZsRMjTpfhuThAA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=
