### ISSUE TITLE
duplicate external helpers content at beginning of each output file

### ISSUE THREAD

**Issue by jokeyrhyme** [babel/babel#875]
I originally reported this against a downstream project: https://github.com/hailocab/react-pure/issues/2

I think it's terrific that Babel doesn't just dump the entire external helpers file everywhere, or requires the whole thing to be used by every project, because that's effectively what traceur ends up doing and for small projects it ends up being quite bloated.

However, I've noticed that a small set of helpers is being duplicated across every file in the aforementioned project.  I've read about helpers here:
https://babeljs.io/docs/usage/external-helpers/

There doesn't seem to actually be a way to disable the helpers. The default behaviour seems to be:
```sh
babel --external-helpers
```
and the following doesn't change the behaviour:
```sh
babel --no-external-helpers
```

Is there a way to have Babel output a deduplicated centralised module (or modules) for the tailored set of helpers, and automatically have `require()` statements injected into the output where the duplicated content used to be?

**Comment by jokeyrhyme** [comment]
Also, what if `_interopRequire`, `_objectWithoutProperties`, and `_extends` where output to separate files? Or where individually addressable as requirements?

For example, instead of this:
```javascript
require("babel/external-helpers");
```
have this:
```javascript
require("babel/external-helpers/interop-require");
require("babel/external-helpers/object-without-properties");
require("babel/external-helpers/extends");
```

**Comment by sebmck** [comment]
The [runtime](https://babeljs.io/docs/usage/runtime/) does exactly this already.

**Comment by jokeyrhyme** [comment]
Awesome. Cheers! <3

**Comment by dexbol** [comment]
[runtime](https://babeljs.io/docs/usage/runtime/) was 404 now.
