### ISSUE TITLE
Typescript: constructor auto-assign not working in 7.1

### ISSUE THREAD

**Issue by mkusher** [babel/babel#8752]
## Bug Report

**Current Behavior**
Constructor auto-assign not working with `@babel/preset-typescript@7.1`, however it works with `@babel/plugin-transform-typescript@7.1`.

**Input Code**
- Input code is same that used in test: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/test/fixtures/class/parameter-properties-with-class/input.js

```js
class Person {
  constructor(public name: string) {}
}
```

**Expected behavior/code**
The result should be same as in test https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/test/fixtures/class/parameter-properties-with-class/output.js

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["preset-typescript"],
  "plugins": ["transform-classes"]
}
```

**Environment**
- Babel version(s): 7.1
- Node/npm version: Node 10/npm 6
- OS: OSX 10.13.4
- How you are using Babel: cli

**Possible Solution**
You can avoid this bug if you use `@babel/plugin-transform-typescript` instead of `@babel/preset-typescript`

**Comment by hcomnetworkers** [comment]
We have the same problem in combination with 'preset-env'. The constructor properties are gone after the build. But only if we compile for browsers 'last 2 versions'. If we compile for 'last 2 Chrome versions', the properties exist.

babel.config.js
```js
module.exports = function (api) {
  api.cache(false);
  return {
    'presets': [
      '@babel/typescript',
      [
        '@babel/preset-env',
        {
          'targets': {
            'browsers': ['last 2 versions'],
          },
          'modules': false,
        },
      ],
    ],
  };
};
```

package.json
```json
{
  "name": "foo",
  "version": "1.0.0",
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-typescript": "^7.3.3",
    "@babel/runtime": "^7.4.3",
    "babel-loader": "^8.0.5",
    "typescript": "^3.4.3",
    "webpack": "4.29.6",
    "webpack-cli": "^3.1.2"
  },
  "dependencies": {},
  "scripts": {
    "build": "webpack"
  }
}
```

webpack.config.js
```js
const path = require('path');

module.exports = function () {
  return {
    mode: 'production',
    module: {
      rules: [
        {
          test: /\.(js|ts)$/,
          exclude: [/node_modules/],
          use: [{loader: 'babel-loader'}],
        },
      ],
    },
    entry: {
      Foo: [
        path.resolve(__dirname, 'Foo.ts'),
      ],
    },
  };
};
```

Foo.ts
```ts
class Foo {

    constructor(private readonly bar: string) {
    }

    log() {
        console.log(this.bar);
    }
}

(() => (new Foo('baz')).log())();
```

Run 
```bash
npm install
npm run build
node dist/Foo.js
```
The output should be 'baz' and not 'undefined'.

**Comment by dyatko** [comment]
@hcomnetworkers swapping presets helped me (first env and then typescript)

**Comment by nicolo-ribaudo** [comment]
This is working now: https://babeljs.io/repl#?browsers=node%205.0.0&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAKCmAnCB7AdtA3gKGtY6EALogK7BEqIAUADqQEYgCWw0aYAtvAFzTGJmaAOYBKLAF9sEoA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=
