### ISSUE TITLE
Typescript + React + Babel, warning setState, props syntax.

### ISSUE THREAD

**Issue by hg-pyun** [babel/babel#8757]
Hello.
I currently use a combination of babel and typescript. It's a very nice project.
With React, warnings appear in `this.setState` and `this.props`. How do I clear this? Compile operates normally.
![image](https://user-images.githubusercontent.com/10627668/45938875-066f5b80-c009-11e8-952c-4059c7819cc0.png)

Thank you :D

**Comment by milesj** [comment]
@hg-pyun This isn't a Babel issue, this is TypeScript. I'd suggest taking this somewhere else.

That being said, be sure to install `@types/react`.

**Comment by hg-pyun** [comment]
@milesj Should I installed `@babel/preset-typescript`. `@types/react` required?

**Comment by hg-pyun** [comment]
@milesj I got it. thank you!
