### ISSUE TITLE
@jsx pragma ignored if not in the first comment

### ISSUE THREAD

**Issue by brandonhorst** [babel/babel#876]
I'm working with the custom JSX transforms from https://github.com/babel/babel/issues/841. The @jsx pragma is ignored unless it is the very first comment.

```js
/** @jsx x */
<test />
```
becomes
```js
/** @jsx x */
x("test", null);
```
but
```js
/**/
/** @jsx x */
<test />
```
becomes
```js
React.createElement("test", null);
```

This could be a problem if folks have other comment pragmas (like linter directives) that like to hang out at the tops of files.

**Comment by Dashed** [comment]
I think it's safe to assume that, generally, comments won't be preserved. There are many issues with comments in transformed code.

**Comment by brandonhorst** [comment]
@Dashed That's not the issue, I don't care what comments are transpiled.

Since https://github.com/babel/babel/commit/35bd5109304dcddb6daa6f60263241418d2a2124 Babel itself makes use of the `/** @jsx ... */` comment to change the generated code (see `x` vs `React.createElement` above). The problem is that this only works if it is the very first comment in the file.

**Comment by brandonhorst** [comment]
You are the man @sebmck
