### ISSUE TITLE
@babel/plugin-transform-runtime inlined helpers

### ISSUE THREAD

**Issue by Genuifx** [babel/babel#8766]
## Bug Report

**Current Behavior**
@babel/plugin-transform-runtime inlined helpers that used by @babel/plugin-proposal-decorators.

**Input Code**
- REPL or Repo link if applicable:

```js
function Test(target, key, descriptor) {
    return descriptor
}

@Test
class Main {
    constructor() {

    }

    foo() {
        console.log('foo')
    }
}
```

**Expected behavior/code**
@babel/plugin-transform-runtime remove inline helpers, replace with `require` expression.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "sourceMap": false,
    "presets": [
        [
            "@babel/preset-env"
        ]
    ],
    "plugins": [
        ["@babel/plugin-proposal-decorators", {"decoratorsBeforeExport": true}],
        ["@babel/plugin-transform-runtime", {"corejs": false}]
    ]
}
```

**Environment**
- Babel version(s): 7.1.0
- Node/npm version: node v9.5.0, npm v5.6.0
- OS: macOS: 10.13.2
- Monorepo: no
- How you are using Babel: cli

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/10156994/45996902-7268c700-c0d0-11e8-873e-26421a4d9b30.png)

**Comment by nicolo-ribaudo** [comment]
`@babel/plugin-transform-runtime` must output code compatible with `@babel/runtime@^7.0.0`, but the `decorate` helper has been introduced in version 7.1.0. You can specify it:
```json
{
    "sourceMap": false,
    "presets": [
        [
            "@babel/preset-env"
        ]
    ],
    "plugins": [
        ["@babel/plugin-proposal-decorators", {"decoratorsBeforeExport": true}],
        ["@babel/plugin-transform-runtime", {"corejs": false, "version": "7.1.0"}]
    ]
}
```

**Comment by Genuifx** [comment]
@nicolo-ribaudo 
emmm, do not find @babel/runtime@7.1.0
![image](https://user-images.githubusercontent.com/10156994/46003058-33dc0800-c0e2-11e8-9988-589a80765640.png)

**Comment by Genuifx** [comment]
@nicolo-ribaudo otherwise, the `version` option is not in the documentation. https://babeljs.io/docs/en/babel-plugin-transform-runtime

**Comment by nicolo-ribaudo** [comment]
Ok, it is probably a bug in our publishing process.

**Comment by Genuifx** [comment]
@nicolo-ribaudo so, we still need to specify the version in the transform-runtime plugin?

**Comment by nicolo-ribaudo** [comment]
Yes, because we must be compatible by default even with `@babel/runtime@7.0.0` by default.

**Comment by adriengibrat** [comment]
**Babel Configuration (babel.config.json)**
```
{
    presets: [
      '@babel/preset-typescript'
    ],
    plugins: [
      ['@babel/plugin-transform-runtime', { useESModules: true }],
      ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }],
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-optional-chaining'
    ].filter(Boolean),
  }
```

**Environment**
Babel version(s): 7.10.3
@babel/plugin-proposal-class-properties: 7.10.1
@babel/plugin-proposal-decorators: 7.10.3
@babel/plugin-transform-runtime: 7.10.3
Node/npm version: node v12.16.2, npm v6.14.4
OS: linux mint
Monorepo: no
How you are using Babel: cli 7.10.3 and rollup (@rollup/plugin-babel 5.0.4)

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/62407/85333996-d6553500-b4da-11ea-84a5-8da7bde5c98b.png)

`plugin-proposal-decorators` with option `{ legacy: true }` does have helpers replaced with import expression, but the stage 2 version adds 11.4kb !!, in my case in every single web component file (~2kb)...

Does someone knows a viable workaround or alternative ?

**Comment by nicolo-ribaudo** [comment]
Did you try configuring `transform-runtime` as shown above? (https://github.com/babel/babel/issues/8766#issuecomment-424246989)

**Comment by adriengibrat** [comment]
Thanks ;)
my bad:
```
 ['@babel/plugin-transform-runtime', { useESModules: true, version: "7.10.3" }],
```
did solve the issue!

**Comment by nicolo-ribaudo** [comment]
This is now documented: https://babeljs.io/docs/en/babel-plugin-transform-runtime#version
