### ISSUE TITLE
@babel/generator: missing parens cases with JSXElement

### ISSUE THREAD

**Issue by mingxian** [babel/babel#8771]
## Bug Report

**Current Behavior**
@babel/core@7.1.0,  when generating code by calling "transformFromAstSync", some parentheses are missing

**Input Code**

```js
var jsx = (
  <div><a /></div>
);
```

**Expected behavior/code**

should ouput the same thing:

```js

var jsx = (
  <div><a /></div>
);

```

but instead:

```js
var jsx = 
  <div><a /></div>;

```

**Babel Configuration (.babelrc, package.json, cli command)**

**Environment**
- Babel version(s): @babel/core@7.1.0
- Node/npm version: node: v8.12.0/npm: 6.4.1
- OS: OSX 10.13.6
- Monorepo no
- How you are using Babel:  require('@babel/core')

**Possible Solution**

maybe should keep the same logic with babelv6.

**Comment by nicolo-ribaudo** [comment]
Currently Babel outputs

```js
var jsx = <div><a /></div>;
```

But even your output (with the newline) is correct: parentheses are not needed here. Babel doesn't make any guarantee about its output formatting.
