### ISSUE TITLE
memory overflow when handling large file

### ISSUE THREAD

**Issue by wxminigame1** [babel/babel#8772]
## Bug Report
file size 7MB，more than 200,000 lines
**Current Behavior**
<--- Last few GCs --->

   55097 ms: Mark-sweep 1359.0 (1436.3) -> 1359.0 (1436.3) MB, 1650.6 / 0.0 ms [allocation failure] [GC in old space requested].
   56550 ms: Mark-sweep 1359.0 (1436.3) -> 1359.0 (1436.3) MB, 1452.4 / 0.0 ms [allocation failure] [GC in old space requested].
   57978 ms: Mark-sweep 1359.0 (1436.3) -> 1358.9 (1420.3) MB, 1428.3 / 0.0 ms [last resort gc].
   59432 ms: Mark-sweep 1358.9 (1420.3) -> 1358.9 (1420.3) MB, 1453.8 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x336f39acfb39 <JS Object>
    1: popContext [/Users/addy/Documents/test/node_modules/babel-traverse/lib/path/context.js:~222] [pc=0x27b547014c63] (this=0x2140c3932bd9 <a NodePath with map 0x1fe823818a49>)
    2: visitQueue [/Users/addy/Documents/test/node_modules/babel-traverse/lib/context.js:~114] [pc=0x27b547dfaf45] (this=0x2140c3932b71 <a TraversalContext with map 0x1fe823818c01>,queue=0x2140c3932bb9 <JS Array[1]>)
 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [/usr/local/bin/node]
 6: v8::internal::Object::ToString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
 7: v8::internal::Object::ConvertToName(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
 8: v8::internal::LookupIterator::PropertyOrElement(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, bool*, v8::internal::LookupIterator::Configuration) [/usr/local/bin/node]
 9: v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
10: v8::internal::Runtime_KeyedGetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x27b546d092a7
Abort trap: 6

**Comment by liuxingbaoyu** [comment]
Since this issue is outdated, I'll close it, feel free to open a new issue if there are still issues.
