### ISSUE TITLE
i find when i use npm run dev  and find not can open my project in safari  

### ISSUE THREAD

**Issue by roy201603** [babel/babel#8776]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
in safari i not can open my project  and told us  'const' are not supposed in strict mode 
**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```
{
  "presets": [
    "es2015" ,
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime","transform-es2015-block-scoping"]
}

**Environment**
- Babel version(s): babel-core:6.22.1 babel-loader: 7.1.1
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]
 loader
**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/25165512/46121286-b204ef80-c245-11e8-9a77-8b603b2107cf.png)

**Comment by hzoo** [comment]
If this is via webpack (I see loader) then your deps are using const as well so you'd need to compile those with babel or use another dep that is compiled https://stackoverflow.com/questions/33878586/safari-babel-webpack-const-declarations-are-not-supported-in-strict-mode
