### ISSUE TITLE
7.1.0 packages are still not published in npm. Why?

### ISSUE THREAD

**Issue by deser** [babel/babel#8778]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Slack Community Chat: https://babeljs.slack.com (you can sign-up at https://slack.babeljs.io/ for an invite)
* StackOverflow: https://stackoverflow.com/questions/tagged/babeljs using the tag `babeljs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/babeljs
* Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by nicolo-ribaudo** [comment]
We only republish packages which change. Many are still attend 7.0.0 because there were no changes since then.

**Comment by deser** [comment]
Thanks

**Comment by rjgotten** [comment]
> The only package which is still at 7.0.0 but should be at 7.1.0 is `@babel/runtime`. We will fix it in the next release.

And `@babel/runtime-corejs2`.
You updated `@babel/plugin-transform-runtime` to restore the erroneously removed `Math` methods, but didn't bother to update the corejs2 runtime to reinclude the polyfill hookups.
Builds now complain that `@babel/runtime-corejs2/core-js/math/trunc` etc. are missing.

**Comment by hzoo** [comment]
Yeah there was an issue in the publishing processes as there are no diffs in the package itself but it's changed based on if the helpers change so we need to force publish it. https://github.com/babel/babel/releases/tag/v7.1.1
