### ISSUE TITLE
Shim causing error with specific RegExp

### ISSUE THREAD

**Issue by wiredprairie** [babel/babel#878]
I've been trying to get babel working with a node package that ultimate requires the package [xregexp](https://github.com/slevithan/XRegExp). I've narrowed the problem down so it's simple to reproduce.

If I create a simple script and install these two packages:

    > npm install babel
    > npm install xregexp

#### test.js - SUCCEEDS

    var xregexp = require('xregexp');

#### test.js - FAILS

    require("babel/register");
    var xregexp = require('xregexp');

I don't follow what the shim is trying to do, so I don't know how to attempt to fix it. 

Here is the stack trace for the error that happens:

    D:\TEMP\babel-issue1\node_modules\babel\node_modules\core-js\shim.js:1150
            ? pattern.source : pattern, flags);
                               ^
    SyntaxError: Invalid flags supplied to RegExp constructor 'gy'
        at RegExp (native)
        at new RegExp (D:\TEMP\babel-issue1\node_modules\babel\node_modules\core-js\shim.js:1150:28)
        at copy (D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:154:29)
        at addToken.on (D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:393:30)
        at D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:1138:5
        at Object.<anonymous> (D:\TEMP\babel-issue1\node_modules\xregexp\xregexp-all.js:1267:2)
        at Module._compile (module.js:460:26)
        at Module._extensions..js (module.js:478:10)
        at Object.require.extensions.(anonymous function) [as .js] (D:\TEMP\babel-issue1\node_modules\babel\lib\babel\api\register\node.js:113:7)
        at Module.load (module.js:355:32)

**Comment by sebmck** [comment]
This should be reported on the [core-js](https://github.com/zloirock/core-js) repo, it's a completely separate project. It's a known issue and it lies in xregexp as it has extremely broken feature detection, see [this](https://gitter.im/babel/babel?at=54eab9abb2f5a2a728a21bbd) discussion on gitter for more.

**Comment by wiredprairie** [comment]
OK ... although its bugs break your project. :(

**Comment by wiredprairie** [comment]
Apparently, [this bug](https://github.com/zloirock/core-js/issues/36) was fixed in core-js 0.60 which is not targeted by Babel.

**Comment by sebmck** [comment]
Just so we're clear, it's not a bug in core-js, core-js just added a work around for xregexp's buggy behaviour. Was "fixed" as of 4.4.6 (see 3ce9508a1c2828c2534a6ff7861d16b58201c597), thanks!

**Comment by wiredprairie** [comment]
OK -- thanks for the clarification. I definitely wasn't familiar with any of the code that was having issues and after spelunking far too long yesterday, I gave up and decided to post the issue I was having once I finally had simplified it to just two lines of code. The issue manifested itself extremely deeply in a node_module dependency, so it took some time to find: 

`web\node_modules\mailgun-js\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\node_modules\ftp\node_modules\xregexp\xregexp-all.js`

I appreciate the quick response!

**Comment by sebmck** [comment]
All good, thanks for the report!
