### ISSUE TITLE
Babel is confused by a package.json file in a subdirectory

### ISSUE THREAD

**Issue by wereHamster** [babel/babel#8781]
# v7 Regression

I have a monorepo (standard lerna setup) where I install babel in the root and use that to compile files across all packages. Babel 7 fails to compile files inside the packages, but only if there is a `package.json` file present. When I remove the file babel works. Files outside of these directories can be compiled just fine (eg. `root.tsx` in the below example).

This is my directory structure:

```
├── .babelrc
├── package.json
├── root.tsx
└── packages
    └── foo
        ├── package.json
        └── index.tsx
```

I use only the babel typescript preset, and the failure appears to be due to that preset not being loaded when compiling the `index.tsx` file.

.babelrc:

```json
{
  "presets": ["@babel/preset-typescript"]
}
```

index.tsx:

```js
export type foo = number
export default (): foo => 1
```

command:

```
./node_modules/.bin/babel packages/foo/index.tsx
```

output:

```
{ SyntaxError: …/packages/foo/test.tsx: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):

> 1 | export type foo = number
    |        ^
  2 | export default (): foo => 1
  3 |
```

**Environment**
- Babel version(s):7.1.0
- Node/npm version: node 10
- Monorepo: yes/Lerna
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
It's the expected behavior. `.babelrc` config doesn't leak across package boundaries: if you want to apply a config to your subpackages, you should use `babel.config.js`. 
You can read https://babeljs.io/docs/en/config-files for more information.

**Comment by wereHamster** [comment]
You are right, once I renamed `.babelrc` to `babel.config.js` I was able to build the packages.

While the *Config Files* documentation page nicely explains the whole situation, this breaking change is not mentioned on the *Upgrade to Babel 7* page.

**Comment by hzoo** [comment]
Ok thanks @wereHamster, we should add it to the upgrade page if it's not there.
