### ISSUE TITLE
Recursion within async functions

### ISSUE THREAD

**Issue by nathan3000** [babel/babel#8783]
## Bug Report

**Current Behavior**
When trying to upgrade to Babel 7. Calling async function from within self-invoking function now causes `ReferenceError: poll is not defined`.

**Input Code**
```js
(async function poll() {
  console.log(await Promise.resolve('Hello'))
  setTimeout(poll, 1000);
})();
```
**Transformed Code**
```js
(function () {
  var _poll = _asyncToGenerator(
  /*#__PURE__*/
  regeneratorRuntime.mark(function _callee() {
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.t0 = console;
            _context.next = 3;
            return Promise.resolve('Hello');

          case 3:
            _context.t1 = _context.sent;

            _context.t0.log.call(_context.t0, _context.t1);

            setTimeout(poll, 1000);

          case 6:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function poll() {
    return _poll.apply(this, arguments);
  };
})()();
```

**Error**
```js
Applications.js:64 Uncaught (in promise) ReferenceError: poll is not defined
    at _callee$ (Applications.js:64)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(anonymous function) [as next] (webpack:///./node_modules/regenerator-runtime/runtime.js?:114:21)
    at asyncGeneratorStep (Applications.js:19)
    at _next (Applications.js:21)
```

**Expected behavior/code**
Recursively calls async function.

**Babel Configuration (babel.config.js, webpack.config.js)**

```js
module.exports = function (api) {
    api.cache(true)
    const presets = [ '@babel/preset-env', '@babel/preset-react' ];
    const plugins = [ '@babel/plugin-proposal-class-properties' ];
  
    return {
      presets,
      plugins
    };
  }
```

Using @babel/polyfill in webpack.config.js
```js
entry: {
  react: ['@babel/polyfill', './index.js']
},
```

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: v8.9.0
- OS: OSX 10.12.6
- Monorepo: no
- How you are using Babel: loader

**Additional context/Screenshots**
<img width="484" alt="screen shot 2018-09-28 at 12 33 51" src="https://user-images.githubusercontent.com/734863/46206095-d7aff880-c31a-11e8-813b-18812f223064.png">

**Comment by GriffinSauce** [comment]
@nathan3000 I ran into the same issue and found a temporary workaround:
```.js
async function poll() {
    setTimeout(repoll, 1000); // eslint-disable-line no-use-before-define
}

function repoll(...args) {
  return poll(...args);
}
```
YMMV but it might help until the actual problem is fixed.

**Comment by nathan3000** [comment]
Thanks @GriffinSauce. I'll go with that for now.

**Comment by yairEO** [comment]
How did such a huge bug didn't failed a test? 

This is a serious issue because it breaks a common practice

**Comment by nicolo-ribaudo** [comment]
Note: I suggest debugging this by only enabling `@babel/plugin-transform-async-to-generator`, since `regenerator` (used by the presets) adds a lot of noise.
