### ISSUE TITLE
@babel/template desn't in @babel/parser

### ISSUE THREAD

**Issue by joebnb** [babel/babel#8784]
![image](https://user-images.githubusercontent.com/1646883/46242730-b7f20080-c3fe-11e8-94f5-2085028eb050.png)

**Comment by nicolo-ribaudo** [comment]
That package exists 🤔 https://www.npmjs.com/package/@babel/parser

Are you using a proxy or a private registry for npm? If so, clear the cache.
Also, clear your local npm cache.

**Comment by joebnb** [comment]
this problem cause by private registry ,sorry for report this

**Comment by joebnb** [comment]
> That package exists 🤔 https://www.npmjs.com/package/@babel/parser
> 
> Are you using a proxy or a private registry for npm? If so, clear the cache.
> Also, clear your local npm cache.

thx for advice
