### ISSUE TITLE
React Native - bundling failed: Error: Unable to resolve module `http`

### ISSUE THREAD

**Issue by elango** [babel/babel#8786]
bundling failed: Error: Unable to resolve module `http` from `/Volumes/{user}/node_modules/node-fetch/index.js`: Module `http` does not exist in the Haste module map

Anyidea how to resolve this?

Thanks

**Comment by nicolo-ribaudo** [comment]
This has nothing to do with Babel. I suggest asking on stackoverflow or opening an issue to the react native bundler repo.
