### ISSUE TITLE
inferBabelVersion is not defined

### ISSUE THREAD

**Issue by sriharikapu** [babel/babel#8788]
# v7 Regression

**Expected behavior/code**
I have the code of a react app and inside which am using babel package
When am trying to start the app usiing 

``` npm start ```

The follwoing error is occuring.. I need your assistance on this.. 

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- OS: [e.g. OSX Mojave, ]

![screen shot 2018-09-30 at 7 42 25 pm](https://user-images.githubusercontent.com/6247133/46257267-65414300-c4e9-11e8-8ec0-67d4d43a16e1.png)

**Comment by sriharikapu** [comment]
![screen shot 2018-09-30 at 7 50 20 pm](https://user-images.githubusercontent.com/6247133/46257328-560ec500-c4ea-11e8-9560-89eac78bb442.png)

**Comment by loganfsmyth** [comment]
That looks to be an issue with `parcel-bundler`, not Babel.
