### ISSUE TITLE
Super and this

### ISSUE THREAD

**Issue by gsklee** [babel/babel#879]
Here's a React component snippet:

```javascript
class Something extends React.Component {

...

  componentWillMount() {
    DataStore.addChangeListener(this.onStoreChange);
  }

...

  onStoreChange() {
    super.setState({
      data: DataStore.get()
    });
  }

}
```

I thought this would work but actually it won't, because all `this` inside `super.setState` will still refer to `DataStore`. Is this standard ES6 behavior?

**Comment by sebmck** [comment]
Class methods aren't bound to their instance so you still need to bind it. You can use either:

```javascript
DataStore.addChangeListener(this.onStoreChange.bind(this));
```

*or*:

```javascript
DataStore.addChangeListener(() => this.onStoreChange());
```
