### ISSUE TITLE
Cannot find module '@babel/preset-plugin-syntax-class-properties'

### ISSUE THREAD

**Issue by JamesTheHacker** [babel/babel#8794]
This really needs to be made clear in the documentation especially since the recently changes with removing stages. To the average user Googling around for what they need they land on: 

* Here: https://babeljs.io/docs/en/babel-plugin-transform-class-properties
* Here: https://babeljs.io/docs/en/babel-plugin-proposal-class-properties
* Here: https://www.npmjs.com/package/@babel/plugin-proposal-class-properties
* Here: https://www.npmjs.com/package/babel-plugin-transform-class-properties

https://github.com/babel/babel/issues/7018 was closed yet many people are still having the same problems. Somewhere in the docs it needs to be made absolutely clear for the average developer.

**Comment by nicolo-ribaudo** [comment]
Probably the underlying problem is that you put the plugin in the `presets` section instead of `plugins`.

**Comment by promixmart** [comment]
> Probably the underlying problem is that you put the plugin in the `presets` section instead of `plugins`.

no its not,,, i'm still having the same problem and stuck there

**Comment by nicolo-ribaudo** [comment]
What are your config, your package.json and the exact error message?
