### ISSUE TITLE
Arrow functions within object literals lose 'this' and incorrectly transform 'arguments'

### ISSUE THREAD

**Issue by ArtemGovorov** [babel/babel#880]
Following code
```javascript
console.log(require('babel').transform('var a = { f: () => this };').code);
console.log(require('babel').transform('var a = { f: () => arguments[0] };').code);
```
outputs
```
"use strict";

var a = { f: function () {
    return undefined;
  } };
"use strict";

var _arguments = arguments;
var a = { f: function () {
    return _arguments[0];
  } };
```

**Comment by sebmck** [comment]
This is how arrow functions work. Their `this` and `arguments` are aliased to their parent.

**Comment by ArtemGovorov** [comment]
The parent object is an 'a' object in this case. If you run this code in say io.js (with `--harmony --harmony_arrow_functions` flags):
```javascript
var a = {test: 1, f: () => this.test, g: () => arguments[0]};

console.log(a.f());
console.log(a.g(1));
```
the output will be
```
1
1
```

**Comment by sebmck** [comment]
Arrow functions are incomplete in node. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this) or check the [ES6 spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation):

> **An ArrowFunction does not define local bindings for arguments, super, this, or new.target. Any reference to arguments, super, or this within an ArrowFunction must resolve to a binding in a lexically enclosing environment.** Typically this will be the Function Environment of an immediately enclosing function

This is correct behaviour.

**Comment by sebmck** [comment]
And see the ES6 page on the io.js website [here](https://iojs.org/en/es6.html): 

> On Node.js™@0.12.x (V8 3.28+), the --harmony runtime flag enables all completed, staged and in progress ES6 features together, in bulk (with the exception of proxies which are hidden under --harmony-proxies). **This means that some really buggy or even broken features like Arrow Functions** are just as readily available for developers as generators, which have very little or even no known-issues.

**Comment by ArtemGovorov** [comment]
Makes sense, thanks. 
Interestingly, both FF and io.js are consistently wrong on this one (output 1):
```javascript
var a = {g: () => arguments[0]};
console.log(a.g(1));
```
