### ISSUE TITLE
Plugin: cannot get options from state argument on 'pre'

### ISSUE THREAD

**Issue by ovidijusr** [babel/babel#8800]
## Bug Report

**Current Behavior**
cannot get options (state.opts) from pre function, but returns undefined:

>hello world! undefined

**Input Code**
```js
module.exports = () => ({
  pre(state) {
    console.log('hello world!', state.opts.myOption);
  },
});
```

**Expected behavior/code**
I want to get options in pre function
**Babel Configuration (.babelrc, package.json, cli command)**
```js
 plugins: [
    ['./src/utils/babel/myPlugin', {
      myOption: 'this is variable',
    }],
  ],
```

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: v10.6.0
- OS: OSX 10.14.1
- Monorepo no
- How you are using Babel: though webpack

**Possible Solution**
add method to send arguments though pre

**Comment by loganfsmyth** [comment]
The first argument of `pre` isn't `state`, which is why that is failing. You'd want `this.opts`.

That said, if you don't need to support Babel 6, only 7, it is much easier to get the options up front from the plugin fn argument.

```
module.exports = (api, opts) => ({
  pre() {
    console.log('hello world!', opts.myOption);
  },
});
```
