### ISSUE TITLE
After migration to Babel 7, dynamic import with Promise all does not work in Node 10

### ISSUE THREAD

**Issue by palaniichukdmytro** [babel/babel#8801]
## Bug Report

**Current Behavior**
When I run develop or prod mode, all new plugins, preset are work well. But during unit-test with `mocha` I get an error, that `Error: Not supported
      at Object.all [as fr] (src\intlConfigurations/applicationLocales.js:13:25)`

**Input Code**
- REPL or Repo link if applicable:

```
export const locales = {
    'en': () => Promise.all([
        import('../intl/en'),
        import('date-fns/locale/en-US'),
        import('react-intl/locale-data/en'),
    ]),
    'it': () => Promise.all([
        import('../intl/it'),
        import('date-fns/locale/it'),
        import('react-intl/locale-data/it'),
    ]),
}
```

**Expected behavior/code**
Should support dynamic import and transpile import() to a deferred require(), for node.

**Babel Configuration (.babelrc, package.json, cli command)**

```
const nodeEnv = process.env.NODE_ENV || 'development'
let presetEnvConfig, plugins

if (nodeEnv === 'test') {
    presetEnvConfig = {targets: {node: 'current'}}
    plugins = ['istanbul']
} else {
    presetEnvConfig = {
        targets: {
            browsers: ['last 1 versions', 'ie >= 11']
        },
        modules: false,
    }
    plugins = ['react-hot-loader/babel']
}

const config = {
    presets: [
        ['@babel/preset-env', presetEnvConfig],
        '@babel/preset-react',
    ],
    plugins: [
        ...plugins,
        "@babel/plugin-syntax-dynamic-import", '@babel/plugin-proposal-class-properties',
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-nullish-coalescing-operator",
        "@babel/plugin-proposal-optional-chaining",
        "@babel/plugin-proposal-numeric-separator",
        "@babel/plugin-transform-runtime",
    ],
}

module.exports = config
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Should I use `babel-plugin-dynamic-import-node-babel-7` or `babel-plugin-dynamic-import-node` for now?

**Comment by palaniichukdmytro** [comment]
`babel-plugin-dynamic-import-node-babel-7` works for me correct

**Comment by nicolo-ribaudo** [comment]
Yeah, you need to use that third-party plugin since Babel doesn't transpile `import()` (yet?)
