### ISSUE TITLE
regenerator for `for of` inside async function doesn't produce valid code

### ISSUE THREAD

**Issue by sormy** [babel/babel#8810]
## Bug Report

**Current Behavior**

```
(node:21354) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: num is not defined
```

**Input Code**

```js
async function test(data) {
    for (num of data) {
        console.log(num);
    }
}

test([1, 2, 3]);
```

```
npx babel test.js --out-file test-node6.js --presets=@babel/env --plugins=@babel/transform-runtime
node test-node6.js 
```

**Expected behavior/code**

Should output without errors:

```
1
2
3
```

**Babel Configuration (.babelrc, package.json, cli command)**

package.json:

```
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/runtime": "^7.1.2",
```

**Environment**
- Babel version(s): v7.1.2
- Node/npm version: v6.14.4
- OS: Linux x86_64
- Monorepo: no?
- How you are using Babel: cli

**Possible Solution**

Manually edit JS code:

```js
async function test(data) {
    var num;
    for (num of data) {
        console.log(num);
    }
}

test([1, 2, 3]);
```

**Additional context/Screenshots**

N/A

**Comment by nicolo-ribaudo** [comment]
ES modules are `"use strict"` by default, so undeclared variables (`num`, in your case) must throw. You can add `"sourceType": "script"` to your Babel config and pass the `"modules": false` option to the env preset, to indicate that you don't want your files to be considered as modules.

**Comment by sormy** [comment]
Thanks, it is enough to just add `--source-type script` to babel cli.

By the way, original file could be processed by NodeJS v10.x without any additional settings but after transpilation it can't be processed neither by NodeJS v6.x neither by NodeJS v10.x. I would say that it is most likely not desired default behavior for anybody (including me).

**Comment by nicolo-ribaudo** [comment]
We thought about defaulting to `script` in Babel 7, but it would have broken the default behavior for anyone using es modules (which are more people than the one using non-strict code with Babel).
