### ISSUE TITLE
Unsafe usage of ThrowStatement in iterableToArrayLimit

### ISSUE THREAD

**Issue by niftylettuce** [babel/babel#8816]
## Bug Report

**Current Behavior**

A babel config with a target (e.g. Node v6.4) that requires the `iterableToArrayLimit` (`slicedToArray`) polyfill will throw an error in ESLint about unsafe usage of `throw` in a try/catch "finally" block.

```sh
error  Unsafe usage of ThrowStatement  no-unsafe-finally
```

The standard `.eslintrc` config is (using `eslint` and `eslint-plugin-node`):

```json
{
  "extends": ["eslint:recommended", "plugin:node/recommended"]
}
```

**Input Code**

https://github.com/babel/babel/blob/5150f5f5003b25d89f8b5041543412839cfde5fd/packages/babel-helpers/src/helpers.js#L898

**Expected behavior/code**

Probably shouldn't have a throw in the finally block here?

**Babel Configuration (.babelrc)**

> `package.json`:

```json
"@babel/cli": "^7.1.1",
"@babel/core": "^7.1.1",
"@babel/preset-env": "^7.1.0",
```

> `.babelrc`:

```json
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "6.4.0"
      }
    }]
  ],
  "sourceMaps": "inline"
}
```

**Environment**
- Babel version(s): v7.1.1
- Node/npm version: Node v8.12.0
- OS: OS X
- Monorepo [e.g. yes/no/Lerna] no
- How you are using Babel: [e.g. `cli`, `register`, `loader`] cli

**Possible Solution**

I'm guessing we shouldn't throw in the finally block?

**Comment by nicolo-ribaudo** [comment]
It's correct: if the iterator throws, we must re-throw the error.
Generally, linting code generated by Babel isn't a good idea: in order to be spec compliant we need to do "bad things" 😝

**Comment by niftylettuce** [comment]
Is there an `eslint-plugin-babel` somewhere that has a list of all these common/bad things done?

**Comment by nicolo-ribaudo** [comment]
No; there is an `eslint-plugin-babel` but it is to allow linting new syntax.

You should lint the input source code, not the compiled output.

**Comment by niftylettuce** [comment]
I feel like it'd be best practice to lint the compiled output, and make use of <https://github.com/mysticatea/eslint-plugin-node#readme>, unless Babel uses this internally somehow?

**Comment by niftylettuce** [comment]
*Lint the compiled output (in addition to the input)

The last thing I want to do is output a Babel build that has errors and publish it to NPM

**Comment by niftylettuce** [comment]
Similarly I get an error with `no-func-assign`.

I feel like these should be re-opened.

Why can't the code inside the `finally` block go after the try instead?

```diff
+if (!_n && _i["return"] != null) _i["return"]();
+if (_d) throw _e;
-try {
-  if (!_n && _i["return"] != null) _i["return"]();
-} finally {
-  if (_d) throw _e;
-}
```

Why isn't there a `} catch (err) {` here as well?

We should remove `} finally {` usage, no?  It shouldn't be needed since we have `catch (err)`.

Please re-open

**Comment by niftylettuce** [comment]
My issue with `no-func-assign` is when using Lodash's template function.

Input:

```js
const tmpl = require('lodash/template');
const { oneLineTrim } = require('common-tags');
```

and

```js
        message: oneLineTrim`
          {{ req.ip }}\u00A0
          [{{ req.id ? req.id : new Date().toUTCString() }}]\u00A0
          "
          {{ req.method }}\u00A0
          {{ req.url }}\u00A0
          HTTP/{{ req.httpVersionMajor }}.{{ req.httpVersionMinor }}
          "\u00A0
          {{ res.statusCode }}\u00A0
          {{ res.get('X-Response-Time') }}
        `,
```

Output:

```js
function _templateObject() {
  var data = _taggedTemplateLiteral(["\n          {{ req.ip }}\xA0\n          [{{ req.id ? req.id : new Date().toUTCString() }}]\xA0\n          \"\n          {{ req.method }}\xA0\n          {{ req.url }}\xA0\n          HTTP/{{ req.httpVersionMajor }}.{{ req.httpVersionMinor }}\n          \"\xA0\n          {{ res.statusCode }}\xA0\n          {{ res.get('X-Response-Time') }}\n        "], ["\n          {{ req.ip }}\\u00A0\n          [{{ req.id ? req.id : new Date().toUTCString() }}]\\u00A0\n          \"\n          {{ req.method }}\\u00A0\n          {{ req.url }}\\u00A0\n          HTTP/{{ req.httpVersionMajor }}.{{ req.httpVersionMinor }}\n          \"\\u00A0\n          {{ res.statusCode }}\\u00A0\n          {{ res.get('X-Response-Time') }}\n        "]);

  _templateObject = function _templateObject() {
    return data;
  };

  return data;
}
```

and

```js
message: oneLineTrim(_templateObject()),
```

**Comment by niftylettuce** [comment]
Lastly you commented here:

> You should lint the input source code, not the compiled output.

I feel this is BAD practice, as we should not just assume that the compiler/babel is always going to work as we intended.  There are bugs that come up, people publish bad versions, edge cases, etc.  There should always be an extra eye.
