### ISSUE TITLE
Issue with generator arrows

### ISSUE THREAD

**Issue by vzaccaria** [babel/babel#882]
This works:

```es6
var routine = function*(){ 
    		...
    		var project = yield fillWithData(template, { productName: 'prod'});
    		...
}
```

This doesn't:

```es6
var routine = *() => { 
    		...
    		var project = yield fillWithData(template, { productName: 'prod'});
    		...
}
```

with this compile error: 

```bash
SyntaxError: index.js: Unexpected token (12:15)
  10 | var main = () => {
  11 | 
> 12 | 	var routine = *() => { 
     |                ^
  13 |     		var template = readTemplate();
  14 |     		var project = yield fillWithData(template, { productName: 'pippo'});
  15 |     		writeProject(project, 'pippo')
```

**Comment by sebmck** [comment]
There's no such thing as generator arrow functions.

On Tuesday, 24 February 2015, Vittorio Zaccaria <notifications@github.com>
wrote:

> This works:
>
> var routine = function*(){
>             ...
>             var project = yield fillWithData(template, { productName: 'prod'});
>             ...
> }
>
> This doesn't:
>
> var routine = *() => {
>             ...
>             var project = yield fillWithData(template, { productName: 'prod'});
>             ...
> }
>
> with this compile error:
>
> SyntaxError: index.js: Unexpected token (12:15)
>   10 | var main = () => {
>   11 | > 12 |  var routine = *() => {
>      |                ^
>   13 |          var template = readTemplate();
>   14 |          var project = yield fillWithData(template, { productName: 'pippo'});
>   15 |          writeProject(project, 'pippo')
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/882>.
>


-- 
Sebastian McKenzie
