### ISSUE TITLE
@babel/preset-env support weex

### ISSUE THREAD

**Issue by myeveryheart** [babel/babel#8822]
Hi, babel7 is awesome. When I use it in weex, I don't know how to config the @babel/preset-env.
In babel6, I use 
```
{
  "presets": [
    "es2015",
    "stage-0"
  ]
}
```
is fine.
But in babel7? I have no idea.

**Comment by nicolo-ribaudo** [comment]
```json
{
  "presets": ["@babel/preset-env"],
  "plugins": [
    // Any plugin from [1] that you are actually using
  ]
}
```

And you need to `npm install --save-dev @babel/core @babel/preset-env @babel/plugin-proposal-that-you-are-using`

[1] https://github.com/babel/babel/blob/master/packages/babel-preset-stage-0/README.md
