### ISSUE TITLE
Babel does not output ES5.

### ISSUE THREAD

**Issue by nikolovjd** [babel/babel#8824]
## Bug Report

**Current Behavior**
Babel is outputting const. This breaks in older browsers because const is not allowed in strict mode.

**Input Code**
- REPL or Repo link if applicable:

```js
const zipCodes = [...]
```

**Expected behavior/code**
To output var. The output stays as const zipCodes... (etc)

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["@babel/plugin-proposal-class-properties"],
  "presets": [["@babel/preset-env", {"targets": "> 0.25%, not dead", "forceAllTransforms": true}], "@babel/preset-react"]
}
```

**Environment**
- Babel version(s): "@babel/core": "^7.1.2",
- Node/npm version: v10.9.0
- OS: irrelevant
- How you are using Babel: babel-loader for webpack

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
What is your directory structure? Probably Babel isn't picking up your config.

PS. Instead of using targets+forceAllTransforms, you can just use preset-env without options.

**Comment by xtuc** [comment]
Not enough informations were provided, closing for now.
