### ISSUE TITLE
"regeneratorRuntime is not defined" error with async and "useBuiltIns": "usage"

### ISSUE THREAD

**Issue by mrichmond** [babel/babel#8829]
## Bug Report

**Current Behavior**
I get a "regeneratorRuntime is not defined" error when using `@babel/preset-env` and `"useBuiltIns": "usage"` with a nested async arrow function in my React HOC.

**Input Code**
React Component JS - DeleteAsset.js
```js
import React from 'react';
import { compose, withHandlers, setDisplayName } from 'recompose';
import { Button } from '@material-ui/core';

export default compose(
  setDisplayName('DeleteAsset'),
  withHandlers({
    onConfirm: ({ deleteImage, deleteVideo, id, type }) => async () => {
      if (type === 'image') await deleteImage(id);
      else if (type === 'video') await deleteVideo(id);
      console.log('ASSET DELETED');
    },
  }),
)(({ onConfirm }) => (<Button {...{ onClick: onConfirm }}>Delete</Button>));
```

**Expected behavior/code**
No regeneratorRuntime errors

**Babel Configuration (.babelrc, package.json, cli command)**
package.json
```json
{
  "devDependencies": {
    "@babel/cli": "7.1.2",
    "@babel/core": "7.1.2",
    "@babel/polyfill": "7.0.0",
    "@babel/preset-env": "7.1.0",
    "@babel/preset-react": "7.0.0",
    "webpack": "4.20.2",
    "webpack-cli": "3.1.2",
    "webpack-dev-server": "3.1.9"
  }
}
```

.babelrc
```json
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { "browsers": ["last 2 chrome versions"] },
      "useBuiltIns": "usage"
    }],
    "@babel/preset-react"
  ]
}
```

**Environment**
- @babel/cli version: **7.1.2**
- @babel/core version: **7.1.2**
- @babel/polyfill version: **7.0.0**
- @babel/preset-env version: **7.1.0**
- Node version: **10.11.0**
- NPM version: **6.4.1**
- Yarn version: **1.10.1**
- webpack version: **4.20.2**
- webpack-cli version: **3.1.2**
- webpack-dev-server version: **3.1.9**
- How you are using Babel: **loader (webpack)**

**Possible Solution**
 If I switch to "entry" mode and add the polyfill to my webpack entry, then the regeneratorRuntime error is no longer present.
> example .babelrc config: `"useBuiltIns": "entry"`
> example webpack.config.js config: `entry: ['@babel/polyfill', './src/index.js'],`, 

It seems that "entry" is a less optimal solution than "usage" for the "useBuiltIns" parameter. I believe this indicates a possible bug with the "usage" feature of "useBuiltIns" with Babel 7 @babel/preset-env.

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/240698/46635216-6afde080-cb08-11e8-826a-e82466255541.png)

**Comment by cjgarde** [comment]
Hi,
 Same problem here as @mrichmond. His "hack" is really useful for me, now I can use **async** functions at any component in my project.

 Just fyi my **package.json** is:
`
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.0.0",
    "webpack": "^4.16.5",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5",
`

and my **.babelrc** is :
`
{
  "presets": ["@babel/preset-env",  "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-export-default-from",
    "react-hot-loader/babel"
  ]
}
`

After suggested in the first post, now is working. My **.babelrc** now is:
`
{
  "presets": [[
    "@babel/preset-env", {
      "useBuiltIns": "entry"
    }],
    "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-export-default-from",
    "react-hot-loader/babel"
  ]
}
`

And the **entry** key of my **webpack** configuration file is:
`module.exports = {
  entry: ['@babel/polyfill', './src/index.js'],
...

`

Also I've checked with plugins:
babel-plugin-syntax-async-functions
@babel/plugin-transform-async-to-generator
@babel/plugin-transform-runtime

And with all of them i had the same error of "regeneratorRuntime is not defined"
Cheers!

**Comment by slater101** [comment]
Same problem here. 

usage should work... Problem with entry is that my file is no 2X larger than before...

**Comment by iedmrc** [comment]
> Hi,
> Same problem here as @mrichmond. His "hack" is really useful for me, now I can use **async** functions at any component in my project.
> 
> Just fyi my **package.json** is:
> 
> ```
>   "devDependencies": {
>     "@babel/cli": "^7.0.0",
>     "@babel/core": "^7.0.0",
>     "@babel/plugin-proposal-class-properties": "^7.0.0",
>     "@babel/plugin-proposal-export-default-from": "^7.0.0",
>     "@babel/polyfill": "^7.0.0",
>     "@babel/preset-env": "^7.0.0",
>     "@babel/preset-react": "^7.0.0",
>     "babel-core": "7.0.0-bridge.0",
>     "babel-eslint": "^9.0.0",
>     "babel-jest": "^23.4.2",
>     "babel-loader": "^8.0.0",
>     "webpack": "^4.16.5",
>     "webpack-cli": "^3.1.0",
>     "webpack-dev-server": "^3.1.5",
> ```
> and my **.babelrc** is :
> 
> ```
> {
>   "presets": ["@babel/preset-env",  "@babel/preset-react"],
>   "plugins": [
>     "@babel/plugin-proposal-class-properties",
>     "@babel/plugin-proposal-export-default-from",
>     "react-hot-loader/babel"
>   ]
> }
> ```
> After suggested in the first post, now is working. My **.babelrc** now is:
> 
> ```
> {
>   "presets": [[
>     "@babel/preset-env", {
>       "useBuiltIns": "entry"
>     }],
>     "@babel/preset-react"],
>   "plugins": [
>     "@babel/plugin-proposal-class-properties",
>     "@babel/plugin-proposal-export-default-from",
>     "react-hot-loader/babel"
>   ]
> }
> ```
> And the **entry** key of my **webpack** configuration file is:
> `module.exports = { entry: ['@babel/polyfill', './src/index.js'], ...`
> 
> Also I've checked with plugins:
> 
> > babel-plugin-syntax-async-functions
> 
> > @babel/plugin-transform-async-to-generator
> 
> > @babel/plugin-transform-runtime
> 
> And with all of them i had the same error of "regeneratorRuntime is not defined"
> Cheers!

This works like a charm! Thanks! 🎉🎉🎉

**Comment by laustdeleuran** [comment]
+1

I'm experiencing this same issue. @mrichmond's workaround does resolve the issue, and I'm not  experiencing the ~2x bloat in file size that "@ghost" was referring to. It does still seem like a bug, tho?

**Comment by Cody0913** [comment]
The solution from [this issue thread](https://github.com/parcel-bundler/parcel/issues/871) worked for me. Importing the following:
```
yarn add @babel/plugin-transform-runtime --dev
yarn add @babel/runtime
```
for my dependencies and having the following in my .babelrc
```
"plugins": [
    ["@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ],
```

**Comment by tstirrat15** [comment]
@Cody0913 meaning in addition to `useBuiltIns: 'usage'`? Or is that instead of?

Under what circumstances will `useBuiltIns: 'usage'` work? I'm seeing the same error as OP, and reverting to `entry` seems like a workaround more so than a fix.

**Comment by ford04** [comment]
@Cody0913 your solution works for me too.

Isn't using `@babel/polyfill` in combination with `@babel/plugin-transform-runtime` and `@babel/runtime` not kinda redundant? All the docs I have read say, you should only install either of them (dependent on if you develop a library or an application). Would be interested in a more clear solution, but honestly lack the babel internal knowledge here...

**Comment by nicolo-ribaudo** [comment]
Do you want to globally install polyfills? `@babel/polyfill` or `core-js`
Do you want to only make polyfills available to your own code? `@babel/transform-runtime` + `@babel/runtime`

**Comment by ford04** [comment]
thx @nicolo-ribaudo, I thought both were mutually exclusive.

Just curious: why cannot `@babel/polyfill` alone provide the regenerator-runtime as it is already included in the package? If I include this polyfill, I would expect it to contain everything necessary. Do you have some code lines/ modules where one can dig into the issue?

```
+-- @babel/polyfill@7.4.3
| `-- regenerator-runtime@0.13.2
```

**Comment by josemigallas** [comment]
> The solution from [this issue thread](https://github.com/parcel-bundler/parcel/issues/871) worked for me. Importing the following:
> 
> ```
> yarn add @babel/plugin-transform-runtime --dev
> yarn add @babel/runtime
> ```
> 
> for my dependencies and having the following in my .babelrc
> 
> ```
> "plugins": [
>     ["@babel/plugin-transform-runtime",
>       {
>         "regenerator": true
>       }
>     ]
>   ],
> ```

As a comment on this solution, `regenerator` value [is true by default](https://babeljs.io/docs/en/babel-plugin-transform-runtime#via-babelrc-recommended), no need to add that. It worked like a charm by the way, thanks! (Short version I guess is: use **[babel-plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime)**.)

**Comment by nicolo-ribaudo** [comment]
Is this still an issue?
