### ISSUE TITLE
No support for plugin options in babel standalone

### ISSUE THREAD

**Issue by mateuszluczak** [babel/babel#8831]
## Bug Report

**Current Behavior**
There is no way to pass configurations for plugins in babel standalone which causes REPL to not work with for example decorators.

**Babel Configuration (.babelrc, package.json, cli command)**
[Example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAKgU2jAvDAFMKIBOBKVAPhgG8AoGGHBKAVxzBmABsBDCCGBADygTAAmnLLlIVKTcNBy0ROdADolrHAHMIBchJgBICLQAOCeUoUr1eANzjKAXxswHACwTNmIdJps6drZsah0AHIXNxAgqwd7O0oyezIAAURoMhZ2TgBRblYAWwN_MUpQSCgZOU9Cyh0oJwBLCAVQ909LRzs42LIwBAB3GCzc_IQWsiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.0.0-rc.4&envVersion=)

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] 7.0.0-rc4
- How you are using Babel: [e.g. `cli`, `register`, `loader`] standalone

**Comment by mateuszluczak** [comment]
Is there anyway to do it in using standalone through scripts? I am injecting it to the page and `data-plugins` don't want to cooperate.

**Comment by nicolo-ribaudo** [comment]
Currently it is only supported if you are calling Babel standalone programmatically

**Comment by mateuszluczak** [comment]
Ok, thanks for clarification. I was thinking about creating custom preset and somehow injecting it, but not sure if this work.

Could you provide some context why `decoratorsBeforeExport` have no default value in the plugin? But receiving this error is something that is not expected from documentation and if you want to have almost zero configuration to run babel that would be something I would expect.

**Comment by nicolo-ribaudo** [comment]
TC39 has not decided where decorators should go yet, so we don't want to default to a value which might soon become uncompliant.

Zero-config only if you are not using experimental features 😝

**Comment by dojyorin** [comment]
I had the same problem and tried "first aid".
It is a brute force method, but it worked well.

```html
<!-- For InternetExplorer -->
<script src="https://cdn.jsdelivr.net/npm/@babel/polyfill@latest/dist/polyfill.min.js"></script>

<script>
    // Immediate function to limited the scope of variable.
    // If you support IE, you must write in ES5.
    (function(){
        const xhr = new XMLHttpRequest();

        // No way, but use "sync"
        // Can't be used "minified"
        xhr.open("GET", "https://cdn.jsdelivr.net/npm/@babel/standalone@latest/babel.js", false);
        xhr.send();

        if(xhr.status === 200){
            const script = document.createElement("script");

            // var decoratorsBeforeExport = false or true.
            script.innerHTML = xhr.responseText.replace(/var decoratorsBeforeExport = .+?;/g, "var decoratorsBeforeExport = true;");
            document.getElementsByTagName("head")[0].appendChild(script);
        }
    })();
</script>

<head></head>

<script type="text/babel" data-presets="es2015,stage-2">
    // ES6~ source
</script>
```

**Comment by nicolo-ribaudo** [comment]
You can create a custom preset and use it:
https://jsfiddle.net/0n8w6zh9/

**Comment by thiagoarrais** [comment]
Considering this fixed since the REPL now exposes some plugin config options like decorator mode and pipeline proposal. This is currently done on a per-plugin basis, but it is PR-able.
