### ISSUE TITLE
Option to specify env for browserslist

### ISSUE THREAD

**Issue by JoyceBabu** [babel/babel#8834]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I am using `babel-preset-env` to transpile my JS source into two bundles. One for ES5 browsers and another for modern browsers. I would like to use browserslistrc for this purpose with two [environments](https://github.com/browserslist/browserslist#environments) defined for `es5` and `es6`. Selecting the correct environment requires setting the `BROWSERSLIST_ENV` environment variable or passing the `env` option. I cannot use the `BROWSERSLIST_ENV` as both versions are transpiled by the same gulp job.

I would like to use the [env](https://github.com/browserslist/browserslist#js-api) option of browserslist, which is currently not supported by babel.

**Describe the solution you'd like**
I would like to introduce a new option to `babel-preset-env` , which will be passed as the `env` option to browserslist.

**Describe alternatives you've considered**
Alternative is to use `BROWSERSLIST_ENV` or `NODE_ENV`. But for a gulp watch job which handles multiple environments, this is not really an option.

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by serwer-WittGruppe** [comment]
We have to pass the `env` [from here](https://github.com/babel/babel/blob/0514a9f90370b2c14bcd722f96fd97644024f9fd/packages/babel-preset-env/src/index.js#L204)
