### ISSUE TITLE
Error after upgrading to babel 7

### ISSUE THREAD

**Issue by timotew** [babel/babel#8835]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
After upgarding from bable 6 to 7, My dev script stop working and doesn't recorgnize ES6.
I'm using babel-node here is my `www` file content:
**Input Code**
- REPL or Repo link if applicable:

```js
const  { config } = require('dotenv');
config();
import 'babel-polyfill';
var app = require('../app');
var debug = require('debug')('tlikes:server');
var http = require('http');
var socket= require('../socket');

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
Compile and let `nodemon` start dev server
**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": ["@babel/preset-env", "@babel/react", "minify"],
    "env": {
        "production": {
          "presets": ["minify"]
        }
      },
    "plugins": ["@babel/plugin-transform-runtime"],
    "exclude": "/node_modules/",
    "ignore": [
            "src/public"
                ]
  }
```

**Environment**
- Babel version(s): ^7.0.0
- Node/npm version: v10.9.0 / npm 6.2.0
- OS:  OSX 10.13.6
- Monorepo [no
- How you are using Babel: `cli`

**Possible Solution**

Reverting to babel 6
**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
This is my script file:
```bash
  "scripts": {
    "start": "nodemon -- src/bin/www --inspect --exec babel-node",
    "build": "BABEL_ENV=production babel src --plugins transform-remove-console --out-dir dist --copy-files &&  babel src/bin/www  --out-file dist/bin/www",
    "serve": "node dist/bin/www",
    "clean": "rm -rf dist",
    "lint": "eslint ./",
    "test": "make test"
  }
```

Here is my console log
```bash
import 'babel-polyfill';
       ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by skwon-mdsol** [comment]
you can't just do `require('babel-polyfill')` ?

**Comment by cattermo** [comment]
Babel-polyfill is removed since babel 7, use core-js instead.

**Comment by timotew** [comment]
@skwon-mdsol  That the purpose of using babel in the first place.

@cattermo  I have removed the `babel-polyfill`, The error occurs  anytime I use ES6 import.
```console
import app from '../app';
       ^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

**Comment by skwon-mdsol** [comment]
@cattermo https://babeljs.io/docs/en/babel-polyfill polyfill still exists, it's just named differently - using the submodule prefix

**Comment by bertho-zero** [comment]
I have the same problem in a monorepo since I did a `babel.config.js` at root and I have no `.babelrc.js` in my package.

**Comment by markpradhan** [comment]
Having same issue, had to revert back to v6.

**Comment by timotew** [comment]
Still no solution to this.

**Comment by Blackfaded** [comment]
Same problem here

```
import io from '../websocket';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by nicolo-ribaudo** [comment]
@Blackfaded Are you using Babel 6 or 7?

**Comment by joeguerra504** [comment]
I'm having the same issue. Had to revert to babel 6. Tried to upgrade boilerplate and use babel 7 but i had same error as above. Tried re-adding .babelrc then it barked about not being able to find stuff. Don't really have time to do too much troubleshooting, unfortunately, so I was forced to revert to babel 6 until a future date. if anyone has any additional information about this, I'd love to hear it.

Unfortunately, I don't quite understand how babel works within the environment and its interaction and setup in the boilerplate.

**Comment by MaximeHeckel** [comment]
Has there been any new updates for this issue? (Having the same issue, and still can't work around it)

**Comment by timotew** [comment]
@MaximeHeckel There was no solution, I had to revert back to babel 6 on the project.

**Comment by MaximeHeckel** [comment]
@timotew sorry to hear that, I'm stuck as well, I'm having the same exact issue that you have while running Nightwatch (for e2e tests)

**Comment by Luc-cpl** [comment]
Same issue here after update from Babel 6.

**Comment by Luc-cpl** [comment]
Fixed deleting .babelrc and creating babel.config.js with folow code

```
module.exports = {
  presets: ["@babel/env"], // "@babel/preset-env"
  plugins: []"
};
```

**Comment by nicolo-ribaudo** [comment]
This might be a configuration problem. Keep in mind that .babelrc files only apply to the package they are put in; not to subpackages (delimited by new `package.json` files) or to files external to the repository.

https://babeljs.io/docs/en/config-files

**Comment by VyvIT** [comment]
Because I'm running dev mode though babel-node as well, I had to explicitly define modules: 'auto' to determine whether to transform them to CJS (auto) or not, so I've defined my preset-env like this and now it works like a charm (comments borrowed from create-react-app btw):
```
'@babel/preset-env', {
          // Allow importing core-js in entrypoint and use browserlist to select polyfills
          useBuiltIns: 'entry',
          // Set the corejs version we are using to avoid warnings in console
          // This will need to change once we upgrade to corejs@3
          corejs: 3,
          // Transform modules based on env support
          modules: 'auto',
          // Exclude transforms that make all code slower
          exclude: ['transform-typeof-symbol'],
        }
```

**Comment by JokerQyou** [comment]
It seems like moving `bin/www` to `bin/www.js` solved this issue for me.
