### ISSUE TITLE
[TypeScript] Assert fail

### ISSUE THREAD

**Issue by jaejun-choi** [babel/babel#8837]
## Bug Report

**Current Behavior**
Code fails with Babel, but it works with TSC

**Input Code**
```js
type x = string
<div></div>
```
```
Error: Assert fail
    at assert (@babel/parser/lib/index.js:8543:11)
    at _class.parseMaybeAssign (@babel/parser/lib/index.js:10196:9)
...
```

**Babel Configuration (.babelrc, package.json, cli command)**
- typescript
- jsx

**Environment**
- Babel version(s): 7.1.2
- Node/npm version: Node 8.12 / npm 6.4.1
- OS: Linux Mint 18.3

**Comment by woongsikchoi** [comment]
This issue also occurs when merge conflict message like "<<<<<<< HEAD" occurs after TypeScript interface declaration.

```
interface Foo { }
<<<<<<< HEAD
```

**Comment by JakeGinnivan** [comment]
Found another example of this error:

```
let assignMe

tern ? (assignMe = <div />) : (assignMe = <div>Doesn't work</div>)
```

An inline ternary which assigns JSX to a variable. It is only the `else` path which causes the Assert fail.

**Comment by armano2** [comment]
this issue seem to be fixed in jsx or when react preset is enabled

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/12599, thanks!
