### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by indapublic** [babel/babel#8838]
## Bug Report

**Environment**
```
"babel": "^6.23.0",
"babel-cli": "^6.26.0",
"babel-core": "^6.26.3"
```
```
OSX: 10.13.6 (17G3014)
```
```
node -v
v10.0.0
```
```
npm -v
5.6.0
```

**Babel Configuration (.babelrc)**

```js
{
  "presets": [ "react",  ["env", {
    "targets": {
     "browsers": [ ">0.25%", "not ie 11", "not op_mini all"]
    }
  }], "stage-0" ],
  "env": {
   "production": {
      "presets": ["minify"]
    }
  },
  "plugins": [
    [ "transform-object-rest-spread", { "useBuiltIns": true } ],
    "transform-es2015-destructuring",
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

Want to transform code

```js
import { transform } from '@babel/core'
...
const source = await readFile(fileName)
const posixName = posixPath(fileName)
const result = transform(source, {
  babelrc: true,
  filename: fileName
})
```

**Current Behavior**
```
Error: Plugin/Preset files are not allowed to export objects, only functions.
```

**Expected behavior/code**
Code is successfully transformed regarded to working project with that babel config.

**Comment by loganfsmyth** [comment]
The error means you are running a Babel 6 config file using Babel 7. You're using `@babel/core`, you're using Babel 7. 

If you want to use Babel 6, you should be using `babel-core`. If you want to use Babel 7, then you need to update your config file to use the Babel 7 versions of your plugins.

**Comment by loganfsmyth** [comment]
Also, FYI we have a `transformFile` function, so you don't need to read the file yourself, and converting with `posixPath` shouldn't be needed.

**Comment by indapublic** [comment]
@loganfsmyth Thanks for explanation. It's weird. I don't see `@` inside import.
But it's legacy code and it not contains any babel 7 dependencies.
Could you tell me how it's possible to load babel 7 without dependencies?

```
"babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-minify": "^0.4.3",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-intl": "^2.4.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
```

As I know, babel-loader 7 (only once dependency with 7 version) works with babel6

**Comment by indapublic** [comment]
Thanks for `transformFile` mention!

**Comment by loganfsmyth** [comment]
> Thanks for explanation. It's weird. I don't saw @ inside import :(.

I don't understand this statement. The code you posted uses `@babel/core`:
```
import { transform } from '@babel/core'
...
const source = await readFile(fileName)
```
so if you want Babel 6, it should be

```
import { transform } from 'babel-core'
...
const source = await readFile(fileName)
```

Does that help?

**Comment by indapublic** [comment]
1. `import { transform } from 'babel-core'` is not working: 
```
Error: Cannot find module 'babel/core'
```

2. As I mentioned, I have `babel-core` for 6 version:
```
"babel-core": "^6.26.3",
```
And I don't understand, why I'm not receiving any error on '@babel-core' importing.

**Comment by nicolo-ribaudo** [comment]
>Error: Cannot find module 'babel/core'

It's babel-core, not babel/core

**Comment by indapublic** [comment]
Oh, my fault :( Sorry.
Thanks @nicolo-ribaudo 
Thanks @loganfsmyth
