### ISSUE TITLE
Add [Symbol.iterator]() methods to HTMLCollection

### ISSUE THREAD

**Issue by tp** [babel/babel#884]
This is related to #545.

I had this code (working in Firefox without Babel):

```
for (let contentGroupEl of xmlDocument.getElementsByTagName('contentGroups')) {
...
}
```

Where xmlDocument is defined as follows:
```
var xmlDocument = (new DOMParser).parseFromString(content, "application/xhtml+xml");
```

The above loop iterates over a [HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection).

Babel (v4.4) generates the following JS, which throws an exception in Chrome: 
```
for (var _iterator = xmlDocument.getElementsByTagName("contentGroups")[Symbol.iterator](), _step; !(_step = _iterator.next()).done; ) {
                var contentGroupEl = _step.value;
}
```

**TypeError: undefined is not a function**: since `xmlDocument.getElementsByTagName("contentGroups")[Symbol.iterator]` equals `undefined`.

Is is possible to extend HTMLCollection with the iterator methods as well?

My current workaround looks like this:
```
for (let contentGroupEl of[].slice.call(xmlDocument.getElementsByTagName('contentGroups'))) {
...
```

Simply extending the HTMLCollection prototype does not seem to work. This code has no effect on the HTMLCollection instances.
```
if (!HTMLCollection.prototype[Symbol.iterator]) {
  HTMLCollection.prototype[Symbol.iterator] = [][Symbol.iterator]
}
```

**Comment by sebmck** [comment]
As mentioned in #545, the polyfill is a separate project. Please request this on the [core-js](https://github.com/zloirock/core-js) repo. Thanks!
