### ISSUE TITLE
[Babel 7] [Flow] Flow typed class properties are kept in the output & can affect class methods 

### ISSUE THREAD

**Issue by ahmedelgabri** [babel/babel#8841]
# v7 Regression

> First check out: https://new.babeljs.io/docs/en/next/v7-migration.html
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Describe the regression**
Flow typed class properties without values are included in the compiled output and if you have a class method with the same name it will override it with `undefined`.

```js
class Foo {
  // both of them will end up in the compiled code
  propertyTypeDeclaration: Object
  foo: Function // <-- yes this is not right in the first place, but shouldn't affect the semantics of the output for this.foo()

  constructor() {
    this.classProperty()
    this.foo() // this will throw
  }

  classMethod() {
    console.log('test')
  }

  foo() {
    console.log('will throw')
  }

  classProperty = () => {
    console.log('test')
  }
}
```

## 1st problem:

Is that the types are actually included in the output even if they don't have values. Instead of being stripped out completely. 

https://github.com/ahmedelgabri/babel-class-props-bug/blob/master/7/class.compiled.js#L17

## 2nd problem

That it actually can shadow class methods if mistakenly having a name conflict. 

This is because class property value is `null` in the AST so the `value` here is falsy which fallback to `scope.buildUndefinedNode()` which will `void 0` in the output code. 

https://github.com/babel/babel/blob/6b8261bbb7ebb8d2980cb30c3b3369678fd99835/packages/babel-plugin-proposal-class-properties/src/index.js#L197

https://github.com/babel/babel/blob/6b8261bbb7ebb8d2980cb30c3b3369678fd99835/packages/babel-plugin-proposal-class-properties/src/index.js#L209

https://github.com/ahmedelgabri/babel-class-props-bug/blob/master/7/class.compiled.js#L19

**Input Code**
Reproducible in this repo https://github.com/ahmedelgabri/babel-class-props-bug

**Expected behavior/code**
That all types are stripped in the compiled code & that if a type name clashes with a class method that it won't affect the class method. Here is the output in babel 6

https://github.com/ahmedelgabri/babel-class-props-bug/blob/master/6/class.compiled.js#L8-L17

**Environment**
- Babel version(s): `7.1.2`
- Node/npm version: tested with node 8/10 & yarn 1.10.1
- OS: macOS 10.14
- Monorepo: no
- How you are using Babel: `cli` & `loader`

**Comment by ahmedelgabri** [comment]
Actually, according to the proposal https://github.com/tc39/proposal-class-fields looks like it was a bug in v6 that was fixed v7.

**Comment by dperetti** [comment]
But then it means we can no longer simply and safely describe class properties with Flow !!

**Comment by ahmedelgabri** [comment]
@dperetti that's not true, the issue here was a confusion because of a wrong babel 6 _(if it's a bug or a proposal behavior, I didn't check yet. But I assume the later)_ so when we updated to 7 the plugin had the new behavior.

If you have the plugin installed & want to use class fields

This is a valid JS syntax 

```js
class Foo {
  bar 
}
```

Which translates to something like
```js
function Foo() {}
Foo.bar = undefined;
```

With flow it will become

```js
class Foo {
  bar: Object 
}
```

Babel flow plugin in version 6, used to remove `bar: Object` completely.

Babel 7 will rightfully leave `bar` in the code because it's a class field.

The major issue here & _it has nothing to do with Flow or Babel BTW_ is if you do something like this

```js
class Foo {
  bar: Function
  constructor() {
    this.bar(); // this will throw
  }
  bar() { // this won't be called
    console.log('Called from bar')
  }
} 
```

This will translate to something like this
```js
function Foo() {
  this.bar();
}
Foo.bar = undefined;
Foo.prototype.bar = function () {
  console.log('Called from bar')
}
```

Because you have a property on the class with the same name of a class method, so when you call `this.bar()` it will throw since it will call the property & the property has an `undefined` value & not the method. This has nothing to do with flow or babel this is simply a bug in the code. 

Flow by default doesn't require you to type methods but it needs types for properties. 

So what you actually want with Flow is this 

```js
class Foo {
  constructor() {
    this.bar(); 
  }
  bar() { 
    console.log('Called from bar')
  }
} 
```

or if you have a class field

```js
class Foo {
  baz: number
  constructor() {
    this.baz = 10;
    this.bar(); 
  }
  bar() { 
    console.log('Called from bar')
  }
} 
```
or 

```js
class Foo {
  baz: number = 10;
  constructor() {
    this.bar(); 
  }
  bar() { 
    console.log('Called from bar')
  }
} 
```

I hope this clarified things a bit.
