### ISSUE TITLE
rest args input could be simplified further, depending on the usage.

### ISSUE THREAD

**Issue by stefanpenner** [babel/babel#886]
```js
function apple(foo, ...bar) {
  var a = bar[0];
}
```

currently produces:

```js
"use strict";

function apple(foo) {
  for (var _len = arguments.length, bar = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
    bar[_key - 1] = arguments[_key];
  }

  var a = bar[0];
}
```

but with some SA could produce:

```js
function apple(foo) {
  var a = arguments[1];
}
```

**Comment by neVERberleRfellerER** [comment]
I have created something in
https://github.com/neVERberleRfellerER/babel/tree/fix-extends-anon-class

It transforms this

  function f(foo, ...bar) {
    console.log(bar[0]);
    console.log(bar[1]);
  }

  function g(foo, ...bar) {
    console.log(bar);
  }

  function h(foo, ...bar) {
    return bar[0];
  }

  function i(foo, ...bar) {
  }

  function j(foo, ...bar) {
    var x = function z(bar) {
      bar[1] = 5;
    };
  }

into this

  function f(foo) {
    console.log(arguments[1]);
    console.log(arguments[2]);
  }

  function g(foo) {
    for (var _len = arguments.length, bar = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
      bar[_key - 1] = arguments[_key];
    }

    console.log(bar);
  }

  function h(foo) {
    return arguments[1];
  }

  function i(foo) {}

  function j(foo) {
    var x = function z(bar) {
      bar[1] = 5;
    };
  }

These parts of babel are completely new for me, so I would be glad for any feedback (worst practices for example).

**Comment by sebmck** [comment]
@neVERberleRfellerER Woo, that looks really solid! Mind opening a PR so I can review/leave comments? Thanks!

**Comment by sebmck** [comment]
One thing you'll need to keep in mind is breaking the optimisation whenever you hit a function since `arguments` will reference the wrong function.

**Comment by neVERberleRfellerER** [comment]
@sebmck I'll send PR as soon, as I finish one small experiment. And then I have to rebase this for 4.4.6 which could end in disaster.

Would you prefer simple optimization (the one that does what I have show in https://github.com/babel/babel/issues/886#issuecomment-75836269) or more complicated one[1], that can transform things like

    function m(foo, ...bar) {
      var x = bar[1+1];
      var y = bar[x+5];
    }

    function o(foo, ...bar) {
      var x = bar[+1];
      var y = bar[+x];
    }

into

    function m(foo) {
      var x = bar[1 + 1 + 1];
      var y = bar[x + 5 + 1];
    }

    function o(foo) {
      var x = bar[+1 + 1];
      var y = bar[+x + 1];
    }

?

Thanks for the warning with nested function. I do not know how to handle it, but I am definitely going to find a way.

[1] It looks fragile, but it adds only UnaryExpression and BinaryExpression support, which do have have numeric results only.

**Comment by sebmck** [comment]
> Thanks for the warning with nested function. I do not know how to handle it, but I am definitely going to find a way.

Just do:

```javascript
if (t.isFunctionDeclaration(node) || t.isFunctionExpression(node)) {
  this.skip();
}
```

You don't want to alias `var _arguments = arguments;` and then reference `_arguments` because it'll cause the function to deopt so it's safest/fastest to just coerce it into an array first.

> It looks fragile, but it adds only UnaryExpression and BinaryExpression support, which do have have numeric results only.

You can safely assume that any value passed to `arguments[i]` is going to be a number since the only other properties you could be accessing would be `callee` which isn't available in strict mode. If you wanted to go one step further you could check if `file.transformers.useStrict.canRun()` is `true` and then only do the number assumption logic.

**Comment by stefanpenner** [comment]
> One thing you'll need to keep in mind is breaking the optimisation whenever you hit a function since arguments will reference the wrong function.

this should unroll i think

**Comment by sebmck** [comment]
@stefanpenner Yeah, there's no way to reference the parent `arguments` without a deopt.

**Comment by sebmck** [comment]
Closed via #889 and 751557aef19c34969be3d2ab788b9e63c175ea5b.

**Comment by stefanpenner** [comment]
awesome!

**Comment by sebmck** [comment]
@stefanpenner Let me know if there's anything else that you think can be optimised. There's bound to be more patterns that come up that can be optimised away.

**Comment by stefanpenner** [comment]
> @stefanpenner Let me know if there's anything else that you think can be optimised. There's bound to be more patterns that come up that can be optimized away.

yup absolutely
