### ISSUE TITLE
Decorators support inconsistent with Typescript

### ISSUE THREAD

**Issue by PeterKottas** [babel/babel#8864]
## Bug Report
I was trying to port build pipeline (webpack) from ts-loader to babel-loader.
I am using decorator (for redux action types) implementation bellow.

**Current Behavior**
My input code works just fine with typescript. However using babel, prototype in actionClass in my decorator is undefined. I also tried various modifications (omit prototype and set type directly on actionClass) but all failed. I was simply unable to set type on the base class with decorator.

```
// Babel console.log(actionClass);
Descriptor {kind: "class", elements: Array(0), Symbol(Symbol.toStringTag): "Descriptor"}
```

**Input Code**
```
abstract class Action {
    public type: string;
    constructor() {
        this.type = this.type;
    }
}

export interface ActionClass<T extends Action> {
    prototype: T;
}

export function typeName(name: string): <T extends Action>(actionClass: ActionClass<T>) => void {
    return actionClass => {
        actionClass.prototype.type = name;
    };
}

// Usage :
export interface TestActionPayload {
    sample: string;
}
@typeName('TEST_ACTION')
export class TestAction extends Action {
    constructor(public payload: TestActionPayload) {
        super(payload);
    }
}
```

**Expected behavior/code**
It is partly unclear to me if this is a bug, or problem on my end. However, one way or another, I am expecting to be able to set properties on base class with decorators. Currently I can't.

```
// Typescript console.log(actionClass);
ƒ TestAction(payload) {
    var _this = _super.call(this, payload) || this;
    _this.payload = payload;
    return _this;
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```
options: {
    cacheDirectory: true,
    babelrc: false,
    presets: [
        [
            "@babel/preset-env",
            { targets: { browsers: "last 2 versions" } } // or whatever your project requires
        ],
        "@babel/preset-typescript",
        "@babel/preset-react"
    ],
    plugins: [
        ["@babel/plugin-proposal-decorators", { decoratorsBeforeExport: true }],
        ["@babel/plugin-proposal-class-properties", { loose: true }],
        "@babel/plugin-syntax-dynamic-import",
        "react-hot-loader/babel"
    ]
}
```

**Environment**
- Babel version(s): [7.1.2]
- Node/npm version: [Node 9.5.0/npm 6.4.1]
- OS: [Windows 10]
- Monorepo [no]
- How you are using Babel: [`loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
TypeScript uses legacy decorators. You should replace `"decoratorsBeforeExport": true` with `"legacy": true`.

**Comment by PeterKottas** [comment]
@nicolo-ribaudo ok that sounds intersting.
Trying it right now but first problem, apparently 
'decoratorsBeforeExport' can't be used with legacy decorators
yet I use the decorator before export in like a million places.

**Comment by PeterKottas** [comment]
Ok ts-lint goes crazy if I try to stick decorator after export. I am afraid I won't be able to make this work after all. I think I'll keep this open though cause it seems to me like this should work. At least I should be able to combine those 2 options imho.

**Comment by PeterKottas** [comment]
Nah doesn't seem that way. I am afk now but if I tried 
```
@typeName('TEST_ACTION')
export class TestAction extends Action {
    constructor(public payload: TestActionPayload) {
        super(payload);
    }
}
```
With 
```
@babel/plugin-proposal-decorators, { legacy: true }
```
It didn't pick it up at all. (Didn't hit the breakpoint and therefore, obviously didn't set the type)

**Comment by PeterKottas** [comment]
I think this might work:
```
@typeName('TEST_ACTION')
class TestAction extends Action {
    constructor(public payload: TestActionPayload) {
        super(payload);
    }
}
export { TestAction  };
```
But again, million of places in code to change this in.

**Comment by nicolo-ribaudo** [comment]
> ```js
> @typeName('TEST_ACTION')
> export class TestAction extends Action {
>     constructor(public payload: TestActionPayload) {
>         super(payload);
>     }
> }
> ```

What is the output generated by Babel?

**Comment by trusktr** [comment]
I can't imagine why @PeterKottas had any issue with that. It works fine for me.

But in general, the legacy decorators in Babel behave different than legacy decorators in TypeScript. For example:

- In Babel legacy decorators, they may receive an `initializer` property instead of a `value` property, but in TypeScript there is never an `initializer` property, only a `value` property.
- In TypeScript, decorators _must_ return a descriptor for them to be chained with other decorators on the same class element.
- In TypeScript, the previous point still results in the class field (if decorator was used on a field) using [[Set]] semantics when `useDefineForClassFields` is set to `false` (otherwise decorators break).
- In Babel, if a legacy decorator returns a descriptor, this causes the class field to always use [[Define]] semantics, regardless of the value of the `loose` option for the `plugin-proposal-class-properties` option (which [seems like a bug](https://github.com/babel/babel/issues/12040)), which is opposite of TypeScript behavior.

And there are more differences. Overall, they are two very different decorator systems, although they both supposedly are based on the same spec.

If anyone knows of more difference in detail, please do list them here. That would be helpful!

**Comment by PeterKottas** [comment]
This issue is 2 years old buddy. That is usually a hint that things might work differently now ;-) You are right, things work now but there are definitely differences. 

Just for completeness, this is what I ended up doing. Maybe somebody finds it useful:

```
abstract class Action implements AnyAction {
  public type: string;
  // tslint:disable-next-line: variable-name
  public __proto__?: Action;
  constructor() {
    this.type = this.__proto__?.type || this.type;
  }
}

export interface ActionClass<T extends Action> {
  prototype: T;
}

export function typeName(
  name: string
): <T extends Action>(actionClass: ActionClass<T>) => void {
  return actionClass => {
    actionClass.prototype.type = name;
  };
}

export function isActionType<T extends Action>(
  action: Action,
  actionClass: ActionClass<T>
): action is T {
  return action.type === actionClass.prototype.type;
}
```

I assume there are other ways, this works, and I am fairly happy with it. This is how it's used:

```
@typeName('TEST')
export class TestAction extends Action {
  constructor(
    public data: SomeType
  ) {
    super();
  }
}

export const reducer: Reducer<State> = (state: State, action): State => {
  if (isActionType(action, TestAction)) {
    return { ...state, data: action.data };
  }
  return state;
}
```

**Comment by trusktr** [comment]
> This issue is 2 years old

There are _still_ quite a few differences, and worse yet, they aren't documented anywhere (even after 2 years). If I find more, I will document them here to start with, and then maybe I'll put them in an article later, buddy. ;)

**Comment by liuxingbaoyu** [comment]
Since both ts and babel now support the latest decorator proposal, I will close this issue.
