### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by reeversedev** [babel/babel#8869]
I've been getting this issue while using Parcel for building my application. It seems like this problem has occurred after upgrading to Babel 7.
 
**package.json**

```json
{
  "name": "abc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html"
  },
  "repository": {
    "type": "git",
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel": "^1.6.2",
    "react": "^16.5.2",
    "react-router-dom": "^4.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "babel-preset-react": "^7.0",
    "babel-preset-stage-1": "^7.0"
  }
}
```

**Comment by nicolo-ribaudo** [comment]
Insrafe of `babel-preset-react` and `babel-preset-stage-1` you need to use `@babel/preset-react` and the plugins from https://github.com/babel/babel/blob/master/packages/babel-preset-stage-1/README.md that you actually need.
Also, what is your Babel config?

**Comment by reeversedev** [comment]
Okay, I just solved it. What I was doing wrong was that I was adding .babelrc file in which i was adding ev and react, which makes no sense at all after upgrading to version 7 because there is no need for that. 
So, the problem was with .babelrc and as I've removed it, it is solved now.
