### ISSUE TITLE
Hole array spread inside of another array isn't work correctly

### ISSUE THREAD

**Issue by macabeus** [babel/babel#8874]
## Bug Report

**Current Behavior**
If we spread an array with hole (`[1,, 2]` of `new Array(3)`, for example), the code generated from Babel don't convert the holes to `undefined`.

**Input Code**
Using babel, this code
```js
[1, ...[2,, 3]]
```

generates this:

```js
[1].concat([2,, 3]) // returns [1, 4, (empty), 3]
```

**Expected behavior/code**
```js
[1, ...[2,, 3]] // should returns [1, 2, undefined, 3]
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  plugins: ["@babel/plugin-transform-spread"]
}
```

**Environment**
- Babel version(s): lasted version from git
- Node/npm version: Node v9, NPM 5.6.0
- OS: macOS High Sierra
- Monorepo: yep
- How you are using Babel: CLI

**Additional context/Screenshots**
I found this bug when I'm doing this PR for fix a similar bug: https://github.com/babel/babel/pull/8872
This PR isn't fix this another bug.

**Comment by davwheat** [comment]
Can reproduce. Here's a full example of it causing an issue in the real world:

### Typescript

```ts
function chunkArray<T>(a: T[], n: number): T[][] {
    return [...Array(Math.ceil(a.length / n))].map((_, i) => {
        return a.slice(n * i, n + n * i);
    });
}
```

### Equivalent JS

```js
function chunkArray(a, n) {
    return [...Array(Math.ceil(a.length / n))].map((_, i) => {
        return a.slice(n * i, n + n * i);
    });
}
```

### Babel transpiled code

```js
function chunkArray(a, n) {
    return [].concat(Array(Math.ceil(a.length / n))).map(function (_, i) {
      return a.slice(n * i, n + n * i);
    });
}
```

### Results

```
// TS/JS
chunkArray([1, 2, 3], 2)
// returns: [[1, 2], [3]]

// Babel-ified JS
chunkArray([1, 2, 3], 2)
// returns: [empty, empty]
```

This is caused by `[...Array(3)]`, which should be `[undefined, undefined, undefined]`, being `[empty, empty, empty]`, meaning `.map()` does not get called on the array items.
