### ISSUE TITLE
`export Something from './Something'` doesn't work

### ISSUE THREAD

**Issue by Igor10k** [babel/babel#8875]
## Bug Report

**Current Behavior**
After updating to v7 I started getting this error:

```
Module parse failed: Unexpected token (115:7)
You may need an appropriate loader to handle this file type.
| });
| 
> export TextField from './TextField';
```

**Input Code**

index.js:

```js
...
export TextField from './TextField'
...
```

Textfield.js:

```js
export default 'test'
```

**Expected behavior/code**
Expect it to work. And it actually works just fine if I replace `export TextField from './TextField'` with `export { default as TextField } from './TextField'`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-syntax-export-default-from",
    "@babel/plugin-proposal-function-bind",
    [ "@babel/plugin-proposal-optional-chaining", { "loose": false } ],
    [ "@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false } ],
    "@babel/plugin-proposal-do-expressions",
    [ "@babel/plugin-proposal-class-properties", { "loose": false } ],
    "react-hot-loader/babel"
  ]
}
```

**Environment**
- Babel version(s): 7.1.2
- Node/npm version: node 10.12.0 / npm 6.4.1
- OS: macOS 10.14
- Monorepo yes
- How you are using Babel: loader

**Comment by Igor10k** [comment]
Should've used `@babel/proposal-export-default-from` instead of `@babel/plugin-syntax-export-default-from`

**Comment by alex-cory** [comment]
@Igor10k could you post your babel setup from package.json or .babelrc so we could see what you did? I'm having this problem even with using `@babel/proposal-export-default-from`

**Comment by Igor10k** [comment]
@alex-cory sure

**.babelrc**

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-function-bind",
    [ "@babel/plugin-proposal-optional-chaining", { "loose": false } ],
    [ "@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false } ],
    "@babel/plugin-proposal-do-expressions",
    [ "@babel/plugin-proposal-class-properties", { "loose": false } ],
    "react-hot-loader/babel"
  ]
}
```
