### ISSUE TITLE
babel-preset-env can't be installed

### ISSUE THREAD

**Issue by hungHoangDang** [babel/babel#8876]
## Bug Report

**Current Behavior**
I run this code `npm install --save-dev babel-preset-env` but it throw me this
![capture](https://user-images.githubusercontent.com/33661599/46939471-93e61e80-d090-11e8-9854-812896f01c1a.PNG)

**Input Code**
I type `npm install --save-dev babel-preset-env` to my terminal

**Expected behavior/code**
I hoped it would have installed the package to my package.json file since I had been recommended to install babel-preset-env instead of babel-preset-es2015, babel-preset-es2016, babel-preset-es2017. Although when I installed babel-preset-es2015, the same message was displayed

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "name": "todo-list-react",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.4",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-es2018": "^1.0.0",
    "babel-preset-react": "^6.24.1",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.9"
  }
}
```

**Environment**
- Babel version(s): Babel 6
- Node/npm version: Node 6.4.1
- OS: Windows 7 64bits
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: `loader`

**Possible Solution**
I don't know how babel-preset-env is constructed but if it contains babel-preset-es2015, then you guys should really look at it because it has the same issue with babel-preset-env

**Additional context/Screenshots**
I don't have more screenshots. Thank you!

**Comment by loganfsmyth** [comment]
The package is definitely published. Issues like this usually mean you have a network issue, or you have a corrupt local cache.
