### ISSUE TITLE
TypeScript: enum member with the same name as an imported type prevents import stripping

### ISSUE THREAD

**Issue by dfreeman** [babel/babel#8881]
## Bug Report

**Current Behavior**
If the name of an `enum` member matches that of an imported type, the corresponding `import` statement remains through transpilation, even if it's never referenced.

**Input Code**

```ts
import Foo from 'some-module';

enum Enum {
  Foo
}

function myFunction(): Foo {}
```

([REPL link](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAMQhOAzKERwOQGdMCmAtCBACYCuANgdgNwBQDBAdhVgKJtYDeDciZAwC-TVBRYBjGMAgs4IAJ4IJ02SwAUASgBcglD1FA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=Node-6&version=7.0.0-beta.36&envVersion=7.0.0-beta.38))

**Expected behavior/code**
I expect _not_ to see `import Foo from 'some-module';` in the compiled output, since `Foo` is only ever used as a type.

Note that changing the name of the `enum` member, e.g. to `Foo2`, causes the `import` statement to be stripped.

**Environment**
- `@babel/core`: 7.1.2
- `@babel/plugin-transform-typescript`: 7.1.0

**Comment by chriskrycho** [comment]
@dfreeman I assume changing the name of the import *also* fixes the problem, i.e. with this?

```ts
import { Foo as Foo2 } from './foo';

enum Enum {
  Foo
}

function myFunction(): Foo2 {}
```

**Comment by joseds** [comment]
I see it as a sloppyness with the source code. The tslint rule "no-unused-variable" would have caught this and I see it rather as a job for a linter than a compiler.

I recommend to close this issue.

**Comment by nicolo-ribaudo** [comment]
This is a real bug. For example, in this example the no-unused-variable rule wouldn't warn:

```js
import Foo from 'some-module';

enum Enum {
  Foo
}

function myFunction(): Foo { }

export default Enum.Foo;
```

**Comment by echenley** [comment]
It doesn't need to be an Enum:



```js
import { Foo } from './test-babel-2';

const obj: { Foo: Foo } = { Foo: 'foo' };
export default obj;
```

**Comment by echenley** [comment]
This bug doesn't only apply to Enums. If you define an object with a property with the same name as the type import, the import will not be removed:

```ts
// foo.d.ts
export type Foo = string;
```

```ts
// bar.ts
import { Foo } from './foo';
const obj: { Foo: Foo }: = { Foo: 'foo' };
export default obj;
```

```js
// bar.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _foo = require("./foo");

const obj = {
  Foo: 'foo'
};
var _default = obj;
exports.default = _default;
```

When using webpack, this results in an extremely confusing error:

```
Error: Can't resolve './foo' in '/path/to/bar'
```
