### ISSUE TITLE
Support for the experimentalsyntax 'classProperties' isn't currently enabled when config is in package.json

### ISSUE THREAD

**Issue by janzenz** [babel/babel#8889]
## Bug Report

**Current Behavior**
I have this config on my `package.json` file:
```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "entry"
            }
        ],
        "@babel/preset-flow"
    ],
    "plugins": [["@babel/plugin-proposal-class-properties", { "loose": true }]]
}
```
it seems to throw an error on build:
> Support for the experimentalsyntax 'classProperties' isn't currently enabled

However, when I move the said config to `.babelrc` file, the build runs without problem.

**Environment**
- Babel version(s): 7.1.2
- Node/npm version: 8.12.0
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: `loader`

**Comment by janzenz** [comment]
Sorry, I realised I had an existing config on my `babel-loader` which conflicted with my config on `package.json` file. Closing.

**Comment by nicolo-ribaudo** [comment]
What is your full package.json? Is you package.json in the same folder of .babelrc?
