### ISSUE TITLE
Unexpected async function parameter rename

### ISSUE THREAD

**Issue by unckleg** [babel/babel#8890]
## Bug Report

**Current Behavior**
When I declare asnyc function inside class and when I  stringify function (toString) to inspect function parameters (JS Reflection hack) with a goal to inject wanted dependencies I can't because parameters get renamed.  

**Input Code**
```js
async all(res) {
    await res.json(['test']);
  }
```

**Expected behavior/code**
Unchanged output:

```js
{
async all(res) {
    await res.json(['test']);
  }
}
```

**Current behavior/code**
Renamed argument leads to undefined injected dependencies:

```js
{
async all(_x) {
    await res.json(['test']);
  }
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "stage-2"
  ],

  "plugins": ["add-module-exports"]
}

```

**Environment**
- Babel version(s): [e.g. v6.0.0]
- How you are using Babel: [`cli`]

Similar to: #4782

**Comment by unckleg** [comment]
Real problem here is with async functions. Stringifying async function leads to mutated function parameter names.
It is due to async-to-generator preset that uglify function parameter names because of don't know why ? ? ? @hzoo  :dagger: 
Bypassed the problem with targeting node environment, so async func's 'll be resolved with native Node.js trans.

I would still like to get some info about using babel's preset without mutating function param names.

**Comment by loganfsmyth** [comment]
Relying on `.toString` for JS reflection is a mistake. The only guarantees you get with `toString` is that it'll vaguely represent the code you put in, and so Babel also provides no other guarantees.
