### ISSUE TITLE
Parsing error when JSX argument contains object with `class` field

### ISSUE THREAD

**Issue by just-boris** [babel/babel#8891]
## Bug Report

**Input Code**

```js
<Select prop={{ class: 'test' }} />;
```

**Current Behavior**

With the latest version of `@babel/parser@7.1.3` it fails with the error

```
SyntaxError: /Users/serdiuk/coding/test/test.js: Unexpected token, expected "jsxTagEnd"
```

**Expected behavior/code**

With `@babel/parser@7.1.2` and bellow it works:

```
React.createElement(Select, {
  prop: {
    class: 'test'
  }
});
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": ["@babel/preset-react"]
}

```

**Environment**
- Babel version(s): `@babel/core@7.1.2`
- Node/npm version: `v8.9.4`
- OS: OSX 10.12.6
- Monorepo: n/a
- How you are using Babel: cli, but also happens in `babel-loader`

**Possible Solution**

As a current workaround I can write the following:

```js
const prop = { class: 'test' };
<Select prop={prop} />;
```

This works with any version. But this is still an issue, because it fails to parse the code, that is supposed to be valid Javascript.

**Comment by lucasreppewelander** [comment]
You get another error when using it with a "regular" jsx tag like this:
```javascript
<Button prop={{ class: 'test' }}>{'ButtonText'}</Button>
```

then you get only `Unexpected token` as fail message but it is still the same issue, the same workaround works as state here up

**Comment by danez** [comment]
Same thing happens with
```jsx
<Select prop={{ function: \'test\' }} />;
```
