### ISSUE TITLE
Babel 7 and Jest (you need both babel 6 and babel 7 to get them to work)

### ISSUE THREAD

**Issue by maciej-gurban** [babel/babel#8892]
## Bug Report

**Current Behavior**
Migrating from babel 6x to 7.x First tried manually, then using `npx babel-upgrade`. Getting the same error thrown for both cases. Error:
```
Support for the experimental syntax 'classProperties' isn't currently enabled (52:20):
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

I did what the error asks me to do but it makes zero difference

**Input Code**

```js
export class Foo extends React.Component {
  static propTypes = {
  }
}
```

relevant sections of package.json
```js
  "devDependencies": {
    "@babel/core": "7.1.2",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/preset-env": "7.0.0",
    "@babel/preset-react": "7.0.0",
    "@babel/runtime": "7.1.2",
  }
```

**Expected behavior/code**
It should compile as expected

**Babel Configuration (package.json section)**

```js
{
    "plugins": [
      "react-hot-loader/babel",
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-syntax-import-meta",
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-proposal-json-strings",
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ],
      "@babel/plugin-proposal-function-sent",
      "@babel/plugin-proposal-export-namespace-from",
      "@babel/plugin-proposal-numeric-separator",
      "@babel/plugin-proposal-throw-expressions"
    ],
    "presets": [
      [
        "@babel/preset-env",
        {
          "modules": false
        }
      ],
      "@babel/preset-react"
    ],
}
```

**Environment**
- Babel version(s): as listed in devDependencies above
- Node/npm version: Node 8.11.3/npm 5.6.0
- Using Yarn 1.5.1 with workspaces
- OS: OSX 10.14
- Monorepo: yes, devDependecies are defined in the root package.json only
- How you are using Babel: loader

Tried using `.babelrc.js` file as well, but it makes no difference and that one particular plugin is never applied/recognized as being defined in `plugins`

**Comment by nicolo-ribaudo** [comment]
With a monorepo you need to use `babel.config.js` instead of `.babelrc`

**Comment by maciej-gurban** [comment]
Thanks, this seems to work. What about browser targets though? With my current config I'm getting `Unknown option: .env["test"].targets.`

**Comment by existentialism** [comment]
Yea, `targets` is only valid an option for the env preset.

Another option for you, is with `babel.config.js`, you have a lot more flexibility (since it's JavaScript)... so rather than the `env` key you can do something like we do:

https://github.com/babel/babel/blob/master/babel.config.js

**Comment by maciej-gurban** [comment]
I see, thanks.

Looking at current `packages` and how babel 7 seems to be organized, should I only ever need the plugins published under `@babel`? 

I'm asking since as the next step in the migration I began checking our Jest tests which started failing since babel cannot handle dynamic imports. I didn't need any additional plugin other than `plugin-syntax-dynamic-import` to get that to work with babel 6.

At the moment, it seems that having `@babel/plugin-syntax-dynamic-import` and `@babel/plugin-transform-regenerator` is not enough, even while using `babel-jest` or trying custom jest transforms, and while running jest with no cache. Is there anything else I could possibly be missing? I think I've tried any combination possible by now.

It's been approx 3h since I started my attempts at fixing it so I'm getting pretty desperate here.

**Comment by milesj** [comment]
@maciej-gurban I'd suggest not using `env` in babel config, it's deprecated. Just use `process.env.NODE_ENV`.

**Comment by maciej-gurban** [comment]
You mean to detect the env using NODE_ENV i side babel.config.js and return a different config if it's `test`?

**Comment by maciej-gurban** [comment]
That doesn't seem to work out of the box as the docs would suggest. Just having a function as export of `babel.config.js` will throw the following:
```
Caching was left unconfigured. Babel's plugins, presets, and .babelrc.js files can be configured
for various types of caching, using the first param of their handler functions:
```

**Comment by nicolo-ribaudo** [comment]
@milesj Why? You should always use `api.env()`, which automatically does caching for you (https://babeljs.io/docs/en/config-files#apienv)

**Comment by milesj** [comment]
@nicolo-ribaudo Correct, that's a better solution. Just saying doing env checks manually instead of relying on `env` property is a better implementation.

**Comment by danez** [comment]
`babel-plugin-dynamic-import-node` works on both babel 6 and 7 as of version 2.2.0.

`@babel/xxx` are "official" plugins for babel 7+, which are all located in this repository. Third party plugins (aka. "unofficial") like `babel-plugin-dynamic-import-node` will not be in the namespace "@babel/" even if they work for babel 7.

**Comment by nicolo-ribaudo** [comment]
Jest 24 supports Babel 7 :tada:

**Comment by osv-hub** [comment]
@nicolo-ribaudo I am struggling with this. I have spent a significant amount of time and configurations to get jest working with babel 7 but I am still getting a  SyntaxError: Unexpected identifier when importing a file. Is there a special plugin I need to install

**Comment by hbarve1** [comment]
Hello everyone,

I'm trying to configure jest with babel v7 and using async/await but it is giving "ReferenceError: regeneratorRuntime is not defined", is there anything that I'm missing here?

**Comment by milesj** [comment]
@hbarve1 Sounds like you targets don't support async/await, so it's falling back to regenerator runtime.

**Comment by nicolo-ribaudo** [comment]
Or you can use `@babel/plugin-transform-runtime`
