### ISSUE TITLE
The default value of `development` in `@babel/preset-react` is unexpected.

### ISSUE THREAD

**Issue by vzaidman** [babel/babel#8902]
## Bug Report

**Current Behavior**
The default value of `development` in `@babel/preset-react` is unexpected.

**Input Code**
From the [documentation](https://babeljs.io/docs/en/babel-preset-react#development): 
```
development
boolean, defaults to false.
```

**Expected behavior/code**
I'd expect the `development` property to default to:

`process.env.BABEL_ENV === 'development' || process.env.NODE_ENV === 'development'`

And if anybody wants to turn it off / on manually let them do it. I think not many people use it right now because they expect it's on by default.

**Comment by nayelimdejesus** [comment]
I'd like to work on this issue.

**Comment by nicolo-ribaudo** [comment]
If you need any help feel free to ask!
