### ISSUE TITLE
npn error with github:kangax/compat-table#688097f1ce623cb113640cc9108fe04fc41

### ISSUE THREAD

**Issue by MatellioSumit** [babel/babel#8904]
We were using "babel-preset-es2015". But when we tried to use "babel-preset-env", we are getting error in npm install. The error is as follows:

npm ERR! Unexpected end of input at 1:49197
npm ERR! able":"github:kangax/compat-table#688097f1ce623cb113640cc9108fe04fc41

Is this error related to compat-table? Please suggest what we should do?

**Comment by existentialism** [comment]
@MatellioSumit I had no problems installing it? Do you have some kind of npm cache?

**Comment by zloirock** [comment]
It definitely not a `babel` issue. Seems the problem with npm proxy / npm cache or something ike that.
