### ISSUE TITLE
Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by Fillah** [babel/babel#8908]
I know that this issue has been around a couple of times, but i still can't seem to fix it.

When i'm running my solution, i get the following error:

> ERROR in ./src/app.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> TypeError: Cannot read property 'bindings' of null
>     at Scope.moveBindingTo (...node_modules\@babel\traverse\lib\scope\index.js:867:12)

Does "traverse" reference to that i'm using babel 6 insted of 7?

my packages:

```
"dependencies": {
    "@babel/core": "7.1.0",
    "@babel/preset-env": "7.1.0",
    "babel-loader": "^8.0.4",
    "babel-preset-env": "^1.7.0",
    "webpack": "^4.21.0",
    "webpack-dev-server": "^3.1.9"
}
```

I've set the babel core and preset-env to be the exact same version.

How do i fix this issue?

**webpack.config.js**

```
const path = require('path')

module.exports = {
    entry: {
        app: './src/app.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
    devServer: {
        inline: false,
        contentBase: "./dist",
    },
    module: {
        rules: [{
            test: /\.js?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                presets: ['env']
            }
        }]
    }
}
```

**Comment by loganfsmyth** [comment]
> I've set the babel core and preset-env to be the exact same version.

That isn't quite the case. `presets: ['env']` will load

> `"babel-preset-env": "^1.7.0",`

not

> `"@babel/preset-env": "7.1.0",`

You should delete `"babel-preset-env": "^1.7.0",` and do `presets: ['@babel/preset-env']`

**Comment by Fillah** [comment]
Thanks for the quick answer! 

If i do that and run the project, i get the following error:

Error: Cannot find module 'babel-preset-env' from 'C:\Users\Jonas\Documents\webpack'
- Did you mean "@babel/env"?

**Comment by loganfsmyth** [comment]
Do you maybe also have a `.babelrc` file referencing `'env'`?

**Comment by Fillah** [comment]
**.babelrc** 
`{ "presets": ["@babel/preset-env"] }`

**Comment by loganfsmyth** [comment]
For that error, there's definitely got to be something somewhere referencing `babel-preset-env` or `env` as the name of a preset where it should be `@babel/preset-env` or `@babel/env`.

**Comment by Fillah** [comment]
So how do i fix this? By running a different version of @babel/preset-env and @babel/core?

**Comment by loganfsmyth** [comment]
I'd `grep` around your codebase looking for other references to presets.

> Error: Cannot find module 'babel-preset-env' from 'C:\Users\Jonas\Documents\webpack'

Means something something in your config is still referencing `env` as the name of a preset, which will try to load `babel-preset-env`, which is a Babel 6 preset. All of your configs need to be referencing the Babel 7 version of the preset, `@babel/preset-env`.

**Comment by Fillah** [comment]
The only code i have is:

**Package.json:**
```
{
  "name": "babel-webpack-starter",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --mode development"
  },
  "author": "fillah",
  "license": "MIT",
  "dependencies": {
    "@babel/core": "7.1.0",
    "@babel/preset-env": "7.1.0",
    "babel-loader": "^8.0.4",
    "webpack": "^4.21.0",
    "webpack-dev-server": "^3.1.9"
  },
  "devDependencies": {
    "webpack-cli": "^3.1.2"
  }
}
```
**webpack.config.js**
```
const path = require('path')

module.exports = {
    entry: {
        app: './src/app.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
    devServer: {
        inline: false,
        contentBase: "./dist",
    },
    module: {
        rules: [{
            test: /\.js?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                presets: ['env']
            }
        }]
    }
}
```

**.babelrc**
`{ "presets": ["@babel/preset-env"] }`

**src/app.js**

`let test = () => console.log(123)`

**Comment by yacineyacineyacineyacineyacine** [comment]
**thank you** @loganfsmyth i had the same probleme and its resolved now. also thank you @Fillah for posting that _issue_
