### ISSUE TITLE
Pass entire to be compiled file list to plugins?

### ISSUE THREAD

**Issue by milesj** [babel/babel#8911]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I have a plugin that converts TS interfaces to React prop types, which works rather well, as seen here: https://github.com/milesj/babel-plugin-typescript-to-proptypes However, the library cannot resolve type references that lie outside the current file.

To solve this, I'm looking to integrate the TS type checker into the Babel plugin here: https://github.com/milesj/babel-plugin-typescript-to-proptypes/pull/2/files#diff-f41e9d04a45c83f3b6f6e630f10117feR95 Creating a TS program *per file* is very costly, but if I had all the files upfront, it would be 1 call instead of N calls.

**Describe the solution you'd like**

Besides passing `filename` to plugin AST methods, pass the entire list of "files to be compiled" to `pre`.

**Describe alternatives you've considered**

None at the moment.

**Teachability, Documentation, Adoption, Migration Strategy**

Very minor change that would only affect plugin developers.

**Comment by loganfsmyth** [comment]
The hard part of this is that it's only really when you use the Babel CLI that Babel knows the full list of files. If you use `babel-loader` or `@babel/register` or `gulp-babel` or `babelify` or any other integrations, there's no way to know the full list of files ahead of time.

**Comment by milesj** [comment]
@loganfsmyth Good point. Does Babel have any information on what is triggering the compile?

**Comment by loganfsmyth** [comment]
It potentially knows the name of the tool doing the compilation, but that's about it at the moment. Was there some specific information you were hoping for?

I think the primary issue is that most tools don't know what files something is importing until after Babel has processed the file, so even the tool calling Babel doesn't know all the files yet.

**Comment by milesj** [comment]
I suppose I can handle this with a glob option passed to the plugin.

```
['babel-plugin-typescript-to-proptypes', { src: './src/**/*.js' }],
```

A little more work but would solve this scenario I believe.

**Comment by milesj** [comment]
Awesome, sounds like this should work, thank you! I'll close this for now.
