### ISSUE TITLE
`Array.prototype.find` doesn't work in the runtime

### ISSUE THREAD

**Issue by daliwali** [babel/babel#892]
When I call `[].find()` using `babel-node` it works, but it doesn't work in the runtime because it doesn't proxy `find` to `core-js`. Suggestion: use `_core.Array.find`, but this may be difficult. This probably belongs to a bigger class of problems regarding ES6 built-in prototype extensions. Easy way is to just polyfill it. Any ideas?

**Comment by zloirock** [comment]
Better static analysis, where it's not possible for array and string ES6/7 methods names something like:
```javascript
foo.includes(bar);

// =>

_callMethod(foo, 'includes', [bar]);

function _callMethod(that, key, args){
  switch(that && that.constructor){
    case Array: return _core.Array[key].apply(null, [that].concat(args));
    case String: return _core.String[key].apply(null, [that].concat(args));
  } return that[key].apply(that, args);
}
```
but it can reduce performance where available native methods.

**Comment by sebmck** [comment]
@daliwali There's currently no way to use the runtime transformer **and** have instance methods. The method suggested by @zloirock would be very intensive and wouldn't be worth the overhead. 

Alternatively you can use:

```javascript
Array.find(arr, callback);
```

but it's important to note that this is a `core-js` specific extension.

**Comment by zloirock** [comment]
@sebmck I do not think there will be significant overhead if you replace only the explicit call methods from the list ES6/7 methods. It will not works for `foo['in' + 'cludes'](bar)`, but it's not a big problem. Problem only in slowdown for a modern environment with native methods & static analysis :)

**Comment by sebmck** [comment]
@zloirock I don't feel comfortable applying it to:

```javascript
var foo = {
  find: function () {}
};

foo.find();
```

The only way I'd feel comfortable with this is if some type inference is added (related #883) but it's a long way off.

**Comment by zloirock** [comment]
@sebmck ok, for more comfortable
```javascript
function _callMethod(that, key, args){
  var fn = that[key];
  switch(!fn && Object.prototype.toString.call(that)){
    case '[object Array]': return _core.Array[key].apply(null, [that].concat(args));
    case '[object String]': return _core.String[key].apply(null, [that].concat(args));
  } return fn.apply(that, args);
}
```
more correct check, minimal overhead with native :)

**Comment by daliwali** [comment]
So the solution right now is to just not use ES6 instance methods with the runtime? I like @zloirock's proposal.

**Comment by chicoxyzzy** [comment]
Just want to say I also like @zloirock's proposal. It looks like it should work proper

**Comment by lijunle** [comment]
@zloirock 's solution is amazing. Do any update on this issue?

**Comment by grrowl** [comment]
Wow, I don't mind this not being technically feasible but `Array.includes` is not listed on the [caveats page](https://babeljs.io/docs/advanced/caveats/) page so getting to the bottom of this issue is a bit of a rabbit hole to go down.

**Comment by sebmck** [comment]
Feel free to submit a PR. Repo is [here](https://github.com/babel/babel.github.io).
