### ISSUE TITLE
Thanks From an All Things Open Attendee!

### ISSUE THREAD

**Issue by rcdilorenzo** [babel/babel#8922]
At All Things Open 2018 yesterday (Raleigh), @hzoo talked about the life of a maintainer. As a user of Babel in pretty much every JavaScript project, I just wanted to say how much I appreciate the hard work of the major contributors to this project.

Additionally, I really appreciate hearing the Biblical conduct from @hzoo of not returning evil for evil in terms of frustrated users wanting free support immediately. Keep up the good work, brother!

(As far as the issue, I'll close it after a week just so people can at least consider the amount of work that goes into this project. Feel free to close it sooner if need be. 😄)

**Comment by thiagoarrais** [comment]
Just wanted to weigh in here.

Maintaining open source is at many levels an unappreciated job. Thank all mantainers for your hard work. @hzoo is leading the pack here, but [all other team members](https://babeljs.io/team) are also responsible for growing such an exemplary community.

**Comment by hzoo** [comment]
Thanks @rcdilorenzo!! Much appreciated 🙌

aside: haha we should make some GitHub Actions later to insert some gifs or something for our bot instead of the same message
