### ISSUE TITLE
create-react-app + mobx decorators 

### ISSUE THREAD

**Issue by monkeyCheng** [babel/babel#8929]
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.

**Comment by monkeyCheng** [comment]
![image](https://user-images.githubusercontent.com/22185735/47554396-c79c3080-d93b-11e8-9a46-12adec316445.png)

I have already executed npm install --save-dev babel-plugin-transform-decorators-legacy  and  modified configuration

**Comment by nicolo-ribaudo** [comment]
IIRC, `create-reacy-app` uses Babel 7. Can you try to install `@babel/plugin-proposal-decorators` and add `["@babel/proposal-decorators", { "legacy": true }]` to your config?

**Comment by monkeyCheng** [comment]
@nicolo-ribaudo thanks for your answer,i try
