### ISSUE TITLE
Feature Request: "caller" option for @babel/cli

### ISSUE THREAD

**Issue by lixiaoyan** [babel/babel#8930]
## Feature Request

```sh
babel --caller '{name: "...", supportsStaticESM: true}' ...
```

**Comment by nicolo-ribaudo** [comment]
What is your use case? The caller option is meant to be used by tools (e.g. babel-loader), not directly. You can just update your babel configuration to disable modules transformaton.

**Comment by lixiaoyan** [comment]
@nicolo-ribaudo Thanks for your explanation.
