### ISSUE TITLE
You must sign up for private packages : @babel/plugin-transform-omi-jsx

### ISSUE THREAD

**Issue by dntzhang** [babel/babel#8933]
How to publish private package for babel7？

https://github.com/Tencent/omi/issues/123

**Comment by nicolo-ribaudo** [comment]
The `@babel/` prefix is only for official packages. You should publish it as `babel-plugin-transform-omi-jsx` and write in the readme that if it is compatible with Babel 7 or Babel 6.

**Comment by dntzhang** [comment]
ok. thanks~~
