### ISSUE TITLE
some import statements in files are not being transformed 

### ISSUE THREAD

**Issue by lopugit** [babel/babel#8934]
I made a reproduction repo at 

https://github.com/lopudesigns/reproduction

`git clone https://github.com/lopudesigns/reproduction && cd reproduction && npm i && build`

then if you go to `lib/testImport3/module1/files/test.js`

it has 
`
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.test1 = test1;

function test1(test) {
  console.log(test);
}
`
which is what it should be, I can't reproduce the error.. but in my real repo where the issue is

if you `git clone https://github.com/lopudesigns/wehelpjs && cd wehelpjs && npm i && npm run build`

and go to `lib/auth/ecc/files/aes.js` you'll see

`
var secureRandom = require('secure-random');

var ByteBuffer = require('bytebuffer');

var crypto = require('browserify-aes');

var assert = require('assert');

var PublicKey = require('./key_public');

var PrivateKey = require('./key_private');

var hash = require('./hash');

const Long = ByteBuffer.Long;
/**
    Spec: http://localhost:3002/steem/@dantheman/how-to-encrypt-a-memo-when-transferring-steem
    @throws {Error|TypeError} - "Invalid Key, ..."
    @arg {PrivateKey} private_key - required and used for decryption
    @arg {PublicKey} public_key - required and used to calculate the shared secret
    @arg {string} [nonce = uniqueNonce()] - assigned a random unique uint64

    @return {object}
    @property {string} nonce - random or unique uint64, provides entropy when re-using the same private/public keys.
    @property {Buffer} message - Plain text message
    @property {number} checksum - shared secret checksum
*/

export function encrypt(private_key, public_key, message, nonce = uniqueNonce()) {
  return crypt(private_key, public_key, nonce, message);
}
`

which means it isn't being transformed properly

other files are being transformed properly.

It seems that the problem is restricted to the auth/ecc and auth/serializer folders but I've been trying to fix this for 48 hours to no avail

the .babelrc files are configured the same, @babel/deps are the same in both repo's

I can't figure it out

**Comment by lopugit** [comment]
IT WAS BECAUSE SRC/AUTH/SERIALIZER AND ECC HAD PACKAGE.JSON FILES IN THEM

and because of the specific _babel property in their package.json's I'm guessing

**Comment by nicolo-ribaudo** [comment]
If you want your config to be applied to nested packages, you can use `babel.config.js` instead of `.babelrc`
