### ISSUE TITLE
babel-helper-plugin-utils syntax error

### ISSUE THREAD

**Issue by Caspinol** [babel/babel#8936]
## Bug Report

**Current Behavior**
There seem to be a syntax error on line 93 in the babel-helper-plugin-utils/index.js.

**Input Code**
https://github.com/babel/babel/blob/d942d47e10e84d5da0ad9c85f1f73403b82d7a61/packages/babel-helper-plugin-utils/src/index.js#L93

**Environment**
- Babel version(s): Master branch
- Node/npm version: v10.11.0
- OS: OSX 10.13.6

**Possible Solution**
Removing `:any`.

**Comment by loganfsmyth** [comment]
The `: any` is a Flowtype annotation. https://babeljs.io/docs/en/babel-preset-flow

**Comment by Caspinol** [comment]
Ahh, very well then. Sorry for false alarm.
