### ISSUE TITLE
throwIfNamespace doesn't work

### ISSUE THREAD

**Issue by TheKnarf** [babel/babel#8941]
## Bug Report

**Current Behavior**
I'm building a library that need to be able to work with JSX with namespaces. According to [Babel documentation](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) this should work by setting the throwIfNamespace option. However this does not seem to work.

**Input Code**
https://github.com/TheKnarf/babel-namespace-test

**Expected behavior/code**
Running `babel src/index.js` should transpile the test code without any errors.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: ['@babel/preset-react'],
  plugins: [
    ['@babel/transform-react-jsx', {
      'pragma': 'dom',
		'throwIfNamespace': false
    }]
  ]
}
```

**Environment**
- Babel version(s): 7.1.2 (@babel/core 7.1.2)
- Node/npm version: v10.12.0
- OS: macOS 10.13.6
- How you are using Babel: cli

**Additional context/Screenshots**
<img width="449" alt="screen shot 2018-10-29 at 13 07 56" src="https://user-images.githubusercontent.com/213777/47648871-ad509580-db7b-11e8-9f4a-c4d565f9ce39.png">

**Comment by TheKnarf** [comment]
The throwIfNamespace flag seems to have been added by @jukben in commit 04d2c030be2ecbbcdfc664b6ef16ef5f23eb0b20 from PR #6563. I tried downgrading to beta.5 as that seems to be the first version that includes that commit, but I can't get it to work there either.

Cloning the babel repo and running test suit myself verifies that the test introduced in #6563 does indeed work, so the question then becomes what I'm doing wrong / different than the test.

I changed the test script to include a verbose flag:
```
diff --git a/scripts/test.sh b/scripts/test.sh
index f9c9e384e..188fdde26 100755
--- a/scripts/test.sh
+++ b/scripts/test.sh
@@ -23,4 +23,8 @@ if [ -n "$TEST_ONLY" ]; then
   jestArgs+=("(packages|codemods)/.*$TEST_ONLY.*/test")
 fi

+if [ -n "$VERBOSE" ]; then
+       jestArgs+=("--verbose")
+fi
+
 $node node_modules/jest/bin/jest.js "${jestArgs[@]}"
(END)
```

And than ran it with:
```
TEST_ONLY=transform-react-jsx VERBOSE=true ./scripts/test.sh
```

The test called "should support xml namespaces if flag" seems to run and pass.

How would I go forward to duplicate what that test does in a new repo? Since whatever I did in my [own example](https://github.com/TheKnarf/babel-namespace-test) does not seem to work.

**Comment by TheKnarf** [comment]
I've boiled my issue down to a `.babelrc` that works and one that don't.

Working `.babelrc`:
```
{
  plugins: [
    ['@babel/transform-react-jsx', {
      'pragma': 'dom',
      'throwIfNamespace': false
    }]
  ]
}
```

Not working:
```
{
  presets: ['@babel/preset-react'],
  plugins: [
    ['@babel/transform-react-jsx', {
      'pragma': 'dom',
      'throwIfNamespace': false
    }]
  ]
}
```

Somehow adding `@babel/preset-react` breaks the `throwIfNamespace: false` functionallity.

**Comment by TheKnarf** [comment]
I now realised my mistake. I've been used to in eariler versions to set the pragma option directly on the plugin, but it seems that the correct way is to set options on the preset:

```
{
  "presets": [
    [
      "@babel/preset-react",
      {
        "pragma": "dom", // default pragma is React.createElement
        "pragmaFrag": "DomFrag", // default is React.Fragment
        "throwIfNamespace": false // defaults to true
      }
    ]
  ]
}
```

Still a bit weird, because setting the `pragma` option directly on the plugin works well, however setting throwIfNamespace only works if you either set it directly on the plugin but don't include the preset, or if you set it directly on the preset.

**Comment by loganfsmyth** [comment]
If you load `'@babel/preset-react'` and `'@babel/transform-react-jsx'` at the same time, you're loading two separate copies of `'@babel/transform-react-jsx'` with their own independent sets of options. While one of them has `throwIfNamespace: false` set, the other one will still do its default behavior of throwing an exception.

**Comment by TheKnarf** [comment]
Thanks, @loganfsmyth! I didn't realize it would load it twice.

I guess that closes this issue.
