### ISSUE TITLE
Some function types fail to parse inside arrow functions

### ISSUE THREAD

**Issue by mroch** [babel/babel#8942]
## Bug Report

**Current Behavior**
`let x = (): (T) => U => 123` is a parse error, to avoid ambiguity/lookahead after the first `=>`. Wrapping the return type in parens avoids the ambiguity: `let x = (): ((T) => U) => 123`

But it fails to parse when a function type is nested inside a generic, inside the return type (see below), even though that similarly delimits the nested function type.

**Input Code**
https://astexplorer.net/#/gist/af5836b64b734d2c74496bbcccec6f3e/305660c62c2d85a3475bf5df4e35fe40a3be29cc

```js
var x = (): Array<(string) => number> => [];
```

**Expected behavior/code**
Should parse as a function type with an anonymous `string` param, inside an `Array` generic type, inside the return type annotation of an arrow function.

**Environment**
- Babel version(s): 7.0.0
- How you are using Babel: astexplorer

**Possible Solution**
See related Flow parser fix: https://github.com/facebook/flow/commit/607e9fa83a5955a36d305ece10688411413ec492

I'm not sure how it's implemented in Babylon, but I'm guessing the fix might be similar.

**Comment by ijm87102** [comment]
Test

**Comment by ijm87102** [comment]
Test

**Comment by ijm87102** [comment]
Test

**Comment by danez** [comment]
Just to clarify: 
This is NOT a parse error:
```
let x = (): (string) => number => 123
```
whereas this is:
```
let x = (): (string) => 123 => 123
```
This is both true for latest babel-parser and flow 0.85.

That is correct I guess, because the first is not ambiguous?
