### ISSUE TITLE
Babel 7 Classes - arrow function overrides from constructor

### ISSUE THREAD

**Issue by hackmushroom** [babel/babel#8943]
## Bug Report

**Current Behavior**
I have class B that extends class A. Class A has an init method which is called from the constructor. Class B also has a init override but does not appear to be called? If I change init to a standard non-arrow function it works okay, is this how its supposed to be?

**Input Code**

```js
class A {
    constructor() {
        this.init();
    }

    init = () => {
        console.log('Class A init');
    }
}

class B extends A {
    init = () => {
        console.log('Class B init');
    }
}

const test = new B();
```

**Expected behavior/code**
I'd expect to see 'Class B init', but I get 'Class A init'

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": [
        "@babel/env"
    ],
    "plugins": [
        "@babel/plugin-proposal-class-properties"
    ]
}
```

**Environment**
  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/node": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/register": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    ...
}

**Comment by nicolo-ribaudo** [comment]
It is correct: class fields are initialized _after_ the parent constructor runs, because until then `this` isn't defined (so class fields couldn't be defined anywhere).

Normal methods work before they are defined on the prototype instead of `this`.
