### ISSUE TITLE
Babel 7 monorepo issue

### ISSUE THREAD

**Issue by judikdavid** [babel/babel#8945]
# v7 Regression

**Describe the regression**
I want to run build/test cli command from packages as well, not just from the project root.
If I run `npx babel-node index.js` in my project root, everything works as expected.
But if I run `npx babel-node index.js` inside `packages/packA`, I get the following error:
```
/Users/djudik/repos/babel-7/packages/packB/index.js:3
export default (a: number, b: number) => {
^^^^^^

SyntaxError: Unexpected token export
```

I assume that packB file does not get compiled when I want to use it from packA, not from the project root. 

**Input Code**
https://github.com/judikdavid/babel-7

**Babel Configuration (.babelrc, package.json, cli command)**
https://github.com/judikdavid/babel-7/blob/master/babel.config.js

**Expected behavior/code**
I should be able to use babel from any packages folder and it should use the root `babel.config.js` config.

**Environment**
- Babel version(s): "@babel/core": "^7.1.2"
- Node/npm version: Node 10.11.0/npm 6.4.1
- OS: OSX 10.14]
- Monorepo: yes
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
It is the expected behavior: Babel only searches for `babel.config.js` in the current directory. This behavior can be changed using the `root` and `rootMode` programmatic options, or using `babel-node --config-file ../../babel.config.js`

**Comment by judikdavid** [comment]
Thank you for your answer. However if I use `npx babel-node --config-file ../../babel.config.js index.js` in packA folder, I still get the same error.

**Comment by rwieruch** [comment]
I find it super difficult to find a minimal working example project on this topic :)

**Comment by adityak74** [comment]
Using `--ignore` worked for me with my monorepo setup.

**Comment by adityak74** [comment]
I got this working without the `--ignore` flag if you want to have a look at: https://github.com/adityak74/babel7-import-example

**Comment by saiftase** [comment]
@nicolo-ribaudo 
How does one set the `rootMode` option using gulp-babel?

I'm having a similar issue as OP. Looking at the [readme](https://github.com/babel/gulp-babel#api), gulp-babel allows you to pass in an object with options. 

`.pipe(plugins.babel({ rootMode: 'upward' }))`

This, however, does not seem to solve the issue. Am I doing something wrong here?

My application structure is:
babel.config.js
node_modules
src
--package1
----node_modules
--package2
----node_modules
--package3
----node_modules

**Comment by loganfsmyth** [comment]
@saiftase Would you be able to make a reproducible example? That should work.

**Comment by MoOx** [comment]
FYI, I was struggling with `--root-mode upward` and I ended up understanding that `package.json(#babel)` is not considered when looking upward. Am I wrong @loganfsmyth ?
I had to move my config to a `babel.config.js` to have "upward" behavior as expected. Took me a while, because I was clearly sure that `package.json` would work...

**Comment by loganfsmyth** [comment]
@MoOx `upward` looks for the root by finding a `babel.config.js`, but you'd still then want to configure the `babelrcRoots` value in order to load `package.json` config. `package.json` configs are treated identically to `.babelrc` files.

**Comment by MoOx** [comment]
I get that now, but it wasn't clear at all for me when reading migration/upgrade notes.

**Comment by adityak74** [comment]
@MoOx Would you be able to post a working example repo, that would help people trying to figure this out. Thanks.

**Comment by MoOx** [comment]
Here is my commit to migrate my monorepo to babel 7 
https://github.com/phenomic/phenomic/commit/bb0ce41b4fde26fbe4230601f3c39a6a442e873e
Not that hard after all, just a bit tricky :)

I guess the initial issue (this one) can be closed as the problem described initially is expected according to release notes. Maybe one improvement would be to add `--root-mode upward` option to `babel-node` too :) (to avoid the `--config-file ../babel.config.js`)

**Comment by jibees** [comment]
@MoOx Adding `--root-mode` option to `babel-node` already has its PR : https://github.com/babel/babel/pull/9148

**Comment by Tymek** [comment]
As a temporary solution, running babel-node from project root and not from package helped. In my case:
- `nodemon --exec babel-node ./packages/server/src/index.js`
- **not** `lerna run start --scope @(monoreponame)/server --stream` (with `start: nodemon --exec babel-node ./src/index.js` in package)

It reminded me: _this isn't stable version_ 🙂 Thank you all for spotting and bugfixing it.

**Comment by pitops** [comment]
For me what worked was to rename the root to `.babelrc` to `babel.config.js` and from there you can use the solution provided by @adityak74 to have multiple babel configs.

**Comment by judikdavid** [comment]
Thanks everyone for the suggestions, using this command from packA from my repo:
https://github.com/judikdavid/babel-7/tree/master/packages/packA
`npx babel-node --root-mode upward --ignore=" " index.js`
everything is working. So `--root-mode` takes care of finding the root babel.config.js in your project, and `--ignore=' '` takes care to transpile other packages that you could have in your monorepo.

**Comment by nmccready** [comment]
So how do you deal with this problem so webpack picks up the correct babel-loader options. I followed @adityak74 's repo and I have gotten the app to be 90% better. However, I still have some stubborn files that will not transform correctly, even though there `include`'s match exactly.

**Comment by nmccready** [comment]
More answers here https://github.com/babel/babel/issues/8309

**Comment by benfjohnson** [comment]
https://github.com/babel/babel/issues/8309#issuecomment-439161848 solved it for me (from the thread @nmccready linked above)

**Comment by nmccready** [comment]
For me this comment was by far the cleanest solution https://github.com/babel/babel/issues/8309#issuecomment-449515834
