### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by ShaMan123** [babel/babel#8949]
# v7 Regression

> First check out: https://new.babeljs.io/docs/en/next/v7-migration.html
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade => **Tried and is buggy**

**Potential Commit/PR that introduced the regression**
No idea.

**Describe the regression**
running `npm install` does not install sub modules.
running `yarn add` behaves strangely.

**Babel Configuration (.babelrc, package.json, cli command)**
not relevant

**Expected behavior/code**
#### npm
running `npm i --save-dev @babel/preset-env` (for example) does not add the package.
Deleting the entire `@babel` node_module directory causes the install the say it has added whatever sub module I've just installed but doesn't do that (Checked the folder `node_modules/@babel`)
running `npm cache clean --force` doesn't make a difference.

#### yarn
Using `yarn` solved the problem **ONLY** if installing this way: 
`yarn add --dev @babel/sub-moduleA @babel/sub-moduleB @babel/sub-moduleC`.
trying to install each one overrides the previous install:
```
yarn add --dev @babel/sub-moduleA
yarn add --dev @babel/sub-moduleB
yarn add --dev @babel/sub-moduleC
```

**Environment**
- Babel version(s): v7.1.2
- Node/npm version: node v10.13.0/npm 6.1.0
- OS:  Windows 10
- Monorepo: I think no
- How you are using Babel: guessing loader (sorry... using with react)

**Comment by nicolo-ribaudo** [comment]
If you install multiple packages (e.g. `npm install -D @babel/core` and `npm install -D @babel/preset-env`), which folders do you see inside `node_modules/@babel`?

**Comment by ShaMan123** [comment]
I saw that `@babel/core` removes `@babel`'s entire content before installing.
`yarn` does it too. It removes everything each time I add a package

**Comment by nicolo-ribaudo** [comment]
Give the last comment, it seems like a problem with your environment (maybe a file system issue or premission issue).
Anyway, this should be reported to yarn/npm.
