### ISSUE TITLE
Not all properties on import  with register 7

### ISSUE THREAD

**Issue by msaglietto** [babel/babel#8953]
# v7 Regression

I am updating an app to babel 7 and the application build with @babel/loader seems to be working fine but the test that run wit babel-registry is not working as before

On the app I'm updating the registry is included by mocha
```
default: `${crossEnv('NODE_ENV=test')} mocha 'test/**/*.test.js' --colors --require @babel/register --timeout 10000 --exit`,
```

So not sure if I'm missing some configuration or something is not working correctly

**Describe the regression**
When importing `mongoose` library the property `Schema` that  is  on the imported object when running with register 7 is not there anymore
In the example below the Schema property is undefined when used with @babel/register

**Input Code**

I create a repo to showcase the error https://github.com/msaglietto/babel-test
```js
import mongoose, { Schema } from 'mongoose';

console.log('Schema is', Schema);
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [ "@babel/env", { "targets": { "node": "8" } } ]
  ]
}
```

**Expected behavior/code**
You can use Schema from mongoose import with babel-register as in babel-loader 

**Environment**
- Babel version(s): 7.1.2
- Node/npm version: Node 10
- OS: Ubuntu 8.10
- Monorepo: no
- How you are using Babel: `register`

**Comment by nicolo-ribaudo** [comment]
The problem is that mongoose doesn't export both a default export and named exports (I don't know why it worked with Babel 6).
You should
```js
import mongoose from "mongoose";
const { Scheme } = mongoose;
```

**Comment by loganfsmyth** [comment]
Babel's interop helpers expects named imports to be `own` properties, but `.Scheme` lives on the `mongoose` instance's prototype: https://github.com/Automattic/mongoose/blob/5ba13a7808071cc1b13beffcb08006f6050e19da/lib/index.js#L678

We've also had this discussion in https://github.com/babel/babel/issues/6915#issuecomment-348555592 in the past.

**Comment by msaglietto** [comment]
Yes to work around that is not problem .. just is strange that babel-loader works and babel-register dont ...

**Comment by nicolo-ribaudo** [comment]
Babel is working correctly, given that [mongoose's export](https://github.com/Automattic/mongoose/blob/5ba13a7808071cc1b13beffcb08006f6050e19da/lib/index.js#L910) isn't a plain object and thus shouldn't be considered as a bag of named exports.
