### ISSUE TITLE
Why was Regexp.escape removed from babel-polyfill in v7?

### ISSUE THREAD

**Issue by jharris4** [babel/babel#8955]
# v7 Regression

**Potential Commit/PR that introduced the regression**

I dug into it and noticed that in V6, babel-polyfill has this comment & code:

```
// Should be removed in the next major release:

import "core-js/fn/regexp/escape";
```

https://github.com/babel/babel/blob/6.x/packages/babel-polyfill/src/index.js#L11

**Describe the regression**

After upgrading to Babel 7 (from 6) I get these errors in the browser:

`Uncaught TypeError: RegExp.escape is not a function`

**Expected behavior/code**

I was expecting RegExp.escape to continue working :-)

I get that it seems to have been removed on purpose, but I tried and failed to find any issue or note in the upgrade/migration guides that describes why.

**Environment**
- Babel version(s): 7.0

**Comment by loganfsmyth** [comment]
`RegExp.escape` is not a standard function. Support for it was dropped because it is no longer being explored as part of the spec. I'd recommend using https://www.npmjs.com/package/regexp.escape or https://lodash.com/docs/4.17.11#escapeRegExp

**Comment by jharris4** [comment]
ah ok thanks for the back story!

I actually ended up going with https://github.com/sindresorhus/escape-string-regexp as a workaround.
