### ISSUE TITLE
Dynamic imports must disallow trailing comma

### ISSUE THREAD

**Issue by wchargin** [babel/babel#8957]
### Current Behavior

Dynamic imports are allowed to have trailing commas. The spec says that
they must not.

### Input Code

```js
import("abc");  // OK
import("def", );  // should fail to parse!
```

[BabelJS REPL link.](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgFAIgIYCMDGCCUBuABLgegNwHkBpAKFElkQBMBTAMwQBpcd8jcBnACwgBXADZ1cTJMGG4YEXGCRQeDAIQUgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

### Expected behavior/code
This should raise a parse error. The *ImportCall* production has

> **`import`** **`(`** *AssignmentExpression* **`)`**

and an *AssignmentExpression* cannot have a trailing comma.

See also: <https://github.com/facebook/flow/issues/7124>

See also: <https://github.com/tc39/proposal-dynamic-import/issues/15>

### Babel Configuration (.babelrc, package.json, cli command)

Default on REPL (es2015, stage-2, react).

**Comment by ljharb** [comment]
I think it should be allowed; that’s not the same as signaling that it might change. I’d file a new issue in that repo for allowing a trailing comma (or better, make a PR that allows it)

**Comment by existentialism** [comment]
Fixed in https://github.com/babel/babel/pull/9313
