### ISSUE TITLE
Import used by @jsx pragma is elided by typescript transform

### ISSUE THREAD

**Issue by Jessidhia** [babel/babel#8958]
## Bug Report

**Current Behavior**
When an imported value is used only implicitly via JSX, the typescript type import elision is incorrectly removing the "type-only" import.

**Input Code**
- REPL or Repo link if applicable:

```js
/* @jsx jsx */
import { jsx } from '@emotion/core'

import ReactDOM from 'react-dom'

ReactDOM.render(<div/>, document.appendChild(document.createElement('div')))
```

**Expected behavior/code**
The "jsx" import should still be present in the output

**Babel Configuration**

Literally `create-react-app --typescript` defaults.

**Additional context/Screenshots**

Output from webpack:

```js
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react-dom */ "./node_modules/react-dom/index.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react_dom__WEBPACK_IMPORTED_MODULE_0__);
var _jsxFileName = "/Users/kovensky/src/statsim/src/index.tsx";

/* @jsx jsx */

react_dom__WEBPACK_IMPORTED_MODULE_0___default.a.render(jsx("div", {
  __source: {
    fileName: _jsxFileName,
    lineNumber: 6
  },
  __self: undefined
}), document.appendChild(document.createElement('div')));
```

Note how the `@emotion/core` import is missing entirely.

Adding an unused `jsx` reference anywhere to the file makes the build correct.

**Comment by jfrolich** [comment]
A fix is to not use the pragma parameter of the typescript plugin (keep the default react). Then use another babel plugin (order matters) to add the pragma. Not ideal. I think the typescript plugin shouldn't need to do anything with the pragma parameter. I think it needs to specify the pragma so it knows it needs to strip out type only imports. However these will be tree shaken out anyway I guess, so do we really need to have this option?

**Comment by cameron-martin** [comment]
Surely there should be a similar option in the typescript preset that mirrors the [`pragmaFrag` option](https://babeljs.io/docs/en/babel-preset-react#pragmafrag) in the react preset.
