### ISSUE TITLE
Upgrade to v7 stops module concatentation from working

### ISSUE THREAD

**Issue by jacobwindsor** [babel/babel#8960]
# v7 Regression

> First check out: https://new.babeljs.io/docs/en/next/v7-migration.html
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Potential Commit/PR that introduced the regression**
I'm unsure if this is related to a change in babel or babel loader. I would guess babel but have been unable to find a PR related to it. However, [PR #660](https://github.com/babel/babel-loader/pull/660) in babel-loader is related.

**Describe the regression**
When upgrading to babel 7, webpack's module concatenation does not behave correctly. Everything builds okay but results in a runtime error:

![image](https://user-images.githubusercontent.com/5579270/47856953-58618900-dde0-11e8-8d56-426af67aabf5.png)

Disabling `optimization.concatenateModules` in the webpack production config fixes this.  `optimization.concatenateModules` is disabled by default in the development mode so this issue only arises in production.

As expected from previously mentioned babel-loader PR, setting `modules` to `commonjs` in the babel config also fixes the issue. 

Both of the above fixes just force module concatenation to be disabled.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": [["@babel/env", {
        "targets": {
            "browsers": ["last 2 versions", "ie >= 9"]
        }
        , "useBuiltIns": "entry"
    }]]
    , "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

**Expected behavior/code**
Webpack's module concatenation should behave as expected with Babel 7.

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: 8.9.4
- OS: windows 10
- babel-loader: 8.0.4
- How you are using Babel: loader

**Comment by jacobwindsor** [comment]
Module concatenation would have been disabled before I upgraded to babel 7 too. I hadn't disabled module transformation in the babel config.

So, this might not be a babel issue but I'm unable to confirm whether it's a webpack issue. I'll leave it here in the hope that someone might have an idea.

**Comment by loganfsmyth** [comment]
Not sure specifically, but maybe this is related to https://github.com/webpack/webpack/issues/4039#issuecomment-419284940? Are you compiling any CommonJS files in your project? If not, it's possible you're doing something else that Webpack doesn't expect. I'm not sure, I'd have to see the actual code that throws the error.

**Comment by jacobwindsor** [comment]
Thanks for the tip @loganfsmyth 

Unfortunately, I can't share the code. It doesn't seem like our project is subject to any of those two conditions. We are only transpiling our source code and not node_modules and are using harmony imports/exports everywhere. The only thing I can think is that we have one file that contains many harmony imports and one require statement. The require statement is needed as it is importing a commonjs module. 

I have tried adding `sourceType: unambigous` but it does not help.

**Comment by danez** [comment]
Can you try adding `modules: false` to the preset-env config? In theory babel should autodetect that webpack supports esmodules and set this configuration, but if this fixes the problem, then we definitely know it is a problem in babel.

```js
{
    "presets": [["@babel/env", {
        "targets": {
            "browsers": ["last 2 versions", "ie >= 9"]
        }
        , "modules": false
        , "useBuiltIns": "entry"
    }]]
    , "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

**Comment by jacobwindsor** [comment]
@danez That does not fix the issue. Still exactly the same problem. Why does this mean it;s a babel issue?

**Comment by nicolo-ribaudo** [comment]
If not transforming modules with Babel doesn't solve the issue, then it is a bug with webpack.

**Comment by jacobwindsor** [comment]
Closed and moving to webpack repo
