### ISSUE TITLE
@babel/types BaseComment type not match @babel/parser output

### ISSUE THREAD

**Issue by wulunyi** [babel/babel#8969]
@babel/types/lib/index.d.ts 
```typescript
interface BaseComment {
  value: string;
  start: number;
  end: number;
  loc: SourceLocation;
  type: "BlockComment" | "LineComment";
}

export interface BlockComment extends BaseComment {
  type: "BlockComment";
}

export interface LineComment extends BaseComment {
  type: "LineComment";
}
```
https://astexplorer.net/ result
![image](https://user-images.githubusercontent.com/15170275/47962877-35440d00-e05e-11e8-9636-446487454e6f.png)

![image](https://user-images.githubusercontent.com/15170275/47962874-2a897800-e05e-11e8-87cf-1bc196c43894.png)

**Comment by alexsilvar** [comment]
Hello, which is the expected output, "BlockComment" ? (please, tell which version of Babel are you using at astexplorer)

**Comment by wulunyi** [comment]
I expect the @babel/types .d.ts comment declaration match the @babel/parser output.

@babel/parser version 7.1.0
The parser output  comment node type "CommentBlock"
