### ISSUE TITLE
Decorator without key create a property named 'undefined'

### ISSUE THREAD

**Issue by pabloalmunia** [babel/babel#8973]
If we configure -by error- a `descriptor.key` as `undefined` and the plugin create a new field with `"undefined"` as name:

```js
function changeName (name) {
  return function(descriptor) {
    descriptor.key = name;
    return descriptor;
  }
}

class K {
  @changeName()
  m() {
    return 'm';
  }
  @changeName('f')
  j() {
    return 'f';
  }
}

const k = new K();
console.log(k.undefined()); // 'm'
console.log(k.f());         // 'f'
```

It's not a very important issue, because we can check the name before the decoration, but perhaps it's a little error into the babel transpilation.

**Comment by nicolo-ribaudo** [comment]
I think that it is correct: `descriptor.key` is converted to a string and then used to create the method (`String(undefined) === "undefined"`).

**Comment by pabloalmunia** [comment]
Umm, I read the the decorator specification send to ECMAScript specification for toPropertyKey:

> 7.1.14 ToPropertyKey ( argument )
> The abstract operation ToPropertyKey converts argument to a value that can be used as a property key by performing the following steps:
>
> 1. Let key be ? ToPrimitive(argument, hint String).
> 2. If Type(key) is Symbol, then
>     a. Return key.
> 3. Return ! ToString(key).

Yes, the behavior it's OK, little bit strange, but this is the specification.

Kind regards
