### ISSUE TITLE
@babel/generator is removing the parentheses

### ISSUE THREAD

**Issue by oyilmaztekin** [babel/babel#8974]
## Bug Report

**Current Behavior**
Generated codes and source codes aren't the same. When the code generation occurs parentheses after the render is removing. I checked the nodes after transforming ` parenthesized: true` is still there.

**Input Code**
- https://github.com/oyilmaztekin/vscode-undoc/blob/dev/lib/astStages.js#L229

```js
function(parsedAst) {
    const babelGenerator = require('@babel/generator');

    let generatedCode = "";
    let outputFunc= babelGenerator.default(parsedAst, generatedCode);
    return outputFunc
}
```

**Expected behavior/code**
Dom objects or components are needed to be inserted into the render parentheses

**Babel Configuration (.babelrc, package.json, CLI command)**
There is no specified babel conf but only dependencies
```js
 "dependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "@babel/parser": "^7.1.3",
    "@babel/plugin-proposal-async-generator-functions": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-proposal-optional-catch-binding": "^7.0.0",
    "@babel/plugin-transform-block-scoped-functions": "^7.0.0",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0",
    "@babel/plugin-transform-literals": "^7.0.0",
    "@babel/plugin-transform-object-super": "^7.1.0",
    "@babel/plugin-transform-react-display-name": "^7.0.0",
    "@babel/plugin-transform-react-jsx": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-generator": "^6.26.1",
    "babel-traverse": "^6.26.0",
    ...... 
}
```

**Environment**
- Babel version(s): [e.g. v7.1.2,]
- Node/npm version: [e.g. v8.11.1]
- OS: [e.g. OSX 10.13.4]
- Monorepo [e.g. no]
- How you are using Babel: [e.g. `cli`]

**Additional context/Screenshots**
**Input:**
![input code](https://user-images.githubusercontent.com/863600/47958105-32510a00-dfd5-11e8-99ac-1e3dbee0a437.png)

**Output**
![output code](https://user-images.githubusercontent.com/863600/47958106-3c730880-dfd5-11e8-8352-0e53086264c8.png)

**Comment by nicolo-ribaudo** [comment]
That parentheses are optional, so the input code and the output code have the same behavior.
Babel doesn't make any guarantees about formatting: if you need to keep the original code style, you should use recast (you can see how to use recast and Babel together at  https://github.com/nicolo-ribaudo/legacy-decorators-migration-utility/blob/1c9f306b5287bb2d5d07a512d1ad84036fd4956a/packages/wrap-legacy-decorators/src/index.js#L105)
