### ISSUE TITLE
Feature request: destructuring props inside of JSX tags

### ISSUE THREAD

**Issue by harrysolovay** [babel/babel#8976]
## Feature Request

**Consider the following:**
```jsx
class BoardWithDraggables extends Component {
  onDragStart = () => {...}
  onDragUpdate = () => {...}
  onDragEnd = () => {...}
  render() {
    const {onDragStart, onDragUpdate, onDragEnd} = this
    return (
      <DragDropContext {...{onDragStart, onDragUpdate, onDragEnd}}>
        {...}
      </DragDropContext />
    )
  }
}
```

**It would be fantastic if users could do this instead:**
```jsx
class BoardWithDraggables extends Component {
  onDragStart = () => {...}
  onDragUpdate = () => {...}
  onDragEnd = () => {...}
  render() {
    return (
      <DragDropContext {...{this: {onDragStart, onDragUpdate, onDragEnd}}}>
        {...}
      </DragDropContext />
    )
  }
}
```

**Teachability, Documentation, Adoption, Migration Strategy**
This isn't a breaking change, so no real strategy is necessary. One way to spread the word would be to get BabelJS contributors to use this syntax in documenting their numerous, extremely-popular libraries.

**Comment by nicolo-ribaudo** [comment]
You should propose this feature either to the JSX spec (https://github.com/facebook/jsx) or to the ECMAScript spec[1] (https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals). Babel only implements things defined by some standard.

[1] You might be interested in this discussion: https://esdiscuss.org/topic/extended-dot-notation-pick-notation-proposal

PS.
```js
class BoardWithDraggables extends Component {
  onDragStart = () => {...}
  onDragUpdate = () => {...}
  onDragEnd = () => {...}
  render() {
    return (
      <DragDropContext {...{this: {onDragStart, onDragUpdate, onDragEnd}}}>
        {...}
      </DragDropContext />
    )
  }
}
```

This is already valid code, so it would be a breaking change. Currently, it is equivalent to
```js
class BoardWithDraggables extends Component {
  onDragStart = () => {...}
  onDragUpdate = () => {...}
  onDragEnd = () => {...}
  render() {
    return (
      <DragDropContext this={{onDragStart, onDragUpdate, onDragEnd}}>
        {...}
      </DragDropContext />
    )
  }
}
```

**Comment by harrysolovay** [comment]
Ahhh gotcha. Thank you for taking the time to give such a good response!

I now see how it would be breaking.
