### ISSUE TITLE
Better control over external helpers

### ISSUE THREAD

**Issue by scottgonzalez** [babel/babel#898]
Using `externalHelpers` is nice for transforming several files individually, then concatenating them later, but this has two negative side effects:

* Every helper must be included, even if only a few are needed.
* The helpers are exposed as globals.

If `babel.transform()` would expose the list of helpers that were required by the transform and `babel.buildExernalHelpers()` accepted an array of helpers to build, then builds could be optimized. Ideally there would be a way to completely skip the global setting as well.

**Comment by sebmck** [comment]
> The helpers are exposed as globals.

Sounds like you might be looking for the [optional runtime transformer](http://babeljs.io/docs/usage/runtime/) then.

> If `babel.transform()` would expose the list of helpers that were required by the transform and `babel.buildExernalHelpers()` accepted an array of helpers to build

Hm, possibly, should be fairly easy to implement.

**Comment by sebmck** [comment]
Added as of 4.5.2, writing up docs now.

**Comment by sebmck** [comment]
Docs available [here](http://babeljs.io/docs/usage/external-helpers/#selective-builds). Thanks!

**Comment by scottgonzalez** [comment]
Thanks for getting this done so fast. The whitelist doesn't seem to be working for me though. When calling `babel.buildExternalHelpers([ 'class-call-check', 'inherits', 'prototype-properties' ])`, I'm still getting all of the helpers.

**Comment by sebmck** [comment]
@scottgonzalez Ugh whoops, had the whitelist logic completely back the front. dc6129eb6a2036954ef295ecc300362649c96470. I'll push out a new version now.

**Comment by sebmck** [comment]
Should be fixed as of 4.5.4.

**Comment by scottgonzalez** [comment]
Thanks, that got my build much smaller :-)

So the only thing left for me is the globals. I'm building for the browser and I want to bundle the helpers in my code, so I don't think the runtime transformer is an option. Am I missing something?

**Comment by sebmck** [comment]
Yeah it's not suitable since it'll include **all** the helpers, they just wont be global. There's not really a way to do it as you'd have to add something like browserify to your build system to load them in locally and if you have that then you probably don't care about the additional 5KB that the external helpers take up.
