### ISSUE TITLE
IE Syntax error on minified code evaluation

### ISSUE THREAD

**Issue by attatrol** [babel/babel#8980]
## Bug Report

**Current Behavior**
IE 11.0.14393.0 returns error `Syntax error in regular exception` when i try to copy the minified code in its console.

**Input Code**
[REPL link](https://babeljs.io/repl#?babili=true&browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBGCmDm0A8AOBVAdgSwMYHsAm0AygK5JI5gAuA3AFABmxaWlGOaEl0AzpQBQBKCAG8ItSmACeIiGmgB3CACU4AUWR8ARAB1i9ffU0AaCJuKaB1KHESpMuAiTIVKEALycwxaFYC-tCAgsEEosAAs-aCFhf18gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Cbabili%2Cenv&prettier=true&targets=&version=6.26.0&envVersion=1.6.2)

```js
var regexpUnicodeSupport;
function test() { 
try { new RegExp("\uffff", "u"); regexpUnicodeSupport = true; }
  catch(e) {}
}
```

**Expected behavior/code**
Successful evaluation.

**Babel Configuration**
default minify preset used by REPL

**Environment**
REPL

**Comment by nicolo-ribaudo** [comment]
I'm moving this issue to the minifier repo.

@babel-bot Move to babel/minify
