### ISSUE TITLE
index.js with export default as returns undefined

### ISSUE THREAD

**Issue by BorisTB** [babel/babel#8987]
## Bug Report

**Current Behavior**
File structure:
```
components
│__ComponentA
|  └ index.js
│__ComponentB
|  └ index.js
│__ComponentC
|  └ index.js
└ index.js
```

components/index.js
```javascript
export { default as ComponentA } from './ComponentA'
export { default as ComponentB } from './ComponentB'
export { default as ComponentC } from './ComponentC'
```

components/ComponentA/index.js
`import { ComponentC } from 'Components' // Components is webpack alias to components folder`

So the problem is when I import ComponentA in ComponentB with destructuring (`import { ComponentA } from 'Components'`), it's undefined. Behaviour is similar to circular dependency, but I don't think this should be treated as circular dep. Other imports works great, until I don't import other components in them.

**Expected behavior/code**
The component should be defined when imported with destructuring

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-env",
    ["react-app", {
      "flow": true,
      "typescript": false
    }]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime",
    "inline-dotenv",
    "relay"
  ]
}
```

**Environment**
- Babel version(s): 7.1.0
- Node/npm version: Node v11.1.0 / npm v6.4.1
- OS: OSX 10.14
- Monorepo no
- How you are using Babel: `loader`

**Comment by nicolo-ribaudo** [comment]
If you are using babel-loader, Babel isn't traspiling those exports since they are handled by webpack.

**Comment by nicolo-ribaudo** [comment]
Answered at https://github.com/babel/babel/issues/8987#issuecomment-436786792
