### ISSUE TITLE
Not possible to create a `ClassMethod` with a `LogicalExpression` as the key

### ISSUE THREAD

**Issue by majapw** [babel/babel#8991]
## Bug Report

**Current Behavior**
It is not possible to create a `ClassMethod` with a `LogicalExpression` as the key, e.g. something like:
```
class foo() {
  [someBoolean && 'foo']() {
    ...
  }
}
```

**Input Code**
```js
const method = t.classMethod(
      'method',
      t.logicalExpression(
        '&&', 
        t.identifier('someBoolean'),
        t.stringLiteral('foo')
      ),
      [],
      t.blockStatement([])
    );
```

**Expected behavior/code**
The above code should not error. Instead, it throws
```
unknown: Property key of ClassMethod expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "LogicalExpression"
```

**Environment**
- Babel version(s): v6, v7 (as included in https://astexplorer.net/)
- How you are using Babel: ASTExplorer, errors similarly when writing the same code as a custom babel transform

to: @ljharb @skevy

**Comment by ljharb** [comment]
Indeed, a computed property name should be able to take any expression value whatsoever.

**Comment by majapw** [comment]
Is there any way we could improve the error message in that case?

**Comment by nicolo-ribaudo** [comment]
Currently the error messages are auto-generated, so I don't think that it is worth to add a special case.

**Comment by majapw** [comment]
Welp, guess this can be closed. It'd be great if discoverability of this option (and what it does) could be increased.
