### ISSUE TITLE
getParentNode

### ISSUE THREAD

**Issue by Ivorfason** [babel/babel#8995]
I have a problem:

page A:   `<div><B a="1" b="2"/><div>`

how can I get the node A? I have got the node at B, but path.parentPath doesn't work which can only got the first node in B.

**Comment by xtuc** [comment]
Have you tried `path.parentPath`?

**Comment by Ivorfason** [comment]
> Have you tried `path.parentPath`?

I tried this. but it can only got the node in B...  I want get the node in A

**Comment by Ivorfason** [comment]
> Where is node A? If it's its parent you can do `path.parentPath.parentPath` or use `a = path.findParent(node => ...)`

page A:
`import B from './B;
 return (
<div><B a=1 b=2></div>
)`

page B:
`return (<div><div><p>123</p></div></div>)`;

**Comment by xtuc** [comment]
I see, Babel parses an AST per file, so we won't be able to jump between those two modules/pages.

**Comment by Ivorfason** [comment]
> I see, Babel parses an AST per file, so we won't be able to jump between those two modules/pages.

all right... thanks :)
