### ISSUE TITLE
Babel Couldn't find preset "@babel/preset-env"(with preset installed!)

### ISSUE THREAD

**Issue by nikoladim123** [babel/babel#9002]
im getting Couldn't find preset "@babel/preset-env" error with message 
Error: Couldn't find preset "@babel/preset-env" relative to directory "C:\\Users\\TMB\\Desktop\\prac
tise\\React"
    at C:\Users\TMB\Desktop\practise\React\Babel\node_modules\babel-core\lib\transformation\file\opt
ions\option-manager.js:293:19

Even tho i 100% instaled preset-env,here is my package.json

{
  "name": "babel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "babel src -d lib"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/preset-env": "^7.1.5",
    "babel-cli": "^6.26.0"
  },
  "dependencies": {
    "babel-preset-env": "^1.7.0"
  }
}

and my .babelrc

{
  "presets": ["@babel/preset-env"]
}

i installed preset, and followed every instruction on Babel official website and tried all other sources on internet and could not find any solutions.

**Comment by danez** [comment]
You should install `@babel/preset-env and @babel/cli` for babel 7.

`babel-cli and babel-preset-env` are for version 6.x and will not work with babel 7 packages (`@babel/xxx`)
