### ISSUE TITLE
--watch stops because of compilation error

### ISSUE THREAD

**Issue by chpill** [babel/babel#901]
Hello!

I'm using babel to transpile my code on each file change with the following command: `babel server --out-dir dist --blacklist regenerator -w`. This works really well, until I write, say, a syntax error. The process then exits with status 1.

As I'm fairly new to ES6 syntax I tend to make a lot of mistakes. Having to restart the watch process each time may be a bit unforgiving to newbies like me :).

Is this behavior intentional?

*tested with:*
* iojs v1.3.0
* npm 2.5.1
* babel 4.5.5

**Comment by sebmck** [comment]
Yeah, it's the current behaviour but it's not the ideal behaviour I agree, just haven't gotten around to wrapping it in a try-catch.

**Comment by chpill** [comment]
Thanks for the quick update! Sadly, this does not work :(

No exception are thrown during transformation, the process exits directly on syntax error https://github.com/babel/babel/blob/339bd2b6d9999db78f2e7db7b6a5ad60f0b1d3b4/bin/babel/util.js#L35

**Comment by sebmck** [comment]
Oh shit, right.

**Comment by sebmck** [comment]
Fixed, can't recall why it was like that.

**Comment by chpill** [comment]
It works! This is going to save me a lot of time, thanks a lot!
