### ISSUE TITLE
Couldn't find preset "@babel/env" relative to directory

### ISSUE THREAD

**Issue by Pasoul** [babel/babel#9016]
## Bug Report

**Current Behavior**

I use webpack to build the js file. The js file import an NPM package。When I run `yarn run build`,
npm package was error：`Couldn't find preset "@babel/env" relative to directory "/Users/username/project/node_modules/jlb-tools"`

**Input Code**

My project's package.json
```js
{
  "dependencies": {
    "jlb-tools": "^0.0.4"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "7",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2"
  },
  "scripts": {
    "build": "webpack --mode development"
  }
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

My project's .babelrc

```js
{
	"presets": ["env", "stage-0"]
}
```

The npm package's .babelrc

```js
{
  "presets": [["@babel/preset-env", { "modules": false }]],
  "env": {
    "test": {
      "plugins": ["istanbul"]
    }
  }
}

```

**Environment**
- Babel version(s):v6.26.3
- Node/npm version: Node 8.9.10
- OS: 10.13.5
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: loader

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/22902187/48334964-4a8ced00-e697-11e8-9e23-f00043418087.png)

**Comment by Pasoul** [comment]
I change npm package's .babelrc to .babelrc.js,and it work

```js
module.exports = {
  presets: [
    require('@babel/preset-env')
  ]
}
```
why?

**Comment by nicolo-ribaudo** [comment]
It's because Babel 6 only handles .babelrc files. To fix your problem, you should exclude node_modules from your compilation.

**Comment by Pasoul** [comment]
ok,thanks
