### ISSUE TITLE
Is there a @babel scoped version of this package?

### ISSUE THREAD

**Issue by adamreisnz** [babel/babel#9017]
If not, why not?

**Comment by nicolo-ribaudo** [comment]
Which package?

**Comment by adamreisnz** [comment]
Sorry, I must have raised this issue in the wrong repository. I wanted to post it on `babel-plugin-syntax-async-functions` repo, and I'm referring to that package.

**Comment by adamreisnz** [comment]
I see that package documented on the babel site, but it has no (apparent) @babel scoped counter part, only async generators.

**Comment by nicolo-ribaudo** [comment]
That package has been deprecated and is not maintained anymore, since parsing async functions is now enabled by default.

**Comment by adamreisnz** [comment]
Ok, it might be worthwhile to mention that on the package readme, or deprecate it using npm.

**Comment by escapedcat** [comment]
@nicolo-ribaudo 
> [...] since parsing async functions is now enabled by default.

Is there a link to where this is enabled or documented? Thanks!
