### ISSUE TITLE
plugin-transform-regenerator can produce infinite loop using async/await and nested try/catch/finally

### ISSUE THREAD

**Issue by mgroenhoff** [babel/babel#9019]
## Bug Report

**Current Behavior**
The state machine produced by `@babel/plugin-transform-regenerator` is incorrect and *can* produce an infinite loop using nested try/catch/finally statements inside a loop together with async/await as shown in the example below.

If I run the code from the repl below with `node` it loops two times and then exits the loop. If I run the code produced by `babel` it loops 10 times.

**Input Code**

```js
let call = 0;
async function callback() {
    ++call;
    if (call < 2) {
        throw new Error("err");
    }
    call = 0;
}

async function main() {
    let retry;
    do {
      	retry = false;
        let result;
        try {
            try {
                result = await callback();
                console.log("success");
            } catch (error) {
                console.log("error 1");
                throw error;
            }/* finally {
                // If I enable this finally block and `await callback()` does not throw ("success"), it jumps to the outer catch block ("error 2") below
                console.log("finally 1");
            }*/
        } catch (error) {
            console.log("error 2");
            retry = true;
        } finally {
            console.log("finally 2");
        }
    } while (retry);
}

main();
```

[See repl](https://babeljs.io/repl#?babili=false&browsers=IE%2011&build=&builtIns=false&spec=false&loose=false&code_lz=FAGwpgLgBAxghiEUC8UAMBuYcDOBPAOxigDMBXIiASwHsDYEQAjOGAawAoBKKAb2CiCoAamHxEWIVCokoHcUgA8UAEw9-UqRAAWAJxoB3KATBGAorv26OAIjCWbXSUIC-AoQpTosb7PiKkFDDUdFAAtnBUBNx87oLg0LqQunjO8ZBQcBAQYGEADtComHFQACY0sZpQAJBJECleJAg4YGmaolk5-RBtUglQSThkID0lWg0aVZr1eJVT84PDhZkGkdAKLOzcvfMedDg04AB0IDQA5rZDMDBgODiOO1UuDBAw2nL2Vupju4Iw-4cwCdzrZPjRdFAAIwPH6_HT6Ixg3SPTTPEhRRizSa_KT_AgHY6nC42dEETFQmE4qBuebPeCvd4cJHfKl4glAomgyzg1SUnF1BqoepkVqw6mkDGILFi3EAwkgkmSkCzFR8p5itmA4HEgV4GwAGky2VyBScJWeBm0VHAcl1UAAZPajV0ClBlJC0GbfBEottgEA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.38&envVersion=7.0.0-beta.38)

**Expected behavior/code**
If I uncomment the inner `finally` everything works as expected.
[See repl](https://babeljs.io/repl#?babili=false&browsers=IE%2011&build=&builtIns=false&spec=false&loose=false&code_lz=FAGwpgLgBAxghiEUC8UAMBuYcDOBPAOxigDMBXIiASwHsDYEQAjOGAawAoBKKAb2CiCoAamHxEWIVCokoHcUgA8UAEw9-UqRAAWAJxoB3KATBGAorv26OAIjCWbXSUIC-AoQpTosb7PiKkFDDUdFAAtnBUBNx87oLg0LqQunjO8ZBQcBAQYGEADtComHFQACY0sZpQAJBJECleJAg4YGmaolk5-RBtUglQSThkID0lWg0aVZr1eJVT84PDhZkGkdAKLOzcvfMedDg04AB0IDQA5rZDMDBgODiOO1UuDBAw2nL2Vupju4Iw-4cwCdzrZPjRdFAAIwPH6_HT6Ixg3SPTQuAD0ACpSFFGLNJr8pP8CAdjqcLjYSDjELNoU5YaiMWj6c94K93hwkd8CbAAaSQXZLODVDDuXUGqh6mRWszsQRcXNfkSSUCybZKXLqcK6fM3PMlYDgeSxXgbAAaTLZXIFbWuKAGbRUcByY1QABkrotXQKUGUkLQdN8ESi22AQA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.38&envVersion=7.0.0-beta.38)

**Comment by ulrichb** [comment]
@mgroenhoff Is the `this._invoke()` in `defineIteratorMethods()` involved in this endless loop?

I'm also seeing an endless loop here (but only in the MS Edge browser, not in Chrome/Fx)...

**Comment by mgroenhoff** [comment]
@ulrichb I'm sorry but I don't see any references to `this._invoke()` or `defineIteratorMethods()` in my code or the generated code. Can you try to explain why you brought those up?

**Comment by ulrichb** [comment]
@mgroenhoff Sry. Forget my comment. I had an endless iterator (just affecting MS Edge).

**Comment by OFRBG** [comment]
I'm using a library that uses `finally` blocks to handle cleanups inside async functions. Is there any way to clean this up at a higher level instead of modifying the libraries?

**Comment by nicolo-ribaudo** [comment]
@babel-bot Move to facebook/regenerator
