### ISSUE TITLE
Object destructuring error?

### ISSUE THREAD

**Issue by gsklee** [babel/babel#902]
```javascript
var o = {
  test() {
  }
};

const {constructor} = o;

console.log(constructor);
```
Currently returns `function Object() { [native code] }`, but should be `undefined`.

**Comment by sebmck** [comment]
There's no ES7 object spread happening here?

**Comment by sebmck** [comment]
Also that's expected behaviour. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor).

**Comment by gsklee** [comment]
Oops, I see, thanks.
