### ISSUE TITLE
function scope related

### ISSUE THREAD

**Issue by flyinglove** [babel/babel#9023]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
i was learning es6 using babel, and i had this code
```js
var x = 1

function foo(x, y = function() {x = 2}) {
	var x = 3
	y()
	console.log(x)
}
foo() // 3
console.log(x) 1
```

but when i babel it , i got this:

```js
"use strict";

var x = 1;

function foo(x) {
	var y = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : function () {
		x = 2;
	};

	var x = 3;
	y();
	console.log(x);
}
foo(); //2
console.log(x); //1
```
as you can see, the log in foo function is different, and i tried the babel in the [official website](https://babel.docschina.org/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAHhC8EEYBQSBmBXAdgYwC4EsB7TCVQwgCigBoIBPOUrPIzCgSggG8Z4AmAL6cuSAJChIvCAGYxdDmOzEAzoQA2AUwB0awgHMq7JALTkFSzKs079hoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-0%2Cstage-2%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2), from which i got the same problem

**Comment by nicolo-ribaudo** [comment]
Thank you for the big report; we are already tracking it at https://github.com/babel/babel/issues/2471
