### ISSUE TITLE
about babel-plugin's path & state

### ISSUE THREAD

**Issue by Lyd9607** [babel/babel#9024]
How do I know what parameters path and state of Babel plugin have?

**Comment by nicolo-ribaudo** [comment]
You can find some info at https://github.com/jamiebuilds/babel-handbook, but I suggest reading `@babel/traverse` source code.

**Comment by hzoo** [comment]
Thanks for the question. You can also console.log the visitor when testing like in https://astexplorer.net/#/gist/76245abb554673a79071ee13242b2e77/73b900ad2fdf6a16d631cb60d162fb302599c763
