### ISSUE TITLE
How can i resolve this error in @babel/runtime/core-js/map + material-ui/styles/withStyles.js?

### ISSUE THREAD

**Issue by hamedhossani** [babel/babel#9026]
I'm getting the following error while tried to ```webpack``` the application in windows 10 x64 b.

```
ERROR in ./node_modules/material-ui/styles/withStyles.js
Module not found: Error: Can't resolve '@babel/runtime/core-js/map'
```

I searched on the ```github``` and ```stackoverflow``` but don't find proper answer.

my Material UI is ```"^1.0.0-beta.47"```,. and ```@babel/runtime": "^7.1.5"```.

I  try that solutions
```
. 1-npm install @babel/runtime
  2-npm install @material-ui/core 
```
but I also have the error. How can i resolve this?

**Comment by sanzhardanybayev** [comment]
@hamedhossani I got the same issue. Can't solve for now.

**Comment by loganfsmyth** [comment]
The `material-ui` beta package is deprecated and buggy, hence the issue here. You should change to a stable version of `@material-ui/core`.

**Comment by sanzhardanybayev** [comment]
@loganfsmyth Yeah! I switched to @material-ui/core entirely. It solves the problem.

**Comment by hamedhossani** [comment]
> @loganfsmyth Yeah! I switched to @material-ui/core entirely. It solves the problem.

which version?

**Comment by chmbila202** [comment]
> @loganfsmyth Yeah! I switched to @material-ui/core entirely. It solves the problem.

how bro ?

**Comment by luisgurmendezMLabs** [comment]
@chmbila202 make sure to import from '@material-ui/core' and not from 'material-ui'

**Comment by mikepc** [comment]
Sorry but we have a codebase that is using an older version, retrofitting is just not an option right now.  What is a reasonable solution for     "material-ui": "1.0.0-beta.47" ? 

@material-ui/core has significant api differences that will impact the entire app.

**Comment by nicolo-ribaudo** [comment]
@mikepc If you are using yarn you can use [`resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to install an old enough beta of `material-ui`'s `@babel/runtime` dependency which still includes `core-js`.

**Comment by trusktr** [comment]
I don't understand this error. As you can clearly see in my screenshot, the error is coming from `animation-loop` (on the right), and on the left you can clearly see that the `array/from` file exists.

<img width="1627" alt="Screen Shot 2019-07-09 at 3 15 59 PM" src="https://user-images.githubusercontent.com/297678/60926807-91e67000-a25c-11e9-83fa-094d0ad84e04.png">

I'm using Webpack to build a bundle. Any idea why it complains that it can't find array/from when it is clearly right there?

**Comment by nicolo-ribaudo** [comment]
What's your webpack config?

**Comment by trusktr** [comment]
@nicolo-ribaudo My config is fairly simple:

<details> <summary>webpack.config.js</summary>

```js
const {DefinePlugin} = require('webpack')
const Path = require('path')
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')
// const CopyPlugin = require('copy-webpack-plugin')
const packageJson = require('../../package.json')

const baseDir = Path.resolve(__dirname, '..', '..')
const srcRootDir = Path.resolve(baseDir, 'src')
const isDev = process.env.NODE_ENV !== 'production'
const isProd = !isDev

const distDir = `${baseDir}/dist/`

module.exports = {
  cache: true,
  context: srcRootDir,

  entry: {
    saffron: './annotator/saffronEntry',
    renderer: './annotator/entry',
  },

  output: {
    path: `${distDir}/package`,
    filename: 'bundle-[name].js',
    // this is important, it means that externals will be imported by the output
    // bundle using `require()` calls (useful in Node or Electron)
    libraryTarget: 'commonjs2',
  },

  module: {
    rules: [
      // SOURCE MAPS
      {
        test: /\.js$/,
        exclude: /(typelogger|async-file|node_modules)/,
        use: ['source-map-loader'],
        enforce: 'pre',
      },

      // CSS / SCSS
      {
        test: /\.(scss|css)$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {},
          },
        ],
      },

      // YAML
      {
        test: /\.(yaml|yml)$/,
        use: ['json-loader', 'yaml-loader'],
      },

      // TYPESCRIPT
      {
        test: /\.tsx?$/,
        exclude: [/node_modules/],
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
          //experimentalWatchApi: true,
        },
      },

      // JADE
      {
        test: /\.(jade|pug)$/,
        use: ['pug-loader'],
      },

      // ASSETS
      {
        test: /\.(eot|svg|ttf|woff|woff2|png|jpg|gif|ico)\w*/,
        use: [
          {
            loader: 'url-loader',
            options: {
              // include assets smaller than this inside the bundle as data URLs
              limit: Infinity,
            },
          },
        ],
      },
    ],
  },

  resolve: {
    modules: [Path.join(baseDir, 'src'), Path.join(baseDir, 'node_modules')],
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
  },

  plugins: [
    new DefinePlugin({
      'process.env.WEBPACK': true,
      'process.env.isDev': isDev,
      'process.env.APP_VERSION': JSON.stringify(packageJson.version),
      'process.env.APP_NAME': JSON.stringify(packageJson.appName),
      'process.env.APP_DESCRIPTION': JSON.stringify(packageJson.description),
    }),

    // new CopyPlugin([{from: '**/*', to: 'src/'}, {from: '../tsconfig.json', to: 'src/'}]),
  ].concat(
    isProd
      ? []
      : [
          // with the current size of project, its faster without this plugin.
          new ForkTsCheckerWebpackPlugin({
            tsconfig: Path.resolve(baseDir, 'tsconfig.json'),
          }),
        ]
  ),

  /**
   * Node Shims
   */
  node: {
    __dirname: false,
    __filename: true,
    global: true,
    process: true,
    console: true,
  },

  // externals are not bundled, the bundle imports these with `require()`
  // calls.
  externals: [
    // supplied by Node
    'electron',
    'source-map-support',
    'require-context',

    // supplied by Saffron
    'react',
    '@mapperai/mapper-saffron-sdk',
  ],

  devServer: {
    contentBase: Path.join(baseDir, 'dist'),
    host: '0.0.0.0',
    port: 5000,
    hot: true,
  },

  devtool: isDev ? 'source-map' : 'source-map',

  stats: {
    assets: false, // shows all output assets
  },

  optimization: {
    minimize: isDev ? false : true,
  },
}
```

</details>

Thanks for taking a look!

**Comment by nicolo-ribaudo** [comment]
Oh ok, so that is an already transpiles module. I suggest reporting this error to webpack: since Babel doesn't run during your build process, there is nothing we can do ☹️

**Comment by trusktr** [comment]
Hmm, yeah, seems like Webpack is not resolving modules as expected.

**Comment by loganfsmyth** [comment]
```
modules: [Path.join(baseDir, 'src'), Path.join(baseDir, 'node_modules')],
```
explicitly overrides Node's default resolution, which is breaking this. If you had
```
modules: [Path.join(baseDir, 'src'), 'node_modules'],
```
it would work fine.

**Comment by trusktr** [comment]
Oh, I see! It is because `Path.join(baseDir, 'node_modules')` creates an absolute path (`baseDir` is absolute), and because of this Webpack won't use the regular search algo on absolute paths as mentioned in the [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolvemodules) doc:

> A relative path will be scanned similarly to how Node scans for node_modules, by looking through the current directory as well as its ancestors (i.e. ./node_modules, ../node_modules, and on).
> 
> **With an absolute path, it will only search in the given directory.**
