### ISSUE TITLE
Latest version of @babel/standalone doesn't work with imports

### ISSUE THREAD

**Issue by voronianski** [babel/babel#9027]
## Bug Report

**Current Behavior**
I've tried to upgrade my project to `@babel/standalone` v7.1.0 from `babel-standalone` v6.26.0. 
Unfortunately latest version doesn't work with `import` statements. But they work fine in v6.26.0.

**Input Code**

```js
import React from 'react';

console.log("react", React);
```

**Transpiled versions**

### `@babel/standalone` v7.1.0
```js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

var _react = _interopRequireDefault(require("react"));

console.log("react", _react.default);
```

### `babel-standalone` v6.26.0
```js
"use strict";

var _react = require("react");

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log("react", _react2.default);
```

Any ideas why `@babel/standalone` requires helpers instead of inlining them?

**Comment by loganfsmyth** [comment]
What's the issue with not inlining the helper here? They should behave the same.

**Comment by damianobarbati** [comment]
@voronianski did you manage to solve this? I have a similar issue: @babel/cli is not inlining imports and all of them are undefined

**Comment by nicolo-ribaudo** [comment]
Can someone of you post here the Babel configuration?

**Comment by voronianski** [comment]
@damianobarbati you issue is not related to this one and babel-standalone at all...

@loganfsmyth my concern was that https://wzrd.in could not properly resolve deep requires and it didn't work for me. But it's solved now. Also I thought that it could be simpler to have it inlined.
