### ISSUE TITLE
Nested configs are not properly cleared when merging presets and options into the final config

### ISSUE THREAD

**Issue by franjohn21** [babel/babel#9031]
### Current Behavior
When using the [OptionManager](https://github.com/babel/babel/blob/eac4c5bc17133c2857f2c94c1a6a8643e3b547a7/packages/babel-core/src/index.js#L47) from `@babel/core`, the same plugin is attached twice if the plugin is defined in a preset that is using the `env` option.

[@babel/register uses the OptionManager](https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L41) so In practice this fails hard for example when using `@babel/register` with a plugin that does not handle visiting the same node twice gracefully (in my case I ran into this with `babel-plugin-dynamic-import-node`). 

### Expected behavior/code
This [code sandbox](https://codesandbox.io/s/2plq3kjl70) loads a custom babel plugin that will append `Visited` to any identifers. The code we are loading is simple and only defines one variable so `Visited` should only be attached once.

**Input code**
```
const foo = 'bar'
```

**Code produced by passing in babel options directly: ✅**
```
const fooVisited = 'bar';
```

**Code produced by passing in babel options through babel.OptionManager(): ❌**
```
const fooVisitedVisited = 'bar';
```
[![Edit 2plq3kjl70](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2plq3kjl70)

### Babel Configuration (.babelrc, package.json, cli command)
```js
// .babelrc.js
const preset = {
  env: {
     foo: {
       plugins: ['babel-plugin-foo']
     }
  }
}

module.exports = {
  presets: [preset]
}
```

### Environment
- Babel version(s): ^7.0.0
- Node/npm version: Node 8/npm 5
- OS: 10.13.5
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: Programatically via @babel/core and via @babel/register

### Possible Solution
Plugins should _probably_ be able to handle gracefully visiting the same Node twice. I will make a PR to `babel-plugin-dynamic-import-node` to do so, but babel should also not be attaching the same plugin multiple times.

**Comment by loganfsmyth** [comment]
Thanks so much for the thorough reproduction case. Definitely a bug!

**Comment by loganfsmyth** [comment]
I've posted a fix, but in the short term if your preset doesn't need Babel 6 support, you can tweak your preset to use `api.env` to avoid the nested `env` block:
```
const preset = api => {
  return {
    plugins: [
      api.env('foo') ? 'babel-plugin-foo' : null,
    ].filter(Boolean),
  };
};
```
