### ISSUE TITLE
@babel/register does not always use sibling .babelrc config

### ISSUE THREAD

**Issue by ianstormtaylor** [babel/babel#9033]
## Bug Report

**Current Behavior**

If you require `@babel/register` in a file that has its sibling `.babelrc` file, everything works as expected if you run it from inside the package. But if you run the same file from one directory up, it no longer works.

This seems like a bug, because from what I can tell in the docs `.babelrc` isn't supposed to care about the current working directory—it is supposed to be file-relative, and search for up the tree until it reaches a `package.json` boundary.

**Input Code**

If you have a directory structure like:

```
example/
  .babelrc
  app.js
  index.js
  package.json
```

And `index.js` is an entrypoint for using `@babel/register`, like:

```js
// index.js
require('@babel/register')
require('./app')
```

And `app.js` is the file to be compiled:

```js
// app.js
export default 42
```

And you run it with...

```bash
/example   $ node ./index.js
```

...it works fine. But if you move one directory higher and then run it...

```bash
cd ..
/          $ node ./example/index.js
```

...then you get an error:

```
/example/app.js:1
(function (exports, require, module, __filename, __dirname) { export default 42;
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Module._compile (/example/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/example/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Expected behavior/code**

This doesn't seem right. I thought `.babelrc` was supposed to be file-relative.

I think this bug is leading to some of the confusing behaviors in other issues:

- https://github.com/babel/babel/issues/8424
- https://github.com/babel/babel/issues/8458
- https://github.com/babel/babel/issues/7566
- https://github.com/babel/babel/issues/8802
- https://github.com/babel/babel/issues/7701

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    "@babel/plugin-transform-modules-commonjs"
  ]
}
```

**Environment**
- Babel version(s): 7.x
- Node/npm version: 10.x
- OS: OSX
- Monorepo: no
- How you are using Babel: register

**Comment by loganfsmyth** [comment]
> This doesn't seem right. I thought .babelrc was supposed to be file-relative.

It is file-relative, but we only search for it if the file being compiled is in the "root" package by default. When you run from outside of the `example` directory, you're running with a different default `root` value. If `example/` is logically the root of your application, but you want to run things with an arbitrary working directory, you can always do

```
require('@babel/register')({
  cwd: __dirname
});
```
to set a specific working directory for Babel. In this case,
```
require('@babel/register')({
  root: __dirname
});
```
would also work.

**Comment by ianstormtaylor** [comment]
Hey @loganfsmyth, thanks for the quick response!

That doesn't work for me though.

---

(I was writing this up before you responded...)

Further, doing some investigating to see what a workaround is (even though this seems like a bug that should be fixed to me), it's hard to find a solution. None of these things work...

**Renaming to `babel.config.js`**

Renaming the `.babelrc` to `babel.config.js`, like...

```js
// babel.config.js
module.exports = {
  plugins: [
    '@babel/plugin-transform-modules-commonjs'
  ]
}
``` 

...doesn't work.

**Passing the `cwd` option**

Changing the `@babel/register` call to pass in the `cwd` option, like...

```js
// index.js
require('@babel/register', { cwd: __dirname })
require('./app')
```

...doesn't work either.

**Passing the `root` option**

Changing the `@babel/register` call to pass in the `root` option, like...

```js
// index.js
require('@babel/register', { root: __dirname })
require('./app')
```

...doesn't work either.

**Passing the `ignore` option**

Changing the `@babel/register` call to pass in the `ignore` option, like...

```js
// index.js
require('@babel/register', { ignore: [] })
require('./app')
```

...doesn't work either—although I didn't think this would.

**Using the `node -r` flag**

Removing the `./app` reference from the `index.js` entrypoint and then running the program with the `node -r` flag instead from above, like...

```js
// index.js
require('@babel/register')
```
```bash
cd ..
/          $ node -r ./example.index ./example/app.js
```

...doesn't work either.

**Using `@babel/node`**

Running from above with `@babel/node` instead, like...

```bash
cd ..
/          $ babel-node ./example/app.js
```

...doesn't work.

**Comment by loganfsmyth** [comment]
```
require('@babel/register', { root: __dirname })
```
isn't quite the right syntax. You're passing those options to `require`, where you should be passing them to the function returned by `require`.
```
require('@babel/register')({ root: __dirname })
```

**Comment by ianstormtaylor** [comment]
@loganfsmyth oh my god, thank you. Wow, can't believe I didn't catch that. Thank you!
