### ISSUE TITLE
Object estructuring assignment on import

### ISSUE THREAD

**Issue by traBolic** [babel/babel#9040]
## Bug Report

**Current Behavior**
I've updated my project dependency versions to "@babel/core": "^7.1.6", "@babel/preset-env": "^7.1.6", "@babel/plugin-transform-runtime": "^7.1.0"
Because I need to use async/await in my project and the ways I tried, lead me to version upgrade.
But after upgrading, the object destructuring assignment is not working properly when I use it on an import

**Input Code**
- **index1.js**
```js
const ListOfObjects = {
	a: 10
}
export default ListOfObjects
```

- **test.js**
```js
import { obj1 } from "./index1";

let obj2 = {
	b: 20
}

let { a } = obj1;
let { b } = obj2;

console.log(a); // undefined
console.log(b); // 20
```

**Expected behavior/code**
I expected to the a variable contains "10" normally.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
	presets: [
		'@babel/preset-env',
		{
			plugins: [
				'@babel/plugin-transform-runtime'
			]
		}
	]
}
```

**Environment**
- Babel version(s): 7.1.6
- Node/npm version: Node 10.13.0/npm 6.4.1
- OS: Ubuntu 18.04.1 LTS
- Monorepo: no
- How you are using Babel: inside the gulp file with transforming with babelify, register

**Additional context/Screenshots**
In other way that I use this, here
![image](https://user-images.githubusercontent.com/5789670/48684062-18ace680-ebc1-11e8-9b0e-9cd3d0e27623.png)
![image](https://user-images.githubusercontent.com/5789670/48684026-dd121c80-ebc0-11e8-9d98-b4e5e367215b.png)
![image](https://user-images.githubusercontent.com/5789670/48684053-092d9d80-ebc1-11e8-918c-669f44fb3616.png)

**Comment by loganfsmyth** [comment]
This isn't quite how imports and exports fit together.

```
export default ListOfObjects
```
exports an export named "default" that contains an object.
```
import { obj1 } from "./index1";
```
imports an export named "obj1", which does not exist since you only exported "default", which is why you don't get `10`.

You should either export `obj1` as a named export, e.g.
```
export const obj1 = 10;
```
or else import the default object and get the property from that:
```
import ListOfObjects from "./index1";
const { obj1 } = ListOfObjects;
```

**Comment by loganfsmyth** [comment]
The core thing is that imports are not destructuring. When you `import { Auth } from` you are importing the export `Auth`, not reading the `Auth` property from the default export.

**Comment by traBolic** [comment]
I'm exporting the object that contains Auth property. Normally, isn't it worked as it expected?
I mean if I do this, it works fine. But I believe this issue is not supposed to happen

![image](https://user-images.githubusercontent.com/5789670/48685457-7f350300-ebc7-11e8-9c2f-b93a0e0306b6.png)

**Comment by loganfsmyth** [comment]
```
import ActionsOfServer from "";
let { Auth } = ActionsOfServer;
```
and
```
import { Auth } from "";
```
are not equivalent.

The first example imports the `default` export and reads a property from it, whereas the second one imports an export named `Auth`.
