### ISSUE TITLE
Babel config is not used for files without .js suffix

### ISSUE THREAD

**Issue by ivan-kleshnin** [babel/babel#9041]
## Bug Report

**Current Behavior**

I have a `run` file which serves as a command dispatcher:

```
./run doX
./run doY
```

I use it instead of `package.json` scripts (for reasons I don't want to describe here).
This scheme served me well until Babel-7.

**The Problem**

`babel.config.js` file is ignored when the executable (file) name has no `.js` suffix.
It doesn't matter which config I use, `babel.config.js` file is loaded ONLY when the file is named
`run.js` (or whatever with `.js` suffix). For `run` file it fallbacks to default babel configs. 

Once again, when I rename file and do:

```
./run.js doX
./run.js doY
```

everything's fine, ES6 imports are transpiled, etc. 

**Environment**
- Babel version(s): [7.1.6]
- Node/npm version: [10.4.1]

**Comment by nicolo-ribaudo** [comment]
Sorry for the long delay in responding to this issue. Did you already solve it?

If not, we need a lot more information to understand what is the problem:
- What are the contents or the `run` file?
- How are you calling Babel?
- Is the file which need to be transpiled run.js, or another file?
