### ISSUE TITLE
Babel is stuck doing networking? 

### ISSUE THREAD

**Issue by pronebird** [babel/babel#9042]
## Bug Report

**Current Behavior**

When connection a VPN tunnel and running `babel` at the same time, I see that `babel` simply does not proceed converting ES6 files, until it gets access to network. 

I am too lazy to run a little snitch at this point, but I don't believe in coincidence and I can reliably reproduce the issue:

```
$ cross-env yarn run private:compile --source-maps true && run-p -r private:watch private:serve
$ babel src/ --copy-files --out-dir build --extensions ".ts,.tsx,.js" --source-maps true
Successfully compiled 76 files with Babel.
$ cross-env yarn run private:compile --source-maps true --watch --skip-initial-build
$ cross-env babel-node scripts/serve.js
$ babel src/ --copy-files --out-dir build --extensions ".ts,.tsx,.js" --source-maps true --watch --skip-initial-build
... STUCK ...
```

It hangs for about 30 seconds maybe then it continues the execution. Anyone knows what's up?

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { "electron": "3.0" }
    }],
    "@babel/preset-react",
    "@babel/preset-typescript",
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

**Environment**
- Babel version(s): v7.1.x
- Node/npm version: [e.g. Node 8/npm 5] Node 10.13
- OS: macOS 10.14
- Monorepo [e.g. yes/no/Lerna] yes
- How you are using Babel: [e.g. `cli`, `register`, `loader`] cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
Babel doesn't make any network request :thinking:

**Comment by pronebird** [comment]
@nicolo-ribaudo maybe `watch` is being stuck because of firewall or something. I'll try with `DEBUG=*` maybe to find where exactly it's being stuck.

**Comment by xtuc** [comment]
Since Babel doesn't use the network at all, that's likely unreleated.
