### ISSUE TITLE
Update facebook/regenerator dependency used by babel-polyfill and babel-runtime packages

### ISSUE THREAD

**Issue by sashapwc** [babel/babel#9043]
## Bug Report

**Current Behavior**
If a Content Security Policy header is present to prevent unsafe-eval, and the website uses a library that was compiled via Babel and uses babel plugins which use a version of facebook/regenerator <+ 0.12.0, the browser will refuse to execute the library.

**Possible Solution**
The versions of facebook/regenerator listed in [Babel's yarn.lock](https://github.com/babel/babel/blob/master/yarn.lock) are prior to the bug fix for https://github.com/facebook/regenerator/issues/336 which was released in 0.12.1 of that library. So an update of this library is necessary to fix the issue.

**Comment by nicolo-ribaudo** [comment]
This has been updated to the lastest version in Babel 7.4.
