### ISSUE TITLE
Updated regenerator-runtime breaks babel-polyfill

### ISSUE THREAD

**Issue by jsg2021** [babel/babel#9044]
## Bug Report

The `regenerator-runtime` package no longer assigns `regeneratorRuntime` to global when imported by module. The current polyfill code just imports it expecting it to create `regeneratorRuntime`, when it does not... 

this is now required:
```
global.regeneratorRuntime = require('regenerator-runtime')
```

**Comment by loganfsmyth** [comment]
I'm not sure I understand. The polyfill depends on `0.12` which does create the global.

**Comment by jsg2021** [comment]
oh, we must be getting a hoisted version then. :|

**Comment by Hypnosphi** [comment]
Same problem with `useBuiltIns: usage` in preset-env. Should I create a separate issue?

**Comment by Hypnosphi** [comment]
One possible solution is to generate something like that:

```
import regeneratorRuntime from 'regenerator-runtime`

// of course, it should `global` or `self` instead of `window` in corresponding environments
window.regeneratorRuntime = regeneratorRuntime
```

**Comment by psi-4ward** [comment]
some problem here. I include some (rollup) libs which depends on the global regeneratorRuntime
`window.regeneratorRuntime = regeneratorRuntime` does not work for me cause the lib get's loaded before the index.js

**Comment by loganfsmyth** [comment]
@psi-4ward I'd file that as a bug on the library.

**Comment by Hypnosphi** [comment]
@loganfsmyth what if this "library" is called "@babel/preset-env"?

**Comment by loganfsmyth** [comment]
@Hypnosphi I'm not sure what you mean by that. The issue is with the planned usage of code output by Babel. If you're using something as a library, you don't want a library injecting stuff into the global scope, so `usage` is a bad idea. If you're an application, injecting globals is fine. I'd recommend filing a new issue with a clear example so we can continue this discussion in a more targeted sense.

**Comment by BartJanvanAssen** [comment]
> One possible solution is to generate something like that:
> 
> ```
> import regeneratorRuntime from 'regenerator-runtime`
> 
> // of course, it should `global` or `self` instead of `window` in corresponding environments
> window.regeneratorRuntime = regeneratorRuntime
> ```
> This should be compatible with both 0.12 and 0.13

You made my day. this fixed like 2 days of debugging...
