### ISSUE TITLE
vscode breakpoints don't work

### ISSUE THREAD

**Issue by luke93h** [babel/babel#9045]
I'm developing a babel-plugin. I set breakpoints in vscode using dubuggin tool of vscode.
But the breakpoints don't work.Can some one help me out.
Here's the repo of my example: [https://github.com/luke93h/babel-plugin-test](https://github.com/luke93h/babel-plugin-test)

**Comment by suchipi** [comment]
Hi @luke93h,

Please see instructions for debugging node applications in VSCode here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature

If you toggle Auto-Attach and then launch the script from VSCode's integrated terminal using `node --inspect ./my-script.js` or `node --inspect-brk ./my-script.js`, then vscode should automatically attach to the node process and stop at your breakpoint.

**Comment by luke93h** [comment]
> Hi @luke93h,
> 
> Please see instructions for debugging node applications in VSCode here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature
> 
> If you toggle Auto-Attach and then launch the script from VSCode's integrated terminal using `node --inspect ./my-script.js` or `node --inspect-brk ./my-script.js`, then vscode should automatically attach to the node process and stop at your breakpoint.

thank you very much！
