### ISSUE TITLE
@babel/preset-env incorrectly add too many plugins with Node.js target

### ISSUE THREAD

**Issue by ehmicky** [babel/babel#9047]
## Bug Report

**Current Behavior**
When targeting the latest Node.js version (`11.2.0`), `@babel/preset-env` adds the following plugins: 

```
@babel/preset-env: `DEBUG` option

Using targets:
{
  "node": "11"
}

Using modules transform: auto

Using plugins:
  proposal-async-generator-functions { "node":"11" }
  syntax-object-rest-spread { "node":"11" }
  proposal-unicode-property-regex { "node":"11" }
  proposal-json-strings { "node":"11" }
  proposal-optional-catch-binding { "node":"11" }

Using polyfills with `usage` option:

[myfile.js] Based on your code and targets, none were added.
"use strict";
```

**Input Code**

```js
// empty file
```

**Expected behavior/code**
All those plugins are not needed with Node.js `11.2.0` which already supports those.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  plugins: [
    "@babel/plugin-transform-runtime",
  ],
  presets: [
    ["@babel/preset-env", {
      targets: {
        node: "11"
      },
      useBuiltIns: 'usage',
      debug: true,
    }]
  ]
}
```

**Environment**
- Babel version(s): `6.23.0`
- Node/npm version: Node `11.2.0`, npm `6.4.1`
- OS: Ubuntu `18.10`
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**
This seems to be an issue with `compat-table` data. I've opened an issue [here](https://github.com/kangax/compat-table/issues/1374)

**Comment by existentialism** [comment]
@ehmicky published #9048 for this (we've been waiting for compat-table to get node10+ support so that we could update our mappings)

**Comment by ehmicky** [comment]
Great, thanks for this very fast PR!

I note the following:
  - `proposal-json-strings` should be the only transform needed for Node.js `11`
  - `syntax-object-rest-spread` is not needed. I am not sure how it actually gets added there, but hopefully this PR will fix it as well.

**Comment by existentialism** [comment]
@ehmicky syntax-object-rest-spread is needed to enable parsing in babel, _not_ for transforming.
