### ISSUE TITLE
I can't use this in React Naive

### ISSUE THREAD

**Issue by ShininingLancer** [babel/babel#9052]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Slack Community Chat: https://babeljs.slack.com (you can sign-up at https://slack.babeljs.io/ for an invite)
* StackOverflow: https://stackoverflow.com/questions/tagged/babeljs using the tag `babeljs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/babeljs
* Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by ShininingLancer** [comment]
I am trying to use it in react native. but I couldn't. I created the project using react-native-cli.

**Comment by existentialism** [comment]
@ShininingLancer when you say you can't use it, could you provide more information? Is there an error? Can you provide a small repo that shows the problem?

**Comment by ShininingLancer** [comment]
I just create new project using react-native-cli and
install the package.
my .babelrc is as follows:

{
  "presets": [
    "module:metro-react-native-babel-preset"
  ],
  "plugins": [
      "@babel/plugin-syntax-dynamic-import"
  ]
}

but when i try to import(`${variable}`), I am getting errors.

**Comment by Slapbox** [comment]
@ShininingLancer how can the maintainers possibly help if you don't take the time to include even the error text?

**Comment by nicolo-ribaudo** [comment]
@ShininingLancer I'm closing this issue as we don't have enough information. If you can post your error message I'll reopen the issue.
