### ISSUE TITLE
regenerator-runtime dependence version

### ISSUE THREAD

**Issue by AMDvsTMD** [babel/babel#9053]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
the verison of regenerator-runtime  when install by npm is ^0.11.1 should be ^0.12.1

**Expected behavior/code**
the verison of regenerator-runtime when install by npm should be as project package.json to be  ^0.12.1

**Environment**
- Babel version(s): [e.g. v6.26.0]
- Node/npm version: [Node 8/npm 5]
- OS: [Windows 10]
- How you are using Babel: `loader`]

**Comment by AMDvsTMD** [comment]
when install from npm the package.json is 
{
  "_from": "@babel/polyfill",
  "_id": "@babel/polyfill@7.0.0",
  "_inBundle": false,
  "_integrity": "sha512-dnrMRkyyr74CRelJwvgnnSUDh2ge2NCTyHVwpOdvRMHtJUyxLtMAfhBN3s64pY41zdw0kgiLPh6S20eb1NcX6Q==",
  "_location": "/@babel/polyfill",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "@babel/polyfill",
    "name": "@babel/polyfill",
    "escapedName": "@babel%2fpolyfill",
    "scope": "@babel",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@babel/polyfill/-/polyfill-7.0.0.tgz",
  "_shasum": "c8ff65c9ec3be6a1ba10113ebd40e8750fb90bff",
  "_spec": "@babel/polyfill",
  "_where": "D:\\test",
  "author": {
    "name": "Sebastian McKenzie",
    "email": "sebmck@gmail.com"
  },
  "bundleDependencies": false,
  "dependencies": {
    "core-js": "^2.5.7",
    "regenerator-runtime": "^0.11.1"
  },
  "deprecated": false,
  "description": "Provides polyfills necessary for a full ES2015+ environment",
  "homepage": "https://babeljs.io/",
  "license": "MIT",
  "main": "lib/index.js",
  "name": "@babel/polyfill",
  "repository": {
    "type": "git",
    "url": "https://github.com/babel/babel/tree/master/packages/babel-polyfill"
  },
  "version": "7.0.0"
}

**Comment by nicolo-ribaudo** [comment]
For some reason https://github.com/babel/babel/commit/679e4b8f3791d17f465318dc1010ca6642f8c2cf has not been published. It will be fixed in the next release.

**Comment by wmertens** [comment]
This is present 7.3.1 it seems

**Comment by nicolo-ribaudo** [comment]
This has been fixed in 7.2.5: https://unpkg.com/@babel/polyfill@7.2.5/package.json
