### ISSUE TITLE
babel 7 ecmascript 7 configuration

### ISSUE THREAD

**Issue by m-korkut** [babel/babel#9054]
how use babel 7 version into ecmascript 7 configuration  ?

example my ->  .babelrc --> 
```json
{
"plugins":[
   //.....
               ],
  "presets": [
     "@babel/env",
     "@babel/flow",
    "@babel/preset-react"
                    ]
 }
```

**Comment by nicolo-ribaudo** [comment]
If by "ECMAScript 7 configuration" you mean that you want to transform ECMAScript 7 (2016) to ECMAScript 5, your configuration is already ok.

**Comment by xtuc** [comment]
This reminds me about https://github.com/babel/babel/issues/6613, it would be usefull for this kind of use-cases.

**Comment by nicolo-ribaudo** [comment]
Closing as a duplicate of #6613. Targeting a specific ECMAScript version isn't supported yet.
