### ISSUE TITLE
Unexpected yield expression transform

### ISSUE THREAD

**Issue by Banou26** [babel/babel#9063]
## Bug Report

**Current Behavior**
Not able to make a yield an expression

**Input Code**
```js
(async function * () {
  await (yield)
})
```
is transformed into
```js
(async function* () {
  await yield
})
```
which results in an ``SyntaxError: Unexpected strict mode reserved word``

**Expected behavior/code**
Yield should stay in between the parenthesis to be an expression

**Environment**
- Babel version(s): [v7.0.0]

**Comment by nicolo-ribaudo** [comment]
If anyone wants to work on this issue, you should take a look at https://github.com/babel/babel/blob/d2971a1959775d86cbf954bc4b22ee4a6595c6a8/packages/babel-generator/src/node/parentheses.js#L162-L172

**Comment by phapp88** [comment]
I'd like to work on this as my first contribution to babel.

**Comment by nicolo-ribaudo** [comment]
Go for it!
