### ISSUE TITLE
Babel-parser doesn't support TSIndexedAccessType

### ISSUE THREAD

**Issue by smashercosmo** [babel/babel#9065]
## Bug Report

**Current Behavior**
When I'm using lookup types like this
```typescript
type Hello = {
  hi: string
}

type Bla = {
  foo: Hello['hi']
}
```
I get ```Unexpected token, expected "]"``` error

**Input Code**
https://astexplorer.net/#/gist/36d15fc22465f8ef8ae505e7e57a676a/eb237abbc9b773d4b594ae9606cedf872e9e955f

**Expected behavior/code**
This syntax should be supported

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  test: /\.js$/,
  include: [APP_DIR],
  use: [
    {
      loader: 'babel-loader',
      options: {
         presets: [
           '@babel/preset-env',
           ['@babel/preset-react', { development: !optimize }],
           [
             '@babel/preset-typescript',
             {
               isTSX: true,
               allExtensions: true,
              },
           ],
         ],
         plugins: ['@babel/plugin-proposal-class-properties'],
       },
     },
   ],
 }
```

**Environment**

 - OS: macOS Sierra 10.12.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
 - Memory: 633.35 MB / 16.00 GB
 - Shell: 5.2 - /bin/zsh
 - Node: 10.12.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - ~/.yarn/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - @babel/core: 7.1.6 => 7.1.6

**Comment by nicolo-ribaudo** [comment]
You have to enable the typescript plugin: https://astexplorer.net/#/gist/feea39c5da115301dd651f829b0790b5/815408a3921ba8b67c62f7c4bfecf78b213d4a61

You are applying your config in Babel loader only to .js files. Are you using a .ts file?

**Comment by smashercosmo** [comment]
Hm... I think I did something stupid) Thx for response.
