### ISSUE TITLE
Difference between @babel/plugin-syntax-dynamic-import and babel-plugin-dynamic-import-node ?

### ISSUE THREAD

**Issue by kopax** [babel/babel#9066]
# v7

Hi and thanks for the great work in V7.
I have updated my babel configuration using `npx babel-upgrade --write` and I'd like to understand this new package added to my `package.json`:

[@babel/plugin-syntax-dynamic-import](https://babeljs.io/docs/en/next/babel-plugin-syntax-dynamic-import.html)

Does it replace `babel-plugin-dynamic-import-node` ?

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node 10
- OS: Linux Debian Stretch

Thanks in advance

**Comment by nicolo-ribaudo** [comment]
`babel-plugin-dynamic-import-node` (and `babel-plugin-dynamic-import-node-babel-7`) are two community packages used to transform `import()` to `require` calls and promises. `@babel/plugin-syntax-dynamic-import` only makes Babel parse `import()`, but it needs to be handled by something else (native implementation, webpack or rollup).

**Comment by kopax** [comment]
@nicolo-ribaudo Should I use `babel-plugin-dynamic-import-node-babel-7` for babel 7 ? It seems to be a fork. @ljharb have said on the issue tracker that 2.2.0 of `babel-plugin-dynamic-import-node` is for babel 7

**Comment by nicolo-ribaudo** [comment]
I don't know, but if it works... :+1:

**Comment by ljharb** [comment]
The -babel-7 version was a fork made while Babel 7 is in beta and the transform didn’t yet support it. There’s joe reason to use it anymore.
