### ISSUE TITLE
Decorators Stage 2: initializer element descriptor kind is not supported

### ISSUE THREAD

**Issue by buschtoens** [babel/babel#9068]
## Bug Report

**Current Behavior**

```
TypeError: An element descriptor's .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "initializer"
    at _toElementDescriptor
```

https://github.com/babel/babel/blob/d35563ee1a7c3d8a69b5bc1b87fc8d6d883f00ea/packages/babel-helpers/src/helpers.js#L1589-L1598

The code below triggers the above error. It seems that initializers are just not handled yet.

**Input Code**
[REPL](https://deploy-preview-1816--babel.netlify.com/repl#?babili=false&browsers=&build=master&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAEwKYTgCjQZwgSkQG8AoRRAJ1ShAqVPPIDoXcIAaMx1ADygoCGOAFyIA2l0bFJUxAGsYYZKIDkimLAEAbGAC9UFFZ1mMADloERUAW1RgoquAHcwRmVPWad-ipkIMTRgwwHDgtVCYtOABzTCgACxgcfABud0YAX3SsqQBdLgy0rJIICxwcRAAxODhpcgABNAwuWwS4ZD86xABIYNDwyJi4xJx2RBVW-PaVVIKSYrBUJyqalKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.1.6&envVersion=)

```js
function deco(desc) {
  return {
    ...desc,
    extras: [
      {
        kind: 'initializer',
        placement: 'own',
        initializer() {
          console.log(this);
        }
      }
    ]
  };
}

class Foo {
  @deco
  method() {}
}

new Foo;
```

**Expected behavior/code**
The initializer should be executed during class initialization and should log the class instance.

https://github.com/tc39/proposal-decorators/blob/master/METAPROGRAMMING.md#initializers

**Babel Configuration (.babelrc, package.json, cli command)**
Just the decorators. See the REPL.

**Environment**
- Babel version(s): v7.1.6

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/pull/9008
