### ISSUE TITLE
Overriding setters result in value being `undefined`

### ISSUE THREAD

**Issue by saschagehlich** [babel/babel#907]
Example:

http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=class%20Foo%20%7B%0A%20%20constructor%20()%20%7B%0A%20%20%20%20this._dirty%20%3D%20false%3B%0A%20%20%7D%0A%20%20%0A%20%20set%20dirty%20(dirty)%20%7B%0A%20%20%20%20this._dirty%20%3D%20dirty%3B%0A%20%20%7D%0A%20%20%0A%20%20get%20dirty%20()%20%7B%0A%20%20%20%20return%20this._dirty%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Bar%20extends%20Foo%20%7B%0A%20%20set%20dirty%20(dirty)%20%7B%0A%20%20%20%20super._dirty%20%3D%20dirty%3B%0A%20%20%20%20%2F%2F%20do%20something%20else%20here...%0A%20%20%7D%0A%7D%0A%0Alet%20foo%20%3D%20new%20Foo()%3B%0Afoo.dirty%20%3D%20true%3B%0Aconsole.log(foo.dirty)%3B%0A%0Alet%20bar%20%3D%20new%20Bar()%3B%0Abar.dirty%20%3D%20true%3B%0Aconsole.log(bar.dirty)%3B%0A

```js
class Foo {
  constructor () {
    this._dirty = false;
  }
  
  set dirty (dirty) {
    this._dirty = dirty;
  }
  
  get dirty () {
    return this._dirty;
  }
}

class Bar extends Foo {
  set dirty (dirty) {
    super._dirty = dirty;
  }
}

let foo = new Foo();
foo.dirty = true;
console.log(foo.dirty);

let bar = new Bar();
bar.dirty = true;
console.log(bar.dirty);
```

See the link and look at the console output. `console.log(foo.dirty);` prints `true`, but `console.log(bar.dirty);` prints `undefined` - is this the intended behavior?

**Comment by eventualbuddha** [comment]
Your `Bar` should look like this:

```js
class Bar extends Foo {
  set dirty(dirty) {
    this._dirty = dirty;
  }
}
```

It does not make sense to set a property on `super` that is not a setter and expect it to have an effect on `this`.

**Comment by sebmck** [comment]
This is expected behaviour, do as @eventualbuddha suggests.
