### ISSUE TITLE
Babel not using plugins according to target environment support

### ISSUE THREAD

**Issue by mohsinulhaq** [babel/babel#9075]
## Bug Report

**Current Behavior**
While using `@babel/env`, with my .browserslistrc saying "last 1 Chrome version", and debug mode on, the build said:

```
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "70"
}

Using modules transform: auto

Using plugins:
  syntax-async-generators { "chrome":"70" }
  syntax-object-rest-spread { "chrome":"70" }
  proposal-json-strings { "chrome":"70" }
  syntax-optional-catch-binding { "chrome":"70" }
```
Now, except propsal-json-strings (not sure how to paste that Unicode character), all other syntaxes do work in Chrome 70 natively.

**Expected behavior/code**
At least plugins for async-generators, rest-spread, and optional catch binding should not have been used if Chrome 70 is the target environment.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [['@babel/preset-env', {debug: true, useBuiltIns: "usage"}]],
  plugins: ['@babel/transform-runtime']
}
```

**Environment**
- Babel version(s): 7.1.6
- Node/npm version: Node 10/npm 6
- OS: OSX 10.14.1
- Monorepo no
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
The `syntax-*` plugins are just to enablee _parsing_ of some features in Babel, they do not transform anything.

**Comment by nicolo-ribaudo** [comment]
It is to make Babel understand your code.
