### ISSUE TITLE
Spread operator on classList only appends first element in IE11

### ISSUE THREAD

**Issue by kreiswelt** [babel/babel#9077]
## Bug Report

**Current Behavior**
Spread operator on classList only appends first element in IE11

**Input Code**
- REPL or Repo link if applicable: [sample code](https://babeljs.io/en/repl.html#?babili=false&browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=G4QwTgBAtg9gJgUwM4QLwQNoCJaILR4A2MIcAlgHYDmWANBDvAgcGQA5YC6A3AFCiQQAMwAuCMAGUAxmAQIKAGRJw0EABRk49XMgCUaAHwQA3rwCQUmBSQiIAEgSEEUVXBhSArlHkiAdFQQRAFEnbwoRACEATwBJOA04XT4IFPtHZ18pQhAkJAUyG19SeN9SnSQk3gBfXlrhMUkZOUVlNSxiKgC4PEo8JCb5OmgmCu4gA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

```js
var modes = ["mode--loading", "mode--vip"];
var afterScreenLoad = (id, modes) => {
	const $elem = document.getElementById(id);
    $elem.classList.add(...modes);
}


afterScreenLoad("logged-in-screen", modes);
```

- After transpiled to es2015, it only includes first mode, i.e. mode--loading. Sample HTML:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div id="logged-in-screen" class="screen">
            <div class="screen-wrapper">
                <span>Hello</span>
            </div>
        </div>
        <script>
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

var modes = ["mode--loading", "mode--vip"];
var afterScreenLoad = function afterScreenLoad(id, modes) {
  var _$elem$classList;

  var $elem = document.getElementById(id);
  (_$elem$classList = $elem.classList).add.apply(_$elem$classList, _toConsumableArray(modes));
};
afterScreenLoad("logged-in-screen", modes);
        </script>
    </body>
</html>
```

**Expected behavior/code**
All array elements are added correctly
May be using forEach to add one by one, instead of using apply

**Comment by loganfsmyth** [comment]
This is not an issue with Babel, but rather with IE11's `.add` function. IE11 only supports a single argument passed to `.add`, but by doing `.add(...items);` you are explicitly telling Babel to pass multiple arguments, and it is doing what you've asked. 

You'd either need to perform the loop yourself, or load a polyfill like https://www.npmjs.com/package/classlist-polyfill
