### ISSUE TITLE
Error starting server due to polyfill

### ISSUE THREAD

**Issue by Rishat7c** [babel/babel#9081]
I can not start the server, swears at the `polyfill`
Error text:

> The 'polyfill' option has been removed. The @babel/runtime module now skips polyfilling by default.

**Comment by Rishat7c** [comment]
@babel-bot @nicolo-ribaudo 
Configuration of my `.babelrc`

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "9"
        }
      }
    ]
  ],
  "plugins": [
    "import-graphql",
    [
      "@babel/plugin-transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ]
  ]
}
```

**Comment by nicolo-ribaudo** [comment]
The `polyfill` option has been removed and is now false by default. You should remove it from your configuration.
