### ISSUE TITLE
Assignment in custom object literal key ignored on iOS

### ISSUE THREAD

**Issue by dirant** [babel/babel#9082]
## Bug Report

**Current Behavior**
When destructuring a parameter in a function call and subsequently using it in an object literal with an assignment, the result is inconsistent on iOS browsers.

This only happens if the parameter was first destructured from an array and only on iPhones.

The output code from the compilation is correct, it may be iOS dealing with object literals differently then expected.

**Input Code**
```js
function test() {
    let ID = "1|123456";
    return (([id, obj]) => ({[id = id.split('|')[1]]: {id: id}}))([ID, {}]);
}
test();
```

**Expected result/Chrome on Windows result**
```js
{"123456":{"id":"123456"}}
```

**iOS result**
```js
{"123456":{"id":"1|123456"}}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets":[
        ["@babel/preset-env",{"targets":
            {"browsers":["last 2 Chrome versions"]}
        }]
    ],
    "plugins":[
        ["@babel/plugin-transform-react-jsx",{
            "pragma":"h"
        }],
        "macros"
    ]
}
```

**Environment**
- Babel version(s): v7.1.6
- Node/npm version: Node 8/npm 5
- OS: Windows 10
- Monorepo no
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
It might be an ordering issue. Could you test if `{ [alert(1)]: alert(2) }` alerts first `1` or first `2`?

**Comment by dirant** [comment]
Unfortunately I can't, I discovered it by remotely logging this via HTTP calls to the server.
I could get the result of the following code:
```js
function test() {
    let ID = "1|123456";
    return {
        [id = id.split('|')[1]]: id
    }
}
test();//{"123456":"123456"}
```
It works correctly, so in this case the order of execution is respected.

I suspect the issue might be with the iOS implementation of the Javascript engine happening when the "id" variable comes from an array destructuring in the function arguments

**Comment by dirant** [comment]
I finally solved the issue by adding specific support for the last 2 versions of iOS in the browserlist.
