### ISSUE TITLE
When a class extends Array, "isPrototypeOf" didn't work properly 

### ISSUE THREAD

**Issue by lin1987www** [babel/babel#9085]
## Bug Report

**Current Behavior**

When a class extends Array, creating instance by that class, compliing the code, I found out the function 'isPrototypeOf' didn't work properly, because it didn't set [[prototype]] to that class.

**Input Code**

```js
class A extends Array{}
var a = new A();
console.log(A.prototype.isPrototypeOf(a));
```

**Expected behavior/code**

```js
// It should be true.
A.prototype.isPrototypeOf(a)  
```

**Environment**
- Babel version(s): v6.26.0

I do the online testing it still the same problem.
https://babeljs.io/repl  

**Possible Solution**

```js
class A extends Array{
    constructor(...args) {
        super(...args);
        // Fix problem
        Object.setPrototypeOf(this,A.prototype);
    }
}
var a = new A();
console.log(A.prototype.isPrototypeOf(a));
```

**Comment by nicolo-ribaudo** [comment]
Can you test it using https://babeljs.io/repl/build/master? Is should work in Babel 7

**Comment by lin1987www** [comment]
Wow, I didn't know that is already fixed in Babel 7 !  
I will update my Babel version, thanks you.
