### ISSUE TITLE
Babel require(component) not working in latest version

### ISSUE THREAD

**Issue by Taerarenai** [babel/babel#9087]
# v7 Regression

**Describe the regression**
A clear and concise description of what the regression is.

Since upgrading to @babel/core (7.1.6) i can't use require(COMPONENT) in React. I was using this to separate SSR React from Client Side React. 

I'm using ReactJS.NET and i have 2 types of components. The SSR component which sends props to other client side components. My SSR loads fine since it has no "window" dependency, but my client-side component stopped working.

**Input Code**
```js
let IRFList;
IRFList = require('./IRFList.jsx');

```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-transform-modules-commonjs",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 2,
        "helpers": true,
        "regenerator": true,
        "useESModules": true
      }
    ]
  ]
} 
```

**Expected behavior/code**
I'm using require to load my child component (which uses window) AFTER the parent has finished loading (so it doesnt throw SSR errors). It is not working anymore and keeps throwing errors such as 

`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Environment**
- Babel version(s):@babel/core 7.1.6
- Node/npm version: Node 8/npm 6
- OS: Windows 10
- Monorepo No
- How you are using Babel: loader with webpack

More info on the error here -> https://stackoverflow.com/questions/53481869/react-createelement-type-is-invalid-uncaught-error-element-type-is-invalid?noredirect=1#comment93833730_53481869

**Comment by nicolo-ribaudo** [comment]
You should `require(COMPONENT).default`, because Babel threats default exports as named exports so that live bindings work.
