### ISSUE TITLE
 Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.

### ISSUE THREAD

**Issue by kingerking** [babel/babel#9088]
My rollup / babel project is not transpiling. The error say's to add 'decoratorsBeforeExport' option.
Ive tried adding this option to my .babelrc and my rollup babel plugin but nothing has helped.
![screen shot 2018-11-26 at 7 30 06 pm](https://user-images.githubusercontent.com/24500901/49054547-d59ad680-f1b1-11e8-868c-dde833011662.png)

**Comment by loganfsmyth** [comment]
I'm not sure about that error specifically, but the first step would be updating to use the Babel 7 version of those plugins, e.g. `@babel/plugin-proposal-decorators` and `@babel/plugin-proposal-class-properties`

**Comment by kingerking** [comment]
@loganfsmyth Okay so I did that, now I have a new error(as seen in the following screenshot). I've tried changing the "decoratorsBeforeExport" to true, false and straight up not adding the option, in all cases I get errors. I'm at a loss here. Haven't been able to fix this 😕
![screen shot 2018-11-30 at 8 37 08 pm](https://user-images.githubusercontent.com/24500901/49323879-2bd48600-f4e0-11e8-8cc6-f6596f351606.png)

**Comment by loganfsmyth** [comment]
Can you post your Rollup config as it stands now? That error makes it sound like `rollup-plugin-babel` isn't active anymore.

**Comment by kingerking** [comment]
Here is my current configuration.
````
// Rollup plugins
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'lib/index.js',
  dest: 'build/index.js',
  format: 'iife',
  sourceMap: 'inline',
    plugins: [
    commonjs(),
    babel({
        exclude: 'node_modules/**',
    }),
  ],
};
````

**Comment by loganfsmyth** [comment]
Could you try changin the Babel config to
```
    babel({
        cwd: __dirname,
        exclude: 'node_modules/**',
    }),
```
and see if that helps?

**Comment by kingerking** [comment]
Nope, got the same error, unfortunately. I found a migration guide for roll-up(some configuration key's they changed), changed over and still nothing sadly 😕, Any other idea's?

**Comment by loganfsmyth** [comment]
Would you be able to make a reproducible example repo? Nothing else is really jumping out at me.

**Comment by kingerking** [comment]
Yeah sure. Would you mind if I added you to a private repository so you can clone? reproduction is just running `yarn build` or `npm build`

**Comment by loganfsmyth** [comment]
Sure, that's fine.

**Comment by loganfsmyth** [comment]
Ah! Thanks, I'm not super familiar with Rollup so I didn't spot it originally.

You need to put `commonjs()` _after_ `babel(/* ... */)` in the Rollup config.

**Comment by kingerking** [comment]
Awesome! you fixed it haha, Thanks for the help, much appreciated.
