### ISSUE TITLE
async/await in .forEach doesn't seem to actually await async operations

### ISSUE THREAD

**Issue by brooklynDev** [babel/babel#909]
I'm not 100% sure this is a bug, or if this the intended semantic, but it feels like a bug to me. Given the following code:

```es6
async function test(){
  let arr = [1,2,3];
  arr.forEach(async (num) => {
   let result = await getData(num);
   console.log(result);
  });
  console.log('after foreach');
}

function getData(x){
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(x);
    }, 500);
  });
}

test().then(() =>{
  console.log('done');
})
```
I would expect the output to be:
```
1
2
3
after foreach
done
```
However, the output I AM getting, is this:
```
after foreach
done
1
2
3
```
Like I said, not sure if this is a bug, or just an artifact of how forEach is actually working, but it certainly wasn't the behavior I was expecting.

**Comment by fkling** [comment]
Well, `forEach` expects synchronous function.

**Comment by brooklynDev** [comment]
Right, that's a valid point. Time for a .forEachAsync :grinning: 

Thanks!

**Comment by neVERberleRfellerER** [comment]
@brooklynDev  This is alternative to async for loop

    async function test(){
      let arr = [1,2,3];
      await Promise.all(arr.map(async (num) => {
        let result = await getData(num);
        console.log(result);
      }));
      console.log('after foreach');
    }

**Comment by sebmck** [comment]
@neVERberleRfellerER Shorthand for that is:

```javascript
async function test(){
  let arr = [1,2,3];
  await* arr.map(async (num) => {
    let result = await getData(num);
    console.log(result);
  });
  console.log('after foreach');
}
```

**Comment by neVERberleRfellerER** [comment]
@sebmck This is perfect. Thanks for info.

**Comment by brooklynDev** [comment]
@sebmck that is awesome! I had no idea `await*` was a thing.

**Comment by ngnam** [comment]
Thanks Bro ^^
`let asyncFn = (item) => {
            return new Promise((resolve, reject) => {
                setTimeout( () => {console.log(item); resolve(true)}, 1000 )
            })
        }
        // asyncFn('a')
        // .then(()=>{return async('b')})
        // .then(()=>{return async('c')})
        // .then(()=>{return async('d')})
        let a = ['a','b','c','d']
        a.reduce((previous, current, index, array) => {
            return previous                                    // initiates the promise chain
            .then(()=>{return asyncFn(array[index])})      //adds .then() promise for each item
        }, Promise.resolve())`
