### ISSUE TITLE
Address duplicate core-js import

### ISSUE THREAD

**Issue by lerayne** [babel/babel#9097]
## Feature Request

This is related to @babel/preset-env and @babel/runtime

useBuiltIns:usage is a great feature that helps avoiding unnecessary polyfills. The drawback though is that other libraries still import core-js explicitly. Because of that, I usually have many core-js modules imported twice:

![image](https://user-images.githubusercontent.com/671158/49209551-77454200-f3c3-11e8-9477-8bf9848da71f.png)

Once as /core-js/modules (via @babel/runtime with 'useBuiltIns:usage') and the second time as /core-js/library/modules

I assume there should be the way to avoid that. Like, for @babel/runtime to import core-js as /core-js/library/modules or programmatically detect polyfills that are already imported

**Comment by zloirock** [comment]
It's rather an issue for a bundler. You could add a mapping `core-js/library` -> `core-js` to webpack. However, you can get some problems with a difference of versions.

**Comment by davidhouweling** [comment]
I wasn't able to map `core-js/library` to `core-js` using webpack, but I was able to go the other way... In webpack you can do...
```
    alias: {
      'core-js': 'core-js/library'
    }
```

**Comment by davidhouweling** [comment]
after a bit more testing it doesn't seem to work accordingly. IE11 complains that Promise isn't available for example.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue because, even if the "duplicated" modules are similar, they have different interfaces and can't be fixed programmatically by Babel.
