### ISSUE TITLE
babel src --out-file / Cannot file module './lib/example'

### ISSUE THREAD

**Issue by jacob-cross99** [babel/babel#9098]
Whenever I built with the command:
```
babel src --out-file client.min.js
```
the following code is generated:
```
var _example = require('./lib/example');

var _example2 = _interopRequireDefault(_example);
.....
```

.babelrc
```
{
  "presets": ["babel-preset-env", "babel-preset-stage-3"]
}
```

I'm expecting the output file to compile all required project files from lib to a single file to remove the require code. Any ideas?

**Comment by xtuc** [comment]
What you are describing is a bundler (like Webpack), Babel transpiles 1:1 the files.

**Comment by jacob-cross99** [comment]
> What you are describing is a bundler (like Webpack), Babel transpiles 1:1 the files.

Why does it add the code from './lib/example' to the --out-file then? I'm getting
```
var Example = function () { ... }
```
No reason to import './lib/example' when the code is already there.

**Comment by loganfsmyth** [comment]
If you have an `import` for that file, it is converted to `require`.
