### ISSUE TITLE
bable-cli ignores folder if there are just .ts files

### ISSUE THREAD

**Issue by MikeMitterer** [babel/babel#9099]
## Bug Report

**Current Behavior**
I have a folder (tools) with two .ts files in it.

If I run `BABEL_ENV=node babel --extensions ".ts, .tsx" tools`
I get an empty output.

If I run `BABEL_ENV=node babel --extensions ".ts, .tsx" tools/fs-test`
the file (it is a .ts file) gets compiled.

If I use webpack it works.

**Expected behavior/code**
Should compile the whole dir into one file like it is mentioned here: https://babeljs.io/docs/en/babel-cli/#compile-directories

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }],
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ],
  "env": {
    "node": {
      "presets": [
        ["@babel/preset-env", {
          "targets": {
            "esmodules": true,
            "node": "current"
          },
          "modules": "auto"
        }]
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 7.1.5 (@babel/core 7.1.6)
- Node/npm version: v11.2.0
- OS: ProductName:	Mac OS X, ProductVersion:	10.11.6

- How you are using Babel: [e.g. `cli`, `register`, `loader`]

BTW: The whole bable/TS-Thing works great!!! (except this little issue)

**Comment by loganfsmyth** [comment]
You get no output because of https://github.com/babel/babel/pull/8668, but yeah really you want `--out-dir`
