### ISSUE TITLE
path.insertBefore creates function parentheses

### ISSUE THREAD

**Issue by JohMun** [babel/babel#9103]
Hey, 

I like to add a new element to an array with `path.insertBefore`. However, I don't get clean code, because babel inserts function parentheses. I made an example at [AST explorer](https://astexplorer.net/#/gist/f21f51c36fd4d9141214418e3ec5eaca/7e0edadeb7be7e9040a31a0d5c4deef0304dbf7b). Is there a way to get an Array that is looking like this?
```
[
  'a', "d",
  'b',
  'c'];
```
Thanks for your help!

**Comment by danez** [comment]
I'm not sure insertBefore should work in this case, but changing it to this seems to work:
https://astexplorer.net/#/gist/f21f51c36fd4d9141214418e3ec5eaca/1d75e6a4c0f497079ada0e688a05d3f7b59a6363

**Comment by JohMun** [comment]
Thx, seems to work!
