### ISSUE TITLE
Simplify buildNamespaceReexport

### ISSUE THREAD

**Issue by mathiasbynens** [babel/babel#9109]
This code is meant to prevent `__esModule` from being overwritten: https://github.com/babel/babel/blob/806e1334737f4fbf29615c04d227076b76d7f041/packages/babel-helper-module-transforms/src/index.js#L243

It’s helpful in loose mode, but for non-loose mode the `key === "__esModule"` is redundant, since the `__esModule` property is then added as follows:

```js
Object.defineProperty(exports, '__esModule', {
  value: true
});
```

Note that `enumerable: false` is implied here, and so `__esModule` won’t show up in `Object.keys(exports)`.

Your mission, should you choose to accept it, is to remove this redundant check from the non-loose mode code path!

Ref. https://github.com/tc39/ecma262/pull/1320#issuecomment-443403224.

**Comment by loganfsmyth** [comment]
I don't think we can do that safely because it's not a question of if the _current_ file is running in loose mode, but rather if the module namespace that is being re-exported is in loose mode.

**Comment by mathiasbynens** [comment]
In that case we should close this issue :)
