### ISSUE TITLE
@babel/plugin-proposal-private-methods is not published.

### ISSUE THREAD

**Issue by m31271n** [babel/babel#9118]
## Bug Report

**Current Behavior**
I noticed [babel-plugin-proposal-private-methods](https://github.com/babel/babel/tree/4e28459a2fc27dd7888efac3cf803ccb2f712285/packages/babel-plugin-proposal-private-methods) is commited.

But It's not published on NPM.

**Question**
Is it still in testing stage?

**Comment by danez** [comment]
This is correct it was not yet published. It will be published with version 7.2.0 soon.
