### ISSUE TITLE
Decorators are not enabled with `@babel/plugin-proposal-class-properties` and `@babel/plugin-proposal-decorators`

### ISSUE THREAD

**Issue by HsuTing** [babel/babel#9123]
## Bug Report

**Current Behavior**
Can not compile

**Input Code**
- [repo](https://github.com/HsuTing/babel-bug-example)

**Expected behavior/code**
This should work. Before `7.2.0`, this can compile.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = { 
  presets: [
    [   
      '@babel/preset-env',
      {   
        useBuiltIns: 'usage',
      },  
    ],  
  ],  
  plugins: [
    '@babel/plugin-proposal-class-properties',
    [   
      '@babel/plugin-proposal-decorators',
      {   
        legacy: true,
      },  
    ],  
  ],  
};
```

**Environment**
- Babel version(s): v7.2.0
- Node/npm version: node 11.3.0/npm 6.4.1
- OS: OSX 10.14.1
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
Ad stated at https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babel-plugin-proposal-class-properties, the decorators plugin must come _before_ the class properties plugin.

I cloned your repo and, if I swap them, I get this output:

```js
"use strict";

var _class;

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Test = decorator(_class = function Test() {
  _classCallCheck(this, Test);
}) || _class;%  
```

**Comment by HsuTing** [comment]
@nicolo-ribaudo thank you for your help.
I did not note that, sorry.
