### ISSUE TITLE
@babel/parser - provide means to traverse the AST.

### ISSUE THREAD

**Issue by Izhaki** [babel/babel#9126]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It seems that @babel/parser does not expose means to traverse the AST.

**Describe the solution you'd like**
Similar to [Typescript's forEachChild](https://github.com/Microsoft/TypeScript/blob/8ddb2b61d2c996ab442b282ab9b36195ed697c13/lib/typescript.d.ts#L3532), something like `forEachChild(node, callback)` will do.

**Describe alternatives you've considered**
```js
const { isArray } = Array;
const isNode = node => node && (node.type || isArray(node)); // This just happens to work.
const flatten = (acc, item) => acc.concat(item);

const getNodeChildren = node => {
  const children = Object.values(node)
    .filter(isNode)
    .reduce(flatten, []);
  return children;
};

export default (node, callback) => {
  const children = getNodeChildren(node);
  children.forEach(callback);
};
```
But this relies on `node.type`, which is loooooooose.
The `Node` class does not seem to be exported, so one cannot use (the more rigid) `instanceof`.

**Comment by loganfsmyth** [comment]
We provide the `@babel/traverse` package: https://babeljs.io/docs/en/babel-traverse
