### ISSUE TITLE
Update browserslist v4.3.2

### ISSUE THREAD

**Issue by y-ogura** [babel/babel#9138]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Hi, I'm having issue with `@babel/preset-env`.
I got this error when run unit test.
```
BrowserslistError: [BABEL] /Users/ogura/vue/nuts/nuts-manage-ui/test/unit/specs/open-hours/open-hours.spec.js: Unknown version 11 of Node.js (While processing: "/Users/ogura/vue/nuts/nuts-manage-ui/node_modules/@babel/preset-env/lib/index.js")
```
This issue fixed in browserslist v4.3.2
But `@babel/preset-env` has browserslist v4.1.1
I'm using Babel 7

**Describe the solution you'd like**
1. Use Browserslist 4.3.2

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by existentialism** [comment]
@y-ogura preset-env actually uses [`browserslist@^4.3.4`](https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json#L54)? Can you try reinstalling or updating your lockfile?

**Comment by y-ogura** [comment]
@existentialism 
I updated babel ^7.2.0 then I can running unit test.
thank you for your support.
closing this issue.
