### ISSUE TITLE
Disable transforms for parameters/destructuring in Edge 18

### ISSUE THREAD

**Issue by saschanaz** [babel/babel#9139]
## Bug Report

**Current Behavior**
babel-preset-env forces parameters/destructuring transforms for "last 1 Edge version"

**Input Code**

```js
function foo({bar = ""} = {}) { return bar; }
var [c] = foo();
```

**Expected behavior/code**
It should just pass-through.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "last 1 Firefox version, last 1 Chrome version, last 1 Safari version, last 1 Edge version",
        "modules": "amd"
      }
    ]
  ]
}

```

**Environment**
- Babel version(s): v7.1.5
- Node/npm version: Node 11/npm 6
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `cli`

**Comment by existentialism** [comment]
Fixed in https://github.com/babel/babel/pull/9140
