### ISSUE TITLE
Duplicate declaration error when defining variables with same name inside different class private methods

### ISSUE THREAD

**Issue by SeinopSys** [babel/babel#9150]
## Bug Report

**Current Behavior**
The code below causes a `Duplicate declaration "values"` error.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1oGIBGAKAlM1qIApgC7QBuYIArkRANwrQC-Tawu-BxZlNdjVK2ZA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=stage-3&prettier=false&targets=&version=7.2.0&envVersion=

```js
class A {
  #b(){
    let values;
  }
  #c(){
    let values;
  }
}
```

**Expected behavior/code**
The variables should not conflict as they are in different scopes.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: ['@babel/preset-env','@babel/preset-react'],
  plugins: [
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-private-methods',
    '@babel/plugin-proposal-class-properties',
  ]
}
```

**Environment**
- Babel version(s): v7.2.1
- Node/npm version: Node 10, npm 6.4.1
- OS: Windows 10
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [`gulp-babel`](https://github.com/babel/gulp-babel)

**Comment by danez** [comment]
This does not seem to happen anymore. Can you test again with the latest version of babel?

/cc @nicolo-ribaudo Do you know if we fixed this?

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9453 :+1:
