### ISSUE TITLE
Babel7 error Missing class properties transform

### ISSUE THREAD

**Issue by cam510** [babel/babel#9156]
hello, I upgrade the bable 7 in my react project ,but i have some error when I use webpack and npm run build.

ERROR in ./src/pages/ticket-qrcode.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/cam/workspace/h5_workspace/custom_bus_babel_test/src/pages/ticket-qrcode.js: Missing class properties transform.
  34 |   }
  35 | 
> 36 |   goToMyTickets = () => {
     |   ^
  37 |     this.props.history.replace('./my-tickets')
  38 |   }

my .babelrc is 
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-transform-arrow-functions",
    "@babel/plugin-transform-runtime",
    "@babel/plugin-transform-block-scoping",
    "@babel/plugin-transform-classes",
    [
      "@babel/plugin-proposal-function-bind",
      {
        "loose": true
      }
    ],
    "@babel/plugin-syntax-class-properties",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-regenerator",
    "@babel/plugin-proposal-object-rest-spread",
    "babel-plugin-flow-react-proptypes",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-class-properties",
    "transform-class-properties",
    "transform-object-rest-spread",
    [
      "import",
      {
        "libraryName": "antd-mobile",
        "style": true
      }
    ]
  ]
}

and my package.json is 
"dependencies": {
    "@babel/plugin-proposal-decorators": "^7.2.0",
    "@babel/plugin-transform-arrow-functions": "^7.2.0",
    "antd-mobile": "^2.2.3",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "cookies-js": "^1.2.3",
    "crypto-js": "^3.1.9-1",
    "js-base64": "^2.4.9",
    "jsencrypt": "^3.0.0-rc.1",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "qr-image": "^3.2.0",
    "qs": "^6.5.2",
    "react": "^16.4.2",
    "react-barcode": "^1.3.4",
    "react-dom": "^16.4.2",
    "react-loadable": "^5.5.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "sm-crypto": "0.0.6",
    "storejs": "^1.0.20",
    "svgpath": "^2.2.1"
  },
"devDependencies": {
    "@babel/cli": "^7.2.0",
    "@babel/core": "^7.2.0",
    "@babel/plugin-proposal-class-properties": "^7.2.1",
    "@babel/plugin-proposal-function-bind": "^7.2.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
    "@babel/plugin-syntax-class-properties": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-block-scoping": "^7.2.0",
    "@babel/plugin-transform-classes": "^7.2.0",
    "@babel/plugin-transform-regenerator": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.2.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.2.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-flow-react-proptypes": "^24.1.2",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "css-loader": "^1.0.0",
    "encryptjs": "^2.0.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "json-loader": "^0.5.7",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.4.1",
    "raw-loader": "^0.5.1",
    "readline": "^1.3.0",
    "sass-loader": "^7.1.0",
    "serviceworker-webpack-plugin": "^1.0.1",
    "style-loader": "^0.22.1",
    "svg-loader": "0.0.2",
    "svg-url-loader": "^2.3.2",
    "terser-webpack-plugin": "^1.1.0",
    "uglify-es": "^3.3.9",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.16.5",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5"
  }

**Comment by hzoo** [comment]
Thanks, but it would be helpful if you had a reproducible example. Right now there are a lot of extraneous packages included (like if you are using Babel 7 now I would remove things like "transform-class-properties","transform-object-rest-spread". "@babel/plugin-transform-arrow-functions", 
"@babel/plugin-transform-block-scoping": "^7.2.0",
"@babel/plugin-transform-classes": "^7.2.0", are also not necessary since they are included in preset-env.

**Comment by cam510** [comment]
@hzoo thanks,let me try remove these plugins and build again

**Comment by cam510** [comment]
@hzoo 
thanks very much, when i remove the plugins what you say and run build successful.

**Comment by cam510** [comment]
@hzoo 
Hi hzoo，may I ask a stupid question?
If I want to output es5 with webpack,
i just user @babel/polyfill in the index js file? or I add plugins: [@babel/plugin-proposal-object-rest-spread] in .babelrc ?
