### ISSUE TITLE
Playground suggestion: Enums

### ISSUE THREAD

**Issue by cvrebert** [babel/babel#916]
[Like in TypeScript.](http://www.typescriptlang.org/Handbook#basic-types-enum)
Page 121 of [their spec](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf) shows the suggested transformation; it's fairly simple.

**Comment by Dashed** [comment]
Sorta +1 for the sugar.

You can already use Symbols to emulate Enums: http://www.2ality.com/2014/12/es6-symbols.html

**Comment by sebmck** [comment]
Not looking to pursue this at this time, may revisit in the future. Thanks for the suggestion!
