### ISSUE TITLE
Android 4.4 Webview Uncaught ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by dcDulsea** [babel/babel#9162]
## Bug Report

**Current Behavior**
At Android4.4 webview or  a lower version of the browser, ES6 'new Map()' and 'new Set()' ain't transformed.
I was install '@babel/plugin-transform-runtime' and '@babel/runtime-corejs2', and i also configuration complete, but it didn't work

**Input Code**
- REPL or Repo link if applicable:

```js

/***/ "./node_modules/@babel/runtime-corejs2/core-js/map.js":
/*!************************************************************!*\
  !*** ./node_modules/@babel/runtime-corejs2/core-js/map.js ***!
  \************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! core-js/library/fn/map */ "./node_modules/core-js/library/fn/map.js");

/***/ }),

function assembleStyles() {
  var codes = new Map();

```

**Expected behavior/code**
I want to the 'Map' can be transformed

**Babel Configuration (.babelrc, package.json, cli command)**

```js

"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      ["@babel/plugin-transform-runtime",{
        "corejs": 2,
        "helpers": true,
        "regenerator": true,
        "useESModules": false
      }]
    ]
  },

```

**Environment**
- Babel version(s): [v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [Android 4.4]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [`loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by loganfsmyth** [comment]
Is `assembleStyles` your own code, or a `node_module`? Are you compiling `node_modules`?

**Comment by dcDulsea** [comment]
> Is `assembleStyles` your own code, or a `node_module`? Are you compiling `node_modules`?

`node_modules`,i find it at 'ansi-styles', but i find it at chrome's console when i build with webpack4(webpack-dev-server). 

`'use strict';
const colorConvert = require('color-convert');

const wrapAnsi16 = (fn, offset) => function () {
	const code = fn.apply(colorConvert, arguments);
	return `\u001B[${code + offset}m`;
};

const wrapAnsi256 = (fn, offset) => function () {
	const code = fn.apply(colorConvert, arguments);
	return `\u001B[${38 + offset};5;${code}m`;
};

const wrapAnsi16m = (fn, offset) => function () {
	const rgb = fn.apply(colorConvert, arguments);
	return `\u001B[${38 + offset};2;${rgb[0]};${rgb[1]};${rgb[2]}m`;
};

function assembleStyles() {
	const codes = new Map();
	const styles = {
		modifier: {
			reset: [0, 0],
			// 21 isn't widely supported and 22 does the same thing
			bold: [1, 22],`
