### ISSUE TITLE
Retain indentation on inserting new nodes

### ISSUE THREAD

**Issue by innovation-stack** [babel/babel#9164]
Is there a way to preserve indentation on inserting new nodes? I've created a sample example [here](https://astexplorer.net/#/gist/529b344f2747d854900ff42b04dea5af/c4329e96a5977eb49254a680619eeab4659b88c8).
**Input:**
```
var obj = {
  x: [
    'abc',
    'def'
  ]
};
```
**Actual Output**
```
var obj = {
  x: ['ghi', 'abc', 'def']
};
```

**Expected**
```
var obj = {
  x: [
    'abc',
    'def',
    'ghi'
  ]
};

```

**Comment by loganfsmyth** [comment]
Babel does not preserve formatting, just code structure. Maybe run the code through Prettier or try using Babel with `recast`?

**Comment by innovation-stack** [comment]
Thank you @loganfsmyth .
