### ISSUE TITLE
compile a file into a subdirectory fails

### ISSUE THREAD

**Issue by xxyyzz2050** [babel/babel#9169]
examples
npx babel file.js --out-file subdir/file.compiled.js  -> fails
but compiling the same file into the current directory succedded
npx babel file.js --out-file file.compiled.js -> success

**Comment by loganfsmyth** [comment]
What specifically fails? Is there an error?

**Comment by danez** [comment]
If you have more info please reopen and add info about which version you are using, what the exact error is what the file you are trying to compile looks like.

**Comment by xxyyzz2050** [comment]
more details...
if you want to use babel to transpile a file into a non-exist sub directory, an error occurres:
-> the error is because the sub-directory is not exist, so it is a minor issue

>npx babel ts.js --out-file subdir/file.compiled.js
{ Error: ENOENT: no such file or directory, open 'subdir/file.compiled.js'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1187:35)
    at output (node_modules\@babel
\cli\lib\babel\file.js:148:23)
    at node_modules\@babel\cli\lib
\babel\file.js:234:9
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (node_modules\@babel\cli\lib\babel\file.js:74:103)
    at _next (node_modules\@babel\cli\lib\babel\file.js:76:194)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'subdir/file.compiled.js' }

but when you compile a whole directory to a non-exist directory, babel automatically creates the non-exist sub directory
