### ISSUE TITLE
useBuiltIns: 'usage' does not build

### ISSUE THREAD

**Issue by modestotech** [babel/babel#9175]
## Bug Report

**Current Behavior**
I'm using babel-polyfill with the @babel/preset-env package. My current setup is this, and it works fine, confirmed to polyfill for functioning on IE11 etc. Everything babel related is up to date. 

**Working Code**

babel.config.js
```js
module.exports = function (api) {
  api.cache(true);

  const presets = [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'entry',
      },
    ],
    '@babel/preset-react',
  ];
  const plugins = ['@babel/plugin-proposal-class-properties'];

  return {
    presets,
    plugins,
  };
};
```

webpack.common.js
```js
...
module.exports = {
  entry: ['@babel/polyfill', './src/index.js'],
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },
...
```

When I set `useBuiltIns: 'usage'`, and change entry to `['./src/index.js']`, as is described in the official documentation [here](https://babeljs.io/docs/en/babel-polyfill#usage-in-node-browserify-webpack), I get a lot of warnings and one error when building, before webpack stops. 

The errors are related to npm modules as well as application code. I add some examples below: 
```terminal

WARNING in ./node_modules/react-popper/lib/esm/Reference.js 29:4-11
"export 'default' (imported as 'warning') was not found in 'warning'
 @ ./node_modules/react-popper/lib/esm/index.js
 @ ./node_modules/react-datepicker/es/index.js
 @ ./src/components/shared/FormControls/DateTimePicker.jsx
 @ ./src/components/shared/FormControls/FormField.js
 @ ./src/components/forms/NotificationForm/InformationTemplate.js
 @ ./src/components/pages/IssuesPage/IssuesPage.jsx
 @ ./src/config/routes.js
 @ ./src/components/AppRouterSwitch.jsx
 @ ./src/components/App.jsx
 @ ./src/index.js
 @ multi ./src/index.js

WARNING in ./node_modules/react-router-dom/es/BrowserRouter.js 62:4-11
"export 'default' (imported as 'warning') was not found in 'warning'
 @ ./node_modules/react-router-dom/es/index.js
 @ ./src/components/App.jsx
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in   Error: C:\Ikea.iSubscribe\src\Ikea.iSubscribe.ClientApp\public\in  dex.html:1090
  module.exports = function (it, S) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of objec  t '#<Object>'

```

**Expected behavior/code**
I expect `useBuiltIns: 'usage'` to work so that I can take advantage of the bundler loading each polyfill once, as stated [here](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage-experimental) without me having to do anything more compared to the `useBuiltIns: 'entry'`, that works well. 

**Babel versions**
```js
...
  "dependencies": {
    "@babel/polyfill": "^7.0.0",
...
  "devDependencies": {
    "@babel/core": "^7.2.0",
    "@babel/plugin-proposal-class-properties": "^7.2.1",
    "@babel/preset-env": "^7.2.0",
    "@babel/preset-react": "^7.0.0",
    "autoprefixer": "^9.4.2",
    "babel-loader": "^8.0.4",
...
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: v10.13.0/6.4.1
- OS: Windows 8
- How you are using Babel: webpack

**Comment by nicolo-ribaudo** [comment]
Could you try to set `sourceType: "unambiguous"` in your babel config? I think that Babel is injecting `import` statements in your cjs dependencies and thus WebPack is bundling them as ES modules.

**Comment by modestotech** [comment]
@nicolo-ribaudo, by including that option I got rid of the errors in the npm modules, but now it failed on this error. 
```terminal
ERROR in   Error: C:\Ikea.iSubscribe\src\Ikea.iSubscribe.ClientApp\public\index.html:960
    var SYMBOL = wks(KEY);
                 ^
  TypeError: wks is not a function
```

I googled and found another thread where you have been active, and the solution was [here](https://github.com/babel/babel/issues/8731#issuecomment-423898350). 

This is quite badly documented, I've created a [request](https://github.com/babel/babel/issues/9185) for better documentation, and difference between 'usage' and 'entry', when you should use on over the another etc. 

For people having similar problems, here is my babel.config.js:
```javascript
module.exports = function (api) {
  api.cache(true);

  const ignore = [
    /[\/\\]core-js/,
    /@babel[\/\\]runtime/,
  ];

  const sourceType = 'unambiguous';

  const presets = [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'usage',
      },
    ],
    '@babel/preset-react',
  ];

  const plugins = ['@babel/plugin-proposal-class-properties'];

  return {
    ignore,
    sourceType,
    presets,
    plugins,
  };
};
```
