### ISSUE TITLE
Compiling ES modules to CJS with `noInterop: true` does not preserve export order

### ISSUE THREAD

**Issue by robertrossmann** [babel/babel#9177]
## Bug Report

**Current Behavior**

With the `noInterop: true` flag provided to the `@babel/transform-modules-commonjs` plugin, the order of named export statements is not preserved in the compiled CommonJS module.

**Input Code**

```js
// input.mjs
const first = true
const second = true

export {
  first,
  second,
}
```

**Expected behavior/code**

When I `import` or `require` the above-mentioned _input.mjs_ file (compiled), I would expect that the keys would be enumerated in the order they were exported:

```js
const input = require('./input')
// or
import * as input from './input'

const names = Object.keys(input)

names[0] // -> 'first'
names[1] // -> 'second'
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  sourceMaps: 'inline',
  comments: false,
  plugins: [
    '@babel/syntax-object-rest-spread',
    ['@babel/transform-modules-commonjs', {
      allowTopLevelThis: false,
      noInterop: true,
    }],
    ['@babel/proposal-decorators', {
      decoratorsBeforeExport: false,
    }],
    '@babel/proposal-class-properties',
    '@babel/proposal-function-bind',
  ],
}
```

**Environment**
- Babel version(s): `7.2.0 (@babel/core 7.2.0)`
- Node/npm version: Node.js 11.3.0
- OS: macOS 10.14
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**

The compiled code might create the properties on the `exports` object in the order in which the ES modules' `export` statement has been defined.

**Additional context/Screenshots**

The exported names' order **is preserved** if I set `noInterop: false`. I am not sure what the correct behaviour is - whether this is a bug in Babel or that the order is only preserved due to the way how CommonJS modules are normally defined when `noInterop: false`. Object keys should preserve their order as per the spec, I believe, but I am not certain if named exports can be considered an "object" when they are imported.

Nevertheless, one might argue that since we are compiling the ES module to a CommonJS module which is, by definition, an object, it would be "logical" to expect the export order to be preserved, but I think this is purely philosophical.

**Comment by robertrossmann** [comment]
Oh... thanks for the explanation. Looks like I will have to re-work my project quite seriously to avoid dependency on CommonJS module exports being exported in the order they were defined. 😢

Feel free to keep this open to track the sorting order compliance or close this - I will have to fix my problem on my end regardless of the outcome here. Thanks for the help! ❤️

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue: even is Babel isn't 100% spec compliant here, I don't think we can do any better.
