### ISSUE TITLE
Derived class loses prototype

### ISSUE THREAD

**Issue by d07RiV** [babel/babel#9183]
## Bug Report

**Current Behavior**

Outputs `{ foo: 1 }` (plain object). Prototype is lost and uses Object instead. Attempting to call `bar()` will fail.

Same result using online translator at https://babeljs.io/en/repl

**Input Code**

```js
const fooBar = parent => class extends parent {
  constructor() {
    super();
    this.foo = 1;
  }
  bar() {
    return 2;
  }
}

class FooBar extends fooBar(Object) {};

console.log(new FooBar());
```

**Expected behavior/code**

Outputs `FooBar { foo: 1 }` when the original file is ran.

Babel output: https://pastebin.com/raw/AkFwCZH7

**Babel Configuration (.babelrc)**

```js
{
  "presets": ["@babel/preset-env"]
}
```

**Environment**
- Babel version(s): v7.2.0 or v6.25 (both fail)
- Node/npm version: Node 8.9.1 or 11.4.0 (both fail), npm 5.3.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: cli and loader

**Possible Solution**
If I declare `fooBar` as a class derived from `Object`, the `Object` is wrapped via `_wrapNativeSuper`. But if it is passed as a parameter, Babel does not seem to detect this case and omits the wrap call.

**Comment by nicolo-ribaudo** [comment]
It is a known limitation of extending built-ins.

In Babel 7 we fixed it, but you need to "hint" Babel that you are extending a builtin class putting it directly in the `extends` expression:

```js
const fooBar = parent => class extends parent {
  constructor() {
    super();
    this.foo = 1;
  }
  bar() {
    return 2;
  }
}

class FooBar extends fooBar(class extends Object {}) {};

console.log(new FooBar());
```

**Comment by d07RiV** [comment]
I just noticed that inheriting from Object directly adds a call to `_wrapNativeSuper`, which would explain the fix.

Would this trick work with Babel 6?

**Comment by nicolo-ribaudo** [comment]
Nope, we fixed in the first release of Babel 7. Btw, you can use Babel 7 in the repl at https://babeljs.io/repl/build/master

**Comment by d07RiV** [comment]
Just making sure - `class {}` is equivalent to `class extends Object {}`, and will work in any version, right?

**Comment by nicolo-ribaudo** [comment]
Yes :+1:
