### ISSUE TITLE
Better documentation and explanation of useBuiltIns in @babel/preset-env

### ISSUE THREAD

**Issue by modestotech** [babel/babel#9185]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'm having troubles wrapping my head the implications of the `useBuiltIns` option in`@babel/preset-env`. I've read the [documentation](https://babeljs.io/docs/en/babel-preset-env) and can understand the concepts, but the implications of the `useBuiltIns` options remain vague to me. 

I used the `entry` option successfully but then wanted to use `usage` as it seems to me that it makes more sense to import the polyfills when needed. I had some troubles with the implementation but got help from the community [here](https://github.com/babel/babel/issues/9175) and [here](https://github.com/babel/babel/issues/8731). The solutions are not obvious to me. 

**Describe the solution you'd like**

I would like a better documentation of what each option does (in terms comprehensible to your average developer), and _why_ both options exist. Is one of them recommended, or what decides when one should be chosen over another?

**Comment by zloirock** [comment]
Seems it's an issue for another repo.

@babel-bot move to babel/website
