### ISSUE TITLE
@babel/preset-typescript runtime type-checking option

### ISSUE THREAD

**Issue by harrysolovay** [babel/babel#9188]
## Feature Request

Using `babel-register` in conjunction with `preset-typescript` is really powerful if not for the fact that there's no runtime type-checking. The benefit of `babel-register` is that compilation tasks can be avoided. Regularly running `tsc` (even in watch mode) is frustrating.

**Describe the solution you'd like**
I like the idea of keeping it closer to the wire by having some more configuration options (such as pointing to a `tsconfig.json` and even a `tslint.json`). It might be a little slower, but the DX benefits would be TREMENDOUS.

**Describe alternatives you've considered**
Running separate typechecking and linting scripts is frustrating.

**Teachability, Documentation, Adoption, Migration Strategy**
Updating the documentation.

**Comment by harrysolovay** [comment]
Oh and... if there's a performant way to throw TSLint in there as well, that'd be pretty sweeeeeet

**Comment by danez** [comment]
This is out of scope for babel. Babel is a source code transformer and we do not have the infrastructure for doing type checks.
This does not mean it is not possible todo, but it probably has to be done as a separate tool that can be used in conjunction with `babel-register`.
The other thing I can think of is transforming typescript type annotations to javascript code that checks types during runtime, but this is a huge effort and also not in scope for babel itself. This could be done in a separate project.
