### ISSUE TITLE
notarget No matching version found for @babel/types@^7.2.2

### ISSUE THREAD

**Issue by igbaryya** [babel/babel#9191]
Hi,
 

After upgrading the babel/versions to V7.2.2 our npm are not able to find the new version and it is throwing below errors: 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.2.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget

I tried to clean the cache/remove the node-modules/ update all the packages, but it still failing 

Please advise what it could be.. 

Thanks! 
[2018-12-15T20_58_02_210Z-debug.log](https://github.com/babel/babel/files/2683068/2018-12-15T20_58_02_210Z-debug.log)

**Comment by danez** [comment]
It was release successfully, see here https://unpkg.com/@babel/types@7.2.2/ or directly look in the npm registry http://registry.npmjs.org/@babel/types

Are you using a npm proxy such as Sonatype Nexus, JFrog Artifactory or similar? You might need to flush the cache there.
