### ISSUE TITLE
This relative module was not found:  ../test/test.js in ./node_modules/babel-loader/lib

### ISSUE THREAD

**Issue by xxyyzz2050** [babel/babel#9195]
This relative module was not found:
../test/test.js in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vu
e-loader/lib??vue-loader-options!./pages/ts.vue?vue&type=script&lang=js&

(node:6300) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loadResources' of undefined
    at Server.loadResources (node_modules\@nuxt\server\dist\server.js:653:26)
    at compiler.hooks.done.tap (node_modules\@nuxt\webpack\dist\webpack.js:5089:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by loganfsmyth** [comment]
This does not appear to be a Babel issue.

**Comment by xxyyzz2050** [comment]
I ask about the error from babel (even it is not from babel), it should give more details

**Comment by loganfsmyth** [comment]
The only reason Babel is mentioned in the error is because Vue uses Babel. The error itself appears to be from Nuxt, so I would raise it with them.
