### ISSUE TITLE
If it's obvious that split is invoked on String, core-js/modules/es6.regexp.split.js shouldn't be included (required)

### ISSUE THREAD

**Issue by haqer1** [babel/babel#9196]
## Bug Report

**Current Behavior**
The unnecessary require call significantly increases the size of the output file: which results in unnecessary data traveling all over the web (originating from sites using Babel).

**Input Code**
E.g., new String is made from string below as an attempt to make it obvious that core-js/modules/es6.regexp.split.js is not needed:

```js
var sa = new String(string).split(".");
```

**Expected behavior/code**
require("core-js/modules/es6.regexp.split") is completely redundant here, but it gets included even when it's obvious the call is made on a String.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
const presets = [ 
  [
    "@babel/preset-env",
    {   
      targets: {
        ie: "9",
        edge: "16",
        firefox: "50",
        chrome: "57",
        safari: "10",
      },  
      modules: "auto",
      useBuiltIns: "usage",
      debug: false
    },  
  ],  
];

module.exports = { presets };
```

**Environment**
- Babel version(s): 7.2.0 (@babel/core 7.2.0)
- Node/npm version: [Node v10.14.1/npm 6.4.1]
- OS: Ubuntu
- How you are using Babel: `cli`

**Possible Solution**
After a few trials to prevent core-js/modules/es6.regexp.split from being required (included), i just used ant to hack the file generated by Babel:
```xml
		<exec dir="${basedir}" executable="sed">
			<arg value="-ri "/>
			<arg value='/require\("core-js\/modules\/es6.regexp.split"\);/d'/>
			<arg value="src/main/webapp/include/js/compiled/generated/file.js"/>
		</exec>
```

**Additional context**
I believe even in simple conditionals like the following, Babel should be smart enough to not include unnecessary modules:
var sa = typeof str == "string" ? /* it's now obvious that str is a String */ str.split(".") : null;

**Comment by nicolo-ribaudo** [comment]
`core-js/modules/es6.regexp.split` is actually a polyfill for `String.prototype.split`

**Comment by haqer1** [comment]
> core-js/modules/es6.regexp.split is actually a polyfill for String.prototype.split
That doesn't seem to be an accurate statement. es6.regexp.split.js file is 5.1KB, which pulls in even more files:
```js
var isRegExp = require('./_is-regexp');
var anObject = require('./_an-object');
var speciesConstructor = require('./_species-constructor');
var advanceStringIndex = require('./_advance-string-index');
var toLength = require('./_to-length');
var callRegExpExec = require('./_regexp-exec-abstract');
var regexpExec = require('./_regexp-exec');
```
IMHO, when all of that is easily avoidable it should be avoided. E.g., 
String.prototype.split() is supported almost ubiquitously:
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/split
So in absolute majority of (if not all) cases there's no need to import anything for a split() invoked on a String.

P.S. A framework importing unnecessary code causes overhead in the apps using it, & in browsers of all the users using those apps. I.e., waste is propagated around; conversely, an optimization will also be propagated around.

**Comment by haqer1** [comment]
> By "it is obvious that the call is made on a string", do you mean that the `this` object is a string (e.g. `new String(string)`)
Yes, the object that split method is invoked on.
> or that the parameter is a string (`"."`)?
split method is not invoked on param, so it's not really relevant to this bug.
> In the first case the polyfill is definetly needed
I disagree, because String.split is ubiquitously supported without including a bunch of additional code, which is completely redundant (& wasteful):
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/split

P.S. I logged a similar issue issue for https://api.jquery.com/find/ treatment:
https://github.com/babel/babel/issues/9308

**Comment by zloirock** [comment]
> split method is not invoked on param, so it's not really relevant to this bug.

`es6.regexp.split` is not required only if `.split` param is a string. In the rest cases, this method has many bugs and behavior of the method changed by the latest spec. Well-known symbols, direct call of `.exec` method of regexp, etc.

**Comment by nicolo-ribaudo** [comment]
An example:
```js
new String("foo").split({
  __proto__: /./,
  exec() {
    alert("It should be called!");
    return null;
  }
}); 
```

**Comment by haqer1** [comment]
> An example:
> 
> ```js
> new String("foo").split({
>   __proto__: /./,
>   exec() {
>     alert("It should be called!");
>     return null;
>   }
> }); 
> ```
Running this in Firefox Scratchpad produces the following:
/*
Exception: TypeError: get global method called on incompatible Object
@Scratchpad/1:10:19
*/

I think in many if not most cases the param to split would be a plain String as well, so if there are fringe cases that can't be optimized the optimization can be limited to split calls with plain String param (which again, would cover many if not most cases relevant to this bug).

**Comment by esynaps** [comment]
I am also concerned by this problem. I have an empty page loaded into a hidden iframe that contains a small script in Js (18Kb). At one place I use `myVariable.split(',')` and I end up with useless polyfills (87.4Kb) 4 times heavier than my code

**Comment by nailao** [comment]
![image](https://user-images.githubusercontent.com/19665552/105580428-4a382280-5dc7-11eb-851e-d429b91f0095.png)
Use "window.location.search" to also add polyfill

**Comment by nicolo-ribaudo** [comment]
I have opened https://github.com/babel/babel-polyfills/pull/58 to fix this. That package will be soon used by preset-env internally, and it will be the recommended way to inject polyfills starting from Babel 8.

**Comment by zhanxiaoge** [comment]
> I have opened [babel/babel-polyfills#58](https://github.com/babel/babel-polyfills/pull/58) to fix this. That repository will be soon used by preset-env internally, and it will be the recommended way to inject polyfills starting from Babel 8.

Thank you for your reply.
