### ISSUE TITLE
transform-regenerator do not work with generator method in class. 

### ISSUE THREAD

**Issue by bubkoo** [babel/babel#9203]
## Bug Report

**Current Behavior**

Class with a generator method like this:

```js
class Foo {  
  method(){
    thia.val = 10;
  }

  *bar(){
    yield this.val;
    return 'bar';
  }
}
```

I disabled class transform option because many browsers are natively support this feature.  But I got a bad transformed output:

```js
class Foo {
  method() {
    thia.val = 10;
  }

  bar() {
    return regeneratorRuntime.wrap(
      function _callee$(_context) {
        while (1)
          switch ((_context.prev = _context.next)) {
            case 0:
              _context.next = 2;
              return this.val;

            case 2:
              return _context.abrupt("return", "bar");

            case 3:
            case "end":
              return _context.stop();
          }
      },
      _callee,
      this
    );
  }
}
```

When run in browser, got `_callee` is not defined.

**Expected behavior/code**

The correct transform result maybe looks like:

```js
class Foo {
  method() {
    thia.val = 10;
  }

  bar() {
    return regeneratorRuntime.mark(function bar() {
      return regeneratorRuntime.wrap(
        function bar$(_context) {
          while (1) {
            switch ((_context.prev = _context.next)) {
              case 0:
                _context.next = 2;
                return this.val;

              case 2:
                return _context.abrupt("return", "bar");

              case 3:
              case "end":
                return _context.stop();
            }
          }
        },
        bar,
        this
      );
    });
  }
}
```
**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/6045824/50137862-7d9a5000-02d7-11e9-9e52-406026374877.png)

**Comment by benjamn** [comment]
When I first implemented Regenerator, it made sense to assume the class transform would be used earlier in the Babel plugin pipeline, but I think it's probably time to revisit that assumption and make this work with native `class` syntax.

**Comment by dewelloper** [comment]
@benjamn iam not experienced with this so much, so in my opensource project regeneratior making those things to my code, like that

          while (1) {
            switch (_context14.prev = _context14.next) {
              case 0:
                _context14.next = 2;
                return _api.default.ajax.register.retrieve(data);

              case 2:
                response = _context14.sent;
                dispatch(handleRegisterProperties(response.json));

              case 4:
              case "end":
                return _context14.stop();
            }
          }
        }, _callee14);

What would you like to say with native class sytax. Should i change my include manners in my classes from import to require or what else, now it look like that
import Register from './register';

**Comment by nicolo-ribaudo** [comment]
@dewelloper He was saying that regenerator doesn't support generator methods in transpiled classes yet.
If you are affected by this bug, I suggest transpiling your classes for now. It it is a different problem, please open a new issue.
