### ISSUE TITLE
getProgramParent().traverse does nothing

### ISSUE THREAD

**Issue by ajcrites** [babel/babel#9208]
## Bug Report

**Current Behavior**
In cases where babel plugins are expecting to `getFunctionParent()` to return Program, babel suggests upgrading to [something like:](https://babeljs.io/docs/en/v7-migration-api#babel-traverse)

    func = path.scope.getFunctionParent() || path.scope.getProgramParent();

So far so good, but if you use `.traverse` on `getProgramParent()`, nothing seems to happen.

**Expected behavior/code**
For example, you can have a plugin like this:

```js
module.exports = function(babel) {
  return {
    ImportDeclaration() {
      path.scope.getProgramParent().traverse({
        ImportSpecifier() {
          console.log('program');
        }
      });

      path.traverse({
        ImportSpecifier() {
          console.log('path');
        }
      });
    }
  };
};
```

This will *only* emit `path` even though you would expect that you would traverse over the import specifier for the `program` as well.

**Environment**
- Babel version(s): v7
- Node/npm version: v11
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
As a workaround, you can use `path.scope.getProgramParent().path.traverse`
