### ISSUE TITLE
using babel directly from folder with projects

### ISSUE THREAD

**Issue by termitek12** [babel/babel#9211]
I don't know how to start from custom >project< folder that all files are in, and NOT from babel default SRC folder.

so u use:
npm run build

inside package.json file:

  "scripts": {
    "build": "babel --presets @babel/preset-es2015 SRC -d LIVE"
  },

any ideas?

**Comment by termitek12** [comment]
hmm if i put file name in

"scripts": {"build": "babel --presets @babel/preset-es2015 app.js -d LIVE"},

it is working fine... but how to conver all JS extension files (*) with subdirectories from THIS folder (that I have package.json and .babelrc files) ??

**Comment by nicolo-ribaudo** [comment]
You can use `.`, which means "this folder":
```
babel --presets @babel/preset-es2015 . -d LIVE
```

**Comment by termitek12** [comment]
thanks, DOT is exactly what I needed.
