### ISSUE TITLE
Typescript: Incorrect detection of sourceType (TSExportAssignment)

### ISSUE THREAD

**Issue by armano2** [babel/babel#9213]
## Bug Report

**Current Behavior**
Incorrect detection of sourceType in typescript

**Input Code**
- REPL or Repo link if applicable:

```ts
const foo = '';
export = foo;
```

**Expected behavior/code**
Resolved sourceType should be resolved to module..

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  sourceType: 'unambiguous',
  allowImportExportEverywhere: true,
  allowReturnOutsideFunction: true,
  ranges: true,
  plugins: [
    'jsx',
    'typescript',
    'objectRestSpread',
    'decorators-legacy',
    'classProperties',
    'asyncGenerators',
    'dynamicImport',
    'estree',
    'bigInt'
  ]
},
```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: 6-10
- OS: windows & linux 
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

Add node of type `TSExportAssignment` to detection.

**Comment by nicolo-ribaudo** [comment]
I'm not sure about that. Arent `export =` and `import foo =` syntax sugar for commonjs?

**Comment by armano2** [comment]
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

when used in typescript (tsc) its defining sourceType as module.

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/babel/babel/pull/15497
