### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by wmitsuda** [babel/babel#9214]
Just try to access https://babeljs.io/

Your SSL certificate seems to have expired on Dec 18th.

**Comment by xtuc** [comment]
I think it has been automatically renewed; I see that it expires on Friday, March 8, 2019 at 11:04:01 AM.

Could you please try again?

**Comment by wmitsuda** [comment]
Still not working, I've tried from both my computer and my phone, from different networks, I'm only getting the expired certificate. How is the website content served?

**Comment by wmitsuda** [comment]
Output from `http https://babeljs.io/`:

```
http: error: SSLError: HTTPSConnectionPool(host='babeljs.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1051)'))) while doing GET request to URL: https://babeljs.io/
```

**Comment by existentialism** [comment]
Looks fine to me?

![image](https://user-images.githubusercontent.com/56288/50296086-3af38780-043f-11e9-92e6-9190881f672c.png)

**Comment by wmitsuda** [comment]
It looks like some people are also getting the old certificate, see this tweet:

https://twitter.com/viniciussalvati/status/1075737054431100933

**Comment by wmitsuda** [comment]
Maybe something with the region? Both me and the guy from the tweet above are accessing it from Brazil.

**Comment by nicolo-ribaudo** [comment]
Does it work if you use a different browser or private navigation?

**Comment by wmitsuda** [comment]
Nope, I've tried also Firefox and incognito mode on chrome.

**Comment by hzoo** [comment]
Yeah it sounds like potentially just a region issue, not sure. FYI we use Netlify for the website (and for https)

**Comment by Wesitos** [comment]
Also getting the expired cerificate trying to access from Perú.

**Comment by BrendanBall** [comment]
I'm also getting it from south africa. I see it uses LetsEncrypt and the cert says 
```
Issued On	Wednesday, 19 September 2018 at 12:03:30
Expires On	Tuesday, 18 December 2018 at 12:03:30
```

**Comment by wmitsuda** [comment]
It is working fine now.
