### ISSUE TITLE
Babel --watch not working on Docker

### ISSUE THREAD

**Issue by theprobugmaker** [babel/babel#9215]
I'm using Babel 7 with a monorepo in Lerna and Yarn Workspaces with Docker but unfortunately `babel --watch` doesn't seem to being triggering on Docker.
In nodemon it's the same but they have a `-L` flag that supports Docker, what about Babel?

**Comment by 592da** [comment]
any solution ?

**Comment by JLHwung** [comment]
Babel cli under the hood uses chokidar to watch file changes, according to the [document](https://github.com/paulmillr/chokidar#performance), you can use
```
CHOKIDAR_USEPOLLING=true babel --watch
```
to instruct chokidar to use polling for files over network.

Given that this workaround exists, babel cli would not support extra chokidar watch options.
