### ISSUE TITLE
Export - cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by Balasnest** [babel/babel#9218]
## Bug Report

**Current Behavior**
Getting error saying that

> cannot read property 'default' of undefined
> Object.get [as API]

**Input Code**
```
repolib/index.js
-----------------

import * as components from './components';
import * as utils from './utils';

var Utils = {
  Logger: utils.Logger,
  Toast: utils.Toast
}

var Components = {
  Button: components.Button
}

module.exports = {
  Utils,
  Components,
}
Utils/Toast.js
---------------
var Toast = require('../repolib').Utils.Toast;
export default {
  ...(Toast)
}
API/loginAPI.js
-----------------
import Toast from '../Utils/Toast';
export default {
  login: () => {...}
}
API/index.js
----------------
import loginAPI from './loginAPI';
export default {
  loginAPI
}
common/index.js
-----------------
export { default as API } from '../API';
```

**Expected behavior/code**
Importing/exporting file should get data which is imported in the other files. Its was working with react native 0.54.0. 

**Actual behavior**
It's not working in react native 0.57.2

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.47

- Node/npm version: 6.4.1
- OS: 10.13.6
- Monorepo: NO
- How you are using Babel: cli

**Additional context/Screenshots**
![screenshot_1545308694](https://user-images.githubusercontent.com/6050520/50284858-65b20000-0480-11e9-8904-79277150940c.png)

**Comment by nicolo-ribaudo** [comment]
First of all, I suggest using the stable version of Babel (`@babel/core@^7.0.0`). You will also need to replace `babel-preset-react-native` (which is for Babel 6) with https://github.com/facebook/metro/tree/master/packages/metro-react-native-babel-preset (which is for Babel 7).

If it still doesn't work, cna you post the compiled output that throws that error?

**Comment by Balasnest** [comment]
@nicolo-ribaudo I am using the stable version only `@babel/core": "^7.0.0"` and replaced with `metro-react-native-babel-preset`. 

Do you have any idea of what causing this break?

**Comment by nicolo-ribaudo** [comment]
Could you share your webpack config and (I don't know if it is possible with react native) the webpack output around the like that throws?

As a quick possible fix, I suggest trying this config:
```json
{
  "presets": [
    ["module:metro-react-native-babel-preset", { "disableImportExportTransform": true }]
  ]
}
```

**Comment by Balasnest** [comment]
@nicolo-ribaudo Tried disabling `disableImportExportTransform` in babel config. But getting an error saying `Unexpected use of reserved word 'import'`.  I'm not using webpack config. This is happening in react native.

**Comment by erez-guesty** [comment]
any update?

**Comment by Balasnest** [comment]
@erez-guesty @nicolo-ribaudo 
 In the end, it turned out that we had a dependency cycle that was hard to spot. Once reorganized by files is started to work.
Some modules depend on others that depend back on the original. This was lead to cases like this, where the API object hasn't been initialized yet when our code tries to use it.
