### ISSUE TITLE
[Bug]: Decorators Conflict With Function Overloading

### ISSUE THREAD

**Issue by daniel-nagy** [babel/babel#9220]
## Bug Report

**Current Behavior**

When using **@babel/plugin-proposal-decorators** alongside **@babel/preset-typescript** [function overloading](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) does not work.

`TypeError: Duplicated element (nameOfOverloadedClassMethod)`

This is the transpiled output:

```javascript
{
  kind: "field",
  key: "nameOfOverloadedClassMethod",
  value: void 0
}, {
  kind: "field",
  key: "nameOfOverloadedClassMethod",
  value: void 0
}, {
  kind: "method",
  key: "nameOfOverloadedClassMethod",
  value: function value(_bar) {
    // actual body of method
  }
}
```

**Input Code**

```typescript
class Foo {
  nameOfOverloadedClassMethod(bar: string);
  nameOfOverloadedClassMethod(bar: number);
  nameOfOverloadedClassMethod(bar) {
    // some implementation
  }
}
```

**Expected behavior/code**

The overloaded methods are removed when transpiling before decorators mangle the class.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  loader: 'babel-loader',
  options: {
    presets: [
      [
        '@babel/preset-env',
        {
          modules: false,
          useBuiltIns: 'usage'
        }
      ],
      '@babel/typescript'
    ],
    plugins: [
      ['@babel/plugin-proposal-decorators', {
        decoratorsBeforeExport: true
      }],
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-object-rest-spread',
      '@babel/plugin-transform-runtime',
      'angularjs-annotate'
    ]
  }
}
```

**Environment**
- Babel version(s): v7.2.0
- Node/npm version: Node 9.11.2
- OS: OSX 10.14.1
- Monorepo: no
- How you are using Babel: `loader`

**Comment by nicolo-ribaudo** [comment]
Does it work if you use `@babel/plugin-transform-typescript` instead of the preset? (Try placing it before or after the decorators plugin)

The problem here is that TypeScript should run before decorators.

**Comment by daniel-nagy** [comment]
I tried putting **@babel/plugin-transform-typescript** before and after **@babel/plugin-proposal-decorators** and I got the same result. I did confirm that if I remove **@babel/plugin-proposal-decorators** that function overloading transpiles correctly.

It seems that plugins sorta act on the AST in parallel. This was an enlightening read https://jamie.build/babel-plugin-ordering.html. According to the article,

> "[plugins] can also be written in a way where they beat other plugins in the race to a node."

So it seems the decorator plugin is beating the typescript plugin to class methods no matter what order it is in.

**Comment by daniel-nagy** [comment]
Actually, this issue is seems to be directly related to the linked PR in that article https://github.com/babel/babel/pull/5735.

**Comment by nicolo-ribaudo** [comment]
Hi! The decorators proposal has been completely rewritten and we are discontinuing maintenance of the 2018-09 version (which will then be completely removed in Babel 8). You can migrate to the Stage 3 version of the [proposal](https://github.com/tc39/proposal-decorators/) by using `version: "2021-12"`.
