### ISSUE TITLE
[Doc]：what is the behaviour about modules in babel-preset-env

### ISSUE THREAD

**Issue by radicalviva** [babel/babel#9221]
Hi, recently I read the docs about [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env#modules)
I have a question about module
![image](https://user-images.githubusercontent.com/15885774/50327810-7b303400-052b-11e9-9a4c-a2c3d9899b7a.png)
I want to know what is auto ?
And Another question is that If I set the module: commonJS or I use this plugin: [transform-modules-commonjs](https://babeljs.io/docs/en/next/babel-plugin-transform-modules-commonjs.html)
I want to know any difference?
Thank you very much :)

**Comment by nicolo-ribaudo** [comment]
`auto` means "If the library which called Babel has support for esmodules (e.g. babel-loader or rollup-plugin-babel), then output them as-is; if it doesn't, then transform them to commonjs".

The `commonjs` option value internally uses `transform-modules-commonjs`, so using the plugin is the same thing but with more config :slightly_smiling_face: I'd recommend doing it only if, for some reason, the version of the plugin which comes with preset-env doesn't work for you.
