### ISSUE TITLE
try it out can't use

### ISSUE THREAD

**Issue by renyuns** [babel/babel#9223]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
![image](https://user-images.githubusercontent.com/22095724/50334333-eafde900-0542-11e9-9aa3-9cdb5d009b3d.png)

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
Can you try clearing cache and cookies?

**Comment by renyuns** [comment]
> Can you try clearing cache and cookies?

Other navigation can be used, but only this one can't. This happened in the last two days.
I cleaned up the cache and forced refresh was useless.

**Comment by renyuns** [comment]
It seems like this problem. A JS file can't be found. (https://unpkg.com/babel-standalone@6.26.0/index.js)
![image](https://user-images.githubusercontent.com/22095724/50334810-6c09b000-0544-11e9-9a17-c2adb08aa171.png)
![image](https://user-images.githubusercontent.com/22095724/50334822-6f9d3700-0544-11e9-9ded-db9954152fd9.png)

**Comment by renyuns** [comment]
@nicolo-ribaudo ok, thanks

**Comment by nicolo-ribaudo** [comment]
Could you expand the `Name` and `Initiator` columns in the devtools? I'm not able to reproduce this, so I'll need a bit of help from you.

**Comment by nicolo-ribaudo** [comment]
@babel-bot 	Move to babel/website
