### ISSUE TITLE
babel-helpers - es3 support

### ISSUE THREAD

**Issue by sormy** [babel/babel#9226]
## Bug Report

**Current Behavior**

`babel-helpers` package is using keywords that are reserved in es3, so even if target is set to es3 it is still not producing the valid es3 code.

**Input Code**

Any React code.

**Expected behavior/code**

It should produce es3 compatible code.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  compact: false,
  presets: [
    // transform-function-name is breaking React 0.14.x: '_renderedComponent' is null or not an object
    ['@babel/preset-env', { targets: ['IE 7'], loose: true /* es3 */, exclude: ['transform-function-name'] }],
    ['@babel/preset-react', { development: true }],
    ['@babel/preset-typescript', { isTSX: true, allExtensions: true }]
  ],
  plugins: [
    ['@babel/proposal-class-properties', { loose: true /* es3 */ }],
    ['@babel/proposal-object-rest-spread', { loose: true /* es3 */ }],
    'transform-es3-member-expression-literals', // es3
    'transform-es3-property-literals',          // es3
    'add-react-displayname',
  ]
}
```

**Environment**

- Babel version(s): 7.1.6
- Node/npm version: Node 8
- OS: dev: macOS, runtime: Windows CE 7 + Internet Explorer 7 Mobile (zebra MC32 hand scanner)
- Monorepo: ?
- How you are using Babel: as a transform plugin with rollup

**Possible Solution**

Simple fix:

```diff
diff -ur helpers.old/lib/helpers.js helpers/lib/helpers.js
--- helpers.old/lib/helpers.js	2018-12-13 20:51:50.000000000 -0500
+++ helpers/lib/helpers.js	2018-12-13 20:52:17.000000000 -0500
@@ -47,7 +47,7 @@
   export default function _createRawReactElement(type, props, key, children) {
     if (!REACT_ELEMENT_TYPE) {
       REACT_ELEMENT_TYPE = (
-        typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")
+        typeof Symbol === "function" && Symbol["for"] && Symbol["for"]("react.element")
       ) || 0xeac7;
     }
 ```

**Additional context/Screenshots**

N/A

**Comment by milesj** [comment]
Curious, do you really have to support IE7/ES3?

**Comment by sormy** [comment]
Yes, Zebra MC32 hand scanners with windows CE 7 and Internet Explorer 7 Mobile

**Comment by milesj** [comment]
@sormy Sorry to hear that :P

**Comment by sormy** [comment]
So, would you accept PR for this change? If yes, I will submit a PR.

**Comment by nicolo-ribaudo** [comment]
Yes :+1:

**Comment by sormy** [comment]
helpers code is not going through presets so this issue can't be fixed with es3 preset
