### ISSUE TITLE
@babel/polyfill was published yesterday without pushing browser.js

### ISSUE THREAD

**Issue by PWKad** [babel/babel#9227]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

In version 7.0.0 there was a file, browser.js, which was distributed when published.

**Input Code**
- REPL or Repo link if applicable:
https://github.com/babel/babel/blob/master/packages/babel-polyfill/scripts/postpublish.js#L7
```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

Re-publish the polyfill package with the browser.js file.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
Fixed in v7.2.5. Sorry for the inconvenience!
