### ISSUE TITLE
ERROR in ./main.js Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by fa6oomawad** [babel/babel#9229]
## Bug Report

**Current Behavior**
when i try to run the command **npm start** i get that error  :
ERROR in ./main.js Module build failed (from ./node_modules/babel-loader/lib/index.js),
although i tried multiple solutions i found here but nothing seems to work with me yet !! 

**Expected Behavior**
opens localhost with **Hello world!!!**

**Input Code**

**App.js** 
```
import React, { Component } from 'react';
class App extends Component{
   render(){
      return(
         <div>
            <h1>Hello World</h1>
         </div>
      );
   }
}
export default App;
```

**main.js**

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.js';

ReactDOM.render(<App />, document.getElementById('app'));
```

**index.html**

```
<!DOCTYPE html>
<html lang = "en">
   <head>
      <meta charset = "UTF-8">
      <title>React App</title>
   </head>
   <body>
      <div id = "app"></div>
      <script src = 'index_bundle.js'></script>
   </body>
</html>

```

**Babel Configuration (.babelrc, package.json, cli command)**

**package.json**
```
{
  "name": "fourth",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --mode development --open --hot",
    "build": "webpack --mode production"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.11"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "babel-loader": "^8.0.4",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.28.1"
  }
}
```

**webpack.config.js**

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
   entry: './main.js',
   output: {
      path: path.join(__dirname, '/bundle'),
      filename: 'index_bundle.js'
   },
   devServer: {
      inline: true,
      port: 8081
   },
   module: {
      rules: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
               presets: ['es2015', 'react']
            }
         }
      ]
   },
   plugins:[
      new HtmlWebpackPlugin({
         template: './index.html'
      })
   ]
}
```

**.babelrc**
```
{
   "presets":[
  "@babel/preset-env", "@babel/preset-react"]
}
```

**Environment**
- Node/npm version:  Node 10.14.2 (x64)
- OS: Windows 10

**Additional context/Screenshots**

**here is a screenshot for the error on cmd** 

![capture](https://user-images.githubusercontent.com/39637255/50370416-ff0e0e80-0573-11e9-8c37-c2d1e5ffd249.PNG)

**Comment by nicolo-ribaudo** [comment]
1. Remove `query` from the loader config, some you are already using babelrc. Also, those are v6 plugins.
2. `npm i -D @babel/preset-react`

**Comment by fa6oomawad** [comment]
it workkkked !!! 
i removed the query and run the command , these versions are so confusing specially when you r new with them like me lol 
thanq so much @nicolo-ribaudo

**Comment by fa6oomawad** [comment]
it workkkked !!!
i removed the query and run the command , these versions are so confusing specially when you r new with them like me lol
thanq so much @nicolo-ribaudo
