### ISSUE TITLE
Typescript: Inconsistent properties in TS function like nodes [parser, estree]

### ISSUE THREAD

**Issue by armano2** [babel/babel#9231]
## Bug Report

**Current Behavior**
Ast structure is inconsistent for function like nodes. 

### requested change
- property `params` should be renamed to `parameters`
- property `typeAnnotation` should be renamed to `returnType` if used as return type

### affected nodes
 - `TSCallSignatureDeclaration`
 - `TSConstructSignatureDeclaration`
 - `TSFunctionType`
 - `TSConstructorType`
 - `TSMethodSignature`

**Input Code**
```ts
interface A {
  (a: string): string
  new(a: string): string
}
```

Other function like nodes (FunctionExpression, ArrowFunctionExpression, FunctionDeclaration, ....) have properties:
- `typeParameters`
- `params`
- `returnType`

**Estree**

https://github.com/estree/estree/blob/master/extensions/type-annotations.md#functions

**Environment**
- Babel version(s): 7.2.3
- Node/npm version: 6-11
- OS: win/linux
- Monorepo: no
- How you are using Babel: cli

**Comment by thorn0** [comment]
@nicolo-ribaudo Please consider adding this issue to https://github.com/babel/babel/milestone/16
