### ISSUE TITLE
when @babel/polyfill is used with webpack 5 it throws a ReferenceError: global is not defined

### ISSUE THREAD

**Issue by capaj** [babel/babel#9232]
## Bug Report

**Current Behavior**
on startup, I get the ReferenceError

```
index.js:25 Uncaught ReferenceError: global is not defined
    at Object.../node_modules/@babel/polyfill/lib/index.js (index.js:25)
    at __webpack_require__ (bootstrap:22)
    at fn (hot module replacement:64)
    at Module../src/index/globals-import.ts (error-handler.js:37)
    at __webpack_require__ (bootstrap:22)
    at fn (hot module replacement:64)
    at Module../src/index/index.js (globals-import.ts:15)
    at __webpack_require__ (bootstrap:22)
    at bootstrap:47
    at bootstrap:47
```

**Expected behavior/code**
no ReferenceError is thrown

**Environment**
- Babel version(s): "@babel/polyfill": "^7.2.5"
- Node/npm version: Node 8/npm 6.4.1
- OS: ubuntu
- Monorepo: `no`
- How you are using Babel: [`loader`]

I understand that I probably should just provide a `global` and that could mitigate the startup issue, but I also wanted to ask why?
Isn't babel polyfill primarily targeted at old browsers? Why is it that it relies on `global` to bootstrap itself when it's obviously not going to be there? Unless using webpack 1-4 obviously....

**Comment by nicolo-ribaudo** [comment]
I think that this has something to do with the fact that webpack 5 doesn't polyfill any node feature (i.e. `global`) by default anymore.

**Comment by andersk** [comment]
The [documentation recommends](https://babeljs.io/docs/en/babel-polyfill#usage-in-node-browserify-webpack) using `@babel/preset-env` with the [`useBuiltIns`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) option set to `'entry'` or `'usage'`. In that case the top-level `@babel/polyfill` module isn’t used and this bug doesn’t appear.

We should still fix `@babel/polyfill`, but at least the `useBuiltIns` workaround is something you might want to be doing anyway.
