### ISSUE TITLE
Decorators throws TypeError in some mobile phones.

### ISSUE THREAD

**Issue by akira-cn** [babel/babel#9234]
## Bug Report

**Current Behavior**

Use method decorators may throws error:

```bash
TypeError: Cannot redefine property: name
```
The function's name property is not configurable in some mobile phone's browsers.

such as:

- vivo x7Plus (Android 5.1.1）
- vivo x6sa （Android 5.1.1)
- oppo R831（Android 4.3）

**Input Code**

```js
function mydecorator(elementDescriptor) {
    return elementDescriptor;
}

class Foo() {
    @mydecorator
    bar() {
    }
}
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: [Node 9/npm 5]
- OS: [OSX 10.13.2]
- Monorepo: [no]
- How you are using Babel: [`cli`, `loader`]

**Possible Solution**

```js
function _createElementDescriptor(def) {
  var key = toPropertyKey(def.key);
  var descriptor;

  if (def.kind === "method") {
    descriptor = {
      value: def.value,
      writable: true,
      configurable: true,
      enumerable: false
    };
    try {
      delete def.value.name;
      Object.defineProperty(def.value, "name", {
        value: _typeof(key) === "symbol" ? "" : key,
        configurable: true
      });
    } catch(ex) {
      // warn(...)
    } 
...
```

**Comment by justinfagnani** [comment]
Seeing this error too on older browsers like Chrome 41.
