### ISSUE TITLE
Changed Map's JSON.stringify in babel 7

### ISSUE THREAD

**Issue by darkowic** [babel/babel#9236]
# v7 Regression

> First check out: https://babeljs.io/docs/en/v7-migration
> Also a partial upgrade tool: https://github.com/babel/babel-upgrade

**Potential Commit/PR that introduced the regression**
If you have time to investigate, what PR/date introduced this issue.
https://github.com/babel/babel/issues/4990

**Describe the regression**
In babel 7 the way how `JSON.stringify` works with `Map` object is different than for babel 6 (and 7 beta.37) even with the same presets.

I did git bisect in my project and the regression was found in commit upgrading babel to version 7.0 (from `7.0.0-beta.37`)

**Input Code**

Babel 6 and Babel 7.0.0-beta.37
```js
const test = new Map([['test', 1]])

console.log('hello', JSON.stringify(test))
```
![babel_6](https://user-images.githubusercontent.com/11510581/50398427-d0f91c00-0777-11e9-8900-b3d30d7a43f0.png)

With babel 7.0 `JSON.stringify(test)` will return `{}`. Link to codesandbox.io (based on create-react-app with babel 7) https://codesandbox.io/s/6jljkkm8nn

**Babel Configuration (.babelrc, package.json, cli command)**
Default from https://babeljs.io/en/repl and stage-0

```js
{
  "plugins": [
    "babel-plugin-styled-components",
        // Stage 0
    "@babel/plugin-proposal-function-bind",

    // Stage 1
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    ["@babel/plugin-proposal-optional-chaining", { "loose": false }],
    ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
    ["@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false }],
    "@babel/plugin-proposal-do-expressions",

    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-transform-async-to-generator",
    "@babel/plugin-transform-classes",
    "@babel/plugin-proposal-json-strings"
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "modules": false
      }
    ],
    "@babel/preset-react"
  ],
}
```

Browserslistrc
```
> 1% in DE
safari>=10
iOS>=10
not ie>0
```

**Expected behavior/code**
The `JSON.stringify` behavior not change.

**Environment**
- Babel version(s): [v7.1.0]
- Node/npm version: [Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo [e.g. no]
- How you are using Babel: [`register`, `loader`]

**Comment by zloirock** [comment]
[This proposal](https://github.com/DavidBruant/Map-Set.prototype.toJSON) rejected.

**Comment by darkowic** [comment]
Oh :/ Do you think it is missing in babel 7 upgrade notes? Or when
upgrading should I check more babel dependencies changelogs?

pon., 24 gru 2018, 12:40: Denis Pushkarev <notifications@github.com>
napisał(a):
