### ISSUE TITLE
BabelJS Cannot find module 'babel-plugin-syntax-jsx'

### ISSUE THREAD

**Issue by SanjayBanjade** [babel/babel#9237]
I recently updated my project. I did `ncu -a` to upgrade package.json and did `npm i -g webpack-cli --save-dev` and `npm i webpack-cli --save-dev`.

After that I did `babel-upgrade --write --install`. However, I am getting the following error:
```
    Error: [BABEL] /vue-project/src/main.js: Cannot find module 'babel-plugin-syntax-jsx' (While processing: "/vue-project/node_modules/babel-plugin-transform-vue-jsx/index.js")
```

Then did `npm i --save babel-plugin-transform-vue-jsx` which gave me the following errors:
````
    These dependencies were not found:
    
    * @babel/runtime/helpers/asyncToGenerator in ./src/store/modules/menu.js, ./src/store/modules/model.js and 10 others
    * @babel/runtime/helpers/defineProperty in ./src/store/modules/menu.js, ./src/store/modules/model.js and 11 others
    * @babel/runtime/helpers/objectDestructuringEmpty in ./src/store/modules/schema.js, ./src/store/modules/apiurl.js
    * @babel/runtime/helpers/objectSpread in ./src/store/modules/menu.js
    * @babel/runtime/helpers/slicedToArray in ./src/store/modules/builder.js
    * @babel/runtime/helpers/toConsumableArray in ./src/store/modules/menu.js
    * @babel/runtime/regenerator in ./src/store/modules/menu.js, ./src/store/modules/model.js and 10 others
````
How do I fix this?

**Comment by nicolo-ribaudo** [comment]
What is your babel config?

**Comment by luniks** [comment]
Seems that plugin 'babel-plugin-transform-vue-jsx' does not support babel 7 for now.

**Comment by nicolo-ribaudo** [comment]
Looking at the source code it seems that it does :thinking:

**Comment by luniks** [comment]
The latest published version, on npm registry, is 3.7.0 which use bazel 6.26 ...
Support of bazel 7 seems to come with version 4.x, which has not been published yet.

**Comment by existentialism** [comment]
Looks published to me?

https://unpkg.com/babel-plugin-transform-vue-jsx@4.0.1/

**Comment by luniks** [comment]
@existentialism Your right 👍 
I didn't find it with a regular `npm search` because the **latest** tag pointed to **3.7.0** version. My bad !
```
$ npm show babel-plugin-transform-vue-jsx author version dist-tags
author = 'Evan You'
version = '3.7.0'
dist-tags = { latest: '3.7.0', next: '4.0.1' }
```

Thanks for the feedback !

**Comment by luniks** [comment]
@SanjayBanjade You can try with `npm i -D babel-plugin-transform-vue-jsx@4.0.1`

**Comment by nicolo-ribaudo** [comment]
@SanjayBanjade Is this still a bug?
