### ISSUE TITLE
[Help] transform-runtime & modules: false, not work good with commonJS module

### ISSUE THREAD

**Issue by SmileSmith** [babel/babel#9238]
## Bug Report

**Current Behavior**
Babel-plugin-transform-runtime insert ‘import’ code in commonJs module, when preset-env.modules = false.
```
import _typeof from "babel-runtime/helpers/typeof";
...
module.exports = foo;
```

**Input Code**
- REPL or Repo link if applicable:

```js
// My babelConfig
{
"presets": [ [ "babel-preset-env",{ "modules": false } ], "babel-preset-stage-2"],
"plugins": [ "transform-runtime" ],
}
// module A (esModule)
import * as B from './B';

// module B (commonJS)
module.exports = foo;

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
    "babel-core": "^6.26.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
```

**Environment**
- Babel version(s): [v6.26.3]
- Node/npm version: [Node 10.3/npm 6.4.0]
- OS: [OSX 10.13.4]
- Monorepo: [no]
- How you are using Babel: [`loader`]

**Possible Solution**
Delete modules= false will be ok, but it make tree-shaking invalid

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
That option only means that you don't want to transpile modules. Try setting `spurceType: "unambiguous"` (or better, `"script"` if it works for your usecase) in your Babel config.

**Comment by SmileSmith** [comment]
my workaround, mix with (esModule, commonJSModule)

it make other error.

```
 Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' 
```

**Comment by nicolo-ribaudo** [comment]
Did you get that error with `sourceType: "unambiguous"`? 🤔 Can you share the file which throws?

**Comment by SmileSmith** [comment]
@nicolo-ribaudo my early problem demo：
https://github.com/SmileSmith/Daily/tree/master/examples/webpack/20181201

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> (CommonJSModule.js:2)
    at Object.<anonymous> (CommonJSModule.js:16)
    at __webpack_require__ (bootstrap e24ef8cf95b64f7e4a8d:19)
    at Object.<anonymous> (index.js:4)
    at __webpack_require__ (bootstrap e24ef8cf95b64f7e4a8d:19)
    at bootstrap e24ef8cf95b64f7e4a8d:62
    at bootstrap e24ef8cf95b64f7e4a8d:62
```


![image](https://user-images.githubusercontent.com/17798955/50422882-91225980-0889-11e9-85c1-daf4a193b605.png)

**Comment by nicolo-ribaudo** [comment]
Oh, `unambiguous` is only supported in Babel 7. If you are using Babel 6, you need to different instances of Babel loader in your webpack config: une for esm files (with `sourceType: module`) and one for cjs files (with `sourceType: script`). You need to use webpack's test/include/exclude loader options to apply the correct config.

**Comment by nicolo-ribaudo** [comment]
Oh and `transform-runtime@6` is buggy so in the `script` case you'll need to set `modules: "commonjs"` in the preset-env config:

```js
[
            {
                test: /CommonJSModule\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: "babel-loader",
                        // remove {{ modules: false }} or {{ plugins: ["transform-runtime"] }} ,it work correct
                        options: {
                            presets: [
                                [
                                    "env",
                                    {
                                        modules: "commonjs"
                                    }
                                ],
                                "stage-2",
                            ],
                            plugins: ["transform-runtime"],
                            cacheDirectory: true,
                            sourceType: "script"
                        }
                    }
                ],
            },
            {
                test: /(ESModule|index)\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: "babel-loader",
                        // remove {{ modules: false }} or {{ plugins: ["transform-runtime"] }} ,it work correct
                        options: {
                            presets: [
                                [
                                    "env",
                                    {
                                        modules: false
                                    }
                                ],
                                "stage-2",
                            ],
                            plugins: ["transform-runtime"],
                            cacheDirectory: true,
                            sourceType: "module"
                        },
                    }
                ],
            }
        ]
```

**Comment by SmileSmith** [comment]
@nicolo-ribaudo tks, it work correct. :thumbsup:

**Comment by luobotang** [comment]
I have a similar problem,  @babel/preset-env insert "import" into CommonJS module.

I make a gist as demo:
<https://gist.github.com/luobotang/6a373a141bea8bc0f2fbdfadcb09841f>

I have to change config from:

```
useBuiltIns: 'usage'
```

to:

```
useBuiltIns: 'entry'
```

to solve this.

Maybe in the `useBuiltIns: 'usage'` mode, @babel/preset-env can detect the current module to decide use `import`(in ES module), or use `require()`(in CommonJS module).

**Comment by luobotang** [comment]
**AND** after tye the method of config `spurceType: "unambiguous"`, I found it's OK!

SO, JUST ADD `spurceType: "unambiguous"` TO BABEL CONFIG!
