### ISSUE TITLE
@babel/types wasn't released after being modified

### ISSUE THREAD

**Issue by cameron-martin** [babel/babel#9239]
## Bug Report

**Current Behavior**
https://github.com/babel/babel/pull/9110 modified the typescript generator for @babel/types. There have been several releases since this PR was merged (v7.2.3-v7.2.5). However, these versions were not released for @babel/types - [the most recent release is still v7.2.2](https://www.npmjs.com/package/@babel/types).

**Expected behavior/code**
I would expect a new version of @babel/types to be released after the typescript generator was modified.

**Comment by cameron-martin** [comment]
Presumably this is because the [scripts that generate the type definitions live outside of the package directory](https://github.com/babel/babel/tree/master/scripts/generators) and lerna is not detecting this package as changed since the last release.

If somebody can confirm that this is the issue, then I can send a PR to move the scripts into the package directory.

**Comment by nicolo-ribaudo** [comment]
> If somebody can confirm that this is the issue, then I can send a PR to move the scripts into the package directory.

Yes please!
