### ISSUE TITLE
Unable to resolve "core-js/modules/es7.promise.finally"

### ISSUE THREAD

**Issue by chrisirhc** [babel/babel#9241]
## Bug Report

As mentioned in https://github.com/babel/babel/issues/8297#issuecomment-418061728, when using `@babel/preset-env`, one can run into `Unable to resolve "core-js/modules/es7.promise.finally"`.

This is due to `core-js/modules/es7.promise.finally` not available in versions of core-js prior to 2.6:
https://github.com/babel/babel/blob/c586d4e8cac816941bf2ba559472fd9cc3150921/packages/babel-polyfill/package.json#L14

See https://github.com/zloirock/core-js/commit/ed59a9c0822eb1fa3509e06f996f424d8392d0a9 where it was introduced in core-js 2.6 .

**Current Behavior**
Using any code path that hits `es7.promise.finally` such as using built-ins in ES7 hits this error

**Input Code**
Unfortunately, I haven't come up with a minimal use case.

**Expected behavior/code**
Using the `es7.promise.finally` is successful.

**Environment**
- Babel version(s): preset-env@7.2.0, polyfill@7.0.0
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**
Users to add add core-js@2.6 to their devDependecies or yarn resolutions. Perhaps add this in workarounds.

---
Related to https://github.com/fusionjs/fusion-cli/issues/656

**Comment by zloirock** [comment]
It's available from [`core-js@2.5.0`](https://github.com/zloirock/core-js/releases/tag/v2.5.0).

**Comment by chrisirhc** [comment]
Thanks, my bad. Didn't realize that GitHub doesn't sort the version tags, it showed 2.6.0 as the earliest version tag.
