### ISSUE TITLE
t.templateLiteral does not automatically populate `cooked` from `raw`, no helpers available for conversion

### ISSUE THREAD

**Issue by coreyfarrell** [babel/babel#9242]
## Bug Report

**Current Behavior**
`t.templateLiteral({raw}, tail)` does not contain a `cooked` value.

**Input Code**
https://github.com/cfware/babel-plugin-template-html-minifier/commit/aa91d8cccbbf1a69f0eb9d396e6eef6bdf51178a

My babel plugin uses the `raw` value of quasi elements.  Babel does not provide any helper to convert between `raw` and `cooked` values for templateElement.  Per cfware/babel-plugin-template-html-minifier#10 lack of `cooked` creates a problem when transpiling for IE11 (I will post an update if I get a minimal reproduction repo).

**Expected behavior/code**
A way to create a templateElement when only `cooked` or `raw` is known should be possible.

**Babel Configuration (.babelrc, package.json, cli command)**
I don't have the specific babelrc, I will provide once I get an update from the reporter of the bug on my plugin.

**Environment**
- Babel version(s): ^7.0.0
- Node/npm version: node 10.14.2, npm 6.4.1
- OS: Fedora 28
- Monorepo: no
- How you are using Babel: webpack

**Possible Solution**
`t.templateElement` could automatically populate `cooked` from `raw`, or `raw` from `cooked` if only one option is provided.  Alternatively a helper function to convert between `raw` and `cooked` would be helpful.

**Comment by web-padawan** [comment]
The configuration which I am using and where the original error was reproduced can be found here:
web-padawan/polymer3-webpack-starter#22

Especially, it relies on `webpack-babel-multi-target-plugin` and the relevant part of config is there: https://github.com/web-padawan/polymer3-webpack-starter/blob/ca2c579c6026a94e62e6fbc73335a07bde33043f/webpack.config.js#L89

**Comment by jaydenseric** [comment]
I'm working on a new version of [`babel-plugin-syntax-highlight`](https://github.com/jaydenseric/babel-plugin-syntax-highlight), and finding it very tricky indeed to set the right `raw` and `cooked` values when creating a new `templateElement`.

A regular string needs to be converted into a template literal, but it may contain characters like `` ` ``  that need to be backlash escaped. Essentially, a `raw` value needs to be derived from a `cooked` one. This is my work in progress:

```js
const sourceString = '`'

types.templateLiteral(
  [
    types.templateElement(
      {
       // Add a backslash before every backslash or backtick.
        raw: sourceString.replace(/\\|`/g, '\\$&'),
        cooked: sourceString
      },
      true
    )
  ],
  []
)
```
