### ISSUE TITLE
Using solidus/backslash with pipe in template string produces only a pipe

### ISSUE THREAD

**Issue by edge** [babel/babel#925]
Babel compiles this ES6 code:
```js
let a = `|`;

let b = `\|`;

let c = `\\|`;
```
to this:
```js
"use strict";

var a = "|";

var b = "|";

var c = "\\|";
```

I've taken a look through the spec draft, and I didn't see anything about escaping pipes.

![Bug](http://i.imgur.com/TxhlKwD.png)

Other raw strings work fine.

![Working](http://i.imgur.com/Q9iwGOh.png)

As it stands, there seems to be no way to produce `\|` with a template string.

**Comment by neVERberleRfellerER** [comment]
@edge `\n` is valid escape sequence (newline). `\\|` is also valid escape sequence (it is backslash followed by pipe). `\|` is nothing. Also, you are interchanging string contents and what it is printed as: try `console.log(`\\|`)`.

**Comment by edge** [comment]
Thanks, you're right. My mistake. Closing.

**Comment by edge** [comment]
Thanks, you're right. My mistake, closing.
