### ISSUE TITLE
@babel/traverse: can't traverse Property using path.traverse with AST parsers different then @babel/parser

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#9251]
## Bug Report

**Current Behavior**
`@babel/traverse` dot not traverse `AST`-nodes `Property` of `ObjectPattern` generated by different parsers then `@babel/parser` using `path.traverse`.

**Input Code**
- REPL or Repo link if applicable:

As an example I used, `acorn`, `espree` and `cherow`. All of them use `Property` instead of `ObjectProperty` in `ObjectPattern`. There is a `fix` visitor that renames `Property` to `ObjectProperty` and with this fix everything works as expected. 

```js
const espree = require('espree');
const babel = require('@babel/parser');
const cherow = require('cherow');
const acorn = require('acorn');

const traverse = require('@babel/traverse').default;

const source = `
    const {a} = obj;
`;

const babelAST = babel.parse(source);
const cherowAST = cherow.parse(source);
const acornAST = acorn.parse(source)
const espreeAST = espree.parse(source, {
    ecmaVersion: 6,
});

const visitor = {
    enter(path) {
        if (path.type !== 'ObjectPattern')
            return;

        path.traverse({
            noScope: true,
            Property(path) {
                console.log('Property: only get here using babel');
            },
            ObjectProperty(path) {
                console.log('ObjectProperty: only get here using babel');
            },
        });
    }
};

const fix = {
    enter(path) {
        if (path.type !== 'Property')
            return;

        path.node.type = 'ObjectProperty';
    },
};

// uncoment to make things work as expected
//traverse(cherowAST, fix);
//traverse(espreeAST, fix);
//traverse(acornAST, fix);

traverse(babelAST, visitor);
traverse(cherowAST, visitor);
traverse(acornAST, visitor);
traverse(espreeAST, visitor);
```

**Expected behavior/code**
Would be great if `path.traverse` works the same way when `Property` used, because other parsers uses this name instead of `ObjectProperty` according to [estree standard](https://github.com/estree/estree/blob/master/es2015.md#objectpattern).

**Babel Configuration (.babelrc, package.json, cli command)**

```
npm i @babel/parser @babel/traverse acorn espree cherow
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]` latest`
- Node/npm version: [e.g. Node 8/npm 5] node `v11`
- OS: [e.g. OSX 10.13.4, Windows 10]: linux
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`] as a `parser`

**Possible Solution**

As I undestand there is an [aliases](https://github.com/babel/babel/blob/v7.2.5/packages/babel-traverse/src/visitors.js#L13) but they work only for method `enter` of a `visitor` but not for `path.traverse`, maybe this part should be fixed.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by oyilmaztekin** [comment]
I suppose it would be better if you could open this issue as a future, not the bug.

**Comment by elevatebart** [comment]
I seem to have the same issue with Litteral as Property, StringLitteral is aliased as Litteral even in the parsed ast.

**Comment by nicolo-ribaudo** [comment]
In the jan-14 meeting we discussed about this issue. Supporting both our AST format and ESTree would be incompatible with our current plugins ecosystem, since plugins don't know what to do with a `Property` or a `Literal`. We might consider switching back to the ESTree ast format, but there is a problem: ESTree mainly specifies standard features, so we would have to invent our own nodes for experimental features. This would lead again to differences in the long term.

Our parser's `estree` plugin is only needed for `babel-eslint`.

If you have an ESTree AST and you need to traverse it using Babel, we reccomend converting the AST using a tool like @coderaiser's https://github.com/coderaiser/estree-to-babel

**Comment by elevatebart** [comment]
Hello @nicolo-ribaudo , 
My problem is actually the standard parse -> traverse -> generate all using babel.

When I parse a `let a = 'test'` I get am ast containing a `Literal` node. if I try to traverse it I cannot reference it using the StringLiteral demanded by traverse. When I try to write code from the node itself, babel gets lost as well.

here is no emergency here since tehere is a workaround but it is worth noting.

**Comment by nicolo-ribaudo** [comment]
I don't get any `Literal` node for that code :thinking: 	

```js
{
  "type": "VariableDeclaration",
  "start": 0,
  "end": 14,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 1,
      "column": 14
    }
  },
  "declarations": [
    {
      "type": "VariableDeclarator",
      "start": 4,
      "end": 14,
      "loc": {
        "start": {
          "line": 1,
          "column": 4
        },
        "end": {
          "line": 1,
          "column": 14
        }
      },
      "id": {
        "type": "Identifier",
        "start": 4,
        "end": 5,
        "loc": {
          "start": {
            "line": 1,
            "column": 4
          },
          "end": {
            "line": 1,
            "column": 5
          },
          "identifierName": "a"
        },
        "name": "a"
      },
      "init": {
        "type": "StringLiteral",
        "start": 8,
        "end": 14,
        "loc": {
          "start": {
            "line": 1,
            "column": 8
          },
          "end": {
            "line": 1,
            "column": 14
          }
        },
        "extra": {
          "rawValue": "test",
          "raw": "'test'"
        },
        "value": "test"
      }
    }
  ],
  "kind": "let"
}
```

**Comment by elevatebart** [comment]
Oh !!!! my Big mistake, I was using the estree plugin of @babel/parser... apologies
