### ISSUE TITLE
Performance tradeoffs

### ISSUE THREAD

**Issue by harrysolovay** [babel/babel#9254]
I'm working on a node app that needs to extract require/import statements out of some source. I'm planning to use Cherow for parsing the source into an AST (forums such as [this one](https://news.ycombinator.com/item?id=15334763) lead me to believe that it has better performance). Given that I don't need plugins, Cherow should do the trick.

As for traversal and code generation, I'm unsure of what the fastest packages available are. I was wondering if someone could speak to the performance of @babel/traverse and @babel/core?... I haven't been able to find any definitive answer as to what I should use as the building blocks of my compiler. Any help would be greatly appreciated.

Thank you!!!

**Comment by hzoo** [comment]
This is late so you probably already picked something, but if you're use case is only for import/export there might be specific tools you can use just for parsing that (like even a regex at that point) if you want speed. Babel may give you flexibility but will be inherently slower
