### ISSUE TITLE
v7 Regression: Different behavior of babel-preset-env around whether Edge 15 needs destructuring to be transpiled

### ISSUE THREAD

**Issue by rmacklin** [babel/babel#9255]
# v7 Regression

**Describe the regression**
I’ve noticed that while upgrading a project to babel 7, which includes replacing the old `babel-preset-env@1.7.0` package with the newer `@babel/preset-env@7.2.3`, the set of transforms applied for the `edge 15` browser target changed.

Before the upgrade, destructuring was not being transpiled, but after the upgrade it is being transpiled (unexpectedly).

**Input Code**

```js
function foo({ a, b }) {
  return a + b;
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

This is the configuration passed to `babel-preset-env` / `@babel/preset-env`:
```js
targets: {
  browsers: ['edge 15']
}
```

**Output**

Output using babel 6.2.6 and babel-preset-env 1.6.2 [(REPL)](https://babeljs.io/en/repl.html#?babili=false&browsers=chrome%2064&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUBvRBDANIgI0QF8BKRDAKEUQCcBTKEWpbRAakIG5Lig&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2):
```js
"use strict";

function foo({ a, b }) {
  return a + b;
}
```

Output using babel 7.2.2 and preset-env 7.2.3 [(REPL)](https://babeljs.io/repl/build/master#?babili=false&browsers=edge%2015&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUBvRBDANIgI0QF8BKRDAKEUQCcBTKEWpbRAakIG5Lig&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.2.2&envVersion=7.2.3):

```js
"use strict";

function foo(_ref) {
  let a = _ref.a,
      b = _ref.b;
  return a + b;
}
```

**Expected behavior/code**

I expected the output code using babel 7 to be the same as when using babel 6. That is, I didn't expect that upgrading to babel 7 would start transpiling destructuring for Edge 15.

**Environment**
- Babel version(s): See REPL links
- Node/npm version: N/A see REPL links
- OS: N/A see REPL links
- Monorepo: N/A see REPL links
- How you are using Babel: N/A see REPL links

**Comment by rmacklin** [comment]
I came across https://github.com/babel/babel/pull/9140/files which adds `"edge: 18"` to the `transform-destructuring` configuration in `babel-preset-env/data/plugins.json`, and if I change the configured browser target to `edge 18`, it goes back to not transpiling destructuring. However, I’d like to understand why it wasn’t being transpiled originally when using babel 6 and babel-preset-env 1.6.x or 1.7.0.

How does babel-preset-env use caniuse data, and in particular, how that has changed since babel-preset-env was its own package outside the monorepo (i.e. version <= 1.7.0)?

Ideally, I’d like to be able to upgrade the project I'm working on to babel 7 without changing the transpiled output and without changing the browsers list, but running into this issue makes that impossible. Thus, I’d like to understand what’s different in the newer versions of the env preset so that I can make the right decision about whether to accept different transpilation output or modify the browsers configuration.

**Comment by nicolo-ribaudo** [comment]
We had to enable that transpilation because of https://github.com/babel/babel/issues/8349
