### ISSUE TITLE
Transpiled classes do not use Symbol.toStringTag

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel#9256]
## Bug Report

**Current Behavior**
Similar to #2470, use of `Object.prototype.toString` on an instance of a class does not contain the constructor name.

**Input Code**
```js
class Hmm {}
const hmm = new Hmm();

console.log(Object.prototype.toString.call(hmm)); //-> "[object Object]"
```

**Expected behavior/code**
```js
console.log(Object.prototype.toString.call(hmm)); //-> "[object Hmm]"
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: 6.4.1
- OS: macOS 10.14.2
- Monorepo: no
- How you are using Babel: babelify

**Possible Solution**
```js
if (typeof Symbol === 'function' && Symbol.toStringTag) {
    Hmm[Symbol.toStringTag] = 'Hmm';
}
```

If I understand correctly, though, this will produce inconsistent runtime results between browsers with a native `Symbol.toStringTag` and those with a polyfill/shim.

**Comment by zloirock** [comment]
It's expected behavior. For your class, you should add `@@toStringTag` by yourself.

**Comment by stevenvachon** [comment]
Why would I add it myself when it's expected ES2015 behaviour?

**Comment by zloirock** [comment]
If you don't think so - please, add a link to related part of the spec.

**Comment by nicolo-ribaudo** [comment]
You can test it in any modern browser: the correct output is `[object Object]`.
