### ISSUE TITLE
_interopRequire && _esModule

### ISSUE THREAD

**Issue by u9520107** [babel/babel#926]
last I checked, babel 4.5.5 in node doesn't have __esModule set to true, but 4.6.3 has __esModule set to true. So currently _interopRequire would attempt to return "default", which ends up to be undefined.

Transpiled es6 import would get transpiled into 
```
var babel = _interopRequire(require("babel"));
console.log(babel); //undefined
```

**Comment by sebmck** [comment]
Please see #908.
