### ISSUE TITLE
@babel/plugin-proposal-decorators doesn't support kind: "initializer"

### ISSUE THREAD

**Issue by tjcrowder** [babel/babel#9260]
## Bug Report

**Don't know if this should be a bug report or a feature request.** Apologies if it should be the latter, but since the plugin is out there... I couldn't find an existing bug report for this either.

**Current Behavior**
At present, trying to create a `kind: "initializer"` element descriptor (added in November in [PR#165](https://github.com/tc39/proposal-decorators/pull/165)) causes an error:

> TypeError: An element descriptor's .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "initializer"

**Input Code**

```js
"use strict";

function example(ed) {
    console.log(`converting ${ed.key} to initializer`);
    return {
        kind: "initializer",
        placement: "own",
        initializer() {
            console.log("initializer ran");
        }
    };
}

class Foo {
    @example x = 1;
}

new Foo;
```

(Can't provide REPL link since the plugin requires an option, and the REPL doesn't have a means of setting options AFAIKT.)

**Expected behavior/code**
Expected the initializer to run and for `x` not to be created on the instance.

**Babel Configuration (.babelrc, package.json, cli command)**

`.babelrc`:
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "chrome": "70"
        }
      }
    ]
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {"decoratorsBeforeExport": false}],
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-private-methods"
  ]
}
```

`package.json`:

```json
{
  "name": "decorators-bugreport",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "babel src -d lib"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/plugin-proposal-decorators": "^7.2.3",
    "@babel/plugin-proposal-private-methods": "^7.2.3",
    "@babel/preset-env": "^7.2.3"
  }
}
```

Built using `npm run build`.

**Environment**
- Babel version(s): v.7.2.3 for everything except `@babel/core`, which is v7.2.2
- Node/npm version:Node 11.3.0/npm 5.3.0
- OS: Linux Mint
- Monorepo: No
- How you are using Babel: `cli`

As always, thank you for the work you do on Babel and the plugins. Hope to help at some point.

**Comment by nicolo-ribaudo** [comment]
We are implementing it at https://github.com/babel/babel/pull/9008 (but it is blocked by https://github.com/babel/babel/pull/9166)

**Comment by mweststrate** [comment]
Note that this issue title is outdated (but the concern still valid), as the feature has been renamed per https://github.com/tc39/proposal-decorators/pull/199, which is being implemented in: https://github.com/babel/babel/pull/9360/files

**Comment by nicolo-ribaudo** [comment]
Closing because of the proposal changes
