### ISSUE TITLE
scope.rename with renamed re-export

### ISSUE THREAD

**Issue by mischnic** [babel/babel#9266]
## Bug Report

**Current Behavior**
Running this visitor on the input code
```js
{
  FunctionDeclaration(path) {
    path.scope.rename(path.node.id.name, "a")
  }
}
```
renames the reexport as well:
```js
function a() {
  return "YES";
}export { a as x };

export { a as someFunction } from './lib2.js';
```

**Input Code**
```js
export function x() {
  return "YES";
}

export { x as someFunction } from './lib2.js'
```

**Expected behavior/code**
The identifier `x`  in the export specifier has nothing to do with the function named `x`. Renaming the function should **not** affect the re-export.
```js
function a() {
  return "YES";
}export { a as x };

export { x as someFunction } from './lib2.js';
```

**Babel Configuration (.babelrc, package.json, cli command)**

Tested in https://astexplorer.net/

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: -
- OS: -
- Monorepo: -
- How you are using Babel: astexplorer.net

**Comment by mischnic** [comment]
A crude fix (if there is no bug deeper in babel): (`path.parentPath.parent.source` is used to determine re-exports)
```diff
diff --git a/packages/babel-traverse/src/scope/lib/renamer.js b/packages/babel-traverse/src/scope/lib/renamer.js
index cdfd9081..6ec401e6 100644
--- a/packages/babel-traverse/src/scope/lib/renamer.js
+++ b/packages/babel-traverse/src/scope/lib/renamer.js
@@ -3,8 +3,13 @@ import splitExportDeclaration from "@babel/helper-split-export-declaration";
 import * as t from "@babel/types";

 const renameVisitor = {
-  ReferencedIdentifier({ node }, state) {
-    if (node.name === state.oldName) {
+  ReferencedIdentifier(path, state) {
+    const { node } = path;
+    if(t.isExportSpecifier(path.parent) && path.parentPath.parent.source !== null){
+      return;
+    }
+
+    if (node.name === state.oldName && t.) {
       node.name = state.newName;
     }
   },
```

**Comment by devongovett** [comment]
Seems like the real issue is that `x` is in the `referencePaths` at all. `x` in the export specifier does not actually reference the local variable `x`.
