### ISSUE TITLE
Flow optional arguments don't have question mark stripped

### ISSUE THREAD

**Issue by thomasboyt** [babel/babel#927]
Flow supports optional arguments (see docs [here](http://flowtype.org/docs/functions.html#function-based-type-annotations)) with the following syntax:

```
function foo(bar?: number) {
}
```

This should get compiled to:

```
function foo(bar) {
}
```

However, Babel leaves in the question mark when stripping the type, as seen here: https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=function%20foo(bar%3F%3A%20number)%20%7B%0A%7D

**Comment by sebmck** [comment]
Fixed as of 4.6.4, thanks!
