### ISSUE TITLE
The method `inherits` of babel-helpers is not executed properly

### ISSUE THREAD

**Issue by cadleo** [babel/babel#9270]
## Bug Report

**Current Behavior**
@version7.2.0,emmmm,my english is so poor, [click here to view the source code](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L410)
```javascript

  import setPrototypeOf from "setPrototypeOf";
  export default function _inherits(subClass, superClass) {
    if (typeof superClass !== "function" && superClass !== null) {
      throw new TypeError("Super expression must either be null or a function");
    }
    // Here, it replaced the prototype of subClass, the origin prototype will be lost?
    // Here, it replaced the prototype of subClass, the origin prototype will be lost?
    // Here, it replaced the prototype of subClass, the origin prototype will be lost?
    // Important things should be repeated for 3 times,forgive my recklessness,thx
    subClass.prototype = Object.create(superClass && superClass.prototype, {
      constructor: {
        value: subClass,
        writable: true,
        configurable: true
      }
    });
    if (superClass) setPrototypeOf(subClass, superClass);
  }

```
React class-component will lose its all custom method of prototype when the source code transpiled from ES6 to ES5

**Comment by cadleo** [comment]
> You are correct that the original prototype is replaced, but it shouldn't have been used yet when the helper is executed, so it should not have any issues.

Thx,I have find the real problem,but I think maybe it is related to babel. In the npm package `dva`@2.4.1, 
the code of output-file `lib/dynamic.js` transpiled incorrect, it call `createClass` first,and then call `inherits`, and this leads to lose the original prototype of subClass, , is it a feature in babel 7?

**Comment by nicolo-ribaudo** [comment]
Why do you need the original prototype? The new one inherits from the original one, so any functionality will still be there.
