### ISSUE TITLE
@babel/preset-flow :: memo<PropTypes> not correctly handled/stripped by plugin

### ISSUE THREAD

**Issue by alexgurr** [babel/babel#9272]
## Bug Report

**Current Behavior**
Doesn't remove the flow syntax on compile causing an error.

```ReferenceError: ProgressBarProps is not defined```

This typing is required by Flow. If it's not included it throws a Flow error:

```Missing type annotation for `P`. `P` is a type parameter declared in  function type [1] and was implicitly instantiated at call of `memo` [2].Flow(InferError)```

**Input Code**

```js
import React, { memo } from 'react';

type ProgressBarProps = {
    ...
};

function ProgressBar() {
    ...
}

export default memo<ProgressBarProps>(ProgressBar);
```

**Expected behavior/code**
Successful compilation/babel plugin stripping the props type.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "transform-class-properties",
    "babel-plugin-transform-dynamic-import"
  ],
  "presets": ["@babel/preset-flow", "@babel/preset-react", "@babel/preset-env"],
  "env": {
    "production": {
      "presets": ["minify"]
    }
  }
}

```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: 8.21
- OS: OSX @ latest
- Monorepo: no
- How you are using Babel: cli through jest

**Possible Solution**
Correctly handle this syntax

**Comment by alexgurr** [comment]
I've never had to use // @flow at the top of my files before. I have ```all=true``` in my .flowconfig.

**Comment by nicolo-ribaudo** [comment]
You can set `"all": true` as an option of the Babel flow preset.

**Comment by alexgurr** [comment]
Regardless, the file is being “flowified” as the rest of the flow annotations are handled, so the original problem is still a problem.

**Comment by nicolo-ribaudo** [comment]
The problem is that without `all`, valid JavaScript is parser as JavaScript. e.g. that line is
```js
export default (memo < ProgressBarProps) > ProgressBar;
```
You need somehow to tell Babel that that file isn't just "JavaScript with flow annotations" but something else: that is what the `all` option is for.

**Comment by alexgurr** [comment]
Legend, thanks a lot.
