### ISSUE TITLE
Spread transformation requires Symbol.iterator now

### ISSUE THREAD

**Issue by clshortfuse** [babel/babel#9277]
# v7 Regression

**Potential Commit/PR that introduced the regression**

https://github.com/babel/babel/commit/4da3f3bc64841e0b4b7906c6c26af73920264095

**Describe the regression**

Transformation of `Spread` now requires `Symbol`

**Input Code**

```js
const divElements = [...document.getElementsByTagName('div')];
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// from webpack:

module: {
  rules: [{
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    use: {
      loader: 'babel-loader',
      options: {
        presets: [
          ['@babel/preset-env'],
        ],
      },
    },
  }
}
```

**Expected behavior/code**

Before this commit, all you needed was a polyfill for `Array.from()`. Now `Symbol.iterator` is needed as well. This breaks IE11.

**Environment**
- Babel version(s): @babel/preset-env: 7.2.3,
- Node/npm version: 8.11.3 / 6.5.0
- OS: OSX 10.14.2
- Monorepo: ??
- How you are using Babel: webpack

If, for some reason we still need `Symbol.iterator`, perhaps we perform the `isIterable` check *AFTER* the prototype check for `[object Arguments]`. That way, requiring `Symbol.iterator` would be a last-ditch effort.

**Comment by zloirock** [comment]
#7646 fixes this case.

**Comment by nicolo-ribaudo** [comment]
Thank you for the bug report! We are tracking it at https://github.com/babel/babel/issues/7597, and there is a PR at https://github.com/babel/babel/pull/8947.

**Comment by clshortfuse** [comment]
@nicolo-ribaudo I'm not sure this is the same issue, or perhaps I'm just being too specific. #7597 `Symbol` entirely, which would also remove caveats for `Array destructuring` and `Array For Of`as listed in https://babeljs.io/docs/en/caveats

This is just talking about `Spread` specifically. If anything, I would say PR #8947 would fix this issue as well as #7597.

**Comment by nicolo-ribaudo** [comment]
I can leave this open if you prefer, just in case someone else has the same problem to avoid another issue.

**Comment by ljharb** [comment]
That PR only solved it for strings, not yet for arrays, or Maps or Sets (all builtins should work even without the presence of Symbol.iterator)

**Comment by nicolo-ribaudo** [comment]
Yeah sorry, I'm opening the new PR now.

**Comment by nicolo-ribaudo** [comment]
I'm leaving this open until the example in the original post works.

**Comment by nicolo-ribaudo** [comment]
The original example works when using the `allowArrayLike` option, or the upcoming (Babel 7.13.0) `arrayLikeIsIterable` assumption.
