### ISSUE TITLE
Promise is not defined when I use babel in android 4.4

### ISSUE THREAD

**Issue by Kerminate** [babel/babel#9279]
## Bug Report
In Android 4.4, I use babel6 but I got an error that Promise is not defined.

**Input Code**

```js
const Promise = new Promise();
```

**Expected behavior/code**
Promise should work fine.

**Babel Configuration (.babelrc, package.json, cli command)**
My package.json is like this:

```json
"dependencies": {
    "babel-runtime": "^6.26.0",
},
  "devDependencies": {
    "babel-core": "^6.4.5",
    "babel-loader": "^6.2.1",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-0": "^6.5.0"
  },
```

My .babelrc is like this:
```json
{
    "presets": [
        ["env", {
            "modules": false,
            "targets": {
                "browsers": ["> 1%", "last 2 versions", "Android >= 3.2", "not ie <= 8"]
            },
            "useBuiltIns": true
        }],
        "stage-0"
    ],
    "plugins": [
        "transform-runtime",
        ["import", {
            "libraryName": "vant",
            "libraryDirectory": "es",
            "style": true
        }]
    ],
    "comments": false
}
```

**Environment**
- Babel version(s): [babel6]
- Node/npm version: [Node 8.12.0/npm 6.4.1]
- OS: [OSX 10.14.2]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [`loader`]

**Possible Solution**

**Additional context/Screenshots**

**Comment by nicolo-ribaudo** [comment]
`"useBuiltIns": true` isn't valid; it should be `"useBuiltIns": "usage"`

**Comment by nicolo-ribaudo** [comment]
It is the expected behavior. That code is roughlty equivalent to this:

```js
const Promise = undefined;
Promise = new Promise();
```

If you try to run that line of code in any modern browser, you'll get the same error.
