### ISSUE TITLE
TypeError: Class constructor model cannot be invoked without 'new' after uninstalling babel

### ISSUE THREAD

**Issue by ekkatharisi** [babel/babel#9280]
## Bug Report

**Current Behavior**
i have a trouble using babel , and when i unistalling it to use just the ES5 , it shoots this error : 
TypeError: Class constructor model cannot be invoked without 'new'
this is my code :
**Input Code**
```js
        const fs = require('fs');
        const path = require('path'); 
        const Sequelize = require('sequelize');
        const basename = path.basename(__filename);
        const env = 'development';
        const config = require('../config/config')[env];

           const sequelize  = new Sequelize(config.database.database_name, config.database.username, 
           config.database.password, config.database.database_config);

      var db = {
         sequelize : sequelize,
         Sequelize : Sequelize
      };

        db.sequelize.authenticate().then(() => {
        console.log('database worked !!!');


    fs.readdirSync(path.join(__dirname,'models/')).filter(file => {
        return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
    }).forEach(file => {
        var model = db.sequelize.import(path.join(__dirname,"models/", file));
        //var model = require(path.join(__dirname,"models/", file))(sequelize, Sequelize);
        db[model.name] = model;
    });

       Object.keys(db).forEach(modelName => {
           if (db[modelName].associate) {
               db[modelName].associate(db);
          }
         } );
       db.sequelize.sync({force : true}).then(res => {
           console.log('database created !!!!!!!!!');
      }).catch(err => {
           console.log(err.stack);
     })
        }).catch(error => {
            console.log(error.stack);
       });
       module.exports = db;
```

please what i should do now ??

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 10.14.2/npm 6.4.1]
- OS: [Windows 10]
- How you are using Babel: [`cli`]

**Comment by nicolo-ribaudo** [comment]
Which lines doe throw that error?
Also, I'm not sure that I understood the question: your code works when if you use Babel but doesn't work without Babel?

**Comment by ekkatharisi** [comment]
thank you @nicolo-ribaudo for responding me, so the problem that i install BABEL in my laptop (and other pc), after that the console shoots this error in this line 
`        
         var model = db.sequelize.import(path.join(__dirname,"models/", file));
` 
after , i remove BABEL by this comande :
`
         npm uninstall babel-cli babel-preset-es2015 babel-preset-env
         npm uninstall -g babel-cli babel-preset-es2015 babel-preset-env
`
but the error still the same, what I want is to execute the code fine without this error.
NOTE 1: the error occurs when I use this command 
`node connect.js`
NOTE 2: I use node version 10.13.0.
the whole project is in [this repo](https://github.com/ekkatharisi/mailer)
thank you in advance.

**Comment by ekkatharisi** [comment]
but the sequelize modules are transpiled to es5, (have you see any es6 expression )
and no as i say i remove conmpletely BABEL , but the error still the same .
and thank you @nicolo-ribaudo for reference but i don't find the solution yet.

**Comment by TidyIQ** [comment]
I'm experiencing the same issue although as far as I'm aware it only occurs when I AM using babel (if I remove babel then none of my imports work so I can't run my app to check).

It's also occurring for me at sequelize.import()

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/8656
