### ISSUE TITLE
Babeljs.io REPL code conversion doesn't work with async functions due to `regeneratorRuntime` not being defined

### ISSUE THREAD

**Issue by josephrocca** [babel/babel#9283]
## Bug Report

The homepage of babeljs (babeljs.io) allows users to test out babel quickly by putting some code in the input and getting the resulting transformed (es5) code in the output box:

![image](https://user-images.githubusercontent.com/1167575/50733102-ebe97880-11da-11e9-9673-453ea7d3133e.png)

As you can see I've put this code in the input box:

```js
async function delayedHello() {
  await new Promise(r => setTimeout(1000, r));
  return "hello";
}
```
And as the output I get this:

```js
var delayedHello = function () {
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.next = 2;
            return new Promise(function (r) {
              return setTimeout(1000, r);
            });

          case 2:
            return _context.abrupt("return", "hello");

          case 3:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function delayedHello() {
    return _ref.apply(this, arguments);
  };
}();

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
```

But this code doesn't work because `regeneratorRuntime` isn't defined. Surely the tester REPL should actually produce code that works for something as common (in terms of user requirements) as `async` functions?

**Comment by nicolo-ribaudo** [comment]
Note that it works in the main repl (click on "Evaluate"): https://babeljs.io/repl/build/master#?babili=false&browsers=last%205%20versions%2C%20ie%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsIwCYFMA2wYu2AEgfugBQCUMA3gFAwzADuwqyMEubMABQBO6ALaoQuKkJgBeAHwxJyACqpRudAmTSANDACMABhM0aAbmat8uIToBEAeQDS9i1aG5kCIVnsALCnR7SwBfRkY8QmIyINpLIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017&prettier=false&targets=&version=7.2.2&envVersion=7.2.3
It is impossible to transform generators/async functions without pulling in a very big runtime helper: for this reason we ask users to either import it by theirselves or by using `@babel/transform-runtime`.

PS. The arguments of `setTimeout` are in the wrong order.

**Comment by josephrocca** [comment]
Fair enough, but which user of your REPL doesn't want that runtime helper? If the code doesn't work without it, then the REPL hasn't really done its job. I might just be a lost noob here though. Thanks for your reply in any case!

**Comment by nicolo-ribaudo** [comment]
The repl a demo that allows quick testing: you write your code, see the result and click on "Evaluate".
If you want to compile your app you'll need to install Babel.
