### ISSUE TITLE
Element instanceof EventTarget

### ISSUE THREAD

**Issue by theMatthes** [babel/babel#9289]
## Bug Report

**Current Behavior**
Ok, this is a rather complicated issue.
When I try to do for example ```document.body instanceof EventTarget```, it doesn't work in IE.

**Environment**
- Babel version(s): 7.2.0
- How you are using Babel: In the browser (Chrome)

**Possible Solution**

Replace it with something IE knows (like ```typeof(document.body.addEventListener) === 'undefined'```)

**Comment by nicolo-ribaudo** [comment]
That is out of scope for the main Babel project, since it only focuses on ECMAScript. I suggest you to write your own plugin.
