### ISSUE TITLE
Babel escape report  "Duplicate declaration", but typescript have not the error

### ISSUE THREAD

**Issue by relign** [babel/babel#9291]
## Bug Report
![image](https://user-images.githubusercontent.com/13749042/50773242-4a8e1f80-12cb-11e9-80a0-69724dc263ef.png)

**Environment**
- Babel version(s): v7.2.2
- Node/npm version: 9.6.0
- OS
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
Thank you for the bug report! We are tracking it at https://github.com/babel/babel/issues/7943
