### ISSUE TITLE
Babel minor upgrade introduce inline helpers

### ISSUE THREAD

**Issue by pascalduez** [babel/babel#9297]
## Bug Report

**Current Behavior**
Upgraded our preset dependencies to the latest minor, so from `7.1.6` to `7.2.3`. 
In our snapshot tests I noticed a huge amount of inline helpers added. 

I couldn'f find a real hint or help from the changelog, although I understand quite some stuff changed at the class, class-properties level. But hey, it's a minor...

**Input Code**

Please see [this MR](https://github.com/Gandi/babel-preset-gandi/pull/12) for the diffs.
Our [preset setup](https://github.com/Gandi/babel-preset-gandi/blob/master/index.js).  

**Environment**
- Babel version(s): `7.2.3`
- Node version:`10.12.0`
- npm version:`6.5.0`
- OS: Ubuntu Linux
- Monorepo: no
- How you are using Babel: [`api`, `cli`, `loader`]

**Possible Solution**
Switching order of plugin, seems to bring back the same compilation output.
But I'm not sure this is the desired output?  
 
So from 
```
let plugins = [
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-proposal-class-properties',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-transform-runtime', runtimeOpts],
];
```
to
```
let plugins = [
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    '@babel/plugin-proposal-class-properties',
    ['@babel/plugin-transform-runtime', runtimeOpts],
];
```

Input
```
@decorated
class A {}
```
output
```
"import _classCallCheck from \\"@babel/runtime-corejs2/helpers/esm/classCallCheck\\";

var _class;

var A = decorated(_class = function A() {
  _classCallCheck(this, A);
}) || _class;"
```

**Comment by loganfsmyth** [comment]
Would you be able to make a small self-contained example?

**Comment by pascalduez** [comment]
@loganfsmyth Here we go https://github.com/pascalduez/babel-9297

**Comment by nicolo-ribaudo** [comment]
As stated in the docs (https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babel-plugin-proposal-class-properties), if you are using legacy decorators that plugin must come _before_ the `class-properties` plugin: that is why the second configuration work.

Probably we should throw an error instead of transforming decorators following the current spec, that is what happened with your setup.

**Comment by nicolo-ribaudo** [comment]
A side note: by default, the code generated by transform-runtime needs to be compatible with `@babel/runtime@^7.0.0`: for this reason, if we create a new helper it will be directly injected in your code, without `import`ing it. You can avoid it by specifying the version of `@babel/runtime` that you are using:

```js
["@babel/transform-runtime", { "version". "7.2.0" }]
```

**Comment by pascalduez** [comment]
@nicolo-ribaudo Thanks a bunch for the explanations!
Yeah somehow I missed the plugins documentation while upgrading to Babel 7 :\
