### ISSUE TITLE
Documentation not updated for #8167

### ISSUE THREAD

**Issue by Worthaboutapig** [babel/babel#9298]
## Bug Report

Further to issue [#8167](https://github.com/babel/babel/issues/8167), apparently the valid formats for `targets` has changed, but as far as I can see the documentation has not been updated to reflect this. The documentation I'm looking at is [@babel/preset-env](https://babeljs.io/docs/en/next/babel-preset-env.html#browserslist-integration), it may be in other places too.

As I understand it the options `string | Array<string>` are no longer supported, is this right?

**Current Behavior**
The behaviour has been updated, but the documentation does not reflect this and claims options that are not supported.

**Expected behavior/code**
The documentation should be up-to-date

**Possible Solution**
Update the docs

**Comment by existentialism** [comment]
@Worthaboutapig @hzoo's comment was correct at the time, but support for targets as a string was added later (https://github.com/babel/babel/pull/8509).

We have tests that cover the various ways to declare targets:

https://github.com/babel/babel/tree/master/packages/babel-preset-env/test/fixtures/preset-options/targets-as-object

https://github.com/babel/babel/tree/master/packages/babel-preset-env/test/fixtures/preset-options/targets-as-string

**Comment by Worthaboutapig** [comment]
@existentialism Thanks, should it be working in v7.2.3? Because that's the one I have it not working in.  It's going through `@vue/babel-preset-app`, though, which has a dependency on `"@babel/preset-env": "^7.0.0"`

**Comment by existentialism** [comment]
Yep, it should work.

Can you put up an example repo where it's not?
