### ISSUE TITLE
Unexpected identifier with babel-node in windows only

### ISSUE THREAD

**Issue by vanZeben** [babel/babel#9301]
## Bug Report

**Current Behavior**
In Windows 10, when running a babel-node from a package.json file, babel-node reports gives the following error, note that this works as intended with the same source in OS X and some other Windows instances
```
(function (exports, require, module, __filename, __dirname) { import app from "../app";
                                                                    ^^^^^
SyntaxError: Unexpected identifier
   at new Script (vm.js:79:7)
   at createScript (vm.js:251:10)
   at Object.runInThisContext (vm.js:303:10)
   at Module._compile (internal/modules/cjs/loader.js:657:28)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
   at Module.load (internal/modules/cjs/loader.js:599:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
   at Function.Module._load (internal/modules/cjs/loader.js:530:3)
   at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
   at Object.<anonymous> (C:\Users\Ken\gv6\typecast\node_modules\@babel\node\lib\_babel-node.js:234:23)
```

This *only* happens when running babel-node through the package.json file and hitting `node_modules/.bin/babel-node` in a cmd-prompt works as expected.

This is only happening in some windows instances and OS X is fine.

**Input Code**
package.json: 
```
{
    "name": "typecast",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "start": "babel-node ./src/server/entry.ts --extensions '.ts'",
        "build:server": "babel src -d dist --extensions \".ts\"",
    },
    "dependencies": {
        "@babel/cli": "^7.2.3",
        "@babel/core": "^7.2.2",
        "@babel/node": "^7.2.2",
        "@babel/plugin-proposal-class-properties": "^7.2.3",
        "@babel/plugin-proposal-json-strings": "^7.2.0",
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/plugin-syntax-import-meta": "^7.2.0",
        "@babel/plugin-transform-object-assign": "^7.2.0",
        "@babel/plugin-transform-template-literals": "^7.2.0",
        "@babel/polyfill": "^7.2.5",
        "@babel/preset-env": "^7.2.3",
        "@babel/preset-react": "^7.0.0",
        "@babel/preset-typescript": "^7.1.0",
        ...
    },
    "devDependencies": {
        "tslint": "^5.11.0",
        "tslint-config-prettier": "^1.14.0",
        "typescript": "^3.2.1",
        ...
    }
}
```

./src/server/entry.ts
```
import app from "../app";

app.set("port", config.EnvConfig.port || 3000);
app.listen(config.EnvConfig.port);
```
 
**Expected behavior/code**
I am expecting babel-node to process the typescript file properly. Also note that building out the typescript files with `babel src -d dist --extensions \".ts\"` works as intended.

**Babel Configuration (.babelrc, package.json, cli command)**
.babelrc at root of the project
```js
{
    "presets": [
        ["@babel/preset-env", {
            "targets": {
                "browsers": [">0.2%"]
            },
            "modules": "commonjs",
            "useBuiltIns": "usage"
        }], "@babel/preset-react", "@babel/preset-typescript"
    ],
    "ignore": ["node_modules"],
    "plugins": ["@babel/plugin-syntax-dynamic-import", "@babel/plugin-syntax-import-meta", "@babel/plugin-proposal-class-properties", "@babel/plugin-proposal-json-strings", "@babel/plugin-transform-template-literals"]
}
```

**Environment**
- Babel version(s): v7.2.2
- Node/npm version: Node v10.15.0/NPM v6.4.1 
- OS: Windows 10
- Monorepo: no
- How you are using Babel: cli & loader

**Possible Solution**
My suspicion is that the `.babelrc` file is not being loaded or its being processed as a different directory, however I attempted to specify an absolute path with the --config-file option to no avail

**Comment by MaximeHeckel** [comment]
@vanZeben I'm getting the same issue on a linux based OS. Did you find a solution to this?

**Comment by vanZeben** [comment]
> @vanZeben I'm getting the same issue on a linux based OS. Did you find a solution to this?

After about 2 days of debugging, yeah I did. From what I recall, it was `"start": "babel-node ./src/server/entry.ts --extensions '.ts'",` the single quotes in the `--extensions '.ts'` need to be explicitly defined as double quotes. For some reason the single quotes were the cause.

**Comment by kunver400** [comment]
Same issue windows 10.

**Comment by vidhu** [comment]
Looks like to be a bug with commander parsing CLI arguments. 
I console.log the `extensions` args here on line 66:
https://github.com/babel/babel/blob/master/packages/babel-node/src/_babel-node.js#L66

```
program.option(
  "--root-mode [mode]",
  "The project-root resolution mode. " +
    "One of 'root' (the default), 'upward', or 'upward-optional'.",
);
program.option("-w, --plugins [string]", "", collect);
program.option("-b, --presets [string]", "", collect);

program.version(pkg.version);
program.usage("[options] [ -e script | script.js ] [arguments]");
program.parse(process.argv);

console.log(program.extensions)
// ^^^^^^^^^^^^^^^^^^^
```

With double quotes, output is `[ '.ts', '.tsx' ]`
With single quotes, output us  `[ '\'.ts', '.tsx\'' ]` (it treats ts and tsx as a single string rather than 2 elements)

**Comment by JLHwung** [comment]
Unlike [Bourne shell](https://www.cs.ait.ac.th/~on/O/oreilly/unix/upt/ch08_14.htm), single quotes are not used at all by the cmd.exe command processor except [limited cases](https://stackoverflow.com/a/24181667/1490357). Therefore the following is expected to fail on Windows cmd.exe
```
babel-node ./src/server/entry.ts --extensions '.ts'
```

Closing this as it is out of babel scope.
