### ISSUE TITLE
parser: TypeScript: Parse error on abstract class with abstract method and optional methods in abstract/declare classes.

### ISSUE THREAD

**Issue by armano2** [babel/babel#9305]
## Bug Report

**Current Behavior**
Babel expect that abstract methods must have body, this is not a case for typescript. 
This is also issue for optional methods in abstract/declare classes.

```
SyntaxError: Unexpected token, expected "{"
```

**Input Code**
```ts
abstract class AbstractSocket {
    abstract createSocket(): Promise<string>;
}
```
```ts
abstract class AbstractSocket {
    createSocket?(): Promise<string>;
}
```
```ts
declare class Foo {
    bar?(): any;
}
```

**Expected behavior/code**
There should not be any parse errors

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  const babel = require('@babel/parser');
  const plugins: ParserPlugin[] = [
    'typescript',
    'objectRestSpread',
    'decorators-legacy',
    'classProperties',
    'asyncGenerators',
    'dynamicImport',
    'estree',
    'bigInt',
    'importMeta'
  ];
  if (jsx) {
    plugins.push('jsx');
  }

  return babel.parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins
  });
```

**Environment**
- Babel version(s):  7.2.3
- Node/npm version: 6-11
- OS: ----
- Monorepo: ---
- How you are using Babel: @babel/parser -> `parse`

**Comment by armano2** [comment]
@existentialism is it something what we want to support?

**Comment by RWOverdijk** [comment]
Please, yes. If anything, do it for eslint.

**Comment by nicolo-ribaudo** [comment]
This only happens when the `estree` plugin is enabled.

**Comment by RWOverdijk** [comment]
I don't think I'm using that plugin and I'm seeing the same happen. Does that mean eslint adds that?

**Comment by devongovett** [comment]
Should be fixed by https://github.com/babel/babel/pull/9890

**Comment by armano2** [comment]
can confirm its fixed
