### ISSUE TITLE
babel-generator arguments typeof null 

### ISSUE THREAD

**Issue by chlshown** [babel/babel#9307]
## Bug Report

**Current Behavior**

Module build failed: TypeError: Cannot read property 'auxiliaryCommentBefore' of null

beble-generator/lib/index.js line:47 and line:76

for unknown reason, soametimes Generator arguments:opt can be 'null', so when the code is running in line 76 when we need read some options by using opts.auxiliaryCommentBefore,the exception is happend.Maybe we should add some judgement of the arguments 'opt' with the type 'null'?

**Environment**
- babel-generator version(s): [6.26.1]
- Node/npm version: [8.11.3/5.6.0]

**Comment by nicolo-ribaudo** [comment]
Is the issue also present in Babel 7?
