### ISSUE TITLE
If it's obvious that find is invoked on jQuery, core-js/modules/es6.array.find shouldn't be included (required)

### ISSUE THREAD

**Issue by haqer1** [babel/babel#9308]
## Bug Report

**Current Behavior**
The unnecessary require call significantly increases the size of the output file: which results in unnecessary data traveling all over the web (originating from sites using Babel).

**Input Code**
E.g., find below is obviously invoked on jQuery, so array.find is not needed & is irrelevant:

```js
var jQueriedStuff = jQuery(MY_SELECTOR).find('.my-class[data-something="' +something+'"]');
```

**Expected behavior/code**
require("core-js/modules/es6.array.find") is completely redundant here, but it gets included even though it's quite obvious the call is made on jQuery.

**Babel Configuration (.babelrc, package.json, cli command)**
Same as in #9196.

**Environment**
Same as in #9196.

**Possible Solution**
I'm resorting to hacking Babel-generated file again, just as in #9196:
```xml
		<exec dir="${basedir}" executable="sed">
			<arg value="-ri "/>
			<arg value='/require\("core-js\/modules\/es6.array.find"\);/d'/>
			<arg value="src/main/webapp/include/js/compiled/generated/file.js"/>
		</exec>
```

**Additional context/Screenshots**
One perhaps could argue that sometimes it's not obvious that $ stands for jQuery (?). If that's the case, perhaps you can't always optimize find invoked on $(".selector"). But in this case, it's obvious because jQuery var is used, which by default should be treated as coming from the library provided by http://jquery.com/

**Comment by zloirock** [comment]
We can't be sure that `jQuery` does not return an array and can't add special cases for all possible libraries.

**Comment by zloirock** [comment]
About `$` - I know some libraries - jQuery replacement which adds `Array.prototype` to instance prototype chain for use `Array` methods.

**Comment by haqer1** [comment]
> We can't be sure that `jQuery` does not return an array and can't add special cases for all possible libraries.

IMHO, this is a wrong diagnosis of the issue: it doesn't matter what jQuery returns, it matters that find here is implemented by jQuery and including core-js/modules/es6.array.find is completely unnecessary in such cases (and in addition, the developers use it knowing that it will work for the relevant targeted browsers).

By closing such issues, you just ensure that some people like me who don't want to pollute the Internet will continue to have to hack Babel-generated files (as i mentioned in Possible Solution above).
Currently, by avoiding redundant 
core-js/modules/es6.array.find
inclusion i end up with file size being 3.1KB instead of 8.4KB. To me that matters: why would i want to pollute each page request with 5.3KB of unnecessary data traveling across the Internet. Similar situation & additional waste vs. optimization in #9196. I think Babel should care about such optimizations as well: it would reflect negatively on Babel's rep if it didn't IMHO.

**Comment by zloirock** [comment]
Feel free to add a magic logic which, by a statical analysis, could determinate that result of `jQuery` global method is not an instance of `Array`.

By comments like this, you discourage last desire to participate in the development of free software.

**Comment by haqer1** [comment]
> determinate that result of `jQuery` global (even not imported explicitly) method is not an instance of `Array`

This bug is specifically about https://api.jquery.com/find/: method documented as supported by jQuery & widely known as such. You don't need to know what that method returns: WHATEVER THAT IS it's handled by jQuery itself.

I state that IMHO Babel currently leads to pollution on the Internet (as well as unnecessary expenses in PaaS environments, for example, even if they might be unimportant for big companies) which in cases like this & #9196 is fairly easily avoidable.

P.S. By closing an issue like this 22 minutes after it was logged, without any discussion (!), & keeping up the same thing going after my next follow-up a week later, you've already made me add a filter for emails to babel@noreply.github.com: because that is not a constructive attitude, & i don't have time for that.
P.P.S. Having seen that Babel causes unnecessary increases in file sizes of my JS code, & given that my current project already uses a framework that involves a fairly big-size JS payload per page, i've decided to limit usage of Babel significantly, & i currently consider even that limited usage only acceptable with my hacks like the ones i've mentioned (https://github.com/babel/babel/issues/9308#issue-397769351 & https://github.com/babel/babel/issues/9196#issue-391560116) which remove some of the redundant & polluting stuff & make the file sizes closer to what they should be. To me that matters: i think by doing this i make my project & the Internet better.

**Comment by haqer1** [comment]
The following facts could be taken advantage of:
1. jQuery is in many if not absolute majority of cases used without importing it (let alone redefining it, let alone redefining it to a function returning an array).
	I.e., you could optimize cases in which it's not imported and redefined to return an array: this in fact would cover the majority of relevant cases (in fact probably all valid cases in the real world).
2. Param type in jQuery.find is in many if not absolute majority of cases a String (sometimes element or jQuery object), whereas for Array.prototype.find it is always a function.
https://api.jquery.com/find/
vs.
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/find
	I.e., you could start by optimizing only the cases where the param is a String: this in fact would cover many (IMHO, the majority) of relevant cases in the real world).
> ```js
> // a.js
> window.jQuery = () => [];
> ```

In light of the items 1. & 2. above, if this kind of code is detected, behavior could be left as it is now.
> ```js
> // b.js
> 
> import "a.js";
> 
> jQuery().find(() => {});
> ```

In light of the items 1. & 2. above, if this kind of code is (or a non-anonymous function name in the param) detected, behavior could be left as it is now as well.

A valid real-world example to start with could be with a String param, as in the OP. https://github.com/babel/babel/issues/9308#issue-397769351 To emphasize the String param aspect, i've added the following in the OP:
```js
const MY_SELECTOR = "#some\\:thing";
```
In fact, in many cases the param would be a literal, i.e., easier than my OP above.

P.S. As any human, or human-made engineering artifact, can be smarter, I'm just saying Babel can be smarter than it currently is.
P.P.S. To give a monetary implication, I once (recently) was presented a bill involving $15/MB of data for roaming abroad. In this context, extra 5,3KB/page means 8 U.S. cents of extra expense per page. Just some extra fruit for thought...
