### ISSUE TITLE
bug: exception with destructuring assignment with private fields

### ISSUE THREAD

**Issue by dnalborczyk** [babel/babel#9310]
## Bug Report

**Current Behavior**
`Invalid destructuring assignment target` exception with destructuring assignment with private fields

**Input Code**
- [REPL](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oGJQEsCmAdgC6rrTDwEREBOArsEfDQBQAON8bEAlCmRhbJyIfMQBc0IgAscEAHTZRhItAC-0ALzQOXXmTWpDQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=stage-3&prettier=false&targets=&version=7.2.2&envVersion=)

```js
class Foo {
  #client

  constructor(props) {
    ;({ client: this.#client } = props) // throws: Invalid destructuring assignment target
  }
}
```

transpiles to _(excerpt)_:
```js
({
  client: _classPrivateFieldGet(this, _client)  // notice the getter
} = props);
```

**Environment**
- Babel version: **v7.2.2**

_update_:

I suppose it would need to use **_classPrivateFieldSet** as well as transpile the ES2015 destructuring assignment? unless destructuring assignments work with a function call ... which I don't think it does?

```js
var client = props.client
_classPrivateFieldSet(this, _client, client);
```

for what it's worth: works in `node --harmony` **v11.6.0**

**Comment by nicolo-ribaudo** [comment]
We should transpile it by moving the private assignment after the destructuring.

**Comment by dnalborczyk** [comment]
then you'd need to rename the instance private field inside the destructuring to local scope as well I suppose?

```js
({ client: this.#client } = props)
```
becomes something like ...
```js
var _client
({ client: _client } = props)
_classPrivateFieldSet(this, _client, client)
```

**Comment by nicolo-ribaudo** [comment]
Yes :+1:
