### ISSUE TITLE
@babel/parser(ts): class with preceding keywords on different line

### ISSUE THREAD

**Issue by armano2** [babel/babel#9325]
## Bug Report

**Current Behavior**
Babel ignores new lines between class and keyword, typescript does not

https://github.com/Microsoft/TypeScript/blob/master/tests/cases/conformance/classes/classDeclarations/classAbstractKeyword/classAbstractSingleLineDecl.ts

**Input Code**
```ts
abstract
class B {}
```
```ts
declare
class B {}
```

**Expected behavior/code**
in body there should be 2 statements
- ExpressionStatement `abstract` and `declare` and 
- ClassDeclaration

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  const babel = require('@babel/parser');
  const plugins: ParserPlugin[] = [
    'typescript',
    'objectRestSpread',
    'decorators-legacy',
    'classProperties',
    'asyncGenerators',
    'dynamicImport',
    'estree',
    'bigInt',
    'importMeta'
  ];
  if (jsx) {
    plugins.push('jsx');
  }

  return babel.parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins
  });
```

**Environment**
- Babel version(s):  7.2.3
- Node/npm version: 6-11
- OS: ----
- Monorepo: ---
- How you are using Babel: @babel/parser -> `parse`

**Comment by armano2** [comment]
@nicolo-ribaudo is it something what we want to reproduce here from typescript?

i was planning to fix it.

**Comment by nicolo-ribaudo** [comment]
Yes :+1:
Do you want to open a PR? You can look at how we disallow the line terminator between `async function`.

**Comment by armano2** [comment]
i was planning to do it, but i found few issues in alignment tests in [typescript-estree](https://github.com/JamesHenry/typescript-estree/pull/123) which i have to address first
