### ISSUE TITLE
Setting exports.__esModule without setting "default" property so undefined is exported. 

### ISSUE THREAD

**Issue by nicksrandall** [babel/babel#933]
The file that I am looking at is `lib > babel > api > register > node.js`.

On line 69, `exports.__esModule = true;`  is problematic because it says that this module is an es6 module but we haven't defined a "default" property to be exported. 

I will submit a pull request that will fix this error.

**Comment by neVERberleRfellerER** [comment]
@nicksrandall 
There is no need for default property. This file is supposed to be imported as
```
import * as something from "./lib/babel/api/register/node.js";
```
Read
https://github.com/babel/babel/issues/908

**Comment by nicksrandall** [comment]
Sorry, I just read that. Please close this issue.
