### ISSUE TITLE
...rest of object-rest-spread contains picked value

### ISSUE THREAD

**Issue by Xiphe** [babel/babel#9332]
## Bug Report

**Current Behavior**
When setting a value to an object using a dynamic + numeric key
The key is converted to a string (expected)
When I then use destructuring to receive the value it works using the numeric key
When I also take the `...rest` of the object
Then I expect the rest not to contain the previously destructured key

BUT the key is still present in the rest

**Input Code**
[REPL link (See console)](https://babeljs.io/repl#?babili=true&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBA1gUwJ4wLwwEwG4BQpKzQCGUCaMA3jANqJIC6AXDAOQBmIILANDAEZEATsxYCAXixgBfXPmiUadJjAAOAGwCuwOLwB0-wQnlTyxUrPDyq1AMpRBASzABzABR0AlMvVa4GPQZGUBjSplAkCBaQIGoIukQQEAiCUK44MDBQSCoIIGwwAPJ8AFYIwFC6dBCuZgge1AAM9Gio6CzQji486TAABgCiAB455QgAJjAAJBRFpeWVyNW19U0mUCD8ZEQwHU7OvTgeeJYxcQlJKWkZPtot6Dd-3D0Dw2WkE9MPaxt8ZJ-a2gwUgORwA9KCYAAVAAWDggMDYRAcaggjGO0Vi8USyVSPVmbwWSGqhmgHl0sRcUGhd0KJQJVVcJOCZIpzipTwyLxG7ymFAAUjYCgA5XS7FwONhIRlBDzfGAIACOGiIal5AuFovsewlUqZGFlIKAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Cstage-2%2Cbabili&prettier=false&targets=&version=6.26.0&envVersion=)

```js
const key = 2;
const state = { [key]: 'foo', bar: 'baz' };
const { [key]: pluck, ...rest } = state;
const { [String(key)]: pluck2, ...rest2 } = state;
console.assert(
  typeof Object.keys(state)[0] === 'string',
  `Expected ${Object.keys(state)[0]} to be a string`
)
console.assert(
  pluck === pluck2,
  `Expected ${pluck} to be ${pluck2}`
)
// This fails:
console.assert(
  Object.keys(rest).length === Object.keys(rest2).length,
  `Expected ${JSON.stringify(rest)} to equal ${JSON.stringify(rest2)}`
)
```

**Expected behavior/code**

1. The destructured key should not be contained in rest even if a numeric key is used for destructuring
2. The assertions in above code should not throw when code is transpiled with babel and evaluated

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["preset-stage-3"]
}
```

**Environment**
- Babel version(s): `v6.26.0` (REPL), `v7.2.2` (my machine)
- Node/npm version: Node 11.4.0/npm 6.4.1
- OS: MacOS 10.14.1
- Monorepo: 🤷‍♂️ 
- How you are using Babel: loader

**Additional context/Screenshots**
Works as expected in Chrome + Firefox Console

**Comment by nicolo-ribaudo** [comment]
What is your Babel 7 configuration? It works for me: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBA1gUwJ4wLwwEwG4BQpKzQCGUCaMA3jANqJIC6AXDAOQBmIILANDAEZEATsxYCAXixgBfXPmiUadJjAAOAGwCuwOLwB0-wQnlTyxUrPDyq1AMpRBASzABzABR0AlMvVa4GPQZGUBjSplAkCLh4liBqCLrAcUKuHhaQsfFqIG44MDBQSCoIIGwwAPJ8AFYIwFC6dBCuZgge1AAM9Gio6CzQji48uTAABgCiAB5FtQgAJjAAJBQV1bX1yI3NrR0mUCD8ZEQwfU7Owzge0elxulk5eT7aXegPftxDY5M1pHOLLzt7fDIv002gwUjOFwA9JCYAAVAAWDggMDYRAcaggjEuEAyN2yriGyy-ayQjUM0A8NwQLig8Ke5SqxIarnJwUpcRp8LeeQ-U2-CwoACkbGUAHK6Y4uBxsJAsoIef4wBAARw0RDUAuFYol9hO0tlrIwCohQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.2.2&envVersion=7.2.3

**Comment by existentialism** [comment]
Possibly related: https://github.com/babel/babel/issues/6341

**Comment by Xiphe** [comment]
yes, duplicate of #6341 sorry!

**Comment by existentialism** [comment]
@Xiphe no need to apologize, we should definitely look into making sure this gets resolved

**Comment by Xiphe** [comment]
I'm not able to reproduce the issue on babel@7.2.2 now 🤷‍♂️

**Comment by Xiphe** [comment]
I just updated to debug this, maybe it was a caching issue... Thanks for the help!
