### ISSUE TITLE
Babel 7.3.0

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#9334]
This is an experiment. Many projects uses issues to track progress on releases, lets see if it works for us.

### New features
- [x] Transform for the smart pipeline operator proposal (https://github.com/babel/babel/pull/9179)
- [x] Private Class Methods Stage 3: Private Accessors (https://github.com/babel/babel/pull/9101)
- [x] Named capturing groups in preset-env (https://github.com/babel/babel/pull/9345)

**Comment by hzoo** [comment]
We're publishing now so there might be some issues!

**Comment by kentcdodds** [comment]
Woo! Thanks 👏👏

**Comment by yoyo837** [comment]
Excuse me, have you missed to release `@babel/core` version 7.3.0 ?

**Comment by nicolo-ribaudo** [comment]
We only release changed packages; that one hasn't had any change

**Comment by hzoo** [comment]
Regressions/Fixes:

- https://github.com/babel/babel/pull/9377
- https://github.com/babel/babel/pull/9341
