### ISSUE TITLE
Trying to parse an Array-like object to array by [...nodeList] seems to be some issue

### ISSUE THREAD

**Issue by xiaoyuze88** [babel/babel#934]
Hi, there!

Today, when I'm trying to parse an Array-Like object to an array by :

    var nodeList = document.querySelectorAll('div');
    var array = [...nodeList];

Some error shown up. When I looked up the compiled code, I found out that babel compiled them to 

    var _toConsumableArray = function (arr) {
        if (Array.isArray(arr)) {
            for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i];
            return arr2;
        } else {
            return Array.from(arr);
        }
    };
    
    var nodeList = document.querySelectorAll("div");
    var array = [].concat(_toConsumableArray(nodeList));

As a `nodeList` is not an Array, the `_toConsumableArray` function will return `Array.from(arr)`. But `Array.from` is an ES6 function, then I got the `undefined is not a function` error in my Chrome.
Is this an issue, or am I not using it the right way?

Thanks!

**Comment by neVERberleRfellerER** [comment]
Take a look at caveats
https://babeljs.io/docs/usage/caveats/
You need polyfill for Array.from

**Comment by xiaoyuze88** [comment]
Got it! Thanks!

**Comment by shlomisas** [comment]
isn't do something like this it's enough?

`Array.prototype.slice.call(arguments)`

**Comment by jherax** [comment]
Seriously??? Babel is supposed to be used to transpile ES6+ to ES5. Why you guys uses ES6 features in the ES5 generated code???

It is as easy as `return Array.apply(null, arr)`
E.g. `Array.apply(null, document.querySelectorAll('p'))`

**Comment by loganfsmyth** [comment]
It is not that simple, spread is for arbitrary iterable types, not just arrays. And we use `Array.from` because we expect people to be loading `babel-polyfill` or using `transform-runtime`.
