### ISSUE TITLE
this.props is undefined if props are types with Flow as 'props: { ... }' inside classes

### ISSUE THREAD

**Issue by Foxhoundn** [babel/babel#9340]
## Bug Report

**Current Behavior**
Typing React props with flow inside classes results in `this.props` being undefined. Removing `props: Props` fixes the issue. I suppose the issue will also be present with `this.state`
**Input Code**
- REPL or Repo link if applicable:

```js
@connect(viewSelector)
@withModal()
@titleManager('Dashboard')
export default class Dashboard extends Component {
  props: Props; // <- Here, removing this fixes everything

  state: {
    chartTab: string,
    nodeTab: string,
    canLoadMoreRemotes: boolean,
  } = {
    chartTab: '1 hour band',
    nodeTab: Object.keys(this.props.system.cluster_info)[0],
    remotes: getSlicedRemotes(this.props.health.data.remote),
    canLoadMoreRemotes:
      this.props.health.data.remote && this.props.health.data.remote.length > 5,
  };

```

**Expected behavior/code**
No errors hopefully :)

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react", "@babel/preset-flow"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-class-properties"
  ],
  "ignore": ["/node_modules/"],
  "retainLines": true
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]: 7.2.3
- Node/npm version: [e.g. Node 8/npm 5] 8 / 5
- OS: [e.g. OSX 10.13.4, Windows 10] 10.14
- Monorepo: [e.g. yes/no/Lerna] no
- How you are using Babel: [e.g. `cli`, `register`, `loader`] loader

**Possible Solution**

**Additional context/Screenshots**
- I have updated our app from ancient stuff like webpack 1, babel 4 etc. It was working fine when used with the babel-strip-flow.... preset.

**Comment by nicolo-ribaudo** [comment]
It is the expected behavior per the current class fields proposal. Also, it is already tracked at https://github.com/babel/babel/issues/8417.

You can fix it using `props: Props = this.props`

**Comment by Foxhoundn** [comment]
> It is the expected behavior per the current class fields proposal. Also, it is already tracked at #8417.
> 
> You can fix it using `props: Props = this.props`

Thank you very much!
