### ISSUE TITLE
Partial Application syntax: Stage 1

### ISSUE THREAD

**Issue by byara** [babel/babel#9342]
> This proposal introduces a new syntax using the ? token in an argument list which allows you to partially apply an argument list to a call expression by acting as a placeholder for an argument.

## Info
Stage: 1
Champion: Ron Buckton (@rbuckton)
Proposal repo: https://github.com/tc39/proposal-partial-application

## Example
```javascript
const addOne = add(1, ?); // apply from the left
addOne(2); // 3

const addTen = add(?, 10); // apply from the right
addTen(2); // 12

// with pipeline
let newScore = player.score
  |> add(7, ?)
  |> clamp(0, 100, ?); // shallow stack, the pipe to `clamp` is the same frame as the pipe to `add`.

// partial template strings
const Diagnostics = {
  unexpected_token: `Unexpected token: ${?}`,
  name_not_found: `'${?}' not found.`
};
Diagnostics.name_not_found("foo"); // "'foo' not found."
```

## Basic Rules

- can be used one or more at the top level of the Arguments of a `CallExpression`, `CallMemberExpression`, or `SuperCall` (e.g. `f(?)` or `o.f(?)`)
- can be used in place of a `TemplateMiddleList`

## ESTree/Parsing

- I guess we can use the token `question`
- we can create a `Partial` node in `parseExprListItem` function

## Transform

We will add `Partial` node to the AST and it will be added to the spec.

**Comment by nicolo-ribaudo** [comment]
Please note that we aren't following the ESTree spec since it doesn't support proposals.

**Comment by byara** [comment]
> Please note that we aren't following the ESTree spec since it doesn't support proposals.

Thanks for pointing that out, I changed the main post.
