### ISSUE TITLE
Use both .babelrc and babel.config.js

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [babel/babel#9350]
In the current project, I am employing expo, react-native and babel-plugin-module-resolver.

As the b-p-m-r doesn't support babel.config.js, I have to add .babelrc.

But in babel.config.js, I have statement of api.cache(true), which I want to keep.

So my question is, what if I maintain babel.config.js with only api.cache(true) and set plugin in .babelrc, will it work or what will happen?

**Comment by nicolo-ribaudo** [comment]
Those configs will be merged, but `.babelrc` is only applied to the package which contains it: not to subpackages (in case of a monorepo) and not to node_modules.
