### ISSUE TITLE
How does Typescript parse customized syntax configured with babel?

### ISSUE THREAD

**Issue by tranvansang** [babel/babel#9353]
It has been known long ago that [babel supports typescript](https://babeljs.io/docs/en/babel-preset-typescript) via the `babel-preset-typescript`.

The work flow is something like

- `.ts` files are converted to `.js` file with type annotation removed by babel.

- Concurrently, typescript type-checks the `.ts` files via `tsc` command.

How does typescript understands (parses) many custom syntax configured with babel? For example: [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining)

Is anyway to make babel just compile the code from Typescript into Typescript with custom syntax parsed. For example, I want babel to convert this code

```
const a: number = foo?.bar
```

into
```
const a: number = (_foo = foo) === undefined && _foo.bar
```

instead of
```
const a = (_foo = foo) === undefined && _foo.bar
```

If babel can do that, I can freely add any language features as I want without waiting for Typescript support.

Another way would be letting typescript ignore custom syntax configured with babel, and just do the type check.
However, IMO babel is too flexible for typescript to handle its supported syntax.

---

* Slack Community Chat: https://babeljs.slack.com (you can sign-up at https://slack.babeljs.io/ for an invite)
* StackOverflow: https://stackoverflow.com/questions/tagged/babeljs using the tag `babeljs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/babeljs
* Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by milesj** [comment]
@tranvansang You cannot use experimental syntax/proposals within TypeScript, even though it's being compiled with Babel, and expect the type checker (`tsc`) to work. This is one of those areas where TS has to support it first.

**Comment by nicolo-ribaudo** [comment]
You could have two different builds:

1) Your normal build
2) A build without the TS preset which only transpiles experimental features not supported by tsc: this build can the be type-checked.

**Comment by tranvansang** [comment]
@milesj if that is the case, I don't see any advantage of integrating typescript to babel build over just using typescript only.

@nicolo-ribaudo I am interested by your second point. That is what exactly I want and asked in my question.

How do you configure the build that transpiles experimental features while preserving typescript type annotation?

By the way, IMHO, these kinds of things should be explicitly clarified in the docs.

**Comment by nicolo-ribaudo** [comment]
You can try something like this:

```js
module.exports = function (api) {
  const config = {
    plugins: ["@babel/plugin-proposal-feature-not-supported-by-typescript"],
    presets: [],
  };

  if (api.env("tsc")) {
    // Make Babel parse TS syntax without transforming it
    config.plugins.push("@babel/plugin-syntax-typescript");
  } else {
    config.plugins.push("@babel/plugin-already-supported-by-typescript");
    config.presets.push("@babel/preset-typescript");
  }

  return config;
};
```

If you want to typecheck your files you should then compile then using the `BABEL_ENV=tsc` env var.

**Comment by nicolo-ribaudo** [comment]
Yes, `-syntax-` plugins don't transform anything

**Comment by milesj** [comment]
@tranvansang Too utilize Babel, its plugins, and its entire community.
