### ISSUE TITLE
babel7 + vue 2.5.x + webapcak 4x  const /let not changge

### ISSUE THREAD

**Issue by lilingling3** [babel/babel#9357]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

* Slack Community Chat: https://babeljs.slack.com (you can sign-up at https://slack.babeljs.io/ for an invite)
* StackOverflow: https://stackoverflow.com/questions/tagged/babeljs using the tag `babeljs`
* Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/babeljs
* Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by existentialism** [comment]
@lilingling3 thanks for the issue! please fill out our issue template so we can help you with your issue!

A small repo that reproduces your problem will also help greatly!

**Comment by kausters** [comment]
I'm experiencing the same problem: after upgrading from Babel 7.1.2 to 7.2.3 it's no leaving uncompiled `let`s in my an imported package.

**Comment by nicolo-ribaudo** [comment]
package.json's `babel` key doesn't apply to imported packages. You need `babel.config.js`.

**Comment by kausters** [comment]
Huh that's news to me (also then why would it have worked with 7.1.2) but I'll definitely try that, thanks!

**Comment by nicolo-ribaudo** [comment]
Is this still an issue?

**Comment by kausters** [comment]
Not for me. Sorry I forgot to comment but yes, begrudgingly switching to `babel.config.js` solved the issue for good, thanks!
