### ISSUE TITLE
Object literal after short arrow doesn't compile right

### ISSUE THREAD

**Issue by elclanrs** [babel/babel#936]
This piece of code:
```javascript
var is = (t, x) => {}.toString.call(x).slice(8,-1) === t
```
Produces this incorrect output:
```javascript
var is = (function (t, x) {}).toString.call(x).slice(8, -1) === t; 
```
The following works though:
```javascript
var is = (t, x) => ({}).toString.call(x).slice(8,-1) === t
//                  ^ note parentheses
```

**Comment by sebmck** [comment]
No this is correct behaviour and follows the ES6 grammar correctly.

**Comment by elclanrs** [comment]
It is? Mmm, I guess I'm too used to CoffeeScript where it does work.

**Comment by eventualbuddha** [comment]
The reason it works in CoffeeScript is because it uses indentation to denote a block, whereas JS uses curly braces. So any place in JS where either an object expression or a block statement may appear would be ambiguous without having parentheses around the curly braces.

**Comment by fkling** [comment]
> So any place in JS where either an object expression or a block statement may appear would be ambiguous without having parentheses around the curly braces.

And if there are no parenthesis, JS usually interprets the braces as block.
