### ISSUE TITLE
Native classes cannot be extended by transpiled classes

### ISSUE THREAD

**Issue by vzaidman** [babel/babel#9367]
## Bug Report

**Current Behavior**
I'm building the library [@welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render) where I transpile the code:
```
class WDYRPatchedClassComponent extends ClassComponent{
  ...
}
```
Where `ClassComponent` is provided by the user.

For the code transpiling I use `@babel/preset-env` with default target which means plugins are used including `babel-plugin-transform-classes`.

If a user provides a native class in case his app is transpiled for latest browsers without `babel-plugin-transform-classes`, the applicaiton fails with the error:
```
TypeError: Class constructor model cannot be invoked without 'new'
```
Because transpiled classes are failing to extend native classes.

**Expected behavior/code**
Transpiled classes supports native classes extension.

**Babel Config File (Simplified)**
```
module.exports = function(api){
  const presets = [
    ['@babel/preset-env', {
      modules: false
    }],
    '@babel/preset-react'
  ]
  const plugins = [
    'babel-plugin-lodash',
  ]
  return {presets, plugins}
}
```

**Environment**
```
    "@babel/cli": "7.2.3",
    "@babel/core": "7.2.2",
    "@babel/preset-env": "7.2.3",
    "@babel/preset-react": "7.0.0"
```
- Node/npm version: v10.15.0, v6.4.1
- OS: Windows 10
- Monorepo: no
- How you are using Babel: 'rollup'

**Possible Solution**
Make the plugin check if the passed class to extend is a native one and if it is, use the native `extends` code or an equivalent one.

**Workarounds**
For now, to help users who encounter this problem, [I added 3 endpoints where classes are not transpiled](https://github.com/welldone-software/why-did-you-render/releases/tag/v2.5.0):
```
  "main-no-classes-transpile": "dist/no-classes-transpile/cjs/whyDidYouRender.min.js",
  "module-no-classes-transpile": "dist/no-classes-transpile/esm/whyDidYouRender.min.js",
  "browser-no-classes-transpile": "dist/no-classes-transpile/umd/whyDidYouRender.min.js"
```
by excluding the `babel-plugin-transform-classes` plugin:
```
    ['@babel/preset-env', {
      modules: false,
      exclude: ['babel-plugin-transform-classes']
    }],
```

**Other Relevant Suggestions**
If we had an improved error message when calling a class as a function, this error would of been much easier to debug. The error `Class constructor model cannot be invoked without 'new'` is very unclear: https://github.com/babel/babel/issues/8948

**Related Issues**
https://github.com/babel/babel/issues/4269
https://github.com/babel/babel/issues/6299
https://github.com/babel/babel/issues/7022
https://github.com/babel/babel/issues/7221
https://github.com/babel/babel/issues/8894
https://github.com/babel/babel/issues/9280

**Comment by vzaidman** [comment]
I'll be glad to fix it with a PR of my own. Can I have a suggestion on how to do it?

**Comment by nicolo-ribaudo** [comment]
Actually there already is https://github.com/babel/babel/pull/8656!

**Comment by vzaidman** [comment]
oh wow thanks

**Comment by mschipperheyn** [comment]
@nicolo-ribaudo the PR is no longer compatible with master

**Comment by rijnhard** [comment]
Keep running into this bug as well

**Comment by scaret** [comment]
Thanks! My early version of preset-env:
`"exclude": ["babel-plugin-transform-es2015-classes"],`

**Comment by neonsilk** [comment]
@nicolo-ribaudo it looks like this is still an issue when loose mode is enabled, is that expected?

Starting with the output from [this repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=MYGwhgzhAEDKCuAHApgJ2gbwL4CgekhgQCNpkAPAF2QDsATIpNTXHG5AdznmIAoBKANxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.15.2&externalPlugins=&assumptions=%7B%7D), if I replace `var Super = function Super() {}` with `class Super {}` then I get the error:
```
Uncaught TypeError: Class constructor Super cannot be invoked without 'new'
```

**Comment by nicolo-ribaudo** [comment]
It's because you are using `loose` mode. You can disable `loose` mode, and granularly enable the [assumptions](https://babeljs.io/docs/en/assumptions) you need (but not `superIsCallableConstructor`).
