### ISSUE TITLE
IOS 10 not loading app (vue.js)

### ISSUE THREAD

**Issue by postalangel** [babel/babel#9368]
## Bug Report
I am developing web app vue3/npm and have node babel package installed.
I had an object.values undefined on Vue app render error in IOS 9,10 so I have included following script inside babel.config.js
 presets: [
    '@vue/app',
    ["@babel/preset-env", {
      "useBuiltIns": "entry"
    }]
  ]

and then included in main.js entry point import '@babel/polyfill';

**Current Behavior**
Now I have no errors when tracking app running on IOS 10, but still I see that vue app has not been rendered (blank screen)

**Environment**
- @babel/polyfill 7.2.5
- node 11.7.0
- vue3
- OS: IOS 9.3.2.

**Comment by existentialism** [comment]
@postalangel sorry you're running into issues, but it's going to be really hard for us to debug if there's no example repo or stack trace :(
