### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ycjcl868** [babel/babel#9376]
## Bug Report

![image](https://user-images.githubusercontent.com/13595509/51512226-f4c78480-1e3f-11e9-9bc6-4cc667c2eb5f.png)

bug version: `@babel/runtime 7.3.0`,  #9334

**Comment by gera2ld** [comment]
It breaks everything!
![image](https://user-images.githubusercontent.com/3139113/51512981-7967d200-1e43-11e9-937c-53179e950946.png)

**Comment by danez** [comment]
Thanks for reporting. I will have a look now.

**Comment by danez** [comment]
Does anyone have a simple example of a spread that I can use to reproduce this?

**Comment by yesmeck** [comment]
@feiyingx See https://github.com/umijs/umi/pull/1888

**Comment by loganfsmyth** [comment]
Reopening this because it seems like a legitimate regression on our side. The runtime is supposed to stay compatible.

**Comment by gera2ld** [comment]
I don't think this is a version conflict since it breaks all code that depends on `@babel/runtime@~7.2.0`.
Should every third-party library pack a copy of `@babel/runtime` with it in the future?

**Comment by yesmeck** [comment]
https://github.com/yesmeck/babel-spread-undefined

Here is a reproduction. It seems `@babel/runtime@7.3.0` not compatible with `    "@babel/plugin-proposal-object-rest-spread@7.2.0`
