### ISSUE TITLE
Babel output should not produce jshint warnings.

### ISSUE THREAD

**Issue by jimbolla** [babel/babel#938]
I'm running the output of babel through jshint as part of my webpack build by chaining the loaders like so: `loader: 'jshint-loader!babel-loader'` I get some warnings in code inserted by babel. For example:

Given this source method

    setState(...newState) {
        this.state = _.assign({}, this.state, ...newState);
        this.trigger(this.state);
    },

JSHint produces the following error:

    jshint results in errors
    Missing 'new' prefix when invoking a constructor. @ line 20 char 54
        for (var _len = arguments.length, newState = Array(_len), _key = 0; _key < _len; _key++) {

**Comment by sebmck** [comment]
Similar issue to #354 where I said:

> Seems like a slippery slope so 6to5 obviously can't generate code compatible with every single style. Currently 6to5 outputs code that confines to the [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript#functions) with the exception of double quoted strings instead of single.

**Comment by sebmck** [comment]
If you're interested in linting your Babel code then the custom ESLint parser [babel-eslint](https://github.com/babel/babel-eslint) might be of interest (JSHint, JSCS etc don't fully support all the ES6 syntax that Babel supports).
