### ISSUE TITLE
Syntax Regular Expression Error in IE

### ISSUE THREAD

**Issue by Chun-MingChen** [babel/babel#9380]
## Bug Report

**Current Behavior**

`core-js@2.6.x` start support sticky flag `y` in modules/es6.regexp.split.js
Unfortunately, this feature IE didn't support (see http://kangax.github.io/compat-table/es6/#test-RegExp_y_and_u_flags).

```
SCRIPT5017: Syntax error in regular expression
```

ref: https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#sticky-flag

**Possible Solution**
Remove `^` in [package.json](https://github.com/babel/babel/blob/master/packages/babel-polyfill/package.json#L14).

**Babel Configuration (.babelrc, package.json, cli command)**

```diff
{
  "name": "@babel/polyfill",
  "dependencies": {
-   "core-js": "^2.5.7",
+   "core-js": "2.5.7",
    "regenerator-runtime": "^0.12.0"
  }
}
```

**Environment**
- Babel version(s): `6.5.2`
- Node/npm version: `8.14.0`

**Comment by nicolo-ribaudo** [comment]
@babel-bot 	Move to zloirock/core-js

**Comment by Chun-MingChen** [comment]
@nicolo-ribaudo, Reg exp `sticky flag` not support in core-js `2.6.x` from `babel polyfill`. Remove the `^` would allow `babel-pollfill` more IE friendly.

**Comment by nicolo-ribaudo** [comment]
We should just fix core-js

**Comment by waynelai614** [comment]
@nicolo-ribaudo 
Agreed, but we can avoid this unexpected issue by removing `^`

Although we didn't upgrade the `babel-polyfill` version, it'll install the latest version of `core-js`if someone reinstall the whole package.

**Comment by waynelai614** [comment]
`core-js` didn't have any plan to fix it, that's what we can do now by fixed the `core-js` version
ref: https://github.com/zloirock/core-js/issues/372#event-1439847152

**Comment by zloirock** [comment]
It's a `babel-minify` issue https://github.com/babel/minify/issues/928.
