### ISSUE TITLE
Typescript loses this in class method when parameter has type signature and default value

### ISSUE THREAD

**Issue by mkusher** [babel/babel#9385]
## Bug Report

**Current Behavior**
Having code as in example will produce invalid es5 with broken this

**Input Code**

```ts
export class Test {
  invite(options: { privacy: string } = {}) {
    const privacy = options.privacy || "Private"
    console.log(this)
  }
}
```

Babel output will be:
```js
export var Test =
/*#__PURE__*/
function () {
  function Test() {
    _classCallCheck(this, Test);
  }

  _createClass(Test, [{
    key: "invite",
    value: function invite() {
      var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
      return function () {
        var privacy = options.privacy || "Private";
        console.log(this);
      }();
    }
  }]);

  return Test;
}();
```

**Expected behavior/code**
No additional scope should be created.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    "@babel/plugin-transform-typescript"
  ],
  "env": {
    "production": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "modules": false
          }
        ]
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: Node 10/npm 6
- OS: OSX
- Monorepo: no
- How you are using Babel: `cli`, `loader`]

**Possible Solution**
A possible workaround is to move type from method declaration:

```ts
type Options = { privacy: string }
export class Test {
  invite(options: Options = {}) {
    const privacy = options.privacy || "Private"
    console.log(this)
  }
}
```

**Comment by yang** [comment]
I also just ran into this.  Babel is generating incorrect code.

Here's a minimal test case - a full working repro is available on https://codesandbox.io/s/7mv19mkl61:

```ts
function f(obj: { a?: boolean } = {})  {
  const a = obj;
  console.log(this);
}
```

You can see the transpiled function in Chrome DevTools, either open up index.tsx in the Source tab, or add a `debugger;` line right before the function declaration to break there:

```js
function f() {
  var obj = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  return function () {
    var a = obj;
    console.log(this);
  }();
}
```

The extra nested `function` seems to be triggered by the presence of all three:

- inline anonymous type declaration `{ a?: boolean }`
- default value `{}`
- variable that shadows a field in the type declaration, `const a`

**Comment by nicolo-ribaudo** [comment]
Minimal example:
```js
var privacy;

class Test {
  invite(options = privacy) {
    const privacy;
    this;
  }
}
```

Only the parameters plugin is necessary to show the bug.
