### ISSUE TITLE
TS: Computed class properties fail to build when typed as the class itself

### ISSUE THREAD

**Issue by pavasich** [babel/babel#9386]
## Bug Report

**Current Behavior**
Creating a self-typed, `computed` class property on a TS class throws this error:
```
TypeError: Property exprName of TSTypeQuery expected node to be of a type ["TSEntityName"] but instead got "SequenceExpression"
```

**Input Code**
```ts
class A {}

class B {
    a:     A; // Ok

    ['b']: A; // Ok

    c:     B; // Ok

    ['d']: B; // Error
    
}
```

**Expected behavior/code**
Expected `['d']: B;` to behave the same as `c: B;`

**Babel Configuration**

```js
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-transform-runtime",
        "@babel/plugin-proposal-class-properties",
        [
            "@babel/plugin-proposal-decorators",
            {
                "legacy": true
            }
        ]
    ],
    "overrides": [
        {
            "test": [
                "./src/**/*.ts",
                "./src/**/*.tsx"
            ],
            "presets": [
                  "@babel/preset-typescript",
                  "@babel/preset-env",
                  "@babel/preset-react"
            ]
        }
    ]
}
```

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: Node 9.2.0/npm 6.1.0
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel:  `loader`

**Comment by pavasich** [comment]
Popover moves as the pill grows and shrinks during filter configuration
![grow](https://user-images.githubusercontent.com/7889751/51620720-97dbd500-1ef8-11e9-8fdf-b517be046834.gif)

**Comment by nicolo-ribaudo** [comment]
This is now fixed: https://babeljs.io/repl#?browsers=chrome%2050&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8C-AoFpIwEKJdf0YAXAfrANzQD0V0A8gNZqkDaA5AEZsC6JF1tRswLASpLJRr0meAuwAmPEhIHQAogCcNAew2z8KJEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.12.1
