### ISSUE TITLE
Class properties use overrides descriptor defined at parent constructor after super() is called

### ISSUE THREAD

**Issue by finom** [babel/babel#9388]
## Bug Report

**Current Behavior**
It's kinda complicated to explain. Class `X` defines some descriptor of `prop` in its constructor. Class `Y` inherits `X` and includes a class property `prop`. When `Y#super()` is called, a babel helper calls its own `Object.defineProperty` which either overrides descriptor definition or causes an error `Uncaught TypeError: Cannot redefine property: prop` in case if `configureble` set to `false`.

**Input Code**
```js
class X {
  constructor() {
    Object.defineProperty(this, 'prop', {
      configurable: false,
    });
  }
}

new class Y extends X {
  prop = 1;
  constructor() {
    super(); // error because of Object.defineProperty call inside a babel helper
  }
}
```
**Expected behavior/code**

I'd expect babel to not override descriptor if it's set by `super()`.

**Babel Configuration (.babelrc, package.json, cli command)**

Isn't noteworthy.

**Environment**

```js
"@babel/core": "^7.2.2",
"@babel/plugin-proposal-class-properties": "^7.2.3",
```

**Possible Solution**

Not to call defineProperty after `super()` but at very beginning of a constructor.

**Comment by nicolo-ribaudo** [comment]
It is the expected behavior: fields are defined after super (), since before "this" doesn't exist

**Comment by finom** [comment]
@nicolo-ribaudo but they exists *at* `super()` (at the parent constructor).

**Comment by nicolo-ribaudo** [comment]
No, the parent constructor can't see the fields of subclasses.

**Comment by finom** [comment]
@nicolo-ribaudo hmm, looks like you're right, I can see that InitializeInstanceFields goes after everything (if I understood the spec properly https://tc39.github.io/proposal-class-fields/#the-super-keyword). But ... why? Closing this issue :(

**Comment by nicolo-ribaudo** [comment]
It's because class fields are deifned on `this`, and `this` is defined after that `super()` is run.
