### ISSUE TITLE
Possible @types/babel-types issue with latest @babel/types release

### ISSUE THREAD

**Issue by tbranyen** [babel/babel#9389]
## Bug Report

**Current Behavior**

Updating to 7.3.0 from 7.2.2 produces an unexpected TypeScript type regression

```
Type 'UnaryExpression' is not assignable to type 'UpdateExpression'.
  Types of property 'type' are incompatible.
```

**Input Code**

```js
if (types.isIdentifier(path.node) && path.node.name === 'undefined') {
  path.replaceWith(types.unaryExpression('void', types.numericLiteral(0)));
}
```

**Expected behavior/code**

No TypeScript definition errors should occur

**Environment**
- Babel version(s): @babel/types@7.3.0, @types/babel-types@7.0.4
- TypeScript compiler: 3.2.4

**Comment by nicolo-ribaudo** [comment]
We don't maintain the `@types/babel-types` package.

**Comment by tbranyen** [comment]
@nicolo-ribaudo I was told in the Slack channel by @loganfsmyth that you do and to open it here.

**Comment by nicolo-ribaudo** [comment]
Oh ok, I didn't know sorry :sweat_smile:

**Comment by nicolo-ribaudo** [comment]
Closing, since `@types/babel-types` is a third-party package and (since we ship our own TS types) don't officially recommend using it.
