### ISSUE TITLE
() => import('')  无法异步引入

### ISSUE THREAD

**Issue by siriusSupreme** [babel/babel#9390]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- REPL or Repo link if applicable:

```js
// import Layout from '../views/layout/Layout.vue'
let Layout = () => import('../views/layout/Layout.vue')
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
"presets": [
    [ "@babel/preset-env", {
      "modules": false,
      "useBuiltIns": "usage",
      "forceAllTransforms": true,
      "targets": {
        "browsers": [ "> 1%", "last 2 versions", "not ie <= 8" ]
      }
    } ]
  ],
  "plugins": [
    "lodash",
    "@babel/plugin-syntax-jsx",
    "@babel/plugin-proposal-function-bind",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-runtime",
    [ "@babel/plugin-syntax-decorators", {
      "decoratorsBeforeExport": true
    } ],
    "transform-class",
    "transform-class-properties",
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ],
```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: Node 8，npm 5
- OS: Windows 10
- How you are using Babel:`loader`

**Possible Solution**

![image](https://user-images.githubusercontent.com/20105166/51577948-a5905b00-1ef6-11e9-968c-10b097879f98.png)

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by loganfsmyth** [comment]
Sounds like you may be hitting https://github.com/webpack/webpack/issues/8656

**Comment by hzoo** [comment]
Can you verify @siriusSupreme? Otherwise we should close if it's unrelated to Babel. thanks!

**Comment by nicolo-ribaudo** [comment]
Closing as per https://github.com/babel/babel/issues/9390#issuecomment-456641279
