### ISSUE TITLE
Why does the doc 'transform-runtime' say 'Instance methods such as "foobar".includes("foo") will not work'?

### ISSUE THREAD

**Issue by shileiyuan** [babel/babel#9392]
The doc of 'transform-runtime' of babel7 says that instance methods transformation is not supported.

Let's say you will use @babel/plugin-transform-runtime, you can select either @babel/runtime or @babel/runtime-corejs together with it.

If you use @babel/runtime which doesn't have a dependency of corejs, you can not only use instance methods nor all the polyfill methods such as Promise or Set.
Else if you use @babel/runtime-corejs which references corejs, you can use all the polyfill methods.

So what's the real meaning of the doc? Did the doc make a mistake or am I misunderstand?

**Comment by zloirock** [comment]
Even with `@babel/runtime-corejs`, runtime transforms only constructors, static methods and has a special case for iterators. Instance methods are not transformed. They will be added after https://github.com/babel/babel/pull/7646.

**Comment by shileiyuan** [comment]
I finally understand what the meaning of "transform". That runtime can only transforms static methods and constructors is because runtime can return a refference of these static methods to only use in the current module, without polluting the global environment. For the instance methods, however, we can not transform them. We have to use polyfills to make them available in the global environment. What I misunderstanded at the beginning is that I think when I use `@babel/runtime` instead of `@babel/polyfill`, the instance methods can not be used safely as they may cause errors. But now I know, although the runtime can't transforms instance methods, we can still use them through polyfills. Thank you for your help!
