### ISSUE TITLE
Now.sh build breaking due to: Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by leongaban** [babel/babel#9397]
Hi, I'm using experimental decorators in my NextJS app and deployed it using Now.sh.

However I still get the following error doing the build process on Now. Is this something you guys have seen before?

I am using `@babel/plugin-proposal-decorators` in my `.bablerc` file. 

My stackoverflow question: https://stackoverflow.com/questions/54332378/now-sh-build-breaking-due-to-support-for-the-experimental-syntax-decorators-le

![screen shot 2019-01-23 at 11 32 53 am](https://user-images.githubusercontent.com/191636/51625368-a333fe00-1f02-11e9-9e5d-803d7a10d7ab.png)

```
SyntaxError: /tmp/131ed032/components/Board.tsx: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (45:3):

  43 |   }
  44 | 
> 45 |   @bind
     |   ^
  46 |   private handleOnSearch() {
  47 |     console.log('handleSearchButton...');
  48 |   }

```

**Comment by nicolo-ribaudo** [comment]
Where is you config file? Are there any `package.json`s between yuor config and that file? Which folder is Babel run from?

**Comment by hzoo** [comment]
Looks like @leongaban figured it out 😁 https://stackoverflow.com/a/54333082/724650 - there are different configs for dev/production (so not really a Babel issue per se)
