### ISSUE TITLE
Array.from isn't polyfilled in Node.js

### ISSUE THREAD

**Issue by bananushka** [babel/babel#940]
Hey, I've been using babel with node.js and it works pretty great, but I noticed that some features (like turning Iterables to arrays) don't work, because Array.from doesn't exist. There's a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) so I wondered if it's possible to add it (I don't mind doing myself and sending a pull request, I just wanted to know first if you're interested).

**Comment by neVERberleRfellerER** [comment]
https://babeljs.io/docs/usage/caveats/
```require("babel/polyfill");```

**Comment by sebmck** [comment]
Yep as @neVERberleRfellerER said, you need to use the built-in [polyfill](http://babeljs.io/docs/usage/polyfill) for built-ins and instance methods.

**Comment by QuantumInformation** [comment]
Why must we use a polyfill for this?

**Comment by sebmck** [comment]
How else do you expect it to work?

**Comment by QuantumInformation** [comment]
That it would be transcribed by default.

**Comment by loganfsmyth** [comment]
@QuantumInformation Babel is a syntax transformer, it does not provide ES6 library functions, for that you must load a polyfill.
