### ISSUE TITLE
@babel/plugin-proposal-do-expressions: StatementList behavior

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [babel/babel#9404]
## Bug Report

**Current Behavior**
Compilation result:
```js
x = 1;
x = (1, void 0);
```

**Input Code**
A module with the following contents
```js
x = do { 1; };
x = do { 1;;;; };
```

**Expected behavior/code**
Expected compilation result:
```js
x = 1;
x = 1;
```
This would match what what the ECMAScript spec currently says:
>The value of a StatementList is the value of the last value-producing item in the StatementList. For example, the following calls to the eval function all return the value 1:
>
> eval("1;;;;;")
> eval("1;{}")
> eval("1;var a;")

Chrome and Node repls both comply with the spec's assertion above.

I'm not sure this plugin attempts to evaluate StatementLists the same way. Its description is
> the final statement completion value inside the block becomes the completion value of the do expression.

"final statement completion value" could mean either the last value-producing statement (as above), or could mean the syntactically latest-appearing in the block. I'm not sure which is intended.

I'm not even sure the do-expression spec is precise enough right now to justify my expectation here. It suggests:
```
(do { <stmt> };) equivalent to { <stmt> }
```
but that doesn't parse:
```
$ npx babel --plugins @babel/plugin-proposal-do-expressions index.js
{ SyntaxError: /Users/swilson/code/playground/index.js: Unexpected token, expected "," (2:17)

  1 | x = do { 1; };
> 2 | x = (do { 1;;;; };);
    |                  ^
  3 |
  4 |
    at Parser.raise (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:3834:17)
    at Parser.unexpected (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5142:16)
    at Parser.expect (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5134:28)
    at Parser.parseParenAndDistinguishExpression (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:6413:14)
    at Parser.parseExprAtom (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:6211:21)
    at Parser.parseExprSubscripts (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5848:23)
    at Parser.parseMaybeUnary (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5828:21)
    at Parser.parseExprOps (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5717:23)
    at Parser.parseMaybeConditional (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5690:23)
    at Parser.parseMaybeAssign (/Users/swilson/code/playground/node_modules/@babel/parser/lib/index.js:5635:21)
  pos: 32,
  loc: Position { line: 2, column: 17 },
  code: 'BABEL_PARSE_ERROR' }
```

Thanks in advance!

**Babel Configuration (.babelrc, package.json, cli command)**
package.json dependencies:
```json
{
  "@babel/cli": "^7.2.3",
  "@babel/core": "^7.2.2",
  "@babel/plugin-proposal-do-expressions": "^7.2.0"
}
```
CLI command:
```sh
npx babel --plugins @babel/plugin-proposal-do-expressions index.js
```

**Environment**
- Babel version(s): both what's in the repl, and the above version info
- Node/npm version: 11.7.0/6.5.0
- OS: macOS 10.13.6
- Monorepo: No
- How you are using Babel: `cli`

**Comment by wlawt** [comment]
is this still available to work on?

**Comment by nicolo-ribaudo** [comment]
Yes!

**Comment by wlawt** [comment]
if i'm understanding the issue correctly, I have to write a plugin support for do-expressions in `babel-plugin-syntax-do-expressions` ?

**Comment by nicolo-ribaudo** [comment]
Yeah this is already supported, but we don't transpile correctly that code.

**Comment by wlawt** [comment]
is there documentation for the functions used like `replaceExpressionWithStatements` and `replaceWith` to understand how it's handling all the transpiling in `babel-plugin-proposal-do-expressions` ?

**Comment by wlawt** [comment]
@nicolo-ribaudo where can I find the AST for the `do-expression` plugin?

**Comment by hzoo** [comment]
@wlawt I would look at https://github.com/babel/babel/blob/master/packages/babel-parser/ast/spec.md and test things in https://astexplorer.net/

**Comment by wlawt** [comment]
@hzoo gotcha, I went looking around and found this https://github.com/babel/babel/blob/41085248560b1403b8d0f99f108491e679531c6c/packages/babel-generator/src/generators/expressions.js#L21

but not sure if I'm on the right track

**Comment by nicolo-ribaudo** [comment]
The code is indeed a bit confusing: `@babel/plugin-proposal-do-expressions` is almost empty and simply delegates to https://github.com/babel/babel/blob/fd3c76941e2e826cacab8844672f1d985f7ea564/packages/babel-traverse/src/path/replacement.js#L210

It then calls `toSequenceExpression()`, which delegates to https://github.com/babel/babel/blob/fd3c76941e2e826cacab8844672f1d985f7ea564/packages/babel-types/src/converters/gatherSequenceExpressions.js#L19. You can see that we are explicitly handling empty statements (i.e. `;`) ensuring that the resulting code ends with `undefined`.

After a git of automatic and manual `git blame`, you can see that it has been introduced byhttps://github.com/babel/babel/commit/9f1053212bd310d91996335f08f42189451d4017. Unfortunately this commit doesn't explain why :confused:
Maybe the proposal just changed after all these years, so that commit is now invalid. I'd say: try to fix it and see if it breaks any test.

**Comment by wlawt** [comment]
yup and for the 2nd part with the parsing error, that wouldn't be related to the files you've linked but more with `babel-parser/src/parser/expression.js` in how exactly is it handling `x = (do { 1;;;; };);`?

**Comment by nicolo-ribaudo** [comment]
Oh actually that paring error seems correct to me 🤔
You can't have ; inside an expression, only inside of the {...}

**Comment by wlawt** [comment]
oh I'm confused so the `(do { <stmt> };) equivalent to { <stmt> }` doesn't need to be addressed?
