### ISSUE TITLE
@babel/stage-2 changed for plugins with deep dependencies 

### ISSUE THREAD

**Issue by AlejandroArmenteros** [babel/babel#9408]
# v7 Regression

### Potential Commit/PR that introduced the regression
I just update babel to v7 and changed stage-2 for recommended plugins, but i get other result in bundle (I'm using webpack) only with this change. seems like deep dependencies doesn't work as expected with plugins but works perfectly with @babel/stage-2.  

### Describe the regression
If i use version 6 or using @babel/stage-2 everything works as expected.

### Input Code
**library A:**
```js
//https://github.com/visionmedia/superagent
require('superagent')
```

**main project:**
```js
require("A");
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true
      }
    ],
    [
      "@babel/preset-react",
     // "@babel/stage-2" //removing some plugins and adding this line works perfectly
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

**Comment by hzoo** [comment]
> but i get other result in bundle (I'm using webpack) only with this change

It's honestly hard to understand what is going on with this information. The the output just different or has a bug/incorrect?
