### ISSUE TITLE
Support ES6 Unicode escaped identifiers

### ISSUE THREAD

**Issue by getify** [babel/babel#941]
The new Unicode "code point escape" form is also valid for identifiers, such as:

```js
var \u{2B400} = 42;
```

AFAICT, no one has implemented this part of the grammar yet. As usual, @mathiasbynens has a [bunch of great stuff](https://mathiasbynens.be/demo/javascript-identifier-regex) about what makes a valid Unicode identifier in ES6 vs ES5, etc.

-------
BTW:

I'm not sure, but support of this feature may just need to be that such variables are straight up hygenically renamed to something else entirely, because there's (AFAICT) no equivalent way to do those kind of identifier names in pre-ES6.

**Comment by sebmck** [comment]
Please request this upstream at [acorn](https://github.com/marijnh/acorn).

**Comment by getify** [comment]
https://github.com/marijnh/acorn/issues/214

**Comment by mathiasbynens** [comment]
marijnh/acorn#214 and marijnh/acorn#215 are now fixed.

**Comment by sebmck** [comment]
Will take a little longer than I hoped since acorn is radically changing it's structure and will require me to rewrite all the custom acorn extensions (ES7, Flow etc). Once marijnh/acorn#216 is merged I should be able to nut through it in a day.

**Comment by sebmck** [comment]
Fixed in the `experimental` branch.

**Comment by getify** [comment]
is this going to stay *only* in "experimental" mode?

**Comment by sebmck** [comment]
No, the `experimental` branch is the current unstable branch (terrible name I know).

**Comment by getify** [comment]
ahh, ok, sorry for misunderstanding. thanks! :)
