### ISSUE TITLE
The "verbs" decorator can only be used on class verbs.

### ISSUE THREAD

**Issue by Kunoacc** [babel/babel#9410]
## Bug Report

**Current Behavior**
Decorators can't be used in class methods. It fails and throws this error when run with nodemon, "The "verbs" decorator can only be used on class verbs."

**Input Code**

```js
@route('/places')
export default class Places{
    constructor({PlacesService}){
        this.service = PlacesService;
    }

    @route('/list')
    @GET()
    async listPlaces(ctx){

    }
```

**Expected behavior/code**
Expected to compile and run

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "sourceMaps": "both",
    "plugins": [
      "@babel/plugin-transform-runtime",
      "@babel/plugin-proposal-object-rest-spread",
      [
        "@babel/plugin-proposal-decorators",
        {
          "decoratorsBeforeExport": true
        }
      ]
    ],
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ],
    "env": {
      "production": {
        "plugins": [
          "source-map-support"
        ]
      }
    }
}
```

**Environment**
- Babel version(s): v7.2.2
- Node/npm version: Node 10.15.0 / npm 6.5.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/16244990/51743011-b4fcd900-209b-11e9-83b6-b187fd7e2ac5.png)

**Comment by nicolo-ribaudo** [comment]
https://github.com/jeffijoe/awilix-router-core (assuming that that error comes from this library) uses legacy decorators. You need to use `"legacy": true` instead of `"decoratorsBeforeExport": true` in your config.

**Comment by Kunoacc** [comment]
THANK YOU!!!
