### ISSUE TITLE
Wrong order of ES6 imports. How I can make the order manual?

### ISSUE THREAD

**Issue by akopchinskiy** [babel/babel#9411]
Babel compiles imports in wrong order and this is causing errors and breaks the whole app. When I use manual load through html>head everything is working fine. 
How can I make Babel compile the code in order that I defined?

**Comment by nicolo-ribaudo** [comment]
Can you provide an example of input code, and how Babel reorders the exports?

**Comment by akopchinskiy** [comment]
@nicolo-ribaudo 
```js
// module1.js
const A = 1;

// module2.js
const B = 2;

// module3.js
console.log(A, B);

// app.js
import './module1';
import './module2';
import './module3';
```
Babel output like that:
```
// bundle.js
console.log(A, B); // undefined, undefined
const A = 1;
const B = 2;
```
Simple as that.

**Comment by nicolo-ribaudo** [comment]
Babel doesn't bundle files: it's a bug with your bundler (webpack or rollup maybe?).
Also, if you don't export those variable and import them in module3 you won't be able to log them.

**Comment by akopchinskiy** [comment]
@nicolo-ribaudo I presume you're wrong. Babel checks modules dependencies and sort them in a specific order for a bundler (webpack currently).
p.s. I just forgot to add `export` in the example, it was late evening, sry.

**Comment by nicolo-ribaudo** [comment]
>  I presume you're wrong. Babel checks modules dependencies and sort them in a specific order for a bundler

No it doesn't. The bundler gives Babel a file, Babel gives back the output for that file. It doesn't even know that there are multiple files

**Comment by nicolo-ribaudo** [comment]
Closing as this is not an issue with Babel.
