### ISSUE TITLE
Having import dependency issues within karma

### ISSUE THREAD

**Issue by joshbedo** [babel/babel#942]
Hey everyone! I'm currently trying to setup babel with karma using mocha, chai, sinon. I seem to be having a problem within my dependencies and not sure what the solution would be. Right now i have a file called `row.es6.js` that gets transpiled and i have a spec `row.spec.es6.js` that gets transpiled. The problem is that `row.es6.js` imports another module named `ui/common/tooltip` which is closer to a top level directory. I think the problem is that the `tooltip` is a `.coffee` file and import doesn't know to look for that extension type. Any help would be very much appreciated, Thanks!

Ex: 
`views/performance/reviews/row.es6.js`
`ui/common/tooltip.coffee`

I also have some jade templates i want to import, is this possible? 

![](https://api.monosnap.com/rpc/file/download?id=Vs3zCyrKl0N1BPjsY0FrFfTmTNd5BZ)
![](https://api.monosnap.com/rpc/file/download?id=53Fb8Qguh8zU50QvcuHVNN5mWSztSb)

**Comment by sebmck** [comment]
Hey @joshbedo! The Babel issue tracker is exclusively for bugs and features requests for Babel, for questions and support you can try our [gitter room](https://gitter.im/babel/babel) and [StackOverflow](http://stackoverflow.com), thanks!
