### ISSUE TITLE
bable-plugin-transform-runtime supports static transfrom ?

### ISSUE THREAD

**Issue by shizhipeng** [babel/babel#9421]
Hi, I have one  question
In our react component, we choose to discard using `bable-plugin-transform-runtime`,  
so that we are building a duplicating code lib like `function _classCallCheck () ={} ; _classCallCheck()` ...
but we have a plan, in our engineering, we are using bable-plugin-transform-runtime to transform `function _classCallCheck () ={} ; _classCallCheck()` with `babel/runtime` under `node_modules` by webpack config,  emm...something like: 
```javascript
{
    test: /\.(js|jsx)?$/,
    exclude: /node_modules\/(?!(@music)\/).*/,
        use: [{
             loader: 'babel-loader',
             options: {}
        }]
},
```
However, by looking into the packaged code, I found the duplicated codes is still exist, may i know how `bable-plugin-transform-runtim` works with `bable-runtime` ?
or our plan is wrong ? many thanks :)

**Comment by nicolo-ribaudo** [comment]
Your plan is correct, but if some of your dependecies are transpiled with Babel and don't use `@babel/transform-runtime`, the helpers will be duplicated for each of those dependencies. Anyway, it's better than duplicating them in each file.
