### ISSUE TITLE
[TypeScript] fails when destructure an array param on function

### ISSUE THREAD

**Issue by mhcgrq** [babel/babel#9430]
## Bug Report

**Current Behavior**
Code fails with Babel, works with TSC.

**Input Code**
- [REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=C4TwDgpgBAsiAq5oF4oAoDaBDANFARgLoBcUGAzsAE4CWAdgOZ50CuAtvhFYQJRTIA-KJVqMAUGID0kqKEiwESfugDeWAL6k1pEfQbq-g4dT0SAxgHs6lKAA9ScRPNQr1QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ctypescript&prettier=false&targets=&version=7.2.0&envVersion=7.2.0) (ps: needs to install the @babel/plugin-transform-typescript plugin)
- [TypeScript Playground](http://www.typescriptlang.org/play/#src=type%20MyType%20%3D%20(%7B%20theme%20%7D%3A%20%7B%20theme%3A%20string%20%7D)%20%3D%3E%20string%0D%0A%0D%0Aconst%20x%3A%20MyType%20%3D%20%7B%7D)

This code fails on Babel but not on TSC:
```typescript
type MyType = ([a, b]: [string, number]) => string

const x: MyType = {}
```

**Expected behavior/code**
Support this syntax, because tsc supports it.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**
- Babel version(s): 
    - "@babel/cli": "^7.2.3",
    - "@babel/core": "^7.2.2",
    - "@babel/preset-typescript": "^7.1.0"
- Node/npm version: Node 8/npm 5
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
see PR

**Related Issue**
[#8745](https://github.com/babel/babel/issues/8745)

**Comment by tyteen4a03** [comment]
Just ran into this issue as well.
