### ISSUE TITLE
Error: "Exporting local "Map", which is not declared."

### ISSUE THREAD

**Issue by martinschayna** [babel/babel#9433]
## Bug Report

**Current Behavior**
Error occurred when exporting built-in class (e.g. Set) from a module.

**Input Code**
https://github.com/martinschayna/babel-exporting-set

```js
export { Map, Set, WeakMap, WeakSet };
```

**Expected behavior/code**
It should.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "targets": ["defaults", "maintained node versions", "not node 8"]
      }
    ],
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from"
  ]
}
```

**Environment**
- Babel version(s):
```
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/polyfill": "^7.2.5",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-flow": "^7.0.0",
    "@babel/register": "^7.0.0"
```
- Node/npm version: `v10.14.2`
- OS: `Linux hp 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Monorepo: no
- How you are using Babel: `babel-node`, `register` (via mocha)

**Additional context/Screenshots**
```
SyntaxError: /home/mase/Projects/babel-exporting-set/mutable.js: Exporting local "Map", which is not declared.
  1 | // @flow
  2 | 
> 3 | export { Map, Set, WeakMap, WeakSet };
    |          ^
  4 | 
  5 | 
```

**Comment by martinschayna** [comment]
This one is working, but I had to rename exported classes:
```
export const MutableMap = Map;
export const MutableSet = Set;
export const MutableWeakMap = WeakMap;
export const MutableWeakSet = WeakSet;
```

**Comment by martinschayna** [comment]
Also, @nicolo-ribaudo :+1: suggests another solution, which is currently working without renaming exported classes:
```
const $Map = Map;
const $Set = Set;
const $WeakMap = Map;
const $WeakSet = Set;

export { $Map as Map, $Set as Set, $WeakMap as WeakMap, $WeakSet as WeakSet };
```

**Comment by loganfsmyth** [comment]
This is expected behavior. The spec requires that exported variables be local variables in the module itself, so you cannot export a global in this fashion. 

This is because an export doesn't have any runtime behavior, it is literally saying "expose this variable binding so it can be imported elsewhere", and if the thing being exported is a global, there would be no variable binding in the module to expose.

https://tc39.github.io/ecma262/#sec-module-semantics-static-semantics-early-errors

> It is a Syntax Error if any element of the ExportedBindings of ModuleItemList does not also occur in either the VarDeclaredNames of ModuleItemList, or the LexicallyDeclaredNames of ModuleItemList.
