### ISSUE TITLE
transform-module-commonjs' use of `var` vs. `const`

### ISSUE THREAD

**Issue by rdmurphy** [babel/babel#9435]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but something I noticed that's different from how TypeScript's compiler handles the conversion of an ES module `import` to a CommonJS `require` — if browser support is flagged appropriately, TypeScript will use a `const` for this transform for anything `ES2015` or above (via TypeScript's `--target` flag) :

```js
// in TypeScript
import { join } from 'path';

join('hello', 'world');

// becomes

const path_1 = require('path');

path_1.join('hello', 'world');
```

But in Babel (via `@babel/plugin-transform-module-commonjs`), it'll always use a `var` due to how it's hardcoded in.

https://github.com/babel/babel/blob/7e9029e3376f14720ccfdf9f676fed36f44498e7/packages/babel-plugin-transform-modules-commonjs/src/index.js#L188-L190

```js
// in JavaScript + Babel
import { join } from 'path';

join('hello', 'world');

// becomes

var _path = require('path');

_path.join('hello', 'world');
```

**Describe the solution you'd like**
Maybe it's not a big deal. 😄 But did think it was interesting there was a difference! The perfectionist in me *would* prefer it used `const` when a compilation target allowed for it (and an imported value technically *is* `readonly` in an ESM environment). But anyway! Wanted to see if anyone else had feelings about it. I admit I don't know the technical challenges from Babel's perspective regarding this - is this is something `@babel/plugin-transform-block-scoping` would then catch later and correctly convert if necessary?

**Describe alternatives you've considered**
Only to not get so caught up about it. 😁 

**Teachability, Documentation, Adoption, Migration Strategy**
I do think there's something to be said for using `const` all through your code, only to see the compiled version sneak a `var` in there (while leaving all the other `const`s alone) and how that *could* be confusing. But in general I feel like this could be a painless alteration *unless* `transform-block-scoping` wouldn't catch it.

**Comment by loganfsmyth** [comment]
This comes down to 2 things:

* We don't have a great story around plugin ordering yet, so I'd definitely worry about it being missed
* It's still relatively common to just compile to ES5, so it just hasn't been a priority
* If we output `const` we then need to clearly document that we output ES6 and have some way to make it clear to users what plugins they'd need to then get ES5. Not that this is insurmountable, but it raises 1 big question for me. What features are we allowed to use, and what qualifies as a breaking change? If our for-of transform outputs code with `const`, and thus expects all users to have the block-scoping transform, and later we decide to have it output destructuring, e.g. `{value, done} = iter.next()`, would it count as a breaking change? It could certainly be breaking if the user had explicitly only enabled for-of and block-scoping transformation, and suddenly start getting destructuring in their output. Then we get into the territory of plugin dependency systems and such.

**Comment by nicolo-ribaudo** [comment]
Closing this, since the output with `var` is 100% valid and even two bytes smaller.
