### ISSUE TITLE
Error due: mocha --require babel-register 

### ISSUE THREAD

**Issue by akopchinskiy** [babel/babel#9437]
Error when using babel-register module.
`mocha --require babel-register --renderer tests/unit-tests/share.js`

```
Setter must have exactly one formal parameter.
D:\WORK\Projects\apollo-time-tracker\node_modules\jsdom\lib\jsdom\level1\core.js:379
  set nodeName() { throw new core.DOMException();},
              ^^

SyntaxError: Setter must have exactly one formal parameter.
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Module._extensions..js (module.js:653:10)
...
```
Same error with `@babel/register`

But everything fine in other project with `mocha --require  ts-node/register --renderer ./tests/unit/unit.test.ts`

Is babel incompatible with mocha or what?

**Comment by loganfsmyth** [comment]
This sounds like a bug somewhere is deleting the parameter of that function, but without a reproducible example it is impossible to say more. That function does have an argument in its originall source: https://github.com/jsdom/jsdom/blob/18d83c837d1d69c8e1eb916691e362f9e228cb2e/lib/jsdom/level1/core.js#L444

**Comment by danez** [comment]
Which version of jsdom is installed in your project? This was a problem of jsdom version <= 0.6.0 (which is over 5 years old). Ensure you are using a newer version than that. If you do then there is probably something removing the param, as Logan mentioned.

https://github.com/jsdom/jsdom/commit/b0f6c73cf5f1d1e8d3bda6f5f0b49b7567b9eeea

**Comment by akopchinskiy** [comment]
@danez I don't have `jsdom` dependency in my project

**Comment by akopchinskiy** [comment]
@danez  I found what causes the issue: it's `knockout@2.1.0`. I simply working on a legacy project and I need to keep old dependencies. `knockout@2.1.0` has this weird dependency on `jsdom@0.2.3` which is case the issue.
