### ISSUE TITLE
Embedded Traversers

### ISSUE THREAD

**Issue by harrysolovay** [babel/babel#9438]
I'm creating a plugin that works with embedded function calls:

```js
const ast = parse(`
  const a = greatGrandParent(
    grandMother(
      motherOne(
        daughterOne(),
        sonOne(),
      ),
      fatherOne(
        daughterTwo(),
        sonTwo(),
      )
    ),
    grandFather(
      motherTwo(
        daughterThree(),
        sonThree(),
      ),
      fatherTwo(
        daughterFour(),
        sonFour(),
      )
    )
  )
`)
```

And is meant to transform these calls into something like this:

```js
// const a = [
//   greatGrandParent,
//   [
//     [
//       grandMother,
//       [
//         [motherOne, [[daughterOne, []], [sonOne, []]]],
//         [fatherOne, [[daughterTwo, []], [sonTwo, []]]],
//       ],
//     ],
//     [
//       grandFather,
//       [
//         [motherTwo, [[daughterThree, []], [sonThree, []]]],
//         [fatherTwo, [[daughterFour, []], [sonFour, []]]],
//       ],
//     ],
//   ],
// ]
```

Here's where it gets tricky... some of the functions will be called in a curry-ish form:

```js
embeddedFn()(
  anotherFn()
)
```

Some of them will be called via tagged template expressions:

```js
someFn`single text arg`
```

Some of them will be called via both:

```js
someFn({some: 'prop'})`tag contents`
```

The solution I'd like most is to create a visitor that identifies and extracts the arguments from these varying-form call expressions. It then needs to set some state for each of these call expressions and traverse the argument nodes with the same visitor. Because of the variation of call expressions (I guess some of them aren't technically call expressions...) it's easier to write if I stop the current traversal, and call `traverse` again on the argument nodes. For the example above, here's what I'm currently trying. Any help would be greatly appreciated!:

```js
const visitor = {
  CallExpression: {
    enter(path) {
      const {callee, arguments: args} = path.node
      path.state = {callee, args}
      if (args.length >= 1) {
        path.get('node.arguments').traverse(visitor) // cannot get `traverse` of undefined
      }
      path.stop() // keeps sibling nodes from being processed
    },
    exit(path) {
      const {callee, args} = path.state
      const replacement = t.arrayExpression([callee, t.arrayExpression(args)])
      path.replaceWith(replacement)
    },
  },
}

traverse(ast, visitor)
console.log(generate(ast).code)
```

Thank you for taking the time to look this over! Any help would be greatly appreciated :)

**Comment by nicolo-ribaudo** [comment]
Hey, sorry for the super long delay. I hope that you have already figured it out :sweat_smile:

In case you didn't, the problem is caused by this line:
```js
path.get('node.arguments').traverse(visitor)
```
It should be
```js
path.get("arguments").forEach(p => p.traverse(visitor));
```
