### ISSUE TITLE
loose mode: typescript classes remove type only properties

### ISSUE THREAD

**Issue by andykais** [babel/babel#9439]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This fr is related to the `@babel/plugin-transform-typescript` plugin. Previously described in https://github.com/babel/babel/issues/7997, when you define class properties that are type only, it assumes those properties should be defined on a class with a value of undefined. This leads to an issue when parent classes set a value that child classes want to access. I have created a [sample-repo](https://github.com/andykais/babel-define-class-typescript-properties) which describes the problem.

**Describe the solution you'd like**
From what I understand, a `{ loose: true }` option for the `@babel/plugin-transform-typescript` would be the best place to define this option. From the previous discussion, I understood that this was intentional, but that it could be implemented if there was good reason for it.

**Describe alternatives you've considered**
Alternatively, I could keep my inherited class types less specific or set the typed properties directly on the inherited properties.

**Teachability, Documentation, Adoption, Migration Strategy**
When using loose mode, this option will be enabled, the docs for `@babel.plugin-transform-typescript` and `@babel/preset-typescript` will reflect the option.

**Comment by nicolo-ribaudo** [comment]
See https://github.com/babel/babel/pull/9141

**Comment by andykais** [comment]
Thank you, that looks like what I am looking for! Just as a follow up though, I'd appreciate hearing the reason why this belongs on `@babel/proposal-class-properties` and not plug would it ever make sense to move this flag to the typescript babel plugin?

**Comment by nicolo-ribaudo** [comment]
Because it's used both by TS and flow. Also, due to ordering problems, if it isn't in the class properties plugins it won't always work.

**Comment by andykais** [comment]
ah had assumed the plugins would always go
1. typescript
2. class-properties
I can see how if class properties runs first, typescript would not be able to determine what was intended
