### ISSUE TITLE
Update parser typescript defintions

### ISSUE THREAD

**Issue by danez** [babel/babel#9441]
The Typescript definitions for the parser currently do no allow plugin options.

It would also be nice to have validation of plugin options in the typescript definition. (if possible) Say when doing this:
```ts
{
  plugins: [
     ["flow", { "notavalidoption": true }],
  ],
}
```
it should be marked as invalid and only all valid options.

The file I'm talking about is this: https://github.com/babel/babel/blob/master/packages/babel-parser/typings/babel-parser.d.ts

The options are all described at the website: https://babeljs.io/docs/en/babel-parser

I tried doing this, but I was getting nowhere because I don't know typescript enough.

**Comment by nicolo-ribaudo** [comment]
Yes it could work :+1:
