### ISSUE TITLE
[flow] @babel/types error when create declare class with TypeParameterDeclaration at DeclareClass.typeParameters

### ISSUE THREAD

**Issue by ilyalesik** [babel/babel#9443]
## Bug Report

**Current Behavior**
I traverse flowtyped .js file through @babel/traverse and receive an **TypeError: Property typeParameters of DeclareClass expected node to be of a type ["TypeParameterInstantiation"] but instead got "TypeParameterDeclaration"** error when try to create DeclareClass node with TypeParameterDeclaration instance as typeParameters.

**Input Code**
[REPL](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaFtgM7GgCqASgDIA8AKgHygDeiAvkA)

```js
// @flow

declare class URL<T> {
}
```

**Expected behavior/code**
No errors, because it is syntactically correct.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env", "@babel/preset-flow"]
}
```

**Environment**
- Babel version(s): [7.2.2]
- Node/npm version: [8.12.0/6.4.1]
- OS: [OSX 10.14.2]
- Monorepo: [no]
- How you are using Babel: [`parcer`, `traverse`, `generator`]

**Possible Solution**
Change
```js
defineInterfaceishType("DeclareClass", "TypeParameterInstantiation");
```
to
```js
defineInterfaceishType("DeclareClass", "TypeParameterDeclaration");
```
at _packages/babel-types/src/definitions/flow.js_:

**Additional context/Screenshots**

**Comment by danez** [comment]
Thanks for reporting this. Would you be willing to create a Pull request with this change? It seems correct to me that `TypeParameterDeclaration` should be there instead of `TypeParameterInstantiation`.
