### ISSUE TITLE
transform-commonjs's 'lazy' option is incorrectly negated for in the case of arrays of strings

### ISSUE THREAD

**Issue by kdy1** [babel/babel#9447]
## Bug Report

**Current Behavior**
`lazy` option acts like a blacklist.

https://github.com/babel/babel/blob/9eb010da5010f4d05468707bbb3bdee42d09f752/packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-whitelist/import-default/output.js#L1-L16

**Input Code**
https://github.com/babel/babel/blob/9eb010da5010f4d05468707bbb3bdee42d09f752/packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-whitelist/import-default/input.mjs#L1-L7

**Expected behavior/code**
`lazy: ["white"]` make "white" lazy-loaded.

**Babel Configuration (.babelrc, package.json, cli command)**

https://github.com/babel/babel/blob/9eb010da5010f4d05468707bbb3bdee42d09f752/packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-whitelist/options.json#L1-L6

**Environment**
- Babel version(s): master
- Node/npm version: N/A
- OS: N/A
- Monorepo: yes
- How you are using Babel: internal tester

**Possible Solution**

**Additional context/Screenshots**

I'm currently porting babel to rust ([swc][]), and I'm confused by test suite.

[swc]:https://github.com/swc-project/swc

**Comment by nicolo-ribaudo** [comment]
WIP PR at #9479

**Comment by Taym95** [comment]
I'm new to the babel world and I would like to take this issue!

**Comment by nicolo-ribaudo** [comment]
If you need any help you can contact me or any other team member on Slack 🙂

**Comment by paschalidi** [comment]
@nicolo-ribaudo @Taym95 if this is not on progress I can take over the issue the next days. please let me know :)

**Comment by Taym95** [comment]
I tried with it but no results, you can take it over ;)
