### ISSUE TITLE
Babel includes polyfill 'core-js/modules/web.dom.iterable' to output if script contains forEach() method call.

### ISSUE THREAD

**Issue by zhaparoff** [babel/babel#9449]
## Bug Report

**Current Behavior**
Babel includes `import "core-js/modules/web.dom.iterable";` in any output which input contains _forEach()_ method call. It can be _Array.prototype.forEach()_ or _forEach()_ method defined in custom class or interface:
https://github.com/zhaparoff/ts-babel-tests/blob/master/src/js/babelTest2.js -> https://github.com/zhaparoff/ts-babel-tests/blob/master/dist/js/babelTest2.js

https://github.com/zhaparoff/ts-babel-tests/blob/master/src/ts/babelTest1.ts ->
https://github.com/zhaparoff/ts-babel-tests/blob/master/dist/ts/babelTest1.js

The only exception is calling _forEach()_ for an array defined in the same visibility scope.
https://github.com/zhaparoff/ts-babel-tests/blob/master/src/js/babelTest1.js -> https://github.com/zhaparoff/ts-babel-tests/blob/master/dist/js/babelTest1.js

Also targeting Node instead of browsers omits that polyfill, which is obviously expected.
But targeting any browser, even the latest version of Chrome, includes that polyfill.

**Input Code**
https://github.com/zhaparoff/ts-babel-tests

**Expected behavior/code**
From my point of view, Babel shouldn't polyfill something that does not require polyfilling for sure.
I understand that JS has no type signatures and polyfilling suggestions could be made only from the context where the call is found. But developer should have ability to precisely control such kind of polyfilling, am I right? Probably there is a setting or plugin to tur off or a workaround, that I'm not aware of?

**Babel Configuration (.babelrc, package.json, cli command)**
https://github.com/zhaparoff/ts-babel-tests/blob/master/package.json
https://github.com/zhaparoff/ts-babel-tests/blob/master/.babelrc
`npm run build`

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: Node 11.8.0/npm 6.7.0
- OS: Windows 10, 1803
- Monorepo: ?
- How you are using Babel: cli through npm run

**Possible Solution**
Include the option for DOM polyfills into env preset, allowing to control it separately of browser/node target settings. Or move this polyfilling to a separate plugin, which can be disabled. 

**Additional context/Screenshots**
I even won't use DOM manipulations in my project, they will be handled by existing application platform API. I believe, there should be the feasible way to control it.

**Comment by nicolo-ribaudo** [comment]
You can use `exclude`: https://babeljs.io/docs/en/babel-preset-env#exclude

**Comment by zhaparoff** [comment]
@nicolo-ribaudo 

Yes I can... Suddenly, this option works with built-ins as well as with plugins, although documentation says nothing about it... Thanks for pointing that.

Anyway, potential ability to control web-polyfills sepately from selected targets could be quite usefull as for me.

**Comment by nicolo-ribaudo** [comment]
Well, it says "it works like includes" and includes mentions polyfills a few lines above.

> Anyway, potential ability to control web-polyfills sepately from selected targets could be quite usefull as for me.

How would your ideal configuration be?

**Comment by zhaparoff** [comment]
Well... Ideally, my configuration should be... no configuration at all. Suddenly, isn't it? ;-)

So, as I can imagine it, babel-typescript preset should use some plugin, which will add some metadata to the transpiled code. It could be @decorators or just comments in some fixed format, like webpack is using for example.

This metadata could be used by JS processing to optimize JS transpilation. Thus, if some parameter or method call will be marked as 'does not require polyfilling/shimming' it won't be affected by further transpilation.

Probably, these metadata descriptors can be documented and added manually to sorce JS code, for those developers who doesn't work with TS, but want to control babel transpilation more precisely.

In the final stage these metadata records can be cleaned out, to minify the output. Or left untouched for debugging purposes.

This is very highlevel, raw sketch - I'm not aware of any babel internal implementation, so can't even say if it's possible. Again, TypeScript support is new thing in Babel, so probably it is in roadmap already...  And I can't even imagine, how this could affect the performance...

But my opinion is that information defined by types should be kept until the end of transpilation flow and used during this process.

**Comment by polkovnikov-ph** [comment]
It's a very weird situation when there are several kilobytes of polyfills included if there is a `forEach`, which was added several years ago and has universal support. Whatever is that feature it's intended to polyfill, it must be opt-in, not opt-out.

**Comment by btmorex** [comment]
I hit this bug too. The problem is not just including unnecessary polyfills, it's that they're not included if you set useBuiltIns usage in preset-env leading to a runtime error. I had a random object with a "forEach" method call and I was getting a runtime error until I changed it to "each".

**Comment by zloirock** [comment]
@btmorex it can't be related to this issue.

**Comment by btmorex** [comment]
@zloirock Why? I had a runtime error about missing core-js/modules/web.dom.iterable. I renamed one of my own methods from forEach to each and the error went away. Seems related.

**Comment by zloirock** [comment]
@btmorex if you have this runtime error, you have incorrect / missed `@babel/runtime-corejs2` or `core-js` dependency. But this issue about incorrect polyfill injection.

**Comment by dteirney** [comment]
@zloirock do you know if there is a 2.6.6 release planned that will include this fix? We found this issue recently after tracking down why we were seeing a lot of unexpected polyfills showing up in a number of our bundles.

**Comment by zloirock** [comment]
@dteirney what do you mean? It's not a `core-js` issue. `core-js@2` has not a polyfill of `forEach` method on DOM collections, it was added in `core-js@3`. `web.dom.iterable` was mistakenly added in `@babel/preset-env` definitions. It was fixed in `@babel/preset-env@7.4`.
