### ISSUE TITLE
@babel/polyfill Array.prototype.map is incomplete

### ISSUE THREAD

**Issue by marcofranssen** [babel/babel#9452]
## Bug Report

**Current Behavior**
The polyfill for Array.prototype.map is not complete and is not handling the optional third parameter `array` as defined in this spec. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Syntax

**Input Code**

```js
const map1 = array1.map((x, i, arr) => `x:${x}, index:${i}, arr:${arr}`);
```

arr here is undefined....

Following react component is using map in this way. https://www.npmjs.com/package/react-truncate See the usage example https://www.npmjs.com/package/react-truncate#usage in the second code block. This all works fine until polyfills are loaded in an older browser version.

**Expected behavior/code**

```js
const map1 = array1.map((x, i, arr) => `x:${x}, index:${i}, arr:${arr}`);
```

arr should have the value of array1. So it matches the Array.prototype.map spec as defined over here. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Syntax

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "env",
    "stage-0",
    "stage-1",
    "react",
    "flow"
  ],
  "plugins": ["transform-class-properties", "transform-decorators-legacy"]
}
```

**Environment**
- "babel-polyfill": "^6.7.4"
- Node/npm version: Node 10, Node 11
- How you are using Babel: [Webpack, cli]

**Possible Solution**
Update the `Array.prototype.map` implementation.

**Comment by nicolo-ribaudo** [comment]
@babel-bot Move to zloirock/core-js

@marcofranssen I'm moving this issue to the correct repo. If you want to help fixing it, the bug is probably in https://github.com/zloirock/core-js/blob/v2/modules/es6.array.map.js
