### ISSUE TITLE
@babel/plugin-proposal-decorators not working with @babel/plugin-transform-runtime

### ISSUE THREAD

**Issue by Lodin** [babel/babel#9454]
## Bug Report

**Current Behavior**
Decorator helpers are not imported if `@babel/plugin-transform-runtime` is enabled, instead, they are still defined in file as if no transform-runtime plugin is used. 

**Input Code**
- REPL or Repo link if applicable:
https://runkit.com/lodin/decorators-transform-runtime-issue

```js
@cls
class A {
  @prop
  test() {}
}
```

**Expected behavior/code**
All helper functions in the file are replaced with imports from `@babel/runtime`. 

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  plugins: [
    [require("@babel/plugin-proposal-decorators"), {decoratorsBeforeExport: true}],
    require("@babel/plugin-proposal-class-properties"),
    [require("@babel/plugin-transform-runtime"), {
      "corejs": false,
      "helpers": true,
      "regenerator": false,
      "useESModules": true
    }],
  ],
  presets: [],
}
```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: node 11.8.0/npm 6.5.0
- OS: Windows 10
- Monorepo: [e.g. yes/no/Lerna]: no
- How you are using Babel: [e.g. `cli`, `register`, `loader`]: cli

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

I can find `@babel/runtime/helpers/esm/decorate.js` file in `node_modules`, so only import replacing doesn't work for some reason.

**Comment by nicolo-ribaudo** [comment]
You need to specify which runtime version you are using:

```js
{
  plugins: [
    [require("@babel/plugin-proposal-decorators"), {decoratorsBeforeExport: true}],
    require("@babel/plugin-proposal-class-properties"),
    [require("@babel/plugin-transform-runtime"), {
      "corejs": false,
      "helpers": true,
      "regenerator": false,
      "useESModules": true,
      "version": "7.2.2"
    }],
  ],
  presets: [],
}
```

By default, Babel must output code compatible with runtime v7.0.0

**Comment by Lodin** [comment]
@nicolo-ribaudo, great, thanks! Could it be mentioned in the documentation somewhere? I couldn't find it at the [`@babel/runtime` page](https://babeljs.io/docs/en/babel-plugin-transform-runtime)

**Comment by nicolo-ribaudo** [comment]
Do you want to document it? :smile: 🙏

**Comment by Lodin** [comment]
@nicolo-ribaudo, oh sorry for the delay 😅
Ok, I'll do it when I have time.

**Comment by nicolo-ribaudo** [comment]
Hi! The decorators proposal has been completely rewritten and we are discontinuing maintenance of the 2018-09 version (which will then be completely removed in Babel 8). You can migrate to the Stage 3 version of the [proposal](https://github.com/tc39/proposal-decorators/) by using `version: "2021-12"`.
