### ISSUE TITLE
Importing babel/polyfill crashes ie11

### ISSUE THREAD

**Issue by Ashot-KR** [babel/babel#9456]
Importing `@babel/polyfill` crashes IE.

![crash](https://user-images.githubusercontent.com/899218/52220122-37ad4180-28af-11e9-906b-952f1da7814e.png)

**Build environment**
- Node/npm version: node v10.15.0, npm 6.7.0
- MacOS 10.13.6

**Comment by nicolo-ribaudo** [comment]
IE version? Does it work if you import core-js instead?

**Comment by Ashot-KR** [comment]
`import 'core-js'` also crashes ie.
IE 11.0.9600.16384 on Win7 crashes
but IE 11.0.9600.16384 on Win10 is OK

**Comment by nicolo-ribaudo** [comment]
Ok, I'm moving this to the correct repository.

Could you rewrite your last comment there? Also, could you test of you have the same issue with older core-js versions?

@babel-bot move to zloirock/core-js
