### ISSUE TITLE
Breaking Code that uses ASI 

### ISSUE THREAD

**Issue by mattdesl** [babel/babel#946]
A lot of my code uses ASI (as per npm style) and I noticed this breakage without a semicolon:

```js
let Mesh = { positions: [], cells: [] }
let { positions, cells } = Mesh
//some comment
```

Using babelify + browserify the code transpiles to: 

```js
"use strict";

var Mesh = { positions: [], cells: [] };
var positions = Mesh
//some comment
.positions;
var cells = Mesh.cells;
```

Whereas adding a semicolon will fix the code:

```js
let Mesh = { positions: [], cells: [] }
let { positions, cells } = Mesh;
//some comment
```

Transpiles to:

```js
"use strict";

var Mesh = { positions: [], cells: [] };
var positions = Mesh.positions;

//some comment
var cells = Mesh.cells;
```

**Comment by eventualbuddha** [comment]
That is interesting. Technically the generated code is syntactically correct and should work as expected, but it definitely is odd. Probably what should happen is the comment currently attached to the `Mesh` identifier should be attached to the second generated `VariableDeclaration` for `cells`.

**Comment by neVERberleRfellerER** [comment]
Another interesting thing is that this only happen when there is nothing after the comment. Adding anything after the comment and resulting code is normal/expected.

**Comment by sebmck** [comment]
The comment is being attached to the `Mesh` identifier and it's being reused. Not really a bug. Not willing to go out of my way to support non-semicolon usage.

**Comment by mattdesl** [comment]
ASI is pretty clearly written into the spec. Diverging Babel from the spec in favour of your own coding style is sure is sure to turn off a lot of a lot of people and also break a fair amount of code.

**Comment by sebmck** [comment]
@mattdesl I'm not diverging from the spec. The code is correctly parsed. I was referring to the specifics of comment attachment as it's based on tokens and the closest node.

**Comment by sebmck** [comment]
And as @eventualbuddha said, that code is syntactically correct and will run without a problem so there's nothing breaking here.

**Comment by mattdesl** [comment]
Hmm yep, you're right. Code runs fine even though it looks pretty weird.
