### ISSUE TITLE
babeljs.io website throws error

### ISSUE THREAD

**Issue by timreichen** [babel/babel#9460]
## Bug Report

**Current Behavior**
Babeljs.io website throws an error when adding the babel-plugin-transform-named-capturing-groups-regex plugin.

```js
const regex = /(?<name>helloworld)/
```

**Expected behavior/code**
Should transpile to and wrap.

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- OS: [e.g. OSX 10.13.4]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
<img width="1552" alt="bildschirmfoto 2019-02-05 um 20 07 03" src="https://user-images.githubusercontent.com/14932257/52298007-3b5dc880-2982-11e9-9dce-ef4a57950015.png">

**Comment by nicolo-ribaudo** [comment]
Babel 7 plugins can't be used with Babel 6. We are working on upgrading the main repl; in the meantime you can use https://babeljs.io/repl/build/master
