### ISSUE TITLE
TypeScript: missing error on empty typeArguments and typeParameters

### ISSUE THREAD

**Issue by armano2** [babel/babel#9462]
## Bug Report

**Current Behavior**
Babel does not report error on empty typeParameters and typeArguments

**Input Code**
```ts
const foo: Foo<>
```
```ts
function f1<>() {}
```

**Expected behavior/code**
babel should throw errors:
> Type parameter list cannot be empty.
> Type argument list cannot be empty.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  const babel = require('@babel/parser');
  const plugins: ParserPlugin[] = [
    'typescript',
    'objectRestSpread',
    'decorators-legacy',
    'classProperties',
    'asyncGenerators',
    'dynamicImport',
    'estree',
    'bigInt',
    'importMeta'
  ];
  if (jsx) {
    plugins.push('jsx');
  }

  return babel.parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins
  });
```

**Environment**
- Babel version(s):  7.3.2
- Node/npm version: 6-11
- OS: ----
- Monorepo: ---
- How you are using Babel: @babel/parser -> `parse`

**Comment by danez** [comment]
For some reason we do not fail and have this comment in the code:
https://github.com/babel/babel/blob/c36eb35c3ddeda40842712c5f25443c8a6f5999f/packages/babel-parser/src/plugins/typescript.js#L2151

Not sure why we wouldn't though.
