### ISSUE TITLE
System.config before imports

### ISSUE THREAD

**Issue by sochka** [babel/babel#947]
Hi, this is more of a question for advice. I use ES6 modules and have something like the following in some js files:

```
System.config({
 paths: {
   'user': 'some-file-on-server.js'
 }
});

import 'user'
```

I cannot move `System.config` to one main file because I need to have this config distributed.  How do I compile this file (to system.js module) in such a way that System.config doesn't end-up inside module definition resulting in non-defined paths?

**Comment by sebmck** [comment]
Hey @sochka! The Babel issue tracker is exclusively for bugs and features requests for Babel, for questions and support you can try our [gitter room](https://gitter.im/babel/babel) and [StackOverflow](http://stackoverflow.com), thanks!
