### ISSUE TITLE
A bug about this in babel

### ISSUE THREAD

**Issue by WU-SUNFLOWER** [babel/babel#9471]
## Bug Report

**Current Behavior**
If I input the following code into babel
```js
var kkk = 6666;
let test = _=>this.kkk;
console.log(test());
```
It will output the following code
```js
"use strict";

var _this = void 0;

var kkk = 6666;

var test = function test(_) {
  return _this.kkk;
};

console.log(a());
```
**Expected behavior/code**
If I run the output code in Chrome, I will get a error.
> _Uncaught TypeError: Cannot read property 'kkk' of undefined_

But in fact, the code that I input is right, and it will output `6666` successfully in Chrome!
And I try to modify `var kkk = 6666;` to `let kkk = 6666;` in my original code, but babel output the same code.This makes me very confused.

**Environment**
- Babel version(s): v7.2.2
- OS: Windows 7 with Chrome72
- How you are using Babel: I only use the online babel:https://babeljs.io/repl/

**Possible Solution**
Babel should judge `this` correctly.

**Comment by loganfsmyth** [comment]
This should explain: https://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined-and-inserting-use-str/34983495#34983495
