### ISSUE TITLE
Your site not working: https://babeljs.io/repl

### ISSUE THREAD

**Issue by zeves095** [babel/babel#9473]
Your site not working: https://babeljs.io/repl

Not found https://unpkg.com/@babel/standalone@6.26.0 (in chrome devtool network tab )

actually https://unpkg.com/@babel/standalone ---point to---> 
 https://unpkg.com/@babel/standalone@7.3.2/babel.js

**Comment by nicolo-ribaudo** [comment]
It might be a caching problem. If you load https://babeljs.io/repl#?version=7, does it start working?

**Comment by polkovnikov-ph** [comment]
Same for me. It's as if there is a server-side exception in Node.js, and it doesn't even close the socket.

**Comment by danez** [comment]
This should now be fixed with babel/website#1964

**Comment by zeves095** [comment]
Yes with your link it is working.
