### ISSUE TITLE
babel throws when running test suite with ts-jest

### ISSUE THREAD

**Issue by paulrehkugler** [babel/babel#9475]
# v7 Regression

**Potential Commit/PR that introduced the regression**
https://github.com/babel/babel/commit/6d177ba4c554136e9d6175b4162d6d84fbc85c52

**Describe the regression**
Running tests using `ts-jest` no longer works because this error is thrown:
> [BABEL] unknown: Configuration contains string/RegExp pattern, but no filename was passed to Babel

(This issue is also filed in `ts-jest`—https://github.com/kulshekhar/ts-jest/issues/934—, but I believe it is a Babel error)

**Input Code**

Here is a minimal repo that I made that reproduces this issue:
https://github.com/paulrehkugler/ts-jest-babel-no-filename-repro

**Babel Configuration (.babelrc, package.json, cli command)**

[(in repo above)](https://github.com/paulrehkugler/ts-jest-babel-no-filename-repro/blob/master/babel.config.json)

**Expected behavior/code**

Previously, the tests ran without crashing. Commenting out throwing the error in Babel also allows the tests to run.

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: node 10.9.0 / npm 6.2.0
- OS: macOS 10.14.3
- How you are using Babel: in our testing environment (where this fails), we are using it from ts-jest as a secondary compiler for non-TypeScript files

**Comment by twinser** [comment]
We came across this bug too, in a slightly different setting. 
We were using the following babel config for our Vue app (pretty sure it is the default from the cli):
`module.exports = {
  presets: ["@vue/app"]
};`
When running jest, we were receiving the _Jest encountered an unexpected token_ error when importing core-js modules. With some searching we discovered #8731 and [this answer](https://github.com/babel/babel/issues/8731#issuecomment-423845498) which suggests we use `ignore: [/\/core-js/]`. 

So far so good, the tests started running and most passed. However, one suite would not run. We got the error mentioned in the OP's description and commenting out the lines also makes the test run for us. Interestingly, switching the regex pattern in the babel config for a string also makes the test run.

**Comment by nicolo-ribaudo** [comment]
@paulrehkugler In your repo you use `babel.config.json`, but it isn't a valid configuration file name: it should be `babel.config.js`

**Comment by garyo** [comment]
Like @twinser, I'm also using Vue and typescript, and am getting this same error. But I'm not importing core-js, and @twinser's solution didn't help for me. The error doesn't say what module is causing the problem. I do have an "ignore" stanza in my babel.config.js to ignore some dependencies:
```
module.exports = {
  presets: [
    '@vue/app' // see node_modules/@vue/babel-preset-app/index.js
  ],
  ignore: [
    "ngl",                       // important!!
    "three.js",                   // ?
  ],
  env: {
    development: {
      sourceMaps: true,
      retainLines: true
    }
  }
}
```
and if I remove that stanza temporarily, the tests run (well, I don't get that error anyway).

**Comment by danez** [comment]
Updating `jest` and `ts-jest` to the latest version and removing `babel-core@7.0.0-bridge.0` (which isn't needed anymore) fixed the issue for me.

```diff
diff --git a/package.json b/package.json
index 4f5883e..aa8d222 100644
--- a/package.json
+++ b/package.json
@@ -8,9 +8,11 @@
   "devDependencies": {
     "@babel/core": "^7.2.2",
     "@babel/preset-env": "^7.2.3",
+    "@types/jest": "^24.0.13",
+    "babel-jest": "^24.8.0",
     "babel-preset-react-app": "^7.0.0",
-    "jest": "^23.6.0",
-    "ts-jest": "^23.10.5",
+    "jest": "^24.8.0",
+    "ts-jest": "^24.0.2",
     "typescript": "^3.2.2",
     "webpack": "^4.28.3"
   },
@@ -44,8 +46,5 @@
     "reporters": [
       "default"
     ]
-  },
-  "dependencies": {
-    "babel-core": "^7.0.0-bridge.0"
   }
 }
```
