### ISSUE TITLE
babel-node should not handle the arguments after the script

### ISSUE THREAD

**Issue by danthegoodman** [babel/babel#948]
I have a script which responds to the --debug flag.

```
babel-node main.js --debug
```

Right now, it is getting handled by 'babel-node' and not being passed to main.js

I think babel-node should only handle arguments that come before the script.

**Comment by neVERberleRfellerER** [comment]
Use two dashes to separate babel arguments from your arguments
```
babel-node --some-babel-args -- main.js --debug
```
