### ISSUE TITLE
babel/parse@7.3.1(7.3.2) does not compile correctly?

### ISSUE THREAD

**Issue by xiezhongfu** [babel/babel#9489]
## Bug Report

**Current Behavior**
@babel_parser@7.3.1, @babel_parser@7.3.2 does not know `${...}` correctly.
@babel_parser@7.2.3 compile successfully

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "targets": {
          "browsers": [
            "last 3 versions",
            "safari >= 7",
            "not ie <= 8"
          ]
        }
      }
    ],
    "@babel/react"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import",
    [
      "import",
      {
        "libraryName": "antd",
        "style": true // `style: true` 会加载 less 文件
      }
    ],
    "react-hot-loader/babel"
  ]
}
```

**Environment**
- Babel version(s): [^7.2.2]
- Node/npm version: [Node 10.13.0/npm 6.4.1]
- OS: [OSX 10.13.4, Windows 10, Windows 7]
- Monorepo: [no]
- How you are using Babel: [`loader`]

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/10264972/52549235-20210c00-2e0d-11e9-8df9-1b0be1afe926.png)

**how do I solve the problem temporarily**
![image](https://user-images.githubusercontent.com/10264972/52549860-4dbb8480-2e10-11e9-83aa-cfbbbfd37459.png)

**Comment by danez** [comment]
That error is weird. I'm not able to reproduce this yet. I wonder if there is some invisible unicode character that sneaked in front of the first `${`. Can you check?

**Comment by xiezhongfu** [comment]
> That error is weird. I'm not able to reproduce this yet. I wonder if there is some invisible unicode character that sneaked in front of the first `${`. Can you check?


![image](https://user-images.githubusercontent.com/10264972/52555723-7c902580-2e25-11e9-9310-3488d539d294.png)

**Comment by nicolo-ribaudo** [comment]
I can't reproduce it using this code:

```js
export const fetchPageConfig = (pageId, pageLink) => dispatch => {
    return myFetch(
      `${API.apiPrefix}page/config/\${pageId}/1\${pageLink === "preview" ? "?preview=true" : ""}`,
      {
        method: "POST",
        isQuiet: true,
        isLoading: true,
      }
    );
  };
```

Can you share a file which triggers the error (a file, not an image please).
