### ISSUE TITLE
Nested Destructuring

### ISSUE THREAD

**Issue by gsklee** [babel/babel#949]
```javascript
const obj = {x: 1, y: {z: 'yo'}};
const {x, {z} = y} = obj;
```

This currently does not work. Is this the expected behavior of ES6?

**Comment by sebmck** [comment]
This is a bug in [acorn](https://github.com/marijnh/acorn) please report it upstream.

**Comment by sebmck** [comment]
Wait no it's not.

**Comment by sebmck** [comment]
I'm not sure how you're expecting this to work. What do you expect:

```javascript
const {x, {z} = y} = obj;
```

to do?

**Comment by gsklee** [comment]
```javascript
const obj = {x: 1, y: {z: 'yo'}};
const {x, {z} = y} = obj;

// x=1, y={z: 'yo'}, z=yo
```

I think this makes sense, no?

**Comment by sebmck** [comment]
It doesn't. You aren't providing an identifier when you specify `{z}` so it wont have anything to bind to. 

The valid version is:

```javascript
const { x, { y: { z } } } = obj;
```

**Comment by gsklee** [comment]
Wow, ok. But it's not working either: [REPL](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=const%20obj%20%3D%20%7Bx%3A%201%2C%20y%3A%20%7Bz%3A%20'yo'%7D%7D%3B%0Aconst%20%7Bx%2C%20%7By%3A%20%7Bz%7D%7D%7D%20%3D%20obj%3B%0A%0A%0Aconsole.log(x%2C%20y%2C%20z)%3B)

**Comment by sebmck** [comment]
@gsklee Like [this](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=const%20obj%20%3D%20%7Bx%3A%201%2C%20y%3A%20%7Bz%3A%20'yo'%7D%7D%3B%0Aconst%20%7Bx%2C%20y%3A%20%7Bz%7D%7D%20%3D%20obj%3B%0A%0A%0Aconsole.log(x%2C%20y%2C%20z)%3B).

**Comment by gsklee** [comment]
@sebmck Ah okay. So no way to capture `y = {z:"yo"}`?

**Comment by sebmck** [comment]
@gsklee Not if you want to destructure one of it's children.

**Comment by gsklee** [comment]
@sebmck Alrighty, thanks!
