### ISSUE TITLE
@babel/plugin-proposal-object-rest-spread can cause path.hub to be undefined

### ISSUE THREAD

**Issue by coreyfarrell** [babel/babel#9496]
## Bug Report

**Current Behavior**
path.hub can be undefined.

**Input Code**
```js
const assert = require('assert');
const {transform} = require('@babel/core');

transform('const copy = {...anyObject};', {
	configFile: false,
	babelrc: false,
	plugins: [
		'@babel/plugin-proposal-object-rest-spread',
		babel => ({
			visitor: {
				VariableDeclarator(path) {
					assert(typeof path.hub !== 'undefined')
				}
			}
		})
	],
});
```

**Expected behavior/code**
path.hub should not be undefined (maybe always `===` second argument of visitor function?).

**Babel Configuration (.babelrc, package.json, cli command)**

```shell
npm i @babel/core @babel/plugin-proposal-object-rest-spread
```

**Environment**
- Babel version(s): `@babel/core@7.2.2`, `@babel/plugin-proposal-object-rest-spread@7.3.2`
- Node/npm version: node 10.15.0, npm 6.4.1
- OS: Fedora 28
- Monorepo: no
- How you are using Babel: API / see script

**Additional context/Screenshots**
Potentially related to #8641

**Comment by coreyfarrell** [comment]
Further detail, it appears that `path.hub` is undefined for parts that were inserted by `@babel/plugin-proposal-object-rest-spread`.  Replace the assertion with:
```js
console.log(`${typeof path.hub}: ${path.node.id.name}`);
```
This prints:
```
object: copy
undefined: i
undefined: source
undefined: ownKeys
```

**Comment by jeron-diovis** [comment]
Just ran into this. For me, error happens in code like this:
```js
for await (const x of xs) {
    whatever(...x)
}
```
Removing either spread or `await` fixes error.
