### ISSUE TITLE
Question: has TCO been implemented?

### ISSUE THREAD

**Issue by SekibOmazic** [babel/babel#950]
Hi,

I'm not sure if the tail call optimisation has been fully implemented or not, but when running this code in repl:

```Javascript
const even = (n) => n === 0 || (n !== 1 && even(n - 2))

console.log(even(100042));
```
I get following message:

```Shell
Maximum call stack size exceeded
```

**Comment by sebmck** [comment]
Hey @SekibOmazic! The Babel issue tracker is exclusively for bugs and features requests for Babel, for questions and support you can try our [gitter room](https://gitter.im/babel/babel) and [StackOverflow](http://stackoverflow.com), thanks!

**Comment by SekibOmazic** [comment]
@sebmck Well no need to go to http://stackoverflow.com and ask the question. It's enough to put the code above in the REPL to get the stack overlow ;-)

**Comment by ericelliott** [comment]
The problem seems to be that [tail calls don't work with anonymous functions](https://github.com/babel/babel/issues/1367).
