### ISSUE TITLE
preset-env: do you not support ES5?

### ISSUE THREAD

**Issue by zfrisch** [babel/babel#9513]
Does babel not support ES5 ?

I switched to using preset-env and my files seem to be transpiling but still using `const`. That doesn't make any sense to me. Is there a plugin for this, or what?

I've looked everywhere for this question and read the documentation for babel, babel-presets, browserlist, all the github repos. Nothing is helping me and even when the question is asked on stackoverflow it's not answered. 

What's the deal?

**Comment by existentialism** [comment]
@zfrisch we'll need more information in order to help you. can you post your babel config? or better yet, a repo that reproduces the problem?

**Comment by zfrisch** [comment]
It's not really a question of build if babel/babelify doesn't support ES5 variables anymore

**Comment by nicolo-ribaudo** [comment]
Yes, it does support them. Please provide the required info so that we can understand why it isn't working for you.

**Comment by zfrisch** [comment]
Ah, interesting. Actually it looks like it's babelify - and I'm not sure if that would still fall under this repo? I can give the code if it is. Basically it's transpiling but no presets are loading in at all. Doesn't matter if they're setup inside of .babelrc, the gulpfile, or the package.json. I even checked the babel object that's created while transforming the files. It's just not pulling it in no matter what I do, so it's very frustrating.

**Comment by nicolo-ribaudo** [comment]
babelify uses `@babel/core` internally, so it is likely a configuration bug.
What are:
 1. You package.json's devDependencies
 2. Your babel config
 3. Your directory structure (it's important to know where are the config files and the source files, and where you are running the build command from)
