### ISSUE TITLE
@babel/plugin-syntax-flow returns incompatible Flow code

### ISSUE THREAD

**Issue by mrtnzlml** [babel/babel#9514]
## Bug Report

**Current Behavior**
When I use `@babel/plugin-syntax-flow` to parse Flow code it generates wrong output (completely incompatible).

**Input Code**
[REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=C4TwDgpgBAJAYgJwIYHMC2EB2wBKEBmAPACoB8UAvFEpiAFB2iSx4A2SIACggPZgDOhbn34AaKGw7CwZSrADyAIwBWAWSRhCdKLAAiAS3xFpYqAG8oCCOxAAuCdam8ZUAD5QAbj30ATKAF9SUW0oAAoSewsAahgrfGJwCHsaEADSUKhiAEpKclhEVAxsPCIyHIAyEPDiSKgYuITIZNo00IB-bNyoNvhkdCxcAhJSLJCAejGoADoZulIgA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=Node-6&version=7.2.2) (do not forget `@babel/plugin-syntax-flow`)

```js
type $FragmentRef<T> = any

type $RelayProps<Props, RelayPropT> = $ObjMap<
  $Diff<Props, { relay: RelayPropT | void }>,
  (<T: { +$refType: any }>( T) =>  $FragmentRef<T>) &
  (<T: { +$refType: any }>(?T) => ?$FragmentRef<T>)
  // ...
>
```

**Output Code**

```js
type $FragmentRef<T> = any;
type $RelayProps<Props, RelayPropT> = $ObjMap<$Diff<Props, {
  relay: RelayPropT | void
}>, <T: {
  +$refType: any
}>(T) => $FragmentRef<T> & <T: {
  +$refType: any
}>(?T) => ?$FragmentRef<T> // ...
>;
```

Notice the missing brackets. Prettified (😅) code:

```js
type $FragmentRef<T> = any;
type $RelayProps<Props, RelayPropT> = $ObjMap<
  $Diff<
    Props,
    {
      relay: RelayPropT | void
    }
  >,
  <
    T: {
      +$refType: any
    }
  >(
    T
  ) => $FragmentRef<T> &
    (<
      T: {
        +$refType: any
      }
    >(
      ?T
    ) => ?$FragmentRef<T>) // ...
>;
```

Meaning of this code is different from the original.

**Expected behavior/code**
It doesn't change the code in any incompatible way. It should return basically the same since there is no additional transpilation.

Currently, I can workaround it like this which is not nice at all:

```js
/*::

type $FragmentRef<T> = any

type $RelayProps<Props, RelayPropT> = $ObjMap<
  $Diff<Props, { relay: RelayPropT | void }>,
  (<T: { +$refType: any }>( T) =>  $FragmentRef<T>) &
  (<T: { +$refType: any }>(?T) => ?$FragmentRef<T>)
  // ...
>

*/
```

**Comment by nicolo-ribaudo** [comment]
If you (or anyone else) wants to open a PR, this file exports some functions used to decide wheter a node needs to be wrapped in parentheses or not:
https://github.com/babel/babel/blob/master/packages/babel-generator/src/node/parentheses.js

**Comment by tanhauhau** [comment]
Can I give it a try?

**Comment by nicolo-ribaudo** [comment]
Yup :+1:

**Comment by jonatoni** [comment]
Hello @tanhauhau. Thanks a lot for fixing the issue, it was very helpful for us. We, Kiwi.com, are supporting open source projects and appreciating the work that volunteers put into the projects, that's why we would like to offer you a 100 EUR flight voucher as a way to say thank you for fixing this issue. 🎉 Please contact me on code@kiwi.com so I can send you the voucher.
