### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by EvandroLG** [babel/babel#9515]
## Bug Report

**Current Behavior**
I'm trying to use babel/present-env and I identified a possible bug to compile es6 module.
I'm receiving the following error in the browser after the compilation:
```
Uncaught ReferenceError: require is not defined
```

Basically, Babel is creating a function called `require` and it doesn't create it anywhere.

**Input Code**
```js
import Places from './places.js';
import Form from './form.js';

document.addEventListener('DOMContentLoaded', async () => {
    const places = new Places();
    await places.getCurrentPosition();
    places.searchByOpenPlaces();

    const form = new Form();
    form.bindSubmit(places.searchByOpenPlaces.bind(places));
}, false);

```

**Output after compilation **
```js
"use strict";

var _places = _interopRequireDefault(require("./places.js"));

var _form = _interopRequireDefault(require("./form.js"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

document.addEventListener('DOMContentLoaded', async () => {
  const places = new _places.default();
  await places.getCurrentPosition();
  places.searchByOpenPlaces();
  const form = new _form.default();
  form.bindSubmit(places.searchByOpenPlaces.bind(places));
}, false);
```

**Babel Configuration (.babelrc)**

```js
{
    "presets": [
        [
            "@babel/preset-env",
        {
            "targets": {
                "esmodules": true
            }
        }
        ]
    ]
}

```

I'm using the following command to compile:
```sh
node_modules/.bin/babel src/index.js --out-file dist/index.js
```

**Comment by nicolo-ribaudo** [comment]
Babel needs a module loader to load imports. It defaults to commonJS (which is used in node), but you can specify `"modules": "amd"` or `"systemjs"` in your preset options to use a browser-based loader.

I recommend using `"module": false` (which doesn't transpile `import`s) and use webpack or rollup to transpile it and concatenate your files.

**Comment by EvandroLG** [comment]
@nicolo-ribaudo tks!
