### ISSUE TITLE
Temporarily disable all visitors for class.

### ISSUE THREAD

**Issue by CreatorVilius** [babel/babel#9525]
I have made a new class declaration which I put in Block Statement. When I replace class with Block Statement which contains other class, it creates endless loop. I want to temporarily disable visitors. Why am I replacing class with another class? I am trying to turn this:
```js
class A {
    B = 10
    static C = 20
}
```
To
```js
let A = (function() {
    class A {}
    Object.defineProperties(A.prototype, {
        B: {
            value: 10,
            writable: true
        }
    })
    Object.defineProperties(A, {
        C: {
            value: 20,
            writable: true
        }
    })
    return A
})()
```

Why am I not asking this in stackoverflow? My questions left unanswered in stackoverflow and I have to delete them, simply because they will be probably answered in like 10 years when I won't care.

**Comment by nicolo-ribaudo** [comment]
In our plugins we usually add the new class to a WeakSet and avoid transforming it again if it is already there.

**Comment by CreatorVilius** [comment]
But can't we get one without all Visitors? This could help in some cases, like I am doing. The best I could do is use `replaceWithSourceString`, but I can't transform classes, their methods, etc. to String. At least ability to somehow turn BlockStatement to string would be good.

**Comment by JLHwung** [comment]
Implementing this feature will introduce unnecessary complexity to the traverser, which is very performance-sensitive on the memory layout. As @nicolo-ribaudo has mentioned the `WeakSet` solution, closing this issue as won't fix.
