### ISSUE TITLE
babel parserOpts.parser and generatorOpts.generator not working

### ISSUE THREAD

**Issue by emrul** [babel/babel#9527]
## Bug Report

**Current Behavior**
I'm upgrading from Babel 6 to Babel 7.  Most things work except my parserOpts.parse and generatorOpts.generator do not appear to get used anymore.  I was using recast in Babel 6 and want to continue using it.

**Input Code**
- I migrated to using babel.config.js and based my template on the test here: https://github.com/babel/babel/blob/master/packages/babel-core/test/api.js (parser and generator options)

```js
const recast = {
    parse: function (code, opts) {
        debugger;
        return opts.parser.parse(code);
    },
    print: function (ast) {
        debugger;
        return generator(ast);
    },
};

debugger;

module.exports = function (api) {
  const babelEnv = api.env();

  return {
    "plugins": [
      "transform-class-properties"
    ],
    "compact": false,
    "sourceType": "module",
    "parserOpts": {
      "parser": recast.parse,
      "format": {
        "indent": {
          "adjustMultilineComment": false,
          "style": "    "
        }
      }
    },
    "generatorOpts": {
      "generator": recast.print,
      "compact": false,
      "format": {
        "indent": {
          "adjustMultilineComment": false,
          "style": "    "
        }
      }
    }
  }
  ;
};
```

I used NDB to ensure that the code was being loaded and it does hit the main debugger line in babel.config.js however, the babel process completes without hitting either the `parse` or `print` functions I've defined which is why I believe these options are not being invoked. 

** Possible Solution **
Edit: just found the following on Slack and it appears to solve my problem:
```
const { parse, print } = require("recast");
 
module.exports = function pluginRecast(){
  return {
    parserOverride(code, opts, parser) {
      return parse(code, {
        ...opts,
        parser: {
          parse: source => parser(source, opts),
        },
      });
    },
    generatorOverride(ast, opts) {
       return print(ast, opts);
    },
  };
};
```
**Environment**
- Babel version(s): 7.2.3 (@babel/core 7.3.3)
- Node/npm version: Node v11.9.0 / NPM 6.8.0
- OS: Mac OSX 10.14.2 (18C54)
- Monorepo: no
- How you are using Babel: cli

**Comment by Nilegfx** [comment]
@emrul thanks for hinting the workaround, however, as a newbie to babel plugins, it took me sometime to understand how/where should I implement your code snippet, I think the original [comment here ](https://github.com/babel/babel/pull/6781#issue-151579061) explains it in more details

**Comment by nicolo-ribaudo** [comment]
Yeah, this was an intended api change!
