### ISSUE TITLE
Babel throwing error about exportDefaultFrom when there is no default export with TypeScript

### ISSUE THREAD

**Issue by samjmckenzie** [babel/babel#9528]
## Bug Report

**Current Behavior**
I'm using the `preset-typescript` preset and it's configured with the `.babelrc` file. 
When trying to import an enum from a file outside of the project root folder, Babel will throw an error saying the following: `Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled`
This error isn't thrown when I try to import a class or constant from files outside of the project root. Seems to only be with enums. 
Full erorr:  
```
ERROR in ../shared/enum-test.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/sammckenzie/babel-typescript-issue/shared/enum-test.ts: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):

> 1 | export enum EnumTest {
    |        ^
  2 |     Test,
  3 | }
  4 | 
```

**Input Code**
https://github.com/samjmckenzie/babel-typescript-issue

**Expected behavior/code**
I expect the code to transpile successfully.

**Babel Configuration (.babelrc)**
```
{
    "presets": [
        "@babel/preset-typescript"
    ]
}
```

**Environment**
- Babel version(s): babel-core 7.3.3, babel-loader 8.0.5
- Node/npm version: Node 11.7.0
- OS: macOS 10.14.2
- How you are using Babel: webpack 4.29.4

**Possible Solution**
The issue can be fixed by including the options in the webpack config file instead of `.babelrc` or by moving all the files to the source folder inside the project root instead of outside the project root. I have included a working `webpack.working.js` webpack config and a broken `webpack.broken.js` webpack config in the issue repo.

**Comment by CadsoftBrianW** [comment]
I'm getting the same issue. Did you find a solution?

**Comment by samjmckenzie** [comment]
I did find a temporary solution. I explained it at the end of the issue report. Hope it helps.

**Comment by nicolo-ribaudo** [comment]
@samjmckenzie In your repo a possible problem is that `.babelrc` is only applied to the current floder/package, so it isn't applied to `shared`. Using `babel.config.js` could fix it. If it doesn't, I will download your repo.

**Comment by samjmckenzie** [comment]
Yeah, I found that putting the Babel config into my webpack config fixed the issue. However, this was not at all obvious and I don't recall reading about this anywhere in the documentation. It could be that I missed it somewhere. The error message didn't really help either.

**Comment by existentialism** [comment]
@samjmckenzie would love feedback on https://babeljs.io/docs/en/configuration!

**Comment by CadsoftBrianW** [comment]
Thanks that did the trick!

**Comment by matildahfy** [comment]
hi, i could fix my problem:   

./node_modules/react-icons/md/index.js
SyntaxError: C:\Users\User\Desktop\burger\node_modules\react-icons\md\index.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):

> 1 | export Md3dRotation from './3d-rotation';
    |        ^
  2 | export MdAcUnit from './ac-unit';
  3 | export MdAccessAlarm from './access-alarm';
  4 | export MdAccessAlarms from './access-alarms';

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation. 

Kindly help me . Thanks

**Comment by nicolo-ribaudo** [comment]
@matildahfy Did you add that plugin to your configuration?
Did you use `babel.config.js`? (it's needed to transpile files in different packages, e.g. inside `react-icons`)
