### ISSUE TITLE
Class binding issue with var

### ISSUE THREAD

**Issue by lukescott** [babel/babel#953]
Spawned from this discussion: https://esdiscuss.org/topic/class-double-bind

"log" does not get printed (currently not supposed to, unless something changes as a result to above discussion):
```javascript
class Foo {
  foo() {
    
  }
  
  static newFoo() {
    return new Foo();
  }
}

Foo = class extends Foo {
  foo() {
    super.foo();
    console.log("log");
  }
};

Foo.newFoo().foo();
```

 But this doesn't work either:
```javascript
var Foo = class {
  foo() {
    
  }
  
  static newFoo() {
    return new Foo();
  }
}

Foo = class extends Foo {
  foo() {
    super.foo();
    console.log("log");
  }
};

Foo.newFoo().foo();
```

The second version generates the same code as the first, but the second works in Traceur.

**Comment by sebmck** [comment]
See #952.
