### ISSUE TITLE
Spurious newlines are added around block comments 

### ISSUE THREAD

**Issue by arv** [babel/babel#9547]
## Bug Report

**Current Behavior**
The code printer adds a newlines before and after block comments

**Input Code**

Input:

```js
f(/* hi */ b);
```

Output:

```js
f(
  /* hi */
  b
);

```

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYCg9AVABAFgllCYoCMCUBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=false&presets=es2016%2Ces2017%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=&version=7.3.3

```js
function f() {
  return /* bye */ 42;
}
```
Output:

```js
function f() {
  return (
    /* bye */
    42
  );
}
```

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMAFASkQbwFCMQJwFMoR8kB6AKkQCMBPQxS8xAFgCYBubAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=false&presets=es2016%2Ces2017%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=&version=7.3.3

**Expected behavior/code**
I expect there to be no extra newlines added when the block comment is attached to an expression. Only add newlines when the comments are attached to statements.

**Environment**
- Babel version(s): 7.3.3

**Comment by hatchette** [comment]
Additionally, line comments are added to wrong node.

input:
```
// a
const x = 1;

// b
const y = 2;
```

output:
```
// a
const x = 1; // b

const y = 2;
```



https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEEMCgGMHsDsDOAXUAPUBeUBGA3JJCKAEYwIqgCeWoATAUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.4.3&externalPlugins=
