### ISSUE TITLE
[bug report] - plugin-transform-typescript doesn't function correctly with 2 pragmas

### ISSUE THREAD

**Issue by vidarc** [babel/babel#9549]
## Bug Report

**Current Behavior**
Using version 7.3.2 of plugin-transform-typescript results in unexpected behavior. Using `/** @jsx jsx */` at the top of the file works for that one, but files that are just plain react will remove the `import React from 'react'`. 

Versions of plugin-transform-typescript before 7.3.2 work as expected. I assume this PR: https://github.com/babel/babel/pull/9095 is the one that broke this.

**Input Code**
- REPL or Repo link if applicable:

File A
```js
/** @jsx jsx */
import { css, jsx } from '@emotion/core'

....code
```

File B
```js
import React from 'react'

.....code
```

File A gets output as expected. File B gets output as expected, except for the React import being removed. Adding `/** @jsx React.createElement */` at the top does not fix this. Produces same result.

**Expected behavior/code**
I expect `/** @jsx jsx */` to only effect the file it is in

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["@babel/plugin-transform-typescript", {
      "isTSX": true,
    }],
    "@babel/plugin-syntax-jsx",
    "@babel/plugin-transform-react-jsx",
  ]
}
```

**Environment**
    "@babel/cli": "7.2.3",
    "@babel/core": "7.3.3",
    "@babel/plugin-syntax-jsx": "7.2.0",
    "@babel/plugin-transform-react-jsx": "7.3.0",
    "@babel/plugin-transform-typescript": "7.2.0",
    "babel-loader": "8.0.5",

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9798
