### ISSUE TITLE
validation.undeclaredVariableCheck incorrectly flags 'export as' construct

### ISSUE THREAD

**Issue by artdent** [babel/babel#956]
If you enable the optional "validation.undeclaredVariableCheck" transform, it incorrectly complains about the following ES6 construct:
````javascript
class Foo {}
export Foo as Bar;
````
You get the following error:
`ReferenceError: myfile.js: Line 2: Reference to undeclared variable "Bar"`

It looks like the check doesn't realize that "as Bar" creates a new name.

This is using babel 4.6.6.

**Comment by artdent** [comment]
whoops, syntax error: that export line should have read `export {Foo as Bar};`.

**Comment by sebmck** [comment]
Fixed as of 4.7.0, thanks!
