### ISSUE TITLE
[typescript] async arrow function property with generics fails parser

### ISSUE THREAD

**Issue by milesj** [babel/babel#9560]
## Bug Report

**Current Behavior**

In the current `@babel/parser` version 7.3.3, a class property that defines an async arrow function with generics breaks the parser.

```
    SyntaxError: boost/packages/core/src/Executor.ts: Unexpected token, expected ";" (85:52)

      83 |    * Execute a task with the provided value.
      84 |    */
    > 85 |   executeTask = async <T>(task: Task<Ctx>, value?: T): Promise<any> => {
         |                                                      ^
      86 |     const { console: cli } = this.tool;
      87 |     let result = null;
      88 | 

      at Object.raise (node_modules/@babel/parser/lib/index.js:3831:17)
```

If you remove the `<T>` generics or the `async/await`, the parser works.

**Input Code**

```ts
  executeTask = async <T>(task: Task<Ctx>, value?: T): Promise<any> => {
    const { console: cli } = this.tool;
    let result = null;

    cli.emit('task', [task, value, this.parallel]);

    try {
      result = await task.run(this.context, value);

      if (task.isSkipped()) {
        cli.emit('task.skip', [task, value, this.parallel]);
      } else {
        cli.emit('task.pass', [task, result, this.parallel]);
      }
    } catch (error) {
      cli.emit('task.fail', [task, error, this.parallel]);

      throw error;
    }

    return result;
  };
```

**Expected behavior/code**

It parses. This worked in the previous version.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  "babelrc": false,
  "comments": false,
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-catch-binding",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-syntax-dynamic-import",
    [
      "babel-plugin-transform-dev",
      {
        "evaluate": false
      }
    ]
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs",
        "shippedProposals": true,
        "targets": {
          "node": "10.9.0"
        },
        "useBuiltIns": false
      }
    ],
    "@babel/preset-typescript"
  ]
};
```

**Environment**
- Babel version(s): 7.3.3
- Node/npm version: 10.14.1/6.5.0
- OS: OSX 10.14.3
- Monorepo: yes
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
It's working for me on master. Could you share a bigger code snippet?

**Comment by milesj** [comment]
This is the entire snippet, heres the full file: https://github.com/milesj/boost/blob/master/packages/core/src/Executor.ts#L85

**Comment by milesj** [comment]
You may be right. I tried re-creating it here: https://github.com/milesj/boost/pull/42

Isn't crashing anymore. Perhaps a bad cache or node modules? I'll tinker around a bit more.

**Comment by nicolo-ribaudo** [comment]
Maybe there is an old parser version in your node modules? Try tu run `npx nls why @babel/parser`

**Comment by milesj** [comment]
Looks like it. If you look at my PR, the `yarn.lock` diff shows multiple versions of `@babel/core` and `@babel/parser`. Perhaps the wrong version was being pulled in.

I have no idea why yarn isn't flattening them.

**Comment by milesj** [comment]
Was able to reproduce. Deleted `yarn.lock`, re-installed deps, and the error occurs. Here's another PR: https://github.com/milesj/boost/pull/43

**Comment by nicolo-ribaudo** [comment]
Thank you, I was able to reduce the bug to this code:

```js
class Cl {
  a = async<T>() => {
    await 0;
  };

  b = async <T>(value?) => {
  };
}
```

I'm working on it.

**Comment by milesj** [comment]
Awesome thanks!
