### ISSUE TITLE
when I run my babel-node ,I got error with plugin @babel/plugin-proposal-object-rest-spread"

### ISSUE THREAD

**Issue by harmnot** [babel/babel#9564]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**

 throw Object.assign(err, {
  ^

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
What is your package.json?

**Comment by harmnot** [comment]
```
({
  "name": "express-from-scratch",
  "version": "1.0.0",
  "description": "Learn Express",
  "main": "app.js",
  "scripts": {
    "start": "nodemon --exec babel-node --presets env app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/bold-fox"
  },
  "author": "blabla",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/bold-fox-2018/express-from-scratch/issues"
  },
  "dependencies": {
    "ejs": "^2.6.1",
    "express": "^4.16.4"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.3.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-preset-es2015": "^6.24.1"
  },
  "resolutions": { "babel-core": "^7.0.0-bridge" }
}
)

```


here you go,,
when I remove proposal object rest spread on my .babelrc plugin, my app.js is not has any problem, when I put that plugin, it got error like I said before

**Comment by harmnot** [comment]
everything I run my app babel app.js on my nodejs, it doesn't work 
and always said like this , I renew my package json also just few mins ago 

You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install --save-dev babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.

I did read on that link and install new babel 

```
"dependencies": {
    "ejs": "^2.6.1",
    "express": "^4.16.4",
    "nodemon": "^1.18.10"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.3",
    "babel-preset-env": "^1.7.0"
  }
```

.babelrc 

```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}

```

**Comment by nicolo-ribaudo** [comment]
You need to also install preset-env 7.
