### ISSUE TITLE
readonly properties on Typescript interface cause babel to generate an error

### ISSUE THREAD

**Issue by StokeMasterJack** [babel/babel#9567]
This interface is used in TypeScript docs:

interface Point {
    readonly x: number;
    readonly y: number;
}

But I am getting this error message:

ERROR in ./boRoutes/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Volumes/repos/r/dev/ramko/react/boRoutes/index.tsx: Unexpected token, expected ":" (18:13)

  16 | 
  17 | interface Point {
> 18 |     readonly x: number;
     |              ^
  19 |     readonly y: number;
  20 | }

**Comment by danez** [comment]
When I try this in the repl it works fine. Are you sure typescript is enabled?

Because if i enable flow instead of typescript i get the same error, which is correct as flow does not have this syntax for readonly.
