### ISSUE TITLE
When installing babel-cli, npm audit gives warning in braces package

### ISSUE THREAD

**Issue by volaka** [babel/babel#9578]
## Bug Report

**Current Behavior**
When installing babel-cli with `npm i -D babel-cli`, npm audit gives low vulnerability with package `braces`.
The low vulnerability is `Regular Expression Denial of Service`.
**Input Code**
- npm i -D babel-cli

**Expected behavior/code**
No vulnerability warnings.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "name": "backend",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www",
    "dev": "DEBUG=backend:* npm start"
  },
  "dependencies": {
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.9",
    "express": "~4.16.0",
    "morgan": "~1.9.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0"
  }
}
```

**Environment**
- Babel version(s): v6.26.0
- Node/npm version: Node 8.11.5/ npm 6.4.1
- OS: OSX 10.14.3
- How you are using Babel: `cli`

**Additional context/Screenshots**
<img width="565" alt="screen shot 2019-02-25 at 10 56 18" src="https://user-images.githubusercontent.com/13176256/53322552-c3cdea00-38ec-11e9-864a-564f956d9e4d.png">

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/commit/879a59085b4c6bf7fae744abe758774047427a58, it will be released soon

**Comment by volaka** [comment]
@nicolo-ribaudo Thank you, I will try to upgrade then.
