### ISSUE TITLE
Class prototype problem

### ISSUE THREAD

**Issue by quangbuule** [babel/babel#959]
I have a nodejs file:
```js
'use strict'

class Foo {
  bar() {
    // This is a function
  }
};

console.log(Foo.prototype);
```

When using node --harmony, the output is:
```
{ bar: [Function: bar] }
```

When using babel-node, the output is:
```
{}
```

Is that a problem?

**Comment by sebmck** [comment]
You're using an old or uncompliant version of Node/V8 that has enumerable methods.

**Comment by quangbuule** [comment]
Do you mean that the Class don't have prototype anymore?

**Comment by sebmck** [comment]
No they do. Class methods are just non-enumerable so they appear hidden and don't show up when iterating over them.

**Comment by quangbuule** [comment]
Seem like I can't get the Class prototype functions, or extend Class prototype outside anymore.

```js
Foo.prototype.bar2 = () => {
  console.log(this);
};
```

become:

```js
Foo.prototype.bar2 = function () {
  console.log(undefined);
};
```

**Comment by sebmck** [comment]
@quangbuule Please see the [FAQ](http://babeljs.io/docs/faq/) notably "[Why is this and arguments being remapped in arrow functions?](http://babeljs.io/docs/faq/#why-is-this-and-arguments-being-remapped-in-arrow-functions-)" and "[Why is this being remapped to undefined?](http://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-)".

**Comment by quangbuule** [comment]
Thanks so much, It may be my misunderstand when I define a class in the past ES5, It look like:

```js
function Foo() {
  // Construction here
}

Foo.prototype.bar = function () {
  // this is instance method
}
```
