### ISSUE TITLE
@babel/generator version 7.3.4 not found

### ISSUE THREAD

**Issue by or-bd** [babel/babel#9592]
## Bug Report

**Current Behavior**
`@babel/generator 7.3.4` doesn't exist, at the NPM package page it says that the current version is 7.3.4 but actually after downloading it the version is 7.3.3 - the main issue is that `@babel/core` require `@babel/generator 7.3.4` and failed because npm says that No matching version found for @babel/parser@^7.3.4.

**Expected behavior/code**
`npm i -D @babel/generator` should install the version mentioned on the NPM page (current 7.3.4).

**Environment**
- Babel version(s): @babel/core": "^7.2.2"
- Node/npm version: node 8.12.0
- OS: OSX 10.14.2
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
You need to clean your local npm cache, and the proxy cache if you are using it.

**Comment by flyvekristoffer** [comment]
I experience the same problem with **@babel/parser**, **@babel/traverse** and **@babel/types**.

```
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @babel/types@^7.3.4
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of '@babel/generator'
> npm ERR! notarget
```

`npm view @babel/traverse version`,
`npm view @babel/parser version` and
`npm view @babel/types version` all reports `7.2.3` as beeing the latest.

But i do get `7.2.4` from:
`npm view @babel/generator version`

`npm cache verify`or `npm cache clean --force` did not solve the issue.

**Comment by nicolo-ribaudo** [comment]
Are you using a proxy? Those packages are at v7.3.4: 
https://www.npmjs.com/package/@babel/types
https://www.npmjs.com/package/@babel/parser
https://www.npmjs.com/package/@babel/traverse

**Comment by nicolo-ribaudo** [comment]
It seems that you are affected by https://npm.community/t/npm-view-npm-install-cant-find-latest-package-version/1590/8

**Comment by catagranic** [comment]
I am having this same issue but with the recently uploaded version 7.4.4.

**Comment by nicolo-ribaudo** [comment]
That's not something we can solve; it's either a problem with your npm proxy (in you are using it) or with npm itself.
