### ISSUE TITLE
Proposal: Switch Expression

### ISSUE THREAD

**Issue by koblas** [babel/babel#9603]
## Feature Request

**Is your feature request related to a problem? Please describe.**

This is an improvement to syntax for a standard pattern.

**Describe the solution you'd like**

It's very common to need to compute a value based on a switch statement.  Currently, there are two ways to do this, but both are either hard to understand or prone to error.

This is unmaintainable -- 
```
    const x = v === 'foo' ? 1 : v === 'bar' ? 3 : v === 'baz' ? 6 : 99;  
```
This is maintainable, but is less than ideal:

```
   let x;

   switch (v) {
   case "foo":
     x = 1;
     break;
   case "bar":
     x = 3;
     break;
   case "baz":
     x = 6;
     break;
   default:
     x = 99;
     break;
   }
```

This would all be simpler with allowing switch statement to become switch expressions, like so:

```
   const x = switch (v) {
     case "foo" => 1;
     case "bar" => 3;
     case "baz" => 6;
     default => 99;
   }
```

What I really like is that it preserves all of the normal JavaScript syntax with the small change that a switch is allowed in an expression provided that all of the cases evaluate to expressions hence the use of the '=>' as an indicator.  Fundamentally this is a very basic concept where you have a state machine and need it switch based on the current state and evaluate to the new state.

```
   const nextState = switch (currentState) {
      case ... => 
   }
```

**Describe alternatives you've considered**

There are two Stage 1 proposals that touch on this, but in the case of pattern matching they are still a statement or do expressions which appears to be overly complex for the task.  The problem that I see and want to address is the need to have something that removes the need to chain trinary expressions together to have an Expression.

Pattern matching does shorten the code, but you have a weird default case and also still end up with a loose variable and since pattern matching is a statement you still have an initially undefined variable.

```
   let x;

   case (v) {
     when "foo" -> x = 1;
     when "bar" -> x = 3;     
     when "baz" -> x = 6;
     when v -> x = 99;
   }
```

Let's try do expressions, I'll leave people's thoughts to themselves.  
```
   const x = do {
     if (v === "foo") { 1; }
     else if (v === "bar") { 3; }
     else if (v === "baz") { 6; }
     else { 99; }
   }
```

Or as another do expression variant:

```
   const x = do {
     switch (v) {
       case "foo": 1; break;
       case "bar": 3; break;
       case "baz": 6; break;
       default: 99; break;
     }
   }
```

**Teachability, Documentation, Adoption, Migration Strategy**

No migration is necessary since it's new syntax.

**Comment by jhpratt** [comment]
I still don't see why this wouldn't be covered in its entirety by the pattern matching proposal.

**Comment by koblas** [comment]
Jacob,

Pattern matching is still a statement, rather than an expression.  
Pattern matching still requires the following:

     let x;

     case (v) {
       when "foo" -> x = 1;
       when "bar" -> x = 3;
       when "baz" -> x = 6;
       when v -> x = 99;
     }

Rather than

     const x = switch (v) {
       case "foo" => 1;
       case "bar" => 3;
       case "baz" => 6;
       default => 99;
     }

**Comment by jhpratt** [comment]
Granted, and that's what do-expressions are for.

**Comment by koblas** [comment]
Do expression do cover this as well, as mentioned in the original issue.  If they were a stage 3 proposal, I would probably not be making this suggestion.

**Comment by nicolo-ribaudo** [comment]
This isn't the right place to propose new javascript features :wink:
You can read https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals to know how to do it.
