### ISSUE TITLE
@babel/plugin-transform-typescript can insert public property initialization before the call to super.

### ISSUE THREAD

**Issue by coreyfarrell** [babel/babel#9609]
## Bug Report

**Current Behavior**
`@babel/plugin-transform-typescript` inserts public property initialization at the start of the constructor when `super()` is not the very first statement.

**Input Code**

```js
class A {
}

class B extends A {
  constructor(public p: string) {
    console.log('anything before super');
    super();
  }
}
```

**Expected behavior/code**
`this.p = p;` should be added after the call to `super();`.

**Babel Configuration (.babelrc)**

```js
{
  "plugins": ["@babel/plugin-transform-typescript"]
}
```

**Environment**
- Babel version(s): @babel/core 7.3.4, @babel/plugin-transform-typescript 7.3.2
- Node/npm version: node 10.15.0, npm 6.4.1
- OS: Fedora 28
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**
I'm not sure how to solve this but the issue is here:
https://github.com/babel/babel/blob/208195f42576a70798cedf1abe4d9f1d86979fcc/packages/babel-plugin-transform-typescript/src/index.js#L201-L212

**Additional context/Screenshots**
This was found by users of istanbul, istanbuljs/istanbuljs#237 and istanbuljs/babel-plugin-istanbul#185.

**Comment by nicolo-ribaudo** [comment]
We could fix it, but that is not valid TypeScript code anyway.

https://www.typescriptlang.org/play/index.html#src=class%20A%20%7B%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20constructor(public%20p%3A%20string)%20%7B%0A%20%20%20%20console.log('anything%20before%20super')%3B%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D

**Comment by coreyfarrell** [comment]
@nicolo-ribaudo Thanks for your response.  Really the example code I gave was just an absolute minimal example.  The real life example is that `babel-plugin-istanbul` inserts code to increment the coverage count of the constructor as the first statement.  So with `"plugins": ["istanbul", "@babel/plugin-transform-typescript"]` in babelrc we get the following translation:
Source:
```js
abstract class A {}
export class B extends A {
  constructor(public p: string) {
    super();
  }
}
```

```js
var cov_1zjww7ja73 = function () {
  // ... code which initializes the variable stripped for briefness
}();

class A {}

export class B extends A {
  constructor(p) {
    this.p = p;
    cov_1zjww7ja73.f[0]++;
    cov_1zjww7ja73.s[0]++;
    super();
  }
}
```

We will do what we can to not break TypeScript but `istanbul-lib-instrument` / `babel-plugin-istanbul` are producing JavaScript.  In this specific example the `cov_1zjww7ja73.f[0]++` function counter intentionally happens before the call to `super()` (really it's meant to be the first thing in the constructor).  Same with `cov_1zjww7ja73.s[0]++`, that is counting the fact that the statement `super()` is reached.  Even if `super()` throws an exception the constructor for `B` was reached, as was the statement which calls `super()`.

It's a tough situation, I appreciate your posting a PR for this.
