### ISSUE TITLE
Importing files outside the cli module directory result in error

### ISSUE THREAD

**Issue by Armaldio** [babel/babel#9615]
## Bug Report

**Current Behavior**
I have a cli app running with node.
I'm also using @babel/register with it.

This is my entry: 
```js
#!/usr/bin/env node

const path = require('path');

require('@babel/register')({
  cwd: path.resolve(__dirname),
  root: path.resolve(__dirname),
  ignore: [/node_modules/],
  extends: path.join(__dirname, 'babel.config.js'),
  rootMode: 'upward',
  filename: __filename,
  configFile: path.join(__dirname, 'babel.config.js'),
});
require('@babel/polyfill');

require('./src/app');
```
I've left all the configurations keys *i've tried*.

I have kind of a plugin system where my cli commands are classes that I then load dynamically on statup.
It works fine for files that are under my module path but it fail as soon as I try to import files under `process.cwd() + 'plugins'`

The error I have is `Error: Cannot find module 'core-js/modules/es7.symbol.async-iterator'`.
That means it try to load core-js and regenerator-runtime from the current folder. It works if I have node_modules with these two package at the root of my `process.cwd()`.
**But** this is not my intended behaviour.

**Expected behavior/code**
@babel/register should import the file at `process.cwd()` (the folder in which i'm executing the command) using `babel.config.js` and `node_modules` from `__dirname` (my cli folder) instead.

**Environment**
- Babel
```
"@babel/polyfill": "^7.2.5",
    "@babel/register": "^7.0.0",
    "@babel/runtime": "^7.3.1",
"@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.3.1",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.3.1",
    "@babel/types": "^7.3.4",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-dynamic-import-node": "^2.2.0",
    "babel-plugin-transform-runtime": "^6.23.0",
```
- Node/npm version: 10.15.0
- OS: Windows 10
- Monorepo: No
- How you are using Babel: register

Also maybe related to #8321 but can't find anything working from there.
Having `node_modules` and babel related config files inside the running directory is not an option.

I hope it's clear enough 🙏

**Comment by nicolo-ribaudo** [comment]
The root, extends, configFile and rootMode options are not needed.
What is your babel config?

**Comment by Armaldio** [comment]
Hello,

Thanks for the quick answer.

Removing `root, extends, configFile and rootMode` did not help solving the issue. Also `@babel/runtime` is not used in my project and is probably a leftoverdd added during my tests.

**Comment by nicolo-ribaudo** [comment]
What is your config? You don't need useBuiltIns in preset-env either.

**Comment by Armaldio** [comment]
This is my config (I've removed useBuiltIns):
```js
module.exports = (api) => {
  api.cache(false);

  const presets = [
    ['@babel/env'],
  ];

  const plugins = [
    ['@babel/plugin-proposal-class-properties'],
    ['@babel/plugin-proposal-object-rest-spread'],
    ['@babel/plugin-proposal-optional-chaining'],
    ['dynamic-import-node', { noInterop: true }],
  ];

  return {
    presets,
    plugins,
    sourceMaps: true,
  };
};
```

It seems to work now, but I can't understand what made it to work exactly ?

**Comment by nicolo-ribaudo** [comment]
Those core-js imports were injected by preset-env, but they weren't needed because you are already loading the polyfill.
