### ISSUE TITLE
Trivial "hello world"-style preset-typescript example fails

### ISSUE THREAD

**Issue by toolness** [babel/babel#9617]
I would expect the following to print "let x = 1;" to the console:

```js
const babel = require('@babel/core');
const code = "let x: number = 1;";
const result = babel.transform(code, {
  presets: ["@babel/typescript"]
});
console.log(result.code);
```

However, it instead results in the following error:

```
Error: [BABEL] unknown: Configuration contains string/RegExp pattern, but no filename was passed to Babel
```

This is extremely confusing because I have not passed any string/RegExp patterns to the configuration.

I can work around this problem by simply using the `@babel/plugin-transform-typescript` plugin instead of the TypeScript preset, but it's still odd that such an error is raised.  If the TypeScript preset doesn't support a use  case like this one, I think the error raised should at least say as much, instead of accusing the user of doing something they didn't actually do.

**Comment by nicolo-ribaudo** [comment]
Do you have any other Babel config file in your project? Probably it is being picked up.

**Comment by toolness** [comment]
Nope, I intentionally created this as a self-contained example.  Here's a gist so you can easily reproduce it on your end:

https://gist.github.com/toolness/ae1eac5d40360f648a2af8fbc2bd2322

**Comment by tanhauhau** [comment]
@toolness I think it wasn't explained clearly on [the docs](https://babeljs.io/docs/en/babel-preset-typescript) for cases to use `@babel/core` programmatically.

Basically if you use `@babel/preset-typescript`, it will try to use filename check on the file extension to determine whether it is a `.ts` or `.tsx` file.

To workaround this behaviour, you can either pass a filename or pass `allExtensions: true` to skip the file extension detection.

```js
// pass a filename
const result = babel.transform(code, {
  presets: ['@babel/typescript'],
  filename: 'foo.ts'
});

// turn on allExtension
const result = babel.transform(code, {
  presets: [
    [
      '@babel/typescript'
      {
        allExtensions: true
      }
    ]
  ],
});
```

By setting `allExtensions` to `true`, you will need to manually specify `isTSX` to tell whether the code is `tsx`, or else it will be `false` by default.

Hope it explains.
