### ISSUE TITLE
Provide @babel/parser es6 module release

### ISSUE THREAD

**Issue by plantain-00** [babel/babel#9619]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to import `@babel/parser` as a es6 module, but it actually only provide a commonjs release.

**Describe the solution you'd like**
Release another file, like `lib/index.mjs`, and `"module": "lib/index.mjs"` in `package.json`

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by nicolo-ribaudo** [comment]
What's your usecase? Node (and every tool) supports loading commonjs from es modules, and tree-shaking  wouldn't affect babel/parser.

**Comment by plantain-00** [comment]
My use case is loading it in webpack, but somehow, it shows `exports is not defined`.
I use acorn instead later.

**Comment by nicolo-ribaudo** [comment]
It might be a problem with your webpack config. We are bundling it (in Babel standalone) without problems.
