### ISSUE TITLE
Remove dependency on 'home-or-tmp' package

### ISSUE THREAD

**Issue by IvanGoncharov** [babel/babel#9620]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It's a useless dependency, since the entire package content is:
```js
'use strict';
const os = require('os');

module.exports = os.homedir() || os.tmpdir();
```

**Describe the solution you'd like**
Use `os.homedir() || os.tmpdir()` instead of `home-or-tmp` package:
https://github.com/babel/babel/blob/eac4c5bc17133c2857f2c94c1a6a8643e3b547a7/packages/babel-register/src/cache.js#L4

P.S. Don't have time to setup enviroment myself but I think it would be a great `good first issue`.
Also would be great if someone checks `package.json`s for useless dependencies like this.

**Comment by nicolo-ribaudo** [comment]
:+1: That package isn't needed since node 2.3

**Comment by IvanGoncharov** [comment]
> That package isn't needed since node 2.3. It's only 219 bytes anyway 

@nicolo-ribaudo I'm more worried about the number of packages. For example in `graphql-js` we use `ESLint` + `Mocha` + `Chai` + `nyc` + `babel` which is really pretty minimalistic set of `devDependencies` and it still result in 400+ packages and `yarn.lock` that is 2k+ lines.

**Comment by tanhauhau** [comment]
@nicolo-ribaudo can i work on it?

**Comment by nicolo-ribaudo** [comment]
Maybe you could leave this to someone who never contributed?

**Comment by AmirS** [comment]
Hi, anyone currently working on this? If not I'd like to help out with this enhancement.
