### ISSUE TITLE
babel-preset-env useBuiltins: 'usage' fails to polyfill all usages for given target

### ISSUE THREAD

**Issue by tstirrat15** [babel/babel#9625]
## Bug Report

**Current Behavior**
We want to target Chrome 41 with babel-preset-env, and preferably leverage `useBuiltins: 'usage'` to keep bundle size as small as possible.

However, it doesn't seem as though it correctly identifies all necessary polyfills, especially in npm packages. We see `TypeError: undefined is not a function` errors in our application code when run against Chrome 41. We can fix the issue by switching to `useBuiltIns: 'entry'`, but that increases the bundle size by about 50kb (out of 80kb possible for core-js).

I've been having trouble isolating specific instances of an undefined property, method, or language feature. Is there a recommended way to go about this?

`redux-logger` is one package that fails to be sufficiently polyfilled, though the import is the compiled version of the package, so it's hard to isolate what exactly is failing. [Here's the rollup config](https://github.com/LogRocket/redux-logger/blob/master/rollup.config.js) if that helps.

Also, we're using `babel.config.js` and still seeing this issue. Should `.babelrc` vs `babel.config.js` have an impact on the behavior of this option?

**Input Code**
I haven't gotten to a minimal repro yet. I can work on one if it's necessary.

**Expected behavior/code**
Compiled code with `useBuiltIns: 'usage'` should execute correctly on Chrome 41.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  plugins: [
    'react-hot-loader/babel',
    'universal-import',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-class-properties',
    ['@babel/plugin-transform-runtime', { regenerator: true }],
  ],
  presets: [
    ['@babel/env', { useBuiltIns: 'usage' }],
    '@babel/react',
  ],
  env: {
    production: {
      plugins: [
        [
          'transform-react-remove-prop-types',
          { removeImport: true },
        ],
      ],
    },
  },
};

```

**Environment**
- Babel version(s): v7.3.4
- Node/npm version: Node 8, npm 6
- OS: ubuntu, nodejs docker image
- Monorepo: no
- How you are using Babel: `loader`

**Comment by nicolo-ribaudo** [comment]
We need to know exactly which methods aren't polyfilled.

**Comment by tstirrat15** [comment]
At least one of the errors is, because the set of errors changes when we remove the dependency. That package is https://github.com/LogRocket/redux-logger/. I've been having trouble identifying the specific usage that causes the error, though, because the chrome debugger points to the minified distribution code at the beginning of the file, and not at any particular usage.

**Comment by nicolo-ribaudo** [comment]
Ok, if you want Babel to inject polyfills also for your deps, you can either run `@babel/preset-env` on `node_modules` or use the [`include`](https://babeljs.io/docs/en/next/babel-preset-env.html#include) option.

**Comment by tstirrat15** [comment]
So the default behavior for babel is that it does not transpile `node_modules` packages?

And I take it the `include` option would be useful if I knew which plugins/polyfills I needed beforehand? Or is there a way to say "include `node_modules`" using the `include` option?

**Comment by nicolo-ribaudo** [comment]
> So the default behavior for babel is that it does not transpile node_modules packages?

It depends on your webpack config: how are you using babel-loader?

> And I take it the include option would be useful if I knew which plugins/polyfills I needed beforehand?

Yeah exactly.

**Comment by tstirrat15** [comment]
In module.rules:
```javascript
  test: /\.js/,
  loader: 'babel-loader',
  options: {
    presets: [
      // overriding modules behavior for webpack/terser tree-shaking purposes
      ['@babel/preset-env',
        {
          modules: false,
          targets,
        },
      ],
      '@babel/preset-react',
    ],
  },
```

This just occurred to me too: do babel and webpack merge the options set here with those set in `.babelrc`, or are they overwritten?

**Comment by nicolo-ribaudo** [comment]
That config looks correct, and the options are merged.
I think that this could be a real bug then. I know that it is hard, but could you try to isolate the function that throws?

**Comment by caseycesari** [comment]
I'm seeing the same issue with `redux-logger` using the following config:

```
{
    test: /\.jsx?$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
    query: {
        presets: ['@babel/react', ['@babel/preset-env', {
            targets: "> 0.25%, not dead",
            useBuiltIns: 'usage',
            modules: 'false',
        }]]
    },
},
```

Including `node_modules` is not an option for me (I'm using this on an application that has lots of dependencies, and including `node_modules` introduces too many new problems), so I tried to just include the polyfill that `redux-logger` needs:

````
include: [`es6.object.assign`]
```

The `object.assign` polyfill is now being included (I verified this using `webpack-bundle-analyzer`), but I'm still getting the same error. 

![image](https://user-images.githubusercontent.com/1042475/55244836-53cac080-5218-11e9-9743-ae90cf23eeb3.png)

![image](https://user-images.githubusercontent.com/1042475/55244864-5fb68280-5218-11e9-8729-c54397221b30.png)

**Comment by nicolo-ribaudo** [comment]
```
include: [`es6.object.assign`]
```
this means "Include this module even if you (preset-env) think that it is already supported". Since `preset-env` doesn't see this module as used, it doesn't even check if it isn't supported.
You need to manually add
```
import "core-js/modules/es6.object.assign";
```
before loading the dependency that is using it.

**Comment by caseycesari** [comment]
@nicolo-ribaudo Got it. Thanks for the help and clarification.

**Comment by nicolo-ribaudo** [comment]
Babel can only find used methods in files it transpiles. If you need some polyfills for files Babel doesn't even see (e.g. if you are not transpiling node_modules), you'll need to manually include them (or use `useBuiltIns: entry`).
