### ISSUE TITLE
@babel/traverse@7.3.4 Identifier directly after number

### ISSUE THREAD

**Issue by cisen** [babel/babel#9631]
## Bug Report

**Current Behavior**

**Input Code**
https://github.com/babel/babel/blob/f195daa092ae2cbdf3d5c31c99fc50653f6e275e/packages/babel-traverse/src/context.js#L118

`10_000` make an error: Identifier directly after number。Is `10_000` include a new programmer？

**Expected behavior/code**
I would like to konw what `10_000` means, any one can tell me ? Thanks.

**Environment**
- Babel version(s): [7.2.2]
- Node/npm version: [Node 8.11.1/npm 5.6.0]
- OS: [OSX 10.13.4]
- Monorepo: [no]
- How you are using Babel: [sourcecode debug]

**Possible Solution**

**Comment by nicolo-ribaudo** [comment]
We are using https://github.com/tc39/proposal-numeric-separator
