### ISSUE TITLE
Destructuring bug when using non-latin chars

### ISSUE THREAD

**Issue by SnirShechter** [babel/babel#9632]
## Bug Report

**Current Behavior**
App throws an error 'Cannot read property '1' of null' when input ('selector' variable) is of non-latin chars only (error is on lines 6-7 in the code below).

-  Non-transpiled version of the function works fine.

- Transpiled version is expecting .match (line 6) to return an array, but when the selector is comprised of non-latin chars, it returns null (e.g 'Цвет').

- Seems like the problem is in the destructuring of the parseSelector() return value (see screenshot below).

**Input Code**
Repo:
https://github.com/baianat/vee-validate

the problem is in the transpiled version of _makeCandidateFilters found here https://github.com/baianat/vee-validate/blob/master/src/core/errorBag.js

Transpiled version of the function:
```js
ErrorBag.prototype._makeCandidateFilters = function _makeCandidateFilters (selector) {
  var matchesRule = function () { return true; };
  var matchesScope = function () { return true; };
  var matchesName = function () { return true; };

  var ref = selector.match(/((?:[\w-\s])+\.)?((?:[\w-.*\s])+)(:\w+)?/);
    var scope = ref[1]; // <--- ERROR HAPPENS HERE
    var name = ref[2];
    var rule = ref[3];
  if (rule) {
    rule = rule.replace(':', '');
    matchesRule = function (item) { return item.rule === rule; };
  }

  // match by id, can be combined with rule selection.
  if (selector.startsWith('#')) {
    return {
      isPrimary: function (item) { return matchesRule(item) && (function (item) { return selector.slice(1).startsWith(item.id); }); },
      isAlt: function () { return false; }
    };
  }

  if (isNullOrUndefined(scope)) {
    // if no scope specified, make sure the found error has no scope.
    matchesScope = function (item) { return isNullOrUndefined(item.scope); };
  } else {
    scope = scope.replace('.', '');
    matchesScope = function (item) { return item.scope === scope; };
  }

  if (!isNullOrUndefined(name) && name !== '*') {
    matchesName = function (item) { return item.field === name; };
  }

  // matches the first candidate.
  var isPrimary = function (item) {
    return matchesName(item) && matchesRule(item) && matchesScope(item);
  };

  // matches a second candidate, which is a field with a name containing the '.' character.
  var isAlt = function (item) {
    return matchesRule(item) && item.field === (scope + "." + name);
  };

  return {
    isPrimary: isPrimary,
    isAlt: isAlt
  };
};
```

**Expected behavior/code**
Function should work fine with non-latin chars.

**Babel Configuration (.babelrc, package.json, cli command)**
The default config for nuxt.js (found here - https://github.com/nuxt/nuxt.js/blob/dev/packages/babel-preset-app/src/index.js)

**Environment**
- Babel version(s): 6.26.3
- Node/npm version: Node 10
- OS: Windows 10
- Monorepo: no
- How you are using Babel: loader

**Additional context/Screenshots**
The error
![image](https://user-images.githubusercontent.com/26040325/53728657-e7a8a700-3e7b-11e9-8c64-6dcf0d9824de.png)

Non transpiled version of the function(only the first few lines)
![image](https://user-images.githubusercontent.com/26040325/53729324-a1544780-3e7d-11e9-8257-8cfe5f7f7be3.png)

**Comment by nicolo-ribaudo** [comment]
Where does that regex come from? It should be `var ref = parseSelector(selector)`

**Comment by Qantas94Heavy** [comment]
Are you accidentally getting some old version of the code? The `selector` regex is no longer used in vee-validate: https://github.com/baianat/vee-validate/commit/4fa73d8430c8292dbb03c2a8f08df1ef930875c6#diff-fc1bd09144caf4091dab975e7014096b

**Comment by danez** [comment]
No matter if the destructuring is transpiled or not if you try to destruct from null it is also an error.
```js
var { a, b, c } = null;
Uncaught TypeError: Cannot destructure property `a` of 'undefined' or 'null'.
```

```js
var ref = null;
var a = ref[0];
Uncaught TypeError: Cannot read property '0' of null
```
(Both tested in latest Chrome)

So the case where the input is null needs to be handled in the code. We cannot do anything here, babel is working correctly.

But as the others mentioned it seems the code was already modified, so you probably only need to update `vee-validate`.
