### ISSUE TITLE
Syntax error while compiling component from node_modules

### ISSUE THREAD

**Issue by andiappan-ar** [babel/babel#9633]
I have below structure and its compiling good.

- **Project**
  - Zoo
     - Src
     - Components
         - *MySharedComponents* 

When i try to move my shared components as one Project and try to install it in  other project like below structure. This gives compilation syntax error.

- **Feature** (My shared component project)
  - Src
     - Components
         - *MySharedComponents* 
- **Project**
  - node_modules
     - Feature
  - Zoo
     - Src
     - Components  

When i try to build my project its throwing syntax error in node_modules components.

Error Image : https://i.stack.imgur.com/TEynK.png 

My GIT Repo Here : https://github.com/andiappan-ar/babelIssue.git

I tried below options but nothing works,

1. Instead of manually install my shared project, i have  used lerna that also causing the same issue.

2. Currently my project doesnt have ".babelrc" file  all my babel-presets in webpackconfig itself. Even i introduce babelrc file in both project doesnt solve the issue.

3. I have cross across many git links they are saying to add presets in multiple way. but nothing work out. 
The related Issue seems still open https://github.com/facebook/create-react-app/issues/5100.

**Comment by nicolo-ribaudo** [comment]
Which command should I run in your repo?

**Comment by andiappan-ar** [comment]
Thanks for the reply , you can build my project/safarizoo using ">jss build".
Meanwhile let me check your suggestions

**Comment by andiappan-ar** [comment]
@nicolo-ribaudo i had tried your suggestions still issue is re-produced.

**Comment by liuxingbaoyu** [comment]
Because this issue is out of date, I will close it.
