### ISSUE TITLE
Ignore particular plugins on particular directories

### ISSUE THREAD

**Issue by gurs1kh** [babel/babel#9634]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I've recently had an issue with 2 babel-plugins where the plugin would cause issues in dependencies.
Though there are PRs out to fix this issue in both, it may be better for a solution on the babel level for other places where such an issue could occur.
Reference:
https://github.com/PavelDymkov/babel-plugin-auto-import/pull/4
https://github.com/vihanb/babel-plugin-wildcard/pull/32

**Describe the solution you'd like**
I think it would be good for there to be an `ignore` option that could be applied on a given plugin.
IE:
```
module.exports = function(api) {
  ...
    plugins: [
      ['auto-import', {
        declarations: [
          { path: 'react', default: 'React',  members: ['Component'] },
          { path: 'react-native', members: ['View', 'Text', 'StyleSheet', 'Platform'] },
        ],
        ignore: 'node_modules',
      }],
      ['wildcard', {ignore: 'node_modules'},
    ],
  };
};
```
Of course, I'm open to other ways of doing this.

**Describe alternatives you've considered**
Other alternatives is to request PRs on any plugins that are problematic, but sometimes they take a while to get merged (at the time of posting, neither PRs of the two problematic plugins are merged).
I guess I could republish the plugins or just install them from my own repository, but that may not be the best solution either.

**Teachability, Documentation, Adoption, Migration Strategy**
Users would be able to use this quite easily. In terms of Docs, I think it could be mentioned as an option for plugins similar to the regular `ignore` option

**Comment by nicolo-ribaudo** [comment]
You can use the [`overrides`](https://babeljs.io/docs/en/options#overrides) option:

```js
module.exports = function(
  return {
    // These plugins are run on every file
    plugins: ["@babel/transform-classes"],

    overrides: [
      {
        exclude: /node_modules/,
        plugins: [
          ['auto-import', {
            declarations: [
              { path: 'react', default: 'React',  members: ['Component'] },
              { path: 'react-native', members: ['View', 'Text', 'StyleSheet', 'Platform'] },
            ],
          }],
          'wildcard',
        ]
      } 
    ]
  };
};
```

**Comment by gurs1kh** [comment]
Oh, thanks. I've been dealing with this problem for quite a while but couldn't resolve it and wasn't aware of `overrides`.

Sorry for opening this unneeded ticket :)
