### ISSUE TITLE
Simple react ui component giving syntax error from node_modules

### ISSUE THREAD

**Issue by andiappan-ar** [babel/babel#9653]
Hi I have two plain simple react projects named "feature" and "project-safarizoo".

Below my repository Url. Those are plain react app with babel.

Repository Url : https://github.com/andiappan-ar/simple-babel-issue.git

i have installed my feature app in project using below 

>npm install --save-dev ../feature

Now i try to import "feature/src/Article.js" component from feature to my project-safar-zoo.

Run my project-safarizoo u will find out the error.

>\packages\project-safarizoo>npm start

This throw error.

![capture](https://user-images.githubusercontent.com/11770345/54026405-b1449200-41c3-11e9-86f0-36ce162027b4.PNG)

**Comment by danez** [comment]
You are mixing babel v6 `babel-*` and babel v7 `@babel/*`. Please only use one version as the are incompatible to each other.

**Comment by andiappan-ar** [comment]
Changed everything to babel 7 still issue open. @danez.

**Comment by nicolo-ribaudo** [comment]
Your webpack config isn't being picked up by webpack: it should throw, since you are using `path` and `resolve` which aren't defined.

**Comment by nicolo-ribaudo** [comment]
Also, did you run `npm run eject`? You need to do so before customizing your Babel/webpack config with create-react-app.
