### ISSUE TITLE
@babel/preset-env useBuiltIns: 'usage' - detect module type

### ISSUE THREAD

**Issue by KidkArolis** [babel/babel#9654]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I use @babel/preset-env in a tool (https://github.com/KidkArolis/jetpack/) that doesn't know if you're using esm modules, cjs or some mixture. Recently, due to some change in either webpack or @babel/preset-env, I started running into an issue where builtins are being injected into the files using ESM import syntax, this breaks if the file is using CJS, because webpack can't combine the two.

**Describe the solution you'd like**
I would like useBuiltIns to inject the imports in the module style that is already being used by each individual module when `modules: false` is used in @babel/preset-env.

**Teachability, Documentation, Adoption, Migration Strategy**
This should (?) be transparent to most users and simply work better overall (?).

**Comment by nicolo-ribaudo** [comment]
If a file is parsed as a module, Babel will inject `import`. You can use the `sourceType` option to specify which kind of file it is: https://babeljs.io/docs/en/options#sourcetype (you might be interested in using "unambiguous")

**Comment by KidkArolis** [comment]
I think that is pretty much exactly what I needed. Will give it a spin, added this to jetpack in https://github.com/KidkArolis/jetpack/commit/2182810aa76b191044c2fcd96847067af4046aaa. Thanks!
