### ISSUE TITLE
npm ERR! 500 Internal Server Error: @babel/plugin-transform-named-capturing-groups-regex

### ISSUE THREAD

**Issue by MaplesFS-DNS** [babel/babel#9655]
## Bug Report
npm ERR! 500 Internal Server Error: @babel/plugin-transform-named-capturing-groups-regex@^7.3.0

**Current Behavior**
Unable to load reactjs webapp dependencies due to this package failing with a 500 ERR.

**Input Code**
As simple as running _npm install_ won't work due to this fail.

**Expected behavior/code**
Not to fail and allow to load packages as needed according to app needs.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "name": "ReactJs.WebApp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.3.1",
    "jquery": "3.3.1",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.8",
    "reactstrap": "^7.1.0",
    "rimraf": "^2.6.3"
  },
  "devDependencies": {
    "ajv": "^6.10.0",
    "babel-eslint": "^10.0.1",
    "cross-env": "^5.2.0",
    "eslint": "^5.15.1",
    "eslint-config-react-app": "^3.0.8",
    "eslint-plugin-flowtype": "^3.4.2",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "scripts": {
    "start": "rimraf ./build && react-scripts start",
    "build": "react-scripts build",
    "test": "cross-env CI=true react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint": "eslint ./src/"
  }
}
```

**Environment**
- Babel version(s): @babel/plugin-transform-named-capturing-groups-regex@^7.3.0
- Node/npm version: Node 8.11.1/npm 6.4.1
- OS: [Windows 10]
- How you are using Babel: reactjs depends upon it (sidenav)

**Comment by nicolo-ribaudo** [comment]
This is a problem with npm, not with Babel.
