### ISSUE TITLE
cannot find babel plugins installed globally (locally works great!)

### ISSUE THREAD

**Issue by vans163** [babel/babel#9656]
If you globally install requirements for a simple JSX app it does not find.

```
yarn global add @babel/cli @babel/core @babel/plugin-transform-react-jsx
babel --plugins @babel/plugin-transform-react-jsx index.js

Error: Cannot find module '@babel/plugin-transform-react-jsx' from '/root/app'
```

But installing the dependencies locally
```
yarn add @babel/cli @babel/core @babel/plugin-transform-react-jsx --dev
./node_modules/.bin/babel --plugins @babel/plugin-transform-react-jsx index.js

WORKS
```

**Comment by danez** [comment]
We do not support mixing of local and global dependencies.

**Comment by vans163** [comment]
Im sorry but I do not quite understand, there is no mixing? All the dependencies are global in my case. 

I am not mixing.

**Comment by loganfsmyth** [comment]
You can always resolve the plugin/preset to an absolute path yourself before passing it to Babel, but as-is Babel assumes that plugin-name-resolution is relative to the file referencing the plugin/preset.
