### ISSUE TITLE
Have an error when restarting node

### ISSUE THREAD

**Issue by lisandrolan** [babel/babel#9657]
## Bug Report

**Current Behavior**
When I restart node server I have the following error. 
  return SafeBuffer.Buffer.from(json, 'utf8').toString('base64');
                           ^

TypeError: Cannot read property 'from' of undefined
    at Converter.toBase64 (C:\Users\Documents\ReactProjects\node_modules\convert-source-map\index.js:61:28)
    at Converter.toComment (C:\Users\Documents\ReactProjects\\node_modules\convert-source-map\index.js:65:21)
    at generateCode (C:\Users\\Documents\ReactProjects\node_modules\@babel\core\lib\transformation\file\generate.js:78:76)
    at runSync (C:\Users\468855\Documents\ReactProjects\node_modules\@babel\core\lib\transformation\index.js:50:51)
    at transformSync (C:\Users\\Documents\ReactProjects\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (C:\Users\\Documents\ReactProjects\node_modules\@babel\core\lib\transform.js:22:38)
    at compile (C:\Users\\Documents\ReactProjects\node_modules\@babel\register\lib\node.js:73:20)
    at compileHook (C:\Users\\Documents\ReactProjects\node_modules\@babel\register\lib\node.js:102:12)
    at Module._compile (C:\Users\\Documents\ReactProjects\node_modules\pirates\lib\index.js:77:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{

  "version": "0.1.0",
  "private": true,

  "dependencies": {
    "@aws-amplify/api": "^1.0.11",
    "@aws-amplify/auth": "^1.2.7",
    "@aws-amplify/core": "^1.0.16",
    "@aws-amplify/storage": "^1.0.16",
    "aws-api-gateway-client": "^0.2.12",
    "body-parser": "^1.18.2",
    "canvg": "^1.5.2",
    "compression": "^1.7.2",
    "connected-react-router": "^5.0.1",
    "draft-js": "^0.10.5",
    "draftjs-to-html": "^0.8.4",
    "express": "^4.16.2",
    "history": "^4.6.3",
    "html-to-draftjs": "^1.4.0",
    "ignore-styles": "^5.0.1",
    "immutable": "^3.8.2",
    "jspdf": "^1.4.1",
    "morgan": "^1.9.0",
    "nuka-carousel": "^4.4.7",
    "prop-types": "^15.6.0",
    "qrcode.react": "^0.8.0",
    "react": "^16.7.0",
    "react-adsense": "^0.0.6",
    "react-avatar": "^3.4.6",
    "react-dom": "^16.7.0",
    "react-draft-wysiwyg": "^1.12.19",
    "react-ga": "^2.5.3",
    "react-google-publisher-tag": "^1.0.5",
    "react-icons": "^2.2.5",
    "react-measure": "^2.0.0",
    "react-recaptcha": "^2.3.10",
    "react-redux": "^5.0.5",
    "react-router": "4.3.1",
    "react-router-dom": "^4.1.2",
    "react-scripts": "^2.1.1",
    "react-select": "2.1.2",
    "react-share": "^2.0.0",
    "react-virtualized": "^9.12.0",
    "react-waypoint": "^9.0.1",
    "redux": "4.0.1",
    "redux-thunk": "^2.2.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.85.0",
    "slick-carousel": "^1.8.1",
    "symbol-observable": "^1.2.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.3.4",
    "@babel/node": "^7.2.2",
    "@babel/polyfill": "^7.2.5",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "canvas-prebuilt": "^2.0.0-alpha.14",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "enzyme-to-json": "^3.3.4",
    "eslint-config-react-app": "^3.0.5",
    "jest": "^23.6.0",
    "json-loader": "^0.5.4",
    "react-router-sitemap": "^1.1.5",
    "react-test-renderer": "^16.4.1",
    "redux-mock-store": "^1.5.3",
    "regenerator-runtime": "^0.13.1",
    "rollup-plugin-commonjs": "^9.1.2",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-uglify": "^3.0.0",
    "uglify-js-brunch": "^2.10.0",
    "why-did-you-update": "^0.1.1"
  },
  "scripts": {
    "start": "node app",
    "dummy": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "coverage": "react-scripts test --env=jsdom coverage",
    "eject": "react-scripts eject",
    "serve": "set NODE_ENV=production&& npm run build && node app.js",
    "deploy": "git add . && eb deploy --stage --timeout 30",
    "analyze": "npm run build && source-map-explorer build/static/js/main.* ",
    "prestart": "react-scripts build"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "jest": {
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
}

```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lisandrolan** [comment]
any update?

**Comment by nicolo-ribaudo** [comment]
It's hard to say what the problem is. Could you share a small repo which reproduces the issue?

**Comment by abhisharkjangir** [comment]
Is there any fix? Getting the Same issue.
![Screenshot_11](https://user-images.githubusercontent.com/21080263/54474089-6ac7e680-4806-11e9-988f-93e6b7638108.png)

**Comment by lisandrolan** [comment]
it should work with the following sentence

require("@babel/register")({
  // babelrc: false,
  presets: ['@babel/env', '@babel/react'],
  only: [__dirname + "/../../"],
  ignore: [__dirname + "/../../**/node_modules"],
});
