### ISSUE TITLE
npm documentation correct?

### ISSUE THREAD

**Issue by jehillert** [babel/babel#9659]
## Bug Report

**Current Behavior**
Is the documentation on the npm website (e.g., 1st link below) still correct?  The "Usage" section states: 

> Via .babelrc (Recommended)
> .babelrc
> 
> {
>   "plugins": ["transform-react-jsx-source"]
> }
> Via CLI
> babel --plugins transform-react-jsx-source script.js
> Via Node API
> require("babel-core").transform("code", {
>   plugins: ["transform-react-jsx-source"]
> });

whereas the documentation on your website (2nd link), states: 

> Via .babelrc (Recommended)
> .babelrc
> 
> {
>   "plugins": ["@babel/plugin-transform-react-jsx-source"]
> }
> 
> Copy
> Via CLI
> babel --plugins @babel/plugin-transform-react-jsx-source script.js
> 
> Copy
> Via Node API
> require("@babel/core").transform("code", {
>   plugins: ["@babel/plugin-transform-react-jsx-source"]
> });

npm link: https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source
bablejs.io: https://babeljs.io/docs/en/next/babel-plugin-transform-react-jsx-source.html#via-babelrc-recommended

**Input Code**
**Expected behavior/code**
**Babel Configuration (.babelrc, package.json, cli command)**
**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**
**Additional context/Screenshots**

**Comment by nicolo-ribaudo** [comment]
The npm link is for a v6 package, while on the website you are reading the v7 docs.
