### ISSUE TITLE
@babel/plugin-transform-typescript not supporting fake "this" parameters on getter functions

### ISSUE THREAD

**Issue by christianalfoni** [babel/babel#9660]
## Bug Report

**Current Behavior**
The **@babel/plugin-transform-typescript** does not transform the fake "this" parameter for typing the context of a getter function. [this parameter in TS docs](https://www.typescriptlang.org/docs/handbook/functions.html)

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MDeAoGMDmBTWAWwE8BxAqPAJwAooALASwgC4ZorGwcBKdLGAIC-GIUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.3.4

```ts
const obj = {
 get myGetter(this: SomeType) {

  }
}
```

**Expected behavior/code**
I would expect it to completely remove the argument, as it is Typescript code.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: ['@babel/preset-env'],
  plugins: ['@babel/plugin-transform-typescript'],
}
```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: v10.15.1 / 6.7.0
- OS: MacOS Mojave 10.14.13
- Monorepo: no
- How you are using Babel: `loader`

**Additional context/Screenshots**
<img width="1052" alt="Screenshot 2019-03-11 at 15 07 49" src="https://user-images.githubusercontent.com/3956929/54129844-75057180-440f-11e9-9217-7579f9e6930e.png">

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9641
