### ISSUE TITLE
Throw an error when I use `babel-traverse` to dispose some dependences.

### ISSUE THREAD

**Issue by DingRui12138** [babel/babel#9663]
## Bug Report

**babel-core\lib\transformation\file\index.js:558 throw err;**
I'm coding a `minipack` for my project.
throw an error when I use traverse to dispose some dependences.
what's going on?
any idea. tks :)

![image](https://user-images.githubusercontent.com/24449677/54174399-34663080-44c1-11e9-97ff-5861d9d94bb5.png)

babel-core\lib\transformation\file\index.js:558
TypeError: unknown: Cannot read property 'file' of undefined

**This is my code**
```js
const { transformFromAst } = require('babel-core')
const babylon = require('babylon')
const traverse = require('babel-traverse').default

const translateFile2Ast = (filename) => {
  // const content = fs.readFileSync(filename, 'utf-8')

  const content = 'const a = [1,2,3];\nconsole.log([...a])'
  return babylon.parse(content, {
    sourceType: 'module'
  })
}


const translateAst2Code = (ast, code) => {
  return transformFromAst(ast, code, {
    presets: ['env', 'stage-2'],
  })
}
const ast = translateFile2Ast('test/index.js')
traverse(ast, {}) // if I don't use this line code,everything is ok,I don't know why
const code = translateAst2Code(ast, 'const a = [1,2,3];\nconsole.log([...a])')
```

**Expected behavior/code**

**Babel Configuration (.babelrc, package.json, cli command)**

**Environment**
- Babel version(s): [6.26.0 (babel-core 6.26.3)]
- Node/npm version: [Node 8/npm 6]
- OS: [Windows 7]
- How you are using Babel: [node]

**Comment by nicolo-ribaudo** [comment]
Babel 6 isn't maintained anymore. Do you get the same error when using Babel 7?

**Comment by DingRui12138** [comment]
It works fine when I use Babel 7
