### ISSUE TITLE
the transform of let in the for loop have problem 

### ISSUE THREAD

**Issue by Gjb7598189** [babel/babel#9664]
// transform before: 
```
for (let i = 0; i < 3; i++) {
  let i = 'abc';
  console.log(i); // three time 'abc'
}
```
// transform after:
```
for (var i = 0; i < 3; i++) {
  var i = 'abc';
  console.log(i); // one time 'abc'
}
```

but, Their behavior is different

**Comment by nicolo-ribaudo** [comment]
Didn't GitHub show you an issue template to provide all the required info?

**Comment by nicolo-ribaudo** [comment]
This is working in Babel 7.4.2: https://babeljs.io/repl/build/master#?babili=false&browsers=%3E%201%25%2C%20last%202%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=GYewTgBAFANgpgFwgSwgXggBgNwogHggGZdkBqMgSggG8AoCCeJVDAcgEMAjAYzewYQeIAHYBnEPAB0MEAHMoySrgD0KiAgAWYOHA3IAtns682dAL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.4.2
