### ISSUE TITLE
How dose it could support lower than node version 5.1?

### ISSUE THREAD

**Issue by TongDaDa** [babel/babel#9665]
## Feature Request

Using the old version node's version to run the `babel-register` to compile codes.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Because of some reason, I have to use the 5.1 version of nodeJs on my Windows XP system, and also there have another reason made me compile these using es6+ syntax code transform to executable codes on my computer that only has a 5.1 node version.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

My node's version is 5.1, but the `babel-register` and `babel-core` was failed that run on this version.
 
I was thinking of that is absurd, babel existing for next-generation javascript, but it actually uses the `next-generation` syntax to transform javascript.

Why do you don't consider that?

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by nicolo-ribaudo** [comment]
Babel Is meant to generate code compatible with old environments. If you need to support environments older than node 6, you should compile your code using `@babel/cli` in a compatible environment, and then run the compiled files on node 5.
