### ISSUE TITLE
Babel is not providing polyfill for URLSearchParams

### ISSUE THREAD

**Issue by danreg** [babel/babel#9667]
In my code I have some places where I use URLSearchParams. But it seems that Babel is not polyfilling UrlSearchParams for IE11. So I still need to that manually.
I thought I don't need to worry on polyfilling with babel any more?

Do I understand something wrong with Babel or is it a missing feature?

**Comment by zloirock** [comment]
It's added in `core-js@3` and will be added to `babel` after #7646, most likely in the next minor release.
