### ISSUE TITLE
Please release new version of @babel/register

### ISSUE THREAD

**Issue by simlu** [babel/babel#9676]
There is currently a [bug in yarn](https://github.com/yarnpkg/yarn/issues/7105). Unfortunately that means we can't use `@babel/register` in combination with [nyc](https://www.npmjs.com/package/nyc).

The offending package is [find-cache-dir](https://www.npmjs.com/package/find-cache-dir). The latest release of `@babel/register` sets it to `^1.0.0`, but nyc sets it to `^2.0.0`.

While this is not a bug in babel, a release would solve our issues quickly until it gets fixed in yarn.

**Comment by nicolo-ribaudo** [comment]
We plan to release it on friday or monday.

**Comment by simlu** [comment]
Sweet! Thank you for the quick reply.

**Comment by simlu** [comment]
Cheers!

**Comment by nicolo-ribaudo** [comment]
(It's not released yet)
