### ISSUE TITLE
["@babel/preset-env", {modules: false} ]  crash

### ISSUE THREAD

**Issue by DFOXpro** [babel/babel#9679]
## Bug Report

**Current Behavior**
Module: false pop a deprecated error and brake the process

**Input Code**

```js
"presets": ["@babel/preset-env", {"modules": false} ] 
```

**Expected behavior/code**
Leave untouch the this in the global scope

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env", {"modules": false} ] 
}
```
**Error**

```
Using removed Babel 5 option: .modules - Use the corresponding module transform plugin in the plugins` option. Check out babeljs.io/docs/plugins/#modules
```

**Environment**
- Babel version(s): v7.3.4
- Node/npm version: Node 10 npm 6
- OS: Ubuntu 18.04.2
- Monorepo: no
- How you are using Babel: CLI and grunt

**Possible Solution**

**Additional context/Screenshots**
I just need babel to dont brake the this in the global scope

**Comment by nicolo-ribaudo** [comment]
You need some more brackets:
```js
{
  "presets": [
    ["@babel/preset-env", {"modules": false} ]
  ] 
}
```

Otherwise those two entries are considered as two different plugins.

**Comment by DFOXpro** [comment]
Wow thank you, it's indeed the solution to my problem.
you can close this issue then
