### ISSUE TITLE
REPL output confusing from `JSON.stringify(..)` transformation

### ISSUE THREAD

**Issue by getify** [babel/babel#968]
This code doesn't appear to output correctly in babel's REPL:

```js
var s = Symbol("foo");

var x = {
  [s]: 42
};

console.log( Object.getOwnPropertySymbols(x) );
// [ null ]
```

Apparently it's because the output is using `JSON.stringify(..)`, which of course cannot represent symbols.

Can we get an option (another lovely checkbox) to have `console.log(..)` output shown in the REPL raw without this transformation?

**Comment by zloirock** [comment]
Let me guess, you see this result in REPL? :) For show console results, it's uses `JSON.stringify` and convert symbols to `null`. All issues about polyfill, please, add in [core-js repo](https://github.com/zloirock/core-js/).

**Comment by getify** [comment]
Oh! I guess I didn't realize that the output in the page was being transformed with `JSON.stringify(..)`. Interesting gotcha. Can we have an option in the REPL page to just dump raw output with such transformation?

**Comment by sebmck** [comment]
Yup, the REPL serialisation needs to be improved. It's working as expected,
the return output is just serialised poorly.

On Saturday, 7 March 2015, Denis Pushkarev <notifications@github.com> wrote:

> Let me guess, you see this result in REPL? :) For show console results,
> it's uses JSON.stringify and convert symbols to null. All issues about
> polyfill, please, add in core-js repo
> <https://github.com/zloirock/core-js/>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/968#issuecomment-77687673>.
>


-- 
Sebastian McKenzie

**Comment by getify** [comment]
OK, updated this bug to be about the REPL output concern. Thanks for clarifications!

**Comment by sebmck** [comment]
Moving to babel/babel.github.io#172.
