### ISSUE TITLE
@babel/typescript removed types which prevents decorator metadata from being emitted

### ISSUE THREAD

**Issue by elderapo** [babel/babel#9681]
## Bug Report

**Current Behavior**
It logs `couldn't get the type :(`.

**Input Code**
- [Reproducible demo](https://github.com/elderapo/babel-typescript-reflect-metadata-bug)

```ts
import "reflect-metadata";

const logType = (target: any, key: string): void => {
  const type = Reflect.getMetadata("design:type", target, key);
  if (!type) {
    console.log("couldn't get the type :(");
    return;
  }
  console.log(`${key} type: ${type.name}`);
};

class Demo {
  @logType
  public someProperty: number = 0;
}

new Demo();
```

**Expected behavior/code**
It should log `someProperty type: Number`.

**Babel Configuration (.babelrc)**

```js
{
  "presets": ["@babel/env", "@babel/typescript"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: doesn't matter
- OS: doesn't matter
- Monorepo: no
- How you are using Babel: babel-node/cli

**Possible Solution**
There is a package [babel-decorators-metadata](https://github.com/dragomirtitian/babel-decorators-metadata) which tries to solve this issue but at the same time breaks some stuff. There is also a [question on stackoverflow](https://stackoverflow.com/questions/53015862/metadata-retention-with-typescript-babel-7-decorators) regarding this issue.

**Additional context/Screenshots**
`@babel/typescript` removes TypeScript type definitions before compilation process which causes packages such as `reflect-metadata` to not work correctly.

**Comment by nicolo-ribaudo** [comment]
Why do you expect the type annotation to be stored as a metadata? No one of typescript, decorators or class fields does that.

**Comment by elderapo** [comment]
Because there is an `emitDecoratorMetadata` set to `true` in the `tsconfig.json`. For comparison, the same code running with `ts-node` correctly emits decorators metadata:

```bash
elderapo@ziemniak:/tmp/babel-typescript-reflect-metadata-bug$ yarn start-ts-node
yarn run v1.13.0
$ ts-node ./src/index.ts
someProperty type: Number
Done in 0.82s.
```

**Comment by nicolo-ribaudo** [comment]
> Because there is an `emitDecoratorMetadata` set to `true` in the `tsconfig.json`

Oh ok. Babel doesn't load the `tsconfig.json` file, but it transforms TS as if you were transforming it only with the `isolatedModules: true` option.

I suggest that you use something like this to define those metadata:

```js
import "reflect-metadata";

const logType = (target: any, key: string): void => {
  const type = Reflect.getMetadata("design:type", target, key);
  if (!type) {
    console.log("couldn't get the type :(");
    return;
  }
  console.log(`${key} type: ${type.name}`);
};

class Demo {
  @logType
  @Reflect.metadata("design:type", Number)
  public someProperty: number = 0;
}

new Demo();
```

**Comment by leonardfactory** [comment]
Hi, I developed a plugin in order to emit decorators metadata, similar to TSC compiler, even if using babel with `@babel/preset-typescript`: [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata#readme)
