### ISSUE TITLE
Inherit static properties in IE

### ISSUE THREAD

**Issue by jhollingworth** [babel/babel#969]
It seems inheriting static properties in IE doesn't work. The below test passes in Chrome but fails in IE. Judging by [this conversation](https://esdiscuss.org/topic/static-method-inheritance) it should be part of the ES6 spec so I'm guessing this is a bug?

```js
var expect = require('chai').expect;

describe('inherit static properties', function () {
  var child;
  var expectedResult = {
    bar: 'baz'
  };

  class Parent {
    static get foo() {
      return expectedResult;
    }
  }

  class Child extends Parent {
  }

  it('should inherit static properties', function () {
    expect(Child.foo).to.eql(expectedResult);
  });
});
```

This was tested using
* Babel 4.7.1
* Babelify 5.0.4
* Browserify 5.13.1

**Comment by zloirock** [comment]
IE10-?

**Comment by jhollingworth** [comment]
Ah, sorry didn't see that. Thanks!
