### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by illectronic** [babel/babel#9690]
package.json
```json
{
  "name": "bayesimpact-react",
  "main": "server.js",
  "version": "0.0.1",
  "scripts": {
    "clean": "rimraf dist/*",
    "dist": "npm run clean && REACT_WEBPACK_ENV=dist webpack --bail",
    "start": "node server.js",
    "dev": "webpack-dev-server --hot --inline"
  },
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-react-constant-elements": "^7.2.0",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/polyfill": "7.2.5",
    "@hot-loader/react-dom": "16.8.3",
    "airtable": "0.5.9",
    "algoliasearch": "3.32.0",
    "amplitude-js": "4.6.0",
    "autocomplete.js": "0.35.0",
    "babel-cli": "6.26.0",
    "babel-core": "6.26.3",
    "babel-eslint": "10.0.1",
    "babel-plugin-transform-react-pure-class-to-function": "^1.0.1",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-app": "7.0.2",
    "browser-metrics": "0.1.4",
    "chai": "4.2.0",
    "connected-react-router": "6.3.1",
    "copyfiles": "2.1.0",
    "css-loader": "2.1.1",
    "detect-browser": "4.1.0",
    "emoji-regex": "8.0.0",
    "es6-promise": "4.2.6",
    "es6-set-proptypes": "1.0.0",
    "eslint": "^4.19.1",
    "eslint-import-resolver-webpack": "0.11.0",
    "eslint-loader": "2.1.2",
    "eslint-plugin-import": "2.16.0",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.12.4",
    "eslint-plugin-unicorn": "7.1.0",
    "eslint-plugin-you-dont-need-lodash-underscore": "6.4.0",
    "expo": "^27.1.0",
    "exports-loader": "0.7.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "3.0.1",
    "firebase": "5.8.6",
    "firebase-tools": "6.5.0",
    "glob": "7.1.3",
    "google-protobuf": "3.7.0",
    "html-webpack-plugin": "3.2.0",
    "imagemin": "6.1.0",
    "imagemin-mozjpeg": "8.0.0",
    "imagemin-optipng": "6.0.0",
    "imagemin-svgo": "7.0.0",
    "img-loader": "3.0.1",
    "imports-loader": "0.8.0",
    "isparta-loader": "2.0.0",
    "js-cookie": "2.2.0",
    "json-loader": "0.5.7",
    "jsonlint": "1.6.3",
    "jspdf": "1.5.3",
    "karma": "4.0.1",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.2",
    "karma-mocha": "1.3.0",
    "karma-mocha-reporter": "2.2.5",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "3.0.5",
    "local-storage-fallback": "4.1.1",
    "lodash": "4.17.11",
    "mdi-react": "5.2.0",
    "minimist": "1.2.0",
    "mocha": "6.0.2",
    "mocha-junit-reporter": "1.18.0",
    "moment": "2.24.0",
    "node-sass": "4.11.0",
    "normalize.css": "8.0.1",
    "null-loader": "0.1.1",
    "open": "0.0.5",
    "package-json-validator": "0.6.3",
    "prop-types": "15.7.2",
    "puppeteer": "1.13.0",
    "query-string": "6.3.0",
    "radium": "0.25.1",
    "randexp": "0.5.3",
    "raw-loader": "1.0.0",
    "react": "16.3.1",
    "react-addons-test-utils": "15.6.2",
    "react-custom-scrollbars": "4.2.1",
    "react-dom": "16.8.4",
    "react-facebook-login": "4.1.1",
    "react-google-login": "5.0.2",
    "react-height": "3.0.0",
    "react-hot-loader": "4.7.2",
    "react-lazyload": "2.5.0",
    "react-loadable": "5.5.0",
    "react-markdown": "4.0.6",
    "react-native": "^0.55.4",
    "react-redux": "^5.0.7",
    "react-router": "4.2.0",
    "react-router-dom": "4.3.1",
    "react-select": "2.4.2",
    "react-share": "2.4.0",
    "react-swipeable": "5.0.1",
    "react-test-renderer": "16.8.4",
    "react-twitter-embed": "2.0.4",
    "react-visibility-sensor": "5.0.2",
    "redux": "^4.0.0",
    "redux-devtools-extension": "2.13.8",
    "redux-mock-store": "1.5.3",
    "redux-raven-middleware": "1.2.0",
    "redux-thunk": "2.3.0",
    "rename-output-webpack-plugin": "1.0.1",
    "responsive-loader": "1.2.0",
    "rimraf": "2.6.3",
    "rn-redux-mixpanel": "1.3.0",
    "sass-loader": "7.1.0",
    "sha1": "1.1.1",
    "smoothscroll-polyfill": "0.4.3",
    "style-loader": "0.23.1",
    "svg-transform-loader": "2.0.7",
    "unused-files-webpack-plugin": "3.4.0",
    "url-loader": "1.1.2",
    "webpack": "4.29.6",
    "webpack-cli": "3.2.3",
    "webpack-dev-server": "3.2.1",
    "webpack-hot-middleware": "2.2.0",
    "webpack-pwa-manifest": "4.0.0",
    "whatwg-fetch": "3.0.0",
    "yarn-lazy-lock": "0.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5"
  }
}
```

```
ERROR in ./src/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /usr/app/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/usr/app/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/usr/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/usr/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/usr/app/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/usr/app/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/usr/app/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/usr/app/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/usr/app/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /usr/app/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/usr/app/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/usr/app/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/usr/app/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/usr/app/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/app/node_modules/babel-loader/lib/index.js:3:103)


.babelrc in root dir

  "plugins": [
    "@babel/transform-react-constant-elements",
    "@babel/transform-react-inline-elements",
    "transform-react-remove-prop-types",
    "transform-react-pure-class-to-function",
 "@babel/transform-runtime",
    ["babel-plugin-root-import", {
      "rootPathSuffix": "."
    }]
```

index.jsx file

```js
import React from 'react';
import ReactDom from 'react-dom';
import { Router, browserHistory } from 'react-router';
import routes from './routes';
require('./stylesheets/base.scss');
require('./stylesheets/home.scss');
require('./stylesheets/contact.scss');
ReactDom.render(
  <Router history={browserHistory} routes={routes} />,
  document.querySelector('#app')
);
```

**Comment by existentialism** [comment]
@illectronic it looks like you're mixing v6 and v7 dependencies, you'll want to update them all to the same (babel-core -> @babel/core, etc)

**Comment by illectronic** [comment]
> @illectronic it looks like you're mixing v6 and v7 dependencies, you'll want to update them all to the same (babel-core -> @babel/core, etc)

Here is my modified package.json with the same issue:


{
  "name": "bayesimpact-react",
  "main": "server.js",
  "version": "0.0.1",
  "scripts": {
    "clean": "rimraf dist/*",
    "dist": "npm run clean && REACT_WEBPACK_ENV=dist webpack --bail",
    "start": "node server.js",
    "dev": "webpack-dev-server --hot --inline"
  },
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-react-constant-elements": "^7.2.0",
    "@babel/plugin-transform-react-inline-elements": "^7.2.0",
    "@babel/polyfill": "7.2.5",
    "@hot-loader/react-dom": "16.8.3",
    "airtable": "0.5.9",
    "algoliasearch": "3.32.0",
    "amplitude-js": "4.6.0",
    "autocomplete.js": "0.35.0",
    "@babel/cli": "^7.0.0-rc.1",
    "@babel/core": "^7.0.0-rc.1",
    "@babel/node": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1",
    "babel-eslint": "10.0.1",
    "babel-plugin-transform-react-pure-class-to-function": "^1.0.1",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-app": "7.0.2",
    "browser-metrics": "0.1.4",
    "chai": "4.2.0",
    "connected-react-router": "6.3.1",
    "copyfiles": "2.1.0",
    "css-loader": "2.1.1",
    "detect-browser": "4.1.0",
    "emoji-regex": "8.0.0",
    "es6-promise": "4.2.6",
    "es6-set-proptypes": "1.0.0",
    "eslint": "^4.19.1",
    "eslint-import-resolver-webpack": "0.11.0",
    "eslint-loader": "2.1.2",
    "eslint-plugin-import": "2.16.0",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.12.4",
    "eslint-plugin-unicorn": "7.1.0",
    "eslint-plugin-you-dont-need-lodash-underscore": "6.4.0",
    "expo": "^27.1.0",
    "exports-loader": "0.7.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "3.0.1",
    "firebase": "5.8.6",
    "firebase-tools": "6.5.0",
    "glob": "7.1.3",
    "google-protobuf": "3.7.0",
    "html-webpack-plugin": "3.2.0",
    "imagemin": "6.1.0",
    "imagemin-mozjpeg": "8.0.0",
    "imagemin-optipng": "6.0.0",
    "imagemin-svgo": "7.0.0",
    "img-loader": "3.0.1",
    "imports-loader": "0.8.0",
    "isparta-loader": "2.0.0",
    "js-cookie": "2.2.0",
    "json-loader": "0.5.7",
    "jsonlint": "1.6.3",
    "jspdf": "1.5.3",
    "karma": "4.0.1",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.2",
    "karma-mocha": "1.3.0",
    "karma-mocha-reporter": "2.2.5",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "3.0.5",
    "local-storage-fallback": "4.1.1",
    "lodash": "4.17.11",
    "mdi-react": "5.2.0",
    "minimist": "1.2.0",
    "mocha": "6.0.2",
    "mocha-junit-reporter": "1.18.0",
    "moment": "2.24.0",
    "node-sass": "4.11.0",
    "normalize.css": "8.0.1",
    "null-loader": "0.1.1",
    "open": "0.0.5",
    "package-json-validator": "0.6.3",
    "prop-types": "15.7.2",
    "puppeteer": "1.13.0",
    "query-string": "6.3.0",
    "radium": "0.25.1",
    "randexp": "0.5.3",
    "raw-loader": "1.0.0",
    "react": "16.3.1",
    "react-addons-test-utils": "15.6.2",
    "react-custom-scrollbars": "4.2.1",
    "react-dom": "16.8.4",
    "react-facebook-login": "4.1.1",
    "react-google-login": "5.0.2",
    "react-height": "3.0.0",
    "react-hot-loader": "4.7.2",
    "react-lazyload": "2.5.0",
    "react-loadable": "5.5.0",
    "react-markdown": "4.0.6",
    "react-native": "^0.55.4",
    "react-redux": "^5.0.7",
    "react-router": "4.2.0",
    "react-router-dom": "4.3.1",
    "react-select": "2.4.2",
    "react-share": "2.4.0",
    "react-swipeable": "5.0.1",
    "react-test-renderer": "16.8.4",
    "react-twitter-embed": "2.0.4",
    "react-visibility-sensor": "5.0.2",
    "redux": "^4.0.0",
    "redux-devtools-extension": "2.13.8",
    "redux-mock-store": "1.5.3",
    "redux-raven-middleware": "1.2.0",
    "redux-thunk": "2.3.0",
    "rename-output-webpack-plugin": "1.0.1",
    "responsive-loader": "1.2.0",
    "rimraf": "2.6.3",
    "rn-redux-mixpanel": "1.3.0",
    "sass-loader": "7.1.0",
    "sha1": "1.1.1",
    "smoothscroll-polyfill": "0.4.3",
    "style-loader": "0.23.1",
    "svg-transform-loader": "2.0.7",
    "unused-files-webpack-plugin": "3.4.0",
    "url-loader": "1.1.2",
    "webpack": "4.29.6",
    "webpack-cli": "3.2.3",
    "webpack-dev-server": "3.2.1",
    "webpack-hot-middleware": "2.2.0",
    "webpack-pwa-manifest": "4.0.0",
    "whatwg-fetch": "3.0.0",
    "yarn-lazy-lock": "0.1.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0-rc.1",
    "@babel/core": "^7.0.0-rc.1",
    "@babel/node": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1",
    "babel-eslint": "10.0.1",
    "babel-plugin-transform-react-pure-class-to-function": "^1.0.1",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-app": "7.0.2"
  }
}

**Comment by existentialism** [comment]
You still have some v6 deps:

```
"babel-preset-es2015": "6.24.1",
"babel-preset-react": "6.24.1",
```

**Comment by illectronic** [comment]
> You still have some v6 deps:
> 
> ```
> "babel-preset-es2015": "6.24.1",
> "babel-preset-react": "6.24.1",
> ```

Can you recommend a package.json with all babel 6 please? I am trying to do that now.

**Comment by existentialism** [comment]
@illectronic 

`babel-preset-es2015` -> remove? it's deprecated, and you're using `@babel/preset-env` anyway

`babel-preset-react` -> `@babel/preset-react`

**Comment by illectronic** [comment]
or babel7 now I am getting an error that it's using the wrong version and 6 is specified nowhere.

**Comment by nicolo-ribaudo** [comment]
You can run `npx nls why babel-core` to understand why it is using Babel 6.

PS. Please wrap the code you post in issues with ``` both before and after the block of code.

**Comment by nicolo-ribaudo** [comment]
@illectronic Did you solve the problem?

**Comment by illectronic** [comment]
You can just close this. I aborted the project for now.
