### ISSUE TITLE
Wrong behavior of for of loop

### ISSUE THREAD

**Issue by rabbitooops** [babel/babel#9696]
## Bug Report

**Current Behavior**
Uncaught TypeError: Cannot read property 'length' of null

User code:
```js
var arr = [1,2,3]

for (let v of arr) {
  console.log(v)
  arr = null
}
```
Babel compiled:
```js
"use strict";

var arr = [1, 2, 3];

for (var _i = 0; _i < arr.length; _i++) {
  var v = arr[_i];
  console.log(v);
  arr = null;
}
```

**Expected behavior/code**
1
2
3

**Babel Configuration (.babelrc, package.json, cli command)**
In **try it out** webpage:https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBOkLwQ2gRgDQCZkGYC6AoHAzAe0gAoAbAUwBcJgJD8owwBKCAbxwggGNCA7AM6FKAOjKEA5iWAsuTWBH4BXMmRwBfHEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.3.4

**Environment**
Copy codes to devtool>console.

**Possible Solution**

Compile to:
```js
"use strict";

var arr = [1, 2, 3];

var _arr = arr
for (var _i = 0; _i < _arr.length; _i++) {
  var v = _arr[_i];
  console.log(v);
  arr = null;
}
```

**Comment by danez** [comment]
Thank you for reporting this, this is indeed wrong.

**Comment by rabbitooops** [comment]
You are welcome! :)
