### ISSUE TITLE
TS type in js code

### ISSUE THREAD

**Issue by rreznichenko** [babel/babel#9702]
Hello! is it normal that in plain javaScript I've foun Any type from TS. Sorry for disturbing you. 
https://github.com/babel/babel/blob/f36a6987e489e62240ca571df55557b80ddfe594/packages/babel-helper-plugin-utils/src/index.js#L93

**Comment by loganfsmyth** [comment]
Babel does not use TS at the moment, we use https://flow.org/, which does not have a different extension.
