### ISSUE TITLE
Do and Block Params expressions [Parser]

### ISSUE THREAD

**Issue by CreatorVilius** [babel/babel#9703]
## Feature Request

**Describe the solution you'd like**
I suggest making `do` and block param expressions. `do` expression:
```js
do {
    // code
}
```
And block params:
```js
something {
    // code
}
something(someValue) {
    // code
}
something(someValue) // one line of code
something // one line of code
a.b['c']('d')('e') {
    // code
}
```

`do` expression is already in stage 1 and so is Block params. So why not adding it? Pipeline operator is in stage 1, yet here we have it in Babel. I think that **at least** `do` expressions should be in Babel.

- [Block Params](https://github.com/samuelgoto/proposal-block-params)
- [Do expressions](https://github.com/tc39/proposal-do-expressions)

**Comment by nicolo-ribaudo** [comment]
Do expressions are already supported. https://babeljs.io/docs/en/babel-plugin-proposal-do-expressions.

The code you posted as an example isn't valid, since an expression statement can't start with `do {` (it would be confused with do/while).

**Comment by Sceat** [comment]
what about block params ? it's hell of a sexy feature

**Comment by nicolo-ribaudo** [comment]
I remember that some tc39 members said that that proposal is unlikely to proceed as-is.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue; not because we don't want to support them, but becasue we already track proposals implementation status in another repository: https://github.com/babel/proposals/issues/53
