### ISSUE TITLE
breaking change in @babel/preset-env 7.4.0

### ISSUE THREAD

**Issue by andreineculau** [babel/babel#9707]
## Bug Report

**Current Behavior**
isPluginRequired is not exported anymore from `@babel/preset-env`

**Input Code**

```js
let {isPluginRequired} = require('babel-preset-env');
```

**Expected behavior/code**

isPluginRequired would be a function, not undefined, with the same signature as before.

**Babel Configuration (.babelrc, package.json, cli command)**
-

**Environment**
-

**Possible Solution**

Whether functions like `isPluginRequired` were intended or not to be exposed is a matter of its own, but such a refactoring should not be done in a minor-version bump.

**Additional context/Screenshots**
-

**Comment by andreineculau** [comment]
ping @nicolo-ribaudo @zloirock

**Comment by zloirock** [comment]
Is this a public API?

**Comment by hzoo** [comment]
Ok either way (if we wanted it to be public API or not) that was unintentional to remove a previously exported function. Nicolo made a PR
