### ISSUE TITLE
Feature: preprocess template literals

### ISSUE THREAD

**Issue by jussi-kalliokoski** [babel/babel#971]
One thing I've been thinking about a lot when using template strings is that it would be sweet to be able to define some preprocessing for template strings, especially when used to just create multiline strings without variables. This could be added by being able to specify specially treated tags. For example:

```javascript
var html = minify`<html>
  <head>
  </head>
  <body>
  </body>
</head>`;
```

then if you pass in a html minifier as a preprocessor tag named `minify`, you'd get

```javascript
var html = "<html><head></head><body></body></html>";
```

I don't have my own horse in the race as I no longer for example use angular that much, where this would be especially handy. :)

**Comment by sebmck** [comment]
This would likely be conflating runtime and compile-time logic which is kinda iffy and a slippery slope IMO. You wouldn't be able to deal with interpolated expressions since you'd obviously need runtime knowledge. Not sure how helpful this would be either since you'd just hoist the literal so it's only ran once. Thanks for the suggestion though! I'll tag this as "revisit" as something to potentially revisit in the future.

**Comment by jussi-kalliokoski** [comment]
@sebmck: :+1:

**Comment by kpdecker** [comment]
My reading of the spec effectively defines this behavior FWIW: http://www.ecma-international.org/ecma-262/6.0/#sec-gettemplateobject Step 5 and Note 2 dictate that there is only ever one template object for a given raw string. Implementing this would drastically improve performance of tagged templates and prevent issues where users try to write code around this behavior, i.e.

```
var map = new Map();
function tag(templateObj) {
  map.set(templateObj, extraData);
}
```

It's a bit of a reach but full spec compliance would need it... this does not address the question of if it's worth the complexity of implementing realm.templateMap :)

**Comment by sebmck** [comment]
Yeah, I know. It's actually noted in a disabled [Traceur test comment](https://github.com/babel/babel/blob/master/test/core/traceur.js#L59). There's no way to do it without a runtime.

**Comment by kpdecker** [comment]
It's not full compliance as that is at the global level and that would be a nightmare to manage across builds (in a performant manner), but what about "hoisting" the raw string definition to the current compilation context? I.e. this becomes this:

```
var _taggedTemplateLiteral = require("babel-runtime/helpers/tagged-template-literal")["default"];
var _myTaggedTemplateLiteral1 = _taggedTemplateLiteral(["", " ", ""], ["", " ", ""]);

var data = [1, 2, 3];
function fn(strings, value1, value2) {
  return strings[0] + value1 + strings[1] + value2 + strings[2];
}

test(function () {
  fn(_myTaggedTemplateLiteral1, data[0], data[1] + data[2]);
});};
```

**Comment by sebmck** [comment]
I'm having trouble working out what the original input was. Making it file-dependent is probably worth it in normal mode (ie. not loose mode).

**Comment by kpdecker** [comment]
Original:
```
var data = [1,2,3];
function fn(strings, value1, value2) {
  return strings[0] + value1 + strings[1] + value2 + strings[2];
}

test(function() {
  fn`${data[0]} ${data[1] + data[2]}`;
});
```
