### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by Vibing** [babel/babel#9712]
I use webpack@4.28.4 and babel@7.2.0 in my project.
```
{
	"@babel/cli": "^7.2.0",
	"@babel/core": "^7.2.0",
	"@babel/plugin-proposal-class-properties": "^7.2.1",
	"@babel/plugin-proposal-decorators": "^7.3.0",
	"@babel/plugin-proposal-object-rest-spread": "^7.2.0",
	"@babel/plugin-syntax-dynamic-import": "^7.2.0",
	"@babel/plugin-proposal-optional-chaining": "7.2.0",
	"@babel/polyfill": "^7.2.5",
	"@babel/preset-env": "^7.2.0",
	"@babel/preset-react": "^7.0.0",
	"@babel/preset-typescript": "^7.1.0"
}
```
But the project can't run in iPhone IOS9 Safari, it has a compile error:
<img width="1416" alt="WX20190320-135448@2x" src="https://user-images.githubusercontent.com/10387532/54663698-28abe700-4b1d-11e9-8ec2-140cee7f96c2.png">

The code that caused the error：
<img width="1387" alt="2" src="https://user-images.githubusercontent.com/10387532/54663774-56912b80-4b1d-11e9-8104-0957620ba541.png">

I tried to modify @babel/env to fix this error：
```js
"presets": [
    [
      "@babel/env",
      {
        "useBuiltIns": "usage",
        "targets": {
          "chrome": 52,
          "browsers": ["last 2 versions", "safari 7"]
        },
        "loose": true
      }
    ]
  ],
```
but it is invalid...

 I need a solution, please help me. (My English is not good, please forgive me.)

**Comment by danez** [comment]
Your configuration does not include ios safari 9. You can check your current browserlist query here: https://browserl.ist/?q=last+2+versions%2C+safari+7

Also currently you allow desktop Safari 7, but not 8, 9 and 10. So I assume you want safari 7 or newer?

What I would recommend is just using the browserlist query and include ios safari:
This way you can test which browsers are supported here: https://browserl.ist/?q=last+2+versions%2C+safari+%3E%3D+7%2C+ios_saf+%3E%3D+9%2C+chrome+%3E%3D+52

```
"presets": [
    [
      "@babel/env",
      {
        "useBuiltIns": "usage",
        "targets": {
          "browsers": "last 2 versions, safari >= 7, ios_saf >= 9, chrome >= 52"
        },
        "loose": true
      }
    ]
  ],

```

**Comment by Vibing** [comment]
> Your configuration does not include ios safari 9. You can check your current browserlist query here: https://browserl.ist/?q=last+2+versions%2C+safari+7
> 
> Also currently you allow desktop Safari 7, but not 8, 9 and 10. So I assume you want safari 7 or newer?
> 
> What I would recommend is just using the browserlist query and include ios safari:
> This way you can test which browsers are supported here: https://browserl.ist/?q=last+2+versions%2C+safari+%3E%3D+7%2C+ios_saf+%3E%3D+9%2C+chrome+%3E%3D+52
> 
> ```
> "presets": [
>     [
>       "@babel/env",
>       {
>         "useBuiltIns": "usage",
>         "targets": {
>           "browsers": "last 2 versions, safari >= 7, ios_saf >= 9, chrome >= 52"
>         },
>         "loose": true
>       }
>     ]
>   ],
> ```
> Here is the documentation of browserlist:
> https://github.com/browserslist/browserslist#full-list

@danez Thank you for your answer，I found the cause of the problem. I didn't compile node_modules in my webpack configuration，so some packages in node_modules contain `const`。All I have to do is compile these packages using webpack.

**Comment by simkessy** [comment]
Hi, 

I've been getting the same issue: 

```
const webpack = require("webpack");
var path = require("path");
var HardSourceWebpackPlugin = require("hard-source-webpack-plugin");
var HappyPack = require("happypack");
const pkg = require("./package.json");

module.exports = (env, commit) => {
 
    let plugins = [
        new HardSourceWebpackPlugin(),
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        new HappyPack({
            loaders: ["babel-loader"]
        }),
    ];

    return {
        entry: {
            app: ["whatwg-fetch", "@babel/polyfill", "./src/app/app.ts"]
        },
        resolve: {
            extensions: [".ts", ".tsx", ".js", ".jsx"]
        },
        output: {
            path: path.resolve(
                __dirname,
                "temp/" + envData.environment + "/app/js"
            ),
            filename: "[name].bundle.js",
            publicPath: "/"
        },
        optimization: {
            splitChunks: {
                cacheGroups: {
                    commons: {
                        test: /[\\/]node_modules[\\/]/,
                        name: "vendor",
                        chunks: "initial"
                    }
                }
            }
        },
        module: {
            rules: [
                {
                    test: /\.(js|jsx|ts|tsx)$/,
                    // exclude: /(node_modules)/,
                    loader: "happypack/loader",
                    options: { babelrc: true, cacheDirectory: "./cache" }
                },
 
            ]
        },
        plugins,
    };
};
```

Babelrc: 

```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": "55",
                    "ie": "8"
                }
            },
            "@babel/typescript"
        ]
    ]
}
```

This error is happening in IE 10

**Comment by gupnee81** [comment]
@Vibing - Could you please share webpack settings. I would like to refer them as I am facing same issue.

**Comment by MLDMoritz** [comment]
Experiencing same issues.

**Comment by simkessy** [comment]
Make sure you have the latest @babel/polyfill. 

They introduced a bug that caused this error. 

Run `npm i @babel/polyfill@latest` and it should fix the problem: https://github.com/babel/babel/pull/9812
