### ISSUE TITLE
Incorrect parser errors about undefined exports in Babel 7.4

### ISSUE THREAD

**Issue by devongovett** [babel/babel#9720]
## Bug Report

**Current Behavior**

`@babel/parser` 7.4 added checking for undefined exported bindings in #9589. This seems to be causing some issues for people in commonly used libraries like `history` and `react-intl`. Here's an example error from react-intl. The function it is complaining about is defined in the file, so this seems like a bug in the scope tracking in babel.

```
🚨  /Users/govett/dev/engage-monorepo/node_modules/react-intl/lib/index.es.js:1784:9: Export 'addLocaleData' is not defined (1784:9)
  1782 | addLocaleData(allLocaleData);
  1783 | 
> 1784 | export { addLocaleData, intlShape, injectIntl, defineMessages, IntlProvider, FormattedDate, FormattedTime, FormattedRelative, FormattedNumber, FormattedPlural, FormattedMessage, FormattedHTMLMessage };
       |         ^
  1785 | 
```

**Expected behavior/code**
Code should parse.

**Environment**
- Babel version(s): 7.4.1
- Node/npm version: Node 8
- OS: N/A
- Monorepo: N/A
- How you are using Babel: parcel

Related Parcel issue: https://github.com/parcel-bundler/parcel/issues/2819

**Comment by nicolo-ribaudo** [comment]
I checked both https://unpkg.com/history@4.9.0/esm/history.js and https://unpkg.com/react-intl@2.8.0/lib/index.es.js: Babel doesn't throw when parsing them.

Do you have a repository which shows the issue? (cc @robGetsTheJobDone, https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-474994808)

**Comment by devongovett** [comment]
maybe related to strict mode? we explicitly disable it in parcel. https://github.com/parcel-bundler/parcel/issues/2820#issuecomment-474963945

**Comment by nicolo-ribaudo** [comment]
Ok, I can reproduce the bug :+1:

**Comment by danez** [comment]
The parser adheres to the spec and the spec says that when the target is es module, the file is in strict mode. Disabling strict mode is incorrect. Why are you disabling strict mode?

**Comment by nicolo-ribaudo** [comment]
Well, we have that option explicitly to disable `strictMode` so Babel should handle that case.

**Comment by benjamn** [comment]
Can this be reopened, please? I noticed the same problem while updating Meteor to the latest `@babel/parser` version. We have Babel plugins that make everything work later in the pipeline, so it's super inconvenient for the parser to be enforcing these rules at the very beginning. Making that change in a minor update is especially surprising. For what it's worth, I don't particularly care about the default behavior—I would be happy with an option to disable undefined export checking, since that would be something Meteor can control. Please trust your users to know what's best for them. 🙏

**Comment by danez** [comment]
@benjamn Do you have an example on how Meteor uses exports exactly? It would help us decide how to solve this.

**Comment by benjamn** [comment]
@danez Our plugin pipeline injects some variable declarations into module scope, which makes those variables safe to export, though there's no way for `@babel/parser` to know about those future injections just looking at the source code. This is how Meteor packages share variables while still following the rules of ESM, if you're curious.

I'm not saying this is a super common pattern, but it definitely happens. For example, a Meteor package that uses Mocha for testing relies on Meteor injecting a `mocha` variable declaration from another helper package, and then re-exports that identifier for use by test code. If this was a core Meteor package, I could just fix it to play by the new rules, but it wasn't written by us, and there are probably many other community packages that will be tripped up by this change.
