### ISSUE TITLE
Update regexpu-core dependency to v4.5.4

### ISSUE THREAD

**Issue by mathiasbynens** [babel/babel#9721]
regexpu-core@4.5.4 is out with a bugfix.

The bug caused the following properties to miss some code point ranges:

```
Alphabetic
Assigned
Bidi_Mirrored
Case_Ignorable
Cased
Changes_When_Casefolded
Changes_When_Casemapped
Changes_When_Lowercased
Changes_When_NFKC_Casefolded
Changes_When_Titlecased
Changes_When_Uppercased
Diacritic
Emoji
Grapheme_Base
Grapheme_Extend
ID_Continue
ID_Start
Lowercase
Math
Terminal_Punctuation
Uppercase
XID_Continue
XID_Start
General_Category=Cased_Letter
General_Category=Decimal_Number
General_Category=Letter
General_Category=Lowercase_Letter
General_Category=Mark
General_Category=Nonspacing_Mark
General_Category=Number
General_Category=Other
General_Category=Other_Letter
General_Category=Other_Number
General_Category=Other_Punctuation
General_Category=Other_Symbol
General_Category=Punctuation
General_Category=Spacing_Mark
General_Category=Symbol
General_Category=Unassigned
General_Category=Uppercase_Letter
Script=Common
Script_Extensions=Common
```

i.e. any uses of these within `/\p{Foo}/u` or `/\P{Foo}/u` are currently transpiled incorrectly.

Does anyone want to do the honors and submit a PR updating the dependency? :)

**Comment by existentialism** [comment]
Is there a newer version that 4.5.4?

We're already on [4.5.4](https://github.com/babel/babel/pull/9672) 😄

**Comment by nicolo-ribaudo** [comment]
Whoops, I already even tweeted about the new [help wanted] bug lol

**Comment by mathiasbynens** [comment]
Oh wow 😅 I hadn’t seen any follow-up to https://github.com/babel/babel/pull/9642#issuecomment-471648960 so just assumed it slipped the cracks. My bad, and thanks for the fix! <3

**Comment by existentialism** [comment]
No, my fault... I should have followed up on that comment, thanks again for the reminder to update!
