### ISSUE TITLE
Named capture groups - groups array not correct when using literal expressions

### ISSUE THREAD

**Issue by kurt-genus** [babel/babel#9722]
## Bug Report

**Current Behavior**
If I have mutliple literal regex's, it seems to interfere with the groups array on the exec results.

**Input Code**

```js

const regex1=/(?<alpha>\w+):(?<bravo>\d+)/;
const regex2=/(?<alpha>\w+):(?<bravo>[a-z]+):(?<charlie>\w+)/;

let foo='foo:abc:bar';
let result;

if(result= regex1.exec( foo ) ) {
  console.log( result);
} else if( result=regex2.exec(foo) ) {
  console.log( result );
}
```

**Expected behavior/code**
If you look at the code above, what I expect in the log is for the groups array to contain an entry for "charlie" because that is the expression which matched. However, this is what I see instead:

(4) ["foo:abc:bar", "foo", "abc", "bar", index: 0, input: "foo:abc:bar", groups: {…}]
0: "foo:abc:bar"
1: "foo"
2: "abc"
3: "bar"
groups: {alpha: "foo", bravo: "abc"}
index: 0
input: "foo:abc:bar"
length: 4
__proto__: Array(0)

result.groups.charlie is undefined even though result[3] is set to "bar".

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "name": "genus-player",
  "version": "1.0.0",
  "description": "Media Player component for Genus MediaUpshot assets",
  "main": "dist/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --mode development",
    "build": "babel src -d dist --copy-files",
    "install": "babel src -d dist --copy-files"
  },
  "author": "",
  "license": "ISC",
  "peerDependencies": {
    "prop-types": "^15.7.2",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-pdf-js": "^4.0.2",
    "video.js": "^7.4.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/plugin-proposal-class-properties": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.1",
    "html-webpack-plugin": "^3.2.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-pdf-js": "^4.0.2",
    "script-ext-html-webpack-plugin": "^2.1.3",
    "style-loader": "^0.23.1",
    "video.js": "^7.4.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.2.1"
  }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version:6.9
- OS: linux
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
What is your Babel config and what is the generated output?

**Comment by kurt-genus** [comment]
.babelrc
{
    "presets": ["@babel/env", "@babel/react"],
    "plugins": ["@babel/plugin-proposal-class-properties"]
}

The generated output contains more than just this issue, I'll see if I can't get a complete working version.

But here is what I think is the relevant portion :
 var regex1 = _wrapRegExp(/(\w+):(\d+)/, {
        alpha: 1,
        bravo: 2
      });

      var regex2 = _wrapRegExp(/(\w+):([a-z]+):(\w+)/, {
        alpha: 1,
        bravo: 2,
        charlie: 3
      });

      var foo = 'foo:abc:bar';
      var result;

      if (result = regex1.exec(foo)) {
        console.log(result);
      } else if (result = regex2.exec(foo)) {
        console.log(result);
      }

tion _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _wrapRegExp(re, groups) { _wrapRegExp = function _wrapRegExp(re, groups) { return new BabelRegExp(re, groups); }; var _RegExp = _wrapNativeSuper(RegExp); var _super = RegExp.prototype; var _groups = new WeakMap(); function BabelRegExp(re, groups) { var _this = _RegExp.call(this, re); _groups.set(_this, groups); return _this; } _inherits(BabelRegExp, _RegExp); BabelRegExp.prototype.exec = function (str) { var result = _super.exec.call(this, str); if (result) result.groups = buildGroups(result, this); return result; }; BabelRegExp.prototype[Symbol.replace] = function (str, substitution) { if (typeof substitution === "string") { var groups = _groups.get(this); return _super[Symbol.replace].call(this, str, substitution.replace(/\$<([^>]+)>/g, function (_, name) { return "$" + groups[name]; })); } else if (typeof substitution === "function") { var _this = this; return _super[Symbol.replace].call(this, str, function () { var args = []; args.push.apply(args, arguments); if (_typeof(args[args.length - 1]) !== "object") { args.push(buildGroups(args, _this)); } return substitution.apply(this, args); }); } else { return _super[Symbol.replace].call(this, str, substitution); } }; function buildGroups(result, re) { var g = _groups.get(re); return Object.keys(groups).reduce(function (groups, name) { groups[name] = result[g[name]]; return groups; }, Object.create(null)); } return _wrapRegExp.apply(this, arguments); }

function _wrapNativeSuper(Class) { var _cache = typeof Map === "function" ? new Map() : undefined; _wrapNativeSuper = function _wrapNativeSuper(Class) { if (Class === null || !_isNativeFunction(Class)) return Class; if (typeof Class !== "function") { throw new TypeError("Super expression must either be null or a function"); } if (typeof _cache !== "undefined") { if (_cache.has(Class)) return _cache.get(Class); _cache.set(Class, Wrapper); } function Wrapper() { return _construct(Class, arguments, _getPrototypeOf(this).constructor); } Wrapper.prototype = Object.create(Class.prototype, { constructor: { value: Wrapper, enumerable: false, writable: true, configurable: true } }); return _setPrototypeOf(Wrapper, Class); }; return _wrapNativeSuper(Class); }

**Comment by kurt-genus** [comment]
`
 var regex1 = _wrapRegExp(/(\w+):(\d+)/, {
        alpha: 1,
        bravo: 2
      });

      var regex2 = _wrapRegExp(/(\w+):([a-z]+):(\w+)/, {
        alpha: 1,
        bravo: 2,
        charlie: 3
      });

      var foo = 'foo:abc:bar';
      var result;

      if (result = regex1.exec(foo)) {
        console.log(result);
      } else if (result = regex2.exec(foo)) {
        console.log(result);
      }
function _wrapRegExp(re, groups) { _wrapRegExp = function _wrapRegExp(re, groups) { return new BabelRegExp(re, groups); }; var _RegExp = _wrapNativeSuper(RegExp); var _super = RegExp.prototype; var _groups = new WeakMap(); function BabelRegExp(re, groups) { var _this = _RegExp.call(this, re); _groups.set(_this, groups); return _this; } _inherits(BabelRegExp, _RegExp); BabelRegExp.prototype.exec = function (str) { var result = _super.exec.call(this, str); if (result) result.groups = buildGroups(result, this); return result; }; BabelRegExp.prototype[Symbol.replace] = function (str, substitution) { if (typeof substitution === "string") { var groups = _groups.get(this); return _super[Symbol.replace].call(this, str, substitution.replace(/\$<([^>]+)>/g, function (_, name) { return "$" + groups[name]; })); } else if (typeof substitution === "function") { var _this = this; return _super[Symbol.replace].call(this, str, function () { var args = []; args.push.apply(args, arguments); if (_typeof(args[args.length - 1]) !== "object") { args.push(buildGroups(args, _this)); } return substitution.apply(this, args); }); } else { return _super[Symbol.replace].call(this, str, substitution); } }; function buildGroups(result, re) { var g = _groups.get(re); return Object.keys(groups).reduce(function (groups, name) { groups[name] = result[g[name]]; return groups; }, Object.create(null)); } return _wrapRegExp.apply(this, arguments); }

function _wrapNativeSuper(Class) { var _cache = typeof Map === "function" ? new Map() : undefined; _wrapNativeSuper = function _wrapNativeSuper(Class) { if (Class === null || !_isNativeFunction(Class)) return Class; if (typeof Class !== "function") { throw new TypeError("Super expression must either be null or a function"); } if (typeof _cache !== "undefined") { if (_cache.has(Class)) return _cache.get(Class); _cache.set(Class, Wrapper); } function Wrapper() { return _construct(Class, arguments, _getPrototypeOf(this).constructor); } Wrapper.prototype = Object.create(Class.prototype, { constructor: { value: Wrapper, enumerable: false, writable: true, configurable: true } }); return _setPrototypeOf(Wrapper, Class); }; return _wrapNativeSuper(Class); }


`

**Comment by nicolo-ribaudo** [comment]
OT: You need to use three ```

**Comment by kurt-genus** [comment]
Thanks. And I will preview before posting it.
```
 var regex1 = _wrapRegExp(/(\w+):(\d+)/, {
        alpha: 1,
        bravo: 2
      });

      var regex2 = _wrapRegExp(/(\w+):([a-z]+):(\w+)/, {
        alpha: 1,
        bravo: 2,
        charlie: 3
      });

      var foo = 'foo:abc:bar';
      var result;

      if (result = regex1.exec(foo)) {
        console.log(result);
      } else if (result = regex2.exec(foo)) {
        console.log(result);
      }

function _wrapRegExp(re, groups) { _wrapRegExp = function _wrapRegExp(re, groups) { return new BabelRegExp(re, groups); }; var _RegExp = _wrapNativeSuper(RegExp); var _super = RegExp.prototype; var _groups = new WeakMap(); function BabelRegExp(re, groups) { var _this = _RegExp.call(this, re); _groups.set(_this, groups); return _this; } _inherits(BabelRegExp, _RegExp); BabelRegExp.prototype.exec = function (str) { var result = _super.exec.call(this, str); if (result) result.groups = buildGroups(result, this); return result; }; BabelRegExp.prototype[Symbol.replace] = function (str, substitution) { if (typeof substitution === "string") { var groups = _groups.get(this); return _super[Symbol.replace].call(this, str, substitution.replace(/\$<([^>]+)>/g, function (_, name) { return "$" + groups[name]; })); } else if (typeof substitution === "function") { var _this = this; return _super[Symbol.replace].call(this, str, function () { var args = []; args.push.apply(args, arguments); if (_typeof(args[args.length - 1]) !== "object") { args.push(buildGroups(args, _this)); } return substitution.apply(this, args); }); } else { return _super[Symbol.replace].call(this, str, substitution); } }; function buildGroups(result, re) { var g = _groups.get(re); return Object.keys(groups).reduce(function (groups, name) { groups[name] = result[g[name]]; return groups; }, Object.create(null)); } return _wrapRegExp.apply(this, arguments); }

function _wrapNativeSuper(Class) { var _cache = typeof Map === "function" ? new Map() : undefined; _wrapNativeSuper = function _wrapNativeSuper(Class) { if (Class === null || !_isNativeFunction(Class)) return Class; if (typeof Class !== "function") { throw new TypeError("Super expression must either be null or a function"); } if (typeof _cache !== "undefined") { if (_cache.has(Class)) return _cache.get(Class); _cache.set(Class, Wrapper); } function Wrapper() { return _construct(Class, arguments, _getPrototypeOf(this).constructor); } Wrapper.prototype = Object.create(Class.prototype, { constructor: { value: Wrapper, enumerable: false, writable: true, configurable: true } }); return _setPrototypeOf(Wrapper, Class); }; return _wrapNativeSuper(Class); }

```

**Comment by nicolo-ribaudo** [comment]
Suggestion: use ```js to get syntax highlighting!

I have hidden your other two comments and edited the original one.
