### ISSUE TITLE
@babel/plugin-transform-typescript removes regular imports

### ISSUE THREAD

**Issue by hulkish** [babel/babel#9723]
## Bug Report

**Current Behavior**
[this logic](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/src/index.js#L75) seems to be introducing a bug for non-typescript code. 

Specifically, it is incorrectly removing a regular module import.

**Input Code**
```js
import foo from 'foo';
export bar from 'bar';
export * as baz from 'baz';

export default class Foobar {}
```

**Expected output**
```js
import foo from 'foo'; // why is this line is removed?
import _bar from 'bar';
export { _bar as bar };
import * as _baz from 'baz';
export { _baz as baz };
var Foobar = function Foobar() {};
export { Foobar as default };
```

**Actual output**
```js
import _bar from 'bar';
export { _bar as bar };
import * as _baz from 'baz';
export { _baz as baz };
export default class Foobar {}
```

**Babel Configuration (.babelrc, package.json, cli command)**
```js
{
  "presets": ["@babel/preset-typescript", { isTSX: true, allExtensions: true }]
}
```

**Environment**
- Babel version(s): `@babel/core@7.3.4`, `@babel/preset-typescript@7.3.3`
- Node/npm version: `npm@`, `node@10.15.3`
- OS: `macOS@10.14.1`
- Monorepo: yes, but doesn't matter - happens anywhere.
- How you are using Babel: directly using `transformFileSync()` from `@babel/core`

**Possible Solution**
Fix issue in `@babel/plugin-transform-typescript`

**Additional context/Screenshots**
N/A

**Comment by nicolo-ribaudo** [comment]
That is the expected behavior: https://www.typescriptlang.org/play/index.html#src=import%20foo%20from%20'foo'%3B%0A%0Aexport%20default%20class%20Foobar%20%7B%7D

In TypeScript, unused imports as considered as type imports and thus removed.

**Comment by hulkish** [comment]
@nicolo-ribaudo How is this considered safe? What if `foo` has side effects?

**Comment by nicolo-ribaudo** [comment]
I agree that it is unexpected, but it is a bug with the TypeScript language. We won't diverge from their implementation, so it needs to be fixed upstream first.

If you need `foo` for its side effects, you can use `import "foo"` and it shouldn't be removed.

**Comment by hulkish** [comment]
Understood, thanks for the explanation!
