### ISSUE TITLE
pkg: preset-env changelog is out of date

### ISSUE THREAD

**Issue by eddiemonge** [babel/babel#9730]
## Bug Report

**Current Behavior**
preset-env's changelog file is almost 2 years old

**Expected behavior/code**
The changelog file should be up to date or removed.

**Comment by zloirock** [comment]
The `preset-env` changelog from the `preset-env` directory related changes of this package when it was not a port of `babel` monorepo. You can find the actual changelog in the root of this repo.

**Comment by eddiemonge** [comment]
Hence my suggestion of removing it since it is no longer an accurate changelog. Or change it to say look at the root one.

**Comment by nicolo-ribaudo** [comment]
Yeah, we should move it to `.github/` and link in the main changelog, like we did for Babylon. Do you want to open a PR?
