### ISSUE TITLE
core-js upgrade to 3 seems like a breaking change (broke StorybookJS)

### ISSUE THREAD

**Issue by eddiemonge** [babel/babel#9731]
The upgrade in preset-env (and others) to core-js@3 seems like a breaking change. It broke my StorybookJS instance (which is probably a fault of Storybook). I am going to open a related issue on Storybook but just wanted some reference here. Feel free to close this if the maintainers disagree

**Comment by nicolo-ribaudo** [comment]
Does it seem related to https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-475008861?

**Comment by eddiemonge** [comment]
It looks like a similar issue. The specific error I get is

```
  ● Test suite failed to run

    Cannot find module 'core-js/modules/es6.object.define-property' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:202:17)
      at Object.<anonymous> (node_modules/@storybook/client-api/dist/index.js:3:1)
```
It looks like it is trying to load from core-js@3 instead of core-js@2

**Comment by nicolo-ribaudo** [comment]
Yeah, it's exactly that problem. They depend on core-js@2 (third line of https://unpkg.com/@storybook/client-api@5.0.3/dist/index.js) but it isn't specified in https://unpkg.com/@storybook/client-api@5.0.3/package.json
