### ISSUE TITLE
New Babel release creates too many `require()` and polyfills

### ISSUE THREAD

**Issue by ehmicky** [babel/babel#9736]
## Bug Report

**Current Behavior**
When trying to compile a line like `Promise.race([])` with `@babel/preset-env`:
  1) polyfills and ponyfills are added even though the target environment (Node `8.10.0`) supports `Promise.race()`.
  2) Some polyfilling is performed, where I was expecting only ponyfilling to happen with the latest release. I.e. I was not expecting globals to be modifed.
  3) I'm not sure this is a problem or not, but `core-js` gets required, where I expected only `@babel/runtime-corejs3` to be required in compiled code. I.e. I was expecting to only have to install `@babel/runtime-corejs3` as a production dependency.

I am choosing `Promise.race([])` for simplicity sake but this happens with other common methods such as `Function.bind()`

This behavior did not happen in previous releases.

**Input Code**

`test.js`:

```js
Promise.race([])
```

Output of `babel test.js`:

```js
"use strict";

var _interopRequireDefault = require("@babel/runtime-corejs3/helpers/interopRequireDefault");

require("core-js/modules/es.array.iterator");

require("core-js/modules/es.promise");

var _promise = _interopRequireDefault(require("@babel/runtime-corejs3/core-js-stable/promise"));

_promise.default.race([]);
```

**Expected behavior/code**
`Promise.race([])` should be compiled as is (no modifications nor imports needed).

**Babel Configuration (.babelrc.js)**

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      { targets: { node: '8.10.0' }, useBuiltIns: 'usage', corejs: '3' },
    ],
  ],
  plugins: [['@babel/plugin-transform-runtime', { corejs: 3 }]],
}
```

**Environment**

```bash
npm ls @babel/cli @babel/core @babel/plugin-transform-runtime @babel/preset-env @babel/runtime core-js @babel/runtime-corejs3
/home/ether/Desktop
├── @babel/cli@7.2.3 
├── @babel/core@7.4.0 
├── @babel/plugin-transform-runtime@7.4.0 
├─┬ @babel/preset-env@7.4.2
│ └─┬ core-js-compat@3.0.0
│   └── core-js@3.0.0 
└── @babel/runtime-corejs3@7.4.2
```

Node/npm version: node `v11.12.0`, npm `6.9.0`
OS: Ubuntu `18.10`
Monorepo: no
How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
`@babel/plugin-transform-runtime` compiles down to ES5: it is a separate plugin from `@babel/preset-env` and it isn't affected by the other config.

Also, transform-runtime and `useBuiltIns: usage` address the same problem but with different approaches: you should choose one of them, not both.
- transform-runtime doesn't pollute the global scope, but polyfills everything
- useBuiltIns only injects needed polyfills, but it defines them in the global env.

**Comment by ehmicky** [comment]
Thanks for your reply. Please let me know if I understood correctly:
  - `@babel/plugin-transform-runtime` does not modify globals, but it always compile down to ES5.
  - `@babel/preset-env` with `useBuiltIns: usage` modifies globals, but one can choose a target environment.

If I understood this correctly: is there a way to get the best of both, i.e. not modifying globals while targeting a specific environment?

When it comes to the compat data source, your explanation makes sense for `es.promise`. But why is [`es.array.iterator`](https://github.com/zloirock/core-js/blob/v3.0.0/packages/core-js/modules/es.array.iterator.js) required here? It seems like this is injected [for `chrome <=66`](https://github.com/zloirock/core-js/blob/49f7664a89a2710196d868d76c702dc19fe6ee49/packages/core-js-compat/src/data.js#L165), i.e. [`Node <10.0`](https://github.com/zloirock/core-js/blob/49f7664a89a2710196d868d76c702dc19fe6ee49/packages/core-js-compat/src/mapping.js#L21). My guess is that it's because of `Array.values()` which is only available since Node 10. However the code above is not using `Array.values()`. Is this because `es.promise` is using `Array.values()`?

**Comment by nicolo-ribaudo** [comment]
Yeah, it's correct. In the future we will probably add something `useBuiltIns: "runtime"` which would give the ideal result.

> But why is es.array.iterator required here? It seems like this is injected for chrome <=66, i.e. Node <10.0. 

I'm not sure, maybe @zloirock 	will know.

**Comment by zloirock** [comment]
V8 6.6 has [a serious bug in `Promise`](https://bugs.chromium.org/p/chromium/issues/detail?id=830565), so it's marked as unsupported for V8 < 6.7 -> NodeJS < 10.4. 

Yes, `es.array.iterator` here added because of missed `Array.prototype.values`, but it's too problematically get rid of this it this case since `Array.prototype[@@iterator]` and `Array.prototype.values` defined in one module, it's a problem of the current `preset-env` and `core-js` architecture, it can be splitted in the future. It's not very large and it concerns only a little part of the old engines, so I don't think that it something critical.

**Comment by evilebottnawi** [comment]
Maybe release.

Config:
```
 "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "6.9.0"
          },
          "useBuiltIns": "usage"
        }
      ]
    ]
  }
```

Insert `require("core-js/modules/es6.object.to-string");` when we compile code for node

**Comment by zloirock** [comment]
This module not required from NodeJS 6.0, for older versions it's required for `@@toStringTag` support, but seems because you implicitly use `corejs: 2`, here used not completely correct data from `compat-table`.

**Comment by ehmicky** [comment]
@nicolo-ribaudo Oh I understand now what you meant by that `runtime` option in the `core-js` release article. Looking forward to that feature! For the moment I think modifying globals is a lesser level than adding unnecessary ponyfills/helpers (which would increase bundle size and decrease performance), so I will stick with only `@babel/preset-env` and remove `@babel/plugin-runtime-transform`.

@zloirock thanks for the explanation.

I am closing this issue as this not a bug, but a mix of me not understanding the configuration, and features planned in the roadmap.

**Comment by evilebottnawi** [comment]
@zloirock looks like regression and breaking change, before it is doesn't add polyfill(s). now it is break code for node

**Comment by ehmicky** [comment]
@evilebottnawi You might want to add a separate issue, as my initial problem was resolved in this issue.

**Comment by zloirock** [comment]
@evilebottnawi how it can break any code for node? It's a fix of old `preset-env` bug.

**Comment by evilebottnawi** [comment]
@zloirock https://github.com/babel/babel/issues/9737
