### ISSUE TITLE
Unnecessary polyfills in code

### ISSUE THREAD

**Issue by evilebottnawi** [babel/babel#9737]
## Bug Report

**Current Behavior**

Babel insert unnecessary polyfills in code for node in new version

**Input Code**
- REPL or Repo link if applicable:

```js
console.log({}.toString)
```

Run:
```shell
node_modules/.bin/babel test.js
```

Output:
```
// Warning about core-js
"use strict";

require("core-js/modules/es6.object.to-string");

console.log({}.toString);
```

Looks like regression because previously we don't have polyfills in code.

**Expected behavior/code**

No unnecessary polyfills

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "6.9.0"
          },
          "useBuiltIns": "usage"
        }
      ]
    ]
}
```

**Environment**
- Babel version(s): latest (`babel-preset-env: 7.4.2`)
- Node/npm version: v10.15.0
- OS: Ubuntu 18.10
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**

No

**Additional context/Screenshots**

No

**Comment by evilebottnawi** [comment]
@zloirock because we don't have `core-js` in our dependencies so people get 
```
Error: Cannot find module 'core-js/modules/es6.object.to-string'
```

**Comment by zloirock** [comment]
If you haven't `core-js` in your dependencies, you should not use `useBuiltIns` option, no? -)

**Comment by evilebottnawi** [comment]
@zloirock disagree, when we setup this we use https://babeljs.io/docs/en/babel-preset-env#usebuiltins doc, no information about `core-js@2`/`core-js@3` and previously all work fine, now we should change setup and update this across multiple loader/plugin in `webpack`

**Comment by zloirock** [comment]
This docs still not changed. See, at least, this note:
> This option adds direct references to the `core-js` module as bare imports. Thus `core-js` will be resolved relative to the file itself and needs to be accessible. You may need to specify `core-js@2` as a top level dependency in your application if there isn't a `core-js` dependency or there are multiple versions.

**Comment by zloirock** [comment]
See [this explanation](https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-475008861) of your problem from @nicolo-ribaudo.

**Comment by evilebottnawi** [comment]
@zloirock seriously, you just closed the problem? Behavior was changed in patch versions and it is not breaking change?

**Comment by evilebottnawi** [comment]
I understand why this is happening, my issue about it was breaking change in minor/patch release, what potentially break code for many developers

**Comment by zloirock** [comment]
Your issue is a duplicate of many other related issues. It's a breaking change for you only because of your or other your dependencies mistake, not `babel` or `core-js`, and it's a very popular mistake. But it's not a reason for stop `core-js` and `babel` progress.

**Comment by evilebottnawi** [comment]
@zloirock it should not break code, and for breaking change exists major release

**Comment by zloirock** [comment]
@evilebottnawi did you check [this explanation](https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-475008861)? It's not a breaking change in `babel`. You could have this kind of issues even if `babel@7.4` was not released since after `core-js@3` release your dependencies would not be resolved correctly because you missed `core-js` in your `package.json`.

**Comment by evilebottnawi** [comment]
it is still `transitive` breaking change, okey, apparently not enough developers talk about this so say something is useless
