### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by andreypopp** [babel/babel#974]
As I understand, [decorators](https://github.com/jonathandturner/brainstorming/blob/master/README.md) are going to be suggested to TC39. I also think they are useful for [higher-order React components](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775).

Example:
```
// decorator is a function
function annotation(target) {  
   // Add a property on target  
   target.annotated = true;  
}

// its usage
@annotation  
class MyClass { } 

// compiles to something like
class MyClass {}
MyClass = annotation(MyClass)
```

**Comment by andreypopp** [comment]
Seems like TypeScript also plans to implement them. Microsoft/TypeScript#2249

**Comment by sebmck** [comment]
Are you requesting they be implemented now or enquiring if they will be once they've got a stable spec?

**Comment by andreypopp** [comment]
@sebmck yes, this is a feature request.

**Comment by sebmck** [comment]
@andreypopp Yup, I have every intention of implementing them. Waiting on the next TC39 meeting where they'll be presented (~2 weeks away!) and then hopefully I can gauge their stability.

**Comment by truongsinh** [comment]
I would like to add : http://blogs.msdn.com/b/typescript/archive/2015/03/05/angular-2-0-built-on-typescript.aspx

**Comment by jayphelps** [comment]
I'm anxiously awaiting too

![omg](http://1.bp.blogspot.com/-li_Gqo7n7oE/Ubf84t4ymzI/AAAAAAAAAEg/FSRR7go69N0/s1600/resizedimage.gif)

**Comment by zloirock** [comment]
[Private fields](https://github.com/zenparsing/es-private-fields)  (will be discussed in next tc39 meeting) conflict with decorators - uses the same syntax.

**Comment by domenic** [comment]
@zloirock false, they both use an `@` sign, but there is no syntax conflict.

**Comment by zloirock** [comment]
@domenic I do not see the difference: [class method declaration](https://github.com/jonathandturner/brainstorming/blob/master/README.md#35-class-method-declaration), [private fields](https://github.com/zenparsing/es-private-fields#a-brief-introduction).

**Comment by domenic** [comment]
@zloirock the decorators appear on top of a method declaration; the private fields do not.

**Comment by zloirock** [comment]
@domenic I do not understand. In the examples I see it:
```js
class Class {
  @decorator
  @privateField;
  method(){}
}
```

**Comment by domenic** [comment]
Yes, that works just fine. It declares a private field named `privateField` and applies the decorator `decorator` to `method`.

**Comment by zloirock** [comment]
@domenic i.e. the only difference is the presence of semicolons? Their joint application will make code unreadable and will cause a lot of bugs.

**Comment by domenic** [comment]
I disagree.
________________________________

**Comment by sebmck** [comment]
In a language with ASI relying on semicolons to distinguish declarators and private methods is dangerous.

**Comment by wycats** [comment]
We definitely will need to work out apparent syntactic conflicts between private fields and decorators. This is why we can't simply ship features one at a time, but need to vet them as a whole.

The JavaScript Decorators proposal I plan to present to TC39 in Paris is at https://github.com/wycats/javascript-decorators. I will be working with @zenparsing ahead of that meeting to see what we can come up with that won't conflict but still be possible to prototype in the short term via babel.

**Comment by wycats** [comment]
At minimum, trying to use `@` syntax for both in class bodies is visually very confusing.

**Comment by domenic** [comment]
Yeah, it's confusing, no disagreement there. Just saying that there's no conflict that would prevent both from being implemented as-is.

**Comment by zenparsing** [comment]
As @wycats mentioned, we're working together now on this intersection.  Unfortunately, we're designing within a very constrained syntactic space, but that's all part of the fun.  : )

**Comment by sebmck** [comment]
A complete implementation will be available in the next major behind the experimental flag. It's not recommended to use them in production code as breaking changes will be introduced without bumping the major as the proposal develops.

**Comment by truongsinh** [comment]
@sebmck so is it available from `master` already?

**Comment by sebmck** [comment]
@truongsinh No, I try not to do unstable development on the `master` branch. It's available in the `experimental` branch which is undergoing a lot of development in preparation for 5.0.0.

**Comment by truongsinh** [comment]
Thanks, I think I'll try in the `experimental` branch

**Comment by truongsinh** [comment]
@sebmck which commit is it btw?

**Comment by sebmck** [comment]
@truongsinh Commit for what?

**Comment by sebmck** [comment]
@truongsinh Whoops, totally thought I was in a different thread. e04ecc79c7c3709b5b510d135db8032922af2636, daecec2a861e7d664c533115bd8f62dfede261e9 and others.
