### ISSUE TITLE
Ignore option is not working

### ISSUE THREAD

**Issue by rico345100** [babel/babel#9740]
## Bug Report

**Current Behavior**
I want to exclude test codes from transpiling, but using ignore option totally won't worked. My test files are located in "src/" like "src/module.test.js".

I tried with setting .babelrc and run command directly with --ignore option, but no luck.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": [
        "@babel/preset-flow",
        ["@babel/preset-env", {
            "modules": false,
            "targets": {
                "node": 4
            }
        }]
    ],
    "env": {
        "test": {
            "presets": [
                ["@babel/preset-env"]
            ]
        }
    },
    // None of these working
    "ignore": [
        "src/**/*.test.js",
        "**/*.test.js",
        "**.test.js",
        "src/module.test.js"
    ]
}
```

**Environment**
- Babel version(s): 7.3.4
- Node/npm version: 11.0
- OS: macOS 10.13.1
- How you are using Babel: cli with npm scripts

**Comment by loganfsmyth** [comment]
Would you be able to make a reproducible example repo?

**Comment by rico345100** [comment]
@loganfsmyth Sure, here's the repo:
https://github.com/rico345100/socket.io-file/tree/dev-3.0

**Comment by rico345100** [comment]
Nah, maybe using --copy-file option with --ignore doesn't work. I solved by not using copy-file-option. Thanks!

**Comment by chase-moskal** [comment]
@rico345100 -- i seem to be having the same issue, babel is ignoring my `ignore` rules and trying to compile `node_modules`.. i must be doing something wrong, there's no way there's a bug this critical in babel?
