### ISSUE TITLE
preset-env does not consider browser not supporting generators, and does not automatically use runtime transformation (to convert generators to functions)

### ISSUE THREAD

**Issue by niftylettuce** [babel/babel#9741]
Simple babel configuration:

```sh
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": [ "> 1%", "last 2 versions" ]
      }
    }]
  ]
}
```

With the following simple babel config, I would assume that since browsers (e.g. IE11) do not support generators, then it would compile them using runtime transformation.

This isn't really documented in https://babeljs.io/docs/en/babel-preset-env.

**Comment by nicolo-ribaudo** [comment]
What does it log if you add `"debug": true` to the options of the preset?

**Comment by niftylettuce** [comment]
Sorry, this was a bug on my end (I was accidentally excluding it... 🤦‍♂️ ).  Thank you for your time helping @nicolo-ribaudo.
