### ISSUE TITLE
when I use @babel/plugin-syntax-dynamic-import to import some ui components, get error.

### ISSUE THREAD

**Issue by seek-distance** [babel/babel#9744]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
![image](https://user-images.githubusercontent.com/18638579/54806725-df42cf80-4cb5-11e9-966c-e1873260d1f1.png)
![image](https://user-images.githubusercontent.com/18638579/54806734-e2d65680-4cb5-11e9-812f-cf460288a583.png)
at this time my .babelrc is 
```js
{
  "presets": [
    ["@babel/preset-env", {
      "useBuiltIns": "usage",
    }]
  ],
  "plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ],
    "add-module-exports",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-modules-commonjs",
  ]
}
```
when I remove "@babel/plugin-transform-modules-commonjs", it run correctly.

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: Node 10.15.1/npm 6.4.1
- OS: OSX 10.13.4
- How you are using Babel: loader

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
It probably conflicts with something you have to load case files using `import`. Anyway, when using webpack it is better to let webpack handle import/export, so you don't need that Babel plugin.

**Comment by nicolo-ribaudo** [comment]
Closing, as this is a problem with the configuration: imports shouldn't be transpiled if they need to be processed by webpack loaders.
