### ISSUE TITLE
Trailing commas in iterable destructuring

### ISSUE THREAD

**Issue by webbedspace** [babel/babel#975]
`var [a,] = [1]` [is erroneously regarded as invalid](https://babeljs.io/repl/#?experimental=false&playground=false&evaluate=false&loose=false&spec=true&code=var%20[a%2C]%20%3D%20[1%2C2]%0A).

[Source](https://twitter.com/awbjs/status/574791053619785728)

**Comment by sebmck** [comment]
Please report this upstream at [acorn](https://github.com/marijnh/acorn).

**Comment by marijnh** [comment]
This is now fixed on the `v1` branch. The intention is to push out a release based on that _real soon now_.

**Comment by sebmck** [comment]
Awesome, thanks @marijnh for your awesome work on acorn! I'm really excited for the plugin system in v1.
