### ISSUE TITLE
[@babel/preset-env] Provides broken warnings on compile with useBuiltIns

### ISSUE THREAD

**Issue by bradennapier** [babel/babel#9751]
## Bug Report

**Current Behavior**

```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```

When using `useBuiltIns` it is giving this warning.  So I changed and used core-js 3.0.0 since it seemed like that was an option based on it saying i could run that.

I added `corejs` to the config stating 3.0.0, but then it just errors and no longer works:

```
Error: Cannot find module 'core-js/modules/es7.symbol.async-iterator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Shared/Development/projects/idex-server-v2/node_modules/@auroradao/logger/dist/constants.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Shared/Development/projects/idex-server-v2/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/Shared/Development/projects/idex-server-v2/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Note that installing and using corejs 2 does work - so this is just reporting about the fact its confusing it seems to indicate support of 3.0.0 when it doesnt have it**

**Expected behavior/code**

be more clear that i should not use core-js@3 if it is not supported / remove that entire set of yarn commands to not confuse people.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function getBabelConfiguration(api) {
  api.cache.never();
  return {
    presets: [
      [
        '@babel/preset-env',
        {
          useBuiltIns: 'usage',
          corejs: '3.0.0',
          shippedProposals: true,
          targets: {
            node: '10.15',
          },
        },
      ],
    ],
    plugins: [
      [
        'module-resolver',
        {
          root: ['./src/shared'],
        },
      ],
      '@babel/plugin-transform-flow-strip-types',
      '@babel/proposal-class-properties',
      '@babel/proposal-optional-chaining',
      'dynamic-import-node',
      'lodash',
    ],
  };
};

```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] See below
- Node/npm version: [e.g. Node 8/npm 5] Node 10.15
- OS: [e.g. OSX 10.13.4, Windows 10] OSX
- Monorepo: [e.g. yes/no/Lerna] no

```
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-flow": "^7.0.0",
```

**Comment by nicolo-ribaudo** [comment]
It's probably a bug with one of your dependencies (you can find it in the stack trace), which is importing `core-js` (and it is relying on core-js@2) without specifying it in their dependencies.

**Comment by bradennapier** [comment]
Sweet, thanks! Makes sense and yeah that is a private package.  Thanks!

**Comment by bradennapier** [comment]
@nicolo-ribaudo actually now i am trying to fix packages where this is an issue and using `corejs: 3` is not working on those now

```TypeError: [BABEL] /Users/Shared/Development/projects/task-handler/src/constants.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/Shared/Development/projects/task-handler/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/Shared/Development/projects/task-handler/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/Shared/Development/projects/task-handler/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/Shared/Development/projects/task-handler/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/Shared/Development/projects/task-handler/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/Shared/Development/projects/task-handler/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/Shared/Development/projects/task-handler/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/Shared/Development/projects/task-handler/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/Shared/Development/projects/task-handler/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/Shared/Development/projects/task-handler/node_modules/@babel/core/lib/config/full.js:74:38)```

**Comment by bradennapier** [comment]
Note to anyone doing this - I had to delete my node_modules when changing to core-js 3 or i got the following errors:

```
TypeError: [BABEL] /Users/Shared/Development/projects/task-handler/src/constants.js: (0 , _semver(...).coerce) is not a function
```

Guessing it is a cache issue, not quite sure.

**Comment by nicolo-ribaudo** [comment]
What is the error message for that stack trace?

**Comment by nicolo-ribaudo** [comment]
Yeah, that is our fault :stuck_out_tongue: It's fixed on master and it will be in the next release. In the meantime, as you mentioned, reinstalling node_modules should be enough.

**Comment by bradennapier** [comment]
Thanks, easy enough to fix :)

**Comment by mnpenner** [comment]
`corejs` option is not documented [here](https://babeljs.io/docs/en/babel-preset-env)

**Comment by jnwng** [comment]
> `corejs` option is not documented [here](https://babeljs.io/docs/en/babel-preset-env)

concretely, the set of options sent to `@babel/preset-env` needs to have this property like so:
```
{
  "presets": [
    "@babel/preset-flow",
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.10"
        },
        "corejs": "2", // <---
        "useBuiltIns": "usage"
      }
    ]
  ]
}
```

along with the dependency in `package.json`

**Comment by manigandham** [comment]
core-js@3 is a big new release with tighter integration into babel, worth reading the blog post: https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

> Since @babel/preset-env now supports core-js@2 and core-js@3, useBuiltIns requires setting a new option, corejs, which specifies the used version (corejs: 2 or corejs: 3). If it isn't directly set, corejs: 2 will be used by default and it will show a warning.

**Comment by crayner** [comment]
Came here looking for help on this one for Symfony Webpack throwing this warning.  In Symfony webpack.config.js add the following:
`    .configureBabel((babelConfig) => {
        const preset = babelConfig.presets.find(([name]) => name === "@babel/preset-env");
        if (preset !== undefined) {
            preset[1].useBuiltIns = "usage";
            preset[1].corejs = '3.0.0';
        }
    })
`

This appears to have removed the warning.
