### ISSUE TITLE
New @babel/parser early errors break by-name typescript exports

### ISSUE THREAD

**Issue by Jessidhia** [babel/babel#9763]
## Bug Report

**Current Behavior**
`@babel/parser` doesn't consider identifiers declared with typescript syntax as identifiers in scope.

**Input Code**

```ts
enum Test {}

export { Test as default }
```

**Expected behavior/code**
`export`s of typescript types should not be a build error.

This case is particularly strange as `Test` is _actually_ a concrete value; it's just declared with a typescript declaration.

This is the expected output, for reference:

```js
var Test;

(function (Test) {})(Test || (Test = {}));

export { Test as default }
```

Direct `export enum Test {}` is unaffected.

**Babel Configuration (.babelrc, package.json, cli command)**

Way too big, but just adding `@babel/plugin-syntax-typescript` to the REPL is sufficient to reproduce it. `@babel/plugin-transform-typescript` doesn't help as the error happens before any transforms can run.

**Environment**
- Babel version(s): 7.4.2
- Node/npm version: 11.10.0
- OS: macOS 18.2.0
- Monorepo: yes
- How you are using Babel: `babel-jest` / `babel-loader`

**Possible Solution**
Identifiers declared with `type`, `enum`, `interface` (and `namespace`) need to be considered as valid for `export`ing when the `typescript` plugin is enabled.

This same problem affects `flow` but the other way around. The following code is "valid syntax" in both flow and typescript; but babel can only parse the flow version, which is incorrect at runtime as flow requires explicitly annotating the export as a type export:

```ts
type Foo = {}
export { Foo }
```

**Comment by Jessidhia** [comment]
Tangentially related: `@babel/traverse` doesn't seem to track typescript identifiers on `Scope` at all.

Maybe it's some kind of missing `@babel/types` alias?

**Comment by benmosher** [comment]
I am also seeing this with function overloads. Here's a [repro (same code also below)](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEGMHsFtoUwHYBcCWCDmokAs6gGaQA2RkA7mpgIYAmNKqkCVRo6icATiuKDXOCJVOVRglCc4AZ2IA3aVlygUUqQFc4AfgBQcAB4AHSJyQE1CcGIJCkSRAB4AagD4AFNtDK7IgEZE4AFygAJLeVH5wTqAAPiFhEU7OzgA02gCUQaFc4f5ZIkjGidq6hsam-OaWKEwAVNaidgiuDNkRmfH-9lQIAJ7OGXGtuWEFnF29zqAA3h4ExqCu_qYt0KCQ-F5DcGnTs54oG81SeTlwzXbQaTs9KHBENHUre6B3Ung3dzSb0LMAvtr_EpGExmCxWcDYKhodyeAB08Javn8UiCrm6PRigyRkXR_QA2gBddLtLYnUbjPq7TySJBqTjifA2RrnLZSNIA4r6YGmKYQSFoUBUKQQJjgUSgf5AA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.4.2) -- you also have to explicitly add the `typescript` syntax plugin or it errors on syntax instead.

```ts
// commenting the following overload signature resolves the issue?
export function flatten<V>(
  iterable: Iterable<V | Iterable<V>>,
): IterableIterator<V>

export function* flatten(iterable: Iterable<any>): IterableIterator<any> {
  for (let item of iterable) {
    if (isIterable(item)) yield* item
    else yield item
  }
}

export function chain(
  ...iterables: (any | Iterable<any>)[]
): IterableIterator<any> {
  return flatten(iterables)
}

export { chain as concat }
```

output: 
```
/repl: Export 'chain' is not defined (19:9)

  17 | }
  18 | 
> 19 | export { chain as concat }
     |          ^
  20 | 
```

Also weird: `export { flatten as concat }` works fine. So I'm not able to intuit what is going on. Also this worked fine 2 hours ago before I regenerated my `yarn.lock`. 😅

**Comment by nicolo-ribaudo** [comment]
I'm working on this. Is it correct that enum are block-scoped, it is not an error to declare a var/function/enum with the same name in the same block but it is an error to redeclare it using let/const?

**Comment by nicolo-ribaudo** [comment]
This is an error:
```ts
enum Foo { }
var Foo;
```

But this is not:
```ts
{
    enum Foo { }
    var Foo;
}
```

:thinking: cc @babel/typescript

**Comment by fenok** [comment]
Looks like the issue is still there. I managed to reproduce it in [TypeScript-Babel-Starter](https://github.com/Microsoft/TypeScript-Babel-Starter) (with actual dependencies) with that:
```typescript
interface Test {}

export { Test }
```
```
SyntaxError: D:\TypeScript-Babel-Starter\src\index.ts: Exporting local "Test", which is not declared.
  1 | interface Test {}
  2 | 
> 3 | export { Test }
    |          ^
```

**Comment by nicolo-ribaudo** [comment]
I must have missed something in the PR; I will check it soon

**Comment by fenok** [comment]
https://gist.github.com/fenok/f0ebbda0c19c6f7e68ffd34f80f46b56

Not sure why it says `7.4.0`, @babel/parser in `node_modules` has version `7.4.4`
