### ISSUE TITLE
Babel transform seems to be stripping backslash path separators (used on Windows)

### ISSUE THREAD

**Issue by brandonweiss** [babel/babel#9765]
## Bug Report

**Current Behavior**

I have some code that is run through Babel like so:

```javascript
let code = `import React from "C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"`

let result = babelTransform(code, {
  presets: [
    require.resolve("@babel/preset-react"),
    [
      require.resolve("@babel/preset-env"),
      {
        targets: {
          node: "current",
        },
      },
    ],
  ],
})

result.code
```

This is the output (roughly):

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _UsersRavisUildRandonweisschargeOde_modulesEactindex = _interopRequireDefault(require("C:Users\travis\build\brandonweisscharge\node_modules\reactindex.js"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

The important part is:

```
"C:Users\travis\build\brandonweisscharge\node_modules\reactindex.js"
```

On Linux (with forward slashes) it works fine, but on Windows, Babel seems to have mysteriously removed several of the path separators, munging the path.

```
"C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js" // before
"C: Users\travis\build\brandonweiss charge\node_modules\react index.js" // after (spacing inserted to align)
```

**Input Code**

[REPL](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIgGEAuAHQFUBnJKS0mKFAN2DoCMBXYAGwBNS2jAHa8IQgO5JWdNAAsUUAOZJSQiLyQB9EOo7ckdKKgylgIpAA8AdACtK-IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.4.2)

**Expected behavior/code**

The path should be:

```
"C:Users\travis\build\brandonweiss\charge\node_modules\react\index.js"
```

**Environment**
- Babel version(s): ^7.4.0
- Node/npm version: 8
- OS: Windows Server, version 1803

**Comment by loganfsmyth** [comment]
Seems like 

```
let code = `import React from "C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"`
```
should be either
```
// escaped
let code = `import React from "C:\\Users\\travis\\build\\brandonweiss\\charge\\node_modules\\react\\index.js"`
// raw
let code = String.raw`import React from "C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"`
```
otherwise `\U` is literally an escaped `U`.

**Comment by nicolo-ribaudo** [comment]
Yeah, the example provided is wrong but this is a real bug: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIgGEAuAHQFUBnJKS0mKFAN2DoCMBXYAGwBNS2jAHa8IQgO5JWdNAAsUUAOZJSQiLyQB9EOo7ckdKKgylgIpAA8AdACtK-IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.4.2

**Comment by brandonweiss** [comment]
@nicolo-ribaudo Thanks!

@loganfsmyth Sorry, I got confused between the difference between the string’s actual contents versus how it looks when it’s logged to the screen, so I didn’t quite faithfully represent it in the example (although the REPL link has it right).

**Comment by nicolo-ribaudo** [comment]
This is a parser bug: https://astexplorer.net/#/gist/a0c801a1a49fabf2c794511d8324dcb1/08cbe325a60bec779bb3b74ceaf18ef7c561b8a4

**Comment by nicolo-ribaudo** [comment]
This is not a bug. In strings, backslashs should be escaped:

```js
import React from "C:\\Users\\travis\\build\\brandonweiss\\charge\\node_modules\\react\\index.js"
```

Otherwise,
```js
import React from "Users\travis"
```
would try to import it from `Users[TAB]ravis`.

You can test it by running this code in the console of any browser, which should give you the representation of what the browser sees in your code (where `\t`, for example, is a tab).
```js
JSON.stringify("C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js")
```

PS. The code you posted should have 4 backslashes, since any `\` needs to become `\\` because it is inside a string, and then `\` needs to become `\\` because it is inside the template literal :stuck_out_tongue: 	
```js
let code = `import React from "C:\\\\Users\\\\travis\\\\build\\\\brandonweiss\\\\charge\\\\node_modules\\\\react\\\\index.js"`;
```

**Comment by brandonweiss** [comment]
@nicolo-ribaudo Thanks so much for digging into this!

Hmm… are you sure? I can’t tell if I’m misunderstanding this or not. It’s possible my representation of the example is causing confusion. I just did `console.log(JSON.stringify(pathVariable))` of the path string (before it goes through Babel) in order to get a visual representation of what the string is, and I got this:

```
"C:\\Users\\travis\\build\\brandonweiss\\charge\\node_modules\\react\\index.js"
```

That looks right to me… does that look right to you? I think that means “internally”, the string is actually:

```
"C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"
```

Right? All the backslashes have been properly escaped to leave just the single actual backslash in the path.

But then when that string goes through Babel some of the backslashes are gone.

I apologize if I’m completely misunderstanding this!

**Comment by brandonweiss** [comment]
I’m definitely losing my mind trying to reason about this 😭😅

OK, I stepped through the code and used `console.log` to output the string variable before and after running it through Babel.

This is what I see before (ignore the React component—I just kept it in so you could see exactly what I was transforming):

```javascript
import React from "C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"
export default ({ pages }) => (
  <React.Fragment>
    {
      pages.map(
        (page) => (
          <p key={page.path}>{page.path}</p>
        )
      )
    }
  </React.Fragment>
)
```

I see all the backslashes and there is only one at each part of the path, which seems correct to me? In order for it to render correctly when logged, the string must have all the backslashes properly escaped, right?

Then I run it through Babel and get this:

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _UsersRavisUildRandonweisschargeOde_modulesEactindex = _interopRequireDefault(require("C:Users\travis\build\brandonweisscharge\node_modules\reactindex.js"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var _default = ({
  pages
}) => _UsersRavisUildRandonweisschargeOde_modulesEactindex.default.createElement(_UsersRavisUildRandonweisschargeOde_modulesEactindex.default.Fragment, null, pages.map(page => _UsersRavisUildRandonweisschargeOde_modulesEactindex.default.createElement("p", {
  key: page.path
}, page.path)));

exports.default = _default;
```

Now it’s not rendering correctly, which seems to indicate that some of the backslashes are no longer escaped correctly. Am I understanding that correctly, or no?

**Comment by nicolo-ribaudo** [comment]
Let's not reason about Babel for a moment.

Try to run this code:
```
require("C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"");
```

You'll see that it throws "module not found", because you need to escape backslashes.

**Comment by brandonweiss** [comment]
@nicolo-ribaudo Right, I get why that example fails. But I’m not hard-coding the path in my code, I just did that in my example to try and simplify it (which I realize now caused some confusion 😭). Sorry about that!

In my code I’m getting the path from `require.resolve("react")`. When I `console.log` the value of that string seems correct to me. Or at least, if it’s not correct, I think that would mean there’s a terribly bad bug in Node on Windows? When I pass that string through Babel transform, that’s when the problem occurs.

**Comment by nicolo-ribaudo** [comment]
> In my code I’m getting the path from require.resolve("react"). When I console.log(require.resolve("react")) the value of that string seems correct to me.

Do you mean something like this?
```js
const input = `import React from "${require.resolve("react")}"`?
```

If so, you need to escape the return value of `require.resolve`:
```js
const input = `import React from ${JSON.stringify(require.resolve("react"))}`?
```

Instead of printing to the console, I suggest writing `input` to a file (before transforming it with Babel) instead of using the console, so that you see the actual backslashes used.

**Comment by brandonweiss** [comment]
Ah shit, I just now understood what I’m doing wrong. I’m so annoyed at myself. 😭

The path string is properly escaped initially. It’s even properly escaped after it’s interpolated into the “code”, which is why if I `console.log` it it visually _looks_ correct.

But the problem is I‘m effectively creating another string in the interpolation, but not escaping it for that string. 😡

I’m sorry I took up so much of your time! Thanks so much for bearing with me and explaining it to me! ❤️
