### ISSUE TITLE
Global level awaits

### ISSUE THREAD

**Issue by ivan-kleshnin** [babel/babel#977]
Is there any notion or plans for such thing? In Node we use `doSomeStuffSync` in global (module) space, where concurrency isn't required and order of commands really matters. 
```javascript
// this is global space
let x = a.doStuffSync();
let y = b.doOtherStuffSync(x);  
```

But global-space `await`s could obsolete those `Sync` -suffixed functions and open the possibility to remove them entirely.

```javascript
// this is global space, no "async" function wrapper
let x = await a.doStuff(); 
let y = await a.doOtherStuff(x); 
```

Of course, if `a.doOtherStuff` accepts promises it may be implemented on usual async versions, but if it's not (most of today's API), we have an option. I'm not sure about technical possibility for this at transpiler level. Just being curious.

**Comment by sebmck** [comment]
This is more a question for the [ecmascript-asyncawait](https://github.com/lukehoban/ecmascript-asyncawait) repo where the spec that Babel follows is actually defined.

**Comment by ivan-kleshnin** [comment]
Yes, you're right.
