### ISSUE TITLE
babel-plugin-proposal-class-properties: Cannot read property of undefined

### ISSUE THREAD

**Issue by gazedash** [babel/babel#9770]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

Exception when accessing `this.property` in class property initializers that was defined in constructor.

https://stackblitz.com/edit/react-tcvkds

**Input Code**
- REPL or Repo link if applicable:

```js
class X {
  constructor() {
    super();
    this.bla = {y: {x:'x'}}
    //  const aaa = this.bla.y.x
  }

  // no error:
  // bla = { y: { x: 5}}
  // error:
  aaa = this.bla.y.x
}
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

No errors, expect behaviour to be the same.

**Environment**
- Babel version(s): 7.1.2
- Node/npm version: 11.7.0/6.5.0
- OS: Mac OS X 10.14.3
- Monorepo: no
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
That error is correct, because fields are initialized right after `super();` (or at the beginning of a constructor, in a base class). That code is the equivalent of this:
```js
super();
this.aaa = this.bla.y.x
this.bla = {y: {x:'x'}}
```
