### ISSUE TITLE
How I can specify auto generated tsconfig, for transformation, using babel-cli?

### ISSUE THREAD

**Issue by lifeart** [babel/babel#9771]
Given:
few projects, with different typescript configuration.
ast-analyzer tool, trying to get ast data from this projects.

Problem:
Can't specify custom tsconfig location or inject it inline to babelOptions

Question:
How I can do it?

**Comment by nicolo-ribaudo** [comment]
Babel doesn't load tsconfig.json, since most of the options it has (except experimentalDecorators) don't make sense for Babel.
