### ISSUE TITLE
How to push an object to the body of BlockStatement

### ISSUE THREAD

**Issue by aermin** [babel/babel#9772]
The scenario：

I want to push an object into the body of this BlockStatement.

![image](https://user-images.githubusercontent.com/24861316/55008945-c2dbc580-501c-11e9-84ff-4b9a038b3d6b.png)

This code as follow:

```js
  const addCommentVisitor = {
    BlockStatement(path) {
      path.node.body.push({
        type: 'ExpressionStatement',
        trailingComments: [
          {
            type: 'CommentBlock',
            value: 'this is a comment',
          }
        ]
      });
    }
  };
```

But when I run this code, it will throw an error as follow:

![image](https://user-images.githubusercontent.com/24861316/55009419-780e7d80-501d-11e9-9988-142c4e9b14ab.png)

If I change the code as follow, it can fix the error and work well.

code path: @babel/generator/lib/node/index.js

```diff
function find(obj, node, parent, printStack) {
-  const fn = obj[node.type];
+  const fn = obj[node && node.type];
  return fn ? fn(node, parent, printStack) : null;
}
```

So, could I make a  pull request to fix it like that? Or If It isn't a bug, please tell me what I should do if I want to push an object to the body of BlockStatement.

Thank you very much!

**Comment by loganfsmyth** [comment]
You are pushing an invalid `ExpressionStatement` node. They require an `expression` child node for the actual expression itself.

**Comment by aermin** [comment]
> You are pushing an invalid `ExpressionStatement` node. They require an `expression` child node for the actual expression itself.

Got it. 
Thanks!
