### ISSUE TITLE
babel-core doesn't list which plugins/presets are duplicated

### ISSUE THREAD

**Issue by worc** [babel/babel#9778]
## Bug Report

**Current Behavior**
babel-core doesn't list which plugins/presets are duplicated:

```
   Duplicate plugin/preset detected.
    If you'd like to use two separate instances of a plugin,
    they need separate names, e.g.

      plugins: [
        ['some-plugin', {}],
        ['some-plugin', {}, 'some unique name'],
      ]

      at assertNoDuplicates (node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at alias (node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
      at cachedFunction (node_modules/@babel/core/lib/config/caching.js:33:19)
      at plugins.plugins (node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
      at mergeChainOpts (node_modules/@babel/core/lib/config/config-chain.js:319:26)
      at node_modules/@babel/core/lib/config/config-chain.js:283:7
      at buildRootChain (node_modules/@babel/core/lib/config/config-chain.js:68:29)
      at loadPrivatePartialConfig (node_modules/@babel/core/lib/config/partial.js:85:55)
```

**Expected behavior/code**
A list of duplicate plugins/presets so that you know which ones to remove or rename.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
  "babel": {
    "plugins": [
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-transform-runtime",
      "babel-plugin-istanbul",
      "babel-plugin-styled-components",
      "syntax-export-extensions"
    ],
    "presets": [
      ["@babel/preset-env", {
        "debug": true
      }],
      ["@babel/preset-react", { "debug":  true }]
    ]
  },
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: Node 10/npm 6
- OS: macOS 10.14.3

**Comment by luminous3** [comment]
Any updates on this? 

I keep getting this error and don't know which plugins/presets are duplicated or how to fix it.

**Comment by nicolo-ribaudo** [comment]
Not yet, but if you join our slack channel and share your config we can try fixing it together.

https://slack.babeljs.io/

**Comment by luminous3** [comment]
@nicolo-ribaudo Thanks Nicolo! I just signed up. Is there a specific channel I should join?

**Comment by nicolo-ribaudo** [comment]
You can ask on #discussion

**Comment by jjwallace** [comment]
I get this same error

`"devDependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/node": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "css-loader": "^2.1.1",
    "npm-run-all": "^4.1.5",
    "react": "^16.8.6",
    "react-app-rewire-mobx": "^1.0.9",
    "react-dom": "^16.8.6",
    "react-flip-move": "^3.0.3",
    "react-hot-loader": "^3.1.3",
    "react-router-dom": "^4.2.2",
    "react-tap-event-plugin": "^3.0.2",
    "socket.io": "^2.0.4",
    "style-loader": "^0.23.1",
    "styled-components": "^3.1.6",
    "webpack": "^4.33.0",
    "webpack-cli": "^3.3.3",
    "webpack-dev-server": "^2.11.1"
  },
  "dependencies": {
    "mobx": "^5.9.4",
    "mobx-react": "^5.4.4",
    "mobx-react-devtools": "^6.0.1",
    "node-persist": "^3.0.4",
    "nodemon": "^1.19.1",
    "react-autosuggest": "^9.4.3",
    "react-motion": "^0.5.2",
    "react-simple-maps": "^0.12.1",
    "run-all": "^1.0.1",
    "save": "^2.4.0",
    "sentencer": "^0.2.0",
    "three": "^0.104.0",
    "three-full": "^17.1.0",
    "threejs-full-es6": "^5.1.0"
  },`

**Comment by luminous3** [comment]
I was able to get rid of the error by doing something like this:

`{
	"presets": [
    ["@babel/preset-env", {}],
    ["@babel/preset-typescript", {}, "typescript"]
	],
	"plugins": [
			["@babel/proposal-class-properties", {}],
			["@babel/proposal-object-rest-spread", {}, "object-rest-spread"]
	]
}`



As far as I can tell, there haven't been any other errors from doing this and my app works like before. It doesn't solve the root of the problem, but at least it lets you run your application.

**Comment by nicolo-ribaudo** [comment]
You should probably exclude the object rest-spread plugin from `@babel/preset-env`

**Comment by luminous3** [comment]
That actually fixed the error, thanks @nicolo-ribaudo
