### ISSUE TITLE
Inconsistent field assignment for Legacy/Stage 1 Decorators

### ISSUE THREAD

**Issue by pzuraq** [babel/babel#9779]
## Bug Report

**Current Behavior**

Currently, the legacy decorators transform requires the class fields to be configured to `loose` mode. In loose mode, class fields are assigned using _set_ semantics, instead of `Object.defineProperty`. This makes sense - in TS, fields are assigned with _set_ semantics, even when they are decorated - and is referenced frequently in the current discussion about the downsides of stage 1 decorators, and the differences between them and stage 2-3 decorators.

However, it seems that currently, fields which are decorated [actually _are_ set using `Object.defineProperty`](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L982-L991).

**Input Code**
- The REPL currently doesn't seem to support compiling with class fields in loose mode to demonstrate, but [here is the code with them in strict, with the error/warning](https://babeljs.io/repl#?babili=false&browsers=Last%201%20Chrome%20Version&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAEBiD29oG8BQ1oAEAmBTY8ATmAC67QBGYh0AvNAIwBMAzANzTqcZUBedjVm1QBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-1%2Cenv&prettier=true&targets=Node-8.9&version=7.4.2)

```js
class Foo {
  @decorate bar = 123; 
  
  baz = 123;
}
```

**Expected behavior/code**

Class field assignment should always be consistent. Both decorated and undecorated fields should be defined using `Object.defineProperty`, or _set_.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { legacy: true }],
    ["@babel/plugin-proposal-class-properties", { loose: true }]
  ]
}
```

**Environment**
- Babel version(s): v7.4.2
- Node/npm version: Node 8/npm 5
- OS: OSX 10.14.3
- Monorepo: N/A
- How you are using Babel: `ember-cli-babel`

**Possible Solution**

One possible solution would be to change the decorators transform to assign values using _set_, but that seems like it could be a breaking change. Alternatively, we could remove the restriction requiring `loose` mode for class properties, and have them be assigned with `Object.defineProperty` in a spec compliant way. Then it will be consistent. 

Also, apologies if I'm missing anything nuanced here, and this behavior is required for other reasons 😅

cc @nicolo-ribaudo, was told you'd be interested in this

**Comment by nicolo-ribaudo** [comment]
> One possible solution would be to change the decorators transform to assign values using set, but that seems like it could be a breaking change. Alternatively, we could remove the restriction requiring loose mode for class properties, and have them be assigned with Object.defineProperty in a spec compliant way.

Since "legacy" decorators are currently the version recommended by TC39, I'd like to do both things:
1) Add a `loose` mode to decorators which uses [[Set]] instead of [[Define]]: this would be consistent with class fields and probably more compatible with TypeScript
2) Make legacy decorators compatible with non-loose class fields.

This wouldn't be a breaking change, since the only currently valid config (loose fields/spec decorators) will still behave the same.

**Comment by pzuraq** [comment]
I like that approach! It makes sure we aren’t breaking apps, and it keeps things flexible 😄 

I would say “loose” mode decorators would be _most_ useful if we could add initializers to accessors as well. The use case is, you want to create a getter/setter that intercepts a value and sets it internally on a symbolic property on the instance, and you want to ensure that property is assigned an initial value during construction, so the object is properly shaped. I believe at one point the transform would throw and error if you attempted to have an initializer and accessor on the same decorated descriptor, unsure if that’s still true.

**Comment by jhpratt** [comment]
Running into this same issue. I'm using the same Babel config as @pzuraq (plus some other irrelevant things). _My_ code doesn't behave any differently with define/set, but I noticed it as I was wondering why files were noticeably larger than expected. I wouldn't be surprised if others are unknowingly relying on this (incorrect) behavior, so adding an extra option as @nicolo-ribaudo  suggested is probably for the best.

I highly doubt there's some workaround? Where would I go about looking to potentially fix this?

**Comment by endel** [comment]
I'm having the same problem using [@colyseus/schema](https://github.com/colyseus/schema) + Babel. The lib doesn't work using Babel, only plain TypeScript, I'm wondering what can I do to make it compatible with Babel.

I believe it's related to the `initializerDefineProperty_default` calls from Babel, not really sure.

**Comment by pzuraq** [comment]
@nicolo-ribaudo would you be interested in a PR to fix this? I can probably get one done soon-ish, if I could get a pointer to how the current class fields transform manages to replace the [`initializerWarningHelper`](https://github.com/babel/babel/blob/ba2c0f7adf58dfb9de6a152d858c418f374c6194/packages/babel-plugin-proposal-decorators/src/transformer-legacy.js#L154) when in `loose` mode
