### ISSUE TITLE
Simple Browser Test Fails in Firefox 29.0

### ISSUE THREAD

**Issue by j03m** [babel/babel#978]
Getting an error:  
TypeError: obj[Symbol.iterator] is not a function
http://localhost:8000/compile.o.js
Line 15

When trying to compile a pretty a simile demo script and run an older version of firefox. Steps to replicate:

* install
```
> npm install -g babel 
> cp /usr/local/lib/node_modules/babel/browser-polyfill.js browser-polyfill.js
```
* create compile.me.js
```javascript
var isOdd = number => number % 2 === 1;

function forOf(){
    var obj = {a:1, b:2, c:3};

    for (var prop of obj){
        console.log(prop);
    }
}
```
* compile
```
> babel compile.me.js  > compile.o.js
```
* Create basic html harness:
```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script type="text/javascript" src="browser-polyfill.js"></script>
    <script type="text/javascript" src="compile.o.js"></script>
    <script type="text/javascript">
        forOf();
    </script>
</head>
<body>

</body>
</html>
```
* Python to serve
```
> python -m SimpleHTTPServer
```

Run in Firefox 29.0, open console.
![screen shot 2015-03-09 at 8 20 22 am](https://cloud.githubusercontent.com/assets/697639/6554724/32132c0c-c635-11e4-9055-943bb7465a15.png)

**Comment by sebmck** [comment]
This is expected behaviour. Objects have no iterators so you can't `for...of` over them.
