### ISSUE TITLE
"ignore" option not working in .babelrc or package.json

### ISSUE THREAD

**Issue by chase-moskal** [babel/babel#9782]
## Bug Report

**Current Behavior**  
`ignore` option doesn't work in `.babelrc`  
also doesn't work in `package.json` "babel" field  
***as a workaround, i found using multiple `--ignore` options is working***

**Input Code**  
[Repro repo: babel-broken](https://github.com/chase-moskal/babel-broken)

**Expected behavior/code**  
`ignore` option in `.babelrc` should cause babel to ignore things

**Babel Configuration (.babelrc, package.json, cli command)**  
```json
{
	"ignore": [
		"dist",
		"ignore-this",
		"node_modules"
	]
}
```

**Environment**
- Babel version(s): v7.4.0 (cli 7.2.3)
- Node/npm version: node 10
- OS: xubuntu
- Monorepo: no
- How you are using Babel: cli

----

let me know if i've just made a simple mistake, because this seems like pretty basic functionality that i'd be surprised to find is actually broken in babel.. but maybe..

related to #9740, pinging @rico345100, @loganfsmyth

**Comment by nicolo-ribaudo** [comment]
I'm not sure about `dist` and `ignore-this`, but `node_modules` isn't ignored because `.babelrc` and `package.json` are only loaded for files in the same package, not for nested packages (`node_modules/foo`).
If you want your config to be applied to the whole project, you need to use `babel.config.js`.

**Comment by chase-moskal** [comment]
### indeed the solution is to use `babel.config.js`, not `.babelrc`

commit 872d492 demonstrates how i fixed my example repo
