### ISSUE TITLE
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by KoushikVanama** [babel/babel#9783]
## Bug Report

**Current Behavior**
Trying to use babel with webpack in my react application

**Error**
![image](https://user-images.githubusercontent.com/24358668/55144891-b7e17c00-5167-11e9-8d68-2d8550a89712.png)

**package.json**
![image](https://user-images.githubusercontent.com/24358668/55145298-7f8e6d80-5168-11e9-96ce-21e68dfa9334.png)

**webpack.config.js**
![image](https://user-images.githubusercontent.com/24358668/55145122-29212f00-5168-11e9-910b-eab9bb0e6deb.png)

**Expected behavior/code**
@babel/core ^7.x should work with babel-loader ^8.x

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: Node 10.5.0/npm 6.1.0
- OS: Windows 10
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
Is it there in your `node_modules` folder? If not, try deleting it and running `npm i` again.
Also, you need to update babel-cli to v7.

**Comment by KoushikVanama** [comment]
Added "@babel/cli": "^7.2.3", and re-installed node packages. That doesn't work. Still facing the same issue.

**Comment by liuxingbaoyu** [comment]
Because this issue is out of date, I will close it.
