### ISSUE TITLE
babel-polyfill not work when "modules": false

### ISSUE THREAD

**Issue by hketkennethlung** [babel/babel#9784]
## Bug Report

**Current Behavior**
I have a React component library with `.babelrc` as below
```
{
    "presets": [
        ["@babel/preset-env", { "modules": false }],
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-export-default-from",
        ["import-rename", { "^(.*)\\.jsx$": "$1.js" }],
        "@babel/plugin-syntax-dynamic-import",
        ["react-docgen"],
        ["@babel/plugin-transform-runtime", { "useESModules": true }]
    ]
}

```
and I have a React website project using the React component library with `.babelrc` as below
```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false,
                "useBuiltIns": "usage"
            }
        ],
        ["@babel/preset-react"]
    ],
    "plugins": ["@babel/plugin-proposal-class-properties"]
}

```
I found that some web pages crash and the console throw error `'Promise' is undefined` on IE 11. After I remove the config `"modules": false`, the web pages work fine.

Why `babel-polyfill` not work when setting `"modules": false`, is it a bug or just wrong configuration?
How can make `babel-polyfill` work if I want to keep using `"modules": false`?

I found a similar question https://stackoverflow.com/questions/45035841/babel-promise-polyfill-not-working-with-webpack-modules-false but I cannot find any answer. Thanks for helping.

**Expected behavior/code**
Promise works on IE 11.

**Environment**
- Babel version(s): `babel-polyfill` v7.2.5, `preset-env` v7.3.4
- Node/npm version: 9.11.1/5.6.0
- OS: Windows 8
- How you are using Babel: `cli` for component library, `loader` for website project

**Comment by nicolo-ribaudo** [comment]
Does the output generated by webpack include `"@babel/polyfill"`?

**Comment by yaelballa** [comment]
I have a similar issue, and yes, I'm importing the "@babel/polyfill" in the code

**Comment by nicolo-ribaudo** [comment]
`@babel/polyfill` has now been deprecated. You can use `core-js` directly, or a different polyfill.
