### ISSUE TITLE
Object prototype functions break functionality

### ISSUE THREAD

**Issue by ekkis** [babel/babel#9786]
## Bug Report

This is related to https://github.com/babel/babel/pull/9518 and stems from the presence of Object prototypes at the time this module runs.

as an example, define:
```js
Object.prototype._test_function = () => null
```
and then attempt to load the module

**Current Behavior**

Here's the stack trace produced

> /Users/ekkis/dev/tst/node_modules/babel-traverse/lib/visitors.js:205
>           throw new Error(messages.get("traverseVerifyVisitorProperty", nodeType, visitorKey));
>           ^   
> 
> Error: You passed `traverse()` a visitor object with the property "Block" that has the invalid property "_test_function"
>     at verify (/Users/ekkis/dev/tst/node_modules/babel-traverse/lib/visitors.js:205:17)
>     at Function.explode (/Users/ekkis/dev/tst/node_modules/babel-traverse/lib/visitors.js:72:3)  
>     at Plugin.normaliseVisitor (/Users/ekkis/dev/tst/node_modules/babel-core/lib/transformation/plugin.js:155:29)
>     at new Plugin (/Users/ekkis/dev/tst/node_modules/babel-core/lib/transformation/plugin.js:66:27) 
>     at Object.<anonymous> (/Users/ekkis/dev/tst/node_modules/babel-core/lib/transformation/internal-plugins/block-hoist.js:15:19)
>     at Module._compile (internal/modules/cjs/loader.js:721:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:657:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/Users/ekkis/dev/tst/node_modules/babel-core/lib/transformation/file/index.js:96:19)
>     at Module._compile (internal/modules/cjs/loader.js:721:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
> 
**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: 11.5.0
- OS: OSX 10.14.3
- Monorepo: ?
- How you are using Babel: [loader]

**Possible Solution**
The code breaks because it is not properly checking `.hasOwnProperty()` for object keys.

I've identified a few places where this needs fixing and am providing a patch that can be applied to 6.26.0 below and am happy to produce a PR if it has any change of getting merged

here's the patch for it:
```
diff --git a/node_modules/babel-traverse/lib/visitors.js b/node_modules/babel-traverse/lib/visitors.js
index dadf5d0..708d825 100644
--- a/node_modules/babel-traverse/lib/visitors.js
+++ b/node_modules/babel-traverse/lib/visitors.js
@@ -131,12 +131,18 @@ function explode(visitor) {
 
   for (var _nodeType in visitor) {
     if (shouldIgnoreKey(_nodeType)) continue;
+    if (!visitor.hasOwnProperty(_nodeType)) continue;
 
     var _fns = visitor[_nodeType];
 
-    var aliases = t.FLIPPED_ALIAS_KEYS[_nodeType];
+    var aliases = t.FLIPPED_ALIAS_KEYS.hasOwnProperty(_nodeType)
+		? t.FLIPPED_ALIAS_KEYS[_nodeType]
+		: null;
+
+    var deprecratedKey = t.DEPRECATED_KEYS.hasOwnProperty(_nodeType)
+		? t.DEPRECATED_KEYS[_nodeType]
+		: null;
 
-    var deprecratedKey = t.DEPRECATED_KEYS[_nodeType];
     if (deprecratedKey) {
       console.trace("Visitor defined for " + _nodeType + " but it has been renamed to " + deprecratedKey);
       aliases = [deprecratedKey];
@@ -199,6 +205,7 @@ function verify(visitor) {
     var visitors = visitor[nodeType];
     if ((typeof visitors === "undefined" ? "undefined" : (0, _typeof3.default)(visitors)) === "object") {
       for (var visitorKey in visitors) {
+        if (!visitors.hasOwnProperty(visitorKey)) continue;
         if (visitorKey === "enter" || visitorKey === "exit") {
           validateVisitorMethods(nodeType + "." + visitorKey, visitors[visitorKey]);
         } else {
```

**Comment by nicolo-ribaudo** [comment]
Babel 6 isn't maintained anymore, if you need #9518 you must upgrade to Babel ^7.4.0

**Comment by ekkis** [comment]
> Babel 6 isn't maintained anymore, if you need #9518 you must upgrade to Babel ^7.4.0.

ah.  it's someone else's package that has the dependency and they're pulling in 6.26.0 -- I'll get them to upgrade.  thanks!

> As a workaround...

fascinating! thank you.  I didn't realise one could create functions like that!
