### ISSUE TITLE
Version 7.4.2 is slower than 7.2.3

### ISSUE THREAD

**Issue by kirill-konshin** [babel/babel#9789]
## Bug Report

**Current Behavior**

I have a project with roughly 6000 modules. After upgrade from 7.2.3 to 7.4.2 I have consistent slow down by ~20 seconds.

I am using Webpack 4 and it stucks on `79% chunk modules optimization ModuleConcatenationPlugin`.

It might be not the Babel, but that plugin issue.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = (modules) => ({
    presets: [
        ['@babel/preset-env', {
            targets: {
                browsers: browserList,
            },
            loose: true,
            modules: modules,
            useBuiltIns: 'entry',
            exclude: ['transform-regenerator', 'transform-async-to-generator'],
        }],
        '@babel/preset-react',
    ],
    plugins: [
        ['module:fast-async', {
            spec: true,
            useRuntimeModule: true,
        }],
        ['@babel/plugin-transform-runtime', {
            regenerator: false,
            useESModules: false,
        }],
        ['@babel/plugin-proposal-decorators', {
            legacy: true,
        }],
        '@babel/plugin-proposal-export-namespace-from',
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-syntax-dynamic-import',
    ],
    env: {
        test: {},
        production: {
            plugins: ['transform-react-remove-prop-types'],
        },
        build: {
            ignore: ['/**/*.spec.js', '/**/*.test.js', '/**/*-test.js', '/__tests__/'],
        },
    },
});
```

With 7.4.2 the upper section has additional `corejs: 2` option.

**Comment by kirill-konshin** [comment]
In our setup we use Jest and Webpack, so we need env preset with `modules:cjs` for Jest (it does not work otherwise) and `modules:false` for Webpack to enable tree-shaking.

So we have `.babelrc.js` with `modules:cjs` and the `.babelrc.ES6.js` with `modules:false` which is used in `babel-loader`:

```js
{
  loader: require.resolve('babel-loader'),
  options: {
    extends: require.resolve('./.babelrc.ES6'),
    cacheDirectory: true
  }
}
```

During Webpack build both configs are imported in the following order (version does not affect order):

1. `.babelrc.ES6.js`
2. `.babelrc.js`

**⚠️⚠️⚠️ Now the main thing: it seems that `7.4.x` version produces final config with `false` whereas `7.2.x` — with `cjs`.**

If I add `babelrc: false` to loader config only the one that is mentioned in `extends` is used and both versions work the same way.

I wonder if such behavior and its changes are documented anywhere?

**Comment by nicolo-ribaudo** [comment]
Thank you for investigating! This change seems like a bug. Do you have a public repo I could look at?

**Comment by kirill-konshin** [comment]
We have a fairly complicated system, I will try to boil it down to some minimal reproducible case and post it as a repo.

**Comment by JLHwung** [comment]
Feel free to reopen this issue if there is reproducible repository.
