### ISSUE TITLE
Couldn't find any versions for "electron-to-chromium" that matches "^1.3.122"

### ISSUE THREAD

**Issue by rsmelo92** [babel/babel#9795]
## Bug Report

**Current Behavior**
Trying to use `@babel/preset-env` but when installing this error shows... It's an internal dependecy of browserfy, I believe 

**Expected behavior/code**
Should install without asking the version of internal dependecy

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "module:metro-react-native-babel-preset",
    [
      "@babel/preset-env",
      {
        "ignoreBrowserslistConfig": true,
        "targets": {
          "node": "current",
        },
      },
    ],
  ],
  "plugins": [
    "relay",
    ["babel-plugin-root-import", {
      "rootPathSuffix": "src/"
    }],
    "@babel/syntax-flow",
    "module:jsx-control-statements"
  ]
}
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: 8
- OS:ubuntu
- Monorepo: no

**Possible Solution**
Edit babel internal dependecies

**Additional context/Screenshots**
with yarn:
![image](https://user-images.githubusercontent.com/16295402/55278497-dec8bb00-52eb-11e9-9236-51ba0bb43721.png)
with NPM
![image](https://user-images.githubusercontent.com/16295402/55278531-39faad80-52ec-11e9-8953-b3738e5538db.png)

**Comment by nicolo-ribaudo** [comment]
That version exists: https://www.npmjs.com/package/electron-to-chromium
It's likely a cache or proxy issue.
