### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/es6.object.create'

### ISSUE THREAD

**Issue by anonyzm** [babel/babel#9796]
Having issues trying to build server side react node js application.

```
ERROR in ./src/external/BaseComponent.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.create' in 'C:\Users\Too\WebstormProjects\react_back\src\external'
 @ ./src/external/BaseComponent.js 4:0-43
 @ ./src/server.js
 @ ./src/index.js
```

Seemed like its something about _core-js_ version. It generates polyfill requires like this: 
```js
require("core-js/modules/es6.symbol");
```
But actually they are so: 
```
core-js/modules/es.symbol.js
```

**npm ls core-js**
```
react_back@1.0.0 C:\Users\Too\WebstormProjects\react_back
+-- @babel/preset-env@7.4.2
| -- core-js-compat@3.0.0
|   -- core-js@3.0.0  deduped
-- core-js@3.0.0
```

**Webpack config**
```js
const path = require('path');
module.exports = {
    entry: './src/index.js',
    mode: 'development',
    output: {
        path: path.resolve(__dirname, 'assets'),
        filename: "[name].js"
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: "babel-loader"
            }
        ]
    },
    target: 'node',
    node: {
        console: true
    },
    externals: ['express'],
};
```

**package.json**
```json
{
  "name": "react_back",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "start": "node src/index.js",
    "pack": "webpack --config webpack.config.babel.js",
    "babel": "babel src -d views",
    "build": "npm run pack && npm run babel"
  },
  "dependencies": {
    "core-js": "^3.0.0",
    "express": "^4.16.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.0",
    "@babel/core": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.2",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2"
  }
}
```

**.babelrc**
```json
{
  "presets": [
    ["@babel/preset-env", {
      "useBuiltIns": "usage",
      "debug": true
    }],
    "@babel/preset-react"
  ]
}
```

Any ideas?

**Comment by nicolo-ribaudo** [comment]
By default Babel injects imports to core-js@2, you need to install that.

**Comment by anonyzm** [comment]
> By default Babel injects imports to core-js@2, you need to install that. Or better, you can update preset-env to ^7.4.0 and enable the `corejs: 3` option of that preset.

Thank you! That helped core-js error, every polyfill is required correctly in compiled files, but now it looks like import polyfill doesn't work. 
Now i have following error:
`C:\Users\Too\WebstormProjects\react_back\src\server.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                                     ^^^^^

SyntaxError: Unexpected identifier`

Edited **package.json:**
`"@babel/preset-env": "^7.4.0",`

And **.babelrc:**
`{
  "presets": [
    ["@babel/preset-env", {
      "useBuiltIns": "usage",
      "debug": true,
      "corejs": 3
    }],
    "@babel/preset-react"
  ]
}`

**Comment by jacobbogers** [comment]
Same issue for me, was there an npm update some days ago, because it started happening to me yesteday

**Comment by nicolo-ribaudo** [comment]
@anonyzm You need to run the compiled files (in `views`), not the original sources (in `src`).

@jacobbogers What is the full stack trace?

**Comment by jacobbogers** [comment]
My `babel.config.js`
````javascript
const presets = [
	['@babel/preset-react'],
	[
		'@babel/env',
		{
			useBuiltIns: 'usage',
			targets: `last 1 version,> 1%,maintained node versions,not dead`
		}
	]
];

const plugins = [
	['@babel/plugin-proposal-class-properties'],
	[
		'babel-plugin-styled-components',
		{
			pure: true
		}
	]
];

module.exports = { presets, plugins };
```

My babel is part of a webpack build, does i generate a stacktract when  i use the options `--verbose`?

**Comment by jacobbogers** [comment]
I have it working after i changes settings to this
```javascript
const presets = [
	['@babel/preset-react'],
	[
		'@babel/env',
		{
			"loose": true,
			"targets": {
			  "browsers": [
				"> 0.1%",
				"last 3 versions",
				"ie 10",
				"ie 11"
			  ]
			}
		 }
	]
];

const plugins = [
	['@babel/plugin-proposal-class-properties'],
	[
		'babel-plugin-styled-components',
		{
			pure: true
		}
	]
];

module.exports = { presets, plugins };
```

**Comment by nicolo-ribaudo** [comment]
That won't load polyfills. Since you where using `useBuiltIns`, did you install `core-js@2`?

**Comment by jacobbogers** [comment]
@nicolo-ribaudo , hi, not sure what you mean, its not supposed to load polyfills unless its not supported by any of the targets nativly,.... but it does try to look for polyfills isnt that what the message is trying to say? `Module not found:`

**Comment by nicolo-ribaudo** [comment]
`useBuiltIns` generates in your code imports to polyfills from `core-js`, but you need to install it.

**Comment by milesj** [comment]
Have you all read the core-js + babel migration guide? https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

**Comment by jacobbogers** [comment]
@nicolo-ribaudo thanks for explaining, the babel site is not very clear me thinks on this issue.
 
@milesj  first time to use babel so extensivly (normal i use typescript and configure the targets there. I.E es2015 or whatever). Will reading  your link give me all the answer with regard to my problem?

**Comment by nicolo-ribaudo** [comment]
Is this still an issue?
