### ISSUE TITLE
TypeScript const assertions raise error in babel

### ISSUE THREAD

**Issue by ssynix** [babel/babel#9800]
## Bug Report

**Current Behavior**
Some [const assertions](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#const-assertions) result in errors. Seems like the check introduced in [this PR](https://github.com/babel/babel/pull/9534/files#diff-be80f98b2faf4a89409f44cabdf86e5dR357) is too strict? Because I didn't see any errors in VSCode till I started webpack dev server.

**Input Code**

```js
function foo() {
  const a = getObjectAWithLongAssType();
  const b = getObjectBWithLongAssType();

  return [a, b] as const; // no errors in tsc or vscode
  // Previously: return [a,b] as [typeof a, typeof b]
}
```

**Expected behavior/code**
VSCode outputs the expected readonly tuple type, so I don't expect any errors in babel.

**Babel Configuration (.babelrc, package.json, cli command)**

```
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/polyfill": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.3.3",
```

**Possible Solution**

@tanhauhau is there a need for `tsCheckLiteralForConstantContext` to happen in babel? To me it seems like it's enough to parse `as const` expressions as assertions and move on, since TypeScript is actually in charge of ensuring the assertions are valid.

**Comment by tanhauhau** [comment]
hmm.. @nicolo-ribaudo need your advice

**Comment by nicolo-ribaudo** [comment]
Ok, I downloaded TS 3.4 and apparentely we only need to check the top-level node.

e.g. This isn't valid:
```js
(a ? 0 : 1) as const;
```
but this is:
```js
[a ? 0 : 1] as const;
```

**Comment by ssynix** [comment]
These are also valid:
```typescript
const obj = {
  readonly: [1, 'foo'] as const,
  array: [1, 'foo']
};

const array = [1, 'foo', [1, 'foo'] as const] as const;
```
From the announcement:
> * no literal types in that expression should be widened (e.g. no going from "hello" to string)
> * object literals get readonly properties
> * array literals become readonly tuples

It doesn't seem to put any constraints on the members of those array/object literals, or that `as const` can only be applied to the top-level.
___
Does babel typically try to validate types, or simply parse them? To me `(a ? 0 : 1) as const` is syntactically valid TypeScript, although it's not semantically correct in this specific version of TypeScript. I don't expect any errors from babel for the same reason I don't see babel errors when I write: `'foo' as number`.

**Comment by nicolo-ribaudo** [comment]
> To me `(a ? 0 : 1)` as const is syntactically valid TypeScript, although it's not semantically correct in this specific version of TypeScript.

I don't think so. If it wasn't syntax-related, those two snippets would be equivalent:
```ts
const foo = [1, 2, 3] as const;
```
```ts
const _tmp = [1, 2, 3] as const;
const foo = _tmp as const;
```
But the first is valid; the second isn't. What the "argument" to as-const is syntax-related, not type related.

**Comment by ssynix** [comment]
The syntax is valid TypeScript, except that it contains typing errors. It's feasible to imagine a TypeScript version that will add support for `(a ? 0 : 1) as const` (i.e. `0 | 1`), or for your example. 

Same with `'foo' as number`: we can easily determine at parse time that it's a semantic error, but Babel will happily parse it (as it should!).

We don't want to duplicate the type-checker's work in the Babel parser itself, since the TypeScript compiler is already in charge of that. Babel should emit code as if the types don't exist, and using an incorrect typing assertion should not get in the way of that.
___
That's my 2 cents based on the limited knowledge I have of the internals of babel, so definitely take it with a grain of salt! The main issue here is that valid const assertions are being rejected by babel in a few cases.

**Comment by DanielRosenwasser** [comment]
Yeah, `as const` should be very permissive in the syntax which it parses. None of the semantic restrictions should be applied to Babel if it's just going to get erased anyway.

**Comment by tanhauhau** [comment]
sorry for the late MR 😅

**Comment by foisonocean** [comment]
Could someone update the version of `@babel/preset-typescript` so I can use the `as const` syntax in my project?

**Comment by ahem** [comment]
It is great that this is merged, but is there a timeline for when it will also be released?

**Comment by clentfort** [comment]
The fix has been released in @babel/parser 7.4.4. 13 days ago. https://www.npmjs.com/package/@babel/parser/v/7.4.4

**Comment by anyexinglu** [comment]
> Could someone update the version of `@babel/preset-typescript` so I can use the `as const` syntax in my project?

I've upgrade the @babe/parser to v7.4.4, but it has not been solved.

usage:

![image](https://user-images.githubusercontent.com/8243326/59401322-e832d100-8dcc-11e9-9157-084da9bbab15.png)

yarn.lock
```
"@babel/preset-typescript@^7.3.3":
  version "7.3.3"
  resolved "http://bnpm.corp.yiran.com/@babel%2fpreset-typescript/-/preset-typescript-7.3.3.tgz#88669911053fa16b2b276ea2ede2ca603b3f307a"
  integrity sha1-iGaZEQU/oWsrJ26i7eLKYDs/MHo=
  dependencies:
    "@babel/helper-plugin-utils" "^7.0.0"
    "@babel/plugin-transform-typescript" "^7.3.2"

"@babel/plugin-transform-typescript@^7.3.2":
  version "7.4.5"
  resolved "http://bnpm.corp.yiran.com/@babel%2fplugin-transform-typescript/-/plugin-transform-typescript-7.4.5.tgz#ab3351ba35307b79981993536c93ff8be050ba28"
  integrity sha1-qzNRujUwe3mYGZNTbJP/i+BQuig=
  dependencies:
    "@babel/helper-plugin-utils" "^7.0.0"
    "@babel/plugin-syntax-typescript" "^7.2.0"

"@babel/parser@^7.1.0", "@babel/parser@^7.4.3", "@babel/parser@^7.4.4", "@babel/parser@^7.4.5":
  version "7.4.5"
  resolved "http://bnpm.corp.yiran.com/@babel%2fparser/-/parser-7.4.5.tgz#04af8d5d5a2b044a2a1bffacc1e5e6673544e872"
  integrity sha1-BK+NXVorBEoqG/+sweXmZzVE6HI=
```

@babel/preset-typescript and @babel/plugin-transform-typescript are the latest version, something to do with them?

cc @foisonocean

**Comment by 0xorial** [comment]
Should the following work?
```
export const newData = {
  clientNumber: '082224',
} as const;
```
Because I am getting an error - Unexpected token.

**Comment by 0xorial** [comment]
Should following work?
```
export const newData = {
  clientNumber: '082224',
} as const;
```
Because I am getting unexpected token error with @babel/parser@7.5.5

**Comment by tanhauhau** [comment]
@0xorial yes [repl](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM72cA7gEQIYx5wC8cA3gFByIA2AlsMjAHICuAtgEbBQBccAcgAMADgBMEgCwCANBQC-cPKkQp0AbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.5.5)
