### ISSUE TITLE
directory compile has not working on windows

### ISSUE THREAD

**Issue by wh1tecat-nya** [babel/babel#9803]
## Bug Report

**Current Behavior**
i'm developing typescript project on mac/windows.
this issued happened by after switch to windows.

run `yarn(npx) babel src -d(--out-dir) dist  --extensions '.ts'` but no compiled file and shown message "Successfully compiled 0 files with Babel."
then i'm tried some change options(input: single file/directory, output: single file/directory, extensions flag)  And I understood some things.

input → ,↓output|single file|directory
-|-|-
no options|shown compiled source code| no message on cli
file path(-o flag)|compilation result is output normally. (if directory path does not exist, shown error message.)|create -o arg file. but this is empty
directory(-d flag)|no error but not create file(this issue)|same to left

**Input Code**
+ i'm using convert sample code for this.
```ts
const array: Array<number> = [0, 1, 2, 3, 4];

array.map((n: number) => {
    console.log(n);
});
```

**Expected behavior/code**
Compile all .ts files correctly and output .js files. (do the same thing as mac.)

**Babel Configuration (.babelrc, package.json, cli command)**
+ .babelrc

```js
{
  "comments": true,
  "presets": [
    "@babel/preset-typescript",
    [
      "@babel/env",
      {
        "targets": {
          "node": "8",
          "browsers": ["last 2 versions"]
        },
        "exclude": ["transform-regenerator"]
      }
    ]
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```
+ package.json(i need hide some info. sorry)
```js
{
  "name": "*****",
  "version": "1.0.0",
  "author": "wh1tecat",
  "license": "MIT",
  "main": "dist/index.js",
  "scripts": {
    "build": "rimraf dist && npm run build:tsc && npm run build:babel",
    "build:tsc": "yarn tsc",
    "build:babel": "yarn babel ./src --out-dir ./dist --extensions '.ts,.tsx' --config-file ./.babelrc",
    "lint": "yarn eslint --config ./.eslintrc.js --cache src --ext .tsx,.ts",
    "test": "exit 1"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.3.3",
    "@typescript-eslint/parser": "^1.5.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.15.3",
    "eslint-config-prettier": "^4.1.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-mocha": "^5.3.0",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-typescript": "^0.14.0",
    "mocha": "^6.0.2",
    "prettier": "^1.16.4",
    "rimraf": "^2.6.3",
    "typescript": "^3.3.4"
  }
}
```

**Environment**
- Babel version(s): [cli: 7.2.3, core: 7.4.0]
- Node/npm version: [node 11.13.0]
- OS: [Windows 10]
- Monorepo: [no]
- How you are using Babel: [cli]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by taogilaaa** [comment]
I also encounter this, using similar setup after switching from mac to windows. 

I tried
```
babel src --out-dir lib --extensions .ts,.tsx
```

without the `'` on the `.ts,.tsx`, it kinda works for me

**Comment by ghobashy** [comment]
@taogilaaa , save few hours of my time, thanks!

**Comment by wh1tecat-nya** [comment]
i'm sorry, forgot this issue...
this problem reason is same of @taogilaaa answer.
thanks for help and i hoped same problemed someone got this answer.
closed this issue. thank you.
