### ISSUE TITLE
Can I prevent babel from converting Chinese characters to unicode encoding?

### ISSUE THREAD

**Issue by 951565664** [babel/babel#9804]
## Bug Report or Question

**Current Behavior**
Babel escaping Chinese characters into unicode characters

Babel escaping Chinese characters into unicode characters, then in Windows 7, When parsing js to render the page ,  unicode turns into Chinese string will cause problems.as the picture shows. As far as I know this is a common bug in window7.So I think if babel doesn't convert Chinese strings to unicode, maybe this problem won't happen.

In window7：
![image](https://user-images.githubusercontent.com/22285404/55324371-6f51f780-54b4-11e9-93d3-155a3c081cd6.png)

In window10：
![image](https://user-images.githubusercontent.com/22285404/55324867-e9cf4700-54b5-11e9-9d80-8e28a73d5c9a.png)

I found the same problem in stackoverflow, But this problem has not been solved
https://stackoverflow.com/questions/49338158/can-i-prevent-babel-preset-es2015-from-encode-unicode-characters-in-template-lit

**Comment by nicolo-ribaudo** [comment]
You can add this option to your config:
```js
  generatorOpts: {
    jsescOption: {
      minimal: true,
    },
  },
```
