### ISSUE TITLE
Number not a function

### ISSUE THREAD

**Issue by ifrim** [babel/babel#981]
Hi,

This code: 

    Number('23') 

fails with babelify that includes the runtime.
The error is 'object is not a function'. 

This code is transpiled to

    _core.Number('23')

which apparently is not a function, just a regular object.

    console.log(Number instanceof Function); // false

browserify version: 8.1.1
babelify version: 5.0.4
babel-runtime: 4.7.3

    > browserify .\babel-test.js -t [babelify --optional runtime] -o babel-test-bundle.js
    > browserify .\babel-test.js -t babelify -o babel-test-bundle.js

The bundle from the first command has problems when run in the browser, the bundle from the second command works just fine.

babel-test.js only contains the specified code.

**Comment by sebmck** [comment]
@zloirock `Number` needs to be added to `core-js/library`.

**Comment by sebmck** [comment]
Fixed as of 4.7.4, thanks!

**Comment by zloirock** [comment]
@sebmck not sure. Some features can't be added to `core-js/library` because of possible conflicts, for example:
```js
var core = require('core-js/library');
Number === core.Number; // => fasle
Number.prototype === core.Number.prototype; // => true
core.Number.prototype.constructor === Number; // ???
core.Number.prototype.constructor === core.Number; // ???
```

**Comment by sebmck** [comment]
Ah right.
