### ISSUE TITLE
Typescript transformer option

### ISSUE THREAD

**Issue by andykais** [babel/babel#9813]
## Feature Request

This feature request depends on the following question:
Are typescript transformers usable by babel?

If they are not, then this Feature request is mute, and it can be closed.

**Is your feature request related to a problem? Please describe.**
I want to use [typescript-is](https://github.com/woutervh-/typescript-is) in my typescript project to compile runtime typechecking. However, it requires using a typescript transformer, which is not supported by babel.

**Describe the solution you'd like**
If babel plugin-typescript allowed a custom typescript transformers option (similar to the [ttypescript](https://github.com/cevek/ttypescript) project, then this intermediate step could be removed.

**Describe alternatives you've considered**
Currently, to use runtime types, I have to compile the runtime types before the rest of build (which uses `webpack` `babel-loader` & `@babel/preset-typescript`) and version the files into my project since I cannot replace-in-place with webpack. See my [package.json scripts.build](https://github.com/andykais/scrape-pages/blob/master/package.json#L13) for the implementation.

**Teachability, Documentation, Adoption, Migration Strategy**
```json
{
  "presets": [
    [
      "@babel/typescript",
      {
        "transformers": ["typescript-is/lib/transform-inline/transformer"]
      }
    ]
  ]
}
```

**Comment by nicolo-ribaudo** [comment]
Unfortunatly Babel's AST and TypeScript's AST are totally incompatible. You need to rewrite that transformer as a Babel plugin.
