### ISSUE TITLE
The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean

### ISSUE THREAD

**Issue by xgAnd** [babel/babel#9816]
![B833C236-F967-492F-997E-6E8C0ADBFCB3](https://user-images.githubusercontent.com/27660602/55471850-414bef00-563d-11e9-8a88-1c3096a87a0f.png)
"react": "16.8.3",
"react-native": "0.59.2"
"mobx": "^5.9.4",
"mobx-react": "^5.4.3",
the issues is when i want to use Mobx decorator i get the error please help to resolvt it thanks
![7C579E2C-84DF-43C7-8072-6CAAD13D6EF6](https://user-images.githubusercontent.com/27660602/55471755-0a75d900-563d-11e9-8e1f-37fc671e5414.png)

![BC984C79-6087-486D-BAC1-8C3B2AB68C32](https://user-images.githubusercontent.com/27660602/55471701-ec0fdd80-563c-11e9-8d43-889baedc2409.png)
![BC984C79-6087-486D-BAC1-8C3B2AB68C32](https://user-images.githubusercontent.com/27660602/55471712-f205be80-563c-11e9-94b1-2528afc4e2f5.png)

**Comment by nicolo-ribaudo** [comment]
You need two pairs of `[`:
```
plugins: [
  ["plugin-name", { pluginOptions }]
]
```

**Comment by xgAnd** [comment]
it resolved me issues thanks a lot
