### ISSUE TITLE
Recent change results in build failure babel/polyfill 7.4.3

### ISSUE THREAD

**Issue by infolock** [babel/babel#9819]
## Bug Report

**Current Behavior**
```shell
ERROR in bundle.5ecbe226d86cc8df5e59.js from UglifyJs
Unexpected token: keyword «const» [./node_modules/@babel/polyfill/lib/index.js:6,0][bundle.5ecbe226d86cc8df5e59.js:95888,2]
Child extract-css-chunks-webpack-plugin node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js??ref--8-2!node_modules/@salesforce-mc/blockstandardcomponents/components/emoji-picker/emoji-picker.scss:
```

**Input Code**
Not sure where the code is, but if you navigate to the file its complaining about (`node_modules/@babel/polyfill/lib/index.js`) you can see a definition for the `global` function

```js
function _global() {
  const data = _interopRequireDefault(require("core-js/library/fn/global"));

  _global = function () {
    return data;
  };

  return data;
}
```

Changing `const data` to just be `var data` results in the build passing again.

**Expected behavior/code**
The build should pass without issue...

**Environment**
- Babel version(s): 7.4.3
- Node/npm version: Node 8/npm 5.5.1
- OS: OSX
- Monorepo: ehh...?
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**
Change `const` to `var` and it works fine...

**Additional context/Screenshots**

![Screen Shot 2019-04-03 at 12 24 40 PM](https://user-images.githubusercontent.com/808850/55495715-86efc400-560b-11e9-8920-1fce975c8d40.png)

![Screen Shot 2019-04-03 at 12 36 03 PM](https://user-images.githubusercontent.com/808850/55496468-1c3f8800-560d-11e9-8f2d-8f7c8f4e6d3b.png)

![Screen Shot 2019-04-03 at 12 38 11 PM](https://user-images.githubusercontent.com/808850/55496571-66286e00-560d-11e9-8b02-1c98f7891dea.png)

**Comment by infolock** [comment]
I can also run this build using by passing in `devtools: 'evel'` to `webpack` and it passes without issue.

**Comment by nicolo-ribaudo** [comment]
This will be fixed by https://github.com/babel/babel/pull/9812

**Comment by infolock** [comment]
Thanks!

**Comment by infolock** [comment]
fwiw, `7.4.0` builds fine as well

**Comment by justinyueh** [comment]
I use idempotent-babel-polyfill to prevent polyfill multiple times, and i can't revert 7.4.0.
when release the new version?

**Comment by nicolo-ribaudo** [comment]
@justinyueh You could use `@babel/polyfill` v7.4.0 and import `@babel/polyfill/noConflict` which doesn't warn when loaded multiple times.

**Comment by artemave** [comment]
What is the ETA on the fix being released?

**Comment by nicolo-ribaudo** [comment]
Merged: https://github.com/babel/babel/pull/9812
