### ISSUE TITLE
Support New Decorators Spec

### ISSUE THREAD

**Issue by pgoforth** [babel/babel#9822]
## Feature Request
The decorators spec has changed again and should be implemented in `@babel/plugin-proposal-decorators`.
https://github.com/tc39/proposal-decorators

**Comment by jhpratt** [comment]
@nicolo-ribaudo What's the status of implementation? Anything we can help out with?

**Comment by nicolo-ribaudo** [comment]
You can now use the new proposal using `["@babel/plugin-proposal-decorators", { "version": "2021-12" }]` - https://babeljs.io/docs/en/babel-plugin-proposal-decorators#version.
