### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by jamalabo1** [babel/babel#9823]
I have Upgraded to babel 7 yesterday, and from then i was fixing bugs that come a long,
one of is:

```
(function (exports, require, module, __filename, __dirname) { import * as colors from './colors'; 
SyntaxError: Unexpected token *
``` 
 
 
babel.config.js
```js
module.exports = {
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react", 
  ],
  "plugins": [
    "transform-es2015-modules-commonjs",
    "transform-export-extensions",
    "@babel/plugin-proposal-function-bind",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    [
      "@babel/plugin-proposal-optional-chaining",
      {
        "loose": false
      }
    ],
    [
      "@babel/plugin-proposal-pipeline-operator",
      {
        "proposal": "minimal"
      }
    ],
    [
      "@babel/plugin-proposal-nullish-coalescing-operator",
      {
        "loose": false
      }
    ],
    "@babel/plugin-proposal-do-expressions",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings"
  ],
}
```

**Expected behavior/code**
to run without errors 

**Environment**
- Babel version(s): [7.4.3]
- Node/npm version: [Node: v10.15.1, Npm: 6.4.1]
- OS: [Windows 10] 
- How you are using Babel: [register, loader]

### note: 
this error is happening because of package,
i'm using react ssr with express!

**Comment by nicolo-ribaudo** [comment]
1. You need to update `transform-export-extensions` to v7: https://babeljs.io/docs/en/v7-migration#split-babel-plugin-transform-export-extensions-into-the-two-renamed-proposals
2. `transform-es2015-modules-commonjs` is included in `@babel/env`, you should remove it.

**Comment by jamalabo1** [comment]
@nicolo-ribaudo 

Did't work!

**Comment by nicolo-ribaudo** [comment]
1) What is your updated config?
2) How are you running Babel?
3) What is the file path of the file which isn't correctly parsed?

**Comment by jamalabo1** [comment]
1. I'm running server side rendering,
webpack for client and nodemon for server 

#### index.js
```
require("@babel/register")()
require("@babel/polyfill")
require("./server");
```

##### server/index.js:
is a file where express is running, 
requires Reactjs files from "src"

2.
C:\dev\reactjs\{project_name}\node_modules\@atlaskit\theme\index.js:1
`
SyntaxError: Unexpected token *
`

3. no, it's  just module importing problem,

**Comment by nicolo-ribaudo** [comment]
`@babel/register` by default ignores files in other packages (e.g. in `node_modules`). If you want to compile that package, you can configure it like this:
```js
require("@babel/register")({
  ignore: /node_modules.(?!@atlaskit)/
})
```

**Comment by jamalabo1** [comment]
@nicolo-ribaudo still same error, 
it may be an error because of node require reactjs modules because bundling the packages with webpack does not have errors, compile without errors

**Comment by nicolo-ribaudo** [comment]
That's because webpack handles `import`, while node doesn't.

If you add some invalid code in the first line of C:\dev\reactjs{project_name}\node_modules@atlaskit\theme\index.js, does Babel throw an error, or is it thrown by node? This is needed to understand if Babel loads the file or not.

**Comment by jamalabo1** [comment]
```
 25% building 126/144 modules 18 active ...node_modules\core-js\modules\_export.jsC:\dev\reactjs\{project_name}\node_modules\@babel\core\lib\transformation\normalize-file.js:209
    throw err;
    ^

SyntaxError: C:\dev\reactjs\{project_name}\node_modules\@atlaskit\theme\index.js: Unexpected token (1:8)

> 1 | function() {
    |         ^
  2 | 
  3 | }
  4 | import * as colors from './colors';
    at Parser.raise (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3851:17)
    at Parser.unexpected (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5167:16)
    at Parser.parseIdentifierName (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7007:18)
    at Parser.parseIdentifier (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:6985:23)
    at Parser.parseFunctionId (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8015:55)
    at Parser.parseFunction (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7985:22)
    at Parser.parseFunctionStatement (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7639:17)
    at Parser.parseStatementContent (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7329:21)
    at Parser.parseStatement (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7291:17)
    at Parser.parseBlockOrModuleBlockBody (C:\dev\reactjs\{project_name}\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7868:25)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jamalabo1** [comment]
@nicolo-ribaudo any updates?

**Comment by nicolo-ribaudo** [comment]
You could try directly passing your config to `@babel/register`. Without a repository which reproduces the issue I can't say much else 🙁

**Comment by jamalabo1** [comment]
> You could try directly passing your config to `@babel/register`. Without a repository which reproduces the issue I can't say much else 🙁

I have changed `.babelrc` to `babel.config.js`, and passed the configurations from `babel.config.js` to `@babel/register` and everything works fine now 😊
