### ISSUE TITLE
Typo in babel-types cloneNode()

### ISSUE THREAD

**Issue by evandervalk** [babel/babel#9828]
## Bug Report

**Current Behavior**
At the moment innerComments are broken when cloning a node. This is because of a typo in the cloneNode function for babel-types.

**Input Code**
- N/A

**Expected behavior/code**
When cloning a node it should also copy over the innerComments.

**Environment**
- Babel version(s): master/latest
- Node/npm version: N/A
- OS: N/A
- Monorepo: yes
- How you are using Babel: loader

**Possible Solution**
Change `node.innerCmments` to `node.innerComments`.

See the [original source code](https://github.com/babel/babel/blob/b4224ed8f37bf317c6a10be044dce4d9bce179a1/packages/babel-types/src/clone/cloneNode.js#L69) for reference.

**Comment by existentialism** [comment]
@evandervalk doh, do you want to send a PR to fix this?

**Comment by evandervalk** [comment]
No problem, I'll get right on it.
