### ISSUE TITLE
JetBrains WebStorm/PhpStorm debugging support

### ISSUE THREAD

**Issue by drieks** [babel/babel#983]
Hello,

I'm trying to figure out how to support "on the fly" debugging in JetBrains WebStorm/PhpStorm IDEs for babel in nodejs using babels require hook.

I will show here my findings so far. It is easy to integrate the code from **app.js** into babels require hook, even with source map support. The problem is that the IDE will sometimes show the wrong file.

Here are some steps to reproduce. Create a new directory, call `npm install babel source-map-support` and create **app.js**, **a.js** and **b/c.js**. Please also create an empty directory **out**. Open the new Directory with WebStorm/PhpStorm.

**app.js**
```javascript
"use strict";

var fs = require("fs");
var count = 0;

function storm() {
    var oldExtension = require.extensions[".js"];
    require.extensions[".js"] = function (mod, filename) {
        if (filename.indexOf("/node_modules/") == -1) {
            const compile = mod._compile;
            mod._compile = function (content, filename) {
                const outFile = __dirname + "/out/babel-storm." + (count++) + ".js";
                fs.writeFileSync(outFile, content);
                compile.call(mod, content, outFile);
            };
        }
        oldExtension(mod, filename);
    };
}

require("source-map-support").install();
require("babel/register")({
    cache: false
});
storm();
require("./a").main();
```

**a.js**
```javascript
import {functionB} from "./b/c"

function functionA() {
    return new Error().stack;
}

function extractStackLine(stack) {
    return stack.split("\n")[1];
}

export function main() {
    const lineA = functionA();
    const lineB = functionB();
    const a = extractStackLine(lineA);
    const b = extractStackLine(lineB);
    debugger;
    console.log(a.endsWith("a.js:4:12)"), a);
    console.log(b.endsWith("test/b.js:1:32)"), b);
}
```

**b/c.js**
```javascript
export const functionB = () => new Error().stack;
```

Then create a laun ch configuration and start debugging.

The IDE will open the File **babel-storm.0.js**
```javascript
(function (exports, require, module, __filename, __dirname) { "use strict";

exports.main = main;

var functionB = require("./b/c").functionB;

function functionA() {
    return new Error().stack;
}

function extractStackLine(stack) {
    return stack.split("\n")[1];
}

function main() {
    var lineA = functionA();
    var lineB = functionB();
    var a = extractStackLine(lineA);
    var b = extractStackLine(lineB);
    debugger;
    console.log(a.endsWith("a.js:4:12)"), a);
    console.log(b.endsWith("test/b.js:1:32)"), b);
}

Object.defineProperty(exports, "__esModule", {
    value: true
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL2RyaWVrcy9Qcm9qZWt0ZS90ZXN0NS9hLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O1FBVWdCLElBQUksR0FBSixJQUFJOztJQVZaLFNBQVMsV0FBTyxPQUFPLEVBQXZCLFNBQVM7O0FBRWpCLFNBQVMsU0FBUyxHQUFHO0FBQ2pCLFdBQU8sSUFBSSxLQUFLLEVBQUUsQ0FBQyxLQUFLLENBQUM7Q0FDNUI7O0FBRUQsU0FBUyxnQkFBZ0IsQ0FBQyxLQUFLLEVBQUU7QUFDN0IsV0FBTyxLQUFLLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO0NBQy9COztBQUVNLFNBQVMsSUFBSSxHQUFHO0FBQ25CLFFBQU0sS0FBSyxHQUFHLFNBQVMsRUFBRSxDQUFDO0FBQzFCLFFBQU0sS0FBSyxHQUFHLFNBQVMsRUFBRSxDQUFDO0FBQzFCLFFBQU0sQ0FBQyxHQUFHLGdCQUFnQixDQUFDLEtBQUssQ0FBQyxDQUFDO0FBQ2xDLFFBQU0sQ0FBQyxHQUFHLGdCQUFnQixDQUFDLEtBQUssQ0FBQyxDQUFDO0FBQ2xDLGFBQVM7QUFDVCxXQUFPLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FBQyxRQUFRLENBQUMsWUFBWSxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUM7QUFDekMsV0FBTyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsUUFBUSxDQUFDLGlCQUFpQixDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUM7Q0FDakQiLCJmaWxlIjoiL2hvbWUvZHJpZWtzL1Byb2pla3RlL3Rlc3Q1L2EuanMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQge2Z1bmN0aW9uQn0gZnJvbSBcIi4vYi9jXCJcblxuZnVuY3Rpb24gZnVuY3Rpb25BKCkge1xuICAgIHJldHVybiBuZXcgRXJyb3IoKS5zdGFjaztcbn1cblxuZnVuY3Rpb24gZXh0cmFjdFN0YWNrTGluZShzdGFjaykge1xuICAgIHJldHVybiBzdGFjay5zcGxpdChcIlxcblwiKVsxXTtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIG1haW4oKSB7XG4gICAgY29uc3QgbGluZUEgPSBmdW5jdGlvbkEoKTtcbiAgICBjb25zdCBsaW5lQiA9IGZ1bmN0aW9uQigpO1xuICAgIGNvbnN0IGEgPSBleHRyYWN0U3RhY2tMaW5lKGxpbmVBKTtcbiAgICBjb25zdCBiID0gZXh0cmFjdFN0YWNrTGluZShsaW5lQik7XG4gICAgZGVidWdnZXI7XG4gICAgY29uc29sZS5sb2coYS5lbmRzV2l0aChcImEuanM6NDoxMilcIiksIGEpO1xuICAgIGNvbnNvbGUubG9nKGIuZW5kc1dpdGgoXCJ0ZXN0L2IuanM6MTozMilcIiksIGIpO1xufVxuIl19
});
```

with highlighted **debugger** line. Please note that the IDE will now display **out/babel-storm.0.js** and **out/babel-storm.1.js** in the project view.

Then, just restart debugging. (click "stop and restart" if necessary) The right file **a.js** will be shown with line 16 highlighted, as wanted.

Now delete all files in **out** and restart debugging again, **out/babel-storm.0.js** will be open. Another restart will show the right file. It seems that the IDE will use the source map from **babel-storm.*.js** when the file is already on disk when the debugger was started.

I think that is will be possible to debug using "File Watchers", but this will need to be separately configured and the options need to be in sync. Another option is to use "File Watches" and require the files transpiled by the IDE.

I hope to find a way to debug in WebStorm/PhpStorm "on the fly" like in `node-inspector`.

If you have any hint for me please let my now.

**Comment by sebmck** [comment]
This would be an issue/bug with Webstorm/PHPStorm since Babel outputs all the correct source map information.

**Comment by KeKs0r** [comment]
@sebmck : I know that the issue for Babel itself is solved, but how did u end up solving the problem in general? (I am trying to debug some mocha tests)

**Comment by dmorgantini** [comment]
https://youtrack.jetbrains.com/issue/WEB-16397 go and upvote this if you want it fixed!
