### ISSUE TITLE
Unable to get private member from other instance. :(

### ISSUE THREAD

**Issue by trusktr** [babel/babel#9831]
## Bug Report

**Current Behavior**

```
Uncaught TypeError: attempted to get private field on non-instance
```

Run the code generated from the [this repl](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAMTnAsjAHjMAKAIQEMBnAUwEpEBvAKEUQCcyoRGkIAbUklNRMlihkwAE17FyNeogCQAYmCIAvIgCsMhkVGi8cKAAsyjKnQbnEhmCQB0ixAGpV-o4zvBNiAL4zZAcxZEYDxTTwZmVnZLA2t3Tx8GHx9aLh5EAEEaH1SSCSzaFO5cvjgBIRFxEswcfHTTbKKJIkYy4TFeVAxsXEJ6gogEEigglUQwMgB3EpTB4YAjUfGp4kYC4BttXTmKfsG4TjIbTjg_PHXgKgB6S8QABQAlAHkCABkAUXQAQiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.4.3&externalPlugins=) example. It is a small reproduction example.

In actual real use cases, this problem happens when making base classes for use with Custom Elements.

For example, consider a library author writing code like

```js
export default
function WebComponent(Base = HTMLElement) {
  return class WebComponent extends Base {
    methodThatDoesSomethingWithOtherWebComponents(other) {
      // ... PROBLEM ...
    }
  }
}
```

and the user choosing which element to extend from:

```js
import WebComponent from 'awesome-lib/WebComponent'

// suppose user gains dynamic templates, state reactivity,
// shadow dom, etc, from using WebComponent
class AwesomeButton extends WebComponent(HTMLButtonElement) {
  // ...
}
```

And now the user is disappointed because the library throws errors, library author tested only with HTMLElement and it worked fine, then the library author has to go find a solution like switching to WeakMaps or something.

**Input Code**

See above repl

**Expected behavior/code**

It works

**Babel Configuration (.babelrc, package.json, cli command)**

see above repl example

**Environment**

see above repl example

**Possible Solution**

Allow access.

**Comment by loganfsmyth** [comment]
Could you clarify your example? The REPL example is expected behavior since the only thing relating `f` and `b` is that they use the same mixin, but since that mixin creates two separate parent classes, they aren't actually the same private field and thus the exception is expected.

Is there something about your actual code with HTMLButtonElement that changes that to exposes an issue that is unexpected per the spec?

**Comment by jridgewell** [comment]
Correct, and I know you're [aware](https://github.com/tc39/proposal-class-fields/issues/60#issuecomment-476015588) of why this is the case. Babel tries to follow TC39 specs, so you have to change the spec before we'll support this.
