### ISSUE TITLE
Missing parens when generating ArrowFunctionExpression

### ISSUE THREAD

**Issue by wonnage** [babel/babel#9836]
## Bug Report

Generating code for ArrowFunctionExpression not wrapped in ExpressionStatement is missing parens when the body is an ObjectExpression.

**Input Code**

```js
import { parse } from '@babel/parser';
import generate from '@babel/generator';

ast = parse("() => ({ foo: 'bar' })");
node = ast.program.body[0];
generate(node, {});
```

**Expected behavior/code**
```js
"() => ({\n  foo: "bar"\n});"
```

**Actual output**
```js
"() => {\n  foo: 'bar'\n}"
```

**Babel Configuration (.babelrc, package.json, cli command)**
None (just using the default options)

**Environment**
- Babel version(s): 7.4.0
- Node/npm version:Node 8/npm 6
- OS: Linux
- Monorepo: no
- How you are using Babel: Node API

**Possible Solution**
The issue is that the parentheses injection logic doesn't work on a lone ArrowFunctionExpression here: https://github.com/babel/babel/blob/master/packages/babel-generator/src/node/parentheses.js#L274

The two nodes in `printStack` are `[ArrowFunctionExpression, ObjectExpression]`; after popping both of those, `i` is 0 and the loop never runs. Some options include checking for `i >= 0`, adding another case on L235 (https://github.com/babel/babel/blob/master/packages/babel-generator/src/node/parentheses.js#L285), or maybe this is an invalid use case and I should close this bug. I'm not familiar with the code so I'm not sure what side effects changing the conditions might introduce.

**Comment by tanhauhau** [comment]
@wonnage I tried but I couldn't reproduce it locally. Can check if it still happens with the latest babel version?

**Comment by nicolo-ribaudo** [comment]
This error can't be reproduced on master.
