### ISSUE TITLE
Babel 7 uses babel-plugin-transform-runtime instead of @babel/plugin-transform-runtime

### ISSUE THREAD

**Issue by zerkdev** [babel/babel#9841]
I want to use @babel/plugin-transform-runtime for my application but instead it uses the old one with lower version and i cannot uninstall it and its not even in my dependencies.

package.json : 

> "devDependencies": {
        "@babel/plugin-transform-runtime": "^7.4.3",
        "@babel/preset-env": "^7.4.3",
        "@vue/test-utils": "^1.0.0-beta.29",
        "axios": "^0.18",
        "babel-jest": "^24.7.1",
        "babel-loader": "^8.0.5",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.2.0",
        "jest": "^24.7.1",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "lodash": "^4.17.5",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "vue": "^2.6.7",
        "vue-jest": "^3.0.4"
    },
    "dependencies": {
        "@babel/core": "^7.4.3",
        "@babel/runtime": "^7.4.3",
        "@fortawesome/fontawesome-svg-core": "^1.2.17",
        "@fortawesome/free-solid-svg-icons": "^5.8.1",
        "@fortawesome/vue-fontawesome": "^0.1.6",
        "feather-icons": "^4.19.0",
        "nprogress": "^0.2.0",
        "vue-notification": "^1.3.16",
        "vue-router": "^3.0.2",
        "vue-select": "^2.6.3",
        "vue-sortable": "^0.1.3",
        "vue-sweetalert2": "^1.6.4",
        "vue-template-compiler": "^2.6.10",
        "vuex": "^3.1.0"
    }

babel.config.js : 

> module.exports = {
    presets: [
      '@babel/preset-env'
    ],
    plugins: [
      '@babel/plugin-transform-runtime'
    ]
  };

---

**Comment by nicolo-ribaudo** [comment]
What does this command log?
```
npx nls why babel-plugin-transform-runtime 
```
