### ISSUE TITLE
Setting broserslist to "ie 9" lacks "MutationObserver" object

### ISSUE THREAD

**Issue by SetTrend** [babel/babel#9842]
## Bug Report

![MutationObserver undefined](https://user-images.githubusercontent.com/9283914/55818000-f24b0180-5af5-11e9-9f76-b5df17ed6d0a.png)

**Current Behavior**
When polyfilling down to IE9, `@Babel/polyfill` seems to lack an implementation for the `MutationObserver` object (see screenshot).

**Input Code**
&ndash; private, proprietary &ndash;

**Expected behavior/code**
`MutationObserver` should be polyfilled.

**Babel Configuration (.babelrc, package.json, cli command)**

### webpack.config.js
```js
{
  test: /\.js$/i,
  include: [
    /[/\\]node_modules[/\\]lit-html[/\\]/i,
    /[/\\]node_modules[/\\]@babel[/\\]/i,
    /[/\\]node_modules[/\\]@webcomponents[/\\]/i
  ],
  use: {
    loader: 'babel-loader',
    options: {
      presets: ['@babel/preset-env']
    }
  }
}
```

### .babelrc
```js
{
	useBuiltIns: false
}
```

### browserslist
```
ie 9
```

### main.ts
```ts
import "@babel/polyfill"

import "@webcomponents/webcomponentsjs/webcomponents-bundle";
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js';
```

**Environment**
- Babel version(s):
   "@babel/core": "^7.4.3"
   "@babel/polyfill": "^7.4.3"
   "@babel/preset-env": "^7.4.3"
- Node/npm version: v10.15.3/6.4.1
- OS: Windows 10x64
- How you are using Babel: webpack

**Comment by SetTrend** [comment]
As a workaround, I installed `mutationobserver-shim`. Now I can see that the following Object properties are not available, too:

## Object.setPrototypeOf

![Object.setPrototypeOf](https://user-images.githubusercontent.com/9283914/55819095-58d11f00-5af8-11e9-98bb-73a2028967a2.png)

## Event.composedPath

![Event.composedPath](https://user-images.githubusercontent.com/9283914/55819225-96ce4300-5af8-11e9-8a9c-525e27989166.png)

**Comment by nicolo-ribaudo** [comment]
Babel only polyfills ECMAScript methods (i.e. things available in every JS engine, not just in browsers).

`MutationObserver` and `Event.composedPath` are Web API, so you need to manually load polyfills for them.

`Object.setPrototypeOf` should be polyfilled: are you sure that you are compiling the file which uses that function with Babel?

**Comment by SetTrend** [comment]
Thanks for clarifying, @nicolo-ribaudo!

I'm not sure if this distinction comes clear from the [readme](https://babeljs.io/docs/en/babel-polyfill).

For now, I've been using: https://gist.github.com/edoardocavazza/47246856759f2273e48b

**Comment by JLHwung** [comment]
Closing this as it is out of babel's scope.
