### ISSUE TITLE
_typeof function in generated code calls itself before it is defined

### ISSUE THREAD

**Issue by cyrilchapon** [babel/babel#9844]
[#4125](https://github.com/babel/babel/issues/4125) is far from being resolved and should be reopened

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/issues/4125#issuecomment-395483513

> Can some of you create a reproducible example by only using Babel?

**Comment by cyrilchapon** [comment]
@nicolo-ribaudo What do you mean ?

Isn't babel supposed to bundle packages ?

I can surely `npm install babel-cli` and `babel` but I'm not sure it will reproduce any issue

**Comment by mAAdhaTTah** [comment]
@cyrilchapon Babel is not a bundler, it's a transpiler. The concern is the underlying issue is caused by Parcel, not Babel, so an isolated, reproducible example would be helpful for narrowing down the cause.

**Comment by nicolo-ribaudo** [comment]
Is anyone able to reproduce this issue without using Parcel? Parcel does a lot of magic around Babel, so I'm not sure who is causing this problem.

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue, since I can't reproduce it using Babel an no one else can show an example.
