### ISSUE TITLE
@babel/preset-typescript generate declaration file

### ISSUE THREAD

**Issue by njleonzhang** [babel/babel#9850]
can @babel/preset-typescript  generate a declaration file? It seems if we want declaration, we must build typescript file with tsc.

**Comment by nicolo-ribaudo** [comment]
Ok order to build a `.d.ts` file, we would need type information.
Babel is only meant to transpile TS syntax to JavaScript: for anything type-related you still need `tsc`.

**Comment by njleonzhang** [comment]
@nicolo-ribaudo so I need to build typescript again with tsc for `.d.ts`.

**Comment by nicolo-ribaudo** [comment]
You can use Babel for transpiling and `tsc --emitDeclarationOnly` for `.d.ts` files.

**Comment by njleonzhang** [comment]
@nicolo-ribaudo tnx very much
