### ISSUE TITLE
Legacy Decorators + Generator Methods

### ISSUE THREAD

**Issue by buschtoens** [babel/babel#9852]
## Bug Report

**Current Behavior**
Legacy decorators cannot decorate generator methods. An `Unexpected token` error is thrown:

```
/repl: Unexpected token (5:21)

  3 | class Foo {
  4 |   @deco
> 5 |   *generatorMethod() {}
    |                      ^
  6 | }
```

**Input Code**
[REPL](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABAEwKYTgCgJSIN4C-AUERADYCGAzlYgGJxz5GKIACaGLiAVAOaowqAE4UocYQFlUUABZxkOfMQJA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=7.4.3&externalPlugins=)

```js
function deco() {}

class Foo {
  @deco
  *generatorMethod() {}
}
```

**Expected behavior/code**
No error should be thrown and the method should be transpiled like normal methods.

**Babel Configuration**
Presets: `es2015` + `stage-2` 
Decorators: legacy

**Environment**
Babel version(s): 7.4.3

**Possible Solution**
#8742

**Additional context/Screenshots**
#5704, https://github.com/babel/babylon/issues/382

**Comment by nicolo-ribaudo** [comment]
We should update our parser to https://github.com/wycats/javascript-decorators/commit/e240cbc91a45d87b07fb2ba6fd7a499e4bf27e46, so that we also match TS's behavior.

**Comment by buschtoens** [comment]
I never meddled with the Babel parser, but I would like to help implement this. Can you provide some pointers?

**Comment by robclancy** [comment]
I don't understand how stage 1 decorators can be recommended over stage 2 while this bug exists. It's a now default JS feature that isn't compatible but was fixed in stage 2.
