### ISSUE TITLE
Path.getsource can't work well,Cannot read property 'getCode' of undefined

### ISSUE THREAD

**Issue by flytam** [babel/babel#9855]
## Bug Report

**Current Behavior**
Can not get the source code

**Input Code**

```js
// Here are the smallest example
const parser = require("@babel/parser");
const traverse = require("@babel/traverse").default;

const input = `<p>test</p>`;
const ast = parser.parse(input, {
    plugins: ["jsx"]
});

traverse(ast, {
    JSXElement: {
        enter(path) {
            console.log(path.getSource());
        }
    }
});
```

**Expected behavior/code**
Ouput the source code

**Environment**
- Babel version(s):        "@babel/parser": "^7.4.2","@babel/traverse": "^7.4.0",
- Node/npm version: [e.g. Node 8/npm 5]
- OS: OSX 10.14,

**Additional context/Screenshots**

<img width="897" alt="bug" src="https://user-images.githubusercontent.com/20512530/56088021-58df6f00-5eaa-11e9-91e1-8bb043c77420.png">

**Comment by flytam** [comment]
？

**Comment by nicolo-ribaudo** [comment]
`getSource` uses an internal object (`hub`) which contains some information provided by `@babel/core`: that object contains the original source code, alongside with other metadata.
If you are using `@babel/traverse` directly and want a method which uses `hub`, you need to setup `hub` manually.
Depending on your usecase, you could use `path.toString()` instead, which builds the string using `@babel/generator` and thus doesn't need to retrieve the original source.

**Comment by flytam** [comment]
it works well,thanks
