### ISSUE TITLE
strictMode disabled causes SyntaxError with exportDefaultFrom

### ISSUE THREAD

**Issue by sebdeckers** [babel/babel#9858]
## Bug Report

**Current Behavior**
Fails with `strictMode: false`, passes with `strictMode: true`.

**Input Code**

```js
const parser = require('@babel/parser')
const source = `
  export { f }
  function f () {}
`
const options = {
  sourceType: 'module',
  plugins: ['exportDefaultFrom']
}

parser.parse(source, { ...options, strictMode: true })
// OK

parser.parse(source, { ...options, strictMode: false })
// SyntaxError: Export 'f' is not defined (2:11)
```

**Expected behavior/code**
Disabling strict mode should not cause a syntax error for code that parses with strict mode enabled.

**Babel Configuration (.babelrc, package.json, cli command)**

N/A, see example code above

**Environment**
- Babel version(s): v7.4.3
- Node/npm version: Node 11.13.0/npm 6.7.0
- OS: macOS 10.13.6 (High Sierra)
- Monorepo: no
- How you are using Babel: `parser`

**Possible Solution**

N/A

**Additional context/Screenshots**

Originally came across this problem while parsing Moment.js source code.

`moment/src/lib/utils/hooks.js`

https://github.com/moment/moment/blob/92c28cb639d7537d00f9f48f326e5f1ced4c869b/src/lib/utils/hooks.js

**Comment by nicolo-ribaudo** [comment]
Are you sure `@babel/parser` is 7.4.3? It should have been fixed by https://github.com/babel/babel/pull/9725

**Comment by sebdeckers** [comment]
@nicolo-ribaudo I can confirm that it is 7.4.3 and that patch is included.

package-lock.json

```json
{
  "name": "test-babel-parser",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@babel/parser": {
      "version": "7.4.3",
      "resolved": "https://registry.npmjs.org/@babel/parser/-/parser-7.4.3.tgz",
      "integrity": "sha512-gxpEUhTS1sGA63EGQGuA+WESPR/6tz6ng7tSHFCmaTJK/cGK8y37cBTspX+U2xCAue2IQVvF6Z0oigmjwD8YGQ=="
    }
  }
}
```

node_modules/@babel/parser/lib/index.js

```js
  checkLocalExport(id) {
    if (this.scopeStack[0].lexical.indexOf(id.name) === -1 && this.scopeStack[0].var.indexOf(id.name) === -1 && this.scopeStack[0].functions.indexOf(id.name) === -1) {
      this.undefinedExports.set(id.name, id.start);
    }
  }
```

**Comment by sebdeckers** [comment]
CI run:
https://gitlab.com/sebdeckers/test-babel-parser/-/jobs/196421474
