### ISSUE TITLE
Input Code is not formatted the same as Output

### ISSUE THREAD

**Issue by moonmeister** [babel/babel#9860]
## Report

**Current Behavior**
We're trying to use parse/generate to read a js config file, modify the config, then write back to the same file. To start I decided to ignore the modification step to verify I could read a config and write it back accurately. This is where we ran into an issue. Formatting and some comments get lost.

I honestly not sure if this is expected, a bug, or I'm missing a critical configuration option. Thanks for the help. 

Input code:

```js
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    /* this (optional) plugin enables Progressive Web App + Offline functionality */
    // To learn more, visit: https://gatsby.dev/offline
    // 'gatsby-plugin-offline'
  ],
}
```

What get's written to a file:

```js
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`
  },
  plugins: [`gatsby-plugin-react-helmet`, {
    resolve: `gatsby-source-filesystem`,
    options: {
      name: `images`,
      path: `${__dirname}/src/images`
    }
  }, `gatsby-transformer-sharp`, `gatsby-plugin-sharp`, {
    resolve: `gatsby-plugin-manifest`,
    options: {
      name: `gatsby-starter-default`,
      short_name: `starter`,
      start_url: `/`,
      background_color: `#663399`,
      theme_color: `#663399`,
      display: `minimal-ui`,
      icon: `src/images/gatsby-icon.png` // This path is relative to the root of the site.

    }
  }]
};
```

1. Notice the `{,[` brackets on the same line and not on a new line. 
2. Notice the final 3 lines of comments are missing.

**Input Code**
- REPL or Repo link if applicable:

```js
const fileLocation = path.join(rootPath, `gatsby-config.js`)
const file = fs.readFileSync(fileLocation).toString()
const currentConfigAST = parse(file)

const configString = generate(currentConfigAST, {
    comments: true,
    compact: false,
    concise: false,
  }).code

fs.writeFile(`gatsby-config-test.js`, configString, err => {
    if (err) throw new Error(`gatsby-config-test.js write error: ${err}`)
  })
```

**Expected behavior/code**
I would expect these two files to be identical. The brackets on a newline I could probably ignore, but missing comments is definitely not okay for our situation.

**Environment**
-   "@babel/code-frame": "^7.0.0",
    "@babel/core": "^7.4.3",
    "@babel/generator": "^7.4.0",
    "@babel/parser": "^7.4.3",
    "@babel/polyfill": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@babel/traverse": "^7.4.3",
- Node/npm version: node v10.15.3/npm v6.4.1
- OS: Ubuntu Linux 18.10
- Monorepo: lerna
- How you are using Babel: import

Thanks ya'll.

**Comment by andreydrozd** [comment]
I'm getting similar formatting issues on JSX, except I'm primarily getting newlines added in functions and in markup.

**Comment by vikr01** [comment]
Have you tried using the [`shouldPrintComment` option](https://babeljs.io/docs/en/options#shouldprintcomment)?

I think it should look something like this:

```diff
const fileLocation = path.join(rootPath, `gatsby-config.js`)
const file = fs.readFileSync(fileLocation).toString()
const currentConfigAST = parse(file)

const configString = generate(currentConfigAST, {
    comments: true,
+    shouldPrintComment: ()=>true,
    compact: false,
    concise: false,
  }).code

fs.writeFile(`gatsby-config-test.js`, configString, err => {
    if (err) throw new Error(`gatsby-config-test.js write error: ${err}`)
  })
```

As for formatting, that's not on Babel. With something like [`prettier`](https://github.com/prettier/prettier) you may be able to prettify the code string with their API.

**Comment by nicolo-ribaudo** [comment]
Matching the original formatting is not a goal of Babel. I suggest using recast with Babel if you want to do so.

You can find an example at https://github.com/nicolo-ribaudo/legacy-decorators-migration-utility/blob/master/packages/wrap-legacy-decorators/src/index.js#L105

**Comment by moonmeister** [comment]
I can understand the formatting stuff. @vikr01 I just tried it and nothing changed. Comments are still not included...either way I'd expect `comments: true` to include all comments.

**Comment by nicolo-ribaudo** [comment]
Yeah, comments shouldn't disappear

**Comment by JLHwung** [comment]
> Comments are still not included...either way I'd expect comments: true to include all comments.

I can not reproduce this issue on Babel 7.10.5: [REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=LYewJgrgNgpgdDAHgBxAJwC4GcAEBeHAbwCgccsBLDGAWRgwEMwHGAuI0snDK2dgAwDiLLACMAnjgAiMAGYNoGHAGVGmGGn4AaTmTAwsAYzQVkPEADsBAaQqGA1jhCzZOcSAhocFpBi04AczQYFhxhbAkcZDQQACsYQyUAdyoAC25Uilx9eUVyNWo0OBwAFUzcUQZg0UsDfKrC8kzkXBSMdPaYHGAGCgswkUjDS1kKAM8WCkscUdhcdwhusdSlHxgwOG1dHAV29AEAAQDB8VisLbIAXx0yZCgIAL6sdgBtbf5jiPEAWjuHvu-wQYiW-qRgUGA9AuXBIXC4wSwICgADcYAJPmIfojPIYYN9ZgZxFhqMBoXCQGYphZnhw4XCLAxIQIKD0AgYyXTkCxUgIACSEAD6ArAFDQDMhlwA9Fg0IZJSyGGzzjc6ddtmq4R8Tt8MGgGNTZOhIWhvlhUlVkBytV9fvdHhZTea0JaVWRYXSEUjUejtX97d8ehYKLIDBgOWQKeZqex3XTvIy0ThrZjTQUNN8cgooGHXXSzegMALxYn-MSGhpw1wy5gBZ4oAJJZWyJUHEEPBYwALhlB9kmAMQANgHAGZhwBOMdNjIwSFdpG9_iDkfjye5uEirB3BjiATAPoKqDfCAUKd2SwCGVyhVKyUYiTfM8WODICwBbQ4SWS0rlKLcnBZHBgigSZUW4EBp0AkAQCUZwIMoag4G2K5cw1LhJQAKgyACAApIypBgoAASiiO0-hwGAGVEOYcAABRiIIDEoUCAHUYFEHAAEFkGQHAAGocAAeRcKA-i6WQIAsRJ8JEjBJHQyVtk_UpwNgKp-lAYJ_GRLIqHYFYMBaVhPzvcQ4H0ZFJWcWQRJ8RSvwAchM21_gdKybJgezOAAXR0S5iCAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.10.5&externalPlugins=)

Feel free to reopen it if you can draft a reproducing example on REPL.
