### ISSUE TITLE
Flags Polyfill Incorrectly Being Applied

### ISSUE THREAD

**Issue by noahbuscher** [babel/babel#9868]
## Bug Report

**Current Behavior**

In our library we're using the `flags` prop to allow for configuring components. We're transpiling the library using `@babel/plugin-transform-runtime` and the `corejs: 3` flag. Oddly, for some reason Core.js and/or Babel is mistakenly thinking that our flags prop needs the polyfill.

Before transpiling (simplified):

```js
import React from "react";
import PropTypes from "prop-types";

/**
 * @class Button
 * @desc button component
 * @param {array} [flags]
 *     Set the flag for "add-button-margin" to override the special add button margin styling.
 * @example
 *  <Button>
 *  </Button>
 */

const checkTestFlag = flags => flags.includes("test-flag");

function Button ({
    flags,
}) {
    const hasTestFlag = checkFixAddMargin(flags);

    return (
        <Button className={ hasTestFlag ? "testClass" : null }>
            Test
        </Button>
    );
}

Button.propTypes = {
    flags: PropTypes.arrayOf(PropTypes.string),
};

Button.defaultProps = {
    flags: [],
};

export default Button;
```

After transpiling:
```js
var _flags = _interopRequireDefault(require("@babel/runtime-corejs3/core-js-stable/instance/flags"));
var _react = _interopRequireDefault(require("react"));
var _propTypes = _interopRequireDefault(require("prop-types"));

/**
 * @class Button
 * @desc button component
 * @param {array} [flags]
 *     Set the flag for "add-button-margin" to override the special add button margin styling.
 * @example
 *  <Button>
 *  </Button>
 */

var checkTestFlag = function checkFixAddMargin(flags) {
  return (0, _includes["default"])(flags).call(flags, "test-flag");
};

function Button(_ref) {
  var flags = (0, _flags["default"])(_ref),
  var hasTestFlag = checkFixAddMargin(flags);

  return _react["default"].createElement(Button, {
    className: hasTestFlag ? "testClass" : null
  }, "Test");
}

Button.propTypes = {
  flags: _propTypes["default"].arrayOf(_propTypes["default"].string)
};

Button.defaultProps = {
  flags: []
};

Button.buttonTypes = buttonTypes;
var _default = Button;
exports["default"] = _default;
module.exports = exports["default"];
```

It still appears that our code works, even _with_ the polyfill mistakenly added, but we would prefer it not have to be included regardless.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): v7.4.0
- Node/npm version: Node 8.12.0 | npm 6.7.0
- OS: macOS 10.14.3
- Monorepo: No
- How you are using Babel: loader

**Comment by zloirock** [comment]
I already [answered](https://github.com/zloirock/core-js/issues/530#issuecomment-484159112) in the `core-js` repo. In your case, it's expected behavior, can't be optimized and should not break anything. `(0, _flags["default"])(something)` helper is just an equal of `something.flags` and if `something` is not a regexp, in this helper a polyfill will not be applied.
