### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by sebmck** [babel/babel#987]

**Comment by sebmck** [comment]
I've got the visitor API figured out since it'd just be exposing the internals which I've got pretty stable. Only thing that I'm still trying to figure out is what would be the best way to inject transformers into the transformer pipeline.

I'm considering the following options:

 - All ran **before** the internal transformers
 - All ran **after** the internal transformers
 - A transformer exposes whether it should be ran before or after.
 - The user defines whether it should be ran before or after.

**Comment by sebmck** [comment]
I'm leaning more towards requiring all custom transformers be ran before the internal ones.

**Comment by stefanpenner** [comment]
Cc @rwjblue

**Comment by amasad** [comment]
For our particular use case we need our transformers to run before, because we need information that could be lost after babel's transformers run. e.g. we have private var munging in classes (see jstransform)

**Comment by timoxley** [comment]
Perhaps plugins could elect at what point they run in the pipeline, even perhaps choosing to run before/after other specific plugins. Browserify compiler pipeline exposes an api that allows plugins a lot of control over where they run. https://github.com/substack/browserify-handbook#compiler-pipeline & https://www.npmjs.com/package/labeled-stream-splicer

**Comment by sebmck** [comment]
Plugins should not be aware of what position they sit in and it's up to the
user to order the position in which their plugins are ran (before internal
transformers). Internal transformer position is very important and allowing
plugins to hook into that is dangerous as it exposes too much internal
behaviour that can and will change.

On Monday, 16 March 2015, Tim Oxley <notifications@github.com> wrote:

> Perhaps plugins could elect at what point they run in the pipeline, even
> perhaps choosing to run before/after other specific plugins. Browserify
> compiler pipeline exposes an api that allows plugins a lot of control over
> where they run.
> https://github.com/substack/browserify-handbook#compiler-pipeline &
> https://www.npmjs.com/package/labeled-stream-splicer
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/987#issuecomment-81101354>.
>


-- 
Sebastian McKenzie

**Comment by timoxley** [comment]
you're right.

**Comment by Alxandr** [comment]
I agree on running before all internal transformers. Otherwise, we could just use `esprima` on the output.

**Comment by philidem** [comment]
In my particular use case, having access to the AST after the internal transformations would be ideal. The transformer I have would be looking for the `require(...)` method calls after the imports have been normalized to CommonJS. The original source code would have a mix of `require(...)` and `import` so it would be easier to find these after being normalized. I like the proposal of letting the custom transformer choose _before_ or _after_ internal transformers.

**Comment by Alxandr** [comment]
@philidem You can do this today though, by simply running `esprima` on the transpiled code, and regenerating it with `escodegen`.

**Comment by philidem** [comment]
@Alxandr I'm looking for a more efficient solution if possible. I did implement the `esprima` solution already but `esprima` is repeating a lot of the same work that Babel did internally. Re-parsing the generated code seems like something that should be avoided.

I am working on adding ES6 support to https://github.com/raptorjs/optimizer. This tool builds a dependency graph by analyzing the AST and then applies some transformations. I am trying to see if there is a way to piggyback on top of Babel's own parse and transform code. With very large projects, avoiding duplicate work would be ideal. The `optimizer` does cache the transformed results so I can get by for a little while (the initial build will be a slower but subsequent builds should be very fast).

**Comment by lukescott** [comment]
Running before or after all transformers: I don't think it's always going to be that simple. When writing a plugin the AST you expect is going to be before or after a particular transformer. Running before or after all internal transformers may solve some simple cases, but what about the order running relative to each other?

I agree that the user shouldn't specify the order (user of the plugin). But the plugin itself should specify a relative position to another plugin/transformer. Something like this:

```javascript
{
  before: "es6.forOf"
}
```

So you'd have `before` or `after` (not both). You could also have `depends` to make sure another transformer is enabled.

If a plugin doesn't specify, a sane default should be used: perhaps after the ones already added?

I don't see why someone shouldn't be able to load their transformers last if they want to. Esprima has ES6 support now, but it's been a bit behind feature wise. And if you're using babel already, it's kind of a waste to have to do extra processing.

My use case: I'm replacing the forOf transformer to behave slightly different than the internal one. I have been monkey-patching that since version 3 (updating it when things change). I add forOf to the blacklist, but the generators transformer makes a similar transformation to the for-of statement so I end up having to disable both. Which is ok in the project I'm using it for since it doesn't require generators.

**Comment by sebmck** [comment]
@Alxandr 

> You can do this today though, by simply running `esprima` on the transpiled code, and regenerating it with `escodegen`.

Kind of defeats the purpose. Then you wont have access to any of the actual transformation infrastructure that Babel has, which is what most people would prefer anyway.

@lukescott 

> Running before or after all internal transformers may solve some simple cases, but what about the order of plugins running relative to each other?

Plugins should not be aware of what position they sit in and it's up to the user to order the position in which their plugins are ran. I'm not willing to document the position of the internal transformers because you shouldn't be architecting your plugins to rely on an internal transformer whose position and behaviour can change without notice. It would require bumping a major every single time I wanted to change the position of one of them for whatever reason. I haven't been able to think of a scenario where a plugin injecting itself between any of the internal transformers is a good idea.

> My use case: I'm replacing the forOf transformer to behave slightly different than the internal one. I have been monkey-patching that since version 3 (updating it when things change).

Why can't you just do the transformation before everything else has happened? What transformations are you waiting on prior?

> I add forOf to the blacklist, but the generators transformer makes a similar transformation to the for-of statement so I end up having to disable both.

This hasn't been the case since `regenerator-babel` was reintroduced.

**Comment by myfreeweb** [comment]
before++;

I really want [sweet.js](http://sweetjs.org/) to be integrated with babel.

**Comment by sebmck** [comment]
@myfreeweb See the discussion [here](https://github.com/babel/babel/issues/568#issuecomment-71716260). Unlikely to ever be implemented as the architecture of both projects is too different to allow any sort of interopability.

**Comment by mjackson** [comment]
Any idea yet what the plugin API is going to look like?

**Comment by amasad** [comment]
:dancer: :dancer:
