### ISSUE TITLE
Split up CLI

### ISSUE THREAD

**Issue by sebmck** [babel/babel#988]

**Comment by cesarandreu** [comment]
Is this a new repo, or npm package, or how is this gonna work?

I saw the [babel-cli](https://github.com/babel/babel-cli) repo but it's empty.

**Comment by sebmck** [comment]
@cesarandreu Was going to be a separate package but it's easier to just keep it in the core for now.

**Comment by cesarandreu** [comment]
Gotcha, thanks!
