### ISSUE TITLE
Test cases are failing after #make test in babel repository 

### ISSUE THREAD

**Issue by sunil1783** [babel/babel#9889]
Test cases are failing after #make test in babel repository 

To Reproduce :

curl https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh| bash
source ~/.nvm/nvm.sh
nvm install v8.15.1	
npm install -g yarn
git clone https://github.com/babel/babel/
cd babel
make bootstrap
make build
make test

Result :

Summary of all failing tests
 FAIL  packages/babel-preset-env/test/fixtures.js (10.426s)
  â babel-preset-env/corejs3 âº entry chromeandroid

    Expected /home/babel/packages/babel-preset-env/test/fixtures/corejs3/entry-chromeandroid/output.mjs to match transform output.
    To autogenerate a passing version of this file, delete the file and re-run the tests.

    Diff:

    - Expected
    + Received

    - import "core-js/modules/es.array.unscopables.flat";
    - import "core-js/modules/es.array.unscopables.flat-map";
    - import "core-js/modules/es.object.from-entries";
      import "core-js/modules/web.immediate";
      1 ** 2;

      333 |
      334 |       try {
    > 335 |         expect(actualCode).toEqualFile({
          |                            ^
      336 |           filename: expected.loc,
      337 |           code: expectCode
      338 |         });

      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:335:28)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:412:13)
      at Object.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:436:15)

Test Suites: 1 failed, 140 passed, 141 total
Tests:       1 failed, 115 skipped, 9380 passed, 9496 total
Snapshots:   26 passed, 26 total
Time:        384.283s
Ran all test suites.

Environment :
	  
[root@e0fd41b0f935 babel]# npx envinfo
npx: installed 1 in 9.201s

  System:
    OS: Linux 4.4 CentOS Linux 7 (AltArch)
    CPU: (1) ppc64 unknown
    Memory: 895.75 MB / 1.98 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v8.15.1/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
	
	
[root@e0fd41b0f935 babel]# ./node_modules/.bin/babel --version
7.2.3 (@babel/core 7.4.0)

**Comment by nicolo-ribaudo** [comment]
Confirmed: https://travis-ci.org/babel/babel/jobs/523099628

**Comment by sunil1783** [comment]
Deleted the file  "babel/packages/babel-preset-env/test/fixtures/corejs3/entry-chromeandroid/output.mjs" 
and Then run all the test cases successfully.

Is there any other solution to this problem?
