### ISSUE TITLE
Better comment attachment

### ISSUE THREAD

**Issue by sebmck** [babel/babel#989]

**Comment by mathieumg** [comment]
@sebmck Perhaps add the `cantfix` label here? Followed a 6-issue trail to this issue from https://github.com/babel/babel/issues/1904. Thanks!

**Comment by hzoo** [comment]
I think its part of https://github.com/babel/babel/issues/1486: "Attach comments in parser"

**Comment by mathieumg** [comment]
@hzoo Thanks! Hadn't found a trail from these issues to that one.
