### ISSUE TITLE
Weird behaviour of `@babel/plugin-transform-named-capturing-groups-regex`

### ISSUE THREAD

**Issue by FouadWahabi** [babel/babel#9904]
## Bug Report

**Current Behavior**
The plugin `@babel/plugin-transform-named-capturing-groups-regex` returns the same result for two different named groups when they are nested inside another matching group.

**Input Code**
```js
const line = /((?<res>[^\s()]+):(?<restype>[^\s]+) )?(?<name>[^\s()]+)(\((?<dim>[^\s()]+)\))/.exec('res:int solve(n)')
console.log(line.groups)
```

**Expected behavior**
This expected value of `line.groups` is :
```js
{
    dim: "n",
    name: "solve",
    res: "res",
    restype: "int",
}
```
But, I get this instead :
```js
{
    dim: "n",
    name: "solve",
    res: "res",
    restype: "res",
}
```
so as you see the values of `res` and `restype` are the same.

But, if I ignore the outer matching group : `(?:(?<res>[^\s()]+):(?<restype>[^\s]+) )?(?<name>[^\s()]+)(\((?<dim>[^\s()]+)\)` it works perfectly.

**Additional context**
Link to REPL : [REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBARgJxAawKZgEqoOaoB4wC8MA9ABRkD8APAqhAHwDaAegDoRkCUAugNRcAXFVr0oATwAOqZuwj8uMLpRFgAhgFsZrDtwVk2FGgBMAlhtm7eAtly4kAUKEiwAZqbypjWXAWLlKYRo6Rh1OayEREIlpS3kBJRUadS04vQEDI2ozCzD0rlt7BwcANzUEGFMwSQBXWGIAchDBKtgIEAAbEtQyMC4G4ud2jtQAOg6QbDJEFHQffFH8VGAyKtqoLlHsJBrJCC4ncGGxian3T28cBaWVtbrN7ZBd_aA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.4.3&externalPlugins=%40babel%2Fplugin-transform-named-capturing-groups-regex%407.4.2)

**Comment by nicolo-ribaudo** [comment]
@DmitrySoshnikov This looks like a bug with `regexp-tree`

**Comment by DmitrySoshnikov** [comment]
Will take a look.

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/issues/175 (`regexp-tree`: `v0.1.6`).
