### ISSUE TITLE
Typescript 3.4 `as const` not working for arrays

### ISSUE THREAD

**Issue by gcangussu** [babel/babel#9910]
## Bug Report

**Current Behavior**
Babel's typescript transform plugin doesn't support `as const` with arrays if those have variables or objects into them. The main Typescript implementation does support it.

**Input Code**
Here's a quick repo reproducing it: https://github.com/gcangussu/babel-typescript-const-error

But basically this is the problem:
```ts
function ok() {
  return ['oi', 42] as const; // Type 'readonly ["oi", 42]'
}

function notOk() {
  const a = 'oi';
  const b = 42;
  return [a, b] as const; // SyntaxError: Only literal values are allowed in constant contexts
}
```

**Expected behavior/code**

```ts
function notOk() {
  const a = 'oi';
  const b = 42;
  return [a, b] as const; // Type 'readonly ["oi", 42]'
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: ['@babel/preset-typescript'],
};
```

**Environment**
- Babel version: @babel/core 7.4.3, @babel/plugin-transform-typescript 7.4.0
- Node/npm version: node 11.14, yarn 1.15.2
- OS: Ubuntu 18.4
- How you are using Babel:`yarn babel index.ts`

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9869
