### ISSUE TITLE
@babel inside the bundle.js

### ISSUE THREAD

**Issue by Pagnito** [babel/babel#9913]
My bundle is too big for what seems to be no reason. I have the whole @babel inside my build and I can't figure out why and can't find anything similar on google.
![Screen Shot 2019-04-27 at 12 53 24 AM](https://user-images.githubusercontent.com/25378614/56844955-6243e080-6887-11e9-906b-d4c3bb8e5b2b.png)

{
  "name": "endeavor",
  "version": "1.0.0",
  "sideEffects": false,
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "NODE_ENV=production webpack -p --mode production",
    "start": "webpack-dev-server -d --mode development",
    "test": "jest --coverage"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "latest",
    "react": "latest",
    "react-calendar": "^2.18.1",
    "react-dom": "latest",
    "react-redux": "latest",
    "react-router-dom": "latest",
    "redux": "latest",
    "redux-thunk": "latest"
  },
  "devDependencies": {
    "@babel/core": "^7.1.5",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
    "compression-webpack-plugin": "^2.0.0",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "latest",
    "html-webpack-plugin": "latest",
    "mini-css-extract-plugin": "latest",
    "node-sass": "^4.11.0",
    "regenerator-runtime": "^0.13.2",
    "sass-loader": "^7.1.0",
    "webpack": "^4.30.0",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "latest",
    "webpack-dev-server": "latest"
  }
}

**Comment by nicolo-ribaudo** [comment]
You can run webpack with the ` --display-modules` and ` --display-reasons` options.

**Comment by Pagnito** [comment]
I ran --display-modules and --display-reasons and my best guesses this has something to do with it, but I still dont know what this means.
![Screen Shot 2019-04-27 at 12 16 02 PM](https://user-images.githubusercontent.com/25378614/56852239-a4e8d580-68e6-11e9-8f52-50106c284782.png)
![Screen Shot 2019-04-27 at 12 16 48 PM](https://user-images.githubusercontent.com/25378614/56852240-a6b29900-68e6-11e9-9864-670b70e82ef7.png)

**Comment by nicolo-ribaudo** [comment]
There should be somewhere in the pink text (on the left of each line) a reference to `@babel/types` _not_ coming (the light green title) from `@babel/types`.

**Comment by Pagnito** [comment]
There is no pink text on the left side. All the pink text is on the right side.

**Comment by Pagnito** [comment]
Not sure what you mean. The reference is in light green text or pink?

**Comment by Pagnito** [comment]
It seems redux was pulling it in :/ I cant understand why. My other project i using redux almost identically without this problem.

**Comment by nicolo-ribaudo** [comment]
That's strange. Which file of redux, specifically? 

(I'm closing this issue since it's not a big with Babel, nor something we can address)
