### ISSUE TITLE
@babel/plugin-transform-typescript strips vital JSDoc @typedef comments

### ISSUE THREAD

**Issue by lll000111** [babel/babel#9916]
## Bug Report

<br>

**EDIT:** See my comment https://github.com/babel/babel/issues/9916#issuecomment-489404010 below, there is a strange inconsistency depending on the location of `import` statements.

<br>

Running Babel with nothing but @babel/plugin-transform-typescript removes all but the very first of many JSDoc `@typedef` comments.

Those comments are for (and just above) Typescript type definitions (export type, export interface). When the Typescript types are stripped, so are the JSDoc comments. When I run `jsdoc3` to generate the HTML API docs this tool too runs Babel and this plugin in order to be able to parse the file. Obviously, the removal of the JSDoc is counterproductive especially in this use case.

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: 11.14
- jsdoc 3.5.5
- OS: Linux

- How you are using Babel: jsdoc3, config (jsdoc.json, babel section):

```
"babel": {
        "extensions": ["js","ts","jsx","tsx"],
        "presets": ["@babel/preset-typescript"],
        "plugins": [],
        "babelrc": false
    },
```

## Example

Here is an excerpt of the beginning of a file with many TS type definitions and there accompanying JSDoc comments.

```js
/**
 * This defines the creation status string constants for files
 * @global
 * @typedef {("new"|"exists")} FileCreationStatus
 */
export type FileCreationStatus = typeof CREATION_STATUS[keyof typeof CREATION_STATUS];

/**
 * @global
 * @typedef {Object} FileCreation
 * @property {SHA256Hash} hash - The SHA-256 hash of the contents of a versioned ONE object
 * @property {FileCreationStatus} status - A string constant showing whether the file
 * already existed or if it had to be created.
 */
export interface FileCreation {
    hash: SHA256Hash;
    status: FileCreationStatus;
}

/**
 * This defines the creation status string constants for objects.
 * @global
 * @typedef {FileCreationStatus} ObjectCreationStatus
 */
export type ObjectCreationStatus = FileCreationStatus;
```
After the transformation only this is left of these comments:

```js
/**
 * This defines the creation status string constants for files
 * @global
 * @typedef {("new"|"exists")} FileCreationStatus
 */
export type FileCreationStatus = typeof CREATION_STATUS[keyof typeof CREATION_STATUS];
```

Lots and lots of comments erased while there were nothing but Typescript type definitions encountered by the parser. Only when there was actual JS code again did the comment removal stop.

## Proposed solution

Don't delete any JSDoc (or any) comments. Comment removal should be left to the boolean "comment" Babel configuration property and whatever Babel code is following that instruction. If it is not set to `true` no comments should be removed, especially not JSDoc `@typedef` ones.

**Comment by lll000111** [comment]
Could someone give me a hint, please?

I tried changing the code myself. Whenever I try to do `node.replaceWith` it won't let me, telling me "[thisSameThing] expecte".

I want to either just replace the nodes with the comments, or with some other node (one that JSDoc ignores). I can't replace anything. And just commenting out various `remove()` statements worked at first, so after producing the JSDoc I put everything back into the original state because it was so easy and I need the removal for the regular build. But when I try it now that same simple commenting out leads to JSDoc parse errors. So now I have to actually replace those comments.

But how???

As I said, it just won't let me. How does `replaceWith` wort if it complains when I try using it???

Also, the docs, e.g. https://github.com/jamiebuilds/babel-docs/blob/master/en_US/authors/guides/transformation-operations.md always show some completely unexplained "`t.`" When I look in other code it's actually some function `t()`, and when I copy that function I need to also copy a bit of other stuff and strange includes like _interop[Something] around a require statement, which I also need to get form somewhere... Cold you please update the docs to explain that "`t.`"??

**Comment by nicolo-ribaudo** [comment]
How are you using `replaceWith`? You can't replace a node with a comment, you must replace a node with another node. Probably you want to copy the comments to another existing node.

`t()` is because you are looking at the compiled Babel code and it is a reference to `@babel/types`; I suggest reading the original source code in this repository.

**Comment by lll000111** [comment]
@nicolo-ribaudo I know, I read that much. I tried a few things and got an error that a "Declaration" was expected when I tried that in the `TSInterfaceDeclaration` (word from memory, something like that) node handler function (originally consisting only of `path.remove()`).

>  Probably you want to copy the comments to another existing node.

Well, thanks, I'm asking *how*... although I'm not completely clear what exactly is happening. Does the path.remove indeed remove those comments? Or is it a higher level effect?

I found "t()", it was compiled to `_core().types`.

**Comment by nicolo-ribaudo** [comment]
> Well, thanks, I'm asking how... although I'm not completely clear what exactly is happening. Does the path.remove indeed remove those comments?

Yes, because those comments are attached to the node you are removing. You can see it [here](https://astexplorer.net/#/gist/a1f604b8774283ac0dd16dca716dccb3/1b0693e7152218ea57d9f8b52e3c1982a6891240): they are attached to the `ExportNamedDeclaration` node.

You can use `t.inheritsComments(target, origin)` to copy the comments you want to keep to a different node.

Keep in mind that usually removing comments from a removed node is the right behavior, so you probably won't find a generic solution but you need to hard-core what needs to be kept. I'm curious: why do you need JSDoc comments in the compiled output? Developers/dev tools should use the original source code. Doesn't `jsdoc3` support TypeScript code?

> I found "t()", it was compiled to _core().types.

Yeah, which is `@babel/types` re-exported by `@babel/core`.

**Comment by pauloptimizely** [comment]
@lll000111 I ran into this exact issue today and I got around it by adding a semicolon to the end the interface.

For some reason `@babel/preset-typescript` respects semi-colons and will include the file if a semi-colon is present.

Here's quick example:

**interface.ts**

```js
/**
 * @global
 * @typedef {Object} FileCreation
 * @property {SHA256Hash} hash - The SHA-256 hash of the contents of a versioned ONE object
 * @property {FileCreationStatus} status - A string constant showing whether the file
 * already existed or if it had to be created.
 */
export interface FileCreation {
    hash: SHA256Hash;
    status: FileCreationStatus;
};
```

**Run babel**
`babel --extensions ".ts" src/ --out-dir dist/`

**dist/interface.js**

```js
/**
 * @global
 * @typedef {Object} FileCreation
 * @property {SHA256Hash} hash - The SHA-256 hash of the contents of a versioned ONE object
 * @property {FileCreationStatus} status - A string constant showing whether the file
 * already existed or if it had to be created.
 */
;
```

Also this is `babelrc` file that I used

**.babelrc**

```js
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": true } }],
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

I hope this works for you!!

**Comment by lll000111** [comment]
> I'm curious: why do you need JSDoc comments in the compiled output?

I'm explaining it in the second paragraph: I'm running jsdoc! To generate the HTML API docs! I **need** **exactly** the JSDoc!

**Comment by lll000111** [comment]
@nicolo-ribaudo I found something really weird, the issue is more complicated an nuanced. The comment removal is not always happening! If it was so simple as you show in the parser, the comment belong to the parsed statement so it's removed, then it would be a reliable outcome, but it isn't.

[Here is a Babel Repl example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=OQVwzgpgBGAuBOBLAxrYBuAUJg9AKj0yjygAEBbAewBMQAbCIvHbRcgB0vligG9l4EAIawIAWQhgwQgOYQAQuAC-UAGbxK5KMAB0OnOUnS5AWgBG4DNnyFiZWAE92EahFV8AYiAB2qRJW8VAAUNckRIACVJSjoANwgAYTMmFggAD05uKEdnKBDNcIgosBj4pIAeABUAPigAXigAClihOhAIAH4ALihKqAAfPNDCgBlEAGsIKuqASnra2MpEaixcAiZ7Jxc3Tx8_AODhyIgAKwhUJJTMdMyeHOh8sOOzi7N6psEhEu9uqCFvBxzOoLJYrazrOyke6udy8ADyZhesBUlXgQmQ40Q3hkj0KCJOVxuXB4WNE8FU6OgqPRmOxuMg-OmfCIUFZ7COEB69KmNSwrNZghKcU5QwKxyFZTM0z5_MESK5HKiSKSWCU4NsJChWxhfHx52RUAAgnQ6ABlCCwWAMaiEjLE7JbI0m82W61Mhq8FptEWVAA0MFgInAPWAqnoqkQJpcwBUg14n2-PR8428lAA7t5_XAg2AQ3L9dGlKsbBstc4dfDEfqVMazRarS5TYHYOBbbcoMgAnAnXXXY3m-B3rwWayPABVEYeACSIxGAFEACIhsN0CNR6jAX0jqAROcAKTnCUqi7zpwLG8wKi-Ha7sGLOF6EQAmju52I4QA1KcAOQA4r0AAk5ygBI4QXYCRh_YD5DnEY4QAdUwTtvG7CQpFkBRBwaARhFENDjEwsBGhmLAgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.4.4&externalPlugins=%40babel%2Fplugin-transform-typescript%407.4.4) 

Try removing the last line. With that line all comments above are gone as reported as my original problem. When that line is not there, all the comments are there! It is the 2nd real code line, if it was the first one I would understand, but why does the comment removal above hinge on that line?

It's not generalizable easily, the real file of course has a lot more lines (of real code), and I have files where all comments are removed and files where they are all still present in the output.
