### ISSUE TITLE
Offer (browser) ESM distributions for proposed replacements to @babel/polyfill

### ISSUE THREAD

**Issue by brettz9** [babel/babel#9917]
## Feature Request

**Is your feature request related to a problem? Please describe.**

`@babel/polyfill` has been deprecated in favor of core-js and regenerator-runtime, but neither of these offer an ESM distribution built for the browser, so I'm forced to do my own building now even for applications such as demos where I wanted to avoid polluting my repo with such.

**Describe the solution you'd like**

Working with core-js and regenerator-runtime so they may offer such builds to continue meeting the needs of @babel/polyfill users.

**Describe alternatives you've considered**

Building: This, besides being a hassle to have to do for every consuming project, is an obstacle for rapid debugging, and deters one from use of new ES features and quick development.

**Teachability, Documentation, Adoption, Migration Strategy**

This will ease the migration to core-js and regenerator-runtime for projects which don't need or wish to do their own building. Just as prominent projects provide pre-built binaries, I think these highly important polyfills deserve their own pre-built modules.

**Comment by nicolo-ribaudo** [comment]
This feature request should be discussed in the `core-js` and `regenerator` repositories.

**Comment by brettz9** [comment]
https://github.com/zloirock/core-js/issues/385 and https://github.com/facebook/regenerator/issues/302
