### ISSUE TITLE
SyntaxError: Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by dandv** [babel/babel#9918]
Filing this as a close duplicate of #9299 because that issue is locked, and with the release of Node v12, the createRequireFromPath boilerplate has become more [widespread](http://2ality.com/2019/04/nodejs-esm-impl.html#importing-commonjs-from-esm), and it involves `import.meta.url`:

```js
import {createRequireFromPath as createRequire} from 'module';
import {fileURLToPath as fromURL} from 'url';
const require = createRequire(fromURL(import.meta.url));
```

As a Babel end-user, I don't know how to work around the `SyntaxError: Cannot use 'import.meta' outside a module`, and leaving that issue open might allow someone more knowledgeable to offer a solution.

<sub>I personally find it mildly infuriating when conversations are locked without any spam or abuse problems, because nether I nor others can add anything that might help each other. Sometimes the "final word" from the core team is less than intelligible to those new to the topic.</sub>

**Comment by nicolo-ribaudo** [comment]
Is that error thrown by node or by Babel? What is your config? Are you using `node --experimental-modules`?

<details>
<summary>OT - Locking issues</summary>

I understand you point of view, but I believe locking old closed issues is better for us maintainers and our users.

1. This repository generates a really high number of notifications: often it's not possible to handle all of them. If someone comments on an hold issue, there are high chances that we'll forget about it. On the other end, new opened issues are always in the first page on GitHub so, even if we momentarily ignore it, it's easier to reply later.

2. People often replied something like "I have a similar problem", without giving any other information. By opening a new issue, they are forced to fill the template.


</details>

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue since the needed information has not been provided.

**Comment by natuprog** [comment]
`import CampElec from "newscript.js";

origen = [2,-3,0];
destino = [1,5,-6];
carga = 6*Math.pow(10,-6);
campo = CampElec(origen, destino, carga);
console.log("Campo Electrico: ");
console.log(campo[0], " en el eje x");
console.log(campo[1], " en el eje y");
console.log(campo[2], " en el eje z");`

it makes me the error: 
man.js:2 Uncaught SyntaxError: Cannot use import statement outside a module

and i want to import the export: 

`export function CampElec(origen, destino, carga){
    vector = vector(origen,destino);
    modulo = Math.sqrt(Math.pow(vector[0],2) + Math.pow(vector[1],2) + Math.pow(vector[2],2));
    unitario = moduloVector(vector);
    CampElec =[0,0,0];
    CampElec[0] = k*(carga/Math.pow(modulo, 2))*unitario[0];
    CampElec[1] = k*(carga/Math.pow(modulo, 2))*unitario[1];
    CampElec[2] = k*(carga/Math.pow(modulo, 2))*unitario[2];
    return CampElec;
}`

**Comment by nicolo-ribaudo** [comment]
That error isn't thrown by Babel. Babel throws `'import' and 'export' may appear only with 'sourceType: "module"'`

**Comment by natuprog** [comment]
maybe the error can be that i havent put the export as default export?
