### ISSUE TITLE
IE 11 plugin-transform-runtime causes forof iteration errors

### ISSUE THREAD

**Issue by Cerlancism** [babel/babel#9919]
## Bug Report

**Current Behavior**
With `plugin-transform-runtime` causes `Object doesn't support property or method 'Symbol(Symbol.iterator)_4.d7pjr549xf3'` in IE 11 when using `for of` from `function*` generators. `for await` with `async function*` works fine though.

**Input Code**
```js
function* generator()
{
    yield 1;
}

for (let iterator of generator())
{
    console.log(iterator);
}
```

**Expected behavior/code**
logs `1`

**Babel Configuration (.babelrc, package.json, cli command)**
<details>
 <summary>
 package.json 
</summary>

```js
{
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@orange-games/phaser-input": "^2.0.5",
    "@types/parcel-env": "^0.0.0",
    "parcel-bundler": "^1.12.3",
    "typescript": "^3.3.3333"
  },
  "dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "phaser-ce": "^2.12.0"
  }
}
```

</details>

<details>
 <summary>
.babelrc
</summary>

```js
{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
    ]
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "ie": "11"
        }
      }
    ]
  ]
}
```

</details>

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: v10.14.1
- OS: Windows 10
- How you are using Babel: With ParcelJS

**Possible Solution**
Remove "@babel/plugin-transform-runtime" or turn off regenerator of "@babel/plugin-transform-runtime" in `.babelrc`.
```js
"@babel/plugin-transform-runtime",
{
    "regenerator": false,
}
```

**Comment by JLHwung** [comment]
Closing it as duplicates of #7597.
