### ISSUE TITLE
@babel/plugin-proposal-object-rest-spread does not properly support `false`

### ISSUE THREAD

**Issue by arasmussen** [babel/babel#9923]
## Bug Report

**Current Behavior**
Using the object rest spread with an expression that evaluates to false throws a runtime error:  `Uncaught TypeError: Invalid attempt to spread non-iterable instance`. 

This does not match the behavior of Node v10 or Chrome latest, or what @ljharb says is correct on [TC39 object rest spread proposal](https://github.com/tc39/proposal-object-rest-spread/issues/45):

> Yes, it should mirror Object.assign.
> In other words, your first example must be equivalent to const vocalAnimal = Object.assign({}, animal, animal.species === 'cat' && {purr: 'meow'}, animal.species === 'dog' && {bark: 'woof'}); - and Object.assign will treat all primitives (like undefined) as the same as {} - in other words, this works just fine as-is.

Even using options `{loose: true, useBuiltIns: true}` does not fix the problem.

**Input Code**
```
var shouldAddBar = false;
var foo = {
  ...shouldAddBar && {
    bar: true,
  },
};
```

**Expected behavior/code**
No runtime error, `foo = {};`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ],
  "presets": [
    "@babel/preset-env"
  ]
}
```

**Environment**
- Babel version(s): 7.4.3
- Node/npm version: Node 10.15.3/npm 6.4.1
- OS: macOS 10.14.4

**Possible Solution**
`_toConsumableArray` should return `{}` if `false` is passed in, rather than throwing an error. But this might break other plugins, so I'm not completely sure.

**Comment by nicolo-ribaudo** [comment]
Are you sure that the error is thrown by that line? Babel doesn't use `_toConsumableArray` for object spread.

**Comment by arasmussen** [comment]
@nicolo-ribaudo My mistake, I thought I was using object rest spread, but was actually doing an array rest spread. Thanks for your help, and sorry for the trouble.

![image](https://media0.giphy.com/media/9Wuo275eRE2EU/giphy.gif)
