### ISSUE TITLE
Core-js incorrectly required for transform-runtime

### ISSUE THREAD

**Issue by Sawtaytoes** [babel/babel#9925]
## Bug Report

**Current Behavior**
When using `@babel/plugin-transform-runtime`, I'm seeing a couple errors show up on transpilation:
```log
ERROR in ./src/logic/temporaryWhitelistEpic.js
Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.replace' in 'D:\Projects\Companies\InsCyt\inscyt-safe-browsing\src\logic'
 @ ./src/logic/temporaryWhitelistEpic.js 1:0-44
 @ ./src/entries/background.js

ERROR in ./src/logic/transformBlocklistEpic.js
Module not found: Error: Can't resolve 'core-js/modules/es6.regexp.split' in 'D:\Projects\Companies\InsCyt\inscyt-safe-browsing\src\logic'
 @ ./src/logic/transformBlocklistEpic.js 1:0-42
 @ ./src/entries/background.js
```

I used to be able to compile no problem, but started seeing these errors tonight.

Looking through the docs, the `corejs` prop defaults to `false` so these errors shouldn't be showing up.

As far as I understand it, `string.prototype.replace` has supported regular expressions since ES5. The other error seems nonsensical because I'm calling `.split` on an array and no where else in the entire codebase.

**Input Code**
```js
url
.replace(
  /^.*\/\/(.*)\/.*\/?$/,
  '$1',
)
```

```js
blocklist
.split('\n')
```

```browserslistrc
last 2 Chrome versions
last 2 Edge versions
last 2 Firefox versions
```

**Expected behavior/code**
I expect the code to compile without requiring core-js unless I've explicitly stated it.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  plugins: [
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-transform-runtime',
  ],
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
        useBuiltIns: 'usage',
      },
    ],
    '@babel/preset-react',
  ],
}
```

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: 12.1.0
- OS: Windows 10
- Monorepo: No
- How you are using Babel: Webpack loader

**Possible Solution**
One way I've gotten around this is to remove `@babel/plugin-transform-runtime` altogether and set `useBuiltIns: false`.

**Comment by nicolo-ribaudo** [comment]
It _is_ explicitly stated: that's what `useBuiltIns` in preset-env means.

**Comment by Sawtaytoes** [comment]
I think I was expecting it to look at `.browserslistrc` which it does not.
