### ISSUE TITLE
Error: Cannot find module '@babel/plugin-runtime'

### ISSUE THREAD

**Issue by topCoding** [babel/babel#9928]
"@babel/core": "^7.4.4",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.4.4",
    "@babel/runtime-corejs2": "^7.4.4",
    "@babel/runtime-corejs3": "^7.4.4",
    "@loadable/babel-plugin": "^5.7.2",
  "@babel/cli": "^7.4.3",
    "@babel/generator": "^7.4.4",
    "@babel/node": "^7.2.2",
    "@babel/plugin-transform-runtime": "^7.4.4",
![image](https://user-images.githubusercontent.com/27414779/56948007-5e52df80-6b61-11e9-86f4-29bfbb72fdb1.png)
![image](https://user-images.githubusercontent.com/27414779/56948019-690d7480-6b61-11e9-94eb-a15095316c9e.png)

**Comment by nicolo-ribaudo** [comment]
`@babel/runtime` isn't a plugin. It's a time package which you should put in your dependencies when using `@babel/transform-runime`.

**Comment by TopCoding** [comment]
![image](https://user-images.githubusercontent.com/27414779/56948711-8e9b7d80-6b63-11e9-904a-2b96fe7e3153.png)
I think his document says so. I think he means that the development environment uses @babel/plugin-transform-runtime and the production environment uses @babel/runtime. I am not sure if this means
@nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
Yes, but you only run Babel plugins during development: they are not executed at runtime in your app.

Probably it would e clearer if we change "production dependency" to "runtime dependency" in the docs.
