### ISSUE TITLE
Function name inference: computed properties and Symbol properties

### ISSUE THREAD

**Issue by getify** [babel/babel#993]
```js
var o = {
  ["foo"](){},
  [Symbol.for("foo")](){}
}

console.log( o.foo.name );
console.log( o[Symbol.for("foo")].name );
```

These [should print](https://twitter.com/ziyunfei/status/575136680115445760) out `"foo"` and `"[foo]"` respectively, but [currently babel prints out](http://babeljs.io/repl/#?experimental=false&playground=false&evaluate=true&loose=false&spec=true&code=var%20o%20%3D%20%7B%0A%20%20%5B%22foo%22%5D()%7B%7D%2C%0A%20%20%5BSymbol.for(%22foo%22)%5D()%7B%7D%0A%7D%0A%0Aconsole.log(%20o.foo.name%20)%3B%0Aconsole.log(%20o%5BSymbol.for(%22foo%22)%5D.name%20)%3B) empty strings.

**Comment by zloirock** [comment]
How do you propose to implement it? :)

**Comment by sebmck** [comment]
The first one can be handled by the second one cannot.

**Comment by zloirock** [comment]
@sebmck the first case is not typical and very strange - why use a computed property, if the name is known in advance?

**Comment by sebmck** [comment]
@zloirock Yeah I know, it can still be handled though.

**Comment by getify** [comment]
@zloirock was simplifying... consider:

```js
var fname = "foo";

var o = {
   [ fname.toUpperCase() ]: function() { }
};

o.FOO.name;
```

**Comment by getify** [comment]
> the second one cannot.

It could be handled, at least partially, with `eval(..)`, right?

```js
var fn = eval("function " + fname.toString() + "(..) { .. }");
```

Of course, you'd have to filter out non-identifier characters. But then, this approach would also let you handle cases like this which you also don't yet cover:

```js
var o = {
  "foo bar"() { }
}

o["foo bar"].name;  // "foo bar"
```

**Comment by getify** [comment]
the point is not perfect parity (where it's not possible), but similar to perf optimizations, best effort and, critically, something > nothing.

**Comment by sebmck** [comment]
@getify That's not practical at all. Terrible performance and it still doesn't get you `"[foo]"` since `[` and `]` are obviously not valid identifier characters.

**Comment by sebmck** [comment]
Literals are now inferred as of 4.7.9, thanks!

**Comment by getify** [comment]
:)
