### ISSUE TITLE
@babel/plugin-proposal-object-rest-spread should be deprecated

### ISSUE THREAD

**Issue by GrosSacASac** [babel/babel#9933]
## Bug Report

**Current Behavior**
@babel/plugin-proposal-object-rest-spread is not marked as deprecated

**Expected behavior/code**
@babel/plugin-proposal-object-rest-spread should be deprecated since it is already included in @babel/preset-env and is no longer just a proposal

**Environment**
- Babel version(s): 7+

**Possible Solution**
Add a note here https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

**Comment by nicolo-ribaudo** [comment]
We are not deprecating any of the individual transform packages, since many people use them directly to be able to specify the options more granurarly.
