### ISSUE TITLE
[Bug] Using super in async method

### ISSUE THREAD

**Issue by orlov-vo** [babel/babel#9935]
## Bug Report

**Current Behavior**
I have error ```RangeError: Maximum call stack size exceeded``` when I used a `super` in my async method

**Input Code**
[REPL](https://babeljs.io/repl/#?babili=false&browsers=Chrome%20%3E%3D%2060%2C%20Safari%20%3E%3D%2011%2C%20iOS%20%3E%3D%2010.3%2C%20Firefox%20%3E%3D%2055%2C%20Edge%20%3E%3D%2016&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECyCeBhcVoFMAeAXNA7AJjAEKRrKQwDeAUNNJPLsNCAPZj4CiuWAllvAAUASmg06dLAAteEAHQB3NACMI_NNAC89BWH7RpsuWw4B1FWpwiA3LQmH5AJzQAHVo6xyIaLIlYBbFzBcIQdFC3U5YACgkOFbCWgIAFcXNEdjdi4efiF4uwBfagKgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.4.4&externalPlugins=)

```js
class MyClass extends BaseClass {
  async loadEntity() {
    this.website = await this.loadWebsite();
    this.report.setCompany(this.website.company);
    super.loadEntity();
  }
}
```

**Expected behavior/code**
It should work without looping

```js
class MyClass extends BaseClass {
  loadEntity() {
    var _this = this,
        _superprop_callLoadEntity = function _superprop_callLoadEntity() {
      return _superprop_callLoadEntity(...arguments); // <= HERE I HAVE LOOPING :(
    };

    return _asyncToGenerator(function* () {
      _this.website = yield _this.loadWebsite();

      _this.report.setCompany(_this.website.company);

      _superprop_callLoadEntity();
    })();
  }

}
```

**Comment by nicolo-ribaudo** [comment]
This is probably impossible to transpile without also transpiling classes. If your targets supported arguments rest/spread, that could would have been transpiled to this:

```js
class MyClass extends BaseClass {
  loadEntity() {
    var _this = this,
        _superprop_callLoadEntity = (...args) =>   super.loadEntity(...args);

    return _asyncToGenerator(function* () {
      _this.website = yield _this.loadWebsite();

      _this.report.setCompany(_this.website.company);

      _superprop_callLoadEntity();
    })();
  }

}
```

Unfortunatly `(...args) =>   super.loadEntity(...args)` doesn't work in some of your targets: for this reason we have to transpile it to a normal function, but then we can't correctly transpie the `super` reference.

If you add `"include": ["transform-classes"]` to your `preset-env` options, it should correctly work.

**Comment by nicolo-ribaudo** [comment]
Oh I might have a fix
