### ISSUE TITLE
@babel/runtime uses `module.exports` breaking my ES6 application

### ISSUE THREAD

**Issue by SukantPal** [babel/babel#9937]
## Bug Report

**Current Behavior**
My web application uses `@babel/runtime`. I am using the `typeof` operator in one my ES6 modules (bundled with webpack). However babel transforms that into something like `_typeof3` in `@babel/runtime/helpers/typeof.js`.

The `typeof.js` file in your project uses `module.exports`, which is causing a read-only error in the browser. In addition, webpack complains (warns) that an `export default` wasn't found in `typeof.js`.

**Expected behavior/code**
It should work transparently.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
comments: false,
presets: [
  [
    '@babel/preset-env',
    {
      targets: '>0.25%, not dead'
    }
  ],
  '@babel/preset-flow'
],
plugins: [
  '@babel/plugin-transform-runtime',
  '@babel/plugin-proposal-export-default-from'
]
```

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: Node 10
- OS: Ubuntu 19
- How you are using Babel: webpack `babel-loader`

**Possible Solution**
I think you're going to do a huge refactor and change `module.exports` to `export default` everywhere.

**Comment by loganfsmyth** [comment]
Can you see if setting [`sourceType`](https://babeljs.io/docs/en/options#sourcetype) to `unambiguous` resolves your problem?

**Comment by SukantPal** [comment]
Yes @loganfsmyth, your solution works.

Thank You!

P.S. Where do you get your knowledge from?

**Comment by SukantPal** [comment]
No. The problem was solved by making Babel not run on the `@babel/runtime` package.

```
{
  exclude: path.resolve(__dirname, 'node_modules/@babel/runtime')
}
```
