### ISSUE TITLE
Error importing CommonJS module that works with --experimental-modules

### ISSUE THREAD

**Issue by dandv** [babel/babel#9938]
## Bug Report

**Current Behavior**
I'm trying to use the default import with [node-influx](https://github.com/node-influx/node-influx/). This works with `node --experimental-modules`, but not with Babel and the `transform-modules-commonjs` plugin.

**Input Code**

**import-influx.mjs**
```js
import InfluxDB from 'influx';
console.log(InfluxDB.FieldType.STRING);  // 2
```

**Expected behavior/code**
```sh
$ node --experimental-modules import-influx.mjs (node:3614) ExperimentalWarning: The ESM module loader is experimental.
2
$ ./node_modules/.bin/babel-node ./import-influx.mjs 
/home/dandv/prg/v12/a/import-influx.mjs:7
console.log(_influx.default.FieldType.STRING); // 2
                            ^

TypeError: Cannot read property 'FieldType' of undefined
```

**Babel Configuration (babel.config.js)**

```js
module.exports = {
  plugins: [
    '@babel/plugin-transform-modules-commonjs',
  ],
};
```

**Environment**
- Babel version(s): 7.4.4
- Node 12/npm  6.9.0
- OS: Ubuntu 18
- Monorepo: no
- How you are using Babel: `cli` (babel-node)

**Comment by nicolo-ribaudo** [comment]
That module doesn't have a default export; only named imports: https://github.com/node-influx/node-influx/blob/master/src/index.ts.

With node you can only import it as default because node doesn't know about Babel/TypeScript/Webpack way of handling transpiled es modules.

**Comment by dandv** [comment]
I found the same problem with other modules, e.g. [faast.js](https://github.com/faastjs/faast.js/issues/36).

Is there a TypeScript transpilation setting that these modules could enable?

**Comment by nicolo-ribaudo** [comment]
They could add an entry-point `as-default.js` like this:

```js
import * as mod from "./index.js";
export default mod;
```

By doing so, the original entry point still uses named exports, but if you import `faast.js/as-default.js` you can use the default import as you would do in node when importing `faast.js`.
