### ISSUE TITLE
CLI: -rc flag

### ISSUE THREAD

**Issue by fundon** [babel/babel#994]
CLI supports `-rc`, likes `--config` flag.

```bash
$ babel -rc .babelrc
```

**Comment by sebmck** [comment]
There's already support for `.babelrc`.

**Comment by fundon** [comment]
Thanks.

Great work! :+1: 
The `mocha --compilers js:babel/register` also works.

**Comment by fundon** [comment]
@sebmck 

Another Question:
I tested, the `gulp-babel` is not working with this.

**Comment by sebmck** [comment]
@fundon Yes it's currently not supported by any of the plugins.
