### ISSUE TITLE
[preset-env] corejs option doesn't compatible with exclude option

### ISSUE THREAD

**Issue by lili21** [babel/babel#9948]
## Bug Report

**Current Behavior**
 
Error Message:

![image](https://user-images.githubusercontent.com/4456380/57209731-47523880-700c-11e9-97f2-34df5255f4d7.png)

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'usage',
        corejs: 3,
        exclude: ['es6.promise']
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): v7.4.4
- Node/npm version: node 10/npm 6
- OS: OSX 10.14.3
- Monorepo: no
- How you are using Babel: rollup-plugin-babel

**Possible Solution**

**Additional context/Screenshots**

Change `corejs` options from `3` to `2` will fix the error message.

**Comment by nicolo-ribaudo** [comment]
You can find the polyfill names at https://github.com/zloirock/core-js/tree/master/packages/core-js/modules: it should be `es.promise`.

**Comment by lili21** [comment]
Thanks. The error message is kind of misleading.
