### ISSUE TITLE
Incorrect location for ClassMethod with Decorator

### ISSUE THREAD

**Issue by RoniSegal** [babel/babel#9949]
## Bug Report

**Current Behavior**
Typescript class method with decorator gets an incorrect line number.
In the sample bellow function ```bar``` is at line 11 with leading decorator in line 10, the method  line number considered to be 10.
But function ```baz```  (without decorator) gets the right line number (15)

**Input Code**:

```js
export function logMethod(
    target: Object,
    propertyName: string,
    propertyDesciptor: PropertyDescriptor): PropertyDescriptor {
    console.log("Logged");
    return propertyDesciptor;
};

class Foo {
    @logMethod
    private bar(): void {
        console.log( `bar`);
    }

    private baz(): void {
        console.log( `baz`);
    }
}

```
**Parsing Output**:
Bar;
```js
"type": "ClassMethod",
      "start": 224,
      "end": 298,
      "loc": {
        "start": {
          "line": 10,
          "column": 4
        },
        "end": {
          "line": 13,
          "column": 5
        }
      }
}
```
Baz;
```js
{
      "type": "ClassMethod",
      "start": 306,
      "end": 364,
      "loc": {
        "start": {
          "line": 15,
          "column": 4
        },
        "end": {
          "line": 17,
          "column": 5
        }
      }
}
```

**Expected behavior/code**
Function foo line number should be 11

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    // parse in strict mode and allow module declarations
    sourceType: 'module',
    plugins: [["decorators", {decoratorsBeforeExport: true}], "*"]
}
```

**Environment**
- Babel version(s): 7.3.2
- Node/npm version: Node 10.11.0/npm 6.4.1
- OS: Windows 10
- Monorepo: no
- How you are using Babel: api (require "@babel/parser" and call "parse")

**Comment by RoniSegal** [comment]
Any updates on this?

**Comment by loganfsmyth** [comment]
I would consider this expected (though understandably surprising) behavior. AST node start/end locations generally fully enclose all of the ranges of their child nodes, and since the decorators of a class method are child nodes, the start location of the method needs to be before the decorators.

**Comment by RoniSegal** [comment]
I wouldn't consider this as expected behavior, if you transpile the code into js with source maps, the source location of the method will be one line after the decorators

**Comment by loganfsmyth** [comment]
If you'd like to create a specific example where the sourcemap is off, we can certainly see if there is a way to fix it, but the AST position is unlikely to change.

**Comment by nicolo-ribaudo** [comment]
Closing as the AST position is expected (https://github.com/babel/babel/issues/9949#issuecomment-491607771), and there is on example for source maps.
