### ISSUE TITLE
Merchandise updates?

### ISSUE THREAD

**Issue by ahtee** [babel/babel#9952]
Will the Babel store be updated with non-seasonal merch soon? Would love to nerd-out and support this project, as well as promote it! 🙌 ❤️ 😍

**Comment by nicolo-ribaudo** [comment]
I'm not sure who in the team manages the Babel store, but I'm :100: on this

**Comment by ahtee** [comment]
thank you @nicolo-ribaudo ! sorry to open an issue on this!

**Comment by hzoo** [comment]
I set it up a long time ago, can certainly look into it again but hasn't been a big priority sorry! We'll probably post on twitter or slack when we do though!
