### ISSUE TITLE
Browserslist versions incorrectly evaluated

### ISSUE THREAD

**Issue by somebody32** [babel/babel#9954]
## Bug Report

**Current Behavior**
When using `defaults, Chrome >= 41` as browserslist config line babel stops including IE 11 support, but calling `npx browserslist` or visiting [the site](https://browserl.ist/?q=defaults%2C+Chrome+%3E%3D+41) shows that IE 11 is in the list.

Adding IE 11 explicitly to the config fixes the issue, but that is not a solution

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl#?babili=false&browsers=defaults%2C%20Chrome%20%3E%3D%2041&build=&builtIns=usage&spec=false&loose=false&code_lz=MYewdgzgLgBAhgXgIwG4BQpKwEYIEwbjQzQBOMCMABgCQDecAvvdo1WoZCADYCmAdNxABzABTYAlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.4.4&externalPlugins=

```js
const str = `${1}${2}`;
```

**Expected behavior/code**
template string should be transpiled, like with just `defaults` in browserslist:

```js
var str = "".concat(1, 2);
```

**Babel Configuration (.babelrc, package.json, cli command)**

```browserlist.rc
defaults
Chrome >= 41
```

**Comment by nicolo-ribaudo** [comment]
`defaults` is not supported yet, see https://github.com/babel/babel/pull/8897

**Comment by somebody32** [comment]
oh, thanks @nicolo-ribaudo. So just with `defaults` being there now, babel just transpiles for "all" browsers?

**Comment by nicolo-ribaudo** [comment]
I think that Babel currently ignores it and just targets Chrome 41.

**Comment by somebody32** [comment]
I thought more about the case when `browserslist` field having only `defaults` and nothing more. I believe I'm not the only one who thought that this will limit babel from including support for dead browsers :) 
I'll close this issue then, thanks!
