### ISSUE TITLE
"Unterminated template" thrown with CSS source map inside template literal

### ISSUE THREAD

**Issue by morewry** [babel/babel#9956]
## Bug Report

**Current Behavior**
I'm attempting to transpile a Svelte single file component (built as a custom element) with Babel. The Svelte compiler's `dev` mode includes a source map for CSS. When this option is turned on, it outputs an inline source map with the styles. This is all inside of a template literal.

That itself is valid code and it runs as expected in Chrome. When this is passed to Babel, however, to do further transformations, Babel errors with `Unterminated template`. We found that the following stopped Babel's error:

1. Removing the newline before the source map.
2. Removing the `/` (note: invalid CSS).

**Input Code**
- [REPL link to reproduction](https://babeljs.io/repl/#?babili=false&browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=FACgZgrgdgxgLgSwPZRAGwDQAIHYG7YCmAlFgN5Z5YC8WaAdDAE6ECGchAomoQLaFQ4IBMQDcleqwDOAT1g0sARnF56UpjAUByAPQ6tWANRZ0SGO2RR6ACyRS4WAD6OsWtGdZpb9rcTUAHNAQhLQAuXwBtAAYAXSNXUIBmAFYAdgAmAE4dILxCFndWABN6ACspAH4pKAR_PKZqRS1xQgUGAHNCOG4-ATgpACEZABVWdoA5Vn5hYmiYlvp_VhZBcaQiwnoEKCl8uAHCMCQWEAIsEgBfYhAiswh-QWwtKWZauF9RUEhYRBQTUjIwAAkFoILssPYmAh4M1gMDvvBLFgoEgkP4QACLnCgQjflAsMUigB9dzmPEgQg8B5wbBgBA8bBBKCEbAwJBoe5QVnWZYA4FAym9QT0IlEqR5NAcIn8OCsBSAoGK0mhchYOkMujbFlYNkc3hcnU8phYLGKi6fIFY-HQRF_JjQcBQPmKlhwCBMfFgVBiYFWnE2vFYABGaFYUAA1kSkEHSoR4BjyPzXe78QB5GNxuCMFjsQggKAQNBoH2W7G4pH2qBEzxoR1SZ04nb0I5MTisGDWECVkt-8t_BBSIl91BwazbdoN5MerBwGT-QhIMAzsdQdo0ai0LTD2Gl60_JFSVhgQhElFwImEACOEE8IFY2CDk66KYJWAAhLQ5RVg-ufyq5R-tBBk4LggHeWAAGQQTOc4Lkucobpu0axjCpDODB86Lq-iGuNuPZlgGSKsP485QEUICykwnQ0si6wkImiqUdRkgkQIRQAMJjmg5Eohs-F7ra-LbLsTBCExXTYLx2phh2xwNuJWbCXsBwtnmUnYDJtjGuhBZFvx_r7n8Gyyh2-Z0Q2UmLMsfRrBs9AsLwSB5Jx9I8eZFq9oRfyCtS-ZTPRCpAlO-K3DA9x9NmbAcD0vlQP5-nDjOhAAB5CEU7CsE-brTqF4XCswUWEMMKVwLZebpbKCVefiUhLDAeZZS-HCpSABgfL6BGGfi7BwEwZkbBpcC9QgQYQBw-CeBAAX8ggS6nJNrQbsihbFrRdkOU5hAAIJDVCo0cHeu0jWNJAWgKaDgpZuxwDtw37XmPV7SdE0cqdHUCYGHauSsFJUn0jXTltTBMKwMjNkwSC8L9QpZl93FlfWHmdYJEJdESFWsBRJXYBjDYY9oBjGBjZ2zSYzVZvjgFYLjSWpfQ-O0MT70GSjcBIO07Q8ESMChlIUjQ9Skn-dgbMczwDY-RFPPSFIAAyA5wBEouc6035aISBgqloG15FoMR-fw-k8A4YXA303OQ_4KB9J8H0HmjpsrOebK8FbzKCCALtu_9DFAo75te9bggKIH7twEjwJsjsDhFAgokyBbrtB_0CgRPM2JR_YWAsFI7J5MS_gQ7wA6LVgAAKRcl_ZhC52geQYhaxtYBA_gVSeLzWIQRSFl3ChgJ4uwWpnDhBtssertzNZBu24ZSKn6d-ygWcrBsTCT0W08wLP89D0vDhgByUjWOvaCb9vtBp7bLOBh3Xc90SLdtwmgWkyAb6P7mYodnfPBFA2QIfylLfbuv8FC9SmmdIKNc85dyJIXSGVdRwCHAIfawJZSy7mvkRIoxIV75BPmfR0T4yL4PMBvGeUhFhgk7F6KqXU1SoOfvyYeqMBAEIoQoZkAB3LAABlLoDdsRAluL7IEeg1Rx3sKyGswZDjHEIAAVVbrmNU1UpD8jEToAkZFm7KI4DqS2yd1GKiBFwrirQbhx1nInb2ghKE8FXKOf-i9o4GKTmHBQsd442KMWoMcYAhDoMVNdbm7onY-LDp7QxYcgkAL0XmUOEUAAkSSgl-kVGY-kFjR5kXHOwre9iBDtCccGMeeSyGnwoX42agTBEaPEUgg0KB6puNsSnayui25FGkUWepWijwcCYEotuqiuqUKwMMMcc9eCgx1KwMEhA-kQggEGXY14-idNzJQ-g9ANGZJ4CYPBa8Kln0KY4tBoiXFZxOTPBQRz8mz0WGiQRJigSvzfLsNhNyCk2GkJ7KeM9iDOL9gCredTXmaKwDstQSAsDtBvEwIoBJ2isGEg4bYdIaj6PcGiYxrzPlVm-Y8wk_zyFb1iaaM0_ILhYH2RYrx1jEl2PoA44paCr6mPMSYA-1CHlnLZf_HlR8-VPPRNcdB6TAHt2_iA3utB-4XUIBHLBfwpUgBSQ2V-KTwZjGpP_bVartUMpkEEys1YizqqSfQIMciWBEiOUE7VYAQbtGpIsS19MrEyGwNq-AyVHVWuNZwlaHKgTaoGfgo5zZjhtlMoSe1bFSGgvDBK5miVHLQGdtEvoUT3F9BFssaiGlYBaQbCwigzrdX5qwCgaUSBM3YFrRsSESBvUEgCZGxNxoaW0CZVmFJHLK2uoilDBSxbZJMB9PycRKAACy9bg48lYjsdtgzlytG2MEBAnhV35GGbmegWADjmAWdO_pHahnxLmWS7eS7SI4HxCweo4JjirxMNsZkxo6RMHsMQM9tLWjAJ7jWqA87M3XsqQU2Rqld2XpGUSvF8b7lErAqQagAA-URLDuFRirM23qraFC1ozcKGZ6JuzNnpIM4Qg5hxBNfk2muBGTWXMYy2sG_hqEgGhThtjzG0nnEVZc8RnAiidDmeCAAtK05OtLpDUyYxDGQvcEC8H4LHXMaBvUaMhY5LOQRwyUhkASOecoc6FgcFhOUOTx5rk3YgTwA5xw6bNTWfMhAuG4fRop1taSNF9voNq4jC6HAXwXpaKdioI1ryjS2WNnYkNdoeXQlG-GlO5raTjLo7YVwTl9q_ALGrRGuYtYVq1fGlNBLKzq4dwpyLGRy-OSLipxHDFTAAEVTMtIsNaxo1qQcaFgYApDYG2DzCAtmZNh0C0kkw-1kSEF7mzJZhca75DyBIuKaAISyg4BUP9JjqsVcI727NwonUuupMGoskDqt-vlOaalabqpYBmYZ9GXqMvJ2wIZljL85pvmq8a_-xqIl9EoZxo-X2YmQKA1zNVVWzv9sDV6h7Z1KVA69REX7cRaDgKVc9-h9nofVrRHiEbD77AyW1AVT-Q7Ba0XPFeG8aAUmKGwPA_wp5_L1l9iwpY4S-0hzCQHJHZ0Qn-0EGDj2fbmv84hv4OetAyeWAhwrue6EyCPeYXvLAKSQ5I5m_KDR9O-gql0pgfzcBkrm5WhgIRkKqccA0ZzqQKpOfc_4CNjRUrzeon8PbkxZ4LzXk8H7pnofWdJPZxooMC6igqhDGGSMyFMwYnt0soIx4YAyB5oskxwXM0qjToHxUx2ZDF5iKXoENrVIJpIUwSv1fov19Xk3_zKBybm481gWdxEQAC9F3m4O35B9S7u53kqWBK_EAzyY8RhB6gyFHOOQTux_PJrd8GUMEYowZnjLPjRxrbe9LNBypuOYijGflQPAn_JfXW4UGi6nGjvzP9gAkpHHP1fYBAL9l6U0aGmGgUioWqVq92UEjOIeLObOHqfq2OhAMgVeeu4B1uCBSBCgeAC0QKlybyc02qce0ARQ6BMQpABB8eJB80r0sSeBhybAV-pAb2J4xqJOjwWAv2FKGiVwGi7u6uHKBq8SLyUCxQ1-M49oBOLo0A5qtYBBtqJ4DqZ0F2VawcvaOYUopuHsD-_qHKDG_g5O9ACk_8uh-h1gMgRQIMHAziShtWWYtYcM5hyCKuS8BhhaXQQKkCNKlI4IIBYaVqGhsMQhmCoBc0ThTY2wBGkE0E1W_hWwpA0Rl2EUCAgRJGWaw-QgfajaehquLhVEEkNaWRzhmkckkCQqnYqa_IEuIu4-SOA-1k1RaRRsXQfCEo0Uf0ggFor8s4mES4AAEsMLOrLDFBslTKCCQpil3L4L7Lwi0VwG0aFjqLzHPCVGxHPH0QMUMcHCAcPPaPAMcEwvii3PkIEUCCvpQj1DlrwjyLcFwiABQI5BsFrGiAIAYFcB4Q7lHMyPAF3OxMmvsSYi2CYCwr9g-suAODNmoO4ENF3MCqcSxKRBxFxORLCdqlIJCRwMQTjpwSYukkCI9MdBwJxGGJ0BxL8Y9Gzo2txAAGoLSSQebUnUGXKnERBknR644LZcL0kQJcEO5JJpatp_GKh8kyAURTIiziGxLIlCmcL-5vEaJJIoAUSwQ9KQYprCZaJtadYQi2CFhIqnEKY8Aor6JswEg4KcB5CCDyz2ACD5AVA6YsIIYKAilgm-qb5KywRxDoROmUIuk3pSBunzhslpzuF2mb5UJQ5ErNYujPjTgJgYa4EsJjwpQhyhmJnJSphgCkoqk0GvypnvhLSSaKBxGhm1RBD1TCAkLJTYCFmQKWiykmJJLXQCmQqbTAwIA4ICDBjGbv71SjZLjBBYA8hzyu7cln7Mw6AABUEIGgOgncRYSANgcAvA22nQn6uYSKQYxm0xlI-ieAiQ9A6Q9AigWA45OgGcuu6opcAAROoDADOZSO4AuUuZeVfIlLTuoQkTLtbg2FgcaLVGGCLFENgKiUgDRHAOzjOOkBysFFhiqK-WoQ1Jcn-fiLQJLB7NeUsFAJeRKVEGAiVCAJeT0feUgBgAAAUAA6-IWAWFNZwF8xqFQg15kJ1FOmYFuFLUfq9AcUhsNZcA6QbFDFb4zFrysJmgtAKIaINZ8apIFgCptFtIWS2AAALNgOkNgAAGyJCxJSUeDkhIXyUaiqVYCAVYCJCZBpJz5KiwUvbSyqb9Q1zOKjgQw8LcJYCcDAx7GXmhGUKmHmEqIoBaa0rHDbykxIJTYbJcLyZexZJIpcLBDWDrpYAAAGPlFhrAIYhAKo-OiV-ReIQlZoFlQIvAVl9CKRFErhNERRk6lySkokZVuRNEel2iE6Wly65EjVcAUQLV8JIAjVtFXVbEPVkJIs1ZOmxE3VclEF5lDu_gxVKMaqHYRJXcrIX51Vc0C1q4XcnF8UuBISGMFE4FHFXFb0rylKloBVCAfuaI1eSAl1AeDuCeoyqWPmwpDWX0q4zir8r1uWwKX1PVGFWJVKo5mCiU3ZeYKSuwaAYAPqSSru0N2wWBQQbcDYTcFAR1BMJoCgKSru_BDZlIYAgW10mNMN6uNAwBGir8WgR1Bg2wKBruZBSS8NjmT8lN_kWgQs_ARNruW13F1KUF0Z-IqN_kJoyq0sfMWAhFc55wqUKxzR25sxMMfOe8OxbMfUXl_8UghxfUkZxOpx2AFACkmVUyfixQSAXCAASqiA4BcKNtHNTqyPBUOB-Q1UeCeMHszp4NgBEJeUdZeaQaGsYarh9SEQUU2IYbgTVUIF5TkUWqCRTlHZVZwTpgHc4XTbgciY2VHXTTWTiIwgDRgkEU7tCHCk0dGCJPnLdE9BwPzP_NBV7T7eFuktRMiP5AKdBciagclNzRIQXU0UdQbNNCYunQIoLRza8SbrnejszGFPYJDBsf0PTIcFqPhbOe4JJuKHLZedgBLe4JFhOVObeXSJSCUNYIucudaRYb3BubLZKK0LufuYeceaeZHOeVktHgoNedOYfdxI-WgM-cjJ9A7f4dHp7CtYFD-dTAgHgGpTjJA4ZbHHgMZbRcZR1TA3gOBbxag4kEBZCeg1gxA3gMpRCJCYZXAIQ7RXg3AMkKg1Q0QyBYpXzdlALf5rNQA4VE2fA2pQoPRfhfA3lYKbA1w3MTw5A3w8IpAzhShUI5ebw7Ekg4IzDPhbRaIx1QoH-WWbEvA0eZIwo9IyIxo5A4oAYSVOxJPioVRamCHZ4H_cJXxbQGow1DWfA4kPI75Lo3gKI7RVo4Jjo0oxKc43Y3VA4zpvA4pS4zmm4x48Q2E2hb4zxaEwE-2EE_ipCf494647EyxckKo4E8cfA1k9o64zIzRZCfE2k-Exk8JUbaJbRBJaNbtINSBcZd7f5JvVRV_UUJJqGDar_VpTgiSDpZYA0ygxIjwNHtgJkOpVWWpWZY4-I4wIsZMBzbQJee07LGlZSNYyYtpWSIM_A8ZReWM1gAABxKVVmJBHP6NoPzMyyLNXntMWN4hWM8XswqzcyLGWJoPYCeWWO_3LWd2hGeC9PEjSXkiaP6WECHOKDgWEPpCKCpCXMHmi1SC3Pv1DgIBH1rPdNrMyD1pwCbNRZ9Mgu7OwPguHOpAqVVlRDpBaX1OeNfM-1fPtOSYNb0iiPbMyWoB0sjMQvgWKDQNYCEOJDpDwuzN31IsovLPtPtbZasuSWEsDMKlOOku8s0OGVZAit1O9RDOGXNP8CtMrPovcSSZRwEY9NyvAsKucvEPKtVkTMCtKVRCaXmv9M7OyUpM2tYDpDGWEOKWKXUuiuKXXN8wSttOGscSd4Qy_3OtEuKuQOEMHO8snOevYCJAZA0tau0WEO6uED6tMte6HidBsvyuutWt0MevpB4M-uZAXOivJBBvItC2Sthuzo1wFs5vRuWsfM0MJsqVqtKVqUauvIcP1shsGtH34u4nFscsfP8s9tYD8vGVHOdUeEFVoAsNIg2VQxSS84-GOWm3smuXuV9TfMmFmEX0gYBVcJBVzwhWdxhXBwRVzxRWgKxWjgJXJVnsZTpWZXiHZWhF8PW0O5FWPWBilVjpNWlrVU7B7B1Ux0cPjqlqSWtUzuoP-ujXIfwNwPiP9VkQfOIOQnLvofdWYcAU4f1Ykv4MjWvJjUDXweTVIfEeQP8tONkcfN4OeOsd0dwBOtEe0dMeoOKWcdxvYMgVofUcYfCcziCcMd8cEMifcdCdQMizJCKfMeQMqcye4d5PyfSdcEFUzUgdIjzU8gbXdI6igNJ1rUmfEn0AAurQ-EnEvNcxIsfPgUnuWBWN_O2c_N52Afk23XXUBf3XrtGTPU3DZZvV5Y-GfURffW4G_UcO-e82E4oyg3APg143Q2w0oGM2I25jI1NH62dxLOuBs05UefbY35CY9q018FCIZeQ0E1NG0BY0k1xkgEU1IL8DU34ite4r025dtm5itRdeEBlejec3q4GHFfHXBEmBaB2c9e1f9c5dQAI1DcHQLc_Nld2eTe4reePPFjo4MMvhFe9CZGHfC1T2LFYAABiYbUtHAZEc8W5N9c9it0cytexatoiGt84WtoasJR8Jt5tltWwUAn6axssCgiVAAPPYDIDwOhvA2QLHCWaDKECGGYOGFiBOQAMQQj1oaCEB94kTjgKJm2yzUAYyhBjWlkcs6DlAoCiALU_pdDUBjRgCSZHOiDTy7BqXKWIEABS6QAAWgABpC8ABerAAA6pkBAAAJKlBIBS-yzsRC8zKy_JRoDK9IAICi9LmnwADiAAijeD0WbXAEGOxIr1IIr1AOMHgEUJL6UBL7OggKmBdAb0b0GGbxb1bzb0L0UOr9L0GIkJSTIAAJrpCUlS-m9ZATbG-UkTa29qWy8yCK9HMwCJCi-nyW9oCpi8CZBcJFDG91xBigbtBl-3dQBlyUmxWi_G_JRq-y-i_-Ci_a_hji-2_tCyxS_JAwAhjJQQBlw9HjBRCEDa9oBlxoAj-K_sQDDhisDi9R-dAyBL8r_jBcJ--3fJCpgIADAjTG-ZClCsBS9SDtBgCUkj9lzsSZBS9FA9EXSi_DCD_D-j_G9m2tyH-lC79S8wApeigGAIr14Dt9O-yUbvrb0MDi9jeildoIr3ayQCV-a_GPslGsA59Z0mQHvkLzACG8N4X_WdFH1l5C9T4nAdAVP0yCKAigt3WKrP3n7sQtoCApAcv1X7tA0BGAxIFgJwFa9KSUgUXuQOsBR9eAfAnvorxgFwCEBjAqQVtGz7pBkozvRfhAGIGKAZ-DfH3gQNN7W9je93CASANKCKUjmssRIOMCkDh9TeEg-AQvyYF39MgrAqPpYJkHtAy4X_H_gMD_46CABQAkAWAI75d9hgiQAYFEDl4K9iByUEAb_3_6AC6gMAS3v4CDDpBkg1gIMO1nf4IAmB1ghAZwBL5l8K-vAW7lIFgFWDpBtg-wY4MQFcI8ATfNAOkHoFK9GBRzaoekEV7G9TBUfcXuMCl719G-vvL_pwAl5m0eQ2vfQWkIyENCYA8gxQQMGUGy9VB3QjQSby0FN9KSUQYgRdDEGGBbBUvP3pkCiB1DrBRg9IN_yKClBRhzg1wbHHcFRDvBoA8AV3wT4K8n-QvPAEGFoEIB9h0gxAS3x2FRAWhSQoMLLwUTYCNevA_gexEUB_9EhUQGAMX0KHQCthPwj4RkKQHbCT-ew0oJUImEKCigqQofukOcH38yhRQ5gcgLYEcDMBwIzXnLz4ECDVBOfcYNYFF6x8RheIsYbIKxFTCZhcw9QfgMWHW9ZecfCYbX1F7qCy4GIvAByJxFnDShKAywYcOOGnCh-c_UfuP1KAwi0ApfXEaPCYES9rAO_RIEL1-HN9uIi_YIcnzgCi9eEW0TIAvxgBQBUwigBgQMB4A9EBgEoqAKb3aB-8VhLQnIeXxeH5D7e7WKIO0EN4FCJhCiVIEUKMEmC1RS5TUWkOD6h8uRaAHPIr3T6KAog9vXgIoAwGuj4hvAIoFLz14IBTeCiW7pb14TJQeiZYisYMVu4DAyxs6KQKbyiANjTeMgZKI2PLHtZBimQbsUcxbFtiBgZtKsbLFrGyx6x3YhREOPbEyAhemQR-rDx0AI8keiVf2lii9J60Zw5VQ2mCWB7XELaIFE0DbSpwf5Dmb5E8EA3AqHhjwp4ECtAQ9pYAvao3fVnZ19ra1g65OIOiYCjph0HOEdEAH-PKoixRS5XQoiWmKI6YcStBICSHTVwrcHOQ9SOvBMWDq4aCpRY4qdUpTpJC6mgJuqXXWxdwK6-JGuK3X5rPjLyr4jAO5xQBWMG6QiJuqN3ImMNY64JDiqN0noVEmizE0bv_GQm3F10o9IJJhPKKKgCJPzFiU1CNpaEDuFXLicEhLqSS7O_EmSY2QoC7cx6_xCek9kwTT02YvAOepQg2DjEeGF0STO01ab3cj6u9LRKpitiiRXAAAAWnjdMdAVsLTOqDQDNAsA4iQoJNmdSQwsA7EdrOMBBKdxigcIC4BiB9B6ACeucd0PVFJ7-ByelPagKNDIg8AyglCMjMACAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.4.4&externalPlugins=)

```js
this.shadowRoot.innerHTML = `<style>div{display:block}
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZmllbGQuaHRtbCIsInNvdXJjZXMiOlsiZmllbGQuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOm9wdGlvbnMgdGFnPVwiZGxzLWZpZWxkXCIgLz5cblxuPHN0eWxlPlxuICBkaXYgeyBkaXNwbGF5OiBibG9jazsgfVxuPC9zdHlsZT5cblxuPGRpdiBjbGFzcz1cImZpZWxkXCI+XG4gIDxkaXYgY2xhc3M9XCJfZmllbGRMYWJlbExheW91dFwiPlxuICAgIDxkaXYgY2xhc3M9XCJmaWVsZExhYmVsXCI+XG4gICAgICA8c2xvdCBuYW1lPVwiZmllbGQtbGFiZWxcIj48L3Nsb3Q+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImZpZWxkT3B0aW9uYWxcIiBjbGFzczpvcHRpb25hbD5cbiAgICAgIE9wdGlvbmFsXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiZmllbGREZXRhaWxcIj5cbiAgICA8c2xvdCBuYW1lPVwiZmllbGQtZGV0YWlsXCI+PC9zbG90PlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImZpZWxkQ29udHJvbFwiPlxuICAgIDxzbG90IG5hbWU9XCJmaWVsZC1jb250cm9sXCI+PC9zbG90PlxuICAgIDxzbG90Pjwvc2xvdD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJmaWVsZE1lc3NhZ2VcIj5cbiAgICA8c2xvdCBuYW1lPVwiZmllbGQtbWVzc2FnZVwiPjwvc2xvdD5cbiAgPC9kaXY+XG48L2Rpdj5cblxuPHNjcmlwdD5cbiAgZXhwb3J0IGxldCB0aGVtZSA9ICcnO1xuICBleHBvcnQgbGV0IG9wdGlvbmFsID0gZmFsc2U7XG48L3NjcmlwdD5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFHRSxHQUFHLEFBQUMsQ0FBQyxBQUFDLE9BQU8sQ0FBRSxLQUFLLEFBQUUsQ0FBQyJ9 */</style>`;
```

![Screen Shot 2019-05-07 at 12 48 33 PM](https://user-images.githubusercontent.com/1043291/57328750-1aaf2700-70c7-11e9-8352-949b44c2923e.png)

**Expected behavior/code**
I expect this not to error.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  babelrc: false,
  extensions: ['.html', '.js', '.mjs', '.svelte'],
  include: ['**/*.html', '**/*.js', '**/*.mjs', '**/*.svelte'],
  exclude: ['node_modules/@babel/runtime/**'],
  plugins: [
    'transform-custom-element-classes',
    [
      '@babel/plugin-transform-runtime',
      {
        regenerator: false,
        useESModules: false
      }
    ]
  ],
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          // TODO: temporary
          chrome: '70',
          ie: '11'
        }
      }
    ]
  ],
  runtimeHelpers: true
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
7.4.3
- Node/npm version: [e.g. Node 8/npm 5]
node.js v10.15.0, npm 6.9.0
- OS: [e.g. OSX 10.13.4, Windows 10]
OSX 10.14.4
- Monorepo: [e.g. yes/no/Lerna]
Lerna
- How you are using Babel: [e.g. `cli`, `register`, `loader`] 
Lerna -> npm script -> Rollup -> https://github.com/rollup/rollup-plugin-babel

<details>
  <summary><b>Click for 2-level Babel version info</b></summary>
<pre>
├─┬ @babel/core@7.4.3
│ ├── @babel/code-frame@7.0.0
│ ├── @babel/generator@7.4.0
│ ├── @babel/helpers@7.4.3
│ ├── @babel/parser@7.4.3
│ ├── @babel/template@7.4.0
│ ├── @babel/traverse@7.4.3
│ ├── @babel/types@7.4.0
│ ├── convert-source-map@1.6.0
│ ├── debug@4.1.1
│ ├── json5@2.1.0
│ ├── lodash@4.17.11
│ ├── resolve@1.10.0
│ ├── semver@5.7.0
│ └── source-map@0.5.7
├─┬ @babel/plugin-transform-runtime@7.4.3
│ ├── @babel/helper-module-imports@7.0.0
│ ├── @babel/helper-plugin-utils@7.0.0
│ ├── resolve@1.10.0 deduped
│ └── semver@5.7.0 deduped
├─┬ @babel/polyfill@7.4.3
│ ├── core-js@2.6.5
│ └── regenerator-runtime@0.13.2
├─┬ @babel/preset-env@7.4.3
│ ├── @babel/helper-module-imports@7.0.0 deduped
│ ├── @babel/helper-plugin-utils@7.0.0 deduped
│ ├── @babel/plugin-proposal-async-generator-functions@7.2.0
│ ├── @babel/plugin-proposal-json-strings@7.2.0
│ ├── @babel/plugin-proposal-object-rest-spread@7.4.3
│ ├── @babel/plugin-proposal-optional-catch-binding@7.2.0
│ ├── @babel/plugin-proposal-unicode-property-regex@7.4.0
│ ├── @babel/plugin-syntax-async-generators@7.2.0
│ ├── @babel/plugin-syntax-json-strings@7.2.0
│ ├── @babel/plugin-syntax-object-rest-spread@7.2.0
│ ├── @babel/plugin-syntax-optional-catch-binding@7.2.0
│ ├── @babel/plugin-transform-arrow-functions@7.2.0
│ ├── @babel/plugin-transform-async-to-generator@7.4.0
│ ├── @babel/plugin-transform-block-scoped-functions@7.2.0
│ ├── @babel/plugin-transform-block-scoping@7.4.0
│ ├── @babel/plugin-transform-classes@7.4.3
│ ├── @babel/plugin-transform-computed-properties@7.2.0
│ ├── @babel/plugin-transform-destructuring@7.4.3
│ ├── @babel/plugin-transform-dotall-regex@7.4.3
│ ├── @babel/plugin-transform-duplicate-keys@7.2.0
│ ├── @babel/plugin-transform-exponentiation-operator@7.2.0
│ ├── @babel/plugin-transform-for-of@7.4.3
│ ├── @babel/plugin-transform-function-name@7.4.3
│ ├── @babel/plugin-transform-literals@7.2.0
│ ├── @babel/plugin-transform-member-expression-literals@7.2.0
│ ├── @babel/plugin-transform-modules-amd@7.2.0
│ ├── @babel/plugin-transform-modules-commonjs@7.4.3
│ ├── @babel/plugin-transform-modules-systemjs@7.4.0
│ ├── @babel/plugin-transform-modules-umd@7.2.0
│ ├── @babel/plugin-transform-named-capturing-groups-regex@7.4.2
│ ├── @babel/plugin-transform-new-target@7.4.0
│ ├── @babel/plugin-transform-object-super@7.2.0
│ ├── @babel/plugin-transform-parameters@7.4.3
│ ├── @babel/plugin-transform-property-literals@7.2.0
│ ├── @babel/plugin-transform-regenerator@7.4.3
│ ├── @babel/plugin-transform-reserved-words@7.2.0
│ ├── @babel/plugin-transform-shorthand-properties@7.2.0
│ ├── @babel/plugin-transform-spread@7.2.2
│ ├── @babel/plugin-transform-sticky-regex@7.2.0
│ ├── @babel/plugin-transform-template-literals@7.2.0
│ ├── @babel/plugin-transform-typeof-symbol@7.2.0
│ ├── @babel/plugin-transform-unicode-regex@7.4.3
│ ├── @babel/types@7.4.0 deduped
├─┬ babel-plugin-transform-custom-element-classes@0.1.0
</pre>
</details><br />

**Possible Solution**
Dunno.

**Additional context/Screenshots**
Simpler uses of CSS comments in template literals are fine, [see this very reduced similar case that isn't a source map](https://babeljs.io/repl#?babili=false&browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECyCeAhEB7YBraBvAUNawKAdhAC4BOArsKSuQBQCU2e-0pAFgJYQB0XRIgFNyACQAqsADLQAvNAAGAEy4A3bCogAHcPABc0AEaoMAXxwB6AFTQIKALZCCDx0VLQrFhQG5W580A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.4.4&externalPlugins=)

```js
this.innerHTML = `div {display: block}
/* some comment */`;
```

![Screen Shot 2019-05-07 at 12 48 39 PM](https://user-images.githubusercontent.com/1043291/57328772-2c90ca00-70c7-11e9-8ebf-110a43163aa0.png)

This is similar to https://github.com/babel/babel/issues/9790. Sounded different enough to me to file on its own, but do feel free to close if it's a duplicate.

<details>
  <summary><b>Previously filed as</b></summary>

https://github.com/rollup/rollup-plugin-babel/issues/307 
https://github.com/sveltejs/svelte/issues/2704

</details>

**Comment by majose1500** [comment]
In my case I can to resolve that error because I forget to put this symbol (`) in the end of the definition of my styled const, example:
`export const Image = styled.img`
  border: 1px solid #ddd;
  box-shadow: 0px 10px 14px rgba(0, 0, 0, .2);
  border-radius: 50%;
  height: auto;
  overflow: hidden;
  object-fit: cover;
  height: 75px;
  width: 75px;
``

**Comment by majose1500** [comment]
In my case I can to resolve that error because I forget to put this symbol (grave accent) in the end of the definition of my styled const, example:
export const Image = styled.img`
  border: 1px solid #ddd;
  box-shadow: 0px 10px 14px rgba(0, 0, 0, .2);
  border-radius: 50%;
  height: auto;
  overflow: hidden;
  object-fit: cover;
  height: 75px;
  width: 75px;
`
