### ISSUE TITLE
leadingComments drops last line comment before expression

### ISSUE THREAD

**Issue by ian-craig** [babel/babel#9957]
## Bug Report

**Current Behavior**
`leadingComments` is mising last line comment before expression when expression contains parens.

**Input Code**
https://astexplorer.net/#/gist/ff2da32a9fe6bf725c83b66adadc148d/6aa7b8c2421146443f11eaaa5937c5ff990a61fa

```js
let fun = () => {
    // one
    // two
    // three
    return (1);
}
```

Current AST (@babel/parser 7.3.3+)
```
{
  "type": "ReturnStatement",
  ...
  "leadingComments": [
    {
      "type": "CommentLine",
      "value": " one",
      ...
    },
    {
      "type": "CommentLine",
      "value": " two",
      ...
    }
  ]
}
```

**Expected behavior/code**
Expect that the `leadingComments` should have three comments, as there are three in the source code. @babel/parser 7.3.2 is correct and outputs the following 
```
{
  "type": "ReturnStatement",
  ...
  "leadingComments": [
    {
      "type": "CommentLine",
      "value": " one",
      ...
    },
    {
      "type": "CommentLine",
      "value": " two",
      ...
    },
    {
      "type": "CommentLine",
      "value": " three",
      ...
    }
  ]
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

Repros on AST Explorer which may be a more standard environment than I'm running.

```js
{
  "dependencies": {
    "@babel/generator": "7.4.4",
    "@babel/parser": "7.4.4",
    "@babel/template": "7.4.4",
    "@babel/traverse": "7.4.4",
    "@babel/types": "7.4.4",
  }
}
```

```ts
import { parse } from '@babel/parser';

parse(sourceText, {
    sourceType: 'module',
    strictMode: false,
    plugins: ['classProperties', 'typescript', 'decorators-legacy'],
});
```

**Environment**
- Babel version(s): @babel/parser 7.3.3+ (**Regression** since @babel/parser 7.3.2)
- Node/npm version: 10.15.1
- OS: Windows 10
- Monorepo: no
- How you are using Babel: plugin, or AST explorer repros the issue too (link above)

**Additional context/Screenshots**

This only seems to repro when the statement with leading comments has parens.

#### Example 1
The below works just fine
 ```js
let fun = () => {
    // one
    // two
    // three
    return 1;
}
```
The below drops comment `// three`
 ```js
let fun = () => {
    // one
    // two
    // three
    return (1);
}
```

#### Example 2
The below works just fine
 ```js
let fun = () => {
    // one
    // two
    // three
    if (!condition) {
       ...
    }
}
```
The below drops comment `// three`
 ```js
let fun = () => {
    // one
    // two
    // three
    if (!(condition1)) {
       ...
    }
}
```

**Comment by matthewrobertson** [comment]
this was caused by this commit https://github.com/babel/babel/pull/9463

**Comment by danez** [comment]
Thanks @matthewrobertson for pointing out which commit introduced the issue. Made it easy for me to find the issue.

Did you use `git bisect`?

**Comment by matthewrobertson** [comment]
Thanks for fixing this @danez !

I did use bisect to track down the regression: I added a unit test that repro'ed the problem, then wrote a 3 line shell script to build and run my test, and then I used `git bisect --run myscript.sh` to find the commit that introduced the regression: https://git-scm.com/docs/git-bisect#_bisect_run
