### ISSUE TITLE
react-constant-elements breaks with ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by natew** [babel/babel#9959]
## Bug Report

**Current Behavior**

I noticed in production mode I was getting undefined react elements, when using `@babel/plugin-transform-react-constant-elements`.

I'll need to come up with a repo as it's in a large project, but basically it seems the order is not proper in my bundle.

The only thing I noticed special about `Header` is its required by files A > B, and in B (required by A) it is undefined.

![image](https://user-images.githubusercontent.com/12100/57399290-d040af80-7185-11e9-91b9-e5262e6bb85d.png)

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: 10

**Comment by navigatorOpera** [comment]
I also encountered this question, although i add the 'allowMutablePropsOnTags' option that it still did not work, so i dropped this plugin. i hope there is a solution to make it well. thanks.

**Comment by JLHwung** [comment]
Could you offer a reproduction repo? It would help us narrow down the problem.
