### ISSUE TITLE
Only change browserslist defaults if no config file exists

### ISSUE THREAD

**Issue by danez** [babel/babel#9962]
https://github.com/babel/babel/pull/8897#issuecomment-490659840

> I guess the best solution would be to check ourself if there is a browserlist config in the fs if there are not targets specified. We could do this with `browserlist.findConfig(from)`. If we find one we do not change defaults. But that would also be a breaking change so I guess we would need to wait for v8. https://github.com/browserslist/browserslist/blob/master/node.js#L238

**Comment by taralx** [comment]
FYI it's "browserslist" and not "browserlist", which is why I did not originally find this one. :)

**Comment by JLHwung** [comment]
In Babel 8, `preset-env` (and other `targets` awared plugins) will defaults to `defaults, no ie 11`. 

Closing this issue as it has been fixed in #12989.
