### ISSUE TITLE
Incorrect destructuring compilation of `for (let [[x] = [1]] = [];;) {...}`

### ISSUE THREAD

**Issue by gkz** [babel/babel#9963]
## Bug Report

**Current Behavior**
`x` is not defined in the correct scope after transformation, and is not available in the for-loop body. Running the below code results in `ReferenceError: x is not defined`

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAlhC8EAYDcAoAZgewE4QBSkgG1CAPAXTgkIEYyL5CyloIAeCa5qAam4EoIAbxQQIAYwwA7AM4ZQAOmAYA5rhJ8UAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.4.4&externalPlugins=

```js
let i = 0;
for (let [[x] = [1]] = []; i < 1; i++) {
  console.log(x)
}
```

Current compilation:
```js
var i = 0;

for (function () {
  var _ref = [],
      _ref$ = _ref[0];
  _ref$ = _ref$ === void 0 ? [1] : _ref$;

  var _ref$2 = _slicedToArray(_ref$, 1),
      x = _ref$2[0]; // x is defined within this IIFE, so is not available below
}(); i < 1; i++) {
  console.log(x);
}
```

**Expected behavior/code**
`x` is defined so that it is available in the body of the for-loop. If we are to run the code, we should print `1`.

**Babel Configuration (.babelrc, package.json, cli command)/Enviroment**
- Whatever is the latest on the Babel repl (see link above)

**Comment by brianppoole** [comment]
I'm experiencing a similar issue that seems related. If not, please let me know and I'll open a new bug report.

Here's the original code
```JavaScript
let data = getDataArray();

let list = [];
for(let i = 0; i < data.length; i++){
    let entity = this.entities[data[i] - 1];
    if(entity) list.push(entity);
}

let scores = [];
for(let entity of list){
    let index = this.entities.indexOf(entity);
    if(!scores[index]) scores[index] = 0;
    scores[index ]++;
}
```

End up producing code that doesn't run:
```JavaScript
var c = []
for (var m = this.getArray(), f = 0, g; f < m.length; f++)
    g = this.entities[m[f] - 1],
    g && c.push(g);
for (var h = [], v = 0; v < (void 0).length; v++) {
    var _ = (void 0)[v]
        , x = this.entities.indexOf(_);
    h[x] || (h[x] = 0),
    h[x]++
}
```

If I manually change both `(void 0)`s to `c` then the code runs.

However, if I rearrange how the variables are declared:
```JavaScript
let data = getDataArray();

let list = [];
let scores = [];

for(let i = 0; i < data.length; i++){
    let entity = this.entities[data[i] - 1];
    if(entity) list.push(entity);
}

for(let entity of list){
    let index = this.entities.indexOf(entity);
    if(!scores[index]) scores[index] = 0;
    scores[index ]++;
}
```

Then it does work:
```JS
for (var p = [], m = [], f = getDataArray(), g = 0, h; g < f.length; g++)
    h = this.entities[f[g] - 1],
    h && m.push(h);
for (var v = 0, _ = m; v < _.length; v++) {
    var x = _[v]
        , y = this.entities.indexOf(x);
    p[y] || (p[y] = 0),
    p[y]++
}
```

**Comment by Zzzen** [comment]
🤔Interesting. I'm gonna work on it.
