### ISSUE TITLE
@babel/plugin-proposal-decorators decoratorsBeforeExport option does not work

### ISSUE THREAD

**Issue by Arichy** [babel/babel#9964]
## Bug Report

**Current Behavior**
I'm using create-react-app and @babel/plugin-proposal-decorators, and I want to write decorators before export keyword , so I add "decoratorsBeforeExport":true to .babelrc, but it throw an error.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": [
        "react-app"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-decorators",
            {
                "decoratorsBeforeExport": true
            }
        ]
    ]
}
```

**Environment**
- Babel version(s): 7.x.x
- Node/npm version: node v11.13.0
- OS: OSX 10.14.4

- How you are using Babel: create-react-app

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/29599723/57501752-4b879a00-731b-11e9-91ce-8c1557c7c6f8.png)

**Comment by nicolo-ribaudo** [comment]
The official decorator proposals doesn't allow decorators before exports anymore.

Anyway, that option should still work in Babel. For some reasons that config files isn't being picked up, I think. Could you try using `babel.config.js` instad of `.babelrc`?

**Comment by sacridias** [comment]
Removing this feature basically ruins decorators :(
