### ISSUE TITLE
Should split out shorthand properties in CSS.

### ISSUE THREAD

**Issue by adjenks** [babel/babel#9967]
Some properties have a lot of trouble being handled in shorthand form with functions inside of them. For example: ["calc() does not work when used in the flex property"](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/850091/)
(I realise that link is broken but it exists in the bug list and can be found if you search for it: https://www.bing.com/search?q=calc%28%29+does+not+work+when+used+in+the+flex+property)

And example is that this doesn't work:
```
flex: calc(1) 1 150px;
```

but this does:
```
flex-grow: calc(1);
flex-shrink: 1;
flex-basis: auto;
```

So splitting them out for compatibility with Edge and other struggling browsers should be useful.

Also... Does babel even transform CSS? If not, then where should I put this?

**Comment by nicolo-ribaudo** [comment]
Nope, Babel is only for JavaScript. You can take a look at PostCSS (https://github.com/postcss/postcss), which is similar to Babel but for CSS.

**Comment by adjenks** [comment]
@nicolo-ribaudo Thank you good sir!
