### ISSUE TITLE
TypeScript: Function params have this param and spread param would lost the first param. 

### ISSUE THREAD

**Issue by XGHeaven** [babel/babel#9969]
## Bug Report

**Current Behavior**
When function params have this annotation and spread params, the first params would lost.

Original code:
```ts
function A(this: any, ...args: any[]) {
  console.log(this, args)
}
```

After compile:
```js
function A() {
  for (var _len = arguments.length, args = new Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
    args[_key - 1] = arguments[_key];
  }

  console.log(this, args);
}
```

if you write `A(1, 2, 3)`.The first argument `1` would be lost in console output.

**Expected behavior/code**

Should output follow code after compile:
```js
function A() {
  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }

  console.log(this, args);
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-typescript", "@babel/preset-env"]
}
```

**Environment**
- Babel version(s): v7.4.4
- @babel/preset-typescript: 7.3.3
- Node/npm version: Node v11.15.0/Yarn 1.15.2
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**
Maybe not. But I pleasure to help find the solution.

**Comment by nicolo-ribaudo** [comment]
Could you try changing the order of the presets?

**Comment by XGHeaven** [comment]
@nicolo-ribaudo It works. 

BTW, I have a question. Why `[typescript, env]` order no errors occurs?

**Comment by nicolo-ribaudo** [comment]
Because if typescript is transformed first, then `...args`'s index is 0. Otherwise, it's 1: preset-env doesn't know that `this` is a special parameter and will be removed.
