### ISSUE TITLE
Thoughts on implementing support for V8's strong mode

### ISSUE THREAD

**Issue by creatorrr** [babel/babel#997]
Hey all,

What does the project think about implementing supporting for V8's strong mode and maybe even a gradual type system ala Soundscript?

Announced [here](https://developers.google.com/v8/experiments) and detailed proposal [here](https://docs.google.com/document/d/1Qk0qC4s_XNCLemj42FqfsRLp49nDQMZ1y7fwf5YjaI4/mobilebasic)

**Comment by sebmck** [comment]
The type annotations and all syntax proposed can already be parsed and
output.

On Wednesday, 11 March 2015, Diwank Singh Tomer <notifications@github.com>
wrote:

> Hey all,
>
> What does the project think about implementing supporting for V8's strong
> mode and maybe even a gradual type system ala Soundscript?
>
> Announced here <https://developers.google.com/v8/experiments> and
> detailed proposal here
> <https://docs.google.com/document/d/1Qk0qC4s_XNCLemj42FqfsRLp49nDQMZ1y7fwf5YjaI4/mobilebasic>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/997>.
>


-- 
Sebastian McKenzie

**Comment by monsanto** [comment]
It'd be cool to have validation transformers that raise `SyntaxError` on `==`/`!=` and `var`. I would find this useful regardless of the success of strong mode.

**Comment by sebmck** [comment]
Sure, would be extremely possible with the transformer API I have planned
for the next major.

On Wednesday, 11 March 2015, Christopher Monsanto <notifications@github.com>
wrote:

> It'd be cool to have validation transformers that raise SyntaxError on ==/
> != and var. I would find this useful regardless of the success of strong
> mode.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/997#issuecomment-78224054>.
>


-- 
Sebastian McKenzie
