### ISSUE TITLE
Private fields in decorated classes are not supported yet

### ISSUE THREAD

**Issue by pnewell** [babel/babel#9973]
Are there plans to support private fields in decorated classes? (or is there a plugin for this). I can't seem to find much info on the issue:

```
SyntaxError: /Users/paulnewell/Development/my-app/src/components/my-app.js: Private fields in decorated classes are not supported yet.
  33 |   @property({type: String}) appTitle = '';
  34 | 
> 35 |   @property({type: String}) #page = '';
     |   ^
  36 | 
  37 |   @property({type: Boolean}) #snackbarOpened = false;
```

**Comment by nicolo-ribaudo** [comment]
Currently not. We will definetly implement them (I'm currently trying to fully understand the new proposal), but it will take some time.

**Comment by hardikpthv** [comment]
I think this will indeed be nice to support. We currently can not use it.

**Comment by nicolo-ribaudo** [comment]
Note that this plugin doesn't reflect the current proposal anymore

**Comment by nicolo-ribaudo** [comment]
I'm closing this PR, since the current non-legacy decorators implementation will be removed in Babel 8 because it's completely different from the current decorators proposal.
