### ISSUE TITLE
babel-node takes arguments as options

### ISSUE THREAD

**Issue by marsaud** [babel/babel#999]
The babel-node help says like node's help : 
```sh
Usage: babel-node [options] [ -e script | script.js ] [arguments]
```
With a myScript.js containing only "console.log(process.argv)", on the following call, -p is taken as a babel-node option instead of a script argument :
```sh
$ babel-node myScript.js -p abc
ReferenceError: abc is not defined
```
Where node outputs :
```sh
$ node myScript.js -p abc
[ 'node',
  '/home/fabrice.marsaud/Documents/myScript.js',
  '-p',
  'abc' ]
```

**Comment by neVERberleRfellerER** [comment]
Double dash: `babel-node -- script.js ...` should work

**Comment by sebmck** [comment]
Thanks @neVERberleRfellerER!
