### ISSUE TITLE
"useBuiltIns": "entry" is importing all polyfills

### ISSUE THREAD

**Issue by Juriy** [babel/babel#9990]
## Bug Report

**Current Behavior**
While transpiling the file with an option "useBuiltIns" set to "entry", all polyfills are included, instead of the ones actually used by the code. 

**Input Code**

.babelrc configuration:

```
{
  "presets": [
    ["@babel/env", {
      "useBuiltIns": "entry",
      "corejs": 3
    }]
  ]
}
```

Original file
```js
import 'core-js/stable';
import 'regenerator-runtime/runtime';

function f() {
  return Promise.resolve('data');
}
```

Transpiled file:

```
"use strict";

require("core-js/modules/es.symbol");

require("core-js/modules/es.symbol.description");

require("core-js/modules/es.symbol.async-iterator");

require("core-js/modules/es.symbol.has-instance");

require("core-js/modules/es.symbol.is-concat-spreadable");

require("core-js/modules/es.symbol.iterator");

require("core-js/modules/es.symbol.match");

require("core-js/modules/es.symbol.replace");

require("core-js/modules/es.symbol.search");

require("core-js/modules/es.symbol.species");

/* AROUND 100 imports omited */

require("core-js/modules/web.url");

require("core-js/modules/web.url.to-json");

require("core-js/modules/web.url-search-params");

require("regenerator-runtime/runtime");

function f() {
  return Promise.resolve('data');
}
```

**Expected behavior/code**
Expected to see only the imports that are actually required by the code. For example, following is the result of the same configuration but with  "useBuiltIns" set to "usage"

```js
"use strict";

require("core-js/modules/es.object.to-string");

require("core-js/modules/es.promise");

require("regenerator-runtime/runtime");

function f() {
  return Promise.resolve('data');
}
```

**Environment**
- Babel version: 7.4.4
- Node/npm version: 11.6.0 NPM 6.5.0-next.0
- OS: OSX 10.12.6
- Monorepo: not applicable
- How you are using Babel: CLI

**Comment by nicolo-ribaudo** [comment]
That's exactly what `usage` is for. `entry` loads all the polyfills not supported by your target browsers.

**Comment by Juriy** [comment]
@nicolo-ribaudo thanks, now I got it. I misread the docs, it states "based on environment", so "entry" doesn't take into the account the actual code, only the target platform.
