### ISSUE TITLE
In IE11, NodeLists cannot be spread.

### ISSUE THREAD

**Issue by ZainlessBrombie** [babel/babel#9993]
## Bug Report
Cause of Issue is known, will do a pull request.

**Current Behavior**
In IE11, NodeLists cannot be spread.
"Invalid attempt to spread non-iterable instance"

**Input Code**
```js
[...document.querySelectorAll('.filter-item')]
```

**Expected behavior/code**
The NodeList is turned into an Array.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@babel/preset-react", "@babel/preset-env"]
}
```
```js
{
"devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/polyfill": "^7.2.5",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "^8.0.5",
    "babel-preset-vue": "^2.0.2"
}
"dependencies": {
    "babel-polyfill": "^6.26.0"
}
}
```

**Environment**
- Babel version(s): see above
- Node/npm version: node v10.14.1 / npm 6.4.1
- OS: Ubuntu 18.04
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**
In _toConsumableArray, add `"[object NodeList]" === Object.prototype.toString.call(iter)` additionally to `"[object Arguments]" === Object.prototype.toString.call(iter)`. In Chrome, the method will return `[object Arguments]`, but in IE11 (Windows 8.1) it will return `[object NodeList]`.
_Edit: removed redundant quotes_

**Comment by loganfsmyth** [comment]
If you are loading `@babel/polyfill` then `NodeList` objects should pass the `Symbol.iterator in Object(iter)` check on the line above that string check. The polyfill should be making Nodelists iterable.

**Comment by ZainlessBrombie** [comment]
In that case my apoplogies. I will investigate my setup to see why this is not happening.

**Comment by ZainlessBrombie** [comment]
@loganfsmyth I can't find the code that is supposed to do this, as nowhere in the repo there is a corresponding reference to neither NodeList nor the methods that would return a NoteList. Can you give me a pointer?

**Comment by loganfsmyth** [comment]
Should be set up in https://github.com/zloirock/core-js/blob/v2/modules/web.dom.iterable.js#L55 for core-js@2.x and https://github.com/zloirock/core-js/blob/d42976f7af29832cddc04051cb7032057d17ab74/packages/core-js/modules/web.dom-collections.iterator.js#L18 for `core-js@3.x`

**Comment by ZainlessBrombie** [comment]
@loganfsmyth oh yes of course it is in corejs, sillyme

**Comment by ZainlessBrombie** [comment]
Symbol.iterator: `jscomp_symbol_Symbol.iterator_0`
ITERATOR when defining: `Symbol(Symbol.iterator)_2.68wrbuupnw2`
Uuuuh

**Comment by ZainlessBrombie** [comment]
See pull request for resolution.
The project included an import to default-recaptcha which came with its own variant of polyfill. This caused a clash and mixed polyfills.

**Comment by tbell511** [comment]
Having the same problem in Edge 17.  Are there any short term solutions for this? I can't seem to find the pull request.  Thanks!

**Comment by ZainlessBrombie** [comment]
@tbell511 Hey there. Yes there are multiple solutions. The pull request has been closed, but here are your options:
A) use Array.from to convert the nodelist. This will avoid the critical call to toConsumableArray.
B) Modify babel as follows: https://github.com/babel/babel/pull/9994/commits/f81228fa962bedf0c9ce9fe24660f7a66b204f59
C) Remove the offending dependency that overwrites the polyfill (recaptcha in my case) and replace it by an appropriate vue/react ready variant. This is the best option, as the others may leave you with other problems of this sort further down the line.

Hope this helps, cheers! :)

**Comment by tbell511** [comment]
@ZainlessBrombie thanks for the reply.  Array.from fixed the issue. Thanks for the recommendation!

Any suggestions on how I could find what dependency is causing the issue? Thanks so much!

**Comment by ZainlessBrombie** [comment]
@tbell511 Yes:
the first thing to do after reintroducing the error for debugging is to visit the page in chrome, optimally the build artifact version of the page.
In the console under sources, check all js files for the precise error message, in my case a missing exlamation mark was the giveaway that it did not come from the desired polyfill.
If You have not found the dependency that way / the error message came from Your js bundle, the next step is to --beautify it using uglifyjs so that you can edit it properly (and still have it dealt to the browser, remember to empty caches each reload).
Put a console log line with an unusual string to the code that makes the code in question easy to find.
It will likely make a call to _toConsumableArray. Due to bundling, the _toConsumableArray method will be defined multiple times in several scopes, so either debug all of them or find out which one is the one called here.
Then use either the chrome debugger or console.log to find out what Symbol and Symbol.iterator are in the local and global scope. Symbol should evaluate to a native function, but locally it won't. Instead it contains some string, maybe something with jcomp, that you can search the page sources file for again, in the browser dev window. Somehere there needs to be a spot where this string was created and once You find that file, You have Your guilty party.
