### ISSUE TITLE
@babel/plugin-proposal-class-properties explicitly assigns properties that are declared, without a value, as `undefined`.

### ISSUE THREAD

**Issue by rgraffbrd** [babel/babel#9996]
## Bug Report

**Current Behavior**
`@babel/plugin-proposal-class-properties` is executing an assignment to `undefined` for class properties that are declared without a default value. (The previous plugin `babel-plugin-transform-class-properties` did/does not do this.)

**Input Code**
See this PR: https://github.com/resistdesign/resistdesign-babel-config/pull/3

```js
class A {
  constructor(config = {}){
    Object.assign(config);
  }
}

class B extends A {
  declaredAsUndefined = undefined;
  
  declaredWithNoDefault;
  
  constructor(){
    super({
      declaredAsUndefined: true,
      declaredWithNoDefault: true
    });
  }
}

const b = new B();

b.declaredAsUndefined; // undefined <- Good
b.declaredWithNoDefault; // undefined <- Bad
```

**Expected behavior/code**
There should be **no** assignments for class properties declared without a default value.

**Babel Configuration (.babelrc, package.json, cli command)**
All tools, all environments.

```js
// See code above.
```

**Environment**
- Babel version(s): Any
- Node/npm version: 8.4.x
- OS: OSX
- Monorepo: no
- How you are using Babel: mocha (require register), webpack 4

**Possible Solution**
Revert it back to the old code??? Not sure. Not clear on the spec here either TBH.

**Additional context/Screenshots**
None.

**Comment by nicolo-ribaudo** [comment]
This is the behavior defined by the spec. If you don't that field to be assigned to undefined, you can either remove it or declare it as `declaredWithNoDefault = this.declaredWithNoDefault`.

Anyway, there is a PR to match the behavior you want: https://github.com/babel/babel/pull/9141
