### ISSUE TITLE
Typescript enum names violate uid generation

### ISSUE THREAD

**Issue by Wolvereness** [babel/babel#9997]
## Bug Report

**Current Behavior**

`generateUid` fails to consider members of an `enum` via *typescript*.

**Input Code**

```typescript
enum E {
  _E,
}
```

```js
if ("_E" === path.scope.generateUid("E")) throw "Not actually unique";
```

**Expected behavior/code**

To generate a Uid that considers the enum values

**Babel Configuration (.babelrc, package.json, cli command)**

`TEST_ONLY=babel-plugin-transform-typescript make test-only`

**Environment**
- Babel version(s): 165ef2941694184d83307b41d311751bd3dabae0
- Node/npm version: Node v8.12.0
- OS: Windows 10
- Monorepo: ??
- How you are using Babel: see above

**Additional context/Screenshots**

Found this while fixing up the typescript namespace implementation.

**Comment by edsrzf** [comment]
Hi, just doing some issue triage. I think I understand what's being reported, but does it actually cause any problems? The TypeScript enum in the report roughly compiles into:

```js
var E = {
  _E: 0
}
```

It seems to me that we don't need to worry about generating an identifier that collides with `_E` because the enum only introduces an `E` binding to the variable scope, not `_E`.

If I'm missing something, then perhaps we could clear it up with a reproduction or a description of what problem this might cause in practice?

**Comment by Wolvereness** [comment]
I'd suspect this would be an issue if a transform was attaching something to the enum itself, especially auto-generating more values. I reported the issue because it violates the assumption that a generated uid is unique to a file. Whether or not a variable scope matters is a question of how many turtles down you go into implementation.

It's not pertinent to anything I'm working on; I just happened to find it when writing the unit tests for the namespace stuff. If it's worth addressing I leave to the discretion of the project.

**Comment by nicolo-ribaudo** [comment]
As mentioned by @edsrzf, Babel already doesn't guarantee that the uid will not clash with object/class properties.
`generateUid` generated an unique id for a variable, guaranteed not to collide with any other binding.

**Comment by JLHwung** [comment]
If you are writing a plugin, you can construct your own `generateUid` function that accepts an optional denylist. For example we generate a uid that does not collide with private class elements in `proposal-class-static`:

https://github.com/babel/babel/blob/bab5c62f907b6f90d094531ab22aa0a86d7c35a5/packages/babel-plugin-proposal-class-static-block/src/index.js#L4-L20
