### ISSUE TITLE
Decorators plugin throws error in ie 11

### ISSUE THREAD

**Issue by quetzalsly** [babel/babel#9999]
## Bug Report

**Current Behavior**
ie 11 fully fails with `throw new TypeError("@@toPrimitive must return a primitive value.")}`

**Input Code**
```js
@customElement('test')
class TestApp extends connect(store)(LitElement)
{
  @property({ type: String }) _Test = 'Hello';
```

**Expected behavior/code**
It's meant to not throw an error.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "browserslist": [
    ">= 0.2%",
    "not dead",
    "not ie <= 10",
    "not op_mini all",
    "ie 11",
    "chrome 41"
  ],

  "use strict";

const {minify} = require('terser');

module.exports = {
  presets: [
    ['@babel/env', {
      useBuiltIns: 'usage',
      loose:       true,
      modules:     'amd',
      corejs:      3
    }]
  ],
  plugins: [
    ['template-html-minifier', {
      modules: {
        'lit-html': ['html', 'svg'], // lit-html
        'lit-element': ['html', 'svg'], // LitElement
        '@polymer/polymer/polymer-element': ['html'], // Polymer 3 - exported from Polymer Element
        '@polymer/polymer/lib/utils/html-tag.js': ['html'], // Polymer 3 - exported from utils (used by PolymerElements family)
      },
      htmlMinifier: {
        caseSensitive:      true,
        collapseWhitespace: true,
        removeComments:     true,
        sortAttributes:     false,
        sortClassName:      false,
        minifyCSS:          true,
        minifyJS:           (code) => minify(code).code,
        useShortDoctype:    true
      },
    }],
    ['@babel/transform-runtime', {
      sourceType: 'unambiguous',
      corejs: 3
    }],
    ['@babel/proposal-decorators', {
      decoratorsBeforeExport: true,
    }],
    ['@babel/proposal-class-properties', {
      loose: false
    }],
    ['@babel/proposal-object-rest-spread'],
    ['@babel/syntax-dynamic-import']
  ]
};

"devDependencies": {
    "@babel/core": "7.4.4",
    "@babel/plugin-proposal-class-properties": "7.4.4",
    "@babel/plugin-proposal-decorators": "7.4.4",
    "@babel/plugin-proposal-object-rest-spread": "7.4.4",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-runtime": "7.4.4",
    "@babel/preset-env": "7.4.4",
    "acorn": "6.1.1",
    "babel-eslint": "11.0.0-beta.0",
    "babel-loader": "8.0.6",
    "babel-loader-exclude-node-modules-except": "1.0.1",
    "babel-plugin-template-html-minifier": "3.0.0",

cli is just webpack + webpack dev server using the configs.
}
```

**Environment**
- Babel version(s): 7 4 4
- Node/npm version: 12.2
- OS: win7
- Monorepo: yes
- How you are using Babel: loader

**Comment by nicolo-ribaudo** [comment]
How are those decorators defined?

**Comment by quetzalsly** [comment]
What do you mean by defined? I am using lit-element code. On their github page they give the exact code I used, it's just using the decorator + properties. https://github.com/Polymer/lit-element

**Comment by lamianbu** [comment]
I have the same issue.

open-wc lit-element rollup:

```
  const plugins = [
    ["@babel/plugin-proposal-decorators", { decoratorsBeforeExport: false }],
    "@babel/plugin-proposal-class-properties"
  ];
```

ie 11 fully fails with throw new TypeError("@@toPrimitive must return a primitive value.")}

**Comment by lamianbu** [comment]
_const standardProperty =
    (options: PropertyDeclaration, element: ClassElement) => {
      // When decorating an accessor, pass it through and add property metadata.
      // Note, the `hasOwnProperty` check in `createProperty` ensures we don't
      // stomp over the user's accessor.
      if (element.kind === 'method' && element.descriptor &&
          !('value' in element.descriptor)) {
        return {
          ...element,
          finisher(clazz: typeof UpdatingElement) {
            clazz.createProperty(element.key, options);
          }
        };
      } else {
        // createProperty() takes care of defining the property, but we still
        // must return some kind of descriptor, so return a descriptor for an
        // unused prototype field. The finisher calls createProperty().
        return {
          kind: 'field',
          key: Symbol(),
          placement: 'own',
          descriptor: {},
          // When @babel/plugin-proposal-decorators implements initializers,
          // do this instead of the initializer below. See:
          // https://github.com/babel/babel/issues/9260 extras: [
          //   {
          //     kind: 'initializer',
          //     placement: 'own',
          //     initializer: descriptor.initializer,
          //   }
          // ],
          initializer(this: {[key: string]: unknown}) {
            if (typeof element.initializer === 'function') {
              this[element.key as string] = element.initializer.call(this);
            }
          },
          finisher(clazz: typeof UpdatingElement) {
            clazz.createProperty(element.key, options);
          }
        };
      }
    };

const legacyProperty =
    (options: PropertyDeclaration, proto: Object, name: PropertyKey) => {
      (proto.constructor as typeof UpdatingElement)
          .createProperty(name, options);
    };

/**
 * A property decorator which creates a LitElement property which reflects a
 * corresponding attribute value. A `PropertyDeclaration` may optionally be
 * supplied to configure property features.
 *
 * @ExportDecoratedItems
 */
export function property(options?: PropertyDeclaration) {
  // tslint:disable-next-line:no-any decorator
  return (protoOrDescriptor: Object|ClassElement, name?: PropertyKey): any =>
             (name !== undefined) ?
      legacyProperty(options!, protoOrDescriptor as Object, name) :
      standardProperty(options!, protoOrDescriptor as ClassElement);
}_

because of Symbol(), ie11 is err

**Comment by emilio-martinez** [comment]
I just bumped into this issue as well—also with LitElement decorators. (cc @justinfagnani, FYI)

**Comment by borblanto** [comment]
We had the same problem with LitElement decorators. 
But, this babel configuration works for us:

```
{
  "presets": [
    "@babel/preset-typescript"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
}
```

**Comment by emilio-martinez** [comment]
Just to clarify, setting the decorators plugin to "legacy" merely side-steps the issue for LitElement in particular, but doesn't actually solve this issue. As also noted above, LitElement's decorators handle both current proposal and legacy cases, although their handling of legacy is more meant for Typescript (as in tsc) decorators.

**Comment by mmirca** [comment]
I got some issues on IE11 using LitElement decorators too. In the end I manage to make it work using this webpack config for babel:

```javascript
{
  module: {
    rules: [
      {
        test: /\.(ts|js)$/,
        exclude: /node_modules\/(?!(lit-element|lit-html))/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-typescript',
              ['@babel/preset-env', {
                targets: {
                  browsers: '> 0.25%, IE 11, not dead',
                }
              }]
            ],
            plugins: [
              ['@babel/plugin-proposal-decorators', {
                decoratorsBeforeExport: true
              }],
              ['@babel/plugin-proposal-class-properties'],
              ['@babel/plugin-transform-runtime', {
                regenerator: true
              }]
            ]
          }
        }
      }
    ]
  }
}
```

And by adding the `find` polyfill from core-js to the entry:

```javascript
{
  entry: [
    path.join(__dirname, 'node_modules/core-js/features/array/find'),
    path.join(__dirname, 'src/index.ts')
  ]
}
```

**Comment by nicolo-ribaudo** [comment]
Hi! The decorators proposal has been completely rewritten and we are discontinuing maintenance of the 2018-09 version (which will then be completely removed in Babel 8). You can migrate to the Stage 3 version of the [proposal](https://github.com/tc39/proposal-decorators/) by using `version: "2021-12"`.
